### ISSUE TITLE
[android, question] 5.2.0 is it available?

### ISSUE THREAD

**Issue by StasDoskalenko** [mapbox/mapbox-gl-native#10003]
Hey, guys!

Thanks for an awesome library. I have only one question. How can I get android library version 5.2.0? As I understand it's not available at maven yet. Because I need such feature as image overlay.

I'm new to android development so can some one share the compiled library with me? Thanks!

**Comment by jfirebaugh** [comment]
No, 5.2.0 has not yet been released. The most recent version is 5.1.3.

**Comment by StasDoskalenko** [comment]
@jfirebaugh thanks, I figured out how to compile and use **aar** library in my project :)
