### ISSUE TITLE
Avoid onUpdate calls while loading style

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#10007]
When we're loading a style, we're repeatedly calling APIs like `addLayer`, `addLight` etc. as we parse the stylesheet. Every call in turn triggers a call to `Map::Impl::onUpdate`, which schedules a render frontend update. We should instead pause these calls while loading a stylesheet and only trigger one once loading completed.

/cc @ivovandongen @jfirebaugh

**Comment by jfirebaugh** [comment]
IIRC @brunoabinader made some efforts towards this in #9884 but had to back them out because of test failures.
