### ISSUE TITLE
Android: offline region download too big

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#10004]
When downloading an offline region in the Android SDK, I've found 2 issues last weeks:

- I'm setting correct bounds (LatLngBounds), but there is always a much bigger area that is downloaded. Is this a known issue?

- Sometimes the 'onError' method is called with this error 'SERVER_ERROR' - 'timeout' while downloading an offline region.

**Comment by jfirebaugh** [comment]
@nijs9, please use the issue template when filing issues.
