### ISSUE TITLE
Downloaded offline region is much larger than defined region

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#10005]
**Platform:* Android*
**Mapbox SDK version:* 5.1.3*

### Steps to trigger behavior

 1. Define bounds (NE and SW coordinate) for downloading offline region
 2. Start download (offlineManager.createOfflineRegion)
 3. Disable internet connection on device and check downloaded area

### Expected behavior

Just the area defined by NE  and SW coordinate downloaded for offline use.

### Actual behavior

A much bigger area is downloaded. I'm sure I configure the right NE and SW coordinate. 
This is how I define the region to download:

           `LatLng NE = new LatLng(maxLat, maxLon); // Northeast
            LatLng SW = new LatLng(minLat, minLon); // Southwest

            // Set up the OfflineManager
            OfflineManager offlineManager = OfflineManager.getInstance(RoutePlanner.this);

            // Create a bounding box for the offline region
            LatLngBounds latLngBounds = new LatLngBounds.Builder()
                    .include(NE) // Northeast
                    .include(SW) // Southwest
                    .build();

            // Define the offline region
            OfflineTilePyramidRegionDefinition definition = new OfflineTilePyramidRegionDefinition(
                    styleurl,
                    latLngBounds,
                    9,
                    15,
                    RoutePlanner.this.getResources().getDisplayMetrics().density);`

**Comment by tobrun** [comment]
the offline region is build out of tiles. When you download a region it will download all the tiles found in your LatLngBounds, even if your region only covers a little part of a tile, the full tile will be downloaded. Closing as this is known and expected behaviour.
