### ISSUE TITLE
Xcode 9: setAccessibilityIgnoresInvertColors: is only available on iOS 11.0 or newer

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#10010]
**Platform:** Xcode 9
**Mapbox SDK version:** v3.6.3

The approach we took to the inverted color opt-out from #9876 is throwing warnings in Xcode 9:

> `MGLMapView.mm:482:97: 'setAccessibilityIgnoresInvertColors:' is only available on iOS 11.0 or newer`

Instead, it wants us to use the `@available()` check (which we can’t, to stay compatible with Xcode 8).

![screen shot 2017-09-15 at 6 47 53 pm](https://user-images.githubusercontent.com/1198851/30506020-6b6ba276-9a46-11e7-912c-f049ee9c8317.png)

/cc @jmkiley

**Comment by boundsj** [comment]
Fwiw, in https://github.com/mapbox/mapbox-gl-native/pull/9995 we [suppressed the warning](https://github.com/mapbox/mapbox-gl-native/pull/9995/files#diff-20502b6bc02986a4398d0da84b2d4b94R972) instead of using the new `@available()` check.

**Comment by jmkiley** [comment]
Addressed in #10425
