### ISSUE TITLE
Will cached tiles ever refresh?

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#10014]
**Platform:*Android*
**Mapbox SDK version:*5.1.3*

### Steps to trigger behavior

 1. Change and publish existing custom style in Mapbox Studio online
 2. Wait some hours
 3. Check map in mobile app

### Expected behavior

Changes made hours ago are visible in mobile app.

### Actual behavior

Changes are not visible, unless you remove the app and reinstall. Cached tiles in the app are not updated, even after some hourse they will not update. Is there a possibility to clear cache manually? I've read something of changing cache header, but how to perform this?

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
