### ISSUE TITLE
Check if offline map download is still running and resume if not

### ISSUE THREAD

**Issue by accursedm0** [mapbox/mapbox-gl-native#10018]
Sorry if I'm just missing something obvious here but I fail to find any information on these two essential issues regarding offline maps.

1. If I already started an offline map data download and user leaves activity/app and returns, then howto check if the previously started download is still running? If I follow the offline examples then the download is started again and again from scratch resulting in an array of offline regions.
2. If the download is not running anymore but was incomplete, then how to resume the partial download in order to not having to start all over again?

Here's my code example with the two issues marked as TODOs.

```
offlineRegions[0].getStatus(new OfflineRegion.OfflineRegionStatusCallback() {

  @Override
  public void onStatus(OfflineRegionStatus offlineRegionStatus) {
    if( offlineRegionStatus.isComplete() ){
      Log.e(TAG, "Offline Map Data found, not downloading it again");
    } else {
      // TODO: 1 howto check if offline region is still downloading
      if( mOfflineDataDownloadRunning ){
        Log.e(TAG, "Offline Map Data download still running, not downloading it twice");
      } else {
        Log.e(TAG, "Map Data found but incomplete, resume download");
        // TODO: 2 howto resume download
     }
    }
  }
  
  @Override
  public void onError(String error) {
    Log.e(TAG, "onStatusError: " + error + ", try downloading map");
    downloadOfflineMap();
  }

});
```

** Platform: Android **
** Mapbox SDK version: 5.1.3 **

**Comment by jfirebaugh** [comment]
Offline downloads are not automatically reactivated when the process is restarted. However, if you reactivate the download, it will not redownload already-downloaded resources. (It does need to check the database for previous resources, and this process will still be reflected in the progress notifications.)

To check the current status of an offline download, use [`OfflineRegion.getStatus`](https://www.mapbox.com/android-docs/api/map-sdk/5.1.3/com/mapbox/mapboxsdk/offline/OfflineRegion.html#getStatus-com.mapbox.mapboxsdk.offline.OfflineRegion.OfflineRegionStatusCallback-)

**Comment by accursedm0** [comment]
Thank you for the quick response.

So the download is still running if `offlineRegionStatus.getDownloadState() == OfflineRegion.STATE_ACTIVE` correct?

To reactivate the download of a region, is it enough to set the download state?
 `offlineRegion.setDownloadState(OfflineRegion.STATE_ACTIVE);`

```
offlineRegions[0].getStatus(new OfflineRegion.OfflineRegionStatusCallback() {

  @Override
  public void onStatus(OfflineRegionStatus offlineRegionStatus) {
    if( offlineRegionStatus.isComplete() ){
      Log.e(TAG, "Offline Map Data found, not downloading it again");
    } else {
      // TODO: 1 howto check if offline region is still downloading
      if( offlineRegionStatus.getDownloadState() == OfflineRegion.STATE_ACTIVE ){
        Log.e(TAG, "Offline Map Data download still running, not downloading it twice");
      } else {
        Log.e(TAG, "Map Data found but incomplete, resume download");
        // TODO: 2 howto resume download
        offlineRegions[0].setDownloadState(OfflineRegion.STATE_ACTIVE);
     }
    }
  }
  
  @Override
  public void onError(String error) {
    Log.e(TAG, "onStatusError: " + error + ", try downloading map");
    downloadOfflineMap();
  }

});
```

**Comment by jfirebaugh** [comment]
Yes, correct on both questions.

**Comment by accursedm0** [comment]
Thank you very much, this seems to work.
I'd humbly suggest to add this point to the offline map examples. Super useful.
