### ISSUE TITLE
404 'mapbox' is not in the npm registry

### ISSUE THREAD

**Issue by multimolti** [mapbox/mapbox-gl-native#10023]
Hello,

I'm simply trying to install tileserver-gl via npm via the following command:
`sudo npm install -g tileserver-gl`
but the packages mapbox/vector-tile/1.3.0, mapbox/mapbox-gl-native/3.5.4 and mapbox/sphericalmercator/1.0.5 don't seem to be in the registry. 

**Platform:** Ubuntu 14.04 LTS
**Mapbox SDK version:**

### Steps to trigger behavior

 1. run `sudo npm install -g tileserver-gl`

### Expected behavior

Successful installation of tileserver-gl including various mapbox packages

### Actual behavior

```
npm http 404 https://registry.npmjs.org/mapbox/vector-tile/1.3.0
npm ERR! 404 'mapbox' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "tileserver-gl"
npm ERR! cwd /home/username
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code E404
```

**Comment by jfirebaugh** [comment]
The `tileserver-gl` module is not written or maintained by Mapbox. It looks like you should report issues to https://github.com/klokantech/tileserver-gl.
