### ISSUE TITLE
"MGLOfflinePackState wrong for 'old' packs" or "How to find out if pack is already downloaded"

### ISSUE THREAD

**Issue by dr-falsch** [mapbox/mapbox-gl-native#10025]
**Platform: iOS**
**Mapbox SDK version: 3.6.3**

### Steps to trigger behavior

If you take your offline packs example (https://www.mapbox.com/ios-sdk/examples/offline-pack/) and add the following code in `offlinePackProgressDidChange` everything works fine:

```
if let pack = notification.object as? MGLOfflinePack,
    let userInfo = NSKeyedUnarchiver.unarchiveObject(with: pack.context) as? [String: String] {
    print( pack.state.hashValue )
```

Which means you get `2` (`MGLOfflinePackStateActive`) while the download is working and `3` (`MGLOfflinePackStateComplete`) when it's finished.

But if you wanna check if "old" packs were already downloaded, I always get state `0` (`MGLOfflinePackStateUnknown`). You can check it e.g. if you add the following code in your `startOfflinePackDownload`:

```
if let packs = MGLOfflineStorage.shared().packs {
    for pack in packs {
        if let userInfo = NSKeyedUnarchiver.unarchiveObject( with: pack.context ) as? [String : String] {
            print( userInfo[ "name"]  )
        }
        log.error( pack.state.hashValue )
    }
}
```

### Expected behavior

I expected to get the real states and not only 0 (`MGLOfflinePackStateUnknown`).

### Actual behavior

I always get state 0 (`MGLOfflinePackStateUnknown`) for "old" packs.

So, how can I find out if my offline packs are already downloaded?

**Comment by jfirebaugh** [comment]
See [the documentation for `MGLOfflinePackStateUnknown`](https://www.mapbox.com/ios-sdk/api/3.7.0-alpha.1/Enums/MGLOfflinePackState.html#/c:@E@MGLOfflinePackState@MGLOfflinePackStateUnknown).
