### ISSUE TITLE
[ios] Heading arrow should be larger

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#10028]
**Platform:** iOS
**Mapbox SDK version:** v3.6.3

Initial feedback is that the permanent heading arrow is a bit too small and that it should be easier to read at a natural distance.

<img src='https://user-images.githubusercontent.com/1198851/29946988-90631e24-8e75-11e7-8ce4-a84a26fa0e4f.png' width=275>

_the original_

/cc @mayagao

**Comment by mayagao** [comment]
urmm even bigger? 
![screen shot 2017-09-19 at 3 17 21 pm](https://user-images.githubusercontent.com/5186564/30610881-a78770f0-9d4d-11e7-996d-02d3b0604c3c.png)

**Comment by stonetip** [comment]
I'd construct it as follows: A triangle behind a circle with its outermost point equal in distance to the radius of the circle. The other two points tangent to the circle. Then use a stroke on the circle 1/5th the diameter. There are a many older users I talk to who can barely see direction indicators used by Google, et al. Others comment on not being able to see a pointer while in motion, e.g. running.

![location pointer](https://user-images.githubusercontent.com/3766798/31848253-1253b096-b5eb-11e7-93c8-d24f3c3cf58f.png)

**Comment by yueno12** [comment]
+1

**Comment by Feyewon** [comment]
How to deal this question in v3.7.3,Please.

**Comment by friedbunny** [comment]
The current heading indicator is being made somewhat larger in #11337. If this design doesn’t suit your purposes or if you can’t wait until v3.7.6, check out [this example](https://www.mapbox.com/ios-sdk/examples/user-location-annotation/) to see how to implement your own user location annotation with heading indicator.

**Comment by stonetip** [comment]
As shown in #11337 that's definitely an improvement. Moreover, I really appreciate the link to the custom example. We have a nav indicator that's radically different since it's meant to be visible when trail running, etc. Thanks!

**Comment by marconealberto** [comment]
not related but I haven't found anything on the topic: is this implemented for Android?

**Comment by friedbunny** [comment]
Fixed in #11337 and `ios-v3.7.6`.

@marconealberto please feel free to open a new issue requesting this feature on Android. 🙇
