### ISSUE TITLE
Zoom-in and zoom-out do not invoke any onCameraXXX callbacks

### ISSUE THREAD

**Issue by akoprow** [mapbox/mapbox-gl-native#10022]
**Platform:**  Android
**Mapbox SDK version:**  5.1.3

### Steps to trigger behavior
 1. Double-click with a mouse to trigger zoom-in on the map.

### Expected behavior
Some onCameraXXX callback should be invoked.

### Actual behavior
As far as I can see the only callback being called is [OnCameraChangeListener](https://www.mapbox.com/android-docs/api/map-sdk/5.1.0/com/mapbox/mapboxsdk/maps/MapboxMap.OnCameraChangeListener.html).  How is one supposed to handle those events given that aforementioned callback is deprecated?

**Comment by Guardiola31337** [comment]
Hey 👋 @akoprow thanks for reaching out and report your question.

With `5.1.0` release, we introduced a new system around camera notifications 👀 [Camera Change Listener v2.0](https://github.com/mapbox/mapbox-gl-native/pull/8644) and [Camera start, ongoing, and end events notifications](https://github.com/mapbox/mapbox-gl-native/issues/6350) tickets.

There is an example in the test app ([`CameraPositionActivity`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/CameraPositionActivity.java)) showing how to use the new CameraChangeListener API that you can check.

Going ahead and close this as the question is answered. Feel free to open new tickets if you have any other questions 😉

**Comment by akoprow** [comment]
Let me clarify.  I'm aware of the new API and am using it.  I created a simple app logging to Logcat whenever any of the camera callbacks fires.  Everything works nicely *except* when I add zoom-in/out icons to the map:

`mMap.getUiSettings().setZoomControlsEnabled(true);`

Zooming with double clicking the map triggers a series of callback and eventually `OnCameraIdle` when the camera move is finished (this is the event I'm interested in and this is the behavior I'd expect).

However, clicking the zoom-in/out buttons *only* triggers a series of `OnCameraMoveStarted` (never triggering `OnCameraIdle`).

I doubt this is "Working as intended"?

**Comment by tobrun** [comment]
Thank you for the report @akoprow, fix for this in #10221.

**Comment by lilykaiser** [comment]
Can this be closed?
