### ISSUE TITLE
MGLMapView turns black when returning from another UIViewController.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1003]
This consistently reproduces. Here is how to reproduce it.

1. From the UIViewController that hold MGLMapView push a new UIViewController
2. Tap Back

Screen is black after tapping back. 

This is what I have tried to figure out the root cause so far. Please note #2 (Issue disappears when breakpoint inserted inside asyncRender callback function).

1.) I tried forcing rerender via Map::update from viewWillAppear (UIThread) but it does not seem to  help.
2.) If I put breakpoint inside asyncRender to debug whether the render is actually happening, the issue disappears.

**Comment by robipresotto** [comment]
+1

**Comment by incanus** [comment]
@kkaefer Do you think this might be related to your recent missing frame fix? 

@mb12 @robipresotto Can you see if the situation changes without https://github.com/mapbox/mapbox-gl-native/commit/47ede853c4c0dd8e953f3ee98b807f044d178d76, which fixed the above issue recently?

**Comment by mb12** [comment]
@incanus Forcing rerender via Map::update from UIViewController::viewDidAppear addresses the issue. I will keep on it and let you know if the issue reappears with this change. I think this also explains why putting breakpoint in asyncRender was causing the issue to disappear.
 
When I had it in viewWillAppear, it wasn't helping until I put a breakpoint in asyncRender. Putting breakPoint in asyncRender was probably forcing render to happen after viewDidAppear.

**Comment by robipresotto** [comment]
[[MGLMapView alloc] initWithFrame: styleJSON: accessToken:];

I receive this error when the user go out of the app and back to the app,
[ERROR] Setup: (-1) loading style failed: The operation couldn’t be completed. (NSURLErrorDomain error -1002.)

The error turns the map view black in my case

ideas?

**Comment by robipresotto** [comment]
The StyleURL from this method is empty when you close the app and re-open the app...

void Map::prepare() {
    assert(std::this_thread::get_id() == mapThread);

    if (!style) {
        style = std::make_shared<Style>();

        env->request({ Resource::Kind::JSON, styleURL}, [&](const Response &res) {
            if (res.status == Response::Successful) {
                // Calculate the base
                const size_t pos = styleURL.rfind('/');
                std::string base = "";
                if (pos != std::string::npos) {
                    base = styleURL.substr(0, pos + 1);
                }

                setStyleJSON(res.data, base);
            } else {
                Log::Error(Event::Setup, "loading style failed: %s", res.message.c_str());
                std::cout << "styleURL " << styleURL;
            }
        });
    }

**Comment by robipresotto** [comment]
@mb12 how are you updating the map from uiviewcontroller? for me still the same problem...

**Comment by incanus** [comment]
@mb12 @robipresotto How is this looking to you currently on `master`?

**Comment by mb12** [comment]
I think the issue that I've reported and the one @robipresotto  is referring to are different issues.
I can try the latest master tomorrow morning or on Monday but I don't think the issue is fixed since its related to UIViewController lifecycle.

1.) From MBXViewController, push/present an new UIViewController.
2.) Tap on "Back". 

The MapScreen turns black unless touched / re-rendered. I am able to work around it by forcing re-render from viewDidAppear.

**Comment by robipresotto** [comment]
okay, can be! i can open a new issue.

**Comment by 1ec5** [comment]
Doesn’t currently seem to reproduce with push or show segues in storyboards. Let’s see if it reproduces programmatically…

**Comment by 1ec5** [comment]
@mb12, I still can’t reproduce the issue on master (iOS 8.3 iPhone 6 Simulator, iOS 8.2 iPhone 5 Simulator, iOS 8.2 iPhone 6):

![push](https://cloud.githubusercontent.com/assets/1231218/6905618/136db5a6-d6de-11e4-9f8f-e27722796842.gif)

Can you share the code you’re working with?

**Comment by mb12** [comment]
I've the following code in the UIViewController:

- (void)viewDidAppear:(BOOL)animated {
     [_mglMapView triggerUpdate];
}

triggerUpdate is just a wrapper around Map::triggerUpdate in MGLMapView.

-(void) triggerUpdate {
    if(mbglMap) {
        mbglMap->triggerUpdate();
    }
}

**Comment by mb12** [comment]
This bug is fixed in the latest repo. Latest MGLMapView uses drawInRect to call renderSync from drawInRect:.
I've an old repo where the bug reproduces because renderSync in missing from drawInRect:.

Thank you very much for following up on this and fixing it properly.

**Comment by 1ec5** [comment]
Good to hear it’s working now!
