### ISSUE TITLE
Android: build a new Docker image for Circle CI

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#10046]
There are a few updates to the Android SDK/NDK, so we should build a new docker image that has these preinstalled:

* We're currently using the support lib 25.4.0 (26 is also out)
* A CMake update is in their repository
* Lots of other small updates
* NDK version r16

Instead of manually doing this update, we should move our image build process to Circle CI as well to simplify updates in the future.

/cc @tobrun

**Comment by tobrun** [comment]
done in https://github.com/mapbox/mapbox-gl-native/pull/10474
