### ISSUE TITLE
MapBoxSDK for iOS is periodically making a request to the custom StyleJSON url

### ISSUE THREAD

**Issue by f2m2rd** [mapbox/mapbox-gl-native#10049]
**Platform:**  `iOS`

**Mapbox SDK version:** `3.6.3`

### Issue

The MapBoxSDK for iOS is periodically making a request to the custom StyleJSON url. 

As a result, if the StyleJSON contains content that is dynamic, such as a filter function with a timestamp, then a map refresh is triggered.   This is causing the map to appear to flicker.

### Steps to trigger behavior

 1. Clone the & Setup the sample iOS App `(X-Code 9 Required)`  [https://github.com/airmap-scratch/MapBox-JSONStyle-Issue]()
 	1. Run `pod install`
 	2. Open `maptest.xcworkspace`
 	3. Update the `MapBox Token` & `AirMap APIKey`
5. Run a Proxy (i.e. Charles Proxy) to see the requests.
6. Run the App
 
### Expected behavior
The map should only refresh once, when the StyleJSON loads.

### Actual behavior
The SDK continues to request the StyleURL and the map continues to refresh when a 200 response is returned.

Here is a video: [https://airmap.box.com/s/maxc7umuklgaz2mt479gzcx9znzw5uei]()

**Comment by jfirebaugh** [comment]
This is intended behavior. The SDK requests the style on an interval determined by the `Expires` or `Cache-Control` headers of the response. If you do not want the style to be refreshed, configure the serve to send headers with a long expiration time, or with no `Expires` or `Cache-Control` headers.

**Comment by f2m2rd** [comment]
This doesn’t seem to be happening on Android.  Is this behavior only Intended for iOS?
