### ISSUE TITLE
HTTP: Fix freshness/usable calculation for requests that don't provide Cache-Control/Expires headers

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#10044]
We're currently treating tiles that don't have either header set as unusable when `must-revalidate` is set as well. Instead, [we should use a heuristic](https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.2) to determine whether it is still fresh.

**Comment by jfirebaugh** [comment]
This sounds good when making a new initial request for a resource. However, we should ensure that any heuristic we add does not change the revalidation behavior for resources that are "in use" (have an outstanding `AsyncRequest`). People are likely relying (ref #10049) on the current behavior, which is not to revalidate until there is a new "initial" request (e.g. new `Map` object, or tile comes back into viewport).
