### ISSUE TITLE
Very slow install using cocoapods

### ISSUE THREAD

**Issue by eriadam** [mapbox/mapbox-gl-native#10056]
**Platform:** iOS
MacOS Sierra 10.12.6

**Mapbox SDK version:** 3.6.2

### Steps to trigger behavior

 1. pod install

It takes forever to download the package from S3. After some time the download speed just drops to 0.

(My location is Vienna, Austria. We have a 260-something MBit/sec download speed.)

-> Installing Mapbox-iOS-SDK (3.6.2)
 > Http download
   $ /usr/bin/curl -f -L -o /var/folders/g3/pdwt4t_n291cjyplbhs76nl80000gn/T/d20170925-27747-11hk3n7/file.zip
   https://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-3.6.2-dynamic.zip --create-dirs --netrc-optional
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
    18 67.6M   18 12.8M    0     0  91128      0  0:12:58  0:02:27  0:10:31 52463

### Expected behavior

Download in a timely manner.

### Actual behavior

Download takes forever, stops after a while.

**curl: (56) SSLRead() return error -9806**

   https://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-3.6.2-dynamic.zip --create-dirs --netrc-optional
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
    33 67.6M   33 22.5M    0     0  52020      0  0:22:44  0:07:34  0:15:10     0

**Comment by fabian-guerra** [comment]
Hi @eriadam. Thank you for using Mapbox. I am sorry to hear you are having some issues. Our servers look ok and I am able to download our SDK without problems. Could it be related to your ISP?

I am closing this because this repo is for bugs and crashes within the SDK itself.
