### ISSUE TITLE
Support API level 14

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#10057]
We currently support API level 15 as our min SDK. However, we hear from developers that it'd be useful to lower that requirement to API level 14. This will require changes to some of our dependencies that also require 15+ (https://github.com/mapbox/mapbox-gl-native/issues/9403 would be a requirement). Let's use this ticket to research whether this is a possibility.

Related ticket for MAS: https://github.com/mapbox/mapbox-java/issues/575

cc: @tobrun  @Guardiola31337

**Comment by Guardiola31337** [comment]
Fixed via https://github.com/mapbox/mapbox-gl-native/pull/10355

Closing.
