### ISSUE TITLE
MapBoxMetrixClient.o error

### ISSUE THREAD

**Issue by indejun** [mapbox/mapbox-gl-native#10052]
**Platform:**
Unity (iOS)
**Mapbox SDK version:**
MapBox Unity 1.1.0
### Steps to trigger behavior

 1. By using MapBox Unity 1.1.0, we were try
![mapbox_arm64error_2_20170925](https://user-images.githubusercontent.com/32251629/30789393-3f915f82-a1e0-11e7-912f-b968fa5ad2d3.jpg)
![mapbox_arm64error_1_20170925](https://user-images.githubusercontent.com/32251629/30789394-3f91e330-a1e0-11e7-9a95-1f5baec4b88a.jpg)

ing to export to iOS build
 2. During the process, after exporting by xcode and linking process, we've received the error message
    "MapBoxMetrixClient.o cannot be defined".
 3. Our developer said that file(MapBoxMetrixClient.o) is not in MapBox API which Imported from Unity

**Comment by Guardiola31337** [comment]
Hi @indejun 👋
Thanks for reaching out and report your problem. I redirected your issue to https://github.com/mapbox/mapbox-unity-sdk/issues/254 so you can keep track of it there.

Closing.
