### ISSUE TITLE
Use bilinear scaling when resizing the entire sprite atlas

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1007]
Now that we have it (#843), we should use bilinear scaling when resizing the entire sprite atlas. Resizing the atlas occurs when the user changes the pixelRatio of the Map (e.g. when moving the window from a non-retina screen to a retina screen and vice versa).

**Comment by jfirebaugh** [comment]
Changing the pixel ratio of the map is no longer supported, so this isn't applicable.
