### ISSUE TITLE
Zooming gestures problem on 5.1.4

### ISSUE THREAD

**Issue by Petrulak** [mapbox/mapbox-gl-native#10082]
**Platform:Android**
**Mapbox SDK version:5.1.4**

### Steps to trigger behavior

 1. Add mapbox 5.1.4 map into your view. Use following settings.
```
        mapBoxMap.uiSettings.isRotateGesturesEnabled = false
        mapBoxMap.uiSettings.isLogoEnabled = false
        mapBoxMap.uiSettings.isAttributionEnabled = false
        mapBoxMap.uiSettings.isTiltGesturesEnabled = false
```
 2. Run the app
 2. Start zooming with 2 fingers.

### Expected behavior
The map should zoom in/out.
### Actual behavior
The map doesn't zoom in/out. Once it zooms in out, it's not smooth at all. 
Seems like it jumps from one frame to second one.
**Please see attached video**
Device on the video is One plus 5
[mapbox_zooming_5_1_4.mp4.zip](https://github.com/mapbox/mapbox-gl-native/files/1340157/mapbox_zooming_5_1_4.mp4.zip)

**Comment by tobrun** [comment]
@Petrulak performance improvements (using GLSurfaceView) is coming with the 5.2.0 release.
With that in place we will be hitting 60 fps. Would you be able to the `5.2.0-SNAPSHOT` for a test? In the next few weeks we are releasing a couple of beta versions and would love some feedback on it before a final 5.2.0 release. 

To use snapshots, add the snapshots repo in the root build.gradle file:

```java
allprojects {
    repositories {
        jcenter()
        maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
    }
}
```

In you app build.gradle replace current dependency with:

```java
    compile(com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-SNAPSHOT@aar) {
        transitive = true
    }
```

Going to close this as the ticket tracking  general improvements to gestures can be found in #10016.

**Comment by Petrulak** [comment]
@tobrun is there any timeline for #10016 ?
