### ISSUE TITLE
Load @3x assets

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1008]
Follow up to #843: We should also create and load 3x assets when the pixelRatio is >= 3. This is currently capped to 2x.

**Comment by incanus** [comment]
> create

IIRC from chat, we want to scale these up on the fly from 2x, right?

**Comment by kkaefer** [comment]
> IIRC from chat, we want to scale these up on the fly from 2x, right?

We are currently doing this, but they're, well, scaled up.

**Comment by incanus** [comment]
Ok, so I guess my question then is: do you mean to pre-create 3x sprites? If so, where do we draw the line, given that Android has higher ratios as well as [non-integer ratios](https://github.com/mapbox/mapbox-gl-native/issues/397#issuecomment-50787511)?

**Comment by friedbunny** [comment]
In the long term, it seems like moving to vectorized sprites is the way to fix this. SVG, fonts, PaintCode-esque procedural generation...

In the short term, it appears the [official Android guidance](https://developer.android.com/guide/practices/screens_support.html) is to have up to `xxhdpi` (`@3x`) assets: 

> You should not use the `xxxhdpi` qualifier for UI elements other than the launcher icon.

Of course, there's a ton more complexity than "just use 3x!" when it comes to Android screens, but that looks adequate for now?

**Comment by kkaefer** [comment]
Agree that we should use vector spirits and rasterize on the CPU, eg. With a stripped down version of agg

**Comment by ljbade** [comment]
My HTC One and Sony Xperia Z3 both use pixel ratios of 3

**Comment by ljbade** [comment]
@kkaefer Hmm how much of a code size burden will SVG + AGG be?

But I do aggree vector sprites is the correct way to future proof this. I would not be surprised sooner or later a 4x phone will come out with a 4k screen or something crazy.

**Comment by friedbunny** [comment]
On the iOS side, it [appears](https://david-smith.org/iosversionstats/) that roughly 30-40% of devices in use are `@3x`, while four (of seven) of the iPhones that Apple currently sells are `@3x`.
