### ISSUE TITLE
MGLMapSnapshotOptions.size should be measured in points

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#10088]
`MGLMapSnapshotOptions.size` is supposedly measured in pixels, but its type is CGSize, which is almost always measured in points when used with a screen coordinate system. (After all, the width and height can be fractional, whereas there’s no such thing as a fractional pixel.) Ideally, this property should remain CGSize-typed, but we should change MGLSnapshotter to convert to pixels behind the scenes.

/cc @fabian-guerra

**Comment by 1ec5** [comment]
Another reason to switch to points is for consistency with MapboxStatic.swift:

https://github.com/mapbox/MapboxStatic.swift/blob/b73aa38ddb02332fa04e2dfeb7abb50fd8ab1177/MapboxStatic/SnapshotOptions.swift#L213-L218

**Comment by frederoni** [comment]
I might be mistaken but I think it's measured in points but the minimum size is 64x64 in pixels.
https://github.com/mapbox/mapbox-gl-native/pull/10105 fixes the incorrect scale.

**Comment by fabian-guerra** [comment]
Can we close this? We specify as well in the [docs](https://github.com/mapbox/mapbox-gl-native/pull/10020/files#diff-0a849fb567e33a0aed0cad63f8e7505eR59) `MGLMapSnapshotOptions.size` is measured in points. And @frederoni clarified in the comment above.

**Comment by 1ec5** [comment]
Yep, looks good now.
