### ISSUE TITLE
Snapshotter scales incorrectly

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#10089]
If I create an MGLMapSnapshotOptions object with `size` set to 456×480 on a 2× display, MGLMapSnapshotter produces an image 1,824 pixels wide by 1,920 pixels tall, which is what I would expect on a 4× display if `MGLMapSnapshotOptions.size` were measured in points (#10088). As the property is currently documented, however, a `size` of 456×480 should result in a 456×480-pixel image regardless of the screen resolution.

/ref https://github.com/mapbox/mapbox-gl-native/pull/10020#discussion_r140622580
/cc @fabian-guerra @frederoni

**Comment by fabian-guerra** [comment]
As https://github.com/mapbox/mapbox-gl-native/pull/10020#discussion_r141961596 we do handle internally the scale. The output image is scaled accordingly. 456x480 will scale as 1:1 on non-retina screens otherwise will be 1824x1920 px on a 4× display.

**Comment by 1ec5** [comment]
Regardless of whether we internally handle the scale, MGLMapSnapshotter is incorrectly scaling the output image. The example above was on a 2× display, not a 4× display, yet MGLMapSnapshotter was behaving as if it was on a 4× display.
