### ISSUE TITLE
MGLMapView showAnnotations does not work as expected with MGLShapeCollectionFeature

### ISSUE THREAD

**Issue by quicklywilliam** [mapbox/mapbox-gl-native#10096]
When calling showAnnotations on a MGLShapeCollectionFeature, the shape collection appears not to be correctly unpacked before generating the bounding box being used.

For example, the following code results in the wrong viewport:
`self.mapView.showAnnotations([shapeCollectionFeature], edgePadding: insets, animated: true)`
<img width="545" alt="screen shot 2017-09-29 at 1 26 53 pm" src="https://user-images.githubusercontent.com/2109/31034671-e2d4d0ac-a519-11e7-84bb-6b67cc1ab5be.png">

Where as it works fine if you unpack the shapes:
`self.mapView.showAnnotations(shapeCollectionFeature.shapes, edgePadding: insets, animated: true)`
<img width="545" alt="screen shot 2017-09-29 at 1 27 16 pm" src="https://user-images.githubusercontent.com/2109/31034675-ebee337c-a519-11e7-8f7c-fb903321f173.png">

**Comment by 1ec5** [comment]
As a convenience, passing an MGLAnnotation into `showAnnotations(_:)` automatically adds the annotations to the map if they haven’t already been added. The [`addAnnotations(_:)`](https://www.mapbox.com/ios-sdk/api/3.6.4/Classes/MGLMapView.html#/c:objc%28cs%29MGLMapView%28im%29addAnnotations:) documentation states that instances of MGLShapeCollection (of which MGLShapeCollectionFeature is a subclass) can’t be added to the map and are silently ignored. #6181 would reimplement the annotation API atop the runtime styling API, making it possible to add any type of shape to the map as an annotation.
