### ISSUE TITLE
Android: Build Fails - cannot find android-21

### ISSUE THREAD

**Issue by hallahan** [mapbox/mapbox-gl-native#1010]
I'm attempting to install the latest Android build for MapboxGL. after running `git submodule init` and `git submodule update`, I then run `make android`.

Although I do have Android API 21:

![screenshot 2015-03-16 14 54 01](https://cloud.githubusercontent.com/assets/556367/6677360/726dd1e6-cbec-11e4-8f00-22cbbfbf7491.png)

When running `make android`, I get the following error:

```
Build tools 21.1.2 missing. Downloading...
Compilation API android-21 missing. Downloading...
Support library repository missing. Downloading...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':MapboxGLAndroidSDK'.
> Failed to notify project evaluation listener.
   > failed to find target android-21 : /Users/nick/.android-sdk
   > Cannot call getBootClasspath() before setTargetInfo() is called.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.374 secs
make: *** [android] Error 1
```

This was not a problem 2 months ago when last building Android MapboxGL. This is a fresh git clone.

**Comment by ljbade** [comment]
Hmm looks like it may be a bug in the Gradle plugin: https://code.google.com/p/android/issues/detail?id=152811

Specifically it was introduced in Gradle 1.1.0 which we switched to a a while back, and should be fixed in 1.1.2. Will update.

**Comment by ljbade** [comment]
@hallahan I created the android-22 branch which uses Gradle plugin 1.1.3 as well as latest API 22 build tools that have just been released.

Can you check if this fixes your problem?

**Comment by hallahan** [comment]
Just tried it - same issue on android-22 branch

```sh
Build tools 22.0.0 missing. Downloading...
Compilation API android-22 missing. Downloading...
Support library repository missing. Downloading...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':MapboxGLAndroidSDK'.
> Failed to notify project evaluation listener.
   > failed to find target android-22 : /Users/nick/.android-sdk
   > failed to find target android-22 : /Users/nick/.android-sdk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 37.331 secs
make: *** [android] Error 1
n:mapbox-gl-android nick$ git branch -v
* android-22 856b5d9 Update to latest API 22 build tools
  master     0d8b3aa [behind 2] Merge pull request #1006 from mapbox/linux_build_fix
```

**Comment by ljbade** [comment]
Hmm looks like `Cannot call getBootClasspath() before setTargetInfo() is called.` disappeared.

What OS are you building on? I do not get this error on my Linux machines.

**Comment by hallahan** [comment]
```
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	MBP112.0138.B14
  SMC Version (system):	2.19f3

System Version:	OS X 10.10.2 (14C109)
  Kernel Version:	Darwin 14.1.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	n
  User Name:	Nicholas Hallahan (nick)
  Secure Virtual Memory:	Enabled
  Time since boot:	5 days 9:18
```

**Comment by bleege** [comment]
FWIW, I was just able to get `android-22` to run using `make android` on my MacBook Pro.  

That said, I think I found the problem.  The Android SDK Manager is installing API and tools to one path, while the Gradle build script is looking for them in another.  Specifically:

Android SDK Manager Thinks This is ANDROID_HOME
![screen shot 2015-03-16 at 10 36 45 pm](https://cloud.githubusercontent.com/assets/989928/6680975/1d8a292c-cc2d-11e4-9b90-b54c06cfe7d8.png)

Gradle Thinks This Is ANDROID_HOME
> failed to find target android-22 : /Users/nick/.android-sdk

The trick is to set ANDROID_HOME in to one and have both use the same version.  Are you launching the Android SDK Manager from Android Studio?  If so [here's some instructions](http://stackoverflow.com/questions/16581752/android-studio-how-to-change-android-sdk-path) for how to change the SDK location.

**Comment by hallahan** [comment]
OK, I ran `make clean` and tried again. 

```sh
n:mapbox-gl-android nick$ export ANDROID_HOME="/Users/nick/adt-bundle-mac-x86_64-20140702"
n:mapbox-gl-android nick$ make android
```

We still get the same problem. So, it looks like the ANDROID_HOME environment variable is not recognized and the hard-coded ~/.android-sdk is what is being used.

**Comment by hallahan** [comment]
```
BUILD SUCCESSFUL

Total time: 58.659 secs
```

I had to change my sdk location to `~/.android-sdk`, and then get all of the APIs with the SDK Manager. Somewhere `~/.android-sdk` is hardcoded in the build process, and this should be fixed. I did a search in the repo, and all I could find is `mapbox-gl-android/android/java/local.properties`:

```
# DO NOT check this file into source control.
sdk.dir=/Users/nick/.android-sdk
```

I'm not sure where the hard-coding occurs--maybe somewhere in the bowls of mason?

**Comment by ljbade** [comment]
Hmm, @bleege as far as I am aware that local.properties is set up by Android Studio when it first loads a new project?

It is certainly not checked into git repo.

**Comment by bleege** [comment]
Yep `local.properties` is built and set by Android Studio.  Updating the SDK path in Android Studio as a Global SDK and the Project SDK will address this (i.e., set it to `/Users/nick/sdk...`).

As a suggestion (YMMV), I'd suggest deleting one of the 2 instances of the Android SDK that are installed on your computer.  It may trigger some pain in the short run, but that'd be a good thing as it'd help show where things are currently being pointed at a different filesystem version than expected.  This would then give you an opportunity to fix it so that all the Android stuff on your computer is using the same 1 instance.

**Comment by hallahan** [comment]
Ah, OK. Since this is a goofiness with Android Studio, I suppose we should close this issue. I think what happened was that I was using Eclipse first and switched to Android Studio when things started getting stable and awesome. Studio has a default place for the SDK, but it also detected the location of where I had personally put the SDK. 

When I pointed Studio to `~/.android-sdk`, I was able to install all of the API packages there. The build then worked. I appreciate your help @bleege and @ljbade

**Comment by bleege** [comment]
Glad it's working now @hallahan!  FWIW, it's usually the most reliable to just [install the SDK on it's own](http://developer.android.com/sdk/index.html#Other) and then just point Android Studio / Eclipse or whatever at it.  I usually have it installed in `/usr/local/` and then set `ANDROID_HOME` in `.bash_profile`.  YMMV.
