### ISSUE TITLE
Incorrect userLocation annotation position after zoomLevel is changed

### ISSUE THREAD

**Issue by ungurdav** [mapbox/mapbox-gl-native#10108]
**Platform: iOS**
**Mapbox SDK version: 3.6.2**

User puck is drawn in a different place after `zoomLevel` is changed and `userTrackingMode` is set to `followWithCourse ` and `userLocationVerticalAlignment` is set to `bottom`.

### Steps to trigger behavior

 1. mapView.userLocationVerticalAlignment = .bottom
 2. mapVIew.setUserTrackingMode(.followWithCourse, animated: false)

 3. mapView.setZoomLevel(14, animated: true) 

### Expected behavior
Map should zoom out and user annotation/puck should stay at the same place as it was before the animation started.

### Actual behavior
User puck moves to a different place (where the user isn't). Panning the map helps to redraw the puck in correct location.

**Comment by 1ec5** [comment]
The `userLocationVerticalAlignment` property was deprecated in favor of a delegate method in #12907.
