### ISSUE TITLE
[Question] Allow Custom Location Source on iOS

### ISSUE THREAD

**Issue by emerciercontexeo** [mapbox/mapbox-gl-native#10100]
This feature exists on Android but I can't find any information about it on iOS.

Am I missing something ? Will this feature be implemented ?

**Comment by fabian-guerra** [comment]
Hi, @emerciercontexeo. Thank you for using Mapbox. The feature you mention is an OS level feature for Android. On iOS is not possible to implement your own version of `CLLocationManager`.

I am closing this ticket since is not related to our SDK.

**Comment by frederoni** [comment]
@emerciercontexeo there's a related ticket #6867 which track overriding location/course tracking but I think we should let users set `MGLMapView`’s location manager but it would require more than just exposing the property as writeable.

How do you intend to use this custom location source?

**Comment by emerciercontexeo** [comment]
Thanks for answers.

@frederoni : I have to use different location provider to display a more accurate location when a user is inside a building. Gps works well outdoor but is useless indoor.
With all my providers, I can compute a location and display it on the map.

It was easy in your android SDK with the CustomLocationEngine and I was hopping that the same feature exists on iOS.

As workaround, I use a custom annotation that I add on the map and update on each new location. But doing it this way, I have to implement all tracking feature by myself which is a bit sad :)

**Comment by frederoni** [comment]
@emerciercontexeo Ok. We ran into a similar issue in [mapbox-navigation-ios](http://github.com/mapbox/mapbox-navigation-ios) which we worked around by exposing that `MGLMapView`, does in fact, conform to `CLLocationManagerDelegate`. See [MGLMapView+MGLNavigationAdditions](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxNavigation/MGLMapView+MGLNavigationAdditions.h).
