### ISSUE TITLE
Implement transparency in MGLMapSnapshotter

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/mapbox-gl-native#10118]
As is asserted in this [comment](https://github.com/mapbox/mapbox-gl-native/pull/10105#discussion_r142498056) a `MGLMapView` is not necessarily opaque. `MGLMapSnapshotter` should implement an alpha channel if the background style layer has a non-opaque fill color.

**Comment by 1ec5** [comment]
This should just be a matter of passing `YES` in as the second parameter to `UIGraphicsBeginImageContextWithOptions()`:

https://github.com/mapbox/mapbox-gl-native/blob/736e9d60848b1f5f11ffa1ddfbd8c052f79e2cdc/platform/darwin/src/MGLMapSnapshotter.mm#L139

If the image ends up getting saved out in a format that doesn't support transparency, like JPEG, the output will be no worse than it would be without this change. For images that require no alpha channel, which is the usual case, I suppose there would be a marginal increase in file size, but it shouldn't matter greatly.

**Comment by 1ec5** [comment]
> if the background style layer has a non-opaque fill color

This would require #9914, although per https://github.com/mapbox/mapbox-gl-native/issues/10118#issuecomment-334013562, I don’t think it’s strictly necessary to enable opacity in any case.
