### ISSUE TITLE
There aren't camera started and Idle notifications on the two fingers tap 

### ISSUE THREAD

**Issue by TranThuong** [mapbox/mapbox-gl-native#10111]
Android
Mapbox SDK version:5.1.4

### Steps to trigger behavior

Tap on the map with two fingers

### Expected behavior
must receive the onCameraMoveStarted and onCameraIdle callbacks

### Actual behavior
there aren't any callback

I'd tried to add the line below in `boolean onTouchEvent(MotionEvent event)` of the class `MapGestureDetector` it works well, I have the camera started and idle callbacks 
> boolean onTouchEvent(MotionEvent event) {
> ...
> case MotionEvent.ACTION_UP:
> ...
> if (twoTap && isTap && !inProgress) {
>     **cameraChangeDispatcher.onCameraMoveStarted(REASON_API_GESTURE);**
> ...

**Comment by tobrun** [comment]
Thank you for reporting this issue, it seems accurate that we don't have integration for those events yet.

**Comment by tobrun** [comment]
@TranThuong I just did a test without any changes and I'm receiving the callbacks:

```
10-05 12:34:34.642 5666-5666/com.mapbox.mapboxsdk.testapp E/CameraPositionActivity: OnCameraMoveStarted: REASON_API_GESTURE
10-05 12:34:34.662 5666-5666/com.mapbox.mapboxsdk.testapp I/ScaleGestureDetector: TwScaleGestureDetector
10-05 12:34:34.722 5666-5666/com.mapbox.mapboxsdk.testapp E/CameraPositionActivity: OnCameraIdle
```

You can also see it visually here with a toast:

![ezgif com-video-to-gif 39](https://user-images.githubusercontent.com/2151639/31224298-9fe61978-a9cd-11e7-9f9c-44c4ce715052.gif)
