### ISSUE TITLE
Add ability for cameraForShape to fix the pitch

### ISSUE THREAD

**Issue by asheemmamoowala** [mapbox/mapbox-gl-native#10115]
This is a follow-up to #9809 and depends on #2259.

`Map::cameraForLatLngs` should provide an overload where an arbitrary pitch can be provided for fitting a shape.

**Comment by 1ec5** [comment]
This feature is being implemented in #12213.

**Comment by asheemmamoowala** [comment]
@1ec5 #12213 doesn't implement correctness when pitch is set to a non-zero value. Lets leave this open to implement pitch-aware fitting.

**Comment by d-prukop** [comment]
@asheemmamoowala see #13007
