### ISSUE TITLE
User location annotation is drawn across pixel boundaries

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#10119]
**Platform:** iOS
**Mapbox SDK version:** v3.6.4

We sometimes position the user location annotation using the output of [`-convertCoordinate:toPointToView:`](https://www.mapbox.com/ios-sdk/api/3.6.4/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)convertCoordinate:toPointToView:) without first rounding to screen points (or logical pixels), which means that the annotation is slightly blurry and loses some small amount of rendering performance.

![screen shot 2017-10-03 at 5 25 20 pm](https://user-images.githubusercontent.com/1198851/31155939-a7ea9af8-a866-11e7-947b-e018d27ca816.png)

/cc @1ec5

**Comment by friedbunny** [comment]
Any view annotations that we place on the map are also susceptible to this. Though MapKit does _not_ round its `-convertCoordinate:toPointToView:` output, I can’t really think of a reason why we shouldn’t?

/cc @frederoni @boundsj @fabian-guerra

**Comment by 1ec5** [comment]
> Though MapKit does _not_ round its `-convertCoordinate:toPointToView:` output, I can’t really think of a reason why we shouldn’t?

Probably because rounding errors can accumulate when converting back and forth. It should be up to the caller to do the rounding before positioning the view or layer on the screen.

**Comment by friedbunny** [comment]
Fixed in #10219; will be in v3.7.0-beta.3.
