### ISSUE TITLE
DefaultFileSource::setOfflineMapboxTileCountLimit shouldn't use invokeSync

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#10126]
Using `invokeSync` will cause the calling thread to hang if the `DefaultFileSource` thread is busy servicing requests (for instance, running an expensive SQL query). I don't think there's any reason setting the tile count limit needs to be a synchronous invocation. Is there?

cc @ivovandongen

**Comment by ivovandongen** [comment]
No, that shouldn't be synchronous. Actually, on master, it's a call to `ActorRef::invoke`: https://github.com/mapbox/mapbox-gl-native/blob/master/platform/default/default_file_source.cpp#L303

Which branch is still using `invokeSync`?

**Comment by jfirebaugh** [comment]
Ah great, this is already fixed then. I was looking at the v3.6.0/v5.1.0 release branch.
