### ISSUE TITLE
Add snapshot classes to jazzy table of contents

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#10121]
MGLMapSnapshotOptions and MGLMapSnapshotter are currently listed under “[Other Classes](https://www.mapbox.com/ios-sdk/api/3.7.0-alpha.1/Other%20Classes.html)” in the iOS and macOS API references’ tables of contents. We should add these classes under “Maps” in both jazzy.yml files so they’re easier to find.

https://github.com/mapbox/mapbox-gl-native/blob/f01588cac78b5e5411385faa451080a74320500b/platform/ios/jazzy.yml#L29-L35
https://github.com/mapbox/mapbox-gl-native/blob/f01588cac78b5e5411385faa451080a74320500b/platform/macos/jazzy.yml#L25-L30

/cc @fabian-guerra

**Comment by friedbunny** [comment]
Got this in #10639.
