### ISSUE TITLE
How to get layers' groups in iOS?

### ISSUE THREAD

**Issue by fleuverouge** [mapbox/mapbox-gl-native#10129]
**Platform: iOS**
**Mapbox SDK version: 3.6.4**

Hi, 
We have to display the list of layers of loaded style in groups. From API, we can get layers' groups in a style (their "metadata.mapbox:group"). However, I wonder if there's some way to get this information without calling API, since sometimes we need the app to work offline.

Thanks in advance.

**Comment by stonetip** [comment]
What about getting that info while online and storing it locally?

**Comment by fleuverouge** [comment]
Hi @stonetip , thanks for replying!
That's what I'm doing now. I don't want to call many APIs when loading a map though, since when a map is loaded, its metadata should be fetched too.

**Comment by stonetip** [comment]
I definitely agree it would be better if the metadata came along with the map data. Does making the metadata API call count against quotas? (Just curious...good info to know). Thanks.

**Comment by jfirebaugh** [comment]
`metadata.mapbox:group` is not an official public API (it's internal state created by Mapbox Studio), so we can't expose it in the Map SDK as if it were. However, so long as Mapbox Studio doesn't change, storing it locally could be a viable solution for you.
