### ISSUE TITLE
onMapReady not called when started in offline

### ISSUE THREAD

**Issue by PavelKorolev** [mapbox/mapbox-gl-native#10139]
**Platform:** Android
**Mapbox SDK version:** 5.1.4

[Here is repository](https://github.com/PavelKorolev/MapboxOfflineTest) of example project with described behaviour. Basically it's just SimpleOfflineActivity from mapbox example repository.

There are two similar bugs with onMapReady.

## 1

This one reproduced in 100% cases.

### Steps to trigger behavior

 1. Install the app with Mapbox Maps
 2. Set Airplane mode
 3. Open map

### Expected behavior
Should trigger onMapReady callback

### Actual behavior
onMapReady not triggered - map is black. If I disable Airplane mode map starts loading. Next app start without network is ok. Some tiles which were saved into cache successfully loaded after onMapReady successfully triggered.

## 2

It can be reproduced in 100% cases after some sequence of actions, but couldn't understand this exact sequence. Actions were something like these:

### Steps to trigger behavior

 1. Start downloading region for offline
 2. Set Airplane mode in the middle of process/wait the end and set airplane mode.
 3. Restart app with Airplane mode enabled.

### Expected behavior
Should trigger onMapReady callback

### Actual behavior
onMapReady not triggered - map is black, looks exactly as first one, but there should be saved tiles already and app still can't draw map. 

Tested on both OnePlus 3 and Nexus 5.

**Comment by tobrun** [comment]
I think there is a misconception about how the OnMapReady callback should work:
We invoke onMapReady when the style has finished (down)loading. If the user doesn't have an internet connection, we can't load the style and thus can't invoke the callback. The only case where this doesn't apply is when you have a offline region downloaded. For that we can load the style from the database.

Let us know if you run into anymore issues, calling this issue a work as designed.

**Comment by PavelKorolev** [comment]
But to set style programmatically we need to use MapboxMap param of onMapReady method which is not called, isn't it? Any customization of map like compass position happens here, so if onMapReady is not triggered user sees black map with compass in default place and so on. Is it designed to work like this or I understand something wrong in terms of how to use map?

Anyway second bug appears when there should be some tiles downloaded. Is it possible that Mapbox SDK deletes all downloaded tiles completely from device if something happened like download error/download limit exceeded so there are no tiles after app restart and user sees black map again?

**Comment by tobrun** [comment]
@PavelKorolev there are a couple of ways of setting your style early before OnMapReady:
 - xml attributes as `mapbox_styleUrl` when inflating from xml
 - `MapboxMapOptions#setStyleUrl` when creating programatically
 - `MapView#setStyleUrl`

**Comment by Dagzo** [comment]
Hi.
Please let me ask 2 questions.
1. How can I get MapBoxMap object in this case ?
2. Is there a callback that is called instead of onMapReady in offline?

**Comment by tobrun** [comment]
If you have an offline download, the callback will be invoked
