### ISSUE TITLE
[Qt] ResourceTransform interface is missing in Qt bindings

### ISSUE THREAD

**Issue by rinigus** [mapbox/mapbox-gl-native#10130]
Hi,

I would like to transform URLs before requests when using Qt bindings. It looks like there is no API for specifying `ResourceTransform` in Qt. 

One way to resolve the issue would be to expose the used `mbgl::DefaultFileSource` object pointer, so I can access its methods. At present, its hidden in the private `QMapboxGLPrivate` object. 

Alternative would be to let me specify the ResourceTransform object as a part of `QMapboxGLSettings`. 

I think it would be sufficient to use `std::string` in this case and not overload it with `QString` to avoid too much translations between Qt and `std` worlds.

Reference: ResourceTransform introduced in https://github.com/mapbox/mapbox-gl-native/pull/8084 for other platforms

**Comment by brunoabinader** [comment]
Nice addition @rinigus :100:

**Comment by rinigus** [comment]
Thank you for the fast review and  merge!
