### ISSUE TITLE
Revisit keyboard/mouse events

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#10131]
Our current keyboard support hasn't been updated since the initial v2.0.0 release. Since that time more Android tablets with keyboards have been released and now with the ability of running Android applications on chromebooks we need to revisit this implementation.

Some examples of current implementation that need to change:
 - When you scroll your mouse wheel, the map is location is changed while the desired UX here would be to zoom the map
 - We currently don't have a way to change the camera tilt through keyboard/mouse configuration
 - ..

Note that this integration can also be two fold:
 - integration in the SDK for map interaction events as shown above
 - test app integration that allows to easily debug different activities (eg. print camera position to log, enable debug mode, load style, etc..)

**Comment by langsmith** [comment]
Related documentation for future reference:

https://developer.android.com/training/gestures

https://developer.android.com/training/keyboard-input/commands.html

https://developer.android.com/training/keyboard-input/navigation.html

**Comment by langsmith** [comment]
Maps SDK's class that's related to this work is `MapKeyListener` https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapKeyListener.java

**Comment by langsmith** [comment]
>When you scroll your mouse wheel, the map is location is changed while the desired UX here would be to zoom the map

@tobrun , does the gif below match up with what you're describing. The focal point (or camera target?) changes _along_ with the zoom level. You're saying that https://github.com/mapbox/mapbox-gl-native/pull/14789 should make it so that zooming in/out _only_ adjusts the zoom level and doesn't adjust the map focal point, correct?

![ezgif com-resize (2)](https://user-images.githubusercontent.com/4394910/59641477-8b118500-9116-11e9-82fd-a5dfcdec03e7.gif)

**Comment by tobrun** [comment]
> Focal point moves to where the mouse is when I zoom in/out. This is not what you want, right?:

This is what gl-js does and provides the best UX. IMO go for it.

**Comment by langsmith** [comment]
>This is what gl-js does and provides the best UX. IMO go for it.

Oh, ok. Well then the Maps SDK already has this behavior at 

https://github.com/mapbox/mapbox-gl-native/blob/da69a88c04fcd7e93507dde74ffbc4e0fbd57210/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java#L292

As FYI, switching that line to `transform.zoomBy(scrollDist, new PointF(uiSettings.getWidth() / 2, uiSettings.getHeight() / 2));` would keep the camera target the same, as seen in the 1st GIF above.
