### ISSUE TITLE
Multiple maps on Android

### ISSUE THREAD

**Issue by SamuelDebruyn** [mapbox/mapbox-gl-native#10132]
**Platform:** Android
**Mapbox SDK version:** 5.1.1

I'm using Mapbox together with Xamarin.Forms. I've added a map to 2 pages. Whenever I open one of the pages, everything is fine. But when I open the first page and then navigate to the second page, keeping the first one in the back stack, I see 2 maps in the mapview. It looks like OpenGL is still rendering the first map too.

**Comment by tobrun** [comment]
@SamuelDebruyn thank you for reaching out, at first glance this looks like an issue with Xamarin library and how it's handling the concept of "pages". It' doesn't seem to correctly destroy the underlying fragment/activity. The Xamarin library found [here](https://components.xamarin.com/view/mapboxsdk/) isn't an official Mapbox product. Happy to look more into the code but I wasn't able to find anything. Going ahead and close this as this isn't actionable for us. Feel free to follow up with more information so we can get to the bottom of this.
