### ISSUE TITLE
MGLImageSource doesn't overlay an image

### ISSUE THREAD

**Issue by fousa** [mapbox/mapbox-gl-native#10138]
**Platform: iPhone iOS 11.0.1**
**Mapbox SDK version: Mapbox-iOS-SDK 3.7.0-beta.1**

### Steps to trigger behavior

Here is a small code snippet to render the `radar.gif` on the map as done in the example:

I added the `MGLMapView` as an outlet to my controller and this works fine until I want to display an overlay.

```swift
func mapView(_ mapView: MGLMapView, didFinishLoading style: MGLStyle) {
    let coordinates = MGLCoordinateQuad(
        topLeft: CLLocationCoordinate2D(latitude: 46.437, longitude: -80.425),
        bottomLeft: CLLocationCoordinate2D(latitude: 37.936, longitude: -80.425),
        bottomRight: CLLocationCoordinate2D(latitude: 37.936, longitude: -71.516),
        topRight: CLLocationCoordinate2D(latitude: 46.437, longitude: -71.516)
    )
    let source = MGLImageSource(identifier: "radar", coordinateQuad: coordinates, url: URL(string: "https://www.mapbox.com/mapbox-gl-js/assets/radar.gif")!)
    style.addSource(source)
}
```

### Expected behavior

It should render the rain overlay on the map.

### Actual behavior

It renders no image...

**Comment by jmkiley** [comment]
Hi @fousa -

You will want to use the `MGLImageSource` to create a `MGLRasterStyleLayer`. The radar should appear once you add that layer to your map's style.

For example:
```swift
        let coordinates = MGLCoordinateQuad(
            topLeft: CLLocationCoordinate2D(latitude: 46.437, longitude: -80.425),
            bottomLeft: CLLocationCoordinate2D(latitude: 37.936, longitude: -80.425),
            bottomRight: CLLocationCoordinate2D(latitude: 37.936, longitude: -71.516),
            topRight: CLLocationCoordinate2D(latitude: 46.437, longitude: -71.516))
        let source = MGLImageSource(identifier: "radar", coordinateQuad: coordinates, url: URL(string: "https://www.mapbox.com/mapbox-gl-js/assets/radar.gif")!)
        style.addSource(source)
        
        let layer = MGLRasterStyleLayer(identifier: "radar-layer", source: source)
        layer.rasterOpacity = MGLStyleValue(rawValue: 0.5)
        style.addLayer(layer)
```

**Comment by fabian-guerra** [comment]
The [example](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/MGLImageSource.h#L36-L42) in `MGLImageSource` documentation does not mention creating a raster style. We should update the example clarifying it's usage.

/cc @jmkiley

**Comment by fousa** [comment]
That makes sense. Now it works! Thanks for your quick response @jmkiley!
