### ISSUE TITLE
[Style]: Failed to load tile 13/6459/4067=>13 for source composite: connect timed out

### ISSUE THREAD

**Issue by AlexLiuSheng** [mapbox/mapbox-gl-native#10159]
**Platform:**Android 
**Mapbox SDK version:**5.1.4

### Steps to trigger behavior

 1.use `mapbox://styles/mapbox/streets-v10` to setStyle ,and set a `OnStyleLoadedListener` to style
 2.it seems style has been loaded in map,but the callback don't trigger and logged a error as above
 3.i can confirm the access-token of map is right

so could u tell me why ?thank u  so much

**Comment by AlexLiuSheng** [comment]
and the internet is connected

**Comment by tobrun** [comment]
Not able to reproduce the issue shown in OP, constantly getting callbacks when a load a new style. Seeing that you are located in Chendu, are you using our chinese endpoint? Getting a connect time out can be considered expected behaviour when connecting out of China to our standard endpoints.
