### ISSUE TITLE
Marker's Rotation is missing

### ISSUE THREAD

**Issue by Deaniesaur** [mapbox/mapbox-gl-native#10155]
Platform: Android
SDK Version:5.1.4 native

In the latest Tutorials for Android Demo App(Annotations), I can see the method MarkerViewOptions.rotation();. I would like to implement it with my app but it seems that the method
rotation for MarkerViewOptions is not present in SDK 5.1.4

I would like to know alternative for rotation the markers in SDK 5.1.4. Thank you

**Comment by tobrun** [comment]
the MarkerViewOptions rotation is availlable in 5.1.4 (for now, as we are deprecating the MarkerView setup). The way forward for implementing this is with SymbolLayer and using the icon-rotate property (see [here](https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-icon-rotate)).
