### ISSUE TITLE
Adding MGLRasterStyleLayer on map is not refreshing until we pan the map.

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [mapbox/mapbox-gl-native#10160]
**Platform:** IOS
**Mapbox SDK version:** ios-v3.7.0-beta.1

### Steps to trigger behavior

 1. Create a button called "Add Raster".
 2. Open map, wait to load all the layer's on map.
 3. Now tap on the button to add the `MGLRasterStyleLayer`.
 4. Adding `MGLRasterStyleLayer` on map is not refreshing until we pan the map.

### Expected behavior

1. `MGLRasterStyleLayer` should add on map. 

### Actual behavior

1. But it's not adding on map, until the map is panned.

Here is how I am adding `MGLRasterStyleLayer` on map,

```
let source = MGLRasterSource(identifier: "custom-raster-source", tileURLTemplates: [basemapURL], options: [ .tileSize: 256 ])
let rasterLayer = MGLRasterStyleLayer(identifier: "custom-raster-layer", source: source)
rasterLayer.isVisible = true
mapView?.style?.addSource(source)
if let water = mapView?.style?.layer(withIdentifier: "water") {
      mapView?.style?.insertLayer(rasterLayer, below: water)
}
```

The same is working in older version of SDK.

**Comment by fabian-guerra** [comment]
Hi, @ThiyagarajanShivSankaran. Thank you for using Mapbox. Looking at the source code you provided I realized that the source is added but raster layer.

If you add this line it will work:
`mapView?.style?.addLayer(rasterLayer)`

The full example should be:
```
let source = MGLRasterSource(identifier: "custom-raster-source", tileURLTemplates: [basemapURL], options: [ .tileSize: 256 ])
let rasterLayer = MGLRasterStyleLayer(identifier: "custom-raster-layer", source: source)
rasterLayer.isVisible = true
mapView?.style?.addSource(source)
mapView?.style?.addLayer(rasterLayer)
```

I tried [this code](https://www.mapbox.com/ios-sdk/examples/source-custom-raster/) with [3.6.4](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.6.4) and [3.7.0-beta.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.7.0-beta.1) and works as expected.

| 3.6.4 | 3.7.0-beta.1 |
| --- | --- |
| ![simulator screen shot - iphone 7 - 2017-10-09 at 10 58 47](https://user-images.githubusercontent.com/2745166/31352445-ad8a29c0-ace3-11e7-9f78-3000176bdc40.png) | ![simulator screen shot - iphone 7 - 2017-10-09 at 11 03 14](https://user-images.githubusercontent.com/2745166/31352462-bfcd3082-ace3-11e7-83a4-d6c135c12475.png) |

Let me know if this helps.

**Comment by ThiyagarajanShivSankaran** [comment]
Hi @fabian-guerra , Actually I have missed the line while copying and pasting. Now edited the above code snippet. Also, updated the steps to reinvent the issue can you look at that, Thanks,

**Comment by fabian-guerra** [comment]
Hi, @ThiyagarajanShivSankaran. Thank you for updating the example. I tried the sample code you provided and I still don't get any problem.

| 3.6.4 | 3.7.0-beta.1 |
| --- | --- |
| ![3 6 4](https://user-images.githubusercontent.com/2745166/31456992-47dafb2a-ae70-11e7-876d-d586810c6274.png) | ![3 7 0](https://user-images.githubusercontent.com/2745166/31457007-548fee5c-ae70-11e7-880f-ec5e835d4795.png) |

I'm loading the style in:
`func mapView(_ mapView: MGLMapView, didFinishLoading style: MGLStyle)`

**Comment by ThiyagarajanShivSankaran** [comment]
Hi @fabian-guerra adding raster style in:
`func mapView(_ mapView: MGLMapView, didFinishLoading style: MGLStyle)`  is working for me as well.

Look at the below steps to reinvent,

1. Open map view .
2. Wait to load all the layer's on map.
3. Create a button called `Add Raster Style`
3. Now, tap on that button to add the style on map.
4. It's not loading at the time of tap event, but if you pan map little it's loading.

If you are unable to reinvent just reply me. I will try to upload a video, Thanks.

**Comment by fabian-guerra** [comment]
Hi, @ThiyagarajanShivSankaran. Thank you for providing the steps to reproduce the error. Now I see what is happening. I am going to track down the problem.

**Comment by fabian-guerra** [comment]
@jfirebaugh could you please take a look.

**Comment by fabian-guerra** [comment]
@jfirebaugh this is the code sample to reproduce the problem.

```
    MGLRasterSource *source = [[MGLRasterSource alloc] initWithIdentifier:@"stamen-watercolor" tileURLTemplates:@[@"https://stamen-tiles.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg"] options:@{MGLTileSourceOptionTileSize:@256}];
    
    MGLRasterStyleLayer *rasterLayer = [[MGLRasterStyleLayer alloc] initWithIdentifier:@"custom-stamen-watercolor" source:source];
    
    rasterLayer.rasterOpacity = [MGLStyleValue valueWithRawValue:@0.4];
    rasterLayer.visible = YES;
    
    [self.mapView.style addSource:source];
    
    MGLStyleLayer *water = [self.mapView.style layerWithIdentifier:@"water"];
    if (water) {
        [self.mapView.style insertLayer:rasterLayer belowLayer:water];
    }
```

This must be called outside `mapView:didFinishLoadingStyle:`.

**Comment by jfirebaugh** [comment]
@fabian-guerra Sure -- can you please push a branch with the code that reproduces the issue?

**Comment by jfirebaugh** [comment]
Oops, didn't see your latest comment!

**Comment by fabian-guerra** [comment]
@jfirebaugh no worries if it's more useful I made this branch that reproduces the problem. https://github.com/mapbox/mapbox-gl-native/tree/fabian-load-style-10160 Tap on Add Style and pan the map.
