### ISSUE TITLE
Map unable to display on activity

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#10167]
_Originally opened in the android navigation repo @AshrafRah96_

Hi, ive implemented the Mapbox sdk for android and suggested however when i run the application the map is only displayed for a second before is disappears, same for when the user presses the back button to exit the activity.

The code on the activity i placed the map is:

    public class MapsActivity extends AppCompatActivity {

    private MapView mapView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Mapbox access token is configured here. This needs to be called either in your application
        // object or in the same activity which contains the mapview.
        Mapbox.getInstance(this, getString(R.string.access_token));

        // This contains the MapView in XML and needs to be called after the access token is configured.
        setContentView(R.layout.activity_maps);

        mapView = (MapView) findViewById(R.id.mapView);
        mapView.onCreate(savedInstanceState);
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {

                // Customize map with markers, polylines, etc.

            }
        });
    }

    // Add the mapView lifecycle to the activity's lifecycle methods
    @Override
    public void onResume() {
        super.onResume();
        mapView.onResume();
    }

    @Override
    protected void onStart() {
        super.onStart();
        mapView.onStart();
    }

    @Override
    protected void onStop() {
        super.onStop();
        mapView.onStop();
    }

    @Override
    public void onPause() {
        super.onPause();
        mapView.onPause();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        mapView.onDestroy();
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mapView.onSaveInstanceState(outState);
    }
}

The build.gradel:

    apply plugin: 'com.android.application'

    android {
        compileSdkVersion 26
        buildToolsVersion "26.0.0"
        defaultConfig {
            applicationId "com.name.test"
            minSdkVersion 21
            targetSdkVersion 26
            versionCode 1
            versionName "1.0"

            multiDexEnabled true

            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
            exclude group: 'com.android.support', module: 'support-annotations'
        })

        // Mapbox dependencies
        compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.4@aar') {
            transitive = true
        }

        // Mapbox Android UI
        compile 'com.mapbox.mapboxsdk:mapbox-android-ui:2.2.5'

        compile 'com.android.support:design:26.+'
        compile 'com.android.support:support-v4:26.+'
        compile 'com.android.support:appcompat-v7:26.+'

        compile 'com.android.support.constraint:constraint-layout:1.0.2'
        compile 'com.jakewharton:butterknife:8.8.1'
        compile 'com.google.android.gms:play-services:11.0.4'
        compile 'com.squareup.okhttp3:okhttp:3.8.1'
        compile 'com.google.android.gms:play-services-maps:11.0.4'
        compile 'com.google.maps.android:android-maps-utils:0.5'

        testCompile 'junit:junit:4.12'
        annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    }

The XML:

    <?xml version="1.0" encoding="utf-8"?>
    <RelativeLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:mapbox="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        >

        <com.mapbox.mapboxsdk.maps.MapView
            android:id="@+id/mapView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            mapbox:mapbox_cameraTargetLat="40.73581"
            mapbox:mapbox_cameraTargetLng="-73.99155"
            mapbox:mapbox_cameraZoom="11"
            mapbox:mapbox_styleUrl="mapbox://styles/ashrafrahman/cj8ew25mcafxz2rpnnbbyzl9d"/>

    </RelativeLayout>
![mapbox](https://user-images.githubusercontent.com/29957644/31308574-d943bff0-ab70-11e7-943c-1c4a7de1f37e.png)

### Steps to trigger behavior

 1. Clicking button to view to map activity
 2.
 3.

### Actual behavior: Blank canvas

**Comment by Guardiola31337** [comment]
Was also reported here 👀 #10157 
Closing as duplicated.
