### ISSUE TITLE
Runtime styling prototyping guide has outdated Studio screenshots

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#10178]
The “[Working with Mapbox Studio](https://www.mapbox.com/ios-sdk/api/3.6.4/working-with-mapbox-studio.html)” guide features screenshots of Mapbox Studio’s former dark theme. These screenshots should be updated for [the lighter theme that debuted today](https://blog.mapbox.com/behind-mapbox-studios-new-look-874c156395fd).

/cc @captainbarbosa @ericrwolfe

**Comment by colleenmcginnis** [comment]
@ericrwolfe @1ec5 @captainbarbosa how would you feel about limiting the content in this guide to information that is specific to iOS and pointing to help page content for general information about Mapbox Studio? The support team will be keeping track of Mapbox Studio updates and adjusting help content when necessary &mdash; that's likely the best way to prevent this guide from becoming out of date. If the help page is lacking information covered in this guide that's non-iOS-specific, I'd be happy to work on adding that content to the help page so all our users can benefit!

**Comment by 1ec5** [comment]
I think the original intent of this guide was to capture the entire workflow from code to Studio and back to code, while delving into specifics that the developer-designer would encounter frequently. If we can maintain a similar guide as part of Mapbox’s help site, with at least the same level of iOS-specific detail, then we can remove the guide from the iOS docset and link out to the help site.

Two pieces of information stand out to me as being critical and not captured anywhere else as part of a Studio workflow:

* The use of `-[MGLMapViewDelegate mapView:didFinishLoadingStyle:]`
* Links to “[Information for style authors](https://www.mapbox.com/ios-sdk/api/3.6.4/for-style-authors.html)”, which does contain some high-level content but also a lot of code-level detail that would be essential to anyone prototyping runtime styling in Studio.

**Comment by captainbarbosa** [comment]
For posterity, this was addressed with the new redesign of [mapbox.com/ios-sdk](https://www.mapbox.com/ios-sdk/).
