### ISSUE TITLE
AnnotationView attached to screen

### ISSUE THREAD

**Issue by iBinh** [mapbox/mapbox-gl-native#10179]
**Platform:** iOS
**Mapbox SDK version:**  ios-v3.7.0-beta.1

### Steps to trigger behavior

 1. Create MGLMapView instance
 2.  Add annotationView to MGLMapView
 3. Present ViewController and add MGLMapView to ViewController

### Actual behavior

AnnotationView attached to screen

**Comment by boundsj** [comment]
Thanks for the report @iBinh. We are not able to reproduce this with the steps you provided. Can you please provide a code sample or simple project that reproduces this issue?

**Comment by iBinh** [comment]
my project 
import UIKit
`
class PickLocationButton: UIButton {

    override func awakeFromNib() {
        super.awakeFromNib()
        self.addTarget(self, action: #selector(onClick), for: .touchUpInside)
    }
    @objc func onClick() {
        let topVC = currentTopViewController()
        let pickLocationVC = LocationPickerViewController()
        pickLocationVC.mapBoxView = GlobalObject.sharedInstance().mapBoxView
        topVC?.present(pickLocationVC, animated: true, completion: nil)
                
    }
    func currentTopViewController() -> UIViewController? {
        var topVC = UIApplication.shared.keyWindow?.rootViewController
        while topVC?.presentedViewController != nil {
            topVC = topVC?.presentedViewController
        }
        return topVC
    }
}`

**Comment by boundsj** [comment]
Thanks @iBinh. The code snippet you shared above appears to be about dynamic view controller selection and presentation. I can see you are using some globally shared `MGLMapView` instance but that information alone will probably not help us reproduce this issue since it does not illustrate where and how you are adding `MGLAnnotationView` instances to the `MGLMapView`. Any additional information you can provide would be helpful including screen captures or recordings and a more complete solution that reproduces the problem.

**Comment by iBinh** [comment]
Here is my code:

1. AnnotationView delegate

`-(MBXAnnotationView *)annotationViewForAnnotation:(GoongAnnotation *)annotation tapGesture:(UITapGestureRecognizer *)taptap{
    if ([annotation isKindOfClass:[GoongAnnotation class]]) {
        if (annotation.reuseIdentifier) {
            if (annotation.type != TypeRealTime) {
                MBXAnnotationView *annotationView = (MBXAnnotationView *)[self dequeueReusableAnnotationViewWithIdentifier:annotation.reuseIdentifier];
                
                if (!annotationView) {
                    annotationView = [[MBXAnnotationView alloc] initWithReuseIdentifier:annotation.reuseIdentifier];
                }
                for (UIGestureRecognizer *ges in annotationView.gestureRecognizers) {
                    [taptap requireGestureRecognizerToFail:ges];
                }
                
                annotationView.scalesWithViewingDistance = NO;
                UIImageView *imgView = [[UIImageView alloc] initWithImage:annotation.image];
                imgView.contentMode = UIViewContentModeScaleToFill;
                annotationView.imgView = imgView;
                [annotationView addSubview:annotationView.imgView];
                imgView.transform = CGAffineTransformMakeScale(0.1, 0.1);
                [UIView animateWithDuration:.75 delay:0 usingSpringWithDamping:0.5 initialSpringVelocity:0.3 options:UIViewAnimationOptionCurveEaseOut animations:^{
                    imgView.transform = CGAffineTransformMakeScale(1.0, 1.0);
                } completion:^(BOOL finished) {
                    
                }];
                
                
                
                // Calculate frame and size of annotationView and imgView
                if (annotation.type == TypeMarker) {
                    if (![GoongInstance.currentMarkerType containsObject:@"SUGGESTION"]) {
                        if ([GoongInstance.currentMarkerType containsObject:@"TD"] || annotation.type == TypeSaved) {
                            annotationView.frame = CGRectMake(0, 0, 25, 25);
                            imgView.viewSize = CGSizeMake(25, 25);
                            imgView.center = CGPointMake(25/2, 25/2);
                            
                        } else {
                            annotationView.frame = CGRectMake(0, 0, 35, 35);
                            //                            imgView.viewSize = CGSizeMake(35, 35);
                            imgView.height = 35;
                            imgView.contentMode = UIViewContentModeScaleAspectFill;
                            imgView.left = 0;
                            imgView.bottom = annotationView.middleX;
                        }
                    } else {
                        
                        annotationView.frame = CGRectMake(0, 0, 40, 100);
                        
                        UIView *aView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 40, 50)];
                        UIImageView *frame = [[UIImageView alloc] initWithFrame:CGRectMake(0, 1, 40, 50)];
                        frame.image = [UIImage imageNamed:@"suggestion_frame"];
                        [aView addSubview:frame];
                        
                        NSString *tempHex;
                        if ([annotation.bgColorHex.description containsString:@"#"]) {
                            tempHex = [annotation.bgColorHex stringByReplacingOccurrencesOfString:@"#" withString:@"0x"];
                        }
                        
                        
                        unsigned colorInt = 0;
                        
                        [[NSScanner scannerWithString:tempHex] scanHexInt:&colorInt];
                        
                        UIView *bgView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 30, 30)];
                        bgView.center = frame.center;
                        bgView.backgroundColor = UIColorFromRGB(colorInt);;
                        bgView.layer.cornerRadius = 3;
                        bgView.clipsToBounds = YES;
                        [aView addSubview:bgView];
                        
                        UIImageView *imgIcon = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, 25, 25)];
                        imgIcon.center = frame.center;
                        
                        
                        
                        NSString *imagePath = [Utils foursquareImageExisted:annotation.foursquareIcon];
                        if (imagePath) {
                            UIImage *image = [UIImage imageWithContentsOfFile:imagePath];
                            [imgIcon setImage:image];
                        } else {
                            [imgIcon sd_setImageWithURL:[NSURL URLWithString:annotation.foursquareIcon]];
                        }
                        
                        
                        [aView addSubview:imgIcon];
                        annotationView.aView = aView;
                        [annotationView addSubview:annotationView.aView];
                        aView.transform = CGAffineTransformMakeScale(0.1, 0.1);
                        [UIView animateWithDuration:.75 delay:0 usingSpringWithDamping:0.5 initialSpringVelocity:0.3 options:UIViewAnimationOptionCurveEaseOut animations:^{
                            aView.transform = CGAffineTransformMakeScale(1.0, 1.0);
                        } completion:^(BOOL finished) {
                            
                        }];
                        
                        
                        
                        imgView.viewSize = CGSizeZero;
                    }
                } else if (annotation.type == TypeRedDot) {
                    if ([GoongInstance.currentMarkerType containsObject:@"SUGGESTION"]) {
                        annotationView.frame = CGRectMake(0, 0, 8, 8);
                        
                        imgView.viewSize = CGSizeZero;
                        NSString *tempHex;
                        if ([annotation.bgColorHex.description containsString:@"#"]) {
                            tempHex = [annotation.bgColorHex stringByReplacingOccurrencesOfString:@"#" withString:@"0x"];
                        }
                        unsigned colorInt = 0;
                        
                        [[NSScanner scannerWithString:tempHex] scanHexInt:&colorInt];
                        UIView *view = [[UIView alloc] initWithFrame:CGRectMake(0, 0, annotationView.width, annotationView.height)];
                        view.backgroundColor = UIColorFromRGB(colorInt);
                        view.layer.cornerRadius = view.height/2;
                        view.clipsToBounds = YES;
                        view.layer.borderColor = [UIColor whiteColor].CGColor;
                        view.layer.borderWidth = 1;
                        [Utils addShadowToView:view size:CGSizeMake(0, 1)];
                        [annotationView addSubview:view];
                        view.transform = CGAffineTransformMakeScale(0.1, 0.1);
                        [UIView animateWithDuration:.75 delay:0 usingSpringWithDamping:0.5 initialSpringVelocity:0.3 options:UIViewAnimationOptionCurveEaseOut animations:^{
                            view.transform = CGAffineTransformMakeScale(1.0, 1.0);
                        } completion:^(BOOL finished) {
                            
                        }];
                        
                    } else
                        annotationView.frame = CGRectMake(0, 0, 12, 12);
                    
                    
                } else if (annotation.type == TypeSaved) {
                    annotationView.frame = CGRectMake(0, 0, 35, 35);
                } else if (annotation.type == TypeDroppin) {
                    
                        imgView.bottom = annotationView.centerY;
                        imgView.left = annotationView.centerX;
                    
                    
                }
                if (annotation.type == TypeABC) {
                    imgView.bottom = annotationView.centerY;
                    imgView.left = annotationView.centerX;
                }
                
                
                if ([GoongInstance.currentMarkerType containsObject:@"SUGGESTION"] && annotation.type == TypeMarker) {
                    // Display marker name beside icon
                    BorderdLabel *lblTitle = [[BorderdLabel alloc] init];
                    lblTitle.numberOfLines = 2;
                    lblTitle.text = annotation.title;
                    lblTitle.font = [UIFont systemFontOfSize:10];
                    lblTitle.frame = CGRectMake(0, 0, 60, 30);
                    lblTitle.left = 40;
                    lblTitle.top = imgView.y + 5;
                    lblTitle.textColor = [UIColor blackColor];
                    
                    
                    
                    EDStarRating *starRating = [[EDStarRating alloc] init];
                    starRating.starHighlightedImage = [UIImage imageNamed:@"star_selected"];
                    starRating.maxRating = 5.0;
                    starRating.editable=NO;
                    starRating.displayMode=EDStarRatingDisplayFull;
                    starRating.horizontalMargin = 0;
                    starRating.frame = CGRectMake(0, 0, 90, 20);
                    starRating.left = 35;
                    starRating.top = lblTitle.bottom-5;
                    starRating.backgroundColor = [UIColor clearColor];
                    
                    starRating.rating= [annotation.starPoint doubleValue] / 2;
                    annotationView.lblTitle = lblTitle;
                    annotationView.ratingView = starRating;
                    
                    [annotationView addSubview:annotationView.lblTitle];
                    [annotationView addSubview:annotationView.ratingView];
                    
                }
                
                return annotationView;
                
            } else {
                MBXAnnotationView *annotationView = (MBXAnnotationView *)[self dequeueReusableAnnotationViewWithIdentifier:annotation.reuseIdentifier];
                
                if (!annotationView) {
                    annotationView = [[MBXAnnotationView alloc] initWithReuseIdentifier:annotation.reuseIdentifier];
                    annotationView.frame = CGRectMake(0, 0, 50, 50);
                    annotationView.layer.cornerRadius = annotationView.width/2;
                    annotationView.scalesWithViewingDistance = NO;
                    annotationView.clipsToBounds = YES;
                }
                
                UIImageView *imgView = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, 20, 20)];
                imgView.layer.borderColor = [UIColor greenColor].CGColor;
                imgView.layer.borderWidth = 1;
                imgView.layer.cornerRadius = imgView.frame.size.height/2;
                imgView.clipsToBounds = YES;
                imgView.center = CGPointMake(annotationView.width/2, annotationView.width/2);
                NSURL *avatarURL = [NSURL new];
                if (![annotation.avatarURL isKindOfClass:[NSNull class]] && [annotation.avatarURL containsString:@"http"]) {
                    avatarURL = [NSURL URLWithString:annotation.avatarURL];
                    [imgView sd_setImageWithURL:avatarURL placeholderImage:[UIImage imageNamed:@"contact_avatar"]];
                } else
                    [imgView setImage:[UIImage imageNamed:@"contact_avatar"]];
                [annotationView addSubview:imgView];
                imgView.transform = CGAffineTransformMakeScale(0.1, 0.1);
                [UIView animateWithDuration:.75 delay:0 usingSpringWithDamping:0.5 initialSpringVelocity:0.3 options:UIViewAnimationOptionCurveEaseOut animations:^{
                    imgView.transform = CGAffineTransformMakeScale(1.0, 1.0);
                } completion:^(BOOL finished) {
                    
                }];
                

                return annotationView;
                
            }
            
            
        }
    }
    
    
    return nil;
}`



2. Add annotation
` GoongAnnotation *ann = [[GoongAnnotation alloc] init];
                        ann.coordinate = coor;
                        ann.title = [dict valueForKey:@"name"];
                        ann.markerID = [[dict valueForKey:@"id"] stringValue];
                        ann.likeCount = [dict valueForKey:@"like_count"];
                        ann.countRating = [dict valueForKey:@"count_rating"];
                        ann.dislikeCount = [dict valueForKey:@"dislike_count"];
                        ann.starPoint = [dict valueForKey:@"rating_point"];
                        ann.subtitle = [dict valueForKey:@"description"];
                        ann.sharedByUser = [dict valueForKey:@"user_full_name"];
                        ann.bgColorHex = [dict valueForKey:@"icon_bg_corlor"];
                        NSString *iconURL = [dict valueForKey:@"icon_url"];
                        if ([iconURL.description containsString:@"http"]) {
                            ann.foursquareIcon = iconURL;
                            
                            UIApplication*    app = [UIApplication sharedApplication];
                            __block UIBackgroundTaskIdentifier task;

                            task = [app beginBackgroundTaskWithExpirationHandler:^{
                                [app endBackgroundTask:task];
                                task = UIBackgroundTaskInvalid;
                            }];
                            // Start the long-running task and return immediately.
                            dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
                                
                                // Do the work associated with the task.
//                                NSLog(@"Started background task timeremaining = %f", [app backgroundTimeRemaining]);
                               
                                NSURL *documentsDirectoryURL = [[NSURL alloc] initFileURLWithPath:[Utils createLocalImageFolder]];
                                NSString *imagePath = [Utils foursquareImageExisted:iconURL];
                                if (!imagePath) {
                                    NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
                                    AFURLSessionManager *manager = [[AFURLSessionManager alloc] initWithSessionConfiguration:configuration];
                                    
                                    NSURL *URL = [NSURL URLWithString:iconURL];
                                    NSURLRequest *request = [NSURLRequest requestWithURL:URL];
                                    
                                    NSURLSessionDownloadTask *downloadTask = [manager downloadTaskWithRequest:request progress:nil destination:^NSURL *(NSURL *targetPath, NSURLResponse *response) {
                                        
                                        NSString* imageUrl = [[response.URL.absoluteString componentsSeparatedByString:@"/"] lastObject];
                                        NSRange range = [imageUrl rangeOfString:@".png"];
                                        NSString *newPath = [imageUrl stringByReplacingCharactersInRange:NSMakeRange(range.location+4, imageUrl.length - range.location - range.length) withString:@""];
                                        return [documentsDirectoryURL URLByAppendingPathComponent:newPath];
                                    } completionHandler:^(NSURLResponse *response, NSURL *filePath, NSError *error) {
                                        NSLog(@"File downloaded: %@", [[filePath.absoluteString componentsSeparatedByString:@"/"] lastObject]);
                                    }];
                                    [downloadTask resume];
                                }
                                
                                [app endBackgroundTask:task];
                                task = UIBackgroundTaskInvalid;
                            });
                        } else ann.foursquareIcon = nil;
                        
                        NSString *imgName = nil;
                        NSString *markerType = [dict valueForKey:@"marker_type_code"];
                        ann.reuseIdentifier = markerType;
                        if (resultAdd == OK_MARKER) {
                            ann.type = TypeMarker;
                            imgName = [Utils imageNameFromMarkerType:markerType markerName:ann.title];
                            ann.image = [UIImage imageNamed:imgName];
                            
                        } else {
                            ann.type = TypeRedDot;
                            ann.reuseIdentifier = @"reddot";
                            ann.image = [UIImage imageNamed:@"red_dot.png"];
                        }
                        if (!GoongInstance.mapboxRegionIsChanging) {
                            [mapBoxView addAnnotation:ann];
                        }`

3. In PickLocationButton:
`import UIKit

class PickLocationButton: UIButton, LocationPickerDelegate {
    func didPick(_ location: GeoCodeLocation!) {
        geoLocation = location
        self.setTitle(" " + location.address, for: .normal)
        self.contentHorizontalAlignment = .left
    }
    var geoLocation: GeoCodeLocation!
    override func awakeFromNib() {
        super.awakeFromNib()
        self.addTarget(self, action: #selector(onClick), for: .touchUpInside)
    }
    @objc func onClick() {
        let topVC = currentTopViewController()
        let pickLocationVC = LocationPickerViewController()
        pickLocationVC.delegate = self
        pickLocationVC.mapBoxView = GlobalObject.sharedInstance().mapBoxView
        if let annotations = GlobalObject.sharedInstance().mapBoxView.annotations {
//            GlobalObject.sharedInstance().mapBoxView.removeAnnotations(annotations)
        }
        
        topVC?.present(pickLocationVC, animated: true, completion: nil)
                
    }
    func currentTopViewController() -> UIViewController? {
        var topVC = UIApplication.shared.keyWindow?.rootViewController
        while topVC?.presentedViewController != nil {
            topVC = topVC?.presentedViewController
        }
        return topVC
    }
}`

4. In LocationPickerViewController
`-(void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    _mapBoxView.frame = CGRectMake(0, 0, _mapView.width, _mapView.height);
    _mapBoxView.delegate = self;
    [self.mapView addSubview:_mapBoxView];
    _mapBoxView.scaleBar.hidden = false;
    geoLocation = [[GeoCodeLocation alloc] init];
}`

Here is the video 

https://youtu.be/uW-TpLZVOno

**Comment by jfirebaugh** [comment]
Stale.
