### ISSUE TITLE
API for an UncaughtExceptionHandler

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#10188]
Currently when an exception is thrown in the codepath of a callback from native to the JVM we will get a native stacktrace with:

```java
assertion "terminating with uncaught exception of type jni::PendingJavaException" failed
```

We can catch such issues with a  try/catch as follows:

```cpp
try {
       javaPeer->Call(*_env, onMapChanged, (int) change);
} catch(jni::PendingJavaException&) {
       _env->ExceptionDescribe();
}
```

Though there are use-cases where we want to throw an exception to point out a programming error. 
Capturing from chat that the best way forward would be to look into adding an API for an UncaughtExceptionHandler.

**Comment by tobrun** [comment]
adding a note here that this also impacts other callbacks as eg. MapSnapshotter.

**Comment by Tsabary** [comment]
I am recieving the same
terminating with uncaught exception of type jni::PendingJavaException" failed
error. It makes my app ceash frequently. I've tried to go through all the threads with the same issue but they sem to resolve with a new update, where I am currently using the most latest version.
