### ISSUE TITLE
Heading returns nil

### ISSUE THREAD

**Issue by mikaelhellqvist** [mapbox/mapbox-gl-native#10181]
**Platform: iPhone**
**Mapbox SDK version: 3.6.3**

Heading always shows nil.

func mapViewDidFinishLoadingMap(_ mapView: MGLMapView) {
  mapView.showsUserLocation = true
  mapView.userTrackingMode = .follow
}

func mapView(_ mapView: MGLMapView, didUpdate userLocation: MGLUserLocation?) {
        print(userLocation?.coordinate)
        print(userLocation?.heading)
}

The coordinates prints out just fine, but not heading.

**Comment by friedbunny** [comment]
Heading is not provided by the map view’s location manager unless the user tracking mode is `.followWithHeading` or if [`MGLMapView.showsUserHeadingIndicator`](https://www.mapbox.com/ios-sdk/api/3.6.4/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)showsUserHeadingIndicator) is enabled.

**Comment by mikaelhellqvist** [comment]
I've tried that as well and it still doesn't work. It still outputs nil. And shouldn't the user annotation be changed to a dot with a small triangle indicating the heading?

**Comment by mikaelhellqvist** [comment]
Ok it's solved.

Instead of:
mapView.showsUserLocation = true
mapView.userTrackingMode = .followWithHeading

I had to swap the lines:
mapView.userTrackingMode = .followWithHeading
mapView.showsUserLocation = true
