### ISSUE TITLE
Failing on raster-masking/overlapping-zoom

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-native#10195]
Tests are failing on the raster-masking/overlapping-zoom test added in https://github.com/mapbox/mapbox-gl-js/commit/060bd313cbec3971d26bbdb600dbea0c76215de0.

cc @mollymerp

**Comment by mollymerp** [comment]
these were passing before. do you know when they started failing?

**Comment by mollymerp** [comment]
a brief glance at recent PRs makes me think this is a likely culprit cc @kkaefer  https://github.com/mapbox/mapbox-gl-native/pull/10186
