### ISSUE TITLE
[android] Single marker z-order: keep a marker on top of everything else, moving it continuously

### ISSUE THREAD

**Issue by nicomazz** [mapbox/mapbox-gl-native#10193]
**Platform:** Android
**Mapbox SDK version:** 5.1.3
There is currently no way to adjust the z-index of each marker individually.
There are already many questions about this on stackoverflow (without real solutions).
The problem with using marker levels is that the continuous shift of one of these triggers performance issues.
I think it would be very handy and useful to many.

**Desired behavior:**
With a map full of POIs, a custom marker for the position of the user in continuous motion. This last marker should always be above all others.

**Comment by tobrun** [comment]
The desired behavior can be achieved with having a separate SymbolLayer. FWIW we have LocationLayer plugin that does exactly this in https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/locationlayer.

**Comment by farfromrefug** [comment]
@tobrun wouldn't be good to have it as symbol property? It could be very useful for GeoJSON or Marker to make some appear on top of each others.
Plus if we have multiple markers with zIndex we would not need to create one Symbol Layer per marker.

**Comment by Xgamefactory** [comment]
we are totally agree. juwst take mapbox ios sdk or heremaps or other prof instread of making hard such simple things.

**Comment by tobrun** [comment]
With the upcoming 6.6.0 release symbol layer will support z ordering based on data ordering:
 - see PR in https://github.com/mapbox/mapbox-gl-native/pull/12783

That said, I'm working on an annotation plugin that will integrate above but in an easier use api. You will be able to provide an int value and we will show markers above another based on that value. Annotation plugin is in the works [here](https://github.com/mapbox/mapbox-gl-native/pull/12783), code for z symbol ordering is implemented but requires the release of 6.6.0 first. See feature request [here](https://github.com/mapbox/mapbox-plugins-android/issues/657).
