### ISSUE TITLE
tessellation errors

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1019]
Are tessellation errors on water polygons expected? E.g. Great Lakes area:

![image](https://cloud.githubusercontent.com/assets/98601/6697901/25d43d50-ccb1-11e4-93d4-8f584cd19214.png)

With this style:

```
{
  "version": 7,
  "sources": {
    "mapbox": {
      "type": "vector",
      "url": "mapbox://mapbox.mapbox-streets-v6"
    }
  },
  "layers": [{
    "id": "background",
    "type": "background",
    "paint": {
      "background-color": "white"
    }
  }, {
    "id": "land",
    "type": "fill",
    "source": "mapbox",
    "source-layer": "water",
    "paint": {
      "fill-color": "rgba(255,0,0,1)",
      "fill-opacity": 0.5
    }
  }]
}
```

I'm assuming we typically don't notice this because it isn't visible with an opaque fill.

**Comment by ansis** [comment]
@jfirebaugh I'm fairly sure this is not a tessellation issue. I think there are multiple overlapping water polygons in the vector tiles. I didn't check this now, but I remember running into this a long time ago.

**Comment by ansis** [comment]
Just checked and these are data issues.

**Comment by 1ec5** [comment]
Background info: http://thread.gmane.org/gmane.comp.gis.openstreetmap.region.us/15019

**Comment by kkaefer** [comment]
FWIW, this shouldn't happen since we're merging all polygons with Clipper. Are you seeing this in native?

**Comment by ansis** [comment]
@kkaefer -native merges polygons within a single feature but not across features. These are two features with overlapping geometries.

**Comment by kkaefer** [comment]
Ah, gotcha
