### ISSUE TITLE
LocationLayerPlugin hidden @5.2.0-beta.1

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-gl-native#10192]
Hey,

if I have this setup
```
compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-beta.1@aar') {
	transitive = true
}
compile 'com.mapbox.mapboxsdk:mapbox-android-telemetry:2.2.5'
compile 'com.mapbox.mapboxsdk:mapbox-android-services:2.2.6'
compile('com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0-SNAPSHOT') {
	transitive = true
}
compile('com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.2.0-SNAPSHOT') {
	transitive = true
}
```

I don't really know how to describe this issue well. Therefore I made two screen videos. 
There a no location updates or other method calls beside setMapboxLocationLayerMode(this, LocationLayerMode.TRACKING) or setMapboxLocationLayerMode(this, LocationLayerMode.NAVIGATION) and a simple camera animation after my button click. If I rotate the mapview, the locationLayerPlugin is hidden at a specific angle to the route.

This issue doesn't occur with mapbox-android-sdk:5.1.4@aar, only with mapbox-android-sdk:@5.2.0-beta.1.

1. LocationLayerMode.NAVIGATION
![ezgif com-video-to-gif-7](https://user-images.githubusercontent.com/23097192/31526270-04cdf29a-afc6-11e7-9655-9200ce16c9c4.gif)

2. LocationLayerMode.TRACKING
![ezgif com-video-to-gif-5](https://user-images.githubusercontent.com/23097192/31526221-b7cb9614-afc5-11e7-92f6-4d0a452530e2.gif)

**Comment by tobrun** [comment]
We recently noticed the same, was related to bumping dependencies to 5.2.0-beta.1. The issue will be fixed when components in the dependency section have been updated to 5.2.0. Thank you for the report and using Mapbox!
