### ISSUE TITLE
iOS: offline region downloads are faster when downloaded at least one offline pack before

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#10209]
I'm not sure this is normal behaviour but I have no explanation for it... When downloading an offline pack with the latest mapbox ios sdk, the first downloaded pack is downloading very slow. But once you downloaded one pack, the next are downloading faster.

**Comment by jfirebaugh** [comment]
This is expected behavior; identical resources that used by multiple packs are shared between those packs, and there are almost always some shared resources (glyphs, for example).
