### ISSUE TITLE
[Android] Performance issue and fps drops in packed areas

### ISSUE THREAD

**Issue by schachi5000** [mapbox/mapbox-gl-native#10200]
Hi there,

I'm currently evaluating Mapbox as a possible replacement in our navigation app.
While playing around with the Android SDK and the current version of the Android Sample App 
I've noticed major performance issues on one of our test devices. Zooming and camera animation, in general, tend to stutter and skip frames a lot. 

Normally we would classify this as one of our 'beefier' devices since it performed very admirable with the Map Engine we are currently using, but with Mapbox, we would sadly rank it very low in regards to performance.  

Are there perhaps ways to reduce render load or any best practices how to improve performance?

**Device Info**
Sony Xperia Z3 Tablet Compact (SGP621)
Android 6.0.1

**How to reproduce**
The simplest way to reproduce the issue would be to run the **Animate the map camera** in the Sample App on said device.

![example](https://user-images.githubusercontent.com/25952987/31603315-0a014ebe-b260-11e7-9447-1b408a0f8f91.gif)

**Comment by tobrun** [comment]
@schachi5000 
which version of the SDK are you using? with the upcoming 5.2.0 release we are making multiple changes that will result in a smoother experience. You can test out the 5.2.0 release when using `5.2.0-beta.1` as SDK version as your gradle dependency.

 -  migration to GLSurfaceView in #9576: 
    - this moves rendering from the main thread to a separate render thread and as a result we rarely drop any frames (see gif below)
 - animations using Android SDK animators in https://github.com/mapbox/mapbox-gl-native/pull/10001
    - this allows for a creating smoother/flexible animations than the currently exposed animation framework (also demonstrated in gif below)
   - note that we are still migrating our gestures and the older animation api https://github.com/mapbox/mapbox-gl-native/issues/8175

![30490690-0ce00270-9a3b-11e7-89fa-5bcb0f0210b4](https://user-images.githubusercontent.com/2151639/31605016-637061f6-b265-11e7-9e25-9cf7774db96a.gif)



I'm going to close this as this issue itself is not actionable, we aim to improve the experience with every release. Feel free to reach out if you have any questions/suggestions/contributions.
