### ISSUE TITLE
RasterSource for custom maptile host for Android SDK

### ISSUE THREAD

**Issue by 1412276** [mapbox/mapbox-gl-native#10206]
I'm using **Mapbox iOS SDK** and find a way to add my own custom map tile as a layer to map like this: 

```
let source = MGLRasterSource(identifier: "stamen-watercolor", tileURLTemplates: ["https://stamen-tiles.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg"], options: [ .tileSize: 256 ])
 let rasterLayer = MGLRasterStyleLayer(identifier: "stamen-watercolor", source: source)
 style.addSource(source)
 style.addLayer(rasterLayer) 
```
But I can't find something similar in **Android SDK** to load **http://xyz.com/{z}/{x}/{y}.jpg**. Can you implement this method for RasterSource class. Thank you.

**Comment by tobrun** [comment]
@1412276 have you tried using the `RasterSource(String id, TileSet tileSet)`?

**Comment by 1412276** [comment]
@tobrun I have tried but nothing is shown, can you explain the parameters of TileSet I shoud put correctly?. Thank you.
```RasterSource source = new RasterSource("source", new TileSet("tileset", "http://120.72.116.80/tiles/AnhCat/77006/{z}/{x}/{y}.pbf"), 256);
  mMap.addSource(source);
  RasterLayer layer = new RasterLayer("layer", "source");
  mMap.addLayer(layer);```

**Comment by tobrun** [comment]
@1412276 do you see anything logged when you execute above code?
In any case, TileSet first parameter is: `A semver.org style version number. Describes the version of the TileJSON spec that is implemented by this JSON object.` So could you try replacing `"tileset"` with `"2.1.0"`?

**Comment by 1412276** [comment]
@tobrun Oh, I just move above code to **onMapChange** function instead of **onMapReady** and it works perfectly. Maybe the map doesn't finish loading when i add the source and layer to it. Thank for your help. 
![screenshot_20171019-005015](https://user-images.githubusercontent.com/32338074/31734121-db1e19a6-b467-11e7-8802-086c83bed205.png)
