### ISSUE TITLE
[ios, macos] Display the shape annotation's callout when the center coordinate is off viewport.

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/mapbox-gl-native#10229]
For shapes that outbound the current viewport the center coordinate may be outside the current viewport thus will not be able to display the callout when selected.

From this comment's [thread](https://github.com/mapbox/mapbox-gl-native/pull/9984#discussion_r138705129) two possible solutions would be either pan to the selected shape annotation’s centroid or anchor the callout at the tap location when the centroid is off the current viewport.

/cc @bounds @frederoni @1ec5

**Comment by lilykaiser** [comment]
Can this be closed?

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/10255
