### ISSUE TITLE
[ios, macos] Return a shape annotation the second time, as long as persist is set to YES.

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/mapbox-gl-native#10228]
From this [comment](https://github.com/mapbox/mapbox-gl-native/pull/9984#discussion_r145513504).

> If there is both a point annotation and a shape annotation beneath the passed-in point, this method should return the point annotation the first time this method is called and the shape annotation the second time, as long as persist is set to YES. That way the shape annotation remains accessible even when there is an overlapping point annotation.

/cc @1ec5

**Comment by lilykaiser** [comment]
Can this be closed?

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/10262
