### ISSUE TITLE
Could more caches even if the number exceeds 6000.

### ISSUE THREAD

**Issue by noramimiyuma** [mapbox/mapbox-gl-native#10236]
**Platform: iPhone Simulator (iPhone7 - iOS10.3)**
**Mapbox SDK version: iOS-3.7.0-beta.1**

In downloading maps. (Offline Caching)

### Expected behavior
If the cached style reaches 6000, The following method is called and the cancel more offline caching. 
`- (void)offlinePackMaximumMapboxTilesReachedNotification:(NSNotification*)notification;`

### Actual behavior
Not called the method, so I can download more than 6000 caches.
As far as I confirmed, it exceeds 24000, but I was able to download a new cache.
The file size of cache.db was 541 MB.

<img width="1334" alt="ScreenShot+cache.db" src="https://user-images.githubusercontent.com/15150828/31762397-013f3384-b4f6-11e7-847a-83cffb5b3014.png">

**Comment by boundsj** [comment]
I tried to reproduce this, running at the head of the [release-agua](https://github.com/mapbox/mapbox-gl-native/tree/release-agua) branch (our next planned release) with the `iosapp` app. I attempted to download an offline region around the size of the San Francisco Bay Area in the United States.

The `iosapp` runs with the 6k tile limit by default and, when I ran my test, I hit the expected limitation handled by [this implementation](https://github.com/mapbox/mapbox-gl-native/blob/release-agua/platform/ios/app/MBXOfflinePacksTableViewController.m#L260-L266) in the `iosapp`.

So, I'm unable to reproduce this. Can you say more about how your application is able to download beyond the default tile limit? Any code or an example project you can provide would be helpful.
