### ISSUE TITLE
Crash applying two styles in tandem

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1023]
Very similar to #1014, we get the following crash on iOS when trying to apply a style synchronously immediately after applying a style:

```
#4	0x00000001005bee4b in mbgl::Map::stop(std::__1::function<void ()>) at /Users/mxn/hub/mapbox-gl-native-2/src/mbgl/map/map.cpp:181
#5	0x00000001005c238b in mbgl::Map::setStyleURL(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) at /Users/mxn/hub/mapbox-gl-native-2/src/mbgl/map/map.cpp:354
#6	0x000000010082c36e in -[MGLMapView setStyleURL:] at /Users/mxn/hub/mapbox-gl-native-2/platform/ios/MGLMapView.mm:192
```

We’re failing this assertion in `mbgl::Map::stop()`:

```
assert(mainThread != mapThread);
```

**Comment by 1ec5** [comment]
Also occurs in the demo app if you triple-tap the style switcher.

Belongs on the beta 2 milestone because we’re planning to omit support for multiple styles from beta 1 in #1031.

**Comment by incanus** [comment]
I think this is obsolete now with the recent `MapData` work bringing stability to style switching.

**Comment by 1ec5** [comment]
Yes, it was fixed by that work.
