### ISSUE TITLE
Clipped labels appear on static map

### ISSUE THREAD

**Issue by mase7569** [mapbox/mapbox-gl-native#10237]
**Platform:** Web browser, laptop

### Steps to trigger behavior

 1. Request a static map: eg. at -73.98572; 40.74843, zoom-level 16 (500x500px).
 2. Inspect the generated image - clipped labels appear.
     For example: lower left corner, "A. D &" appears. Mid lower left above label "H mart" the text "nford" appears.)

### Expected behavior
Same appearance in static and dynamic map.
![27735086-1f65c74c-5d9e-11e7-87f6-a69ea8170ada](https://user-images.githubusercontent.com/17294047/31767472-7c21f3a0-b4cb-11e7-8872-74b95882d449.png)

### Actual behavior
Clipped labels appear in the static map, in some places, some zoom-levels.
![27735068-0799f03e-5d9e-11e7-86d2-ba6790e29035](https://user-images.githubusercontent.com/17294047/31767476-86750400-b4cb-11e7-9a03-bd18f0335e29.png)

**Comment by fabian-guerra** [comment]
Hi, @mase7569. Thank you for using Mapbox Studio. I am sorry to hear you are having some issues. This repo is for our GL SDK's (iOS/macOS/Android/QT). I am going to close this ticket and let the Studio team know about the problem.

/cc @tristen
