### ISSUE TITLE
map class-related methods should accept transition options

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1025]
`addClass`, `removeClass` and `setClasses` should accept options to control the transition duration or disable transitions entirely.

`MGLMapView::setStyleClasses` should use this option rather than calling `setDefaultTransitionDuration`.

**Comment by robipresotto** [comment]
exactly, on the current build version (https://github.com/mapbox/mapbox-gl-native/commit/4eb48683d6) the transition not work and the style class change only after a zoom on map.
