### ISSUE TITLE
[node] removeSource not working

### ISSUE THREAD

**Issue by edpop** [mapbox/mapbox-gl-native#10265]
Hello.
It seems that **map.removeSource** does not work. Unfortunately, there is almost no documentation, so I hope I'm doing it right.

**Platform:** Node
**Mapbox SDK version:** @mapbox/mapbox-gl-native: 3.5.8

### Steps to trigger behavior

```js
const sharp = require('sharp');
const mbgl = require('@mapbox/mapbox-gl-native');

const image = __dirname + '/pic.png';

const map = new mbgl.Map({
	request: () => {},
	ratio: 1
});

const style = {
	sources: {},
	layers: [{
		id: 'circle',
		source: 'my_point',
		type: 'circle',
		paint: {
			'circle-color': '#2A9D44',
			'circle-radius': 30
		}
	}]
}

map.load(style);
map.addSource('my_point', {
	type: 'geojson',
	data: {
		type: 'Feature',
		geometry: {
			type: 'Point',
			coordinates: [0, 0]
		},
		properties: {}
	}
});
map.removeSource('my_point');

const mapPosition = {
	zoom: 0,
	width: 512,
	height: 512,
	center: [0, 0]
}

map.render(mapPosition, function (err, buffer) {
	if (err) throw err;

	sharp(buffer, {
		raw: {
			width: mapPosition.width,
			height: mapPosition.height,
			channels: 4
		}
	}).toFile(image, function (err) {
		if (err) throw err;

		console.info('OK!');
		process.exit(0);
	});
});
```

### Expected behavior
Do not see the green dot

### Actual behavior
I see the green dot

output:
>libEGL warning: failed to create a pipe screen for i965
>OK!

Node 6.9.1 Ubuntu 14.04

**Comment by jfirebaugh** [comment]
If there's a layer using a source, it cannot be removed from the style. If you want the green dot to be hidden, you can remove the layer or set its visibility to hidden.

**Comment by edpop** [comment]
Thanks for answer. So, if I want to change the geojson, I should remove all layers that use this source, remove source, add new source, and then return layers back...
