### ISSUE TITLE
Map view is slow to respond to some gestures and fly animations

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-gl-native#10266]
The panning / flyto slowness we've been observing on `master` and `agua` seems to be because of some underlying performance problem related to an internal framework method (`_updateConstraintsAsNecessaryAndApplyLayoutFromEngine`) to update constraints. We were exposed to this in https://github.com/mapbox/mapbox-gl-native/pull/9995 by setting `_scaleBar.translatesAutoresizingMaskIntoConstraints = NO;`. 

However, this was not actually a problem before the [last merge](https://github.com/mapbox/mapbox-gl-native/commit/6d1fdf2ca3a93839bc7dc0929599dd096ab00e33) but something about the rendering interface updates done back  in https://github.com/mapbox/mapbox-gl-native/commit/b6d56ad634e2b3048e97bedd9f674aa4ec975453 trigger this problem and are driven by repeated calls to `-[MGLScaleBar setMetersPerPoint:]` in `-[MGLMapView cameraIsChanging]`. 

We see this problem now after the merge since all of the commits to trigger it are in place (there is no problem with the merge itself). The constant updates to the scale bar's frame triggered by the renderer / camera / gesture updates are just too much.

cc @frederoni @1ec5 @fabian-guerra @ivovandongen @lilykaiser

**Comment by boundsj** [comment]
I see that Apple Maps actually shows the scale bar far less than we do (only when the user does a two finger zoom gesture). I've tested and copying that UX works around the issue described here since, if the scale bar is not visible, the `setMetersPerPoint:` message is never sent. I'll make a PR for that workaround.

**Comment by 1ec5** [comment]
> I see that Apple Maps actually shows the scale bar far less than we do (only when the user does a two finger zoom gesture).

That’s the case by default, but the scale bar is always visible when `showsScale` is true.

**Comment by frederoni** [comment]
Can we have another range index so we don't have to find the preferred row or limit the number of calls to `setMetersPerPoint:` by rounding?

**Comment by boundsj** [comment]
> That’s the case by default, but the scale bar is always visible when showsScale is true.

Good point. Let's not implement that workaround I [mentioned before](https://github.com/mapbox/mapbox-gl-native/issues/10266#issuecomment-338879721) then.

> Can we have another range index so we don't have to find the preferred row or limit the number of calls to setMetersPerPoint: by rounding?

That may be a good / the best? idea. For now, I've proposed [this workaround](https://github.com/mapbox/mapbox-gl-native/pull/10273) that fixes the UX issues (slow flyto and panning)

**Comment by boundsj** [comment]
I spent more time today digging into why the renderer changes triggered this issue. I think https://github.com/mapbox/mapbox-gl-native/pull/10277 may be a better approach.
