### ISSUE TITLE
Geocoding error search

### ISSUE THREAD

**Issue by VincenzoWiman** [mapbox/mapbox-gl-native#10279]
**Platform:*Android 7.0 *
**Mapbox SDK version:*5.1.4*

### Steps to trigger behavior

 1. Search Bogotà with GeocodingCriteria.TYPE_PLACE

### Expected behavior
Bogotà city
### Actual behavior
Very far from the Bogotà city

**Comment by jfirebaugh** [comment]
Hi @VincenzoWiman! For reporting issues with Mapbox Geocoding results, please use [this page](https://www.mapbox.com/geocoder-feedback/). Thank you!
