### ISSUE TITLE
Loading style images asynchronously does not update relevant layers

### ISSUE THREAD

**Issue by mattijsf** [mapbox/mapbox-gl-native#10271]
**Platform:** Android
**Mapbox SDK version:** 5.2.0-beta.2

### Steps to trigger behavior

 1. Add a (GeoJson) source with some points
 2. Add a `SymbolLayer` referencing an `iconImage` name
 3. Fetch the image(s) asynchronously / delayed
 4. Add the image via `MapboxMap.addImage(name, bitmap)` 

[MainActivity.java.txt](https://github.com/mapbox/mapbox-gl-native/files/1412113/MainActivity.java.txt)

### Expected behavior

The marker images appear on the map as soon as the image referenced in `iconImage` becomes available after being added via `addImage`. 

### Actual behavior

The marker image are never rendered.

**Comment by jfirebaugh** [comment]
This sequence of API calls is not supported. All images used by a symbol layer must be present at the time the layer is added.

**Comment by mattijsf** [comment]
Got it. I guess it is somewhat tricky to know which layers are referencing which images (especially with data-driven styling) But would be a nice to have though! In my use-case I'm using mapbox in a custom react-native component focussing on pure JS based geojson / styling approach. Images are also bridged from react-native which could either be sourced from embedded resources or a URI.

For now I'll postpone loading all the styles untill all images are loaded. Thanks for the feedback!
