### ISSUE TITLE
Ambient cache is not saved when offline cache is saved for 50 MB or more.

### ISSUE THREAD

**Issue by noramimiyuma** [mapbox/mapbox-gl-native#10290]
**Platform:**
iPhone7, iOS 11.0.3

**Mapbox SDK version:**
ios-v3.7.0-beta.2

### Expected behavior
・
・

### Actual behavior
・
・

Ambient cahce

**Comment by boundsj** [comment]
This is a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/4411
