### ISSUE TITLE
Not able to find Mapbox SDK?

### ISSUE THREAD

**Issue by kunalsharma** [mapbox/mapbox-gl-native#10317]
I am getting below error i also tried to download and add but still i am getting issue

Error:Could not find mapbox-android-sdk.aar (com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-beta.3).
Searched in the following locations:
    https://plugins.gradle.org/m2/com/mapbox/mapboxsdk/mapbox-android-sdk/5.2.0-beta.3/mapbox-android-sdk-5.2.0-beta.3.aar

**Comment by tobrun** [comment]
@kunalsharma the dependency is there, could you add your build.gradle dependency entry?

**Comment by kunalsharma** [comment]
I just download the latest code from github. Its not working, If i change the sdk to lower version then the demo start working. 

Once i resolved the error by adding lower sdk version of mapbox i am not able to import below Class
import com.mapbox.turf.TurfHelpers;

**Comment by tobrun** [comment]
Feel free to reach out to us on https://www.mapbox.com/help/
This is not an SDK issue or feature request. 
Thank you for reaching out.
