### ISSUE TITLE
Decrypting the data inside a pbf just before it renders.

### ISSUE THREAD

**Issue by ImCarrot** [mapbox/mapbox-gl-native#10315]
Hi I am working with security on the vector Tiles and this thread is basically a follow up from the actual post on [tippecanoe](https://github.com/mapbox/tippecanoe) about encrypting data inside a pbf for security at [this issue](https://github.com/mapbox/tippecanoe/issues/478#issuecomment-340029684). 

Thanks to the community at `mapbox` i've been able to successfully encrypt the data inside the `.pbf` making it a pair of `key` and `encypted Values`. 

Now I am using `android` and `iOS` `SDKs` on my mobile front and `open-gl` on the web front, 

My question is, can someone point me out to a specific `file` or `function` in the library where the `.pbf` gets deserialized. So that I can decrypt the values and hence get the actual key and values for my map to show data in a secure way, so that even if someone `inspect elements` the `.pbfs`, he/she isn't able to make sense out of the downloaded `.pbf`

**Comment by jfirebaugh** [comment]
You would need to fork the SDK and add code [here](https://github.com/mapbox/mapbox-gl-native/blob/484c04a924565feade99f162826152fcf3acb8b9/src/mbgl/tile/vector_tile_data.cpp#L24-L30).
