### ISSUE TITLE
android sdk geofencing

### ISSUE THREAD

**Issue by caopeng000** [mapbox/mapbox-gl-native#10311]
How to judge whether it is inside or outside the geography fence？

**Comment by tobrun** [comment]
@caopeng000 the maps SDK doesn't expose any geofencing API's, you can use additional third party libraries for that. That said, if you want to determine if a certain `LatLng` is found in a certain area you can use `LatLngBounds#contains(LatLng)`.

**Comment by caopeng000** [comment]
https://www.mapbox.com/bites/00223/

**Comment by caopeng000** [comment]
The official website in the websdk have this support, why not android sdk?
