### ISSUE TITLE
5.2 how to support TextureView

### ISSUE THREAD

**Issue by mister-tang** [mapbox/mapbox-gl-native#10326]
textureMode
**Platform:android
**Mapbox SDK version5.2.0

I am using textureMode, because the app needs to use TextureView to achieve flip, there are other ways to achieve, thank you

**Comment by tobrun** [comment]
@mister-tang we are currently working on bringing this feature back fro 5.2.0, this will be included in the final 5.2.0 and will be testable in a follow up beta release. Thank you for reaching out and using our product!

**Comment by tobrun** [comment]
see https://github.com/mapbox/mapbox-gl-native/pull/10334
