### ISSUE TITLE
SymbolLayer doesn't work on raster tiles

### ISSUE THREAD

**Issue by rakuishi** [mapbox/mapbox-gl-native#10325]
**Platform: Android**
**Mapbox SDK version: 5.2.0-beta.3**

### Steps to trigger behavior

1. Create a map view, which style is raster tiles.
2. Add a GeoJsonSource, and a SymbolLayer.
3. SymbolLayer doesn't show any symbols.

### Expected behavior

SimbolLayer works well on raster tiles.

### Actual behavior

SymbolLayer doesn't work on raster tiles, but other patterns it works well.

| Style | Layer | Behavior |
| ----- | ----- |  ----- |
| Raster Tiles | SimbolLayer | NG |
| Raster Tiles | CircleLayer | OK |
| Style.OUTDOORS | SimbolLayer | OK |
| Style.OUTDOORS | CircleLayer | OK |

### Sample project

I made a sample project to reproduce this problem.
https://github.com/rakuishi/mapbox-raster-tiles-android

The following json is Mapbox style for raster tiles.

```
{
  "version": 8,
  "name": "Raster Tiles",
  "sources": {
    "cyberjapandata": {
      "type": "raster",
      "tiles": [
        "https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png"
      ],
      "tileSize": 256
    }
  },
  "layers": [{
    "id": "cyberjapandata",
    "type": "raster",
    "source": "cyberjapandata"
  }]
}
```

**Comment by jfirebaugh** [comment]
Symbol layers require a style that provides a [`glyphs` property](https://www.mapbox.com/mapbox-gl-js/style-spec/#root-glyphs). If you include that property in your style, it should work.

**Comment by rakuishi** [comment]
Thank you. After adding `glyphs` property, SymbolLayer work well on raster tiles.
