### ISSUE TITLE
RegionDidChange differences between iOS and Android SDK

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-native#10337]
Hey,

while working on the react-native port of gl-native, we've noticed that `RegionDidChange` behaves differently on iOS and Android on user gestures. [Link](https://github.com/mapbox/react-native-mapbox-gl/issues/698).

iOS implements `RegionDidChange` as an event that fires at the end of a user gesture. 
Android fires the event for each animation frame during the user gesture. These should probably be aligned or explicitly defined as different between the SDKs.

**Comment by Jose4gg** [comment]
Any progress with this?

**Comment by dorthwein** [comment]
One work around we did was to wrap the call back in a setTimeout that would reset on each RegionDidChange so we didn't end up spamming/reloading the map constantly.

**Comment by Jose4gg** [comment]
Nothing yet?

**Comment by Jose4gg** [comment]
Is there news about this?
