### ISSUE TITLE
LocationSource request does not respect LocationEngine Settings

### ISSUE THREAD

**Issue by grote** [mapbox/mapbox-gl-native#10335]
It seems that the default `LocationSource` is always using the same hard-coded values to do location requests:

https://github.com/mapbox/mapbox-gl-native/blob/74bcca380dd7faa7a629d59e3346506e6a8cca34/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationSource.java#L105-L108

Shouldn't it use the values provided by the inherited `LocationEngine` instead like so?

```java
    LocationRequest request = LocationRequest.create()
      .setInterval(interval)
      .setFastestInterval(fastestInterval)
      .setSmallestDisplacement(smallestDisplacement);
```

**Comment by tobrun** [comment]
@Guardiola31337 could you look into this as part of #9403?

**Comment by Guardiola31337** [comment]
@grote 👋 Thanks for reaching out and report your problem.

This was addressed in https://github.com/mapbox/mapbox-gl-native/commit/29a94ae939cf1d81017251ec374e3fff703dc4a6

https://github.com/mapbox/mapbox-gl-native/blob/29a94ae939cf1d81017251ec374e3fff703dc4a6/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationSource.java#L132-L142

which was included in the [`mapbox-android-sdk:5.2.0-beta.4`](https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v5.2.0-beta.4) release and it'll be also available in the `5.2.0` final release.

BTW, `LocationSource` is now `@Deprecated` and the location provider is optional (we're not including Lost within the SDK anymore). So, in the case you still use `LocationSource` you'll need to include explicitly the Lost dependency in your `build.gradle` file.

Going ahead and closing here.
Thanks for using Mapbox and feel free to open new tickets if you have any other questions 😉

**Comment by grote** [comment]
Thanks @Guardiola31337!

Do you have a migration guide up somewhere already for all those changes (I am also thinking MarkerView deprecation)? Or a place where it will be published eventually?

**Comment by Guardiola31337** [comment]
@grote sure thing!

When we release `5.2.0` we'll update accordingly the documentation reflecting these changes. We also have the [Android 4.x to 5.0](https://github.com/mapbox/mapbox-gl-native/wiki/Android-4.x-to-5.0-update) migration guide in which definitely we'll include migration guidance for the deprecated APIs in a new section.

Thanks for the heads up!

**Comment by grote** [comment]
@Guardiola31337 have you tested this change with Lost?

With  `mapbox-android-sdk:5.2.0-beta.4` when adding `compile 'com.mapzen.android:lost:3.0.4'`, I am getting this runtime crash:

```
                                     java.lang.NoSuchMethodError: No interface method getLastLocation()Landroid/location/Location; in class Lcom/mapzen/android/lost/api/FusedLocationProviderApi; or its super classes
                                         at com.mapbox.services.android.telemetry.location.LostLocationEngine.getLastLocation(LostLocationEngine.java:85)
                                         at com.mapbox.mapboxsdk.maps.widgets.MyLocationView$GpsLocationListener.onConnected(MyLocationView.java:795)
                                         at com.mapbox.services.android.telemetry.location.LostLocationEngine.activate(LostLocationEngine.java:48)
```

**Comment by Guardiola31337** [comment]
Hey @grote we're still relying on `com.mapzen.android:lost:1.1.1` in `5.2.0-beta.4` (got reverted with #10380) :eyes: https://github.com/mapbox/mapbox-gl-native/issues/9581

For now, including Lost `1.1.1` version should do the trick.

Let me know if it solves your issue. Thanks for reporting!

**Comment by Guardiola31337** [comment]
@grote 👀 https://github.com/mapbox/mapbox-gl-native/issues/9581#issuecomment-343903844
Thanks again!
