### ISSUE TITLE
natural=bay draws water over islands

### ISSUE THREAD

**Issue by JohanEntur** [mapbox/mapbox-gl-native#10330]
Bay overwrites islands
----

- Sorry, I'm not a regular Github-user, nor a programmer so I might be posting this in the wrong place. 

However, the issue I have is with "Tag:natural=bay" overwrites some islands in the Oslo fjord. We are talking about this https://www.openstreetmap.org/relation/6812187#map=12/59.8064/10.7206 overwriting the islands within it. Only roads and buildings and piers remain visible.

This happens in all the default styles in Mapbox studio so it should be fairly easy to recreate.

**From OSM wiki:**
"Since bays are generally part of a larger waterbody, either a lake or the ocean, _they should not be rendered in solid color indicating water themselves_. The Standard tile layer renders named bays with a label."
-  https://wiki.openstreetmap.org/wiki/Tag:natural%3Dbay

**Comment by JohanEntur** [comment]
Bump

**Comment by kkaefer** [comment]
Thanks for your report. We are tracking this bug internally, as it is related to the Mapbox Streets data source we provide. It is, however, not a bug in Mapbox GL itself, just in the way data is processed before they go into the Mapbox-provided vector tiles.
