### ISSUE TITLE
Integrate Metrics

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1033]
Integrate Metrics API into iOS GL.

1. [x] Install MBLocationManager
1. [x] Install [Mapbox Events iOS](https://github.com/mapbox/mapbox-events-ios)
1. [x] Setup metrics gathering
1. [x] Build Opt Out Checking In MGLMapboxEvents
1. [x] Build Disabled Metrics Functionality In MGLMapboxEvents

**Comment by bleege** [comment]
I've got MBLocationManager integrated with Core GL via MGLMapView.  It now is instantiated via [commonInit] and waits patiently for Location to be authorized.  When Location is authorized it piggybacks on those permissions and starts receiving updates.

**Comment by bleege** [comment]
Renamed MBLocationManager to MGLMetricsLocationManager to better fit with project naming conventions.

**Comment by friedbunny** [comment]
There are clear (and solidly established) technical and business cases for collecting this information, but as a developer or end-user it feels icky. 

Reading the [privacy policy](https://www.mapbox.com/privacy/#start) I (naively?) wouldn't expect a UUID, my carrier, battery level, or phone orientation to be transmitted beyond the confines of my device:

>Information Collection, Use, and Sharing

>We do not collect or store any personally identifiable user data, except what you voluntarily provide through mapbox.com or other direct contact. We do not share this information with anyone outside of Mapbox.

>We do collect IP addresses of devices accessing our services in our server logs, as well as information like internet domains, the date and time of a visit, and the pages accessed on mapbox.com. This information is used solely for diagnostic and analytic purposes in order to improve the services we provide.

>We ONLY use anonymized data with data providers for the purposes of improving our platform.

It's probably not reasonable to expect this to move to opt-in/out, but I feel that the privacy policy should be amended to be as explicit as possible about what information is sent over the air. Not that anyone reads privacy policies...

**Comment by bleege** [comment]
Hey @friedbunny, sorry for the confusion here. See the [PR](https://github.com/mapbox/mapbox-gl-native/pull/1036) for some more context on where this is headed. We're trying to keep all discussion on the review over there so it's in one place.

**Comment by bleege** [comment]
Mapbox Events iOS is now integrated and has successfully sent a batch of events to the Mapbox API.  The Opt Out functionality now needs to be added.

**Comment by bleege** [comment]
Need to build:

1. Opt Out Checking
1. Disabled Metrics Checking

**Comment by bleege** [comment]
Added logic to flush all remaining metric events in the event queue when the app enters the background.  This alleviates the need to persist them on the file system.

**Comment by bleege** [comment]
Screenshot of Settings.app for Mapbox GL showing Metrics Opt Out control.

![20150324-settings-mapbox-opt-out](https://cloud.githubusercontent.com/assets/989928/6806170/17a5ed1e-d215-11e4-8060-075a58d6d1e1.png)

**Comment by bleege** [comment]
Should also note that whenever the end user Opts Out of Mapbox Metrics, any events that may still be on the device but haven't been sent yet are immediately deleted.

**Comment by bleege** [comment]
Just built the Metrics Disabled UI in Settings.app and functionality to support it in the Events infrastructure.  The screenshot below is what it'll look like to end users.

![20150324-settings-mapbox-metrics-disabled](https://cloud.githubusercontent.com/assets/989928/6806979/ce151fa8-d219-11e4-9ddf-d94658c4a364.png)

**Comment by bleege** [comment]
Everything is built.  Will start merging into `master` next.

**Comment by freenerd** [comment]
Could the _Mapbox Metrics_ screen have a one-sentence explanation of what it means? Grey text like screenshot below:

![2015-03-24 at 21 34](https://cloud.githubusercontent.com/assets/25713/6812239/d60b294c-d26d-11e4-8689-26a40686ee79.png)

Text like 

> Send annonymized statistics to Mapbox for improving map quality

**Comment by 1ec5** [comment]
For gray text, I think you want [`PSTitleValueSpecifier`](https://developer.apple.com/library/ios/documentation/PreferenceSettings/Conceptual/SettingsApplicationSchemaReference/Articles/PSTitleValueSpecifier.html#//apple_ref/doc/uid/TP40007015-SW1).

**Comment by bleege** [comment]
Just merged in #1036.
