### ISSUE TITLE
[node] Node.js 8 support

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-native#10343]
Node.js 8 Moves into Long-Term Support, with a big improvement both in syntax and performance. Would you consider upgrade node-mapbox-gl-native with Node.js 8 support?

**Comment by jfirebaugh** [comment]
In order to keep our test matrix to a reasonable size, we're going to hold off until we can drop node 4 support, which is pending some server-side work here at Mapbox.
