### ISSUE TITLE
Render CJK glyphs at client side [Android/iOS]

### ISSUE THREAD

**Issue by chriswu42** [mapbox/mapbox-gl-native#10340]
### Summary
[Loading CJK glyphs at the client side](https://www.mapbox.com/mapbox-gl-js/example/local-ideographs/) enables significantly faster map loads than downloading font packages per query. For example, we can reduce the overall map package from 15mb to 1.5mb using this technique - this is something that many developers/customers in Asia are looking to optimize when adding maps on their mobile apps / websites.

@ChrisLoer implemented CJK loading at client side on [GL JS using TinySDF](https://github.com/mapbox/mapbox-gl-js/pull/4895) and we are looking to add support on native SDKs for Android and iOS.

### Technical lifts
1. gl-native “core” support for using TinySDF 
2. Android-specific font-loading and configuration
3. iOS-specific font-loading and configuration. 

Per voice with @ChrisLoer, he could tackle the first item, but we are looking for support from the Android and iOS teams for items 2 and 3, respectively. @zugaldia @boundsj 

@ChrisLoer please add in any technical details I may be missing.

cc @mourner

**Comment by zugaldia** [comment]
cc: @lilykaiser

**Comment by 1ec5** [comment]
Rendering system or local fonts for all scripts, not just CJK, is also tracked in #7862.

**Comment by kkaefer** [comment]
First part of this PR is in https://github.com/mapbox/mapbox-gl-native/pull/10522

**Comment by lilykaiser** [comment]
Since https://github.com/mapbox/mapbox-gl-native/pull/10522 has merged, I believe this can be closed. If I'm wrong, please reopen!
