### ISSUE TITLE
Crash due to MapboxTelemetry (No virtual method initialize)

### ISSUE THREAD

**Issue by amanzan** [mapbox/mapbox-gl-native#10357]
**Platform: Android**
**Mapbox SDK version: 5.2.0-beta.3**

### Steps to trigger behavior
 1. Run app

### Expected behavior
No crashes

### Actual behavior
FATAL EXCEPTION: main Process: com.example.myapp, PID: 16817 java.lang.NoSuchMethodError: No virtual method initialize(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Lcom/mapbox/services/android/telemetry/location/LocationEngine;)V in class Lcom/mapbox/services/android/telemetry/MapboxTelemetry; or its super classes (declaration of 'com.mapbox.services.android.telemetry.MapboxTelemetry' appears in /data/app/com.example.myapp-4RgMqGrrEFZc1X5nPn936g==/base.apk:classes84.dex) at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:58) at com.example.myapp.App.onCreate(App.java:128) at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791) at android.app.ActivityThread.-wrap1(Unknown Source:0) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) at android.os.Handler.dispatchMessage(Handler.java:105) at android.os.Looper.loop(Looper.java:164) at android.app.ActivityThread.main(ActivityThread.java:6541) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

11-02 10:10:35.386 16817-16817/com.example.myapp E/CrashlyticsCore: Failed to execute task. java.util.concurrent.TimeoutException at java.util.concurrent.FutureTask.get(FutureTask.java:206) at com.crashlytics.android.core.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException(CrashlyticsExecutorServiceWrapper.java:44) at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:251) at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068) at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063) at java.lang.Thread.dispatchUncaughtException(Thread.java:1953)

**Comment by tobrun** [comment]
@amanzan could you list your dependencies of your build.gradle? The no such method error indicates that the telemetry dependency is being overwritten by another and that version doesn't have the same api definition as the one included in this project.

**Comment by amanzan** [comment]
After struggling for some time, I added "exclude" in my gradle dependencies and now it works. This is what I have now:

`    compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-beta.3@aar'){
        transitive=true
        exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-services'
    }

    compile ('com.mapbox.mapboxsdk:mapbox-android-services:2.3.0-SNAPSHOT') {
        exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-sdk'
        exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-telemetry'
    }`

Apparently there were some internal conflicts somewhere...

**Comment by tobrun** [comment]
That version is currently not compatible. Two options to resolve this:
- use the map sdk snapshot untill beta.4 is released:

```
com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-SNAPSHOT@aar
```
- use an older version of the mapbox-android-services:
