### ISSUE TITLE
I want to show the Infowindow on top of marker without clicking on the marker.It needs to displayed at all times.How do I achieve this functionality in mapbox Android?

### ISSUE THREAD

**Issue by aadhil-ahmed** [mapbox/mapbox-gl-native#10358]
**Platform:**
**Mapbox SDK version:**

### Steps to trigger behavior

 1.
 2.
 3.

**Comment by tobrun** [comment]
@aadhil-ahmed to achieve that functionality you need to do 2 things: 
 - mapboxMap.getUiSettings().setDeselectMarkersOnTap(false)
 - mapboxMap.selectMarker(marker) 

Thank you for reaching out, closing as question was answered.
