### ISSUE TITLE
gyp: Disable builds with BUILDTYPE not in (Release, Debug)

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1035]
When compiling with `BUILDTYPE` set to another value, we're not using the correct compiler flags.

**Comment by jfirebaugh** [comment]
Still relevant after the switch to CMake?

**Comment by kkaefer** [comment]
Fixed as part of the CMake switch: https://github.com/mapbox/mapbox-gl-native/commit/692fe1f3ffc8f4364b39c14aa7d90cec2ff5c0a6#diff-b67911656ef5d18c4ae36cb6741b7965R3

**Comment by kkaefer** [comment]
```
$ BUILDTYPE=Other make
Makefile:6: *** BUILDTYPE must be Debug or Release.  Stop.
```
