### ISSUE TITLE
How to compile windows system android unsuccessful ?

### ISSUE THREAD

**Issue by zkjmyy** [mapbox/mapbox-gl-native#10373]
**Platform:**
**Mapbox SDK version:**

### Steps to trigger behavior

 1.How to compile windows system android unsuccessful ?
 2.compile failure always.
 3.

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. Unfortunately, you haven't provided enough information for us to be able to help you. When opening an issue, please fill out the provided issue template completely -- we need all this data in order to provide an answer.
