### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0

### ISSUE THREAD

**Issue by OksanaZakharova** [mapbox/mapbox-gl-native#10378]
Platform: Android 6.0.1

Mapbox SDK version:
dependencies {
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.6.3'
    compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.6.3') {
        transitive = true
    }
}

I tried to work with navigation

//init navigation
        MapboxNavigationOptions options = MapboxNavigationOptions.builder()
                .defaultMilestonesEnabled(true)
                .isDebugLoggingEnabled(true)
                .snapToRoute(true)
                .isFromNavigationUi(true)
                .build();

        navigation = new MapboxNavigation(mContext, Mapbox.getAccessToken(), options);

After starting navigation I've got exception

11-03 18:14:01.360 2715-2715/com.parko.android A/libc: **Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 2715** (m.parko.android)
11-03 18:14:01.430 2314-2314/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-03 18:14:01.430 2314-2314/? A/DEBUG: Build fingerprint: 'samsung/j7xeltexx/j7xelte:6.0.1/MMB29K/J710FXXU3AQF8:user/release-keys'
11-03 18:14:01.430 2314-2314/? A/DEBUG: Revision: '7'
11-03 18:14:01.430 2314-2314/? A/DEBUG: ABI: 'arm'
11-03 18:14:01.430 2314-2314/? A/DEBUG: pid: 2715, tid: 2715, name: m.parko.android  >>> com.parko.android <<<
11-03 18:14:01.430 2314-2314/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
11-03 18:14:01.470 2314-2314/? A/DEBUG:     r0 00000000  r1 ffcede74  r2 ffcedea0  r3 df12d141
11-03 18:14:01.470 2314-2314/? A/DEBUG:     r4 ffcede74  r5 ffcede74  r6 d1f7297c  r7 ffcede28
11-03 18:14:01.470 2314-2314/? A/DEBUG:     r8 ca982380  r9 ffcedea0  sl ffcedf40  fp f4ef6500
11-03 18:14:01.470 2314-2314/? A/DEBUG:     ip f4ec2000  sp ffcedd98  lr df0f47ef  pc df12d15c  cpsr 88070030
11-03 18:14:01.480 2314-2314/? A/DEBUG: backtrace:
11-03 18:14:01.480 2314-2314/? A/DEBUG:     #00 pc 0019515c  /data/app/com.parko.android-2/lib/arm/libmapbox-gl.so
11-03 18:14:01.480 2314-2314/? A/DEBUG:     #01 pc 0015c7ed  /data/app/com.parko.android-2/lib/arm/libmapbox-gl.so
11-03 18:14:01.480 2314-2314/? A/DEBUG:     #02 pc 0015dc07  /data/app/com.parko.android-2/lib/arm/libmapbox-gl.so
11-03 18:14:01.480 2314-2314/? A/DEBUG:     #03 pc 000c2beb  /data/app/com.parko.android-2/lib/arm/libmapbox-gl.so
11-03 18:14:01.480 2314-2314/? A/DEBUG:     #04 pc 000bd8b3  /data/app/com.parko.android-2/lib/arm/libmapbox-gl.so
11-03 18:14:01.480 2314-2314/? A/DEBUG:     #05 pc 000bfd5b  /data/app/com.parko.android-2/lib/arm/libmapbox-gl.so
11-03 18:14:01.480 2314-2314/? A/DEBUG:     #06 pc 000ea8a9  /system/lib/libart.so (art_quick_generic_jni_trampoline+40)
11-03 18:14:01.480 2314-2314/? A/DEBUG:     #07 pc 000e61b1  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
11-03 18:14:01.480 2314-2314/? A/DEBUG:     #08 pc 004031ed  /system/lib/libart.so (art_quick_invoke_stub+188)
11-03 18:14:01.480 2314-2314/? A/DEBUG:     #09 pc 007fb06c  [stack]

**Comment by kingfisherphuoc** [comment]
I got this issue too.

**Comment by tobrun** [comment]
Since this report we released multiple new versions of the maps + navigation sdk. Feel free to reach out if still having the issues mentioned in OP. Closing.
