### ISSUE TITLE
polygon outline width

### ISSUE THREAD

**Issue by sdliuxu** [mapbox/mapbox-gl-native#10374]
how to change polygon outline width？
1.I found that that is no polygon outline width property.
2.I want to modify it's source code to resolve this problem.but I fouud it‘s useless.

The code is as follows.
The location is /renderer/layers/render_fill_layer.cpp
if (evaluated.get<FillAntialias>() && parameters.pass == RenderPass::Translucent) {
                //glLineWidth(8);
                draw(parameters.programs.fillOutline,
                     gl::Lines{ 2.0f },
                     parameters.depthModeForSublayer(
                             unevaluated.get<FillOutlineColor>().isUndefined() ? 2 : 0,
                             gl::DepthMode::ReadOnly),
                     *bucket.lineIndexBuffer,
                     bucket.lineSegments);
            }
I found it's the source code drawing outline,but I change gl::Line(2.0f) to gl::Line(10.0f).The polygon outline width always is 1 pixel.

I hope the author can provide some suggestions or methods for this problem.
Many thanks!

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
