### ISSUE TITLE
Stretched sprites

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-native#1038]
#### Sometimes, the sprites look vertically stretched (on-device vs laptop):

![img_1069](https://cloud.githubusercontent.com/assets/4551508/6760150/661d89e4-cf03-11e4-9fef-3564f5ace095.png)

![screen shot 2015-03-20 at 1 17 53 pm](https://cloud.githubusercontent.com/assets/4551508/6760169/8b6026ee-cf03-11e4-8a06-4d66d19c35e4.png)

#### Other times, it looks like the text is simply shifted up:

![img_1072](https://cloud.githubusercontent.com/assets/4551508/6760184/af9c9880-cf03-11e4-97fa-c7b132a638d8.png)

![screen shot 2015-03-20 at 1 14 09 pm](https://cloud.githubusercontent.com/assets/4551508/6760191/b8e66e98-cf03-11e4-9773-75213464c999.png)

cc/ @incanus @jfirebaugh

**Comment by incanus** [comment]
I'm still seeing this as well. 

![img_3181](https://cloud.githubusercontent.com/assets/17722/6784839/4e675030-d13f-11e4-95b9-a3bfa63c15a0.PNG)

**Comment by ansis** [comment]
What is the dpi on the devices that you're seeing this on?

**Comment by incanus** [comment]
Mine was an iPhone 5s, so 326ppi.

**Comment by ansis** [comment]
Sorry, I meant dppx. It looks like it's 2 for the 5s. hmm

**Comment by peterqliu** [comment]
@ansis mine is iPhone 5
