### ISSUE TITLE
Rename to Mapbox Maps SDK

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#10385]
The team has decided to rename the Mapbox Android SDK, Mapbox iOS SDK, Mapbox macOS SDK, and Mapbox Qt SDK to the Mapbox Maps SDK for Android, iOS, macOS, and Qt, respectively. It’s expected that this change will primarily affect documentation and packaging.

The module name on iOS and macOS will remain simply `Mapbox`. The CocoaPods pod names will also remain Mapbox-iOS-SDK and Mapbox-macOS-SDK – we aren’t taking this opportunity to unify them into a single pod. For now, the homepage remains at mapbox.com/ios-sdk/. The name “Mapbox iOS SDK” does appear in a couple places in UI, so these strings will need to be updated and retranslated.

On a historical note, this is the latest in a series of renames intended to clarify the scope of these projects:

* Mapbox GL for iOS was renamed Mapbox iOS SDK (superseding the raster Mapbox iOS SDK) in [v2.0.0-pre.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v2.0.0-pre.1).
* Mapbox GL for Android was renamed Mapbox Android SDK (superseding the raster Mapbox Android SDK) in #2487.
* Mapbox OS X SDK was renamed Mapbox macOS SDK in #5343.

Last but not least, the overall LLMR project was renamed Mapbox GL in #210.

/cc @mapbox/gl @mapbox/mobile

**Comment by 1ec5** [comment]
> The name “Mapbox iOS SDK” does appear in a couple places in UI, so these strings will need to be updated and retranslated.

For the iOS SDK, the strings `SDK_NAME` and `SDK_UPDATE_AVAILABLE` both contain the product name. Apparently all of the checked-in translations kept the name in English. I think there’s a potential for some of the translations to opt for a less literal translation with “Mapbox Maps SDK for iOS” (to translate the word “for”). But it won’t be a showstopper if we’re unable to give translators time to take care of that detail ahead of a patch release that includes this change.

**Comment by langsmith** [comment]
Already did https://github.com/mapbox/android-docs/pull/249/files and I will handle all renaming for Android content across all repos (gl-native, docs, plugins, etc.)

**Comment by 1ec5** [comment]
#10610 took care of the iOS and macOS map SDKs in large part.

**Comment by 1ec5** [comment]
@brunoabinader @tmpsantos, anything left to do here on the Qt side, or can we close this issue out?

**Comment by brunoabinader** [comment]
@1ec5 👉 https://github.com/mapbox/mapbox-gl-native/pull/11315
