### ISSUE TITLE
rotation-alignment:viewport does not work on iPhone 5

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-native#1039]
Expected:

![screen shot 2015-03-20 at 1 37 11 pm](https://cloud.githubusercontent.com/assets/4551508/6760504/6b44e16c-cf06-11e4-9d7c-beab7a56f079.png)

Observed:

![img_1068](https://cloud.githubusercontent.com/assets/4551508/6760507/782e2c9e-cf06-11e4-8be6-37ab64f9f1a5.png)

**Comment by friedbunny** [comment]
Labels seem to rotate without any issues as of `master` a1a7ab62e176afb354109ba23360c668f84771e8 + cfbdbc9d0d24aa414391636e30314d5c28acdbb2 (latest styles submodule).

**iPhone 5**
[![screen-shot-2015-03-20-at-9 40 07-pm_sm](https://cloud.githubusercontent.com/assets/1198851/6763786/e1bf3e12-cf49-11e4-8ae7-9abcaa141790.png)](https://cloud.githubusercontent.com/assets/1198851/6763784/de35f2cc-cf49-11e4-8b33-c2d18c2190cd.png)

Simulator also rotates as expected.

My phone does seem to bog down a ton when loading uncached tiles on Emerald, though. As in, zooming into cities has an unusual, several seconds delay before tiles pop in (if they do at all). The simulator doesn't do this.

**Comment by peterqliu** [comment]
no longer seeing this
