### ISSUE TITLE
Never resolve tokens after evaluating a text-field or icon-image expression

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-native#10399]
GL Native quivalent of https://github.com/mapbox/mapbox-gl-js/issues/5599

**Comment by anandthakker** [comment]
I think this will be much cleaner to implement once basic SDK support is in place, because at that point, we can likely remove the `{Camera,Source,Composite}Function<T>` templates (or at least their corresponding `*Stops<T>` members), making the function => expression conversion code much more tightly contained.

Since resolving this issue amounts to adding token string => `["concat", ...]` to that conversion, it will be a simpler and cleaner change at that point than it would be now.

**Comment by 1ec5** [comment]
Fixed in #11509.
