### ISSUE TITLE
Port: Expressions for "enum"-typed properties need a post-evaluation validation step

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native#10396]
Placeholder for test ignore: I'm not sure what the right analog of https://github.com/mapbox/mapbox-gl-js/issues/5576 is on the native side.

/cc @anandthakker

**Comment by anandthakker** [comment]
Ah - I believe the native side should already be taken care of in the main expressions PR #9439 -- will confirm

**Comment by anandthakker** [comment]
Confirmed @ChrisLoer the mapbox-gl-js#5576 regression test passes in the main expressions branch
