### ISSUE TITLE
Scrambled label sdf's

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-native#1040]
Can't describe exactly when, but at occasional zooms, labels become scrambled:

![screen shot 2015-03-20 at 1 54 35 pm](https://cloud.githubusercontent.com/assets/4551508/6760710/aefc5c4e-cf08-11e4-94b6-a7094609442d.png)

**Comment by incanus** [comment]
Weird; have never seen this. Might be a regression of https://github.com/mapbox/mapbox-gl-native/issues/832 which was fixed in #957? 

/cc @jfirebaugh

**Comment by peterqliu** [comment]
Not seeing this after downloading the app as of 3/21 -- @jfirebaugh feel free to close if you can't replicate

**Comment by incanus** [comment]
I have not seen this once since @jfirebaugh's tile-related fixes. Gonna close.
