### ISSUE TITLE
Add custom data to marker

### ISSUE THREAD

**Issue by dbrgn** [mapbox/mapbox-gl-native#10407]
**Platform:** Android
**Mapbox SDK version:** 5.2.0-beta.3

Is there a way to add custom data to a marker?

## Actual goal

I'm displaying many sensors on a map. When I receive the list of sensors with coordinates from the API, I create a marker for each of them.

When the user taps on a marker, I want to be able to fetch the sensor instance from my internal data structure. So I need a way to associate a marker with a sensor.

## Potential implementation

If there were a way to attach arbitrary data to a marker (maybe via generics?), I could attach the sensor data (or alternatively the sensor id) to the marker and access this data in the `OnMarkerClickListener`.

## Current workaround

Right now, I either have to pass my information pre-processed as a string to the marker snippet, or I have to create a new data structure with associations from marker id to sensor id.

Maybe my whole approach is wrong and there is a better way? If not, consider this a feature request :)

**Comment by tobrun** [comment]
@dbrgn first of all, thank you for using Mapbox.

# SymbolLayer using a GeoJSON Source
This will be the most performant and flexible solution. You put your additional data as feature properties in a geojson entry. You can later look up these features with `MapboxMap#QueryRenderedFeaturesAt`. [Here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/ZoomFunctionSymbolLayerActivity.java) is one example that incorporates having a selected event but there are other examples in the same package. 

# Extending Marker
It's possible to extend Marker and MarkerOptions to put in additional data (note that you need to override the parceable interface) and cast markers coming in from OnMarkerClickListener to the correct type. 

Don't see this issue as actionable, 2 workarounds provided. Going to close. 

Feel free to reach out if you hit any issues.

**Comment by dbrgn** [comment]
@tobrun thanks! :)

**Comment by GitHubMurt** [comment]
O moving from pure GoogleMaps to MapBox. It would be nice if you provide feature such as Google Markers.tag do. Later I can find selected marker data by a tag, that is assigned to it
