### ISSUE TITLE
[Qt] SQLite implementation issues with concurrent writes

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#10413]
We've seen concurrency issues related to the SQLite Qt-based implementation e.g. when two or more database connections attempt to write an entry into the `tiles` table, the entry's `data` column ends up empty, causing loss of data and rendering artifacts as seen below:

![screenshot from 2017-11-08 13-33-01](https://user-images.githubusercontent.com/76133/32546952-5c2ce924-c489-11e7-955b-db2a3fd70ab9.png)

In the image above, the same tile data for 0/0/0 is requested from two different render tiles, with one successfully obtaining the data, and the other not. The faulty render tile ends up writing the empty `data` column back in the offline database.

This bug has been haunting us for a while - though it doesn't show up as often due to a series of factors:

1. We don't necessarily generate the database file via Qt e.g. we could initialize it using the GLFW demo app (which uses the default database implementation) and further reuse it on Qt;
2. In some rare cases, the tiles shows just fine and the data is properly written into the database - suggesting this could be a race condition issue;
3. We only happen to request the same tile data from different render tiles when showing the _wrapped_ world, which is usually the case when approaching zoom levels 1 & 0.

So far my mitigation attempts have failed:
- Our Qt-based `Transaction` implementation doesn't follow `QSqlDatabase` transaction implementation, as it doesn't allow us to provide which transaction behavior to use. Instead, we use the same `exec()` calls as in the default SQLite implementation (I've also attempted using `QSqlDatabase`'s `transaction()`, `commit()` & `rollback()` calls with no effect).
- I've already attempted adding more transaction gates inside `OfflineDatabase::putTile` with no effect.

/cc @tmpsantos @kkaefer

**Comment by tmpsantos** [comment]
I can reproduce this after replacing the `DefaultFileSource` with `OnlineFileSource`: https://gist.github.com/tmpsantos/7a17d78a094c8c617c7577698820ec53

**Comment by brunoabinader** [comment]
This causes the render tiles to load properly (and valid data being stored in the database):

```
diff --git a/platform/qt/src/http_file_source.cpp b/platform/qt/src/http_file_source.cpp
index 573b707..d2a5a11 100644
--- a/platform/qt/src/http_file_source.cpp
+++ b/platform/qt/src/http_file_source.cpp
@@ -102,7 +102,7 @@ std::unique_ptr<AsyncRequest> HTTPFileSource::request(const Resource& resource,
 
 uint32_t HTTPFileSource::maximumConcurrentRequests() {
 #if QT_VERSION >= 0x050000
-    return 20;
+    return 1;
 #else
     return 10;
 #endif
```

From what it looks, the bug probably is in Qt's `HTTPFileSource` implementation.

**Comment by brunoabinader** [comment]
Fix proposal in: https://github.com/mapbox/mapbox-gl-native/pull/10416/commits/b18a9becd5e185769dcdca1bb7db7c9e6f107137
