### ISSUE TITLE
Fix failing viewport-collision render tests

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native#10412]
The following tests pass locally for me but give different results on some of our CI environments:

debug/collision-lines-pitched
debug/collision-lines
text-pitch-alignment/viewport-overzoomed-single-glyph
text-pitch-alignment/viewport-text-depthtest

/cc @ansis @jfirebaugh @kkaefer

**Comment by ChrisLoer** [comment]
`text-pitch-alignment/viewport-overzoomed-single-glyph` and `text-pitch-alignment/viewport-text-depthtest` are fixed.

I switched `debug/collision-pitched-wrapped` over to this issue. It was previously ignored against issue #3841, but it looks like theres an actual difference in collision result now, not just a difference in how collision boxes are rendered.

**Comment by anandthakker** [comment]
Per @brunoabinader 's comment in https://github.com/mapbox/mapbox-gl-js/pull/6250#issuecomment-369383014, I added ignores for `real-world/{bangkok,chicago,sanfrancisco` targeting this issue.
