### ISSUE TITLE
User location tracking is rough

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1041]
User location tracking for is functional #756 but rough compared to MapKit’s implementation. In MapKit, the user dot crawls continuously and the map pans just as smoothly. Our implementation jerks forward every time the GPS location changes. Since the panning motion is animated, the map always trails the user dot. Instead, perhaps it could lead the user dot, by overshooting it based on its _n_ previous coordinates.

**Comment by 1ec5** [comment]
Looks like `-[CLLocation speed]` and `-[CLLocation course]` will be of use here.

**Comment by mikemorris** [comment]
Perfect opportunity for implementation of techniques from video games here. Valve has published some great work on this. [I've previously implemented entity interpolation in JavaScript](https://github.com/nclud/2013.beercamp.com/blob/master/game/core/types/Entity.js#L185-L241) (mostly transliterating from Valve's C++ examples) and would be happy to help with this if needed.
- https://developer.valvesoftware.com/wiki/Source_Multiplayer_Networking
- https://developer.valvesoftware.com/wiki/Latency_Compensating_Methods_in_Client/Server_In-game_Protocol_Design_and_Optimization

**Comment by mikemorris** [comment]
There are two different ways to implement this:
- "dead reckoning"
  - Optimistically assume that an entity will continue traveling on it's current trajectory and velocity, retroactively correcting as necessary.
  - This works well for bullets, does not work well for less predictable actions like player movement (can cause "lag skipping" all over the screen in high latency conditions).
- "entity interpolation"
  - Interpolate an object, animating it from a less recently known location to a more recently known location.
  - This can introduce slight player latency, but is configurable for smoothness versus accuracy and generally results in smoother, more predictable animation.

**Comment by incanus** [comment]
> Interpolate an object, animating it from a less recently known location to a more recently known location.

We can do this pretty easily as the user dot is a native iOS view. We do an [atomic position update](https://github.com/mapbox/mapbox-gl-native/blob/8eafe36932c3c5407a305268bc5b62e70ad8b8b0/platform/ios/MGLMapView.mm#L2191) that could just use implicit layer animation.

**Comment by 1ec5** [comment]
MapKit apparently uses entity interpolation. In the iOS Simulator, switch from City Run to City Bicycle Ride (for instance) and note how the user dot animates back to the Infinite Loop 1 entrance without skipping any steps. In dfd563aadde1a3ac7444fc78a3541a217184e220, I used UIView block-based animation to accomplish pretty much the same thing for the non-tracking case.

**Comment by incanus** [comment]
Using `map.userTrackingMode = .FollowWithCourse` is much more stable here and applicable to navigation-type apps.

**Comment by 1ec5** [comment]
No, `.FollowWithCourse` will have the same behavior described here.

**Comment by picciano** [comment]
Any thoughts on scheduling this into a milestone?

**Comment by muZZkat** [comment]
In Map kit, the user location view is fixed on the screen and the map moves under it, This is not really related to any entity interpolation of the current users location.

**Comment by 1ec5** [comment]
@muZZkat, the behavior you describe would still require entry interpolation or dead reckoning, except only to pan the map smoothly, rather than move the user dot (thus causing the map to pan), as #1582 does.

**Comment by incanus** [comment]
This isn't going to make it into 3.0.0, but we should take another pass at it.

**Comment by 1ec5** [comment]
I’m working on some changes that will unblock a better fix for this issue, including #3086.

**Comment by 1ec5** [comment]
#3589 uses entity interpolation to smooth transitions in user tracking mode. #1582 is quite stale, but it would smooth the user dot outside of user tracking mode.

**Comment by 1ec5** [comment]
Next steps are in #1582, which is about smoothly moving the user dot outside of user tracking mode.
