### ISSUE TITLE
Size attribution to fit narrower snapshot images

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#10423]
Continuing where #10114 left off, narrower snapshot images may not have enough room for both the Mapbox logo and the fully spelled-out attribution text on a single line. For consistency with the Mapbox Static API, the following formats have been proposed, in order from longest to shortest:

* <img width="85" alt="helmet and wordmark" src="https://user-images.githubusercontent.com/1231218/32572747-73b0aa44-c480-11e7-9ae8-9ef2ee8b2740.png"> &nbsp;&nbsp;&nbsp; © Mapbox © OpenStreetMap © DigitalGlobe
* <img src="https://user-images.githubusercontent.com/1231218/32572833-bf117964-c480-11e7-82ae-a68f57eb1c27.png" height="22" alt="helmet"> &nbsp;&nbsp;&nbsp; © Mapbox © OpenStreetMap © DigitalGlobe
* © Mapbox © OSM © DigitalGlobe

The exact attribution text depends on the sources involved. The examples above assume the Mapbox Satellite Streets style, which involves the most sources of any Mapbox-designed core style.

/cc @tobrun @fabian-guerra

**Comment by lilykaiser** [comment]
Hey @1ec5 , let's follow the above proposal where space allows. To make attribution as frictionless as possible, we are going to add the following logic to minimize the cases where developers have to add their own attribution:

1. [FULL LOGO] ©Mapbox (©OpenStreetMap) (©DigitalGlobe)
2. [HELMET] ©Mapbox (©OpenStreetMap) (©DigitalGlobe)
3. ©Mapbox (©OpenStreetMap) (©DigitalGlobe)
4. **©Mapbox (©OSM) (©DigitalGlobe)**
5. We throw an error, developer must provide attribution

**Comment by 1ec5** [comment]
> We throw an error, developer must provide attribution

If we throw an error, there will be no snapshot to provide attribution for. Can we just log a one-time warning to the console instead?

**Comment by lilykaiser** [comment]
Maybe that is what I meant, I defer to the implementers!

Thanks for clarifying @1ec5

**Comment by lilykaiser** [comment]
Hi @fabian-guerra , should we close this or wait for https://github.com/mapbox/mapbox-gl-native/pull/10525 ?

**Comment by fabian-guerra** [comment]
Hi, @lilykaiser. I think we can close it.
