### ISSUE TITLE
VectorSource's querySourceFeatures filter not working with feature id

### ISSUE THREAD

**Issue by Jukurrpa** [mapbox/mapbox-gl-native#10422]
**Platform:** Android
**Mapbox SDK version:** 5.1.5

Calling `VectorSource.querySourceFeatures()` with a filter on the id, e.g. `Filter.eq("$id", "12345"))` doesn't return anything even if matching features exist.

I tried these methods to find the desired features (in Kotlin):

    // Mapbox filter, no results
    map.getSourceAs<VectorSource>("source")?.querySourceFeatures(arrayOf("segments"), Filter.eq("\$id", "12345"))

    // Manual filter, one or more results
    map.getSourceAs<VectorSource>("source")?.querySourceFeatures(arrayOf("segments"), null).filter { feature -> feature.id == "12345" }

This doesn't work with `Filter.in()` either. Is this on purpose?

Edit: additional note, filtering by type does work

**Comment by 1ec5** [comment]
> the same issue exists on the iOS SDK

Note that you need to use the `%K` placeholder when creating an NSPredicate mentioning the `$type` property: see the example code in [this document](https://www.mapbox.com/ios-sdk/api/3.6.4/Classes/MGLVectorStyleLayer.html#/c:objc%28cs%29MGLVectorStyleLayer%28py%29predicate) for details.

**Comment by tobrun** [comment]
Noting here that [QuerySourceFeaturesActivity](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QuerySourceFeaturesActivity.java) also seems to be broken, querySourceFeatures is returning 4 identical features [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QuerySourceFeaturesActivity.java#L61) while there was only one added [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QuerySourceFeaturesActivity.java#L50).

**Comment by ivovandongen** [comment]
@Jukurrpa I just tested this out locally and I see the filters working on `id`. Could you check that the type of the `id` is actually a string and not a number?

**Comment by ivovandongen** [comment]
> Noting here that QuerySourceFeaturesActivity also seems to be broken

Seems like a different issue @tobrun

**Comment by Jukurrpa** [comment]
@ivovandongen Sorry for the delayed response. Do you mean the `id` of the feature itself? If so, it is originally an `uint64` in the vector tiles fed to the map (as per https://github.com/mapbox/vector-tile-spec). As for the parameter I give to `Filter.eq()` it is indeed a string (also tried with an int, doesn't work either).

**Comment by Jukurrpa** [comment]
Bumping this as I'm having the same issue when trying to apply an id filter on a layer. The filter is built this way (still in Kotlin). `defaultFilter` is the layer's base filter and `featureId` is a `String`:
`Filter.all(defaultFilter, Filter.neq("\$id", featureId))`

This doesn't hide the symbol. The feature id is directly taken from the feature returned by `MapboxMap.queryRenderedFeatures()`. Using a filter on `$type` instead of `$id` works properly, and using the id filter on iOS with the same source and layer works too.

Contrary to what I previously mentioned, the filter works on iOS with the same source, layer, etc. For some time I thought this could be due to our source (self hosted vector tiles) but I guess this means it isn't.

**Comment by karijkangas** [comment]
Seeing this same issue in react-native-mapbox-gl, but with GeoJsonSource (RNMGL ShapeSource); filter ['in', '$id', ...visibleFeatures] works in iOS but does not work in Android. Moving the id to feature properties and changing the filter to ['in', 'id', ...visibleFeatures] works as expected in both iOS and Android.

**Comment by Jukurrpa** [comment]
Gave this another try with the v6.2.1 of the SDK, and querying the source works with this expression: `Expression.eq(Expression.id(), featureId)`. The feature id needs to be an int though, it won't work if it's a string which can be confusing as `Feature.id()` returns a string. But if this is the intended behavior I guess the issue can be closed :+1:

**Comment by tobrun** [comment]
Thank you for following up @Jukurrpa
