### ISSUE TITLE
MGLMapSnapshotter has redundant properties

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#10435]
MGLMapSnapshotter has [several unused properties](https://github.com/mapbox/mapbox-gl-native/blob/a936fd6f8a625e8a95c3d1ab524b8dddbbbb5ccd/platform/darwin/src/MGLMapSnapshotter.h#L160-L197) that are redundant to properties on MGLMapSnapshotOptions. These properties should be replaced by a single `options` property.

/cc @fabian-guerra @jmkiley

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/10702
