### ISSUE TITLE
iPhone 5 particularly sluggish with Emerald style

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#1044]
When trying out the Emerald style on my iPhone 5, rendering is super sluggish (and occasionally never finishes).

And now for the most boring GIF you'll ever watch: 

![1043-emerald-slow-2](https://cloud.githubusercontent.com/assets/1198851/6763997/fda7c2d8-cf54-11e4-9c08-2ff88c930c99.gif)

**Comment by peterqliu** [comment]
experiencing this as well, if not slower. It may help when I [composite sources](https://github.com/mapbox/mapbox-gl-styles/blob/mb-pages/styles/emerald-v7.json#L24-L31), but not sure by how much.

**Comment by friedbunny** [comment]
During such zooming, both CPU cores are pegged:

![screen shot 2015-03-20 at 11 22 11 pm](https://cloud.githubusercontent.com/assets/1198851/6764043/29fbf0c6-cf59-11e4-9051-988cf8c80497.png)

**Comment by friedbunny** [comment]
![screen shot 2015-03-20 at 11 43 56 pm](https://cloud.githubusercontent.com/assets/1198851/6764076/962abf6e-cf5b-11e4-8e0c-a7235d239a66.png)

... and then it's `detail::dispatcher` all the way down.

**Comment by mb12** [comment]
@peterqliu 
1.) What is the the source layer hillshade in mapbox://mapbox.mapbox-terrain-v2 for?   TileParser would create  fill buckets for both the street-v6 as well as terrain v2 sources.

2.) You can delete source mapbox://mapbox.mapbox-terrain-v1 since its not referenced anywhere in the style.

3.) In general when tile parsing is slow, look into reducing the size of your pbf files by simplifying geometries esp at lower zoom levels.

**Comment by kkaefer** [comment]
Did you compile in Release mode? Parsing in Debug mode is very slow because the code isn't optimized. In particular Boost's Rtree is at least an order of magnitude slower.

**Comment by friedbunny** [comment]
Release does make a big difference — it's usable, but tiles still noticeably pop in and zooming several levels at once has a couple seconds delay. In profiling it looks to be about twice/thrice as fast as debug, which means the CPU is pegged for only one or two seconds at a time.

![1104-slow-2](https://cloud.githubusercontent.com/assets/1198851/6765618/d4f3d862-cfa5-11e4-8a67-1383c8551919.gif)

**Comment by picciano** [comment]
Let me add this valuable comment: "me too"

:+1:

**Comment by peterqliu** [comment]
@mb12 sorry i missed your comment-- I've since composited terrain and streets into once source, and removed terrain-v1 :+1:

**Comment by incanus** [comment]
I still see a noticeable pop between layers coming in on iPhone 5**s** in _Release_. Emerald is the first style I've seen perf issues with.

**Comment by incanus** [comment]
We're currently focused on performance across the board, so the core issue here is flagged.
