### ISSUE TITLE
Sanitizer error on DefaultFileSource.GetBaseURLAndAccessTokenWhilePaused 

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native#10448]
Seen at https://circleci.com/gh/mapbox/mapbox-gl-native/39233, doesn't _seem_ related to the changes being tested in that PR. Looks pretty similar to https://github.com/mapbox/mapbox-gl-native/issues/9620.

    ../../../platform/default/run_loop.cpp:134:18: runtime error: member call on null pointer of type 'mbgl::util::AsyncTask'
    #0 0x1881183 in mbgl::util::RunLoop::push(std::shared_ptr<mbgl::WorkTask>) /src/build/linux-x86_64/Sanitize/../../../platform/default/run_loop.cpp:134:18
    #1 0x18817b2 in void mbgl::util::RunLoop::invoke<mbgl::util::RunLoop::stop()::$_1>(mbgl::util::RunLoop::stop()::$_1&&) /src/build/linux-x86_64/Sanitize/../../../include/mbgl/util/run_loop.hpp:54:9
    #2 0x18816bd in mbgl::util::RunLoop::stop() /src/build/linux-x86_64/Sanitize/../../../platform/default/run_loop.cpp:151:5
    #3 0x17d6666 in mbgl::util::Thread<mbgl::DefaultFileSource::Impl>::~Thread() /src/build/linux-x86_64/Sanitize/../../../include/mbgl/util/thread.hpp:80:15
    #4 0x17d6919 in mbgl::util::Thread<mbgl::DefaultFileSource::Impl>::~Thread() /src/build/linux-x86_64/Sanitize/../../../include/mbgl/util/thread.hpp:63:24
    #5 0x17e3cf6 in std::default_delete<mbgl::util::Thread<mbgl::DefaultFileSource::Impl> >::operator()(mbgl::util::Thread<mbgl::DefaultFileSource::Impl>*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/unique_ptr.h:76:2
    #6 0x17bfb3a in std::unique_ptr<mbgl::util::Thread<mbgl::DefaultFileSource::Impl>, std::default_delete<mbgl::util::Thread<mbgl::DefaultFileSource::Impl> > >::~unique_ptr() /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/unique_ptr.h:236:4
    #7 0x17bbee0 in mbgl::DefaultFileSource::~DefaultFileSource() /src/build/linux-x86_64/Sanitize/../../../platform/default/default_file_source.cpp:220:39
    #8 0x6e3fa2 in DefaultFileSource_GetBaseURLAndAccessTokenWhilePaused_Test::TestBody() /src/build/linux-x86_64/Sanitize/../../../test/storage/default_file_source.test.cpp:324:1

/cc @ansis @jfirebaugh @tmpsantos @kkaefer

**Comment by tmpsantos** [comment]
Thanks for reporting. Seen this today too.

**Comment by ChrisLoer** [comment]
I looked at this more closely today along with another very similar sanitizer error at https://circleci.com/gh/mapbox/mapbox-gl-native/41653.

I'm fairly confident it's a duplicate of #9620, and think I have an explanation.
