### ISSUE TITLE
Update everything to require Xcode 9 or remove use of `@available`

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#10452]
[#10425](https://github.com/mapbox/mapbox-gl-native/pull/10425/files#diff-20502b6bc02986a4398d0da84b2d4b94R392) added the use of Xcode 9’s `@available` macro, which bumps up the version of Xcode required to compile this SDK from 8.3.x to 9.

If we choose to continue to require Xcode 9 to compile, there are some new build settings we should be sure are enabled, such as `-Wunguarded-availability` and the new build system. Our CI builds have all switched over to Xcode 9 and any SDK binaries should always be compiled with the latest Xcode version, anyway, so it’s probably fine to require contributors to use Xcode 9, too.

I _think_ we’re probably still able to integrate the compiled SDK using Xcode 8.3.x, but that should also be verified.

So:

- [x] Decide whether or not to continue requiring Xcode 9 for SDK compilation.
- [ ] Take advantage of new Xcode 9 features → #10605
- [ ] Verify binaries compiled with Xcode 9 continue to be backwards compatible with Xcode 8 apps.

/cc @jmkiley @1ec5 @fabian-guerra

**Comment by 1ec5** [comment]
> Our CI builds have all switched over to Xcode 9 and any SDK binaries should always be compiled with the latest Xcode version, anyway, so it’s probably fine to require contributors to use Xcode 9, too.

As of mapbox/mapbox-navigation-ios#786, the iOS navigation SDK also requires Xcode 9 to build. Since that library is distributed as source, developers are required to use Xcode 9 even to install the SDK.

But we should probably recommend Xcode 9.1 and above, due to #9959.

**Comment by akitchen** [comment]
I'm not sure if the ship has sailed yet or not, but I would suggest we aim to support the current released Xcode plus the previous major version. 

We're on 9.1 now, and we continue to support 9.1 and 9.0. In a perfect world I would like for us to keep support for the last 8.x (supporting 9.x and 8.x) but I don't want to introduce any re-work at this point. 

Generally speaking I believe this would be the recommended pattern for maintaining tools within the Apple ecosystems, being sensitive to the fact that consumers of our SDKs might not have the luxury of immediately updating their toolchains.

**Comment by 1ec5** [comment]
> Verify binaries compiled with Xcode 9 continue to be backwards compatible with Xcode 8 apps.

Given that the `@available` expression was introduced in an implementation file, I don’t see a reason why the SDK can’t still be installed in Xcode 8.x, but this is something we should verify.

Assuming Xcode 8.x can still link against the SDK framework (both dynamic and static varieties), I think it’d be fine to require Xcode 9.1 and above (not Xcode 9.0) to compile this framework. The impact of this requirement would be limited to folks who work on the SDK; downstream developers would be unaffected.

**Comment by friedbunny** [comment]
Indeed, this issue is about compiling the SDK binaries for distribution. Historically we’ve been fairly aggressive about adopting the absolute latest version of Xcode for SDK compilation — in this case, we’ve done it somewhat inadvertently, so I opened this issue to track other changes/considerations in the move to Xcode 9.

I’d expect that our baseline requirement for integrating the SDK into apps remains at Xcode 8.3.3 (~two major versions back), though that’s something that we:

- Don’t always test for (and occasionally break).
- Should keep reevaluating, pushing forward if there’s a good reason to drop older versions.
