### ISSUE TITLE
How to load vector tile using mapbox on android?

### ISSUE THREAD

**Issue by sdliuxu** [mapbox/mapbox-gl-native#10450]
Platform:Android
Mapbox SDK version:5.x.x
I want to load vector tile (geojson format or pbf format) using Mapbox Android SDK.
Any Idea to help me? Thank you!

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by zhiwo** [comment]
> Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

Whether it is supported now？vector tile (geojson format or pbf format) using Mapbox Android SDK
