### ISSUE TITLE
Location marker not on right level on launch

### ISSUE THREAD

**Issue by thomas-huet** [mapbox/mapbox-gl-native#1045]
When launching app on android, the map is at zoom min but the location marker seems to be on a different zoom level. So when you move the map, the location marker doesn't move at the same speed as the map. The problem stop the first time you zoom in.

**Comment by ljbade** [comment]
Does this still happen?

**Comment by ljbade** [comment]
@bleege I don't this will be a problem after the recent changes?

**Comment by bleege** [comment]
@thomas-huet We just did a major refactor of this in #1940.  Can you double check to see if this is still an issue that you're seeing.  Thanks!

**Comment by thomas-huet** [comment]
I can't test it before at least a month, sorry.

**Comment by ljbade** [comment]
This has been fixed now.
