### ISSUE TITLE
SymbolLayer Android Custom View Support?

### ISSUE THREAD

**Issue by asmenter15** [mapbox/mapbox-gl-native#10469]
**Platform: Android**
**Mapbox SDK version: 5.2.0-Beta.4**

Is there currently support for custom Android SDK View Markers in SymbolLayers? I cannot find any documentation or examples supporting this idea. For my first pass I went the route of using custom MarkerViews even though they are deprecated in favor of SymbolLayers, which lead me to this exploration.

My need is to add markers which contain dynamically populated / changing information. On iOS I am using custom point annotations and it seems to have better performance over MarkerViews on Android (which i understand could just be a platform thing). 

It seems like MarkerViews (somewhat) solve this problem for me, but I just wanted to make sure I wasn't missing a better way to handle this.

**Comment by rubenweerts** [comment]
I would like to know this aswell. Right now I can't find a way to dynamically update a marker

**Comment by asmenter15** [comment]
To be clear, the intent of my question is just to find out what is currently supported and the recommended route to take for now. If the answer is it is unsupported, then I would just like to know that so I can determine which way to proceed.

**Comment by jfirebaugh** [comment]
We're not planning to add support for custom Android SDK View Markers in symbol layers. In order to support good performance for symbol layers, it's important that icons not be dynamically changing.
