### ISSUE TITLE
How to load a pbf format vector file?

### ISSUE THREAD

**Issue by sdliuxu** [mapbox/mapbox-gl-native#10461]
Platform:Android,
Version:the latest version,
My Question is how to load a pbf format vector tile？
I use the api mapView.setStyleUrl("asset://mapzen.json");
the mapzen.json is as follows:

{
  "version": 8,
  "sources": {
    "osm": {
      "type": "vector",
      "tiles": ["http://172.16.100.223:8090/api/v1/tilesets/admin/SJXXk_GlkM"]
    }
  },
  "layers": [{
    "id": "background",
    "type": "background",
    "paint": {
      "background-color": "#ffffff"
    }
  }, {
    "id": "water",
    "type": "fill",
    "source": "osm",
    "source-layer": "water",
    "filter": ["==", "$type", "Polygon"],
    "paint": {
      "fill-color": "#3887be"
    }
  }]
}

But I got an error unknown pbf field type exception.I don't know why the error accurs.anyone can help me？
Is there any other way to load my own format data using mapbox Android SDK？such as geojson vector tile or a pbf vector tile on Android platform.
Is there some example code?
Thank you！

**Comment by jfirebaugh** [comment]
This error usually means that your tile server is misconfigured, and is serving gzip-compressed tiles without a `Content-Encoding: gzip` response header.

Note that this issue tracker is for reporting bugs and feature requests. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). Thank you!
