### ISSUE TITLE
Emerald style not available

### ISSUE THREAD

**Issue by thomas-huet** [mapbox/mapbox-gl-native#1046]
I have pulled the latest master (188331505e78ccacb8f010b91d549735062c69e6), ran `git submodule update` and `make android` but the emerald style is not available in the app.

**Comment by incanus** [comment]
I don't think we've brought it to the Android app yet, just iOS and the `styles` subfolder.

**Comment by ljbade** [comment]
This should be easy, just a case of adding the style to the drop menu.

**Comment by ljbade** [comment]
Closing, moving style updating to a new ticket https://github.com/mapbox/mapbox-gl-native/issues/1264
