### ISSUE TITLE
OfflineManager.ListOfflineRegionsCallback doesn't work

### ISSUE THREAD

**Issue by rakuishi** [mapbox/mapbox-gl-native#10470]
**Platform:** Android 
**Mapbox SDK version:** 5.2.0-beta.3

I made a sample project which can reproduce a below bug.
https://github.com/rakuishi/mapbox-gl-native-issue

I think OfflineManager depends on MapView's lifecycle.
Because, after removing `mapView.onStop()`, callback works fine.

### Steps to trigger behavior

 1. Launch [MainActivity](https://github.com/rakuishi/mapbox-gl-native-issue/blob/master/app/src/main/java/com/rakuishi/mapbox_offlinemanager/MainActivity.java) which it has a MapView.
 2. Launch [Main2Activity](https://github.com/rakuishi/mapbox-gl-native-issue/blob/master/app/src/main/java/com/rakuishi/mapbox_offlinemanager/Main2Activity.java) from MainActivity.
 3. Then, call `OfflineManager.getInstance(context).listOfflineRegions()` by a touch event, but it's callback(`OfflineManager.ListOfflineRegionsCallback`) doesn't work.

### Expected behavior

- `OfflineManager.getInstance(context).listOfflineRegions()` works correctly.

### Actual behavior

- `OfflineManager.getInstance(context).listOfflineRegions()` doesn't work.

**Comment by rakuishi** [comment]
Additional Information.

Callback works fine, when I put `FileSource.getInstance().activate()` and `FileSource.getInstance().deactivate()`on MainActivity2's `onStart()` and `onStop`.

**Comment by tobrun** [comment]
@rakuishi thank you for the write up, we were indeed missing a activate/deactivate call as part of `OfflineManager#listOfflineRegions()`.

**Comment by rakuishi** [comment]
@tobrun thank you, too!
