### ISSUE TITLE
Mapbox logo is squished on macOS

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#10475]
The Mapbox logo is squished (or the map box flattened) on macOS on the release-agua branch on High Sierra:

<img width="324" alt="flattened" src="https://user-images.githubusercontent.com/1231218/32871986-12514ff6-ca39-11e7-8eea-f6a2a308f6fd.png">

This issue didn’t reproduce in v0.5.x. @fabian-guerra, could this be fallout from some of the recent attribution work?

**Comment by fabian-guerra** [comment]
Do you think is a problem related to High Sierra? I am using `release-agua` on Sierra and I don't see a problem. Also the work I have done only affects `MGLMapSnapshotter`

<img width="352" alt="screen shot 2017-11-16 at 9 39 01 am" src="https://user-images.githubusercontent.com/2745166/32896860-22a85d12-cab2-11e7-9d91-a9632fda76e4.png">

**Comment by 1ec5** [comment]
Ah, I think you’re right. I didn’t see this issue until I upgraded to High Sierra.

**Comment by 1ec5** [comment]
Fixed in #10606 on the release-agua branch.
