### ISSUE TITLE
[iOS] App crashing when configuring MGLLineStyleLayer

### ISSUE THREAD

**Issue by Suryu** [mapbox/mapbox-gl-native#10476]
**Platform: iOS
**Mapbox SDK version: ios-v3.7.0-rc.1 with last commit hash 10a9b25928bd8cd28f0c459de1f083e206e473e5 (from November 10)

### Steps to trigger behavior

In Swift, after adding source to the style:
            let layer = MGLLineStyleLayer(identifier: "polyline", source: source)
            layer.lineJoin = MGLStyleValue(rawValue: NSValue(mglLineJoin: .round))
            layer.lineCap = MGLStyleValue(rawValue: NSValue(mglLineCap: .round))
            layer.lineColor = MGLStyleValue(rawValue: UIColor.red)
            layer.lineWidth = MGLStyleValue(interpolationMode: .exponential,
                                            cameraStops: [14: MGLStyleValue<NSNumber>(rawValue: 5),
                                                          18: MGLStyleValue<NSNumber>(rawValue: 20)],
                                            options: [.defaultValue: MGLConstantStyleValue<NSNumber>(rawValue: 5)])
style.addLayer(layer)

### Expected behavior

Drawing polyline - it did work in v3.6.4 version with last commit with hash 7bcb3232cccbc4e405b12ff0ff772e71d86995b4 (from September 25)

### Actual behavior

App is crashing with EXC_BAD_ACCESS. Relevant stack parts:

2   Mapbox                              0x0000000101e91630 _ZN24MGLStyleValueTransformerIfU8__strongP8NSNumberfS2_E25toDataDrivenPropertyValueEP13MGLStyleValueIS1_E + 316,
3   Mapbox                              0x0000000101f8b494 -[MGLLineStyleLayer setLineWidth:] + 128,
4 <func with lines mentioned in #steps to trigger behavior#>
...

2. leads to MGLStyleValue_Private, mbgl::style::DataDrivenPropertyValue<MBGLType> toDataDrivenPropertyValue(MGLStyleValue<ObjCType> *value) function, highlights line starting with "auto result = "

3. 
- (void)setLineWidth:(MGLStyleValue<NSNumber *> *)lineWidth {
    MGLAssertStyleLayerIsValid();

    auto mbglValue = MGLStyleValueTransformer<float, NSNumber *>().toDataDrivenPropertyValue(lineWidth);
    self.rawLayer->setLineWidth(mbglValue);
}

**Comment by shinma** [comment]
I have the same behaviour. Please fix it ASAP.

**Comment by Suryu** [comment]
These problems might be related to 4b2e1cddb4645fb6d2c5f9634dbeb7c21516cede commit, which added Convertible type. This was commited on branch release-agua, which wasn't included in mapbox version we used before where this worked, and is now merged.

**Comment by fabian-guerra** [comment]
@jfirebaugh could you please take a look. Looks like @Suryu tracked down the problem to https://github.com/mapbox/mapbox-gl-native/commit/4b2e1cddb4645fb6d2c5f9634dbeb7c21516cede

/cc @akitchen @lilykaiser

**Comment by jfirebaugh** [comment]
Can someone set up a test case that reproduces the issue and I'll take a look?

**Comment by fabian-guerra** [comment]
Hi, @Suryu. Thank you for using Mapbox. I am not able to reproduce the error with the steps you mentioned in https://github.com/mapbox/mapbox-gl-native/issues/10476#issue-274447681. Could you please help us providing more detail or an app we could use to test. Thanks in advance.

/cc @jfirebaugh @lilykaiser @akitchen

**Comment by Suryu** [comment]
Sure, I will prepare a project for you to test as soon as I can. Thanks for the feedback :)

**Comment by Suryu** [comment]
Also, here are some more details:

**Comment by Suryu** [comment]
Ok, I did a few tests with example app and it doesn't crash. However, when using a release framework (built with "make iframework BUILDTYPE=Release SYMBOLS=NO") we still get the crash. I tried using the same map styles in both our app and example, and this will crash only in our app with release framework. I also updated dependencies, but this didn't change anything.

**Comment by Suryu** [comment]
I formatted a patch you can apply for testing. It includes mbx-test-route file, which contains example data for route in Poland, testing.swift which contains Testing class written in swift which has the same code as we do that causes the crash + swift->objc bridging was added to the app. Also, a "draw" button was added in top right corner of map view that causes the polyline to be drawn. The project is now configured to use Release-iphoneos version of the framework, so this needs to be built first.
 
@fabian-guerra 

[0001-ios-App-crashing-when-drawing-polyline.-Click-button.patch.zip](https://github.com/mapbox/mapbox-gl-native/files/1487671/0001-ios-App-crashing-when-drawing-polyline.-Click-button.patch.zip)

**Comment by fabian-guerra** [comment]
Hi, @Suryu. Thank you for providing the patch. I am still not able to reproduce the problem.

![poland](https://user-images.githubusercontent.com/2745166/33081554-a262662a-cea8-11e7-8698-aa2a57bbc412.png)

**Comment by akitchen** [comment]
Hi there - I tried out the patch sent by @Suryu and noticed a few problems with the project configuration. When building the app it was still attempting to build & link the Debug mode `Mapbox.framework` within Xcode, and the path to the externally built framework wasn't correct.

In order to address this I removed discovery of implicit dependencies in `iosapp.xcscheme` and fixed up the build phases and reference to the externally-built `Mapbox.framework`. Once the project config was fixed up I was able to run the app and draw the route without any issue.

Please try applying this patch on top of the branch where the patch 0001 was created and let us know if you still run into issues. The only changes required for building & running after applying this patch would have to do with configuring code signing and API key.

Thanks!

[0002-Additional-adjustments-to-build-settings-for-integra.patch.zip](https://github.com/mapbox/mapbox-gl-native/files/1497013/0002-Additional-adjustments-to-build-settings-for-integra.patch.zip)

**Comment by shinma** [comment]
I would like to check this patch too, to which commit should it be applied?

**Comment by akitchen** [comment]
Here are the steps I took:

 - Mapbox SDK version 3.7.0 `git checkout ios-v3.7.0`
 - Build the SDK externally `make iframework BUILDTYPE=Release SYMBOLS=NO`
 - Apply [patch 0001](https://github.com/mapbox/mapbox-gl-native/files/1487671/0001-ios-App-crashing-when-drawing-polyline.-Click-button.patch.zip) (note whitespace warnings, ignore)
`git apply --check ~/Downloads/0001-ios-App-crashing-when-drawing-polyline.-Click-button.patch`
`git am --signoff < ~/Downloads/0001-ios-App-crashing-when-drawing-polyline.-Click-button.patch`
 - Apply [patch 0002](https://github.com/mapbox/mapbox-gl-native/files/1497013/0002-Additional-adjustments-to-build-settings-for-integra.patch.zip)
`git apply --check ~/Downloads/0002-Additional-adjustments-to-build-settings-for-integra.patch`
`git am --signoff < ~/Downloads/0002-Additional-adjustments-to-build-settings-for-integra.patch`
 - Adjust code signing
 - Build & run on device

**Comment by akitchen** [comment]
Hello @Suryu @shinma 

have you had a chance to revisit this using the configuration changes suggested in my patch? Please let us know as we are unable to reproduce the issue using an official release.

Thank you
