### ISSUE TITLE
Android double tap drag zoom gesture initiates camera movement late

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-native#10489]
**Platform:** Android 
**Mapbox SDK version:** 5.2.0-beta.5

### Steps to trigger behavior

 1. Open a map. 
 2. Perform a double-tap-drag zoom gesture (not sure if this has a more formal name)

### Expected behavior

Camera begins to zoom as soon as gesture is initiated. 

### Actual behavior

Camera begins to zoom partway through the gesture. It also appears that calculation of the zoom amount begins right away and is applied all at once when the camera eventually begins to zoom, resulting in an abrupt jump.

**Comment by tobrun** [comment]
Briefly looked into this, reason is the following code block:

```
      // Ignore short touches in case it is a tap
      // Also ignore small scales
      long time = detector.getEventTime();
      long interval = time - scaleBeginTime;
      if (!scaleGestureOccurred && (interval <= ViewConfiguration.getTapTimeout())) {
        return false;
      }
```

Ideally this is taking up with #10016 .

**Comment by zugaldia** [comment]
> Ideally this is taking up with #10016 .

@tobrun Considering that https://github.com/mapbox/mapbox-gl-native/issues/10016 is a larger lift, is there any fix we could introduce earlier to mitigate this issue?

**Comment by tobrun** [comment]
We could short wire it for now, this would introduce a couple of additional if checks in the onScale method.

**Comment by tobrun** [comment]
Going to be picked up as part of #10016
