### ISSUE TITLE
[Android] crash with beta.5 - LostLocationEngine

### ISSUE THREAD

**Issue by StasDoskalenko** [mapbox/mapbox-gl-native#10484]
Hi!
Just upgraded from beta4 to beta5 

> compile 'com.mapbox.mapboxsdk:mapbox-android-services:2.2.2'
>     compile 'com.mapbox.mapboxsdk:mapbox-android-telemetry:2.1.0@aar'
>     compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-beta.5@aar') {
>         transitive = true
>     }

and got the following error:

> E/AndroidRuntime: FATAL EXCEPTION: main
>                   Process: com.mapshighload, PID: 13213
>                   java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/services/android/telemetry/location/LostLocationEngine;
>                       at com.mapbox.services.android.telemetry.location.LostLocationEngineFactory.supply(LostLocationEngineFactory.java:17)
>                       at com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(LocationEngineProvider.java:44)
>                       at com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(LocationEngineProvider.java:23)
>                       at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:54)
>                       at com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLModule$1.run(ReactNativeMapboxGLModule.java:165)
>                       at android.os.Handler.handleCallback(Handler.java:751)
>                       at android.os.Handler.dispatchMessage(Handler.java:95)
>                       at android.os.Looper.loop(Looper.java:154)
>                       at android.app.ActivityThread.main(ActivityThread.java:6119)
>                       at java.lang.reflect.Method.invoke(Native Method)
>                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
>                    Caused by: java.lang.ClassNotFoundException: com.mapbox.services.android.telemetry.location.LostLocationEngine
>                       at java.lang.VMClassLoader.findLoadedClass(Native Method)
>                       at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
>                       at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
>                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
>                       at com.mapbox.services.android.telemetry.location.LostLocationEngineFactory.supply(LostLocationEngineFactory.java:17) 
>                       at com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(LocationEngineProvider.java:44) 
>                       at com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(LocationEngineProvider.java:23) 
>                       at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:54) 
>                       at com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLModule$1.run(ReactNativeMapboxGLModule.java:165) 
>                       at android.os.Handler.handleCallback(Handler.java:751) 
>                       at android.os.Handler.dispatchMessage(Handler.java:95) 
>                       at android.os.Looper.loop(Looper.java:154) 
>                       at android.app.ActivityThread.main(ActivityThread.java:6119) 
>                       at java.lang.reflect.Method.invoke(Native Method) 
>                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
>                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
>                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapzen/android/lost/api/LostApiClient$ConnectionCallbacks;
>                       at com.mapbox.services.android.telemetry.location.LostLocationEngineFactory.supply(LostLocationEngineFactory.java:17) 
>                       at com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(LocationEngineProvider.java:44) 
>                       at com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(LocationEngineProvider.java:23) 
>                       at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:54) 
>                       at com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLModule$1.run(ReactNativeMapboxGLModule.java:165) 
>                       at android.os.Handler.handleCallback(Handler.java:751) 
>                       at android.os.Handler.dispatchMessage(Handler.java:95) 
>                       at android.os.Looper.loop(Looper.java:154) 
>                       at android.app.ActivityThread.main(ActivityThread.java:6119) 
>                       at java.lang.reflect.Method.invoke(Native Method) 
>                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
>                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
>                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapzen.android.lost.api.LostApiClient$ConnectionCallbacks" on path: DexPathList[[zip file "/data/app/com.mapshighload-2/base.apk"],nativeLibraryDirectories=[/data/app/com.mapshighload-2/lib/x86, /data/app/com.mapshighload-2/base.apk!/lib/x86, /system/lib, /vendor/lib]]
>                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
>                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
>                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
>                       at com.mapbox.services.android.telemetry.location.LostLocationEngineFactory.supply(LostLocationEngineFactory.java:17) 
>                       at com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(LocationEngineProvider.java:44) 
>                       at com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(LocationEngineProvider.java:23) 
>                       at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:54) 
>                       at com.mapbox.reactnativemapboxgl.ReactNativeMapboxGLModule$1.run(ReactNativeMapboxGLModule.java:165) 
>                       at android.os.Handler.handleCallback(Handler.java:751) 
>                       at android.os.Handler.dispatchMessage(Handler.java:95) 
>                       at android.os.Looper.loop(Looper.java:154) 
>                       at android.app.ActivityThread.main(ActivityThread.java:6119) 
>                       at java.lang.reflect.Method.invoke(Native Method) 
>                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
>                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by Guardiola31337** [comment]
Hey @StasDoskalenko 👋 
Thanks for reaching out and report your problem.

Bumping `mapbox-android-services` and `mapbox-android-telemetry` dependencies to the latest version [`2.2.9`](https://github.com/mapbox/mapbox-java/releases/tag/v2.2.9) should fix your issue.

Let me know if it solves your problem.

**Comment by yperess** [comment]
`2.2.9` isn't published yet: https://mvnrepository.com/artifact/com.mapbox.mapboxsdk/mapbox-android-services

**Comment by Guardiola31337** [comment]
Hey @yperess MAS `2.2.9` is available in Maven Central https://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-services/2.2.9/

👀 https://search.maven.org/#artifactdetails%7Ccom.mapbox.mapboxsdk%7Cmapbox-android-services%7C2.2.9%7Caar

**Comment by yperess** [comment]
I have `mavenCentral()` in my `repositories` and `2.2.9` isn't resolving

**Comment by StasDoskalenko** [comment]
@Guardiola31337 hey thanks! I've tried latest versions too. No trick

**Comment by yperess** [comment]
@stasdoskalenko did you try importing lost directly, worked for me.

**Comment by Guardiola31337** [comment]
@StasDoskalenko are you using Lost? As @yperess mentioned per https://github.com/mapbox/mapbox-gl-native/pull/9488 the location provider is optional (we're not including Lost within the SDK anymore) and in https://github.com/mapbox/mapbox-gl-native/pull/10355 we bumped the Lost version to `3.0.4` https://github.com/mapbox/mapbox-gl-native/blob/ffea8e145f5b67bbeb7aec46c77d73b95ef6ea31/platform/android/dependencies.gradle#L23 which is the one that MAS `2.2.9` uses. Bumping to `3.0.4` should do the trick.

@yperess I've just tried it in a new simple project and it's working. Try `Invalidate Caches / Restart...` and `Clean Project`.

**Comment by yperess** [comment]
The location provider is not really optional unless I'm missing some options that can be passed, the offending line is:

```
Mapbox.getInstance(getApplicationContext(), MAPBOX_ACCESS_TOKEN);
```

**Comment by Guardiola31337** [comment]
@yperess for further information on making the location provider optional you can check https://github.com/mapbox/mapbox-gl-native/issues/9403 and the implementation details https://github.com/mapbox/mapbox-java/pull/502

**Comment by yperess** [comment]
:+1: `2.2.9` is resolving now but I'll point out that it's not correct to say that the lost library is no longer needed, running `./gradlew :app:dependencies` shows:

```
+--- com.mapbox.mapboxsdk:mapbox-android-services:2.2.9
|    +--- com.mapbox.mapboxsdk:mapbox-java-services:2.2.9
|    |    +--- com.mapbox.mapboxsdk:mapbox-java-geojson:2.2.9 (*)
|    |    +--- com.squareup.retrofit2:retrofit:2.2.0 (*)
|    |    +--- com.squareup.retrofit2:converter-gson:2.2.0 (*)
|    |    \--- com.squareup.okhttp3:logging-interceptor:3.6.0
|    |         \--- com.squareup.okhttp3:okhttp:3.6.0 -> 3.9.0 (*)
|    +--- com.mapbox.mapboxsdk:mapbox-android-telemetry:2.2.9 (*)
|    +--- com.android.support:appcompat-v7:25.4.0 -> 26.1.0 (*)
|    +--- com.android.support:support-compat:25.4.0 -> 26.1.0 (*)
|    +--- com.jakewharton.timber:timber:4.5.1
|    \--- com.mapzen.android:lost:3.0.4
|         +--- com.android.support:support-annotations:25.3.1 -> 26.1.0
|         \--- com.android.support:appcompat-v7:25.3.1 -> 26.1.0 (*)
```

Without the mapbox services library we still see this crash from simply calling `getInstance`.

**Comment by Guardiola31337** [comment]
@yperess 
> Without the mapbox services library we still see this crash from simply calling `getInstance`.

As indicated in the [documentation](https://www.mapbox.com/android-docs/map-sdk/overview/) in order to add the Mapbox SDK dependency you need to tweak you `build.gradle` as follows:

```groovy
repositories {
  mavenCentral()
}
 
dependencies {
  compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0@aar') {
    transitive = true
  }
}
```

If you do it as described above you won't get the crash you mentioned and you won't need to add MAS. We're not including Lost within the SDK anymore 👀 

```
+--- com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0
|    +--- com.android.support:support-annotations:25.4.0 -> 26.0.0-alpha1
|    +--- com.android.support:support-fragment:25.4.0 -> 26.0.0-alpha1
|    |    +--- com.android.support:support-compat:26.0.0-alpha1
|    |    |    \--- com.android.support:support-annotations:26.0.0-alpha1
|    |    +--- com.android.support:support-core-ui:26.0.0-alpha1
|    |    |    +--- com.android.support:support-annotations:26.0.0-alpha1
|    |    |    \--- com.android.support:support-compat:26.0.0-alpha1 (*)
|    |    \--- com.android.support:support-core-utils:26.0.0-alpha1
|    |         +--- com.android.support:support-annotations:26.0.0-alpha1
|    |         \--- com.android.support:support-compat:26.0.0-alpha1 (*)
|    +--- com.jakewharton.timber:timber:4.5.1
|    +--- com.squareup.okhttp3:okhttp:3.9.0
|    |    \--- com.squareup.okio:okio:1.13.0
|    +--- com.mapbox.mapboxsdk:mapbox-java-geojson:2.2.9
|    |    +--- com.mapbox.mapboxsdk:mapbox-java-core:2.2.9
|    |    \--- com.google.code.gson:gson:2.8.0
|    \--- com.mapbox.mapboxsdk:mapbox-android-telemetry:2.2.9
|         \--- com.squareup.okhttp3:okhttp:3.6.0 -> 3.9.0 (*)
```

For now, we're still including the Lost dependency in `mapbox-android-services` artifact https://github.com/mapbox/mapbox-java/blob/master/mapbox/libandroid-services/build.gradle#L46 (we're going to make Lost `provided` there in the next major release) but definitely Lost is no longer needed when including the `mapbox-android-sdk` dependency.

**Comment by tobrun** [comment]
Closing as answered, feel free to add more context to this ticket if needed and please let us know if you have trouble resolving the dependencies.

**Comment by StasDoskalenko** [comment]
@tobrun yeah thanks, all fine

**Comment by olsisaqe** [comment]
Proguard on 5.2.1 version of mapbox though is complaining that it can't find lost. 

Adding: `-dontwarn com.mapzen.android.lost.api.**` seems to fix. 

Logs: 

`Warning: com.mapbox.mapboxsdk.location.LocationSource: can't find superclass or interface com.mapzen.android.lost.api.LostApiClient$ConnectionCallbacks
Warning: com.mapbox.mapboxsdk.location.LocationSource: can't find superclass or interface com.mapzen.android.lost.api.LocationListener
Warning: com.mapbox.services.android.telemetry.location.LostLocationEngine: can't find superclass or interface com.mapzen.android.lost.api.LostApiClient$ConnectionCallbacks.....
`

**Comment by Guardiola31337** [comment]
Hey 👋 @olsisaqe thanks for reaching out and report your problem.

Did you try with `5.3.0` version (currently the latest)? Are you using any other Mapbox dependencies by any chance? There are some versions that are not compatible with each other. Could you share your build config (`build.gradle)? We run into a similar problem here https://github.com/mapbox/mapbox-android-demo/pull/588 which we solved tweaking the versions used (without Proguard rules) and I guess you could do the same if that's your issue.

**Comment by stoefln** [comment]
same problem here. `-dontwarn com.mapzen.android.lost.api.**`worked for me too. Thanks @olsisaqe
