### ISSUE TITLE
mapbox GL license and cache size limit

### ISSUE THREAD

**Issue by farfromrefug** [mapbox/mapbox-gl-native#10488]
Hi,

I am looking at switching to Mapbox GL native as an alternative to Google Maps. Currently comparing it to Carto Mobile SDK
The idea is not really to use it with Mapbox vector tiles. At least not now.
I am implementing a free and open source app so i need free vector tiles.
So i am looking at using mapzen tiles source and a bunch of other free raster sources (OSM, esri...).
To do that i might have to fork Mapbox-gl-native. 
I have look at the license and it seems that i can do that, right?

Also in this case can i raise the cache size limit? This is a must have for me as my app is made for hiking (so no network connection).

Thanks

**Comment by farfromrefug** [comment]
I understand that it might be a tricky issue for you, but i can of need an answer fast as i am about to fork and start developping.
I have gone through the license again and, even if i am not that good at reading licences, it seems i can fork and do the modifications i want on the framework.
I think the issue is with the terms of use of "mapbox data".
Just so you know i dont intend to make a totally different fork, i want to make PRs. But i intend to make a more source agnostic version of the framework that i or any other open source project can use whatever the use case (download restrictions, etc...)

Thanks

**Comment by jfirebaugh** [comment]
Hi @farfromrefug -- Mapbox GL Native is BSD licensed; you're free to fork and modify it under the terms of that license, and we welcome any contributions you make.

The cache size limit applies only to Mapbox tiles.

**Comment by farfromrefug** [comment]
Thanks @jfirebaugh for the answer, I actually completely missed the test here for mapbox url here:
https://github.com/mapbox/mapbox-gl-native/blob/e2702c76ead76b77f2ac3621673ef74e532d38d7/platform/default/mbgl/storage/offline_download.cpp#L357

Will start PRs right away!

Thanks again
