### ISSUE TITLE
Clip parent-tile symbols in mixed-zoom tiles

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native#10480]
Consider a tile at zoom `z`, partially covered by a child tile at zoom `z + 1`:

    +-----------------+
    |                 |
    |                 |
    |                 |
    |--------+        |
    |    * OAK        |
    | * SF   |        |
    |        |        |
    +--------+--------+

In our current logic, symbols are rendered without clipping for both tiles. We rely on the `CrossTileSymbolIndex` to prevent duplicates from being double-drawn (in fact, we _draw_ duplicates, but we make the duplicate copies invisible). We rely on the global `CollisionIndex` to prevent collisions between the child and parent tile.

However, symbols from the parent tile that are in the quadrant covered by the child tile can still "show through", as long as they don't collide with anything in the same layer. Once the parent tile is removed, they'll disappear, and maybe be replaced by something in a later layer from the child tile. This means that the quadrant covered by the child ends up showing three sets of symbols over the course of loading: parent -> mixed -> child. That "mixed" phase isn't really wrong, but it's unnecessary and can lead to extra label cross-fading (aka collision/label instability).

We could fix this if at placement time we were aware of which quadrants of a tile were covered by children, and just avoided placing symbols in those areas.

/cc @ansis @jfirebaugh @kkaefer

**Comment by kkaefer** [comment]
I think this is a great idea. We already have logic to calculate the covered children masks that we use for raster tiles:

https://github.com/mapbox/mapbox-gl-native/blob/dcd7da14f6627a09a5840a3046b5708449962f69/src/mbgl/algorithm/update_tile_masks.hpp#L48-L125
