### ISSUE TITLE
Android app doesn't work offline

### ISSUE THREAD

**Issue by thomas-huet** [mapbox/mapbox-gl-native#1048]
The android app seems to cache tiles (the cache size used by the app increases as I explore new parts of the world) but doesn't seem to read from the cache (tiles are not displayed faster if they were already visited and are not accessible when offline).

**Comment by incanus** [comment]
Not sure if Android-specific — @thomas-huet can you try on Linux or OS X desktop? Or iOS?

**Comment by thomas-huet** [comment]
I can't build it for linux. `./configure` fails (`${MASON_PLATFORM}` seems to be empty) and `make linux` fails too (missing `GLFW/glfw3.h`).

**Comment by incanus** [comment]
https://github.com/mapbox/mapbox-gl-native/issues/584
