### ISSUE TITLE
Remove underline from static snapshot attribution text

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#10493]
The snapshot attribution text in 3.7.0 has the text styled with an underline, which could give the impression that they’re hyperlinks — they are not, so let’s get rid of that underline.

_Maybe also round the corners of the translucent box, too._

<img width="528" alt="screen shot 2017-11-17 at 2 28 54 pm" src="https://user-images.githubusercontent.com/1198851/32965126-acfeda6c-cba3-11e7-8c67-71030d90715c.png">

/cc @fabian-guerra @1ec5

**Comment by 1ec5** [comment]
This is happening in #10456.

**Comment by 1ec5** [comment]
> Maybe also round the corners of the translucent box, too.

I’m actually kind of OK with the squared look on a snapshot, at least when the image is viewed in isolation. But if the snapshot is displayed in UI, then I can see a case for rounding the corners like we do for MGLMapView.

**Comment by friedbunny** [comment]
Done in #10456.
