### ISSUE TITLE
GeometryTileProvider should allow tile-id based callback methods

### ISSUE THREAD

**Issue by asheemmamoowala** [mapbox/mapbox-gl-native#10495]
The custom geometry source API on iOS/macOS (`MGLComputedShapeSource`) allows implementers to pick between callbacks that specify a tile-id and a geographic bound.

This allows using existing tiled data more easily.

```
- (NSArray<MGLShape <MGLFeature> *>*)featuresInTileAtX:(NSUInteger)x y:(NSUInteger)y zoomLevel:(NSUInteger)zoomLevel;

- (NSArray<MGLShape <MGLFeature> *>*)featuresInCoordinateBounds:(MGLCoordinateBounds)bounds zoomLevel:(NSUInteger)zoomLevel;
```

The Android SDK should also provide such an option as part of the `GeomegtryTileProvider`.

**Comment by tobrun** [comment]
Really like the flexibility, you either hook into the high level model objects or the low level x,y,z tile coordinates. One top of exposing an interface for each, I'm interested in adding an adapter class that provides empty implementations.
