### ISSUE TITLE
Refactor MGLMapSnapshotter attribution

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#10490]
As followup from #10456, MGLMapSnapshotter’s attribution logic is inflexible and needs to be refactored:

* MGLSnapshotAttributionOptions goes away.
* An `MGLAttributionInfoStyle` enumeration along the lines of `NSFormattingUnitStyle` or `NSDateFormatterStyle`. “Short” for a logo means just the helmet; “short” for an attribution item could mean abbreviation.
* `-[MGLMapSnapshotter logoImageWithStyle:]` returns either the full image or the helmet image.
* `-[MGLAttributionInfo sizeWithStyle:]` determines the size of an individual attribution image, depending on whether it’s abbreviated or written out in full.
* `-[MGLMapSnapshotter attributionSizeWithLogoStyle:sourceAttributionStyle:]` takes two `MGLAttributionInfoStyle`s and returns the size of the attribution.
* The snapshot completion handler tries calling `-[MGLMapSnapshotter attributionSizeWithLogoStyle:sourceAttributionStyle:]` with each permutation of attribution info styles. Once one of the permutations fits the snapshot’s width, it uses `-[MGLMapSnapshotter logoImageWithStyle:]` and MGLAttributionInfo to put together the attribution.

/cc @fabian-guerra @lilykaiser

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/10525
