### ISSUE TITLE
Carthage can't install 3.7.0 (Not available in json spec)

### ISSUE THREAD

**Issue by Sealos** [mapbox/mapbox-gl-native#10508]
**Platform: iOS
**Mapbox SDK version: 3.7.0
**Carthage 0.26.2

### Steps to trigger behavior

 1. Use Carthage to install mapbox (Following the instructions on https://www.mapbox.com/install/ios/carthage/)
 2. Run carthage update

### Expected behavior
Carthage correctly installs version 3.7.0 of Mapbox iOS SDK

### Actual behavior
Carthage fails with error code Parse error: syntax of version "3.4.0" is unsupported in line: 3.4.0-beta.4

Carthage json spec does not contain version 3.7.0 (https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json)

**Comment by friedbunny** [comment]
Thanks for posting — there was a delay in publishing the site updates (including the 3.7.0 docs and Carthage spec), but these should be available now for 3.7.0.
