### ISSUE TITLE
MapBox Telemetry does not shutdown when the app enters background

### ISSUE THREAD

**Issue by Gerungofulus** [mapbox/mapbox-gl-native#10503]
When the app enters background, the location manager of map box telemetry does not get suspended. Even though we are not using MapBox's user location marker, we were having background location updates. We put comments on our own instance of CLLocationManager so we made sure none of our code was issuing the problem. The LocationEnergyImpact was still showing to be low when the app was suspended using the home button. After turning of the MapBox Telemetry, the location energy impact returned to zero on app suspense.

**Platform:**
- iOS (iPhones 5-7+)
**Mapbox SDK version:**

### Steps to trigger behavior

 1. Open the Location Energy Impact instrument in Instruments (e.g. by clicking on "Location Profile" in the energy gauge in Xcode)
 2. Suspend a test app.
 3. See that the energy impact is still reported to be low and therefore existent
 4. Open the app again and disable telemetry
 5. suspend the app
 6. see how the energy impact is reported to be zero

### Expected behavior

Telemetry or at least location data should be suspended when the app is suspended as it leads to energy drain.

### Actual behavior

Telemetry is not suspended

**Comment by boundsj** [comment]
Thanks for your feedback. This is intended behavior and is the result of our telemetry module's location manager running in the background in a host application that has been given `always` location permissions from the user.

As developers we understand the constraints of resources on mobile. Our data collection has been optimized in collaboration with developers in our community and has been field tested with millions of users to make sure we can improve maps without noticeable impact on the battery for applications that use the Mapbox Map SDKs.

Our Maps SDK's telemetry collection implementation is available to review in this repo and you can also check out [our telemetry overview](https://www.mapbox.com/telemetry/) for more information on how we use this aggregated data (_spoiler: to improve OSM_) and about how fiercely we keep it anonymous and private. You're always welcome to get in touch with us [through our website](https://www.mapbox.com/contact/) about specific concerns you have about your particular application.
