### ISSUE TITLE
Unable to read the license file 

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#10512]
**Platform: iOS**
**Mapbox SDK version: v3.7.0**
**pod version: 1.4.0.beta2**

### Steps to trigger behavior

 1. Create pod file
 2. Target version 3.7.0
 3. pod install

### Expected behavior

Clean output, no warnings

### Actual behavior

The installation does not fail, but it does warn about not being able to read the license file:

```
Pod installation complete! There are 10 dependencies from the Podfile and 17 total pods installed.

[!] Unable to read the license file `/Users/bobby/Documents/mapbox/voyage-ios/Pods/Mapbox-iOS-SDK/LICENSE.md` for the spec `Mapbox-iOS-SDK (3.7.0)`

[!] Unable to read the license file `/Users/bobby/Documents/mapbox/voyage-ios/Pods/Mapbox-iOS-SDK/LICENSE.md` for the spec `Mapbox-iOS-SDK (3.7.0)`

[!] Unable to read the license file `/Users/bobby/Documents/mapbox/voyage-ios/Pods/Mapbox-iOS-SDK/LICENSE.md` for the spec `Mapbox-iOS-SDK (3.7.0)`

[!] Unable to read the license file `/Users/bobby/Documents/mapbox/voyage-ios/Pods/Mapbox-iOS-SDK/LICENSE.md` for the spec `Mapbox-iOS-SDK (3.7.0)`
```

/cc @friedbunny @fabian-guerra

**Comment by gduranon** [comment]
Same happens to me... also, the mapbox-ios-sdk cocoa pods directory is empty (this is why the licenses can't be found)

**Comment by AkdM** [comment]
Same to me. What is happening?

**Comment by bsudekum** [comment]
@gduranon @AkdM can you clear your Pods folder and cache and try one more time?

**Comment by AkdM** [comment]
Mh, that's strange. I've reinstalled Xcode and it worked.

Btw, Clearing the pod cache (I ran `pod cache clean --all` multiple times) did nothing.

**Comment by friedbunny** [comment]
There was an issue for a couple hours today with the file being downloaded — we’ve fixed it, but caches are likely to retain the bad version. To clear the problematic cache, try this:

```
pod cache clean Mapbox-iOS-SDK
rm Pods/Mapbox-iOS-SDK/
```

And then `pod update`, like usual.
