### ISSUE TITLE
请问是否可以纯内网离线部署？

### ISSUE THREAD

**Issue by ZhanRu** [mapbox/mapbox-gl-native#10516]
在完全没有任何外部网络的情况下是否可以使用呢？

Can it be used without any external network?

**Comment by tobrun** [comment]
Not sure what your question is about but in general use you will need an internet connection though we expose some offline api's. These api's allow you to download tiles upfront and use them without an internet connection. Going to close this issue as non-actionable. Feel free to add more context.

**Comment by ZhanRu** [comment]
I see. Thank you.
