### ISSUE TITLE
Emerald sprite showing up in Bright

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1051]
At least I think that's what that is. As of https://github.com/mapbox/mapbox-gl-native/commit/188331505e78ccacb8f010b91d549735062c69e6. 

/cc @peterqliu 

![ios simulator screen shot mar 21 2015 1 12 15 pm](https://cloud.githubusercontent.com/assets/17722/6766661/1f87d4ac-cfcc-11e4-99e7-93471178d7ee.png)

**Comment by 1ec5** [comment]
Yes, that’s a clipped Interstate shield coming through, and only Emerald has Interstate shields at the moment. Actually, I’m seeing a clipped U.S. Route shield in the same place instead.

**Comment by 1ec5** [comment]
A different sprite shows up every time you relaunch the app.

**Comment by incanus** [comment]
I think this is related to having two styles with fill sprites in them, which we've only recently started to do.

**Comment by incanus** [comment]
Easiest test for this theory would be: 

* Add any other style in which uses fill sprites. 
* Select it first on start. 
* Note its sprites used in Emerald & Bright. 

Or just swap Bright & Emerald.

**Comment by incanus** [comment]
Confirmed this isn't happening anymore.
