### ISSUE TITLE
IOS: app crashes after upgrade to Mapbox sdk version 3.7

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#10518]
**Platform:*iOS*
**Mapbox SDK version:*3.7.0*

### Steps to trigger behavior

 1. Open MapboxMap on iOS Device
 2. Set center of map (MapView.setCenter)
 3. Do this multiple times

### Expected behavior

Map pans smoothly

### Actual behavior

After 3 or 4 center changes, I get this strange error:

<img width="1440" alt="schermafbeelding 2017-11-21 om 14 46 45" src="https://user-images.githubusercontent.com/10425157/33075946-7490d088-cecb-11e7-83d7-f1f9318d68a8.png">

I have no idea how to solve is. This issue is starting since I upgraded from 3.6 to 3.7.

UPDATE: when I change center of map, it seems that regionDidChangeAnimated is called multiple times. Is this normal behavior? Functions inside regiondDidChangeAnimated are called to much times after each other. Is this normal behavior?

**Comment by fabian-guerra** [comment]
Hi, @nijs9. Thank you for using Mapbox. I am sorry to hear you are having some issues with our latest release. Could you please help us with a test app or code we could use to track down what is causing the crash?

**Comment by nijs9** [comment]
Hi fabian-guerra, I founded the issue. My code that is executed in regiondDidChangeAnimated is called several times when changing mapView centercoordinate and that is causing this issue. Is it possible in previous versions regiondDidChangeAnimated called only once when changing map center coordinate? Only when set camera animated movement, regionDidChanged is called multiple times. When moving without animation, it's only called once.

**Comment by fabian-guerra** [comment]
Hi, @nijs9. Are you callling `setCenterCoordinate` often? could you please post a test app or code snipet that help us track down the issue.

**Comment by flash1108** [comment]
Hi, I have the same problem.
I just called setCamera 2 or 3 times in succession and it caused the crash.
This problem only occurs in SDK 3.7.x.


<img width="740" alt="screen shot 2018-01-02 at 10 20 10 pm" src="https://user-images.githubusercontent.com/783920/34486498-2f080a2a-f00b-11e7-8df8-6b06a00849da.png">
