### ISSUE TITLE
Installing binary framework 3.7.0 via Carthage fails

### ISSUE THREAD

**Issue by fanquake** [mapbox/mapbox-gl-native#10513]
**Platform:** iOS
**Mapbox SDK version:** 3.7.0
**Carthage version**: 0.26.2

### Steps to trigger behavior

 1. Update cartfile `binary "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json" ~> 3.7.0`
 2. `carthage update --platform ios`

### Expected behavior
Successful installation.

### Actual behavior
The install fails. Looks similar to https://github.com/Carthage/Carthage/issues/1776.

```
*** Downloading binary-only framework Mapbox-iOS-SDK at "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json"
Failed to read file or folder at /private/var/folders/rb/jqqd25w926s5429rf58_zsv00000gn/T/carthage-archive.Wqzr7M/__MACOSX/mapbox-ios-sdk-3.7.0-dynamic/dynamic/Mapbox.framework: Error Domain=com.antitypical.Result Code=0 "the DTSDKName key in its plist file is missing" UserInfo={com.antitypical.Result.file=/tmp/carthage-20171014-5839-1rwellh/Source/CarthageKit/Project.swift, com.antitypical.Result.function=readFailed, com.antitypical.Result.line=1087, NSLocalizedDescription=the DTSDKName key in its plist file is missing}
```

**Comment by boundsj** [comment]
Thanks for the report. This was probably related to https://github.com/mapbox/mapbox-gl-native/issues/10512 and should be fixed now. Can you please clear Carthage caches and try again?

**Comment by fanquake** [comment]
Clearing the caches and rebuilding seemed to solve the problem. Thanks.
