### ISSUE TITLE
fail gracefully for bad sprites

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1052]
Currently we crash hard if unexpected types are encountered in sprite JSON: 

https://github.com/mapbox/mapbox-gl-native/blob/188331505e78ccacb8f010b91d549735062c69e6/src/mbgl/map/sprite.cpp#L135

![screen shot 2015-03-21 at 5 12 52 pm](https://cloud.githubusercontent.com/assets/17722/6767474/1aca668c-cfef-11e4-8a91-28f41ec08c15.png)

![screen shot 2015-03-21 at 5 12 48 pm](https://cloud.githubusercontent.com/assets/17722/6767476/1e0dbdee-cfef-11e4-9352-5c369d759510.png)

Yes, this is incorrect in the sprite, but we shouldn't crash, particularly when sprite sheets could be coming form the net. 

Turned up in https://github.com/mapbox/mapbox-gl-styles/pull/43#issuecomment-84480098. 

/cc @kkaefer

**Comment by kkaefer** [comment]
See #219, #308.

**Comment by incanus** [comment]
Ok, closing in favor of #219.
