### ISSUE TITLE
Revisit LatLngBounds API

### ISSUE THREAD

**Issue by wedi** [mapbox/mapbox-gl-native#10529]
Is there a specific reason why [`LatLngBounds.fromLatLngs(final List<? extends ILatLng> latLngs)`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java#L196
) is not declared public?

If not I'd like to suggest to make it public like all other methods in this class. I can make a pull request.

**Platform:** Android
**Mapbox SDK version:** 5.2.0

**Comment by osana** [comment]
It would be good to add some other convenience methods to LatLngBounds.Builder 
either constructor: 
public Builder(final double northLatitude, final double eastLongitude, final double southLatitude,
               final double westLongitude);

**Comment by tobrun** [comment]
I renamed this issue to take in account multiple changes to the API.

Besides above comments, I would like to include some methods that could mitigate memory churn in code paths that are called often (eg. providing a bounds with a custom source).

**Comment by tobrun** [comment]
Since this issue we had multiple patches on the LatLngBounds API by @osana, 
I think we are in a good shape to close this.
