### ISSUE TITLE
Add data-driven-styling support for `text-font`

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#10535]
Port https://github.com/mapbox/mapbox-gl-js/pull/5698 / https://github.com/mapbox/mapbox-gl-js/issues/5568.

**Comment by 1ec5** [comment]
#10620 pulled in a new version of the style specification that includes the changes from mapbox/mapbox-gl-js#5698. As a result, running `make style-code` now changes the `text-font` implementations to assume data-driven styling support. In #10726, the iOS/macOS runtime styling code generation script manually overrides that change (as well as heatmap/hillshade layers).
