### ISSUE TITLE
Calling requestProgress on a completed offline pack will make it inactive 

### ISSUE THREAD

**Issue by arnekaiser** [mapbox/mapbox-gl-native#10534]
**Platform:** iOS 11.1.2 
**Mapbox SDK version:** 3.7.0 (ObjC)

### Steps to trigger behavior

 1. Download an offline pack
 2. Check if the state is "MGLOfflinePackStateComplete"
 3. Call [pack requestProgress]

### Expected behavior

State of the offline pack is still "MGLOfflinePackStateComplete" in callback

### Actual behavior (since Version 3.7.0)

State of the offline pack is "MGLOfflinePackStateInactive" in callback

**Comment by arnekaiser** [comment]
The issue doesn't appear in Version 4.4.1 anymore.

**Comment by pteasima** [comment]
@arnekaiser this is happening to me on iOS12, Mapbox 4.5.0. Could you please reopen this issue so I dont have to duplicate it?

**Comment by pteasima** [comment]
@mapbox let me know if you cant reproduce this, Ill provide sample code.

**Comment by pteasima** [comment]
Fyi for me this is fixed on 5.2.0

**Comment by julianrex** [comment]
Good to hear - thanks for the update @pteasima!
