### ISSUE TITLE
QuerySource features returns duplicate features

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#10530]
[QuerySourceFeaturesActivity](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QuerySourceFeaturesActivity.java) seems to be broken, querySourceFeatures is returning 4 identical features [on this line](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QuerySourceFeaturesActivity.java#L61) while there was only one added [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QuerySourceFeaturesActivity.java#L50).

**Comment by tobrun** [comment]
Capturing from @ivovandongen this is behaviour comes from tile borders. The coordinate 0,0 is precisely found on the border of 4 tiles. We aren't filtering out duplicates atm though I feel that would be the most logical.

**Comment by jfirebaugh** [comment]
This is expected behavior. The same caveats apply to native as are [outlined](https://www.mapbox.com/mapbox-gl-js/api#map#querysourcefeatures) for GL JS: 

> Because features come from tiled vector data or GeoJSON data that is converted to tiles internally, feature geometries may be split or duplicated across tile boundaries and, as a result, features may appear multiple times in query results. For example, suppose there is a highway running through the bounding rectangle of a query. The results of the query will be those parts of the highway that lie within the map tiles covering the bounding rectangle, even if the highway extends into other tiles, and the portion of the highway within each map tile will be returned as a separate feature. Similarly, a point feature near a tile boundary may appear in multiple tiles due to tile buffering.
