### ISSUE TITLE
Android Location - Security API 26-27 

### ISSUE THREAD

**Issue by nikiizvorski** [mapbox/mapbox-gl-native#10543]
Hi just wanted to report what we are getting on the newest devices. And its not coming from No Permission its not properly made for the new apis maybe its Android Issue.

Exception java.lang.RuntimeException: Unable to resume activity java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.

and i found another one with the permissions again

Exception in MapView.OnMapChangedListener
                                                               java.lang.SecurityException: Client must have ACCESS_FINE_LOCATION permission to request PRIORITY_HIGH_ACCURACY locations.

**Platform: Android
**Mapbox SDK version: - Latests 5.2.0

### Steps to trigger behavior

 1. Just normal usage as before it works on old apis no issue

### Expected behavior

- Not to stop the process or crash

### Actual behavior

- Stopping app flow and crashing

**Comment by nikiizvorski** [comment]
Hi there just to point what i found about the SecurityException since permissions like the ones that MapBox request are considered in a new group after API 26-27. Here is something that goes around on the tested devices we have. Most of the time its working better but need to be included on your side too.

if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            if (ContextCompat.checkSelfPermission(getApplicationContext(), Manifest.permission.WRITE_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED
                    && ContextCompat.checkSelfPermission(getApplicationContext(), Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED)
                requestPermissions(new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.ACCESS_COARSE_LOCATION}, PERMISSION_LOCATION_STORAGE);
            else if (ContextCompat.checkSelfPermission(getApplicationContext(), Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED)
                requestPermissions(new String[]{Manifest.permission.ACCESS_COARSE_LOCATION}, PERMISSION_LOCATION);
            else if (ContextCompat.checkSelfPermission(getApplicationContext(), Manifest.permission.WRITE_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED)
                requestPermissions(new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE}, PERMISSION_WRITE_EXTERNAL);
            else if (ContextCompat.checkSelfPermission(getApplicationContext(), Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED)
                requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION}, PERMISSION_LOCATION_FINE);        }

Handle the result after:

`@Override
    public void onRequestPermissionsResult(int requestCode, String permissions[], int[] grantResults) {
        Timber.d("Permission" + permissions[0]);
        Timber.d("Grant Results size " + grantResults.length);
        switch (requestCode) {
            case PERMISSION_LOCATION: {
                if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                    //Manage Permission Granted
                    buttonSignup.setVisibility(View.VISIBLE);
                    facebookLoginButton.setVisibility(View.VISIBLE);
                    Log.d("TAG", "camera permission granted");
                } else {
                    if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.M)
                        requestPermissions(new String[]{Manifest.permission.ACCESS_COARSE_LOCATION}, PERMISSION_LOCATION);
                    // Manage Permission Denied
                }
                break;
            }
            case PERMISSION_LOCATION_FINE: {
                if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                    //Manage Permission Granted
                    buttonSignup.setVisibility(View.VISIBLE);
                    facebookLoginButton.setVisibility(View.VISIBLE);
                    Log.d("TAG", "camera permission granted");
                } else {
                    if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.M)
                        requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION}, PERMISSION_LOCATION_FINE);
                    // Manage Permission Denied
                }
                break;
            }
        }
    }`

Since these permission doesn't exist in the group we want them or they are going to be moved not sure about it, we need to ask for them even if there is no dialog sometimes. You will need to include the check in the library.

**Comment by nikiizvorski** [comment]
Radar had the same issue its solved you can try to ask them how they did solve the issue since its mandatory! On new devices MapBox is useless and with the depricated apis even more.

**Comment by zugaldia** [comment]
@Guardiola31337 Looks like there're some permission exceptions that we should catch at the SDK level? We probably don't want to crash the app, instead emit some kind of warning.

**Comment by nikiizvorski** [comment]
Here is a small solution to be added if you want i can place it inside and push. Please let me know

`@Override
    public boolean checkSelfPermissions() {
        return (Build.VERSION.SDK_INT < 23) || ((this != null) && (ContextCompat.checkSelfPermission(this, "android.permission.ACCESS_FINE_LOCATION") == 0));
    }`

` @Override
    public void requestPermissions(Activity activity) {
        if ((Build.VERSION.SDK_INT >= 23) && (ContextCompat.checkSelfPermission(activity, "android.permission.ACCESS_FINE_LOCATION") != 0)) {
            int requestCode = 0;
            ActivityCompat.requestPermissions(activity, new String[] { "android.permission.ACCESS_FINE_LOCATION" }, requestCode);
        }
    }`

**Comment by Guardiola31337** [comment]
Hey @nikiizvorski thanks for reaching out and report your problem.

Tested location-related activities in the [test app](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android/MapboxGLAndroidSDKTestApp) on a Google Pixel XL API 26-27 and I wasn't able to reproduce the issue described in OP.

Could you add some more information for reproducing the `SecurityException` (minimal example) or any other specifics around your test setup? Do you have some more information on used device? If there is any sample or pseudo code you can provide, that would be really helpful because without having additional information, I'm unable to reproduce.

**Comment by nikiairdates** [comment]
Here is an example of what happens:

`Exception java.lang.RuntimeException: Unable to resume activity java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
`

**Comment by Guardiola31337** [comment]
@nikiairdates could you add the code that throws https://github.com/mapbox/mapbox-gl-native/issues/10543#issuecomment-348936859
Without that information, it's hard to reproduce the same scenario. Thank you.

**Comment by nikiairdates** [comment]
Yep there you go an example:

`mapView.onCreate(savedInstanceState);

        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(final MapboxMap mapboxMap) {
                MapActivity.this.mapboxMap = mapboxMap;
                goToMyLastLocation();

                RelativeLayout llBottomSheet = (RelativeLayout) findViewById(R.id.bottom_sheet);
                final BottomSheetBehavior bottomSheetBehavior = BottomSheetBehavior.from(llBottomSheet);
                presenter.setCustomViewMyLocation();

                if (checkSelfPermissions()) {
                    if (mapboxMap != null) {
                        if (mapboxMap.getMyLocationViewSettings() != null) {
                            mapboxMap.getMyLocationViewSettings().setAccuracyAlpha(0);
                        }

                        mapboxMap.setMyLocationEnabled(true);

                        mapboxMap.getUiSettings().setRotateGesturesEnabled(false);

                        if (mapboxMap.getTrackingSettings() != null) {
                            mapboxMap.getTrackingSettings().setMyBearingTrackingMode(MyBearingTracking.NONE);
                        }
                    }
                } else {
                    requestPermissions(MapActivity.this);
                }
            }
        });`

after that persists mapbox.onStart and on mapbox.Listeners

Kind Regards,
Niki

**Comment by Guardiola31337** [comment]
Hey @nikiairdates 👋
 
```java
mapView.getMapAsync(new OnMapReadyCallback() {
      @Override
      public void onMapReady(@NonNull final MapboxMap mapboxMap) {
        mapboxMap.setMyLocationEnabled(true);
      }
});
```
```xml
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
```
Tested ☝️ in a simple activity of a new project and I'm not getting any security exception.

If I manually granted the location permissions and enable location, the current location view is displayed on the map 👀

![location_api_27](https://user-images.githubusercontent.com/1668582/33574164-75ac2dba-d938-11e7-9ad4-bb529aa0034e.gif)

For further info on how to request permissions at runtime, you can check the [test app location-related examples](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/userlocation).

In any case, `MyLocationView` and related classes are deprecated, you should use the [location layer plugin](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/locationlayer) instead. Feel free to report any issues you have in that repo. Closing.

**Comment by zugaldia** [comment]
Documentation for the location layer plugin is available on https://www.mapbox.com/android-docs/plugins/overview/location-layer/.

**Comment by nikiairdates** [comment]
@Guardiola31337 Are you using your new location plugin try not to use that one and see what happens! Since it doesn't seem to track or work properly as it should! And then say that the issue i bring is not relevant :)
