### ISSUE TITLE
Audit headers for nullability (Swift support)

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1054]
Once we distribute a framework (#828), developers will be able to interface with `MGLMapView` and other classes in Swift. We’ll want to audit the headers for nullability so that developers don’t have to deal with a litany of implicitly unwrapped optionals like `NSString!`.

More information:
* https://developer.apple.com/swift/blog/?id=25
* http://nshipster.com/swift-1.2/#nullability-annotations

**Comment by incanus** [comment]
:+1:

**Comment by 1ec5** [comment]
After #975 is merged, this work will still be blocked by travis-ci/travis-ci#3216 because the nullability qualifiers will still go into the Objective-C code that Travis builds.

**Comment by 1ec5** [comment]
Apparently this isn’t completely blocked: Automatic uses [conditionally-compiled macros](https://github.com/Automatic/Automatic-iOS-SDK/blob/bd6a889a9d343263cac3ebbc035517fbbf178a57/AutomaticSDK/AUTClient.h#L13) to declare nullability:

```objc
#if __has_feature(nullability)
#define mgl_nonnull nonnull
#define mgl_nullable nullable
// …
#else
#define mgl_nonnull
#define mgl_nullable
// …
#endif
```

**Comment by 1ec5** [comment]
Or, come to think of it, even just:

```objc
#if !__has_feature(nullability)
#define nonnull
#define nullable
// …
#endif
```
