### ISSUE TITLE
Problem with selecting annonations

### ISSUE THREAD

**Issue by junestchick** [mapbox/mapbox-gl-native#10540]
**Platform: ios**
**Mapbox SDK version: 3.7**

Hello, 
I have 2 annonation with custom view on the map: A and B. It seems that there is only 1 annonation because A is lying over B. (or A has same coordinate with B).

### Steps to trigger behavior

 1. Select A -> A is selected.
 2. Deselect A -> A is deselected

### Expected behavior
When deselect A, A is deselected and B is not selected.
### Actual behavior
When select A, B is not selected -> ok
When deselect A, A is deselected but B is selected.

Thanks!

**Comment by fabian-guerra** [comment]
Hi, @junestchick. Thank you for using Mapbox. If you have two annotations that share the _same coordinates_ and if you tap twice on them it will deselect the first and select the second. It's the expected behavior. Could you please check if you tap outside the annotations deselects them?

**Comment by junestchick** [comment]
Ok i got it.
