### ISSUE TITLE
Android Foreground Drawable

### ISSUE THREAD

**Issue by nikiizvorski** [mapbox/mapbox-gl-native#10544]
Hello we are currently experiencing a lot issues with your Location Plugin and we don't want to use it as our default client for sure. There are issues with Lifecycle Activity too.

And since the setForegroundDrawable is depricated and we have no more control on that how are we supposed to use that? Please answer since its a serious matter. And seems on top the method is no longer working in API 26-27 too

**Platform: Android 7.0, 7.1 - 8.0
**Mapbox SDK version: Latest 5.2.0

### Steps to trigger behavior

 1. Just normal usage
 2. Drawing the drawable as usual
 3. Place as Foreground Drawable for the blue dot

### Expected behavior

- To work and to show the marker on latest ApI and maybe revert back and get the method again.

- And a proper example would not hurt since the one that was given doesn't seem to work.

- https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/locationlayer is broken

### Actual behavior

 - Not showing anything on newest APIs and being depricated.

**Comment by nikiizvorski** [comment]
Hi there. We are still experiencing the current issue some support wouldn't be nice. 

Thanks you

**Comment by DejanRistic** [comment]
Noting here that i filed a similar issue about customizing the user location layer here:
https://github.com/mapbox/mapbox-plugins-android/issues/178

**Comment by nikiairdates** [comment]
Hey any updates on this?

**Comment by lilykaiser** [comment]
Thanks for the report! Since this issue is related to the location layer plugin, related work will be tracked [here](https://github.com/mapbox/mapbox-plugins-android/issues/178) as a starting point. Closing this ticket.
