### ISSUE TITLE
SymbolLayer dissapears

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#10559]
When adding a 1-point backed SymbolLayer to the map and assigning it an iconImage,
I'm seeing the following behaviour on master (not on release branch):

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/2151639/33210105-238e1704-d119-11e7-9d24-7aff30c624a7.gif)

[Code](https://github.com/mapbox/mapbox-gl-native/blob/05ec852885608070d7a5df50c7a098441e643bce/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/CustomSpriteActivity.java#L73)

cc @ChrisLoer @ansis

**Comment by ChrisLoer** [comment]
I may be missing something, but isn't this what we expect now that we've implemented cross-source symbol placement? Before, this icon was placed with its own source so it could never collide with anything. Now, it's placed along with everything else, so if you want to avoid collision you need to use `icon-allow-overlap`/`icon-ignore-placement`.

I wonder how many users unintentionally depend on the current lack of cross-source placement. We could build a "grandfathered" mode in that kept the old behavior by default, but in most cases I imagine the new behavior is closer to what users would expect, and if the new behavior causes a problem it should be easy to adjust your style to get the behavior you want (and a style that's cross-source aware could still degrade to the same behavior with earlier versions of the SDK that don't support cross-source placement).

**Comment by tobrun** [comment]
Thank you for adding context, I had a hunch that this was expected behavior but didn't knew about `icon-ignore-placement` to get it working again. With that in place it's the same as before!

I don't mind this becoming default behavior though this would mean that this feature is a Semver change. Re. grandfathering users, in the past we have written migration docs for major version updates, this change is something that could be included in that. 

cc @mapbox/ios

**Comment by 1ec5** [comment]
Unless annotations suddenly start disappearing due to collision, I think it’s fine to ship this change without worrying about backwards incompatibility. But this change is going into a semver-major release anyways. 😉

**Comment by tobrun** [comment]
I have been experimenting with animating symbol layer items, 
when working on the release branch everything works:

![ezgif com-video-to-gif 19](https://user-images.githubusercontent.com/2151639/34251137-596f19b4-e63f-11e7-98c5-a31213357b3a.gif)

But the same code is resulting in the following on master:

![ezgif com-video-to-gif 21](https://user-images.githubusercontent.com/2151639/34251108-4061000e-e63f-11e7-86fc-267058c02171.gif)

What the code is doing is use an Android SDK animator to perform the animation, which each animation callback we are calling setGeoJSON on the GeoJSON source. Is this something we can optimise symbol placement for?

**Comment by ChrisLoer** [comment]
> Is this something we can optimise symbol placement for?

Yeah, we're in the middle of realizing we broke this on GL-JS. We think we have fixes in place that we can port to address this: https://github.com/mapbox/mapbox-gl-js/issues/5716 (native port is https://github.com/mapbox/mapbox-gl-native/issues/10536), https://github.com/mapbox/mapbox-gl-js/issues/5837, https://github.com/mapbox/mapbox-gl-js/issues/5887

/cc @ansis

**Comment by ChrisLoer** [comment]
This should be mostly fixed by https://github.com/mapbox/mapbox-gl-native/pull/10899 when it goes in. #10778 is still an issue but probably not relevant here.

**Comment by tobrun** [comment]
@ChrisLoer thank you for following up, was able to confirm that the issue is resolved with #10899:

![ezgif com-video-to-gif 28](https://user-images.githubusercontent.com/2151639/34815113-75f9aee2-f6b0-11e7-971b-e8a67a0677eb.gif)
