### ISSUE TITLE
Fail to load tile : SLL handcheck

### ISSUE THREAD

**Issue by ganfra** [mapbox/mapbox-gl-native#10557]
Hi, here is my issue 

**Platform: Android**
**Mapbox SDK versions: 5.1.4 and 5.2.0

### Steps to trigger behavior

I have to use a third party tile provider, so I configure MapView like that : 

 ```
<com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/home_map_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:mapbox_styleUrl="@string/custom_style_url"/>
```
I also have in Application onCreate `Mapbox.getInstance(this, getString(R.string.mapbox_token));`

I have noticed the issue on two Android 7.0 devices (Samsung Galaxy S7, Moto G4) , but it's ok on : 
- Android 5.0 (Samsung Galaxy S4)
- Android 6.0 (Moto G2)
- Android 8.0 (Nexus 5x)

This issue results in black screen...
When I change the styleUrl to an official Mapbox one, it does work.
The certificate of the tile provider is ok (and it's working for most of the devices)

Any idea on this ?

Thanks

**Comment by jfirebaugh** [comment]
I assume you mean "SSL handshake" rather than "SLL handcheck". This indicates a networking issue with the tile server, and is therefore something that's out of our control. If you're using third-party tile servers, you'll need to ensure correct SSL support.
