### ISSUE TITLE
Flickering on layer when changing zoom level

### ISSUE THREAD

**Issue by palto-blubek** [mapbox/mapbox-gl-native#10552]
**Platform:** Android
**Mapbox SDK version:** 5.2.0 (but also present on older versions, AFAICT)

### Steps to trigger behavior

- We add a `SymbolLayer` on the map. (`mapboxMap.addLayer(new SymbolLayer(`, etc.)
- All is well, except if we quickly zoom in/out, we see our layer disappearing and reappearing quickly, which produces a kind of flickering (please see video, link below).
- I'm not completely sure, but it looks like this happens when one of the underlying layers shows different information based on the zoom level.  Is it possible that refreshing one layer redraws all the layer above it, thus producing this flickering? 
- If you're unlucky (can't reproduce consistently), you can stop the zoom gesture right when the layer is not visible, and it will stay invisible until the next zoom change! 

Please don't hesitate if you need more information to investigate the issue.

Demonstration video: https://www.dropbox.com/s/pu3dln7zm216tj0/device-2017-11-23-163554.mp4?dl=0

**Comment by kkaefer** [comment]
This is very likely fixed by https://github.com/mapbox/mapbox-gl-native/pull/10436

**Comment by tobrun** [comment]
Confirming that the flickering shown in the video from OP is fixed on master

**Comment by palto-blubek** [comment]
Hi!  I am able to reproduce the issue (or something very similar at least) with 5.2.1
When moving / zooming in/out the symbol randomly disappears.  It is very easy to reprodduce (see video below)

Was the fix supposed to be included in 5.2.1 ?

A video showing the issue on 5.2.1: https://photos.app.goo.gl/jKuCEEhyoDsx2iWl1

**Comment by tobrun** [comment]
This will be fixed with the upcoming 6.0.0 release
