### ISSUE TITLE
Android 5.2.0 tombstone caused by null pointer dereference libmapbox-gl.so

### ISSUE THREAD

**Issue by cmxyzx** [mapbox/mapbox-gl-native#10555]
**Platform:Android**
**Mapbox SDK version:5.2.0**

### Steps to trigger behavior

 1.Integrate Android 5.2.0 SDK
 2.Using Google Android 8.1 Preview device running monkey test
 3.monkey failed with tombstone caused by null pointer dereference in libmapbox-gl.so

### Expected behavior
no tombstone 
### Actual behavior
monkey failed with tombstone caused by null pointer dereference in libmapbox-gl.so

```
Build fingerprint: 'google/bullhead/bullhead:8.1.0/OPP5.170921.005/4373449:user/release-keys'
Revision: 'rev_1.0'
ABI: 'arm'
pid: 10094, tid: 10323, name: GLThread 1179  >>> com.moji.mjweather <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    r0 00000000  r1 00000000  r2 bdeea000  r3 00000000
    r4 c9029e9c  r5 00000000  r6 c9029e8c  r7 bf502728
    r8 00000000  r9 bb0ba000  sl bf502ec0  fp bf502e4c
    ip e981bd58  sp bf502700  lr c883eb1f  pc c883e7b8  cpsr 60030030
    d0  bf28396000000000  d1  bf283180ca99d6a0
    d2  203a657a69732034  d3  73736572706d6f35
    d4  1a8d4991af7d0f5e  d5  f25cfc72fadb5f2b
    d6  bc46cb5f29ad4431  d7  7fe212bfb9bcd687
    d8  0000000000000000  d9  0000000000000000
    d10 0000000000000000  d11 0000000000000000
    d12 0000000000000000  d13 0000000000000000
    d14 0000000000000000  d15 0000000000000000
    d16 3ff0000000000000  d17 0000000000000000
    d18 3d483c0000000000  d19 3ff0000000000000
    d20 3fe63191534fa263  d21 3f625466f5d58108
    d22 3fac6d26eaf61c09  d23 3fcec2cc18c0a733
    d24 3fcc73dfbda3158a  d25 3fc24924920083ff
    d26 3f966f1085ad2216  d27 c84f439400000034
    d28 0000000000000000  d29 0000000000000000
    d30 0000000058109689  d31 00000002c084b448
    scr 28000093

backtrace:
    #00 pc 001cc7b8  /data/app/com.moji.mjweather-kCTufUt8yGHMU_J8dVbB4Q==/lib/arm/libmapbox-gl.so
    #01 pc 00263363  /data/app/com.moji.mjweather-kCTufUt8yGHMU_J8dVbB4Q==/lib/arm/libmapbox-gl.so
    #02 pc 00263297  /data/app/com.moji.mjweather-kCTufUt8yGHMU_J8dVbB4Q==/lib/arm/libmapbox-gl.so
    #03 pc 001d5ead  /data/app/com.moji.mjweather-kCTufUt8yGHMU_J8dVbB4Q==/lib/arm/libmapbox-gl.so
    #04 pc 001d4177  /data/app/com.moji.mjweather-kCTufUt8yGHMU_J8dVbB4Q==/lib/arm/libmapbox-gl.so
    #05 pc 00070dd3  /data/app/com.moji.mjweather-kCTufUt8yGHMU_J8dVbB4Q==/lib/arm/libmapbox-gl.so
    #06 pc 0007271d  /data/app/com.moji.mjweather-kCTufUt8yGHMU_J8dVbB4Q==/lib/arm/libmapbox-gl.so
    #07 pc 00072761  /data/app/com.moji.mjweather-kCTufUt8yGHMU_J8dVbB4Q==/lib/arm/libmapbox-gl.so
    #08 pc 000564bb  /data/app/com.moji.mjweather-kCTufUt8yGHMU_J8dVbB4Q==/oat/arm/base.odex (offset 0x54000)
```

detailed tombstone dump as below:

[tombstone_08.log](https://github.com/mapbox/mapbox-gl-native/files/1501029/tombstone_08.log)
[tombstone_09.log](https://github.com/mapbox/mapbox-gl-native/files/1501030/tombstone_09.log)

**Comment by kkaefer** [comment]
Thank you for reporting this crash. Is it possible to get a symbolicated backtrace for this crash? Otherwise, it'll be impossible for us to debug this. Additionally, do you remember what actions you did to provoke this crash? Does this crash reproduce reliably?

**Comment by cmxyzx** [comment]
1. I'm using the 5.2.0 SDK release aar,  I think the symbols are not published with the release version.
Maybe you shuold try with [ndk-stack](https://developer.android.com/ndk/guides/ndk-stack.html) or addr2line with the symbols on your release build server.
2. I'm not sure what action caused crash. It happens during automatic monkey test. With the random monkey routine the crash can always be reproduced .

**Comment by tobrun** [comment]
@cmxyzx thank you for the report, estimating that this is the same issue as https://github.com/mapbox/mapbox-gl-native/issues/10439 (which is also triggered from using the monkey test).
