### ISSUE TITLE
Plz update Xamarin links to NAXAM's repositories

### ISSUE THREAD

**Issue by tuyen-vuduc** [mapbox/mapbox-gl-native#10561]
Xamarin packages for Mapbox are not updated for a long time.

Working with Mapbox in several projects, we have created the packages ourselves and published on our own repos ([Android](https://github.com/NAXAM/mapbox-android-binding), [iOS](https://github.com/NAXAM/mapbox-ios-binding)).

We also create a repo for Mapbox on Xamarin.Forms [here](https://github.com/NAXAM/mapbox-xamarin-forms).

Plz help to update the links regarding Xamarin, so Xamarin developers could use Mapbox happily :)

Cheers.

**Comment by 1ec5** [comment]
Thanks for writing these libraries! We’d accept a pull request that lists your Xamarin packages alongside the official ones. Please also consider editing [the OpenStreetMap Wiki’s article on Mapbox GL](https://wiki.openstreetmap.org/wiki/Mapbox_GL) to mention your libraries, in case any Xamarin developer finds out about Mapbox through that site.

By the way, would you mind updating each of your libraries’ license files to include [the Mapbox GL license](https://github.com/mapbox/mapbox-gl-native/blob/master/LICENSE.md)? Thank you.
