### ISSUE TITLE
Ubuntu 16 mapbox Android build error

### ISSUE THREAD

**Issue by sdliuxu** [mapbox/mapbox-gl-native#10562]
Platform:Android 
Mapbox SDK version:the latest

My Question is build error.
1.My system is Ubuntu 16.04, on Android Studio 3.0.
2.I use git clone to clone the mapbox-glnative.And when I import the MapboxGLAndroidSDKTestAPP,it accurs an error.The error info as follows:

Error:A problem occurred configuring project ':MapboxGLAndroidSDK'.
> executing external native build for cmake /home/liuxu/work_geocompass/work_project/mapbox-gl-native/CMakeLists.txt

Would you give me some advice to help me solve this error?
Thanks!

**Comment by tobrun** [comment]
@sdliuxu thank you for reporting your problem. First of all, are you sure you want to build this project from source? For most use-case, using the binary, available on maven, is way more easier.

That said, I don't' see any indications that you went through [the installation instructions](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/README.md) of this repo. Feel free to report any issues afterwards but for now I'm going to close this issue.

Fwiw, I'm running this project also on Ubuntu 17 without an issue.
