### ISSUE TITLE
Obtain Features from mapView without rendering it

### ISSUE THREAD

**Issue by Totolik** [mapbox/mapbox-gl-native#10560]
This is feature request (not a bug). It is in iOS SDK (and probably in Android as well). Currently I can obtain list of features at Point or in the Rectangle from MGLMapView. But it only works if MGLMapView was fully rendered and actually attached to window stack. When I try to render it in stand alone Graphics Context - it returns 0 features (whether I'm online or use offline saved Map Pack). It would be really nice (especially for offline use) if I can obtain features from Map View without rendering it. In fact it would even be better if I can obtain features as raw data rather than part of MGLMapView. Data is there anyway - why I need visual representation just for extracting the data? Appreciate if you can include it into future version of iOS SDK (and Android too - I haven't try it yet).

**Comment by jfirebaugh** [comment]
Hi @Totolik -- thanks for the suggestion, but I don't think this is something we're likely to implement in the near future. The SDKs are primarily map rendering SDKs, so we focus on providing feature data only to the extent that it relates to a rendered map. If you want feature data without a rendered map, you're best off loading and querying the data directly.
