### ISSUE TITLE
MGLMapView initWith styleJSON

### ISSUE THREAD

**Issue by robipresotto** [mapbox/mapbox-gl-native#1056]
I load my custom style from web (after download the json from web, the system serializes the data - see below) 

NSData *jsonData = [NSJSONSerialization dataWithJSONObject:responseObject options:NSJSONWritingPrettyPrinted error:&error];
NSString *jsonString = [[NSString alloc] initWithData:jsonData encoding:[NSString defaultCStringEncoding]];

[[MGLMapView alloc] initWithFrame:self.view.bounds accessToken:@"blablabla" styleJSON:jsonString];

The map view works fine in the current view, but if the user goes out and returns to the app the screen turns black.

**Comment by robipresotto** [comment]
if the json file is local, the map view works fine.

[[MGLMapView alloc] initWithFrame:self.view.bounds accessToken:"blablabla" mapBoxAccessToken] bundledStyleNamed:@"customJSON"];

**Comment by incanus** [comment]
Well that's interesting. Same exact style in both methods? Any way you could share it? Private is ok; let's keep the discussion here but feel free to email me `firstname` @mapbox.com.

**Comment by robipresotto** [comment]
exactly the same - can be the encoding system? after the encoding the json sprite url changes to:
"sprite" : "http:\/\/

if you do something like that [jsonString stringByReplacingOccurrencesOfString:@"\\/" withString:@"/"] fix the url string, but maybe something else is missing...

i will write to you tomorrow :)

**Comment by incanus** [comment]
I have your style via email; we'll post more soon.

**Comment by incanus** [comment]
Still haven't had a chance to get to this, but @robipresotto are you still seeing this after the fix in #1077?

**Comment by robipresotto** [comment]
the app crash on

#ifndef _LIBCPP_HAS_NO_RVALUE_REFERENCES
operator=(unique_ptr<_Yp, _Dp>&& __r);
#else // _LIBCPP_HAS_NO_RVALUE_REFERENCES
operator=(unique_ptr<_Yp, _Dp> __r);
#endif

void swap(shared_ptr& __r) _NOEXCEPT;
void reset() _NOEXCEPT;
template<class _Yp>
    typename enable_if
    <
        is_convertible<_Yp*, element_type*>::value,
        void
    >::type
    reset(_Yp* __p);
template<class _Yp, class _Dp>
    typename enable_if
    <
        is_convertible<_Yp*, element_type*>::value,
        void
    >::type
    reset(_Yp* __p, _Dp __d);
template<class _Yp, class _Dp, class _Alloc>
    typename enable_if
    <
        is_convertible<_Yp*, element_type*>::value,
        void
    >::type
    reset(_Yp* __p, _Dp __d, _Alloc __a);

_LIBCPP_INLINE_VISIBILITY
element_type* get() const _NOEXCEPT {return __ptr_;}  <<<<<<<<<<STOP HERE
_LIBCPP_INLINE_VISIBILITY
typename add_lvalue_reference<element_type>::type operator*() const _NOEXCEPT
    {return *__ptr_;}
_LIBCPP_INLINE_VISIBILITY
element_type* operator->() const _NOEXCEPT {return __ptr_;}
_LIBCPP_INLINE_VISIBILITY
long use_count() const _NOEXCEPT {return __cntrl_ ? __cntrl_->use_count() : 0;}
_LIBCPP_INLINE_VISIBILITY
bool unique() const _NOEXCEPT {return use_count() == 1;}
_LIBCPP_INLINE_VISIBILITY
_LIBCPP_EXPLICIT operator bool() const _NOEXCEPT {return get() != 0;}
template <class _Up>
    _LIBCPP_INLINE_VISIBILITY
    bool owner_before(shared_ptr<_Up> const& __p) const
    {return __cntrl_ < __p.__cntrl_;}
template <class _Up>
    _LIBCPP_INLINE_VISIBILITY
    bool owner_before(weak_ptr<_Up> const& __p) const
    {return __cntrl_ < __p.__cntrl_;}
_LIBCPP_INLINE_VISIBILITY
bool
__owner_equivalent(const shared_ptr& __p) const
    {return __cntrl_ == __p.__cntrl_;}

**Comment by 1ec5** [comment]
I’m curious whether #1147 and the style API refactoring therein might’ve fixed this issue.
