### ISSUE TITLE
ISSUE :: Mapbox mapview showing the same view in multiple fragments

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-gl-native#10575]
Hi all,

I am using mapbox mapview in my fragment classes. So the scenario is as follows,

Fragment A having mapview and Fragment B having mapview.

When I add fragment B on Fragment A, so fragment A map are showing/overlapping on fragment B mapview.
What is the issue????

I dont know, how to clear previous map. Any help really appreciate.

**Comment by tobrun** [comment]
@mf-mindcrewtech it's expected when you use the `add` fragment transaction that the previous fragment is still active. You should use `add` only once and afterwards use `replace`. 

That said, this is only a part of the issue. The issue you are seeing is overlapping surfaces, (GL)SurfaceView has a couple of pitfalls and one of those is using overlain surfaces. You can workaround this issue by using TextureView in your second fragment (either by xml `mapbox_renderTextureMode` or using `MapboxMapOptions#textureMode(true)`).

Closing as question is answered, let us know if you have any other issues.
