### ISSUE TITLE
MGLMapView.minimumZoomLevel is not working.

### ISSUE THREAD

**Issue by noramimiyuma** [mapbox/mapbox-gl-native#10591]
**Platform:**
iPhone 7 - iOS 11.1.1

**Mapbox SDK version:**
3.7.0

### Steps to trigger behavior

 1. Run the following code.
```
- (void)viewDidLoad {
    [super viewDidLoad];
    
    MGLMapView *mapView = [[MGLMapView alloc] initWithFrame:CGRectMake(0, 0, 100, 100) styleURL:[MGLStyle satelliteStreetsStyleURL]];
    
    mapView.maximumZoomLevel = 15;
    mapView.minimumZoomLevel = 10;
    
    mapView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    
    // Set the map’s center coordinate and zoom level.
    [mapView setCenterCoordinate:CLLocationCoordinate2DMake(59.31, 18.06)
                       zoomLevel:9
                        animated:NO];
    
    [self.view addSubview:mapView];

}
```

### Expected behavior
`NSLog(@"%@", @(mapView.minimumZoomLevel));` -> 10

### Actual behavior
`NSLog(@"%@", @(mapView.minimumZoomLevel));` -> 0

**Comment by noramimiyuma** [comment]
On the other hand, `mapView.maximumZoomLevel` can be set value correctly.

**Comment by Hugal31** [comment]
I have the same problem with the same version.

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/10596

**Comment by noramimiyuma** [comment]
I found that the setter is not doing anything in SDK.
```
- (void)setMinimumZoomLevel:(double)minimumZoomLevel
{
}

- (double)minimumZoomLevel
{
    return _mbglMap->getMinZoom();
}
```

**Comment by fabian-guerra** [comment]
I fixed that in https://github.com/mapbox/mapbox-gl-native/pull/10596 will be shipped in our next release. I apologize for any inconvenience.

**Comment by noramimiyuma** [comment]
I sincerely appreciate your prompt handling! We are awaiting your next release.
