### ISSUE TITLE
MGLImageSource should support animated GIFs

### ISSUE THREAD

**Issue by asheemmamoowala** [mapbox/mapbox-gl-native#10594]
An `MGLImageSource` pointed to a _gif_ file displays only the first frame of an animated _gif_.

It should animate the gif.

**Comment by 1ec5** [comment]
Same for APNG, another animated image format supported on Apple platforms.

**Comment by jfirebaugh** [comment]
Oof. Can we check if this is feasible in JS before committing to it?

**Comment by jfirebaugh** [comment]
Yep: https://stackoverflow.com/questions/4645274/extracting-single-frames-from-an-animated-gif-to-canvas
