### ISSUE TITLE
How to customize the userLocation annotation.

### ISSUE THREAD

**Issue by ashishke2m** [mapbox/mapbox-gl-native#10601]
Hi,
I am using simple MGLMapView inserted over the UIView.and set the property for the user location.SDK version latest.
I used below code to put a map on a view and want an every location updates in mapView(_ mapView: MGLMapView, didUpdate userLocation: MGLUserLocation?).

//Map setup
        let localMgMapView = MGLMapView(frame: self.view.frame, styleURL: mapStyleurl)
        localMgMapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        
        localMgMapView.delegate=self
        localMgMapView.attributionButton.alpha=0
        localMgMapView.compassView.isHidden=true
        localMgMapView.logoView.isHidden=true
        localMgMapView.showsUserLocation=false
      
        self.view.insertSubview(localMgMapView, at: 0)
I want to hide current location blue bubble to hide and put a custom annotation instead of it for my current Location.is it something possible?

**Comment by fabian-guerra** [comment]
Hi, @ashishke2m. Thank you for using Mapbox. Take a look at:
https://github.com/mapbox/mapbox-gl-native/blob/7e6ca6793a3fe508d4111a11a5887362707ddd26/platform/ios/app/MBXViewController.m#L1724-L1734

**Comment by jmkiley** [comment]
Hi @ashishke2m -

It looks like you may be hiding the Mapbox wordmark and information button that contains attribution information, as well as a telemetry opt-out option for your end-users. 

Per our attribution guidelines, the Mapbox wordmark and information button are required when building with our SDKs. 
 
For more information about our attribution guidelines, see [this guide](https://www.mapbox.com/help/how-attribution-works/). Feel free to [contact support](https://www.mapbox.com/contact/) if you have any questions.

**Comment by ashishke2m** [comment]
@fabian-guerra ,
How i can use this controller with default mapbox sdk.?
