### ISSUE TITLE
queryRenderedFeatures failing for circle layers on a tile boundary

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#10615]
In the sample set up below, when the user taps on the map:

- If we use queryRenderedFeatures to detect the yellow circle layer, everything works as expected (the circle layer is found).
- If we use queryRenderedFeatures to detect the gray circle layer, which is in between a tile boundary, it'll only be detected when tapped on the right side. queryRenderedFeatures will fail with coordinates on the left side of the circle.
- If they gray circle gets moved east (out of the boundary), queryRenderedFeatures works again as expected.

![screenshot_20171201-160431](https://user-images.githubusercontent.com/6964/33503446-c1ccb716-d6b1-11e7-9d85-9849935755b1.png)

cc: @tobrun

**Comment by jfirebaugh** [comment]
Equivalent GL JS issue: https://github.com/mapbox/mapbox-gl-js/issues/5756

**Comment by jfirebaugh** [comment]
In https://github.com/mapbox/mapbox-gl-native/pull/11452, I added ignores for the query tests included https://github.com/mapbox/mapbox-gl-js/pull/6036 that should be removed when this is fixed.
