### ISSUE TITLE
Location marker disappear when orientation changes

### ISSUE THREAD

**Issue by mdakram** [mapbox/mapbox-gl-native#10628]
**Platform:** Android 8.0.0
**Mapbox SDK version:** 5.2.0

### Steps to trigger behavior

 1. Open activity with locationview in portrait mode
 2. Rotate device to landscape
 3. LocationView marker dissapear

### Expected behavior
Location marker should be there as activity recreated

### Actual behavior

Location marker disappears

PS: I checked Location Layer plugin.Its not in state to completely replace LocationView, So sticking with LocationView for now and facing this issue.

**Comment by LukasPaczos** [comment]
Thanks for reaching out and reporting this @mdakram.
I was able to reproduce the issue and found the culprit - we are currently not restoring `MyLocationView` and `MyLocationViewSetting` states after a change, like a screen rotation, occurs.
I'll try to include a fix for this one in the `5.2.2` release.

That said I encourage you to try `LocationLayerPlugin` again. It's been under constant development and we, unfortunately, won't be targeting `MyLocationView` with future updates.

**Comment by kingfisherphuoc** [comment]
I tried `LocationLayerPlugin` now, and it worked. However, if I tilted the map with tracking mode `LocationLayerMode.NAVIGATION`, the my location icon disappeared sometimes as well.
