### ISSUE TITLE
Unable to change Layer's source

### ISSUE THREAD

**Issue by johnnybaloney** [mapbox/mapbox-gl-native#10631]
**Platform:** Android
**Mapbox SDK version:** 5.2.0

### Steps to trigger behavior

Played with a modified [`com.mapbox.mapboxandroiddemo.examples.styles.LineLayerActivity`](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/LineLayerActivity.java):

 1. Create a source (`source1`), a layer (e.g. `circlelayer`), that uses this source, and add to map.
 2. Remove the layer and the source from the map.
 3. Create a new source (`source2`), add to map.
 4. Replace source with the new one using `layer.setSourceLayer("source2");` and re-add the layer to map.

### Expected behavior

The layer is using the new source.

### Actual behavior

Cannot find the source:

```
12-04 21:10:07.626 3317-3375/com.mapbox.mapboxandroiddemo.debug W/mbgl: {GLThread 185}[Render]: can't find source for layer 'circlelayer'
12-04 21:10:07.651 3317-3375/com.mapbox.mapboxandroiddemo.debug W/mbgl: {GLThread 185}[Render]: can't find source for layer 'circlelayer'
12-04 21:10:07.664 3317-3375/com.mapbox.mapboxandroiddemo.debug W/mbgl: {GLThread 185}[Render]: can't find source for layer 'circlelayer'
...
```

**Comment by jfirebaugh** [comment]
Hi @johnnybaloney -- "source" and "source layer" are different things. "Source" refers to the source object from the style, but "source layer" (as set by `setSourceLayer`) refers to the Vector Tile _[layer](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#41-layers)_ within the source.

The source layer can be changed after the style layer is created, but the source can be set only at creation time.

**Comment by johnnybaloney** [comment]
Hi @jfirebaugh, thanks for the explanation. So there is no way to dynamically swap out the source in the layers that come with the style created with Mapbox Studio other than recreating them from scratch, correct?

**Comment by jfirebaugh** [comment]
Yes, that's correct.
