### ISSUE TITLE
"CannotAddLayerException: Invalid index" with index = 0

### ISSUE THREAD

**Issue by ArLabDev** [mapbox/mapbox-gl-native#10634]
Hello, 

I received a number (at the moment more than 350) of crashes of my Android App with the Exception 
"Exception com.mapbox.mapboxsdk.style.layers.CannotAddLayerException: Invalid index" during a call to addLayerAt method.
I was not able to reproduce the problem myself.

I use the android java wrapper of the library
	com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.3

and, in the case of the crash, I use a custom (JSON) style for the map.
([no_layer_map.json.txt](https://github.com/mapbox/mapbox-gl-native/files/1530928/no_layer_map.json.txt))

The crash happened on all Android API supported by my App and on large different types of devices

in onMapready I call addLayerAt method with 0 index parameter.

```
    public void onMapReady(MapboxMap mapboxMap)
    {
		...
		
        if( mapLayerSource != null )
        {
            // Be sure Style URl is custom if selected LayerSource (not really needed, because already done)
            if( cMapboxStyle_Custom.compareTo( mMapBoxMap.getStyleUrl() ) != 0 )
                mMapBoxMap.setStyleUrl( cMapboxStyle_Custom );
            mMapBoxMap.clear();
            mMapBoxMap.removeLayer( "web-map-layer" );
            mMapBoxMap.addLayerAt( new RasterLayer("web-map-layer", mapLayerSource ), 0 );		<---- Exception
        }
		
		...
	}

```

I've looked into native code and the check that raises the "invalid index" exception should be this:

```
    int numLayers = layers.size() - 1;
    if (index > numLayers || index < 0) {
        Log::Error(Event::JNI, "Index out of range: %i", index);
        jni::ThrowNew(env, jni::FindClass(env, "com/mapbox/mapboxsdk/style/layers/CannotAddLayerException"),
            std::string("Invalid index").c_str());
        return;
    }
```

so it should always pass if layer index is "0"

Anyway, the stacks reports only the java part and it seems not so usefull:

com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddLayerAt (NativeMapView.java)
com.mapbox.mapboxsdk.maps.NativeMapView.addLayerAt (NativeMapView.java:752)
com.mapbox.mapboxsdk.maps.MapboxMap.addLayerAt (MapboxMap.java:332)
com.arlabsmobile.altimeter.MapsFragment.onMapReady (MapsFragment.java:1948)
com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady (MapView.java:945)
com.mapbox.mapboxsdk.maps.MapView$MapCallback.access$1000 (MapView.java:910)
com.mapbox.mapboxsdk.maps.MapView$MapCallback$1.run (MapView.java:928)
android.os.Handler.handleCallback (Handler.java:739)

**Comment by tobrun** [comment]
@ArLabDev thank you for reaching out, the issue that you are seeing is related to loading a style and at the same time trying to manipulate the style layers. 

Add the following to be sure the style is fully loaded:

```java
mapboxMap.setStyleUrl(style, new MapboxMap.OnStyleLoadedListener() {
            @Override
            public void onStyleLoaded(String style) {
              Timber.d("Style loaded %s", style);
              // add map manipulations here
            }
          });
```

That said, if this is only for loading 1 style. You should try adding your style url before calling getMapAsync. This can be done either through xml attributes, mapboxMapOptions#styleUrl() or MapView#setStyleUrl(). The onMapReady callback will later be invoked when that style has finished loading.

**Comment by ArLabDev** [comment]
@tobrun Thankyou for the answer.

In fact I call
                mMapBoxView.setStyleUrl( cMapboxStyle_Custom );
before then
                mMapBoxView.getMapAsync( this );
As you suggested.

The 
     mMapBoxMap.setStyleUrl( cMapboxStyle_Custom );
in the onMapReady is an attempt to fix a problem and is done only if not already set.
As I now know it is not enough to call it synchronously, but I need to wait for the callback.

Thanks
