### ISSUE TITLE
Android Things Map

### ISSUE THREAD

**Issue by electrostat** [mapbox/mapbox-gl-native#10630]
**Platform:** Android Things 0.6-devpreview on [NXP Pico i.MX7D ](https://developer.android.com/things/hardware/imx7d.html)
**Mapbox SDK version:** 5.2

Attempted to get the Android maps sdk running on Android Things and hit a few snags. When loading the map, `eglChooseConfig()` fails and the application crashes. This occurs even after setting the `mapbox_renderTextureMode="true"`.  

Are there any solutions to get around this limitation I'm running into? 

The hardware has a 1 GHz ARM A7 processor, with 512 MB of RAM, and an integrated graphics chip.

**Comment by Guardiola31337** [comment]
Tested with the latest Mapbox SDK version `5.2.1` and it's working (with and without `TextureView`) 👀

![Maps on Android Things](https://user-images.githubusercontent.com/1668582/33799386-d0250e56-dd2a-11e7-965e-24d8518d4c6e.jpg)

Closing.
