### ISSUE TITLE
How to get an icon name missing from sprite?

### ISSUE THREAD

**Issue by rinigus** [mapbox/mapbox-gl-native#10645]
When designing styles, its easy to miss an icon in sprite. Is there any debug flag or environment variable that would print the missing requested icon on stderr, for example?

**Comment by kkaefer** [comment]
This isn't supported right now, but a patch could be as straightforward as:

```diff
diff --git a/src/mbgl/renderer/image_manager.cpp b/src/mbgl/renderer/image_manager.cpp
index 2ef6be0c4..267460118 100644
--- a/src/mbgl/renderer/image_manager.cpp
+++ b/src/mbgl/renderer/image_manager.cpp
@@ -90,6 +90,8 @@ void ImageManager::notify(ImageRequestor& requestor, const ImageRequestPair& pai
         auto it = images.find(dependency);
         if (it != images.end()) {
             response.emplace(*it);
+        } else {
+            Log::Warning(Event::Image, "ImageManager: image '%s' is missing", dependency.c_str());
         }
     }
 
```

**Comment by rinigus** [comment]
Great! Any plans to add that? I wonder how many of us, Mapbox GL users, have no clue what's going on with missing items on the map...

**Comment by jfirebaugh** [comment]
IIRC, we actually had that at one point, but people complained about it so we removed it.

**Comment by rinigus** [comment]
I see. It's probably as annoying for those who have no control over tile data and style as useful for those who design them. What about compile-time switch? I would compale it enabled on desktop and leave it out for mobile users...

**Comment by rinigus** [comment]
For now, I can just use this patch in my own compilation and it would be sufficient for me. In this sense, we can probably close the issue and have it around for documentation purposes. Would that be OK?

**Comment by rinigus** [comment]
Closing since there are no objections
