### ISSUE TITLE
Make validation of demo app a CI job

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-gl-native#10657]
The demo app added in https://github.com/mapbox/mapbox-gl-native/pull/10524 is now highlighted in our install flow and it looks like it may continue to be for some time:

![screen shot 2017-12-07 at 3 42 57 pm](https://user-images.githubusercontent.com/63186/33744346-afcda986-db65-11e7-94a5-d98a3f626d58.png)

As noted in https://github.com/mapbox/mapbox-gl-native/pull/10524#pullrequestreview-78254419, we should rewire things so that the demo app is validated as part of the regular CI process to help ensure it is working and can always be included in the published build output.

cc @Lndsay @lilykaiser

**Comment by friedbunny** [comment]
Noting that the demo app broke sometime around the `ios-v4.0.0` release and isn’t currently packaged with the SDK downloads.
