### ISSUE TITLE
Symbol visibility warnings in core expressions code

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#10656]
iOS builds on master ([such as this one](https://circleci.com/gh/mapbox/mapbox-gl-native/46773), as of ca9d9bb85733f8127154cf34cb61e871fee91bdf) are currently showing a bushel of similar warnings in newly added expressions code about how, “direct access in [function] to global weak symbol [symbol] means the weak symbol cannot be overridden at runtime”:

> ⚠️ ld: direct access in function `mbgl::style::expression::ArrayAssertion::operator==(mbgl::style::expression::Expression const&) const` from file '/Users/distiller/project/build/ios/Debug-iphonesimulator/libmbgl-core.a(array_assertion.o)' to global weak symbol `typeinfo for mbgl::style::expression::Expression` from file '/Users/distiller/project/build/ios/ios.build/Debug-iphonesimulator/test.build/Objects-normal/x86_64/MGLFillStyleLayerTests.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

/cc @anandthakker @1ec5

**Comment by 1ec5** [comment]
> a bushel of similar warnings

![](https://upload.wikimedia.org/wikipedia/commons/3/3e/Bushel_Table_of_States.jpg)
