### ISSUE TITLE
[ios,android] Implement local ideographic glyph generation for MapSnapshotter

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native#10665]
#10522 introduces support for local generation of ideographic glyphs. For maps that use lots of CJK glyphs, this can lead to a dramatic reduction in data usage. The Android and iOS implementations of `MapSnapshotter` don't currently take advantage of this setting, so for a CJK user using the local override, a map might load with 1MB worth of data, but taking a snapshot of that map might require downloading an extra 10MB of glyph data.

`HeadlessFrontend` already supports a `localFontFamily` argument, so the only change to portable code required here is to pass that argument through the `MapSnapshotter` constructor.

The Android implementation will need to expose an appropriate option to the Java `MapSnapshotter` class. The iOS implementation may take advantage of the existing `MGLIdeographicFontFamily` setting in `Info.plist`.

**Comment by zugaldia** [comment]
`MapSnapshotter` is actively used with maps that use CJK glyphs, I understand this is an improvement we still want to do. Tagging @chloekraw for confirmation and prioritization.

**Comment by chriswu42** [comment]
@ChrisLoer can you verify that [this work is now completed?](https://github.com/mapbox/mapbox-gl-native/pull/13427)

**Comment by ChrisLoer** [comment]
Yup, we just fixed this with https://github.com/mapbox/mapbox-gl-native/pull/13427, we just forgot about the tracking issue!
