### ISSUE TITLE
Difference in location accuracy between v4 and v9/v10 maps

### ISSUE THREAD

**Issue by yashiro32** [mapbox/mapbox-gl-native#10667]
There is an offset of location of tens of meters in the v9/v10 maps when i used the SDK. Ironically when I used the v4 maps through the APIs the map it returns is much closer to my actual physical location and the location shown on Google Map.

**Comment by kkaefer** [comment]
Thanks for using Mapbox. Unfortunately, we are unable to diagnose this issue without further information. Please provide a small example and describe what you're doing, what you expect to see, and what's happening instead.

**Comment by yashiro32** [comment]
For example, take this latitude and longitude: 1.31083, 103.7502. The v4 map generated is much closer to the map google generated than the v9/v10 map.

The center of the map is the lat, lon that you pass in as parameters right ?

**Comment by kkaefer** [comment]
Hm, can you please elaborate what you mean with v4 map and v9/10 map?

**Comment by yashiro32** [comment]
v4 map:
https://api.mapbox.com/v4/mapbox.emerald

v9/v10 maps:
mapbox://styles/mapbox/light-v9
mapbox://styles/mapbox/streets-v10

**Comment by jfirebaugh** [comment]
streets-v10:

![image](https://user-images.githubusercontent.com/98601/40254635-1c66622e-5a99-11e8-825a-34a03828daae.png)

mapbox.emerald:

![image](https://user-images.githubusercontent.com/98601/40254654-2d22abd6-5a99-11e8-9c28-060297d4cc3f.png)

The visual style is different, but the data is identical.
