### ISSUE TITLE
Update to Mapbox Java 3.0

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#10663]
We've been updating Mapbox Java to 3.0 with some pretty significant changes such as immutable GeoJSON objects and the removal of `Position` in favor of `Point` exclusively. With the next version of the Map SDK being 6.0, we should start planning on integrating these changes so we have time to fix any issues we might encounter. 

There's a hand full of dependencies currently published, the only one the Map SDK relies on is the GeoJSON module.

cc: @mapbox/android

**Comment by zugaldia** [comment]
Noting that we've already published `3.0.0-beta.1` for MAS so we can already start working on testing the integration. We'll need a MAS final release before Maps SDK 6.0.0 final though.

**Comment by tobrun** [comment]
this landed in #10920
