### ISSUE TITLE
Broken polygon rendering

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-native#1067]
Hello,

the native iOS client seem to have issues rendering certain polygons. We can't really identify why or under which circumstances it triggers, but it is a bug not found in the web client. Here are some screenshots, description below.

![ios simulator screen shot 20 mar 2015 18 00 35](https://cloud.githubusercontent.com/assets/5638107/6784317/4cca4e54-d17f-11e4-854f-e57176f92023.png)
![screenshot 2015-03-23 17 03 40](https://cloud.githubusercontent.com/assets/5638107/6784320/4ccf9896-d17f-11e4-8fbc-d8259a2bb9a6.png)

![ios simulator screen shot 20 mar 2015 18 01 15](https://cloud.githubusercontent.com/assets/5638107/6784318/4ccc0910-d17f-11e4-9ab5-4e717f6eeb26.png)
![screenshot 2015-03-23 17 03 09](https://cloud.githubusercontent.com/assets/5638107/6784319/4ccdd6be-d17f-11e4-981b-b3e7f31da086.png)

The red layer is our land-layer from a custom data source. The data is initially stored in a postGIS db, and validated with ST_IsValid. 

The poly should cover all the brown areas, which is the map background color. The first screenshot in each pair is from the native client, the other is from the web client covering the same location. Style and source is identical.

As you can see, a lot of red polys are missing in the native client. The web client has no issues rendering these polys.

The straight lines that cut through large polys are cutting lines in the custom dataset, which leads us to believe that the iOS client is dropping certain polys all together.

We don't have more information than this to go on, we'll start experimenting with various preprocessing steps such as cutting and merging the polys before building the pbf-tiles.

The data is custom, but we'll be more than happy to provide pbf samples, styles and postGIS db-extracts in private.

**Comment by kristfal** [comment]
Update, managed to find a workaround.

The initial data is "tiled" like this:

![mapbox data](https://cloud.githubusercontent.com/assets/5638107/6846925/8aad3dd6-d3c2-11e4-8f67-97c5e533e545.JPG)

Which in turn causes the native client to completely drop rendering certain polygons: 

![unnamed](https://cloud.githubusercontent.com/assets/5638107/6846933/98aa8812-d3c2-11e4-9d6a-758f9d2374d6.png)

We then meged the polygons to a single multipolygon before exporting to mbtiles:

![mapbox data merged](https://cloud.githubusercontent.com/assets/5638107/6846970/fd183056-d3c2-11e4-88d0-cd22e065e037.JPG)

Which in turn led to proper rendering:

![db](https://cloud.githubusercontent.com/assets/5638107/6846984/08a86b84-d3c3-11e4-8552-ce510a1e3ccb.png)


The layer contains only geometry, no attributes fields are passed through the MBS export in either case, so it seems like a pure geometry issue. We can share both sources if you need debug material. Again, the js-client has no issues rendering either data source.

**Comment by kkaefer** [comment]
I'd be interested in the sample material. Can you please send them to konstantin (at) mapbox.com? The JS renderer uses different approach to polygon rendering which doesn't involve tessellation. However, that will change soon since rendering is faster with properly tessellated polygons.

**Comment by kristfal** [comment]
@kkaefer We fixed this in the data by running ST_ForceRHR on the polys. That should probably narrow your search ;)

**Comment by jfirebaugh** [comment]
Yes, RHR is required. Tracking this upstream in https://github.com/mapbox/vector-tile-spec/issues/18 and https://github.com/mapbox/mapnik-vector-tile/issues/59.
