### ISSUE TITLE
PingFang font isn’t available on iOS 8

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#10675]
After #10522 and #10662, we hard-code the PingFang font and suggest its use — this will fail on iOS 8, because it wasn’t introduced until iOS 9 (alongside the SF system font).

For Chinese system fonts on iOS, Heiti SC/TC were the predecessors to PingFang SC/TC/HK.

/cc @ChrisLoer @akitchen

**Comment by ChrisLoer** [comment]
Happy to change the example in the comments to whatever we think is best, but I'm not sure Heiti is obviously better? In the case iOS can't load what you requested, it has font fallback behavior (full disclosure: I don't know how the fallback behavior works, I've just seen it while testing). So for instance I tried changing the "PingFang" test to the definitely-not-installed-on-my-system "HurgleBurgle" and it still renders a reasonable-looking result:

![actual](https://user-images.githubusercontent.com/375121/33861808-9887b8f2-de94-11e7-8058-2dcc0f36616c.png)

There's no place other than that unit test where "PingFang" is hard coded.

/cc @1ec5

**Comment by akitchen** [comment]
I set breakpoints inside the core classes to spot-check the data flowing thru while working on the ObjC wrapper and saw iOS decide to use Helvetica when a bogus or non-existent font was specified. It could be worth doing this again for iOS 8 if we're worried about it, but I suspect it might just work ™

**Comment by 1ec5** [comment]
iOS does implement font fallback. I also wondered in https://github.com/mapbox/mapbox-gl-native/pull/10522#discussion_r155863098 whether `PingFang` also fell back to SF Text on newer systems, because the PostScript font names are actually `PingFangHK`, `PingFangSC`, and `PingFangTC`, not simply `PingFang`.

**Comment by friedbunny** [comment]
Hrm, so it sounds like it would be useful to better understand and then document the fallback behavior. This all makes me wonder if not specifying any font and allowing the system to choose wouldn’t produce a better result on iOS.

For instance, if the developer specifies `PingFang` and we use it to render the entire CJK range, but the user is looking at Japanese text, this would result in a worse visual experience (because iOS has the Hiragino fonts for Japanese and PingFang does a poor job with non-Chinese characters).

To @1ec5’s point, this is also a concern with simply `PingFang` — is it rendering Simplified, Traditional, or Hong Kong Chinese glyphs? I’m deeply unfamiliar with the Chinese unicode range(s), but it would be good to (re-)confirm that we’re showing the correct characters with the best typeface in each situation. [This article](https://people.w3.org/rishida/scripts/chinese/) indicates that some characters share the same code point but should be rendered differently at the font-level.

**Comment by akitchen** [comment]
Where would be the most appropriate place to document this? In the Info.plist key documentation?

**Comment by friedbunny** [comment]
@akitchen Yeah, I suppose that’d be the only place iOS developers would end up seeing it.
