### ISSUE TITLE
Question about Source/Layer API

### ISSUE THREAD

**Issue by ganfra** [mapbox/mapbox-gl-native#10673]
Hi,
I'm using the source and layer API to draw a large amount of symbol on the map (around 15 000) .
This process can take around 1 or 2 seconds to finish after setting the FeatureCollection.

Then, I would like to know when the symbols are actually ready (but maybe not rendered, because not in the box, or because of zoom level)
Is there some callback to do so ?

Thanks

**Comment by kkaefer** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
