### ISSUE TITLE
How to make polygon/polyline at the top of the map

### ISSUE THREAD

**Issue by StannyBing** [mapbox/mapbox-gl-native#10680]
**Platform:Android
**Mapbox SDK version:5.0.2

### Steps to trigger behavior

 1.init map
 2.addLayer
 3.addPolygon/addPolyline

or
 1.init map
 2.addPolygon/addPolyline
 3.addLayer
4.polygon/polyline update

### Expected behavior
polygon/polyline at the top of the map

### Actual behavior
The polygon is under the layer

How to keep the polygon at the top, or to change its position dynamically。
If use api can't be implemented, can you tell me how to implement it by changing the source code, I've built the source code environment。
thank you again！

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
