### ISSUE TITLE
[Qt] Network access limits connection to localhost in some Qt platforms

### ISSUE THREAD

**Issue by rinigus** [mapbox/mapbox-gl-native#10686]
I am writing my findings over here in a hope that they maybe useful for someone hitting the same issue.

Platform: Sailfish OS (Linux, Qt 5.6, ARM), mobile

I am running map application based on Mapbox GL Native QML bindings that fetches the data and style either from online providers (such as Mapbox) or a map tile server running on localhost (OSM Scout Server). It all works fine with all servers when the network access is either via cellular or WiFi connection. 

When users switch off cellular and wifi network interfaces, connection even to localhost by Mapbox GL Native client is failing with  "Network access is disabled" message. Note that its even sufficient to have non-working network interface switched on (like non-configured WiFi) to get around this access issue.

Similar issues has been reported earlier for Qt at different conditions, with https://bugreports.qt.io/browse/QTBUG-59219 and its fix https://codereview.qt-project.org/#/c/202192/ the closest. Since I cannot change / patch Qt easily on my phone, the simplest solution was to compile qmapboxgl version that would use libcurl for network access by dropping 

```
platform/qt/src/http_file_source.cpp
platform/qt/src/http_request.cpp
platform/qt/src/http_file_source.hpp
platform/qt/src/http_request.hpp
```

and adding

```
platform/default/http_file_source.cpp
```
in the build pro-file.

I am going to close this issue, since its not really a problem of Mapbox GL Native, but underlying platform (Qt).

/cc @tmpsantos @brunoabinader

**Comment by rinigus** [comment]
Closing the issue, as stated earlier

**Comment by kkaefer** [comment]
Thanks for documenting this here!
