### ISSUE TITLE
Why FillLayer change shape when zooming

### ISSUE THREAD

**Issue by StannyBing** [mapbox/mapbox-gl-native#10683]
**Platform:Android
**Mapbox SDK version:5.0.2

### Steps to trigger behavior

 1.add a FillLayer with GeoJsonSource
 2.zoom the mapview
 3.the FillLayer will change shape

### Expected behavior
the FillLayer will change shape
### Actual behavior
No change

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. It's not clear from your description what the issue is. Could you please attach screenshots or code sample that shows the issue?

**Comment by StannyBing** [comment]
Thank you for your reply。
I'll give you some screenshots and some code。
This is before zooming
![1](https://user-images.githubusercontent.com/23026258/33980998-1c0cd90c-e0e6-11e7-9e3c-6701719365be.png)
This is after zooming
![2](https://user-images.githubusercontent.com/23026258/33981129-920dc83c-e0e6-11e7-9254-707ea41c57a3.png)
![2017-12-14-16-09-31](https://user-images.githubusercontent.com/23026258/33981921-a2d8ae18-e0e9-11e7-94ff-32f679165ce0.gif)
This is my code
![qq 20171214161349](https://user-images.githubusercontent.com/23026258/33981963-cc1a470a-e0e9-11e7-8d8f-dcc6f0ba8101.png)
The problem is so serious that I can't continue my work and hope to get your help.
Thank you，again.

**Comment by StannyBing** [comment]
Hello，I've solved this problem, but I think it's a bug
I found if I create a FillLayer by adding point way,This problem will appear
But if I create a FillLayer by queryRenderedFeature，This problem will not appear
So I check the json of Feature，I found the Coordinates in this json of the way by queryRenderedFeature，it has one more Coordinates  than another way what  adding point .
and i had test if i add more point ，Surprisingly, the mistake is gone！
It mean ：
if i add point1，point2, point3，point4，to create a Feature，to create a FillLayer, It will go wrong
but if i add point1，point2，point3，point4，point1，to create a Feature，to create a FillLayer, it will be normal
Do you notice it？
i had add the begin point twice。
I think it's OpenGl‘s bug。
so i inquiry the Source code of queryRenderedFeature。
i found there are some code  in render_layer.cpp
when query feature,you had add the begin Point of query layer.
so
 i think you need solved this bug,when add filllayer ,thank you again!

**Comment by kkaefer** [comment]
Thanks for your observations. It is indeed correct that you'll have to specify point1 again. [Section 3.1.6 of the GeoJSON spec](https://tools.ietf.org/html/rfc7946#section-3.1.6) talks about requirements to linear rings which make up polygons:

> The first and last positions are equivalent, and they MUST contain identical values; their representation SHOULD also be identical.

This is a requirement for GeoJSON itself, so when setting the initial feature, you must duplicate this point.

**Comment by jfirebaugh** [comment]
You must also specify a polygon that is free of self intersections. Your polygon has multiple self-intersections.
