### ISSUE TITLE
Standardize on an NSString encoding

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1068]
Several `MGLMapView` methods make use of `+[NSString defaultCStringEncoding]` when converting between `NSString` and `std::string`. The [`+defaultCStringEncoding` documentation](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSString_Class/#//apple_ref/occ/clm/NSString/defaultCStringEncoding) makes clear that we should consider it a last resort. Relying on it could lead to weird bugs that depend on the system language (especially with right-to-left languages). We should standardize on `NSUTF8StringEncoding`.

**Comment by robipresotto** [comment]
:+1:

**Comment by incanus** [comment]
Good move. This was my bad; let's correct to UTF8.

**Comment by 1ec5** [comment]
FYI we also need this for consistency with the string boxed expressions we’re using throughout (`@("")`), which [assume UTF-8](http://clang.llvm.org/docs/ObjectiveCLiterals.html).
