### ISSUE TITLE
Layers are removed after updating Map style

### ISSUE THREAD

**Issue by Dhvl-Golakiya** [mapbox/mapbox-gl-native#10697]
Hi,

I am using Mapbox with Fusetools. I am adding multiple layers on a map and they are displayed perfectly. But when I change map style, all previously added layers are removed.

Code for changing map style in iOS:

`
            self.mapView.styleURL = [[NSURL alloc] initWithString:mapStyle];`

And for Android:
`mapboxMap.setStyleUrl(mapStyle);`

Should changing map style affect all added layers? Should I need to add layer again?

**Comment by jmkiley** [comment]
Hi @Dhvl-Golakiya -

When you call `addLayer` or `addSource`, you are adding that source or layer to your map's current style, not to the map directly. Therefore, you need to add any styles and sources to your new style after that style has finished loading. We are [discussing](https://github.com/mapbox/mapbox-gl-native/issues/6180) allowing sources and layers to persist after a style change, but do not have a timeline for that feature. See https://github.com/mapbox/mapbox-gl-native/issues/6180 for discussions about workarounds.
