### ISSUE TITLE
Flicker when dragging MGLAnnotationView and tapping screen

### ISSUE THREAD

**Issue by arthurhammer** [mapbox/mapbox-gl-native#10709]
**Platform:** iOS
**Mapbox SDK version:** 3.7.1

When dragging a draggable `MGLAnnotationView` and tapping the screen with another finger, the view flickers back to its starting location.

### Steps to trigger behavior

 1. Create a draggable annotation view
 2. Start dragging 
 3. Touch the screen with a second finger

### Expected behavior

The drag continues smoothly.

### Actual behavior

The annotation view jumps back to its drag starting location. When the drag continues the view jumps to its current dragging point.

---

I have tried disabling and even removing all map gesture recognizers prior to the drag but this does not seem to be the source of the issue.

![ezgif com-resize](https://user-images.githubusercontent.com/4521216/34057040-bf39de28-e1d5-11e7-9cef-8a86cc3cf204.gif)

**Comment by jmkiley** [comment]
The most reliable way that I have found to repro this jump is to:
1. Drag the annotation away from its original position.
2. Long press on the annotation with one finger, so the annotation is no longer being dragged.
3. Tap with a second finger.
