### ISSUE TITLE
Stringify expressions

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#10714]
mbgl should have a mechanism for converting an `mbgl::style::expression::Expression` to a JSON structure or string. Perhaps it could live in stringify.hpp. This would be useful for implementing the style property getters on iOS/macOS for #8074: instead of working with the specialized C++ types, the getter code could transform JSON-like structures, just as the setter code produces JSON-like structures via a converter.

/ref #7563
/cc @anandthakker

**Comment by 1ec5** [comment]
This mechanism or one that converts to `mbgl::Value` would also enable the SDKs to expose alternative setters and getters in JSON format. Studio just added an “Edit property as JSON” option that these setters and getters could tie into, and React Native Mapbox GL would also benefit from not having to reverse-engineer the native SDKs’ expression APIs.

On the iOS/macOS side, we’re still going to prefer the NSExpression syntax, as it would require far fewer `@`s in code, but an `+[NSExpression mgl_expressionForJSONObject:]` and `-[NSExpression mgl_jsonObject]` would be a sensible alternative for certain workflows.

/cc @nitaliano @davidtheclark

**Comment by anandthakker** [comment]
👍 this shouldn't be too hard to add.

> Perhaps it could live in stringify.hpp

Might be easier for this to be a member function on each `mbgl::style::expression::Expression` subclass.

**Comment by ChrisLoer** [comment]
Implemented in #11156.

**Comment by nitaliano** [comment]
@ChrisLoer @1ec5 so will this be exposed in the Android/iOS SDK so from react native I can just send a JSON blob?

**Comment by ChrisLoer** [comment]
I'm not sure on the Android side -- do you know how we'll expose it @tobrun? On the iOS side there is currently `MGLJSONObjectFromMBGLExpression`, which @1ec5 plans to re-implement as a thin wrapper on this functionality. I take it `react-native-mapbox-gl` is implemented on top of the iOS/Android SDK interface so it can't call directly into `mbgl-core` code?

**Comment by nitaliano** [comment]
yes that is correct

**Comment by 1ec5** [comment]
@nitaliano, as of #11072, the iOS map SDK already exposes [two methods](https://github.com/mapbox/mapbox-gl-native/blob/374bad18c04ae8fea574f85d2149af8aeffb8dcc/platform/darwin/src/NSExpression%2BMGLAdditions.h#L14-L43) for roundtripping between NSExpression and JSON-style Foundation objects (like NSArray). The `MGLJSONObjectFromMBGLExpression()` refactoring mentioned above plus [these issues](https://github.com/mapbox/mapbox-gl-native/issues?q=is%3Aissue+is%3Aopen+expression+author%3A1ec5+milestone%3Aios-v4.0.0) will fix a number of roundtripping bugs, but there are no plans to allow e.g. `MGLSymbolStyleLayer.text` to be set to a JSON object directly, since the paint and layout properties are declared with the type NSExpression.

**Comment by tobrun** [comment]
@nitaliano 

### Input
https://github.com/mapbox/mapbox-gl-native/issues/11158 was ticketed out to support that use-case.

### Output
You can use Expression.toString() that will generate a json string that is compliant to the syntax form the style spec.

eg.
```java
  @Test
  public void testExpressionMinToString() throws Exception {
    String expected = "[\"min\", 0, 1, 2, 3]";
    String actual = min(0, 1, 2, 3).toString();
    assertEquals("toString should match", expected, actual);
  }
```

Note that I'm still working on the getters support for this in #10721
