### ISSUE TITLE
Add expression filter support

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#10720]
Tailwork of expression integration in #10654. Capturing from https://github.com/mapbox/mapbox-gl-native/pull/10654#issuecomment-351176411 that expression support for core needs to be implemented first.

**Comment by 1ec5** [comment]
Per https://github.com/mapbox/mapbox-gl-native/issues/7978#issuecomment-355240792, this task includes adding a `getFilter()` accessor to `Layer`.

**Comment by anandthakker** [comment]
Outline of an implementation approach:
1. Allow expressions to be used as filters:
  a. Add an `ExpressionFilter` type to [include/mbgl/style/filter.hpp](https://github.com/mapbox/mapbox-gl-native/blob/671dfefc1e3fff5038a6d9cedc78daabffa5597f/include/mbgl/style/filter.hpp) that holds an `mbgl::style::Expression` object (of type `mbgl::style::expression::type::Boolean`)
  b. Add a corresponding overload for [`mbgl::style::FilterEvaluator`](https://github.com/mapbox/mapbox-gl-native/blob/671dfefc1e3fff5038a6d9cedc78daabffa5597f/include/mbgl/style/filter_evaluator.hpp)
  c. In [src/mbgl/style/conversion/filter.cpp](https://github.com/mapbox/mapbox-gl-native/blob/671dfefc1e3fff5038a6d9cedc78daabffa5597f/src/mbgl/style/conversion/filter.cpp), add a port of [isExpressionFilter](https://github.com/mapbox/mapbox-gl-js/blob/063fdebeaffbf6bc3ffff32233ed6248f42f3c59/src/style-spec/feature_filter/index.js#L11-L45) and use it to decide in [`Converter<Filter>::operator()`](https://github.com/mapbox/mapbox-gl-native/blob/671dfefc1e3fff5038a6d9cedc78daabffa5597f/src/mbgl/style/conversion/filter.cpp#L202) whether to parse the incoming JSON as an `ExpressionFilter` or one of the legacy filter types.
2. Convert "legacy" filters directly into expressions.
  a. Port the [specialized `filter-*` expressions](https://github.com/mapbox/mapbox-gl-js/blob/063fdebeaffbf6bc3ffff32233ed6248f42f3c59/src/style-spec/expression/definitions/index.js#L332-L450) from GL JS, adding them to [src/mbgl/style/expression/compound_expression.cpp](https://github.com/mapbox/mapbox-gl-native/blob/671dfefc1e3fff5038a6d9cedc78daabffa5597f/src/mbgl/style/expression/compound_expression.cpp#L386).
  b. Update [src/mbgl/style/conversion/filter.cpp](https://github.com/mapbox/mapbox-gl-native/blob/671dfefc1e3fff5038a6d9cedc78daabffa5597f/src/mbgl/style/conversion/filter.cpp) to _always_ convert incoming JSON values to an `ExpressionFilter` (using the `filter-*` types as needed for legacy syntax)
  c. Rewrite/simplify [include/mbgl/style/filter.hpp](https://github.com/mapbox/mapbox-gl-native/blob/671dfefc1e3fff5038a6d9cedc78daabffa5597f/include/mbgl/style/filter.hpp) and [`mbgl::style::FilterEvaluator`](https://github.com/mapbox/mapbox-gl-native/blob/671dfefc1e3fff5038a6d9cedc78daabffa5597f/include/mbgl/style/filter_evaluator.hpp), removing all the different `*Filter` types and the `Filter` variant and renaming `ExpressionFilter` to `Filter`.

**Comment by 1ec5** [comment]
Once the core changes in https://github.com/mapbox/mapbox-gl-native/issues/10720#issuecomment-363476243 are complete, we can remove the `FilterEvaluator` from [NSExpression+MGLAdditions.mm](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/NSExpression+MGLAdditions.mm) and round out a few remaining NSPredicate-specific operators for #11013.
