### ISSUE TITLE
Improve darwin localization process and tests

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#10739]
The darwin localization process isn’t well understood by the team and the technical correctness of our localizations is not currently tested. We should:

- Streamline the localization scripts so that they work reliably on everyone’s computers.
- Improve docs and awareness of when/how to localize, update localizations, etc.
- Test formatting and existence of localizations on CI.

Refs #10731.

/cc @mapbox/ios

**Comment by 1ec5** [comment]
> Streamline the localization scripts so that they work reliably on everyone’s computers.

@fabian-guerra, do you remember what problems you ran into with `make genstrings`? I haven’t run into any problems with it myself, but it would be dependent on the Xcode toolchain etc.

> Improve docs and awareness of when/how to localize, update localizations, etc.

Currently, this documentation lives in DEVELOPING.md ([iOS](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md#adding-user-facing-text), [macOS](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/macos/DEVELOPING.md#adding-user-facing-text)). I’m sure the documentation could be beefed up, for example with screenshots or troubleshooting advice.

> Test formatting and existence of localizations on CI.

Xcode’s static analyzer produces localizability warnings that we could fail a build on. In #1549, we originally ran into difficulties analyzing the iOS SDK on Bitrise, but that was during the GYP days. We’re probably in a much better position to analyze the project, though build times are always a concern when enabling static analysis.
