### ISSUE TITLE
Mark deprecated methods as unavailable

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#10735]
The upcoming iOS map SDK release is a major release with backwards-incompatible changes. During the course of the iOS map SDK’s v3.x release series, we’ve marked 29 methods with the `deprecated` attribute, with the expectation that they’d be removed when v4.0.0 comes around, so now’s our chance. Twenty of these methods are shared with the macOS map SDK; since that SDK hasn’t reached v1.0 yet, the removal of these methods should be no problem.

Many of the methods come with deprecation warnings that explain what to use instead. We can keep these messages around in the form of `unavailable` attributes.

/cc @mapbox/maps-ios

**Comment by jmkiley** [comment]
Closed with #11205
