### ISSUE TITLE
Pinch to zoom changed drastically between 5.1.2 and 5.2.0

### ISSUE THREAD

**Issue by cvance** [mapbox/mapbox-gl-native#10737]
**Platform:** Android
**Mapbox SDK version:** 5.2.0

### Steps to trigger behavior
 1. Pinch to zoom

### Expected behavior
Map stops moving or continues to move a little based on momentum

### Actual behavior
Map snaps to a zoom level beyond where the pinching stopped

Zooming on 5.1.2:
https://imgur.com/a/8g9kt

Zooming on 5.2.0:
https://imgur.com/a/Wniez

**Comment by tobrun** [comment]
zooming now has velocity, you can pinch and as a result trigger a scale animation. 
Reworking this is ticketed in #10016
