### ISSUE TITLE
Tap gesture recognizer for MGLPointAnnotation loses accuracy with 3.7.1

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-gl-native#10734]
**Platform:** iOS
**Mapbox SDK version:** 

:x: occurs in 3.7.1
✅ does not occur in 3.7.0
✅ does not occur in 3.6.4

### Steps to trigger behavior

 1. Add a good amount of `MGLPointAnnotations` to the map. This issue occurred for me when using ~50 annotations.

```swift 
        var annotations = [MGLPointAnnotation]()
        var long = -70
        
        for _ in 1...50 {
            long += 2
            let point = MGLPointAnnotation()
            point.coordinate = CLLocationCoordinate2D(latitude: 40.73, longitude: CLLocationDegrees(long))
            point.title = "Hello world!"
            annotations.append(point)
        }
        
        mapView.addAnnotations(annotations)
```
 2. Attempt to tap on the annotations to reveal callouts

### Expected behavior

1. The callout should open the first time an annotation is tapped directly.

### Actual behavior
1. The callout does not appear every time an annotation is tapped. Multiple taps on an annotation are sometimes required in order for the annotation to appear.

**Comment by fabian-guerra** [comment]
Could you please try same code in our sample app?
```
NSMutableArray * annotations = [NSMutableArray array];
    CLLocationDegrees longitude = -70;
    
    for (int i=0; i < 50; i++) {
        longitude += 2;
        MGLPointAnnotation * point = [[MGLPointAnnotation alloc] init];
        point.coordinate = CLLocationCoordinate2DMake(40.73, longitude);
        point.title = @"Hello world!";
        [annotations addObject:point];
    }
    
    [self.mapView addAnnotations:annotations];
```
Running the code above in our sample app works as expected. But if I try the code you used in my tryout app it does not work even with 3.7.0

**Comment by captainbarbosa** [comment]
@fabian-guerra this fell off my radar, sorry! 🙈 

I tested this out with 3.7.5 and I'm not seeing this issue anymore, so I think it is safe to close this for now.
