### ISSUE TITLE
IOS-Getting issue with "make ipackage"

### ISSUE THREAD

**Issue by harshit-mapmyindia** [mapbox/mapbox-gl-native#10744]
I have imported <Mapbox/Mapbox.h> in http_file_source.mm because i need to manipulate 

/{z}/{x}/{y}.pbf

everything is working fine but when i try to run the command   "make ipackage" im getting the following error: 

❌  /Users/harshit/mapbox-gl-native/platform/darwin/src/http_file_source.mm:12:10: 'Mapbox/Mapbox.h' file not found

#include <Mapbox/Mapbox.h>
         ^~~~~~~~~~~~~~~~~

▸ Compiling online_file_source.cpp
▸ Compiling offline_download.cpp
** BUILD FAILED **

The following build commands failed:
	CompileC build/ios/mbgl.build/Debug-iphonesimulator/mbgl-filesource.build/Objects-normal/i386/http_file_source.o platform/darwin/src/http_file_source.mm normal i386 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/ios/mbgl.build/Debug-iphonesimulator/mbgl-filesource.build/Objects-normal/x86_64/http_file_source.o platform/darwin/src/http_file_source.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

**Comment by kkaefer** [comment]
There's no need to manipulate anything in this file. Instead, you can configure the URLs for tile endpoints in the [source](https://www.mapbox.com/mapbox-gl-js/style-spec#sources-vector) of your style.

**Comment by harshit-mapmyindia** [comment]
i want to encrypt /{z}/{x}/{y}.pbf and that can be accessed in http_file_source.mm file only. also i want to add a header to the the api call which is handled in the same class.

**Comment by sameerakohli** [comment]
I am facing the same issue when i tried to modify http_file_source.mm for encryption of {z}/{x}/{y}.pbf and for adding some extra headers in the Api call.
