### ISSUE TITLE
Upload data from OSM to Mapbox

### ISSUE THREAD

**Issue by adolgiy** [mapbox/mapbox-gl-native#10751]
Hi, Mapbox Team! We chose your service because of flexibilty of OSM integration. We've added lots of data to OSM. So, how we can import that data to Mapbox? This data is actually roads, buildings and so on.

**Comment by jfirebaugh** [comment]
Hi, @adolgiy thanks for using Mapbox! For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
