### ISSUE TITLE
Stratified MyLocationView 

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#10761]
Capturing from https://github.com/mapbox/mapbox-gl-native/pull/10746#issuecomment-353030631

"Step to reproduce.
Run Any activity with location marker on it.->Take app in background.->Bring app in foreground

Location marker is splitting in two parts attached is screenshot.(Device is OnePlus 3T running Oreo)"

![whatsapp image 2017-12-20 at 16 12 45](https://user-images.githubusercontent.com/1751271/34203480-47a345be-e5a1-11e7-9a7d-258ac8311e82.jpeg)

/cc @mdakram

**Comment by LukasPaczos** [comment]
@mdakram Feel free to test out `6.0.0-SNAPSHOT` and let us know if all works for you now.

**Comment by mdakram** [comment]
Hi @LukasPaczos tested this fix with 5.3.0 release and its working as expected. Thanks man.
