### ISSUE TITLE
Compass and scale bar constraints are incorrect on iOS 10

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#10773]
The top offset for our compass and scale bar is too large on iOS 10. This is a regression on `release-agua` since v3.7.1, so probably it’s related to #10658.

<img src=https://user-images.githubusercontent.com/1198851/34237759-3d5d7aa4-e5b3-11e7-8cda-1d44d1347cbe.png width=275>

Note that the top map view is incorrectly offset from the nav bar, while the lower map view hugs the top. You don’t need two map views to reproduce this, this is just where I happened to take a screenshot.

/cc @fabian-guerra @akitchen @frederoni @lilykaiser

**Comment by fabian-guerra** [comment]
https://github.com/mapbox/mapbox-gl-native/pull/10658 fixes the offset for iOS 11 since it introduced a new way to add constraints `constraintEqualToSystemSpacingBelowAnchor`. I am looking at what is causing the big offset on iOS 10.

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/10777
