### ISSUE TITLE
visibleAnnotations(in: rect) returns wrong number of annotations the second time

### ISSUE THREAD

**Issue by mikaelhellqvist** [mapbox/mapbox-gl-native#10788]
**Platform: iOS**
**Mapbox SDK version: 3.7.2**

### Steps to trigger behavior

 1. Draw polygon on map
 2. Add mapView.visibleAnnotations(in: rect)
 3. Tap the in the same rect twice

### Expected behavior
Should return the same number of annotations no matter how many times the user taps in the rect.

### Actual behavior
Returns the same annotation twice when tapping the second time.
Tapping a third time it returns only the first annotation again.
Tapping a fourth time the behovior is the same as tapping a second time. And so it goes on.

**Comment by jmkiley** [comment]
Hey @mikaelhellqvist  -

Thank you for the report. I have not been able to reproduce this issue with v3.7.2. Could you share a minimal test case that repros this issue?

**Comment by mikaelhellqvist** [comment]
My bad! It was me. Really sorry! I thought I'd tested this  thoroughly but apparently not.
