### ISSUE TITLE
Labeling density and priority

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-native#1078]
Labels are sparse, and out of sequence (minor cities appear before majors) -- is the latest labeling code part of gl-native yet?

Compare https://www.mapbox.com/bites/00108/#4.1/36.859/-75.362 with:

![img_1075](https://cloud.githubusercontent.com/assets/4551508/6796841/175ab35c-d1b7-11e4-9383-7a8450c14105.PNG)

cc/ @incanus @jfirebaugh

**Comment by jfirebaugh** [comment]
> is the latest labeling code part of gl-native yet

No, it hasn't been ported.

**Comment by jfirebaugh** [comment]
⇢ #1139.
