### ISSUE TITLE
mapbox freeze when background and foreground again.

### ISSUE THREAD

**Issue by radaresdeportugal** [mapbox/mapbox-gl-native#10787]
I have a app with this plugin. The plugin LocationLayer 0.2.0-SNAPSHOT works fine with 5.2.0 beta.3 SDK, but if i try version 0.3.0-SNAPSHOT with 5.2.0 beta.4 or higher the mapbox freeze when come back from standby. in other words, if i press power button and back again the map is freezed (blocked).

freeze: https://www.youtube.com/watch?v=OZAI5U3W7OQ

SDK 5.3.0-SNAPSHOT
PLUGIN: LocationLayer 0.3.0-SNASPHOT

The plugin 0.2.0 SNAPSHOT dont work on 5.2.0 beta.4 SDK or higher version

Please help.

Thank you.

**Comment by tobrun** [comment]
Thank you for reaching out I will try reproducing.

**Comment by radaresdeportugal** [comment]
Please see: https://youtu.be/0LR67XP-9do

Thank you!

**Comment by radaresdeportugal** [comment]
sorted out. I had an error in mapView.onStop (); thank you!
