### ISSUE TITLE
MGLMapSnapshotter: crash com.mapbox.mbgl.Map Snapshotter (31): EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by alpennec** [mapbox/mapbox-gl-native#10799]
Hello,

I am trying to migrate from `MKMapSnapshotter` to `MGLMapSnapshotter` but I encounter a crash.
I configure the `MGLMapSnapshotter` with some options, then start the rendering process (from a background thread, in an operation). The "same" code is working perfectly for the `MKMapSnapshotter`.

**Is there anything wrong with my implementation?**

___
Configuration for both MapKit and Mapbox.

<img width="1044" alt="capture d ecran 2017-12-25 06 13 23" src="https://user-images.githubusercontent.com/2082662/34333236-c9dc9ac0-e93a-11e7-91f0-3afc214ce86c.png">

___
Crash below.
Crashlog provided by Fabric: 
[com.alepennec.skipper_issue_214_crash_57d91604901e40c69332fcd139b7c882_02c7ff4ae93111e7a44b56847afe9799_0_v2.txt](https://github.com/mapbox/mapbox-gl-native/files/1585353/com.alepennec.skipper_issue_214_crash_57d91604901e40c69332fcd139b7c882_02c7ff4ae93111e7a44b56847afe9799_0_v2.txt)

<img width="1402" alt="capture d ecran 2017-12-25 06 15 15" src="https://user-images.githubusercontent.com/2082662/34333248-fefd415a-e93a-11e7-8a3f-5983fdb85ca2.png">

___
**Platform:** iOS
**Mapbox SDK version:** 3.7.2

### Expected behavior
A snapshot should be generated.

### Actual behavior
A crash occurs.

**Comment by fabian-guerra** [comment]
Hi, @alpennec. Thank you for using Mapbox. From the screenshot you posted I noticed `fakeCamera` is not properly initialized please take a look at the [class example](https://www.mapbox.com/ios-sdk/api/3.7.2/Classes/MGLMapSnapshotter.html). Could you please post a code snippet we could use to track down the crash?

**Comment by alpennec** [comment]
Hi, @fabian-guerra.

Thanks for your answer. I fixed my issue by running my code on the main thread.
I also tried to initialize the camera using your class example (```let camera = MGLMapCamera(lookingAtCenter: CLLocationCoordinate2D(latitude: 37.7184, longitude: -122.4365), fromDistance: 100, pitch: 20, heading: 0)```) and I had the same issue.

The following code works (even though I am initializing the ```fakeCamera``` without providing any parameters.

```
case .mapbox:
     DispatchQueue.main.sync {
          let styleURL = MGLStyle.outdoorsStyleURL(withVersion: 9)
          let fakeCamera = MGLMapCamera()
          let snapshotOptions = MGLMapSnapshotOptions(styleURL: styleURL, camera: fakeCamera, size: size)
          snapshotOptions.zoomLevel = 9
          snapshotOptions.coordinateBounds = MGLCoordinateBounds(sw: regionForActivity.southWest, ne: regionForActivity.northEast)
                
          let snapshotter = MGLMapSnapshotter(options: snapshotOptions)
          snapshotter.start { (snapshot, error) in
               
               guard !self.isCancelled else {
                    self.finish()
                    return
               }
                    
               guard error == nil else {
                    self.finish()
                    return
               }
                    
               guard let unwrappedSnapshot = snapshot else {
                    self.finish()
                    return
               }
                    
               self.snapshotAvailable = true
               self.rawMapboxSnapshot = unwrappedSnapshot
               self.finish()
           }
      }
}
```

Axel

**Comment by fabian-guerra** [comment]
Hi, @alpennec.

Since you already fixed the issue I'm going to close it. Please feel free to re-open if it's the case.

Fabián.
