### ISSUE TITLE
Mapbox freeze when i open keyboard on facebook messenger.

### ISSUE THREAD

**Issue by radaresdeportugal** [mapbox/mapbox-gl-native#10798]
Mapbox freeze when i open keyboard on facebook messenger or in other program

SDK: 5.3.0 snapshot

Please, see de video: https://youtu.be/h-OYtges8gE

Thanks.

**Comment by tobrun** [comment]
@radaresdeportugal I'm unable to view the attached video, would you be able to reupload it? Are you able to give a bit more context to this issue?

**Comment by radaresdeportugal** [comment]
Hello tobrun! 

Its fixed! I resolve when i installing this: 

    public class GLMapViewRenderer implements GLSurfaceView.Renderer {

        private static final String TAG = "MyGLRenderer";

        public void onSurfaceCreated(GL10 unused, EGLConfig config) {
            GLES20.glClearColor(1.0f, 0.0f, 0.0f, 1.0f);
        }

        @Override
        public void onDrawFrame(GL10 unused) {
            GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT | GLES20.GL_DEPTH_BUFFER_BIT);
        }

        @Override
        public void onSurfaceCreated(GL10 gl10, javax.microedition.khronos.egl.EGLConfig eglConfig) {
            GLES20.glClearColor(1.0f, 0.0f, 0.0f, 1.0f);
        }

        @Override
        public void onSurfaceChanged(GL10 unused, int width, int height) {
            GLES20.glViewport(0, 0, width, height);
        }
    }

Thank you! :)
