### ISSUE TITLE
confirm animated/unanimated callbacks

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1080]
We should confirm that we are using `MapChangeRegionDidChangeAnimated` properly, for example here, this is not an animated change: 

https://github.com/mapbox/mapbox-gl-native/blob/2990f388240e6de586de6ebf20258503e68dad6a/platform/ios/MGLMapView.mm#L667

**Comment by incanus** [comment]
To clarify, `animated:YES` should indicate a programmatic change that received an `animated:YES` argument.

**Comment by friedbunny** [comment]
It looks like this may have been fixed, @incanus?
