### ISSUE TITLE
InfoWindowAdapter

### ISSUE THREAD

**Issue by britneygill** [mapbox/mapbox-gl-native#10806]
Hi,
I am working with the custom view in the info window adapter and I continue to have issues. I created a layout and inflated the view except some times the correct window pops up and sometimes the generic window pops up.

Android
mapbox-sidk:5.2.0aar

I am using the setInfoWindowAdapter method however it decides when it wants to work. Anyone have these issues or know a solution?

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
