### ISSUE TITLE
Use a DirectionResponse JSON to init a Route for Navigation

### ISSUE THREAD

**Issue by DDraiman1990** [mapbox/mapbox-gl-native#10802]
**Platform: IOS Swift 3.2, XCode 9.1**
**Mapbox SDK version: 3.6**

### Steps to trigger behavior
Calculate a certain route using Mapbox on an external server and send the DirectionResponse (JSON containing the "code", "routes" and "waypoints" fields) to the client.

### Expected behavior
Have a certain way to parse the DirectionResponse JSON to a Route to be able to use it for navigation.
Example: "Route(json: JSONDictionary)" that expects a DirectionResponse
Or maybe make MBRouteOptions' "response" function be generic to parse a JSON DirectionResponse into ([Waypoint]?, [Route]?)

### Actual behavior
There is no inherit way to parse it using Mapbox since the "response(from json: JSONDictionary) -> ([Waypoint]?, [Route]?)" within MBRouteOptions is marked as Internal (along with Waypoint's "convenience init?(geoJSON json: JSONDictionary)") and there is no other way to parse that information. 

**Is there no way to parse a DirectionResponse into a Route using MapBox classes to be able to use it for navigation??**

Thanks

**Comment by fabian-guerra** [comment]
Hi @DDraiman1990. Thank you for using Mapbox. Please post this issue in our [MapboxDirections.swift](https://github.com/mapbox/MapboxDirections.swift/issues) repo.
