### ISSUE TITLE
MAPBOX 3.7 version update iOS giving crash on adding Annotations.

### ISSUE THREAD

**Issue by siddharthadeb** [mapbox/mapbox-gl-native#10800]
**Platform:**
iOS 9+ to latest 
Xcode 9.2
**Mapbox SDK version:**
Mapbox 3.7 (installed thru cocapods)
### Steps to trigger behavior

 1. Trying to add annotations in map box in offline downloaded packs.
 2.
 3.

### Expected behavior
It should add as older versions happened.
### Actual behavior
Giving crashes - Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MKAnnotationView setMapView:]: unrecognized selector sent to instance

**Comment by fabian-guerra** [comment]
Hi, @siddharthadeb. Thank you for using Mapbox. Could you please post a code snippet or app we could use to track down the exception?
