### ISSUE TITLE
MapView.onDestroy() hangs, freezes, does not return, ANRs when used in certain Activity/Fragment 

### ISSUE THREAD

**Issue by michaelfomin** [mapbox/mapbox-gl-native#10809]
In my app I use an Activity with Fragment with MapView.  When I open this Activity and close it, MapView.onDestroy does-not-return causing an ANR

I have included a sample app showing this
[MapBoxFreeze.zip](https://github.com/mapbox/mapbox-gl-native/files/1594143/MapBoxFreeze.zip)

See traces.txt for the ANR
[traces.txt](https://github.com/mapbox/mapbox-gl-native/files/1594144/traces.txt)

**Platform: Android 8.1**
**Mapbox SDK version: mapbox-android-sdk:5.3.0**

### Steps to trigger behavior

 1. Launch the attached app
 2. Open the 2nd activity by clicking the 'popop' button
 3. Click android back button
 4. Observer freeze ANR

### Expected behavior
Does not freeze

### Actual behavior
Freezes

**Comment by michaelfomin** [comment]
In the sample app, please don't forget to add a working access token in MainActivity.java

**Comment by michaelfomin** [comment]
I have commented out the calls the MapView.onDestroy() as a workaround. What is the affect of this?

**Comment by tobrun** [comment]
You need to call `MapView#onDestroy` as part of `Fragment#onDestroyView` and not `Fragment#onDestroy`
