### ISSUE TITLE
Marker Blinking issue 

### ISSUE THREAD

**Issue by swsong12** [mapbox/mapbox-gl-native#10808]
Hi Mapbox team and contributors! Recently I approached a very critical issue that affects our user experience. Whenever I zoom in and out of the map, the markers would blink. Other issue/post suggests that this issue is solved on upcoming 6.0.0 release. Yet, there seems to be no estimate on release date. Before the 6.0.0 update, is there anyway we can temporarily fix this problem? 

Platform: android
Mapbox SDK version: 5.3.0

**Comment by tobrun** [comment]
@swsong12 afaik there isn't a way to workaround this. We are aiming a 6.0.0-beta.1 release somewhere this week. Since this issue is fixed on master, going to close this.

**Comment by swsong12** [comment]
@tobrun Is 6.0.0-beta.1 coming out soon? Is this also fixed on 6.0.0 SNAPSHOT?

**Comment by tobrun** [comment]
beta.1 is planned for this week and yes 6.0.0-SNAPSHOT will contain this fix!
