### ISSUE TITLE
error

### ISSUE THREAD

**Issue by siddarthk123** [mapbox/mapbox-gl-native#10805]
dyld: Library not loaded: @rpath/MapboxDirections.framework/MapboxDirections

import UIKit
import Mapbox
import MapboxDirections
import MapboxNavigation
import MapboxCoreNavigation

This is my code.
class ViewController: UIViewController, MGLMapViewDelegate {
    
    var mapView: NavigationMapView!
    var directionsRoute: Route?
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        mapView = NavigationMapView(frame: view.bounds)
        
        view.addSubview(mapView)
        
        // Set the map view's delegate
        mapView.delegate = self
    }
    
}

**Comment by fabian-guerra** [comment]
Hi, @siddarthk123. Thank you for using Mapbox. Please post this issue in [MapboxDirections.swift](https://github.com/mapbox/MapboxDirections.swift/issues) repo.
