### ISSUE TITLE
Crash after setting max zoom and zooming into downloaded region

### ISSUE THREAD

**Issue by dsuresh-ap** [mapbox/mapbox-gl-native#10807]
**Platform: Android**
**Mapbox SDK version: 5.2.1**

App crashes after setting min, max zoom and downloading offline region. The crash happens when zooming into offline region.

### Steps to trigger behavior

 1. Set `MapboxMap.setMinZoomPreference(8)`
 2. Set `MapboxMap.setMaxZoomPreference(14)`
 3. Zoom to maximum and start download
 4. After download completed set min to 0 and max to 20.
 5. Attempt to zoom into downloaded region.

### Expected behavior

Map should zoom into region as much as it can

### Actual behavior

App crashes with following stacktrace:

`FATAL EXCEPTION: GLThread 6358
                                                                 Process: com.gotenna.pro, PID: 25219
                                                                 java.lang.Error: Requested zoom higher than maxZoom: 16
                                                                     at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeRender(Native Method)
                                                                     at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onDrawFrame(MapRenderer.java:91)
                                                                     at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.onDrawFrame(GLSurfaceViewMapRenderer.java:55)
                                                                     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1561)
                                                                     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1278)`

The following are zoom levels before crash.

`mapView.getMaxZoom() = 20.0
mapView.nativeGetMaxZoom() = 20.0
mapView.getZoom() = 16.39531068214362`

**Comment by tobrun** [comment]
@dsuresh-ap thank you for reaching out and reporting your issue. I'm currently not able to reproduce this:

![ezgif com-video-to-gif 7](https://user-images.githubusercontent.com/2151639/34489354-5a92bf34-efdc-11e7-8eae-30d830880c24.gif)

In above I did the same steps as mentioned in OP. Do you have some additional information, code or context?

**Comment by dsuresh-ap** [comment]
@tobrun I think the issue had to do because I added a Polygon after setting min/max and when zooming into the region with the Polygon after resetting the min/max caused the crash. The workaround I found was to reload all the Polygons after I reset the min/max.

Code to add polygon:
`PolygonOptions polygonOptions = new PolygonOptions()
                .addAll(polygonPoints)
                .strokeColor(ContextCompat.getColor(getActivity(), R.color.mapBoxOfflineRegionOverlayColor))
                .fillColor(ContextCompat.getColor(getActivity(), R.color.mapBoxOfflineRegionOverlayColor));

        Polygon polygon = mapboxMap.addPolygon(polygonOptions);`

**Comment by tobrun** [comment]
Thank you for adding the Polygon part, was able to reproduce with that in place.

**Comment by tobrun** [comment]
@dsuresh-ap to make it easier for other :eyes:  I created a follow up ticket in #10816.
