### ISSUE TITLE
SymbolLayer's categorical function won't work

### ISSUE THREAD

**Issue by uburoiubu** [mapbox/mapbox-gl-native#10819]
**Mapbox Android SDK 5.2.1.**

Here's how I set my layer:

```
        SymbolLayer eventLayer = new SymbolLayer("event_layer", "event_source");
        eventLayer.setProperties(PropertyFactory.iconImage(Function.property("eventTypeId", Stops.categorical(
                Stop.stop(1730916298, PropertyFactory.iconImage("event_in")),
                Stop.stop(-937726786, PropertyFactory.iconImage("event_out"))
                ))),
                iconAllowOverlap(true)
        );
```

Here's how I add it:

```
public void addEvents(RealmList<EventRealmObj> events) {

        ArrayList<Feature> points = new ArrayList<>();

        for (int i = 0; i < events.size(); i++) {
            if (events.get(i).getLongitude() == 0 || events.get(i).getLatitude() == 0) continue;
            points.add(makeEventPoint(events.get(i)));
        }

        FeatureCollection collection = FeatureCollection.fromFeatures(points);
        GeoJsonSource geoJsonPoints = (GeoJsonSource) mapboxMap.getSource("event_source");
        if (geoJsonPoints != null) geoJsonPoints.setGeoJson(collection);
    }

    private Feature makeEventPoint(EventRealmObj event) {
        JsonObject properties  = new JsonObject();
        properties.addProperty("eventTypeId", event.getTypeId());
        Point point = Point.fromCoordinates(Position.fromLngLat(event.getLongitude(), event.getLatitude()));
        return Feature.fromGeometry(point, properties);
    }
```

Here comes my `Json`:

`{"features":[{"geometry":{"coordinates":[38.4748878,55.8603668],"type":"Point"},"properties":{"eventTypeId":1730916298},"type":"Feature"},{"geometry":{"coordinates":[38.4748955,55.8611832],"type":"Point"},"properties":{"eventTypeId":-937726786},"type":"Feature"},{"geometry":{"coordinates":[38.4749451,55.8611526],"type":"Point"},"properties":{"eventTypeId":1730916298},"type":"Feature"},{"geometry":{"coordinates":[38.4749031,55.860878],"type":"Point"},"properties":{"eventTypeId":-937726786},"type":"Feature"},{"geometry":{"coordinates":[38.4750862,55.8596268],"type":"Point"},"properties":{"eventTypeId":1730916298},"type":"Feature"},{"geometry":{"coordinates":[38.46278,55.8578606],"type":"Point"},"properties":{"eventTypeId":-937726786},"type":"Feature"},{"geometry":{"coordinates":[38.4752235,55.8611641],"type":"Point"},"properties":{"eventTypeId":1730916298},"type":"Feature"},{"geometry":{"coordinates":[38.4748611,55.8611755],"type":"Point"},"properties":{"eventTypeId":-937726786},"type":"Feature"},{"geometry":{"coordinates":[38.4750595,55.8611641],"type":"Point"},"properties":{"eventTypeId":1730916298},"type":"Feature"},{"geometry":{"coordinates":[38.4751549,55.8583679],"type":"Point"},"properties":{"eventTypeId":-937726786},"type":"Feature"}],"type":"FeatureCollection"}
`

It does not work. Why?

**Comment by LukasPaczos** [comment]
I was able to reproduce on `master` with the following:
```
    mapView.getMapAsync(map -> {
      mapboxMap = map;

      mapboxMap.addImage(
        "event_in",
        BitmapFactory.decodeResource(SymbolLayerActivity.this.getResources(),
          R.drawable.ic_android)
      );

      mapboxMap.addImage(
        "event_out",
        BitmapFactory.decodeResource(SymbolLayerActivity.this.getResources(),
          R.drawable.ic_android_2)
      );

      FeatureCollection featureCollection = FeatureCollection.fromJson(JSON);
      GeoJsonSource source = new GeoJsonSource("event_source", featureCollection);
      mapboxMap.addSource(source);

      SymbolLayer eventLayer = new SymbolLayer("event_layer", "event_source");
      eventLayer.setProperties(
        PropertyFactory.iconImage(
          Function.property("eventTypeId", Stops.categorical(
            Stop.stop(1730916298, PropertyFactory.iconImage("event_in")),
            Stop.stop(-937726786, PropertyFactory.iconImage("event_out"))
          ))),
        iconAllowOverlap(true),
        iconIgnorePlacement(true)
      );

      mapboxMap.addLayer(eventLayer);

      // Show
      mapboxMap.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(55.8, 38.4), 10));
    });
```

**Comment by LukasPaczos** [comment]
It seems like there is a type mismatch when converting between Core and Android values, therefore the map doesn't pick up the function properly. Notice, that when we use smaller values as `eventTypeId` everything works fine.

A temporary solution would be to use `String` as your `eventTypeId` property value, for example:
```
private Feature makeEventPoint(EventRealmObj event) {
        JsonObject properties  = new JsonObject();
        properties.addProperty("eventTypeId", String.valueOf(event.getTypeId()));
        Point point = Point.fromCoordinates(Position.fromLngLat(event.getLongitude(), event.getLatitude()));
        return Feature.fromGeometry(point, properties);
    }
```
and
```
eventLayer.setProperties(PropertyFactory.iconImage(Function.property("eventTypeId", Stops.categorical(
                Stop.stop("1730916298", PropertyFactory.iconImage("event_in")),
                Stop.stop("-937726786", PropertyFactory.iconImage("event_out"))
                ))),
                iconAllowOverlap(true)
        );
```

@uburoiubu, thanks for reporting this problem and let us know if above solution helps and fits your use-case.

/cc @tobrun @ivovandongen @kkaefer

**Comment by LukasPaczos** [comment]
I found out that the value which we are passing in the function is later on converted to `unsigned char` array and passed further. Can that conversion be the source of this issue?

**Comment by uburoiubu** [comment]
I had this temporary workaround ():

```
private static final int EVENT_ZONE_IN = 1730916298;
private static final int EVENT_ZONE_OUT = -937726786;

public void addEvents(RealmList<EventRealmObj> events) {

        ArrayList<Feature> points = new ArrayList<>();

        for (int i = 0; i < events.size(); i++) {
            if (events.get(i).getLongitude() == 0 || events.get(i).getLatitude() == 0) continue;
            points.add(makeEventPoint(events.get(i)));
        }

        FeatureCollection collection = FeatureCollection.fromFeatures(points);
        GeoJsonSource geoJsonPoints = (GeoJsonSource) mapboxMap.getSource("event_source");
        if (geoJsonPoints != null) geoJsonPoints.setGeoJson(collection);
    }

 private Feature makeEventPoint(EventRealmObj event) {
        JsonObject properties  = new JsonObject();

        if (event.getTypeId() == EVENT_ZONE_IN) {
            properties.addProperty("enter", true);
        } else if (event.getTypeId() == EVENT_ZONE_OUT) {
            properties.addProperty("enter", false);
        }

        Point point = Point.fromCoordinates(Position.fromLngLat(event.getLongitude(), event.getLatitude()));
        return Feature.fromGeometry(point, properties);
    }


```

**Comment by jfirebaugh** [comment]
@LukasPaczos Can you link to the code you're referring to?

**Comment by LukasPaczos** [comment]
@jfirebaugh What I noticed is that before the `convertStops()` function returns [here](https://github.com/mapbox/mapbox-gl-native/blob/dadd90e4e9085ab69bb9c95758f9a5224a1da0b3/include/mbgl/style/conversion/function.hpp#L128), our value is represented by an `unsigned char array` of 32 elements and after it returns, stop value in the map is represented by 16 elements. It's just a blind shot, please correct me if I'm looking at totally unrelated things.

**Comment by jfirebaugh** [comment]
Might be related. Can you step into [here](https://github.com/mapbox/mapbox-gl-native/blob/dadd90e4e9085ab69bb9c95758f9a5224a1da0b3/include/mbgl/style/conversion/function.hpp#L103-L116) and look at `n`?

**Comment by LukasPaczos** [comment]
`n.__val_` looks fine here, matches the given value.

**Comment by LukasPaczos** [comment]
I noticed that [this](https://github.com/mapbox/mapbox-gl-native/blob/dadd90e4e9085ab69bb9c95758f9a5224a1da0b3/include/mbgl/style/conversion/function.hpp#L110) returns `unsigned char array` of 32 and later, `d`'s underlying value [here](https://github.com/mapbox/mapbox-gl-native/blob/dadd90e4e9085ab69bb9c95758f9a5224a1da0b3/include/mbgl/style/conversion/function.hpp#L46) has only 16 elements.

**Comment by geekmario** [comment]
fuck the problem...

**Comment by jfirebaugh** [comment]
Stale; this functionality has been replaced by expressions.
