### ISSUE TITLE
Add image to style by URL

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#10826]
We currently require users to provide a fully loaded image when calling `Style::addImage`. We should also allow passing a name + URL, and then use our internal file request capabilities to load that image instead of forcing users to implement this routine themselves.

**Comment by kkaefer** [comment]
Previous tickets: https://github.com/mapbox/mapbox-gl-native/issues/9461

Related: https://github.com/mapbox/mapbox-gl-js/issues/4086

**Comment by hussi-azam** [comment]
Anything on this ?
