### ISSUE TITLE
MGLShapeSourceOption conflict in jazzy

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#10821]
Running `make idocument` on `master` (but not `release-agua`) as of 637892c will result in this warning from jazzy (v0.9.0):

> Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: type definition MGLShapeSourceOption, type definition MGLShapeSourceOption

/cc @asheemmamoowala @1ec5 @jmkiley

**Comment by asheemmamoowala** [comment]
Looks like it got re-defined in `MGLAbstractShapeSource`, but not removed from `MGLShapeShource`.
