### ISSUE TITLE
Logo and attribution constraints are incorrect on iOS 11 and iPhone X

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/mapbox-gl-native#10834]
The botttom offset for our logo and attribution is too large on iOS 11 and iPhone X in fullscreen `MGLMapView`. This is a regression on `release-agua` since v3.7.1

![simulator screen shot - iphone x - 2018-01-04 at 15 29 35](https://user-images.githubusercontent.com/2745166/34585894-5577dc64-f167-11e7-843f-657f090bff58.png)

**Comment by akitchen** [comment]
Given the number of regressions around this, I think it is really important to have a test of the layout which we can run on a number of devices/versions to ensure we're consistently doing the right thing. I'd be happy to pair on that if it would be helpful.

**Comment by friedbunny** [comment]
As one anecdotal point, this isn’t happening in Studio Preview (which features a full screen map defined in a storyboard).

@akitchen I’d be interested in tag-teaming on tests for this with you and @fabian-guerra — it’d be great if we could get into the regular practice of “fix a regression, add a test” while we’re at it. 👩‍🏫

**Comment by fabian-guerra** [comment]
@friedbunny @akitchen let me know if you have time today to pair and add tests for the layout. Is interesting that is not happening in Studio Preview.
