### ISSUE TITLE
Expose SourceInfo on Map object

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#1083]
Need some way to grab `center`, `bounds` and similar keys from [`SourceInfo`](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/style/style_source.hpp#L18-L26) to build a `getInfo` [Tilelive API](https://github.com/mapbox/tilelive.js/blob/master/API.md) method similar to [`Vector.prototype.getInfo`](https://github.com/mapbox/tilelive-vector/blob/master/index.js#L226-L263).

**Comment by jfirebaugh** [comment]
I think this wants the `center` and `zoom` from the style (https://github.com/mapbox/mapbox-gl-style-spec/issues/247, not implemented yet). Grabbing it from the source is weird because there can be multiple sources.

**Comment by mikemorris** [comment]
Yea, looking at Mapnik this info seems to be [tied directly to the XML stylesheet](https://github.com/mapbox/tilelive-vector/blob/master/test/fixtures/a.xml#L6-L12). I was thinking that we would somehow composite the parameters from multiple sources together, but implementing this on the style itself would be much simpler.

**Comment by jfirebaugh** [comment]
We're holding on building out the tilelive API for GL -- it doesn't have a clear use case.
