### ISSUE TITLE
#10810 updated a generated file without changing the source

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#10846]
cc @tobrun 

The source for this file needs the update so that the changes in #10810 doesn't get overwritten the next time we run `make style-code`.

**Comment by jfirebaugh** [comment]
Same with #10549.

**Comment by tobrun** [comment]
Thank you for flagging, fix in https://github.com/mapbox/mapbox-gl-native/pull/10856
