### ISSUE TITLE
Annotations inappropriately disappear en masse based on zoom

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#10845]
On `master` circa 10a44050f485a18f8dd6523aca6a7a9f82f7afc7 (pre-ios-v4.0.0), zooming in/out of a map with 10,000 sprite annotations can cause virtually every annotation to inappropriately disappear.

1. Add 10,000 sprite annotations in iosapp.
2. Zoom several levels in and out — annotations will disappear and then mostly never reappear.

[Check out this video for a demonstration.](https://www.dropbox.com/s/kwsz5wczulb90q1/ScreenRecording_01-05-2018%2016-21-46.MP4?dl=0)

If you quickly zoom in to ~z11 and then out to ~z4, it’s possible to have a single annotation remaining (out of the 10k that should be visible). In general, this appears to be happening within individual tiles.

![sprites_gonezo](https://user-images.githubusercontent.com/1198851/34629187-4c0328a4-f235-11e7-850e-9222b73005fb.png)
_Annotations have gonezo._

/cc @mapbox/gl-core @akitchen @fabian-guerra @lilykaiser

**Comment by 1ec5** [comment]
Does this issue reproduce only with annotations, or does it also reproduce with symbols in a symbol layer? Collision detection was overhauled in #10436 on master; could that be related?

**Comment by ChrisLoer** [comment]
> Collision detection was overhauled in #10436 on master; could that be related?

Yeah, I think so, although I'm not super familiar with how Annotations are implemented -- basically a `SymbolAnnotation` should behave like an icon feature, right? @ansis, this makes me think "inappropriate CrossTileSymbolIndex duplicate detection" -- does this ring any bells with the work you're doing right now?

**Comment by jfirebaugh** [comment]
Symbol annotations use a symbol layer with `"icon-allow-overlap": true` and `"icon-ignore-placement": true`.

Another potential culprit is ac32b41493956e6b03ab13475f27a4dcd64355ae.

**Comment by ChrisLoer** [comment]
I can reproduce this on the commit before https://github.com/mapbox/mapbox-gl-native/commit/ac32b41493956e6b03ab13475f27a4dcd64355ae.

**Comment by kkaefer** [comment]
I believe https://github.com/mapbox/mapbox-gl-native/commit/ac32b41493956e6b03ab13475f27a4dcd64355ae isn't at fault here, since I can observe the same behavior in the commit immediately preceding it.

**Comment by ChrisLoer** [comment]
Bisected to #10436.

**Comment by ChrisLoer** [comment]
https://github.com/mapbox/mapbox-gl-native/pull/10899 appears to fix this (I've tested on macosapp and a simulated iphone 6s so far).
