### ISSUE TITLE
"Lost connection to “My Mac”" error after adding mapbox-macos-sdk

### ISSUE THREAD

**Issue by marsteini** [mapbox/mapbox-gl-native#10840]
I'm trying to build an MacOS application with the Mapbox-macOS-SDK, but I have trouble getting it started. I added the dependency via Cocoapods (SDK Version 0.6.0) and added an API key.
The project is compiling without errors, but when the app started I'm getting a ```Lost connection to “My Mac”```error message from Xcode. Target is OSX 10.12.

Has anyone same problems? Or a clue why this is happening?

**Comment by jfirebaugh** [comment]
Hi @marsteini, thanks for using Mapbox. A "Lost connection to “My Mac”" error doesn't sound related to Mapbox GL, so I'm afraid we can't help there. (If you have other reason to believe it's related, let us know.)
