### ISSUE TITLE
LatLngBounds.Builder should create bounds with the shortest longitude span

### ISSUE THREAD

**Issue by osana** [mapbox/mapbox-gl-native#10843]
The following test should be passing:  

@Test
  public void dateLineSpanBuilder1() {
    latLngBounds = new LatLngBounds.Builder()
      .include(new LatLng(10, -170))
      .include(new LatLng(-10, 170))
      .build();

    LatLngSpan latLngSpan = latLngBounds.getSpan();
    assertEquals("LatLngSpan should be shortest distance", new LatLngSpan(20, 20),
      latLngSpan);
  }

  @Test
  public void dateLineSpanFrom1() {
    latLngBounds = LatLngBounds.from(10, -170, -10, 170);
    LatLngSpan latLngSpan = latLngBounds.getSpan();
    assertEquals("LatLngSpan should be shortest distance", new LatLngSpan(20, 20),
      latLngSpan);
  }

**Comment by tobrun** [comment]
merged with #10892
