### ISSUE TITLE
Android Marker flat option not working

### ISSUE THREAD

**Issue by pahakorolev** [mapbox/mapbox-gl-native#10867]
**Platform:** Android
**Mapbox SDK version:** 5.3.0

### Steps to trigger behavior

 1. Create `MarkerViewOptions` with `flat` option 
 2. Add created `MarkerViewOptions` to the `MapboxMap`
 3. Rotate the map by the touch rotation gesture

### Expected behavior
The marker should rotate with the map if `flat=true` and the marker should not rotate with map if `flat=false`

### Actual behavior
The marker doesn't rotates along with the map and it does not depend true or false passed to the `flat` option of  `MarkerViewOptions`

![screencapture-1515481200572](https://user-images.githubusercontent.com/6101875/34708510-30546f9a-f524-11e7-9220-0b478d9c2d88.gif)

**Comment by tobrun** [comment]
`flat` means it stays with the map when tilting not when rotating. So this would be a works as designed.
That said, we have deprecated MarkerViews, we highly suggest you moving to SymbolLayer instead.We recently published a blogpost on it, see [here](https://blog.mapbox.com/a-guide-to-the-android-symbollayer-api-5daac7b66f2c).

**Comment by pahakorolev** [comment]
Thanks, but it worked like I described on the old 4 version.
Is there an `flat` option in the `SymbolLayer`? Does it work as I described in the expected behavior?

**Comment by tobrun** [comment]
@pahakorolev yes take a look at the style spec:
 - https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-icon-rotation-alignment
 - https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-icon-keep-upright
 - https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-icon-pitch-alignment
