### ISSUE TITLE
reduce verbosity of metrics

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1087]
Pinged in chat, but the verbosity needs to go down. Right now it's impacting performance during pans and zooms. 

![screen shot 2015-03-24 at 6 27 46 pm](https://cloud.githubusercontent.com/assets/17722/6816662/804751ee-d253-11e4-9479-bf77575ebfdd.png)

**Comment by bleege** [comment]
Resolved in https://github.com/mapbox/mapbox-gl-native/pull/1086.
