### ISSUE TITLE
[qt] app for mapbox qt sdk doenst compile - msvc2015 x64 qt5.10

### ISSUE THREAD

**Issue by diesel437** [mapbox/mapbox-gl-native#10875]
**Platform:** Windows 10 - QtCreator 4.5 - Qt 5.10
**Mapbox SDK version:** source files for example from revision 145a0ee6d0b9f544899bff4d4c67cbf91b470a75

 1. Copied libraries from https://ci.appveyor.com/project/Mapbox/mapbox-gl-native/build/119/artifacts
 2. Created a sample project, added main/mapwindow source files and referenced library and include files.

Build gives me the following error:

- Creating library debug\mapboxgltest.lib and object debug\mapboxgltest.exp
- main.obj : error LNK2001: unresolved external symbol "public: static struct QMetaObject const QMapboxGL::staticMetaObject" (?staticMetaObject@QMapboxGL@@2UQMetaObject@@B)
- mapwindow.obj : error LNK2001: unresolved external symbol "public: static struct QMetaObject const QMapboxGL::staticMetaObject" (?staticMetaObject@QMapboxGL@@2UQMetaObject@@B)
- moc_mapwindow.obj : error LNK2001: unresolved external symbol "public: static struct QMetaObject const QMapboxGL::staticMetaObject" (?staticMetaObject@QMapboxGL@@2UQMetaObject@@B)
- debug\mapboxgltest.exe : fatal error LNK1120: 1 unresolved externals

Odd, seems it wants to create a library?!!

The content of .pro file is:

```
TEMPLATE = app

QT       = core gui network opengl widgets sql

TARGET = mapboxgltest

SOURCES += \
        main.cpp \
        mapwindow.cpp

HEADERS += \
    mapwindow.hpp

INCLUDEPATH += $$PWD/qmapboxgl/include
LIBS += -L$$PWD/qmapboxgl/lib -lqmapboxgl
message($$LIBS) 
```

**Comment by tmpsantos** [comment]
Try adding the `QMapboxGL` headers to the `HEADERS` section of your project. This should not be necessary but worked for me. I'm still investigating why.

**Comment by tmpsantos** [comment]
BTW, I did something similar here to see to map the dependencies for a self contained Mapbox GL Qt app:
https://www.dropbox.com/s/dkrzjfxp2vntdoc/mapboxgl.zip?dl=0

**Comment by tmpsantos** [comment]
Fix here https://github.com/mapbox/mapbox-gl-native/pull/10869

**Comment by diesel437** [comment]
Hi, Im still having issues running the demo app.
Now it builds correctly but when I run, it crashes with the following messages:

```
Starting D:\Projetos\build-mapboxgltest-Desktop_Qt_5_10_0_MSVC2015_64bit-Debug\debug\mapboxgltest.exe...
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
QEventLoop: Cannot be used without QApplication
QEventLoop: Cannot be used without QApplication
QEventLoop: Cannot be used without QApplication
QObject::connect: Cannot connect (null)::aboutToQuit() to QNativeWifiEngine::closeHandle()
The program has unexpectedly finished.
The process was ended forcefully.
D:/Projetos/build-mapboxgltest-Desktop_Qt_5_10_0_MSVC2015_64bit-Debug/debug/mapboxgltest.exe crashed.
```
**Platform:** Windows 10 - QtCreator 4.5 - Qt 5.10
**Mapbox SDK version:** source files for example from revision 4fc070dcfd84324d2596a748f3bb815a2e4a7b5f
Artifact downloaded from build [341](https://ci.appveyor.com/project/Mapbox/mapbox-gl-native/build/341)

**main.cpp**

```
#include "mapwindow.hpp"
#include <QApplication>

int main(int argc, char **argv)
{
    QApplication app(argc, argv);

    QMapboxGLSettings settings;
    settings.setCacheDatabasePath("mbgl-cache.db");
    settings.setCacheDatabaseMaximumSize(20 * 1024 * 1024);

    MapWindow window(settings);

    window.resize(800, 600);
    window.show();

    if (argc == 2 && QString("--test") == argv[1]) {
        window.selfTest();
    }

    return app.exec();
}
```

Any ideas?

**Comment by tmpsantos** [comment]
@diesel437 it seems correct to me. I can reproduce this one on Windows or Linux. :-/

**Comment by diesel437** [comment]
[mapboxgltest.zip](https://github.com/mapbox/mapbox-gl-native/files/1682475/mapboxgltest.zip)

I know you said it seems correct to you.. but, could you take a look and help me understand why it wont work with this simple test case?

Maybe some special dll is needed to run 64bit apps with mapboxgl?

**Comment by tmpsantos** [comment]
@diesel437 This is a self contained build I made with all the DLLs you need to pack for shipping a 64-bit MSVC build. It works just fine here.

[mapboxgl.zip](https://github.com/mapbox/mapbox-gl-native/files/1691225/mapboxgl.zip)

**Comment by diesel437** [comment]
Hi,
Just letting you know I finally found what was happening!
Turns out I was trying to run a debug build using those artifacts that are build in release mode.
So this was causing the issue.
Lesson: Never mix debug and release builds!!

**Comment by tmpsantos** [comment]
@diesel437 glad to hear that you got it working, thanks for the feedback.
