### ISSUE TITLE
tilejson-default render test failure

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native#10880]
Saw a failure on the "recycle-map" build:

https://circleci.com/gh/mapbox/mapbox-gl-native/56081?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

/cc @asheemmamoowala @kkaefer

**Comment by kkaefer** [comment]
This happens more frequently; what does a fix for this look like?
