### ISSUE TITLE
Android Firebase tests take too long to complete

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#10883]
The `android-debug-arm-v7` build on CircleCI currently takes ~20-35 minutes to complete, even for cached builds. This is by far the longest running CI build — all other builds take ~12 minutes clean and less than 10 minutes cached.

If the attempts to run on Firebase somehow fail (recently ~5-10?% of the time), `android-debug-arm-v7` can take [an hour to finish](https://circleci.com/gh/mapbox/mapbox-gl-native/56154). 👴 

![screen shot 2018-01-09 at 5 16 53 pm](https://user-images.githubusercontent.com/1198851/34746125-ef3de35a-f560-11e7-8b85-a08f6d5387b3.png)

/cc @tobrun

**Comment by tobrun** [comment]
Thanks for writing this up. It seems that this issue is twofold:
 - the time to execute the 561 tests on firebase from circle 
 - instability with circle/firebase integration

For the former, I will look into analysing where the build is spending the most of the time and will look into limiting the amount of tests executed.

For the latter, it's the first time that I have seen this issue. This is not supposed to happen as the circle configuration forces a timeout of 1200 seconds (20 minutes). Not sure if we can do a lot around this issue other than to contact circle CI.

**Comment by friedbunny** [comment]
> This is not supposed to happen as the circle configuration forces a timeout of 1200 seconds (20 minutes).

Looking through Circle’s docs, I don’t see a regular timeout — just `no_output_timeout`. 😬

**Comment by tobrun** [comment]
I wasn't aware that there was a difference @friedbunny. Thank you for pointing that out. That said, I looked into the linked build and I'm seeing that Firebase wasn't able to allocate us a device so the tests were postponed for 30 minutes. I punt on that this is a Firebase issue and there is nothing to be done from our end.

On the amount of time for tests to execute, I don't feel there is legitimate case of lowering the amount of instrumentation tests for the sake of you being able to merge your PR faster.These tests help us detect and prevent regressions. I highly encourage you to bring these kind of tests to iOS and macOS as well.

**Comment by tobrun** [comment]
Here is an analysis of an [example](https://circleci.com/gh/mapbox/mapbox-gl-native/57136) build:

Total execution time was **24:30** and the step for firebase took **12:49**, this means that if we would remove the firebase step completely we would still be the longest running job with **11:31**. 

Total execution time for the Firebase step was **12:49**, from which:
  - ~4 minutes was spend on initialisation and installing the application
  - 7 minutes was spend on executing the tests
  - remainder of the time was spend on downloading and interpreting the results

@friedbunny, which next actions do you want to see taken to resolve this issue?

**Comment by friedbunny** [comment]
I definitely think these tests are valuable and worth running, but long run times for every build on CI harms everyone’s productivity, slows iteration between changes, and consumes resources. A single extra-long build also largely negates caching and speed improvements that other builds have made.

### Possible solutions

Here are some high-level ideas that we can mix/match:

- **Nightly or scheduled builds:** Move long-running and/or specialized tests to nightly or scheduled builds. CircleCI jobs are able to be [scheduled via cron.](https://circleci.com/docs/2.0/configuration-reference/#schedule)

- **On-demand or filtered builds:** Use magic words in a commit message or comment here on Github to trigger a long-running build. E.g., commits with `[android]` or `run-firebase` (or whatever).

- **Split into separate fast/slow builds:** Run a minimal suite of tests for every commit, then trigger a more comprehensive suite manually for PRs that warrant more scrutiny.

**Comment by tobrun** [comment]
The first option is not viable as it's doesn't prevent regressions, it only detects them when it already too late. The third option is not viable as all tests are equally important.

I'm okay with the second option when it comes to platform filtering. Note that we would have to read out all commit messages from a PR and check for `android`, `core` and `all` as just validating for `android` only is not enough. Looking forward to the PR.

**Comment by tobrun** [comment]
In #10909 I'm changing the device under test to a more recent model. This should improve the the time it takes for firebase to assign us a device as we were still using a 2014 model.

**Comment by friedbunny** [comment]
Awesome, thanks @tobrun. I’ll start looking at ways to implement Option 2 — I think it’ll turn out to be more of a cultural (rather than technical) challenge, figuring out a system that works for our multi-platform monorepo that balances safety, discoverability, and productivity. 🤔
