### ISSUE TITLE
adjust iOS callout offsets for screen edges

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1089]
Background in https://github.com/mapbox/mapbox-gl-native/pull/1074#issuecomment-85766309. This needs to account both for would-be offscreen callouts with `SMCalloutView`'s repositioning delay, as well as would-be obscured callouts with navigation and/or toolbars on a view controller via `constrainedInsets`.

**Comment by maciekish** [comment]
cc @zakay

**Comment by 1ec5** [comment]
Related: #3249.

**Comment by lilykaiser** [comment]
Closing due to ticket age. If this is still a problem, please re-open

**Comment by 1ec5** [comment]
The issue persists, but #3249 is the preferred solution.
