### ISSUE TITLE
Heading tracking gets backed up when the user moves and rotates simultaneously

### ISSUE THREAD

**Issue by pushian** [mapbox/mapbox-gl-native#10906]
**Platform: iOS
**Mapbox SDK version: binary "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json" ~> 3.7

### Steps to trigger behavior

 1. self.mapView.userTrackingMode = .followWithHeading
 2. walk around with the map

### Expected behavior
The user location marker should moving together with the user with certain accurancy

### Actual behavior
The user location marker is moving slower than the actual movement and after a while, the marker will be far behind the user's current location. And if the user stops, the marker will then slowly catch up first and at last will has a speed up to the user's stopping location.
In the .none Mode, it is working fine which means the location marker is moving smoothly and seamlessly with the user's actual location

**Comment by 1ec5** [comment]
This is the behavior described in https://github.com/mapbox/mapbox-gl-native/issues/3625#issuecomment-173128298. This would be fixed as a side effect of supporting concurrent animations instead of canceling the current animation when beginning a new one: #3625.

**Comment by 1ec5** [comment]
Closing in favor of #3625.
