### ISSUE TITLE
IllegalStateException during initialization

### ISSUE THREAD

**Issue by Orbyt** [mapbox/mapbox-gl-native#10900]
This issue was reported last year, and mentioned in the following locations:

Reported:  https://github.com/mapbox/mapbox-gl-native/issues/9649
Supposed fix: https://github.com/mapbox/mapbox-gl-native/pull/9658

The fix simply wrapped initialization in a `try/catch` block:

```
try {
    MapboxTelemetry.getInstance().initialize(
    appContext, accessToken, BuildConfig.MAPBOX_EVENTS_USER_AGENT, locationEngine);
} catch (Exception exception) {
    Timber.e(exception, "Unable to instantiate Mapbox telemetry");
}
```

While this mitigated the crash, it does not fix the core issue regarding the changes in Android Services introduced Android Oreo, and described [here](https://stackoverflow.com/a/46771000/3917064) as well as in the documentation.

This issue was referenced in the [mapbox-java](https://github.com/mapbox/mapbox-java)  repository here: https://github.com/mapbox/mapbox-java/issues/527. However, this issue was closed in October without any reference to a fix.

Was this issue actually resolved? If so, where? As far as I can tell, the `try/catch` block is still in place, and is mitigating crashes, while the core issue remains.

**Platform:** Android
**Mapbox SDK version:** 5.0.2/5.3.1

**Comment by tobrun** [comment]
@Orbyt could you elaborate how this issue is impacting you? MapboxTelemetry is not a developer facing feature and it doesn't impact the ability of using the maps library. That said, we are working on a new version of MapboxTelemetry that will workaround the limitations set by Android Oreo.

**Comment by Orbyt** [comment]
@tobrun We noticed a large spike in crashes with users running Android Oreo, similar to the initial report in [#9694](https://github.com/mapbox/mapbox-gl-native/issues/9649).

We're concerned that the fix implemented by Mapbox in [#9658](https://github.com/mapbox/mapbox-gl-native/pull/9658) is only temporary, as it does not appear fix the core issue.

In regards to "MapboxTelemetry is not a developer facing feature", while not necessarily relevant, note that `MapboxTelemetry` is public, and methods like `MapboxTelemetry.getInstance().setTelemetryEnabled()` are available to the developer and noted in your Javadocs.

**Comment by tobrun** [comment]
This issue is going to be fixed upstream in https://github.com/mapbox/mapbox-events-android, by replacing background service with a JobScheduler equivalent setup. We are aiming to ship this with an upcoming major release. Thank you for reaching out!

**Comment by boundsj** [comment]
Since the issue is because of a dependency, let's track this issue there in https://github.com/mapbox/mapbox-events-android/issues/55.
