### ISSUE TITLE
OfflineRegion.OfflineRegionStatusCallback is not invoked if not viewing a map or downloading

### ISSUE THREAD

**Issue by masterjefferson** [mapbox/mapbox-gl-native#10902]
**Platform: Android**
**Mapbox SDK version: 5.3.1**

### Steps to trigger behavior

 1. Obtain an `OfflineRegion` list from the `OfflineManager`
 2. Ensure no map is visible, and no region download is in progress.
 3. Attempt to get a region's status using `OfflineRegion.getStatus()`.

### Expected behavior

The `OfflineRegionStatusCallback` should be invoked with either a status or error.

### Actual behavior

Nothing happens. In fact, the only time these callbacks seem to fire correctly is when transitioning out of the calling activity, a map view is being rendered on screen, or a download is already in progress.

This has been observed on API 19, 25, 26, and 27.

**Comment by tobrun** [comment]
Adding this to the milestone for the upcoming patch release. As workaround for now you can call `FileSource.getInstance().activate()` to be able to get the status without the prerequisites.

**Comment by masterjefferson** [comment]
Thank you!
