### ISSUE TITLE
Profile SDK performance on CI

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#10917]
Proposal to start capturing metrics around UI performance and memory allocation on CI. Being able to pinpoint performance degradation or memory growth in time is useful to pinpoint regressions.

### Measuring UI Performance

By using a tool as

> adb shell dumpsys gfxinfo <PACKAGE_NAME>

It's possible to measure get aggregated framestats:

```xml
Stats since: 752958278148ns
Total frames rendered: 82189
Janky frames: 35335 (42.99%)
90th percentile: 34ms
95th percentile: 42ms
99th percentile: 69ms
Number Missed Vsync: 4706
Number High input latency: 142
Number Slow UI thread: 17270
Number Slow bitmap uploads: 1542
Number Slow draw: 23342
```

It's also possible to get more precise framing time info with:

>adb shell dumpsys gfxinfo <PACKAGE_NAME> framestats

This prints out data that later can be pasted in a spreadsheet tool:

![image](https://user-images.githubusercontent.com/2151639/34876578-7ad4aae6-f7a2-11e7-9f6c-5a0ff30526eb.png)

### Memory allocation

With Android Studio 3.0 tooling it's now possible to see where which memory was allocated and make a distinction what amount of memory was used for graphics, native and java.

![screenshot from 2018-01-12 14-44-24](https://user-images.githubusercontent.com/2151639/34877643-26a4a426-f7a7-11e7-9109-5d6d970306b7.png)

## Integration in CI

To be able to run these kind of tests on AWS or Firebase we need integration through JUnit rules so we can run them as part of an espresso instrumentation test. Examples of such rules can be found in [android-perf-testing](https://github.com/googlecodelabs/android-perf-testing/tree/master/app/src/androidTest/java/com/google/android/perftesting/testrules). More information in this performance codelab [here](https://codelabs.developers.google.com/codelabs/android-perf-testing).

**Comment by tobrun** [comment]
a MVP for this would look like:

Circle-CI job that:
 - Pulls in latest code from master
 - Builds SDK and test app in release mode
 - Runs performance test on device from AWS device farm*
 - Pulls output files with AWS cli 
 - Publishes results to an AWS s3 bucket

\* = if tools in OP aren't optimised to integrate easily, let's move forward with a simple FPS counter test as 9b190e272e39fb34a32af5fbe269d2a9bcae4bd7, write the average fps to a file on the device that we later can pull.

**Comment by tobrun** [comment]
This is ongoing but in a separate repo

**Comment by lukaswelte** [comment]
@tobrun could you link the repo? I would be very interested in having a look on it

**Comment by tobrun** [comment]
Sadly this is a private repo.
