### ISSUE TITLE
Can't control the z-Position of Polylines relative to layers

### ISSUE THREAD

**Issue by rm3dbeckers** [mapbox/mapbox-gl-native#10912]
I've just run into a problem, that occurs when I mix polylines and other (Line)Layers.
First of all it took me a while to realize that after (re)calling setStyleUrl, I not only have to readd all my sources, images and layers, but I also have to wait with it until the DID_FINISH_LOADING_STYLE event occured.
Having added some Polylines before, doesn't seem to be a problem though, as they seem to be something different from a "Layer" and even after setStyleUrl, they are still visible (i.e. the layers from the style seem to be added BELOW the polylines). But if I then go ahead and manually create some sources and (line)layers, they are all added on top of the polylines (which is what I am trying to prevent).
I couldn't really find a way to use addLayerAt, addLayerBelow or addLayerAbove such that I could avoid this issue. And removing the polylines and recreating them from their options, whenever I add a layer, doesn't seem right as well.

**Platform: Android**
**Mapbox SDK version: 5.3.0**

### Steps to trigger behavior

 1. Add Polylines to the mapview.
 2. Call setStyleUrl (with a valid style url).
 3. Create overlapping sources and (Line)Layers.
 4. You will observe that the polylines are rendered above the layers from the style (at least this happens with my RasterLayers in the style), but the LineLayers will be rendered above the polylines (since they are added afterwards).

### Expected behavior
There should be other methods than the order in which polylines and layers are added, to control their z-order.

### Actual behavior
I couldn't find any elegant way to always have my polylines on top.

**Comment by tobrun** [comment]
Thank you for reaching out, for more fine granular control you will have to use the runtime style equivalent components:
 - FillLayer = Polygon
 - LineLayer = Polyline

When adding these layers to the map, you are able to pass in where they should be added (eg. before/after a certain layer). We are currently working on bringing more z order support for annotations but for now you will have to work with the Layer concept.

**Comment by rm3dbeckers** [comment]
Alright, thx.
