### ISSUE TITLE
None of your spec sources contain a spec satisfying the dependency: `Mapbox-iOS-SDK (~> 3.7.3)`

### ISSUE THREAD

**Issue by Dhvl-Golakiya** [mapbox/mapbox-gl-native#10929]
Hi,

As per Mapbox ios documentation, the current version is 3.7.3 but when I try to install 3.7.3 with Cocoapods, I am  getting this error:

[!] Unable to satisfy the following requirements:

- `Mapbox-iOS-SDK (~> 3.7.3)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Mapbox-iOS-SDK (~> 3.7.3)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

Podfile:
```
target 'MapStyleDemo' do
pod 'Mapbox-iOS-SDK', '3.7.3’
end
```
I am using 
- Cocoapods version 1.3.1
- Xcode 9.2

**Comment by friedbunny** [comment]
Our spec on CocoaPods [is updated properly for 3.7.3](https://github.com/CocoaPods/Specs/blob/master/Specs/a/5/9/Mapbox-iOS-SDK/3.7.3/Mapbox-iOS-SDK.podspec.json), so this is very likely a local problem. Try following the advice in the error message (particularly, `pod repo update`).
