### ISSUE TITLE
The marker with the Symbol layer is flashed when zooming in/out

### ISSUE THREAD

**Issue by mappy-mobile** [mapbox/mapbox-gl-native#10927]
**Platform: Android**
**Mapbox SDK version: 5.3**

### Steps to trigger behavior

 1. Create the marker with the symbol layer 
 2. Zoom in/out the map

### Expected behavior
The marker isn't flashed

### Actual behavior
The marker is flashed (see at the end of the video)
[device-2018-01-15-172744.mp4.zip](https://github.com/mapbox/mapbox-gl-native/files/1632376/device-2018-01-15-172744.mp4.zip)

**Comment by LukasPaczos** [comment]
Thanks for reaching out @mappy-mobile. Fix for this issue landed on `master` with https://github.com/mapbox/mapbox-gl-native/pull/10899 and will be a part of our next major release. In the meantime feel free to test it out with `6.0.0-SNAPSHOT`.

**Comment by StasDoskalenko** [comment]
@LukasPaczos Hey! This issue still present on iOS 3.7.5 (didn't test on Android yet)
https://monosnap.com/file/hGhL1GuJaRCGIIVSRIIFfw4ziLoAC9
