### ISSUE TITLE
setLocationEnabled in android is deprecated since 5.2

### ISSUE THREAD

**Issue by alaaodeh95** [mapbox/mapbox-gl-native#10922]
**Platform:** Android 
**Mapbox SDK version:** 5.3

Is their any alternative for that ?, and is there a feature for android to show an arrow on the location to indicate the user direction ?

**Comment by rakuishi** [comment]
You can use location-layer plugin instead of deprecated location view.
https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-locationlayer

**Comment by LukasPaczos** [comment]
`LocationLayerPlugin` is our supported way of displaying user's location on the map from now on, thanks @rakuishi for linking to the repo!
