### ISSUE TITLE
[iOS] missing bundle image assets

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#10926]
**Platform: iOS**
**Mapbox SDK version: 3.x (6/7)**

### Steps to trigger behavior

 1. Build mapbox static or get official framework
 2. Link to app
 3. Launch app

### Expected behavior
Map loads correctly

### Actual behavior
Crash on missing images asset (MGLResourceNotFoundException).

=> the images are not copied during the build phase in the bundle. They are added to the Xcode project correctly, but Xcode does not copy the xcasset file with the images.

**Comment by RomainQuidet** [comment]
Seems that Xcode 9 does not copy Images.xcassets in bundle target ... strange !

**Comment by RomainQuidet** [comment]
Sorry, they are now in the assets.car.

https://stackoverflow.com/questions/46429157/xcode-9-no-longer-copies-xcassets-into-bundle-target

**Comment by username0x0a** [comment]
It seems like Xcode 11 sometimes fails to copy over the resources to the `Assets.car` when building the `dynamic` target, causing a runtime crash as mentioned above. I will follow the issue and try getting some additional info or a behavioural pattern causing this.
