### ISSUE TITLE
OnCameraIdleListener not working as expected

### ISSUE THREAD

**Issue by novodimaporo** [mapbox/mapbox-gl-native#10923]
**Platform: Android**
**Mapbox SDK version: 5.2.1** 

### Steps to trigger behavior

 1. Make a simple activity with a mapview, attach an OnIdleListener onMapReady to print Log.
 2. Run the app.
 3. Start panning and zooming.

### Expected behavior
Log should be printed in every end of camera movement.

_From the docs:_
_Adds a callback that is invoked when camera movement has ended._

### Actual behavior
**Panning**
Logs are printed after the user lift its finger to the screen while performing a fling gesture, another log is printed on the end of camera movement.

**Zooming**
Logs are printed after the user lift its finger to the screen while performing a zoom gesture, and not on the end of camera movement.

[I attached a video that demonstrates this here](https://drive.google.com/file/d/1RoGn8wNyBei6l6KAxJ8PxeJ7vzEpI071/view?usp=sharing)

**Comment by kjkrum** [comment]
I'm still seeing this in 6.1.1.  The camera idle listener is called once on a move, twice on a fling, and 3-6 times on a pinch zoom.

**Comment by LukasPaczos** [comment]
@kjkrum tracking this in https://github.com/mapbox/mapbox-gl-native/issues/12260.
