### ISSUE TITLE
Layers disappear after style change

### ISSUE THREAD

**Issue by 2Rec** [mapbox/mapbox-gl-native#10930]
**Platform:*Android*
**Mapbox SDK version:*5.3.1*

### Steps to trigger behavior

 1. Add any Layer by: 
map.addSource(source);
map.addLayer(layer);
Layer is displaying.
 2. Now change mapStyle:
for example:
 mapboxMap.setStyleUrl(Style.SATELLITE);

### Expected behavior
Everything displaying correct.
### Actual behavior
Actually map doesn't display layers added before style changing.

Current solution for me is to remove layers before style change and add them after this operation.

**Comment by tobrun** [comment]
@2Rec there seems to be a misconception from your end. Style is the root component and adding Layers/Sources to MapboxMap will add them to the loaded style. If you load a new style, you will have to recreate your layers and sources and add them agian. 

Actual behaviour is a work as designed, UX improvements around this will be done in https://github.com/mapbox/mapbox-gl-native/issues/9338.
