### ISSUE TITLE
Feature request: Attribution button interaction

### ISSUE THREAD

**Issue by andrei-cimpan** [mapbox/mapbox-gl-native#10932]
**Platform: Android**

Hello,
Could you please implement a mechanism (a listener would be easy) to get notified when the attribution dialog is displayed and hidden?
I'm creating a map-game with a timer, and I would need to pause the timer when the player taps the attribution button. 

Thanks

**Comment by tobrun** [comment]
@andrei-cimpan you are able to roll your own attribution as long as you are compliant with our terms and conditions. With this custom implementation you are able to provide a hook for pausing/resuming your game (at that time you can reuse the dialog we are showing). I don't feel the proposed use-case fulfils the requirements to be able to expose this as an api.

**Comment by andrei-cimpan** [comment]
@tobrun Thanks for the answer. I know there is a method to show the dialog on iOS [MGLMapView showAttribution:], but I didn't find the correspondent one on Android. Do you know where is located, so I don't have do implement the dialog from scratch?

**Comment by tobrun** [comment]
You are correct that we don't expose such that API though that would make sense for these kind of cases.  For now you can, after the map has loaded, add a click listener to the button that overrides the SDK default behaviour:

```
findViewById(R.id.attributionView).setOnClickListener(this);
```

You can copy/paste the code from AttributionManager into your project and hook it up to the click listener.

I'm reopening this issue to expose the same API as iOS.
