### ISSUE TITLE
iOS equivalent to Android setOnPolylineClickListener

### ISSUE THREAD

**Issue by bradmartin** [mapbox/mapbox-gl-native#10934]
**Platform:**
iOS
**Mapbox SDK version:**
pod 'Mapbox-iOS-SDK', '~> 3.7.3'

Unfortunately, this isn't an issue, I've tried [stackoverflow here](https://stackoverflow.com/questions/48246522/mapbox-ios-equivalent-to-android-setonpolylineclicklistener) and it bugs me even opening an issue on the repo 😢 so apologies from me.

I've been working with the SDKs for sometime now and am very familiar with android but iOS is not my strong suit and being more comfortable with java/android its hard for me to follow iOS naming conventions and the other bits. At any rate, my question is in the SO post and I'm looking for a way to define some click/tap event on polylines and polygons when they're added to the map. Android provides the clickListeners to set it but I cannot find an approach for iOS. I've poured over the docs so if this is in there I'd gladly accept a link response to silence me 😄 .

Here is how I'm adding the source to the map and it does get added just fine but of course now I have no clue on how to approach setting up a click listener for that polyline (I'm working on adding polygons too but not there yet).

``` typescript
 const shape = MGLShape.shapeWithDataEncodingError(
        geo,
        NSUTF8StringEncoding
      );
      const source = MGLShapeSource.alloc().initWithIdentifierShapeOptions(
        polylineID,
        shape,
        null
      );
      theMap.style.addSource(source);

      const layer = MGLLineStyleLayer.alloc().initWithIdentifierSource(
        polylineID,
        source
      );
```

**Comment by jmkiley** [comment]
Hi @bradmartin -

If you are using the Maps SDK for iOS, you can use [`-mapView:didSelectAnnotation:`](https://www.mapbox.com/ios-sdk/api/3.7.3/Protocols/MGLMapViewDelegate.html#/c:objc(pl)MGLMapViewDelegate(im)mapView:didSelectAnnotation:) to handle taps on a `MGLPolyline`. 

With a `MGLLineStyleLayer`,  you will need to implement a tap gesture recognizer that [accesses visible features](https://www.mapbox.com/ios-sdk/api/3.7.3/Classes/MGLMapView.html#/Accessing%20the%20Underlying%20Map%20Data). Hope this helps!

**Comment by bradmartin** [comment]
Yes, thank you very much @jmkiley - it pained me to open this issue 😞 but I very much appreciate the answer.
