### ISSUE TITLE
[iOS 3.7.3] why did remove or add annotations would perform regionDidChangeAnimated

### ISSUE THREAD

**Issue by iseeicando** [mapbox/mapbox-gl-native#10941]
（sorry for my pool English ：）））

I removed and added some annotations in mapView:regionDidChangeAnimated:
then i found mapView:regionDidChangeAnimated: would be recursive  called for many times。
I upload an picture  ，I don't know if this is BUG

![c1e324bc-3e33-4a6f-b02a-71e350cb32af](https://user-images.githubusercontent.com/18023018/35034113-047d5988-fba8-11e7-9c3a-64ac219f989c.png)

**Comment by kehlawler** [comment]
I seem to be having a similar problem which eventually puts the main thread in a mutexwait state and my app hangs.
![screen shot 2018-01-22 at 12 52 18 pm](https://user-images.githubusercontent.com/8228577/35244173-1f97bc5c-ff74-11e7-8211-e11946162655.png)

**Comment by kehlawler** [comment]
Reverting back to version 3.6.3 the problem no longer exists

**Comment by jfirebaugh** [comment]
Tracking in #11180.
