### ISSUE TITLE
Harden detached sources/layers

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#10947]
A typical source of crashes is when a user loads a new style and tries to call methods on sources/layers that were attached to previous style. I think the issue at hand is twofold:
 - conceptually it's not clear that a style is the owner of the underlying sources/layers and when you call `MapboxMap#addLayer()` it feels like MapboxMap owns it and it's valid as long as the MapView lives. This API change is ticketed out in https://github.com/mapbox/mapbox-gl-native/issues/9338.
 - it crashes the application but doesn't give any clear insight on what went wrong. To close this issue I'm proposing to track the detachment of a source/layer and either throw an exception to prevent core from crashing or ignore any method calls for detached sources/layers.

**Comment by LukasPaczos** [comment]
Closed by https://github.com/mapbox/mapbox-gl-native/pull/13484.
