### ISSUE TITLE
Feature Request (IOS): Need to fetch all the features from source-layers, despite of viewport or region.

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [mapbox/mapbox-gl-native#10958]
We have a scenario in which we need to fetch all the features from vector source layers. 

There is an option to do that https://www.mapbox.com/ios-sdk/api/3.7.3/Classes/MGLVectorSource.html#/c:objc(cs)MGLVectorSource(im)featuresInSourceLayersWithIdentifiers:predicate 

But with the following restrictions,

1.) Only, fetching features from source associated with a layer that was recently used.
2.) And, features were in the bounds of a recently scrolled to region.

If it's possible can you guys implement this option in further releases.

Thanks.

**Comment by jfirebaugh** [comment]
Sorry, those are limitations we're unlikely to lift. If you need to obtain features that are outside the bounds of the currently rendered map, you'll need to implement that yourself.

**Comment by ThiyagarajanShivSankaran** [comment]
@jfirebaugh Can you tell me how to do that. Or any suggestion please. We really need to implement this functionality in our app.Thanks.

**Comment by ThiyagarajanShivSankaran** [comment]
Hello, Is anyone help me out with this??
