### ISSUE TITLE
More then one file was found with OS independent path in android using 5.3.1 mapbox SDK version

### ISSUE THREAD

**Issue by HirenBharodiya** [mapbox/mapbox-gl-native#10968]
Hi,
I am Hiren Bharodiya, here I am facing issue with 5.3.1 map box SDK version while building in Fusetools. 

When I was using the older version(5.2.0-beta.1) of map box SDK, it was working fine. but at this time when I upgrade SDK of map box to 5.3.1 version, there is not running application properly

**Fusetools**
**Mapbox SDK Version 5.3.1**

### Steps to trigger behavior

 1.when I was using 5.2.0-beta.1 SDK in Fusetools, it was running successfully
 2.After that, I upgraded SDK version to 5.3.1 which is latest SDK version
 3.As of now, I am facing Issue with this latest SDK version of map box

**Issue** 
Here, I generating issue as I derived below.
```
Error:Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/armeabi-v7a/libgnustl_shared.so'
```

### Expected behavior
-There should be display map properly on android device
### Actual behavior
-Even, there is not running application 

I have also share link to Fusetools sample project for better understand
https://www.dropbox.com/s/nb8vp1zrnoli30n/MapBoxSample.zip?dl=0

**Comment by tobrun** [comment]
@HirenBharodiya thank you for reaching out, the referenced file `libgnustl_shared.so` is not a shared object from this SDK. Please open an issue in the repo where that file is coming from. Closing as not directly related to this repository.
