### ISSUE TITLE
Symbol not hiding symbols below on mobile

### ISSUE THREAD

**Issue by Jukurrpa** [mapbox/mapbox-gl-native#10973]
**Platforms:** Android 5.3.1 & iOS 3.7.2

#### Steps to reproduce:
 1. Use two symbol layers, the one below with some symbols here and there. All placement options (allow icon overlap, etc) are off on both layers
 2. Add a symbol on the top layer at the same location as one from the bottom layer

The newly added symbol should make the nearby symbols of the layer below disappear, but it doesn't. This works properly in Mapbox Studio and on the web, but on both mobile versions the symbols stay. The issue also exists when just toggling the visibility of the top layer.

In our use case when the user clicks on a symbol, we add another one add the same location on a layer above.

Expected behavior (result in Mapbox Studio and web):

![studio-hidden](https://user-images.githubusercontent.com/341072/35179420-d7bbb162-fd4e-11e7-95ea-670ff209d0ad.png)
![studio-visible](https://user-images.githubusercontent.com/341072/35179421-dc8c45c6-fd4e-11e7-8496-4cbdb0531f61.png)

Issue (on Android, similar on iOS):

![mobile-hidden](https://user-images.githubusercontent.com/341072/35179436-18a4ba34-fd4f-11e7-82e3-6c70d30d312c.png)
![mobile-visible](https://user-images.githubusercontent.com/341072/35179437-19d67d48-fd4f-11e7-9056-c2f4ef6f802c.png)

As you can see the original pin stays visible on mobile. Both mobile and web used the same style, source and data in this example (text difference is due to the time at which the screenshots were taken). The newly added symbol has a different id, bottom layer uses a vector source, top layer uses a GeoJson source.

**Comment by tobrun** [comment]
@Jukurrpa we recently added symbol placement that takes in account multiple layers in https://github.com/mapbox/mapbox-gl-native/pull/10468. This is aimed to be released with the 6.0.0 release on Android and will fulfil the use-case shown in OP. The first 6.0.0-beta release is planned for the week/early next. (fwiw you can test this behaviour out using the 6.0.0-SNAPSHOT build). Let us know if you have any more questions!

**Comment by Jukurrpa** [comment]
Thanks @tobrun . I take it the change will also be present in the next major release on iOS?

**Comment by friedbunny** [comment]
@jukurrpa Yup, the same thing goes for iOS — this is planned for v4.0.0.

**Comment by Jukurrpa** [comment]
Perfect, thanks!
