### ISSUE TITLE
Loading style failed: HTTP status code 401

### ISSUE THREAD

**Issue by mcichecki** [mapbox/mapbox-gl-native#10976]
**Platform: iOS**
**Mapbox SDK version: **

### Expected behavior
Map is visible

### Actual behavior
Map is white but I can see mapbox logo and `i` icon on the bottom. I know that's token related issue but I've already checked my token on https://api.mapbox.com/v4/mapbox.streets/page.html?access_token= and it worked. Moreover I made sure that there are no white spaces. I'm using default style from the tutorial: `mapbox://styles/mapbox/streets-v10`

Whole message:
App2[10899:403719] [ERROR] {}[Setup]: loading style failed: HTTP status code 401

**Comment by mcichecki** [comment]
after couple of hours I've noticed that there was a typo on my plist file...

**Comment by at-tantv** [comment]
glfw[2323:818983] [INFO] {}[General]: GPU Identifier: SKL Graphics
2018-08-31 15:14:46.003059+0700 mbgl-glfw[2323:818983] [ERROR] {}[Setup]: loading style failed: HTTP status code 401

I build project with macos
I received this error, How to add access token to Macos
Help me

**Comment by kritiagarwal13** [comment]
I'm having the following error:
Offline pack “unknown” has 0 of 1 resources — 0.0%.
Offline pack “unknown” received error: HTTP status code 401

How can I resolve this?
