### ISSUE TITLE
Android crash when device in airplane mode

### ISSUE THREAD

**Issue by aaronblondeau** [mapbox/mapbox-gl-native#10985]
**Platform: Android **
**Mapbox SDK version: 5.3.1**

### Steps to trigger behavior

 1. Add MapView to an Activity
 2. Put device in airplane mode
 3. Open map activity (if you've opened map while online, you may need to pan/zoom to un-cached map area to trigger crash)

### Expected behavior

Instead of crashing the app, the map should just be blank.

### Actual behavior

Nasty native NDK SIGABRT:
```
01-22 09:34:49.251 12766-12790/--- A/libc: /usr/local/google/buildbot/src/android/ndk-r15-release/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type jni::PendingJavaException" failed
01-22 09:34:49.251 12766-12790/--- A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 12790 (DefaultFileSour)
                                                           
                                                           [ 01-22 09:34:49.251   463:  463 W/         ]
                                                           debuggerd: handling request: pid=12766 uid=10218 gid=10218 tid=12790
```

**Comment by tobrun** [comment]
@aaronblondeau do you have more information on this issue? is this reproducible on demand? is it reproducible with latest version 5.4.1?

**Comment by tobrun** [comment]
Haven't been able to reproduce, @aaronblondeau let us know if this is still reproducible with the latest stable version 5.5.0. Closing.
