### ISSUE TITLE
Not responding on returning back from MapActivity

### ISSUE THREAD

**Issue by saran2020** [mapbox/mapbox-gl-native#10980]
**Platform:** Android M
**Mapbox SDK version:** 5.31

### Steps to trigger behavior

 1. Create the Main activity with a button to start MapActivity
 2. Create a MapFragment which contains the MapView
 3. Place the MapFragment inside the MapActivity (not via XML but via code in activity)
 4. Start the app
 5. Go to MapActivity by clicking on the button added in step 1
 6. Wait till the map is loaded in MapFragment in MapActivity
 7. Press back button to return back to the MainActivity from MapActivity
 8. Again try clicking on the Button in MainActivity or perform any action on MainActivity, the activity will not respond.

### Expected behavior
MainActivity should still respond even after returning from the MapActivity.

### Actual behavior
MainActivity not responding after returning from the MapActivity.

[Here](https://github.com/saran2020/MapApplication) is the repo that I created for test.

**Comment by tobrun** [comment]
Thank you for reaching out and backing up this issue with detailed instruction and code. Looking into the code reveals that you are calling `MapView#onDestroy` as part of `Fragment#onDestroy` while it should be hooking into `Fragment#onDestroyView` instead. Changing this should resolve the issue, feel free to communicate back if not. Closing as answered.
