### ISSUE TITLE
Add darwin style code for raster-dem and hillshade 

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-native#10991]
Per https://github.com/mapbox/mapbox-gl-native/pull/10642#discussion_r163034806

> Unfortunately, darwin-style-code is unable to automate the entire process of adding a new layer type, so some changes are still needed before this layer type can be used on iOS and macOS:

After #10642 ships we will need to:

* [x] Implement an MGLRasterDEMSource class
* [x] [Add the new files](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md#adding-a-source-code-file) to the SDKs
   Otherwise the new MGLStyleLayer subclass doesn’t get included in the SDK.
* [x] [Add the new classes](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md#making-a-type-or-constant-public) to the documentation table of contents
   Otherwise the new MGLStyleLayer subclass isn’t listed with the other subclasses in the jazzy documentation.
* [x] [Wrap the new layer type](https://github.com/mapbox/mapbox-gl-native/blob/2d15aed43c9faa875a8f625c3afc286f1175e0ce/platform/darwin/src/MGLStyle.mm#L388) in an Objective-C object in the runtime styling API
   Otherwise the runtime styling API may crash when introspecting the current style.
* [x] [Refine the new class’s documentation](https://github.com/mapbox/mapbox-gl-native/blob/2d15aed43c9faa875a8f625c3afc286f1175e0ce/platform/darwin/scripts/style-spec-overrides-v8.json#L11)
   Otherwise the API reference isn’t self-contained.
* [x] [Add an icon](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/macos/app/StyleLayerIconTransformer.m) to represent this layer type in the sidebar of macosapp
   Otherwise terrain layers look blank in the sidebar.
* [x] Mention the new APIs in the changelogs
   Otherwise iOS developers won’t know about the new feature.

**Comment by 1ec5** [comment]
Added some context to each item, for prioritization purposes.
