### ISSUE TITLE
Raster source maximumZoomLevel does not work

### ISSUE THREAD

**Issue by Yangg1223** [mapbox/mapbox-gl-native#10992]
**Platform: iOS**
**Mapbox SDK version: 3.6.4 & 3.7.3**

### Steps to trigger behavior

 1. Initialise MGLRasterSource with customised data, for example: http://tiles-a.data-cdn.linz.govt.nz/services;key=45e0e2a6c72241f590d555e7e4b13a6f/tiles/v4/layer=88131/EPSG:3857/{z}/{x}/{y}.png, also specify minimumZoomLevel (14) and maximumZoomLevel (16) in options.
 2. Initialise MGLRasterStyleLayer with the source in step 1.
 3. Insert the layer initialised in step 2 into the MapView.style
 4. In my code, the baseLayerId is 'mapbox-mapbox-satellite'. The inserting happens in `func mapView(_ mapView: MGLMapView, didFinishLoading style: MGLStyle)` after the map is switched to satellite style  

### Expected behavior
Customised raster tilejson should be used in minZoom and maxZoom range. When the zoom level is out of the range, customised raster tilejson should go away, and the base layer (mapbox-mapbox-satellite) should be used.

### Actual behavior
minimumZoomLevel works properly, but maximumZoomLevel does not work. After zoom in to larger zoom level than maximumZoomLevel, let's say 17, the raster tile does not go away, it does not try to download tile pics at z17    ###neither.

### Code initialising source, layer and inserting the layer
```
for item in layerTilejsonArray {
    let source = MGLRasterSource(identifier: item.id, tileURLTemplates: item.source.tiles, options: [
        .minimumZoomLevel: 14,
        .maximumZoomLevel: 16,
        .tileSize: 512
     ])
     let rasterLayer = MGLRasterStyleLayer(identifier: item.id, source: source)
     style.addSource(source)
     let baseLayer = style.layer(withIdentifier: item.basedLayerId)
     if baseLayer != nil {
         style.insertLayer(rasterLayer, above: baseLayer!)
     }
}
```

**Comment by asheemmamoowala** [comment]
@Yangg1223 This behavior is as expected.

The min/max zoom level for the source indicates the zooms for which tile data is available. The visibility of source layers is controlled by the `maximumZoomLevel` and `minimumZoomLevel` properties of the `MGLRasterStyleLayer.`
