### ISSUE TITLE
[MGLSnapshot pointForCoordinate:] returns a wrong image point.

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/mapbox-gl-native#11003]
**Platform:** iOS/macOS
**Mapbox SDK version:** 3.7.3

### Steps to trigger behavior

 1. Create a `MGLMapSnapshotter`
 2. Execute `[snapshotter startWithCompletionHandler: ^(MGLMapSnapshot* snapshot, NSError *error)`
 3. In the enclosing block try to obtain the image center:
`CGPoint center = [snapshot pointForCoordinate:options.camera.centerCoordinate];`

### Expected behavior
If you pass any coordinates that is within the bounds of the snapshotter get the correct image point.
### Actual behavior
You get a wrong point.

Test code:
```
    MGLMapCamera* mapCamera = [[MGLMapCamera alloc] init];
    mapCamera.pitch = 20;
    mapCamera.centerCoordinate = coordinates;
    MGLMapSnapshotOptions* options = [[MGLMapSnapshotOptions alloc] initWithStyleURL:[MGLStyle satelliteStreetsStyleURL] camera:mapCamera size:self.view.bounds.size];
    options.zoomLevel = 10;
    
    MGLMapSnapshotter* snapshotter = [[MGLMapSnapshotter alloc] initWithOptions:options];
    [snapshotter startWithCompletionHandler: ^(MGLMapSnapshot* snapshot, NSError *error) {
        if (error) {
            NSLog(@"Could not load snapshot: %@", [error localizedDescription]);
        } else {
            CGPoint center = [snapshot pointForCoordinate:options.camera.centerCoordinate];
            
        }
    }];
```

/cc @ivovandongen @tobrun

**Comment by tobrun** [comment]
@fabian-guerra as requested I looked into the android example on this, while I think I found a nit bug the value returned from `snapshot#pixelForLatLng` looks correct. Though this seems different as your setup.

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/11035
