### ISSUE TITLE
Add NSExpression syntax for conditionals with multiple branches

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#11007]
The NSExpression-based property value implementation in #10726 should support a more compact syntax for conditionals with multiple branches. Currently, an NSExpression containing a nested `TERNARY` gets converted into nested [`case`](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-case) expressions, and a `case` expression with multiple branches gets converted into a nested `TERNARY` structure. At least a nested `TERNARY` should be converted into a flat `case`.

**Comment by 1ec5** [comment]
@friedbunny pointed out that `+[NSExpression expressionForConditional:trueExpression:falseExpression:]` is unavailable in iOS 8.x, so the proposed syntax would be even more useful for developers that need to deploy back to that version.

**Comment by friedbunny** [comment]
Indeed, besides recommending `+[NSExpression expressionForConditional:trueExpression:falseExpression:]` in the docs a couple times, we use it here:

https://github.com/mapbox/mapbox-gl-native/blob/fb5b8d34f20b696319cfc16838243265143ba972/platform/darwin/src/NSExpression%2BMGLAdditions.mm#L477

and here:

https://github.com/mapbox/mapbox-gl-native/blob/44ca0a5ec4979138514e8dda10dd1b1173dd0db1/platform/darwin/test/MGLExpressionTests.mm#L580

**Comment by 1ec5** [comment]
Fixed in #11450 on the release-boba branch for iOS map SDK v4.0.0 and macOS map SDK v0.7.0.
