### ISSUE TITLE
Convert feature data and lookup expressions to NSExpression

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#11006]
The NSExpression-based property value implementation in #10726 should be able to express the following feature data and lookup operators defined in the style specification:

* [ ] [`geometry-type`](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-geometry-type) – custom `shapeKind` function
* [ ] [`id`](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-id) – custom `id` function
* [ ] [`properties`](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-properties) – custom `properties` function
* [ ] [`at`](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-at) – aggregate expression `array[0]`
* [ ] [`has`](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-has) – aggregate expression `SELF CONTAINS`?

(`get` and `count` are already implemented.)

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/11528
