### ISSUE TITLE
Streamline custom function syntax for NSExpression

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#11015]
As of the initial NSExpression implementation in #10726, we rely on the clunky custom function syntax to represent many of the style specification’s expression operators. For example, string concatenation is a common operation by requires all sorts of undiscoverable and error-prone punctuation:

```swift
NSExpression(format: "FUNCTION('Old', 'stringByAppendingString:', FUNCTION(' ', 'stringByAppendingString:', 'MacDonald'))")
```

As previously proposed in https://github.com/mapbox/mapbox-gl-native/issues/8074#issuecomment-355383677, we should extend the private _NSPredicateUtilities class using the Objective-C runtime:

```swift
NSExpression(format: "mgl_join({'Old', ' ', 'MacDonald'})")
```

This would result in the most natural usage, but it’s also a bit Clever™. We’ll need to [tiptoe around a bit](https://gist.github.com/1ec5/1403a1b35929fc68fb2519902c012f81) to avoid directly using any private APIs, and we’ll need to include safeguards in case the underlying NSExpression implementation changes at any point.

/cc @akitchen @fabian-guerra @jmkiley

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/11472
