### ISSUE TITLE
Add NSExpression syntax for coercing array to color

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#11011]
The NSExpression-based property value implementation in #10726 lacks a way to represent the [`to-rgba`](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-to-rgba) operator for coercing an array into a color, although it does support color values in general.

**Comment by 1ec5** [comment]
#11389 added support for the `rgba` operator but not the `to-rgba` operator. A natural translation of `to-rgba` would be `CAST(…, 'UIColor')` on iOS and `CAST(…, 'NSColor')` on macOS.

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/11725
