### ISSUE TITLE
Add NSPredicate-specific operators to NSExpression

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#11013]
The NSExpression-based property value implementation in #10726 doesn’t support all the same predicate operators (for conditional expressions) that the NSPredicate-based filter implementation supports:

* [ ] `BETWEEN` (equivalent to `>= AND <=`)
* [ ] `IN` (reverse of `CONTAINS`)
* [ ] `CONTAINS` (based on the `has` operator)

/cc @jmkiley @anandthakker

**Comment by 1ec5** [comment]
Most likely blocked by #10720.

**Comment by 1ec5** [comment]
> `CONTAINS` (based on the `has` operator)

To clarify, `CONTAINS` is typically used to check whether an array contains an item. (This is one of the most common predicate operators.) In a JSON expression, `match` would be used for this purpose rather than `has`. `match` supports multiple values in a case, so I’d expect a filter like `["in", 1, 2, 3]` to be translated into `["match", [1, 2, 3], true, false]`. Until we support that syntax in NSExpression (#11539), we’ll need to use the `MGL_FUNCTION` syntax being introduced in #11472.

/cc @fabian-guerra

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/11632
