### ISSUE TITLE
Run cross-platform expression tests against NSExpression

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#11014]
The iOS and macOS test targets should somehow exercise the NSExpression implementation added in #10726 against the [cross-platform expression tests](https://github.com/mapbox/mapbox-gl-js/tree/master/test/integration/expression-tests/) in the GL JS submodule.

As a starting point, we could run all the expressions through `+[NSExpression(MGLAdditions) mgl_expressionWithJSONObject:]` and `-[NSExpression(MGLAdditions) mgl_jsonExpressionObject]` to ensure that these methods round-trip without crashing Foundation’s NSExpression parser. As a longer-term effort, we could supplement the test fixtures with Darwin-specific files specifying the expected NSExpression translation of each JSON-formatted expression.

/cc @akitchen @fabian-guerra @anandthakker

**Comment by akitchen** [comment]
@1ec5 @anandthakker @fabian-guerra 

The code in https://github.com/mapbox/mapbox-gl-native/tree/fb-expression-tests-from-js can be used to run the expressions tests from gl-js against the iOS SDK. I suppose we could open a "do not merge" PR as well.

Once the branch is checked out simply run the tests against the dynamic framework target in the iOS project to see the results.

**Comment by 1ec5** [comment]
The branch above has been PR’d as #11435.
