### ISSUE TITLE
Java Peer RasterDEMSource missing

### ISSUE THREAD

**Issue by femski** [mapbox/mapbox-gl-native#11025]
**Platform:**
Android

**Mapbox SDK version:**
Master Branch

### Steps to trigger behavior
Add a new layer of type HillshadeLayer

### Expected behavior
Brilliant new HillshadeLayer layer

### Actual behavior
Crash

Probable cause: Java Peer RasterDEMSource is not defined so I don't see a way to add DEM layer right now. If you just add normal RASTER layer (RGB terrain) it still leads to segmentation fault in:

line 97: mapbox-gl-native/src/mbgl/renderer/layers/render_hillshade_layer.cpp
assert(dynamic_cast<HillshadeBucket*>(tile.tile.getBucket(*baseImpl)));

Thank you for looking.

**Comment by tobrun** [comment]
@femski you are correct, while layers are automatically generated as part of the style spec code generation, sources as RasterDEMSource aren't and these need to be manually added. I will look into adding integration of RasterDEMSource on the Android binding.

cc @mollymerp

**Comment by femski** [comment]
Similar to #10991

**Comment by tobrun** [comment]
#11031 resolves this issue by adding the RasterDEMSource integration and an example, once merged you can retest with the 6.0.0-SNAPSHOT or master branch. Thank you for reporting this @femski.
