### ISSUE TITLE
Add examples for using hillshade layers in iOS docs

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-native#11034]
Blocked upstream until #11025 #10991 are closed

**Comment by 1ec5** [comment]
#11036 adds a very handwavy example to go in the MGLHillshadeStyleLayer class reference, based on [this GL JS example](https://www.mapbox.com/mapbox-gl-js/example/hillshade/). We could also add a more full-fledged example to the [ios-sdk-examples](https://github.com/mapbox/ios-sdk-examples/) project (which winds up on mapbox.com).

**Comment by 1ec5** [comment]
I think iOS is also covered between #11036 and mapbox/ios-sdk-examples#144. Closing.
