### ISSUE TITLE
Markers and street labels are flickering when changing position of one marker

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#11049]
**Platform:*Android*
**Mapbox SDK version:*5.3.2*

### Steps to trigger behavior

 1. Draw some markers on the map
 2. Get some location updates
 3. Update position of one certain marker after each location update

### Expected behavior

Map is not flickering

### Actual behavior

Each time when I get a new location, I'm updating the location of my 'current location marker':

    `if (myLocation == null) {

                myLocation = map.addMarker(new MarkerOptions()
                        .position(new LatLng(location.getLatitude(), location.getLongitude()))
                        .title("my location")
                        .snippet("")
                        .icon(myLocationIcon));
            }
            else {
                
                myLocation.setPosition(new LatLng(location.getLatitude(), location.getLongitude()));
            }`

Each time I get a new location from GPS provider, myLocation.setPosition is called. This works fine, but everytime position is changing, all other markers (and streetlabels) are 'flickering' (they dissapear for a second and then they became visible again). When removing 'myLocation.setPosition(new LatLng(location.getLatitude(), location.getLongitude()));', the map and other markers don't flicker anymore.

I'm adding approx. 20 markers on the map in this way:

     `Marker marker = map.addMarker(new MarkerOptions()
                            .position(new LatLng(knooppunt.getLocation().getLatitude(), knooppunt.getLocation().getLongitude()))
                            .title("knooppunt")
                            .snippet(gson.toJson(knooppunt))
                            .icon(icon)

                    );`

**Comment by tobrun** [comment]
Thank you for the report @nijs9, this was fixed with https://github.com/mapbox/mapbox-gl-native/pull/10899 and will be available in the upcoming 6.0.0 release. We are aiming to release the first beta build this week.
