### ISSUE TITLE
App crashes when downloading offline region after upgrading to 5.3.2

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#11048]
**Platform:*Android*
**Mapbox SDK version:*5.3.2*

### Steps to trigger behavior

 1. Define OfflineRegion
 2. Download OfflineRegion
 3.

### Expected behavior

Region downloading

### Actual behavior

I upgraded from version 5.1.5 tot 5.3.2. Code for downloading offline region is not working anymore after this upgrade. I'm using the demo code (https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/offline/OfflineManagerActivity.java).

The app crashes after calling offlineManager.createOfflineRegion, and I see this error:

`A/art: art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: JNI GetMethodID called with pending exception java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
A/art: art/runtime/java_vm_ext.cc:470]   at void android.os.Handler.<init>(android.os.Handler$Callback, boolean) (Handler.java:200)
A/art: art/runtime/java_vm_ext.cc:470]   at void android.os.Handler.<init>() (Handler.java:114)
A/art: art/runtime/java_vm_ext.cc:470]   at void com.mapbox.mapboxsdk.offline.OfflineRegion.<init>(long, com.mapbox.mapboxsdk.storage.FileSource, long, com.mapbox.mapboxsdk.offline.OfflineRegionDefinition, byte[]) (OfflineRegion.java:54)`

**Comment by tobrun** [comment]
@nijs9 thank you for the report, this is fixed with https://github.com/mapbox/mapbox-gl-native/pull/11021. As workaround for now you can use 5.3.1 untill 5.3.3 lands.
