### ISSUE TITLE
About android offline map download 

### ISSUE THREAD

**Issue by swsong12** [mapbox/mapbox-gl-native#11056]
**Platform: android**
**Mapbox SDK version: 5.3.2**

Hello Mapbox Team. I have some question and concerns regarding offline map download.

First I noticed that in-app offline Map download was extremely slow. 

Second I haven't seen an option that allows you to download the map into the APK. In other words, I was looking for a way we can download the offline data and store it into our project. This way user doesn't have to go through the download procedure twice. (i.e download app > open >download offline map) Is this feature available now? or will it be available soon in map box?

thanks!

**Comment by tobrun** [comment]
> First I noticed that in-app offline Map download was extremely slow.

We are aware of this and it's a long term goal to decrease the download time for tiles, this is definitely one of the higher priorities. This will probably require revisiting the vector tile specification. 

> Second I haven't seen an option that allows you to download the map into the APK. 

Prepackaging offline downloads is ticketed in https://github.com/mapbox/mapbox-gl-native/issues/3894. 

Thank you for reaching out but I'm closing this issue as the first item is not actionable at the moment, the second was already ticketed out. Thank you for using our product!
