### ISSUE TITLE
Mapbox SDK IOS MGLAnnotationView with Async Image

### ISSUE THREAD

**Issue by JulienLevallois** [mapbox/mapbox-gl-native#11064]
Hi ! I want to user Mapbox to show user on one map. How can i create MGLAnnotationView with images who are downloaded from backend, so async images ?
So when the image is download, i want to update my custom MGLAnnotationView

![image](https://user-images.githubusercontent.com/5727223/35437589-53bf0f54-0293-11e8-876e-f500273853eb.png)

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
