### ISSUE TITLE
Loading slow

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapbox-gl-native#1106]
Using Mapbox GL latest.

Map loads very slow to the point where in the first 15 seconds I am wondering whether the app is dead (I see only grey). Entirely possible my network is slow, but the impression is brokenness as nothing indicates to me that loading is in progress.

**Comment by 1ec5** [comment]
What phone and iOS version are you using?

**Comment by lxbarth** [comment]
Sry, iOS8.1 iPhone6.

**Comment by incanus** [comment]
Cool, let's try a new build tonight and see how it lands.
