### ISSUE TITLE
Location Drawable Attributes not working

### ISSUE THREAD

**Issue by vadimleonov** [mapbox/mapbox-gl-native#11079]
**Mapbox SDK version:**
LocationLayer: 0.3.0
Navigation: 0.9.0
Navigation-ui: 0.9.0
Mapbox-sdk:5.3.2

The problem is that tags 
```
app:mapbox_myLocationBearingDrawable
app:mapbox_myLocationDrawable
```
are not working in this case:

        <com.mapbox.mapboxsdk.maps.MapView
            android:id="@+id/mapView"
            android:layout_width="0dp"
            android:layout_height="0dp"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:mapbox_myLocationBearingDrawable="@drawable/ic_location_placeholder"
            app:mapbox_myLocationDrawable="@drawable/ic_location_placeholder"
            app:mapbox_styleUrl="@string/mapbox_style_mapbox_streets" />

But If I use them in:

```
    <style name="CustomLocationLayer" parent="LocationLayer">
        <item name="backgroundDrawable">@drawable/ic_location_placeholder</item>
        <item name="foregroundDrawable">@drawable/ic_location_placeholder</item>
    </style>

locationPlugin?.applyStyle(R.style.CustomLocationLayer)
```

All is working fine.

**Comment by tobrun** [comment]
You are confusing the deprecated MyLocationView with the newer LocationLayerPlugin. 
These are two different components and have a different configuration setup. 
Closing as non-actionable.

**Comment by vadimleonov** [comment]
I found these attributes in your official sdk guide: https://www.mapbox.com/android-docs/map-sdk/overview/

On the bottom there is link:  "You can always view the full list of MapView attributes here."
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml

And these attributes are not working

**Comment by tobrun** [comment]
There are two different concepts:
 - [MyLocationView](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java#L52) 
 - [LocationLayerPlugin](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-locationlayer)

The first configuration mentioned in OP is related to MyLocationView, the second configuration mentioned in is related to MyLocationLayer plugin. You shouldn't expect the former configuration to work with the latter.
