### ISSUE TITLE
is navigation SDK can be used in unity.if it possible how to use it.please explain

### ISSUE THREAD

**Issue by rajupinnam** [mapbox/mapbox-gl-native#11081]
**Platform:**
**Mapbox SDK version:**

### Steps to trigger behavior

 1.
 2.
 3.

**Comment by captainbarbosa** [comment]
The Mapbox Navigation SDK is currently not supported on the Unity platform. Please note this repository is intended for the development of the Mapbox Maps SDK for mobile platforms only and is not suited for general support questions. In the future, reach out through our [contact page](https://www.mapbox.com/contact/) if you have additional questions about Mapbox products.
