### ISSUE TITLE
can't render image without X  display?

### ISSUE THREAD

**Issue by lihuadong1988** [mapbox/mapbox-gl-native#11086]
./mbgl-render 
Error: Failed to open X display.
mbgl-render: ../../../platform/default/thread_local.cpp:36: mbgl::util::ThreadLocal<T>::~ThreadLocal() [with T = mbgl::Scheduler]: Assertion `!get()' failed.
Aborted (core dumped)

**Comment by jfirebaugh** [comment]
Yes, if you want to use this utility (developer focused, not really a formally supported API), you'll need to ensure that an X display is accessible.

**Comment by lihuadong1988** [comment]
how can i use this library to generate png without display? is this possible？
