### ISSUE TITLE
Noisey logging in TrackingSettings

### ISSUE THREAD

**Issue by colinrtwhite** [mapbox/mapbox-gl-native#11082]
**Platform:** Android
**Mapbox SDK version:** v.5.3.2

### Steps to trigger behavior

 1. Don't request the Location permission.
 2. Call `MapboxMap.initialise` to initialise the map.

### Expected behavior
Nothing should be logged since we didn't request user location tracking.

### Actual behavior
`Could not activate user location tracking: user did not accept the permission or permissions were not requested.` is logged through Timber.

The issue is that the error is always logged even if we don't need to request the user's location.
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/TrackingSettings.java#L376

We should only log the error if `locationEnabled = true` and we fail to acquire the permission.

**Comment by LukasPaczos** [comment]
Thanks for the report @colinrtwhite. Fixed with #11084.

**Comment by colinrtwhite** [comment]
:100: Thanks for the quick response!
