### ISSUE TITLE
MGLPointAnnotation within MGLPolygon

### ISSUE THREAD

**Issue by dan-burt** [mapbox/mapbox-gl-native#11080]
Can I check this? Is there an advanced mathematical model to do it?

Once annotations are dropped onto map, they should identify if they are within a MGLPloygon's boundaries. Or it should be available to calculate.

Internet searches do not seem to provide much. Some references to the Google Maps API, nothing obvious or definitive.

Not sure how critical this info is to the problem, but I am using the iOS SDK.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
