### ISSUE TITLE
offline render with multi glyphs?

### ISSUE THREAD

**Issue by lihuadong1988** [mapbox/mapbox-gl-native#11092]
I see offline render in map.test.cpp get glyphs like this:
test.fileSource.put(Resource::glyphs(prefix + "{fontstack}/{range}.pbf", {{"Helvetica"}}, {0, 255}), expiredItem("glyph.pbf"));

but what if one vector tile include characters across two different ranges?for example: character 1 is included in range {0, 255},character 2 is included in range {256,512}?

**Comment by jfirebaugh** [comment]
map.test.cpp is just test code, it's not necessarily indicative of production behavior.
