### ISSUE TITLE
Order text element index buffer by min zoom level

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#111]
This allows us to draw shorter ranges (= fewer vertices to process). Alternatively, we could sort it by angle (we have always 50% of vertices that we need to hide because they'd be upside down).

**Comment by jfirebaugh** [comment]
@kkaefer @ansis Does this still matter?

**Comment by kkaefer** [comment]
I don't think this is feasible anymore, since we're doing placement on rotation now.

**Comment by ansis** [comment]
I think it would still be possible to do this for zoom, but I think it's ok to close this and not do it for now.
