### ISSUE TITLE
PointAnnotation artifact when using flyTo

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11104]
When you add a point annotation to the map and use flyTo to animate the camera to that position:

![ezgif com-video-to-gif 38](https://user-images.githubusercontent.com/2151639/35683792-59cafa62-0765-11e8-86d5-31bfdbd7e7f9.gif)

This behaviour is not found in release-agua, solely in the release-boba codebase.
Code used to reproduce this issue [here](https://gist.github.com/tobrun/08b7f2aa8cc312d99ee418b71c06189c).

**Comment by ansis** [comment]
I think I see the issue: https://github.com/mapbox/mapbox-gl-native/blob/c3bf7c55a1f648e57c3853d555ff5f63c989f8c4/src/mbgl/text/placement.cpp#L233-L236 https://github.com/mapbox/mapbox-gl-native/blob/c3bf7c55a1f648e57c3853d555ff5f63c989f8c4/src/mbgl/text/placement.cpp#L241-L244 Duplicate labels get the `defaultOpacityState` when they should always be hidden.

**Comment by ansis** [comment]
@tobrun is it easy for you to check if  https://github.com/mapbox/mapbox-gl-native/commit/c4176633b64cfa53939a5495dfb7360f2a00c167 fixes it? otherwise I can try to build an example to actually reproduce.

@ChrisLoer does that fix look right? would it regress some case I'm not thinking about?

**Comment by ChrisLoer** [comment]
@ansis Yeah that change looks right to me, I'm surprised we didn't notice it earlier.

We have to make the same fix here:

https://github.com/mapbox/mapbox-gl-js/blob/adfc154ea28e587482f0e5de4c2c7055f7c22c1b/src/symbol/placement.js#L274-L281

I'm trying to think through what's going to regress from this... since it's a regression itself from the flickering fixes!

**Comment by ChrisLoer** [comment]
Confirmed that @ansis's fix (with a fix-to-fix to make sure duplicate symbols are _always_ hidden) gets rid of the duplicate marker artifact in @tobrun's `SimpleMapActivity` example.
