### ISSUE TITLE
android) Marker performance

### ISSUE THREAD

**Issue by swsong12** [mapbox/mapbox-gl-native#11107]
**Platform: android **
**Mapbox SDK version: 5.3.0**

Hi Mapbox team!

Currently if you have 1000+ marker/symbol layer with image loaded the performance is not too great. (There are some frame drops) Will there be updates and improvement on this issue?

Also, as for now, we are using vector tiles. Will using raster tiles improve the overall performance? I am assuming that rendering map + 1000 markers w/ image is hurting the performance. 

Thanks for the great work and support!

**Comment by tobrun** [comment]
@swsong12 thank you for reaching out and using our products. Sadly why is this slow is not really an actionable issue for us. We continue to invest to improve performance to meet all kind of different use-cases. That said, showing 1000+ markers on a map at the same time isn't really providing a good user experience. Have you tried something as clustering? This limits the amount of markers on a map while at the same your don't overload your users with too much information.

**Comment by tobrun** [comment]
fwiw https://github.com/mapbox/mapbox-gl-native/pull/11000 is going to improve adding images to the map (if this is what you are referring to in `There are some frame drops`).
