### ISSUE TITLE
Work with a mapbox offline map

### ISSUE THREAD

**Issue by DimaZatolokin** [mapbox/mapbox-gl-native#11105]
Hello, I have a question regarding a work with a mapbox offline map. I cache the map according to the tutorial (I set the borders of the needed region, create an OfflineManager object and call createOfflineRegion method). These are the borders I set: LatNorth – 56.9504454, LatSouth – 56.9484881, LonEast – 24.1137511, LonWest – 24.1019118 and then send them to the offlineManager. Still as a result when after that I visit the map offline I can see it's being cached in a considerably larger size than I set in the latLngBounds, i.e. LatNorth – 57.164127 , LatSouth - 56.942440, LonEast - 24.256790, LonWest - 23.885660 (10-16 zoom). As you can see a big piece of the map to the North, the West and the East is being cached. The amount of the cached data is really essential to me, so could you please help me to find out the reason of such behavior, and how this can be solved. Thanks in advance.

**Comment by tobrun** [comment]
@DimaZatolokin for each region definition we will download the responding tiles, if your bounds at the edge crosses a tile for only eg. 10%, we will still need to download and cache the full tile. There are no workaround for this and we don't perceive this an bug. That said there are ways to visually limit what the user is able to see eg. setLatLngBoundsForCameraTarget
