### ISSUE TITLE
Incorrect drawing route

### ISSUE THREAD

**Issue by Phanith-Fe** [mapbox/mapbox-gl-native#11101]
**Platform:**
MapboxNavigation v0.13

incorrect draw route to long destination.
In web, it's working fine.
![simulator screen shot - iphone 8 - 2018-01-31 at 23 30 57](https://user-images.githubusercontent.com/22009512/35634887-5fb4b34a-06df-11e8-9dd8-afaf0875423c.png)

**Comment by jmkiley** [comment]
Hey @Phanith-Fe -

Thank you for using our Navigation SDK for iOS! This repo tracks our Maps SDKs. Please open a new issue in the [repo for our navigation SDK](https://github.com/mapbox/mapbox-navigation-ios).
