### ISSUE TITLE
MGLMapSnapshotter leaks memory when taking a snapshot.

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/mapbox-gl-native#11117]
**Platform:** iOS
**Mapbox SDK version:** 3.7.x

### Steps to trigger behavior

 1. Initialize a map.
 2. Take a snapshot.
 3. Look at Debug Memory Graph it will display the retain cycles.

### Expected behavior
All objects should be realsed.
### Actual behavior
Objects related to Attribution Info are retained.
Memory does not get released.

**Comment by friedbunny** [comment]
Fixed by #11193, will be in the forthcoming `ios-v3.7.6` release.
