### ISSUE TITLE
UncaughtException: java.lang.Error: Bad optional Access Android

### ISSUE THREAD

**Issue by nikiizvorski** [mapbox/mapbox-gl-native#11115]
Hello we are experiencing some issues with the latest version actually our problems started from 5.20 and above. Here is the exception we are getting on one of the places we currently use mapbox.

UncaughtException: java.lang.Error: Bad optional Access

@Override
    protected void onStop() {
        super.onStop();
        if (mapView != null) {
            if (mapboxMap != null) {
                mapView.onStop();
            }
        }
    }

**Platform: Android
**Mapbox SDK version: latest 6.0.0

### Steps to trigger behavior

 1. Just normal usage
 2. onStop

### Expected behavior

Just no crash.

### Actual behavior

Work :)

**Comment by tobrun** [comment]
@nikiizvorski we haven't seen any reports on our end on this issue. Could you clarify why you are adding those null checks on mapView or mapboxMap? I believe those should be removed to resolve this issue.
