### ISSUE TITLE
[Feature Request] Add Rotation and Anchor for Marker

### ISSUE THREAD

**Issue by ltluc253** [mapbox/mapbox-gl-native#11114]
I'm switching our app from Google Map to Mapbox, but some basic features like Rotation Marker and set Anchor for Marker isn't supported by Mapbox. These features is very important in our app, can you add its on new version?

**Platform:** Android
**Mapbox SDK version:** 5.3.2

**Comment by tobrun** [comment]
We currently don't support these concept on our higher level api of Marker. For now you will need to use SymbolLayer to use rotation/anchoring.

**Comment by luistrejo** [comment]
I can have every symbol layer icon different bearing?, I can't find how it is possible in android and markerviewoptions is deprecated.

**Comment by tobrun** [comment]
@luistrejo yes you can, we call this concept data driven styling where you can style a layout property based on the underlying data. A couple of examples can be found in [this](https://blog.mapbox.com/a-guide-to-the-android-symbollayer-api-5daac7b66f2c) blogpost.

Here is an example of iconSize , but this can also work for iconRotate:

```
 PropertyFactory.iconSize(
      Function.property(
        "selected",
        Stops.categorical(
          Stop.stop(true, PropertyFactory.iconSize(1.5f)),
          Stop.stop(false, PropertyFactory.iconSize(1.0f))
        )
      )
    )
```

Note that with the upcoming 6.0.0 SDK release we are migrating to replace the Function syntax with an expression syntax.

**Comment by lilykaiser** [comment]
It seems this issue is resolved, please reopen if it is still a problem
