### ISSUE TITLE
Add support for annotations when snapshotting

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#11113]
It’s currently impossible/difficult to add annotations or shape overlays to snapshots — we should support this use-case, as it’s somewhat rare for developers to simply want a plain map image.

The current workaround for this use-case is to use our web static maps API, wrapped by something like [MapboxStatic.swift](https://github.com/mapbox/MapboxStatic.swift/), which does include direct methods for annotations/overlays.

Related: https://github.com/mapbox/mapbox-gl-native/issues/9914, which talks about adding runtime styling support to the snapshot APIs.

/cc @ivovandongen @tobrun @1ec5 @frederoni

**Comment by frederoni** [comment]
We're on par with [MKMapSnapshot](https://developer.apple.com/documentation/mapkit/mkmapsnapshot) as of #10163. Are you saying that we should provide a way to draw images on images or is the conversion between coordinate systems sufficient?

**Comment by friedbunny** [comment]
@frederoni I think we should do a couple things:

- Look at enabling the composition of point and shape annotations, using existing classes, onto a map before it’s rendered into a raster image.
- Improve the docs: explain what the coordinate conversion methods are and how to use them. AFAIK, we currently just say that such a thing is possible but not how or what the limitations of this approach might be:

https://github.com/mapbox/mapbox-gl-native/blob/90f29a91729b536da9f090d389549db1ec4b8e9f/platform/darwin/src/MGLMapSnapshotter.h#L132-L133

**Comment by 1ec5** [comment]
> Look at enabling the composition of point and shape annotations, using existing classes, onto a map before it’s rendered into a raster image.

Both point and shape annotations are rendered by style layers, and snapshots don’t need on-the-fly addition/removal or interactivity. So once snapshots support runtime styling (#9914), MGLMapSnapshotter could translate annotations to style layers as they are added to the snapshot.

View-backed annotations could work similarly, except that we’d snapshot the view before adding it to the snapshot. (Yay overloaded terminology!)

**Comment by tobrun** [comment]
Removing android label as https://github.com/mapbox/mapbox-gl-native/issues/9914 would be the same since we don't have the concept of a view annotation anymore on android.

**Comment by julianrex** [comment]
Still valid.
