### ISSUE TITLE
[Qt] IOS & android not working

### ISSUE THREAD

**Issue by ducmaxime** [mapbox/mapbox-gl-native#11139]
Hello

I try you sdk with QML with your sample

width: 512
    height: 512
    visible: true

    Plugin {
        id: mapboxglPlugin
        name: "mapboxgl"
    }

    Map {

    anchors.fill: parent
    plugin: mapboxglPlugin
    center: QtPositioning.coordinate(59.91, 10.75) // Oslo
    zoomLevel: 14
    }

It's work on MACX but not on android and IOS.

Can you help me ?

**Comment by friedbunny** [comment]
As far as I’m aware, we do not officially support deploying Qt to iOS or Android — for those platforms, we offer fully-featured, tested, and mature native SDKs: 

- [Mapbox Maps SDK for iOS](https://www.mapbox.com/ios-sdk/)
- [Mapbox Maps SDK for Android](https://www.mapbox.com/android-docs/map-sdk/overview/)

**Comment by tmpsantos** [comment]
@ducmaxime this is an issue with the Qt Location plugin (not mapbox-gl-native). Can you open it here? https://bugreports.qt.io
