### ISSUE TITLE
LatLngBounds.contains(LatLong) can return always 'false'

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#11137]
**Platform:** Android
**Mapbox SDK version:** 5.4.0 (not reproduced on 5.0.2)

### Steps to trigger behavior
 1. LatLngBounds latLngBounds  =  mapboxMap.getProjection().getVisibleRegion().latLngBounds
 2. latLngBounds.toString()
 3. Sametime (change map rotation angle): "N:55.99722274440842; E:92.80566583823929; S:56.00073056968671; W:92.77899862655636"
 4.method: LatLngBounds.contains(ILatLng latLng) return always 'false', because latitudeNorth < latitudeSouth
```
public boolean contains(final ILatLng latLng) {
    final double latitude = latLng.getLatitude();
    final double longitude = latLng.getLongitude();
    return ((latitude <= this.latitudeNorth)
      && (latitude >= this.latitudeSouth))
      && ((longitude <= this.longitudeEast)
      && (longitude >= this.longitudeWest));
  }
```

**Comment by tobrun** [comment]
@osana would you be able :eyes:  this issue? You have recently worked on this class and its business logic.

**Comment by osana** [comment]
@klblk what are the LatLng bounds that are passed into contains() method of LatLngBounds object with values that you specified?

**Comment by klblk** [comment]
Sorry, I did not understand the question. 
My case: 
Determine user sees LatLng point in screen or not.

For Mapbox 5.0.2 and less, i use VisibleRegion.latLngBounds, and contains() method. But this broken in 5.4.0 if rotate map (not tested other version).

My current solution for 5.4.0: 
I not use VisibleRegion.latLngBounds, and create LatLngBounds through method: 
```
private static LatLngBounds visibleLatLngBounds(VisibleRegion visibleRegion) {
        return new LatLngBounds.Builder()
                .include(visibleRegion.farLeft)
                .include(visibleRegion.farRight)
                .include(visibleRegion.nearLeft)
                .include(visibleRegion.nearRight)
                .build();
    }
```

**Comment by osana** [comment]
@klblk Thank you for clarifying. I thought that the bug was against incorrectly working `contains` method.

**Comment by osana** [comment]
@klblk  I am confirming that indeed this is reproducible in master.

**Comment by osana** [comment]
@tobrun  The source of the problem is a combination of implementation of ```Projection.getVisibleRegion() ```
https://github.com/mapbox/mapbox-gl-native/blob/63eb511d8365c5a22cde65a9118559dc7561f1de/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java#L106

and implementation of 
```LatLngBounds.fromLatLngs()```
https://github.com/mapbox/mapbox-gl-native/blob/63eb511d8365c5a22cde65a9118559dc7561f1de/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java#L292

If map is rotated topLeft of the VisibleRegion will not be the actual northWest.

**Comment by osana** [comment]
@tobrun  A couple of action items / further discussions out of this

1) VisibleRegion takes farLeft, farRight, nearLeft, nearRight and latlngBounds which are supposed to be The smallest bounding box that includes the visible region defined in this class. There are no checks to ensure if that is indeed the case. Should we do some checks in the constructor?

2) We should add a check to LatLngBounds constructor:  throw an IAE if  north < south
