### ISSUE TITLE
Crash in addImages

### ISSUE THREAD

**Issue by femski** [mapbox/mapbox-gl-native#11135]
**Platform:** Android
**Mapbox SDK version:** Master Branch

### Steps to trigger behavior

Call mapboxMap.addImages((HashMap<String, Bitmap>)bitmaps)
with more than 512 images.

### Expected behavior

Images added and can be used in Symbol layer as icons using iconImage("xxxx") property.

### Actual behavior

Native crash.

**02-06 22:36:17.463 A/art: art/runtime/indirect_reference_table.cc:116] JNI ERROR (app bug): local reference table overflow (max=512)**

02-06 22:36:17.644 A/art: art/runtime/runtime.cc:403]   at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddImages(Native method)
02-06 22:36:17.644  A/art: art/runtime/runtime.cc:403]   at com.mapbox.mapboxsdk.maps.NativeMapView.access$300(NativeMapView.java:45)
02-06 22:36:17.644  A/art: art/runtime/runtime.cc:403]   at com.mapbox.mapboxsdk.maps.NativeMapView$BitmapImageConversionTask.onPostExecute(NativeMapView.java:1179)
02-06 22:36:17.644 A/art: art/runtime/runtime.cc:403]   at com.mapbox.mapboxsdk.maps.NativeMapView$BitmapImageConversionTask.onPostExecute(NativeMapView.java:1138)

Based on this Stackoverflow answer 

https://stackoverflow.com/questions/26685491/jni-error-app-bug-local-reference-table-overflow-max-512?answertab=active#tab-top

it seems possible issue is with non-deletion of local reference in native_map_view.cpp:

```cpp
void NativeMapView::addImages(JNIEnv& env, jni::Array<jni::Object<mbgl::android::Image>> jimages) {
    jni::NullCheck(env, &jimages);
    std::size_t len = jimages.Length(env);

    for (std::size_t i = 0; i < len; i++) {
        jni::Object<mbgl::android::Image> jimage = jimages.Get(env, i);
        auto image = mbgl::android::Image::getImage(env, jimage);
        map->getStyle().addImage(std::make_unique<mbgl::style::Image>(image));
        jni::DeleteLocalRef(env, jimage);
    }
}
```

**Comment by tobrun** [comment]
will be fixed with #11350
