### ISSUE TITLE
Size of offline regions gets lost after app restart

### ISSUE THREAD

**Issue by riserpete** [mapbox/mapbox-gl-native#11140]
(Byte) size of a MGLOfflinePack (within the progress property) is always 0 (zero) after a restart of the app. While downloading the progress works fine, but once the app is restarted, file/tile sizes of the offline regions are always 0.

**Platform: iOS (and as it looks also Android)**
**Mapbox SDK version: 3.7.3 (iOS)**

### Steps to trigger behavior

 1. Download offline region via `MGLOfflineStorage.shared().addPack(for: ...`
 2. During download the `progress` property of the MGLOfflinePack is correct 
 3. Restart app
 4. All packs retrieved via `MGLOfflineStorage.shared().packs` have the value 0 in the `progress` attributes such as `countOfBytesCompleted`

### Expected behavior
Retain size of offline regions after app restarts to show the user how much space offline regions occupy

### Actual behavior
Offline region sizes info gets lost after app restart

**Comment by jfirebaugh** [comment]
This is expected behavior; see [the documentation for `progress`](https://www.mapbox.com/ios-sdk/api/3.7.4/Classes/MGLOfflinePack.html#/c:objc(cs)MGLOfflinePack(py)progress) for an explanation.
