### ISSUE TITLE
Remove scheduled requests based on requestor

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11147]
This feature request would solve the issue shown in https://github.com/mapbox/mapbox-gl-native/issues/11123 and thus our flaky tests on CI. The issue we have in #11123 stems from using an unified filesource with multiple maps. Having the ability to remove/cancel request based on the requestor (a map instance or an offline download) would allow the binding to have more control over the request queue. One way to implement this is to add a tag to every request that functions as an unique id to the requestor. Exposing an api to clear the queue based on this id would give the binding the required hook.

Not sure if this is the way forward, feel free to close if not.

**Comment by jfirebaugh** [comment]
`FileSource` already implements cancellation -- the result of [the `request` method](https://github.com/mapbox/mapbox-gl-native/blob/b2fabe5eefc81cc38866a4856d6db37f4471d6ae/include/mbgl/storage/file_source.hpp#L25) is an owned object which will cancel the request when it's destroyed, and destroying a map will eventually trigger destroying all its owned requests. So tracking down #11123 will more involve an investigation of why the cancellation mechanism isn't as effective as we want.
