### ISSUE TITLE
Conditional render tests

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-native#11144]
A tricky issue has come up while finalizing the heatmap layer (#11046) — to render nicely, it needs some GL extensions that are not present on some devices, in which case it falls back to a lower-quality rendering. Ideally, we would want to cover both the "ideal" and the "fallback" versions in render tests, something the current test setup doesn't accommodate. You can see an example of the difference in [these test results](https://67603-16286131-gh.circle-artifacts.com/0/render-tests).

In GL JS, we only cover the "fallback" mode because `headless-gl`, a module used for rendering WebGL on CI servers, doesn't support the necessary extensions. But in gl-native, some builds in the CI matrix can render the "ideal" version while others don't.

Open questions:
- What's the best way to introduce conditional render tests runs, and how do we configure those conditions?
- Will we manually keep a config of which platform can run in which mode (like we do with ignores), updating when the build matrix changes, or could we implement some kind of automatic way to bail out of a render test without failing?
- How do we force "ideal"-capable platforms to run the "fallback" version? Checking a special style.metadata property in the render code?
- Are there any other cases beside heatmaps that could utilize the new flexibility?
- Can we introduce this without adding too much complexity in the test harness?

cc @mapbox/gl-core

**Comment by mourner** [comment]
One makes matters more complicated is that [this Pixel Android failure](https://circleci.com/gh/mapbox/mapbox-gl-native/67593?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) seems to suggest that the presense of relevant extensions doesn't guarantee that the "ideal" rendering will work — to be completely sure, we have to try binding a half-float texture as a render target and check for "Incomplete attachment" error after that. Basically this means we can only detect whether the device is capable of "ideal" rendering at runtime, not compile time.

**Comment by kkaefer** [comment]
One way of solving this problem is to expand what is currently `GLContextMode` to a more full-fledged bitfield that controls extension usage as well. Then we could use these flags to initialize the Node.js map object from the metadata provided in the stylesheet.

**Comment by anandthakker** [comment]
> Then we could use these flags to initialize the Node.js map object from the metadata provided in the stylesheet.

@kkaefer are there use cases for this beyond the half-float one for heatmaps?  If not, that might be unnecessary -- i.e., just a more direct hardwired no_half_float flag might be better, even though it's a little unsightly...

**Comment by jfirebaugh** [comment]
What about a "simplest thing that could possibly work" proposal: allow multiple files of the form `expected-*.png` (in this case one for platforms that support the extension, and one for platforms that don't), and pass the test if any of them pixelmatch the output? (Then use `description` field in the JSON to explain the variants, a convention established in https://github.com/mapbox/mapbox-gl-js/pull/5780.)

This isn't completely exhaustive (wouldn't catch the case where an extension-supporting platform renders as if it weren't supported, for example), but it seems like a decent trade off between completeness and complexity.

**Comment by mourner** [comment]
@jfirebaugh I like this. Seems much easier and simpler than all solutions proposed up till this point. I'll try it out!
