### ISSUE TITLE
Publish debug build

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#11150]
In order to get line numbers from a native crash as described [in our guide here](https://github.com/mapbox/mapbox-gl-native/wiki/Getting-line-numbers-from-an-Android-crash-with-ndk-stack) we need to work with a debug build of the SDK. This plays well when using the embedded Test App, but becomes more difficult when consuming the SDK as an external dependency.

I suggest publishing an additional `-debug` build of our SDK to Maven to make it easier to troubleshoot this kind of issues. A developer would be able to switch the regular dependency (e.g. `com.mapbox.mapboxsdk:mapbox-android-sdk:5.4.0`) with the debug build (e.g. `com.mapbox.mapboxsdk:mapbox-android-sdk:5.4.0-debug`) to symbolicate the trace.

@mapbox/maps-android What do you think?

cc: @kkaefer

**Comment by tobrun** [comment]
Been thinking a bit on how this could fit best into our current workflow to minimise impact to the other bindings (eg. increased CI build time). I think we should follow the same workflow as we are currently doing for our cn builds. Have a separate CI build for building the debug equivalent of `make apackage`. The other solution of direct integration in current workflow would double the execution time (need to build for debug/release separately).

**Comment by tobrun** [comment]
A different approach to this issue would be publish SNAPSHOT builds as debug.

**Comment by LukasPaczos** [comment]
Creating new `-debug` artifact with every release shouldn't impact day to day workflow as it won't be executed for PRs, but only for final release branches.

Changing `SNAPSHOT`s to debug build is a great idea as well. It should serve a debug purpose as we encourage people not to use `SNAPSHOT`s on production, but rather to test out if the issue is still present on `master`, or release branch. Making it a debug build allows acting on it easier with the user's help.

Do you think we can put both those ideas into life?

**Comment by tobrun** [comment]
> Creating new -debug artifact with every release shouldn't impact day to day workflow as it won't be executed for PRs, but only for final release branches.

small note is that we build the release with every push to the repo. Only when the target branch is a release/master we will upload that binary to maven:


```
      - deploy:
          name: Publish to Maven
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then make run-android-upload-archives ; fi
```

If we would build the additional -debug variant, we should include the same branch check above before actually building the debug variant so it doesn't impact our day-to-day workflow.

**Comment by LukasPaczos** [comment]
Oh yes, true. If-checking for a release branch should make it viable then.

**Comment by zugaldia** [comment]
> small note is that we build the release with every push to the repo. Only when the target branch is a release/master we will upload that binary to maven:

Good point. A strategy we follow for other repos is to hide that step behind an environment variable instead of a branch check (the strategy for [nightly builds](https://circleci.com/docs/1.0/nightly-builds/)). Something like:

```
- run:
	name: Upload to Maven
	command: |
		if [ -n "${IS_RELEASE_BUILD}" ]; then
			...
		fi
```

**Comment by tobrun** [comment]
Done in #12485
