### ISSUE TITLE
Call to mapView.onDestroy freezes at nativeDestroy

### ISSUE THREAD

**Issue by haydenkaizeta** [mapbox/mapbox-gl-native#11153]
NativeDestroy freezes and never completes

**Platform:**
Android SDK 24
**Mapbox SDK version:**
v5.4.0
### Steps to trigger behavior

 1. Get a MapboxMapView
 2. Switch to another activity, resulting in a call to `onDestroy` of the map
 3. The call to `nativeDestroy` never completes

### Expected behavior
`mapView.onDestroy()` completes without issue
### Actual behavior
Call to destroy freezes thread, if another thread is used it causes a native crash later in the process.

**Comment by tobrun** [comment]
Thank you for reaching out. Are you using a fragment? If not, can you add some sample code? We haven't seen this issue on our end only when calling Mapview#onDestroy from Fragment#onDestroy while it should be hooked in from Fragment#onDestroyView

**Comment by haydenkaizeta** [comment]
@tobrun ah yep. Fragment#onDestroyView was the key. Thanks
