### ISSUE TITLE
Raw expression support

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11158]
Feedback from a user trying out expressions: It would have been nice being able to use raw expressions as used in the [style-spec](https://www.mapbox.com/mapbox-gl-js/style-spec/). This would allow for both using the current DSL approach in combination with approach taken in the style-spec. 

eg.
```java
iconImage(get("key))
```
vs
```java
iconImage("[\"get\", key]")
```

**Comment by jfirebaugh** [comment]
How would you distinguish a literal string value from an expression string?

**Comment by anandthakker** [comment]
@tobrun what about adding a `raw()` function to the DSL?

```
iconImage(raw("[\"get\", key]"))
```

**Comment by 1ec5** [comment]
This will significantly reduce the amount of work needed for mapbox/react-native-mapbox-gl#1047, since the iOS map SDK already has something like this.

Note that a similar conversion would be needed for filters as well.

/cc @nitaliano
