### ISSUE TITLE
Sum expression has trailing decimals

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11160]
Capturing from a user trying out expressions to convert temperature celsius to kelvin:

> Expression evaluator doesn't seem to return expected value. For example with expression like
10.2 + 273.15, it returns 283.34999999999999. The extra decimals are not expected.

cc @anandthakker

**Comment by jfirebaugh** [comment]
This is expected behavior; see http://floating-point-gui.de/
