### ISSUE TITLE
crash in metrics gesture tracking

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1116]
Crashes are occurring inside of `-[MGLMapView trackGestureEvent:forRecognizer:]`, probably compounded the extreme rapid-fire nature of them during pans and zooms. 

This ticket tracks crashes related to mutation of objects during iteration. 

* https://rink.hockeyapp.net/manage/apps/163490/app_versions/2/crash_reasons/31107650
* https://rink.hockeyapp.net/manage/apps/163490/app_versions/2/crash_reasons/31108916
* https://rink.hockeyapp.net/manage/apps/163490/app_versions/2/crash_reasons/31128721
* https://rink.hockeyapp.net/manage/apps/163490/app_versions/2/crash_reasons/31136788
* https://rink.hockeyapp.net/manage/apps/163490/app_versions/2/crash_reasons/31152675

**Comment by incanus** [comment]
There are other lingering crashes in `-[MGLMapView trackGestureEvent:forRecognizer:]` as well, but let's knock out the above, which looks to me like a clear sing of non-threadsafety, first.

**Comment by bleege** [comment]
The first 2 crash reports from HockeyApp both give the following as the crash point:

> 10  UIKit                                0x000000018aa6ba40 -[UIGestureRecognizer locationInView:] + 264
> 10  UIKit                                0x000000018b25ba40 -[UIGestureRecognizer locationInView:] + 264

The final 3 crash reports all report:

> We have determined that the link register (lr) is very likely to contain the return address of frame #0's calling function, and have inserted it into the crashing thread's backtrace as frame #1 to aid in analysis. This determination was made by applying a heuristic to determine whether the crashing function was likely to have created a new stack frame at the time of the crash.

**Comment by incanus** [comment]
This just sounds like UI access not on the main thread to me.

**Comment by bleege** [comment]
Yep.  https://github.com/mapbox/mapbox-gl-native/pull/1115/files#r27249748

**Comment by incanus** [comment]
Just about through with a large refactor here. The main cause of crashes here is that we are crossing access to `_queue` from both of our custom serial queues as well as the main UI thread.

**Comment by bleege** [comment]
![keep-calm-and-don-t-cross-the-streams-6](https://cloud.githubusercontent.com/assets/989928/6860501/0e48908a-d3f7-11e4-9a10-26856d4875ec.png)
