### ISSUE TITLE
Add heatmap-color support on Android

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11172]
Capturing from @mourner in https://github.com/mapbox/mapbox-gl-native/pull/11046#discussion_r167568302:

> I disabled any code generation for heatmap-color on the Android side because it requires being able to pass expressions as its values — as far as I remember, we had some bits missing about expressions which made it very hard to make it work.

Ticketing this out so we don't forget adding this for the final release.

**Comment by tobrun** [comment]
I reenabled generating the heatmap-color property from the specification and I'm hitting:

<img width="1258" alt="screen shot 2018-02-12 at 20 03 32" src="https://user-images.githubusercontent.com/2151639/36114268-d3be1a16-102f-11e8-9156-438a631bdf45.png">

**Comment by mourner** [comment]
@tobrun I recall that we were not able to convert properly at the time of the PR, but @anandthakker @ChrisLoer might be working on this now, or at least expect to land some improvements soon — can you comment?

**Comment by ChrisLoer** [comment]
@mourner we're close to landing an [`Expression::serialize()`](https://github.com/mapbox/mapbox-gl-native/pull/11156) that returns an `mbgl::Value` is that what you'd need?

**Comment by tobrun** [comment]
@ChrisLoer awesome to hear, that would integration from my end make it a lot easier

**Comment by anandthakker** [comment]
@tobrun yeah, I think this needs the equivalent of https://github.com/mapbox/mapbox-gl-native/pull/11074

**Comment by tobrun** [comment]
fixed with #11220, getter will be added with #11352
