### ISSUE TITLE
Multiple Clusters in one map

### ISSUE THREAD

**Issue by maley63** [mapbox/mapbox-gl-native#11173]
I am currently using MapBox Cluster Example - https://www.mapbox.com/ios-sdk/examples/clustering/

I would like to use multiple GeoJSON and to cluster my annotations.

My problem is that if I add multiple GeoJSONs, the clusters are shown overlapped on top of each other. Instead of having 2/3 clusters it should only show 1 for that specific area.

Is there a way to only show one cluster?

I am using Swift but have left this out to see if anyone has had experience in Java etc.

Thanks

**Comment by jfirebaugh** [comment]
All data you want clustered together must be in a single GeoJSON source. There isn't a way to cluster across multiple sources.

**Comment by maley63** [comment]
Do you know if I could change the images of the annotations in a single GeoJSON?  
If I accessed the GeoJSON and its name was equal to Hospital.  Show Hospital icon? etc.
Thanks

**Comment by Joey-Rose** [comment]
Is there still not a way to cluster across multiple sources? I'm facing a similar situation, though my clustered data is spread across a vector tile data source and a geojson data source and I'm using Mapbox GL JS.
