### ISSUE TITLE
Hook to prevent gesture execution

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11170]
We deprecated TrackingSettings as part of MyLocationView deprecation in https://github.com/mapbox/mapbox-gl-native/pull/9771. We haven't exposed the equivalent functionality in a plugin. To support the same functionality we need to refactor the gesture code to allow a external plugin to determine if a gesture is allowed to occur or its result should be ignored. 

eg. when creating a locked down navigation app and we're tracking the location of a user, we would like to be able to react on the user starting to pan the map. If the following method returns true, the gesture occurs if not the result of the gesture is ignored.

```java
boolean isCameraChangeAllowed(int CameraChangeType)
``` 

Having above + being able to set a focal point should result in supporting the same use-cases.

cc @cammace @LukasPaczos

**Comment by LukasPaczos** [comment]
Alternatively, we can include camera/location managing plugin as a `compileOnly` dependency in the Maps SDK and execute gestures + camera checks logic only if the plugin is present.

**Comment by LukasPaczos** [comment]
Closing as this won't be needed.
