### ISSUE TITLE
ReactNative GLSurfaceView integration results in ANR

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11177]
Capturing from @nitaliano:

> React Native runs in a single activity, so there's no guarantee that N number of MapViews will be rendered before the App is killed and onDestroy gets called. It's creating an ANR calling it from the lifecycle hooks that I have access to with a GLSurfaceView, but when I switch to a TextureView I don't get the ANR.

**Comment by tobrun** [comment]
@nitaliano are you able to hook into the view removal of React Native? 

I noticed the following:
 - addView / onCreate / onStart /onResume
 - onPause/ onStop/ removeView / onDestroy -> results in ANR

While:
 - addView / onCreate / onStart /onResume
 - onPause/ onStop/ onDestroy / removeView -> works as normal

**Comment by nitaliano** [comment]
@tobrun yes we have complete access to the native view lifecycle. Thanks for looking into it I'll give it a go!

**Comment by nitaliano** [comment]
I have tested this locally and I'm not seeing the ANR. I'll be submit a PR and see if others are seeing the same thing then come back here and close this out

**Comment by nitaliano** [comment]
I spoke too soon I'm still running into the issue

**Comment by nitaliano** [comment]
@tobrun so what you mentioned above works in a pure native app, but once I throw React Native into the mix it stills get's the ANR. I'll go over what the lifecycle looks like in React Native.

When we write out components in Javascript they go over a "bridge" to the native code. You can think of this bridge as a websocket server that is receiving a blob of json with all the information about the views.

Once the server/manager receives one of these events from the Javascript it parses the JSON and put's everything on an operation queue called the [`UIViewOperationQueue`](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIViewOperationQueue.java). This queue handles all view operations, so it will have create/update/delete operation tasks.

When it pops one of those tasks off of the queue it will hit the [`NativeViewHierarchyManager`](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyManager.java) this manager is what will tell our view managers when to create/update/remove, so based off the operations it received it will loop through the information given and tell the ViewManager what event it should handle, the notable ones in this case are `createViewInstance` and `dropViewInstance`

The ViewManagers in React Native are singletons, they are initialized once we start the applications, so in our case we have a ViewManager for our MapView, this ViewManager will know about all of it's views and decide which view it should create/update/delete.

When the `NativeViewHierarchyManager` calls our `createViewInstance` method on our MapViewManager we will create a Mapbox MapView, inside of that constructor is where we will call `onCreate/onResume/onStart/getMapAsync`.

When the `NativeViewHierarchyManager` calls our `dropViewInstance` method on our MapViewManager will then try to cleanup our map. I have created on `synchronized dispose` method that will tell the locationlayer to stop, and it will also call `onPause/onStop/onDestroy` here is where we are getting our ANR, the view is also no longer visible on the screen at this point in some cases.

Threading wise all calls to our MapView will happening on the main thread. Hope this information helps

**Comment by nitaliano** [comment]
@tobrun I was able to figure out a way to work around the issue with this commit https://github.com/mapbox/react-native-mapbox-gl/pull/1033/commits/5f2e782ed0f9f6d8eb394b3d920dfb84753bb657 react has the concept of a `ShadowNode` that runs on a background thread, it helps keep the JS and native view properties in sync. I've extended this `ShadowNode` and created a custom `MapShadowNode` because it has a `dispose` method that would get called before the native view would be removed, and calling the `onDestroy` from this method seems to prevent the ANR.

**Comment by tobrun** [comment]
great to hear! going ahead and close this out
