### ISSUE TITLE
Still [Crashing] IllegalStateException: setRenderer has already been called for this instance

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-gl-native#11181]
Facing crashing issue when using mapview for multiple fragments inside a view pager with Tab Layout.

Using the sdk version - 5.3.2

**Comment by LukasPaczos** [comment]
Thanks for reaching out and reporting your issue @mf-mindcrewtech.
Is there a chance that in your setup map fragments are overlapping? If yes, that's an ill-advised use-case from the Android platform perspective as there should be only one `GLSurfaceView` present on a portion of the screen.
However,  https://github.com/mapbox/mapbox-gl-native/pull/11124 included in the `5.4.1` release might help with this issue, please feel free to test it out.

Another approach would be trying out `TextureView` mode.

Let us know whether any of the above helps.

**Comment by tobrun** [comment]
Thank you for reaching out, this is fixed in the latest version of the SDK (5.4.1), feel free to report if you are able to reproduce with that version. Closing.
