### ISSUE TITLE
Change image of annotations in single GeoJSON

### ISSUE THREAD

**Issue by maley63** [mapbox/mapbox-gl-native#11194]
Are we able to change the images of the annotations in a single GeoJSON in cluster.
If I accessed the GeoJSON and its name was equal to Hospital. Show Hospital icon? etc.
Thanks

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
