### ISSUE TITLE
How should I handle clicks on overlapping polylines?

### ISSUE THREAD

**Issue by marconealberto** [mapbox/mapbox-gl-native#11203]
Android 7
MapBox 5.4.1

I draw two polylines that share a piece of route and tap on the top line

### Expected behavior
The polyline on top should be the one that gets selected

### Actual behavior
The click bleeds through the views and is triggered from the bottom polyline

Example of overlapping polylines:
![screenshot_20180214-151140](https://user-images.githubusercontent.com/779070/36208727-0ab17782-119a-11e8-9000-d7b6979889d4.png)

A similar thing happens if I tap on a marker and there's a polyline beneath, the polyline will result as clicked and the click on the marker will be ignored.

**Comment by tobrun** [comment]
Besides the issue shown in OP you can roll your own click selection mechanism for a more fine grained control with an OnMapClickListener and using MapboxMap#queryRenderedFeatures. With this method you can query the map for a feature with using a layer id. The id for that layer will match the id of the polyline with `"com.mapbox.annotations.shape.{id}"`. 

Re. the issue, I'm guessing the issue here is two fold, on one end prioritisation of point annotation selection vs shape annotation selection and they way we prioritise shapes selection in queryRenderedFeatures.

**Comment by marconealberto** [comment]
thank you for your answer.
Once I implement the OnMapClickListener, the onMapClick method returns a LatLng only. How can I detect what was clicked?
As I said above I have the same problem with a Marker and a Polyline, if I click on the marker, the polyline click will be triggered and the marker click will be ignored. 
I thought that this was a common scenario, what's the best practice in this case?

**Comment by LukasPaczos** [comment]
@marconealberto you can transform the `LatLng` returned by the map click to a pixel point and query map features
```
final PointF pixel = mapboxMap.getProjection().toScreenLocation(point);
List<Feature> features = mapboxMap.queryRenderedFeatures(pixel, "com.mapbox.annotations.shape.{id}");
```
with the layer `id` explained by @tobrun.

**Comment by marconealberto** [comment]
the problem with this is that you have to click right on the exact coordinates to have the queryRenderedFeatures return you the object you clicked.

I tried tapping with my finger on a polyline and only 1 out of 3-4 is triggered. How can I make it so that there's some tolerance? The onPolyLineClicklistener reacts way better than this.
 I haven't tried it yet but I guess the same thing will apply to Markers. What if I don't click on the exact coordinates, but instead on the bigger icon?

Can't still wrap my head around the fact I have to go this length for what it looks an obvious use case..  I have to call the queryRenderedFeatures on each single polyline or marker and check if it's been clicked, instead of using normal listeners.

**Comment by LukasPaczos** [comment]
When using `mapboxMap.queryRenderedFeatures()` instead of passing a point you can pass a rectangle which would look for features in a bigger area, decreasing the click precision needed.

**Comment by marconealberto** [comment]
never updated on this, but it's exactly what I was looking for. Thank you @LukasPaczos
