### ISSUE TITLE
MBGLMapView getRawStyle returns nil

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#1120]
When using a bundled style, the getRawStyle method returns nil. Expected behavior: it would return an NSDictionary representation of the current style.

However, after setting a map style with setRawStyle:, the getRawStyle works as expected.

**Comment by incanus** [comment]
This API will likely go away in favor of just style URL setting, externally via a passed `NSURL` (local or remote) or internally during setup. Also we'll probably lose the bundled style name-based API.

**Comment by incanus** [comment]
This API has gone away.
