### ISSUE TITLE
Possibility of making play-services-location optional

### ISSUE THREAD

**Issue by yang-owl** [mapbox/mapbox-gl-native#11208]
**Platform:** Android
**Mapbox SDK version:** 5.4.1

Currently `com.mapbox.services.android.telemetry.location` has dependencies from `com.google.android.gms:play-services-location`. As we are only using the Mapbox engine to render offline maps, we don't want to include the `com.google.android.gms:play-services-location` dependency.

We've only included `com.mapbox.mapboxsdk:mapbox-android-sdk:$mapboxSdkVersion` and are able to do what we need (without getting runtime crashes etc), but we are getting proguard warnings because obviously we have not provided the `play-services-location` dependency as mentioned above. We can bypass the warnings by adding `-dontwarn com.mapbox.services.android.telemetry.location.**`, but would it be feasible to move this transitive dependency on `play-services-location` out of the core SDK?
Thanks.

**Comment by tobrun** [comment]
@yang-owl with 6.0.0 we are introducing a new telemetry library. That dependency makes play services optional, see [this line](https://github.com/mapbox/mapbox-events-android/blob/master/liblocation/build.gradle#L26). Closing as already resolved.
