### ISSUE TITLE
Look into indices for update operations

### ISSUE THREAD

**Issue by lilykaiser** [mapbox/mapbox-gl-native#11218]
Per internal conversation, it appears that our offline downloads spend a lot of time in sqlite operations. We could save time by correcting our indices for the update operations to avoid doing table scans.

@kkaefer or @ivovandongen can you look into this?

**Comment by jfirebaugh** [comment]
They shouldn't be doing table scans. I made sure of that when designing the schema.

Who is seeing table scans, and where?

**Comment by jfirebaugh** [comment]
Specifically:

* `UPDATE resources` queries should all be using the index on `url` created by the table's `UNIQUE` constraint.
* `UPDATE tiles` queries should all be using the index on `(url_template, pixel_ratio, z, x, y)` created by the table's unique constraint.
* `UPDATE regions` queries should be using the table's `id` primary key.

**Comment by jfirebaugh** [comment]
Closing; I think this was likely just misdiagnosed.
