### ISSUE TITLE
[iOS]Map artifacts when adding MGLSymbolStyleLayer

### ISSUE THREAD

**Issue by yulian948** [mapbox/mapbox-gl-native#11216]
Experiencing strange artifacts when working with MGLShapeSource, MGLSymbolStyleLayer.
The issue appeared after updating from SDK ver. 3.6.4 to 3.7.3

The issue disappears if only a small number of features are on screen. 
Also it disappears on zooming.

I think it is in some way similar to this issue [#1857](https://github.com/mapbox/mapbox-gl-native/issues/1857)

Platform: iOS
Mapbox SDK version: 3.7.3, 3.7.4

### Steps to trigger behavior

 1. Add a lot of spots with images using MGLSymbolStyleLayer.

### Expected behavior
On SDK 3.6.4
<img width="294" alt="2018-02-16 12 30 53" src="https://user-images.githubusercontent.com/5032192/36284549-b63ac5e2-12b0-11e8-80c0-ea92f52947a2.png">

### Actual behavior
On SDK 3.7.3
<img width="259" alt="2018-02-15 8 00 10" src="https://user-images.githubusercontent.com/5032192/36284905-3a9728a2-12b2-11e8-9c10-6d48ee9f07f9.png">

**Comment by kkaefer** [comment]
@yulian948 can you please what kind of data you're using? The screenshots you posted look like data processing artifacts, not rendering artifacts.

**Comment by yulian948** [comment]
@kkaefer can you tell in more details what should I provide ? What kinds of data are used in MapBox ? 
Sorry, I'm new here and don't fully understand your question.

**Comment by jmkiley** [comment]
Hi @yulian948 =

Could you tell us more about where the data that the points represent come from (for example, are they coming from a GeoJSON file or vector tileset)?

**Comment by yulian948** [comment]
Hi @jmkiley, thanks for the explanation. 
The data is an array of MGLPointFeature.

**Comment by jmkiley** [comment]
Thank you @yulian948. Can you tell us where the coordinates that are being used to create the MGLPointFeatures are coming from?

Could you also provide a minimal test case that reproduces this issue? It would allow us to more quickly examine this issue.

**Comment by yulian948** [comment]
@jmkiley The coordinates comes from our server. It comes as a part of our model object, and is converted to MGLPointFeature (we just set coordinate property of feature, and adding two attributes) before displaying. 

I tried to create minimal test case, but this bug is reproduced only with our custom style, so I can't share it.

**Comment by jfirebaugh** [comment]
@yulian948 If this is still an issue for you, would you be willing to share a test app privately?
