### ISSUE TITLE
port Tileset encoding parameter to SDKs

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-native#11224]
follow up to #10931 where I added an `encoding` option on the `Tileset` class to allow users to specify the encoding of the raster-dem source their using. currently only supports `mapbox` (default) and `terrarium`.

looks like i need to add it in the following places for ios and android
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/MGLTileSource.h
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/MGLTileSource.mm
and the style author guides

https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/TileSet.java

happy to do this if these are the right places to make changes @tobrun @1ec5

**Comment by 1ec5** [comment]
For iOS and macOS, this task would consist of the following changes:

* [ ] Define a `MGLTileSourceOptionRasterDEMEncoding` constant of type `MGLTileSourceOption` (either in MGLTileSource.h or MGLRasterDEMSource.h).
* [ ] Factor out the call to `MGLTileSetFromTileURLTemplates()` inside `-[MGLRasterSource initWithIdentifier:tileURLTemplates:options:]` into an instance method.
* [ ] Override that method in MGLRasterDEMSource to apply `MGLTileSourceOptionRasterDEMEncoding`.
* [ ] Mention the new option in [this documentation](https://github.com/mapbox/mapbox-gl-native/blob/c3bf7c55a1f648e57c3853d555ff5f63c989f8c4/platform/darwin/docs/guides/For%20Style%20Authors.md.ejs#L198) and run `make darwin-style-code` to update the iOS and macOS guides.

**Comment by mollymerp** [comment]
thanks @1ec5 – I'm working on a branch this morning.
one question: what is an "instance method" in the context of the second step you outlined above?

**Comment by 1ec5** [comment]
> Factor out the call to `MGLTileSetFromTileURLTemplates()` inside `-[MGLRasterSource initWithIdentifier:tileURLTemplates:options:]` into an instance method.

To expand on this, there’s currently a call to `MGLTileSetFromTileURLTemplates()` inside `-[MGLRasterSource initWithIdentifier:tileURLTemplates:options:]`. Instead, `-initWithIdentifier:tileURLTemplates:options:` should call `-tileSetWithURLTemplates:options:`, which in turn calls `MGLTileSetFromTileURLTemplates()`. MGLRasterDEMSource can override `-tileSetWithURLTemplates:options:` to first call `super`’s implementation then add its own option handling.

**Comment by mollymerp** [comment]
done in #11274 and #11339
