### ISSUE TITLE
Feature request: Allow client app to add additional sprite sheets to existing style

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#1122]
I realize that annotations is a work in progress, but this would allow the app to add custom marker without the need to duplicate an existing style just to modify its sprite sheet.

The "sprite" dictionary key for a style currently only support a single string. If this were modified to accept either a string or array of string, the user could add custom markers to an existing style.

**Comment by incanus** [comment]
Yep, that's the next milestone for annotations. However, we don't have a good ticket capturing that plan, so here it is :-)

* Now: sprite sheet prebundled
* Next: Runtime raster imagery from Cocoa-side
* Eventual: synced `UIView` objects atop map like user dot & callout are now

**Comment by incanus** [comment]
Ah, here it is: https://github.com/mapbox/mapbox-gl-native/issues/941

**Comment by picciano** [comment]
Very good. Sorry I missed seeing that one.
