### ISSUE TITLE
How to disable interaction MGLPolygon? - iOS 

### ISSUE THREAD

**Issue by eastern-amol** [mapbox/mapbox-gl-native#11234]
Hi Guys, 

I'm using mapbox in my project, I'm facing one issue like Polygon area is getting touch/click, I want disable it. 

Would you please someone guide me how I can do this? I search lot but didn't get any solution on it.

MGLPolygon overlay should not be clickable in my requirement, because its creating problem for markers/MGLAnnotation to detect click.

**Comment by jmkiley** [comment]
One option is to implement a check for the type of annotation that was selected. For example:

```swift
    func mapView(_ mapView: MGLMapView, didSelect annotation: MGLAnnotation) {
        if annotation.isKind(of: MGLPolygon.self) {
            return
        }
        
        print("Point selected")
    }
    ```

**Comment by eastern-amol** [comment]
Hi jmkiley, 

If I add above suggested validation then we need click on marker 2 times, because click its taking for polygon which we added and on second click its taking for marker. which not good as per user point of view.

Please suggest, if any other workaround for this?

**Comment by hernangonzalez** [comment]
I am experiencing a similar issue. MGLPolygon is consuming touches, and preventing other handlers from handling them. i.e. To handle feature touch on a cluster. 
Should this be reopened @jmkiley ? Thank you, H.

**Comment by jmkiley** [comment]
Thanks for following up! This issue is being tracked in https://github.com/mapbox/mapbox-gl-native/issues/10539
