### ISSUE TITLE
didUpdateUserLocation is not called

### ISSUE THREAD

**Issue by fantasticsid** [mapbox/mapbox-gl-native#11236]
**Platform: iOS
**Mapbox SDK version: 3.7.5

### Steps to trigger behavior

```
import UIKit
import Mapbox

class ViewController: UIViewController, MGLMapViewDelegate {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        let url = URL(string: "mapbox://styles/mapbox/streets-v10")
        let mapView = MGLMapView(frame: view.bounds, styleURL: url)
        mapView.delegate = self;
        mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        view.addSubview(mapView)
        mapView.showsUserLocation = true
    }

    func mapViewWillStartLocatingUser(_ mapView: MGLMapView) {
        print("will start locating user\n")
    }
    
    func mapView(_ mapView: MGLMapView, didUpdateUserLocation userLocation: Any!) {
        print("did update user location\n")
    }
    
    func mapViewDidStopLocatingUser(_ mapView: MGLMapView) {
        print("did stop locating user")
    }
    
    func mapView(_ mapView: MGLMapView, didFailToLocateUserWithError error: Error) {
        print("did fail to locate user")
    }
    
    func mapView(_ mapView: MGLMapView, didChangeUserTrackingMode mode: Any!, animated: Bool) {
        print("did change user tracking mode")
    }
    
    func mapViewDidFinishLoadingMap(_ mapView: MGLMapView) {
        print("did finish loading map")
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}
```
### Expected behavior

I see the blue dot that accurately represent my location, but the callback is not called

### Actual behavior
callback is not called, I don't see output of print

**Comment by friedbunny** [comment]
That method signature is incorrect — the `userLocation` type is `MGLUserLocation?`, not `Any!`. I’d expect Xcode to warn about this, like so:

![screen shot 2018-02-19 at 11 16 03 am](https://user-images.githubusercontent.com/1198851/36387312-9c54e9c4-1566-11e8-85ff-274595213203.png)

Unfortunately, our docs generator [doesn’t create correct Swift interfaces](https://github.com/realm/jazzy/issues/609) for some methods/parameters, [`-[MGLMapViewDelegate mapView:didUpdateUserLocation:]`](https://www.mapbox.com/ios-sdk/api/3.7.5/Protocols/MGLMapViewDelegate.html#/c:objc(pl)MGLMapViewDelegate(im)mapView:didUpdateUserLocation:) being one.

Sorry that this bit you, @fantasticsid — we’ll see what we can do about making sure the documentation is corrected.

**Comment by fantasticsid** [comment]
This works! Thank you!
