### ISSUE TITLE
Implement observer for UIApplicationWillResignActiveNotification?

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#11232]
#11229 removed the observer for `UIApplicationWillResignActiveNotification` that was added in https://github.com/mapbox/mapbox-gl-native/pull/11151, because it caused a `sleepGL:`↔`wakeGL:` loop when requesting location permission (#11225).

Way back in #2988, we decided this observer was unnecessary (and, indeed, these observers have caused a fair share of bugs historically).

We should investigate:

1. Do we need to to listen for `UIApplicationWillResignActiveNotification`?
2. If yes, what changes need to be made to `sleepGL:` and `wakeGL:` to avoid #11225.

/cc @julianrex @1ec5 @akitchen

**Comment by 1ec5** [comment]
Lots of things have changed with respect to Location Services permissions since #2988 landed. So I don’t think observing for that notification would’ve caused this loop back then. One factor to consider is that a different sequence of notification is posted when the application launches normally versus when it emerges from background mode (a setup we probably don’t test as rigorously as we used to).

**Comment by friedbunny** [comment]
> I think it should be the responsibility of the host app to request location permissions and when to schedule that. Is that something that's possible currently?

The developer currently implicitly chooses when to ask for permission by enabling `showsUserLocation`, `userTrackingMode`, etc. — the map won’t ask for permission unless the developer tries to use a feature that requires it.

**Comment by julianrex** [comment]
Still valid.

**Comment by julianrex** [comment]
This is happening the context of PR https://github.com/mapbox/mapbox-gl-native/pull/14222.

**Comment by tristanmellett** [comment]
I'm currently Using Mapbox 5.1 and I seem to be having a memory leak causing an error in MapViewWillResign Active. It only happens when I lock the iPhone as soon as the mapview is loading. Apparently 'CPU access for textures with MTLResourceStorageModePrivate storage mode is disallowed.'

**Comment by julianrex** [comment]
Created issue #15806 from the [comment above](https://github.com/mapbox/mapbox-gl-native/issues/11232#issuecomment-541390272).
