### ISSUE TITLE
Move iOS release builds to CircleCI

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#11231]
The builds for our official releases currently happen on Bitrise (https://github.com/mapbox/mapbox-gl-native/pull/10170), but, as we’ve done with our daily CI builds, we should also move release builds to CircleCI.

**Comment by tobrun** [comment]
just as fyi: on android we currently use branch checking to determine if we need to do a release (see circle config [here](https://github.com/mapbox/mapbox-gl-native/blob/master/circle.yml#L406)) though there are plans to move this to using git tags in https://github.com/mapbox/mapbox-gl-native/issues/10551.

**Comment by friedbunny** [comment]
This happened in #11437 — `ios-v3.7.6` was the first iOS release to be deployed using CircleCI. The build/deploy went from ~50 minutes on Bitrise to ~35 minutes on CircleCI.
