### ISSUE TITLE
Create Polygone with border and clear fill color

### ISSUE THREAD

**Issue by JulienLevallois** [mapbox/mapbox-gl-native#11233]
Hi!
Im using mapbox ios sdk to create polygone on my map. I want to create circle with clear fill color and blue stroke color. Im not able to create this....

- (CGFloat)mapView:(MGLMapView *)mapView lineWidthForPolylineAnnotation:(MGLPolyline *)annotation{

or

- (UIColor *)mapView:(MGLMapView *)mapView strokeColorForShapeAnnotation:(MGLShape *)annotation {

dont works...

If someone have an idea :) 
![img_8226](https://user-images.githubusercontent.com/5727223/36340215-a436f694-13d8-11e8-9614-bac25687b65c.jpeg)

- (CGFloat)mapView:(nonnull MGLMapView *)mapView
    lineWidthForPolylineAnnotation:(nonnull MGLPolyline *)annotation;
it never called....

**Comment by jmkiley** [comment]
Thank you for using Mapbox! This repo is for reporting issues or requesting features. For support or "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/), or ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
