### ISSUE TITLE
Break anonid Into Two

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1124]
`anonid` currently records either Advertiser Id (IDFA) or Vendor Id (IDFV) depending [on availability of IDFA](https://github.com/mapbox/mapbox-gl-native/blob/501f9701cd25c004b496dbdf96c8ac45845718be/platform/ios/MGLMapboxEvents.m#L74-L90).  `anonid` should be split into `advertiserId` and `vendorId`.  `advertiserId` should be collected when available using the same logic as is currently in use, and if not available send in an empty string.  `vendorId` should be collected each time.

/cc @willwhite @camilleanne @sbma44 @mikemorris @michaelsteffen

**Comment by bleege** [comment]
Just spilt `anonid` into `advertiserId` and `vendorId`.  If IDFA is not available then `advertiserId` returns the value of "NONE".

**Comment by mikemorris** [comment]
`"NONE"` seems like a strange response, as that string will evaluate to true in JavaScript conditionals checking `if (advertiserid)`, while `""` or `null` would both eval to false.

**Comment by bleege** [comment]
Agreed, but @camilleanne is already making us of it [for WiFi](https://github.com/mapbox/mapbox-gl-native/blob/7cd8daf5a7df41aa8a998a393d10ee7c9215594b/platform/ios/MGLMapboxEvents.m#L337) so I did this for consistency.  Should we change?

**Comment by bleege** [comment]
Just changed `advertiserId`, `cellularNetworkType` and `wifi` to use empty string for data consistency.

**Comment by bleege** [comment]
Upon further discussion with @camilleanne and @edenh it was decided that "NONE" is actually a "legitimate description" of state and should be used where appropriate.  In this case that's `cellularNetworkType` and `wifi`.

**Comment by bleege** [comment]
Restored.

**Comment by bleege** [comment]
Reopening to make this work with the massive refactor ing #1132.  Should just need to re-implement the following commit: 7cd8daf5a7df41aa8a998a393d10ee7c9215594b

**Comment by bleege** [comment]
Just waiting on Travis now for merge approval.  https://travis-ci.org/mapbox/mapbox-gl-native/builds/56117796

**Comment by bleege** [comment]
Travis approved!
