### ISSUE TITLE
Remove leftovers from stop-based functions

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#11247]
We're intending to take advantage of the fact that the upcoming releases of the iOS and Android SDKs are semver-major versions in order to introduce expressions as a complete replacement for the prior stop-based function functionality, and remove the stop-based APIs entirely. (Existing styles which use stop functions will be transparently converted to equivalent expressions when loaded.)

We should review the iOS and Android SDK APIs now that expressions have landed, and confirm that all stop-based function APIs have been removed.

As a second confirmation that we haven't left any lingering APIs which we'd be unable to remove until the next semver-major release, we should make the relevant core code private. This will allow us to refactor the core code at our leisure. (Among other things, such core refactoring may allow us to decrease the binary size.)

**Comment by jfirebaugh** [comment]
I pushed https://github.com/mapbox/mapbox-gl-native/compare/release-boba...11247 to test this out.

In core, the `stringify` functions for `*Function` need to replace stringification of the stops with serialization (from #11156) of the expression. (This should be fine; for `*Function` I believe `stringify` is needed only for `groupByLayout`.)

The whole [`Function`](https://github.com/mapbox/mapbox-gl-native/blob/685b8b2c84e47d8126e924ff3fddc22a96237680/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/functions/Function.java) class hierarchy still exists in the Android SDK. @tobrun is the plan to remove this?

**Comment by tobrun** [comment]
> The whole Function class hierarchy still exists in the Android SDK. @tobrun is the plan to remove this?

Yes, going to tackle this with accessors in #10721, syncing with Ivo on this today.

**Comment by jfirebaugh** [comment]
I updated https://github.com/mapbox/mapbox-gl-native/compare/release-boba...11247 showing that we can now do this cleanup at our leisure; i.e. on `master` sometime after `release-boba` is merged back.

**Comment by jfirebaugh** [comment]
#11509 wound up removing the `stops` member, but there's still significant cleanup work we could do here.

**Comment by jfirebaugh** [comment]
This is currently looking the the number one thing we could do to reduce binary size. If we can remove all the `*Steps` templates and convert JSON directly to expressions, it will probably produce a substantial size savings.
