### ISSUE TITLE
QuickZoom zoom level after zooming in

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11240]
![ezgif com-video-to-gif 43 43](https://user-images.githubusercontent.com/2151639/36389452-668e3514-159f-11e8-92d0-a442c2ece21f.gif)

If you use the quick zoom gestures (double tap and hold) and you zoom based on y-amount of pixels and later zoom back in with same y amount, you don’t end up and the initial zoom level.

cc @LukasPaczos

**Comment by LukasPaczos** [comment]
Debugging the issue I noticed that underlying `ScaleGestureDetector` can return suspicious values
```
D/MapGestureDetector$Scal: scale: factor - 1.1339383
D/MapGestureDetector$Scal: scale: factor - 1.0364736
D/MapGestureDetector$Scal: scale: factor - 0.84954655
D/MapGestureDetector$Scal: scale: factor - 1.3086545
D/MapGestureDetector$Scal: scale: below 0
D/MapGestureDetector$Scal: scale: factor - 0.84537005
D/MapGestureDetector$Scal: scale: factor - 0.8748795
D/MapGestureDetector$Scal: scale: factor - 0.94667435
D/MapGestureDetector$Scal: scale: factor - 1.0942392
D/MapGestureDetector$Scal: scale: factor - 1.2115576
D/MapGestureDetector$Scal: scale: factor - 1.2501236
```
adding clamping to that can result in uneven zoom effect.

We should tackle this issue with https://github.com/mapbox/mapbox-gestures-android/issues/15.

**Comment by LukasPaczos** [comment]
Decreasing the deadzone in https://github.com/mapbox/mapbox-gestures-android/pull/30 helped a lot and I'm not feeling like this one is an issue anymore.
@tobrun, could you re-check `release-boba` on a device that you used for testing in the OP?

**Comment by tobrun** [comment]
:rocket:
