### ISSUE TITLE
Adopt LOCALIZED_STRING_MACRO_NAMES build setting

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#11250]
[Xcode 9.3b2](https://download.developer.apple.com/Developer_Tools/Xcode_9.3_beta_2/Release_Notes_for_Xcode_9.3_beta_2.pdf#page=5) adds a new `LOCALIZED_STRING_MACRO_NAMES` build setting that makes it possible to cleanly customize the set of localization macros. That would allow us to avoid [overloading `NSLocalizedStringWithDefaultValue()`](https://github.com/mapbox/mapbox-gl-native/blob/374bad18c04ae8fea574f85d2149af8aeffb8dcc/platform/ios/DEVELOPING.md#adding-user-facing-text). We should adopt this build setting once we make Xcode 9.3 the minimum required Xcode version for building the SDK from source.

/cc @friedbunny

**Comment by 1ec5** [comment]
> We should adopt this build setting once we make Xcode 9.3 the minimum required Xcode version for building the SDK from source.

At this point, I think it’d be reasonable to increase the minimum required Xcode version from 9.1 (from #10962) to 9.3. `LOCALIZED_STRING_MACRO_NAMES` would allow us to normalize our localization workflow quite a bit. It isn’t uncommon for PRs to omit the required NSBundle+MGLAdditions.h import statement on the first iteration; this change would remove the need to remember that gl-native-specific detail.

**Comment by julianrex** [comment]
Would love to adopt this - and avoid the overloading.
