### ISSUE TITLE
[iOS] Can't seem to be able to prevent world repeating in a clean fashion

### ISSUE THREAD

**Issue by Mcgode** [mapbox/mapbox-gl-native#11255]
Unlike the JS version of the API, I can't seem to be able to find a method to disable continuous world. I can achieve something similar by using the visibleCoordinateBounds property, but it is far less than ideal.

**Comment by jmkiley** [comment]
Thank you for using Mapbox! This repo is for reporting issues or requesting features. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
