### ISSUE TITLE
[android] Backticks mangled in localIdeographFontFamily documentation

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native#11260]
https://www.mapbox.com/android-docs/api/map-sdk/5.3.2/com/mapbox/mapboxsdk/maps/MapboxMapOptions.html#localIdeographFontFamily-java.lang.String-

Looks like a newbie mistake on my part -- is there a limited character set or an implied non-UTF8 encoding for javadoc?

/cc @tobrun

**Comment by tobrun** [comment]
I was already working on fixing this in https://github.com/mapbox/mapbox-gl-native/tree/tvn-javadoc :)

**Comment by ChrisLoer** [comment]
Ah, perfect! I'll try to keep this in mind next time I'm editing the Android docs... 🙇
