### ISSUE TITLE
Android - Bounds in projection invalid

### ISSUE THREAD

**Issue by emerciercontexeo** [mapbox/mapbox-gl-native#11273]
**Platform:Android **
**Mapbox SDK version: Probably all**

The method Projection.getVisibleRegion produce wrong bounds.
The methods returned value is the following : 

```java
return new VisibleRegion(topLeft, topRight, bottomLeft, bottomRight,
      LatLngBounds.from(
        topRight.getLatitude(),
        topRight.getLongitude(),
        bottomLeft.getLatitude(),
        bottomLeft.getLongitude())
    );
```

The results is OK if the bearing == 0

On any others bearing value, taking topRight and bottomLeft of the screen to create the bounds is not correct cause they don't match with southWest and northEast.

A solution could be : 

```java
double latMin = Math.min(Math.min(topLeft.getLatitude(),topRight.getLatitude()), Math.min(bottomRight.getLatitude(),bottomLeft.getLatitude()));
double latMax = Math.max(Math.max(topLeft.getLatitude(),topRight.getLatitude()), Math.max(bottomRight.getLatitude(),bottomLeft.getLatitude()));
double lonMin = Math.min(Math.min(topLeft.getLongitude(),topRight.getLongitude()), Math.min(bottomRight.getLongitude(),bottomLeft.getLongitude()));
double lonMax = Math.max(Math.max(topLeft.getLongitude(),topRight.getLongitude()), Math.max(bottomRight.getLongitude(),bottomLeft.getLongitude()));
return LatLngBounds.from(latMax, lonMax, latMin, lonMin);
```

**Comment by tobrun** [comment]
@emerciercontexeo this was fixed with https://github.com/mapbox/mapbox-gl-native/pull/11226, will pull in these changes for the v5.5.0 release happening next week.

**Comment by emerciercontexeo** [comment]
@tobrun Oh! Sorry, I didn' t see it. Thanks for answer
