### ISSUE TITLE
Art warnings in application log.

### ISSUE THREAD

**Issue by vishalkharat** [mapbox/mapbox-gl-native#11285]
I have added following dependencies in my build.gradle file for accessing mapbox sdk.
However i am getting following logs after launching an application.

02-23 00:04:24.403 10261-10261/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.mapbox.mapboxsdk.location.LocationSource>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapzen/android/lost/api/LostApiClient$ConnectionCallbacks;
02-23 00:04:24.403 10261-10261/? I/art:     at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:52)
02-23 00:04:24.403 10261-10261/? I/art:     at void com.test.TestApplication.initializeApplication() (TestApplication.java:54)
02-23 00:04:24.403 10261-10261/? I/art:     at void com.test.TestApplication.onCreate() (TestApplication.java:48)
02-23 00:04:24.403 10261-10261/? I/art:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1024)
02-23 00:04:24.403 10261-10261/? I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5361)
02-23 00:04:24.403 10261-10261/? I/art:     at void android.app.ActivityThread.-wrap2(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
02-23 00:04:24.403 10261-10261/? I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1528)
02-23 00:04:24.403 10261-10261/? I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
02-23 00:04:24.403 10261-10261/? I/art:     at void android.os.Looper.loop() (Looper.java:154)
02-23 00:04:24.403 10261-10261/? I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
02-23 00:04:24.403 10261-10261/? I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
02-23 00:04:24.403 10261-10261/? I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:865)
02-23 00:04:24.403 10261-10261/? I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:755)
02-23 00:04:24.403 10261-10261/? I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapzen.android.lost.api.LostApiClient$ConnectionCallbacks" on path: DexPathList[[zip file "/data/app/com.test-1/base.apk"],nativeLibraryDirectories=[/data/app/com.test-1/lib/arm, /system/fake-libs, /data/app/com.test-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
02-23 00:04:24.403 10261-10261/? I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
02-23 00:04:24.403 10261-10261/? I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
02-23 00:04:24.403 10261-10261/? I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
02-23 00:04:24.403 10261-10261/? I/art:     at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:52)
02-23 00:04:24.403 10261-10261/? I/art:     at void com.test.TestApplication.initializeApplication() (TestApplication.java:54)
02-23 00:04:24.404 10261-10261/? I/art:     at void com.test.TestApplication.onCreate() (TestApplication.java:48)
02-23 00:04:24.404 10261-10261/? I/art:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1024)
02-23 00:04:24.404 10261-10261/? I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5361)
02-23 00:04:24.404 10261-10261/? I/art:     at void android.app.ActivityThread.-wrap2(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
02-23 00:04:24.404 10261-10261/? I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1528)
02-23 00:04:24.404 10261-10261/? I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
02-23 00:04:24.404 10261-10261/? I/art:     at void android.os.Looper.loop() (Looper.java:154)
02-23 00:04:24.404 10261-10261/? I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
02-23 00:04:24.404 10261-10261/? I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
02-23 00:04:24.404 10261-10261/? I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:865)
02-23 00:04:24.404 10261-10261/? I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:755)
02-23 00:04:24.404 10261-10261/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.mapbox.mapboxsdk.EmptyLocationSource>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/mapboxsdk/location/LocationSource;
02-23 00:04:24.404 10261-10261/? I/art:     at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:52)
02-23 00:04:24.404 10261-10261/? I/art:     at void com.test.TestApplication.initializeApplication() (TestApplication.java:54)
02-23 00:04:24.404 10261-10261/? I/art:     at void com.test.TestApplication.onCreate() (TestApplication.java:48)
02-23 00:04:24.404 10261-10261/? I/art:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1024)
02-23 00:04:24.404 10261-10261/? I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5361)
02-23 00:04:24.404 10261-10261/? I/art:     at void android.app.ActivityThread.-wrap2(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
02-23 00:04:24.404 10261-10261/? I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1528)
02-23 00:04:24.404 10261-10261/? I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
02-23 00:04:24.404 10261-10261/? I/art:     at void android.os.Looper.loop() (Looper.java:154)
02-23 00:04:24.404 10261-10261/? I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
02-23 00:04:24.404 10261-10261/? I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
02-23 00:04:24.404 10261-10261/? I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:865)
02-23 00:04:24.404 10261-10261/? I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:755)
02-23 00:04:24.404 10261-10261/? I/art: Caused by: java.lang.ClassNotFoundException: com.mapbox.mapboxsdk.location.LocationSource
02-23 00:04:24.404 10261-10261/? I/art:     at java.lang.Class java.lang.VMClassLoader.findLoadedClass!(java.lang.ClassLoader, java.lang.String) (VMClassLoader.java:-2)
02-23 00:04:24.404 10261-10261/? I/art:     at java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) (ClassLoader.java:742)
02-23 00:04:24.404 10261-10261/? I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:362)
02-23 00:04:24.404 10261-10261/? I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
02-23 00:04:24.404 10261-10261/? I/art:     at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:52)
02-23 00:04:24.404 10261-10261/? I/art:     at void com.test.TestApplication.initializeApplication() (TestApplication.java:54)
02-23 00:04:24.404 10261-10261/? I/art:     at void com.test.TestApplication.onCreate() (TestApplication.java:48)
02-23 00:04:24.404 10261-10261/? I/art:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1024)
02-23 00:04:24.404 10261-10261/? I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5361)
02-23 00:04:24.404 10261-10261/? I/art:     at void android.app.ActivityThread.-wrap2(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
02-23 00:04:24.405 10261-10261/? I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1528)
02-23 00:04:24.405 10261-10261/? I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
02-23 00:04:24.405 10261-10261/? I/art:     at void android.os.Looper.loop() (Looper.java:154)
02-23 00:04:24.405 10261-10261/? I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
02-23 00:04:24.405 10261-10261/? I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
02-23 00:04:24.405 10261-10261/? I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:865)
02-23 00:04:24.405 10261-10261/? I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:755)
02-23 00:04:24.407 10261-10261/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.mapbox.mapboxsdk.location.LocationSource>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapzen/android/lost/api/LostApiClient$ConnectionCallbacks;
02-23 00:04:24.407 10261-10261/? I/art:     at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:52)
02-23 00:04:24.407 10261-10261/? I/art:     at void com.test.TestApplication.initializeApplication() (TestApplication.java:54)
02-23 00:04:24.407 10261-10261/? I/art:     at void com.test.TestApplication.onCreate() (TestApplication.java:48)
02-23 00:04:24.407 10261-10261/? I/art:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1024)
02-23 00:04:24.407 10261-10261/? I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5361)
02-23 00:04:24.407 10261-10261/? I/art:     at void android.app.ActivityThread.-wrap2(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
02-23 00:04:24.407 10261-10261/? I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1528)
02-23 00:04:24.407 10261-10261/? I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
02-23 00:04:24.407 10261-10261/? I/art:     at void android.os.Looper.loop() (Looper.java:154)
02-23 00:04:24.407 10261-10261/? I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
02-23 00:04:24.407 10261-10261/? I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
02-23 00:04:24.407 10261-10261/? I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:865)
02-23 00:04:24.408 10261-10261/? I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:755)
02-23 00:04:24.408 10261-10261/? I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapzen.android.lost.api.LostApiClient$ConnectionCallbacks" on path: DexPathList[[zip file "/data/app/com.test-1/base.apk"],nativeLibraryDirectories=[/data/app/com.test-1/lib/arm, /system/fake-libs, /data/app/com.test-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
02-23 00:04:24.408 10261-10261/? I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
02-23 00:04:24.408 10261-10261/? I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
02-23 00:04:24.408 10261-10261/? I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
02-23 00:04:24.408 10261-10261/? I/art:     at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:52)
02-23 00:04:24.408 10261-10261/? I/art:     at void com.test.TestApplication.initializeApplication() (TestApplication.java:54)
02-23 00:04:24.408 10261-10261/? I/art:     at void com.test.TestApplication.onCreate() (TestApplication.java:48)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1024)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5361)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.app.ActivityThread.-wrap2(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1528)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.os.Looper.loop() (Looper.java:154)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
02-23 00:04:24.408 10261-10261/? I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
02-23 00:04:24.408 10261-10261/? I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:865)
02-23 00:04:24.408 10261-10261/? I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:755)
02-23 00:04:24.408 10261-10261/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.mapbox.mapboxsdk.location.LocationSource>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapzen/android/lost/api/LostApiClient$ConnectionCallbacks;
02-23 00:04:24.408 10261-10261/? I/art:     at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:52)
02-23 00:04:24.408 10261-10261/? I/art:     at void com.test.TestApplication.initializeApplication() (TestApplication.java:54)
02-23 00:04:24.408 10261-10261/? I/art:     at void com.test.TestApplication.onCreate() (TestApplication.java:48)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1024)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5361)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.app.ActivityThread.-wrap2(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1528)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.os.Looper.loop() (Looper.java:154)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
02-23 00:04:24.408 10261-10261/? I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
02-23 00:04:24.408 10261-10261/? I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:865)
02-23 00:04:24.408 10261-10261/? I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:755)
02-23 00:04:24.408 10261-10261/? I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapzen.android.lost.api.LostApiClient$ConnectionCallbacks" on path: DexPathList[[zip file "/data/app/com.test-1/base.apk"],nativeLibraryDirectories=[/data/app/com.test-1/lib/arm, /system/fake-libs, /data/app/com.test-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
02-23 00:04:24.408 10261-10261/? I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
02-23 00:04:24.408 10261-10261/? I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
02-23 00:04:24.408 10261-10261/? I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
02-23 00:04:24.408 10261-10261/? I/art:     at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:52)
02-23 00:04:24.408 10261-10261/? I/art:     at void com.test.TestApplication.initializeApplication() (TestApplication.java:54)
02-23 00:04:24.408 10261-10261/? I/art:     at void com.test.TestApplication.onCreate() (TestApplication.java:48)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1024)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5361)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.app.ActivityThread.-wrap2(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1528)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.os.Looper.loop() (Looper.java:154)
02-23 00:04:24.408 10261-10261/? I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
02-23 00:04:24.408 10261-10261/? I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
02-23 00:04:24.408 10261-10261/? I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:865)
02-23 00:04:24.408 10261-10261/? I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:755)

**Platform:  Android**
**Mapbox SDK version:**
compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.4.1'){
        transitive=true
    }
    compile ('com.mapbox.mapboxsdk:mapbox-android-geocoder:1.0.0@aar'){
        transitive=true
    }

**Comment by tobrun** [comment]
This is because we made the location provider optional in https://github.com/mapbox/mapbox-gl-native/issues/9403. So the warnings are actually normal behaviour though it would be nice to suppress them.  For that I ticketed out https://github.com/mapbox/mapbox-events-android/issues/68. Closing as this needs to be handled upstream in the core-location module.
