### ISSUE TITLE
[iOS] Incorrect symbols sometimes rendered

### ISSUE THREAD

**Issue by jluxenberg-scoot** [mapbox/mapbox-gl-native#11299]
**Platform:** iOS
**Mapbox SDK version:** 3.7.3 via React Native binding

On iOS, we've had a couple of instances of style corruption. Symbol layers will render an incorrect symbol for points on the layer. In cases where this has happened, the rendered symbols are other symbols that are in our style, but they are not the correct ones.

Our style URL:
mapbox://styles/scoottech/cj3ktak2200032sn445kmt3j4

### Steps to trigger behavior

Haven't figured out reproduction steps yet.

### Expected behavior

Points on symbol layers render with the correct symbol. 

### Actual behavior

A random symbol is rendered. It seems that the mapping is scrambled; e.g. if we have a point on a symbol layer that is supposed to render a "scooter" symbol, it will instead render some other random symbol (e.g. the one we use for garages). The mapping from correct to incorrect symbol seems to be consistent; e.g. if a "scooter" symbol is supposed to be rendered, a "garage" symbol will always render instead.

When the app is in this state, the only thing that fixes it is to delete and re-install the app. It seems to map a given symbol to the wrong symbol consistently

e.g. in this image, all of the pins are rendering the wrong symbol. The "unicorns" should all be regular "scooter" symbols, etc.

![unicorns in sf-](https://user-images.githubusercontent.com/29718740/36625635-3aaf9104-18d8-11e8-9391-13ea9dfca046.png)

**Comment by kkaefer** [comment]
This looks like it's an instance of https://github.com/mapbox/mapbox-gl-native/issues/4117

**Comment by lilykaiser** [comment]
Thanks for reporting this issue @jluxenberg-scoot ! Can I ask for some additional detail around whom this bug affects and when?

- I think you mentioned in our conversation last week that this bug also affects Android but iOS seems to be worse, is that true?
- From your description, it doesn't seem like this bug affects all devices at once, but rather, each device individually at different times. Can you confirm this?
- Is it inevitable that every iOS device will end up in this state, or do some remain unaffected?
