### ISSUE TITLE
Remove marker and add new marker on exact same position and name

### ISSUE THREAD

**Issue by KaRa777** [mapbox/mapbox-gl-native#11306]
I have a strange problem with adding and removing markers.

My use case is that I have a temporary marker which moves to the position on which the user clicked, implemented like this and works good:

    public void AddTemporaryMarker(LatLng position, String name) {
        if (mTemporaryMarker != null) {
            mMap.removeMarker(mTemporaryMarker );
        }

        mTemporaryMarker = mMap.addMarker(new MarkerOptions().position(position).title(name));

    }

If the user clicks a Button the temporary marker should get permanent, implemented like this:

    public void TemporaryMarkerToPin()
    {
        if(mTemporaryMarker != null){
            mMap.removeMarker(mTemporaryMarker );
        }

        Marker marker = mMap.addMarker(new MarkerOptions().position(mTemporaryMarker .getPosition()).title(mTemporaryMarker .getTitle()));
        marker.setId(markerID);
        markerID++;
        Pin pin = new Pin(marker);
        mPins.add(pin);
    }

Now if I click on the new marker, onMarkerClick is not triggered. Strangly I got an other method which loads markers on startup.The difference is this is called from the onMapReady and the upper one from an ButtonClickListener:

    public void AddPin(LatLng position, String name)
    {
        Marker marker = mMap.addMarker(new MarkerOptions().position(position).title(name));
        marker.setId(markerID);
        markerID++;
        Pin pin = new Pin(marker);
        mPins.add(pin);
    }

Because the markers added on startup are clickable I guess it has something to do with removing a marker and setting a new one to the exact same position. I also tried to move the temporary marker afterwards with no success.

**Platform: Android
**Mapbox SDK version: 5.4.1

### Steps to trigger behavior

 1. Add a marker with addMarker
 2. Remove this marker with removeMarker
 3. Add a new marker with addMarker on the exact same position and name as the removed marker.

### Expected behavior

New marker is clickable.

### Actual behavior

New marker is not cklickable.

**Comment by tobrun** [comment]
@KaRa777 the Marker#setId method is not to be used by end users. It's marked as to only be used as an internal API. If you need a new id, you will need to create a new marker. If you don't want to show the InfoWindow when the marker is clicked, you can return `true` from OnMarkerClickListener. Let us know if you have any questions, closing for now.
