### ISSUE TITLE
How Can i set Pulsing (" marker.setAnchor(0.5f, 1.0f + 2 * t);") not working. in mapbox is there any solution ? or else any other type of animation which can we set on marker with the help of marker marker will bounce on map automatically

### ISSUE THREAD

**Issue by lovekothari123** [mapbox/mapbox-gl-native#11301]
want to set pulsing on a map means -- when my map will open marker will bounce on the map automatically is there any solution for that when we using GOOGLE MAP and we set on " marker.setAnchor(0.5f, 1.0f + 2 * t);"
it will start bounce but this method not supported in map box. if anyone knows this so plz help me thank~you.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by afanasy** [comment]
I'm interested in this too. Would be great to have a link to working code.
