### ISSUE TITLE
Different annotation images using clusters. 

### ISSUE THREAD

**Issue by amrit42087** [mapbox/mapbox-gl-native#11328]
Hello,

I am using MapBox in one of my app and I have 2 different type of annotations, which I wish to look different using different images. 
But if I use clusters and pins get unclustered on zooming in there is no way, I can pass two seprate images. 

`         if item.title == "campsites" {
                imageIdentifier = "camp"
                self.myMapView.style!.setImage(#imageLiteral(resourceName: "cabin"), forName: imageIdentifier)
            } else if item.title == "scenic_locations" {
                imageIdentifier = "scenic"
                self.myMapView.style!.setImage(#imageLiteral(resourceName: "closed cabin"), forName: imageIdentifier)
            }`

I tried to use this code. But what ever is the last item, all images become same. 
I have seen same issue reported earlier also. Is there a solution already?

**Swift 4**
**Mapbox SDK version: Mapbox-iOS-SDK', '~> 3.4**

Am I right about the issue or I am doing something wrong.

**Comment by jmkiley** [comment]
Thank you for using Mapbox! This repo is for reporting issues or requesting features. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
