### ISSUE TITLE
Failed to load source mapbox://mapbox.mapbox-traffic-v1: bounds latitude values must be between -90 and 90 with bottom less than top

### ISSUE THREAD

**Issue by kingfisherphuoc** [mapbox/mapbox-gl-native#11330]
**Platform: Android**
**Mapbox SDK version: 5.4.1**

### Steps to trigger behavior

 I tried to load traffic style in MapView, but I got this issue, then the map style was not loaded.
```
Failed to load source mapbox://mapbox.mapbox-traffic-v1: bounds latitude values must be between -90 and 90 with bottom less than top
```

### Expected behavior
The traffic style is loaded properly.
### Actual behavior
The above issue.

**Comment by tobrun** [comment]
@kingfisherphuoc thank you for the report, this is fixed with https://github.com/mapbox/mapbox-gl-native/pull/11178 and will ship in the upcoming 5.5.0 release. We aim to release this week or next at latest.
