### ISSUE TITLE
mail metrics erroneously reports false

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1134]
If `MFMailComposeViewController` is not found, mail setup status can't be checked. It might not be found because its framework isn't linked in, but email could still be setup. The `canSendMail` method is only meant to check that mail is setup before attempting to send. 

/cc @bleege

**Comment by bleege** [comment]
Discussed with @camilleanne @edenh @incanus this afternoon and decided to pull the `enabled.mail` metric for now as the current setup "only tells us if the app is using email sending at all, not if email is setup on the device".

**Comment by bleege** [comment]
Removed and merged!
