### ISSUE TITLE
Camera is not centered on the point when easeCamera is called with LatLngBounds argument and MapboxMap paddings are set

### ISSUE THREAD

**Issue by fdermishin-radargeo** [mapbox/mapbox-gl-native#11340]
**Platform: Android**
**Mapbox SDK version: 5.4.1**

### Steps to trigger behavior

 1. Set bottom padding as half of the screen width (Kotlin code below)

            mapboxMap.setPadding(padding[0], padding[1], padding[2], screenHeightPixels / 2)

 2. Animate the camera

            // Case 1:
            val offset = 1e-3
            val latLngBounds: LatLngBounds = LatLngBounds.Builder()
                    .include(LatLng(latLng.latitude - offset, latLng.longitude - offset))
                    .include(LatLng(latLng.latitude - offset, latLng.longitude + offset))
                    .include(LatLng(latLng.latitude + offset, latLng.longitude + offset))
                    .include(LatLng(latLng.latitude + offset, latLng.longitude - offset))
                    .build()
            mapboxMap.easeCamera(CameraUpdateFactory.newLatLngBounds(latLngBounds, 0))

            // Case 2:
            mapboxMap.easeCamera(CameraUpdateFactory.newLatLng(latLng))

### Expected behavior
Camera is centered at one quarter of the screen height after the animation is finished in both cases.

### Actual behavior
Camera is centered at one quarter of the screen height in case 2 as expected, but in case 1 it is incorrectly centered at the top of the screen. When I change `offset` to 1e-4 then the center of the camera is slightly shifted from the correct position. Longitude is about 55 degrees north.

**Comment by LukasPaczos** [comment]
Thanks for reporting this @fdermishin-radargeo. I was able to reproduce the issue, fix will be included in the `6.0.0-beta.4`.

**Comment by tobrun** [comment]
This landed with #11410
