### ISSUE TITLE
Using sortIndex to skip duplicates in FeatureIndex::query is incorrect(dead code).

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#11357]
**Platform:All
**Mapbox SDK version:Master

### Steps to trigger behavior

The following line tries to skip analyzing duplicate features by comparing the sortIndex

https://github.com/mapbox/mapbox-gl-native/blob/25cfb5863c9ac3705d2bcf4086c237608264e3ae/src/mbgl/geometry/feature_index.cpp#L72 

This condition will never be true because sortIndex is a data member that is continuously incremented in FeatureIndex::insert

https://github.com/mapbox/mapbox-gl-native/blob/25cfb5863c9ac3705d2bcf4086c237608264e3ae/src/mbgl/geometry/feature_index.cpp#L30

### Expected behavior
To skip duplicates FeatureIndex.index could be used for Points, LineString and Polygons. It cannot be used for MultiLineString and MultiPolygons.

**Comment by jfirebaugh** [comment]
cc @ansis
