### ISSUE TITLE
iOS clustering

### ISSUE THREAD

**Issue by camh** [mapbox/mapbox-gl-native#11355]
I'm using the MapBox iOS SDK version 3.7.1.

My app generates a source and style layers to cluster icons on a map. My app code works essentially the same as the provided clustering example: https://www.mapbox.com/ios-sdk/examples/clustering/

How can I get more information from a cluster?

For example in the tutorial, you can use `visibleFeatures(in: rect, styleLayerIdentifiers: ["clusteredPorts"])`, which returns an array of `MGLPointFeature`s.

Each of those has some basic information like lat, long, and point count … but not much else.

What points does that cluster represent? Is there a way to get the `MGLPointFeature`s of a particular cluster? What zoom level will this cluster disappear? Is there a way other than `visibleFeatures(in: styleLayerIdentifiers:)` to get information about the clustering? Is there any way to access any other clustering options other than the three options defined in `MGLShapeSource`?

Since this is the only way to cluster points with MapBox on iOS (since annotation view-backed clustering is not available) I expected it to be very customizable and flexible. Is it not?

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
