### ISSUE TITLE
Support vector tile rendered to raster in Java

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-native#11361]
Hi:

I am not familiar with C++, so I wonder if we can use java to render the vector tile to raster?

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by exotfboy** [comment]
@jfirebaugh 

Are you serious? 

You mean I have to go to a company for a technical problem of a open source project?

Furthermore,  `mapboxgl-native` support different platform exclude `java`, so isn't a feature request?

I doubt if you read my question carefully.
