### ISSUE TITLE
How can I adjust the size of Attribute?

### ISSUE THREAD

**Issue by naykun** [mapbox/mapbox-gl-native#11362]
**Platform:**

Browser Chrome
OS Windows 10

**Mapbox SDK version:**

v0.38.0/mapbox-gl.js

### Steps to trigger behavior
mapboxgl.accessToken ='-----------';
    var map = new mapboxgl.Map({
        container: 'main',
        style: 'mapbox://styles/----------------',
        center:[116.402030, 39.937034],
        zoom:12
    });
just as the basic setting in the document
### Expected behavior
A map with an normal size attribution.
### Actual behavior
![image](https://user-images.githubusercontent.com/20919663/36885120-faeaf584-1e1f-11e8-81a4-2f8741d3aceb.png)
Obviously the attribution is too large. How can I adjust it? 

I have tried to change the value of compact in AttributionControl (https://www.mapbox.com/mapbox-gl-js/api/#attributioncontrol) . But it didn't work. Thanks a lot.

**Comment by tobrun** [comment]
@naykun thank you for reaching out, can you repost your issue in https://github.com/mapbox/mapbox-gl-js/issues? This repo is reporting issues for gl-native.

**Comment by naykun** [comment]
I'm sorry for that. Thank you any way.
