### ISSUE TITLE
Feature request for Snapshotter#latLngForPixel

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11365]
Currently we expose `pixelForLatLng` api on MapSnapshotter to allow to place images (eg. a marker) on a snapshot. Capturing from a user:

> have a latLngForPixel method in addition to pixelForLatLng. That would allow for things like looking up data based on the LatLng inside the image the user clicked.

**Comment by julianrex** [comment]
Making a note: we'll need to add the same functionality (as in https://github.com/mapbox/mapbox-gl-native/pull/12221) to iOS. i.e. getting lat/long from a snapshot coordinate. /cc @lilykaiser

**Comment by julianrex** [comment]
I went ahead and added the iOS functionality: https://github.com/mapbox/mapbox-gl-native/pull/12221/commits/69ec5f0188c56063ff36a181ca2e356c65253225
