### ISSUE TITLE
Mapbox-iOS: Polygons created at runtime dynamically not showing up

### ISSUE THREAD

**Issue by saru2020** [mapbox/mapbox-gl-native#11376]
**Platform:** iOS
**Language:** Objective C
**Mapbox SDK version:** 3.7

**Here's the code:**
<img width="808" alt="mapbox- polygon issue" src="https://user-images.githubusercontent.com/1034916/36935347-ebacb8f2-1f1c-11e8-9d21-4f2ee5e41b2f.png">

**Notes:**
1.) MGLShapeSource *polygonSource;
2.) MGLPolygon *polygon;
3.) I tried running this in the main thread and am pretty sure that it's not a thread issue.
4.) [This](https://www.mapbox.com/ios-sdk/examples/polygon/) sample with static coordinates works very well.

#### Simulator Behaviour
It is weird. 
Polygon is displayed when I step over (In Debugging/Breakpoint mode) from Line: 212 and I can see the log from Line: 219 as below:
"self.polygon: <MGLPolygon: 0x6040004a2be0; count = 12; bounds = { sw = {45.5, -122.7}, ne = {45.5, -122.7}}>"

#### Device Behaviour
No polygon is displayed

### Steps to trigger behavior

 1. Form a polygon object with dynamically calculated coordinates
 2. Assign it to the shape of the source var

### Expected behavior
The polygon should be displayed

### Actual behavior
The polygon is not displayed (But, weird that it's displayed in debugging mode)

**-------------------- X --------------------**

What am I missing here?

Any help/guidance would be great! 

Thanks!

**Comment by fabian-guerra** [comment]
Hi, @saru2020. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).

**Comment by saru2020** [comment]
Hi, 
Thanks for replying back @fabian-guerra I did know that.
I'm facing issue with this API: "[MGLPolygon polygonWithCoordinates:points count:numberOfPoints];" (As clearly described above) when the dynamic coordinates are passed to it, the API doesn't return the polygon, it simply returns null. 
Should I still be posting this on StackOverflow?

**Comment by jmkiley** [comment]
Hi @saru2020, 

From the screenshot you posted above, it does not appear that the polygon is being added to the map. For example, it looks like line 213 is commented out.

**Comment by saru2020** [comment]
Hi @jmkiley ,
I'm not adding it directly to the map as annotation instead, I'm adding the polygon to the polygonSource(MGLShapeSource) [Refer: Line 217] that has been already added to the map.
Its very obvious that the issue is with this API: "[MGLPolygon polygonWithCoordinates:points count:numberOfPoints];", because, I tried printing out the polygon [Refer: Line 213] and it printed out as null.
Hope that clarifies your doubt.  

Any other clue?

**Comment by fabian-guerra** [comment]
Hi, @saru2020. I did try making a polygon with runtime coordinates, and didn't found a problem. As @jmkiley pointed the issue may be in your code elsewhere. 

If you think there is still an issue please feel to reopen this ticket and add a code snippet or app sample that help us trace it.

**Comment by saru2020** [comment]
I'm very much comfortable with sharing the code, as it was already open-sourced with GoogleMaps API's but I am tried to achieve the same with the MapBox API's now.
[Here's](https://www.dropbox.com/s/und5alzlwheyabd/SARMapDrawView_Sample_ForMapBoxDebugging.zip?dl=0) the sample code. 
Kindly, let me know if you need anything else from my end. Thanks!

**Comment by jmkiley** [comment]
Hi @saru2020 -

Happy to help with this. Please send that sample code, along with your question, to [our support team](https://www.mapbox.com/contact/support/). Thank you!
