### ISSUE TITLE
Incorrect bounding box for polylines across the antimeridian

### ISSUE THREAD

**Issue by invliD** [mapbox/mapbox-gl-native#11377]
**Platform:** iOS
**Mapbox SDK version:** 3.7.5

### Steps to trigger behavior

 1. Render a MapView
 2. Add an `MGLPolyline` with (at least) two points around the antimeridian.
 3. Center the polyline using `mapView.setVisibleCoordinateBounds(line.overlayBounds, …)` or `mapView.showAnnotations([line], …)`.

### Expected behavior
The map is centered around the line with its entire length in view

### Actual behavior
The map shows as much of the world as possible with the current aspect ratio, splitting the line in two.
See screenshot of a geodesic line from San Francisco to Shanghai:
<img width="375" alt="bildschirmfoto 2018-03-03 um 21 48 16" src="https://user-images.githubusercontent.com/42910/36942640-9d7d6018-1f2c-11e8-8a2a-003eff74bdbc.png">

### Additional information
`MGLPolyline` does not have its own implementation for `overlayBounds`, it falls back to `MGLMultiPoint`'s. That implementation goes through all points and figures out the bounding box by `min`/`max`ing the next point's lat/long with the current bounds. This is not an unreasonable implementation as multiple points don't have any clear structure to them. It is, however, debatable whether the bounds of (0,179) and (0,-179) should actually be longitudes 179 to 181 instead of -179 to 179.
In an `MGLPolyline`, points actually have a structure, so I claim this behavior is definitely unexpected and unwanted most of the time.

An additional problem in the current implementation of `overlayBounds` is the fact that it returns an "empty" bounding box if a point is "invalid" (e.g. abs(longitude) > 180). Since using longitudes > 180 or < -180 is *the* mechanism to render lines across the antimeridian, all such lines will produce an incorrect bounding box.

**Comment by fabian-guerra** [comment]
Hi, @invliD. Thank you for using Mapbox. Please refer to the [documentation](https://www.mapbox.com/ios-sdk/api/3.7.5/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)visibleCoordinateBounds) to learn how to use coordinates that straddle the antimeridian.

**Comment by invliD** [comment]
I know how I could achieve this myself. This issue is about the unexpected/broken behavior of overlayBounds. It doesn’t even return a valid bounding box for any line that crosses the antimeridian.

**Comment by fabian-guerra** [comment]
Hi, @invliD. Thank you for the follow up and clarification. I am reopening this ticket.

**Comment by 1ec5** [comment]
The fix is to apply a solution similar to #11265 in the `overlayBounds` property’s implementation.

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/11783
