### ISSUE TITLE
Include OkHttp 3.10.0 breaking changes fixes in boba

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#11371]
Re. https://github.com/mapbox/mapbox-gl-native/issues/11325.
In order to fix breaking changes that come with OkHttp `3.10.0` for the upcoming `v6.0.0` release, we need to bump the version of the new telemetry library to the one that includes fix tracked by https://github.com/mapbox/mapbox-events-android/issues/69.

Fix for `v5.5.0` landed with https://github.com/mapbox/mapbox-gl-native/pull/11338.

/cc @Guardiola31337 @tobrun

**Comment by Guardiola31337** [comment]
> fix tracked by mapbox/mapbox-events-android#69

PR which fixes ☝️ https://github.com/mapbox/mapbox-events-android/pull/72

**Comment by Guardiola31337** [comment]
Noting here that https://github.com/mapbox/mapbox-events-android/pull/72 landed.

**Comment by tobrun** [comment]
landed with https://github.com/mapbox/mapbox-gl-native/pull/11474
