### ISSUE TITLE
How to pan, rotate & zoom to around different golf holes?

### ISSUE THREAD

**Issue by dan-burt** [mapbox/mapbox-gl-native#11385]
I would like to be able to zoom around an iOS app selecting the different holes on a golf course, so that:

- the teebox is at the bottom & middle of the screen
- the green is at the top & middle of the screen

This means the bearing / heading will change every time. I am trying to figure out the best way to do this with MGLCoordinateBounds, and have messed around with various coordinates but none are ideal. The coordinates used below were obtained by running my test app on my iPhone, manually pinch & zooming to show the ideal zoom & rotation, then running `print(mapView.visibleCoordinateBounds)` to obtain the coordinates of the current screen to use. I have also tried the `behindTee` & `pastGreen` coordinates as well.

Current code:

```
@IBAction func buttonHole13Tapped(_ sender: UIButton) {
        
        let behindTee = CLLocationCoordinate2D(latitude: 53.874111, longitude: -1.476129)
        let pastGreen = CLLocationCoordinate2D(latitude: 53.872808, longitude: -1.474248)
        let behindTeePin = MGLPointAnnotation()
        behindTeePin.coordinate = behindTee
        let pastGreenPin = MGLPointAnnotation()
        pastGreenPin.coordinate = pastGreen
        
        let boundSW = CLLocationCoordinate2D(latitude: 53.872451989108072, longitude: -1.4768923018508531)
        let pinSW = MGLPointAnnotation()
        pinSW.coordinate = boundSW
        pinSW.title = "SW"
        let boundNE = CLLocationCoordinate2D(latitude: 53.87454639312665, longitude: -1.4734744847826278)
        let pinNE = MGLPointAnnotation()
        pinNE.title = "NE"
        pinNE.coordinate = boundNE
        let bounds = MGLCoordinateBounds(sw: boundSW, ne: boundNE)
        
        let bearingOrig = radianToDegree(radian: bearingToLocationRadian2(firstLocation: behindTee, secondLocation: pastGreen))

        mapView.setDirection(bearingOrig, animated: false)
        mapView.setVisibleCoordinateBounds(bounds, animated: true)
        //mapView.addAnnotations([behindTeePin, pastGreenPin])
        mapView.addAnnotations([pinSW, pinNE])
        
        
        
    }

```

Produces the attached image, with MGLPointAnnotations for the CLLocationCoordinate2D points used for SW & NE... But it should show the area in the red box (or similar).
![img_4462 with box](https://user-images.githubusercontent.com/29703514/36977179-317fc778-2078-11e8-816f-07fa3688b79d.PNG)

Is this because of the rotation messing up SW & NE?
Can I request some help please?

**Comment by fabian-guerra** [comment]
Hi, @dan-burt. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
