### ISSUE TITLE
[Android] How to use SymbolLayer with custom view?

### ISSUE THREAD

**Issue by PhanVanLinh** [mapbox/mapbox-gl-native#11381]
I am using many `MarkerView` with customview which has animation in map.  However, it still have problem when zoom or move map (example `MarkerView` image is not display fully or animation stop).
I know that  `MarkerView` is deprecated so I plan to use `SymbolLayer`. Also after checking this document (https://www.mapbox.com/help/markers/#add-markers-in-android), I think that `SymbolLayer` is suitable for my case.
However, after check `SymbolLayer` demo below, I can not find the way to use SymbolLayer with custom view?
https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/BasicSymbolLayerActivity.java
Please help me. Thanks you.

**Comment by tobrun** [comment]
@PhanVanLinh take a look at this [blogpost](https://blog.mapbox.com/a-guide-to-the-android-symbollayer-api-5daac7b66f2c) and this [example code](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java).

**Comment by PhanVanLinh** [comment]
@tobrun Thank you for your supporting. However, I see that in all blog post and demo, you only add 1 single image for each marker (SymbolLayer).
My requirement now is I need to add a complex view to each marker (a view content 2 image, 1 view below 2 image with animation scale up/scale down). Below I used `MapboxMap.MarkerViewAdapter` follow here https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java

**Comment by tobrun** [comment]
@PhanVanLinh the example code linked above is generating a different image from an Android SDK view for each marker. It uses the `{}` to look up the image id you specified in the source and added as id when creating the image.

See [here](https://github.com/mapbox/mapbox-gl-native/blob/release-agua/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java#L222) for the `{}`-syntax. We are generating different images [here](https://github.com/mapbox/mapbox-gl-native/blob/release-agua/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java#L254) where countryname = the id.

**Comment by PhanVanLinh** [comment]
@tobrun Thank you. I understood about different images but how to create animation, in my case I need add both image and animation like 
![mapbox_symbol_layer_animation](https://user-images.githubusercontent.com/15084259/37023973-33f7fc7c-215a-11e8-901a-fdf8718f3788.gif)

**Comment by tobrun** [comment]
As shown in the blogpost that is a second SymbolLayer, full code for the blogpost example is [here](https://github.com/mapbox/mapbox-android-demo/blob/1951b4b48f977db4ea3df54dfdcdc1efddf97568/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/SymbolLayerExampleActivity.java).

**Comment by PhanVanLinh** [comment]
@tobrun Thank you for sharing the full example. However, I still have 2 questions.
After I checked all demos, I see that: To display a custom view (xml layout) to map using `SymbolLayer` we need to convert this custom view to bitmap then add it to SymbolLayer.
Therefore, I think currently we cannot use a android custom view (xml layout) directly for SymbolLayer like MarkerView do right?

Another problem is about animation.
After I check the demo, I see there is 2 ways for apply animation.
1) Use Animator
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/AnimatedSymbolLayerActivity.java
2) Use exponential
https://github.com/mapbox/mapbox-android-demo/blob/1951b4b48f977db4ea3df54dfdcdc1efddf97568/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/SymbolLayerExampleActivity.java#L249
Which way is better for performance or it is same?

**Comment by tobrun** [comment]
> android custom view (xml layout) directly for SymbolLayer like MarkerView

yes correct, we discarded the idea of synchronising an Android SDK view on top of the map. This is not performant and doesn't match the map projection correctly.

> 2 ways for apply animation

The best is to use the exponential variant, this uses data driven styling to animate the map style properties and doesn't require to update the underlying data as with animators.

**Comment by SamStenner** [comment]
> we discarded the idea of synchronising an Android SDK view on top of the map. This is not performant and doesn't match the map projection correctly.

This doesn't seem like a satisfactory solution at all. Our iOS app can easily add a UIView to the map as a marker, so why can't we on Android? The MarkerView allows this. The MarkerView does indeed have some weird lag / floating behaviour, but if it can be matched on iOS then why not Android? iOS doesn't have anything Android doesn't in this sense, so I find it hard to believe that this isn't achievable.
