### ISSUE TITLE
port new labeling to -native

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#1139]
https://github.com/mapbox/mapbox-gl-js/pull/1079

**Comment by mikemorris** [comment]
Oooh, will be great to get this into native!

**Comment by ansis** [comment]
Large parts of this are ported: https://github.com/mapbox/mapbox-gl-native/tree/new-labelling

It's working (without rotation).

- [ ] redo placement when map rotates
- [ ] optimize getGlyphQuads in -js and then port that
- [ ] reparse overscaled tiles to get better density at high zooms https://github.com/mapbox/mapbox-gl-native/issues/912
- [ ] port tests

Redoing placement when map rotates looks like it'll be the hard part because source stuff and tile parsing is fairly different in -native.

**Comment by ansis** [comment]
now at https://github.com/mapbox/mapbox-gl-native/pull/1666
