### ISSUE TITLE
Remove java8 language features from SDK

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11392]
At Google I/O last year, support for java 8 languages features was announced. With the upcoming 6.0.0 release we enabled this and migrated the codebase to leverage these features (eg. Lambda). Now we are noticing that users aren't able to compile if they don't enable this configuration in their build.gradle (see https://github.com/mapbox/mapbox-gl-native/issues/11378 as example). Capturing from internal conversations that as a library we should not enforce this configuration. Let's revert these changes for the SDK and keep the configuration for the test application.

**Comment by LukasPaczos** [comment]
Landed with https://github.com/mapbox/mapbox-gl-native/pull/11398.
