### ISSUE TITLE
Visibility property lacks Expression argument

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#11396]
Currently, the `PropertyFactory#visibility()` is missing the `Expression` type argument, even though it accepts `Function`.

**Comment by jfirebaugh** [comment]
`visibility` doesn't support expressions. (It doesn't support functions either, so accepting `Function` is probably a bug.)

**Comment by tobrun** [comment]
For reference you can verify if a layout or paint property supports expressions if they are listed for having data-driven styling support. eg. https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-line-visibility
