### ISSUE TITLE
Add custom view to marker android

### ISSUE THREAD

**Issue by Dhvl-Golakiya** [mapbox/mapbox-gl-native#11395]
Hi,

I want to add a custom view to the marker. I checked Symbol layers and we can add images to it But in my case, I have four different images and all are set in a view like below image:
![screen shot 2018-03-06 at 4 11 37 pm](https://user-images.githubusercontent.com/9317298/37028127-686dd55e-2159-11e8-8e38-4668e7936e0d.png)

I am doing this on iOS by adding Custom view but On Android, I found we can add the only image so first, I create a view and then take its snapshot and add to the marker. 
```
Bitmap bitmap = createDrawableFromView(context, parentLayout);// Here I am taking snapshot of parentLayout
IconFactory iconFactory = IconFactory.getInstance(context);
Icon icon = iconFactory.fromBitmap(bitmap);//Convert Bitmap to Icon
mapboxMap.addMarker(new MarkerOptions()
                        .position(new LatLng(activityObject.getLatitude(), activityObject.getLongitude()))
                        .icon(icon));
```
But all images are loading from server so creating a snapshot of every view is not possible when I have more markers. So are there any way so I can add a view to Marker directly like on iOS.

**Comment by tobrun** [comment]
We used to have the concept of MarkerView (atm still in the codebase but deprecated). This concept is the equivalent of the iOS API and allows to synchronise Android SDK views on top of the map. That said we are not actively looking into reintegrating such an api atm. Feel free to use the deprecated one for now.

**Comment by Dhvl-Golakiya** [comment]
Thanks @tobrun
