### ISSUE TITLE
Adding Custom Annotation in Mapbox Crashing - [MGLMAPView installAnnotationImage](MGLAnnotationImage*) - iOS

### ISSUE THREAD

**Issue by siddharthadeb** [mapbox/mapbox-gl-native#11393]
**Platform:**
iOS 11.2.6
**Mapbox SDK version:**
pod 'Mapbox-iOS-SDK', '~> 3.7'
### Steps to trigger behavior

 1. Adding custom annotation with custom image with delegate methods 
 2.
self.data contains all  CustomClassAnnotation data. 
CLLocationCoordinate2D coordinates; 
 for (CustomClassAnnotationView *annotation in self.data) {
        coordinates = annotation.coordinate;
 CustomClassAnnotation *points = [[CustomClassAnnotation alloc]init];
        points.coordinate = coordinates;
        points.customImage = annotation.annotationImage;
        points.idAnnotationView = annotation.idAnnotationView;
        [self.mapbox addAnnotation:points];
}
 3. if I add custom image with calling with MAPBOX delegate methods - I am getting the crash.
- (MGLAnnotationImage *)mapView:(MGLMapView *)mapView imageForAnnotation:(id <MGLAnnotation>)annotation {
}
### Expected behavior
Add custom annotation with custom image in mapbox.
### Actual behavior
Getting A crash with Bad-Excess - with break on -  [MGLMAPView installAnnotationImage](MGLAnnotationImage*).

Please Help me to resolve it. Urgent !!!!

**Comment by fabian-guerra** [comment]
Hi, @siddharthadeb. Thank you for using Mapbox. I am sorry to hear you are having some issues. Could you please take a look at this [example](https://www.mapbox.com/ios-sdk/examples/annotation-view-image/), and in case you are still having crashes please add a code snippet or sample app that help us track the issue.

**Comment by friedbunny** [comment]
This doesn’t currently appear to be a bug in the SDK and there’s a separate support thread playing out in private — closing here.
