### ISSUE TITLE
How to draw a path for user foot steps in iOS?

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [mapbox/mapbox-gl-native#11403]
Thanks for the great library. I am going to use this library for my iOS app.

But, my requirement is, if user located some place and he started navigating from that place to other place by walking, I want to draw a path from his starting point to end point like a diagram for his foot steps.

How can I achieve this using this library, can you please suggest/guide me?

**Comment by lloydsheng** [comment]
It seems the feature is about navigation, i think this library may help you:
https://github.com/mapbox/mapbox-navigation-ios

**Comment by AnilkumarRabhasa** [comment]
@lloydsheng thanks for quick response, really appreciate you. But, using this library can I load GeoJson java script file to show data layer in iOS?

**Comment by lloydsheng** [comment]
@AnilkumarRabhasa you can do it with this sample:
https://www.mapbox.com/ios-sdk/examples/line-geojson/
Btw, there are some other examples will help you learn about how to use Mapbox.
https://www.mapbox.com/ios-sdk/examples/

**Comment by AnilkumarRabhasa** [comment]
@lloydsheng I have 2 requirements.

1. I have to load geojson file to maps and need to show as layer
2. From user location, once he starts navigating/footsteps I have to create a path from his starting point to end point for all his foot steps.

So, these two requirements are possible by using MapBox? or Mapbox navigation?

Which one can I go to achieve my requirements?

Can you guide me while I am very new to MapBox library.

**Comment by fabian-guerra** [comment]
Hi, @AnilkumarRabhasa. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).

Also take a look at this [comment](https://github.com/mapbox/mapbox-gl-native/issues/11403#issuecomment-371088938) links.
