### ISSUE TITLE
Error generating signed apk

### ISSUE THREAD

**Issue by Jayce2177** [mapbox/mapbox-gl-native#11400]
This is the error I get when I am trying to generate my signed APK file. I do not get this error when I am using a debug version though, only when I go to sign the apk.

Warning:com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerOptions: can't find referenced class com.google.auto.value.AutoValue
Warning:com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerOptions$Builder: can't find referenced class com.google.auto.value.AutoValue$Builder
Warning:com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerOptions$Builder: can't find referenced class com.google.auto.value.AutoValue
Warning:com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerOptions$Builder: can't find referenced class com.google.auto.value.AutoValue$Builder
Warning:okhttp3.internal.platform.ConscryptPlatform: can't find referenced class org.conscrypt.OpenSSLProvider
Warning:okhttp3.internal.platform.ConscryptPlatform: can't find referenced class org.conscrypt.Conscrypt

my build.gradle includes these:

// MAP BOX
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.5.0@aar') {
        transitive = true
    }

implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.4.0'

This is becoming so frustrating as there is very limited documentation or tutorials and the example apps don't even work without crashing or being able to generate a signed apk.

**Comment by LukasPaczos** [comment]
Thanks for reporting your issue @Jayce2177. Unfortunately, this compile exception is due to `proguard` settings found in the `LocationLayerPlugin` project.

Please head to https://github.com/mapbox/mapbox-plugins-android/issues and report your issue there as it's not directly connected with the Maps SDK.

**Comment by AmirMehr** [comment]
I have the same issue, how to solve it?

**Comment by LukasPaczos** [comment]
Hey @AmirMehr, which versions of the `LocationLayerPlugin` and/or Maps SDK are you using?

**Comment by AmirMehr** [comment]
Hi, 6.3.0:
 implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.3.0'

**Comment by LukasPaczos** [comment]
If you are only using the Maps SDK, this is a separate issue. Would you mind creating a new issue ticket and describing your problem?
