### ISSUE TITLE
World-scale TileJSON bounds cause incorrect map rendering

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-gl-native#11411]
**Platform:** iOS
**Mapbox SDK version:** 3.7.4, 3.7.5

### Steps to trigger behavior

 1. Create a new MGLMapView. Assign a map style containing a vector source that has a very wide set of TileJSON bounds at world-scale. In this case, I used the [Odyssey](https://www.mapbox.com/designer-maps/#odyssey) and [North Star](https://www.mapbox.com/designer-maps/#north-star) Mapbox designer styles. These two styles contain a vector source that represent [graticules](https://en.wiktionary.org/wiki/graticule) on a map. The vector tileset sources  (`mapbox.9zm59932` and `mapbox.9mssep40`) have the following TileJSON bounds:

```
"bounds": [
    -179.9999893871037,
    -89.99993255000595,
    180.00000000000006,
    90
]
```
 2. Observe unexpected rendering issues when zooming/panning on the map.

### Expected behavior
![north-star-bug-good](https://user-images.githubusercontent.com/10850812/37120912-950cbf0a-2210-11e8-951e-571d15900fa7.gif)

### Actual behavior
![north-star-bug-bad](https://user-images.githubusercontent.com/10850812/37120914-978b343c-2210-11e8-84a3-4e446edae4a1.gif)

A `git bisect` between 9e96aa1 and 3a0c87b reveals that the issue may have been introduced in 4ab07f5be.

cc @asheemmamoowala

**Comment by friedbunny** [comment]
Fixed by #11425, which will be available in the forthcoming `ios-v3.7.6` release.
