### ISSUE TITLE
Not able to show annotations/markers for iOS by Geojson data

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [mapbox/mapbox-gl-native#11416]
Thanks for the great library, But, I am trying to showing multiple annotations by geoJson data in my iOS app. But, its not able to loading.

I am writing following code

 
>         DispatchQueue.global(qos: .background).async { [weak self] () -> Void in
>             // Get the path for example.geojson in the app's bundle
>             let jsonPath = Bundle.main.path(forResource: "stations", ofType: "geojson")
>             let jsonData = NSData(contentsOfFile: jsonPath!)
>             
>             do {
>                 // Load and serialize the GeoJSON into a dictionary filled with properly-typed objects
>                 if let jsonDict = try JSONSerialization.jsonObject(with: jsonData! as Data, options: []) as? [String:Any] {
>                     // Load the `features` array for iteration
>                     if let features = jsonDict["features"] as? NSArray {
>                         for feature in features {
>                             if let feature = feature as? NSDictionary {
>                                 if let geometry = feature["geometry"] as? NSDictionary {
>                                     if geometry["type"] as? String == "Point" {
>                                         // Create an array to hold the formatted coordinates for our line
>                                         var coordinates: [CLLocationCoordinate2D] = []
>                                         
>                                         
>                                         if let locations = geometry["coordinates"] as? NSArray {
>                                             // Iterate over line coordinates, stored in GeoJSON as many lng, lat arrays
>                                             for location in locations {
>                                                 // Make a CLLocationCoordinate2D with the lat, lng
>                                                 let coordinate = CLLocationCoordinate2DMake((locations[1] as AnyObject).doubleValue, (locations[0] as AnyObject).doubleValue)
>                                                 
>                                                 // Add coordinate to coordinates array
>                                                      coordinates.append(coordinate)
>                                                 print("location is \(location)")
>                                                 print("locations are \(locations)")
> 
>                                             }
>                                         }
>                                         
>                                         let line = MGLPolyline(coordinates: &coordinates, count: UInt(coordinates.count))
>                                         
>                                         // Optionally set the title of the polyline, which can be used for:
>                                         //  - Callout view
>                                         //  - Object identification
>                                         line.title = "Crema to Council Crest"
>                                         
>                                         // Add the annotation on the main thread
>                                         DispatchQueue.main.async { () -> Void in
>                                             // Unowned reference to self to prevent retain cycle
>                                             self?.mapView.addAnnotation(line)
>                                         }
>                                     }
>                                 }
>                             }
>                         }
>                     }
>                 }
>             }
>             catch
>             {
>                 print("GeoJSON parsing failed")
>             }
>             
>         }

Can you guide me for how to achieve my requirement?

**Comment by friedbunny** [comment]
Hello again @AnilkumarRabhasa — as we’ve mentioned, this repo is for reporting bugs or requesting features. For help with “how do I” questions like this one, please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox+ios) or reach out to our [support team](https://www.mapbox.com/contact/support/).
