### ISSUE TITLE
Points sometimes disappear when clustered

### ISSUE THREAD

**Issue by dougnd** [mapbox/mapbox-gl-native#11424]
**Platform:** iOS (tested on iPhone 6 Plus)
**Mapbox SDK version:** 3.7.5

### Steps to trigger behavior

 1. Install the iOS example app. (https://github.com/mapbox/ios-sdk-examples)
 2. Go to ClusteringExample (or ClusteringExample_Swift)
 3. Go to Bermuda
 4. Zoom in and out.

### Expected behavior

There should always either be 2 distinct harbors, or a cluster of 2 harbors.

### Actual behavior

Sometimes, there is only one harbor and no cluster.  See the following screenshots

<img src=https://user-images.githubusercontent.com/5289854/37174166-c6ca0574-22e3-11e8-8aa7-f50986941f55.PNG width=250>
<img src=https://user-images.githubusercontent.com/5289854/37174203-db739c42-22e3-11e8-9684-6ace8fe32d63.PNG width=250>
<img src=https://user-images.githubusercontent.com/5289854/37174205-de2c5582-22e3-11e8-855b-bb5fab994221.PNG width=250>

This is also not limited to just the Bermuda harbors.  See below:
<img src=https://user-images.githubusercontent.com/5289854/37174265-017fc528-22e4-11e8-9899-38d0ebb087ce.PNG width=250>
<img src=https://user-images.githubusercontent.com/5289854/37174285-0d2db61e-22e4-11e8-8ffb-bba590a715e9.PNG width=250>
<img src=https://user-images.githubusercontent.com/5289854/37174272-088b9a5e-22e4-11e8-8d15-2c0053f8aaf1.PNG width=250>

There does seem to be an angle component to this. If I rotate the map so that the two points are vertical or horizontal, it behaves correctly (jumping directly from 2 harbors to 1 cluster).

P.S.  Sorry for the large screenshots.

**Comment by formigarafa** [comment]
I saw something similar happening on both iOS and Android. No clusters just pins.

**Comment by tobrun** [comment]
I believe this issue stems from not setting the following configuration to true: 
https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-icon-ignore-placement
