### ISSUE TITLE
Map downloading doesn't resume after internet is on

### ISSUE THREAD

**Issue by ioel** [mapbox/mapbox-gl-native#11439]
**Platform:** Android
**Mapbox SDK version:** 5.5.0

### Steps to trigger behavior

 1. Start offline map downloading
 2. Turn off the internet
 3. Relaunch application
 4. Run map downloading
 5. Turn on the intenet

### Expected behavior

Map downloading should resume after internet is on. Looks like the problem appears only
after start downloading without internet. 

### Actual behavior

Downloading doesn't resume after internet is on.

**Comment by ioel** [comment]
One more intresting thing:

1. Add map downloading progress logging to logcat
2. Start offline map downloading
3. Put the app in background
4. Download continues (progress is being changed in logcat)
5. Wait for a minute - dowload stops without error callback
6. Bring the app in foreground - download doesn't resume

**Comment by jfirebaugh** [comment]
The behavior in the initial description is expected. Offline regions don't automatically resume when the application is restarted; you'll need to resume them yourself. This is to give developers flexibility to e.g. _not_ resume when on a cellular data connection.

I'm not sure about the behavior in your followup comment. Perhaps a @mapbox/android team member knows whether that's expected or not.

**Comment by ioel** [comment]
@jfirebaugh 
In the first case I run download againg after restart the app and error callback doesn't call despite the fact that there is no internet connection, so I can't implement retry download logic.
