### ISSUE TITLE
[Android] Symbol layer disappears on tilt / rotation

### ISSUE THREAD

**Issue by emerciercontexeo** [mapbox/mapbox-gl-native#11448]
**Platform:Android **
**Mapbox SDK version: 5.5.0**

At this point, I don't know if it is a issue from mapbox itself or from the location plugin. As Mapbox recommends to use it in the documentation, I open the issue here.

### Steps to trigger behavior

 1. Add location layer plugin
 2. Zoom on location
 3. Tilt and rotate

### Expected behavior

Location point should be always visible

### Actual behavior

Depends of tilt and bearing, the point disappears

The following screenshots are from the demo app of plugins to avoid collision with the internal work of my application.

![device-2018-03-14-162541](https://user-images.githubusercontent.com/8739777/37412054-81d48cf8-27a4-11e8-9e0d-afc58f7819d8.png)
![device-2018-03-14-162608](https://user-images.githubusercontent.com/8739777/37412056-81f56a68-27a4-11e8-937c-4282a1967f8d.png)

**Comment by tobrun** [comment]
Going to be fixed with 6.0.0, see #10559

**Comment by emerciercontexeo** [comment]
My bad, didn't see it. Thanks for answer.
