### ISSUE TITLE
Determine visible icon when MGLShapeSourceOptionClustered is enabled.

### ISSUE THREAD

**Issue by eklipse2k8** [mapbox/mapbox-gl-native#11445]
Curious if there's a way to determine which feature is visible when clustering is enabled?

We have ranked our features and it doesn't seem like there's anyway to control what is clustered or not.

**Comment by eklipse2k8** [comment]
Ping.

**Comment by eklipse2k8** [comment]
Ping.

**Comment by 1ec5** [comment]
> Curious if there's a way to determine which feature is visible when clustering is enabled?

It depends. If you query the map for visible features (using a method like -[MGLMapView visibleFeaturesInRect:inStyleLayersWithIdentifiers:]`), then you could determine that certain features aren’t present in the results. However, there isn’t a way to determine directly whether a feature is clustered or not.

> We have ranked our features and it doesn't seem like there's anyway to control what is clustered or not.

A source as a whole is clustered or not clustered. We don’t currently have a way to opt certain features in a source or layout out of clustering.

For future questions about the map SDK’s capabilities, please [contact the Mapbox Support team](https://www.mapbox.com/contact/support/) to get a more prompt response. Thank you!
