### ISSUE TITLE
onSnapshotReady Not Called While Mapview Not in View.

### ISSUE THREAD

**Issue by odemiral** [mapbox/mapbox-gl-native#11454]
Good Afternoon,

I don't know if this is an intended behavior but **onSnapshotReady** won't be called if the map is not currently in the view. I would like to be able to take a snapshot of the map so that I can use the bitmap as my minimap (similar to Lite Mode in Google Maps) and be able to update it even while the user isn't looking at the map.

I just wanted to get a confirmation that this is an intended behavior, and if it is, I was wondering if there are other methods exposed to generate a bitmap image of MapView.

Thanks!

**Comment by tobrun** [comment]
@odemiral yes this is intended, we wait for the view to be measured before we start loading the style. That said we do expose another API to cover the `Lite mode` use-case from Google. We call this the MapSnapshotter and this API allows to generate bitmaps from Maps without an MapView.
[Here](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/snapshot) are some examples. 

Let us know if you have any other questions! Closing this as answered.
