### ISSUE TITLE
Unable to turn on user location tracking immediately at startup

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1145]
Currently it doesn’t seem possible for an app to turn on `MGLUserTrackingModeFollowWithHeading` at startup, because `-[MGLMapView setUserTrackingMode:animated:]` goes and resets the mode to `MGLUserTrackingModeNone` if `self.userLocation.coordinate` is invalid. The coordinate is invalid from startup until we receive the first location update. And setting `MGLUserTrackingModeFollow` at startup doesn’t quite work either: we pan and zoom to the current location but immediately stop following after that.

**Comment by 1ec5** [comment]
The workaround is to first set a valid center coordinate. That’s a pretty sensible workaround, so I don’t think this bug is important for beta 1.

**Comment by incanus** [comment]
Pretty sure this is obsolete, but needs testing.

**Comment by 1ec5** [comment]
Still reproduces. Without setting a center coordinate, set the user tracking mode. Nothing happens.

**Comment by 1ec5** [comment]
This is probably stale now, given that `-commonInit` does set a center coordinate these days.

**Comment by friedbunny** [comment]
Tried this on #3680's branch — plain `follow` is now possible, but `heading` and `course` modes both knock down to `follow` because the heading isn't valid yet.

**Comment by 1ec5** [comment]
> `heading` and `course` modes both knock down to `follow` because the heading isn't valid yet.

A fix is ready in #3680.
