### ISSUE TITLE
Compass and Scale tools appear correctly on iOS11 but not iOS10 they appear out of place.

### ISSUE THREAD

**Issue by kalimar** [mapbox/mapbox-gl-native#11459]
**Platform:** iOS
**Mapbox SDK version:** 3.7

### Steps to trigger behavior

 1. Build app on iOS 10.3.1 
 2. Build same app on iOS11

### Expected behavior
Compass and scale should appear on both versions of iOS in the same location on the screen

### Actual behavior
Compass and scale appear correctly on iOS11. 
In iOS 10.3 it is visible when lowering the height of map screen

```swift
        mapView.scaleBar.isHidden = false
        mapView.displayHeadingCalibration = true
```

This might be related to https://github.com/mapbox/mapbox-gl-native/issues/10773

**Comment by kalimar** [comment]
Here's a quick time video provided by the user. In email correspondence he clarifies that if he reduces the size of the map he is able to see the compass and scale tools. However in these videos he only demonstrates that the tools are not visible. 
Video includes:

* ios 10.3.1 with iphone 6s (not able to see the compass and scalebar)
* ios 10.3.2 with iphone 7  (not able to see the compass and scalebar)
* ios 11.2 with iphone 7 (working fine for all ios 11 and above).

The video is very large so they provided a link to a zipped file. It requires signing into Microsoft. If that proves challenging I have the QuickTime video on my computer and can share elsewhere.
https://honeywellprod-my.sharepoint.com/personal/ramakrishna_savaram_honeywell_com/Documents/Attachments/MapBox%20Compass%20and%20scale%20bar.zip

**Comment by kalimar** [comment]
Here's the video with a dropbox link https://www.dropbox.com/s/dhy1umwxal9wmqc/MapBox%20Compass%20and%20scale%20bar.mov?dl=0

**Comment by fabian-guerra** [comment]
Hi, I looked into this issue and the compass appears on both versions of iOS. In order to make visible the scale bar you should use `mapView.showsScale` instead of `mapView.scaleBar.isHidden`.

This is the dropbox link for the video that shows the compass. https://www.dropbox.com/s/3sfzdh6bhd17nrk/ornaments.mov?dl=0
