### ISSUE TITLE
Remove tilt workaround from MapGestureDetector

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11467]
To optimise the fling gesture in the past, we added a patch [here](https://github.com/mapbox/mapbox-gl-native/blob/release-boba/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java#L421)  to work around tilt specific issues. With the new gesture library from @LukasPaczos we should be able to remove these. This should result in a more consistent UX between being tilted vs not.

**Comment by LukasPaczos** [comment]
Noting, that removing the tilt variable from the linked equation still results in an undefined behavior.
![tilt bounce back](https://user-images.githubusercontent.com/16925074/37521434-08a8c0a0-2921-11e8-9456-fb749f1b842c.gif)

**Comment by tobrun** [comment]
I assumed that the onFling was part of the Almeros library but now seeing it's part of the support gesture library..

**Comment by LukasPaczos** [comment]
The idea would be to move velocity animation initialization into `onMoveEnd()` which exposes nearly the same functionality and fits better into gesture detectors system. Maybe replace it with animators instead of the core animation as well.

**Comment by tobrun** [comment]
Not actionable
