### ISSUE TITLE
Full screen symbol flicker on pitched map with text-translate

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native#11487]
gl-native version of https://github.com/mapbox/mapbox-gl-js/issues/6363.

To fix, we just need to pull over the updated shaders from https://github.com/mapbox/mapbox-gl-js/pull/6365.

This problem existed in release-agua, although I don't know that it's serious enough to require a patch. We should definitely try to get the fix into release-boba.

/cc @ansis @malwoodsantoro @fabian-guerra @friedbunny

**Comment by fabian-guerra** [comment]
@ChrisLoer is this something that the @mapbox/maps-android should be aware?

**Comment by ChrisLoer** [comment]
Yeah, I tagged @tobrun on the fix PR.

**Comment by ChrisLoer** [comment]
Fixed in #11488.
