### ISSUE TITLE
Npe in TrackingSettings.setOnMyLocationChangeListener(TrackingSettings.java:346) 5.5.0 version

### ISSUE THREAD

**Issue by sibuty** [mapbox/mapbox-gl-native#11494]
Hello.
I use 'my location' from MapView.
When I enabled in android-dev-settings 'dont save state operations', after use home button and restore app, I got this stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.mapbox.services.android.telemetry.location.LocationEngine.removeLocationEngineListener(com.mapbox.services.android.telemetry.location.LocationEngineListener)' on a null object reference
                                                                     at com.mapbox.mapboxsdk.maps.TrackingSettings.setOnMyLocationChangeListener(TrackingSettings.java:346)
                                                                     at com.mapbox.mapboxsdk.maps.MapboxMap.setOnMyLocationChangeListener(MapboxMap.java:2130)
```

Sometime later, I found why It has happened.
In TrackingSettings, locationSource do not initialised after restore state, only on create state, look at:
```
MapView initialiseMap method:
if (savedInstanceState == null) {
      mapboxMap.initialise(context, mapboxMapOptions);
    } else {
      mapboxMap.onRestoreInstanceState(savedInstanceState);
    }
```

I fixed it two way:
1) Set MapView in onCreate(state) anytime null mapView.onCreate(null)

2) Use shitty reflection after on create mapbox object:
```
private void checkNpeInTrackingSettings() {
    if(mapboxMap != null) {
      final TrackingSettings trackingSettings = mapboxMap.getTrackingSettings();
      if(trackingSettings != null) {
        final Field[] fields = trackingSettings.getClass().getDeclaredFields();
        for(final Field field : fields) {
          if(LocationEngine.class.isAssignableFrom(field.getType())) {
            field.setAccessible(true);
            try {
              if(field.get(trackingSettings) == null) {
                field.set(trackingSettings, Mapbox.getLocationEngine());
              }
            } catch(final IllegalAccessException e) {
              e.printStackTrace();
            }
            break;
          }
        }
      }
    }
  }
```

How do you think what way is worst?
And mb you can prompt me third way? Or anything else?

**Comment by LukasPaczos** [comment]
Thanks for reporting @sibuty. Unfortunately, I don't have the option to not save state on my test devices (only to not keep activities), therefore wasn't able to reproduce. I grasp the nature of the problem, but how can this option disable saving state, yet still pass `non-null` bundle in `onCreate()`?

In any case, starting from `6.0.0` and forward we are removing all location related services from the Maps SDK and recommend using [LocationLayerPlugin](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-locationlayer) for displaying user's location on the map.

Closing as the issue references deprecated code.

**Comment by sibuty** [comment]
Ok.
