### ISSUE TITLE
android how to listen mapview fail loading events

### ISSUE THREAD

**Issue by qin9smile** [mapbox/mapbox-gl-native#11497]
in ios version there has delegate function ：
- (void)mapViewDidFailLoadingMap:(MGLMapView *)mapView withError:(NSError *)error;

and android ，i don't find....

**Comment by LukasPaczos** [comment]
Thanks for reaching out @qin9smile. With Maps SDK for Android, you can listen for `MapChange` events:
```
mapView.addOnMapChangedListener(new MapView.OnMapChangedListener() {
  @Override
  public void onMapChanged(int change) {
    if (change == MapView.DID_FAIL_LOADING_MAP) {
      // your code
    }
  }
});
```

Let us know if that's what you are looking for.

**Comment by qin9smile** [comment]
thank you.

**Comment by whyzjl** [comment]
Hi，I cannot get the event：MapView.DID_FAIL_LOADING_MAP ，and I disconnect the network。my mapbox version is V5.5.1
