### ISSUE TITLE
Expose Events lib public methods

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#11493]
https://github.com/mapbox/mapbox-gl-native/pull/11474 brought the latest Events lib changes and we realized that currently there's no way to access the [`MapboxTelemetry`](https://github.com/mapbox/mapbox-events-android/blob/master/libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java) `public` methods through the Maps SDK.

We should expose those methods to developers.

cc @zugaldia @electrostat @LukasPaczos @tobrun @osana

**Comment by tobrun** [comment]
done with #11503
