### ISSUE TITLE
contentInsets return to 0 while following the user

### ISSUE THREAD

**Issue by iDevid** [mapbox/mapbox-gl-native#11491]
![ezgif-4-c6c7979bd1](https://user-images.githubusercontent.com/1254022/37707662-38f9966c-2d04-11e8-92a0-db1c33f4d8fd.gif)

**Platform:**
iOS
**Mapbox SDK version:**
3.7.6

### Steps to trigger behavior

 1. Start following the user
 2. Set contentInsets

### Expected behavior
The contentInsets remain the same

### Actual behavior
The ContentInsets reset unexpectedly

**Comment by iDevid** [comment]
UP

**Comment by julianrex** [comment]
Hi @iDevid, FYI we're looking at a range of (potentially related) issues regarding `contentInset` - though we don't have an ETA right now.

**Comment by iDevid** [comment]
This issue regards the userLocationVerticalAlignment, during the tracking the framework checks the current userLocationVerticalAlignment and set the contentInset to the relative Alignment.
