### ISSUE TITLE
Vector tile overzooming

### ISSUE THREAD

**Issue by mzervens** [mapbox/mapbox-gl-native#11492]
**Platform:** Android
**Mapbox SDK version:** 5.5.0

### Description

I have a similar situation which was described in here: #9863
But the problem is not when specific zoom levels all data is missing but only some parts of it. This is caused by the cache being created with specific index where only parts which require more detail are cached in closer zoom levels, the rest should be displayed from the previous zoom levels.

With this cache at each zoom level the layer should be drawn using vector tiles from many different levels.

Heres example of the problem in android (the missing tile in upper left corner):
![screenshot_20180321-152536](https://user-images.githubusercontent.com/7412294/37712638-22ce8ea6-2d1d-11e8-9ccb-ed7e2cb4fa1d.png)

The same vector tile cache seems to work as expected in the mapbox js where the library displays the data from previous levels when the server responds with 404 statuss 

![mapbox_web](https://user-images.githubusercontent.com/7412294/37712775-9279b208-2d1d-11e8-8638-b7d6feaf61ea.PNG)

Setting the maxzoom propery is not an option since at closer levels no requests are made to the server even though more detailed information is available for some regions.

Is there some kind of property / configuration available for this kind of cache for the mapbox android, 
the mapbox js library seems to be working with this kind of cache out of the box with no configuration.

**Comment by kkaefer** [comment]
> This is caused by the cache being created with specific index where only parts which require more detail are cached in closer zoom levels

Could you please describe this in more detail? I'm not sure what you're doing here. Are you using vector tiles that you created yourself, or those hosted on mapbox.com?

**Comment by mzervens** [comment]
@kkaefer Vector tiles which were created using Esri Arcgis pro

The idea of this kind of cache is described here:
http://pro.arcgis.com/en/pro-app/tool-reference/data-management/create-vector-tile-index.htm
