### ISSUE TITLE
displaying custom symbol layer icon with different sizes

### ISSUE THREAD

**Issue by MinwookHyejin** [mapbox/mapbox-gl-native#11513]
**Platform: android**
**Mapbox SDK version: 6.0.0.beta.4**

### Steps to trigger behavior

 1. I put 3 bitmaps with mapboxmap.addImage(String, Bitmap) which have same size(width, height).
 I checked it through logging the size before adding.
(I'll call them simply Bitmap A, B, C.)
 2. I'm using 3 symbol layers with each bitmap, and each layer has property 'icon size' = 1f

                    PropertyFactory.iconImage("loading"),
                    PropertyFactory.iconAnchor("bottom"),
                    PropertyFactory.iconSize(1f),

                    PropertyFactory.textField("{name}"),
                    PropertyFactory.textAnchor("top"),
                    PropertyFactory.textSize(10f),
                    PropertyFactory.textColor(Color.RED)

like this. only difference among the layers is the iconImage

 3. Bitmap A is loaded from web, B, C are loaded from res folder.
 4. All of the Bitmaps are loaded through Glide Image Loader. 

### Expected behavior
 The size of Displaying icons must have to be same size

### Actual behavior
  B, C are about 1.5 times bigger than A
  But the textSize is same.

**Comment by tobrun** [comment]
Thank you for reaching out and reporting your problem. I will try to see if I can reproduce this issue.  FWIW you are able to show different icons with one symbol layer see [this](https://blog.mapbox.com/a-guide-to-the-android-symbollayer-api-5daac7b66f2c) blogpost for more information.

**Comment by tobrun** [comment]
Not able to reproduce with the provided code, this is what I'm seeing on my end:

<img width="311" alt="screen shot 2018-03-24 at 10 05 56" src="https://user-images.githubusercontent.com/2151639/37864880-0679d03c-2f4b-11e8-840a-93e6218279e0.png">

**Comment by tobrun** [comment]
@MinwookHyejin not really able to reproduce on my end without having the actual images to test with. My guess is that Glide does perform some changes while loading the image which is not in our control. Could you validate that the `Bitmap.getConfig` returns the same value with the local resource images?
