### ISSUE TITLE
SetStyleJson() is not persistent

### ISSUE THREAD

**Issue by invised** [mapbox/mapbox-gl-native#11516]
**Platform:** Android
**Mapbox SDK version:** 5.5.0

### Steps to trigger behavior

 1. Setup `SupportMapFragment`.
 2. Call `MapboxMap.setStyleJson()`
 3. Force the fragment to go into stopped state (for example, press "Recent tasks" phone button)
 4. Return to the fragment's activity (so back to the resumed state)

### Expected behavior
Nothing changes, the style is the one, that we've set in step 2.
### Actual behavior
The style is reset to the default one (seems like Mapbox Streets).

**Comment by tobrun** [comment]
Thank you for the report @invised, was able to reproduce

**Comment by tobrun** [comment]
Landed with #11519
