### ISSUE TITLE
Confusing CannotAddLayerException while re-adding layer

### ISSUE THREAD

**Issue by invised** [mapbox/mapbox-gl-native#11515]
**Platform:** Android
**Mapbox SDK version:** 5.5.0

### Steps to trigger behavior

 1. Set map style and create own Layer object, for example `FillLayer()`
 2. Add created layer to the map (`MapboxMap.addLayerBelow()`)
 3. Make a configuration change (rotate the device)
 4. Set map style again and add **the same** layer **object** created at step 1

### Expected behavior
Layer should be added succesfully, as at the time of adding `MapboxMap.getLayer(id)` returns `null` for it, and `MapboxMap.getLayers()` also doesn't contain the layer that is being added 

### Actual behavior
`CannotAddLayerException` is thrown, saying that layer cannot be added twice.

After some debugging I realized that we cannot reuse `Layer` objects and javadoc for `removeLayer(@NonNull String layerId)` says just like that 

> Removes the layer. Any references to the layer become invalid and should not be used anymore

But this **behaviour is so confusing**, as my code is not calling `removeLayer()`, and it seems like `removeLayer()` _is called somewhere under the hood_

**Comment by tobrun** [comment]
This is expected behavior and not actionable. The layer is linked to the style, activity recreation results in reloading the style and thus the layer becomes invalid.

**Comment by tobrun** [comment]
@JRWilding this isn't really the same issue as the one from OP (even if you are hitting the same exception). Don't think that is possible without having to reload the style. When implementing such benchmars, I would create multiple json definitions of the same style and load that, this should give the most clean result as you aren't adding/removing anything pro grammatically while the style is already fully loaded. .
