### ISSUE TITLE
Android sdk native crash on MapView#onLowMemory()

### ISSUE THREAD

**Issue by fightyz** [mapbox/mapbox-gl-native#11523]
Hi, Please pay attention to this crash.
This crash is not happened on Android Mapbox sdk 5.2.1, but on 5.4.1.
Here is the log:

1 #00 pc 00070c2c /data/app/xxx/lib/arm/libmapbox-gl.so [armeabi-v7a]
--
2 #01 pc 00067c9d /data/app/xxx/lib/arm/libmapbox-gl.so [armeabi-v7a]
3 #02 pc 00067cdf /data/app/xxx/lib/arm/libmapbox-gl.so [armeabi-v7a]
4 #03 pc 02c3924f /data/app/xxx/oat/arm/base.odex (oatexec+2089551) [armeabi]
5 java:
6 com.mapbox.mapboxsdk.maps.NativeMapView.void onLowMemory()(SourceFile:506)
7 com.mapbox.mapboxsdk.maps.MapView.void onLowMemory()(SourceFile:481)

Mapbox sdk: 5.4.1
Android platforms: All

**Comment by fightyz** [comment]
I have found that it outbreaks on 5.3.2.

**Comment by LukasPaczos** [comment]
Thanks for reporting the issue @fightyz. Could you provide any more context for this one? Some code examples/devices used would be great as I wasn't able to reproduce the issue on my end.

**Comment by LukasPaczos** [comment]
Noting, that you can also try and fill up the RAM with one of the debug apps available on the Play Store that are made to stress your device.

**Comment by jfirebaugh** [comment]
@fightyz Let us know if you're able to supply more information that would help us diagnose the issue.
