### ISSUE TITLE
Move Sprite loading outside of Sprite object

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1152]
We're currently constructing the Sprite object with a URL. Instead, the Sprite object should be unaware of those concerns and be initialized with the already-loaded image/JSON. This allows us to make the Sprite object all-`const`. This will make it easier to test the Sprite object and its parsing of the Sprite JSON files.

**Comment by kkaefer** [comment]
Depends on https://github.com/mapbox/mapbox-gl-native/issues/925

**Comment by incanus** [comment]
> This allows us to make the Sprite object all-const. 

Possibly at odds with https://github.com/mapbox/mapbox-gl-native/issues/941, depending on approach.

**Comment by jfirebaugh** [comment]
@kkaefer Still think we want to do this, given #2722? I'm happy having each object responsible for requesting/monitoring its own resources.

**Comment by kkaefer** [comment]
No.
