### ISSUE TITLE
Android) Clustering Priority 

### ISSUE THREAD

**Issue by swsong12** [mapbox/mapbox-gl-native#11522]
**Platform:* ANDROID *
**Mapbox SDK version:* 6.0.0 beta 4*

Hi Mapbox Team. I am super curious if we can prioritize specific symbol in clustering. For example, there are 3 symbol below:

![not clustered](https://user-images.githubusercontent.com/22624800/37881707-af63e420-3050-11e8-85ed-086d5e5807ce.png)

Mapbox will automatically cluster symbol like this:

![mapbox cluster](https://user-images.githubusercontent.com/22624800/37881715-bdbd3c1a-3050-11e8-81cb-b682ab3fcea0.png)

However, I would like to cluster symbol like this:

![what i want](https://user-images.githubusercontent.com/22624800/37881727-d1eb6fcc-3050-11e8-8034-8d5b1bcc7dd3.png)

Thank you for the great work!

**Comment by swsong12** [comment]
@tobrun 

Is there anyway we can work around this issue? or do we have to wait for future release?

**Comment by jfirebaugh** [comment]
@swsong12 This is not really possible with the clustering algorithm used by Mapbox GL unfortunately. If you need a specific behavior, you are probably best off creating a custom data source that's pre-clustered the way you desire.
