### ISSUE TITLE
Merge all gyp projects

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1153]
We currently have several gyp projects for a platform, on OS X they are `macosx/mapboxgl-app.gyp`, `linux/mabpoxgl-app.gyp`, `test/test.gyp`, and `bin/render.gyp`. We should convert them to includes and merge them into one umbrella objects so we can share build caches between them. Currently, you'll have to create separate projects to run the tests and execute the sample app, and they can't be open at the same time, since they reference the same `mbgl.xcodeproj`.

**Comment by jfirebaugh** [comment]
Looks like this happened already.

**Comment by kkaefer** [comment]
This happened for all, except for the node project, which is still a separate file since building is controlled via node-gyp.
