### ISSUE TITLE
Marker serialization freeze

### ISSUE THREAD

**Issue by psinetron** [mapbox/mapbox-gl-native#11531]
Hi! I have some problems with serialization of Marker. I have infinite looping when serialize Marker class with Gson and Retrofit if  you do not mark the field as Transient. 
**Platform:** Android
**Mapbox SDK version:** 5.5.0

### Steps to trigger behavior

Create DTO class (Kotlin): 

```
class AddressResultDTO {
    @SerializedName("result") var results:ArrayList<Result>? = null

    class Result {
        @SerializedName("lat") internal var latitude: Double? = null
        @SerializedName("lng") internal var longitude: Double? = null
        @SerializedName("name") internal var name: String? = null
        @SerializedName("address") internal var address: String? = null

       var selected = false
       var markersOptions: MarkerOptions? = null
       var marker: Marker? = null
    }
}
```

But when mark as Transient it worked. I think some problems in serialization section at Marker class.

### Actual behavior
Freezed application

**Comment by tobrun** [comment]
@psinetron Marker is not supposed to be serialized, only the options class.
