### ISSUE TITLE
CONTAINS predicate operator should test whether a string contains a substring

### ISSUE THREAD

**Issue by qin9smile** [mapbox/mapbox-gl-native#11532]
MGLSymbolStyleLayer can add predicate like this 
![image](https://user-images.githubusercontent.com/12714985/37955206-88929266-31da-11e8-8025-1879812c1baa.png)

but actually i want to use 'CONTAINS' , but it's crashed with error:
'NSInvalidArgumentException', reason: 'IN not supported for string comparison.'

maybe it's not support 'CONTAINS' ?

**Comment by 1ec5** [comment]
The SDK does support `CONTAINS` for determining whether an array contains a string. However, it doesn’t support `CONTAINS` for determining whether a string contains a substring. That’s blocked by mapbox/mapbox-gl-js#4113. Additionally, in v4.0.0-beta.3, it’s a known issue that this operator doesn’t work at all: #11013.
