### ISSUE TITLE
onSurfaceChanged crash with react-native

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11549]
```
java.lang.IllegalArgumentException: 
  at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onSurfaceChanged (MapRenderer.java:67)
  at com.mapbox.mapboxsdk.maps.renderer.textureview.TextureViewMapRenderer.onSurfaceChanged (TextureViewMapRenderer.java:48)
  at com.mapbox.mapboxsdk.maps.renderer.textureview.TextureViewRenderThread.run (TextureViewRenderThread.java:269)
```

This stacktrace indicates that we received a negative value for width. While we haven't had reports of this on this repo, this can occur when using react-native. 

```java
 @CallSuper
  protected void onSurfaceChanged(GL10 gl, int width, int height) {
    if (width < 0) {
      throw new IllegalArgumentException("fbWidth cannot be negative.");
    }

    if (height < 0) {
      throw new IllegalArgumentException("fbHeight cannot be negative.");
    }

    if (width > 65535) {
      throw new IllegalArgumentException(
        "fbWidth cannot be greater than 65535.");
    }

    if (height > 65535) {
      throw new IllegalArgumentException(
        "fbHeight cannot be greater than 65535.");
    }

    gl.glViewport(0, 0, width, height);
    nativeOnSurfaceChanged(width, height);
  }
```

cc @ivovandongen  @nitaliano

**Comment by tobrun** [comment]
Similar issue in https://github.com/mapbox/mapbox-gl-native/pull/6788/files

**Comment by nitaliano** [comment]
They just posted back in the RN issue, they're seeing `fbWidth cannot be negative` in the logs

**Comment by tobrun** [comment]
@ivovandongen 
 - where did these values come from? 
 - would be able to get away with capping the value at 0 when height/widht are negative? 
and at 65535 when higher?

**Comment by tobrun** [comment]
Since we only saw this crash downstream with react native, we are patching it up [there](https://github.com/mapbox/react-native-mapbox-gl/issues/1106#issuecomment-381147279) instead of here. Closing for now.
