### ISSUE TITLE
[Android] queryRenderedFeatures incomplete

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-gl-native#11546]
Hey!

Platform: Android 
Mapbox SDK version: 
```
    api('com.mapbox.mapboxsdk:mapbox-android-sdk:5.5.1') {
        transitive = true
    }
```

Device: Motorola Nexus 6 (Android 7.1.1)

### Steps to trigger behavior

 1. Copy [SelectBuildingActivity.java](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/query/SelectBuildingActivity.java) from Android Demo Project
 2. Try to select the building at LatLng 53.874537962512875, 10.683847682870237

### Expected behavior
Select building completely

### Actual behavior
Building is partially selected

![2018-03-28 13 14 42](https://user-images.githubusercontent.com/23097192/38025928-713ed218-328a-11e8-81ac-c01aa64294b1.jpg)
![2018-03-28 13 14 47](https://user-images.githubusercontent.com/23097192/38025930-71612ec6-328a-11e8-871c-b71762e793bd.jpg)

In OSM editor the building looks like this:
![bildschirmfoto 2018-03-28 um 13 16 38](https://user-images.githubusercontent.com/23097192/38025959-8ac205f2-328a-11e8-88df-153b2c0f5e2f.png)

I've got a few other buildings where queryRenderedFeatures gets less points than in reality. Zoom level doesn't matter.

**Comment by asheemmamoowala** [comment]
@P-Zenker thank you for using Mapbox. The `queryRenderedFeatures` method returns visible features that may have been split across tile boundaries. To retrieve all (tiled)parts of a feature, use the `querySourceFeatures` method with a unique identifier.
