### ISSUE TITLE
Don't reload/reparse tiles after app gets backgrounded

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1154]
We're currently reloading and reparsing the tiles once the app gets backgrounded on iOS (and Android for that matter). This is because the `Style` object gets deleted, which clears out all loaded tiles. While the vector tile itself is most likely cached, we still have the overhead of reparsing all of the tiles.

Instead, we should hold on to the parsed buffers as long as possible (and possibly relinquish them when we get a memory warning, see #1157) and when reloading, check whether we still have a buffer object around that matches that layer's settings.

**Comment by jfirebaugh** [comment]
Fixed in #1065.
