### ISSUE TITLE
How to add mgpolyline with annotation

### ISSUE THREAD

**Issue by amrit42087** [mapbox/mapbox-gl-native#11545]

**Comment by fabian-guerra** [comment]
Hi, @amrit42087 . Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
