### ISSUE TITLE
`make android` fails with JDK 9

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#11552]
After installing with `brew cask install java`:

```
$ java --version
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
$ make android
cd platform/android && ./gradlew --parallel --max-workers=4 -Pmapbox.buildtype=debug -Pmapbox.abis=armeabi-v7a :MapboxGLAndroidSDKTestApp:assembleDebug
/Users/john/Development/mapbox-gl-native/platform/android

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9.0.4'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
make: *** [android-arm-v7] Error 1
```

Gradle 4.1 is used here:

https://github.com/mapbox/mapbox-gl-native/blob/639c033d8e2f307282557a9a7838ec1277903c79/platform/android/gradle/wrapper/gradle-wrapper.properties#L5

If I change the `4.1` to `4.6`, then I get:

```
$ make android
/Users/john/Development/mapbox-gl-native/platform/android
Parallel execution is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':MapboxGLAndroidSDK'.
> Failed to notify project evaluation listener.
   > Could not initialize class com.android.sdklib.repository.AndroidSdkHandler
   > Could not initialize class com.android.sdklib.repository.AndroidSdkHandler
   > Could not get unknown property 'compileDebugUnitTestSources' for project ':MapboxGLAndroidSDK' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
make: *** [android-arm-v7] Error 1
```

**Comment by tobrun** [comment]
To get the project to compile you will have to downgrade to java 8.

```
brew cask install java8
```

On my machine I'm getting the following output for `java -version`

> java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

This also matches the version we use on [CI](https://github.com/mapbox/mbgl-ci-images/blob/master/java/Dockerfile#L15). Java 9 is not supported for doing Android Development and is currently not on the roadmap for Google to implement. Closing as resolved, please reopen if this is still an issue after downgrading.

**Comment by jfirebaugh** [comment]
`brew cask install java8` doesn't work for me.

> Error: Cask 'java8' is unavailable: No Cask with this name exists.

**Comment by jfirebaugh** [comment]
`brew cask install caskroom/versions/java8` does though! 🙏
