### ISSUE TITLE
Recompiling new version of libicuuc.a with new version of xcode should increment version (to prevent breaking old builds)

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#11557]
**Platform:iOS**
**Mapbox SDK version:Any version built with xcode 8.x e.g. 3.5.2**

### Steps to trigger behavior

I am filing this bug to ensure that when dependencies like libicuuc.a are re-compiled in future with a newer version of xcode, the version number (used in mason) gets incremented. This will prevent builds working with older version of xcode from failing.

 1. Checkout a version of mapbox-gl-native compatible with Xcode 8.x. 
 2. Build iosapp target
 

### Expected behavior
Build should go through.
### Actual behavior
Build fails at link time with error: Invalid bitcode version.
It fails because libicuuc.a  was recompiled but its version number was not incremented from 58.1.
Luckily I had an older version 58.1-min-size lying around. Copying it manually under mason_packages fixed the error.

**Comment by 1ec5** [comment]
Hi @mb12, the iOS and macOS map SDKs currently [require Xcode 9.1 and above](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md#requirements) to build from source. Unfortunately, we’re unable to support building from source on Xcode 8._x_. Would the issue also affect Xcode 9._x_? If so, would a clean build work around the issue?

**Comment by springmeyer** [comment]
I'm responsible for rebuilding the ICU package. I agree that I should have bumped the version number to avoid this, and will in the future. However, like @1ec5, I am assuming a full, clean recompile should work around the issue. Would be interested to learn why, if not.

**Comment by mb12** [comment]
@springmeyer I was building an older version of mapbox-gl-native (hash 6ae8bb526f0104fcfe43b6e6065048eb64720f97).  The build (target iosapp) failed at link time with error: Invalid bitcode version(Producer xxxxx Reader yyy). My guess is the reason is a different version of xcode than the one with which the dependency was compiled.

Similar error with other projects is also discussed here on stackoverflow.

https://stackoverflow.com/questions/43480556/xcode-8-2-1-error-invalid-bitcode-version-producer-802-0-41-0-0-reader

I had an older version of the library.  Copying it over fixed the build error.
