### ISSUE TITLE
Catch inserting propertyValue invocations inside an expression

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11560]
While migrating old dds code to the new expression syntax, a typical issue that users run into will be that they need to remove the additional invocation of the property they are setting. Wrongly ported code will look like:

```java
      lineOpacity(interpolate(exponential(1f), zoom(),
        stop(17f, lineOpacity(1f)),
        stop(16.5f, lineOpacity(0.5f)),
        stop(16f, lineOpacity(0f))))
      );
```

Atm this compiles but throws a native crash at runtime. We should add type checking to validate if the provided stop value isn't of the type PropertyValue and throw a java exception instead.

**Comment by LukasPaczos** [comment]
As of #11572 we are throwing an exception when this happens.
