### ISSUE TITLE
Support expression operators in style layer predicates

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#11567]
#11251 implemented underlying support for converting an NSPredicate to an `mbgl::style::ExpressionFilter`, but that doesn’t appear to be hooked up to `-[NS*Predicate mgl_filter]` yet. As a result, the following code crashes:

```objc
lineLayer.predicate = [NSPredicate predicateWithFormat:@"maki == lowercase('THEATRE')"];
```

```
[General] Comparison predicate must compare an attribute (as a key path) to a constant or vice versa.
2018-03-30 04:06:54.994117-0700 Mapbox GL[41905:16769647] [General] (
	0   CoreFoundation                      0x00007fff459d6fcb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff6c678c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff45a689ed +[NSException raise:format:] + 205
	3   Mapbox                              0x00000001005b1d44 -[NSComparisonPredicate(MGLAdditions) mgl_keyPath] + 436
	4   Mapbox                              0x00000001005ae032 -[NSComparisonPredicate(MGLAdditions) mgl_filter] + 498
	5   Mapbox                              0x00000001006119b1 -[MGLSymbolStyleLayer setPredicate:] + 289
```

The fix is to replace the switch statements in `-[NSPredicate mgl_filter]`, `-[NSComparisonPredicate mgl_filter]`, and `-[NSCompoundPredicate mgl_filter]` with calls to the respective `-mgl_jsonExpressionObject` methods. This will cause some tests to fail; #11013 covers implementing some NSPredicate-specific operators that are exercised by these tests.

/cc @fabian-guerra

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/11587
