### ISSUE TITLE
Add support for excluding ideographic characters from offline downloads

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native#11561]
I just took a look at a ~200MB offline cache I collected for a narrow area around Beijing. It appeared to have ~24MB of tiles and ~161MB of font data. I suspect a large amount of that font data is CJK ideographs, which I don't need because I'm using the cache with an app that renders ideographs locally. We should add an option to `OfflineDownload` to exclude requests for glyph ranges that are part of `i18n::allowsFixedWidthGlyphGeneration`, expose the option in the various users of `OfflineDownload` (`mbgl-offline`, `MGLOfflineStorage`, ...?), and figure out how to document it appropriately.

/cc @kkaefer @tobrun @1ec5

**Comment by mb12** [comment]
@ChrisLoer Another approach to reduce the download bandwidth would be to download the .ttf file and generate the pbfs locally using node-fontnik. For 'Open Sans' fonts, this can reduce bandwidth by  6x (uncompressed).

**Comment by ChrisLoer** [comment]
Implemented in #13607.
