### ISSUE TITLE
[QML] set angle of view

### ISSUE THREAD

**Issue by ducmaxime** [mapbox/mapbox-gl-native#11576]
Hello,

I try to set the angle of view of QML Map Component.

I've tried to set fieldOfView property, but it's not working.

my code:

 Map {
    id : map
    anchors.fill : parent
    center: QtPositioning.coordinate()
    zoomLevel: 14
     plugin : Plugin {
      id   : mapPlugin
      name : "mapboxgl"

      allowExperimental: true
     PluginParameter {
        name: "mapboxgl.access_token"
        value: "...."
      }
      PluginParameter{
        name: "mapboxgl.mapping.items.insert_before"
        value: "road-label-small"
      }
      PluginParameter{
        name: "mapboxgl.mapping.use_fbo"
        value: "true"
      }
    }

any idea ?

**Comment by fabian-guerra** [comment]
Hi, @ducmaxime . Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
