### ISSUE TITLE
Replace outdated vector tile fixtures

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-native#11579]
While working on https://github.com/mapbox/mapbox-gl-native/pull/11489, I discovered that at least one (and probably more) of our vector tile unit test fixtures is out of date.

Specifically, https://github.com/mapbox/mapbox-gl-native/blob/553efa38e3591ce62863d4d74222710f8e3c2337/test/fixtures/map/offline/0-0-0.vector.pbf (originally added in https://github.com/mapbox/mapbox-gl-native/pull/2721) is a v1 vector tile that appears to include a linestring with a ClosePath command.  The v1 spec did not disallow this, but it causes `vtzero` to throw an exception ("expected command 1 but got 7").

We should:
 - For most of our unit tests, update the vector tiles we're using as test fixtures to v2 tiles.
 - Add some v1 tiles to https://github.com/mapbox/mvt-fixtures, and then add a unit test specifically targeting v1 compatibility

**Comment by jfirebaugh** [comment]
We released offline before v2 vector tiles (https://github.com/mapbox/mapbox-gl-native/pull/2444#issuecomment-188454475), so it's definitely possible (and supported) to have an offline database with v1 tiles in it.

**Comment by anandthakker** [comment]
Yeah -- my suggestion here is just that our normal unit test fixtures be v2 tiles (since that probably accounts for the large majority of use in practice), and that we separate v1 compatibility into its own, explicit test(s)

**Comment by anandthakker** [comment]
A _separate_ question is whether we need to make sure we can continue to handle tiles exhibiting the specific issue (the spurious closepath command) that prompted this.  

My understanding is that in general,  `vtzero` does attempt to be flexible in decoding tiles, leaving strict validation up to the client.  cc @springmeyer @joto

**Comment by anandthakker** [comment]
> That is not really true. Vtzero is strict in some places where it matters and where the strictness is cheap to check.

👍  thanks for clarifying this @joto.  I suspect that in practice, it's really just invalid geometries coming from old v1 tiles that we would need to worry about, and I think it sounds fine to deal with such backwards compatibility issues on a case-by-case basis.
