### ISSUE TITLE
It took me 5 seconds to generate one png,why so slow?

### ISSUE THREAD

**Issue by lihuadong1988** [mapbox/mapbox-gl-native#11582]
Platform: linux
Mapbox SDK version: 5.0.2

when I used mbgl-render which was compiled by linux default platform to generate png file,  it took a long time to generate only one single png, but when using nodejs platform to generate the same png,the speed was relatively faster than using linux default platform,i don't know why?

**Comment by jfirebaugh** [comment]
mbgl-render is a developer tool. Unfortunately, we can't provide technical support for it.
