### ISSUE TITLE
Offline packs should load @1x and @2x sprites

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#11584]
`OfflineDownload` should default to include both `@1x` and `@2x` assets to account for the offline pack being used in multiple environments.

**Comment by jfirebaugh** [comment]
What about raster sources? It would be prohibitively expensive to include both `@1x` and `@2x` raster tiles.

I think I'd rather keep it the way it is, for consistency.

**Comment by ChrisLoer** [comment]
Good point about raster tiles, but there are probably still situations where someone’s creating a vector tile offline pack that’s going to run on devices with multiple pixel ratios, right? How should we tell them to build their packs? Maybe keep the default at a single pixel ratio but allow multiple ratios?

Maybe we can also do something to help developers who make the (easy) mistake of bundling the wrong pixelRatio? As is the map just fails to load and the sprite loading error message isn’t very obviously the cause. It’s not much but maybe the simplest thing we can do is add an “if you’re using an offline cache...” blurb to the sprite loading error message?

**Comment by mb12** [comment]
@jfirebaugh Are you suggesting that the native client automatically appends @1x or @2x prefix for raster tile URLs? Or is  there some pixel ratio  parameter that gets automatically added to tile URL templates for mapbox sources that mapbox tile servers use when serving raster tiles?

**Comment by 1ec5** [comment]
> there are probably still situations where someone’s creating a vector tile offline pack that’s going to run on devices with multiple pixel ratios, right?

This could potentially happen in two scenarios: map snapshots and [sideloading](https://github.com/mapbox/mapbox-gl-native/wiki/Sideloading-offline-maps) (which at the moment isn’t officially supported).

**Comment by kkaefer** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/12933
