### ISSUE TITLE
higher-level pre-made styles API

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1159]
Summarizing voice with @samanpwbb about making tighter the connection between styles online and styles in the mobile app. 

Whether the user pre-bundles styles with an app as local assets or wants to refer to hosted styles, the interactions should be at the **map ID** level. Currently we've been doing this not at this level: 

1. C++: At the [style URL level](https://github.com/mapbox/mapbox-gl-native/blob/3ed1e7a695491120020e00ff3dc7926dba71834e/include/mbgl/map/map.hpp#L105-L106) (local or remote). 
1. Cocoa: At the [style name level](https://github.com/mapbox/mapbox-gl-native/blob/3ed1e7a695491120020e00ff3dc7926dba71834e/include/mbgl/ios/MGLMapView.h#L190) (`mapView.useBundledStyleNamed()`). 

We should build our [URL normalization in C++](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/util/mapbox.hpp) to handle style-type URLs, as well as layer Cocoa and eventually Android APIs on top of that for indicating map ID. 

Unanswered questions: 

* How does the dev most easily bundle styles created online locally with an app? 
* How does the dev programmatically differentiate between local and remote style map IDs? 

/cc @bleege @jfirebaugh @1ec5

**Comment by jfirebaugh** [comment]
Agree. #892 covers the C++ side of this (supporting `mapbox://<style ID>` URLs).

**Comment by incanus** [comment]
We have C++ support in https://github.com/mapbox/mapbox-gl-native/pull/1161 and Cocoa API support in https://github.com/mapbox/mapbox-gl-native/pull/1163. This whole API area is still a bit soft, so let's close for until we shore up which ways we'll set styles and which ways we'll cut, then port that to Android.
