### ISSUE TITLE
Filtering by "$id" feature identifier

### ISSUE THREAD

**Issue by invised** [mapbox/mapbox-gl-native#11595]
**Platform:** Android 
**Mapbox SDK version:** 5.5.0

### Steps to trigger behavior

 1. Define an id for the feature, for example
```
{"type" : "Feature",
  "id" : 777,
  "geometry" : ...,
  "properties" : ...
}
```
 2. Reference feature's ID in filter, for example:
`symbolLayer.setFilter(Filter.in("$id", 777));`

### Expected behavior
As per [spec](https://www.mapbox.com/mapbox-gl-js/style-spec/):

> A key must be a string that identifies a feature property, or one of the following special keys:
> 
> "$type": the feature type. This key may be used with the "==","!=", "in", and "!in" operators. Possible values are"Point", "LineString", and "Polygon".
> "$id": the feature identifier. This key may be used with the "==","!=", "has", "!has", "in", and "!in" operators.

 feature with id=777 should be shown

### Actual behavior
The whole layer is not shown at all

Am I doing it wrong? If this is intended behaviour, how to filter by id then? Doing `symbolLayer.setFilter(Filter.in("id", 777));` doesn't work too.
The alternative for me was to to declare custom property and filter based on it.

If this is a bug, than it exists long ago before Mapbox 5.5.0

**Comment by tobrun** [comment]
@invised could you try filtering with the token syntax? eg. `in("{id}", 777)`

**Comment by invised** [comment]
@tobrun doesn't work

**Comment by LukasPaczos** [comment]
@invised You could also try moving the value to a property
```
{"type" : "Feature",
  "geometry" : ...,
  "properties" : {
    "identifier": 777
  }
}
```
and then use the token syntax
`symbolLayer.setFilter(Filter.in("{identifier}", 777));`

**Comment by tobrun** [comment]
@LukasPaczos is right, filter only works on the feature properties.

**Comment by invised** [comment]
@LukasPaczos that is exactly what I did, I've specified it at the end of the first post, except that I didn't use {} brackets to identify the property

This issue is not a problem for me, just wanted to be sure it's not a bug

@tobrun thanks

**Comment by LukasPaczos** [comment]
I missed it, sorry!
Wrapping up - not a bug, but thanks for reaching out @invised!

**Comment by itko** [comment]
> @LukasPaczos is right, filter only works on the feature properties.

Shouldn't this be mentioned in the documentation? As far as I can tell, it's not at the moment.
