### ISSUE TITLE
App crash when updating marker postion

### ISSUE THREAD

**Issue by tan-tran-ea** [mapbox/mapbox-gl-native#11604]
**Platform: Android 6.0 + Kotlin**
**Mapbox SDK version: 5.5.1**

### Steps to trigger behavior

 1. Create a marker:
`marker = mapboxMap?.addMarker(this, latLng, R.drawable.map_marker)`
 2. Update marker location
`marker.position = latLng`

### Expected behavior
location of marker is updated
### Actual behavior
app is crashed, logs:
```
java.lang.ClassCastException: com.mapbox.mapboxsdk.annotations.Polyline cannot be cast to com.mapbox.mapboxsdk.annotations.Marker
        at com.mapbox.mapboxsdk.maps.IconManager.setTopOffsetPixels(IconManager.java:139)
        at com.mapbox.mapboxsdk.maps.IconManager.ensureIconLoaded(IconManager.java:134)
        at com.mapbox.mapboxsdk.maps.MarkerContainer.ensureIconLoaded(MarkerContainer.java:215)
        at com.mapbox.mapboxsdk.maps.MarkerContainer.update(MarkerContainer.java:80)
        at com.mapbox.mapboxsdk.maps.AnnotationManager.updateMarker(AnnotationManager.java:185)
        at com.mapbox.mapboxsdk.maps.MapboxMap.updateMarker(MapboxMap.java:1301)
        at com.mapbox.mapboxsdk.annotations.Marker.setPosition(Marker.java:126)
```

Kotlin extension for adding marker: 
```
internal fun MapboxMap.addMarker(context: Context, latLng: LatLng?, resId: Int): Marker? {
  return latLng?.let {
    addMarker(MarkerOptions()
        .position(latLng)
        .icon(getIconFromDrawableXml(context, resId)))
  }
}

```

**Comment by LukasPaczos** [comment]
Thanks for the report @tan-tran-ea.
I wasn't able to reproduce the issue neither in Java nor Kotlin.
Here is the code I used in Kotlin
```
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_map_simple)
    mapView = findViewById(R.id.mapView) as MapView
    mapView?.onCreate(savedInstanceState)
    mapView?.getMapAsync { mapboxMap ->
        val marker = mapboxMap.addMarker(
                this@SimpleMapActivity,
                LatLng(50.0, 16.0),
                R.drawable.mapbox_mylocation_icon_default)
        mapboxMap.addOnMapClickListener {
            marker?.position = LatLng(50.0, 17.0)
        }
    }
}

...

internal fun MapboxMap.addMarker(context: Context, latLng: LatLng?, resId: Int): Marker? {
    return latLng?.let {
        addMarker(MarkerOptions()
                .position(latLng)
                .icon(IconFactory.getInstance(context).fromResource(resId)))
    }
}
```
Could you include some code that refers to the Polylines? It seems like you are also working with them.
Are you manipulating any other annotations ID's?

**Comment by tan-tran-ea** [comment]
@LukasPaczos Yes, I'm drawing the polyline also, here is the code:

display 2 locations when the map is ready:

```
override fun onMapReady(mapboxMap: MapboxMap) {
    this.mapboxMap = mapboxMap.apply {
        mapboxMap.addMarker(this@MainActivity, startingLatLng, R.drawable.map_marker_start)
        mapboxMap.addMarker(this@MainActivity, endingLatLng, R.drawable.map_marker_end)
    }
}
```

then everytime I have a user location, I update the current location and draw a route from current location to starting location:

private fun displayCurrentLocation(location: Location) {
    currentLatLng = LatLng(location.latitude, location.longitude)
    if (currentLocationMarker == null) {
      currentLocationMarker = mapboxMap?.addMarker(this, currentLatLng,
          R.drawable.map_marker_current_location)

      mapboxMap?.animateCamera(newLatLngZoom(currentLatLng!!, 16.0), 3000)
    } else {
      currentLocationMarker!!.position = currentLatLng
    }

    navigationRoute.getRoute(currentLatLng!!, startingLatLng!!, object : NavigationRouteCallback() {
      override fun onRouteResponse(latLngs: List<LatLng>, distance: Double, duration: Double) {
        if (latLngs.isNotEmpty()) {
          route?.remove()
          route = mapboxMap?.addPolyline(
              PolylineOptions().addAll(latLngs).width(3f).color(Color.BLACK))

          tvDuration.text = "${(duration / 60).toInt()} mins"
          tvDistance.text = "${(distance / 1000).toInt()} km"
        }
      }
    })
  }

oops, I see that I'm using the remove method, maybe it's the cause, I will change it and test again

**Comment by tan-tran-ea** [comment]
@LukasPaczos I have changed to use mapboxMap?.removePolyline instead of route?.remove() and it's ok now, sorry, will close this issue
