### ISSUE TITLE
coordinate conversion incorrect during animated zooms

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1160]
Discovered in https://github.com/mapbox/mapbox-gl-native/issues/1125, when the map is zooming animated (like say after a double-tap zoom in), the geo-to-viewport conversions are vastly out of range, leading to a disappearing user dot until the animation is complete. 

You can confirm this with the following [patch](https://gist.github.com/incanus/742ddb29a13b60335641) against https://github.com/mapbox/mapbox-gl-native/commit/3ed1e7a695491120020e00ff3dc7926dba71834e: 

```diff
diff --git a/platform/ios/MGLMapView.mm b/platform/ios/MGLMapView.mm
index 49cfdd3..824e826 100644
--- a/platform/ios/MGLMapView.mm
+++ b/platform/ios/MGLMapView.mm
@@ -2117,6 +2117,8 @@ CLLocationCoordinate2D latLngToCoordinate(mbgl::LatLng latLng)
     }
     else
     {
+        NSLog(@"hiding user dot since out of viewport: %@", [NSValue valueWithCGPoint:userPoint]);
+
         self.userLocationAnnotationView.layer.hidden = YES;
     }
 }
```

First, showing normal out-of-viewport hiding, then showing during animation: 

![anigif-1427741775](https://cloud.githubusercontent.com/assets/17722/6904192/f3cf2752-d6d3-11e4-9cd2-46ef986533aa.gif)

This appears to be down in the `projection.hpp` C++ level.

**Comment by incanus** [comment]
@jfirebaugh This could use some :eyes: if you've any bandwidth.

**Comment by jfirebaugh** [comment]
Is it possible this was caused by the same issue as #1181?

**Comment by incanus** [comment]
I tested this morning after merge just to be sure, and no.

**Comment by jfirebaugh** [comment]
@ansis, could you take a look at this?

**Comment by incanus** [comment]
AGHGHGGH SO GOOD
