### ISSUE TITLE
Android offset center feature

### ISSUE THREAD

**Issue by adauvalter** [mapbox/mapbox-gl-native#11624]
Any plans to implement offset center method on the map in the case if the map overlays with some UI like a BottomSheet for example?

**Comment by tobrun** [comment]
@adauvalter you can use map padding for that with `MapboxMap#setPadding(int left, int top, int right, int bottom`. Closing as answered.

**Comment by adauvalter** [comment]
Already tried to use padding on the fly, when BottomSheet comes up. It occurs some strange some and movements of the camera.

**Comment by samiede** [comment]
Hey guys!
In my application, the camera is not updated automatically, (which is to be expected as there is no function call to moveCamera in setPadding anymore). I can't come up with a function to correctly do the camera movement without losing the correct camera position after opening a bottom drawer and closing it. Could someone point me in the right direction? :)

Thanks!

**Comment by AlanLarsson** [comment]
Is there some way to offset center with map tilted? 
SetPadding only moves the camera up, without moving the point closer to the user.
