### ISSUE TITLE
Custom Markers And Street Names Disappear on Rotate Map Close Zoom Map Pitched

### ISSUE THREAD

**Issue by TimmyBest** [mapbox/mapbox-gl-native#11622]
**Platform:** iOS
**Mapbox SDK version:** 3.7.6

### Steps to trigger behavior

 1. Implement the Mapbox [Custom Marker Example](https://www.mapbox.com/ios-sdk/examples/marker-image/)
 2. Zoom to the marker
 3. Pitch the map (two fingers slide up gesture)
 4. Rotate the map (two fingers slide-rotate gesture)

### Screencast of behavior 
Download [here ](https://drive.google.com/open?id=1F0s4FIwAujl7LcTuxh3YjLScUX3J2AMb)
(iPhone7, iOS 11.2.2, Mapbox mapbox-ios-sdk-3.7.6-dynamic.zip installed)

### Issue Reproducing Project
[ git Repo](https://github.com/TimmyBest/MapboxTestT)

### Expected behavior
 Markers and street names do not disappear
### Actual behavior
 Markers and street names DO disappear, and re-appear after rotating to a different angle, 
or after zooming out,
or after decreasing the pitch.

**Comment by jmkiley** [comment]
Hello @TimmyBest -

Thank you for the bug report and steps to reproduce it. I do see this issue in v3.7.6, but it looks like it has been resolved as of 4.0.0-beta.3. Please let us know if you continue to see this issue on the [latest beta](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v4.0.0-beta.3).

**Comment by ChrisLoer** [comment]
I haven't actually tried out the reproduction case, but this sounds like something we fixed with PR #10436. 🙂
