### ISSUE TITLE
Switch to yarn for JS/node package management

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#11620]
We currently use npm to install JavaScript packages that are build and test dependencies, but it appears that yarn is preferable for this task and we should look into switching.

Refs https://github.com/mapbox/mapbox-gl-js/pull/6470#issuecomment-379362986.

/cc @kkaefer @brunoabinader @jfirebaugh @mourner

**Comment by kkaefer** [comment]
Switching to yarn means that we'll also have to integrate this into our CMake build, which currently handles running npm install/update to ensure dependencies are kept fresh. Before running yarn, we'd have to ensure that it's installed/updates. Yarn is typically installed globally, but automatically installing software that is available to the user on a system-wide scope isn't good practice.

Alternatively, we could just expect that yarn is installed and error in CMake when we can't find yarn.
