### ISSUE TITLE
setPadding with aimateCamera occurs zoom unexpectedly

### ISSUE THREAD

**Issue by adauvalter** [mapbox/mapbox-gl-native#11626]
**Platform:** Android
**Mapbox SDK version:** 5.3.1

### Steps to trigger behavior

 1. use `setPading` method
 2. use animateCamera for center some marker on the either with the same Zoom level `.zoom(mapboxMap.getCameraPosition().zoom)` or without call this method 

### Expected behavior
Only movements of the camera expected
### Actual behavior
Not only movements but also a zoom in both cases

**Comment by LukasPaczos** [comment]
@adauvalter `MapboxMap#animateCamera` is the type of movement that animates zoom back and forth to imitate a "jump". I tested it out with the upcoming `6.0.0` release and a zoom level before initiating the movement is identical to the zoom level after the movement finished.

If you are looking for a movement that doesn't animate the zoom try using `MapboxMap#easeCamera` instead.
