### ISSUE TITLE
Pins on map disappear when zoom-in and rotate/tilt the map

### ISSUE THREAD

**Issue by Yangg1223** [mapbox/mapbox-gl-native#11623]
**Platform: Android (test phone: Samsung S5 with Android 6.0.1)**
**Mapbox SDK version: mapbox-android-sdk:5.5.1**

### Steps to trigger behavior

 1. Create a bunch of pins on the map
 2. Zoom in, rotate/tilt map to a certain angle
 3. You can see the pins start disappearing

### Expected behavior
Pins do not disappear
### Actual behavior
Pins disappear

### Test Code (nearly copy-paste Mapbox native tutorial)
https://github.com/Yangg1223/MapboxPinDisappearBug

### Recording video
![2803uu](https://user-images.githubusercontent.com/13507365/38477569-72cd5e70-3c07-11e8-8196-40a6f1fe6909.gif)

**Comment by LukasPaczos** [comment]
Thanks for reaching out @Yangg1223. Various issues regarding annotations and layers flickering have been addressed in the upcoming `6.0.0` release and quickly testing it out I don't see this one happening anymore.
Please feel free to re-test it with `6.0.0-beta.6` or with the upcoming stable release and reopen if necessary.

**Comment by atoropov** [comment]
I am using `com.mapbox.mapboxsdk:mapbox-android-sdk:7.2.0` and still have similar issue
![ezgif-1-07e3fddd5e16](https://user-images.githubusercontent.com/5703185/53643612-9020f600-3c45-11e9-86d9-722c612ecc2d.gif)

**Comment by LukasPaczos** [comment]
Hey @atoropov, would you mind opening a new issue with some details regarding your layer setup and reproduction steps? Thank you!
