### ISSUE TITLE
[Android] Load image from url in callout view

### ISSUE THREAD

**Issue by chibeamed** [mapbox/mapbox-gl-native#11638]
Hi, I'm trying to load an image from url (using glide) for each callout view when the marker is selected. While I show the custom info window when a marker on the layer is selected, the image doesn't load. How can I do this?

**Platform:* Android*
**Mapbox SDK version:*5.5.1*

### How I tried doing it
```kotlin
private fun addMarkers(partners: List<Partners>) {
  val features = partners.map {
        val feature = Feature.fromGeometry(
          Point.fromCoordinates(doubleArrayOf(it.longitude.toDouble(), it.latitude.toDouble())))
        feature.addStringProperty("feature-id", it.id.toString())
        val gson = GsonBuilder().create()
        feature.addProperty("feature-chain-data", gson.toJsonTree(it.chain, Chain::class.java))
        feature.addBooleanProperty("selected", false)
        feature
      }
      val featureCollection = FeatureCollection.fromFeatures(features)
    //....
   // adding my callout layer
  featureCollection.features.forEach {
        val infoWindow = DataBindingUtil.inflate<SingleMapItemBinding>(LayoutInflater.from(context),
            R.layout.single_map_item, parent, false)
        val chainProperty = it.getProperty("feature-chain-data")
        val id = it.getStringProperty("feature-id")
        val chain = Gson().fromJson(chainProperty, Chain::class.java)
        chain?.let {
          val bitmap = infoWindow?.let {
            singleMapItemTvName.text = it.name
            singleMapItemTvDescription.text = it.missionDescription
            singleMapItemTvAddress.text = it.address
            GlideApp.with(singleMapItemIvLogo.context)
                .asBitmap()
                .load(it.logoImage)
                .placeholder(R.drawable.diginnyesyes)
                .circleCrop()
                .into(singleMapItemIvLogo)

          }?.root?.generate()
          bitmap ?: return
          imagesMap[id] = bitmap
          viewMap[id] = infoWindow.root
        }
     }
   mapBox.addImages(imagesMap)
      val calloutLayer = SymbolLayer("my-new-callout-layer-id", MARKER_SOURCE)
          .withProperties(
              PropertyFactory.iconImage("{feature-id}"),
              PropertyFactory.iconAnchor("bottom-left"))
          .withFilter(Filter.eq("selected", true))
      mapBox.addLayer(calloutLayer)
```
### Expected behavior
<img width="184" alt="screen shot 2018-04-10 at 10 10 20 
am" src="https://user-images.githubusercontent.com/37589087/38547716-b88d1c7a-3ca7-11e8-9376-62403a88418c.png">
### Actual behavior
<img width="189" alt="screen shot 2018-04-10 at 10 13 34 am" src="https://user-images.githubusercontent.com/37589087/38547799-f91c8654-3ca7-11e8-9230-f51904a55781.png">

If you see from the above, loading all glide images used in each marker's callout view, however, what I'll really want is to be able to create the callout image for that marker only when user selects the marker, and at that moment build the custom callout view and load the image (thereby saving me from unnecessary network calls, and showing the image that would be loaded).

**Comment by LukasPaczos** [comment]
Thanks for reaching out @chibeamed.
I'm trying to verify a couple of things here - you are calling
```
GlideApp.with(singleMapItemIvLogo.context)
                .asBitmap()
                .load(it.logoImage)
                .placeholder(R.drawable.diginnyesyes)
                .circleCrop()
                .into(singleMapItemIvLogo)
```
then immediately generating a bitmap out of the callout view, that's what `?.root?.generate()` is responsible for, right?
Isn't the glide call asynchronus and the image simply didn't have time to load before you generated a bitmap out of it?

Generally I don't see Maps SDK being at fault here, the map is only interested in the bitmap you provide, which is being shown correctly. The problem seems to be the bitmap generation itself.

**Comment by chibeamed** [comment]
Thanks @LukasPaczos for your response. Thats what the methods does, and `roo?.generate()` does the image loading asynchronously! (skipped my mind) How do I do it such that the callout window is created when the marker is selected and I can use the data I have in the feature to create the callout window? Also, the approach I listed above means I have to make those requests for each of the many markers I have, which isn't good, so how do I make sure this only happens when the call out window is about to be shown.

btw, now I can show the images for the marker by generating and adding the image and id in the Glide RequestListener::onResourceReady, and it now works, but the above issue still persists.

**Comment by LukasPaczos** [comment]
I'm glad it's working for you. When it comes to requests issues, I'd look into downloading images only for markers in an expanded visible region, then refreshing the callout window bitmaps and caching the results for future use (Glide probably does that automatically to some extent). Downloading an image and refreshing the callout window only after the click might result in a poor UX.

Going to close the issue as it's not directly related to the Maps SDK.

**Comment by chibeamed** [comment]
I don't think its not a Maps SDK issue, because with the API, I still can't figure out how its possible to create a callout window for a marker item at the time when that symbol layer marker item is selected. I only download image only for markers in an expanded region, and glide caches the images automatically, however there're many markers in a single location such that downloading all those images for those markers is not good and slows down my app as I have to wait for those images to be downloaded and set in the image before generating the bitmap image for that marker. So my issue still is, how do I create the callout window (it's a custom layout) for a marker only when that item is selected, so I can only load that image at that point).
