### ISSUE TITLE
make clean leaves Android builds in inconsistent state

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#11652]
**Platform:Android**
**Mapbox SDK version:Master**

### Steps to trigger behavior

 1. Checkout new repository and build using make android. Everything builds as expected.
 2. make clean
 3. Now do make android. Build fails.

make clean should clean using the clean task in gradle script.

Doing this manually cleans correctly.

    ./gradlew -Pmapbox.abis=armeabi-v7a MapboxGLAndroidSDK:clean
./gradlew -Pmapbox.abis=armeabi-v7a MapboxGLAndroidSDKTestApp:clean

### Expected behavior
make clean should leave build in a state where it can be build again via make android.
### Actual behavior
Clean via the command line above or Android studio is needed to restore it back to consistent state.

**Comment by tobrun** [comment]
Not able to reproduce with provided steps, could you provide the error you were seeing?

**Comment by mb12** [comment]
This is to confirm that I am no longer able to reproduce the error either. The only change in my environment is that I have added ccache in the path. The error was some file missing in the path 'platform/android/MapboxGLAndroidSDK/.externalNativeBuild....'. Sorry I didn't preserve the exact error log.
If it reproduces, I will open a new issue. 
Thanks for looking into it.
