### ISSUE TITLE
check out NSURLSession for metrics

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1166]
We use `NSURLConnection` for metrics now, but we should check out `NSURLSession`, which is what we use for [all the other](https://github.com/mapbox/mapbox-gl-native/blob/1bb04ce65b4bb070b5df9e860e85123634a41184/platform/darwin/http_request_nsurl.mm#L95-L100) Darwin (OS X / iOS) HTTP requests. Sessions give you the ability to intelligently manage groups of connections, so settings things like user agent or max connections just once. 

Check out some docs: 

https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSessionConfiguration_class/index.html#//apple_ref/occ/cl/NSURLSessionConfiguration

There are some great switches for things like: 

* headers
* timeouts
* `networkServiceType`

    > The network service type provides a hint to the operating system about what the underlying traffic is used for. This hint enhances the system's ability to prioritize traffic, determine how quickly it needs to wake up the cellular or Wi-Fi radio, and so on.
* `allowsCellularAccess`

    > This property controls whether tasks in sessions based on this session configuration are allowed to make connections over a cellular network.
* caching policies
* TLS min/max version policies
* and more! 

This could help incrementally with battery use, too. 

/cc @bleege

**Comment by bleege** [comment]
Refactored Metrics to use NSURLSession.  Wasn't able to take advantage of setting Headers at the `NSURLSessionConfiguration` level in `init` as setting `User-Agent` requires access to the fully instantiated `MGLMapboxEvents` object.

Reviewed other configuration options in ` NSURLSessionConfiguration` and determined that the the defaults (networkServiceType and allowsCellularAccess specifically) already are set to what the Metrics API needs for now.  Certainly can add to this in the future though.

Waiting for Travis CI to finish building and then will merge.

**Comment by bleege** [comment]
Travis finally approved.  :-)  Merged!
