### ISSUE TITLE
Failed to load source composite

### ISSUE THREAD

**Issue by keehoo** [mapbox/mapbox-gl-native#11667]
**Platform:** 
Android 7.0
**Mapbox SDK version:**
5.5.1

### Steps to trigger behavior

 1. Add a MapView inside a Fragment (with all necessary lifecycle methods)
 2. Check that maps displays fine with standard light map (styleUrl `            mapbox:mapbox_styleUrl="@string/mapbox_style_light"
)`
 3. Change map style with both XML styleUrl and runtime setStyleUrl 
4. Observe that map is black, but the pointer (marker) to a location is displayed.
5. The following log is found in the logical: 

> 04-12 08:11:49.404 11941-11941/com.signal.tonnagelist.dev.debug E/mbgl: {elist.dev.debug}[Style]: Failed to load source composite: bounds latitude values must be between -90 and 90 with bottom less than top

### Expected behavior
The styleUrl that was given is already in production for both iOS and frontend. I'd expect to see the same styled map as on both of the maps mentioned above

### Actual behavior
The map is black, but the pointer is visible and I can move the black map (based on the movement of the marker)

**Comment by tobrun** [comment]
@keehoo could you retest with v5.5.2? This looks like a bug we recently addressed though that already shipped with v5.0.0 https://github.com/mapbox/mapbox-gl-native/pull/11178.

**Comment by keehoo** [comment]
@tobrun Unfortunately upgrading the lib to 5.2.2 hasn't solved the issue. Still getting the same log in logcat and the map displays black.

**Comment by tobrun** [comment]
@keehoo are you loading a mapbox hosted style? if so, could you add style url? 
cc @asheemmamoowala as this error looks similar to the one fixed in #11178.

**Comment by keehoo** [comment]
style url :

>  mapbox://styles/axypas/cj3lnok4900032rpl3d8niyf2

It does seems similar. Is there anything that I might "hard code" to set these bounds as per the range in runtime?
Thank you in advance,
Keehoo

**Comment by tobrun** [comment]
Closing as stale, please reach out if you are still hitting this issue!

**Comment by vinoth-berkmons** [comment]
Hi, 
I am new to mapbox.

while loading the map am getting below error


 ERROR  Mapbox error {com.xxx}[Style]: Failed to load source composite: HTTP status code 403 {"level": "error", "message": "{com.xxx}[Style]: Failed to load source composite: HTTP status code 403", "tag": "Mbgl"}
