### ISSUE TITLE
MapView hook into View removal, resolve freeze

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#11685]
We have heard about issues of fragments not correctly integrating into our SDK due to `MapView#onDestroy` only being called by `Fragment#onDestroy` while it should be called by `Fragment#onDestroyView`. 

The underlying issue is that the render surface needs to be destroyed before we remove the hosting view. We should analyse if it's possible to hook into view removal and call `MapView#onPause/MapView#onStop/MapView#onDestroy` as part of it.

**Comment by tikimcfee** [comment]
> We should analyse if it's possible to hook into view removal and call MapView#onPause/MapView#onStop/MapView#onDestroy as part of it.

+1! +5! This would be great! It's tough to get some attach/detach flows working from the outside looking in when doing things like animation or manual view management (remove and reattach somewhere else). Wish you luck on this, and hope the Android view listening APIs give ya enough info.

**Comment by tobrun** [comment]
Announced at Google I/O was the following editor for app flow:

![screenshot from 2018-05-11 10-45-50](https://user-images.githubusercontent.com/2151639/39915563-8ee5adbe-5508-11e8-9fb8-0c51141a87ab.png)

It looks like the code generated for that shows using a static fragment:

![screenshot from 2018-05-11 10-43-12](https://user-images.githubusercontent.com/2151639/39915587-9dc7053a-5508-11e8-894a-7138b8320d5b.png)

Since this issue is reproducible with static fragments, I think we should prioritize this.

cc @mapbox/maps-android

**Comment by dylanhiemstra** [comment]
Any updates on this issue?

**Comment by tobrun** [comment]
Yes, still under investigation, the gist is that we try to cleanup the map while the render thread is already destroyed. We need a refactoring in setup to resolve this.

**Comment by tobrun** [comment]
The issue was introduced as part of https://github.com/mapbox/mapbox-gl-native/commit/18bb6da10968872e585b6e0b787f45cb3a806b76. There are situations where the underlying GL render thread is already destroyed (one example being Fragment setup with destroy/destroyView ). In those case it freezes as resetRenderer is never called.

**Comment by fredo-** [comment]
Sorry, I'm still a little confused @tobrun. How does this last merge request fix issue #10205?
My main issue being: if I'm using Conductor with Mapbox, where do I call `mapView.onDestroy()`? Since calling it in Conductor's `onDestroyView()` crashes the app.

**Comment by zugaldia** [comment]
@fredo- thanks for the feedback on `Conductor`. Would you mind [cutting a separate ticket](https://github.com/mapbox/mapbox-gl-native/issues/new?template=android.md) about the issue you're seeing to avoid conflating the two conversations?

**Comment by kshailes** [comment]
I can find solution anywhere?

**Comment by zugaldia** [comment]
@kshailes we believe this issue was solved by https://github.com/mapbox/mapbox-gl-native/pull/13926. If you're still observing this freeze, please cut a separate ticket on https://github.com/mapbox/mapbox-gl-native-android and the team will follow up. Thanks.
