### ISSUE TITLE
Unexpected behavior when using MGLSymbolStyleLayer with multiple UIImageRenderingModes

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-gl-native#11682]
**Platform:** iOS
**Mapbox SDK version:** v4.0.0-beta.3, v3.7.6

### Steps to trigger behavior

 1. Create a map view and add a new MGLSymbolStyleLayer from [the following GeoJSON file](https://github.com/captainbarbosa/gl-native-image-symbol-bug/blob/master/gl-native-symbol-bug/points.geojson).
 2. Include the following two PDF images within `Assets.xcassets`:
    - [Image 1 - camera](https://github.com/captainbarbosa/gl-native-image-symbol-bug/blob/master/gl-native-symbol-bug/Assets.xcassets/camera.imageset/camera.pdf)
    - [Image 2 - star](https://github.com/captainbarbosa/gl-native-image-symbol-bug/blob/master/gl-native-symbol-bug/Assets.xcassets/star.imageset/star.pdf)
3. Set the `UIImageRenderingMode` for the star image to `alwaysTemplate`
4. Set the `UIImageRenderingMode` for the camera image to `alwaysOriginal`
 2. Create a [data expression](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions) (or property function is using pre-4.0.0 release) to apply a different  `iconImageName` to each symbol based on its `name` property.
3. Assign a tint color to the `MGLSymbolStyleLayer`
4. Observe unexpected behavior

_[The full minimal test case can be found here.](https://github.com/captainbarbosa/gl-native-image-symbol-bug)_

### Expected behavior
The camera image that has `UIImageRenderingMode` set to `alwaysOriginal` should always be rendered as the original image, like so:

<img height="470" src="https://user-images.githubusercontent.com/10850812/38757627-87b38788-3f22-11e8-9bb7-41e64dfa2b4b.png" />

### Actual behavior

The camera image, which has its `UIImageRenderingMode` set to `alwaysOriginal`, is being rendered as a template image with the specified tint color _only at zoom levels lower than z12_.

![bug](https://user-images.githubusercontent.com/10850812/38757714-dbc78202-3f22-11e8-8f5a-38d69d459d11.gif)

If you swap the rendering modes for the camera and start images, the star image, which has its `UIImageRenderingMode` set to `alwaysOriginal`, is being rendered as a template image with the specified tint color _only at zoom levels lower than z14_.

![bug2](https://user-images.githubusercontent.com/10850812/38757934-adc0b26a-3f23-11e8-8441-de72fbca072f.gif)

**Comment by andy-remi** [comment]
We are having the same issue with this problem. Especially the displaying problem is being shown on iPhone 6S and iPhone X(seems not working correctly on the big screen models. iPhone 6 and iPhone SE were ok without any problems). We tried to display annotations with png files and pdf files in various way like various resolutions, but it didn't make any difference and still having the displaying problem. We've confirmed it's exactly the problem of MGLSymbolStyleLayer. Of course we called mapView.style?.setImage() before calling mapView.style?.addLayer(). We tried to change MGLSymbolStyleLayer to MGLCircleStyleLayer and then there was no problem but we can't use images with MGLCircleStyleLayer. It's a problem.
Below url is the screen capture in the error situation.

[http://52.52.182.203/imagebug.jpg](http://52.52.182.203/imagebug.jpg)

That should be shown as below if there was no problem:

[http://52.52.182.203/imagecorrect.jpg](http://52.52.182.203/imagecorrect.jpg)

**Comment by 1ec5** [comment]
If the rendering mode is “Always Template” in the asset catalog or `UIImageRenderingModeAlwaysTemplate` in code, then mbgl treats it as an SDF image; otherwise, it treats it like a normal image with color and alpha channels:

https://github.com/mapbox/mapbox-gl-native/blob/d05fa404a8b2d67c908c857cbebacd38f594052a/platform/ios/src/UIImage%2BMGLAdditions.mm#L39-L42

Does this issue also reproduce when the rendering mode is “Default” in the asset catalog or `UIImageRenderingModeAutomatic` in code?

**Comment by andy-remi** [comment]
Thanks for suggesting the solution but we already tried with the rendering mode in various way with 4 channels png files and had no luck.
