### ISSUE TITLE
Remove mgl_ prefix from built-in expression variables

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#11683]
In https://github.com/mapbox/mapbox-gl-native/pull/11528#discussion_r177309911, I suggested prepending an `mgl_` prefix to built-in expression variables, that is `$mgl_geometryType` and `$mgl_featureType`. However, I didn’t fully consider that `$zoomLevel` and `$heatmapDensity` are already unprefixed and probably should remain that way for ergonomic reasons. #11472 introduced an `MGL_FUNCTION()` syntax, offering a way out in case there do happen to be conflicts with style-defined variables.

We should remove the `mgl_` prefix from `$mgl_geometryType` and `$mgl_featureType` and also document `MGL_FUNCTION('zoom')` etc. as alternative syntax for `$zoomLevel` and the like.

/ref #11010
/cc @fabian-guerra @jmkiley

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/11689
