### ISSUE TITLE
The best way to show the too many markers that each markers hava other bitmap image on the mapbox map?

### ISSUE THREAD

**Issue by hohoins** [mapbox/mapbox-gl-native#11684]
Platform: Android N(27)
Mapbox SDK version: 6.0.0-beta.6

It's no bug.
"The best way to show the too many markers that each markers have other bitmap image on the mapbox map?"

### Expected behavior
I had the many markers that each markers have other bitmap image.
The something that i want is load the image bitmap about current visible markers because memory performance.

but I am using the 'MapboxMap.addMarker()' in mapbox android sdk 6.0.0-beta6.

val iconFactory = IconFactory.getInstance(context!!)
val icon = iconFactory.fromBitmap(...)
mapboxMap.addMarker(MarkerOptions().icon(icon).position(...).title(...).setSnippet(...)

This code has the problem because the all bitmaps are loaded on start this screen.

### Actual behavior
I want to know the way that to load the bitmap about current visible markers.

**Comment by LukasPaczos** [comment]
Thanks for reaching out @hohoins. To achieve that you could utilize Projection API and check whether a marker is in the visible region whenever camera stops and add it only if it's inside:
```
mapboxMap.addOnCameraIdleListener(new MapboxMap.OnCameraIdleListener() {
  @Override
  public void onCameraIdle() {
    boolean isInRegion = mapboxMap.getProjection().getVisibleRegion().latLngBounds.contains(markerLatLng);
    if (isInRegion) {
      // add a marker
    }
  }
});
```
You could also resize the region itself to cover a bigger area.
