### ISSUE TITLE
Port 'Collator' string comparison support to native

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native#11692]
Port of https://github.com/mapbox/mapbox-gl-js/pull/6270, see also design discussion at https://github.com/mapbox/mapbox-gl-js/issues/4136.

Unfortunately this isn't a trivial port because we'll depend on platform-specific behavior. The rough plan is to implement this is to use built-in string comparison support on iOS and Android, and to bundle ICU (along with the necessary resource bundle) for other platforms. I suspect we won't figure out what we're actually going to do with Qt until the rubber hits the road.

/cc @anandthakker @nickidlugash @1ec5 @brunoabinader

**Comment by brunoabinader** [comment]
For Qt, we should probably follow the same procedure as adopted for other platforms using ICU as backend.

**Comment by tobrun** [comment]
This landed, follow up tickets #12268 and #12269 for Android/iOS
