### ISSUE TITLE
confirm tile draw priority

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#117]
In working on #115 raster tile crossfading, I wanted to make sure that I understand the current desired intent with drawing tiles, including parent and children tiles for currently un-parsed native zoom tiles. This is important because it affects what textures are on screen when crossfading occurs. 

Say we are at the top left of `z8`. In the best case scenario, we want these tiles to draw: 

```
+-------+-------+
|       |       |
| 8,0,0 | 8,1,0 |
|       |       |
+-------+-------+
|       |       |
| 8,0,1 | 8,1,1 |
|       |       |
+-------+-------+
```

If all we have for a missing `8,1,1` is one of its child tiles from `z9`, we instead get this (not to scale): 

```
+-------+---------------+
|       |               |
| 8,0,0 |     8,1,0     |
|       |               |
+-------+-------+-------+
|       |       |       |
| 8,0,1 +-------+-------+
|       |       | 9,3,3 |
+-------+-------+-------+
```

When `8,1,1` does come in, it's drawn, `9,3,3` is not, and all is good. 

On the flip side, if all we have for a missing `8,1,1` is its direct *parent* tile `7,0,0`, what we want is this: 

```
+-------+---------------+
|       |               |
| 8,0,0 |     8,1,0     |
|       |               |
+-------+---------------+
|       |               |
|       |  lower-right  |
| 8,0,1 |  quarter of   |
|       |     7,0,0     |
|       |               |
+-------+---------------+
```

But instead, we first draw the three `z8` tiles (per high zoom sort order front to back), then draw `7,0,0` like this, since this `z7` tile is the parent of all four `z8` tiles in question: 

```
+-----------------------+
|                       |
|                       |
|                       |
|                       |
|         7,0,0         |
|                       |
|                       |
|                       |
|                       |
+-----------------------+
```

We don't make any extra draw calls (three native `z8` tiles unclobbered + one clipped `z7` vs. three native `z8` tiles clobbered + one full `z7` tile) but we do extra work for unnecessary tile fade animations on the `z8` tiles, plus we lose out on the higher resolution available in the clobbered `z8` tiles until `8,1,1` finishes coming in.

**Comment by jfirebaugh** [comment]
Closing old ticket; I don't think we know of any serious issues with our current tile priority.
