### ISSUE TITLE
After removing marker from the map needs to do some actions to see result

### ISSUE THREAD

**Issue by vadimleonov** [mapbox/mapbox-gl-native#11701]
**Platform:** Android
**Mapbox SDK version:**
LocationLayer: 0.3.0
Navigation: 0.9.0
Navigation-ui: 0.9.0
Mapbox-sdk:5.3.2

### Steps to trigger behavior

 1. Add market to the map: map.addMarker(marker)
 2. And remove them:  map.removeMarker(marker)

### Expected behavior
Marker is removed from the map

### Actual behavior
Unless we don't touch the map, marker is not removed. Needs to swipe/zoomIn/ZoomOut map to see changes... IMO we need function like notifyDataChanges() like in recyclerview to redraw map

**Comment by tobrun** [comment]
This seems like MarkerView behaviour and this is a deprecated api. I would advice using the normal marker or SymbolLayer api instead. FWIW you can invalidate markerviews with `mapboxMap#getMarkerViewManger().invalidateMarkerViewsInRegion()`.

**Comment by vadimleonov** [comment]
I don't use `MarkerView`
I'm using com.mapbox.mapboxsdk.annotations.Marker remove marker

`  /**
   * <p>
   * Convenience method for removing a Marker from the map.
   * </p>
   * Calls removeAnnotation() internally.
   *
   * @param marker Marker to remove
   */
  public void removeMarker(@NonNull Marker marker) {
    annotationManager.removeAnnotation(marker);
  }`


and to add

` /**
   * <p>
   * Adds a marker to this map.
   * </p>
   * The marker's icon is rendered on the map at the location {@code Marker.position}.
   * If {@code Marker.title} is defined, the map shows an info box with the marker's title and snippet.
   *
   * @param markerOptions A marker options object that defines how to render the marker
   * @return The {@code Marker} that was added to the map
   */
  @NonNull
  public Marker addMarker(@NonNull BaseMarkerOptions markerOptions) {
    return annotationManager.addMarker(markerOptions, this);
  }`
