### ISSUE TITLE
Implement line-gradient property

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#11718]
mapbox/mapbox-gl-js#6303 needs to be ported to this codebase and exposed as part of the runtime styling API. The [gradient branch](https://github.com/mapbox/mapbox-gl-native/compare/gradient) contains some early work towards implementing the `line-gradient` property.

/ref mapbox/mapbox-gl-js#4095
/cc @lbud

**Comment by lbud** [comment]
😅 I've been working on porting geojson-vt changes to geojson-vt-cpp, and then will pick the gradient branch back up.

**Comment by danpe** [comment]
👍

**Comment by brunoabinader** [comment]
This has been implemented in #12575.
