### ISSUE TITLE
MGLAnnotationView sticked on the screen border when change the camera heading

### ISSUE THREAD

**Issue by kiklenain** [mapbox/mapbox-gl-native#11711]
**Platform: iOS 11.3 / 10.1.1
**Mapbox SDK version: 3.7.6

 1. Pitch the map
 2. Place MGLAnnotationView
 3. Change camera heading by rotation gesture or with camera.heading or with MGLMapCamera.init + MGLMapView.setCenter then drag the map or set another camera centerCoordinate

### Expected behavior
The MGLAnnotationView should correctly follow the map

### Actual behavior
MGLAnnotationView are sticked on the screen border

![mapbox_git_annotation mov](https://user-images.githubusercontent.com/4135569/38880596-643bf776-4266-11e8-91fd-e177bac158ee.gif)

**Comment by julianrex** [comment]
Thanks for reporting this issue @kiklenain - can you provide a minimal sample application that demonstrates this bug?
