### ISSUE TITLE
Crash com.mapbox.mbgl.DefaultFileSource

### ISSUE THREAD

**Issue by iBinh** [mapbox/mapbox-gl-native#11722]
**Platform:** iOS
**Mapbox SDK version:** 4.0.0.rc.1

### Steps to trigger behavior

 1. Add mapview in interface builder
 2. Configure MGLMapView

### Expected behavior
Working

### Actual behavior
Crash:
```
2018-04-18 15:52:58.425079+0700 App[756:112583] [INFO] {com.mapbox.mbgl.DefaultFileSour}[Database]: cannot open file at line 40840 of [2b0954060f] (Code 14)
2018-04-18 15:52:58.425812+0700 App[756:112583] [INFO] {com.mapbox.mbgl.DefaultFileSour}[Database]: [2b0954060f]:40840: (0) open(/var/mobile/Containers/Data/Application/1480A797-8A81-4316-8CB9-08405949B410/Library/Application Support/com.abc.xyz/.mapbox/cache.db) - Undefined error: 0 (Code 14)

```

https://i.imgur.com/JJuRckm.png

**Comment by friedbunny** [comment]
This isn’t a crash — it’s an exception. Please see #10796.

**Comment by jontyt** [comment]
@friedbunny This is a crash though? I'm receiving com.mapbox.mbgl.DefaultFileSource (12): EXC_BAD_ACCESS (code=1, address=0x0), but only for the first time the application opens.

**Comment by friedbunny** [comment]
@jontyt That indeed does not sound typical — if you could go ahead and open a new issue with the stack trace, console logs, etc., that’d be much appreciated. 🙇

**Comment by jontyt** [comment]
Sweet, will do!

**Comment by julianrex** [comment]
@jontyt did you solve your crash? I see you didn't open a new issue.

**Comment by pedrocruzlopez** [comment]
@julianrex, @friedbunny please re-open this issue, I'm experiencing this scenario and I'm just adding a map on the viewDidLoad method of my main controller. Any ideas?

**Comment by pedrocruzlopez** [comment]
This si the stack trace: 
<img width="1060" alt="Screen Shot 2019-04-04 at 23 57 49" src="https://user-images.githubusercontent.com/12741167/55606288-7c314e00-5735-11e9-9b4c-5c493b5b0000.png">

**Comment by friedbunny** [comment]
@pedrocruzlopez If you could also open a new issue and follow the template (especially around providing a reproduction), we’d be best able to investigate the crash you’re seeing. 🙇
