### ISSUE TITLE
com.mapbox.mapboxsdk.storage.FileSource.deactivate crash

### ISSUE THREAD

**Issue by osana** [mapbox/mapbox-gl-native#11727]
An issue reported in mapbox-java  https://github.com/mapbox/mapbox-java/issues/798

It's been reported a crash 5 times on Crashlitics (in few days on a small number of devices)
mapbox-android-sdk:5.5.0
Android 7 and 7.1.1
Devices: 3 of them are Moto G5

Fatal Exception: java.lang.Error
Bad optional Access
 
StackTrace:
com.mapbox.mapboxsdk.storage.FileSource.deactivate (SourceFile)
com.mapbox.mapboxsdk.maps.MapView.onStop (SourceFile:394)
com.arlabsmobile.altimeter.MapsFragment.onStop (SourceFile:660)
android.support.v4.app.Fragment.performStop (SourceFile:2545)
android.support.v4.app.FragmentManagerImpl.moveToState (SourceFile:1492)
android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState (SourceFile:1759)
android.support.v4.app.FragmentManagerImpl.moveToState (SourceFile:1827)
android.support.v4.app.FragmentManagerImpl.dispatchStateChange (SourceFile:3244)
android.support.v4.app.FragmentManagerImpl.dispatchStop (SourceFile:3221)
android.support.v4.app.FragmentController.dispatchStop (SourceFile:239)
android.support.v4.app.FragmentActivity.onStop (SourceFile:619)
android.support.v7.app.AppCompatActivity.onStop (SourceFile:183)
com.arlabsmobile.altimeter.MainActivity.onStop (SourceFile:389)
...

cc @ArLabDev

**Comment by LukasPaczos** [comment]
@ArLabDev If you are using `MapView` inside a `Fragment` you need to call `MapView#onDestroy` from you fragment's `Fragment#onDestroyView` method, not `Fragment#onDestroy`. Could you verify if that's the case?
You can also use our `MapFragment` class that takes care of those lifecycle calls.

**Comment by tobrun** [comment]
in those cases you need to call:

```
MapView#onCreate
MapView#onStart
MapView#onResume
...
MapView#onPause
MapView#onStop
MapView#onDestroy
```
