### ISSUE TITLE
pointAnnotation disappeared when pitch、zoom and rotate?

### ISSUE THREAD

**Issue by thomas-ho** [mapbox/mapbox-gl-native#11721]
I've just add about 5(or more) PointAnnotations around a point , when pitch , then zoom and  rotate around , annotation will disappear.
here is code, just add to SDK Examples->BuildingsExample.m
here is video about [this.](http://brtbeacon.oss-cn-beijing.aliyuncs.com/hetao/mapbox.mov)
```
@implementation BuildingsExample
- (void)viewDidLoad {

    //Insert my code below:
    UITapGestureRecognizer *gesture = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(handleTap:)];
    gesture.numberOfTapsRequired = 1;
    gesture.delegate = self;
    [mapView addGestureRecognizer:gesture];
}

- (void)handleTap:(UITapGestureRecognizer *)gesture {
    
    MGLPointAnnotation *hello = [[MGLPointAnnotation alloc] init];
    hello.coordinate = [mapView convertPoint:[gesture locationInView:self.view] toCoordinateFromView:self.view];
    hello.title = @"Hello world!";
    hello.subtitle = @"Welcome to my marker";
    
    [mapView addAnnotation:hello];
}
```

** Platform:IOS
** Mapbox SDK version:MapboxVersionNumber->11741.000000**

### Steps to trigger behavior

 1. add MGLPointAnnotations  to SDK Examples->BuildingsExample.m (or a simple demo)
 2.pitch map first.
 3.zoom and rotate map around  MGLPointAnnotations.

### Expected behavior
always show MGLPointAnnotation

### Actual behavior
some MGLPointAnnotation disappeared.

**Comment by 1ec5** [comment]
> MapboxVersionNumber->11741.000000

Apparently this is v3.7.5.
