### ISSUE TITLE
Rename $featureProperties to $featureAttributes

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#11739]
The `$featureProperties` expression variable should be renamed `$featureAttributes` to match the `MGLFeature.attributes` property. The iOS/macOS map SDK avoids using the term “property” to refer to things that aren’t represented by class or instance properties in Objective-C or Swift.

If this change doesn’t take place before the iOS map SDK v4.0.0 release, we can support both variable names but prefer `$featureAttributes`. (`$featureProperties` [isn’t documented](https://www.mapbox.com/ios-sdk/api/4.0.0-rc.1/predicates-and-expressions.html), in any case.) The `NSExpression.featurePropertiesVariableExpression` property would ideally be renamed as well; we’d have to leave a deprecated alias in place for it.

/cc @fabian-guerra

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/11748
