### ISSUE TITLE
[iOS] How to disable MapBox logs?

### ISSUE THREAD

**Issue by iDevid** [mapbox/mapbox-gl-native#11732]
**Platform:** iOS
**Mapbox SDK version:** Latest

There is a way to disable Mapbox logging (for http request) ?

**Comment by jfirebaugh** [comment]
Can you give an example of the logging you're referring to?

**Comment by iDevid** [comment]
Task <6EBC2EBC-6540-4DD8-A1EB-A3492AE9D15F>.<42> finished with error - code: -999

**Comment by jfirebaugh** [comment]
Unfortunately, this appears to be an operating system issue and not something we have control over; see https://openradar.appspot.com/36175576.
