### ISSUE TITLE
Raster layer seems to float on small camera moee

### ISSUE THREAD

**Issue by emerciercontexeo** [mapbox/mapbox-gl-native#11737]
**Platform:Android**
**Mapbox SDK version:6.0.1**

A gif is better than a thousand words so : 

Raster layer seems to float above the map.

![ezgif com-crop 1](https://user-images.githubusercontent.com/8739777/39001338-60bad856-43f6-11e8-9954-b3681ce3a22f.gif)

**Comment by jfirebaugh** [comment]
@emerciercontexeo Can you provide a bit more information? What are we looking at here in terms of sources and layers?

**Comment by jfirebaugh** [comment]
This is probably due to https://github.com/mapbox/mapbox-gl-native/pull/10984; discussion in https://github.com/mapbox/mapbox-gl-js/issues/6150.
