### ISSUE TITLE
Programmatically selecting an annotation, with MGLAnnotationView.enabled == NO, should fail.

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#11736]
**Platform:** iOS
**Mapbox SDK version:** ios-v4.0.0-rc.1

Selecting an annotation (using an `MGLAnnotationView` with `enabled` == `NO`) using 
`-[MGLAnnotationView selectAnnotation:animated:]` ignores the enabled property.

Either we should disallow this case, or improve the documentation so that `enabled` refers to user-interaction selection.

**Comment by julianrex** [comment]
See https://github.com/mapbox/mapbox-gl-native/pull/11731/commits/2e2612de07957d1d59fb730d250635ed8962088b for an associated test.

**Comment by 1ec5** [comment]
> improve the documentation so that `enabled` refers to user-interaction selection

For consistency with `MGLAnnotationImage.enabled` and `MKAnnotationView.enabled`, this property should only affect selection by tap, not programmatic selection. In principle, the API shouldn’t expose an option for ignoring another part of the API.

/ref #12064
