### ISSUE TITLE
icon-rotate incorrectly added as both layout and paint property.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1173]
It looks like icon-rotate is incorrectly added as a paint property in style_parser.cpp.  If it is supposed to be a paint property as well, can you please clarify what its intended to do at rendering time? The paint part is NYI.

Also is it safe to use the same PropertyKey for layout and symbol properties (in this case Key::IconRotate)?

**Comment by ansis** [comment]
You're right. It's not a paint property. Removed in https://github.com/mapbox/mapbox-gl-native/commit/65306490dd074a268d4041a98302f54eaf82242f
