### ISSUE TITLE
sparse arrays aren't being handled correctly in Android Expression conversion

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#11749]
When trying to serialize JSON to a jsonArray and use the convert method, if the JSON string has an empty element `, ,`, the Map SDK throws a runtime exception https://github.com/mapbox/mapbox-gl-native/blob/release-boba/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java#L3677 since when I use GSON to serialize, this value becomes a null element. 

cc: @mapbox/maps-android

**Comment by tobrun** [comment]
Can you show a code snippet or example data of what you are trying to convert?

**Comment by cammace** [comment]
Sure, so can actually reproduce this issue in https://github.com/mapbox/mapbox-plugins-android/pull/455, the somewhat modified expression JSON:
```
["step", ["zoom"], 0.0, , 13.0, ["get", "{name_ru}"]]
```

gets converted to:
```
["step",["zoom"],0.0,null,13.0,["get","{name_ru}"]]
```

when I use GSON to convert it back to a JsonArray.

**Comment by jfirebaugh** [comment]
`["step", ["zoom"], 0.0, , 13.0, ["get", "{name_ru}"]]` isn't a valid expression (it's not valid JSON, for one thing). Where did that come from?

**Comment by cammace** [comment]
sorry, the before modifying anything the expressions written like:
```
["step", ["zoom"], 0.0, , 13.0, {name_ru}]
```

which is also not valid JSON, https://github.com/mapbox/mapbox-gl-native/issues/11659 is an issue. To be more specific where this expression is coming from, the default Mapbox Streets style when grabbing the `state-label-lg` layer, converting the expression to an array and then printing it to log using `Arrays.toString()`.

**Comment by 1ec5** [comment]
#11659 is purely about `{token}` syntax embedded in strings in valid JSON, stuff like this:

```json
["step", ["zoom"], 0.0, "", 13.0, "{name_ru}"]
```

What you’re seeing with [`Arrays.toString()`](https://developer.android.com/reference/java/util/Arrays.html#toString%28java.lang.Object[]%29) is probably a lossy string representation that isn’t intended to be valid JSON. (This is reminiscent of what you see in Objective-C when you try to `po` an array in LLDB.) You might get better results with [`Arrays.deepToString()`](https://developer.android.com/reference/java/util/Arrays.html#deepToString%28java.lang.Object[]%29), but the map SDK’s own [`Expression.toString()`](https://www.mapbox.com/android-docs/api/map-sdk/6.0.1/com/mapbox/mapboxsdk/style/expressions/Expression.html#toString--) sounds like it outputs a valid JSON-encoded string.

**Comment by 1ec5** [comment]
OK, if the conversion to a string isn’t at issue, then something along the way is interpreting the empty string as a `null`, which is incorrect.

**Comment by cammace** [comment]
> then something along the way is interpreting the empty string as a null

So you're saying the empty string is valid JSON since it's inside the array? Shouldn't null also be acceptable in this case then as well and be treated the same?

**Comment by 1ec5** [comment]
I don’t think you can validly set `text-field` to `null` in a style JSON file. The empty string is the way that a symbol layer indicates it has no `text-field`. So a stop value of `null` inside a `step` expression would be similarly invalid.

**Comment by cammace** [comment]
Ahhh, I see. In that case issue https://github.com/mapbox/mapbox-gl-native/issues/11158 should resolve this issue. for now, a solution for this I suppose would be writing a custom serializer for empty strings so that GSON doesn't automatically assume the field is null. 

@tobrun do you want to merge this ticket with https://github.com/mapbox/mapbox-gl-native/issues/11158 or leave open to ensure we include a test case for this?

**Comment by tobrun** [comment]
#11158 will solve this use-case and don't see a reason to double track this. Closing.
