### ISSUE TITLE
Crackling audio during heavy rendering

### ISSUE THREAD

**Issue by leelx78** [mapbox/mapbox-gl-native#11744]
Hi I'm using 6.0.1 and during heavy rendering I hear audio crackling heavily (e.g. while playing music on the background). Chipset is RK3368 which is not very recent but still relatively powerful.

I always had this problem, also on 5.x but I'd like to see if there is a solution, for instance

- Can I limit the number of CPUs used for rendering? That would avoid using 100% of the CPU for rendering and would leave some processor for other tasks

For info, if I use the CPU monitor built into the developer tool section I see these issues only when there is a significant BLUE fraction of the bar. RED and GREEN don't seem to affect the audio.

Incidentally, why is the blue bar high in MapBox? I thought it was related to high IO interrupts?

Please let me know

Thanks

PS: I attach an image for the monitor which caused a 2s total lockup of the audio
![device-2018-04-20-000900](https://user-images.githubusercontent.com/28741731/39022793-29d4d128-442f-11e8-97d5-4c9d4108c72a.png)

**Comment by jfirebaugh** [comment]
Hi @leelx78, thanks for using Mapbox. Audo crackling or lockup is going to be outside of the control of Mapbox GL -- that's handled by the operating system.

To lessen the CPU load, you would need to reduce the work that Mapbox GL needs to do, for example by using a simpler style or avoiding animation.

**Comment by leelx78** [comment]
Thanks John, So there isn't any way to control the max number of threads in the renderer? Setting them to CPU-1 might work in preserving some resources
