### ISSUE TITLE
No way of handling failed tile fetch requests

### ISSUE THREAD

**Issue by jontyt** [mapbox/mapbox-gl-native#11747]
**Platform:** iOS
**Mapbox SDK version:** 3.7.3

### Steps to trigger behavior

I am using the MGLOfflineStorage delegate to update tile urls at runtime to point to tiles hosted on a 3rd party server. It would be nice to be able to be notified and to re-request failed file requests similarly to how the MGLOfflinePackError notification works. 

### Expected behavior

Have a delegate or NSNotification system to share the state of tile requests

### Actual behavior

MapBox's internal renderer prints error messages (>400s) to the console with no way of handling these.

**Comment by 1ec5** [comment]
[`-[MGLMapViewDelegate mapViewDidFailLoadingMap:withError:`](https://www.mapbox.com/ios-sdk/api/4.0.0/Protocols/MGLMapViewDelegate.html#/c:objc%28pl%29MGLMapViewDelegate%28im%29mapViewDidFailLoadingMap:withError:) is called when any request fails in the context of loading a map in an MGLMapView.

**Comment by jontyt** [comment]
@iec5 
While that method works well or issues such as network connectivity or failure loading style sheets,   unfortunately it is not triggered for issues loading individual tiles.

**Comment by mrpantsuit** [comment]
This would also be useful to us.  We transform the URL based on the version of the tile data, e.g., http://ourserver/sometile?data_version=1.  When a tile request fails, that's a cue for us to pull the current data version from the server (e.g., http://ourserver/getCurrentDataVersion) and change the URL transformation, e.g., http://ourserver/sometile?data_version=2.

**Comment by 1ec5** [comment]
> While that method works well or issues such as network connectivity or failure loading style sheets, unfortunately it is not triggered for issues loading individual tiles. (iOS SDK, swift)

If I’m reading #2775 correctly, MapKit surfaces this error by passing `NO` into `-[MKMapViewDelegate mapViewDidFinishRenderingMap:fullyRendered:]`. #1804 tracks calling `-[MGLMapViewDelegate mapViewDidFinishRenderingMap:fullyRendered:]` in this situation.

/cc @friedbunny
