### ISSUE TITLE
Are HTTP requests blocking in MapBox?

### ISSUE THREAD

**Issue by leelx78** [mapbox/mapbox-gl-native#11754]
Hi I'm doing some code profiling and I see a few yellow bits in the CPU trace with Android Studio when it is pulling data through the network. 

Is this the IO load that briefly freezes the system (Blue bar, I had another post on this)? When this happens my audio starts to crackle. I still have that problem unfortunately..

![device-2018-04-20-000900](https://user-images.githubusercontent.com/28741731/39086859-8b5ea04c-4590-11e8-995b-0056ab887eb3.png)

Are the HTTP requests blocking the main thread in any way? Sometimes it seems to stutter when zooming in/out and that seems to coincide with large number of network requests.

Any other ideas?

Thanks

**Comment by mb12** [comment]
This is the peer class that does network IO. You can put breakoints in there to verify that HTTP requests are not happening on UI thread.
https://github.com/mapbox/mapbox-gl-native/blob/11d506f8034c02103bc33e06ae8913be7908a877/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java

I would recommend enabling 'Strict Mode' under developer options. It would make the screen flash if the application performs long operation on main thread. It would also log the relevant stack trace under logcat. In the past I've noticed telemetry service doing file I/O on UI thread.  But that might have changed.

**Comment by leelx78** [comment]
Hi 

I did that but nothing is flashing.

 

However, as soon as the “Blue Bar” comes up while rendering the background music starts stuttering, even if at ~50% CPU. 

 

I don’t think this an issue with the audio player. There seem to be *something* happening in the rendering thread that locks up audio?

 

I’m on 5.5.2 now but had the same issue on 6.0.1
