### ISSUE TITLE
Allow symbolic array subscripting in expression

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#11757]
According to [this NSHipster article](http://nshipster.com/nspredicate/), there are three symbolic array subscripts, which the NSExpression to JSON conversion doesn’t recognize:

* [ ] `array[FIRST]` – equivalent to `array[0]`
* [ ] `array[LAST]` – equivalent to `array[count(array) - 1]`
* [ ] `array[SIZE]` – equivalent to `count(array)`

All three syntaxes are actually `objectFrom:withIndex:` function calls, with the last argument being a constant value expression containing a string (`FIRST`, `LAST`, or `SIZE`).

/cc @fabian-guerra

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/11770
