### ISSUE TITLE
Publicly expose NSPredicate-JSON conversion

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#11751]
Just as the iOS and macOS map SDKs expose conversion methods between NSExpression and JSON-like Foundation objects representing style specification expressions, they should also expose conversion methods between NSPredicate and JSON expressions. `+[NSPredicate(MGLExpressionAdditions) mgl_predicateWithJSONObject:]` and `mgl_jsonExpressionObject` have already been implemented, but they’re stuck in the private NSPredicate+MGLAdditions.h header:

https://github.com/mapbox/mapbox-gl-native/blob/991264ae657303e172ba1cdd1aa56eb27b951c92/platform/darwin/src/NSPredicate+MGLAdditions.h#L15-L17

Once #11610 lands, we should move the rest of that header into an MGLPrivateAdditions category inside NSPredicate+MGLPrivateAdditions.h and reserve the MGLAdditions category for just these two public symbols.

Among other things, this will make it possible for React Native Mapbox GL to work with layer filters.

/cc @fabian-guerra @nitaliano @lucaswoj

**Comment by 1ec5** [comment]
`+[NSPredicate(MGLExpressionAdditions) mgl_predicateWithJSONObject:]` should be renamed `+predicateWithMGLJSONObject:`, along the lines of #11612.

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/11810
