### ISSUE TITLE
Still having freezing and audio issues when rendering

### ISSUE THREAD

**Issue by leelx78** [mapbox/mapbox-gl-native#11763]
Hi 
I raised this issues last week about audio crackling when rendering, which correlated with the "mysterious" blue bar in the CPU meter. It was closed soon after as it was "system-side" and "not relevant to MapBox" but I believe this has something to do with how rendering is done in the app.

![device-2018-04-20-000900](https://user-images.githubusercontent.com/28741731/39142689-46a0ff10-4723-11e8-92ae-c8a97f22aa06.png)

I did some checks with and without a RasterLayer and with different combinations of the vector layer but the problem remains. Strange thing is that it happens also when the CPU is not at 100% (maybe just 50%, see below)

![screen shot 2018-04-21 at 18 52 44](https://user-images.githubusercontent.com/28741731/39142948-1ba42598-4724-11e8-885c-441eff2af53a.jpg)

In general I think no application should ever be allowed to freeze the system or crackle the audio so I do believe there are some issues that need to be looked at in the rendering thread.

To start with, can anybody replicate this issue? Example:

- Play some music in the background
- Manually pan a map (e.g vector + raster) around with plenty of zoom to cause a spike in CPU and see the "Blue Bar"
- At this point you should hear audio crackling / stuttering

Pls confirm thanks

(This was with both versions 5.x and 6.x on RK3368 Android)

**Comment by leelx78** [comment]
Is anybody looking into this issue? I need to sort it asap because I need music + map in my application and it's pretty much unusable..

Any help would be very appreciated!

Thanks!

**Comment by tobrun** [comment]
Looked into the issue and wasn't able to reproduce with:

```java
    mapView = (MapView) findViewById(R.id.mapView);
    mapView.onCreate(savedInstanceState);
    MediaPlayer mp = MediaPlayer.create(this, R.raw.test);
    mp.start();
```

This was run on a Galaxy s9, I'm thinking this might be related to the underlying hardware. Happy to look into this more if you can provide a minimal reproducible example.

**Comment by leelx78** [comment]
Thanks @tobrun . Do you have both raster and vector layers enabled? Pls enable the CPU monitor in developer options and keep panning and moving the maps until you see high CPU usage. In particular:

- Do you see the blue bar at any moment?
- Does audio stutter in any way under heavy CPU?

Thanks

**Comment by leelx78** [comment]
Hi @tobrun I tested with 

`MediaPlayer mp = MediaPlayer.create(this, R.raw.test);
    mp.start();`

I can confirm that as soon as the blue bar comes up the audio stutters. This is both with MediaPlayer and ExoPlayer, both local and network playback. I'm on Android 5 (Can't upgrade)

I'm using a vector map based on OSM-BRIGHT GL style. Would be good if you could test with that as well. 

I spent A LOT of time trying with different GL settings. Even if I disable almost all the layers (both in mapView and GL style json) the problem is still there. must be something in the GL renderer?
