### ISSUE TITLE
Expression migration guide incorrectly listed in jazzy table of contents

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#11761]
The “Migrating to Expressions” guide is listed above the “Predicates and Expressions” guide in the jazzy table of contents for iOS. For macOS, the guide is still listed under the working title “Style Layers Using Expressions”, which means the actual guide ends up listed under “Other Guides”.

/ref #11724
/cc @jmkiley

**Comment by jmkiley** [comment]
Fixed with #11808
