### ISSUE TITLE
PropertyFactory.iconAllowOverlap() not working in 6.0.1

### ISSUE THREAD

**Issue by carlol** [mapbox/mapbox-gl-native#11778]
**Platform: Android**
**Mapbox SDK version: 6.0.1**

Hi, I'm porting mapbox from 5.x to 6.0.1 version but I get some strange behavior using iconAllowOverlap property.

The init layer code is:

```
new SymbolLayer(markerLayerId, markerSourceId)
                    .withProperties(
                            PropertyFactory.iconAllowOverlap(true) //
                            , PropertyFactory.iconImage("{" + PoiProperty.ICO_RELATIVE_URL + "}")
                            , PropertyFactory.iconAnchor(Expression.match(Expression.get(PoiProperty.ICO_ANCHOR)
                                    , Expression.literal(Property.ICON_ANCHOR_CENTER),  MapStops.ICON_ANCHOR_STOPS))
                    );
```

### Expected behavior
All marker are visible of this layer are visible

### Actual behavior
iconAllowOverlap seams to be ignored and only few markers are visible at time, when I zoom in more markers appear on the screen.

Note:
if I try to use:

`PropertyFactory.iconAllowOverlap(Expression.literal(true))`

the application crashes with this jni exception:

"abort_message: assertion "terminating with uncaught exception of type jni::PendingJavaException" failed"

Best regards

**Comment by LukasPaczos** [comment]
Thanks for reaching out @carlol.
I wasn't able to reproduce the issue, icons are overlapping just fine for me. Could you verify whether the issue persists without the `iconAnchor` property?
Also, you can use `Expression.get()` instead of deprecated tokens, for ex.
```
PropertyFactory.iconImage(Expression.get(PoiProperty.ICO_RELATIVE_URL))
```
Regarding the expression crash - following up in https://github.com/mapbox/mapbox-gl-native/issues/11790.

**Comment by tobrun** [comment]
@carlol have you tried using the [icon-ignore-placement](https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-icon-ignore-placement) property?

**Comment by LukasPaczos** [comment]
Stale, closing. Let us know if it's still an issue for you.

**Comment by mdakram** [comment]
Trying with v6.3.0

iconImage(string(get(literal("icon")))),
                        iconAllowOverlap(true),
                        textAllowOverlap(true),

this should allow overlapping symbols but seems its not working
