### ISSUE TITLE
SymbolLayer vs. map style

### ISSUE THREAD

**Issue by cleemansen** [mapbox/mapbox-gl-native#11773]
**Platform:** Android
**Mapbox SDK version:** 6.0.1

### Steps to trigger behavior

 1. Setup a `MapView` w/ a clustered geo-json source (like the `GeoJsonClusteringActivity` example from the mapbox-android-demo-app)
 2. Switch the map style url via `mapboxMap.setStyleUrl()`

### Expected behavior

I expected that the cluster layer and all other layers will survive the map style switch.

### Actual behavior

The cluster layer is not visible any more! 

If that is the expected behavior, what is the best way to add all previous layers again (w/o running into a `com.mapbox.mapboxsdk.style.sources.CannotAddSourceException: Source XX already exists` exception)?

I have adjusted your demo-app (`GeoJsonClusteringActivity`) w/ a map type switcher (FAB).

![symbol_layer_vs_map_style](https://user-images.githubusercontent.com/868171/39248031-54e97c22-489b-11e8-945d-6099e68fbefc.gif)

Adjusted sample app: https://github.com/cleemansen/mapbox-android-demo/blob/debug%2Fsymbol_layer_vs_map_style/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/GeoJsonClusteringActivity.java

**Comment by tobrun** [comment]
Sources and layers are a part of a style. If you change the style, you need toreadd the sources and layers. An example of this can be found [here](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-traffic/src/main/java/com/mapbox/mapboxsdk/plugins/traffic/TrafficPlugin.java#L118).

**Comment by cleemansen** [comment]
Thanks a lot! :)
