### ISSUE TITLE
mapView.onDestroy takes 3 secs in activity

### ISSUE THREAD

**Issue by samoilovich** [mapbox/mapbox-gl-native#11781]
Hello.

I have activity A which has list with items. Click on a item start new activity B which contains mapView.
When user click 'Back' button activity B just is finished and user see activity A again. 
But if user try to click again on items of activity A he can have delayed in reacting of screen cause actviity B is still finishing. And a reason of this long finishing is mapView.onDestroy() which can takes 3 secs. :(
Only activities - no fragments.
On activity B i draw some polygobns and polylines. 

May be need to remove this objects to impove time of finishing or something else.
Could you help with this problem?

mapbox sdk: com.mapbox.mapboxsdk:mapbox-android-sdk:5.5.0
android 7.0 Sumsung Galaxy 7 edge

Thanks.

**Comment by mrfaa** [comment]
Did you override all life cycle methods?

onCreate();
onStart();
onResume();
onPause();
onStop();
onSaveInstanceState();
onLowMemory();
onDestroy();

https://www.mapbox.com/android-docs/map-sdk/overview/

**Comment by samoilovich** [comment]
After updating to version `com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.1`
it started working ok. I think that issue is resolved.

Thanks.
