### ISSUE TITLE
[Android] Question: InfoWindow for Features?

### ISSUE THREAD

**Issue by rm3dbeckers** [mapbox/mapbox-gl-native#11791]
**Platform: Android**
**Mapbox SDK version: 6.0.1**

Is it possible to show an InfoWindow (or a bubble) for a clicked feature (for example a LineString)?
Or is it possible to get the closest point of/on a feature to a given tap location (so we can add the bubble ourselves)?

**Comment by LukasPaczos** [comment]
There is a post about the `SymbolLayer` API that presents how to create a bubble-like layout available on [our blog](https://blog.mapbox.com/a-guide-to-the-android-symbollayer-api-5daac7b66f2c). I hope it helps!

**Comment by rm3dbeckers** [comment]
Alright thanks, it really does.
I am still having the problem that I have to find out where I should add that Symbol (if I want it to appear on the LineString closest to the clicked location), but since I do know which feature was clicked, where the click location took place and I do have the feature's geometry, I can calculate that myself.
Thank you very much.
