### ISSUE TITLE
SymbolLayer icon example with interpolate expression

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#11799]
Refs. https://github.com/mapbox/mapbox-gl-native/issues/9975#issuecomment-384960990.
It looks like `string` is not interpolatable which results in `Error setting property: icon-image Type string is not interpolatable.` when trying to set `icon-image` with `interpolate` expression, as in [one of our examples](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/ZoomFunctionSymbolLayerActivity.java#L105-L111).

**Comment by anandthakker** [comment]
This should probably be a [`step`](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-step) operator
