### ISSUE TITLE
Set DEFINES_MODULE in podspec for downstream Swift libraries

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#11794]
According to [this blog post](http://blog.cocoapods.org/CocoaPods-1.5.0/), the iOS map SDK’s CocoaPods podspecs would need to set the `DEFINES_MODULE` build setting inside a [`pod_target_xcconfig`](https://guides.cocoapods.org/syntax/podspec.html#pod_target_xcconfig) directive in order for a Podfile, in order for the iOS navigation SDK to be installed as a static Swift library. (For consistency, the same directive would go in the macOS map SDK’s podspecs.)

/cc @friedbunny @frederoni @rclee

**Comment by friedbunny** [comment]
It looks like updating our podspec isn’t make-or-break for this:

> In this release, you will be able to opt into stricter header search paths (and module map generation for Objective-C pods). As a pod author, you can add `'DEFINES_MODULE' => 'YES'` to your pod_target_xcconfig. Alternatively, in your Podfile you can add `use_modular_headers!` to enable the stricter search paths and module map generation for all of your pods, or you can add `:modular_headers => true` to a single pod declaration to enable for only that pod.

... so the people/projects who need this downstream should be able to force our pod into compliance. Until we can validate that this change doesn’t break anything else, that seems like a reasonable workaround.

**Comment by Coeur** [comment]
@friedbunny As it's only making build search paths stricter, you'll directly see when doing `pod update` if it builds or not. If it still builds, then nothing is broken.

On top of that, setting it at the podspec level is going to do EXACTLY THE SAME as adding `modular_headers => true`, so the workaround is going to work either flawlessly for everybody, or for nobody. So it's best to have it at podspec level directly.
