### ISSUE TITLE
[Linux] Build failing in uv.h dependency on Ubuntu 14.04 with g++-5.5

### ISSUE THREAD

**Issue by JamesWilmot** [mapbox/mapbox-gl-native#11793]
Attempting to build mapbox-gl-native on Linux

### Steps to trigger behavior

 1. RTFM: https://github.com/mapbox/mapbox-gl-native/tree/master/platform/linux
 2. Building and installing a version of cmake which isn't extremely old: https://www.claudiokuenzler.com/blog/611/installing-cmake-3.4.1-ubuntu-14.04-trusty-using-alternatives
 3. `make distclean`
 4. `make glfw-app`

### Terminal dump

> mkdir -p build/linux-x86_64/Debug
> (cd build/linux-x86_64/Debug && cmake -G Ninja ../../.. \
> 		-DCMAKE_BUILD_TYPE=Debug \
> 		-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
> 		-DWITH_CXX11ABI=OFF \
> 		-DWITH_COVERAGE= \
> 		-DWITH_OSMESA= \
> 		-DWITH_EGL=)
> -- The CXX compiler identification is GNU 5.5.0
> -- The C compiler identification is GNU 4.8.4
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Updating submodules...
> ln: failed to create symbolic link ‘./node_modules’: File exists
> -- Running 'npm install' for mapbox-gl-native...
> 
> /usr/lib/node_modules/npm/lib/config/cmd-list.js:113
> module.exports.aliases = Object.assign({}, shorthands, affordances)
>                                 ^
> TypeError: Object function Object() { [native code] } has no method 'assign'
>     at Object.<anonymous> (/usr/lib/node_modules/npm/lib/config/cmd-list.js:113:33)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at /usr/lib/node_modules/npm/lib/npm.js:36:17
>     at Object.<anonymous> (/usr/lib/node_modules/npm/lib/npm.js:470:3)
>     at Module._compile (module.js:456:26)
> -- Running 'npm install' for mapbox-gl-js...
> 
> /usr/lib/node_modules/npm/lib/config/cmd-list.js:113
> module.exports.aliases = Object.assign({}, shorthands, affordances)
>                                 ^
> TypeError: Object function Object() { [native code] } has no method 'assign'
>     at Object.<anonymous> (/usr/lib/node_modules/npm/lib/config/cmd-list.js:113:33)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at /usr/lib/node_modules/npm/lib/npm.js:36:17
>     at Object.<anonymous> (/usr/lib/node_modules/npm/lib/npm.js:470:3)
>     at Module._compile (module.js:456:26)
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/geometry/0.9.2.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/geometry/0.9.2...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/variant/1.1.4.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/variant/1.1.4...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/unique_resource/cba309e.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/unique_resource/cba309e...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/rapidjson/1.1.0.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/rapidjson/1.1.0...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/boost/1.65.1.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/boost/1.65.1...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/geojsonvt/6.3.0.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/geojsonvt/6.3.0...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/supercluster/0.2.2.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/supercluster/0.2.2...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/kdbush/0.1.1-1.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/kdbush/0.1.1-1...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/earcut/0.12.4.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/earcut/0.12.4...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/protozero/1.5.2.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/protozero/1.5.2...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/pixelmatch/0.10.0.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/pixelmatch/0.10.0...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/geojson/0.4.2.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/geojson/0.4.2...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/polylabel/1.0.3.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/polylabel/1.0.3...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/wagyu/0.4.3.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/wagyu/0.4.3...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/shelf-pack/2.1.1.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/shelf-pack/2.1.1...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/cheap-ruler/2.5.3.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/cheap-ruler/2.5.3...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/vector-tile/1.0.1.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/vector-tile/1.0.1...
> -- Can't find ccache — consider installing ccache to improve recompilation performance
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/linux-x86_64/glfw/2017-07-13-67c9155.tar.gz...
> [Mason] Unpacking package to mason_packages/linux-x86_64/glfw/2017-07-13-67c9155...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/linux-x86_64/mesa/13.0.4.tar.gz...
> [Mason] Unpacking package to mason_packages/linux-x86_64/mesa/13.0.4...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/linux-x86_64/sqlite/3.14.2.tar.gz...
> [Mason] Unpacking package to mason_packages/linux-x86_64/sqlite/3.14.2...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/linux-x86_64/libuv/1.9.1.tar.gz...
> [Mason] Unpacking package to mason_packages/linux-x86_64/libuv/1.9.1...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/linux-x86_64/nunicode/1.7.1.tar.gz...
> [Mason] Unpacking package to mason_packages/linux-x86_64/nunicode/1.7.1...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/linux-x86_64/libpng/1.6.25.tar.gz...
> [Mason] Unpacking package to mason_packages/linux-x86_64/libpng/1.6.25...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/linux-x86_64/libjpeg-turbo/1.5.0.tar.gz...
> [Mason] Unpacking package to mason_packages/linux-x86_64/libjpeg-turbo/1.5.0...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/linux-x86_64/webp/0.5.1.tar.gz...
> [Mason] Unpacking package to mason_packages/linux-x86_64/webp/0.5.1...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/linux-x86_64/gtest/1.8.0.tar.gz...
> [Mason] Unpacking package to mason_packages/linux-x86_64/gtest/1.8.0...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/linux-x86_64/benchmark/1.2.0.tar.gz...
> [Mason] Unpacking package to mason_packages/linux-x86_64/benchmark/1.2.0...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/linux-x86_64/icu/58.1-min-size.tar.gz...
> [Mason] Unpacking package to mason_packages/linux-x86_64/icu/58.1-min-size...
> [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/args/6.2.0.tar.gz...
> [Mason] Unpacking package to mason_packages/headers/args/6.2.0...
> -- Downloading: https://nodejs.org/download/release/v0.10.46/SHASUMS256.txt
> -- NodeJS: Using node, version v0.10.46
> -- Downloading: https://nodejs.org/download/release/v0.10.46/node-v0.10.46-headers.tar.gz
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/james/vendor/mapbox-gl-native/build/linux-x86_64/Debug
> platform/linux/ninja  -j4 -C build/linux-x86_64/Debug mbgl-glfw
> ninja: Entering directory `build/linux-x86_64/Debug'
> [2/318] Building CXX object CMakeFiles/mbgl-loop-uv.dir/platform/default/async_task.cpp.o
> FAILED: CMakeFiles/mbgl-loop-uv.dir/platform/default/async_task.cpp.o 
> /usr/bin/c++  -DRAPIDJSON_HAS_STDSTRING=1 -D_GLIBCXX_USE_CXX11_ABI=0 -I../../../include -I../../../src -Inode/v0.10.46/include -I../../../mason_packages/headers/geometry/0.9.2/include -I../../../mason_packages/headers/variant/1.1.4/include -I../../../mason_packages/linux-x86_64/mesa/13.0.4/include -I../../../mason_packages/linux-x86_64/nunicode/1.7.1/include -I../../../mason_packages/linux-x86_64/libpng/1.6.25/include/libpng16 -I../../../mason_packages/linux-x86_64/libjpeg-turbo/1.5.0/include -I../../../mason_packages/linux-x86_64/webp/0.5.1/include -std=c++14 -ftemplate-depth=1024 -fPIC -fvisibility=hidden -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wno-variadic-macros -Wno-unknown-pragmas -Werror -fext-numeric-literals -g   -std=gnu++14 -MD -MT CMakeFiles/mbgl-loop-uv.dir/platform/default/async_task.cpp.o -MF CMakeFiles/mbgl-loop-uv.dir/platform/default/async_task.cpp.o.d -o CMakeFiles/mbgl-loop-uv.dir/platform/default/async_task.cpp.o -c ../../../platform/default/async_task.cpp
> ../../../platform/default/async_task.cpp: In constructor ‘mbgl::util::AsyncTask::Impl::Impl(std::function<void()>&&)’:
> ../../../platform/default/async_task.cpp:20:53: error: invalid conversion from ‘void (*)(uv_async_t*) {aka void (*)(uv_async_s*)}’ to ‘uv_async_cb {aka void (*)(uv_async_s*, int)}’ [-fpermissive]
>          if (uv_async_init(loop, async, asyncCallback) != 0) {
>                                                      ^
> In file included from ../../../platform/default/async_task.cpp:8:0:
> node/v0.10.46/include/uv.h:1211:15: note:   initializing argument 3 of ‘int uv_async_init(uv_loop_t*, uv_async_t*, uv_async_cb)’
>  UV_EXTERN int uv_async_init(uv_loop_t*, uv_async_t* async,
>                ^
> [3/318] Building CXX object CMakeFiles/mbgl-loop-uv.dir/platform/default/run_loop.cpp.o
> FAILED: CMakeFiles/mbgl-loop-uv.dir/platform/default/run_loop.cpp.o 
> /usr/bin/c++  -DRAPIDJSON_HAS_STDSTRING=1 -D_GLIBCXX_USE_CXX11_ABI=0 -I../../../include -I../../../src -Inode/v0.10.46/include -I../../../mason_packages/headers/geometry/0.9.2/include -I../../../mason_packages/headers/variant/1.1.4/include -I../../../mason_packages/linux-x86_64/mesa/13.0.4/include -I../../../mason_packages/linux-x86_64/nunicode/1.7.1/include -I../../../mason_packages/linux-x86_64/libpng/1.6.25/include/libpng16 -I../../../mason_packages/linux-x86_64/libjpeg-turbo/1.5.0/include -I../../../mason_packages/linux-x86_64/webp/0.5.1/include -std=c++14 -ftemplate-depth=1024 -fPIC -fvisibility=hidden -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wno-variadic-macros -Wno-unknown-pragmas -Werror -fext-numeric-literals -g   -std=gnu++14 -MD -MT CMakeFiles/mbgl-loop-uv.dir/platform/default/run_loop.cpp.o -MF CMakeFiles/mbgl-loop-uv.dir/platform/default/run_loop.cpp.o.d -o CMakeFiles/mbgl-loop-uv.dir/platform/default/run_loop.cpp.o -c ../../../platform/default/run_loop.cpp
> ../../../platform/default/run_loop.cpp: In constructor ‘mbgl::util::RunLoop::RunLoop(mbgl::util::RunLoop::Type)’:
> ../../../platform/default/run_loop.cpp:83:36: error: ‘uv_loop_init’ was not declared in this scope
>          if (uv_loop_init(impl->loop) != 0) {
>                                     ^
> ../../../platform/default/run_loop.cpp:94:62: error: invalid conversion from ‘void (*)(uv_async_t*) {aka void (*)(uv_async_s*)}’ to ‘uv_async_cb {aka void (*)(uv_async_s*, int)}’ [-fpermissive]
>      if (uv_async_init(impl->loop, impl->holder, dummyCallback) != 0) {
>                                                               ^
> In file included from ../../../platform/default/run_loop.cpp:6:0:
> node/v0.10.46/include/uv.h:1211:15: note:   initializing argument 3 of ‘int uv_async_init(uv_loop_t*, uv_async_t*, uv_async_cb)’
>  UV_EXTERN int uv_async_init(uv_loop_t*, uv_async_t* async,
>                ^
> ../../../platform/default/run_loop.cpp: In destructor ‘virtual mbgl::util::RunLoop::~RunLoop()’:
> ../../../platform/default/run_loop.cpp:122:33: error: ‘uv_loop_close’ was not declared in this scope
>      if (uv_loop_close(impl->loop) == UV_EBUSY) {
>                                  ^
> [5/318] Building CXX object CMakeFiles/mbgl-core.dir/src/mbgl/programs/collision_box_program.cpp.o
> ninja: build stopped: subcommand failed.
> make: *** [glfw-app] Error 1

### Expected behavior

Make to return zero (hopefully.)

### Build environment

`g++ --version`:

> g++ (Ubuntu 5.5.0-12ubuntu1~14.04) 5.5.0 20171010
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

`cmake --version`:

> cmake version 3.10.1
> 
> CMake suite maintained and supported by Kitware (kitware.com/cmake).

`lsb_release -a`:

> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 14.04.5 LTS
> Release:	14.04
> Codename:	trusty

`uname -a`:

> Linux wowbagger 3.13.0-144-generic #193-Ubuntu SMP Thu Mar 15 17:03:53 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jfirebaugh** [comment]
Thanks for the report. I've opened:

* #11796 to clarify that Node 4+ is a prerequisite on linux.
* #11797 to fix the fact that `make glfw-app` was trying to use node includes when it shouldn't.

**Comment by JamesWilmot** [comment]
Thanks!

Just FYI:

`node --version`:

> v8.4.0

**Comment by JamesWilmot** [comment]
The fix in https://github.com/mapbox/mapbox-gl-native/pull/11797 solves my issue.
