### ISSUE TITLE
Cannot set zoom immediately after setting center coordinate

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1181]
The following code takes you to the lovely town of Emerald, Victoria, Australia:

```objc
self.mapView.zoomLevel = 15;
[self.mapView setCenterCoordinate:CLLocationCoordinate2DMake(-23.526029999999999, 148.16224)];
```

![vic](https://cloud.githubusercontent.com/assets/1231218/6968788/3978b16e-d91e-11e4-9dba-1d2c2d28de3b.png)

But reverse the two calls and you wind up off the coast of Papua New Guinea:

```obc
[self.mapView setCenterCoordinate:CLLocationCoordinate2DMake(-23.526029999999999, 148.16224)];
self.mapView.zoomLevel = 15;
```

![png](https://cloud.githubusercontent.com/assets/1231218/6968792/3d8289f6-d91e-11e4-9415-6084003b92b2.png)

`-[MGLMapView setCenterCoordinate:zoomLevel:animated:]` works fine of course, but I need something less atomic to make #929 work well. Otherwise you have to ensure that `zoomLevel` appears before `latitude` or `longitude` in the storyboard XML. (Interface Builder doesn’t let you rearrange user-defined runtime attributes using the inspector.)

**Comment by incanus** [comment]
Yep, we had this problem in the iOS SDK and I've been seeing it in testing.

**Comment by friedbunny** [comment]
(Your description is clear, but the code example isn't actually reversed.)

**Comment by 1ec5** [comment]
Nice catch, @friedbunny! Fixed.
