### ISSUE TITLE
Distinguish background layer and unloaded tile visually

### ISSUE THREAD

**Issue by always-beta** [mapbox/mapbox-gl-native#11814]
<img width="282" alt="77f2eba3-f21e-476e-9e8f-f771e7aa3c72" src="https://user-images.githubusercontent.com/1987864/39514515-f96e29ee-4e29-11e8-95da-6d0888cdb7b5.png">

From the screenshot, right part of the red vertical line has no tiles (or not loaded yet), and left part has loaded tile, but the data in that tile doesn't cover the whole area. 
What I want to do is to fill only the right part using some color or pattern but not fill the empty areas in the left part.

I set the background layer's pattern to an image of plane, but it will cover the whole planet no matter whether tiles are loaded or not.

Is there any api or workaround to achieve this?

**Comment by jfirebaugh** [comment]
#119 tracks this feature.

As a workaround, you could ensure that each tile is completely covered by a square base layer, and style that differently than the background layer.
