### ISSUE TITLE
iOS: Heading from delegate method is always 0

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#1182]
In my implementation of the delegate method:

 `- (void)mapView:(MGLMapView *)mapView didUpdateUserLocation:(MGLUserLocation *)userLocation`

`userLocation.heading.trueHeading` is always `0.00000` no matter which direction the phone is moving.

**Comment by incanus** [comment]
Weird, the code looks hooked up. Will confirm.

**Comment by picciano** [comment]
Could be related to #1183. When using MGLUserTrackingModeFollowWithHeading, the tracking mode is getting reset.

**Comment by friedbunny** [comment]
As long as `MGLUserTrackingModeFollowWithHeading` is enabled (which, as you said, is not entirely reliable yet) I see all the expected heading information in the delegate method:

```objc
2015-04-04 10:00:14.507 Mapbox GL[4682:659602] (null)
2015-04-04 10:00:15.833 Mapbox GL[4682:659602] MGLUserTrackingModeFollow enabled
2015-04-04 10:00:15.835 Mapbox GL[4682:659602] didChangeUserTrackingMode: 1
2015-04-04 10:00:16.030 Mapbox GL[4682:659602] (null)
...
2015-04-04 10:00:22.379 Mapbox GL[4682:659602] MGLUserTrackingModeFollowWithHeading enabled
2015-04-04 10:00:22.381 Mapbox GL[4682:659602] didChangeUserTrackingMode: 2
2015-04-04 10:00:23.469 Mapbox GL[4682:659602] magneticHeading 162.20 trueHeading 176.02 accuracy 25.00 x -5.243 y -17.409 z -44.955 @ 2015-04-04 17:00:23 +0000
```

**Comment by picciano** [comment]
Yes, this was definitely being caused by MGLUserTrackingModeFollowWithHeading being reset inadvertently.

**Comment by incanus** [comment]
Just to confirm @picciano, _you_ were resetting it, or GL was inadvertently, and if the latter, is that bug captured?

**Comment by picciano** [comment]
I was calling `setDirection:` on the map view, and that was turning off user tracking as a side effect. I guess the question would be if calling `setDirection:` **should** reset user tracking to `MGLUserTrackingModeNone` or not.

**Comment by incanus** [comment]
I think that it should. Apple doesn't have such an API (programmatic control of the heading; they use the `MKMapCamera` API instead) but this would fall in line with other programatic viewport changes. You could always reapply the tracking mode in your use case.

**Comment by picciano** [comment]
Makes sense. In this case I was trying to do too much by setting the map direction to the user heading, rather than just letting the map view do that.
