### ISSUE TITLE
Load Offline Map from Internal Storage

### ISSUE THREAD

**Issue by dsuresh-ap** [mapbox/mapbox-gl-native#11824]
**Platform:Android, iOS**

Is it possible to download a MapBox map externally (on a server) and on the mobile client load it from an SD card? We have a situation where clients would be able to connect to a server (hotspot) remotely away from internet access.

The flow would look like this:
1. Server downloads the map needed. (If possible where could we download it from)
2. Client (Android, iOS) asks server for map and downloads the file off server.
3. Client loads downloaded map into MapBox.

**Comment by fabian-guerra** [comment]
Hi, @dsuresh-ap. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
