### ISSUE TITLE
[node] clipped symbols on vectortile borders

### ISSUE THREAD

**Issue by prozessor13** [mapbox/mapbox-gl-native#11838]
**Platform:** Linux, Node v6.11.5
**Mapbox SDK version:** @mapbox/mapbox-gl-native@3.5.8

### Steps to trigger behavior

 1. Extract the Zip Archive [mapboxGLtest.zip](https://github.com/mapbox/mapbox-gl-native/files/1974724/mapboxGLtest.zip)
 2. Run `npm install`
 3. Run `node test.js`

### Expected behavior

On serverside rendered maps, the symbols should placed correctly over vectortile borders, given the sufficient `buffer_size` of 256.

### Actual behavior

![39632271-e351c814-4fb4-11e8-82da-16d8b24c77b0](https://user-images.githubusercontent.com/45103/39828722-57c056f6-53bc-11e8-9876-52288ef35a9f.png)

Labels are clipped on vectortile-borders. One example is the feature with id `18386548590` and  name `Parc Arheologic`.  The attached vectortiles are created with tilelive and a `buffer_size` of 256.

Thanks for any help!

**Comment by muesliq** [comment]
I've seen this or a similar problems in many situations, also in Mapbox repos. Wondering why nobody here chimes in?

**Comment by lincomatic** [comment]
I've seen this in my own apps, and in other 3rd party apps that use Mapbox, such as Strava. It's particularly common in Strava

**Comment by lincomatic** [comment]
> @lincomatic Do you have screenshots from Strava's map showing the problem?

It happens fairly regularly, but I'm having trouble digging one up right now. Will post one next time I see it on Strava

**Comment by lincomatic** [comment]
Strava map sample. Notice the place names in the center of the map are cut off at the tile border:

![fullsizerender](https://user-images.githubusercontent.com/1422186/42470442-4f20340c-836f-11e8-912e-37d704f235e3.jpg)

**Comment by muesliq** [comment]
@jfirebaugh This hasn't been classified as a bug yet. Or are we missing something and this has been fixed in the master branch since the last Node release? Any pointers would be greatly appreciated.

**Comment by jfirebaugh** [comment]
Sure, applied tags. I do believe there have been quite a few changes to symbol rendering since 3.5.8. Have you tried any of the 4.0.0 prereleases?

**Comment by muesliq** [comment]
Not yet (as 4.0 was released after this bug report), will do!
