### ISSUE TITLE
valueForKeyPath seems to produce a nil value

### ISSUE THREAD

**Issue by jmkiley** [mapbox/mapbox-gl-native#11830]
**Platform:** iOS
**Mapbox SDK version:** v4.0.0

The format string `"valueForKeyPath:"` seems to resolve to a nil value. When I use it to set a circle layer's color property, the layer appears black.

```swift
let stops = [
            "earthquake": UIColor.orange,
            "explosion": UIColor.red,
            "quarry blast": UIColor.yellow
        ]
        
        let layer = MGLCircleStyleLayer(identifier: "circles", source: source)
        layer.circleColor = NSExpression(format: "FUNCTION(%@, 'valueForKeyPath:', type)", stops)
        mapView.style?.addLayer(layer)
```
This behavior continues when a ternary function is used to check for a nil value.
```swift
layer.circleColor = NSExpression(format: "TERNARY(FUNCTION(%@, 'valueForKeyPath:', type) != nil, FUNCTION(%@, 'valueForKeyPath:', type), %@)", stops, stops, UIColor.blue)
```
[Code that reproduces the issue]:(https://gist.github.com/jmkiley/f7c9d664d19e0ee5af37a9b1f00fa90a)

cc @1ec5 @captainbarbosa

**Comment by jmkiley** [comment]
This seems to occur when the attribute has a value that is not included in the stops dictionary. The above layer renders as black because some features have a value of "ice quakes" for `type`.

**Comment by jmkiley** [comment]
Noting that this also the layer is also black if I use a predicate to try to filter out values not accounted for:

```swift
layer.predicate = NSPredicate(format: "type IN { 'earthquake', 'explosion', 'quarry blast', 'volcanic eruption', 'ice quake' }")
```

**Comment by ThiyagarajanShivSankaran** [comment]
@jmkiley We are also facing the same issue. Please, fix this as soon as possible.

**Comment by 1ec5** [comment]
The expression’s `mgl_jsonExpressionObject` is:

```json
["get",["get","type"],["literal",{"explosion":["rgb",255,0,0],"earthquake":["rgb",255,127.5,0],"quarry blast":["rgb",255,255,0]}]]
```

The problem is that the style specification only allows a [`get`](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-get) expression’s first argument to be a literal string, not an expression.

/cc @anandthakker

**Comment by jfirebaugh** [comment]
> The problem is that the style specification only allows a get expression’s first argument to be a literal string, not an expression.

No, expressions are permitted there. The problem is that "literal" expressions are entirely literal. Keys in the object `["rgb",255,0,0]` are not evaluated, so the result of this expression is a heterogeneous four element array, not a color.

**Comment by ThiyagarajanShivSankaran** [comment]
We tried the example code in our app, but the app is crashing, 

Console log,  

> 2018-07-04 17:42:06.292261+0530 OurApp[5101:1919118] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unrecognized expression function MGL_MATCH:.'
> *** First throw call stack:
> (0x18111ed8c 0x1802d85ec 0x18111ec6c 0x1094d1538 0x1093ef3c8 0x1093ef1ec 0x104989af8 0x104468f60 0x10a49d260 0x10a49d220 0x10a4a1db0 0x1810c7070 0x1810c4bc8 0x180fe4da8 0x182fc7020 0x18afc578c 0x104a70510 0x180a75fc0)
> libc++abi.dylib: terminating with uncaught exception of type NSException

Code, 
 ```
let arguments = [NSExpression(forKeyPath: attributeName)] + stops.flatMap {[$0.0, $0.1] } + [UIColor.red]         
 layer.circleColor = NSExpression(forFunction: "MGL_MATCH:", arguments: arguments)      
 layer.circleStrokeColor = NSExpression(forFunction: "MGL_MATCH:", arguments: arguments)
```

**Mapbox SDK version:** v4.1.1

**Comment by 1ec5** [comment]
My bad, that should be `MGL_MATCH`, without the colon. (There’s an alternative syntax `mgl_match:`, with a colon and a different argument order.)

**Comment by 1ec5** [comment]
Great to hear it!

> The problem is that "literal" expressions are entirely literal. Values in the object, such as `["rgb",255,0,0]`, are not evaluated, so the result of this expression is a heterogeneous four element array, not a color.

This problem is being tracked in mapbox/mapbox-gl-js#6155, also for expressions within arrays.
