### ISSUE TITLE
Is it possible to parse a Polyline String with Mapbox?

### ISSUE THREAD

**Issue by flashspys** [mapbox/mapbox-gl-native#11833]
Hey, 
the Mapbox Directions API returns among other things a [Polyline String](https://developers.google.com/maps/documentation/utilities/polylinealgorithm). Is there a possibility to draw this polyline on a Mapbox MapView with the iOS SDK?

**Comment by fabian-guerra** [comment]
Hi, @flashspys. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/) or check our [documentation](https://www.mapbox.com/ios-sdk/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
