### ISSUE TITLE
QueryRenderedFeatures should include `source` and `sourceLayer` 

### ISSUE THREAD

**Issue by asheemmamoowala** [mapbox/mapbox-gl-native#11846]
In  [#6263(gl-js)](https://github.com/mapbox/mapbox-gl-js/pull/6263), `Map#queryRenderedFeatures` was updated to include the `source`, `sourceLayer`, and `state` properties on each feature in the results.

`Renderer::queryRenderedFeatures()` should be updated to include these properties in its results.

**Comment by 1ec5** [comment]
Currently, the native implementation’s feature querying results are plain features that also lack the style layer ID and evaluated layer properties: #7162.
