### ISSUE TITLE
[Android] - properties field in Feature.fromGeometry static factory methods should be @Nullable

### ISSUE THREAD

**Issue by ychescale9** [mapbox/mapbox-gl-native#11850]
**Platform: Android**
**Mapbox SDK version: 6.0.1**

### Steps to trigger behavior

Static factory methods `Feature.fromGeometry(... @NonNull JsonObject properties, ...) should use `@Nullable` for `JsonObject properties` fields.

**Comment by tobrun** [comment]
Thank you for reaching out, the correct location to provide feedback on above API is in https://github.com/mapbox/mapbox-java/. I copied over your issue to [here](https://github.com/mapbox/mapbox-java/issues/813). Closing as this will be handled upstream.
