### ISSUE TITLE
telemetry can not be resolved.

### ISSUE THREAD

**Issue by BravoJason** [mapbox/mapbox-gl-native#11871]
Platform: Android Studio
Mapbox SDK version: mapbox-android-sdk:6.1.1

### Steps to trigger behavior

 1. I followed the tutorial from official website to create a navigation app.(Tutorial link: https://www.mapbox.com/help/android-navigation-sdk/)
 2. When I change the SDK version from 5.2.+ to 6.1.1 and compile the code, it tells me that "error: package com.mapbox.services.android.telemetry.location does not exist".

<img width="1438" alt="screen shot 2018-05-09 at 12 11 27 pm" src="https://user-images.githubusercontent.com/14823865/39826398-8a17e978-5382-11e8-9838-fbca12323472.png">

### Expected behavior
Compile everything.
### Actual behavior
 Can not find the telemetry package.

I tried Invalidate Caches / Restart, but it doesn't work.

I will upload the MainActivity code and module build.gradle as attachment.
It may help you to locate the problem.

Thanks for your time.

### Upload file
[MainActivity.txt](https://github.com/mapbox/mapbox-gl-native/files/1988585/MainActivity.txt)
[build.txt](https://github.com/mapbox/mapbox-gl-native/files/1988595/build.txt)

**Comment by LukasPaczos** [comment]
Thanks for reaching out @BravoJason. Unfortunately, the `v6.1.1` of the Maps SDK for Android and `v0.12.0` of the Navigation SDK are incompatible and we need to update our docs. Thanks for pointing this out!

Instead, remove the explicit Maps SDK dependency and use only the newest, `v0.13.0` of the Navigation SDK (which brings Maps SDK dependency with it). Remove all those invalid imports as well, and reimport what's necessary, as the packages has changed recently, hence the errors.

For more info see the 5.x to 6.x [migration guide](https://github.com/mapbox/mapbox-gl-native/wiki/Android-5.x-to-6.x-migration-guide) and 0.13.0 navigation [release notes](https://github.com/mapbox/mapbox-navigation-android/releases).
