### ISSUE TITLE
[ios, macos] Nested attributes does not get parsed according to the expressions spec.

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/mapbox-gl-native#11874]
Given the following JSON:
```
"properties":{
            "lineStyle":{
                "color":"#00ffff",
            },
}    
```
Trying to access the `lineColor` attribute using the following expression 
`[NSExpression expressionForKeyPath:@"lineStyle.color"]` should parse into 
`@[@"get", @"color", @[@"get", @"lineStyle"]]` but gets parsed as `@[@"get", @"lineStyle.color"]` instead.

/cc @anandthakker @jmkiley @1ec5

**Comment by 1ec5** [comment]
It looks like we don’t handle the `valueForKeyPath:` function’s argument like a key path:

https://github.com/mapbox/mapbox-gl-native/blob/a1195f6a9dc57910f7c3e6c9217e3041929a01fb/platform/darwin/src/NSExpression%2BMGLAdditions.mm#L1064-L1065

However, I’m unsure how this code for key path expressions is incorrect:

https://github.com/mapbox/mapbox-gl-native/blob/a1195f6a9dc57910f7c3e6c9217e3041929a01fb/platform/darwin/src/NSExpression%2BMGLAdditions.mm#L1046-L1056
