### ISSUE TITLE
64 bit builds (ABI arm64-v8) on Android are noticeably slower than 32 bit builds )ABI armeabi-v7a

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#11883]
**Platform:Android**
**Mapbox SDK version:Master**

### Steps to trigger behavior
I recently ran into this issue when I noticed that map performance was much better on older 32 bit devices (Note 3, Galaxy AMP2) and perceptibly slower on Pixel and more recent Samsung tablets. Upon further investigation I found that the devices where performance is perceptibly slow are 8 CPU core, ARM-v8 devices.
I deleted the arm-v8 folder from jniLibs and re-created the .aar file. With arm-v7 libs in the .aar file, performance returns back to acceptable on Pixel.

  
 1. Areas with lot of fills, lines and symbols (urban areas), it takes perceptibly longer times for tiles to appear on 64 bit devices (e.g. pixel)

 2. From the .aar file remove the 64 bit jniLibs
 3. Rebuild the application.
 4.  Performance returns back to normal.

I tried looking at the flags used for 64 bit compilation. But I didn't see anything unusual.
You can find the relevant flags in this file.
MapboxGLAndroidSDK/.externalNativeBuild/cmake/release/arm64-v8a/build.ninja

### Expected behavior
Performance on 64 bit devices with ARM v8 binaries should be comparable with performance on 64 bit devices with ARM V7 binaries.

### Actual behavior
Removing the 64 bit jniLibs gives a tremendous improvement in performance on 64 bit devices.

**Comment by tobrun** [comment]
@mb12 how are you measuring performance and which device are you testing on?

I did 2 clean runs on a Samsung s8 and seeing the following average fps:
 - 64 bit : 59.71
 - 32 bit : 60.30

Can't say that these results vary enough to be noticeable.

**Comment by mb12** [comment]
By performance I am not referring to FPS. I am referring to the time it takes to layout a tile into buckets. There is a noticeable lag on 64 bit devices.
For eg doing setFilter on a basemap layer triggers layout of all the tiles in the viewport. This is significantly slow on 64 bit devices.  So if changing the filter causes map appearance to change, this change is significantly delayed on 64 bit devices.
