### ISSUE TITLE
Compass Mapbox

### ISSUE THREAD

**Issue by lorenzhahaha** [mapbox/mapbox-gl-native#11884]
Hello. I would like to ask if I can customize the compass default given by mapbox. I would like it to look like a Floating Action Button with elevation because in the default, it has no elevation. Please help me.

**Comment by tobrun** [comment]
@lorenzhahaha the compass shown overlain on the map is an ImageView. If you want you can access the view with `mapView.findViewById(R.id.compassView)` and set elevation yourself. Additionally you can change other the image used by CompassView with `mapboxMap.getUiSettings().setCompassImage(Drawable drawable)`.  FWIW you can also create a custom compass by listening to map change events and updating the view as:

```java
  /**
   * Updates the direction of the compass.
   *
   * @param bearing the direction value of the map
   */
  public void update(final double bearing) {
    rotation = (float) bearing;

    if (!isEnabled()) {
      return;
    }

    if (isHidden()) {
      if (getVisibility() == View.INVISIBLE || fadeAnimator != null) {
        return;
      }
      postDelayed(this, TIME_WAIT_IDLE);
      return;
    } else {
      resetAnimation();
      setAlpha(1.0f);
      setVisibility(View.VISIBLE);
    }

    notifyCompassAnimationListenerWhenAnimating();
    setRotation(rotation);
  }

```

Hope this helps, closing as answered.
