### ISSUE TITLE
MGLMapView does not allow me to change desired accuracy

### ISSUE THREAD

**Issue by str11ngfello** [mapbox/mapbox-gl-native#11890]
#showUserLocation on the MGLMapView in iOS defaults the GPS radio accuracy to Best with no apparent way for us to control it. We desperately need to control the accuracy (so we can lower it) for performance reasons in specific environmental conditions. I don't see any way to reach into Mapbox and set it lower. Please advise. Thank you.

**Platform:**
**Mapbox SDK version:**

### Steps to trigger behavior

 1.
 2.
 3.

**Comment by sebastianludwig** [comment]
This would be addressed by #11983
