### ISSUE TITLE
-Wfloat-equal produces compiler warning in Mapbox SDK

### ISSUE THREAD

**Issue by leviathan** [mapbox/mapbox-gl-native#11898]
**Platform:**
```
MacOS high sierra - 10.13.4 (17E202)
Xcode Version 9.3 (9E145)
Carthage 0.29.0
```

**Mapbox SDK version:**
```
Maps SDK for iOS v4.0.0
```

### Steps to trigger behavior

 1. Include Mapbox SDK via carthage into the project.
 2. In Xcode build settings `Treat Warnings as Errors` = YES
 3. In `xcconfig` set `WARNING_CFLAGS = -Wfloat-equal`

### Expected behavior

No warning is produced, because float numbers are compared for equality as suggested by Apple (e.g. `fabs(...) & epsilon).

### Actual behavior

Compiler warning is produced:
```
Mapbox.framework/Headers/MGLGeometry.h:33:33: Comparing floating point with == or != is unsafe
```

![screenshot 2018-05-14 09 01 00](https://user-images.githubusercontent.com/115210/39982937-403719d2-5756-11e8-8adc-efe6a6c7e838.png)

**Comment by friedbunny** [comment]
Thanks for the report — I’m unsure if this warning represents a practical issue, as there’s [some dispute](https://stackoverflow.com/questions/11421756/weverything-yielding-comparing-floating-point-with-or-is-unsafe) about this [tricky topic](https://bitbashing.io/comparing-floats.html).

As for how `MGLCoordinateSpan`s  are generated and used, I think manually input values could be problematic in terms of comparison:

```objc
- (void)testCoordinateSpan {
    MGLCoordinateBounds bounds = MGLCoordinateBoundsMake(CLLocationCoordinate2DMake(38.9131982, -77.0325453144239),
                                                         CLLocationCoordinate2DMake(37.7757368, -122.4135302));

    MGLCoordinateSpan span = MGLCoordinateBoundsGetCoordinateSpan(bounds);
    MGLCoordinateSpan expectedSpan = MGLCoordinateSpanMake(-1.1374614, -45.3809848856);

//    error: -[MGLGeometryTests testCoordinateSpan] : ((span.latitudeDelta) equal to (expectedSpan.latitudeDelta)) failed: ("-1.1374614") is not equal to ("-1.1374614")
//    error: -[MGLGeometryTests testCoordinateSpan] : ((span.longitudeDelta) equal to (expectedSpan.longitudeDelta)) failed: ("-45.3809848856") is not equal to ("-45.3809848856")

    expectedSpan = MGLCoordinateSpanMake(-1.1374613999999994, -45.380984885576098);

    XCTAssertEqual(span.latitudeDelta, expectedSpan.latitudeDelta);
    XCTAssertEqual(span.longitudeDelta, expectedSpan.longitudeDelta);

    XCTAssertTrue(MGLCoordinateSpanEqualToCoordinateSpan(span, expectedSpan));

    // ✅
}
```

... but I don’t think manual input is a use case we’ve ever seen — `MGLCoordinateSpan` is always generated by the SDK from existing bounds, where full precision is maintained. This isn’t a topic I’m particularly well versed in, though, so perhaps @1ec5 and @julianrex have thoughts.

**Comment by 1ec5** [comment]
`MGLCoordinateSpanEqualToCoordinateSpan()` is a pretty obscure function provided for completeness rather than a concrete need in the SDK itself. MapKit apparently doesn’t have a corresponding `MKCoordinateSpanEqualToCoordinateSpan()` function, even though that library uses coordinate spans a lot more heavily than this SDK does.

Some options:

* Introduce an epsilon tolerance into the comparison. Does this change the expected semantics of an “is equal” function?
* Move the implementation of this function into MGLGeometry.mm so that the inlined code doesn’t pollute application targets’ build logs.
* Use a pragma to ignore the warning.

/ref mapbox/mapbox-gl-native#6060
