### ISSUE TITLE
Metrics: Location anonymization on-device

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#1190]
My proposal is to do as much anonymization as possible on-device, only sending the least intrusive (but still viable) location data to Mapbox servers.

Doing this on-device would have privacy benefits for the user and would demonstrate in the open (i.e., source) what steps Mapbox is taking to that end. The metrics platform hasn't launched and I'm sure there have been reams of internal discussion about all of this, but based on my current understanding as an outsider here are a few suggestions.

[`[MGLMetricsLocationManager init]`](https://github.com/mapbox/mapbox-gl-native/blob/bf3c87b17ffe8e560f9509ba99d8e1e923d034fe/platform/ios/MGLMetricsLocationManager.m#L14-L23):

- Using a `desiredAccuracy` less than `kCLLocationAccuracyBest` has potential battery life benefits and even the coarsest level `kCLLocationAccuracyThreeKilometers` would probably be sufficient.

- Setting `distanceFilter` (location-change update granularity) to some large value (currently 2 meters) could also have some benefit, though this would have to be investigated.

[`[MGLMetricsLocationManager locationManager:didUpdateLocations:]`](https://github.com/mapbox/mapbox-gl-native/blob/bf3c87b17ffe8e560f9509ba99d8e1e923d034fe/platform/ios/MGLMetricsLocationManager.m#L47-L48):

- Generalize/truncate `latitude` and `longitude` before they're sent anywhere.

Would also have to look into the effect `MGLMapView`'s location manager being active has on these changes, making the third point likely the most significant.

In any case, I'm looking forward to learning more about these metrics and seeing what the larger picture and public messaging will be.

**Comment by incanus** [comment]
Cool, thanks for the feedback. FWIW we are shooting for using the significant change API and not "normal mode", which is where `desiredAccuracy` and `distanceFilter` factor in. Still some testing to be done there but FYI.

**Comment by mb12** [comment]
@incanus A better way to derive this metric would be to parse tile server access logs.

**Comment by friedbunny** [comment]
@mb12 Wouldn't that be a measure of which places were the most viewed, rather than user location?

@incanus Happy to hear about plans to use the significant-change API, that should mitigate most of the battery impact. The [Core Location docs](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/CoreLocation/CoreLocation.html) emphasize background waking, but of course it's possible to judiciously turn off location monitoring whenever. :grin:

**Comment by mb12** [comment]
@friedbunny Yes, that is correct. "Where the map is viewed metric" is more important if one wants to focus on optimizing rendering quality, tile parsing times, change map styles etc.

**Comment by friedbunny** [comment]
@bleege and company have been working hard on this, closing this stale issue.
