### ISSUE TITLE
use setGestureInProgress()

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1191]
Android SDK should call `setGestureInProgress(true)` when a gesture begins and `setGestureInProgress(false)` when it ends. This is used to enable/disable texture interpolation:

Without `setGestureInProgress()`:

![](http://g.recordit.co/l1av82ToiD.gif)

With `setGestureInProgress()`:

![](http://g.recordit.co/7pJwpozCL6.gif)

Note how the icon doesn't jump between pixels but rather moves gradually at the expense of sharpness.

**Comment by ljbade** [comment]
Currently working on this.

**Comment by ljbade** [comment]
OK this has been merged. I basically set it in progress whenever there is a finger on the screen as this was easier than messing with the gesture detectors.

I think it is working fine, hard to tell the difference though due to my phone's high screen resolution.
