### ISSUE TITLE
MapBox New Style Doesn't Work: Android

### ISSUE THREAD

**Issue by nikiizvorski** [mapbox/mapbox-gl-native#11912]
Hi, we are having some issues on Android since our IOS version is currently working with this style:

mapbox:mapbox_styleUrl="mapbox://styles/primozplanko/cjh7pyhzj68lt2rqskwb5qq3t"

**Platform: Android N, O, P 
**Mapbox SDK version: 5.20, 6.00, 6.01

### Steps to trigger behavior

 1. Just load the link and it doesn't render

### Expected behavior

1. Load the style on Android and IOS

### Actual behavior

You can see the attached screens below from IOS and Android:

https://imgur.com/a/WVzKQlu - Android Version

https://imgur.com/a/Lza1Pv8 - IOS Version

We would like to have Android working as expected.

Working style for us:

mapbox:mapbox_styleUrl="mapbox://styles/primozplanko/cj98nustu2jkn2so4wandrag9"

We would like the link on the top to render also and don't give us artifacts. Thanks

**Comment by novodimaporo** [comment]
+1
Im getting the same issue here, but in my case im getting a lag. Using a custom map built using mapstudio will cause a lag that freeze the screen forever, using the default map wont trigger the lag. we added a custom layer, is that contributing to this problem?

**Comment by nikiizvorski** [comment]
We found where is the issue it was because of the deprecation. This is the code we need a representation of the new version:

`SymbolLayer markers = new SymbolLayer("marker-layer", "marker-source"); markers.setProperties(iconImage(property("id", categorical(stops.toArray(new Stop[stops.size()])))), iconAllowOverlap(true), iconIgnorePlacement(true), circleRadius(zoom(exponential( stop(12, circleRadius(10f)), stop(22, circleRadius(10f)) ).withBase(10f))));`

After this it should work as expected

**Comment by novodimaporo** [comment]
You can replace it with expressions. Im not so used to it, but theres equivalent, eg. Expression.zoom, Expression.stop.

**Comment by nikiizvorski** [comment]
> You can replace it with expressions. Im not so used to it, but theres equivalent, eg. Expression.zoom, Expression.stop.

Thats exactly my point there is no documentation for this! Please if someone can share some more information how the exact representation of the code above can be achieved. Thanks Expression.zoom and stops is fine the issues is iconImage(property("id", categorical(stops.toArray(new Stop[stops.size()]))))

And on top of that circleRadius crash now since it says SymbolLayer doesn't support it!

**Comment by tobrun** [comment]
@nikiizvorski 

#### iconImage expression:
Could you provide your full setup please? you are referring to stops but you didn't add any definition of those. Happy to look more into this if you provide the required information.

#### circelRadius:
`And on top of that circleRadius crash now since it says SymbolLayer doesn't support it!` symbols have never supported the circleRadius property. What you are looking for will probably be `iconSize`, circleRadius only works for CircleLayer. That said: the correcty syntax would be to remove the circleRadius from your expression definition: eg. `circleRadius(zoom(exponential( stop(12, 10f)), stop(22, 10f)) ).withBase(10f))));`

#### documentation
`Thats exactly my point there is no documentation for this! `, thank you for flagging this, we are aware and working on fixing this asap.  cc @zugaldia @lilykaiser @langsmith

**Comment by tobrun** [comment]
@novodimaporo that is a different issue, please ticket this out in a separate issue.

**Comment by nikiizvorski** [comment]
final ArrayList<Expression.Stop> stops = new ArrayList<>();

SymbolLayer markers = new SymbolLayer("marker-layer", "marker-source"); markers.setProperties(iconImage(property("id", categorical(stops.toArray(new Stop[stops.size()])))), iconAllowOverlap(true), iconIgnorePlacement(true), circleRadius(zoom(exponential( stop(12, circleRadius(10f)), stop(22, circleRadius(10f)) ).withBase(10f))));

com.mapbox.geojson.Feature feature = com.mapbox.geojson.Feature.fromGeometry(com.mapbox.geojson.Point.fromLngLat(getLocationCoordinates().getLongitude(), getLocationCoordinates().getLatitude()));
                JsonObject jsonObject = new JsonObject();
                jsonObject.addProperty("id", mapUser.getFireId());
                //feature.setProperties(jsonObject);
                feature.addProperty("id", jsonObject);
                markerCoordinates.add(feature);
                stops.add(stop("id", screen.iconImageRandom("id", "url", null)));

**Comment by tobrun** [comment]
First item to address is with `stop("id", screen.iconImageRandom("id", "url", null)` this means you will create a stop with key="id" while you want reference the feature property value with key="id" instead. To get that value you need to use `get("id")` so the code becomes: `stop(get("id"), screen.iconImageRandom("id", "url", null)`.  

Second is that categorical function have been removed and replaced with expressions. Given that the id mentioned in your code reference a Number or a String. You can use the match expression:

Here is an example with fillColor (this example doesn't wrap the stops but we expose the api to do so)
```java
      fillColor(
        match(
          get("name"),
          literal("Westerpark"), rgba(255.0f, 0.0f, 0.0f, 1.0f),
          literal("Jordaan"), rgba(0.0f, 0.0f, 255.0f, 1.0f),
          literal("Prinseneiland"), rgba(0.0f, 255.0f, 0.0f, 1.0f),
          rgba(0.0f, 255.0f, 255.0f, 1.0f) // default if nothing matches
        )
      )
```

More information on expressions [here](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions),    and the javadoc in Expression.java contains examples of all exposed expressions.

**Comment by nikiizvorski** [comment]
Thanks for the information Tobrun but it seems your implementation doesn't work! We already tried everything. Here is a snippet:

`markers.setProperties(
                   iconImage(
                           match(get("id"),
                                   literal(1) , literal("my-marker-image1"),
                                   literal("my-marker-image")
                           )
                   )
           );`

**Comment by nikiizvorski** [comment]
Thanks Tobrun we had the same implementation apparently, the feature was the problem for us. Here is the example:  feature.addNumberProperty();

**Comment by nikiizvorski** [comment]
Hey Tobrun just a quick popup we have another issues which is related to the current one here:

`iconIgnorePlacement(true),
            textIgnorePlacement(true),
            iconAnchor(ICON_ANCHOR_TOP),
            iconAllowOverlap(true),`

We are using the same as before but currently the icons that we have on our Symbol Layer seem to overlap each other we haven't changed nothing in our code and we want more spacing between them without adding more zoom to them. How can we add more spacing between the icons even if they are at the same spot? Thanks you!

**Comment by tobrun** [comment]
> Thanks Tobrun we had the same implementation apparently, the feature was the problem for us. Here is the example: feature.addNumberProperty();

Expression is aware of types and it's possible that you need to covert what you get with the `get()` expression with something as `Expression.toString(get("id"))`. The expression system should print out warnings when you aren't complying to the expected input. Aren't you seeing any logs printed when setting the layer properties?

> have on our Symbol Layer seem to overlap each other we haven't changed nothing in our code and we want more spacing between them without adding more zoom to them.

Not sure if I completely understand what you are aiming for here. Could you clarify with words or an image? The configuration mentioned indicates that you are allowing overlap and ignoring placement. A full list of symbol options can be found in the style spec [here](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-symbol).

**Comment by nikiizvorski** [comment]
Hey Tobrun, 

`Not sure if I completely understand what you are aiming for here. Could you clarify with words or an image? The configuration mentioned indicates that you are allowing overlap and ignoring placement. A full list of symbol options can be found in the style spec here.`

As i said before, we have the same implementation as before. Currently nothing changed but out icons on the map overlap each other we used the above to achieve the end result. Doesn't seem to work so we are asking for example if possible. I will prepare a screenshot for you so you can see what i mean and what we would like to achieve. Basically space between each icon if they overlap each other to push a bit and have more space between them.

Here is example:

[https://imgur.com/a/s58ogXz](url)

Result: 

They should be separated a bit more with some space between them not over each other. Hope its clearer this time. Thanks

**Comment by tobrun** [comment]
If this issue stems from multiple layers using on source, you should be able to leverage https://github.com/mapbox/mapbox-gl-native/pull/12842 to get the old 5.x behaviour.
Please reach out if you are still facing any issues, closing this issue as stale.
