### ISSUE TITLE
Feature request: Support for Android's LifecycleObserver

### ISSUE THREAD

**Issue by vanshg** [mapbox/mapbox-gl-native#11919]
I think it would make sense for the `MapView` to implement the `LifecycleObserver`/[`DefaultLifecycleObserver`](https://developer.android.com/reference/android/arch/lifecycle/DefaultLifecycleObserver). 

Then, you could simply write `getLifecycle().addObserver(mapView);` from any `LifecycleOwner` (which is implemented by both `AppCompatActivity` and `Fragment`). That way, lifecycle events can be delegated directly to `MapView` without developers having to write and manage multiple lifecycle overrides (onStart, onStop, onPause, etc etc)

I believe this would also allow backwards compatibility with the current way of doing things, as the `LifecycleOberserver` methods internally can call the pre-existing `onStart`, `onStop`, `onPause`, etc

**Comment by tobrun** [comment]
Thanks for reaching out an proposing this @vanshg. I initially looked into this in https://github.com/mapbox/mapbox-gl-native/pull/10870. I punted on progress there as I had to rewrite state management to a ViewModel vs Bundle with onSaveInstanceState. @LukasPaczos is now looking implementing this again.

**Comment by tobrun** [comment]
Now remembering that we are already tracking this in https://github.com/mapbox/mapbox-gl-native/issues/9039. 
Closing as a duplicate, thank you for reaching out though!

**Comment by vanshg** [comment]
Ah, sorry for the duplicate. I had searched in Issues but not Pull Requests
