### ISSUE TITLE
MapBox 6.1.1 Latest ProGuard Rules - Android

### ISSUE THREAD

**Issue by nikiizvorski** [mapbox/mapbox-gl-native#11926]
Hi we are experiencing major crash on production after release build here is the output with telemetry:

`
Fatal Exception: java.lang.ExceptionInInitializerError
com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000 (Unknown Source:41)
com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry (Unknown Source:46)
com.mapbox.mapboxsdk.maps.Telemetry.initialize (Unknown Source:30)
com.mapbox.mapboxsdk.Mapbox.getInstance (Unknown Source:49)
app.setMap (Unknown Source:71)
app.onCreate (Unknown Source:40)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1125)
arrow_drop_down
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
Caused by java.lang.IllegalStateException
Not allowed to start service Intent { cmp=/com.mapbox.android.telemetry.TelemetryService }: app is in background uid UidRecord{ed3b95c u0a959 CEM idle procs:1 seq(0,0,0)}
android.app.ContextImpl.startServiceCommon (ContextImpl.java:1538)
arrow_drop_down
android.content.ContextWrapper.startService (ContextWrapper.java:663)
arrow_right
com.mapbox.android.telemetry.MapboxTelemetry.startLocation (Unknown Source:490)
com.mapbox.android.telemetry.MapboxTelemetry.startTelemetryService (Unknown Source:226)
com.mapbox.android.telemetry.MapboxTelemetry.optLocationIn (Unknown Source:197)
com.mapbox.android.telemetry.MapboxTelemetry.startTelemetry (Unknown Source:461)
com.mapbox.android.telemetry.MapboxTelemetry.enable (Unknown Source:136)
com.mapbox.mapboxsdk.maps.Telemetry. (Unknown Source:25)
com.mapbox.mapboxsdk.maps.Telemetry. (Unknown Source:10)
com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder. (Unknown Source:42)
com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000 (Unknown Source:41)
com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry (Unknown Source:46)
com.mapbox.mapboxsdk.maps.Telemetry.initialize (Unknown Source:30)
com.mapbox.mapboxsdk.Mapbox.getInstance (Unknown Source:49)
app.setMap (Unknown Source:71)
app.onCreate (Unknown Source:40)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1125)
arrow_drop_down
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)`

**Platform: Android
**Mapbox SDK version: 6.1.1

### Steps to trigger behavior
 0. We are using the following dependencies:

`implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.1'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic:0.3.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.2'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-building:0.1.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-geojson:0.1.0'

    /*
        MapBox Android UI
    */
    implementation 'com.mapbox.mapboxsdk:mapbox-android-ui:2.2.9'`

 1. Build Config Release App 
 2. We already have quit a lot configs for OkHttp3 and retrofit so by our base we have that included

`
# config for the SDK
-keep class com.mapbox.mapboxsdk.** { *; }
-keep interface com.mapbox.mapboxsdk.** { *; }
-keep class com.mapbox.mapboxsdk.maps.** { *; }
-keep interface com.mapbox.mapboxsdk.maps.** { *; }
-keep class com.mapbox.mapboxsdk.maps.Telemetry.* { *; }
-keep class com.mapbox.mapboxsdk.plugins.locationlayer.* { *; }
-keep interface com.mapbox.mapboxsdk.plugins.locationlayer.* { *; }

# config for mapbox-android-telemetry:3.0.0-beta.1
-keep class com.mapbox.services.android.telemetry.** { *; }
-keep class com.mapbox.android.telemetry.** { *; }
-keep class om.mapbox.android.core.* { *; }
-dontwarn com.mapbox.android.core.location.MockLocationEngine
-dontwarn com.mapbox.android.core.location.MockLocationEngine$LocationUpdateRunnable
-dontwarn java.awt.Color
-dontwarn com.mapzen.android.lost.api**
-dontwarn org.conscrypt.OpenSSLProvider
-dontwarn org.conscrypt.Conscrypt

# config for mapbox-sdk-geojson:3.0.1
-keep class com.mapbox.geojson.** { *; }
-keep class com.google.gson.** { *; }
-dontnote com.google.gson.internal.UnsafeAllocator

# MAS data models that will be serialized/deserialized over Gson
-keep class com.mapbox.services.api.directionsmatrix.v1.models.** { *; }

# --- Java ---
-dontwarn com.mapbox.api.staticmap.v1.models.StaticMarkerAnnotation
-dontwarn com.mapbox.api.staticmap.v1.models.StaticPolylineAnnotation

# --- AutoValue ---
# AutoValue annotations are retained but dependency is compileOnly.
-dontwarn com.google.auto.value.**

-dontwarn com.mapzen.android.lost.api**

-dontwarn com.mapbox.mapboxsdk.plugins.locationlayer.**
-dontwarn okhttp3.internal.platform.ConscryptPlatform.**

# --- GMS ---
-keep public class com.google.android.gms.* { public *; }
-dontwarn com.google.android.gms.**`

These are the mapbox configs in our proguard. Also we are including the latest map as implementation and as an api. Both cases same result. We have tested with the same config on 5.2+ no issues.

Would greatly appreciate some help on this one. Thanks for the support.

### Expected behavior

Not to crash on MapBox Load

### Actual behavior

Crash on MapBox Load

**Comment by LukasPaczos** [comment]
Thanks for reaching out @nikiizvorski. Tagging @electrostat here.

**Comment by nikiizvorski** [comment]
Thanks Lukas i had some talks with different people and we found a solution around this i believe. 

https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten

**Comment by nikiizvorski** [comment]
That issue is related to both. The obfuscation also! You won't be able to start the application if you don't have that rule and if you use the same setup as we do.

**Comment by nick-kleban** [comment]
I can't see any significant difference between our logs, i just trimmed top part of my log. It's the same issue about starting service when app is in background on Android 8.0, and i have it on debug build. I'm wondering what the difference?

We are using MapBox without any custom rules on release builds with proguard, and it works same, crash happens only in rare cases. 
Our version is:
`implementation "com.mapbox.mapboxsdk:mapbox-android-sdk:6.0.1"`

**Comment by nikiizvorski** [comment]
Yes the difference is that the application doesn't even start in our case in the beginning.

**Comment by nikiizvorski** [comment]
Remove your obfuscation and try again if you can post the proguard. I will able to help you out on it :), Usually it is either ProGuard. But the case for telemetry is:

https://github.com/mapbox/mapbox-events-android/pull/152

**Comment by tobrun** [comment]
Haven't heard about any issues in the latest 6.2.1 release. 
Closing, feel free to reach out if you hit any issues.
