### ISSUE TITLE
Map continues to display for 0.5 second after the screen is closed

### ISSUE THREAD

**Issue by ioel** [mapbox/mapbox-gl-native#11920]
**Platform:** Android
**Mapbox SDK version:** 5.5.1

### Steps to trigger behavior

 1. Create screen with ViewPager
 2. Place MapView on first page and some other info on second page
 3. Open screen and switch to second page
 4. Close screen by back button

### Expected behavior
Map should dessapear with screen

### Actual behavior
Map continues to display for 0.5 second after the screen is closed. 
Video: https://www.youtube.com/watch?v=EJLgo2rckNE&feature=youtu.be
Reproduced only on Samsung devices. Tested on Samsung A5 (7.0) and Samsung Note 5 (7.0)

**Comment by tobrun** [comment]
To support these kind of interactions you need enable TextureView rendering instead of using the standard GLSurfaceView. You can either enable this in xml (`mapbox_textureMode=true`) or with `MapboxMapOptions#textureMode(true)`. Let us know if this doesn't solve your issue.
Closing as responded.
