### ISSUE TITLE
Map freeze using custom style

### ISSUE THREAD

**Issue by novodimaporo** [mapbox/mapbox-gl-native#11928]
**Platform: Android 8**
**Mapbox SDK version: 6.1.1**

### Steps to trigger behavior
 1. `MapTry.kt`
```kotlin
class MapTry : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        Mapbox.getInstance(this, "...")
        setContentView(R.layout.content_main_static)
        map_view.onCreate(savedInstanceState)
    }

    ...
}
```
 2. `content_main_static.xml`
```xml
...
    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/map_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        mapbox:mapbox_cameraTargetLat="35.667386"
        mapbox:mapbox_cameraTargetLng="139.696212"
        mapbox:mapbox_cameraZoom="14"
        mapbox:mapbox_styleUrl="mapbox://styles/flipmap/cjfqad3fe50wz2sp9o5ha7i9y" />
...
```
 3. Launch the Application

### Expected behavior
It should work normally

### Actual behavior
Huge lag is experienced, in logcat I receive ~4 logs that says
`E/mbgl: {<package-name>}[Setup]: loading style failed: failed to connect to api.mapbox.com/54.192.72.80 (port 443) from /192.168.2.141 (port 41360) after 10000ms`

The lag is not immediate if I set the default `cameraTarget` to another place other than the region inside Japan. Perhaps because the data is concentrated in Japan.

This shows after launching the app
<img src="https://user-images.githubusercontent.com/28850977/40154230-f75ea4fc-59bf-11e8-8fca-a480e1bd2695.gif" width="200">

Then, this shows up after around a min.
<img src="https://user-images.githubusercontent.com/28850977/40154234-f9e97ce2-59bf-11e8-8057-f4b4d0658f88.gif" width="200">

**Comment by LukasPaczos** [comment]
Thanks for reaching out @novodimaporo. Tagging @electrostat here.

**Comment by LukasPaczos** [comment]
Hey @novodimaporo, is this one still an issue? I can load the specified region without any problems using the default style. The style you provided throws `404`, is it still available?

**Comment by LukasPaczos** [comment]
Closing the ticket as I was able to reach the linked style and the map is loading with no issues. Feel free to reach out if you're still seeing any problems.
