### ISSUE TITLE
How to restore info window on configuration change with cluster plugin?

### ISSUE THREAD

**Issue by dotPilot** [mapbox/mapbox-gl-native#11932]
I use mapbox-android-plugin-cluster-utils:0.1.0. I need to restore info window on device rotation. Right now I call `marker.showInfoWindow(mMapboxMap, mMapView)` in `CreateMarkerTask.perform(MarkerModifier markerModifier)` of custom modification of ClusterRenderer, but then this info window can't be closed by tap on a map, although others info windows work fine and open/hide, while restored info window remain visible all the time. Also, that info window is not moving with it's marker on map scrolling, but stays at the same position at screen.
So, what is best practice to restore info windows and what listener can tell me when cluster plugin put all markers at map?

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by dotPilot** [comment]
So, this is not a bug?
![device-2018-05-19-145700 2](https://user-images.githubusercontent.com/12918725/40267610-fccde6fe-5b78-11e8-91e6-f2d9ed7240ab.gif)

**Comment by LukasPaczos** [comment]
@dotPilot, per https://github.com/mapbox/mapbox-plugins-android/issues/522 the cluster-plugin is going to be deprecated and removed so I suggest switching to the Layer API. You can find some pointers and examples regarding clustering and info windows in the [demo Activity](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/SymbolLayerMapillaryActivity.java).
