### ISSUE TITLE
Offline Region conflicts after migrating vom V5 to V6

### ISSUE THREAD

**Issue by johanneslaubermoovel** [mapbox/mapbox-gl-native#11930]
**Platform:** Android
**Mapbox SDK version:** 6.1.1.

### Steps to trigger behavior

 1. Start the Project with V5.x.x and download map tiles, in our case Stuttgart, Germany area
 2. Upgrade the project to V6.1.1 
 3. Request the offline regions

As you see in the screenshot, the requiredResourceCount for some regionswithstatus is smaller than the completedResourceCount. Which makes no sense in my understanding. 

![bildschirmfoto 2018-05-17 um 14 43 44](https://user-images.githubusercontent.com/17448539/40178670-78d0383a-59e2-11e8-9ddc-95615f509e25.png)

**Comment by jfirebaugh** [comment]
This is likely due to https://github.com/mapbox/mapbox-gl-native/pull/11055. It's harmless and can be ignored. Or you can create a new region, and then delete the old one. The common resources will be reused, and the 256 unused resources will be eligible for eviction from the cache.

cc @kkaefer
