### ISSUE TITLE
Crash on Android after updating to 6.1.1 from 5.0 beta (SIGSEGV)

### ISSUE THREAD

**Issue by LouisCAD** [mapbox/mapbox-gl-native#11945]
Here's the only log I get:
```console
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 26137
```

**Comment by tobrun** [comment]
Thank you for reaching out @LouisCAD, with current provided information this issue isn't really actionable. To look more into this could you provide a minimal reproducible example?

**Comment by LouisCAD** [comment]
@tobrun I have no clue in what causes the issue, and I can't share my company's project on GitHub, but I'll add more details about the dependencies used, and what happens MapBox wise before the crash strikes when I'm back at office.

**Comment by LouisCAD** [comment]
@tobrun Here are the dependencies:
```groovy
// MapBox
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.1'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-cluster-utils:0.3.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.2'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places:0.4.0'
```
Note that I have no dependencies that have native libraries apart from MapBox.

The crashes are being experienced on a Samsung Galaxy A5 2016 running Android 7.0 and the app has been build using Android Studio 3.1.2 with the same version of the Android Gradle plugin.

What is reproducing the issue on my side is starting, exiting, restarting, exiting again and so on about ten times, an Activity that displays a SupportMapFragment (using support lib 27.1.1), with location layer plugin enabled, and one marker added plus animating camera with a newLatLngZoom.

**Comment by tobrun** [comment]
Seems very similar to https://github.com/mapbox/mapbox-plugins-android/issues/509, are you hooking into onStart/onStop correctly from the LocationLayerPlugin?

**Comment by LouisCAD** [comment]
Oh no, why don't you take advantage of the `Lifecycle`s in Android Architecture Components?

You changed `map.isMyLocationEnabled = true` to an unsafe implementation nightmare...

**Comment by LouisCAD** [comment]
Putting `@RequiresPermission` on the `onStart` method is bad API design. I'm not sure the authors of the location layer plugin understood how lifecycle events work...

**Comment by LouisCAD** [comment]
Anyway, I solved the issue by calling the onStart and onStop methods with a lifecycle observer
