### ISSUE TITLE
iOS: NSExpression with heatmapColor 

### ISSUE THREAD

**Issue by benslk** [mapbox/mapbox-gl-native#11947]
**Platform:** iOS 11.3 / Swift 4.1
**Mapbox SDK version:** 4.0.1

Hello, 

I cannot find the right way to use `NSExpression` with colors, specifically to set a custom color palette to a `MGLHeatmapStyleLayer` with the `heatmapColor`. I could not find any example in the documentation or anywhere else for that matter.

The code I am trying to produce is the following. I have `source` and `mapView` that are previously defined.

```
let layer = MGLHeatmapStyleLayer(identifier: "my-heat", source: source)
layer.heatmapColor = NSExpression(format: "mgl_interpolate:withCurveType:parameters:stops:($heatmapDensity, 'linear', nil, %@)",
                                                              [0: UIColor.init(red: 33, green: 102, blue: 172, 0),
                                                               0.2: UIColor.init(red: 103, green: 169, blue: 207),
                                                               0.4: UIColor.init(red: 209, green: 229, blue: 240),
                                                               0.6: UIColor.init(red: 253, green: 219, blue: 199),
                                                               0.8: UIColor.init(red: 239, green: 138, blue: 98),
                                                               1: UIColor.init(red: 178, green: 24, blue: 43)])
mapView.style?.addLayer(layer)
```

I cannot compile this code, as I have an error `Contextual type 'CVarArg' cannot be used with dictionary literal`, however, I'd like to know how to use `NSExpression` with `UIColor` correctly.

Thank you in advance.

**Comment by jmkiley** [comment]
Thank you for using Mapbox! This repo is for reporting issues or requesting features. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/). We'd be happy to help. You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).

In the meantime, you may find this [heatmap layer example](https://github.com/mapbox/ios-sdk-examples/blob/master/Examples/Swift/HeatmapExample.swift#L29) layer helpful.
