### ISSUE TITLE
Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.2.

### ISSUE THREAD

**Issue by paulsUsername** [mapbox/mapbox-gl-native#11956]
**Platform:**
Android
**Mapbox SDK version:**
6.1.2
6.1.1

Only version that works is 5.5.0

### Steps to trigger behavior

 1. Setup new project
 2. Add everything as per instructions
 3. Get this message when trying to sync gradle:
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.2.

Only way to resolve:
change version to 5.5.0

### Expected behavior
Gradle to sync and map to work

### Actual behavior
Get the following messages when syncing gradle:

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.2.
Open File
Show Details

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.2.
Open File
Show Details

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.2.
Open File
Show Details

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.2.
Open File
Show Details

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.2.
Open File
Show Details

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.2.
Open File
Show Details

Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.2.
Open File
Show Details

Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.2.
Open File
Show Details

Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.2.
Open File
Show Details

Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.2.
Open File
Show Details

**Comment by langsmith** [comment]
Do you have a period after the 2 in the `6.1.2` declaration? I can't tell whether it's something that Android Studio added to the end of the error sentence or whether it's part of your actual gradle file declaration. It should just be `6.1.2` and not 6.1.2.`

**Comment by nikiizvorski** [comment]
Working example:

`/*
        MapBox
    */
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.2'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic:0.3.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.2'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-building:0.1.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-geojson:0.1.0'

    /*
        MapBox Android UI
    */
    implementation 'com.mapbox.mapboxsdk:mapbox-android-ui:2.2.9'`

**Comment by jfirebaugh** [comment]
Great!

**Comment by josephepia** [comment]
tuve el mismo problema. 

en la documentación sugieren la version `9.3.0`
`implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.3.0' `
pero solo funcionó la `9.2.1`

**Comment by 0xD34D** [comment]
> tuve el mismo problema.
> 
> en la documentación sugieren la version `9.3.0`
> `implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.3.0' `
> pero solo funcionó la `9.2.1`

Encountered this as well, 9.3.0 does not download but 9.2.1 does.  Current documentation references using 9.3.0 for gradle dependency

**Comment by pengdev** [comment]
@josephepia @0xD34D please check the release note on the 9.3.0 https://github.com/mapbox/mapbox-gl-native-android/releases/tag/android-v9.3.0 .

Starting from 9.3.0, you will need to follow the instructions from https://docs.mapbox.com/android/maps/overview/#configure-credentials to obtain a Mapbox access token with the Downloads:Read scope. And then use Mapbox's maven url to fetch the sdk.
