### ISSUE TITLE
Slow load in cities around zoom 12-13

### ISSUE THREAD

**Issue by kjkrum** [mapbox/mapbox-gl-native#11954]
I'm using version 6.1.1 for Android.

If the map starts in vector mode in an area with a high density of features, either following a configuration change or because I set its position when there is no saved instance state, there is a delay of several seconds before anything is rendered. When the map finally does appear, it all renders very fast as if everything was loaded before anything was rendered. In contrast, if you then pan the map, features in the newly visible area are perceptibly loaded incrementally. I see this most often in cities around zoom level 12-13. The effect diminishes at higher or lower zoom levels when there are fewer features on the screen.

Is there a reason why the initial rendering is not incremental?

**Comment by kjkrum** [comment]
From a cold start (app swiped from recents), with version 5.5.3, the first map details appear in less than 2.5 seconds. With 6.1.2, it takes over 10 seconds. I switched back and forth between the two versions a couple times, with repeatable results.

**Comment by mb12** [comment]
@kjkrum what is the ABI/architecture type of your device ( armv7 or armv8)?

**Comment by kjkrum** [comment]
@mb12 

PROCESSOR
CPU Architecture: ARMv7 Processor rev 5 (v7l)
Board: msm8909
Chipset: Qualcomm Technologies, Inc MSM8909
Cores: 4
Clock Speed: 800 MHz - 1267 MHz
Instruction Sets: armeabi-v7a, armeabi
CPU Features: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 evtstrm
CPU Governor: interactive
Kernel Version: 3.10.49-g6441669-00001-g4983cb6
Kernel Architecture: armv7l

GRAPHICS
Renderer: Adreno (TM) 304
Vendor: Qualcomm
OpenGL Version: OpenGL ES 3.0

**Comment by LukasPaczos** [comment]
I'm not seeing any noticeable performance regression in load times between `5.x` and `6.x` on "cold", empty cache start, results were consistent on both versions:
 - Pixel 2 (Pie), 2.0s-2.5s
 - Xperia Z1 (Lollipop), 3.0s-4.0s

Tested over SF with zoom 12.

Would you be able to provide a style you are using?
