### ISSUE TITLE
ComputedShapeSource empty array causes high cpu utilisation

### ISSUE THREAD

**Issue by WilliamSundqvist** [mapbox/mapbox-gl-native#11957]
**Platform: iOS**
**Mapbox SDK version: master, commit: 25629c81a**

### Steps to trigger behavior

 1. In sample project, replace provided example in `MBXViewController` for [MGLComputedShapeSourceDataSource](https://github.com/mapbox/mapbox-gl-native/blob/a84ac4c8d79952fa3031f5414b10a560fdef2e1d/platform/ios/app/MBXViewController.m#L2065) with:
```objc
- (NSArray<id <MGLFeature>>*)featuresInCoordinateBounds:(MGLCoordinateBounds)bounds zoomLevel:(NSUInteger)zoom {
    return @[];
}
```
 2. Enable the "Custom Lat/Lon Grid" example.

### Expected behavior
0% CPU utilisation after the map settles. 

### Actual behavior
The CPU now hovers around 80% (on an iPhone 7 simulator). It never reaches 0, as expected. Tested on simulator and device, similar results. 

### Findings
If we move the [setData](https://github.com/mapbox/mapbox-gl-native/blob/a84ac4c8d79952fa3031f5414b10a560fdef2e1d/src/mbgl/tile/custom_geometry_tile.cpp#L45) call inside the if-statement the CPU utilisation drops as expected.

**Comment by fabian-guerra** [comment]
Hi, @WilliamSundqvist. Thank you for using Mapbox, and I am sorry to hear you have some issues. Just to confirm what you are saying is that  our [latest SDK](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v4.0.1) has the increased CPU usage?

**Comment by WilliamSundqvist** [comment]
Hi @fabian-guerra, yes I can confirm that the problem exists in the latest iOS release(ios-v4.0.1).
