### ISSUE TITLE
Rendering Issue when Offline

### ISSUE THREAD

**Issue by dsuresh-ap** [mapbox/mapbox-gl-native#11951]
**Platform: Android**
**Mapbox SDK version: 6.1.1**

### Steps to trigger behavior

 1. Add FillLayers and Symbol Layers
 2. Download offline region
 3. Turn off Internet and restart app
4. Open Map, circle polygon fill is not complete (using 45 sided Polygon for Circle)
5. Reconnect to wifi
6. Observe titles appear and circle fill is properly filled.

### Expected behavior

SymbolLayer text is shown and FillLayer fill is solid.

### Actual behavior

SymbolLayer text is not shown and circle has drawing issues.

Attached: [Recording](https://drive.google.com/file/d/1JSlMBGHTZ324uRwq53xfH4PnFj72B1ZH/view?usp=sharing)

**Comment by thaphiudil** [comment]
Same problem here. Any solution?

**Comment by tobrun** [comment]
Probably related to how your style loading is setup, to show all data as in OP, you will need to set the style url as part of MapboxMapOptions, through xml, or MapView#setStyleUrl in Activity#Oncreate. Any code backing this issue up would be appreciated but closing as answered for now.

**Comment by dsuresh-ap** [comment]
@tobrun The user is allowed to select between street/sat maps in our app and download offline regions accordingly. We set the style url in a few places at a few stages.

1. We set the style url in XML to default to street
2. We set the style url on the `MapView` in onActivityCreated before calling `getMapAsync()` to match the user's setting.
3. After `onMapReady` we call `setStyle()` on the MapBoxMap with the url again.
4. We set the style url when the user toggles between.

I remember doing 2 and 3 because otherwise our layers don't show on the map until we set the style url again when offline.

**Comment by dsuresh-ap** [comment]
@tobrun I modified the demo app's `OfflineManagerActivity` to show the issue where if we don't call setStyleUrl multiple times the layers don't show when offline.

[Recording](https://drive.google.com/file/d/1JSlMBGHTZ324uRwq53xfH4PnFj72B1ZH/view?usp=sharing)

```mapView.getMapAsync(new OnMapReadyCallback() {
      @Override
      public void onMapReady(MapboxMap mapboxMap) {
        map = mapboxMap;
        addLayers();
      }
    });

private void addLayers()
  {
    List<Feature> markerCoordinates = new ArrayList<>();
    markerCoordinates.add(Feature.fromGeometry(
            Point.fromLngLat(-74.0151, 40.7358))); // Boston Common Park
    markerCoordinates.add(Feature.fromGeometry(
            Point.fromLngLat(-74.0152, 40.7359))); // Fenway Park
    markerCoordinates.add(Feature.fromGeometry(
            Point.fromLngLat(-74.0150, 40.7360))); // The Paul Revere House
    FeatureCollection featureCollection = FeatureCollection.fromFeatures(markerCoordinates);

    Source geoJsonSource = new GeoJsonSource("marker-source", featureCollection);
    map.addSource(geoJsonSource);

    Bitmap icon = BitmapFactory.decodeResource(
            OfflineManagerActivity.this.getResources(), R.drawable.blue_marker_view);

    // Add the marker image to map
    map.addImage("my-marker-image", icon);

    SymbolLayer markers = new SymbolLayer("marker-layer", "marker-source")
            .withProperties(PropertyFactory.iconImage("my-marker-image"),
                            PropertyFactory.textField("Testing"));
    map.addLayer(markers);

    // Add the selected marker source and layer
    FeatureCollection emptySource = FeatureCollection.fromFeatures(new Feature[]{});
    Source selectedMarkerSource = new GeoJsonSource("selected-marker", emptySource);
    map.addSource(selectedMarkerSource);

    SymbolLayer selectedMarker = new SymbolLayer("selected-marker-layer", "selected-marker")
            .withProperties(PropertyFactory.iconImage("my-marker-image"));
    map.addLayer(selectedMarker);
  }```

**Comment by tobrun** [comment]
@dsuresh-ap could you remove:
 - the streets style in your xml decleration 
 - remove the setStyle in the onMapReady callback

instead of calling `MapView#setStyleUrl` just use `MapView#setOfflineRegionDefinition` instead?

**Comment by dsuresh-ap** [comment]
@tobrun Removing the declaration from the xml and `setStyle` from `onMapReady` fixed the issue. Thanks!
