### ISSUE TITLE
Use fragment's xml attributes

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#11967]
We are not taking into account mapbox attributes passed with fragment's xml tag, for example in the [multi-map activity](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/activity_multi_map.xml). Since fragments are getting more traction again, we should fix the parsing.

**Comment by tobrun** [comment]
<img width="816" alt="screen shot 2018-05-27 at 10 39 29" src="https://user-images.githubusercontent.com/2151639/40584038-85126900-619a-11e8-9dfa-ed8e34d56a25.png">
