### ISSUE TITLE
Java 8 compatibility problem of mapbox-sdk-geojson

### ISSUE THREAD

**Issue by fightyz** [mapbox/mapbox-gl-native#11975]
**Platform:** Android 8.0
**Mapbox SDK version:** com.mapbox.mapboxsdk:mapbox-sdk-geojson:3.1.0

### Steps to trigger behavior

 1. Set the android plugin for gradle to "com.android.tools.build:gradle:2.3.3" (below 3.1.0)
 2. Set the mapbox-sdk-geojson to "com.mapbox.mapboxsdk:mapbox-sdk-geojson:3.1.0"
 3. Set the target sdk version to 21 (below 24)

### Actual behavior
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the \u0027java\u0027 gradle plugin in a library submodule add \ntargetCompatibility \u003d \u00271.7\u0027\nsourceCompatibility \u003d \u00271.7\u0027\nto that submodule\u0027s build.gradle file.

So I add 

    compileOptions {    
            sourceCompatibility JavaVersion.VERSION_1_7    
            targetCompatibility JavaVersion.VERSION_1_7    
        }

But the error is still there. 

Then I think this problem is caused by the mapbox-sdk-geojson:3.1.0 is compiled by java 8. So I change the compile options to 

    compileOptions {  
            sourceCompatibility JavaVersion.VERSION_1_8  
            targetCompatibility JavaVersion.VERSION_1_8  
        }
and add the Jack support:

    jackOptions {  
                enabled true  
            }
Then it told me: "Static method com.mapbox.geojson.Geometry fromJson(java.lang.String null) not supported in Android API level less than 24.", which is already stated in [release note](https://github.com/mapbox/mapbox-navigation-android/releases/tag/0.12.0).
![image](https://user-images.githubusercontent.com/1697504/40362545-66ccc9ac-5dff-11e8-97b7-a8764a0f3862.png)

But I already add the compile version options.

After my research, I think this is caused by the Android Plugin for Gradle whose version is 2.3.3. [Java 8 is supported after 3.0.0](https://developer.android.com/studio/write/java8-support), so I need Jack. But it seems Jack just happens not to support the static interface method, as the wrong info mentioned in above picture.

So, how can I import the new mapbox-sdk-geojson:3.1.0 using "com.android.tools.build:gradle:2.3.3" and target sdk version=21?

**Comment by fightyz** [comment]
Here is my project' build.gradle:
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
============================

Here is my module's build.gradle:
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"
    defaultConfig {
        applicationId "com.xxx.mapboxdemo"
        minSdkVersion 19
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        jackOptions {
            enabled true
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:27.1.1'
    compile 'com.android.support.constraint:constraint-layout:1.1.0'
    compile 'com.mapbox.mapboxsdk:mapbox-sdk-geojson:3.1.0'
    testCompile 'junit:junit:4.12'
    androidTestCompile 'com.android.support.test:runner:1.0.2'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:3.0.2'

}

**Comment by tobrun** [comment]
> So, how can I import the new mapbox-sdk-geojson:3.1.0 using "com.android.tools.build:gradle:2.3.3" and target sdk version=21?

Target SDK will not affect the issue from OP afaik, but the used gradle tools version will. You will need to use a minimal gradle version of `com.android.tools.build:gradle:3.x` (we use currently 3.0.1 but 3.1.2 is available) to use java 8 language features. What is the reason behind not updating the gradle tools version to a more recent version?

**Comment by fightyz** [comment]
We use [DexKnifePlugin](https://github.com/ceabie/DexKnifePlugin) to support multidex, which doesn't support `com.android.tools.build:gradle:3.x`. And some other gradle scripts using gradle's old syntactic maybe.
