### ISSUE TITLE
Receiving a lot of errors in production version (Input dispatching timed out , tgkill, signal 11 SIGSEGV)

### ISSUE THREAD

**Issue by camparound-developers** [mapbox/mapbox-gl-native#11978]
Since updating the mapbox library, we received a huge amount of ANRs and Crashes in Google Play Console.
Example ANRs and stacktraces are attached to this issue.

While running SDK 5.2.1 before the update, we didn't caputre anything like this.

I wanted to ask you, if you could lead me into the right direction on how to fix these issues and if they are based on mapbox or on our implementation.

We implemented Mapbox like given in your documentation. There's only one thing, which i assume to be the issue, but i'm not really sure: we're drawing the markers with help of a ThreadPool to the map.

Implemenation example:
`
...
mThreadPool.execute(new Runnable() {
            @Override
            public void run() {
                   ...
                   map.addMarkers(options);
                   ....
            }
})
...
`

Could this be the problem?

**Platform:** Android
**Mapbox SDK version:** 5.5.3

### Steps to trigger behavior

 1. ??? Unknown, since it happens sporadically

### Expected behavior

Should not throw any exceptions like these

### Actual behavior
Throws a lot of exceptions and tgkills

Attached logs:
[anr-1.txt](https://github.com/mapbox/mapbox-gl-native/files/2027580/anr-1.txt)
[ANR-SIGSEGV-11.txt](https://github.com/mapbox/mapbox-gl-native/files/2027581/ANR-SIGSEGV-11.txt)
[anr-tgkill-2.txt](https://github.com/mapbox/mapbox-gl-native/files/2027582/anr-tgkill-2.txt)

**Comment by jfirebaugh** [comment]
> We're drawing the markers with help of a ThreadPool to the map

This isn't supported and likely explains the crashes and ANRs; map methods like `addMarkers` must be called from the main UI thread.

**Comment by camparound-developers** [comment]
Would like to reopen this issue, since its still appearing. Changed the implementation to use the main ui thread only (double-checked it with logging out the currently used thread) and thos native crashes are still appearing.

`*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.camparound.camperapp.android <<<

backtrace:
#00  pc 000000000004a230  /system/lib/libc.so (tgkill+12)
#01  pc 00000000000479c3  /system/lib/libc.so (pthread_kill+34)
#02  pc 000000000001d9c5  /system/lib/libc.so (raise+10)
#03  pc 0000000000019511  /system/lib/libc.so (__libc_android_abort+34)
#04  pc 0000000000017150  /system/lib/libc.so (abort+4)
#05  pc 000000000031be9d  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+252)
#06  pc 00000000000b4d4b  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+866)
#07  pc 000000000023a4a1  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1584)
#08  pc 000000000023a76b  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+66)
#09  pc 000000000026b0c9  /system/lib/libart.so (_ZN3art3JNI15CallVoidMethodVEP7_JNIEnvP8_jobjectP10_jmethodIDSt9__va_list+488)
#10  pc 000000000004c4c3  /data/app/com.camparound.camperapp.android-1/lib/arm/libmapbox-gl.so
#11  pc 00000000000721e3  /data/app/com.camparound.camperapp.android-1/lib/arm/libmapbox-gl.so
#12  pc 00000000000712e7  /data/app/com.camparound.camperapp.android-1/lib/arm/libmapbox-gl.so
#13  pc 00000000002551bb  /data/app/com.camparound.camperapp.android-1/lib/arm/libmapbox-gl.so
#14  pc 00000000001c15c3  /data/app/com.camparound.camperapp.android-1/lib/arm/libmapbox-gl.so
#15  pc 00000000001bf119  /data/app/com.camparound.camperapp.android-1/lib/arm/libmapbox-gl.so
#16  pc 00000000001bf1eb  /data/app/com.camparound.camperapp.android-1/lib/arm/libmapbox-gl.so
#17  pc 00000000002510af  /data/app/com.camparound.camperapp.android-1/lib/arm/libmapbox-gl.so
#18  pc 0000000000250a11  /data/app/com.camparound.camperapp.android-1/lib/arm/libmapbox-gl.so
#19  pc 0000000000250201  /data/app/com.camparound.camperapp.android-1/lib/arm/libmapbox-gl.so
#20  pc 0000000000011f33  /system/lib/libutils.so (_ZN7android6Looper9pollInnerEi+614)
#21  pc 0000000000011c3f  /system/lib/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+26)
#22  pc 0000000000097c51  /system/lib/libandroid_runtime.so (_ZN7android18NativeMessageQueue8pollOnceEP7_JNIEnvP8_jobjecti+22)
#23  pc 00000000025b3c45  /system/framework/arm/boot-framework.oat (android.os.MessageQueue.nativePollOnce+96)
#24  pc 00000000025b5161  /system/framework/arm/boot-framework.oat (android.os.MessageQueue.next+188)
#25  pc 00000000025b0853  /system/framework/arm/boot-framework.oat (android.os.Looper.loop+366)
#26  pc 0000000001f3f733  /system/framework/arm/boot-framework.oat (android.app.ActivityThread.main+598)
#27  pc 00000000000a92c1  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
#28  pc 0000000000407a51  /system/lib/libart.so (art_quick_invoke_static_stub+228)
#29  pc 00000000000b05df  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+182)
#30  pc 0000000000316e4b  /system/lib/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+58)
#31  pc 00000000003181bf  /system/lib/libart.so (_ZN3art12InvokeMethodERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectS4_S4_j+766)
#32  pc 00000000002be8a1  /system/lib/libart.so (_ZN3artL13Method_invokeEP7_JNIEnvP8_jobjectS3_S3_+40)
#33  pc 0000000000606159  /system/framework/arm/boot.oat (java.lang.reflect.Method.invoke+116)
#34  pc 0000000002b54a01  /system/framework/arm/boot-framework.oat (com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run+100)
#35  pc 0000000002b55f4d  /system/framework/arm/boot-framework.oat (com.android.internal.os.ZygoteInit.main+1408)
#36  pc 00000000000a92c1  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
#37  pc 0000000000407a51  /system/lib/libart.so (art_quick_invoke_static_stub+228)
#38  pc 00000000000b05df  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+182)
#39  pc 0000000000316e4b  /system/lib/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+58)
#40  pc 0000000000316c5b  /system/lib/libart.so (_ZN3art17InvokeWithVarArgsERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDSt9__va_list+266)
#41  pc 0000000000278c57  /system/lib/libart.so (_ZN3art3JNI21CallStaticVoidMethodVEP7_JNIEnvP7_jclassP10_jmethodIDSt9__va_list+426)
#42  pc 000000000006b025  /system/lib/libandroid_runtime.so
#43  pc 000000000006ca9b  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb+510)
#44  pc 0000000000002e47  /system/bin/app_process32
#45  pc 0000000000016d69  /system/lib/libc.so (__libc_init+48)
#46  pc 000000000000293c  /system/bin/app_process32`

**Comment by jfirebaugh** [comment]
Okay, reopening. Could you please post a code sample or a test app that help us track down the problem?

**Comment by jfirebaugh** [comment]
Ping @camparound-developers.
