### ISSUE TITLE
iOS Crash going into background

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#1197]
I am seeing a few crashes when the app goes into background mode.

![screen shot 2015-04-03 at 10 29 29 am](https://cloud.githubusercontent.com/assets/417933/6985085/9015e6c6-d9ec-11e4-8c7e-c20bc183f513.png)

**Comment by incanus** [comment]
https://rink.hockeyapp.net/manage/apps/163490/app_versions/7/crash_reasons/32078826

**Comment by 1ec5** [comment]
Might be related to #760.

**Comment by 1ec5** [comment]
I think this is the same as #760. The differences at the bottom of the stack trace are due to the introduction of frontboard in iOS 8.
