### ISSUE TITLE
read image file failed on windows(msvc2015 + qt)

### ISSUE THREAD

**Issue by lostangelwangyang** [mapbox/mapbox-gl-native#11971]
**Platform:** windows(msvc2015 + qt)
**Mapbox SDK version:** master branch.

### Steps to trigger behavior

 1. read a local sprite(png) file via file://sprite.png.  I just got the head of the file instead of total file.

app output : [ ERROR ]  "{unknown}[Style]: Failed to load sprite: Unsupported image type"

the solution is to change the file mapbox-gl-native-master/src/mbgl/util/io.cpp: 
std::string read_file(const std::string &filename) {
\-    std::ifstream file(filename);
\+    std::ifstream file(filename, std::ios::binary);
    if (file.good()) {
        std::stringstream data;
        data << file.rdbuf();
        return data.str();
    } else {
        throw std::runtime_error(std::string("Cannot read file ") + filename);
    }
}

It's ok on Linux without std::ios::binary. but not ok on windows. Hope the author can check that.

**Comment by brunoabinader** [comment]
Hi @lostangelwangyang - thanks for your contribution! I added a patch for this in https://github.com/mapbox/mapbox-gl-native/pull/11973.

**Comment by brunoabinader** [comment]
Fixed in #11973.
