### ISSUE TITLE
iOS - High CPU Usage

### ISSUE THREAD

**Issue by SudarshanMahesh** [mapbox/mapbox-gl-native#11988]
Hello,

The CPU usage of Mapbox 4.0 and 4.0.1 are above 100% when there is a lot of objects on the map that needs to be rendered. My app then becomes not responsive anymore. I haven't had this issue before version 4.

**iOS**
**Mapbox SDK 4.0 and 4.0.1**

### Steps to trigger behavior

 1. Load a map with a lot of objects on it.
 2. Zoom in or move the map.
 3. The app becomes unresponsive.

### Expected behavior

Smooth rendering, low CPU usage.

### Actual behavior

High CPU usage, slow and app don't respond anymore.

**Comment by fabian-guerra** [comment]
Hi, @SudarshanMahesh. Thank you for using Mapbox. I am sorry to hear you are having some issues. Could you please post a code sample or a test app that help us track down the problem?

**Comment by SudarshanMahesh** [comment]
@fabian-guerra  : Here is an example project. Just zoom in on the map. 

https://we.tl/5dA8IE7mm7
