### ISSUE TITLE
Tilt gesture is too easy to trigger

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#11982]
The two-finger-vertical-drag gesture that controls tilt is currently (as of `ios-v4.0.x`) too easy to trigger — I often find myself accidentally tilting the map, when I intended to pinch zoom/rotate.

I have a vague recollection of this happening more often starting around #9386 or #9571.

This is tangentially related to #6562 (which deals with it being too easy to rotate-gesture) and #2192.

/cc @captainbarbosa @1ec5 @fabian-guerra

**Comment by julianrex** [comment]
Any reason we shouldn't add
```
[_twoFingerDrag requireGestureRecognizerToFail:_pinch];
[_twoFingerDrag requireGestureRecognizerToFail:_rotate];
```
?

**Comment by friedbunny** [comment]
I think the fix may be as simple as that, @julianrex, but we’d want to be conscious not to exacerbate #2192.

**Comment by chloekraw** [comment]
any idea if this also happens on @mapbox/maps-android ?

**Comment by LukasPaczos** [comment]
Gestures handling is implemented differently on iOS and Andriod, so we won't be of much help here :(
