### ISSUE TITLE
Heading-tracking mode takes the long way around

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#1199]
When using `MGLUserTrackingModeFollowWithHeading`, rotating the device several degrees around due south causes the map to go the wrong way to get there.

![rotation-bug](https://cloud.githubusercontent.com/assets/1198851/6986644/27ee0436-d9f4-11e4-9f96-e475bf6e038b.gif)

**Comment by friedbunny** [comment]
The headings from [`[MGLMapView locationManager:didUpdateHeading:]`](https://github.com/mapbox/mapbox-gl-native/blob/c253232473b82c5e3ae2fcb937301581c89bab50/platform/ios/MGLMapView.mm#L1870) are good.

```objc
11:48:25.347 Mapbox GL[3393:500129] headingDirection: 179.321411 (true:179.321411/mag:165.504303)
11:48:28.515 Mapbox GL[3393:500129] headingDirection: 184.756287 (true:184.756287/mag:170.939178)
11:48:34.055 Mapbox GL[3393:500129] headingDirection: 179.454987 (true:179.454987/mag:165.637878)
11:48:35.089 Mapbox GL[3393:500129] headingDirection: 184.748398 (true:184.748398/mag:170.931290)
11:48:36.282 Mapbox GL[3393:500129] headingDirection: 179.720413 (true:179.720413/mag:165.903305)
11:48:37.559 Mapbox GL[3393:500129] headingDirection: 185.071442 (true:185.071442/mag:171.254333)
```

**Comment by friedbunny** [comment]
[`Transform::_setAngle`](https://github.com/mapbox/mapbox-gl-native/blob/12c07b916b106272ba68f0fc85a10b774fd07a50/src/mbgl/map/transform.cpp#L326-L360) is trying to interpolate between negative and positive angles, where headings > 180º become negative angles.

```objc
headingDirection: 174.973160
Transform::_setAngle: -2.920038 → -3.053858
headingDirection: 180.300735
Transform::_setAngle: -3.022575 → 3.136344
headingDirection: 174.859329
Transform::_setAngle: 3.136344 → -3.051871
headingDirection: 180.390106
Transform::_setAngle: -3.051871 → 3.134784
```

**Comment by friedbunny** [comment]
@kkaefer, perhaps you've got some ideas about the best way to fix what appears to be an interpolation issue?

**Comment by jfirebaugh** [comment]
This looks like the native version of https://github.com/mapbox/mapbox-gl-js/issues/818, probably a similar fix should be applied.
