### ISSUE TITLE
Users Location Not showing with latest demo

### ISSUE THREAD

**Issue by olsisaqe** [mapbox/mapbox-gl-native#12002]
**Platform:** Android
**Mapbox SDK version:**
```
// Mapbox
            mapboxMapSdk             : '6.1.1',
            mapboxTurf               : '3.1.0',
            mapboxGeoJson            : '3.1.0',
            mapboxPluginBuilding     : '0.3.0',
            mapboxPluginLocationLayer: '0.5.2',
            mapboxPluginMarkerCluster: '0.3.0',
            mapboxPluginPlaces       : '0.4.0',
            mapboxPluginLocalization : '0.3.0',
            mapboxPluginTraffic      : '0.6.0',
```

### Steps to trigger behavior

 1. Open Demo App
 2. Go to `Show a user's location`

### Expected behavior
Zoom to current user location as it is stated in: `LocationPluginActivity`

```
  @Override
  public void onLocationChanged(Location location) {
    if (location != null) {
      setCameraPosition(location);
      locationEngine.removeLocationEngineListener(this);
    }
  }
```
### Actual behavior
You will notice the location is not shown correctly since the icon is displayed at 0,0
![image](https://user-images.githubusercontent.com/5824180/40497288-23a3dbd8-5f7c-11e8-91fb-5dc29a1f6e52.png)

**Comment by olsisaqe** [comment]
Also i think the location icon is bigger than `14 dp` specified here: https://github.com/mapbox/mapbox-plugins-android/blob/752c368aec643d408a538283545bf539849fc04f/plugin-locationlayer/src/main/res/drawable/mapbox_user_icon.xml#L3

**Comment by tobrun** [comment]
Thank you for the report @olsisaqe, this repo is used to report issues related to the Mapbox Maps SDK for Android and the underlying render engine. For issues that are related to plugins, please report them [here](https://github.com/mapbox/mapbox-plugins-android).

**Comment by olsisaqe** [comment]
thanks @tobrun . Following [here](https://github.com/mapbox/mapbox-plugins-android/issues/540)
