### ISSUE TITLE
Mapbox SDK slow while downloading offline region

### ISSUE THREAD

**Issue by diegolaballos** [mapbox/mapbox-gl-native#12008]
**Platform:** Android
**Mapbox SDK version:** 5.4.0

**Issues:**

1. While downloading an offline region through the OfflineManager, a call to OfflineManager.listOfflineRegions takes more than 3 seconds. Usually, if there is no ongoing download, it takes less than 1 second.

2. While downloading an offline region, maps take more than 5 seconds to load the tiles. Also, the first 1-2 seconds, the map view shows in black.

**Comment by tobrun** [comment]
Thank you for reaching out and reporting this issue @diegolaballos , sadly this behavior has already been ticketed in https://github.com/mapbox/mapbox-gl-native/issues/11461 and I will need to close this as a duplciate. Thanks you for using our products!
