### ISSUE TITLE
Tilting and zooming to boundaries at the same time not possible

### ISSUE THREAD

**Issue by stoefln** [mapbox/mapbox-gl-native#12019]
**Platform:** 
Android
**Mapbox SDK version:**
6.0.? (installed as dependency of location layer plugin 0.5.2)

I need a way of tilting and zooming to boundaries at the same time. Currently I am doing the zoom via `mapboxMap.easeCamera(CameraUpdateFactory.newLatLngBounds` and the tilting via `mapboxMap.animateCamera(CameraUpdateFactory.newCameraPosition(position)`
One call cancels the other one. Of cause I could execute the calls sequentially, but due to our quite complex app logic we would easily end up in callback hell.

Any way of doing both in parallel?

**Comment by LukasPaczos** [comment]
To achieve two separate animations running in parallel you can leverage Android Animators and call `MapboxMap#MoveCamera` on each step of the animation, separately for the bounds and tilt.
Noting, that this prevents `#onCameraMove` callbacks from being dispatched for the animations and you'd have to handle the logic yourself.

Closing as answered, let us know if you have any more questions.
