### ISSUE TITLE
Telemetry is not completely disabled

### ISSUE THREAD

**Issue by rooholam** [mapbox/mapbox-gl-native#12015]
**Platform: android
**Mapbox SDK version: 6.0.1

### Steps to trigger behavior

 1. Disable telemtry using: TelemetryEnabler.updateTelemetryState(TelemetryEnabler.State.DISABLED)
 2. Launch the android app with a MapView

### Expected behavior
It is expected that Telemetry won't send any event to server.

### Actual behavior
By starting the mapview an event is sent to "events.mapbox.com" 
This might be because of this line of code: https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java#L277

![wireshark-screenshot](https://user-images.githubusercontent.com/13508039/40574406-79404390-60e6-11e8-85a4-b7525334099a.png)

**Comment by tobrun** [comment]
Capturing from @zugaldia that above shown event is the turnstile event and it's expected to be always sent on map creation, this also includes when the end user opts out of telemetry (data is different as normal telemetry collection). cc @electrostat
