### ISSUE TITLE
Marker not visible sometime after move camera in android

### ISSUE THREAD

**Issue by kinDSa** [mapbox/mapbox-gl-native#12017]
Hello,
I am showing marker on map. when I use (**map.moveCamera()** or **map.easeCamera()**, or **map.animateCamera()**)  any method map doesn't show marker. Currently camera move to correct position but marker visible sometime. If  touching or moving map then marker visible. 

I have tried following thing but not get accepted result:
1) MapboxMap.getMarkerViewManager().invalidateViewMarkersInVisibleRegion() in the onFinish() of the animateCamera callback.

**Comment by tobrun** [comment]
@kinDSa thank you for reaching out and reporting your problem. We will need a bit more information to look into this issue:
 - which version of the SDK are you using?
 - which kind of marker (Marker.java/MarkerOptions.java)?

**Comment by kinDSa** [comment]
I am using SDK version **6.0.1**.  For showing marker used **MarkerViewOptions**. In marker I have set drawble  icon.

**Comment by tobrun** [comment]
MarkerViewOptions is deprecated and will not receive any further updates. Please move towards a SymbolLayer,java (many options/more difficult api) or Marker.java (simple but limited) approach. An example of SymbolLayer can be found [here](https://blog.mapbox.com/a-guide-to-the-android-symbollayer-api-5daac7b66f2c). We are currently working on improving the API arounds Markers.
