### ISSUE TITLE
Parameter order for SAM interface for CustomGeometrySource

### ISSUE THREAD

**Issue by mkrussel77** [mapbox/mapbox-gl-native#12010]
**Platform:** Android
**Mapbox SDK version:** 6.1.1

The current parameter order the CustomGeometrySource makes it harder to use with Kotlin.

` public CustomGeometrySource(String id, GeometryTileProvider provider, CustomGeometrySourceOptions options)`

Would be nicer as 

` public CustomGeometrySource(String id, CustomGeometrySourceOptions options, GeometryTileProvider provider)`

This is Googles recommendation for making Java libraries more Kotlin friendly.

https://android.github.io/kotlin-guides/interop.html#lambda-parameters-last

Minor issue, but a change to consider with the next major release.  Or deprecating the current constructor and adding a new constructor.

**Comment by tobrun** [comment]
Landed in #13178 on `android-semver`
