### ISSUE TITLE
how to add padding to marker?

### ISSUE THREAD

**Issue by Kaspisijus** [mapbox/mapbox-gl-native#12016]
Hello,

In Android SDK documentation it is said:

> The anchoring of the marker will be in the center, meaning if you have an icon with a point, you'll need to add padding to the bottom of the image.

Making image height twice bigger (adding extra transparent space at the bottom) lifts the marker to correct position, but the empty bottom of the marker is still clickable, which I don't want to happen.
![screenshot_2](https://user-images.githubusercontent.com/33354414/40601176-c78a670c-625c-11e8-867f-f0626468e277.png)

Is there a way to add padding without making the image bigger?

**Comment by LukasPaczos** [comment]
Thanks for reaching out @Kaspisijus. You can experiment with properties like `PropertyFactory#iconTranslate`, `PropertyFactory#iconTranslateAnchor`, `PropertyFactory#iconOffset` and `PropertyFactory#iconAnchor` to get the desired symbol placement.
