### ISSUE TITLE
ios: Support custom NSURLProtocol

### ISSUE THREAD

**Issue by sebastianludwig** [mapbox/mapbox-gl-native#12026]
**Platform: iOS**
**Mapbox SDK version: 4.0**

Based on the discussion in #3597. 

To modify the HTTP request headers or, in general, handle all sorts of remote requests, it's desirable to be able to use custom `NSURLProtocol` implementations.  For this to work, we'd need a way to add `NSURLProtocol` classes to `NSURLSessionConfiguration.protocolClasses` ([as described here](https://stackoverflow.com/questions/28705534)). 

How would we go about this? A delegate call? A class property?

I'm unfamiliar with the codebase but this is as I understand it so far:
1. The `NSURLSession` is created in `HTTPFileSource::Impl()` in [`darwin/src/http_file_source.mm`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/http_file_source.mm#L84-L89)
1. This is instantiated by `DefaultFileSource::Impl()` in [`platform/default/default_file_source.cpp`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/default/default_file_source.cpp#L21)
1. which is called by `SDKOfflineStorage-init` in [`SDK/Foundation/Offline Maps/SDKOfflineStorage.mm`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/MGLOfflineStorage.mm#L214) (real path is `darwin/src/MGLOfflineStorage.mm`)
1. This initialization happes due to `[MGLOfflineStorage sharedOfflineStorage].mbglFileSource` being accessed in
1. `MGLRendererConfiguration.fileSource` in [`SDK/Foundation/MGLRendererConfiguration.mm`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/MGLRendererConfiguration.mm#L18) (also `darwin/src/`)
1. accessed in `MGLMapView-commonInit` in [`SDK/Kit/MGLMapView.mm`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/src/MGLMapView.mm#L418) (`ios/src/`)

So, MapView -> Renderer -> Offline Storage -> Default File Source -> HTTP File Source.

`SDKOfflineStorage` and `MGLMapView` do have delegates, but we can't use either because `HTTPFileSource::Impl()` is called during their initialization. We could add an additional parameter to an `MGLMapView-init` variation. However that would require to pass it through `platform/`**`default`**`/default_source_file.cpp`, which is undesirable, I guess. The only option I see would be a class property on...some class. `HTTPFileSource` doesn't have a ObjC pendant yet. Could we add one? Or have it access some other global state thing?

The Android solution is implemented in #10948. Would the equivalent be to have `SDK/[Foundation|Kit]/MGLHTTPRequestUtil.{h,mm}` and access that in `HTTPFileSource::Impl()`?

Edit: Is it even possible to access anything in the SDK part from the platform part?

I'm pretty much lost here. Any thoughts, @1ec5? Could you point me in a direction?

Also, are fonts/glyphs downloaded via the same mechanism?

**Comment by sebastianludwig** [comment]
Having thought about it a little bit more, I think it'd be best if it'd be possible to provide the whole `NSURLSessionConfiguration`. 

Still no clue how to go about this, though oO [ARCHITECTURE.md](https://github.com/mapbox/mapbox-gl-native/blob/master/ARCHITECTURE.md) affirms my understanding that the SDK uses and accesses the C++ core, not the other way around. Could we have a `NSURLSessionConfiguration` setter on...`MGLOfflineStorage` that somehow accesses the used `HTTPFileSource::Impl` and passes the given value through? `HTTPFileSource::Impl` would then need to re-initialize its `session`.

**Comment by Woody4618** [comment]
Would be really nice to have this.

**Comment by 1ec5** [comment]
> Is it even possible to access anything in the SDK part from the platform part?

No, because the SDK is intended to be compatible with pure Objective-C projects, whereas mbgl’s public API is entirely in C++.

> the SDK uses and accesses the C++ core, not the other way around

This is true for the most part. mbgl does have [some platform-specific Objective-C++ code](https://github.com/mapbox/mapbox-gl-native/blob/561fa249a7130f0eed320188b649ed4ba6a8cc55/platform/darwin/src/http_file_source.mm) at the very lowest level for working with NSURLSession.

@kkaefer, do you think we could expose a way for developers to customize NSURLSessionConfiguration? I think this would be one important step towards resolving #4291 as well.

/cc @julianrex

**Comment by julianrex** [comment]
I think it's also worth looking at what's happening over in the Android version re customizing networking.

**Comment by sebastianludwig** [comment]
This might be a way to go forward: https://github.com/mapbox/mapbox-gl-native/pull/13491

**Comment by friedbunny** [comment]
Stay open, plz.

**Comment by sebastianludwig** [comment]
@fabian-guerra is there a label we can add so the stale bot [ignores it](https://github.com/apps/stale)? (and remove the "archived" label)

**Comment by friedbunny** [comment]
Still, stalebot seems to be malfunctioning — unsure why it’s trying to continually close issues after mere hours of inactivity. /cc @tmpsantos

**Comment by fabian-guerra** [comment]
I'm going to assign this for now.

**Comment by tmpsantos** [comment]
> Still, stalebot seems to be malfunctioning — unsure why it’s trying to continually close issues after mere hours of inactivity. /cc @tmpsantos

It is because the label `archived` was not removed. The bot will mark as `archived` after detecting the inactivity and then close.

**Comment by BenderNK** [comment]
Hello @fabian-guerra - I realize this issue was just closed. Is there a ticket to allow for similar customizations on the Android side?
