### ISSUE TITLE
less sequential bucket parsing

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#1202]
From what I can tell -native parses all buckets in order. It only finds out it needs glyphs when it starts parsing the bucket that needs them. While loading glyphs it blocks all other buckets.

In -js bucket parsing is less sequential:
- it starts downloading missing glyphs asap instead of waiting to reach the bucket
- it can parse other buckets while waiting for glyphs to download

https://github.com/mapbox/mapbox-gl-js/blob/f9198c34b59c680cd97a4e4fc76b7133438c9ec9/js/source/worker_tile.js#L128-L135

Async operations are started asap.
If there is work it could do now, it does it instead of waiting.

For example with these four buckets:

- LineBucket A
- SymbolBucket B that needs glyph range 0
- FillBucket C
- SymbolBucket D that needs glyph range 1

In native it would work like this:
- parse A
- parse B. start loading range 0. wait until range 0 downloads. finish B.
- parse C
- parse D. start loading range 1. wait until range 1 downloads. finish D.

In -js with less sequential parsing:
- check B and start loading range 0.
- check D and start loading range 1.
- parse A
- parse C
- wait until range 0 finishes downloading. parse B.
- wait until range 1 finishes downloading. parse D.

**Comment by mb12** [comment]
@ansis  What is wrong with this approach? For western languages this would just mean a single request for range 0-255.  After that no requests will be made.
Does js start rendering fill and line buckets even before all symbol buckets are ready?

**Comment by ansis** [comment]
@mb12 You're right that it might not be that significant. The benefits might not be worth the complexity this would add. If it isn't worth it, we should change -js to more sequential parsing.

> For western languages this would just mean a single request for range 0-255. After that no requests will be made.

Yes, but areas with glyphs in many ranges often need to download new glyph ranges for new tiles. Since the ranges are cached, less sequential loading would only help the first time.

> Does js start rendering fill and line buckets even before all symbol buckets are ready?

No, but if it can download the glyphs while parsing other buckets the entire tile will be ready sooner.

**Comment by kkaefer** [comment]
refs https://github.com/mapbox/mapbox-gl-native/issues/925

**Comment by mourner** [comment]
In practice, symbol buckets are placed after all fill/line buckets in our styles, so it won't be significant.

**Comment by kkaefer** [comment]
I think this is a valid concern; we should probably split up tile parsing in two parts; first it should determine all prerequisites, then parse the actual tile. This is also the path to fixing https://github.com/mapbox/mapbox-gl-native/issues/925

**Comment by jfirebaugh** [comment]
@tmpsantos Is this fixed?

**Comment by tmpsantos** [comment]
@jfirebaugh should be fixed by https://github.com/mapbox/mapbox-gl-native/pull/1539
