### ISSUE TITLE
Expression not(has("property_name")) not working

### ISSUE THREAD

**Issue by Jukurrpa** [mapbox/mapbox-gl-native#12020]
**Platform: Android**
**Mapbox SDK version: 6.1.3**

When I build a layer filter for "doesn't have property_name" using `Expression` factory methods `Expression.not(Expression.has("property_name"))`, the filter doesn't seem to be working as all features are still displayed, regardless of whether they have the property or not.

Building the "not has" manually with `Expression("!has", Expression.literal("property_name"))` does work as expected. So it's not a major issue but I'd like to avoid hardcoding operators and would rather rely on factory methods.

**Comment by tobrun** [comment]
@Jukurrpa thank you for reaching out and reporting your issue.

Did a quick test locally using [this](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java) Activity and currently unable to reproduce:

![ezgif com-video-to-gif 16](https://user-images.githubusercontent.com/2151639/40654455-b062f37c-633e-11e8-9910-159ff14352a2.gif)

The changes I made to the code is add the following in `onDataLoaded`:

```
    Feature feature = featureCollection.features().get(0);
    Timber.e("Feature "+feature.getStringProperty(FEATURE_ID));
    feature.addNumberProperty("hello", 9);
    featureCollection.features().set(0, feature);
```

and afterwards setup the filter:

```
    symbolLayer.setFilter(has("hello"));
```

Wrapping above with a not expression results in the reverse/correct behaviour:

![image](https://user-images.githubusercontent.com/2151639/40654578-fcc6144c-633e-11e8-83e6-bc9601cdd075.png)

Any information to help troubleshoot is highly appreciated.

**Comment by Jukurrpa** [comment]
Could it be related to the type of the source? Applying the `not(has())` version on a layer whose source is a `GeoJsonSource` works on my end, but not on the layers using a `VectorSource`

**Comment by Jukurrpa** [comment]
Issue turned out to be the same as for #12270 (combining deprecated filters and expressions)
