### ISSUE TITLE
Cannot change style twice in offline

### ISSUE THREAD

**Issue by dotPilot** [mapbox/mapbox-gl-native#12032]
I need to switch my app to night mode and back at offline, so I change style to Dark and call
```
mMapboxMap.setStyleUrl(STYLE_URL_NIGHT);
AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);
recreate();
```
In offline if Dark style was not loaded, Day style remains visible on a map, but if try to change it back to Day style then map dissappers. 
Are there any way to check if style is cached and preload it?
Same behavior can be reproduced in Mapbox Demo App :
```
com.mapbox.mapboxandroiddemo.debug E/UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.MapboxMap.setStyleUrl(java.lang.String)' on a null object reference
                                                                                         at com.mapbox.mapboxandroiddemo.examples.styles.DefaultStyleActivity.onOptionsItemSelected(DefaultStyleActivity.java:106)
```
![giphy](https://user-images.githubusercontent.com/12918725/40720461-3fc7e0c6-6430-11e8-854d-7975f28df83a.gif)

**Comment by tobrun** [comment]
You can cache styles by downloading an offline region with them or packaging them with your app. 
This way they will be always ready available. Let us now if you have any additional questions, Closing as answered.
