### ISSUE TITLE
Support other projection rather than 3857

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-native#12030]
In mapbox-gl-js it is the `src/geo/transform.js` which handling all the geo-transforming (like lng,lat to point and reverse), so we could change the `transfrom.js` to support different project instead of `EPSG:3857`.

However in mapbox-gl-native I can find the transforming codes everywhere, for example the `include/utile/projection.hpp`, however the `project` method inside this file is not called at all during my debugging.

So which should be customized if I want to support other projection?

**Comment by jfirebaugh** [comment]
Hi @exotfboy -- custom projections isn't really a feature that can be implemented by changing a few functions. It will require quite some work throughout the ecosystem. We're tracking this in https://github.com/mapbox/mapbox-gl-js/issues/3184.

**Comment by PierreLacroix** [comment]
Hi,
I am really impressed by all the functions that Mapbox GL supports. However it would be great if it vould support other projections than Mercator.
Is it foreseen to develop this?
Thanks for the answer

**Comment by Svensl** [comment]
Hi all,
Sifting through the issues, I believe the first request/wish for this was formulated on June 21st 2016 with "WIP - support for non-mercator projections #1466"
Now we all love MapBox, but we would love it even more if it allowed for non mercator projections no?
Any news about this? We are more and more GIS users out there from many different CRSs and it is becoming increasingly useful to enable non mercator projections.
Cheers!

**Comment by samFredLumley** [comment]
Is there any update on this discussion? Or any non-hacky solutions out there for displaying global data without Mercator on a web map?

**Comment by Luooooooo** [comment]
now dose it support other projection?
