### ISSUE TITLE
Pin (annotation) image is shown pixelated with the wrong resolution :(

### ISSUE THREAD

**Issue by AEiosApp** [mapbox/mapbox-gl-native#12048]
I wasn't able to find a way to get my custom pin image on the map with a high resolution. (I'm telling about MapBox iOS SDK).

Usually, this may occur in Xcode when the UIImage size is equal to *.png size. I've tried to prepare 3x scaled *.png file and resize my UIImage object, but still getting low-resolution image on the screen. Any ideas?

Mapbox SDK for iOS version 4.0.2

Same pin images worked fine (were shown with a high resolution) when I previously used standard library MapKit.

![image](https://user-images.githubusercontent.com/19554725/40849657-360e9a88-65cb-11e8-8fea-c2dd285a1b73.png)

**Comment by julianrex** [comment]
Thanks for reporting this @AEiosApp. Are you able to provide a minimal sample project that demonstrates this issue?
