### ISSUE TITLE
Android polygon incorrect FillColor

### ISSUE THREAD

**Issue by psinetron** [mapbox/mapbox-gl-native#12047]
mapbox-android-sdk:6.1.3

I add polygon with my fill color:
```
mapBox?.addPolygon(PolygonOptions()
                            .addAll(points)
                            .fillColor(Color.parseColor("#FFFF0000")) //Red color
                            .strokeColor(Color.parseColor("#FFFF0000")) //Red color
```

Polygon was added but fill color is not Red. Fill color is light blue and stroke color is white. Why?

**Comment by LukasPaczos** [comment]
Thanks for reaching out @psinetron. Unfortunately, I wasn't able to reproduce the issue using below code:
```
    mapView.getMapAsync(new OnMapReadyCallback() {
      @Override
      public void onMapReady(MapboxMap mapboxMap) {
        mapboxMap.addPolygon(new PolygonOptions()
          .add(
            new LatLng(50, 16),
            new LatLng(51, 16),
            new LatLng(51, 16.5),
            new LatLng(50, 16))
          .fillColor(Color.parseColor("#FFFF0000")) //Red color
          .strokeColor(Color.parseColor("#FFFF0000"))); //Red color)
      }
    });
```
![device-2018-06-01-175448](https://user-images.githubusercontent.com/16925074/40850614-68993cca-65c5-11e8-93fa-e5de67c7f39f.png)

Would you mind providing a little more context? Are there any other manipulations performed on those polygons?
