### ISSUE TITLE
After adding location on map and click on annotation no annotation view appears

### ISSUE THREAD

**Issue by bDivergent** [mapbox/mapbox-gl-native#12056]
**Platform:**
IOS 9.X ->

**Mapbox SDK version:**
4.X ->

### Steps to trigger behavior

 1. Clean map add notion static or dynamic
 2. Click on annotation

### Expected behavior
After adding annotation and clicking on it annotation view should appear.
I use both functions 'viewFor annotation' and 'annotationCanShowCallout'

### Actual behavior
But most of the time nothing happens, no annotation view shows up.
After zoom in/out a little or moving/panning the map clicking the annotation the annotation view
does appear.
In the demo i display locations from server and place them on the map. When moving
the map around I get outside a radius of 2km and remove all earlier placed annotations.
Then I read new locations from server and place them on the map.
I can do that back and forth. It makes no difference.
Sometimes I do get a annotation view and sometimes not.
I used a basic sample from Mapbox and added my fetching location function.
Also tried a app from GitHub that did the same thing adding/removing annotations. That app
reacted the same.
[demo.mov.zip](https://github.com/mapbox/mapbox-gl-native/files/2067555/demo.mov.zip)

> 	func fetchLocations() {
		
		if mapView.annotations?.count != nil, let existingAnnotations = mapView.annotations {
			mapView.removeAnnotations(existingAnnotations)
		}
		
		let parameters_value: Parameters = ["category": filter,
											"radius": radius,
											"latitude": arrivedLocation.coordinate.latitude,
											"longitude": arrivedLocation.coordinate.longitude]
		
		Alamofire.request(serverLocation, method: .post, parameters: parameters_value).responseJSON {
			response in
			
			if let dictionary = response.result.value as? [AnyHashable: Any] {
				let array = dictionary["locations"] as! [[String: Any]]
				let userLocation = CLLocation(latitude: (self.mapView.userLocation?.coordinate.latitude)!, longitude: (self.mapView.userLocation?.coordinate.longitude)!)
				
				self.pointAnnotations = [MGLPointAnnotation]()
				
				for result in array {
					
					let header = result["header"] as! String
					let latitude = result["latitude"]as! Double
					let longitude = result["longitude"] as! Double
					
					let annotation = LocationObjects(identifier: identifier,
													 header: header,
													 lat: latitude,
													 long: longitude)
					
					let point = MGLPointAnnotation()
					point.coordinate = CLLocationCoordinate2D(latitude: annotation.coordinate.latitude, longitude: annotation.coordinate.longitude)
					
					point.title = annotation.Header
					point.subtitle = annotation.Address
					self.pointAnnotations.append(point)
				}
				self.mapView.addAnnotations(self.pointAnnotations)
			}
			
		}
		
	}

>

**Comment by bDivergent** [comment]
Yes it looks very alike, except it happens now in IOS.
Hope it can be solved (soon)🤔

**Comment by chrisballinger** [comment]
This issue should be reopened - this is still a problem on the latest SDK version (5.2.0).
