### ISSUE TITLE
[Android] UI thread checking in android-v6.2.0

### ISSUE THREAD

**Issue by ychescale9** [mapbox/mapbox-gl-native#12054]
**Platform:** Android
**Mapbox SDK version:** android-v6.2.0-beta.1

Version 6.2 now enforces `setGeoJson(...)` to be called from the main thread.
I understand based on [previous discussions](https://github.com/mapbox/mapbox-gl-native/issues/11414) that these operations should not be run from the background thread and that rendering large maps blocks the main thread is a [known issue](https://github.com/mapbox/mapbox-gl-native/issues/8484).

What would be your recommended approach for projects that are already using background thread to call `setGeoJson(...)` to workaround the performance issue going forward? Thanks.

**Comment by tobrun** [comment]
Thank for reaching out @ychescale9 , updating a GeoJsonSource from a worker thread is not supported and can result in crashes. As flagged, we are aware of the performance around this and will be tackling it as part of https://github.com/mapbox/mapbox-gl-native/issues/8484.

If you need to dynamically change the underlying geometry of a source with calculating that geometry on a workerthread. You can do this with a `CustomGeometrySource` and the `GeometryTileProvider`. The latter component will be executed on a worker thread:

```java
/**
 * Interface that defines methods for working with {@link CustomGeometrySource}.
 */
public interface GeometryTileProvider {

  /***
   * Interface method called by {@link CustomGeometrySource} to request features for a tile.
   *
   * @param bounds {@link LatLngBounds} of the tile.
   * @param zoomLevel Tile zoom level.
   * @return Return a @{link FeatureCollection} to be displayed in the requested tile.
   */
  @WorkerThread
  FeatureCollection getFeaturesForBounds(LatLngBounds bounds, int zoomLevel);
}
```
Closing this issue, follow up will happen in https://github.com/mapbox/mapbox-gl-native/issues/8484.
