### ISSUE TITLE
No callout after removing and adding annotations

### ISSUE THREAD

**Issue by Sandiryakov** [mapbox/mapbox-gl-native#12057]
**Platform:**
iOS 11

**Mapbox SDK version:**
4.0.2

### Steps to trigger behavior

 1. Make a map with annotation and callout inside UITabBarController
 2. Add code to remove and add annotation in viewWillAppear
 3. Run app and tap annotation. Callout shows up as expected
 4. Switch to another tab and then back to the map
 5. Tap annotation again

### Expected behavior
Callout shows up

### Actual behavior
No callout is shown

### Additional Info
If you zoom map callouts begin to show up

### Source code

```
import Mapbox

class ViewController: UIViewController, MGLMapViewDelegate {
    
    var mapView: MGLMapView!
    var annotation = MGLPointAnnotation()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        mapView = MGLMapView(frame: view.bounds)
        mapView.setCenter(CLLocationCoordinate2D(latitude: 40.74699, longitude: -73.98742), zoomLevel: 9, animated: false)
        view.addSubview(mapView)
        mapView.delegate = self
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        mapView.removeAnnotation(annotation)
        annotation = MGLPointAnnotation()
        annotation.coordinate = CLLocationCoordinate2D(latitude: 40.77014, longitude: -73.97480)
        annotation.title = "Central Park"
        mapView.addAnnotation(annotation)
    }
    
    func mapView(_ mapView: MGLMapView, annotationCanShowCallout annotation: MGLAnnotation) -> Bool {
        return true
    }
}
```

**Comment by julianrex** [comment]
@Sandiryakov thanks for the bug report.

**Comment by fabian-guerra** [comment]
This may be related to https://github.com/mapbox/mapbox-gl-native/issues/12056

**Comment by Lavmint** [comment]
Hi, I have same/similar issue. It seems that after remove/add annotation map doesn't recognise tap on annotationView. However you can invoke mapView.selectAnnotation and it'll be selected. So I'm thinking that the problem relates to determine tap region for handling.

**Comment by chrisballinger** [comment]
I am also experiencing this problem.

**Comment by chrisballinger** [comment]
Hey, I wanted to say that I am still experiencing this issue as of the latest SDK version a year later. This issue should be reopened.
