### ISSUE TITLE
Adopt Dark Mode

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#12058]
When [Dark Mode](https://developer.apple.com/documentation/appkit/supporting_dark_mode_in_your_interface) is active, perhaps MGLMapView should automatically replace the Light style with the Dark style.

/ref #9859

**Comment by 1ec5** [comment]
Overheard at WWDC.

**Comment by friedbunny** [comment]
_Moved from https://github.com/mapbox/mapbox-gl-native/issues/14876..._

iOS 13 adds [dark mode](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/dark-mode/) — the good news is that we should mostly get for it for free.

In preliminary testing, I’ve noticed a couple areas we’ll want to tweak:

- The user location annotation’s white outer ring might need to become a bit darker when dark mode is enabled.
- When using a named color that has different colors defined for Any/Light/Dark is used as the tint, the user location annotation can revert to the Any variant when you switch from the dot to the course puck.

**Comment by friedbunny** [comment]
> perhaps MGLMapView should automatically replace the Light style with the Dark style.

I see this sort of feature as something a developer should consider implementing in their app, but I don’t think it’d be appropriate for the SDK. We could definitely do an example, though.

**Comment by julianrex** [comment]
I think it's worth us thinking about how semantic colours might work in the style spec.

**Comment by 1ec5** [comment]
Resources for iOS/macOS:

* [Supporting Dark Mode in Your Interface](https://developer.apple.com/documentation/appkit/supporting_dark_mode_in_your_interface) – concise, illustrated guide
* [UI Element Colors](https://developer.apple.com/documentation/uikit/uicolor/ui_element_colors) – for UIColor in UIKit on iOS
* [UI Element Colors](https://developer.apple.com/documentation/appkit/nscolor/ui_element_colors) – for NSColor in AppKit on macOS
* [Implementing Dark Mode on iOS](https://developer.apple.com/videos/play/wwdc2019/214/) – WWDC session video

In case a cross-platform solution is desired:

* [Dark theme on Android](https://developer.android.com/preview/features/darktheme)
* [`prefers-color-scheme` media query in CSS](https://discourse.wicg.io/t/proposal-a-color-theme-media-query-and-system-colors/2844/7)
* [System colors in CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#System_Colors)
