### ISSUE TITLE
android add layer cannot display chinese

### ISSUE THREAD

**Issue by yalongGuo-0** [mapbox/mapbox-gl-native#12055]
textLayer.withProperties(
                            PropertyFactory.textField("{land_name}"),
                            PropertyFactory.textSize(10f),
                            PropertyFactory.textColor(getResources().getColor(R.color.text_white))
                    );
                    mMap.addLayer(textLayer);

**Comment by lilykaiser** [comment]
Hi @yalongGuo-0 can you provide more information? Does your code work if the values for land_name are in English?

**Comment by yalongGuo-0** [comment]
com.mapbox.mapboxsdk:mapbox-android-sdk:5.5.0@aar
mapbox sdk version
land_name value chinese don't display
but number and letter can display

**Comment by yalongGuo-0** [comment]
Can you tell me?Which version is more stable?

**Comment by macro-shen** [comment]
Hi @yalongGuo-0 5.5.0 SDK should be OK. You may also try 6.1.x. 
1. Could you make sure there are Chinese text in **land_name** of geojson data? 
2. And how do you set glyphs in style json file?

**Comment by tobrun** [comment]
Closing as stale, feel free to reach out if this is still an issue! 
Thank you for reaching our products!
