### ISSUE TITLE
Android. v6.3.1. Where is mapboxsdk.style.functions in 6.3.1?

### ISSUE THREAD

**Issue by psinetron** [mapbox/mapbox-gl-native#12066]
I make application from sample https://blog.mapbox.com/a-guide-to-the-android-symbollayer-api-5daac7b66f2c

This code have a Function from com.mapbox.mapboxsdk.style.functions:

```
mapboxMap.addLayer(myLayer)
  .withProperties(
    iconImage("{poi}-15"),
    PropertyFactory.iconSize(
      Function.property(
        "selected",
        Stops.categorical(
          Stop.stop(true, PropertyFactory.iconSize(1.5f)),
          Stop.stop(false, PropertyFactory.iconSize(1.0f))
        )
      )
    )
  )
);
```

But I can't find this library in mapboxsdk.style.  Where is it?

gradle:
`implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.3'`

**Comment by tobrun** [comment]
the old dds function api was replaced with a more flexible expression api, see the migration guide for more information in https://github.com/mapbox/mapbox-gl-native/wiki/Android-5.x-to-6.x-migration-guide#using-expressions-vs-functions--filters. The source code for the blog post can be found here and is updated to 6.x syntax. Note though there are some issues with it in https://github.com/mapbox/mapbox-android-demo/issues/737.
