### ISSUE TITLE
Android: 6.1.3 dynamically marker icon change. Question

### ISSUE THREAD

**Issue by psinetron** [mapbox/mapbox-gl-native#12067]
I create markers like in demo app.
When I create a feature I add a boolean property **selected** like this:

```
val feature = Feature.fromGeometry(Point.fromLngLat(dataBuilding.longitude, dataBuilding.latitude))
                    feature.addStringProperty("block_id", dataBuilding.id)
                    feature.addBooleanProperty("selected", true)
```

Then I create layer with Expression at iconImage property:
```
val blockMarkersLayer = SymbolLayer("block-markers-layer", "block-markers-source")
.withProperties(PropertyFactory.iconImage(
                            Expression.match(
                                    Expression.get("selected"),
                                    Expression.literal("unselected-marker"),
                                    Expression.stop(true, "selected-marker"),
                                    Expression.stop(false, "unselected-marker"))))
```
But all markers haven't any icons.
 
And when I change Expression to zoom changing it work perfectly:
```
val blockMarkersLayer = SymbolLayer("block-markers-layer", "block-markers-source")
.withProperties(PropertyFactory.iconImage(
                            Expression.step(Expression.zoom(), 
                                    Expression.literal("unselected-marker"), 
                                    Expression.stop(12.0f, "selected-marker"))))
```

Where is the mistake?

**Comment by tobrun** [comment]
Capturing from the style specification [here](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-match):

>Selects the output whose label value matches the input value, or the fallback value if no match is found. The input can be any string or number expression (e.g. ["get", "building_type"]). Each label can either be a single literal value or an array of values.

The input type must be a string or number, I'm advising to move towards [swtichCase](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-case) instead. Fwiw, if an expression doesn't "work" it will print out a log message indicating what is wrong. 

Let us know if you have any others questions!

**Comment by psinetron** [comment]
Sorry, but I don't understand how to work switchCase. Wow to use input value in my case?

**Comment by Gary111** [comment]
@psinetron, too late, but maybe it will help someone. You forgot add fallback expression as last param for `match`.

Documentation says
> ...
> If types of the input and keys don't match, or the input value doesn't exist, the expresion will fail without falling back to the default value

`Match` expression
```
PropertyFactory.iconImage(
    Expression.match(
            Expression.get("selected"), //getting property or null
            Expression.literal("true"), Expression.literal("selected-marker"), // if true
            Expression.literal("unselected-marker") // else
    )
)
```

`SwitchCase` expression
```
PropertyFactory.iconImage(
    Expression.switchCase(
            Expression.get("selected"), //getting property or null
            Expression.literal("selected-marker"), // if true
            Expression.literal("unselected-marker") // else
    )
)
```
