### ISSUE TITLE
Dissolve cluster to bounding box of clustered items

### ISSUE THREAD

**Issue by cleemansen** [mapbox/mapbox-gl-native#12069]
**Platform:** android
**Mapbox SDK version:** 6.1.1

_This is more a question/feature-request than an issue!_ I will explain it based on the mapbox-android-demo-app:

### Steps to trigger behavior

 1. Start the mapbox-android-demo-app
 2. Navigate to the example "Style" > "Create and style data clusters"
 3. Touch on a cluster-icon

### Expected behavior

- the cluster will be dissolved (zoom in until all single items clustered by the clicked icon are visible)

### Actual behavior

- I know already I can query if I touched a cluster icon via `mMapboxMap.queryRenderedFeatures(screenPoint, clusterLayerId);`. But the returned feature doesn't contain any information about the single items clustered by that feature.

Thanks in advice!

**Comment by cleemansen** [comment]
Any ideas how I can get the bounding box of all included items of the clicked cluster?

**Comment by F0rc0sigan** [comment]
I want to achieve same thing. Is there any way to do cluster disolving?

**Comment by tobrun** [comment]
Thanks for reaching out, we are adding an option to the sdk in https://github.com/mapbox/mapbox-gl-native/issues/12441 which will allow you to query a geojson source (if it's a cluster) to get the zoom level at which a cluster would dissolve. (additionally you can also query the contents of a clustered item).

**Comment by cleemansen** [comment]
Thank you for this feature :)

An entry point for everybody to use it is: 
- https://docs.mapbox.com/android/api/map-sdk/7.1.2/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.html#getClusterExpansionZoom-Feature-
- IMHO best to work w/ an bounding-box of the children via https://docs.mapbox.com/android/api/map-sdk/7.1.2/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.html#getClusterChildren-Feature-
