### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_MGLMapPointForCoordinate"

### ISSUE THREAD

**Issue by datwelk** [mapbox/mapbox-gl-native#12079]
Calling `MGLMapPointForCoordinate` anywhere in an application linked against Mapbox, results in a linker error.

**Platform:**
iOS
**Mapbox SDK version:**
4.0.2

### Steps to trigger behavior
 1. Download the iOS sample project (https://github.com/mapbox/ios-sdk-examples)
 2. Run pod install
 3. In AppDelegate.m, add the following line within `application:didFinishLaunchingWithOptions:`:
```MGLMapPointForCoordinate(kCLLocationCoordinate2DInvalid, 0);```
 4. Build the app

### Expected behavior
The build succeeds, with no errors.

### Actual behavior
The build fails with the following linker error:
Undefined symbols for architecture x86_64:   "_MGLMapPointForCoordinate"

**Comment by 1ec5** [comment]
@julianrex pointed out that `MGLMapPointForCoordinate()` is used only in a unit test but not elsewhere in the framework; perhaps the function has been optimized away when built as part of `make ipackage`.

**Comment by friedbunny** [comment]
@datwelk thanks for reporting this issue. The `MGLMapPointForCoordinate()` method is perhaps deceivingly named and inadequately documented — if you’re looking to convert between screen and map coordinates, something like [this example](https://github.com/mapbox/ios-sdk-examples/blob/7f4545d2a96b8394b9246bf058a026a4ed016e13/Examples/ObjectiveC/PointConversionExample.m) is more useful/appropriate.

**Comment by datwelk** [comment]
Thanks @friedbunny but I was looking for conversion from lat/long (WSG84 / EPSG 4326) to X,Y (EPSG 3857)
