### ISSUE TITLE
iPhone 4s and 5 Simulator doesn't render map labels

### ISSUE THREAD

**Issue by nole87** [mapbox/mapbox-gl-native#12070]
**Platform:** iOS
**Mapbox SDK version:** 4.0.2

### Steps to trigger behavior

 1. Run any app with mapbox SDK for iOS on iphone 4s or 5 simulator no matter of iOS version

### Expected behavior
Maps should have text labels

### Actual behavior
Text labels are black without texts
![4s](https://user-images.githubusercontent.com/4254736/41047907-e2524e62-69ad-11e8-95b6-f6c5d209b9ee.png)
![5](https://user-images.githubusercontent.com/4254736/41047908-e278b7a0-69ad-11e8-881f-a95c8a5c2b0a.png)

**Comment by julianrex** [comment]
Just noting that this sounds similar to https://github.com/mapbox/mapbox-gl-native/issues/11946

**Comment by sigis151** [comment]
I have similar issues with Android emulator as well 
![emulator](https://user-images.githubusercontent.com/5768811/41144114-6efc40dc-6b04-11e8-815c-062f4f702dc6.png)
this is screenshot from 6.1.3 sdk version

**Comment by nole87** [comment]
Any response about this bug?

**Comment by julianrex** [comment]
@sigis151 We're tracking the Android issue in https://github.com/mapbox/mapbox-gl-native/issues/10829

@nole87 For iOS - we're still investigating. We have just released v4.1.0 - can you try again? Which version of Xcode are you using?

**Comment by nole87** [comment]
newest one xcode, I try 4.1 SDk but I can download pod yet ... I will try tomorrow 4.1

**Comment by julianrex** [comment]
@nole87 I've recreated your scenario. This may be related to the Android issue, but not confirmed yet.

**Comment by julianrex** [comment]
For reference - this does not occur on iPhone 5 hardware (running 9.3)

**Comment by nole87** [comment]
sdk 4.0.2 iPhone simulator 9.3

![untitled](https://user-images.githubusercontent.com/4254736/41736283-54709168-758c-11e8-9c94-6d2abfd76b6e.png)

**Comment by nole87** [comment]
4.1 sdk iOS 9.3 still same on simulator, I don't have real iPhone below 6 series to try it ...
<img width="400" alt="iphone 4s" src="https://user-images.githubusercontent.com/4254736/41823080-ebce614c-77f9-11e8-860e-029773f7a1b6.png">
<img width="400" alt="iphone 5" src="https://user-images.githubusercontent.com/4254736/41823081-ebf0825e-77f9-11e8-957c-92f703e57c60.png">

**Comment by nole87** [comment]
What about this. I just try SDK 4.2 but it's same, no text labels only black rectangles ...

**Comment by julianrex** [comment]
@nole87 unfortunately we don't have an update at this time (other than this appears to be a simulator-only issue).

**Comment by nole87** [comment]
Great to hear it's just simulator :)

I am in hurry to publish my app, maybe it's not right place to ask but I need to add padding to user location. In android there is that. In iOS I find mapView.setUserLocationVerticalAlignment(MGLAnnotationVerticalAlignment.bottom, animated: true) but not good enough for my app, I need like in android to set padding in points...

Also, self.mapView.setUserTrackingMode(.followWithCourse, animated: true) when before this line user location is fixed with: mapView.setUserTrackingMode(.follow, animated: true) which is my case than map heading is set hard without animation ... it's bad user experience ...

**Comment by friedbunny** [comment]
While this does easily reproduce on the iPhone 5 Simulator (iOS 9.3) using Xcode 9, I can confirm that it does not happen on a physical iPhone 5 (iOS 9.3.5) when running `ios-v4.2.0`:

![img_3591](https://user-images.githubusercontent.com/1198851/43012947-67d02c56-8c15-11e8-85eb-746dc5709713.PNG)

Though inconvenient, this is an upstream issue that is 1. likely beyond our control, and 2. does not affect end-users. To that end, I’m going to close this as “(probably) won’t fix”.

@nole87 See #12203.
