### ISSUE TITLE
MGLVectorStyleLayer Appending predicate will be crash

### ISSUE THREAD

**Issue by 150vb** [mapbox/mapbox-gl-native#12077]
**Platform:iphoneos**
**Mapbox SDK version:4.0.2**

### Steps to trigger behavior

```objective-c
// 去掉已选的要修改条件
        MGLVectorStyleLayer *vk = (MGLVectorStyleLayer *)k;
        NSMutableArray *mu = [NSMutableArray arrayWithCapacity:0];
        if ([originalPredicate isKindOfClass:[NSCompoundPredicate class]]) {
            NSArray *sub = ((NSCompoundPredicate *)originalPredicate).subpredicates;
            for (NSCompoundPredicate *s in sub) {
                NSString *str = s.predicateFormat;
                if (![str containsString:@"floor"] && ![str containsString:@"ref:building"]) {
                    [mu addObject:s];
                }
            }
        }
        NSPredicate *f = [NSPredicate predicateWithFormat:@"floor == %@", floor];
        [mu addObject:f];
        NSPredicate *b = [NSPredicate predicateWithFormat:@"%K == %@", @"ref:building", buildingId];
        [mu addObject:b];
        reSetPredicate = [NSCompoundPredicate andPredicateWithSubpredicates:mu];
        // 重置过滤
        vk.predicate = reSetPredicate;
```

### Expected behavior
Only filtered buildings and floors are displayed
### Actual behavior
crash on 
<img width="1028" alt="20180607115352" src="https://user-images.githubusercontent.com/6121133/41077496-797a9ede-6a49-11e8-8fe8-5f41d1128309.png">

**Comment by 1ec5** [comment]
Does anything get printed out to the console? Does the crash reproduce if you cast the `floor` or `ref:building` key path to the same type as `floor` or `buildingId`? For example, `CAST(floor, 'NSNumber') == %@`.

**Comment by 150vb** [comment]
Hello ,
Here is the log printed out to the console :
<img width="919" alt="20180608112933" src="https://user-images.githubusercontent.com/6121133/41137708-3e971dc6-6b0f-11e8-897e-d40ea97f9c49.png">

I have try to use the code  following , it didn't crash
```Objective-C
MGLVectorStyleLayer *vk = (MGLVectorStyleLayer *)k;
NSMutableArray *mu = [NSMutableArray arrayWithCapacity:0];
NSPredicate *f = [NSPredicate predicateWithFormat:@"floor == %@", floor];
[mu addObject:f];
NSPredicate *b = [NSPredicate predicateWithFormat:@"%K == %@", @"ref:building", buildingId];
[mu addObject:b];
reSetPredicate = [NSCompoundPredicate andPredicateWithSubpredicates:mu];
// 重置过滤
vk.predicate = reSetPredicate;
```
but it would crash when I just reset the predicate :
```Objective-C
MGLVectorStyleLayer *vk = (MGLVectorStyleLayer *)k;
NSPredicate *originalPredicate = vk.predicate;
reSetPredicate = originalPredicate;
// 重置过滤
vk.predicate = reSetPredicate;
```

**Comment by 1ec5** [comment]
Thanks for the additional details. `filter-type-==` and `filter->=` are invalid expression operators, which explains the crash.

**Comment by 150vb** [comment]
Oh, I see . Thank you for your reply!
