### ISSUE TITLE
Unable to build mbgl in Xcode 10

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#12084]
In Xcode 10.0 beta 1 (build 10L176w), building any mbgl target in the workspace generated by `make xproj` or `make iproj` fails with the following error:

```
ccache: error: execv of /Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed: No such file or directory
Command CompileC failed with a nonzero exit code
```

`xcrun -f clang` shows that `clang` is located at /path/to/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang.

/cc @kkaefer @julianrex

**Comment by 1ec5** [comment]
All the compiler invocations look like this:

```
CompileC /path/to/mapbox-gl-native/build/macos/mbgl.build/Debug/mbgl-core.build/Objects-normal/x86_64/reachability.o /path/to/mapbox-gl-native/platform/darwin/mbgl/storage/reachability.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target: mbgl-core)
```

**Comment by kkaefer** [comment]
Looks like Xcode 10 removed the environment variable `DEVELOPER_DIR` that was set when Xcode <= 9 invoked the compiler. Judging from the available environment variables, we're going to have to do some hacking to obtain the current developer directory from `PATH`.

**Comment by kkaefer** [comment]
Documenting here that Xcode 10 removed `DEVELOPER_DIR`, and added the `LLBUILD_TASK_ID` environment variables. In addition to that, `PATH` changed from:

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

to 

`/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin`
