### ISSUE TITLE
Support: Android 6.1.3 MapBoxView and SurfaceView

### ISSUE THREAD

**Issue by psinetron** [mapbox/mapbox-gl-native#12097]
I need to paste mapbox and surfaceView in one activity. But map not loaded.

My activity xml:
```
<RelativeLayout xmlns:tools="http://schemas.android.com/tools"
        android:id="@+id/activity_main"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
...
<SurfaceView
            android:id="@+id/surfaceView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            />

<com.mapbox.mapboxsdk.maps.MapView
            android:id="@+id/mapView"
            android:layout_width="160dp"
            android:layout_height="160dp"
            mapbox:mapbox_cameraTilt="60"
            mapbox:mapbox_cameraZoom="12"
            mapbox:mapbox_renderTextureMode="true"
            mapbox:mapbox_styleUrl="mapbox://styles/mapbox/streets-v10"
            />
...
```
I see a compass and uiLogo, put not see tiles. 

If set visibility of surfaceView to GONE map work perfectly.
![device-2018-06-08-170705](https://user-images.githubusercontent.com/3624600/41162607-0e28157a-6b3f-11e8-8c57-4c231909f9db.png)

**Comment by tobrun** [comment]
@psinetron if you want to overlay a map and a SurfaceView, I would suggest using a TextureView as render surface for the map. To enable this feature use:

In xml:

```xml
mapbox_renderTextureMode="true"
```

in code:
```
MapboxMapOptions#textureMode(true)
```

Let us know if this doesn't resolve your issue, closing as answered.
