### ISSUE TITLE
Render test integration: intermediate results

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#12095]
Follow up from the node render test suite integration on Android in #12041. There is still some work left to get them fully working. There are currently **78** tests failing of the **607** executed tests. Would love some input from @mapbox/gl-core so we can cut down on the amount of failed tests.

#### Results

| test |  actual  | expected | output | 
| ------------- | ------------- | ------------- | ------------- | 
| `background-pattern  pitch` | ![actual](https://user-images.githubusercontent.com/2151639/41148687-e2adf106-6b09-11e8-9c46-f77ec8bdb6a0.png) | ![expected](https://user-images.githubusercontent.com/2151639/41148731-f4bf888c-6b09-11e8-9801-8082b88deb4e.png) | ![output](https://user-images.githubusercontent.com/2151639/41148742-fa111c24-6b09-11e8-95d4-977417909865.png) | 
| `background-pattern rotated` | ![actual](https://user-images.githubusercontent.com/2151639/41150461-546ff222-6b0e-11e8-98ba-f03b6d3c1fb3.png) | ![expected](https://user-images.githubusercontent.com/2151639/41150466-580fb07a-6b0e-11e8-9d4d-bc082c7ba1d5.png) | ![output](https://user-images.githubusercontent.com/2151639/41150474-5b5fbad6-6b0e-11e8-923e-f452994a1e1f.png) |
| `background-color colorspace-hcl`  | ![actual](https://user-images.githubusercontent.com/2151639/41148560-89b83a16-6b09-11e8-88e3-e8155ace3cc4.png) | ![expected](https://user-images.githubusercontent.com/2151639/41148568-8db12c04-6b09-11e8-9877-2b30c7f452d2.png) | ![output](https://user-images.githubusercontent.com/2151639/41148575-91a71f12-6b09-11e8-8782-0fcf00837b34.png) |
| `background-pattern @2x` | ![actual](https://user-images.githubusercontent.com/2151639/41150398-327c5aac-6b0e-11e8-9a62-a77936465913.png) | ![expected](https://user-images.githubusercontent.com/2151639/41150409-37f9d7f2-6b0e-11e8-84f6-a3daf01d4ff3.png) | ![output](https://user-images.githubusercontent.com/2151639/41150417-3d79ffb8-6b0e-11e8-8162-198fbc93f751.png) |
| `fill-pattern uneven-pattern` | ![actual](https://user-images.githubusercontent.com/2151639/41154068-2f08f7ee-6b19-11e8-9a84-144e1a01f40c.png) | ![expected](https://user-images.githubusercontent.com/2151639/41154078-381e7e62-6b19-11e8-8a9e-b14bc524c550.png) | ![output](https://user-images.githubusercontent.com/2151639/41154084-3cf6c980-6b19-11e8-9823-119e5bfae80e.png)
| `hillshade-accent-color zoom-function` | ![actual](https://user-images.githubusercontent.com/2151639/41154116-5e5931f8-6b19-11e8-8bb6-74ae1da48db9.png) | ![expected](https://user-images.githubusercontent.com/2151639/41154120-63427774-6b19-11e8-9d76-d83efd8fbca7.png) | ![output](https://user-images.githubusercontent.com/2151639/41154126-6809f16a-6b19-11e8-8dd9-7644bf2d15e6.png) |
| `line-pattern overscaled` | ![actual](https://user-images.githubusercontent.com/2151639/41154316-14649b72-6b1a-11e8-8ef2-cfadf7a9b5cd.png) | ![expected](https://user-images.githubusercontent.com/2151639/41154320-187a6598-6b1a-11e8-8d87-c2194a5ce333.png) | ![output](https://user-images.githubusercontent.com/2151639/41154325-1dbd52ea-6b1a-11e8-9c7e-b988abbc583e.png)
| `combinations line-translucent--fil-translucent` | ![actual](https://user-images.githubusercontent.com/2151639/41154820-b557b068-6b1b-11e8-88e6-cd90720b83b4.png) | ![expected](https://user-images.githubusercontent.com/2151639/41154822-b6ae9cec-6b1b-11e8-8025-38a8f9e0ec0d.png) | ![output](https://user-images.githubusercontent.com/2151639/41154824-b8406734-6b1b-11e8-8c58-5feea894b9e0.png)
| `combinations-hilldshade-line-translucent` |![actual](https://user-images.githubusercontent.com/2151639/41154875-eb147bd2-6b1b-11e8-9eda-b13a773cf7ed.png) | ![expected](https://user-images.githubusercontent.com/2151639/41154877-ec30d628-6b1b-11e8-9b5d-70a8842f7224.png) | ![output](https://user-images.githubusercontent.com/2151639/41154878-ed7bfb2a-6b1b-11e8-8ca0-521f64aa6065.png) |

#### Notes:
 - Most tests fail due to having either a bearing or pitch value in the style.json (shown in first two images) 
 - Some tests fail due to having a test property that isn't supported yet on Android (not listed above)

**Comment by jfirebaugh** [comment]
`background-pattern pitch` and `background-pattern rotated` look most like a legit bug -- like the map is just ending up with the wrong pitch and bearing values.

`background-color colorspace-hcl` looks like some sort of colorspace transformation bug.

`hillshade-accent-color zoom-function` and `combinations-hilldshade-line-translucent` have the same issue with seams, presumably on a tile edge.

The other ones look like floating point issues, e.g. with `fill-pattern uneven-pattern` the pattern is shifted vertically a tiny amount.

**Comment by lilykaiser** [comment]
Catching up here, what's the best next step? Should `background-pattern pitch` and `background-pattern rotated` and `background-color colorspace-hcl ` be ticketed as gl core bugs?

**Comment by riastrad** [comment]
When using `.addMarker()` for bitmap icon placements, variation between color rendering for different devices has been observed. Here's a quick comparison that's been submitted, where POIs are more red on one device and more orange on another device:

**HTC U11:**
<img src="https://user-images.githubusercontent.com/16272584/43550776-aea130a2-95b2-11e8-8ca4-04cfd75c16a5.png" width="250">   

**Samsung Galaxy S7**
<img src="https://user-images.githubusercontent.com/16272584/43550784-b47bd19e-95b2-11e8-9ae2-7eff323ef35b.png" width="250">

**Comment by riastrad** [comment]
@kkaefer in the above example, the icons aren't generated using a sprite-sheet, but are applied individually using different url calls. Here's the main one:
 
![icon](https://user-images.githubusercontent.com/16272584/43594466-459e1340-9648-11e8-864e-cd3e86230268.png)

Let me know if you need more than this.

**Comment by kkaefer** [comment]
Thank you for providing this image. It looks like the color discrepancies you're seeing might be due to the `gAMA`/`cHRM` chunks in this particular image: 
![image](https://user-images.githubusercontent.com/52399/43772515-a4dc8b7c-9a42-11e8-84fe-0db7347ce5f2.png)

You could try removing these to ensure uniform interpretation on all devices. I ticketed a further investigation into this issue in https://github.com/mapbox/mapbox-gl-native/issues/12560; please continue discussion there if necessary as this ticket is actually about a different issue.
