### ISSUE TITLE
Update macos-debug-qt5 build to Xcode 10.x

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#12105]
#12102 updated CircleCI builds to Xcode 9.4... except for `macos-debug-qt5`, [which failed with](https://circleci.com/gh/mapbox/mapbox-gl-native/113703):

```
[ RUN      ] OfflineDatabase.ConcurrentUse
[ WARNING ]  "{}[Database]: Removing existing incompatible offline database"
QSqlDatabasePrivate::database: requested database does not belong to the calling thread.
QSqlDatabasePrivate::database: requested database does not belong to the calling thread.
QSqlQuery::prepare: database not open
QSqlQuery::prepare: database not open
libc++abi.dylib: libc++abi.dylib: terminating with uncaught exception of type mapbox::sqlite::Exception: Driver not loaded Driver not loadedterminating with uncaught exception of type mapbox::sqlite::Exception: Driver not loaded Driver not loaded
```

/cc @brunoabinader @tmpsantos

**Comment by tmpsantos** [comment]
@brunoabinader have you seen this before? I would guess it has something to do with the SQL driver depending on some old ABI.

**Comment by brunoabinader** [comment]
> @brunoabinader have you seen this before?

Not yet - a quick look at the Homebrew script shows that XCods 9.4 (High Sierra) should be fine - I can check tomorrow at the office on the MacBook.

**Comment by friedbunny** [comment]
[This still has a similar failure](https://circleci.com/gh/mapbox/mapbox-gl-native/136807) using Xcode 9.4.1. (https://github.com/mapbox/mapbox-gl-native/pull/12522)

**Comment by friedbunny** [comment]
[This still has a similar failure](https://circleci.com/gh/mapbox/mapbox-gl-native/194649) using Xcode 10.1. (#13323)

**Comment by friedbunny** [comment]
Stalebot...

**Comment by julianrex** [comment]
@brunoabinader any chance we can look at this soon? Would be nice to move to an Xcode 10

**Comment by brunoabinader** [comment]
@julianrex we don't have short term bandwidth atm - @tmpsantos is there someone from GL native who could handle this?
