### ISSUE TITLE
queryRenderedSymbols sorting for overlapping features is based on the wrong index

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native#12104]
@julianrex noticed the asserts in our sort function triggering:

https://github.com/mapbox/mapbox-gl-native/blob/5a837c17024e37c41b10dbba7dd27c364281035e/src/mbgl/geometry/feature_index.cpp#L96-L104

The indices in `featureSortOrder` are populated here:

https://github.com/mapbox/mapbox-gl-native/blob/5a837c17024e37c41b10dbba7dd27c364281035e/src/mbgl/renderer/buckets/symbol_bucket.cpp#L208-L210

The problem is that `symbolInstance.featureIndex` is not the same as the `feature.index` that gets stored in the `IndexedSubfeature` -- just super close. `featureIndex` is an index into the features that pass filters and get included in the tile, while `feature.index` is an index into the raw set of features in the tile. 🤦‍♂️ 

The implication of this (I believe) is that sort order gets messed up when items are getting filtered out. The assertion warned us the sort order was wrong, but we should be able to keep running just fine -- symbols that don't show up in `featureSortOrder` because of this bug will just get incorrectly sorted to the end of the list. Since the order of results in `queryRenderedSymbols` shouldn't usually matter and is already kind of hard for someone to predict, I doubt this bug is causing much impact.

/cc @ansis @julianrex @fabian-guerra

**Comment by julianrex** [comment]
Adding https://github.com/mapbox/mapbox-gl-native/issues/12209 as a probable example of this in the wild.

**Comment by ChrisLoer** [comment]
Fixed in #12225.
