### ISSUE TITLE
Placeholder for still-loading tile is always land

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1210]
When you pan or zoom, tiles that haven’t loaded are represented by solid land-colored tiles:

![straight-edge](https://cloud.githubusercontent.com/assets/1231218/7009133/f17c7652-dc4c-11e4-9ef2-87ca2216a09a.PNG)

This behavior makes sense on land, but not as much when you’re panning around in the ocean or in an archipelago. It would be nice if GL could know that the entire screen edge is all water-colored, so the placeholder tiles should also be water-colored.

If that’s too complex, would it be possible to let the developer somehow style this background (independently of the style’s land color)? The developer might want something like:

![linen](https://cloud.githubusercontent.com/assets/1231218/7009006/15d7e118-dc4c-11e4-97a6-7b17fce626fd.png)

I kid. More realistically, a `UIVisualEffectView` underneath the tiles could be a really cool effect.

**Comment by incanus** [comment]
I think #119 probably covers this better and in a more expected way? The color BTW is `background` in the style.

**Comment by 1ec5** [comment]
Agreed.
