### ISSUE TITLE
Ubuntu 18 server : what():  eglInitialize() failed.

### ISSUE THREAD

**Issue by raphaelMalie** [mapbox/mapbox-gl-native#12108]
Hello,

I'm trying to run mapbox-gl-native on my server to render static images of my map.

I have this error when I run the demo script (https://github.com/mapbox/mapbox-gl-native/tree/master/platform/node) :

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  eglInitialize() failed.
```

Everything works fine on my computer, but on my server I am stuck with this error.

So far I did just a basic installation :

```
npm install @mapbox/mapbox-gl-native
npm install canvas
npm install sharp
```

Do I need to run a graphic server like xvfb to make this work?

I'm stuck on this problem since two days, any help would be massively appreciated.

Regards

**Comment by kkaefer** [comment]
> Do I need to run a graphic server like xvfb to make this work?

Depends on what implementation you're using. Mesa's implementation of EGL/OpenGL ES requires an X server; XVFB has worked for us. Other implementations such as SwiftShader do not necessarily require an X server. Mapbox GL can't affect the way the EGL/OpenGL implementations work, so you'll have to make sure to provide all dependencies for it to function correctly.

In our CI scripts, we use this: https://github.com/mapbox/mapbox-gl-native/blob/95a6fcdd26c93ebea2726c43f8afdf04b4245830/circle.yml#L203-L204

**Comment by bigsheeper** [comment]
> Mesa's implementation of EGL/OpenGL ES requires an X server; 
> 
> 
> https://github.com/mapbox/mapbox-gl-native/blob/95a6fcdd26c93ebea2726c43f8afdf04b4245830/circle.yml#L203-L204

I don't think mesa EGL requires an X server, and I'v been successfully rendered without X server. And also, mapd(OmniSci) use EGL to render without graphics.

**Comment by elenacliu** [comment]
@bigsheeper Wow, if so, what can I do to make mesa EGL render without X server?

**Comment by jackcjp** [comment]
Use tileserver-gl [Dockerfile](https://github.com/maptiler/tileserver-gl/blob/master/Dockerfile) to build an image and [docker-entrypoint.sh](https://github.com/maptiler/tileserver-gl/blob/master/docker-entrypoint.sh) to start my service, it works well for me.
