### ISSUE TITLE
Fix issues in LineAtlas::addDash

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#12113]
We're currently not validating `line-dasharray` values parsed from a style. This means that when passing them to `addDash`, there are a number of issues:

- Empty dash arrays, or those with just on value produce unexpected results
- Dash arrays containing negative dash values aren't rejected
- Large numbers aren't validated and the resulting `LinePatternPos` contains a width that goes beyond the texture

**Comment by springmeyer** [comment]
@kkaefer can this be closed now that #12114 is landed?

**Comment by kkaefer** [comment]
Let's keep this open to track adding more validation to the stylesheet when parsing invalid dasharrays.
