### ISSUE TITLE
Expose feature query functions in QMapboxGLMapRenderer

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#12118]
`QMapboxGLMapRenderer` should be able to expose the feature query functions from `mbgl::Renderer`, in particular, `queryRenderedFeatures`. Also, we should be able to specify an individual instance of `QMapboxGLMapRenderer` to `QMapboxGL`.

@ivovandongen @tmpsantos I suppose this is related to the upcoming render thread changes?

/cc @nagineni @pozdnyakov

**Comment by tmpsantos** [comment]
> @ivovandongen @tmpsantos I suppose this is related to the upcoming render thread changes?

I think this could be implemented already without the refactoring.
