### ISSUE TITLE
Crash at [MGLMapView annotationTagsInRect:] on map zoom change

### ISSUE THREAD

**Issue by aaasifrz9** [mapbox/mapbox-gl-native#12138]
**Platform:** 
platform :ios, '9.3'

**Mapbox SDK version:**
pod 'Mapbox-iOS-SDK', '~> 4.0'

### Steps to trigger behavior

 1. After load map, annotation renders properly
 2. After zoom map, API returns annotation list data to re-render annotations at mapview, gets crashed at [MGLMapView annotationTagsInRect:] on map zoom change. Screenshot attached.

I am using iPhone 6 (iOS version 11.3.1)

![screen shot 2018-06-13 at 4 33 07 pm](https://user-images.githubusercontent.com/24565054/41348232-a14d9076-6f29-11e8-97f8-19f97900fc9a.png)

**Comment by aaasifrz9** [comment]
I have check v3.6.4 as commented by @Phanith-Fe in ticket #10891. And this version is working fine for me.

**Comment by julianrex** [comment]
Thanks for the report @aaasifrz9 - we have made some recent changes that may solve this issue, and are due in v4.1.0. 

Are you able to try [ios-v4.1.0-beta.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v4.1.0-beta.1)?
