### ISSUE TITLE
Get bearing accuacy

### ISSUE THREAD

**Issue by samoilovich** [mapbox/mapbox-gl-native#12137]
Hello

My task is to implement the same icon for current location as in Google Maps with showing of bearing accuracy.
![google_maps_current_position](https://user-images.githubusercontent.com/7480005/41347829-87791370-6f13-11e8-9ab0-f56b4c6d0563.png)

Could you prompt where I can get accuracy of bearing? And it is possible or not with mapbox sdk?
mapbox sdk: "com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.1"
locatio plugin: "com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.2"

Thanks

**Comment by LukasPaczos** [comment]
Thanks for reaching out @samoilovich. I need to close this one as it doesn't reference `mapbox-gl-native` repo but rather `mapbox-plugins-android`. Following up in https://github.com/mapbox/mapbox-plugins-android/issues/553.

**Comment by danesfeder** [comment]
@samoilovich please check out some follow-up questions regarding this issue https://github.com/mapbox/mapbox-plugins-android/issues/553#issuecomment-404255125
