### ISSUE TITLE
Duplicate text labels with MGLSymbolStyleLayer

### ISSUE THREAD

**Issue by jadar** [mapbox/mapbox-gl-native#12141]
**Platform:** iOS
**Mapbox SDK version:** 3.7.8

### Steps to trigger behavior

 1. Set up a MGLShapeSource with shapes in a MGLShapeCollectionFeature.
 2. Create a MGLStyleLayer for displaying text from a feature attribute with the previously created MGLShapeSource as the source.
 3. View the map in the app.

### Expected behavior

I expect the text to be positioned in the center or the polylabel center of the polygon and only shown once.

### Actual behavior

The text is positioned arbitrarily and sometimes multiple times. I don't understand what controls this.

![simulator_screen_shot_-_iphone_8_-_2018-06-13_at_16_25_46](https://user-images.githubusercontent.com/3793928/41376548-869d35e4-6f27-11e8-8d30-6ad29c71a601.png)

**Comment by jmkiley** [comment]
Hello - 

I have not been able to replicate the duplicate label issue. Could you share a minimal test case that demonstrates this issue? It will help us to look into what is going on.

**Comment by jadar** [comment]
Thanks for the reply. 
In short,
1. Instances of `MGLMultiPolygonFeature` are created to represent distinct features on the map that have a multi-polygon. The `MGLMultiPolygonFeature(coordinates:,count:,interiorPolygons:)` constructor is used.
2. A collection of these objects is used to make a `MGLShapeCollectionFeature`.
3. That `MGLShapeCollectionFeature` is then used as the shape for an `MGLShapeSource`
4. A `MGLFillStyleLayer` layer is set up to display the polygons as an overlay, with the perviously mentioned `MGLShapeSource` as its source.
5. Another layer, `MGLSymbolStyleLayer`, is set up to display the feature's text attribute with the same `MGLShapeSource` as its source.
6. In the app, zooming in to any of the polygons shows the text, but the text will be shown multiple times over the polygon, as pictured in the given screenshot.

**Comment by IsVer** [comment]
Thanks for raising this issue, I have the same problem for country labels when working with Mapbox Studio. Changing the zoom-level specification does not fix it.

Anyone an idea on how to prevent multiple of the same labels when zooming in? 
Thanks
