### ISSUE TITLE
Add contentInsetAdjustmentBehavior property to MGLMapView

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#12143]
In iOS 11.0, `UIViewController.automaticallyAdjustsScrollViewInsets` is deprecated in favor of `UIScrollView.contentInsetAdjustmentBehavior`. `automaticallyAdjustsScrollViewInsets` has always been a bit of a pain for us, versus how macOS handles the same configuration option, because it’s a property on the containing view controller instead of the view itself. (We have to crawl up the responder chain looking for the view controller just to update MGLMapView’s internal constraints.) MGLMapView should implement its own `contentInsetAdjustmentBehavior` property that lets the developer indicate whether the MGLMapView itself should adjust the insets automatically.

We’ll have to keep support for `UIViewController.automaticallyAdjustsScrollViewInsets` around until that property is removed from the (Apple) iOS SDK, in case any developer depends on the currently documented behavior.

/ref #12142 #10485
/cc @friedbunny @julianrex

**Comment by nickprkins** [comment]
I am seeing an issue where the map is not loading tiles and is just showing the containing view background color. it randomly happens at times on first load of the app.  I see in the console this message:

> MGLMapView WARNING UIViewController.automaticallyAdjustsScrollViewInsets is deprecated use MGLMapView.automaticallyAdjustContentInset instead.

Is this a possible cause of that issue?  I have set `self.automaticallyAdjustsScrollViewInsets = false` on the mapbox view but I am still getting that message.  Any ideas? Is this related?

![Image from iOS (1)](https://user-images.githubusercontent.com/44300035/109982858-4ce43c80-7cd0-11eb-8d28-1f794b592aaa.png)
