### ISSUE TITLE
Android 6.1.3 MoveCamera to bounds bug

### ISSUE THREAD

**Issue by psinetron** [mapbox/mapbox-gl-native#12150]
I move camera to bounds like this:
```
val geoPoint = LatLng(currentLocation.latitude, currentLocation.longitude)

val bounds = LatLngBounds.Builder()
                            .include(Converters.getInstance().getDestinationPoint(geoPoint, 2000, 0.0))
                            .include(Converters.getInstance().getDestinationPoint(geoPoint, 2000, 90.0))
                            .include(Converters.getInstance().getDestinationPoint(geoPoint, 2000, 180.0))
                            .include(Converters.getInstance().getDestinationPoint(geoPoint, 2000, 270.0))
                            .build()
```
Then I move camera:
`mapBox.moveCamera(CameraUpdateFactory.newLatLngBounds(bounds, 0))`

**Expected result:** 
The same zoom level when changing location. For example (10.114803380...)

**Actual result:**
Random zoom level +/- 0.5 when changing location.

UPD:
I made the test. I draw a polygon at the points of the Bunds. The polygon is drawn correctly. Always the same distance in 2000 meters from the edge to the point.
Error is in camera zoom
![2018-06-14 11 59 01](https://user-images.githubusercontent.com/3624600/41402224-69d62a6c-6fca-11e8-96ff-b0d36f8461e7.png)
![2018-06-14 11 59 22](https://user-images.githubusercontent.com/3624600/41402228-6c0a4b42-6fca-11e8-9be6-648a7664afc3.png)

**Comment by LukasPaczos** [comment]
I'm not really sure I'm following - the camera for bounds update is supposed to zoom in/out in order to fit the bounds as tightly as possible, that's the expected behavior. Are you seeing that when zooming from one point (after already being zoomed in) to another the zoom differs? Would you mind providing a concrete reproducible test-case?

**Comment by LukasPaczos** [comment]
Thanks for the extensive write-up! I'll try to reproduce using this info.

**Comment by LukasPaczos** [comment]
Hey @psinetron, sorry for a late response on this one.

I was able to reproduce for bounds that are rotated:
![ezgif com-video-to-gif 12](https://user-images.githubusercontent.com/16925074/45889365-8eaef000-bdc0-11e8-9632-3a9bf081f7bb.gif)

This, however, is working as desinged. If your bounds are rotated, we are going to create a convex hull out of them which for rotated bounds results in a new, north facing bounds which are wrapping the initial one, therefore, it's bigger and results in a higher zoom level.

You can see that behavior above - black bounds are rotated and we are taking the grey one into consideration instead. For unrotated (red) bounds, every works as expected as well.

From the gif you provided it's unclear whether the bounds are rotated, but I wasn't able to reproduce any unwanted behavior for unrotated bounds. Also, please look into `mapboxMap#getCameraForLatLngBounds` which let's you get a camera update that includes a bearing as well.

Closing as not actionable, but please feel free to reach out if you spot something off in my understanding of the issue.
