### ISSUE TITLE
[ios] two/three finger crash

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-native#12160]
**Platform:**
iOS

**Mapbox SDK version:**
iOS-v4.0.1

### Steps to trigger behavior

 1. Start a two-finger zoom
 2. Introduce a third finger while still zooming
 3. Release all fingers

### Expected behavior
No crash/failed assert

### Actual behavior
Crash(failed assert) with the following message
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unbalanced change delimiter suppression/unsuppression'

**Comment by 1ec5** [comment]
This looks a lot like what @lloydsheng is fixing in #12148.

**Comment by lloydsheng** [comment]
@halset  Thanks for filing this bug, it was fixed in this PR https://github.com/mapbox/mapbox-gl-native/pull/12148
