### ISSUE TITLE
Invalid filter value exception when setting layer.predicate in iosapp samples

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#12169]
**Platform:** iOS
**Mapbox SDK version:** 4.1.0 beta

### Steps to trigger behavior

 1. Run `iosapp`
 2. Select `Add Building Extrusions` from the debug menu.
 3. `'NSInvalidArgumentException', reason: 'Invalid filter value: [2]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead.'`

The following line triggers the exception: https://github.com/mapbox/mapbox-gl-native/blob/fba8fd7d649e7384b926ec19e9887eaa5f9a093a/platform/ios/app/MBXViewController.m#L931

Edit: This also occurs in `Style Fill With Numeric Filter`:

https://github.com/mapbox/mapbox-gl-native/blob/fba8fd7d649e7384b926ec19e9887eaa5f9a093a/platform/ios/app/MBXViewController.m#L1113

**Comment by 1ec5** [comment]
Looks like these predicates were never upgraded to v4.0.0, which no longer automatically casts key paths in comparisons. These are the only two lines that match the regular expression `predicateWithFormat:.*[<>]` in iosapp.
