### ISSUE TITLE
MapBox logo & attribution insets

### ISSUE THREAD

**Issue by hernangonzalez** [mapbox/mapbox-gl-native#12170]
Hi,

Have been setting the content inset, which works great for map elements as annotations and layers, yet the logo and attribution elements are not being updated.

```
        let insets = UIEdgeInsets(top: 0, left: 0, bottom: 200, right: 0) 
        mapView.setContentInset(insets, animated: true)
        mapView.setNeedsUpdateConstraints()
```

The latest `setNeedsUpdateConstraints()` is added because of this reference => https://github.com/mapbox/mapbox-gl-native/issues/10627, yet no luck. Both elements persist at the bottom.

**Platform:** iOS
**Mapbox SDK version:** 4.0.2 (cocoapods)

Thank you,
H.

**Comment by julianrex** [comment]
Related: https://github.com/mapbox/mapbox-gl-native/issues/11068
