### ISSUE TITLE
Send created As Local Time

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1217]
Changed `created` to use device timezone instead of current UTC.

/cc @edenh @mick @camilleanne

**Comment by bleege** [comment]
Decided on the following format as it gives Timezone description and hour offset:

`2015-04-06T17:47:29 CDT -0500`

**Comment by mick** [comment]
@bleege can we make this an ISO 8601 formatted date? This is already really close and that will make it easier to parse in javascript.  I'm not so worried about the timezone as long as we have the offset. 
`2015-04-06T04:31:32-0500`

**Comment by 1ec5** [comment]
> ISO 8601 formatted date

:+1: The description is very ambiguous anyways. The only unambiguous ways to represent a timezone at a given time are ISO 8601 (±hh:mm) and [tz](http://en.wikipedia.org/wiki/List_of_tz_database_time_zones) (e.g., “America/Los_Angeles” or “America/Indiana/Vevay”).

**Comment by bleege** [comment]
Sure thing @mick and @1ec5.  I just updated the date format and once Travis CI is happy I'll merge it in.  Here's a sample from my test:

`2015-04-06T19:10:52-0500`

**Comment by bleege** [comment]
Tested and Merged.
