### ISSUE TITLE
iOS lack of the information

### ISSUE THREAD

**Issue by luannguyenkhoa** [mapbox/mapbox-gl-native#12171]
I'm porting Google Maps to Mapbox but stuck in an issue that exposed in below images:
They are using the same configurations: zoom level, padding,... 
Mapbox looks like a blank map while GM shows a lot of information.

![scrshot](https://user-images.githubusercontent.com/13121441/41590233-bc548e2c-73e0-11e8-978b-68c75bf2596a.png)
![screen shot 2018-06-19 at 4 42 21 pm](https://user-images.githubusercontent.com/13121441/41590244-c2aeb676-73e0-11e8-9797-5dea68aee885.png)

Note: Mapbox light style, GM use custom style.
How could I display Mapbox like GM as the image above? I mean as much information as possible.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. The Mapbox Light style has a minimalist design to support its primary usecase as a basemap for data visualization. That said, you can always customize it for your needs using [Mapbox Studio](https://www.mapbox.com/studio/). In this case, you'd want to lower the minimum zoom level for street label layers.

Note that this issue tracker is for reporting bugs and feature requests. For further "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/).
