### ISSUE TITLE
Bump MBGL deployment targets? iOS is 8.0 / macOS is 10.10

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#12173]
**Platform:** iOS
**Mapbox SDK version:** 4.0.2 / master

`platform/ios/config.cmake` has the iOS deployment target set at 8.0. Any reason we can't bump this to 9.0 in line with https://github.com/mapbox/mapbox-gl-native/pull/11776?

iOS:
https://github.com/mapbox/mapbox-gl-native/blob/b84a184d2ddc496908506c9c69ed6b4778213077/platform/ios/config.cmake#L6

Similarly for macOS?
https://github.com/mapbox/mapbox-gl-native/blob/b84a184d2ddc496908506c9c69ed6b4778213077/platform/macos/config.cmake#L1

/cc @friedbunny @jfirebaugh

**Comment by friedbunny** [comment]
Thanks for noticing this — it should have happened in #11776. It’s unfortunate that there are redundant homes for build settings, but I suppose we don’t change them _that_ often.
