### ISSUE TITLE
Build failure for iOS

### ISSUE THREAD

**Issue by moreinf** [mapbox/mapbox-gl-native#12188]
**Platform:** iOS, mac
**Mapbox SDK version:** current as of 6/20 4:28pm EST.

### Steps to trigger behavior

 1. I followed everything exactly as https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/INSTALL.md says.
 2. when I did 'make....' as shown below in the section of 'Actual behavior', build failed.

### Actual behavior: build failed.

hong mapbox $ git clone https://github.com/mapbox/mapbox-gl-native.git
Cloning into 'mapbox-gl-native'...
remote: Counting objects: 180321, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 180321 (delta 24), reused 17 (delta 11), pack-reused 180282
Receiving objects: 100% (180321/180321), 199.08 MiB | 7.35 MiB/s, done.
Resolving deltas: 100% (119387/119387), done.
hong mapbox $ cd mapbox-gl-native
hong (master) mapbox-gl-native $ make iframework BUILDTYPE=Release
mkdir -p "platform/ios/ios.xcworkspace/xcuserdata/hong.xcuserdatad"
cp platform/ios/WorkspaceSettings.xcsettings "platform/ios/ios.xcworkspace/xcuserdata/hong.xcuserdatad/WorkspaceSettings.xcsettings"
mkdir -p build/ios
(cd build/ios && cmake -G Xcode ../.. \
		-DCMAKE_TOOLCHAIN_FILE=../../platform/ios/toolchain.cmake \
		-DMBGL_PLATFORM=ios \
		-DMASON_PLATFORM=ios)
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- The C compiler identification is AppleClang 9.1.0.9020039
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - failed
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Detecting C compile features
-- Detecting C compile features - failed
-- Updating submodules...
Submodule 'mapbox-gl-js' (https://github.com/mapbox/mapbox-gl-js.git) registered for path 'mapbox-gl-js'
Cloning into '/Users/hong/mapbox/mapbox-gl-native/mapbox-gl-js'...
Submodule path 'mapbox-gl-js': checked out '45b0be007cd5df6837e5381e067b9c2a42b78501'
-- Running 'npm install' for mapbox-gl-native...
npm notice created a lockfile as package-lock.json. You should commit this file.
added 254 packages from 220 contributors and audited 627 packages in 8.705s
found 12 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
-- Running 'npm install' for mapbox-gl-js...
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @mapbox/mapbox-gl-test-suite@0.0.0 No repository field.
npm WARN @mapbox/mapbox-gl-test-suite@0.0.0 license should be a valid SPDX license expression

added 56 packages from 43 contributors and audited 77 packages in 4.029s
found 0 vulnerabilities

Submodule 'platform/ios/vendor/mapbox-events-ios' (https://github.com/mapbox/mapbox-events-ios.git) registered for path 'platform/ios/vendor/mapbox-events-ios'
Cloning into '/Users/hong/mapbox/mapbox-gl-native/platform/ios/vendor/mapbox-events-ios'...
Submodule path 'platform/ios/vendor/mapbox-events-ios': checked out '2570417b77d9b9c22a40930cdf1fad4b985aff06'
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/geometry/0.9.2.tar.gz...
[Mason] Unpacking package to mason_packages/headers/geometry/0.9.2...
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/variant/1.1.4.tar.gz...
[Mason] Unpacking package to mason_packages/headers/variant/1.1.4...
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/unique_resource/cba309e.tar.gz...
[Mason] Unpacking package to mason_packages/headers/unique_resource/cba309e...
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/rapidjson/1.1.0.tar.gz...
[Mason] Unpacking package to mason_packages/headers/rapidjson/1.1.0...
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/boost/1.65.1.tar.gz...
[Mason] Unpacking package to mason_packages/headers/boost/1.65.1...
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/geojsonvt/6.3.0.tar.gz...
[Mason] Unpacking package to mason_packages/headers/geojsonvt/6.3.0...
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/supercluster/0.2.2.tar.gz...
[Mason] Unpacking package to mason_packages/headers/supercluster/0.2.2...
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/kdbush/0.1.1-1.tar.gz...
[Mason] Unpacking package to mason_packages/headers/kdbush/0.1.1-1...
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/earcut/0.12.4.tar.gz...
[Mason] Unpacking package to mason_packages/headers/earcut/0.12.4...
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/protozero/1.5.2.tar.gz...
[Mason] Unpacking package to mason_packages/headers/protozero/1.5.2...
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/pixelmatch/0.10.0.tar.gz...
[Mason] Unpacking package to mason_packages/headers/pixelmatch/0.10.0...
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/geojson/0.4.2.tar.gz...
[Mason] Unpacking package to mason_packages/headers/geojson/0.4.2...
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/polylabel/1.0.3.tar.gz...
[Mason] Unpacking package to mason_packages/headers/polylabel/1.0.3...
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/wagyu/0.4.3.tar.gz...
[Mason] Unpacking package to mason_packages/headers/wagyu/0.4.3...
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/shelf-pack/2.1.1.tar.gz...
[Mason] Unpacking package to mason_packages/headers/shelf-pack/2.1.1...
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/cheap-ruler/2.5.3.tar.gz...
[Mason] Unpacking package to mason_packages/headers/cheap-ruler/2.5.3...
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/vector-tile/1.0.1.tar.gz...
[Mason] Unpacking package to mason_packages/headers/vector-tile/1.0.1...
[Mason] Downloading package https://mason-binaries.s3.amazonaws.com/ios-8.0/icu/58.1-min-size.tar.gz...
[Mason] Unpacking package to mason_packages/ios-8.0/icu/58.1-min-size...
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/hong/mapbox/mapbox-gl-native/build/ios
FORMAT=dynamic BUILD_DEVICE= SYMBOLS= \
	./platform/ios/scripts/package.sh
* Configuring dynamic Release framework for iphoneos 11.4; symbols: YES
Xcode 9.4.1
Build version 9F2000
* Recording library version…
mapbox-gl-native 2886aca3e2
* Building targets (build 12741, version 4.1.0-alpha.1)
* Building for iOS Simulator using scheme dynamic
2018-06-20 16:24:34.242 xcodebuild[19881:759843]  DTDeviceKit: deviceType from 68519ebfa5e25d9ffedcb02cdbb7a3a083775622 was NULL
▸ Building ios/settings [Release]
▸ Check Dependencies
▸ Processing Root.plist
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.strings
▸ Copying Root.plist
▸ Touching Settings.bundle
▸ Signing /Users/hong/mapbox/mapbox-gl-native/build/ios/Release-iphonesimulator/Settings.bundle
▸ Aggregate mbgl/ZERO_CHECK [Release]
▸ Check Dependencies
▸ Running script 'CMake Rules'
▸ Building mbgl/mbgl-loop-darwin [Release]
▸ Check Dependencies
▸ Compiling async_task.cpp
▸ Compiling run_loop.cpp
▸ Compiling timer.cpp
▸ Compiling async_task.cpp
▸ Compiling run_loop.cpp
▸ Compiling timer.cpp
▸ Building mbgl/mbgl-core [Release]
▸ Check Dependencies
** BUILD FAILED **

The following build commands failed:
	CompileC build/ios/mbgl.build/Release-iphonesimulator/mbgl-loop-darwin.build/Objects-normal/i386/async_task.o platform/darwin/src/async_task.cpp normal i386 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/ios/mbgl.build/Release-iphonesimulator/mbgl-loop-darwin.build/Objects-normal/i386/run_loop.o platform/darwin/src/run_loop.cpp normal i386 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/ios/mbgl.build/Release-iphonesimulator/mbgl-loop-darwin.build/Objects-normal/i386/timer.o platform/darwin/src/timer.cpp normal i386 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/ios/mbgl.build/Release-iphonesimulator/mbgl-loop-darwin.build/Objects-normal/x86_64/async_task.o platform/darwin/src/async_task.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/ios/mbgl.build/Release-iphonesimulator/mbgl-loop-darwin.build/Objects-normal/x86_64/run_loop.o platform/darwin/src/run_loop.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/ios/mbgl.build/Release-iphonesimulator/mbgl-loop-darwin.build/Objects-normal/x86_64/timer.o platform/darwin/src/timer.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(6 failures)
make: *** [iframework] Error 65

**Comment by friedbunny** [comment]
I can’t reproduce this using these steps (including cloning a new repo) and the build errors don’t seem to say what actually failed. If you could try running `make ios-test` and then looking at the log in `build/xcodebuild-[date].log` for more specific detail, that’d be great.

**Comment by kkaefer** [comment]
It looks like there's something wrong with your compiler installation. Please run
```
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
```
to reset the path and rerun.
