### ISSUE TITLE
MGLAnnotation Strings Wrapped in Double Optionals

### ISSUE THREAD

**Issue by nkanetka** [mapbox/mapbox-gl-native#12189]
**Platform:** iOS
**Mapbox SDK version:** 4.1.0 and 3.7.0

### Steps to trigger behavior

 1. Use an `MGLAnnotation`
 2. The value of the `title` and `subtitle` property is wrapped in a Double optional (i.e. `String??` instead of `String?`).

### Expected behavior
Only have one optional wrapper on `String`'s within `MGLAnnotation`'s.

### Actual behavior
From the [documentation](https://www.mapbox.com/ios-sdk/api/4.1.0/Protocols/MGLAnnotation.html#/c:objc(pl)MGLAnnotation(py)title) it appears as though there should be 1 optional wrapper. In both 3.7.0 and 4.1.0 it looks like there are double optionals on both the`String` properties (see the screenshot below). Finally, only `String`'s within `MGLAnnotation`'s seem to have double optionals.

Not a huge deal if this is the intended behaviour but it makes unwrapping optionals a bit awkward i.e.

`let annotationTitle: String = (annotation.title ?? nil) ?? ""`
instead of
`let annotationTitle: String = annotation.title ?? ""`

![screen shot 2018-06-20 at 10 47 34 pm](https://user-images.githubusercontent.com/10577783/41695729-474776c2-74de-11e8-8968-e0f6df9142a9.png)

**Comment by jmkiley** [comment]
Hi @nkanetka - 

Thank you for the report! I'm not seeing the double optionals with v4.1.0. Could you tell us a little more about your implementation? Which class conforming to the `MGLAnnotation` protocol are you seeing this behavior with?

**Comment by julianrex** [comment]
@nkanetka in addition, which version of Xcode are you using?

**Comment by nkanetka** [comment]
Hey, thanks for getting back so quickly!

@jmkiley I'm using a fairly vanilla `MGLAnnotation`/ `MGPointAnnotation` setup. I have a a custom class that subclasses a `UIView` and within that I have an `MGLMapView`. Without posting the whole class (I might be able to privately send you the code for the file), I have a function to plot the point (using an `MGLPointAnnotation`) and then use the `mapView(_ mapView: MGLMapView, imageFor annotation: MGLAnnotation)` and `mapView(_ mapView: MGLMapView, didSelect annotation: MGLAnnotation)` delegate methods to serve the correct pin icon and to handle when the user selects a pin on the map. I only seem to see this issue in the delegate methods when I access the the `MGLAnnotation`.

Here are the implementations of those methods:
_Annotating Method:_
```
func annotate(pin: Coordinate?, id: String? = nil, shouldCenter: Bool = true) {
    guard let pin = pin else {
        return
    }
    let annotation = MGLPointAnnotation()
    annotation.coordinate = CLLocationCoordinate2DMake(pin.latitude, pin.longitude)
    annotation.title = id
    mapView.addAnnotation(annotation)
    if shouldCenter {
        center(coordinate: pin)
    }
}
```

_`MGLMapViewDelegate` Methods:_
```
extension MapDataView: MGLMapViewDelegate {
    func mapView(_ mapView: MGLMapView, imageFor annotation: MGLAnnotation) -> MGLAnnotationImage? {
        if annotation.title ?? nil != nil {
            return nil
        }

        guard let annotationImage = mapView.dequeueReusableAnnotationImage(withIdentifier: style.identifier) else {
            return style.annotationImage
        }
        return annotationImage
    }

    func mapView(_ mapView: MGLMapView, didSelect annotation: MGLAnnotation) {
        mapView.setCenter(annotation.coordinate, animated: true)
        selectedNoteText = annotation.title ?? nil
    }
}
```

@julianrex I'm using the most recent version of Xcode (9.4.1). Unfortunately I can't remember if this was occurring with earlier versions of Xcode

**Comment by jmkiley** [comment]
Thank you so much for the code! I am seeing the double optional in delegate methods. It looks like the optional properties from the `MGLAnnotation` protocol are being wrapped as optional again.

**Comment by 1ec5** [comment]
These MGLAnnotation properties are doubly optional because a) conforming classes aren’t required to implement them, and b) these properties are nullable. For better or worse, Swift conflates the two concepts of optionality and nullability. If you prefer to work with singly optional properties, you can create an instance of MGLPointAnnotation or have your custom class inherit from MGLPointAnnotation.

**Comment by nkanetka** [comment]
@1ec5 Thanks for looking into that. I've fixed it on my end by creating an `extension` for the `MGLAnnotation` protocol...Seems like it will be the most straightforward solution.

```
extension MGLAnnotation {
    var unwrappedTitle: String? {
        return title ?? nil
    }

    var unwrappedSubtitle: String? {
        return subtitle ?? nil
    }
}
```

Its usage is pretty straightforward:
```
extension MapDataView: MGLMapViewDelegate {
    func mapView(_ mapView: MGLMapView, imageFor annotation: MGLAnnotation) -> MGLAnnotationImage? {
        if annotation.unwrappedTitle != nil {
            return nil
        }

        guard let annotationImage = mapView.dequeueReusableAnnotationImage(withIdentifier: style.identifier) else {
            return style.annotationImage
        }
        return annotationImage
    }

    func mapView(_ mapView: MGLMapView, didSelect annotation: MGLAnnotation) {
        mapView.setCenter(annotation.coordinate, animated: true)
        selectedNote.value = annotation.unwrappedTitle
    }
}
```

**Comment by nkanetka** [comment]
Closing this as we've come up with a compromised solution :)
