### ISSUE TITLE
Clustering circles don't get invisible when point_count is 0 after update to 6.2.0

### ISSUE THREAD

**Issue by rock31** [mapbox/mapbox-gl-native#12196]
**Platform: Android
**Mapbox SDK version: 6.2.0

I'm following the example under https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/GeoJsonClusteringActivity.java to cluster my points in a Symbollayer from a GeoJSON source.

```
 for (int i = 0; i < layers.length; i++) {
      // Add some nice circles
      CircleLayer circles = new CircleLayer("cluster-" + i, "earthquakes");
      circles.setProperties(
        circleColor(layers[i][1]),
        circleRadius(18f)
      );

      Expression pointCount = toNumber(get("point_count"));
      circles.setFilter(
        i == 0
          ? gte(pointCount, literal(layers[i][0])) :
          all(
            gte(pointCount, literal(layers[i][0])),
            lt(pointCount, literal(layers[i - 1][0]))
          )
      );
      mapboxMap.addLayer(circles);
    }
```
![screenshot_20180622-134159](https://user-images.githubusercontent.com/40492016/41775012-51a4961e-7622-11e8-97e2-b43e756cb357.png)

However, since updating to 6.2.0 yesterday the clustering circles do not dissapear when the point_count value hits 0. Do I need to change anything in the filter?

This issue is also visible in the demo app.
![screenshot_20180622-134123](https://user-images.githubusercontent.com/40492016/41775029-609b45fa-7622-11e8-933d-2360c78e1b1c.png)

**Comment by tobrun** [comment]
Thank you for reaching and reporting this. Was able to reproduce with the test application.

**Comment by tobrun** [comment]
the examples have been updated with the correct expression syntax. Thank you for reporting!

**Comment by rock31** [comment]
Thanks for updating! Everythings working fine now.
