### ISSUE TITLE
user location + heatmap

### ISSUE THREAD

**Issue by hackolite** [mapbox/mapbox-gl-native#12197]
**Platform:**
**Mapbox SDK version:**

### Feature request 
Their is no example of  user location + heatmap 
Is it possible to do that ?
Thanks you, good job.

**Comment by fabian-guerra** [comment]
Hi, @hackolite. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/) or check our [documentation](https://www.mapbox.com/ios-sdk/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
