### ISSUE TITLE
feature_index.cpp assert fail

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-native#12209]
**Platform:** iOS
**Mapbox SDK version:** ios-v4.1.0

### Steps to trigger behavior

 1. Start app with vector layers that worked before

### Expected behavior
No crash or assert fail

### Actual behavior
Assertion failed: (sortedA != featureSortOrder->end()), function operator(), file ...mapbox-gl-native/src/mbgl/geometry/feature_index.cpp, line 102.

**Comment by halset** [comment]
This assert is from a62745edf9. Do not know if the problem was introduced then or before. Commenting out the two asserts now in my code.

**Comment by julianrex** [comment]
@halset Thanks for the report! We're tracking this issue over at https://github.com/mapbox/mapbox-gl-native/issues/12104

**Comment by julianrex** [comment]
Closing as a duplicate.
