### ISSUE TITLE
Binary size metrics collection is broken

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#12212]
[Binary size metrics collection](https://github.com/mapbox/mapbox-gl-native/pull/7005) hasn't been working for any of the original platforms since ~December 2017.

#### Android

Collected in `android-release-snapshot` and `android-release-tag` jobs. Currently failing silently with:

```
* File 'platform/android/MapboxGLAndroidSDK/build/intermediates/bundles/default/jni/armeabi/libmapbox-gl.so' does not exist
* File 'platform/android/MapboxGLAndroidSDK/build/intermediates/bundles/default/jni/armeabi-v7a/libmapbox-gl.so' does not exist
* File 'platform/android/MapboxGLAndroidSDK/build/intermediates/bundles/default/jni/arm64-v8a/libmapbox-gl.so' does not exist
* File 'platform/android/MapboxGLAndroidSDK/build/intermediates/bundles/default/jni/x86/libmapbox-gl.so' does not exist
* File 'platform/android/MapboxGLAndroidSDK/build/intermediates/bundles/default/jni/x86_64/libmapbox-gl.so' does not exist
* File 'platform/android/MapboxGLAndroidSDK/build/intermediates/bundles/default/jni/mips/libmapbox-gl.so' does not exist
```

#### iOS

Was only being run on Bitrise nightly builds, which were discontinued. (#10551)

#### Linux

Was being run on Travis; not carried over in #9051.

**Comment by jfirebaugh** [comment]
I'm thinking of replacing the current mechanism with one based on [GitHub checks](https://blog.github.com/2018-05-07-introducing-checks-api/).

* Create a GitHub app owned by the Mapbox organization and install it in mapbox-gl-native. This app is purely for authentication purposes (the Checks API is accessible only to GitHub apps) and has no directly-associated code or deployment.
* Add a step to our CI jobs that authenticates with the GitHub API using the app credentials, and adds a "check run" for the current SHA noting the resulting binary size. (Resulting UI looks like [this](https://github.com/jfirebaugh/github-app/runs/5191237).)
* Use some sort of convention in the check run description so the size can be parsed back out.
* Then the CI step can retrieve the corresponding check run for a PR's base and compare the size, flagging any significant increases.
* The [report page](https://mapbox.github.io/mapbox-gl-native/metrics/binary-size/) would have to be reworked. There's no list API for check runs; the best you can do is request [runs for a specific ref](https://developer.github.com/v3/checks/runs/#list-check-runs-for-a-specific-ref). So this report would become expensive to generate.

The major advantage of this approach is that it's granular at the commit level. Instead of recording the binary size only for nightly builds, we record it for every accepted PR, and can pinpoint which PR introduced a size regression.

**Comment by kkaefer** [comment]
We've recorded the binary size for every commit too, only the statistics page was less granular.

**Comment by jfirebaugh** [comment]
Can you point me to that? I only see iOS and Android nightlies in #7005, and I'm not sure how we would be distinguishing in the Cloudwatch statistics between sizes associated with merged commits and commits from branches that were never merged.

**Comment by friedbunny** [comment]
I was planning on bringing back iOS nightlies this week, mainly to collect these binary size statistics again.

> I'm thinking of replacing the current mechanism with one based on GitHub checks.

This proposal sounds like a great improvement and I’d be eager to lend a hand.

One issue for iOS is that we would need a new CI job that builds in Release mode — we don’t have this now (for individual commits or otherwise), as such a build generally takes ~2× longer to complete. There may be some acceptable shortcuts we can take to speed this up, though, like only building a subset of architectures.

**Comment by kkaefer** [comment]
Hm, it looks like we don't record the branch right now, but we only _publish_ the metrics on release branches.

**Comment by jfirebaugh** [comment]
Other random issues I've noticed:

* The `aws cloudwatch get-metric-statistics  | gzip | aws s3 cp` pipeline in [publish_binary_size.sh](https://github.com/mapbox/mapbox-gl-native/blob/37e71666d863c7025b0be8db89b3237f70ee3882/scripts/publish_binary_size.sh#L33-L47) typically misses the most recent batch of statistics added by [log_binary_size.sh](https://github.com/mapbox/mapbox-gl-native/blob/37e71666d863c7025b0be8db89b3237f70ee3882/scripts/log_binary_size.sh) (probably an eventual consistency issue with Cloudwatch). I believe the effect of this is that statistics on the report page lag by one day.
* [ios/scripts/metrics.sh](https://github.com/mapbox/mapbox-gl-native/blob/37e71666d863c7025b0be8db89b3237f70ee3882/platform/ios/scripts/metrics.sh) doesn't strip the binary as much as it could. If you run it on `make ipackage` output, the numbers will be inflated by the symbol string table, which more than doubles the size. Were we running this on `make ipackage-strip` output, back when the nightly builds were running on Bitrise?
