### ISSUE TITLE
Can't set style url from a file saved in the filesystem

### ISSUE THREAD

**Issue by fedeojeda95** [mapbox/mapbox-gl-native#12220]
I'm currently performing a migration from the version 3.7.0 to 4.1.0 of the mapbox SDK on iOS. The migration has been been really easy, except for setting the style url.

In preivous versions, we manually created a style file following the [Mapbox style specification](https://www.mapbox.com/mapbox-gl-js/style-spec), by adding the sources and layers we wanted. We created a dictionary containing the information and then saved it to the filesystem. Then, we would set the styleURL as the local filepath of the newly created file with the style json. 

This worked perfectly in version 3.7.0, but not on the newest version. Setting a predefined styleURL does work (for example `MGLStyle.satelliteStreetsStyleURL`)

The path to the file is similar to the following one (currently testing on simulator): `/Users/{username}/Library/Developer/CoreSimulator/Devices/716C4F99-7C4A-4021-BB55-4CC9C1FDEBD7/data/Containers/Data/Application/DE1869EA-8F24-45FA-BD95-BE011DABC517/Documents/layers.json`

**Platform:** iOS
**Mapbox SDK version:** 4.1.0

### Steps to trigger behavior

 1. Create a correct dictionary with all the information (version, name, sprite, glyphs, sources, layers)
 2. Save it to the filesystem as a `.json` file
 3. Set this newly created local file url as the `styleURL` of the mapView.

### Expected behavior

The style loads correctly and is shown in the map

### Actual behavior

The map does not load with the following error: 
```
[ERROR] {}[Setup]: loading style failed:
Error Domain=MGLErrorDomain Code=5 "The map failed to load because the style can't be loaded." UserInfo={NSLocalizedDescription=The map failed to load because the style can't be loaded., NSLocalizedFailureReason=loading style failed: }
```

Thank you very much in advance!

**Comment by fedeojeda95** [comment]
So I finally found the solution to this. It seems that in the latest version, the SDK is a little bit more constrained on the format of the url. While a url like the one mentioned in the issue was allowed and worked in the previous versions, it now must be an url with the format `file://{URL}`. 

My workaround was to create a new `URL` with the `absoluteString` of the previous one, and it started to work.

I believe the documentation on using a styleURL from a local file could be improved. It's a use case that's not really taken account and it's really useful!

Thanks! Hope it helps

**Comment by stdavis** [comment]
@fedeojeda95 Thank you for posting your solution! Very helpful to me.

**Comment by gino8080** [comment]
thank you @fedeojeda95 could you please be more specific with an example?

**Comment by stdavis** [comment]
I ended up having to spin up a local server: https://github.com/agrc/recreate/blob/master/src/mapStyles.js

**Comment by julianrex** [comment]
Still valid.
