### ISSUE TITLE
mbgl::style::Style::getJSON should update according to runtime styling

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#12229]
In GL JS, `map.getStyle()` invokes `style.serialize()`, which serializes the current state stylesheet state. This means that every runtime styling change is going to affect the layer property values on the returned JSON object.

In GL Native, `mbgl::style::Style::getJSON` returns the same original style JSON set via either `mbgl::style::Style::loadJSON` or `mbgl::style::Style::getURL`.

We should follow GJ JS approach and keep the returned JSON up-to-date with the runtime styling changes.

**Comment by brunoabinader** [comment]
To accomplish this, we could adopt the following plan:

1. Add `mbgl::style::Layer::asJSON()` and `mbgl::style::Source::asJSON()`, and generate `mbgl::style::Style::getJSON` on the fly, or

2. Adopt source/layer update observers in the style object that would eventually update the internal JSON stylesheet upon changes

Option 2) is tricky because it requires traversing the JSON to update individual entries on each runtime style change, but provides O(1) results for `getJSON`. Thus, I find option 1) more compelling as it keeps parity with GL JS implementation, and `getJSON` does not seem like a function that needs to be called multiple times.

Adding `{Layer,Source}::asJSON` requires a serialization mechanism similar to `Conversion::stringify`.

**Comment by jfirebaugh** [comment]
Duplicate of #7563.
