### ISSUE TITLE
OutOfMemoryError in http class

### ISSUE THREAD

**Issue by siavashabdoli** [mapbox/mapbox-gl-native#12231]
**Platform:**
**Mapbox SDK version:6.1.2**

### Steps to trigger behavior

I didn't know the steps but few user get OutOfMemoryError with this stacktrace:

Fatal Exception: java.lang.OutOfMemoryError(Heap Size=32803KB, Allocated=28956KB) Raw Text
--
  | okio.Buffer.readByteArray (Buffer.java:779)
  | okio.Buffer.readByteArray (Buffer.java:767)
  | okio.RealBufferedSource.readByteArray (RealBufferedSource.java:109)
  | okhttp3.ResponseBody.bytes (ResponseBody.java:136)
  | com.mapbox.mapboxsdk.http.HTTPRequest.onResponse (HTTPRequest.java:147)
  | okhttp3.RealCall$AsyncCall.execute (RealCall.java:153)
  | okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
  | java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1076)
  | java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:569)
  | java.lang.Thread.run (Thread.java:864)

**Comment by LukasPaczos** [comment]
Thanks for reaching out @siavashabdoli. Would you mind providing some additional more information? What were the devices affected? Are you using mapbox-hosted tiles or your own solution? Do you think you'd be able to provide a minimal reproducible example?

**Comment by siavashabdoli** [comment]
I didn't see error on my devices but As fabric reported: It's HTC with android version 4 and near 55 Mib(13%) free ram.(we just launched previous month and we only have some early adapters) at that time there's 155 active thread and lots of them belong to okhttp; im not sure is it normal or not. right now I can't find any memory leak in my project.
maybe I should not care about that device with that amount of memory. should I?
if I find any leak related to mapbox project I'll let you know by sure :) sorry and thanks.seems I should close this with this information

**Comment by LukasPaczos** [comment]
We are not seeing this issue anywhere else so I'd say that the device's performance might be the culprit here. One last question, are you using offline features or just a regular online map?

**Comment by siavashabdoli** [comment]
hm. good question. we are using an API that created by ourselves, with our custom data and style. is it related? how I can measure the performance of that data? because after we migrate to version 6 the rendering is work a little slower than mapbox api. our data was working better with version 5! after migration, we optimized too many things and generally it's better now but not like the original! and our backend team can't find good guideline and documentation for that :)
we are using cache system that provided by mapbox sdk and it has expire time.

**Comment by jfirebaugh** [comment]
> maybe I should not care about that device with that amount of memory. should I?

Yeah, it's not surprising to me that Mapbox GL runs out of memory with a limit of 32 MB. For that constrained of a device, you will probably need to stick with a raster map renderer.
