### ISSUE TITLE
Substitute the `mbgl::noncopiable::noncopyable` class with a macro

### ISSUE THREAD

**Issue by pozdnyakov** [mapbox/mapbox-gl-native#12232]
Rationals:
- a macro like 
```
#define MBGL_NONCOPYABLE(ClassName) \
   private: \
     ClassName(const ClassName&) = delete; \
     ClassName& operator=(const ClassName&) = delete
``` 
 is simpler
- mbgl::noncopiable::noncopyable is an extra type which is unnecessary and affects binary size
- mbgl::noncopiable::noncopyable is unnecessarily interfering into class hierarchy
- mbgl::noncopiable::noncopyable produces hard-to-find compilation issues with older `libcpp` environment (e.g. `mapbox-gl-native` builds on QNX cc @nagineni)

**Comment by pozdnyakov** [comment]
cc @brunoabinader @tmpsantos @kkaefer

**Comment by jfirebaugh** [comment]
Not really a fan of the macro. I'd rather [remove use of `noncopyable` (it's not usually necessary)](https://github.com/mapbox/mapbox-gl-native/issues/6545) or write out the `= delete`s explicitly.

**Comment by kkaefer** [comment]
Yeah, let's replace with explicitly writing out the constructors/move operators. We've been doing this in a few places already. This allows us to completely drop the include header as well and is arguably more idiomatic C++.

**Comment by pozdnyakov** [comment]
So, the resolution is `explicitly writing out the constructors/move operators`.
