### ISSUE TITLE
Check Out Significant Change Location Service

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1224]
Research CoreLocation's [Significant Change Location Service](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/CoreLocation/CoreLocation.html#//apple_ref/doc/uid/TP40009497-CH2-SW8).  This allows for more passive and battery light approach to location monitoring.

See how this would work with the existing Location Monitoring logic as well as permissions / background mode.

@mapbox/mobile

**Comment by mikemorris** [comment]
> The significant-change location service can also wake up an iOS app that is currently suspended or not running in order to deliver new location data.

> If you leave the significant-change location service running and your iOS app is subsequently suspended or terminated, the service automatically wakes up your app when new location data arrives.

This sounds like a "feature" we should avoid? It's less aggressive than active location monitoring in the background, but I would think that constantly waking up the app and restarting location services would have a non-negligible effect on battery usage.

**Comment by bleege** [comment]
Working on in #1422 now.
