### ISSUE TITLE
How to update MGLPolygon without removing and adding it ?

### ISSUE THREAD

**Issue by BharathM02** [mapbox/mapbox-gl-native#12248]
**Platform: IOS**
**Mapbox SDK version: 4.1.0**

 What I’m doing : 

1. Adding a polygon in the MGLMapView and add a UIImageView to facilitate Drag and Drop of the polygon.

 2. After long pressing the polygon, now it's ready to move. I get the old center point of the polygon as CLLocationCoordinate and the current point from UIImageView’s touch move function, then find the difference between old point and current point. Loop all the points of the polygon and change the coordinate values with respect to the difference between two points.

3. Now I have the new updated coordinates of the polygon . 

4. I removed the old polygon and added the new polygon in the mapView.

### Expected behaviour
Screen shot of google maps behaviour 

![google polygon](https://user-images.githubusercontent.com/36758733/42012772-6e76b3e6-7ab7-11e8-85e1-82edfae9cac0.gif)
### Actual behavior
But in  MapBox there is lots of flickering and movement doesn't seem to be native/realistic.

![mapbox polygon](https://user-images.githubusercontent.com/36758733/42012783-7e602436-7ab7-11e8-8deb-205aaebbd08f.gif)

**Comment by fabian-guerra** [comment]
Hi, @BharathM02. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/) or check our [documentation](https://www.mapbox.com/ios-sdk/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).

**Comment by BharathM02** [comment]
Hi @fabian-guerra , sorry if the title mislead you to assume this as a support ticket. This is actually a issue and a feature request. 

When i change the coordinates on a polygon, in addition to showing the new polygon, the old polygon isn't removed hence i need to remove the source polygon and add it as a new one, thus this doesn't render properly and looks non-realistic.

I hope my issue is related to https://github.com/mapbox/mapbox-gl-native/issues/6177
