### ISSUE TITLE
xcode 10 build error!

### ISSUE THREAD

**Issue by TWALKINGDEAD** [mapbox/mapbox-gl-native#12249]
xcode 10 bate1, ios 开发 编译错误信息:

/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/usr/include/CommonCrypto/module.modulemap:1:8: error: redefinition of module 'CommonCrypto'
module CommonCrypto [system] [extern_c] {
       ^
/Users/hsbc/Library/Developer/Xcode/DerivedData/HSBCHybrid-cxkzxtqdjzvfftckrzjsqwdjxgxr/Build/Intermediates.noindex/Migration.build/Testing_With_Debug-iphonesimulator/CommonCrypto.build/module.modulemap:2:8: note: previously defined here
module CommonCrypto [system] {
       ^
### Command MergeSwiftModule failed with a nonzero exit code

![ac75a9de-6680-43ed-9333-e8dfdaa16a3c](https://user-images.githubusercontent.com/18112556/42018163-c940ce34-7ae3-11e8-950c-cc3f4f665125.png)

请大神帮助解决!

**Comment by fabian-guerra** [comment]
Hi @TWALKINGDEAD. This repo is for issues related to Mapbox Maps SDK.
