### ISSUE TITLE
Transform tile hook

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-native#12240]
This is a feature request / discussion starting point.

**Backstory**
We're in a business situation where we need to distribute encrypted tiles, and decrypt them at runtime on mobile and QT apps. We believe the best approach would be to encrypt each `pbf` blob before sending them over the wire. The decryption would ideally happen just before the tile is parsed, meaning the data would stay encrypted at rest. This approach would by no means be fool proof, but it would raise the data protection bar "high enough" to meet the business requirement. We're currently using the SDK on iOS, Android, via RN and QT, making this a cross-platform issue.

**Proposal**
With this encryption situation being an absolute business requirement, we can fork the core SDK to resolve it, but we'd much rather contribute back. Our idea is to open up a general purpose API for transforming `pbf` tiles before they are passed to the parse and render pipeline. 

#10315 addressed the same issue, but the reply seemed to indicate that a fork was the way to go. Is this still the case, or would you consider accepting a PR that opens up the possibility to transform data before tile parse?

Thanks

**Comment by tmpsantos** [comment]
> We believe the best approach would be to encrypt each pbf blob before sending them over the wire. The decryption would ideally happen just before the tile is parsed

Isn't this what HTTPS is doing for you automatically?

**Comment by kristfal** [comment]
@tmpsantos HTTPS does not satisfy our business requirements, as the tiles are not encrypted at rest. 

As an example, we'll need to ship tile bundles on a standard storage unit (SD card / memory sticks) and only have them usable by units that have the correct decryption key. 

This is one of several business case we need to support with encryption in mind.

**Comment by tmpsantos** [comment]
@kristfal maybe you want to change the behavior of the compress/decompress methods.

https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/util/compression.cpp#L34

These are used when reading from the cache and storing at the cache.

**Comment by kristfal** [comment]
@tmpsantos Thanks for pointing us in that direction, yes – that may be a good alternative. We would still like to hear if this concept is something you're fine with accepting a PR for before we start moving forward.

Thanks

**Comment by kristfal** [comment]
@tmpsantos that sounds like a good proposal. I think that would fit our needs and keep the overall architecture clean.

**Comment by asheemmamoowala** [comment]
Closing since there doesn't seem to be any pending request here.

**Comment by maxtracking** [comment]
@tmpsantos Were there any developments around this feature request? Are there any other similar requests where it would be beneficial for MapBox-based apps developers to have a way to decrypt tiles just before they are parsed? Forking is one way to approach it of course but that's surely not ideal one.

**Comment by tmpsantos** [comment]
@maxtracking being very realistic, there is not enough demand for this feature. :-/

**Comment by maxtracking** [comment]
@tmpsantos OK, but how would you suggest to protect your data then? Apart from forking, that is :)

**Comment by tmpsantos** [comment]
If you disable tile caching you pretty much achieve the same result, because the tile is transmitted encrypted through the network (assuming HTTPS is used) and decrypted in memory by the network stack. It is vulnerable if the attacker has access to memory space of the process rendering the map, but the same vulnerability also exists with the decryption hook suggested.

@maxtracking we would love to help you and understand better why you need client side encryption when storing your tiles. Let's move this conversation to our customer support channel. https://support.mapbox.com/hc/en-us

**Comment by maxtracking** [comment]
@tmpsantos Before we move to support channel,  could you explain please how to disable MapBox tile caching properly? I saw a method a-la `OfflineManager.setOfflineMapboxTileCountLimit()` but it mentions in docs that it violates MapBox's T&Cs. I'm sure I missed something.

Re "the tile is transmitted encrypted through the network (assuming HTTPS is used)" - it can be different, eg for our use-case it might be read from encrypted SD card by certain SDK. If you ship such SDK to 3rd-parties,  while attacker in theory can get access to memory space, it's much harder than reading data from MB disk cache.

**Comment by tmpsantos** [comment]
@maxtracking `DefaultFileSource::setMaximumAmbientCacheSize(0)` will effectively disable the cache.

**Comment by maxtracking** [comment]
Awesome, thanks!
