### ISSUE TITLE
CI build timing out because of npm issues

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#12250]
Last couple of days seeing a lot CI failures on a variety of targets with the following output:

```
Cloning into 'mapbox-gl-js'...
Submodule path 'mapbox-gl-js': checked out 'f546de26b9b531a84fe621a5f51f4c0f791e57fb'
-- Running 'npm install' for mapbox-gl-native...
-- Running 'npm install' for mapbox-gl-js...
Makefile:305: recipe for target 'build/linux-x86_64/Sanitize/build.ninja' failed
make: *** [build/linux-x86_64/Sanitize/build.ninja] Terminated
Too long with no output (exceeded 10m0s)
```
[Link](https://circleci.com/gh/mapbox/mapbox-gl-native/119752?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

cc @mapbox/gl-core

**Comment by julianrex** [comment]
Looks like it was this issue: https://status.npmjs.org/incidents/xt6t05ffsqfh

**Comment by jfirebaugh** [comment]
This seems to be resolved now.

**Comment by jfirebaugh** [comment]
Nope. https://circleci.com/gh/mapbox/mapbox-gl-native/123453

**Comment by friedbunny** [comment]
[Still seeing this.](https://circleci.com/gh/mapbox/mapbox-gl-native/140775) 😞
