### ISSUE TITLE
[android] Write "collator" wrappers for Expression.java

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native#12268]
Follow-on for https://github.com/mapbox/mapbox-gl-native/pull/11869: Android now supports "collator" expressions, but they're not directly exposed via the SDK. Collator expressions take a dictionary-style object as an argument, e.g.:

`["collator", {"case-sensitive": false, "diacritic-sensitive": true, "locale": "en"}]`

This is a new pattern so we'll have to figure out the right Java-appropriate way to wrap it.

/cc @LukasPaczos @tobrun

**Comment by tobrun** [comment]
Looking into this and noticing that the expression evaluate is expecting an object, this isn't yet supported in jni for our filter/properties conversion system (see todo [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/src/style/android_conversion.hpp#L52)). Currently taking the approach to represent an object as Map<String, Object> where the key/value represent the fields of the object.
