### ISSUE TITLE
Disallow internal "filter-*" expressions in style JSON

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-native#12264]
Follow-up to https://github.com/mapbox/mapbox-gl-native/pull/12263, which fixes an assertion failure / crash caused by attempting to parse expressions that use internal `filter-*` expressions.  

We should disallow these (but gracefully, with an error message) from user code, since we don't want users' style documents or runtime styling code to rely on them.

**Comment by kkaefer** [comment]
This requires converting filters to full-on expressions, rather than special internal `filter-*` expressions; otherwise we'd break the workflow of "getFilter" -> "setFilter" when serializing them inbetween.

**Comment by jfirebaugh** [comment]
> requires converting filters to full-on expressions

It's not possible to do this without regressing performance.

**Comment by anandthakker** [comment]
I don't think that's required, @kkaefer:  for legacy filters, we could store the original input on `Filter` and return that from `getFilter`, rather than serializing the `filter-*` expression
