### ISSUE TITLE
Document iOS GL Installation Instructions

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1226]
Document instructions for integrating Mapbox GL iOS into an app.  Instructions should be for both Objective-C and for Swift.  Known issues and workarounds should also be listed.

@mapbox/mobile

**Comment by 1ec5** [comment]
https://github.com/mapbox/mapbox-gl-native/wiki/Installing-Mapbox-GL-for-iOS

**Comment by 1ec5** [comment]
TODO: Describe [this GIF](https://github.com/mapbox/mapbox-gl-native/pull/1184#issue-65976641) for an easier setup workflow.

**Comment by friedbunny** [comment]
> There is no way to pin versions right now; that will come when we release officially and on the CocoaPods master repository.

Hrm, I missing why the `podspec` file isn't in the repo root — then this would work, in theory:

```c
pod 'MapboxGL', :git => 'https://github.com/mapbox/mapbox-gl-native.git', :tag => 'ios-0.2.9'
```

Did it used to be or will it soon be? The [Releasing Mapbox GL for iOS](https://github.com/mapbox/mapbox-gl-native/wiki/Releasing-Mapbox-GL-for-iOS) wiki page thinks it is, anyway.

**Comment by incanus** [comment]
It's not in the repo root because it doesn't have to be when you use the `:podspec` line per https://github.com/mapbox/mapbox-gl-native/wiki/Installing%20Mapbox%20GL%20for%20iOS#using-cocoapods. It's better for org to keep this under `./ios` since it's temporary anyway (until we get the pod ready to be published to the world). 

As for tags, all that a `:tag` points to in our repo is the same podspec. Right now our library is prebuilt and installed via CocoaPods as a static library (via faux framework). If we get to a point where it's worth having CocoaPods actually build it (all....) from source, then tags will be a better way. Right now CocoaPods is basically a convenience method for getting at the static library we've now got Travis rolling.

**Comment by friedbunny** [comment]
Ah, I see that it was moved back to `./ios` in #1227.

@incanus Right, being able to specify a `:tag` would only be useful as a poor-man's version pinning, not for building the library from source or anything.

(Hope your teeth and general head-region are/is feeling better, by the way.)

**Comment by bleege** [comment]
Will also want to document Pause / Restart Metrics functionality from #1216 for Background Modes where there are no other CLLocationManager/CLLocationManagerDelegates actively listening for location updates.

**Comment by 1ec5** [comment]
@bleege I added documentation for pausing and resuming metrics collection here; please have a look:

https://github.com/mapbox/mapbox-gl-native/wiki/Installing-Mapbox-GL-for-iOS

**Comment by bleege** [comment]
Thanks @1ec5!  I edited it to clarify the scenarios for both implementing Opt Out and when pause / resume needs to be used.  That said it's now looking a bit blocky to me.  Maybe a 2nd pass would do it some good to be more approachable.  I'll take another crack at it tomorrow with fresh eyes.

**Comment by 1ec5** [comment]
I [copyedited it pretty aggressively](https://github.com/mapbox/mapbox-gl-native/wiki/Installing-Mapbox-GL-for-iOS/_compare/444f2ec5c682a44de7ba2eaba965c0b62d931ff9...679803418b22c6b9348cc99974c6cabd7484b9a5) to match the tone of the rest of the page, anticipating that this will be a starting point for a Mapbox guide. Hopefully I got the semantics right.

**Comment by bleege** [comment]
Thank you for distilling the content into a more tone matching style @1ec5.  That was definitely needed.  I just made a [minor clarification edit](https://github.com/mapbox/mapbox-gl-native/wiki/Installing-Mapbox-GL-for-iOS/e5414d813355f973df5b7157cd9bb19d5c4cc378) to make sure that people only do this when the app is in the background.  I _believe_ the current state is that Location metrics will be tracked while the app is in the foreground and active once the app has requested and user has granted location access regardless if the app is actively tracking location itself yet.

**Comment by 1ec5** [comment]
@bleege, are we done here?

**Comment by bleege** [comment]
Let's hold off on closing this for now @1ec5 as there are still some logistics to be worked out.

**Comment by incanus** [comment]
Clarification: the scope here applies to metrics background pause/resume and I will move this soon to the `mapbox-gl-ios` repo as a goal to address there and close here.

**Comment by friedbunny** [comment]
I don't think the `Settings.bundle` section is clear enough — for one, it never actually says `Settings.bundle`.

**Comment by incanus** [comment]
`mapbox-gl-ios` is up and launched, so I think we just need `Settings.bundle` docs here.

**Comment by bleege** [comment]
`Settings.bundle` is now documented and live at https://github.com/mapbox/mapbox-gl-ios/pull/2.

This should complete this ticket.
