### ISSUE TITLE
[android] Rendering artifacts in Samsung Galaxy S - Android 4.1.1

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#12277]
While testing [Mapbox Navigation test app](https://github.com/mapbox/mapbox-navigation-android/tree/master/app) found 👇

**Platform:** Android 4.1.1 Samsung Galaxy S (GT-I9000)
**Mapbox SDK version:** `6.2.1`

### Steps to trigger behavior

 1. Mapbox Navigation test app
 2. Open `Navigation Views` activity
 3. Long press map to place destination
 4. Click on `LAUNCH NAVIGATION` button
 5. Observe unexpected rendering issues while navigating 👀

![gt-i9000-runtime-styling-artifacts](https://user-images.githubusercontent.com/1668582/42170572-34595d5e-7e17-11e8-834f-96183f32d8cf.png)

![gt-i9000-shade-artifacts](https://user-images.githubusercontent.com/1668582/42170579-3995a4ee-7e17-11e8-9cab-1e272a1af59a.png)

Noting that also saw some other rendering artifacts (street names, etc.) in that device. 

If you want any further testing done, let me know. Happy to help!

cc @LukasPaczos

**Comment by lilykaiser** [comment]
@Guardiola31337 is this issue specific to one device?

**Comment by Guardiola31337** [comment]
@lilykaiser 
> is this issue specific to one device?

Yeah, as mentioned in OP I've only seen those rendering artifacts in that pretty old Samsung Galaxy S (GT-I9000) running on Android 4.1.1

Please, let me know if there's anything I can help you with moving forward here.
