### ISSUE TITLE
[Android] PropertyFactory.textColor not working with Expressions

### ISSUE THREAD

**Issue by DiogoAndre** [mapbox/mapbox-gl-native#12273]
Hi! 👋 

I'm having issues trying to style layers. I've tried a few different things but nothing worked. I also saw that the `android-v6.3.0-alpha.1` release has some fix related to color. I wanted to try it before submitting the issue but coudn't get the snapshot to work. 😞

**Platform:** Android
**Mapbox SDK version:** 6.2.1

### Steps to trigger behavior

 1.  Assign a property to a Feature storing a color 
```kotlin
val props: JsonObject = JsonObject()
props.addProperty("vColor", Color.MAGENTA)
val feature = Feature.fromGeometry(Point.fromLngLat(pos.lon,pos.lat), props)
```
 2. Try to style the text of the feature based on an expression
```kotlin
mapSymbols.setProperties(
  PropertyFactory.textColor(toColor(Expression.get("vColor")))
)
```

```kotlin
mapSymbols.textColor.expression  will be null
```
 3. Styling with the color directly works
```kotlin
mapSymbols.setProperties(
  PropertyFactory.textColor(Color.MAGENTA)
)
```

### Expected behavior

Text be colored with the specified color.

### Actual behavior

Text defaults to black color.

**Comment by tobrun** [comment]
@DiogoAndre 

The color representation within gl-native is not of type int and the toColor operation is not able to convert an int color (as Android developer though this is what we are used to). To fix this issue you can do the following:

```kotlin
val props: JsonObject = JsonObject()
props.addProperty("vColor", PropertyFactory.colorToRgbaString(Color.MAGENTA))
val feature = Feature.fromGeometry(Point.fromLngLat(pos.lon,pos.lat), props)
```

The rgba string representation is something core should be able to interpret. For completeness, there are also rgb and rgba expressions. Let us know if you have any additional questions!

**Comment by DiogoAndre** [comment]
Thanks, @tobrun!
