### ISSUE TITLE
ZoomButtonsController is deprecated with Oreo

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#12275]
`ZoomButtonsController` is deprecated in API level >= 26 (Oreo) and we should either drop the support for the controller or roll out our own implementation.

**Comment by LukasPaczos** [comment]
Noting, that in order to support non-multi-touch devices we should implement our own solution for the zoom buttons instead of dropping the support completely.

/cc @tobrun

**Comment by tobrun** [comment]
Capturing from discussion with @chloekraw and @LukasPaczos, we are not going to show the zoombutton controller for Android O and above.

**Comment by tobrun** [comment]
Landed in #13197 on `master` and #13198 on `android-semver`
