### ISSUE TITLE
Consolidate Android release builds

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#12299]
We currently have three flavors of Android release builds:

* android-build-release
	ignores master/release-*
        no maven publishing
* android-release-snapshot
	only master/release-*
	includes maven publishing
* android-release-tag
	only android-v* tags
	has “Update version name” step
	includes maven publishing

These builds mostly do the same thing, and are intended to be mutually exclusive. However, having different job names means the first `android-build-release` build on a new branch never has a matching cache:

```
No cache is found for key: v3/android-build-release/arch1-linux-amd64-6_62/binary-size-diffs/19gUdVQmMqkCxZ3cwNeNKy_0nUe9as0xnnyDpV5u5FE=
No cache is found for key: v3/android-build-release/arch1-linux-amd64-6_62/master/19gUdVQmMqkCxZ3cwNeNKy_0nUe9as0xnnyDpV5u5FE=
```

The first key doesn't match because it's the first build on the branch. The second key doesn't match because the master branch doesn't build the `android-build-release` job.

We should consolidate these three jobs under a single `android-release` job and run the “Update version name” and maven publishing steps conditionally.

**Comment by tobrun** [comment]
cc @LukasPaczos
