### ISSUE TITLE
Overzoom cached/offline tiles

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#123]
Something that would boost perceived performance, at least on raster, is to consider a `TileData::state::cached` somewhere between `invalid` and `loaded`. It's odd because it's logic branching, not serial, but with this we could consider loading and parsing/decoding for use in child/parent tile scenarios. 

To put it another way, this wouldn't require the user to have ever zoomed to a parent or child tile zoom level in the current run of the app in order to make use of those tiles for drawing. If I launch the app at `z8` but have one or more `z7` tiles cached, they could get drawn until I get all the `z8` tiles I need for optimum resolution. 

There's a tradeoff between spending time pulling these from cache vs. spending resources in getting the `z8` tiles, but it might be worthwhile.

**Comment by jfirebaugh** [comment]
Implemented in #5143.
