### ISSUE TITLE
LatLngBounds.Builder.includes() performance

### ISSUE THREAD

**Issue by florianPOLARSTEPS** [mapbox/mapbox-gl-native#12316]
Hi guys,

I stumbled upon a rather big performance problem in the `LatLngBounds.Builder` API recently. The issue is within the `LatLngBounds.Builder.includes(List<LatLng>)` function.

Calling `Builder.includes(List<LatLng>)` with a huge list of `LatLngs`, will cause performance to degrade exponentially. The issue is the `contains` call here:

```
public Builder include(@NonNull LatLng latLng) {
      if (!latLngList.contains(latLng)) {
        latLngList.add(latLng);
      }
      return this;
}
```

If I bypass the builder, the performance improves drastically. Maybe the builder could expose a method where one can bypass the contains check and just set the `latLngList`.

### Steps to reproduce

 1. Generate a long list of `LatLngs` ( I tested with 30.000 )
 2. Build the bounds with `LatLngBounds.Builder.includes()`
 3. Wait

### Expected behavior

The API should be much faster

### Actual behavior

The API has exponential complexity in its implementation and takes a long time to compute.

### Configuration

**Android versions:** Any
**Device models:** Any
**Mapbox SDK versions:** 6.1.3

**Comment by tobrun** [comment]
Thanks for the report @florianPOLARSTEPS, fix in #12335
