### ISSUE TITLE
Bug: Android 6.2.1 Polygons mush

### ISSUE THREAD

**Issue by psinetron** [mapbox/mapbox-gl-native#12318]
When polygon does not fit into the camera I see polygons noise when camera move.
### Steps to reproduce

 1. draw polygon with fitting to camera and move. All Ok
 2. zoom in 
 3. move camera and see noise

### Sample
![ezgif com-video-to-gif 5](https://user-images.githubusercontent.com/3624600/42328649-841da428-8077-11e8-9cfb-6449b615c2b5.gif)

### Configuration

**Android versions:**  All
**Device models:** Xiaomi
**Mapbox SDK versions:** 6.2.1

**Comment by LukasPaczos** [comment]
Looks similar to https://github.com/mapbox/mapbox-gl-native/issues/11469. Could you verify that your polygon geometries are enclosed (first and last points are the same)?
