### ISSUE TITLE
strategy for bundling sprite data with framework

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1232]
We may be able to bundle style sprite image/JSON with the framework to enhance performance.

**Comment by barrycug** [comment]
This is very important。

**Comment by incanus** [comment]
Also part of what @kkaefer is looking into for more flexible, runtime sprites for b3.

**Comment by kkaefer** [comment]
You can already bundle sprites with the application and reference them from the stylesheet with an `asset://` URL.

**Comment by jfirebaugh** [comment]
#3894 is the direction I think we should go here.
