### ISSUE TITLE
Current location marker not showing with Fusetools

### ISSUE THREAD

**Issue by Dhvl-Golakiya** [mapbox/mapbox-gl-native#12334]
Hi,

I am using Mapbox with Fusetools. I am using old version of Mapbox and navigation-plugin because latest verision gives error with Fusetools.

When map load, it is moving to current location of the user but blue location marker is not showing.

in `gradle.build`:
```
compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.4.1') { 
     transitive = true
}
compile ('com.mapbox.mapboxsdk:mapbox-android-navigation:0.10.0') { 
    transitive = true
}
compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.10.0') { 
    transitive = true;
}
```

Please check this Fusetools project.
[MapBoxSample.zip](https://github.com/mapbox/mapbox-gl-native/files/2170393/MapBoxSample.zip)
Let me know if you need any help from me with Fusetools.

**Comment by tobrun** [comment]
@Dhvl-Golakiya nothing comes to mind that would break Fusetools integration with the location marker. Would you be able to retest with a more recent version of our depenencies?
 - For maps v6.2.1 is the latest stable
 - For navigation v0.15.0 is the latest stable

**Comment by tobrun** [comment]
Closing this as stale, feel free to create a new issue if still an issue!
