### ISSUE TITLE
Question: MapBox Android - Define PropertyFactory.iconImage using expressions

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#12342]
I am trying to define the value for the method `PropertyFactory.iconImage` for my layer object. The return value `PropertyValue<String>` should use a certain field inside the Feature to define it's value.

The result could look something like that:

`PropertyFactory.iconImage(Expression.step(Expression.get("myfield"),"mydefaultValue", Expression.Stop.stop("case1", "valueForCase1"), Expression.Stop.stop("case2", "valueForCase2"));`

Unfortunately I was not able to find a similar solution so far.

### Configuration

**Android versions:** All
**Device models:** All
**Mapbox SDK versions:** 6.2.1

**Comment by tobrun** [comment]
@Mordag thank you for reaching out! The issue with the expression shown is that the step expression requires an input of type number. Capturing from the style spec:

```
["step",
    input: number,
    stop_output_0: OutputType,
    stop_input_1: number, stop_output_1: OutputType,
    stop_input_n: number, stop_output_n: OutputType, ...
]: OutputType
```

What you are looking for is the match expression that allows to use String input as well:

```
["match",
    input: InputType (number or string),
    label_1: InputType | [InputType, InputType, ...], output_1: OutputType,
    label_n: InputType | [InputType, InputType, ...], output_n: OutputType, ...,
    default: OutputType
]: OutputType
```

To trouble shoot expressions, you should be able to see a log message indicating what went wrong.
Closing as answered, let us know if you have any more questions!

**Comment by Mordag** [comment]
@tobrun Thank you for the answer. Unfortunately it is difficult for me to find the relevant methods in Android to solve the required expressions. The method `Expression.match` has two versions: (`Expression`) or (`Expression` for input, `Expression` for default, `Expression.Stop`)

My current state looks like that:

```Java
SymbolLayer("asset-layer", "assetMapDataSource")
               .withProperties(
                            PropertyFactory.iconImage(Expression.match(
                                    Expression.get("asset_type"), Expression.literal("bbq_default"),
                                    Expression.stop("bridge", Expression.literal("bridge_default"))))
)
```

**Comment by Mordag** [comment]
Ok thank you. I found the problem and my data source was to blame. I actually have another question, but I will open a new issue for that.
