### ISSUE TITLE
Symbols canned up when switching between high and low zoom levels

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#12356]
I noticed this behavior recently while switching from the demo route (`E`) and going back to world view (`X`) in our GLFW demo app:
![screenshot from glyph-glitch ogv](https://user-images.githubusercontent.com/76133/42518625-f3105104-846a-11e8-88cb-3d6879170dab.png)
From the image above, you can see all the symbols fading from a single point on the map. @ChrisLoer 
 I am assuming this as a side effect of https://github.com/mapbox/mapbox-gl-native/pull/10436 - I'd like to propose that we establish a zoom range threshold for the fade transition to happen.

/cc @mapbox/gl-core

**Comment by ChrisLoer** [comment]
This behavior was introduced with cross-tile symbol fading -- we were aware of it and decided it was OK:

https://github.com/mapbox/mapbox-gl-native/pull/10468#issuecomment-344738893

But if it's a problem, it shouldn't be too hard to address, I think we'd basically put some kind of "zoom delta cap" on the tiles that we hold onto in the "holdForFade" logic, so that maybe after you crossed three zoom levels out we just immediately made symbols disappear.

**Comment by ChrisLoer** [comment]
@m-stephen if you're interested in taking a look at this, probably the easiest place to modify is right here in the `TilePyramid` logic:

https://github.com/mapbox/mapbox-gl-native/blob/9e7694cb38982cf0434be64b8894c1628236d0d9/src/mbgl/renderer/tile_pyramid.cpp#L199-L205

If you look higher up in that logic, you'll see where we calculate the `idealZoom` for the transform state. I think the logic you want would be something like "hold for fade if the `holdForFade() == true` and the tile's zoom is within +/- 1 of the `idealZoom`". That way, for instance, if we're rendering at z12.4, we'll show z12 tiles but we'll also hold onto z13 or z11 tiles for fading. If we were holding onto a z13 tile while zooming out, we'd stop rendering the tile as soon as we crossed to z11.99. When you crossed from z12 to z11.99, the z13 tile would get discarded. If you crossed back to z12, it wouldn't start rendering again (you'd have to go all the way back to z13 to get it to show again).

I think we should try making the change and play around with it for a while to make sure it gives us a visual effect we like -- we might want to tweak the "how long to hold" parameters one way or another.

**Comment by kkaefer** [comment]
We've added something similar to GL JS recently: https://github.com/mapbox/mapbox-gl-js/pull/8628
