### ISSUE TITLE
Adding images to Layers with SDF set to true not working

### ISSUE THREAD

**Issue by DiogoAndre** [mapbox/mapbox-gl-native#12357]
When using the new support for SDF images introduced in `6.3.0-alpha1` images are not shown at all.

ps: Using PNG images or WebP images.

### Steps to reproduce

 1. Add an image to the layer
```kotlin
val myIconDraw = getResources().getDrawable(R.drawable.ic_myIcon, null)
val myIconImg = BitmapUtils.getBitmapFromDrawable(myIconDraw)
mainMap?.addImage("myImg", myIconImg, true)
```
 2. Create a layer and add an icon image
```kotlin
val mapSymbols = SymbolLayer("MyImgs-symbols", "images")
mapSymbols.setProperties(
  PropertyFactory.iconImage("myImg"),
  PropertyFactory.iconColor(Color.MAGENTA),
  PropertyFactory.textField("My Label."),
  PropertyFactory.textColor(Color.MAGENTA),
)
```
 3. load map

### Expected behavior

The image and the text are tinted with the same color.

### Actual behavior

Only text appears(tinted). Images are not shown.

### Configuration

**Android versions:**  API 28
**Device models:** Nexus
**Mapbox SDK versions:** 6.3.0

**Comment by tobrun** [comment]
@DiogoAndre 

thank you for the report but unable to reproduce atm:

![image](https://user-images.githubusercontent.com/2151639/42569346-84350364-8510-11e8-9900-b1b32aaf3969.png)

Does you image qualify as a glyph/template image?

**Comment by DiogoAndre** [comment]
Thanks for looking into this @tobrun!

> Does you image qualify as a glyph/template image?

Maybe that's what I'm missing. In iOS I can just declare an image to be a template with: 

```swift
UIImage.init(named: "myImg")?.withRenderingMode(.alwaysTemplate)
```
I assumed that the `sdf: true` in adroid was simmilar. 

Here's an example resource I'm using: 
![circle](https://user-images.githubusercontent.com/572843/42570391-1e4a5f20-84ea-11e8-97d9-351ae5d85e9b.png)

**Comment by DiogoAndre** [comment]
Solved using SVG icons.  Thanks!
