### ISSUE TITLE
How to use didChangeUserTrackingMode

### ISSUE THREAD

**Issue by matheusmatos** [mapbox/mapbox-gl-native#12369]
Hi guys,

I'm trying to listen the `didChangeUserTrackingMode` event.

I want to show the _recenterButton_ only when the `userTrackingMode` is not `followWithHeading`.

How can I know that the user have changed the `trackingMode` moving the map?

There's an example of what I'm trying to do:

```
import Mapbox

class MapViewController: UIViewController, MGLMapViewDelegate {
    var mapView: MGLMapView!
    @IBOutlet var button: UserLocationButton!

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let url = URL(string: "mapbox://styles/mapbox/navigation-guidance-night-v2")
        mapView = MGLMapView(frame: view.bounds, styleURL: url)
        mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        mapView.delegate = self
        
        view.addSubview(mapView)
        
        // Create button to allow user to change the tracking mode
        setupLocationButton()
    }
    
    func mapView(_ mapView: MGLMapView, didChangeUserTrackingMode mode: Any!, animated: Bool) {
        print("didChangeUserTrackingMode")
    }

    // Update the user tracking mode when the user toggles through the
    // user tracking mode button.
    @IBAction func locationButtonTapped(sender: RecenterButton) {
        ...
    }
    
    // Button creation and autolayout setup
    func setupLocationButton() {
        ...
    }
}
```

Really thanks!

**Comment by fabian-guerra** [comment]
Hi, @matheusmatos. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/) or check our [documentation](https://www.mapbox.com/ios-sdk/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
