### ISSUE TITLE
MapBox Android - Expression.literal(array) is not working for PropertyFactory.lineDasharray

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#12362]
I am trying to define the value for the method `PropertyFactory.lineDasharray` for my layer object. My problem is the value seems not to work.

My current state looks like that:

```kotlin
PropertyFactory.lineDasharray(Expression.match(
      Expression.get("track_type"), Expression.literal(arrayOf(.01f, 3f)),
      Expression.stop("bushwalking", Expression.literal(arrayOf(.03f, 3f))
))
```

Should I use a different Expression method for the array? Using this solution, the line is displayed as a solid line. If I use the `PropertyFactory.lineDasharray(arrayOf(.01f, 3f))` the line is displayed correctly using the expected dash pattern.

### Configuration

**Android versions:** All
**Device models:** All
**Mapbox SDK versions:** 6.2.1

**Comment by tobrun** [comment]
Capturing from the style-spec that this property isn't data driven (yet):
 - https://www.mapbox.com/mapbox-gl-js/style-spec/#paint-line-line-dasharray

You will have to work around this by using a layer for each track_type and filtering out other data in that layer. Closing ticket as answered, thank you for reaching out and using our products!

**Comment by hrach** [comment]
Is there an issue for tracking this feature please?
