### ISSUE TITLE
changing minzoom value in MapParameter for 3d-buildings

### ISSUE THREAD

**Issue by frankipl** [mapbox/mapbox-gl-native#12376]
Hi
Not sure whether this is good place for that
I'm using mapboxgl in Qt application (5.10.1), I have app based on this example:
[https://github.com/tmpsantos/qmapboxglapp/tree/tmpsantos-cheapruler](https://github.com/tmpsantos/qmapboxglapp/tree/tmpsantos-cheapruler)
There is layer with 3D buildings

`MapParameter {
                type: "layer"

                property var name: "3d-buildings"
                property var source: "composite"
                property var sourceLayer: "building"
                property var layerType: "fill-extrusion"
                property var minzoom: mapPage.buildingZoom
            }

            MapParameter {
                type: "filter"

                property var layer: "3d-buildings"
                property var filter: [ "==", "extrude", "true" ]
            }

            MapParameter {
                type: "paint"

                property var layer: "3d-buildings"
                property var fillExtrusionColor: "#00617f"
                property var fillExtrusionOpacity: .6
                property var fillExtrusionHeight: { return { type: "identity", property: "height" } }
                property var fillExtrusionBase: { return { type: "identity", property: "min_height" } }
            }`

I have bound minzoom to mapPage.buildingZoom property so I thought I could change this layer visibility but when I change mapPage.buildingZoom property app is crashing with an error:

`terminate called after throwing an instance of 'std::runtime_error'
  what():  Layer 3d-buildings already exists`

Can I do something about it?

Best Regards
Marek

**Comment by brunoabinader** [comment]
Hi Marek, please open an issue in Qt's [bug reports](https://bugreports.qt.io) for that - please select "Location: Mapbox plugins" in Component field. Thanks!
