### ISSUE TITLE
Annotation on iPhone X wrong position in landscape on simulator

### ISSUE THREAD

**Issue by nole87** [mapbox/mapbox-gl-native#12386]
SDK 4.1

### Steps to reproduce
<img width="400" alt="untitled" src="https://user-images.githubusercontent.com/4254736/42723406-476a697a-875d-11e8-9d0d-9cb77d5b73e4.png">

**Comment by nole87** [comment]
Look "i" over mapbox logo in bottom left...

**Comment by jfirebaugh** [comment]
Okay, thanks for letting us know.
