### ISSUE TITLE
Conflict android.arch.lifecycle:runtime:1.1.0 -> 1.1.1 When using version 6.2.1 and Android Support libs

### ISSUE THREAD

**Issue by leelx78** [mapbox/mapbox-gl-native#12383]
Hi

With 6.2.1 I get this error in Android Studio which was not there with 6.1.3.

> Caused by: java.lang.RuntimeException: Android dependency 'android.arch.lifecycle:runtime' has different version for the compile (1.1.0) and runtime (1.1.1) classpath. You should manually set the same version via DependencyResolution

Then I looked at dependencies. 6.2.1 indeed has runtime 1.1.1

> +--- com.mapbox.mapboxsdk:mapbox-android-sdk:6.2.1
|    +--- com.mapbox.mapboxsdk:mapbox-android-telemetry:3.1.3
|    |    +--- com.mapbox.mapboxsdk:mapbox-android-core:0.2.0
|    |    +--- com.squareup.okhttp3:okhttp:3.10.0
|    |    |    \--- com.squareup.okio:okio:1.14.0
|    |    +--- com.google.code.gson:gson:2.8.2
|    |    \--- android.arch.lifecycle:extensions:1.1.1
|    |         +--- android.arch.lifecycle:runtime:1.1.1 (*)
|    |         +--- android.arch.core:common:1.1.1 (*)
|    |         +--- android.arch.core:runtime:1.1.1 (*)
|    |         +--- com.android.support:support-fragment:26.1.0 -> 27.1.1 (*)
|    |         +--- android.arch.lifecycle:common:1.1.1 (*)
|    |         +--- android.arch.lifecycle:livedata:1.1.1
|    |         |    +--- android.arch.core:runtime:1.1.1 (*)
|    |         |    +--- android.arch.lifecycle:livedata-core:1.1.1 (*)
|    |         |    \--- android.arch.core:common:1.1.1 (*)
|    |         \--- android.arch.lifecycle:viewmodel:1.1.1 (*)
|    +--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:3.2.0
|    |    \--- com.google.code.gson:gson:2.8.2
|    +--- com.mapbox.mapboxsdk:mapbox-android-gestures:0.2.0
|    |    \--- com.jakewharton.timber:timber:4.5.1 -> 4.7.0
|    +--- com.android.support:support-annotations:27.1.1
|    +--- com.android.support:support-fragment:27.1.1 (*)
|    +--- com.jakewharton.timber:timber:4.7.0
|    \--- com.squareup.okhttp3:okhttp:3.10.0 (*)

But I see that the support library has dependencies linking to runtime 1.1.0?

> +--- com.android.support:support-v4:27.1.1
|    +--- com.android.support:support-compat:27.1.1
|    |    +--- com.android.support:support-annotations:27.1.1
|    |    \--- android.arch.lifecycle:runtime:1.1.0 -> 1.1.1
|    |         +--- android.arch.lifecycle:common:1.1.1
|    |         |    \--- com.android.support:support-annotations:26.1.0 -> 27.1.1
|    |         +--- android.arch.core:common:1.1.1
|    |         |    \--- com.android.support:support-annotations:26.1.0 -> 27.1.1
|    |         \--- com.android.support:support-annotations:26.1.0 -> 27.1.1
|    +--- com.android.support:support-media-compat:27.1.1
|    |    +--- com.android.support:support-annotations:27.1.1
|    |    \--- com.android.support:support-compat:27.1.1 (*)
|    +--- com.android.support:support-core-utils:27.1.1
|    |    +--- com.android.support:support-annotations:27.1.1
|    |    \--- com.android.support:support-compat:27.1.1 (*)
|    +--- com.android.support:support-core-ui:27.1.1
|    |    +--- com.android.support:support-annotations:27.1.1
|    |    +--- com.android.support:support-compat:27.1.1 (*)
|    |    \--- com.android.support:support-core-utils:27.1.1 (*)
|    \--- com.android.support:support-fragment:27.1.1
|         +--- com.android.support:support-compat:27.1.1 (*)
|         +--- com.android.support:support-core-ui:27.1.1 (*)
|         +--- com.android.support:support-core-utils:27.1.1 (*)
|         +--- com.android.support:support-annotations:27.1.1
|         +--- android.arch.lifecycle:livedata-core:1.1.0 -> 1.1.1
|         |    +--- android.arch.lifecycle:common:1.1.1 (*)
|         |    +--- android.arch.core:common:1.1.1 (*)
|         |    \--- android.arch.core:runtime:1.1.1
|         |         +--- com.android.support:support-annotations:26.1.0 -> 27.1.1
|         |         \--- android.arch.core:common:1.1.1 (*)
|         \--- android.arch.lifecycle:viewmodel:1.1.0 -> 1.1.1
|              \--- com.android.support:support-annotations:26.1.0 -> 27.1.1

Any workaround? As far as I know com.android.support:support-v4:27.1.1 is the latest and I need that in.

Thanks

**Comment by leelx78** [comment]
Can anybody replicate this?

**Comment by LukasPaczos** [comment]
Looking at the arch components release notes there are no impactful for us changes between `1.1.0` and `1.1.1`. Could you try manually excluding arch components dependency?
```
implementation ("com.mapbox.mapboxsdk:mapbox-android-sdk:6.2.1") {
        exclude group: 'android.arch.lifecycle', module: 'runtime'
    }
```

This change was introduced in https://github.com/mapbox/mapbox-events-android/pull/157, do you think we can downgrade to `1.1.0` @electrostat?

**Comment by leelx78** [comment]
Thanks @LukasPaczos.

Tried it but still complaining about it in a different place

> Android dependency 'android.arch.lifecycle:livedata-core' has different version for the compile (1.1.0) and runtime (1.1.1) classpath. You should manually set the same version via DependencyResolution

Also tried to add group "android.arch.lifecycle:livedata-core" but still not working

**Comment by electrostat** [comment]
@LukasPaczos I'll look into if downgrading is an option for us.

**Comment by electrostat** [comment]
@LukasPaczos we are a go for downgrading. PR is here: https://github.com/mapbox/mapbox-events-android/pull/183

**Comment by anbarasuthresnathan** [comment]
> @LukasPaczos I'll look into if downgrading is an option for us.

Change implementation to api
