### ISSUE TITLE
How to debug the native source code of android sdk?

### ISSUE THREAD

**Issue by mrrichardli** [mapbox/mapbox-gl-native#12380]
hello, I am a programmer in GIS, and I am also a follower of mapbox。 I want to read, debug, and finally contribute to the program of mapbox-gl-native android sdk. But here,  I'm blocked with the problem of ** how to debug the native code of MapBox Android SDK via Android Studio ?** in the process of reading source code.  I searched for answer through stackoverflow & google, and found no solution for it .  

 **could you be kind enough to give me some instruction?**
### Steps to reproduce

 1.
 2.
 3.

### Configuration

**Android versions:** 
**Device models:** 
**Mapbox SDK versions:**

**Comment by tobrun** [comment]
Hey thank you for showing interest in the Android SDK. To debug the native code you will have to get the project up and running and download lldb-debugger from the android sdk tools. 

After that your run configurations will be changed when you toggle to the debug tab. Set debug type to Native and your breakpoints in cpp code should be hit when running in debug mode. 
 
<img width="1069" alt="screen shot 2018-07-13 at 13 14 48" src="https://user-images.githubusercontent.com/2151639/42688975-c6bb841c-869e-11e8-9759-653cbf1472b4.png">

Closing as answered
