### ISSUE TITLE
Location annotation padding

### ISSUE THREAD

**Issue by nole87** [mapbox/mapbox-gl-native#12398]
On android, there are:

int[] padding;

                    if (getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT) {
                         padding = new int[]{0, displayMetrics.heightPixels / 6, 0, 0};
                    } else {
                        padding = new int[]{0, displayMetrics.heightPixels / 6, 0, 0};
                    }

                    LocationLayerOptions options = LocationLayerOptions.builder(MainActivity.this)
                            .padding(padding)
                            .accuracyAlpha(0)
                            .build();

How to do that in iOS swift? I find mapView.setUserLocationVerticalAlignment(MGLAnnotationVerticalAlignment.bottom, animated: true) but only for center, bottom and top, I also need to better adjust with point precision ...
**Mapbox SDK versions:** 
SDK 4.1

**Comment by fabian-guerra** [comment]
Hi, @nole87. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/) or check our [documentation](https://www.mapbox.com/ios-sdk/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
