### ISSUE TITLE
[Android] Offline region download crash

### ISSUE THREAD

**Issue by BharathMG** [mapbox/mapbox-gl-native#12390]
Downloading Offline region crashes with disk error. 

Minimum Zoom Level: 10.0
Maximum Zoom Level: 16.0
Bounding Box: N:12.9774; E:77.6458; S:10.8525; W:76.2398
Region Snapshot,

![mapboxregion](https://user-images.githubusercontent.com/977859/42753515-ce0ce720-890e-11e8-9e9b-d852acfe2286.png)

```
  mbgl  I  {DefaultFileSour}[Database](6410): statement aborts at 58: [DELETE FROM tiles WHERE id IN (   SELECT id FROM tiles   LEFT JOIN region_tiles   ON tile_id = tiles.id   WHERE tile_id IS NULL   AND accessed <= ?1 ) ] disk I/O error
                   libc  F  /buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type mapbox::sqlite::Exception: disk I/O error" failed
                  GoLog  E  terminating with uncaught exception of type mapbox::sqlite::Exception: disk I/O error
                         E  /buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type mapbox::sqlite::Exception: disk I/O error" failed
                   libc  F  Fatal signal 6 (SIGABRT), code -6 in tid 28207 (DefaultFileSour)
            HTTPRequest  V  [HTTP] Request was successful (code = 200).
```

Please let me know why this error could have happened. Thanks!
**Mapbox SDK versions: 6.3.0-SNAPSHOT**

**Comment by kkaefer** [comment]
Thank you for reporting this error, and sorry you're running into trouble with the Mapbox SDK. We are aware of this error, and it will be fixed with https://github.com/mapbox/mapbox-gl-native/pull/12224. Closing this as a duplicate.

**Comment by BharathMG** [comment]
@kkaefer Thanks! When can we expect this PR to be merged? Currently, when the Map is visible in foreground, it crashes with this error.

**Comment by ChrisLoer** [comment]
@BharathMG I can't be certain, but I would expect that PR to merge within maybe a month?
