### ISSUE TITLE
Mapbox Android - Cluster map points via layer

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#12416]
I am trying to add clusters to my application. Unfortunately I was unable to find any Android based examples that could help me. I found one iOS example so far, but because of different classes and implementations that example was not quite helpful. It would be helpful to have an example that shows how to use a Layer object to cluster map points.

### Configuration

**Android versions:** All
**Device models:** All
**Mapbox SDK versions:** 6.2.1

**Comment by langsmith** [comment]
Hey @Mordag , thanks for using Mapbox!  Check out https://www.mapbox.com/android-docs/maps/overview/clustering/ for info about data clustering

**Comment by Mordag** [comment]
Thanks! These examples helped me a lot. :) 

I am facing some issues regarding the label. As soon as the "point_count" is 1, the label is empty. I am using the CircleLayer and would like to replace the circle in that case with the actual symbol from this position. Is that somehow possible?

**Comment by langsmith** [comment]
Hey @Mordag , I'm sure what you're trying to do is possible but I'm not exactly sure what you're trying to accomplish visually.

- `the label is empty` what label? The `SymbolLayer` text which shows the # of data points in an area?
- `the actual symbol from this position` Did you add an unclustered `SymbolLayer` as seen in [the demo app's `CircleLayer` clustering example](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/GeoJsonClusteringActivity.java#L164-L182)? Or are you talking about something else?

**Comment by Mordag** [comment]
@langsmith Thanks for your answer, I will send you an example in the next days.

**Comment by Mordag** [comment]
@langsmith I found the problem. It seems like that the property cluster_point is not given in certain cases. In my case this was always given if the cluster was based on one point only and this point was a feature on the map. Is that something you would classify as an expected behaviour? I would expect the point_count to be 1.
