### ISSUE TITLE
Parse rest of the tile in case glyph PBFs fail to load

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1241]
#1237 shows that the entire map fails when glyph PBFs fail to load. Instead of not parsing the entire tile, we should parse the parts that we can.

**Comment by jfirebaugh** [comment]
@tmpsantos Is this fixed?

**Comment by tmpsantos** [comment]
> @tmpsantos Is this fixed?

No, I can start this one friday.

**Comment by tmpsantos** [comment]
This is actually fixed, but will cause the `MapMode::Still` never to return. Being worked here #1565 .
