### ISSUE TITLE
Mapbox Android - Always show compass

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#12418]
I want to always show the compass on the map regardless if I clicked on the compass or it is faced to north. Currently you can only define the fade animation, margin, gravity and compass image. Is there any other way to prevent the compass from getting invisible?

### Configuration

**Android versions:** All
**Device models:** All
**Mapbox SDK versions:** 6.2.1

**Comment by tobrun** [comment]
@Mordag we already expose this functionality with:

```java
MapboxMap.getUiSettings().setCompassFadeFacingNorth(false)
```

Thank you for reaching out, closing as answered.

**Comment by Mordag** [comment]
@tobrun Thank you for your answer. Yes, but the method is not doing what I described. I want to always display the compass regardless what the user does. This method is only effecting the fading if the compass is facing north. 

According to your source code documentation:

> Enables or disables fading of the compass when facing north.

**Comment by tobrun** [comment]
Apologies @Mordag if you have trouble getting the expected behaviour but not able reproduce:

![ezgif com-video-to-gif 70](https://user-images.githubusercontent.com/2151639/42883569-3a9beae2-8a9c-11e8-9397-060347052f42.gif)
