### ISSUE TITLE
Directed symbols placed along a line are always wrong (Inconsistency between resample and Placement::getIcon).

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1242]
Directed symbols placed along a line are always wrong. For e.g. if the symbol is an arrow along a road going east, it would show the arrow as going west.

The issue is that nextIndex used in Placement::getIcon is incorrect/inconsistent with how anchor.segment is set in resample.

- In resample, when creating anchor for a segment going from i to i+1, anchor.segment is set to i.
- In Placement::getIcon, when computing the angle between anchor and the next point in the segment, it should pick i+1 and not i.

**Comment by ansis** [comment]
Yep, thanks for tracking down the bug.

This was just fixed in -js and will be in -native soon.
https://github.com/mapbox/mapbox-gl-js/compare/icon-rotation-fix?expand=1
