### ISSUE TITLE
App crashes when navigating back before map is loaded

### ISSUE THREAD

**Issue by stoefln** [mapbox/mapbox-gl-native#12422]
### Steps to reproduce

 1. open fragment showing a mapview
 2. press "back" before mapview is loaded
 3. app crashes with log line "Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10 in tid 10452 

### Expected behavior
Should not crash

### Actual behavior
Crashes

### Configuration

**Android versions:** 
Android 7

**Device models:** 
Samsung Galaxy S7

**Mapbox SDK versions:** 
6.1.2

**Comment by tobrun** [comment]
Having some trouble reproducing this, do you have a minimal reproducible example?

![ezgif com-video-to-gif 71](https://user-images.githubusercontent.com/2151639/42930240-c07043de-8b3c-11e8-9974-e5e00754d3ce.gif)

**Comment by stoefln** [comment]
Unfortunately not. Forgot to mention that we also use the LocationLayer Plugin. Maybe it's related to this.

**Comment by tobrun** [comment]
@LukasPaczos would you be able to test that out when you have the llp project open? In my test above I overridden `OnBackPressed` in the `FeatureOverViewActivity` and not called `super.onBackPressed` to avoid closing the app.

**Comment by LukasPaczos** [comment]
Hey @stoefln, which version of the plugin are you using?

**Comment by LukasPaczos** [comment]
> press "back" before mapview is loaded

Could you also elaborate more on that? Which point of the lifecycle is that? Has the map ready callback been delivered? Can you reproduce that by placing the `onBackPressed()` method invocation anywhere in your code?
