### ISSUE TITLE
Creating GeoJsonSource out of UI Thread raises exception

### ISSUE THREAD

**Issue by milo1000** [mapbox/mapbox-gl-native#12435]
Creating instance of GeoJsonSource class outside of UI Thread raises
com.mapbox.mapboxsdk.exceptions.CalledFromWorkerThreadException

Since it has nothing to do with UI itself nor View/Layer instance, and parsing GeoJson can be time consuming, this shall be considered bad design.

**Android versions:** 8.1
**Device models:** Nokia 7+
**Mapbox SDK versions:** 6.2.1

**Comment by tobrun** [comment]
parse GeoJson on workerthread
pass that result to the main thread and create source from it

**Comment by milo1000** [comment]
> parse GeoJson on workerthread

 That's not the point of this issue. I don't parse GeoJSON by myself, just create GeoJsonSource from GeoJSON string like this:

`GeoJsonSource geoJsonSource = new GeoJsonSource(OVERLAY_SOURCE_ID, overlaySource);`

Since my `overlaySource`  can be huge, such operation seems to be heavyweight and it's strange to do such operation within UI thread.

**Comment by tobrun** [comment]
tracking optimisations to this feature in https://github.com/mapbox/mapbox-gl-native/issues/8484
