### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by BringeRaj** [mapbox/mapbox-gl-native#12439]
- My requirement is clustering in mapbox : Need to show different icons for individual points when zoomed in. While zooming out need to show clustering like circle with some color and count in center.
- So, I have searched for achieving this feature using Mapbox and found symbol layer to show individual points with icons and circle layer for clustering. With this, I added symbol layer to show different icons for different locations(points) and added the circle layer for clustering with another symbol layer to show text over the clustered points.
- The issue is that I could not find the individual point icons when zoomed in because the circle layer is laid over the symbol layer which makes the icons to be hidden. How to make the icons visible when the individual points are shown and show the circle layer only on clustering?  

try {
    FeatureCollection featureCollection = FeatureCollection.fromFeatures(coordinatesToCluster);

    mapboxMap.addSource(
            new GeoJsonSource("earthquakes",
                    featureCollection,
                    new GeoJsonOptions()
                            .withCluster(true)
                            .withClusterMaxZoom(15) // Max zoom to cluster points on
                            .withClusterRadius(20) // Use small cluster radius for the hotspots look
            )
    );
} catch (Exception exception) {
    Log.e(TAG, "Source points not added : " + exception.getMessage());
}

int[][] layers = new int[][]{
        new int[]{100, Color.parseColor("#FF0000")},
        new int[]{10, Color.parseColor("#00FF00")},
        new int[]{2, Color.parseColor("#0000FF")}
};

SymbolLayer myLayer = new SymbolLayer("unclustered-points", "earthquakes");   // Here individual point images are loaded as symbol layer 
    for (CategoryModel categories : categories) {
        String categoryId = categories.getId().toString();
        Bitmap myImage = loadBitmap(categoryId);
        mapboxMap.addImage(categoryId, myImage);
    }
mapboxMap.addLayer(myLayer);

for (int i = 0; i < layers.length; i++) {                                     // Here circle layer is added for clustering
    //Add clusters' circles
    CircleLayer circles = new CircleLayer("cluster-" + i, "earthquakes");
    circles.setProperties(
            circleColor(layers[i][1]), //if last layer set color to transparent
            circleRadius(18f)
    );

    Expression pointCount = toNumber(get("point_count"));

    // Add a filter to the cluster layer that hides the circles based on "point_count"
    circles.setFilter(
            i == 0
                    ? gte(pointCount, literal(layers[i][0])) :
                    all(
                            gte(pointCount, literal(layers[i][0])),
                            lt(pointCount, literal(layers[i - 1][0]))
                    )
    );
    mapboxMap.addLayer(circles);
   
}

//Add the count labels
SymbolLayer count = new SymbolLayer("count", "earthquakes");                      // Here symbol layer added to show text in clustering
count.withProperties(PropertyFactory.iconImage("image"));
count.setProperties(
        textField("{point_count}"),
        textSize(12f),
        textColor(Color.WHITE)
);
mapboxMap.addLayer(count);

**Comment by mourner** [comment]
This is a place to report issues with Mapbox GL. Unfortunately we don't have the bandwidth to develop your application for you — please use StackOverflow, or consult documentation on expressions.
