### ISSUE TITLE
Support `getLeaves` and other new clustering methods in Android SDK

### ISSUE THREAD

**Issue by lilykaiser** [mapbox/mapbox-gl-native#12441]
We need an Android equivalent of https://github.com/mapbox/mapbox-gl-js/pull/6829 to support features created in the [most recent release of supercluster.hpp](https://github.com/mapbox/supercluster.hpp/releases/tag/v0.3.0) including `getChildren`, `getLeaves`, and `getClusterExpansionZoom`.

**Comment by 1ec5** [comment]
The iOS/macOS equivalent of this issue is #12442.

**Comment by F0rc0sigan** [comment]
Is there any ETA for this feature request?

**Comment by chloekraw** [comment]
@F0rc0sigan - thanks for your patience. This landed on Android in https://github.com/mapbox/mapbox-gl-native/pull/12727; closing this issue.

**Comment by djdance** [comment]
excuse me, and where is it now in 2020? I need getLeaves method...
