### ISSUE TITLE
[Android] Source Async?

### ISSUE THREAD

**Issue by shaqu1988** [mapbox/mapbox-gl-native#12450]
Hello,
Is there posibility to execute
`GeoJsonSource geoJsonSource = new GeoJsonSource("geojson-source", featureCollection); `
asynchronously? It takes time in main thread and freeze whole app for ~8 seconds.

code:
`
ArrayList<Feature> features = new ArrayList<>(); 
// adding multiple polygons into features
FeatureCollection featureCollection = FeatureCollection.fromFeatures( features.toArray(new Feature[features.size()]) );

GeoJsonSource geoJsonSource = new GeoJsonSource("geojson-source", featureCollection); // freezing
        
mapboxMap.addSource(geoJsonSource);
`

Thanks in advance :)

**Comment by tobrun** [comment]
@shaqu1988 you need to perform the following on a background thread:

```
ArrayList features = new ArrayList<>();
// adding multiple polygons into features
FeatureCollection featureCollection = FeatureCollection.fromFeatures( features.toArray(new Feature[features.size()]) );
```

and pass that result to the main thread to create your source. 

We are tracking doing asynchronous updates in https://github.com/mapbox/mapbox-gl-native/issues/8484 that completely should fix your issue.

**Comment by shaqu1988** [comment]
That's what I'm doing , but in onPostExecute I have

`GeoJsonSource geoJsonSource = new GeoJsonSource("geojson-source", featureCollection); // freezing`

and this is the moment where it freezes whole app.
