### ISSUE TITLE
Polygon is not being filled/Highlighted fully.

### ISSUE THREAD

**Issue by adiahuja07** [mapbox/mapbox-gl-native#12466]
![london city - geofencing](https://user-images.githubusercontent.com/10696479/43135081-cada0f98-8f61-11e8-8e22-ed3166ae3567.png)
Code - 

  func createGeoFence()
    {
        cordinateArray = [
            CLLocationCoordinate2D(latitude: 51.525318, longitude: -0.087293),
            CLLocationCoordinate2D(latitude: 51.525510, longitude: -0.088052),
            CLLocationCoordinate2D(latitude: 51.527037, longitude: -0.088379),
            CLLocationCoordinate2D(latitude: 51.528459, longitude: -0.092649),
            CLLocationCoordinate2D(latitude: 51.528788, longitude: -0.093923),
            CLLocationCoordinate2D(latitude: 51.529696, longitude: -0.097512),
            CLLocationCoordinate2D(latitude: 51.529779, longitude: -0.102379),
            CLLocationCoordinate2D(latitude: 51.530303, longitude: -0.103345),
            CLLocationCoordinate2D(latitude: 51.531868, longitude: -0.106234),
            CLLocationCoordinate2D(latitude: 51.531574, longitude: -0.111204),
            CLLocationCoordinate2D(latitude: 51.530096, longitude: -0.115448),
            CLLocationCoordinate2D(latitude: 51.529704, longitude: -0.115743),
            CLLocationCoordinate2D(latitude: 51.529392, longitude: -0.115791),
            CLLocationCoordinate2D(latitude: 51.528992, longitude: -0.117567),
            CLLocationCoordinate2D(latitude: 51.530531, longitude: -0.122536),
            CLLocationCoordinate2D(latitude: 51.530274, longitude: -0.123131),
            CLLocationCoordinate2D(latitude: 51.530005, longitude: -0.123740),
            CLLocationCoordinate2D(latitude: 51.529041, longitude: -0.126048),
            CLLocationCoordinate2D(latitude: 51.527655, longitude: -0.129610),
            CLLocationCoordinate2D(latitude: 51.527296, longitude: -0.130551),
            CLLocationCoordinate2D(latitude: 51.526269, longitude: -0.133548),
            CLLocationCoordinate2D(latitude: 51.524484, longitude: -0.134775),
            CLLocationCoordinate2D(latitude: 51.523675, longitude: -0.137317),
            CLLocationCoordinate2D(latitude: 51.524508, longitude: -0.137891),
            CLLocationCoordinate2D(latitude: 51.524247, longitude: -0.140629),
            CLLocationCoordinate2D(latitude: 51.523617, longitude: -0.143612),
            CLLocationCoordinate2D(latitude: 51.523470, longitude: -0.144001),
            CLLocationCoordinate2D(latitude: 51.522851, longitude: -0.146054),
            CLLocationCoordinate2D(latitude: 51.523294, longitude: -0.148431),
            CLLocationCoordinate2D(latitude: 51.523229, longitude: -0.148895),
            CLLocationCoordinate2D(latitude: 51.523038, longitude: -0.151137),
            CLLocationCoordinate2D(latitude: 51.522786, longitude: -0.153261),
            CLLocationCoordinate2D(latitude: 51.522614, longitude: -0.154227),
            CLLocationCoordinate2D(latitude: 51.522217, longitude: -0.156434),
            CLLocationCoordinate2D(latitude: 51.520890, longitude: -0.156911),
            CLLocationCoordinate2D(latitude: 51.520515, longitude: -0.159167),
            CLLocationCoordinate2D(latitude: 51.521377, longitude: -0.161043),
            CLLocationCoordinate2D(latitude: 51.521177, longitude: -0.162171),
            CLLocationCoordinate2D(latitude: 51.520870, longitude: -0.164027),
            CLLocationCoordinate2D(latitude: 51.519391, longitude: -0.165776),
            CLLocationCoordinate2D(latitude: 51.517713, longitude: -0.166588),
            CLLocationCoordinate2D(latitude: 51.516921, longitude: -0.165414),
            CLLocationCoordinate2D(latitude: 51.515948, longitude: -0.164026),
            CLLocationCoordinate2D(latitude: 51.515042, longitude: -0.162764),
            CLLocationCoordinate2D(latitude: 51.514237, longitude: -0.161450),
            CLLocationCoordinate2D(latitude: 51.513972, longitude: -0.161017),
            CLLocationCoordinate2D(latitude: 51.513415, longitude: -0.158957),
            CLLocationCoordinate2D(latitude: 51.494424, longitude: -0.095624),
            CLLocationCoordinate2D(latitude: 51.494203, longitude: -0.092839),
            CLLocationCoordinate2D(latitude: 51.494272, longitude: -0.090197),
            CLLocationCoordinate2D(latitude: 51.494292, longitude: -0.089335),
            CLLocationCoordinate2D(latitude: 51.494769, longitude: -0.086233),
            CLLocationCoordinate2D(latitude: 51.495103, longitude: -0.084281),
            CLLocationCoordinate2D(latitude: 51.496717, longitude: -0.081923),
            CLLocationCoordinate2D(latitude: 51.497708, longitude: -0.079861),
            CLLocationCoordinate2D(latitude: 51.500204, longitude: -0.078648),
            CLLocationCoordinate2D(latitude: 51.501305, longitude: -0.078131),
            CLLocationCoordinate2D(latitude: 51.502210, longitude: -0.077732),
            CLLocationCoordinate2D(latitude: 51.509623, longitude: -0.074289),
            CLLocationCoordinate2D(latitude: 51.509888, longitude: -0.074651),
            CLLocationCoordinate2D(latitude: 51.511131, longitude: -0.075194),
            CLLocationCoordinate2D(latitude: 51.511807, longitude: -0.073109),
            CLLocationCoordinate2D(latitude: 51.513546, longitude: -0.073451),
            CLLocationCoordinate2D(latitude: 51.514464, longitude: -0.074087),
            CLLocationCoordinate2D(latitude: 51.514536, longitude: -0.074166),
            CLLocationCoordinate2D(latitude: 51.514981, longitude: -0.072728),
            CLLocationCoordinate2D(latitude: 51.515936, longitude: -0.072443),
            CLLocationCoordinate2D(latitude: 51.519121, longitude: -0.074586),
            CLLocationCoordinate2D(latitude: 51.520216, longitude: -0.074562),
            CLLocationCoordinate2D(latitude: 51.520705, longitude: -0.074944),
            CLLocationCoordinate2D(latitude: 51.521658, longitude: -0.076060),
            CLLocationCoordinate2D(latitude: 51.522812, longitude: -0.077661),
            CLLocationCoordinate2D(latitude: 51.523157, longitude: -0.078466),
            CLLocationCoordinate2D(latitude: 51.523599, longitude: -0.080361),
            CLLocationCoordinate2D(latitude: 51.524265, longitude: -0.080388),
            CLLocationCoordinate2D(latitude: 51.524642, longitude: -0.080900),
            CLLocationCoordinate2D(latitude: 51.524729, longitude: -0.081061),
            CLLocationCoordinate2D(latitude: 51.526194, longitude: -0.084989),
            CLLocationCoordinate2D(latitude: 51.513463, longitude: -0.158624),
            CLLocationCoordinate2D(latitude: 51.512750, longitude: -0.157939),
            CLLocationCoordinate2D(latitude: 51.511048, longitude: -0.157047),
            CLLocationCoordinate2D(latitude: 51.510511, longitude: -0.156743),
            CLLocationCoordinate2D(latitude: 51.508963, longitude: -0.154794),
            CLLocationCoordinate2D(latitude: 51.507987, longitude: -0.153726),
            CLLocationCoordinate2D(latitude: 51.506724, longitude: -0.152204),
            CLLocationCoordinate2D(latitude: 51.506629, longitude: -0.152080),
            CLLocationCoordinate2D(latitude: 51.506090, longitude: -0.151490),
            CLLocationCoordinate2D(latitude: 51.505166, longitude: -0.150862),
            CLLocationCoordinate2D(latitude: 51.503339, longitude: -0.150664),
            CLLocationCoordinate2D(latitude: 51.502725, longitude: -0.149736),
            CLLocationCoordinate2D(latitude: 51.498223, longitude: -0.143991),
            CLLocationCoordinate2D(latitude: 51.496684, longitude: -0.141775),
            CLLocationCoordinate2D(latitude: 51.492851, longitude: -0.138023),
            CLLocationCoordinate2D(latitude: 51.492083, longitude: -0.136403),
            CLLocationCoordinate2D(latitude: 51.490262, longitude: -0.132562),
            CLLocationCoordinate2D(latitude: 51.489397, longitude: -0.130744),
            CLLocationCoordinate2D(latitude: 51.488819, longitude: -0.129435),
            CLLocationCoordinate2D(latitude: 51.486559, longitude: -0.123873),
            CLLocationCoordinate2D(latitude: 51.486320, longitude: -0.120649),
            CLLocationCoordinate2D(latitude: 51.486507, longitude: -0.119222),
            CLLocationCoordinate2D(latitude: 51.486905, longitude: -0.116538),
            CLLocationCoordinate2D(latitude: 51.486985, longitude: -0.115095),
            CLLocationCoordinate2D(latitude: 51.487170, longitude: -0.112812),
            CLLocationCoordinate2D(latitude: 51.488659, longitude: -0.111283),
            CLLocationCoordinate2D(latitude: 51.491017, longitude: -0.105243),
            CLLocationCoordinate2D(latitude: 51.491880, longitude: -0.102520),
            CLLocationCoordinate2D(latitude: 51.495090, longitude: -0.101348),
            CLLocationCoordinate2D(latitude: 51.495745, longitude: -0.100500),
            CLLocationCoordinate2D(latitude: 51.494728, longitude: -0.097065),
            CLLocationCoordinate2D(latitude: 51.525318, longitude: -0.087293)
        ]
        
        let shape = MGLPolygon(coordinates: &cordinateArray, count: UInt(cordinateArray.count))
      //let shape = MGLPolygon(coordinates: &cordinateArray, count: UInt(coordinateArray.count))
        self.vwMap.addAnnotation(shape)
        
        
        for cordinate in cordinateArray
        {
            let annotation = MGLPointAnnotation()
            annotation.coordinate = cordinate 
            vwMap.addAnnotation(annotation)
            let zoneRadius:Double = 10000.0
            let zoneregion = CLCircularRegion(center: annotation.coordinate, radius: zoneRadius, identifier: (cordinate.latitude as AnyObject).stringValue)
            zoneregion.notifyOnExit = true
            zoneregion.notifyOnEntry = true
            startMonitoring(zoneRegion: zoneregion)
        }
    }

    
    func mapView(_ mapView: MGLMapView, alphaForShapeAnnotation annotation: MGLShape) -> CGFloat
    {
        return 0.5
    }
    
    func mapView(_ mapView: MGLMapView, strokeColorForShapeAnnotation annotation: MGLShape) -> UIColor
    {
        return .purple
    }
    
    func mapView(_ mapView: MGLMapView, fillColorForPolygonAnnotation annotation: MGLPolygon) -> UIColor
    {
        return UIColor(red: 0/255, green: 0/255, blue: 255/255, alpha: 1)
    }

Start with a brief description below this line. -->

Thanks in advance

### Expected behavior
The blue color should cover all the area within the pins

### Actual behavior
As seen in the screenshot above, the highlighted region is not covering all of the area inside the pins.

What changes can I do to Make the region inside colored.

### Configuration

**Mapbox SDK versions:**  3.6.0
**iOS/macOS versions:** ios10.3
**Device/simulator models:** iphone 7
**Xcode version:**  8.3.2

**Comment by friedbunny** [comment]
Hi @adiahuja07 — thanks for using Mapbox. This repo is for reporting bugs, requesting features, and coordinating work related to the various Mapbox Map SDKs. For help with “how do I” questions, please ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox) or reach out to our excellent [support team](https://www.mapbox.com/contact/support/).

In this case, I’d recommend checking that your coordinates produce a valid polygon.

**Comment by adiahuja07** [comment]
okay
