### ISSUE TITLE
Marker disappear at certain zoom and bearing

### ISSUE THREAD

**Issue by sarahthe** [mapbox/mapbox-gl-native#12467]
I have markers for points of interest on a map. On certain zoom levels and rotations of the map, the markers disappear but click events are still handled, so markers are invisible.
The disappearance correlates with the disappearance of place or street names (in the screenshot below: "Essen Hbf").

![device-2018-07-24-144515](https://user-images.githubusercontent.com/27763767/43139217-7ac3da8a-8f51-11e8-837e-8ecd796a57ec.png)
![device-2018-07-24-144538](https://user-images.githubusercontent.com/27763767/43139232-80dee6bc-8f51-11e8-85d5-eb7ee9d6fe44.png)

### Steps to reproduce

 1. Create a map with markers (on SymbolLayers) and lines
 2. Zoom and rotate until markers disappear

### Expected behavior
Markers stay visible

### Actual behavior
Markers are invisible, but click events work

### Configuration

**Android versions:** 8.0
**Device models:** Nexus 5X (but also happens on other devices like the Samsung Galaxy S9)
**Mapbox SDK versions:** Android SDK 5.5.1, Services 2.2.10, Location Layer 0.4.0

Increasing the versions would result in quite some work as the app uses multiple maps and the API changes quite a lot, so fixing this another way would be better.

**Comment by LukasPaczos** [comment]
Hey @sarahthe, thanks for reaching out. I'm sorry to hear that you are having issues with the Maps SDK, but the `6.x` version has been out for a couple of months and without retesting on the latest builds (where the issue might already be fixed), this issue is not actionable for us.
