### ISSUE TITLE
Location permission dialog box disappears quicky

### ISSUE THREAD

**Issue by errazkisibawaih** [mapbox/mapbox-gl-native#12481]
I am using the location of the user in an IOS app. The issue is that when I launch the app with location services turned off, the dialog box of location permission disappears quickly without any user click. I am wondering if mapbox can't propose to the user to turn on location, but the big trouble is that mapbox display the dialog box. Sorry for my English. I am using Mapbox 4.2 , Swift 4 and IOS 11.4. I am blocked in this issue for 2 days. Thank you so much
Swift 4
I put the mapbox directions in the viewDidLoad function
> 
 override func viewDidLoad() {
        
       ......
        // Set the delegate property of our map view to self after instantiating it.
        mainMap.delegate = self
        
        // Allow the map to display the user's location
        mainMap.showsUserLocation = true
        mainMap.setUserTrackingMode(.follow, animated: true)
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
    }
>

**Comment by captainbarbosa** [comment]
@errazkisibawaih Hi there, I attempted to reproduce the issue with the code you have provided and was unable to do so. If there is any way you could produce another minimal test case that simulates the issue you're seeing, please reach out to us through our [contact form](https://www.mapbox.com/contact/support/) with additional details.
