### ISSUE TITLE
runtime_error: unknown schema version on downgrade Mapbox version

### ISSUE THREAD

**Issue by asetiyadi** [mapbox/mapbox-gl-native#12499]
We recently upgrade from Mapbox 3.7 to 4.1.  Everything is fine when users upgrade from previous version of the app (with Mapbox v3.7) to the newer version (with Mapbox v4.1).  However when they try to reinstall the previous app version, the app crash with the following message: `libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: unknown schema version`

### Steps to reproduce
 1.  Install older app version (Mapbox 3.7)
 2. Install newer app version (Mapbox 4.1)
 3. Reinstall older app version

### Expected behavior
No crash

### Actual behavior
Crash: `libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: unknown schema version`

### Configuration

**Mapbox SDK versions:**  
Old version: Mapbox 3.7
New version: Mapbox 4.1

**iOS/macOS versions:** 
iOS 11

**Device/simulator models:**
iPhone 7 and 8

**Xcode version:** 
9.4.1

**Comment by fabian-guerra** [comment]
Hi, @asetiyadi. Thank you for using Mapbox. I am sorry to hear you are having some issues. We don't support downgrade migration.

**Comment by fabian-guerra** [comment]
Hi, @asetiyadi. Could you please share a code snippet or test app we could use to test?
