### ISSUE TITLE
CustomGeometrySource race condition

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#12508]
Users are reporting that there is a possibility of a race condition while using the `CustomGeometrySource` if the data is requested and invalidated in a quick succession. The example scenario looks like this:

1. Tile comes on screen
2. `fetchTile` is called
3. `GeometryTileRequest` gets data from the provider
4. Starts call to `setTileData`
5. Provider invalidates the tile
6. `cancelTile` is called
7. `fetchTile` is called
8. `GeometryTileRequest` gets data from the provider
9. Starts call to `setTileData`

With this example, we can have 2 calls to `setTileData`, from 2 different threads running simultaneously and the one that is going to get converted from Java's `FeatureCollection` to `mbgl::FeatureCollection` quicker is going to win that race as the conversion seems to be the point that takes the longest (depending on the size of the collection).

This leads to a case, where the second update required shorter time to get converted, then is briefly displayed only to be overwritten by the initial update, which is not the desired behavior.

**Comment by ChrisLoer** [comment]
cc @asheemmamoowala
