### ISSUE TITLE
Android MapBox - mix extrusion and 3D models

### ISSUE THREAD

**Issue by Emixam23** [mapbox/mapbox-gl-native#12528]
Hi,

I am coming because, after all I read about this package, I didn't find what I was searching for.

In fact, I would like to know if I can exchange an extruded structure by a 3D model/mesh? Because at some part of my map I would like to add a mesh/model but there is an extruded building/structure.. Or at least, can I renderer it as invisible? Like change the color/properties of only one extruded building/structure?

I asked for android, but if I could get the answer for ReactJs and iOS it would be perfect :)

Thanks !

**Comment by jfirebaugh** [comment]
Mapbox GL doesn't currently support 3D models. https://github.com/mapbox/mapbox-gl-js/issues/3996 is the issue for that feature request.

**Comment by Emixam23** [comment]
Hi !

Thanks for the reply, but does unity do it? I mean mix the extrusion and the 3D models?

Thanks :)

**Comment by atripathi-mb** [comment]
@Emixam23 Yes, Maps SDK for Unity can do it. We have an example to do exactly this in our SDK. 
Here is a link to the documentation https://www.mapbox.com/unity-sdk/maps/examples/replace-features/

**Comment by Emixam23** [comment]
Wow perfect ! I read a lot about unity but couldn't find this link tho... Thanks :)

Last question, how can I make it fully generated? Because from my tests of the maps of mapbox's unity 3D extension, it's only a scene proposing only a part of the map, how can I make it infinite?

**Comment by atripathi-mb** [comment]
@Emixam23 Happy to help. 

Here is a zoomable,pannable map example. https://www.mapbox.com/unity-sdk/maps/examples/zoomable-map/

I suggest going through the documentation, tutorials & examples to see all the awesome possibilities of the SDK. 

If you have questions please use this repo to log tickets for us https://github.com/mapbox/mapbox-unity-sdk

**Comment by Emixam23** [comment]
Ok perfect I will, thank you so much !
