### ISSUE TITLE
Interacting with annotations from Style URL

### ISSUE THREAD

**Issue by troutinsights** [mapbox/mapbox-gl-native#12524]
Hi, 
I have a pretty basic use case that i cant seem to find coverage or guidance on. I have several sets of large geoJSON datasets that i manage in MapBox Studio that contain objects that are mostly lines with titles and notes associated with each. Id like to have my map allow the user to touch these lines and have a dialog pop up with the associated information in that geoJSON. I dont see any documentation on how to convert objects from styleURL into annotations that enable those interactions without compiling in that geoJSON inside of xcode. Any suggestions? Great work on this open project. 
-Zach

**Comment by fabian-guerra** [comment]
Hi, @troutinsights. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/) or check our [documentation](https://www.mapbox.com/ios-sdk/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
