### ISSUE TITLE
Android: Expression not working after update to 6.3.0 

### ISSUE THREAD

**Issue by psinetron** [mapbox/mapbox-gl-native#12536]
After update from 6.2.0 to 6.3.0 this code not working:
```
 val pointCount = Expression.toNumber(Expression.get("point_count"))
val blockMarkersLayer = SymbolLayer("block-markers-layer", "block-markers-source")
                    .withProperties(PropertyFactory.iconImage(
                            Expression.match(
                                    Expression.get("selected"),
                                    Expression.literal("unselected-marker"),
                                    Expression.stop("true", "selected-marker"),
                                    Expression.stop("false", "unselected-marker"))))
                    .withProperties(PropertyFactory.iconAnchor(Property.ICON_ANCHOR_BOTTOM))
                    .withProperties(PropertyFactory.iconAllowOverlap(true))
            blockMarkersLayer.filter = Expression.lte(pointCount, 1)
            mapBox.addLayer(blockMarkersLayer)
```
Before updating it show green(selected-marker) or blue(unselected-marker) markers. After update no one markers shown

I think somebody changed in **Expression.get("point_count")**. It shown without filter **blockMarkersLayer.filter = Expression.lte(pointCount, 1)**
What changed?

**Comment by tobrun** [comment]
Thanks for the report @psinetron, our default filter integration seems to be working as before:

![ezgif com-video-to-gif 25](https://user-images.githubusercontent.com/2151639/44029063-4d2aaed6-9efc-11e8-96d3-d2ab3b57b618.gif)

Some follow up questions:
 - are you using geojson source with clustering?
 - if yes, could see if https://github.com/mapbox/mapbox-gl-native/pull/12211/files#diff-f500db5272de0a3199d6f964419ffe60R185 would resolve your issue? on our end we had include has("point_count") in our configuration when using expressions with clusters.
 - are you seeing any error messages logged when setting the filter?

**Comment by psinetron** [comment]
1. Yes, I use geoJson with clustering
2. I was use other method:
`blockMarkersLayer.filter = Expression.not(Expression.has("point_count"))`
3. No any errors

**Comment by tobrun** [comment]
@psinetron could you try replacing with the following filter definition: 

```
all(has("point_count"), gte(toNumber(get("point_count")), 1)
```

one more follow up question? This filter is set on a symbollayer that is clustered together?

**Comment by psinetron** [comment]
> `all(has("point_count"), gte(toNumber(get("point_count")), 1)`

It not working for me. I thing layer has no field "point_count"

> This filter is set on a symbollayer that is clustered together?

Yes

**Comment by tobrun** [comment]
point_count is automatically added as property by the supercluster.hpp, see [here](https://github.com/mapbox/supercluster.hpp/blob/master/include/supercluster.hpp#L46).  Please reach out if this is still an issue with a minimal reproducible example. Closing this as stale as don't have any issues on our end with clustering.
