### ISSUE TITLE
Bug: Bearing is inverted with LatLngBounds Update

### ISSUE THREAD

**Issue by JGerdes** [mapbox/mapbox-gl-native#12549]
When animating the camera via `CameraUpdateFactory.newLatLngBounds()`, bearing gets mirrored on north/south axis.
When applying the same CameraUpdate from `CameraUpdateFactory.newLatLngBounds()` multiple times, the bearing keep swapping between two values:

original bearing | bearing after re-applying update
----- | -----
![orginal bearing](https://user-images.githubusercontent.com/6023465/43690135-54739e8e-9905-11e8-9e83-5b14eb65d7c4.png) | ![bearing after second update](https://user-images.githubusercontent.com/6023465/43690136-54899568-9905-11e8-876f-4eb560750c2e.png)

Can be reproduced with all `map.animateCamera()`, `map.easeCamera()` and `map.MoveCamera()`.

### Steps to reproduce

 1. Start map view with bearing set to 0 (north facing up)
 2. Apply CameraUpdate obtained with `CameraUpdateFactory.LatLngBounds()`
 3. Rotate map (changing it's bearing)
 4. Apply new (or same, doesn't matter) CameraUpdate obtained with `CameraUpdateFactory.LatLngBounds()`

### Expected behavior
Animating to same bounds as before with either keeping current bearing or resetting it to 0 (latter one used to be the behavior)

### Actual behavior
Bearing seems to be mirrored on north-south axis (before second update: 42.27285333486378, after second update: 317.7271466651362).

### Configuration

**Android versions:** Tested and reproduced on Android 8.0 and 4.4.2
**Device models:** One Plus 3T (Android 8.0), Nexus 5 Emulator (Android 4.4.2)
**Mapbox SDK versions:** 6.3.0

This bug might be related to/was introduced with https://github.com/mapbox/mapbox-gl-native/issues/11993

**Comment by tobrun** [comment]
Thanks for the detailed report @JGerdes
