### ISSUE TITLE
Core: Offline Maps' efficiency

### ISSUE THREAD

**Issue by GBanlik** [mapbox/mapbox-gl-native#12548]
Are there any plans on improving the efficiency of offline maps?

It is understandable that the main purpose behind Mapbox was to provide online maps, hence layers did the trick. However, for offline maps, pure & simple per-zoom layers are not a viable long-term option, downloading 6k+ layers just to have a detailed NYC isn't exactly viable in terms of storage, nor for per-request download, picture a client downloading such vast numbers of layers everytime a new city is used.  For instance, other competitors such as Maps.Me - which was obviously created for that purpose which gives them a big advantage - use a single fileObject containing the per-zoom information, in a highly compressed file, sure it consumes a lot of battery, but object file sizes decreasing tenfold of more, are well worth it.

Let me know your thoughts on this.

Besides this, congratulations, your product, customer support, continuous updates and last but not least, community support via data science, open source, etc, are amazing.

**Comment by asheemmamoowala** [comment]
@GBanlik There are currently no plans to change the format of offline data storage in the Maps SDKs. The vector tile data is already quite size optimized for tiled rendering and storage. Also style layers do not map 1:1 to offline downloads, so storage (and download) does not increase when more layers are added to the style. 
Is there a specific problem you are running into with regards to the size of downloaded offline regions?
