### ISSUE TITLE
MapBox Flutter Plugin Status

### ISSUE THREAD

**Issue by GBanlik** [mapbox/mapbox-gl-native#12547]
I stumbled upon this issue, which states a plugin is being built, which is awesome. However, no more updates have occurred for 2 months now, and only android support is in. Any ETA/news on this subject?

[Original project.](https://github.com/mapbox/flutter-mapbox-gl)
[With leaflet](https://github.com/apptreesoftware/flutter_map)

In addition, will the plugin include the Navigation SDK?

**Comment by asheemmamoowala** [comment]
Hello @GBanlik , thank you for your interest in the Mapbox Android SDK. However, your question doesn't seem to be related to the Mapbox SDK specifically. This issue tracker is for reporting bugs and feature requests. 
You should instead ask this question on the [flutter repo](https://github.com/mapbox/flutter-mapbox-gl).
