### ISSUE TITLE
addAnnotations cause crash when calls method setCenter

### ISSUE THREAD

**Issue by LiborZa** [mapbox/mapbox-gl-native#12558]
### Steps to reproduce

I am not sure exact steps how to reproduce this with blank project. So I am including log from Crashlytics and example of my code:
<img width="627" alt="screen shot 2018-08-07 at 08 28 14" src="https://user-images.githubusercontent.com/39513305/43758340-1765c13a-9a1c-11e8-8327-ff7275f1f73c.png">

```
DispatchQueue.main.async {
     let annotsToAdd = users.map { MapUserAnnotation(user: $0) }
                    
     let annotsToRemove = self?.mapView.annotations?.filter({ $0 is MapUserAnnotation })
     if let annotsToRemove = annotsToRemove {
        self?.mapView.removeAnnotations(annotsToRemove)
     }
              
     self?.mapView.addAnnotations(annotsToAdd)
}
```

It happens on line where I try to add annotations. In most cases it works fine but few times it crashes the app. I am not sure what's wrong. I added line to check if mapView.layer is nil but I think it didn't help. Can I make more checks to be sure that it don't crash in Mapbox library?

### Configuration

**Mapbox SDK versions:** 4.0.2, 4.2.0 (not sure maybe in versions before
**iOS/macOS versions:** iOS 11 (at least 11.3.1, 11.4.1), iOS 12
**Device/simulator models:** iPhone 5S, iPhone X and maybe more
**Notes:** mapView is added in Storyboard

**Comment by julianrex** [comment]
Thanks for the report @LiborZa. It's likely that the coordinate for one of the `users` is invalid as defined by `CLLocationCoordinate2DIsValid(CLLocationCoordinate2D coord)`.

Can you please check your `MapUserAnnotation`'s coordinates, and confirm (or not!).
