### ISSUE TITLE
cmake error in cmakelist.txt when compile from source

### ISSUE THREAD

**Issue by j1m1y** [mapbox/mapbox-gl-native#12552]
i use ubuntu with jdk 8 and i have install cmake,c++ compiler, android studio, etc. but i have problem when build mapbox library.
when i build with run "make android" and show error.

this my error:
`CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "mbgl-test":
    "source/mapbox-gl-native/mason_packages/headers/geometry/0.9.3/include"
 CMake Error in CMakeLists.txt:
    Found relative path while evaluating include directories of "mbgl-core":
       "source/mapbox-gl-native/mason_packages/headers/geometry/0.9.3/include"
`
 thx for help

**Comment by kkaefer** [comment]
We can't reproduce this. Please provide more information around your build system.
