### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type mapbox::util::bad_variant_access: in get<T>()

### ISSUE THREAD

**Issue by jjniemand** [mapbox/mapbox-gl-native#12562]
### Steps to reproduce

 1. Use the attached GeoJSON file: [sample.geojson.zip](https://github.com/mapbox/mapbox-gl-native/files/2266165/sample.geojson.zip)
 2. Using the code below
 3. Works on most files, but fails on this one. Although the file is working fine using Mapbox-Android-SDK

### Expected behavior
Expecting the shapes to be drawn on the map

### Actual behavior
Displays some shapes, but it fails with the attached GeoJSON File. It is working fine using Mapbox-Android-SDK.

Fails with exception: 
`libc++abi.dylib: terminating with uncaught exception of type mapbox::util::bad_variant_access: in get<T>()`

### Configuration

**Mapbox SDK versions:**  4.2
**iOS/macOS versions:** 11.4.1 (15G77)
**Device/simulator models:** iPhone X - MQAD2AA/A
**Xcode version:** 9.4.1 (9F2000)

### Sample Code
```
let JsonVar = try JSON(data: data)
                    print(JsonVar["features"][0]["properties"]["FIELDNAME"].string!)
                    let shapeCollectionFeature = try MGLShape(data: data, encoding: String.Encoding.utf8.rawValue) as! MGLShapeCollectionFeature
                    print("GeoJSON Loaded1")
                    let source = MGLShapeSource(identifier: "field_\(fieldCounter)", shape: shapeCollectionFeature, options: nil)
                    print("GeoJSON Loaded2")
                    style.addSource(source)
                    
                    let polygonLayer = MGLFillStyleLayer(identifier: "field_style_\(fieldCounter)", source: source)
                    polygonLayer.fillColor = NSExpression(forConstantValue: UIColor.black)
                    polygonLayer.fillOpacity = NSExpression(forConstantValue: 0.6)
                    
                    let symbolLayer = style.layer(withIdentifier: "com.mapbox.annotations.points")
                    style.insertLayer(polygonLayer, below: symbolLayer!)
```

**Comment by fabian-guerra** [comment]
Hi, @jjniemand. Thanks for using Mapbox. I am sorry to hear you are having some issues. I used your code and geojson file to try to replicate the crash but I couldn't. Could you please provide a sample app we could use to track the issue?

**Comment by fabian-guerra** [comment]
Never mind, I was able to reproduce it.

**Comment by mourner** [comment]
@fabian-guerra do you have a full stack trace to share? Wondering if it's somewhere on the geojson-vt-cpp level.

**Comment by jjniemand** [comment]
@fabian-guerra or @jfirebaugh can I assist with any more information? Any feedback on the issue?

**Comment by ThiyagarajanShivSankaran** [comment]
Hello, This issue is not fixed yet. I am still facing this with v5.1.

**Comment by ansarikhurshid786** [comment]
same issue too

**Comment by v-andr** [comment]
Mapbox 5.9.0
had the same error ("mapbox::util::bad_variant_access") when trying to set source's shape with MGLShapeCollectionFeature made from shapes (MGLPolygon or MGLPolyline) instead of features (MGLPolygonFeature or MGLPolylineFeature respectively).

not 100% related as originally data was geojson, while I'm operating on objects made from coordinates, but I couldn't find any other relevant threads, so maybe it helps someone.

on a side note, MGLShapeCollectionFeature creation from array of shapes when expecting features is quite nightmarish
