### ISSUE TITLE
Possible MGLMapView rendering bug

### ISSUE THREAD

**Issue by randomiser** [mapbox/mapbox-gl-native#12585]
Hi there,

I'm currently using Mapbox-iOS-SDK (4.2.0).

I load a MGLMapView with annotations and associated custom views. These views are very simple mainly coloured circles that change colour for model states.

Now I can alter the colour of a custom MGLAnnotationView by say tapping a button in my interface , finding the relevant annotation view and changing it's state to effect a colour change. This all works perfectly btw.

However, when I present a modal screen over the top of the MGLMapView and then perform the "same operation" (via the main thread) no changes occur on the mapview. 

I've tried a lot of different permutations including removing all of the annotations and re-adding them as soon as the screen is redisplayed in the dismiss completion block. Also tried setNeedsDisplay() etc, None of these seem to change the MGLMapView. (NB: If I scroll a bit it seems to update.)

What MGLMapView needs is the ability to explicitly force it to redraw or reload.

Do you have any suggestions on how to get this working? Or any workarounds perhaps. Again these events are happening in the main thread.

Thanks in advance.
Matt

**Comment by jmkiley** [comment]
Hi @randomiser -

Thank you for your report! Are you still seeing this issue with iOS SDK v4.10.0? I have not been able to reproduce the issue with the following steps (see [this branch](https://github.com/mapbox/mapbox-gl-native/tree/jmkiley-repro-12585)):

1. Add 1000 annotation views.
2. Change the color of a random annotation view by pressing a button.
3. Present a new view controller modally, then dismiss it.
4. Change the color of an annotation view by pressing a button.

If you are still seeing the issue, would you be able to share a minimal test case that reproduces the issue?

**Comment by captainbarbosa** [comment]
Closing for now, but @randomiser if you can supply a test case we'd be happy to look into it.
