### ISSUE TITLE
Panning animation does not cancel upon tap. (iOS)

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1258]
Steps to reproduce

1. Flick to pan the map fast
2. Tap to stop the panning

Panning animation continues instead of stopping upon tap.

**Comment by incanus** [comment]
This used to work — might be related to https://github.com/mapbox/mapbox-gl-native/commit/12c07b916b106272ba68f0fc85a10b774fd07a50.

**Comment by 1ec5** [comment]
I don’t see anything in 12c07b916b106272ba68f0fc85a10b774fd07a50 that would’ve regressed this detail. In fact, I don’t see how any of the existing gesture recognizers would be able to stop the drift-pan animation on touch down. It looks like we’ll need to stop the animation within `-touchesBegan:withEvent:`.
