### ISSUE TITLE
Arabic text is not displayed correctly

### ISSUE THREAD

**Issue by rafati** [mapbox/mapbox-gl-native#1259]
Please see the two screenshots below for the following coordination:
longitude: 31.7690400944025
latitude: 35.1514434765522

The first one have been generated using mapbox SDK, while the second one have been done using mapbox-gl. Please notice how the arabic characters are not connected in the second one, also the characters are displayed left to right instead of right to left.
Please let me know if you need any more information on this issue.
Thanks

![screen shot 2015-04-13 at 4 12 58 am](https://cloud.githubusercontent.com/assets/11851312/7112053/d4ee417c-e193-11e4-99cb-a352e53197d1.png)
![screen shot 2015-04-13 at 4 01 51 am](https://cloud.githubusercontent.com/assets/11851312/7111888/7b1d0fe4-e192-11e4-87ae-bbdccfd8e143.png)

**Comment by mikemorris** [comment]
Known issue, we haven't added support for text shaping (connected characters) or right-to-left scripts yet.

**Comment by mikemorris** [comment]
-> https://github.com/mapbox/mapbox-gl/issues/4
