### ISSUE TITLE
Symbol Layer Icons have different sizes

### ISSUE THREAD

**Issue by felixerdy** [mapbox/mapbox-gl-native#12595]
I created custom markers based on the Mapbox Maki Icons. All of them were built using the same template. However, they don't appear to have the same size on the map. This is a follow up of #11513 with a provided example project.

### Steps to reproduce

 1. Clone https://github.com/felixerdy/mapbox-explore-outdoors-18/tree/master/navigation
 2. Run project on Android device
 3. Look at the icons

### Expected behavior
All icons have the same size

### Actual behavior
Icons have a different size (e.g. compare the burger icon with the bbq icon)
![screenshot_atlas_20180809-204335](https://user-images.githubusercontent.com/12086004/43919580-a5faaa36-9c16-11e8-9307-bb54757f7aaf.png)

### Configuration

**Android versions:** Android 8.1.0 [Pixel Experience OnePlus 3T](https://forum.xda-developers.com/oneplus-3/oneplus-3--3t-cross-device-development/rom-pixel-experience-t3729897)
**Device models:** OnePlus 3T
**Mapbox SDK versions:** 6.3.0@aar

**Comment by tobrun** [comment]
Thanks for the report @felixerdy and providing code for reproducing!

Logging out the used width and height in your drawableToBitmap function shows:
```
08-14 14:32:54.540 19537-19537/felix.atlas E/SIZE: 72 72
08-14 14:32:54.557 19537-19537/felix.atlas E/SIZE: 72 72
08-14 14:32:54.560 19537-19537/felix.atlas E/SIZE: 90 90
```
This means that the source of the issue will be with the used resources and not with the maps sdk. A quick glance at your vector resources doesn't immediately show the issue. I will have to close this issue as this isn't actionable for us.
