### ISSUE TITLE
Document application sandbox requirements

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#12598]
If you switch on the App Sandbox capability for a macOS application target, mbgl fails to load any style with what appears to be a hostname resolution error:

```
[ERROR] {}[Setup]: loading style failed: A server with the specified hostname could not be found.
```

The macOS map SDK requires the ability to make outgoing network requests to Mapbox APIs. So the Outgoing Connections (Client) checkbox needs to be checked:

<img width="412" alt="outgoing connections" src="https://user-images.githubusercontent.com/1231218/43927225-b8b19b38-9be1-11e8-8225-60dbdd24a65b.png">

It may sound obvious, but we should document this requirement for completeness’ sake.

/cc @riastrad

**Comment by songyuyang0918** [comment]
On iphone, GCDWebServer was used to read mbtiles in the sandbox through the local service. Everything was normal before, but recently it reported "[ERROR] {}[Style]: Failed to load tile 14/13590/7009=>14 for source testmbtiles-14-18. Mbtiles: A server with the specified hostname could not be found."
Is there a good solution for him?
