### ISSUE TITLE
Unable to clone git repo

### ISSUE THREAD

**Issue by jcamp1** [mapbox/mapbox-gl-native#1261]
Hi guys,

Upon an initial clone, when I run the following command:
```
git submodule update
```

I get the error:
```
fatal: reference is not a tree: ab5a46ff7e970de5578df48a1e1f013bd5e1bd4e
Unable to checkout 'ab5a46ff7e970de5578df48a1e1f013bd5e1bd4e' in submodule path 'test/ios/KIF'
```

Research seems to indicate that there was a main branch commit/push that references a module that was not pushed to the server.

Thanks,
Justin

**Comment by friedbunny** [comment]
Originally added: https://github.com/mapbox/mapbox-gl-native/commit/350be60

https://github.com/mapbox/KIF/tree/ab5a46ff7e970de5578df48a1e1f013bd5e1bd4e

**Comment by friedbunny** [comment]
It looks like the `.gitmodules` submodule got changed to point at the main KIF repo but the subproject commit for `test/ios/KIF` still references the Mapbox fork.

**Comment by friedbunny** [comment]
@jcamp1 You should still be able to proceed with using your local clone, KIF is only used for iOS tests (that aren't fully reintegrated yet). Doing `make iproj` will build a working iOS Xcode project for you, for example.

**Comment by jcamp1** [comment]
hi @friedbunny,

Yes you're correct. I've successfully imported the compiled android aar.
Thanks!
