### ISSUE TITLE
Mapbox map turning to black screen while downloading offline regions

### ISSUE THREAD

**Issue by BringeRaj** [mapbox/mapbox-gl-native#12610]
I have two issues while using offline map in the Mapbox SDK. They are,

- First issue is that when I’ve started downloading a region and navigate to other screen which contains a map it turns out to be black until the offline map is completely downloaded. Please find the below attachment for more details, where mapbox demo app is used to demonstrate this issue.

- Second issue is that while downloading a large region(region covering a country) the app gets crashed.

How to resolve these issues?

Tested on Android version 6.0, 7.0 and 8.0. I am using mapbox SDK version 6.1.3

![mapbox](https://user-images.githubusercontent.com/36030954/43988713-106a5ca2-9d59-11e8-8931-04c460ef21a6.gif)

**Comment by tobrun** [comment]
@BringeRaj would you be able to retest with a more recent version? eg 6.3.0 (6.4.0 will be released later today) In gif below I'm downloading a large region on appication start (clean install), while the map takes a couple seconds to load, it shows as expected:

![ezgif com-video-to-gif 29](https://user-images.githubusercontent.com/2151639/44159283-39900800-a0b7-11e8-814a-1b46b4df5fe7.gif)

**Comment by tobrun** [comment]
Capturing from @LukasPaczos that this is still an issue with 6.3.0 but is resolved with 6.4.0.
@BringeRaj would you be able to provide a stacktrace of the crash mentioned in op with using v6.4.0?
Please open a new issue for that. Closing as black screen is resolved.
