### ISSUE TITLE
Multiple text formats for symbols via "format" expression

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#12612]
Port of https://github.com/mapbox/mapbox-gl-js/pull/6994, in order to support multi-icon/multi-text symbols (https://github.com/mapbox/mapbox-gl-js/issues/4366).

**Comment by ChrisLoer** [comment]
Fixed with https://github.com/mapbox/mapbox-gl-native/pull/12624. 🎉
