### ISSUE TITLE
Do not work on Genymotion

### ISSUE THREAD

**Issue by dsilvera** [mapbox/mapbox-gl-native#12629]
### Steps to reproduce

 1. Clone the last stable version 6.3.0 (https://github.com/mapbox/mapbox-gl-native/tree/android-v6.3.0)

 2. Change access token with yours
 
3. Launch test app on Genymotion (any version)

### Expected behavior
The card manipulation is fluid.

### Actual behavior
The map is difficult to manipulate. It is not fluid.

### Configuration

**Android versions:**  Any version
**Device models:** Genymotion
**Mapbox SDK versions:** 6.3.0

On version 5.4, we do not have this problem. It is a blocking problem to migrate to this new version

**Comment by mayardb** [comment]
By the way, the problem exists on avd too. Loading tiles makes the application lags.

![avd mapbox lags](https://user-images.githubusercontent.com/6266608/44195428-50773e80-a139-11e8-91a8-7396578d90d5.gif)

But it's worse on genymotion.

![genymotion mapbox lags](https://user-images.githubusercontent.com/6266608/44198802-9be21a80-a142-11e8-99d0-f09bae4e347f.gif)

To reproduce this animation, add in `SimpleMapActivity`:
```java
    @Override
    protected void onResume() {
        super.onResume();
        mapView.onResume();

        mapView.addOnMapChangedListener(new MapView.OnMapChangedListener() {
            @Override
            public void onMapChanged(int change) {
                if (change == MapView.DID_FINISH_RENDERING_FRAME_FULLY_RENDERED) {
                    mapView.getMapAsync(mapboxMap -> {
                        mapView.removeOnMapChangedListener(this);
                        mapboxMap.animateCamera(CameraUpdateFactory.newCameraPosition(
                                new CameraPosition.Builder()
                                        .target(new LatLng(48.85, 2.35))
                                        .zoom(9)
                                        .build()
                                ), 3000
                        );
                    });
                }
            }
        });
    }```

**Comment by lilykaiser** [comment]
@philemonmerlet , we expect https://github.com/mapbox/mapbox-gl-native/pull/12832 to improve this issue. It should be released in the middle of next week for you to try out!
