### ISSUE TITLE
call onLowMemory on Android memory warning

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#1263]
https://github.com/mapbox/mapbox-gl-native/pull/1255#issue-67710046

**Comment by ljbade** [comment]
Also need to hook up `setSourceTileCacheSize`

**Comment by ljbade** [comment]
I am adding this to `MapView`.

The example app and Sirius will need to forward [onLowMemory()](http://developer.android.com/reference/android/content/ComponentCallbacks.html) or [onTrimMemory](http://developer.android.com/reference/android/content/ComponentCallbacks2.html) event to `MapView`.
