### ISSUE TITLE
Java 8 language features

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#12637]
Not all enterprise clients are able to use java 8 in their projects and as a result can't upgrade to a recent version of the Mapbox Maps SDK for Android. Afaik we only use a couple of lambda constructs and try with resources constructions that can be easily reverted.

Issue that needs to be fixed downstream before picking this up in https://github.com/mapbox/mapbox-java/issues/868.

cc @mapbox/maps-android

**Comment by osana** [comment]
This was brought up before in https://github.com/mapbox/mapbox-gl-native/issues/11392 as well

**Comment by osana** [comment]
According to Oracle documentation:
