### ISSUE TITLE
Warnings on making release signed APK, that com.google.auto.value.AutoValue cant be found

### ISSUE THREAD

**Issue by AmirMehr** [mapbox/mapbox-gl-native#12635]
When I want to make A signed release APK, Mapbox produce warnings, The whole warnings are:
Java Compiler:
com.mapbox.geojson.BoundingBox: can't find referenced class com.google.auto.value.AutoValue 
com.mapbox.geojson.Feature: can't find referenced class com.google.auto.value.AutoValue 
com.mapbox.geojson.FeatureCollection: can't find referenced class com.google.auto.value.AutoValue 
com.mapbox.geojson.GeometryCollection: can't find referenced class com.google.auto.value.AutoValue 
com.mapbox.geojson.LineString: can't find referenced class com.google.auto.value.AutoValue 
com.mapbox.geojson.MultiLineString: can't find referenced class com.google.auto.value.AutoValue 
com.mapbox.geojson.MultiPoint: can't find referenced class com.google.auto.value.AutoValue 
com.mapbox.geojson.MultiPolygon: can't find referenced class com.google.auto.value.AutoValue 
com.mapbox.geojson.Point: can't find referenced class com.google.auto.value.AutoValue 
com.mapbox.geojson.Polygon: can't find referenced class com.google.auto.value.AutoValue 
there were 10 unresolved references to classes or interfaces. 
Exception while processing task java.io.IOException: Please correct the above warnings first. 

Android:
        minSdkVersion 16
        targetSdkVersion 28
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.3.0'
Note: I didn't modify proguard, it is default
Android Studio 3.1.4
Build #AI-173.4907809, built on July 24, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by LukasPaczos** [comment]
Hey @AmirMehr! Could you ensure that your project includes the `proguard-rules.pro` file that we ship with the library?
```
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
```
Above line is responsible for this.

**Comment by AmirMehr** [comment]
@LukasPaczos Can u send me link or just write answer here?
