### ISSUE TITLE
tweak logo placement on iOS

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1265]
This looks sloppy. 

![img_3268 copy](https://cloud.githubusercontent.com/assets/17722/7140952/4ed63752-e283-11e4-9f26-b39b8193aae2.png)

**Comment by 1ec5** [comment]
It’s aligned to the baseline of “Ma_box”, not the bottom of the “p”.

**Comment by incanus** [comment]
Right, but it looks weird IMHO and the side margins are different, anyway.

**Comment by incanus** [comment]
The placement to the _(i)_ by the way is Apple's default.

**Comment by 1ec5** [comment]
Ref #1079

**Comment by 1ec5** [comment]
I also considered aligning the baseline of “Ma_box” (not counting the outline) to the “i” in :information_source:.

**Comment by bsudekum** [comment]
Have you considered remove the :information_source: and just going with the `Mapbox` logo? It's a lot going on.

**Comment by incanus** [comment]
The :information_source: is how we reveal attribution info, and eventually contribution info. Currently on GL it just opens Safari, but on the iOS SDK, we've had a lot of luck with popping both the OSM and the open source code info in there so that folks don't forget it (it's opt-out, and [worded in a way](https://www.mapbox.com/mapbox-ios-sdk/api/Classes/RMMapView.html#task_Attributing%20Map%20Data) that makes people question that they should be hiding it). 

![anigif-1429029353](https://cloud.githubusercontent.com/assets/17722/7141937/ac1d8892-e289-11e4-925c-e98060704e5b.gif)

**Comment by 1ec5** [comment]
And if we had the logo subsume the function of the :information_source: then we’d probably launch a thousand [talk@](https://lists.openstreetmap.org/listinfo/talk/) threads.

**Comment by incanus** [comment]
Things look ok now.
