### ISSUE TITLE
Npm install failing with 403 error

### ISSUE THREAD

**Issue by ma2rten** [mapbox/mapbox-gl-native#12667]
I'm using MacOS. Node version v10.9.0. 

I'm getting the following error:

node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v4.0.0-pre.14/node-v64-darwin-x64-Release.tar.gz

**Comment by ma2rten** [comment]
To be sure I also tried version v4.9.1 of node since the README says:

"Node.js v4.x (note: v5+ is known to have issues)"

**Comment by jfirebaugh** [comment]
We're not yet publishing binaries for Node v10, only for v6 at the moment. We've merged support for simultaneous v6/8/10 support to `master`, but the v4.0.0-pre releases are being made from an older branch for the time being.
