### ISSUE TITLE
Too much friction when flicking (short-distance panning) the map

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1266]
@lbud showed me today that the way `MGLMapView` handles panning gestures seems to impede navigation more than MapKit and the Google Maps SDK, as measured by the (very handy!) ease-of-getting-across-town metric. Part of this perception may come from #1258, but we definitely differ from those frameworks in other ways as well.

Here’s the first thing that comes to mind: in Mapbox GL, “flicking” the map doesn’t cause it to travel as far, and it takes a more robust pan gesture to register a flick. Both MapKit and the Google Maps SDK are more sensitive to flicks. The result is that you feel more friction while navigating.

I don’t have a good setup for scientifically comparing our gesture recognition, but in the name of pseudoscience, I positioned an `MGLMapView` and a `MKMapView` both so that [Twp. Rd. E in Williams Co., OH](https://www.mapbox.com/mapbox-gl-styles/#16/41.4859/-84.7995), is at the bottom at roughly the same zoom level. (This county built roads in a mostly regular grid, numbering north-south roads and lettering east-west roads, surely anticipating this experiment.) In the screen recordings below, 16 downward flicks of roughly the same length and speed sent the `MGLMapView` north to [Co. Rd. I](https://www.mapbox.com/mapbox-gl-styles/#16/41.5432/-84.7991) but the `MKMapView` all the way to [SR 34](https://www.mapbox.com/mapbox-gl-styles/#16/41.5566/-84.7976) (which would be J on the grid):

![mapbox](https://cloud.githubusercontent.com/assets/1231218/7145708/261fdc6c-e2a3-11e4-9827-084b8ac2df07.gif) ![mapkit](https://cloud.githubusercontent.com/assets/1231218/7145711/285344a6-e2a3-11e4-9aa5-7a1b51e2adc8.gif)

On a device, the same gestures also took the `MGLMapView` to Co. Rd. I but sent the `MKMapView` past I-80/90 (roughly O on the grid). Google Maps sped all the way to Co. Rd. S.

It’s important to get this gesture right because it’s probably going to be the most common.

**Comment by incanus** [comment]
Interesting, I don't use it this way at all, but my gestures are totally influenced by my development! 

/cc @mourner, who tweaked our current inertial pan last.

**Comment by mourner** [comment]
@1ec5 can you try fiddling with the `deceleration` and `ease` parameters here? https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/MGLMapView.mm#L661 E.g. decreasing `deceleration` will make it travel further, and changing `ease` will alter the slowdown curve.

**Comment by ljbade** [comment]
It would be nice to take the values you end up with here and using them for panning on Android too. Flicking is rather broken on Android currently though.

**Comment by 1ec5** [comment]
I’m continuing to play with the constants, with an eye towards making the map feel as slippery as a `UIScrollView`.

**Comment by 1ec5** [comment]
The framerate didn’t turn out to be impacted by 2bc63f76a4c3200c61902e7133898d7ba35fedc1 after all. I was probably seeing minor performance degradation due to increased tile loading from panning farther each time.
