### ISSUE TITLE
LLVM_LTO should be enabled for all configurations and not just Release/ReleaseWithSymbols

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#12669]
Is there any reason to disable LLVM_LTO for debug configuration? I do not notice any preceptible degradation in link time when enabled for debug configuratio.

### Expected behavior
Link time flags should as close as possible between debug and release builds.

### Actual behavior
LLVM_LTO is disabled for debug configuration.

### Configuration

**Mapbox SDK versions:** 
**iOS/macOS versions:** 
**Device/simulator models:**
**Xcode version:**

**Comment by jfirebaugh** [comment]
Yes, LTO definitely increases the link time significantly.

**Comment by jfirebaugh** [comment]
Yes, see https://github.com/mapbox/mapbox-gl-native/pull/12502#issuecomment-408956255.

**Comment by mb12** [comment]
@jfirebaugh Where do you see the massive increase in link time for iosapp or its dependencies?  I enabled monolithic LTO in Xcode for these targets.

**Comment by mb12** [comment]
@jfirebaugh Having the same link time switches between release and debug bits would be preferable(esp a link time option that is not default.). But if there is a 50x degradation in link time  then it’s not worth it. Thanks for looking into it.
