### ISSUE TITLE
old sources not released

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1267]
If you change map styles, the new one loads async, parses, and creates its source(s). However, the old sources~~, and possibly the style,~~ never go away. 

This was revealed in https://github.com/mapbox/mapbox-gl-native/pull/1255#issuecomment-92618603 when it was found that naturally, the source's cache also doesn't go away, so we start accumulating sources with ever-growing tile caches.

**Comment by incanus** [comment]
The style's destructor does get called, but `Source`'s never does.

**Comment by ansis** [comment]
StyleBucket has a shared pointer to Source https://github.com/mapbox/mapbox-gl-native/blob/88b8d452b9ed2cc6c156b6b446904b86afd3c7a2/src/mbgl/style/style_bucket.hpp#L23
StyleLayer has a shared pointer to StyleBucket https://github.com/mapbox/mapbox-gl-native/blob/88b8d452b9ed2cc6c156b6b446904b86afd3c7a2/src/mbgl/style/style_layer.hpp#L70
Style has a shared pointer to StyleLayer https://github.com/mapbox/mapbox-gl-native/blob/88b8d452b9ed2cc6c156b6b446904b86afd3c7a2/src/mbgl/style/style.hpp#L37
VectorTileData has a shared pointer to Style https://github.com/mapbox/mapbox-gl-native/blob/88b8d452b9ed2cc6c156b6b446904b86afd3c7a2/src/mbgl/map/vector_tile_data.hpp#L63
Source has pointers to VectorTileData https://github.com/mapbox/mapbox-gl-native/blob/88b8d452b9ed2cc6c156b6b446904b86afd3c7a2/src/mbgl/map/source.hpp#L98

I'm still looking for a good way to fix this.

**Comment by jfirebaugh** [comment]
VectorTileData is supposed to [break the reference chain](https://github.com/mapbox/mapbox-gl-native/blob/88b8d452b9ed2cc6c156b6b446904b86afd3c7a2/src/mbgl/map/vector_tile_data.cpp#L52) when it starts the parse.

Is it possible this happens only for [cancelled tiles](https://github.com/mapbox/mapbox-gl-native/blob/88b8d452b9ed2cc6c156b6b446904b86afd3c7a2/src/mbgl/map/tile_data.cpp#L23)?

**Comment by incanus** [comment]
Looking at this.

**Comment by incanus** [comment]
`StyleLayer`, and thus `StyleBucket`, which holds a reference to `Source`, never go away.

**Comment by incanus** [comment]
Maybe unrelated, but any idea @kkaefer @jfirebaugh why we are not using smart pointers for `StyleLayer` like this? 

https://gist.github.com/incanus/af8a4cd9cb8ae46eec01

**Comment by jfirebaugh** [comment]
Smart pointers should only be used when it is necessary to express ownership or lifetime semantics. `render`, `hasData`, `renderLayer`, etc. do not need to express such semantics -- they receive a layer reference, do something with it, and then return, without storing a reference to the layer. So there's no need to use a smart pointer.

**Comment by incanus** [comment]
Cool, thanks for the info @jfirebaugh. 

Welp, definitely tracked it down to [my block that creates the annotation layer](https://github.com/mapbox/mapbox-gl-native/blob/ed74c6e23d12a9c196d623ab1ed344c1d829fcc7/src/mbgl/style/style_parser.cpp#L40-L69). Can't figure out why yet, but commenting that out gets layers, buckets, and sources to release properly.

**Comment by incanus** [comment]
You were on the right track, @jfirebaugh — but so was I. Turns out `VectorTileData` _may_ be holding onto the style for cancelled tiles (still gonna dig on that, plus found a bug related to annotations at `z0` that I'll also hit), but `LiveTileData` was _always_ holding onto the style in cases of no annotations, because `LiveTile` objects were never coming out of `annotationManager.getTile()`, thus `parse()` was never called, nor `style.reset()`. Since `LiveTileData` are always created with a style reference, we'll have to always `style.reset()`. 

Digging around in the creation of the annotations style layer and its memory management for the `sources`, `sourcesMap`, `layers`, and `layersMap` was a red herring. :red_circle: :fish: :-1: 

Fix incoming.

**Comment by incanus** [comment]
Yep, easily confirmed that cancelled vector tiles also don't get their style reset. Fixing.
