### ISSUE TITLE
Show the Marker title, as soon as the map is loaded

### ISSUE THREAD

**Issue by tr0lczyk** [mapbox/mapbox-gl-native#12670]
Hi All! I would like to show to user the title of the marker added to a map, however none of the solutions that i've found on the web is giving anything. Unfortunately not the showInfoWindow nor selectMarker helps:(

Please see below my code:

`
 
@Override

    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

        Mapbox.getInstance(getActivity(),getString(R.string.map_box_api));

        View rootView = inflater.inflate(R.layout.fragment_ustka_object_map_mapbox, container,
                false);

        mapView = rootView.findViewById(R.id.mapViewMapBox);

        mapView.onCreate(savedInstanceState);

        mapView.getMapAsync(new OnMapReadyCallback() {

            @Override
            public void onMapReady(MapboxMap mapboxMap) {

                mapboxMapMyLocation = mapboxMap;
                enableLocationPlugin();

                CameraPosition position = new CameraPosition.Builder()
                        .target(new LatLng(lat,lng))
                        .zoom(11)
                        .tilt(30)
                        .build();

                mapboxMap.animateCamera(CameraUpdateFactory
                        .newCameraPosition(position), 4000);

                Marker marker = mapboxMap.addMarker(new MarkerOptions().setPosition(new LatLng(lat,lng))
                        .setTitle(name));

                mapboxMap.getUiSettings().setDeselectMarkersOnTap(false);
                mapboxMap.selectMarker(marker);
            }
        });
        return rootView;
    }`

### Configuration
**Newest MapBox version**

**Comment by LukasPaczos** [comment]
Thanks for reaching out @tr0lczyk! Let's continue the discussion on the [related SO question](https://stackoverflow.com/questions/51926977/show-the-marker-title-as-soon-as-the-mapbox-map-is-loaded-on-android) until we can determine whether it really is a bug, meanwhile, I'm closing this one.
