### ISSUE TITLE
Ho to show infoWindow for all markers

### ISSUE THREAD

**Issue by VictorJava** [mapbox/mapbox-gl-native#12684]
Hi,
I can show infoWindow for one of the marker like  mapboxMap.selectMarker(marker)
How I can show infoWindow for all markers on map?
Thanks

### Configuration

**Android versions: 6.0** 
**Device models: Nexus 5** 
**Mapbox SDK versions: com.mapbox.mapboxsdk:mapbox-android-sdk:6.3.0**

**Comment by tobrun** [comment]
@VictorJava 
You can do this with:
```java
mapboxMap#setAllowConcurrentMultipleOpenInfoWindows(true)
```
and afterwards iterating all markers and calling
```java
mapboxMap.selectMarker(marker)
```
Note that this might not scale very well with many markers. Depending on the use-case I would suggest generating bitmaps from views and using that as your icon-image in a SymbolLayer approach. An example of that can be found [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java)

**Comment by VictorJava** [comment]
@tobrun 
Thanks for your quick help.
