### ISSUE TITLE
Crash when map tile request is cancelled with inject the OKHttpClient.

### ISSUE THREAD

**Issue by anjinlu** [mapbox/mapbox-gl-native#12700]
I try to catch the error code of Mapbox map tile fetch, on Android, I do inject the OkHttp client, the code is very simple, but got crash when the map tile request is cancelled. (Mapbox will cancel the tile request if the tile is not needed, e.g. a request could be cancelled when pan the map.

using System;
using Square.OkHttp3;
public class HttpInterceptor : Java.Lang.Object {
	public Response Intercept(IInterceptorChain chain) {
		Response response = null;
		try {
			Request request = chain.Request();
			response = chain.Proceed(request);

                        // Do some thing here depends on the http code.

		} catch (Exception e) {
			throw;
		}
		return response;
	}
}

var interceptor = new HttpInterceptor();
OkHttpClient client = new OkHttpClient.Builder()
	.AddNetworkInterceptor(new HttpInterceptor())
	.Build();
Com.Mapbox.Mapboxsdk.Http.HttpRequestUtil.SetOkHttpClient(client);

It works and I can check the http response code, but cause crash if chain.Proceed(request) throw an exception.
-- Re-throw the exception, will cause crash.
-- Do not re-throw the exception and return NULL, will crash due to NRE ( NULL Reference Exception)

Any idea?

Thanks.

**Comment by tobrun** [comment]
adding try catch block around request execution doesn't seem to be supported as it overwrites the internally set logic. Don't feel this is something that needs to be supported, happy to look more into this is there is a valid use-case for it.
