### ISSUE TITLE
iOS make iproj，.ccache/tmp/nsthread.stdout: Permission denied

### ISSUE THREAD

**Issue by xiaoleiiOS** [mapbox/mapbox-gl-native#12705]
ccache: error: Failed to create temporary file for /Users/wangxiaolei/.ccache/tmp/nsthread.stdout: Permission denied
Command /Users/***/Documents/***/mapbox-gl-native/build/ios/launch-c failed with exit code 1

When make iproj is successful, run the project and prompt for an error.

Who can help me solve this problem,thank you!

**Comment by friedbunny** [comment]
This is likely an issue with your local ccache installation — make sure that your user owns the files in question.
