### ISSUE TITLE
sharedThreadPool reference in platform specific implementations

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#12712]
`DraggableMarkerActivity` crashes on `master` during startup with this exception:
```
java.lang.Error: mutex lock failed: Device or resource busy
    at com.mapbox.mapboxsdk.style.sources.GeoJsonSource.nativeSetFeatureCollection(Native Method)
    at com.mapbox.mapboxsdk.style.sources.GeoJsonSource.setGeoJson(GeoJsonSource.java:220)
    at com.mapbox.mapboxsdk.style.sources.GeoJsonSource.<init>(GeoJsonSource.java:124)
    at com.mapbox.mapboxsdk.testapp.activity.style.DraggableMarkerActivity.<init>(DraggableMarkerActivity.kt:49)
    at java.lang.Class.newInstance(Native Method)
    at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
    at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
```

/cc @tobrun

**Comment by LukasPaczos** [comment]
Initial debugging shows that creating sources before the map is initialized is broken and results in the above crash or freeze. This regression was introduced with the async GeoJsonSource features conversion in https://github.com/mapbox/mapbox-gl-native/pull/12580.

**Comment by LukasPaczos** [comment]
I'm seeing `mutex lock failed: Device or resource busy` when trying to [lock `mutex`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/default/mbgl/util/default_thread_pool.cpp#L50) after [invoking the actor](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/src/style/sources/geojson_source.cpp#L119) but only when the map is not created. There seems to be no issues scheduling the actor after the map is initialized.

**Comment by jfirebaugh** [comment]
The `GeoJSONSource` constructors call `std::make_unique<Actor<FeatureConverter>>(*sharedThreadPool()), dereferencing the `std::shared_ptr<ThreadPool>` that `sharedThreadPool()` returns. But as soon as this line is complete, the `shared_ptr` is destroyed, and it's the last outstanding reference, so the `ThreadPool` is destroyed and the actor is left with a dangling reference.

cc @kkaefer

**Comment by jfirebaugh** [comment]
`CustomGeometrySource` has the same issue.

**Comment by kkaefer** [comment]
They shouldn't reference `sharedThreadPool` to begin with. It's a platform-specific implementation and will e.g. not be available in the node bindings.

**Comment by LukasPaczos** [comment]
What are the next steps here? Should we keep the reference to the pointer instead of dereferencing it? Is a separate thread pool implementation required as of now?

Ideally, the fix would need to land before the `6.5.0` release.

**Comment by jfirebaugh** [comment]
> They shouldn't reference `sharedThreadPool` to begin with. It's a platform-specific implementation and will e.g. not be available in the node bindings.

This is the Android-specific `GeoJSONSource` class, so we're okay on that front at least.

**Comment by kkaefer** [comment]
🤦‍♂️
