### ISSUE TITLE
Weird behavior when combining Predicates/Expressions

### ISSUE THREAD

**Issue by MehdiSv** [mapbox/mapbox-gl-native#12723]
**Platform: iOS
Mapbox SDK version: 4.2.0**

I'm trying to apply a filter in addition to a layer's default filter.
My default filter is like this:

```
MGL_MATCH(name, {"Free", "MeterHour", "NoData", "TimeLimit"}, 1, 0) == 1)
```

My additional filter looks like this:
```
(CAST(price, "NSNumber") <= 25 OR price == nil)
```

Both filters combined look like this:
```
(CAST(price, "NSNumber") <= 25 OR price == nil) AND MGL_MATCH(name, {"Free", "MeterHour", "NoData", "TimeLimit"}, 1, 0) == 1
```
But the price == nil is not taken into account.

This is how I create my additional filter:
```
let priceValuePredicate = NSPredicate(format: "CAST(price, 'NSNumber') <= \(Int(value))")
let priceNamePredicate = NSPredicate(format: "price == nil")
return NSCompoundPredicate(type: .or, subpredicates: [priceValuePredicate, priceNamePredicate])

```

Should I create it differently for this to work?
I'm not sure what is the issue here.

Note: If I remove the default filter, everything works as expected (nil is taken into account).

**Comment by fabian-guerra** [comment]
Hi, @MehdiSv. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/) or check our [documentation](https://www.mapbox.com/ios-sdk/api/4.3.0/predicates-and-expressions.html). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).

**Comment by MehdiSv** [comment]
Hi @fabian-guerra, thanks for your answer!

This seems to me like a bug in the SDK. I read the documentation and this seems like it should be working.
Am I missing something obvious?

Thanks!
