### ISSUE TITLE
App crashes because of NPE in TelemetryUtils

### ISSUE THREAD

**Issue by iverc** [mapbox/mapbox-gl-native#12748]
App crashes because of NPE in TelemetryUtils.

  | com.mapbox.android.telemetry.TelemetryUtils.obtainSharedPreferences (TelemetryUtils.java:191)
-- | --
  | com.mapbox.android.telemetry.TelemetryLocationEnabler.updateLocationPreferences (TelemetryLocationEnabler.java:61)
  | com.mapbox.android.telemetry.TelemetryLocationEnabler.updateTelemetryLocationState (TelemetryLocationEnabler.java:40)
  | com.mapbox.android.telemetry.TelemetryService.disableTelemetryLocationState (TelemetryService.java:243)
  | com.mapbox.android.telemetry.TelemetryService.onDestroy (TelemetryService.java:65)
  | android.app.ActivityThread.handleStopService (ActivityThread.java:3504)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)

### Expected behavior
App should not crash.

### Actual behavior
App crashes.

### Configuration

**Android versions:** 8.1.0
**Device models:** TA-1004
**Mapbox SDK versions:** 6.3.0

What is the latest stable version of Mapbox SDK for Android?
Lots of various crashes and ANR's started to appear since update to version 6+.
Thanks.

**Comment by zugaldia** [comment]
Thanks @iverc for the report. That error points at [the following code](https://github.com/mapbox/mapbox-events-android/blob/master/libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java#L190-L192), an attempt to access the app context:

```
static SharedPreferences obtainSharedPreferences() {
    return MapboxTelemetry.applicationContext.getSharedPreferences(MAPBOX_SHARED_PREFERENCES, Context.MODE_PRIVATE);
  }
```

@electrostat Could this be related to https://github.com/mapbox/mapbox-events-android/issues/146#issuecomment-416347786? If so, are there any strategies the app could follow to avoid the issue before a fix lands?

**Comment by electrostat** [comment]
Adding `null` checks in this PR: https://github.com/mapbox/mapbox-events-android/pull/202
