### ISSUE TITLE
User dot sometimes jitters during panning gesture

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#12740]
Sometimes, the user dot (user location annotation view) moves inconsistently as the user pans the map view from side to side; in other words, it sometimes darts forward or backtracks, producing a jarring jittering effect. To illustrate the problem, here’s a 30&nbsp;fps recording at half speed ([original screen recording](https://www.dropbox.com/s/758utro56nkiv80/jitter.mp4?dl=0)):

![jitter](https://user-images.githubusercontent.com/1231218/44617763-ba6ca380-a81d-11e8-9c78-9109db675b24.gif)

This effect is distinct from the issue in #5489, in which the map view lags behind the annotation views but the annotation views move at a consistent rate. That issue also reproduces during camera animations driven by mbgl, such as drift animations following gestures. By contrast, this issue only reproduces during panning gestures, even slow ones in which the underlying map is able to move at a consistent rate. It’s fairly difficult to reproduce reliably: scrubbing the same map region repeatedly will reliably reproduce the issue, but then it’ll stop reproducing after you switch applications or stop interacting with the map for awhile.

The user dot differs from any other annotation view in that its `center` property is set inside an instantaneous UIView animation block that is triggered by `-glkView:drawInRect:` after telling mbgl to render a frame:

https://github.com/mapbox/mapbox-gl-native/blob/d297bf10ef89e97da30e1a00dd49560e18bcb3f0/platform/ios/src/MGLMapView.mm#L987-L989 https://github.com/mapbox/mapbox-gl-native/blob/d297bf10ef89e97da30e1a00dd49560e18bcb3f0/platform/ios/src/MGLMapView.mm#L5743 https://github.com/mapbox/mapbox-gl-native/blob/d297bf10ef89e97da30e1a00dd49560e18bcb3f0/platform/ios/src/MGLMapView.mm#L5939-L5953

`-glkView:drawInRect:` is driven by a CADisplayLink, which #2985 proposes eliminating. (Optionally, `-updateFromDisplayLink` will also throttle rendering, but that functionality isn’t enabled here.)

Meanwhile, every other annotation view’s `center` property is set directly via `-mapViewDidFinishRenderingFrameFullyRendered:` after mbgl finishes rendering a frame:

https://github.com/mapbox/mapbox-gl-native/blob/d297bf10ef89e97da30e1a00dd49560e18bcb3f0/platform/ios/src/MGLMapView.mm#L5805

`-mapViewDidFinishRenderingFrameFullyRendered:` can be called not only after `-glkView:drawInRect:` asks mbgl to render a frame but also after mbgl renders a frame on its own volition. Perhaps not coincidentally, I’ve only been able to reproduce this issue when labels fade in and out as I pan the map, as seen in the recording above. That fading is driven entirely by a timer in mbgl, as are the drift animations in #5489.

The iOS and macOS map SDKs use mbgl’s synchronous rendering path rather than the asynchronous rendering path that the Android map SDK uses. So on each frame rendered because of CADisplayLink, `-updateAnnotationViews` gets called before `-updateUserLocationAnnotationView`.

### Configuration

**Mapbox SDK versions:** v4.3.0, but probably earlier
**iOS/macOS versions:** 11.4.1
**Device/simulator models:** iPhone 8
**Xcode version:** 10.0 beta 6

/ref https://github.com/mapbox/mapbox-gl-native/issues/8874#issuecomment-300602917
/cc @mapbox/maps-ios

**Comment by 1ec5** [comment]
`-[MGLFaux3DUserLocationAnnotationView updateFrameWithSize:]` also sets the `center` property directly. This code is triggered by a call to `-[MGLUserLocationAnnotationView update]` right after the call to `+[UIView animateWithDuration:delay:options:animations:completion:]` in `-[MGLMapView updateUserLocationAnnotationViewAnimatedWithDuration:]`. Perhaps that `-update` call should go in the completion handler of `+[UIView animateWithDuration:delay:options:animations:completion:]`, which is asynchronous even when it’s instantaneous.

**Comment by 1ec5** [comment]
Fixed in #12895.

**Comment by julianrex** [comment]
I believe there may still be an issue if two simultaneous operations try to modify the user location at the same time (for example dragging the map while the being repositioned by location updates). @1ec5 feel free to reopen should you notice this.
