### ISSUE TITLE
Nullability of Polygon coordinates

### ISSUE THREAD

**Issue by mkrussel77** [mapbox/mapbox-gl-native#12745]
Not a bug, but there seems to be some inconsistency with the nullability of coordinates.

`CoordinateContainer.coordinates` is not annotated to indicate what the nullability is.  Must of the static analysis treat this as unknown, and you may or may not check.

All the subclasses annotate the method as `NonNull`, except for `Polygon`, which marks it as `Nullable`.  Seems strange that single implementation can be null but all the others cannot.  And if I access from the parent interface, and don't get any warnings about not checking for null.

**Android versions:** N/A
**Device models:** N/A
**Mapbox SDK versions:** 6.4.0

**Comment by tobrun** [comment]
Thanks for the report @mkrussel77 , following up on this upstream in https://github.com/mapbox/mapbox-java/issues/881
