### ISSUE TITLE
Nullability of Feature properties

### ISSUE THREAD

**Issue by mkrussel77** [mapbox/mapbox-gl-native#12744]
Have not actually experienced any problems, but the code shows how it could happen.

In `com.mapbox.geojson.Feature` the `properties` method is annotated as `Nullable`.  The `getStringProperty` and others like it deferences the returned value with out checking for null.

**Android versions:** N/A
**Device models:** N/A
**Mapbox SDK versions:** 6.4.0

**Comment by tobrun** [comment]
Thanks for the report @mkrussel77 , following up on this upstream in https://github.com/mapbox/mapbox-java/issues/880
