### ISSUE TITLE
How to create multiline title or subtitle

### ISSUE THREAD

**Issue by Bogdan59** [mapbox/mapbox-gl-native#12755]
how can in mapbox create multi line in title or subtitle?

Im try 

var features = [MGLPointFeature]()
 let feature = MGLPointFeature()

   feature.coordinate = coordinate
   feature.title = "test text more text here sdfdsffsdfdsfsdf \n sdfdsfsdf"
   feature.subtitle = "test text more text here sdfdsffsdfdsfsdf \n sdfdsfsdf"

   features.append(feature)
   mapView.addAnnotations(features)

But if I press annotation - show only in 1 line title and subtitle

and \n dont show

**Comment by friedbunny** [comment]
Hi @Bogdan59 — thanks for using Mapbox. This repo is for reporting bugs, requesting features, and coordinating work related to the various Mapbox Map SDKs. For help with “how do I” questions, please ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox) or reach out to our excellent [support team](https://www.mapbox.com/contact/support/).
