### ISSUE TITLE
Crash on HTC 610

### ISSUE THREAD

**Issue by jcamp1** [mapbox/mapbox-gl-native#1275]
Greetings,

When I try to load a mapview on my Android HTC 610 I get the following crash:

```
04-15 14:32:22.153    1617-1617/com.app..alpha E/libEGL﹕ validate_display:259 error 3008 (EGL_BAD_DISPLAY)
04-15 14:32:22.153    1617-1617/com.app.alpha E/mbgl﹕ {0}{Main}[OpenGL]: eglCreateWindowSurface() returned error 12296
04-15 14:32:22.153    1617-1617/com.app.alpha A/libc﹕ Fatal signal 6 (SIGABRT) at 0x00000651 (code=-6), thread 1617 (lanmobile.alpha)
```

Thanks,
Justin

**Comment by sevar83** [comment]
I have the same crash on startup:

04-20 23:50:22.073  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: EGL Vendor: Android
04-20 23:50:22.073  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: EGL Version: 1.4 Android META-EGL
04-20 23:50:22.073  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: EGL Client APIs: OpenGL_ES
04-20 23:50:22.073  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: EGL Client Extensions: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_ANDROID_image_native_buffer EGL_ANDROID_recordable
04-20 23:50:22.077  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: Found 6 configs
04-20 23:50:22.077  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: Config 0:
04-20 23:50:22.077  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Caveat: 12344
04-20 23:50:22.077  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Conformant: 4
04-20 23:50:22.077  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Color: 32
04-20 23:50:22.077  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Red: 8
04-20 23:50:22.077  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Green: 8
04-20 23:50:22.077  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Blue: 8
04-20 23:50:22.077  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Alpha: 8
04-20 23:50:22.077  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Alpha mask: 0
04-20 23:50:22.077  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Depth: 24
04-20 23:50:22.077  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Stencil: 8
04-20 23:50:22.077  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Sample buffers: 0
04-20 23:50:22.077  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Samples: 0
04-20 23:50:22.077  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: Config 1:
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Caveat: 12344
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Conformant: 4
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Color: 32
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Red: 8
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Green: 8
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Blue: 8
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Alpha: 0
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Alpha mask: 0
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Depth: 24
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Stencil: 8
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Sample buffers: 0
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Samples: 0
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: Config 2:
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Caveat: 12344
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Conformant: 4
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Color: 32
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Red: 8
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Green: 8
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Blue: 8
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Alpha: 8
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Alpha mask: 0
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Depth: 24
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Stencil: 8
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Sample buffers: 1
04-20 23:50:22.078  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Samples: 4
04-20 23:50:22.082  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: Config 3:
04-20 23:50:22.082  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Caveat: 12344
04-20 23:50:22.082  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Conformant: 4
04-20 23:50:22.082  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Color: 32
04-20 23:50:22.082  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Red: 8
04-20 23:50:22.082  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Green: 8
04-20 23:50:22.082  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Blue: 8
04-20 23:50:22.083  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Alpha: 0
04-20 23:50:22.083  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Alpha mask: 0
04-20 23:50:22.083  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Depth: 24
04-20 23:50:22.083  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Stencil: 8
04-20 23:50:22.083  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Sample buffers: 1
04-20 23:50:22.084  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Samples: 4
04-20 23:50:22.084  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: Config 4:
04-20 23:50:22.088  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Caveat: 12344
04-20 23:50:22.088  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Conformant: 4
04-20 23:50:22.088  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Color: 16
04-20 23:50:22.089  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Red: 5
04-20 23:50:22.089  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Green: 6
04-20 23:50:22.089  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Blue: 5
04-20 23:50:22.089  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Alpha: 0
04-20 23:50:22.089  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Alpha mask: 0
04-20 23:50:22.089  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Depth: 24
04-20 23:50:22.090  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Stencil: 8
04-20 23:50:22.090  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Sample buffers: 0
04-20 23:50:22.090  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Samples: 0
04-20 23:50:22.090  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: Config 5:
04-20 23:50:22.090  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Caveat: 12344
04-20 23:50:22.090  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Conformant: 4
04-20 23:50:22.090  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Color: 16
04-20 23:50:22.090  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Red: 5
04-20 23:50:22.090  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Green: 6
04-20 23:50:22.090  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Blue: 5
04-20 23:50:22.090  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Alpha: 0
04-20 23:50:22.090  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Alpha mask: 0
04-20 23:50:22.090  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Depth: 24
04-20 23:50:22.091  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Stencil: 8
04-20 23:50:22.091  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Sample buffers: 1
04-20 23:50:22.091  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: ...Samples: 4
04-20 23:50:22.091  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: Chosen config is 1
04-20 23:50:22.091  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: Chosen window format is 511
04-20 23:50:22.350  21143-21143/com.mapbox.mapboxgl.testapp V/MapFragment﹕ onStart
04-20 23:50:22.461  21143-21156/com.mapbox.mapboxgl.testapp I/art﹕ Background sticky concurrent mark sweep GC freed 3406(296KB) AllocSpace objects, 1(16KB) LOS objects, 11% free, 2MB/2MB, paused 5.065ms total 89.294ms
04-20 23:50:22.465  21143-21143/com.mapbox.mapboxgl.testapp V/MapFragment﹕ onResume
04-20 23:50:22.491  21143-21203/com.mapbox.mapboxgl.testapp D/OpenGLRenderer﹕ Render dirty regions requested: true
04-20 23:50:22.507  21143-21143/com.mapbox.mapboxgl.testapp D/Atlas﹕ Validating map...
04-20 23:50:22.625  21143-21203/com.mapbox.mapboxgl.testapp I/OpenGLRenderer﹕ Initialized EGL, version 1.4
04-20 23:50:22.626  21143-21203/com.mapbox.mapboxgl.testapp W/OpenGLRenderer﹕ Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
04-20 23:50:22.665  21143-21203/com.mapbox.mapboxgl.testapp D/OpenGLRenderer﹕ Enabling debug mode 0
04-20 23:50:22.883  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: GL Vendor: Imagination Technologies
04-20 23:50:22.883  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: GL Renderer: PowerVR SGX 540
04-20 23:50:22.883  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: GL Version: OpenGL ES 2.0 build 1.9@2291151
04-20 23:50:22.883  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: GL SL Version: OpenGL ES GLSL ES 1.00 build 1.9@2291151
04-20 23:50:22.883  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: GL Extensions: GL_EXT_debug_marker GL_OES_rgb8_rgba8 GL_OES_depth24 GL_OES_vertex_half_float GL_OES_texture_float GL_OES_texture_half_float GL_OES_element_index_uint GL_OES_mapbuffer GL_OES_fragment_precision_high GL_OES_compressed_ETC1_RGB8_texture GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_required_internalformat GL_OES_depth_texture GL_OES_get_program_binary GL_OES_packed_depth_stencil GL_OES_standard_derivatives GL_OES_vertex_array_object GL_OES_egl_sync GL_EXT_multi_draw_arrays GL_EXT_texture_format_BGRA8888 G
04-20 23:50:22.883  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: GL Extensions: L_EXT_discard_framebuffer GL_EXT_shader_texture_lod GL_IMG_shader_binary GL_IMG_texture_compression_pvrtc GL_IMG_texture_npot GL_IMG_texture_format_BGRA8888 GL_IMG_read_format GL_IMG_program_binary GL_IMG_uniform_buffer_object GL_IMG_multisampled_render_to_texture
04-20 23:50:22.883  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: Using GL_OES_vertex_array_object.
04-20 23:50:22.884  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: Using GL_OES_packed_depth_stencil.
04-20 23:50:22.884  21143-21143/com.mapbox.mapboxgl.testapp I/mbgl﹕ {0}{Main}[OpenGL]: Using GL_EXT_debug_marker.
04-20 23:50:23.223  21143-21156/com.mapbox.mapboxgl.testapp I/art﹕ Background partial concurrent mark sweep GC freed 2608(162KB) AllocSpace objects, 1(12KB) LOS objects, 39% free, 2MB/4MB, paused 6.744ms total 56.243ms
04-20 23:50:23.312  21143-21143/com.mapbox.mapboxgl.testapp I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@8bfa88c time:23569442
04-20 23:50:25.375  21143-21200/com.mapbox.mapboxgl.testapp A/libc﹕ Fatal signal 6 (SIGABRT), code -6 in tid 21200 (apboxgl.testapp)

**Comment by jeromoney** [comment]
I got the exact same error on my Nexus 4. Does it work when you run through the AVD emulator?

**Comment by ljbade** [comment]
Reopen if these crashes still occur

**Comment by bleege** [comment]
@jcamp1 @sevar83 @jeromoney If you're still experiencing issues with this, we've got a solution now documented in #1929.  It works for both using the MapView in Fragment and Activity.
