### ISSUE TITLE
glDisableVertexAttribArray(location): Error GL_INVALID_VALUE

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#12762]
### Steps to reproduce

 1. Open DebugActivity (Or any other)
 2. Zoom in 1 level
 3. Wait half a second

### Expected behavior

- Not crash

### Actual behavior

- Crash:

```
W/dalvikvm( 7436): threadid=22: thread exiting with uncaught exception (group=0x417d5700)
E/AndroidRuntime( 7436): FATAL EXCEPTION: GLThread 538
E/AndroidRuntime( 7436): java.lang.Error: glDisableVertexAttribArray(location): Error GL_INVALID_VALUE at /Users/ivo/git/mapbox-gl-native/src/mbgl/gl/value.cpp:382
E/AndroidRuntime( 7436): 	at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeRender(Native Method)
E/AndroidRuntime( 7436): 	at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onDrawFrame(MapRenderer.java:74)
E/AndroidRuntime( 7436): 	at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.onDrawFrame(GLSurfaceViewMapRenderer.java:57)
E/AndroidRuntime( 7436): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1523)
E/AndroidRuntime( 7436): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

### Configuration

**Android versions:** 

4.3

**Device models:** 

Galaxy Nexus

**Mapbox SDK versions:** 

Master branch

**Comment by ivovandongen** [comment]
Looking into this quickly, it turns out that this happens for a Linelayer. But always on `location=8` which might indicate that we hit a limit on this device (assuming this is 0-indexed).

**Comment by kkaefer** [comment]
@ivovandongen can you please find out what the GL_MAX_VERTEX_ATTRIBS value is on this device?

**Comment by kkaefer** [comment]
We fixed this crash with https://github.com/mapbox/mapbox-gl-native/pull/11656, but maybe the Galaxy Nexus is misreporting the number of attributes it supports?

**Comment by ivovandongen** [comment]
> maybe the Galaxy Nexus is misreporting the number of attributes it supports?

I checked (a long time ago) and it reported 8 IIRC.
