### ISSUE TITLE
Running core tests results in segmentation fault

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#12761]
While updating and running the core test make target of `run-android-core-test-x86`, I'm hitting a segmentation fault at start. No additional output or stacktrace shown in the shell provided through adb.

**Comment by alexshalamov** [comment]
@tobrun Looks like it crashes when [android::AndroidRuntime::startReg(&env);](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/src/test/main.jni.cpp#L63
) is called.

Do you know when was the last time these tests were executed? Tests use libandroid_runtime.so APIs that were deprecated https://developer.android.com/about/versions/nougat/android-7.0-changes#ndk

**Comment by tobrun** [comment]
going to be fixed with https://github.com/mapbox/mapbox-gl-native/pull/13628
