### ISSUE TITLE
In 3D mode Map scrolls quickly in the opposite direction when the user attempts to swipe the map downward quickly

### ISSUE THREAD

**Issue by SandipBuchade** [mapbox/mapbox-gl-native#12764]
In 3D mode, when user swipe down without finishing previous swipe animation, the map moves upward (north) and quickly scrolls downward (south) with a bounce effect.

### Steps to reproduce

 1. Drag 2 fingers upside to set map in 3D tilt mode
 2. Swipe down on map continuously before the previous animation is finished.

Please find below the video recording of the issue.
[Functionality - Quick Swipe Downward rebound.mp4.zip](https://github.com/mapbox/mapbox-gl-native/files/2331912/Functionality.-.Quick.Swipe.Downward.rebound.mp4.zip)

### Expected behavior
While in 3D mode, the map should move upword (north) on swiping it down.

### Actual behavior
The map moves upward (north) for a fraction of second and then quickly scrolls downward (south)

### Configuration

**Mapbox SDK versions:** 4.2.0
**iOS/macOS versions:**  iOS 11.4
**Device/simulator models:** iPhone 6
**Xcode version:** 9.4.1

**Comment by friedbunny** [comment]
Thank you very much for taking the time to report this problem, @SandipBuchade — we’re tracking it over at #5292.
