### ISSUE TITLE
Extreme letterboxing on iOS after changing orientation while app is in background

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1276]
If you change the device’s orientation while the app is in the background, the constraints get all wacky.

1. While the device is oriented in portrait mode, press the home button to leave the iOS demo app.
2. Double-press the home button to reveal the demo app in the app switcher.
3. Orient the device to landscape mode, then select the demo app to switch back to it.

![letterboxed](https://cloud.githubusercontent.com/assets/1231218/7169979/2ae5a74a-e37f-11e4-9631-20754aa6cd02.PNG)

**Comment by 1ec5** [comment]
It just keeps getting weirder:

![stretched](https://cloud.githubusercontent.com/assets/1231218/7170125/46d2b514-e380-11e4-81e9-04e20c93ec88.PNG)

While the view is letterboxed, it doesn’t respond to any gestures.

**Comment by 1ec5** [comment]
Apparently a regression from #1254.

**Comment by incanus** [comment]
Doing a `UIImageView` again like this doesn't have the problem: 

https://gist.github.com/incanus/68567dfc7134e0d635a4

**Comment by 1ec5** [comment]
The root cause turned out to be the use of `-[UIView snapshotViewAfterScreenUpdates:]` rather than `-[UIView resizableSnapshotViewFromRect:afterScreenUpdates:withCapInsets:]`.
