### ISSUE TITLE
android-debug-arm-v7 job intermittently timing out waiting for Firebase

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#12773]
See https://circleci.com/gh/mapbox/mapbox-gl-native/151237 — Firebase tests appear to succeed, but CircleCI apparently never gets the final response it’s looking for. The [included firebase link](https://console.firebase.google.com/project/android-gl-native/testlab/histories/bh.1470d2ab45df6f1f/matrices/8724072223529813631) shows that it continued to spin (despite my attempts to cancel).

```
18:44:23 Test is Pending
18:44:35 Starting attempt 1.
18:44:35 Started logcat recording.
18:44:35 Preparing device.
18:44:35 Test is Running
18:45:12 Logging in to Google account on device.
18:45:12 Installing apps.
18:45:24 Retrieving Pre-Test Package Stats information from the device.
18:45:24 Retrieving Performance Environment information from the device.
18:45:24 Started crash monitoring.
18:45:24 Started performance monitoring.
18:45:30 Started video recording.
18:53:58 Stopped video recording.
18:54:10 Stopped performance monitoring.
18:54:16 Stopped crash monitoring.
18:54:16 Retrieving Post-test Package Stats information from the device.
18:54:16 Stopped logcat recording.
18:54:16 Logging out of Google account on device.
18:54:16 Done. Test time = 508 (secs)
Too long with no output (exceeded 20m0s)
```

Refs #10883.

/cc @tobrun @LukasPaczos @zugaldia

**Comment by friedbunny** [comment]
Looks like all of our Firebase jobs are failing to complete:

<img width="658" alt="screen shot 2018-08-29 at 3 47 26 pm" src="https://user-images.githubusercontent.com/1198851/44811522-e16f0080-aba2-11e8-92ee-702bca5405e7.png">

[Firebase status](https://status.firebase.google.com) for Test Lab is green, however.

**Comment by tobrun** [comment]
@friedbunny thanks for adding #12776, 
love the ability for such a feature for the other teams working on this project.

**Comment by tobrun** [comment]
Firebase seems to be operating again as expected, closing for now.
