### ISSUE TITLE
Cannot resolve android 6.5.0-alpha.2 dependency

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#12777]
I am trying to use the latest mapbox alpha version but I get a "Unable to resolve..." error when using this dependency "com.mapbox.mapboxsdk:mapbox-android-sdk:6.5.0-alpha.2". Alpha 1 was working fine for me.

**Comment by mdakram** [comment]
Its not available as gradle dependency as of now.

you can check it here.

https://mvnrepository.com/artifact/com.mapbox.mapboxsdk/mapbox-android-sdk

**Comment by LukasPaczos** [comment]
Hey, thanks for reaching out and testing the pre-releases! You can see that the `alpha.2` is up there http://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-sdk/6.5.0-alpha.2/ but it's strangely not resolving. I'd give it a bit more time as it might be Maven's issue.

**Comment by ac87** [comment]
I had the same problem but found the alpha.2 was in the [release](https://oss.sonatype.org/content/repositories/releases/com/mapbox/mapboxsdk/mapbox-android-sdk/6.5.0-alpha.2/) repo so changed the build.gradle URL to:

`maven { url "https://oss.sonatype.org/content/repositories/releases" }`

Works for now.

**Comment by LukasPaczos** [comment]
It looks like at this point the `6.5.0-alpha.2` is resolving with no issues, closing.
