### ISSUE TITLE
Annotations sometimes disappear when coming from background

### ISSUE THREAD

**Issue by marcelofabri** [mapbox/mapbox-gl-native#12775]
Sometimes all annotations disappear when coming from background if the app was backgrounded for a while. I think it could be related to #11197 (added on 4.0.0).

Unfortunately, I wasn't able to consistently reproduce it. After I'm in that state, I'm able to "fix" it if I do an action on my app that removes/adds one existing annotation.

### Steps to reproduce

1. Put some annotations on the map
2. Go to background
3. Wait (usually hours/days)
4. Open the app
5. All the annotations are gone from the map. However, I think they're there logically because if I do an action that centers the map into an annotation, it works.

### Expected behavior

The annotations would be displayed on the map.

### Actual behavior

No annotations are visible on the map.

### Configuration

**Mapbox SDK versions:** 4.3.0
**iOS/macOS versions:** 11.4
**Device/simulator models:** iPhone X
**Xcode version:** 9.4

**Comment by tumppikumppi** [comment]
i have exactly the same problem. Is there any solution for this problem?

**Comment by julianrex** [comment]
@tumppikumppi are you using annotation views or images?

**Comment by tumppikumppi** [comment]
Views

**Comment by julianrex** [comment]
@tumppikumppi we do not have a solution yet - we first need to understand what is happening, though suspect a memory warning notification is the trigger.

**Comment by tmatrai** [comment]
Do you have any update on this? I have the same bug with MapBox 6.0.0 IOS SDK.
