### ISSUE TITLE
Release build tombstone with android-v6.5.0-alpha 

### ISSUE THREAD

**Issue by ac87** [mapbox/mapbox-gl-native#12779]
Using either android-v6.5.0-alpha.1 or android-v6.5.0-alpha.2 in a signed proguarded release build tombstones with [this](https://github.com/mapbox/mapbox-gl-native/files/2335558/tombstone.txt).

Disabling proguard fixes it, although I'm not sure why since its not what you'd expect to be a proguard issue.
```
minifyEnabled false
shrinkResources false
```
Tested on 
- Pixel (Android 9)
- Samsung S9 (Android 8)

Using v6.4.0 works fine.

**Comment by tobrun** [comment]
Thank you for the report @ac87 , will be fixed with 6.5.0-beta.1 release happening this week!
