### ISSUE TITLE
Add UI to clear ambient and/or offline cache

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#12781]
This is a follow up to https://github.com/mapbox/mapbox-gl-native/issues/4376 that proposes adding adding API to clear ambient cache.

In addition to that, I propose providing some default UI (that a developer could override if they decided to provide their own functionality) so that users, not only developers, could manually clear their tiles cache. This is useful to reclaim space without having to reinstall their app (iOS and Android) or removing the app's storage (Android).

One possible location for this feature could be a "reset map" option in the popup menu that's shown on both iOS and Android when the user taps the (i) icon on the bottom left.

/cc: @julianrex @tobrun @lilykaiser

**Comment by 1ec5** [comment]
I see that <kbd>macOS</kbd> has been tagged on this issue. For what it’s worth, there is no ℹ️ button on macOS, just an IBAction method on MGLMapView that an application can hook up to a menu item. The SDK has no control over the application’s menus.

**Comment by zugaldia** [comment]
We're still working on this feature.

**Comment by langsmith** [comment]
https://github.com/mapbox/mapbox-gl-native/pull/14365 landed and is the start of our work on increased cache flexibility.

**Comment by zugaldia** [comment]
After internal team conversations, we've decided that the we won't be adding UI directly to the SDK. Instead, we'll build a reference implementation, starting with https://github.com/mapbox/mapbox-android-demo/issues/1015. I suggest we close this ticket accordingly.

**Comment by zugaldia** [comment]
Forgot to add the corresponding iOS ticket: https://github.com/mapbox/ios-sdk-examples/issues/295.
