### ISSUE TITLE
Build Error iOS Swift, preferredFramesPerSecond variable of NavigationMapView

### ISSUE THREAD

**Issue by guuuss** [mapbox/mapbox-gl-native#12782]
Hi,

I just updated to Mapbox-iOS-SDK (4.3.0) and I am now getting these two errors for this field:
fileprivate var preferredFramesPerSecond: Int = 60
The errors:
var must be as accessible as the declaration it overrides,
Property 'preferredFramesPerSecond' with type 'Int' cannot override a property with type 'MGLMapViewPreferredFramesPerSecond'

Not sure if this is just for me, I've tried reintegrating my pod project entirely, removing everything. Deleted derived data as well. Any ideas?

I did sort of fix It for now like this:
override open var preferredFramesPerSecond: NSInteger 
but I highly doubt that is how it's supposed to be

**Comment by 1ec5** [comment]
The next release of the iOS navigation SDK will include mapbox/mapbox-navigation-ios#1608, which ensures compatibility with map SDK v4.3._x_ and above. In the meantime, you can either upgrade to v0.19.1 or above or specify that your application depends on map SDK v4.2.0 and no higher. (The exact syntax depends on whether you’re using CocoaPods or Carthage.)
