### ISSUE TITLE
annotations don't show at z0

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1279]
![anigif-1429157747](https://cloud.githubusercontent.com/assets/17722/7173940/9b1dd138-e3b4-11e4-81e0-2667c7298aba.gif)

**Comment by ljbade** [comment]
Have you decided how you will/will not handle wrap-around of the map?

**Comment by incanus** [comment]
@ljbade I think it's handled automatically since the tiles share the same numbers? We will have some interesting things to tackle when it comes to bounding boxes of features and the like, as always, but for now, rendering works ok?

**Comment by incanus** [comment]
Punting to b2 as non-blocking.

**Comment by incanus** [comment]
Punting again to b3 as non-blocking. We'll be shoring up the annotations framework significantly with things like https://github.com/mapbox/mapbox-gl-native/pull/1694 which will get rid of annotations falling through the cracks at varying zoom levels owing to missing tiles (presumably what's happening here).

**Comment by ansis** [comment]
This is a different issue than https://github.com/mapbox/mapbox-gl-native/issues/1675

It affects all symbol layers at z0, including text layers using the vectortile source.
