### ISSUE TITLE
invalid Map::setLatLngBounds

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#12797]
Copying over an user reported bug:

-------------------------------

**Platform:** Android
**Mapbox SDK version (if applicable):** 6.4.0
### Steps to trigger behavior

`mapboxMap.setLatLngBoundsForCameraTarget(LatLngBounds.from(40, 180.0, -40.0, -180.0));`

### Expected behavior
Camera is restricted to the center of the world vertically, but full navigation horizontally.

### Actual behavior
Only able to pan vertically.
Vertical panning is correctly limited.
Camera is restricted to the IDL for longitude.

This worked correctly in the 5.x baseline.

-----------------------------------------

Running the code provided result in the following output:

![ezgif com-video-to-gif 38](https://user-images.githubusercontent.com/2151639/44982724-21edc600-af77-11e8-8d14-0c2eee32c6b5.gif)

While debugging, `TransformState::setLatLngZoom` shows a constrained LatLng of 0,180 while it shoulld remain 0,0. The issue seems to stem from `LatLngBounds::constrain`

```cpp
    LatLng constrain(const LatLng& p) const {
        if (contains(p)) {
            return p;
        }
        return LatLng {
            util::clamp(p.latitude(), sw.latitude(), ne.latitude()),
            util::clamp(p.longitude(), sw.longitude(), ne.longitude())
        };
    }
```

The` LatLngBounds::contains` invocation return false for WrapMode:Unwrapped:

![image](https://user-images.githubusercontent.com/2151639/44983422-6b3f1500-af79-11e8-8676-14ca144c6aee.png)

**Comment by ryanhamley** [comment]
I think this might actually be an Android bug, not Core. It was introduced [here](https://github.com/mapbox/mapbox-gl-native/pull/11807/files#diff-6645cf705bd2b19cb05a61021d3da93eR20) in the Android v6.1.0 release.  I also think this is basically the same bug as this older ticket? https://github.com/mapbox/mapbox-java/issues/264
