### ISSUE TITLE
Fill style layer partially disappears while zooming

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#12790]
**Platform:** iOS 11
**Mapbox SDK version:** iOS 4.0.0-4.3.0, 4.4.0-alpha.2, perhaps earlier versions.

### Steps to trigger behavior

 1. Run ios-sdk-examples’ [PolygonPatternExample](https://github.com/mapbox/ios-sdk-examples/blob/ad656dd6015e03d29feb26225397d423cd87b8c6/Examples/ObjectiveC/PolygonPatternExample.m), which uses `MGLFillStyleLayer` with a `fillPattern`.
 2. Zoom back/forth from z8 to z9 (or other whole zoom levels).
 3. Half of the layer disappears and then reappears, split on the tile boundary.

### Actual behavior

|  ![](https://user-images.githubusercontent.com/1198851/44936477-e79be300-ad42-11e8-87f6-eb6889d4a628.gif) | <img src=https://user-images.githubusercontent.com/1198851/44936769-08186d00-ad44-11e8-89da-b5a6cd064614.jpeg width=385> |
|---|---|

/cc @jfirebaugh @ChrisLoer

**Comment by ChrisLoer** [comment]
@friedbunny Do you think this is a regression? Also is there an easy way to look at that "drone restrictions" tile set? In the example I just see `mapbox://examples.0cd7imtl` and don't know where to go from that. The first thing I'd want to look at would be to just verify that the polygon actually extends into `9/146/196` in the vector tile source.

@mollymerp Does this ring any bells with any of the tile overdraw stuff you've been looking at?

**Comment by friedbunny** [comment]
@ChrisLoer This bug exists at least as far back as `ios-v4.0.0`, so it’s not a _recent_ regression, at any rate.

I think @captainbarbosa can provide more context re: this dataset.

**Comment by captainbarbosa** [comment]
By using the [map ID](https://www.mapbox.com/help/define-map-id/) I pulled the tileset at the specific tile (`9/146/196`) using the [Maps API](https://www.mapbox.com/api-documentation/#retrieve-tiles): `https://api.mapbox.com/v4/examples.0cd7imtl/9/146/196.png?access_token=<your_access_token_here>`

There seems to be data here:

![196](https://user-images.githubusercontent.com/10850812/45050636-aa7f6b80-b036-11e8-8d80-87bbfcfa48c9.png)

**Comment by ChrisLoer** [comment]
Thanks for the help @captainbarbosa! I played around with this in the debugger and I can reproduce it pretty easily.

When we cross to a higher zoom, we expect to keep showing the (overzoomed) lower zoom version of the tile that contains the patterned polygon, until the tile finishes loading. Just looking at this visually, it seems like we're not rendering the parent tile -- so the polygon flickers out until the higher zoom tile loads a few hundred milliseconds later. My guess would be the update_renderables logic that looks for parent tiles is running up against some edge case where it's up against the bounds of the tileset?

@mollymerp (and @ryanhamley) now this _really_ looks to me like the stuff you've been staring at over the last few weeks. Any chance you could take over investigation?

**Comment by mollymerp** [comment]
yep – are you seeing it actually flicker and load eventually or does that part of the feature never just disappear and never load? 

this could be a bug w the bounds check and not overdraw, but I can look into it
cc @asheemmamoowala

**Comment by mollymerp** [comment]
hmm I can't reproduce this in the glfw app – source maxzoom is 7 and it seems to be correctly retaining the Z7 tiles past that.

**Comment by ChrisLoer** [comment]
> are you seeing it actually flicker and load eventually or does that part of the feature never just disappear and never load?

Running the example in the simulator, I see it load within a fraction of a second without any further viewport change.

> this could be a bug w the bounds check 

Ah yeah, I forgot about that whole set of TileJSON bounds work @asheemmamoowala did...

**Comment by friedbunny** [comment]
> yep – are you seeing it actually flicker and load eventually or does that part of the feature never just disappear and never load?

It eventually loads, after ~500ms. Depending how many zoom levels you traverse, in which direction, and how quickly, different parts of the shape can disappear and reappear at different intervals.

**Comment by asheemmamoowala** [comment]
> It eventually loads, after ~500ms.

This should eliminate TileJSON bounds as a culprit. That code will prevent tiles from being created entirely.

**Comment by mollymerp** [comment]
ok I can reproduce it on glfw app if there are lots of other layers in the style (I originally tried it as a single layer style and couldn't repro the bug)

**Comment by mollymerp** [comment]
interesting – I can only reproduce if the layer is added with runtime styling 🕵️‍♀️

**Comment by captainbarbosa** [comment]
Unsure if this is related, but I'm observing a similar behavior for polygon annotations with a solid fill color going all the way back to v4.0.0. Tracking in https://github.com/mapbox/mapbox-gl-native/issues/12868.

**Comment by mollymerp** [comment]
consolidating this issue with other related ones over at #12981
