### ISSUE TITLE
Optimize for iPad Retina

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#128]
It's running a little slow on iPad retina

Main issues:
- Glyph rendering takes about ~7ms.
- Tile mask generation seems unreasonably slow given that fact that it only draws a couple of triangles. We should assemble a buffer on every frame so we can draw all of these in one go.

Other issues:
- Building polygon density in DC is just ridiculous

**Comment by incanus** [comment]
Bump @kkaefer. Feels fine to me.
