### ISSUE TITLE
Mapbox in recycler only loads once, then crashes when I return to it 

### ISSUE THREAD

**Issue by PieterVenter77** [mapbox/mapbox-gl-native#12802]
I am using kotlin, a recycler view and mapbox. I have mapbox as one of the items in my recycler, when I scroll to mapbox in the recycler, after a bit of waiting it will load, then when i scroll up and go back to the mapbox item, it will crash entirely, very similar to the issue in #12731, however even when downgrading to 6.3.0 it does not solve my problem. 

### Steps to reproduce

 1. Create a recycler view with mapbox as one of the items and some other items as well
 2. Scroll to the mapbox item
 3. Scroll away from the item so it goes out of focus, then scroll to it again

### Expected behavior
Loads every time

### Actual behavior
Crashes, only loads once

### Configuration

**Android versions:** 22,23,24
**Device models:** Any
**Mapbox SDK versions:** 6.3, 6.4

**Comment by LukasPaczos** [comment]
Thanks for reaching out @PieterVenter77! Would you be able to add the stack-trace, or the error message? A minimal reproducible example would be great as well.

**Comment by PieterVenter77** [comment]
Hi, I’ve managed to improve it by implementing onMapReadyCallback in my recycler, you can close the issue, sorry : )

**Comment by LukasPaczos** [comment]
Great to hear that your issue has been resolved @PieterVenter77!
