### ISSUE TITLE
Crashing issue

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-gl-native#12805]
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x58 in tid 9327 (FinalizerDaemon)

Once I updated the sdk 6.4.0.

Anyone know what is the issue?

**Comment by LukasPaczos** [comment]
Hi @mf-mindcrewtech, thanks for using our products! When opening a ticket please try to elaborate on the issue, provide stack-traces, code snippets or ideally a minimal reproducible example.
