### ISSUE TITLE
Runtime crashing on Map

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-gl-native#12800]
A/libc: /buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type jni::PendingJavaException" failed

My added libraries ::

implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.4.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.7.1'
implementation 'com.mapbox.mapboxsdk:mapbox-android-services:2.3.0-SNAPSHOT'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-building:0.1.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.18.0'
implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places:0.2.1'
implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.18.0') {
transitive = true
}

Can anyone please let me know, what version is stable?

**Comment by Guardiola31337** [comment]
Duplicated of https://github.com/mapbox/mapbox-navigation-android/issues/1254

Closing as answered in ☝️
