### ISSUE TITLE
Incorrect error message in LatLngBounds.java

### ISSUE THREAD

**Issue by clydebarrow** [mapbox/mapbox-gl-native#12815]
In file com/mapbox/mapboxsdk/geometry/LatLngBounds.java, line 334, the error message is the wrong way around:
````
    if (latNorth < latSouth) {
      throw new IllegalArgumentException("LatSouth cannot be less than latNorth");
    }
 ````

**Mapbox SDK versions:** 6.4.0

**Comment by tobrun** [comment]
great catch, will fix this up
