### ISSUE TITLE
Sources hosted on localhost still need network connection.

### ISSUE THREAD

**Issue by kptlronyttcna** [mapbox/mapbox-gl-native#12819]
### Steps to reproduce

 1. Host a vector tile according to [this](https://gist.github.com/typebrook/7d25be326f0e9afd58e0bbc333d2a175).
 2. Not be connected to a network

### Expected behavior
See the vector tiles without network connection.

### Actual behavior
No tiles is shown.

### Configuration
Mapbox SDK versions: 6.5.0-alpha.1

**Comment by tobrun** [comment]
This was working with older versions of the SDK and thus a regression?

**Comment by kptlronyttcna** [comment]
No, it did not work with older versions either.

**Comment by tobrun** [comment]
You can call `Mapbox#setConnected(true)` to override system connectivity state changes. 
This should solve your use-case.
