### ISSUE TITLE
styleWillLoad delegate/callback Request

### ISSUE THREAD

**Issue by akac** [mapbox/mapbox-gl-native#12824]
Style changes - either through setStyleURL or through automatic style reloads - will lose programmatically added/customized layers, attributes. This is expected, but if we have a data stream that is live updating data we would like to know when the style is about to be loaded/reloaded so we can pause the data stream or any other work we are doing with the layers until the time that map has finished loading with the style. We sometimes also want to save the state of a layer or grab information from it before it goes away.

Current delegate methods get called _after_ the style is set to nil - we would like a "will" callback that is called before the style is set to nil.

**Platform:**
iOS or Android
**Mapbox SDK version:**
4.x/6.x

### Steps to trigger behavior

 1. Load a style
 2. Create a thread that updates layer data in realtime streaming from an endpoint
 3. Reload the style

### Expected behavior
Get a callback that the style is about to go away. 

### Actual behavior
Get a callback after the style has already been set to nil.

**Comment by kkaefer** [comment]
Also see https://github.com/mapbox/mapbox-gl-native/issues/6180
