### ISSUE TITLE
Add an option to restore per-source collision detection

### ISSUE THREAD

**Issue by lilykaiser** [mapbox/mapbox-gl-native#12820]
Implement the equivalent of https://github.com/mapbox/mapbox-gl-js/pull/6566 in gl-native

Add an option to restore collision detection behavior from before cross-source collision detection (https://github.com/mapbox/mapbox-gl-native/pull/10436)

**Comment by 1ec5** [comment]
Just a reminder that point annotations should never be hidden due to symbols in other sources, regardless of the option that would be introduced for this issue. Otherwise, we’ll regress #10845.

**Comment by ChrisLoer** [comment]
I don't _think_ this will have anything to do with #10845, since point annotations use `"icon-allow-overlap": true` under the hood. At any rate, if people change this option from the default, the result is to show _more_ symbols, not fewer.

**Comment by ChrisLoer** [comment]
Fixed in Node and Android with #12842.  iOS is ticketed at https://github.com/mapbox/mapbox-gl-native/issues/12847.
