### ISSUE TITLE
Offline Tiles Downloading [Pause/Resume]

### ISSUE THREAD

**Issue by Ami-Patel** [mapbox/mapbox-gl-native#12831]
Hello,

I am managing resume and cancel tiles downloading feature.
To Cancel(Pause), I am using below line
  offlineRegion.setDownloadState(OfflineRegion.STATE_INACTIVE);

To Resume, I am using below line
 offlineRegion.setDownloadState(OfflineRegion.STATE_ACTIVE);

But sometimes i am facing crash. 
Here is crash details which i got it on logcat

 {DefaultFileSour}[Database](6410): statement aborts at 37: [UPDATE resources SET kind            = ?1,     etag            = ?2,     expires         = ?3,     must_revalidate = ?4,     modified        = ?5,     accessed        = ?6,     data   
com.android A/libc: /buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type mapbox::sqlite::Exception: disk I/O error" failed

Steps to reproduce
You can reproduce it by doing pause and resume multiple  times.

Below is Configuration
Android versions: 7.1.1 
Device models: Moto g5 
Mapbox SDK versions: 6.4.0 

Would you please help me to fix it?

**Comment by kkaefer** [comment]
Thank you for reporting this issue. We fixed it in https://github.com/mapbox/mapbox-gl-native/pull/12224, which will be part of the upcoming release this month.
