### ISSUE TITLE
Map hangs after tile count limit exceeded when downloading offline map

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#12833]
### Steps to reproduce

 1. Select a large region for offline download
 2. Download region
 3. When tile limit exceeds, and panning to another region, a grey underground is visible (map doesn't load anymore)
4. Below my code when limit exceeds. 

```
@Override
public void mapboxTileCountLimitExceeded(long limit) {
 // Notify if offline region exceeds maximum tile count
Log.e("offline_download_error", "Mapbox tile count limit exceeded: " + limit);
offlineRegion.setDownloadState(OfflineRegion.STATE_INACTIVE);

}
```

### Expected behavior

Map is visible when panning after limit exceeds.

### Actual behavior

Map is stuck: when panning to another region, no map is visible anymore. Only way to make it work again is to restart app. 

### Configuration

**Android versions:*8.1* 
**Device models:*Noka 7 Plus* 
**Mapbox SDK versions:*6.4.0*

**Comment by tobrun** [comment]
This is fixed with https://github.com/mapbox/mapbox-gl-native/issues/12655
