### ISSUE TITLE
need a simple method to show hide marker for android sdk 

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-gl-native#12849]
Showing and hiding markers available in many ssdk like google heremaps etc
also we can achieve it with mapbox ios sdk.

That is just a simple thing also we cant find zindex future for markers too.

**Comment by LukasPaczos** [comment]
Hey @Xgamefactory, thanks for using our products!

You can remove all of the markers from the map by iterating through a list obtained with
```
mapboxMap.getMarkers()
```

There is no concept of z-indexing for annotations. To achieve that you will have to use the [`SymbolLayer` API](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-symbol).

For future reference, this repository is for bugs and feature requests only. For other questions head to https://www.mapbox.com/help/ or https://stackoverflow.com/questions/tagged/mapbox.

**Comment by Xgamefactory** [comment]
Thanks for reply but i want hiding marker not removing this is a feature request very simple though and this feature have many sdks including mapbox ios sdk as i mentioned before.
