### ISSUE TITLE
Fails to download offline map on Android (fatal signal 6 GC crash)

### ISSUE THREAD

**Issue by evbarnett** [mapbox/mapbox-gl-native#12848]
Running mapbox 6.4.0 on an Samsung S8, API 26

Using the code from the [tutorial](https://www.mapbox.com/android-docs/maps/overview/offline/)-

The download starts fine, printing out a line like this every few seconds (related to the GC):

```
09-07 17:03:59.681 653-664/my.app I/zygote64: Background concurrent copying GC freed 56227(3MB) AllocSpace objects, 41(2MB) LOS objects, 70% free, 2MB/8MB, paused 338us total 253.259ms
```

After that for a while, it crashes with the following error (this is the complete error message):

```
09-07 17:05:25.879 653-1419/my.app A/zygote64: concurrent_copying.cc:1014] Check failed: self == thread_running_gc_ Only GC-running thread should access the mark stack in the GC exclusive mark stack mode
    runtime.cc:516] Runtime aborting...
    runtime.cc:516] 
09-07 17:05:25.880 653-1419/my.app A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 1419 (.mapbox.com/...)
```

If I reload the app and use the map with the partially downloaded tiles, every time I touch the map is prints

```
09-07 16:58:35.963 29052-29150/my.app E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE)
```

Thank you,

**Comment by evbarnett** [comment]
More information: I was able to download a bound of ~300 tiles without error. The error was originally occurring 10-20% of the way through a larger download (3-4k tiles). The ```JVMTI_ERROR_THREAD_NOT_ALIVE``` error messages occurs always, no matter if the download was successful or not.

**Comment by zugaldia** [comment]
@evbarnett thank you for the feedback - could you run your tests again with the latest version of the SDK? We've recently shipped large changes that improve the stability of our offline DB https://github.com/mapbox/mapbox-gl-native/pull/12224 (among other offline improvements) and I'd like to see if those changes help here. These are API-compatible changes so you shouldn't need to make any changes to your app code.
