### ISSUE TITLE
how to make mapbox digital style

### ISSUE THREAD

**Issue by fukemy** [mapbox/mapbox-gl-native#12851]
Hello. Im new in mapbox development. 

Can somebody help me how to make map style like that: 
<img width="776" alt="screen shot 2018-09-10 at 16 30 11" src="https://user-images.githubusercontent.com/8202437/45293737-399eee80-b523-11e8-9785-47838b0c2f1a.png">

**Comment by LukasPaczos** [comment]
Hi @fukemy, thanks for using Mapbox services! This repository is for bug reports and feature requests only. For support questions head to https://www.mapbox.com/help/ or https://stackoverflow.com/questions/tagged/mapbox.
