### ISSUE TITLE
Qt/Qml support

### ISSUE THREAD

**Issue by marco-piccolino** [mapbox/mapbox-gl-native#1286]
Hello guys, thanks for an awesome lib!

As you might know, Qt/Qml has now become a first-class solution to develop native apps on mobile.
The mapping front is becoming thus increasingly important, so that in the new Qt 5.5 release they are including support for Mapbox tiles (http://doc-snapshots.qt.io/qt5-5.5/location-plugin-mapbox.html), alongside OSM and Here (formerly Nokia).

Now Esri has understood this and they have just released the new Arcgis Runtime SDK for Qt, which sports a lot of awesome features (https://developers.arcgis.com/qt/).

Given that Mapbox GL is written in C++, creating a Qt plugin is very possible and, IMHO, strategically very important for Mapbox. It should come with a few features that are currently missing in QtLocation, such as support for offline data. Just give it a thought and, well, act accordingly!

**Comment by springmeyer** [comment]
Hi @marco-piccolino - Thanks for saying hello and letting us know about your interest. We are focused on iOS and Android and overall performance now, but once the API becomes more stable it should be feasible for anyone to integrate mbgl-native into a Qt app. If this is something you are planning on working on we'd love to hear updates of your progress. I'll close this ticket now, but feel free to comment back with updates.

**Comment by marco-piccolino** [comment]
Hello Dane, thanks for the feedback.
I gather that Qt/Qml support is not a priority for you guys right now. However, please consider it for the near future as it could make the Mapbox ecosystem stand out on this awesome and fast-growing cross-platform framework. I currently do not have enough skills to tackle the task. Let's see if I can gather some more interest around it. Keep up the good work!

**Comment by springmeyer** [comment]
Sounds good Marco!

**Comment by tmpsantos** [comment]
@marco-piccolino I think you might like this: https://github.com/tmpsantos/qmapboxgl

![screenshot from 2015-05-31 23 18 12](https://cloud.githubusercontent.com/assets/996307/7911050/77eed1bc-0862-11e5-9087-2731cc8b6f5c.png)

**Comment by marco-piccolino** [comment]
Brilliant! Yes I do indeed... :-) Any plans for a qml interface?

**Comment by tmpsantos** [comment]
> Brilliant! Yes I do indeed... :-) Any plans for a qml interface?

I will give it a shot at the next cloudy/rainy weekend. :)

**Comment by marco-piccolino** [comment]
that's really awesome - if you need any kind of input please do let me know
