### ISSUE TITLE
Need help with others sources

### ISSUE THREAD

**Issue by H4wak** [mapbox/mapbox-gl-native#1287]
Hi i'm in a student's training course and i have to explore MapBox GL. I'm a beginner with theses technologies but i try to do my best ! I want to use MapBox GL with a map created with MapBox Studio, so i uploaded my map to MapBox and have the MapID. I modified the "satellite-v7.json" like that : "satellite": {
      "type": "raster",
      "url": "mapbox://mapbox.satellite",
      "tileSize": 256
    },
changed to :
 "satellite": {
      "type": "raster",
      "url": "mapbox://hawak.14a1a038",  <--- the MapID
      "tileSize": 256
    }, 
Then I load that style and it's work nice but i want to have a vector map not a raster type. I tried little things but i have somme issues and i don't know why. Someone have any solutions ? Thanks !

**Comment by friedbunny** [comment]
Hi @H4wak, welcome to the the insanely fun world of online map-making! If you're looking for a good place to start with Mapbox GL right now, I'd suggest looking at the [JavaScript/web version](https://github.com/mapbox/mapbox-gl-js/). (This repo is for the native iOS, Android, etc. versions and isn't quite ready for everyone to use yet.)

As for your raster/vector problem, I don't think Mapbox Studio can make styled maps that will work as GL vectors. To make a base map (roads, buildings, and so on) you'll have to style it manually [using JSON properties](https://www.mapbox.com/mapbox-gl-style-spec/) — try looking at [basic-v7.json](https://github.com/mapbox/mapbox-gl-styles/blob/mb-pages/styles/basic-v7.json) to start.

For a great general overview of digital maps and their terminology, definitely check out [mapschool](http://mapschool.io/).

**Comment by H4wak** [comment]
Hi @friedbunny, thank you for your nice response !! :+1: I'm gonna check that Web version before, and thank your for this mapschool link. It's clear and easy to read ! (even for a French student ;) )

Have a nice day.

**Comment by H4wak** [comment]
Hi @friedbunny, i looked at the JavaScript/web version but that's not what i want. I have to work with vector maps only ! So I have a question : How can I create vector maps and use them with GL ?

**Comment by jfirebaugh** [comment]
@H4wak [Mapbox GL JS](https://www.mapbox.com/mapbox-gl-js/) is vector based, just as GL Native is.

**Comment by H4wak** [comment]
@jfirebaugh GL JS isn't that I want because I have to work with the native version, not with the Web version. Sorry for the misunderstanding.
