### ISSUE TITLE
Annotation should have a String UUID instead of long id to avoid collision

### ISSUE THREAD

**Issue by ben-j69** [mapbox/mapbox-gl-native#12872]
Currently Annotation have a long ID.
If you add several Annotation on the map mixing for example Markers and Ploygon it can happen that a Marker and a Polygon have the same id. Then it will generate the error 
`com.mapbox.mapboxsdk.annotations.Polygon cannot be cast to com.mapbox.mapboxsdk.annotations.Marker`

### Steps to reproduce

 1. Add several Annotation of different type from diferents threads.

### Expected behavior
If the Annotation model had an UUID String there will be no collision on ids and this error will not occur.

### Configuration

**Android versions:All
**Device models:All
**Mapbox SDK versions:5.5.3 (Can't test on newer version since the bug of BinderProxy is breaking everything)

**Comment by tobrun** [comment]
Annotations have been deprecated and will be replaced with [annotations plugin](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-annotation).
