### ISSUE TITLE
showAnnotations isn't zooming correctly when I call setContentInset

### ISSUE THREAD

**Issue by the4thfloor** [mapbox/mapbox-gl-native#12874]
I use `func showAnnotations(_ annotations: [MGLAnnotation], animated: Bool)` to show all added annotations. It works fine, all annotations are visible, and the zoom level is perfect.

But when I call `func setContentInset(_ contentInset: UIEdgeInsets, animated: Bool)` to decrease the viewport, the zoom level of showAnnotations is not perfect. All annotations are in the middle of the map at one point, MapBox doesn’t use the available screen / viewport completely. I get the same result when I change the order of both calls.

### Steps to reproduce

 1. call `showAnnotations(...)`
 2. call `setContentInset(...)`

### Expected behavior

All annotations fit into the available viewport.

### Actual behavior

All annotations are in the middle of the viewport.

### Configuration

**Mapbox SDK versions:** 4.3.0
**iOS/macOS versions:** 11.4
**Device/simulator models:** iPhone SE
**Xcode version:** 9.4.1

without `setContentInset(...)`:
![screen shot 2018-08-14 at 16 26 12](https://user-images.githubusercontent.com/1191649/45417291-1b9bd000-b682-11e8-9b91-6b3b2a5a220a.png)

with `setContentInset(...)`:
![screen shot 2018-08-14 at 16 26 46](https://user-images.githubusercontent.com/1191649/45417316-27879200-b682-11e8-81b5-f973e394253e.png)

**Comment by fabian-guerra** [comment]
Hi @the4thfloor. Thank you for using Mapbox. The behavior you are seen is the expected as there is a logical viewport change. Have you tried with:
```
showAnnotations([MGLAnnotation], edgePadding: UIEdgeInsets, animated: Bool)
``` 

This will allow displaying the annotations and increase/decrease the padding.
