### ISSUE TITLE
NPM install failed with Qt

### ISSUE THREAD

**Issue by lonnibesancon** [mapbox/mapbox-gl-native#12886]
Hello everyone

I am trying to install mapbox-gl-native to use with Qt on my Mac.

**Platform: Mac OS**
**Mapbox SDK version: downloaded from master branch**
**node version: v10.8.0**

### Steps to trigger behavior

 1. I downloaded mapbox-gl-native from the repo
 2. I installed qt5 with homebrew
 3. I used the command: "make qt-lib" as suggested on the wiki

### Expected behavior
Installation successful

### Actual behavior
Installation failed with "NPM install failed"

Complete output is: 

`make qt-lib
mkdir -p build/qt-macos-x86_64/Debug
(cd build/qt-macos-x86_64/Debug && cmake -G Ninja ../../.. \
		-DCMAKE_BUILD_TYPE=Debug \
		-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
		-DMBGL_PLATFORM=qt \
		-DMASON_PLATFORM= \
		-DMASON_PLATFORM_VERSION= \
		-DWITH_QT_DECODERS= \
		-DWITH_QT_I18N= \
		-DWITH_QT_4=0 \
		-DWITH_CXX11ABI=OFF \
		-DWITH_COVERAGE=)
-- Updating submodules...
fatal: not a git repository (or any of the parent directories): .git
-- Running 'npm install' for mapbox-gl-js...
-- Finished 'npm install' for mapbox-gl-js...
CMake Error at cmake/mbgl.cmake:54 (message):
  NPM install failed:

Call Stack (most recent call first):
  cmake/mbgl.cmake:97 (_npm_install)
  CMakeLists.txt:11 (include)

-- Configuring incomplete, errors occurred!
See also "/Users/lonbe19/Downloads/mapbox-gl-native-master/build/qt-macos-x86_64/Debug/CMakeFiles/CMakeOutput.log".
make: *** [build/qt-macos-x86_64/Debug/build.ninja] Error 1`

Would anyone know what is wrong here?

**Comment by lonnibesancon** [comment]
Up?

**Comment by kkaefer** [comment]
It's hard to tell what from this log, but likely it's an npm timeout. Please check the NPM log files to see what went wrong there.

**Comment by dgccom** [comment]
@kkaefer hello！ I get the same error with logs！

Detecting CXX compiler ABI info failed to compile with the following output:
Change Dir: /Users/mac/Documents/mapbox-gl-native-ios-v4.4.1/build/ios/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/xcodebuild" "-project" "CMAKE_TRY_COMPILE.xcodeproj" "build" "-target" "cmTC_44550" "-configuration" "Debug"
=== BUILD TARGET cmTC_44550 OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===

Check dependencies
target specifies product type 'com.apple.product-type.tool', but there's no such product type for the 'iphoneos' platform

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

**Comment by lonnibesancon** [comment]
@kkaefer 

I tried using verbose mode for npm (as suggested [here](https://stackoverflow.com/questions/39412424/how-to-see-logs-from-npm-installation) for instance but) I don't get any other info. How else would you check the log for npm?

@dgccom I believe that this is a completely different error. Your build is failing but it's not an npm issue.

**Comment by kkaefer** [comment]
I debugged this a little further and it seems that the failure you're seeing is connected to a missing `mapbox-gl-js` checkout. In order to built, we use [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js) as a git submodule. It seems that you downloaded the source code as a zip file rather than using a git checkout. To fix this error, please use a git checkout.

**Comment by dgccom** [comment]
@kkaefer I don't download mapbox-gl-js，it automatic checkout with “make iproj”！

**Comment by lonnibesancon** [comment]
@kkaefer indeed that was the problem. I believe that the document on the building process should mentioned that somewhere. Perhaps I missed it, but in this case having it on each individual "how-to-build" would probably be nice. Thanks for the help.

@dgccom I believe that this is a completely different error, absolutely unrelated to that issue.

**Comment by dgccom** [comment]
@kkaefer I fix this error，the reason is that  "mapbox-gl-js" dwonload error，I checkout "mapbox-gl-js" and copy into "mapbox-gl-native-ios-4.4.1",it build successful。Thanks！！！

@lonnibesancon I hope this will help you！
