### ISSUE TITLE
rendering error with style peterqliu.bf9a8d40

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-native#1288]
This map style doesn't render correctly. Background is all black. The significant change between this version and earlier versions is that it uses the `background-image` property. See the style here: https://api.tiles.mapbox.com/styles/v1/peterqliu/peterqliu.bf9a8d40?access_token=pk.eyJ1IjoicGV0ZXJxbGl1IiwiYSI6ImpvZmV0UEEifQ._D4bRmVcGfJvo1wjuOpA1g

**Comment by peterqliu** [comment]
-> https://github.com/mapbox/gl-internal/issues/138

**Comment by 1ec5** [comment]
No longer seeing this issue in [a newer Emerald](https://www.mapbox.com/bites/00116/?style=peterqliu.9e140828&access_token=pk.eyJ1IjoicGV0ZXJxbGl1IiwiYSI6ImpvZmV0UEEifQ._D4bRmVcGfJvo1wjuOpA1g#9.31/41.5826/-79.1234) – what changed?

**Comment by 1ec5** [comment]
Haven’t seen this issue with Emerald for quite some time.
