### ISSUE TITLE
Wrong position of attribution dialog after rotation on iPad

### ISSUE THREAD

**Issue by kbauhaus** [mapbox/mapbox-gl-native#12897]
### Steps to reproduce

 1. initialize a new MGLMapView and add it to the viewcontroller 
 2. tap on the attribution information icon 
 3. then rotate the ipad
 4. observe callout placement

### Expected behavior

The callout/dialog popup should resize to be on top of the `i` still

### Actual behavior

The callout doesn't resize to be on top of the `i`.

<img width="1109" alt="screenshot 2018-09-14 16 13 44" src="https://user-images.githubusercontent.com/11279680/45579454-7ed16200-b83c-11e8-81ec-8a6573c83d40.png">

### Configuration

**Mapbox SDK versions:**  ios sdk versions 3.7.4 and 4.3
**iOS/macOS versions:** 11.4
**Device/simulator models:** iPhone 7 sim
**Xcode version:**  Xcode 9.4.1

cc @captainbarbosa

**Comment by friedbunny** [comment]
Note that this only affects iPad — on iPhone, the action sheet is presented modally and fills the screen.

**Comment by zxlee618** [comment]
Is anyone working on this? Can I try to fix the bug?

**Comment by friedbunny** [comment]
Go for it, @zxlee618 — we’re always happy to review pull requests. 🙇

**Comment by zxlee618** [comment]
Hi @friedbunny I don't seem to be able to request for reviews in the pull request 😶

**Comment by julianrex** [comment]
Hi @zxlee618 - I've requested reviews on your behalf - not sure why you couldn't.

**Comment by zxlee618** [comment]
👍
