### ISSUE TITLE
Cannot update Podfiles since 4.4.1 release

### ISSUE THREAD

**Issue by yoowinks** [mapbox/mapbox-gl-native#12900]
Hi, first off, apologies if this is posted in the wrong section.

I am going through the Mapbox examples and for each example I create a new project (installing Mapbox via Cocoapods). This means creating a new pod file. Prior to when 4.4.1 was released, I could enter the following in my Podfile and the `pod update` would run successfully: 

<img width="848" alt="screen shot 2018-09-14 at 10 11 34 pm" src="https://user-images.githubusercontent.com/33309141/45581826-2b2a3d00-b86b-11e8-81e1-11cd332aef12.png">

Now when I add that line to a new Mapbox example project, in Terminal the update appears to hang at `Installing Mapbox-iOS-SDK (4.4.1)` and then produces an error:

<img width="1116" alt="screen shot 2018-09-14 at 10 06 50 pm" src="https://user-images.githubusercontent.com/33309141/45581841-5dd43580-b86b-11e8-8366-e8d33115cad2.png">

Is there something I am doing wrong? I have Googled this but to no avail. Hoping someone can shed some light.

Thank you!

**Comment by captainbarbosa** [comment]
Hi @yoowinks - I was able to install the SDK with the same Podfile syntax you noted. Are you still running into this issue?

**Comment by yoowinks** [comment]
Hi @captainbarbosa - thank you for getting back to me so quickly. It appears to be working now under a different public connection. The one I was using yesterday and last week from the same location repeatedly failed, which is why I thought it was something I was doing.

I appreciate your confirmation that the install works fine.
