### ISSUE TITLE
Every ios-release CI build on master uploads “nightly” release

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#12906]
CircleCI doesn’t offer an easy way to know if a build is a nightly or otherwise triggered by a cronjob, so the `ios-release` build checks for the non-existence of a comparison URL and if the build is happening on `master`.

https://github.com/mapbox/mapbox-gl-native/blob/f3efa628c00b1141332d11dd27de5a19f8a8d22a/circle.yml#L1060-L1065

This turns out to also trigger when a PR is merged to `master`, so our “nightly” build is effectively more of a “snapshot” of the current state of `master`. This isn’t a huge issue (the upload only takes ~30 seconds), but it is unexpected for a “nightly” to change throughout the day.

/cc @mapbox/maps-ios

**Comment by LukasPaczos** [comment]
Correct, we are publishing `snapshot` builds with every push to `master` or a release branch.
