### ISSUE TITLE
SDK crashes in sstream

### ISSUE THREAD

**Issue by msh91** [mapbox/mapbox-gl-native#12901]
We have an issue only on Huawei p6 with Android 4.2.2
Mapbox version: 6.4.0

Here is the last crash report generated by Fabric Crashlytics native report:
Platform: android
Date: 2018-09-15T19:15:00Z
OS Version: 4.2.2
Device: HUAWEI P6
RAM Free: 7.4%
Disk Free: 10.4%

0. Crashed: Thread
0  libGAL.so                      0x5c7daf88 (Missing)
1  libGAL.so                      0x5c7e4f63 (Missing)
2  libGLESv2_VIVANTE.so           0x5c7f55ed (Missing)
3  libGLESv2_VIVANTE.so           0x5c7fb429 (Missing)
4  libmapbox-gl.so                0x5f711cdd (Missing)
5  libmapbox-gl.so                0x5f6a66fe mbgl::util::readFile(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&) (sstream:246)
6  libmapbox-gl.so                0x5f85dcbb std::__ndk1::num_put<char, std::__ndk1::ostreambuf_iterator<char, std::__ndk1::char_traits<char> > >::do_put(std::__ndk1::ostreambuf_iterator<char, std::__ndk1::char_traits<char> >, std::__ndk1::ios_base&, char, unsigned long) const (locale:1524)
7  libmapbox-gl.so                0x5f5a1859 std::__ndk1::basic_streambuf<char, std::__ndk1::char_traits<char> >::xsputn(char const*, int) (__string:225)
8  libmapbox-gl.so                0x5f900057 (Missing)
9  libc.so                        0x40123581 (Missing)
10 libmapbox-gl.so                0x5f900055 (Missing)
11 libc.so                        0x4011f0d3 (Missing)
12 libc.so                        0x4012a0a4 (Missing)
13 libbinder.so                   0x4020de8f (Missing)
14 libbinder.so                   0x4020b269 (Missing)
15 libbinder.so                   0x4020dd89 (Missing)
16 libbinder.so                   0x4020f695 (Missing)
17 libc.so                        0x401239d1 (Missing)
18 libc.so                        0x4011f0d3 (Missing)
19 libbinder.so                   0x4020dbdf (Missing)
20 libbinder.so                   0x4020dc4d (Missing)
21 libbinder.so                   0x402089c7 (Missing)
22 libgui.so                      0x404e2749 (Missing)
23 (Missing)                      0x4137994e (Missing)
24 (Missing)                      0x4100ffff (Missing)
25 libc.so                        0x4014dcb6 (Missing)
26 libutils.so                    0x401d8d53 (Missing)
27 libandroid_runtime.so          0x40276e45 (Missing)
28 (Missing)                      0x56be2866 (Missing)
29 libdvm.so                      0x407da452 (Missing)
30 (Missing)                      0x41ea295e (Missing)
31 libdvm.so                      0x408095d3 (Missing)
32 (Missing)                      0x5882f1a0 (Missing)
33 libandroid_runtime.so          0x40276e61 (Missing)
34 libdvm.so                      0x4082ed95 (Missing)
35 libdvm.so                      0x40834901 (Missing)
36 (Missing)                      0x41e94006 (Missing)
37 (Missing)                      0x41e94006 (Missing)
38 libdvm.so                      0x407da5be (Missing)
39 (Missing)                      0x40eff75e (Missing)
40 (Missing)                      0x420f6096 (Missing)
41 (Missing)                      0x41ea295e (Missing)
42 (Missing)                      0x41ea2962 (Missing)
43 libdvm.so                      0x4080e6c7 (Missing)
44 (Missing)                      0x58529f84 (Missing)
45 (Missing)                      0x413cab2e (Missing)
46 libdvm.so                      0x407da5be (Missing)
47 libdvm.so                      0x407e3862 (Missing)
48 (Missing)                      0x56bf1ef6 (Missing)
49 (Missing)                      0x41ea1752 (Missing)
50 libdvm.so                      0x407e773e (Missing)
51 (Missing)                      0x583f5476 (Missing)
52 (Missing)                      0x56b5f2a6 (Missing)
53 (Missing)                      0x40ee6ffe (Missing)
54 (Missing)                      0x41ea15ce (Missing)
55 (Missing)                      0x56bf1ef6 (Missing)
56 (Missing)                      0x41ea1752 (Missing)
57 libdvm.so                      0x4081c355 (Missing)
58 (Missing)                      0x56bf1ef6 (Missing)
59 (Missing)                      0x413782a6 (Missing)
60 (Missing)                      0x41ea1576 (Missing)
61 (Missing)                      0x41ea173e (Missing)

--

#0. Crashed: Thread
0  libGAL.so                      0x5c7daf88 (Missing)
1  libGAL.so                      0x5c7e4f63 (Missing)
2  libGLESv2_VIVANTE.so           0x5c7f55ed (Missing)
3  libGLESv2_VIVANTE.so           0x5c7fb429 (Missing)
4  libmapbox-gl.so                0x5f711cdd (Missing)
5  libmapbox-gl.so                0x5f6a66fe mbgl::util::readFile(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&) (sstream:246)
6  libmapbox-gl.so                0x5f85dcbb std::__ndk1::num_put<char, std::__ndk1::ostreambuf_iterator<char, std::__ndk1::char_traits<char> > >::do_put(std::__ndk1::ostreambuf_iterator<char, std::__ndk1::char_traits<char> >, std::__ndk1::ios_base&, char, unsigned long) const (locale:1524)
7  libmapbox-gl.so                0x5f5a1859 std::__ndk1::basic_streambuf<char, std::__ndk1::char_traits<char> >::xsputn(char const*, int) (__string:225)
8  libmapbox-gl.so                0x5f900057 (Missing)
9  libc.so                        0x40123581 (Missing)
10 libmapbox-gl.so                0x5f900055 (Missing)
11 libc.so                        0x4011f0d3 (Missing)
12 libc.so                        0x4012a0a4 (Missing)
13 libbinder.so                   0x4020de8f (Missing)
14 libbinder.so                   0x4020b269 (Missing)
15 libbinder.so                   0x4020dd89 (Missing)
16 libbinder.so                   0x4020f695 (Missing)
17 libc.so                        0x401239d1 (Missing)
18 libc.so                        0x4011f0d3 (Missing)
19 libbinder.so                   0x4020dbdf (Missing)
20 libbinder.so                   0x4020dc4d (Missing)
21 libbinder.so                   0x402089c7 (Missing)
22 libgui.so                      0x404e2749 (Missing)
23 (Missing)                      0x4137994e (Missing)
24 (Missing)                      0x4100ffff (Missing)
25 libc.so                        0x4014dcb6 (Missing)
26 libutils.so                    0x401d8d53 (Missing)
27 libandroid_runtime.so          0x40276e45 (Missing)
28 (Missing)                      0x56be2866 (Missing)
29 libdvm.so                      0x407da452 (Missing)
30 (Missing)                      0x41ea295e (Missing)
31 libdvm.so                      0x408095d3 (Missing)
32 (Missing)                      0x5882f1a0 (Missing)
33 libandroid_runtime.so          0x40276e61 (Missing)
34 libdvm.so                      0x4082ed95 (Missing)
35 libdvm.so                      0x40834901 (Missing)
36 (Missing)                      0x41e94006 (Missing)
37 (Missing)                      0x41e94006 (Missing)
38 libdvm.so                      0x407da5be (Missing)
39 (Missing)                      0x40eff75e (Missing)
40 (Missing)                      0x420f6096 (Missing)
41 (Missing)                      0x41ea295e (Missing)
42 (Missing)                      0x41ea2962 (Missing)
43 libdvm.so                      0x4080e6c7 (Missing)
44 (Missing)                      0x58529f84 (Missing)
45 (Missing)                      0x413cab2e (Missing)
46 libdvm.so                      0x407da5be (Missing)
47 libdvm.so                      0x407e3862 (Missing)
48 (Missing)                      0x56bf1ef6 (Missing)
49 (Missing)                      0x41ea1752 (Missing)
50 libdvm.so                      0x407e773e (Missing)
51 (Missing)                      0x583f5476 (Missing)
52 (Missing)                      0x56b5f2a6 (Missing)
53 (Missing)                      0x40ee6ffe (Missing)
54 (Missing)                      0x41ea15ce (Missing)
55 (Missing)                      0x56bf1ef6 (Missing)
56 (Missing)                      0x41ea1752 (Missing)
57 libdvm.so                      0x4081c355 (Missing)
58 (Missing)                      0x56bf1ef6 (Missing)
59 (Missing)                      0x413782a6 (Missing)
60 (Missing)                      0x41ea1576 (Missing)
61 (Missing)                      0x41ea173e (Missing)

**Comment by tobrun** [comment]
Thanks for the report @msh91, sad to hear that our SDK is crashing for you. Without an actual stacktrace that we can symbolicate or any steps to reproduce the crash, this issue is allmost impossible to look into. 

A valid stacktrace will look something as:

```
I/DEBUG   (   31): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (   31): Build fingerprint: 'generic/google_sdk/generic/:2.2/FRF91/43546:eng/test-keys'
I/DEBUG   (   31): pid: 351, tid: 351  >>> /data/local/ndk-tests/crasher <<<
I/DEBUG   (   31): signal 11 (SIGSEGV), fault addr 0d9f00d8
I/DEBUG   (   31):  r0 0000af88  r1 0000a008  r2 baadf00d  r3 0d9f00d8
I/DEBUG   (   31):  r4 00000004  r5 0000a008  r6 0000af88  r7 00013c44
I/DEBUG   (   31):  r8 00000000  r9 00000000  10 00000000  fp 00000000
I/DEBUG   (   31):  ip 0000959c  sp be956cc8  lr 00008403  pc 0000841e  cpsr 60000030
I/DEBUG   (   31):          #00  pc 0000841e  /data/local/ndk-tests/crasher
I/DEBUG   (   31):          #01  pc 000083fe  /data/local/ndk-tests/crasher
I/DEBUG   (   31):          #02  pc 000083f6  /data/local/ndk-tests/crasher
I/DEBUG   (   31):          #03  pc 000191ac  /system/lib/libc.so
I/DEBUG   (   31):          #04  pc 000083ea  /data/local/ndk-tests/crasher
I/DEBUG   (   31):          #05  pc 00008458  /data/local/ndk-tests/crasher
I/DEBUG   (   31):          #06  pc 0000d362  /system/lib/libc.so
I/DEBUG   (   31):
```
as seen [here](https://developer.android.com/ndk/guides/ndk-stack).

Please reach out if you have any more actionable information on this!
Thank you for using our products.
