### ISSUE TITLE
mapView.setVisibleCoordinates not working when the iPhone is in "Zoom mode"

### ISSUE THREAD

**Issue by gregoireLem** [mapbox/mapbox-gl-native#12916]
mapView.setVisibleCoordinates is not working properly when the iPhone settings is in "zoom mode"

### Steps to reproduce

 1. Put the iPhone in Zoom mode in settings
 2. use the function mapView.setVisibleCoordinates()

### Expected behavior

All coordinates should be visible (this is working fine when the iPhone is in "normal mode"

### Actual behavior

The zoom is maximal on the mapview & not showing the coordinates

### Configuration

**Mapbox SDK versions: 4.2.0** 
**iOS: 11** 
**Device models: 7/8**
**Xcode version: 9/10**

**Comment by julianrex** [comment]
@gregoireLem can you confirm what you mean by "Zoom mode" please? Is it one of the following?
1. "Plus" sized iPhone models have a "Display Zoom" mode under Display & Brightness -> Display Zoom.
2. There are zoom options under General -> Accessibility -> Zoom
3. And also Text Size under Display & Brightness -> Text Size

thanks!

**Comment by gregoireLem** [comment]
On iOS 12 this is the one you control in :
Settings -> Display & brightness-> Display Zoom

**Comment by gregoireLem** [comment]
I just tried on iPhone 8 iOS 12 & I am not able to reproduce the bug. I will check tomorrow on iPhone 7 iOS 11 & let you know.
