### ISSUE TITLE
onDestroy() using fragment results in Fatal signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by vnhjdh** [mapbox/mapbox-gl-native#12924]
Using MapView in a fragment.

override fun onDestroyView() { 
    mapView.onDestroy()
 }

results in Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR).

### Configuration
- Android API 28.
- Emulator.
- 6.5.0.

**Comment by tobrun** [comment]
@vnhjdh do you have more information on reproducing this? 
Not seeing this behaviour on our end:

![ezgif com-video-to-gif 82](https://user-images.githubusercontent.com/2151639/45805760-b36f6e80-bcbf-11e8-92df-94391db79659.gif)

**Comment by tobrun** [comment]
Thank you for providing test code @vnhjdh, this is always helpfull.

Currently I'm seeing the following in the provided code:

```java
/**
 * A placeholder fragment containing a simple view.
 */
class MainActivityFragment : Fragment() {

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        Mapbox.getInstance(context!!, context?.getString(R.string.mapbox_access_token))
        return inflater.inflate(R.layout.fragment_main, container, false)
    }
}
```

On one end this doesn't contain the method you mention in OP:

```
override fun onDestroyView() { 
   mapView.onDestroy()
 }
```

On the other end it doesn't contain all the other required lifecycle methods (onCreate, onStart, ...)

**Comment by vnhjdh** [comment]
[MapboxTest2.zip](https://github.com/mapbox/mapbox-gl-native/files/2401754/MapboxTest2.zip)

This example seems to show there is not a issue with mapbox. You can close the issue.

**Comment by tobrun** [comment]
Thank you for reporting this back and using our products!
