### ISSUE TITLE
Mapbox GL on Raspberry Pi 3 for Qt 

### ISSUE THREAD

**Issue by polivier2** [mapbox/mapbox-gl-native#12940]
Hi, I am trying to use _mapboxgl_ as a plugin for Qt 5.10.1 on a Raspberry Pi 3. I have been working with two configs without success yet.

**Platform:** Raspberry Pi 3

### Config 1

For this config I have been following these steps: http://wiki.qt.io/RaspberryPi2EGLFS with:

-  Raspbian Stretch Lite (_Version: June 2018_)
-  Qt 5.10
-  GCC 6.3.0

While compiling QtLocation 5.10.1 for my RPi, the MapboxGL plugin was said to be compiled to. Yet, when I was running the app on the RPi there were no display of any map. Only the Mapbox plugin was working.

### Config 2

For this config I tried the meta-qt5 Yocto layer following these steps: https://jumpnowtek.com/rpi/Raspberry-Pi-Systems-with-Yocto.html with:

-  Yocto 2.5.1
-  Qt 5.10.1
-  GCC 7.3.0

I was able to build a qt5-image and to make it run on my RPi but as the previous config there were no display of any maps using _mapboxgl_ plugin. I do know that you are providing support for this platform but I have seen some issues where MapboxGL is running on RPi so I was wondering if i had miss something or if anyone had some advice.

Thanks for your time!

**Comment by brunoabinader** [comment]
Hi @polivier2, thank you for the feedback! This repository is for keeping track of issues related to the Mapbox GL native map rendering engine. Please use Qt's bug tracker system for Qt related issues.

Link: https://bugreports.qt.io

We've released a Yocto meta layer in the past - see https://blog.mapbox.com/vector-maps-on-raspberry-pi-and-yocto-faf9f1423757 for details.

Our meta is hosted here (though not currently maintained): https://github.com/mapbox/meta-mapbox
