### ISSUE TITLE
Map center changes randomly/inconsistently when zooming in while panning animation is on (iOS)

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1294]
Map center changes inconsistently/randomly if one zooms in/out (using animated:NO) while panning animation is on. For e.g. if you are panning in land area with animation, zooming in/out changes map center so randomly that one ends  up in sea/water area.

This bug is consistently reproducible using the following steps:

1.) Add a stepper control that increments/decrements zoom without animation. (This is to be able to consistently zoom in/out without animation while panning animation is running).
2.) Pan with animation.
3.) Use the stepper controls to zoom in/out.

**Comment by 1ec5** [comment]
Hm, I think this may be what's complicating the zoom animation I'm working on for #1292.

**Comment by incanus** [comment]
This probably also relates to the transform problems over in #1125 & https://github.com/mapbox/mapbox-gl-native/issues/1160.

**Comment by incanus** [comment]
Is this still relevant @mb12? I don't think we see this anymore.

**Comment by mb12** [comment]
You are right. Its not relevant any more. I haven't noticed random center changes on iOS for quite some time.
