### ISSUE TITLE
Error 443 when rendering tiles

### ISSUE THREAD

**Issue by pbnsilva** [mapbox/mapbox-gl-native#12948]
Hello, I'm using `node-mapbox-gl-native` to render tiles using a custom style.

I'm running `node-mapbox-gl-native` version `4.0.0`.

Rendering with the code:

```
var tile1 = {
  ratio: 1.556650390625,
  zoom: 8,
  width: 1024,
  height:  1024,
  center: [8.420257, 50.854598],
  pxWidth: 1594,
  pxHeight: 1594,
}

var tile2 = {
  ratio: 1.556650390625,
  zoom: 8,
  width: 1024,
  height:  1024,
  center: [11.232842, 50.854598],
  pxWidth: 1594,
  pxHeight: 1594,
}

renderTile('tile1', t1);
renderTile('tile2', t2);

function renderTile(name, tile) {
  var options = {
    request: function(req, callback) {
       // ...
    },
    ratio: tile.ratio,
  };

  var map = new mbgl.Map(options);

  map.load(require(stylePath));

  map.render({
    zoom: tile.zoom,
    width: tile.width,
    height:  tile.height,
    center: tile.center,
    bearing: 0,
    pitch: 0,
  }, function(err, buffer) {
      console.log(err); // <--- 443 ERROR HERE
      if (err) throw err;

      map.release();

      var image = sharp(buffer, {
          raw: {
              width: tile.pxWidth,
              height: tile.pxHeight,
              channels: 4
          }
      });

      // Convert raw image buffer to PNG
      image.toFile(name + '.png', function(err) {
          if (err) throw err;
      });
  });
}
```

### Steps to trigger behavior

 1. Run the above code several times consecutively.

### Expected behavior

Tiles get rendered every time.

### Actual behavior

Get error:
`Error: getaddrinfo ENOTFOUND a.tiles.mapbox.com a.tiles.mapbox.com:443`

I could understand if it were a 429, and I was hitting rate limiting (?). But this 443 is undocumented.

Thank you

**Comment by kkaefer** [comment]
It looks like you're confusing HTTP status codes with TCP port numbers. The error message you posted says that the DNS resolver can't resolve `a.tiles.mapbox.com`. This usually means that something with your internet connection is not working; maybe a temporary blip?

**Comment by pbnsilva** [comment]
@kkaefer  Yes, of course, silly me.

In any case, I face this issue both locally and on my servers, and it is not new...

**Comment by pbnsilva** [comment]
@kkaefer I'm getting these errors consistently. I'm not behind any proxy or firewall. It happens both on my local machine and on a gcloud server.

I see several other people with the same problem on this page.

Could it have anything to do with request rate?

**Comment by kkaefer** [comment]
> I see several other people with the same problem on this page.

Where do you see them?

The error appears to happen earlier in the stack: `a.tiles.mapbox.com` can't be found by whatever code you're using in the networking stack.

**Comment by crb596** [comment]
Did anyone find a fix to this? Running into the same issue, same error, both on servers and running locally as mentioned when running the code several times consecutively. Haven't seen any resolutions despite the age of the problem
