### ISSUE TITLE
Software Type Layer.

### ISSUE THREAD

**Issue by ramanbranavitski** [mapbox/mapbox-gl-native#12951]
Hi, I just have a small question. Is it possible to render a MapView using LAYER_TYPE_SOFTWARE to make it possible to apply any shape for it using PorterDuff filters? Thanks.

**Comment by kkaefer** [comment]
No. Mapbox GL requires hardware acceleration and will not work in software layers.

**Comment by ramanbranavitski** [comment]
Thanks.
