### ISSUE TITLE
onCameraMove not triggered when using the location layer in 6.6.0_alpha.1

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#12953]
The onCameraMove is currently not triggered when using the new location layer (and CameraMode is set to NONE) which was introduced with 6.6.0_alpha.1. I saw that https://github.com/mapbox/mapbox-gl-native/pull/12932 might fix that issue. Is there any ETA when this fix and a new alpha is out?

**Comment by LukasPaczos** [comment]
Correct, https://github.com/mapbox/mapbox-gl-native/pull/12932 fixes the issue an will be available in the `6.6.0-alpha.2` mid-week and ultimately in the stable `6.6.0`.
