### ISSUE TITLE
dx tool failed:Uncaught translation error: com.android.dx.cf.code.SimException (LoggerDefinition,NativeHttpRequest)

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-gl-native#12965]
Unable to compile apk getting error.

event with java1.8 configs 

```
android {
    ...
    ...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

```
dx tool failed:Uncaught translation error: com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
Uncaught translation error: com.android.dx.cf.code.SimException: default or static interface method used without --min-sdk-version >= 24
Uncaught translation error: com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
3 errors; aborting
```

**Comment by Xgamefactory** [comment]
using build tools build-tools\28.0.2 we are getting more detailed errors with mapbox sdk classes
```
dx tool failed:
WARNING in com.mapbox.mapboxsdk.log.LoggerDefinition.log:(ILjava/lang/String;Ljava/lang/String;)V: 
defining a static interface method requires --min-sdk-version >= 24 (currently 13) for interface methods:
 com.mapbox.mapboxsdk.log.LoggerDefinition.log:(ILjava/lang/String;Ljava/lang/String;)V

Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in 
com.mapbox.mapboxsdk.http.NativeHttpRequest.executeLocalReques:(Ljava/lang/String;)V: 
invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)

Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in 
com.mapbox.mapboxsdk.log.Logger.log:(ILjava/lang/String;Ljava/lang/String;)V: invoking a static 
interface method com.mapbox.mapboxsdk.log.LoggerDefinition.log:(ILjava/lang/String;Ljava
/lang/String;)V strictly requires --min-sdk-version >= 24 (blocked at current API level 13)

Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in 
com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface:(Lcom/mapbox/mapboxsdk
/maps/MapboxMapOptions;)V: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 
(currently 13)
3 errors; aborting
```

**Comment by Xgamefactory** [comment]
myBuildToolsVersion=27.0.3
myMinSdkVersion=27
myTargetSdkVersion=27
myCompileSdkVersion=27

**Comment by tobrun** [comment]
I'm thinking this is an gradle wrapper/ tools issue. You are trying to use java 8 with a version that doesn't support this without the jack compiler. Could you update your Android Studio installation to 3.2.0? and update gradle wrapper version to 4.6 with android plugin version to 3.2.0?

**Comment by Xgamefactory** [comment]
ok i will try.

**Comment by Xgamefactory** [comment]
we have updated android studio android plugin version and graddle wrapper 
build tool changed to 28.0.2 
 but same result.

**Comment by LukasPaczos** [comment]
Hey @Xgamefactory, have you been able to resolve issues mentioned in the ticket?

That said, we are going to downgrade to Java 1.7 by mid-November, closing this one as not actionable at this point.

**Comment by Xgamefactory** [comment]
No @LukasPaczos.
Hope you fan finish downgrade earlier.

**Comment by Xgamefactory** [comment]
we will appreciate if you can downgrade at least these classes only  for now.
we are getting error only in these classes.

- LoggerDefinition
- NativeHttpRequest
- MapView

changing invokedynamic  and static interface method _log_

**Comment by tobrun** [comment]
Hey @Xgamefactory, using java 8 language features is commonly accepted in the android community and nowadays results in no added size to the resulting apk. Why aren't you able to upgrade? 

> LoggerDefinition
NativeHttpRequest
MapView

FWIW,  Non of these classes use any java8 language features

This all said, we are removing java 8 language features in the upcoming next major release. Initially planned for next month but we will have to postpone that until a month later. Reason for this is that we want to include as much api changing features as possible  so we limit the amount of major releases.

Thanks for reaching out and using our products.
