### ISSUE TITLE
Android crash "Binary XML file line #2: Error inflating class com.mapbox.mapboxgl.views.MapView"

### ISSUE THREAD

**Issue by thanawatSuj** [mapbox/mapbox-gl-native#1298]
I test on 
Nexus 5
Sony Xperia Z2 Tablet LTE
Samsung S4

but error "Binary XML file line #2: Error inflating class com.mapbox.mapboxgl.views.MapView"

same Issue https://github.com/mapbox/mapbox-gl-native/issues/1245
and https://github.com/mapbox/mapbox-gl-native/issues/738

how to confix this error.
Thank you.

**Comment by kkaefer** [comment]
Duplicate of #1245
