### ISSUE TITLE
Unknown pbf field type exception

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#12984]
Originally reported in https://github.com/mapbox/mapbox-navigation-android/issues/1326 by @Danny-James

> Hi Guys, I've just come across when starting my Navigation, I've tried to reproduce this and i'm not able to do so.
>
> ```
> 09-27 11:38:48.801 8930-10471/uk.co.ainscough.routeinfo E/AndroidRuntime: FATAL EXCEPTION: > GLThread 21502
>     Process: uk.co.ainscough.routeinfo, PID: 8930
>     java.lang.Error: unknown pbf field type exception
>         at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeRender(Native Method)
>         at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onDrawFrame(MapRenderer.java:74)
>         at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.onDrawFrame(GLSurfaceViewMapRenderer.java:57)
>         at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
>         at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
> ```
>
> Crashlytics - http://crashes.to/s/614e14337a5

**Comment by LukasPaczos** [comment]
Thanks for reporting the issue @Danny-James.
> java.lang.Error: unknown pbf field type exception

Just to verify, are you generating and hosting the used tileset yourself, or using Mapbox services for that?

**Comment by Danny-James** [comment]
everything is standard using mapbox @LukasPaczos

**Comment by tobrun** [comment]
This is a race condition with our binary shaders. Binary shaders have been disabled in https://github.com/mapbox/mapbox-gl-native/pull/14298 so it won't crash anymore. Follow up on enabling them in long term future is ticketed in https://github.com/mapbox/mapbox-gl-native/issues/14294.

This fix is available in the `v7.4.0` release and is currently being backported to v6.8.x in https://github.com/mapbox/mapbox-gl-native/pull/14672 (which we aim to release somewhere this week).
