### ISSUE TITLE
[Android] LineLayer not appearing on map

### ISSUE THREAD

**Issue by amir169** [mapbox/mapbox-gl-native#12990]
I tried to add a line using LineLayer and I got different results on different devices! On my device, Galaxy A3-2017, this was fine and the line was drawn correctly but on many other devices such as: Nexus 5X, Asus Zenphone, Huawei honor, ... this was not working and no line where drawn. Here's my code:

            List<Point> points = new ArrayList<>();
            for (LatLng coord : getCoords()) {
                points.add(com.mapbox.geojson.Point.fromLngLat(coord.getLongitude(), coord.getLatitude()));
            }
           LineString lineString = LineString.fromLngLats(points);

            GeoJsonSource geoJsonSource = new GeoJsonSource("source", lineString);
            mapboxMap.addSource(geoJsonSource);

            LineLayer layer = new LineLayer("id", "source");

            Float[] dashArray = new Float[1];
            dashArray[0] = 1f;

            layer.setProperties(
                    PropertyFactory.lineCap("round"),
                    PropertyFactory.lineJoin("round"),
                    PropertyFactory.lineWidth(7f),
                    PropertyFactory.lineColor("#09baba"),
                    PropertyFactory.lineOpacity(1f)
                    ,PropertyFactory.lineDasharray(dashArray));

            mapboxMap.addLayer(layer);

### Expected behavior
A simple map with a line drawn on it:
![image](https://user-images.githubusercontent.com/16114653/46241714-a989f180-c3ca-11e8-85d8-538a12567205.png)

### Actual behavior
A simple map:
![image](https://user-images.githubusercontent.com/16114653/46241741-008fc680-c3cb-11e8-8dbc-0c399ae4a27c.png)

### Configuration

Device models: Nexus 5X with android 8, Huawei honor with android 5, Asus Zenphone
Mapbox SDK version: 6.5.0

The weird thing is, this was OK in previous versions of Mapbox SDK such as 6.1.0.

**Comment by tobrun** [comment]
6.6.0 has landed, feel free to test out if this version resolves your issue from OP. 
Please reach out if not, closing for now.

**Comment by amir169** [comment]
@tobrun 
I can see this issue in 'Mapbox SDK version: 6.7.0' on 'Samsung GT-N7100' device.
Would you please re-open this.

**Comment by rudza** [comment]
Is there any progress on this?
