### ISSUE TITLE
Response class in not NSHTTPURLResponse

### ISSUE THREAD

**Issue by robipresotto** [mapbox/mapbox-gl-native#1299]
The api accept now only NSURL to set the json style,
How is possible download the json style, change it locally and reuse the data on mapstyle?

I got it all the time...
[ERROR] {0}{Map}[Setup]: loading style failed: response class is not NSHTTPURLResponse

**Comment by kkaefer** [comment]
You can use `asset://...` to load from disk, or use `.setStyleJSON()` to load styles directly from memory.

**Comment by robipresotto** [comment]
the setStyleJSON is private on master branch... as some reason for that?

**Comment by kkaefer** [comment]
I don't think it's private: https://github.com/mapbox/mapbox-gl-native/blob/2831073f85b502ed0b00c3fb335fadfd705524a5/include/mbgl/map/map.hpp#L105

Maybe you're running an outdated version?

**Comment by robipresotto** [comment]
yeah, i know... but nothing on MGLMapView.h

**Comment by 1ec5** [comment]
I got rid of the `styleJSON` API for now, per https://github.com/mapbox/mapbox-gl-native/issues/1147#issuecomment-88171503 and #900. We'll eventually need some way to interact with styles with that kind of granularity for #837.

/cc @incanus

**Comment by 1ec5** [comment]
Just to close the loop, if you pass a relative URL into `-setStyleURL:`, we’ll treat that as a local file relative to the main bundle. Absolute file URLs still lead to an error; see #3505.
