### ISSUE TITLE
Can I provide a drawing tool to the user by mapbox-gl-native?

### ISSUE THREAD

**Issue by LSG8** [mapbox/mapbox-gl-native#13001]
### Expected behavior

Mapbox-gl-js has mapbox-gl-draw which provides a drawing tool to the user and user can draw a polygon on the map. It has an example: https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/
Can mapbox-gl-native provide a drawing tool to the user? If not, then how do I replicate mapbox-gl-draw in native android application?

**Comment by kkaefer** [comment]
Thanks for your interest in Mapbox GL. This isn't a feature that the Android or iOS (native) SDKs support, and it's not something we will be adding any time soon.

To replicate what `mapbox-gl-draw` is doing, I recommend looking at its documentation and source code. `mapbox-gl-native` provides many of the same APIs that `mapbox-gl-js` has, so it's likely that you can port the project.
