### ISSUE TITLE
[iOS] cameraThatFitsShape: direction: edgePadding: should also work with pitch

### ISSUE THREAD

**Issue by d-prukop** [mapbox/mapbox-gl-native#13005]
A new method should be added to return a camera that fits a shape while the map is pitched.

**Comment by 1ec5** [comment]
Duplicate of #10115.

**Comment by d-prukop** [comment]
This is not a duplicate of #10115. That ticket is about the `cameraForLatLngs` method in core. This one is for exposing that capability in the iOS SDK.
