### ISSUE TITLE
User location dot appears outside MGLMapView

### ISSUE THREAD

**Issue by robipresotto** [mapbox/mapbox-gl-native#1300]
The current user location dot is outside of the mapbox gl class

**Comment by incanus** [comment]
Not sure I follow @robipresotto — could you clarify?

**Comment by robipresotto** [comment]
small things :)

![ios simulator screen shot 22 apr 2015 08 48 44](https://cloud.githubusercontent.com/assets/3818948/7268793/49fd9f0e-e8cd-11e4-97f8-5fc02645716a.png)

**Comment by robipresotto** [comment]
* arrow = user location dot (my bad)

**Comment by friedbunny** [comment]
@robipresotto That looks like you're sliding the drawer menu in on the left and the dot is mistakenly covering it? I wonder if #1322 would help this, or if the superview is the problem.

**Comment by robipresotto** [comment]
Exactly, but unfortunately after merge the push request this bug still the same

**Comment by 1ec5** [comment]
[This line](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/MGLMapView.mm#L54) causes any annotation within 150 points vertically / 150 points horizontally of the viewport to be added to the view hierarchy and drawn. We should set `clipsToBounds` on the `MGLMapView`.

**Comment by incanus** [comment]
Ah! That makes sense and seems like the right/easy fix.

**Comment by 1ec5** [comment]
The :dog:, :information_source:, and compass can all get clipped with `clipsToBounds` set, depending on the `MGLMapView`’s frame.
