### ISSUE TITLE
Question about ToS and pricing

### ISSUE THREAD

**Issue by tanjakainz** [mapbox/mapbox-gl-native#13012]
I am currently evaluating the use of the MapBox SDK for a mobile app (Android and iOS).
After I read all the information about attribution, pricing and ToS I still have some questions.

Can I use the SDK for free if I use only self hosted services and my own data (including own vector tiles, own styles, etc.)?

If yes, do I need to display the attribution on the map itself or can it be shown inside a separate screen like "Credits & Licenses"?

To clarify I don’t want to use any MapBox services, APIs, styles or anything provided by MapBox which requires the purchase of a MapBox plan/license.

Thanks,
Tanja

**Comment by LukasPaczos** [comment]
Hey @tanjakainz, we're glad that you're interested in Mapbox! This repo is for bug reports and feature requests only. For pricing questions please contact [the sales department](https://www.mapbox.com/contact/sales/?page=/pricing).
