### ISSUE TITLE
add api to warm ambient cache

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#13022]
Add an api that lets a developer warm the cache with their style. Having the style cached before the map view is created reduces time-to-first-render and allows the developer to modify the style without waiting for it to load.

Example:
The app downloads a post that contains a map + marker and wants to preload the style before the user opens a post. When the user opens a post later (possibly with lower connectivity) the marker is rendered immediately as a geojson layer and time-to-first-render for the rest of the map is lower.

A developer mentioned that it might be nice to be able to eventually do this from a separate library so the app does not take the hit from loading the entire mbgl library if it isn't being used yet.

**Comment by ChrisLoer** [comment]
@halset made a PR in this direction at https://github.com/mapbox/mapbox-gl-native/pull/12217 that provides an API for explicitly adding resources to the cache (e.g. `putResourceWithUrl`). That might be something we can use? I think we might be concerned that exposing too much of the internals of the cache might put too much responsibility on the caller of the API (and introduce backwards compatibility issues).

@asheemmamoowala recently introduced "merge offline regions" functionality (see the [ios MGLOfflineStorage addContentsOfFile](https://www.mapbox.com/ios-sdk/api/4.5.0-beta.1/Classes/MGLOfflineStorage.html#/c:objc(cs)MGLOfflineStorage(im)addContentsOfFile:withCompletionHandler:)) that we think may have mainly addressed @halset's "download and install new regions" use case. As a temporary solution, it might conceivably be used as a way to pre-cache a style as well? It would require the user who wanted to pre-cache a style to wrap it up in an "offline region" sqlite database, which has I think a few tens of KB of overhead.

The way I understand this request, a specific "pre-load style" API would have the advantages:

- Easier for the caller than figuring out how to make an offline region containing just the style
- Less complexity for the user/fewer internals exposed than a generalized "put resources into the cache"

We'd have to nail down what exactly we wanted to add to the cache, though:

- The stylesheet itself (obviously)
  - Do we need to be thinking about cache-control behavior, or should we just leave it to the caller (if they want explicit control over when the download happens, they can do it themselves and then add to the cache with a local file url)?
- The spritesheet for the style?
  - This is not technically necessary for showing a minimal map, but a lot of use cases will probably want to show icons.
- Glyphs for the style?
  - When we make offline regions, we calculate the complete set of font stacks for the style and download all glyphs for all of them. This is at least tens of megabytes, and probably not what we want to do. Would it make sense to just download the common 0-255 blocks though?

**Comment by ChrisLoer** [comment]
Fixed with #13119, which sidesteps all logic specific to "style" and just provides an API for putting arbitrary resources into the ambient cache (thanks @halset for the PR I based my changes off of!). It's up to the caller to choose what to cache -- pushing both the stylesheet and the spritesheet would be pretty simple, while pushing glyphs would require making some judgments about which font stacks and glyph ranges to pre-load.
