### ISSUE TITLE
Avoid setStyle remove some of previous sources and layers that added manually.

### ISSUE THREAD

**Issue by siavashabdoli** [mapbox/mapbox-gl-native#13030]
Hi I want to change my style at runtime but as you know after setStyleUrl all previous sources and layers will be deleted including LocationLayer (provided by LocationLayerPlugin). It's really hard to add all custom layers again. maybe at least adding a listener for styleChange help here. I saw the callback for onStyleLoad but it's not useful. I have lots of classes and I use lots of plugin from mapbox that add some custom layers(like traffic ...) I need a addStyleChangeListener on mapboxMap so I will be able to add all of those after any style change. of course I will be happy if we can add some sources and layers in a way that style change does not have effect on them.

**Comment by tobrun** [comment]
@siavashabdoli thank you for reaching out and reporting your issue. It's indeed a work as designed that reloading clears previous sources and layers. The reason for this is that the style object is the parent of all sources and layers, changing the parent also removes current attached children. I follow your vision that this is cumbersome and for this reason our plugins are re-added automatically when this happens! 

Isn't this happening for you when using the LocationLayerPlugin or TrafficPlugin?

See sources of LocationLayerPlugin [here](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin.java#L951). We expose the same configuration for our other plugins.

In the distant feature we might be able to fix this up with style components but for the time being this is not actionable right now. Please reach out if the plugins aren't reloaded as expected!
