### ISSUE TITLE
Crash when trying to set MGLSymbolStyleLayer.textOffset

### ISSUE THREAD

**Issue by joshfisher** [mapbox/mapbox-gl-native#13033]
I'm attempting to set the `textOffset` property to be a function of the `zoomLevel`, like so
```
        let textOffsetStops = [
            14: NSValue(cgVector: CGVector(dx: 0, dy: 0)),
            22: NSValue(cgVector: CGVector(dx: 0, dy: 2))
        ]
        textOffset = NSExpression(format: "mgl_interpolate:withCurveType:parameters:stops:($zoomLevel, 'exponential', 1.5, %@)", textOffsetStops)
```

But that causes an exception at the point of setting. I put on an "all exceptions" breakpoint & it shows me the location in the attached screenshot. I also tried the following, with the same result.
```
        textOffset = NSExpression(forMGLInterpolating: NSExpression(forVariable: "$zoomLevel"),
                                  curveType: .exponential,
                                  parameters: [NSExpression (forConstantValue: 1.5)],
                                  stops: NSExpression(forConstantValue: textOffsetStops))
```

The following worked in the 3.7 SDK version. 
```
        textOffset = MGLCameraStyleFunction(interpolationMode: .exponential,
                                            stops: [18: MGLStyleValue(rawValue: NSValue(cgVector: CGVector(dx: -1, dy: 0))),
                                                    20: MGLStyleValue(rawValue: NSValue(cgVector: CGVector(dx: -2, dy: 0))),
                                                    22: MGLStyleValue(rawValue: NSValue(cgVector: CGVector(dx: -3, dy: 0)))])
```

[The documentation](https://www.mapbox.com/ios-sdk/api/4.4.1/Classes/MGLSymbolStyleLayer.html#/c:objc(cs)MGLSymbolStyleLayer(py)textOffset) indicates that it should work, unless I'm misreading it somehow?

**Mapbox SDK versions:** 
4.4.1

**iOS/macOS versions:** 
iOS 12

**Device/simulator models:**
iPhone 8 simulator

**Xcode version:** 
Xcode 9.4.1

<img width="1476" alt="screen shot 2018-10-04 at 12 35 25 pm" src="https://user-images.githubusercontent.com/545891/46489090-84ceb900-c7d2-11e8-8903-8389b0b284ec.png">

**Comment by captainbarbosa** [comment]
I can confirm that this crashes for me as well. cc @1ec5

**Comment by fabian-guerra** [comment]
Hi, @joshfisher. Thank you for using Mapbox. When using the new API you also have to wrap the values as expressions just like you wrapped the values as `MGLStyleValue` before:

```
textOffset = MGLCameraStyleFunction(interpolationMode: .exponential,
                                            stops: [18: MGLStyleValue(rawValue: NSValue(cgVector: CGVector(dx: -1, dy: 0))),
                                                    20: MGLStyleValue(rawValue: NSValue(cgVector: CGVector(dx: -2, dy: 0))),
                                                    22: MGLStyleValue(rawValue: NSValue(cgVector: CGVector(dx: -3, dy: 0)))])
```

Change:
```
let textOffsetStops = [
            14: NSValue(cgVector: CGVector(dx: 0, dy: 0)),
            22: NSValue(cgVector: CGVector(dx: 0, dy: 2))
        ]
```
To:
```
let textOffsetStops = [
            14: NSExpression(format: "%@", NSValue(cgVector: CGVector(dx: 0, dy: 0))),
            22: NSExpression(format: "%@", NSValue(cgVector: CGVector(dx: 0, dy: 2)))
        ]
```

That will make it work.

I'm going to close this issue but feel free to reopen it if the above doesn't work.
