### ISSUE TITLE
problem when building from source android on mac os

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-gl-native#13048]
after running **make aproje**
project opened in android studio with this error

```
Unsupported Modules Detected: Compilation is not supported for following modules: android. 
Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.

Error:Could not get unknown property 'compileDebugUnitTestSources' for project 
':MapboxGLAndroidSDK' of type org.gradle.api.Project.
```
![screenshot](https://user-images.githubusercontent.com/22529051/46606258-4fe19f80-cb0d-11e8-9e81-c196a886ef3f.png)

**Comment by tobrun** [comment]
Thank you for reaching out @Xgamefactory, haven't heard about this issue before. 

Here is some information on my local working configuration on mac:
<img width="641" alt="screen shot 2018-10-09 at 12 38 36" src="https://user-images.githubusercontent.com/2151639/46664409-3dc13900-cbc1-11e8-8554-1ebe8b271b12.png">

Project structure of the android tab should look like:
<img width="344" alt="screen shot 2018-10-09 at 12 44 21" src="https://user-images.githubusercontent.com/2151639/46664422-487bce00-cbc1-11e8-9bd9-97ef2f593bd1.png">

configuration.gradle file contents:
<img width="314" alt="screen shot 2018-10-09 at 12 44 31" src="https://user-images.githubusercontent.com/2151639/46664438-54679000-cbc1-11e8-9175-7a59c2d193ec.png">

SDK tools:

<img width="783" alt="screen shot 2018-10-09 at 12 47 09" src="https://user-images.githubusercontent.com/2151639/46664489-79f49980-cbc1-11e8-88fe-00944c2658c2.png">

Considering that we do not provide support for building from source and we aren't hitting this issue locally. Going to close.

**Comment by Xgamefactory** [comment]
thanks @tobrun we are using ndk 17c we will try with ndk15.

**Comment by tobrun** [comment]
17c should work as well, 18 isn't yet supported see https://github.com/mapbox/mapbox-gl-native/pull/12972

**Comment by Xgamefactory** [comment]
unfortunately we have 17c and stucked 

![46664898-4fabd780-cbd3-11e8-997d-67964cf3e9c2](https://user-images.githubusercontent.com/22529051/46666193-14aba300-cbd7-11e8-9fcd-bb277ef7a590.png)

**Comment by Xgamefactory** [comment]
is it normal that output aar MapboxGLAndroidSDK-debug.aar is 22mb ? 
official mapbox-android-sdk-6.5.0.aar  is less than 10mb

**Comment by Xgamefactory** [comment]
we tried **make android-lib-arm-v8** also gives 22mb aar output

**Comment by tobrun** [comment]
this is normal as this is a debug variant, you can build a release with `BUILDTYPE=Release make android` for arm-v7. The normal release aar is build with `make apackage`.

**Comment by Xgamefactory** [comment]
thanks for tips where we should define BUILDTYPE ?

**Comment by Xgamefactory** [comment]
we did **make apackage** we get build success on terminal but no aar output

**Comment by tobrun** [comment]
BUILDTYPE is a command line argument, when building with Android Studio, it will automatically pick up if you are building debug or a release variant. 

What is the path you are looking for the aar output?

**Comment by Xgamefactory** [comment]
there is a line in build.gradle 
    `defaultPublishConfig project.hasProperty("mapbox.buildtype") ? project.getProperty("mapbox.buildtype") : "debug"`

but we did not found where is mapbox.buildtype  defined.
just changed debug to release

can you provide a screenshot where did you provide BUILDTYPE=Release make android ?

this is the path where aar is generated 
**/Users/user/Downloads/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/build/outputs**

**Comment by Xgamefactory** [comment]
thanks for support @tobrun for know i will use debug arr
or just replace files under jni folder with orignial aar ones )

**Comment by tobrun** [comment]
either command-line:

<img width="542" alt="screen shot 2018-10-09 at 14 44 11" src="https://user-images.githubusercontent.com/2151639/46670211-dbbcff80-cbd1-11e8-8cba-eb2b124ad370.png">

or in android studio build variants:

<img width="361" alt="screen shot 2018-10-09 at 14 45 08" src="https://user-images.githubusercontent.com/2151639/46670257-f7c0a100-cbd1-11e8-8c24-362de216e1a1.png">

**Comment by Xgamefactory** [comment]
i have changed to release through build variants.
but release build gives error

```
by the way running test app crashes


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':MapboxGLAndroidSDK:externalNativeBuildRelease'.
> Build command failed.
  Error while executing process /Users/Xtrack/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /Users/Xtrack/Downloads/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/release/x86_64 --target mapbox-gl}
  [1/402] Linking CXX static library libicu.a
  [2/402] Building C object CMakeFiles/sqlite.dir/vendor/sqlite/src/sqlite3.c.o
  [3/402] Building CXX object CMakeFiles/mbgl-core.dir/src/mbgl/actor/mailbox.cpp.o
  [4/402] Building CXX object CMakeFiles/mbgl-core.dir/src/mbgl/actor/scheduler.cpp.o
  [5/402] Building CXX object CMakeFiles/mbgl-core.dir/src/mbgl/algorithm/generate_clip_ids.cpp.o
  [6/402] Building CXX object CMakeFiles/mbgl-core.dir/src/mbgl/annotation/annotation_manager.cpp.o
  [7/402] Building CXX object CMakeFiles/mbgl-core.dir/src/mbgl/annotation/annotation_source.cpp.o
  FAILED: /Users/Xtrack/Downloads/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/release/x86_64/launch-c /Users/Xtrack/Downloads/android-ndk-r17c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang  --target=x86_64-none-linux-android --gcc-toolchain=/Users/Xtrack/Downloads/android-ndk-r17c/toolchains/x86_64-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/Xtrack/Downloads/android-ndk-r17c/sysroot -DHAVE_DECL_STRERROR_R=1 -DHAVE_DLFCN_H=1 -DHAVE_FDATASYNC=1 -DHAVE_GMTIME_R=1 -DHAVE_INTTYPES_H=1 -DHAVE_LOCALTIME_R=1 -DHAVE_MEMORY_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRERROR_R=1 -DHAVE_STRINGS_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DHAVE_USLEEP=1 -DHAVE_ZLIB_H=1 -DMBGL_USE_GLES2=1 -DRAPIDJSON_HAS_STDSTRING=1 -DSQLITE_HAVE_ZLIB -DSQLITE_THREADSAFE=1 -DSTDC_HEADERS=int -DVERSION=\"3.24.0\" -D_GLIBCXX_USE_CXX11_ABI=0 -D_REENTRANT=1 -I../../../../../../../vendor/sqlite/include -isystem /Users/Xtrack/Downloads/android-ndk-r17c/sysroot/usr/include/x86_64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -Wall -Wextra -Wshadow -Wno-variadic-macros -Wno-unknown-pragmas -Werror -ffunction-sections -fdata-sections -O2 -DNDEBUG  -Os -DNDEBUG -flto -fPIC -fvisibility=hidden   -Wno-int-conversion -Wno-implicit-fallthrough -std=c99 -MD -MT CMakeFiles/sqlite.dir/vendor/sqlite/src/sqlite3.c.o -MF CMakeFiles/sqlite.dir/vendor/sqlite/src/sqlite3.c.o.d -o CMakeFiles/sqlite.dir/vendor/sqlite/src/sqlite3.c.o   -c /Users/Xtrack/Downloads/mapbox-gl-native/vendor/sqlite/src/sqlite3.c
  clang: error: argument unused during compilation: '-Wa,--noexecstack' [-Werror,-Wunused-command-line-argument]
  ninja: build stopped: subcommand failed.
```
