### ISSUE TITLE
unable to "Building & Developing from Source" windows android studio 3.2

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-gl-native#13043]
Hi

We tried to build from source mapbox android sdk.
downloaded mapbox-gl-native-master and import from android studio
but we get weird project structure 

![image 1](https://user-images.githubusercontent.com/22529051/46576070-fd03cd00-c9d2-11e8-9d12-dcada6061921.png)

we did not found any tips for windows os just mac and linux how to build project after downloading.
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/README.md

also we got warning "**this project does not use the Gradle build system**"
![mapbox_import_7_migrate](https://user-images.githubusercontent.com/22529051/46576485-a353d080-c9db-11e8-8464-bfe43a4c284c.png)

We would really appreciate any help.

**Comment by Xgamefactory** [comment]
are you still not supporting building from source on windows ?
we need to downgrade android sdk to java7 as have issues building apk #12965

**Comment by tobrun** [comment]
Building the android sdk from source on Windows isn't supported atm though theoretical possible.
We are open source, happy to review any PRs contributed. Closing as non actionable.
