### ISSUE TITLE
weird errors with cmake could not lock config file .git/config: File exists

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-gl-native#13054]
failed to sync gradle trying to build from source on mac.

looks like cmake trying to create a project instead of update merge.

CMake Error at cmake/mbgl.cmake:54 (message):

```
fatal: destination path '/Users/Xtrack/Downloads/mapbox-gl-native/mapbox-gl-js' already exists and is not an empty directory.	
fatal: clone of 'https://github.com/mapbox/mapbox-gl-js.git' into submodule path '/Users/Xtrack/Downloads/mapbox-gl-native/mapbox-gl-js' failed	
Failed to clone 'mapbox-gl-js'. Retry scheduled	
Failed to clone 'mapbox-gl-js' a second time, aborting	
```

```

-- Detecting C compile features - done	
-- Updating submodules...	
could not lock config file .git/config: File exists	
fatal: Failed to register url for submodule path 'mapbox-gl-js'	
-- Running 'npm install' for mapbox-gl-native...	
-- Finished 'npm install' for mapbox-gl-native...	
-- Running 'npm install' for mapbox-gl-js...	
```

**Comment by Xgamefactory** [comment]
we have installed all dependencies as you have described but unabled successfully build on mac.
also developing.md simple just not exists
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/DEVELOPING.md

Anyway i have commented out these npm sync processes from cmake/mbgl.cmake that caused error.
gradle sync error has gone but  executing externalNativeBuildDebug process never completes 

are there anyone you can able to make a build from source on mac ?


![screenshot](https://user-images.githubusercontent.com/22529051/46663832-2a699a00-cbd0-11e8-8f67-87ae9cfe486b.png)

**Comment by tobrun** [comment]
Thanks for the report @Xgamefactory.

How did you download the project? You need to use `git clone git@github.com:mapbox/mapbox-gl-native.git`, downloading as zip will not work for the submodule configuration.

> developing.md simple just not exists
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/DEVELOPING.md

Is there a broken link somewhere in our documentation? I never heard about the convention of needing to have DEVELOPING.md file. fwiw our environement setup is covered [here](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android#setup-environment).

> are there anyone you can able to make a build from source on mac ?

Yes, most of us build from source on a mac daily. 

Going to close this issue as building from source if not something we officially provide support on.

**Comment by Xgamefactory** [comment]
Yes we get project by **git clone git@github.com:mapbox/mapbox-gl-native.git**

> I never heard about the convention of needing to have DEVELOPING.md file. fwiw our environement setup is covered here.

![image 3](https://user-images.githubusercontent.com/22529051/46665017-a44f5280-cbd3-11e8-8529-ec035faad94f.png)
