### ISSUE TITLE
Rendering multiple layers

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1305]
Some of our styles have a lot of layers, in particular, they have a lot of line layers. However, many of these line layers only have a few items on them (e.g. highway bridge casings). Instead of rendering every layer separately, we should look at rendering multiple layers together.

Currently, our styles are split into a _layout_ and a _paint_ component; the _layout_ part gets statically parsed into GL buffers. The _paint_ part is passed into the pipeline as uniforms during rendering, since it may change on every frame. To combine multiple geometries into one buffer, we'd have to add a style index to every vertex (effectively increasing every vertex by 4 bytes, since we shouldn't make indices non-4-byte aligned) and pass in uniform values as an array (corresponding to the indices we added to the buffers).

**Polygons:**
- translation matrix
- fill color

**Lines:**
- translation matrix
- fill color
- line width
- blur

Since we only allow affine transformations, we could use a 9-element 3D matrix rather than 4D matrices; polygon would thus require 13 elements per layer; OpenGL ES 2's required minimum is 128, so with some headroom (and uniform packing inefficiencies) that'll probably leave us with 7-8 layers we could render per draw call. Lines need more data, per layer, so we could probably only merge 5-6 line layers into one draw call.

Alternatively, we could use vertex textures to look up the values, but they're less efficient to update than uniforms and Tegra doesn't support texture access from vertex shaders, effectively ruling out this possibility.

/cc @ansis @mourner @jfirebaugh

**Comment by mb12** [comment]
Is this to reduce the number of glDrawElements calls?
Would this change also support coalescing calls for styles with different dash_len/dash_gaps?

**Comment by mourner** [comment]
What I'm worried about with this is that we still have no clue how to measure the performance benefit of changes like this. So it might be a lot of effort introducing lots of complexity for a possibly insignificant gain (or a bad tradeoff), so it's a gamble.

So can we tackle the rendering benchmark task first? Related: https://github.com/mapbox/mapbox-gl-js/issues/954

**Comment by ansis** [comment]
I agree with @mourner that we should tackle rendering benchmarking first.

If we render multiple layers in one call we also need to make sure that blending, depth and draw order are correct.

**Comment by kkaefer** [comment]
We have data driven styling now, which enables this feature.
