### ISSUE TITLE
OnMarkerClickListener is not called

### ISSUE THREAD

**Issue by amir169** [mapbox/mapbox-gl-native#13056]
### Description

If user clicks on a marker which is placed inside of a polygon, OnPolygonClick event is raised and OnMarkerClick event is ignored. 
I think this is a wrong behavior because the user sees that the marker is placed above the polygon.

### Steps to reproduce

 1. Add a polygon on map
 2. Add a marker inside the polygon.
 3. Register an OnMarkerClickListener using MapboxMap#setOnMarkerClickListener.
 4. Register an OnPolygonClickListener using MapboxMap#setOnPolygonClickListener.
 5. Run the program and click on the marker.
### Expected behavior
  The OnMarkerClickListener that I registered should be called.

### Actual behavior
  OnPolygonClickListener is called and OnMarkerClickListener is ignored.

### Configuration

**Mapbox SDK versions:** mapbox-android-sdk version 6.5.0

**Comment by tobrun** [comment]
@amir169 correct that we currently prioritise tapping shapes vs markers, see code below:

```java
  //
  // Click event
  //

  boolean onTap(PointF tapPoint) {
    ShapeAnnotationHit shapeAnnotationHit = getShapeAnnotationHitFromTap(tapPoint);
    Annotation annotation = new ShapeAnnotationHitResolver(shapeAnnotations).execute(shapeAnnotationHit);
    if (annotation != null) {
      if (handleClickForShapeAnnotation(annotation)) {
        return true;
      }
    }

    MarkerHit markerHit = getMarkerHitFromTouchArea(tapPoint);
    long markerId = new MarkerHitResolver(mapboxMap).execute(markerHit);
    return markerId != NO_ANNOTATION_ID && isClickHandledForMarker(markerId);
  }
```

I support your case that Marker should get priority over Polygon when clicking the map. 
The order of above code block should be switched.
