### ISSUE TITLE
-[MGLAnnotationView setSelected:animated:] is always animated

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#13055]
As of #11442, the `animated` parameter of `-[MGLMapView selectAnnotation:animated:]` correctly determines whether the map pans to fit a GL point or shape annotation and its callout view. However, annotation views continue to suffer from #3249.

Specifically, both `-handleSingleTapGesture:` and `-selectAnnotation:animated:` specify `animateSelection` as `YES` when calling `-[MGLMapView selectAnnotation:moveOnscreen:animateSelection:calloutPositioningRect:]`. `animateSelection` is then passed in as the `animate` parameter of `-[MGLAnnotationView setSelected:animated:]`, regardless of whether the developer asked for the annotation selection to be animated, which contradicts that method’s documented behavior. It’s also inconsistent with:

* `-[MGLMapView selectAnnotation:animated:]` with GL point annotations
* `-[MGLMapView deselectAnnotation:animated:]` with either kind of point annotation
* MapKit’s `-[MKMapView selectAnnotation:animated:]`

https://github.com/mapbox/mapbox-gl-native/blob/f4ffcaa62f595b996f8bbf2c030006129c765d61/platform/ios/src/MGLMapView.mm#L4373 https://github.com/mapbox/mapbox-gl-native/blob/f4ffcaa62f595b996f8bbf2c030006129c765d61/platform/ios/src/MGLMapView.mm#L4404

Here’s the fix, which can also simplify the surrounding method a bit:

```objc
[annotationView setSelected:YES animated:moveOnScreen];
```

/ref #12064
/cc @julianrex

**Comment by fphilipe** [comment]
Just ran into this. I need to swap out the view for an annotation. I do this by removing the annotation and adding it back, which will result in a different view for the annotation. At the same time I want to preserve the selection, but I do not want to animate the selection:

```swift
let wasSelected = view.isSelected
mapView.removeAnnotation(x)
mapView.addAnnotation(x)
if wasSelected {
    mapView.selectAnnotation(x, animated: false)
}
```

Unfortunately, the animation always shows.
