### ISSUE TITLE
Invalid documentation on feature property accessors

### ISSUE THREAD

**Issue by Tetr4** [mapbox/mapbox-gl-native#13067]
Hi,

the `com.mapbox.geojson.Feature` class in the android SDK has some convenience methods to access properties, like `Feature#getStringProperty(String key)`. The JavaDoc says, it will return `the value of the member, null if it doesn't exist`. But it actually throws a `NullPointerException` if the property does not exist.

### Steps to reproduce

1. Create a feature:
```kotlin
val feature = Feature.fromGeometry(Point.fromLngLat(-71.065634, 42.354950))
```

2. Try to access the property:
```kotlin
val stringProperty: String? = feature.getStringProperty("invalid_id")
```
 
### Expected behavior
`stringProperty` should be `null`.

### Actual behavior
`NullPointerException` is thrown.

### Configuration

**Mapbox SDK versions:** 6.5.0

**Comment by tobrun** [comment]
thanks for the report @Tetr4 , this issue needs to be handled upstream in mapbox-java, I created https://github.com/mapbox/mapbox-java/issues/902 to fix this. Closing as it will be fixed upstream.
