### ISSUE TITLE
marker fade in/out animation 

### ISSUE THREAD

**Issue by basitsaleemmb** [mapbox/mapbox-gl-native#13085]
@tobrun  
how can i add animation of fade out to maker
here you go :

mapboxMap.setOnMarkerClickListener(new MapboxMap.OnMarkerClickListener() {
                @Override
                public boolean onMarkerClick(@NonNull Marker marker) {
                      // add fade out animation to marker here

                      }
}

**Comment by tobrun** [comment]
Your question has been handled [here](https://github.com/mapbox/mapbox-android-demo/issues/883). Please do not spam questions in multiple repositories. Additionally would like to flag that this repository is used to report bugs/crashes and feature requests, not to provide support.
