### ISSUE TITLE
6.6.0 Build failed with proguard

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#13088]
### Steps to reproduce

 1. minifyEnabled true
 2. build

### Expected behavior
BUILD SUCCESSFUL

### Actual behavior
BUILD FAILED
Log:
```
Warning: com.mapbox.api.directions.v5.MapboxDirections: can't find referenced class com.sun.xml.internal.ws.spi.db.BindingContextFactory
Warning: com.mapbox.api.directions.v5.MapboxDirections: can't find referenced class com.sun.xml.internal.ws.spi.db.BindingContextFactory
Warning: com.mapbox.api.matching.v5.MapboxMapMatching: can't find referenced class com.sun.xml.internal.ws.spi.db.BindingContextFactory
Warning: com.mapbox.api.matching.v5.MapboxMapMatching: can't find referenced class com.sun.xml.internal.ws.spi.db.BindingContextFactory
```

### Configuration

**Android versions:** any
**Device models:** any
**Mapbox SDK versions:** 6.6.0 (not reproduce on 6.5.0)

**Comment by tobrun** [comment]
@klblk what others Mapbox libraries are you using? 
`com.mapbox.api.` packages aren't packaged in with the maps SDK

**Comment by klblk** [comment]
i use 'com.mapbox.mapboxsdk:mapbox-sdk-services:4.0.0'. (but not use MapboxDirections api)

Mapbox 6.5.0 build is ok, if change to 6.6.0 build failed (no chage other code )

**Comment by tobrun** [comment]
@klblk the reason why this shows now is that we have slimmed down our proguard configuration on the map sdk to obfuscate more classes for a smaller apk size.

The reason why this isn't handled by the mapbox-sdk-services:4.0.0 dependency, is that itself is not an aar but a jar and doesn't come with a proguard configuration.  

You will have to fix this on your end in your app proguard file, as this is not up to the maps sdk to fix and mapbox-sdk-services doesn't support this configuration.

**Comment by tobrun** [comment]
Reopening this issue as we had another report of this. To avoid more users running into this, I will include an entry for Mapbox services in this repo.
