### ISSUE TITLE
MapView separated to 2 maps and show map from not related fragment 

### ISSUE THREAD

**Issue by pavelpoley** [mapbox/mapbox-gl-native#13098]
I have strange issue, i am using MapBox map in 2 fragments in the app, when i open the second fragment with map the map separated to 2 maps and include map from first fragment, the fragments that include maps not lays one on the other so it not possible the the second fragment show some transparent background.

I have attached screenshots, i also use SwipeBack framework so you can see that the fragment below second fragment not include any map.

The fragments using 2 different **MapView**'s xml elements.

I am using **FragmentTransaction.add()** and not **replace()** so the previews map not destroyed, maybe it is the issue?

![screenshot_2018-10-14-15-09-17-628_com ae touringbee](https://user-images.githubusercontent.com/33838217/46916766-9cbeed80-cfc7-11e8-9bba-0578bfda09d8.png)

SwipeBack
![screenshot_2018-10-14-15-09-27-814_com ae touringbee](https://user-images.githubusercontent.com/33838217/46916770-b102ea80-cfc7-11e8-9bd8-a8fc3abef5d8.png)

Mapbox SDK version - 6.5.0:

**Comment by tobrun** [comment]
@pavelpoley this is because of the used render surface. By default we use an GLSurfaceView implementation. You can get this use-case working by leveraging a TextureView as render surface instead. To enable this feature use either:

```java

  // in MapboxMapOptions.java, which instance can be passed to a MapView constructor

  /**
   * Enable {@link android.view.TextureView} as rendered surface.
   * <p>
   * Since the 5.2.0 release we replaced our TextureView with an {@link android.opengl.GLSurfaceView}
   * implementation. Enabling this option will use the {@link android.view.TextureView} instead.
   * {@link android.view.TextureView} can be useful in situations where you need to animate, scale
   * or transform the view. This comes at a siginficant performance penalty and should not be considered
   * unless absolutely needed.
   * </p>
   *
   * @param textureMode True to enable texture mode
   * @return This
   */
  @NonNull
  public MapboxMapOptions textureMode(boolean textureMode) {
    this.textureMode = textureMode;
    return this;
  }
```

or through xml attributes:

```xml
        <com.mapbox.mapboxsdk.maps.MapView
            android:id="@+id/mapView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:mapbox_renderTextureMode="true" />
```

Closing as answered, please reach out if this approach didn't fix the issue with your use-case!

**Comment by pavelpoley** [comment]
Thank you for help, works!
