### ISSUE TITLE
Missing ProGuard rules

### ISSUE THREAD

**Issue by jrgonzalezg** [mapbox/mapbox-gl-native#13101]
### Steps to reproduce

 1. Add `com.mapbox.mapboxsdk:mapbox-android-sdk:6.6.0` and `com.mapbox.mapboxsdk:mapbox-sdk-services:4.0.0` dependencies to an Android project.
 2. Build a release version of the app with ProGuard turned on.

### Expected behavior

App compiles and APKs are generated.

### Actual behavior

Build fails in ProGuard due to the following warnings stopping the build:

```
Warning: com.mapbox.api.directions.v5.MapboxDirections: can't find referenced class com.sun.xml.internal.ws.spi.db.BindingContextFactory
Warning: com.mapbox.api.directions.v5.MapboxDirections: can't find referenced class com.sun.xml.internal.ws.spi.db.BindingContextFactory
Warning: com.mapbox.api.matching.v5.MapboxMapMatching: can't find referenced class com.sun.xml.internal.ws.spi.db.BindingContextFactory
Warning: com.mapbox.api.matching.v5.MapboxMapMatching: can't find referenced class com.sun.xml.internal.ws.spi.db.BindingContextFactory
```

The problem does not occur with mapbox-android-sdk 6.5.0 and same version of mapbox-sdk-services.

### Configuration

**Android versions:** N/A
**Device models:** N/A
**Mapbox SDK versions:** mapbox-android-sdk 6.6.0 and mapbox-sdk-services 4.0.0

**Comment by tobrun** [comment]
More context in https://github.com/mapbox/mapbox-gl-native/issues/13088, since you are the second person hitting this issue and we can't fix this in `mapbox-sdk-services` , I'm leaning towards fixing it up in this repo instead.

**Comment by tobrun** [comment]
If have reopened the other issue. Closing this in favor of fixing #13088 
Thanks for reporting and using our products @jrgonzalezg!
