### ISSUE TITLE
Can't Implement Interfaces [MapboxMap.OnMyLocationChangeListener]?

### ISSUE THREAD

**Issue by swadallail** [mapbox/mapbox-gl-native#13106]
I have a problem when loading mapbox in Android Studio can not work implements from MapboxMap.OnMyLocationChangeListener And the rest of the things are well.

Part of code problem:-

`public class MainActivity extends AppCompatActivity implements OnMapReadyCallback,MapboxMap.OnMyLocationChangeListener {
   

### Configuration

**Android versions:3.1.4** 
**Mapbox SDK versions:26**

**Comment by tobrun** [comment]
@swadallail OnMyLocationChangeListener hasn't been part of the Maps SDK for a while. 
See https://github.com/mapbox/mapbox-gl-native/pull/11351 for context

**Comment by swadallail** [comment]
> 
> 
> @swadallail OnMyLocationChangeListener hasn't been part of the Maps SDK for a while.
> See #11351 for context

Thank you very much, now I understand

**Comment by swadallail** [comment]
I have a question
how get user location in map and the location updating?

**Comment by tobrun** [comment]
nowadays that is done with the location component. Here are some examples https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location

**Comment by swadallail** [comment]
> 
> 
> nowadays that is done with the location component. Here are some examples https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location

Everything works fine, but there is a mistake that always happens to me when included
import com.mapbox.mapboxsdk.location.LocationComponent;
the error give me:-
cannot resolve symbol 'location'

**Comment by tobrun** [comment]
you are probably not using v6.6.0?

**Comment by swadallail** [comment]
- 

> 
> 
> you are probably not using v6.6.0?

Yes now I changed this and thank you
