### ISSUE TITLE
Expose request interface for FileSource

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native#13126]
The `FileSource` class wraps the core `DefaultFileSource`, but it doesn't expose the actual request interface. On the iOS side, `MGLOfflineStorage` exposes the underlying `DefaultFileSource` object (it's easier of course because no need to cross the JNI bridge). On the iOS side, we don't publicly document the availability of the file source, but we make use of it to write tests that exercise caching behavior. Similar tests on the Android side would currently require writing code to open up the SQLite offline cache to manually check its status.

This came up as part of writing the Android wrapper for a cache-warming API (https://github.com/mapbox/mapbox-gl-native/pull/13119).

cc @tobrun

**Comment by tobrun** [comment]
Leaving this closed as #14119 will remove the filesource from public api
