### ISSUE TITLE
MGLTimeIntervalFromDuration(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> >) 

### ISSUE THREAD

**Issue by sajeel** [mapbox/mapbox-gl-native#13124]
I found a random crash on the iPhone 7 with iOS 11.4, it crashed multiple times , When ever i open the application and goes to map screen it crashed.

Crashed: com.apple.main-thread
0  Mapbox                         0x101e005c0 MGLTimeIntervalFromDuration(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> >) + 972736
1  Mapbox                         0x101cc2ba4 MBGLCustomGeometrySourceOptionsFromDictionary(NSDictionary<NSString*, objc_object*>*) + 31604
2  GLKit                          0x192067970 -[GLKView _display:] + 216
3  Mapbox                         0x101cc3364 MBGLCustomGeometrySourceOptionsFromDictionary(NSDictionary<NSString*, objc_object*>*) + 33588
4  QuartzCore                     0x188a70f4c CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 820
5  IOKit                          0x184c6748c IODispatchCalloutFromCFMessage + 492
6  CoreFoundation                 0x18498cb20 __CFMachPortPerform + 188
7  CoreFoundation                 0x1849a7ae8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
8  CoreFoundation                 0x1849a7230 __CFRunLoopDoSource1 + 440
9  CoreFoundation                 0x1849a4c80 __CFRunLoopRun + 2456
10 CoreFoundation                 0x1848c4da8 CFRunLoopRunSpecific + 552
11 GraphicsServices               0x1868aa020 GSEventRunModal + 100
12 UIKit                          0x18e8e4758 UIApplicationMain + 236
13 TEST                           0x100c867b8 main (main.m:16)
14 libdyld.dylib                  0x184355fc0 start + 4

### Steps to reproduce

 1. Its totally random , it doesnt happen all the time 

[test_issue_14_MB_crash.txt](https://github.com/mapbox/mapbox-gl-native/files/2487335/test_issue_14_MB_crash.txt)
### Configuration

**Mapbox SDK versions:**  4.5.0
**iOS/macOS versions:** iOS 12 and iOS 11.4
**Device/simulator models:** iPhone X and iPhone 7
**Xcode version:** Xcode 10

**Comment by chloekraw** [comment]
@sajeel - thanks for the report. While we were not able to reproduce your exact issue, we investigated and fixed a similar crash which we believe has the same root cause (https://github.com/mapbox/mapbox-gl-native/pull/13367). This is in the latest alpha.2 release and the final release will be out on Dec 19. It'd be great if you could test out the latest version to let us know whether you're still experiencing this crash.
