### ISSUE TITLE
Refactor the number of concurrent http requests when downloading files

### ISSUE THREAD

**Issue by chaupow** [mapbox/mapbox-gl-native#13130]
### Background
Currently, every HTTPFileSource sets the number of maximum concurrent requests with a static function `HTTPFileSource::maximumConcurrentRequests()`.

This function is static and implemented for each platform but most are hardcoded to return `20`:
- default, android, darwin: `20`
- qt: `20`, for older qt versions `10`

With https://github.com/mapbox/mapbox-gl-native/pull/13019 we introduce `OnlineFileSource::getMaximumConcurrentRequests()` to be able to set the number of maximum concurrent requests to write more predictable tests with concurrency set to `1`.

This is a follow-up issue of https://github.com/mapbox/mapbox-gl-native/pull/13019 .

### Proposal

Instead of a static function in `HTTPFileSource` the number of concurrent requests should be a member variable in either `FileSource` or `OnlineFileSource`. The advantages would be

- tests can set the concurrency to 1 more easily
- we can solve: https://github.com/mapbox/mapbox-gl-native/issues/11200
- atm, most platforms are hardcoded to `20` anyways so we could hardcode it in `OnlineFileSource`
- if we want to customize the concurrency, we would probably change the behaviour based on network constraints or mobile vs desktop and not based on platform anyways

### Implementation Sketch
- `HTTPFileSource::maximumConcurrentRequests()` is called in two places in the code:
      - in `OnlineFileSource`: https://github.com/mapbox/mapbox-gl-native/blob/f3341dd589c6330c0cfd6e8e381398d08493b48a/platform/default/online_file_source.cpp#L106
      - in `OfflineDownload`: https://github.com/mapbox/mapbox-gl-native/blob/153acd981b344d7a3963514cfb3241e8cb27ba2d/platform/default/mbgl/storage/offline_download.cpp#L343
- If the `NumberMaximumConcurrentRequest` is a member variable in `OnlineFileSource`, the first call is changeable to read the member variable but `OfflineDownload` only has a `FileSource`. This can be either fixed by
     - having the information of `NumberMaximumConcurrentRequest` in `FileSource` and not only in `OnlineFileSource`. There should be digging into what the abstraction here is and whether there are FileSources that do not need a number of maximum concurrent requests or whether this information makes sense in the design of `FileSource`
     - change `OfflineDownload` that way that it is not initializing a `FileSource` but an `OnlineFileSource`. The way the variable is named hints that the FileSource might be an OnlineFileSource in most (all?) cases anyways: https://github.com/mapbox/mapbox-gl-native/blob/master/platform/default/mbgl/storage/offline_download.hpp#L55

**Comment by ryanhamley** [comment]
I believe this can be closed since #13019 was merged
