### ISSUE TITLE
Cluster items on map

### ISSUE THREAD

**Issue by AlexeyIke** [mapbox/mapbox-gl-native#13143]
Hello, i need to display many items on map and clustering it.  If user touch cluster - i need get all clustered items detail. I've try to seach how do it with simple Marker, and found only old example. I've try to do it with GeoJsonSource - clustering works but impossible to get items on cluster. 
I've see it possible on JS - https://www.mapbox.com/mapbox-gl-js/api#geojsonsource#getclusterchildren 
But still absent on Android - https://github.com/mapbox/mapbox-gl-native/issues/12441 

So, how now i can do clustering with getting all items on cluster? 
Or i need just wait till it be done by 12441  issue?

### Configuration
**Mapbox SDK versions:** 
6.6.0

**Comment by tobrun** [comment]
Hey @Alexeylke, this will be made available with https://github.com/mapbox/mapbox-gl-native/pull/12726, we are aiming for this to land with 6.7.0. This release is aimed to be released in 3 weeks, once the PR landed you can test it out using SNAPSHOT or a alpha/beta release.
