### ISSUE TITLE
Respect user default (NSUserDefaults) for MGLCollisionBehaviorPre4_0 Info.plist key

### ISSUE THREAD

**Issue by samfader** [mapbox/mapbox-gl-native#13155]
This is more of a feature request so I've changed the template around:

### The request
With the `MGLCollisionBehaviorPre4_0` Info.plist key added here (https://github.com/mapbox/mapbox-gl-native/pull/12941), app developers can now set this key to determine cross-source collision behavior. However, there is no way to set this key at the developer level (`NSUserDefaults`).

I know there is some discussion as to why this choice was made [here](https://github.com/mapbox/mapbox-gl-native/pull/12941#discussion_r219728765), but it would be useful to those wrapping the iOS SDK to have a user-controlled option here as well.

**Comment by 1ec5** [comment]
> However, there is no way to set this key at the user level (`NSUserDefaults`).

NSUserDefaults is something of a misnomer. The only practical difference between Info.plist keys and NSUserDefaults settings is that the latter can be set at runtime, whereas the former is static – it can only be set at build time and can’t differ from device to device. With the Info.plist key, a wrapper of this SDK would have no control over the setting.

**Comment by 1ec5** [comment]
Fixed in #13426.
