### ISSUE TITLE
scripts/build-version.py inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by stalkerg** [mapbox/mapbox-gl-native#1315]
About:
  File "scripts/build-version.py", line 16
    ver = re.sub("[^0-9.]", "", sys.argv[2])

Need 8 space. ;)

**Comment by stalkerg** [comment]
And please use #!/usr/bin/env python2.7 not simple python if you write in 2.x style.

**Comment by friedbunny** [comment]
I happened to address this in #1118, but let's do a simple style fix PR...
