### ISSUE TITLE
I failed to compile mapbox-gl-native on android

### ISSUE THREAD

**Issue by leedejun** [mapbox/mapbox-gl-native#13151]
### Steps to reproduce

 1.I followed the mapbox instructions on github to prepare ubuntu16.04's Linux environment and dependencies: https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android
 2.make android-lib-arm-v7
 3.Unfortunately, the compilation failed

### Expected behavior

I expect the compilation to be successful

### Actual behavior

Unfortunately, the compilation failed:

cd platform/android && ./gradlew --parallel --max-workers=1 -Pmapbox.buildtype=debug -Pmapbox.stl=c++_static -Pmapbox.abis=armeabi-v7a :MapboxGLAndroidSDK:assembleDebug
Parallel execution is an incubating feature.

> Task :MapboxGLAndroidSDK:compileDebugJavaWithJavac 
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :MapboxGLAndroidSDK:generateJsonModelDebug 
External native generate JSON debug: starting JSON generation
External native generate JSON debug: using platform version 16 for ABI ARMEABI_V7A and min SDK version 14
External native generate JSON debug: rebuilding JSON /home/lee/work/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/android_gradle_build.json due to:
External native generate JSON debug: - expected json /home/lee/work/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/android_gradle_build.json file is not present, will remove stale json folder
External native generate JSON debug: - missing previous command file /home/lee/work/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/cmake_build_command.txt, will remove stale json folder
External native generate JSON debug: removing stale contents from '/home/lee/work/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a'
External native generate JSON debug: created folder '/home/lee/work/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a'
External native generate JSON debug: executing cmake Executable : /mnt/android-sdk-linux/cmake/3.6.4111459/bin/cmake
arguments : 
-H/home/lee/work/mapbox-gl-native
-B/home/lee/work/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a
-DANDROID_ABI=armeabi-v7a
-DANDROID_PLATFORM=android-16
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/lee/work/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/build/intermediates/cmake/debug/obj/armeabi-v7a
-DCMAKE_BUILD_TYPE=Debug
-DANDROID_NDK=/mnt/android-sdk-linux/ndk-bundle
-DCMAKE_C_FLAGS=-Qunused-arguments
-DCMAKE_CXX_FLAGS=-Qunused-arguments
-DCMAKE_TOOLCHAIN_FILE=/mnt/android-sdk-linux/ndk-bundle/build/cmake/android.toolchain.cmake
-DCMAKE_MAKE_PROGRAM=/mnt/android-sdk-linux/cmake/3.6.4111459/bin/ninja
-GAndroid Gradle - Ninja
-DANDROID_TOOLCHAIN=clang
-DANDROID_STL=c++_static
-DANDROID_CPP_FEATURES=rtti;exceptions
-DMBGL_PLATFORM=android
-DMASON_PLATFORM=android
-DNodeJS_EXECUTABLE=/usr/bin/node
-Dnpm_EXECUTABLE=/usr/bin/npm
-DANDROID_CCACHE=/usr/bin/ccache
jvmArgs : 

-- Check for working CXX compiler: /mnt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
-- Check for working CXX compiler: /mnt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /mnt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /mnt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Updating submodules...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lee/work/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a
External native generate JSON debug: done executing cmake
External native generate JSON debug: write build output /home/lee/work/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/cmake_build_output.txt
External native generate JSON debug: write command file /home/lee/work/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/cmake_build_command.txt
External native generate JSON debug: JSON generation completed without problems

> Task :MapboxGLAndroidSDK:externalNativeBuildDebug 
Build mapbox-gl armeabi-v7a
[1/421] Building CXX object CMakeFiles/icu.dir/vendor/icu/src/ubidiln.cpp.o
[2/421] Building CXX object CMakeFiles/icu.dir/vendor/icu/src/ubidiwrt.cpp.o
[3/421] Building CXX object CMakeFiles/icu.dir/vendor/icu/src/cmemory.cpp.o
[4/421] Building CXX object CMakeFiles/icu.dir/vendor/icu/src/cstring.cpp.o
[5/421] Building CXX object CMakeFiles/icu.dir/vendor/icu/src/ubidi.cpp.o
[6/421] Building CXX object CMakeFiles/icu.dir/vendor/icu/src/ubidi_props.cpp.o
[7/421] Building CXX object CMakeFiles/icu.dir/vendor/icu/src/uchar.cpp.o
[8/421] Building CXX object CMakeFiles/icu.dir/vendor/icu/src/udataswp.cpp.o
[9/421] Building CXX object CMakeFiles/icu.dir/vendor/icu/src/uinvchar.cpp.o
[10/421] Building CXX object CMakeFiles/icu.dir/vendor/icu/src/umath.cpp.o
[11/421] Building CXX object CMakeFiles/icu.dir/vendor/icu/src/ushape.cpp.o
[12/421] Building CXX object CMakeFiles/icu.dir/vendor/icu/src/ustring.cpp.o
[13/421] Building CXX object CMakeFiles/icu.dir/vendor/icu/src/utf_impl.cpp.o
[14/421] Building CXX object CMakeFiles/icu.dir/vendor/icu/src/utrie2.cpp.o
[15/421] Building CXX object CMakeFiles/icu.dir/vendor/icu/src/utypes.cpp.o
[16/421] Building C object CMakeFiles/sqlite.dir/vendor/sqlite/src/sqlite3.c.o
[17/421] Linking CXX static library libicu.a
[18/421] Linking C static library libsqlite.a
[19/421] Building CXX object CMakeFiles/mbgl-core.dir/src/mbgl/programs/collision_box_program.cpp.o
[20/421] Building CXX object CMakeFiles/mbgl-core.dir/src/mbgl/actor/mailbox.cpp.o
FAILED: /home/lee/work/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/launch-cxx /mnt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  --target=armv7-none-linux-androideabi16 --gcc-toolchain=/mnt/android-sdk-linux/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/mnt/android-sdk-linux/ndk-bundle/sysroot  -DMBGL_USE_GLES2=1 -DRAPIDJSON_HAS_STDSTRING=1 -D_GLIBCXX_USE_CXX11_ABI=0 -I../../../../../../../include -I../../../../../../../src -I../../../../../../../mason_packages/headers/geometry/0.9.3/include -I../../../../../../../mason_packages/headers/variant/1.1.4/include -I../../../../../../../mason_packages/headers/unique_resource/cba309e/include -I../../../../../../../mason_packages/headers/rapidjson/1.1.0/include -I../../../../../../../mason_packages/headers/boost/1.65.1/include -I../../../../../../../mason_packages/headers/geojson/0.4.2/include -I../../../../../../../mason_packages/headers/geojsonvt/6.6.1/include -I../../../../../../../mason_packages/headers/supercluster/0.2.2/include -I../../../../../../../mason_packages/headers/kdbush/0.1.1-1/include -I../../../../../../../mason_packages/headers/earcut/0.12.4/include -I../../../../../../../mason_packages/headers/protozero/1.5.2/include -I../../../../../../../mason_packages/headers/polylabel/1.0.3/include -I../../../../../../../mason_packages/headers/wagyu/0.4.3/include -I../../../../../../../mason_packages/headers/shelf-pack/2.1.1/include -I../../../../../../../mason_packages/headers/vector-tile/1.0.2/include -I../../../../../../default -I../../../../../ -I../../../../../../../mason_packages/headers/jni.hpp/4.0.0/include -I../../../../../../../vendor/icu/include -I../../../../../../../vendor/expected/include -isystem /mnt/android-sdk-linux/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem /mnt/android-sdk-linux/ndk-bundle/sources/android/support/include -isystem /mnt/android-sdk-linux/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem /mnt/android-sdk-linux/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -frtti -fexceptions -Qunused-arguments -ftemplate-depth=1024 -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wno-variadic-macros -Wno-unknown-pragmas -Werror -Wno-error=unknown-warning-option -Qunused-arguments -fcolor-diagnostics -ffunction-sections -fdata-sections -O0 -fno-limit-debug-info  -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -std=c++14 -MD -MT CMakeFiles/mbgl-core.dir/src/mbgl/actor/mailbox.cpp.o -MF CMakeFiles/mbgl-core.dir/src/mbgl/actor/mailbox.cpp.o.d -o CMakeFiles/mbgl-core.dir/src/mbgl/actor/mailbox.cpp.o -c /home/lee/work/mapbox-gl-native/src/mbgl/actor/mailbox.cpp
In file included from /home/lee/work/mapbox-gl-native/src/mbgl/actor/mailbox.cpp:1:
In file included from ../../../../../../../include/mbgl/actor/mailbox.hpp:3:
In file included from ../../../../../../../include/mbgl/util/optional.hpp:3:
/mnt/android-sdk-linux/ndk-bundle/sources/cxx-stl/llvm-libc++/include/experimental/optional:11:2: error: "<experimental/optional> has been removed. Use <optional> instead."
#error "<experimental/optional> has been removed. Use <optional> instead."
 ^
In file included from /home/lee/work/mapbox-gl-native/src/mbgl/actor/mailbox.cpp:1:
In file included from ../../../../../../../include/mbgl/actor/mailbox.hpp:3:
../../../../../../../include/mbgl/util/optional.hpp:8:18: error: use of undeclared identifier 'std'
using optional = std::experimental::optional<T>;
                 ^
../../../../../../../include/mbgl/util/optional.hpp:10:19: error: use of undeclared identifier 'std'
using nullopt_t = std::experimental::nullopt_t;
                  ^
../../../../../../../include/mbgl/util/optional.hpp:11:11: error: unknown type name 'nullopt_t'
constexpr nullopt_t nullopt = std::experimental::nullopt;
          ^
../../../../../../../include/mbgl/util/optional.hpp:11:31: error: use of undeclared identifier 'std'
constexpr nullopt_t nullopt = std::experimental::nullopt;
                              ^
In file included from /home/lee/work/mapbox-gl-native/src/mbgl/actor/mailbox.cpp:1:
../../../../../../../include/mbgl/actor/mailbox.hpp:39:5: error: no template named 'optional'
    optional<Scheduler*> scheduler;
    ^
/home/lee/work/mapbox-gl-native/src/mbgl/actor/mailbox.cpp:31:32: error: no matching member function for call to 'shared_from_this'
        (*scheduler)->schedule(shared_from_this());
                               ^~~~~~~~~~~~~~~~
/mnt/android-sdk-linux/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:5340:21: note: candidate function not viable: no known conversion from 'mbgl::Mailbox' to 'std::__ndk1::enable_shared_from_this<mbgl::Mailbox>' for object argument
    shared_ptr<_Tp> shared_from_this()
                    ^
/mnt/android-sdk-linux/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:5343:27: note: candidate function not viable: no known conversion from 'mbgl::Mailbox' to 'const std::__ndk1::enable_shared_from_this<mbgl::Mailbox>' for object argument
    shared_ptr<_Tp const> shared_from_this() const
                          ^
/home/lee/work/mapbox-gl-native/src/mbgl/actor/mailbox.cpp:61:32: error: no matching member function for call to 'shared_from_this'
        (*scheduler)->schedule(shared_from_this());
                               ^~~~~~~~~~~~~~~~
/mnt/android-sdk-linux/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:5340:21: note: candidate function not viable: no known conversion from 'mbgl::Mailbox' to 'std::__ndk1::enable_shared_from_this<mbgl::Mailbox>' for object argument
    shared_ptr<_Tp> shared_from_this()
                    ^
/mnt/android-sdk-linux/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:5343:27: note: candidate function not viable: no known conversion from 'mbgl::Mailbox' to 'const std::__ndk1::enable_shared_from_this<mbgl::Mailbox>' for object argument
    shared_ptr<_Tp const> shared_from_this() const
                          ^
/home/lee/work/mapbox-gl-native/src/mbgl/actor/mailbox.cpp:88:32: error: no matching member function for call to 'shared_from_this'
        (*scheduler)->schedule(shared_from_this());
                               ^~~~~~~~~~~~~~~~
/mnt/android-sdk-linux/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:5340:21: note: candidate function not viable: no known conversion from 'mbgl::Mailbox' to 'std::__ndk1::enable_shared_from_this<mbgl::Mailbox>' for object argument
    shared_ptr<_Tp> shared_from_this()
                    ^
/mnt/android-sdk-linux/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:5343:27: note: candidate function not viable: no known conversion from 'mbgl::Mailbox' to 'const std::__ndk1::enable_shared_from_this<mbgl::Mailbox>' for object argument
    shared_ptr<_Tp const> shared_from_this() const
                          ^
In file included from /home/lee/work/mapbox-gl-native/src/mbgl/actor/mailbox.cpp:1:
../../../../../../../include/mbgl/actor/mailbox.hpp:39:26: error: private field 'scheduler' is not used [-Werror,-Wunused-private-field]
    optional<Scheduler*> scheduler;
                         ^
10 errors generated.

### Configuration

**Android versions:** 
**Device models:** 
**Mapbox SDK versions:** 

It is the latest main branch code.

**Comment by tobrun** [comment]
NDK 18 isn't yet supported, see https://github.com/mapbox/mapbox-gl-native/pull/12972 for reference. Manually downgrading to NDK 17 will fix your issue. Closing as resolved.

**Comment by evgenijkrivelev17** [comment]
Hye. I have a problem.  When I am trying to build realese. I got a problem.
  clang++: error: argument unused during compilation: '-Wa,--noexecstack' [-Werror,-Wunused-command-line-argument]
  FAILED: /Users/alexeykuropov/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv7-none-linux-androideabi --gcc-toolchain=/Users/alexeykuropov/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/alexeykuropov/Library/Android/sdk/ndk-bundle/sysroot  -DMBGL_USE_GLES2=1 -DRAPIDJSON_HAS_STDSTRING=1 -D_GLIBCXX_USE_CXX11_ABI=1 -I../../../../../../../include -I../../../../../../../src -I../../../../../../default/include -I../../../../../include -isystem ../../../../../../../vendor/earcut.hpp/include -isystem ../../../../../../../vendor/eternal/include -isystem ../../../../../../../vendor/expected/include -isystem ../../../../../../../vendor/geojson-vt-cpp/include -isystem ../../../../../../../vendor/kdbush.hpp/include -isystem ../../../../../../../vendor/shelf-pack-cpp/include -isystem ../../../../../../../vendor/supercluster.hpp/include -isystem ../../../../../../../vendor/unique_resource -isystem ../../../../../../../vendor/wagyu/include -isystem ../../../../../../../vendor/boost/include -isystem ../../../../../../../vendor/geojson.hpp/include -isystem ../../../../../../../vendor/geometry.hpp/include -isystem ../../../../../../../vendor/icu/include -isystem ../../../../../../../vendor/polylabel/include -isystem ../../../../../../../vendor/protozero/include -isystem ../../../../../../../vendor/rapidjson/include -isystem ../../../../../../../vendor/variant/include -isystem ../../../../../../../vendor/vector-tile/include -isystem ../../../../../../../vendor/jni.hpp/include -isystem /Users/alexeykuropov/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem /Users/alexeykuropov/Library/Android/sdk/ndk-bundle/sources/android/support/include -isystem /Users/alexeykuropov/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem /Users/alexeykuropov/Library/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=14 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -frtti -fexceptions  -Werror -ftemplate-depth=1024 -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wno-variadic-macros -Wno-unknown-pragmas -Wno-error=unknown-warning-option -ffunction-sections -fdata-sections -Os -DNDEBUG  -Os -DNDEBUG -flto -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -std=c++14 -MD -MT CMakeFiles/mbgl-core.dir/src/mbgl/annotation/annotation_tile.cpp.o -MF CMakeFiles/mbgl-core.dir/src/mbgl/annotation/annotation_tile.cpp.o.d -o CMakeFiles/mbgl-core.dir/src/mbgl/annotation/annotation_tile.cpp.o -c /Users/alexeykuropov/mapbox-gl-native/src/mbgl/annotation/annotation_tile.cpp

**Comment by tobrun** [comment]
Compilation failed due to unused arguments. In our configuration with ccache, we don't hit this issue due to the following construct:
```
                    // Enable ccache if the user has installed it.
                    if (ccache?.trim()) {
                        arguments "-DANDROID_CCACHE=" + ccache
                        // ccache splits up the compile command until multiple invocations and uses -E
                        // with one of them, and clang doesn't like unused arguments in that case.
                        cFlags "-Qunused-arguments"
                        cppFlags "-Qunused-arguments"
                    }
```

Either install and enable ccache or add compiler flags to be used allways.

**Comment by evgenijkrivelev17** [comment]
I have checked. Ccache in the project is empty.
