### ISSUE TITLE
loading style failed: SSL connect error: Unknown SSL protocol error in connection to api.mapbox.com:443 

### ISSUE THREAD

**Issue by leedejun** [mapbox/mapbox-gl-native#13157]
### Steps to reproduce

 1.I successfully compiled mapbox-gl-native on linux(unbuntu 16.04)
 2.make run-glfw-app
 3.The run result is only a black screen.

### Expected behavior

I expect it display streets map.

### Actual behavior
The run result is only a black screen.

[INFO] {mbgl-glfw}[General]: GPU Identifier: llvmpipe (LLVM 6.0, 256 bits)
[ERROR] {mbgl-glfw}[Setup]: loading style failed: SSL connect error: Unknown SSL protocol error in connection to api.mapbox.com:443 

### Configuration

**Android versions:** 
**Device models:** 
**Mapbox SDK versions:** 
The lastest master branch

**Comment by ChrisLoer** [comment]
Seems like maybe wherever you are `api.mapbox.com` isn't resolving to the expected location? What do you get if you try `curl https://api.mapbox.com:443`? Are you accessing from within China?

**Comment by leedejun** [comment]
@ChrisLoer , Thank you lots!

yes , I,m in china now.

sometime mbgl-glfw  can load style successful! It may be caused by the bad state of the network.

so, thank you very much for your help.

And other question: mapbox-gl-native ,how  can  it extend the custom layer, for example, how do it display 3d mode data: .DAE, .DXF, .FBX, .geoTIFF, .glTF data format , etc.

**Comment by ChrisLoer** [comment]
@leedejun OK, sounds like it's probably a network connectivity issue. It might be better to get an access token that allows you to connect to `api.mapbox.cn` inside of China -- you would have to contact Mapbox sales/support for that.

> And other question: mapbox-gl-native ,how can it extend the custom layer, for example, how do it display 3d mode data: .DAE, .DXF, .FBX, .geoTIFF, .glTF data format , etc.

That's a really broad question, and unfortunately we can't provide general support through GitHub issues. The shortest answer I can think of is: (1) try importing the data into vector tiles (maybe using a tool like tippecanoe) and use our "fill-extrusion" layer to display it, or (2) draw 3d items directly into the GL context that the mapbox uses (we don't provide any official support for doing this, and it will be difficult).

**Comment by leedejun** [comment]
@ChrisLoer 

Thank you very much!

I just want to extend a mapbox fuction by modifying the code of mapbox-gl-native, so as to display 3d model data.

Could you give me a direction on how to start implementing this functionality on a mapbox basis?

**Comment by leedejun** [comment]
Hi, @ChrisLoer，

Do you know what coordinate system the mapbox render data is?

**Comment by leedejun** [comment]
I is doing that I want to render the 3d model to the mapbox, the center of the 3d model is (0,0), but its coordinate  in the real world  is longitude and latitude.

**Comment by luoyechendian** [comment]
@leedejun 你好！请问你有解决mapbox添加3D模型支持的功能吗？能否提供代码片段或demo？最近我也在尝试，但因对opengl es了解的不深，未成功。

**Comment by baoluojian123** [comment]
@luoyechendian https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/你看一下官网这个添加3d模型的demo，是否可以帮你解决问题？

**Comment by luoyechendian** [comment]
多谢！有没有Android 环境的？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"bai jian"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月11日(星期三) 上午9:27
收件人:&nbsp;"mapbox/mapbox-gl-native"<mapbox-gl-native@noreply.github.com&gt;;
抄送:&nbsp;"落夜"<993259334@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [mapbox/mapbox-gl-native] loading style failed: SSL connect error: Unknown SSL protocol error in connection to api.mapbox.com:443  (#13157)




@luoyechendian https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/你看一下官网这个添加3d模型的demo，是否可以帮你解决问题？

**Comment by leedejun** [comment]
@luoyechendian 
 hi, I have successfully displayed the. Dae data by modifying the internal code of mapbox gl native.

you could think about that  
https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model

![Uploading image.png…]()
