### ISSUE TITLE
onMapReady isn't called when using non-local styles

### ISSUE THREAD

**Issue by johnwilde** [mapbox/mapbox-gl-native#13159]
The `onMapReady` callback isn't called when using non-local styles and the device has no network connection or cached data.  This makes UI testing difficult when testing a MapView that doesn't define a style like "asset://local_style_file.json"

### Steps to reproduce

 1. Download https://github.com/mapbox/mapbox-android-demo
 2. Run `make sanity-test-example-activities` to generate the UI tests
 3. Disable network on a test device and run a test, e.g.: ` adb shell am instrument -w -r   -e debug false -e class 'com.mapbox.mapboxsdk.testapp.gen.styles.DefaultStyleActivityTest' com.mapbox.mapboxandroiddemo.debug.test/android.support.test.runner.AndroidJUnitRunner`

### Expected behavior
UI test completes successfully.

### Actual behavior
Test fails because `onMapReady` is never called

### Configuration

**Android versions:** 
**Device models:** 
**Mapbox SDK versions:**

**Comment by tobrun** [comment]
Thank you for reaching out and reporting this issue @johnwilde. We hit this issue ourselves and resolved it with using a local style file as you mentioned. We are working to resolve this with a #12219 and #9338.
