### ISSUE TITLE
textHaloBlurTransition doesn't work

### ISSUE THREAD

**Issue by andy-remi** [mapbox/mapbox-gl-native#13154]
### Steps to reproduce

 1. In ClusteringExample.swift of https://github.com/mapbox/ios-sdk-examples
 2. There is a symbol creation code like this(line 71):
```swift
let numbersLayer = MGLSymbolStyleLayer(identifier: "clusteredPortsNumbers", source: source)
....
// And try to add this line:
numbersLayer.textHaloBlurTransition.duration = 0
```
 3. Run and see how the numbers on cluster is disappearing.

### Expected behavior

Fade out of symbol layer should be disabled by "textHaloBlurTransition.duration = 0"

### Actual behavior

But it's not working.

### Configuration

**Mapbox SDK versions:** 
4.5.0

**iOS/macOS versions:** 
iOS 12.0.1

**Device/simulator models:**

iPhone 6

**Xcode version:** 

10.0

**Comment by ChrisLoer** [comment]
Hi @andy-remi, thanks for reporting. `textHaloBlurTransition.duration` controls the animation duration if you change the `text-halo-blur` property, but it doesn't control the collision detection based symbol fade-in/fade-out behavior, which is what you're seeing in this case. There's no way currently to control the collision detection fade duration, although @brunoabinader has started on a PR that allows you to control it globally (but not on a per-layer basis): https://github.com/mapbox/mapbox-gl-native/pull/13035.

**Comment by noblic** [comment]
Hi ChrisLoer, no problem. I wasn't talking about the collision but when you zoom in/out the map, simply the fade out is applied to the symbols all the time no matter they collided each other or not. You can confirm it with the example what I told about. I thought that property is for controlling it but it didn't work..and actually it didn't change anything.

**Comment by andy-remi** [comment]
Hi ChrisLoer, no problem. I wasn't talking about the collision but when you zoom in/out the map, simply the fade out is applied to the symbols all the time no matter they collided each other or not. You can confirm it with the example what I told about. I thought that property is for controlling it but it didn't work..and actually it didn't change anything.

**Comment by andy-remi** [comment]
Actually "numbersLayer.textOpacityTransition.duration = 0" isn't working as well. Anyway thank you!

**Comment by ChrisLoer** [comment]
Yeah, there is no way to directly control the fade duration you're seeing without something like #13035. Sorry I know it's confusing I call it the "collision fade" even though it's not necessarily collision -- it's the same mechanism that's used for fading symbols in and out when tiles are added or removed.

One thing you can experiment is setting the "minzoom" or "maxzoom" of layers so that they disappear immediately when they cross a certain zoom level.
