### ISSUE TITLE
How can I display 3d mode data on map, for example , I need display .dae format data on map

### ISSUE THREAD

**Issue by leedejun** [mapbox/mapbox-gl-native#13166]
### Steps to reproduce

 1.I success compile the mapbox-gl-native code;
 2.Next plan, I want expand a fuction that it can display 3d mode data, the data is common 3d data format, such as , 3D Studio Max (.max, .3ds) AC3D (.AC) Apple 3DMF (.3dm / .3dmf) Autocad (.dwg) Blender (.blend) Caligari Object (.cob) Collada (.dae) Dassault (.3dxml) DEC Object File Format (.off) DirectX 3D Model (.x) Drawing Interchange Format (.dxf) DXF Extensible 3D (.x3d) Form-Z (.fmz) GameExchange2-Mirai (.gof) Google Earth (.kml / .kmz) HOOPS HSF (.hsf) LightWave (.lwo / .lws) Lightwave Motion (.mot) MicroStation (.dgn) Nendo (.ndo) OBJ (.obj) Okino Transfer File Format (.bdf) OpenFlight (.flt) Openinventor (.iv) Pro Engineer (.slp) Radiosity (.radio) Raw Faces (.raw) RenderWare Object (.rwx) Revit (.rvt) Sketchup (.skp) Softimage XSI (.xsi) Stanford PLY (.ply) STEP (.stp) Stereo Litography (.stl) Strata StudioPro (.vis) TrueSpace (.cob) trueSpace (.cob, .scn) Universal (.u3d) VectorWorks (.mcd) VideoScape (.obj) Viewpoint (.vet) VRML (.wrl) Wavefront (.obj) Wings 3D (.wings) X3D Extensible 3D (.x3d) Xfig Export (.fig);
 3. How do I develop a fuction for dispaly 3d mode data.

### Expected behavior

It can display 3d mode in map.

### Actual behavior

It couldn't display 3d mode in map

### Configuration

**Android versions:** 
**Device models:** 
**Mapbox SDK versions:** 
Lastest version

**Comment by ChrisLoer** [comment]
See comment in https://github.com/mapbox/mapbox-gl-native/issues/13157.
