### ISSUE TITLE
please completly  revert java8 support in the Maps SDK 

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-gl-native#13164]
due to this commit https://github.com/mapbox/mapbox-gl-native/commit/990999402caca7e149e44a2ac73694d751ed7bc4

some classes you have already reverted  but we have dx tool error only with 3 classes

after removing lambda expression and static interface inside loggerdefinition dx tool error has gone but we had build issue from source.

for example NativeHttpRequest.java still have lambda expression inside method **executeLocalReques**

https://github.com/mapbox/mapbox-gl-native/blob/af0de6e015e803c33c1d24e25b34bea4778ecd20/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/NativeHttpRequest.java

also MapView.initialiseDrawingSurface:

```
dx tool failed:
WARNING in com.mapbox.mapboxsdk.log.LoggerDefinition.log:(ILjava/lang/String;Ljava/lang/String;)V: 
defining a static interface method requires --min-sdk-version >= 24 (currently 13) for interface methods:
 com.mapbox.mapboxsdk.log.LoggerDefinition.log:(ILjava/lang/String;Ljava/lang/String;)V

Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in 
com.mapbox.mapboxsdk.http.NativeHttpRequest.executeLocalReques:(Ljava/lang/String;)V: 
invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)

Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in 
com.mapbox.mapboxsdk.log.Logger.log:(ILjava/lang/String;Ljava/lang/String;)V: invoking a static 
interface method com.mapbox.mapboxsdk.log.LoggerDefinition.log:(ILjava/lang/String;Ljava
/lang/String;)V strictly requires --min-sdk-version >= 24 (blocked at current API level 13)

Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in 
com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface:(Lcom/mapbox/mapboxsdk
/maps/MapboxMapOptions;)V: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 
(currently 13)
3 errors; aborting
```

**Comment by tobrun** [comment]
This request has already been covered in https://github.com/mapbox/mapbox-gl-native/issues/12637 and we are aiming to pick this up with the next major release of v7.0.0. Thank you for reaching out but closing as a duplicate.
