### ISSUE TITLE
MKTileOverlay

### ISSUE THREAD

**Issue by robipresotto** [mapbox/mapbox-gl-native#1316]
Plans to implement something like that? [MKTileOverlay Documentation] (https://developer.apple.com/library/prerelease/ios/documentation/MapKit/Reference/MKTileOverlay_class/index.html)

**Comment by incanus** [comment]
Closest thing would be more like https://github.com/mapbox/mapbox-gl-native/issues/836 tile source bridge to carry over from our raster SDK. The preferred way to bring in raster tiles is going to be a TileJSON URL (or `mapbox://` shorthand) in a style's `sources` which then pulls tiles from a server.
