### ISSUE TITLE
Refactor iosapp to remove/reorganize debug cases

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#13162]
We've accumulated a wide variety of debug code in iosapp over the years, much of which is no longer relevant or well-used. Where desirable, we should:

- Move blocks of code out into tests.
- Move remaining non-global groups of code (think DDS) into their own separate view controllers.
- Make globally-useful debug options accessible from any view controller. (Think map info hud, core debug options.)

**Comment by julianrex** [comment]
Closing as a stagnant issue.
