### ISSUE TITLE
Review caching heuristics following gesture recognition overhaul

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1317]
After the gesture recognition overhaul lands in #1292, we should revisit any caching heuristics added in #1281 that were based on the current panning and zooming behavior. The new behavior tends to take the user into neighboring tiles much more easily and quickly, so there will be a tendency to load more tiles than there is now.

/cc @ansis @incanus

**Comment by incanus** [comment]
I'm feeling pretty good about things right now and gestures have been in for a while. Let's close for now and revisit if we have any concrete issues.
