### ISSUE TITLE
Make double-tap-drag work like it does in Google Maps

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1319]
When I showed #1292 to @heyitsgarrett, the first thing he tried was a double-tap-drag gesture that allows you to zoom the map in and out with one finger. `MKMapView` doesn’t support this gesture, but Google Maps does. To my surprise, so does `MGLMapView`, apparently as a side effect of #1296. Unfortunately, our behavior isn’t quite the same as Google’s, and the differences are unintuitive:

- [ ] We only recognize the gesture if you double-tap, _hold_, then drag vertically – Google Maps doesn’t require a hold
- [ ] Dragging upwards zooms in while dragging downwards zooms out – the opposite of Google Maps

**Comment by friedbunny** [comment]
Hrm, I seem to recall reading that this intentionally added by @incanus. Either way, I like the feature but it does lack discoverability (e.g., I had no idea Google Maps had this). Agree that the additional hold is unnecessary from a usability standpoint, Goog's feels good to me

**Comment by ajashton** [comment]
> it does lack discoverability

On the Android side of things this is more common/known I think. Nearly all Google apps have it as an alternate gesture to pinch-zooming (photos, email, chrome, docs).

**Comment by 1ec5** [comment]
Yes, this is a Googleism – a handy one, because you can zoom out with one finger. I was surprised to see it half-work in here; we should either recognize it the way Google Maps users expect or not support it at all.

**Comment by 1ec5** [comment]
> Hrm, I seem to recall reading that this intentionally added by @incanus.

Indeed, it was implemented as `UILongPressGestureRecognizer` requiring [one tap and a quarter-second hold](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/MGLMapView.mm#L361) in mapbox/mapbox-gl-cocoa@86e9aadf4bfca9073d5d6f04b882e2d03761d934. We could nix or reduce the required hold duration, though that might introduce ambiguity with other gesture recognizers.

**Comment by incanus** [comment]
Yeah, I carried this over from our iOS SDK: https://github.com/mapbox/mapbox-ios-sdk/issues/184

I think a long press gesture which requires two taps should be fine. We can nix the delay. We don't otherwise use the double-tap so I don't think it will interfere or will be easily resolved. It'll still be a long press, though, because combining a tap and a drag is tricky otherwise.

**Comment by incanus** [comment]
To be clear, we have enough relatively major gesture tuning going on (https://github.com/mapbox/mapbox-gl-native/pull/1296, https://github.com/mapbox/mapbox-gl-native/pull/1292) that we should probably wait on this until b2.

**Comment by ljbade** [comment]
Making a note that any improvements to touch handling on iOS should also be eventually ported to Android in the big clean up needed in https://github.com/mapbox/mapbox-gl-native/issues/553

**Comment by friedbunny** [comment]
Fixed back in #2153.

**Comment by heyitsgarrett** [comment]
:smile:

**Comment by 1ec5** [comment]
Apparently MapKit in iOS 11 introduces a quick-zoom gesture that zooms in while dragging upwards, like how we implemented it originally but unlike Google Maps and our current implementation. Call it _natural zooming_, if you will. 🤷‍♂️
