### ISSUE TITLE
Backgrounding the app defeats caching

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1320]
If you send the host app to the background and bring it back to the foreground, all visible tiles are forcibly reloaded, HTTP requests and all. At best, the entire map appears to flash in and out. At worst, tiles go AWOL until they’re refetched and rerendered.

`Source::update()` calls `addTile()`, which creates a new `VectorTileData` and calls `TileData::request()` because the cache introduced in #1255 is empty. It might be worth noting that backgrounding and foregrounding the app causes `Map::stop()` and `start()` to be called, respectively.

/cc @ansis @incanus

**Comment by jfirebaugh** [comment]
Not sure of the current status, but on the `1065-separate-ui-from-map-thread` branch, `Map::stop()` shuts down the rendering thread completely, which basically deallocates _everything_.

I'm not sure anyone understands the current backgrounding/foregrounding strategy. I've never been able to get anyone to write up an explanation anyway.

**Comment by 1ec5** [comment]
ref #1065

**Comment by incanus** [comment]
> I'm not sure anyone understands the current backgrounding/foregrounding strategy. I've never been able to get anyone to write up an explanation anyway.

I think @kkaefer might, and I know much of this is complicated by various orders of things happening between iOS and Android for these sequences.

**Comment by jfirebaugh** [comment]
ref #678

**Comment by jfirebaugh** [comment]
Fixed in #1065.
