### ISSUE TITLE
app crash on startup DYLD, Symbol not found referenced from Polyline.framework/Polyline

### ISSUE THREAD

**Issue by Xgamefactory** [mapbox/mapbox-gl-native#13216]
`Termination Description: DYLD, Symbol not found: __T0SSN | Referenced from: /private/var/containers/Bundle/Application/A086D94F-5242-4BC3-97DA-4ABC244690AE/test.app/Frameworks/Polyline.framework/Polyline | Expected in: /private/var/containers/Bundle/Application/A086D94F-5242-4BC3-97DA-4ABC244690AE/test.app/Frameworks/libswiftCore.dylib | in /private/var/containers/Bundle/Application/A086D94F-5242-4BC3-97DA-4ABC244690AE/test.app/Frameworks/Polyline.framework/Polyline`

**Comment by LukasPaczos** [comment]
As mentioned before, we are not providing support for building from source. Also, when reporting an issue, please follow the template and provide necessary information, we are unable to pinpoint the issue otherwise.

**Comment by Xgamefactory** [comment]
this has nothing related to build from source.  thi is original mapbox navigation sdk build.
