### ISSUE TITLE
MGLLineStyleLayer - Gap Line(s) intersect when angled less than 90º

### ISSUE THREAD

**Issue by riastrad** [mapbox/mapbox-gl-native#13227]
On iOS using MGLLineStyleLayer, when setting the `.lineGapWidth` attribute, you would expect that the gap line that's generated would not intersect. However, if the Polyline you are styling has angles that are less than 90º these lines intersect.

### Steps to reproduce

 1. Create a polyline with angles that  < 90º
 2. Style the line using the `line-gap-width` property
 3. Observe that the line gap intersects

### Expected behavior

As this is property is often used to generate an 'outline' of a Polyline feature, it would be expected that the exterior lines would not intersect. Here's how a line gap is rendered on other GIS software:

![line-gap](https://user-images.githubusercontent.com/16272584/47680742-1e08a980-db9e-11e8-832d-41e36beac602.png)

### Actual behavior

You get intersecting lines:

**iOS Maps SDK**
<img width="950" alt="screen shot 2018-10-29 at 4 52 38 pm" src="https://user-images.githubusercontent.com/16272584/47680553-7e4b1b80-db9d-11e8-9917-6775695c4392.png">

**Mapbox GL JS**
<img width="1199" alt="screen shot 2018-10-29 at 5 05 13 pm" src="https://user-images.githubusercontent.com/16272584/47680561-83a86600-db9d-11e8-9e99-ef18ad6ec7ac.png">

### Configuration

I've confirmed this behavior in both the iOS Maps SDK v4.5.0 and Mapbox GL JS v0.50.0

**Comment by chloekraw** [comment]
@mourner would this issue be fixed by https://github.com/mapbox/mapbox-gl-js/pull/8275, and was it / will it be ported to -native?

**Comment by mourner** [comment]
@chloekraw no, this seems like an unrelated issue.
