### ISSUE TITLE
Option to disable location tracking animation

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#13225]
@LukasPaczos commented on [Tue Jul 03 2018](https://github.com/mapbox/mapbox-plugins-android/issues/567)

We are hearing voices that smooth tracking animation puts a real stress on the battery consumption, CPU usage and introduces a delay. In order to improve the experience on lower-end devices, we could expose an option to disable the smooth animation.

/cc @danesfeder 

---

@LukasPaczos commented on [Tue Aug 28 2018](https://github.com/mapbox/mapbox-plugins-android/issues/567#issuecomment-416581358)

Unfortunately, because of the async rendering, disabling animations won't be feasible at this point as we are out of sync when updating the location source and the camera position at the same time.

![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/16925074/44725526-c71b2100-aad5-11e8-827b-c17217f4b927.gif)

The work to unblock this use case is tracked in https://github.com/mapbox/mapbox-gl-native/issues/12752.

**Comment by maxtracking** [comment]
Hello, 

What's happening with this issue? In our project location component animations put TREMENDOUS stress on CPU to the extent of abandoning LocationComponent and reinventing the wheel ourselves :(

Alex

**Comment by zugaldia** [comment]
My understanding from OP is that we're waiting for https://github.com/mapbox/mapbox-gl-native/issues/12752 to be added to our core rendering library, before being able to add the Android-side option. @LukasPaczos please correct me if I'm wrong.

/cc: @tmpsantos

**Comment by LukasPaczos** [comment]
This is correct @zugaldia.

@maxtracking as a stopgap solution, you can throttle the component's animation frames output via [`LocationComponentt#setMaxAnimationFps`](https://docs.mapbox.com/android/api/map-sdk/7.2.0/com/mapbox/mapboxsdk/location/LocationComponent.html#setMaxAnimationFps-int-) as shown in https://github.com/mapbox/mapbox-gl-native/pull/13678 or throttle the whole Map's FPS output when tracking the location via [`MapView#setMaximumFps`](https://docs.mapbox.com/android/api/map-sdk/7.2.0/com/mapbox/mapboxsdk/maps/MapView.html#setMaximumFps-int-). We've seen great results in our [Navigation SDK](https://docs.mapbox.com/android/navigation/overview/) after implementing both of above.

**Comment by maxtracking** [comment]
Thanks a lot, @LukasPaczos, I'll certainly try the one for MapView. We had to switch to the custom layer for user's location anyway due to the complexity of linked layers but MapView fps are under scrutiny now :)

**Comment by jimmyjzemoso** [comment]
Hey @LukasPaczos I can see an expanding animation in Ios current location marker. Is it something that I can enable in android as well??

**Comment by LukasPaczos** [comment]
@jimmyjzemoso we have a similar feature coming, see https://github.com/mapbox/mapbox-gl-native/pull/13942.

**Comment by JonasDaWi** [comment]
Hi! It would also be great to have an option to disable the location's rotation component or at least make its animation much faster. I'm using forceLocationUpdate with a bearing and the rotation indicator animation is much slower than the tracking animation.
