### ISSUE TITLE
Mapbox tiles not visible

### ISSUE THREAD

**Issue by baptistae** [mapbox/mapbox-gl-native#13230]
Hi
I have successfully uploaded a raster tile, but when I add the tile in the Style, I received a message saying "this tileset isnt visible from your map view". How can I fix this? 

Thanks

Kind regards,

Elizabeth

### Steps to reproduce

 1.
 2.
 3.

### Configuration

**Mapbox SDK versions:** 
**iOS/macOS versions:** 
**Device/simulator models:**
**Xcode version:**

**Comment by ryanhamley** [comment]
Hi @baptistae thanks for using Mapbox. You unfortunately have not provided enough information for us to diagnose an issue. You may want to reference our [Blank or missing map tiles](https://www.mapbox.com/help/blank-tiles/) troubleshooting page or contact our excellent [support team](https://www.mapbox.com/contact/support/) directly. Please note that this issue tracker is reserved for reporting bugs and requesting new features.
