### ISSUE TITLE
load offline maps 

### ISSUE THREAD

**Issue by sassiwalid** [mapbox/mapbox-gl-native#13241]
Hi, I tried to load packs and show the map offline that I downloaded. In the documentation, I didn't find how to do!!!! if there is anyone who can help me please.  I wrote this code to copy the cache.db from the 
/Library/Application Support/**********/.mapbox/cache.db to the new folder that I created under Documents/************/MapBoxCache this the code but the offline map is not showing : 

```
let sourceURL = NSURL(fileURLWithPath:"\(NSHomeDirectory())/Library/Application Support/********************/.mapbox/cache.db")
        let TemporaryPathURL = NSURL(fileURLWithPath: "\(NSHomeDirectory())/Documents/EasyMountainFiles/MapBoxCache")
        let mapBoxPathFolder = "\(NSHomeDirectory())/Documents/**********/MapBoxCache"
        var isDirectory : ObjCBool = true
        do {
            if (!FileManager.default.fileExists(atPath: mapBoxPathFolder, isDirectory: &isDirectory)) {
                try FileManager.default.createDirectory(atPath: mapBoxPathFolder, withIntermediateDirectories: true, attributes: nil)
            }
        } catch {
        }
        let databaseURL = TemporaryPathURL.appendingPathComponent("cache.db")
        if !(FileManager.default.fileExists(atPath: (databaseURL?.absoluteString)!)) {
            do {
                try? FileManager.default.copyItem(at: sourceURL as URL, to: databaseURL!)
            } catch {
                print ("ERROR: Fichier existant !!!!")
            }
        }
        MGLOfflineStorage.shared.addContents(of: databaseURL!, withCompletionHandler: nil)
```

### Configuration
**Mapbox SDK versions:** 
**iOS versions:12
**Xcode version:xcode 9.4

**Comment by asheemmamoowala** [comment]
@sassiwalid This is documented in the wiki under [Sideloading offline maps](https://github.com/mapbox/mapbox-gl-native/wiki/Sideloading-offline-maps).

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
