### ISSUE TITLE
[android] Release maps sdk patch with libtelemetry 3.5.2

### ISSUE THREAD

**Issue by andrlee** [mapbox/mapbox-gl-native#13257]
libtelemetry 3.5.2 includes important fixes for:
https://github.com/mapbox/mapbox-events-android/issues/146
https://github.com/mapbox/mapbox-events-android/issues/201

/cc @zugaldia @tobrun @LukasPaczos

**Comment by electrostat** [comment]
`Mapbox-Android-Telemetry-3.5.2` is released and ready to go on Maven: https://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-telemetry/3.5.2/

**Comment by tobrun** [comment]
Done with #13260
