### ISSUE TITLE
Error targeting MIPS ABI

### ISSUE THREAD

**Issue by kidandcat** [mapbox/mapbox-gl-native#13263]
I'm getting an error because mapbox is trying to use MIPS ABI, and it has been retired in Android NDK, Revision r17c (June 2018):

Support for ARMv5 (armeabi), MIPS, and MIPS64 has been removed. Attempting to build any of these ABIs will result in an error.

am I wrong? is any work already in progress to fix this?

I finally could make the build, but I needed to copy an older toolchain manually into the NDK bundle.

### Steps to reproduce

 1. Download and install the latest version of Android NDK
 2. Use this package and compile an app

### Expected behavior

Compile without problem

### Actual behavior

Error due to: Support for ARMv5 (armeabi), MIPS, and MIPS64 has been removed. Attempting to build any of these ABIs will result in an error.

**Comment by tobrun** [comment]
> am I wrong?

You are correct NDK has removed support for these ABIs

> is any work already in progress to fix this?

There is nothing to fix from our end, these ABIs are not longer supported by Google and as result not by us. 

> Download and install the latest version of Android NDK

The latest NDK doesn't work yet with our SDK, see https://github.com/mapbox/mapbox-gl-native/pull/12972


Closing this issue as this is not actionable for us, @kidandcat would love to hear more about your use-case and what you are trying to achieve.
