### ISSUE TITLE
Problems with two fragments with MapView on Android 6.0 Marshmallow

### ISSUE THREAD

**Issue by GlebSviripa** [mapbox/mapbox-gl-native#13264]
### Steps to reproduce

 1.Show first fragment containing MapView
 2.Add marker on map
 3.Show second fragment containing MapView

### Expected behavior
Second fragment should show new instance of map without markers from previous fragment

### Actual behavior
Map on second fragment show marker from previous fragment

First fragment
![image](https://user-images.githubusercontent.com/4890162/47914048-d5efcc80-dea6-11e8-84a1-4fad82ea13ac.png)

Second fragment
![image](https://user-images.githubusercontent.com/4890162/47914143-3252ec00-dea7-11e8-811c-e234858775ad.png)

### Configuration

**Android versions:** 6.0 Marshmallow
**Device models:** Google Nexus 5, Xiaomi Redmi Note 4
**Mapbox SDK version:** mapbox-android-sdk:6.6.1

**Comment by tobrun** [comment]
@GlebSviripa issue stems from using GLSurfaceView as rendering surface. Overlain them isn't supported. This use-case should be handled with TextureView instead. You can enable this feature either with attributes (`mapbox_renderTextureMode=true`) or in code with `MapboxMapOptions#textureMode(true)`.

**Comment by GlebSviripa** [comment]
Thanks. Now it works well
