### ISSUE TITLE
mbgl-offline should provide command line parameter to provide metadata

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#13275]
We should add a parameter to `mbgl-offline` to offer a way to set a context (binary) blob for an offline region, perhaps `--metadata <file>`. Ideally it would support reading from stdin.

EDIT: See https://github.com/mapbox/mapbox-gl-native/issues/13314#issuecomment-439934083 for an additional idea of adding the content type for the blob.

**Comment by 1ec5** [comment]
This would require rewriting the tool in Objective-C: https://github.com/mapbox/mapbox-gl-native/issues/13314#issuecomment-437110648.
