### ISSUE TITLE
[android] Bring Telem SDK v3.5.2 to release `horchata`

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#13280]
With https://github.com/mapbox/mapbox-gl-native/issues/13257 we brought the latest stable Telem SDK v3.x to release `gazpacho`. We should do the same update to the upcoming release.

/cc: @mapbox/maps-android @andrlee

**Comment by andrlee** [comment]
@zugaldia what is the likelihood we could integrate Telem SDK `3.5.3` which we plan to release today? This patch version is going to address issues with `Context` completely.

**Comment by zugaldia** [comment]
Per chat, we'll launch v3.5.2 with `horchata` and include v3.5.3 in a future patch release once we have a chance to integrate it with a QA cycle.
