### ISSUE TITLE
Custom Annotation

### ISSUE THREAD

**Issue by crazyBoat** [mapbox/mapbox-gl-native#1330]
Hello Guys,

Amazing work!
I'm trying to implement a small custom annotation (image annotation) but the api don't have annotation view... someone can explain me the best way to start implementing it?

**Comment by friedbunny** [comment]
As you noticed, annotations are still a big work in progress and annotations/markers are currently [hardcoded to a single `default_marker`](https://github.com/mapbox/mapbox-gl-native/blob/0e8b496d317abab1fc810693c2bc770ed3989a0e/platform/ios/MGLMapView.mm#L50). Support for various types of custom annotations is definitely coming, though, it's just a matter of time.

Thanks for your interest!

**Comment by mikezucc** [comment]
is there a hack that can be done in the immediate time frame on developer side to provide run time defined sprite sheets?
