### ISSUE TITLE
Mapbox Localization plugin does not work when setting style

### ISSUE THREAD

**Issue by diegolaballos** [mapbox/mapbox-gl-native#13303]
I've tested with the Mapbox plugins app, the one that shows how to use all the plugins. The localization works fine until I set a custom style : mapView.setStyleUrl("http://mystyle")

### Steps to reproduce

 1. Clone Mapbox plugins app
 2. Add a custom style to the LocalizationActivity
 3. Try to change the language

### Expected behavior
It should change the language and it works before adding a custom style

### Actual behavior
It ignores the new language

### Configuration

**Mapbox Localization plugin: 0.5.0 **

**Comment by asheemmamoowala** [comment]
@diegolaballos Thank you for using Mapbox! Issues with the localization plugin should be logged in the https://github.com/mapbox/mapbox-plugins-android/ repo.

This issue tracker is for reporting bugs and feature requests for the core renderer and the platform  SDKs, but not plugins.
