### ISSUE TITLE
Possible regression of `MGLShapeSource.features(matching predicate: NSPredicate?)` returns 0 features

### ISSUE THREAD

**Issue by kestred** [mapbox/mapbox-gl-native#13316]
Querying for features using `source.features(matching: nil)` (or anything else) returns `0` features.
This seems like a regression of https://github.com/mapbox/mapbox-gl-native/issues/9767, but presumably it could also be me not using the library correctly, _because Swift_.

### Steps to reproduce
Given some features constructed like so....
```swift
/// somewhere above
let points = lineString.asCoordinates
let feature = MGLPolylineFeature(coordinates: points, count: UInt(points.count))
feature.attributes["featureType"] = self.featureType
for attr in self.featureAttributes {
    feature.attributes[attr.name] = attr.value
}
print("Feature(\(feature.id)): \(feature.attributes)")
```

And source created like so...
```swift
let source = MGLShapeSource(identifier: "network", features: features, options: nil)
```

Add them to the map some long time after `didFinishLoading`
```swift
if let mapStyle = mapView.style {
    mapStyle.addSource(source)
    for layer in layers.values {
        mapStyle.addLayer(layer)

        if let style = layer as? MGLVectorStyleLayer {
            let collection = (source.shape as! MGLShapeCollectionFeature)
            print("Predicate for \(layer.identifier): \(style.predicate)")
            print("Matching features for \(layer.identifier): \(source.features(matching: style.predicate).count) " +
                  "of \(source.features(matching: nil).count) or \(collection.shapes.count)")
        }
    }
}
```

### Expected behavior
It returns more than 0 features.

### Actual behavior
It returns 0 features.

**Log Output:**
```
Feature(lofeature_Krg4rQm6CyQySqmNWL5C9Z): ["featureType": "FiberCable", "measured_length": "5130", "placement": "Underground"]
...
Predicate for Cable (Other): Optional(featureType == "FiberCable")
Matching features for Cable (Other): 0 of 0 or 3775
```

### Configuration
**Mapbox SDK versions:** 4.6.0
**iOS/macOS versions:** iOS 12.1
**Device/simulator models:** iPhone XR, SimulatorApp-877 CoreSimulator-581.2
**Xcode version:** 10.1

**Comment by 1ec5** [comment]
It looks like you’re querying the source layer immediately, synchronously, after adding the source to the style. Other feature querying methods like `MGLVectorTileSource.features(matching:)` only return features in tiles that have already loaded for display in a style layer, which means there would need to be time for a network request and response. This is a shape source, so a network request wouldn’t be necessary, but the interface might still be asynchronous. Can you try querying after a delay?

**Comment by kestred** [comment]
@AlJaMa: ^  (when you have time)


@1ec5: as additional information, this further presents itself in having _no features visible_ on the map.  
By instead using `MGLMapViewDelegate`'s  `____ColorForShapeAnnotation`, the features appear but can't be styled as expected via a Mapbox Style document (I think we might also be adding the shapes differently .

__With the additional context__, are there any other debugging steps / information you might recommend to see what my be the cause of the issue we're experiencing?  
I'll try the querying after a delay to see if that error is a red herring.
