### ISSUE TITLE
Camera animation which cannot be interrupted

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#13319]
On my mapview I have different points of interests for the user, that can be clicked. When clicked, the camera will fly to these positions. Currently the user has the possibility to interrupt this animation by simply touching the mapview canvas (this implementation is default behavior, correct?). It actually happens a lot that the user touches the canvas by accident which forces the user to click that POI again to continue the animation. 

One possible workaround is to disable all possible map touch events which seems quite hacky in my opinion (but maybe the only easy one?). I know that you also provide a "move" method for this usecase, but an animation looks much better to the user (and also provides a better feeling of where the POI is located on the map).

I hope this feature request is helpful. Let me know if you have any questions.

PS: I might create some more feature requests in the next days, because of the current 7.0 development. :)

**Comment by asheemmamoowala** [comment]
@Mordag thank you for using Mapbox-GL. From your question it is not clear what platform you are using. In the future, please try to fill out all the fields in the issue track er templates. 

> One possible workaround is to disable all possible map touch events which seems quite hacky in my opinion (but maybe the only easy one?). 

This is the recommended approach. See https://github.com/mapbox/mapbox-gl-native/issues/9172 for more information on how to use it.
