### ISSUE TITLE
Allow usage of multiple access tokens

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-gl-native#13311]
It would be nice to add more flexibility to token management in the Maps SDKs for Android and iOS. More specifically, the ability to switch tokens in order to use multiple Mapbox products with one another.  

The current use case that this could solve is using China `.cn` products with `.com` products. Mapbox China map styles require a special China access token, but a China token can't load a global style such as `Satellite Streets`. I'd like to be able to load the China tiles with a China access token and then use a global/`.com` access token to load Satellite Streets when I click a `toggle style` button. Right now, the `Mapbox` singleton object will continue to use the China token for all API calls because that was the first token used.

cc @chriswu42 @suntony @springmeyer  @Chaoba @lloydsheng @jmkiley

**Comment by tobrun** [comment]
Adding this to 7.0 as this could potentially impact public API

**Comment by springmeyer** [comment]
> in the Maps SDKs for Android and iOS. 

Re-opening: Is there a plan for iOS? My opinion is that we need parity for this feature to be viable.

**Comment by tobrun** [comment]
Updating the labels to reflect above

**Comment by jmkiley** [comment]
On the iOS side, [`accessToken`](https://www.mapbox.com/ios-sdk/api/maps/4.6.0/Classes/MGLAccountManager.html#/c:objc(cs)MGLAccountManager(cpy)accessToken) is already exposed and can be set programmatically. However, I'm not sure about how this behaves with multiple access tokens. Will investigate.

**Comment by jmkiley** [comment]
:wave: Looks like this already works on iOS. However, we do run into an obstacle with switching the `MGLMapboxAPIBaseURL`, since that is set in the Info.plist. I have opened a ticket to discuss this feature: https://github.com/mapbox/mapbox-gl-native/issues/13605

**Comment by tobrun** [comment]
since iOS is covered on this feature request and we have ticketed out tail work. Going to close this on out.
