### ISSUE TITLE
How can I use MGLSymbolStyleLayer  to show a remote image with .pbf source

### ISSUE THREAD

**Issue by aio-ani** [mapbox/mapbox-gl-native#13315]
### Steps to reproduce

 1.
 2.
 3.

### Configuration

**Mapbox SDK versions:**  mac os 10.14
**iOS/macOS versions:** ios 9.0
**Device/simulator models:** iphone 6s
**Xcode version:**  xcode 10.1

**Comment by aio-ani** [comment]
now my  code is follows:

        let symLayer = MGLSymbolStyleLayer(identifier: "\(sourceLayerIden)-icon", source: source)
        symLayer.sourceLayerIdentifier = sourceLayerIden
        symLayer.iconImageName = NSExpression(forKeyPath: "image-normal")
//        symLayer.iconImageName = NSExpression(forConstantValue: "camera")
        symLayer.iconOpacity = NSExpression(forConstantValue: 1.0)
        symLayer.iconColor = NSExpression(forConstantValue: UIColor.black)
        symLayer.iconAllowsOverlap = NSExpression(forConstantValue: false)
        symLayer.iconScale = NSExpression(forConstantValue: 1.0)
        map.style?.addLayer(symLayer)
        styleLayers.append(symLayer)

     the local image can be showed,but when change the code to ' symLayer.iconImageName = NSExpression(forKeyPath: "image-normal") ' ,the map cannot show the image

**Comment by aio-ani** [comment]
now my  code is follows:

        let symLayer = MGLSymbolStyleLayer(identifier: "\(sourceLayerIden)-icon", source: source)
        symLayer.sourceLayerIdentifier = sourceLayerIden
        symLayer.iconImageName = NSExpression(forKeyPath: "image-normal")
        symLayer.iconOpacity = NSExpression(forConstantValue: 1.0)
        symLayer.iconColor = NSExpression(forConstantValue: UIColor.black)
        symLayer.iconAllowsOverlap = NSExpression(forConstantValue: false)
        symLayer.iconScale = NSExpression(forConstantValue: 1.0)
        map.style?.addLayer(symLayer)
        styleLayers.append(symLayer)

The local image can be showed,but when change the code to ' symLayer.iconImageName = NSExpression(forKeyPath: "image-normal") ' ,the map cannot show the image

**Comment by 1ec5** [comment]
`MGLSymbolStyleLayer.iconImageName` needs to evaluate to the name of an image that is added to the style using `MGLStyle.setImage(_:forName:)`. The image has to be a UIImage (on iOS) or NSImage (on macOS). If the image you want to show on the map is located on a remote server, you’ll need to download the image, for example using `Data(contentsOf:options:)`, convert the downloaded data into a UIImage using `UIImage(data:)`, then add it to the style using `MGLStyle.setImage(_:forName:)`.

**Comment by aio-ani** [comment]
> `MGLSymbolStyleLayer.iconImageName` needs to evaluate to the name of an image that is added to the style using `MGLStyle.setImage(_:forName:)`. The image has to be a UIImage (on iOS) or NSImage (on macOS). If the image you want to show on the map is located on a remote server, you’ll need to download the image, for example using `Data(contentsOf:options:)`, convert the downloaded data into a UIImage using `UIImage(data:)`, then add it to the style using `MGLStyle.setImage(_:forName:)`.

I find that i have not load my custom style ,so the map cannot find the icon,then it shows nothing on the map.

By the way i have another error :  Failed to load glyph range 39936-40191 for font stack Open Sans,Arial Unicode MS: HTTP status code 404   , how can i deal with it.


Thanks very much for your reply. &

**Comment by julianrex** [comment]
@aio-ani if you still require support or assistance, please reach out to our support team at
https://support.mapbox.com.

**Comment by aio-ani** [comment]
> @aio-ani if you still require support or assistance, please reach out to our support team at
> https://support.mapbox.com.

I have solved the issue.thanks for yours replies.Best wishes to yours.
