### ISSUE TITLE
Consider adding mbgl-offline executable to iOS releases

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#13314]
As we continue to improve support for sideloading offline databases, we should consider bundling `mbgl-offline` with our iOS releases.

**Comment by 1ec5** [comment]
mbgl-offline is written in cross-platform C++, so it’s incapable of providing offline region metadata that iOS applications can read using NSKeyedArchiver (as is customary). The only benefit of mbgl-offline over Mapbox GL.app, which is bundled with the macOS map SDK, is that it can be automated. We could add AppleScript scriptability or command line option handling to Mapbox GL.app.

**Comment by julianrex** [comment]
Re metadata - see also https://github.com/mapbox/mapbox-gl-native/issues/13275

**Comment by asheemmamoowala** [comment]
> We could add AppleScript scriptability or command line option handling to Mapbox GL.app.

I always assumed that it is up to the client to determine what/how that metadata would be encoding   into the region. If that is the case, any built-in tools we provide will need some customization to be used. Even more so, with sideloading support, packs created on macOS may be downloaded to non-darwin platforms, and would have to build support for decoding  the metadata appropriately.
Maybe a default cross-platfrom encoding method ( UTF-8 string perhaps) can be used in the off-the-shelf tooling we provide, and developers can swap it with their own at runtime.

**Comment by 1ec5** [comment]
> would a base64 encoded string address the security concern? I see built-in functions in [NSData](https://developer.apple.com/documentation/foundation/nsdata?language=objc) and NSString.

Given an arbitrary binary blob, an application may be able to interpret it as a string without crashing or generating an error, but that doesn’t guarantee that a string is the correct interpretation. The fact that this is a binary blob means we allow it to contain anything. As soon as we start assigning meaning to the blob, that’s a good argument for a separate, more strongly typed column…

> Another way to do this might be to provide an additional `varchar` column in the database for a `name` or `title`.

This is getting pretty far off-topic, but I think a more strongly-typed column would be a very positive improvement to the schema; it seems pretty clear to me that the name is the main thing people use the metadata field for. For the other kinds of metadata a developer might want to include (which they can currently stuff in the dictionary that gets archived), we could add a column for that dictionary encoded as a JSON source string. The only thing that can be represented in plist but not JSON is… binary data blobs. 🐢🐢🐢

**Comment by julianrex** [comment]
> This is getting pretty far off-topic, but I think a more strongly-typed column would be a very positive improvement to the schema

Agreed. Though I do like the flexibility of an arbitrary blob - so perhaps something like a "Content-Type" column for the blob would be good.

**Comment by zugaldia** [comment]
If not bundling it with iOS/Android release, at least we need to make sure we test it as part of our builds https://github.com/mapbox/mapbox-gl-native/pull/14272.
