### ISSUE TITLE
symbol-placement:line not working in iOS

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-native#1332]
Check out the river label: https://www.mapbox.com/bites/00116/?style=peterqliu.9e140828&access_token=pk.eyJ1IjoicGV0ZXJxbGl1IiwiYSI6ImpvZmV0UEEifQ._D4bRmVcGfJvo1wjuOpA1g#15.66/48.8514/2.3562 , and compare with native.

Text should run in a single line along the course of the river, with no line breaks.

**Comment by friedbunny** [comment]
![ios simulator screen shot apr 23 2015 12 38 47 pm](https://cloud.githubusercontent.com/assets/1198851/7305849/f80e169e-e9b5-11e4-965e-ce6fde0ea0eb.png)
