### ISSUE TITLE
FillLayer incomplete fill on zoom in

### ISSUE THREAD

**Issue by phillip-fry** [mapbox/mapbox-gl-native#13325]
Hello,

I believe I found an issue with the FillLayer or I am missing something from the documentation.
This is my first time posting an issue, so I apologize if I missed any guidelines, but I followed the template and checked for similar/duplicate issues.

The Fill Layer as described in the [android sdk documentation](https://www.mapbox.com/android-docs/api/map-sdk/6.7.0/com/mapbox/mapboxsdk/style/layers/FillLayer.html) has some rendering issues when you zoom in on the area. Parts of the filled shape will become unfilled and if you zoom in really close the entire polygon that was initially filled, will have no fill. 

This is the Feature collection provided below is what I am providing to the geojson source I am using to render the FillLayer. I have it filtered to look for the **LineString** tag because I have another layer that uses the same source for a line. I don't think it has anything to do with the way which I have created the source, because it works just fine when zoomed out. I also saw this [issue](https://github.com/mapbox/mapbox-gl-native/issues/10683) where they weren't closing the shape, but 
as you can see in the LineString the points do close [point1, point2, point3, point4, point1]

FeatureCollection{ 
   type=FeatureCollection, 
   bbox=null, 
   features=[
      Feature{
         type=Feature, 
         bbox=null, 
         id=connector, 
         **geometry = LineString{
            type=LineString, 
            bbox=null, 
            coordinates=[
               Point{ type=Point, bbox=null, coordinates=[-119.5762831, 35.0622168] }, 
               Point{ type=Point, bbox=null, coordinates=[-118.8414161, 35.1330492] }, 
               Point{ type=Point, bbox=null, coordinates=[-118.53066, 34.8152248] }, 
               Point{ type=Point, bbox=null, coordinates=[-119.38989616223944, 34.773178587763525] }, 
               Point{type=Point, bbox=null, coordinates=[-119.5762831, 35.0622168] } 
             ]}, 
             properties={} 
      } ,** 
      Feature{
         type=Feature, 
         bbox=null, 
         id=point-603e10be-62c4-418d-83c9-77b19dde9ff3, 
         geometry=Point{
            type=Point, 
            bbox=null, 
            coordinates=[-119.57628305365722, 35.06221678017016]}, 
            properties={"selected":false} 
      }, 
      Feature{
         type=Feature, 
         bbox=null, 
         id=point-d3205d01-3d7e-4020-806a-d2facff0a87d, 
         geometry=Point{
            type=Point, 
            bbox=null, coordinates=[-118.84141610087181, 35.13304923215037]}, 
            properties={"selected":false}
      }, 
      Feature{
         type=Feature, 
         bbox=null, 
         id=point-57d8b9de-c794-4241-9dd7-00538e6c99e7, 
         geometry=Point{
            type=Point, 
            bbox=null, 
            coordinates=[-118.53065998947454, 34.81522479845857]}, 
            properties={"selected":false}
      }, 
      Feature{
         type=Feature, 
         bbox=null, 
         id=point-131c2a27-a5bc-452b-aca4-bac726e7e29d, 
         geometry=Point{type=Point, 
         bbox=null, 
         coordinates=[-119.38989616223944, 34.773178587763525]}, properties={"selected":false}
      }
   ]
}

I could use the polygon annotation, but I would prefer to work with geojson sources and layers.

### Steps to reproduce

 1. Add Source and Layers to mapView 

My function to add source to map. I tried to add the fill layer above the Mapbox points annotations, because those are always above the polygon fills of the base map.

`private void attachDrawing(){
        try {
            customDrawing.applyDrawingProperties();
            if (mapboxMap.getSource(customDrawing.getId()) == null)
                mapboxMap.addSource(customDrawing.getGeoJsonSource());
            if (mapboxMap.getLayer(customDrawing.getPointLayerID()) == null)
                mapboxMap.addLayer(customDrawing.getPointLayer());
            if (mapboxMap.getLayer(customDrawing.getLineLayerID()) == null)
                mapboxMap.addLayer(customDrawing.getLineLayer());
            if (mapboxMap.getLayer(customDrawing.getFillLayerID()) == null)
                mapboxMap.addLayerAbove(customDrawing.getFillLayer(),"com.mapbox.annotations.points");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }`

My function to add styling properties

`public void applyDrawingProperties() {
        int defaultPointColor = Color.parseColor("#ff0000");
        pointLayer.withProperties(
                PropertyFactory.circleColor(defaultPointColor),
                PropertyFactory.circleRadius(
                        interpolate(
                                exponential(1.75f),
                                zoom(),
                                stop(12, 3f),
                                stop(22, 180f)
                        ))
        );

        lineLayer.withProperties(
                lineColor(Color.parseColor("#ff0000")),
                lineWidth(2f),
                lineDasharray(new Float[]{1.7f, 1.7f})
        );

        fillLayer.withProperties(
                PropertyFactory.fillColor(Color.parseColor("#FFD700")),
                PropertyFactory.fillOpacity(0.25f)
        );

    }`

 2. Zoom in

### Expected behavior

Map area remains completely filled so that when you zoom in, even if the edges can't be seen the map should appear tinted with the opaque color defined in the FillLayer properties.

### Actual behavior

Map area loses fill in random regions when zooming in on the area, and will loose all fill color when the zoomed in even closer.

### Configuration

**Android versions:** 
8.0.0
**Device models:** 
Samsung Galaxy S8+
**Mapbox SDK versions:** 
com.mapbox.mapboxsdk:mapbox-android-sdk:6.7.0

**Comment by asheemmamoowala** [comment]
@phillip-fry Thank you for the detailed report. I am able to reproduce your issue when using a `LineString` geojson feature. The issue goes away if the geometry type is switched to `Polygon` - keeping the coordinates the same. 

This is due to the way in which the geojson-vt library simplifies and tiles line strings polygons. LineStrings are not expected to be closed, so when tiled, there is no notion of an `inside` region that should remain filled.

**Comment by phillip-fry** [comment]
Thank you @asheemmamoowala
