### ISSUE TITLE
text-max-size is applied to text-size, not just collision box

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#1333]
Per @peterqliu in chat, -native mistakenly applies the `text-max-size` styling property to the entire text and not just the collision box. Effectively, `text-size` can never be larger than `text-max-size`, even if it should be.

You can see this in [Emerald's city labels](https://github.com/mapbox/mapbox-gl-styles/blob/mb-pages/styles/emerald-v7.json#L1889-L1938). Set `text-max-size: 35` and city labels scale as expected.

GL-JS appears to implement this properly ([example](https://www.mapbox.com/bites/00116/?style=peterqliu.9e140828&access_token=pk.eyJ1IjoicGV0ZXJxbGl1IiwiYSI6ImpvZmV0UEEifQ._D4bRmVcGfJvo1wjuOpA1g#14.24/37.7774/-122.4165), [code](https://github.com/mapbox/mapbox-gl-js/blob/2fbcd24c8e2972b918605203d11f2ad0b2e43233/js/data/symbol_bucket.js#L130-L172)), to spec.

[Here is `SymbolBucket::addFeature` on -native.](https://github.com/mapbox/mapbox-gl-native/blob/ec94e03a8ef91442a7aa7509d3925c1626b05300/src/mbgl/renderer/symbol_bucket.cpp#L225-L353)

The style spec says:

>**text-max-size**
>*Optional number.  Units in pixels. Defaults to 16. Requires text-field.*
>The maximum size text will be laid out, to calculate collisions with.

It seems like this property should be renamed to something like `text-max-collision-size` if it's not meant to constrain `text-size`.

**Comment by friedbunny** [comment]
Workaround (and the way that Streets currently does it) is to always set `text-max-size` to your desired display maximum, which allows text to size properly but presumably also creates a large collision box.

**Comment by ansis** [comment]
I think this is the guilty line: https://github.com/mapbox/mapbox-gl-native/blob/ec94e03a8ef91442a7aa7509d3925c1626b05300/src/mbgl/renderer/painter_symbol.cpp#L38

-js uses text-max-size only if text-size is missing, which I'm not sure actually happens ever: https://github.com/mapbox/mapbox-gl-js/blob/91285d64440a055cf4bc5d9e6b2d84baeb26c757/js/render/draw_symbol.js#L56

**Comment by friedbunny** [comment]
@ansis So this is totally borked. I wonder, does the text of the spec represent an actual/desirable use-case, or should there also/only be a literal `text-max-size`?

**Comment by ansis** [comment]
Since `text-size` has a [default](https://github.com/mapbox/mapbox-gl-style-spec/blob/bdfba27c38d7e559a27a0fbcb990eed1fc2eda9a/reference/v7.json#L996), painter_symbol.cpp and draw_symbol.js should only use `text-size`.

Collision placement code should use `text-max-size` which it's already doing.

There is also an issue about getting rid of `text-max-size`.
https://github.com/mapbox/mapbox-gl-style-spec/issues/255

**Comment by ansis** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/commit/17010bfd73f2c8e94318fece0b216ec4f91b6f91

-js cleaned up in https://github.com/mapbox/mapbox-gl-js/commit/98af02492183975f1f17e089a7a4118ac1ec6ddf
