### ISSUE TITLE
MGLUserLocationAnnotationView shows on top of SMCalloutView

### ISSUE THREAD

**Issue by nnhubbard** [mapbox/mapbox-gl-native#13332]
We use SMCalloutView to show custom callouts when tapping pins on the `MapBox` map. When doing so the current location indicator view (MGLUserLocationAnnotationView) shows overtop of the callout. 

### Steps to reproduce

 1. Implement SMCalloutView
 2. Tap annotation to show callout view
 3. Current user indicator will be overtop of the callout view

### Expected behavior

User location should be behind the callout view

### Actual behavior

User location is on top of callout view

### Configuration

**Mapbox SDK versions:** 
**iOS/macOS versions: 11, 12** 
**Device/simulator models: All**
**Xcode version: 10**

**Comment by friedbunny** [comment]
For reference, this does not happen with the built-in `SMCalloutView` on `ios-v4.10.0`.

![IMG_7397](https://user-images.githubusercontent.com/1198851/57648874-84be4500-757b-11e9-9f3d-0fdbd736d98f.jpg)
