### ISSUE TITLE
.Resources$NotFoundException: File res/drawable/mapbox_info_bg_selector.xml from drawable

### ISSUE THREAD

**Issue by biessek** [mapbox/mapbox-gl-native#13339]
### Steps to reproduce

 1. Created an empty project
 2. Added one activity with just mapview
```
<?xml version="1.0" encoding="utf-8"?>
<com.mapbox.mapboxsdk.maps.MapView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

</com.mapbox.mapboxsdk.maps.MapView>
```
 3. Opened the app

### Expected behavior
Map display without errors

### Actual behavior
Error inflating mapview with Resources$NotFoundException: File res/drawable/mapbox_info_bg_selector.xml from drawable

### Configuration

**Android versions:** 4.2.2 /
**Device models:** Original ALPS A8 + MTK6582
**Mapbox SDK versions:** 6.7.0

**Comment by biessek** [comment]
Note: It works with **android-v6.6.7**

**Comment by tobrun** [comment]
Thank you for flagging @biessek, both v6.7.0 as v6.6.7 contain https://github.com/mapbox/mapbox-gl-native/commit/200ba355b58b7f74c397d496bed1deff1b394582 and haven't been able to reproduce this on a 4.4.2 handset. Will look more into it.

**Comment by biessek** [comment]
@tobrun One thing that I note that may help. I didn't look the resource and the loading, but if this is an svg, you can look for setImageDrawable and replace by setImageResource. 
I had this error message in another resource and that solved as pointed by [the docs](https://developer.android.com/guide/topics/graphics/vector-drawable-resources#vector-drawables-backward-solution)

**Comment by biessek** [comment]
@tobrun, I've checked on another device both versions like you and worked. The issue device had an app with a older version of mapbox and the new one in my test (maybe a conflict?..). So I think it's not a bug, just installation problems.
