### ISSUE TITLE
How to position the user by the bottom of the phone screen, not centered

### ISSUE THREAD

**Issue by giantss** [mapbox/mapbox-gl-native#13341]
How to position the user by the bottom of the phone screen, not centered

**Comment by friedbunny** [comment]
Hi, @giantss — thanks for using Mapbox. This repo is for reporting bugs, requesting features, and coordinating work related to the various Mapbox Map SDKs. For help with “how do I” questions, please ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox) or reach out to our excellent [support team](https://www.mapbox.com/contact/support/).
