### ISSUE TITLE
 [ERROR] {}[Style]: Failed to load sprite:

### ISSUE THREAD

**Issue by aio-ani** [mapbox/mapbox-gl-native#13348]
When i load local style.json,the terminal print the error " Failed to load sprite:" . but i have already configed the local path of spirite ,like "file://{path}/Resource/WTMapSprite"(the path is for replace in running time). 

![style json before replace](https://user-images.githubusercontent.com/10450170/48389485-a196ce80-e738-11e8-947f-4f9a7d94cc66.png)
![style json after replace](https://user-images.githubusercontent.com/10450170/48389501-ad829080-e738-11e8-9f50-df3d8d48d3d4.png)
![local dir](https://user-images.githubusercontent.com/10450170/48389508-b1aeae00-e738-11e8-99a3-f92004c122d8.png)

### Steps to reproduce

 1.
 2.
 3.

### Expected behavior

I hope to show the spirite on the map normally.

### Actual behavior

failed to show the spirite and print the error "Failed to load sprite:".

### Configuration

**Mapbox SDK versions:** 
**iOS/macOS versions:** 10.14
**Device/simulator models:**12.0
**Xcode version:** xcode10

**Comment by kkaefer** [comment]
We recommend using `asset://` instead of `file://` to load data from the bundle of an iOS/macOS application.

**Comment by aio-ani** [comment]
> We recommend using `asset://` instead of `file://` to load data from the bundle of an iOS/macOS application.

when i use 'asset' to load data,the map shows nothing and prompt error: Failed to load glyph range.

**Comment by aio-ani** [comment]
![image](https://user-images.githubusercontent.com/10450170/58865643-7f22cd80-86e9-11e9-906a-8a8bea541898.png)
