### ISSUE TITLE
Maximum zoom level with LatLngBounds camera update

### ISSUE THREAD

**Issue by Jukurrpa** [mapbox/mapbox-gl-native#13340]
It'd be very practical to be able to define a maximum zoom level when building a camera update when using `CameraUpdateFactory.newLatLngBounds()` on Android.

We sometimes need to zoom on a group of POIs that can be very close to each other, or have just one point, resulting in a very high zoom level. We can work around this by checking the size of the box beforehand and changing its bounds if necessary (or using extra padding), but it's not as straightforward  as being able to give a max zoom for the camera update.

The option exists on Mapbox GL JS when using the `fitBounds()` method but I couldn't find an equivalent on Android. Having it ported in a future release would be really great.

**Comment by asheemmamoowala** [comment]
Sounds like this would be a useful addition to the `CameraUpdateFactory`. 

In the meantime, have you considered setting the [`MapboxMap.setMaxZoomPreference`](https://www.mapbox.com/android-docs/api/map-sdk/6.7.0/com/mapbox/mapboxsdk/maps/MapboxMap.html#setMaxZoomPreference-double-) method to constrain the max zoom before the call to update the camera?

**Comment by Jukurrpa** [comment]
Yep I thought of it, but for some reason I thought I had to set it back to its original value in the CancelableCallback after the animation was finished wish wasn't great. But after your suggestion I actually tried setting it back right after calling `animateCamera()` and it works perfectly, thanks :+1: Way better than our previous workaround.
