### ISSUE TITLE
-[MGLMapView mapID] always returns nil

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1334]
`-[MGLMapView mapID]` always returns `nil` because `-styleURL` returns a URL like `https://api.tiles.mapbox.com/styles/v1/texample/texample.deadbeef?access_token=…` even when you set the `styleURL` to `mapbox://texample.deadbeef`.

**Comment by jfirebaugh** [comment]
I'd rather we change `Map::getStyleURL` so that it returns the URL passed to `Map::setStyleURL`.

**Comment by 1ec5** [comment]
In that case, we’d need to more the normalization code from `Map::setStyleURL()` to `MapData::getStyleInfo()`.

**Comment by jfirebaugh** [comment]
@1ec5 Can you verify this was fixed by #1607?

**Comment by 1ec5** [comment]
Yes, #1607 fixed this issue good.
