### ISSUE TITLE
[ iOS ] - Unable to get features for tile source

### ISSUE THREAD

**Issue by BeeWise** [mapbox/mapbox-gl-native#13354]
### Configuration

**Mapbox SDK versions:** 4.5
**iOS/macOS versions:** 12.0
**Device/simulator models:** iPhone 8
**Xcode version:** 10.0 (10A255)

### Steps to reproduce

I am trying to setup a vector tile source after the map view did finish loading.

```
func mapView(_ mapView: MGLMapView, didFinishLoading style: MGLStyle) {
    let urlTemplate = "http://a.tiles.mapbox.com/v4/mapbox.mapbox-streets-v7/{z}/{x}/{y}.mvt?access_token=my_access_token"
    let source = MGLVectorTileSource(identifier: "source",
                                     tileURLTemplates: [urlTemplate],
                                     options: nil)
    mapView.style?.addSource(source)

    let layer = MGLFillStyleLayer(identifier: "layer", source: source)
    layer.sourceLayerIdentifier = "source"
    mapView.style?.addLayer(layer)
}
```

Here is what I use in order to find the features:

```
func mapView(_ mapView: MGLMapView, regionDidChangeAnimated animated: Bool) {
    if let source = mapView.style?.source(withIdentifier: "source") as? MGLVectorTileSource {
        let sourceFeatures = source.features(sourceLayerIdentifiers: Set(["source"]), predicate: nil)
        print("sourceFeatures count = \(sourceFeatures.count)") // Always 0
    }
}
```
I even tried with the `visibleFeatures` from the map view, but it didn't work. I also tried without adding the layer, but it didn't work.

**Comment by 1ec5** [comment]
There’s a difference between style layers and source layers. You’re setting `sourceLayerIdentifier` to `source`, which means the style layer can only contain features that are contained in the `source` layer of the vector tile source. But the Mapbox Streets source doesn’t have a layer called `source`. [This page](https://docs.mapbox.com/vector-tiles/mapbox-streets-v8/) documents the Mapbox Streets source, including each of its layers.
