### ISSUE TITLE
MGLAnnotationViews jump when animating map view frame

### ISSUE THREAD

**Issue by maxmamis** [mapbox/mapbox-gl-native#13366]
When animating a MGLMapView's frame, I would expect all annotations to track with the map during the animation. `MGLAnnotationImage`s behave correctly, but `MGLAnnotationView`s jump to their new location without any animation. I've attached a gif of the behavior I'm describing.

Additionally, the user location annotation exhibits some undesirable parallax behavior, but it is relatively minor compared to the annotations. This can also be observed in my gif.

![mapbox_frame_animation](https://user-images.githubusercontent.com/3718504/48451834-340b9200-e77a-11e8-9253-3ec5cd7db2c8.gif)

### Steps to reproduce

 1. Create a MGLMapView
 2. Add an MGLAnnotationView to the map view
 3. Animate the frame of the map view 

### Expected behavior
annotation view tracks map animation

### Actual behavior
Annotation view jumps to new position without animation 

### Configuration

**Mapbox SDK versions:** Observed on 4.6.0
**iOS/macOS versions:** Observed on iOS 12
**Device/simulator models:** iPhone XS device and various simulators 
**Xcode version:** 10.1

**Comment by maxmamis** [comment]
@julianrex thanks for the response — I just opened #13374 that fixes the issue

**Comment by philfi** [comment]
Any idea when this will be resolved or anything we can do to help move possible solution in https://github.com/mapbox/mapbox-gl-native/pull/13374 along? Experiencing this issue in our app and would love to see it get merged in.

**Comment by maxmamis** [comment]
This is still an issue in the latest SDK release — would love to keep it open if possible :)

**Comment by maxmamis** [comment]
Happy to open a new issue instead if that's the preferred workflow

**Comment by julianrex** [comment]
This ticket is good 👍
