### ISSUE TITLE
Remove Environment::terminate, FileSource::abort, etc

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1336]
`Environment::terminate` is not called from anywhere, so neither is `FileSource::abort`, etc. Can we remove it?

The strategy for canceling requests should be that `FileSource::request` returns a `std::unique_ptr<Request>`, and `~Request` cancels the request if it hasn't completed yet. There should be no explicit cancelling/aborts, just `reset`ting the `unique_ptr<Request>`.

cc @kkaefer @tmpsantos

**Comment by tmpsantos** [comment]
:+1:
