### ISSUE TITLE
[Crash] Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by erluxman** [mapbox/mapbox-gl-native#13369]
- Mapbox Crashes even before start  in sdk version(6.7.0) and after using for some time in 6.6.3 with the following error trace 

# I get the error :  

> 2018-11-14 17:10:07.043 10822-10831/com.kabzeel.android A/libc: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xc4d60434 in tid 10831 (FinalizerDaemon), pid 10822 (kabzeel.android)
 
### Steps to reproduce

 I have the following fragment : 

```
class DashboardMapFragment:Fragment(){
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View {
        Mapbox.getInstance(context!!, BuildConfig.MAPBOX_ACCESS_KEY)
        return inflater.inflate(R.layout.fragment_dashboard_map,container,false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        mapView.onCreate(savedInstanceState)
        mapView.setOnTouchListener { _, _ ->
            mapView.parent.requestDisallowInterceptTouchEvent(true)
            false
        }
    }


    override fun onStart() {
        super.onStart()
        mapView.onStart()
    }

    override fun onResume() {
        super.onResume()
        mapView.onResume()
    }

    override fun onPause() {
        super.onPause()
        mapView.onPause()
    }

    override fun onStop() {
        super.onStop()
        mapView.onStop()
    }

    override fun onLowMemory() {
        super.onLowMemory()
        mapView.onLowMemory()
    }

    override fun onDestroy() {
        super.onDestroy()
        mapView.onDestroy()
    }

    override fun onSaveInstanceState(outState: Bundle) {
        mapView.onSaveInstanceState(outState)
        super.onSaveInstanceState(outState)
    }

    companion object {
        fun newInstance(): DashboardMapFragment {
            return DashboardMapFragment()
        }
    }
}
```

Layout is : 

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:mapbox="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">


    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        mapbox:mapbox_cameraTargetLat="40.73581"
        mapbox:mapbox_cameraTargetLng="-73.99155"
        mapbox:mapbox_cameraZoom="11"
        mapbox:mapbox_styleUrl="mapbox://styles/mapbox/streets-v10" />
</FrameLayout>

```

### Expected behavior
In Mapbox 6.6.3 I was able to use the map for few swipes (Mapview is in ViewPager) then it crashes... but with 6.7.0 I am unable to even start.

### Actual behavior
Crashes The app when this fragment comes in focus.

### Configuration

**Android versions:** android 28
**Device models:**  Emulator Pixel 
**Mapbox SDK versions:** 6.7.0

**Comment by LukasPaczos** [comment]
Thanks for reaching out @erluxman. You need to call `MapView#onDestroy` from your fragment's `#onDestroyView`:
```
override fun onDestroyView() {
  super.onDestroyView()
  mapView.onDestroy()
}
```

Let us know whether this one resolves your issue. You can also compare your setup with our [`ViewPager` example](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/ViewPagerActivity.java).

**Comment by cmpeguerog** [comment]
@LukasPaczos i implements that solution but stil getting the same error

**Comment by erluxman** [comment]
@LukasPaczos sorry for late response, I believe I fixed my issue with your comment but forgot to respond.. Thanks a lot :)
