### ISSUE TITLE
Enabling .lineMetrics on an MGLShapeSource crashes Mapbox

### ISSUE THREAD

**Issue by stoeffn** [mapbox/mapbox-gl-native#13378]
Hi,

I'm trying to use the new line gradient feature but, unfortunately, enabling `.lineMetrics` as per the [documentation](
https://www.mapbox.com/ios-sdk/api/4.6.0/Other%20Constants.html#/c:@MGLShapeSourceOptionLineDistanceMetrics) crashes Mapbox:

```
libc++abi.dylib: terminating with uncaught exception of type std::overflow_error: __next_prime overflow
```

For your convenience, I've attached a [sample project](https://github.com/mapbox/mapbox-gl-native/files/2584428/MapboxTest.zip).

### Configuration

**Mapbox SDK versions:** 4.6
**iOS versions:** 12.1
**Device/simulator models:** iPhone 6 Plus
**Xcode version:** 10.1

**Comment by 1ec5** [comment]
Fixed in #13543.
