### ISSUE TITLE
RemoveSource call can fail without developer indication

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#13381]
Android equivalent of https://github.com/mapbox/mapbox-gl-native/issues/9692

**Comment by tobrun** [comment]
Note: look into correct return value for

```cpp
        // The source may not be removed if any layers still reference it
        return ownedSource != nullptr;
```

**Comment by LukasPaczos** [comment]
I believe this is a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/12526

**Comment by tobrun** [comment]
you are right, let's address it with 7.0
