### ISSUE TITLE
Rotation flick animation support (iOS).

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1338]
Is there any plan to add support for rotation flick animation in Mapbox GL? By rotation flick, I mean the map continues to rotate  even after one takes the fingers off screen.

**Comment by 1ec5** [comment]
#1292 adds rotation drift. It doesn't rotate forever; it's similar to what MapKit does when you rotate quickly. Is that what you mean?

**Comment by mb12** [comment]
Yes, I do mean Mapkit kind of rotation drift where in it sometimes does a full 360 turn upon rotation before it comes to a stop.

**Comment by 1ec5** [comment]
The implementation in #1292 will always drift for one second, spinning by an angle that depends on the angular velocity at the end of the rotation gesture. It’s quite difficult to make it spin a full 360°. The animation is perhaps more conservative than the ones for pan and pinch; I was afraid that an aggressive rotation animation would disorient the user. But please try out that PR and let me know of any improvements I should make.

**Comment by mb12** [comment]
I tried out the latest repo where in this change is already committed. Its almost impossible to trigger rotation drift like animation. It almost always detects it as a zoom.
Its very easy to trigger rotation drift in other vector map impls (Apple/Goog/Nokia).

**Comment by 1ec5** [comment]
> Its almost impossible to trigger rotation drift like animation. It almost always detects it as a zoom.

Agreed; can you file a new ticket? #1434 and #1436 should improve things on the gesture front, but we decided to lock things down to stability and performance fixes ahead of a beta release.
