### ISSUE TITLE
-[MGLTileSetTests testTileSetFromTileURLTemplates] fails on High Sierra and above

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#13386]
#11391 didn’t completely fix #11289: on macOS 10.14 High Sierra and above, `-[MGLTileSetTests testTileSetFromTileURLTemplates]` still fails on the following assertion:

```
Test Suite 'MGLTileSetTests' started at 2018-11-15 18:24:15.215
Test Case '-[MGLTileSetTests testTileSetFromTileURLTemplates]' started.
/path/to/mapbox-gl-native/platform/darwin/test/MGLTileSetTests.mm:95: error: -[MGLTileSetTests testTileSetFromTileURLTemplates] : ((@(tileSet.attribution.c_str())) equal to (html)) failed: ("<font face="Helvetica" size="3" style="font: 12.0px Helvetica"><a href="https://www.mapbox.com/">Mapbox</a> </font><font face="Helvetica" size="3" style="font: 12.0px Helvetica; background-color: #fb0007">GL</font>
") is not equal to ("<font face="Helvetica" size="3" style="font: 12.0px Helvetica"><a href="https://www.mapbox.com/">Mapbox</a> </font><font face="Helvetica" size="3" style="font: 12.0px Helvetica; background-color: #ff0000">GL</font>
")
Test Case '-[MGLTileSetTests testTileSetFromTileURLTemplates]' failed (4.425 seconds).
Test Suite 'MGLTileSetTests' failed at 2018-11-15 18:24:19.642.
```

The problem is that `-[NSAttributedString dataFromRange:documentAttributes:error:]` exports HTML that expresses colors in the generic RGB (aka calibrated RGB) color space instead of sRGB, which is a violation of the CSS specification. I’ve opened [rdar://problem/46115233](http://openradar.appspot.com/radar?id=5504401372348416) (lionheart/openradar-mirror#20722) to track the issue upstream in the (Apple) macOS SDK. In the meantime, we can work around the issue by expressing the test’s initial color in calibrated RGB:

https://github.com/mapbox/mapbox-gl-native/blob/8961768eb0b8580f0670ed5f977009e8461a0fac/platform/darwin/test/MGLTileSetTests.mm#L75

This test is the only place in the codebase where we generate HTML from an attributed string, so the issue and workaround don’t impact production code. It also doesn’t affect builds on CircleCI, which still runs macOS 10.13 Sierra.

/cc @mapbox/maps-ios

**Comment by 1ec5** [comment]
> This test is the only place in the codebase where we generate HTML from an attributed string, so the issue and workaround don’t impact production code.

Actually, this issue does affect production code, specifically the use of `MGLTileSourceOptionAttributionInfos` in `-[MGLVectorTileSource initWithIdentifier:tileURLTemplates:options:]`.

> It also doesn’t affect builds on CircleCI, which still runs macOS 10.13 Sierra.

CircleCI builds run on macOS 10.14 High Sierra these days, which accounts for the failures I’m seeing in #13387. So the difference between running locally and on CI must be related to the system color profile or something.

**Comment by friedbunny** [comment]
This is still an issue locally, running macOS 10.14.5b1 and Xcode 10.2.

**Comment by friedbunny** [comment]
Now seeing a failure [on CircleCI](https://circleci.com/gh/mapbox/mapbox-gl-native/319440) for iOS jobs with Xcode 11b5:

```
MGLTileSetTests
  testTileSetFromTileURLTemplates, ((@(tileSet.attribution.c_str())) equal to (html)) failed: ("<font style="font-family: 'Helvetica'; font-weight: normal; font-style: normal; font-size: 12.00px"><a href="https://www.mapbox.com/">Mapbox</a> </font><font style="font-family: 'Helvetica'; font-weight: normal; font-style: normal; font-size: 12.00px; background-color: #ff0000">GL</font>
  /Users/distiller/project/platform/darwin/test/MGLTileSetTests.mm:95

> #endif
>    XCTAssertEqualObjects(@(tileSet.attribution.c_str()), html);
```
