### ISSUE TITLE
[android] Use China telemetry endpoint with China API endpoint

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#13401]
This is the Android equivalent of https://github.com/mapbox/mapbox-gl-native/pull/11860 that we'd like to bring to the Android Maps SDK in order to provide a consistent experience to our developers.

The suggested change would only be enabled if the application has opted into `api.mapbox.cn` for the Maps API via `MapboxMapOptions.apiBaseUrl()`. For all other applications, the behavior is the same as before.

**Comment by tobrun** [comment]
Capturing from the linked PR:

> Capturing chat with @andrlee: with less urgency on the business need, we're gonna revisit the approach at a later date. @tobrun thanks much for running with these changes, we're gonna leave them unmerged for the time being

Closing for time being.
