### ISSUE TITLE
[MGLMapView glkView:drawInRect:] causing a memory increase of ~60mb

### ISSUE THREAD

**Issue by YanivHas** [mapbox/mapbox-gl-native#13416]
### Steps to reproduce

 1. Create an NavigationMapView(self.bounds)
 2. See the map displaying
 3. Leave screen and deinit map view

### Expected behavior

All memory will be released

### Actual behavior

An addition of 64.03mb is added to the app and not releases.
According to instruments, this happens on:
![screen shot 2018-11-20 at 13 26 48](https://user-images.githubusercontent.com/42316614/48770726-fea9fb80-ecc7-11e8-92ac-b6736fddeb08.png)

### Configuration

**Mapbox SDK versions:** 
Mapbox-iOS-SDK (3.7.8)
**iOS/macOS versions:** 
12.0.1
**Device/simulator models:**
iPhone 8 plus
**Xcode version:** 
Xcode10

**Comment by julianrex** [comment]
@YanivHas thanks for reporting! Do you know if this also happens with the parent class, `MGLMapView`?

**Comment by YanivHas** [comment]
It does...
That was my first try to fix this

**Comment by fabian-guerra** [comment]
Hi, @YanivHas. Thank you for using Mapbox. I've noticed you are using version `Mapbox-iOS-SDK (3.7.8)` is it possible you could try with our [latest 4.6.0](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v4.6.0) SDK?

**Comment by fabian-guerra** [comment]
Please feel free to reopen this issue if you still have the problem.
