### ISSUE TITLE
Map Style Rendering Issue

### ISSUE THREAD

**Issue by philfi** [mapbox/mapbox-gl-native#13420]
![2018111909185565072676](https://user-images.githubusercontent.com/39564615/48783552-b6caaa80-ecae-11e8-856d-395a08a763fd.jpg)

Hello,

Wish I had more information to provide but I'm a bit at a loss as to what's going on here/how to repro. I've experienced this a few times now, it seems like it could be related to connection/background processing issues? It seems the map style gets rendered all weird even though my custom annotations are rendering correctly (note the circle annotation and Home "pill" in the screenshot). I've looked through the Issues, Release Notes, StackOverflow trying to find something similar/related but have come up short so I'm hoping maybe someone will see this and have an idea of what's going on or how to troubleshoot? I've experienced this with iOS Mapbox 4.3.0, will update to latest and keep an eye on it.

Thanks!

**Mapbox SDK versions:** 4.3.0
**iOS/macOS versions:** 12.0/12.1
**Device/simulator models:** iPhone X
**Xcode version:** 10.0

**Comment by gduranon** [comment]
I can confirm it still happens with latest SDK, when the app is in the background for some hours, and then returns to foreground. The text stops rendering and strange vectors appear on top of map. Trying to reset style doesn't fix the graphic corruption

**Comment by julianrex** [comment]
@tobrun @tmpsantos Have you seen/heard of similar behavior on other platforms?

**Comment by tmpsantos** [comment]
> @tobrun @tmpsantos Have you seen/heard of similar behavior on other platforms?

No, I have not seen this before.
