### ISSUE TITLE
Remove IB_DESIGNABLE from MGLMapView

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#13424]
*Ticketing out separately from #10072.*

Given our current issues with `MGLMapView` crashing the Interface Builder agent (#10573, #10072) let's remove the designable support. I would suggest that rather than removing wholesale, we should wrap with an `#ifdef` so that we can periodically check whether a crash occurs.

In addition, as @friedbunny [mentions](https://github.com/mapbox/mapbox-gl-native/issues/10072#issuecomment-332273649) the designable doesn't provide much value. 

Updating our documentation should be considered part of this issue.

**Mapbox SDK versions:** 4.7.0-alpha.1 (at time of writing)
**Xcode version:** 10.1 (at time of writing)

**Comment by captainbarbosa** [comment]
These are the docs that reference using Interface Builder to create a map view, and would need to be updated once this ticket is closed:

https://www.mapbox.com/install/ios/cocoapods-add/
https://www.mapbox.com/install/ios/carthage-add/
https://www.mapbox.com/install/ios/download-add/
https://www.mapbox.com/help/first-steps-ios-sdk/

cc @mapbox/docs

**Comment by fabian-guerra** [comment]
Fixed in #14379
