### ISSUE TITLE
Style issue when local is set to Arabic/Persian

### ISSUE THREAD

**Issue by kptlronyttcna** [mapbox/mapbox-gl-native#13421]
Some form of #10792 still exists.

Set device language to Arabic (without western digits option), Draw a line and style it. It wont work.
Tried it with 6.7.1 and 7.0.0-alpha01

This is the code I've used:
```
val source = GeoJsonSource("source", requireContext().assets.open("test.geojson").bufferedReader().readText())
val lineLayer = LineLayer("lineLayer", "source").withProperties(
    PropertyFactory.lineWidth(8f),
    PropertyFactory.lineColor(Color.YELLOW)
)
val circleLayer = CircleLayer("circleLayer", "source").withProperties(
    PropertyFactory.circleRadius(8f),
    PropertyFactory.circleColor(Color.YELLOW)
)
val fillLayer = FillLayer("fillLayer", "source").withProperties(
    PropertyFactory.fillColor(Color.YELLOW)
)
mapboxMap?.addSource(source)
mapboxMap?.addLayer(fillLayer)
mapboxMap?.addLayer(lineLayer)
mapboxMap?.addLayer(circleLayer)
```

Using the workaround suggested in #10792 fixes the issue.

**Comment by LukasPaczos** [comment]
Thanks for reaching out @kptlronyttcna. I was able to reproduce and can confirm that this issue has been fixed in https://github.com/mapbox/mapbox-gl-native/pull/13393 and will be available in `7.0.0`. Feel free to test it out in the upcoming `7.0.0-alpha.2`. Closing as resolved.
