### ISSUE TITLE
Android - OfflineDownload throwing "too many tiles" even after deleting offline region

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#13437]
When downloading a lot of tiles thought the offline download, I get the expected "too many tiles" error. When deleting this offline region using the Offline Manager, I was trying to "free up" the downloaded tiles. But as soon as I started a new offline download, I instantly get the "too many tiles" error. Is that expected?

### Expected behavior
When deleting an offline region, I expect all related tiles to be migrated to the ambient cache. (I hope I am using the right term to define the ambient cache as the tile storage that is not part of the max tile count which users can download. I know that the ambient cache and persistent offline cache is the same database.)

### Actual behavior
When deleting an offline region, all downloaded tiles are still saved as non-ambient tiles. That leads to the problem that the user has to clear their app storage to download new offline regions (even if that user actually has no offline regions according to the offline manager). 

### Configuration

**Mapbox SDK versions:** 6.x, 7.x

**Comment by tobrun** [comment]
@Mordag 
thank you for the report, I briefly looked into this issue and seeing that the code path for resetting the` cached optional<uint64_t> offlineMapboxTileCount` from `offline_database.hpp` is valid so I'm not sure why the recalculation is not working correctly for you. 

Removing the Android label and adding Core instead.

**Comment by Mordag** [comment]
@tobrun Do you have any updates regarding this issue? This problem is still present in 7.2.0.

**Comment by tobrun** [comment]
@tmpsantos could this be :eyes: 'ed by someone from the core team?

**Comment by tmpsantos** [comment]
@Mordag do you have some code example we could use to reproduce the issue?

**Comment by Mordag** [comment]
@tmpsantos I don't do anything special with the offline download. I can post some examples how we use the offline download and delete offline regions, but I am not certain if I am able to provide a full example for this problem.

```kotlin
val downloadGeometry = GeometryGeoJson.fromJson(jsonHelper.toJson(offlineRegion.geometry))
val metadata = jsonHelper.toJson(offlineMetadata).toByteArray(Charsets.UTF_8)
val offlineGeometryRegionDefinition = OfflineGeometryRegionDefinition(
          resourceAccessor.getString(R.string.map_box_style),
          downloadGeometry,
          OFFLINE_DOWNLOAD_MIN_ZOOM,
          offlineMaxZoomLevel.toDouble(),
          applicationContext.resources.displayMetrics.density)
offlineManager.createOfflineRegion(offlineGeometryRegionDefinition, metadata, this)
```

We save a custom offline region id in a separate database. If the user selects an offline region entry, it is possible to delete that one. Using this id, we iterate though each item provided by offlineManager.listOfflineRegions(...). If the id matches, we delete the region. That works perfectly fine at the moment except the issue I mentioned earlier (regarding the max tile size).

```kotlin
mapboxRegion.delete(object : OfflineRegionDeleteCallback {
    ...
}
```

**Comment by tmpsantos** [comment]
@Mordag we found the issue here. Fix pending review.
