### ISSUE TITLE
Android SDK 6.7.0 won't generate libmapbox-gl.so under armeabi ?

### ISSUE THREAD

**Issue by chancyWu** [mapbox/mapbox-gl-native#13448]
I'm using the  ```implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.7.0'``` in my android module library. in the app module, i'm supporting only x86 and armeabi which is as below: 
```
ndk {
    abiFilters "x86"
    abiFilters "armeabi"
}
```
If i run the app in emulator it works fine. But in any actual device phone. The app crashes due to missing the 'libmapbox-gl.so' and i unzip the apk file find under **lib/armeabi/** there is no 'libmapbox-gl.so' and in lib/x86/ there is. My question is how can i get the missing .so under **lib/armeabi**?

error from the logcat is as below:

> E/Mbgl-LibraryLoader: Failed to load native shared library.
>     java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xxx.xxx-UGEGUGo4RgqFJfMeHCuM9g==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxx-UGEGUGo4RgqFJfMeHCuM9g==/lib/arm, /data/app/com.xxx.xxx-UGEGUGo4RgqFJfMeHCuM9g==/base.apk!/lib/armeabi, /system/lib, /vendor/lib, /product/lib]]] couldn't find "libmapbox-gl.so"
>         at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
>         at java.lang.System.loadLibrary(System.java:1660)
>         at com.mapbox.mapboxsdk.LibraryLoader$1.load(LibraryLoader.java:19)
>         at com.mapbox.mapboxsdk.LibraryLoader.load(LibraryLoader.java:42)
>         at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<clinit>(NativeConnectivityListener.java:13)
>         at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:40)
>         at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
> 
>

**Comment by LukasPaczos** [comment]
Hey @chancyWu, unfortunately, the support for `armeabi` has been dropped in the NDK r17, see https://github.com/mapbox/mapbox-gl-native/pull/11458. Closing as not actionable.
