### ISSUE TITLE
Offline database generation settings and commands

### ISSUE THREAD

**Issue by KonstantinEmelyanov** [mapbox/mapbox-gl-native#13447]
Hi, all!
I generate offline data for Android ang IOS on my Linux server. Please tell me, where i can find all information about settings and commands for it.
Now i use for generate command like this:
`./mbgl-offline --north  --west  --south  --east  --maxZoom 22 --style http:// --token  --output `
But now my data so big.
Maybe there is more settings for generate more compact and efficient data. Please tell me, where i can reed about this?

**Comment by LukasPaczos** [comment]
Hey @KonstantinEmelyanov, all of the available options are listed in [the documentation](https://www.mapbox.com/android-docs/maps/overview/offline/#offline-sideloading). However, there is one more option, not directly connected to generating the offline database - you can append `?optimize=true` to your style URL, for example
```
--style mapbox://styles/mapbox/streets-v10?optimize=true
```

This will use our [vtshaver](https://github.com/mapbox/vtshaver) to optimize the tiles based on the provided style. This might make the tiles incompatible with different styles, but will make them more compact.

Are there any other option you'd like to see included in the tool?

**Comment by asheemmamoowala** [comment]
@KonstantinEmelyanov The tiles endpoint used by the `mbgl-offline` tool is [rate limited](https://www.mapbox.com/api-documentation/#rate-limits). Based on the size of offline regions you have provided, you are probably hitting rate limits, and being throttled by the code that handles the `429` response:

https://github.com/mapbox/mapbox-gl-native/blob/8d0b06d5dd73313724bf5186a244f3ad3e7ba85e/platform/darwin/src/http_file_source.mm#L299-L314

Also note that the offline tile count limit is 6000 tiles. [Contact support](https://www.mapbox.com/contact/) if you'd like to raise either of these limits.
