### ISSUE TITLE
Include Build Number In UserAgent

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1345]
Currently on the app name and app version are include in the app portion of the Metrics User Agent.  Change this to include the build number too.

Current:  `AppName/AppVersion MapboxEventsiOS/1.0`
Future: `AppName/AppVersion-AppBuild MapboxEventsiOS/1.0`

/cc @mapbox/mobile @camilleanne @mick @edenh

**Comment by incanus** [comment]
Related: 

* [`src/mbgl/util/version.cpp`](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/util/version_info.cpp)
* [`scripts/build-version.py`](https://github.com/mapbox/mapbox-gl-native/blob/master/scripts/build-version.py)

**Comment by incanus** [comment]
Begun in above, where we now both the bundle version and the build number, but not if they're equal (like in the GL test app). 

So: 

* `Mapbox GL/0.0.2 MapboxEventsiOS/1.0` for GL
* `MyApp/1.0/13 MapboxEventsiOS/1.0` for `MyApp`

Begs the question of what exactly we should be doing with `MapboxEventsiOS/1.0` in relation to GL's versioning scheme.

**Comment by bleege** [comment]
Added support to grab `CFBundleVersion` from app and pass that in as `appBuildNumber`.  Testing produced the following example:

`Mapbox GL/0.0.2-0.0.3 MapboxEventsiOS/1.0`

**Comment by bleege** [comment]
Tested, Travised, and Merged.

**Comment by bleege** [comment]
Changed format for consistency.

`Mapbox GL/0.0.2/0.0.3 MapboxEventsiOS/1.0`
