### ISSUE TITLE
Android - OfflineManager usage without callbacks

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#13451]
The current implementation of the OfflineManager always requires a callback for any method, like deleting an offline region, listing offline regions etc. Would it be possible to consider running this part without using callbacks? For example listing the offline regions: The onError could be handled by returning null instead (or maybe an empty list to avoid nulls). If someone is interested in the error or wants to display/log it, they could use the callback implementation. The problem with the current implementation is that it leads to quite messy code (in my opinion). 

Messy code means, try to delete a certain offline region if it has a certain state (for whatever reason). Listing the offline region needs a callback, than I need to create a callback for the state and then I need a callback for the deletion.

**Mapbox SDK versions:** 6.7.1

**Comment by LukasPaczos** [comment]
Hey @Mordag, thanks for the suggestion, but the reason for callbacks in the `OfflineManager` is that the operations on the database are done asynchronously and we need a way to communicate back. Closing as this isssue, unfortunately, is not actionable.

**Comment by LukasPaczos** [comment]
I can see how this would clean up the code from the user perspective, let's keep it open as a feature request.

**Comment by masterjefferson** [comment]
+1, these changes would be great.
