### ISSUE TITLE
Unit tests are non-determinative

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-gl-native#13494]
Unit tests should be determinative.

Currently the gl-native tests (`make run-test` with the `linux-gcc5-debug-coverage` circleci job) at 2b84c2d are not. Different code executes each time they are run. 

I think this is a known issue, but I don't see a good overall ticket describing it, so I'm ticking here anew.

The problem with non-determinism in unit tests include:

 - If the same code does not predictably run each time, bugs may be lurking and therefore the test may give a false sense of confidence your code is being tested
 - They may randomly fail or be flaky. At best this causes lost developer time to restart jobs and confirm the cause of failure is known flakyness. At worse flaky tests can results in developers not caring and not noticing deeper problems
 -  They make coverage tracking difficult. If the same code does not run each time the tests are run then a symptom of that deeper problem is that the coverage %s will flap.

This explains why these lines are flapping in coverage reports: https://github.com/mapbox/mapbox-gl-native/issues/13324#issuecomment-438854018

I've spoke with @tmpsantos that this is something to be addressed in the future. One this issue is addressed we should revert #13364 so that we start tracking coverage changes with 0% threshold - that will ensure we don't miss adding tests for new code.

**Comment by springmeyer** [comment]
@tmpsantos any movement on this?

**Comment by tmpsantos** [comment]
@springmeyer I think this could be achieved because of the amount of work we do on worker threads. We could try to run the tests with only one worker thread (might improve) but we still do a lot of asynchronous network requests and other operations that we don't really have control over. Perhaps forcing a deterministic behavior would create a bias on our tests and there is value on having it the way it is.

**Comment by tmpsantos** [comment]
@springmeyer I think this can't be achieved because of the amount of work we do on worker threads. We could try to run the tests with only one worker thread (might improve) but we still do a lot of asynchronous network requests and other operations that we don't really have control over. Perhaps forcing a deterministic behavior would create a bias on our tests and there is value on having it the way it is.

**Comment by springmeyer** [comment]
@tmpsantos I struggle to see how this is due to worker threads. Can you provide a concrete example that explains the flapping in coverage? What I saw is that there are a half dozen if/else conditions in the code that are not reliably executed in the codebase over the entire test run. I can understand that in a single test, due to asynchronous network you might have tiles loaded in a different order. But I can't understand how that would lead to some conditions being hit in some tests runs and some conditions not being hit in other test runs.

**Comment by tmpsantos** [comment]
I can think of if all the tiles are parsed at once and the map state goes from zero to complete at once, it will not trigger code/signals for partially loaded map (i.e. when 3 out of 4 tiles are loaded). If you have only one worker is more likely you hit partial states.

The best really would be see what is different between runs with different coverage.

**Comment by springmeyer** [comment]
> The best really would be see what is difference between runs with different coverage.

We can look at a recent PR that did not change the code at all. You would expect that the test coverage would not change. However it does, due to this indeterminism. For example:

- Open https://github.com/mapbox/mapbox-gl-native/pull/14903
![Screen Shot 2019-06-12 at 1 41 22 PM](https://user-images.githubusercontent.com/20300/59385190-ae07f780-8d18-11e9-9cce-998ade1dffd9.png)

- View the details for the checks and see the `codecov/patch` has changed:

![Screen Shot 2019-06-12 at 1 36 04 PM](https://user-images.githubusercontent.com/20300/59384470-18b83380-8d17-11e9-962e-8e6b036384b7.png)

 - Open the details link: https://codecov.io/gh/mapbox/mapbox-gl-native/compare/ec0fa4c85a53f189946c42e81745bb1670788228...ebee7cdd58380cbd8d6d37982bf78cf9eb8786e2
 - The red boxes provide clickable links to files with less coverage and the green boxes provide clickable links to files with more coverage:

![Screen Shot 2019-06-12 at 1 38 25 PM](https://user-images.githubusercontent.com/20300/59384589-616fec80-8d17-11e9-9bd0-115a0c58adfc.png)

- Clicking on `line_bucket.cpp` shows that the indeterminism here when a check for when two adjacent coordinates are the same sometimes is hit and sometimes is not:

![Screen Shot 2019-06-12 at 1 39 05 PM](https://user-images.githubusercontent.com/20300/59384707-aa27a580-8d17-11e9-93b0-7e11ed9691bd.png)

- Clicking on `expression.hpp` shows that `EvaluationContext(float zoom_, GeometryTileFeature const * feature_)` is only sometimes called in the tests. NOTICE that jagged lines which denote the coverage that changed:

![Screen Shot 2019-06-12 at 1 41 22 PM](https://user-images.githubusercontent.com/20300/59385203-b6603280-8d18-11e9-87bf-449e144a71ae.png)

We can see that this `EvaluationContext(float zoom_, GeometryTileFeature const * feature_)` was covered in the recent commit to master which we are being compared against:  https://codecov.io/gh/mapbox/mapbox-gl-native/src/ec0fa4c/include/mbgl/style/expression/expression.hpp#L30

**Comment by springmeyer** [comment]
This problem persists.
