### ISSUE TITLE
symbol-z-order not respected when symbols are rendered at different coordinates

### ISSUE THREAD

**Issue by samfader** [mapbox/mapbox-gl-native#13490]
### Steps to reproduce

 1. Pull down symbolzorder-example (https://github.com/mapbox/ios-sdk-examples/pull/245) branch in the ios-sdk-examples app.
 2. Run the app and open the ObjC/Swift version of the `Specify z order of features in a symbol layer` example.
 3. Try switching between the two options presented in the toggle at the bottom of the screen.

### Expected behavior
The icons are arranged in the proper order depending on the symbol-z-order.

[Here](https://github.com/mapbox/mapbox-gl-native/files/2635263/viewport-source.test.zip) is a GL JS example (uploaded as a zip because it includes images) that contains two files - one where the symbol-z-order is set to `source`, and another `viewport-y`. You'll see the z-order of the shapes changes as expected.

### Actual behavior
The icons stay in the same arrangement (z-order).

**GL JS**
_source_
![image](https://user-images.githubusercontent.com/1242056/49319640-9cfd4480-f4b2-11e8-9d86-27c14ecc9846.png)

_viewport_y_
![image](https://user-images.githubusercontent.com/1242056/49319649-af777e00-f4b2-11e8-94c0-e52ec6baedb9.png)

**iOS**
[![Image from Gyazo](https://i.gyazo.com/c9fbb2aeab4dda8523ec5ecc0ffcae45.gif)](https://gyazo.com/c9fbb2aeab4dda8523ec5ecc0ffcae45)

### Configuration

**Mapbox SDK versions:** 4.5.0
**iOS/macOS versions:** iOS 12.1
**Device/simulator models:** iPhone XS Max
**Xcode version:** 10.1

cc @captainbarbosa @ryanhamley

**Comment by samfader** [comment]
Not specifically sure what fixed this but it doesn't appear to be an issue anymore.

**Comment by pozdnyakov** [comment]
> Not specifically sure what fixed this but it doesn't appear to be an issue anymore.

Must be fixed by  https://github.com/mapbox/mapbox-gl-native/pull/14486

**Comment by samfader** [comment]
@pozdnyakov That was my thinking as well and why I came back to this, but I also noticed it was working on v4.5.0 of the iOS SDK. Not sure if I was doing something wrong before or what specifically is going on, but it does appear to be working either way.
