### ISSUE TITLE
Bitrise should upload releases to GitHub too

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1349]
Currently Travis uploads prebuilt releases to an s3 directory with no public file listing, [complicating the manual setup story](https://github.com/mapbox/mapbox-gl-native/wiki/Installing-Mapbox-GL-for-iOS/_compare/cbc4f2345a332b69d9f9a01130efffaec4ab87d4...df38e6f10a123c656cdd5d6a7b662fe04f23fb25) for folks who can’t use CocoaPods. We should configure Travis to [automatically deploy a copy of the prebuilt release to GitHub](http://docs.travis-ci.com/user/deployment/releases/) to be listed [here](https://github.com/mapbox/mapbox-gl-native/releases).

/cc @incanus @bsudekum

**Comment by picciano** [comment]
+1

**Comment by friedbunny** [comment]
Agree with also deploying to Github.

Is @incanus the s3 admin for this? Should be easy to do like http://mapbox-ios-sdk.s3.amazonaws.com/index.html again, I think.

**Comment by incanus** [comment]
Yeah we could start with the `index.html` as an assist to what is up there, but I think the idea of uploading the binary ball to GitHub is cool too as it hangs it on the actual tag/release for people to download. 

Re: S3, anyone with a access to the `mapbox` bucket (`mapbox-gl-native/ios/builds` subfolder) should be able to update that.

**Comment by 1ec5** [comment]
> uploading the binary ball to GitHub is cool too as it hangs it on the actual tag/release for people to download

Yes, otherwise it’s going to confuse people who happen upon our Releases page and wind up with a tarball full of raw source, thinking that’s our release.

**Comment by ljbade** [comment]
@bleege should Android artifacts also end up here? Or should we just link through to maven?

**Comment by 1ec5** [comment]
@ljbade, I think they should, if only to keep people from downloading the source tarball that GitHub provides by default for every tag.

**Comment by bleege** [comment]
> @bleege should Android artifacts also end up here? Or should we just link through to maven?

I'm inclined to to keep them only on Maven Central as there are likely going to be 3rd party dependencies that are going to need to be managed that the iOS side doesn't have to deal with.

**Comment by incanus** [comment]
> if only to keep people from downloading the source tarball that GitHub provides by default for every tag

This is a little clearer now [that we are pushing the product to Github](https://github.com/mapbox/mapbox-gl-native/wiki/Releasing-Mapbox-GL-for-iOS/_compare/804a9423faa129fb5ad607c0cdd9933974264bb2...fb835a3152e5676250affe1623fda2e5b1c1bf9a). This means that [releases are a little clearer about source vs. binary](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v0.2.22).

**Comment by 1ec5** [comment]
https://github.com/mapbox/mapbox-gl-native/issues/1349#issuecomment-99880974 relates to Android releases also needing the same treatment.

**Comment by bleege** [comment]
Yep, I follow that @1ec5 (sorry that it seemed like I was glossing over it).  Maybe I'm not understanding this in its entirety correctly, but from the Android perspective having a binary artifact for download is not helpful on it's own without it's likely 3rd party binary dependencies (i.e. it won't run).  Java isn't as self contained as iOS and is generally bad practice to store 3rd party binaries this way.

**Comment by mikemorris** [comment]
Refs https://github.com/mapbox/node-pre-gyp/issues/134#issuecomment-69281215 for Node.js platform binaries.

**Comment by friedbunny** [comment]
We've moved to Bitrise for iOS and Android builds.

**Comment by 1ec5** [comment]
Bitrise has built-in support for [artifact deployments](https://github.com/bitrise-io/steps-bitrise-artifact-deploy), which would be useful for producing nightly builds. Uploading to GitHub would be swell, though.

**Comment by friedbunny** [comment]
See also: #2844

**Comment by 1ec5** [comment]
I implemented a chain of Bitrise workflows that uploads releases to GitHub. I haven’t figured out s3 deployment, but we could always point the podspec to the file on GitHub. Unfortunately, building all five flavors of a release in one Bitrise build blows way past the build timeout, so we’d need to refactor these workflows to run independently of each other.

**Comment by jfirebaugh** [comment]
Ideally we run multiple package variant builds in parallel. I'm not seeing a way to trigger multiple Bitrise builds on from one push though.

**Comment by 1ec5** [comment]
It is possible for a single push to trigger multiple workflows in parallel, but Bitrise builds can only be triggered by a matching branch name rather than a matching tag name. Please vote for [tag-based triggers](https://bitrise.uservoice.com/forums/235233-general/suggestions/10476936-ability-to-trigger-a-step-or-workflow-only-if-ther) and [real support for parallel builds](https://bitrise.uservoice.com/forums/235233-general/suggestions/13062285-parallel-build-tests).

**Comment by mikemorris** [comment]
So, did the switch to Bitrise for Node.js OS X builds break the binary autopublishing I had set up in https://github.com/mapbox/mapbox-gl-native/pull/2944?

**Comment by jfirebaugh** [comment]
@mikemorris Bitrise has AWS credentials set in secret environment variables, and runs the same `after_script.sh` script, so in theory publishing should still work. Of course, since that step only runs when a tagged release is made, it's hard to test. Are you asking because you're seeing it not work?

**Comment by mikemorris** [comment]
@jfirebaugh Asking because I'm anticipating it won't work when I publish a new release today because

> Bitrise builds can only be triggered by a matching branch name rather than a matching tag name

**Comment by 1ec5** [comment]
I was referring to Bitrise’s “triggers” feature, which allows you to build a particular workflow when commits are pushed to matching branch names. If you’re using some other method that scans each commit message for a certain string, as we used to do on Travis for iOS SDK releases, you’ll be fine.

**Comment by mikemorris** [comment]
Welp, it looks like Bitrise failed to trigger a Node.js OS X build (and therefore failed to publish a binary) on  the fast-forward merge and tag of https://github.com/mapbox/mapbox-gl-native/pull/4659

**Comment by friedbunny** [comment]
We’ve been uploading zipped builds to GitHub releases for some time as part of the scripted deployment, but now it happens even more automatically as part of the tag-based-deploy on CI (#10170).
