### ISSUE TITLE
setCameraPosition sets wrong target

### ISSUE THREAD

**Issue by venv21** [mapbox/mapbox-gl-native#13495]
I want to change the camera center. This works not when I don't provide a zoom level and call setCameraPosition before setting the Zoompreferences. The Target is wrong in this case and centers to a african coast (maybe the default center / coordinate (0,0))

So: (TARGET,MIN=8,MAX=20 are constants)
**This works NOT**

```
mapboxMap.setCameraPosition(new CameraPosition.Builder().target(TARGET).build());

mapboxMap.setMinZoomPreference(MIN);
mapboxMap.setMaxZoomPreference(MAX);
```

**This works**
```
mapboxMap.setMinZoomPreference(MIN);
mapboxMap.setMaxZoomPreference(MAX);

mapboxMap.setCameraPosition(new CameraPosition.Builder().target(TARGET).build());
```

**This works, too**
(this equals the first one which doesn't work but I've added `.zoom(15)`)

```
mapboxMap.setCameraPosition(new CameraPosition.Builder().zoom(15).target(TARGET).build());

mapboxMap.setMinZoomPreference(MIN);
mapboxMap.setMaxZoomPreference(MAX);
```

### Configuration

**Android versions: API 19**  
**Mapbox SDK versions: 6.7**

**Comment by venv21** [comment]
sorry, my previous report was unclear. I've edited it.

**Comment by tobrun** [comment]
This is expected behavior, at zoom 0 you are limited in moving the target camera position (we do not allow scrolling above the north pole or below Antarctica). Is this behavior blocking you to achieve anything particular? Going to close this as works-as-designed but curious to hear more about your use-case.
