### ISSUE TITLE
onMarkerClick and InfoWindowAdapter.getInfoWindow are very hard to get fired

### ISSUE THREAD

**Issue by ugochirico** [mapbox/mapbox-gl-native#13502]
I'm using version 6.5.0.
Device: OnePlus 6

I add several markers on the map as in the image below 
I set the OnMarkClickListner, OnMarkerViewClickListener and the infoadapter as in the code below but when I click on a marker only a few times I got the event fired. it seems very hard to get it fired.
I tried also to set the marker with size 100x100 but same behaviour. It's very hard to get the click event.

```
mMap.setOnMarkerClickListener(new MapboxMap.OnMarkerClickListener() {
            @Override
            public boolean onMarkerClick(@NonNull Marker marker) {
                Log.d(LOGTAG, "marker clicked");
                return false;
            }
        });

mapboxMap.getMarkerViewManager().setOnMarkerViewClickListener(new MapboxMap.OnMarkerViewClickListener() {
            @Override
            public boolean onMarkerClick(@NonNull Marker marker, @NonNull View view, @NonNull MapboxMap.MarkerViewAdapter adapter) {
                Log.d(LOGTAG, "markerview clicked");
                return false;
            }
        });

final MapboxMap.InfoWindowAdapter defaultAdapter = mapboxMap.getInfoWindowAdapter();
        mapboxMap.setInfoWindowAdapter(new MapboxMap.InfoWindowAdapter() {
            @Override
            public View getInfoWindow(final Marker marker) {
                ...
```

![device-2018-12-04-134807](https://user-images.githubusercontent.com/10761533/49443387-98939d00-f7cc-11e8-82e6-da747625b010.png)

**Comment by tobrun** [comment]
@ugochirico we have deprecated both Marker as InfoWindow API with the 7.0.0 Release. You can roll your own click mechanism using MapboxMap#queryRendererFeatures at that will allow you to make the clickable area larger as what we currently do. Since the features are deprecated, closing this issue.
