### ISSUE TITLE
Expose apiBaseUrl option for the Snapshotter

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#13501]
In order to support multiple endpoints, the `Snapshotter` has to expose an option to set the base URL.

**Comment by zugaldia** [comment]
Instead of exposing an additional apiBaseUrl option for the Snapshotter, shouldn't we be respecting the endpoint value set by MapboxMapOptions?

**Comment by LukasPaczos** [comment]
`MapboxMapOptions` are set only during the `MapView` inflation, therefore, not applicable to the snapshotter, which doesn't inflate the view @zugaldia. For the time being we've been porting relevant renderer options that are in the `MapboxMapOptions` to the `MapSnapshotter.Options`.

**Comment by zugaldia** [comment]
@LukasPaczos thanks for the clarification :+1:

**Comment by springmeyer** [comment]
Thanks for ticketing @LukasPaczos. Question: is this also needed for iOS?
