### ISSUE TITLE
[OFFTOPIC] React-native repo maintenance

### ISSUE THREAD

**Issue by StasDoskalenko** [mapbox/mapbox-gl-native#13503]
Hey guys! I'm just curious is [react-native-mapbox-gl ](https://github.com/mapbox/react-native-mapbox-gl)repo still maintained? Because nobody responds both in PRs, Issues and gitter chat.
If not we must consider moving to the other solution. Thanks!

**Comment by asheemmamoowala** [comment]
This issue tracker is for reporting bugs and feature requests to the mapbox-gl-native repo.
