### ISSUE TITLE
function autoresizingMask not documented

### ISSUE THREAD

**Issue by ajRiverav** [mapbox/mapbox-gl-native#13519]
I just want to know why all  [examples](https://www.mapbox.com/help/first-steps-ios-sdk/) include the following two lines but the later is never documented either on the code or in the [MGLMapView](https://www.mapbox.com/ios-sdk/api/maps/4.6.0/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)setZoomLevel:animated:) class: 
```
let mapView = MGLMapView(frame: view.bounds)
mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight] // what is this line for?
```

**Comment by asheemmamoowala** [comment]
[`autoresizingMask`](https://developer.apple.com/documentation/uikit/uiview/1622559-autoresizingmask?language=objc) is a property of the base `UIView` that `MGLMapView` derives from.
