### ISSUE TITLE
Mapbox iOS SDK access token required ?

### ISSUE THREAD

**Issue by kacisse** [mapbox/mapbox-gl-native#13510]
Dear community,

Sorry I'm not a developper so I try to do my best to understand every detail.

Is it mandatory to use a Mapbox Access Token in the **iOS SDK** ?
If I'm not wrong we used a dummy "pk.dummy" token in the **Android SDK** and **it worked**.
However for the iOS I don't know if I can use the same trick ?

Indeed I'm not using any Mapbox request / tiles, I will use my own map URL style in the map object.

Many thanks for the support,

Regards,

**Comment by asheemmamoowala** [comment]
@kacisse the Mapbox Access token is only required if you are using mapbox servers to access style, glyph, sprite, or tile data.
 
For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
