### ISSUE TITLE
How to get Map center in Android MapView?

### ISSUE THREAD

**Issue by ekigamba** [mapbox/mapbox-gl-native#13515]
I have tried using the camera position and target, however it seems not to give me the map center and is usually off by some coordinates. It seems that `com.mapbox.mapboxsdk.maps.Transform` has the map center but is not exposed

**Comment by asheemmamoowala** [comment]
For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/) or [stackoverflow](https://stackoverflow.com/questions/tagged/mapbox+android). This issue tracker is for reporting bugs and feature requests. Thank you!
