### ISSUE TITLE
AndroidLocationEngine::onLocationChanged doesn't work for LocationComponent

### ISSUE THREAD

**Issue by osip-000** [mapbox/mapbox-gl-native#13538]
Hello and thanks for contributing to the Mapbox Maps SDK for Android! To help us diagnose your problem quickly, please:

I try use location component: https://www.mapbox.com/android-docs/maps/overview/location-component/

In onMapReady method I enable LocationComponent
```

override fun onMapReady(mapboxMap: MapboxMap) {
        this.mapboxMap = mapboxMap

        mapboxMap.locationComponent.apply {
            activateLocationComponent(this)
            renderMode = RenderMode.COMPASS
            cameraMode = CameraMode.TRACKING
            isLocationComponentEnabled = true
        }
    }
```

After open app debugger stop on AndroidLocationEngine::onLocaionChanged with correct coordinates. But  `locationListeners` contains one listener - object of TelemetryService, but not `locationEngineListener` from `LocationComponent`

Also in your sample app location is incorrect.

### Configuration

**Android versions: 8.1** 
**Device models: Samsung, Xiaomi** 
**Mapbox SDK versions: 6.7.2**

**Comment by LukasPaczos** [comment]
Thanks for reaching out @osip-000! I tested locally and wasn't able to reproduce the issue either with Google Play Location Services or without. This might come out silly, but could you confirm that `onMapReady` code block is called?  Are you calling `mapView.getMapAsync(this)`? You can follow [this example](https://www.mapbox.com/android-docs/maps/overview/#4-add-a-map).

If yes, could you provide a more detailed example of your setup? Are there any logs printed in the logcat? Any additional info would be appreciated, thanks!

**Comment by osip-000** [comment]
@LukasPaczos thank you for answer.
Yes, I call `mapView.getMapAsync(this)` from onCreate my Activity.

I researched this trouble with debugger. And I identified that object of `AndroidLocationEngine` created two times.
First time it created from your lib. And second created after calling my code:
`mapboxMap.locationComponent.apply {
            activateLocationComponent(this)
            renderMode = RenderMode.COMPASS
            cameraMode = CameraMode.TRACKING
            isLocationComponentEnabled = true
}`

Then, `AndroidLocationEngine#onLocationChanged()`  method calling for first object. And `locationListeners` contains only listener - object of TelementryService.

**Comment by LukasPaczos** [comment]
Thanks for trying to debug the issue.

> And I identified that lib creates two objects of AndroidLocationEngine.

> Then, AndroidLocationEngine#onLocationChanged() method calling for first object. And locationListeners contains only listener - object of TelementryService.

This is expected. Does the second `AndroidLocationEngine` object not contain any listeners? Could you debug calls to `LocationEngine#addLocationEngineListener` and `LocationEngine#removeLocationEngineListener` inside of the `LocationComponent`? Thanks!

**Comment by osip-000** [comment]
@LukasPaczos yes, `LocationEngine#addLocationEngineListener` called, when I activate location component.

I think that I found root of the trouble! It's flag `LocationEnginePriority#HIGH_ACCURACY`.
In TelementryService you create LocatonEngine with 'NO_POWER', but in LocationComponent you create with `HIGH_ACCURACY`.

I tried create a object of LocationEngine in my Activity with next code:
```
locationEngine = LocationEngineProvider(this).obtainBestLocationEngineAvailable()       locationEngine.priority = LocationEnginePriority.NO_POWER        locationEngine.addLocationEngineListener(this)
locationEngine.activate()
```

And then I activated LocationComponent:
```
mapboxMap.locationComponent.apply {
    activateLocationComponent(this@MapActivity, this@MapActivity.locationEngine)
    isLocationComponentEnabled = true
    cameraMode = CameraMode.TRACKING
    renderMode = RenderMode.COMPASS
}
```

After AndroidLocationEngine works perfect!

**Comment by LukasPaczos** [comment]
Glad that it's working for you! So just to confirm, setting
```
locationEngine.priority = LocationEnginePriority.HIGH_ACCURACY
```
was not working for you?

Has above been a known issue @electrostat @andrlee? Is there a chance of a similar bug in the `4.x` of the core library?

**Comment by osip-000** [comment]
Yes. `locationEngine.priority = LocationEnginePriority.HIGH_ACCURACY` doesn't work for me.
But I want that it works. Because without Internet connection my location wrong also.

**Comment by osip-000** [comment]
> Has above been a known issue @electrostat @andrlee? Is there a chance of a similar bug in the 4.x of the core library?

@LukasPaczos could you send link for those issues?
