### ISSUE TITLE
Invalidate NSURLSession In Metrics

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1354]
Look into optimizing the NSURLSession lifecycle and clean up memory usage where it's not needed.

<https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSession_class/#//apple_ref/occ/clm/NSURLSession/sessionWithConfiguration:delegate:delegateQueue:>

@mapbox/mobile

**Comment by 1ec5** [comment]
It’s probably enough to call [`-invalidateAndCancel`](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSession_class/#//apple_ref/occ/instm/NSURLSession/invalidateAndCancel) or [`-finishTasksAndInvalidate`](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSession_class/#//apple_ref/occ/instm/NSURLSession/finishTasksAndInvalidate) in `-[MGLMapboxEvents dealloc]`.

**Comment by 1ec5** [comment]
The saga continues in #1382.

**Comment by bleege** [comment]
:+1:
