### ISSUE TITLE
Upgrade default styles to v11

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#13553]
When version 11 of the Mapbox Streets style and other Mapbox-designed styles are released, the following constants will need to be updated:

https://github.com/mapbox/mapbox-gl-native/blob/2d527c2af7224d03429b8b2ccb7c1712e8ffe12b/platform/default/mbgl/util/default_styles.hpp#L16-L21

The style versions have also been hard-coded elsewhere; see mapbox/mapbox-gl-native#6301 for pointers.

/cc @mapbox/maps-ios @mapbox/maps-android @brsbl

**Comment by LukasPaczos** [comment]
https://github.com/mapbox/mapbox-gl-native/pull/13585 and https://github.com/mapbox/mapbox-gl-native/pull/13615 landed so I think we're good to close here.
