### ISSUE TITLE
Android 7.0.0-beta.1 - Initial mapview startup results in black screen for a few seconds

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#13566]
After updating to Android Mapbox 7.0.0-beta.1, the initial mapview state is a black screen for 1-2s. That issue has been fixed in the past by https://github.com/mapbox/mapbox-gl-native/pull/12377. Is it possible that some changes broke that implementation? Can I provide more information to help fix that issue?

**Mapbox SDK versions:** 7.0.0-beta.1

Edit: I tried to define mapbox_foregroundLoadColor, but it had no effect.

**Comment by tobrun** [comment]
This stems from decoupling style loading from OnMapReady, we start to render more early without any content. Will look into patching this up so it behaves as expected.

**Comment by Mordag** [comment]
@tobrun Is it possible that this behavior is fixed for the 7.0.0 release?

**Comment by tobrun** [comment]
I'm having trouble reproducing:

![ezgif com-gif-maker 6](https://user-images.githubusercontent.com/2151639/49957294-a43b3e00-ff07-11e8-83fa-b9361753278c.gif)

Can you share a minimal reproducible example?

**Comment by Mordag** [comment]
@tobrun I've just created an example project, but I saw that @LukasPaczos already created a PR. Let me know if this example project is still relevant.
