### ISSUE TITLE
How to add multiple icon in MGLSymbolStyleLayer > iconImageName?

### ISSUE THREAD

**Issue by tester87** [mapbox/mapbox-gl-native#13568]
Hi all,

Any idea to add in multiple image icon in unclustered? I stuck over here a couple of days but could not find out solution. May I know any update from Mapbox to cater this? Seem like very common to use multiple image icon after zoom in details.
Please help, thank you.

**Comment by asheemmamoowala** [comment]
The `iconImageName` supports runtime styling expressions, as shown in this [example](https://www.mapbox.com/ios-sdk/maps/examples/clustering-with-images/)

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
