### ISSUE TITLE
document node dependency, don't hang silently if not installed

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1358]
If you don't have node installed, `make test-*` hangs silently. Instead it should output a reasonable error message. Also, the node dependency should be mentioned in the README.

**Comment by mikemorris** [comment]
I swear we dropped the node dependency at some point and rewrote a few scripts in Python instead (which is needed already for gyp) so it wouldn't be needed.

**Comment by kkaefer** [comment]
The tests need node to run a http server with specially crafted responses.
