### ISSUE TITLE
Log flooding with JVMTI error 15

### ISSUE THREAD

**Issue by BuNny1123** [mapbox/mapbox-gl-native#13589]
Log flooding with JVMTI error 15

Logs:
12-16 13:37:14.539 5564-5564/com.example.bunny.stareinmap D/SurfaceView: BG show() Surface(name=Background for - SurfaceView - com.example.bunny.stareinmap/com.example.bunny.stareinmap.HomeActivity.HomeNavActivity@7af9ffd@0) android.opengl.GLSurfaceView{7af9ffd V.E...... ......ID 0,0-1080,1726}
12-16 13:37:14.542 5564-5564/com.example.bunny.stareinmap D/SurfaceView: surfaceCreated 1 #8 android.opengl.GLSurfaceView{7af9ffd V.E...... ......ID 0,0-1080,1726}
12-16 13:37:14.543 5564-5564/com.example.bunny.stareinmap D/SurfaceView: surfaceChanged (1080,1726) 1 #8 android.opengl.GLSurfaceView{7af9ffd V.E...... ......ID 0,0-1080,1726}
12-16 13:37:14.546 5564-6723/com.example.bunny.stareinmap I/Mbgl-EGLConfigChooser: In emulator: false
12-16 13:37:14.556 5564-6723/com.example.bunny.stareinmap D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1080x1726]-format:2
12-16 13:37:14.561 5564-6723/com.example.bunny.stareinmap I/Mbgl: {GLThread 4958}[General]: GPU Identifier: Mali-T830
12-16 13:37:14.578 5564-6723/com.example.bunny.stareinmap D/libGLESv2: STS_GLApi : DTS, ODTC are not allowed for Package : com.example.bunny.stareinmap
12-16 13:37:14.804 5564-5564/com.example.bunny.stareinmap D/ViewRootImpl@d9f35e1[HomeNavActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 1920) ci=Rect(0, 63 - 0, 0) vi=Rect(0, 63 - 0, 0) or=1
12-16 13:37:14.805 5564-5564/com.example.bunny.stareinmap D/ViewRootImpl@d9f35e1[HomeNavActivity]: MSG_WINDOW_FOCUS_CHANGED 1
12-16 13:37:15.296 5564-5564/com.example.bunny.stareinmap W/zygote: Verification of void com.mapbox.mapboxsdk.maps.AnnotationManager.<init>(com.mapbox.mapboxsdk.maps.NativeMapView, com.mapbox.mapboxsdk.maps.MapView, android.support.v4.util.LongSparseArray, com.mapbox.mapboxsdk.annotations.MarkerViewManager, com.mapbox.mapboxsdk.maps.IconManager, com.mapbox.mapboxsdk.maps.Annotations, com.mapbox.mapboxsdk.maps.Markers, com.mapbox.mapboxsdk.maps.Polygons, com.mapbox.mapboxsdk.maps.Polylines, com.mapbox.mapboxsdk.maps.ShapeAnnotations) took 159.961ms
12-16 13:37:15.308 5564-5578/com.example.bunny.stareinmap I/zygote: Background concurrent copying GC freed 1081(544KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 9MB/18MB, paused 210us total 454.618ms
12-16 13:37:15.518 5564-5564/com.example.bunny.stareinmap D/InputMethodManager: startInputInner - Id : 0
12-16 13:37:15.519 5564-5564/com.example.bunny.stareinmap I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
12-16 13:37:15.524 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel constructed: fd=136
12-16 13:37:15.524 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel destroyed: fd=112
12-16 13:37:15.626 5564-6719/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.626 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.626 5564-6719/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.626 5564-6719/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-15 identical 1 line
12-16 13:37:15.626 5564-6719/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.627 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.627 5564-6719/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.627 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.627 5564-6719/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.627 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.627 5564-6719/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.627 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.627 5564-6721/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-18 identical 1 line
12-16 13:37:15.627 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.631 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
    JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.631 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.631 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.631 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.631 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.631 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.631 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.631 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.631 5564-6721/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-18 identical 1 line
12-16 13:37:15.631 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.631 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.631 5564-6722/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.631 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.631 5564-6722/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.632 5564-6722/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.632 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.632 5564-6722/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.632 5564-6722/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-19 identical 2 lines
12-16 13:37:15.632 5564-6722/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.633 5564-6719/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.634 5564-6719/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-20 identical 5 lines
12-16 13:37:15.634 5564-6719/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.681 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.682 5564-6720/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-21 identical 5 lines
12-16 13:37:15.682 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.683 5564-5564/com.example.bunny.stareinmap I/Choreographer: Skipped 49 frames!  The application may be doing too much work on its main thread.
12-16 13:37:15.736 5564-6722/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.737 5564-6722/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-22 identical 5 lines
12-16 13:37:15.737 5564-6722/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.748 5564-5564/com.example.bunny.stareinmap D/ViewRootImpl@d9f35e1[HomeNavActivity]: Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x1 surface={valid=true 3329380352} changed=false
12-16 13:37:15.789 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.790 5564-6720/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-23 identical 5 lines
12-16 13:37:15.790 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.834 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.834 5564-6721/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-24 identical 5 lines
12-16 13:37:15.835 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.843 5564-6722/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.853 5564-6722/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-29 identical 33 lines
12-16 13:37:15.853 5564-6722/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.858 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.859 5564-6721/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-30 identical 5 lines
12-16 13:37:15.859 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.870 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.870 5564-6720/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-31 identical 5 lines
12-16 13:37:15.871 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.894 5564-5564/com.example.bunny.stareinmap D/ViewRootImpl@2361262[OTPVerificationActivity]: dispatchDetachedFromWindow
12-16 13:37:15.894 5564-5564/com.example.bunny.stareinmap D/InputEventReceiver: channel '5e21eaf com.example.bunny.stareinmap/com.example.bunny.stareinmap.LoginAndRegisterActivity.OTPVerificationActivity (client)' ~ Disposing input event receiver.
    channel '5e21eaf com.example.bunny.stareinmap/com.example.bunny.stareinmap.LoginAndRegisterActivity.OTPVerificationActivity (client)' ~NativeInputEventReceiver.
12-16 13:37:15.900 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel destroyed: fd=108
12-16 13:37:15.905 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.905 5564-6720/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-32 identical 5 lines
12-16 13:37:15.905 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.922 5564-6719/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.924 5564-6719/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-33 identical 5 lines
12-16 13:37:15.924 5564-6719/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.930 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.931 5564-6721/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-37 identical 5 lines
12-16 13:37:15.931 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.940 5564-6722/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.940 5564-6722/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-38 identical 5 lines
12-16 13:37:15.940 5564-6722/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.955 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.955 5564-6720/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-36 identical 5 lines
12-16 13:37:15.955 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.956 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.957 5564-6721/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-37 identical 5 lines
12-16 13:37:15.957 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.963 5564-6722/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.963 5564-6722/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-38 identical 5 lines
12-16 13:37:15.963 5564-6722/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.977 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:15.979 5564-6720/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-39 identical 5 lines
12-16 13:37:15.979 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:19.519 5564-5612/com.example.bunny.stareinmap I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
12-16 13:37:19.520 5564-5612/com.example.bunny.stareinmap I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
12-16 13:37:24.294 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.294 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.294 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.295 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.295 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.295 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.295 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.295 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.295 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
    JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.295 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.296 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.296 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.296 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.364 5564-6719/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.365 5564-6719/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-43 identical 5 lines
12-16 13:37:24.365 5564-6719/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.389 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.390 5564-6720/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-44 identical 5 lines
12-16 13:37:24.390 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.402 5564-6722/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.402 5564-6722/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-45 identical 5 lines
12-16 13:37:24.402 5564-6722/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.416 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:24.417 5564-6721/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-46 identical 5 lines
12-16 13:37:24.417 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:29.009 5564-5578/com.example.bunny.stareinmap I/zygote: Background concurrent copying GC freed 130647(4MB) AllocSpace objects, 128(5MB) LOS objects, 50% free, 8MB/17MB, paused 307us total 1.621s
12-16 13:37:34.499 5564-5612/com.example.bunny.stareinmap I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
12-16 13:37:34.501 5564-5612/com.example.bunny.stareinmap I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
12-16 13:37:35.034 5564-6722/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:35.035 5564-6722/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-47 identical 5 lines
12-16 13:37:35.035 5564-6722/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:35.035 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:35.035 5564-6720/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-49 identical 2 lines
12-16 13:37:35.036 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:35.036 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:35.036 5564-6721/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-48 identical 5 lines
12-16 13:37:35.036 5564-6721/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:35.037 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:35.037 5564-6720/com.example.bunny.stareinmap I/chatty: uid=10443(com.example.bunny.stareinmap) Thread-49 identical 1 line
12-16 13:37:35.038 5564-6720/com.example.bunny.stareinmap E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
12-16 13:37:37.150 5564-5564/com.example.bunny.stareinmap D/InputMethodManager: startInputInner - Id : 0
12-16 13:37:37.151 5564-5564/com.example.bunny.stareinmap I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
12-16 13:37:37.154 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel constructed: fd=112
12-16 13:37:37.154 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel destroyed: fd=136
12-16 13:37:37.194 5564-5564/com.example.bunny.stareinmap D/InputMethodManager: startInputInner - Id : 0
12-16 13:37:37.195 5564-5564/com.example.bunny.stareinmap I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
12-16 13:37:37.197 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel constructed: fd=135
12-16 13:37:37.198 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel destroyed: fd=112
12-16 13:37:37.221 5564-5564/com.example.bunny.stareinmap D/InputMethodManager: startInputInner - Id : 0
12-16 13:37:37.222 5564-5564/com.example.bunny.stareinmap I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
12-16 13:37:37.225 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel constructed: fd=112
12-16 13:37:37.225 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel destroyed: fd=135
12-16 13:37:37.257 5564-5564/com.example.bunny.stareinmap D/InputMethodManager: startInputInner - Id : 0
12-16 13:37:37.258 5564-5564/com.example.bunny.stareinmap I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
12-16 13:37:37.260 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel constructed: fd=135
12-16 13:37:37.261 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel destroyed: fd=112
12-16 13:37:37.284 5564-5564/com.example.bunny.stareinmap D/InputMethodManager: startInputInner - Id : 0
12-16 13:37:37.286 5564-5564/com.example.bunny.stareinmap I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
12-16 13:37:37.289 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel constructed: fd=112
    Input channel destroyed: fd=135
12-16 13:37:37.317 5564-5564/com.example.bunny.stareinmap D/InputMethodManager: startInputInner - Id : 0
12-16 13:37:37.319 5564-5564/com.example.bunny.stareinmap I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
12-16 13:37:37.323 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel constructed: fd=135
12-16 13:37:37.324 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel destroyed: fd=112
12-16 13:37:37.352 5564-5564/com.example.bunny.stareinmap D/InputMethodManager: startInputInner - Id : 0
12-16 13:37:37.354 5564-5564/com.example.bunny.stareinmap I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
12-16 13:37:37.360 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel constructed: fd=112
    Input channel destroyed: fd=135
12-16 13:37:37.388 5564-5564/com.example.bunny.stareinmap D/InputMethodManager: startInputInner - Id : 0
12-16 13:37:37.389 5564-5564/com.example.bunny.stareinmap I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
12-16 13:37:37.392 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel constructed: fd=136
12-16 13:37:37.393 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel destroyed: fd=112
12-16 13:37:37.420 5564-5564/com.example.bunny.stareinmap D/InputMethodManager: startInputInner - Id : 0
12-16 13:37:37.421 5564-5564/com.example.bunny.stareinmap I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
12-16 13:37:37.424 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel constructed: fd=112
    Input channel destroyed: fd=136
12-16 13:37:37.450 5564-5564/com.example.bunny.stareinmap D/InputMethodManager: startInputInner - Id : 0
12-16 13:37:37.451 5564-5564/com.example.bunny.stareinmap I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
12-16 13:37:37.454 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel constructed: fd=135
12-16 13:37:37.454 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel destroyed: fd=112
12-16 13:37:37.481 5564-5564/com.example.bunny.stareinmap D/InputMethodManager: startInputInner - Id : 0
12-16 13:37:37.482 5564-5564/com.example.bunny.stareinmap I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
12-16 13:37:37.484 5564-5564/com.example.bunny.stareinmap D/InputTransport: Input channel constructed: fd=112
    Input channel destroyed: fd=135
12-16 13:37:37.512 5564-5564/com.example.bunny.stareinmap D/InputMethodManager: startInputInner - Id : 0
12-16 13:37:37.513 5564-5564/com.example.bunny.stareinmap I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus

**Comment by LukasPaczos** [comment]
Thanks for reaching out @BuNny1123. We've noticed this issue before, however, we've never seen it impact production runtimes, only the ones attached to the debugger.

We'll post here whenever we know more.
