### ISSUE TITLE
animateCamera is not working during onMapReady anymore

### ISSUE THREAD

**Issue by siavashabdoli** [mapbox/mapbox-gl-native#13590]
open app and in on map ready try to Animate Camera to specific location in `onMapReady` callback (it's useful for deep link or some other scenario) 

### Expected behavior
animate camera to that location
we were using 6.4.0 version and it was working well but after we update it to 6.7.0 it's not working anymore

### Actual behavior
animateCamera is not working and seems camera position is set by mapbox itself at the beginning 
I think that can be related to `onPostMapReady` function that invalidateCamera Position. you can provide optional callback after `onPostMapReady` for this purpose or do not edit camera position when someone set it from `onMapReady` :D

### Configuration

**Android versions: version 8 and 9 tested but it should be on all devices**
**Device models: pixel and samsung** 
**Mapbox SDK versions:6.7.0** 

BTW we temporarily fix this by adding 500ms delay but it's not good way. as you know android have lots of lifecycle problems and it can lead to some new headache.

**Comment by LukasPaczos** [comment]
Thanks for reaching out @siavashabdoli! I wasn't able to reproduce the mentioned issue. I tried calling `animateCamera` right when the `onMapReady` has been delivered, either in a `Fragment` or `Activity` and with style changes in between but haven't run into any problems.

Would you mind sharing a bit more about your setup or provide a minimal reproducible example?
