### ISSUE TITLE
Build latest-release(6.7.2) source failure

### ISSUE THREAD

**Issue by AliKhoshraftar** [mapbox/mapbox-gl-native#13593]
Hey.

### **Steps to reproduce**

I had compile and successfully publish my mapboxgl as .aar library when i follow this instructions : 
[https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android](url)
As i know this instruction clone whole project of mapbox-gl ( at now about 250MB ) , but my problem is that i download android latest-release zip source code from here : 
[https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v6.7.2](url)

### **Expected behavior**

Same result as previous approach

### **Actual behavior**

But it doesn't compile successfully.
Also i changed NDK version to r17 but still not working ( in previous approach i should revert ndk to r17 to build it successfully , otherwise it won't build )

I got these errors that are same as the errors that i got in previous approach without changing NDK version in project structure : 

`Build command failed.

Error while executing process /home/ali/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map -B/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/x86 -DANDROID_ABI=x86 -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/build/intermediates/cmake/debug/obj/x86 -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=/home/ali/Android/sdk/android-ndk-r17c -DCMAKE_C_FLAGS=-Qunused-arguments -DCMAKE_CXX_FLAGS=-Qunused-arguments -DCMAKE_TOOLCHAIN_FILE=/home/ali/Android/sdk/android-ndk-r17c/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/home/ali/Android/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static -DANDROID_CPP_FEATURES=rtti;exceptions -DMBGL_PLATFORM=android -DMASON_PLATFORM=android -DNodeJS_EXECUTABLE=/usr/bin/node -Dnpm_EXECUTABLE=/usr/bin/npm -DANDROID_CCACHE=/usr/bin/ccache}

-- Check for working CXX compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++

-- Check for working CXX compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Check for working C compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang

-- Check for working C compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Updating submodules...

-- Running 'npm install' for mapbox-gl-js...

-- Finished 'npm install' for mapbox-gl-js...

-- Configuring incomplete, errors occurred!

See also "/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/x86/CMakeFiles/CMakeOutput.log".

pathspec 'mapbox-gl-js' did not match any file(s) known to git.

CMake Error at cmake/mbgl.cmake:54 (message):

Call Stack (most recent call first):

  cmake/mbgl.cmake:97 (_npm_install)

  CMakeLists.txt:11 (include)

Build command failed.

Error while executing process /home/ali/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map -B/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/x86_64 -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/build/intermediates/cmake/debug/obj/x86_64 -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=/home/ali/Android/sdk/android-ndk-r17c -DCMAKE_C_FLAGS=-Qunused-arguments -DCMAKE_CXX_FLAGS=-Qunused-arguments -DCMAKE_TOOLCHAIN_FILE=/home/ali/Android/sdk/android-ndk-r17c/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/home/ali/Android/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static -DANDROID_CPP_FEATURES=rtti;exceptions -DMBGL_PLATFORM=android -DMASON_PLATFORM=android -DNodeJS_EXECUTABLE=/usr/bin/node -Dnpm_EXECUTABLE=/usr/bin/npm -DANDROID_CCACHE=/usr/bin/ccache}

-- Check for working CXX compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++

-- Check for working CXX compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Check for working C compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang

-- Check for working C compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Updating submodules...

pathspec 'mapbox-gl-js' did not match any file(s) known to git.

-- Running 'npm install' for mapbox-gl-js...

-- Finished 'npm install' for mapbox-gl-js...

CMake Error at cmake/mbgl.cmake:54 (message):

Call Stack (most recent call first):

  cmake/mbgl.cmake:97 (_npm_install)

  CMakeLists.txt:11 (include)

-- Configuring incomplete, errors occurred!

See also "/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/x86_64/CMakeFiles/CMakeOutput.log".

Build command failed.

Error while executing process /home/ali/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map -B/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/release/x86_64 -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/build/intermediates/cmake/release/obj/x86_64 -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=/home/ali/Android/sdk/android-ndk-r17c -DCMAKE_C_FLAGS=-Qunused-arguments -DCMAKE_CXX_FLAGS=-Qunused-arguments -DCMAKE_TOOLCHAIN_FILE=/home/ali/Android/sdk/android-ndk-r17c/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/home/ali/Android/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static -DANDROID_CPP_FEATURES=rtti;exceptions -DMBGL_PLATFORM=android -DMASON_PLATFORM=android -DNodeJS_EXECUTABLE=/usr/bin/node -Dnpm_EXECUTABLE=/usr/bin/npm -DANDROID_CCACHE=/usr/bin/ccache}

-- Check for working CXX compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++

-- Check for working CXX compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Check for working C compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang

-- Check for working C compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Updating submodules...

pathspec 'mapbox-gl-js' did not match any file(s) known to git.

-- Running 'npm install' for mapbox-gl-js...

-- Finished 'npm install' for mapbox-gl-js...

CMake Error at cmake/mbgl.cmake:54 (message):

Call Stack (most recent call first):

  cmake/mbgl.cmake:97 (_npm_install)

  CMakeLists.txt:11 (include)

-- Configuring incomplete, errors occurred!

See also "/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/release/x86_64/CMakeFiles/CMakeOutput.log".

Build command failed.

Error while executing process /home/ali/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map -B/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/build/intermediates/cmake/debug/obj/armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=/home/ali/Android/sdk/android-ndk-r17c -DCMAKE_C_FLAGS=-Qunused-arguments -DCMAKE_CXX_FLAGS=-Qunused-arguments -DCMAKE_TOOLCHAIN_FILE=/home/ali/Android/sdk/android-ndk-r17c/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/home/ali/Android/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static -DANDROID_CPP_FEATURES=rtti;exceptions -DMBGL_PLATFORM=android -DMASON_PLATFORM=android -DNodeJS_EXECUTABLE=/usr/bin/node -Dnpm_EXECUTABLE=/usr/bin/npm -DANDROID_CCACHE=/usr/bin/ccache}

-- Check for working CXX compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++

-- Check for working CXX compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Check for working C compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang

-- Check for working C compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Updating submodules...

-- Running 'npm install' for mapbox-gl-js...

-- Finished 'npm install' for mapbox-gl-js...

-- Configuring incomplete, errors occurred!

See also "/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeOutput.log".

pathspec 'mapbox-gl-js' did not match any file(s) known to git.

CMake Error at cmake/mbgl.cmake:54 (message):

Call Stack (most recent call first):

  cmake/mbgl.cmake:97 (_npm_install)

  CMakeLists.txt:11 (include)

Build command failed.

Error while executing process /home/ali/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map -B/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/release/armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/build/intermediates/cmake/release/obj/armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=/home/ali/Android/sdk/android-ndk-r17c -DCMAKE_C_FLAGS=-Qunused-arguments -DCMAKE_CXX_FLAGS=-Qunused-arguments -DCMAKE_TOOLCHAIN_FILE=/home/ali/Android/sdk/android-ndk-r17c/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/home/ali/Android/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static -DANDROID_CPP_FEATURES=rtti;exceptions -DMBGL_PLATFORM=android -DMASON_PLATFORM=android -DNodeJS_EXECUTABLE=/usr/bin/node -Dnpm_EXECUTABLE=/usr/bin/npm -DANDROID_CCACHE=/usr/bin/ccache}

-- Check for working CXX compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++

-- Check for working CXX compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Check for working C compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang

-- Check for working C compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Updating submodules...

pathspec 'mapbox-gl-js' did not match any file(s) known to git.

-- Running 'npm install' for mapbox-gl-js...

-- Finished 'npm install' for mapbox-gl-js...

CMake Error at cmake/mbgl.cmake:54 (message):

Call Stack (most recent call first):

  cmake/mbgl.cmake:97 (_npm_install)

  CMakeLists.txt:11 (include)

-- Configuring incomplete, errors occurred!

See also "/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeOutput.log".

Build command failed.

Error while executing process /home/ali/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map -B/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/arm64-v8a -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/build/intermediates/cmake/debug/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=/home/ali/Android/sdk/android-ndk-r17c -DCMAKE_C_FLAGS=-Qunused-arguments -DCMAKE_CXX_FLAGS=-Qunused-arguments -DCMAKE_TOOLCHAIN_FILE=/home/ali/Android/sdk/android-ndk-r17c/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/home/ali/Android/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static -DANDROID_CPP_FEATURES=rtti;exceptions -DMBGL_PLATFORM=android -DMASON_PLATFORM=android -DNodeJS_EXECUTABLE=/usr/bin/node -Dnpm_EXECUTABLE=/usr/bin/npm -DANDROID_CCACHE=/usr/bin/ccache}

-- Check for working CXX compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++

-- Check for working CXX compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Check for working C compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang

-- Check for working C compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Updating submodules...

pathspec 'mapbox-gl-js' did not match any file(s) known to git.

CMake Error at cmake/mbgl.cmake:54 (message):

Call Stack (most recent call first):

  cmake/mbgl.cmake:97 (_npm_install)

  CMakeLists.txt:11 (include)

-- Running 'npm install' for mapbox-gl-js...

-- Finished 'npm install' for mapbox-gl-js...

-- Configuring incomplete, errors occurred!

See also "/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/arm64-v8a/CMakeFiles/CMakeOutput.log".

Build command failed.

Error while executing process /home/ali/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map -B/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/release/x86 -DANDROID_ABI=x86 -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/build/intermediates/cmake/release/obj/x86 -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=/home/ali/Android/sdk/android-ndk-r17c -DCMAKE_C_FLAGS=-Qunused-arguments -DCMAKE_CXX_FLAGS=-Qunused-arguments -DCMAKE_TOOLCHAIN_FILE=/home/ali/Android/sdk/android-ndk-r17c/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/home/ali/Android/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static -DANDROID_CPP_FEATURES=rtti;exceptions -DMBGL_PLATFORM=android -DMASON_PLATFORM=android -DNodeJS_EXECUTABLE=/usr/bin/node -Dnpm_EXECUTABLE=/usr/bin/npm -DANDROID_CCACHE=/usr/bin/ccache}

-- Check for working CXX compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++

-- Check for working CXX compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Check for working C compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang

-- Check for working C compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Updating submodules...

pathspec 'mapbox-gl-js' did not match any file(s) known to git.

-- Running 'npm install' for mapbox-gl-js...

-- Finished 'npm install' for mapbox-gl-js...

CMake Error at cmake/mbgl.cmake:54 (message):

Call Stack (most recent call first):

  cmake/mbgl.cmake:97 (_npm_install)

  CMakeLists.txt:11 (include)

-- Configuring incomplete, errors occurred!

See also "/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/release/x86/CMakeFiles/CMakeOutput.log".

The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Open File

Build command failed.

Error while executing process /home/ali/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map -B/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/release/arm64-v8a -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/build/intermediates/cmake/release/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=/home/ali/Android/sdk/android-ndk-r17c -DCMAKE_C_FLAGS=-Qunused-arguments -DCMAKE_CXX_FLAGS=-Qunused-arguments -DCMAKE_TOOLCHAIN_FILE=/home/ali/Android/sdk/android-ndk-r17c/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/home/ali/Android/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static -DANDROID_CPP_FEATURES=rtti;exceptions -DMBGL_PLATFORM=android -DMASON_PLATFORM=android -DNodeJS_EXECUTABLE=/usr/bin/node -Dnpm_EXECUTABLE=/usr/bin/npm -DANDROID_CCACHE=/usr/bin/ccache}

-- Check for working CXX compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++

-- Check for working CXX compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Check for working C compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang

-- Check for working C compiler: /home/ali/Android/sdk/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Updating submodules...

pathspec 'mapbox-gl-js' did not match any file(s) known to git.

-- Running 'npm install' for mapbox-gl-js...

CMake Error at cmake/mbgl.cmake:54 (message):

Call Stack (most recent call first):

  cmake/mbgl.cmake:97 (_npm_install)

  CMakeLists.txt:11 (include)

-- Finished 'npm install' for mapbox-gl-js...

-- Configuring incomplete, errors occurred!

See also "/home/ali/Android/Projects/Shiveh/SDKs/Map/android-sdk-v3-map/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/release/arm64-v8a/CMakeFiles/CMakeOutput.log".
`

**Comment by tobrun** [comment]
Downloading as zip won't pull in the submodules:

> pathspec 'mapbox-gl-js' did not match any file(s) known to git.

Getting this configured properly will resolve the build issue shown in OP.
