### ISSUE TITLE
testDelegateRegionDidChange is too fragile

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1360]
I'm seeing relatively frequent test failures, but they're not reproducible. It looks like they heavily depend on timing.

See https://travis-ci.org/mapbox/mapbox-gl-native/jobs/60350680#L1051

@incanus @1ec5

**Comment by friedbunny** [comment]
Says it's doing two unanimated changes when it should only be performing one.

```
testDelegateRegionDidChange, ((unanimatedCount) equal to (1)) failed: ("2") is not equal to ("1") - regionDidChange delegate should indicate one unanimated change
```

**Comment by friedbunny** [comment]
I think [L416's](https://github.com/mapbox/mapbox-gl-native/blob/f9c544a9ea0f9a321616fbc7147f67b5c90b7832/test/ios/MapViewTests.m#L416) `regionDidChange delegate should indicate one unanimated change` is getting bogged down and executing after the next test case.

If that's correct, then this should fix it:

```diff
diff --git a/test/ios/MapViewTests.m b/test/ios/MapViewTests.m
index fff52ad..08a867d 100644
--- a/test/ios/MapViewTests.m
+++ b/test/ios/MapViewTests.m
@@ -406,7 +406,7 @@
                                                    tester.mapView.centerCoordinate = CLLocationCoordinate2DMake(0, 0);
                                                }];
 
-    [tester waitForTimeInterval:1];
+    [tester waitForAnimationsToFinishWithTimeout:1];
 
     XCTAssertEqual([notification.userInfo[@"animated"] boolValue],
                    NO,
@@ -415,6 +415,8 @@
                    1,
                    @"regionDidChange delegate should indicate one unanimated change");
 
+    [tester waitForTimeInterval:1];
+
     notification = [system waitForNotificationName:@"regionDidChangeAnimated"
                                             object:tester.mapView
                                whileExecutingBlock:^{
```

**Comment by friedbunny** [comment]
Noooope, other way around. The test is failing because it's not waiting long enough for the environment to be reset and it's catching that.

**Comment by incanus** [comment]
This is looking great when testing locally and we can probably roll this into reenabling CI iOS tests in https://github.com/mapbox/mapbox-gl-native/issues/1452. We'll give everything some care then to avoid false-positives like this one.
