### ISSUE TITLE
Change marker icon on zoom

### ISSUE THREAD

**Issue by halbaka** [mapbox/mapbox-gl-native#13626]
Hi, this isn't really a bug, but I don't know where to get an answer on this.

On certain zoomlevels I iterate over all markers and change the icon size by applying another (smaller) icon 

```

if(mapboxMap.getCameraPosition.zoom < 12) {
    for(Marker marker : mapboxMap.getMarkers()) { 
        marker.setIcon(iconxy); 
    }
}
```

This works fine but doesn't perform well when many markers are on the map. Is there a way to do this faster? Sadly in Java there are no pointers..

Thanks

**Comment by kkaefer** [comment]
@halbaka a much faster way would be to change your style to use zoom dependent styling and select a larger sprite for zooms >= 12. Then, you don't have to write any custom code as the icons will be automatically changed once the zoom level boundary is crossed.

**Comment by halbaka** [comment]
Thanks. The markers aren't static but dynamically created and removed on runtime. 
To use zoom dependent styling, I need to replace the markers with SymbolLayer annotations, right?
