### ISSUE TITLE
Unusual map behavior with ViewPager ScrollView on Android 7

### ISSUE THREAD

**Issue by paulhristea** [mapbox/mapbox-gl-native#13622]
### Steps to reproduce

 Place the MapView in a ScrollView on one of a ViewPager's views

### Expected behavior

When scrolling the ScrollView vertically or the ViewPager horizontally, the MapView should maintain its GPS positioning, and the whole MapView should move vertically/horizontally with its parent views

### Actual behavior

On Android 7 and 7.1.1 (all I could test), the MapView moves along with the parent views, but the map's GPS positioning moves as well, as though the MapView is fullscreen and placed underneath the ScrollView & ViewPager, and as if these views are scrolling accross a fixed map.

Here are a few screenshots to get a better idea of the problem:

1. Initial position:

![1](https://user-images.githubusercontent.com/12606661/50242465-25e10f00-03d3-11e9-9536-0ceb4547a2d1.PNG)

2. When scrolling the ScrollView upwards, notice how the river is now accross the center of the map, although the MapView hasn't been touched:

![3](https://user-images.githubusercontent.com/12606661/50243177-29759580-03d5-11e9-8cb4-ab4c4dc11654.PNG)

3. When scrolling the ViewPager sideways, notice how the 7TH ARRONDISSEMENT text is now on the far right of the MapView, instead of remaining in the center. Again the MapView has not been touched

![2](https://user-images.githubusercontent.com/12606661/50243288-7b1e2000-03d5-11e9-8f75-84101ca1d271.png)

This doesn't happen on Emulators running Android 8 and 9, with no changes in the codebase.

### Configuration

**Android versions:**  7.0, 7.1.1
**Device models:** Nexus 5 Emulator
**Mapbox SDK versions:** 6.7.2

**Comment by tobrun** [comment]
Thank you for reaching out @paulhristea,  a couple of follow up questions:
 - have you enabled using TextureView as render surface? either with `mapbox_renderTextureMode` xml attribute or `MapboxMapOptions#renderTextureMode(true)`?
 - how does your code differ from https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/RecyclerViewActivity.kt?

**Comment by saddahussain** [comment]
Yes. It does fix the issue.
