### ISSUE TITLE
Metrics connectivity tests (SSL pinning)

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1363]
Latest builds still do not seem to be sending live metrics events. Possibly a bug still in SSL pinning. 

1. Fix this. 
1. Write a test. 
    - Start app. 
    - Do stuff with the map. 
    - Background the app to flush the queue (can we do this with KIF?)
    - Observe SSL network connection, which we'll assume is for metrics since the map isn't being moved. 

Maybe a little brittle, but shouldn't false-positive and about as a good a way as any to test a pinned SSL. 

/cc @bleege

**Comment by incanus** [comment]
Possibly useful: https://github.com/dstnbrkr/VCRURLConnection

**Comment by bleege** [comment]
On brach [1306-metrics-debug](https://github.com/mapbox/mapbox-gl-native/compare/1363-metrics-debug).

**Comment by incanus** [comment]
Actually, let's leave this open and think about testing strategies for SSL pinning still.

**Comment by incanus** [comment]
@bleege Any sense of what we might be able to increase test coverage on here for b2, if at all?

**Comment by bleege** [comment]
Picking this backup...

**Comment by bleege** [comment]
Testing should be quicker now that the `turnstile` event is created and then flushed immediately at launch.  It uses the same events infrastructure so it should be sufficient for testing.

The definition of success for sending events is receiving an `HTTP 204` message back from the event server.

**Comment by bleege** [comment]
Current Metrics Tests --> https://github.com/mapbox/mapbox-gl-native/blob/88b3cfe37de7918723fb9ebb6b886aaec4808bcd/test/ios/MetricsTests.m

**Comment by bleege** [comment]
The actual sending of events data to the server via HTTP is done via `-[MGLMapboxEvents postEvents]` which is an internally accessible only method triggered by `+[MGLMapboxEvents flush]`.

The `-[MGLMapboxEvents pushTurnstileEvent]` method will push an event and then force a flush of the event queue, so it could be an ideal way to test this without too much extra configuration work.  This is executed once via `-[MGLMapboxEvents init]`.

**Comment by bleege** [comment]
Current error message when running in via Mapbox GL dev app.

```
<NSHTTPURLResponse: 0x7fb1a6f004c0> { URL: https://cloudfront-staging.tilestream.net/events/v1?access_token=pk.eyJ1IjoiYmxlZWdlIiwiYSI6IlhFcHdyMlEifQ.A8U0V-ob2G0RjI_gznrjtg } { status code: 401, headers {
    Connection = "keep-alive";
    "Content-Length" = 26;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Fri, 05 Jun 2015 16:22:36 GMT";
    Via = "1.1 60d54c9a5886d76e8497d759ecb76d14.cloudfront.net (CloudFront)";
    "X-Amz-Cf-Id" = "kdUwh30yldmOfIwZnzKQd0wWgY2csjQh-KAZEv9XfyOpdXTLsDBK_Q==";
    "X-Cache" = "Error from cloudfront";
    "X-Content-Type-Options" = nosniff;
    "X-Powered-By" = Express;
} }
```

**Comment by bleege** [comment]
Stepped through process by adding a completion handler to [NSURLSessionDataTask that sends in the metrics events](https://github.com/mapbox/mapbox-gl-native/blob/967fc73c153e4844ff0f3b574264bf3ab9f82e8f/platform/ios/MGLMapboxEvents.m#L600) and discovered that the [SSL Pinning validation actually occurs](https://github.com/mapbox/mapbox-gl-native/blob/967fc73c153e4844ff0f3b574264bf3ab9f82e8f/platform/ios/MGLMapboxEvents.m#L891) before the completion handler fires.  This is a bit confusing as [HTTP 401](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2) is all about telling the requester that it's Unauthorized.  Cart before the horse situation?

**Comment by bleege** [comment]
Also, `[VCR save:@""]` doesn't write any json out when run.  Double / Triple checked directory permissions.

**Comment by bleege** [comment]
Tested using the PROD server and now see that the completion handler is returning an `HTTP 204`.  Wonder what the difference between Staging and PROD is?  Any ideas @camilleanne ?

```
<NSHTTPURLResponse: 0x7ff769cbc500> { URL: https://api.tiles.mapbox.com/events/v1?access_token=pk.eyJ1IjoiYmxlZWdlIiwiYSI6IlhFcHdyMlEifQ.A8U0V-ob2G0RjI_gznrjtg } { status code: 204, headers {
    "Access-Control-Allow-Origin" = "*";
    Connection = "keep-alive";
    Date = "Fri, 05 Jun 2015 17:45:30 GMT";
    Via = "1.1 650859fa2cd80d54569500386ec0cbcc.cloudfront.net (CloudFront)";
    "X-Amz-Cf-Id" = "ljJ0MrqpkxaQHM6XT_4a39g4rp2UsidEOY5myfOl_8CbXA-hwsMlIA==";
    "X-Cache" = "Miss from cloudfront";
    "X-Powered-By" = Express;
} }
```

**Comment by bleege** [comment]
Confirmed with @mick that the 401 is being caused by using a PROD access token on the Staging server.  This is what happens when you cross the streams.

**Comment by bleege** [comment]
Yep, used a Staging token to send to Staging Web server and the HTTP 204 showed up.

```
<NSHTTPURLResponse: 0x7ff04ae9c070> { URL: https://cloudfront-staging.tilestream.net/events/v1?access_token=sk.eyJ1IjoiYmxlZWdlIiwiYSI6InNpcml1c2x5In0.KyT-boMyC_xZYTYojTc8zg } { status code: 204, headers {
    "Access-Control-Allow-Origin" = "*";
    Connection = "keep-alive";
    Date = "Fri, 05 Jun 2015 18:03:11 GMT";
    Via = "1.1 e557f99b88ab1d4aada075c2c1ed6e23.cloudfront.net (CloudFront)";
    "X-Amz-Cf-Id" = "tFP6FxvBt6l1YPn7kazqvAGX_a7u9RIntPsnS_NRNd9FUKw_kHTJog==";
    "X-Cache" = "Miss from cloudfront";
    "X-Powered-By" = Express;
} }
```

**Comment by bleege** [comment]
Finally was able to get VCR to record and persist some data to disk.  Even though this was from `MGLMapboxEvents` it's only gathering resource requests.  I think it has something to do with threading as the only way that it'd record anything was when the VCR commands were started / saved on the main UI thread.

```json
[
  {
    "body" : "",
    "headers" : {
      "Access-Control-Allow-Origin" : "*",
      "X-Frame-Options" : "SAMEORIGIN",
      "X-Cache-Hits" : "0",
      "Age" : "0",
      "Via" : "1.1 varnish",
      "X-Download-Options" : "noopen",
      "X-XSS-Protection" : "1; mode=block",
      "Cache-Control" : "max-age=120",
      "Date" : "Fri, 05 Jun 2015 18:41:39 GMT",
      "Strict-Transport-Security" : "max-age=31536000; includeSubDomains; preload",
      "Connection" : "keep-alive",
      "X-Content-Type-Options" : "nosniff",
      "Etag" : "\"a66d53c9a391b38c0b9a0d259680386b\"",
      "X-Served-By" : "cache-dfw1825-DFW",
      "X-Cache" : "MISS"
    },
    "method" : "GET",
    "status" : 304,
    "uri" : "https:\/\/www.mapbox.com\/mapbox-gl-styles\/sprites\/mapbox-streets@2x.json?events=true"
  }
]
```

**Comment by bleege** [comment]
Ahh... looking closer at [the example in VCR README](https://github.com/dstnbrkr/VCRURLConnection/blame/master/README.md#L18) the `NSURLSession` is using the `sharedSession` while Mapbox GL [rolls it's own](https://github.com/mapbox/mapbox-gl-native/blob/967fc73c153e4844ff0f3b574264bf3ab9f82e8f/platform/ios/MGLMapboxEvents.m#L413).  Let's see if they'll talk to each other.

**Comment by incanus** [comment]
Is [OHHTTPStubs](https://github.com/AliSoftware/OHHTTPStubs) of any use here? We use it now in iOS tests and it automatically finds/mocks `NSURLConnection` and `NSURLSession` instances.

**Comment by bleege** [comment]
I looked into OHTTPStubs, but it was unclear to me if it could handle the custom SSL Handshaking back and forth communication at connection setup time.  It seemed like `OHHTTPStubsResponse` was only for once a connection had been made.

It doesn't look like we'll be able to refactor Mapbox GL's NSURLSession to use the `sharedSession` as the [`delegate` access property is readonly](https://developer.apple.com/library/mac/documentation/Foundation/Reference/NSURLSession_class/index.html#//apple_ref/occ/instp/NSURLSession/delegate), so there's no way to tell it to use itself as the delegate to handle the SSL Pinning.

I'm starting to think that they best we may be able to do is just have a test that reimplements SSL Pinning with the server using the same certs to make sure that it's functional.  That wouldn't tell us that the actual MGLMetricsEvents infrastructure was working, but it'd tell us that the whole setup wasn't.  Not sure how useful that is though.

**Comment by incanus** [comment]
@bleege How are you feeling on b2 scope for this? Sounds like it's basically stepping aside and testing that 1) copies of our certs, 2) our backend, and 3) _some_ Cocoa code are testable, but not our our framework exactly? @jfirebaugh Do you still see a value in this sort of testing?

**Comment by bleege** [comment]
> How are you feeling on b2 scope for this?

I think we're good to bump this to B3, if at all.  I think @jfirebaugh should have the final say as to whether this is valuable or not.

**Comment by jfirebaugh** [comment]
I think this is fine to bump.
