### ISSUE TITLE
Port 'number-format' expression to native

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native#13632]
Port of https://github.com/mapbox/mapbox-gl-js/pull/7626.

Requires iOS, Android, and stub (Qt, etc.) implementations.

cc @1ec5 @asheemmamoowala @dasulit

**Comment by 1ec5** [comment]
Some starting points for iOS/macOS and Android implementations in https://github.com/mapbox/mapbox-gl-js/pull/7626#discussion_r237994955.
