### ISSUE TITLE
Uncouple GL objects from Worker

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1364]
We're currently creating objects that may initialize GL objects in the worker thread; they are part of the *Bucket objects (VAO objects, Buffer objects). Instead, we should only create the block of memory and completely defer creating/destroying the GL-related objects (wrapping GL Buffer object + VAO) to the map thread.

This should avoid issues like https://github.com/mapbox/mapbox-gl-native/issues/1309

**Comment by jfirebaugh** [comment]
This is basically the same as #926 I think.

**Comment by kkaefer** [comment]
Yes
