### ISSUE TITLE
Style url is not loaded when offline

### ISSUE THREAD

**Issue by albintornqvist** [mapbox/mapbox-gl-native#13642]
I am using a custom style sheet that I provide to the map using the `options.styleUrl(url)` when creating my `SupportMapFragment`. I am then providing my own instance of `OkHttpClient` using `HttpRequestUtil.setOkHttpClient(okHttpClient)`, intercepting the requests and serving my style when I recognize my style url. The problem is that my interceptor never recognizes a request for the style when I am offline causing my map to become black. Maybe it is stopped before it reaches my chain of interceptors?
I tried using both `options.styleUrl(url)` and `options.styleJson(json)` which makes the style load even when offline but as soon as my fragment is recreated (e.g. on rotation) the styleJson is forgotten and the style url is reset to default causing my map to go black. 
Is this behaviour intended? Am I missing something?

### Expected behavior
The style json or the style url to be maintained on recreation of the `SupportMapFragment` and the request for the style url to proceed to my interceptor chain even when offline.

### Actual behavior
The style json and style url is forgotten on recreation of the `SupportMapFragment` and I never receive a request for the style json to my OkHttp Interceptor when offline causing my map to become black in different situations.

### Configuration

**Android versions:** 7.0, 8.0
**Device models:** Samsung SM-T810, Samsung SM-G955F
**Mapbox SDK versions:** 6.7.0

**Comment by tobrun** [comment]
@albintornqvist the SDK monitors connectivity state changes and won't request when your device is offline. You can override this behaviour by calling `Mapbox#setConnected(true)`. Let us know if this didn't solve your issue.
