### ISSUE TITLE
Android: Sharing Maps between Activities

### ISSUE THREAD

**Issue by azjkjensen** [mapbox/mapbox-gl-native#13657]
Is there a way to share map instances between activities on android? 

I'm mostly wondering in terms of performance if I can reduce load times by using a single map instance for all views.

**Comment by tobrun** [comment]
@azjkjensen a View is bound by the hosting context. A MapView is not different in that regard. If you would like to create a more dynamic UI and reuse parts of your UI in multiple screens, please look into using fragments for that.
