### ISSUE TITLE
Rendering geojson + fitbounds

### ISSUE THREAD

**Issue by cjm771** [mapbox/mapbox-gl-native#13653]
Hi, Is it possible to use this and render polylines via geojson and fitbounds as done in client side mapbox? Thanks!

**Comment by tobrun** [comment]
Hey @cjm771, I'm not sure if I fully understand your question. Could you elaborate? show an example? Pictures? Thank you!

**Comment by cjm771** [comment]
I realized how to render geojson to the map via the `map.addLayer()` and `map.addSource()` functionality but the `map.fitBounds()` found in the client js version can be seen here: https://www.mapbox.com/mapbox-gl-js/api/#map#fitbounds .  I ended up implementing my own version which basically calculates the zoom level based on the extents, but would be a useful feature! Thanks.
