### ISSUE TITLE
Is there a way to change the location of the user programmatically ?

### ISSUE THREAD

**Issue by khataha92** [mapbox/mapbox-gl-native#13652]
Hi, I'm using mapbox sdk on android and iOS, in android I can force update the location of the user using `locationLayerPlugin.forceLocationUpdate(location);`, is there a way to make that on iOS ?
Also in Android, I can add locationEngine to the location layer plugin and override the `getLastLocation()` method, but I'm not able to make that by iOS. 

       locationLayerPlugin.setLocationEngine(new LocationEngine() {
            @Override
            public void activate() {

            }

            @Override
            public void deactivate() {

            }

            @Override
            public boolean isConnected() {
                return false;
            }

            @SuppressLint("MissingPermission")
            @Override
            public Location getLastLocation() {
                return myFixedLocation;
            }

            @Override
            public void requestLocationUpdates() {

            }

            @Override
            public void removeLocationUpdates() {

            }

            @Override
            public Type obtainType() {
                return null;
            }
        });

**Comment by jmkiley** [comment]
Hey @khataha92 -

Thank you for using Mapbox! This repo is for reporting issues or requesting features. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
