### ISSUE TITLE
How to add Pulse animation effect to MGLCircleStyleLayer ios

### ISSUE THREAD

**Issue by Dhvl-Golakiya** [mapbox/mapbox-gl-native#13658]
HI

I am using mapbox for Android and iOS. I can animate `CircleLaye` with `ValueAnimator` in Android, but I don't know how to make it in iOS. I know, I can animate `AnnotationView` but I want to use layer instead of marker.

Code for Android:

````
ValueAnimator circleLayerAnimator = ValueAnimator.ofObject(
                new FloatEvaluator(),
                15f, 30f
        );
        circleLayerAnimator.setDuration(1000);
        circleLayerAnimator.setRepeatCount(ValueAnimator.INFINITE);
        circleLayerAnimator.setRepeatMode(ValueAnimator.REVERSE);
        circleLayerAnimator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {

            @Override
            public void onAnimationUpdate(ValueAnimator animator) {

                attractions.setProperties(
                        circleRadius((Float) animator.getAnimatedValue())
                );
            }

        });
        circleLayerAnimator.start();
````
I can animate layer radius using `TImer` like this way in iOS:

````
var isSmall = false
var initialRadius : Double = 15
            
Timer.scheduledTimer(withTimeInterval: 0.005, repeats: true, block: {(_) in
    if isSmall {
        initialRadius -= 0.5
        if initialRadius < 5 {
            isSmall = false
         }
    } else {
         initialRadius += 0.5
          if initialRadius > 25 {
               isSmall = true
          }
    }
     layer.circleRadius = NSExpression(forConstantValue: initialRadius)
})
````
Is there is any way to animate layer radius like doing in Android or I have to use `Timer` for that?

**Comment by jmkiley** [comment]
Hi @Dhvl-Golakiya -

Thank you for using Mapbox! This repo is for reporting issues or requesting features. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).

**Comment by Dhvl-Golakiya** [comment]
Hi @jmkiley 

Thanks for the reply. I already asked on StackOverflow, https://stackoverflow.com/questions/53940129/pulse-animation-effect-to-mglcirclestylelayer-mapbox-ios 
But didn't get any reply. I will talk with a Mapbox support team. 
Thanks
