### ISSUE TITLE
Libraries Mismatch  Between Core Libaray and Navigation UI

### ISSUE THREAD

**Issue by IMADHASSAN** [mapbox/mapbox-gl-native#13655]
### Gradle File
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.parque"
        minSdkVersion 17
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    repositories {
        mavenCentral()
        maven { url 'https://mapbox.bintray.com/mapbox' }

    }

}

dependencies {
    def supportLibVersion = '28.0.0-alpha3'
    //noinspection GradleCompatible
    implementation "com.android.support:appcompat-v7:${supportLibVersion}"
    api "com.android.support:design:${supportLibVersion}"
    implementation "com.android.support:support-vector-drawable:${supportLibVersion}"
    implementation "com.android.support:support-v4:${supportLibVersion}"
    implementation 'com.google.firebase:firebase-core:16.0.4'
   implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.7.2'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:4.1.1'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.24.1'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places:0.6.0'
    implementation 'com.google.firebase:firebase-auth:16.0.4'
    implementation 'com.google.firebase:firebase-database:16.0.4'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-core:1.1.0'

}

apply plugin: 'com.google.gms.google-services'
`

###  Facing Error  during compiling `Caused by: com.android.tools.r8.utils.AbortException: Error: Interface `com.mapbox.android.core.location.LocationEngine(classpath class)` used as super class of `com.mapbox.services.android.navigation.v5.location.replay.ReplayRouteLocationEngine`.

`

**Comment by tobrun** [comment]
@IMADHASSAN would you be able to retest with a more recent versions?

For navigation this would be 0.26.0
For maps this would be 6.8.1 
For mapbox-sdk-services this would be 4.3.0
