### ISSUE TITLE
[Core] MGLOpenGLStyleLayer does not wrap center coordinate values when crossing IDL

### ISSUE THREAD

**Issue by ryanhamley** [mapbox/mapbox-gl-native#13664]
This is capturing a bug report from a client. I wanted to add what I've found and get some input on potential solutions.

**Platform:** Cross-platform
**Mapbox SDK version:** Any

### Steps to trigger behavior

 1. Create a custom MGLOpenGLStyleLayer
 2. In the draw function, log/observe the context's `centerCoordinate` attribute
 3. When the map is quickly panned across the IDL (especially in inertial panning after "throwing" the map left or right), the `centerCoordinate` can show unwrapped values such as 230 or -197.

### Expected behavior
The behavior that the client expected was wrapped coordinates, e.g. the returned coordinates would smoothly transition from -179 -> -180 -> 179 or vice versa.

### Actual behavior
Coordinates continue in the positive or negative direction until the inertial panning stops when they revert to the "correct" wrapped coordinates.

### Discussion
This seems to be exclusive to custom style layers. Implementing the fix that the client asked for would be a breaking change which may adversely affect other clients using custom style layers.

I can think of a few possible solutions:

1) Do nothing. This is a custom layer and wrapped coordinates are custom behavior which should be implemented by the client, rather than forcing all users to use wrapped coordinates.
**Pros**: No changes necessary
**Cons**: More work for client. Client may be unhappy with solution.

2) Ensure that the `centerCoordinates` returned by a custom layer's style context are wrapped.
**Pros**: Fixes bug for client and may be more intuitive for many developers to see wrapped coordinates in this use case.
**Cons**: Is a breaking change that could unexpectedly change the behavior of other clients' custom layers.

3)  Expose a `wrapCoordinates` method on the API to allow users to have wrapped coordinates without having to work out the logic themselves.
**Pros**: Is a compromise between 1 and 2 by allowing for a simple fix to the problem without creating a breaking change
**Cons**: Increases API surface. We may not want users to worry about wrapping coordinates themselves since it could become confusing and lead to unintended bugs in their code.

4) Add a `wrap` parameter to the custom style layer. By default, it would be false, but passing in true would return wrapped coordinates.
**Pros**: Gives the advantages of 3 while keeping the wrapping logic internal
**Cons**: Adds a new parameter to the layer

I think 1 and 4 are the best options, but I'd love to get feedback since the native codebase isn't my forte and I'm hesitant to add a breaking change or increase the API size without good reason.

**Comment by ChrisLoer** [comment]
I think 1 is probably the best option. My thinking is that any current users of `MGLOpenGLStyleLayer` already have to handle a sudden jump in the center coordinate due to wrapping, this would just be a matter of doing the jump sooner.

Making the custom layer draw different things in different wrapped copies of the world would still be difficult, but let's call that out-of-scope.

**Comment by ryanhamley** [comment]
I talked to @chloekraw about this and we're going to label it Won't Fix for now. We can revisit if a compelling case for wrapped coordinates in custom layers is made or if we see this reported by more users.
