### ISSUE TITLE
Add way to disable interaction with iOS map view

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1366]
For the benchmarking application (and other use cases like "static" maps), it'd be cool to be able to disable any sort of interaction with the app.

The first step could be just an on/off switch; in further iterations, we could constrain interaction in more sophisticated ways, e.g. disable rotation, lock to specific zoom level ranges and locations.

**Comment by 1ec5** [comment]
Here’s how to disable gestures:

```objc
mapView.zoomEnabled = NO;
mapView.scrollEnabled = NO;
mapView.rotateEnabled = NO;
```

After setting these properties, you can still set the center coordinate, zoom level, and rotation programmatically.

**Comment by kkaefer** [comment]
Dang, didn't find these when looking through the code... Thanks!

**Comment by kkaefer** [comment]
Can we rename `scrollEnabled` to `panEnabled`?

**Comment by kkaefer** [comment]
Also, setting `mapView.userInteractionEnabled = NO;` disables them as well.

**Comment by friedbunny** [comment]
Hah, yeah @kkaefer, was just talking to @1ec5 about `mapView.userInteractionEnabled = NO;`. It looks like it works as one would expect, though it's a sledgehammer versus the fine-grained gesture properties.

**Comment by 1ec5** [comment]
In particular, `userInteractionEnabled` should also disable the :information_source: and compass (in the event that the map starts out rotated).

**Comment by 1ec5** [comment]
> Can we rename `scrollEnabled` to `panEnabled`?

We just copied `MKMapView`. Apple appears to never use the term “pan”, preferring “swipes” that “scroll” the map. (On OS X, two-finger swiping scrolls the map, Esri style, instead of zooming.)

**Comment by incanus** [comment]
Yeah, the idea here was parity to the Apple API. I think we should leave it.
