### ISSUE TITLE
Map::setLatLngBounds crossing the IDL

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#13672]
When calling Map::setLatLngBounds with a bounds crossing the IDL, I'm unable to cross the IDL. The camera resets itself to the most left side of the bounds.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2151639/50696314-65e4fa80-103f-11e9-8d5e-186b272d7a33.gif)

The bounds used is defined [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/LatLngBoundsForCameraActivity.java#L36)

cc @mapbox/gl

**Comment by brunoabinader** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/13958.
