### ISSUE TITLE
Alternative method for setStyleJSON?

### ISSUE THREAD

**Issue by robipresotto** [mapbox/mapbox-gl-native#1367]
mbglMap->setStyleJSON((std::string)[styleJSON cStringUsingEncoding:NSUTF8StringEncoding]

I can not see more this method on public api.

**Comment by kkaefer** [comment]
Can you please elaborate?

**Comment by 1ec5** [comment]
As explained in #1299, I got rid of the `styleJSON` API for now, per https://github.com/mapbox/mapbox-gl-native/issues/1147#issuecomment-88171503 and #900. We'll eventually need some way to interact with styles with that kind of granularity for #837.

**Comment by robipresotto** [comment]
still some crashes on json serialisation,

```ruby
10 Foundation                     0x00000001838ec6f0 +[NSJSONSerialization JSONObjectWithData:options:error:] + 80
```

**Comment by 1ec5** [comment]
On the other hand, if you’re seeing a crash in `+[NSJSONSerialization JSONObjectWithData:options:error:]`, it’s likely an exception caused by malformed JSON or a JSON object of a different type than GL expects. You should set an exception breakpoint and see where and why the exception is thrown.

**Comment by robipresotto** [comment]
:+1:
