### ISSUE TITLE
Update feedback link to https://apps.mapbox.com/feedback/ 

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-native#13697]
The URL for Mapbox's feedback app has been updated to https://apps.mapbox.com/feedback/. There is a 301 redirect in place, so the current URLs should continue to work, but it's probably a good idea to update these at some point. 

@1ec5 thanks for pointing out this repo as one that needs to change. Do you think that you or someone else more familiar with this codebase could make those changes pretty quickly (probably more efficiently than me)? There is no big hurry.

**Comment by 1ec5** [comment]
The older URL on www.mapbox.com occurs [a few times](https://github.com/mapbox/mapbox-gl-native/search?q=%22www.mapbox.com%2Ffeedback%22&unscoped_q=%22www.mapbox.com%2Ffeedback%22) in this repository. It should be a straight-up find-and-replace job, thankfully.
