### ISSUE TITLE
Hello! I would like to ask about the mapbox IOS API, does the vector slice use its own server address?

### ISSUE THREAD

**Issue by songyuyang0918** [mapbox/mapbox-gl-native#13702]
Hello! I would like to ask about the API of mapbox IOS, can you use your own server address for slicing only with your open source framework? I didn't find any methods in the API's GLMapView class, okay?
thank you!

**Comment by friedbunny** [comment]
Our SDKs consume styles that conform to the [Mapbox Style spec](https://www.mapbox.com/mapbox-gl-js/style-spec/) — these styles can specify any server you choose. Check out the [styles section](https://www.mapbox.com/ios-sdk/maps/examples/#map-styles) of our examples page for more info on how to use styles with this SDK.
