### ISSUE TITLE
Crash targeting 4K external display — GL_INVALID_VALUE

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#13703]
The external display support added to iosapp in #13701 works well in the simulator for external displays at 640×480, 720×480, 1,024×768, 1,280×720 (720p), and 1,920×1,080 (1080p) resolutions, but mbgl immediately crashes when displaying the map view on a 3,840×2,160 (4K) display.

The stack trace isn’t particularly enlightening, but it is worth noting that there are four worker threads at the time of the crash:

```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x000000010a6a6b86 in __pthread_kill ()
#1	0x000000010a6f9c50 in pthread_kill ()
#2	0x000000010a469c45 in abort ()
#3	0x000000010a1f05b1 in abort_message ()
#4	0x000000010a1f0735 in default_terminate_handler() ()
#5	0x0000000106b9caa5 in _objc_terminate() ()
#6	0x000000010a1fc65e in std::__terminate(void (*)()) ()
#7	0x000000010a1fc6d3 in std::terminate() ()
#8	0x0000000106b9ca22 in objc_terminate ()
#9	0x000000010a307616 in _dispatch_client_callout ()
#10	0x000000010a30ab78 in _dispatch_block_invoke_direct ()
#11	0x0000000111422ba8 in __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ ()
#12	0x0000000111422860 in -[FBSSerialQueue _performNext] ()
#13	0x0000000111422e40 in -[FBSSerialQueue _performNextFromRunLoopSource] ()
```

The console output is also interesting:

```
2019-01-10 00:56:56.065792-0800 Mapbox GL[53243:21458550] Failed to make complete framebuffer object 8cd6
libc++abi.dylib: terminating with uncaught exception of type mbgl::gl::Error: glGetIntegerv(GL_MAX_VERTEX_ATTRIBS, &value): Error GL_INVALID_VALUE at /path/to/mapbox-gl-native/src/mbgl/gl/context.cpp:100
```

/cc @mapbox/maps-ios @mapbox/gl-core

**Comment by julianrex** [comment]
@kkaefer do we clamp the frame buffer size?

**Comment by 1ec5** [comment]
https://github.com/mapbox/mapbox-gl-native/pull/13701#pullrequestreview-191400586 notes that this crash occurs when targeting a 4K Apple TV as an external display. What’s interesting to me is that I don’t get a crash when a 4K Apple TV (simulator) is the primary display for the tvOS map SDK, which is virtually identical to the iOS map SDK: #9319.

**Comment by julianrex** [comment]
FYI I also had this problem on a screen that was < 4k, but this was with an earlier Apple TV (3rd gen)
