### ISSUE TITLE
Map Panning in RecyclerView

### ISSUE THREAD

**Issue by ulusoyca** [mapbox/mapbox-gl-native#13719]
I have a Horizontal Recyclerview in which each item in RV is fullscreen. One of the items in Horizontal RV is fullscreen MapView. Thanks to your help, I am able to implement it (https://github.com/mapbox/mapbox-gl-native/issues/13529). Your help was very useful and it works. 

However, I am trying to figure out map panning. When I vertically scroll, I can pan but any horizontal scroll is cached by RecyclerView and it starts to scroll to the next item instead of map panning.

I have onMapClickListener and when I click on the Map the click is caught by Maps and it works. Why is the `MotionEvent.ACTION_MOVE` event (I guess this is the event for panning) not consumed by the MapView but RecyclerView?

Am I missing something? 

Platform: Android

**Comment by tobrun** [comment]
@ulusoyca this issue stems from your RecyclerView consuming the touch event and not passing it to its child (MapView in this case). There are many blog and stackoverfllow issues covering the uses. Sadly I don't have any code ready availlable for a horizontal implementation but this is what I'm using in my examples:

```
        class MapItem
        class MapHolder(val mapView: MapView, bundle: Bundle?) : RecyclerView.ViewHolder(mapView) {
            init {
                mapView.onCreate(bundle)
                mapView.setOnTouchListener { view, motionEvent ->
                    // Disallow the touch request for recyclerView scroll
                    view.parent.requestDisallowInterceptTouchEvent(true)
                    mapView.onTouchEvent(motionEvent)
                    true
                }
            }
        }
```

Closing as this isn't an issue with our SDK but with optimizing your code for click handling with the Android framework.
