### ISSUE TITLE
mesa version is specified in three different places

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1372]
https://github.com/mapbox/mapbox-gl-native/blob/c27f84e75364bc3fa4562ab8a399c6e11dd2e363/configure#L55-L56
https://github.com/mapbox/mapbox-gl-native/blob/2b633cc51cd44be3f0224f0b105b18f0a3d7d657/scripts/linux/install.sh#L13-13
https://github.com/mapbox/mapbox-gl-native/blob/2b633cc51cd44be3f0224f0b105b18f0a3d7d657/scripts/linux/run.sh#L31-31

**Comment by kkaefer** [comment]
We reeeeally want to make sure we use the right version ;)
