### ISSUE TITLE
[documentation] make darwin-update-examples fails for MGLUserTrackingMode

### ISSUE THREAD

**Issue by riastrad** [mapbox/mapbox-gl-native#13740]
While working on #13112, I ran into an unexpected problem when attempting to insert a code snippet into `MGLMapView.h`'s definition of `MGLUserTrackingMode`. As #13112 was supposed to be a quick win and this appears to be a significant blocker, I'm splitting out this out as a separate issue.

This is likely an issue either with either the `platform/darwin/scripts/update-examples.js` script _or_ with a bug in [SourceKitten](https://github.com/jpsim/SourceKitten) (which is used to parse the header code). Additional research is necessary to determine exactly what the root cause is.

### Steps to reproduce

Here's the full process to add a code snippet:
https://github.com/mapbox/mapbox-gl-native/blob/c8c664fbf376b615b3f1e4b2a4d7f1c99b6097be/platform/darwin/test/MGLDocumentationExampleTests.swift#L9-L26

To throw this specific error do the following:
 1.  Create a new test function in `MGLDocumentationExampleTests.swift` targeting `MGLUserTrakcingMode`
 2. Add an empty code snippet place holder in the  `MGLMapView.h`
 3. From gl-native's root, run `make darwin-update-examples`

### Expected behavior

The script should successfully parse the test scripts and the targeted header file and inject the specified snippet into the empty snippet placeholder in the comment.

### Actual behavior

The script errors out and logs the following to the terminal:

```
/Users/joshuaerb/repos/source/mapbox-gl-native/platform/darwin/scripts/update-examples.js:46
  let completedComment = commentMatch[0].replace(/^([ \t]*)```swift\n[^]*?```/m, function (m, indentation) {
                                     ^

TypeError: Cannot read property '0' of null
    at completeSymbolInSource (/Users/joshuaerb/repos/source/mapbox-gl-native/platform/darwin/scripts/update-examples.js:46:38)
```

### Configuration

**Mapbox SDK versions:** `4.7.0` (but don't believe this is pertinent) 
**iOS/macOS versions:** N/A
**Device/simulator models: N/A**
**Xcode version:** `10.1`

cc: @1ec5 @mapbox/maps-ios

**Comment by 1ec5** [comment]
This is the regular expression that’s failing to match:

https://github.com/mapbox/mapbox-gl-native/blob/f3341dd589c6330c0cfd6e8e381398d08493b48a/platform/darwin/scripts/update-examples.js#L42-L43

You could try debugging this issue by logging the value of `srcUpToSymbol` if `commentMatch` is `null`.
