### ISSUE TITLE
Error loading geoJSON polygon source

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-native#1376]
Hey,

according to the [gl-style-spec](https://www.mapbox.com/mapbox-gl-style-spec/), geoJSON is supported as a source type through the style. We're currently unable to use this on the native client, as it throws an error 'Source type is not supported' – so I assume support isn't there yet on native.

Is there currently any other viable way of loading geoJSON polygons in native, or should we just go about creating vector-tiles out of the data instead for now?

**Comment by jfirebaugh** [comment]
Polyline annotations landed in v0.4.0. Direct GeoJSON rendering is still being tracked as part of #507.
