### ISSUE TITLE
How to move MGLUserLocation manually without MGLLocationManager by setting a coordinate

### ISSUE THREAD

**Issue by romanandreyvich** [mapbox/mapbox-gl-native#13762]
Are there any ways to move MGLUserLocation manually without MGLLocationManager in iOS SDK?
We need it for our tests. For some reasons, we cannot fake coordinates via GPX and we change the coordinates manually. Has mapbox any ways to fake a coordinate of MGLUserLocation manually, without MGLLocationManager and CLLocationManager?

**Comment by fabian-guerra** [comment]
Hi, @romanandreyvich. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/) or check our [documentation](https://www.mapbox.com/ios-sdk/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
