### ISSUE TITLE
how to make  MGLSymbolStyleLayer's text showed with local system font ,for example '.PingFang-SC-Light'

### ISSUE THREAD

**Issue by aio-ani** [mapbox/mapbox-gl-native#13764]
I want to use local system font for custom map's MGLSymbolStyleLayer ,how can i start with it ?

### Steps to reproduce

the map is customed with a style file

### Actual behavior

i do not want it show the remote font in .pbf file. but my local font

### Configuration

**Mapbox SDK versions:** 
**iOS/macOS versions:** 
**Device/simulator models:**
**Xcode version:**

**Comment by jmkiley** [comment]
Thank you for using Mapbox! This repo is for reporting issues or requesting features. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).

**Comment by aio-ani** [comment]
> Thank you for using Mapbox! This repo is for reporting issues or requesting features. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).

OK,i know. thanks very much.
