### ISSUE TITLE
Thread conflict in setSourceTileCacheSize/onLowMemory

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1377]
Both of these functions invoke `env->performCleanup();` in the Map thread. However, that function may be invoked at a time when the main thread is swapping the framebuffer so the Map thread may not call any GL functions.

**Comment by jfirebaugh** [comment]
How would we fix this? When is it safe for the Map thread to call GL functions?

**Comment by kkaefer** [comment]
...only when we call `renderSync()` from the `MGLMapView.mm` file, i.e. as part of a `render()` call.

**Comment by jfirebaugh** [comment]
This was fixed in 5aa0caf5c50df26e0ce4a4f42b22d0647e6b1ae2.
