### ISSUE TITLE
Camera bounds restriction not respected during fling

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#13770]
Camera bounds can be crossed by the fling velocity animation.

![ezgif com-video-to-gif 29](https://user-images.githubusercontent.com/16925074/51488623-53d8bb00-1da6-11e9-82ff-4463e34498bc.gif)

**Comment by adamb70** [comment]
Have just come across this problem myself when trying to disable infinite map wrapping by setting world bounds.

Here's some sample code to help showcase this issue.

```java
public void onMapReady(@NonNull final MapboxMap mapboxMap) {
    mapboxMap.setStyle(Style.LIGHT, new Style.OnStyleLoaded() {
        @Override
        public void onStyleLoaded(@NonNull Style style) {
            LatLngBounds bounds = new LatLngBounds.Builder()
                    .include(new LatLng(0, 150))
                    .include(new LatLng(90, 0))
                    .build();

            mapboxMap.setLatLngBoundsForCameraTarget(bounds);
        }
    });
}
```

**Comment by LukasPaczos** [comment]
Fixed by https://github.com/mapbox/mapbox-gl-native/pull/13958.
