### ISSUE TITLE
install boost-program-options library via mason

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1378]
The boost-program-options library is needed by the `render` binary, but it is currently an undocumented external dependency on OSX and requires a PPA install on Ubuntu 12.04.

Instead we should install it via mason, and then remove mention of boost from the README (because it will be handled transparently by the build process).

**Comment by jfirebaugh** [comment]
@kkaefer Does bb33493710629b1f78ac7ac23a89b656fb6a8a8c fix this?

**Comment by kkaefer** [comment]
yup.
