### ISSUE TITLE
[iOS] Add telemetry performance event

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#13794]
This is the iOS equivalent of https://github.com/mapbox/mapbox-gl-native/issues/13789

However, we do not yet have an iOS equivalent for the telemetry ticket in https://github.com/mapbox/mapbox-events-ios/ so at the moment this is blocked. /cc @rclee @andrlee 

/cc @captainbarbosa

**Comment by rclee** [comment]
This [PR](https://github.com/mapbox/mapbox-events-ios/pull/93) should allow for any event to be passed through, performance or otherwise. This was [added to gl ](https://github.com/mapbox/mapbox-gl-native/pull/13676)some time ago as well. Sorry for the miscommunication earlier @julianrex!
