### ISSUE TITLE
Custom LocationEngine not rendering current location icon

### ISSUE THREAD

**Issue by gareoke** [mapbox/mapbox-gl-native#13811]
When implementing a new LocationEngine class that wraps Skyhook's Android SDK, MapboxMap's LocationComponent does not show an icon representing the user's current location

### Steps to reproduce

 1. Create a custom class that implements LocationEngine
 2. After onMapReady() and OnStyleLoaded() do: 
```
LocationComponent locationComponent = mapboxMap.getLocationComponent();
locationComponent.activateLocationComponent(this, mapboxMap.getStyle(), skyhookLocationEngine,
    com.mapbox.mapboxsdk.R.style.mapbox_LocationComponent);
locationComponent.setLocationComponentEnabled(true);
locationComponent.setCameraMode(CameraMode.TRACKING);
locationComponent.setRenderMode(RenderMode.COMPASS);
```
 3. Receive updates on locationEngine#requestLocationUpdates()'s LocationEngineCallback

### Expected behavior

The Location Component shows proper icon representing the users current location with camera tracking functional

### Actual behavior

No icon appearing and non-functional camera tracking

### Configuration

**Android versions:** Android Pie
**Mapbox SDK versions: 6.8.1 to 7.0.1

### Additional Notes

For 6.8.1, If mapView's lifecyle events onPause and onResume are called, the Compass Icons appears onResume
For 7.0.1, Location icon never shows

Tried skyhookLocationEngine#getLocationComponent()#forceLocationUpdate() as well to no avail.

When using LocationEngineProvider#getBestLocationEngine (Context), or NOT specifying a custom LocationEngine in LocationEngineProvider#activateLocationComponent, location icon and tracking is OK

**Comment by LukasPaczos** [comment]
Hey @gareoke, thanks for using Mapbox!

When it comes to issues on `v7.0.1`, are you sure that your wrapper is pushing location updates to the `callback` when requested in the `requestLocationUpdates(LocationEngineRequest, LocationEngineCallback, Looper`?

Also, what do you mean by `skyhookLocationEngine#getLocationComponent()#forceLocationUpdate()`?
If you don't want to wrap skyhook, you should be able to activate the component with a `null` engine or by `activate(context, style, false)`, this will not initialize the default engine, and then push all updates that you receive from your arbitrary skyhook implementation via `mapboxMap#getLocationComponent#forceLocationUpdate`. Would you be able to retest with this setup and let us know whether it works for you?

**Comment by ulusoyca** [comment]
I am also using a custom location engine without any issues. Just to be on safe side I want to ask whether you have explicitly defined foreground drawable for location indicator @gareoke ?

**Comment by gareoke** [comment]
Problem was I was not putting forceLocationUpdate on the main thread in locationEngineCallback's onSuccess method:
> new Handler(Looper.getMainLooper()).post(() -> {
>   mapboxMap.getLocationComponent().forceLocationUpdate(originLocation);
> });

Subsequently, I believe this should work for the periodic location update code I had as well as long as requestLocatoinUpdates is behaving properly as @LukasPaczos mentions:
> locationEngine.requestLocationUpdates(builder.build(),
>             locationEngineCallback, Looper.getMainLooper());
