### ISSUE TITLE
MapSnapShotter should support padding

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#13814]
When creating a snapshot, it should be allowed to add a padding (or insets) on the rendered image.

I created a tests based on the latest release, it's working.
I'll make some more tests and make a PR.

**Mapbox SDK versions: 4.7.1**

**Comment by julianrex** [comment]
This is still valid.

**Comment by pengdev** [comment]
This could be potentially solved by the #15436 on Android, paddings can be added to the `CameraPosition` in `MapSnapshotter.Options`.

**Comment by LukasPaczos** [comment]
@pengdev I agree that this would be a preferable solution, removing the Android tag.
