### ISSUE TITLE
Unsynchronized buckets and paint properties when layout changes

### ISSUE THREAD

**Issue by pozdnyakov** [mapbox/mapbox-gl-native#13812]
After layout has changed, a render layer with an updated style is still trying to render the previous bucket (with paint property binders that matched a previous program) until the new bucket is created by the tile worker.

**Comment by kkaefer** [comment]
This is intentional to avoid flickering.

**Comment by pozdnyakov** [comment]
> This is intentional to avoid flickering.

Could you please give more details on this?

**Comment by pozdnyakov** [comment]
@kkaefer right, so we won't remove the old bucket - render layer will be using it with the compatible (old) evaluated paint properties. At the moment paint properties are immediately updated and it causes flickering, pls see https://github.com/mapbox/mapbox-gl-native/issues/13407
