### ISSUE TITLE
AAPT2: mapbox_mapview_internal.xml:10: error: attribute srcCompat not found

### ISSUE THREAD

**Issue by cleemansen** [mapbox/mapbox-gl-native#13836]
I have problems building my app after updating from **mapbox-android-sdk 6.6.0 to 6.6.1**. 

`clean assembleRelease` works fine with `com.mapbox.mapboxsdk:mapbox-android-sdk:6.6.0@aar`. Starting with `6.6.1` (and also tried with `7.0.1`) I get the following error during `./gradlew clean assembleRelease`:

```
> Task :data:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':data:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /path/to/build/intermediates/res/merged/release/layout/mapbox_mapview_internal.xml:10: error: attribute srcCompat (aka <module-name>:srcCompat) not found.
  /path/to/build/intermediates/res/merged/release/layout/mapbox_mapview_internal.xml:18: error: attribute srcCompat (aka <module-name>:srcCompat) not found.
  error: failed linking file resources.
```

The mentioned file `mapbox_mapview_internal.xml` has this content:

```
<?xml version="1.0" encoding="utf-8"?>
<merge xmlns:android="http://schemas.android.com/apk/res/android" xmlns:app="http://schemas.android.com/apk/res-auto">

    <com.mapbox.mapboxsdk.maps.widgets.CompassView
        android:id="@+id/compassView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:contentDescription="@string/mapbox_compassContentDescription"/>

    <android.support.v7.widget.AppCompatImageView
        android:visibility="gone"
        android:id="@+id/logoView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:contentDescription="@null"
        app:srcCompat="@drawable/mapbox_logo_icon"/>

    <android.support.v7.widget.AppCompatImageView
        android:visibility="gone"
        android:id="@+id/attributionView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:adjustViewBounds="true"
        android:clickable="true"
        android:focusable="true"
        android:contentDescription="@string/mapbox_attributionsIconContentDescription"
        app:srcCompat="@drawable/mapbox_info_bg_selector"/>

</merge>
```

### Configuration

**Android Gradle Plugin:** com.android.tools.build:gradle:3.3.0

**Android Compile SDK:** 28

**Gradle version:** 
```
./gradlew --version

------------------------------------------------------------
Gradle 4.10.3
------------------------------------------------------------

Build time:   2018-12-05 00:50:54 UTC
Revision:     e76905e3a1034e6f724566aeb985621347ff43bc

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_202-ea (Oracle Corporation 25.202-b03)
OS:           Mac OS X 10.14.2 x86_64
```

**Mapbox SDK versions:** 7.0.1

**Comment by tobrun** [comment]
@cleemansen could you add the output of `./gradlew :<app_module>:dependencies`?

**Comment by cleemansen** [comment]
Of course @tobrun - `./gradlew :data:dependencies > dependencies.txt`: [dependencies.txt](https://github.com/mapbox/mapbox-gl-native/files/2812861/dependencies.txt)

**Comment by tobrun** [comment]
the v7.0.1 dependency of the Mapbox Maps SDK for Android doesn't seem to be bringing in any external dependencies:

> +--- com.squareup.okhttp3:logging-interceptor:3.9.1
|    \--- com.squareup.okhttp3:okhttp:3.9.1 (*)
+--- com.google.code.gson:gson:2.8.2
+--- com.mapbox.mapboxsdk:mapbox-android-sdk:7.0.1
+--- com.jakewharton.timber:timber:4.6.1
+--- com.android.support:support-compat:28.0.0
|    +--- com.android.support:support-annotations:28.0.0
|    +--- com.android.support:collections:28.0.0
|    |    \--- com.android.support:support-annotations:28.0.0
|    +--- android.arch.lifecycle:runtime:1.1.1
|    |    +--- android.arch.lifecycle:common:1.1.1
|    |    |    \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|    |    +--- android.arch.core:common:1.1.1
|    |    |    \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|    |    \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|    \--- com.android.support:versionedparcelable:28.0.0
|         +--- com.android.support:support-annotations:28.0.0
|         \--- com.android.support:collections:28.0.0 (*)

While others as the support appcompat are bringing in other dependencies. Adding something as `com.android.support:appcompat-v7:28.0.0` will probably resolve this specific build issue but I would like to verify why no dependencies are pulled in for you.

**Comment by cleemansen** [comment]
Nice catch.

First of all: `com.mapbox.mapboxsdk:mapbox-android-sdk:6.6.0` doesn't be bringing in any external dependencies in my setup also (so I still don't know what changed between 6.6.0 and 6.6.1).

My affected gradle-module is of type library (`apply plugin: 'com.android.library'`). The module defines in the dependencies block `implementation dataDependencies.mapbox`. This will be resolved to `com.mapbox.mapboxsdk:mapbox-android-sdk:${mapboxVersion}@aar`. I see no special configuration at this part.

Then the combination `implementation com.mapbox.mapboxsdk:mapbox-android-sdk:6.8.1` *and* `implementation com.android.support:appcompat-v7:28.0.3` works as suggested!

Let me know if you need further information from me. Thanks a lot for this _workaround_!

**Comment by tobrun** [comment]
capturing from @langsmith that he was able to see a different output:

<img width="806" alt="screen shot 2019-02-11 at 11 44 42 am" src="https://user-images.githubusercontent.com/2151639/52700546-d822f600-2f80-11e9-8b78-1d0dc63827c0.png">

Looking into your response above, could you elaborate why you are adding @aar to:

```
`com.mapbox.mapboxsdk:mapbox-android-sdk:${mapboxVersion}@aar`.
```

Removing the `@aar` part will probably result in pulling in the external dependencies.

**Comment by cleemansen** [comment]
Thanks! :)

Removing `@aar` will resolve the necessary dependencies of `com.mapbox.mapboxsdk:mapbox-android-sdk`.
