### ISSUE TITLE
Style switching broken

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#1384]
With the mega-merge of #1065, style switching no longer works reliably on iOS. When using the demo app, changing the style will hang the map layer with a blank screen most of the time (occasionally it will load after ~30s).

**Comment by jfirebaugh** [comment]
I wasn't able to replicate this -- I cycled through all the styles many times and everything appeared to be working.

**Comment by 1ec5** [comment]
Looks like it might be limited to older devices. We’re seeing it on a first-generation iPad mini running iOS 8, but not an iPhone 6 running iOS 8.

**Comment by friedbunny** [comment]
Also my iPhone 5 (8.1.3).

**Comment by 1ec5** [comment]
What we’re seeing on these older devices is that, after you change styles real fast a few times (not waiting for any style to load), you wind up in a state where no more rendering takes place. Even the background color gets stuck on the background color of one of the styles – that background color should be defined in each style’s JSON, without requiring a network request.

**Comment by jfirebaugh** [comment]
Can I borrow an older device from someone today?

**Comment by friedbunny** [comment]
You can have my iPad mini if @incanus is willing to carry it back to PDX with him.
