### ISSUE TITLE
Improve render time of map - Mapbox iOS sdk

### ISSUE THREAD

**Issue by pedrocruzlopez** [mapbox/mapbox-gl-native#13840]
I have a UICollectionView, each cell can show as a pop-up, showing more detailed info, including a map created with a custom style. All the maps should be cached in the DB to work offline. The thing is, while the maps are working ok online and offline, there is a little time to load the tiles every time that I clicked on any cell and this tiles loading is visible to the user. So my question is, is there a way to "pre-render" the tiles or improve the render time in order to show the map immediately after the user clicks on any cell? Thanks.

### Expected behavior

Render the map immediately

### Actual behavior

The tiles load process is visible to the user

### Configuration

**Mapbox SDK versions:**  v4.7.1
**iOS/macOS versions:**  12.1
**Device/simulator models:**
**Xcode version:**  10.1

**Comment by friedbunny** [comment]
The typical “static cell” use-case is better served by something like [MapboxStatic.swift](https://github.com/mapbox/MapboxStatic.swift), which downloads raster images that can be easily cached and (re-)displayed with minimal lag.
