### ISSUE TITLE
refactor MGLMapViewDelegate into its own header

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1385]
We should move this out of `MGLMapView.h` to cut down on size, much like MapKit and our raster SDK.

**Comment by incanus** [comment]
Blocked by some work in #1655, but should be able to hit this pretty easily afterwards.

**Comment by incanus** [comment]
Still planning on getting this when #1655 lands, as it's mostly a cut-and-paste job.

**Comment by 1ec5** [comment]
While you’re at it, would you mind filling out some of the “TODO” comments? `-mapView:regionDidChangeAnimated:` for example is implemented but not documented. Also, Xcode’s Quick Help always shows the doc comment preceding the declaration, so a host of delegate callbacks currently show documentation for `-mapView:rightCalloutAccessoryViewForAnnotation:`, which is confusing.

**Comment by friedbunny** [comment]
This happened on OS X, but still should happen on iOS.
