### ISSUE TITLE
Cannot display Polygon Feature : Docs outdated and examples are not working..

### ISSUE THREAD

**Issue by erluxman** [mapbox/mapbox-gl-native#13864]
### Steps to reproduce

 1. I was trying to implement PolygonFeature in map but could not do it in a fashion I am adding PointFeature. It does not display the Polygon in the map.
 2. I also tried examples [Draw a Polygon](https://docs.mapbox.com/android/maps/examples/draw-a-polygon/) and [Draw a polygon with holes](https://docs.mapbox.com/android/maps/examples/draw-a-polygon-with-holes/) but they are using APIs that at least seem unavailiable in the` version 6.7.0`
Example : 
```
style.addSource()
style.addLayer() 
```
These methods are not available in style of `OnStyleLoadedListener`  which seems to be `String` **type** And `Style.OnStyleLoaded` is **not available**  in the APIs either (which is being used in the example) 
 3.
 ```
style.addSource()
style.addLayer() 
```    
are available on `MapBoxMap` **but that does not render the polygon in the screen.**. 

### Expected behavior

I believed we could just plot Polygon feature as Point feature with some `color` Property for painting it's surface. 

### Actual behavior
Polygon cannot does not get rendered.

### Configuration

**Android versions: 28** 
**Device models: emulator-nexus5** 
**Mapbox SDK versions: 6.7.0**

**Comment by tobrun** [comment]
@erluxman current stable version of the Mapbox Maps SDK for Android is v7.1.1, the examples on our webpage reflect this. You can look through the git history of https://github.com/mapbox/mapbox-android-demo and https://github.com/mapbox/android-docs/issues to find examples compatible with 6.x releases.
