### ISSUE TITLE
Animate marker when the maps starts or change location

### ISSUE THREAD

**Issue by pedrocruzlopez** [mapbox/mapbox-gl-native#13883]
I would love to animate a marker when the map starts or change the location like the gif below, is this possible? thanks.

### Expected behavior

![animate-marker2](https://user-images.githubusercontent.com/12741167/52361232-5d4b5f80-2a03-11e9-87b5-2a9d276be3c8.gif)

### Actual behavior

No animation can be easily apply

### Configuration

**Mapbox SDK versions:**  v4.7.1
**iOS/macOS versions:** 12.1
**Device/simulator models:** N/A
**Xcode version:** 10

**Comment by tobrun** [comment]
![ezgif com-video-to-gif 50](https://user-images.githubusercontent.com/2151639/52401405-dad5a500-2ac1-11e9-86fa-82eca119adf3.gif)

our placepicker supports such an interaction, the code for that is open source and available in https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-places.

The code for this gif above can be found in https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/plugins/PlaceSelectionPluginActivity.java

**Comment by tobrun** [comment]
Just seeing this was about iOS..
