### ISSUE TITLE
MGLMapView invalidates entire view hierarchy layout on device rotation

### ISSUE THREAD

**Issue by ksinghal** [mapbox/mapbox-gl-native#13895]
### Steps to reproduce

 1. Create a single view iOS app with a viewcontroller that has an MGLMapView inside of a container view's viewcontroller
 2. Restrict the app to only portrait mode
 3. Put a log inside the parent viewcontroller's `viewDidLayoutSubviews` method
 4. Run the app and physically rotate the device

### Expected behavior
The Mapbox should not invalidate the parent view's layout and cause `viewDidLayoutSubviews` to fire, so no log should be seen from step #3 above. 

### Actual behavior
The Mapbox seems to be invalidating the entire view hierarchy and causing `viewDidLayoutSubviews` to fire with every rotation - even though only portrait mode is allowed. Please see the following GitHub issue that highlights a possible problem this could cause with compatibility with other libraries: [Pulley Issue #307](https://github.com/52inc/Pulley/issues/307). In particular, see [this comment](https://github.com/52inc/Pulley/issues/307#issuecomment-461663061).

### Configuration

**Mapbox SDK versions:**  4.8.0
**iOS/macOS versions:** 12.1.2
**Device/simulator models:**
**Xcode version:** 10.1

**Comment by riastrad** [comment]
cc: @chloekraw

**Comment by julianrex** [comment]
Thanks @ksinghal - it looks like we layout subviews on each device rotation, regardless of how the application has defined its supported orientations.

See https://github.com/mapbox/mapbox-gl-native/pull/13900 for a quick experiment.

**Comment by julianrex** [comment]
Fixed in #13900
