### ISSUE TITLE
Android : expression iconColor not working

### ISSUE THREAD

**Issue by RoProducts** [mapbox/mapbox-gl-native#13896]
Hi,

The _iconColor_ expression of a SymbolLayer does not have any affect. Icons remain black or whatever color they are. You can check out this behavior even in your sample app :

https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/CircleLayerClusteringActivity.java#L182

Icon color should be interpolated:
![screenshot_20190208-102213_mapbox demo](https://user-images.githubusercontent.com/1333902/52469588-1b015a00-2b8c-11e9-958a-ce63d82a8074.jpg)
The _iconSize_ expression instead works

I tried different vector drawables and the "ic_cross.xml" you are using in the samples.
I tried to give the expression any kind of String or number representation, no success.

Please help.

**Comment by LukasPaczos** [comment]
Hey @RoProducts, thanks for suing Mapbox! You've actually found an issue with the linked example. The icon is added to the map [here](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/CircleLayerClusteringActivity.java#L89-L90), but in order for you to be able to color an icon using the `iconColor` property, it needs to be declared as an `SDF`. You can do that by providing a compatible bitmap to the map like
```
style.addImage(
  "cross-icon-id",
  BitmapUtils.getBitmapFromDrawable(getResources().getDrawable(R.drawable.ic_cross)),
  true
);
```
where `true` flag declares that it's an `SDF` icon. Now, your `iconColor` property should change the icon correctly.

Closing as answered, however, please let us know if that does not resolve your issue.

**Comment by RoProducts** [comment]
Hi @LukasPaczos ,

ah, okay this is silly. Costed my several hours trying different icons and expression.

Thank you however
