### ISSUE TITLE
Mapbox offline usage

### ISSUE THREAD

**Issue by mathtecg** [mapbox/mapbox-gl-native#13898]
Hi, 
I'm working on Mapbox implementation for offline usage on Android devices (java).
Right now I successfully implemented the download manager method of the Mapbox demo...
The Problem is, that the user has to download the Map / open the map at least 1 time before offline usage. I read a lot of discussions but I couldn't figure out how to make the offline map available after the Application is installed.

Maybe someone can help me?

What I want to achieve: Available offline map / load map tiles from a mbtiles file or smth. else, so that the users will have a offline app without proper "download" of the map.

Thanks a lot!

**Comment by LukasPaczos** [comment]
Hey @mathtecg, thanks for using Mapbox! Have you seen our [offline sideloading documentation](https://docs.mapbox.com/android/maps/overview/offline/#offline-sideloading)?

Offline sideloading allows you to create an external `.db` file with tiles, package that file with your APK or download from your server in the runtime at a convenient time and then load it into the on-device database, without ever launching the map. Here's a [short example](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/MergeOfflineRegionsActivity.kt).

**Comment by mosofsky** [comment]
@lukasmartinelli are fonts (AKA "glyphs") included in the offline packages generated by offline?  Should the following work?

1. Put Android device/emulator in Airplane mode
2. Install an Android app built with offline sideloading on the device/emulator 
3. Launch the app
4. See text on the map

My application only displays text if I've launched the app at least once with network enabled.

**Comment by asheemmamoowala** [comment]
@mosofsky glyphs are included when an offline database is created only if they are directly mentioned in the stylesheet.  You can inspect your sideloaded database to ensure that the `resources` table contains glyphs for the fonts you are referencing in your layers. Their `kind` column would have value `4`

**Comment by mosofsky** [comment]
Thank you @asheemmamoowala, indeed my stylesheet did not directly mention any fonts, I just wanted the default font.  In fact my stylesheet is just the most basic one you get in Mapbox Studio when you create a new style and click "Start blank".  So the style.json just says "glyphs": "mapbox://fonts/mosofsky/{fontstack}/{range}.pbf" at the top level and the "background" layer refers to no fonts.

What I understand from your comment is the stylesheet must reference the fonts in order for them to get bundled by the Mapbox offline pack utility (described in the [Offline sideloading documentation](https://docs.mapbox.com/android/maps/overview/offline/#offline-sideloading)).  I think that means fonts need to be mentioned in the layers of the stylesheet, not globally as the top-level "glyphs" parameter.

**Comment by asheemmamoowala** [comment]
> . I think that means fonts need to be mentioned in the layers of the stylesheet, not globally as the top-level "glyphs" parameter.

Based on the below snippet, this is not the case. 
https://github.com/mapbox/mapbox-gl-native/blob/13fb375823f1365f87056cea09ab4525e2880fd2/platform/default/src/mbgl/storage/offline_download.cpp#L208-L213

**Comment by mosofsky** [comment]
Thanks @asheemmamoowala so the global fonts should be in the offline pack?  I tried to look at the contents of the sideloaded database, but it's a binary file.  The file has a .db extension.  How do I inspect it as you suggested yesterday to see if there is a `resources` table with a row having value `4` in the `kind` column?

**Comment by mathtecg** [comment]
Hey,
I worked on the offline sideloading doc. and well unfortunately this doesn't solve my problem because I  need more than 6kTiles.. 
I tried going through this post https://stackoverflow.com/questions/51207393/how-to-use-openmap-vector-tiles-with-mapbox-android-sdk ; but couldn't solve my problem... 

So is there any example code / tutorial to see how to load for example .mbtiles (or other resources), downloaded from https://openmaptiles.com/downloads/planet/  from the asset folder, so that the MapActivity works full offline? (java/android)

thanks a lot!

**Comment by LukasPaczos** [comment]
@mathtecg unfortunately, in order to store more than 6k tiles in your database, either locally sideloaded or downloaded, you'll need to set up an enterprise plan, please give [this](https://docs.mapbox.com/android/maps/overview/offline/#limitations) and [this](https://docs.mapbox.com/help/troubleshooting/mobile-offline/#tile-ceiling--limits) a read.
