### ISSUE TITLE
MGMLMapView: Increase the duration of the animation when following user

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#1389]
Currently, when the map receives a location update it quickly moves the map to re-center on the new location. This appears very choppy. Both Google and Apple have longer durations for this move resulting in a smoother overall animation. Maybe increase it to the time interval of the last location update? Or make it configurable from the client app?

Note: This should only affect location updates. The default 0.3 second duration works well for other animations.

**Comment by 1ec5** [comment]
This is covered by #1041. Simply increasing the animation duration may be a good first step forward, though.
