### ISSUE TITLE
Create generic reusable image decoding + encoding functions

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#139]
We should have an image decoding function that we can just throw any buffer at and returns a decode RGBA image (1st step) or a [S3 DXT 1/3/5 compressed texture](https://www.khronos.org/registry/gles/extensions/EXT/texture_compression_s3tc.txt).

Image formats we should support:
* [ ] PNG
* [ ] JPG
* [ ] WebP
* [ ] S3 (DXT1/3/5)

**Comment by jfirebaugh** [comment]
Looks like we have what we need here for the time being.
