### ISSUE TITLE
Zoomed FillLayer does not draw properly   

### ISSUE THREAD

**Issue by anton-shestak** [mapbox/mapbox-gl-native#13905]
Hello. 
Does anybody know why the polygon which has been drawn by the FillLayer has unpredictable artifacts when I'm zooming? Please, see the pictures below.
![2](https://user-images.githubusercontent.com/42349854/52563113-8c057380-2e11-11e9-8be4-80c56e762c20.png)
![1](https://user-images.githubusercontent.com/42349854/52563114-8c057380-2e11-11e9-8ca2-06c93d32556b.png)

It's code which I use:

        FeatureCollection featureCollection = FeatureCollection.fromFeatures(new Feature[]                {Feature.fromGeometry(lineStringOuter)});
        GeoJsonSource routeSource= new GeoJsonSource("source_id", featureCollection, geoJsonOptions);
        mapboxMap.addSource(routeSource);
        FillLayer routeLayer = new FillLayer("layer_id", "source_id");
        routeLayer.setProperties(
        PropertyFactory.fillColor(color),
        PropertyFactory.fillOutlineColor(borderColor));
        mapboxMap.addLayerBelow(routeLayer, LOCATION_LAYER_ID);

mapbox sdk: "com.mapbox.mapboxsdk:mapbox-android-sdk:6.6.0"
Thanks

**Comment by LukasPaczos** [comment]
Hey @anton-shestak, would you be able to share an example dataset that the issue is reproducible with? Also, this looks similar to https://github.com/mapbox/mapbox-gl-native/issues/11469, could you ensure that all of your geometries are enclosed?

**Comment by anton-shestak** [comment]
@LukasPaczos 
Thank you for feed back! 
I solved problem using this answer https://github.com/mapbox/mapbox-gl-native/issues/11469#issuecomment-374652946
