### ISSUE TITLE
Camera bounds restriction is not impacted by padding

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#13907]
![ezgif com-video-to-gif 30](https://user-images.githubusercontent.com/16925074/52575248-24095a00-2e1e-11e9-9496-386b50634db5.gif)

As seen in the gif, the dark blue dot represents the screen center while the marker represents the padded camera position. Should we try and restrict the camera's target by the bounds or stick to restricting just the screen's center?

**Comment by tobrun** [comment]
cc @brunoabinader

**Comment by LukasPaczos** [comment]
I retested with a different example and it does feel natural. I think we are good to close here, thanks @brunoabinader.
