### ISSUE TITLE
[iOS] [swift] Event trigger for fully loaded custom raster tile source?

### ISSUE THREAD

**Issue by keltonhalbert** [mapbox/mapbox-gl-native#13903]
Forgive me if I’m missing something obvious, but I’ve been digging for the last few days and can’t seem to find anything on this. 

Is there a way to get a notification that all raster tiles have been loaded after being added to a layer? I’m currently downloading a loop of rasters (about 30 raster tile sources) and adding them to the map, and looping by toggling their visibility. 

I’m trying to get the loop “pre-loaded” and am currently using a static scheduledTimer, but this doesn’t always work. It also doesn’t work to pan or zoom while looping because the next zoom level of tiles don’t load. 

I’m looking for some sort of way to know that the raster tiles being displayed have finished loading before moving on to the next raster... is this something that exists, or could be added? I couldn’t find much in the delegate. 

Kelton.

**Comment by keltonhalbert** [comment]
Update: I've discovered the idle callback that gets sent to the delegate, but this doesn't really solve my problem. I still get issues where some raster tiles remain not fully loaded, resulting in tiles at the edge of the viewport not being displayed. It's like the delegate sends the idle signal when the low-res view is loaded but does not wait for the high-res view to load.

**Comment by julianrex** [comment]
@keltonhalbert - you mention "raster tiles"; which version of the SDK are you using?

Also does `MGLMapViewDelegate.mapViewDidFinishRenderingFrame(_ mapView: MGLMapView, fullyRendered: Bool)` where `fullyRendered==true` work for you?
