### ISSUE TITLE
MapBox Android - CameraPosition not correctly calculated depending on device orientation

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#13917]
I've noticed that the camera position is incorrectly calculated depending on the device orientation. The camera target gets the same bounds coordinates to create a LatLongBounds object.

Here some code to show what I mean:

```
val boundsNorth = feature.getProperty("bounds_north")?.safeAsDouble()
val boundsEast = feature.getProperty("bounds_east")?.safeAsDouble()
val boundsSouth = feature.getProperty("bounds_south")?.safeAsDouble()
val boundWest = feature.getProperty("bounds_west")?.safeAsDouble()

if (boundsNorth != null && boundWest != null && boundsSouth != null && boundsEast != null) {
    val defaultPadding = resourceAccessor.getDimension(R.dimen.selected_feature_line_camera_padding).roundToInt()
    val additionalBottomPadding = defaultPadding + resourceAccessor.getDimension(R.dimen.selected_feature_line_camera_additional_bottom_padding).roundToInt()

    val latLng = LatLngBounds.from(boundsNorth, boundsEast, boundsSouth, boundWest)
    val possibleCameraPos = mapboxMap.getCameraForLatLngBounds(latLng,
             intArrayOf(defaultPadding, defaultPadding, defaultPadding, additionalBottomPadding),
             mapboxMap.cameraPosition.bearing,
             mapboxMap.cameraPosition.tilt) ?: mapboxMap.cameraPosition 
}
```

The values for the bounds could be something like that:
> boundsNorth = {Double@15003} -37.558915378847225
> boundsEast = {Double@15004} 149.750121265
> boundsSouth = {Double@15005} -37.57303643786202
> boundWest = {Double@15006} 149.747737328

### **Example:**
**Portrait orientation:**
latlng: N:-37.558915378847225; E:149.750121265; S:-37.57303643786202; W:149.747737328
possibleCameraPos: Target: LatLng [latitude=-37.569126691494134, longitude=149.74892929647763, altitude=0.0], Zoom:13.274163736042373, Bearing:-0.0, Tilt:0.0

**Landscape orientation:**
latlng: N:-37.558915378847225; E:149.750121265; S:-37.57303643786202; W:149.747737328
possibleCameraPos: Target: LatLng [latitude=-37.528310568902945, longitude=149.74892929648342, altitude=0.0], Zoom:21.0, Bearing:-0.0, Tilt:0.0

As you can see the actual target is slightly different but I am using the same coordinates to create this camera target. I am not quite certain about the zoom value. It makes sense that both values are different but I would expect a smaller value for the landscape compared to the portrait mode.

### Configuration

**Android versions:** 5.1, 6, 7, 8, 9
**Mapbox SDK versions:** 7.1.2

**Comment by LukasPaczos** [comment]
Hey @Mordag, thanks for reporting the issue!

Unfortunately, I wasn't able to reproduce with the provided data. Here's my test case:
```
LatLngBounds bounds = LatLngBounds.from(-37.558915378847225, 149.750121265, -37.57303643786202, 149.747737328);
mapboxMap.addPolygon(
  new PolygonOptions()
    .fillColor(Color.BLUE)
    .add(bounds.getNorthWest())
    .add(bounds.getNorthEast())
    .add(bounds.getSouthEast())
    .add(bounds.getSouthWest())
    .add(bounds.getNorthWest())
);
CameraPosition cameraPosition = mapboxMap.getCameraForLatLngBounds(bounds, new int[] {5, 5, 5, 10}, 0, 0);
mapboxMap.moveCamera(CameraUpdateFactory.newCameraPosition(cameraPosition));
Logger.e("SimpleMapActivity", "Camera: " + cameraPosition);
```
and the results:
```
Portrait
Camera: Target: LatLng [latitude=-37.56599872157641, longitude=149.74892929649252, altitude=0.0], Zoom:14.527310986925153, Bearing:-0.0, Tilt:0.0
```
```
Landscape
Camera: Target: LatLng [latitude=-37.566016473887615, longitude=149.74892929647035, altitude=0.0], Zoom:13.687558074433808, Bearing:-0.0, Tilt:0.0
```

Your idea is correct - becuase the bounds are taller than wider, the landscape orientation should have a camera positioned further away to fit the bounds. And because of the higher zoom level when the device is in a landscape orientation the camera target should have the latitude value smaller in comparison to the portrait orientation as the bottom pixel padding is impacting a greater portion of the axis. Both of those values were computed correctly in my sample.

Would you be able to provide a fully isolated example of the issue you are expiriencing and the device (especially looking for the resolution and pixel density)? Thank you!

**Comment by Mordag** [comment]
@LukasPaczos Thanks for your reply. I will try to work on an example in the next days. If it is not the lat/long which is causing my issues, then it is probably the zoom level. As you can see the zoom level for my landscape is 21 and portrait is 14. That does not make sense really. Do you have any ideas why the zoom could be calculated wrongly?

**Comment by Mordag** [comment]
**Update**: @LukasPaczos I found the issue. It seems like that the padding is too large. As soon as I used the defaultPadding for the bottom padding, the camera moved to the expected position. I would expect that the camera can handle any padding values (regardless how large) and would set the camera accordingly - any thoughts?

**Comment by LukasPaczos** [comment]
Would you be able to share padding values you are referring to?

**Comment by Mordag** [comment]
@LukasPaczos 

Reference for:
```
mapboxMap.getCameraForLatLngBounds(latLng,
             intArrayOf(defaultPadding, defaultPadding, defaultPadding, additionalBottomPadding),
             mapboxMap.cameraPosition.bearing,
             mapboxMap.cameraPosition.tilt) ?: mapboxMap.cameraPosition
```
> defaultPadding = 96dp
> additionalPadding = 208dp

To fix the issue, I am now using these values for landscape:
> defaultPadding: 16dp
> additionalPadding = 36dp

Much smaller, but it is working. I think the 208dp (bottom) and 96dp (top) were larger than the current mapview height (in landscape).
