### ISSUE TITLE
awscli missing for iOS deploy builds

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1391]
https://travis-ci.org/mapbox/mapbox-gl-native/jobs/60790176

This appears to now only be in `docker/linux/Dockerfile` but it's needed for iOS deploy commits. 

/cc @kkaefer

**Comment by kkaefer** [comment]
Just install it. We install it for Linux builds as well.

**Comment by incanus** [comment]
Yep, I was rolling a (failing) build post-midnight and didn't want to forget so ticketed.
