### ISSUE TITLE
Need support for cordova framework. 

### ISSUE THREAD

**Issue by ansarikhurshid786** [mapbox/mapbox-gl-native#13912]
I am ionic cordova developer.  I am using mapbox last more than 1 yr. I found one plugin for cordova but it has no support. Mapbox team is not supporting to cordova which is very important.

**Comment by tobrun** [comment]
@ansarikhurshid786 thank you for reaching out and requesting support for the cordova plugin. We consider all cross platform solutions that are build on top of this repository as community driven. (for example see flutter project on [my personal github account](https://github.com/tobrun/flutter-mapbox-gl/issues).

**Comment by ansarikhurshid786** [comment]
I found cordova plugin for mapbox https://github.com/Telerik-Verified-Plugins/Mapbox, but that is not working simple map and also not update.

**Comment by tobrun** [comment]
@ansarikhurshid786 great, either create an issue in that repository or even better contribute to that repo.
