### ISSUE TITLE
Warn when not calling any of the on* methods when using the Android SDK

### ISSUE THREAD

**Issue by vanniktech** [mapbox/mapbox-gl-native#13921]
### Steps to reproduce

 1. Use Map View
 2. Don't call any of the on* methods like onResume/onStop

### Expected behavior

Get a warning that the consumer of the library does not call the on* methods

### Actual behavior

No warnings at all and simply a blank gray map is shown.

### Configuration

**Android versions:** 9
**Device models:** Nexus 5
**Mapbox SDK versions:** 6.5.0 / 6.7.0

I also talked to @Guardiola31337 about this and he is supportive of a warning about this misusage.

**Comment by Guardiola31337** [comment]
Re-opening

**Comment by vanniktech** [comment]
K(
