### ISSUE TITLE
Introduce builder pattern for LocationComponent activation

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#13931]
With a growing number of `LocationComponent#activate` parameters and all of them requiring permutations and creating overrides, it's starting to get hard to maintain. It'd be great to expose a `LocationComponent#ActivationBuilder` that would be passed into a single `LocationComponent#activate` method.

We can expose such a builder and deprecate all of the `#activation` overrides without breaking the semver.

**Comment by carstenhag** [comment]
As commented on https://github.com/mapbox/mapbox-gl-native/pull/13941#issuecomment-477079484, somehow the depreciation notices don't show what else to use because the comments gets removed.
