### ISSUE TITLE
Navigation Junction view and lane assistance

### ISSUE THREAD

**Issue by mkandulavm** [mapbox/mapbox-gl-native#13949]
Hi
Is there support within mapbox to render junction view and lane assistance during navigation ?

What data is required to enable junction view ? Do you require a 3D model of the junction/bridge ? how do other maps implement this ? What data can be extracted from OSM maps to support these functionalities?

What is the best strategy to implement this in mapbox ? 

Any help in understanding these features is greatly appreciated. 

Cheers,
Madan

**Comment by friedbunny** [comment]
Hi @mkandulavm — thanks for considering Mapbox. This repo is for reporting bugs, requesting features, and coordinating work related to the various Mapbox Map SDKs. For help with “how do I” questions, please ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox) or reach out to our excellent [support team](https://www.mapbox.com/contact/support/).
