### ISSUE TITLE
About VoiceOver function

### ISSUE THREAD

**Issue by 150vb** [mapbox/mapbox-gl-native#13946]
Hello!
Voiceover function is needed when our product uses the map. Could we set the content that VoiceOver reads as required? For example, turning off the VoiceOver feature of the compass.

**Comment by friedbunny** [comment]
Hrm, I’m not sure if it’s possible to reliably customize accessibility content for UI we provide — for the compass, it has [values updated automatically during rotation](https://github.com/mapbox/mapbox-gl-native/blob/ios-v4.8.0/platform/ios/src/MGLMapView.mm#L6356-L6357).

/cc @1ec5

**Comment by 150vb** [comment]
That's right, even though I've set the compass accessibilityElementsHidden YES, it won't read, and then it will update and become readable again

**Comment by 1ec5** [comment]
The most you can do right now is to subclass MGLMapView and override UIAccessibilityContainer methods such as `-accessibilityElementCount` and `-accessibilityElementAtIndex:`. I suppose in this case you could look for the entry corresponding to the compass and remove it from the array. 😬 But we should remember the compass button’s `accessibilityElementsHidden` property for when the button gets reshown.

We should probably also expose accessibility-related options. For example, a developer may want to customize [the source layers](https://github.com/mapbox/mapbox-gl-native/blob/cced7db5118ca947455717574c175e5ce5b1a6f0/platform/darwin/src/MGLStyle.mm#L608) that contribute to the list of places, in case they pull in sources other than the Mapbox Streets source.
