### ISSUE TITLE
Mapbox Android - Clusters not displayed due to missing fonts

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#13945]
After updating to Mapbox 7.0.0, I've noticed that no clusters are being rendered when opening the app in offline mode. I identified the issue which is caused by the related cluster layer's font. It seems like something changed between Mapbox 6.x and 7.x regarding how fonts are being downloaded and used. As soon as I re-enable the internet on my device, the clusters are being displayed using the correct font.

My current config of my symbol layer:
```
PropertyFactory.iconImage("cluster_image"),
PropertyFactory.textField(Expression.toString(Expression.get("point_count"))),
PropertyFactory.textSize(resourceAccessor.getDimension(R.dimen.cluster_label_text_size)),
PropertyFactory.textColor(Color.WHITE),
PropertyFactory.textIgnorePlacement(true),
PropertyFactory.textAllowOverlap(true),
PropertyFactory.iconAllowOverlap(true),
PropertyFactory.textFont(arrayOf("VIC SemiBold", "Open Sans Regular"))
```

### Configuration

**Mapbox SDK versions:** 6.x, 7.x

**Comment by Mordag** [comment]
**Update:** It seems like that this issue is not always given. It sometimes appears, sometimes not. It seems to have something to do with the ambient cache of the app. Might be caused by server issues or something related?

**Comment by tobrun** [comment]
@Mordag thank you for reporting and adding updates. It seems your custom font isn't being cached.

**Comment by Mordag** [comment]
@tobrun I forgot to update my post, but I did some more testing with the "default" font and the problem is also given for this one. It works if you nearly never use the map (zooming etc.) but as soon as you increase the usage and fill the ambient cache, the issue happens (when you cold start the app in offline mode).

**Comment by LukasPaczos** [comment]
A wild guess, but can this be connected to https://github.com/mapbox/mapbox-gl-native/issues/4411? Are the custom fonts part of the style used to download offline regions?

**Comment by Mordag** [comment]
@LukasPaczos Sounds like this could be connected. Yes the custom font is part of the offline region download.
