### ISSUE TITLE
Provide way to mock Location or insert custom location manager in Map Android SDK

### ISSUE THREAD

**Issue by sajeel** [mapbox/mapbox-gl-native#13954]
Could you please tell, how to introduce/inject custom location or custom location manager in the latest Android Map SDK? its been there in Navigation SDK but couldn't find in the Map SDK

**Comment by LukasPaczos** [comment]
Hey @sajeel, you can use `LocationComponent#setLocationEngine` and `LocationComponent#setLocationEngineRequest`, or set the location engine to `null` and use `LocationComponent#forceLocationUpdate` to push updates from your arbitrary source of location data.

I hope this helps!

**Comment by sajeel** [comment]
thanks @LukasPaczos for such quick response.
