### ISSUE TITLE
Fullscreen CompassView click behavior

### ISSUE THREAD

**Issue by ulusoyca** [mapbox/mapbox-gl-native#13955]
I want to have a full-screen and semi-transparent `CompassView` on top of map view in a way that `CompassView` looks like a compass rose on the map. However, since the compass view drawable is full-screen, the clicks on the maps are consumed by the compass view instead of map view:
`MapView#compassView.setOnClickListener(createCompassClickListener(cameraDispatcher))`

There should be a way of setting the compass view click listener to `null`. I think this is a common use case when we have `N` `S` `W` `E` letters on a transparent drawable on top of map.

**Comment by tobrun** [comment]
@ulusoyca you should be able to call `mapView.findViewById(R.id.compassView).setOnClickListener(null)`

**Comment by ulusoyca** [comment]
@tobrun Thank you. I should have thought about it. Still, it would be nice to have more explicit API.

**Comment by tobrun** [comment]
I would prefer limiting the API surface, the use-case described in OP doesn't qualify as a supported use-case imo. If we weren't able to pull this off with Android SDK API, I would have suggested creating a own custom view instead of hacking around with the CompassView from this SDK.

**Comment by ulusoyca** [comment]
@tobrun that was my initial idea but then syncing the camera moving in tracking mode with the rotation animation of my customview was the problem. Camera moving, and custom compass should smoothly move together.

**Comment by ulusoyca** [comment]
For future reference, the way without hacking CompassView from this SDK is extending the `MapView` class and overriding `onInterceptTouchEvent` method.
```
    override fun onInterceptTouchEvent(ev: MotionEvent?): Boolean {
        super.onInterceptTouchEvent(ev)
        return true
    }
```
