### ISSUE TITLE
Layers disappearing 

### ISSUE THREAD

**Issue by anton-shestak** [mapbox/mapbox-gl-native#13969]
Hi. I have the next problem. On map I have a Line layer which draws as expected. Than I have a Symbol layer which has the same FeatureCollection like in Line layer. But when i add Symbol layer to the map line layer disappear. 
Code example:

    FeatureCollection featureCollection = FeatureCollection.fromFeatures(features); 
    GeoJsonSource geoJsonSource = new GeoJsonSource("source", featureCollection);
    mapboxMap.addSource(geoJsonSource);
    LineLayer lineLayer = new LineLayer("lines", "source");
        lineLayer.setProperties(
                PropertyFactory.lineWidth(width),
                PropertyFactory.visibility(Property.VISIBLE),
                PropertyFactory.lineColor(color));
        mapboxMap.addLayer(lineLayer);

    SymbolLayer symbolLayer = new SymbolLayer("symbols_asdfasd", "source");
        symbolLayer.setProperties(
                PropertyFactory.symbolPlacement(Property.SYMBOL_PLACEMENT_LINE),
                PropertyFactory.textSize(8f),
                PropertyFactory.textField("1232")
        );
    mapboxMap.addLayer(symbolLayer );  // after that , map hasn't symbolLayer  and lineLayer 

What I did wrong?
version ----    com.mapbox.mapboxsdk:mapbox-android-sdk:6.6.0

**Comment by tobrun** [comment]
@anton-shestak thank you for reaching out and reporting your issue. We have made some fixes in recent version about flickering and dissapearing layers. Would you be able to update your version to a more recent version? Information about how to migrate your 6.0 source code to 7.x [here](https://github.com/mapbox/mapbox-gl-native/wiki/Android-6.x-to-7.x-migration-guide).

**Comment by atoropov** [comment]
I am using `com.mapbox.mapboxsdk:mapbox-android-sdk:7.2.0` and still have similar issue

![ezgif-1-07e3fddd5e16](https://user-images.githubusercontent.com/5703185/53643781-fdcd2200-3c45-11e9-81e9-e5ca0e2480f1.gif)

**Comment by tobrun** [comment]
Thank you for adding that Gif, this makes it a lot easier to understand what is going on. This is actuallly expected behaviour. To alter this enable the following:

```
        // for icon
        iconIgnorePlacement(true),
        iconAllowOverlap(true),
        // for text
        textIgnorePlacement(true),
        textAllowOverlap(true),
```


Closing this issue as answered.
