### ISSUE TITLE
Enable Metrics To TEST Server

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1396]
The [current implementation hardcodes the URL](https://github.com/mapbox/mapbox-gl-native/blob/51c069502880e38a6dabf520c032fd6f293ee744/platform/ios/MGLMapboxEvents.m#L447) endpoint to be [the PROD data server](https://github.com/mapbox/mapbox-gl-native/blob/51c069502880e38a6dabf520c032fd6f293ee744/platform/ios/MGLMapboxEvents.m#L16).  Need to enable access to push to TEST server to help minimize "data pollution" during ongoing development.

/cc @mapbox/mobile @camilleanne @mick @edenh @willwhite

**Comment by 1ec5** [comment]
@bleege and I were brainstorming about ways to enable support for a test server without either exposing that server to the public or enabling developers on free plans to override the server with their own. In the end, it sounds like we may just have to do the most straightforward thing codewise and rely on an honor system, just as we do for attribution. But if there is a stricter way to enforce the use of Mapbox’s Metrics server, we should, because there will be a much greater desire to avoid Mapbox Metrics than Mapbox branding.

**Comment by 1ec5** [comment]
The most straightforward thing to do would be to have `MGLMapboxEvents` implement a `-hostname` method. We shouldn’t hardcode the test server in here because (presumably) it wouldn’t be accessible to developers outside of Mapbox. So you’ll probably have to figure out how internal apps for testing the Metrics server should know about that endpoint.

**Comment by bleege** [comment]
Moved to iOS Beta 2 due to internal discussion today.

**Comment by bleege** [comment]
Look into using [`Info.plist` proposal](https://github.com/mapbox/mapbox-gl-native/issues/1535) to set Metrics server url.  This will hopefully allow for dynamic file substitution at library build time so that the default url will be set to TEST, and release builds can have the PROD url substituted.

**Comment by bleege** [comment]
> We shouldn’t hardcode the test server in here because (presumably) it wouldn’t be accessible to developers outside of Mapbox.

I'm thinking that the way forward on this is to actually hardcode in the TEST URL for the project.  This will ensure that internal and external GL developers are always only sending data to TEST infrastructure during GL development.  The only time that Metrics data should be sent to the PROD infrastructure is for apps implementing the released SDK which is published on Cocoapods.  Of course, that begs the question of how likely do we think people will roll their own iOS GL SDK from source?

**Comment by bleege** [comment]
> Of course, that begs the question of how likely do we think people will roll their own iOS GL SDK from source?

Just saw that there's a new `make ipackage` command for [manually rolling your own iOS GLD SDK from source](https://github.com/mapbox/mapbox-gl-native#manually).  I'll work with this to add PROD URL substitution for this use case.

**Comment by bleege** [comment]
PROD: https://api.tiles.mapbox.com
TEST: https://cloudfront-staging.tilestream.net

**Comment by incanus** [comment]
> Just saw that there's a new make ipackage command

This is also used by Travis for rolling builds, so keep that in mind from a testing / metrics POV.

**Comment by bleege** [comment]
> This is also used by Travis for rolling builds,

Thanks for confirming @incanus.  That actually makes this better as it'll be the one place where ALL release builds come from.  :+1:

**Comment by incanus** [comment]
Keep in mind also that when Travis is severely backed up, sometimes we roll builds locally, manually. But still using `make ipackage`.

**Comment by bleege** [comment]
Ugh... thought / typed too quickly there.  Rolling builds will be internal test builds.  Ok, back to the drawing board.

**Comment by bleege** [comment]
Did some more research and found out that Travis is using `make ipackage-sim` in `RELEASE` mode.  Confirmed with @incanus that when [automated iOS Tests are re-enabled](https://github.com/mapbox/mapbox-gl-native/issues/1452) that a new build process will be setup on Travis and it'll be in `DEBUG` mode.

**Comment by bleege** [comment]
Implemented the ideas ^^ so that...

1. TEST Server is hardcoded into source code
1. PROD Server is substituted in during `make ipackage` when in `Release` build type

**Comment by bleege** [comment]
The next step is allow app based opt out of this so that internal apps that implement the SDK can point to TEST.

**Comment by bleege** [comment]
Ok, after some internal discussion with @1ec5 we've decided that the easiest way to solve this issue would be to ignore the `sed` ^^, keep the Metrics URL constant set to PROD, and rely on `Info.plist` per app to overwrite the TEST url.

This keeps Mapbox GL and internal apps running TEST, while any release of the SDK set to PROD.

**Comment by bleege** [comment]
Travis tested and now merged.
