### ISSUE TITLE
Documentation Question/Suggestion: example of querySourceFeatures()

### ISSUE THREAD

**Issue by Yermo** [mapbox/mapbox-gl-native#13972]
I am working with the Mapbox GL Native Android SDK v7.1.2 from NativeScript.

I have a GeoJSON Source. I would like to get access to it's Features.

[querySourceFeatures() ](https://docs.mapbox.com/android/api/map-sdk/7.1.2/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.html#querySourceFeatures-com.mapbox.mapboxsdk.style.expressions.Expression-)seems to be the method to use but there are no examples or indication how to form an [Expression](https://docs.mapbox.com/android/api/map-sdk/7.1.2/com/mapbox/mapboxsdk/style/expressions/Expression.html) to pull out the first Feature. 

From NativeScript I cannot call querySourceFeatures() without arguments as it does not resolve the method. Calling it with null returns nothing. 

I posted on [Stackoverflow](https://stackoverflow.com/questions/54795079/how-to-get-a-geometry-from-a-mapbox-gl-native-geojsonsource) but have gotten no useful responses.

What am I missing?

**Comment by tobrun** [comment]
@Yermo an example can be found [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/feature/QuerySourceFeaturesActivity.java#L72). More information on expressions can be found [here](https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions).

Since you are implementing from NaitveScript it might make sense using the raw expression, expressions are under the hood just an Json array, you can set them as a string using https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/expressions/Expression.java#L4134. 

I have ticketed out this request for documentation in our documentation repo [here](https://github.com/mapbox/android-docs/issues/865)

**Comment by LukasPaczos** [comment]
Hey @Yermo, a quick note, that in order to get all available features you can simply call `querySourceFeatures(Expression.literal(true))`. Also, querying the source doesn't have a concept of "the first feature", it will always return all reachable features on the map's viewport (even if invisible), unless it's scoped by the filter.

**Comment by Yermo** [comment]
Thank you!! This is exactly what I needed.

**Comment by Yermo** [comment]
There is still something that I am missing. 

To eliminate the possibility that there's some NativeScript bridge/marshalling issue, I decided to try to get querySourceFeatures() to work directly in Java. 

I was unable to get the Mapbox-Android-Demo to compile so I have created a fresh Java project following the [getting started tutorial](https://docs.mapbox.com/help/tutorials/first-steps-android-sdk/). 

Working with the [Draw a GeoJSON Line ](https://docs.mapbox.com/android/maps/examples/draw-a-geojson-line/) example as a base, after quite a bit of trial and error, I have successfully gotten a geojson line to draw on the map. 

```

  String geojsonString = loadGeoJsonFromAsset( "example.geojson");

  Log.d( TAG, "got geojsonString " + geojsonString );

  FeatureCollection testCollection = FeatureCollection.fromJson( geojsonString );

  style.addSource( new GeoJsonSource( "line-source", featureCollection ));

  // this correctly draws a test line on my map. 

  style.addLayer(new LineLayer("linelayer", "line-source")
  .withProperties(PropertyFactory.lineCap(Property.LINE_CAP_SQUARE),
     PropertyFactory.lineJoin(Property.LINE_JOIN_MITER),
     PropertyFactory.lineOpacity(.7f),
     PropertyFactory.lineWidth(7f),
     PropertyFactory.lineColor(Color.parseColor("#3bb2d0"))));

  GeoJsonSource testSource = style.getSourceAs( "line-source");

  // this produces "got source com.mapbox.mapboxsdk.style.sources.GeoJsonSource@671565c"
  
  Log.d( TAG, "got source " + testSource );

  List<Feature> testList = testSource.querySourceFeatures( Expression.literal( true ) );

  // this produces "got testList: []" and I do not understand why.

  Log.d( TAG, "got testList: " + testList );
```

The reason that I want to query the source of the GeoJSON line is that I want to update it as I get new locations for the user thereby drawing a nice line of the user's track on the map. 

My understanding is that I have to query the underlying source, get the feature, add the point to the feature geometry, and ... the line should redraw with the additional point? 

Just in case it's relevant I'm using the following GeoJSON:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "Test Line over Maryland, USA"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [-76.926164,39.019062],
          [-76.926100,39.019168],
          [-76.926013,39.019257],
          [-76.925905,39.019328],
          [-76.925777,39.019380],
          [-76.925632,39.019408],
          [-76.925481,39.019405],
          [-76.908129,39.074828],
          [-76.910401,39.075078],
          [-76.913482,39.074758],
          [-76.924829,39.073772],
          [-77.228768,39.158858],
          [-77.233073,39.161274],
          [-77.237891,39.163827],
          [-77.240401,39.165853],
          [-77.242376,39.168174]
        ]
      }
    }
  ]
}
```

to load the GeoJSON asset I am using this method I ripped off from one of the examples:

```
    private String loadGeoJsonFromAsset(String filename) {
        try {
            // Load GeoJSON file from local asset folder
            InputStream is = getAssets().open(filename);
            int size = is.available();
            byte[] buffer = new byte[size];
            is.read(buffer);
            is.close();
            return new String(buffer, "UTF-8");
        } catch (Exception exception) {
            Log.e("Exception loading GeoJSON: %s", exception.toString());
            exception.printStackTrace();
            return null;
        }
    }
```

What am I doing incorrectly?
