### ISSUE TITLE
Mapbox access token expiration 

### ISSUE THREAD

**Issue by tazik561** [mapbox/mapbox-gl-native#13989]
Hi. I want to use mapbox into application so in order i registered in map box official site and got an access token. But i do not know that any limitation to use access token or other feature is there exist?

For example is there any limitation or expiration date to use access token that i got?

**Comment by LukasPaczos** [comment]
Hey @tazik561, thanks for using Mapbox! When it comes to the access tokens, please refer to [the documentation](https://docs.mapbox.com/help/how-mapbox-works/access-tokens/) and [help](https://docs.mapbox.com/help/) pages in general.

**Comment by topinvestor** [comment]
I also want to know if access token expire. When I try to upload with aws sdk I get 

"error ExpiredToken: The provided token has expired."

After 
curl https://api.mapbox.com/uploads/v1/<username>/credentials?access_token=<Secret token>
I provide: 
AccessKeyId, SecretAccessKey, sessionToken

What token expired? <Secret token> or sessionToken?

I run the command above generate sessionToken but every time the values are same.

Do I need to create new Access tokens in my account when I need to upload new MBTiles file?

**Comment by friedbunny** [comment]
@topinvestor please see https://github.com/mapbox/mapbox-gl-native/issues/13989#issuecomment-467353606 for where to learn more about access tokens.
