### ISSUE TITLE
flaky iOS tests

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1399]
Seeing frequent build failures on Travis like the following:

https://travis-ci.org/mapbox/mapbox-gl-native/jobs/60892927

**Comment by friedbunny** [comment]
@tmpsantos was encountering this Travis simulator issue the other day on #1326, as well.

https://travis-ci.org/mapbox/mapbox-gl-native/jobs/60651556

**Comment by tmpsantos** [comment]
> @tmpsantos was encountering this Travis simulator issue the other day on #1326, as well.
> 
> https://travis-ci.org/mapbox/mapbox-gl-native/jobs/60651556

I think in my case my branch is to blame. I can reproduce the failure locally and when I remove my branch it vanishes. :(

**Comment by kkaefer** [comment]
https://github.com/mapbox/mapbox-gl-native/issues/1360

**Comment by jfirebaugh** [comment]
#1360 looks like a different kind of flakiness. This one is:

```
testBottomLayoutGuide encountered an error (Test process crashed)
```

Presumably just general app crashiness.

**Comment by jfirebaugh** [comment]
@incanus Is there a way we can get stack traces out of iOS test crashes?

**Comment by incanus** [comment]
I can look into it; not sure.

**Comment by friedbunny** [comment]
Yes, #1360 is an actual timing bug in the iOS `testDelegateRegionDidChange` test that has only showed up on Travis. I made that test somewhat more robust in #1362, but it hasn't been Travis-approved (coincidentally, [because of simulator issues](https://travis-ci.org/mapbox/mapbox-gl-native/jobs/60386465)) or merged yet.

**Comment by friedbunny** [comment]
KIF (our iOS testing framework) [has disabled iOS 7 tests on Travis](https://github.com/kif-framework/KIF/pull/640) because they are encountering this issue in their own development.

**Comment by jfirebaugh** [comment]
⇢ #1452
