### ISSUE TITLE
What is all I can use with mapbox-sdk-android in offline mode after downloading maps

### ISSUE THREAD

**Issue by 3issa3issa** [mapbox/mapbox-gl-native#13993]
hello 
iI am currently working on an Android application use maps offline mode ...  Can I do  a search for cafes and restaurants ,get users location , and get route...ect  in mode offline after downloading maps ?

**Comment by captainbarbosa** [comment]
Hi @3issa3issa — thanks for using Mapbox. This repo is for reporting bugs, requesting features, and coordinating work related to the various Mapbox Map SDKs. For help with “how do I” questions, please ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox) or reach out to our excellent [support team](https://www.mapbox.com/contact/support/).

**Comment by mysticvalley** [comment]
Hey @3issa3issa ,

Did you have any luck with android or iOS application perform offline map search using Search SDK for cafes and restaurants? I can see that in Android Beta, we have `[OfflineSearchEngine](https://docs.mapbox.com/android/search/api/core/1.0.0-beta.14/sdk/com.mapbox.search/-offline-search-engine/)`. But this doesn't seems to be true for iOS. Any thoughts?

Any information would be highly appreciated. Thanks.

**Comment by 3issa3issa** [comment]
No, I forgot mapbox .. I haven't used it for a long time. sorry!

Le lun. 28 juin 2021 à 03:56, Rajan Maharjan ***@***.***> a
écrit :
