### ISSUE TITLE
The provided example macosapp Archiving fails

### ISSUE THREAD

**Issue by topinvestor** [mapbox/mapbox-gl-native#14007]
### Steps to reproduce

 1. Build macosapp example at:
https://github.com/mapbox/mapbox-gl-native/tree/master/platform/macos

 2. Archive

 3.

### Expected behavior

Archive created at /Applications folder configured from MapBox as default.

### Actual behavior
Archiving failed with following errors:

  no such file or directory: ~/mapbox-gl-native/build/macos/Release/libgtest.a
  no such file or directory: ~/mapbox-gl-native/build/macos/Release/libmbgl-core.a
  no such file or directory: ~/mapbox-gl-native/build/macos/Release/libmbgl-filesource.a
  no such file or directory: ~/mapbox-gl-native/build/macos/Release/libmbgl-loop-darwin.a
  no such file or directory: ~/mapbox-gl-native/build/macos/Release/libicu.a

### Configuration

**Mapbox SDK versions:** 
**iOS/macOS versions:** 
**Device/simulator models:**
**Xcode version:**

**Comment by 1ec5** [comment]
Did you run `make xproj` beforehand? Here are instructions for building from source:

https://github.com/mapbox/mapbox-gl-native/blob/master/platform/macos/DEVELOPING.md#building-the-sdk
