### ISSUE TITLE
Translation animation conflicts with rotation animation.

### ISSUE THREAD

**Issue by 150vb** [mapbox/mapbox-gl-native#14009]
When MGLMapView.userTrackingMode set to MGLUserTrackingModeFollowWithHeading, zoomLevel is 20, translation animation conflicts with rotation animation. 
When panning and rotations become more frequent, the animation becomes less smooth. One point to another point animation is gone.
I think MGLUserLocationAnimationDuration should be change by developer.

Mapbox SDK versions:4.7.1

**Comment by fabian-guerra** [comment]
We are tracking concurrent animations in https://github.com/mapbox/mapbox-gl-native/issues/3625.

A workaround may be https://github.com/mapbox/mapbox-gl-native/issues/9808

**Comment by juliengdt** [comment]
@fabian-guerra #9808 is not a workaround: just with `MGLMapView.userTrackingMode` set to `.followWithHeading` on a fresh project made this issue (animation for heading of default location manager + animation for coordinate for default location manager)

this is really annoying, mostly when you are developing a indoor position application with heading
