### ISSUE TITLE
Android SDK build failure 

### ISSUE THREAD

**Issue by johnwilde** [mapbox/mapbox-gl-native#14016]
I was following steps here to build Android SDK (trying to track down a native crash) https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android, but am getting a build failure relating to `unique_resource.hpp` not found.  Happy to provide more info if it would be helpful.

### Steps to reproduce

 1. Follow steps above (on mac os, High Sierra) with all dependencies met

### Expected behavior

AS project to be built

### Actual behavior

Build fails (first error): 
> Task :MapboxGLAndroidSDK:externalNativeBuildDebug
Build mapbox-gl arm64-v8a
[1/432] Building CXX object CMakeFiles/mbgl-core.dir/src/mbgl/geometry/line_atlas.cpp.o
FAILED: CMakeFiles/mbgl-core.dir/src/mbgl/geometry/line_atlas.cpp.o 
/Users/johnwilde/code/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/arm64-v8a/launch-cxx /Users/johnwilde/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/Users/johnwilde/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/johnwilde/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot  -DMBGL_USE_GLES2=1 -DRAPIDJSON_HAS_STDSTRING=1 -D_GLIBCXX_USE_CXX11_ABI=1 -I../../../../../../../include -I../../../../../../../src -I../../../../../../default/include -I../../../../../include -isystem ../../../../../../../vendor/earcut.hpp/include -isystem ../../../../../../../vendor/eternal/include -isystem ../../../../../../../vendor/expected/include -isystem ../../../../../../../vendor/geojson-vt-cpp/include -isystem ../../../../../../../vendor/kdbush.hpp/include -isystem ../../../../../../../vendor/shelf-pack-cpp/include -isystem ../../../../../../../vendor/supercluster.hpp/include -isystem ../../../../../../../vendor/unique_resource -isystem ../../../../../../../vendor/wagyu/include -isystem ../../../../../../../vendor/boost/include -isystem ../../../../../../../vendor/geojson.hpp/include -isystem ../../../../../../../vendor/geometry.hpp/include -isystem ../../../../../../../vendor/icu/include -isystem ../../../../../../../vendor/optional/include -isystem ../../../../../../../vendor/polylabel/include -isystem ../../../../../../../vendor/protozero/include -isystem ../../../../../../../vendor/rapidjson/include -isystem ../../../../../../../vendor/variant/include -isystem ../../../../../../../vendor/vector-tile/include -isystem ../../../../../../../vendor/jni.hpp/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security -stdlib=libc++ -frtti -fexceptions -Qunused-arguments -Werror -ftemplate-depth=1024 -Wall -Wextra -Ws
hadow -Wnon-virtual-dtor -Wno-variadic-macros -Wno-unknown-pragmas -Wno-error=unknown-warning-option -Qunused-arguments -fcolor-diagnostics -ffunction-sections -fdata-sections -O0 -fno-limit-debug-info  -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -std=c++14 -MD -MT CMakeFiles/mbgl-core.dir/src/mbgl/geometry/line_atlas.cpp.o -MF CMakeFiles/mbgl-core.dir/src/mbgl/geometry/line_atlas.cpp.o.d -o CMakeFiles/mbgl-core.dir/src/mbgl/geometry/line_atlas.cpp.o -c ../../../../../../../src/mbgl/geometry/line_atlas.cpp
In file included from ../../../../../../../src/mbgl/geometry/line_atlas.cpp:1:
In file included from ../../../../../../../src/mbgl/geometry/line_atlas.hpp:3:
In file included from ../../../../../../../src/mbgl/gl/texture.hpp:3:
../../../../../../../src/mbgl/gl/object.hpp:5:10: fatal error: 'unique_resource.hpp' file not found
#include <unique_resource.hpp>

### Configuration

**Android versions:** 
**Device models:** 
**Mapbox SDK versions:** 
Building from SHA at ceec74f52

**Comment by LukasPaczos** [comment]
Hey @johnwilde, thanks for reaching out. Looks like you're missing vendor packages, could you try initializing the submodules first by calling `git submodule update --init`?

**Comment by johnwilde** [comment]
Thanks for the help.  I did a fresh checkout of the project and was able to get the build to succeed. I think I was in a bad state because I had checked the project out a while ago.  I ran into another issue with installing some node modules, but running `mkdir -p mapbox-gl-js/test/integration` allowed me to proceed.

**Comment by LukasPaczos** [comment]
Great to hear that @johnwilde!
