### ISSUE TITLE
autorelease pool and logging/Request callbacks.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1401]
Can someone please clarify how the following works without any warning/error in xcode?

- Request callbacks are done on a thread that does not have an NSAutoRelease pool.
- In the callback  one could call a method that eventually calls a method that creates autoreleased objects e.g. Log::platformRecord

For these use cases one would expect to get an xcode error that autoreleasepool is not setup. However this warning/error never happens in xcode. I am unable to explain why this is working.

This is what I tried.

1.) In Source::load, it loads the json. In the call back, I added an unconditional Log::Warning. For e.g. Log::Warning(Event::General, "Blah");

This will eventually call Log::platformRecord, where one could end up using autoreleased objects.

2.) In Log::platformRecord, I added the following lines of code.

    NSString* testing = [NSString stringWithFormat:@"Testingblah %d", 5];  // testing is an autoreleased object

    NSLog(@"%@", testing);

However I never see the expected warning/error regarding using autoreleased object without the pool.

**Comment by 1ec5** [comment]
At that point, Cocoa appears to be in multithreaded mode (verified by calling `-[NSThread isMultiThreaded]` inside `Log::platformRecord()`). Supposedly, every thread comes with an autorelease pool [in multithreaded mode only](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmAutoreleasePools.html#//apple_ref/doc/uid/20000047-1041876-CJBFEIEG). The Map thread isn’t created using `NSThread` APIs, so it is possible to get into `Log::platformRecord()` while multithreaded mode is off, by adding a `Log::Warning()` in an `std::thread` created at the top of `-[MGLMapView commonInit]`. However, even then, I get no warning about a missing autorelease pool.

**Comment by mb12** [comment]
1.) Does this mean that in multithreaded mode using @autoreleasepool blocks (for ARC)  is just an optimization to reduce peak memory footprint? It is not needed for correctness.

**Comment by incanus** [comment]
I haven't probed this yet, but keep in mind that some of the core libraries like Darwin HTTP [don't use ARC](https://github.com/mapbox/mapbox-gl-native/blob/c6be7086235cac73d745058b114941edf74f5d5c/gyp/http-nsurl.gypi#L36).

**Comment by 1ec5** [comment]
> some of the core libraries like Darwin HTTP [don't use ARC](https://github.com/mapbox/mapbox-gl-native/blob/c6be7086235cac73d745058b114941edf74f5d5c/gyp/http-nsurl.gypi#L36)

Good point. See also #1425.

**Comment by 1ec5** [comment]
> 1.) Does this mean that in multithreaded mode using `@autoreleasepool` blocks (for ARC) is just an optimization to reduce peak memory footprint? It is not needed for correctness.

No, an autorelease pool is needed “on the stack” any time we expect an object to be autoreleased. That’s why we also apply it [in a few other places](https://github.com/mapbox/mapbox-gl-native/search?utf8=%E2%9C%93&q=autoreleasepool). I don’t know why we aren’t getting a warning in this particular scenario; perhaps we’re getting an autorelease pool indirectly, but I need to do a little more digging to know for sure.

**Comment by mb12** [comment]
Even the following piece of code works as expected (the memory grows and is reclaimed when thread exits) without any warning. I remember this used to give warning long long time ago if 'NSAutoreleasepool alloc init' were missing.

```
-(void) testAutoReleaseBody {
	NSString* largeString = @"";
	for(unsigned int i=0; i<1000; i++) {
		largeString = [NSString stringWithFormat:@"%@-large-string", largeString];
	}
	fprintf(stderr, "%lu\n", (unsigned long)[largeString length]);
	NSMutableArray* array = [[[NSMutableArray alloc] init] autorelease];
	for(unsigned int i=0; i<1000; i++) {
		NSString* str = [NSString stringWithFormat:@"%@", largeString];
		[array addObject:str];
	}
	fprintf(stderr, "%lu\n", (unsigned long)[array count]);
}
-(void)testAutoRelease {
	[self performSelectorInBackground:@selector(testAutoReleaseBody) withObject:nil];
}

```

**Comment by 1ec5** [comment]
@mb12 and I have been expecting to see warnings along the lines of:

>     *** __NSAutoreleaseNoPool(): Object 0x5f1f5c0 of class __NSCFDictionary autoreleased with no pool in place - just leaking

But apparently that warning is specific to the old `NSAutoreleasePool`, whereas these days Cocoa apps use the runtime-level `@autoreleasepool` construct.

Given that we expect client apps to wrap calls to `UIApplicationMain()` in an `@autoreleasepool`, #1425 pacifies the static analyzer, and the memory is reclaimed as you expect, I think we’re in a good position to close this particular ticket. But please reopen or file a new one if you see a leak anywhere that results from a missing pool.
