### ISSUE TITLE
Quick zoom fling issues

### ISSUE THREAD

**Issue by hurrba** [mapbox/mapbox-gl-native#14013]
Latest version of Android SDK has some issues with quick zoom and flinging; it flings the map while zooming instead of just zooming.

### Steps to reproduce

 1. Double-tap and fling to zoom on map

### Expected behavior
Zoom in/out on map where you tap.

Version 7.1.2 works as expected: 
![7 1 2](https://user-images.githubusercontent.com/2956036/53575272-7f06b500-3b71-11e9-9e28-1e1864b6ba22.gif)

### Actual behavior
Zooms in/out and flings the map:
![7 2 0](https://user-images.githubusercontent.com/2956036/53575318-9ba2ed00-3b71-11e9-87ba-07aff5a41258.gif)

### Configuration

**Android versions: 9** 
**Device models: OnePlus A6003** 
**Mapbox SDK versions: 7.2.0**

**Comment by hurrba** [comment]
could it be related to https://github.com/mapbox/mapbox-gl-native/pull/13791 ?

**Comment by LukasPaczos** [comment]
It does look like a regression, thanks a lot for the report @hurrba!
