### ISSUE TITLE
Label clipping / visibility

### ISSUE THREAD

**Issue by pbnsilva** [mapbox/mapbox-gl-native#14011]
Hello, I'm using `node-mapbox-gl-native` `v4.1.0` to render tiles using a custom style.

There are situations where parts of labels are visible at tile borders when they shouldn't because they'd overlap with another label in the adjacent tile.

I am using `mode: tile` and `symbol-avoid-edges: true`. See the full style [here](https://drive.google.com/file/d/1qV170Wjv8BrGoRr7pjDFp0-iQzdCZqK_/view?usp=sharing).

For example, notice the `L` on the right tile, which is part of a city label.

![example](https://user-images.githubusercontent.com/2334434/53558961-05ef6980-3b41-11e9-84f3-e3408a983d07.png)

**Comment by fpsampayo** [comment]
Hi, I can confirm that this problem still persists with v4.2.0.

**Comment by pbnsilva** [comment]
This still happens a lot, even with v5.0.0. Any guidance?

**Comment by pbnsilva** [comment]
I've opened another issue: https://github.com/mapbox/mapbox-gl-native/issues/15805
