### ISSUE TITLE
User location changes more smooth 

### ISSUE THREAD

**Issue by impresyjna** [mapbox/mapbox-gl-native#14027]
### Expected behavior
When I try to make user location changes more smooth it is jumping like hell. I set new center on map using setCenter method and new user location using updateUserLocation method. Is it possible to make this animation smoother? 

**Mapbox SDK versions:** 4.6.0
**iOS/macOS versions:** 11.0 and 12.0
**Device/simulator models:** iPhone 7
**Xcode version:** 10.1

**Comment by fabian-guerra** [comment]
Hi, @impresyjna. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/) or check our [documentation](https://www.mapbox.com/ios-sdk/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
