### ISSUE TITLE
after download packs , how will i show tiles on map when application is offline 

### ISSUE THREAD

**Issue by RahulGusain** [mapbox/mapbox-gl-native#14021]
After downloaded packs , how will i show tiles on map when application is offline

**Comment by tobrun** [comment]
If the tiles are in your cache, they should show up without internet connection. Things that are important to make this happen: having the camera position matching the bounds region and using the same style as the offline region. Closing this issue as answered. For future issues, please follow the issue template guidelines.

**Comment by RahulGusain** [comment]
Thanks a lot, I got it, where I was wrong, I was not passing coordinate of the region.
