### ISSUE TITLE
MapView.onDestroy() freezes at nativeDestroy when map is used inside dialog fragment

### ISSUE THREAD

**Issue by androideveloper** [mapbox/mapbox-gl-native#14025]
When map is used inside DialogFragment,  NativeDestroy freezes and never completes. The sample I have created is using SupportMapFragment inside DialogFragment, but I have also tried to extend Fragment and inmplement map logic inside. The same result.
I have found similar issues here: https://github.com/mapbox/mapbox-gl-native/issues/11153  https://github.com/mapbox/mapbox-gl-native/issues/10809

### Steps to reproduce

[Mapdox Crash Demo](https://www.dropbox.com/s/1826wn6nksukhx3/MapboxDialogCrashDemo.zip?dl=0) (insert your map key in strings.xml)
 1. Open this sample app
 2. Click on button, map dialog is opened
 3. Click Finish or Cancel, app freezes

### Expected behavior

mapView.onDestroy() completes without issue

### Actual behavior
Call to destroy freezes thread

### Configuration

**Android versions:** 9.0, 8.1
**Device models:** Xiaomi mi a2 lite, Moto g5 plus
**Mapbox SDK versions:** v7.2.0

**Comment by LukasPaczos** [comment]
Hey @androideveloper, thanks for reporting the issue. I understand, that you're calling `MapView#onDestroy` from fragment's `#onDestroyView` and still running into a freeze, right? Could you compare your setup to [this example](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/MapInDialogActivity.java)? Do you spot any differences?

**Comment by androideveloper** [comment]
Right. Actually I'm using SupportMapFragment inside my dialog as a child fragment. That's the main difference between these setups. But I have imported your code into my sample project and still get freeze! The only difference as I can see is that I have changed your example Fragments from v4 to AndroidX version.

**Comment by androideveloper** [comment]
I have even tried to convert the app to old appcompat 27.1.1, that is used in your sample and still get the same freeze!

**Comment by androideveloper** [comment]
Here is update including your demo [Updated Demo](https://www.dropbox.com/s/vqzhwv10trrjwws/MapboxDialogCrashDemo_updated.zip?dl=0)
