### ISSUE TITLE
ESRI Vector Tile Package support

### ISSUE THREAD

**Issue by ac87** [mapbox/mapbox-gl-native#14024]
I'm investigating whether ESRI .VTPK are actually inter-operable with the Mapbox SDK specifically Android for now.

There is a sample VTPK from ESRI here: https://www.arcgis.com/home/item.html?id=d9f8ce6f6ac84b90a665a861d71a5d0a

For anyone not familiar, a .VTPK is a zip file containing a [CompactCache V2](https://github.com/Esri/raster-tiles-compactcache), the compact cache normally has raster tiles but now has GZipped MVTs.  

The problem ESRI seem to drop 'version' from their MVTs (or they are using an older spec?) so when the tile is passed to SDK 7.1.0 this is what appears in the logcat.

E/Mbgl: {GLThread 1058}[Style]: Failed to load tile 0/0/0=>0 for source esri: missing required field: version

Is there a way to force the SDK to ignore this, is it an older version or have ERSI intentionally made this incompatible?

Running the tile through [this decoder](https://github.com/wdtinc/mapbox-vector-tile-java) results in similar errors, but from this I can see the output at least, for example.

```
layers {
  name: "City small scale"
  features {
    tags: 0
    tags: 0
    tags: 1
    tags: 0
    tags: 2
    tags: 1
    type: POINT
    geometry: 9
    geometry: 6246598
    geometry: 20037258
  }
  keys: "_symbol"
  keys: "_label_class"
  keys: "_name"
  values {
    int_value: 0
  }
  values {
    string_value: "Los Angeles"
  }
  extent: 8388608
}
```

**Comment by tobrun** [comment]
@ac87 I'm not familiar with ESRI. The SDKs found in this repository comply to the [Mapbox Vector Tile Spec](https://github.com/mapbox/vector-tile-spec). The warning you are seeing is expected as this is required as part of the former mentioned specification. Their is not much I can add to this issue, closing as not actionable.

**Comment by ac87** [comment]
I figured as much, just making sure I didn't miss something obvious. Thanks.
