### ISSUE TITLE
Android studio's emulator is not working error is given below...

### ISSUE THREAD

**Issue by murtuzakhalid** [mapbox/mapbox-gl-native#1402]
my android's studio emulator is not working....because I have core i5 first generation don't have visualization technology...thats why Intel hexm is not installing...tell me alternate way to run my android code please....!

this is the problem is listed below....!
Cannot launch AVD in emulator.
Output:
emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure Intel HAXM is properly installed and usable.
CPU acceleration status: HAX kernel module is not installed!

**Comment by ljbade** [comment]
This is likely a bug in the Android simulator not Mapbox GL.
