### ISSUE TITLE
GeometryConstants MIN_LONGITUDE and MAX_LONGITUDE are incorrect

### ISSUE THREAD

**Issue by ekigamba** [mapbox/mapbox-gl-native#14033]
### Expected

Some values something close to https://github.com/mapbox/mapbox-gl-native/wiki/Android-6.x-to-7.x-migration-guide#new-latlng--latlngbounds-wrapping

### Actual

The min longitude is `-Double.MAX_VALUE` and max longitude is `Double.MAX_VALUE` accessible here https://github.com/mapbox/mapbox-gl-native/blob/05026b704adcbe97c923989b3e2e46feb4fdc7ee/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/GeometryConstants.java#L27 and https://github.com/mapbox/mapbox-gl-native/blob/05026b704adcbe97c923989b3e2e46feb4fdc7ee/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/GeometryConstants.java#L32

### Configuration

**Mapbox SDK versions:** 7.2.0

Are the values correct?

**Comment by tobrun** [comment]
We are no longer wrapping LatLng values, so you are allowed to provide values lower/above -180 and 180. This can be usefull if you want to make a distinction between a bounds that crosses the IDL vs a bounds that doesn't.
