### ISSUE TITLE
iconAllowOverlap for few features only

### ISSUE THREAD

**Issue by Hassan-Fa** [mapbox/mapbox-gl-native#14038]
Hi there
is it possible to use iconAllowOverLap  only for a few set of features ?
like this feature is bookmarked and should be shown over others (other near features being hidden is more preferable but is that possible too)?

 like this : PropertyFactory.iconAllowOverlap(Expression.get("bookmarked"))

**Mapbox SDK version : latest (7.0.1?)**

**Comment by tobrun** [comment]
@Hassan-Fa capturing from our style spec definition that this isn't supported yet. 
For this to work we would need data driven support for that property.

More info [here](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-icon-allow-overlap), and our latest SDK version is 7.2.0 ;)

**Comment by Hassan-Fa** [comment]
@tobrun 
:) thanks
is it doable someHow ? prefered features?
and is it gonna be in any future releases ? data driven support for overlap?

**Comment by tobrun** [comment]
you could split up your data into two layers and use filters to show the specific symbols. One layer would have iconAllowOverlap on while the other would have it off. No immediate timeline on supporting this as a data driven property afaik.

**Comment by Hassan-Fa** [comment]
will give it a try
thanks
