### ISSUE TITLE
Use C++14 features / require gcc 4.9

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1403]
We've encountered several situations where we want to use C++14's [generalized lambda capture](https://isocpp.org/files/papers/N3648.html).

This is supported in [gcc 4.9](https://gcc.gnu.org/projects/cxx1y.html) and [clang 3.4](http://clang.llvm.org/cxx_status.html) (which we already require).

@springmeyer Do you forsee any issues requiring gcc 4.9 rather than 4.8?

**Comment by jfirebaugh** [comment]
Notes from a previous effort to switch to gcc 4.9: https://github.com/mapbox/mapbox-gl-native/pull/1250#issuecomment-91736051

**Comment by jfirebaugh** [comment]
Looking good [here](https://travis-ci.org/mapbox/mapbox-gl-native/builds/60976055).

Blocker seems to be getting a more recent compiler for the android builds:

https://travis-ci.org/mapbox/mapbox-gl-native/builds/60976494

**Comment by springmeyer** [comment]
> @springmeyer Do you forsee any issues requiring gcc 4.9 rather than 4.8?

No. Although it would be interesting to test on ubuntu trusty with the stock 4.9 that comes there - would be nice if that worked and users of at Ubuntu Trusty would not need to upgrade their compiler to get mbgl to build.

**Comment by kkaefer** [comment]
Android builds should use clang 3.5 IIRC.

**Comment by tmpsantos** [comment]
I would be very cautious about this. Apparently we want to support windows, no?

Check this why C++11 is not fully supported by Chromium (C++14 is not even considered):
https://chromium-cpp.appspot.com/

/cc @BergWerkGIS

**Comment by jfirebaugh** [comment]
Summarizing from scrum:

* We don't currently build on Windows and don't forsee doing so in the near future.
* In addition to potential C++11/14 issues, we'd need to port GL code or use [ANGLE](https://code.google.com/p/angleproject/).
* Support for the C++14 feature we need is in VS 2015 Preview, so may be generally available by the time we potentially want to support Windows.

Seems like we have consensus to start adopting C++14 features that have widespread compiler support as needed. I'm going to start with the feature required for #1309. Post-Beta we can look at using `std::make_unique` and any other things we have polyfilled.

**Comment by jfirebaugh** [comment]
Done as part of #1412.
