### ISSUE TITLE
Introduce clusterProperties option for aggregated cluster properties

### ISSUE THREAD

**Issue by pozdnyakov** [mapbox/mapbox-gl-native#14043]
Port of https://github.com/mapbox/mapbox-gl-js/pull/7584

**Comment by samiede** [comment]
What's the status of the cluster icon property? :) Would love to use it in our app!

**Comment by mourner** [comment]
@samiede it's halfway there! The implementation on Supercluster side is done https://github.com/mapbox/supercluster.hpp/pull/24, now it needs SDK bindings.

**Comment by zmiao** [comment]
The implementation for gl-native and android is under review. https://github.com/mapbox/mapbox-gl-native/pull/15287
