### ISSUE TITLE
Map turns black on resume

### ISSUE THREAD

**Issue by akaciassa** [mapbox/mapbox-gl-native#14042]
Hello, 
I am facing an issue when implementing MapBox on Android. 
Actually, When I start the map activity, the map loads normally, I add some layers and symbols everything works fine. 
the issue starts when I start another activity on result or lock my phone's screen when I resume my map activity, I can see the map turning black and nothing is shown, it doesn't keep my displayed layers and markers. 
I  tried to use all the lifecycle methods onPause, onDestroy, onResume, onLowMemory, onSaveInstance... 
nothing worked. 
I check the implementation of onResume but all I find is a comment saying: implement if needed. 

![screenshot_20190306_100505_com capgemini cres smartoffice](https://user-images.githubusercontent.com/48277039/53869848-519a8b00-3ff9-11e9-9353-7e4ec00e2ceb.jpg)

### Configuration

**Android versions: 7.0.0  8.0.0 8.0.1 9.0.0 
**Device models: Huawei P20 and many others
**Mapbox SDK versions: 6.8.1

**Comment by tobrun** [comment]
@akaciassa thank you for reaching out and using our products. Could you provide a minimal reproducible example? we haven't heard about other users facing this issue so I'm thinking this is related to your code/setup specifically.

**Comment by akaciassa** [comment]
Hello, thank you for your answer, of course. 
I have an activity where I need to display different layers and symbols. 
here is what I get after creating the map, everything is displayed properly.

![screenshot_20190306_100500_com capgemini cres smartoffice](https://user-images.githubusercontent.com/48277039/53876031-35e9b180-4006-11e9-8f86-3ba9893d36eb.jpg)

and I am using a token propery : 

```
Mapbox.getInstance(getApplicationContext(),Utility.getMapboxToken(getApplicationContext()));
        mapView.getMapAsync(mapboxMap -> {

            mapboxMap.getUiSettings().setAttributionEnabled(false);
            mapboxMap.getUiSettings().setLogoEnabled(false);
            mapboxMap.setCameraPosition(new CameraPosition.Builder()
                    .target(center) //Map center point
                    .zoom(ZOOM) //Zoom in map
                    .build()
            );

            map = mapboxMap;
            map.setMaxZoomPreference(MAX_ZOOM);
            map.setMinZoomPreference(MIN_ZOOM);
            //add all pois types icons and sources
            prepareMapIconsAndSources();

            //Add map created listener
            this.mcListener = mcListener;
            mcListener.onMapCreated();

            //Add clicked poi layer
            prepareClickedLayer();

            //Set on poi click listener
            map.addOnMapClickListener(this);
        });
```

and then on my life cycle calls I have : 
```
@Override
    protected void onStop() {
        mapView.onStop();
        super.onStop();

    }
    @Override
    protected void onDestroy() {
        mapView.onDestroy();
        super.onDestroy();
    }

  protected void onResume() {
        mapView.onResume();
        intFloorRv();
        super.onResume();
    }

    @Override
    public void onLowMemory() {
        mapView.onLowMemory();
        super.onLowMemory();
    }

    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mapView.onSaveInstanceState(outState);
    }
```

If I lock my screen on this activity, then unlock, the data will appear for one second that a black screen appears like the first image I added.

**Comment by tobrun** [comment]
@akaciassa I'm not seeing any onStart() or onPause(). Could you add that and test again?

**Comment by akaciassa** [comment]
@tobrun thank you for your answer, actually, I added all the lifecycle methods except the onStart and the problem was here :) thanks a lot
