### ISSUE TITLE
Possible to set zoom beyond maximum limit

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#1405]
When setting the zoom level programmatically, `Transform::setLatLngZoom` and the subsequent `Transform::_setScaleXY` do not check if the zoom level is sane.

In iOS, it's possible to set `mapView.zoomLevel = 21.f` and it will render the map, even though the maximum zoom level via gestures is `z18`. Values higher than `21.9f` break rendering but are settable. Using a zoom gesture will pop the map back to `z18`.

Here is one solution that works, but I get the feeling that `Transform::_setScaleXY` is the right place to do this, not `Transform::setLatLng`:

```diff
diff --git a/src/mbgl/map/transform.cpp b/src/mbgl/map/transform.cpp
index 6c0f136..95448a7 100644
--- a/src/mbgl/map/transform.cpp
+++ b/src/mbgl/map/transform.cpp
@@ -118,7 +118,7 @@ void Transform::setLatLng(const LatLng latLng, const Duration duration) {
 void Transform::setLatLngZoom(const LatLng latLng, const double zoom, const Duration duration) {
     std::lock_guard<std::recursive_mutex> lock(mtx);
 
-    double new_scale = std::pow(2.0, zoom);
+    double new_scale = std::pow(2.0, std::fmin(std::fmax(zoom, getMinZoom()), getMaxZoom()));
 
     const double s = new_scale * util::tileSize;
     current.Bc = s / 360;
```

/cc @kkaefer

**Comment by friedbunny** [comment]
Let's link this thread up with the ability to customize the max zoom, #509.

**Comment by 1ec5** [comment]
This is now addressed by copious use of `TransformState::constrain()`.
