### ISSUE TITLE
Following the First steps with the Mapbox Maps SDK for React Native app crash, not starting at all.

### ISSUE THREAD

**Issue by jehielmartinez** [mapbox/mapbox-gl-native#14053]
### Steps to reproduce

 1. Follow steps in guide 
 2. run react-native run-android
 3. compile, build..

### Expected behavior

See the map rendered 

### Actual behavior

App crash

### Configuration

**Android versions:** 7.0
**Device models:** HONOR 6X
**Mapbox SDK versions:** 6.1.3

**Comment by friedbunny** [comment]
Please see the [`react-native-mapbox-gl`](https://github.com/mapbox/react-native-mapbox-gl/) repository for how to get started with that project — thanks!
