### ISSUE TITLE
[ios] Replace ornament margin assert with NSException (follow on to #13911)

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#14065]
Follow-on to PR https://github.com/mapbox/mapbox-gl-native/pull/13911

Rather than asserting 

> `NSAssert(CGRectContainsPoint(self.bounds, scaleBarOffset)`

(e.g. https://github.com/mapbox/mapbox-gl-native/pull/13911/files#diff-20502b6bc02986a4398d0da84b2d4b94R827)

we should:

- [ ] Raise an `NSInvalidArgumentException`. 

    We typically use `NSException`s when alerting the developer of programmer error; in our release SDK, asserts will be "compiled out" (so will be a no-op). Asserts are useful for those developing the SDK itself.

- [ ] As discussed, the margin (offset) is a vector quantity, not a point. Given that the margin is an inset from `mgl_safeTopAnchor` (and related anchors), it's possible to have a valid margin but the assert to fire. This check needs to take the anchors into consideration.

/cc @lloydsheng @friedbunny

**Comment by lloydsheng** [comment]
@julianrex The purpose of those asserts is making sure ornaments in proper positions. Seems `layoutSubviews` is a good position to guard that. Here is my attempt https://github.com/mapbox/mapbox-gl-native/pull/14373. Looking forward to your suggestions. 😊  cc: @chriswu42
