### ISSUE TITLE
Use Maki icons as SDF icons

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#14077]
I believe this used to work but not 100% sure:

I think we were able to use [maki](https://labs.mapbox.com/maki-icons/) icons as a symbol icon and use it as a SDF image. This enables the user to use icon-color and all icon-halo related runtime configurations on symbol layer. At the moment this doesn't seem to be true as setting those properties doesn't do anything visually.

Below image was configured as:

```
        iconImage("bus-15"),
        iconColor(Color.RED),
        iconHaloWidth(6.0f),
        iconHaloBlur(1.0f),
        iconHaloColor(Color.BLACK),
```

But visually I'm seeing:

![image](https://user-images.githubusercontent.com/2151639/54117566-64460300-43f1-11e9-8846-326e2b0af16d.png)

cc @samanpwbb @mapbox/gl-core

**Comment by kkaefer** [comment]
This should still work if you generate a SDF version of the Maki icons, e.g. with https://github.com/mapbox/fontnik, it's C++ equivalent, or https://github.com/mapbox/tiny-sdf

**Comment by tobrun** [comment]
I think my confusion comes from the old sprite sheet having maki icons that could be treated as SDF when referenced as `get("bus-15")`, while current doesn't allow this anymore:

![image](https://user-images.githubusercontent.com/2151639/54265183-04786500-4575-11e9-9136-508b24e2f1cb.png)


Not actionable, closing.
