### ISSUE TITLE
icon-halo style property breaks a high values

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#14075]
icon-halo-width property seems to be broken when providing large values:

Without:
![image](https://user-images.githubusercontent.com/2151639/54116490-31027480-43ef-11e9-9bd8-abc9415c9c5b.png)

With a working configuration:
```java
        iconHaloWidth(4.0f),
        iconHaloBlur(1.0f),
        iconHaloColor(Color.BLACK),
```
![image](https://user-images.githubusercontent.com/2151639/54116522-3e1f6380-43ef-11e9-9546-1dacb4954dc8.png)

With a broken configuration:
```java
        iconHaloWidth(6.0f),
        iconHaloBlur(1.0f),
        iconHaloColor(Color.BLACK),
```
![image](https://user-images.githubusercontent.com/2151639/54116557-4ecfd980-43ef-11e9-8144-cb25ee2606ab.png)

cc @mapbox/gl-core

**Comment by kkaefer** [comment]
This behavior is intentional. See  https://github.com/mapbox/mapbox-gl-js/pull/7441#issuecomment-431162455 for an explanation.

**Comment by chloekraw** [comment]
Is it worth adding a comment or other documentation that for most icon sizes and fontScale values, `iconHaloWidth` values should be kept under 6.0 for a halo, and that values greater will create a different boxed effect around the feature?
