### ISSUE TITLE
Highway shield overlap

### ISSUE THREAD

**Issue by tatsvc** [mapbox/mapbox-gl-native#1409]
When playing around in sirius I noticed this highway shield overlap in DC. It's not happening on GL js. 

![image](https://cloud.githubusercontent.com/assets/2894119/7457130/246ed11a-f258-11e4-9396-2bda90a28fe0.png)

**Comment by mb12** [comment]
Are the overlapping symbols on the tile boundary?   Collision detection is not done across tiles. I've seen such overlaps for street names as well (on the tile boundary).

**Comment by ansis** [comment]
this should be fixed by https://github.com/mapbox/mapbox-gl-native/pull/1666 and https://github.com/mapbox/mapbox-gl-native/pull/1840
