### ISSUE TITLE
i want zoomlevel upto 13 to annotation when map is shown offline

### ISSUE THREAD

**Issue by RahulGusain** [mapbox/mapbox-gl-native#14097]

**Comment by tobrun** [comment]
Capturing from issue template:

Hello and thanks for contributing to the Mapbox Maps SDK for Android! To help us diagnose your problem quickly, please:

 - Include a minimal demonstration of the bug, including code, logs, and screenshots.
 - Ensure you can reproduce the bug using the latest release.
 - Only post to report a bug or request a feature; direct all other questions to: https://stackoverflow.com/questions/tagged/mapbox
