### ISSUE TITLE
Offline sideloading with Mapbox

### ISSUE THREAD

**Issue by amitbaz** [mapbox/mapbox-gl-native#14096]
### Steps to reproduce

 1. Create an android studio project with mapbox-android-sdk:7.1.1.
 2. Successfully show an online map from my own tile server.
 3. Create myfile.db file from my own tile server with mbgl-offline command.
 4. Following Offline sideloading example with my own tile server.

### Expected behavior
Being able to see the map i saved in generated db file in an offline mode.

i want my app to be completely disconnected from the network. I don't want it to be connected to the internet, then downloading the region, then show the offline region when there's no network access.
The app shouldn't be connected to the internet no matter what.
Therefore I thought of using the Offline sideloading.

### Actual behavior

Seen nothing. just empty screen.

### Configuration

So I'm trying to use the Mapbox SDK in an offline mode by merging tiles in a local DB file I created from my own tile server by using 

    ./mbgl-offline --north [north coordinate] --west [west coordinate] --south [south coordinate] --east [east coordinate] --minZoom [minimum zoom] --maxZoom [maximum zoom] --output [output file path] --style [style URL] --token [mapbox token]

command from the mapbox-gl-native library.

I put the file in the /path/to/file/files directory and I implemented the merging code as shown in the example : [merge offline tiles example][1]

When I open the app I get a toast says the merging went successfully but I can't see the map. all I see is a blank surface with the background color of my map style.

As shown in the example, I make sure the app is not connected to the internet and then I merge the DB file before I load the style: 

        protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

    // Mapbox access token is configured here. This needs to be called      either in your application
    // object or in the same activity which contains the map view.
        Mapbox.getInstance(this, getString(R.string.access_token));

    // This contains the MapView in XML and needs to be called after the access token is configured.
        setContentView(R.layout.activity_main);

        mapView = findViewById(R.id.mapView);
        mapView.onCreate(savedInstanceState);

        Mapbox.setConnected(false);
        mergeDb();
        mapView.getMapAsync(this);
    }

    @Override
    public void onMapReady(@NonNull final MapboxMap mapboxMap) {
        MainActivity.this.mapboxMap = mapboxMap;

        mapboxMap.setStyle( new Style.Builder().fromUrl("http://<my_server_ip>/styles/klokantech-basic/style.json")
          , new Style.OnStyleLoaded() {
              @Override
              public void onStyleLoaded(@NonNull Style style) {

    //                  enableLocationComponent(style);

              }
          });
    }

**My mergeDb function:**

        private void mergeDb(){
        System.out.println(FileSource.getResourcesCachePath(this));
        OfflineManager.getInstance(this).mergeOfflineRegions(FileSource.getResourcesCachePath(this) + "/myfile.db", new OfflineManager.MergeOfflineRegionsCallback() {
            @Override
            public void onMerge(OfflineRegion[] offlineRegions) {
                mapView.getMapAsync(new OnMapReadyCallback() {
                    @Override
                    public void onMapReady(@NonNull MapboxMap mapboxMap) {
                        mapboxMap.setStyle(new Style.Builder().fromUrl("http://<my_server_ip>/styles/klokantech-basic/style.json"));

                    }
                });

                Toast.makeText(
                  MainActivity.this,
                  String.format("Merged %d regions.", offlineRegions.length),
                  Toast.LENGTH_LONG).show();
            }

            @Override
            public void onError(String error) {

                Toast.makeText(
                  MainActivity.this,
                String.format("Offline DB merge error." ),
                  Toast.LENGTH_LONG).show();
                System.out.println(error);

            }
        });
    }

Any idea what could be the problem?

  [1]: https://github.com/mapbox/mapbox-gl-native/blob/android-v7.2.0/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/offline/MergeOfflineRegionsActivity.kt

**Android versions:** 9
**Device models:** Huawei mate 10 pro
**Mapbox SDK versions:** 7.1.1

**Comment by LukasPaczos** [comment]
Hey @amitbaz, could you confirm that you're following steps from https://docs.mapbox.com/android/maps/overview/offline/#cli-build-instructions, especially number 3:
> Checkout the release commit equivalent to the version of the Maps SDK that you are using: git checkout {commit hash} (view all release commits)

Thanks!

**Comment by tobrun** [comment]
@amitbaz one additional comment to make is that you need to initialize your map with a camera position matching your offline region. With above and this pointer, you should be able to get it to work. Closing as answered.
