### ISSUE TITLE
Freeze when onPause

### ISSUE THREAD

**Issue by psinetron** [mapbox/mapbox-gl-native#14103]
After migration from 6 to 7 version i have freeze when start other activities.
When start new activity call onPause and all application freezed

**Comment by tmpsantos** [comment]
Hi @psinetron, can you elaborate a bit more what is this issue about?

**Comment by psinetron** [comment]
For a long time I could not understand what the problem was.
Problem at this xml code:
```
<com.mapbox.mapboxsdk.maps.MapView
                android:id="@+id/mapView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                mapbox:mapbox_cameraTargetLat="59.9238667"
                mapbox:mapbox_cameraTargetLng="30.3350637"
                mapbox:mapbox_cameraZoom="11"
                mapbox:mapbox_enableTilePrefetch="true"
                mapbox:mapbox_enableZMediaOverlay="true"
                mapbox:mapbox_renderTextureMode="true"
                mapbox:mapbox_uiTiltGestures="true" />
```

**mapbox:mapbox_renderTextureMode="true"**

**Comment by tobrun** [comment]
could you add some device specifics to the ticket?  and which version of 7 used

**Comment by psinetron** [comment]
com.mapbox.mapboxsdk:mapbox-android-sdk:7.2.0

Android 6.0 Redmi note 4

**Comment by tobrun** [comment]
currently not able to reproduce on a couple of different devices with different OS versions. Can you show some code how you are settings up everything in java/kotlin?

**Comment by madridista89** [comment]
I am facing the same issue with Android 6.0.1 when trying to start other activities.
To avoid getting ANR, I was forced to remove mapbox:mapbox_renderTextureMode="true" but I have other side effect if I remove it.

**Comment by tobrun** [comment]
Tackling this issue in https://github.com/mapbox/mapbox-gl-native/pull/14127

**Comment by madridista89** [comment]
> Tackling this issue in #14127

Thanks.

**Comment by tobrun** [comment]
closed with https://github.com/mapbox/mapbox-gl-native/pull/14127
