### ISSUE TITLE
Rendering problems with hillshading layer on Samsung Galaxy J3 2016 (SM-J320F)

### ISSUE THREAD

**Issue by arnekaiser** [mapbox/mapbox-gl-native#14100]
### Steps to reproduce

 1. Open official "Mapbox Demo" app on Samsung Galaxy J3
 2. Open hillshading demo

### Expected behavior
![image](https://user-images.githubusercontent.com/5116350/54282944-58973f80-459d-11e9-8b67-ba0a4ed4c0e6.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/5116350/54282998-7664a480-459d-11e9-8055-296f3e2168cc.png)
![image](https://user-images.githubusercontent.com/5116350/54283042-87adb100-459d-11e9-9503-aead7d3cda35.png)
![image](https://user-images.githubusercontent.com/5116350/54283071-9300dc80-459d-11e9-8869-3f797865deff.png)

### Configuration
![image](https://user-images.githubusercontent.com/5116350/54283117-a613ac80-459d-11e9-9a57-eebf560e153d.png)

**Android versions:** 5.1.1
**Device models:** Samsung Galaxy J3 2016 (SM-J320F) 
**Mapbox SDK versions:** at least 7.1.2 & 7.2.0

**Comment by tobrun** [comment]
Is anything printed to the log when this occurs?

**Comment by arnekaiser** [comment]
> Is anything printed to the log when this occurs?

Nothing special:

> 03-14 17:02:10.054 9833-9833/? V/Mbgl-ConnectivityReceiver: connected - true
03-14 17:02:10.104 9833-9898/? I/Mbgl-EGLConfigChooser: In emulator: false
03-14 17:02:10.114 9833-9898/? I/Mbgl: {GLThread 1428}[General]: GPU Identifier: Mali-400 MP
03-14 17:02:10.124 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.debug.14631874.pbf
03-14 17:02:10.124 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.clipping_mask.14631874.pbf
03-14 17:02:10.564 9833-9906/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:10.744 9833-9906/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:10.854 9833-9914/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:10.894 9833-9915/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:10.934 9833-9906/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:11.085 9833-9913/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:11.265 9833-9915/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:11.976 9833-9916/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:12.026 9833-9917/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:12.146 9833-9918/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:12.376 9833-9913/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:12.396 9833-9919/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:12.426 9833-9906/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:13.247 9833-9920/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:13.307 9833-9922/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:13.357 9833-9921/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:13.417 9833-9923/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:20.143 9833-9927/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:20.194 9833-9928/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:20.214 9833-9926/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:21.195 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.hillshade.14631874.pbf
03-14 17:02:21.215 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.hillshade_prepare.14631874.pbf
03-14 17:02:21.645 9833-9924/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:22.025 9833-9925/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
03-14 17:02:22.966 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.fill.712f57cd.pbf
03-14 17:02:22.976 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.fill.4518d479.pbf
03-14 17:02:23.006 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.fill_outline.712f57cd.pbf
03-14 17:02:23.016 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.fill.526fe058.pbf
03-14 17:02:23.036 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.fill_outline.526fe058.pbf
03-14 17:02:23.086 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.fill_pattern.712f57cd.pbf
03-14 17:02:23.106 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.fill_outline_pattern.712f57cd.pbf
03-14 17:02:23.146 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.line.a90ab3e8.pbf
03-14 17:02:23.166 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.line.23a61e98.pbf
03-14 17:02:23.216 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.line.aff52bcb.pbf
03-14 17:02:23.237 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.line_sdf.23a61e98.pbf
03-14 17:02:23.257 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.collision_box.14631874.pbf
03-14 17:02:23.267 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.collision_circle.14631874.pbf
03-14 17:02:23.287 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.symbol_icon.5518847d.pbf
03-14 17:02:23.317 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.symbol_sdf.5bec7c94.pbf
03-14 17:02:23.337 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.symbol_icon.edcdf8d0.pbf
03-14 17:02:23.367 9833-9898/? W/Mbgl: {GLThread 1428}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxandroiddemo/cache/com.mapbox.gl.shader.symbol_sdf.5518847d.pbf

**Comment by arnekaiser** [comment]
This problem also appears on the following devices:

- Huawei Y330, Android 4.2.2
- Samsung Galaxy Note 10.1, Android 4.4.2

All of the devices have a low density value (<= 2.0). Maybe this could be the problem?
