### ISSUE TITLE
Offline downloaded region is shown but after multiple use it got disaapear.

### ISSUE THREAD

**Issue by RahulGusain** [mapbox/mapbox-gl-native#14116]
hello, I am facing an issue, that offline map is downloading and showing perfectly but as I use my app multiple time, after some period of time offline region is no more longer there, I don't know why also I have checked that my downloaded region is neither updating or something else.

**Comment by LukasPaczos** [comment]
Hey @RahulGusain, capturing from the issue template:
```
 - Include a minimal demonstration of the bug, including code, logs, and screenshots.
 - Ensure you can reproduce the bug using the latest release.
 - Only post to report a bug or request a feature; direct all other questions to: https://stackoverflow.com/questions/tagged/mapbox

### Configuration

**Android versions:** 
**Device models:** 
**Mapbox SDK versions:** 
```

Please provide the necessary information, otherwise, this isn't actionable for us.
Closing for now, happy to reopen with the updated report.
