### ISSUE TITLE
InvalidLatLngBoundsException - Cannot create a LatLngBounds from 1 items

### ISSUE THREAD

**Issue by androideveloper** [mapbox/mapbox-gl-native#14113]
Creating LatLngBounds with 1 point throws an exception. I have found similar issue here and as I can see author hasn't provided real use case https://github.com/mapbox/mapbox-gl-native/issues/9953 . Our use case is showing a bunch of locations on the map. Cause we don't know how many points will be fetched, "1 point" and "many points" cases are the same for us. I know that we can check and handle 1 point and many points differently, but why if they are the same? Google Maps handles these cases as mentioned.

### Configuration

**Android versions:** 9
**Device models:** Xiaomi Mi a2 lite
**Mapbox SDK versions:** 7.2.0

**Comment by tobrun** [comment]
That exception was added on purpose. We don't consider a single point a bounds atm in the Android binding. This is something we might reconsider with a larger future refactor. For the time being, closing this as a work as designed.

**Comment by androideveloper** [comment]
Ok. I think it is still the same as many points. If you put 2 points on the same location and bounds are calculated, then 1 point case should work the same way. Anyway, we would check 1 point case on our side.
