### ISSUE TITLE
Clear up layerBelow option docs. Expose layerAbove for LocationComponent.

### ISSUE THREAD

**Issue by dsuresh-ap** [mapbox/mapbox-gl-native#14120]
Setting the layer below doesn't result in the location component being above the specified layer. 

### Steps to reproduce

 1. Activate the location component
 2. When style is loaded add layers to map
 3. Apply `LocationComponentOptions` to component

### Expected behavior

LocationComponent is supposed to be above PinLayer

### Actual behavior

LocationComponenet is below PinLayer

```
 mapBoxMapView.addOnDidFinishLoadingStyleListener {
                Logger.d("Style loaded")
                addLayersIfNeeded()
            }

private fun addLayersIfNeeded() {
        pinLayer.addLayerToMapBox(mapboxMap)
        perimeterLayer.addLayerToMapBox(mapboxMap)
        lineLayer.addLayerToMapBox(mapboxMap)
        rectangleLayer.addLayerToMapBox(mapboxMap)
        circleLayer.addLayerToMapBox(mapboxMap)

        mapboxMap?.locationComponent?.let {
            val context = activity!!
            val options = LocationComponentOptions.builder(context)
                .foregroundTintColor(ContextCompat.getColor(context, R.color.light_blue))
                .foregroundStaleTintColor(ContextCompat.getColor(context, R.color.light_blue))
                .enableStaleState(false)
                .layerBelow(PinLayer.LAYER_ID)
                .build()

            it.applyStyle(options)
        }
    }

// Happens on `onStyleLoaded`
@SuppressLint("MissingPermission")
    private fun activateLocationComponent() {
        val context = activity!!

        mapboxMap?.locationComponent?.let {
            it.activateLocationComponent(context, mapboxMap?.style!!)
            it.isLocationComponentEnabled = true
            it.renderMode = RenderMode.COMPASS
        }
    }
```

![image](https://user-images.githubusercontent.com/21132682/54370080-66a49900-464d-11e9-80fc-05e19795ad8c.png)

### Configuration

**Android versions:** 
**Device models:** 
**Mapbox SDK versions:7.2.0**

**Comment by dsuresh-ap** [comment]
The explanation for `addLayerBelow` and `addLayerAbove` is confusing.
From my understanding `addLayerAbove` adds the `layer` above the layer id specified. However the param description is not clear. `@param above the layer id to add this layer above` Same for `addLayerBelow`.

The LocationComponentOption option for `layerBelow` `Sets the layer id to set the location component below to.` sounds like the locationcomponent will be added below the layer id specified. If that is the case is there a way to add the LocationComponent above a layer? We want the user location to be above a SymbolLayer.

**Comment by LukasPaczos** [comment]
Hey @dsuresh-ap, it seems like the docs are unclear and we need to fix them up. The `LocationComponentOptions#layerBelow` places the component _under_ the linked layer. To the puck  _above_, you'll most likely need to introduce an invisible layer, then place the pins layer _below_ the invisible one, and only then activate the component with again with the invisible layer as the `#layerBelow` option.

So I understand that there are 2 tasks here:
- clear up the `LocationComponentOptions#layerBelow` option's docs
- introduce `LocationComponentOptions#layerAbove`

Does that sound right?

**Comment by dsuresh-ap** [comment]
Hey @LukasPaczos,

Yes that sounds about right. Having `layerAbove` would be a great feature. We will use your advice and place an invisible layer in the mean time. Thanks!
