### ISSUE TITLE
public access to `LocationComponentConstants` layer ids

### ISSUE THREAD

**Issue by ulusoyca** [mapbox/mapbox-gl-native#14129]
I am using [mapbox annotation plugin ](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-annotation) and specifically [LineManager](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-annotation/src/main/java/com/mapbox/mapboxsdk/plugins/annotation/LineManager.java). 

By default, when I add a line to the map, it is positioned on top of location icon (mapbox-location-layer). In order to position the line under the location icon, I need to provide [`belowLayerId`](https://docs.mapbox.com/android/api/plugins/annotation/0.5.0/com/mapbox/mapboxsdk/plugins/annotation/LineManager.html#LineManager-MapView-MapboxMap-Style-java.lang.String-) as parameter to `LineManager` construction method.

It works when I copy paste the string [`LocationComponentConstants#BACKGROUND_LAYER`
](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentConstants.java#L54). However, it is not public API. How can I access that layer using public Mapbox API method?

**Comment by cmahopper** [comment]
@LukasPaczos Sorry if I'm misunderstanding something, but how do I retrieve the BACKGROUND_LAYER string if the class is not public?

**Comment by LukasPaczos** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/14333, thanks for catching that @cmahopper!
