### ISSUE TITLE
styleimageneeded port of gl-js

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#14124]
GL-native port of https://github.com/mapbox/mapbox-gl-js/pull/7987:

> The event gets fired when a layer needs an image that the map doesn't have. The developer has a chance to listen for this event and add an image within the callback in order to have it included. This event can be used to dynamically generate icons based on feature properties.

**Comment by chloekraw** [comment]
Closed in https://github.com/mapbox/mapbox-gl-native/pull/14253 by @ansis 

However, noting that on -js and -native we still need to add eviction support
