### ISSUE TITLE
Color getter inconsistency

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#14130]
Every color passed to core has to have R, B and G values in the range of `0-255` to be compliant with [the spec](https://docs.mapbox.com/mapbox-gl-js/style-spec/#types-color), however, when getting those values back they are returned in the range of `0.0-1.0`. This is because that's how they're stored in the [`color.hpp`](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/util/color.hpp) after the [`android -> core`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/src/conversion/color.cpp) conversion and returned in the same form during the [`core -> android`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/src/conversion/constant.cpp#L27-L40) conversion.

How's @mapbox/maps-ios handling this case?

/cc @tobrun @ivovandongen

**Comment by fabian-guerra** [comment]
@LukasPaczos I think is the same as Android, the values within iOS are stored as ranges of rgb `0.0-1.0`. Only when we send them back to GL we convert them to `0-255` ranges.

**Comment by LukasPaczos** [comment]
I see, thanks @fabian-guerra.

In this case, I think we should fix this up on Android, because right now we require users to pass, for example, `rbg(255, 0, 0, 1)` color string to the core and when fetched back, they'll receive `rbg(1, 0, 0, 1)`. The color string conversion from core to Android should expand the value back to `0-255` range.

**Comment by zugaldia** [comment]
> The color string conversion from core to Android should expand the value back to 0-255 range.

Makes sense to me. To clarify, iOS is already doing this, or do we need a separate ticket for iOS?

**Comment by fabian-guerra** [comment]
@LukasPaczos on iOS (unlike Android) our users don't interact with rbg values in the range of `0-255` we extended a class called [`UIColor`](https://developer.apple.com/documentation/uikit/uicolor?language=objc) that uses rgba in the range of `0-1.0` so it's not actually a problem for us (it's already defined that way in the platform). I would hesitate to support a different color range for the previous reason.

cc @zugaldia

**Comment by chloekraw** [comment]
Thanks @fabian-guerra. I'm assuming there's no UIKit equivalent that accepts values in the range of `0-255`? 😛 It does feel a little inefficient to ask for a RBG input in `0-1.0`   ➡️ convert to `0-255` for core   ➡️ convert back to `0-1.0` to return to the user, though I'm not sure what the impact of that is. 

@LukasPaczos @tobrun - is the plan for Android still to change our implementation so that values in the range `0-255` are returned to the user? Thus the Android SDK will accept different values from iOS but no conversion to/from `0-1.0` and `0-255` needs to happen at all.

**Comment by tobrun** [comment]
> is the plan for Android still to change our implementation so that values in the range 0-255 are returned to the user?

Yes, what you set is what you get, the following should always be true:

```java
int color = Color.YELLOW;
foo.setColor(color);
AssertEquals(color, foo.getColor());
```

If we don't apply conversion, above will fail. 


> Thus the Android SDK will accept different values from iOS

Correct, at the OS level. the Android OS has a different way of representing colors as iOS.  
An Android developer will expect us to do comply to the Android OS way, while an iOS developer expects us to comply to the iOS way of handling color.

**Comment by julianrex** [comment]
> It does feel a little inefficient to ask for a RBG input in 0-1.0
This isn't that bad, and I think it's better that the developer uses the `UIColor` class they're used to.
