### ISSUE TITLE
setZoomRate for android?

### ISSUE THREAD

**Issue by Hassan-Fa** [mapbox/mapbox-gl-native#14136]
<b>Hey there!</b>
is it possible to change zoomRate for zooming in/out with two fingers ?
looks like googleMap has lower ZoomRate now and mapView feels more responsive.

**Comment by LukasPaczos** [comment]
Hey @Hassan-Fa, there's no such option as of now. We'll consider this as a feature request and pick-up the work whenever the team has some bandwidth. We're also accepting contributions if you'd like to take a stab at this yourself!

**Comment by noway** [comment]
This is pretty major to us. Our customers report that the map experience is choppy compared to google maps.
