### ISSUE TITLE
Integration of mapbox-events-ios MMENSDateWrapper refactor

### ISSUE THREAD

**Issue by alfwatt** [mapbox/mapbox-gl-native#14147]
Issue tracks changes needed to integrate with changes in `mapbox-events-ios`.

https://github.com/mapbox/mapbox-events-ios/issues/105

### Configuration

mapbox-events-ios - v0.9.1

**Comment by alfwatt** [comment]
Depends on: https://github.com/mapbox/mobile-telemetry/issues/302

**Comment by friedbunny** [comment]
Done in https://github.com/mapbox/mapbox-gl-native/pull/14194.
