### ISSUE TITLE
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x730000000a in tid 2217

### ISSUE THREAD

**Issue by donkii** [mapbox/mapbox-gl-native#14143]
### Steps to reproduce

 1. Create map
 2. Add source and layers
 3. Remove source and layers
 4. Repeat exactly 3 times

### Expected behavior

The map source and layers gets updated

### Actual behavior

Crash occurs always after fourth time I remove layers and source and add them again in order to update the map.

### Configuration

**Android versions: 
    compileSdkVersion 28
    buildToolsVersion '27.0.3'** 
**Device models: All devices/emulators** 
**Mapbox SDK versions: 7.1.2**

**Comment by LukasPaczos** [comment]
Hey @donkii, I created this small demo and wasn't able to reproduce the issue. Could you provide more information, or ideally a minimal reproducible example?

```
mapView.getMapAsync(mapboxMap -> mapboxMap.setStyle(
  new Style.Builder().fromUrl(Style.MAPBOX_STREETS), style -> {
    GeoJsonSource source = new GeoJsonSource("source", Point.fromLngLat(16, 51));
    Layer layer = new CircleLayer("layer", "source")
      .withProperties(PropertyFactory.circleRadius(50f));

    style.addSource(source);
    style.addLayer(layer);

    mapboxMap.addOnMapClickListener(point -> {
      style.removeLayer(layer);
      style.removeSource(source);
      style.addSource(source);
      style.addLayer(layer);
      source.setGeoJson(Point.fromLngLat(point.getLongitude(), point.getLatitude()));
      return false;
    });
  }
));
```

**Comment by donkii** [comment]
I don't know what I did but the problem was resolved, I'll look more into it to see what I've changed

**Comment by LukasPaczos** [comment]
Thanks @donkii! I'll go ahead and close for now but I'm happy to reopen if anything actionable comes up in your testing.

**Comment by ben-j69** [comment]
My user have the same issue : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR) split_config.arm64_v8a.apk

   implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:7.2.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:4.5.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v7:0.5.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.31.0' //0.33.2
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.31.0'
