### ISSUE TITLE
Problems with circle layers

### ISSUE THREAD

**Issue by vientooscuro** [mapbox/mapbox-gl-native#14144]
I'm developing an app using Mapbox and have met a problem with MGLCircleStyleLayer. This problem is also observed in Mapbox for Android (CirclePlayer). The description:
1. Adding a coating of CirclePlayer with 1 point feature on a map
2. Setting a radius of 1000m (calculating meter per pixel at the current latitude for zoom=2 and setting the expression with the calculated values)
3. Scaling the map in such a way that the circle occupies the entire screen
4. Moving the map. At some moment the circle just dissappears though a part of it should be still visible on the screen

I created sample project: https://github.com/vientooscuro/TestMapBox/
Video: https://github.com/vientooscuro/TestMapBox/blob/master/preview.mp4 (~ 21mb)

**Comment by vientooscuro** [comment]
Oops

**Comment by julianrex** [comment]
Still open bot.
