### ISSUE TITLE
Cluster properties map/reduce

### ISSUE THREAD

**Issue by percula** [mapbox/mapbox-gl-native#14142]
In my Android app, I have many `GeoJsonSource`s that are clustered. I would like to use `GeoJsonSource.getClusterExpansionZoom(Feature)` to zoom in after clicking on a cluster. However, there doesn't appear to be a way to find the source that contains the clicked cluster. I have tried adding a `source_id` property to the `GeoJsonSource` features, but those properties do not transfer to clusters. I also tried calling `GeoJsonSource.getClusterLeaves()` and returning if the list was null or empty, however the app will crash with a native error `java.lang.Error: No cluster with the specified id.` that cannot be caught.

**Platform: Android
**Mapbox SDK version: 7.2.0

**Comment by tobrun** [comment]
@percula you are correct that the features returned from a click aren't the same as passed into the source. The supercluster.hpp library from https://github.com/mapbox/supercluster.hpp creates new features to perform the clustering. 

I believe https://github.com/mapbox/supercluster.hpp/issues/9 is tracking what you would need to be unblocked. I'm changing the title to reflect this request and update the label to Core.

cc @tmpsantos @chloekraw

**Comment by tobrun** [comment]
@percula for now you can workaround by setting up your code in a way that you know which layers are associated with which sources. You will have to use multiple queryRenderedFeatures invocations to make that work.

**Comment by percula** [comment]
@tobrun Thanks! Your workaround suggestion came right in time 😄 . 

For anyone else running into this problem, here's what I'm doing. Each cluster layer's id is the source id with "cluster" added as a suffix, which makes finding the source id easy:

```kotlin
val cluster = clusters.first()

// Determine the source that contains the cluster
val source = layerIds.firstOrNull {
    map.queryRenderedFeatures(rectF, Expression.eq(get(CLUSTER), true), it)?.contains(cluster) == true
}
      ?.removeSuffix(CLUSTER)
      ?.let { sourceId -> map.style.sources.find { it.id == sourceId } } as? GeoJsonSource
      ?: return true

breakCluster(cluster, source)
```
