### ISSUE TITLE
Center calculated incorrectly when resetting north with contentInset

### ISSUE THREAD

**Issue by TimWatson** [mapbox/mapbox-gl-native#14150]
With contentInset set with different top and bottom values, if you reset north either by rotating the map or tapping the compass the map jumps either up or down depending on the bigger inset value

Since this only happens when userTrackingMode == .none it led me here
https://github.com/mapbox/mapbox-gl-native/blob/57334407473a31ff43baa645dafd2f5e1bd910fb/platform/ios/src/MGLMapView.mm#L3464-L3470

And since it only happens vertically that led me here
https://github.com/mapbox/mapbox-gl-native/blob/41b25e2aa205a54b916ba987c9c0ae600204ebfd/src/mbgl/map/transform.cpp#L114

I can't figure out why we have that line but I think it's causing this. The only possible explanation I could find was about macOS having a different coordinate system origin 

### Steps to reproduce

 1. Set userTrackingMode to .none
 2. Set mapView.contentInset = UIEdgeInsets(top: 0, left: 10, bottom: 300, right: 10)
 3. Rotate the map to anything but north
 4. Rotate the map back to north
 5. The map jumps up after you release it

### Expected behavior
The map would stay as you had it before releasing it

### Actual behavior
The map jumps up

### Configuration

**Mapbox SDK versions:** ios-v4.9.0
**iOS/macOS versions:** iOS 12.1.4
**Device/simulator models:** iPhoneX
**Xcode version:** 10.1

**Comment by TimWatson** [comment]
If someone can explain how to use a fork of this repo in my project (carthage) I can remove that line and test it

**Comment by 1ec5** [comment]
> I can't figure out why we have that line but I think it's causing this. The only possible explanation I could find was about macOS having a different coordinate system origin

Unless something has changed recently, mbgl assumes an origin at the top-left, just like iOS does natively. Only macOS puts the origin at the bottom-left, but the macOS implementation of MGLMapView compensates by flipping the coordinates in Objective-C.

https://github.com/mapbox/mapbox-gl-native/blob/41b25e2aa205a54b916ba987c9c0ae600204ebfd/platform/macos/src/MGLMapView.mm#L2900-L2901

/ref #3574 #3583

**Comment by TimWatson** [comment]
Yeah that's what I found. So why are we flipping it for iOS in easeTo there?

**Comment by TimWatson** [comment]
This was fixed with the last update (4.10)

**Comment by julianrex** [comment]
@TimWatson thank you for confirming!

**Comment by TimWatson** [comment]
This is happening again in 5.1.0
