### ISSUE TITLE
OnScrollListener documented but not implemented

### ISSUE THREAD

**Issue by xit0c** [mapbox/mapbox-gl-native#14166]
Mapbox SDK version: 7.2.0

[Here](https://docs.mapbox.com/android/maps/overview/events/#on-fling--on-scroll-events) is documented a MapboxMap.OnScrollListener but, in the current version of the SDK (7.2.0), this interface [doesn't exist](https://docs.mapbox.com/android/api/map-sdk/7.2.0/com/mapbox/mapboxsdk/maps/MapboxMap.html).

I find it very useful, is it planned for a future release?

**Comment by LukasPaczos** [comment]
Hey @xit0c, the `OnScrollListener` has been superseded by the [`OnMoveListener`](https://docs.mapbox.com/android/api/map-sdk/7.2.0/com/mapbox/mapboxsdk/maps/MapboxMap.OnMoveListener.html) that can be added with the `MapboxMap#addOnMoveListener`. We definitely need to update the docs, thanks for reaching out!
