### ISSUE TITLE
C++ 14 on Android

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#1416]
Need to investigate upgrading to C++ 14 with Android builds.

- [ ] Check what clang/gcc support is in Android NDK
- [ ] Update android-build AMIs to use newer clang/gcc
- [ ] Enable C++ 14 switch in Android gyp build

/cc @incanus @jfirebaugh

**Comment by jfirebaugh** [comment]
I think we're good here; I moved to C++14 in e476fcbf3be861b4b080d647fd7d7fa71570c86a and the Android-specific part of it was adding `-Wno-c++1y-extensions`.

**Comment by ljbade** [comment]
Great, closing then.
