### ISSUE TITLE
[ios] Binary size diffing is inaccurate

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#14183]
Looking at #14148, I noticed that the binary size change calculation seemed off:

<img width="498" alt="Screen Shot 2019-03-20 at 6 13 05 PM" src="https://user-images.githubusercontent.com/1198851/54728717-cbc02900-4b3c-11e9-899f-271d7474eb05.png">

When building the before/after commits locally, this was the result:

```
FLAVOR			BEFORE	   AFTER      DIFF IN BYTES
Mapbox-stripped		17482360 - 17482344 = 	    16
Mapbox-stripped-arm64	4358776  - 4358760 = 	    16
Mapbox-stripped-armv7	3972632  - 3972572 = 	    60
Mapbox-stripped-x86_64 	4668144  - 4668128 = 	    16
```

So the actual change in `Mapbox-stripped-armv7` was 60 bytes, not 16.4 kilobytes.

May be related to recent changes in the binary size uploading scripts. (#13876, etc.)

/cc @captainbarbosa

**Comment by friedbunny** [comment]
@kkaefer’s hypothesis over in https://github.com/mapbox/mapbox-gl-native/pull/14421#issuecomment-487014558:

> any discrepancies you're seeing results from how the code is packed into the Macho-O data chunks. E.g. they might be filled with 0 bytes. When making a fat binary, they're rearranged which would explain why the numbers are sometimes odd.

If that’s the cause of the skew, then there’s not much we can reasonably do about it.

**Comment by julianrex** [comment]
Check we check pre-fat? (Perhaps in addition.)

**Comment by friedbunny** [comment]
We spent a while looking at this and didn’t come up with any solutions. Given that the reported differences are small (typically bytes or single-digit kilobytes), we can still have reasonable confidence in this script as-is.
