### ISSUE TITLE
Scale Bar should allow user to set if it is metric

### ISSUE THREAD

**Issue by nnhubbard** [mapbox/mapbox-gl-native#14182]
Users don't always want iOS to control the metric setting. For our app we have a Metric setting that users can change, it would be great if the scale bar allowed manually setting of the metric option rather than using the system local.

### Steps to reproduce

 1. Scale Bar uses system local for metric setting

### Expected behavior

Scale bar should allow users to set this option.

### Actual behavior

Scale bar uses system local.

### Configuration

**Mapbox SDK versions:** 
4.9
**iOS/macOS versions:** 
iOS 12
**Device/simulator models:**
iPhone X
**Xcode version:** 
10.1

**Comment by julianrex** [comment]
Still open, bot.

**Comment by adam-schoonmaker** [comment]
Still open, bot.
