### ISSUE TITLE
func mapView(_ didAdd:) not called when using MGLVectorTileSource

### ISSUE THREAD

**Issue by otusweb** [mapbox/mapbox-gl-native#14199]
I'm using mapbox to show POI on a map and using a MGLVectorTileSource to load them.
The POI are displaying corretly,but the didAdd method is not called.

### Steps to reproduce

1. add a MGLVectorTileSource to a map
2. set the delegate on the mapViewbox
3. launch the app and move around until an annotation is displayed

### Expected behavior
the delegate mapView(_ mapView: MGLMapView, didAdd annotationViews: [MGLAnnotationView])  is called

### Actual behavior
the delegate mapView(_ mapView: MGLMapView, didAdd annotationViews: [MGLAnnotationView])  is **NOT** called

### Configuration

**Mapbox SDK versions**: pod 'Mapbox-iOS-SDK', '~> 4.9'
**iOS/macOS versions**: 10.12
**Device/simulator models**: iphone XR 12.1
**Xcode version**: XCode 10.1

**Comment by friedbunny** [comment]
Symbols or shapes added via style layers will not call delegate methods for annotations (as they are not annotations). For more information about the different ways to represent data on maps, see:

- https://docs.mapbox.com/ios/maps/overview/markers-and-annotations/
- https://docs.mapbox.com/ios/maps/overview/runtime-styling/

**Comment by otusweb** [comment]
Thanks
