### ISSUE TITLE
How to draw NavigationMapRoute on top of other line

### ISSUE THREAD

**Issue by stoefln** [mapbox/mapbox-gl-native#14204]
### Steps to reproduce

 1. Setup mapbox navigation and mapview
 2. Draw a line via `mapboxMap.addPolyline()`
 3. Create a NavigationMapRoute

### Expected behavior
Everything works as expected. Still, I would like to have the NavigationMapRoute drawn on top of the line which I drew in step 2.

I am aware of the parameter `belowLayer`, and I am also aware of the fact that  `mapboxMap.addPolyline()` is deprecated and that there is an AnnotationPlugin and a LineManager which also provides a way to pass a `belowLayer` argument. I am just not sure how to make use of this param to achieve my goal.

I guess what I am missing here is how to assign either of both lines to a specific layer.

Can you give me a hint?

**Comment by fabian-guerra** [comment]
Hi, @stoefln. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/) or check our [documentation](https://www.mapbox.com/ios-sdk/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
