### ISSUE TITLE
Different custom marker image with respective to location(Android)

### ISSUE THREAD

**Issue by vigneshr87** [mapbox/mapbox-gl-native#14200]
Hi , I am trying to add custom images(user location on mapbox) instead of marker on the given feature collections. I am hard to find references to achieve the same.
I came across SymbolLayerMapillary, We need something similar to the same but not maki-icons. We need user profile icon with respect to user location.

1. Is it possible by using single SymbolLayer ? If yes, Please help me with references.

**Comment by tobrun** [comment]
Here is an example https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolLayerActivity.java#L171
