### ISSUE TITLE
locationComponent marker position not customizable

### ISSUE THREAD

**Issue by stoefln** [mapbox/mapbox-gl-native#14202]
### Steps to reproduce

 1. activate locationComponent
 2. set CameraMode to TRACKING

### Expected behavior

Everything works as expected. The problem is that I would like to position the marker more towards the bottom of the screen, when using Mapbox for navigation.
Did I miss something? I was achieving this before with setting a padding for the locationLayerPlugin.

**Comment by fabian-guerra** [comment]
Hi, @stoefln. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/) or check our [documentation](https://www.mapbox.com/ios-sdk/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
