### ISSUE TITLE
[iOS] Offline download from background thread

### ISSUE THREAD

**Issue by emerciercontexeo** [mapbox/mapbox-gl-native#14206]
I was working on an application that requires offline download. I have to perform an Api call before starting to download the map and the callback of this call is not running on the main thread.

I ran the download process from this background thread and the download works fine. But, when I instantiate the map, it crashes.

iOS Version 4.9.0 (tested on 4.7.0 and 4.8.0)

### Steps to reproduce

 1. Before instantiating the map, call MWZOfflineStorage.shared on a background thread
 2. Instantiate the map

### Expected behavior

The map should be displayed

### Actual behavior

The application crash

### Opinions

- I didn't find any information about the fact that MWZOfflineStorage.shared should be instantiated on the main thread. If I missed this information, sorry for this post.

- As MWZOfflineStorage.shared is a Singleton, I suppose that when the first call is made in a background thread the MGLMapView fails to use it properly in the main thread.

Etienne

**Comment by 1ec5** [comment]
Would it be feasible for your application to interact with the singleton within a `dispatch_async` block on the main queue?

MGLOfflineStorage wasn’t designed to be initialized on a background thread, at least. I’m not sure how feasible it would be to make the class safe for background threads, given all the work it does on the file system with the cache database and, as you mention, its use by MGLMapView and potentially other UI classes.

We should probably document that `MGLOfflineStorage.sharedOfflineStorage` needs to run on the main thread. Note that `MGLOfflineStorageDelegate`’s methods are also called on the main thread.

**Comment by emerciercontexeo** [comment]
Hi,

Sorry for the lake of reactivity, I didn't see your response to this issue.
This issue was mostly to let you know this behavior and the missing information in the documentation about it.

Note: If I remember properly, we can instantiate from the background thread, run a region download and it works fine. The crash occurs only when you try to display the map after that.

Etienne

**Comment by goors** [comment]
It would be great if this can work on  DispatchQueue.global().async {}. That is not possible right?
