### ISSUE TITLE
<experimental/optional> deprecated in Xcode 10.2

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#14214]
Xcode 10.2 betas include a version of LLVM (`Apple LLVM version 10.0.1 (clang-1001.0.46.2)`) that throws the following error/warning wherever we include [`mbgl/util/optional.hpp`](https://github.com/mapbox/mapbox-gl-native/blob/1d7b243a06c6c3d2def4d1989e93e90250e87cad/include/mbgl/util/optional.hpp):

> <experimental/optional> is deprecated and will be removed in the next release. Please use C++17's <optional> instead.

It appears we’ve already worked around this deprecation for Android in #13049.

This deprecation is currently failing the build in Xcode 10.2b4, so it will likely prevent us from updating to 10.2 (probably available ~next week) if we’re not able to address the issue or temporarily silence the warning/error.

/cc @kkaefer @tmpsantos @julianrex @mapbox/maps-ios

**Comment by friedbunny** [comment]
Xcode 10.2 is available today and [its release notes](
https://developer.apple.com/go/?id=xcode-10.2-fcs) include this:

> The `<experimental/any>` and `<experimental/optional>` headers are deprecated in favor of their C++17 counterparts: `<any>` and `<optional>`. They will be removed in a future release of Xcode, and you shouldn’t rely on their presence. (46903112)

**Comment by kkaefer** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/14241
