### ISSUE TITLE
Build on Windows

### ISSUE THREAD

**Issue by H4wak** [mapbox/mapbox-gl-native#1421]
Hi,
I'm trying to build GL on Windows but GYP is new to me. I built some little projects with GYP but MapBox-GL is bigger by far. Perhaps you can give me some ways to fix my issues !

I have many many `Undefined variable` about all flags and libs ( `glfw3_cflags` , `cflags_cc` , `platform_lib` , `http_lib` ... ).
I think i don't have all the libs for building this. For Linux and OSX, Mason install all the packages for building GL. How can i do that for Windows ?

I know building GL on WIndows is not your priority, but if you have some little advices, this will help me alot ! And, if you want to build GL on Windows one day, this will maybe help you.

Thanks!

**Comment by jfirebaugh** [comment]
Hi @H4wak, thanks for trying out mapbox-gl. Unfortunately we don't support compiling on Windows right now, and it's not on our roadmap.

**Comment by nicomgd** [comment]
FWIW we've started a Windows build on our side here : https://github.com/mapbox/mapbox-gl-native

Right now, it's very WIP but looks promising.

**Comment by danzel** [comment]
I think you meant to link to https://github.com/mgdesign-fr/mapbox-gl-native ?

**Comment by nicomgd** [comment]
Huh, right ! Thanks for pointing this out ! :}

**Comment by lygstate** [comment]
What kinds of reason do not support for windows?

**Comment by AliFlux** [comment]
There wasn't any suitable vector tile rendering system for Windows, so I ended up writing one by myself using C# and SkiaSharp. The results seem promising.

![strip](https://user-images.githubusercontent.com/8333794/38769981-38408760-4025-11e8-86ad-e79dd23ac853.png)

Check it out and let me know what you think.
https://github.com/AliFlux/VectorTileRenderer
