### ISSUE TITLE
BubbleLayout is deprecated

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#14228]
I use BubbleLayout for show callout view. But in mapbox android sdk 7 this class is deprecated. 
What are the alternatives?

Used it in the demo application: https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/res/layout/mapillary_layout_callout.xml

### Expected behavior
not deprecated class for callout view

### Actual behavior
BubbleLayout is deprecated

### Configuration

**Android versions:** Any
**Device models:** Any
**Mapbox SDK versions:**  Android 7+

**Comment by tobrun** [comment]
@klblk BubbleLayout is part of the annotations package that has been deprecated in total. This has been replaced by annotations plugin from https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-annotation. Atm, we do not yet support a InfoWindow alternative this is tracked in https://github.com/mapbox/mapbox-plugins-android/issues/649. 

Imo BubbleLayout, which requires to synchronise an Android SDK view on top of map, was never the best UX. Moving forward we are looking into a bitmap alternative (potentially generated from an Android SDK view). 

Closing this as not actionable, feel free to follow up on the plugin specific issue.
