### ISSUE TITLE
Double tap/hold zoom in/out does not remain on focal point

### ISSUE THREAD

**Issue by mastrgamr** [mapbox/mapbox-gl-native#14227]
Image: [**via Imgur**](https://imgur.com/YqxwsK2)
Video: [hi-rez](https://www.dropbox.com/s/5ex87c6mvts3z7r/2019_03_25_20_46_00_trim.mp4?dl=0)

### Steps to reproduce

 1. Choose an arbitrary focal point on the map.
 2. Double Tap and Hold.
 3. Drag finger down to zoom out.
 4. Repeat 2&3 to zoom in -- notice the focal point is no longer center of the map.

### Expected behavior
Double Tap and Drag to zoom In and Out should be focused on one point while zooming in/out.

### Actual behavior
Double Tap and Drag to zoom In and Out slightly shifts the map then proceeds to zoom in/out
In my image/video My focal point in the beginning of the video was the 3rd Avenue subway station.

### Configuration

**Android versions:** Pie (API 28)
**Device models:** OnePlus 6 (A003)
**Mapbox SDK versions:** 7.2.0

**Comment by tobrun** [comment]
Thank you for the report @mastrgamr
