### ISSUE TITLE
Crash when disabling telemetry

### ISSUE THREAD

**Issue by calvarez-ov** [mapbox/mapbox-gl-native#14235]
We respect the user's gdpr setting and disable telemetry tracking if the user has opted out.

### Steps to reproduce
We call
```kotlin
        Mapbox.getInstance(application, application.getString(R.string.mapbox_token))
        Mapbox.getTelemetry()?.let { telemetry ->
            telemetry.setDebugLoggingEnabled(BuildConfig.DEBUG)
            telemetry.setUserTelemetryRequestState(trackingPreference)
        }
```

### Expected behavior
Telemetry should be enabled/disabled per the call, without a crash.

### Actual behavior

This sometimes results in a crash. Looks like a timing issue? I don't know yet under what conditions the crash occurs, but if I'm able to find out, I'll update here.
```
Caused by: java.lang.NullPointerException: cancel() called with a null PendingIntent
       at android.app.AlarmManager.cancel(AlarmManager.java:920)
       at com.mapbox.android.telemetry.AlarmSchedulerFlusher.unregister(AlarmSchedulerFlusher.java:56)
       at com.mapbox.android.telemetry.MapboxTelemetry.stopAlarm(MapboxTelemetry.java:437)
       at com.mapbox.android.telemetry.MapboxTelemetry.stopTelemetry(MapboxTelemetry.java:542)
       at com.mapbox.android.telemetry.MapboxTelemetry.disable(MapboxTelemetry.java:141)
       at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.setUserTelemetryRequestState(TelemetryImpl.java:75)
       at com.ourapp.OurViewModel.<init>(OurViewModel.kt:89)
       ... 19 more
```

### Configuration

**Android versions:** Seen on Oreo 8.0
**Device models:** Seen on Samsung Galaxy s8+
**Mapbox SDK versions:** 7.2.0

### More information
Not sure yet if this is limited to a specific version of Android or a specific device. For now we've seen it on the device mentioned above.
Based on the AOSP source code for `AlarmManager`, this crash should only happen on Nougat 7.0 and later devices (the `PendingIntent` is `null`):
```java
    public void cancel(PendingIntent operation) { 
        if (operation == null) {
            final String msg = "cancel() called with a null PendingIntent";
            if (mTargetSdkVersion >= Build.VERSION_CODES.N) {
                throw new NullPointerException(msg);
            } else {
                Log.e(TAG, msg);
                return;
            }
        }
...
    }
```

**Comment by calvarez-ov** [comment]
I found one way to reproduce this consistently, but it's not at all what we're actually doing in our app. Reset the telemetry state preference to `ENABLED` before using the api `setUserTelemetryRequestState(false)`.


```kotlin
Mapbox.getInstance(application, application.getString(R.string.mapbox_token))
TelemetryEnabler.updateTelemetryState(TelemetryEnabler.State.ENABLED)
Mapbox.getTelemetry()?.let { telemetry ->
    telemetry.setDebugLoggingEnabled(BuildConfig.DEBUG)
    telemetry.setUserTelemetryRequestState(false)
}
```

In this case, the app crashes every other time we open the map (when the app doesn't crash, you have to kill it before opening it again, to get the crash -- to clear the `AlarmSchedulerFlusher.pendingIntent` field.
.
There are two scenarios:
* telemetry has been previously enabled:
  - `Mapbox.getInstance()` will end up calling `AlarmSchedulerFlusher.register()` which will create the `pendingIntent`.
  - `TelemetryEnabler.updateTelemetryState(TelemetryEnabler.State.ENABLED)` doesn't change anything
  - `telemetry.setUserTelemetryRequestState(false)` ends up calling `AlarmSchedulerFlusher.unregister()`. Since it has a `pendingIntent`, it's ok
  - the telemetry state is set to `DISABLED`.
* telemetry has been previously disabled:
  - `Mapbox.getInstance()` will not end up calling `AlarmSchedulerFlusher.register()`, so its `pendingIntent` stays `null`
  - `TelemetryEnabler.updateTelemetryState(TelemetryEnabler.State.ENABLED)` resets the state to `ENABLED` (without, apparently, having any effect on the telemetry service or `AlarmSchedulerFlusher`)
  - `telemetry.setUserTelemetryRequestState(false)` will end up calling `AlarmSchedulerFlusher.unregister()`.  Since the `pendingIntent` hasn't been initialized, it crashes (on Nougat+)
  - the telemetry state remains `ENABLED` and will be enabled upon next app launch.

To clarify, we're not calling `TelemetryEnabler.updateTelemetryState(TelemetryEnabler.State.ENABLED)` in our real app. But maybe something else in the mapbox sdk is?

**Comment by tobrun** [comment]
cc @andrlee

**Comment by andrlee** [comment]
@calvarez-ov thanks a ton for investing your time into this detailed analysis, i will definitely investigate and put together a solution that fixes root cause, meanwhile we've put a fix (null check) around this error scenario, which is included in https://github.com/mapbox/mapbox-events-android/releases/tag/telem-4.3.0 and as a result in: https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v7.3.0-beta.1 would you mind re-testing with `7.3.0-beta.1`? Thanks again!

**Comment by calvarez-ov** [comment]
Many thanks for the quick reply! I see the fix was done here:  https://github.com/mapbox/mapbox-events-android/pull/345

I'll give the `7.3.0-beta.1` a try.

**Comment by tobrun** [comment]
Considering that this should already be resolved, I'm going to close.
Thanks again @calvarez-ov for reaching out and reporting this!
