### ISSUE TITLE
Satellite style flickers, renders black or inconsistently

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#1423]
Satellite tiles flicker and fail to load most of the time while using the demo app. This was broken as part of [#1325 Simply render path](https://github.com/mapbox/mapbox-gl-native/pull/1325).

 Happens on device and in simulator, as of latest `master` (fab65e75d0b13a5d03eaea151bb63f2fc6b76bd0). I'd guess this affects all raster sources.

![ios simulator screen shot may 5 2015 8 24 24 am](https://cloud.githubusercontent.com/assets/1198851/7476252/30575d04-f301-11e4-99c9-8fe942d67aac.png)

Sorry to keep dropping these on you, @kkaefer.

**Comment by tmpsantos** [comment]
I noticed that too now that we have a style switcher on Linux and MacOS test app.

**Comment by jfirebaugh** [comment]
Fixed by #1513.
