### ISSUE TITLE
Use Geofencing To Reduce Power Usages

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1424]
Monitor device velocity to make an educated guess as to when it's in a relatively static location so that more battery intensive location services (GPS) can be switched off to save device power.  When the device leaves a specific radius (aka "geofence") re-enable location services so that the more accurate location services (GPS) can be re-enabled for map building.

The Geofences can be built using iOS's [Region Monitoring API](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/RegionMonitoring/RegionMonitoring.html#//apple_ref/doc/uid/TP40009497-CH9-SW1).

@mapbox/mobile @mapbox/mobiledata

**Comment by friedbunny** [comment]
I'll be really interested to see which strategy is the best for determining stops while preserving battery. Simple coordinate/time comparison? [Core Motion activity API](https://developer.apple.com/library/ios/documentation/CoreMotion/Reference/CMMotionActivity_class/index.html)? Direct accelerometer access? Significant change API?

**Comment by sbma44** [comment]
@friedbunny we've spoken to some experienced mobile devs who said that they keep a running figure for user velocity. Their use case/user experience emphasizes detecting stops quickly, though, so it's possible we will be able to do something simpler or better.

**Comment by bleege** [comment]
Moving to Beta 3 to focus on map UI features in the short term.

**Comment by bleege** [comment]
So this has been now officially moved from the iOS Beta 3 to iOS 3.2.0 release `#BetterLateThanNever`

**Comment by boundsj** [comment]
Addressed by https://github.com/mapbox/mapbox-gl-native/pull/4115
