### ISSUE TITLE
MGLOpenGLStyleLayer how to draw at geographic coordinates example

### ISSUE THREAD

**Issue by nferruzzi** [mapbox/mapbox-gl-native#14266]
Not a bug, I was going to ask for help understanding how to draw a triangle at geographic coordinates using  MGLOpenGLStyleLayer but after a day of experiments I think I worked it out; I'm just sharing this gist to help anyone else starting with the custom GL layer. Hope you don't mind.

https://gist.github.com/nferruzzi/06abe735c70af9f55e359cae6729bfe3

**Comment by julianrex** [comment]
@nferruzzi thanks so much for this example!
