### ISSUE TITLE
pod broken in 0.37.0 (proper fix)

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1426]
I think this is the upstream issue: https://github.com/CocoaPods/CocoaPods/issues/3106

Per the [changelog](https://github.com/CocoaPods/CocoaPods/blob/0.37.0/CHANGELOG.md): 

> Do not create pod target if `source_files` only contains headers.

https://github.com/mapbox/mapbox-gl-native/blob/24a0d77c839e730e41b9956899f02955de3011e9/ios/MapboxGL.podspec#L25

Things work fine right now with `0.36.4`, so do this: 

* `gem uninstall cocoapods cocoapods-core`
* `gem install cocoapods -v 0.36.4`
* `rm -rf Podfile.lock Pods`
* `pod install`

**Comment by incanus** [comment]
Yeah, this is flat-out a bug in CocoaPods `0.37.0`. Hopefully it'll get fixed in time for our launch :grimacing:

**Comment by neonichu** [comment]
Worst case you should be able to work around it by adding a dummy/empty .m file to your `source_files`.

**Comment by incanus** [comment]
Ah, I had thought about that — thanks for the tip.

**Comment by incanus** [comment]
Managed to fix this using @neonichu's workaround above. Once tests pass, I will merge this and move this ticket to b2 milestone since non-critical. 

@geografa @katydecorah @mapbox/mobile CocoaPods `0.37.0` will work again once this lands. 

* `gem uninstall -a cocoapods cocoapods-core`
* `gem install cocoapods -v 0.37.0`
* `rm -rf Podfile.lock Pods`
* `pod install`

**Comment by incanus** [comment]
Travis acting up — tests locally.

**Comment by incanus** [comment]
In `master` as of https://github.com/mapbox/mapbox-gl-native/commit/6c31d928e1c32ceaee07384e47c644f3643be447. Moving eventual proper resolution to b2.

**Comment by incanus** [comment]
Not critical for b2; pushing for now.

**Comment by incanus** [comment]
Obsoleted by https://github.com/mapbox/mapbox-gl-native/pull/2132; we should clean up here.

**Comment by incanus** [comment]
cf. https://github.com/mapbox/mapbox-gl-native/blob/c4cbe648b1c9cf224740015efaac54bc327f9b7d/scripts/ios/package.sh#L100-L101

**Comment by 1ec5** [comment]
This will be moot once we move to a dynamic framework in #3182 and/or #3183.
