### ISSUE TITLE
Missing logs when a local resource fails to load

### ISSUE THREAD

**Issue by Coneys** [mapbox/mapbox-gl-native#14276]
### Steps to reproduce

 1. Put folder with tiles in internal storage of android device (name/{Z}/{X}/{Y})
 2. Add RasterSource with RasterLayer

// Checking storage permissions

` mapboxMapView.getMapAsync {
                
                it.setStyle(Style.OUTDOORS)
                val tileDirectory = File(filesDir, "name")

                val tileStr =  "file://${tileDirectory.absolutePath}/{z}/{x}/{y}.png"                

                it.getStyle {
                    val source = RasterSource(
                        "tile", TileSet(
                            "1.0", tileStr
                        ), 256
                    )
                    val layer = RasterLayer("tile","tile")
                 
                    it.addSource(source)
                    it.addLayer(layer)

                }`

### Expected behavior

Layer should be showed on map, or Mapbox should at least throw some error / log some warnings

### Actual behavior

Nothing

### Configuration

Checked on many android devices (android 7,8 and 9)
With mapbox 7.3.0

Even changing "tileDirectory" name for some random string doesn't show any error or warning. Also I am sure that tileDirectory and PNG's exists on device

**Comment by LukasPaczos** [comment]
Thanks for the report @Coneys. I'm also not seeing any logs when an invalid path is provided.

I followed the logic, and the error is detected and correctly set on the request object in the [`local_file_request.cpp`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/default/src/mbgl/storage/local_file_request.cpp#L34), but the lambda is never invoked back in the [`raster_source.cpp`](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/style/sources/raster_source.cpp#L54), which in consequence doesn't notify the style about the `onSourceError` which should print the error.

/cc @tmpsantos

**Comment by LukasPaczos** [comment]
Additionally, I have no troubles rendering [raster tiles](https://openmaptiles.com/downloads/tileset/satellite-lowres/) from `file://` or `asset://` paths based off of your example. I suspect there might some other issue, which is hidden under a log that's not printed, so let's try to resolve that first.

**Comment by Coneys** [comment]
Thanks for your response! I found the problem, it turned out that my tiles has another way of indexing Y.
I had to use transform Y with this code : 
` val newY = pow(2, zoom) - oldY - 1`
Still logs would be really helpful, because I had no idea what was wrong. 

Furthermore, is there a way to scale RasterLayer automatically? When I zoom out too much it disappears, and I don't want to create scaled tiles for bigger zooms manually. 

Thanks you once again :)

**Comment by LukasPaczos** [comment]
I'm glad to hear that it works for you!

When it comes to scaling - raster tiles' "overzoom" should work out of the box when out of range, but I'm not sure there's a concept of "underzoom", I think you'll have to provide a base image for `z0` (correct me if I'm wrong @tmpsantos), or limit the min zoom values of the map with `MapboxMapOptions#minZoomPreference` or in the XML with `app:mapbox_cameraZoomMin="{min zoom}"`.

**Comment by tmpsantos** [comment]
> When it comes to scaling - raster tiles' "overzoom" should work out of the box when out of range, but I'm not sure there's a concept of "underzoom", I think you'll have to provide a base image for `z0` (correct me if I'm wrong @tmpsantos), or limit the min zoom values of the map with `MapboxMapOptions#minZoomPreference` or in the XML with `app:mapbox_cameraZoomMin="{min zoom}"`.

This exactly. :+1:

**Comment by LukasPaczos** [comment]
Great, thanks for the confirmation @tmpsantos :+1: 

In this case, the only actionable items here are the missings logs in the event of invalid local resources/paths.

**Comment by LukasPaczos** [comment]
There's still no error message printed when an invalid tileset is provided.
