### ISSUE TITLE
Frame rate tracking should measure frame rate of map, not CADisplayLink

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#14277]
The experimental frame rate measurement feature added in #12557 updates various counters within `-[MGLMapView updateFromDisplayLink:]`, which gets called on every tick of the CADisplayLink. This all but ensures that the resulting frame rate matches the preferred frame rate within a small tolerance, even when the map performs very poorly as in #14264.

A more effective implementation would hook into `-[MGLMapView mapViewDidFinishRenderingFrameFullyRendered:]`, which gets called with the same frequency as `-[MGLMapViewDelegate mapViewDidFinishRenderingFrame:fullyRendered:]`.

/cc @friedbunny @julianrex @fabian-guerra

**Comment by julianrex** [comment]
I think we need to measure both, both the actual FPS and the time spent in framework code. My feeling is that this is more about terminology.

**Comment by 1ec5** [comment]
In what scenario would we anticipate the display link’s frame rate dipping significantly below the preferred frame rate? How would detecting that result in actionable feedback for the application or SDK?
