### ISSUE TITLE
How to vary the pitch level depending on the camera altitude? Getting infinite loop and app crashes

### ISSUE THREAD

**Issue by StratRob** [mapbox/mapbox-gl-native#14275]
Hello,

I am trying to get a "Pokemon GO"-like effect, with the camera pitch varying depending on its altitude. I am restricting the camera zoom level from 17 to 19, so it's always close to the ground.

Aerial view:

<img width="150" alt="Capture d’écran 2019-03-30 à 13 50 48" src="https://user-images.githubusercontent.com/25252204/55287292-2eb88800-53a7-11e9-8fd3-f882fd47a865.png">

Closer to the ground:

<img width="150" alt="Capture d’écran 2019-03-30 à 13 50 32" src="https://user-images.githubusercontent.com/25252204/55287293-324c0f00-53a7-11e9-9bda-6ea0d5ee8fe2.png">

I have written a simple linear function that I plan to improve, returning a value (the pitch) that should always be between ~40 (for a zoom level of 17) and ~100 (for a zoom level of 19).

    func pitchFor(_ altitude: Double = 420) -> CGFloat {
        return CGFloat(100 - ((altitude - 125) / 6.85))
    }

Then I simply thought it would be enough to call `mapViewRegionIsChanging` delegate function, and updating the pitch from here:

    func mapViewRegionIsChanging(_ mapView: MGLMapView) {
        let camera = MGLMapCamera(lookingAtCenter: mapView.camera.centerCoordinate, 
                                         altitude: mapView.camera.altitude, 
                                            pitch: pitchFor(mapView.camera.altitude), 
                                          heading: mapView.camera.heading)
        mapView.setCamera(camera, animated: true)
    }

But I end up getting something that looks a lot like an infinite loop and then the app crashes:

<img width="536" alt="Capture d’écran 2019-03-30 à 16 12 55" src="https://user-images.githubusercontent.com/25252204/55287284-0d579c00-53a7-11e9-96e6-e0f270306cb6.png">

Can you help me with that? I didn't know where to ask so I hope it's the right place, sorry if not.

Thanks for your help.

### Configuration

**Mapbox SDK versions:** 4.9.0
**iOS/macOS versions:** 12.1.4
**Device/simulator models:** iPhone XR
**Xcode version:** 10.1

**Comment by 1ec5** [comment]
Unfortunately, methods such as `-mapViewRegionIsChanging:` get called in response to programmatic camera changes in addition to user-initiated camera changes. So changing the camera within `-mapViewRegionIsChanging:` causes recursion unless you explicitly guard against it with a base case. For example, the method could bail if the pitch is already the same as what you’d change it to.

(Relatedly, #6908 tracks varying the maximum pitch by the altitude or zoom level.)

**Comment by StratRob** [comment]
Thank you for your answer, and all the work you're doing on this project. 
Is there maybe another way to achieve this varying pitch feature, maybe from another delegate method? I have read the related issue and it looks like there is no easy way to do so, or maybe have I missed something.

**Comment by julianrex** [comment]
@StratRob until we fix the core underlying issue, I'd recommend trying to call `setCamera` from a `DispatchQueue.main.async`. See https://github.com/mapbox/mapbox-gl-native/issues/14998#issuecomment-506757397 for a similar issue.

Can you please try this and let me know if this works for you? Thanks

**Comment by nnhubbard** [comment]
Was this issue ever fixed @julianrex ?
