### ISSUE TITLE
Accessing LocationComponent.isLocationComponentEnabled() crashes the app since 7.4.0-Snapshot

### ISSUE THREAD

**Issue by carstenhag** [mapbox/mapbox-gl-native#14299]
```kotlin
    public override fun onResume() {
        super.onResume()
        mapView.onResume()
        // After the user allowed the Location Permission in the settings or the dialog, we can enable the LocationComponent
        if (::mapboxMap.isInitialized && !mapboxMap.locationComponent.isLocationComponentEnabled && PermissionsManager.areLocationPermissionsGranted(this)) {
            enableLocationComponent()
        }
    }
```

```
Caused by: com.mapbox.mapboxsdk.location.LocationComponentNotInitializedException: The LocationComponent has to be activated with one of the LocationComponent#activateLocationComponent overloads before any other methods are invoked.
        at com.mapbox.mapboxsdk.location.LocationComponent.checkActivationState(LocationComponent.java:1521)
        at com.mapbox.mapboxsdk.location.LocationComponent.isLocationComponentEnabled(LocationComponent.java:514)
        at de.chagemann.stadtplanmosbach.MainActivity.onResume(MainActivity.kt:346)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1514)
        at android.app.Activity.performResume(Activity.java:7305)
```

### Steps to reproduce

 1. Access the `isLocationComponentEnabled()` method before having initialized the LocationComponent.
2. The app crashes since 7.4.0-Snapshot

### Expected behavior
* I am allowed to know whether the component was actived yet or not
* Needed to only enable it once
* Needed so it can be done at arbitrary points, like in an onResume, as permissions need to be granted before initializing the component.

### Actual behavior
* Since 7.4.0-Snapshot (not sure which commit), this is disallowed.
I am unsure as on how to activate it now.

### Configuration

**Android versions:** Android 9
**Device models:** One Plus 5
**Mapbox SDK versions:** Works with 7.3.0 and 7.3.0-Snapshot, broken with 7.4.0

**Comment by carstenhag** [comment]
Actually, I am now using the new `LocationComponentActivationOptions.Builder` so that may cause the issue.

**Comment by LukasPaczos** [comment]
Thanks for reporting the issue @carstenhag. Per stack trace, you are checking if the component is enabled before activating it, so the crash is expected.

That said, we realize that we did not expose a proper way to check for activation state, so https://github.com/mapbox/mapbox-gl-native/pull/14262 is on the way to address that.

Also, it's safe to activate the plugin without location permissions, those are required only when enabling it, https://github.com/mapbox/mapbox-gl-native/pull/14311 on the way as well.

**Comment by carstenhag** [comment]
So, to recap, I should proceed as following after #14311 is merged:

1. In the `onMapReady` callback, activate the LocationComponent
2. Prompting/Check the Location permission. Only activate when `isLocationComponentEnabled` returns false.
3. Enable the LocationComponent

Is this right or did I get it wrong? Thanks in advance, you are very quick to answer!

**Comment by LukasPaczos** [comment]
Sounds about right. You can also maintain your own flag that holds activation state if you'd like to keep current behavior (checking in the `onResume`) until https://github.com/mapbox/mapbox-gl-native/pull/14262 is merged.

**Comment by LukasPaczos** [comment]
https://github.com/mapbox/mapbox-gl-native/pull/14262 has landed, closing this one.

**Comment by carstenhag** [comment]
Thanks :) Lovely to work with you.

Łukasz Paczos <notifications@github.com> schrieb am Mo., 8. Apr. 2019,
16:53:
