### ISSUE TITLE
[core] Race condition when saving shaders to disk

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#14294]
When opening the app for the first time or when after after a GL driver update that breaks the binary shader compatibility, Mapbox GL will re-create the shaders and store them on the filesystem. We have two problems here:

- If we have multiple maps, there is a race when writing the shaders to disk. Multiple maps might try to write on the same file.
- There is no recovery from a broken/corrupted shader. File needs to be deleted.

**Comment by tmpsantos** [comment]
This could buy us time until we find a solution https://github.com/mapbox/mapbox-gl-native/pull/14298

**Comment by friedbunny** [comment]
Inadvertently closed by the commit message in #14298.

**Comment by tmpsantos** [comment]
> Inadvertently closed by the commit message in #14298.

Oh, indeed. Thanks!

**Comment by chloekraw** [comment]
This is still a release blocker issue if we decide to re-enable binary caching of shaders. Atm there are no plans to do so.
