### ISSUE TITLE
Have MGLMapView Update MGLAccoutManager Access Token

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1430]
See https://github.com/mapbox/mapbox-gl-native/pull/1329/files#r29707668

`-[MGLMapView setAccessToken:]`

**Comment by incanus** [comment]
Let's move this to b2 as non-critical and a known, rare bug.

**Comment by 1ec5** [comment]
This was fixed in f860169f356af37536443d8f23e8ccd610c21eb9 for #1491.

**Comment by incanus** [comment]
![iur](https://cloud.githubusercontent.com/assets/17722/7622526/0c45987e-f985-11e4-8a2c-f8145ff57bde.gif)
