### ISSUE TITLE
Strange Artifacts in Fill Layer

### ISSUE THREAD

**Issue by olsisaqe** [mapbox/mapbox-gl-native#14316]
When Using holes in Fill Layer strange artefacts do appear depending on the zoom level. The problem is even worse when the Polygon data of the FillLayer is as big as the whole world. 

### Steps to reproduce

 1. Create a FillLayer
 2. Create some complex holes inside of it
 3. Zoom the map in and out. 

### Expected behavior
No strange rendering problems should appear on low zoom levels.  
![image](https://user-images.githubusercontent.com/5824180/55482155-346ed180-5624-11e9-84cf-8b08e4cdc3fd.png)

### Actual behavior
Strange artefacts are rendered: 
![image](https://user-images.githubusercontent.com/5824180/55482131-2751e280-5624-11e9-9899-4f28ade48837.png)

### Configuration

**Android versions:** 9
**Device models:** One Plus 6
**Mapbox SDK versions:** 7.2.0

**Comment by brandonreavis** [comment]
I am also noticing similar artifacts when a fill layer encounters certain polygons with holes.

Mapbox GL JS renders is correctly (https://naturalatlas-gl.global.ssl.fastly.net/styles/polygon-artifacts.html#13.28/39.49517/-105.38068):
<img width="538" alt="Screen Shot 2019-06-06 at 3 01 15 PM" src="https://user-images.githubusercontent.com/118481/59069451-00a26900-886c-11e9-87b3-c891a2cfb370.png">

How Mapbox GL Native renders it:
<img width="315" alt="Screen Shot 2019-06-06 at 3 02 28 PM" src="https://user-images.githubusercontent.com/118481/59069502-2a5b9000-886c-11e9-98ee-19a0f3e87658.png">

### Steps To Reproduce 
- Create map view with the following style url: https://naturalatlas-gl.global.ssl.fastly.net/styles/polygon-artifacts.json
- Center map at `[-105.386364, 39.491909]` and set zoom level to `13.2`

**Comment by jradasaurus** [comment]
I'm also having this problem- I have a geojson object of the entire world, and I "cut" out holes (which are all squares). Depending on zoom level strange artifacts appear. See screen shots, the first screen shot is the expected rendering, the second screen shot shows the artifact.

My Geojson is clearly valid and every geojson visualizer tool online shows the geometry as I would expect.
[geojson.txt](https://github.com/mapbox/mapbox-gl-native/files/4782992/geojson.txt)


<img width="529" alt="Screen Shot 2020-06-15 at 5 03 20 PM" src="https://user-images.githubusercontent.com/61086562/84706345-cb266600-af2a-11ea-9a8d-3b923df3d6f3.png">
<img width="529" alt="Screen Shot 2020-06-15 at 5 03 33 PM" src="https://user-images.githubusercontent.com/61086562/84706354-d11c4700-af2a-11ea-805a-d9db37470406.png">
