### ISSUE TITLE
fix start/finish rendering map delegate callbacks

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1431]
Per https://github.com/mapbox/mapbox-gl-native/commit/fab65e75d0b13a5d03eaea151bb63f2fc6b76bd0#commitcomment-11046360, the `MapChangeWillStartRenderingMap` and `MapChangeDidFinishRenderingMap` notification types are [meant to drive delegate callbacks](https://github.com/mapbox/mapbox-gl-native/blob/fd099593dc0a8fe8cb156fa22bf3739a7c325036/platform/ios/MGLMapView.mm#L2311-L2334) which have parity with Apple's MapKit. These callbacks are meant to relate to the visual appearance of render, not anything frame-based, so that common iOS post-view-load techniques can be employed. 

* Capturing a snapshot of a fully-rendered complex view for use with Core Image/blur filters for view transition effects. 
* Not presenting the map view until it's completely tiled in (we've had requests for this before from partners for raster use cases). 
* Determining when an incomplete map view might be shown, but no more attempts to load anything will be happening (`fullyRendered: NO`). 

Some [MapKit background](https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKMapViewDelegate_Protocol/index.html#//apple_ref/occ/intfm/MKMapViewDelegate/mapViewDidFinishRenderingMap:fullyRendered): 

> The map view calls this method when one or more tiles are revealed and require rendering.

[...]

> This method lets you know when the map view finishes rendering all of the currently visible tiles to the best of its ability. This method is called regardless of whether all tiles were rendered successfully. If there were errors loading one or more tiles that prevented map view from rendering them, the `fullyRendered` parameter is set to `NO`.

Calling these sorts of methods per-frame is not useful to users, either, because any work done in there will impact the render frame rate. 

If we need additional callbacks such as something like `MapChangeDidRenderFrame`, we should make and use them instead, optionally also exporting them to Cocoa. 

/cc @kkaefer

**Comment by incanus** [comment]
Per chat we are moving this to b2 and not updating anything else around delegates — known bug that they no longer work like MapKit.

**Comment by incanus** [comment]
This is a regression currently from b1 to b2.

**Comment by friedbunny** [comment]
Seeing `isChanging` still firing after `didChange`:

```objc
2015-06-23 17:02:45.333 Mapbox GL[46110:4728517] will
2015-06-23 17:02:45.335 Mapbox GL[46110:4728517] is
2015-06-23 17:02:45.442 Mapbox GL[46110:4728517] is
2015-06-23 17:02:45.443 Mapbox GL[46110:4728517] is
2015-06-23 17:02:45.443 Mapbox GL[46110:4728517] is
2015-06-23 17:02:45.539 Mapbox GL[46110:4728517] is
2015-06-23 17:02:45.644 Mapbox GL[46110:4728517] is
2015-06-23 17:02:45.787 Mapbox GL[46110:4728517] did
2015-06-23 17:02:46.085 Mapbox GL[46110:4728517] is
2015-06-23 17:02:46.187 Mapbox GL[46110:4728517] is
```

**Comment by friedbunny** [comment]
Tapping on the map also triggers an `isChanging` notification.

**Comment by jfirebaugh** [comment]
@friedbunny, if you're after region change notifications, I think you wanted #1026. This ticket is about rendering notifications.

Now, as far as I can tell, b1 never sent `*RenderingMap` notifications, and b2 sends them but with non-MapKit semantics. @incanus, is this what you meant by regressing?

bab66c150138aa408f53cec53264593866dd073a lays some groundwork and bd901d252df99f23d6a36a9cd32205cba8f33baf rationalizes `*RenderingMap` -- but not in the way we want. I'll probably rename these notifications to `*RenderingFrame` as suggested above, and then work on notifications with the MapKit semantics.

**Comment by jfirebaugh** [comment]
Done in 6532438fe47bca1af690779ffa7292d6f1080d0c.

What remains unimplemented is support for `fullyRendered:NO` -- we currently do not surface tile errors in a way that made this easy to implement, so I'm punting for now.
