### ISSUE TITLE
[core] Polygon Pattern Example corrupt rendering

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#14321]
During testing of the ios-v4.10.0 branch, the Polygon Pattern Examples of https://github.com/mapbox/ios-sdk-examples (both Obj-C/Swift) appear corrupt:

![IMG_0159](https://user-images.githubusercontent.com/3765757/55453963-0057ca00-55ac-11e9-8ec1-8ded87c88a1f.PNG)
![IMG_0158](https://user-images.githubusercontent.com/3765757/55453964-0057ca00-55ac-11e9-8c5a-74f5ade36159.PNG)
![IMG_0157](https://user-images.githubusercontent.com/3765757/55453965-0057ca00-55ac-11e9-9cf3-207d60049526.PNG)

/cc @chloekraw @tmpsantos 

### Configuration:
Xcode 10.2
iPad 3 running iOS 9.3.5
iPhone 5, running iOS 10.3.3

**Comment by julianrex** [comment]
During testing of mojito beta.2: https://github.com/mapbox/gl-internal/issues/1173

**Device:** iPhone 6+
**iOS version:** iOS 12.3. beta

![IMG_5169](https://user-images.githubusercontent.com/3765757/57169342-1e476300-6dd4-11e9-8027-951eac9c3583.PNG)

![ezgif-5-030533f1c759](https://user-images.githubusercontent.com/3765757/57169489-058b7d00-6dd5-11e9-8abe-b024526d7fae.gif)

**Comment by julianrex** [comment]
Wondering if these issues could be related to #14518 & #14423?

/cc @alexshalamov

**Comment by alexshalamov** [comment]
@julianrex I tried with iPhone XR,  iOS 12.1.4, and various simulator versions, cannot reproduce the issue. Will try to reproduce with my old iPhone6.

**Comment by julianrex** [comment]
@alexshalamov Yep, OS version doesn't seem to make a difference, but I've only seen it on older devices - your 6 should display it (if my 6+ has).

**Comment by alexshalamov** [comment]
@julianrex I spent some time bisecting issue, and I'm able to reproduce bug with v4.4.0, did it ever work on iPhone6?

**Comment by julianrex** [comment]
> did it ever work on iPhone6?

I don't know.
