### ISSUE TITLE
textHaloColor doesn't respect opacity

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-native#14329]
A customer reported that when using opacity with textHaloColor, the opacity isn't respected unless the color is black.

 `mbgl::Color` stores premultiplied values, but the UIColor converter doesn't pre-multiply channels. Should be `- (mbgl::Color)mgl_color` instead to achieve the expected rendering result.

cc: @mapbox/maps-ios

**Comment by alexshalamov** [comment]
Here is a diff for `UIColor` => `mbgl::Color` conversion fix, not sure if there are other places where it needs to be fixed.

```objective-c 
- (mbgl::Color)mgl_color
{
    CGFloat r, g, b, a;
    [self getRed:&r green:&g blue:&b alpha:&a];
-    return { (float)r, (float)g, (float)b, (float)a };
+    return { static_cast<float>(r*a), static_cast<float>(g*a), static_cast<float>(b*a), static_cast<float>(a) };
}
```

`UIColor` or `CGColor` represent unpremultiplied color components, while `mbgl::Color` expects premultiplied color components.

It worked for black color, since color components are 0, thus, unpremultiplied and premultiplied values are the same.

**Comment by 1ec5** [comment]
Same deal with NSColor on macOS:

https://github.com/mapbox/mapbox-gl-native/blob/4a36d848cea80af4f61393da545e1196c30d3846/platform/macos/src/NSColor%2BMGLAdditions.mm#L18

**Comment by fabian-guerra** [comment]
@alexshalamov does this means that I will also have to un-premultiply color values when converting from `mbgl::Color` to `UI/NSColor`?

**Comment by alexshalamov** [comment]
@fabian-guerra as far as I understood from dev documentation [cicolor](https://developer.apple.com/documentation/coreimage/cicolor ) [cgcolor](https://developer.apple.com/documentation/coregraphics/cgcolor)
[nscolor](https://developer.apple.com/documentation/appkit/nscolor) expect un-premultiplied color values, so yes, `mbgl::Color` to `UI/NSColor` conversion would require _'un-premiltiplication_'. @1ec5 please correct me if I'm wrong.
