### ISSUE TITLE
allow simultaneous pinch & pan on iOS

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1434]
We lost this with :runner: & :banana:. 

1. Put two fingers on map. 
1. Pan them around. 
1. Also pinch and zoom them. 

The map should always stick to your fingers. 

/cc @1ec5

**Comment by friedbunny** [comment]
I noticed a while back that MapKit disallows panning while pinch-zooming when location tracking is enabled, which feels kind of nice and has the benefit of not disabling tracking by accidentally panning.

If we want to copy this MapKit-like behavior, it could be good to do it in conjunction with this ticket?

**Comment by incanus** [comment]
Per chat we're gonna punt this to b2. @friedbunny We can probably ticket that one off separately on b2 as well.

**Comment by friedbunny** [comment]
As of 3.3.0b1 (and probably v3.2.x, as I seem to recall us addressing this then), the points underneath your fingers do not change while you’re interacting with the map.

**Comment by 1ec5** [comment]
This got fixed in #4427.
