### ISSUE TITLE
implementation 'com.google.firebase:firebase-ads:17.2.0'Joy

### ISSUE THREAD

**Issue by Pricolist5** [mapbox/mapbox-gl-native#14358]
### Steps to reproduce

 1.
 2.
 3.

### Configuration

**Android versions:** 
**Device models:** 
**Mapbox SDK versions:**

**Comment by tobrun** [comment]
@Pricolist5 thank you for reaching out but your issue doesn't contain any data and title contains non mapbox products or products used by any mapbox sdk. Closing
