### ISSUE TITLE
Multiple sources or filter with one source

### ISSUE THREAD

**Issue by sebastienrouif** [mapbox/mapbox-gl-native#14353]
It's more a general question. I want to draw a line with points : 

1. Solution one : 
  - create a source which contains two features a `LineString` with a property "PROPERTY_TYPE" = "LINE" and `Point`s with property "PROPERTY_TYPE" = "POINT". id = "ROUTE_SOURCE_ID"
 - create a `LineLayer` rendering the line `.withFilter(Expression.eq(get("PROPERTY_TYPE"), "LINE"))` linked to "ROUTE_SOURCE_ID"
 - create a `SymbolLayer` rendering the points `.withFilter(Expression.eq(get("PROPERTY_TYPE"), "POINT"))` linked to "ROUTE_SOURCE_ID"
2. Solution two :
 -  create a source which contains a `LineString`,  id = "LINE_SOURCE_ID"
 - create a`LineLayer` rendering the line linked to "LINE_SOURCE_ID"
 - create a source which contains `Point`s id = "POINT_SOURCE_ID"
 - create a `SymbolLayer` rendering the points  linked to "POINT_SOURCE_ID"

is there an optimisation reason to pick one implementation or the other ? I'm inclined to select the first one as I'm representing one route with its line and stops/waypoints.

Thanks for your help

**Comment by tobrun** [comment]
Solution one should work and I believe the filters aren't even needed. Afaik, we won't try to render as symbol from a linestring.
