### ISSUE TITLE
Map Tiles Gone

### ISSUE THREAD

**Issue by AliKhoshraftar** [mapbox/mapbox-gl-native#14359]
Hi, i'm using mapbox v 6.5.0 in android project. i have a problem. sometimes after switch between app pages and go back to main activity that holds mapview, everythings gone and map hides. after along time search i decided to increase mapbox version. of course i have other module in my app and increase mapbox version has side effect; so i prefer to not increase version. by the way help me what am i shoud to do.

update : this is not only depends on switching between views. it will happen when i add much diffrent markers and data on map . sometimes it will be gone and sometimes is ok. so i can't check when it happens exactly . when it happened it will not load map tiles , but markers and every annotation is ok . what is wrong ?

**Comment by tobrun** [comment]
Please add either some logging, visual resources showcasing the bug or a minimal reproducible example. Current given explanation isn't really helping us much with reproducing the issue. Next to that 6.5.0 is fairly old, you should be able to bump that to 6.7.2 without having any breaking API changes. Closing this until more information is given that is actionable.
