### ISSUE TITLE
SymbolLayer not updating properly 

### ISSUE THREAD

**Issue by MatheusZickuhr** [mapbox/mapbox-gl-native#14368]
Here is a gif of the problem:

![ezgif-4-56763003c2ce](https://user-images.githubusercontent.com/37124939/55732532-86cc3b80-59f2-11e9-9789-ce3e010780dd.gif)

Should update after adding a point (click), but is updating only after a zoom change.

code:

`public class TriangleSourceLayer implements SourceLayer {

    private GeoJsonSource imgSource;
    private GeoJsonSource lineSource;
    private List<Feature> imgLayerFeatureList = new ArrayList<>();
    private List<Point> lineLayerPointList = new ArrayList<>();
    private int color;
    private final String IMG_SOURCE_ID;
    private final String IMG_LAYER_ID;
    private final String LINE_LAYER_ID;
    private final String LINE_SOURCE_ID;
    private final String TRIANGLE_IMAGE_ID;
    private Context context;

    public TriangleSourceLayer(Context context, int id, Style style, int color) {
        this.context = context;
        IMG_SOURCE_ID = "img-source-" + id;
        IMG_LAYER_ID = "img-layer-id" + id;
        LINE_LAYER_ID = "line-layer-" + id;
        LINE_SOURCE_ID = "line-source-" + id;
        TRIANGLE_IMAGE_ID = "triangle-image-" + id;
        this.color = color;
        this.imgSource = this.initImgSource(style);
        this.lineSource = this.initLineSource(style);
        this.initLayerIcons(style);
        this.initImgLayer(style);
        this.initLineLayer(style);
    }

    private GeoJsonSource initImgSource(@NonNull Style loadedMapStyle) {
        FeatureCollection imgFeatureCollection = FeatureCollection.fromFeatures(new Feature[]{});
        GeoJsonSource imgGeoJsonSource = new GeoJsonSource(IMG_SOURCE_ID, imgFeatureCollection);
        loadedMapStyle.addSource(imgGeoJsonSource);
        return imgGeoJsonSource;
    }

    private void initImgLayer(@NonNull Style loadedMapStyle) {
        SymbolLayer symbolLayer = new SymbolLayer(IMG_LAYER_ID, IMG_SOURCE_ID);
        symbolLayer.setProperties(iconImage(TRIANGLE_IMAGE_ID), PropertyFactory.iconColor(this.color));
        symbolLayer.setProperties(PropertyFactory.iconIgnorePlacement(true));
        loadedMapStyle.addLayer(symbolLayer);
    }

    private Drawable loadImg(int imageId, int width, int height){
        Drawable dr = this.context.getDrawable(imageId);
        Bitmap bitmap = ((BitmapDrawable) dr).getBitmap();
        Drawable d = new BitmapDrawable(this.context.getResources(), Bitmap.createScaledBitmap(bitmap, width, height, true));
        d.setColorFilter(this.color, PorterDuff.Mode.SRC_ATOP);
        return d;
    }

    private GeoJsonSource initLineSource(@NonNull Style loadedMapStyle) {
        FeatureCollection lineFeatureCollection = FeatureCollection.fromFeatures(new Feature[]{});
        GeoJsonSource lineGeoJsonSource = new GeoJsonSource(LINE_SOURCE_ID, lineFeatureCollection);
        loadedMapStyle.addSource(lineGeoJsonSource);
        return lineGeoJsonSource;
    }

    private void initLineLayer(@NonNull Style loadedMapStyle) {
        LineLayer lineLayer = new LineLayer(LINE_LAYER_ID, LINE_SOURCE_ID);
        lineLayer.setProperties(lineColor(this.color), lineWidth(5f));
        loadedMapStyle.addLayerBelow(lineLayer, IMG_LAYER_ID);
    }

    private void initLayerIcons(@NotNull Style style) {
        style.addImage(TRIANGLE_IMAGE_ID, BitmapUtils.getBitmapFromDrawable(
                this.loadImg(R.drawable.triangle_16x16, 60, 60)));
    }

    public void addPoint(@NotNull LatLng p) {

        Point mapTargetPoint = Point.fromLngLat(p.getLongitude(), p.getLatitude());

        imgLayerFeatureList.add(Feature.fromGeometry(mapTargetPoint));
        if (imgSource != null) {
            imgSource.setGeoJson(FeatureCollection.fromFeatures(imgLayerFeatureList));
        }

        lineLayerPointList.add(mapTargetPoint);

        if (lineSource != null) {
            lineSource.setGeoJson(FeatureCollection.fromFeatures(new Feature[]
                    {Feature.fromGeometry(LineString.fromLngLats(lineLayerPointList))}));
        }

        try {
            System.out.println(new GeoJsonBuilder(lineLayerPointList).getRoot().toString());
        } catch (JSONException e) {
            e.printStackTrace();
        }
    }

    public void clear() {
        imgLayerFeatureList = new ArrayList<>();
        lineLayerPointList = new ArrayList<>();
        if (imgSource != null) {
            imgSource.setGeoJson(FeatureCollection.fromFeatures(new Feature[]{}));
        }
        if (lineSource != null) {
            lineSource.setGeoJson(FeatureCollection.fromFeatures(new Feature[]{}));
        }
    }
}`

**Comment by tobrun** [comment]
@MatheusZickuhr tried reproducing but wasn't able to:

![ezgif com-video-to-gif (56)](https://user-images.githubusercontent.com/2151639/55821377-a8feb000-5afd-11e9-93e6-4492bba2cee8.gif)

To be able to reproduce the exact same situation, would you be able to deliver that triangle resource? and share the used initial camera position? Thank you!

**Comment by MatheusZickuhr** [comment]
The initial camera position is lat: 48.805817 and lng: 2.1161985.

Here is the triangle resource: 

![triangle_16x16](https://user-images.githubusercontent.com/37124939/55823242-b012c780-5ad7-11e9-8999-881d7af16e48.png)

**Comment by tobrun** [comment]
@MatheusZickuhr I have tried reproducing this 2x with the information given but I haven't been able to reproduce. For other issues, please be more thorough in providing context: which SDK version, zoom level of the camera position and the target density of provide resource are all responsible for making this reproducible. 

Closing this as not reproducible, not an issue with v7.3.2
