### ISSUE TITLE
[IOS] I want a blank map

### ISSUE THREAD

**Issue by songyuyang0918** [mapbox/mapbox-gl-native#14363]
Dear developer! Hello! I want to know if the default Style URL is empty. Can the default Style disable its display? Sometimes I want to have a blank map, but I find I can't?

**Comment by friedbunny** [comment]
Hi @songyuyang0918 — thanks for using Mapbox. This repo is for reporting bugs, requesting features, and coordinating work related to the various Mapbox Map SDKs. For help with “how do I” questions, please ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox) or reach out to our excellent [support team](https://www.mapbox.com/contact/support/).
