### ISSUE TITLE
[android] Mapbox.getTelemetry().setDebugLoggingEnabled(true) is ignored

### ISSUE THREAD

**Issue by osana** [mapbox/mapbox-gl-native#14376]
To reproduce:

1) Add 
Mapbox.getTelemetry().setDebugLoggingEnabled(true); 

 to [PerformanceMeasurement Test](https://github.com/mapbox/mapbox-gl-native/blob/37a886570345ea00d705c3cbe58059be33dda130/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/telemetry/PerformanceMeasurementActivity.java) in the TestApp :

![image](https://user-images.githubusercontent.com/32496536/55800318-76bf6500-5aa1-11e9-8dbf-24cb58038fbc.png)

2) Start the Test App, scroll almost to the bottom and start PerformanceMeasurement Test under Telemetry.

By default, the test app is configured to post telemety events to staging endpoint. Observe the following output when performance telemetry events are posted
![image](https://user-images.githubusercontent.com/32496536/55800037-c18cad00-5aa0-11e9-8644-11152f6e2c68.png)

3) Switch to production telemetry events endpoint by removing the following metadata from Android:

<meta-data
           android:name=“com.mapbox.TestEventsServer”
           android:value=“api-events-staging.tilestream.net” />
<meta-data android:name=“com.mapbox.TestEventsAccessToken” ../>

Notice that there is no logging as there was in 2)

4) It is possible to add TelemetryListener to MapboxTelemetry  locally by doing the following:
![image](https://user-images.githubusercontent.com/32496536/55800794-83908880-5aa2-11e9-9283-73d248e905bc.png)

Rerun the test and notice that Events are being posted because we get a successful response code (but there is no logging output).
![](https://paper-attachments.dropbox.com/s_BC3AA0943B3321C63B9740BFB8F539AC8A9ABEC173C3EFC941D4645FF45E7830_1554787685690_image.png)

**Comment by osana** [comment]
The issue is actually in mapbox-events-android:
https://github.com/mapbox/mapbox-events-android/issues/382
cc @andrlee @tobrun

**Comment by tobrun** [comment]
Considering this isn't actionable fort this repo, closing.
