### ISSUE TITLE
Custom layer hides symbols of standard street layer.

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#14382]
**Platform:** Android, iOS
**Mapbox SDK version:** Android sdk 7.2.0, iOS sdk 4.9.0 (not reproduced 3.7.5)

### Steps to trigger behavior

Create custom layer and source. 

### Expected behavior
Custom layer does not effect for street layer

### Actual behavior
Street name hides if custom layer symbols overlap them:
https://drive.google.com/open?id=1FzRHz73fReQ3t0PvDjHzufZ6lLM-9Gzh

**Comment by tobrun** [comment]
@klblk thank you for reaching out and reporting your issue. Before trying to reproduce. Could you add so more code/context on how you are setting up your symbol layer? Do you have [`iconIgnorePlacement`](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-icon-ignore-placement) enabled?

**Comment by klblk** [comment]
iconIgnorePlacement and textIgnorePlacement help me. Thanks @tobrun. Previously worked without this properties.
