### ISSUE TITLE
[iOS] location indicator wiggling when panning

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1439]
When panning, the location indicator is still wiggling quite a bit: http://take.ms/82O2K

**Comment by incanus** [comment]
Covered by the umbrella https://github.com/mapbox/mapbox-gl-native/issues/1125.

**Comment by 1ec5** [comment]
I've noticed that the wiggling gets worse the farther the dot gets from the screen origin; it's real smooth at the upper-left corner of the screen.

**Comment by kkaefer** [comment]
@1ec5 I can't find a difference in the amount of wiggling.
