### ISSUE TITLE
Unable to localize labels

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#14393]
As of 82b5d8e5c7c4801391cec0e52bfd7513b8a6ad6d, `-[MGLStyle localizeLabelsIntoLocale:]` no longer localizes labels to any locale in Streets style v10 or v11 or similar styles. For example, this line never gets called:

https://github.com/mapbox/mapbox-gl-native/blob/82b5d8e5c7c4801391cec0e52bfd7513b8a6ad6d/platform/darwin/src/MGLStyle.mm#L594

This method worked fine in macOS map SDK v0.10.0 against Streets style v10. (That version predates the v11 styles.)

/cc @mapbox/maps-ios

**Comment by friedbunny** [comment]
Given that we’ve been cherry-picking almost every change into the as-yet unreleased `ios-v4.10.0` branch (`release-liquid`), there’s a very significant chance this is broken there, too.

@1ec5 from this issue it’s not clear to me if this has been confirmed to be broken in our iOS releases — have you done any testing around that? If this is present in `ios-v4.10.0`, we’ll want to prioritize a fix.

**Comment by julianrex** [comment]
Is there (or can we) add a test for this?
