### ISSUE TITLE
Offline download is not restarted when connectivity is re-enabled

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#14396]
Currently, the `ConnectivityReceiver` is activated in 2 points in time:
- the `MapView` is inflated
- the `OfflineRegion` is created.

However, if there's no connectivity when the offline region download is set to active, and the `MapView` is not present, there's no mechanism to inform the offline download once the internet connection is re-established. This can lead to an offline download being "stuck", even though there's a connection to the internet.

**Comment by tobrun** [comment]
Thank you for tracking this down!
