### ISSUE TITLE
Flickering SymbolLayer when changing source data

### ISSUE THREAD

**Issue by xzq2325** [mapbox/mapbox-gl-native#14407]
Platform: iOS
Mapbox SDK version: 4.9.0

Steps to trigger behavior
1、We add a symbolLayer on the map.
2、Timely change source data
 We see the symbolLayer disappearing and reappearing quickly, which produces a kind of flickering .

**Comment by julianrex** [comment]
Thanks for the report @xzq2325 - can you provide a sample project that demonstrates this issue?

Also, can you explain what

> Timely change source data 

means? When and how are you changing the source data?

**Comment by xzq2325** [comment]
Thank you for your response, I just run the code again and found it work normally. 
this is demo code. And I have a new problem, can i provide my indoor location infomation to SDK, look likes "mapView.setLocation(indoor.location)"?
`

    @objc func onTest() {
        print("press test button");
        if timer == nil {
            self.timer = Timer.scheduledTimer(timeInterval: 0.1, target: self, selector: #selector(changeLocation), userInfo: nil, repeats: true)
            self.timer?.fire()
            return;
        }
        
        self.timer?.invalidate();
        self.timer = nil;
    }
    
    @objc func changeLocation() {
        print("changeLocation");
        let old = self.location;
        self.location = CLLocationCoordinate2DMake(old.latitude + 0.000001, old.longitude + 0.000001);
        
        
        let coordinates = [self.location];
        
        let shape = MGLPointCollection.init(coordinates: coordinates, count: UInt(coordinates.count));
        
        var source = self.mapView.style?.source(withIdentifier: "symbol") as? MGLShapeSource;
        if source == nil {
            source = try? MGLShapeSource.init(identifier: "symbol", shape: shape, options: nil)
        
            self.mapView.style?.addSource(source!);
        } else {
            source?.shape = shape;
        }
        
        let oldLayer = self.mapView.style?.layer(withIdentifier: "symbol");
        if oldLayer == nil {
            let layer = MGLSymbolStyleLayer.init(identifier: "symbol", source: source!);
            layer.iconImageName = NSExpression.init(forConstantValue: "airport-15");
            layer.iconAllowsOverlap = NSExpression.init(forConstantValue: true);
            layer.iconIgnoresPlacement = NSExpression.init(forConstantValue: true);
            self.mapView.style?.addLayer(layer);
        }
    }
`

**Comment by julianrex** [comment]
@pozdnyakov will https://github.com/mapbox/mapbox-gl-native/pull/15112 fix this?
