### ISSUE TITLE
Test Offline APIs

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#14400]
We should greatly increase test coverage of our Android offline APIs and refactor the classes to be testable if needed.

**Comment by tobrun** [comment]
We have a simple offline test was added in https://github.com/mapbox/mapbox-gl-native/pull/15058. 
What is left to close this issue?

**Comment by LukasPaczos** [comment]
#15058 is more of a sanity test. I think we should gather popular use-cases like
- pausing/resuming/stopping a download
- setting the region on the map (displaying it)
- region removal
- metadata change
- more?
and cover those in instrumentation tests as well.
