### ISSUE TITLE
(Android - MapBox 7.3.1) queryRenderedFeatures not working properly anymore

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#14422]
After updating from 7.3.0 to 7.3.1, it seems like the queryRenderedFeatures function is broken when resuming a fragment. The method is only returning 0 after stopping and resuming a fragment that holds the mapview. When using 7.3.0 everything worked fine. I assume that https://github.com/mapbox/mapbox-gl-native/pull/14395 broke the whole implementation for fragments.

### Configuration

**Android versions:** all
**Device models:** all
**Mapbox SDK versions:** 7.3.1

**Comment by Guardiola31337** [comment]
We've also noticed this downstream https://github.com/mapbox/mapbox-navigation-android/issues/1886

Will test https://github.com/mapbox/mapbox-gl-native/pull/14426 with a `SNAPSHOT` downstream when it lands into `master`.
