### ISSUE TITLE
(Android - MapBox 7.3.1) Can't set transparent color for linelayer

### ISSUE THREAD

**Issue by darcheville** [mapbox/mapbox-gl-native#14433]
Hello,

i can't query feature when i set transparent color for linelayer, whereas it works with blue, dark and red color ....
`List<Feature> = mapboxMap.queryRenderedFeatures(pointTouchedByUser, myLayerId)`

Can you help me ?
Thanks and regards

**Comment by tobrun** [comment]
I fear this is expected behavior, I could be wrong but I believe that if something isn't going to be drawn it will get optimized away and as result removing it from the query results.

**Comment by darcheville** [comment]
PropertyFactory.lineOpacity(0.000001f) do the job ;)
