### ISSUE TITLE
After upgrading to 7.3.1 symbol not draggable after onPause/onResume

### ISSUE THREAD

**Issue by androideveloper** [mapbox/mapbox-gl-native#14446]
After upgrading from 7.3.0 to 7.3.1 we experience this issue:
1. Add `symbol `and make it `draggable` 
2. Lock screen
3. Unlock screen
4. Pin `not draggable`

Seems to be related to https://github.com/mapbox/mapbox-gl-native/issues/14422 and https://github.com/mapbox/mapbox-gl-native/pull/14395

### Configuration

**Android versions:** all
**Device models:** all
**Mapbox SDK versions:** 7.3.1

**Comment by tobrun** [comment]
As indicated, this is #14422. Closing as duplicate.
