### ISSUE TITLE
Expand SchemaTest

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#14459]
Capturing from https://github.com/mapbox/mapbox-gl-native/pull/14309#discussion_r276597533:
> Can we expand SchemaTest.java to support all events we have in https://github.com/mapbox/mapbox-gl-native/tree/37d17dc2b986c587f06499265f34b49b8bc78f6f/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/telemetry, not all are being tested atm.

/cc @tobrun @Chaoba

**Comment by Chaoba** [comment]
@LukasPaczos Thanks, I will address this issue.
