### ISSUE TITLE
[IOS]About the WFS

### ISSUE THREAD

**Issue by songyuyang0918** [mapbox/mapbox-gl-native#14457]
Dear development team, hello!
I have a need right now:
A WFS data source, I want to generate its elements directly on IOS, and I can get the elements of the click through the click event. I looked for some official documents, but did not get the answer I wanted.
Does the IOS SDK support WFS? If so, can you provide a link to relevant documents?
If not, are there plug-ins available?
Thank you very much!

**Comment by 1ec5** [comment]
I assume you’re referring to the [Web Feature Service](https://en.wikipedia.org/wiki/Web_Feature_Service) standard. No, the Mapbox Maps SDK doesn’t currently support this standard by default on any platform. However, it may be possible to build third-party support for this standard, taking advantage of the SDK’s built-in runtime styling API.
