### ISSUE TITLE
[Android] queryRenderedFeatures(RectF,LAYERID) works incorrect

### ISSUE THREAD

**Issue by Hassan-Fa** [mapbox/mapbox-gl-native#14468]
Hey there!

been using querySourceFeatures with LatLng to query features and works with no problem
but tried it with a RectF and noticed somethings

this link contains an example that is incorrect as new RectF don't accept PonitF as parameter :
https://docs.mapbox.com/android/maps/overview/query/

and this one uses pixels on device screen as parameters but then again RectF don't accept x,y coors : 
https://github.com/mapbox/mapbox-android-demo/issues/305

and i used latitude and longitude for left top right and bottom for inititializing this rectF , but querySourceFeatures method returns empty featureList where there's features visible on screen (that clicking on them and calling querySourceFeatures with screenPoint gets the feature correctly)

am i doing sth wrong ?

**Comment by Hassan-Fa** [comment]
found the problem

first link is incorrect , no changes there

but i got confused because of that and didn't pay attention to the fact that rectF is not map coors and is screen x,ys

so did it this way :

`
// get pointF of them
PointF trPointF =   getMapboxMap().getProjection().toScreenLocation(topRightLatLng);
PointF blPointF =   getMapboxMap().getProjection().toScreenLocation(BottomLeftLatLng);

RectF r = new RectF(blPointF.x,trPointF.y,trPointF.x,blPointF.y);

List<Feature> features = getMapboxMap().queryRenderedFeatures(r, LAYER_ID);
`

**Comment by tobrun** [comment]
Great you figured it out @Hassan-Fa ! Closing as resolved.
