### ISSUE TITLE
[Question] - PBF download

### ISSUE THREAD

**Issue by lhorus** [mapbox/mapbox-gl-native#14475]
Hi guys,

Sorry for the apparently random question, but I've been looking at OfflineManager - and its components - and as far as I cal tell, it is meant for downloading packs based on coordinates. Is there a similar component suitable for downloading a .pbf from an external source? My guess is, using transform to modify the FileSource won't be enough to achieve this.

**Comment by tobrun** [comment]
> downloading a .pbf from an external source

if this external source meets the [vector style specification](https://www.mapbox.com/developers/vector-tiles/), you should be able to add it to your style definition as a [vector source](https://docs.mapbox.com/mapbox-gl-js/style-spec/#sources-vector) so it can be requested when needed.
