### ISSUE TITLE
[Android] symbolLayer causes crash when adding 50,000+ markers

### ISSUE THREAD

**Issue by Hassan-Fa** [mapbox/mapbox-gl-native#14472]
Hi there

i'm currently adding 10,000+ markers and everything in the background and using only one layer , but app freezes on setting source and layer on map , and in some devices app crashes with no stackTrace :

```
List<Feature> coordinates = new ArrayList<>();
for(){
...
coordinates.add(Feature.fromGeometry(
  Point.fromLngLat( Lng , Lat )
  , jsonObject
   ,Id
 ));
...
}


 geoJsonSource = new GeoJsonSource("layerid", mainActivityInterface.getYoungFeatureCollection(),new GeoJsonOptions().withMinZoom((int) minZoom));
 MainActivity.getMapboxMap().addSource(geoJsonSource);


 MainActivity.getMapboxMap().addLayer(markers);

```

is there any way to avoid this ?
any tricks ?
multiple layers ?
only thing coming to mind is adding 1000 in each 5 second .
should i do it or there's a better way ?

**Comment by tobrun** [comment]
@Hassan-Fa 

There are some pointers we can give on GeoJsonSource performance but I feel your use-case should be handled differently. Showing this amount of data at the scale you are requesting, it's better to tile your data, this means you only load data currently shown in your viewport. For example if you are looking and zoomed in at New York City, it wouldn't make much sense "loading data" from London. To do this you need optimise your style in mapbox studio and use our upload api's to tile your data. 

Closing as this issue as answered, the scale limitations is a work as designed at this scale.
