### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR) -> libmapbox-gl.so

### ISSUE THREAD

**Issue by whind** [mapbox/mapbox-gl-native#14479]
In Google Play in ANR and crash tabs frequently appears errors like:
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR) -> libmapbox-gl.so
backtrace:
  #00  pc 00000000000eafd8  /data/app/com.test.test-C8yAhyWr-15hDAhvOubaHQ==/lib/arm64/libmapbox-gl.so
  #01  pc 00000000000eadb0  /data/app/com.test.test-C8yAhyWr-15hDAhvOubaHQ==/lib/arm64/libmapbox-gl.so
  #02  pc 00000000000da11c  /data/app/com.test.test-C8yAhyWr-15hDAhvOubaHQ==/lib/arm64/libmapbox-gl.so
  #03  pc 00000000001a32bc  /data/app/com.test.test-C8yAhyWr-15hDAhvOubaHQ==/lib/arm64/libmapbox-gl.so
  #04  pc 000000000008e380  /data/app/com.test.test-C8yAhyWr-15hDAhvOubaHQ==/lib/arm64/libmapbox-gl.so
  #05  pc 000000000003a2f4  /data/app/com.test.test-C8yAhyWr-15hDAhvOubaHQ==/lib/arm64/libmapbox-gl.so
  #06  pc 000000000002109c  /data/app/com.test.test-C8yAhyWr-15hDAhvOubaHQ==/oat/arm64/base.odex

backtrace:
  #00  pc 000000000008bbd2  /data/app/com.test.test-EIPC6TPkUZKC1GCmHsOIqg==/lib/arm/libmapbox-gl.so
  #01  pc 0000000000051c17  /data/app/com.test.test-EIPC6TPkUZKC1GCmHsOIqg==/lib/arm/libmapbox-gl.so
  #02  pc 000000000001ad13  /data/app/com.test.test-EIPC6TPkUZKC1GCmHsOIqg==/lib/arm/libmapbox-gl.so
  #03  pc 0000000000021063  /data/app/com.test.test-EIPC6TPkUZKC1GCmHsOIqg==/oat/arm/base.odex

### Steps to reproduce

 1.Open map, walking on other Activity, and back to MapActivity

### Expected behavior

All working without crashes

### Actual behavior

Sometimes crash.

### Configuration

**Android versions: Android 8.1, Android 8.0
**Device models: ZTE ZTE BLADE V0920 (P840F03), Samsung Galaxy J6
**Mapbox SDK versions: mapbox-android-sdk:7.3.0, mapbox-sdk-services:4.5.0, mapbox-android-plugin-annotation-v7:0.5.0

**Comment by tobrun** [comment]
@whind I'm confident that this specific crash is fixed with v7.3.2, would you be able to retest/update to this version? Please reach out if you hit any other issues. Closing as resolved.

**Comment by bsterry** [comment]
I am getting the same error with v7.3.2 from two users both running Android 9, one using a Pixel 3 (blueline) and the other a Nokia 6.1 (PL2_sprout)

Here is the stack trace from the Play Store:

backtrace:
  #00  pc 00000000000d7ed4  /data/app/com.cairnapp.cairn-sG3r6SL1h51Zo9IiGpLLrQ==/lib/arm64/libmapbox-gl.so
  #01  pc 000000000008e4d4  /data/app/com.cairnapp.cairn-sG3r6SL1h51Zo9IiGpLLrQ==/lib/arm64/libmapbox-gl.so
  #02  pc 000000000003a448  /data/app/com.cairnapp.cairn-sG3r6SL1h51Zo9IiGpLLrQ==/lib/arm64/libmapbox-gl.so
  #03  pc 00000000000ec09c  /data/app/com.cairnapp.cairn-sG3r6SL1h51Zo9IiGpLLrQ==/oat/arm64/base.odex (com.mapbox.mapboxsdk.maps.renderer.MapRendererRunnable.nativeInitialize [DEDUPED]+124)
  #04  pc 0000000000a96750  /system/framework/arm64/boot-framework.oat (android.opengl.GLSurfaceView$GLThread.guardedRun+2512)
  #05  pc 0000000000a97c90  /system/framework/arm64/boot-framework.oat (android.opengl.GLSurfaceView$GLThread.run+224)
  #06  pc 0000000000545b88  /system/lib64/libart.so (art_quick_invoke_stub+584)
  #07  pc 00000000000cf698  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
  #08  pc 000000000044f524  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
  #09  pc 00000000004505f0  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+424)
  #10  pc 000000000047ae10  /system/lib64/libart.so (art::Thread::CreateCallback(void*)+1260)
  #11  pc 00000000000821e0  /system/lib64/libc.so (__pthread_start(void*)+36)
  #12  pc 0000000000023178  /system/lib64/libc.so (__start_thread+68)
