### ISSUE TITLE
Unable to load vector tiles from a local tileserver php instance

### ISSUE THREAD

**Issue by ramachandranrishi** [mapbox/mapbox-gl-native#14495]
I have a deployed the tileserver php in my local machine and i am trying to load tiles from that server using the android mapbox sdk. Lets say that the ip of my machine is 192.168.1.9.

 I assumed that i could use the json response from http://localhost/tileserver/tileserver.php?/india.json
as the json style with
mapboxMap.setStyle(Style.Builder().fromUrl("http://192.168.1.9/tileserver.php/index.json"))

but i am getting this error "Failed to parse style: style must be an object"

I then moved on to create my own json file with no succes, here is my json file

{
  "version": 8,
  "sources": {
    "simple-tiles": {
      "type": "vector",
      "url": "http://192.168.1.9/tileserver.php?/index.json?/india/{z}/{x}/{y}.pbf",
      "tileSize": 256
    }
  },
  "layers": [
    {
      "id": "simple-tiles",
      "type": "vector",
      "source": "simple-tiles"
    }
  ]
}

but this json is giving me another error
"Failed to load source simple-tiles: Invalid value. at offset 0"

But that is also giving me the same error. What am i missing here?

**Comment by tobrun** [comment]
@ramachandranrishi this repository is for either requesting feature or reporting bugs not for providing/requesting support. Feel free to re-ask your question either on stackoverflow or reach out to us through our support channels [here](https://www.mapbox.com/contact/).

That said, glancing your style json definition there is no layer type called vector.
