### ISSUE TITLE
Roundabout not closed

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#1450]
I found this while testing the glyph loading in a map in Taipei. Apparently the last point is not being rendered. mapbox-gl-js is rendering this fine: https://www.mapbox.com/bites/00108/#18.04/25.03877/-238.48198

![taipei-mbgl](https://cloud.githubusercontent.com/assets/996307/7504215/23dbc79e-f451-11e4-875b-36267bf24674.png)
*Mapbox GL Native*

![taipei-osm](https://cloud.githubusercontent.com/assets/996307/7504216/23de3d62-f451-11e4-9f2f-b27abcddd688.png)
*OSM*

**Comment by 1ec5** [comment]
Reproduces on iOS.

**Comment by mb12** [comment]
We also need to make sure that both are using the same sources/input pbf files for rendering.  If OSM screenshot uses a different source, it could be a data bug as well.

**Comment by friedbunny** [comment]
Noticed this myself recently, too, [with a less complicated circle](https://www.mapbox.com/bites/00116/?style=nicki.d51cce27&access_token=pk.eyJ1Ijoibmlja2kiLCJhIjoiczVvbFlXQSJ9.1Gegt3V_MTupW6wfjxq2QA#18.61/45.51406/-122.97590).

![screen-shot-2015-05-06-at-2 46 01-pm](https://cloud.githubusercontent.com/assets/1198851/7504474/4a8e819e-f3ff-11e4-85bd-48283935dc95.png)

**Comment by 1ec5** [comment]
@mb12 Both gl-js and gl-native are rendering from the latest Mapbox Streets data, which is based on OSM. [The way on OSM](https://www.openstreetmap.org/way/198725737) is closed.

**Comment by 1ec5** [comment]
> I don’t see problems rendering other roundabouts.

Correction: I wasn’t seeing this issue with cul-de-sacs where the way loops in on itself, but that’s a different geometry than the roundabouts pictured here.
