### ISSUE TITLE
Some layers don't render after panning

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#14523]
When panning and zooming, I observe that the forest-y layer sometimes doesn't render correctly in some tiles. When panning around some more, it reappears, so it doesn't look like a data problem of that particular tile. I've been observing those missing layers/tiles in random areas around the world.

![image](https://user-images.githubusercontent.com/52399/56813923-4c5dfd80-683e-11e9-9820-5a02eb99f859.png)

I don't know of a reliable way to reproduce this. What I'm doing is randomly zooming in/out and panning around a bit. It usually manifests itself pretty quickly (less than a minute) of zooming.

I've been able to bisect it to https://github.com/mapbox/mapbox-gl-native/commit/8faf47ab5edcbdf6a72e10c57320f72fdec8fbf8 /cc @pozdnyakov

**Comment by pozdnyakov** [comment]
cc @tobrun @julianrex
