### ISSUE TITLE
Break camera tracking with external animation

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#14538]
Currently, whenever camera tracking is engaged, programmatically invoking standard animation clashes with the tracking animation in an unexpected way. We should instead break the tracking whenever this situation occurs. Users can listen for that event with the `OnCameraTrackingChangedListener` in more complex setups.

@mapbox/navigation-android any thoughts on this?

**Comment by danesfeder** [comment]
> We should instead break the tracking whenever this situation occurs.

@LukasPaczos I agree with this.  We have had developers run into this same issue while integrating our UI components.  We have added APIs to our UI map component that enforces the behavior that you've outline in this ticket https://github.com/mapbox/mapbox-navigation-android/pull/1849
