### ISSUE TITLE
Map is dimed when mapbox is used inside dialog fragment

### ISSUE THREAD

**Issue by androideveloper** [mapbox/mapbox-gl-native#14537]
When map is used inside DialogFragment,  on some Android versions(<8.0) map is dimed. The sample I have created is using SupportMapFragment inside DialogFragment.

### Steps to reproduce

[Mapdox Dim Demo](
https://www.dropbox.com/s/3kuxe4orcc2hbfk/MapboxDialogDimDemo.zip?dl=0) (insert your map key in strings.xml)
 1. Open this sample app
 2. Click on button, map dialog is opened
 3. If you are on Android < 8.0, map inside the dialog is dimed.

### Expected behavior
The same UI on all Android versions

### Actual behavior
Dimed map on some Android versions

![dialog_dim_issue](https://user-images.githubusercontent.com/1249919/56896887-2040b780-6a9e-11e9-84e8-1ee474a17849.jpg)

### Configuration

**Android versions:** 9.0, 8.1, 7.0
**Device models:** Xiaomi mi a2 lite, Android sdk emulator with Android 7.0
**Mapbox SDK versions:** v7.3.2

**Comment by tobrun** [comment]
For this use-case you will need to use a `TextureView` as the OS draws an overlay on top of window. While the surface used by `GLSuraceView` is behind it. You can enable this option with passing `MapboxMapOptions#textureMode(true)` to your `SupportMapFragment.newInstance` call. afaik their isn't a fix we can do to work around this dialog behavior for `GLSurfaceView`. Closing as answered.

**Comment by androideveloper** [comment]
How is the performance compared to `GLSuraceView`? Can we use it as default mode?

**Comment by tobrun** [comment]
Yes sure, please let us know if you are having any issues with it!
