### ISSUE TITLE
Storage not cleared when deleting an OfflineRegion

### ISSUE THREAD

**Issue by diegomedina248** [mapbox/mapbox-gl-native#14549]
### Steps to reproduce

When deleting an `OfflineRegion`, the storage is not cleared.
If you open the App Info, the space used remains the same.
Does the delete method from the `OfflineRegion` clear the storage allocated for that?

Tested in the Mapbox Demo app.
To reproduce, download a large offline region (50MB or up), as I'm not sure if it happens for small offline region definitions.

No other regions were downloaded, just this single one.

### Expected behavior

The storage used by the `OfflineRegion` region to be cleared

### Actual behavior

The storage is not cleared

### Configuration

**Android versions:** 8 / 9
**Device models:** Galaxy S8 / Any Emulator
**Mapbox SDK versions:** checked on 7.2.0 and up

**Comment by tobrun** [comment]
Thank you for reaching out and reporting this issue. Was able to reproduce:

After region download:
![image](https://user-images.githubusercontent.com/2151639/57217601-5c6e9d80-6ff3-11e9-958e-33797e9b2b2e.png)


After region delete:
![image](https://user-images.githubusercontent.com/2151639/57217690-98096780-6ff3-11e9-85c2-bedc966f90b9.png)

**Comment by diegomedina248** [comment]
Hey @tobrun, thanks for answering back.
The ideal would be that this delete also cleared the downloaded tiles & other resources used exclusively by this region.
Otherwise, there's no way to delete this data from the app unless clearing the whole storage or deleting/reinstalling the app.

**Comment by tmpsantos** [comment]
Removing an offline region currently makes the tiles of this region part of the "ambient cache". After that, we remove the "excess tiles". The ambient cache size is currently 50 MB, so if the tiles from the offline region fit on the ambient cache, the size of the database will remain practically the same.

**Comment by tobrun** [comment]
Capturing from @tmpsantos that this is work as designed, you can remove the db itself which would result in expected behavior. We are currently working on an API to clear the ambient cache in https://github.com/mapbox/mapbox-gl-native/issues/12781. Closing as work-as-designed with future improvements coming.

**Comment by diegomedina248** [comment]
Makes sense. Though, I had offline regions of 400MB that, when deleted, the size of the db remained the same.
Removing the db wouldn't work if I have multiple offline regions stored.

**Comment by tmpsantos** [comment]
@diegomedina248 the clear cache API will probably solve this. One problem will be that SQLite will not shrink in size unless we call [VACUUM](https://www.sqlite.org/draft/lang_vacuum.html) and this call is very expensive.

**Comment by tmpsantos** [comment]
@diegomedina248 will be fixed by https://github.com/mapbox/mapbox-gl-native/pull/14901
