### ISSUE TITLE
Parsing error in Mapbox Streets in San Jose, California

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1454]
I got this parsing error in Mapbox Streets in the latest iOS demo app on master on an iPhone 6 running iOS 8.3:

```
[ERROR] [ParseTile]: Parsing [13/1322/3179] failed: expecting an even number of intersections
```

**Comment by kkaefer** [comment]
>    // TODO fix
        // This could get hit when a point intersects very close to a corner
        // and floating point issues cause only one of the entry or exit to be
        // counted

**Comment by ansis** [comment]
this was fixed by https://github.com/mapbox/mapbox-gl-native/pull/1666
