### ISSUE TITLE
-[MGLVectorTileSource attributionHTMLString] crash in source.cpp

### ISSUE THREAD

**Issue by joshpuente** [mapbox/mapbox-gl-native#14541]
Hey, we've received a crash from our crash reporting tool related to MGLVectorTileSource. 

### Steps to reproduce
Unfortunately, no exact steps for replication. 
iOS gives the generic crash log:
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000010

### Expected behavior
Using this part of the SDK should not crash the app.

### Actual behavior
Using this part of the SDK crashes the app.

### Configuration
**Mapbox SDK versions:** V0.28
**iOS/macOS versions:** iOS 12.0
**Device/simulator models:** iPad device
**Xcode version:**  10.1

Please see attached stack trace logs.
[com.transloc.ondemanddriver_issue_crash_85ca23b1c15a4e13b1d5e2b84965eafb_DNE_0_v2.txt](https://github.com/mapbox/mapbox-gl-native/files/3131364/com.transloc.ondemanddriver_issue_crash_85ca23b1c15a4e13b1d5e2b84965eafb_DNE_0_v2.txt)

```
#0. Crashed: com.apple.main-thread
0  Mapbox                         0x101731108 -[MGLVectorTileSource attributionHTMLString] (source.cpp:27)
1  Mapbox                         0x1017a6a18 -[MGLTileSource attributionInfosWithFontSize:linkColor:] (MGLTileSource.mm:38)
2  Mapbox                         0x1017922ec -[MGLStyle attributionInfosWithFontSize:linkColor:] (MGLStyle.mm:251)
3  Mapbox                         0x101767ea8 -[MGLMapView showAttribution:] (MGLMapView.mm:2310)
4  UIKitCore                      0x1f1456314 -[UIApplication sendAction:to:from:forEvent:] + 96
5  UIKitCore                      0x1f0ee3d54 -[UIControl sendAction:to:forEvent:] + 80
6  UIKitCore                      0x1f0ee4074 -[UIControl _sendActionsForEvents:withEvent:] + 440
7  UIKitCore                      0x1f0ee3074 -[UIControl touchesEnded:withEvent:] + 568
8  UIKitCore                      0x1f106aaf0 _UIGestureEnvironmentSortAndSendDelayedTouches + 4324
9  UIKitCore                      0x1f10657ec _UIGestureEnvironmentUpdate + 1236
10 CoreFoundation                 0x1c48fc6bc __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
11 CoreFoundation                 0x1c48f7350 __CFRunLoopDoObservers + 412
12 CoreFoundation                 0x1c48f78f0 __CFRunLoopRun + 1264
13 CoreFoundation                 0x1c48f70e0 CFRunLoopRunSpecific + 436
14 GraphicsServices               0x1c6b70584 GSEventRunModal + 100
15 UIKitCore                      0x1f1454c00 UIApplicationMain + 212
16 OnDemandDriver                 0x100f9fbac main (<compiler-generated>)
17 libdyld.dylib                  0x1c43b5bb4 start + 4
```

**Comment by friedbunny** [comment]
Hrm, the linked stack trace doesn’t appear to be symbolicated and I don’t see anything related to Mapbox in it.

**Comment by joshpuente** [comment]
Hey @friedbunny, sorry could you give it another shot?

**Comment by friedbunny** [comment]
Thanks, @joshpuente, that trace seems quite informative. Since the crash appears to be happening when trying to parse a source’s attribution information, are you able to say which style this was using?
