### ISSUE TITLE
(MapBox Android) setMaximumFps freezes map scrolling

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#14553]
When using setMaximumFps, I have noticed that the map scroll is freezing and even stopping when the render quality is dropping significantly. Everything else is usable inside the app, but no map scrolling. I even encounter "Application not responding" dialogs from time to time. The main problem is that the scrolling completely stops and mapbox seems not to be able to recover from that.

### Configuration
**Mapbox SDK versions:** 7.4.0-beta.2

**Comment by tobrun** [comment]
@Mordag can you share the value of the paramter used to call `setMaximumFps`. This would help with reproducing your issue. Thank you!

**Comment by Mordag** [comment]
@tobrun I actually was able to reproduce that already without setMaximumFps. I can open a new issue regarding that if you want?

**Comment by LukasPaczos** [comment]
Please do and thanks @Mordag. I'm going to close this one as unrelated.
