### ISSUE TITLE
(MapBox Android) MapBox onStop freezes main thread

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#14554]
I am using a MapView inside a Fragment. I have noticed that switching to a different Activity (and therefore calling the onStop of that Fragment that is called the onStop of the MapView), freezes the main thread for a while. Especially slower phones have quite some troubles with that.

### Configuration

**Android versions:** 7.0, 8.1
**Device models:** Moto G5, Nexus 5, Nexus 5X
**Mapbox SDK versions:** 7.4.0-beta.2

**Comment by Mordag** [comment]
Some additional observations: I have noticed that zooming from a low zoom level (like 1) to a much higher zoom level (like 22) and then switching to a new activity without waiting that the MapView settles or the tiles are being rendered increases the blocking time for the main thread.

**Comment by Mordag** [comment]
I did some more testing and tried out running the MapView in textureMode (app:mapbox_renderTextureMode="true"). I have noticed that in this mode, I have no main thread freezes at all.

**Comment by LukasPaczos** [comment]
> do you think we can safely move the renderer pointer reset to the GL thread?

Of course, this is already happening. What I wanted to ask is does it have to be blocking?

**Comment by tobrun** [comment]
> Of course, this is already happening. What I wanted to ask is does it have to be blocking?

Ideally we do not reset renderer at all and fix the root destructor crash with `LocalGlyphRasterizer`. That said, some manual testing with removing the wait invoke didn't show an issue, we can remove it to make it non blocking.

**Comment by ivovandongen** [comment]
IIRC we block there as to make sure all gl resources are cleaned up before the egl context is destroyed.

**Comment by LukasPaczos** [comment]
This UI thread blocking is especially visible when scrolling in a recycler. Comparison between texture, which is not blocking, and surface:
![ezgif com-video-to-gif (41)](https://user-images.githubusercontent.com/16925074/57938280-2ae5b400-78c8-11e9-9c6d-fcaf9eba9870.gif)
