### ISSUE TITLE
(MapBox Android) Support for Jackson

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#14555]
I have noticed that large parts of the MapBox SDK is using GSON to convert objects. Is there any specific reason why GSON has been selected to do this kind of work? Usually the dataset for map related stuff is probably quite large. I know that Jackson has a much better performance when it comes to deserialising large jsons (we are talking about 4 times faster than GSON: https://medium.com/@dannydamsky99/heres-why-you-probably-shouldn-t-be-using-the-gson-library-in-2018-4bed5698b78b).

**Comment by tobrun** [comment]
@Mordag thank you for reaching out and reporting this! This is definitely on our radar to improve as I feel there is a lot of unnecessary overhead when it comes to our GeoJSON performance (not only speed but also memory consumption). Afaik the GeoJSON part is the only part in the code where we need the performance boost.  

We are tracking this issue in https://github.com/mapbox/mapbox-java/issues/710 and hopefully we can start prioritizing this. I added a comment on using Jackson [here](https://github.com/mapbox/mapbox-java/issues/710#issuecomment-488574635).

Thanks again for reaching out and providing valueable feedback. Closing this as next steps are outlined downstream for the geojson module in mapbox-java.
