### ISSUE TITLE
iOS: Features from -[MGLMapView visibleFeaturesAtPoint:] are read-only on iOS

### ISSUE THREAD

**Issue by racer1988** [mapbox/mapbox-gl-native#14566]
From the docs

```
Note that while it is possible to change this value
on feature instances obtained from -[MGLMapView visibleFeaturesAtPoint:]
and related methods, there will be no effect on the map.
Setting this value can be useful when the feature instance 
is used to initialize an MGLShapeSource and that source is added to the map and styled.
```

I have a `VectorSource` filled with `PointFeature`s.
The Features comes from inside the tiles, they are not added on the client

I would like to change some `attributes` of these features when they are clicked, so that the style can render them differently.

However I can't find any way to edit the attributes on iOS and get them reflected in the source.

Are all sources, layers and features read-only?

What is the suggested way to edit a single feature in a source?

### Configuration

**Mapbox SDK versions:** 4.10

**Comment by 1ec5** [comment]
Unfortunately, modifying the content loaded from vector tiles isn’t supported at this time on any platform. Depending on your use case, one workaround may be to continue to query for that selected feature, modify it in memory, and add the modified feature to the map a separate shape source rendered by an additional style layer. The selected feature’s style layer can be inserted above the unselected features’ style layer, and the selected feature can collide out any unselected features as long as properties such as `MGLSymbolStyleLayer.iconAllowsOverlap` or `iconIgnoresPlacement` are set appropriately.
