### ISSUE TITLE
Deploy to bintray broken

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#14563]
[Example build](https://circleci.com/gh/mapbox/mapbox-gl-native/271089?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

> What went wrong:
Execution failed for task ':artifactoryDeploy'.
> File '/src/platform/android/MapboxGLAndroidSDK/build/outputs/aar/mapbox-android-sdk-release.aar' does not exist, and need to be published from publication MapboxMapsSdkPublication

broken since bumping gradle tools in 33b140863ebed6b5fd06459312f0ceae111b2a63

This needs to be either fixed or reverted to do the v7.5.0-alpha.1 release. 

cc @osana (this doesn't impact doing releases on `release-mojito`)

**Comment by friedbunny** [comment]
@mapbox/maps-ios @mapbox/gl-native if you’re wondering about `android-release` failures on `master`, this is the likely culprit — it’s failed 17 of the last 30 builds.

**Comment by tobrun** [comment]
This has been reverted as part of https://github.com/mapbox/mapbox-gl-native/pull/14569, need to revisit approach taken to resolve https://github.com/mapbox/mapbox-gl-native/issues/14154
