### ISSUE TITLE
Partial tiles constantly being reparsed

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#1458]
When a tile is partially parsed (i.e. it is waiting for more data from the network like glyphs and sprites), we are reparsing it everytime we call `update()`. We should only reparse partial tiles when new glyphs or sprites arrive.

That would avoid the CPU being 100% all the time until everything is downloaded and partial tiles are on the viewport.

**Comment by tmpsantos** [comment]
Setting this to Beta 1 because the performance gain is noticeable.

**Comment by tmpsantos** [comment]
Unfortunately there is a stall on two tests (14 and 50). I can reproduce it here on my laptop only on Debug builds. It is late here and I didn't find the cause, so let's not merge this branch for now.

I will continue from tomorrow morning.

**Comment by springmeyer** [comment]
@tmpsantos :+1:  - hopefully with fresh eyes tomorrow you can solve. Rest well.
