### ISSUE TITLE
High CPU when cycling through layer visibilities (macOS)

### ISSUE THREAD

**Issue by ArturGasparyan** [mapbox/mapbox-gl-native#14588]
Hello everybody,

using the latest mapbox API for macOS, the latest Xcode and the latest macOS I have successfully loaded my custom styled map onto a simple window + view. On it I download radar weather data (WMS, png images) as a MGLImageSource and add it as an MGLRasterStyleLayer to my mapView. To be precise, I download n images (each for a different timestamp, interval 5 minutes) and create n layers (with different names) in order to cycle through them: the goal is an animation of the radar data (similarly or identically to https://docs.mapbox.com/mapbox-gl-js/example/animate-images/).

I use a simple GCD timer setup:

```
func showRadarImages() {
    //increase index, get layer 
    DispatchQueue.main.async {
                
        layer.isVisible = false/true
                
    }

}

let queue = DispatchQueue(label: "radarTimer", attributes: .concurrent)
timer = DispatchSource.makeTimerSource(flags: .strict, queue: queue)
timer.schedule(deadline: .now(), repeating: .milliseconds(delay), leeway: .milliseconds(0))
timer.setEventHandler(handler: { [weak self] in
            
    self?.showRadarImages()
            
})
timer.activate()

```
This works, however I experience a CPU usage of ~100-150 % and my MacBook Pro's fans running high.

Having stripped down the entire code to literally only hide and show a layer inside this "loop" still the CPU increases. Uncommenting this one line (.isVisible = false/true) puts the CPU to peace but so the animation.

Also using a delay of 300 ms and lower doesn't improve the fluency of the animation (so I never actually see a fluent animation).

Before, I tried an NSTimer, which actually worked much smoother (I only had ONE layer and was changing the .image parameter) however it also kicked the CPU up. So I'm looking for a solution which I can let run without a high CPU performance.

Is there a way to improve performance? Or is that simply a limitation of a live rending of a mapbox map with multiple layers that CPU will always be pushed?

I'd appreciate every comment and I'm grateful for every suggestion!

Thank you

**Comment by ArturGasparyan** [comment]
I rewrote the whole code now using a DispatchSourceUserDataAdd and a DispatchSourceTimer. The timer calculates the new image index on the background thread and hands it to the UserDataAdd source. The UserDataAdd source works on the main thread and gets updated as quickly as the GUI can, ignoring all the indeces so far, jumping straight to the newest index (this is all based on https://stackoverflow.com/questions/26743367/updating-the-ui-using-dispatch-async-in-swift).

The result is: it seems to be actually faster, but many images are skipped, because the GUI fails to update as quickly as it would need to... also, CPU still at 150 %.

**Comment by 1ec5** [comment]
> Also, now I'm setting the .image parameter again, having only ONE layer and one source.

This would seem like the right approach in general. Just setting `MGLImageSource.image` instead of showing and hiding a pair of layers potentially halves the number of frames being drawn.

Unfortunately, it’s also my experience that anything causing MGLMapView to continuously render causes significant CPU and power usage. This is essentially the same regression that has affected iOS since 2016: #7236.
