### ISSUE TITLE
Tile doesn't render after zoom 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#14582]
Not sure but think this is a follow up from https://github.com/mapbox/mapbox-gl-native/issues/14523. When testing v7.5.0-alpha.1 of the Android SDK containing https://github.com/mapbox/mapbox-gl-native/pull/14527.

### Before zoom:

> Target: LatLng [latitude=40.723102, longitude=-73.9979, altitude=0.0], Zoom:11.797530889511108, Bearing:14.754321455955505, Tilt:11.962963104248047

![image](https://user-images.githubusercontent.com/2151639/57129224-0cdf6600-6d96-11e9-845f-ee221e32622c.png)

### After zoom:

> Target: LatLng [latitude=40.723102, longitude=-73.9979, altitude=0.0], Zoom:12.32962965965271, Bearing:24.598148703575134, Tilt:19.94444465637207

![image](https://user-images.githubusercontent.com/2151639/57129191-f76a3c00-6d95-11e9-80c6-d09a926cc85f.png)

The tiles in the top aren't loading (the one in the bottom did and is showing more detail). 
fwiw zooming a bit more doesn't load the other tiles. 

cc @pozdnyakov @kkaefer @julianrex

**Comment by tobrun** [comment]
Not able to reproduce this with debug so might be layer related:

![image](https://user-images.githubusercontent.com/2151639/57130408-ae1beb80-6d99-11e9-8972-dc11194b396c.png)

**Comment by tobrun** [comment]
7.3.2 produces:

![image](https://user-images.githubusercontent.com/2151639/57134806-90558300-6da7-11e9-8934-8f589196d392.png)

**Comment by pozdnyakov** [comment]
Below is a screenshot of glfw-app at `android-v7.4.0-alpha.1` (version before #14523 took place)
![Screenshot from 2019-05-03 21-07-21](https://user-images.githubusercontent.com/998253/57158228-91a89f00-6deb-11e9-8c08-f5dd20d09dbf.png)

Could be data problem

**Comment by pozdnyakov** [comment]
![Screenshot from 2019-05-03 21-43-03](https://user-images.githubusercontent.com/998253/57158609-7e4a0380-6dec-11e9-9c6b-834dc11a9062.png)

**Comment by pozdnyakov** [comment]
There is a problem with the style - missing sprite image:`[ERROR] {mbgl-glfw}[Style]: Failed to load sprite: HTTP status code 404`. Missing image is preventing from finalizing loading tiles where this image is used |=> tiles are not rendered.

**Comment by pozdnyakov** [comment]
Reopening as `gl-js` is treating it differently: is still shows tiles even if sprite load failed. 
Such behavior looks to be more user-friendly, so`gl-native` shall take after `gl-js`.

**Comment by kkaefer** [comment]
Ticketed the GL action in https://github.com/mapbox/mapbox-gl-native/issues/14615
