### ISSUE TITLE
Cannot resolve Android Mapbox 7.4.0-beta.3

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#14580]
The latest beta release (7.4.0-beta.3) cannot be resolved. I have noticed that the related bintray folder is empty and has only the maven metadata.

https://bintray.com/mapbox/mapbox/mapbox-android-sdk/7.4.0-beta.3#files/com%2Fmapbox%2Fmapboxsdk%2Fmapbox-android-sdk

### Configuration

**Mapbox SDK versions:** 7.4.0-beta.3

**Comment by tobrun** [comment]
We forgot to press the sync button:

<img width="392" alt="Screenshot 2019-05-03 at 09 04 43" src="https://user-images.githubusercontent.com/2151639/57123583-a13fcd80-6d82-11e9-8b6d-6dba0e5cd1ca.png">

Pressed and release should be available in the coming hours.

cc @osana
