### ISSUE TITLE
I need to do auto clustering on IOS sample

### ISSUE THREAD

**Issue by jbarros35** [mapbox/mapbox-gl-native#14584]
### Steps to reproduce

 1.
 2.
 3.

### Configuration

**Mapbox SDK versions:** 
**iOS/macOS versions:** 
**Device/simulator models:**
**Xcode version:** 

My question is very simple and I'll not take too much time from you guys.
Is that posible to do autoclustering on the IOS sdk or not? I mean I have a bunch of annotations but they won't auto cluster themselves when I do zoom out. How can I achieve that?
Provided samples on the website are useless.
Remember I don't want to see Android stuff, I'm a IOS so I'm expecting a swift code for playing.
By the way this is a paid feature.

**Comment by julianrex** [comment]
@jbarros35 thanks for writing.

This repo is for reporting issues or requesting features related to the Maps SDK for iOS. 
For support or assistance with "how to" questions, please reach out to our support team at 
https://support.mapbox.com.

However, unfortunately clustering is not currently supported when using `MGLAnnotationView` or `MGLAnnotationImage`; it *is supported* with `MGLSymbolStyleLayer` and `MGLCircleStyleLayer`, as documented here: https://docs.mapbox.com/ios/maps/overview/markers-and-annotations/

There's an example that uses both here: https://docs.mapbox.com/ios/maps/examples/clustering/ (EDIT: though I see you've referenced that [here](https://github.com/mapbox/MapboxStatic.swift/issues/93) too).

Marking this issue as answered.

**Comment by jbarros35** [comment]
I seen these sample before, my issue is that I need to update those clusters using a service not a geoJSON file. There is no reason apps having a geoJSON file, there is no value on it because most apps will load positions from a server!
