### ISSUE TITLE
[ios, macos] Consider disabling auto-resizing from underlying GLKView

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#14597]
Resizing `MGLMapView` automatically resizes the `GLKView` and as such will re-create frame-buffers. This results in poor performance noticeable during view bounds animations.

We should consider resizing the view at the start or end of the animation, and cropping the GL view to its parent during the animation.

Some of this work would help to introduce #14596, though neither are dependent on each other.

This is likely part of the solution to #4352.

**Comment by 1ec5** [comment]
> This is likely part of the solution to #4352.

#4352 is implicitly a request for adding implicit animation support to camera-related properties. Maximizing the GLKView during the animation would be a workaround but not really the solution; it would still be just as jarring to see the map contents “freeze” while the ornaments, user puck, view-backed annotations, and callout view resize in unison with the outer map view.
