### ISSUE TITLE
[ios, macos] Delay GL map setup until application is active and parent view is established.

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#14596]
We should delay creation/setup of the underlying GL map until 2 conditions are met:

1. The parent view is at its correct dimensions.

    `commonInit` can be called with the view dimensions as setup in an IBStoryboard, and render can occur at those dimensions before the view layout occurs. This is unlikely to cause issues, since the the map view is set-up with resizing masks, however it's not ideal - for example, it may initially allocate more memory than is strictly necessary, and reduced start-up time as frame buffers are re-created.

2. We should wait until the app is active to create GL views, as mentioned in this comment:

    > If you set up OpenGL drawing in your app delegate's methods, make sure that you only did so in applicationDidBecomeActive:, never in application:willFinishLaunchingWithOptions: or application:didFinishLaunchingWithOptions:. According to some reports, even displaying an FPS indicator for SpriteKit could cause rendering to occur before it is allowed.

    from https://github.com/mapbox/mapbox-gl-native/issues/13824

We'll need to introduce a delegate callback that indicates when the map view is ready - this would be the equivalent of Android's `onMapReady`.

**Comment by julianrex** [comment]
Marking as `SEMVER-MAJOR`, as this would likely be an API change.

**Comment by chloekraw** [comment]
> We'll need to introduce a delegate callback that indicates when the map view is ready - this would be the equivalent of Android's onMapReady.

@julianrex could we decouple adding the delegate callback from the rest of this ticket? I'm thinking that the equivalent of `onMapReady` could be added in a minor version bump, and potentially be used by developers in their implementations to help prevent some crashes and race conditions

**Comment by julianrex** [comment]
Closing as won't-fix/stale.
