### ISSUE TITLE
(MapBox Android) Map camera is freezing

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#14598]
Related to https://github.com/mapbox/mapbox-gl-native/issues/14553. I have noticed that the mapbox camera scrolling gesture is stopping to work after a while. I haven't been able to find reproducible steps but I was able to get into this state a few times already.

Only the camera panning is not working anymore. Zooming, pinching etc is still working as expected.

### Configuration

**Android versions:** 7.0, 8.1
**Device models:** Moto G5, Nexus 5X
**Mapbox SDK versions:** 7.4.0-beta.2

**Comment by LukasPaczos** [comment]
Thanks for cutting the ticket @Mordag. Is there any more information that you'd be able to provide? What are your dependencies? Are there any views that are overlaid on top of the map that can block touch events? Any logs that might point to the root cause?

**Comment by Mordag** [comment]
I have added no new dependencies since 7.2 and I never found any problems regarding scrolling. As I said I am still able to zoom, pinch and rotate the map so I cannot be view related (regarding a possible overlay). I got no logs I could provide you that indicate any issues with scrolling but I will do some more testing tomorrow. Btw. I was able to reproduce that with 7.5.0-alpha.1 as well.

**Comment by LukasPaczos** [comment]
Thanks @Mordag. Please keep us posted while we test on our side as well.

**Comment by Mordag** [comment]
@LukasPaczos I did some more testing and was able to reproduce this issue on a Samsung A5 as well. I tried to analyse the logs but there's nothing helpful. But I have noticed a few lines that might be related to this issue? I'm not certain..

> 2019-05-10 12:54:39.575 3065-3176/? D/InputReader: Input event(3): value=0 when=12180126039000
> 2019-05-10 12:54:39.575 3065-3176/? I/InputReader: Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=12180126039000
> 2019-05-10 12:54:39.575 3065-3175/? I/InputDispatcher: Delivering touch to (6661): action: 0x1, toolType: 1

These lines are printed quite a lot during the freezing state. As I said, zooming, rotating and all other app feature are still working fine - only the camera scrolling is not reacting.

**Comment by JRWilding** [comment]
Steps to reliably reproduce this:

1. Double tap the map
2. Hold your finger down on the 2nd tap
3. Before the timeout for a long press event, perform a swipe with a different finger

This starts a "quick scale gesture" and/or a rotation gesture but somehow breaks the standard gesture detector for panning.

From what I could tell, `mLastFocusX` and `mLastFocusY` in `GestureDetector` are updated with the move touch event's x/y before it calculates the amount to scroll so `scrollX= mLastFocusX - focusX`, is always 0.
I assume this means that the same instance of `GestureDetector` is being used twice somehow.

**Comment by LukasPaczos** [comment]
Thanks @JRWilding, I was able to reproduce.

**Comment by Mordag** [comment]
@LukasPaczos Would it be possible to fix this issue for the upcoming mapbox release?

**Comment by LukasPaczos** [comment]
The move gesture is blocked because we never receive the `ACTION_UP` event from the `StandardOnGestureListener#onDoubleTapEvent`, which should re-enable the move detector. Capturing from the compat library's source code:
```
        case MotionEvent.ACTION_UP:
            mStillDown = false;
            MotionEvent currentUpEvent = MotionEvent.obtain(ev);
            if (mIsDoubleTapping) {
                // Finally, give the up event of the double-tap
                handled |= mDoubleTapListener.onDoubleTapEvent(ev);
            }
```

while the `mIsDoubleTapping` is set to `false` whenever another pointer is placed (`ACTION_POINTER_DOWN`, doesn't have to be a swipe), or the `ACTION_CANCEL` is dispatched. This looks like a bug to me that we get no information that the double tap has been canceled.

https://github.com/mapbox/mapbox-gl-native/pull/14965 makes sure to re-enable the move detector.

**Comment by LukasPaczos** [comment]
@Mordag we are evaluating whether we can CP https://github.com/mapbox/mapbox-gl-native/pull/14965 to the release branch. If not, it's going to be available in a stable release next month.

**Comment by LukasPaczos** [comment]
@JRWilding @Mordag https://github.com/mapbox/mapbox-gl-native/pull/14965 has been merged, would you be able to retest with the [`8.2.0-SNAPSHOT`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/README.md#using-the-sdk-snapshot)?
