### ISSUE TITLE
Use the defaultStyles constant on Android apps

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#1462]
The MacOS and Linux app are now using the defaultStyles as the list of styles we can select from. The iOS and Android apps should use the same list.

defaultStyles was added at https://github.com/mapbox/mapbox-gl-native/pull/1443

/cc @incanus

**Comment by jfirebaugh** [comment]
`default_styles.hpp` should be a header in `include/mbgl/platform` so it can be included via `#include <mbgl/platform/default_styles.hpp>`. There shouldn't be relative includes [like this](https://github.com/mapbox/mapbox-gl-native/blob/606e2c738321682730833d2fe329f981b6e22b6e/linux/main.cpp#L2-2) in the test/sample apps.

**Comment by kkaefer** [comment]
> There shouldn't be relative includes like this in the test/sample apps.

Why not? My reason for not moving it into the `include/mbgl/platform` is that it's technically not part of the library.

**Comment by jfirebaugh** [comment]
I think it should be considered part of the library. If a third-party wanted to build an app with style-switching functionality, they should `#include <mbgl/platform/default_styles.hpp>` and then use it.

**Comment by kkaefer** [comment]
The bundled styles aren't technically part of the library either; they're just there because we package them with the apps.

**Comment by incanus** [comment]
They _are_ part of the library on iOS — we package a `MapboxGL.bundle` with the static library and headers which contains resources like the compass image and Mapbox logo as well as the included styles. It's a first-class part of the library. Currently we recommend users [query for the included styles with an API call](https://www.mapbox.com/mapbox-gl-ios/#map_style_changes), which we hook up by [iterating the filesystem directly](https://github.com/mapbox/mapbox-gl-native/blob/4798c502aa2a8c5e5c18193e1a221a8a371f36ab/platform/ios/MGLMapView.mm#L1528-L1544). This should be a first-class API internal to `mbgl` that bindings like iOS can query.

**Comment by ljbade** [comment]
Hmm good idea @incanus.

**Comment by incanus** [comment]
Punting off of b2 since the bundled styles haven't changed since b1 and nothing under the hood has moved here that makes this any more urgent.

**Comment by ljbade** [comment]
@1ec5 is looking to implement this in https://github.com/mapbox/mapbox-gl-native/pull/2746#issuecomment-150703017 for iOS.

On Android I decided to just have a class that provides static constants in the `Styles` class.

**Comment by tobrun** [comment]
On Android we have:

```java
/**
 * <p>
 * Style provides URLs to several professional styles designed by Mapbox.
 * </p>
 * These styles are all ready to go in your app. To load one, pass it into {@link MapView#setStyleUrl(String)}
 *
 * @see MapView#setStyleUrl(String)
 */
public class Style {

    /**
     * Indicates the parameter accepts one of the values from {@link Style}.
     */
    @StringDef({MAPBOX_STREETS, EMERALD, LIGHT, DARK, SATELLITE, SATELLITE_STREETS})
    @Retention(RetentionPolicy.SOURCE)
    public @interface StyleUrl {
    }

    // IMPORTANT: If you change any of these you also need to edit them in strings.xml

    /**
     * Mapbox Streets: A complete basemap, perfect for incorporating your own data.
     */
    public static final String MAPBOX_STREETS = "mapbox://styles/mapbox/streets-v8";
    /**
     * Emerald: A versatile style, with emphasis on road networks and public transit.
     */
    public static final String EMERALD = "mapbox://styles/mapbox/emerald-v8";
    /**
     * Light: Subtle light backdrop for data visualizations.
     */
    public static final String LIGHT = "mapbox://styles/mapbox/light-v8";
    /**
     * Dark: Subtle dark backdrop for data visualizations.
     */
    public static final String DARK = "mapbox://styles/mapbox/dark-v8";
    /**
     * Satellite: A beautiful global satellite and aerial imagery layer.
     */
    public static final String SATELLITE = "mapbox://styles/mapbox/satellite-v8";

    /**
     * Satellite Streets: Global satellite and aerial imagery with unobtrusive labels.
     */
    public static final String SATELLITE_STREETS = "mapbox://styles/mapbox/satellite-hybrid-v8";

}

```

Since @friedbunny  removed iOS label, I think this is resolved for both platforms!

**Comment by friedbunny** [comment]
Yup, iOS happened in #2746.

**Comment by tobrun** [comment]
It seems the current way is not as requested in this issue.

We should fetch:
 - https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/util/default_styles.hpp#L23

and match those urls on the `Style` class shown above.

-> if we change `default_styles.hpp` -> our app urls should change automatically.

**Comment by 1ec5** [comment]
On the iOS side, we're relying on a compile-time assertion that the number of default styles hasn't changed since we last updated the iOS-specific list. We also have a unit test to the same effect.

**Comment by tobrun** [comment]
I was also thinking about handling this at compile time (integrating this as a task in gradle) but instead of asserting, I was thinking about generating the java file.
\cc @bleege @zugaldia

**Comment by jfirebaugh** [comment]
Obsolete.
