### ISSUE TITLE
Worker pool destroyed and recreated on style changes

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#1463]
We are destroying and recreating the worker pool when changing the style because currently the Style object owns the Worker object.

One solution would be move it to the ResourceLoader and implement a clear() method on the ResourceLoader instead of resetting it too.

**Comment by jfirebaugh** [comment]
Is this actually performance significant?

**Comment by jfirebaugh** [comment]
(See 0c280adebcb9b1dd050aacb1dda1ad3715128ced for why this was done.)

**Comment by tmpsantos** [comment]
> Is this actually performance significant?

There is a significant stall when we switch styles. I'm suspecting it is because we are joining these threads (and we do it on the MapThread), so we have to wait for all the pending jobs to finish.

But yes, like we discussed yesterday, I think I can only proceed with this one after we get rid of the references we are passing to workers.

**Comment by jfirebaugh** [comment]
We make work requests cancelable in 8ee40a544e4b6459253056f2f1b6c812bde1cb33. @tmpsantos Are you still concerned about the pool creation / destruction itself or should we close this?

**Comment by tmpsantos** [comment]
> We make work requests cancelable in 8ee40a5. @tmpsantos Are you still concerned about the pool creation / destruction itself or should we close this?

Closing. We can reopen if it turns to be an issue in the future.
