### ISSUE TITLE
Text collision not calculated properly

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#1465]
After #1326, we render SymbolBuckets as we get glyphs and sprites from the network, but the parser is assuming we have all the buckets already in place when calculating the text collisions (discarding the Collision object after each parsing run).

This is hard to notice on the parts of the map using latin script because you rarely have to wait for glyphs, but can be easily spotted at metropolitan areas of China and Japan (you might see some labels overlapping).

What needs to be done:

* We must keep a reference to the Collision object until the tile is at the state `parsed`.
* The buckets must be added to the Collision object at the same order they appear in the style.
* We need to halt the parser from processing SymbolBuckets at the first empty SymbolBucket we find (so we keep the ordering).

**Comment by tmpsantos** [comment]
![out](https://cloud.githubusercontent.com/assets/996307/7593782/35e29f24-f8e5-11e4-9cff-36ab96600e6d.png)
*How it is now*
![out-after](https://cloud.githubusercontent.com/assets/996307/7593783/35e70870-f8e5-11e4-9f02-6d28a1d0e188.png)
*After we fix the bug*

**Comment by incanus** [comment]
This bug doesn't seem to manifest on 2x iOS, but looks exactly the same as above on 1x.
