### ISSUE TITLE
[ios] Check to see if responding to UIDeviceOrientationDidChangeNotification is required.

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#14661]
Recent testing has hinted at the fact that we may not need the `deviceOrientationDidChange:` method - it looks like this can trigger multiple calls to `layoutSubviews`. This needs to be thoroughly investigated.

Marking as a bug, pending clarification.

**Comment by 1ec5** [comment]
We may still need it in order to ensure that the center coordinate remains at the center.

**Comment by julianrex** [comment]
Closing as stale.
