### ISSUE TITLE
Unclosed outlines around areas

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1467]
[These](https://www.openstreetmap.org/way/56395355) [fields](https://www.openstreetmap.org/way/56395353) [are](https://www.openstreetmap.org/way/56395356) mapped as overlapping but non-intersecting `leisure=pitch` areas in OSM and [render correctly in mapbox-gl-js](https://www.mapbox.com/mapbox-gl-styles/#17.03/39.10135/-84.61210), but are unclosed in mapbox-gl-native on iOS 8:

![baseball](https://cloud.githubusercontent.com/assets/1231218/7526051/6654e4f8-f4c3-11e4-9fdd-cc65edd5ba46.PNG)

Unlike #1450, this issue only seems to affect Mapbox Streets; the outlines are closed in Emerald.

**Comment by 1ec5** [comment]
Also seeing unclosed outlines around lakes in Emerald:

![lakes](https://cloud.githubusercontent.com/assets/1231218/7596244/24b46b04-f8a1-11e4-8b4b-f22ab57dff56.PNG)

**Comment by friedbunny** [comment]
Feels like this may be the same bug as #1450.

**Comment by ljbade** [comment]
Another example to add, the ACT in Australia, most noticeable when zoomed out:
![device-2015-05-21-091032](https://cloud.githubusercontent.com/assets/1215089/7738828/39a1c604-ff9c-11e4-8ae1-ebeb7253c2c4.png)

**Comment by kkaefer** [comment]
Closed by #1725
