### ISSUE TITLE
Create style from json

### ISSUE THREAD

**Issue by AliKhoshraftar** [mapbox/mapbox-gl-native#14706]
Hey.
I need to add style from json. based on my searching i found this issue : 
[Style-compliant JSON in Android and iOS SDKs](https://github.com/mapbox/mapbox-gl-native/issues/13467)

### Steps to reproduce

 1.
 2.
 3.

### Configuration

**Android versions:** 
**Device models:** 
**Mapbox SDK versions:7.3.2

**Comment by samfader** [comment]
@AliKhoshraftar You can add a style from JSON using our Android SDK: https://docs.mapbox.com/android/maps/examples/use-a-local-style-source/
