### ISSUE TITLE
Displays map instead of video in  Exoplayer

### ISSUE THREAD

**Issue by mehdisamavat** [mapbox/mapbox-gl-native#14713]
Hi
 4 fragments in BottomNavigation that one of them is map 
when i open app and go to movie tab  all thing is right but when click on map and then go to play video tab  i see Exo show map
when i use replace for fragment its gonna be alright but i dont want use replace
in some SDK all thing are ok 

### Steps to reproduce

 1.open app and click on map tab
 2.an d then click on cinema tab 
 3.in movie tab  show map Exo (The movie is running because it has sound but displays the map instead of the video image)

### Expected behavior

mapbox show map and exo  play video :-)

### Actual behavior
Exoplayer show map 

![Screenshot 2019-05-21 at 19 23 51](https://user-images.githubusercontent.com/22484260/58106847-022e2900-7bfe-11e9-8de4-5298a9dc65b2.png)

### Configuration
**Android versions:**   6.0.1
**Device models:**  LG-k220
**Mapbox SDK versions:**  7.3.2

**Comment by LukasPaczos** [comment]
> when i use replace for fragment its gonna be alright but i dont want use replace

What's your method for changing the fragment in this case? How are you destroying the map when switching the tab? `SurfaceView`s (map and the video both use it) cannot overlap, you need to properly destroy the map before placing the video surface in its place. You can also try using the texture view mode:
```
app:mapbox_renderTextureMode="true"
```
or
```
mapboxMapOptions.textureMode(true)
```
```
