### ISSUE TITLE
setTextVariableAnchor causes momentary clustering of labels

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#14715]
If you add
```objc
    MGLSymbolStyleLayer *poiLabelLayers = (MGLSymbolStyleLayer *)[self.mapView.style layerWithIdentifier:@"poi-label"];
    poiLabelLayers.textVariableAnchor = [NSExpression expressionForConstantValue:@[@(MGLTextAnchorTop), @(MGLTextAnchorRight)]];
```

to  `-mapView:didFinishLoadingStyle:` in `iosapp` you'll see that labels will cluster together momentarily. 

![Screen Shot 2019-05-21 at 4 49 50 PM](https://user-images.githubusercontent.com/3765757/58129859-b8871380-7be8-11e9-8526-13b22b6a913c.png)

![label-bug](https://user-images.githubusercontent.com/3765757/58130383-e1f46f00-7be9-11e9-9817-1482bded38b0.gif)

You can also reproduce this using `ios-sdk-examples`'s "Change label placement" example, without modification.

The `textVariableAnchor` property calls through to core's `setTextVariableAnchor`.

**Platform:** iOS (though @tobrun has reported on Android)
**Mapbox SDK version:** `release-nectar` branch

**Comment by tobrun** [comment]
reproduction case for android in https://github.com/mapbox/mapbox-gl-native/tree/tvn-test-example

**Comment by pozdnyakov** [comment]
Regression from https://github.com/mapbox/mapbox-gl-native/pull/14669/commits/867555b1c9ef51fec23ce77c682cf7d5b5a23c5e
