### ISSUE TITLE
SymbolLayer text fails when no Style url provided

### ISSUE THREAD

**Issue by DummyCo** [mapbox/mapbox-gl-native#14712]
`SymbolLayer` `textField` property usage attempt fails with the next log error: 
`E/Mbgl-HttpRequest: [HTTP] Unable to parse resourceUrl`, 
when Style is created via Builder from scratch with no url provided. 
Icon-related properties work well at the same time.

### Steps to reproduce

 1. Create a source based on `FeatureColletction` with point and `title` property
 2. Set map style via `Builder` with no `url` provided
 3. Provide `SymbolLayer` for the mentioned source and try to set `textField("{title}")` property

### Expected behavior

Rendered text for source point

### Actual behavior

Broken layer/source with 
`E/Mbgl-HttpRequest: [HTTP] Unable to parse resourceUrl`
log error

### Configuration

**Android versions:** 9
**Device models:** Pixel XL
**Mapbox SDK versions:** 7.5.0-beta.1 and 7.3.2

**Comment by tobrun** [comment]
@DummyCo to display text you will need to have a [font glyph](https://docs.mapbox.com/mapbox-gl-js/style-spec/#root-glyphs) loaded on your style. Without this we can't render text, you will have to create a style json and add entries for your fonts. If you want to avoid loading resources online, you can package glyphs (.pbf extension) in your assets as use `asset://something.pbf`.

**Comment by DummyCo** [comment]
@tobrun custom local style with assets font reference fixed the issue, thank you!
