### ISSUE TITLE
white map when I load two mapviews in different fragments

### ISSUE THREAD

**Issue by quimico99** [mapbox/mapbox-gl-native#14720]
I have developed an activity with a container to switch between two fragments. It turns out that I load "fragment A" and inside it there is a marker with an infowindows, when you click on the infowindows should open a "fragment B" showing a map and other markers. It turns out that when I do this the "Fragment A" is loaded and then the "fragment B" is loaded but the map is not visible it just looks white. I have checked the logCat and the onStyleLoaded method of "Fragment B" is not loaded. To see the problem Try loading "Fragment B" first and then "Fragment A" and the map looks fine.

**FRAGMENT A**

    @Override
    public void onDestroyView() {
        super.onDestroyView();

        socket.close();
        Log.d(TAG,"[onDestroyView]");

        if(style.isFullyLoaded()){
            style.removeLayer("layer-id");
            style.removeLayer(MARKER_LAYER_ID);
            style.removeLayer(CALLOUT_LAYER_ID);
        }

        if (mapboxM != null) {
            Log.d(TAG,"[onDestroyView]removeOnMapClickListener");
            mapboxM.removeOnMapClickListener(onMapClickListener);
        }

        mapView.onDestroy();
    }

**FRAGMENT B**

   View view;
    private static MapView mapViewTrack;
    private static Style style;
    private String TAG="[Trackrc_fragment]";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Mapbox.getInstance(getActivity().getApplicationContext(),getString(R.string.mapbox_access_token));
        Log.d(TAG, "[onCreate]");

    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        Log.d(TAG, "[onCreateView]");
        

            view = inflater.inflate(R.layout.fragment_trackrc_mapbox, container, false);
        mapViewTrack = (MapView) view.findViewById(R.id.mapViewTrack);

        mapViewTrack.onCreate(savedInstanceState);

        return view;
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        Log.d(TAG,"onViewCreated");
       
        mapViewTrack.getMapAsync(this);

    }

    @Override
    public void onMapReady(@NonNull MapboxMap mapboxMap) {
        Log.d(TAG, "[onViewCreate][onMapReady]");

        mapboxMap.setStyle(Style.SATELLITE_STREETS, new Style.OnStyleLoaded() {
            @Override
            public void onStyleLoaded(@NonNull Style style) {
                Log.d(TAG, "[onViewCreate][onMapReady][onStyleLoaded]");

                // Map is set up and the style has loaded. Now you can add data or make other map adjustments
            }
        });

    }

**LOGCAT FRAGMENT B**
2019-05-21 08:47:09.497 21814-21814/com.vv D/[Trackrc_fragment]: [onCreate]
2019-05-21 08:47:09.497 21814-21814/com.v D/[Trackrc_fragment]: [onCreateView]
2019-05-21 08:47:09.521 21814-21814/com.vv D/[Trackrc_fragment]: onViewCreated
2019-05-21 08:47:09.544 21814-23163/com.vv E/EGL_adreno: CreateContext rcMajorVersion:3, minorVersion:0
2019-05-21 08:47:09.544 21814-23163/com.vv E/EGL_adreno: rcMajorVersion = 3, minorVersion = 0
2019-05-21 08:47:09.545 21814-23163/com.vv D/EGL_adreno: eglCreateContext: 0x96b7c240: maj 3 min 0 rcv 3
2019-05-21 08:47:09.570 21814-21814/com.vv D/[Trackrc_fragment]: [onViewCreate][onMapReady]

**MAINACTIVITY**
Mainactivity method to load FRAGMENT B

            @Override
            public void StartTrackRC(boolean state, String id_Trackrc) {

                if(state==true) {
                    Bundle bundle_Trackrc = new Bundle();
                    bundle_Trackrc.putString(getResources().getString(R.string.id_rc), id_Trackrc);

                    trackRC_Mapbox_Fragment = new TrackRC_Mapbox_Fragment();
                    trackRC_Mapbox_Fragment.setArguments(bundle_Trackrc);

                    if(fragmentManager.findFragmentByTag("com.MapboxNavigaDrawer")!=null) {

                        fragmentManager.beginTransaction().remove(fragmentManager.findFragmentByTag("com.MapboxNavigaDrawer")).commit();

                        getSupportFragmentManager().
                                beginTransaction().
                                replace(R.id.content_report_crime_navdraw, new TrackRC_Mapbox_Fragment(), "fragment_trackRC").
                                addToBackStack(null).
                                commit();

                }

                }

            }

### Configuration

**Android versions:** Min Android SDK : 15, target SDK: 28
**Device models:** MEMU 7.1.2
**Mapbox SDK versions:**  sdk mapbox: 7.1.1 and 7.4.0

**Comment by quimico99** [comment]
I don't get it. But I found that the problem only happens when I have defined the onStop method in my Fragment (and it is not defined onResume() ) or they are both and also this onStart(). What is the reason?

**Comment by LukasPaczos** [comment]
@quimico99 are you overriding all required lifecycle methods?
