### ISSUE TITLE
[ios, macos] Add platform tile invalidation APIs

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#14734]
https://github.com/mapbox/mapbox-gl-native/pull/14702 added tile invalidation to core. This placeholder ticket is for the iOS & macOS APIs exposing this functionality.

Once the [follow on PR](https://github.com/mapbox/mapbox-gl-native/pull/14702#issuecomment-494018549) lands, we should be ready to start.

**Comment by friedbunny** [comment]
Would this be done at the same time as #14731, perhaps?

**Comment by jmkiley** [comment]
Landed in #14978
