### ISSUE TITLE
[ios] Lint podspecs and improve version bumping process

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#14730]
We should lint podspec changes and add a script for bumping versions in podspecs, so as to avoid situations like #14729 (which is itself not a terribly large problem, but one that automated checks are very good at helping us avoid).

/cc @mapbox/maps-ios

**Comment by friedbunny** [comment]
The rough implementation I envisioned:

- `make ios-pod-lint` command that runs [`pod spec lint`](https://github.com/CocoaPods/CocoaPods/blob/cff06e94c02b4b75385d5a380294fe7d5439ef6a/lib/cocoapods/command/spec/lint.rb).
- `make ios-pod-bump <version>` command that we manually run to bump the version variable in our various podspecs.

As part of this, I figured we’d also:

- Remove the static podspec, which is no longer part of our releases.
- Stop bundling a local podspec with the releases.
- Make the CI podspec lint step contingent on some podspec file having changed.

**Comment by julianrex** [comment]
Excellent - let's do it.

**Comment by friedbunny** [comment]
A similar thing happened again in #15014, so I’m going to go ahead and work on this myself.

**Comment by friedbunny** [comment]
I’m going to skip implementation of a `make ios-pod-bump` this time, since I think we should reconsider editing the podspecs at all — [something like this](https://github.com/realm/realm-cocoa/blob/3d52fc063acd68ad46e99fd55f90cece1560388a/Realm.podspec#L3) would probably be better, where the source of versioning truth is part of the actual built artifact.
