### ISSUE TITLE
Crash MGLLineStyleLayer lineDashPattern MGL_MATCH

### ISSUE THREAD

**Issue by falcon283** [mapbox/mapbox-gl-native#14738]
Hello, in my source `MGLPolylineFeature` I set an attribute that I use in combination with `MGL_MATCH` function.

I use It for both `lineColor` and `lineWidth`. It works like a charm. Different attributes are matched and the appropriate style is applied, if none default value Is used.

Now I would use the very same code to generate the `NSExpression` for `lineDashPattern` passing, as documented, an array of numbers ([2, 2] or similar), but doing this an exception is raised.

the resulting NSExpression is 
`MGL_MATCH(attributeName, value1, {2, 2}, value2, {}, {})`

and the exception raised is 

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid property value: data expressions not supported'
```

Please note that creating an `NSExpression` with constant value, for instance [2, 2], it works, but of course all the features are drawn in the same style which is supposed to be different.

Am I doing something wrong or this specific NSExpression with arrays is not supported? 

**Mapbox SDK 4.3.0, 4.6.0, 5.0.0:** 
**iOS All:** 
**Device/simulator All:**
**Xcode 10.2:**

**Comment by fabian-guerra** [comment]
Hi, @falcon283. Thank you for using Mapbox. The values supported for `lineDashPattern` attribute are:

- Constant array values no less than 0
- Predefined functions, including mathematical and string operators
- Conditional expressions
- Variable assignments and references to assigned variables
- Step functions applied to the $zoomLevel variable

Specified here:
https://docs.mapbox.com/ios/api/maps/5.0.0/Classes/MGLLineStyleLayer.html#/c:objc(cs)MGLLineStyleLayer(py)lineDashPattern

This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/) or check our [documentation](https://www.mapbox.com/ios-sdk/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
