### ISSUE TITLE
Dynamically add data, remove markers outside of bounds, add markers inside of bounds

### ISSUE THREAD

**Issue by filling** [mapbox/mapbox-gl-native#14735]
Hello!

I've been struggling with this feature for weeks, but am starting to think it's not possible. Hopefully someone here can prove me wrong! :)

Using Mapbox GL. On page load, map renders with markers within the given bounds. I'm trying to mimic functionality where the user drags the map, and based on the new bounds, new markers are drawn and old ones are removed. Data for the new markers are dynamic based on an API request. I managed to find a function after much Googling to test if a point is in bounds of a map and that works, but given how the function works to add/remove the marker, dynamic data doesn't seem to fit in.

I've created a fiddle [here](https://jsfiddle.net/filling/17jcpqym/14/) and hard-coded a new "feature" but it's not getting drawn.

Any advice would be greatly appreciated. Thanks in advance

**Comment by julianrex** [comment]
@filling is this meant for https://github.com/mapbox/mapbox-gl-js? This repo is for reporting issues with the core C++, iOS and Android SDKs.

**Comment by filling** [comment]
Ah, yes, you're right. My apologies.
