### ISSUE TITLE
MGLShapeOfflineRegion with padding

### ISSUE THREAD

**Issue by pimnijman** [mapbox/mapbox-gl-native#14756]
I would like to use MGLShapeOfflineRegion with some padding.

Right now I have a polyline (a route a user can travel along) and I can download an offline region using the following code.

```
let shape = MGLPolyline(coordinates: coordinates, count: UInt(coordinates.count))
let region = MGLShapeOfflineRegion(styleURL: styleUrl, shape: shape, fromZoomLevel: 6.0, toZoomLevel: 17.0)
MGLOfflineStorage.shared.addPack(for: region, withContext: context) { (pack, error) in
   ...
}
```

Mapbox will download all tiles at the given zoom levels that this polyline comes across.
The polyline might just be very close to the edge of a tile without crossing it, which means that the user will still see lots of blurry tiles (from another zoom level) while he's navigating.

![Simulator Screen Shot - iPhone 8 - 2019-05-24 at 09 12 09](https://user-images.githubusercontent.com/6617033/58309315-2d826500-7e04-11e9-814a-000dee0cb450.png)

What I need is a way to tell Mapbox "download all tiles this poyline comes across and all tiles within 1000 meters." Is there any way I can do this?

**Comment by fabian-guerra** [comment]
Hi, @pimnijman. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/) or check our [documentation](https://www.mapbox.com/ios-sdk/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).
