### ISSUE TITLE
[IOS] Load WMS layer, add layers, totally mess

### ISSUE THREAD

**Issue by songyuyang0918** [mapbox/mapbox-gl-native#14758]
Dear developer, I used MGLRasterTileSource to add a WMS layer,
First I get the URL to the WMS from the server, and then I start adding layers.
But in zooming in on the hierarchy, the derangement occurred.
Map zoomed in, and it seems to have duplicated many maps.
What should I do? Thank you very much!
![WMS层紊乱](https://user-images.githubusercontent.com/15685672/58322014-4b76b680-7e52-11e9-8376-fdd224475ba5.gif)
<img width="1526" alt="使用代码" src="https://user-images.githubusercontent.com/15685672/58322030-5c272c80-7e52-11e9-9776-60daf141c9fc.png">
<img width="817" alt="屏幕快照 2019-05-24 下午6 28 30" src="https://user-images.githubusercontent.com/15685672/58322035-60534a00-7e52-11e9-8f02-2217fee04e66.png">

**Comment by julianrex** [comment]
@songyuyang0918 Can you try this on a device please? I think you're hitting a bug with the SDK on the simulator where the camera is getting reset. 

After zooming in, please pan slightly before zooming in again.

**Comment by songyuyang0918** [comment]
Thank you for your answer.
I'm using the 4326 coordinate system,
Because before I used 3857, I clicked somewhere on the map, and the return coordinate is 4326, which is (-180 55.7765730186677)
157.5, 66.51326044311188)
That's not what I want, I want to use 3857 so if I click on the map somewhere the coordinates that I get back are also 3857.
(this is the URL I used :http://192.168.7.645:8397/geoserver/workspaceTest/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=workspaceTest:hebeishanxi&exceptions=application%2Fvnd.ogc.se_inimage&SRS=EPSG%3A4326&STYLES=&WIDTH=1024&HEIGHT=1024&BBOX=110.2454833984375,34.58929443359375,119.84832763671875,42.61767578125)

**Comment by songyuyang0918** [comment]
@julianrex Although I saw between WMS must add bbox={bbox-epsg-3857}
No matter 4326 or 3857, just add bbox={bbox-epsg-3857}.
As it turned out, I succeeded in the test...
All used 4,326

**Comment by songyuyang0918** [comment]
<img width="1979" alt="屏幕快照 2019-05-27 上午11 32 27" src="https://user-images.githubusercontent.com/15685672/58393869-2e6cfe00-8073-11e9-9147-a6a3d87b9400.png">

**Comment by songyuyang0918** [comment]
<img width="1979" alt="屏幕快照 2019-05-27 上午11 32 27" src="https://user-images.githubusercontent.com/15685672/58393896-52304400-8073-11e9-803f-b9a529293b23.png">
This is a click in 3857, and the return coordinate is not 3857

**Comment by songyuyang0918** [comment]
I changed the service to 3857 and loaded it in json file style, again deranged.The same is true for real machines.
![21558945356_ pic_hd](https://user-images.githubusercontent.com/15685672/58406283-d5fe2680-809b-11e9-8997-0a54a10ce517.jpg)
![31558945388_ pic_hd](https://user-images.githubusercontent.com/15685672/58406289-dac2da80-809b-11e9-9b0f-a0ea627340bb.jpg)

**Comment by fabian-guerra** [comment]
Hi, @songyuyang0918. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/) or check our [documentation](https://www.mapbox.com/ios-sdk/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).

**Comment by silvercxy** [comment]
您好，请问可以交流下有关4326坐标系的问题吗，我的邮箱是gisboyshan@gmail.com @songyuyang0918
