### ISSUE TITLE
Icon piles

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#14764]
This is a feature request for an option to pass an icon pile as the `icon-image` property value.

This would allow building composite, data-driven icons. Let's imagine this example built with our current tools:
![ezgif com-video-to-gif (42)](https://user-images.githubusercontent.com/16925074/58342745-85938880-7e51-11e9-8cc9-747a72190ce2.gif)
The composition is correct, but in the process, we are losing collision detection and the z-index between the elements of composite markers is incorrect because each element is laid out on a separate layer.

Icon piles would allow to drastically decrease the number of allocated bitmaps required to represent various states of features in a source.

**Comment by asheemmamoowala** [comment]
@LukasPaczos Can you elaborate what you mean by icon piles? In your example gif, there are three elements to the composited icon for each POI. Are these elements placed on individual layers and expected to be treated as a single icon for collision detection and z-index?

**Comment by LukasPaczos** [comment]
> Are these elements placed on individual layers and expected to be treated as a single icon for collision detection and z-index?

@asheemmamoowala I'm imagining the `"icon-image"` property accepting an array of expressions evaluating to strings with image IDs, so that we can draw all of the images, one on top of the other, on the same layer. For example:
```
"icon-image": [
  ["get", "marker-type"],
  ["get", "highlight-type"],
  ["get", "icon-type"]
]
```
