### ISSUE TITLE
Wrapped tiles don't always show up immediately

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1476]
Just observed this:

![img_0067](https://cloud.githubusercontent.com/assets/52399/7541034/6bc27ce4-f5b2-11e4-8fa3-9994e879ebe0.jpg)

**Comment by tmpsantos** [comment]
What do you mean by wrapped tiles?

**Comment by kkaefer** [comment]
on z0, the tile 0/0/0 is typically displayed multiple times, but we don't need to parse it multiple times. We have logical tiles that are (0/-1/0), (0/1/0) etc. that are linked to the data of the 0/0/0 tile. That means that they should all show up at the same time since the data is either there or not.

**Comment by jfirebaugh** [comment]
@kkaefer Is this still reproducible?
