### ISSUE TITLE
MapSnapshotter doesn't render frames during instrumentation tests

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#14760]
Refs https://github.com/mapbox/mapbox-gl-native/pull/14757.
> when the MapSnapshotter is run as part of the instrumentation test, the renderer doesn't return the snapshot and freezes. Test app examples work fine. 

I can see that there is a map update schedule (`RendererFrontend#update` is invoked), but we are not receiving any frames in the `Map::Impl::onDidFinishRenderingFrame`.

**Comment by LukasPaczos** [comment]
This can be reproduced using https://github.com/mapbox/mapbox-gl-native/tree/tvn-snasphot-crash.

/cc @tobrun

**Comment by tobrun** [comment]
Been lookin into this issue and confirmed that it's working again on master.
Bisected it to and double checked that the following commit works:
> 6262b83cc683db83aef4b3d74b29a04be53fdc3a

and that the commit before it didn't:
> 6583204e69938372fe13f99b2028f9a46dde818d

Moving forward on this issue, I'm going to refactor our snapshotter test as we initially wanted it to work.
