### ISSUE TITLE
MGLFillStyleLayer are drawn at wrong map-layer

### ISSUE THREAD

**Issue by Jackhammer42** [mapbox/mapbox-gl-native#14779]
Hey i discovered an issue in version 5.0.0 in the mapbox gl native SDK for iOS.

iOS: 12.2
iPhone XR
Xcode: 10.2

In our app we draw several polygons with the following code:

           `let url = URL(string: overlay.geojson_url)
            
            // Create source and add it to the map style.
            let source = MGLShapeSource(identifier: "\(overlay.id)", url: url!, options: nil)
            
            let layer = MGLFillStyleLayer(identifier: "\(overlay.id)", source: source)
            
            layer.fillColor = NSExpression(forConstantValue: UIColor(rgba: overlay.fill_color))
            layer.fillOpacity = NSExpression(forConstantValue: overlay.fill_opacity as NSNumber)
            
            let sourceAvailable = sources.filter({$0.identifier == overlay.id})
            
            if sourceAvailable.count == 0 {
                
                mapView.style!.addSource(source)
                
            }
            
            let annotationLayer = mapView.style?.layers.filter({$0.identifier == "com.mapbox.annotations.points"}).first
            
            mapView.style!.insertLayer(layer, below: annotationLayer!)`

We expected to see the following behaviour like in version 4.6.0:

![2019-05-28_09-26-11](https://user-images.githubusercontent.com/2570783/58459016-bfeb7700-812a-11e9-9587-6eecf9a414bb.png)

Instead the following happened in version 5.0.0:

![2019-05-28_09-25-43](https://user-images.githubusercontent.com/2570783/58459179-15278880-812b-11e9-8e0d-6f61e03e7fd8.png)

The same happens in the Android SDK Version 8.0.0. In addition we discovered that the position indicator in the Android SDK (v.8.0.0) is drawn below buildings in the map.

![mapbox location dot](https://user-images.githubusercontent.com/2570783/58459670-3a68c680-812c-11e9-9c1c-fd20f99bcdc7.png)

**Comment by jmkiley** [comment]
It looks like fill extrusion layers are being rendered above fill layers. This can be repro'd in `iosapp` by selecting `Add Building Extrusions`, then `Dynamically Style Polygon`.

cc @kkaefer

**Comment by mrfaa** [comment]
Hi @jmkiley @kkaefer The same happens to me in the Android SDK Version 8.0.0. Is there any update on this issue?

Thank you very much in advance!

**Comment by snkashis** [comment]
Yeah, I encountered this as well in the move to 8.0.0. Is this going to be remedied in 8.2.0?

**Comment by tobrun** [comment]
cc @tmpsantos

**Comment by tmpsantos** [comment]
Wondering if this is somehow related to https://github.com/mapbox/mapbox-gl-native/issues/14844

**Comment by tmpsantos** [comment]
Fixed.
