### ISSUE TITLE
Roads and rivers are vanishing when panning

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1478]
Just observed this:

![out](https://cloud.githubusercontent.com/assets/52399/7542382/ac51229c-f5bc-11e4-9f4f-241eced07d8c.gif)

**Comment by 1ec5** [comment]
I’m also seeing some really bad clipping of streets on an iPhone 6 running iOS 8.3 ([compare with gl-js](https://www.mapbox.com/mapbox-gl-styles/#15.03/38.7590/-89.8013)):

![clipping](https://cloud.githubusercontent.com/assets/1231218/7559738/34543c92-f770-11e4-99e4-e86949911b1a.gif)

**Comment by 1ec5** [comment]
Specifically, features are disappearing when the viewport contains certain tile boundaries (seen in debug mode), and the affected boundaries depend on the style and whether there’s rotation. @jfirebaugh says it’s a clipping issue. Here are some additional data points from Mapbox Streets:

* 14/4105/6275 (shown in the screen recording above) fails to show highway ramps when the northern, southern, or western tile boundary is visible, and it fails to show residential roads when the eastern or southern tile boundary is visible.
* Just to the south, 14/4105/6276 fails to show residential roads when its eastern, southern, or western boundary is visible.
* 12/1026/1569 only shows landcover when the eastern or western tile boundary is visible. It also fails to show residential roads when the northern tile boundary is visible.

This issue does not affect mapbox-gl-js.

**Comment by incanus** [comment]
Do we have any code leads on this yet @kkaefer @jfirebaugh?

**Comment by kkaefer** [comment]
Merged into master and ios-b1.
