### ISSUE TITLE
Implementation duplicated in mbgl-filesource target/project

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#14788]
These implementation files shouldn’t be duplicated in the `mbgl-filesource` project structure or be members of that target:

<img width="351" alt="Screen Shot 2019-05-28 at 5 58 01 PM" src="https://user-images.githubusercontent.com/1198851/58521731-4f684880-8172-11e9-858d-5013b4452cdc.png">

These files are coming from [`platform/darwin/filesource-files.json`](https://github.com/mapbox/mapbox-gl-native/blob/823670ea35df7d35f68a9d3cb5a42dbc823b66ea/platform/darwin/filesource-files.json#L4-L5).

/cc @fabian-guerra

**Comment by friedbunny** [comment]
I’m seeing this sometimes manifest itself as a cyclical dependency error in Xcode 10:

> Cycle in dependencies between targets 'iosapp' and 'dynamic'; building could produce unreliable results.
> Cycle path: iosapp → dynamic → mbgl-filesource → dynamic → iosapp
> Cycle details:
>
> → Target 'iosapp' has copy command from 'mapbox-gl-native/build/ios/Debug-iphonesimulator/Mapbox.framework' to 'mapbox-gl-native/build/ios/Debug-iphonesimulator/Mapbox GL.app/Frameworks/Mapbox.framework’
>
> → Target 'dynamic' has compile command with input 'mapbox-gl-native/platform/ios/resources/Images.xcassets’
>
> ○ Target 'dynamic' has target dependency on Target 'mbgl-filesource’
>
> → Target 'mbgl-filesource' has compile command with input 'mapbox-gl-native/platform/darwin/src/MGLNetworkConfiguration.m'
>
> → Target 'dynamic' has copy command from 'mapbox-gl-native/platform/darwin/src/MGLNetworkConfiguration.h' to 'mapbox-gl-native/build/ios/Debug-iphonesimulator/Mapbox.framework/Headers/MGLNetworkConfiguration.h'

**Comment by julianrex** [comment]
What do you think about setting up explicit dependencies, rather than relying on Xcode's implicit behaviour?
