### ISSUE TITLE
x3 x4 spirtes

### ISSUE THREAD

**Issue by JRWilding** [mapbox/mapbox-gl-native#14793]
Will https://github.com/mapbox/mapbox-gl-native/issues/1008 be revisited?

Since the last comment on it, many devices are now using x3 and beyond, and my designer is complaining of blurry icons on devices as old as a Nexus 5. Although we are generating a sprite for it, it isn't being used.

**Comment by friedbunny** [comment]
Thanks for posting — I’ve reopened #1008, so let’s continue tracking there.
