### ISSUE TITLE
Application crashes when adding a heatmap layer type

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-gl-native#14807]
### Steps to reproduce

 1. Create a heatmap layer and add it to a map view after the style has finished loading:

```swift
func mapView(_ mapView: MGLMapView, didFinishLoading style: MGLStyle) {
    // Parse GeoJSON data. This example uses all M1.0+ earthquakes from 12/22/15 to 1/21/16 as logged by USGS' Earthquake hazards program.
    guard let url = URL(string: "https://www.mapbox.com/mapbox-gl-js/assets/earthquakes.geojson") else { return }
    let source = MGLShapeSource(identifier: "earthquakes", url: url, options: nil)
    style.addSource(source)

    // Create a heatmap layer.
    let heatmapLayer = MGLHeatmapStyleLayer(identifier: "earthquakes", source: source)
    style.addLayer(heatmapLayer)
}
```
_Full minimal test case [can be found here](https://github.com/mapbox/ios-sdk-examples/blob/release-oolong-heatmap-bug/Examples/Swift/HeatmapExample.swift)._

 2. Try to run this code in an application and observe crash.

### Expected behavior
- Application should not crash and heatmap should render.

### Actual behavior
- Entire application crashes with the following log:

```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error
```

### Configuration

**Mapbox SDK versions:** v5.1.0-alpha.1
**iOS/macOS versions:** 10.14.4
**Device/simulator models:** iPhone X, physical device
**Xcode version:** 10.2.1

**Comment by long1eu** [comment]
I'm getting this issue in 5.2. Any workaround?

**Comment by zholmes1** [comment]
@long1eu Did you ever find a solution? I'm encountering this issue when I add a heatmap on iOS only. Android works fine, I'm using the react-native version of this library

**Comment by long1eu** [comment]
unfortunately not

**Comment by zholmes1** [comment]
> unfortunately not

Gotcha. Thanks for the quick reply!
