### ISSUE TITLE
[ios] predicateWithMGLJSONObject can return `Invalid filter value: filter property must be a string`

### ISSUE THREAD

**Issue by mfazekas** [mapbox/mapbox-gl-native#14805]
Using `predicateWithMGLJSONObject` can return `Invalid filter value: filter property must be a string` for a valid expression because of NSPredicate conversion.

### Steps to reproduce

 1.
```objective-c
        statesLayer.predicate = [NSPredicate predicateWithMGLJSONObject: @[
                                                                           @"all",
                                                                           @[@"==", @"$type", @"Point"],
                                                                           @[@"in", @"type", @"Blue Project", @"WFW Project"]
                                                                           ]
                                 ];
```

### Expected behavior

Expected to work.

### Actual behavior

Raises exception: 

```objective-c
'NSInvalidArgumentException', reason: 'Invalid filter value: filter property must be a string'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107d5d6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010884cac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000107d5d555 +[NSException raise:format:] + 197
	3   Mapbox                              0x0000000103c808f3 -[NSPredicate(MGLPrivateAdditions) mgl_filter] + 387
	4   Mapbox                              0x0000000103c9ac70 -[MGLFillStyleLayer setPredicate:] + 928
```

### Configuration

**Mapbox SDK versions: 316584fabc4dacaa53e7a208a88f5f87e6f243b0 - 5.1.0.alpha1** 
**iOS/macOS versions: 12.2/10.14.4** 
**Device/simulator models: iPhone X**
**Xcode version: 10.2.1**

**Comment by mfazekas** [comment]
See https://github.com/react-native-mapbox-gl/maps/issues/70

The issue seems to be that the following JSON
```js
[
    'all',
   ['==', '$type', 'Point'],
   ['in', 'type', 'Blue Project', 'WFW Project']
]
```

Becomes the following NSPredicate for `NSPredicate predicateWithMGLJSONObject`
```js
"$type" == "Point" AND MGL_FUNCTION("in", "type", "Blue Project", "WFW Project") == 1
```

And for that `predicate.mgl_jsonExpressionObject`
```js
[
     'all',
     ['==', '$type', 'Point'],
     ['==', ['in', 'type', 'Blue Project', 'WFW Project'], 1]
]
```

And it sounds like the first argument to `==` is expected to be a string not an array.

**Comment by julianrex** [comment]
Thanks for the detailed report @mfazekas!

**Comment by 1ec5** [comment]
`all` and `in` are part of the filter syntax in the style specification. Filters are deprecated and are no longer supported in the native SDKs. You should use an [expression](https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions) instead.

**Comment by mfazekas** [comment]
@1ec5 I'm a bit confused. The expression docs you're referring to shows [`all`](https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-all) as a valid expression.


![kép](https://user-images.githubusercontent.com/52435/59083621-63d9dd00-88f8-11e9-9faa-687875cb1a9a.png)

**Comment by mfazekas** [comment]
@1ec5 nevermind if i convert "in" to expression from legacy filter as well it works fine:

```objective-c
@[
       @"all",
        @[@"==", @[@"geometry-type"], @"Point"],
        @[@"match",
                 @[@"get", @"type"],
                 @[@"Blue Project", @"WFW Project"], @YES,
                 @NO]
           ]
```
