### ISSUE TITLE
Rendering artifacts with sdf icons

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#14809]
Refs https://github.com/mapbox/mapbox-plugins-android/issues/971.

Whenever an SDF icon is laid out on the same tile (group of tiles?) as a non-SDF icon, the non-SDF becomes SDF as well and changes its color to the color of the SDF and has troubles rendering which can be seen in https://github.com/mapbox/mapbox-plugins-android/issues/971 (lags when animating).

The reproducible case below - https://github.com/mapbox/mapbox-gl-native/tree/lp-sdf-artifacts-repro

![ezgif com-video-to-gif (47)](https://user-images.githubusercontent.com/16925074/58706201-a0b24b00-83b1-11e9-94e6-51c2fde8ac4d.gif)

Above uses maki, but also reproducible when explicitly adding a non-sdf icon:
```
Feature feature1 = Feature.fromGeometry(Point.fromLngLat(16, 50));
feature1.addStringProperty("icon", "non-sdf-image");

Feature feature2 = Feature.fromGeometry(Point.fromLngLat(-15, 40));
feature2.addStringProperty("icon", "sdf-image");

Bitmap bitmap = BitmapUtils.getBitmapFromDrawable(ContextCompat.getDrawable(SimpleMapActivity.this,
  R.drawable.mapbox_user_puck_icon));
if (bitmap != null) {
  style.addImage("sdf-image", bitmap, true /*SDF*/);
}

Bitmap bitmap1 = BitmapUtils.getBitmapFromDrawable(ContextCompat.getDrawable(SimpleMapActivity.this,
  R.drawable.mapbox_user_puck_icon));
if (bitmap1 != null) {
  style.addImage("non-sdf-image", bitmap1, false /*NON-SDF*/);
}
```

**Comment by LukasPaczos** [comment]
I went as far back as `7.1.0` and the issue was still reproducible.

/cc @tmpsantos

**Comment by LukasPaczos** [comment]
> has troubles rendering which can be seen in mapbox/mapbox-plugins-android#971 (lags when animating)

Reopening because even though the icons are not treated as SDFs visually, the rendering performance is still impacted. See https://github.com/mapbox/mapbox-plugins-android/issues/971#issuecomment-525698425.

If the layer contains only SDF icons or only non-SDF icons the performance is fine, we're running into the issue again only when there's a mix of SDF and non-SDF icons on the same layer.

**Comment by alexshalamov** [comment]
@LukasPaczos should we split this issue into two? Issue with mixing sdf and non-sdf icons and applying color is one issue. Performance lag is another issue that should be investigated separately.

@zmiao what do you think?

**Comment by zmiao** [comment]
I agree with @alexshalamov, the lagging issue could be handled separately, is it fine for you @LukasPaczos ?

**Comment by LukasPaczos** [comment]
Sure, let me can a new ticket :+1:

**Comment by LukasPaczos** [comment]
Continuing in https://github.com/mapbox/mapbox-gl-native/issues/15509.
