### ISSUE TITLE
Image blinking on shape update

### ISSUE THREAD

**Issue by emakarov** [mapbox/mapbox-gl-native#14815]
### Steps to reproduce
Hello
I'm using iOS SDK in order to show moving vehicle on the map.
I'm using MGLSymbolStyleLayer and updating shape with the following code:
```
let source = style.source(withIdentifier: "vehicles") as! MGLShapeSource
source.shape = shapeFromGeoJSON
```
I have only 2-3 vehicles, so GeoJSON is very small.
The problem is that vehicle markers are blinking (currently I'm testing in Simulator).

### Expected behavior
Markers should be updated without blinking when source of MGLSymbolStyleLayer is updated

### Actual behavior

Markers are blinking when source of MGLSymbolStyleLayer is updated

### Configuration

**iOS/macOS versions:** 
pod 'Mapbox-iOS-SDK', '~> 5.0.0'

**Xcode version:** 
Version 10.2 (10E125)

**Comment by friedbunny** [comment]
@emakarov thanks for posting — if you could provide a reproduction that we can test against, that would be very helpful in validating/prioritizing/fixing this issue.
