### ISSUE TITLE
On device rotation a mapView is destroyed and recreated. All custom layers are not restored and map features cannot be selected.

### ISSUE THREAD

**Issue by jbrinnand** [mapbox/mapbox-gl-native#14812]
1: Conditions to reproduce: Create a map with custom features loaded from a server as GeoJson. Select a custom Feature. The directions to the feature are rendered and a Callout associated with this feature is displayed. This Callout is added as a Layer with text and an image.

2. Rotate the phone sideways.. The MapView is regenerated, including all the custom features but the Callout is not displayed even though the Symbol Layer with the appropriate image is loaded. Here is a snippet of the the code which generates the image in the Callout.

       public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
               // Code to set textViews, etc. goes here.
               ..........
                ImageView imageView = view.findViewById(R.id.logoView);
                imageView.setImageBitmap(bitmap);
                imageView.setTag(this);

                Bitmap viewBitmap = MainActivity.SymbolGenerator.generate(view);
                mapboxStyle.addImage(currentTitle, viewBitmap);

                SymbolLayer featureLayer = new SymbolLayer(currentTitle, "selected-feature")
                        .withProperties(
                                iconImage(currentTitle),
                                PropertyFactory.visibility(Property.VISIBLE),
                                iconAllowOverlap(true),
                                PropertyFactory.iconAnchor(Property.ICON_ANCHOR_BOTTOM_LEFT),
                                PropertyFactory.iconOffset(new Float[]{-20.0f, -10.0f})
                        ).withFilter(eq(get("selected"), "true"));
                mapboxStyle.addLayer(featureLayer);
                ....
       }
Note: this code works as expected when the app is first brought up. It is the same code that is called when the screen is rotated.

3. After the screen rotation, none of the Custom Features is selectable. Clicking on them results in these error messages:  
`
E/Mbgl-NativeMapView: You're calling `pixelForLatLng` after the `MapView` was destroyed, were you invoking it after `onDestroy()`?`
`E/Mbgl-NativeMapView: You're calling `queryRenderedFeatures` after the `MapView` was destroyed, were you invoking it after `onDestroy()`?`

So - after a screen rotation, why can't the map be restored to its previous state - with the selected feature and its Callout; and why are **all** the points of interest on the map un-selectable? Should the MapView be contained in a Fragment with setRetainInstance(true)? What is the best practice for retaining map state on configuration changes in an Android App.

Thanks for any help in this matter.

**Comment by tobrun** [comment]
@jbrinnand could you share which version of the SDK you are using? This looks a lot like the issue that was fixed with https://github.com/mapbox/mapbox-gl-native/pull/14395 and shipped in v7.4.0

**Comment by jbrinnand** [comment]
I just moved to **com.mapbox.mapboxsdk:mapbox-android-sdk:8.0.0** and I am finding that this problem no longer exists. Thanks for your help.
