### ISSUE TITLE
Append offline resources flag to make offline 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#14835]
All offline resource downloads should use the query parameter of `?offline=true`. Next to our mobile  SDKs integrating this is in https://github.com/mapbox/mapbox-gl-native/issues/14820 and https://github.com/mapbox/mapbox-gl-native/issues/14819. We need to update our `make offline`, which is used for offline sideloading to also include this query parameter.

**Comment by julianrex** [comment]
Noting that we will also need to do this for the macOS app that can also be used to create offline packs.

**Comment by 1ec5** [comment]
#14857 adds the `offline=true` parameter to offline pack requests in the iOS map SDK. It adds a stub for macOS but not the actual parameter. Per @brsbl, we’ll need to add the parameter to track sideloading requests via macosapp. This is orthogonal to the addition of a SKU token: the accounts library doesn’t support macOS, and it isn’t clear yet whether there’s a need for the macOS map SDK to benefit from the same billing models available to iOS applications. (UIKit for macOS throws another wrench into the mix.)
