### ISSUE TITLE
move to strict semver

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1483]
We should ditch the `ios-vX.Y.Z`-style tags we've been doing for the iOS beta, not least of all as it complicates things for @mikemorris with the Node bindings. 

We can alter the deploy script to take a command like `'[publish ios x.y.z]'` and not necessarily tie the OS to the tag name.

**Comment by kkaefer** [comment]
:+1:

**Comment by incanus** [comment]
Thinking about moving on this for b2. Current lay of the land looks like: 

```
$ git tag --column
0.1.0                          ios-preview                    ios-v0.2.18                    ios-v0.2.6
android-v0.1.1                 ios-v0.1.0                     ios-v0.2.19                    ios-v0.2.7
android-v0.1.2                 ios-v0.2.0                     ios-v0.2.2                     ios-v0.2.8
android-v0.1.3                 ios-v0.2.1                     ios-v0.2.20                    ios-v0.2.9
ios-beta-preview-app-0.0.2     ios-v0.2.10                    ios-v0.2.21                    ios-v0.3.0
ios-beta-preview-app-0.0.3     ios-v0.2.11                    ios-v0.2.22                    ios-v0.3.1
ios-beta-preview-app-0.0.4     ios-v0.2.12                    ios-v0.2.23                    ios-v0.3.2
ios-beta-preview-sirius-0.0.5  ios-v0.2.13                    ios-v0.2.24                    ios-v0.3.3
ios-beta-preview-sirius-0.0.6  ios-v0.2.14                    ios-v0.2.25                    ios-v0.3.4
ios-beta-preview-sirius-0.0.7  ios-v0.2.15                    ios-v0.2.3
ios-beta-preview-sirius-0.0.8  ios-v0.2.16                    ios-v0.2.4
ios-beta-preview-sirius-0.0.9  ios-v0.2.17                    ios-v0.2.5
```

Moving on this would involve: 

1. Deciding on a tag style (`_._._` or `v_._._`?)
1. Moving four classes of existing tags to that pattern: 
  - `android-v_._._`
  - `ios-v_._._`
  - `ios-beta-preview-app-_._._`
  - `ios-beta-preview-sirius-_._._`
1. Updating [releases](https://github.com/mapbox/mapbox-gl-native/releases) to coordinate

I don't foresee any of this taking very long; I mostly just want to make sure that I don't break any dependent systems such as the packaging script (I got this), other testing/release scripts (@kkaefer @mikemorris?), or Android stuff (@ljbade?)

Does anyone see problems here?

**Comment by jfirebaugh** [comment]
Do we gain much by redoing the old tags? What if we just leave them and start using `v_._._` going forward?

**Comment by incanus** [comment]
I thought it'd be easier from a diffing point of view, but I can see how it would save a lot of hassle to switch midstream. 

I'll just update the publishing script to handle the new format and use `v_._._` going forward. We can address cleanup/unification later if necessary.

**Comment by incanus** [comment]
Did this above :point_up: in 4094543, which moves to a `v_._._` tagging scheme in Git but retains the `[publish ios-v_._._]` commit message to designate which platform we're packaging.

**Comment by incanus** [comment]
Fixed and now in `master`.

**Comment by jfirebaugh** [comment]
If we are doing "strict semver", we shouldn't be tagging intermediate releases as (e.g.) `v3.5.0`. These releases invariably contain both new features and backward incompatible changes, so according to semantic versioning conventions should be at least a minor version increment.

@incanus Is it necessary to tag these intermediate releases or could we use some other mechanism, and only tag the final `0.4.0` release?

**Comment by 1ec5** [comment]
The semver standard provides for prerelease tagging with suffixes, e.g. `v4.0.0-preview.1`.

**Comment by incanus** [comment]
We could technically adapt our publish script to work against commits, but GitHub's release mechanism, which we use to distribute the downloadable binary for non-CocoaPods use cases, either works with an existing or creates a new tag anyway.

**Comment by mikemorris** [comment]
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Considering the above, I don't have a problem with intermediate releases like `v0.3.5`. +1 to suffixes if we do something different though.

**Comment by incanus** [comment]
In light of @1ec5 & @mikemorris's comments, I think we're ok here? We've got plenty of runway before a `1.0.0` (including `0.10.0` and beyond).

**Comment by jfirebaugh** [comment]
@mikemorris is correct -- semver doesn't strictly require any semantics for pre-1.0 releases. It is a common to increment the minor version for breaking changes or new features though, so I think `v4.0.0-p.1` is the way to go.
