### ISSUE TITLE
Mapbox Upgrade, animations not smooth and dropping frame, but no drop frame logs. 

### ISSUE THREAD

**Issue by erluxman** [mapbox/mapbox-gl-native#14849]
Mapbox Along with its places API were working well with the following config , the animation works very well 
   ```
    val mapbox = "7.1.1"
    val geoJsonCore = "4.3.0"
    val mapBoxAnnotationPlugin = "0.4.0"
    val mapBoxPlacesPlugin = "0.7.0"
```
![Animation Working well](https://media.giphy.com/media/h1PX8olnKecjBMtho8/giphy.gif)

But after I upgraded it to following versions The animations are super slow....

  ```
    val mapbox = "8.0.0"
    val geoJsonCore = "4.8.0"
    val mapBoxAnnotationPlugin = "0.6.0"
    val mapBoxPlacesPlugin = "0.8.0"
```
![Animation Working well](https://media.giphy.com/media/f6Vdl2Vky9vNAsAhdf/giphy.gif)

Only error log I get on logcat is  
`2019-06-05 10:44:50.570 7715-7715/com.kabzeel.android E/kabzeel.androi: Invalid ID 0x00000000.`

Are the new sets of config incompatible??

### Configuration
Emulator API 28 

**Android versions:**  All
**Device models:**  All
**Mapbox SDK versions:**

**Comment by tobrun** [comment]
The source of this issue will probably be  https://github.com/mapbox/mapbox-gl-native/pull/14383 and was fixed with https://github.com/mapbox/mapbox-gl-native/pull/14907. Would you be able to retest with the v8.1.0 release?

**Comment by tobrun** [comment]
Closing as stale but feel free to reach out if still an issue!
