### ISSUE TITLE
Reverse geocoding always results in a failure

### ISSUE THREAD

**Issue by spiekermax** [mapbox/mapbox-gl-native#14845]
Using the latest version of Mapbox my reverse geocoding requests do not appear to work properly anymore.

### Steps to reproduce

Implement a reverse geocoding request like [here](https://docs.mapbox.com/android/java/overview/geocoder/).

### Expected behavior

Geocoding requests should work like in previous Mapbox versions
(In version 7.3.1 everything works as expected).

### Actual behavior

Geocoding requests always result in a failure.

### Configuration

**Android versions:** API Level 24
**Device models:** Samsung SM-G955N, HTC One A9
**Mapbox SDK versions:** 8.0.0

**Comment by 1ec5** [comment]
Hi, this is the repository for the map SDK. Issues with the Mapbox Java SDK should generally be reported in the [mapbox-java](https://github.com/mapbox/mapbox-java/) repository. In this case, you should instead [contact Mapbox support](https://support.mapbox.com/) and provide details about your requests so we can better diagnose the issue for you.
