### ISSUE TITLE
Mismatch between camera target and device location when in `TRACKING` (in China)

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-gl-native#14846]
This ticket is to report a mismatch between the camera target and the actual device location, when the Mapbox China Plugin for Android is being used and the `LocationComponent` is in `TRACKING` camera mode. 

### Steps to reproduce

 1. Create a barebones Android app with a Mapbox map **and** [the Mapbox China Plugin for Android](https://docs.mapbox.com/android/plugins/overview/china/#install-the-china-plugin) (requires a special Mapbox China token). 
2. Also set up [the `LocationComponent`](https://docs.mapbox.com/android/maps/overview/location-component/) with [the `TRACKING` camera mode](https://docs.mapbox.com/android/maps/overview/location-component/#cameramode).

### Expected behavior

The camera stays directly centered on the device location puck.

### Actual behavior

The camera target location has a mismatch with the device's location (puck).

### Configuration

**Android versions:**  Pie
**Device models:**  OnePlus 5
**Mapbox SDK versions:**  8.0.0

**Comment by langsmith** [comment]
@LukasPaczos ' comments about this from a conversation elsewhere:

> The shifter will translate all of the GeoJSON shapes (`Point` objects), that's why the puck is rendered at the correct place, but it won't impact the camera position (`LatLng` objects). 

> that `Point.fromLngLat(latLng.getLongitude(), latLng.getLattitude())` is an often practice, which would result in double shifting. We should probably introduce the shifting whenever a raw `LatLng` is passed to core instead, which means a lot of entry points though.

**Comment by langsmith** [comment]
cc @chriswu42 @Chaoba  as fyi about this

**Comment by chriswu42** [comment]
@Chaoba can you look into this?

**Comment by Chaoba** [comment]
@chriswu42 No problem, I will address this issue.
