### ISSUE TITLE
Bump telemetry to 4.5.0

### ISSUE THREAD

**Issue by andrlee** [mapbox/mapbox-gl-native#14848]
Bump `libtelemetry` to `4.5.0`, will be released on maven by 06/05 noon PST. Would like to have this change included into `android-v8.1.0-alpha.2` if possible. thanks!

**Comment by tobrun** [comment]
Thank you for flagging @andrlee! 

cc @langsmith, as you are running with release.

**Comment by andrlee** [comment]
sharing https://github.com/mapbox/mapbox-events-android/issues/408 for tracking purposes.

**Comment by langsmith** [comment]
https://github.com/mapbox/mapbox-gl-native/pull/14874 bumped `libtelemetry` to `4.5.1` which was the latest version of `libtelemetry`. It made it into the `8.1.0-alpha.2` release.
