### ISSUE TITLE
Styles - Text on lines (like isochrones)

### ISSUE THREAD

**Issue by lhorus** [mapbox/mapbox-gl-native#14843]
Mapbox doesn't seem to expose line text ([see this example, with quantitized color](https://labs.mapbox.com/bites/00156/#10.55/51.6878/-0.163)) in styles. However, this seems to be available for the isochrones API. Any chance on exposing these functions to styles themselves? Or should it be done purely programatically?

**Comment by tobrun** [comment]
LineLayer itself doesn't support text but have you tried using a symbol layer and using `symbol-placement` api with `line`? More info in https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-symbol-placement.

**Comment by lhorus** [comment]
Would that not force the creation of SVGs for each individual name? Is that how the isochrones API is doing it?! 

![image](https://user-images.githubusercontent.com/7058142/58891255-1553f500-86e4-11e9-8b1a-baeaf7ed306e.png)

Are the "20-min", "10-min", etc labels composed of symbol placements - therefore, SVGs?

**Comment by langsmith** [comment]
hey @lhorus , thanks for looking into Mapbox. I adjusted our current Isochrone example in the Mapbox Android demo app to include a toggle for showing the time label on the line: https://github.com/mapbox/mapbox-android-demo/pull/1087.

>Are the "20-min", "10-min", etc labels composed of symbol placements - therefore, SVGs?

The time labels are the `textField` of the `SymbolLayer`. `SymbolLayer`'s support icons and text. [`textField(concat(get("contour"), literal(" MIN"))),`](https://github.com/mapbox/mapbox-android-demo/blob/2e0f3a3ffe93e761f6f711764038afc34863e856/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/IsochroneActivity.java#L271) is where the magic happens. The `concat` Expression is used to combine the `contour` value (found in each isochrone area `Feature` object), with the raw `" MIN"` text.

[`symbolPlacement(SYMBOL_PLACEMENT_LINE),`](https://github.com/mapbox/mapbox-android-demo/blob/2e0f3a3ffe93e761f6f711764038afc34863e856/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/javaservices/IsochroneActivity.java#L273) is what keeps the time label text aligned with the `LineLayer` line.

**Comment by lhorus** [comment]
@langsmith , thank you for your reply. If this is the case, then for large-scale data-driven styling to overcome the style's ability to do this, is adding dynamic symbol layers (a lot of them) a viable option, in terms of scale/performance?

**Comment by tobrun** [comment]
you only need one symbol layer @lhorus
