### ISSUE TITLE
Crash on Download list of MGLOfflinePack

### ISSUE THREAD

**Issue by beemogmbh** [mapbox/mapbox-gl-native#14850]
### Steps to reproduce
1. Upgrade from ios-v4.10.0 to ios-v4.11.0
2. Create a list of MGLOfflinePacks to download
3. Start to download the packs one after another

### Expected behavior
All packs will be downloaded like in ios-v4.10.0

### Actual behavior
The App crashes after finishing a random number of packages. 

### Configuration
Mapbox SDK versions: ios-v4.11.0
iOS versions: all
Device/simulator models: all

<pre>
Crashed: com.mapbox.mbgl.DefaultFileSource
0  libobjc.A.dylib                0x21923a76 objc_msgSend + 21
1  CoreFoundation                 0x22094227 -[__NSDictionaryM objectForKey:] + 130
2  Mapbox                         0x1553a83 -[MGLNetworkConfiguration startDownloadEvent:type:] + 98
3  Mapbox                         0x1765023 mbgl::HTTPFileSource::request(mbgl::Resource const&, std::__1::function<void (mbgl::Response)>) + 1626
4  Mapbox                         0x177f77b mbgl::OnlineFileSource::Impl::activateRequest(mbgl::OnlineFileRequest*) + 154
5  CoreFoundation                 0x2213e58f __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 14
6  CoreFoundation                 0x2213e1c1 __CFRunLoopDoTimer + 936
7  CoreFoundation                 0x2213c00d __CFRunLoopRun + 1484
8  CoreFoundation                 0x2208b229 CFRunLoopRunSpecific + 520
9  CoreFoundation                 0x220cbdd3 CFRunLoopRun + 98
10 Mapbox                         0x176b20f std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, mbgl::util::Thread<mbgl::DefaultFileSource::Impl>::Thread<std::__1::shared_ptr<mbgl::FileSource> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long long&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<mbgl::FileSource> const&&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&&&, unsigned long long&&&)::'lambda'()> >(void*, void*) + 402
11 libsystem_pthread.dylib        0x21eaf85b _pthread_body + 138
12 libsystem_pthread.dylib        0x21eaf7cf _pthread_start + 110
13 libsystem_pthread.dylib        0x21ead724 thread_start + 8
</pre>

The issue was probably introduced with #13997 as [MGLNetworkConfiguration startDownloadEvent:type:] is new in this one.

**Comment by friedbunny** [comment]
Thanks for the report, @beemogmbh.

/cc @fabian-guerra

**Comment by friedbunny** [comment]
Hrm, I ended up accidentally duping this as #14982 and it got a few comments digging into the issue, so let’s use that as the canonical issue to track the problem.

Thanks again for posting this @beemogmbh, sorry to dupe you!
