### ISSUE TITLE
[core] regressions/mapbox-gl-js#3107 render test is flaky

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#14869]
The `regressions/mapbox-gl-js#3107` render test [is failing intermittently](https://circleci.com/gh/mapbox/mapbox-gl-native/285290) on `node-gcc8-debug`.

/cc @tmpsantos

**Comment by julianrex** [comment]
And again: https://circleci.com/gh/mapbox/mapbox-gl-native/303693
