### ISSUE TITLE
Discrepancy in values between gl-js and native for localIdeographFontFamily

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-native#14866]
I'm using a custom ideograph for iOS but attempting to define it the same way as gl-js:

`localIdeographFontFamily: "'Hiragino Sans', 'Noto Sans CJK SC', 'sans-serif'"`

In iOS at least, you can only [set a single font as the ideographic font](https://docs.mapbox.com/ios/api/maps/5.0.0/infoplist-keys.html#mglideographicfontfamilyname). Which is different from what's supported in GL-JS where [fallbacks can be used](https://docs.mapbox.com/mapbox-gl-js/example/local-ideographs/).

This seems confusing and I would expect the value provided to behave the same way.

**Comment by 1ec5** [comment]
On iOS/macOS, we could allow the Info.plist key to be set to an array instead of a string. But there will need to be some changes in the Objective-C implementation in mbgl to specify a font cascade list as part of the font description.

**Comment by chloekraw** [comment]
Related, possible workaround: https://github.com/mapbox/mapbox-gl-native/issues/9308

**Comment by chloekraw** [comment]
@tristen this will be closed by https://github.com/mapbox/mapbox-gl-native/pull/14862
