### ISSUE TITLE
MAPBOX SDK Error: Program type already present: com.getkeepsafe.relinker.ApkLibraryInstaller

### ISSUE THREAD

**Issue by ragshion** [mapbox/mapbox-gl-native#14888]
### Steps to reproduce

 1. When I run my app, i got this error 
`Error: Program type already present: com.getkeepsafe.relinker.ApkLibraryInstaller`

### Expected behavior
in dependencies, if i delete mapbox sdk and mapbox-android-plugin-place, my app works well
```
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.0.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v7:0.8.0'
```

**Android versions:** Pie
**Device models:** Pixel 2 XL
**Mapbox SDK versions:** Mapbox sdk 8.0.0 and Mapbox plugin place v7 0.8.0

Thank you,,.

**Comment by tobrun** [comment]
We are moving towards using another library loader in https://github.com/mapbox/mapbox-gl-native/pull/14890

**Comment by ragshion** [comment]
Oke. thank you in advance, we'll waiting
