### ISSUE TITLE
[ios] Tilt gesture should always require two fingers down

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#14886]
The tilt gesture currently only requires two fingers to initiate, but lifting your second finger later does not cancel the gesture — it should.

Somewhat related to #11982.

### Steps to reproduce

 1. Initiate two finger tilt gesture.
 2. Lift one finger.
 3. Tilting will continue when you drag up/down.

### Configuration

**Mapbox SDK versions:** `ios-v5.0.0`, etc.

/cc @fabian-guerra

**Comment by chloekraw** [comment]
@fabian-guerra @jmkiley I'm assuming this can be addressed with the other work you're doing this sprint?
