### ISSUE TITLE
Polygon area with gradient

### ISSUE THREAD

**Issue by fryette** [mapbox/mapbox-gl-native#14893]
Hi, I have an issue that I could not apply the gradient to the polygon area. And I have not found any examples with a gradient applied to the polygon.

**Platform:**
iOS, Android
**Mapbox SDK version:**
8.0

### Expected behavior
Polygon area with gradient.

### Actual behavior
Polygon area with solid color

**Comment by tobrun** [comment]
A polygon is called a [fill](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layers-fill) in the style specification. We don't support gradient atm though you can achieve this effect with polylines, which are called [line](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layers-line) in the style specification. Take a look at [line-gradient](https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-line-line-gradient). 

Note this repository is for requesting features and reporting bugs, not for requesting support.
