### ISSUE TITLE
A crash in GeoJsonSource::setGeoJson(FeatureCollection features)

### ISSUE THREAD

**Issue by maxtracking** [mapbox/mapbox-gl-native#14897]
GeoJsonSource::setGeoJson(FeatureCollection features) seems to be changed in 8.1.0-alpha.2 compared to eg 8.0.0. The parameter is not annotated (neither Nullable nor NotNull) so it results in a crash when one passed null in that method.

### Steps to reproduce

 1. Create `GeoJsonSource` instance
 2. Execute the following sample code:
      ```
      val featureCollection: FeatureCollection? = null // I put null explicitly here but it can be a result of some logic
      geoJsonSource.setGeoJson(featureCollection)
     ```
 3. Observe NPE

### Expected behavior
Either annotate the method so there will be some warning or Android Studio indication OR check for null in the implementation

### Actual behavior
A crash like 
```
E/SomeActivity$onStart: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.mapbox.geojson.FeatureCollection.features()' on a null object reference
        at com.mapbox.mapboxsdk.style.sources.GeoJsonSource.setGeoJson(GeoJsonSource.java:296)
```

### Configuration

**Android versions:** 8.0
**Device models:** Custom but doesn't matter
**Mapbox SDK versions:**  8.1.0-alpha.2

**Comment by tobrun** [comment]
Thanks for the report and testing out our pre releases. This behavior originates from https://github.com/mapbox/mapbox-gl-native/pull/14804 and should be restored as before with https://github.com/mapbox/mapbox-gl-native/pull/14898.

**Comment by maxtracking** [comment]
Thanks @tobrun!
