### ISSUE TITLE
Polygon with rounded corners

### ISSUE THREAD

**Issue by fryette** [mapbox/mapbox-gl-native#14894]
I cannot create polygon area with rounded corners. Cannot found ay example with it in google(.

**Platform:**
**Mapbox SDK version:**

### Expected behavior
Polygon area with rounded corners

### Actual behavior
Polygon area with shape corners

**Comment by tobrun** [comment]
A polygon is called a [fill](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layers-fill) in the style specification. We don't support rounded corners atm though you can achieve this effect with polylines, which are called [line](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layers-line) in the style specification. Take a look at line-cap and line-join. 

Note this repository is for requesting features and reporting bugs, not for requesting support.
