### ISSUE TITLE
[ios] Load a WMS service, the url is too long to get data

### ISSUE THREAD

**Issue by songyuyang0918** [mapbox/mapbox-gl-native#14892]
Can post requests be used?

**Comment by songyuyang0918** [comment]
Load a WMS service, do not add "CQL_FILTER" parameter can request to the data, add "CQL_FILTER" parameter can not get, who can help me to analyze it? Thank you very much!

<img width="1348" alt="1604AFCD9C6FBCB5EB5721819482231E" src="https://user-images.githubusercontent.com/15685672/59266435-3aafa880-8c7a-11e9-9619-30ff60012c53.png">

**Comment by friedbunny** [comment]
Hi @songyuyang0918 — thanks for using Mapbox. This repo is for reporting bugs, requesting features, and coordinating work related to the various Mapbox Map SDKs. For help with “how do I” questions, please ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox) or reach out to our excellent [support team](https://www.mapbox.com/contact/support/).
