### ISSUE TITLE
Annotation callout disables user location tracking

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1490]
1. Turn on user location tracking.
2. While driving down a highway, select an annotation near your current position.
   - User tracking turns off.
3. Turn user tracking back on.
   - The annotation is deselected as the map pans to the new user location.
   - Then user tracking quickly turns back off as the annotation reselects itself.

**Comment by incanus** [comment]
Is this still valid @1ec5?

**Comment by 1ec5** [comment]
Yes.

**Comment by RomainQuidet** [comment]
I don't see this behavior anymore, the tracking back on keep user tracking.

**Comment by friedbunny** [comment]
In `ios-app`, longpressing to add an annotation will disable the tracking mode. Tapping on an annotation will also disable tracking — e.g., tapping on the user dot.

**Comment by 1ec5** [comment]
What I'm seeing now is that selecting an ordinary annotation turns off tracking, but selecting the user dot does not.

**Comment by 1ec5** [comment]
Fixed in #7856.
