### ISSUE TITLE
[darwin] Some unit tests are locale-dependent

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#14908]
If a simulator or device is set to a non-English-speaking locale (say, Japan), the following tests will fail:

```
platform/darwin/test/MGLClockDirectionFormatterTests.m
platform/darwin/test/MGLCompassDirectionFormatterTests.m
platform/darwin/test/MGLCoordinateFormatterTests.m
platform/ios/test/MGLMapAccessibilityElementTests.m
```

/cc @1ec5 @fabian-guerra

**Comment by friedbunny** [comment]
@1ec5 in chat:
> I don’t remember the exact name, but there’s an environment variable you can pass into an AppKit or UIKit app to force it to a certain locale. That’s how the simulated language feature in Xcode works.

**Comment by 1ec5** [comment]
A clue from simulator console spew in a different project:

> CFLocaleCopyCurrent() failed to look up current locale via 'AppleLocale' and 'AppleLanguages' in user preferences; falling back to locale identifier 'en_US' as the default. Consider checking Console for sandbox violations from this process for reading from preferences, or enabling CoreFoundation debug logging for more information. This will only be logged once.

**Comment by friedbunny** [comment]
The environment variable is indeed `-AppleLocale en_US`, in case anyone was wondering.
