### ISSUE TITLE
Can't parse json value to NSExpression

### ISSUE THREAD

**Issue by maite-manana** [mapbox/mapbox-gl-native#14918]
I want to create a MGLSymbolStyleLayer from a Mapbox Studio Json. I'm using 'Mapbox-iOS-SDK' 4.10. I have some attributes that should be parsed to NSExpression, such as:
```
"text-field": {
  "base": 1,
  "stops": [
     [0, "{abbr}"],
     [5, "{name_en}"]
  ]
}
```
This attribute could also be a String, for example.
Is there a way to parse this value and assign it to the layer or has it to be done manually?

Thanks!

**Comment by fabian-guerra** [comment]
Hola @maite-manana. Thank you for using Mapbox. This repo is for reporting issues or requesting features related to the Mapbox Map SDK. For support or assistance with "how to" questions, please reach out to our [support team](https://www.mapbox.com/contact/support/) or check our [documentation](https://www.mapbox.com/ios-sdk/). You can also ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox).

This is our [documentation link](https://docs.mapbox.com/ios/api/maps/5.1.0/predicates-and-expressions.html) for expressions. I suggest you take a look at the iosapp [source code](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/app/MBXViewController.m)
it has many examples on how to use expressions.
