### ISSUE TITLE
Fallback support for CJK glyph generation

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#14915]
Local glyph generation should include support for fallback fonts. A developer should be able to pass in an array of fonts should they choose to set the font(s) for local glyph generation.

**Comment by chloekraw** [comment]
In https://github.com/mapbox/mapbox-gl-native/pull/10522 we added support in core for using locally-generated glyphs. Per @tobrun, the core implementation accepts a single string and needs to be modified to accept an array of fonts in order to support fallbacks. cc/ @tmpsantos

**Comment by tobrun** [comment]
I noticed that iOS is handling [this](https://github.com/mapbox/mapbox-gl-native/issues/14915#issuecomment-502842598) differently, they check the font array on the binding side and pass only 1 value to core. I believe that handling this on core side would align it more with the other APIs we have that use fonts (eg [text-font](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-font))

**Comment by chloekraw** [comment]
@tobrun, I believe the way iOS handles fallback fonts for `localIdeographFontFamily` matches the implementation they use for passing in fonts for all text, including `text-font`.

Theoretically speaking, is a comparable approach possible on Android, if we wanted to refactor the way that Android passes fonts to core? I'm not sure whether it'd be desirable or whether we've previously had a conversation about the pros/cons of both approaches. cc @1ec5

**Comment by chloekraw** [comment]
@tmpsantos, how big is the change needed in core to support this? it would be extremely valuable to get this into `release-picklejuice` so that Android gets to parity with iOS

**Comment by tmpsantos** [comment]
> @tmpsantos, how big is the change needed in core to support this?

Not big, most of the work here is writing render/unit tests.

**Comment by tobrun** [comment]
Capturing from chat between @tmpsantos, @alexshalamov and me. We are going to add same logic as iOS. Note however that on Android this kind of a hack as we on one end don't have a clear Android API to retrieve system fonts. We can't try/catch creating fonts from names as these factory methods always return non-null even if the font is unusable.

**Comment by chloekraw** [comment]
@tobrun thank you for the update! Could you explain why this decision was made? Is there a technical blocker with implementing this in core?

I want to make sure we're fully considering the implications of this decision and alternatives before proceeding.

cc @zugaldia

**Comment by tobrun** [comment]
I initially thought it would be a bit more easy for going with the core heavy implementation but that would result in going back and forth between core and the SDK. Having https://github.com/mapbox/mapbox-gl-native/pull/15255 is much simpler and matches core setup.

**Comment by chloekraw** [comment]
@tobrun ok, sounds good!

**Comment by chloekraw** [comment]
Closed by https://github.com/mapbox/mapbox-gl-native/pull/15255
