### ISSUE TITLE
[ios] MGLLoggingConfiguration should implement Log::Observer

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#14927]
[`Log::Observer`](https://github.com/mapbox/mapbox-gl-native/blob/9872416c1f6ea9bfa77060deccac17ce0354e561/include/mbgl/util/logging.hpp#L14-L21) is core's mechanism for reporting log events - the iOS/macOS logging handler, `MGLLoggingConfiguration`,  should implement this, so that these logs can be intercepted at the platform level (and therefore passed to the application).

/cc @fabian-guerra

**Comment by julianrex** [comment]
FYI @tmpsantos

**Comment by m-stephen** [comment]
How about use these levels on iOS side:
```
MGLLoggingLevelAll          //Print all logs
MGLLoggingLevelInfo         //Print info logs
MGLLoggingLevelWarning      //Print warning logs - just for a option, not use till now
MGLLoggingLevelDebug        //Print debug logs
MGLLoggingLevelError        //Print both process error and system error(Previously MGLAssert/MGLCAssert will print fault level logs, now combined into error logs)
MGLLoggingLevelNone         //Won't print anything
```

Another question is, I saw that we already can let developers disable logging by using this macro: `MGL_LOGGING_DISABLED`.

Should we provide a `MGLLoggingLevelNone` level for another option? @julianrex 
cc: @chloekraw

**Comment by julianrex** [comment]
I am in favour of adding both `MGLLoggingLevelWarning` and `MGLLoggingLevelNone` to align with the core levels - we could keep `...Fault` as an alias for Error? @fabian-guerra what was your intention with Error vs Fault?

**Comment by julianrex** [comment]
@friedbunny would love your thoughts here too.

**Comment by friedbunny** [comment]
I’m onboard with changing to the log levels in https://github.com/mapbox/mapbox-gl-native/issues/14927#issuecomment-509143416, since they feel more intuitive.

**Comment by chloekraw** [comment]
Thanks for this conversation! Could we make the `MGLLoggingLevel`s match [behavior on the Android SDK](https://github.com/mapbox/mapbox-gl-native/blob/9ea653a4c484e3356537535f037e8fb1a60861b1/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/log/Logger.java#L244)? 

So this would mean:

```
MGLLoggingLevelVerbose      //Print all logs
MGLLoggingLevelDebug        //Print all logs except Verbose
MGLLoggingLevelInfo         //Print all logs except Verbose and Debug
MGLLoggingLevelWarning      //Print warning and error logs
MGLLoggingLevelError        //Print error logs
MGLLoggingLevelNone         //Won't print anything
```

@m-stephen also suggested that we print both process error and system error logs. Previously MGLAssert/MGLCAssert would print fault level logs; now they're combined into error logs. Since `error` logs are printed in all levels except `MGLLoggingLevelNone`, could we confirm that we want this change to take effect throughout the levels?

cc @tobrun

**Comment by friedbunny** [comment]
On second thought, our current log levels correspond to [`os_log`](https://developer.apple.com/documentation/os/logging), which is probably what iOS developers should expect and is what we’ve built our logging upon. Platform convention should override parity with other platforms/implementations.

**Comment by m-stephen** [comment]
> So this would mean:
> ```
> MGLLoggingLevelVerbose      //Print all logs
> MGLLoggingLevelDebug        //Print all logs except verbose
> MGLLoggingLevelInfo         //Print all logs except verbose and debug
> MGLLoggingLevelWarning      //Print warning and error logs
> MGLLoggingLevelError        //Print error logs
> MGLLoggingLevelNone         //Won't print anything
> ```
If so,  what the difference between `MGLLoggingLevelVerbose` and `MGLLoggingLevelDebug`? @chloekraw

**Comment by m-stephen** [comment]
Another question: should we keep the macro: `MGL_LOGGING_DISABLED` which can let developers use this to disable logging? What's your thoughts? @friedbunny @julianrex

**Comment by chloekraw** [comment]
> On second thought, our current log levels correspond to os_log, which is probably what iOS developers should expect and is what we’ve built our logging upon.

That makes sense and works for me. What's a bit challenging for me to discern from that link is whether there's a clear hierarchy from most to least important in those different messages. I think `Default` is the most severe and `Info` is the least, but the other 3 in between are unclear. It would be helpful to see what the `MGLLoggingLevel` implementation would look like if we were to match [`os_log`](https://developer.apple.com/documentation/os/logging).

Also, concretely what would you propose this means for messages sent from core as `Log::Warning`?

> If so, what the difference between MGLLoggingLevelVerbose and MGLLoggingLevelDebug? 



The idea would be that we could add `verbose` logs in the future. You're right, today there would be no difference.

**Comment by m-stephen** [comment]
Hey, Chloe! Per this comment: https://github.com/mapbox/twc-collab/issues/902#issuecomment-510624476
from my understanding, previously, our iOS `MGLLoggingConfiguration` is not related to core `logging`, they’re independent. `MGLLoggingConfiguration` is used to filter logs in iOS SDK but not core logging. In `logging_nslog.mm`, core logging system will call `Log::platformRecord` to directly print core logs.

Correct me if I’m wrong, our goal is to filter all logs by using `MGLLoggingConfiguration` for iOS developers, right? @chloekraw 
cc: @tmpsantos @friedbunny

**Comment by m-stephen** [comment]
For `os_log` mapping, I suggest:
```
MGLLoggingLevelDebug      -   OS_LOG_TYPE_DEBUG
MGLLoggingLevelInfo       -   OS_LOG_TYPE_INFO
MGLLoggingLevelWarning    -   OS_LOG_TYPE_INFO
MGLLoggingLevelError      -   OS_LOG_TYPE_ERROR
MGLLoggingLevelFault      -   OS_LOG_TYPE_FAULT
```

```
EventSeverity:: Debug     -   OS_LOG_TYPE_DEBUG
EventSeverity:: Info      -   OS_LOG_TYPE_INFO
EventSeverity:: Warning   -   OS_LOG_TYPE_INFO
EventSeverity:: Error     -   OS_LOG_TYPE_ERROR
```

@chloekraw @friedbunny 
cc: @tmpsantos

**Comment by chloekraw** [comment]
Thanks @m-stephen -- your proposal looks good to me.

**Comment by m-stephen** [comment]
And for `log_nslog.mm`, I strongly recommend rename this file like `log_apple.mm`, and since iOS system is beyond iOS10, we should implement `os_log` logic in this file. @tmpsantos
