### ISSUE TITLE
[ios] -[MGLOfflineStorageTests testAddFileContent] fails with multiple devices

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#14928]
When running `make ios-test MORE_SIMULATORS=1` with Xcode 10 at 823670ea35df7d35f68a9d3cb5a42dbc823b66ea (~`ios-v5.1.0-beta.1`), `-[MGLOfflineStorageTests testAddFileContent]` fails on all simulators:

```
Failing tests:
	test:
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
```

Seems like this test is taking a very long time:

```
Test case '-[MGLOfflineStorageTests testAddFileContent]' failed on 'iPhone Xs Max' (12.384 seconds)
Test case '-[MGLOfflineStorageTests testAddFileContent]' failed on 'iPhone Xʀ' (12.567 seconds)
Test case '-[MGLOfflineStorageTests testAddFileContent]' failed on 'iPad Pro (11-inch)' (11.952 seconds)
```

... so there’s something about this test that isn’t compatible with multiple concurrent simulators.

/cc @fabian-guerra

**Comment by julianrex** [comment]
Perhaps this requires https://github.com/mapbox/mapbox-gl-native/pull/13916 - certainly would be a good test to see if we should keep that PR open.

**Comment by friedbunny** [comment]
It’s a little cumbersome to reproduce this crash (since you need multiple simulators running the tests at once and you apparently can’t initiate that from Xcode), but I was able to track it down to this vicinity:

https://github.com/mapbox/mapbox-gl-native/blob/c3e94a06480339fe911386cd8be43bdf3e54a17d/platform/darwin/test/MGLOfflineStorageTests.mm#L287-L314

Since this code is doing some strange (and likely problematic) things on the simulator’s file system, I expect that #13916 wouldn’t help here, but we should make sure.
