### ISSUE TITLE
Style change transition regression

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#14939]
A lot of contrast layers are popping up, especially visible when transitioning from light to dark style.

Before:
![ezgif com-video-to-gif (50)](https://user-images.githubusercontent.com/16925074/59605959-497ddb80-9110-11e9-901b-617c7bcddb86.gif)

After:
![ezgif com-video-to-gif (49)](https://user-images.githubusercontent.com/16925074/59605965-4da9f900-9110-11e9-934c-b383ffb3c7fd.gif)

Bisecting points to https://github.com/mapbox/mapbox-gl-native/commit/858097102d9f586e17b118532213e38262e801db.

/cc @pozdnyakov @tmpsantos

**Comment by tmpsantos** [comment]
thanks a lot for bisecting this issue!

**Comment by LukasPaczos** [comment]
@pozdnyakov @tmpsantos the issues seems to still be present on `master`:
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/16925074/62549844-7b3a3580-b869-11e9-82a0-6f54f671908d.gif)

**Comment by pozdnyakov** [comment]
This is a different issue, let's proceed with it at https://github.com/mapbox/mapbox-gl-native/issues/15353
