### ISSUE TITLE
[android] getFillColorAsInt() can't be converted to int

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-gl-native#14943]
Making this ticket to track an issue that came up during `8.1.0` manual QA in https://github.com/mapbox/mapbox-android-demo/issues/1090

`getFillColorAsInt()` from a `FillLayer` seems to be the problem.  
In that demo app example, `rgba(233.00001525878907,233.00001525878907,231.00001525878907,1)` can't be converted to int

Work was recently done in the `ColorUtils` class: https://github.com/mapbox/mapbox-gl-native/pull/14233

**Comment by LukasPaczos** [comment]
Closed with https://github.com/mapbox/mapbox-gl-native/pull/14954.
