### ISSUE TITLE
[iOS, Android, Core] Wind Layer implementation 

### ISSUE THREAD

**Issue by durgeshtrivedi** [mapbox/mapbox-gl-native#14951]
I am trying to implement  [WebGl-Wind](https://github.com/mapbox/webgl-wind) for iOS and Android. We are using [MapBox-React-native ](https://github.com/react-native-mapbox-gl/maps) SDK. When I started exploring the SDK I realise the core part is missing in [MapBox-native](https://github.com/mapbox/mapbox-gl-native) sdk its self. The complete list of files(I said them Layers to understand it easily)  C++, Objective-C/C++ and last JS side for MapBox-React-native. So things need to implement on native side first to bring them on React-Native. So I started exploring the native code and [ARCHITECTURE.md](https://github.com/mapbox/mapbox-gl-native/blob/master/ARCHITECTURE.md) helps me a lot to understand the code flow and different implementation because I didn't know MapBox SDK and where to start. 
I reached to the point where I understand Shaders need to be used which is common for [MapBox-Gl-JS](https://github.com/mapbox/mapbox-gl-js) and [MapBox-native](https://github.com/mapbox/mapbox-gl-native). While exploring the native code I understood  lot of files are generated using some script. Specially the CPP file which is generated from [Shaders](https://github.com/mapbox/mapbox-gl-js/tree/master/src/shaders) and some other supporting file here which are part of ARCHITECTURE. 
For every layer there are some set of file which are generated I refer the [HeatLayer](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/style/layers/heatmap_layer.cpp). 
I think I can use [WebGl-Wind](https://github.com/mapbox/webgl-wind) [Shaders](https://github.com/mapbox/webgl-wind/tree/master/src/shaders) from here but how to generate the files from here I didn't get the document. How to verify those generated file are correct. While building all the layers from here up and testing them while build in small module, is there a document for that because there should be away to build this in small modules and test them, if things are working correct before moving up the layer means(C++ to Objective C/C++) and even in C++ things are working correct or not. If some one can point me in right direction will be very helpful. 
Please correct me if I miss understood the things and also let me know if there is some existing implementation and I can move forward from there.

**Comment by trivedidurgesh** [comment]
@anandthakker , @mourner , @kkaefer, @tobrun , @1ec5 
 
Can any one of your please guide me about it. Some direction will be helpful.

**Comment by durgeshtrivedi** [comment]
@anandthakker , @mourner , @kkaefer, @tobrun , @1ec5 

Can any one of your please guide me about it. Some direction will be helpful.

**Comment by stevehayles** [comment]
@durgeshtrivedi Did you get anywhere with this in the end ?

**Comment by ifzm** [comment]
I am also concerned about this problem, looking forward to :+1:
