### ISSUE TITLE
[core] debug/overdraw render test is flaky

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#14950]
The `debug/overdraw` render test [is intermittently failing](https://circleci.com/gh/mapbox/mapbox-gl-native/290268) on `node-gcc8-debug`.

Another symptom of #14872.

/cc @tmpsantos @brunoabinader

**Comment by astojilj** [comment]
node-gcc8-debug isn't used anymore. If it happens on linux-render-test bot, let's reopen it to mark it as flaky on linux only.
