### ISSUE TITLE
App background cash 

### ISSUE THREAD

**Issue by dongzhixuanyuan** [mapbox/mapbox-gl-native#14979]
This crash was reported in My app crash statistics, but I can't reproduce it myself.  And crash report show that the app was in background when this crash happen.
It happens on Mapbox version: 8.0.0 & 8.0.1，and not happened on mapbox vesion:7.4.0

Crash stacktrace:

java.lang.IllegalArgumentException
Service not registered: com.google.android.gms.common.internal.zzf@8507d6d
1 android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1570)
--
2 android.app.ContextImpl.unbindService(ContextImpl.java:1702)
3 android.content.ContextWrapper.unbindService(ContextWrapper.java:727)
4 com.google.android.gms.common.stats.ConnectionTracker.unbindService(Unknown Source:0)
5 com.google.android.gms.common.internal.zzf.zzf(Unknown Source:24)
6 com.google.android.gms.common.internal.zze.handleMessage(Unknown Source:136)
7 android.os.Handler.dispatchMessage(Handler.java:102)
8 android.os.Looper.loop(Looper.java:201)
9 android.app.ActivityThread.main(ActivityThread.java:6806)
10 java.lang.reflect.Method.invoke(Native Method)
11 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
12 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

### Configuration

**Android versions:android 9.0 or android 8.0
**Device models:many
**Mapbox SDK versions: 8.0.0 or 8.0.1

**Comment by tobrun** [comment]
@dongzhixuanyuan nothing in that stacktrace points towards Mapbox being involved or being the source. 
Closing as not actionable.
