### ISSUE TITLE
[core] regressions/mapbox-gl-js#8273 render test is flaky

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#14983]
The `regressions/mapbox-gl-js#8273` render test [is failing intermittently](https://circleci.com/gh/mapbox/mapbox-gl-native/292809) on `node-gcc8-debug`.

Related to #14872.

/cc @tmpsantos @brunoabinader

**Comment by alexshalamov** [comment]
I think render test operations are the cause of flakiness
```
      "operations": [
        ["setPaintProperty", "line", "line-pattern", "zoo_icon"],
        ["wait"]
      ]
```
The `wait` operation could complete rendering frame before re-layout and rendering of the pattern that was set. Should be easy to fix by changing `wait` to `sleep`

/cc @pozdnyakov
