### ISSUE TITLE
Restore OpenGL ES state after rendering

### ISSUE THREAD

**Issue by plamenterziev** [mapbox/mapbox-gl-native#14988]
**Platform:** Android

I've integrated Mapbox with Open Scene Graph (Mapbox is Open Scene Graph node).

However Mapbox render call changes the OpenGL state and all subsequent renderings in the same frame are broken. On desktop (and OpenGL) I am using:

```
glPushClientAttrib(GL_CLIENT_ALL_ATTRIB_BITS);
m_map->render();
glPopClientAttrib();
```

This fixes the issue but unfortunately `glPushClientAttrib` is not available on OpenGL ES. Obviously Mapbox is changing the OpenGL state and does not restore it at the end of its render method (I guess for performance reasons). However this makes integrating Mapbox with other rendering kits harder.

Would be great if Mapbox supports restoring the OpenGL ES state at the end of its render method even with a slight performance hit.

**Comment by lightandshadow68** [comment]
I'm adding support for FILR's mobile infrared camera hardware via their accessory support SDK. https://developer.flir.com 

Image capture from the device fails when a Mapbox view is visible / rendering. I suspect this is related to the above OpenGL state issue.

**Comment by lightandshadow68** [comment]
Looking into this further, I noticed a private `pauseRendering:` method on MGLMapView, which looked promising, but doesn't seem to have any affect. Creating an instance of MGLMapView, but not adding it to the view hierarchy is the most I can do without triggering the issue.

**Comment by lightandshadow68** [comment]
Latest update: Removing the map view from the view hierarchy seems to allow image capture to resume. However, occasionally this fails as well.

**Comment by pmogilevskiy-ics** [comment]
@plamenterziev , Have you found any solution?
