### ISSUE TITLE
I want to add Source to an existing Layer in style

### ISSUE THREAD

**Issue by siavashabdoli** [mapbox/mapbox-gl-native#14992]
Seems there is option in gl-js project that you can Override data that loaded from tile(https://github.com/mapbox/mapbox-gl-js/issues/2289) but I cant find it in gl-native. I want to have styling from server but add geojson in client. like when I want to draw a route. I want to get route source from server and add it to mapbox. but I don't want to add layer from client in hardcoded model

Can I create a layer in style and set a source-id without providing any .pbf source in style and instead add it from client

**Comment by tobrun** [comment]
> Can I create a layer in style and set a source-id without providing any .pbf source in style and instead add it from client

yes, this should work in the same way as gl-js handles it.
