### ISSUE TITLE
Custom roads is it possible?

### ISSUE THREAD

**Issue by Jorgee97** [mapbox/mapbox-gl-native#14994]
I'm building a gps like system for my university, I'm adding custom roads to the map by using a GeoJson, but mapbox does not recognoize those roads when trying to create a navigation route. Is it possible to add custom roads to the map to be used as roads for the navigation sdk? 

![Screenshot from 2019-06-24 22-21-16](https://user-images.githubusercontent.com/8935477/60067050-b70ca780-96ce-11e9-9bef-5bdf16b4755f.png)

**Comment by tobrun** [comment]
Afaik custom roads are not supported, they need to be part of [openstreetmap](https://www.openstreetmap.org/).
