### ISSUE TITLE
MGLSymbolStyleLayer is drawn above MGLPointAnnotation

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#15007]
### Steps to reproduce

 1. Add a MGLSymbolStyleLayer on a mapBox map
 2. Add an MGLPointAnnotation

First I add a Symbol Layer, after that I add an annotation. Annotation is shown below the Symbol layer. i don't get it, the Symbol Layer has to be below the annotations?

```      let directionsymbols = MGLSymbolStyleLayer(identifier: "direction-images", source: sourcedirections)
        directionsymbols.iconImageName = NSExpression(forConstantValue: "direction")
        directionsymbols.iconScale = NSExpression(forConstantValue: 0.5)
        directionsymbols.iconRotation = NSExpression(forKeyPath: "bearing")
        directionsymbols.iconRotationAlignment = NSExpression(mglJSONObject: NSValue.init(mglIconRotationAlignment: .map))
        directionsymbols.iconAllowsOverlap = NSExpression(forConstantValue: true)
             
        style.addLayer(directionsymbols)
        
        for challenge in wr.challenges!
        {
            
            
            let locationNode = CLLocationCoordinate2D(latitude: challenge.latitude, longitude: challenge.longitude)
            let hello = MGLPointAnnotation()
            hello.coordinate = locationNode
            hello.title = "challenge"
            hello.subtitle = ""
            
            self.challengeMarkersOnMap.append(hello)
            
            mapView.addAnnotations(self.challengeMarkersOnMap)
            
        }
``` 
### Expected behavior

MGLPointAnnotation is shown over the MGLSymbolStyleLayer.

### Actual behavior

MGLSymbolStyleLayer is shown over the MGLPointAnnotation

### Configuration

**Mapbox SDK versions:*5.1.0* 
**iOS/macOS versions:*latest* 
**Device/simulator models:*iPhone X*
**Xcode version:*latest*

**Comment by 1ec5** [comment]
Does this code run in `mapView(_:didFinishLoading:)` or `mapViewDidFinishLoadingMap(_:)`?

**Comment by nijs9** [comment]
didFinishLoading...

**Comment by tobrun** [comment]
@nijs9 did you try using [belowLayer](https://docs.mapbox.com/ios/api/maps/5.1.0/Classes/MGLStyle.html#/c:objc(cs)MGLStyle(im)insertLayer:belowLayer:) with an id set to `com.mapbox.annotations.points` instead of using `addLayer`?

**Comment by nijs9** [comment]
@tobrun it’s not clear to me How to implement your suggestion. Any help would be appreciated.

**Comment by bghenriques** [comment]
Hi @tobrun ,
I have the exact same problem: I want my MGLPointAnnotations to appear above a MGLLineStyleLayer, but on the map they appear below!
From your comment on Jun. 27, 2019 I cannot understand how you did it since you have not mentioned any AnnotationImage on your original post.
Thanks!

**Comment by bghenriques** [comment]
Hi @nijs9
I have the exact same problem: I want my MGLPointAnnotations to appear above a MGLLineStyleLayer, but on the map they appear below!
From your comment on Jun. 27, 2019 I cannot understand how you did it since you have not mentioned any AnnotationImage on your original post.
Thanks!
