### ISSUE TITLE
Port `line-sort-key` `circle-sort-key` and `fill-sort-key`

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#15008]
GL JS PR: https://github.com/mapbox/mapbox-gl-js/pull/8467

**Comment by ahk** [comment]
Here's a try: https://github.com/mapbox/mapbox-gl-native/pull/15839

**Comment by chloekraw** [comment]
PR for circle-sort-key: https://github.com/mapbox/mapbox-gl-native/pull/15875

PR for line-* and fill-*: https://github.com/mapbox/mapbox-gl-native/pull/15839
