### ISSUE TITLE
Rename mapID to styleID

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1500]
Per discussion with @willwhite, `-[MGLMapView mapID]` should be renamed `-styleID` for consistency with `-styleURL` and because the mapbox: URL scheme expands to a style API URL rather than one from the TileJSON API.

We'll need to deprecate `-mapID`, update documentation, and issue a warning from within designables if possible.

**Comment by incanus** [comment]
> deprecate

Do we? We're pre-1.0 ;-) I think we can run with this.

**Comment by 1ec5** [comment]
Will anyone be using `-mapID` in beta 1? If so, we’ll need to either support a migration path (including deprecating `-mapID`) or release note the steps to migrate manually (which involve a bit of fiddling if using storyboards).

**Comment by incanus** [comment]
If we have API for `setMapID:`, but no non-Mapboxers with API access, we can push to b2 and just bulk rename and document.
