### ISSUE TITLE
Labels are always drawn above fill layers

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#15006]
To verify this, just move the `water` layer of Mapbox Streets to the top of the style. Labels should appear like they are clipped by the `water` layer. This is behavior observed on Mapbox GL JS:

![Screenshot from 2019-06-26 17-40-38](https://user-images.githubusercontent.com/996307/60189416-8a28d380-9839-11e9-9db2-5effb3fd07d1.png)

But not on GL Native. It doesn't seem like a regression (or at least a recent one) because I managed to reproduce with `android-v6.3.0-alpha.2`

![Screenshot from 2019-06-26 17-47-32](https://user-images.githubusercontent.com/996307/60189985-8b0e3500-983a-11e9-8f19-4a61aae53a48.png)

/cc @troyyip

**Comment by troyyip** [comment]
@tmpsantos thanks for ticketing this issue!

Do we figure out the root issue causing this behavior? This is reported by AutoNavi and they figure out while they are investigating the FBO issue of rendering two maps (Mapbox and AMap). They found that if they move the `water` layer to the top of style, it can solve the abnormal behavior of water layer (the water will be blank in large zoom level for around 30s, and then will show up again).
![ezgif com-optimize (1)](https://user-images.githubusercontent.com/22021312/60322254-90da5680-99b1-11e9-9231-bd909d8f5a92.gif)

Thus, they just curious if we have any special handling to render the `water` layer.

cc:/ @chriswu42 @Cyrussss

**Comment by tmpsantos** [comment]
@jmalanen fixed this on #14839
