### ISSUE TITLE
"improve this map" should start at map viewport

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1501]
Piggybacking off of https://github.com/mapbox/mapbox-gl-native/pull/1497, tapping the attribution control's "improve this map should mirror the center/zoom of the viewport over at https://www.mapbox.com/map-feedback/, presuming that the user wants to improve the map where they were last looking at it. 

This could also possible be tricky depending on what style was shown in GL immediately beforehand and how that might compare to the style used on the feedback page.

**Comment by friedbunny** [comment]
I think we got this in #1498.

**Comment by incanus** [comment]
Indeed!
