### ISSUE TITLE
Native crash when using MultiPoint FeatureCollection with GeoJson point clustering

### ISSUE THREAD

**Issue by Dkhusainov** [mapbox/mapbox-gl-native#15032]
sdk: "com.mapbox.mapboxsdk:mapbox-android-sdk:7.3.0"
Android: 25
reproducer: https://gist.github.com/Dkhusainov/f8cdb539706c42ba3a8c5a0e5802ae53

To run the reproducer add your token and a marker drawable to your project. When you run it, you'll see `terminating with uncaught exception of type mapbox::util::bad_variant_access: in get<T>()" failed`.

This happens if I you pass `GeoJsonOptions().withCluster(true)` to `GeoJsonSource`.

**Comment by tobrun** [comment]
Thank you for reaching out and providing a reproduction case. Capturing from supercluster.hpp documentation:

> Loads an array of GeoJSON Feature objects. Each feature's geometry **must** be a GeoJSON Point. Once loaded, index is immutable.

In your case, you are trying to use multipoint. Was able to get your example code to work with using a FeatureCollection of points instead. See updated example code [here](https://gist.github.com/tobrun/abaa2e19e2c03719142cb7b36c783a81).

Closing this issue as answered.
