### ISSUE TITLE
Extrusion layer is drawn on top of the symbol layer 

### ISSUE THREAD

**Issue by harrynguyenlong** [mapbox/mapbox-gl-native#15039]
### Steps to reproduce

 1. Run "git clone https://github.com/mapbox/mapbox-gl-native.git"
 2. Go to the cloned folder build the file and start the test app.
 3. In the test app, select the setting button -> Add Building Extrusions

### Expected behaviour
Symbol layer is on top of building extrusion layer.

### Actual behaviour
Building extrusion layer is above the symbol layer.

![IMG_0513](https://user-images.githubusercontent.com/16384073/60583501-b9889480-9d93-11e9-8d47-0b0e6d5a214d.PNG)
![IMG_0514](https://user-images.githubusercontent.com/16384073/60583502-ba212b00-9d93-11e9-861a-e8a1e6a98fbe.PNG)
![IMG_0515](https://user-images.githubusercontent.com/16384073/60583504-ba212b00-9d93-11e9-893c-ea832db964e3.PNG)

### Configuration

**Mapbox SDK versions:**  5.2.0-alpha.1
**iOS/macOS versions:** 10.14.6 beta 
**Device/simulator models:** iPhone 8 (12.2)
**Xcode version:** 10.2
[](url)

**Comment by chloekraw** [comment]
Thanks for the report @harrynguyenlong. Root cause could be the same as https://github.com/mapbox/mapbox-gl-native/issues/15006, though interestingly the behavior is the opposite.

cc: @tmpsantos

**Comment by jmkiley** [comment]
May be related to https://github.com/mapbox/mapbox-gl-native/issues/14779

**Comment by Amerkumar** [comment]
We are facing the same issue. Do you have timeline on this?

**Comment by tmpsantos** [comment]
@Amerkumar we will start to work on this issue Jul/8.

**Comment by astojilj** [comment]
Same cause as #14844 and #14779.

**Comment by tmpsantos** [comment]
PR for this issue here: https://github.com/mapbox/mapbox-gl-native/pull/15065

**Comment by tmpsantos** [comment]
Fixed.
