### ISSUE TITLE
Native crash on Android 5.1 in Google play 

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#15034]
Error in Google Play crash report:
```
backtrace:
  #00  pc 0000000000040a18  /system/lib64/libc.so (dlfree+408)
  #01  pc 0000000000013380  /system/lib64/libc.so (free+20)
  #02  pc 00000000000d9d50  /system/vendor/lib64/egl/libGLESv2_adreno.so (rb_delete_detach_vbo_list+96)
  #03  pc 00000000000e0008  /system/vendor/lib64/egl/libGLESv2_adreno.so (rb_perform_resolve+384)
  #04  pc 00000000000e0488  /system/vendor/lib64/egl/libGLESv2_adreno.so (rb_resolve+524)
  #05  pc 000000000009d868  /system/vendor/lib64/egl/libGLESv2_adreno.so (core_glFinish+28)
  #06  pc 000000000007ba20  /system/vendor/lib64/egl/libGLESv2_adreno.so (glFinish+20)
  #07  pc 0000000000283c68  /data/app/com.hubbmap-1/lib/arm64/libmapbox-gl.so
  #08  pc 0000000000283cbc  /data/app/com.hubbmap-1/lib/arm64/libmapbox-gl.so
  #09  pc 00000000000e2314  /data/app/com.hubbmap-1/lib/arm64/libmapbox-gl.so
  #10  pc 000000000003aa1c  /data/app/com.hubbmap-1/lib/arm64/libmapbox-gl.so
  #11  pc 00000000003cf1c8  /data/dalvik-cache/arm64/data@app@com.hubbmap-1@base.apk@classes.dex
```

### Steps to reproduce
I dont know. But user feedback says: crash on start app (open mapbox map) and not reproduce on previous app version with mapbox 7.3.2 (and geojson 4.6.0) . App use custom map style(basic streets style) and some layers with geoJson source.

### Configuration

**Android versions:** Android 5.1
**Device models:** Xiaomi Redmi 3 (3072 МБ, **Qualcomm MSM8939**, 720x1280), Huawei ShotX (2048 МБ, **Qualcomm MSM8939**, 1080x1920)
**Mapbox SDK versions:** 8.0.0 (and mapbox-sdk-geojson:4.8.0)

**Comment by Chaoba** [comment]
Test android demo on Redmi Note 3 (5.0.2) in Ali cloud, not found this issue. There is no Redmi 3 or ShotX on Ali cloud.
@klblk Is there any other phone could find this issue?

**Comment by alexshalamov** [comment]
Fixed by https://github.com/mapbox/mapbox-gl-native/pull/15978
