### ISSUE TITLE
Updating MLUserAnnotation with own CLLocation

### ISSUE THREAD

**Issue by MaikoHermans** [mapbox/mapbox-gl-native#15042]
This is not really an issue, more of a question that possibly more people might find useful.

I'm currently working on a feature where I want to share the GPS location of an iPhone over bluetooth to a iPad. Sending the data from one device to the other is all working fine.

The issue is with actually updating the mapbox mapview to display this location. I can't find anything in the documenation about manipulating the MLUserAnnotation (not even sure if it's possible).

So I was wondering is there a way we can manipulate the user location ourselfs by specifying where this location should be at any given point.

**Comment by julianrex** [comment]
Hi @MaikoHermans

You'll want to look at `MGLMapView.locationManager` and provide your own object that conforms to `MGLLocationManager`. It sounds like this should be a straight-forward wrapper around code you already have.

We'd love to see the results when you have something!

/cc @fabian-guerra
