### ISSUE TITLE
Scale Bar is broken on zoom levels 1/2/3/4

### ISSUE THREAD

**Issue by racer1988** [mapbox/mapbox-gl-native#15045]
### Steps to reproduce

 1. Open the map
 2. Zoom

### Expected behavior

* Scale Bar is showing all zoom leves

### Actual behavior

* Scale Bars is broken on zoom levels 1/2/3/4

### Configuration

**Mapbox SDK versions:** 5.1.1

![Screenshot 2019-07-03 at 11 56 23](https://user-images.githubusercontent.com/1517398/60583009-3151c180-9d8a-11e9-80ca-eb984b8edbc6.png)

![Screenshot 2019-07-03 at 11 56 35](https://user-images.githubusercontent.com/1517398/60583021-357ddf00-9d8a-11e9-85f8-6f2f23fba24c.png)

**Comment by julianrex** [comment]
Thanks @racer1988!

**Comment by friedbunny** [comment]
Automatically hiding the scale bar at ~z1-z4 is actually intentional and is [mildly documented](https://github.com/mapbox/mapbox-gl-native/blob/12e0a6b0c67bc2356dbe83d7ab19efdd9a3dc2ea/platform/ios/src/MGLMapView.h#L293):

> The scale bar may not be shown at all zoom levels.

Here’s the logic that controls the allowable range of distances the scale bar can show:

https://github.com/mapbox/mapbox-gl-native/blob/12e0a6b0c67bc2356dbe83d7ab19efdd9a3dc2ea/platform/ios/src/MGLScaleBar.mm#L264-L283

**Comment by friedbunny** [comment]
We can consider this as a feature request, though — much as we’re adding `visibility` customization to the compass (https://github.com/mapbox/mapbox-gl-native/issues/9562#issuecomment-316772669), we could follow MapKit’s lead again and add a similar configuration option to the scale bar.

**Comment by racer1988** [comment]
@friedbunny I am happy to it not be shown at zoom 1-4.
However this is a *Bug*.

The Scale Bar is shown Squashed

**Comment by friedbunny** [comment]
Ah, I see, apologies @racer1988... I can’t reproduce this bug, in that case. 😄 The labels do bunch up after the bar disappears, but they disappear very quickly (~hundreds of milliseconds) soon after.

Could you say more about how’re you’re using the scale bar? Is it enabled via `MGLMapView.showsScale` or more directly via `MGLMapView.scaleBar.hidden`?

**Comment by racer1988** [comment]
I Hide the scalebar with a timer when the user stop zooming:

```
UIView.animate(withDuration: 0.3, delay: 0.0, options: .beginFromCurrentState, animations: { [weak self] in
            self?.mapView.scaleBar.alpha = 0.0
        }) { [weak self] _ in
            self?.mapView.showsScale = false
        }
```

and when the zoom starts I show it

```
mapView.scaleBar.alpha = 1.0
        mapView.showsScale = true
```

**Comment by racer1988** [comment]
@friedbunny Found a way to reproduce consistently.
for me the squashed labels are disappearing only after the gesture is finished completely.

So if I zoom back and keep my fingers on the map, the labels stay squashed.

In that case the label and the bar should disappear together and not be indipendentely hidden (at different times)

**Comment by racer1988** [comment]
https://www.dropbox.com/s/rx9azhf5aw1blnv/test.mov?dl=0

**Comment by racer1988** [comment]
```
private func handleZoomOnScale() {
        guard configuration.showsScale else {
            return
        }
        
        mapView.scaleBar.alpha = 1.0
        mapView.showsScale = true
        
        hideScaleTimer?.invalidate()
        hideScaleTimer = Timer.scheduledTimer(withTimeInterval: 2.0, repeats: false, block: { [weak self] (timer) in
            guard timer.isValid else {
                return
            }
            
            self?.hideScale()
        })
    }
    
    private func hideScale(animated: Bool = true) {
        hideScaleTimer?.invalidate()
        hideScaleTimer = nil
        guard animated == true else {
            mapView.showsScale = false
            return
        }
        UIView.animate(withDuration: 0.3, delay: 0.0, options: .beginFromCurrentState, animations: { [weak self] in
            self?.mapView.scaleBar.alpha = 0.0
        }) { [weak self] _ in
            self?.mapView.showsScale = false
        }
    }

```

**Comment by racer1988** [comment]
```
func mapView(_ mapView: MGLMapView, regionIsChangingWith reason: MGLCameraChangeReason) {
        
        if reason.contains(.gesturePinch) ||
            reason.contains(.gestureZoomIn) ||
            reason.contains(.gestureZoomOut) {
            handleZoomOnScale()
        }
}
```
