### ISSUE TITLE
/Downloads/mapbox-gl-native-master-3/build/ios/config.xcconfig: unable to open file (in target "dynamic" in project "ios") (in target 'dynamic')

### ISSUE THREAD

**Issue by pjl1234567** [mapbox/mapbox-gl-native#15046]
When I run this program, why does this error occur？
/Downloads/mapbox-gl-native-master-3/build/ios/config.xcconfig: unable to open file (in target "dynamic" in project "ios") (in target 'dynamic')

**Comment by julianrex** [comment]
Building the iOS project from source requires several dependencies and other build tools. Please see https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md
