### ISSUE TITLE
Enable batch conversion of latlngs to/from screen coordinates

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-native#15043]
Our mobile SDKs contain a [Projection](https://docs.mapbox.com/android/api/map-sdk/5.0.2/com/mapbox/mapboxsdk/maps/Projection.html) class that translates between on-screen location and geographic coordinates on the surface of the Earth. Screen location is in screen pixels with respect to the top left corner of the map.

Currently the `to/fromScreenLocation` methods only accept a single latlng as an input. Customers are requesting the ability to pass in an array of latlngs that can be batch converted to (x,y) screen coordinates. Because the SDK sends the coordinates to core for conversion and then the outputs are sent back to the SDK, you have to cross the bridge many times for multiple latlngs in the status quo. Accepting bulk latlngs would be a performance improvement. 

A customer has implemented the following:
- Pass in a byte buffer of a predefined array of latlngs. A byte buffer is used instead of a java array so that it's quicker for the native code to go through
- Call the native function that uses cache projection to convert those latlngs into (x,y) screen coordinates 

cc @zugaldia @tmpsantos

**Comment by julianrex** [comment]
Interesting timing @chloekraw 😄 

This could offer a significant performance improvement in some situations - since we only need to calculate the projection matrix once for a number of positions. This would be very useful as I dig into accessibility improvements on iOS.

This should be pretty quick to add too.

**Comment by chloekraw** [comment]
Fixed by https://github.com/mapbox/mapbox-gl-native/pull/15891

**Comment by chloekraw** [comment]
@zmiao thanks for landing https://github.com/mapbox/mapbox-gl-native/pull/15891! you mentioned [here](https://github.com/mapbox/mapbox-gl-native/pull/15891#issuecomment-552903991) that 
> for the performance issue, it will be done as a separate issue. After refactoring, the perfomance will be improved, but from SDK point of view, the most performance critical part is actually by invoking the API, which is already done in this pr.

Has this performance refactor been done yet? Is it being tracked anywhere else, or should we repurpose this ticket for doing so?

**Comment by zmiao** [comment]
@chloekraw , the performance refactor is done in https://github.com/mapbox/mapbox-gl-native/pull/15956

**Comment by chloekraw** [comment]
@zmiao okay great, thanks! closing this ticket then 👍
