### ISSUE TITLE
download offline map the SymbolLayer can not show text  and the draw Region can not queryRenderedFeatures

### ISSUE THREAD

**Issue by wlwu** [mapbox/mapbox-gl-native#15067]
### Steps to reproduce

 1. SymbolLayer areaNameLayer = new SymbolLayer
 2.
                SymbolLayer areaNameLayer = new SymbolLayer(styleBuiler.getAreaNameLayerId(), styleBuiler.getSourceId()+"areaName");
                List<PropertyValue<?>> namePropertySource = new ArrayList<>();
                if (!TextUtils.isEmpty(styleBuiler.getAreaNameColor())) {
                    PropertyValue<String> value = PropertyFactory.textColor(Color.parseColor(styleBuiler.getAreaNameColor()));
                    namePropertySource.add(value);
                }
                if (styleBuiler.getAreaNameColorRes() != 0) {
                    PropertyValue<String> value = PropertyFactory.fillColor(styleBuiler.getAreaNameColorRes());
                    namePropertySource.add(value);
                }
                if (styleBuiler.getAreaNameTextSize() > 0) {
                    PropertyValue<Float> value = PropertyFactory.textSize(styleBuiler.getAreaNameTextSize());
                    namePropertySource.add(value);
                }
                PropertyValue<String> areaNameProperty = PropertyFactory.textField(styleBuiler.getAreaName());
                namePropertySource.add(areaNameProperty);

                PropertyValue<Boolean> overLapProperty = PropertyFactory.textAllowOverlap(true);
                namePropertySource.add(overLapProperty);

                PropertyValue<?>[] PropertyNameValueSource = new PropertyValue<?>[namePropertySource.size()];
                for (int i = 0; i < namePropertySource.size(); i++) {
                    PropertyNameValueSource[i] = namePropertySource.get(i);
                }
                areaNameLayer.withProperties(PropertyNameValueSource);
 3.  mMapStyle.addLayerAbove(areaNameLayer, builderName.getRelativeLayerId());

### Expected behavior
the text can show

### Actual behavior
the text no show when download the offline map

### Configuration

**Android versions:** 
**Device models:** 
**Mapbox SDK versions:**

**Comment by tobrun** [comment]
@wlwu to show symbols on an offline map, you will need to use a `textFont` from the downloaded offline region. By default it will try to download another font and since you don't have an internet connection we can't download and render it. This issue is the same as documented in https://github.com/mapbox/mapbox-plugins-android/issues/970. Let us know if this workaround doesn't work.
