### ISSUE TITLE
LocationComponent.forceLocationUpdate(Location) does not animate

### ISSUE THREAD

**Issue by kenichim-flictec** [mapbox/mapbox-gl-native#15075]
Since v8.2.0 Android, LocationComponent.forceLocationUpdate(location) does not animate and location marker jump-to new location

### Steps to reproduce

 1. locationComponent.forceLocationUpdate(location) with release 8.1.0
 2. Confirm smooth animation on Location marker
 3. locationComponent.forceLocationUpdate(location) with release 8.2.0-alpha.2
 4. No animation

### Expected behavior
smooth animation with 8.2.0-alpha.2

### Configuration
            LocationComponentActivationOptions options =
                    LocationComponentActivationOptions.builder(activity.getApplicationContext(), mapboxMap.getStyle())
                            .locationEngine(null)
                            .useDefaultLocationEngine(false).build();

            mLocationComponent = mapboxMap.getLocationComponent();
            mLocationComponent.activateLocationComponent(options);
            mLocationComponent.setLocationComponentEnabled(true);
            mLocationComponent.setCompassEngine(null);
            mLocationComponent.setRenderMode(RenderMode.GPS);
        }

**Android versions:** 
9.0
**Device models:** 
Xperia XZ1
**Mapbox SDK versions:** 
8.2.0-alpha.2

**Comment by LukasPaczos** [comment]
Hey @kenichim-flictec, thanks for reaching out.

Unfortunately, I'm unable to reproduce:
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/16925074/61046710-13b1d700-a3de-11e9-820c-8e2e95da94c7.gif)

Would you be able to share a bit more about your setup, or preferably a full, isolated example? Thanks!

**Comment by kenichim-flictec** [comment]
Hi,

In my case, the map and the location marker animate at the same time like navigation app with heading-up tracking.
Map animation is smooth but maker isn’t.
I’ve tried to repro the bug with https://github.com/mapbox/mapbox-navigation-android but I couldn’t.
(Updated sdk version to 8.2.0-alpha.2 and run a route simulation)
Mapbox-navigation looks OK.
So, maybe there are issues on our side. Please feel free to close and if I found more info, I will let you know.

Kenichi


送信元: Łukasz Paczos <notifications@github.com>
Reply-To: mapbox/mapbox-gl-native <reply@reply.github.com>
日付: 2019年7月11日 木曜日 20:17
宛先: mapbox/mapbox-gl-native <mapbox-gl-native@noreply.github.com>
Cc: Miyazaki Kenichi <kenichim@flictec.com>, Mention <mention@noreply.github.com>
件名: Re: [mapbox/mapbox-gl-native] LocationComponent.forceLocationUpdate(Location) does not animate (#15075)


Hey @kenichim-flictec<https://github.com/kenichim-flictec>, thanks for reaching out.

Unfortunately, I'm unable to reproduce:
[ezgif com-video-to-gif (1)]<https://user-images.githubusercontent.com/16925074/61046710-13b1d700-a3de-11e9-820c-8e2e95da94c7.gif>

Would you be able to share a bit more about your setup, or preferably a full, isolated example? Thanks!

**Comment by LukasPaczos** [comment]
Thanks @kenichim-flictec. I'm gonna go ahead and close for now, but please let us know if the issue turns out to actually be due to the Maps SDK.
