### ISSUE TITLE
Android build aar with arm-v7 & x86 ABIs together and separately

### ISSUE THREAD

**Issue by AliKhoshraftar** [mapbox/mapbox-gl-native#15080]
Hi , i wanna build aar with arm-v7 & x86 ABIs together and separately.

### Steps to reproduce

 1.BUILDTYPE=Release make android-lib-arm-v7 -> build success with 2.5Mb size
 2.BUILDTYPE=Release make android-lib-x86 -> build success with 4.5Mb size ( combines with arm-v7 )
 3.BUILDTYPE=Release make android-lib-arm-v7 -> build success with 4.5Mb size ( x86 also combines with it )

### Expected behavior

By the step 3 i wanna make aar only with arm-v7 standalone.

### Actual behavior

Because of step 2 that i build with x86 abi , it combine with that together and build an 4.5Mb aar that i don't want it.
I used 'make clean' command but it deletes some folders that made me to rebuild project but after that when i did step 1 , it built an 4.5Mb aar ( it has an history that append abis everytime make command runs ).

### Configuration

**Android versions:** No Need
**Device models:** No Need
**Mapbox SDK versions:** 7.4.0 & 8.1.0

**Comment by tobrun** [comment]
@AliKhoshraftar we do not give support for building from source, when consuming binaries you can use abi filters and apk split to filter out unwanted abis
