### ISSUE TITLE
[macos] OnlineFileSource.ConnectionError test is flaky

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#15096]
The `OnlineFileSource.ConnectionError` test on `macos-debug` [can fail with](https://circleci.com/gh/mapbox/mapbox-gl-native/298041):

```
[ RUN      ] OnlineFileSource.ConnectionError
/Users/distiller/project/test/storage/online_file_source.test.cpp:101: Failure
Expected: (wait + 0.2) > (duration), actual: 3.2 vs 3.21111
Backoff timer fired too late
[  FAILED  ] OnlineFileSource.ConnectionError (3212 ms)
```

Seems like this has been an issue in the past: https://github.com/mapbox/mapbox-gl-native/issues/9650

/cc @brunoabinader

**Comment by brunoabinader** [comment]
@tmpsantos I think we should avoid time-based assertions in shared CI environments.

**Comment by tmpsantos** [comment]
> @tmpsantos I think we should avoid time-based assertions in shared CI environments.

+1
