### ISSUE TITLE
How to display image with url in MKPointAnnotation? 

### ISSUE THREAD

**Issue by ajayPris** [mapbox/mapbox-gl-native#15098]
Hello Guys,

in my iOS app i want to display user profile picture (which is in url form) in marker. i had tried many ways but its not working!. 

### Expected behavior
it will load custom image from server url.

### Actual behavior
in annotation user can add only UIImage not able to load image from url.

### Configuration

**Mapbox SDK versions:** 4.9.0)
**iOS/macOS versions:** 10.14
**Device/simulator models:** in all devices (OS 12.3.1)
**Xcode version:** 10.1

**Comment by friedbunny** [comment]
Hi @ajayPris — thanks for using Mapbox. This repo is for reporting bugs, requesting features, and coordinating work related to the various Mapbox Map SDKs. For help with “how do I” questions, please ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox) or reach out to our excellent [support team](https://www.mapbox.com/contact/support/).

**Comment by ajayPris** [comment]
hello @friedbunny, i am asking that is it possible to display image from url in PointAnnotation, as right now it's only allow me to set image from directory or individual image , there is no way to add image from url or set image in annotation , please consider it as a new feature , like set annotation image from url.
Thanks, waiting for positive response.

**Comment by julianrex** [comment]
Thanks @ajayPris - I've tagged this issue as a feature request.

**Comment by ajayPris** [comment]
Hello Team,
is there any chance to get this functionality in next update ! can you please open this issue as a feature request !

**Comment by friedbunny** [comment]
> in annotation user can add only UIImage not able to load image from url.

You should use system APIs to load remote images before attempting to use them in annotations on a map — handling the async network requests and such isn’t functionality that I see us adding.

**Comment by ajayPris** [comment]
@friedbunny, thanks for your response , as you have mention i need to download remote images first and then it will be use as annotation image but i have large amount of data which can be around 1k to 15k then it'll be messy and large memory consuming  apart from this, Is there any way to set image view like google map have in annotation imageView so we can use directly remote image from url.
