### ISSUE TITLE
Mapbox-ios USES MGLImageSource to remove the source and adds the error for the second time

### ISSUE THREAD

**Issue by songyuyang0918** [mapbox/mapbox-gl-native#15101]
I obtained network data (including point coordinates and network image address) through AFNetWorking, and added MGLImageSource objects through loop.
Test: generate a MGLImageSource object from "identifier" and remove the object with "identifier" (layerWithIdentifier, sourceWithIdentifier).
Then, reuse the "identifier" to generate a MGLImageSource object and report that the error exists.

The "identifier" values in the tests are all the same.

I wonder why?
Didn't I delete it? But the image I called (removeSource, removeLayer) did disappear.
All of these operations are performed in the main thread

![511562841257_ pic_hd](https://user-images.githubusercontent.com/15685672/61044318-fa734f80-a40a-11e9-85fa-d5a400913814.jpg)

**Comment by friedbunny** [comment]
If this is a bug report, please follow the issue template and provide information that we can use to resolve the issue — a reproduction, which version of the SDK it’s happening in, and so on. Thanks!
