### ISSUE TITLE
Using fastlane snapshot on my view controller with mapbox causes failure

### ISSUE THREAD

**Issue by mylogon341** [mapbox/mapbox-gl-native#15108]
### Steps to reproduce

 1. Have view controller with mapbox view
 2. Setup fastlane snapshot
 3. In script, navigate to view (testing purposes, a single view app will suffice)
 4. Wait for map to load `sleep(5)` for example
 5. Run `snapshot("01Mapview")`

### Expected behavior

Produce screenshot UITest to pass

### Actual behavior

Error is thrown, saying it is unable to find any windows to screenshot.

### Configuration

**Mapbox SDK versions:** 5.0
**iOS/macOS versions:**  iOS 12.2
**Device/simulator models:** iPhone 8
**Xcode version:** 10.2.1

**Comment by mylogon341** [comment]
Note that standard screenshots work in the simulator and on device.

**Comment by mylogon341** [comment]
It is also worth noting that if I set `isHidden` to true on the mapbox view, the screenshot is successful.

**Comment by mylogon341** [comment]
This did not work for 3 days. I went to run it to get actual error messages and it now works -_-

**Comment by julianrex** [comment]
@mylogon341 please reopen if you continue to see issues.
