### ISSUE TITLE
can not download

### ISSUE THREAD

**Issue by Founder005** [mapbox/mapbox-gl-native#15119]
ERROR: Unable to resolve dependency for ':m_app@debugUnitTest/compileClasspath': Could not download mapbox-android-sdk.aar (com.mapbox.mapboxsdk:mapbox-android-sdk:8.1.0)
### Steps to reproduce

 1.
 2.
 3.

### Configuration

**Android versions:** 
**Device models:** 
**Mapbox SDK versions:** 8.1.0

**Comment by tobrun** [comment]
It's available [here](https://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-sdk/8.1.0/) however. Without any additional information this isn't actionable, this seems like a temporary maven issue that is out of our control.

**Comment by Founder005** [comment]
Maybe it's a maven issue,I don't know,but I add another maven url 'https://maven.aliyun.com/repository/jcenter',  it's OK now.
