### ISSUE TITLE
App crashes after downloading a large amount of raster tiles

### ISSUE THREAD

**Issue by Pxddy** [mapbox/mapbox-gl-native#15126]
Hey Mapbox crew,

we noticed a regression while using the offline region download function. I guess it was introduced with the new 8.2.0 alphas because it was working without any problems before..

It seems to be related to this one: https://github.com/mapbox/mapbox-gl-native/issues/14740

### Steps to reproduce

Download several regions one by one.
Create all offline regions at the beginning but have only one download active at a time and set the remaining downloads inactive. Start the next download when the active one finished.
This should happen in the same Service because otherwise the bug won't appear.
After some time you will notice that a lot of Garbage Collection is going on and also logs like:

Long monitor contention with owner OkHttp ... (5103) at void okio.AsyncTimeout.scheduleTimeout(okio.AsyncTimeout, long, boolean)(AsyncTimeout.java:-1) waiters=4 in void okio.AsyncTimeout.scheduleTimeout(okio.AsyncTimeout, long, boolean) for 126ms

or

Long monitor contention with owner OkHttp ... (5098) at void okhttp3.internal.connection.RouteDatabase.connected(okhttp3.Route)(RouteDatabase.java:-1) waiters=6 in void okhttp3.internal.connection.RouteDatabase.connected(okhttp3.Route) for 181ms

And finally the App will crash.

We are loading the raster tiles from our own Server so we shouldn't be limited by the tile count limit.

### Expected behavior

Download all regions without crashing

### Actual behavior

After some time a lot of Garbage Collection events will appear and the App will crash :(

### Configuration

**Mapbox SDK versions:** 8.2.0-alpha.3

**Comment by LukasPaczos** [comment]
Thanks for reporting the issue @Pxddy. https://github.com/mapbox/mapbox-gl-native/pull/15330 is available in the `8.3.0-alpha.2`, would you be able to retest your case? Thank you!

**Comment by Pxddy** [comment]
Hey @LukasPaczos ,

thank you for your effort but unfortunately this doesn't fix the issue. :(

I got some additional information for you which could help to narrow down the error. The issue seems to only occur when the device is getting low on memory. 

Lets say you have 900MB available on your device storage and start download tiles worth of 600MB. This will most likely trigger the issue.

Best Regards!

**Comment by chloekraw** [comment]
cc @pozdnyakov
