### ISSUE TITLE
setMaximumAmbientCacheSize megabytes or bytes?

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-native#15140]
In https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/MGLOfflineStorage.h#L384 the docs first says "Sets the maximum ambient cache size in megabytes", then "@param cacheSize The maximum size in bytes for the ambient cache". This is a bit confusing.

**Comment by julianrex** [comment]
@halset thanks - this is definitely confusing, and [we've discussed before](https://github.com/mapbox/mapbox-gl-native/pull/14978#discussion_r303676321).

@jmkiley @chloekraw please can we address this in the tail work PR https://github.com/mapbox/mapbox-gl-native/pull/15131?

**Comment by langsmith** [comment]
cc myself @langsmith to follow along as I work on https://github.com/mapbox/android-docs/pull/995 and https://github.com/mapbox/mapbox-android-demo/pull/1139

**Comment by jmkiley** [comment]
Thanks for flagging @halset!

**Comment by chloekraw** [comment]
Confirming that `setMaximumAmbientCacheSize` accepts bytes in core, and iOS should be changed to bytes: https://github.com/mapbox/mapbox-gl-native/pull/14925/files#diff-dd34e25c487b3682d5e1eaff37341b6aR138

core docs: https://github.com/mapbox/mapbox-gl-native/pull/14925/files#diff-fc1f38c847199e960f69c0b2501af3d0R220
Android docs: https://github.com/mapbox/mapbox-gl-native/pull/14962/files#diff-91eb1a5c5cdfa3b0224e1ea4ba140e65R401

cc @tmpsantos @tobrun

**Comment by jmkiley** [comment]
Closed via #
