### ISSUE TITLE
GeoJsonSource/FillExtrusionLayer causes repeated [HTTP] Request with response = 304

### ISSUE THREAD

**Issue by bscheurman** [mapbox/mapbox-gl-native#15145]
There appears to be heavy/frequent network usage when displaying a geojson layer from a url. This could be intended to keep the geojson feature updated when the online geojson files changes. But it looks excessive. Is this intended, and will it result in data costs or server congestion?

Its using the geojson source to feed a FillExtrusionLayer, but I dont know if that contributes to the issue.

### Steps to reproduce

 1. GeoJsonSource gsource = (GeoJsonSource)mapboxMap.getStyle().getSource("source-geojson", <url to geojson>);
 2. FillExtrusionLayer layer3D = new FillExtrusionLayer(...)
 3. mapbox.getStyle().addLayer(layer3D,..)

### Expected behavior
adds 3D extrusion on map
It updates the shape if the online geojson changes

### Actual behavior
logcat shows several HTTP Request response 304s per second ongoing as long as the map is up. Profiler shows ongoing requests to my geojson url.

```
2019-07-17 15:08:30.357 D/Mbgl-HttpRequest: [HTTP] Request with response = 304: No additional information
2019-07-17 15:08:30.377 D/Mbgl-HttpRequest: [HTTP] Request with response = 304: No additional information
2019-07-17 15:08:30.536 D/Mbgl-HttpRequest: [HTTP] Request with response = 304: No additional information
2019-07-17 15:08:31.600 D/Mbgl-HttpRequest: [HTTP] Request with response = 304: No additional information
2019-07-17 15:08:31.749 D/Mbgl-HttpRequest: [HTTP] Request with response = 304: No additional information
```
### Configuration

**Android versions:**  Android P
**Device models:** 
**Mapbox SDK versions:** 8.0.1

**Comment by tmpsantos** [comment]
@bscheurman Mapbox GL will request again the resource when it expires. I think it could be that the date of the server or client is wrong or the HTTP server is setting expiration time too short.

Can you give us the geojson url or the a dump of the HTTP headers for the request?

**Comment by bscheurman** [comment]
The url is from firebase storage. but you're right I think it expires immediately.
