### ISSUE TITLE
Error while building or running the MapboxGLAndroidSDKTestApp

### ISSUE THREAD

**Issue by glencaliba** [mapbox/mapbox-gl-native#15150]
Hello I was trying to build and running the MpaboxGLAndroidSDKTestApp and gives me the next error :

Running 'npm install' for mapbox-gl-js...

### Steps to reproduce

 1. Open the project in the root directory using the command make aproj
 2. Try to build or run the MapboxGLAndroidSDKTestApp.
 3. Gives me the next error 👍 

Error configuring CMake server 
(*****/Android/sdk/cmake/3.10.2.4988404/bin).
Check for working CXX compiler: *****/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
Check for working CXX compiler: *****/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Check for working C compiler: *****/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
Check for working C compiler: *****/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Updating submodules...
Running 'npm install' for mapbox-gl-js...
Finished 'npm install' for mapbox-gl-js...
CMake Error at cmake/mbgl.cmake:54 (message):
  NPM install failed:

Call Stack (most recent call first):
  cmake/mbgl.cmake:100 (_npm_install)
  CMakeLists.txt:37 (include)

Configuring incomplete, errors occurred!
See also "*****/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/x86/CMakeFiles/CMakeOutput.log".

**Comment by LukasPaczos** [comment]
@tmpsantos any idea what this might be caused by? I'm running into the same issue on a Mac.

@glencaliba the workaround is to comment out the faulty line `100` in the `cmake/mbgl.cmake`. It's only responsible for our render tests and does not impact other builds.

**Comment by glencaliba** [comment]
I guess that is because they try to execute npm install mapbox-gl-js and that repository doesn't exisit.
After commenting the line 100 from  cmake/mbgl.cmake gives me another error : 

Execution failed for task ':MapboxGLAndroidSDKTestApp:transformClassesWithInstantRunForDebug'.
> com.android.build.api.transform.TransformException: java.lang.IllegalStateException: java.lang.IllegalStateException

**Comment by glencaliba** [comment]
Hello, 
It keeps me giving the same error. If I build it with Android Studio goes fine but when I try to run ir gives me the same error:
 com.android.build.api.transform.TransformException: java.lang.IllegalStateException: java.lang.IllegalStateException

Should I use an specific version from the tools are required or is any documentation how to run it.
Thanks in advence

**Comment by LukasPaczos** [comment]
I understand that you went through [the required dependencies list](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android#installing-dependencies)? What's your version of NDK? You should run r19/r20.

**Comment by glencaliba** [comment]
I find the problem.
I've just turned off  Insta Run, after that gives me problems with Telemetry. I comment it in the MapboxApplication.java and at the moment it works.
