### ISSUE TITLE
android cluster

### ISSUE THREAD

**Issue by wlwu** [mapbox/mapbox-gl-native#15152]
I want to cluster the layer with point,but have some point I will caclute zero,I found have not the  clusterProperties .can you give me some idea.

### Steps to reproduce

 1.
 2.
 3.

### Expected behavior
I want to calculate with some condition.

### Configuration

**Android versions:** 
**Device models:** 
**Mapbox SDK versions:** 
tha lasted or 7.3

**Comment by tobrun** [comment]
Cluster properties is in the works [here](https://github.com/mapbox/mapbox-gl-native/issues/14043).
For more support questions, please reach out to either stackoverflow or https://www.mapbox.com/contact/.
This repository is used for requesting features and reporting bugs.
