### ISSUE TITLE
stronger enforcement of dev opt-out setup

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1516]
We should take a stronger stance on making sure devs: 

* Provide users with a way to opt-out, and know that they should. 
* Collect metrics by default. 
* Know about the `Settings.bundle` option. 

In working on metrics testing for #1491, I couldn't figure out why my metrics weren't behaving properly. It turns out my test app (`test/ios/ios-tests.xcodeproj`) didn't implement a `Settings.bundle` and was not collecting any metrics. 

We should probably take a stronger approach, such as: 

* Asserting that a `Settings.bundle` exists at first run instead of just logging about it. 
* Allowing for a class method (e.g. `[MGLMapboxEvents setShowsOptOutInApp:YES]`) which a dev has to implement in their code to work around the above. 

@mapbox/mobiledata @1ec5 @gundersen

**Comment by friedbunny** [comment]
The :information_source: button will be a good place to always offer the opt-out, once that becomes more a custom view.

**Comment by incanus** [comment]
That only gets ahead of metrics collection once a map view has been shown, though.

**Comment by gundersen** [comment]
> stronger stance on making sure devs: 
> provide users with a way to opt-out

Great point @incanus. We should make an awesome page on this, maybe even put a section on the new /mobile. Other mapping apps, especially Apple, have it so buried on how to opt out. We really should push opting out as a feature; something that is great for anyone that wants supper low battery usage or just folks that don't like the idea of anyone collecting their data.

**Comment by 1ec5** [comment]
> It turns out my test app (`test/ios/ios-tests.xcodeproj`) didn't implement a `Settings.bundle` and was not collecting any metrics.

I fixed this in e839c2aa21592d9e1c09736a55a4044def9357e3 for #1491. The issue was that `-[NSUserDefaults registerDefaults:]` was being called in `-init` instead of `+initialize`.

**Comment by bleege** [comment]
Added explicit checks for End User Opt Out ability to be implemented by the developer in 48e21ae6e915aecf24022e7ba568d436d876160b.  This can done via 2 ways:

1. Set `[MGLAccountManager setShowsOptOutInApp:YES]` in AppDelegate
1. Check for existence of `Settings.bundle` file via NSAssert that fails program if not satisfied

This code is based off the latest `ios-b1` branch and is available in the `1516-opt-out-checking` branch.

**Comment by bleege** [comment]
PR #1520 was erroneously setup vs the `master` branch instead of today's new `ios-beta1` branch.  Thanks @jfirebaugh for catching this!

**Comment by incanus** [comment]
If we dev off of `ios-b1`, things _should_ merge cleanly later, but if we commit b1-critical stuff to `master`, then cherry pick them over to `ios-b1`, they _definitely will_.

**Comment by friedbunny** [comment]
> That only gets ahead of metrics collection once a map view has been shown, though.

Hrm, I hadn't considered never-sending-metrics as a problem Mapbox was addressing. Theoretically, a user could download a MBGL-using app, open up Settings.app, turn off metrics, and then launch the app, never sending metrics data in.

But it seems like, practically speaking, unless there's an opt-in alert prompt (which isn't on the table and would be a terrible UX/business decision), virtually every user will have some metrics collected before they're able to opt out. It seems to me that most users likely won't ever be aware there is something to opt out of, if a Settings.app switch is enough.

**Comment by 1ec5** [comment]
> The :information_source: button will be a good place to always offer the opt-out, once that becomes more a custom view.

Filed as #1519.

**Comment by bleege** [comment]
Re-switched PRs so that #1520 is now the primary as it has the correct flow of `dev_branch` --> `master` --> `ios-b1`.

**Comment by bleege** [comment]
Just implemented the fixes that @1ec5 suggested in his code review from last night.  The technical core of this issue has now been implemented and tested.  The :information_source: issue is tracked elsewhere, so once Travis approves we should be good to merge this into `master` and then cherrypick back to `ios-b1` if we're feeling good about things.

**Comment by bleege** [comment]
Travis just approved and I merged #1520 into `master`.  It's ready to be merged into `ios-b1` should we choose.  I'll leave this issue open to remind us to think about this later today.

**Comment by 1ec5** [comment]
If we take these changes for beta 1, we should update [the wiki](https://github.com/mapbox/mapbox-gl-native/wiki/Installing-Mapbox-GL-for-iOS#configuring-mapbox-metrics) and mapbox/mapbox-gl-ios to point out the extra step when implementing the opt-out in-app.
