### ISSUE TITLE
Problem with displaying geojson infor after refreshing it

### ISSUE THREAD

**Issue by AlexeyIke** [mapbox/mapbox-gl-native#15168]
Hellow. 

We have android map app showing on map traffic and road poi (point of interest) information  showing via geojson.
Geojson has headers:  cache-control: max-age=60, must-revalidate - should updated every 60 seconds
With android SDK   6 - 7 version everything works well. On Latest 7x version people notise problem - application load latest geojson file, display it, but some time lately after next try to load fresh geojson - (usually app recieve 304 cos it not changed )  and display geojson from pre - previous load -  old incorrect information. Looks like application load from somewhere very cached load.
Usually it fixed by deleting app data with mbgl-offline.db file -  app load freash geojson and some time all works well, but after some time peolple see pre-previous geojson data. Internet work well, it's trouble saw even on WiFi network with no any network errors.
So, the question - where app takes old geojson? From  mbgl-offline.db file?  how to avoid caching it? Why it store pre-previous file when newest file loaded successfully? 

geojson link - https://api-map.vl.ru/poi/v2/points.geojson?srid=4326&precision=6&type_ids=40%2C42%2C70%2C82%2C91%2C92%2C128%2C130

**Comment by tobrun** [comment]
Before looking more into this, would you be able to verify if this is reproducible with the latest stable/beta version? `v8.2.0-beta.1` or `v8.1.0`.

cc @tmpsantos

**Comment by AlexeyIke** [comment]
Hello, yes - but some time lately. Now we check problem with additional  "no-store, no-cache" cache-control header field.

**Comment by AlexeyIke** [comment]
Hello, i've check on 8.2.1 sdk version, problem still  exists. Looks like mbgl-offline.db  keep old data for  geojson file, and after some update iterations (every 60 sec.)  engine receive 304 and load this pre-previos file from mbgl-offline.db.  After some time (and usually after put application to pause for some time - 10 min ) it load fresh geojson version file and display all right.

**Comment by AlexeyIke** [comment]
Looks like map engine don't update 'data' filed in mbgl-offline.db for geojson file every time when OK 200 response comes - we see on map fresh data, but next refresh come with 304 code and engine load  previous data from mbgl-offline.db. And we see old geojson till  it not changed on server.
