### ISSUE TITLE
Memory consumption keeps growing when Debug info is enabled

### ISSUE THREAD

**Issue by zmiao** [mapbox/mapbox-gl-native#15179]
This is probably a regression introduced by pull request https://github.com/mapbox/mapbox-gl-native/pull/14669. 

### Steps to trigger behavior

 1. Run mbgl-glfw with Instruments, using Allocation profiling template. Edit the target, adding arguments "--style=https://static.gaiagps.com/mapboxglstyles/tribal-lands.json --lat=43.6539 --lon=-100.9361 --zoom=12". Start profiling.
 2. Enable debug info by pressing 'Tab'.
 3. Zoom in the map to highest level, then zoom out to lowest. Try several rounds. 

### Expected behavior
Normally after we zoom in and zoom out, the lowest memory consumption will go back to the same level. As the following picture depicts:
![normal](https://user-images.githubusercontent.com/11026055/61537352-9fabaa80-aa3f-11e9-85e6-577e26f9ec80.jpg)

### Actual behavior
When Debug info is enabled, we find the lowest memory use keeps growing with several rounds of zooming in and zooming out.
![regression](https://user-images.githubusercontent.com/11026055/61538505-34170c80-aa42-11e9-9484-b18aae9c3c65.jpg)

**Comment by kkaefer** [comment]
This should be fixed in https://github.com/mapbox/mapbox-gl-native/pull/15395
