### ISSUE TITLE
Random sequence of all shape layers

### ISSUE THREAD

**Issue by IMHitesh** [mapbox/mapbox-gl-native#15190]
### Steps to reproduce

 1. Add `MGLLineStyleLayer`
 2. Add `MGLFillStyleLayer`
 3. Add annotations

### Expected behavior
I am expecting all layers are should be in sequence.
Layer 1 > Layer 2 > Annotations

### Actual behavior

https://user-images.githubusercontent.com/33254089/61596098-bb1fdc80-ac1c-11e9-9538-0554a344fd73.png

### Configuration

**Mapbox SDK versions: Latest version** 
**iOS/macOS versions: iOS 12.0 and MacOS : 10.14.4** 
**Device/simulator models: iPhone X**
**Xcode version: 10.2**

**Comment by 1ec5** [comment]
Did you add the style layers in `-[MGLMapViewDelegate mapView:didFinishLoadingStyle:]` or `-[MGLMapViewDelegate mapViewDidFinishLoadingMap:]`?

**Comment by IMHitesh** [comment]
Nope, I have added a layer into the map when map is starting loading.

**Comment by IMHitesh** [comment]
Also, I have followed your suggestion by adding style into `didFinishLoadingStyle` OR `mapViewDidFinishLoadingMap` but no luck.

**Comment by IMHitesh** [comment]
After 2-3 days of hard work. Below solution is worked for me.

**Comment by IMHitesh** [comment]
After 2-3 day of hard work. Below solution is worked for me.

Add all layers below of annotation layer.

**Code:**

`style.insertLayer(fillLayer, below:style.layer(withIdentifier:"com.mapbox.annotations.points")!)`
