### ISSUE TITLE
MGLAnnotation select not triggering a second time when changing zoom level

### ISSUE THREAD

**Issue by tkrami** [mapbox/mapbox-gl-native#15193]
Hello,
we are using the sdk to display annotations an show detailed information about this by clicking one specific annotation.
But we have an issue in all of our apps. After clicking a annotation, deselecting it and zooming to a lower level the **func mapView(_ mapView: MGLMapView, imageFor annotation: MGLAnnotation) -> MGLAnnotationImage?** function do not trigger the click again.

Also checked that all annotations are drawn right on the map. Also implemented the quick fix by creating an image where the lower half of the icon is transparent (otherwise the sdk will draw the annotation wrong)

### Steps to reproduce

 1. Selecting an annotation
 2. Deselcting the annotation by clicking anywhere on the map (**func mapView(_ mapView: MGLMapView, didDeselect annotation: MGLAnnotation** gets called.
3. Zoom to a lower zoom level
4. Selecting a other annotation

### Expected behavior
The **func mapView(_ mapView: MGLMapView, imageFor annotation: MGLAnnotation) -> MGLAnnotationImage?** function should be triggered on every zoom level and every time an annotation was selected. Its very annoying that some annotations are triggering this function and some annotation do nothing.

### Actual behavior
The **func mapView(_ mapView: MGLMapView, imageFor annotation: MGLAnnotation) -> MGLAnnotationImage?** function is not triggered on every zoom level and every time an annotation was selected. 

### Configuration

**Mapbox SDK versions: 5.1.1 
**iOS/macOS versions: 10.0 - 12.x
**Device/simulator models: all iPhones
**Xcode version: Version 10.2.1 (10E1001)

**Comment by friedbunny** [comment]
Hi @tkrami, thanks for the detailed report. This looks similar to a bug we introduced in 5.1.0 and fixed with https://github.com/mapbox/mapbox-gl-native/pull/15097 (for release in 5.2.0 tomorrow) — could you please give [5.2.0-beta.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v5.2.0-beta.1) a try and report back if this annotation selection issue persists? 🙇

**Comment by tkrami** [comment]
@friedbunny downgrading to version 4.11.1 works for me. When the 5.2.0 is released I will give it a try.

**Comment by tkrami** [comment]
@friedbunny Another issue was detected yesterday. 
Apple rejected the app:
Guideline 3.1.1 - Business - Payments - In-App Purchase

We noticed that your app or its metadata provides access to external mechanisms for purchases or subscriptions to be used in the app, which does not comply with the App Store Review Guidelines.

Specifically, the information button for Mapbox links to the website where digital products and services can be purchased.

Do you know this issue?

**Comment by julianrex** [comment]
> @friedbunny Another issue was detected yesterday.

Noting that this is addressed here: https://github.com/mapbox/mapbox-gl-native/issues/15406#issuecomment-522763976

@tkrami have you had a chance to test 5.2.0 for the original issue?

**Comment by tkrami** [comment]
@julianrex I do not test the newest release. I downgraded to **pod 'Mapbox-iOS-SDK', '~> 4.11.0'** and this will fix the issue for me.

**Comment by tkrami** [comment]
@julianrex I tried v5.2.0. It seems to work correctly with this version.

**Comment by friedbunny** [comment]
@tkrami great, thanks for following up. 🙇
