### ISSUE TITLE
mapView.contentInset is incorrectly set

### ISSUE THREAD

**Issue by racer1988** [mapbox/mapbox-gl-native#15198]
Probably related to #4352

### Steps to reproduce

 1. Set the map in a viewController
 2. Resize the viewController Bounds with Autolayout animated

### Expected behavior

* at the end of the autolayout animation, the content inset of the map is 0

### Actual behavior

* The content inset of the map is equal to half of the constraint changed.

### example:

The mapViewcontroller is 400 px height.
contentInset is 0

A new controller changes the map size as in #4352 and pushes the bottom constraint of the map up 200 px.

The map is now 200 px height.

The expected behaviour is that the map with the new size has also contentInset = 0

However the new map has contentInset = `(0,0,100,0)`

Resetting the constraint of the map to zero brings back the size to 400px..

however the new map has content inset inverted to the animation = `(100,0,0,0)`

### Configuration

**Mapbox SDK versions:**  5.2.0-beta.1
**iOS/macOS versions:** iOS 12

**Comment by 1ec5** [comment]
Related to #15233?

**Comment by racer1988** [comment]
up
