### ISSUE TITLE
Add shortcut to Mapbox Metrics opt-out to ℹ️

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1519]
Per #1518, we already have the technology to [detect that a user switch for Mapbox Metrics has been added](https://github.com/mapbox/mapbox-gl-native/blob/08f1d4b511ee8193735629214faeabf634617731/platform/ios/MGLMapboxEvents.m#L125-133) to the host app’s Settings bundle. When we see that, we should add an “Adjust Privacy Settings” button to the :information_source: menu that takes the user to the host app’s settings in the Settings app. According to #1075, this should do the trick:

```objc
[[UIApplication sharedApplication] openURL:[NSURL URLWithString:UIApplicationOpenSettingsURLString]];
```

**Comment by friedbunny** [comment]
Busting users out to the proper Settings sub-section is iOS 8+, FYI.
