### ISSUE TITLE
Camera Animation are interrupting each other. SetDirection should not

### ISSUE THREAD

**Issue by racer1988** [mapbox/mapbox-gl-native#15200]
Hello!

I am using a personal location manager to manage the user location and we are adding a custom annotation.

On location changes we react by calling `fly(Camera` and on course changes we would like to use `setDirection` but we are forced to use `setCamera` or `fly(camera)` 

### Expected:

calling `setDirection` while `fly` is running, updates the direction at the same time or queues the animation in the SDK and the final result is the moved and rotated camera. 

### Issue:

calling `setDirection` while `fly` is running, interrupts the `fly` animation and rotates camera the `setDirection` in the wrong coordinate.

Same happens if `fly` is called during another `fly` or `setCamera`

### Proposals:

1- Provide a completion handler also for `setDirection` as it is available for `fly` and `setCamera`. this way we could create an animation queue on our side by using completion handlers

2- Make `setDirection` not interrupting ongoing camera changes internally.

### Configuration

**Mapbox SDK versions:** 5.2.0 beta1
**iOS/macOS versions:**  iOS 12

**Comment by racer1988** [comment]
on a side note: Using only `setCamera` one after the other actually retains the animations correctly.

using multiple `fly` calls the animation flow breaks completely

**Comment by racer1988** [comment]
Another couple of discoveries:

### Missing completion handler on Cancel

Calling `fly` immediately after another `fly`, cancel the first fly but does not call its completion handler.

on Android is it possible to register for the cancel event.
If the behaviour is going to stay the same, for feature parity we maybe could add a `onCancel` callback so that we can verify on our side how to handle the animation fail.

### View Bounds changes breaks animation

If the map changes bounds while fly is running, also this cancel the fly animation

**Comment by 1ec5** [comment]
By design, any camera change operation immediately cancels any ongoing camera animation and calls its completion handler. (A change to the map view’s size would also cause a camera change operation.) #3625 tracks removing this limitation.

> Calling `fly` immediately after another `fly`, cancel the first fly but does not call its completion handler.

This is unexpected. Did the two calls to `-flyToCamera:completionHandler:` pass in the same camera perhaps?

**Comment by racer1988** [comment]
@1ec5 Umh that is a good question, we since then changed the way the camera is handled.

I will try to double check that.
It might be that the camera is the same APART from the heading.

We need to queue up fly animation due to setDirection interrupting the panning
