### ISSUE TITLE
SymbolLayer show incorrectly in different viewing distance

### ISSUE THREAD

**Issue by xtian09** [mapbox/mapbox-gl-native#15215]
Hi, after upgrading to Android-8.2.0-beta.1 my test SymbolLayer behind 3D building can be see ,but in different viewing distance , I don't think it's in right places

### Steps to reproduce

 1.mapStyle.addLayer(mLayer)
 2.upgrading to Android-8.2.0-beta.1

### Expected behavior
1.in room A

![1](https://user-images.githubusercontent.com/43405754/61840764-d57be380-aec4-11e9-8925-fe26d09aeebf.PNG)

### Actual behavior
2.same symbolayer seems like in room B
![2](https://user-images.githubusercontent.com/43405754/61840766-db71c480-aec4-11e9-9f2e-80ec8557ac6b.PNG)

### Configuration

**Android versions:** Android Q
**Device models:** Pixel 2
**Mapbox SDK versions:** Android-8.2.0-beta.1

**Comment by tmpsantos** [comment]
@xtian09 thanks for reporting the issue. Could you please provide a map style for this issue?

**Comment by xtian09** [comment]
Hi , 
thanks to your replay ,here is my style code:
mapView.getMapAsync { mapboxMap ->
            mapboxMap.setStyle(
                Style.Builder().fromUri(Style.LIGHT)
            )

**Comment by tmpsantos** [comment]
@xtian09 in this case I'm referring to a style that can reproduce the issue. :-)

**Comment by xtian09** [comment]
Hi,
i'm using Style.LIGHT and in android sdk the styleurl is "mapbox://styles/mapbox/light-v10",
or do you mean my GeoJsonSource?
Thank you
