### ISSUE TITLE
[iosapp] RenderRasterLayer::prepare assert on "Style Image Source"

### ISSUE THREAD

**Issue by astojilj** [mapbox/mapbox-gl-native#15216]
Behavior: App asserts when activating "Style Image Source" from menu.
This looks like a regression - I tried with SHA 12e0a6b0c67bc2356dbe83d7ab19efdd9a3dc2ea, (randomly chosen point in past) no assert.

### Steps to reproduce

 1. build iosapp from code and run on device.
 2. select "Style Image Source"

Note: to reproduce it, it is needed to uninstall existing iosapp before installing new.

```
#4    0x0000000105532a48 in mbgl::RenderRasterLayer::prepare(mbgl::LayerPrepareParameters const&) at /Users/astojilj/mapbox-gl-native/src/mbgl/renderer/layers/render_raster_layer.cpp:80
#5    0x0000000105591cfc in mbgl::RenderOrchestrator::createRenderTree(mbgl::UpdateParameters const&) at /Users/astojilj/mapbox-gl-native/src/mbgl/renderer/render_orchestrator.cpp:348
#6    0x00000001055d8578 in mbgl::Renderer::render(mbgl::UpdateParameters const&) at /Users/astojilj/mapbox-gl-native/src/mbgl/renderer/renderer.cpp:36
#7    0x0000000105041ba8 in MGLRenderFrontend::render() at /Users/astojilj/mapbox-gl-native/platform/darwin/src/MGLRendererFrontend.h:57
#8    0x0000000105041afc in ::-[MGLMapView renderSync]() at /Users/astojilj/mapbox-gl-native/platform/ios/src/MGLMapView.mm:905
#9    0x0000000104f733b4 in MGLMapViewImpl::render() at /Users/astojilj/mapbox-gl-native/platform/ios/src/MGLMapView+Impl.mm:14
```

**Comment by astojilj** [comment]
Edit: Note: to reproduce it, it is needed to uninstall existing iosapp before installing new.

**Comment by chloekraw** [comment]
@astojilj thanks for finding and fixing this! Have we confirmed where the regression originated?

@mapbox/maps-android have we tested if this is reproducible on android?

**Comment by pozdnyakov** [comment]
@chloekraw the hitting assertion was introduced at https://github.com/mapbox/mapbox-gl-native/pull/15074
The issue was caused by the assertion itself, so release builds are not affected.

**Comment by chloekraw** [comment]
👍 thanks @pozdnyakov
