### ISSUE TITLE
move iOS test dependencies & project to CocoaPods

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1522]
Rather than using a combo of submodule (KIF), inline static library (OCMock), and included source (OHHTTPStubs). 

Related: https://github.com/mapbox/mapbox-gl-native/issues/1452, https://github.com/mapbox/mapbox-gl-native/pull/1517

**Comment by incanus** [comment]
@jfirebaugh How are you feeling about the state of this? Probably interrelated with #1452.

**Comment by jfirebaugh** [comment]
Yeah, I would feel much better about this if #1452 landed first.

**Comment by incanus** [comment]
I think this is going to require us to integrate Travis & CocoaPods-based install. It may be doable. Another option is to check in the pre-built dependencies directly into version control, but that's going to grow our repo. 

Considering we still have the `SMCalloutView` (plus future iOS dependencies) as submodules, it might not be worth eliminating just this one (KIF) once the `npm`-related submodules are removed.

**Comment by 1ec5** [comment]
KIF will go away as part of #4794. We aren’t currently using either OCMock or OHHTTPStubs, since the telemetry tests were removed long ago (#2822).

**Comment by friedbunny** [comment]
This doesn’t seem relevant now. If we need to revisit the question of how to install test dependencies, let’s consider other options before settling on CocoaPods.
