### ISSUE TITLE
MGLShape cannot resolve feature data exceeding 325

### ISSUE THREAD

**Issue by songyuyang0918** [mapbox/mapbox-gl-native#15228]
Dear Team,

We are facing one weird issue with mapbox.I have a MultiPolygon from WFS access to data, I put it into the data generated MGLShape, I prepared through MGLShapeSource, MGLFillStyleLayer to display it, but I test the result is, when I have the features of more than 325, MGLShape convert defeat into nil, I want to know the reason.

Steps to reproduce
I used AFNetworking to make WFS network requests.
To obtain the data to the data transformation 
(NSData * data = [NSJSONSerialization dataWithJSONObject: customDic options: NSJSONWritingPrettyPrinted error: nil])
To MGLShape data object generated 
(MGLShape * shape = [MGLShape shapeWithData: data encoding: NSUTF8StringEncoding error: NULL])
I've been doing this before,
This time the data is huge, so I encountered the problem raised.

I copied the data:
[test data.txt](https://github.com/mapbox/mapbox-gl-native/files/3435104/test.data.txt)

Actual behavior
The MGLShape object is generated and the MultiPolygon is displayed.

Configuration
I tested feature over 325,mglshape nil.
I copied 331 pieces of data.

Configuration
IOS versions:10.1
Device models:Xcode Simulator iphone8
Mapbox SDK versions: mapbox_ios sdk 4.8.0

Regards,
IOS

**Comment by 1ec5** [comment]
If you pass an NSError pointer into `-[MGLShape shapeWithData:encoding:error:]`, is it set to an NSError object afterwards? What is the error’s description?

**Comment by songyuyang0918** [comment]
Geometry must be an object.
I looked at the data again and found that some geometry in the features was null,
I will judge it, thank you for your help, thank you!

**Comment by songyuyang0918** [comment]
@1ec5  Problem after problem, it is too difficult to change feature or shape.
I have some requirements, but I don't know whether this is correct or not. I hope you can have a look at it sometime.

Requirements:
Display geojson data (may include points, lines, planes, multi-point, multi-line, multi-surface)
Define a gesture to select an element
Changes the style and coordinates of selected elements.

Methods for test preparation (for example, polygon):
1. To change the style and coordinates of the selected feature by "visibleFeaturesInRect" (I can't find the methods or examples or ideas for direct change), I'm going to do:
Get the geojson dictionary of the element through the "geoJSONDictionary". Hide the element according to the "TERNARY(name = %@, 0, 1)" algorithm, generate the MGLPolygon object from the geojson data of the element, and change the style and coordinates of the MGLPolygon by deleting and adding.

2. Directly traverse geojson data, directly generate multiple MGLPolygon objects through coordinates, click on a MGLPolygon object to obtain the MGLPolygon that was clicked by "didSelectAnnotation", delete and add to change its style and coordinates (I don't know how this works with a lot of data).

Methods without an "updateAnnotation" are not very friendly!

**Comment by simonmitchell** [comment]
IMHO this shouldn't have been closed, `null` geometry is perfectly valid GeoJSON according to geojson.io and shouldn't result in the whole object failing to initialise! 😞

We have a feature in a new app where users can import layers as various file types, one of which is KML and when converting to GeoJSON using your own `togeojson` tool (This is in a React-Native app) results in `null` geometries, which therefore aren't rendering!

Is there any way your MGLShape could simply ignore null geometries, that's how I'd personally expect it to behave!
