### ISSUE TITLE
Mapview freezes when kept the map idle for sometime

### ISSUE THREAD

**Issue by Lajesh** [mapbox/mapbox-gl-native#15222]
Dear Team,

We are facing one weird issue with mapbox.  We have one fragment with just a single Mapview (Style: Mapbox Streets) and we are showing the users current location. Some times after interacting with the map or keep the application idle for sometime, the application is freezing ( Even-though we are doing all the cleanups eg: onPause(), onStop(), onDestroy()). 

### Steps to reproduce

 1. Add a Mapview in a fragment
 2. Add marker for user's current location
 3. Keep the app idle for sometime

### Expected behavior

The mapview should work fine

### Actual behavior

Application is freezing and we could see below in the logs
Mbgl-HttpRequest: [HTTP] Request with response = 304: Not Modified
Mbgl-HttpRequest: [HTTP] Request with response = 304: Not Modified
Mbgl-HttpRequest: [HTTP] Request with response = 304: Not Modified 

### Configuration

**Android versions: 6.0, 7.0, 8.0** 
**Device models: Samsung Galaxy s8, Oneplus 6t, etc** 
**Mapbox SDK versions: com.mapbox.mapboxsdk:mapbox-android-sdk:8.0.1**

Regards,
Lajesh D

**Comment by LukasPaczos** [comment]
Hey @Lajesh, thanks for reporting the issue. Could you ensure that you're calling `MapView#onDestroy` from `Fragment#onDestroyView` and not from `Fragment#onDestroy`? See [the documentation](https://docs.mapbox.com/android/api/map-sdk/8.1.0/com/mapbox/mapboxsdk/maps/MapView.html#onDestroy--).

If that's the case, would you be able to boil your issue down to a minimal reproducible case that we'd be able to test locally? Thank you!

**Comment by Lajesh** [comment]
@LukasPaczos : Thank you for the quick response. We have done the changes, please bear with us  till we finish our testing.
