### ISSUE TITLE
[Android] Tapping map or an annotation causes a move, and camera to not track user's puck

### ISSUE THREAD

**Issue by cmahopper** [mapbox/mapbox-gl-native#15221]
We use the `OnCameraTrackingChangedListener` on the `LocationComponent` to listen for whether we are currently tracking the user. If this is ever not any of `(CameraMode.TRACKING, CameraMode.TRACKING_GPS_NORTH, CameraMode.TRACKING_GPS)`, a button appears to show that the user is not being tracked by the camera.
We also use an `OnMoveListener` for the MapboxMap.

We also have views on the map added through different layers. When one of these are tapped, a small view pops up, but the camera should not stop tracking the user. Additionally, I would not expect a simple tap on the map to cause tracking to stop.

A tap on the map or an annotation causes the user to no longer be tracked. However, it is possible to tap the map slightly and not cause either of the listeners to be called. Especially on the Pixel 3, it seemed to happen more often than not that the listeners would not be called, for some reason.

### Steps to reproduce

 1. Add a camera tracking listener using `locationComponent?.addOnCameraTrackingChangedListener( ... )` and look for changes in `onCameraTrackingChanged(mode: Int)`.
 2. Add an OnMoveListener using `mapboxMap?.addOnMoveListener( ... )` and look for changes in `onMoveBegin( ... )`.
 3. Tap on the map, or on an annotation.
 4. This causes the MapboxMap's `OnMoveListener.onMoveBegin` to be called.
 5. The method `onCameraTrackingChanged` will then be called with `CameraMode.NONE`.
 6. The user is no longer tracked by the camera.

### Expected behavior

I would not expect a tap on an annotation (or on the map) to count as an "onMoveBegin", and I would expect that the user keeps being tracked.

### Actual behavior

`onMoveBegin` is called, followed by `onCameraTrackingChanged` with `CameraMode.NONE`, causing the user to no longer be tracked.

### Configuration

**Device models (Android versions):** Pixel 3 (Android 9), OnePlus 6 (Android 9), HTC 10 (Android 8), Huawei P20 (Android 9), Samsung Galaxy S9 (Android 8)
**Mapbox SDK versions:** 8.2.0

**Comment by LukasPaczos** [comment]
Hey @cmahopper, we have a special mode for this scenario, [check out `LocationComponentOptions#trackingGesturesManagement(boolean)` and the documentation](https://docs.mapbox.com/android/maps/overview/location-component/#gesture-thresholds-while-camera-tracking). With this mode enabled, you can tap the map, use double-tap to zoom, two-tap to zoom out, quick-zoom and gentle pinch zooms and rotations without breaking the tracking.

Closing as answered, but please let us know if this approach doesn't work for you.

**Comment by cmahopper** [comment]
Hey @LukasPaczos, thanks for the response and the link!

I got it to work, but it was quite difficult and I want to give you some feedback.

Initially, calling the above method with `true` had no effect, and neither did setting `trackingInitialMoveThreshold()`. In `onMoveBegin()`, I tried printing the `detector.moveThreshold` which should have been changed, but it was still `0.0`.

I spent a lot of time looking around in `LocationComponentOptions` and `LocationComponentActivationOptions` and found this check: https://github.com/mapbox/mapbox-gl-native/blob/fd33e066a4440b74328ff4b7139c297ae302c66b/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationComponentActivationOptions.java#L218-L223

Now, we weren't providing the style through the `LocationComponentActivationOptions`, but by using `LocationComponent#applyStyle(context, styleRes)` after setting the `LocationComponentOptions`, so we didn't get an exception. I figured maybe setting the style this way would override the other options, and it seems that's what happened. Setting the style "manually" in `LocationComponentOptions` along with `trackingGesturesManagement` works!

However... I think it is quite annoying that we have to set `.foregroundDrawable(...).bearingDrawable(...).gpsDrawable(...).backgroundDrawableStale(...).accuracyColor(...)` when we 1) already have a style created for this and 2) are already using that same style for the [Navigation](https://github.com/mapbox/mapbox-navigation-android/blob/444555f87d5b848574d788fe48a5e961229a52e3/libandroid-navigation-ui/src/main/res/values/attrs.xml#L61) part of our app where, to my knowledge, it is not possible to set the style as above. Thus, if we want to change the puck icons or colors, we now have to remember it to do it in two different places.

Additionally, I think I should have gotten an error message when calling `applyStyle` to let me know that this will not work as expected when using `LocationComponentOptions`.

Regardless, your solution works the way I was expected so thank you again!
