### ISSUE TITLE
[meta] Automate issue/PR labeling

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#15235]
We have a variety of labels we like to apply situationally to issues and pull requests in the repo, but we’re not always consistent in our application. A bot that looks at file paths or other situational information could apply many of our labels automatically — e.g.,

- Changes to `platform/android` could be labeled `android`.
- Changes to `platform/ios/vendor/mapbox-events-ios` could be labeled `ios` and `telemetry`.
- Text in the commit messages could be parsed for possible labels.
- An issue with `[core]` in the title could be labeled `core`.

This would reduce the manual gardening load and improve searchability of issues/PRs.

## Tools?

- [Danger](https://danger.systems/reference.html) is a popular tool that can do this (and more).
- Others? Please leave your suggestions.

/cc @mapbox/maps-ios @mapbox/maps-android @mapbox/gl-native

**Comment by riastrad** [comment]
As someone who recently spent a few cycles digging through commit history to determine where/when the Node bindings had or hadn't been modified based on core changes,  I am _very_ into this proposal.

**Comment by captainbarbosa** [comment]
And Danger also supports changelog enforcement, I believe 👀 I'm down

**Comment by friedbunny** [comment]
[GitHub Actions](https://help.github.com/en/categories/automating-your-workflow-with-github-actions) recently entered public beta and one of their demos is [a pull request labeler](https://github.com/actions/labeler). 🤔

**Comment by captainbarbosa** [comment]
nice 👌 

<img width="859" alt="Screen Shot 2020-04-13 at 10 08 21 AM" src="https://user-images.githubusercontent.com/10850812/79141484-c00a5a80-7d6e-11ea-9c51-271ef37a737d.png">
