### ISSUE TITLE
Re-investigate compress shader source approach and enable shaders debugging

### ISSUE THREAD

**Issue by astojilj** [mapbox/mapbox-gl-native#15242]
After #12477, we pack shaders source.

Having shaders compressed has positive impact on unpacked size and almost no impact on size of downloaded content on iOS:
https://github.com/mapbox/mapbox-gl-native/pull/12477#issuecomment-407855055

It makes the shaders / render tests debugging difficult as optimally, developer would just tweak shader and see it deployed and running. For debug mode, at least, it would be desired to enable running unpacked shaders.

While at it, it would be useful to re-evaluate impact on size and impact on startup time.

**Comment by astojilj** [comment]
cc @friedbunny

**Comment by astojilj** [comment]
@friedbunny ,

Are the size check values provided by CI, comparable to https://github.com/mapbox/mapbox-gl-native/pull/12477#issuecomment-407855055?

The patch removing shader compression is prepared in branch https://github.com/mapbox/mapbox-gl-native/commits/astojilj-remove-shader-compression

Size - Android x86_64 — +73.7 kB 1.601% (4.68 MB)
Size - iOS Dynamic — +311 kB 1.888% (16.8 MB)
Size - iOS arm64 — +81.9 kB 2.007% (4.16 MB)
Size - iOS armv7 — +81.9 kB 2.105% (3.97 MB)
Size - iOS x86_64 — +74.7 kB 1.720% (4.42 MB)

**Comment by friedbunny** [comment]
> Are the size check values provided by CI, comparable to https://github.com/mapbox/mapbox-gl-native/pull/12477#issuecomment-407855055?

That older comparison was for a single slice of the framework and the absolute sizes there included some application code, but the -66.34 kB difference should be comparable to, say, the size reporter’s iOS arm64 or iOS armv7 columns.

**Comment by astojilj** [comment]
Given that switch to running uncompressed shaders require recompiling a large portion of code, that we have better alternative for debugging (using metal shaders) and that size benefit is still valid, this exercise can be closed.
