### ISSUE TITLE
Android : Load Mapview inside RecylerView Item

### ISSUE THREAD

**Issue by delhmela** [mapbox/mapbox-gl-native#15250]
I added Mapbox Map inside recyler view item and every item mapview loading very very slow.I am not using your server for map style but if I change the map tile server to mapbox server there is no change to loading.How can I improve this?

**Comment by LukasPaczos** [comment]
Hey @delhmela, thanks for reporting the issue. Do you have many instances of the map visible at once? We are limiting the number of concurrent resources requests to 20 for a single app process to not flood the memory, that's what might be a bottleneck in this case.

If you're loading only one map instance or few of them, could you share an example?

**Comment by delhmela** [comment]
Yes I have a viewholder and there is expandable layout,if the user expand the layout I call mapview.getMapAsync() method and if the map is Ready I set the style from another map tile server than I marked the position and draw Polyline when the onStyleLoaded() is fired.I call this methods inside onBindViewHolder like this 

` MyViewHolder.getMapview().getMapAsync(new OnMapReadyCallback() {
                                            @SuppressLint("ClickableViewAccessibility")
                                            @Override
                                            public void onMapReady(@NonNull MapboxMap mapboxMap) {
                                                mapBoxMap = mapboxMap;
                                            
                                    
                                                mapboxMap.setStyle(new Style.Builder().fromUrl(uniqueStyleUrl), new Style.OnStyleLoaded() {
                                                    @Override
                                                    public void onStyleLoaded(@NonNull Style style) {
                                                    // this section I draw polylines and marked the position
                                                        MapsLocation mapsValues = new MapsLocation(position,
                                                                gson.fromJson(myViewHolderModelList.get(myViewHolderModelList.size() - position - 1).getLongitudes(), double[].class),
                                                                gson.fromJson(myViewHolderModelList.get(myViewHolderModelList.size() - position - 1).getLatitudes(), double[].class), mapBoxMap);
                                                        drawPollyLineAndMarkMap(mapsValues);
                                                        MyViewHolder.getMapview().onResume();

                                                    }
                                                });


                                            }
                                        });`

but map is not loaded when I expand the layout. I am waiting a few minutes map is grey and not loaded.

**Comment by tobrun** [comment]
@delhmela [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/GLSurfaceRecyclerViewActivity.kt) is a full example of a working RecylcerView implementation. Let us know if it didn't resolve your issue.
