### ISSUE TITLE
No way to reorder layers

### ISSUE THREAD

**Issue by zestyping** [mapbox/mapbox-gl-native#15263]
As far as I can see, the `Style` object provides no methods that you can use to rearrange the layers in the list.  You can only `addLayer` or `removeLayer`.  And you can't remove a layer and then insert it in a different position in the list, because `removeLayer` also destroys the layer.

This is particularly difficult because you also don't have complete control over the order in which layers are added—there exist elements such as `LocationComponent` that add layers where they want to, and once they are added they then cannot be moved.

To give a particular example, the `LocationComponent` and the `SymbolManager` add their layers in response to event listeners, so their order cannot be easily controlled; and if the wrong one ends up on top, it's impossible to swap them.

**Comment by LukasPaczos** [comment]
As explained in https://github.com/mapbox/mapbox-gl-native/issues/15262#issuecomment-519044187, you can reposition the `LocationComponent` during initialization or later in the runtime.

When it comes to repositioning layers in general, [`Style#removeLayer(Layer)`](https://docs.mapbox.com/android/api/map-sdk/8.2.1/com/mapbox/mapboxsdk/maps/Style.html#removeLayer-com.mapbox.mapboxsdk.style.layers.Layer-) allows to re-use the reference and re-add the layer back to the map when needed. If you only have access to the `Layer`'s ID, you can first get the reference using [`Style#getLayer(String)`](https://docs.mapbox.com/android/api/map-sdk/8.2.1/com/mapbox/mapboxsdk/maps/Style.html#getLayer-java.lang.String-).

**Comment by zestyping** [comment]
Oh, you're right, I didn't see that possibility!  But wow—it's pretty convoluted / non-obvious that this is how one achieves this.

**Comment by LukasPaczos** [comment]
We definitely are @zestyping! This would be a breaking change though, so we're holding off for now, until the next major release.

**Comment by zestyping** [comment]
Cool, thanks!  You could add a new method without breaking anything, or maybe just document that this is how you reorder layers?  I guess if the next major release is really soon then it's moot.
