### ISSUE TITLE
Applying tilting and padding on the location component problem .

### ISSUE THREAD

**Issue by justaaq** [mapbox/mapbox-gl-native#15269]
I am trying to create an efficient navigation view ( in landscape ) , in order to do that, I shifted the center of the current location to the bottom - right side of the screen . using the method 
LocationComponentOptions.builder(context).....padding(intArrayOf(paddingLeft, paddingTop, paddingRight, paddingBottom)).build()
This method works fine and it does shift the "current location" icon to the  desired location , but applying tilting to the camera causes changes to the icon .

kindly observe how the current location icon looks when i put it in the middle . and compare it to the other image when i applied both tilting and padding . 

### Steps to reproduce

 1.apply padding to the "locationComponent" using LocationComponentOptions.builder(context).....padding method
 2.start tracking by calling locationComponent?.cameraMode = CameraMode.TRACKING_GPS
 3.tilt the camera .
4.Observe how the current location icon looks different than when it was in the middle 

### Expected behavior
I want the "locationComponent" icon to stay the same when I apply both tilting and padding and initiate tracking.
However it is fine if it changed when you divert from the new center (that was created by applying padding) 

### Actual behavior
the "locationComponent" icon change look at the two pictures 
![Screenshot_20190731-153438](https://user-images.githubusercontent.com/3956134/62214838-834c2e00-b3ae-11e9-83db-208aab163e5d.png)

![Screenshot_20190731-153445](https://user-images.githubusercontent.com/3956134/62214855-8a733c00-b3ae-11e9-811b-9e07dd820b7a.png)

### Configuration
6.0
Samsung galaxy S6
Mapbox 7.0.0
**Android versions:** 
**Device models:** 
**Mapbox SDK versions:**

**Comment by astojilj** [comment]
This has been implemented in #14664 - [changelog entry](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/CHANGELOG.md#820-alpha1---june-26-2019) states it is available after 8.2.0
