### ISSUE TITLE
Adding an overlay covers up the location indicator

### ISSUE THREAD

**Issue by zestyping** [mapbox/mapbox-gl-native#15262]
### Steps to reproduce

 1. Create a Mapbox MapView with a nice basemap, e.g. Mapbox Streets.
 2. Turn on the LocationComponent and wait until you see an indicator for your GPS location.
 3. Add a raster layer (anything with opaque tiles) using `Style.addLayer(...)`.

### Expected behavior

The raster layer should be drawn on top of the basemap, and the location indicator should still be visible.

### Actual behavior

The location indicator disappears.

### Configuration

**Android versions:** Any
**Device models:** Any
**Mapbox SDK version:** com.mapbox.mapboxsdk:mapbox-android-sdk:7.3.0

### Screenshots

This is an example of how this affects our application.  If the map initially loads with a raster layer, it's fine; but if you remove and re-add the raster layer, the location indicator disappears.  We are using a custom location icon shaped like crosshairs, but the effect is the same regardless of the icon.

![3259](https://user-images.githubusercontent.com/3907554/62134862-86c5b380-b2e1-11e9-9e15-9e309ed30956.gif)

### Discussion

What's actually happening here is that the LocationComponent adds five of its own layers to the map, and then when I add the raster layer, it goes on top of those layers and covers up the location indicator.  So the same thing also happens with annotation layers—if I use a SymbolManager or a LineManager to draw things on the map, adding a raster layer will cover up my annotations.

I now understand why this happens.  But this _feels_ like a bug, because a developer could reasonably expect that adding layers to the map will not interfere with the location indicator.  The location indicator seems like part of the mapping tool, not like part of the content.  In the Google Maps API and the OSMDroid API, for example, the location indicator is drawn separately and is always visible.

Another reason it feels like a bug is that you can't rearrange the layers.  Once you cover up the location indicator, you're stuck.  You can't move the location layers to the top; the only way you can ever see the location indicator again is if you destroy your raster layer. 

Finally, another reason it feels like a bug is that the API does not appear to offer a way to do the right thing.  The only solution I could think of is to insert the raster layer just under the LocationComponent's layers.  But to make that solution work in general, I have to know which layers those are.  I don't have a way to ask the LocationComponent "Which layers are yours?", so I can only look for the layer IDs of these 5 particular layers.  And even if I'm willing to do something that fragile, I can't refer to the layer IDs used by the LocationComponent implementation because the constants in LocationComponentConstants are private.

So I end up doing this:

```
        // If there is a LocationComponent, it will have added some layers to the
        // style.  The SymbolManager and LineManager also add their own layers
        // where they place their symbols and lines.  We need to insert the new
        // overlay just under all these upper layers to keep it from covering up
        // the crosshairs, the point markers, and the traced lines.
        Set<String> upperLayerIds = ImmutableSet.of(
            SymbolManager.ID_GEOJSON_LAYER,
            LineManager.ID_GEOJSON_LAYER,

            // These are exactly the layer IDs defined in LocationComponentConstants,
            // but unfortunately we can't refer to them because it's package-private.
            "mapbox-location-shadow-layer",
            "mapbox-location-foreground-layer",
            "mapbox-location-background-layer",
            "mapbox-location-accuracy-layer",
            "mapbox-location-bearing-layer"
        );

        for (Layer l : map.getStyle().getLayers()) {
            if (upperLayerIds.contains(l.getId())) {
                // We've found the first (lowest) upper layer; insert just below it.
                map.getStyle().addLayerBelow(layer, l.getId());
                return;
            }
        }
        // No upper layers were found, so let's put the overlay on top.
        map.getStyle().addLayer(layer);
```

This isn't a great solution; if the IDs of these layers ever change (or if you make the constants public but then the names of the constants change), this solution will break.  If the internal implementation of the LocationComponent ever changes in future releases to build its appearance out of more or fewer layers, this solution will break.  Adding a content layer shouldn't require knowledge of the internal implementation of the LocationComponent or the SymbolManager.

What to do?

In an ideal world, adding a layer shouldn't _ever_ cover up the location indicator.

One approach would be to draw the annotations and the location indicator separately; they wouldn't be layers at all.  This is the approach taken by Google Maps.

Another possible approach is to divide the layers into a fixed, canonical set of multiple lists.  For example, you could define three layer lists: a content layer list (for map tiles), on top of that an annotation layer list (for markers, lines, tracks, and the like), and on top of that a tool layer list (for indicators, manipulators, HUD-type items, etc.).  The `addLayer()` and `removeLayer` methods, by default, would only manipulate the content layer list.  Other methods like `addToolLayer`, or overloaded methods like `addLayer(..., TOOL)`, would manipulate the other lists.

Another possibility is to allow layers to be organized into arbitrary folders.  Then, by convention, the annotation manager always puts its layers in an "annotations" folder, and the location component puts its layers in a "location" folder.  This would allow the location component to safely encapsulate its implementation details, and would have side benefits like allowing any component to encapsulate its implementation and making it easy to avoid ID collisions.

Another possibility is to assign each layer a "weight" or "z-index" value.  Then you could establish a convention that, say, all z-index values greater than 1000 are reserved for tool-like elements such as the location indicator, enabling a developer to choose a z-index and get a predictable result.

Finally, another possibility is to leave everything the way it is now, but provide an extra API that inserts a layer in an appropriate place, given some options or constraints that you specify.  At first glance this might seem like the solution requiring the least effort, but I suspect it may get tricky to express the constraints you want, and without a structure in place to maintain invariants, the semantics of the constraints might become incoherent (e.g. what does "between the annotation layer and the tool layer" mean if there are a bunch of annotation layers and tool layers mixed together?)

**Comment by zestyping** [comment]
Related discussion: https://github.com/opendatakit/collect/pull/3259

**Comment by JRWilding** [comment]
@zestyping check out `LocationComponentOptions`. When adding the location component to your style, you can specify the layer that the component should go above (or below). If the layer you want to go under the component cannot be added to the style before the location component (I don't see why it couldn't - just invisible), you can put a placeholder layer that doesn't do anything in first, add the location component above it, then add your real layer above the placeholder layer (will still be under the location component).

**Comment by LukasPaczos** [comment]
As @JRWilding mentioned, you can leverage the `above`/`below` APIs of either the `LocationComponentOptions` or `Style`.
You can reorder the location component at any point in time (or during activation) using:
```
locationComponent.applyStyle(
  LocationComponentOptions.builder(SimpleMapActivity.this)
    .layerAbove("raster_layer")
    .build()
);
```
or you can place the layer below the component, if the component is already present:
```
RasterLayer rasterLayer = new RasterLayer("raster_layer", "raster_source");
style.addLayerBelow(rasterLayer, LocationComponentConstants.FOREGROUND_LAYER);
```
[`LocationComponentConstants`](https://docs.mapbox.com/android/api/map-sdk/8.2.1/com/mapbox/mapboxsdk/location/LocationComponentConstants.html) contains constants for all layers that the component is built out of so that you can reference them when positioning other layers.

`LocationComponentOptions#layerBelow` is available in the `7.3.0` and below.
The layer name constants have been exposed in the `7.4.0`.
`LocationComponentOptions#layerAbove` and some fixes wrt to location puck's z-index positioning landed in `8.0.0`.

I hope this helps! Closing as answered, but please let us know if those tools were not enough to serve your use-case.

**Comment by zestyping** [comment]
Hi, and thank you for the thorough reply!

Yes, the ability to reorder the location component that was introduced in 8.0 will certainly help!  I don't quite think the issue is entirely addressed, though.  I have a few comments in response:

> [`LocationComponentConstants`](https://docs.mapbox.com/android/api/map-sdk/8.2.1/com/mapbox/mapboxsdk/location/LocationComponentConstants.html) contains constants for all layers that the component is built out of so that you can reference them when positioning other layers.

Yes, I noted that—unfortunately they were private, so I couldn't use them.  It looks like they just became available 6 days ago, after I filed this issue.  Thanks!

Having the five separate constants is nice, but it means you still have to write code that depends on the number of layers and depends on the names of the constants, which makes it just as intimately coupled and nearly as fragile as it was without them.  It would be better to be able to ask the `LocationComponent` for all its layers without having to know what they are or what they are called, e.g. `List<String> LocationComponent.getLayerIds()` or similar.

The individual layer IDs are really an implementation detail of the `LocationComponent`; there is no contract that it always has exactly those IDs, that number of IDs, or that they will be in any particular order.  The only way you can find out the order is by reading the source code of `LocationComponentController`.  So the only way to be sure your code will work is to check all the layers, as in the code I posted earlier:

        Set<String> upperLayerIds = ImmutableSet.of(
            LocationComponentConstants.SHADOW_LAYER,  // okay, we have constants now
            LocationComponentConstants.FOREGROUND_LAYER,
            LocationComponentConstants.BACKGROUND_LAYER,
            LocationComponentConstants.ACCURACY_LAYER,
            LocationComponentConstants.BEARING_LAYER
        );

        for (Layer l : map.getStyle().getLayers()) {
            if (upperLayerIds.contains(l.getId())) {
                // We've found the first (lowest) upper layer; insert just below it.
                map.getStyle().addLayerBelow(layer, l.getId());
                return;
            }
        }
        // No upper layers were found, so let's put the overlay on top.
        map.getStyle().addLayer(layer);

I don't think I see a way to insert a layer below the `LocationComponent` (even with the new features you described) that's simpler than the above, yes?  Even if one decides to use `layerAbove` to raise the `LocationComponent` after adding your new layer, or inserting a placeholder layer as @JRWilding cleverly suggested, that still means every part of the program that adds layers has to get coupled to the `LocationComponent`.

Given that keeping the location indicator on top is by far the most common thing to want (indeed, it would be entirely acceptable if the location indicator were _always_ on top), it would certainly be nice if this were the default behaviour, or at least easier to do; it shouldn't require jumping through hoops to create the user experience that is going to be correct 99% of the time.  One easy way to fix this is to make `addLayer` responsible for checking for the `LocationComponent` layers and determining where to insert the new layer, or provide a new method `addLayer(Layer layer, boolean belowLocationComponent)` for this purpose.

Thanks for reading and considering my opinion, and and thanks for all your help with this API!

**Comment by zestyping** [comment]
Hi @LukasPaczos, as you explained above, after the layer name constants were exposed in LocationComponentConstants, I can use them with `addLayerBelow` to insert the new layer at the desired level in the layer stack.  In our app, we need to insert the raster layer below the location layer, the symbol layer, and the line layer, hence we would do something like:

        Set<String> upperLayerIds = ImmutableSet.of(
            SymbolManager.ID_GEOJSON_LAYER,
            LineManager.ID_GEOJSON_LAYER,
            
            LocationComponentConstants.SHADOW_LAYER,
            LocationComponentConstants.FOREGROUND_LAYER,
            LocationComponentConstants.BACKGROUND_LAYER,
            LocationComponentConstants.ACCURACY_LAYER,
            LocationComponentConstants.BEARING_LAYER
        );

and then proceed as in the preceding comment.

Unfortunately, this doesn't work—the location layer constants are now available, but now the `SymbolManager` and `LineManager` constants have been removed.  I tried looking for a way to get the layer ID or the `Layer` object from the `SymbolManager` or `LineManager`, but there doesn't seem to be one.  If there is no way to get the layer or the layer ID, then I can't place another below or above it, nor can I move the layer to the top—I can't find any way to reference the symbol or line layers any more.

What is the recommended way to move a symbol layer to the top of the stack?

**Comment by LukasPaczos** [comment]
@zestyping this is tentatively tracked in https://github.com/mapbox/mapbox-plugins-android/issues/1027, the mentioned option `c)` is what I believe you're looking for.

I don't know what's the logic that makes use of the above set you've pasted, but you could instead leverage the annotation manager's constructor that takes `layerBelow` as an argument.

**Comment by zestyping** [comment]
Thanks @LukasPaczos !  Yes, that comment describes exactly the need: to access the symbol layer (and similarly the line layer).

The reason that the annotation manager constructor's `layerBelow` argument isn't sufficient is that I need to add and remove layers at various times (the user gets to select layers to load from files) after the annotation layers already exist.

**Comment by LukasPaczos** [comment]
This is moving in https://github.com/mapbox/mapbox-plugins-android/pull/1071 @zestyping.
