### ISSUE TITLE
Ambient cache breaks map updates

### ISSUE THREAD

**Issue by matthiaskmt** [mapbox/mapbox-gl-native#15267]
Hey,

I experienced a behaviour which seem a bit weird to me. The tile data get's stored in the ambient cache while panning around the map. That's great, but the next time the app is launching I would expect to see the data from the cache but also that a network request is happening to validate the data and maybe update. I could never see such a network request while profiling with mitm or Charles. Is that the intended behaviour ?

**Platform:** iOS and Android
**Mapbox SDK version:** iOS version 5.2.0, Android 8.2.0

**Comment by tobrun** [comment]
@matthiaskmt we use a couple/combination of caching techniques. First we have an expires check that validates if the resource locally is still valid. If it expired, we will do a server request using an etag. The server will either response with not modified -> use local resource and reset expires check. Or it we will pull in the resource and reset all caching related data.

In your case, the local expires check will probably validated to false as the resource hadn't expired yet.

Let us know if you have any more questions!

**Comment by matthiaskmt** [comment]
Thanks @tobrun

So I get it that way. I have to call `invalidateAmbientCacheWithCompletionHandler:` if want to recheck the data from the server. The documentation is mentioning a re-download. Is this re-download happening immediately or when the app is showing the tile again ?

https://docs.mapbox.com/ios/api/maps/5.2.0/Classes/MGLOfflineStorage.html#/c:objc(cs)MGLOfflineStorage(im)invalidateAmbientCacheWithCompletionHandler:

Cheers,
Matthias

**Comment by tobrun** [comment]
invalidateAmbientCache will indeed mark resources as expired, this download will only happen when the engine requires a new tile to be requested for example a gesture interaction (zooming in and out).

**Comment by matthiaskmt** [comment]
Thanks for clarifying this

**Comment by alextorn** [comment]
> invalidateAmbientCache will indeed mark resources as expired, this download will only happen when the engine requires a new tile to be requested for example a gesture interaction (zooming in and out).

@tobrun how to request new tiles without gesture interaction on the map?
