### ISSUE TITLE
[android] Test app MapStrictModeException crash

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-gl-native#15283]
This ticket is related to a test app QA crash that happened a couple of times during `8.2.0` QA.

A crash would happen in [`SupportMapFragmentActivity`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/SupportMapFragmentActivity.java) when I exited the example before the camera movement finished. It also happened in [`HillshadeLayerActivity`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/HillshadeLayerActivity.java) when I exited the example before the raster hillshade layer could finish loading.

https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java#L122

```
com.mapbox.mapboxsdk.MapStrictModeException: Map detected an error that would fail silently otherwise: You're calling `setGestureInProgress` after the `MapView` was destroyed, were you invoking it after `onDestroy()`?
```

![Screen Shot 2019-07-30 at 2 20 40 PM](https://user-images.githubusercontent.com/4394910/62166400-84f5f300-b2d5-11e9-92c0-05761a59b3c3.png)

I'm unable to reproduce the 💥 , so perhaps this ticket isn't actionable.

**Comment by LukasPaczos** [comment]
This is called on a lot of examples in debug mode. I believe I was able to reproduce that by opening activity and closing it really quickly with the system back button which for some reason pushes a motion event to the view hierarchy, while it shouldn't. This is happening only on a pixel 2xl for me though.
