### ISSUE TITLE
[android] Jumping marker in test app's DraggableMarkerActivity.kt on 8.2.0

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-gl-native#15284]
The Android test app's `DraggableMarkerActivity.kt` has odd behavior when a single marker is long-pressed to start dragging. The marker should remain directly where it is when dragging becomes enabled, rather than jumping to a different location.

![ezgif com-resize (11)](https://user-images.githubusercontent.com/4394910/62167320-cedfd880-b2d7-11e9-84f6-64ec9a2126c1.gif)

This was discovered during manual QA of this repo's Android test app on stable `8.2.0` of the Map SDK for Android.

**Comment by LukasPaczos** [comment]
This was already fixed in https://github.com/mapbox/mapbox-gl-native/pull/15181 on `master` 🎉
