### ISSUE TITLE
Running in emulator weirdly renders custom layers

### ISSUE THREAD

**Issue by hrach** [mapbox/mapbox-gl-native#15312]
Hi, running our app in emulator weirdly renders our markers.

1) Photos are gray-scaled (inverted)
2) Some icons are not rendered (or maybe rendered in different z-index?)
3) Rendering circle layer in different z-index (over photo)

This happened also earlier, but in 7.X SDK we were able to "fix" it by going to tasks and return to the app. It re-rendered the content correctly then. In 8.2 SDK it doesn't help.

Though, sometimes during zooming we can see colored photos.

This wrong rendering happens mainly to our own custom layer, but sometimes we see also wrong rendering of map(style) itself.

Any idea how to fix/workaround this? 

### Steps to reproduce

 1. Run app in emulator

### Expected behavior

Correct rendering.

<details><summary>Expected screenshot from real device</summary>

![mapbox_ok](https://user-images.githubusercontent.com/284263/62461805-122dc180-b786-11e9-97a5-773c49f13061.png)

</details>

### Actual behavior

![mapbox_emulator](https://user-images.githubusercontent.com/284263/62461790-0215e200-b786-11e9-97e5-a67f7ba9497e.png)

### Configuration

**Android versions:** Android 8.1 and 9 tested
**Device models:**  Emulator, on multiple machines (Win and Mac)
**Mapbox SDK versions:** 8.2.1

**Comment by LukasPaczos** [comment]
Hey, thanks for reaching out @hrach. This looks like a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/10829, could you test the settings mentioned in https://github.com/mapbox/mapbox-gl-native/issues/10829#issuecomment-441021598?

**Comment by hrach** [comment]
Ah yes, that make it work. Though I had to find how to change these, I'm doing it right now by cli `./emulator -avd NEXUS_7_API_28 -gpu swiftshader_indirect`

**Comment by hrach** [comment]
Thank you for pointing out the workaround.
