### ISSUE TITLE
No z-index for LocationComponent 

### ISSUE THREAD

**Issue by shanih** [mapbox/mapbox-gl-native#15311]
Hi.
Can't find a way to put the location marker above other symbols on the map...

thanks!

**Comment by LukasPaczos** [comment]
Hey, please take a look at [`LocationComponentOptions#layerAbove`](https://docs.mapbox.com/android/api/map-sdk/8.2.1/com/mapbox/mapboxsdk/location/LocationComponentOptions.html#layerAbove--) and [`LocationComponentOptions#layerBelow`](https://docs.mapbox.com/android/api/map-sdk/8.2.1/com/mapbox/mapboxsdk/location/LocationComponentOptions.html#layerBelow--).
