### ISSUE TITLE
Set maxzoom to 20 by default

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-native#1531]
for parity with gl-js

[snippet](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/map/transform.hpp#L86-87)

**Comment by 1ec5** [comment]
Does gl-js have a library-level maximum zoom level, or does it only care what the tile source says the maximum is?

**Comment by peterqliu** [comment]
[Has default max of 20, but configurable](https://www.mapbox.com/mapbox-gl-js/api/)

**Comment by 1ec5** [comment]
That seems like a reasonable way to do it. Anyone know why it isn’t configurable in the first place?

**Comment by kkaefer** [comment]
It was never implemented. No reason not to implement it though.

**Comment by mb12** [comment]
Currently Collison::max placement depth is hard coded to 3 i.e. for a source with Max zoom 15, Symbols are placed until zoom 18. This limitation will go away once @ansis changes for label placement are merged into master.

**Comment by jfirebaugh** [comment]
Duplicate of #509.
