### ISSUE TITLE
[android] android-gnustl-arm-v7 can timeout and fail waiting for Firebase

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#15325]
The `android-gnustl-arm-v7` job c[an hit the 20 minute CircleCI timeout and fail](https://circleci.com/gh/mapbox/mapbox-gl-native/311274), even though [the Firebase device test may ultimately succeed](https://console.firebase.google.com/u/0/project/android-gl-native/testlab/histories/bh.1470d2ab45df6f1f/matrices/8232742097943354519) in “12 minutes, 15 seconds”.

/cc @mapbox/maps-android

**Comment by tobrun** [comment]
this an issue with the `gcloud firebase test android run` command and out of our control to fix.
