### ISSUE TITLE
[android] Glitches while drawing custom tiles

### ISSUE THREAD

**Issue by alexiri** [mapbox/mapbox-gl-native#15329]
We're seeing a couple of different glitches while loading tiles in our React Native app and I wanted to know if these are known issues that have been fixed. The [react native bindings](https://github.com/nitaliano/react-native-mapbox-gl) we're using are a bit old, they're using version 5.5.3 of the Android SDK. We've only seen these issues on Android so far (but that's where we do most of our testing), and we haven't been able to reproduce them reliably. 

The first issue is lines being drawn incorrectly (two parallel green lines in the middle of the image). I've [reported this before](https://github.com/nitaliano/react-native-mapbox-gl/issues/1643) but I got no responses.

![Screenshot_2019-08-05-08-43-38-277_ch cern opendays2019](https://user-images.githubusercontent.com/5055697/62614889-90b46b80-b90c-11e9-9443-74c64daed558.png)

The second issue is some tiles not loading at all. The small green lines are a sprite and the icons are a SymbolLayer, but the numbers are part of the tiles, I'm not sure why those are rendered but the rest of the tile isn't.

![Screenshot_2019-08-05-08-43-33-988_ch cern opendays2019](https://user-images.githubusercontent.com/5055697/62615142-06b8d280-b90d-11e9-82ef-4258572434bc.png)

In both cases, the tiles are perfectly fine. Usually killing the app and restarting it "solves" the problem, the map will then load without any glitches. We're not sure what conditions result in these glitches, but we have yet to see both of them at once.

Are any of these issues known and solved? If so, when were they solved? Upgrading to the newer version of the [react native bindings](https://github.com/react-native-mapbox-gl/maps) is not trivial, it is still in beta phase and there are a lot of API changes, so we'd like to understand first if it will solve these issues before making the effort and taking the extra risk.

**Comment by zugaldia** [comment]
Hey @alexiri - thanks for the report. I think that the best next step is trying to reproduce these rendering glitches using our native Android SDK to figure out if this an SDK issue or an integration with RN problem. A few things that would be useful:
- Would you be able to share (here or email) a minimal project or a style URL showing the issue?
- When you see those rendering issues, do you see any device logs that you could share?
- Finally, does this happen with any Android device, or only in particular brand/model devices?
