### ISSUE TITLE
How to add round corners to the ends of Polylines?

### ISSUE THREAD

**Issue by makinggainz** [mapbox/mapbox-gl-native#15350]
I would like my polylines to not have sharp edges but rather round edges at all intersection points. Possibly like this: https://github.com/mapbox/mapbox-gl-native/issues/1771

### Expected behavior

Round edges

### Configuration

**Mapbox SDK versions:** newest 
**iOS/macOS versions:** 
**Device/simulator models:**
**Xcode version:**  newest ^^^

**Comment by LukasPaczos** [comment]
Hey @makinggainz, you'll need to use the [`MGLLineStyleLayer`](https://docs.mapbox.com/ios/maps/examples/runtime-add-line/). The properties you're looking for are `lineJoin` and `lineCap`.

**Comment by makinggainz** [comment]
@LukasPaczos do I have to switch to use that? no way to do it with usual mglpolyline?

**Comment by LukasPaczos** [comment]
That's correct @makinggainz. `MGLPolyline` is a simplified API, for a whole range of features you'll need to switch to `Source`s and `Layer`s APIs.
