### ISSUE TITLE
[iOS] Bars in scalebar have different sizes

### ISSUE THREAD

**Issue by jmkiley** [mapbox/mapbox-gl-native#15356]
The bars in the scale bar can be different sizes. This seems to occur after the scale bar has gone from having three sections to two. The bars should remain the same size.

![scale-bar](https://user-images.githubusercontent.com/12474734/62886858-da2bfe80-bcf0-11e9-87e8-4e899d477476.jpg)

Initially reported in https://github.com/mapbox/mapbox-gl-native/issues/15197#issuecomment-514533957

/cc @frederoni

**Comment by friedbunny** [comment]
In some cases, the right-most bar can also be pushed beyond the outside border and clip:

![File](https://user-images.githubusercontent.com/1198851/62970966-80493880-bdc5-11e9-839a-7e016ec07b60.jpg)

**Comment by julianrex** [comment]
Looks like the frame of the `containerView` is being miscalculated.

![Screen Recording 2019-09-18 at 11 42 PM](https://user-images.githubusercontent.com/3765757/65211842-15e38200-da6e-11e9-9f02-19f0eb986871.gif)
