### ISSUE TITLE
[android] Unable to resolve host

### ISSUE THREAD

**Issue by LucileBillard** [mapbox/mapbox-gl-native#15375]
Sometimes, mapviews do not load properly.

### Steps to reproduce

 1. Include a MapView in a layout.
 2. Launch the activity containing this layout.

### Expected behavior

The map should load when starting the activity.

### Actual behavior

The map does not load and we get the following log: 

>loading style failed: Unable to resolve host "api.mapbox.com": No address associated with hostnam

### Configuration

**Android versions: 9** 
**Device models: Huawei P20 Lite** 
**Mapbox SDK versions: android-v8.1.0**

**Comment by tmpsantos** [comment]
@LucileBillard can you give some more info on your network setup? Is it firewalled? VPN? What is the ISP? Is this issue easy to reproduce in your environment?

**Comment by LucileBillard** [comment]
@tmpsantos  I was using my 4G data. It's not easy to reproduce: It happened only twice.
