### ISSUE TITLE
Building for iOS framework does not generate the podspec file

### ISSUE THREAD

**Issue by long1eu** [mapbox/mapbox-gl-native#15377]
Building the iOS framework does not generate the podspec file. 
`'{...}/build/ios/pkg/{dynamic|static}/Mapbox-iOS-SDK.podspec'`

The command I used is `make iframework BUILDTYPE=Debug`

**Comment by friedbunny** [comment]
We removed the generated local podspec in #15027 as part of improving validation and streamlining the build process. Can you say more about how you used this file?

**Comment by long1eu** [comment]
I agree with your decision, but the (readme)[https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/INSTALL.md#using-your-own-build-with-cocoapods] is not updated.

**Comment by friedbunny** [comment]
Ah, thanks for pointing that out — we’ll update the docs soon.

To use a local build via CocoaPods, one way would be to edit `platform/ios/Mapbox-iOS-SDK.podspec` and change this:

https://github.com/mapbox/mapbox-gl-native/blob/8e1bd18eae73ffbe14aa9297a039e2431d40bd36/platform/ios/Mapbox-iOS-SDK.podspec#L17-L20

... to:

```ruby
  m.source = {
    :path => "{...}/build/ios/pkg/dynamic/",
    :flatten => true
  }
```

And then point your Podfile to that podspec.

Another way would be to overwrite the CocoaPods-downloaded version with the custom-built `Mapbox.framework` and `.dsym`.

**Comment by long1eu** [comment]
Thanks!
One think that I found is that I don't have any .dsym files when I run `make iframework BUILDTYPE=Debug SYMBOLS=true`

**Comment by friedbunny** [comment]
> One think that I found is that I don't have any .dsym files [for debug builds]

That’s expected, as the binaries in debug builds should keep all of their symbols (and other unoptimized ephemera) that would otherwise be stripped out into a dSYM for a size- and/or performance-optimized release build.

**Comment by long1eu** [comment]
I think we can close this
