### ISSUE TITLE
Static analyzer error in GeometryCollection::fixupPolygons and wagyu

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#15382]
As of cd129612c1d5472a7054ba4a3dd3a99ef29fe182, Xcode 10.3’s static analyzer finds the following error — @astojilj it looks like #15309 may fix this?

> [mapbox-gl-native/src/mbgl/tile/geometry_tile_data.cpp:45:9](https://github.com/mapbox/mapbox-gl-native/blob/cb186aa33dee3d490470911c10599825d4d98271/src/mbgl/tile/geometry_tile_data.cpp#L45): Access to field 'maximum_bound' results in a dereference of a null pointer (loaded from variable 'last_maximum') (within a call to 'add_ring’)
>
> 1. mapbox-gl-native/src/mbgl/tile/geometry_tile_data.cpp:44:27: Entering loop body
> 1. mapbox-gl-native/src/mbgl/tile/geometry_tile_data.cpp:45:9: Calling 'wagyu::add_ring'
> 1. mapbox-gl-native/vendor/wagyu/include/mapbox/geometry/wagyu/wagyu.hpp:47:5: Entered call from 'fixupPolygons'
> 1. mapbox-gl-native/vendor/wagyu/include/mapbox/geometry/wagyu/wagyu.hpp:49:16: Calling 'add_linear_ring<int, int>'
> 1. mapbox-gl-native/vendor/wagyu/include/mapbox/geometry/wagyu/build_local_minima_list.hpp:13:1: Entered call from 'wagyu::add_ring'
> 1. mapbox-gl-native/vendor/wagyu/include/mapbox/geometry/wagyu/build_local_minima_list.hpp:18:63: Assuming the condition is false
> 1. mapbox-gl-native/vendor/wagyu/include/mapbox/geometry/wagyu/build_local_minima_list.hpp:21:5: Calling 'add_ring_to_local_minima_list<int>'
> 1. mapbox-gl-native/vendor/wagyu/include/mapbox/geometry/wagyu/local_minimum_util.hpp:204:1: Entered call from 'add_linear_ring<int, int>'
> 1. mapbox-gl-native/vendor/wagyu/include/mapbox/geometry/wagyu/local_minimum_util.hpp:208:9: Assuming the condition is false
> 1. mapbox-gl-native/vendor/wagyu/include/mapbox/geometry/wagyu/local_minimum_util.hpp:216:5: 'last_maximum' initialized to a null pointer value
> 1. mapbox-gl-native/vendor/wagyu/include/mapbox/geometry/wagyu/local_minimum_util.hpp:217:12: Assuming the condition is false
> 1. mapbox-gl-native/vendor/wagyu/include/mapbox/geometry/wagyu/local_minimum_util.hpp:217:12: Loop body executed 0 times
> 1. mapbox-gl-native/vendor/wagyu/include/mapbox/geometry/wagyu/local_minimum_util.hpp:296:33: Access to field 'maximum_bound' results in a dereference of a null pointer (loaded from variable 'last_maximum’)

/cc @alexshalamov @pozdnyakov

**Comment by astojilj** [comment]
> As of [cd12961](https://github.com/mapbox/mapbox-gl-native/commit/cd129612c1d5472a7054ba4a3dd3a99ef29fe182), Xcode 10.3’s static analyzer finds the following error — @astojilj it looks like #15309 may fix this?

No, we will still have wagyu used after #15309. 
/cc @flippmoke
