### ISSUE TITLE
IB Designables Timed Out/Interface Builder Cocoa Touch Tool crashed

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#1538]
I'm getting this non-fatal error when building Treble, [which uses storyboards](https://github.com/friedbunny/treble/blob/619aa80178f98a94de6ff621467137c8b69c75dd/treble/Base.lproj/Main.storyboard):

> `treble/treble/Base.lproj/Main.storyboard`: error: IB Designables: Failed to render instance of `MGLMapView`: Rendering the view took longer than 200 ms. Your drawing code may suffer from slow performance.

Also this:

> `treble/treble/Base.lproj/Main.storyboard`: error: IB Designables: Failed to update auto layout status: Interface Builder Cocoa Touch Tool crashed

The build continues and works as expected on device, but Interface Builder doesn't allow any customization of the `MGLMapView` properties and the preview doesn't display (because it has timed-out/crashed).

This is on the latest `master`, ~`v0.2.24`.

![screen shot 2015-05-13 at 12 35 30 am](https://cloud.githubusercontent.com/assets/1198851/7605832/55dede0a-f908-11e4-8632-789b49f78034.png)

/cc @1ec5

**Comment by friedbunny** [comment]
Oh, I should mention that I'm running Xcode 6.3.1 on OS X 10.10.4b3.

**Comment by 1ec5** [comment]
Looks like fallout from 190e91120927ea2e48a72c8337ba923dabe31f85 for #1491:

```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSProcessInfo pushEvent:withAttributes:]: unrecognized selector sent to instance 0x7f90b351bda0'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x000000010cf50c65 __exceptionPreprocess + 165
1   libobjc.A.dylib                     0x000000010bccebb7 objc_exception_throw + 45
2   CoreFoundation                      0x000000010cf580ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
3   CoreFoundation                      0x000000010ceae13c ___forwarding___ + 988
4   CoreFoundation                      0x000000010ceadcd8 _CF_forwarding_prep_0 + 120
5   MapboxGL                            0x00000001177c6a75 __44+[MGLMapboxEvents pushEvent:withAttributes:]_block_invoke + 69
6   libdispatch.dylib                   0x000000011050ef16 _dispatch_call_block_and_release + 12
7   libdispatch.dylib                   0x0000000110529964 _dispatch_client_callout + 8
8   libdispatch.dylib                   0x0000000110515dc7 _dispatch_root_queue_drain + 856
9   libdispatch.dylib                   0x0000000110516d59 _dispatch_worker_thread3 + 98
10  libsystem_pthread.dylib             0x00000001108aa637 _pthread_wqthread + 729
11  libsystem_pthread.dylib             0x00000001108a840d start_wqthread + 13
```

**Comment by 1ec5** [comment]
By the way, IB does report it as a crash, at least in Xcode 6.4, rather than a timeout. (But timeouts are usually due to designables agent crashes anyways.)

**Comment by friedbunny** [comment]
@1ec5 How does one get at the IB designables stack traces and so on?

**Comment by 1ec5** [comment]
Normally you can click Debug in the Custom Class section of the Identity inspector (or go to Editor ‣ Debug Selected Views). The debugger will stop on the code that crashes. But that actually hangs Xcode in this case, probably because your workspace only contains the headers, not the implementation files.

So the fallback is to open CrashReporterPrefs (part of the Auxiliary Tools for Xcode download) and switch to Developer mode. Crash Reporter now appears whenever any process crashes, even background processes. That can quickly get annoying, so I also turn on the “Use Notification Center” preference.
