### ISSUE TITLE
iOS 13: Location Update in Background

### ISSUE THREAD

**Issue by t-unit** [mapbox/mapbox-gl-native#15393]
### Steps to reproduce

 1. Integrate Mapbox into an iOS application
 2. Let the user grant `CLLocationManager.requestAlwaysAuthorization`

### Expected behavior

* Mapbox does not use the users location while the app is in background. 
* The system won't inform the user about background usage of his/her location.

### Actual behavior

Mapbox uses the users location even when in background. iOS 13 keeps track of this and informs the user about the usage, see:

![BackgroundUsage](https://user-images.githubusercontent.com/366172/63158483-9f400880-c019-11e9-91b7-4c9864ae00f4.png)

(map/background blurred for privacy reasons)

### Configuration

**Mapbox SDK versions:** 5.2.0
**iOS/macOS versions:** iOS 13 beta 6
**Device/simulator models:** iPhone 6
**Xcode version:** Xcode 11 beta 5

### Demo

I created a sample application exposing this behaviour:
https://github.com/t-unit/MapboxBackgroundTest

**Comment by julianrex** [comment]
Thanks for the report @t-unit - we're tracking changes in iOS 13 over in `mapbox-events-ios`, for example see https://github.com/mapbox/mapbox-events-ios/issues/136.

/cc @alfwatt

**Comment by julianrex** [comment]
@t-unit does your app require "Always" permission? If not you should consider "When in use" permission:

`MGLMapView` looks for the existence of `NSLocationWhenInUseUsageDescription`, `NSLocationAlwaysAndWhenInUseUsageDescription` and `NSLocationAlwaysUsageDescription` in the application's `Info.plist` to determine what level of permission to request - and this only done if you're showing the user's location on the map (`showsUserLocation`).

**Comment by t-unit** [comment]
@julianrex thanks for the suggestion, but our app requires "Always" for some map-unrelated features. So this is not an options for us.

**Comment by alfwatt** [comment]
@t-unit currently, if your app requests `CLLocationManager.requestAlwaysAuthorization ` we will add a geofence to trigger background location collection, you can see the code in our [telemetry library](https://github.com/mapbox/mapbox-events-ios/blob/c03b1aac75889e1e0a27c146e5ff2b0561548219/MapboxMobileEvents/MMELocationManager.m#L119)

We're investigating to see if this feature of our library is increasing the number of dots which show up on that map.

Can you explain al little further about how your app uses background location?

**Comment by t-unit** [comment]
@alfwatt The app we develop only collect location data only when connected to an external device. So users don't expect any geofencing etc. when carrying their phone around without the external device.

**Comment by js** [comment]
There is a wide number of use cases where "always" doesn't necessarily mean "constantly use the location in the background". A lot of use cases is really tied to some interaction in the app, such as starting a workout or other interactions like the above. Yet these apps need to request always authorization for background location updates to work at a later date.

With iOS 13 the Mapbox SDK will make any app that uses background location _selectively_ (such as through a specific interaction) look extremely bad, and will most likely result in users revoking the always authorization.

The fact that we have seen no intention from Mapbox over the course of the past eight betas to resolve this really worries me and puts our and many other apps in a situation where we ultimately betray the users trust. Not a good look.

**Comment by alfwatt** [comment]
@t-unit Thanks for opening this ticket. We've been tracking the iOS 13 changes closely and have been working on an update to our telemetry collection practices. We'll provide an update as soon as possible, as we understand your concern and agree it's an important issue.

We're using your example source as the basis for our testing, thank you for sharing it!

**Comment by georgbachmann** [comment]
Is there anything we as developers need to enable/disable manually? Cause I am seeing the same behavior. Is there a way to tell mapbox not to collect location-data when the app is in background?
