### ISSUE TITLE
[core] Locally generated glyphs shift on over-zoomed tiles

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-native#15405]
GL-Native version of https://github.com/mapbox/mapbox-gl-js/issues/8653

@asheemmamoowala @mapbox/gl-native @tmpsantos 

---

When zooming from z17 to z18, some locally generated glyphs are being replaced by server retrieved glyphs.

On z18 tiles, the glyphs have variable size which is a property of the server generated glyphs. The z17 tiles have fixed size (24/32 px sq.) size that is characteristic of locally generated glyphs.

**platform**: iOS and Android
**version**: 5.2 / 8.2

### Demonstration

GIF created from an iOS screen recording:

![ezgif-4-be3044fbe602](https://user-images.githubusercontent.com/34117059/63230119-6b9de380-c1bd-11e9-9e4c-6604249e4cb4.gif)

Also see https://github.com/mapbox/mapbox-gl-js/issues/8653 for helpful visuals on GL-JS.

### Expected Behavior
Locally generated glyphs are not overridden by server generated ones.

### Actual Behavior
At z18 server glyphs are taking over. Causing a change in the baseline and font of some characters.

**Comment by chloekraw** [comment]
@asheemmamoowala I noticed your native pr https://github.com/mapbox/mapbox-gl-native/pull/15407 is slimmer than your js pr https://github.com/mapbox/mapbox-gl-js/pull/8657. Is that because some changes on js are not needed in native, or because https://github.com/mapbox/mapbox-gl-native/pull/15407 is what we can get into `queso` and other changes could be done as follow-on work for `ristretto`?

**Comment by asheemmamoowala** [comment]
@chloekraw I found two additional issues while debugging the root cause of this bug on GL-JS and decide to address them as well. On Native, the local glyphs are already being cached correctly. I haven't yet had a chance to verify the other issue - correct options override in `Map#setStyle`, but I'll look into it as part of completing the tests for this PR.
