### ISSUE TITLE
AppStore check rejection 3.1.1 Business: Payments - In-App Purchase

### ISSUE THREAD

**Issue by tkrami** [mapbox/mapbox-gl-native#15406]
Hey,
Apple rejected our app because of "AppStore check rejection 3.1.1 Business: Payments - In-App Purchase"

The more detailed message is:

Hello,

Thank you for your response.

Regarding 3.1.1, we still noticed that your app or its metadata provides access to external mechanisms for purchases or subscriptions to be used in the app, which does not comply with the App Store Review Guidelines.

To resolve this issue, it would be appropriate to remove the account registration links and any other fully qualified links to your site that could indirectly provide access to these mechanisms, such as links to web pages for support, FAQs, product or program details, etc.

We appreciate your continued efforts to be in compliance with the App Store Review Guidelines, and are looking forward to reviewing your revised submission.

Best regards,

App Store Review

Apple added following screenshots to the report:

![attachment-5291693063216002703IMG_2817](https://user-images.githubusercontent.com/39692872/63240933-211a7680-c252-11e9-858d-13d33bfc9203.PNG)
![attachment-2213169020441555721IMG_2819](https://user-images.githubusercontent.com/39692872/63240934-211a7680-c252-11e9-88c1-1cd12928ee8a.PNG)
![attachment-5187878808980818685IMG_2816](https://user-images.githubusercontent.com/39692872/63240935-211a7680-c252-11e9-9bbc-c4c7021a2d3c.PNG)
![attachment-7883695631786524789IMG_2818](https://user-images.githubusercontent.com/39692872/63240936-211a7680-c252-11e9-9f9a-3d8c35dedc0e.PNG)

The problem is the info button in the bottom right corner of the map where the alert dialog opens when clicking on it. Is there any way to avoid this issue?

**Comment by julianrex** [comment]
@tkrami inclusion of the Mapbox Maps SDK for iOS should not trigger an App Store review rejection. Please consider including the following in a response to Apple:

> The links to mapbox.com and digitalglobe.com do not violate section [3.1.1 (In-App Purchase) of the App Store Guidelines](https://developer.apple.com/app-store/review/guidelines/#in-app-purchase). These links are part of the maps in the app. While a user could indirectly navigate these links to purchase services from Mapbox or Digital Globe, those purchases or subscriptions *cannot* be used in the app in any way. They are not related to and do not unlock any “features or functionality” of the app. Instead, they are mandatory attribution for the Mapbox “[datasources](https://www.mapbox.com/about/maps/#data-sources)” which are visible on maps in the app. This is required by the data provider and automatically included through their SDK: see https://docs.mapbox.com/help/how-mapbox-works/attribution/#mapbox-maps-sdk-for-ios.

/cc @chloekraw
