### ISSUE TITLE
Fill color is too light

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1541]
Our expected image is black `rgb(0, 0, 0)`:

![image](https://cloud.githubusercontent.com/assets/52399/7608597/5b7d172e-f96b-11e4-8bd6-e033945883c3.png)

However, we're getting `rgb(1, 1, 1)`:

![image](https://cloud.githubusercontent.com/assets/52399/7608601/6433569e-f96b-11e4-941b-0aeaae0d602e.png)

(ignore the border around the tile)

**Comment by kkaefer** [comment]
Seeing this on OS X 10.10.3 with a nVidia GeForce GT 650M.

**Comment by kkaefer** [comment]
This may be due to sRGB bits:

![image](https://cloud.githubusercontent.com/assets/52399/7608791/2d35f9ce-f96d-11e4-8373-f78bd7290c7e.png)

![image](https://cloud.githubusercontent.com/assets/52399/7608799/52a677d8-f96d-11e4-8d39-5a3db301fc51.png)

**Comment by tmpsantos** [comment]
I get the same here on Ubuntu 15.04 Vivid with an ATI Radeon HD 6850.

**Comment by tmpsantos** [comment]
> I get the same here on Ubuntu 15.04 Vivid with an ATI Radeon HD 6850.

Nah, my bad. On fill-color/default here only the borders are different.

**Comment by kkaefer** [comment]
Confirmed that this is the cause of images appearing too dark or bright compared to the reference image; the actual image data is not different. We [set the rendering intent to default](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/image.mm#L29), but it looks like Core Graphics is still outputting perceptual, or ICC color profiles.

**Comment by jfirebaugh** [comment]
@kkaefer Can you test this and #1542 against https://github.com/mapbox/mapbox-gl-test-suite/compare/update -- I updated the tests there using current gl-js and can no longer replicate either. Maybe it is due to a library on my machine being upgraded since the expected results were last generated.

**Comment by kkaefer** [comment]
@jfirebaugh https://github.com/mapbox/mapbox-gl-native/issues/1542#issuecomment-103818602

**Comment by jfirebaugh** [comment]
@kkaefer Can you test this again? I think it was fixed by either always running headless tests in node, or by #3083.
