### ISSUE TITLE
[android] Animating camera with tilt and map padding set couses big memory leaks in nativeCode leading to OOM

### ISSUE THREAD

**Issue by 2Rec** [mapbox/mapbox-gl-native#15411]
Animating camera with tilt and map padding set couses big memory leaks in nativeCode. 
### Steps to reproduce. Profiler from Android Studio shows huge memory usage. 1 minute -> from 120MB to over 500MB in native code.

 1. Set Map padding for example map.setPadding(0, 1000, 0, 0)
 2. Constantly updating one after another cameraPosition
map.easeCamera(CameraUpdateFactory.newCameraPosition(cameraPosition), 1000, false)

### Expected behavior
No leaks, no crashes, smooth movement

### Actual behavior
- Memory leaks, OOM crash

### Configuration

**Android versions:** 8.0.0
**Device models:** HTC U11
**Mapbox SDK versions:** 8.2.1

**Comment by astojilj** [comment]
Addressed with https://github.com/mapbox/mapbox-gl-native/pull/15195.

> map.setPadding(0, 1000, 0, 0)
Note that [setPadding uses logical view coordinates, not physical:](https://docs.mapbox.com/android/api/map-sdk/8.2.1/com/mapbox/mapboxsdk/maps/MapboxMap.html#setPadding-int-int-int-int-) and 1000 will most likely move the center of your screen way under the bottom of the screen.

**Comment by LukasPaczos** [comment]
Closing as resolved.
