### ISSUE TITLE
Opacity tests are slightly miscolored

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1542]
Almost all of the tests involving opacity have different color values (showing the diff images):

![image](https://cloud.githubusercontent.com/assets/52399/7610323/2f9c8e1c-f97c-11e4-98ff-e0e914332e47.png)
![image](https://cloud.githubusercontent.com/assets/52399/7610329/35a25292-f97c-11e4-8eca-89038fd62d00.png)
![image](https://cloud.githubusercontent.com/assets/52399/7610333/3fac7c36-f97c-11e4-8b7a-e2923c3d4e01.png)
![image](https://cloud.githubusercontent.com/assets/52399/7610335/49669356-f97c-11e4-9169-ec259f2f4b64.png)
![image](https://cloud.githubusercontent.com/assets/52399/7610349/7311ffec-f97c-11e4-9e21-c5ac6c7e65c5.png)

Not sure if the test case images is wrong (and JS should be changed) or whether this is an error in this library. Likely, this is related to premultiplication and/or floating point rounding/precision errors.

/cc @ansis

**Comment by kkaefer** [comment]
One issue is:

```
    "paint.opacity": {
      "fill-color": "rgba(255,0,0,1)",
      "fill-opacity": 0.5
    },
```
and 

```
    "paint.multiply": {
      "fill-color": "rgba(255,0,0,0.5)",
      "fill-opacity": 0.5
    }
```

don't resolve to the same color.

**Comment by jfirebaugh** [comment]
I think this turned out to be the same as #1554.

**Comment by kkaefer** [comment]
Nope, I'm seeing these images on OS X, not on Travis. OS X doesn't use the code you mentioned.

**Comment by kkaefer** [comment]
`fill-color/opacity`'s expected color is (255/127/127), but I'm seeing (255/128/128) rendered.

**Comment by kkaefer** [comment]
I'm still seeing the mismatch with the updated test suite. However, when I update the test suite with GL JS on my machine, then run the native tests, the outputs match (safe for the small missing lake polygons).

I suspect this is due to differences in GPU: When I force my GPU to the Intel HD 4000 (rather than the nVidia GeForce GT 650 M), I'm seeing differences in antialiasing (but no differences in the calculated color). Furthermore, the calculation for the `fill-color/opacity` test results in `0.5, 0, 0, 0.5`. Converting this to an actual color leaves us with a red value of 127.5. My guess is that some implementations round that down to 127, while some round it up to 128.

**Comment by kkaefer** [comment]
I'm seeing two ways to move forward here: When calculating colors, we should do change the resulting colors to a floating point value that will non-ambiguously map to an integer value when rendered as 8 bit RGBA: `round(color[0] * 255) / 255`; this would convert `0.5` to `0.5019607843137255`, which converts to 128 when rasterized.

The above quantization of color floats won't entirely solve our problem since implementations may still round differently when alpha compositing. Instead, we could add separate reference images for every GPU/driver and compare our result against all of them, and choose the one with the least differences when evaluating test outcome.

**Comment by kkaefer** [comment]
If we decide to quantize colors, we should also add this to JS /cc @ansis @mourner @tmcw

**Comment by mourner** [comment]
> Instead, we could add separate reference images for every GPU/driver and compare our result against all of them, and choose the one with the least differences when evaluating test outcome.

I'm finding this more and more appealing. But we can only do that if we can also generate those images easily, in semi-automated way. Otherwise doing any rendering changes will be super-painful.

**Comment by ljbade** [comment]
Hmm this is tricky. Is there a smarter way to do image comparisons that can handle slight brightness/tint changes but still flag obvious differences?

**Comment by jfirebaugh** [comment]
Fixed by using pixelmatch-based comparison.
