### ISSUE TITLE
Icon boundary is shifted by 1px

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1543]
The over-blurred icons from the `icon-halo-blur` test uncover that the frame in native is shifted by 1 px to the top and to the left compared to JS. @ansis, is this related to some of the recent changes you made?

![out](https://cloud.githubusercontent.com/assets/52399/7610708/409f80ae-f97f-11e4-87ed-a61492708845.gif)

Diff:

![image](https://cloud.githubusercontent.com/assets/52399/7610696/20284f2c-f97f-11e4-94fb-bca447eba5d7.png)

**Comment by ansis** [comment]
yes, https://github.com/mapbox/mapbox-gl-js/pull/1195
issue about porting: https://github.com/mapbox/mapbox-gl-native/issues/1398

We may also want to reduce the gamma used in these tests to a value the sdf can actually support here.

**Comment by jfirebaugh** [comment]
Covered by #1398.
