### ISSUE TITLE
Icon overlapping differences from test case

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1544]
The icons seem to overlap differently:

![out](https://cloud.githubusercontent.com/assets/52399/7611150/b90c7422-f982-11e4-9c08-7280835d3165.gif)

**Comment by jfirebaugh** [comment]
This is probably lack of y-ordering in native: https://github.com/mapbox/mapbox-gl-js/pull/1184 / https://github.com/mapbox/mapbox-gl-test-suite/pull/22

**Comment by jfirebaugh** [comment]
This was fixed.
