### ISSUE TITLE
Edge tiles do not render on pitched map

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#15442]
When the map is pitched and padded, the tiles on the edge of the screen can fail to render.

@astojilj edit:

----
@LukasPaczos, thanks for debugging.

Issue is reproducible with release-nectar branch, too. It is not related to padding as it is reproducible with no padding, too.

Camera setup used for reproducing:

```
latLng = {const mbgl::LatLng &} 
 lat = {double} 59.116898740996106
 lon = {double} 91.565660781803615
zoom = {double} 2.0551126748417214
bearing = {double} 0.74963938256567264
pitch = {double} 1.0471975511965976

width = {uint32_t} 412
height = {uint32_t} 691

```
----
The map height is `2418px`, top padding is `1000px` and pitch is `60`.
![ezgif com-video-to-gif (11)](https://user-images.githubusercontent.com/16925074/63451061-aa44cf80-c443-11e9-8207-5a178e37bd27.gif)

/cc @chloekraw @astojilj

**Comment by astojilj** [comment]
Issue description and title edit. Issue is not reproducible with JS.
