### ISSUE TITLE
VisibleFeatures function doesn't take in consideration fillExtrusionHeight of polygons

### ISSUE THREAD

**Issue by heltisace** [mapbox/mapbox-gl-native#15464]
### Steps to reproduce

 1. Create a style with MGLPolygonFeature.
 2. Add `fillExtrusionHeight` to it.
 3. Try calling `visibleFeatures` for any point of the feature that is beyond the base of the polygon.

### Expected behavior

It seems like that behavior is caused by the `UIView` point being converted to map coordinates/bound and then trying to get features for those. 
For current function parameters, it would be more right to return features as they are shown/rendered. So cases like getting a feature with `fillExtrusionHeight` won't be a problem.

### Actual behavior

The current function considers only the bases of polygons.

### Configuration

**Mapbox SDK versions: 5.2** 
**iOS/macOS versions: 12.4** 
**Device/simulator models: Any**
**Xcode version: 10.3**

**Comment by bravecow** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/3122 🙏

**Comment by julianrex** [comment]
@tmpsantos this sounds like a core issue, rather than specifically an iOS one - would you agree?

**Comment by tmpsantos** [comment]
Yes, agreed. We would need to do -> https://github.com/mapbox/mapbox-gl-native/issues/13139
