### ISSUE TITLE
Map is drawn over bottom sheet for transparent statusbar

### ISSUE THREAD

**Issue by DeKaN** [mapbox/mapbox-gl-native#15485]
### Steps to reproduce

 1. Use theme `Theme.MaterialComponents.Light.NoActionBar` (not `Theme.MaterialComponents.Light.DarkActionBar`)
 2. Add `android:fitsSystemWindows="true"` to root layout and to map
 3. Run app and try to drag bottom sheet
 4. Press power button to switch off and switch on the screen

Repo with code is [here](https://github.com/DeKaN/mapbox-bottomsheet-sample)
### Expected behavior
Map should be under bottom sheet component

### Actual behavior
Map is drawn over bottom sheet component

### Configuration

**Android versions:** Android 9
**Device models:** Nokia 5.1 and Android emulator
**Mapbox SDK versions:** 8.2.1 and 8.3.0-beta.1

**Comment by tobrun** [comment]
@DeKaN I believe this issue stems form using a GLSurffaceView as rendering surface. For this use-case, a TextureView will be more suitable. To enable this feature either enable it in xml with:

```xml
mapbox_renderTextureMode="true"
```

or in code with:

```java
MapboxMapOptions#textureMode(true)
```

closing as answered, let us know if this didn't resolve your issue. If not could you add some screenshot showcasing the issue?
