### ISSUE TITLE
setLocationManager is breaking Mapbox external location managers

### ISSUE THREAD

**Issue by racer1988** [mapbox/mapbox-gl-native#15483]
Hello!

`setLocationManager` on MGLMapView makes it impossible to set the internal map location manager to nil.

If set to `nil` it will always be reset to a default location manager. 
This is stated in the documentation.

However we are using a external location manager we handle, for tracking purposes, and we *dont* want to provide this to the map, as we don't want the map to track location updates on its own.

We are now forced to call `setActivityType` on the MapBox MapView LocationManager everytime a map is initialized, else the internal mapbox location manager is breaking our configuration by calling:

```
@implementation MGLCLLocationManager

- (instancetype)init
{
    if (self = [super init]) {
        _locationManager = [[CLLocationManager alloc] init];
        _locationManager.delegate = self;
    }
    return self;
}
```

As in iOS the CLLocationManager is internally shared, calling the above resets the fitness level of every other location manager created after this one.

We would suggest to make the location manager really nullable (and not resettable) and not provide a default one if the user does not need it, as this breaks the encapsulation of the framework and causes side effect on the external code

Thanks

**Comment by Selma-cmd** [comment]
Hello!
How can I get one publication of Dezember, 08 2013?
Please answer to my email
selmargfiorio@yahoo.com.br
Thanks a lot for your prompt answer.
Selma Goulart
