### ISSUE TITLE
Run Xcode static analyzer on CircleCI for iOS builds

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1549]
#1538 would’ve been caught like crazy by Xcode’s static analyzer. We should run the static analyzer on Travis since we apparently aren’t great about running it manually ourselves (#1425). From what I’ve seen, the analyzer doesn’t take all that long on our entire project. Note that we’ll need to whitelist some warnings in upstream libraries, which are tracked in memononen/libtess2#19 and [angusj/polyclipping#134](https://sourceforge.net/p/polyclipping/bugs/134/).

/cc @incanus

**Comment by incanus** [comment]
@1ec5 What's the state of this?

**Comment by 1ec5** [comment]
@incanus Further discussion in #1562. I believe the next step is to split the analysis into a separate target that can run in parallel with the others. But it still takes some 225 seconds for `make analyze`, which is just too high a penalty.

At this point, I’d be fine with a cron job on one of our local machines that analyzes the project every time we scrum.

**Comment by 1ec5** [comment]
Added an Xcode Analyze step to the nightly Bitrise workflow.

**Comment by 1ec5** [comment]
The Analyze step only works with schemes, not individual targets as gyp sets up. We’ll need to fix up the workflow after #4641 lands. In the meantime, I’ve removed the Analyze step to fix nightly builds.

**Comment by 1ec5** [comment]
Since https://github.com/mapbox/mapbox-gl-native/issues/1549#issuecomment-210634196, #4641 did land, making it possible to analyze a checked-in scheme. We also moved the iOS builds from Bitrise to CircleCI in #10257.

**Comment by friedbunny** [comment]
Done in `release-boba` via #11529.
