### ISSUE TITLE
Image missing callback impacts rendering of other layers

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#15497]
![ezgif com-video-to-gif (14)](https://user-images.githubusercontent.com/16925074/63776940-96d1b280-c8e2-11e9-83e8-66842aa60d4a.gif)

In the example above there are 3 layers that rely on one geojson source - circle layer and 2 symbol layers. After clicking the button, one of the images that the top layer uses (garbage bin) is removed from the map and starts to trigger the image missing callback which dramatically impacts the rendering of all layers that are based on this source. Other layers and the render thread itself seem to not be impacted as panning and zooming are smooth.

Bisection points to https://github.com/mapbox/mapbox-gl-native/pull/14320 as well.

/cc @tobrun @ansis @chloekraw

**Comment by LukasPaczos** [comment]
This can be reproduced on [lp-image-missing-impacts-other-layers](https://github.com/mapbox/mapbox-gl-native/compare/lp-image-missing-impacts-other-layers) by running the `Simple Map` example.

**Comment by pozdnyakov** [comment]
The fix got reverted at mapbox/mapbox-gl-native#15852
