### ISSUE TITLE
Android cannot push svg drawable in annotations marker icon

### ISSUE THREAD

**Issue by bassamfouad92** [mapbox/mapbox-gl-native#15533]
Unable to set svg drawable icon to com.mapbox.mapboxsdk.annotations.MarkerOptions class.

com.mapbox.mapboxsdk.annotations.MarkerOptions markerOptions1 = new com.mapbox.mapboxsdk.annotations.MarkerOptions().position(new com.mapbox.mapboxsdk.geometry.LatLng(Double.valueOf(coordinates[0]), Double.valueOf(coordinates[1]))).title("");
                            IconFactory iconFactory = IconFactory.getInstance(MainActivity.this);
                            Icon icon = iconFactory.fromResource(R.drawable.traffic);
                            markerOptions1.setIcon(icon);
                            mapboxMap.addMarker(markerOptions1);

`<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="25dp"
    android:height="25dp"
    android:viewportWidth="640"
    android:viewportHeight="640">
  <path
      android:pathData="M582.19,10C609.56,10 631.75,32.19 631.75,59.56C631.75,173.65 631.75,466.35 631.75,580.44C631.75,607.81 609.56,630 582.19,630C467.7,630 173.8,630 59.31,630C31.94,630 9.75,607.81 9.75,580.44C9.75,466.35 9.75,173.65 9.75,59.56C9.75,32.19 31.94,10 59.31,10C173.8,10 467.7,10 582.19,10Z"
      android:fillColor="#ffffff"
      android:fillAlpha="1"/>
  <path
      android:fillColor="#FF000000"
      android:pathData="M582.19,10C609.56,10 631.75,32.19 631.75,59.56C631.75,173.65 631.75,466.35 631.75,580.44C631.75,607.81 609.56,630 582.19,630C467.7,630 173.8,630 59.31,630C31.94,630 9.75,607.81 9.75,580.44C9.75,466.35 9.75,173.65 9.75,59.56C9.75,32.19 31.94,10 59.31,10C173.8,10 467.7,10 582.19,10Z"
      android:strokeAlpha="1"
      android:strokeWidth="1"
      android:fillAlpha="0"
      android:strokeColor="#484547"/>
  <path
      android:pathData="M509.13,297L571.13,297L571.13,429.25L509.13,429.25L509.13,297Z"
      android:fillColor="#ffffff"
      android:fillAlpha="1"/>
  <path
      android:pathData="M70.88,297L132.88,297L132.88,429.25L70.88,429.25L70.88,297Z"
      android:fillColor="#ffffff"
      android:fillAlpha="1"/>
  <path
      android:pathData="M218.8,53.37C238.1,53.37 253.75,69.02 253.75,88.33C253.75,168.14 253.75,372.61 253.75,452.42C253.75,471.73 238.1,487.38 218.8,487.38C186.99,487.38 126.51,487.38 94.7,487.38C75.4,487.38 59.75,471.73 59.75,452.42C59.75,372.61 59.75,168.14 59.75,88.33C59.75,69.02 75.4,53.37 94.7,53.37C126.51,53.37 186.99,53.37 218.8,53.37Z"
      android:fillColor="#514f4f"
      android:fillAlpha="1"/>
  <path
      android:fillColor="#FF000000"
      android:pathData="M218.8,53.37C238.1,53.37 253.75,69.02 253.75,88.33C253.75,168.14 253.75,372.61 253.75,452.42C253.75,471.73 238.1,487.38 218.8,487.38C186.99,487.38 126.51,487.38 94.7,487.38C75.4,487.38 59.75,471.73 59.75,452.42C59.75,372.61 59.75,168.14 59.75,88.33C59.75,69.02 75.4,53.37 94.7,53.37C126.51,53.37 186.99,53.37 218.8,53.37Z"
      android:strokeAlpha="1"
      android:strokeWidth="1"
      android:fillAlpha="0"
      android:strokeColor="#484547"/>
  <path
      android:pathData="M205.75,151.19C205.75,181.99 182.48,207 153.81,207C125.15,207 101.88,181.99 101.88,151.19C101.88,120.38 125.15,95.37 153.81,95.37C182.48,95.37 205.75,120.38 205.75,151.19Z"
      android:fillColor="#ae0a0a"
      android:fillAlpha="1"/>
  <path
      android:pathData="M205.75,279.19C205.75,309.99 182.48,335 153.81,335C125.15,335 101.88,309.99 101.88,279.19C101.88,248.38 125.15,223.37 153.81,223.37C182.48,223.37 205.75,248.38 205.75,279.19Z"
      android:fillColor="#ffde00"
      android:fillAlpha="1"/>
  <path
      android:pathData="M205.75,405.19C205.75,435.99 182.48,461 153.81,461C125.15,461 101.88,435.99 101.88,405.19C101.88,374.38 125.15,349.37 153.81,349.37C182.48,349.37 205.75,374.38 205.75,405.19Z"
      android:fillColor="#1bb366"
      android:fillAlpha="1"/>
  <path
      android:pathData="M132.81,487.38L174.81,487.38L174.81,630L132.81,630L132.81,487.38Z"
      android:fillColor="#393636"
      android:fillAlpha="1"/>
  <path
      android:pathData="M473.18,371.56L473.18,526L455.33,526L455.33,371.56L473.18,371.56Z"
      android:fillColor="#393636"
      android:fillAlpha="1"/>
  <path
      android:fillColor="#FF000000"
      android:pathData="M473.18,371.56L473.18,526L455.33,526L455.33,371.56L473.18,371.56Z"
      android:strokeAlpha="0"
      android:strokeWidth="1"
      android:fillAlpha="0"
      android:strokeColor="#000000"/>
  <path
      android:pathData="M586.13,233.07C586.13,257.63 586.13,321.61 586.13,346.17C586.13,351.52 581.74,355.87 576.33,355.87C529.54,355.87 398.97,355.87 352.17,355.87C346.76,355.87 342.38,351.52 342.38,346.17C342.38,321.61 342.38,257.63 342.38,233.07C342.38,227.72 346.76,223.37 352.17,223.37C398.97,223.37 529.54,223.37 576.33,223.37C581.74,223.37 586.13,227.72 586.13,233.07Z"
      android:fillColor="#000000"
      android:fillAlpha="0"/>
  <path
      android:fillColor="#FF000000"
      android:pathData="M586.13,233.07C586.13,257.63 586.13,321.61 586.13,346.17C586.13,351.52 581.74,355.87 576.33,355.87C529.54,355.87 398.97,355.87 352.17,355.87C346.76,355.87 342.38,351.52 342.38,346.17C342.38,321.61 342.38,257.63 342.38,233.07C342.38,227.72 346.76,223.37 352.17,223.37C398.97,223.37 529.54,223.37 576.33,223.37C581.74,223.37 586.13,227.72 586.13,233.07Z"
      android:strokeAlpha="1"
      android:strokeWidth="17"
      android:fillAlpha="0"
      android:strokeColor="#484547"/>
  <path
      android:pathData="M569.1,245.18L569.1,444.8L362.43,444.8L362.43,245.18L569.1,245.18Z"
      android:fillColor="#393636"
      android:fillAlpha="1"/>
  <path
      android:fillColor="#FF000000"
      android:pathData="M569.1,245.18L569.1,444.8L362.43,444.8L362.43,245.18L569.1,245.18Z"
      android:strokeAlpha="0"
      android:strokeWidth="1"
      android:fillAlpha="0"
      android:strokeColor="#000000"/>
  <path
      android:pathData="M465.76,406.89C431.84,406.89 404.31,380.62 404.31,348.26C404.31,315.89 431.84,289.62 465.76,289.62C499.68,289.62 527.21,315.89 527.21,348.26C527.21,380.62 499.68,406.89 465.76,406.89Z"
      android:fillColor="#6de6ed"
      android:fillAlpha="1"/>
  <path
      android:fillColor="#FF000000"
      android:pathData="M465.76,406.89C431.84,406.89 404.31,380.62 404.31,348.26C404.31,315.89 431.84,289.62 465.76,289.62C499.68,289.62 527.21,315.89 527.21,348.26C527.21,380.62 499.68,406.89 465.76,406.89Z"
      android:strokeAlpha="0"
      android:strokeWidth="1"
      android:fillAlpha="0"
      android:strokeColor="#000000"/>
  <path
      android:pathData="M174.81,519.38L473.18,519.38L473.18,540L174.81,540L174.81,519.38Z"
      android:fillColor="#393636"
      android:fillAlpha="1"/>
</vector>`

**Comment by tobrun** [comment]
@bassamfouad92 could you add a bit more color to this issue? Are you running into `IllegalArgumentException("Failed to decode image. The resource provided must be a Bitmap.")` or is the image not showing up?

**Comment by bassamfouad92** [comment]
@tobrun Image is not showing on the map  (while setting marker in the map). Didn't get any error
