### ISSUE TITLE
[Android] Expression interpolation with -0.1 and 0 as steps is not working 

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-native#15532]
This is an upstream ticket for https://github.com/react-native-mapbox-gl/maps/issues/349

### Steps to reproduce

 1. Define the following expression:

```
fillColor: [
      'interpolate',
      ['linear'],
      ['get', 'drval1'],
      -0.1,
      'red',
      0,
      'blue',
    ],
  },
```

 2. This will default to a black fillColor and log:

```
Mbgl    : {mapboxglexample}[JNI]: Error setting property: fill-color [5]: Input/output pairs for "interpolate" expressions must be arranged with input values in strictly ascending order.
```

A few working variations are: `[0, 'red', 0.1, 'blue']`, `[-0.1, 'red', 0.1, 'blue']`.

Additional non-working variations: `[-0.2, 'red', -0.1, 'blue']`, `[-0.9, 'red', -0.1, 'blue']`

### Expected behavior

The expression is valid for iOS and Web, and should be valid for Android as well.

### Actual behavior

The expression is not valid for Android.

### Configuration

**Mapbox SDK versions:** `8.2.1`

**Comment by tobrun** [comment]
@kristfal Thank you for reaching out and providing a reproducible test. I was able to reproduce and attached a debugger to the expression validation:

![image](https://user-images.githubusercontent.com/2151639/64129078-2c28e700-cdba-11e9-92b7-643615e540ee.png)

You can see that we are handling both the `-0.1` and `0` as `0`.

**Comment by tobrun** [comment]
Quickly verified what we pass over to the c++ from java and that is looking as expected:

![image](https://user-images.githubusercontent.com/2151639/64129329-b756ac80-cdbb-11e9-9221-24c1e6d0402d.png)

**Comment by tobrun** [comment]
I went one step further down the chain, verified the values in our conversion system for value in `android_conversion.hpp`. Those seem to check out as well*:

![Screenshot from 2019-09-03 15-08-50](https://user-images.githubusercontent.com/2151639/64172287-4667d100-ce5d-11e9-8691-45aa377fc23a.png)

![Screenshot from 2019-09-03 15-09-51](https://user-images.githubusercontent.com/2151639/64172274-3f40c300-ce5d-11e9-85d6-e7a14cebfdea.png)

* = except that we are inputting a float and converting it to a double

**Comment by tobrun** [comment]
:man_facepalming:, thanks @LukasPaczos for pointing out the long conversion issue. This should be the rootcause and removing fixes the issue.

**Comment by Bradeskojest** [comment]
A question. I have similar problems with zoom(), when "step" is only reacting to integer values, and not doubles or fractional zoom levels. 

For example, this is only reacting to zoom steps at Integer values, even if ZOOM constant is 8.5:
```
  iconAllowOverlap(
                    step(zoom(), literal(false), stop(OVERLAP_ZOOM, true))
                ),
```
