### ISSUE TITLE
Drag and Drop  ( I want to take Lat Lon from two annotations ) and store them.

### ISSUE THREAD

**Issue by naeemAkee** [mapbox/mapbox-gl-native#15545]
Hello Sir, I'm using Mapbox, 

I want to use two annotations, starting and ending annotation. 

I want to drag and drop on both annotations and get both **Lat Lon** 

How can I do that ?

**Comment by tobrun** [comment]
Thank you for reaching out, this repository is used to request features and report bug fixes. For support, please contact us at https://www.mapbox.com/contact/ or post a question on StackOverflow.

**Comment by naeemAkee** [comment]
https://stackoverflow.com/questions/57769745/drag-and-drop-i-want-to-take-lat-lon-from-two-annotations-and-store-them-map
