### ISSUE TITLE
Support for draggable Layers (MGLSymbolStyleLayer)

### ISSUE THREAD

**Issue by awdhootlele** [mapbox/mapbox-gl-native#15554]
Does the ios native  mapbox sdk has support for draggable Symbol layer (MGLSymbolStyleLayer)?

I know the AnnotationView can be draggable, but the [react-native-mapbox-gl ](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/PointAnnotation.md) library I use says that PointAnnotation (AnnotationView) will soon become deprecated and suggest to use the Symbol Layer instead.

So does the library support DnD for Symbol Layer? Or is there a roadmap for this feature?

Thanks!

**Comment by kunal886496** [comment]
Go away stalebot.
