### ISSUE TITLE
Crash on setVisibleCoordinateBounds with calculated bound from MGLCoordinateBounds(centre: distance: distanceInHalf:)

### ISSUE THREAD

**Issue by matthiaskmt** [mapbox/mapbox-gl-native#15555]
In our app, we calculate a bounding box based on a location and the length of a tour. In a rare edge-case, this length is pretty high. 

We use the following method to calculate the 
**Input values:**
```
startLocation.coordinate: CLLocationCoordinate2D
  - latitude : 48.5216274484992
  - longitude : 9.05204102396965
```
- tour.distance:  5069000

``` 
MGLCoordinateBounds(withCenter: startLocation.coordinate,
                                       distance: tour.distance, distanceInHalf: false)
```

the result is a bounds of 
```
 MGLCoordinateBounds
  ▿ sw : CLLocationCoordinate2D
    - latitude : 2.9372688281776718
    - longitude : -59.56856410906127
  ▿ ne : CLLocationCoordinate2D
    - latitude : 94.10598606882073
    - longitude : 77.67264615700057
```

There is an exception if I take this bounds as input for the following method 

```
mapView.setVisibleCoordinateBounds(tourBox,
                                           edgePadding: edgeInsets,
                                           animated: animated,
                                           completionHandler: nil)
``` 
**Mapbox SDK versions:** 5.2.0
**iOS/macOS versions:** 12.4

**Comment by racer1988** [comment]
maybe the bounding box is too big for the mapView min-zoom level or the bounding box overlaps itself?

if there are checks internally on `setVisibleCoordinateBounds` that might throw exceptions due to zoom levels or too large box, we could get them thrown outside to the caller so we can react accordingly?
