### ISSUE TITLE
[core] Enable `icon-text-fit` with `text-offset` and `text-radial-offset`

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-native#15553]
Need to see if this bug (https://github.com/mapbox/mapbox-gl-js/issues/8722) is reproducible on mobile with https://github.com/mapbox/mapbox-gl-native/pull/15367 merged. If so, it is a release blocker and the fix needs backport to `queso`.

@mapbox/maps-android a repro would be appreciated if you have bandwidth!

---

### Expected Behavior

I would expect collision rules to be governed by `text-offset` when a symbol layer is using `icon-text-fit`.

### Actual Behavior

Here's an example of a layer using `text-offset` vs a layer using `text-offset` and `icon-text-fit`. I would expect the text-offset value to continue to not force a collision with the icon below:

![text-offset-with-icon-fit](https://user-images.githubusercontent.com/61150/64210047-37d6e500-ce70-11e9-912a-867d008645cf.gif)

---

### Link to Demonstration

https://api.mapbox.com/styles/v1/tristen/cjzu99z8h00qp1co0srxwywwn.html?fresh=true&title=true&access_token={TOKEN}#7.9/43.797847/-79.658695

cc @tmpsantos @zugaldia

**Comment by tarigo** [comment]
Reproducible on Android (latest master):

text-offset: { 0.0, 0.95 } 
![Screenshot_1567774482](https://user-images.githubusercontent.com/208208/64429802-81693f00-d0bf-11e9-8ee8-c323eace0fcc.png)

text-offset: { 0.0, 0.95 } + icon-text-fit: "width"
![Screenshot_1567774648](https://user-images.githubusercontent.com/208208/64429819-8b8b3d80-d0bf-11e9-8925-219447e6448b.png)

**Comment by chloekraw** [comment]
Thanks @tarigo! cc @tmpsantos

**Comment by alexshalamov** [comment]
@tarigo @chloekraw Cannot reproduce with native.

Native:
![image](https://user-images.githubusercontent.com/1001009/64519529-f9707880-d2fc-11e9-809b-d731db313d6a.png)

GL-JS
![image](https://user-images.githubusercontent.com/1001009/64519605-1ad16480-d2fd-11e9-964c-ca576ccaba4e.png)

Style, Basic Template with duplicated poi-label that has 2 additional layout properties.
```
"icon-text-fit": "both",
"text-offset": [0, -2.2],
```
mapbox://styles/alexshalamov/ck0c6kpn702ve1do0dvj792e6/draft

**Comment by chloekraw** [comment]
Thanks for checking @alexshalamov. @zugaldia could we continue investigation on the SDK side for a possible bug? Also, let's check if it can be reproduced on @mapbox/maps-ios.

**Comment by alexshalamov** [comment]
Cannot reproduce in native, removing myself from assignment.

**Comment by tarigo** [comment]
After detailed inspection I can confirm, that on Android (gl-native) the behavior is correct:
![gl-native](https://user-images.githubusercontent.com/208208/66379460-26787f80-e9be-11e9-8923-d1c6bd99fc81.png)
While gl-js does not handle it as expected:
![gl-js](https://user-images.githubusercontent.com/208208/66379657-84a56280-e9be-11e9-8297-28f17a334ded.png)
