### ISSUE TITLE
MGLOfflineStorage addPackForRegion gets slower and slower depending on the number of tiles already in DB 

### ISSUE THREAD

**Issue by racer1988** [mapbox/mapbox-gl-native#15567]
[addPackForRegion](https://docs.mapbox.com/ios/api/maps/5.3.0/Classes/MGLOfflineStorage.html#/c:objc(cs)MGLOfflineStorage(im)addPackForRegion:withContext:completionHandler:) becomes extremely slow after some packs have been added to the Database.

It takes different seconds before the completion handler is called.
Is this intended? 

Shouldn't the pack be added immediately and the calcualtion of the progress done asynchronous?

it seems from outside that the DB is running over ALL the tiles already in DB and this is extremely slow.

similar to #15297

### Configuration

**Mapbox SDK versions:** 5.2.0

**Comment by chloekraw** [comment]
@racer1988, I think your issue could be resolved by https://github.com/mapbox/mapbox-gl-native/pull/15521. I’d test with the latest `alpha` and see if you can reproduce this.

**Comment by racer1988** [comment]
@chloekraw I will test this soon, however I can see that the first load is still impacted by a huge time hit.

If my user choose a region far away and ask me to download it (i take all zoom levels) then the method will still be in the same ~ amount of time right?
