### ISSUE TITLE
Performance: Running removePack on multiple packs in parallel makes the DefaultFileSource queue stuck to 100% for a long time

### ISSUE THREAD

**Issue by racer1988** [mapbox/mapbox-gl-native#15573]
This is a performance issue that is also the reason of another crash discovered and reported in #15536.

Running `removePack` on multiple packs in parallel makes the DefaultFileSource queue stuck to 100% for a long time

To give a more contextualized example:
To show on UI how much space would a specific map region take if offlined, I estimate the size by checking the number of resources needed for a map region.

At next launch, as these packs are not needed anymore (as they have not been started),
I want to remove all this packs that have just been used for estimations.

To do that I first filter for this packs, and then run `storage.removePack(pack)` for each of them in a `for loop`.

What I noticed is that when sending multiple deletion request to the DB that will run in parallel, the DB thread (DefaultFileSource) becomes clogged and slow and take a big number of second to complete all the deletion requests.

Running the `storage.removePack(pack)` on the same list in a serial manner is extremely fast in comparision (factor of milliseconds vs 10+ seconds)

```Swift
// Extremely simplified example
for pack in toRemovePacks {
        storage.removePack(pack)
}
```
### Configuration

**Mapbox SDK versions:** 5.2.0
**iOS/macOS versions:** 
**Device/simulator models:**
**Xcode version:**

**Comment by julianrex** [comment]
@tmpsantos FYI I am investigating #15536, but your thoughts/input here would be welcome.
