### ISSUE TITLE
Drag and Drop  annotations and get Lat Lon.

### ISSUE THREAD

**Issue by naeemAkee** [mapbox/mapbox-gl-native#15576]
Hello Sir, I'm using Mapbox,

I want to use two annotations, starting and ending annotation.

I want to drag and drop on both annotations and get both Lat Lon

How can I do that ? I can't solve that.

**Comment by LukasPaczos** [comment]
Hey @naeemAkee, this repository for bug fixes and feature requests only. For general help, please check out our [support pages](https://support.mapbox.com/hc/en-us) or reach out on forums like [StackOverflow](https://stackoverflow.com/).

**Comment by naeemAkee** [comment]
No one replied me there
