### ISSUE TITLE
Android: Sync Offline Region

### ISSUE THREAD

**Issue by JRWilding** [mapbox/mapbox-gl-native#15590]
We'd like to be able to trigger an update for an entire offline region. Some tiles in one of our tile sets in our style are updated periodically, and we'd like to update those without redownloading the entire region.

Currently we create a new region covering the same area and then delete the old region. However, the etag doesn't seem to be used when we do this, so the entire area gets redownloaded.

The invalidate method on OfflineRegion causes only the tiles that the user then interacts with (on a map) to be checked (using the etag) and not the entire region.

**Comment by kristfal** [comment]
Very interested in seeing this as well for both iOS and Android. Something like [invalidateAmbientCache](https://docs.mapbox.com/android/maps/overview/cache-management/#management-methods) but for the offline cache. 

I'd imagine it would iterate over the tiles in a given offline cache, and download a tile if was outdated.
