### ISSUE TITLE
[ios] Upgrade project to Swift 5

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#15591]
Let's upgrade any Swift files to Swift 5

- [ ] Converted tests
- [ ] Converted Playground
- [ ] Tested with Xcode 10.3
- [ ] Tested with Xcode 11

EDIT: The bulk of this was done in https://github.com/mapbox/mapbox-gl-native/pull/14326

**Comment by friedbunny** [comment]
We updated to Swift 5.0 in #14326 — presumably this is about moving to 5.2.

**Comment by julianrex** [comment]
@jmkiley can you see if any changes are required to move to 5.x please?

**Comment by jmkiley** [comment]
I'm not seeing any necessary changes specific to Swift 5. There are a few small changes that will need to be made in order to get the playground working again. I'll open a PR for that.

**Comment by julianrex** [comment]
Closing, since this was handled elsewhere.
@jmkiley please re-open if necessary.
