### ISSUE TITLE
how to style the layer using expression - get more than one property

### ISSUE THREAD

**Issue by bar3200** [mapbox/mapbox-gl-native#15595]
I have circle layer and I want to match color based on two properties.
Is there any expression to do that?

**Comment by JRWilding** [comment]
What are the properties and how do you want to use them?
You can nest expressions and there are a number of math functions (see https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-math) represented by expressions if they are numeric values.
If they are booleans, you could `case` or `match` (see https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-decision)

**Comment by bar3200** [comment]
Hi, The properties are strings.
I want to be able to color the features by the value of these strings.
For example:

"final" and "big" = red
"initial" and "small" = green
"initial" and "big" = blue

**Comment by LukasPaczos** [comment]
A tree of decision paths built from https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-decision that @JRWilding linked should get the job done @bar3200, even for strings. You can use the `get` expression on any depth level.

Let us know if that wasn't enough for your use case!

**Comment by zhiwo** [comment]
> A tree of decision paths built from https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-decision that @JRWilding linked should get the job done @bar3200, even for strings. You can use the `get` expression on any depth level.
> 
> Let us know if that wasn't enough for your use case!

I don't know how to use it on the Android side. Is there a Demo?

**Comment by LukasPaczos** [comment]
@zhiwo you can see a boolean expression in action [here](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/StyleCirclesCategoricallyActivity.java#L68-L74) - we're setting the color based on the feature property.

Instead of setting the color on the first result, you could nest another expression instead.
