### ISSUE TITLE
[iOS] Question about get snapshot with overlays(annotations) already added on map

### ISSUE THREAD

**Issue by 591700757** [mapbox/mapbox-gl-native#15618]
Hello there, I' m immigrate my old project by replace the old map to mapbox.
I want to get the snapshot of the map with every overlay added on it on almost every where 
I use map.  I tried `MGLMapSnapshotter` and `MapboxStatic.swift` , but both of them did not give me the snapshot with overlay.  I just want to if there is a easy way to get snapshot with overlay. Otherwise, I just have to use MapboxStatic to create basic snapshot without overlays.
And add overlays on it(Just like MKMapSnapshotter?).

I read the `MGLMapSnapshotter` which tells me I can use MapboxStatic and add overlay after 
snapshot. But it don't quite mention if there is a way to get snapshot with overlay already added on the map.And the `Add support for annotations when snapshotting` issues seems still open:
https://github.com/mapbox/mapbox-gl-native/issues/11113
 
I really looking forward for the answers. So I can make the strategy, and ask my boss the give
 me proper time to do it.

### Steps to reproduce

 1.I tried `MGLMapSnapshotter`

### Expected behavior
Get snapshot with overlays already added on `MGLMapView`

### Actual behavior
I got snapshot of map with no overlays just like `MKMapSnapshotter`.

### Configuration

```
let options = MGLMapSnapshotOptions(styleURL: mglMapView.styleURL, camera: mglMapView.camera, size: expectMapSize)
                options.zoomLevel = mainMapVC.mglMapView.zoomLevel
                self.snapshotter = MGLMapSnapshotter(options: options)
```

**Comment by yosi199** [comment]
Joining in here - I was surprised to see a snapshot of the map without the polylines drawn too. Would love to have this built in
