### ISSUE TITLE
[meta] Failing CI jobs on master should notify responsible parties

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#15614]
When a CI job fails on `master`, that’s an indication that something is wrong and that we should try to address the issue as soon as reasonably possible. Since we currently don’t really pay attention to the build results on `master`, situations like #15613 can develop where every build is consistently failing for several days. We can also miss intermittent failures, which should never happen on `master`.

To keep `master` green at all times, when a build on that branch flakes/fails we should notify the team responsible for the failing CI job so that they can promptly fix it. The iOS Maps team has been using Slack notifications (https://github.com/mapbox/mapbox-gl-native/pull/12750) to let us know when nightly/deployment CI jobs fail, which we then quickly triage in a thread. This has been working well and we should expand Slack notifications to cover all jobs and assign teams/channels for each.

/cc @tmpsantos @brunoabinader @tobrun @zugaldia @julianrex @springmeyer

**Comment by springmeyer** [comment]
> that’s an indication that something is wrong and that we should try to address the issue as soon as reasonably possible.

👍 

However, while I think notifications are a great idea, we should do more:

I think we should check this box in the branch protections:

<img width="710" alt="Screen Shot 2019-09-11 at 8 20 37 PM" src="https://user-images.githubusercontent.com/20300/64751686-caf7c680-d4d1-11e9-8265-ebfda076fa3e.png">

The effect of this will be that any PRs that are less than super fresh are run on CI at least one last time before merging, which will increase the likelyhood that the PR owner will notice their PRs flakyness, if it exists.

**Comment by friedbunny** [comment]
Unfortunately, requiring branches to be up to date before merging isn’t really tenable in a large monorepo with ~20-30 minute build times. The rate at which you can merge changes effectively becomes the length of your longest build, which would definitely lead to congestion during busy periods. (Not to mention frustration at some other PR merging just as you were ready to merge yours, meaning that you have to wait _another_ cycle.)

**Comment by tmpsantos** [comment]
A solution I have seen in some large projects with long CI times is to auto-revert the PR if when lands on master, it makes the bots red.
