### ISSUE TITLE
Images for annotations bug when zoom out map too much in iOS

### ISSUE THREAD

**Issue by AEiosApp** [mapbox/mapbox-gl-native#15627]
Hi, I'm using MapBox  and experiencing an issue with images for annotations (custom pins images on the map).

### Expected behavior

Everything works fine when I zoom in map enough (see "Zoom in Simulator" in att.).
https://drive.google.com/open?id=13JtgqbtfG5sLcyYYW58aPZCY6RKRUR-Z

### Actual behavior

However, if I zoom out map much enough, I have an issue with my custom images for annotations (see "Zoom Out Bug Simulator" in att.) both in Simulator and physical iPhone 7 (see "Zoom Out Bug iPhone 7")

https://drive.google.com/open?id=1xfpFjZbP_lZKsRMDwhnd49GeVncb8uLx
https://drive.google.com/open?id=1anWGZvoDGZp37aj7EfqQGxCVaVSIINUv

How to fix this bug?

### Configuration

**Mapbox SDK versions: v 5.2.0 
**iOS/macOS versions: iOS 12.4
**Device/simulator models: iPhone 7 and Simulator
**Xcode version: 10.3

**Comment by julianrex** [comment]
Thanks for the report @AEiosApp - can you provide a minimal sample application that demonstrates this issue so that we can investigate?

**Comment by AEiosApp** [comment]
Yes, I can share my apps code. But I'm not ready to put the link to it to public access.
Can I provide it to you in any private way?

**Comment by AEiosApp** [comment]
any update with the issue?
