### ISSUE TITLE
background-image tests are nondeterministic

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1563]
Sometimes the `background-image` (zoomed, literal, rotated) headless tests fail to render anything. This is due to the removal of the `sprite->isLoaded()` check in e2749597534d351d81cb8c2a2bc9b9886fef8028 -- without that there's no guarantee that the image used for rendering the background is ready.

**Comment by tmpsantos** [comment]
Oh, I didn't know that we were using a sprite for rendering the background.
