### ISSUE TITLE
[core] Assert fires in LayerFactory::createBucket

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#15636]
As of https://github.com/mapbox/mapbox-gl-native/commit/40b0cb74cb9e9aae85d748f4d4ea2156cc40f4fa, when running the iOS Integration Test Harness tests, specifically `testForRaisingExceptionsOnStaleLayerObject`, there's an assert in:

https://github.com/mapbox/mapbox-gl-native/blob/40b0cb74cb9e9aae85d748f4d4ea2156cc40f4fa/src/mbgl/layermanager/layer_factory.cpp#L28-L31

for a factory of type `RasterStyleLayerPeerFactory`. Missing function?

@tmpsantos suggested this may be a regression introduced in https://github.com/mapbox/mapbox-gl-native/pull/15308

/cc @tobrun

**Comment by pozdnyakov** [comment]
The reason is that we allow adding layers incompatible with sources. In the test a raster layer is added to a vector source.
