### ISSUE TITLE
Storyboard tests

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1564]
We need automated tests of `MGLMapView` in storyboards.

**Comment by jfirebaugh** [comment]
This is the same as #1569, which is more detailed, right?

**Comment by 1ec5** [comment]
This ticket covers headless tests of the storyboard at runtime. #1569 covers UI tests of the storyboard at design time, inside Interface Builder. This ticket is far more actionable at this point.
