### ISSUE TITLE
[ios] Pitch/Heading equality precision seems too coarse

### ISSUE THREAD

**Issue by m-stephen** [mapbox/mapbox-gl-native#15668]
Our camera equality precision seems too coarse on `pitch` and `heading`:

```
- (BOOL)isEqualToMapCamera:(MGLMapCamera *)otherCamera
{
    if (otherCamera == self)
    {
        return YES;
    }
    
    return (MGLEqualFloatWithAccuracy(_centerCoordinate.latitude, otherCamera.centerCoordinate.latitude, 1e-6)
            && MGLEqualFloatWithAccuracy(_centerCoordinate.longitude, otherCamera.centerCoordinate.longitude, 1e-6)
            && MGLEqualFloatWithAccuracy(_altitude, otherCamera.altitude, 1e-6)
            && MGLEqualFloatWithAccuracy(_pitch, otherCamera.pitch, 1)
            && MGLEqualFloatWithAccuracy(_heading, otherCamera.heading, 1));
}
```

It will cause a stuttering on maps when user try to tilt the map as zoom in.
The idea is to improve the equality precision for `pitch` and `heading` to `1e-2`.

Any other ideas for this issue? @1ec5 

cc: @julianrex

**Comment by chloekraw** [comment]
@mapbox/maps-android what do we do on android?

cc @mapbox/gl-native

**Comment by tobrun** [comment]
> @mapbox/maps-android what do we do on android?

When doing a comparison of camera positions, we do not change the accuracy of the comparison.
