### ISSUE TITLE
Update mapbox-java to stable version

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#15689]
We are currently packaging an alpha build of mapbox-java from https://github.com/mapbox/mapbox-gl-native/pull/15570. 
For the final release, this needs to be updated to a stable release.

**Comment by langsmith** [comment]
Stable `4.9.0` release is moving at https://github.com/mapbox/mapbox-java/pull/1080 and https://github.com/mapbox/mapbox-java/issues/1070
