### ISSUE TITLE
Interface Builder hangs loading MGLMapView designable in storyboard

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1568]
Interface Builder doesn't reload the MGLMapView IB extensions in a Storyboard after it's been created previously.  I'm using Cocoapods with the following Podfile.

```
use_frameworks!
pod 'MapboxGL', '~>0.3.0'
```
The Identity Inspector does display "User Defined Runtime Attributes" however.

![20150515-identify-inspector](https://cloud.githubusercontent.com/assets/989928/7660005/0e2c3804-fb0c-11e4-99ca-b156f08726f8.png)
_Identity Inspector_

![20150515-attributes-inspector](https://cloud.githubusercontent.com/assets/989928/7660006/11b6563a-fb0c-11e4-8560-064a8f4971b7.png)
_Attributes Inspector_

@mapbox/mobile

**Comment by 1ec5** [comment]
To make matters worse, sometimes I get the following hang when IB _does_ pick up the designable/inspectables:

```
    +                                           2663 -[MGLMapView commonInit]  (in MapboxGL) + 895  [0x11833e85f]  MGLMapView.mm:270
    +                                             2663 mbgl::Map::Map(mbgl::View&, mbgl::FileSource&, mbgl::MapMode, bool)  (in MapboxGL) + 532  [0x1182a92d4]  map.cpp:14
    +                                               2663 mbgl::util::detail::unique_type<mbgl::util::Thread<mbgl::MapContext> >::single mbgl::util::make_unique<mbgl::util::Thread<mbgl::MapContext>, char const (&) [4], mbgl::util::ThreadPriority, mbgl::View&, mbgl::FileSource&, mbgl::MapData&, bool&>(char const (&&&) [4], mbgl::util::ThreadPriority&&, mbgl::View&&&, mbgl::FileSource&&&, mbgl::MapData&&&, bool&&&)  (in MapboxGL) + 108  [0x1182aad3c]  std.hpp:21
    +                                                 2663 mbgl::util::Thread<mbgl::MapContext>::Thread<mbgl::View&, mbgl::FileSource&, mbgl::MapData&, bool&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, mbgl::util::ThreadPriority, mbgl::View&&&, mbgl::FileSource&&&, mbgl::MapData&&&, bool&&&)  (in MapboxGL) + 233  [0x1182af7d9]  thread.hpp:126
    +                                                   2663 std::__1::future<void>::get()  (in libc++.1.dylib) + 25  [0x110d00faf]
    +                                                     2663 std::__1::__assoc_sub_state::copy()  (in libc++.1.dylib) + 43  [0x110d00d33]
    +                                                       2663 std::__1::__assoc_sub_state::__sub_wait(std::__1::unique_lock<std::__1::mutex>&)  (in libc++.1.dylib) + 83  [0x110d00e03]
    +                                                         2663 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)  (in libc++.1.dylib) + 47  [0x110d00475]
    +                                                           2663 __psynch_cvwait  (in libsystem_kernel.dylib) + 10  [0x111506136]
    2663 Thread_160415: SQLite Cache
    + 2663 thread_start  (in libsystem_pthread.dylib) + 13  [0x11153541d]
    +   2663 _pthread_start  (in libsystem_pthread.dylib) + 176  [0x1115371e5]
    +     2663 _pthread_body  (in libsystem_pthread.dylib) + 131  [0x111537268]
    +       2663 std::__1::__thread_proxy<std::__1::tuple<mbgl::util::Thread<mbgl::SQLiteCache::Impl>::Thread<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, mbgl::util::ThreadPriority, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&&&)::'lambda'()> >(void*, void*)  (in MapboxGL) + 101  [0x11835d225]  thread:175
    +         2663 mbgl::util::Thread<mbgl::SQLiteCache::Impl>::Thread<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, mbgl::util::ThreadPriority, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&&&)::'lambda'()::operator()() const  (in MapboxGL) + 213  [0x11835d345]  thread.hpp:141
    +           2663 uv_run  (in MapboxGL) + 193  [0x1183615a1]  core.c:317
    +             2663 kevent  (in libsystem_kernel.dylib) + 10  [0x11150721a]
```

**Comment by bleege** [comment]
Also seeing that Cocoapods isn't loading the pod at all now.

![20150515-cocopods-not-loading](https://cloud.githubusercontent.com/assets/989928/7660080/9fc855e0-fb0c-11e4-876d-d223c074d10f.png)

**Comment by 1ec5** [comment]
@bleege, you need to open Fences.xcworkspace, not Fences.xcodeproj.

**Comment by bleege** [comment]
@1ec5 Good catch!  I should also confirm now that I'm using the correct one (xcworkspace), the issues reported above are still existing.

**Comment by 1ec5** [comment]
Reproduces on the ios-b1 branch but not master. @incanus, any insight into what might’ve been left out that would cause this hang?

**Comment by incanus** [comment]
> any insight into what might’ve been left out 

No; here's the diff: https://github.com/mapbox/mapbox-gl-native/compare/ios-b1...master

**Comment by incanus** [comment]
MapKit supports `IBInspectable`, which lets the developer configure properties of the map view such as center coordinate in a visual way in Interface Builder. 

MapKit _doesn't_ support `IBDesignable`, which would render a preview of the map view right in IB. Instead, it's just a pre-iOS 8-style "dumb blue box". 

![anigif-1431720147](https://cloud.githubusercontent.com/assets/17722/7661996/609208f8-fb0c-11e4-99e0-3f056a9b6995.gif)

_MapKit in action_

We support both (https://github.com/mapbox/mapbox-gl-native/issues/929), and what is broken right now is `IBDesignable`, meaning that most devs, particularly newer ones, will want to use the IB setup method and are blocked 100% of the time in `0.3.0`. 

IMHO `IBDesignable` is nice to have, and we have a good setup there (showing the Mapbox logo and making sure that an access token is set), but it's not essential. Especially if it blocks everyone from using IB right now. 

I just tested locally and applying this patch (i.e. removing one line) fixes the problem and puts us on par with MapKit — for now. 

```diff
diff --git a/include/mbgl/ios/MGLMapView.h b/include/mbgl/ios/MGLMapView.h
index 9d7b5c9..e21c743 100644
--- a/include/mbgl/ios/MGLMapView.h
+++ b/include/mbgl/ios/MGLMapView.h
@@ -13,7 +13,6 @@
 *   Use of MGLMapView requires a Mapbox API access token. Obtain an access token on the [Mapbox account page](https://www.mapbox.com/account/apps/). If you instantiate an MGLMapView from Interface Builder, rendering of the map won't begin until the accessToken property has been set.
 *
 *   @warning Please note that you are responsible for getting permission to use the map data, and for ensuring your use adheres to the relevant terms of use. */
-IB_DESIGNABLE
 @interface MGLMapView : UIView
 
 #pragma mark - Initializing a Map View
```

How does this sound for a plan of attack: 

- Apply the above patch and roll an `0.3.1` for today to cover our bases with users. 
- Attempt to figure out why this seems to work in `master` and cherry-pick the changes back to the `ios-b1` branch, rolling an `0.3.2` if successful. 
- Ship the same changes as part of b2 (`0.4.0`?) based on `master`. 

/cc @1ec5 @bleege @jfirebaugh

**Comment by 1ec5** [comment]
For what it’s worth, a blue box is better than a transparent one for usability, but I completely agree with this proposal @incanus.

**Comment by bleege** [comment]
Make it unanimous.  Interface Builder **has to** work with Mapbox GL at launch.

**Comment by incanus** [comment]
Cool, I'll get rolling this now.

**Comment by incanus** [comment]
Removed in https://github.com/mapbox/mapbox-gl-native/commit/5a918cbb2c97271b3144fb8aace06f6fbdf30cb9 and rolling build now.

**Comment by bleege** [comment]
@incanus Cool.  I'll test it out on Fences when it's ready.

**Comment by incanus** [comment]
`0.3.1` is out on CocoaPods.

**Comment by bleege** [comment]
^ and successfully tested!  Mapbox GL and Interface Builder are working great together again!

**Comment by 1ec5** [comment]
For future reference, a `git bisect` shows that the hang was caused by a625ba8a0976ef8417a2609700187c5633be2c58. It isn’t enough for the `Map` to be paused in designables; it should never ever be started in the first place. It would also be reasonable to avoid creating the `Map` in the first place, since we guard any drawing that would take place by first checking whether it’s a designable.

/cc @jfirebaugh

**Comment by jfirebaugh** [comment]
> It would also be reasonable to avoid creating the Map in the first place 

It sounds to me like this is the way to go. There's little point to creating a map that's never started or always paused.

**Comment by 1ec5** [comment]
Unfortunately it would mean a lot of null-checking of `_mbglMap` all over `MGLMapView`, compounded by the fact that the [Elvis operator](https://en.wikipedia.org/wiki/Null_coalescing_operator) is a pedantic warning that we treat as an error.

**Comment by incanus** [comment]
Sounds like we're going with this then: 

> Ship the same changes as part of b2 (0.4.0?) based on master.
