### ISSUE TITLE
How to open a Infowindow on every marker (multiple marker)?

### ISSUE THREAD

**Issue by swadallail** [mapbox/mapbox-gl-native#15696]
How to open a Infowindow on every marker At the same time (multiple marker)?
You have tried to open all infowindows, but only one infowindow opens

**Comment by tobrun** [comment]
```java
      mapboxMap.setAllowConcurrentMultipleOpenInfoWindows(true);
```

**Comment by swadallail** [comment]
I added it to me. Everything was working fine, but suddenly I didn't show the Infowindow unless I moved the map with my hand. I will quote as part of my source code.

code;-
////////////////////////////////////
 mapboxMap.setAllowConcurrentMultipleOpenInfoWindows(true);
 mapboxMap.getUiSettings().setDeselectMarkersOnTap(false);
                           currentLat =mapboxMap.getCameraPosition().target.getLatitude();
                           currentLong = mapboxMap.getCameraPosition().target.getLongitude();
                           double zz = mapboxMap.getCameraPosition().zoom;
                           zoom = (int) zz;
  getAddAllMarker();   // add all marker
//////////////////////////////////////////

I use currentLatand currentLong  and zoom  in the condition of fetching data in one of the functions

**Comment by swadallail** [comment]
I added it to me. Everything was working fine, but suddenly I didn't show the Infowindow unless I moved the map with my hand. I will quote as part of my source code.

`
[mapboxMap.setAllowConcurrentMultipleOpenInfoWindows(true);]
mapboxMap.getUiSettings().setDeselectMarkersOnTap(false);
currentLat =mapboxMap.getCameraPosition().target.getLatitude();
currentLong = mapboxMap.getCameraPosition().target.getLongitude();
double zz = mapboxMap.getCameraPosition().zoom;
zoom = (int) zz;
getAddAllMarker(); // add all marker
`
I use currentLatand currentLong and zoom in the condition of fetching data in one of the functions

This is a picture of the problem:-
![Screenshot_٢٠١٩٠٩٢٣-١٨٠٢٠٦_Agari](https://user-images.githubusercontent.com/44197219/65442847-383e1c80-de2d-11e9-8c89-e1a7cbc56f81.jpg)

**Comment by tobrun** [comment]
Could be that this API suffers from some regressions, it has been deprecated for more than a year and we do not plan to support this going forward. You can hack in workarounds as triggering a camera update that would result in an invalidation of the screen contents. Not reopening this issue as this API is deprecated.
