### ISSUE TITLE
Symbol click event isn't fired. 

### ISSUE THREAD

**Issue by sekitaka** [mapbox/mapbox-gl-native#15718]
Hello
Symbol click event is not fired when I added MapboxMap#addOnMapClickListener.

### Steps to reproduce

 1. run following code.
```
        mapView?.getMapAsync { mapboxMap ->
            this.mapboxMap = mapboxMap
            mapboxMap.setStyle(Style.MAPBOX_STREETS) {
                this.style = it

                //
                mapboxMap.addOnMapClickListener {
                    Log.d("MapboxDebug", "OnMapClick")
                    true
                }
                val symbolManager = SymbolManager(mapView, mapboxMap, style)
                symbolManager.addClickListener {
                    Log.d("MapboxDebug", "OnSymbolClick")
                }
                val iconId = "icon-id"
                val bitmap = BitmapFactory.decodeResource(resources,R.drawable.marker_restaurant)
                style.addImage(iconId, bitmap)
                val o = SymbolOptions().withIconImage(iconId).withLatLng(LatLng(0.0,0.0))
                val symbol = symbolManager.create(o)
            }
        }

```
 2. click the symbol
 3. watch the logcat

### Expected behavior
it put `OnSymbolClick` in logcat.

### Actual behavior
it put `OnMapClick` in logcat. 

### Why I create this issue
I think if the symbol was clicked `symbolManager.addClickListener` should be fired.
I think the current behavior is a bug.

### Configuration

**Android versions:** 9
**Device models:** PH-1
**Mapbox SDK versions:** 8.4.0
**annotation plugin** 0.7.0

**Comment by tobrun** [comment]
```java     
          mapboxMap.addOnMapClickListener {
                    Log.d("MapboxDebug", "OnMapClick")
                    true
                }
```


returning false in above block will fire the symbol click listener. With returning true you are indicating to the engine that the event has been handled.

**Comment by sekitaka** [comment]
@tobrun Thanks for your quick reply.
Yes, I know that.
But if I return true, both listeners are fired.
How can I handle only click symbol event?

**Comment by tobrun** [comment]
there is a feature request for that in https://github.com/mapbox/mapbox-plugins-android/issues/1051

**Comment by sekitaka** [comment]
@tobrun I got it. Thanks.

**Comment by t-hara** [comment]
I found solution for it.

It seems to depend on the calling order of `mapboxMap.addOnMapClickListener` and  `SymbolManager(...)`.

I tryied to call "SymbolManager" constructor before "mapboxMap.addOnMapClickListener (returning true value)", then only Symbol click event is fired, and map click event is not fired.
