### ISSUE TITLE
Slow MGLOfflineStorage removePack hang the map

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-native#15728]
### Steps to reproduce

 1. Load some offline packs with a total of around 500MB tiles.
 2. call MGLOfflineStorage removePack to remove a small pack of around 20MB of tiles.
 3. Zoom or pan the map to an area where there are no tiles in the cache.

### Expected behavior

The map should work right away and the delete complete after some seconds.

### Actual behavior

The map will not load new tiles until the pack remove are completed and this takes around 3 minutes on a iPhone X.

### Configuration

**Mapbox SDK versions:** 5.4.0
**iOS/macOS versions:**  13.1.1
**Device/simulator models:**
**Xcode version:** 11.1

Here is a screen shot from Profiler showing this delete going on for several minutes. Mainly working on a db exec in deleteRegion. Perhaps the VACUUM?

<img width="1280" alt="Screenshot 2019-09-29 at 00 33 55" src="https://user-images.githubusercontent.com/445229/65823254-04ab2a00-e253-11e9-804b-02b4f80e20dc.png">

**Comment by halset** [comment]
Reading up on https://www.sqlite.org/lang_vacuum.html , it says that:

> The VACUUM command works by copying the contents of the database into a temporary database file and then overwriting the original with the contents of the temporary file.

So, it probably tries to copy the ~480MB database? The change from auto_vacuum to vacuum seem to be done in bf0be56946.

**Comment by julianrex** [comment]
Hi @halset - just to confirm - when you say the this "hangs the map" you mean that new tiles aren't displaying, rather than interaction being completely blocked?

cc @tmpsantos for VACUUM discussions

**Comment by halset** [comment]
@julianrex Zooming and paning are fine and the UI responds, but new tiles are not loaded in to the map. Like if the device lost internet connection. I have not checked if cached tiles are also not loaded.

**Comment by halset** [comment]
Current workaround for me is to skip vacuum in deleteRegion. The delete is then very fast and map tile loading does not suffer. The downside is that the database then probably just grows.

**Comment by halset** [comment]
Seems like #15837 is relevant to this.
