### ISSUE TITLE
can't find libmapbox-gl.so in armeabi

### ISSUE THREAD

**Issue by linlintaotao** [mapbox/mapbox-gl-native#15726]
In our project we had already other  *.so in libs/armeabi , It works normal
but when I use mapbox , I find mapbox auto use libmapbox-gl.so in libs/arm64 ,because the device is arm64. so somthing wrong happened , I use the mapbox as directed by the official website. I don't know how to fix it

Only armeabi in my project , I think if I get libmapbox-gl.so in libs/armeabi ,this error maybe fix

![image](https://user-images.githubusercontent.com/13161389/65810018-76459280-e1d7-11e9-986d-a1b2f2de58e0.png)

**Android versions: API 28** 
**Device models: xiaomi 8** 
**Mapbox SDK versions: 8.40**

**Comment by tobrun** [comment]
@linlintaotao you could use abi filters to remove our arm64 shared object. Note that only shipping 32 bit binaries is not supported anymore since August 2019 (see [here](https://developer.android.com/distribute/best-practices/develop/64-bit)) when distributed through Google Play.

**Comment by linlintaotao** [comment]
> @linlintaotao you could use abi filters to remove our arm64 shared object. Note that only shipping 32 bit binaries is not supported anymore since August 2019 (see [here](https://developer.android.com/distribute/best-practices/develop/64-bit)) when distributed through Google Play.

thank you very much
