### ISSUE TITLE
featuresInSourceLayersWithIdentifiers returning null

### ISSUE THREAD

**Issue by neogithub** [mapbox/mapbox-gl-native#15744]
Trying to read all custom features from vector tiles regardless of rect so that I can make tableview with data. Currently using visibleFeaturesInRect (example below) but it doesn't return the entire list (outside of rect).

### Steps to reproduce

 1.  In didFinishLoadingStyle I try the following:
`MGLVectorTileSource *source = [[MGLVectorTileSource alloc] initWithIdentifier:@"myid" configurationURL:[NSURL URLWithString:@"mapbox://name.cjw80xhzm07345345435qini-2aio2"]];
[style addSource:source];
NSSet*set = [NSSet setWithObject:self.layerIdentifier]; // confirmed data layer name
NSArray<id<MGLFeature>> *arr = [source featuresInSourceLayersWithIdentifiers:set predicate:nil]; // nil returns all, right?
NSLog(@"arr: %@", arr);`

### Expected behavior
should return something like this:
arr: (
    "<MGLPointFeature: 0x600000ef3e80; identifier = \"21\", coordinate = 42.342747, -71.064911, attributes = {\n    description = Shopping;\n    name = \"Marie Galvin Fine Millinery\";\n}>",
    "<MGLPointFeature: 0x600000ef2ec0; identifier = \"73\", coordinate = 42.342511, -71.064304, attributes = {\n    description = Shopping;\n    name = \"OKW Fashion\";\n}>",
    "<MGLPointFeature: 0x600000ef2d80; identifier = \"12\", coordinate = 42.346322, -71.068904, attributes = {\n    description = Lifestyle;\n    name = \"Warren Hardware\";\n}>",
)
### Actual behavior
`arr: (
)`

### Configuration

**Mapbox SDK versions:**  5.2.0
**iOS/macOS versions:** 12/13
**Device/simulator models:** 11" Pro
**Xcode version:** 10.2

**Comment by julianrex** [comment]
@neogithub if you set the logging level to `Error`

`[MGLLoggingConfiguration sharedConfiguration].loggingLevel = MGLLoggingLevelError;`

do you see any source loading errors?

**Comment by ZiZasaurus** [comment]
Hi @julianrex, I added the following code to this [example](https://github.com/mapbox/ios-sdk-examples/blob/master/Examples/Swift/DDSCircleLayerExample.swift) and was unable to query any features using `features:InSourceLayers:WithIdentifiers`: 

```
func mapViewDidFinishLoadingMap(_ mapView: MGLMapView) {
        MGLLoggingConfiguration.shared.loggingLevel = .error
         DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) { [unowned self] in
             if let style = mapView.style, let source = style.source(withIdentifier: "composite") as? MGLVectorTileSource {
                 let features = source.features(sourceLayerIdentifiers: Set([self.layerIdentifier]), predicate: nil)
                 print("There are \(features.count) features")
                 let layerFeatures = mapView.visibleFeatures(in: self.mapView.bounds , styleLayerIdentifiers: Set([self.layerIdentifier]))
                 print("There are \(layerFeatures.count) layerFeatures")
             }
         }
     }
```

**Comment by leoyu-sh** [comment]
Has this issue been resolved yet ?  I have the same issue and I am running mapbox 6.2.1.  thanks
