### ISSUE TITLE
OpenGL rendering in background state crash on v5.3

### ISSUE THREAD

**Issue by Svantulden** [mapbox/mapbox-gl-native#15740]
In our Crashlytics tool we see a crash of our app that is related to OpenGL rendering while the app is in the background state (according to the insight Fabric offers). 

### Screenshot of stacktrace
![crash_mapbox_backgroundstate](https://user-images.githubusercontent.com/7554912/66035087-cc357580-e50a-11e9-8455-50e072e455c6.png)

### Steps to reproduce
?? This crash happens for our users and I haven't been able to accurately reproduce it yet. 

### Configuration

**Mapbox SDK versions:** v5.3 of Mapbox SDK, v0.37 of Mapbox Navigation SDK
**iOS/macOS versions:** Seems to happen on iOS 12 versions only so far (had 50 crashes for 10 unique users so not a big enough sample size to know this for sure)
**Device/simulator models:** Seems to be iPhone 6 and 6 plus so far 
**Xcode version:** XCode 11.1

**Comment by julianrex** [comment]
Thanks @Svantulden we have a couple of previous issues related to this one:

- https://github.com/mapbox/mapbox-gl-native/issues/13293 (though we'll use this issue going forward)
- https://github.com/mapbox/mapbox-gl-native/pull/14222 - WIP PR that requires a refactor due to other refactoring.

Do you host your map view in a child view controller, presentation view controller or similar?

**Comment by Svantulden** [comment]
Good to know, thanks! 

We don't use a child viewcontroller or a presentation viewcontroller. To be precise, we use a `NavigationMapView` from the `MapboxNavigation` framework and add that as a subview for our ViewController. It is just a conventional `UIViewController` that we add the  mapview to its view. 

Also good to know that we have CarPlay support in our app, so it could also be that it's presented as an inserted subview of the `rootViewController` of the `CPWindow`. We don't have enough context in the crash report if it's the CarPlay mapview or the iPhone one.

**Comment by julianrex** [comment]
@Svantulden this is fantastic feedback/info! Thank you. Can you tell if any of the crashes happened when CarPlay was active? We definitely have an specialism for Car Play, so my gut is telling me that it's probably related.

**Comment by Svantulden** [comment]
Unfortunately we don't have extra information in the crash report that could indicate a CarPlay connection. When someone with that crash contacts our support, we'll ask for a logfile so we can determine that 👍
