### ISSUE TITLE
Fix Android & iOS binary metrics scripts.

### ISSUE THREAD

**Issue by tarigo** [mapbox/mapbox-gl-native#15751]
Our release job on CI is failing on master at Record size step. Execution of script
`platform/android/scripts/metrics.sh` fails with a 502 when communicating with https://api.github.com/graphql

**Comment by julianrex** [comment]
This is also happening for iOS.

**Comment by jmkiley** [comment]
For both iOS and Android, it looks like this job is only failing when branches are merged into master. It seems to fail because this isn't returning any results:

https://github.com/mapbox/mapbox-gl-native/blob/7139abdbf546ca4010d874bfd64f72e6f2e2cdcf/scripts/check_binary_size.js#L51-L55

**Comment by julianrex** [comment]
Noting that as we fix this, we should include metadata about compiler versions and compilation flags.

**Comment by julianrex** [comment]
@tobrun is this still valid for android?

**Comment by tobrun** [comment]
@julianrex no, we have binary size tracking back up and running that confirms to the schema we use for that other maps sdk.
