### ISSUE TITLE
Use setScale instead of scaleBy

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#1576]
iOS has switched from `scaleBy` to `setScale` with pinch zooming gesture.

Should match on Android?

**Comment by 1ec5** [comment]
`scaleBy()` was working fine, but it was more convenient to use `setScale()` for #1292. Our pinch callback is called continuously during the pinch, but `UIPinchGestureRecognizer`’s `scale` property is absolute rather than being incremental.

**Comment by jfirebaugh** [comment]
Yeah, they don't necessarily have to match. Use whichever is more convenient.
