### ISSUE TITLE
locationComponent.setCameraMode not working anymore after upgrading mapbox

### ISSUE THREAD

**Issue by stoefln** [mapbox/mapbox-gl-native#15772]
We have upgraded android mapbox navigation from 0.40 to 0.41 (com.mapbox.mapboxsdk:mapbox-android-sdk:7.4.0 -> com.mapbox.mapboxsdk:mapbox-android-sdk:8.1.0) recently.

Unfortunately `locationComponent.setCameraMode` now does not show any effect anymore after the upgrade. 
Interestingly OnLocationCameraTransitionListener still completes successfully (`onLocationCameraTransitionFinished`), but the the cameraMode keeps it's default value `CameraMode.NONE`.

### Steps to reproduce

 1. Implement app with cameraMode toggle functionality
 2. Upgrade to mapbox 8.1.0
 3. `setCameraMode` stops working

### Configuration

**Android versions:** Android 8-10

**Comment by LukasPaczos** [comment]
@stoefln could you make sure that there are no developer animations invoked after the call to `setCameraMode`? I'm talking about `MapboxMap#moveCamera`, `MapboxMap#animateCamera`, etc.

Previously, those developer-invoked animations were clashing with animations managed by the `LocationComponent` and now they cancel each other out, as they should from the beginning.

**Comment by stoefln** [comment]
@LukasPaczos I am using Animators to set the mapboxMap.cameraPosition. However, I am doing this after `onLocationCameraTransitionFinished` was called.
I also wonder why setCameraMode itself would refuse setting the right value just because of some conflicting animations. Like I wrote above, the cameraMode keeps it's default value CameraMode.NONE no matter which value I set.

**Comment by LukasPaczos** [comment]
> I am using Animators to set the mapboxMap.cameraPosition. However, I am doing this after onLocationCameraTransitionFinished was called.

Does this mean that you're calling `MapboxMap#moveCamera` inside your animator callbacks? If that's the case, it's going to break the tracking because you're trying to reposition the camera while `LocationComponent` wants to do the same as it's tracking the user's position in an animated fashion.

You should be able to place a breakpoint in `OnCameraTrackingChangedListener#onCameraTrackingChanged` whenever the mode changes back to `RenderMode#NONE` and the call stack will point you to the place which interrupted the tracking animation.

**Comment by stoefln** [comment]
> > I am using Animators to set the mapboxMap.cameraPosition. However, I am doing this after onLocationCameraTransitionFinished was called.
> 
> Does this mean that you're calling `MapboxMap#moveCamera` inside your animator callbacks? If that's the case, it's going to break the tracking because you're trying to reposition the camera while `LocationComponent` wants to do the same as it's tracking the user's position in an animated fashion.

You were right, after setting the breakpoint, I can see that the animation updates are causing the cameraMode to reset. (notifyDeveloperAnimationListeners, etc...)

As I wrote, I am animating AFTER the switch to a new CameraMode (in the callback). So I don't really get where the problem is. I don't want to move the camera around, I just want to set a different tilt and zoom- this should not conflict with the camera position updates of the location component IMO.

The reason we want to animate is that we need a different camera angle and zoom for different modes (overview, 3d driving mode). 

How can this be solved with the current version of mapbox?

**Comment by LukasPaczos** [comment]
> I don't want to move the camera around, I just want to set a different tilt and zoom- this should not conflict with the camera position updates of the location component IMO.

I didn't catch that initially and I agree. We're aware of this limitation and we'll try to tackle it in the next iterations of the Camera APIs.

In the meantime, you can use [`LocationComponent#zoomWhileTracking`](https://docs.mapbox.com/android/api/map-sdk/8.4.0/com/mapbox/mapboxsdk/location/LocationComponent.html#zoomWhileTracking-double-long-com.mapbox.mapboxsdk.maps.MapboxMap.CancelableCallback-) and [`LocationComponent#tiltWhileTracking`](https://docs.mapbox.com/android/api/map-sdk/8.4.0/com/mapbox/mapboxsdk/location/LocationComponent.html#tiltWhileTracking-double-long-com.mapbox.mapboxsdk.maps.MapboxMap.CancelableCallback-) which were exposed exactly for this use-case. Please let us know if it helps and if we're good to close here.

**Comment by stoefln** [comment]
Thanks @LukasPaczos that helped! You can close this issue.

**Comment by LukasPaczos** [comment]
Thanks @stoefln!
