### ISSUE TITLE
Annotation Callouts not working iOS

### ISSUE THREAD

**Issue by xakacuk** [mapbox/mapbox-gl-native#15776]
Map annotations cannot be selected to show their callout. The original bugs reporting this last year have been marked as closed, however the issue is still not fixed as of v5.2.0.

I read issues with "annotation callouts" and did not find a solution to the problem.

Steps to reproduce
 1. i add annotations in map, mapView.addAnnotations
 2. Attempt to select annotation to show callout
 3. No callout appears, and annotationCanShowCallout is not called

Occasionally panning and zooming the map after tapping an annotation will cause annotationCanShowCallout to get called, and then the callout appears, but it is not always the case.

Expected behavior
Annotation callouts work as expected.

Actual behavior
Annotation callouts to not appear.

Configuration
Mapbox SDK versions: 5.2.0
iOS/macOS versions: 12.0
Device/simulator models: 12.0
Xcode version: 11.0

**Comment by jmkiley** [comment]
Hello,

Thank you for the report. I haven't been able to reproduce this issue with Maps SDK v5.4.0. Could you share whether you see this issue with v5.4.0? If you do continue to see the issue, could you share a minimal test case that reproduces the behavior?

**Comment by xakacuk** [comment]
yep, i updated to v5.2.0 and i have it is bug
now i updated to v5.4.0 at the moment so far so good
