### ISSUE TITLE
Use of deprecated ICU function

### ISSUE THREAD

**Issue by j-omega** [mapbox/mapbox-gl-native#15795]
https://github.com/mapbox/mapbox-gl-native/blob/1dc01f66441272402d35f0c4d52764d69a900493/platform/default/src/mbgl/i18n/number_format.cpp#L25

Per the icu source code, the `toString` function is depracated and should be replaced with `toString(UErrorCode& status)`

https://github.com/unicode-org/icu/blob/release-63-1/icu4c/source/i18n/unicode/numberformatter.h#L2449

**Comment by tmpsantos** [comment]
This was fixed actually.
