### ISSUE TITLE
Animated MGLMapView methods should accept completion handlers

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1581]
Methods like `-[MGLMapView setCenterCoordinate:animated:]` should have corresponding methods that take completion handlers (callback blocks) as parameters, like `-[MGLMapView setCenterCoordinate:animated:completionHandler:]`. Completion handlers feel much more natural in modern Objective-C and especially Swift, and they’d make it much easier to chain together animated changes to the map.

**Comment by jhoughjr** [comment]
Here here!

**Comment by kdgwill** [comment]
Was their any further discussion on this, or does their at least exist a work around to determine when an mapbox animation has been completed?

**Comment by robipresotto** [comment]
+1

**Comment by 1ec5** [comment]
GL JS can do this; so should the iOS SDK. The most straightforward way to implement it would be to have `CameraOptions` hold a C++ lambda that we can stuff the completion handler block into. Then `easeTo()` can plumb that through to the animation code’s completion code. I’m not sure what effect cancellation will have on this approach, though. For one thing, #2313 is still outstanding.

**Comment by 1ec5** [comment]
> does their at least exist a work around to determine when an mapbox animation has been completed? 

@kdgwill, `-[MGLMapViewDelegate mapView:regionDidChangeAnimated:]` is already available; it gets called for both programmatic and user-initiated region changes. It is possible to chain animations using that callback, but of course the completion handlers proposed here would be more convenient for that use case.
