### ISSUE TITLE
Clarify error messaging for requests canceled by the SDK

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#15810]
There are situations when the SDK will proactively cancel a previously-initiated request. For example, for tiles that are no longer necessary to render the map after user interaction. In those cases, the error message will not clearly indicate the root cause of the cancellation though. Instead, it'll show information about the point at which the request was cancelled ("socket closed", or SSL handshake aborted"). https://github.com/mapbox/mapbox-gl-native/issues/15341#issuecomment-522889062 tracks an instance of this type of situation.

This ticket suggests clarifying the error message to add additional context to the message, explain that the cancellation is expected, and that it was promoted by the SDK. This will help troubleshoot situations were the error could genuinely be network-related.

/cc: @tobrun

**Comment by noway** [comment]
Agree! I see a lot of "socket closed" and "cancelled"  as outlined in #15341 on Info logging level. But it gets worse, on "Debug" level I see heaps of `D/Mbgl-HttpRequest: [HTTP] Request with response = 404: Not Found`. The map is working fine (even though zooming is a bit laggy on my Android?) and from what I gather it's just "tile, that we requested earlier, is no longer visible we will cancel that" (@tobrun).

Really confusing! Also @tobrun can you confirm that `D/Mbgl-HttpRequest: [HTTP] Request with response = 404: Not Found` is to do with tile cancellation too or could that be something else?

**Comment by zugaldia** [comment]
> can you confirm that D/Mbgl-HttpRequest: [HTTP] Request with response = 404: Not Found is to do with tile cancellation too or could that be something else?

Is this happening at specific zoom levels? Which style are you using?

**Comment by noway** [comment]
It happens all the time. I'm using a custom style `'mapbox://styles/spotelf13/ck07kh7g50ds41bmzldaky8a0'`

**Comment by zugaldia** [comment]
Re-opening based on comments on https://github.com/mapbox/mapbox-gl-native-android/pull/304#issuecomment-608444758. I'd like to add additional clarity to the log message.

**Comment by zugaldia** [comment]
Thanks @Chaoba, looks great !
