### ISSUE TITLE
0m terrain lines shows up on certain zoom levels

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#1583]
![screenshot from 2015-05-18 19 41 03](https://cloud.githubusercontent.com/assets/996307/7685631/4189a90a-fd98-11e4-8517-4c132256c3bb.png)

If I keep zooming in, it eventually goes back to 950m, like it should have been in the first place.

```
$ cat /tmp/mbgl-native.cfg 
-44.6192
-19.8779
14.642
1.10056
1
```

**Comment by tmpsantos** [comment]
Could be related to #1540

**Comment by kkaefer** [comment]
This is very likely related to #1540, which is now fixed. Please reopen if you still see this issue.

**Comment by tmpsantos** [comment]
I still can see it on f11a9f8fd9f4a53195168518f6ef1efe782f1cf8

**Comment by jfirebaugh** [comment]
@tmpsantos Is this still reproducible?

**Comment by tmpsantos** [comment]
All good now.
