### ISSUE TITLE
Remove clean from ipackage and ipackage-sim make dependencies

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1584]
`clean` is supposed to be an action that you invoke manually when necessary, not something that's run every time. It's an annoyance because it causes a lengthy recompile and wipes out your Xcode project customizations such as `MAPBOX_ACCESS_TOKEN` environment variable.

**Comment by 1ec5** [comment]
@incanus, would removing the clean step from these targets have any impact on the release process we have now?

**Comment by incanus** [comment]
I am :+1: with this. IIRC @kkaefer had added this to some past iteration of packaging as a safeguard but I think we can trust Clang to update things properly for build packaging.

**Comment by kkaefer** [comment]
No, I'm pro removing clean and I don't remember adding it.
