### ISSUE TITLE
Loading local tiles via RasterSource [Android][offline]

### ISSUE THREAD

**Issue by SilvanaP** [mapbox/mapbox-gl-native#15867]
Hello, I am trying to load a set of custom tiles as an "overlay" of a mapbox map  in Android.

Therefore I created an image pyramid of my source image (which was a plain old .png) with viplibs and stored it in the assets folder of my app. I would like to add this tileset as a RasterSource via this code:

    private fun loadTiles(style: Style){
        val rasterSource = RasterSource("overlay-tiles", "asset://path/to/my/tiles")
        style.addSource(rasterSource)
    } 

I don't see anything of my custom tiles when I start the app and navigate to the map- which is no surprise, as the georeference is still missing. Is there any way to set a lat/long for the upper left and lower right corner of my image on the RasterSource? Or is this only supposed to work with georeferenced images?

**Comment by tobrun** [comment]
@SilvanaP not sure if I'm completely understanding your requirements but have you tried using the `RasterSource(String id, TileSet tileSet)`, the TileSet configuration object allows to configure a bunch more things about tileformat and how the data is structured specific to your setup.
