### ISSUE TITLE
MBXViewController in navigationcontroller stack causes back button to stop working (ios) (inconsistently reproducible).

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1586]
I don't have exact steps to reproduce this (yet). However this issues reproduces frequently enough in my repo(once or twice daily). So I am filing an issue for this. 

I've included below details regarding this:

1.) Add MBXViewController as the rootcontroller in UINavigationController stack.
2.) Push a new UIViewController on the navigation stack in response to some UIView element in MBXViewController.
3.) Press back button of the new UIViewController.  At times I've noticed that the back button stops responding. 

I added the following bits in MBXViewController to dynamically  hide/show the navigation bar. 

```
- (void)viewWillAppear:(BOOL)animated {
	[super viewWillAppear:animated];
	[self.navigationController setNavigationBarHidden:YES animated:NO];
}
- (void)viewWillDisappear:(BOOL)animated {
	[super viewWillDisappear:animated];
	[self.navigationController setNavigationBarHidden:NO animated:NO];
}

```

**Comment by friedbunny** [comment]
Does this still reproduce?
