### ISSUE TITLE
Implement 'in' expression

### ISSUE THREAD

**Issue by alexshalamov** [mapbox/mapbox-gl-native#15893]
https://github.com/mapbox/mapbox-gl-js/pull/8876

**Comment by Chaoba** [comment]
As discussed with @tmpsantos , I will try to fix this issue in Feb since gl team is lack of resources now.
cc: @chriswu42 @chloekraw

**Comment by ryanhamley** [comment]
Thanks for taking this up @Chaoba I haven't had a chance to get to it. It's not an especially complex expression and there weren't any major gotchas with it, but I'm happy to answer any questions that may come up.
