### ISSUE TITLE
Whether pbf format is supported  for android ？

### ISSUE THREAD

**Issue by zhiwo** [mapbox/mapbox-gl-native#15905]
### Steps to reproduce

 1.
 2.
 3.

### Configuration

**Android versions:** 
**Device models:** 
**Mapbox SDK versions:**

**Comment by tobrun** [comment]
Yes we use protobuf for our vector tiles

**Comment by zhiwo** [comment]
> Yes we use protobuf for our vector tiles

Thank you very much for your reply. Does the official have a Demo?

**Comment by zhiwo** [comment]
> Yes we use protobuf for our vector tiles

http://localhost:8088/geoserver/gwc/service/tms/1.0.0/myspace:mylayer@EPSG:900913@pbf/{z}/{x}/{y}.pbf http://localhost:8080/geoserver/gwc/service/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&LAYER=hmyspace: mylayer&STYLE=&TILEMATRIX=EPSG:900913:{z}&TILEMATRIXSET=EPSG:900913&FORMAT=application/x-protobuf;type=mapbox-vector&TILECOL={x}&TILEROW={y}

Is the url address using the second address?

**Comment by zhiwo** [comment]
I solved it
