### ISSUE TITLE
to get map bounds In Android mapbox

### ISSUE THREAD

**Issue by smartman21cen** [mapbox/mapbox-gl-native#15919]
I can't find getBounds function in android sdk doc and example like mapbox-gl-js map.getBounds function.
This is important method for mapbox, but why can't see it?
Please check this issue and ping me if there are this method.

Will wait good news soon from you.
Best regards.

**Comment by tobrun** [comment]
```
mapboxMap.getProjection().getVisibleRegion().latLngBounds
```
