### ISSUE TITLE
How to control telemetry/metrics opt-out.

### ISSUE THREAD

**Issue by Skoti** [mapbox/mapbox-gl-native#15910]
I would like to give a user a possibility to enable/disable Mapbox telemetry in my app other than through an info button displayed on the map.

I couldn't find anything about it in the Mapbox documentation so I've delved into the code.
I've noticed that Mapbox info action sheet uses `MGLMapboxMetricsEnabledKey` in here: https://github.com/mapbox/mapbox-gl-native/blob/5c565a5e51be8379ddc2ffb5c859d8cfebe2fcd5/platform/ios/src/MGLMapView.mm#L2479-L2526 to control this in UserDefaults. However, neither this key is publicly available nor there is any other function to control it in Mapbox iOS SDK.
How can I get a state of and enable/disable telemetry from within an app that is aligned with Mapbox internals and uses the very same source of truth?
### Configuration

**Mapbox SDK versions:** 5.5

**Comment by JustinGanzer** [comment]
Please refer to this [link](https://docs.mapbox.com/help/how-mapbox-works/attribution/#mapbox-maps-sdk-for-ios). I suspect it has all the info you seek.

In short you either control the Userdefault from within the app or give means to edit it from within the iPhone app settings.

**Comment by Skoti** [comment]
Thanks it is enough, although I was looking for a more reliable way than a hardcoded string of the same value as in Mapbox SDK. Is there any reason why this key is not publicly available?

**Comment by JustinGanzer** [comment]
@Skoti Yes and no. I believe using userdefaults makes it easy to implement it from outside the app, like the iPhone Settings > AppName > OptOut, for which they have an example up online.
No there really could be a computed property to access it easily through MapBox but its most likely a design choice as to keep more people using the telemetry data, in the end that could prove more valuable than offering tile servers as they are doing now.

**Comment by Skoti** [comment]
Thanks for explanation :)
