### ISSUE TITLE
[core] Assert check failed in TileCache::add

### ISSUE THREAD

**Issue by syershov** [mapbox/mapbox-gl-native#15926]
**Platform:** linux and macOS

**Mapbox SDK version:** checkout from master 1d49c23b8558e8c24a51e7ba84525ddd06f231be

I'm using sdk for parallel generate some thousand static map images and sometimes i have failed assert check in tiles cache.
https://github.com/mapbox/mapbox-gl-native/blob/4c1d03c257754ecc1555f3e31b3c6ccf45c4bf7b/src/mbgl/tile/tile_cache.cpp#L37

Workaround for me was correcting condition 
https://github.com/mapbox/mapbox-gl-native/blob/4c1d03c257754ecc1555f3e31b3c6ccf45c4bf7b/src/mbgl/tile/tile_cache.cpp#L24

```c++
if (!tiles.emplace(key, std::move(tile)).second) {
```

Please check this code.

**Comment by pozdnyakov** [comment]
@syershov thanks for filing this issue and for the root cause analysis! The proposed fix looks correct, would you like to make a PR or you'd like us to make it?

**Comment by syershov** [comment]
I will do it some later with tests.

**Comment by syershov** [comment]
@pozdnyakov please, can you take a look PR?

**Comment by pozdnyakov** [comment]
Fixed with https://github.com/mapbox/mapbox-gl-native/pull/15943
