### ISSUE TITLE
Symbol Layer with buffer has 'avoid-edges' behavior

### ISSUE THREAD

**Issue by riastrad** [mapbox/mapbox-gl-native#15949]
**Platform:** Node.js
**Mapbox SDK version:** v5.0.2

When a symbol layer uses `text-variable-anchor` but the underlying data has a sizeable buffer value, I would expect it to be rendered even when it crosses a tile boundary. However, when `text-variable-anchor` is render treats it as if it also had `avoid-edges=true` set (which it does not). This results in important poi icons disappearing if they cross a tile boundary.

### Steps to trigger behavior

 1. Create a style that uses `text-variable-anchor` for a symbol layer
 2. Render style in "tile" mode
 3. Note the absence of the icon & text label (compared to any other rendering mode)

### Expected behavior

When the tiles are rendered client-side:

<img width="657" alt="image" src="https://user-images.githubusercontent.com/16272584/69197643-0af5ae00-0b00-11ea-9156-eb8ec5a22071.png">

### Actual behavior

When the tiles are rendered server-side using Tile mode:
<img width="571" alt="image" src="https://user-images.githubusercontent.com/16272584/69197684-2496f580-0b00-11ea-9a17-789589584e7f.png">

cc/ @mapbox/gl-core @mapbox/static-apis

**Comment by chloekraw** [comment]
@riastrad this behavior was intentionally added in https://github.com/mapbox/mapbox-gl-native/pull/15828. Is the suggested fix to resolve this ticket to revert https://github.com/mapbox/mapbox-gl-native/pull/15828 and rely on the user to set `avoid-edges: true` in order to avoid clipped labels?

**Comment by kkaefer** [comment]
I think we only need this when placement mode is `MapMode::Tile`
/cc @ansis

**Comment by chloekraw** [comment]
Oh, I meant to link to this pr instead: https://github.com/mapbox/mapbox-gl-native/pull/15854

**Comment by riastrad** [comment]
This is no longer the case 👍
