### ISSUE TITLE
Overlapping labels

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1594]
Still seeing overlapping labels:

![image](https://cloud.githubusercontent.com/assets/52399/7708178/5502600a-fe54-11e4-96c3-bd95a9a8235f.png)

**Comment by mb12** [comment]
Can you please check if the overlapping labels are on tile boundary? Overlap detection is not done across tiles.

**Comment by kkaefer** [comment]
They are not.

**Comment by ansis** [comment]
fixed by #1666
