### ISSUE TITLE
Move addition of "events=true" parameter to FileSource implementation

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1597]
As noted in #1596 all Map Tile sources are evaluated for "events=true" query string appending.  This should be fixed at the Core GL level so that all Mapbox native GL SDKs have this checking and doesn't have to be done at the native GL SDK level.  This will be a larger fix than #1596 so it'll likely come after #1596 is done in Beta 2.

@mapbox/mobile @mapbox/mobiledata @jfirebaugh @kkaefer

**Comment by jfirebaugh** [comment]
#1607 is the first step here.
