### ISSUE TITLE
Announcement: Mobile platform SDKs moved to standalone repos

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-native#15971]
<p align=center>
<img src="https://media.giphy.com/media/3oEdv5TKRImTqq6waA/giphy.gif">
</p>

**After 5+ years, 700+ releases, and 8,000+ issues, [`mapbox-gl-native` as a monorepo](https://blog.mapbox.com/powering-maps-across-all-platforms-with-mapbox-gl-942aad1496a4) has come to an end.** We’re extracting the mobile platform code into two new repos: [`mapbox-gl-native-android`](https://github.com/mapbox/mapbox-gl-native-android) and [`mapbox-gl-native-ios`](https://github.com/mapbox/mapbox-gl-native-ios). All subsequent releases of the Mapbox Maps SDKs for iOS and Android will be published from those repositories, and `mapbox-gl-native` will become exclusively a C++ map rendering library that powers both mobile SDKs.

When we [began](https://blog.mapbox.com/introducing-mapbox-gl-7a1f4e960e16) the Maps SDK initiative on GL-Native, we were a small team of developers, working quickly to bring dynamic vector maps to multiple platforms. Working in a single repository allowed us to stay in sync as we rapidly innovated and developed a wide range of features. Now that we’ve grown to 20+ developers across 3 teams, and the Maps SDK has enjoyed broad adoption, the monorepo has become more of a liability than an advantage.

By splitting the code in `mapbox-gl-native` into three repositories, we will unlock the ability to:

- Control when the mobile SDKs absorb upstream changes in `mapbox-gl-native`, particularly breaking changes.
- Publish stable releases of C++ code in `mapbox-gl-native`, improving the stability of our product.
- Streamline continuous integration to only run tests needed for each repository, accelerating day-to-day development.
- Enable mobile developers to contribute more easily to the Maps SDK, as `mapbox-gl-native-android` and `mapbox-gl-native-ios` are now pure mobile projects.
- Classify community feedback within each repo for simplified tracking. You no longer need to navigate a maze of ticket templates and labels.

We’re excited to bring you a more stable, more robust, and easier to use Maps SDK. Nothing changes in terms of how you consume new releases on distribution platforms such as Maven, Cocoapods, and Carthage; the changes are in how you interact with us on GitHub.

As always, feel free to share your thoughts on this ticket!

**Comment by 1ec5** [comment]
What’s old is new again: mapbox/mapbox-gl-cocoa#83. 🎉
