### ISSUE TITLE
Migrate android-benchmark-arm-v8 to next buildsystem

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#15977]
The final remaining blocker to finish up the removal of android platform code from this repository (see https://github.com/mapbox/mapbox-gl-native/pull/15970) is the reintroduction of `make android-benchmark-arm-v8` into the next build system for metric purposes. 

@tmpsantos can this be prioritized, this is the only remaining blocker to finish up the code removal.

cc @alexshalamov

**Comment by tmpsantos** [comment]
Let's not be blocked by this, we are landing other metrics with much bigger code coverage and we can bring this one back later.

**Comment by tobrun** [comment]
Sounds good!

**Comment by tmpsantos** [comment]
@jmalanen is investigating this one
