### ISSUE TITLE
Adding a Map Style above the current Map Style

### ISSUE THREAD

**Issue by DenWhiteHouse** [mapbox/mapbox-gl-native#15983]
Hello everyone, as from version 7.x of MapBox the map Style is an object, I just want to ask if is possible to put a whole style above another style.

Say it not possible, there is a way to use the Style.Builder and load a style itself from a URI without invoking set style from map box to put the layers of Style A on the current map Style B?

**Comment by LukasPaczos** [comment]
Hey @DenWhiteHouse, unfortunately, this is not possible. What you could do instead is to analyze a style as a typical JSON file, edit it and merge the layers or pre-build the style you need in Mapbox Studio.
