### ISSUE TITLE
raster seams

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1600]
Raster layers have seams on linux. For example, look at the headless tests for raster (it helps if you disable linear interpolation by changing `true` to `false` [here](https://github.com/mapbox/mapbox-gl-native/blob/f89f7f1bc27e36467bab247f40bb823a3b7b178c/src/mbgl/renderer/raster_bucket.cpp#L35-35).

Expected:
![image](https://cloud.githubusercontent.com/assets/98601/7713207/11d34976-fe2b-11e4-80b4-c46915a885f3.png)

Actual:
![image](https://cloud.githubusercontent.com/assets/98601/7713209/189d2344-fe2b-11e4-96ed-010a6171fa22.png)

If you zoom in, you can see that one of the rows of pixels is repeated. In this case, it's the bottom row in the upper tile:

![image](https://cloud.githubusercontent.com/assets/98601/7713222/2c878854-fe2b-11e4-909d-384491885f58.png)

**Comment by jfirebaugh** [comment]
You can see the effect clearly in the [`raster-exact-zoom` branch](https://github.com/mapbox/mapbox-gl-native/compare/raster-exact-zoom). [Test results here](http://mapbox.s3.amazonaws.com/mapbox-gl-native/tests/4326.1/index.html).

![image](https://cloud.githubusercontent.com/assets/98601/7716608/5ad5e980-fe49-11e4-8b23-2a0ad66cad63.png)

**Comment by kkaefer** [comment]
Maybe this is because we use `4096` as tile border and stencil buffer rather than `4095`?

**Comment by jfirebaugh** [comment]
Should it be `4095`? Is this a pixel value (so that 4095 means the top left of the 4096th pixel) or an outer, bottom/right-side bound?

**Comment by jfirebaugh** [comment]
Also happens in js.

**Comment by jfirebaugh** [comment]
No longer happening in js since the switch to headless-gl 2.0. Still happens in native.

**Comment by brunoabinader** [comment]
Fixed in #6899.
