### ISSUE TITLE
Load map take too long time

### ISSUE THREAD

**Issue by AliKhoshraftar** [mapbox/mapbox-gl-native#16007]
We are building our own sdk from mapbox-fl-native for android. so after getting project and do our changes we upload it using bintrayUpload that exists in project with our bintray configuration and every thing is fine except that loading our style take more time that mapbox official sdk.
We have checked our style in changed sdk and also in official sdk and we have seen that load our style take 5 to 8 time more that official sdk.
I don't know why this happens because we don't change anything related to style and core native codes. we just add our headers in HttpRequestImpl , Change mapbox logo to our logo , and remove mapbox styles and add our style to Style class.
Load style from gl-native project is faster also but after publish it in bintray it takes too much time to show map.
Getting style and requests results are also fast and just showing it is slow.

**Platform:** Android
**Mapbox SDK version:** 8.4.0

### Steps to trigger behavior

 1.Clone Mapbox-gl-native and done our changes
 2.Publish to bintray
 3.Implement in new test app

### Expected behavior

Load map fast just same as official mapbox sdk.
### Actual behavior

Load map is very slow

**Comment by tobrun** [comment]
@AliKhoshraftar I appreciate your honesty, but I'm unable to provide support for your use-case if your not a Mapbox customer.
