### ISSUE TITLE
port stretchable icons from -js

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#16017]
I'm opening this issue so that render test ignores can point to something.

prs:
https://github.com/mapbox/mapbox-gl-js/pull/8997
https://github.com/mapbox/mapbox-gl-js/pull/9041
https://github.com/mapbox/mapbox-gl-js/pull/9045

<img width="765" alt="Screen Shot 2019-12-05 at 6 41 25 PM" src="https://user-images.githubusercontent.com/1421652/70331341-45a05b80-180d-11ea-8f04-c6bd0a0f6ade.png">

**Comment by LukasPaczos** [comment]
/cc @mapbox/navigation-android @mapbox/navigation-ios @andrewychen 

A very cool new feature that could enhance route/destination callouts.

**Comment by 1ec5** [comment]
This feature has landed in iOS map SDK v5.8.0. It only works via runtime styling because the server-side changes haven’t landed yet.
