### ISSUE TITLE
[question] Transparent street

### ISSUE THREAD

**Issue by limingchina** [mapbox/mapbox-gl-native#16015]
I've tried transparent street network on both Mapbox studio(using Mapbox javascript) and glfw example app from mapbox gl native. When I set the opacity of the street to less than 1, i.e., I'd like to have a transparent street network, the rendering at the joints have accumulated transparency. See the attached screenshots. The first one is from Mapbox studio and the second one is from the glfw example app with a modified style file, which sets the "road-primary" to a different color and an opacity of 0.5.
<img width="717" alt="Transparent Streets in Mapbox Studio" src="https://user-images.githubusercontent.com/23010280/70267339-8319d000-179e-11ea-85d0-2e903edca2dd.png">

<img width="639" alt="Transparent Streets in GLFW example" src="https://user-images.githubusercontent.com/23010280/70267780-6af68080-179f-11ea-9ed3-e03964ff9316.png">

I would expect this is known issue. However, I can't find it in the existing issues. Can the Mapbox team confirm it's a known issue?

**Comment by chloekraw** [comment]
@limingchina this is a known limitation. See https://github.com/mapbox/mapbox-gl-js/issues/6540 and https://github.com/mapbox/mapbox-gl-js/issues/4090.
