### ISSUE TITLE
Change MAPBOX_ACCESS_TOKEN to MapboxAccessToken

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1604]
We have standardized on `MapboxAccessToken` in all other repositories, so we should switch here as well.

**Comment by tmpsantos** [comment]
oh, is that the env var? Can we keep MAPBOX_ACCESS_TOKEN at least for Linux (otherwise will be the first env var camelCase on my environment, Linux users won't feel at home).

**Comment by tmpsantos** [comment]
keep == we could parse MapboxAccessToken fallbacking to MAPBOX_ACCESS_TOKEN on Linux.

**Comment by 1ec5** [comment]
MAPBOX_ACCESS_TOKEN is more appropriate on OS X as well, owing to its Unix origins.

**Comment by 1ec5** [comment]
Note that the environment variable is merely a convenience for running the demo app. With #1553, we'll also look for `MGLMapboxAccessToken` in a configuration file, per platform naming convention.

**Comment by jfirebaugh** [comment]
> We have standardized on `MapboxAccessToken` in all other repositories

This has actually stalled out; will reopen if it moves again.

**Comment by 1ec5** [comment]
In #4696, I've proposed adding a prompt for the access token, which would be persisted across sessions. That way, you won't have to quit and rerun in the event that you forgot to set an access token.

Also, note that iosapp conventionally uses MBX as its class prefix. Cocoa convention is to use a class prefix in user defaults, environment variables, notification names, and so forth. Not that it would matter so much once we implement #4696.

**Comment by kkaefer** [comment]
`MAPBOX_ACCESS_TOKEN` is only used in our debug application and is not part of the SDK.

**Comment by 1ec5** [comment]
Understood. #4696 is all about iosapp. The automation described in that issue would be useful for Bench GL, which is supposed to run without user intervention.

**Comment by kkaefer** [comment]
Bench GL is also supposed to run without any access to the internet whatsoever; it's currently loading all assets from the app bundle.

**Comment by 1ec5** [comment]
I need to look into this again; the bundling of assets may've fallen out with #4641.

**Comment by 1ec5** [comment]
ios-bench asset bundling fixed in #4740.
