### ISSUE TITLE
iOS: Please add MGLUserTrackingModeFollowWithCourse

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#1605]
It looks like the follow user with heading is off by about 5 to 10 degrees. In this case the user was driving down W Olympic Blvd, but map orientation was quite a bit off. Maybe magnetic heading is being used instead?

**Comment by picciano** [comment]
Just to clarify this a bit...it seems to be orienting to the orientation of the phone, not the direction of travel. This seems very odd when you use it.

**Comment by picciano** [comment]
Sorry to keep going on and on, but it looks like this is the difference between using the `newHeading` from `didUpdateHeading:` and `newLocation.course` from the `didUpdateToLocation:` delegate methods of CLLocationManager.

For navigation apps, the `course` is what is needed. Maybe another user tracking mode is needed?
MGLUserTrackingModeFollowWithCourse

**Comment by picciano** [comment]
We have hacked in a FollowUserWithCourse option. But really look forward to a proper solution with smooth animation and all that jazz!

![ios simulator screen shot jun 23 2015 3 51 25 pm](https://cloud.githubusercontent.com/assets/417933/8318384/2f33c048-19c1-11e5-840a-e47bb5804c60.png)

**Comment by 1ec5** [comment]
Smooth animation is covered by #1582.

**Comment by picciano** [comment]
Thanks, but I did want to differentiate between "follow user with heading" which is the magnetic direction, and "follow user with course" which is their direction of travel. Navigation apps will need follow with course.

**Comment by 1ec5** [comment]
Understood, I left this issue open to track that request.
