### ISSUE TITLE
GeoJSONSource crash when iOS Maps SDK targets release-tequila

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-gl-native#16053]
### Steps to reproduce

 1. [Checkout this branch](https://github.com/mapbox/mapbox-gl-native-ios/pull/100) (which contains a `mapbox-gl-native` submodule pointing at `release`tequila`).
 2. Run the `iosapp` target to launch debug app.
 3. Observe crash.

### Expected behavior
Demo app should boot up and not crash.

### Actual behavior

💥 

The calling stack looks like this:

<img width="478" alt="Screenshot 2019-12-12 14 31 08" src="https://user-images.githubusercontent.com/10850812/70756024-4b57de80-1cf0-11ea-9e64-7fc33a49bd6d.png">

Where the issue seems to be coming from `GeoJSONSource` in geojson_source.hpp. Looking at the diff between whats on `master` vs `release-tequila`, I noticed [this change](https://github.com/mapbox/mapbox-gl-native/pull/15992) happened about 13 days ago, and I wonder if it has anything to do with this present crash.

cc @chloekraw @zugaldia 

### Configuration

**Mapbox SDK versions:** 5.6.0-beta.1 (in progress)
**iOS/macOS versions:** macOS 10.15.2
**Device/simulator models:** iPhone 11 Pro (physical device)
**Xcode version:** 11.3 (11C29)

**Comment by springmeyer** [comment]
fix in progress at https://github.com/mapbox/mapbox-gl-native-ios/pull/102

**Comment by chloekraw** [comment]
fixed!
