### ISSUE TITLE
How loading custom image for markers in clustering data

### ISSUE THREAD

**Issue by saptan** [mapbox/mapbox-gl-native#16060]
Hello, dear developers. I'm doing data clustering for example SymbolLayer clustering (https://docs.mapbox.com/android/maps/examples/symbol-layer-clustering/). Everything works well, but I need to make sure that each marker on the map displays its picture which is loaded on the url. Unfortunately I can not find information how to do it. Please tell me in which direction I need to move?

**Platform: Android **
**Mapbox SDK version: 8.5.0**

**Comment by alexshalamov** [comment]
@saptan Hi, you could try combining symbol clustering with https://docs.mapbox.com/android/maps/examples/missing-icon/ example to add custom icons loaded from URL.

Also, check advanced clustering options: https://github.com/mapbox/mapbox-gl-native-android/blob/master/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonOptions.java#L117 not sure if there are examples for that feature.

**Comment by saptan** [comment]
@alexshalamov Thanks, it really works as I need it

> https://docs.mapbox.com/android/maps/examples/missing-icon/
