### ISSUE TITLE
Plans to expose OSM points of interest?

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#1606]
Are there any plans to expose the points of interest from OSM, either as annotations of somehow query the map? I know we can add our own annotations, but since they are already being drawn, the data has to be in there somewhere.

![ios simulator screen shot may 20 2015 9 39 02 am](https://cloud.githubusercontent.com/assets/417933/7729892/6e086f88-fed4-11e4-968b-5100c7039ec3.png)

**Comment by incanus** [comment]
Yep: https://github.com/mapbox/mapbox-gl-native/issues/352
