### ISSUE TITLE
iconAllowsOverlap is effective across different layers

### ISSUE THREAD

**Issue by pushian** [mapbox/mapbox-gl-native#16078]
### Steps to reproduce
 1.  add two layers of icons on the map
 2. set both layers to iconAllowsOverlap = false

### Expected behavior
For the older versions, the overlap control is only happening in the same layers. For two icons from different layers, even they collide with each other, they will still be visible

### Actual behavior
In the current version, if two icons from different layers collide with each other, one of them will be invisible

### Configuration

**Mapbox SDK versions: V5.4.0

**Comment by DonfexCui** [comment]
I have the same problem, did you solve it?

**Comment by pushian** [comment]
> I have the same problem, did you solve it?

**Comment by pushian** [comment]
> I have the same problem, did you solve it?

Haven't. I think it is a system update which cannot be handled by us. Hope mapbox team can look into this issue and reconsider.

**Comment by DonfexCui** [comment]
@pushian I found this: https://github.com/mapbox/mapbox-gl-native/pull/12941/files.
It solved my problem, hope it will be useful to you.

**Comment by tobrun** [comment]
that is indeed the correct config! @DonfexCui

**Comment by pushian** [comment]
> that is indeed the correct config! @DonfexCui

@tobrun Hi Tobrun, with the current config, I find myself in a dilemma that if I allow the overlap, there will be too many icons displaying on the map but if I don't allow the overlap, the icons are too few on the map. And if I have two layers of icons, the first layer is attractions, the second layer is restaurants, when the zoom level is low, I will only be able to see the attraction icons since all the restaurant icons have been hidden for their overlapping with the attraction icons. I have attached the screenshots of the older version and the current version. To me, the older version seems more reasonable to allow the overlapping for icons from different layers.
![Group 3](https://user-images.githubusercontent.com/16488850/74520202-0c454400-4f52-11ea-9eed-cb4076d71661.png)
