### ISSUE TITLE
How get all points in cluster?

### ISSUE THREAD

**Issue by saptan** [mapbox/mapbox-gl-native#16072]
Hello, dear developers. I'm doing data clustering for example SymbolLayer clustering (https://docs.mapbox.com/android/maps/examples/symbol-layer-clustering/). Please tell me how I can get all the points that are inside the cluster after clicking on the cluster.

**Platform: Android **
**Mapbox SDK version: 8.5.0**

**Comment by tobrun** [comment]
GeoJsonSource#getClusterChildren

example [here](https://github.com/mapbox/mapbox-gl-native-android/blob/master/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/GeoJsonClusteringActivity.java#L132)
