### ISSUE TITLE
[IOS] adds text labels separately

### ISSUE THREAD

**Issue by songyuyang0918** [mapbox/mapbox-gl-native#16070]
I have a point coordinate and I match a text,
How do I load it separately on the map?
It's not a geojson format, and I don't think I can use the MGLSymbolStyleLayer.
I have a lot of this data, how do I load it separately?

**Comment by chloekraw** [comment]
What format is your data in? Why don't you think that you can use MGLSymbolStyleLayer?

**Comment by songyuyang0918** [comment]
My raw data is just two parameters in the array, latitude and longitude, and label text.
This data format is not geojson, so the corresponding MGLSource cannot be generated.
So I thought it would be nice to have a tag class where you can set latitude and longitude and tag text to generate objects.
