### ISSUE TITLE
Consistent crash during app launch

### ISSUE THREAD

**Issue by kohlab** [mapbox/mapbox-gl-native#16084]
Our iOS app now crashes each time it is launched, even after a clean build and resetting the simulator.  

### Steps to reproduce

 1. Clean build folder in Xcode
 2. Build
 3. Run

### Expected behavior

We expect app to launch without complaint, as before.

### Actual behavior

Instead we get this stack trace:

    2019-12-28 06:31:18.155853-0800 MyApp[51591:2158265] +[NSUserDefaults mme_configuration]: unrecognized selector sent to class 0x1089cecc0
    2019-12-28 06:31:18.165360-0800 MyApp[51591:2158265] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSUserDefaults mme_configuration]: unrecognized selector sent to class 0x1089cecc0'
    *** First throw call stack:
    (
    	0   CoreFoundation                      0x00000001087081e6 __exceptionPreprocess + 294
    	1   libobjc.A.dylib                     0x0000000107954031 objc_exception_throw + 48
    	2   CoreFoundation                      0x00000001087896c4 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
    	3   CoreFoundation                      0x000000010868a898 ___forwarding___ + 1432
    	4   CoreFoundation                      0x000000010868a278 _CF_forwarding_prep_0 + 120
    	5   Mapbox                              0x000000010c232802 -[MGLMapboxEvents init] + 262
    	6   Mapbox                              0x000000010c233a9a __33+[MGLMapboxEvents sharedInstance]_block_invoke + 38
    	7   libdispatch.dylib                   0x000000010f94d7ec _dispatch_client_callout + 8
    	8   libdispatch.dylib                   0x000000010f94ed64 dispatch_once_f + 285
    	9   Mapbox                              0x000000010c2332ee +[MGLMapboxEvents sharedInstance] + 97
    	10  Mapbox                              0x000000010c23332c +[MGLMapboxEvents setupWithAccessToken:] + 60
    	11  libdispatch.dylib                   0x000000010f94c7ab _dispatch_call_block_and_release + 12
    	12  libdispatch.dylib                   0x000000010f94d7ec _dispatch_client_callout + 8
    	13  libdispatch.dylib                   0x000000010f9588cf _dispatch_main_queue_callback_4CF + 628
    	14  CoreFoundation                      0x00000001086cac99 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
    	15  CoreFoundation                      0x000000010868eea6 __CFRunLoopRun + 2342
    	16  CoreFoundation                      0x000000010868e30b CFRunLoopRunSpecific + 635
    	17  GraphicsServices                    0x0000000111e67a73 GSEventRunModal + 62
    	18  UIKit                               0x00000001097c0057 UIApplicationMain + 159
    	19  MyApp                               0x000000010697a4eb main + 75
    	20  libdyld.dylib                       0x000000010f9ca955 start + 1
    )
    libc++abi.dylib: terminating with uncaught exception of type NSException

### Configuration

**Mapbox SDK versions:** 

These are the versions we have set up in our Cartfile (the latest, we think):

github "mapbox/MapboxDirections.swift" ~> 0.30
github "mapbox/MapboxGeocoder.swift" ~> 0.12
github "mapbox/mapbox-navigation-ios" ~> 0.38.1
binary "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json" ~> 5.4

**iOS/macOS versions:** 
**Device/simulator models:**

Deploying on iOS 11.4 in iPhone SE Simulator.

**Xcode version:** 

Xcode version 11.3 (11C29)

**Comment by kohlab** [comment]
Oops, I believe I misfiled this here. I've refiled it in the iOS repository here: https://github.com/mapbox/mapbox-gl-native-ios/issues/121

Feel free to close this if it's indeed in the wrong place.

**Comment by julianrex** [comment]
Closing here.
