### ISSUE TITLE
how to Import Mapboxsdk  as modulei and custom style files and vectors

### ISSUE THREAD

**Issue by karanveer0802** [mapbox/mapbox-gl-native#16098]
**Platform:**
**Mapbox SDK version:**

### Steps to trigger behavior

 1.Import mapboxsdk and mapboxsdklint in android project .
 2.Declare the project in Created project gradle file .
 3.Create a class with a mapview in xml file and import all the mapboxfiles such as com.mapbox.mapboxsdk.maps.MapView and com.mapbox.mapboxsdk.maps.Camerafactory.
4.Project can be run and files are editable in it 

### Expected behavior
1.After app is run map should be inflated and can custom sTyle file and replace it on runtime
### Actual behavior
1.App crashes after token is set and view is inflated it shows following error:-
 👎 Error inflating class com.example.mapboxsdk.maps.widgets.CompassView
:-java.lang.ClassNotFoundException: com.example.mapboxsdk.maps.widgets.CompassView
:-android.view.InflateException: Error inflating class com.mapbox.mapboxsdk.maps

**Comment by tobrun** [comment]
@karanveer0802 Thank you for reaching out and using our product! We sadly do not give support for building from source as that is opening up a can worms. Please use our maven published binaries instead, see our [install](https://docs.mapbox.com/android/maps/overview/#install-the-maps-sdk) instructions.

**Comment by karanveer0802** [comment]
So how can i replace style files with another style url which are not generated from mapbox account ?

**Comment by tobrun** [comment]
Something as: (have double checked the actual code so might contain a typo)

`mapboxMap.setStyle(new Style.Builder().fromUrl("....")`

or

`mapboxMap.setStyle(new Style.Builder().fromJson("..")`
