### ISSUE TITLE
Annotations don't update on map if they are updated in ContentView.swift

### ISSUE THREAD

**Issue by CodyPChristian** [mapbox/mapbox-gl-native#16095]
Original post: https://github.com/mapbox/mapbox-maps-swiftui-demo/issues/3
I'm also having these issues as well as others in that thread.
From tutorial: https://docs.mapbox.com/help/tutorials/ios-swiftui/
Latest iOS (13) and Latest SDK (5.6.0)

**Comment by fabian-guerra** [comment]
Hi, @CodyPChristian. Thank you for using Mapbox. The issues reported in this repo should be for the Mapbox Maps SDK for iOS. The swift ui tutorial is not related to this repo.

**Comment by CodyPChristian** [comment]
@fabian-guerra  thanks for your reply, where should this be reported as the bug seems to be with the mapbox maps SDK itself.

**Comment by fabian-guerra** [comment]
For future reference this is not a Mapbox bug and this comment explains why: https://github.com/mapbox/mapbox-maps-swiftui-demo/issues/3#issuecomment-572111228
