### ISSUE TITLE
Imporing showing Errors.

### ISSUE THREAD

**Issue by Avishak-2017831010** [mapbox/mapbox-gl-native#16102]
import com.mapbox.mapboxandroiddemo.R;

this is not importing and showing 
error: package com.mapbox.mapboxandroiddemo does not exist
instead.

**Comment by tobrun** [comment]
@Avishak-2017831010 thank you for reaching out, the R class linked is related to the mapbox-android-demo project and not mapbox-gl-native. That said, this is not a bug, you need to rebuild the project to generate the R class. Stackoveflow will be a good website for starting to resolve your issue.

**Comment by Johneill** [comment]
Hi there

I tried to rebuild the app but this didn't seem to fix the error?
Is there any sort of tutorial I could follow to help get this working?

Many Thanks
