### ISSUE TITLE
Investigate possibility of using inlined vectors

### ISSUE THREAD

**Issue by alexshalamov** [mapbox/mapbox-gl-native#16118]
The issue was raised in https://github.com/mapbox/mapbox-gl-native/pull/16030#issuecomment-571138465.

Preliminary profiling (running 1024-symbol render test) shows heap peak increase from `master branch: 28.90 MB` to `stretchable-icons: 29.30 MB`, however, memory usage goes back to original level when temporary heap allocated vectors are destructed.

We should investigate where small vectors are used and possibility of inlining those. Few known places in a codebase: `ImageStretches` in Image, `Cuts` in quads creation, `StyledText` in BiDi.

**Comment by pozdnyakov** [comment]
std::array could be used as an inline vector, we could introduce a helper class that would wrap both `std::array` and `std::vector` (as a fallback when when the amount of items exceeds the `std::array` size)
