### ISSUE TITLE
Ability to align UX of tile loading with gl-js

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#16122]
GL-native implementation attempts to show geometry from lower zoom levels when panning/zooming out a map and not having those tiles available yet. Imo, this is the best possible UX that we could give to our end users and this should remain our default implementation. 

A customer however is reaching out to make this behavior configurable to match gl-js implementation. With gl-js, you pan/zoom and see the background of the style until the tiles are loaded. 

Sidenote: using `setPrefetchZoomDelta` doesn't result in the expected behavior. 

cc @tmpsantos @malwoodsantoro

**Comment by tmpsantos** [comment]
> Sidenote: using `setPrefetchZoomDelta` doesn't result in the expected behavior.

This is because in this case, we are trying to find this tile from the cache going up in the tile pyramid.
