### ISSUE TITLE
overzooming work wrong when the data is island

### ISSUE THREAD

**Issue by barrycug** [mapbox/mapbox-gl-native#1612]
the data zoom level is 0-9;
when I zoom to level 10, the island will be render failed.
like the attachment.first attachment  at zoom level 9 ,It is ok,but  I double click to zoom in .It‘s wrong,see the second attachment.
the map's background color is blue.
![ios simulator screen shot may 21 2015 4 05 44 pm](https://cloud.githubusercontent.com/assets/1191156/7744215/022a44c0-ffd4-11e4-92b5-b5f9d0d3dcc2.png)
![ios simulator screen shot may 21 2015 4 05 53 pm](https://cloud.githubusercontent.com/assets/1191156/7744227/12861506-ffd4-11e4-8cbe-8cab1694b7a0.png)

**Comment by kkaefer** [comment]
Are you seeing this behavior with tiles loaded from mapbox.com or with custom tiles? If it is the latter, this is probably not an issue with Mapbox GL but with your vector tiles.

**Comment by mb12** [comment]
@kkaefer  Is it possible to make the winding order in tesselation step configurable via a style.json to troubleshoot such issues? The winding order used to be in FillProperties at some point before it was deleted as an unused data member.

@barrycug  This *might* be polygon vertex winding order issue in your Source. For Polygons with holes (as is the case here), winding order is used to determine what is inside/outside the polygon.  

Here are a couple of things you can try to troubleshoot this.

1.) gl-native assumes TESS_WINDING_POSITIVE. In your repo you can try changing the winding order to  one other than the one that it uses. Change the second argument of call to tessTesselate to one of the following enums. 

https://github.com/memononen/libtess2/blob/a43504d78a5695ca07cf3706e34abfdfd5b4343b/Include/tesselator.h

2.) If you are using post gres, try changing the coordinate system to a non-default one using st_forcerhr in your sql.

**Comment by barrycug** [comment]
ok,I use the custom vector tiles. thank you. @kkaefer @mb12

**Comment by barrycug** [comment]
I try to change  the second argument to every enums. It  have the same problem.
I use the osm data (shapefile,downloaded from download.geofabrik.de) to generate vector tiles.
the vector tiles is exported by Mapbox studio2.7.

**Comment by springmeyer** [comment]
@barrycug - can you try using mapbox-studio from github (latest mb-pages) branch and see if that improves the rendering?

**Comment by barrycug** [comment]
@springmeyer  another similar issue,If the data maxlevel=16 ,I zoom in to level17 ,It's ok.at the moment.I pan the map at level 17, when the extent out of the current tile's parent'stile. the map will only display the map's background. the map don't load the tile's parent's tile(if the tile has not loaded);

![img_0044](https://cloud.githubusercontent.com/assets/1191156/7763612/413daaf6-0076-11e5-9652-bb73c7574d54.PNG)

**Comment by jfirebaugh** [comment]
@barrycug Are you still seeing this issue?

**Comment by tmcw** [comment]
Stale issue - would need confirmation on the current version.
