### ISSUE TITLE
[ios] Replace CI build job to build mapbox-gl-native-ios

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#16124]
Add iOS equivalent of https://github.com/mapbox/mapbox-gl-native/pull/16024

**Comment by 1ec5** [comment]
How would the dependency management work? If I push a PR that makes a backwards-incompatible change and simultaneously push a PR in mapbox-gl-native-ios that addresses the incompatibility, I can have the mapbox-gl-native-ios branch’s submodule point to the mapbox-gl-native branch. But how would I tell the mapbox-gl-native branch’s CI bots to check out a specific branch of mapbox-gl-native-ios?
