### ISSUE TITLE
offlinePack: even without an Internet connection, offlinePacks are created in the database

### ISSUE THREAD

**Issue by alextorn** [mapbox/mapbox-gl-native#16144]
### Steps to reproduce

 1. Start creating 3000 (for example) offline packs.
 2. Turn off the internet before completion, and wait for completion :)
 3. Check and count the number of created offline packs in database by getPacks(). The number is 3000.

### Expected behavior

How to make sure which packs from 3000 packs are downloaded correctly?
Why even without an Internet connection, offlinePacks are created in the database?

### Actual behavior

I see 3000 offlinePacks in SQL database. 

### Configuration

**Mapbox SDK versions:*iOS SDK 5.3.2* 
**Device/simulator models:*ios simulator*

**Comment by julianrex** [comment]
@tmpsantos is this expected behavior for GL?

**Comment by alextorn** [comment]
Looks like Mapbox creates empty packs with state 0 in status. So need to think that it is expected behavior.

**Comment by chloekraw** [comment]
@alextorn what behavior are you expecting when you invalidate an offline pack?
