### ISSUE TITLE
The Mapbox JSON is currently invalid

### ISSUE THREAD

**Issue by stefantspike** [mapbox/mapbox-gl-native#16206]
### Steps to reproduce

 1. Run `carthage update` command in the terminal.

### Expected behavior
Carthage builds frameworks normally.

### Actual behavior
Error is thrown - 

> Unable to parse binary-only framework JSON at https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json due to error: invalid JSON: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Badly formed object around character 22379." UserInfo={NSDebugDescription=Badly formed object around character 22379.})))

I can see there is an invalid ` character at the end of the JSON.

### Configuration

**Mapbox SDK versions:**  5.6
**iOS/macOS versions:** iOS 13.0
**Device/simulator models:** Any
**Xcode version:**  11.3

**Comment by captainbarbosa** [comment]
Hi @stefantspike, we're aware of this issue in https://github.com/mapbox/mapbox-gl-native-ios/issues/166 and it has been since resolved.
