### ISSUE TITLE
Show image when map cannot load

### ISSUE THREAD

**Issue by vasquezdennisalon** [mapbox/mapbox-gl-native#16203]
I am trying to show an image when the map cannot be loaded, then reviewing the documentation they provide from the library, the mapViewDidFailLoadingMap method returns the connection error but does not always return it to me, that is, if I am connected to the internet, the region loads me of the map at that time but if I keep moving on the map without a network connection the map cannot load the following regions then there I would like to show an image that the map could not be loaded but the mapViewDidFailLoadingMap function does not respond to me.
How could I solve that?

### Configuration

**iOS/macOS versions:**

**Comment by 1ec5** [comment]
#119 tracks showing something other than a transparent background or the `background` layer when a particular tile hasn’t loaded.
