### ISSUE TITLE
Access token is cached

### ISSUE THREAD

**Issue by johankool** [mapbox/mapbox-gl-native#1621]
It seems that the access token is cached between launches. If it is revoked, or is changed, the previous keeps being used. This is a problem because if an app update changes the access token, and the previous token gets revoked, the only way for users to get their map working again is a fresh install.

**Comment by johankool** [comment]
This is on iOS btw with the 0.3.1 release.

**Comment by 1ec5** [comment]
Did you check out this repo and build the demo app from source? The demo app works quite differently than would a project that pulls in MapboxGL.framework via CocoaPods. In the demo app, the access token is indeed persisted in a user default. But if you set a new access token via the `MAPBOX_ACCESS_TOKEN` environment variable, the demo app should pick that up automatically.

**Comment by johankool** [comment]
No, not the demo app. I've included the libMapboxGL.a manually from the precompiled binary (version 0.3.1) into my app. I am setting the access token via an instance of `MGLMapView`.

**Comment by jfirebaugh** [comment]
AFAIK the library itself does not cache the access token anywhere between launches. @johankool Can you say more about what behavior leads you to believe it's being cached?

**Comment by mikemorris** [comment]
I hit a similar issue previously in https://github.com/mapbox/mapbox-gl-native/issues/749, some debugging tips in there might be helpful.

**Comment by 1ec5** [comment]
As far as I can tell, #749 is specific to the iOS demo app, probably stemming from [this line](https://github.com/mapbox/mapbox-gl-native/blob/256b748458571201fe2b64bdf84dae6ec9b5932e/ios/app/MBXAppDelegate.m#L15). I know of nothing similar that would go into libMapboxGL.a.

**Comment by johankool** [comment]
I had a (secret) access token that at first worked. Then, I revoked it and created a new one, and used that instead. Rebuild my app (without deleting previous build first). The map wouldn't load anymore, instead complaining on the console. The token in the URL in the console message was different from the one I had set. I didn't have the first token handy anymore to see if that one was used. I deleted the app from my phone and installed and ran it again. Than it did work.

I'll go through these steps again today (or tomorrow) to see if I can still reproduce it.

**Comment by xwz** [comment]
Could it be the cached tiles? The sqlite db cache strips the access token from the cache key.

**Comment by jfirebaugh** [comment]
We were caching TileJSON with tile URL templates that had embedded access tokens, and then using those URL templates.

As of 025375ad0b365a06e0742b92fecc9bc538b5a6e0, we always canonicalize tile URL templates to a form that does not include an access token, fixing this issue.
