### ISSUE TITLE
GeoJsonSource support generateId

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#16222]
Is useful when having dataset that doesn't have any id associated so it can be used with feature state api: https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#geojson-generateId

cc @mapbox/gl-native

**Comment by 1ec5** [comment]
[`promoteId`](https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#geojson-promoteId) would be cool too.
