### ISSUE TITLE
Crash in CompoundExpression::evaluate due iOS Maps SDK XCTests

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native#16251]
Detected some crashes from device testing a nightly build generated from https://github.com/mapbox/mapbox-gl-native-ios/commit/e403a069f0 (post `5.7.0-beta.1`) / PR https://github.com/mapbox/mapbox-gl-native-ios/pull/179.

The above pins mapbox-gl-native at d85ce77deba12167f1c25a911ef81f44e35daa2a (on `release-unicorn` branch).

5 tests out of 545 tests failed (over 5 devices), attached 3 symbolicated crashes below:

Some of the crashes look to have happened as the associated XCTest is being shutdown; this feels like a thread clean-up issue. Although the crashes appear expression evaluation related, the offsets are large, and I suspect that there might have been an issue with the symbolication.

* From [Crash 1](https://github.com/mapbox/mapbox-gl-native/files/4269899/symbolicated.txt), [Crash 2](https://github.com/mapbox/mapbox-gl-native/files/4269900/symbolicated2.txt):

    `mbgl::style::expression::CompoundExpression::evaluate(mbgl::style::expression::EvaluationContext const&) const + 1858788` ([`compound_expression.cpp:1158`](https://github.com/mapbox/mapbox-gl-native/blob/d85ce77deba12167f1c25a911ef81f44e35daa2a/src/mbgl/style/expression/compound_expression.cpp#L1158))
    Crash 1 is identified as a segfault

* From [Crash 3](https://github.com/mapbox/mapbox-gl-native/files/4269901/symbolicated3.txt):

    `mbgl::style::expression::BasicComparison::evaluate(mbgl::style::expression::EvaluationContext const&) const + 1809700` ([`comparison.cpp:105`](https://github.com/mapbox/mapbox-gl-native/blob/d85ce77deba12167f1c25a911ef81f44e35daa2a/src/mbgl/style/expression/comparison.cpp#L105))

/cc @tmpsantos @pozdnyakov

**Comment by 1ec5** [comment]
Large offsets like 1858788 and 1809700 typically indicate that the actual symbols were hidden and the stack trace wasn’t correctly symbolicated.

**Comment by 1ec5** [comment]
Any idea what expression may have been evaluated at the time of the crash?

**Comment by alexshalamov** [comment]
@julianrex is there a way to run tests / reproduce an issue locally?

**Comment by julianrex** [comment]
I have not tried locally; I'll send you more info.

**Comment by julianrex** [comment]
I'm 95% certain this was due to a retain cycle that kept the `MGLMapView` alive as the tests were shutting down. Going to close this issue as solved, but should we able to support calling `exit` while a map is still active @tmpsantos ?
