### ISSUE TITLE
Unable to use in expression as layer filter

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#16262]
The `in` expression operator added in #16162 can only be used with paint and layout properties, not with layer filters. To reproduce, load this style and observe that nothing is visible:

<details>
<summary>colors.json</summary>

```json
{
  "version": 8,
  "zoom": 0,
  "center": [0, 0],
  "sources": {
    "quadrants": {
      "type": "geojson",
      "data": {
        "type": "FeatureCollection",
        "features": [
          {
            "type": "Feature",
            "properties": {
              "name": "ABC",
              "color": "red"
            },
            "geometry": {
              "type": "Polygon",
              "coordinates": [[
                [-180, -90],
                [-180, 0],
                [0, 0],
                [0, -90],
                [-180, -90]
              ]]
            }
          },
          {
            "type": "Feature",
            "properties": {
              "name": "DEF",
              "color": "#00ff00"
            },
            "geometry": {
              "type": "Polygon",
              "coordinates": [[
                [-180, 90],
                [-180, 0],
                [0, 0],
                [0, 90],
                [-180, 90]
              ]]
            }
          },
          {
            "type": "Feature",
            "properties": {
              "name": "GHI",
              "color": "#0000ff"
            },
            "geometry": {
              "type": "Polygon",
              "coordinates": [[
                [180, -90],
                [180, 0],
                [0, 0],
                [0, -90],
                [180, -90]
              ]]
            }
          },
          {
            "type": "Feature",
            "properties": {
              "name": "GHI",
              "color": "#ffff00"
            },
            "geometry": {
              "type": "Polygon",
              "coordinates": [[
                [180, 90],
                [180, 0],
                [0, 0],
                [0, 90],
                [180, 90]
              ]]
            }
          }
        ]
      }
    }
  },
  "glyphs": "local://glyphs/{fontstack}/{range}.pbf",
  "layers": [
    {
      "id": "colors",
      "type": "fill",
      "source": "quadrants",
      "filter": ["in", "#", ["get", "color"]],
      "paint": {
        "fill-color": ["get", "color"]
      }
    }
  ]
}
```

</details>

GL JS v1.8.1 | Expected | GL Native v1.3.0
----|----|----
![gl-js](https://user-images.githubusercontent.com/1231218/75748187-a851a800-5cd3-11ea-9c8d-709c4206d030.png) | <img width="869" alt="expected" src="https://user-images.githubusercontent.com/1231218/75747420-b7cff180-5cd1-11ea-8d4f-e0243b49a340.png"> | <img width="869" alt="actual" src="https://user-images.githubusercontent.com/1231218/75747421-b9011e80-5cd1-11ea-9026-1cf97511249b.png">

`mbgl::style::conversion::isExpression()` always returns false for the filter `["in", "#", ["get", "color"]]`, because `in` is also a [legacy filter operator](https://docs.mapbox.com/mapbox-gl-js/style-spec/other/#set-membership-filters):

https://github.com/mapbox/mapbox-gl-native/blob/305df25420e8ec592869d1048ee05a9fb2215bdd/src/mbgl/style/conversion/filter.cpp#L56-L57

/ref https://github.com/mapbox/mapbox-gl-native-ios/pull/183#issuecomment-593731631
/cc @jmkiley @Chaoba @chloekraw

**Comment by 1ec5** [comment]
`mbgl::style::conversion::isExpression()` does have some code to distinguish some expression operators from identically named filters, but `in` with two parameters might not be possible to resolve through static type checking. For example, `["in", "a", "abc"]` has two equally valid interpretations:

* Filter: Is the `a` property equal to “abc”?
* Expression: Is the string “a” a substring of “abc”?

To avoid breaking backwards compatibility with existing styles, we’d have to interpret it as a filter, but that would prevent us from fixing this issue and fully supporting mapbox/mapbox-gl-js#4113.

This is a contrived case, to be sure: it’s more likely for the filter to be written `["==", "a", "abc"]`, and there’s no practical reason for someone to test whether a literal string is in a literal string. But nothing would’ve stopped someone from using `in` instead of `==` back before Studio launched expression support. And `isExpression()` relies on static type checking, which means it doesn’t know whether `a` is a string literal or a reference to a feature property.

**Comment by 1ec5** [comment]
GL JS has code to avoid the original issue above, but it doesn’t quite address the ambiguity: mapbox/mapbox-gl-js#9373.

**Comment by kkaefer** [comment]
JS PR is in https://github.com/mapbox/mapbox-gl-js/pull/9374
