### ISSUE TITLE
incremental parsing

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#163]
We should create the buckets for a tile incrementally, filling them/adding them as we go. This makes the app feel a little faster because you at least see something, e.g. you see all the streets, but not labels yet.

refs #158

**Comment by tmpsantos** [comment]
#1326 has the interesting side effect of making this possible (it will be my next step as soon as I get rid of the promises).

**Comment by jfirebaugh** [comment]
No current plans to pursue this.
