### ISSUE TITLE
Is there a way to use it inside Unity 3D ?

### ISSUE THREAD

**Issue by dagatsoin** [mapbox/mapbox-gl-native#1631]
Is it possible to use mapbox gl inside unity 3D for iOS target ?

There is a part of the manual to build plugin for iOS http://docs.unity3d.com/460/Documentation/Manual/PluginsForIOS.html

But is mapbox gl compatible to this method ? Is there another way ? Is there a special version for unity on the roadmap ?

**Comment by incanus** [comment]
We haven't considered Unity 3D support yet and aren't familiar with it. We'd support any research into it, though. It's not part of the current roadmap. 

Same goes for: 

- Cordova/PhoneGap
- Titanium
- RubyMotion

Though we are experimenting with [React Native](https://github.com/bsudekum/react-native-mapbox-gl).

**Comment by mfkj** [comment]
Unity3D is a powerful cross-platform 3D engine and a user friendly development environment. Significant number of 3D Architecture are made in unity3d, please consider it also because maps are use in architecture where we place our 3d models on glob (map).

**Comment by tmpsantos** [comment]
> Unity3D is a powerful cross-platform 3D engine and a user friendly development environment. Significant number of 3D Architecture are made in unity3d, please consider it also because maps are use in architecture where we place our 3d models on glob (map).

@mfkj Using Mapbox GL inside Unity3D should be totally possible, we just don't provide official support for it ATM. You can see how it was done for Qt at this branch and try to do something similar.

https://github.com/mapbox/mapbox-gl-native/tree/qt-app

**Comment by mattak** [comment]
Hi, there.
I also think Unity3D support is awesome! and I'll try to implement it.

I have two questions.

1. Planned implementation is passing 'mapbox-gl-native' generated texture to Unity3D. Is it technically possible to make 'mapbox-gl-native' to support off-screen rendering?
2. Will this be charged by mobile-users count?  Is mentioned Qt implementation priced by 'mobile-user count' or 'map-view count'?

**Comment by dagatsoin** [comment]
Hi Mattak,
glad to see I am not the only concerned by this case. For various reason I switch from Unity + OnlineMap to Cordova + MapBox + Pixi.js/Three.js. But I kept the same way to put a 2D/2.5D/3D world on top of a map.
My way is is to track invisible markers of a MBGL native view. Each time the region changes or a game object is moved I sync the two views by converting geo coords invisible marker to screen coords GameObject position.
Note that does not take care of the tilt/orientation of the MBGL camera.

**Comment by brsbl** [comment]
Hey @dagatsoin, @mattak, @mfkj, have you seen that we've announced a [Mapbox Unity SDK](https://www.mapbox.com/unity/)?

**Comment by dagatsoin** [comment]
Yep but unfortunely I don't use Unity anymore since that was not possible when I opened this issue.

Do you think it could be possible to do the same thing (share opengl context) with MapboxGL and crosswalk/wkwebview?

Envoy? de mon iPhone

Le 17 d?c. 2016 ? 01:43, Bersabel Tadesse <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Hey @dagatsoin<https://github.com/dagatsoin>, @mattak<https://github.com/mattak>, @mfkj<https://github.com/mfkj>, have you seen that we've announced a Mapbox Unity SDK<https://www.mapbox.com/unity/>?

-
