### ISSUE TITLE
Line layer not rendering

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#16332]
Noticed while creating an example: 

![ezgif com-video-to-gif (11)](https://user-images.githubusercontent.com/2151639/77315174-5bc42000-6d07-11ea-91bd-c9615b8cf499.gif)

Will add PR of the example once it lands so it can be more easily reproduced.

cc @mapbox/gl-native

**Comment by tobrun** [comment]
Example code in https://github.com/mapbox/mapbox-gl-native-android/pull/288, you need to comment out https://github.com/mapbox/mapbox-gl-native-android/pull/288/files#diff-a108a9689c8891945092de42a2388d95R134 to reproduce above.

**Comment by tmpsantos** [comment]
This might be related to the GeoJSON to vector tile generation, because the roads are rendering fine.

**Comment by alexshalamov** [comment]
@tobrun could you try setting geojson's source options buffer to 0?

**Comment by tobrun** [comment]
yes but same result

**Comment by alexshalamov** [comment]
@zmiao could you take a look?

**Comment by zmiao** [comment]
@alexshalamov I will check it. Thanks!

**Comment by tobrun** [comment]
Boiled down to me not using the correct geometry type :man_facepalming:  
 - MultiPoint -> LineString
