### ISSUE TITLE
Take Screenshot when using SwiftUI

### ISSUE THREAD

**Issue by bilics** [mapbox/mapbox-gl-native#16337]
I followed the example here https://github.com/mapbox/mapbox-maps-swiftui-demo to use Mapbox with SwiftUI. However, since there is no access to the actual *mapview* object in SwiftUI, I am struggling on how to follow this example https://docs.mapbox.com/ios/maps/examples/map-snapshotter/ on how to take a screenshot of the map.

### Steps to reproduce

 1. 
 2. 
 3.

### Configuration

**Mapbox SDK versions:** 
**iOS/macOS versions:** 
**Device/simulator models:**
**Xcode version:**

**Comment by iNeedHelpX** [comment]
just to be clear, you want to bring up a live map and have a button that the user can press to take a screen shot of the map? 

ill try to see wgat i can come up with

**Comment by bilics** [comment]
Yes thanks - however, it is using the SwiftUI framework (following the example above).

The problems stems from the fact that I am not able to access the "instance mapView" to call the appropriate method.

**Comment by iNeedHelpX** [comment]
yeah i figure as much. theres a way to handle the content view, unfortunately its not in my head right now. Coronavirus is hitting my country unfortunately and gov wants us to stay home/inside, so ill have a lot of time to think about these things oddly. city is supposedly locked down.
