### ISSUE TITLE
eclipse project for Android.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1634]
Is there a way to generate eclipse projects for MapboxGLANDroidSDKTestApp and MapboxGLAndroidSDK? Debugging tools and plugins are much better for eclipse.
There are more android projects that use eclipse since its been around a lot longer and more developers are familiar with it. 

It would definitely make it easier for those who would  want to integrate the gl-native SDK with existing projects.

**Comment by ljbade** [comment]
At this stage I don't think we week support the demo apps in Eclipse. But we haven't made decision about supporting use of the Android SDK in Eclipse, but I think we likely will.

@bleege comments ?

**Comment by bleege** [comment]
Technically we don't officially support IDEs as our goals are to be IDE agnostic and rely on build tools, in this case Gradle as it's Google recommended tool for Android.  I know Eclipse's support for Gradle has gotten better with [their plugin](https://marketplace.eclipse.org/content/gradle-integration-eclipse-44) as well Gradle's Web site has [good information on working with Eclipse](https://docs.gradle.org/current/userguide/eclipse_plugin.html).  Are these helpful to you?

**Comment by mb12** [comment]
I've been experimenting with Android NDK and the available tools for debugging. I used a sample open gl application that draws a triangle using an android java binding for my analysis.

The following is possible using eclipse based tools. I could not figure out how to do it in Android Studio. Nor could I find *any* documentation on using Android Studio with NDK.

1.) Insert break points in native code.
2.) Recompile automatically in IDE after changing native code.
3.) Architecture specific compiler flags are more likely to  be correct.  Please see details here. (https://github.com/mapbox/mapbox-gl-native/issues/1468#issuecomment-105706016)
4.) ARM and Intel specific eclipse plugins are also available to debug native code (I did not actually evaluate them).

It looks like other mapping applications also keep an eclipse specific project just for debugging.

http://stackoverflow.com/questions/28307481/is-it-possible-to-debug-c-c-in-android-studio

**Comment by ljbade** [comment]
Making a note that new Android Studio 1.3 has C++ support which hopefully includes debugging

**Comment by jfirebaugh** [comment]
http://www.theregister.co.uk/2015/06/29/androids_sun_sets_on_eclipse/

Looking forward to our glorious Android Studio future.
