### ISSUE TITLE
Wiki access closed?

### ISSUE THREAD

**Issue by AAverin** [mapbox/mapbox-gl-native#16346]
Following page is no longer accessible.
https://github.com/mapbox/mapbox-gl-native/wiki#generate-the-offline-package

We are working on the offline side-loading of mapbox packages for our app and that page had detailed description on how to use CLI tool.

Is there any other place where I can find this kind of information? We would need to automatically generate offline packages for some parts of the app.

**Comment by 1ec5** [comment]
The wiki is still open to the public, but that particular page was deleted, as it’s a workflow that isn’t officially supported. If your application does require something like sideloading, please reach out to [Mapbox Technical Support](https://support.mapbox.com/hc/en-us) about your needs. Thanks for understanding!
