### ISSUE TITLE
Getting ANR after some minutes

### ISSUE THREAD

**Issue by Einhesari** [mapbox/mapbox-gl-native#16355]
**Platform:** Android
**Mapbox SDK version:** 9.0.0
**Mapbox Annotation Pluggin version:** 0.8.0

### Steps to trigger behavior
 1.  Create Mapview
 2. Show user location on map using location component ( camera mode = Tracking , render mode = compass )
 3. add some markers using symbol manager 
4. staying in app and not touching anything for about 10 minutes

### Expected behavior
app runs fine 
### Actual behavior
getting ANR with below logs : 

setVertexArrayObject: set vao to 39 (39) 524 152
setVertexArrayObject: set vao to 40 (40) 524 148
setVertexArrayObject: set vao to 0 (0) 524 522

D/Mbgl-HttpRequest: [HTTP] Request with response = 304: Not Modified
I/ri.zomatosampl:        
Thread[3,tid=21084,WaitingInMainSignalCatcherLoop,Thread*=0xed95dc00,peer=0x15ec3e38,"Signal 
Catcher"]: reacting to signal 3
I/ri.zomatosampl: Wrote stack traces to '[tombstoned]'
D/Mbgl-HttpRequest: [HTTP] Request with response = 304: Not Modified
D/Mbgl-HttpRequest: [HTTP] Request with response = 304: Not Modified

note that there's no other processes in the background.

**Comment by jas1989** [comment]
Hi, sorry but if I've no fragment and my logcat is full of setVertexArrayObject logs. Do you know how I can solve it?

**Comment by Einhesari** [comment]
@jas1989 
Hi, I think logging setVertexArrayObject is normal and there's no need to fix it

**Comment by jas1989** [comment]
@Einhesari Oh, yes! Sure! I don't think this is a bug or issue. Anyway there is a way to hide this kind of log in logcat? Because they are generated from mapbox I guess..
I'm sorry if this is not strictly related with this topic

**Comment by Einhesari** [comment]
@jas1989 
sorry I don't khow if there's a way to hide them.
