### ISSUE TITLE
On Android, the thin wall won't display.

### ISSUE THREAD

**Issue by wangwen520312** [mapbox/mapbox-gl-native#16350]
**Platform:Android**
**Mapbox SDK version:8.1.0**

### Steps to trigger behavior

 1.On Web, the thin wall are displayed.
 2.On Android, the thin wall won't display.

### Expected behavior
On android, thin walls also show up.

**Comment by tobrun** [comment]
thanks for reaching out @wangwen520312 but without seeing any screenshots or clear explanation what thin walls are. We won't be able to help..
