### ISSUE TITLE
Android Mapbox Mapview shows white screen before rendering maps

### ISSUE THREAD

**Issue by bssandeshbs** [mapbox/mapbox-gl-native#16367]
Mapbox Mapview shows a white screen flash before the Mapview is rendered. The flash stays for like 500ms after which the map is displayed. I am adding Mapview dynamically to my FrameLayout((addView()) at run time. Below is the code snippet. Please help !

Is there any property that needs to be specifically set for mapview

Platform: Android
Mapbox SDK version: 9.0.0

### Steps to trigger behavior

 1. Create a new Mapbox() Instance 
 2. Add it to a layout dynamically
 3. Call Mapbox.getAsync() API 
 4. white screen flash before mapview is displayed

```
private fun initializeMapBoxMap() {
    val mapView = MapView(context) // create new mapview 
    innerLayout.addView(mapView) // add mapView to the FrameLayout
    mapView.getMapAsync { mapboxMap ->
           // white screen shown at this point for 500 ms 
           mapboxMap.setStyle(Style.DARK) {
              // white screen gone after this point
           }
    }
}
```

### Actual behavior : white screen shown before rendering the maps

![Mapbox](https://user-images.githubusercontent.com/13276917/78190623-3b901180-7429-11ea-8e44-2144310b0397.jpeg)

**Comment by tobrun** [comment]
you can change the color to another with:
```
mapboxMapOptions.foregroundLoadColor(int color)
```

we try to mask that the glsurfaceview has loaded but we don't have any content to render as we are still loading the style definition. instead of loading resources, having them offline will also improve the UX.
