### ISSUE TITLE
Demo projects! :yeeeeeaaaaaaaah:

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#1636]
I'm sure there are other demos in the works, but in the meantime I put together a [demo/template project](https://github.com/friedbunny/mbgl-ios-demo) that folks can use as a quick start or basis for experimentation.

To kick things off, I built a [fun ambient light (screen brightness) style switching demo](https://github.com/friedbunny/ambient-light).

![it's actually brightness, ssssssshhhh](https://cloud.githubusercontent.com/assets/1198851/7789780/e743f59c-0222-11e5-9f81-ea80f5a0c66c.gif)

It's difficult to illustrate ambient light changes in a screencap, so I cheated and manually moved the brightness—*but imagine it's happening automagically*.

**Comment by friedbunny** [comment]
![alright](https://cloud.githubusercontent.com/assets/1198851/7792704/71965206-026b-11e5-8388-5e2d0a6cb5f3.gif)

Here's the ambient light demo again with the phone shoved under a desk lamp, now featuring a current brightness indicator!

**Comment by incanus** [comment]
wat. This is awesome.

**Comment by webventil** [comment]
Really nice idea! It would be great making the change of the style animatable to get a smooth color transition.
