### ISSUE TITLE
support load parent tile

### ISSUE THREAD

**Issue by barrycug** [mapbox/mapbox-gl-native#1637]
When I use the custom vector tiles,I want to generate all world boundary tiles at zoom level 0 to zoom level 5,then generate all country  boundary tiles at zoom level 6 to zoom  10 and generate citys tiles at zoom level 11 to zoom  16. I don't need generate all  world boundary tiles for one city.   
 
 in this case, at zoom level 11,I need load the tiles that out of the city boundary tiles from country ,but the country's tiles only valid for  zoom level 6 to zoom level 10.I think if there is no tile，the map can load the tile's parent tile.      

the nutiteq sdk https://developer.nutiteq.com/getting-started/ios has the feature. I think it is important for user that use the custom tiles.Generate all of the world tiles is difficult.

**Comment by barrycug** [comment]
![out](https://cloud.githubusercontent.com/assets/1191156/7794570/94574f8c-02fe-11e5-8198-b55635653191.gif)
from this gif, you can view the tile's parent tile data.

**Comment by mb12** [comment]
@barrycug One way to model this in Mapbox would be to create three Sources in your style.json.

world_boundary:
country_boundary
city_bondaries_and_features.

**Comment by barrycug** [comment]
thank you very much @mb12  It is OK.

**Comment by jfirebaugh** [comment]
Yes, as @mb12 suggested, I think this will already work if you specify sources with the appropriate `maxzoom` property.
