### ISSUE TITLE
Null object Reference .,I'm trying to retrive data from Firebase storage & Database on RecyclerView,but recyclerview(on Fragment) also contain navigation drawer , so its showing null object exception.

### ISSUE THREAD

**Issue by veda7999** [mapbox/mapbox-gl-native#16385]
**Main file on which RecyclerView will be called**

public class HomeFragment extends Fragment {
    EditText inputSearch;
    RecyclerView recyclerView;
    FloatingActionButton floatingbtn;
    FirebaseRecyclerOptions<Car> options;
    FirebaseRecyclerAdapter<Car, MyViewHolder> adapter;
   DatabaseReference Dataref;
    FragmentManager fragmentManager;
    FragmentTransaction fragmentTransaction;

    private MainActivity listener;
    private FloatingActionButton camera_Floating_btn;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.home_fragment, container, false);

        Dataref = FirebaseDatabase.getInstance().getReference().child("Car");
        inputSearch = view.findViewById(R.id.inputSearch);
        recyclerView = view.findViewById(R.id.recylerView);
        FloatingActionButton camera_Floating_btn = view.findViewById(R.id.fab);
        recyclerView.setLayoutManager(new LinearLayoutManager(getActivity()));
        recyclerView.setHasFixedSize(true);
      
        camera_Floating_btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // listener.onCameraBtnSelect();
            }
        });
        **LoadData("");**

        inputSearch.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {
            }
            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
         }
         @Override
            public void afterTextChanged(Editable s) {
                if (s.toString()!=null)
                {
                    **LoadData(s.toString());**
                }
                else
                {
                    **LoadData("");**
                }
            }
        });
        return view;
    }
    **private void LoadData(String data) {
        listener.loadD(data);
    }**

}

MainActivity.java

public class MainActivity extends AppCompatActivity implements NavigationView.OnNavigationItemSelectedListener{

    DrawerLayout drawerLayout;
    ActionBarDrawerToggle actionBarDrawerToggle;
    Toolbar toolbar;
    NavigationView navigationView;
    View v;
    FirebaseRecyclerOptions<Car> options;
    FirebaseRecyclerAdapter<Car, MyViewHolder> adapter;
    DatabaseReference Dataref;
    RecyclerView recyclerView;
    FragmentManager fragmentManager;
    FragmentTransaction fragmentTransaction;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
      /*  toolbar=findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
*/
        start();
    }

    private void start() {
        drawerLayout=findViewById(R.id.drawer);
        navigationView=findViewById(R.id.navigationView);
        navigationView.setNavigationItemSelectedListener(this);

       actionBarDrawerToggle = new ActionBarDrawerToggle(this,drawerLayout,toolbar,R.string.open,R.string.close);
        drawerLayout.addDrawerListener(actionBarDrawerToggle);
        actionBarDrawerToggle.setDrawerIndicatorEnabled(true);
        actionBarDrawerToggle.syncState();

        //default fragment
        fragmentManager= getSupportFragmentManager();
        fragmentTransaction=fragmentManager.beginTransaction();
        fragmentTransaction.add(R.id.container_fragment,new HomeFragment());
        fragmentTransaction.commit();
    }

    @Override
    public boolean onNavigationItemSelected(@NonNull MenuItem item) {
        drawerLayout.closeDrawer(GravityCompat.START);
        if(item.getItemId() == R.id.home){
            fragmentManager= getSupportFragmentManager();
            fragmentTransaction=fragmentManager.beginTransaction();
            fragmentTransaction.replace(R.id.container_fragment,new HomeFragment());
            fragmentTransaction.commit();

        }
        else if(item.getItemId() == R.id.myOrder){
            fragmentManager= getSupportFragmentManager();
            fragmentTransaction=fragmentManager.beginTransaction();
            fragmentTransaction.replace(R.id.container_fragment,new MyOrder());
            fragmentTransaction.commit();

        }else if(item.getItemId() == R.id.cart){
            fragmentManager= getSupportFragmentManager();
            fragmentTransaction=fragmentManager.beginTransaction();
            fragmentTransaction.replace(R.id.container_fragment,new Fragment_cart());
            fragmentTransaction.commit();

        }else if(item.getItemId() == R.id.notification){
            fragmentManager= getSupportFragmentManager();
            fragmentTransaction=fragmentManager.beginTransaction();
            fragmentTransaction.replace(R.id.container_fragment,new Fragment_cart());
            fragmentTransaction.commit();

        }else if(item.getItemId() == R.id.camera){
            fragmentManager= getSupportFragmentManager();
            fragmentTransaction=fragmentManager.beginTransaction();
            fragmentTransaction.replace(R.id.container_fragment,new Camera_Fragment());
            fragmentTransaction.commit();

        }else if(item.getItemId() == R.id.signOut){
            Intent singIn = new Intent(MainActivity.this,HomeFragment.class);
            singIn.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
            startActivity(singIn);
        }
        return true;
    }

    public void onCameraBtnSelect() {
        fragmentManager= getSupportFragmentManager();
        fragmentTransaction=fragmentManager.beginTransaction();
        fragmentTransaction.replace(R.id.container_fragment,new Camera_Fragment());
        fragmentTransaction.commit();
    }
    public void onImageUpload_from_farmer() {
        fragmentManager= getSupportFragmentManager();
        fragmentTransaction=fragmentManager.beginTransaction();
        fragmentTransaction.replace(R.id.container_fragment,new HomeFragment());
        fragmentTransaction.commit();
    }

 

    public void gotohome() {
        fragmentManager= getSupportFragmentManager();
        fragmentTransaction=fragmentManager.beginTransaction();
        fragmentTransaction.replace(R.id.container_fragment,new HomeFragment());
        fragmentTransaction.commit();

    }

    

> public void loadD(String data) {
>         Query query=Dataref.orderByChild("CarName").startAt(data).endAt(data+"\uf8ff");
>         options=new FirebaseRecyclerOptions.Builder<Car>().setQuery(query,Car.class).build();
>         adapter=new FirebaseRecyclerAdapter<Car, MyViewHolder>(options) {
>             @NonNull
>             @Override
>             public MyViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
>                 View v= LayoutInflater.from(parent.getContext()).inflate(R.layout.single_view,parent,false);
>                 return new MyViewHolder(v);
>             }
> 
>             @Override
>             protected void onBindViewHolder(@NonNull MyViewHolder holder, final int position, @NonNull Car model) {
>                 holder.textView.setText(model.getCarName());
>                 Picasso.get().load(model.getImageUrl()).into(holder.imageView);
>                 holder.v.setOnClickListener(new View.OnClickListener() {
>                     @Override
>                     public void onClick(View v) {
> 
>                         Intent intent = new Intent(v.getContext(),ViewActivity.class);
>                         intent.putExtra("key",getRef(position).getKey());
>                         startActivity(intent);
>                     }
>                 });
> 
>             }
> 
>         };
>         adapter.startListening();
>         recyclerView.setAdapter(adapter);
> 
>     }
> 

   }

gives me error like this

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.drawerfragment, PID: 17491
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.example.drawerfragment.MainActivity.loadD(java.lang.String)' on a null object reference
        at com.example.drawerfragment.HomeFragment.LoadData(HomeFragment.java:108)
        at com.example.drawerfragment.HomeFragment.onCreateView(HomeFragment.java:76)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
        at android.app.Activity.performStart(Activity.java:7978)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3472)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
I/BiChannelGoogleApi: [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@8360723
I/BiChannelGoogleApi: [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@8360723
`

**Comment by tobrun** [comment]
@veda7999 you are hitting a null pointer exception, nothing in your trace shows its related to Mapbox.
