### ISSUE TITLE
mapbox-gl-native doesn't like GCC 10

### ISSUE THREAD

**Issue by tsarajar** [mapbox/mapbox-gl-native#16438]
**Platform:** SLES 15
**Mapbox SDK version:** no idea, sorry

### Steps to trigger behavior

We build mapbox-gl-native in Qt 5.15, and it isn't compatible with GCC 10.
See https://bugreports.qt.io/browse/QTBUG-82850 with proposed fixes.

**Comment by alexshalamov** [comment]
@tsarajar fixed by https://github.com/mapbox/mapbox-gl-native/pull/16424. Closing for now, please reopen if needed. Thanks!

**Comment by tmpsantos** [comment]
> @tsarajar fixed by #16424. Closing for now, please reopen if needed. Thanks!

Cherry-picked these changes to `qt-staging`.

**Comment by krop** [comment]
> > @tsarajar fixed by #16424. Closing for now, please reopen if needed. Thanks!
> 
> Cherry-picked these changes to `qt-staging`.

#16424 doesn't have the include fix in render_vector_source.cpp. See https://bugzilla.opensuse.org/show_bug.cgi?id=1158510#c25 for the background

**Comment by tmpsantos** [comment]
@krop added, thanks for the heads-up!

**Comment by tsarajar** [comment]
Do we have a fix for the render_vector_source.cpp anywhere then?

**Comment by krop** [comment]
> Do we have a fix for the render_vector_source.cpp anywhere then?

https://github.com/mapbox/mapbox-gl-native/commit/d7e368c4 ?
