### ISSUE TITLE
iOS setDirection:animated: cancels setCenterCoordinate:animated:

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#1643]
When the following calls are made:

```
[self.mapView setCenterCoordinate:newLocation.coordinate animated:YES];
[self.mapView setDirection:newLocation.course * -1 + 360 animated:YES];
```

The first call to `setCenterCoordinate:` is ignored. If the order of the calls is reversed, then the call to `setDirection:` is ignored.

Ideally, there would be a single method to set both centerCoordinate and direction with both items animated.

**Comment by incanus** [comment]
> Ideally, there would be a single method to set both centerCoordinate and direction with both items animated.

Interesting. MapKit gets around this with the `MKMapCamera` API for setting all at once. We should indeed add a combined convenience method, and I would say the current behavior is expected.

**Comment by incanus** [comment]
This will be handled by the camera API work over in https://github.com/mapbox/mapbox-gl-native/pull/2193.
