### ISSUE TITLE
iOS setDirection:animated: resets the userTrackingMode

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#1644]
Calls to `setDirection:animated:` sets the userTrackingMode to MGLUserTrackingModeNone. There should be a way to set the direction while keeping the userTrackingMode set to MGLUserTrackingModeFollow.

**Comment by incanus** [comment]
This should be pretty simple, and while we're at it we should audit other locations where we aggressively reset to `.None` when we could keep `.Follow`. 

* [`resetNorthAnimated`](https://github.com/mapbox/mapbox-gl-native/blob/2ce4ae3047216d3e041d97646ba2cb94015862d7/platform/ios/MGLMapView.mm#L1342)
* [`setDirection:animated:`](https://github.com/mapbox/mapbox-gl-native/blob/2ce4ae3047216d3e041d97646ba2cb94015862d7/platform/ios/MGLMapView.mm#L1482)

**Comment by friedbunny** [comment]
@incanus Yay! I hit `resetNorthAnimated:` in #1257 and there's discussion of gestures+tracking in #1436.

**Comment by picciano** [comment]
Any chance we could get this little one back in the queue?
