### ISSUE TITLE
Runtime Marker Imagery

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1645]
Add ability to load custom Marker images to `MBXAnnotation`.

![screen shot 2015-05-26 at 5 06 37 pm](https://cloud.githubusercontent.com/assets/989928/7826050/a30c31d4-03c9-11e5-96db-969646e1f0fa.png)
_Current Default_

**Comment by incanus** [comment]
Already captured in https://github.com/mapbox/mapbox-gl-native/issues/941.

**Comment by 1ec5** [comment]
I think we'd probably expose an MGLMapViewDelegate method for providing the UIImage, similar to how you can specify the sprite image today. The annotation model objects are more about the data represented by the markers than the markers themselves.
