### ISSUE TITLE
Map is drawn over drawer

### ISSUE THREAD

**Issue by kalucky0** [mapbox/mapbox-gl-native#16469]
**Platform:** Android
**Mapbox SDK version:** 9.2.0

It happens from time to time on different phones. I'm using mikepenz's MaterialDrawer but it is also happening with default material drawer in my other app. Never occurred on my phone, but my users are complaining about it quite often.

### Expected behavior
![obraz](https://user-images.githubusercontent.com/10831698/82149742-8211c200-9857-11ea-9b8b-170cd0f5a1f5.png)

### Actual behavior
![obraz](https://user-images.githubusercontent.com/10831698/82149670-6d352e80-9857-11ea-92d4-3cf1267085a0.png)

### The code
```
findViewById(R.id.progressBar).setVisibility(View.VISIBLE);
findViewById(R.id.mapView).setVisibility(View.INVISIBLE);
setTitle("Mapa");
mapView.onCreate(savedInstanceState);
mapView.getMapAsync(mapboxMap -> mapboxMap.setStyle(new Style.Builder().fromUri("mapbox://styles/kalucki23/cka9w99ev1qoz1iog344td4sa"), style -> {
     Log.e("Test", "Test");
     findViewById(R.id.mapView).setVisibility(View.VISIBLE);
}));
```

**Comment by tobrun** [comment]
This stems from rendering with a GLSurfaceView, You can opt to use TextureView instead:
 -xml: textureMode=true
 -mapboxMapOptions#textureMode(true)
