### ISSUE TITLE
Emerald label render problems

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1646]
As of 2ce4ae3047216d3e041d97646ba2cb94015862d7. Not seen in the other three bundled styles. 

![ios simulator screen shot may 26 2015 10 01 43 pm](https://cloud.githubusercontent.com/assets/17722/7829150/e8a0ef90-03f2-11e5-8062-c4487946dcf0.png)

_Pine, Geary, and Ellis_

/cc @peterqliu

**Comment by 1ec5** [comment]
Looks like a tile boundary issue.

**Comment by incanus** [comment]
Yep, seems so. /cc @kkaefer @tmpsantos

![image](https://cloud.githubusercontent.com/assets/17722/7846865/100ecab6-0475-11e5-89b5-87ad77aeda97.jpg)

**Comment by 1ec5** [comment]
ref mapbox/mapbox-gl-js#757

**Comment by 1ec5** [comment]
Also reproduces in ios-v0.3.1:

![geary](https://cloud.githubusercontent.com/assets/1231218/7966413/c474d776-09d8-11e5-91eb-12c15edd7805.png)

**Comment by 1ec5** [comment]
#1666 fixes labels good:

![newgeary](https://cloud.githubusercontent.com/assets/1231218/7967021/65055438-09dc-11e5-98f8-007596c7ed1d.png)

**Comment by incanus** [comment]
Let's leave open just until this merges, just to be pedantic :stuck_out_tongue:
