### ISSUE TITLE
MGLRasterTileSource not being drawn for custom server

### ISSUE THREAD

**Issue by furysheep** [mapbox/mapbox-gl-native#16477]
I couldn't find a problem.

### Steps to reproduce
```
func mapView(_ mapView: MGLMapView, didFinishLoading style: MGLStyle) {
        let source = MGLRasterTileSource(identifier: "stamen", tileURLTemplates: ["http://gk200.com:3005/map_tiles/{x}/{y}/{z}"], options: [ .tileSize: 512 ])
        let rasterLayer = MGLRasterStyleLayer(identifier: "stamen", source: source)
        style.addSource(source)
        style.addLayer(rasterLayer)
         
        self.rasterLayer = rasterLayer
    }
```
I am using custom tile server to draw over the default style.
https://docs.mapbox.com/ios/maps/examples/source-custom-raster/

When i use this server, the tiles are successfully drawn.
https://stamen-tiles.a.ssl.fastly.net/terrain/{z}/{x}/{y}.jpg

If i use this server url, it doesn't work.
http://gk200.com:3005/map_tiles/{x}/{y}/{z}

### Expected behavior
The custom tiles should be drawn.

### Actual behavior
No raster style is drawn

### Configuration

Mapbox SDK versions: 5.9
iOS 13.4
iPhone 11 pro simulator
Xcode version: 11.4

**Comment by RustamG** [comment]
Hey @furysheep! 
How did you resolve the issue?
