### ISSUE TITLE
First steps guide fails on error

### ISSUE THREAD

**Issue by ashleyclough** [mapbox/mapbox-gl-native#1648]
I've been following the first steps guide but get an error when running the app for the first time in Xcode with Mapbox GL 0.3.1. - see attached (swift version, same error occurs with Objective-C). The other published demo at https://github.com/friedbunny/mbgl-ios-demo works fine but 'pod update' seemed to install v0.3.2? Any ideas?
![ios gl error](https://cloud.githubusercontent.com/assets/912721/7833403/70d80144-045e-11e5-9c70-15dac5d979fe.png)

**Comment by 1ec5** [comment]
This looks like an assertion failure related to a missing setup step. Please scroll up in the console area, copy the exception message near the top, and paste it in here. Thank you!

**Comment by ashleyclough** [comment]
2015-05-27 16:30:10.078 My First GL App[44581:19473666] *** Assertion failure in -[MGLMapboxEvents init], /Users/travis/build/mapbox/mapbox-gl-native/platform/ios/MGLMapboxEvents.m:216
2015-05-27 16:30:10.086 My First GL App[44581:19473666] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'End users must be able to opt out of Metrics in your app, either inside Settings (via Settings.bundle) or inside this app. If you implement the opt-out control inside this app, disable this assertion by setting [MGLAccountManager setMapboxMetricsEnabledSettingShownInApp:YES] before the app initializes any Mapbox GL classes.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010b414c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010cf7fbb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010b414aca +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x000000010b8b198f -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   MapboxGL                            0x000000010b0a933a -[MGLMapboxEvents init] + 1242
	5   MapboxGL                            0x000000010b0a9c36 __32+[MGLMapboxEvents sharedManager]_block_invoke_2 + 38
	6   libdispatch.dylib                   0x000000010e5da614 _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x000000010e5c6881 dispatch_once_f + 565
	8   MapboxGL                            0x000000010b0a9bff __32+[MGLMapboxEvents sharedManager]_block_invoke + 95
	9   MapboxGL                            0x000000010b0a9b1d +[MGLMapboxEvents sharedManager] + 221
	10  MapboxGL                            0x000000010b0c0447 +[MGLAccountManager setAccessToken:] + 119
	11  MapboxGL                            0x000000010b0ae04c -[MGLMapView setAccessToken:] + 188
	12  MapboxGL                            0x000000010b0add9a -[MGLMapView initWithFrame:accessToken:styleURL:] + 170
	13  MapboxGL                            0x000000010b0adcea -[MGLMapView initWithFrame:accessToken:] + 58
	14  My First GL App                     0x000000010af51ac9 _TTOFCSo10MGLMapViewcfMS_FT5frameVSC6CGRect11accessTokenGSQSS__GSQS__ + 233
	15  My First GL App                     0x000000010af4d294 _TFCSo10MGLMapViewCfMS_FT5frameVSC6CGRect11accessTokenGSQSS__GSQS__ + 148
	16  My First GL App                     0x000000010af4c6cd _TFC15My_First_GL_App14ViewController11viewDidLoadfS0_FT_T_ + 397
	17  My First GL App                     0x000000010af4cab2 _TToFC15My_First_GL_App14ViewController11viewDidLoadfS0_FT_T_ + 34
	18  UIKit                               0x000000010bde4210 -[UIViewController loadViewIfRequired] + 738
	19  UIKit                               0x000000010bde440e -[UIViewController view] + 27
	20  UIKit                               0x000000010bcff2c9 -[UIWindow addRootViewControllerViewIfPossible] + 58
	21  UIKit                               0x000000010bcff68f -[UIWindow _setHidden:forced:] + 247
	22  UIKit                               0x000000010bd0be21 -[UIWindow makeKeyAndVisible] + 42
	23  UIKit                               0x000000010bcaf457 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 2732
	24  UIKit                               0x000000010bcb21de -[UIApplication _runWithMainScene:transitionContext:completion:] + 1349
	25  UIKit                               0x000000010bcb10d5 -[UIApplication workspaceDidEndTransaction:] + 179
	26  FrontBoardServices                  0x000000010fa865e5 __31-[FBSSerialQueue performAsync:]_block_invoke_2 + 21
	27  CoreFoundation                      0x000000010b34841c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	28  CoreFoundation                      0x000000010b33e165 __CFRunLoopDoBlocks + 341
	29  CoreFoundation                      0x000000010b33df25 __CFRunLoopRun + 2389
	30  CoreFoundation                      0x000000010b33d366 CFRunLoopRunSpecific + 470
	31  UIKit                               0x000000010bcb0b42 -[UIApplication _run] + 413
	32  UIKit                               0x000000010bcb3900 UIApplicationMain + 1282
	33  My First GL App                     0x000000010af52237 main + 135
	34  libdyld.dylib                       0x000000010e60e145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by incanus** [comment]
Key line is: 

>  'End users must be able to opt out of Metrics in your app, either inside Settings (via Settings.bundle) or inside this app. If you implement the opt-out control inside this app, disable this assertion by setting [MGLAccountManager setMapboxMetricsEnabledSettingShownInApp:YES] before the app initializes any Mapbox GL classes.'

Check [this step](https://www.mapbox.com/guides/first-steps-gl-ios/#settings) and make sure you have a bundle setup. 

> mbgl-ios-demo works fine but 'pod update' seemed to install v0.3.2? 

That project's [`Podfile`](https://github.com/friedbunny/mbgl-demo-ios/blob/master/Podfile) points at the current GL repository `master`. Releases publish to CocoaPods and are obtained with just `pod 'MapboxGL'`.

**Comment by ashleyclough** [comment]
I had already followed the settings bundle installation:

![root plist](https://cloud.githubusercontent.com/assets/912721/7840608/1edc350e-0490-11e5-91ad-3b1c2cffdcd1.png)
![root strings](https://cloud.githubusercontent.com/assets/912721/7840609/1efdd22c-0490-11e5-9d2d-9079f387413c.png)

**Comment by friedbunny** [comment]
> That project's Podfile points at the current GL repository master. Releases publish to CocoaPods and are obtained with just pod 'MapboxGL'.

Hrm, I missed that we'd hit the Cocoapods big time, will update my demos!

**Comment by friedbunny** [comment]
@ashleyclough The `Identifier` key in `Settings.bundle` is wrong: `mapbox_metrics_enabled_preference` needs to be `MGLMapboxMetricsEnabled`. We'll need to update the download, sorry.

**Comment by ashleyclough** [comment]
I've changed the value and it now works fine. Thanks

**Comment by 1ec5** [comment]
The guide links to a very outdated copy of the example Settings bundle. We’ve updated the example. Thanks for reporting the issue!
