### ISSUE TITLE
ios

### ISSUE THREAD

**Issue by Trapster223** [mapbox/mapbox-gl-native#16488]
### Steps to reproduce

 1.npm i @mapbox/mapbox-gl-native

### Actual behavior
@mapbox/mapbox-gl-native

### Configuration

**Mapbox SDK versions:** macos catalina 10.15.4
**iOS/macOS versions:** ios 13.4
**Device/simulator models:**
**Xcode version:**

**Comment by Trapster223** [comment]
macos catalina 10.15.4
ios 13.4
npm i @mapbox/mapbox-gl-native

**Comment by tobrun** [comment]
Thank you for reaching out and using our products.
This issue doesn't have any actionable information.
