### ISSUE TITLE
Mapbox gl native android sdk size is more than mapbox android bintray library

### ISSUE THREAD

**Issue by karanveer0802** [mapbox/mapbox-gl-native#16487]
I have uploaded mapbox gl native android sdk code to bintray and used it as a dependency in another project which increase my apk size with 25 mb and in same project if a use mapbox dependency mention on official site of mapbox it increase the size of apk only 11 mb .please help me in this case how can i reduce the size of apk.

**Comment by tobrun** [comment]
Thank you for reaching out and using our products. As mentioned by you, our product is working as designed.

**Comment by karanveer0802** [comment]
your welcome but please let me know about the difference in sdk size i am using same code of mapbox android sdk or you use any command to compress code and then upload it to bintray?

**Comment by karanveer0802** [comment]
@tobrun

**Comment by tobrun** [comment]
@karanveer0802 all our code is publicly availlable in https://github.com/mapbox/mapbox-gl-native-android. Apologies but we can't provide support for your use-case.

**Comment by karanveer0802** [comment]
@tobrun yes ,i have checked the link but please you can help me in this issue or guide why is so much diffrence in the size if i am using same sdk from mentioned link
