### ISSUE TITLE
Icons are black and white on Android

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1649]
![image](https://cloud.githubusercontent.com/assets/52399/7834496/28ea521c-0470-11e5-9af1-3446e06a74c4.png)

**Comment by ljbade** [comment]
On my Sony Xperia Z3 it is even worse, I just get a white filled shape the same outline as those markers with no black fill.

Some sort of GL issue?

**Comment by bleege** [comment]
This look similar to https://github.com/mapbox/mapbox-gl-native/pull/843.

**Comment by ljbade** [comment]
Did some testing.

With a red outputting `icon.fragment.glsl` I get red squares. The actual shader is simple pass through of the texture colour. So it apppears to be either an issue with creating the GL texture or bad texture data.

It appears the GL code to create and load the `SpiteAtlas` is OK. Thus it might be the underlying SpriteAtlas data that is wrong.

I also experimented with hard coding the pixel ratio at https://github.com/mapbox/mapbox-gl-native/blob/master/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java#L139

With `1.0f`, `2.0f`, `3.0f`, `4.0f` the icons load fine.

**Comment by ljbade** [comment]
Ignore above for the moment

@kkaefer can you test again with latest master, icons loading fine on my Sony now. Not sure what got changed recently.

**Comment by tmpsantos** [comment]
Funny that I hit something similar on QMapboxGL (on Linux only) that I fixed with a nasty hack:
https://github.com/tmpsantos/qmapboxgl/blob/master/src/qmapboxgl.cpp#L118-L122

**Comment by ljbade** [comment]
Perhaps there is a bug in the code that scales sprite data as it gets copied to the sprite atlas

**Comment by kkaefer** [comment]
Just checked, this problem still exists with current master.

**Comment by ljbade** [comment]
Hmm I wonder what is specific to your phone

**Comment by mb12** [comment]
@kkaefer What is the screen density on your device (Devicemetrics.density)? Android devices can have fractional densities (1.5, 2.5 etc.).

**Comment by kkaefer** [comment]
@mb12 it's 2.0

**Comment by ljbade** [comment]
@kkaefer what happens if you try a suggestion I got to change the spite fragment shader to output red pixels?

**Comment by mb12** [comment]
@tmpsantos  and @kkaefer  Were you able to figure out why on linux adding 0.0001 to device density causes icons to show up with regular colors instead of black and white?  Is it possible to do the same experiment on the Android device  that shows black and white icons?

**Comment by ljbade** [comment]
I wonder if there is something wrong in the code that scales up sprites from the original image to the size required by the GL texture (which is set based on density) that causes it to not correctly copy the data.

**Comment by zugaldia** [comment]
Just in case it helps, I can see color icons on a Nexus 5 with current master:

![screenshot_2015-06-30-15-02-14](https://cloud.githubusercontent.com/assets/6964/8439330/555d8b64-1f39-11e5-8c8f-a749f9175cef.png)

**Comment by bleege** [comment]
I also haven't seen this recently.  @kkaefer @ljbade can you :eyes: things again on your devices.  If things are good we can close this ticket.

**Comment by bleege** [comment]
Haven't seen this recently and no one is talking about it.  We also just bumped to V8 styles as of 24-Aug-2015 via 6966addb8d0b850f10195408c0eef38836c97a1d.

**Comment by kkaefer** [comment]
I can't reproduce this anymore on my Moto G2.

**Comment by zugaldia** [comment]
Just FYI, the Espresso tests for the test app include now a way to take screenshots of the map that could help track this kind of issue in the future.

For example, [this test](https://github.com/zugaldia/mapbox-gl-native/blob/2317-espresso/android/java/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxgl/testapp/MainActivityScreenTest.java#L49) switches to the Streets style, and perform two double clicks (to zoom in). Then it takes a screenshot named `testMapboxStreetsBlackAndWhite.png`. This works on AWS Device Farm, so we could check the resulting screen in dozens of devices automatically.

**Comment by zugaldia** [comment]
Forgot to add, AWS also let's you mock the user location to any lat/lon.

**Comment by ljbade** [comment]
@zugaldia: Nice, perhaps you can script an image compare test? Then we could add test cases as we find and fix render bugs.

**Comment by ljbade** [comment]
@zugaldia: Nice, perhaps you can script an image compare test? Then we could add test cases as we find and fix render bugs.
