### ISSUE TITLE
Support CGRectNull in init

### ISSUE THREAD

**Issue by msingleton** [mapbox/mapbox-gl-native#1654]
Putting together a basic hello world example of a full screen map using autolayout, works fine if you give it a dummy frame to start, but it would be great to avoid a crash when you give it CGRectNull

https://gist.github.com/msingleton/f5c6aa12ab761d42fdb7

**Comment by 1ec5** [comment]
This is basically the same thing as #1572, even though `CGRectNull` isn’t technically the same thing as `CGRectZero`.
