### ISSUE TITLE
Android SDK artifacts not available at maven central

### ISSUE THREAD

**Issue by 14v** [mapbox/mapbox-gl-native#16556]
**Platform: Android**
**Mapbox SDK version: 9.5.0**

### Steps to trigger behavior

 1. Do not add mapbox maven repo
 2. Add SDK dependency
 3. Sync gradle

### Expected behavior
Artifacts available or there is notice in readme that maven central not maintained

### Actual behavior
SDK artifacts available up to 9.2.1 https://search.maven.org/search?q=mapbox-android-sdk
otherwise 
```Failed to resolve: com.mapbox.mapboxsdk:mapbox-android-sdk:9.5.0```

**Comment by tobrun** [comment]
see https://github.com/mapbox/mapbox-gl-native-android#project-configuration
