### ISSUE TITLE
how can draw the custom layer data on the map by mbgl::painter ?

### ISSUE THREAD

**Issue by zochunhua** [mapbox/mapbox-gl-native#1656]
I have some json layer  data , like 

{
    "type": "FeatureCollection", 
    "features": [
        {
            "geometry": {
                "type": "Point", 
                "coordinates": [
                    116.21000836585, 
                    39.327215323
                ]
            }, 
            "type": "Feature", 
            "properties": {
                "hello": "beijing"
            }
        }
    ]
}

how can draw the layer data on the map by mbgl::painter ?
please give some example?

**Comment by jfirebaugh** [comment]
GeoJSON data overlays are not currently possible, but we're working on it. See previous issues like #507 and #893.
