### ISSUE TITLE
Metrics To TEST Server Need SSLPinning Support

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1659]
Metrics are not being sent to the TEST / Staging server url due to lack of support for the SSL Certificate on https://cloudfront-staging.tilestream.net/.  Add this cert and check it only if Staging server is endpoint to get #1396 working.

/cc @mapbox/mobiledata

**Comment by incanus** [comment]
Again, SSL pinning works! :wink:

**Comment by bleege** [comment]
Added cert from test server, and only check it if the 2 primary PROD certs aren't found AND it's confirmed that the app is setup to send metrics to Staging.

Travising now and then will merge.

**Comment by bleege** [comment]
Travis tested, merged.  Metrics events should now be showing in Staging for dev builds.

**Comment by bleege** [comment]
Implementing @1ec5's [code review suggestions](https://github.com/mapbox/mapbox-gl-native/pull/1661/files#r31294516) and then will close.

**Comment by bleege** [comment]
Implemented suggestions, re-Travised, merged.  Done.
