### ISSUE TITLE
AnnotationManager::getAnnotationsInBounds broken

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1660]
Noticed while working in https://github.com/mapbox/mapbox-gl-native/pull/1655 — applies to current `master` as well. Always comes up empty.

**Comment by 1ec5** [comment]
Reproduces until you zoom in or out.

**Comment by incanus** [comment]
Not sure what conditions you were seeing this under @1ec5, but my case was due to not clamping latitude for Mercator (bf6be3c) and another issue around returning duplicate annotations int the query (8626f91).

**Comment by incanus** [comment]
This is all patched up now. 376ad5ee0240ee7d4ca68633089d0f38002a2b19 fixes things for shapes (union, not containment) and da013180caa0fcd6075f835316af9fc208d17862 allows filtering by annotation type in the C++ API, which iOS now uses to filter to just points for tap selection.

**Comment by 1ec5** [comment]
I was seeing #1675 rather than this bug.
