### ISSUE TITLE
mbgl-offline tool compilation failed on Linux

### ISSUE THREAD

**Issue by nsourligas** [mapbox/mapbox-gl-native#16610]
**Platform:** Linux Mint 19.3 Cinnamon
**Mapbox SDK version:** Mapbox GL Native on Linux

### Steps to trigger behavior

 1. git clone --recurse-submodules https://github.com/mapbox/mapbox-gl-native.git
 2. make offline **OR** make mbgl-offline

### Expected behavior

Running into normal linux compilation procedure and wait to generate the binary tool mbgl-offline

### Actual behavior

Error message: **make: *** No rule to make target 'offline'.  Stop.**

**Comment by sedot42** [comment]
Hi, thanks for reporting this potential bug. This project compiles via cmake. Please try following this answer: https://stackoverflow.com/a/67701189/4700618

> After you followed those steps you will have build/bin/ which contains the built applications. You where searching for build/bin/mbgl-offline.

**Comment by nsourligas** [comment]
@sedot42 

Following the answer solved it. Thanks!
