### ISSUE TITLE
Where is querysourcefeatures?

### ISSUE THREAD

**Issue by johnnyzen** [mapbox/mapbox-gl-native#16612]
Android SDK
com.mapbox.maps:android:10.0.0-beta.20

According to examples and other online sources, GeoJsonSource should have querySourceFeatures?

But I cannot see it within GeoJsonSource?

I am trying to extract data out of a GeoJsonSource object, and this seems like the best way to do it.

Am I missing something?

**Comment by tobrun** [comment]
mapboxMap.querySourceFeatures("id", querySourceOptions, querySourceCallback)
