### ISSUE TITLE
Inability to simultaneously use with MapboxMaps 10

### ISSUE THREAD

**Issue by nab0y4enko** [mapbox/mapbox-gl-native#16620]
### Steps to reproduce

Add to Podfile both of current versions of SDK and run `pod install`
```
pod 'Mapbox-iOS-SDK', '6.3.0'
pod 'MapboxMaps', '10.0.0-rc.4'
```

### Expected behavior
Both libraries installed correctly. 

### Actual behavior
Libraries use completely different hardcoded versions of `MapboxMobileEvents`

```
[!] CocoaPods could not find compatible versions for pod "MapboxMobileEvents":
  In snapshot (Podfile.lock):
    MapboxMobileEvents (= 1.0.2)

  In Podfile:
    Mapbox-iOS-SDK (= 6.3.0) was resolved to 6.3.0, which depends on
      MapboxMobileEvents (~> 0.10.4)

    MapboxMaps (= 10.0.0-rc.4) was resolved to 10.0.0-rc.4, which depends on
      MapboxMobileEvents (= 1.0.2)

Specs satisfying the `MapboxMobileEvents (= 1.0.2), MapboxMobileEvents (= 1.0.2), MapboxMobileEvents (~> 0.10.4)` dependency were found, but they required a higher minimum deployment target.

```

### Configuration

**Mapbox SDK versions: 6.3.0 and 10.0.0-rc.4** 
**iOS/macOS versions: 11.4 (20F71)** 
**Device/simulator models: none**
**Xcode version: 12.5.1 (12E507)**

**Comment by mostafaac30** [comment]
need help too

**Comment by khush004** [comment]
Any solution found for this?
