### ISSUE TITLE
Linux build fails on exception_ptr

### ISSUE THREAD

**Issue by jchristof** [mapbox/mapbox-gl-native#16653]
**Platform:** Ubuntu 22.04.1
**Mapbox SDK version:** Build from source

### Steps to trigger behavior

 1. Start a build from terminal following steps listed in readme

### Expected behavior
Build succeeds

### Actual behavior
Build fails:
/mapbox-gl-native/include/mbgl/util/string.hpp:68:33: error: ‘exception_ptr’ in namespace ‘std’ does not name a type; did you mean ‘exception’?

mapbox-gl-native/vendor/benchmark/src/benchmark_register.h:22:30: error: ‘numeric_limits’ is not a member of ‘std’

Is this a standard library version error? What steps to fix the error?

**Comment by jchristof** [comment]
Platform issue. I'll ask elsewhere.

**Comment by tinoue** [comment]
@jchristof Just FYI. I have the same issue and adding `#include `<exception>` in the string.hpp solves the error. Thanks to ChatGPT!
