### ISSUE TITLE
Add Android integration testing

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#1667]
I am working on using [Calabash](https://github.com/calabash/calabash-android) to add integration testing for the Android test app to Travis. Hopefully this will prevent regression as we push on the Android beta.

However it is tricky getting the Android emulator to work on Travis with OpenGL.

I tried copying over the mesa install from the Linux builds but it does not seem to be enough.

The message I get from the emulator is 

```
Failed to Initialize backend EGL display
emulator: WARNING: Could not initialize OpenglES emulation, using software renderer.
```

Which I think is the reason Calabash can't connect to the app later on (since the app would not be able to start?).

My current work is in https://github.com/mapbox/mapbox-gl-native/tree/android-testing

If it proves impossible to emulate Android on Travis then we might have to just use TestMunk - https://github.com/mapbox/mapbox-gl-native/issues/587 - which runs on a real device, but we would need to subscribe to one of their plans.

@kkaefer Can you see anything I missed as far as installing Mesa on the Travis Android instance?

**Comment by ljbade** [comment]
Just realised the problem might be that I also need to copy https://github.com/mapbox/mapbox-gl-native/blob/master/scripts/linux/setup.sh for Android.

**Comment by bleege** [comment]
If Travis and TestMunk don't work out, we may want to consider Google's new [Cloud Test Lab](http://www.androidpolice.com/2015/05/28/io-2015-google-announces-cloud-test-lab-to-remotely-test-your-app-on-the-top-20-android-devices/) that was introduced at Google IO last week.

**Comment by ljbade** [comment]
@bleege Google's service looks interesting. I signed up to test it. I wonder if it will be a free service?

**Comment by bleege** [comment]
@ljbade I believe it will be, but let's set it aside for the time being and concentrate on Travis first since that's our primary system.  We can always come back to it.

**Comment by ljbade** [comment]
Enabled some logging at found that the app starts in the emulator but then fails to load GLES: https://travis-ci.org/mapbox/mapbox-gl-native/jobs/65007570#L5422

`E/mbgl    ( 1557): {Main}[OpenGL]: eglChooseConfig() returned no configs.`

**Comment by ljbade** [comment]
Also found
`D/libEGL  (   53): Emulator without GPU support detected. Fallback to software renderer.`

Looks like the emulator still isn't enabling GL even with mesa installed.

**Comment by ljbade** [comment]
I might try install the apt-package mesa for Android jobs instead of our custom built one next.

**Comment by ljbade** [comment]
I discovered I might need to add `-gpu on` to the `emulator` command. But now it appears the emulator fails to start up.

**Comment by ljbade** [comment]
From https://travis-ci.org/mapbox/mapbox-gl-native/jobs/65030854

It seems the emulator gets into a constant boot crash loop because it can't load EGL.

**Comment by ljbade** [comment]
@bleege it is beginning to look like Travis is not suitable for testing OpenGL Android apps :-/

Perhaps cloud testing will be the only way for us to do automated Android tests.

**Comment by bleege** [comment]
> it is beginning to look like Travis is not suitable for testing OpenGL Android apps

That's good to learn.  Can you clarify if you mean as for UI testing or for general unit testing on a commit by commit basis?

**Comment by ljbade** [comment]
Both. As long as you create an instance of the MapView you need to be able to load GL.

**Comment by bleege** [comment]
@ljbade So in other words, using Travis CI for Android GL development is not going to work?

**Comment by ljbade** [comment]
@bleege Unless I figure out how to get the emulator to work with mesa (software GL implementation - we use it for the Linux tests on Travis).

@kkaefer suggested trying to recreate the issue on a local VM to get more insight. I started setting up a VM last night.

**Comment by ljbade** [comment]
@kkaefer I figure out what is going on.

For whatever bizzare reason the Android SDK has 32bit tools, thus the Android emulator is 32bit.

I installed 32bit libs of libc/libc++/mesa/x11/dri.

I made some progress, the emulator can now find libGL, however the 32bit libGL tries to load the 64bit version of the software raster version of the GL DRI and obviously fails.

This is the debug output:

![image](https://cloud.githubusercontent.com/assets/1215089/7953832/cfca84b6-0a0c-11e5-8465-c2ba384e400a.png)

**Comment by ljbade** [comment]
So we at least need a 32bit mason built or apt-get installed version of mesa if we continue with trying to run Mapbox GL in an emulator.

**Comment by ljbade** [comment]
Hmm it might be because I installed the 64bit version of Xvfb which might explain why it is trying to load 64bit DRI.

I tried removing everything then installing `xvfb:i386` package but get error:
![image](https://cloud.githubusercontent.com/assets/1215089/7954058/49823464-0a0f-11e5-8eaa-ccfc38a52eaf.png)

I might have to try fresh Ubuntu install incase my messing around with 32bit and 64bit mesa broke something.

**Comment by ljbade** [comment]
Even with fresh Ubuntu it is impossible to install 32bit xvfb on 64bit machine. Thus my conclusion is the Android emulator will only run GLES apps on 64bit Linux when there is a real GPU installed.

@bleege It is therefore impossible to use the Android emulator for our purposes on Travis. Looks like we have no choice but to use cloud testing service. I recommend we sign up for a Testmunk plan.

**Comment by freenerd** [comment]
AWS launched the AWS Device Farm, that might help running Integration Tests on Android.

https://aws.amazon.com/blogs/aws/aws-device-farm-test-mobile-apps-on-real-devices/

On a related note there is also CodePipeline now, which might help feeding jobs into AWS Device Farm.

https://aws.amazon.com/codepipeline/

**Comment by ljbade** [comment]
@freenerd Cool! I will try it out when I next get a chance to look integration testing again.

**Comment by ljbade** [comment]
Quick note I spotted at https://developer.android.com/tools/sdk/tools-notes.html

Build tools 24.3.4:
* Added support for GPU emulation on Windows and Linux platforms using the -gpu mesa command line option.

This should allow us to run the Android simulator on Travis for testing.

It also appears they might have fixed some of the emulator GL bug I encountered before.

**Comment by tobrun** [comment]
This issue is no longer applicable, see unit + ui testing integration on Android.
