### ISSUE TITLE
Add Crashlytics NDK Support To Android GL Test App

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1668]
To help with debugging issues in Android GL between the Java bindings layer and the C++ Core GL layer let's implemented the new [Crashlytics NDK support](http://crashlytics.com/blog/the-wait-is-over-launching-crashlytics-for-android-ndk) for error tracking.

The longer term fix will be the [new NDK support in Android Studio](http://arstechnica.com/gadgets/2015/05/good-news-for-game-devs-android-studio-1-3-supports-androids-cc-ndk/), but in the mean time this will help make issues more clear.

@mapbox/mobile @kkaefer @jfirebaugh

**Comment by bleege** [comment]
Successfully tested integration by removing Mapbox Access Token and running the app.  This caused the [app to crash](https://github.com/mapbox/mapbox-gl-native/issues/1915) and throw a `java.langRunTimeException` which Fabric / Crashlytics [captured](https://fabric.io/mapbox4/android/apps/com.mapbox.mapboxgl.testapp/issues/55afd5372f03874947a0d150).

**Comment by bleege** [comment]
Steps for using Fabric / Crashlytics:

1. Sign up for a free [Fabric account](https://fabric.io/).
1. Install plugin into IDE
1. Include `fabric.properties` file in the TestApp

**Comment by bleege** [comment]
Merged!

**Comment by mb12** [comment]
Can you please clarify the following?

1.) Does this mean we have to sign up with Crashlytics just to build and test on Android? Note that its not available for everyone. You have to sign up. Then they put you on the list etc.

2.) Also does this mean Mapbox customers now have to purchase Crashlytics plan as well in addition to Mapbox's?

3.) Do we need to inform end users as well about any metrics/data sharing with Crashlytics in addition to Mapbox?

**Comment by bleege** [comment]
Happy to do so @mb12!

> 1.) Does this mean we have to sign up with Crashlytics just to build and test on Android? Note that its not available for everyone. You have to sign up. Then they put you on the list etc.

I don't believe so.  It should be possible to continue to run the TestApp as is if one does not have the Crashlytics plugin installed in the IDE and / or does not have an account.  Please test this out though.  If it turns out to not be the case (ie, the TestApp will not compile / run without Crashlytics) then please let us know and we will reconsider.  It's not our goal to require 3rd party developers to have to use Crashlytics.

> 2.) Also does this mean Mapbox customers now have to purchase Crashlytics plan as well in addition to Mapbox's?

No.  Twitter Fabric (which Crashlytics is part of) [is a free service](https://www.crashlytics.com/blog/crashlytics-enterprise-is-now-free/).

> 3.) Do we need to inform end users as well about any metrics/data sharing with Crashlytics in addition to Mapbox?

No.  This is strictly for use in the TestApp and development purposes and it's our goal to not have it distributed with the Mapbox Android GL SDK.  Similarly, if it turns out that this isn't possible to distribute the SDK (in binary form via Maven Central or JCenter) without Twitter Fabric then we will reconsider using Crashlytics.

The primary goal / reason for Crashlytics is to make debugging better for internal Mapbox developers until better debugging / tooling is available from Google.

Hope this helps!
