### ISSUE TITLE
Add Android Studio 1.3 NDK support

### ISSUE THREAD

**Issue by zlsa** [mapbox/mapbox-gl-native#1669]
Android Studio 1.3 (Canary channel only) supposedly has NDK integration.

**Comment by ljbade** [comment]
@zlsa we have already looked into it and current Android Studio 1.3 builds do not have C++ integration yet.

See
> As announced at Google I/O, Android Studio 1.3 will include C/C++ support as well, but that is not included in the first couple of preview builds. https://sites.google.com/a/android.com/tools/recent/androidstudio13preview1available

Closing for now. However @bleege and @kkaefer are going to keep an eye on this as we are looking to use Studio 1.3 for easier C++ debugging.

**Comment by zlsa** [comment]
Sounds good. I just wanted to make sure there was an issue for this so it wouldn't be forgotten. Thanks!

**Comment by bleege** [comment]
@zlsa Oh yeah... we're definitely going to want / need the NDK support.  Can't wait for it to be released!  :-)
