### ISSUE TITLE
determine annotation policy for > +/- 85.xxx latitude

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1671]
When we add point or shape annotations, as of https://github.com/mapbox/mapbox-gl-native/commit/bf6be3c2207aab29a15cb1764eadece03fc0e722 we now properly clamp high latitude values to avoid problems with projection. We leave the passed latitude intact, though, so data queries still work as expected. 

We need to determine render behavior, though. Per @1ec5, Apple MapKit doesn't render points at high latitude, but maintains them in `mapView.annotations` for querying. Behavior for shapes isn't known yet, but we probably want to just clip them as we do at tile edges. 

Related: https://github.com/mapbox/mapbox-gl-native/issues/1660

**Comment by jfirebaugh** [comment]
Closing. Almost two years with no action and never heard this come up in practice. Presumably the existing behavior is acceptable.
