### ISSUE TITLE
Publish Android GL Artifacts For Distrubution

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1672]
Distribution of the Android GL library will be (primarily) via Maven Central so that build tools such as Gradle and Maven can easily integrate it and it's dependencies into projects.  The current [`build.gradle`](https://github.com/mapbox/mapbox-gl-native/blob/88b3cfe37de7918723fb9ebb6b886aaec4808bcd/android/java/MapboxGLAndroidSDK/build.gradle) appears to have the necessary tools to do this, it just needs to be setup to push.  To be clear, the Android GL library will be published as an Android Library project, aka `.aar`, similar to the [Mapbox Android SDK](http://search.maven.org/#search|gav|1|g%3A%22com.mapbox.mapboxsdk%22%20AND%20a%3A%22mapbox-android-sdk%22).

For the purposes of this ticket, let's just concentrate on pushing SNAPSHOT builds from development.  Publishing official releases is a similar process that will be able to dovetail on the SNAPSHOT setup.

* [x] SNAPSHOT Release support
* [ ] Securely store Maven Central credentials so that CI server can access them
* [ ] Secure store Java Keystore used to sign artifacts so that CI server can access them
* [ ] Have CI Server automatically publish SNAPSHOTS upon successful builds

@mapbox/mobile

**Comment by ljbade** [comment]
At the same time let's also get the release build test app apk set up for signing. We will need a secure android key store on Travis

**Comment by bleege** [comment]
To clarify, an internal release test build app will be powered by (SNAPSHOT) artifact to mirror what a 3rd party implementing project would use.

**Comment by ljbade** [comment]
Something else @bleege, currently Travis builds each ABI in a seperate job. During the Maven publishing we need to collate each ABIs jniLibs files into one place before we run gradle to ensure our .aar has all the ABIs.

**Comment by bleege** [comment]
Let's look at publishing to JCenter instead of Maven Central as it's the preferred distribution point for Google these days.  It's also a super set of Maven Central based on previous research [[ 1 ]](https://github.com/mapbox/mapbox-android-sdk/issues/775) [[ 2 ]](https://github.com/mapbox/mapbox-android-sdk/issues/777).

**Comment by bleege** [comment]
According to the Bintray documentation, [SNAPSHOT builds should not be published to JCenter](https://bintray.com/docs/usermanual/whatisbintray/whatisbintray_correctandincorrectusage.html).  They can be published to the companion distribution channel of [Artifactory](http://www.jfrog.com/artifactory/) though.  Artifactory is available either as a download for on premise installation or as Saas, however there does not appear to be [free plan for Open Source projects](http://www.jfrog.com/pricing/).

In light of these details, I'm inclined to keep the Mapbox on Maven Central with Sonatype.  That and we've already gone through the pain of setting it up for the Android Raster SDK so it should be relatively quick to get it working for GL.

**Comment by bleege** [comment]
Manual Publish SNAPSHOT Process:

```sh
// Remove outdated code and .so
make clean

// Update android/java/MapboxGLAndroidSDK/gradle.properties
// Version Info  (make sure it's -SNAPSHOT)

// Build libmapbox-gl.so for all ABI
// Also runs ./gradlew --parallel-threads=4 assembleRelease
make android-all

// Update android/java/MapboxGLAndroidSDK/gradle.properties
// Credentials

// Upload artifact
cd android/java/MapboxGLAndroidSDK
../gradlew uploadArchives
```

I just finished this process (see images below).  Will attempt to integrate it into a "standalone Android app" now to see if we've got all the i's dotted and t's crossed.


![20150723-make-clean](https://cloud.githubusercontent.com/assets/989928/8856662/d0122496-3131-11e5-9c5a-b00bb1e1f3dd.png)
__make clean__

![20150723-make-android-all-abi](https://cloud.githubusercontent.com/assets/989928/8856672/dc1a2478-3131-11e5-871e-895bb9e326b1.png)
__ABIs built__

![20150723-end-of-make-android-all](https://cloud.githubusercontent.com/assets/989928/8856688/f46ce40c-3131-11e5-88fe-2f989a919c21.png)
__End of make android-all__

![20150723-aar-built](https://cloud.githubusercontent.com/assets/989928/8856691/fe6cda5c-3131-11e5-96c5-f6594f45d97d.png)
__Artifact Produced by make android-all to be uploaded to Maven Central__

![20150723-upload-snapshot](https://cloud.githubusercontent.com/assets/989928/8856710/1047efd2-3132-11e5-8dbf-5a99cbc72b4d.png)
__Artifacts, Meta, and Docs Uploaded to Maven Central__

**Comment by bleege** [comment]
Was able to confirm internally that manual build and distribution process described ^^ works for SNAPSHOTS.

**Comment by bleege** [comment]
Integration with Maven Central is working.  Will punt on CI Server specific implementation details until new CI server is chosen.
