### ISSUE TITLE
add padding to annotation tiles

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#1673]
In order to properly sort markers across tiles (#988) we need annotation tiles to also include features that are outside of the tile's boundaries, but within a certain distance of the tile edge.

This will let us clip markers to tile boundaries at draw time to avoid incorrect overlap across tiles. Since markers near edges are included in both tiles they will be drawn seamlessly. Half the marker will be drawn by one tile and half by the other. This is how the -js implementation works.

This should be done after https://github.com/mapbox/mapbox-gl-native/pull/1666 and https://github.com/mapbox/mapbox-gl-native/pull/1655 are merged.

This will fix 
![screen shot 2015-06-02 at 11 28 57 am](https://cloud.githubusercontent.com/assets/1421652/7939740/96799a1e-091a-11e5-8250-82dedc0d1415.png)

After implementing, change these two lines:
https://github.com/mapbox/mapbox-gl-native/blob/3dfa317cf9689c5bbd0994f86bdf6b068b1c6716/src/mbgl/renderer/symbol_bucket.cpp#L326
https://github.com/mapbox/mapbox-gl-native/blob/3dfa317cf9689c5bbd0994f86bdf6b068b1c6716/src/mbgl/renderer/painter_symbol.cpp#L122

**Comment by incanus** [comment]
This is stale, right @ansis?

**Comment by ansis** [comment]
I think this still needs to be done. But it is unblocked now
