### ISSUE TITLE
While panning, location indicator wiggles significantly more on android compared to iOS (Android).

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1676]
Filing this issue for tracking purposes.
While panning, location indicator wiggles a lot more on Android compared to iOS.  Maybe whatever changes were done for the following needs to be migrated for Android as well.

https://github.com/mapbox/mapbox-gl-native/issues/1439

**Comment by 1ec5** [comment]
#1439 was duped to #1125, which is still open. #1582 will get us to parity with MapKit by using Core Animation. Does Android have anything similar?

**Comment by ljbade** [comment]
@1ec5 there is currently no filtering of the compass data. It is updating the screen as frequently as we get sensor data. We need to implement some sort of rate limit or other data filtering.

**Comment by 1ec5** [comment]
Would it be necessary to throttle the user location updates if the user dot animated to each location instead of blitting there?

**Comment by ljbade** [comment]
The compass and GPS locations are separate data sources. Android already limits location to once a second so we need to do something similar with the compass.

**Comment by ljbade** [comment]
This is still a problem even after @bleege recent changes.

@incanus How did you speed up the map/location marker sync?

**Comment by erf** [comment]
@ljbade i created a pull request now  #2065 regarding compass filtering. but after i had added the filtering like in a previous pull request, i saw that the FAB does not toggle into Follow mode. I guess @bleege is in the middle of some refactoring here, but would be nice if the filtering could be included if you test that it is ok. Thanks.

**Comment by incanus** [comment]
We need to insert the routine which updates the user dot's location on screen between these two lines: 

https://github.com/mapbox/mapbox-gl-native/blob/fa18f1afd0f2c736e09ffc8989548fdc0bafdf3c/android/cpp/native_map_view.cpp#L710-L711

Per https://github.com/mapbox/mapbox-gl-native/issues/1125, `renderSync` draws the current GL frame, then `nudgeTransitions` updates the `Transform`, which affects any subsequent geo/screen conversions. If the user dot placement happens **not** between those two, it is using a `Transform` for the placement conversion that is not in sync with the GL draw.

**Comment by ljbade** [comment]
@incanus Aha! Thanks for that pointer! I'm going to figure this one out

**Comment by bleege** [comment]
Bumping to `0.2.0`.

@ljbade Any progress on this?

**Comment by ljbade** [comment]
@bleege not yet, will pick this up after `0.1.0`

**Comment by incanus** [comment]
When we clean this up to be driven by frame updates (building on https://github.com/mapbox/mapbox-gl-native/pull/2255), we should be sure to clean [this stuff](https://github.com/mapbox/mapbox-gl-native/pull/2255#issuecomment-137632810) up: 

> I think the idea with `updateMap()` on Java side was related to triggering the UI to fetch updated GPS coordinates and update the location of the GPS marker dot (it made sense at the time to use same code for map pan/zoom updates).
