### ISSUE TITLE
Homebrew formula for mbgl

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#1677]
It should be nice to have both Mapbox GL application and library available via [Homebrew](http://brew.sh):

> $ brew install mbgl

This sounds like a good option for developers to satisfy pkg-config dependencies from eg. https://github.com/tmpsantos/qmapboxgl - though mason might also resolve that already.

**Comment by tmcw** [comment]
I can take a stab at this - I wrote the homebrew formula for tippecanoe recently and as long as our dependencies are homebrew-installable this should be possible.

That said, @brunoabinader to support the goal of having mapbox-gl-native installable as a _library_, I'd expect there to be a `make install` task in the project and existing docs for how to use it as a library. That would have to come first.

**Comment by tmcw** [comment]
Draft: https://github.com/Homebrew/homebrew/compare/master...mapbox:mapbox-gl-native?expand=1

**Comment by jfirebaugh** [comment]
Closing; not currently a priority and we plan to bring Qt in as a platform alongside iOS/Android/node.
