### ISSUE TITLE
Missing libmgl pkg-config info

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#1678]
It might be already there, but I couldn't easily find it.

**Comment by tmpsantos** [comment]
I'm maintaining it separately on my Debian package branch:
https://github.com/tmpsantos/mapbox-gl-native/tree/debian-package

You can add the PPA here:
https://launchpad.net/~tmpsantos/+archive/ubuntu/mapbox-gl

And get a pkg-config file by installing the `libmbgl-dev` package.
