### ISSUE TITLE
Glyph bitmap overflow, disappearing labels on rotation

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1681]
With #1666 in iOS 8.3 on an iPhone 6, when rotating the map, I’m seeing CJK labels disappear instead of flipping vertically:

![img_0291](https://cloud.githubusercontent.com/assets/1231218/7967436/eba1dfa0-09de-11e5-8fee-4f7ba22942e9.PNG)
![img_0292](https://cloud.githubusercontent.com/assets/1231218/7967481/2fd9e6d6-09df-11e5-9a4d-440652a6e60c.PNG)
![img_0293](https://cloud.githubusercontent.com/assets/1231218/7967482/2fde40c8-09df-11e5-9390-41dc393c849d.PNG)

Doesn’t reproduce [in mapbox-gl-js](https://www.mapbox.com/mapbox-gl-styles/#18.35/35.66916/139.75906/38.9) (Emerald style) in Firefox 40.0a2 (2015-06-02).

/cc @ansis

**Comment by 1ec5** [comment]
Although I wouldn’t discount the possibility that it has something to do with the corrupted glyph in that POI label in the center of the map.

**Comment by 1ec5** [comment]
I was also seeing the issue on Vietnamese labels (Latin with diacritics). But after restarting the app, I’m no longer seeing either the glyph corruption (completely misdrawn and flashing on every redraw) or the labels disappearing – the labels flip as expected. So it probably is related to the glyph corruption.

**Comment by 1ec5** [comment]
When I do return to the problematic POI, I get lots of this in the console:

```
2015-06-03 11:09:20.093 TeaPod[10815:1731778] [ERROR] [OpenGL]: glyph bitmap overflow
```

**Comment by mikemorris** [comment]
We've seen this with Chinese labels before (can't find the issue though), but we're essentially overstuffing the glyph atlas, because the glyphs needed are spread across so many "glyph tiles" (blocks of 256 codepoints), and we attempt to add all the bitmaps for a requested glyph tile to the atlas, even if only one or two glyphs in that block are actually needed for rendering at the moment.

**Comment by jfirebaugh** [comment]
We have several issues about sprite atlas overflow, but maybe not one about glyph atlas overflow specifically. However there is #1444, which is likely compounding the issue.

**Comment by 1ec5** [comment]
In case it wasn’t clear from the screenshots I took in https://github.com/mapbox/mapbox-gl-native/issues/1681#issue-84693624, this is what glyph overflow currently looks like:

![glitch](https://cloud.githubusercontent.com/assets/1231218/16787727/5e5d454e-4853-11e6-96ce-068f78e3d1d6.gif)

It’s easy to reproduce this issue by panning around a city such as Tapei, in which many street names and POIs have Chinese names but not English names.

mapbox/mapbox-gl-js#141 is the equivalent bug in Mapbox GL JS.

**Comment by 1ec5** [comment]
What’s the state of this issue now that #5908 has landed? I’m unable to reproduce the issue anymore, though I haven’t tried very thoroughly. Do we still need this ticket around?

**Comment by amyleew** [comment]
Haven't noticed it again @1ec5. Let's close for now, we can reopen if this becomes an issue in the future
