### ISSUE TITLE
Vertical CJK labels

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1682]
CJK labels running along north-south roads (or roads that go from top to bottom due to map rotation) should orient glyphs vertically so that one can read the labels without tilting one’s head. Since the map can be rotated arbitrarily, it’s easy to wind up in a situation where all the road labels are vertical. CJK makes it possible to maintain legibility in such configurations.

/cc @ansis @nickidlugash @peterqliu @mayagao @friedbunny @mikemorris

**Comment by friedbunny** [comment]
An example from Yahoo JP, near Tokyo Station. Notice that even roman characters can be drawn vertically.

![screen shot 2015-06-03 at 1 23 11 pm](https://cloud.githubusercontent.com/assets/1198851/7970668/7cfba458-09f4-11e5-95de-e875074ccebd.png)

http://yahoo.jp/2RqUBc

**Comment by nickidlugash** [comment]
@mikemorris is planning to add vertical advance information [here](https://github.com/mapbox/node-fontnik/blob/harfbuzz/proto/glyphs.proto#L24) to allow this.

**Comment by mikemorris** [comment]
> Note that only a few font formats provide vertical metrics. You can test whether a given face object contains them by using the macro FT_HAS_VERTICAL, which returns true if appropriate.

https://www.freetype.org/freetype2/docs/tutorial/step2.html is interesting and has more details on vertical glyph metrics and what we would need to include in the glyph spec to support vertical layout

**Comment by 1ec5** [comment]
An implementation is nearly ready to port in mapbox/mapbox-gl-js#3438.
