### ISSUE TITLE
Add ARM v5, x86-64 and MIPS 64 support to Travis

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#1683]
Just noticed for whatever reason we don't build `arm-v5`, `x86-64` and `mips-64` ABIs.

**Comment by ljbade** [comment]
@jfirebaugh We probably don't want to be expanding the build matrix? If anything we could drop MIPS 32bit too.

However if we decide to implement pushing build snapshots from Travis to automate what @bleege is currently doing by hand we will need to somehow build all the ABIs on Travis. Basically https://github.com/mapbox/mapbox-gl-native/issues/1672

**Comment by jfirebaugh** [comment]
Agreed, let's avoid expanding the matrix if possible.

If we need to build all ABIs for snapshots we can try to figure out a way to do that only for certain builds.

**Comment by ljbade** [comment]
@jfirebaugh: yes I think that would be the easiest way. We can have something in the commit like [snapshot] that triggers a script that runs `make android-all` before uploading the results.
