### ISSUE TITLE
Rotation causes some labels to collide

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1689]
I’m seeing a couple labels collide:

![collision](https://cloud.githubusercontent.com/assets/1231218/7988413/1fef2a2e-0a98-11e5-9609-7bd5d9d831c0.PNG)

As soon as I change styles, that overlapping “N 4th St” label disappears, and it stays hidden if I change back to the original style (Mapbox Streets):

![uncollision](https://cloud.githubusercontent.com/assets/1231218/7988420/27d4e940-0a98-11e5-9889-4325c8b2aa70.PNG)

But if I gingerly rotate the map, the “N 4th St” label reappears, and resetting the rotation doesn’t fix the collision.

This is with the changes for #1666. Doesn’t reproduce [in mapbox-gl-js](https://www.mapbox.com/mapbox-gl-styles/#15.43/37.3453/-121.8920/1.4).

**Comment by mikemorris** [comment]
Reopening this with some new examples of collisions I've noticed from `MapMode::Still` renders with a rotation applied. I suspect these are old bugs we just never caught, not recent regressions.

**Collision between `Valley Stream`, `Hempstead` and a route marker**
![image](https://cloud.githubusercontent.com/assets/1149913/14022123/d4a36026-f1b4-11e5-8281-bc9088b4b8ad.png)

**Collision between `Point Reyes National Seashore` and a route marker, `San Francisco` and `Oakland` labels appear to collide as well**
![image](https://cloud.githubusercontent.com/assets/1149913/14022127/daa0498a-f1b4-11e5-86e8-4eded161fc6c.png)

/cc @ansis

**Comment by ansis** [comment]
@mikemorris what is the code / setup for reproducing these? can you render the images with collision boxes?

**Comment by ansis** [comment]
@mikemorris thinks https://github.com/mapbox/mapbox-gl-native/issues/1689#issuecomment-200891795 is a bug in the project that uses mapbox-gl-native.
