### ISSUE TITLE
How to set z-ordering for annotations

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#1700]
How is the z-ordering for annotations determined? I have tried adding certain annotations first and last, but each time they seem to end up below the other annotations. Is there are way to control this from the client app?

In this case, I am trying to put the larger marker with the gradient on top of the smaller green dots.

![ios simulator screen shot jun 9 2015 5 24 14 pm](https://cloud.githubusercontent.com/assets/417933/8071976/e1a046b6-0ecc-11e5-9cbd-0f5a104bf6fb.png)

**Comment by friedbunny** [comment]
@ansis's new labeling and z-indexing (#1666) should have annotations being ordered left-to-right, top-to-bottom (bottom-right behind top-most). Fairly sure we haven't done anything around custom z-indexes yet, but we'll have to.

**Comment by incanus** [comment]
Related: https://github.com/mapbox/mapbox-gl-native/issues/991

Prior art: https://github.com/mapbox/mapbox-ios-sdk/pull/491

**Comment by jfirebaugh** [comment]
Also #1728.
