### ISSUE TITLE
Add map snapshot API

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1701]
To achieve closer parity with Apple's MapKit, Mapbox GL should have a corresponsding [MKMapSnapshotter API](https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKMapSnapshotter_class/) for asynchronously loading map imagery.  This will likely just mean providing a cleaner API around the [Mapbox Static Images API](https://www.mapbox.com/developers/api/static/#images).

**Comment by 1ec5** [comment]
mbgl is already capable of static rendering. Instead of running that same code on the server, we should just expose static rendering mode in the Cocoa later.

**Comment by bleege** [comment]
^^ Cool.  Yeah, if we can accomplish this on device let's build the MapKit mirroring API that way.  :+1:

**Comment by incanus** [comment]
AFAICT this will be using one or both of [`-[UIView snapshotViewAfterScreenUpdates:]`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIView_Class/index.html#//apple_ref/occ/instm/UIView/snapshotViewAfterScreenUpdates:) and [`-[GLKView snapshot]`](https://developer.apple.com/library/ios/documentation/GLkit/Reference/GLKView_ClassReference/index.html#//apple_ref/occ/instm/GLKView/snapshot) since capturing only the `GLKView` isn't enough to also get the user dot, logo, attribution button, compass, and any annotation views. 

Performance might also be an issue here, but I guess it depends on the use cases for the snapshot (e.g. a simple dummy overlay view for transitions vs. something needing to be more performant like a blur).

**Comment by incanus** [comment]
The other interesting bit will be determining if all tiles are loaded to the best of our ability before capturing, so https://github.com/mapbox/mapbox-gl-native/issues/1804 becomes relevant.

**Comment by TWDdpigram** [comment]
I've noticed something when trying to take a snapshot of the map view.  I'm having to actually add the  map view to the a subview before taking snapshot of it.  If I were to take a snap shot immediately after adding it, the map won't be loaded and the snapshot's base map would be completely black.  I'm still able to see Mapbox logo at the bottom of the view but there is no map.  Below is the example I've used to make it work.  Is there a way to have the map load faster in order for the snapshot to not appear as a black screen or will I always have to wait for the map to load before take a snap shot?
`
-(void)viewDidLoad {
    MGLMapView *mapView = [[MGLMapView alloc] initWithFrame:self.view.frame];
    [self.view addSubview:mapView];
    
    //waiting 2 seconds so that the map will load.
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        
        //removing the interactive map.
        [mapView removeFromSuperview];
        
        UIImageView *snapShotImgView = [[UIImageView alloc]initWithImage:[self snapshot:mapView]];
        snapShotImgView.frame = self.view.frame;
        
        //adding the snapshot
        [self.view addSubview:snapShotImgView];
    });
}

- (UIImage *)snapshot:(UIView *)view {
    UIGraphicsBeginImageContextWithOptions(view.bounds.size, YES, 0);
    [view drawViewHierarchyInRect:view.bounds afterScreenUpdates:YES];
    UIImage *snapshot = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return snapshot;
}
`

**Comment by friedbunny** [comment]
@TWDdpigram Initiating the manual snapshot in [`-[MGLMapViewDelegate mapViewDidFinishLoadingMap:]`](https://www.mapbox.com/ios-sdk/api/3.1.2/Protocols/MGLMapViewDelegate.html#/c:objc(pl)MGLMapViewDelegate(im)mapViewDidFinishLoadingMap:) would probably be the fastest way to do this right now. It won’t load the map more quickly, but it should be the first instant the map is visually ready.

**Comment by jcarlos-p** [comment]
@friedbunny does _visually ready_ means all the elements in the map are already rendered on top of it? I've tried taking a snapshot of an MGLMapView using the code suggested inside of its delegate's `mapViewDidFinishLoadingMap:` and most of the time the map is drawn without many elements such as city labels and there's even the case where the map is completely blank.

Here are some examples of what I'm getting:

<img width="379" alt="atlanta" src="https://cloud.githubusercontent.com/assets/14112456/16168902/780d87da-34e7-11e6-84e5-32250c85463c.png">
<img width="377" alt="cupertino lbs" src="https://cloud.githubusercontent.com/assets/14112456/16168903/7818ac14-34e7-11e6-952b-fc3430f15f9f.png">

**Comment by friedbunny** [comment]
@jcarlos-p It appears that `-[MGLMapViewDelegate mapViewDidFinishLoadingMap:]` is being sent a tick too early. Snapshotting using [the above method](https://github.com/mapbox/mapbox-gl-native/issues/1701#issuecomment-190819164) is working for me, after inserting a zero second delay (which causes it to fire on the next run loop cycle):

```objc
[self performSelector:@selector(snapshot:) withObject:mapView afterDelay:0];
```

**Comment by jcarlos-p** [comment]
@friedbunny Can the sample code be safely executed while the app is in the background ? 

We found a problem where we execute this code but if the App is in the background, the map snapshot would come back completely black.

**Comment by friedbunny** [comment]
@jcarlos-p I wouldn’t expect MGLMapView to render anything if the app is not in the foreground. We’ve had crashes related to instantiating a GL context in the background and currently [guard against this happening](https://github.com/mapbox/mapbox-gl-native/blob/5f969e3302457804824c3e6af360c1657a44bda7/platform/ios/src/MGLMapView.mm#L371-L375).

As others have touched on on this thread, how to accomplish off-screen rendering is the main hurdle that needs to be addressed for the feature to move forward.

**Comment by jcarlos-p** [comment]
That's what I thought. Thanks for the clarification. 

We'll just put a workaround in place then.

**Comment by quicklywilliam** [comment]
@jcarlos-p just wondering if you could share your workaround for this? We also need to render our map in the background so that it can be included in a UNNotificationAttachment  (this, in turn, is a workaround for #6230 – Mapbox doesn't work in a Notification Extension). We're currently using MapboxStatic to accomplish this, but the results are not nearly as pretty and are tied to the old Classic API's/styles.

**Comment by jcarlos-p** [comment]
@quicklywilliam We had to go the static API way also :(

**Comment by friedbunny** [comment]
Accidentally closed by errant verbiage in mapbox/MapboxStatic.swift#54.

**Comment by 1ec5** [comment]
lol, if only it were so simple!

**Comment by kkaefer** [comment]
> We found a problem where we execute this code but if the App is in the background, the map snapshot would come back completely black.

iOS prohibits OpenGL operations when the application is in the background: https://developer.apple.com/library/content/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/ImplementingaMultitasking-awareOpenGLESApplication/ImplementingaMultitasking-awareOpenGLESApplication.html

**Comment by tobrun** [comment]
This happened in https://github.com/mapbox/mapbox-gl-native/pull/9891, tail work is ticketed out in #9916, #9914 and https://github.com/mapbox/mapbox-gl-native/issues/9920

**Comment by haxpor** [comment]
Just for a note for someone else trying to achieve the same thing. I have to directly use `MGLMapView` and **not** its `snapshotView(afterScreenUpdates:)`. If not, I will get black screen. Use solution as posted by friedbunny above. Thanks.
**PS**. Xcode 9.3, iOS 11, both release version and Mapbox 3.7.
