### ISSUE TITLE
NullPointerException crash in updateMap (Android)

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1703]
I've attached a screenshot of the stack trace from logcat. 

![null_pointer_exception_crash](https://cloud.githubusercontent.com/assets/8890269/8074932/a2e58208-0eed-11e5-834d-d3d71cdb45eb.jpg)

**Comment by ljbade** [comment]
Seeing this in Crashlytics.

Looks like a compass sensor update is fired before everything is ready so something in `updateMap` is `null`.

Possibly `mapView`? But that is strange as we set that right at the start.

**Comment by ljbade** [comment]
@mb12 Does this happen anymore?

**Comment by mb12** [comment]
I don't see this specific crash with the latest repo.
