### ISSUE TITLE
how to create the v6 map vector tiles from the osm data in the postgis db?

### ISSUE THREAD

**Issue by zochunhua** [mapbox/mapbox-gl-native#1704]
the mapbox-studio  cann't create the vector tiles? Is there any other tools ?

**Comment by frenos** [comment]
I got it working using Tilestache. You can use the cache-function and tilestache-seed to pre-generate tiles and use them in Mapbox-gl-(native/js).

**Comment by hanchao** [comment]
Mapzen create vector tile service  https://github.com/mapzen/vector-datasource

**Comment by jfirebaugh** [comment]
Hi -- we've got a guide covering the creation of vector tiles from a PostGIS database. [Check it out here](https://www.mapbox.com/guides/postgis-manual/).
