### ISSUE TITLE
Styles missing from style switcher in test app (Android).

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1706]
The following styles are missing from style switcher in sample test app for Android. They are available in  sample iOS test app.

    @"Bright",
    @"Basic",
    @"Outdoors",
    @"Satellite",

**Comment by 1ec5** [comment]
These styles are not officially supported by Mapbox GL at the moment. They don’t ship with Mapbox GL for iOS, either, but the iOS demo app still hard-codes them. Switching to those styles does nothing. The proper fix will be #1462.
