### ISSUE TITLE
Lots of linker warnings in Xcode 7 / iOS 9 SDK — built for newer iOS version (9.0) than being linked (8.2)

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1707]
I get 28 of these warnings when building the iosapp scheme in Xcode 7 for the iPhone 6 (9.0) simulator:

```
ld: warning: object file (/path/to/mapbox-gl-native/mason_packages/ios-8.3/libuv/0.10.28/lib/libuv.a(async.o)) was built for newer iOS version (8.3) than being linked (7.0)
```

**Comment by 1ec5** [comment]
Also reproduces in any project that incorporates Mapbox GL via CocoaPods:

```
ld: warning: object file (/path/to/ExampleProject/Pods/MapboxGL/libMapboxGL.a(async.o)) was built for newer iOS version (9.0) than being linked (8.2)
```

**Comment by AdrianaPineda** [comment]
Hi!. Any updates on this?

**Comment by 1ec5** [comment]
Looks like Mason [assumes](https://github.com/mapbox/mason/blob/8def5e5d155fa9a1d9370992abfab6d1efb52833/mason.sh#L61) you always want the latest SDK supported by your current Xcode toolchain (which is 9.0 for Xcode 7.0), rather than the SDK of the minimum deployment target (7.0). To be clear, these are only warnings, and they appear to be harmless.

/cc @kkaefer @incanus

**Comment by 1ec5** [comment]
@AdrianaPineda, the fix is in mapbox/mason#110. Once that’s merged and the submodule in this repo incorporates that fix (likely via #1962), the warnings will go away.

**Comment by AdrianaPineda** [comment]
@1ec5 thanks! :)

**Comment by jhoughjr** [comment]
Any news on this? I'm using Mapbox-ios-sdk 2.1.2 as a cocoa pod and still get these tons of warnings for all the object files.

I'd also add that warnings are not harmless and ignoring them has many disadvantages.

**Comment by 1ec5** [comment]
@jhoughjr, I’m not seeing the warnings anymore with 2.1.2 when building in Xcode 7 with the iOS 9 SDK. In the warnings you’re seeing, is the iOS version 9.0 and the linked version 8.2, or something else?

**Comment by friedbunny** [comment]
Indeed, I cannot reproduce these warnings with the [recommended podfile](https://www.mapbox.com/ios-sdk/#cocoapods).

**Comment by 1ec5** [comment]
> I'd also add that warnings are not harmless and ignoring them has many disadvantages.

Agreed. In this case, I was only recommending to be patient for mapbox/mason#110 to make it into a build, not to ignore the warnings indefinitely.

@jhoughjr, did you upgrade the Mapbox iOS SDK pod or install it into a fresh project? If you upgraded it, be sure to fully clean your project before rebuilding: hold down ⌥, then go to Product ‣ Clean Build Folder.
