### ISSUE TITLE
Arbitrary TileSources from any WMTS

### ISSUE THREAD

**Issue by drhaynes** [mapbox/mapbox-gl-native#1714]
In order to achieve feature parity with iOS/Android raster SDKs, aside from Mapbox hosted tile sources, we would also like to see the functionality to add any WMTS as a `TileSource` to the map.

Much like the `RMAbstractWebMapTileSource` functionality in the iOS SDK.

**Comment by incanus** [comment]
https://github.com/mapbox/mapbox-gl-native/issues/836 should cover this.
