### ISSUE TITLE
Image snapshot of visible map bounds

### ISSUE THREAD

**Issue by drhaynes** [mapbox/mapbox-gl-native#1715]
As per iOS raster SDK's `RMMapView` `- (UIImage *)takeSnapshotAndIncludeOverlay:(BOOL)includeOverlay` method.

This is useful for things like cached animation layers, and generation of thumbnails for saved routes, etc.

**Comment by jfirebaugh** [comment]
#1701

**Comment by 1ec5** [comment]
In the meantime, as a workaround, you can call `-[MGLMapView snapshotViewAfterScreenUpdates:]`, but the resulting snapshot will include any ornaments that are visible on-screen (compass etc.).
