### ISSUE TITLE
Rename kReachabilityChangedNotification

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#1717]
This is a popular class to include in client apps. By including it in the libMapboxGL.a , but not including the header in the Headers directory prevents client app from using it. Also, if a client tries to include its own version of reachability, duplicate symbols build errors are the result.

**Comment by 1ec5** [comment]
#759 renamed Mapbox GL’s copy of Reachability to MGLReachability, which allows the client to include their own version of Reachability without triggering duplicate symbol warnings. Reachability is a dependency of Mapbox GL but kind of out of scope for its public API.

**Comment by picciano** [comment]
Looks like the problem comes from this const in reachability.h:
`extern NSString *const kReachabilityChangedNotification;`

The workaround would either be for the client app to rename this, or rename the one in MGLReachability.
