### ISSUE TITLE
CompassView is part of MainActivity not MapView in Android (Feature or Bug).

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1719]
CompassView for android is part of test app (MainActivity) in android. This is different from iOS, where in it is part of the SDK. 
Is this difference between the two platforms intentional?

**Comment by ljbade** [comment]
This was already on my work list for this week. We will have the GPS marker part of the SDK in the Android beta.

**Comment by mb12** [comment]
Is it possible to share the internal target date/month for Android beta?

**Comment by bleege** [comment]
This is done as of #1940 .
