### ISSUE TITLE
Device rotation causes crash on Android.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1721]
- This is consistently reproducible on Nexus S.
- The crash is intermittent on Note 3.

**Comment by zugaldia** [comment]
In case it helps, I can't reproduce this with current master on a Nexus 5. The map flickers with device rotations, but doesn't crash.

**Comment by ljbade** [comment]
@mb12 Do you have a crash log.

**Comment by mb12** [comment]
Is crashlytics automatically set up with the latest set up? Or do I need to set up an account etc.
With the latest repo, I am running into #1941 .

**Comment by ljbade** [comment]
@bleege re crashlytics? ^

**Comment by bleege** [comment]
@mb12 You'll need [to setup your own Crashlytics account and access tokens](https://github.com/mapbox/mapbox-gl-native/issues/1668#issuecomment-123828855) to get this to work on your end.

**Comment by tobrunvannuland** [comment]
Reproducible with following setup:
Genymotion - Google Nexus 5.0.0 image - 0.0.1-SNAPSHOT

Actions:
Open app with MapView, trigger an orientation change. 

Problem:
Field operation on invalid stack indirect reference table or invalid reference: 0x0 in call to GetDoubleField from void NativeMapView.nativeSetLatLng() while calling MapView.onCreate.

[Full Stacktrace](http://pastebin.com/Asewnem9) - [Code](https://github.com/tobrunvannuland/mapbox-gl-native/tree/playground/android/java/MapboxGLAndroidPlaygroundApp)

**Comment by ljbade** [comment]
Thanks @tobrunvannuland.

I suspect there is a `null` `LatLng` being passed to `setCentreCoordinate` during the restoration of the saved instance state of the View.

This would be saved before rotation and tear down of the activity by Android, and restored after. So somehow it is saving a `null`.

I will see if I can reproduce the rotation crash locally.

**Comment by ljbade** [comment]
Doesn't crash locally but picked up some bugs in #2090

**Comment by tobrunvannuland** [comment]
@ljbade FYI: I'm not setting any location programmatically, 
I'm handling ActivityLifeCycles callbacks [here](https://github.com/tobrunvannuland/mapbox-gl-native/blob/playground/android/java/MapboxGLAndroidPlaygroundApp/src/main/java/com/mapbox/mapboxgl/playgroundapp/controller/MapViewController.java) and after onCreate:

mMapView.setStyleUrl(Style.STREETS_V7);
mMapView..removeAllStyleClasses();

**Comment by ljbade** [comment]
Taking another look at this.

@tobrunvannuland does it happen in the TestApp or only your PlaygroundApp?

**Comment by ljbade** [comment]
Interesting recreated it in PlaygroundApp with latest code from master.

**Comment by ljbade** [comment]
Looks it is definitely being passed a `null` saved `LatLng` from  `savedInstanceState`

**Comment by ljbade** [comment]
Turns out this is a bug in your app @tobrunvannuland.

Specifically here: https://github.com/tobrunvannuland/mapbox-gl-native/blob/153361fe24ce16f770707067c7cef92e431b8116/android/java/MapboxGLAndroidPlaygroundApp/src/main/java/com/mapbox/mapboxgl/playgroundapp/activity/BaseActivity.java#L58

See http://stackoverflow.com/questions/30549722/onsaveinstancestate-is-not-getting-called-after-screen-rotation.

Replacing `public void onSaveInstanceState(final Bundle outState, final PersistableBundle outPersistentState)` with `public void onSaveInstanceState(final Bundle outState)` fixes the crash.

**Comment by tobrunvannuland** [comment]
@ljbade well spotted, sorry to start you off on the wrong foot.
But I'm also able to reproduce this with the sample app.
 
Actions:
Do heavy scroll, rotate device before animation stops.

**Comment by ljbade** [comment]
@tobrunvannuland Can you open a new ticket for that bug?
