### ISSUE TITLE
Unable to Compile iOS and OSX Builds on Latest Commit

### ISSUE THREAD

**Issue by hallahan** [mapbox/mapbox-gl-native#1722]
I am attempting to build from source the MapboxGL source and sample iOS project via `make iproj`.

It looks like, according to the instructions, that I just run: 

git submodule init
git submodule update
make iproj

When `make iproj` finishes, it pops open XCode with a project. I then put in the Mapbox Access Code as per the README.

I then try to build for the iPhone 6 Simulator. I select the iosapp to be run.

When I try and build, I get the a hand full of Parse issues that halts the build:

![screenshot 2015-06-13 16 35 01](https://cloud.githubusercontent.com/assets/556367/8146407/7b25357e-11ea-11e5-893a-258e8a1b171c.png)
![screenshot 2015-06-12 17 08 06](https://cloud.githubusercontent.com/assets/556367/8146417/0d1f0e6e-11eb-11e5-93d2-78ed50132edb.png)

I have successfully compiled the OSX project via `make xproj` in the past #512 . So, I went a head and did a `make clean` and gave that a try. I am getting the same errors for the osxapp.

I am using XCode 6.1.1. Is that the problem? Should I be on a newer XCode?

**Comment by hallahan** [comment]
I updated to XCode 6.3.2 and am having the same error.

**Comment by friedbunny** [comment]
Updating to Xcode 6.3.x should have fixed this issue, in my estimation.

**Comment by 1ec5** [comment]
f46328655e027bf490692fcde4aab770912aac8d requires Xcode 6.3 or later. I guess a425df0f95f5f0088444b8ebc67708756ff962aa was premature; the compatibility shim is needed for folks still using older Xcodes, even if Travis is on something newer.

**Comment by 1ec5** [comment]
This raises an interesting question: independently of iOS SDK version, how far back should our Xcode support go? For instance, should we continue to support 6.0–6.2 after 7 comes out? Between #1723 and #1711, supporting older Xcodes is increasingly going to muck up the code base. Two compiler features are manageable, but more than that starts looking tough to justify.

/cc @incanus @jfirebaugh

**Comment by hallahan** [comment]
I cleaned and tried again. Success! Thanks @1ec5 for jumping on this so fast!

BTW, now that it works, its amazing how easy it is to build!

![screenshot 2015-06-14 12 40 51](https://cloud.githubusercontent.com/assets/556367/8150159/f330a212-1292-11e5-930b-5cb4ec9b3e9a.png)

**Comment by incanus** [comment]
I am picturing Xcode support similar to OS’s — current minus one. So, currently Xcode 6.3 and 6.2, with investigations into 7.0, and soon 6.4 will drop, meaning 6.3 and 6.4; eventually 7.0 and 6.4.
