### ISSUE TITLE
More descriptive error when trying to load custom styles

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#1724]
Trying to load a legacy custom style:

```objc
mapView.styleUrl = [NSURL URLWithString:@"mapbox://username.stylehash"];
```

... returns a 404 instead of informing developers that their style isn't compatible with GL.

**Comment by jfirebaugh** [comment]
There's now a `Response::NotFound` enum value that can be used to implement this cleanly.
