### ISSUE TITLE
add support for geodesic polylines (and thus great circles)

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1726]
We did this before in our raster SDK here: 

https://github.com/mapbox/mapbox-ios-sdk/blob/edbe9905299ddbf8b32e41d8978b7b3265eef8f8/MapView/Map/RMGreatCircleAnnotation.m

Demo: https://vimeo.com/73482728

This uses a ~100 segment polyline to approximate a curved one and looks good. But we probably want to do this at the C++ level and wrap it in client APIs? 

Relatively low priority.

**Comment by tmcw** [comment]
@bleege @1ec5 are there built-in great circle line constructors in MapKit or Google Maps? If not, would it be okay to implement this outside of core?

**Comment by 1ec5** [comment]
MapKit [supports circles](https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKCircle_class/index.html#//apple_ref/occ/cl/MKCircle); we're tracking an equivalent in #2167.

We don't have an answer for implementing anything "outside of core" at the moment. There's no plugin system, but one could be fashioned out of CocoaPods subspecs. (There's no equivalent concept for Carthage, Fabric, or manual installation.)

**Comment by tmcw** [comment]
I'll implement this in Swift as a learning exercise.

**Comment by bleege** [comment]
@tmcw Nope on Android either.  That said, I think there's some confusion about "outside of core" means here.  We'd likely want to bake the math part into Core GL (aka C++ level that @incanus talked about above) and then have iOS and Android bindings in the regular SDKs and not standalone libraries that would be distributed via CocoaPods or Maven Central.  Make sense?

**Comment by 1ec5** [comment]
> But no, I think support for geodesic polylines on iOS is limited to the legacy Mapbox iOS SDK and possibly some niche libraries.

Correction: MapKit supports geodesic polylines with the [MKGeodesicPolyline](https://developer.apple.com/library/prerelease/ios/documentation/MapKit/Reference/MKGeodesicPolyline_class/index.html) class.

**Comment by 1ec5** [comment]
@jfirebaugh, would geometry.hpp need to support geodesic polylines as a separate geometry type, or could it be treated as a special case of a line string?

**Comment by kkaefer** [comment]
See https://github.com/mapbox/mapbox-gl-native/pull/6940 / https://github.com/mapbox/mapbox-gl-native/pull/6940 for a potential alternative.

**Comment by captainbarbosa** [comment]
Is this something that we would still consider implementing?

**Comment by mikaelhellqvist** [comment]
@captainbarbosa I've just pushed a calculation of great circles to GitHub. Feel free to use that: https://github.com/mikaelhellqvist/GreatCircle/tree/master
