### ISSUE TITLE
add support for multipolygons and polygon interior holes

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1729]
Punted from #1655. Will need to be exposed in `MGLPolygon` as well on iOS.

**Comment by jfirebaugh** [comment]
[GeoJSON sources](https://github.com/mapbox/mapbox-gl-native/pull/2161) support the full range of GeoJSON geometries. However if we want to continue expanding the annotations API, we could support this there too.

**Comment by Zakay** [comment]
+1 really need this!

**Comment by TYRONEMICHAEL** [comment]
+1

**Comment by maciekish** [comment]
+1

**Comment by dariav** [comment]
+1

**Comment by MaximAlien** [comment]
+1

**Comment by aemchuk** [comment]
+1 Will be very useful

**Comment by caHarkness** [comment]
We have switched from Google Maps to Mapbox for the rendering speed of polygons, but this feature is essential. We absolutely need holes!

**Comment by nealsanche** [comment]
+1 I am currently working with a mapping app with very complex polygons with holes that Google Maps API is stumbling on quite profoundly. I'd dearly love to replace it with MapBox and then found out that holes are not currently supported. If I have to, I'd work to contribute a PR to the project so that this could be supported. Would you please contact me, so that I might be about to assess the work that might be involved in making that happen?

**Comment by 1ec5** [comment]
#5110 adds support for holes in polygons to the iOS and OS X SDKs. Note that, unlike in MapKit, a MGLPolygon cannot be nested more than one level deep; a concentric polygon, as it were, would be represented by an MGLMultiPolygon, which currently cannot be added to the map as a single annotation. True multipolygon support will have to wait for #5158.

**Comment by nealsanche** [comment]
Last night I was able to render a polygon with holes on Android. Added the
API for adding holes to Java. Processed it in the JNI layer, and added
support in the rendering for the new data.

On Fri, May 27, 2016, 1:35 AM Minh Nguyễn <notifications@github.com> wrote:

> #5110 <https://github.com/mapbox/mapbox-gl-native/pull/5110> adds support
> for holes in polygons to the iOS and OS X SDKs. Note that, unlike in
> MapKit, a MGLPolygon cannot be nested more than one level deep; a
> concentric polygon, as it were, would be represented by an MGLMultiPolygon,
> which currently cannot be added to the map as a single annotation. True
> multipolygon support will have to wait for #5158
> <https://github.com/mapbox/mapbox-gl-native/issues/5158>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/mapbox/mapbox-gl-native/issues/1729#issuecomment-222071139>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFHsyc1aVVW4RDYPUcEFNYXJt4eMgfy2ks5qFpCagaJpZM4FD7gp>
> .
>

-- 
Robots and Pencils Inc | 1507 14th Ave SW Calgary AB T3C 0W4
You can unsubscribe from the Robots and Pencils mailing lists by clicking 
here. <https://robotsandpencils.com/contact/unsubscribe.html>

**Comment by 1ec5** [comment]
That's great, @nealsanche! Would you mind posting a pull request so we can consider your changes?

**Comment by nealsanche** [comment]
Absolutely. I will do that this morning.

On Fri, May 27, 2016, 9:35 AM Minh Nguyễn <notifications@github.com> wrote:

> That's great, @nealsanche <https://github.com/nealsanche>! Would you mind
> posting a pull request so we can consider your changes?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/mapbox/mapbox-gl-native/issues/1729#issuecomment-222162631>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFHsyY136ktyyFXW4x3Bjdl8T5bnyJQxks5qFwEegaJpZM4FD7gp>
> .
>

-- 
Robots and Pencils Inc | 1507 14th Ave SW Calgary AB T3C 0W4
You can unsubscribe from the Robots and Pencils mailing lists by clicking 
here. <https://robotsandpencils.com/contact/unsubscribe.html>

**Comment by nealsanche** [comment]
Okay, I've added a PR: https://github.com/mapbox/mapbox-gl-native/pull/5170

**Comment by nealsanche** [comment]
Anyway, I'm sure after seeing that PR you'll want to re-implement it. But it gets me past the hurdle I was working though.

[Screenshot](https://www.dropbox.com/s/4m4u3cm6o5fuy25/Screenshot_20160527-092539.png?dl=0)

**Comment by 1ec5** [comment]
#5110 has been merged and is expected to be in iOS SDK v3.3.0-beta.1 and the next OS X SDK release. Leaving this issue open for Android.

**Comment by jfirebaugh** [comment]
Both polygons, multipolygons, and multiline strings are supported by the core API as of #5200.

**Comment by ivovandongen** [comment]
Removed the current milestone as this requires breaking changes to the api

**Comment by incanus** [comment]
Just to clarify, we have interior hole support in iOS as of de905ab64c34e0fd8e35603c4f4fc338d76f89b2.

**Comment by cvance** [comment]
will this be released in 4.2.0?

**Comment by 1ec5** [comment]
No, this feature is now scheduled for v5.0.0, apparently with the expectation that adding support for multipolygons would be a breaking change.

In my opinion, polygon hole support could trivially be added beforehand in v4.x via `getHoles()` and `setHoles()` methods on `com.mapbox.mapboxsdk.annotations.Polygon`, for compatibility with `com.google.maps.model.Polygon`. The underlying core support is already in place.

**Comment by paulVulog** [comment]
@zugaldia  Any update on it ? I was waiting for v5.0.0 to fixit  but looks like it is no more the case...

**Comment by 1ec5** [comment]
#7397 is the latest attempt, but someone more familiar with Android than I will need to adopt it.

**Comment by 1ec5** [comment]
Fixed on Android in #8557.
