### ISSUE TITLE
Podspec 0.3.5 does not work

### ISSUE THREAD

**Issue by webventil** [mapbox/mapbox-gl-native#1733]
When using the latest podspec version by pointing on the git repo it seems not to work. The library won't be downloaded correctly even though `pod install`ends successfully. No header files and libraries are embedded. 
```
use_frameworks!
pod 'MapboxGL', :git => 'https://github.com/mapbox/mapbox-gl-native'
```

**Comment by incanus** [comment]
Correct. You need to point at the podspec itself with `:podspec` and the raw GitHub path to `ios/MapboxGL.podspec`. This is encompassed in https://github.com/mapbox/mapbox-gl-native/issues/1437.
