### ISSUE TITLE
Shape annotations cause console spew — layer does not have buckets

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1735]
I’m getting occasional console spew as I play around with shape annotations, both in iosapp and in a separate app I’m experimenting in:

```
[WARNING] [ParseTile]: layer 'com.mapbox.annotations.shape.20' does not have buckets
```

/cc @incanus

**Comment by tmpsantos** [comment]
Should have been fixed by #1736.
