### ISSUE TITLE
support polygon annotation stroke widths

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1737]
Blocked upstream by https://github.com/mapbox/mapbox-gl-style-spec/issues/223. Currently we just have fill outlines, which are very faint and with non-adjustable stroke width. 

Workaround for now is adding a closed polygon annotation for fill, then a closed polyline (or two) with stroke atop, such as in https://github.com/incanus/WWDSee/blob/35c7c19922d7d339d5033dca99085232a5384b4f/WWDSee/ViewController.swift#L235-L244.

**Comment by tkrajacic** [comment]
What is the plan on styling those overlays in general?
Wouldn't it be great to be able to style them the same way as the vector tile sources in Mapbox Studio (using a stylesheet)? (*Answer:* Yes it would)
I am not sure if this would work with the current rendering pipeline.

This would be awesome for example: I am thinking about a fat semi-transparent stroke on the outline, clip it to the polygon to have basically an 'inside' stroke, then add another thin opaque stroke.

With Apple's MapKit you can draw pretty much anything in your overlays (using CoreGraphics) iirc.

Just thinking out loud here. Not sure if this is what you have in mind for overlays.

**Comment by ljbade** [comment]
This ticket is superseeded by https://github.com/mapbox/mapbox-gl-native/issues/837 which will allow the full range of style properties.
