### ISSUE TITLE
Port circle render type (v8 styles)

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1740]
We need to port the [point symbol type](https://github.com/mapbox/mapbox-gl-style-spec/issues/276) to C++. This type will be able to render plain circles with arbitrary color, which is very useful for visualizing many small features that don't require a particular icon.

There is a [JS implementation](https://github.com/mapbox/mapbox-gl-js/pull/1241) already which contains the shaders and a general outline of what the feature will look like. Porting it includes:

- Parse the stylesheet into the correct structures (see style spec for how the JSON looks like)
- When parsing vector tiles into buckets, generate the OpenGL buffers required for rendering
- When rendering, add code that renders the buffers with the correct shaders
- Add tests for correct bucket creation (may not exist in JS yet)
- Add visual rendering tests (may not exist yet in the test suite)

**Comment by jfirebaugh** [comment]
⇢ #1766
