### ISSUE TITLE
`Error: libstdc++.so.6: version `GLIBCXX_3.4.20' not found`

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#1741]
I'm getting the following error after installing the `mapbox-gl-native@1.1.1`:

```
Error: /home/travis/build/mapbox/api-gl/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/travis/build/mapbox/api-gl/node_modules/gl-maps/node_modules/tilelive-gl/node_modules/mapbox-gl-native/lib/mapbox-gl-native.node)
```
Link to [failed build can be found here](https://magnum.travis-ci.com/mapbox/api-gl/builds/12827381#L722).

/cc @mikemorris @jfirebaugh

**Comment by jfirebaugh** [comment]
@bsudekum This should be filed in https://github.com/mapbox/node-mapbox-gl-native.
