### ISSUE TITLE
Show annotation's callout view automatically if title is set

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#1743]
If an annotation has its `title` property set, tapping the annotation should present the callout automatically, without having to manually return true in the `mapView:annotationCanShowCallout:` delegate method.

```objc
- (void)viewDidLoad {
    ...

    // Declare the marker `hello` and set its coordinates, title, and subtitle
    MGLPointAnnotation *hello = [[MGLPointAnnotation alloc] init];
    hello.coordinate = CLLocationCoordinate2DMake(40.7326808, -73.9843407);
    hello.title = @"Hello world!";
    hello.subtitle = @"Welcome to my marker";
    
    // Add marker `hello` to the map
    [mapView addAnnotation:hello];
}
```

```objc
// Allow markers callouts to show when tapped
- (BOOL)mapView:(MGLMapView *)mapView annotationCanShowCallout:(id <MGLAnnotation>)annotation {
    return YES;
}
```

/cc @incanus @1ec5

**Comment by friedbunny** [comment]
MapKit will display the callout automatically on tap, but only if the marker hasn't been otherwise customized.

**Comment by incanus** [comment]
I don't think we want this — not all point makers should show a callout, which is why the API exists. 

https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKAnnotationView_Class/index.html#//apple_ref/occ/instp/MKAnnotationView/canShowCallout

Lots of markers will have titles which may have other uses. I think this should remain opt-in.

**Comment by picciano** [comment]
I would agree we Incanus here. We use markers that have a title, but should not display a callout. We are using the title to determine the symbolName. Maybe there should be a better way to do that, but that's another question.

**Comment by friedbunny** [comment]
OK, I'm convinced that we're good here for now. Hopefully we can revisit this and consider using a `canShowCallout` property.

**Comment by incanus** [comment]
Yeah, per chat, when we have annotation _views_ and not just models, I see this moving from a delegate method to the view class like Apple's (`MKPointAnnotation` :point_right: `MKPinAnnotationView.canShowCallout`).
