### ISSUE TITLE
Map is not redrawn after setClasses / addClass on Android

### ISSUE THREAD

**Issue by erf** [mapbox/mapbox-gl-native#1744]
Map is not redrawn with the new theme after setClasses / addClass on Android.

I have to zoom before changes happens.

**Comment by erf** [comment]
The following solves the problem for me:
<pre>
   // force redraw with new theme
   new Handler().postDelayed(new Runnable() {
      @Override
      public void run() {
         mMapFragment.getMap().setZoomLevel(mMapFragment.getMap().getZoomLevel());
      }
   }, 0);
</pre>

**Comment by vespakoen** [comment]
+1 Seeing the same here, setting the zoomlevel works for now..

**Comment by ljbade** [comment]
@incanus I assume this works on iOS? I wonder what the difference is between Android and iOS they both just call the `Map` functions?

**Comment by bleege** [comment]
Bumping to `0.2.0`.

**Comment by tobrun** [comment]
As indicated in #2875 style classes are obsolete, closing down.
