### ISSUE TITLE
Labels along lines cross tile boundaries

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-native#1747]
These tests were done on the iOS simulator on my Macbook Pro Retina 15in. Not sure if it matters, but the first screenshot is of over-zoomed tiles; the second is of not over-zoomed tiles.

/cc @ansis @nickidlugash

![screen shot 2015-06-17 at 6 04 43 pm](https://cloud.githubusercontent.com/assets/5607844/8220097/579e2e7c-151d-11e5-97c4-44b1ccbc5572.png)

![screen shot 2015-06-17 at 6 15 51 pm](https://cloud.githubusercontent.com/assets/5607844/8220098/579e5564-151d-11e5-97a5-130e9454ab9d.png)

**Comment by ansis** [comment]
I think these are overscaled zoom levels (15+) and the tile boundaries are for annotations or something else.

**Comment by ansis** [comment]
And the second image is this issue: https://github.com/mapbox/mapbox-gl-js/issues/1072

We only check if there is enough room along the feature before the edge of the tile. We don't actually check if the box crosses a tile boundary yet.
