### ISSUE TITLE
Get Core GL C++ Into Android Project

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1753]
In order to support C++ / NDK debugging in Android Studio and streamline CI builds and artifact publication we need to refactor the current `make android` process to integrate the Core GL C++ project files into the Gradle managed Android project.  The current process compiles the Core GL into `.so` files based on ABI and places them into `jniLibs` for the Gradle build process to then use as a separate step, while the new process will copy the uncompiled C++ files into `jni` and make (the Gradle driven) Android NDK responsible for compiling them and linking them via JNI to the Android code along with building the SDK as whole in one step.  This process will essentially mirror what is done for iOS and Xcode with `make iproj` where Xcode is responsible for all the compilation and linking.

**Unknowns**
- Will custom `Android.mk` files be needed or will the built in NDK controls in Gradle be enough.
- Will current GL Makefile process work or will refactoring to use something like [Bazel](http://bazel.io/) be needed?

**Resources**
- [Android Studio, gradle and NDK integration by Xavier Hallade](http://ph0b.com/android-studio-gradle-and-ndk-integration/)
  - I've personally found this article to be incredibly helpful for configs, architectures, and overall customization.
- [Secrets of Android.mk](http://android.mk/)
- [Using custom Android.mk with Gradle/Android Studio](http://blog.gaku.net/ndk/)
- [NDK With Android Studio](http://www.shaneenishry.com/blog/2014/08/17/ndk-with-android-studio/)
- [Building An Android Project With Djinni (Dropbox)](https://medium.com/@thomasnguyen_21504/building-an-android-project-with-djinni-56266cfae83a)

@mapbox/mobile @mapbox/gl

**Comment by bleege** [comment]
What Before and After *should* look like:

![20150618-current-jnilibs-to-new-jni](https://cloud.githubusercontent.com/assets/989928/8235542/30b913a4-15a8-11e5-95a5-6116f89df490.png)

**Comment by mb12** [comment]
This would be really awesome when it is available. Is this already working in your local repo?
In this year's Google IO, they announced that Jetbrains NDK plugin will be available for free for Android development.

https://www.youtube.com/watch?v=f7ihSQ44WO0

**Comment by ljbade** [comment]
Yeah I look forward to having everything in Studio too. At one point in time (June last year) I did actually have everything built with a custom `Android.mk` file but a lot has changed since.

Let me know if you need help with this @bleege. First I would try getting NDK to compile all the C++ files. If we can get that to work then the hardest bit will be getting everything linked nicely.

**Comment by bleege** [comment]
@ljbade Yeah, it'd be fantastic to get your :eyes: on this.

> First I would try getting NDK to compile all the C++ files. 

Agreed.  It's a little unclear to me how all the C++ and related dependencies would be compiled via NDK.  I assume that [Mason](https://github.com/mapbox/mason) has to stay in the mix somewhere?  Can you sketch out how you think this would work on a branch?

**Comment by ljbade** [comment]
Hmm yeah we going to need mason. Can't think off the top of my head the best way to do this.

Perhaps we are going to need to create a series of custom Gradle tasks that somehow add dependencies and etc automatically from mason command calls into the NDK settings in the Gradle state.

**Comment by ljbade** [comment]
This is my thinking so far:
- gradle has custom task that copies C++ files to jni dir, perhaps by calling a gyp command that does this from the gyp files (it may be better to symlink though so you can edit the files in Android Studio?)
- gradle has another custom task that runs the mason setup - this will install the deps, copy the libs to the jniLibs dir and also insert the required compiler and linker flags into the NDK compile config
- gradle then uses normal NDK process to compile jni dir and link with jniLibs

**Comment by ljbade** [comment]
@kkaefer How hard would it be to get gyp to copy or symlink the C++ files in the Android target instead of compiling them?

Is it also possible to capture the compile and linker flags set in gyp? Berhaps echoing them to stdout then gradle can grab them

**Comment by kkaefer** [comment]
Can we get around copying the files into the jni dir by specifying the paths in a (generated) `Android.mk` file?

**Comment by bleege** [comment]
@kkaefer Yep.  We can point the NDK at what ever path we want to.  The only potential issue is if the debugger will work like this, but that's more of an unknown as Google hasn't even released it in Android Studio yet.  In other words, lets worry about that later.

My big blocker is just knowing what all needs to be compiled on the C++ side.  If I can get pointed at the all the C++ needed I can then get the Gradle / NDK side wired up to start compiling things.

**Comment by bleege** [comment]
Internal discussion between @kkaefer and @bleege about [the pieces involved with C++ compilation for Android](https://mapbox.slack.com/archives/mobile/p1435073142000412).

**Comment by bleege** [comment]
According to this [bug report](https://code.google.com/p/gyp/issues/detail?id=275#c12) Android generator is being removed from GYP.

**Comment by bleege** [comment]
After experimenting with gyp's `-f android` and being told to `run lunch`, I'm going to look into using Gradle to set a task to copy the C++ files into `jni` and compile from there.  This seems like a more robust solution based on the GYP bug report ^^ from May 2015 about it being removed anyway.  Does this seem reasonable @kkaefer @springmeyer?

```sh
Makefile/android-%: CMD = deps/run_gyp android/mapboxgl-app.gyp $(CONFIG_android-$*) $(LIBS_android) --generator-output=./build/android-$* -f android
```

```
deps/run_gyp android/mapboxgl-app.gyp -Dhost=android -Iconfig/android-arm-v7.gypi -Dheadless_lib=none -Dplatform_lib=android -Dasset_lib=zip -Dhttp_lib=curl -Dcache_lib=sqlite --depth=. -Goutput_dir=. --generator-output=./build/android-arm-v7 -f android
Traceback (most recent call last):
  File "deps/run_gyp", line 8, in <module>
    sys.exit(gyp.script_main())
  File "deps/gyp/pylib/gyp/__init__.py", line 534, in script_main
    return main(sys.argv[1:])
  File "deps/gyp/pylib/gyp/__init__.py", line 527, in main
    return gyp_main(args)
  File "deps/gyp/pylib/gyp/__init__.py", line 512, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "deps/gyp/pylib/gyp/generator/android.py", line 969, in GenerateOutput
    assert android_top_dir, '$ANDROID_BUILD_TOP not set; you need to run lunch.'
AssertionError: $ANDROID_BUILD_TOP not set; you need to run lunch.
make: *** [Makefile/android-arm-v7] Error 1
```

**Comment by bleege** [comment]
Setting up the Copy C++ route.  The `build.gradle` file will now copy in the basic C++ files (Android C++, Core GL, and Platform), while [http, asset, and cache](https://github.com/mapbox/mapbox-gl-native/blob/3396bcaaac5d317ee35b4cc2433663e3eb4b355d/android/mapboxgl-app.gyp#L14-L16) remain to be done.

After `http`, `asset`, and `cache` are done the next step will be to integrate the library dependencies as well as configure NDK to compile everything.

**Comment by bleege** [comment]
Reviewed [`http`](https://github.com/mapbox/mapbox-gl-native/blob/3396bcaaac5d317ee35b4cc2433663e3eb4b355d/mbgl.gyp#L19-L20), [`asset`](https://github.com/mapbox/mapbox-gl-native/blob/3396bcaaac5d317ee35b4cc2433663e3eb4b355d/mbgl.gyp#L21-L22) and [`cache`](https://github.com/mapbox/mapbox-gl-native/blob/3396bcaaac5d317ee35b4cc2433663e3eb4b355d/mbgl.gyp#L23) .gypi files and determined that they all are already included as part of the `platform` and `android` copy process.  Future additions or removals in these directories should auto update as the copy processes (as currently) implemented grab `default` and `android` specific content (ie, no iOS stuff should ever be in these directories).

Will now look at setting up the basic NDK build process.  This will include:

1. [Adding the C++ library dependencies](https://github.com/mapbox/mapbox-gl-native/blob/3396bcaaac5d317ee35b4cc2433663e3eb4b355d/android/mapboxgl-app.gyp#L28-L35)
1. Compiler Options like [LDFLAGS](https://github.com/mapbox/mapbox-gl-native/blob/3396bcaaac5d317ee35b4cc2433663e3eb4b355d/android/mapboxgl-app.gyp#L38-L51)

**Comment by bleege** [comment]
Added copying of Certs and Styles to `assets` directory in SDK file structure to the build file.  This should be the last of the files that need to be transferred over AFAICT.  The "current" view of what this looks like in the filesystem is the screen shot below.

![20150624-current-filesystem](https://cloud.githubusercontent.com/assets/989928/8341921/21d23010-1a8e-11e5-99ef-4108fdda2f01.png)

**Comment by bleege** [comment]
Versions of Static Library dependencies are documented in [`configure`](https://github.com/mapbox/mapbox-gl-native/blob/3396bcaaac5d317ee35b4cc2433663e3eb4b355d/configure#L29-L38)

**Comment by bleege** [comment]
**Branch:**
https://github.com/mapbox/mapbox-gl-native/compare/1753-gradle-ndk

**Configure NDK**

* Download [Android NDK](https://developer.android.com/ndk/index.html)
* Set `ndk.dir` variable in `mapbox-gl-native/android/java/local.properties`

**Current Test Process:**

```sh
cd mapbox-gl-native/android/java

// Copy C++ and Assets To Appropriate Android Locations
./gradlew setupCoreGL

// Attempt Compile of libmapbx-gl.so
// This fails as it should at this point due to no C++ dependencies
./gradlew compileDebugNdk
```

I'm trying to figure out how best to get the Static Library dependencies for the C++ compilation.  They'll need to live in `jniLibs` by ABI type.  I'd like to use [Mason](https://github.com/mapbox/mason) as [suggested above](https://github.com/mapbox/mapbox-gl-native/issues/1753#issuecomment-114312267), but it's unclear if we'd be able to install it on a CI Server cloud vendor.  Are there any alternatives?

After ^^, the remaining issue will be integrating the proper `compiler` and `linker` flags into the `build.gradle` and then working out the compile issues.

Thoughts so far @ljbade @kkaefer ?

**Comment by ljbade** [comment]
@bleege Looks great! Nice to see everything in Studio. Only thing we need to remember is any changes via Studio editor to C++ files will get lost when hit build, which might be confusing for new people looking at our project (and other team members) so should document this somewhere.

As far as `mason` wrt to CI integration. I wonder if we can have a step somewhere possibly in `mason` repo Travis scripts that takes the list of static libs and versions then bundles them all into a single `.tar.gz` somewhere on S3 for a Gradle custom task to download and extract into `jniLibs`.

@kkaefer @springmeyer Thoughts on ^?

**Comment by kkaefer** [comment]
@bleege can we write a gradle target that uses mason to download the dependencies when they're required? Might also be a good idea to split up the gradle build by platform various `productFlavors` (see http://ph0b.com/android-studio-gradle-and-ndk-integration/) so that our build doesn't always build all platform targets (and download all mason dependencies).

**Comment by bleege** [comment]
Thanks for the :eyes: @ljbade @kkaefer 

> Only thing we need to remember is any changes via Studio editor to C++ files will get lost when hit build,

Yeah, I'm non plussed about this.  I'm going to explore `jni.srcDirs` config so that the C++ files will only be in one spot.  It's unclear if this will work since the C++ files all live outside the Android project root in Android Studio.  Will try it out though.

This is tough because w/o Android Studio being aware of the C++ then we won't be able to use the C++ Debugger that Google is now promising that ["we hope to be ready in the next week or two"](http://tools.android.com/recent/androidstudio13betaavailable).  Maybe we'll end up having to move the location of the [MapboxGLAndroidSDK module](https://github.com/mapbox/mapbox-gl-native/tree/master/android/java/MapboxGLAndroidSDK) in the file system?

> can we write a gradle target that uses mason to download the dependencies when they're required? 

Sure can.  My concern with Mason is that the it needs to be installed on the local file system first before it can do it's magic.  Running this on our dev laptops is no problem as it's already installed, the question is whether or not any CI SAAS vendor will let us do this on the fly.  One way to find out.  :-)

> Might also be a good idea to split up the gradle build by platform various productFlavors

Agreed.

**Comment by bleege** [comment]
I commented out the C++ copying portion of `setupCoreGL` and replaced it with `jni.srcDirs`.  The results are the screenshots below.

**Not Showing Up In Android Studio (aka No GUI Debug)**
![20150625-jni-srcdirs-not-working](https://cloud.githubusercontent.com/assets/989928/8363549/32b398a8-1b45-11e5-8a2e-0efe4a22e427.png)

**Compiling From Command Line Gives False Positive**
* This should have still given an error as the C++ files wouldn't have their dependencies.
* Interpreting this to mean that Gradle didn't actually find the C++ files
![20150625-jni-srdirs-not-working-cli](https://cloud.githubusercontent.com/assets/989928/8363618/b63c5624-1b45-11e5-9941-161b95d59b4c.png)

**Comment by kkaefer** [comment]
can we use symlinks in the `jni` dir?

**Comment by bleege** [comment]
I'm trying out the Java NIO Symlink API inside Gradle to get the files "inside Android Studio".  This will give us _in theory_ cross platform symlinks.  So far the symlink to the `cpp` is looking promising.  Will try for specific files next.

![20150625-symlink-starting-to-work](https://cloud.githubusercontent.com/assets/989928/8364270/9446aef2-1b4a-11e5-8131-558eb8dd049d.png)

**Comment by bleege** [comment]
Ah... discovered that the `jniDir.deleteDir();` in the Clean JNI portion was not just deleting the sym links but also the content in them.  When commented out and re-run the 2 *.cpp files show up in Android Studio!

Will look at ways to clean `jni` directory but not nuke files that are being symlinked to.

**Comment by bleege** [comment]
[`Files.delete(Path path)`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#delete-java.nio.file.Path-) will only remove the symlink and not the underlying content.  Will use this to make sure that content is fresh.

**Comment by bleege** [comment]
I finished implementing @kkaefer's symlink suggestion, which produces the following results in screenshot below.  I'm happy with this as it solves several issues:

1. Core GL and Platform GL C++ are "included" in Android Studio while avoid file duplication
  * Created top level directories `coregl` and `platformgl` to be maintain auto inclusivity as new files are added to the the Core projects.  Android will get them automatically without having to update the `build.gradle` file
1. `jni.cpp` and `native_map_view.cpp` are moved to `jni` directory
  * These are Android GL JNI specific C++ files and this is their natural home, rather than being split off in a generic `cpp` directory
  * Any new Android GL JNI specific C++ files will also live here
1. Left `assets` directory as copy instead of symlink
  * Certs and Styles are just here for build purposes and will not likely be edited here
  * `setupCoreGL()` is being run universally, so anytime a Gradle task is executed it'll be run and therefore updated.

Next up is to work on Mason integration for the dependencies.

![20150625-symlinks-working](https://cloud.githubusercontent.com/assets/989928/8366434/9bb5acbe-1b5a-11e5-8d01-5d51cd002a22.png)

**Comment by bleege** [comment]
Basic Mason setup in build directory working.

**Comment by ljbade** [comment]
Good progress @bleege

**Comment by bleege** [comment]
Next thing to do is to get the `installJNILibs` to have the list of C++ dependencies and their ABI so that they can be downloaded to `src/main`jniLibs`.  After this is done, then the next step will be configuring the NDK build.

**Comment by bleege** [comment]
The list of Libraries and their Versions that Mason needs to download is located in the [`configure` file](https://github.com/mapbox/mapbox-gl-native/blob/e2bc0f4122f0889429a102977dde8e4a0979b2e5/configure#L29-L38).

**Comment by bleege** [comment]
Discussed with @kkaefer this morning and we agreed that it's fine for the listing of Mason libraries for Android to be moved to a file inside the `android` project for easier access by Gradle build system.

**Comment by bleege** [comment]
Google released [NDK Preview Support in Android Studio 1.3 RC 1](http://tools.android.com/recent/androidstudiowithandroidndkpreviewsupportavailable) today.  They also released this [documentation for how to get started with it](http://tools.android.com/tech-docs/android-ndk-preview).

**Comment by bleege** [comment]
Have basic Mason downloading of library calls setup.  Failing on not being able to resolve `MASON_DIR` [environment variable to do the actual downloading](https://github.com/mapbox/mason/blob/4c71c8614fd888058408994841a470271268821a/mason#L57) though.

**Comment by bleege** [comment]
Worked through Google's [NDK Preview example](http://tools.android.com/tech-docs/android-ndk-preview) this afternoon.  Was able to get [their Teapot demo](https://github.com/googlesamples/android-ndk) to compile and run on an ARM emulator.  Couldn't get the in IDE debugging to work however (run target wouldn't set).

The fact that it did compile and run is a promising sign.  After finishing the Mason work, will look to build the Core GL compilation work using the new tech.  Over time it'll improve and eventually will get debugging.  In the short run though we'll hopefully get Java and C++ compiling and assembling via one process (which will also give us distribution options).

**Comment by bleege** [comment]
I looked into what it'd take to migrate the existing `build.gradle` to the new Google NDK Preview style and discovered Google's [Experimental Plugin User Guide](http://tools.android.com/tech-docs/new-build-system/gradle-experimental).  One the first things on this Web page is the following warm and fuzzy note:

![20150715-experimental-warning](https://cloud.githubusercontent.com/assets/989928/8710582/a44af398-2aff-11e5-9b91-161df4e797af.png)

A little further down the page, there's specifics on "Known Limitations" of the NDK Support:

![20150715-experimental-ndk-limitations](https://cloud.githubusercontent.com/assets/989928/8710645/2c6be85e-2b00-11e5-80dc-e44fc71ad06a.png)

The big issues that jump out to me are:

1. No support for creating and depending on static libraries
1. No support for integrating external build systems.
 
So... as much as I love working with new tech, I'm thinking that it's in the project's best interest to let this sit for awhile and let Google mature this tech a bit more before we start making use of it.  What this means is:

1. We focus on using the existing Gradle / NDK support as it's been around longer and is more likely to be supported on CI servers
1. We keep an eye on Google's new NDK support and at a later date look to migrate to it when it's more mature.

**Comment by hallahan** [comment]
One idea is we can continue using remote gdb, but we can find a nice GUI to let us step through C++ easily.

There is a plugin for netbeans:
http://wiki.netbeans.org/GdbServer

Also, Qt Creator allows remote debugging. @tmpsantos - do you think that might make sense?

**Comment by bleege** [comment]
Variants are now producing proper ABI specific artifacts!

![screen shot 2015-07-15 at 5 52 53 pm](https://cloud.githubusercontent.com/assets/989928/8713166/5eca6e96-2b1a-11e5-84aa-a2d9507ec692.png)

**Comment by tmpsantos** [comment]
> Also, Qt Creator allows remote debugging. @tmpsantos - do you think that might make sense?

I wouldn't count on Qt Creator for Android development because IIRC it always assume that the app itself is using Qt. :-/

**Comment by bleege** [comment]
Here's my review of the current status of this ticket and opinion on what needs to happen to finish it.

#### Current State Of Development Cycle
1. Make changes to Core GL C++ Code
1. Recompile Core GL C++ Code using `make android` to create `libmapbox-gl.so` per ABI
1. Compile MapboxAndroidGLSDK using `gradle build` / variant if looking to run on local emulator

#### Future State End Goal (aka "How you'll start developing when this is done")
1. Open project in IDE (likely Android Studio) and have project automatically setup via `gradle setupCoreGL`
1. Make changes to Core GL C++ Code directly in IDE
1. Compile MapboxAndroidGLSDK using `gradle build` / variant if looking to run on local emulator
  * This will contain NDK compiling logic

#### What's Done Already
1. `setupCoreGL` to clean and setup symlinks to Core GL C++ code
1. Download and setup of `mason` dependency manager dynamically via Gradle

#### What Needs To Be Done
1. C++ Compilation Logic
  * [ ] How does this work?
  * [ ] How to configure [mason](https://github.com/mapbox/mason) to download the ABI specific dependencies needed for compilation
  * [ ] What are all the flags / settings needed to compile (see image below)
![cpp-flags-questions](https://cloud.githubusercontent.com/assets/989928/8827634/6e805790-3053-11e5-88db-bac3bdd47a13.png)

I think we're on the home stretch with this, but I'm hitting a blocker on the C++ stuff.  Will need support from @ljbade @kkaefer @springmeyer to port the existing Makefile base approach.

**Comment by ljbade** [comment]
@bleege With the current branch do you get error on the TestApp module not finding class import from SDK module?

![image](https://cloud.githubusercontent.com/assets/1215089/8841435/c6e74f6e-3130-11e5-9c17-03af7ce759bb.png)

**Comment by bleege** [comment]
@ljbade Can't say that I do.  Just to clarify, you're referring to https://github.com/mapbox/mapbox-gl-native/compare/1753-gradle-ndk correct?  If so, it's not surprising as the `build.gradle` script isn't in a buildable state IIRC.  `master` should be good though.  Perhaps running `Build | Clean Project` might help clear the cobwebs.

**Comment by ljbade** [comment]
I think first variable to tackle will be `cFlags`. There is a few places these come from.

In `mason.sh` there are several ABI dependant flags set here more or less copied from the NDK defaults. I need to check which ones have been added beyond the NDK ones. I assume at this stage that gradle uses the NDK defaults already?

There are also some set it the gyp files. Common flags such as C++14 is set in `gyp/common.gypi`. Most of the other gyp files include flags specific to the static libs dependencies.

**Comment by bleege** [comment]
Bumping to `0.2.0`.

**Comment by ljbade** [comment]
@incanus Hopefully with Bitrise we can avoid the need to wrap `make` in `gradle`.

**Comment by ljbade** [comment]
@bleege I think we can close this now we selected Bitrise?

**Comment by bleege** [comment]
> I think we can close this now we selected Bitrise?

@ljbade No.  This is still need to address the need to have inline debugging of Java and C++.  Please see the first sentence in this ticket:

> In order to support C++ / NDK debugging in Android Studio

**Comment by mdakram** [comment]
Any update on this ?

**Comment by tomlocks** [comment]
Bumping...

Would It be possible to get at least working Android.mk and Application.mk files with all flags and dependecies needed to build?

@ljbade You mentioned before that you successfully created Android.mk with all dependecies for older SDK version. Can you share it with us?

**Comment by bleege** [comment]
@tomlocks We welcome PRs on enabling this functionality.  The difficulty has always been trying to integrate the common C++ code that doesn't live directly in the Android project filesystem as it's reused by iOS, OSX, Qt, and others.

**Comment by zhangzhuowh** [comment]
@bleege  How can I import `mapbox-gl-native Android sdk` project to Android Studio like you? If I use `make android` command line, it generate `.so` files, I can't modify C++ files. Thanks!
[![enter image description here][1]][1]

  [1]: http://i.stack.imgur.com/iEscd.png

**Comment by bleege** [comment]
> How can I import mapbox-gl-native Android sdk project to Android Studio like you? 

@zhangzhuowh The oiginal work on this was focused on copying the C++ source code into the Android Studio `jni` folder but it was never finalized.  This is [still the current status of this work](https://github.com/mapbox/mapbox-gl-native/issues/1753#issuecomment-123740695) if you'd like to pick this effort up.  Pull Requests are always welcomed.

**Comment by jfirebaugh** [comment]
⇢ #5855
