### ISSUE TITLE
allow shape annotations to layer below labels

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1754]
Eventually we'll fully open up the layering (collisions, etc.), but in the meantime, for simple, traditional shape annotations, people will want to layer them just below labels for clarity. 

Related: https://github.com/mapbox/mapbox-gl-native/issues/1728

![img_0650](https://cloud.githubusercontent.com/assets/17722/8238542/55049b2c-15ab-11e5-9fc3-80d674a1e9fc.PNG)

**Comment by friedbunny** [comment]
This would also be useful for polylines.

**Comment by jlansing** [comment]
This is definitely something we'd like to do for polylines as well.

**Comment by kkaefer** [comment]
See https://github.com/mapbox/mapbox-gl-js/issues/4225 and https://github.com/mapbox/mapbox-gl-native/issues/1728

**Comment by marcbaldwin** [comment]
I'd like to be able to add `MGLPolygon` below city labels, is there another way of doing it? Perhaps using layers? Any help would be greatly appreciated.

**Comment by kkaefer** [comment]
@marcbaldwin You can use a GeoJSON source, and use runtime styling to add it. This API allows you to specify the strata at which to insert the data. See https://www.mapbox.com/ios-sdk/api/3.6.0/runtime-styling.html for more documentation on this feature.

**Comment by marcbaldwin** [comment]
Hey @kkaefer, thanks for your quick reply. Using the MGLPolygonFeature, MGLShapeSource, and MGLFillStyleLayer classes to do it, thanks! :)
