### ISSUE TITLE
Changing device orientation causes user dot to wander

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1755]
Rotating the device between landscape and portrait can cause the user dot to wander all over the world map if you zoom out to the minimum allowed zoom level.

Start out in portrait with the user dot visible, and note your location. Zoom all the way out to the minimum zoom level:

![1](https://cloud.githubusercontent.com/assets/1231218/8238721/5a997ef8-15ac-11e5-8e20-4511aeb4f4b5.png)

Rotate the device to landscape:

![2](https://cloud.githubusercontent.com/assets/1231218/8238776/9214033a-15ac-11e5-935a-cc4c5fadebe8.png)

Zoom further out:

![3](https://cloud.githubusercontent.com/assets/1231218/8238790/b54f9288-15ac-11e5-9e15-8148b859414f.png)

Rotate back to portrait:

![4](https://cloud.githubusercontent.com/assets/1231218/8238807/cfe85d28-15ac-11e5-990e-c3d3ba98425f.png)

The user dot has wandered hundreds of miles. Now pan left and right:

![5](https://cloud.githubusercontent.com/assets/1231218/8238849/0a306cd2-15ad-11e5-8d49-59ff1e89f23e.png)

The user dot moves relative to the map content, sometimes disappears, and sometimes reappears on the other side of the screen.

The bug goes away as soon as you zoom in or out.

/cc @incanus

**Comment by friedbunny** [comment]
I'm no longer seeing this wandering. There is a slight delay after rotation where the dot slides back to its proper position, but the location is still accurate.

**Comment by 1ec5** [comment]
Same here iOS 9.0 on the same device I saw this issue in originally.
