### ISSUE TITLE
appledoc-generated docset shows unavailable methods as being available

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1759]
If you follow the [instructions to install and run appledoc](https://github.com/mapbox/mapbox-gl-native#manually), the resulting Xcode docset includes the following unavailable methods with no indication that the method has been made unavailable via a compiler attribute:

* `+[MGLAccountManager setMapboxMetricsEnabledSettingShownInApp:]`
* `MGLMapView.accessToken`

/cc @incanus

**Comment by incanus** [comment]
Handled for now in b2.

**Comment by 1ec5** [comment]
I think we can call this issue fixed: we just need to remember to remove the documentation comment whenever we mark a symbol unavailable.
