### ISSUE TITLE
fix scalars not showing up in iOS docs

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1763]
Scalars like `MGLCoordinateBounds` don't show up, probably because we need to document them for `appledoc`.

**Comment by friedbunny** [comment]
This goes for everything defined in `MGLGeometry.h` — it doesn't show up in quick help or appledoc.

**Comment by 1ec5** [comment]
#3203 fixed this issue by replacing appledoc with jazzy.
