### ISSUE TITLE
update iOS install wiki page

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1764]
https://github.com/mapbox/mapbox-gl-native/wiki/Installing-Mapbox-GL-for-iOS

Most of this can be shunted over to https://www.mapbox.com/mapbox-gl-ios/, but some might need to stick around.

**Comment by 1ec5** [comment]
The main part that isn't covered is storyboards.

**Comment by 1ec5** [comment]
We’ve incorporated the storyboard workflow into the “[First steps with the Mapbox iOS SDK](https://www.mapbox.com/help/first-steps-ios-sdk/)” guide. I left in the “[Using Mapbox iOS SDK in an Interface Builder storyboard](https://github.com/mapbox/mapbox-gl-native/wiki/Using-Mapbox-iOS-SDK-in-an-Interface-Builder-storyboard)” wiki page as a soft redirect.
