### ISSUE TITLE
Delegate methods for MGLMapView user interaction

### ISSUE THREAD

**Issue by tomtaylor** [mapbox/mapbox-gl-native#1769]
It would be really handy to be able to discern between a user initiated `MGLMapView` region change, and a programatic one. In `RMMapView` this was possible with `- (void)beforeMapMove:(RMMapView *)map byUser:(BOOL)wasUserAction`. Something similar would be ideal.

**Comment by jhoughjr** [comment]
Here here!

**Comment by jormon** [comment]
:+1:
