### ISSUE TITLE
Add ability to filter/intercept location updates

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#1772]
Feature request:
We would like the ability to intercept the user location tracking in order to "snap" the user location to a route, modify the user's course to match a route, or even replace the location tracking completely to simulate driving routes. Some of this can be accomplished with subclassing, but it gets pretty ugly.

**Comment by tobrun** [comment]
Removing the Android label as we deprecated all location related code in the SDK. This feature request should go into the location layer plugin.

**Comment by jfirebaugh** [comment]
→ #12280
