### ISSUE TITLE
Label renders black blocks on some loads

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#1773]
On some loads, labels are rendered as black blocks. This is using `node-mapbox-gl-native@1.1.2`. The error seems to be very intermittent and predictable. It however never happens on the first load of a particular size, always on subsequent loads. 

![](https://cloud.githubusercontent.com/assets/1058624/8292809/6b1d68ce-18e6-11e5-8d44-8f0be5ad0b57.png)
![](https://cloud.githubusercontent.com/assets/1058624/8292810/6bd43f22-18e6-11e5-81bb-c4acb6b1e7fa.png)

/cc @mikemorris @ansis

**Comment by incanus** [comment]
I'll bet you anything it's that ⬛️⬛️⬛️⬛️⬛️⬛️⬛️ good-for-nothing ⬛️⬛️⬛️⬛️⬛️ again.

**Comment by 1ec5** [comment]
Watch your language, @incanus, this is a public repo!

**Comment by jfirebaugh** [comment]
No longer seeing this.
