### ISSUE TITLE
map change listener should detect fling updates (Android)

### ISSUE THREAD

**Issue by erf** [mapbox/mapbox-gl-native#1777]
When i fling the map i don't get map update changes after the first touch. that is i also want updates whilst the map is moving. (So that i can update the gps location marker in the map.. since this feature is missing in the Android version..)

**Comment by ljbade** [comment]
What ended being done for this on iOS? @incanus

**Comment by incanus** [comment]
This should be cleaned up significantly with @jfirebaugh's work in https://github.com/mapbox/mapbox-gl-native/pull/1624/ for all platforms. @erf On iOS, we are currently listening for these updates for the GPS dot on iOS, but I am working in https://github.com/mapbox/mapbox-gl-native/issues/1125 on syncing this up better by updating in the same call as the OpenGL frame update. 

Please reopen this if hooking up to the `notifyMapChange` isn't enough to work from.
