### ISSUE TITLE
Rotation based on heading going opposite of Google / Apple (iOS)

### ISSUE THREAD

**Issue by parrots** [mapbox/mapbox-gl-native#1780]
When setting the direction in MapBox GL to a specific heading it seems to rotate in a direction opposite Google Maps and Apple. Meaning at 0 and 180 the maps line up but at 90 MapBox is at an Apple equivalent to 270.

Probably just need to reverse the direction you start to rotate based on a heading.

Video here: http://f.cl.ly/items/0w3K2a3C0T1R2m1K1D0m/Rotation.mov

**Comment by 1ec5** [comment]
As @friedbunny points out, we’re also inconsistent with mapbox/mapbox-gl-js. From the documentation for `-[MKCamera heading]`:

> The value `0` means that the top edge of the map view corresponds to true north. The value `90` means the top of the map is pointing due east. The value `180` means the top of the map points due south, and so on.
