### ISSUE TITLE
DisplayHeadingCalibration does nothing (iOS)

### ISSUE THREAD

**Issue by parrots** [mapbox/mapbox-gl-native#1782]
Setting displayHeadingCalibration to false does not remove the commas from the display:

```
mapView.setCenterCoordinate(center, zoomLevel: zoom - 1, animated: animated)
mapView.setDirection(heading, animated: animated)
mapView.displayHeadingCalibration = false
```

Yields:
![simulator screen shot jun 23 2015 4 43 14 pm](https://cloud.githubusercontent.com/assets/171163/8316737/f6f3bf48-19c6-11e5-9579-ad954adaeafb.png)

**Comment by 1ec5** [comment]
Are you trying to hide the compass? In #1770, we’ve discussed adding a `showsCompass` property to MGLMapView, now that MKMapView has added it in iOS 9. It isn’t currently supported, but as a temporary workaround, you can forward-declare [this property](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/MGLMapView.mm#L70) and set `.hidden = YES` on it.

**Comment by 1ec5** [comment]
`displayHeadingCalibration` is for displaying a “heading calibration alert”.

**Comment by parrots** [comment]
Sorry, I fail at reading the docs apparently.
