### ISSUE TITLE
iOS annotation views

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1784]
Our current iOS user dot is a custom view (made of three parts; the dot and, mutually exclusively, either the pulsing halo or the accuracy radius). 

![ios simulator screen shot jun 23 2015 3 39 49 pm](https://cloud.githubusercontent.com/assets/17722/8319071/8bbdc180-19bf-11e5-9bea-fe42971160e9.png)

We also do this with the (singular) callout view: 

![ios simulator screen shot jun 23 2015 3 40 25 pm](https://cloud.githubusercontent.com/assets/17722/8319073/9050fe06-19bf-11e5-8dad-bc2546486f00.png)

Though we currently punt on _tracking_ this callout view to the map pan/zoom since there are margin and layout issues that are more complex than the mere user dot. 

We eventually want to support other, user-provided views atop the GL map view for several reasons: 

- Users are already creating views in projects and want to use them on maps. 
- Follows expected MapKit APIs. 
- Allows use of existing libraries expecting to work with views such as [kingpin](https://github.com/itsbonczek/kingpin) (related: https://github.com/mapbox/mapbox-gl-native/issues/320). 
- Native views allow animatability with Cocoa APIs (`CABasicAnimation`, `UIView` animation blocks, etc.)

Somewhat blocked by / could be improved upon with https://github.com/mapbox/mapbox-gl-native/issues/1125, which I think is at the core of a successful implementation. 

Tasks: 

- Memory-efficient reuse identifier-based queueing approach for view vending from delegate (`-[MGLMapViewDelegate mapView:viewForAnnotation:]`, `-[MGLMapView dequeueReusableAnnotationViewWithIdentifier]`, etc.)

- Improved syncing/tracking performance in #1125 as mentioned above, including research into possible frame-based view/layer OpenGL compositing/texture uploading. 

- Branching current tap gesture hit testing to account for native-side views as well as core-side symbols.

**Comment by 1ec5** [comment]
This is a good opportunity to pick #1582 back up as well.

**Comment by incanus** [comment]
:+1:

**Comment by incanus** [comment]
> Branching current tap gesture hit testing to account for native-side views as well as core-side symbols.

Actually, this might not be necessary as long as the size of native-side views is taken into account, as hit testing can work the same way.

**Comment by incanus** [comment]
Based on what I'm seeing with #941, we may be able to punt on this for b3 and just benefit from custom marker imagery there and a better user dot and callout from #1125. It would definitely keep hit testing simple and not have problematic z-ordering between iOS-side views and GL-side sprites, and using what I learned in https://github.com/mapbox/mapbox-gl-native/issues/1125#issuecomment-117471812 we could keep this all GL-side even when using `UIView` for b4.

**Comment by incanus** [comment]
Pushing this off of b3 to keep things simple, as well as keep us in platform-independent territory a bit longer. We'll hit it right & performant out of the gate for b4.

**Comment by maxneust** [comment]
@incanus Any ETA for when will this be implemented? The only thing keeping us from moving to Mapbox-gl is custom views for annotations/callouts.

**Comment by mackuba** [comment]
I'd also be interested in this - I'm migrating my app from MBXMapKit right now, and I have a "pulsating dot" custom view there very similar to the one described above that I use for map markers.

**Comment by mackuba** [comment]
Also, once you add support for views, something like `map.viewForAnnotation(annotation)` would be nice, because I need to access existing annotation views on the map and rotate them in some cases.

**Comment by pecheriere** [comment]
Hey @incanus, do you have any news about this ?

**Comment by gpbl** [comment]
I also need to use a custom view for the user location annotation. I tried to subclass `MGLMapView` but many internals seems to be only accessible by the MGLMapView instance itself.

**Comment by 1ec5** [comment]
If you need to customize the appearance of the user location annotation view (user dot) and don't need a lot of fanciness (like the puck that appears during course tracking), here's a workaround you can use:

1. Implement a class similar to [MGLUserLocationAnnotationView](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/MGLUserLocationAnnotationView.h) that responds to all the same methods.
1. In your MGLMapView subclass (or even your view controller), swap out the map view's private `userLocationAnnotationView` property using `-setValueForKey:`.

**Important:** This is a kludge, and there's no guarantee that it won't break in future releases, especially once we close out this bug but even in seemingly unrelated changes. So this is a last resort; please test thoroughly.

**Comment by XemaCobra** [comment]
I was wondering when do you expect this to be implemented as it is the only thing blocking me from using MapBox over MapKit in my current project even if t only supports a couple of hundred markers instead of thousands. Thanks

**Comment by stephensilber** [comment]
Also waiting on this feature to migrate from MKMapKit to Mapbox for 2 separate projects of mine!

**Comment by 1ec5** [comment]
This feature has largely been blocked by #1125, which will be addressed by #3683. Work to implement native annotation views can then move forward, assuming there’s consensus that there should be two parallel ways to add annotations to the map (UIViews versus Mapbox GL sprites). In the meantime, please note that the existing MGLAnnotationImage is available for markers made of static images (and to some extent text).

**Comment by RomainQuidet** [comment]
@1ec5 Can you expose your choice over annotations (native or GL) ? We need to animate annotations, it's quite impossible for us in GL!

**Comment by devcarlos** [comment]
Is this going to be implemented someday ? We have only decided to use MapBox because of the Dark/Light custom styles and the Annotation cannot be as flexible as the map? Really ? Very disappointed so far and thinking to stay with MapKit after all.

At least you should give some hints to create an MGLAnnotationImage with custom texts like title, subtitle or similar.

**Comment by 1ec5** [comment]
Yes, this issue is on the 3.3.0 milestone. The implementation depends on #4384 and would likely progress in tandem with #4392.

In the meantime, the iosapp demo application has [some code you can crib](https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.2.0-beta.2/platform/ios/app/MBXViewController.mm#L522-L578) for rendering text onto an annotation image. It looks like this:

![annotation images](https://cloud.githubusercontent.com/assets/1231218/13960556/10ad3470-f016-11e5-9e36-8070556208aa.png)

**Comment by devcarlos** [comment]
Thanks @1ec5 I was going to try the same (take a UIView snapshot) with my Map Pin icon as background and the Title text required.

Regards,
Carlos

**Comment by 1ec5** [comment]
The Android analogue to this issue is #3276.

**Comment by postmechanical** [comment]
@1ec5 Any progress on this issue? Is there a branch for it yet?

**Comment by 1ec5** [comment]
Hey @postmechanical, we’re just getting started on this issue today. We’re starting with #4384, as that’ll be critical for performance. Performance-wise, there’s also the approach @incanus took in https://github.com/mapbox/mapbox-gl-native/issues/1125#issuecomment-117471812, but we aren’t planning to revisit that optimization until we’ve got the basic API up and running.

**Comment by mmccroskey** [comment]
Hi @1ec5 -- I work with @postmechanical and was wondering if there were any updates you guys could offer on this one?

**Comment by boundsj** [comment]
Hi @mmccroskey as @1ec5 said above, we are just getting started on this. I will make a PR in the coming days but I don't have an exact ETA on when this feature will be completed. As @1ec5 mentioned, you can monitor #4384 (and this ticket) for updates as they happen.

cc @twbell

**Comment by mmccroskey** [comment]
Sounds good, thanks @boundsj 

cc @postmechanical

**Comment by 1ec5** [comment]
For future reference, the experimental performance optimization described in https://github.com/mapbox/mapbox-gl-native/issues/1125#issuecomment-117471812 is on the [`view-based-points` branch](https://github.com/mapbox/mapbox-gl-native/compare/view-based-points).

**Comment by 1ec5** [comment]
MGLAnnotationView landed on iOS in #4801. Opened #5035 to track porting it to OS X.

**Comment by 1ec5** [comment]
> Our current iOS user dot is a custom view (made of three parts; the dot and, mutually exclusively, either the pulsing halo or the accuracy radius).

Filed #5039 to base the user dot on the annotation view class.

> I also need to use a custom view for the user location annotation.

Filed #5037 to add a way for you to specify the user location annotation’s view.

Filed some more issues for tail work: #5036 #5038 #5040.
