### ISSUE TITLE
Annotation updates block main thread (iOS)

### ISSUE THREAD

**Issue by parrots** [mapbox/mapbox-gl-native#1798]
Related to #1797 possibly, but when the map need to redraw as part of an update to the annotations, the main thread is blocked for an unusual amount of time resulting in paused UI rendering for other controls.

Example: http://f.cl.ly/items/1U2K0o0F0k462L1a092T/Blocker.m4v. You can see that during the ~0.5 seconds it takes to redraw the polylines, the rest of the UI in the app is hung waiting.

**Comment by incanus** [comment]
Just confirming here @parrots — "update" to annotations means adding or removing in this context? So #1688 covers the flickering and this ticket covers the UI thread blocking.

**Comment by parrots** [comment]
That's correct.

**Comment by incanus** [comment]
@parrots I'm seeing pretty satisfactory performance of rapid adds & removes of annotations as of current pre-release. Check out this branch of a sample project I've been working on: 

https://github.com/incanus/UISyncedMap/tree/rapid-annotation-add-remove

This adds a single static path, but then in response to a UI slider, removes all others and adds a new, small, red segment representing the next sub-segment in the path. 

![](https://github.com/incanus/UISyncedMap/raw/rapid-annotation-add-remove/demo.gif)

Seems pretty snappy to me (keep in mind this is a GIF). We get a little annotation flashing still (#1688) but even MapKit does this IIRC. 

Could you try `ios-v-2.1.0-pre.2` per [this method](https://github.com/incanus/UISyncedMap/blob/b1f9b40caa1023b18506acf4a9081f25919f920d/Podfile#L2) and see how it fares in your project?

**Comment by parrots** [comment]
It's running quite a bit better on-device. Running my app using this build of MapBox I'm getting 54-59 FPS on an iPhone 6 (swift whole-module optimization, etc -- all the good stuff). I notice a hickup here and there, but dramatically better. Apple Maps is 57-59 using the same setup.

I'm seeing pretty similar characteristics on an iPhone 5 (just a tad lower, closer to 53 - 57 FPS).

I'm noticing that in the simulator with this build I get more hiccups than I'd expect, or than I see on-device (this includes your sample project above, too). Feels closer, but a bit better than, what the old version of the SDK was like in terms of performance. Mapkit and Google maps don't exhibit the same slow-down in the sim. This is a vastly secondary problem, IMO, and shouldn't prevent this issue from being marked as resolved.

**Comment by incanus** [comment]
Awesome, glad to hear it. I have uncovered some root improvements that could be made, but I'm not sure if they'll go into this release yet or not.

**Comment by parrots** [comment]
Followup re:flicker for #1688, it's still pretty noticeable in-app on-device (I can make a recording if you'd like). Better than it used to be, but still not really shippable. But at least it isn't blocking the main thready anymore 🎉

**Comment by incanus** [comment]
This should ultimately get better in #1688, so I'm going to close here. Thanks for the testing and feedback @parrots.

**Comment by Gerz-inc** [comment]
I have block main thread problem on annotations adding (AnnotationView) in version 3.4
