### ISSUE TITLE
support mapViewDidFinishRenderingMap:fullyRendered:NO

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1804]
Followup to #1431.

What remains unimplemented is support for fullyRendered:NO -- we currently do not surface tile errors in a way that made this easy to implement, so I'm punting for now.

**Comment by mkrussel77** [comment]
We typically create VectorSources for data that changes and may or may not have anything visible.

Currently if there is a failure to download the tiles, it just looks to the user that there is nothing happening.  

Being able to report that there has been an error would let them know that there might be something there but we are unable to display it to them.
