### ISSUE TITLE
Labels do not fully render on launch

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1806]
New since 0.4.0, when launching the app, any labels in the initial viewport are washed out until the next render pass:

![washout](https://cloud.githubusercontent.com/assets/1231218/8444491/10fcf524-1f46-11e5-8c03-126f95a5682c.jpg)

Seen in iOS 8.4 on iPhone 6.

/cc @kkaefer @tmpsantos

**Comment by jfirebaugh** [comment]
This is the same as #1548.

**Comment by 1ec5** [comment]
This is worse since last week. I'm seeing it at launch. Technically there has been one zoom change by this point, but I've been seeing #1548 for much longer.

**Comment by 1ec5** [comment]
Ah, I was seeing this in a test app that was animating the transition to the initial coordinates and zoom level.
