### ISSUE TITLE
iOS: Swiping from bottom/top to access control/notification centre in full screen map -> pan map

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-native#1812]
Hey,

minor usability issue on iOS:

Google Maps and other full screen map apps on iOS disable map pan on swipes from the bottom/top edge to prevent the map from moving when the user is trying to access the iOS control centre and notification centre.

Right now, it's doesn't seem possible to disable swiping in a region of the map in the Mapbox SDK. If the user try to open the notification/control centre in a full screen map view, iOS detects that the gesture is triggering map movement, and only shows the 'open arrow' instead. 

The result is that the map pans and the user has to swipe twice from the bottom/top edge to open the control/notification centre.

It is possible to hack around this by creating a transparent overlay that catches the touch events at the bottom/top of the map, but it is probably better to handle this in the SDK.

**Comment by 1ec5** [comment]
Reproduces in landscape – can't interact with the little tab that pops up – but portrait works fine.

**Comment by 1ec5** [comment]
iOS displays the tab for Notification Center when there’s no top bar and the tab for Control Center when there’s no bottom bar. I see the same behavior in both Apple Maps and Google Maps: in either app, tap the map to hide the toolbars, then swipe from the top or bottom edge. The map pans, and only a tab appears. @kristfal, are you seeing different behavior?
