### ISSUE TITLE
label collision across tile boundaries

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#1816]
![mapbox_gl__mapbox_streets_2015-07-01_15-23-00](https://cloud.githubusercontent.com/assets/1421652/8460218/2c5ea064-2023-11e5-9e1c-ce63be41b4ff.png)

This doesn't happen in -js so it's likely a porting bug:

http://localhost:9966/debug/#12.44/40.5846/-74.1418/19.8

**Comment by jfirebaugh** [comment]
This is likely the same bug as #1689.
