### ISSUE TITLE
iOS sample app Auto Layout exception at runtime — View hierarchy unprepared for constraint

### ISSUE THREAD

**Issue by bmeine** [mapbox/mapbox-gl-native#1818]
I cloned the repo and got everything to compile and was able to run the Android sample app without problems. When I ran the iOS sample it compiles everything fine, but throws the following exception before the map loads.

2015-07-01 16:22:32.406 Mapbox GL[4153:60b] The view hierarchy is not prepared for the constraint: <NSLayoutConstraint:0x15d83d50 V:[_UILayoutGuide:0x15d82fd0]-(>=5)-[UIView:0x15e64330]>
	When added to a view, the constraint's items must be descendants of that view (or the view itself). This will crash if the constraint needs to be resolved before the view hierarchy is assembled. Break on -[UIView _viewHierarchyUnpreparedForConstraint:] to debug.
2015-07-01 16:22:32.409 Mapbox GL[4153:60b] View hierarchy unprepared for constraint.
	Constraint: <NSLayoutConstraint:0x15d83d50 V:[_UILayoutGuide:0x15d82fd0]-(>=5)-[UIView:0x15e64330]>
	Container hierarchy: 
<UIView: 0x15e64330; frame = (0 0; 0 0); gestureRecognizers = <NSArray: 0x15e64700>; layer = <CALayer: 0x15e64200>>
   | <UIImageView: 0x15e62930; frame = (0 0; 36 36); alpha = 0; opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x15e63530>>
	View not found in container hierarchy: <_UILayoutGuide: 0x15d82fd0; frame = (0 0; 0 64); hidden = YES; layer = <CALayer: 0x15d83110>>
	That view's superview: <UIView: 0x15e51c90; frame = (0 0; 320 568); autoresize = W+H; layer = <CALayer: 0x15e51cf0>>
2015-07-01 16:22:32.412 Mapbox GL[4153:60b] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Unable to install constraint on view.  Does the constraint reference something from outside the subtree of the view?  That's illegal. constraint:<NSLayoutConstraint:0x15d83d50 V:[_UILayoutGuide:0x15d82fd0]-(>=5)-[UIView:0x15e64330]> view:<UIView: 0x15e64330; frame = (0 0; 0 0); gestureRecognizers = <NSArray: 0x15e64700>; layer = <CALayer: 0x15e64200>>'
*** First throw call stack:
(0x2fe52ecb 0x3a5edce7 0x2fe52e0d 0x307ba14b 0x3277425d 0x327740b5 0x3277402f 0x32773f37 0x3277da17 0x307b9d33 0x3277d989 0x37a5f5 0x32c102eb 0x3277822b 0x2fd86159 0x32c10285 0x3277822b 0x2fd86159 0x32c10285 0x3277822b 0x2fd86159 0x32c10285 0x3277822b 0x2fd86159 0x32c10285 0x3277822b 0x2fd86159 0x32c10285 0x3277822b 0x307b9d33 0x327920c7 0x32684543 0x32732233 0x326842e5 0x3230031b 0x322fbb3f 0x3232ab4d 0x3270087f 0x326fee89 0x326fe0c7 0x326fe04f 0x326fdfe7 0x326f6661 0x3268a677 0x326fdd39 0x326fd809 0x3268f5f5 0x3268cdb9 0x326f6a31 0xec12b 0x326f3ca1 0x326f35f3 0x326edca9 0x32689c77 0x32688dd9 0x326ed3e5 0x34cf6b55 0x34cf673f 0x2fe1d807 0x2fe1d7a3 0x2fe1bf6f 0x2fd86729 0x2fd8650b 0x326ec60b 0x326e7871 0xebcfd 0x3aaebab7)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

Any ideas? I hope it's just a step I missed somewhere...

**Comment by 1ec5** [comment]
This is the iosapp target, unmodified? Which device (or simulated device) and OS version are you running?

**Comment by bmeine** [comment]
When you asked for the version that made me realize I hadn't updated my development phone from iOS7 to 8. Tried in the simulator, which uses 8.3, and all is good...should have tried that before posting. 

Sorry for wasting your time and thanks for the quick response.

**Comment by 1ec5** [comment]
iOS 7 is supported; this may be a regression from #1793.

**Comment by bmeine** [comment]
Oh, well in case it helps I'm using an iPhone 5 with iOS 7.1.2

Let me know if you need anything else from me that would help

**Comment by mariobento** [comment]
In my case i have the base SDK defined to latest (8.3) and just with this:

MGLMapView * map = [[MGLMapView alloc] initWithFrame:self.view.bounds];
        [map setDelegate:self];
        [self.view addSubview:map];

It crashes, what's the real fix? i don't think that update my phone (iOS 7.1.2) is the right solution, we also need this app to rum on ios7!

Ideas?

**Comment by 1ec5** [comment]
@mariobento, agreed, we do want to support iOS 7. Do you encounter the same issue if you use the latest stable version of Mapbox GL (0.4.0)?
