### ISSUE TITLE
Installing pre-release versions through Cocoapods?

### ISSUE THREAD

**Issue by tomtaylor** [mapbox/mapbox-gl-native#1822]
It'd be really handy to document the installation procedure for pre-release versions. I'm trying to install it through Cocoapods using the following line:

```
pod 'MapboxGL', git: 'https://github.com/mapbox/mapbox-gl-native.git'
```

And it recognises the Podspec (`Installing MapboxGL (0.4.4-symbols)`), but I get `'MapboxGL/MapboxGL.h' file not found` wherever I try to `#include` it. Am I missing something, or do these releases need to be installed with a different process?

Thanks!

**Comment by frenos** [comment]
You don't need to do this anymore I think.
Just use `pod MapboxGL` and you will get the current v0.4.4.
Or did I miss your problem?

**Comment by friedbunny** [comment]
This will get you the latest (pre-)release on GitHub:

```
pod 'MapboxGL', :podspec => 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/master/ios/MapboxGL.podspec'
```

Note that this doesn't checkout this repo or build anything from source, [it uses the latest release from here](https://github.com/mapbox/mapbox-gl-native/releases) that may or may not have also been released to CocoaPods' public repo.

**Comment by tomtaylor** [comment]
@frenos 0.4.4 doesn't seem to be in the published repo. 0.4 works fine.

@friedbunny thanks, that works, but is there an obvious way of selecting the version without symbols - it just uses whatever it in the version attribute, which is `0.4.4-symbols`. I guess one way would be to take a local copy of the file?

**Comment by tomtaylor** [comment]
OK, so installing with a local Podspec works file. But now I'm guessing what I'm guessing is a separate issue:

```
Undefined symbols for architecture x86_64:
  "mbgl::Map::fitBounds(std::__1::vector<mbgl::LatLng, std::__1::allocator<mbgl::LatLng> >, mbgl::$_1, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> >)", referenced from:
      -[MGLMapView setVisibleCoordinates:count:edgePadding:animated:] in libMapboxGL.a(MGLMapView.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by friedbunny** [comment]
@tomtaylor We're looking to enable build-from-source via CocoaPods in #1437, if that's what you're trying to do.

@incanus may know how to wrangle the podspec to prefer the smaller unsymbolicated release.

**Comment by incanus** [comment]
For interim prereleases: 

1. Create a local `MapboxGL.podspec` to point to. 
1. Update its `version` to the appropriate spot. 
1. Choose either `x.y.z` or `x.y.z-symbols` accordingly. 

By default, our stable releases (`x.y.0`) are not symbolicated.

**Comment by 1ec5** [comment]
@tomtaylor, that linker error looks like something that might happen if you haven’t `make clean`’d after upgrading.

**Comment by incanus** [comment]
@tomtaylor if you have any further info on the link error you saw, would you mind elaborating at #1859? I think we're done here, though.

**Comment by robipresotto** [comment]
I'm trying to setup the pod file to load from local (to prototype features and fix bugs) but 'm not lucky,

- My pod file

```ruby
pod 'Mapbox-iOS-SDK', :podspec => './Mapbox-iOS-SDK.podspec'
```

- My podspec (Mapbox-iOS-SDK.podspec)

```ruby
Pod::Spec.new do |s|

    s.name    = 'Mapbox-iOS-SDK'
    s.version = '2.1.2'

    s.summary          = 'Open source vector map solution for iOS with full styling capabilities.'
    s.description      = 'Open source OpenGL-based vector map solution for iOS with full styling capabilities and Cocoa bindings.'
    s.homepage         = 'https://www.mapbox.com/ios-sdk/'
    s.license          = 'BSD'
    s.author           = { 'Mapbox' => 'mobile@mapbox.com' }
    s.screenshot       = 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/master/ios/screenshot.png'
    s.social_media_url = 'https://twitter.com/mapbox'
    s.documentation_url = 'https://www.mapbox.com/ios-sdk/'

    s.source = {
    :path => "/Users/robipresotto/Work/iSea/Mapbox/mapbox-gl-native/build/ios/pkg/static",
    }

    s.platform              = :ios
    s.ios.deployment_target = '8.0'

    s.requires_arc = true

    s.source_files = 'Headers/*.h', 'MGLDummy.m'
    s.resource_bundle = { 'Mapbox' => 'Mapbox.bundle/*' }
    s.vendored_library = 'libMapbox.a'
    s.module_name = 'Mapbox'

    s.frameworks = 'CoreLocation', 'CoreTelephony', 'GLKit', 'ImageIO', 'MobileCoreServices', 'QuartzCore', 'SystemConfiguration'
    s.libraries = 'c++', 'sqlite3', 'z'
    s.xcconfig = {
    'OTHER_CPLUSPLUSFLAGS' => '-std=gnu++11 -stdlib=libc++',
    'OTHER_LDFLAGS' => '-ObjC',
    }
end
```

- I got it on my debug, what's missing?

```ruby
Downloading dependencies

-> Installing Mapbox-iOS-SDK (2.1.2)

[!] Error installing Mapbox-iOS-SDK
 -> Mapbox-iOS-SDK (2.1.2)
    - ERROR | [iOS] unknown: Encountered an unknown error (Unsupported download strategy `{:path=>"/Users/robipresotto/Work/iSea/Mapbox/mapbox-gl-native/build/ios/pkg/static"}`.) during validation.
```
