### ISSUE TITLE
Use iOS/OS X NSURLRequest’s NSURLRequestReturnCacheDataElseLoad

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1824]
We're currently implementing our own SQLite-based caching so that we can implement custom caching logic. We circumvent NSURL*'s caches by specifying `NSURLRequestReloadIgnoringLocalCacheData` when loading resources so that we can [implement our own interpretation of the HTTP caching spec](https://github.com/mapbox/mapbox-gl-native/issues/896).

With iOS 9, network caches are shared across all apps, and using it could benefit GL native when the user uses more than one application that has GL maps. `NSURLRequest` actually supports what we want to do by specifying `NSURLRequestReloadIgnoringLocalCacheData`, so we could replace our `SQLiteCache` implementation for Cocoa with a lookup in the global cache (e.g. by specifying `NSURLRequestReturnCacheDataDontLoad`, which just obtains cached data if it's there and doesn't load otherwise).

**Comment by mb12** [comment]
Tile URLs have a vendor specific mapbox  access token. Wouldn't it prevent caching across apps?

**Comment by kkaefer** [comment]
> Tile URLs have a vendor specific mapbox access token. Wouldn't it prevent caching across apps?

Good point; this probably makes it impossible to cache across apps anyway. Also, @1ec5 informs me that the network cache sharing is just for the Safari in-app browser, and not for the generic networking stack. This probably means it doesn't make sense to pursue this.

FWIW, we are normalizing mapbox.com URLs so they drop the access_token when caching, so requests can be cached (in one app) regardless of the access token.

**Comment by jfirebaugh** [comment]
Closing since it sounds like this is a dead end.
