### ISSUE TITLE
Remove dependency on pkg-config

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#1825]
When using mason, we're currently relying on `pkg-config`. Instead, the mason packages should not rely on `pkg-config` and have the correct configuration flags baked into the package files already.

**Comment by springmeyer** [comment]
:+1: I'd be happy to ban pkg-config for mason packages overall: https://github.com/mapbox/mason/issues/68

**Comment by springmeyer** [comment]
Solved by #5359
