### ISSUE TITLE
remove build-time dependency on llvm.org

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1828]
This host has poor reliability, and when it goes down our builds fail.

**Comment by 1ec5** [comment]
Can we at least make use of Travis’ `cache:` option?

**Comment by jfirebaugh** [comment]
@springmeyer Do you know where in the build process the following is coming from:

```
$ curl -sSL "http://llvm.org/apt/llvm-snapshot.gpg.key" | sudo -E apt-key add -
curl: (56) Recv failure: Connection reset by peer
gpg: no valid OpenPGP data found.
```

**Comment by springmeyer** [comment]
@jfirebaugh - I think it is coming from the whitelisted apt package we use for upgrading clang++: https://github.com/mapbox/mapbox-gl-native/blob/108792420c1907f4ecf1d7b03f28e4a5ac33b27f/.travis.yml#L19

> Can we at least make use of Travis’ cache: option?
@1ec5 - good idea. But I went to read about this and see: `Note that APT caching is not available for the container-based infrastructure.` at http://docs.travis-ci.com/user/caching/

**Comment by ljbade** [comment]
Just hit this too.

Why o why Travis

**Comment by mikemorris** [comment]
+1 here, got tripped up on this trying to get https://github.com/mapbox/mapbox-gl-native/pull/2391 merged yesterday

**Comment by ljbade** [comment]
@1ec5 You sure it doesn't work on containers? @daniel-j-h post seems to say it does?

**Comment by 1ec5** [comment]
Based on the documentation, apt caching is unavailable to us, and it's an apt package that depends on llvm.org availability. Directory-based caching may work, but it doesn't look like it'll solve this particular problem.

**Comment by ljbade** [comment]
@1ec5 I see now directory caching != apt caching

**Comment by daniel-j-h** [comment]
You could set up a local mirror or make a snapshot of the packages (e.g. check out aptly), and cache its directory. Not sure if worth the effort. You also have to think about cache invalidation.

**Comment by jfirebaugh** [comment]
There doesn't seem to be any reasonable way to do this.
