### ISSUE TITLE
Limit raster loading to visible tiles

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#183]
Currently, raster tile loading is a bit weird. Every source should have a default "min tile size" (which is 512 for vector tiles, and e.g. 128 for raster tiles so they're drawn from 128 - 384 pixel size).

We need to do this on a per-source basis so that we can properly determine what tiles we actually need to load. Currently, we're loading way too many raster tiles because we're just blindly loading all children of a vector parent tile.

**Comment by jfirebaugh** [comment]
I don't think this is relevant any more. Reopen if I'm wrong.
