### ISSUE TITLE
Privatize emptyMemoryCache

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1833]
mapbox/react-native-mapbox-gl#65 exposes `-[MGLMapView emptyMemoryCache]` to React Native users. Should this method even be public? I see that it’s used in iosapp’s gear menu, as a way of simulating low memory conditions. However, it doesn’t seem to have a good use case beyond that, and it’s poorly named to boot.

/cc @bsudekum @incanus

**Comment by incanus** [comment]
No, this is not meant for public consumption.

**Comment by 1ec5** [comment]
Because this is public API, it needs to be deprecated before it can be removed. If it’s still useful in iosapp, then it should be redeclared via a category on MGLMapView and looked at askance.
