### ISSUE TITLE
Apple Mach O Linker Error

### ISSUE THREAD

**Issue by flightsimmer668** [mapbox/mapbox-gl-native#1847]
I'm new to software development and I've run out of Google and StackOverflow searches as to how to fix this problem, so I decided to post here.

I'm running Xcode 6.4 with Mapbox-GL 0.4.5-symbols installed via Cocoapods. I get this error when I try to run my project on my iPad Retina. Here is a screenshot of the linker error.
![screen shot 2015-07-08 at 5 25 42 pm](https://cloud.githubusercontent.com/assets/11444749/8572768/fb0cf2d0-2596-11e5-8d73-68f0b720bd48.png)

Please help me figure this out.

**Comment by 1ec5** [comment]
Mapbox GL doesn’t come with a “MapboxViewController” class. Any reference to it should be a compiler error. Since you’ve come as far as the linker, have you defined a MapboxViewController yourself?

**Comment by 1ec5** [comment]
Ack, never mind, I misread that log. Can you verify that your project has the `-ObjC` linker flag set? It should be set by CocoaPods automatically.

**Comment by flightsimmer668** [comment]
That -ObjC linker flag was set in the Project Target Build Settings, but not in the Pods, so I added it in. Now the project builds, but I get this runtime error in the console: dyld: Library not loaded: @rpath/Pods.framework/Pods
  Referenced from: /private/var/mobile/Containers/Bundle/Application/90EA36E2-FE37-4F3A-AA80-13198FEBAAB3/appName.app/appName
  Reason: image not found

**Comment by flightsimmer668** [comment]
ah, I found a solution to that: Pods.framework was set to required, not optional. In any case, setting the `-ObjC` linker flag in both the project and pods target solved the problem.

**Comment by 1ec5** [comment]
@flightsimmer668, that’s good to hear. Still curious as to how you got into this situation, though; `pod install` should set up the build settings correctly. What version of CocoaPods are you using?

**Comment by flightsimmer668** [comment]
yes, i thought it would. but also today I was tempted to install a pre-release version of cocoapods, maybe that was the problem. `pod --version` tells me i'm running `0.38.0.beta.2'

I was also using mapbox-gl 0.4.5-symbols but I downgraded to 0.4.0

**Comment by incanus** [comment]
:point_right: https://github.com/mapbox/mapbox-gl-native/issues/1849
