### ISSUE TITLE
Combine raster tiles

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#185]
Load raster tiles into a bigger texture (and do partial uploads with [`glTexSubImage2D`](http://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexSubImage2D.xml)), then create a buffer that contains triangles for all areas of that texture, and draw them in one batch.

This might also allow us to implement a "`needsClipping()`" API that allows us to reduce the the number of checkerboard images we need to draw.

**Comment by jfirebaugh** [comment]
Closing here because we decided against this in the equivalent gl-js issue: https://github.com/mapbox/mapbox-gl-js/issues/111.
