### ISSUE TITLE
allow iOS shape delegate color properties to be nil

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1850]
The methods that return `UIColor` for polylines/polygons should allow `nil` so that you don't have to provide a color for every shape and can use the default. 

I'm open to not doing this, too. 

@1ec5 @friedbunny

**Comment by 1ec5** [comment]
For reference, `-[MKOverlayPathRenderer lineWidth]` is 0 by default, and `fillColor` and `strokeColor` are nullable.

**Comment by friedbunny** [comment]
Allowing `nil` here seems sensible. This would effectively be the same as not defining the various delegates in the first place, no?

**Comment by incanus** [comment]
The difference is that you can choose which annotations you want to respond for.

**Comment by friedbunny** [comment]
@incanus Right, which is why we should do it. :+1:

**Comment by lilykaiser** [comment]
Closing due to ticket age. If this is still a problem, please re-open
