### ISSUE TITLE
clean up iOS notifyMapChange posting

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1853]
I doubt we need the serial operation queue stuff anymore since @jfirebaugh's work in https://github.com/mapbox/mapbox-gl-native/commit/6532438fe47bca1af690779ffa7292d6f1080d0c. Core GL fires these at the right time, including for animated changes, and we can likely simplify the iOS code.

**Comment by friedbunny** [comment]
Stale.
