### ISSUE TITLE
Implement Material Design In Test App

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1856]
See [documentation](http://developer.android.com/training/material/index.html) for more details.

**Comment by incanus** [comment]
Can we break this down any more concretely? Is there a way to do it incrementally?

**Comment by bleege** [comment]
Yep.  The main goal here is to make people aware that we're explicitly going to use Material instead of the previous styles now that Google has improved Backward Compatibility via the [Android Design Support Library](http://android-developers.blogspot.co.uk/2015/05/android-design-support-library.html) as of Google IO 2015.

#### Initial Setup

* [ ] Add Android Design Support Library to Gradle via `compile 'com.android.support:design:22.2.0'`
* [ ] Change "Old" Widgets To "New" Widgets
  * [ ] [ActionBarActivity](https://github.com/mapbox/mapbox-gl-native/blob/1a3ae887868e9ecd6f0fd69add4b7b504d941b95/android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MainActivity.java#L35) --> [AppCompatActivity](https://developer.android.com/reference/android/support/v7/app/AppCompatActivity.html)

#### On Going

* [ ] Use "New Design Widgets" like [FAB](http://www.google.com/design/spec/components/buttons-floating-action-button.html) and [Snackbar](http://www.google.com/design/spec/components/snackbars-toasts.html) instead of old ones.

#### Bigger Picture

* [Intro To Material Design Concepts](http://www.google.com/design/spec/material-design/introduction.html)

**Comment by hallahan** [comment]
:+1: I think this is going to be awesome. I'd also enjoy seeing a little bit of tweaking to give it the Mapbox look and feel.

**Comment by ljbade** [comment]
Interesting. Gets hard to keep track of all the UI paradigm changes on Android and the various compatibility libraries.

**Comment by bleege** [comment]
I'm going to start converting the TestGLApp to Material Design based on Chris Banes' [Cheesesquare demo project](https://github.com/chrisbanes/cheesesquare).  This will help ensure that the GL SDK, and specifically the MapView work properly in the new design paradigm that Google is promoting as well as what customers will likely expect.  It'll also make it easier to add new features for testing to the app by using the Navigation Drawer.

**Comment by bleege** [comment]
For future comparison, here are screenshots of the current UI.

![20150807-starting-point-1](https://cloud.githubusercontent.com/assets/989928/9140855/d14aeaea-3cf9-11e5-92e3-6eae516b07db.png)

![20150807-starting-point-2](https://cloud.githubusercontent.com/assets/989928/9140858/d41264ba-3cf9-11e5-97db-0e9564e64358.png)

**Comment by erf** [comment]
May i suggest implementing a transparent statusbar with a floating toolbar for maximum map view. ( like in google maps)

**Comment by bleege** [comment]
Initial conversion to Material Design has been completed.  It's been tested on Samsung Galaxy S5 running Android 21.  All that remains is to refactor the Compass UI from the SDK into the TestApp.  The functionality should stay in the SDK as is, but the FAB should be separated because the SDK should not force a design implementation on developers (outside the existing user dot and compass).

![20150807-main-screen](https://cloud.githubusercontent.com/assets/989928/9146060/14e8bcee-3d1f-11e5-964d-70e240c03b30.png)

![20150807-navdrawer](https://cloud.githubusercontent.com/assets/989928/9146062/18bb3842-3d1f-11e5-9264-47f24268e066.png)

**Comment by bleege** [comment]
Next up is to remove the FAB designed User Location Modes (None, Location, Follow) from the TestApp and place it in the SDK via an API.  The [Google Maps Android API](https://developers.google.com/android/reference/com/google/android/gms/maps/UiSettings) is a bit unclear about this, so I'm thinking that we mirror the Mapbox Android Raster SDK's [TrackingMode API](https://www.mapbox.com/mapbox-android-sdk/api/0.7.4/com/mapbox/mapboxsdk/overlay/UserLocationOverlay.TrackingMode.html).

**Comment by bleege** [comment]
Initial refactor to remove FAB UI for location from SDK and replace it with an API.  Part of this meant returning the Compass image, which was hidden under the Toolbar in Material Design setup.  Thinking this has to do with FrameLayout nature of MapView.  Will likely have to redo once follow modes UI is settled.  Screenshots below of before and after.

![20150810-compass-under-toolbar](https://cloud.githubusercontent.com/assets/989928/9183740/cfb217d8-3f76-11e5-8a77-a37ecd136bd9.png)

![20150810-compass-out-from-under-toolbar](https://cloud.githubusercontent.com/assets/989928/9183745/d2d5af06-3f76-11e5-8462-c68723eece1a.png)

**Comment by ljbade** [comment]
@bleege I have noticed a few bugs.

Tapping the compass does not reset to north.

Cycling through the GPS modes sometimes the GPS marker loses it's correct location relative to the map, panning the map fixes it.

**Comment by bleege** [comment]
Thanks for the :eyes: @ljbade.  It's not too surprising as quite a few things moved at once yesterday between UI and API setup, with a few more left for today (namely settling on a UX for specific features).  :-)

After ^^ wraps up then it'll be time to look at refactoring `MapView` to extend from something other than `FrameLayout`, with `ViewGroup` being the likely candidate.

The goal is for these changes to result in a common Material Design pattern that works on both Lollipop and 4.x Android versions.

**Comment by erf** [comment]
By moving stuff from the Test app to MapView, we are making it simpler for most users, but what if you have special uses cases fro gps or compass updates, like you like to control how often gps updates are, or you would like to save positions or do some other things..? You could add a second gps or compass listener, but wouldn't this cause overhead in performance, memory usage etc? A second option would be to add event listeners for gps and compas updates. A third options, would be to just move all that stuff to the test app and keep it there as a template for the user, or move it out to its own class.

**Comment by bleege** [comment]
@erf Thanks for the suggestions.  I agree that "making it simpler" is the correct thing that the project should be striving for.  [The thinking for moving the FloatingActionButton (FAB)](https://github.com/mapbox/mapbox-gl-native/issues/1856#issuecomment-128835629) from `MapView` (aka the SDK) to the TestGLApp is that it's actually a developer decision what UI element (if any) should be used for toggling UserLocation on or off.  For the time being the only UI elements that the SDK will provide are the UserLocation dot and the Compass image.

The way to do this meshes quite well with your ideas about GPS and compass listeners... have APIs at the SDK level that the developer can choose to use or not use.  The UserLocation API was setup to be this way in #1940, but as you suggest there are definitely more that can and will be built.

I also should note that only [the MapboxGLAndroidSDK part](https://github.com/mapbox/mapbox-gl-native/tree/master/android/java/MapboxGLAndroidSDK) will be bundled up and distributed to developers [via Maven Central as an Android Library (`*.aar`)](https://github.com/mapbox/mapbox-gl-native/issues/1672).  The [MapboxGLAndroidSDKTestApp](https://github.com/mapbox/mapbox-gl-native/tree/master/android/java/MapboxGLAndroidSDKTestApp) exists as a way for the development team to work with the SDK as well as to serve as examples for developers using the SDK in their apps.

**Comment by erf** [comment]
Thanks for filling me in. Sounds like it will be a good solution that will 'just work' in most cases, and maybe there will be options later for configuring for special options or users will just add those as needed. Mapbox as a gradle dependency will be really nice, but i hope the source also will be available to play with=)

**Comment by bleege** [comment]
> but i hope the source also will be available to play with

Most definitely.  This an open source project and it will remain on GitHub.  :+1:

**Comment by bleege** [comment]
Just finished up the conversion to using Material Design UI elements for development / testing / example purposes.  Was able to confirm that using `FrameLayout` for the base class of `MapView` should be fine for Material Design uses.  Only real issue is when a MapView is layered under an [AppBarLayout](http://developer.android.com/reference/android/support/design/widget/AppBarLayout.html) as the AppBar will float over the map.  The biggest problem from this is that it can be hard to see the Compass.  This is all to be expected though as it's related to vertical scrolling which is a core part of the AppBar concept.

The only thing that remains is to improve the performance of the Tracking Mode updates (None, Follow, and Bearing) as there are too many events on the UI thread for this now.  I'll create a new ticket to solve this separately, as we need to get the UserDot and Location code into the `master` branch sooner rather than later.

Merge is next.

![20150812-mapview](https://cloud.githubusercontent.com/assets/989928/9229918/1833fbf6-40e5-11e5-98fd-adc26bc7967b.png)
_Main View_

![20150812-navigationdrawer](https://cloud.githubusercontent.com/assets/989928/9229926/1fceca80-40e5-11e5-9bb4-5abf9a1709b3.png)
_Navigation Drawer_

**Comment by incanus** [comment]
This looks awesome! 

Totally small niggle here, but the shadow is getting cropped: 

![1833fbf6-40e5-11e5-98fd-adc26bc7967b](https://cloud.githubusercontent.com/assets/17722/9232057/693a0ef0-40e0-11e5-9a55-57c395c9c12a.png)

**Comment by bleege** [comment]
Good catch @incanus.  It's one of the discrepancies between KitKat and Lollipop in the Design Support Library.  I'll see if I can get it to not clip on Lollipop.

![screen shot 2015-08-12 at 2 31 28 pm](https://cloud.githubusercontent.com/assets/989928/9234646/9d21971e-40ff-11e5-9590-e8e52e077f09.png)
_KitKat Emulator_

**Comment by bleege** [comment]
In the short term I've removed the Shadow from the FAB, as the suggested work arounds were still clipping on Lollipop.  Based on what I've [seen on Stackoverflow](http://stackoverflow.com/questions/30552353/android-design-support-library-floatingactionbuton-fab-displaying-correctly-o) and [Google's own Android issue tracker](https://code.google.com/p/android/issues/detail?id=175068) there still seems to be a few kinks being worked out in the Android Design Support Library since it was released in May at Google IO.

![device-2015-08-12-144859](https://cloud.githubusercontent.com/assets/989928/9235376/04ba4124-4104-11e5-8fa2-a993a40a10bd.png)
_Lollipop Device_

![screen shot 2015-08-12 at 2 51 25 pm](https://cloud.githubusercontent.com/assets/989928/9235386/0de0667a-4104-11e5-8a5f-da0d838d023f.png)
_KitKat Emulator_

**Comment by bleege** [comment]
Ticketed out the more responsive User Location Mode work in #2049.  Thanks again to @erf for the great head start by building this.

The FAB Shadow has also been merged as of #2047 so all remaining issues for this ticket should be complete now.
