### ISSUE TITLE
Polyline and polygon on raster tile

### ISSUE THREAD

**Issue by honjo** [mapbox/mapbox-gl-native#1858]
Polyline and polygon, hidden behind when the raster tile at iOS.
https://www.mapbox.com/blog/mapbox-mobile-polylines/

**Comment by incanus** [comment]
Yep, we saw this too and think it was fixed in https://github.com/mapbox/mapbox-gl-native/commit/c00e473e46e2c0ee44545110522158167c4b8e34 in another branch — will check it out here.

**Comment by honjo** [comment]
Displayed! Thanx!

**Comment by incanus** [comment]
Do you mean you applied that patch and it fixed it? If so, please reopen here so that we can properly address it in `master`.

**Comment by incanus** [comment]
Going to look at this for b3.

**Comment by incanus** [comment]
Yep, this is improper use of `std::vector::end()`. 

<img width="577" alt="screen shot 2015-07-09 at 8 52 02 am" src="https://cloud.githubusercontent.com/assets/17722/8599911/d55dc7ae-2617-11e5-98cc-e774edb1dcee.png">

We should have all "normal" layers, then, shapes (latest last), then points.
