### ISSUE TITLE
investigate fitBounds link errors

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1859]
We've seen this in a couple places now (like https://github.com/mapbox/mapbox-gl-native/issues/1822#issuecomment-118136119) and it does not seem to be limited to non-Travis builds. 

```
Undefined symbols for architecture x86_64:
  "mbgl::Map::fitBounds(std::__1::vector<mbgl::LatLng, std::__1::allocator<mbgl::LatLng> >, mbgl::$_1, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> >)", referenced from:
      -[MGLMapView setVisibleCoordinates:count:edgePadding:animated:] in libMapboxGL.a(MGLMapView.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I went back through the routines around `mbgl::Map::fitBounds` to see if anything looked amiss. I think I have a few things; not sure how relevant they are. 

- [ ] We use `INFINITY` and `std::fmax`/`std::fmin`/`std::log2` etc. but don't `#import <cmath>`. 

- [ ] Use of `vec2<>` without a type, like so: 

  ```
  vec2<> swPixel = pixelForLatLng(bounds.sw);
  ```

  This isn't very explicit at the very least, but could it also be introducing some problems? 

- [x] Static analyzer run comes up pretty clean. 

  ![screen shot 2015-07-08 at 10 06 58 pm](https://cloud.githubusercontent.com/assets/17722/8588328/ae37f0be-25bd-11e5-83ac-99ecec662b72.png)

Anything jump out at anyone? 

@1ec5 @kkaefer @springmeyer @tmpsantos @brunoabinader

**Comment by incanus** [comment]
To clarify what is happening here, the build is finishing fully and appears fine, but folks using it externally sometimes see this link problem when trying to compile. This could be related to the way that we test GL inline vs. as a static library. Though I haven't seen this problem with our own static library (via Swift) usage.

**Comment by 1ec5** [comment]
`vec2` is declared to be `double` by default. The remaining static analyzer warnings are covered upstream. Importing cmath is a good idea, plus vector if we aren't already somewhere. Is there anything unusual about how LatLng is defined?

**Comment by springmeyer** [comment]
This might be a conflict with `-stdlib`. Is this replicable if you try linking a sample app against libmbgl with `-stdlib=libstdc++` (which is wrong, should be `-stdlib=libc++`)?

**Comment by incanus** [comment]
Going to build a test project to replicate this first, that we can track in VCS and get to the bottom of this.

**Comment by incanus** [comment]
Replicated: 

https://github.com/incanus/LinkerTest

This is an Objective-C app, downloading RC 1 w/o symbols and using the binary install method. Went through the setup instructions, then tried to build and got the `fitBounds` compile error.

**Comment by incanus** [comment]
Link problem doesn't happen on the the `-symbols` version (which is why we don't typically see it).

**Comment by incanus** [comment]
This was related to the declaration of `EdgeInsets` prior to https://github.com/mapbox/mapbox-gl-native/commit/3318a3ced0d0c115e8ba4be40e669619ce4537af, which created an anonymous `struct` that was causing problems with the `fitBounds` function symbols.
