### ISSUE TITLE
Fit to bounds across the antemeridian spans the whole world

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1867]
Along the lines of https://github.com/mapbox/mapbox-ios-sdk/pull/470#issuecomment-120119726, `fitToBounds()` spans the whole world if given a set of coordinates that straddles the antemeridian. This case is important for fitting the viewport to an annotation that straddles the antemeridian.

In order to do the right thing in all cases, this method would have to accept an additional parameter that indicates whether the intent is to span the Prime Meridian or antemeridian.

/cc @incanus @friedbunny

**Comment by lilykaiser** [comment]
Closing due to ticket age. If this is still a problem, please re-open

**Comment by 1ec5** [comment]
Forward-duping to #4664 and #9731.
