### ISSUE TITLE
[MGLAnnotationImage] does not work

### ISSUE THREAD

**Issue by xrayed** [mapbox/mapbox-gl-native#1872]
```objc
- (MGLAnnotationImage *)mapView:(MGLMapView *)mapView imageForAnnotation:(LocationBasedObjectAnnotation *)annotation {
  .....
    return [MGLAnnotationImage annotationImageWithImage:image reuseIdentifier:reuseIdentifier];
}
```

After update from 0.4.5 map annotations stopped being displayed if I use new delegate method

**Comment by 1ec5** [comment]
What format is the image in? Did you load it from a bundle resource or draw it on the fly?

**Comment by friedbunny** [comment]
Hi @xrayed, we're going to need a little bit more info. How and where are you adding your annotation? How is `image` set and what format is it?

**Comment by xrayed** [comment]
UIImage * image = [UIImage imageNamed:@"portrait_small_background_1"];
During debug I double checked that image object is there (not NULL)
I attached images.

Check if your code works correctly with @2x and @3x images
![portrait_small_background_1 3x](https://cloud.githubusercontent.com/assets/13271930/8620563/90645b5e-2720-11e5-9957-191ab103f3da.png)
![portrait_small_background_1 2x](https://cloud.githubusercontent.com/assets/13271930/8620564/908b9aac-2720-11e5-8de9-1be121e93943.png)

**Comment by friedbunny** [comment]
@xrayed Is there any console output — errors or warnings? Does the app crash?

**Comment by xrayed** [comment]
I'm out of office, I will provide console logs only tomorrow, there were no app crashes.

**Comment by xrayed** [comment]
No crash and nothing in console, I'll wait for next release and try again

**Comment by xrayed** [comment]
I got more details when I tried v0.5.1:

Here is delegate method:
- (MGLAnnotationImage *)mapView:(MGLMapView *)mapView imageForAnnotation:(LocationBasedObjectAnnotation *)annotation {
    UIImage * image = [UIImage imageNamed:@"portrait_small_background_1"];
    NSString * reuseIdentifier = NSStringFromClass(annotation.class);
    return [MGLAnnotationImage annotationImageWithImage:image reuseIdentifier:reuseIdentifier];
}

Console log output:
[INFO] {Worker}[Sprite]: Can't find sprite named 'com.mapbox.sprites.CharacterAnnotation'

The thing is that this line is shown different amount of times if I run app again and again, it never corresponds to number of Annotations I have added (currently I added 5 annotations)

If I change number of annotations to 1 and run app again it has permanent crash (see attachment)

![screen shot 2015-07-14 at 11 20 42](https://cloud.githubusercontent.com/assets/13271930/8670146/7886a4a4-2a1a-11e5-819a-a9d59c1b6f39.png)

**Comment by friedbunny** [comment]
The reuse identifier exists so that each delegate call doesn't need to load a new image. I'd suggest following a pattern that checks if `MGLAnnotationImage` exists with the desired identifier, like in [this example](https://www.mapbox.com/mapbox-gl-ios/examples/marker-image/):

```objc
- (MGLAnnotationImage *)mapView:(MGLMapView *)mapView imageForAnnotation:(id <MGLAnnotation>)annotation
{
    MGLAnnotationImage *annotationImage = [mapView dequeueReusableAnnotationImageWithIdentifier:@"whatever"];
    
    if ( ! annotationImage)
    {
        UIImage *image = [UIImage imageNamed:@"whatever"];
        annotationImage = [MGLAnnotationImage annotationImageWithImage:image reuseIdentifier:@"whatever"];
    }
    
    return annotationImage;
}
```

**Comment by xrayed** [comment]
but then my crash log is still valid since when I try with 1 annotation the delegate method will be called only once so [dequeueReusableAnnotationImageWithIdentifier] call will not help

**Comment by friedbunny** [comment]
@xrayed You're right, of course. :smile:

It looks like the annotations are being added in `viewDidLoad` — there was/is a crash (https://github.com/mapbox/mapbox-gl-native/pull/1874) when annotations are added too quickly after map initialization. Could you please try adding the annotations in `viewDidAppear`?

**Comment by friedbunny** [comment]
#1874 fixes this crash and will be included in the next release. In the meantime, please use add annotations in `viewDidAppear`. Thanks for your help in tracking this down, @xrayed.
