### ISSUE TITLE
Swift: MGLMultiPoint should use Int for pointCount

### ISSUE THREAD

**Issue by quicklywilliam** [mapbox/mapbox-gl-native#1878]
See https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKMultiPoint_class/index.html#//apple_ref/occ/instp/MKMultiPoint/pointCount

MKMultiPoint uses NSUInteger in Obj-c land, but Int for Swift. MGLMultiPoint uses Uint in Swift.

**Comment by 1ec5** [comment]
`swiftc` does the translation from Objective-C and Swift automatically, based on the Objective-C header, and it doesn’t appear to offer a way to customize the argument type. `pointCount` is declared identically in both MapKit and Mapbox GL:

```objc
@property (nonatomic, readonly) NSUInteger pointCount;
```

MapKit probably benefits from a custom mapping that goes beyond on-the-fly translation.

**Comment by 1ec5** [comment]
However, please feel free to [file a bug with Apple](http://bugreport.apple.com/) regarding the fact that `NSUInteger` is mapped to `Int`.
