### ISSUE TITLE
Circle annotations

### ISSUE THREAD

**Issue by EasyAsABC123** [mapbox/mapbox-gl-native#1882]
`RMCircle` doesn't appear to be defined in swift, how can I draw a simple circle?

```
var circle = RMCircle(position: position, radius: 3000)
```
instead I only have `MLGShape` and `MLGPolygon` but no `MLGCircle`

http://stackoverflow.com/questions/31364438/create-a-circle-in-mapbox-gl-for-ios

**Comment by 1ec5** [comment]
Mapbox GL for iOS doesn’t have an equivalent to `RMCircle` or `RMCircleAnnotation` yet. See also #1726, which tracks adding a great circle annotation type. For now, the workaround is to draw a many-sided polygon using `MGLPolygon`.

**Comment by bmeine** [comment]
I created a many sided polygon, but many of the points are removed if they're too close together unless at maximum zoom then the circle's borders appear smooth. The circle loses it's smooth roundness at lower zoom levels and at a low enough zoom will become a box/diamond.

Is there any way to force it to keep more points?

Thanks

**Comment by incanus** [comment]
> Is there any way to force it to keep more points?

Not right now — the proper fix here is in https://github.com/mapbox/mapbox-gl-native/issues/1740, which is part of the `v8` style spec. /cc @brunoabinader

**Comment by 1ec5** [comment]
The Cocoa side of this is being tracked in #2167.
