### ISSUE TITLE
MGLMapboxEvents tests are failing

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#1887]
`-[MetricsTests testPushEventAddsToEventQueue]` and `-[MetricsTests testTimerCreatedAfterEventPushed]` sometimes [time out on Travis](https://travis-ci.org/mapbox/mapbox-gl-native/jobs/70809933#L1016), causing test failures that I can’t reproduce locally.

/cc @bleege @incanus

**Comment by brunoabinader** [comment]
Got this in https://travis-ci.org/mapbox/mapbox-gl-native/jobs/70906410.

**Comment by 1ec5** [comment]
These tests have started failing locally for me as well. They never fail individually, only when running the whole suite.

**Comment by jfirebaugh** [comment]
@1ec5: Are the failures due to code changes (bisectable?) or something external?

**Comment by 1ec5** [comment]
@jfirebaugh, I believe these failures may be influenced by code changes. I had a go at bisecting today, but it was a bit confusing because different failures came in and out at different times – pretty consistently for each commit. So there may be multiple issues.

**Comment by 1ec5** [comment]
Some of the failures I’m seeing are legitimate failures, better described by #2036.
