### ISSUE TITLE
{Worker}[Sprite]: Can't find sprite named 'camera-11'

### ISSUE THREAD

**Issue by tomtaylor** [mapbox/mapbox-gl-native#1893]
I'm seeing lots of log entries saying `{Worker}[Sprite]: Can't find sprite named 'camera-11'` when panning around over central London, using Mapbox Streets style. I'm guessing a sprite is missing from the build?

**Comment by tomtaylor** [comment]
Oh, this is probably the same issues as #1877.

**Comment by 1ec5** [comment]
Tracking in #1885 now.

**Comment by 1ec5** [comment]
Now tracking in mapbox/mapbox-gl-styles#232.
