### ISSUE TITLE
setDirection animated=true does not work (Android) 3c1d461

### ISSUE THREAD

**Issue by erf** [mapbox/mapbox-gl-native#1895]
MapView.setDirection animated==true does not work (Android)
MapView.resetNorth() does neither
commit 3c1d461

**Comment by ljbade** [comment]
Is this still happening?

**Comment by erf** [comment]
Yes

**Comment by bleege** [comment]
`resetNorth()` is working via the Compass currently.

**Comment by bleege** [comment]
Tested `setDirection()` in TestApp by replacing the Compass calling of `resetNorth()` with `setDirection(60, true)`.  Tried using `setDirection(60)` and that also worked.  Considering this issue resolved.  Please feel free to reopen though.
