### ISSUE TITLE
Adding annotation fails with EXC_BAD_ADDRESS

### ISSUE THREAD

**Issue by aleksandr-vin** [mapbox/mapbox-gl-native#1896]
Locked in https://www.mapbox.com/guides/first-steps-gl-ios/#adding-a-point-annotation

I've done the tutorial till annotation section. Then it started to fail on run.

![screen shot 2015-07-17 at 00 48 31](https://cloud.githubusercontent.com/assets/223293/8736019/e3012a52-2c1d-11e5-9d9c-291e826d0ae4.png)

 cat Podfile.lock
PODS:
  - MapboxGL (0.5.1)

DEPENDENCIES:
  - MapboxGL

SPEC CHECKSUMS:
  MapboxGL: 4198dd3100fa012d3df5fc26ad13b69f6834473c

COCOAPODS: 0.37.1

**Comment by friedbunny** [comment]
Thanks for posting about this, @aleksandr-vin. #1874 fixes this crash and will be included in the next release. In the meantime, please use add annotations in `viewDidAppear`. I'll update the guide with this workaround.

**Comment by aleksandr-vin** [comment]
@friedbunny -- not regarding this issue, but -- is there any way to cache vector tiles in Mapbox GL like in Mapbox iOS SDK https://www.mapbox.com/mapbox-ios-sdk/#tile_caching__class ?

**Comment by friedbunny** [comment]
@aleksandr-vin Not yet, follow https://github.com/mapbox/mapbox-gl-native/issues/584 for progress.
