### ISSUE TITLE
Crash in uv__async_event when adding annotation to mapView

### ISSUE THREAD

**Issue by mejackreed** [mapbox/mapbox-gl-native#1897]
Following the guide here: https://www.mapbox.com/guides/first-steps-gl-ios/

When adding the annotation to the map, I'm getting a crash `exc_bad_access`

```
...
    0x10a870b23 <+147>: xorl   %esi, %esi
    0x10a870b25 <+149>: movq   -0x28(%rbp), %rax
    0x10a870b29 <+153>: movl   $0x0, 0x58(%rax)
    0x10a870b30 <+160>: movq   -0x28(%rbp), %rax
    0x10a870b34 <+164>: movq   0x40(%rax), %rax
    0x10a870b38 <+168>: movq   -0x28(%rbp), %rdi
    0x10a870b3c <+172>: callq  *%rax
    0x10a870b3e <+174>: movq   -0x20(%rbp), %rax
    0x10a870b42 <+178>: movq   0x8(%rax), %rax
    0x10a870b46 <+182>: movq   %rax, -0x20(%rbp)
    0x10a870b4a <+186>: jmp    0x10a870ab2               ; <+34> at 
...
```

cat Podfile.loc

PODS:
  - MapboxGL (0.5.1)

DEPENDENCIES:
  - MapboxGL

SPEC CHECKSUMS:
  MapboxGL: 4198dd3100fa012d3df5fc26ad13b69f6834473c

COCOAPODS: 0.37.2

**Comment by mejackreed** [comment]
Ok so after reading the docs here: https://www.mapbox.com/mapbox-gl-ios/examples/marker-image/

It appears that the issue is a documentation issue on the guide.

**Comment by friedbunny** [comment]
Thanks for posting about this, @mejackreed. #1874 fixes this crash and will be included in the next release. In the meantime, please use add annotations in `viewDidAppear`. I'll update the guide with this workaround.
