### ISSUE TITLE
Another way of loading maps data

### ISSUE THREAD

**Issue by stepanmazokha** [mapbox/mapbox-gl-native#1900]
I am new to this library. Maybe didn't find the solution, but it already exists - then sorry about this opened issue.

But I am looking for a way of using Mapbox GL for Android & iOS (currently android) with my own maps data. So I have data in GeoJSON format and how can they be loaded into the project for rendering? In other words, I don't want to use Mapbox maps, but the library is awesome :)

So can I load external data? And if yes - then now can it be implemented? 

Would be thankful for any information and advice. Thanks in advance.

**Comment by friedbunny** [comment]
You'll need a vector tile source that conforms to the [Mapbox Vector Tile Spec](https://github.com/mapbox/vector-tile-spec). The best and most excellent way to do this is to use Mapbox services, but there are other possibilities.

GeoJSON is best suited for annotations and data overlaid on top of base maps — [like this GeoJSON line example](https://www.mapbox.com/mapbox-gl-ios/examples/line-geojson/).

**Comment by stepanmazokha** [comment]
@friedbunny yes, but this example shows adding line on the mapbox map. it doesn't explain, how to use other maps source with the library. and my idea was to use my own maps with mapbox gl. can i somehow use my own maps with mapbox gl? or only standard maps can be used?

**Comment by ljbade** [comment]
@stepanmazokha As long as you set up a vector tile endpoint you can send whatever data you want to create your own maps.

Of course this is not straightforward but is doable if you connect the various pieces yourself. However with Mapbox Studio you can create and upload to our servers a custom vector data source without too much effort.

Then it is simply a case of pointing the GL style to this new vector data source.

**Comment by ljbade** [comment]
@stepanmazokha Here are the guides: https://www.mapbox.com/guides/source-quickstart/
https://www.mapbox.com/guides/source-manual/
