### ISSUE TITLE
Can't launch android example. libmapbox-gl.so is not found.

### ISSUE THREAD

**Issue by stepanmazokha** [mapbox/mapbox-gl-native#1902]
I found the same issue here #859, but there is no solution to the problem. 

Here is the list of what I've done:
   I cloned the repo to my desktop, opened the project in android studio, launched make command - everything was OK, no problems detected. 

But when I launched the application on VM (x86) - the first and only exception was "libmapbox-gl.so is not found". 

The folder 'android/java/MapboxGLAndroidSDK/src/main/jniLibs/armeabi-v7a/' does not exist at all in the cloned project. 

What should I do? And how far is the mapbox gl from release? Would be great to try its best features :)

**Comment by mb12** [comment]
You would have to create x86 specific .so.
ANDROID_ABI=x86 make android

**Comment by stepanmazokha** [comment]
@mb12 where should i run this command?

**Comment by mb12** [comment]
You have to run it in the root directory of your git repo.

cd mapbox-gl-native; ANDROID_ABI=x86 make android

**Comment by bleege** [comment]
Different ABIs can also be generated using the following command:

```sh
// Pattern
 make android-lib-ABI

// Example for x86
 make android-lib-x86
```
This will build `libmapbox-gl.so` for the specified and place it in the `jniLibs` directory.  The screenshot below shows what this looks like after running `make android-lib-x86` after I'd already built for the default `armeabi-v7a` that `make android` does.  It's perfectly acceptable to have N ABI .so in the project at once (aka the TestApp will still run).

Incidentally, one can create all the supported ABIs by running:  `make android-all`.

![20150722-libmapbox-so-abi](https://cloud.githubusercontent.com/assets/989928/8835225/b8deca76-307e-11e5-9127-3a73bb8b7a0e.png)

**Comment by mb12** [comment]
Is there a target to do it for all the architectures?

**Comment by bleege** [comment]
@mb12 Yep,  it's `make android-all`

**Comment by ljbade** [comment]
Should also note that down the road we hope to get the static lib building integrated into Gradle so that hitting build in Studio will also generate the .so files.
