### ISSUE TITLE
Crash when calling latLngForPixel(point)

### ISSUE THREAD

**Issue by vespakoen** [mapbox/mapbox-gl-native#1905]
I am trying to open a modal when clicking somewhere on the map.
I started by adding some code directly into `MapView.java` to see if I can get a result.
However, upon calling `mNativeMapView.latLngForPixel(point);` the app crashes without any useful out put.

```cpp
// Called for single taps after a delay
@Override
public boolean onSingleTapConfirmed(MotionEvent e) {
    PointF point = new PointF(e.getX(), e.getY());
    LatLng latLng = mNativeMapView.latLngForPixel(point);
    Log.v("TEST", String.valueOf(latLng.getLatitude()));
    return true;
}
```

Perhaps I should change some parameters in android studio to get a backtrace?

Thanks

**Comment by vespakoen** [comment]
Ah, my log level was simply not set low enough.

I got a hint now:
```
07-21 00:20:24.734    4501-4501/com.mapbox.mapboxgl.testapp W/dalvikvm﹕ JNI WARNING: GetDoubleField for field 'x' of expected type D, got F
07-21 00:20:24.734    4501-4501/com.mapbox.mapboxgl.testapp W/dalvikvm﹕ in Lcom/mapbox/mapboxgl/views/NativeMapView;.nativeLatLngForPixel:(JLandroid/graphics/PointF;)Lcom/mapbox/mapboxgl/geometry/LatLng; (GetDoubleField)
```

It seems in jni.cpp mapbox is trying to get a double value from the PointF object

```cpp
jfloat x = env->GetDoubleField(pixel, pointFXId);
```

However, the PointF object only accepts floats.

**Comment by vespakoen** [comment]
Fixed it by changing `GetDoubleField` to `GetFloatField`

See my pull request here: https://github.com/mapbox/mapbox-gl-native/pull/1926

**Comment by ljbade** [comment]
Seen this in Crashlytics too

**Comment by ljbade** [comment]
Thanks for find the cause @vespakoen

**Comment by incanus** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/1926.
