### ISSUE TITLE
raster ground overlay

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1906]
It's not tiles and it's not fill pattern images — it's raster imagery "stuck to" the map surface with a given bounding box, and zooming and shrinking with the map. Think of something like a geo-referenced floor plan drawing on top of the map. 

Two stages of iteration here: 

* Basic single-res image support which supports a limited zoom range to either side of the 100% raster scale before unacceptable distortion
* Multi-sampled, possibly even tiled imagery so that all zooms look crisp

**Comment by jfirebaugh** [comment]
Duplicate of #1350.
