### ISSUE TITLE
Consider adding support for using tiles from a given zoom across a wider range of zooms

### ISSUE THREAD

**Issue by chris780** [mapbox/mapbox-gl-native#1908]
Vector tiles are very scalable, so, for instance, it's often reasonable to use tiles generated for zoom 10 all the way down to zoom 12 without fetching entirely new tiles at zoom 11. Reusing tiles across multiple zooms can reduce the total amount of data that clients need to download.

It would be useful to be able to tell a tile source to request tiles only at specific integer zooms - perhaps by adding a "tilezooms" array to the resource response.

**Comment by ansis** [comment]
We used to have something implemented in mapbox-gl-js way back but it was removed.

I don't think the savings from this would be significant as long as the vector tiles is thinned and simplified appropriately when they are created.

I don't see us implementing this so I'll close this issue. If you find that it does significantly reduce data and are interested in contributing this please re-open.
