### ISSUE TITLE
MGLUserAnnotation not displaying 

### ISSUE THREAD

**Issue by JohnRbk** [mapbox/mapbox-gl-native#1912]
Looking at Stackoverflow post [here](http://stackoverflow.com/questions/31546489/how-to-display-user-location-marker-in-mapbox-gl) it seems like `MGLUserLocation::setLocation` tests the distance between new and old locations before actually setting the new value. Because the initial latitude and longitude as set to `MAXFLOAT`, one of the conditionals checking distance always returns zero, preventing the new location value from being set:

```
 - (void)setLocation:(CLLocation *)newLocation {
    if ([newLocation distanceFromLocation:_location] /* always zero? */ 
     && newLocation.coordinate. latitude != 0 
     && newLocation.coordinate.longitude != 0)`...
```

I think this may be preventing the display of the MGLUserLocation annotation.

To test out my theory, I made the small change below (`MGLUserLocation.m`) and it seems to have worked - the MGLUserAnnotation now renders on my map as a pulsating circle.

```
 - (void)setLocation:(CLLocation *)newLocation
 {
    // new code to test my theory out
     if(_location.coordinate.latitude == MAXFLOAT || _location.coordinate.longitude == MAXFLOAT) {
          [self willChangeValueForKey:@"location"];
          _location = newLocation;
          [self didChangeValueForKey:@"location"];
    }`
    else if ([newLocation distanceFromLocation:_location] && newLocation.coordinate. latitude != 0 &&
             newLocation.coordinate.longitude != 0)
     {
         [self willChangeValueForKey:@"location"];
         _location = newLocation;
         [self didChangeValueForKey:@"location"];
     }
}
```

**Comment by JohnRbk** [comment]
Forgot to mention: Xcode 7 Beta 3, 0.5.2 mapbox-gl build, targeting ios9.

**Comment by 1ec5** [comment]
Yes, this looks like an iOS 9-specific issue and the fix appears to work.

**Comment by incanus** [comment]
I have occasionally noticed an issue that I've been meaning to report with the user dot related to wrapped panning horizontally and the dot prematurely then disappearing. Try zooming out all the way, panning the world past a few times, and see what I mean. Not sure if related.

**Comment by 1ec5** [comment]
@incanus, I’m pretty sure that’s #1755.
