### ISSUE TITLE
MapboxGL Pod does not work with new version of CocoaPods (0.38.0)

### ISSUE THREAD

**Issue by xrayed** [mapbox/mapbox-gl-native#1914]
I ran this test on 2 different machines with my main project and hello world project

![screen shot 2015-07-22 at 17 08 49](https://cloud.githubusercontent.com/assets/13271930/8828818/58e0bf38-3094-11e5-9e4d-b468bf8a01cb.png)

**Comment by 1ec5** [comment]
Huh, this should’ve been fixed by #1876, which is in 0.5.1. What’s your Podfile entry look like?

**Comment by xrayed** [comment]
platform :ios, '8.0'
pod 'MapboxGL'

**Comment by 1ec5** [comment]
We removed the requirement for `-ObjC` in #2967. If you’re still seeing this issue, please make sure you’ve got an .xcworkspace open rather than your project’s individual .xcodeproj.
