### ISSUE TITLE
Tidy up Android annotations

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#1920]
Following on from @hallahan and @nulvinge work on Android annotation support in https://github.com/mapbox/mapbox-gl-native/pull/1899

There are a few things that still need to be tidied up or implemented:
- [x] replace the added C style casts in `jni.cpp` with C++ style casts (spotted a few in @nulvinge commit too)
- [x] remove the commented out code in `jni.cpp`
- [x] check error handling in `annotation_segment_from_latlng_jlist` - I think it is OK, should raise Java exception
- [ ] exception handling in `nativeAdd*` functions and the corresponding TODOs in `NativeMapView.java` - I think this should be fine, the `-1` return path should result in a Java exception anyway via JNI `CheckException()`
- [x] not sure about location of `readPolygons` I have been trying to keep helper functions at the top of the file to seperate them from the JNI `native*` methods... I think it should also have similar naming style to the other Javs <-> C++ object conversion functions?
- [ ] remove all the TODO/UNIMPLEMENTED comments from the Java files and instead create GitHub issues to track these
- [ ] consider collapsing the single and multiple/array variants of the polygon functions with just the array variant and instead forward the single variant to the array variant in the Java side - reduces duplicated code
- [ ] convert markers and polylines to also take arrays
- [x] @nulvinge for some reason you changed `Annotation` `getId()` from `long` to `Long`?
- [ ] support Parceable, Serializable, equals, hashCode, toString for all new annontations objects
- [x] correctly call `DeleteGlobalRef` in error cases in `JNI_OnLoad`
- [x] make sure class and method IDs are extern
- [x] tidy up ordering in JNi file to follow existing order
- [ ] implement other sprite methods
- [ ] refactor some of the array conversion code into shared functions
- [ ] annotation `get/setID` should not be public
- [ ] do something about the commented `getWorldBoundsMeters`
- [ ] do something about the unused `visible` field
- [ ] updating Annotation properties updates the map
- [ ] Annotation objects can only exist with id
- [ ] move remove() to Annotation objects
- [ ] save annotation state

Also making a quick note that the test app now defaults to zooming into a fixed location at startup to show the test annotations. Perhaps it is a better idea to have this happen when the annotations are toggled on?

@kkaefer Do you think it would be a good idea to turn on C style cast compile warnings/errors? Might help stop them creeping into the code.

/cc @bleege

**Comment by bleege** [comment]
@ljbade  :+1:

**Comment by ljbade** [comment]
First pass in https://github.com/mapbox/mapbox-gl-native/tree/android-annotation-tidyup

**Comment by erf** [comment]
There's a problem in Android where Markers don't show up until i zoom the map. It does work if i add markers with a timer Handler with 1 sec delay to it.

**Comment by erf** [comment]
I've found another issue.. If call 'startActiviyForResult' and then in the same activity in onResume i try to add a marker, the app crashes.

**Comment by erf** [comment]
I created two new issues #2095 and #2096

**Comment by bleege** [comment]
Bumping to `0.2.0`.  @ljbade Should also consider breaking the remaining tasks into separate tickets for easier tracking.

**Comment by ljbade** [comment]
Pretty much done. Remaining stuff already in tickets.
