### ISSUE TITLE
Expose polyline pattern options in MGLMapViewDelegate?

### ISSUE THREAD

**Issue by tomtaylor** [mapbox/mapbox-gl-native#1922]
At the moment we can control alpha, line colour, width, etc. I know there's work in progress to expose richer controls over annotation styling, but in the short term, would it be possible to expose a line pattern delegate method to enable dotted/dashed lines?

**Comment by friedbunny** [comment]
This sounds good to me, but I'm unsure on our plans here. @incanus?

**Comment by incanus** [comment]
This is basically subsumed by https://github.com/mapbox/mapbox-gl-native/issues/1734.
