### ISSUE TITLE
(Question)Using comma separator in source url.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1923]
The mapbox-streets-v7 uses the following to specify url for source "composite".
     
 "url": "mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6",

Can someone please clarify why it uses a comma in the url?

1.) Is it just another way of passing some parameter (after the url is normalized)  instead of using key=value pair?

or

2.) Is this some way of specifying multiple sources in style.json that is handled optimally in the client?

**Comment by ljbade** [comment]
@mb12 this syntax is a way to specify multiple sources.

It is optimal because our tile servers combine both sources into a single vector tile layer instead of two separate layers. This reduces the number of network requests and generally improves performance of the maps.

**Comment by mb12** [comment]
Thanks  @ljbade for the clarification.
