### ISSUE TITLE
(Android) Device reboots after few minutes of usage (consistently reproducible).

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#1927]
This consistently reproduces on Samsung Nexus S. I've tried two different Nexus S handsets.

- Simply use the sample app for a few minutes.

The device will reboot.

**Comment by bleege** [comment]
Wow...  that's interesting to learn.  Looking at the [phone specs](http://www.gsmarena.com/samsung_google_nexus_s-3620.php) it appears to not have much on board memory.  Wondering if that is contributing as there may be a memory leak somewhere in the TestApp code that eventually pushes it over the edge.  Can you verify heap usage using Android Studio?

**Comment by ljbade** [comment]
I noticed that the low memory https://github.com/mapbox/mapbox-gl-native/issues/1263 and cache size control are not wired up. This could contribute to the problem.

**Comment by mb12** [comment]
With the latest repo, the device no longer reboots.
