### ISSUE TITLE
iOS app crashes while loading specific image for annotation

### ISSUE THREAD

**Issue by andrewstay** [mapbox/mapbox-gl-native#1936]
Please load images attached as MGLAnnotationImage.
Application crashes with util::SpriteImageException("Sprite image pixel count mismatch")

![blue-cafe](https://cloud.githubusercontent.com/assets/13018567/8906058/9f26a2b6-346b-11e5-96b3-94f1329ce5d4.png)
![blue-cafe 2x](https://cloud.githubusercontent.com/assets/13018567/8906061/a0e38a06-346b-11e5-9274-8e68602c9218.png)

**Comment by friedbunny** [comment]
`Sprite image pixel count mismatch` is actually a fairly accurate error message in this case: the image sizes aren't matched.

@andrewstay, your `@2x` image is 55x79, when it should be an exact doubling of the 28x40 `@1x` image. Resizing the `@2x` resource to 56x80 fixes this.

@kkaefer I'm not sure how much wiggle room we have here in regards to sprite dimensions, is this something that can/should be made more lenient?

**Comment by yaalaa** [comment]
shame on mapbox-gl-native

**Comment by 1ec5** [comment]
Tracking a fix in #2198 now.
