### ISSUE TITLE
Implement missing basic APIs

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#1943]
Having a quick look at the Google Maps API there are a few basic things we don't expose in the API yet:
- camera position changes, e.g. zoomBy, panTo etc https://developers.google.com/android/reference/com/google/android/gms/maps/CameraUpdateFactory
- various configuration toggles for gestures etc (should also implement options in a separate class like this for easier saving of state? annotations work follows this pattern) https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMapOptions https://developers.google.com/android/reference/com/google/android/gms/maps/UiSettings

/cc @bleege

**Comment by incanus** [comment]
@1ec5 is handling some core camera work in https://github.com/mapbox/mapbox-gl-native/issues/1834 (no movement there yet, but that's been his scrum-mentioned focus).

**Comment by 1ec5** [comment]
mbgl already has zoomBy and panTo support; that ticket is about being able to set multiple properties at once and have them animate simultaneously.

**Comment by bleege** [comment]
This is good stuff @ljbade.  Let's not worry too much about this yet for Android as we need to get some of the other basic API (Annotations, User Dot, GLSurfaceView, etc) built out first.

**Comment by ljbade** [comment]
Yeah I'll close this for now until camera API is ready.

**Comment by bleege** [comment]
Actually, let's leave this open so that we remember to build it.  :-)  We'll just change the milestone.

**Comment by ljbade** [comment]
Only thing missing really is the zoom controls setting.

**Comment by ljbade** [comment]
Also we could rename the `setZoomEnabled` etc to Google's more accurate `setZoomGesturesEnabled` however we can do this if we create a separate Options class.

I am working on a PR to add `setZoomControlsEnabled` and `setAllGesturesEnabled`
