### ISSUE TITLE
Implement styleId, improve styleUrl

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#1947]
Noticed Android does not have `styleId`.

`styleUrl` also needs some changes:
- allow `null` to choose default map style
- additional validation to ensure any `asset://` URLs are only in the list of `bundledStyleUrls`

Add `bundledStyleUrls`

**Comment by 1ec5** [comment]
It's styleID and styleURL now on the iOS side.

**Comment by bleege** [comment]
Bumping to `0.2.0`

**Comment by ljbade** [comment]
I'm not going to implement styleID on Android. Instead I might add a static function that formats a mapbox URL or just document it well in #2002.

Also going to look at adding static strings for the bundled styles.

**Comment by bleege** [comment]
@ljbade Can you explain why you decided not to implement styleID?

**Comment by ljbade** [comment]
@bleege It is redundant. `setStyleUrl` is a superset of `setStyleId`. I have carefully documented in JavaDoc that `mapbox://styles/user/style` is the correct way to load a custom Studio style. It is also the URL Studio gives you to copy paste into your app/webpage. Finally this provides parity with JS API (if I understand @jfirebaugh).

Also @1ec5 mentioned that `setStyleId` is a workaround for Xcode which can't handle NSURL functions in Interface Builder and that he was contemplating moving it to the IB only header (ie deprecating it for code use).

**Comment by bleege** [comment]
@ljbade Cool!  Thanks for explaining.
