### ISSUE TITLE
Implement missing geography functions in Android from iOS

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#1948]
In `MGLMapView.mm` there is a bunch of functions under "Geography" that have not been implemented in Android.

**Comment by 1ec5** [comment]
Not all of them are publicly exposed; see MGLMapView.h for the public ones. There is a bunch more geometry in MGLGeometry.h as well.

**Comment by ljbade** [comment]
OK specific public ones are at https://github.com/mapbox/mapbox-gl-native/issues/2076

As for `MGLGeometry` seems Android missing:
- `MGLCoordinateBoundsGetCoordinateSpan`
- `MGLCoordinateBoundsOffset`
- `MGLStringFromCoordinateBounds`
- `MGLCoordinateBoundsIsEmpty`

**Comment by 1ec5** [comment]
Note that the standalone functions in MGLGeometry should probably be implemented on Android as methods of a separate class of some sort. We’ll want a `CoordinateBounds` class, for example.

* `MGLCoordinateBoundsGetCoordinateSpan`: `BoundingBox.getLatitudeSpan()` and `BoundingBox.getLongitudeSpan()` are already implemented, but it would make sense to combine them into a `BoundingBox.getSpan()` that returns a `CoordinateSpan`.
* `MGLStringFromCoordinateBounds`: Already implemented as `BoundingBox.toString()`.

**Comment by ljbade** [comment]
@1ec5 good spotting!

**Comment by ljbade** [comment]
Need to implement `BoundingBox.getSpan()`, `MGLCoordinateBoundsOffset` and `MGLCoordinateBoundsIsEmpty`

**Comment by tobrun** [comment]
The requested methods have been made obsolete in favor of `LatLngSpan` and `LatLngBounds`. 
Closing.
