### ISSUE TITLE
-[MGLMapView setShowsUserLocation] has no effect

### ISSUE THREAD

**Issue by andrewstay** [mapbox/mapbox-gl-native#1949]
self.map.showsUserLocation = NO;
  self.map.userTrackingMode = MGLUserTrackingModeFollowWithHeading;
And I still get big blue dot with white stroke representing user location.

**Comment by 1ec5** [comment]
We currently automatically show the user dot if you set the user tracking mode.

**Comment by andrewstay** [comment]
I suppose this is wrong because showsUserLocation is set to NO

**Comment by incanus** [comment]
Like MapKit, turning on `userTrackingMode` to track the user implicitly turns on `showsUserLocation`.

**Comment by friedbunny** [comment]
@andrewstay Is your intention to follow the user's location without showing the dot? That's not a use case we cover right now, though you may be able to override the dot's visual appearance.

**Comment by incanus** [comment]
> That's not a use case we cover right now, though you may be able to override the dot's visual appearance.

When we hit https://github.com/mapbox/mapbox-gl-native/issues/1784, we will make the `userLocation` work in this manner as well, meaning like MapKit, you can return `nil` to use the default or return a custom (or blank/hidden) view for the user dot to hit this use case.

**Comment by 1ec5** [comment]
In the meantime, a somewhat kludgy workaround is to get `[mapView objectForKeyPath:@"userLocationAnnotationView"]`, which is a UIView, and set its `hidden` property to `NO`.

**Comment by andrewstay** [comment]
@friedbunny the intention is to provide a custom UI for user location. To do that I need the framework to hide/do not show the default one

**Comment by 1ec5** [comment]
In that case, I recommend implementing your own user location tracking inside your MGLMapViewDelegate's `-mapView:didUpdateUserLocation:`.

**Comment by andrewstay** [comment]
That's is the goal. But I need the default one to get hidden first!

**Comment by 1ec5** [comment]
I was thinking that, by implementing your own user location tracking, you could avoid setting `userTrackingMode`, which is what's forcing the user dot to display. However, the combination of hiding the user dot and leaving user tracking off means MGLMapView won't send you location updates; you'll have to register for Core Location updates yourself.

I agree that ultimately we need to support customizing the user dot's appearance. It's understandable that you'd like to avoid reaching in and grabbing the private `userLocationAnnotationView`. It is pretty likely, however, that that property will only cease to be called that or be a UIView when we implement #1784.

**Comment by andrewstay** [comment]
Why would you need the delegate method then?
MGLMapViewDelegate's -mapView:didUpdateUserLocation:.

**Comment by 1ec5** [comment]
Right, in that case, the delegate method is no longer relevant (never gets called). If you implement your own user tracking directly atop CLLocationManager, your CLLocationManagerDelegate method would get called and would be responsible for panning the map view.
