### ISSUE TITLE
userTrackingMode = MGLUserTrackingModeFollowWithHeading does not have proper UI

### ISSUE THREAD

**Issue by andrewstay** [mapbox/mapbox-gl-native#1950]
When user tracking mode is set to MGLUserTrackingModeFollowWithHeading it is expected to get appropriate graphics for user headings and automatic updates for it.

**Comment by friedbunny** [comment]
https://github.com/mapbox/mapbox-gl-native/issues/1093 tracks the implementation of this.

**Comment by 1ec5** [comment]
Mapbox GL does deliver automatic heading updates, however. Are they not coming through for you?

**Comment by andrewstay** [comment]
I suppose if I set map.showsUserLocation = YES; and map. userTrackingMode = MGLUserTrackingModeFollowWithHeading I would expect framework to handle UI automatically.
