### ISSUE TITLE
The using location icon does not disappear when app terminates

### ISSUE THREAD

**Issue by webventil** [mapbox/mapbox-gl-native#1955]
When using  ``NSLocationAlwaysUsageDescription`` and a ``MGLMapView``the "is using location" icon in the status bar does not disappear even the app is terminated. Only after deleting the app it disappears or after calling ``stopMonitoringVisits()`` on a ``CLLocationManager``.

**Comment by friedbunny** [comment]
This is expected behavior, due to the way [Mapbox Metrics](https://www.mapbox.com/blog/mobile-location-analytics/) functions — [check out this FAQ entry](https://www.mapbox.com/help/private-mobile/) for more information.
