### ISSUE TITLE
Developer build "make iproj" can't find Boost.

### ISSUE THREAD

**Issue by adozenlines** [mapbox/mapbox-gl-native#1961]
Developer builds broken

**Comment by 1ec5** [comment]
Did you install the [dependencies](https://github.com/mapbox/mapbox-gl-native#depends)? You can get Boost via [Homebrew](http://brew.sh/).

Note that installing this way is only necessary if you want to fork or contribute to Mapbox GL. To integrate Mapbox GL into your application, follow the CocoaPods or binary [installation instructions](https://www.mapbox.com/mapbox-gl-ios/#installation).

**Comment by adozenlines** [comment]
The scripts seems to be trying to reach out to mason and fails...

**Comment by tmcw** [comment]
Closing: please reopen if you've installed boost and still encounter this issue.
