### ISSUE TITLE
Update Android Library Dependencies

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#1965]
The SDK and TestGLApp dependencies are out of date (Support Libs, OkHttp, etc).  Update to the latest.

**Comment by ljbade** [comment]
Worth mentioning every so soften a review of the native/mason Android dependencies is also a good idea. Particularly for stuff like OpenSSL (but hopefully we will be removing this one).

**Comment by bleege** [comment]
@ljbade Agreed.  That's mostly likely to be done at the Core GL level I believe.  In other words it's likely to come from general @mapbox/gl IIRC.

**Comment by ljbade** [comment]
@bleege yes but there are quite a few lines only used by Android but hopefully we can reduce that
