### ISSUE TITLE
Add getAnnotationsInBounds in NativeMapView.java

### ISSUE THREAD

**Issue by erf** [mapbox/mapbox-gl-native#1969]
I'm looking at implementing annotation selection in Android but i need the getAnnotationsInBounds method.

**Comment by ljbade** [comment]
@incanus How does this relate to your long press pin drop stuff?

**Comment by incanus** [comment]
Not related.

**Comment by incanus** [comment]
Eventually it will relate to selection of dropped pins, but that's cart before horse right now.

**Comment by ljbade** [comment]
@incanus some feedback on how to design this:

First you should implement https://github.com/mapbox/mapbox-gl-native/issues/1998
This will require you to keep a shadow of the Annotation objects in a local `LinkedList` as a private member of `MapView`. Basically each time you handle `add*` or `remove*` you update the Java list as well as call the JNI function.

Then the `getAnnotations` will simply return this as a `List`.

You can then change the JNI `nativeGetAnnotationsInBounds` to return a `long[]` of annotation IDs. In the Java implementation of `getAnnotationsInBounds` you then use this array of IDs to build an `ArrayList` of `Annotation

**Comment by incanus** [comment]
I think I follow, but does this account for needing to query an arbitrary bounding box? That's why I want to pass down to the C++ routine.

**Comment by ljbade** [comment]
@incanus Oh yes you still pass down to the C++ routine the bounding box. But you return the list of annotation ID numbers, which is then used to find the actual `Annotation` object created with that ID.

**Comment by incanus** [comment]
Ah I gotcha — yes, thanks for the help outlining the Java side of the API. Once I get there! :smile:

**Comment by ljbade** [comment]
@incanus After #2094 and #2088 all that's left now is this. I might be able to pick this up tomorrow.

**Comment by incanus** [comment]
:point_right: https://github.com/mapbox/mapbox-gl-native/pull/2201

**Comment by erf** [comment]
nice! :+1:

**Comment by bleege** [comment]
Fixed by #2201
