### ISSUE TITLE
restore Android logging backend in JNI

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1972]
@ljbade says this used to work, but I am not getting any logging to happen inside of `jni.cpp`, `mbgl::Log` or otherwise. 

Doing something like this fixed it locally: 

```c++
diff --git a/android/cpp/jni.cpp b/android/cpp/jni.cpp
index 85022db..d9a18bb 100644
--- a/android/cpp/jni.cpp
+++ b/android/cpp/jni.cpp
@@ -23,6 +23,14 @@
 #include <mbgl/platform/log.hpp>
 #include <mbgl/storage/network_status.hpp>
 
+#include <android/log.h>
+
+#define LOGV(...) __android_log_print(ANDROID_LOG_VERBOSE, "JNI_DEBUGGING", __VA_ARGS__)
+#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG,   "JNI_DEBUGGING", __VA_ARGS__)
+#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,    "JNI_DEBUGGING", __VA_ARGS__)
+#define LOGW(...) __android_log_print(ANDROID_LOG_WARN,    "JNI_DEBUGGING", __VA_ARGS__)
+#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,   "JNI_DEBUGGING", __VA_ARGS__)
+
 #pragma clang diagnostic ignored "-Wunused-parameter"
 
 namespace mbgl {
@@ -282,6 +290,9 @@ using namespace mbgl::android;
 
 jlong JNICALL nativeCreate(JNIEnv *env, jobject obj, jstring cachePath_, jstring dataPath_, jstring apkPath_, jfloat pixelRatio, jint availableProcessors, jlong totalMemory) {
     mbgl::Log::Debug(mbgl::Event::JNI, "nativeCreate");
+
+    LOGD("ratio: %f\n", pixelRatio);
+
     cachePath = std_string_from_jstring(env, cachePath_);
     dataPath = std_string_from_jstring(env, dataPath_);
     apkPath = std_string_from_jstring(env, apkPath_);
```

So it seems to me that use of `__android_log_print` is possibly required.

**Comment by incanus** [comment]
Discovered this approach via http://www.brokenteapotstudios.com/android-game-development-blog/2011/05/using-printfs-with-the-android-ndk-and-visual-studio.html.

**Comment by mb12** [comment]
@incanus mbgl::Log::Debug will not work in Release builds. You can convert this into mbgl::Log::Info etc.

**Comment by incanus** [comment]
I experimented with Release builds as well to no avail.

**Comment by mb12** [comment]
Are you trying to see printfs in jni code via adb logcat?  I had run into a similar issue. That's when I filed this https://github.com/mapbox/mapbox-gl-native/issues/1720  .

I replaced mbgl::Log::Debug in jni.cpp with the following to work around it.
mbgl::Log::Info(mbgl::Event::Android,

**Comment by ljbade** [comment]
This is working again.

**Comment by incanus** [comment]
BTW the key here, I later found, is to `V=1 make android` to turn this on. This wasn't clear, not being a regular Android developer at the time.
