### ISSUE TITLE
Updating "MGLPointAnnotation" coordinate does not change annotation placement on a map

### ISSUE THREAD

**Issue by xrayed** [mapbox/mapbox-gl-native#1980]
Mapbox GL 0.5.1

**Comment by 1ec5** [comment]
For now, the workaround is to remove the annotation and add it back at the new coordinates.

**Comment by bwhtmn** [comment]
It seems that the workaround would be affected by issue #1688.

**Comment by friedbunny** [comment]
We have core support for updating the position of point annotations in #3933, which was implemented in Android in #3943.

**Comment by 1ec5** [comment]
The fix for this issue is ready for review: #3835.
