### ISSUE TITLE
Remove {get,set}DefaultTransition{Duration,Delay}

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#1985]
These values should come from the style -- https://www.mapbox.com/mapbox-gl-style-spec/#transition.

Existing, class-mutation-related use of these properties should be eliminated as described in #1025.

Refs #302.

**Comment by ljbade** [comment]
Yeah seems weird to have a global parameter for this.

**Comment by brunoabinader** [comment]
I wonder if we might find scenarios where the user agent is willing to modify the default values for such values (i.e. old devices and/or devices without much processing power).

I might be wrong here, but I see this in the same level as the possibility to modify the default font type/size/color in web browsers. Would that make sense then, [to provide a way for user agents to provide their own style default values in a higher order level](https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade#Cascading_order)?

**Comment by jfirebaugh** [comment]
> I wonder if we might find scenarios 

YAGNI -- if this actually comes up in the future, we can think about it then.

**Comment by brunoabinader** [comment]
> if this actually comes up in the future, we can think about it then.

Fair enough :+1:
