### ISSUE TITLE
Use mapbox inside other linux-app

### ISSUE THREAD

**Issue by Vecherkin** [mapbox/mapbox-gl-native#1987]
Tried to use mapbox inside my own linux app, but when I try to connect compiled libraries, errors appear.

For example in libmgl-http-curl.a: undefined reference to HTTPContextBase::removeRequest.

Is there right way to use mapbox inside my own app?

**Comment by kkaefer** [comment]
How are you linking Mapbox GL? How did you compile it? Can you post your linker lines?

**Comment by Vecherkin** [comment]
1) I built mapbox with make -linux.
2) connect all libraries libmbgl-curl.a and others like in mapboxgl-app.gypi.
3) then connect all necessary libraries: libz, libpng, libcurl and others in my app.
4) then specify header search paths ( include/...)
5) tried to run app like in file linux/main.cpp

But i think that this is the wrong way.

**Comment by tmcw** [comment]
@Vecherkin - please post back with more details to get this issue debugged.

**Comment by Vecherkin** [comment]
@tmcw At the moment all works fine.
