### ISSUE TITLE
Android user agent string

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#1993]
From #823 current curl implementation just uses `MapboxGL/1.0`

At @kkaefer suggestion should:
- [ ] Indicate platform e.g. MapboxGL Android, Linux etc. using build macros?
- [ ] use actual version from `version.hpp`

**Comment by kkaefer** [comment]
Something like:

- `MapboxGL/0.5.4 (e6053aa5) [Android 4.4.4 (KTU84Q)] [HTC One (M8) (HTC6525LVW)]`
- `MapboxGL/0.5.4 (e6053aa5) [iOS 8.4 (12H143)] [Apple iPhone 6 (A1549)]`

**Comment by ljbade** [comment]
@incanus How does iOS currently format the user agent?

**Comment by ljbade** [comment]
@kkaefer What would be the best way to do this?

I am thinking some shared code in mbgl::util that returns a formatted string given platform specific stuff like OS version and phone make/model?

**Comment by ljbade** [comment]
Current effort in https://github.com/mapbox/mapbox-gl-native/tree/1993-useragent Basically extended `version.hpp` to create the first part of the user agent string. Still need to fill in the platform specific bit elsewhere.

@kkaefer When I try to build that branch it can't find `<mbgl/util/version.hpp>`, am I including it right?

**Comment by kkaefer** [comment]
`version.hpp` is automatically generated and should be in the include path.

**Comment by ljbade** [comment]
@kkaefer that's what I thought. I'll have to dig deeper and see why it isn't finding it.

**Comment by ljbade** [comment]
Should take a look at the iOS metrics user agent string.

**Comment by tobrun** [comment]
@bleege 
I believe this one can be closed with the work you have been doing on metrics.
Can you validate this?

**Comment by bleege** [comment]
@tobrun There are actually 2 different scenarios here.  The first one (which @ljbade @kkaefer discussed above) has to do with the User Agent for the HTTP client that loads Tiles, Sprites, etc for the SDK.  This is set in [`http_request_android.cpp`](https://github.com/mapbox/mapbox-gl-native/blob/c10f6489e61a52e3ae36af7cd2c40d120f9181da/platform/android/src/http_request_android.cpp#L138) and looks like it should be made more informative.  I think it could get by with `MapboxGL/x.y.z - Android` as the rest of the data is / will be recorded in the Telemetry API.  Please check with @willwhite though to see if / how they're using this data on the Web server though to confirm.

The second one has to do with the Telemetry HTTP client as it has [it's own User Agent](https://github.com/mapbox/mapbox-gl-native/blob/c10f6489e61a52e3ae36af7cd2c40d120f9181da/platform/ios/src/MGLMapboxEvents.m#L578).  This will be mirrored in Android when Telemetry is built there.

**Comment by bleege** [comment]
Noting that the UserAgent for Tiles / Resources is now set in [`http_file_source.cpp`](https://github.com/mapbox/mapbox-gl-native/blob/d14ca37570bfbb15cd184516da81fbe357dc6d6e/platform/android/src/http_file_source.cpp#L90) as the Android SDK is using OkHttp to handle HTTP networking and not the previous curl based common library in Core GL.

**Comment by jfirebaugh** [comment]
Done for telemetry in 8fad77faa4a49301cb80f25b3091ecd2ddd4aace. Still needs to be done for other requests. With some slight refactoring this can be done entirely in Java code. There's no reason it needs to be threaded through the `http_file_source.cpp` JNI code.

**Comment by bleege** [comment]
Looks like this one has slipped through the cracks.  Let's get it on to `4.2.0` as it's long over due.

/cc @zugaldia
