### ISSUE TITLE
MapView should perform click, longclick, drag events

### ISSUE THREAD

**Issue by erf** [mapbox/mapbox-gl-native#1996]
I would like to listen for mapView's events for click, longclick, drag events etc. 

For this to work now I had to call performClick and performLongClick in MapView's gesture listener.

**Comment by ljbade** [comment]
Yeah we need a decent set of event listeners. I have a ticket for this over in https://github.com/mapbox/mapbox-gl-native/issues/1942

So closing this one, but add your specific event requests in there.
