### ISSUE TITLE
Make MapView's setStyleJson public

### ISSUE THREAD

**Issue by erf** [mapbox/mapbox-gl-native#1997]
I would like to have setStyleJson as a public method in MapView, like so:

<pre>
    public void setStyleJson(String json){
        mNativeMapView.setStyleJson(json);
    }
</pre>

**Comment by 1ec5** [comment]
For reference, on the iOS side, we removed `-setStyleJSON:` in #1299 but are definitely open to reintroducing granular styling in some form (#837).

**Comment by ljbade** [comment]
I'd much rather see #837 as the public API instead of this as setting the JSON directly is messy and I recall it causing issues a while ago.

@jfirebaugh Should we expose this to developers?

**Comment by jfirebaugh** [comment]
Yep, #837 covers what our plans are for public APIs in this area. @erf, let us know if for some reason your use case wouldn't be satisfied with that approach.

**Comment by erf** [comment]
@jfirebaugh #837 looks promising - has work on this begun for Android ?

**Comment by jfirebaugh** [comment]
No, we haven't started on it for any native platform yet.
