### ISSUE TITLE
getAnnotations method in MapView

### ISSUE THREAD

**Issue by erf** [mapbox/mapbox-gl-native#1998]
I would like a getAnnotations as a public method in mapView to perform collision etc.

<pre>
    public List<Annotation> getAnnotations() {
        return annotations;
    }
</pre>

**Comment by ljbade** [comment]
Hopefully you won't need to do your own collision once @incanus lands https://github.com/mapbox/mapbox-gl-native/tree/android-bind-annotation-bounds

This will expose the native bounds API.

@incanus Does iOS have a similar get API?

**Comment by ljbade** [comment]
@erf Can you make a PR for this?

Will help @incanus with #1969

**Comment by erf** [comment]
Sure! See #2094
