### ISSUE TITLE
R.raw.token not found in android MapboxGLAndroidSDKTestApp

### ISSUE THREAD

**Issue by nikssss** [mapbox/mapbox-gl-native#2005]
In android application MapboxGLAndroidSDKTestApp  R.raw.token file not found.

**Comment by erf** [comment]
Please read 'README.md' for instructions on how to add a token.

**Comment by nikssss** [comment]
Hello ,

In Response to  R.raw.token not found in android MapboxGLAndroidSDKTestApp
(#2005)

i not find exact about R.raw.token specially for android , so , please you
provide me more information related to how to add  R.raw.token.

Thank you.

Nirav Mehta.
