### ISSUE TITLE
Mobile connection optimization: Keep-Alive

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#2007]
@1ec5 @incanus @brunoabinader 

Given a high-latency but mildly-fast-once-the-download-has-started 3G network, how can we reduce round-trip time?

I'm a noob here but my two guesses:

1. Remove tile URL sharding: https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/map/source.cpp#L101 - this is a web optimization that is a disadvantage rather than an advantage on mobile
2. Keep-Alive: are we using it? With Cloudfront we can't use HTTP2 or SPDY but this gets us some of the way, potentially cutting down on negotiation and re-negotiation of tile load requests.

Thoughts?

**Comment by friedbunny** [comment]
Here are iOS demo app headers captured using [Charles Proxy](http://www.charlesproxy.com). Looks like we're trying to use `keep-alive` on both ends.

**Request**

```http
GET /v4/mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6/2/0/2.vector.pbf?access_token=tokenWasHere&events=true HTTP/1.1
Host: a.tiles.mapbox.com
If-None-Match: "33b78a6ffc95d2bf588374d3343d5fcb"
Proxy-Connection: keep-alive
Accept: */*
User-Agent: MapboxGL
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive
```

**Response**

```http
HTTP/1.1 200 OK
Content-Type: application/x-protobuf
Content-Length: 13188
Connection: keep-alive
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: *
Cache-Control: max-age=43200,s-maxage=300
Content-Encoding: gzip
Date: Thu, 06 Aug 2015 17:28:33 GMT
ETag: "33b78a6ffc95d2bf588374d3343d5fcb"
Last-Modified: Tue, 26 May 2015 21:18:51 GMT
Server: nginx
Timing-Allow-Origin: *
X-Powered-By: Express
X-Cache: Miss from cloudfront
Via: 1.1 45578d14a69df96accaab0d1aba82a5a.cloudfront.net (CloudFront)
X-Amz-Cf-Id: AaxSZk9YKyduZDmN7bag3oMioow79nVfb2qCFPnHccdckjaBZBUtNA==
```

**Comment by kkaefer** [comment]
On iOS, we're using the system libraries for HTTP requests, which handle the connections internally. On Android, we're using OkHTTP; @ljbade can speak more on how it manages connections.

**Comment by ljbade** [comment]
Default Android OkHTTP settings mentioned in http://square.github.io/okhttp/javadoc/com/squareup/okhttp/ConnectionPool.html

- uses keep alive
- keeps up to 5 connections open in the pool
- closes connections after 5 minutes idle
- support s SPDY/HTTP 2.0

**Comment by 2beaucoup** [comment]
HTTP/1.1 connections are persistent by default. Therefore `Connection: keep-alive` doesn't beed to be set explicitly. See http://tools.ietf.org/html/rfc2616#section-8.1.2.

**Comment by tmcw** [comment]
:+1: thx for the context, looks like we're using keep-alive where appropriate already
