### ISSUE TITLE
Project failed to compile on OS X Yosemite using Xcode 6.4

### ISSUE THREAD

**Issue by mrfortynine** [mapbox/mapbox-gl-native#2016]
The clang compiler complain about "/Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.10.xctoolchain/usr/include/c++/v1/atomic:632:58: No viable conversion from 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000> >' to '_Atomic(std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000> >)'
" 

in MapData's constructor, as chrono::duration isn't trivially copyable.

**Comment by 1ec5** [comment]
I’m not seeing this error building for iOS 8.4 in Xcode 6.4 on Yosemite. Can you provide additional details about your setup?

* Which target are you building?
* Did you make any modifications to the workspace before building, such as integrating your own project or changing the C dialect or minimum deployment target in the build settings?
* Are you building for the device or a simulator? Which simulator?
* Are you building inside Xcode or on the command line via `make ipackage` / `xcodebuild`?
* Does this error persist after going to Product ‣ Clean Build Folder (hold down Option)?

**Comment by 1ec5** [comment]
Also, are you building a workspace that was generated via `make iproj` (for iOS) or `make xproj` (for OS X)?

**Comment by mrfortynine** [comment]
I used "make xproj", after which, I attempted to build target "All". The error is reported for "core".

The error persists after a clean.

Here's the complete error message:


CompileC /Users/jia/Library/Developer/Xcode/DerivedData/osx-aixmqurwktlssdeqkuhrkgwtknxf/Build/Intermediates/mbgl.build/Debug/core.build/Objects-normal/x86_64/map.o src/mbgl/map/map.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/jia/Documents/git-workspace/mapbox-gl-native
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.10.xctoolchain/usr/bin/clang -x c++ -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -stdlib=libc++ -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wconditional-uninitialized -Wno-unknown-pragmas -pedantic -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DDEBUG -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -mmacosx-version-min=10.9 -g -Wno-sign-conversion -I/Users/jia/Library/Developer/Xcode/DerivedData/osx-aixmqurwktlssdeqkuhrkgwtknxf/Build/Intermediates/mbgl.build/Debug/core.build/mbgl-core.hmap -I/Users/jia/Library/Developer/Xcode/DerivedData/osx-aixmqurwktlssdeqkuhrkgwtknxf/Build/Products/Debug/include -Iinclude -Isrc -I/Users/jia/Library/Developer/Xcode/DerivedData/osx-aixmqurwktlssdeqkuhrkgwtknxf/Build/Products/DerivedSources/Debug/include -I/Users/jia/Library/Developer/Xcode/DerivedData/osx-aixmqurwktlssdeqkuhrkgwtknxf/Build/Products/DerivedSources/Debug/include -I/Users/jia/Library/Developer/Xcode/DerivedData/osx-aixmqurwktlssdeqkuhrkgwtknxf/Build/Intermediates/mbgl.build/Debug/core.build/DerivedSources/x86_64 -I/Users/jia/Library/Developer/Xcode/DerivedData/osx-aixmqurwktlssdeqkuhrkgwtknxf/Build/Intermediates/mbgl.build/Debug/core.build/DerivedSources -F/Users/jia/Library/Developer/Xcode/DerivedData/osx-aixmqurwktlssdeqkuhrkgwtknxf/Build/Products/Debug -std=c++1y -Werror -Wall -Wextra -Wshadow -Wno-variadic-macros -frtti -fexceptions -I/Users/jia/Documents/git-workspace/mapbox-gl-native/mason_packages/osx-10.10/libuv/0.10.28/include -I/Users/jia/Documents/git-workspace/mapbox-gl-native/mason_packages/headers/boost/1.57.0/include -fPIC -fno-omit-frame-pointer -fwrapv -fstack-protector-all -fno-common -MMD -MT dependencies -MF /Users/jia/Library/Developer/Xcode/DerivedData/osx-aixmqurwktlssdeqkuhrkgwtknxf/Build/Intermediates/mbgl.build/Debug/core.build/Objects-normal/x86_64/map.d --serialize-diagnostics /Users/jia/Library/Developer/Xcode/DerivedData/osx-aixmqurwktlssdeqkuhrkgwtknxf/Build/Intermediates/mbgl.build/Debug/core.build/Objects-normal/x86_64/map.dia -c /Users/jia/Documents/git-workspace/mapbox-gl-native/src/mbgl/map/map.cpp -o /Users/jia/Library/Developer/Xcode/DerivedData/osx-aixmqurwktlssdeqkuhrkgwtknxf/Build/Intermediates/mbgl.build/Debug/core.build/Objects-normal/x86_64/map.o

In file included from /Users/jia/Documents/git-workspace/mapbox-gl-native/src/mbgl/map/map.cpp:1:
In file included from include/mbgl/map/map.hpp:9:
In file included from include/mbgl/util/vec.hpp:8:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.10.xctoolchain/usr/bin/../include/c++/v1/array:108:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.10.xctoolchain/usr/bin/../include/c++/v1/algorithm:627:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.10.xctoolchain/usr/bin/../include/c++/v1/memory:610:
/Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.10.xctoolchain/usr/bin/../include/c++/v1/atomic:632:58: error: no viable conversion from 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000> >' to '_Atomic(std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000> >)'
    _LIBCPP_CONSTEXPR __atomic_base(_Tp __d) _NOEXCEPT : __a_(__d) {}
                                                         ^    ~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.10.xctoolchain/usr/bin/../include/c++/v1/atomic:736:51: note: in instantiation of member function 'std::__1::__atomic_base<std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000> >, false>::__atomic_base' requested here
    _LIBCPP_CONSTEXPR atomic(_Tp __d) _NOEXCEPT : __base(__d) {}
                                                  ^
In file included from /Users/jia/Documents/git-workspace/mapbox-gl-native/src/mbgl/map/map.cpp:6:
src/mbgl/map/map_data.hpp:26:11: note: in instantiation of member function 'std::__1::atomic<std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000> > >::atomic' requested here
        , animationTime(Duration::zero())
          ^
1 error generated.

**Comment by 1ec5** [comment]
I’m seeing #2025 instead. In any case, I think it may be a regression from #1988, which started pulling in boost from mason instead of using the system’s copy.

**Comment by 1ec5** [comment]
The OS X have been completely rewritten in #3135. Please let us know if you’re still seeing this error. Thanks!
