### ISSUE TITLE
iOS sample application does not save map state.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#2017]
The iOS sample application does not save map state anymore.  It used to save the map state at one point and restore it correctly. Is it possible to add it back again? This would make issues a litter faster and easier to analyze on iOS.

**Comment by 1ec5** [comment]
It seems to only save map state when you quit the application using the app switcher (command-H twice), but not if you pan around and kill the debugging process.

**Comment by mb12** [comment]
Thanks a ton. This is exactly what I am looking for. I recently switched from debugging on device to emulator.  Again thank you very much.
