### ISSUE TITLE
Segmentation fault in mbgl::DefaultFileSource::setAccessToken

### ISSUE THREAD

**Issue by vecherkin** [mapbox/mapbox-gl-native#2021]
Hello!

I have class, for example:
```
class MapboxGL {
public:
 explicit MapboxGL();
 ~MapboxGL();
}
```

In constructor ```MapboxGL() ``` i tried to create an object and set access token:
```mbgl::DefaultFileSource *fileS = new mbgl::DefaultFIleSource(nullptr);```
 ```fileS->setAccessToken("my token");```

But after ```fileS->setAccessToken(..) ``` i have error:
```Segmentation fault in mbgl::DefaultFileSource::setAccessToken(..)```

call stack: function: ```std::string::assign(std::string const&)()```

What is the problem?

**Comment by ljbade** [comment]
@Vecherkin Can you post the full stack trace of the crash?

**Comment by Vecherkin** [comment]
Another feature - the error appears in the BUILDTYPE=Debug

**Comment by jfirebaugh** [comment]
Is this still an issue?
