### ISSUE TITLE
Using source code (GYP integration)

### ISSUE THREAD

**Issue by xrayed** [mapbox/mapbox-gl-native#2022]
I have tried to use Mapbox GL source, so I followed steps and used GYP,
but here are some problems when I ran following:

gyp ios/app/mapboxgl-app.gypi --depth=. -f xcode --generator-output=./build.xcodefiles/

1) gyp: name 'host' is not defined while evaluating condition 'host == "ios"' in ios/app/mapboxgl-app.gypi
 - it seems that this is an naming error, this file might have 'OS == "ios" instead of 'host == "ios"

2) When I tried with ['OS == "ios"] another error appeared:
gyp: Undefined variable platform_lib in ios/app/mapboxgl-app.gypi

I'm new to GYP, maybe I did something wrong

**Comment by 1ec5** [comment]
You shouldn't need to use gyp directly for developing Mapbox GL. To create the iOS Xcode workspace, run `make iproj`. See the readme for more details.
