### ISSUE TITLE
xproj fails to build — GLFW/glfw3.h not found

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#2025]
1. Clean and distclean everything.
1. `make xproj`
1. Build the osxapp target.

```
In file included from /Users/mxn/hub/mapbox-gl-native/macosx/main.mm:6:
../include/mbgl/platform/default/glfw_view.hpp:9:10: fatal error: 'GLFW/glfw3.h' file not found
#include <GLFW/glfw3.h>
```

I also see lots of warnings in mbgl-render of the form:

```
ld: warning: direct access in void boost::throw_exception<boost::bad_lexical_cast>(boost::bad_lexical_cast const&) to global weak symbol typeinfo for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_lexical_cast> > means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

Xcode 6.4 on OS X 10.10.4. Possibly related to #2016.

/cc @kkaefer @incanus

**Comment by 1ec5** [comment]
Possibly a regression from #1988.

**Comment by incanus** [comment]
Doing a `make distclean`, then `make xproj` here builds fine for me in Xcode 6.4.

**Comment by incanus** [comment]
Also no sign of the boost logs either with running the gamut of interactive tests on OS X.

**Comment by 1ec5** [comment]
After `distclean`, I encounter the errors in master but not release-0.5.0. I’m bisecting right now, but it’ll take awhile.

**Comment by 1ec5** [comment]
I must’ve had some cruft lying around. After a bunch of bisecting, I no longer get the GLFW compiler error, although the Boost linker warnings remain.
