### ISSUE TITLE
Move Android C++ files

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2032]
Currently Android doesn't follow the other platforms as far as location of the C++ files.

Proposal:
- move `android/cpp` to `platform/android`
- move `android/java` to `android`

/cc @bleege @jfirebaugh

**Comment by kkaefer** [comment]
Yeah, let's do this!

**Comment by ljbade** [comment]
Lets get this tidied up before our first release.

Shouldn't take much effort.
