### ISSUE TITLE
Why use clang++ for compiling native code for android? (Question)

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#2035]
Why does mapbox-gl-native use clang++ to compile native code for Android? The default compiler in Android NDK is g++. All the SDK samples pick g++ by default.

**Comment by ljbade** [comment]
clang is a better compiler than GCC. Faster, more useful error messages, and it is what we use for our other platforms.

The NDK supports both GCC and clang and projects can choose either.

**Comment by kkaefer** [comment]
@mb12 are you seeing any issues with using clang rather than GCC?

**Comment by mb12** [comment]
No, I am not seeing clang specific issues. I just wanted to know the reason for choosing  clang++ over the default compiler.
