### ISSUE TITLE
Next native -> Java targets

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2037]
Other pieces of native code to eventually replace with Java:
- PNG/JPEG image decoding
- Unicode string upper/lower case
- SQLITE caching
- Asset fetching

**Comment by ljbade** [comment]
@kkaefer mentions that PNG/JPEG and Unicode are the easiest

I think I will tackle Unicode first since this is very minimal

**Comment by ljbade** [comment]
Need to split into individual tickets.

**Comment by bleege** [comment]
> Need to split into individual tickets.

Cool.  Please do, link 'em back to this one, and then close.  :+1:

**Comment by ljbade** [comment]
Issues created ^

**Comment by bleege** [comment]
@ljbade :+1:
