### ISSUE TITLE
getMapAsync for Android like in Google maps

### ISSUE THREAD

**Issue by erf** [mapbox/mapbox-gl-native#2042]
Would it be an idea to load the mapview async as in google maps:
<pre>
   mapFragment = new SupportMapFragment();
        mapFragment.getMapAsync(this);

   FragmentManager fragmentManager = getSupportFragmentManager();
   FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();
   fragmentTransaction.replace(R.id.container, mapFragment);
   fragmentTransaction.commit();
</pre>
In this way you could make the mapFragment static so you don't have to reinstanciate it each time you create the activity containing the map.

I have made an implementation of this.

**Comment by erf** [comment]
I created a pull request for this:
https://github.com/mapbox/mapbox-gl-native/pull/2043

**Comment by erf** [comment]
The problem i described in #2018 is back after i load the mapview this way

**Comment by ljbade** [comment]
I don't really understand what this does.

It seems you are only changing the way the test app works?

/cc @bleege

**Comment by erf** [comment]
You probably would like to have MapView in a Fragment to reuse map functionality (like google do) and to add it programmatically you need to retrieve the MapView async from the MapFragment when it's added to the view or else it's null if you try to retrieve it just after you've created the MapFragment. 

But.. This causes another problem, i describe in #2018 that when i tried to switch from the MapActivity to some other Activity (after moved the maped) and back the app crashes..

**Comment by tobrun** [comment]
@ljbade 

I would like to elaborate why Google exposes this async get method:

![image](https://cloud.githubusercontent.com/assets/2151639/10336371/9fdad0e0-6cf8-11e5-985b-7016b99fb8a1.png)

This would not work because the MapFragment is not created yet, for this reason that method exists.

cc @bleege

**Comment by tobrun** [comment]
Also here is an example how getMap can work, I used to implement GoogleMaps in this fashion before the async method was introduced and getMap was deprecated:

![image](https://cloud.githubusercontent.com/assets/2151639/10336459/3da85acc-6cf9-11e5-9bcc-441ec2f143fc.png)

**Comment by ljbade** [comment]
@tobrun Interesting! Perhaps we should put this on 2.2.0 milestone as part of the refactor.

**Comment by tobrun** [comment]
This will be implemented with #3145

**Comment by tobrun** [comment]
This has landed with #3145. Closing
