### ISSUE TITLE
Add -[MGLMapView showAnnotations:animated:]

### ISSUE THREAD

**Issue by jncn** [mapbox/mapbox-gl-native#2044]
MapKit has a method since iOS 7 which sets the visible region so that the map displays all specified annotations. It would be nice if `MGLMapView` has a method like this:
```
- (void)showAnnotations:(NSArray<id<MGLAnnotation>> * _Nonnull)annotations animated:(BOOL)animated
```

**Comment by incanus** [comment]
I _swear_ we had a ticket on this already, but I can't find it. Maybe not. 

We have `-setVisibleCoordinateBounds:edgePadding:animated:` and friends now, so this would just be a layering on that. Should be a simple patch.
