### ISSUE TITLE
update iOS accuracy circle during zooms

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2045]
@friedbunny great user annotation work in https://github.com/mapbox/mapbox-gl-native/pull/2010 brought us an accuracy circle (among other things). But its size should change smoothly with map zoom instead of animated immediately after the zoom finishes. 

![anigif-1439404266](https://cloud.githubusercontent.com/assets/17722/9233036/b4df7f52-40e5-11e5-9198-7f252920a5bd.gif)

Should be able to hit this pretty easily inside of `-[MGLMapView updateUserLocationAnnotationView]`.

**Comment by incanus** [comment]
Possibly helpful: `MGLCircle` by way of https://github.com/mapbox/mapbox-gl-native/issues/2167, which would mean moving at least the non-pulsing (accuracy) circle) to GL-side. Maybe we don't want to do that, but it's an option.

**Comment by 1ec5** [comment]
> change smoothly with map zoom instead of animated immediately after the zoom finishes

Actually, `-[MGLMapView updateUserLocationAnnotationView]` does cause the accuracy ring to resize in tandem with the map animation. The change lags behind the map animation because Core Animation applies an implicit animation to any property changes on the user dot’s layers.

**Comment by 1ec5** [comment]
See #3683 for an example of disabling the implicit animation.

**Comment by friedbunny** [comment]
We’re good here after #6215.
