### ISSUE TITLE
Custom path rendering/shadows

### ISSUE THREAD

**Issue by pkmital** [mapbox/mapbox-gl-native#2048]
I'm loving Mapbox-GL, but really need to be able to customize the paths drawn.  In MapKit, you can provide a custom renderer [1] which can handle shadows, and other intricacies, given a list of points.  It'd be great to have this same functionality, or even taking it to the next step and having a way to draw custom GL code for a set of points defined by CLLocationCoordinate2Ds to the screen.  

[1]. https://developer.apple.com/library/mac/documentation/MapKit/Reference/MKPolylineRenderer_class/index.html#//apple_ref/occ/cl/MKPolylineRenderer

**Comment by incanus** [comment]
Like most things of this ilk, the tradeoff is a bit of complexity, but mostly the potential for negative performance impact. I could see us calling out to per-platform callbacks for a given fill or path's rectangle on a per-tile basis, which mirrors/fits with `-[UIView drawRect:]` behavior.
