### ISSUE TITLE
OSX build error does not fail Travis

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2059]
From https://github.com/mapbox/mapbox-gl-native/pull/2034#issuecomment-130493229

For some reason a compile error in the OSX job does not fail the job on Travis.

**Comment by ljbade** [comment]
Looks like the script is correct https://github.com/mapbox/mapbox-gl-native/blob/master/scripts/osx/run.sh#L3-L4

Yet the script returns 0 at https://travis-ci.org/mapbox/mapbox-gl-native/jobs/75360573#L458

Is `make xosx` somehow not returning an error code on fail?

/cc @jfirebaugh

**Comment by jfirebaugh** [comment]
The error isn't from run.sh, it's [this bit](https://travis-ci.org/mapbox/mapbox-gl-native/jobs/75360573#L360):

```
▸ Compiling settings_nsuserdefaults.mm
⌦  /Users/travis/build/mapbox/mapbox-gl-native/platform/darwin/settings_nsuserdefaults.mm:35:28: use of old-style cast [-Werror,-Wold-style-cast]
        userTrackingMode = (MGLUserTrackingMode)uncheckedTrackingMode;
                           ^                    ~~~~~~~~~~~~~~~~~~~~~
** BUILD FAILED **
The following build commands failed:
	CompileC build/osx.build/Debug/osxapp.build/Objects-normal/x86_64/settings_nsuserdefaults.o /Users/travis/build/mapbox/mapbox-gl-native/platform/darwin/settings_nsuserdefaults.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

That's part of `make Xcode/osxapp`, which is implemented [here](https://github.com/mapbox/mapbox-gl-native/blob/5165757c2e05a3bf3e84e67948ff6d86ef25f55e/scripts/main.mk#L101-109).

I'm seeing indications on StackOverflow that `xcodebuild` always returns 0 rather than a proper exit code,  so that's likely the issue. We should switch to [xctool](https://github.com/facebook/xctool) everywhere. It's actually the Travis default, and seems to be better.

**Comment by ljbade** [comment]
@jfirebaugh Created branch in https://github.com/mapbox/mapbox-gl-native/commit/7114538f41adb9d177b86ba61a1336c2b985a3e0 with `xctool` in `scripts/make.mk` will see if it runs on Travis then I'll try it with a broken commit to see if it fails.

A quick `grep` also finds `xcodebuild` in `scripts/ios/package.sh`, and in the KIF and OHHTTPStubs projects. I assume we only need to mess with `package.sh`?

**Comment by ljbade** [comment]
@jfirebaugh The parallel testing feature the `xctool` page mentions might be useful for Travis run times?

**Comment by ljbade** [comment]
Also I guess we will need to get everyone to install `brew install xctool` and update the README.md to reflect this.

**Comment by ljbade** [comment]
Blindly replacing `xcodebuild` with `xctool` results in an error: `ERROR: Unexpected action: -target`
https://travis-ci.org/mapbox/mapbox-gl-native/jobs/75392568#L199

**Comment by ljbade** [comment]
"NOTE: xctool doesn't support directly building targets using -target; you must use schemes."

**Comment by ljbade** [comment]
Looks like `gyp` does not support schemes from this 2 year old feature request: https://code.google.com/p/gyp/issues/detail?id=333
Even the patch to add it has not been accepted https://codereview.chromium.org/385963006/

**Comment by ljbade** [comment]
I am not familiar with Xcode, I have seen people talk about creating a workspace by hand then using this with gyp's project output?

@1ec5 Perhaps you have more insight into how to get correct error return codes from `xcodebuild` or how to create these "schemes"?

**Comment by ljbade** [comment]
@jfirebaugh A workaround may be to wrap `xcodebuild` in some sort of `grep` that looks for failed builds then returns correct error code?

**Comment by ljbade** [comment]
@jfirebaugh Aha! I did some testing on my Mac mini and it turns out `xcodebuild` does return the error code 65 on a compile error which `make` picks up and also returns an error code of 1.

I eventually discovered installing `xcpretty` like on Travis (see https://github.com/mapbox/mapbox-gl-native/blob/master/scripts/osx/install.sh#L10) triggers this https://github.com/mapbox/mapbox-gl-native/blob/master/scripts/main.mk#L109 and https://github.com/mapbox/mapbox-gl-native/blob/master/scripts/xcpretty.sh

It turns out `xcpretty` ignores the error code from `xcodebuild` hence our issues.

Removing `xcpretty` from Travis should fix this.

**Comment by ljbade** [comment]
Second aha! From https://github.com/supermarin/xcpretty

"Important: If you're running xcpretty on a CI like Travis or Jenkins, you may want to exit with same status code as xcodebuild. CI systems usually use status codes to determine if the build has failed."

**Comment by ljbade** [comment]
Quick chat with @kkaefer suggested adding 
`set -o pipefile && ` before `xcodebuild`

It works locally. Making a branch to test it on Travis.
