### ISSUE TITLE
Add Mapbox logo and attribution button to Android

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2074]
After the compass and location marker the only missing UI elements vs iOS is the Mapbox logo and attribution button.

**Comment by ljbade** [comment]
@bleege Perhaps you can do this once you get location marker refactor finished?

**Comment by tobrunvannuland** [comment]
If you can provide a screenshot of the iOS version + MapBox logo. I will take this up.

**Comment by friedbunny** [comment]
The Mapbox logo that's bundled with iOS lives here: [/platform/ios/resources](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/ios/resources)

![ios simulator screen shot aug 20 2015 11 37 18 am](https://cloud.githubusercontent.com/assets/1198851/9387743/01689fa2-4730-11e5-854a-dfaf2d6582fa.png)

The logo stays pinned to the bottom-left and the attribution control is at the bottom-right. Both must be movable/hide-able.

**Comment by tobrunvannuland** [comment]
Logo is added but the sample app is currently using the bottom-right to display a fab for user location.

![device-2015-08-21-091136](https://cloud.githubusercontent.com/assets/2151639/9403183/f42b4000-47e4-11e5-8a61-693314aa677e.png)

Are the actions behind the attribution control the same as the ones found in the navigation drawer?

![device-2015-08-21-091504](https://cloud.githubusercontent.com/assets/2151639/9403207/2b46ea6c-47e5-11e5-8582-5aa3c7bd9e89.png)

**Comment by friedbunny** [comment]
> http://sharkfood.com/content/Developers/content/Sound%20Switch/

No, that appears to correspond to the gears debug menu on iOS.

I'm not sure which direction @ljbade and @bleege want to take the attribution control on Android, but [here are the strings](https://github.com/mapbox/mapbox-gl-native/blob/6d1c10dc1884712a66e7231cc18ecf1e21414b77/platform/ios/MGLMapView.mm#L1359-L1390) and [here are the links/actions](https://github.com/mapbox/mapbox-gl-native/blob/6d1c10dc1884712a66e7231cc18ecf1e21414b77/platform/ios/MGLMapView.mm#L1359-L1390) on iOS. This contains:

- Copyright notice for Mapbox linked to https://www.mapbox.com/about/maps/
- Copyright notice for OpenStreetMap linked to http://www.openstreetmap.org/about/
- Link to "Improve this map" linked to https://www.mapbox.com/map-feedback/#/%.5f/%.5f/%i
 - Replace with current longitude/latitude/zoom
- Metrics opt-out switch or kick-out to setting

**Comment by ljbade** [comment]
I think the attribution control should be fairly easy to implement with some sort of popup dialog.

Only thing not settled yet is metrics stuff.

@tobrunvannuland - yeah every app might have different UI overlaid on the map. At a minimum we should allow configuring of which corner the logo is in, and possibly provide fine tuning of the margin.

**Comment by friedbunny** [comment]
Oh, I should say: we've made the logo and attribution controls mildly configurable on iOS and they are hide-able/movable. See #1781.

**Comment by tobrunvannuland** [comment]
I will implement a solution based on CompassView implementation:
 - expose method
 - expose attribute

Will use following method signatures:

LogoView:
 - setLogoVisible(boolean visible)
 - setLogoGravity(int gravity)
 - setLogoMargins(int left, int top, int right, int bottom)

AttributionControlView:
 - setAttributionControlVisible(boolean visible)
 - setAttributionControlGravitiy(int gravity)
 - setAttributionControlMargins(int left, int top, int right, int botton)

@ljbade 
 - Shall I expose gravity + margins for CompassView as well?
 - Related to pop-up: there are 3 possible solutions
  * **AlertDialog** is not ideal due to problems found by [Square](https://corner.squareup.com/2015/08/a-small-leak.html), proposed only works for Android 4.3+. The basic idea can be ported to MapView activity lifecycle methods. 
  * **DialogFragment**, not possible, don't make library depend on FragmentActivity/FragmentManager.
  *  **PopUpWindow**, create custom dialog implementation

**Comment by bleege** [comment]
@tobrunvannuland This all looks great!  Just a few pieces of feedback:

Logo and Attribution should always appear on the MapView, so there's no need to implement `setXYZ
![screen shot 2015-08-31 at 2 15 42 pm](https://cloud.githubusercontent.com/assets/989928/9588008/4d995fba-4feb-11e5-9517-d5830d5ddf3d.png)
Visible()` methods for either of them.  The other two methods for each look :+1: .

Here's what and how iOS provides for Attribution links.  The top 3 all open Web pages in the native Web browser which is the same functionality that we can use in Android.  No need to implement `Adjust Privacy Setting` yet, as the SDK does not have Metrics in it like iOS does (see #1033) so there's nothing to adjust yet.  :-)  It will in the future though as will the need to build the `Adjust Privacy Setting` option.

As for the UI pattern to display / hold this, please feel free to use what you think works best.

![screen shot 2015-08-31 at 2 15 42 pm](https://cloud.githubusercontent.com/assets/989928/9588117/0acf2588-4fec-11e5-90cb-3349c8684fcd.png)

**Comment by tobrunvannuland** [comment]
@bleege 
Currently for opening webpages I'm using the standard ACTION_VIEW intent. (shown left in GIF)
With minor adjustments we can use [Chrome custom tabs](https://developer.chrome.com/multidevice/android/customtabs). 



![webpage](https://cloud.githubusercontent.com/assets/2151639/9605461/1fcd70de-50be-11e5-9ccd-24bd15c84d33.gif)

Let me know what you prefer.

**Comment by ljbade** [comment]
@tobrunvannuland Hmm I think a WebView would interfere less with the hosting Activity/app of the MapView? We need to be careful we don't break any UI flow of the hosting app.

**Comment by bleege** [comment]
@tobrunvannuland I'm intrigued by the Chrome custom tabs, but I think @ljbade is correct about firing an Intent to kick the germane Web site out to a WebVeiw interfering less with an app's UX.  Since we're building an SDK, we can't assume any access to non MapView UI components.

**Comment by ljbade** [comment]
@bleege True, I mean what happens if a user does not have a web browser or Chrome installed on their phone?

We should remember we want our Android SDK to work on all variations of Android if possible, not just Google blessed ones.

It is entirely possible Chineese Android based phones come with a completely different browser.

**Comment by ljbade** [comment]
@bleege @incanus Do we need to include an option in the attribution screen that links or displays some of the licence notices as required by a number of the open source components used.

See https://github.com/mapbox/mapbox-gl-native/blob/8f37502c719feb151e01cb31d89c2effaf1b91ad/LICENSE.md

**Comment by bleege** [comment]
@ljbade I didn't see examples of license's requiring display inside of apps in the list.  Did I miss something?  If not, I think just having them in the LICENSE.md file as we do should be fine.

**Comment by incanus** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/2292.
