### ISSUE TITLE
Implement setVisibleCoordinateBounds, setVisibleCoordinates, showAnnotations

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2075]
These iOS methods are missing equivalents in Android:
- `setVisibleCoordinateBounds`
- `setVisibleCoordinates`
- `showAnnotations`

**Comment by tobrun** [comment]
setVisibleCoorindateBounds landed with #2613

@1ec5 @friedbunny 
What do these other methods do:
- setVisibleCoordinates?
  - calculate a coordinate bounds based on LatLngs and call setVisibleCoorindateBounds?
  - or what is the difference with setVisibleCoorindateBounds?
- showAnnotations?

cc @bleege @zugaldia

**Comment by 1ec5** [comment]
-setVisibleCoordinateBounds:edgePadding:animated: fits to a rectangular bounds. -setVisibleCoordinates:edgePadding:animated: fits the map to an arbitrary set of coordinates. -showAnnotations: fits to the given annotation objects.

**Comment by 1ec5** [comment]
-showAnnotations: was implemented for MapKit compatibility; that terminology may not make sense on Android.

**Comment by tobrun** [comment]
We have parity with Google maps and remaining actionable things are tracked in a more detailed issue eg. #3602.
