### ISSUE TITLE
Implement convertPoint, convertCoordinate and metersPerPixelAtLatitude on Android

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2076]
These iOS methods are missing equivalents in Android:
- `convertPoint`
- `convertCoordinate`
- `metersPerPixelAtLatitude`

**Comment by 1ec5** [comment]
In Objective-C, parameters are spliced in between parts of a method name, so you're actually looking at `-convertPoint:toCoordinateFromView:` and `-convertCoordinate:toPointToView:`.

**Comment by ljbade** [comment]
Oh wow. that's an interesting syntax.

**Comment by incanus** [comment]
We have some of this already in the form of [these methods](https://github.com/mapbox/mapbox-gl-native/blob/0f80fb9103a3e014f82c7d4990b401706a0430fd/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java#L816-L823).

**Comment by ljbade** [comment]
@incanus Ah so its only `metersPerPixelAtLatitude` that's missing?

**Comment by ljbade** [comment]
This was done in #2076
