### ISSUE TITLE
Implement emptyMemoryCache on Android

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2078]
Android is missing `emptyMemoryCache`

**Comment by tobrun** [comment]
@bleege 
do you have more information on this ticket? 
is this still relevant?

**Comment by bleege** [comment]
@tobrun Looks like it's an [iOS wrapper method for calling `onLowMemory()`](https://github.com/mapbox/mapbox-gl-native/blob/45a0f48ea023a73d8652c6c2af94f7048a02157c/platform/ios/src/MGLMapView.mm#L1577-L1580).  I'm not sure how it's used in iOS however.  @1ec5 @friedbunny would have details on that.

**Comment by 1ec5** [comment]
We intend to take this API private in #1833. It was never supposed to be public, but iosapp and the iOS benchmarking application do make use of it.

**Comment by bleege** [comment]
Thanks @1ec5!  Let's leave it not implemented in Android for now then.
