### ISSUE TITLE
Replace user dot with puck when course tracking is enabled

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#2083]
Turn-by-turn applications conventionally display a “puck” at the user location, pointed in the direction of travel, instead of a user dot pointed in the direction that the device is facing. `MGLUserLocationAnnotationView` should draw a similar puck instead of the pulsing user dot.

In Apple Maps, the puck looks like a flat, white circle containing a blue or gray arrow that looks similar to the user tracking icon we’re already using in iosapp. (It looks like a pog.)

ref #2068

/cc @friedbunny @incanus

**Comment by incanus** [comment]
I think we should hold on this until we figure out how the turn-by-turn UI fits into this toolkit, if at all.

**Comment by 1ec5** [comment]
This was fixed in #2300.
