### ISSUE TITLE
Course tracking on Android

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#2084]
As a followup to #2004 and #2068, the Android bindings should have a tracking mode that reports the direction the device is traveling, rather than the direction the device is facing. (Imagine you’re on a train, sitting unfortunately in a seat that’s facing backwards. Or imagine that your phone is mounted on the dash, facing diagonally towards the driver’s seat.)

/cc @ljbade @bleege @incanus

**Comment by bleege** [comment]
See #2049

**Comment by bleege** [comment]
I misunderstood this originally.  Android should have this.

**Comment by ljbade** [comment]
@1ec5 in my old location marker (pre move to SDK) code I had a heuristic where if you are stationary then you use compass heading, but if you had GPS motion then it would use GPS heading.

I have suggested to LOST in https://github.com/mapzen/LOST/issues/30 that this would be a great feature for the location platform.

Perhaps we can make this configurable.

**Comment by ljbade** [comment]
Should point out that Google Maps is guilty of the sideways travelling arrow. They always use the compass.

**Comment by tobrun** [comment]
This is implemented as [GPS mode](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MyBearingTracking.java#L39)
