### ISSUE TITLE
Qt-Android-App crashes when include libmapbox-gl.so

### ISSUE THREAD

**Issue by Vecherkin** [mapbox/mapbox-gl-native#2085]
When tried to connect libmapbox-gl.so to my Qt-Android project:
```contains(ANDROID_TARGET_ARCH,armeabi-v7a) {
    ANDROID_EXTRA_LIBS = \
        $$PWD/../Desktop/mapbox-gl-native/build/android-arm-v7/Release/lib.target/libmapbox-gl.so
} ```
app crashes on device, but i can build it.

What can be wrong?

**Comment by ljbade** [comment]
We  don't use Qt-Android?

**Comment by Vecherkin** [comment]
I tried to use qmapboxgl (https://github.com/tmpsantos/qmapboxgl) and build this project using libmapbox-gl.so instead libmbgl-dev.

Is it possible?

**Comment by tmpsantos** [comment]
> Is it possible?

Maybe yes. :) But I will close this ticket here because is unsupported, so we move the discussion to qmapboxgl.
