### ISSUE TITLE
Xcode 7 beta 5 grabs 100% CPU on iOS 9 simulator when calling setVisibleCoordinateBounds

### ISSUE THREAD

**Issue by LucasVanDongen** [mapbox/mapbox-gl-native#2086]
I have the following block of code:

    func mapView(mapView: MGLMapView, didUpdateUserLocation userLocation: MGLUserLocation?) {
        guard let userLocation = userLocation else { return }
        let region = MKCoordinateRegionMakeWithDistance(userLocation.coordinate, 2000, 2000)
        let (sw, ne) = region.ne_sw_extremes()
        let coordinateBounds = MGLCoordinateBounds(sw: sw, ne: ne)
        mapView.setVisibleCoordinateBounds(coordinateBounds, animated: false)
    }

When I start my app and run it on the iOS 9 simulator at a certain point animations don't happen anymore and the UI is not responsive anymore. The CPU is always close to 100%, basically the main thread is blocked. If I pause it shows me a stack trace that has it's origin in setVisibleCoordinateBounds.

If I comment it out everything else works perfect. When I run exactly the same code on my iOS 8.4 device it works perfect (including the mapView.setVisibleCoordinateBounds call). I do not have an iOS 9 device to test.

Here's the stack: (it seems to be in the same place every time I pause)

![screen shot 2015-08-14 at 19 49 43](https://cloud.githubusercontent.com/assets/5376434/9285618/2236b6cc-42be-11e5-8488-577d797ab8b4.png)

**Comment by 1ec5** [comment]
Can you include the code for `ne_sw_extremes()`? Are you sure it returns a tuple of (sw, ne) rather than (ne, sw)?

**Comment by LucasVanDongen** [comment]
Sure:

    func ne_sw_extremes() -> (CLLocationCoordinate2D, CLLocationCoordinate2D) {
        return (
            CLLocationCoordinate2D(latitude: center.latitude + span.latitudeDelta, longitude: center.longitude + span.longitudeDelta),
            CLLocationCoordinate2D(latitude: center.latitude - span.latitudeDelta, longitude: center.longitude - span.longitudeDelta)
        )
    }

This is what the debugger says:

    (lldb) po (sw, ne)
    ▿ 2 elements
      ▿ .0 : 3.40282346638529e+38;3.40282346638529e+38
        - latitude : 3.40282346638529e+38
        - longitude : 3.40282346638529e+38
      ▿ .1 : 3.40282346638529e+38;3.40282346638529e+38
        - latitude : 3.40282346638529e+38
        - longitude : 3.40282346638529e+38

**Comment by 1ec5** [comment]
3.40282346638529e+38 is `FLT_MAX`. Starting in iOS 9, you’ll need to check `CLLocationCoordinate2DIsValid()` before using the coordinates. (This affected the Mapbox GL itself at one point: #1925.)

Also, `ne_sw_extremes()` appears to return a tuple of (ne, sw), not (sw, ne) as your implementation of `mapView(_:didUpdateUserLocation:)` expects.

**Comment by LucasVanDongen** [comment]
Hi, thanks for your super quick responses, you helped me a lot. I tested some more this morning and it appears that the userLocation.coordinate value already has the FLT_MAX values instead of the regular values I see in iOS 8. I do emulate a location (Apple campus) with the simulator.

I added the following line of code:

        guard CLLocationCoordinate2DIsValid(userLocation.coordinate) else {
            return
        }

Now it never updates my location anymore but it doesn't hang the app at least. Do you have any idea why it gives these potentially dangerous values instead of regular coordinates?

**Comment by 1ec5** [comment]
Typically you get invalid coordinates if the application doesn’t have permission to access the user’s location. Are you seeing #1930 by any chance? Also, did you set the `NSLocationAlwaysUsageDescription` and/or `NSLocationWhenInUseUsageDescription` Info.plist keys? (Mapbox GL only checks for one of them currently; see #1909).
