### ISSUE TITLE
Prevent crash if accessToken is not provided (Android)

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#2087]
I run into this almost every time I check out a new repo. Is it possible to give a warning message via Toast etc. for invalid access tokens.

**Comment by ljbade** [comment]
We crash with a message pointing to the README because you can't use the map at all without an access token.

**Comment by dariav** [comment]
In case I want to use external map styles (so no usage of Mapbox resources at all) how can I use mapbox-gl-native without AccessToken ?
I saw on iOS there was this fix https://github.com/mapbox/mapbox-gl-native/pull/1211 which allowed `nil` for accesstoken.

Is there anything similar on Android?
If not, would it make sense to create something like this (I can do a PR just want to know if that would be within Mapbox ToS)?
