### ISSUE TITLE
Markers don't show up intil map is zoomed or op is delayed

### ISSUE THREAD

**Issue by erf** [mapbox/mapbox-gl-native#2095]
There's a problem in Android where Markers don't show up until i zoom the map. It does work if i add markers with a timer Handler with 1 sec delay to it.

**Comment by ljbade** [comment]
Hmm sounds like the map isn't redrawing?

Do you have an example of how you are adding the markers?

**Comment by erf** [comment]
I execute an AsyncTask in onResume which gets markers data an then i add them in onPostExecute and the markers will not show up.If i add them inside a:
<pre>
            new Handler().postDelayed(
                    new Runnable() {
                        public void run() {
                        }
                    }, 1000);
</pre>
block, then they will show up. Also if i zoom down one level.

**Comment by erf** [comment]
*Get's markers data from a http rest service

**Comment by erf** [comment]
https://github.com/erf/mapbox-gl-native/tree/annotation-not-showing

**Comment by incanus** [comment]
@erf Is this the same as https://github.com/mapbox/mapbox-gl-native/issues/1675?

**Comment by erf** [comment]
Yes i would guess so. Close this?
