### ISSUE TITLE
iOS LocationManagerDelegate uses deprecated delegate-method

### ISSUE THREAD

**Issue by christocracy** [mapbox/mapbox-gl-native#2097]
`locationManager:didUpdateToLocation:fromLocation` was [deprecated @ ios 6.0](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManagerDelegate_Protocol/#//apple_ref/occ/intfm/CLLocationManagerDelegate/locationManager:didUpdateToLocation:fromLocation:)

`locationManager:didUpdateLocations:` should be used instead.

@see https://github.com/mapbox/mapbox-gl-native/commit/b7b4515d4883f7da1fdcfb4d5aff7a2f3118ae86#diff-f315cd6ead3270a0818a2dcfb84bd99bR2014

**Comment by incanus** [comment]
`locationManager:didUpdateLocations:` was introduced in iOS 6. I think the reasoning here was how we ported this from our old raster SDK, which supports back to iOS 5. 

:+1:
