### ISSUE TITLE
Point annotations missing until map is zoomed

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#2099]
I am creating a new map. Adding 1 line annotation and 2 point annotations. The line annotation shows up immediately, but the point animations do not show up until the map is zoomed.

Video:
http://tinypic.com/r/2u4235k/8

**Comment by tmpsantos** [comment]
Duplicated #1675.

**Comment by tmpsantos** [comment]
@picciano you can probably mitigate the problem by now if you use `loadStyleJSON()` instead if `setStyleURL`.

**Comment by picciano** [comment]
loadStyleJSON is not exposed in MGLMapView. I'm using initWithFrame:styleURL:

Is there another way?

**Comment by tmpsantos** [comment]
There is a race between loading the style and adding the annotations that I didn't figured out yet. I guess the only way ATM is to make sure you have the style loaded before you add the annotations.

`loadStyleJSON()` supposedly "fixes" it because it won't make a network request to load the style. I'll try to get back to this issue this week.

**Comment by mb12** [comment]
@picciano  You can experiment with the map events stuff. Maybe there is an event that is emitted to indicate end of style load or any event that is emitted post style load. 

1.) Start listening to mapViewDidFinishLoadingMap  and call setStyleUrl
2.) When the delegate method mapViewDidFinishLoadingMap is called do the annotation stuff.

**Comment by picciano** [comment]
Interesting results, but nothing that helps.

First, it doesn't look like `mapViewDidFinishLoadingMap` is ever called. I see it defined in `view.hpp` and `MGLMapView.mm`, but never referenced anywhere else.

The `mapViewDidFinishRenderingFrame:fullyRendered:` and `mapViewDidFinishRenderingMap:fullyRendered:` looked promising, but the `fullyRendered` flag never goes to `YES` until the map is zoomed down to the next zoom level. Then I get a `YES` and the missing annotations show up.

**Comment by mb12** [comment]
If you build from source, you can try adding view.notify(mbgl::MapChangeDidFinishLoadingMap) after <a href="https://github.com/mapbox/mapbox-gl-native/blob/5ff855bb0054e7055ae23cf072702b3a216b86e4/src/mbgl/map/map_context.cpp#L115">loadStyleJSON  </a> .

**Comment by picciano** [comment]
Thanks. I made the change and am receiving the event in the client app, then adding the annotations after that. But they still do not display until the map is zoomed.

Here is how I added the event notification:

```
    styleRequest = fs->request({ Resource::Kind::Style, styleURL }, util::RunLoop::getLoop(), [this, base](const Response &res) {
        styleRequest = nullptr;

        if (res.status == Response::Successful) {
            loadStyleJSON(res.data, base);
            view.notifyMapChange(mbgl::MapChangeDidFinishLoadingMap);
        } else {
            Log::Error(Event::Setup, "loading style failed: %s", res.message.c_str());
        }
    });
```

**Comment by ljbade** [comment]
Possibly related #2095

**Comment by mb12** [comment]
Sorry it looks like the original analysis/guess regarding it being a race between loading style and adding annotations was wrong. The issue persists even after you made sure its sequential.
