### ISSUE TITLE
Add Java Based Error For validateAccessToken()

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2101]
The SDK should produce a Java stacktrace with a human friendly / readable error message.  This error checking should work for both Programmatic and XML setting of Access Token as described in #1929.  The first thing that will need to be done is revert #2092 as having the `validateAccessToken()` call in `onCreate()` breaks XML setting of Access Tokens.

/cc @ljbade

**Comment by ljbade** [comment]
@bleege Are you sure checking in `onCreate()` breaks XML attributes?

The XML attributes are loaded in `initialize()` which is called during the `MapView()` constructor.

This will be called before `onCreate()` so the access token should already be set.

**Comment by ljbade** [comment]
I tested with the test app and XML access token is working correctly.
