### ISSUE TITLE
Flyover from point A at zoom X  to point B at zoom Y for iOS.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#2102]
Is there some way to emulate flyover from point A at zoom X to point B at zoom Y?

**Comment by 1ec5** [comment]
This will be implemented as part of #1834. Hang tight!

**Comment by 1ec5** [comment]
Just to be sure I understand your request, are you referring to something akin to Apple Maps’ flyover feature? Or something like the [animation shown here](https://www.mapbox.com/blog/mapbox-gl-js-0-8-1/)?

**Comment by mb12** [comment]
I do not need perspective mode.  I just need to animate the following:

1. Start at San Diego at reasonably high zoom.
2. Zoom out to show overview
3. Pan to San Francisco
4. Zoom in again.

**Comment by incanus** [comment]
Something like this would be accomplished in MapKit with `MKMapCamera` and a series of them spun off on delays, chaining together independent animations. 

I wonder if we could do better. 

What about once we have the camera API complete, allowing for passing a waypoint-esque property with multiple points along the path, plus durations. 

Alternatively, we could do a JS-style callback mechanism, chaining completion blocks, similar to a `UIView` animation block.

**Comment by 1ec5** [comment]
This would be accomplished with a combination of #2193 and #2102.

**Comment by 1ec5** [comment]
This would be accomplished with a combination of #2193 and #1581.
