### ISSUE TITLE
Update To Android Marshmallow

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2104]
Android Marshmallow (aka API 23) has [officially launched today (17-Aug-2015)](http://android-developers.blogspot.com/2015/08/m-developer-preview-3-final-sdk.html).  Update Build Tools, Support Libraries, and Compile SDKs to support it.

Also check out the new [Doze / App Standby](https://developer.android.com/preview/behavior-changes.html) features.

![image00](https://cloud.githubusercontent.com/assets/989928/9318204/31424230-4507-11e5-8323-0d5e760dfccb.png)

/cc @incanus @ljbade

**Comment by incanus** [comment]
:white_circle: :fire: :white_circle: :fire: :white_circle: :fire: :white_circle: :fire: :white_circle: :fire: :white_circle: :fire:

**Comment by ljbade** [comment]
Also don't forget the new permissions system! Likely need to tweak way we start GPS.

**Comment by ljbade** [comment]
Also:

4K Display Mode
The platform now allows apps to request that the display resolution be upgraded to 4K rendering on compatible hardware. To query the current physical resolution, use the new Display.Mode APIs. If the UI is drawn at a lower logical resolution and is upscaled to a larger physical resolution, be aware that the physical resolution the getPhysicalWidth() method returns may differ from the logical resolution reported by getSize().

You can request the system to change the physical resolution in your app as it runs, by setting the preferredDisplayModeId property of your app’s window. This feature is useful if you want to switch to 4K display resolution. While in 4K display mode, the UI continues to be rendered at the original resolution (such as 1080p) and is upscaled to 4K, but SurfaceView objects may show content at the native resolution.

**Comment by ljbade** [comment]
We need to test how our MapView behaves in a app that requests the 4K upgrade.

**Comment by ljbade** [comment]
Installed the updated components, trying to update project but is seems the Android support libs for platform 23 have not been uploaded to gradle yet.

**Comment by ljbade** [comment]
OK the new support lib is up. Re-running Travis now.

**Comment by ljbade** [comment]
```
Android is moving away from OpenSSL to the BoringSSL library. If you’re using the Android NDK in your app, don't link against cryptographic libraries that are not a part of the NDK API, such as libcrypto.so and libssl.so. These libraries are not public APIs, and may change or break without notice across releases and devices. In addition, you may expose yourself to security vulnerabilities. Instead, modify your native code to call the Java cryptography APIs via JNI or to statically link against a cryptography library of your choice.
```

**Comment by ljbade** [comment]
@bleege relevant for metrics:
```
Access to Hardware Identifier
To provide users with greater data protection, starting in this release, Android removes programmatic access to the device’s local hardware identifier for apps using the Wi-Fi and Bluetooth APIs. The WifiInfo.getMacAddress() and the BluetoothAdapter.getAddress() methods now return a constant value of 02:00:00:00:00:00.

To access the hardware identifiers of nearby external devices via Bluetooth and Wi-Fi scans, your app must now have the following permissions:

WifiManager.getScanResults(): Your app must have ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION permission.
BluetoothDevice.ACTION_FOUND: Your app must have ACCESS_COARSE_LOCATION permission.
BluetoothLeScanner.startScan(): Your app must have ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION permission.
Note: When a device running M Developer Preview initiates a background Wi-Fi or Bluetooth scan, the operation is visible to external devices as originating from a randomized MAC address.
```

**Comment by ljbade** [comment]
Created tickets for remaining tasks:
https://github.com/mapbox/mapbox-gl-native/issues/2109
https://github.com/mapbox/mapbox-gl-native/issues/2110
https://github.com/mapbox/mapbox-gl-native/issues/2111

**Comment by ljbade** [comment]
@bleege Can you test if support lib version 23 fixes the FAB drop shadow bug?

**Comment by bleege** [comment]
This ticket was about updating to the latest SDK, build tools, and Support Libraries.  Those are done so this issue is done.
