### ISSUE TITLE
default marker image asset

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2106]
We should come up with a basic marker (blank Maki one? something else?) that looks good on all/most maps, bundle it alongside other assets like compass imagery, Mapbox logo, etc., and have the platforms fall back to using it if client code doesn't provide a raster image to use. 

We should do this before updating any style pin to https://github.com/mapbox/mapbox-gl-styles/commit/dbabdfee63fa625ed8af32efa3826c6197d8395b or later.

**Comment by ljbade** [comment]
Good idea!

**Comment by nickidlugash** [comment]
Per chat, I can help out with this. Does something like [this](https://github.com/mapbox/maki/blob/mb-pages/src/marker-18.svg) work? But probably a different color.

- What size/file format does this need to be in? 
- What should it be named?
Where should it live?

/cc @1ec5

**Comment by 1ec5** [comment]
> What size/file format does this need to be in?

Here’s what we’re currently using on iOS:

https://github.com/mapbox/mapbox-gl-styles/blob/mb-pages/sprites/streets-src/renders/extras/default_marker.png
https://github.com/mapbox/mapbox-gl-styles/blob/mb-pages/sprites/streets-src/renders/extras/default_marker%402x.png

PNG would be best (at both resolutions). SVG isn’t a native image format in UIKit.

> What should it be named? Where should it live?

For iOS, the images should live in https://github.com/mapbox/mapbox-gl-native/tree/master/platform/ios/resources and be called something like “default_marker.png” and “default_marker@2x.png”. Just PR the images and I or @incanus can take care of hooking them up to the SDK.

Per @bleege, Android has the images at various resolutions in https://github.com/mapbox/mapbox-gl-native/tree/master/android/java/MapboxGLAndroidSDKTestApp/src/main/res.

**Comment by DiogoAndre** [comment]
Maybe also good to provide @3x to support the 6plus?  It is not mandatory, but would be nice to have the marker in all supported resolutions. 

Here's a handy guide on iPhone screen resolutions: http://iosdesign.ivomynttinen.com/

Looking forward to having default markers, and then #2250 :smile:

**Comment by friedbunny** [comment]
Ideally we'd have `@3x`, too, but I'm not sure that the GL backend can handle `@3x` sprites right now — @incanus? Might as well produce and include the asset, in any case.

An `@3x` marker based on the [current marker](https://github.com/mapbox/mapbox-gl-styles/blob/e48ea060b62ec5a2f76c97840fb67b5e82d74e66/sprites/streets-src/renders/extras/default_marker%402x.png) will be 60x150 (1.5x larger than `@2x`).

**Comment by ljbade** [comment]
@friedbunny Going to have to support arbitrary sprite sizes for Android, from <1.0, to over 4.0. So iOS support for 3x will come soon too I suspect.

**Comment by ljbade** [comment]
Merged, follow up on Android scaling issue im #2506
