### ISSUE TITLE
Test support for Android M 4k screens

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2109]
From:
> 4K Display Mode
> The platform now allows apps to request that the display resolution be upgraded to 4K rendering on compatible hardware. To query the current physical resolution, use the new Display.Mode APIs. If the UI is drawn at a lower logical resolution and is upscaled to a larger physical resolution, be aware that the physical resolution the getPhysicalWidth() method returns may differ from the logical resolution reported by getSize().

> You can request the system to change the physical resolution in your app as it runs, by setting the preferredDisplayModeId property of your app’s window. This feature is useful if you want to switch to 4K display resolution. While in 4K display mode, the UI continues to be rendered at the original resolution (such as 1080p) and is upscaled to 4K, but SurfaceView objects may show content at the native resolution.

We need to check what happens in an app that requests 4k support. I suspect we will need to ensure our GL framebuffer is the correct size and that we calculate the DPI correctly.

**Comment by ljbade** [comment]
Leaving a note here that the new Sony Z5 comes with a builtin 4k screen and appears to use same 1080p -> 4k upscaling mode unless the app opts in to native 4k `SurfaceView`.

**Comment by tobrun** [comment]
Closing this as currently not relevant
