### ISSUE TITLE
Support Android M permissions

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2110]
Android M has new permission model. We need to support this.

From what I can tell this only affects the GPS location support.

More info in https://developer.android.com/preview/features/runtime-permissions.html

Currently in the Android M simulator the test app crashes as soon as you hit the GPS button.

**Comment by ljbade** [comment]
While we are at it we should dynamically check current apps permissions on older Android versions.

That way we remove the location permissions from the app and require the app developer to enable them if they want to use location support in the map.

This will be similar to the way we do things on iOS where a developer can choose to not provide location services.

An example is in http://stackoverflow.com/questions/4616095/how-to-get-the-build-version-number-of-your-android-application

**Comment by ljbade** [comment]
OK here is the plan:
- remove the `LOCATION_COARSE` and `LOCATION_FINE` permissions from SDK manifest and move to the app (if an app never enables `setMyLocationEnabled` then we don't need these, so leave it up to app developers)
- put `LOCATION_COARSE` and `LOCATION_FINE` permissions in the test app manifest
- in the test app correctly check and request those permissions

**Comment by ljbade** [comment]
@bleege Can you test if support lib version 23 fixes the FAB drop shadow bug?

**Comment by ljbade** [comment]
@bleege Can you test if support lib version 23 fixes the FAB drop shadow bug?

**Comment by tobrunvannuland** [comment]
I will take this up, will add the corresponding "runtime permission dialog"

**Comment by ljbade** [comment]
@tobrunvannuland I actually nearly finished this locally will be pushing to branch soon.

**Comment by zugaldia** [comment]
We need to bring (or refactor) the work @ljbade did in https://github.com/mapbox/mapbox-gl-native/issues/2112 to `MyLocationTrackingModeActivity`. We include the right permissions in the manifest, but we need to check for them [at runtime](http://developer.android.com/training/permissions/requesting.html).

Right now, on an Android 6.0 device, the TestApp crashes with the following stack trace:

```
         AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: com.mapbox.mapboxgl.testapp, PID: 7505
                         E  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapbox.mapboxgl.testapp/com.mapbox.mapboxsdk.testapp.MyLocationTrackingModeActivity}: java.lang.Securi
                            tyException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
                         E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                         E      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                         E      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:148)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5417)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                         E  Caused by: java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
                         E      at android.os.Parcel.readException(Parcel.java:1599)
                         E      at android.os.Parcel.readException(Parcel.java:1552)
                         E      at android.location.ILocationManager$Stub$Proxy.getLastLocation(ILocationManager.java:717)
                         E      at android.location.LocationManager.getLastKnownLocation(LocationManager.java:1200)
                         E      at com.mapzen.android.lost.internal.FusionEngine.getLastLocation(FusionEngine.java:50)
                         E      at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.getLastLocation(FusedLocationProviderApiImpl.java:32)
                         E      at com.mapbox.mapboxsdk.views.UserLocationView.toggleGps(UserLocationView.java:335)
                         E      at com.mapbox.mapboxsdk.views.UserLocationView.setEnabled(UserLocationView.java:261)
                         E      at com.mapbox.mapboxsdk.views.MapView.setMyLocationEnabled(MapView.java:3188)
                         E      at com.mapbox.mapboxsdk.testapp.MyLocationTrackingModeActivity.onCreate(MyLocationTrackingModeActivity.java:61)
                         E      at android.app.Activity.performCreate(Activity.java:6237)
                         E      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                         E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                         E      ... 9 more
        CrashlyticsCore  I  Crashlytics report upload complete: 563A37D1008B-0001-1D51-4F70B9451C7C.cls
                Process  I  Sending signal. PID: 7505 SIG: 9

```

**Comment by ljbade** [comment]
Good catch.

**Comment by ljbade** [comment]
@tobrun Has found a crash when you revoke permissions in settings then return to a backgrounded app.

Permissions need to be rechecked in `onStart`

**Comment by ljbade** [comment]
Turns out that when you change a permission, Android will destroy and recreate the activity, just like with rotations.

However we save the GPS enabled state in MapView which then crashes when it tries to restore it in onCreate

**Comment by ljbade** [comment]
I wonder how Google Maps handles this.

@tobrun I'm thinking we either need to move locations permissions handling into MapView, or make GPS enabled a non-saved state, which will be a breaking change...
