### ISSUE TITLE
Test new Android M Doze functionality with async tile requests

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2111]
We should check that our map handles having network suspended and resumed while loading tiles as part of the new Doze functionality in Android M.

More info: https://developer.android.com/preview/testing/guide.html#doze-standby

**Comment by tobrun** [comment]
Some [extra information](https://plus.google.com/+AndroidDevelopers/posts/94jCkmG4jff) on the subject.

**Comment by tobrun** [comment]
>Doze mode is activated when the device is not plugged in, when the screen is locked, and when no motion has been detected for some time. These assumptions imply that the user has put down the device and walked away.

One requirement is that the screen is locked, so we will always get an onPause and afterwards an onResume. I have no idea how loading is currently implemented but I think the doze feature will/should not have an impact on us.

**Comment by ljbade** [comment]
@tobrun do you know what devices will have Android m on them for testing?

**Comment by tobrun** [comment]
I have a Nexus 5 with m preview 3, will probably buy both upcoming nexus devices.
I you need a good test device, nexus is the way to go ;)

**Comment by ljbade** [comment]
I think the only thing Doze might impact is metrics.

**Comment by tobrun** [comment]
Closing this down, not actionable enough. 
- Problems related with metrics will be noticed fast enough, will reopen if a problem surfaces.
