### ISSUE TITLE
Sprites have different colors on Android and iOS

### ISSUE THREAD

**Issue by erf** [mapbox/mapbox-gl-native#2113]
from iOS
![img_1265](https://cloud.githubusercontent.com/assets/1562523/9328264/92727188-45a7-11e5-8617-63af1891ffd9.PNG)
from Android
![screenshot_2015-08-18-12-42-48](https://cloud.githubusercontent.com/assets/1562523/9328265/940751e4-45a7-11e5-94e2-b39b4b4ca0f6.png)

iOS have the correct color.

**Comment by erf** [comment]
Notice Android has a darker color

**Comment by ljbade** [comment]
Hmm interesting.

Perhaps there is a PNG gamma conversion error somewhere.

**Comment by kkaefer** [comment]
This might be related to sRGB. iOS seems to use sRGB by default. We might need to enable `glEnable(GL_FRAMEBUFFER_SRGB)` on Android.

**Comment by ljbade** [comment]
@kkaefer how well supported is that extension?

**Comment by jfirebaugh** [comment]
This may be fixed after 0c1e378bc9555f6cf826bb38b1a36fa742f8ce9b.
