### ISSUE TITLE
allow appledoc upgrade

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2117]
Currently we require appledoc 2.2v963 exactly for iOS docs generation. Is this still the case? If not, let's fix that so we can move on.

**Comment by 1ec5** [comment]
Last I checked, the main holdup was that newer versions of appledoc come with templates that mimick Apple’s 2014-era docsets. Those templates require JavaScript to work correctly, but Xcode’s Documentation window seems to disallow JavaScript in third-party docsets. This won’t be an issue for the [online documentation](https://www.mapbox.com/mapbox-gl-ios/api/) but will be for those who install the docset in Xcode (which I gather will be relatively few people).

I’d much prefer that we come up with new templates, like the ones used for [Mapbox GL JS documentation](https://www.mapbox.com/mapbox-gl-js/api/).

**Comment by 1ec5** [comment]
It’s more likely that we’ll end up switching to jazzy: #3203.

**Comment by 1ec5** [comment]
Bitrise is running appledoc 2.2.1. I just upgraded my machine from 2.2.0 and the templates are broken, which means we’ve been building broken documentation on Bitrise all this time. 2.2.1 comes with an impressive [58 commits](https://github.com/tomaz/appledoc/compare/v2.2-963...2.2.1).

**Comment by 1ec5** [comment]
The template breakage is tomaz/appledoc#561.
