### ISSUE TITLE
Fix linking

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#2126]
We have a few linking messages that are all along these lines:

`ld: warning: direct access in uv::timer::start(unsigned long long, unsigned long long, std::__1::function<void ()>) to global weak symbol uv::timer::timer_cb(uv_timer_s*, int) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.`

**Comment by jfirebaugh** [comment]
This no longer happens.
