### ISSUE TITLE
tile_cover runs too often

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#2127]
We're currently running `tile_cover` on every frame, even if the actual transform didn't change. We should only run `tile_cover` when the transform changes.

**Comment by jfirebaugh** [comment]
After #9119, this should be fairly straightforward to implement:

* Keep a copy of the last used `TransformState` in `TilePyramid`
* Don't recalculate tile cover in `TilePyramid::update` if the incoming `TransformState` hasn't changed
* _Do_ still call `tile.setLayers(layers)` on existing tiles when `needsRelayout` is true, even when the `TransformState` hasn't changed

**Comment by jfirebaugh** [comment]
FWIW, this isn't currently showing up as significant in profiling. Maybe after #9157 is fixed it'll be more prominent.

**Comment by jfirebaugh** [comment]
It's now ~4% of rendering time in the bench app.
