### ISSUE TITLE
Stop / Start Location Services During Lifecycle Methods

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2135]
To better manage resources (aka don't drain the device's battery) Location tracking should be started / stopped when different lifecycle methods are called.  This will be determined by the status of `mIsGpsOn` when each method is called.

* MapView.onPause()
* MapView.onResume()
* MapView.onStart()
* MapView.onStop()

**Comment by ljbade** [comment]
@bleege This is was recently implemented in `master`, currently onPause/onResume calls `toggleGps`.

You can test it by loading the TestApp, turning on the GPS dot then hitting the app switch button, you should see the location indicator in the status bar turn off when the app is paused.

**Comment by bleege** [comment]
@ljbade Perfect!  I verified that they're in [`onPause()`](https://github.com/mapbox/mapbox-gl-native/blob/765c4695d85ca9114c419e2e49f121b41f80a85d/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java#L718-L720) and [`onResume()`](https://github.com/mapbox/mapbox-gl-native/blob/765c4695d85ca9114c419e2e49f121b41f80a85d/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/views/MapView.java#L733-L735) and that they work as needed.  Thanks!
