### ISSUE TITLE
CocoaPods "use_frameworks!" breaks iOS7 support

### ISSUE THREAD

**Issue by millenbop** [mapbox/mapbox-gl-native#2136]
As far as I know, "use_frameworks!" is not supported on iOS7. 

According to https://www.mapbox.com/mapbox-gl-ios/#cocoapods iOS7 is supported, but that is not true. You can get it to run on device running iOS7, yes, but if you try to submit it to Apple, it's rejected.

**Comment by 1ec5** [comment]
We've been discussing this over in #1870, but yes, if you want to deploy backwards to iOS 7.0, you'll either need to use CocoaPods without the use_frameworks flag or use the binary installation method on that page. If you're coding in Swift, this means you'll have to import MapboxGL into a bridging header before using it in Swift code.

**Comment by millenbop** [comment]
Thanks for the speedy reply. I totally missed the "Binary" section of that page, will try that out and see if that works for me. I'd ofc prefer to use CocoaPods, but I'm happy doing it the  old way for now.

Just removing "use_frameworks" gives linker errors (haven't really tried to fix that.. yet). 

I guess the web page needs to be updated by removing the part about support for iOS7, or make use_frameworks optional and make it work without it.

**Comment by incanus** [comment]
Thanks for these clarifications @millenbop — we'll get on this.

**Comment by mackuba** [comment]
You should probably update the docs at https://www.mapbox.com/ios-sdk/#cocoapods, because they specifically show `platform :ios, "7.0"` and `use_frameworks!` right next to each other...

**Comment by millenbop** [comment]
I tried the old fashioned way of statically linking but I wasn't able to get it to build. Not sure if there is something wrong with the lib or something I did or didn't do on my end.

**Comment by 1ec5** [comment]
@millenbop, are you coding in Objective-C or Swift? What build error are you seeing?

**Comment by millenbop** [comment]
Objective-C. It's actually a link error. I don't have the build log in front of me, but I'll get it for you later.

**Comment by millenbop** [comment]
Here's the error log;

`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MGLPolyline", referenced from:
      objc-class-ref in MapBoxViewController.o
  "_OBJC_CLASS_$_MGLAccountManager", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`


libMapboxGL.a is set as required under "General/Linked Frameworks and Libraries", and also in "Build Phases/Link Binary With Libraries". "Library Search Paths" is also correct.

**Comment by 1ec5** [comment]
And did you wind up with `-ObjC` in `OTHER_LDFLAGS` in the Mapbox-iOS-SDK-Mapbox target of Pods.xcodeproj, as well as in your application target?

**Comment by millenbop** [comment]
For MapboxGL, yes I did get -ObjC when using cocoapods. I don't have Mapbox-iOS-SDK-Mapbox, is Mapbox-iOS-SDK required for GL as well? Or maybe that was just a typo.

**Comment by millenbop** [comment]
I just updated my cocoapods and removed use_frameworks, and now it compiles, so whatever you changed appears to have worked. I also noticed it was marked as deprecated, but I guess that's just temporary right?

I haven't tried uploading to AppStore though, but as long as the lib is not dynlinked it should be ok.

**Comment by 1ec5** [comment]
> I also noticed it was marked as deprecated, but I guess that's just temporary right?

Actually, over the weekend, we renamed “Mapbox GL for iOS” to the “Mapbox iOS SDK”, co-opting the old mapbox/mapbox-ios-sdk, which only supported raster tiles. Going forward, we’ll publish new releases of this vector map library to the Mapbox-iOS-SDK pod instead of the MapboxGL pod. That’s why you see the latter as being deprecated. Hopefully that isn’t too confusing. We’re hoping it’ll be less confusing in the long run.

**Comment by 1ec5** [comment]
Glad to hear it worked. Let us know if you have any problems with the submission.

**Comment by millenbop** [comment]
Ah thanks for clearing that up, switching over to the new one.
