### ISSUE TITLE
update Transform geo/screen conversions for tilt

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2139]
In https://github.com/mapbox/mapbox-gl-native/pull/2116 we have a PR for tilt/pitch. However we have yet to update `Transform::pixelForLatLng` & `Transform::latLngForPixel` to actually use the matrix instead of just doing trig for center, zoom, and rotation, so that `pitch` can be factored in. As a result, we get things like the floating user dot on iOS and these conversions will be off for e.g. long-press marker drop gestures, too. 

Note that we do already account for world wrap and the date line in the current routines. 

/cc @ansis @friedbunny @1ec5

**Comment by 1ec5** [comment]
`pixelForLatLng()` and `latLngForPixel()` need to work with `pitch`, or things like `fitToBounds()` will yield unexpected results.

**Comment by incanus** [comment]
Right, this is not just cosmetic.

**Comment by incanus** [comment]
Per chat, it's unclear if `-[MGLMapView metersPerPixelAtLatitude:]` is affected by this. Need to investigate MapKit.

**Comment by ansis** [comment]
These should be implemented in 1551424 and fixed in 1081992.

I'm still working on:
- [ ]  making the same location stay under your finger during panning, zooming, etc
- [ ] making fitBounds work better

**Comment by ansis** [comment]
Gesture improvements are finished in https://github.com/mapbox/mapbox-gl-native/commits/perspective-continued
- when you pan the same location stays under your finger
- when you zoom the location at the center of the pinch stays the same
- when you rotate the location at the center of the pinch stays the same

**Comment by incanus** [comment]
>  making fitBounds work better

Is above and/or anything else here still actionable?

**Comment by 1ec5** [comment]
This is still actionable: `fitBounds` does not account for the trapezoidal shape of the bounds when the map is tilted. As a result, the map’s camera fails to round-trip correctly (tending to zoom out) when the map starts out tilted.

**Comment by incanus** [comment]
Just a clarification question here — does the fact that MapKit doesn’t use perspective, but just simple tilt, behave differently in this regard? I wonder if MKMapRect etc. automatically account for tilt.

**Comment by mb12** [comment]
@incanus is it possible to share what's the difference between Mapbox perspective and Map kit tilt and why one picks over the other?

**Comment by 1ec5** [comment]
#2259 covers the `fitBounds` work that needs to take place. Let’s see if we can get @ansis’ work on the perspective-continued branch into master.

**Comment by 1ec5** [comment]
The perspective-continued branch appears to have been deleted. @ansis, can you re-push your work towards this issue? Thanks.

**Comment by friedbunny** [comment]
I have re-pushed `perspective-continued` from my local copy, feel free to delete if unnecessary.

**Comment by 1ec5** [comment]
I don’t think that was the tip of perspective-continued. Hopefully @ansis has the fixes described in https://github.com/mapbox/mapbox-gl-native/issues/2139#issuecomment-135178162 around locally still.
