### ISSUE TITLE
Multicolored polyline

### ISSUE THREAD

**Issue by webventil** [mapbox/mapbox-gl-native#2142]
It would be nice extending the polyline renderer to support more than one color. These colors have to be faded by a gradient. This would help implementing sport tracking apps or in general having more possibilities to visualize data.

**Comment by webventil** [comment]
![img_8685](https://cloud.githubusercontent.com/assets/1701915/9403260/b7a7eb82-47e5-11e5-84b6-7550d4c15edc.png)

**Comment by lucaswoj** [comment]
This is a cool idea @webventil! Let's have a discussion about stylesheet syntax in https://github.com/mapbox/mapbox-gl-style-spec.

**Comment by jfirebaugh** [comment]
Upstream in #349.
