### ISSUE TITLE
Get tests to work on iOS/Android

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#2150]
We should run all available test suites on each platform.

| Platform | [Core tests](https://github.com/mapbox/mapbox-gl-native/tree/master/test) | [Rendering tests](https://github.com/mapbox/mapbox-gl-test-suite) | Platform tests |
| --- | --- | --- | --- |
| Android | ✘ #4671 | ✘ #2488 | ✔︎ |
| iOS | [✔︎](https://github.com/mapbox/mapbox-gl-native/pull/4574) ([Regressed](https://github.com/mapbox/mapbox-gl-native/issues/6423)) | ✘ #2488 | ✘ #4495, #2734, etc. |
| OS X | ✔︎ | ✘ #2488 | ✔︎ |
| Linux | ✔︎ | ✘ #2488 | n/a |
| Node OS X | n/a | [✔︎](https://github.com/mapbox/mapbox-gl-native/pull/4560) | ✔︎ |
| Node Linux | n/a | ✔︎ | ✔︎ |

**Comment by ljbade** [comment]
On Android side there have been a few tickets in this area: https://github.com/mapbox/mapbox-gl-native/issues/1667

**Comment by ljbade** [comment]
And https://github.com/mapbox/mapbox-gl-native/issues/1898

**Comment by tobrun** [comment]
Closing this down because we have UI testing frameworks for both platforms:
 - Espresso on Android 
 - KIF on iOS

**Comment by jfirebaugh** [comment]
Technically his is still relevant: in a perfect world we would run [the headless rendering tests](https://github.com/mapbox/mapbox-gl-test-suite) on every platform. It's low priority / not actionable right now though.

**Comment by tobrun** [comment]
@jfirebaugh on Android we have Unit tests using JUnit, these are executed on each commit to this repo.
Coverage is not that high but we are working on this to improve.

@1ec5 / @friedbunny does iOS have this?

**Comment by friedbunny** [comment]
iOS has [functionality tests](https://github.com/mapbox/mapbox-gl-native/blob/c10f6489e61a52e3ae36af7cd2c40d120f9181da/test/ios/MapViewTests.m) using KIF.

**Comment by kkaefer** [comment]
@tobrun KIF/JUnit are running integration tests. This issue is about unit tests, that independently test parts of the system. Integration tests may not cover everything tested by unit tests (and vice versa).

**Comment by 1ec5** [comment]
As of #3406, a little of the code shared between the iOS and OS X SDKs is being unit tested (in the strict sense of the word) on OS X. Although this issue sounds like it’s about the rendering tests, which currently rely on gtest. Is gtest compatibility with iOS even feasible?

**Comment by tmpsantos** [comment]
Running at least the `test/storage` tests would be extremely recommended and should be the priority, as these will test the platform specific network backend.

There are several corner cases that must be handled by the network backend that if not implemented correctly can interfere with the cache operation, rendering of stale tiles, etc. They are all covered by the tests.

/cc @tobrun

**Comment by jfirebaugh** [comment]
I started trying to do this in [`android-tests`](https://github.com/mapbox/mapbox-gl-native/compare/android-tests?expand=1). It's difficult because the tests are currently a monolithic thing which requires a full headless implementation for whatever platform they're running on. We may need to split them (and the mbgl-core library they link against) into a part that relies on GL and a part with minimal dependencies.

**Comment by jfirebaugh** [comment]
In #3989 we have a `test` scheme for the iOS Xcode project which runs most (but not all) of the core unit tests. Getting it to actually run successfully in a CI environment is challenging however, and hasn't been tackled yet.

**Comment by jfirebaugh** [comment]
As of #4560 we run rendering tests on the OS X Bitrise Node build.
