### ISSUE TITLE
Add centerOffset and calloutOffset properties to MGLAnnotation

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#2151]
MGLAnnotation needs the ability to shift the positioning of annotations and their callouts, akin to MapKit's [`centerOffset`](https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKAnnotationView_Class/index.html#//apple_ref/occ/instp/MKAnnotationView/centerOffset) and [`calloutOffset`](https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKAnnotationView_Class/index.html#//apple_ref/occ/instp/MKAnnotationView/calloutOffset).

Per @incanus in https://github.com/mapbox/mapbox-gl-native/issues/1121#issuecomment-88667899:

> We will hopefully be passing bitmap imagery across the wire instead of relying on pre-made sprite sheets, so this point is moot. At that point, since you are supplying imagery at runtime (which might be created on-the-fly anyway), passing things like [`calloutOffset`](https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKAnnotationView_Class/index.html#//apple_ref/occ/instp/MKAnnotationView/calloutOffset) and [`centerOffset`](https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKAnnotationView_Class/index.html#//apple_ref/occ/instp/MKAnnotationView/centerOffset) is much more natural.

This should probably happen in conjunction with fixing #1504.

/cc @1ec5

**Comment by incanus** [comment]
We can maybe leverage the GL style spec's `translate` property here.

**Comment by 1ec5** [comment]
In #3135 for OS X, I’ve eschewed the mbgl::Map methods for looking up the annotation images’ alignment rects directly. Eventually, I’d like to reverse it so that MGLAnnotationImage keeps an `anchorPoint` and `calloutEdge`, by analogy with `-[NSCursor hotspot]`.

**Comment by RomainQuidet** [comment]
Hi,
I'd like to work on this feature.

**Comment by RomainQuidet** [comment]
center offset for annotations is done, need to offset the touch event and the callout too.

**Comment by RomainQuidet** [comment]
checkout pull request #3220 for this to work (core + iOS code)

**Comment by 1ec5** [comment]
By way of an update, #3261 introduced support for alignment insets in annotation images, so the “center offset” effect can be achieved by padding the annotation image and insetting it to the visible portion.

**Comment by BFTE** [comment]
Hi @1ec5 , at some point in v.3.1.0 there was a change:
"Tapping now selects annotations more reliably. Tapping near the top of a large annotation image now selects that annotation. An annotation image’s alignment insets influence how far away the user can tap and still select the annotation."

According to above I try to change annotation image alignment rect like this:
```
MGLAnnotationImage *annotationImage;
UIImage *image = [UIImage imageNamed:[self annotationImageName]];
image = [image imageWithAlignmentRectInsets:UIEdgeInsetsMake(0, 0, 60.0, 0)];
annotationImage = [MGLAnnotationImage annotationImageWithImage:image reuseIdentifier:self.identifier];
```

but I did not notice any changes in clickable area which is too big in my case, I have to reduce clickable area to half of the annotation image.
I can add that dequeue method:
```
[mapView dequeueReusableAnnotationImageWithIdentifier:identifier]
```
returns me annotations image with correct alignment rect: (0, 0, 60.0, 0)

Maybe I'm doing something wrong or misunderstand something... Can you show me an example how to set annotation image's alignment rect or what I'm doing wrong? Thanks!

("annotation image" I mean property "image" in MGLAnnotationImage)

**Comment by friedbunny** [comment]
@BFTE We're quite happy to help, but in general please create a new issue or find one that more closely relates to the bug/problem at hand.
