### ISSUE TITLE
Why use libstdc++ and not libc++ with clang++ ?  (Android)

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#2157]
All the native code is compiled with clang++. However when we build libmapbox-gl.so, instead of statically linking libc++.a (which is the runtime c++ library for clang), we link in libstdc++.a.
 
 libc++_static.a is available as part of Android NDK under $ANDROD_NDK_ROOT/sources/cxx-stl/llvm-libc++/libs/{ARCH}/libc++_static.a

**Comment by ljbade** [comment]
I recall there are bugs/issues with libstdc++ with C++14 features.

@kkaefer Is that correct?

**Comment by ljbade** [comment]
@mb12 We are using `libc++_static.a` but as part of building a standalone NDK toolchain (which we use in `mason`) the `$ANDROD_NDK_ROOT/build/tools/make-standalone-toolchain.sh` script renames `libc++_static.a` to `libstdc++.a`.

It appears this is so build scripts that assume `-lstdc++` is how to link to the C++ STL automatically pick up the correct implementation.

**Comment by mb12** [comment]
@ljbade Thanks a lot for the explanation.
