### ISSUE TITLE
make SMCalloutView a CocoaPods dependency for source installs

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2171]
When we are building from source (https://github.com/mapbox/mapbox-gl-native/issues/1437), similarly to how we did in the iOS SDK 1.x, we should have `SMCalloutView` be a CocoaPods pinned to the version we need.

**Comment by friedbunny** [comment]
SMCalloutView is being removed (https://github.com/mapbox/mapbox-gl-native/issues/4392) and we’re not planning on using CocoaPods as a dependency manager in this project (https://github.com/mapbox/mapbox-gl-native/issues/1522).
