### ISSUE TITLE
add delegate methods called when map position/zoom/rotation changes

### ISSUE THREAD

**Issue by mackuba** [mapbox/mapbox-gl-native#2178]
In `MKMapViewDelegate` protocol there are methods `mapView(regionWillChangeAnimated:)` and `mapView(regionDidChangeAnimated:)` which are called when the map is resized, moved or rotated. I use those in my app to restart animation in my custom annotation views, and also to rotate some of them in the right direction (there's a car icon on the map, and it should always be rotated in the direction where the car is heading - normally when you rotate the map, the icon doesn't rotate with it automatically). It doesn't seem like I can do anything like that in Mapbox GL right now.

**Comment by friedbunny** [comment]
[We have `regionWill/Is/DidChange` available](https://github.com/mapbox/mapbox-gl-native/blob/15a5532d76c387142db60913c4ce0876d4450eb8/include/mbgl/ios/MGLMapView.h#L420-L442), though they haven't quite made their way into documentation yet — please give these a try. :dancers:
