### ISSUE TITLE
Add Density Specific Compass Images

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2182]
Android currently uses 1 image size for Compass which is then scaled per density.  iOS provides 3 different assets for each of their primary densities.  Let's repurpose those and fill in missing densities using `@3x` as the source and scale it down.

https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/resources/Compass.png

https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/resources/Compass@2x.png

https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/resources/Compass@3x.png

**Comment by bleege** [comment]
Sizes:

1x = 36x36
2x = 72x72
3x = 104x104

**Comment by bleege** [comment]
Going to use the following scaling rules as it was the one suggested by Google.  ;-)

Accordingly, will start with this `1x == mdpi` and `2x == xhdpi`.

http://stackoverflow.com/questions/11581649/about-android-image-and-asset-sizes

![screen shot 2015-08-26 at 11 08 11 am](https://cloud.githubusercontent.com/assets/989928/9501875/cd15e5f4-4be2-11e5-8de7-52c44ca8c8ec.png)

**Comment by bleege** [comment]
So, change of direction here.  Instead of adjusting an iOS styled compass, I've replaced it with a more Android styled compass image.  This will likely (and should) get replaced in time, but for an initial release this should work.  Let's see how it plays in test though.

![device-2015-08-26-172427](https://cloud.githubusercontent.com/assets/989928/9509729/d758828a-4c17-11e5-8bbf-bb4393a4945c.png)
_New Compass Image On Samsung S5_

**Comment by ljbade** [comment]
Nice @bleege, looks way cooler.

**Comment by ljbade** [comment]
Hmm I think I'm going to disable the elevation on the FAB again. Looks nice on my phones (well except for Samsung), then I see a screenshot like this...

**Comment by bleege** [comment]
Merged.

**Comment by tobrunvannuland** [comment]
@bleege this looks way better, but IMHO it is a bit pixelated.
Could a designer produce an svg for us? 
Android Studio has a Vector Asset wizard that generate pngs.

**Comment by ljbade** [comment]
I also noticed that the white section of the compass is transparent. So it lets through the map in that triagngle.

**Comment by bleege** [comment]
I discussed this with @tatsvc and she's graciously agreed to update the compass image.  She'll touch up the original design and then produce sizes for `mdpi`, `hdpi`, `xhdpi`, and `xxhdpi`.  She'll post the results to this ticket and then I'll re-integrate them into the SDK.

**Comment by tatsvc** [comment]
I'm suggesting something like this with a subtle transparent outline, so it doesn't get lost on a dark map:

![d758828a-4c17-11e5-8bbf-bb4393a4945c](https://cloud.githubusercontent.com/assets/2894119/9661815/bc2ec6c2-525c-11e5-9bfb-e5a3fc584e1a.jpg)

![48](https://cloud.githubusercontent.com/assets/2894119/9661844/e6646ffa-525c-11e5-966f-cdf73e0acaac.png)
![72](https://cloud.githubusercontent.com/assets/2894119/9661841/e66160bc-525c-11e5-80e8-3ac53b3fab0b.png)
![96](https://cloud.githubusercontent.com/assets/2894119/9661843/e6637fd2-525c-11e5-9db6-492b7b8a8a3a.png)
![144](https://cloud.githubusercontent.com/assets/2894119/9661842/e66206b6-525c-11e5-9650-734f77c04f67.png)

**Comment by bleege** [comment]
Screenshot of the @tatsvc's new and improved compass imagery in action.  :ok_hand: 

![device-2015-09-03-143009](https://cloud.githubusercontent.com/assets/989928/9668704/c5fe9da8-5248-11e5-8a2f-c029c01555de.png)

![device-2015-09-03-143023](https://cloud.githubusercontent.com/assets/989928/9668708/c97ac0a6-5248-11e5-8843-27ce59f94cb4.png)

![device-2015-09-03-143116](https://cloud.githubusercontent.com/assets/989928/9668710/cd116602-5248-11e5-9ca6-b802009909fc.png)

![device-2015-09-03-143136](https://cloud.githubusercontent.com/assets/989928/9668715/d024fbc4-5248-11e5-9a60-4864b28d8d6f.png)

**Comment by tatsvc** [comment]
Awesome! Works really well on the black map as well! Yay

**Comment by bleege** [comment]
Merged!  Thanks again @tatsvc!

**Comment by ljbade** [comment]
Wow so pretty.
