### ISSUE TITLE
Use Square Leak Canary To Review Performance

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2184]
Let's use [Square Leak Canary](https://github.com/square/leakcanary) to help track memory usage / guard against leaky 1s and 0s.

https://corner.squareup.com/2015/05/leak-canary.html

**Comment by ljbade** [comment]
@bleege Only thing to remember is I don't think this will catch leaks caused in the native side, or track memory used by native objects held by Java objects.

Still useful however.

**Comment by tobrun** [comment]
I added LeakCanary to the sample app but it is not playing nice with the native code.
In certain cases, it shows the dialog to dump memory but it never closes.. 
Only killing the app resolves this.

![leakcanary2](https://cloud.githubusercontent.com/assets/2151639/10016505/d5523bdc-6127-11e5-90cd-cea8eaa5abff.png)
![leakcanary](https://cloud.githubusercontent.com/assets/2151639/10016506/d7a402e4-6127-11e5-9b1e-d2adfe32f999.png)



Haven't had this issue on while developing trivial apps.

**Comment by incanus** [comment]
:snowflake:

**Comment by ljbade** [comment]
Perhaps it doesn't know how to free non-Java threads that are created on the C++ side.

Do they have NDK support/integration that we need to enable?

**Comment by ljbade** [comment]
There is an issue on this here:
https://github.com/square/leakcanary/issues/285

Looks like we would need to bring back the external storage permission as well as some permission checks for Marshmallow.

**Comment by pyricau** [comment]
LeakCanary `1.4-SNAPSHOT` has a fix for this (asking for permission at runtime on M). You'll need the storage permission on your dev builds. You could also implement your own `LeakDirectoryProvider` and use a different storage.

**Comment by tobrun** [comment]
I reintegrated this in the TestApp and :snowflake: problem from above seems to be resolved. 
Will PR so we can close this issue.
