### ISSUE TITLE
Add Windows Phone support by using ANGLE

### ISSUE THREAD

**Issue by bmeine** [mapbox/mapbox-gl-native#2185]
I know y'all are busy with both iOS & Android...hence "later down the road", but it'd be nice to have it on a future roadmap.

Add Windows Phone support by using ANGLE (https://code.google.com/p/angleproject/)

Thanks

**Comment by incanus** [comment]
Interesting, thanks for the link @bmeine. I am going to close the ticket right now as we still have no plans for Windows, but having this ticket is useful for search / future references purposes when we have a larger business driver to think about this again.
