### ISSUE TITLE
Annotations don't maintain size during tilting

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#2186]
When the map is tilted, marker annotations are scaled with the rest of the map — markers closer to the horizon are small and difficult to interact with.

We should provide an option (default: on) for annotations to maintain their normal scale during tilting.

![simulator screen shot aug 26 2015 4 47 13 pm](https://cloud.githubusercontent.com/assets/1198851/9509256/36f57c4e-4c12-11e5-86be-d6084a6f85b3.png)

/cc @ansis @incanus @1ec5

**Comment by incanus** [comment]
This is especially jarring considering the wide range of sizes that can happen. 

![img_4133](https://cloud.githubusercontent.com/assets/17722/9513641/154f4da6-4c47-11e5-9e8b-31ebaa41a1e4.PNG)

**Comment by ansis** [comment]
Yeah, it's not just annotations. Road and poi labels become illegible near the top. Nothing works well when the map is tilted this steep. The roads become so narrow they disappear. Steep tilt is a completely different game. Many things (rendering, data loading, styling, labeling) need to be different. I think this will be a lot of work so I'm not sure how soon we'll have it.

We can also tweak the [`altitude`](https://github.com/mapbox/mapbox-gl-native/blob/0e456940b98f53624618f4e2a42bf025ce392a9e/src/mbgl/map/transform_state.hpp#L103) parameter to make the maps less perspectivey. If altitude is higher than the map can be squished more in the y direction without making close things appear bigger.

What's the use case here? Why is the map in perspective mode and why do annotations need to be equally prominent in this case?

Does it matter that it's harder to interact? Can the user just pan the map forward to make things at the back bigger? (this will be easier with https://github.com/mapbox/mapbox-gl-native/issues/2139#issuecomment-135178162)

Does the hit detection need to be adjusted for perspective views?

**Comment by mb12** [comment]
In Nokia maps, Google Maps and Apple maps,  the user can drop a pin (annotation) anywhere on the map. The application then does an object query and shows whats at that point (address etc.).  This user pin retains its original size/shape when the map is panned with perspective enabled.

**Comment by incanus** [comment]
What @mb12 said — all mobile toolkits maintain size for markers. This affects hit detection as well as popup/callout placement. 

The use case is general tilt for interactive maps just like other frameworks. Once you've got tilt, users expect it to work the same way.

**Comment by friedbunny** [comment]
Aye, parity is the main reason — having the option to perspective-scale markers is cool, though.

**Comment by incanus** [comment]
Per voice, this sounds like a fairly heavy lift since it would "undoing" the sizing for certain symbols and not necessarily just not executing a current routine. It also has collision implications. 

We can also play with the altitude to see how it affects the steepness of the angle.

**Comment by friedbunny** [comment]
The user location annotation's accuracy circle now has the opposite problem: it should maintain scale as the map is vertically panned, but it instead maintains a constant size... which means it's inaccurate everywhere on the tilted screen except in the center.

The user location annotation is a native `UIView` and will need a separate-but-related fix to our GL-implemented marker annotations.

**Comment by 1ec5** [comment]
#5040 asks for the opposite behavior with respect to the user dot and other annotation views.

**Comment by 1ec5** [comment]
#9009 will unblock this work at the mbgl level.
