### ISSUE TITLE
Add puck for course tracking mode

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#2188]
The puck is the on-screen element that's shown during course-based user location tracking, usually in conjunction with navigation.

![puck](https://cloud.githubusercontent.com/assets/1198851/9510593/7b214b22-4c22-11e5-9131-3c9d6f22c99e.jpg)

/cc @incanus @1ec5

**Comment by 1ec5** [comment]
This was fixed in #2233.
