### ISSUE TITLE
line blur adjustment is sometimes wrong in perspective views

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#2189]
from https://github.com/mapbox/mapbox-gl-native/pull/2116#issuecomment-135460967

@1ec5 

![](https://cloud.githubusercontent.com/assets/1231218/9523981/5e7c98c2-4c91-11e5-9b22-daecd760d705.jpg)
![](https://cloud.githubusercontent.com/assets/1231218/9523983/5eb639f6-4c91-11e5-99be-c17e42ca2ea5.jpg)

**Comment by ansis** [comment]
@1ec5 I think `fix-perspective-line-blur` should fix this. Can you check if it fixes rendering for you?

**Comment by 1ec5** [comment]
Yes, that fixes it. Thanks!
