### ISSUE TITLE
Sky and ground need distinct background colors

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#2190]
The perspective view being added in #2116 and #2159 will constrain the pitch to 90° (at least at the mbgl level). MGLMapView currently constrains it further to 60° to avoid showing the horizon, but we’d like to use a limit that varies by zoom level (altitude) for consistency with MapKit. At the lowest altitude, about 7 stories up, MapKit shows an idyllic blue sky:

![sky](https://cloud.githubusercontent.com/assets/1231218/9528548/e2ca8d74-4ca9-11e5-9956-1bc5b6bc2149.PNG)

By contrast, Mapbox GL uses the background color, which for most maps will be similar to the ground color. It should be possible to style a second background color that represents the “room in which the map is floating”, so to speak.

/ref #119, #1210
/cc @ansis @incanus

**Comment by incanus** [comment]
Do you see this happening at the platform level @1ec5? Like, could this just be a subview of the `MGLMapView` behind the `GLKView`?

**Comment by 1ec5** [comment]
The GLKView draws inside its entire bounds, doesn’t it?

**Comment by incanus** [comment]
Yes, but we might be able to make part of it transparent? Not sure.

**Comment by ljbade** [comment]
Shouldn't this be styleable, e.g. night vs daytime maps

**Comment by 1ec5** [comment]
A common workaround seen in navigation applications is to fake the presence of a sky by overlaying a view with a linear gradient from opaque blue at the top to clear at the bottom. However, the effect is artificial at best, because it violates the user’s sense of horizon.

Another workaround, more common in games, is to simulate poor visibility with a fog effect. It’s basically the same as the previous workaround, except using opaque gray and a steeper gradient. Neither of these workarounds will work once we have 3D extrusion (#6745), because the extruded geometries will be truncated at the simulated horizon.

As @incanus indicated in https://github.com/mapbox/mapbox-gl-native/issues/2190#issuecomment-135511297, it may be possible to make MGLMapView’s layer non-opaque, taking advantage of #3096, then place a view with the desired background color behind the MGLMapView.

**Comment by 1ec5** [comment]
> we’d like to use a limit that varies by zoom level (altitude) for consistency with MapKit

#6908

**Comment by 1ec5** [comment]
> it may be possible to make MGLMapView’s layer non-opaque, taking advantage of #3096, then place a view with the desired background color behind the MGLMapView

No, that won’t work, because – as I originally described above – the sky and ground are rendered using the same background style layer. If you make the background style layer transparent and slide a blue view beneath the map view, the ground becomes blue too.

**Comment by mdakram** [comment]
Any update on this?

**Comment by ansis** [comment]
@mdakram nope, we haven't fixed the things blocking us from allowing the map to be pitched far enough to have the sky show (level-of-detail loading, antialiasing issues, etc).

**Comment by astojilj** [comment]
Dependent on https://github.com/mapbox/mapbox-gl-js/pull/8975.
