### ISSUE TITLE
Tilt gesture is slightly delayed

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#2192]
Compared to Apple, our tilt gesture lags — both in initial recognition and during the gesture. This may be two issues:
1. Our iOS gesture recognizer may be waiting too long to see if other gestures are failing
2. Setting pitch on the map view may have a lag before it takes effect

/cc @ansis @1ec5 @incanus

**Comment by incanus** [comment]
Per voice, a way to address this might be to combine the rotate + tilt + two-finger tap to zoom out gestures into one so avoid conflicts amongst two-finger gestures.
