### ISSUE TITLE
Remove Height / Width On Test App FAB

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2194]
[FAB shadow issue](https://github.com/mapbox/mapbox-gl-native/issues/2104#issuecomment-132104443) with Design Support Library.  Let's pull it for now in the TestApp.

**Comment by bleege** [comment]
Current rendering on Samsung S5.

![device-2015-08-27-124436](https://cloud.githubusercontent.com/assets/989928/9531187/66d53042-4cb9-11e5-81ca-d5702ccca698.png)

**Comment by bleege** [comment]
Now.... shadowless!

![device-2015-08-27-133025](https://cloud.githubusercontent.com/assets/989928/9532368/1ac878f6-4cc0-11e5-97ec-41d35ef012a0.png)

**Comment by bleege** [comment]
Merged.

**Comment by ljbade** [comment]
If anything it matches the flat compass.
