### ISSUE TITLE
Polka dot sprite pattern scales poorly when tilted

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#2196]
The sprite pattern used to fill schoolgrounds in Emerald scales poorly towards the back when the map is tilted to 60°:

![polka](https://cloud.githubusercontent.com/assets/1231218/9535408/be462798-4cd5-11e5-8178-3ec411c445e8.PNG)

@ansis suggested that using a mipmap for the sprite would address this issue.

/cc @peterqliu

**Comment by planemad** [comment]
Looks like [moire patterns](https://en.wikipedia.org/wiki/Moiré_pattern)
