### ISSUE TITLE
Add option to control MGLAnnotationImage's anchor point.

### ISSUE THREAD

**Issue by petrmanek** [mapbox/mapbox-gl-native#2203]
Hello again! This time, I have a trivial feature request.

When annotating map views with point markers, I commonly use custom images. It is often a problem for me (and my OCD-suffering graphic designer) to align these images precisely at the correct geographic coordinate since their *anchor point* differs from the default marker image.

I don't know if the images are aligned so that their middle center point rests on the exact coordinate, or the bottom center point does. Anyway, it would be great if I didn't have to resort to padding my marker images with transparent pixels on their sides just to achieve a precise alignment.

I would therefore like to propose a new trivial feature which might be implemented as a new property on the `MGLAnnotationImage` class. This property could be a `CGPoint` specifying an exact anchor point within the `UIImage`'s bounds. To maintain backward compatibility, value of this member could be initialized to the current anchoring policy by default.

From what I can think of, there are two more alternatives to this:

 1. Use the same property but let it have a relative value instead of an absolute one, just like `CALayer.anchorPoint`. Problem with this option is the initial value, what would it be?
 2. Specify an explicit anchoring policy and add a `CGPoint` property which would control point offset in relation to that policy. By default, value of this property would be `CGPoint.zeroPoint`. This, I think, is the most Apple-compliant way to implement the feature.

IMHO this is quite trivial feature to implement. The only thing worth discussing is the object paradigm to use. I look forward to your comments!

**Comment by incanus** [comment]
:point_right: https://github.com/mapbox/mapbox-gl-native/issues/2151
