### ISSUE TITLE
MGLMapView setCenterCoordinate:zoomLevel:animated doesn't stop any running animations

### ISSUE THREAD

**Issue by tomtaylor** [mapbox/mapbox-gl-native#2204]
When doing the following:

- `setCenterCoordinate:zoomLevel:animated` is called, with a true animation flag
- while the animation is executing, `setCenterCoordinate:zoomLevel:animated` is called again, with a false animation flag

The MGLMapView ends up at the first location, ignoring the second call. I can see the `mapViewRegionIsChanging` callback announce the second location once, as expected, but then it continues to announce the remaining regions changes for the animation.

Perhaps related, if an `MGLMapView` is already set to the exact region the user is animating to, the `mapViewRegionIsChanging` callback is fired a number of times, announcing the current position, without the map region actually changing.

**Comment by incanus** [comment]
@tomtaylor Is this still an issue with the latest release and the camera API?

**Comment by tomtaylor** [comment]
@incanus I haven't switched to using the camera API, but it's still an issue with `setCenterCoordinate:zoomLevel:animated`. I can try the camera API if you think it'll behave differently.

**Comment by tomtaylor** [comment]
Just to confirm - this is still a problem with the `setCamera` API too.

**Comment by tomtaylor** [comment]
(Ignore previous messages) This looks fixed to me.
