### ISSUE TITLE
Replace MGLAnnotation image on didSelectAnnotation:

### ISSUE THREAD

**Issue by hshah2811** [mapbox/mapbox-gl-native#2210]
In Earlier Mapbox version 1.X, we do have RMMarker.replaceUIImage(Image) API to change the annotation image on marker/annotation selection.

But in new 2.0+ versions, i cann't see any API available on MGLAnnotation to replace the existing annotation image. 

Requirement is: I want to change annotation/marker image when user taps/select on any annotation/marker in the map. 

CODE:

Assigning non-selected image to all markers during map load.

- (MGLAnnotationImage *)mapView:(MGLMapView *)mapView imageForAnnotation:(LocationBasedObjectAnnotation *)annotation {
    UIImage * image = [UIImage imageNamed:@"nonSelectedImage"];
    NSString * reuseIdentifier = NSStringFromClass(annotation.class);
    return [MGLAnnotationImage annotationImageWithImage:image reuseIdentifier:reuseIdentifier];
}

Once user taps:
- (MGLAnnotiation*) mapView:(MGLMapView*)mapView didSelectAnnotation:(MGLAnnotation*)annotation
{

//No API to change image of selected annotation 
}

**Comment by incanus** [comment]
This will rely on #1688.

**Comment by incanus** [comment]
Refs https://github.com/mapbox/mapbox-gl-native/issues/1980

**Comment by hshah2811** [comment]
May i know when can we expect this fix?

**Comment by incanus** [comment]
@hshah2811 That (#1688) is of a class of bug/enhancement we are trying to get into this week's release, but it may not quite make it. Stay tuned — on a short timeline.

**Comment by minikin** [comment]
I'm also  looking forward to fix this bug/enhancement. Thank you.

**Comment by RomainQuidet** [comment]
FYI I'm working on it. Will send a pull request soon

**Comment by RomainQuidet** [comment]
Code is working, cleaning up and pull request coming soon

**Comment by RomainQuidet** [comment]
Pull request sent : (#3146)
Just get your annotationImage and update the image property

**Comment by friedbunny** [comment]
Fixed by #3146.

**Comment by minikin** [comment]
@RomainQuidet Could you give me an example how to change an image(MGLAnnotationImage) for selected annotation in didSelectAnnotation? I can't figure out ... 
Thank you in advance.

**Comment by RomainQuidet** [comment]
@minikin : I'm doing this on my sample
`- (void)mapView:(MFMapView *)mapView didSelectAnnotation:(nonnull id<MGLAnnotation>)annotation
{
    // set selected annotation image
    MGLAnnotationImage *annoImage = [self.annotationImages objectForKey:annotation.title];
    annoImage.image = [UIImage imageNamed:@"marker-green"];
}
`

**Comment by minikin** [comment]
@RomainQuidet Thank you very much!
Just one question: How do you define annotationImages ?
I do like this :
`var annotationImages = [String:MGLAnnotationImage]()` also tried `var annotationImages = [String:AnuObject]()` but I can't call   ` objectForKey`

I would  appreciate any advice. Thanks.

**Comment by RomainQuidet** [comment]
@minikin MGLAnnotationImages are objects in the mapBox SDK with a designated initializer
+ (instancetype)annotationImageWithImage:(UIImage *)image reuseIdentifier:(NSString *)reuseIdentifier;
(in ObjC)

**Comment by minikin** [comment]
@RomainQuidet  Thank you.
If I understand you correctly  I need to do like this: 

 ```
   let annotationImage = self.mapView.dequeueReusableAnnotationImageWithIdentifier("nonSelectedImage")

       let annoImage = annotationImage?.valueForKey(annotation.title!!) as! MGLAnnotationImage
    
      annoImage.image = UIImage(named: "selectedPin")!
```
I have an error :

```
[< UIImage 0x7f91060f0cd0 > valueForUndefinedKey:]: this class is not key value coding-compliant for the key Antalia.

objc[54908]: pthread_rwlock_rdlock failed (11)
```

ps:  `annotation.title!! `- looks weird

**Comment by minikin** [comment]
@1ec5 maybe you can help me? Thanks!

**Comment by 1ec5** [comment]
@minikin, please [contact our Support staff](https://www.mapbox.com/contact/), and we’d be happy to assist you further.

**Comment by alexagat** [comment]
I am still facing an issue trying to change an image of annotation on the fly.

I create a dictionary of annotation titles to annotations - [String : MGLAnnotationImage]
`var annotationsTitlesAndImages: [String:MGLAnnotationImage] = [:]`

I populate this dictionary with all my MGLAnnotationImages within the `imageForAnnotation` function
`annotationsTitlesAndImages[annotation.title!!] = annotationImage`

I try and update the annotation's image in the `didSelectAnnotation` function
`annotationsTitlesAndImages[annotation.title!!]!.image = UIImage(named: "map-pin-active")!`

With a breakpoint, I see this code in the framework being run:
```
- (void)setImage:(UIImage *)image {
    _image = image;
    [self.delegate annotationImageNeedsRedisplay:self];
}
```

...but the image doesn't update.

Any insight?

**Comment by RomainQuidet** [comment]
replacing the image property of annotationImage should do the job. But I've seen yesterday an error saying 
`{Map}[Sprite]: Can't change sprite dimensions for 'com.mapbox.sprites.4'`

I'll check that.

**Comment by Ramshandilya** [comment]
@alexagat Were you able to find a way to change image of an annotation? (without removing & adding)

**Comment by 1ec5** [comment]
@alexagat @Ramshandilya, setting the MGLAnnotationImage’s `image` property should work following #3835. Please try it out in the v3.3.0 alphas and let us know if it isn’t working as expected. Thanks!
