### ISSUE TITLE
Allow more annotation callout view customization

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#2211]
Our annotation callout view is [currently hardcoded to a plain `SMCalloutView`](https://github.com/mapbox/mapbox-gl-native/blob/c6e3ed8c6629d0a42d984a4ced57eff558eac0ea/platform/ios/MGLMapView.mm#L2215-L2225) and only offers custom title/subtitle text and [customization of the left and right accessory views](https://github.com/mapbox/mapbox-gl-native/blob/c6e3ed8c6629d0a42d984a4ced57eff558eac0ea/include/mbgl/ios/MGLMapView.h#L408-L439).

We should expose our `SMCalloutView` object and/or provide a delegate method for setting a custom callout view on a per annotation basis.

/cc @1ec5 @incanus

**Comment by wrutkowski** [comment]
Possible duplicate of https://github.com/mapbox/mapbox-gl-native/issues/1784

**Comment by friedbunny** [comment]
> Possible duplicate of #1784

#1784 is a similar use case, but refers to adding arbitrary custom native views as annotations on top of the GL map view. This ticket refers to our existing callout view, which needs to be better exposed for customization.

**Comment by Name-less** [comment]
Someone know if callout view customization will be avaible ?

**Comment by robipresotto** [comment]
+1

**Comment by ljbade** [comment]
@friedbunny Adding parity ticket as we already have this feature in Android release.

**Comment by RomainQuidet** [comment]
Hi, we need this feature at Mappy, I'm working on adding an API to set a custom callout view

**Comment by RomainQuidet** [comment]
new pull request done: #3322

**Comment by YBthebest** [comment]
Hi,

is this possible with the new pull request? I'd like to display a UIView instead of the default callout, is this achievable?

Thanks!

**Comment by byroncoetsee** [comment]
That's what I'm busy doing at the moment @YBthebest . You can do it by returning false for the `annotationCanShowCallout` delegate method and handling the annotation manually. For example show your custom UIView from that method with the information contained in the annotation (which already comes in as an argument in the `annotationCanShowCallout` method)

**Comment by RomainQuidet** [comment]
@byroncoetsee it's already done by this pull request #3322
@YBthebest Yes just pull the branch dedicated to #3322 and go to the demo app, there is an example.

**Comment by YBthebest** [comment]
@RomainQuidet sorry I'm fairly new to Github and its process, how can I pull your branch? I can't seem to find an URL

**Comment by RomainQuidet** [comment]
if you're new to github use the graphical app from github or bitbucket (I like sourceTree on MacOSX). From the graphical app, you have a remote source where you'll see all branches, find the one starting with 2211_ it's the one I worked on. then double click on it to pull it from the source.
If you're new to Git, read some doc about sources management!

**Comment by YBthebest** [comment]
Thanks for the tips, I have started reading all the docs !

For the time being, I am using SourceTree, and it's quite weird because in the "Remotes" => "origin" section, I see loads of branches, but the 2211 branch isn't there...

**Comment by RomainQuidet** [comment]
@YBthebest Sorry, it's not in MapBox repo yet, it's in our fork : https://github.com/Mappy/mapbox-gl-native

**Comment by YBthebest** [comment]
Will it be in the MapBox repo soon? Thanks for the great work

**Comment by friedbunny** [comment]
Fixed by #3456.
