### ISSUE TITLE
icons sometimes are not z-ordered correctly with icon-translate-anchor: viewport

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#2212]
The `icon-translate-anchor/viewport` test is flapping.

Expected:

![](http://mapbox.s3.amazonaws.com/mapbox-gl-native/tests/5853.1/icon-translate-anchor/viewport/expected.png)

Occasionally will render like this:

![](http://mapbox.s3.amazonaws.com/mapbox-gl-native/tests/5853.1/icon-translate-anchor/viewport/actual.png)

Diff:

![](http://mapbox.s3.amazonaws.com/mapbox-gl-native/tests/5853.1/icon-translate-anchor/viewport/diff.png)

You can see the wrong z-order in the set of icons that are close together in a line. The other diffs come from pixel positioning differences.

**Comment by jfirebaugh** [comment]
cc @ansis

**Comment by ansis** [comment]
this is probably the same bug as #1800

**Comment by jfirebaugh** [comment]
Heh, yeah, I forgot I already reported this.
