### ISSUE TITLE
Add marker/annotation clustering with animations

### ISSUE THREAD

**Issue by bmeine** [mapbox/mapbox-gl-native#2214]
It'd be great to get some clustering...maybe similar to Leaflet Marker Clustering

http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html

I actually got this working by porting the JS to C# in Xamarin iOS and used views instead of actual annotations, but wanted to try to improve it further.

I noticed the tracking of annotations appears smoother than tracking views (especially on Android) so I tried to make it so it dynamically switched to a view for the animation then back to the annotation when the animation was complete, but haven't got that working right yet.

If there's any way to dynamically change the position and opacity of an annotation then I'd be set, but I haven't seen anything like that.

**Comment by incanus** [comment]
:point_right: https://github.com/mapbox/mapbox-gl-native/issues/320
