### ISSUE TITLE
Download Multiple ROI

### ISSUE THREAD

**Issue by akapoor-ari** [mapbox/mapbox-gl-native#2215]
Note: Offline maps / Maps download needs to be supported for this issue. This is dependent on https://github.com/mapbox/mapbox-gl-native/issues/584

This is a feature request for downloading maps for multiple region of interests (ROI) on Mapbox GL SDK. Currently this functionality is not available even available in the raster SDK as it allows downloading on single ROI

**Comment by jfirebaugh** [comment]
Support for multiple ROIs is part of #3715 and will be included in SDK bindings in future iOS and Android releases.
