### ISSUE TITLE
Support for Pause and Cancel of tiles download

### ISSUE THREAD

**Issue by akapoor-ari** [mapbox/mapbox-gl-native#2216]
Note: Offline maps / Maps download needs to be supported in GL SDK for this issue. This is dependent on https://github.com/mapbox/mapbox-gl-native/issues/584

This is a feature request for interfaces to pause and stop the ongoing download of map tiles for an ROI. While downloading maps the user might want to pause or cancel the download. 

Also, a "good to have" feature would be to implement a download manager so that in case the  download is terminated unexpectedly (due to netwok issues), it is started from the point where it was terminated.

**Comment by jfirebaugh** [comment]
The ability to deactivate a download is part of #3715 and will be included in SDK bindings in future iOS and Android releases.
