### ISSUE TITLE
Clear cache after partial/incomplete download

### ISSUE THREAD

**Issue by akapoor-ari** [mapbox/mapbox-gl-native#2217]
Note: Offline maps / Maps download needs to be supported in GL Android SDK for this issue. This is dependent on https://github.com/mapbox/mapbox-gl-native/issues/584

This is a feature request for Mapbox GL Android SDK to clear the cache in case the download is terminated unexpectedly. This has been observed in Mapbox Raster SDK that in case the download of tiles fails, the SDK did not clear the incomplete download data and doesn't allow another download, thus leaving user with the only option to clear data or re-install the app.

**Comment by jfirebaugh** [comment]
Removal of offline regions is part of #3715 and will be included in SDK bindings in future iOS and Android releases.
