### ISSUE TITLE
Download Progress Information

### ISSUE THREAD

**Issue by akapoor-ari** [mapbox/mapbox-gl-native#2219]
Note: Offline maps / Maps download needs to be supported in GL SDK for this issue. This is dependent on https://github.com/mapbox/mapbox-gl-native/issues/584

This is a feature request for Mapbox GL Android SDK to add interface to provide feedback about the download progress. Following information is requested to be supported:
1. Number of tiles downloaded / Total number of tiles
2. Size in bytes download / Total size in bytes
3. Radius of area downloaded / Radius of total area requested

**Comment by jfirebaugh** [comment]
Download progress notification is part of #3715 and will be included in SDK bindings in future iOS and Android releases.
