### ISSUE TITLE
Introduce custom views - enhancement/refactor

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2222]
For Android we are currently using multiple Views to overlay the MapView (eg. CompassView). I'm suggesting to refactor these into custom views.  

This would have following benefits:
 - easier to write independent tests and trace bugs  
 - makes the size of MapView class smaller which makes it easier to maintain
 - makes it easier for users to change appearance (configuration through styles/theme, no boiler plate)
 - makes multiple custom attributes obsolete, by applying them directly on a the custom view we can use attributes from the framework.

*Current custom attributes used for compass :
>   \<attr name="compassEnabled" format="boolean" />
>        \<attr name="compassGravity"></attr>
>  \<attr name="compassMarginLeft" format="dimension"/>
> \<attr name="compassMarginTop" format="dimension"/>
>  \<attr name="compassMarginRight" format="dimension"/>
>   \<attr name="compassMarginBottom" format="dimension"/>

**Comment by tobrun** [comment]
First will try to introduce custom styles for each component before actually introducing customviews

**Comment by ljbade** [comment]
@tobrun what about https://github.com/mapbox/mapbox-gl-native/issues/2224 ?

**Comment by tobrun** [comment]
It is in the same line as these enhancements, will do a test on that first before taking this up

**Comment by tobrun** [comment]
Been trying some stuff out:
 - created a CompassView 
  - this works great, removed a lot of code from MapView!
 - tried creating separate attributes for CompassView
  - this would only work if we enforce the end developer to use a theme we are supplying:

>     <style name="CustomCompassView" parent="Theme.Mapbox.CompassView">
        <item name="android:gravity">left</item>
        <item name="android:layout_marginLeft">32dp</item>
    </style>

**Comment by tobrun** [comment]
Will finalise CompassView and drop the attributes part.

**Comment by incanus** [comment]
Can we think about possible integration testing here (even if only local for now)? I'm not as familiar with the specifics of the Android views, but one thing we test for on iOS (and I know Android doesn't do this one in particular, but it's an example) is that tapping the compass rotates the map back to north-up, then fades out the compass opacity (just like Apple's MapKit). That's the kind of thing I mean. It's fine if we don't have enough complex UI dependencies like this (yet) on Android, but just something to think about. 

Example on iOS: https://github.com/mapbox/mapbox-gl-native/blob/d89aa51e0f59b2465dbbe5e56dd7c59ed88b2e86/test/ios/MapViewTests.m#L60-L81

**Comment by tobrun** [comment]
@incanus currently we are using JUnit for unit tests and Espresso for ui tests. An integration testing framework to test components like a View has not been setup. For this I would advice going for something like [RoboElectric](http://robolectric.org/), it has the benefit of running tests on the jvm of the development machine. 

For now I will write tests in Espresso, will migrate if we would use something like RoboElectric.

**Comment by tobrun** [comment]
Apparently Espresso doesn't support Rotation gestures out of the box, need to discuss test setup with @bleege. In meantime will generate PR so we can have :eyes: on current progress.

**Comment by bleege** [comment]
Interesting find @tobrun.  :+1: on PR with what you have now though.
