### ISSUE TITLE
Non public-resources in AAR 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2223]
For the Android SDK we should support configuration of [non-public resources](https://plus.google.com/+ChrisBanes/posts/8Rip6rQGK32)

**Comment by tobrun** [comment]
This issue will solve code completion of our internal resources for end developers when using the aar:
<img width="312" alt="screen shot 2015-09-25 at 12 22 36" src="https://cloud.githubusercontent.com/assets/2151639/10098257/4cbbb11c-6380-11e5-886a-64c01074f246.png">

**Comment by tobrun** [comment]
I have a working configuration!

I have hidden the resources shown in previous post:
<img width="580" alt="screen shot 2015-09-25 at 13 31 29" src="https://cloud.githubusercontent.com/assets/2151639/10099475/40086bfe-638a-11e5-8129-7de3fed5a5ea.png">




I exposed the style for attribution dialog:
<img width="350" alt="screen shot 2015-09-25 at 13 30 28" src="https://cloud.githubusercontent.com/assets/2151639/10099453/0efd68ca-638a-11e5-8ab4-3214e7484c01.png">

**Comment by ljbade** [comment]
@tobrun You going to commit it?

**Comment by ljbade** [comment]
Never mind, found the PR

**Comment by jfirebaugh** [comment]
Fixed in #2442.
