### ISSUE TITLE
Inflating MapView children using xml 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2224]
For the MapView class we are currently adding child views programmatically. I want to test if using a layout inflater is as fast/efficient. The general idea is that this is the preferred way of creating views on Android and this would reduce ui code in the MapView class.

**Comment by tobrun** [comment]
Some things I will measure:
 - [ ] Size AAR
 - [ ] Memory 
 - [ ] Execution time initialise method

**Comment by tobrun** [comment]
Data below is composed out of 10 runs:

###### Size AAR:
 - Master: 2,1 mb -> 2.104.897 bytes
 - Branch: 2,1 mb -> 2.105.278 bytes 

--> difference only 381 bytes, flagging this as irrelevant

###### Memory usage average:
- Master: 21.67 mb 
- Branch: 19.68 mb

###### Execution time initialise method average:
- Master: 41.7 ms
- Branch: 45.4 ms

##### Conclusion
It confirms what I initially thought:
 - less memory usage (less objects need to be created)
 - slower in startup time (need to parse xml files)

##### Personal opinion
I think the improvement in mb of memory is more important than slower startup time in ms.

What are you thoughts on this @incanus @bleege @ljbade?

**Comment by ljbade** [comment]
XML allows more control for end developers of how the map looks in their apps?

**Comment by tobrun** [comment]
Yes, they are able to override the resource file but they are obliged to use same view types and ids to make it work for them. 

Thinking more about this there other things end-developers can change that should not be changeable. This is where #2222 could resolve some issues but not all of them. I will create a new ticket explaining my findings.

**Comment by tobrun** [comment]
Picking this up again,
My initial idea that we need to limit overriding resources was incorrect.
I don't see any objections for adding this.

Currently only seeing the benefits of this:
 - lowering memory footprint at startup time.
 - moving ui code out the MapView class and into a layout xml file.

**Comment by bleege** [comment]
:+1:

**Comment by ljbade** [comment]
Now that we re-factored CompassView and UserLocationView into proper View classes this should be easier.

**Comment by ljbade** [comment]
Now that we re-factored CompassView and UserLocationView into proper View classes this should be easier.
