### ISSUE TITLE
condense JNI boilerplate

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2225]
Not critical right now (so leaving off of even the 0.2.0 Android milestone), but we should think about refactoring and condensing much of the setup & teardown in `jni.cpp` per https://github.com/mapbox/mapbox-gl-native/pull/2209#issuecomment-136782502. 

Here is but a small sample: 

https://github.com/mapbox/mapbox-gl-native/blob/244fe93f0e6610cd7d66e1f9fd08ca84cb0dd7b2/android/cpp/jni.cpp#L1816-L1860

**Comment by mb12** [comment]
@incanus Is it possible to investigate using <a href="http://www.swig.org">swig</a> to autogenerate bindings for java as well as javascript node.js? I used it a few years back  on a project to generate perl bindings and swig was a life saver.
