### ISSUE TITLE
update GeoJSON VT version

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2226]
We should wait until after the next [`ios-v2.1.0`](https://github.com/mapbox/mapbox-gl-native/milestones/ios-v2.1.0) release for this, but per https://github.com/mapbox/mapbox-gl-native/commit/244fe93f0e6610cd7d66e1f9fd08ca84cb0dd7b2#commitcomment-13003393, we have a ton of work by @kkaefer on the C++ GeoJSON VT port in https://github.com/mapbox/geojson-vt-cpp/compare/995ffc72c556da4b4880a6036fbcf7159fc5ecce...master that has never made its way into production code here in GL, nor back to the JS port source. 

/cc @mourner

**Comment by incanus** [comment]
We should hit this now as we are still running a GeoJSON VT in `master` that has [nine commits](https://github.com/mapbox/geojson-vt-cpp/tree/83bffbcc6ad75ff59c7640036567820c8932161b) instead of `master`'s 62. 

@kkaefer @jfirebaugh @mikemorris

**Comment by mikemorris** [comment]
Working on this in https://github.com/mapbox/mapbox-gl-native/pull/2584, but completely stumped dealing with mason-installed RapidJSON linker warnings in the iOS test suite.
