### ISSUE TITLE
Move asset loading to Java

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2232]
Using Android platforms [`AssetManager`](http://developer.android.com/reference/android/content/res/AssetManager.html)

Follows on from #823 so we can implement all of `FileSource` in Java. This allows us to drop the native libzip dependency.

**Comment by jfirebaugh** [comment]
Not seeing any compelling reason to change the implementation here at this point.

**Comment by kkaefer** [comment]
What we're looking for is https://developer.android.com/reference/android/content/res/AssetManager.html. There's also a JNI-API for this that allows us to do it directly from C++: https://developer.android.com/ndk/reference/group___asset.html
