### ISSUE TITLE
Not able to load custom style url's in Android

### ISSUE THREAD

**Issue by erf** [mapbox/mapbox-gl-native#2234]
I'm not able to load custom style url any more in Android. Example:
<pre>
mapView.setStyleUrl("http://mydomain.com/style.json");
</pre>

I just get a black screen and then it crashes.

I see the following in the log:
<pre>
9-02 12:57:43.184  31564-31737/? A/libc﹕ Fatal signal 11 (SIGSEGV), code 2, fault addr 0x47432b2b in tid 31737 (NativeMapView::)
</pre>

Tried it in commit 244fe93

**Comment by incanus** [comment]
@erf do you have any more info on the crash log?

**Comment by ljbade** [comment]
@erf Just tried the URL `https://raw.githubusercontent.com/mapbox/mapbox-gl-styles/master/styles/light-v8.json` and it loaded OK.

Where in your app do you call `setStyleUrl`? In case that triggers the bug.

Are you able to share the custom style URL?

Are you using a v8 style?

**Comment by erf** [comment]
I was using v7 style..

**Comment by erf** [comment]
Works with v8 !
