### ISSUE TITLE
consolidate headless testing scripts

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#2236]
We have three versions of the headless testing scripts, all implementing the same test harness logic:

* mapbox-gl-js test/render.test.js
* mapbox-gl-native test/headless/{headless.cpp,server.js}
* mapbox-gl-native platform/node/test/render.test.js

Instead, mapbox-gl-test-suite should export the following API:

```
/**
 * Run the test suite, making exceptions based on the `implementation` ("js" or "native"),
 * compute differences to expected values, and then call `callback` with the results. Caller
 * must supply a `render` function that does the actual rendering and passes the raw image
 * result on to the `render` function's callback. 
 * 
 * @param {string} implementation - `"js"` or `"native"`, used to deal with implementation-
 * specific exceptions.
 * @param {renderFn} render - a function that performs the rendering
 * @param {resultsCallback} callback - called with the results of the test suite run
 */
module.exports = function(implementation, render, callback) {
};

/**
 * @callback renderFn
 * @param {Object} style - style to render
 * @param {renderCallback} callback - callback to call with the results of rendering
 */

/**
 * @callback renderCallback
 * @param {?Error} error
 * @param {Buffer} [result] - raw image data
 */

/**
 * @callback resultsCallback
 * @param {Array<Object>} results - TODO: define format
 */
```

Both mapbox-gl-js and mapbox-gl-native will use this, passing an appropriate `implementation` and `render` function. mapbox-gl-native will do all headless testing using the node bindings.

Then:

* Remove headless tests from non-node rows of the mapbox-gl-native test matrix
* Remove test/headless/{headless.cpp,server.js}
* Remove test/suite/bin/{compare_images,server}.py

**Comment by mikemorris** [comment]
Got tripped up on some test failures when I changed the order of arguments to `HeadlessView` in https://github.com/mapbox/mapbox-gl-native/pull/2310 - are we still using `HeadlessView` in the C++ tests or should it be exclusively used in the node bindings?

**Comment by jfirebaugh** [comment]
Yes, I believe there are a couple of C++ tests that use `HeadlessView`.
