### ISSUE TITLE
JNI functions should check for null

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2243]
Before we pass into the native layer we should do some parameter validation such as `null` checks and throw an exception in Java.

**Comment by incanus** [comment]
Refs https://github.com/mapbox/mapbox-gl-native/issues/2225

**Comment by tobrun** [comment]
The following is added in on public API methods:

```java
    public Marker addMarker(@NonNull MarkerOptions markerOptions) {
        if (markerOptions == null) {
            Log.w(TAG, "markerOptions was null, so just returning null");
            return null;
        }
        ...
     }
```

That snippet will prevent from executing JNI functions with null,
also developers will be notified with the `@NonNull` is they would pass null references.

Closing this down as obsolete.
