### ISSUE TITLE
Add support for multipolygons and multipolylines

### ISSUE THREAD

**Issue by maciekish** [mapbox/mapbox-gl-native#2245]
Our search API sometimes returns cities as separate polygons and streets as separate polylines because these areas and streets are not always connected with each other. However they should still be displayed and treated like one object.

I added support for this in legacy MapBox https://github.com/mapbox/mapbox-ios-sdk-legacy/pull/663

Is there any chance we can get this in `gl` please?

cc @Zakay

**Comment by incanus** [comment]
Would something like https://github.com/mapbox/mapbox-gl-native/issues/1729 effectively cover this? We've targeted it previously just in terms of polygons, but the same concept could apply to polylines, though MapKit (which we are modeled after here) doesn't have that concept.

**Comment by maciekish** [comment]
@incanus Not entirely I'm afraid. While interior polygons would be useful it doesn't cover the entire use case. It was very easy to add this to legacy MapBox but i haven't hade a look at gl yet since I've never worked with c++ nor OpenGL.

**Comment by incanus** [comment]
Then maybe https://github.com/mapbox/mapbox-gl-native/issues/1708 would cover the use case?

**Comment by maciekish** [comment]
If that would support both polylines and polygons as well as interior polygons then yes!

**Comment by jfirebaugh** [comment]
Tracking fuller geometry support for annotations at #1729.
