### ISSUE TITLE
renderStill sometimes renders labels mid-fade

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#2264]
![image](https://cloud.githubusercontent.com/assets/98601/9695275/ceff1c1c-5314-11e5-82f3-2dca9055b199.png)

Label fading should be fully disabled in still rendering mode.

**Comment by mikemorris** [comment]
From chat with @brunoabinader, probably need to adjust something in [`Transform::startTransition`](https://github.com/mapbox/mapbox-gl-native/blob/c1d229280942778e43cce014f3c761db09d191d1/src/mbgl/map/transform.cpp#L362-L387)

> not sure, but we could have a check in TransformState::startTransition to go all the way to the end of the transition immediately if mode is still
> we could just call the callback for transitionFinishFn if I'm correct

**Comment by jfirebaugh** [comment]
Duplicate of #942.

**Comment by jfirebaugh** [comment]
This is still happening.
