### ISSUE TITLE
MGLAnnotationImage should be called MGLAnnotationView

### ISSUE THREAD

**Issue by mjmayank** [mapbox/mapbox-gl-native#2267]
This would allow it to stay consistent with it's equivalent class in MapKit (MKAnnotationView). Is there a reason the naming convention was changed in this case?

**Comment by incanus** [comment]
Yep, because try annotation views will come in https://github.com/mapbox/mapbox-gl-native/issues/1784. This is a way to _just_ store imagery efficiently as well as with a reuse identifier, for now. Then this API will get deprecated in future.
