### ISSUE TITLE
Update gradle plugin to 1.4.0

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2268]
Android Studio 1.4 was released in [Beta channel](http://tools.android.com/recent) and will soon be in Stable Channel. 
We should upgrade build.gradle files to reflect this:

>        classpath 'com.android.tools.build:gradle:1.4.0'

**Comment by ljbade** [comment]
I will hit this when my machine picks up studio 1.4

**Comment by ljbade** [comment]
1.4 is live, will merge after quick test

**Comment by ljbade** [comment]
Going to have to hold off, Gradle plugin v1.4.0 is still in beta:
https://bintray.com/android/android-tools/com.android.tools.build.gradle/view

Will wait for stable release.

**Comment by tobrun** [comment]
Obsolete due #3098
