### ISSUE TITLE
style version 8

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-native#2271]
After upgrading my style to version 8 to make it work with the mapbox-gl-js 0.10.0, symbols (text and sprite) in my style does not show up in mapbox-gl-native. Is there a issue to track the progress of making mapbox-gl-native support v8 as well? 

The documentation https://www.mapbox.com/mapbox-gl-style-spec/ refer to v8 as well.

Here are the Podspec entry I use. 
pod 'Mapbox-iOS-SDK', :podspec => 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/master/ios/Mapbox-iOS-SDK.podspec'

**Comment by friedbunny** [comment]
`master` has `v8` support and it's in the latest pre-release ([ios-v2.1.0-pre.2](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v2.1.0-pre.2)) if you're itching to try it out before our next public release.

**Comment by halset** [comment]
Thank you @friedbunny!
