### ISSUE TITLE
Custom user location image (ios)

### ISSUE THREAD

**Issue by kajensen** [mapbox/mapbox-gl-native#2272]
Hi, i'm seeing if anyone has an implementation for a custom user location annotation image. Its actually kind of funny/awesome- if you set a (custom subclassed) annotation on the exact userlocation coordinate with userlocation tracking heading enabled, it rotates, which is exactly what I want. But it still shows the user location annotation (blue dot), which is unfortunate.

I think it would be awesome if you could set the user location image just like another annotation via [mapView: imageForAnnotation:].

Anyways, i'm trying to do this myself but when I add the platform/ios files to an xcode project it won't compile as its missing numerous .h and .m files. I'm new to this, and I'm not really sure how to get started, so if anybody is willing to help i'd appreciate it.

**Comment by incanus** [comment]
Hi @kajensen. Proper support for this will be added in #1784, but in the meantime, what we are doing now on iOS is not an image but actually is drawn on the fly in Core Graphics in order to take advantage of some animations and the `tintColor` API. You want to customize the `MGLUserLocationAnnotationView` class, which right now isn't very direct nor supported, but is a way that you could hack this.

**Comment by 1ec5** [comment]
> I think it would be awesome if you could set the user location image just like another annotation via [mapView: imageForAnnotation:].

Filed #5037 for the preferred implementation, now that we support annotation views.

> Anyways, i'm trying to do this myself but when I add the platform/ios files to an xcode project it won't compile as its missing numerous .h and .m files. I'm new to this, and I'm not really sure how to get started, so if anybody is willing to help i'd appreciate it.

We overhauled the build system in #4641, simplifying the project structure considerably. Please have a look at [DEVELOPING.md](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md) for guidance.
