### ISSUE TITLE
Adjust InfoWindow triangle for edge of screen annotations

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2273]
If an annotation is near the edge of the screen so the InfoWindow gets pushed over to stay on the screen the triangle no longer aligns with the marker:
![image](https://cloud.githubusercontent.com/assets/1215089/9726111/d973bda4-5631-11e5-91df-8a2253c935da.png)

Somehow the triangle should be moved to stay in line with the marker.

**Comment by tobrun** [comment]
Been looking at [Raster-SDK](https://github.com/mapbox/mapbox-android-sdk/blob/26d8857786856e5bd933ef6ad28b1d359b2a342a/MapboxAndroidSDK/src/main/java/com/mapbox/mapboxsdk/overlay/Marker.java#L525) there we are panning the map to make it fit.

@incanus How is iOS handling this?

**Comment by tobrun** [comment]
Currently noticing that panning hides the InfoWindow, in Raster-SDK it doesn't. 
should this be fixed or is this a works-as-designed feature?

**Comment by ljbade** [comment]
Hmm I'm not sure why we hide on pan, it might have been a work around for the lag/jitter. @bleege @incanus know more about this

**Comment by friedbunny** [comment]
The InfoWindow/callout view should move with the map and stay within the viewport while accounting for margins/etc. Eventually we'll implement this on iOS, but so far we haven't.

See #1089 and #1784.

**Comment by tobrun** [comment]
Based on info given above, I wil add the same functionality as iOS. 
Will wait for general solution on the lag/jitter to update this on.

**Comment by bleege** [comment]
> The InfoWindow/callout view should move with the map and stay within the viewport while accounting for margins/etc.

Yep, @friedbunny is absolutely correct.  Let's mirror what iOS is doing.

**Comment by incanus** [comment]
To be clear, iOS is hiding the callout on any viewport change because we don't have a good system in the sub-project that we use for callouts (which are rather complex and MapKit-like) to reposition without re-displaying. So mirroring iOS behavior would _not_ track the map. 

I do think we should _not_ track the map on Android until we solve the sync problems with the user dot as described elsewhere. then we can move the info window with the map, too, which is more complex and requires re-layout when hitting the map edge, etc.

**Comment by bleege** [comment]
Yep, @incanus is right (as he always is) about the viewport change for things.  I spent some time looking at how iOS currently handles this and it's NOT by moving the viewport it's more sliding the InfoWindow's tip to the Marker where needed to make sure that the InfoWindow displays in it's entirety without moving the Map.  See screenshots below for examples of how this works.

We should get Android to mirror this as much as possible.  The primary goal / definition of success for now is to avoid having Markers and InfoWindows be "disconnected" as shown above ^^.

![photo oct 12 10 42 49 am](https://cloud.githubusercontent.com/assets/989928/10432182/3bb5407a-70cf-11e5-9ae2-0e7ab43edf82.png)
_Slightly Off Center_

![photo oct 12 10 42 28 am](https://cloud.githubusercontent.com/assets/989928/10432189/484195c8-70cf-11e5-82f8-83043752d16d.png)
_Pin On Right Side Of MapView_

![photo oct 12 10 42 38 am](https://cloud.githubusercontent.com/assets/989928/10432219/626dde8e-70cf-11e5-971d-6abcadfc72c5.png)
_Pin Onn Left Side Of MapView_

**Comment by ljbade** [comment]
@bleege Ah yeah so all that's really needed on Android is some logic about where we draw the `InfoWindowTip` class.

**Comment by tobrun** [comment]
@ljbade  Have it almost in place, will PR it tomorrow.

**Comment by ljbade** [comment]
Just found an additional bug in new Sirius to do with switching style with different sized markers.

**Comment by incanus** [comment]
I will add that we are getting this awesome layout logic for free on iOS with SMCalloutView, which is one of many reasons why we kept that from the raster SDK for our callout purposes.

**Comment by ljbade** [comment]
Captured a screenshot showing the bug when opening InfoWindow on Streets, then switching to Emerald:
![device-2015-10-13-164015](https://cloud.githubusercontent.com/assets/1215089/10446726/9fdab9b8-71c9-11e5-9315-3d6968b8dcf2.png)
![device-2015-10-13-164043](https://cloud.githubusercontent.com/assets/1215089/10446729/a453aeaa-71c9-11e5-8993-b96691ff4b2a.png)

**Comment by ljbade** [comment]
Also noticed the touch hit box for Emerald is too small. @bleege is this an already known issue?

**Comment by ljbade** [comment]
Bummer can't fix the marker size change bug until https://github.com/mapbox/mapbox-gl-native/issues/2263 is fixed. So I will make new issue.

**Comment by tobrun** [comment]
> Also noticed the touch hit box for Emerald is too small. @bleege is this an already known issue?
 
@ljbade: details are in #1504

**Comment by ljbade** [comment]
@tobrun Excellent.

**Comment by tobrun** [comment]
Normal                     |  Right                      | Left
:-------------------------:|:-------------------------:|:-------------------------:
![device-2015-10-13-134226](https://cloud.githubusercontent.com/assets/2151639/10453887/612b1dd4-71b0-11e5-97b5-7fe38da56e88.png)  |  ![device-2015-10-13-134211](https://cloud.githubusercontent.com/assets/2151639/10453892/7628af08-71b0-11e5-8b89-a97cbb639630.png) |![device-2015-10-13-134144](https://cloud.githubusercontent.com/assets/2151639/10453893/788ef70c-71b0-11e5-922c-f1c7cb7ccc33.png)

**Comment by tobrun** [comment]
On Android we have 2 types of info windows:
 - Default InfoWindow (shown above)
 - **Adapted InfoWindow provided by end developer  (InfoWindowAdapter)**

I did not implement the margin/repositioning fix for the latter, this would give unexpected results for end developers but I did fix the initial problem for this issue as seen in this screenshot:

Before           |  After
:-------------------------:|:-------------------------:
![device-2015-10-13-140221](https://cloud.githubusercontent.com/assets/2151639/10454204/42d7a0fc-71b3-11e5-93c8-b68323e75dcc.png) |  ![device-2015-10-13-135603](https://cloud.githubusercontent.com/assets/2151639/10454183/202ed930-71b3-11e5-9602-242b22345daa.png)

**Comment by bleege** [comment]
@tobrun This looks great!  The Default InfoWindow will be just fine for now.  :+1:

**Comment by bleege** [comment]
@tobrun I tried testing things out in #2601 to merge, but ran [into some issues](https://github.com/mapbox/mapbox-gl-native/pull/2601#issuecomment-147779639).  We're getting close though!
