### ISSUE TITLE
Zoom to rounded zoom levels for raster tiles

### ISSUE THREAD

**Issue by maciekish** [mapbox/mapbox-gl-native#2276]
Hi,
Is there any way you could perhaps add an option to force the map to zoom to the closest integer zoom level when double-tapping or two-finger-tapping please? As it is right now if you pinch to 12.342 and then double tap, it will zoom to 13.342 instead of 13.0. This would be most useful for raster tiles with labels, otherwise text is too hard to read.

**Comment by mdakram** [comment]
any update on this?

**Comment by mdakram** [comment]
Hi @tobrun is there any plan to implement this?

**Comment by tobrun** [comment]
This issue is currently not in the top tier to pick up, haven't seen many requests for it  and thus I don't see us picking this up in the near future. That said, feel free to run with it and contribute it 😉
