### ISSUE TITLE
Maintaining platform changelogs

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#2284]
I've been maintaining [`platform/node/CHANGELOG.md`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/node/CHANGELOG.md), but noticed that iOS releases are included in [`CHANGELOG.md`](https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md) - I think we should standardize on either maintaining separate changelogs for each platform or including all platforms in the root changelog. Don't have a strong preference here, just think we should pick something and stay consistent.

/cc @mapbox/gl

**Comment by 1ec5** [comment]
I’ve been sticking a running iOS changelog in [milestone descriptions](https://github.com/mapbox/mapbox-gl-native/milestones), but we should get in the habit of updating the actual changelog files as part of PRs.

**Comment by jfirebaugh** [comment]
Seems to me the natural way to go would be to use `CHANGELOG.md` for core library changes and `platform/*/CHANGELOG.md` for SDK releases.

**Comment by incanus** [comment]
:point_right: https://github.com/mapbox/mapbox-gl-native/issues/3068
