### ISSUE TITLE
change request semantics for node

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#2287]
Instead of calling a `respond` method on the request:

```
    request: function(req) {
        fs.readFile(path.join('base/path', req.url), function(err, data) {
            req.respond(err, { data: data });
        });
    },
```

It should be a normal callback:

```
    request: function(req, callback) {
        fs.readFile(path.join('base/path', req.url), function(err, data) {
            callback(err, { data: data });
        });
    },
```

cc @mikemorris

**Comment by mikemorris** [comment]
Ooh, yea I like this plan :+1:

**Comment by mikemorris** [comment]
Got this working on `v0.10.x`, tweaking for newer versions now.

`v8::FunctionTemplate::New` has a constructor that accepts a second argument accessible in the function through `info.Data()` https://groups.google.com/d/msg/v8-users/QRzyrw8BIfA/ZkQtizduSZ0J)
