### ISSUE TITLE
Rotation is laggy

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2290]
The performance of rotations seems to have gotten worse.

Rotating gesture is very laggy on my Sony Z3 and Samung S6 around Canberra.

Panning and double tap zoom is smooth. Two finger zoom also lags.

@incanus @bleege You find this?

**Comment by incanus** [comment]
Hmm, didn't find that. Can you bisect a commit to figure out where it came in?

**Comment by ljbade** [comment]
Doing some testing, this only happens when using touch gesture.

If you fling or use the rotate to north with compass button the animations are very smooth.

I notice on the Samsung S6 the drag gesture is more laggy than the fling animation.
