### ISSUE TITLE
Node v4.x support

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#2294]
Blocked on https://github.com/mapbox/node-pre-gyp/issues/173 currently.

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by mikemorris** [comment]
@ChALkeR We're on `nan@2.0.9`, the blocker for Node v4.x compatibility is a `node-gyp` bug.

**Comment by ChALkeR** [comment]
@mikemorris I am aware of that, the tracking list is not about nan, it's about Node.js 4.0.0 compatibility.
Also note that the version with nan 2.x is not yet packaged on npm.

**Comment by mikemorris** [comment]
Just waiting on https://github.com/mapbox/node-pre-gyp/issues/173 to be published in `node-pre-gyp@0.6.11` to get this working with Node.js v4.1.x.

**Comment by jfirebaugh** [comment]
Fixed in 9fdc36c1a1c91f1fb0db336c2b9b7c61ec94cb20.
