### ISSUE TITLE
Setting map position should cancel scroll

### ISSUE THREAD

**Issue by erf** [mapbox/mapbox-gl-native#2296]
Setting map position should cancel scrolling. There should perhaps be another way of canceling scrolling as well.

**Comment by ljbade** [comment]
I see related to https://github.com/mapbox/mapbox-gl-native/issues/1699

**Comment by ljbade** [comment]
I think this might also affect iOS as there is no `cancelTransitions` for setting coordinates?

**Comment by ljbade** [comment]
I made a PR which also calls `cancelTransitions` in the other `set` functions for position, direction and zoom level.

In https://github.com/mapbox/mapbox-gl-native/pull/2302

**Comment by ljbade** [comment]
Merged PR to `master`.

Awaiting @incanus @bleege eyeballs for release branch cherry pick.

**Comment by incanus** [comment]
Cherry-picked as d894bb7c107018b37a43921fa34c28efe4135d93.
