### ISSUE TITLE
with no background layer, unpainted parts of buffer should be transparent

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#2305]
We are seeing issues in the new Mapbox Studio where font previews and previews of the [empty style](https://github.com/mapbox/mapbox-gl-styles/blob/master/styles/empty-v8.json) produce a random background color.

mapbox-gl-native is probably not clearing the framebuffer contents if there is no background specified, so you get whatever that memory happens to contain at the time. Instead, this case should result in a transparent background.

**Comment by lucaswoj** [comment]
ref https://github.com/mapbox/app/issues/3329

**Comment by ljbade** [comment]
@jfirebaugh Ah yeah seems this has changed sometime. used to be cleared to transparent black each frame, but now if seems `glClear` is only called for solid colour backgrounds.

if there is no background, or a textured background the frame is never `glClear`

**Comment by ljbade** [comment]
Relevant source https://github.com/mapbox/mapbox-gl-native/blob/d9c7fdc5655d48a6e7c54016c0efd94710431430/src/mbgl/renderer/painter.cpp#L147-L155

Only place it is called https://github.com/mapbox/mapbox-gl-native/blob/d9c7fdc5655d48a6e7c54016c0efd94710431430/src/mbgl/renderer/painter.cpp#L215

**Comment by kkaefer** [comment]
I cannot reproduce this. The color is set to [transparent black](https://github.com/mapbox/mapbox-gl-native/blob/9ff66acf61c33c4b073ea44d0932807e9c7632be/src/mbgl/renderer/painter.hpp#L201) and cleared on every frame.

**Comment by kkaefer** [comment]
@jfirebaugh can you provide a way of reproducing this?

**Comment by mikemorris** [comment]
Hopefully https://github.com/mapbox/mapbox-gl-native/pull/2963 resolves this.
