### ISSUE TITLE
native PNG/JPEG encoding in map.render

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#2306]
- [ ] Add a `format` parameter to the options passed to `map.render` that accepts `raw`, `png`, `jpeg` and maybe `webp` values. This can be optional and default to `raw` to avoid a semver major bump.
- [ ] Possibly expose a `quality` parameter for 70/80/90 quality JPEGs or quantized PNGs.

Initial implementation with only `png` support started in https://github.com/mapbox/node-mapbox-gl-native/pull/150.

We've discussed using the image encoding functionality from [mapnik](https://github.com/mapnik/mapnik) or the standalone image library [libvips](https://github.com/jcupitt/libvips) to implement this, keeping the encoding in C++ for better performance (instead of passing the buffer to JavaScript and applying native encoding there through [node-mapnik](https://github.com/mapnik/node-mapnik) or [sharp](https://github.com/lovell/sharp)).

From @springmeyer:
> I think what we want is:
- Support for both `png`, `jpeg`, and perhaps also `webp` to start
- The ability for quantizing (aka crushing) png images to keep them small (resulting in palletized png)
- The best possible performance. Because image encoding can often take longer than rendering it is critical that image encoding is fast.

> The PNGs are already compressed - png is always compressed with zlib. I think the issue is that they are not being crushed to less than 256 colors because the mbgl png writer does not support this? Mapnik's hextree encoder is one implementation of this and we've not ported it from Mapnik to MBGL (like we did all the Mapnik image decoders).

> Pushing uncompressed pixels into a buffer means sending a lot of data across the language boundary from C++ (open gl) to JS and this can trigger a lot of garbage collection overhead in Node.js. Maybe this performance penalty will not matter, or maybe it will - I think we'll want to gut check this with profiling.

> In my experience the most optimal way to go from uncompressed buffer to compressed/encoded image buffer is to keep the ownership of pixels in C++. That means:
- creating a Node.js Image object in C++ that stores a pointer to the underlying uncompressed buffer
- creating an async Encoding function that takes ahold of the pointer to the uncompressed buffer, encodes it, and only when done returns the encoded buffer to JS.

**Comment by jfirebaugh** [comment]
Mapnik got a zero-copy image encoding API in 3.0.5 which we're using successfully downstream. Let's leave this responsibility there.
