### ISSUE TITLE
Cherry Pick To release-android

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2311]
Initial list of things that need to be cherry picked to `release-android` branch from `master`.  Please add to this ticket as things emerge.  We'll close this ticket when release is ready.

* [x] TextureView - https://github.com/mapbox/mapbox-gl-native/pull/2293
* [x] Custom InfoWindow - https://github.com/mapbox/mapbox-gl-native/commit/a6ef907d5e647dec9ecee44f14ee5fdf2d44af06
* [x] Attribution - https://github.com/mapbox/mapbox-gl-native/issues/2074
* [x] Set Map Position - https://github.com/mapbox/mapbox-gl-native/issues/2296#issuecomment-139429150

@mapbox/mobile

**Comment by bleege** [comment]
Release Branch: https://github.com/mapbox/mapbox-gl-native/commits/release-android-v0.1.0

Master Branch: https://github.com/mapbox/mapbox-gl-native/commits/master

**Comment by incanus** [comment]
Just got these, and others, in 17 cherry-picks. 

https://github.com/mapbox/mapbox-gl-native/compare/1f585c2a60eb28479d917638a4266ff0d2b2ba28...68778883851b3f0ea31294ccbddc858f061e62f2

**Comment by bleege** [comment]
:+1:
