### ISSUE TITLE
roll SNAPSHOT of android-v0.1.0-pre.1

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2312]
Following up on #2311, we should roll a SNAPSHOT based on the tag [`android-v0.1.0-pre.1`](https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v0.1.0-pre.1). 

/cc @bleege

**Comment by bleege** [comment]
SNAPSHOT 19 is now available as of 68778883851b3f0ea31294ccbddc858f061e62f2 on [`android-v0.1.0-pre.1`](https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v0.1.0-pre.1).
