### ISSUE TITLE
MGLMapView viewport methods should cancel animations

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#2313]
Per #2296, methods like `-[MGLMapView setCenterCoordinate:zoomLevel:]` should call `mbgl::Map::cancelTransitions()`, just like the gesture recognizers do.

/cc @incanus

**Comment by incanus** [comment]
This would probably help https://github.com/mapbox/mapbox-gl-native/issues/1975#issuecomment-138971829.

**Comment by incanus** [comment]
To be clear: the goal here is to avoid any sort of stale viewport changes to occur after applying _another_ viewport change.

**Comment by tomtaylor** [comment]
Just to confirm, while testing #2204, that this is an issue with `setCamera` too.

**Comment by tomtaylor** [comment]
@incanus do you have an idea of how much work this is? The last good version for me was pre2, which seems to also contain some crashing bugs under iOS 9. I'm blocked on releasing an iOS 9 compatible version of my app at the moment.

**Comment by 1ec5** [comment]
@adam-mapbox, #2321 has been merged, but it doesn’t seem to be testing this scenario: `-testSetCenterCancelsTransitions` seems to:

1. Go to DC instantaneously.
2. Go to the west with animation.
3. Halfway through the animation:
 1. Go back to DC instantaneously.
 2. Immediately assert that step (i) happened.

However, to adequately test whether setting a coordinate cancels other animations, we need to perform (ii) after the animation in (3) runs to completion. This test doesn’t account for the possibility that the animation continues moving to the west after (3) runs to completion.
