### ISSUE TITLE
How can I check if overlayBounds of MGLPolygon contains a certain CLLocationCoordinate2D? (Question)

### ISSUE THREAD

**Issue by mitchellporter** [mapbox/mapbox-gl-native#2314]
I'm using mapbox for an iOS app that I'm building and I'm loving it so far. There's just one problem though that I can't seem to solve.

I have an `MGLPolygon` that I am successfully creating and adding to the map. Whenever the user's location is updated, the `CLLocationManager` lets me access the most recent(current) coordinate which is just a `CLLocationCoordinate2D`.

The `overlayBounds` property of my `MGLPolygon` has two members, `ne` and `sw`, and those are both just `CLLocationCoordinate2D's`.

How can I check to see if the user's most recent location coordinate (`CLLocationCoordinate2D`) is contained within the `overlayBounds` of my `MGLPolygon`?

I really appreciate the help thanks.

**Comment by incanus** [comment]
Glad to hear the toolkits working out for you @mitchellporter! Would love to know what you're working on...

Your best bet here is probably using a combination of `-[MGLMapView convertCoordinate:ToPointToView:]` on the various coordinates and then checking intersection with CGRectContainsPoint`. We do this for the user dot [here](https://github.com/mapbox/mapbox-gl-native/blob/d9c7fdc5655d48a6e7c54016c0efd94710431430/platform/ios/MGLMapView.mm#L2554-L2569), for example.

**Comment by mitchellporter** [comment]
@incanus Thanks!

**Comment by aaasifrz9** [comment]
Hi @mitchellporter ,

I want the same thing but I am not able to check that a specific location lies in polygon or not.
Can you please help me, how can I check?

Thanks in advance.
