### ISSUE TITLE
didSelectAnnotation:(id<MGLAnnotation>)annotation issue

### ISSUE THREAD

**Issue by DKalachniuk** [mapbox/mapbox-gl-native#2315]
I have custom image for annotation. 
when I press on bottom part of image I receive callback in 
-(void)mapView:(MGLMapView *)mapView didSelectAnnotation:(id<MGLAnnotation>)annotation{

if I press at the top - NO callback. Any suggestions?

**Comment by friedbunny** [comment]
How large are is your custom image? The hitbox for annotations is currently hard-coded to 40x60, which is a known limitation that we're working to fix in #1504.

**Comment by DKalachniuk** [comment]
it is 100x120 
so currently I need to resize it to 40x60 max. Am I right?

**Comment by friedbunny** [comment]
>so currently I need to resize it to 40x60 max. Am I right?

Yes, if you need the entire annotation to be tappable the `@1x` image should be 40x60.

If you wanted to [compile your own MBGL](https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md) and only needed a single, larger-sized annotation image, [here](https://github.com/mapbox/mapbox-gl-native/blob/d9c7fdc5655d48a6e7c54016c0efd94710431430/platform/ios/MGLMapView.mm#L1114-L1116) is where you would edit the hitbox size.
