### ISSUE TITLE
Add Espresso UI testing

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#2317]
As discussed with @bleege we're gonna start working on adding Espresso UI testing to the [SDK Test App](https://github.com/mapbox/mapbox-gl-native/tree/master/android/java/MapboxGLAndroidSDKTestApp). This will let us simulate user interactions on the TestApp UI to test the SDK and minimize regressions.

Some advantages of Espresso:
* Supported by Google as part of the Android Testing Support Library (JUnit 4-compatible).
* Supported by Android Studio (you can also run the tests from the command line).
* Supported by AWS Device Farm which will give us access to a [large list](https://aws.amazon.com/device-farm/device-list/) of devices.
* Broad API compatibility: Android 2.2 (API level 8) or higher.

**Comment by zugaldia** [comment]
Work is on this branch: https://github.com/zugaldia/mapbox-gl-native/tree/2317-espresso

**Comment by zugaldia** [comment]
Basic Espresso tests are now set up. Dependencies are included in the Gradle file, a simple `testSanity()` method passes both locally and on AWD Device Farm. Documentation is available in the root folder of the test app.

**Comment by zugaldia** [comment]
Now that basic testing is up and running, it's now time to write some tests. I'll explore as well test coverage and screenshots options.

**Comment by bleege** [comment]
:+1:

**Comment by zugaldia** [comment]
We now have 25+ Espresso tests working both locally and on AWS. They have a new screenshot utility to be able to keep post-test images for all or certain tests.

I also had time to add pure JUnit tests to target POJO (like some `geometry` classes) or any other object without Android dependencies. These tests run directly on the JVM and are considerably faster than Espresso to run. README is now updated with these new tests too.

**Comment by zugaldia** [comment]
Screenshots were failing on the actual map because `SurfaceView` needs extra care to be captured. The code now handles that: https://github.com/zugaldia/mapbox-gl-native/blob/2317-espresso/android/java/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxgl/testapp/utils/ScreenshotUtil.java#L52

Also, we now have tests for the second activity.

**Comment by bleege** [comment]
Merged as of #2324 .
