### ISSUE TITLE
Please add delegate method for tapping callout

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#2325]
Please consider adding a delegate method for tapping the callout itself. There is already delegate method for tapping the accessory controls, but not the callout itself.

Suggested signature:
```
- (void)mapView:(MGLMapView *)mapView annotationTapped:(id <MGLAnnotation>)annotation;
```

**Comment by maciekish** [comment]
See #2279

**Comment by picciano** [comment]
Thanks!
