### ISSUE TITLE
Can't find sprite named 'com.mapbox.sprites.USTATION'

### ISSUE THREAD

**Issue by maciekish** [mapbox/mapbox-gl-native#2326]
Hi,
I'm returning `UIImages` to MapBox using the following method:

    [MGLAnnotationImage annotationImageWithImage:[HITLocation imageForPOIType:location.poiType] reuseIdentifier:location.firstPOIString];

This works initially and displays subway entrances on the map. When i enable the real estate map which draws multiple polygons on the map the subway entrances disappear and the console log is spammed with the following message:

    [INFO] {Worker}[Sprite]: Can't find sprite named 'com.mapbox.sprites.USTATION'

Is this a bug or am i doing it wrong? I'm currently at 8f37502c719feb151e01cb31d89c2effaf1b91ad.

**Comment by friedbunny** [comment]
> I'm returning UIImages to MapBox using the following method:

Are you using the reuse identifier or returning a new `UIImage` for each annotation? If the latter, [here is the recommended flow](https://www.mapbox.com/ios-sdk/examples/marker-image/) which checks if the resource can be reused.

> When i enable the real estate map which draws multiple polygons on the map

Is this a different style?

**Comment by maciekish** [comment]
I was returning a new UIImage for each annotation but i just changed it to leverage the reuse mechanism MapBox is offering. I still get the error message and the annotations still disappear though.

The real estate "map" is just a bunch of shape annotations, we don't change the style.

Here is what happens: http://s.swic.name/d7M6

**Comment by kristfal** [comment]
@friedbunny: we're seeing this issue ios-v2.1.2 both when following the reuse flow and when setting a new ```UIImage``` for each annotation.

Annotations load correctly on initial launch of the app, but if the app is closed and reopened, all loaded annotations disappear. If I pan to a new area with a new annotation not loaded during the previous launch, this new annotation will show – only to disappear on the next app launch.

**Comment by friedbunny** [comment]
I wonder if this is a regression from #2289, @incanus?

**Comment by robipresotto** [comment]
+1

**Comment by incanus** [comment]
Changing the style as you do in your video sounds like it is actually triggering https://github.com/mapbox/mapbox-gl-native/issues/1488, a known issue.

**Comment by maciekish** [comment]
I forgot that we switch to satellite mode which is a different style, sorry!
