### ISSUE TITLE
Crash with slow internet connection

### ISSUE THREAD

**Issue by iCyberon** [mapbox/mapbox-gl-native#2328]
I'm having an issue with low internet connection. I believe it should not crash, instead notify using delegate method.
```libc++abi.dylib: terminating with uncaught exception of type mbgl::util::SpriteLoadingException: Failed to load [https://www.mapbox.com/mapbox-gl-styles/sprites/mapbox-streets@2x.json]: The request timed out.```

Mapbox GL: 2.1.0,  iOS version: 9 GM,  Xcode 7 GM

**Comment by kelleyduran** [comment]
libc++abi.dylib: terminating with uncaught exception of type mbgl::util::SpriteLoadingException: Failed to load [https://www.mapbox.com/mapbox-gl-styles/sprites/dark@2x.json]: The request timed out.  Mapbox SDK version iOS 2.1.2 

any tips on how to prevent this from crashing the app?

**Comment by iCyberon** [comment]
@kelleyduran switch to http://developer.skobbler.com Looks like it's enough stable and doesn't crash with slow internet connections.

**Comment by ljbade** [comment]
@1ec5 Is this possible to fix? Loading a sprite should really return a loading failed event as in https://github.com/mapbox/mapbox-gl-native/issues/2775 and #2762

**Comment by 1ec5** [comment]
These look like v7 sprite URLs. Mapbox iOS SDK 2.1.0 requires v8 styles, which (if I’m not mistaken) should be getting the sprites from this URL instead: `https://api.mapbox.com/styles/v1/mapbox/streets-v8/sprite@2x.json?access_token=…`.

**Comment by 1ec5** [comment]
In short, it’s sounding like a slow Internet connection might be a red herring. Where is the old URL coming from? A cached style, perhaps?

/cc @kkaefer @jfirebaugh

**Comment by jfirebaugh** [comment]
This should be fixed in 3.2.0-beta.2 and later.
