### ISSUE TITLE
Constraining the map to a predefined geographic region

### ISSUE THREAD

**Issue by maciekish** [mapbox/mapbox-gl-native#2329]
Hi,
Our search service only covers Sweden, and we want to prevent the map from being panned outside of Sweden. This was possible in the old `MapBox`. Are there any plans to add this to `-gl`?

**Comment by maciekish** [comment]
I don't like waiting so i went ahead and did i myself #2341

**Comment by friedbunny** [comment]
Fixed in #5584.
