### ISSUE TITLE
Write and use RAII wrappers for all GL resources

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#2337]
Anything that uses `glGen*` should use a RAII wrapper that takes care of the corresponding `glDelete*`.

cc @brunoabinader

**Comment by brunoabinader** [comment]
I've started digging on this and it seems we already started doing so in `TexturePool` and `GLObjectStore`, however we probably need to implement a destructor for both classes that cleans all remaining textures up (something like this: https://gist.github.com/brunoabinader/57d813f3a69fb10871fd ).
