### ISSUE TITLE
GlyphAtlas leaks textures

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#2338]
[This texture](https://github.com/mapbox/mapbox-gl-native/blob/58b93553c10b77eedd573104b56d63916c635cbb/src/mbgl/geometry/glyph_atlas.cpp#L186-186) is never released.

`GlyphAtlas` needs a destructor that does what `LineAtlas` and `SpriteAtlas` do:

```
    if (texture) {
        mbgl::util::ThreadContext::getGLObjectStore()->abandonTexture(texture);
        texture = 0;
    }
```

cc @lucaswoj @mikemorris

**Comment by mikemorris** [comment]
Nice find! :clap:
