### ISSUE TITLE
iOS test failure:   testCenterSet, The step timed out after 10.00 seconds: Application is ignoring interaction events

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#2343]
This is causing frequent build failures, e.g. https://travis-ci.org/mapbox/mapbox-gl-native/jobs/80549743

If we don't have any leads on fixing this, let's disable the test.

cc @incanus @1ec5 @friedbunny

**Comment by friedbunny** [comment]
This will be #2321, added yesterday by @adam-mapbox.

**Comment by jfirebaugh** [comment]
@friedbunny It looks like a different test to me:

Failing: https://github.com/mapbox/mapbox-gl-native/blob/620e554f677d05edd0a588b56f343435516c05a8/test/ios/MapViewTests.m#L297
Added by @adam-mapbox: https://github.com/mapbox/mapbox-gl-native/blob/620e554f677d05edd0a588b56f343435516c05a8/test/ios/MapViewTests.m#L223

**Comment by friedbunny** [comment]
@jfirebaugh You're right. These Travis test failures are mutating, I had't seen `testCenterSet` fail until the last couple days.

**Comment by jfirebaugh** [comment]
Test has been disabled on CI.
