### ISSUE TITLE
Android PNG/JPEG reader

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2354]
From #2037 we should implement `PNGReader` and `JPEGReader` for Android using Java framework.

Allows us to drop `libpng` and `libjpeg` dependency.

**Comment by ljbade** [comment]
We want to use [BitmapFactory](http://developer.android.com/reference/android/graphics/BitmapFactory.html) and [BitmapRegionDecoder](http://developer.android.com/reference/android/graphics/BitmapRegionDecoder.html)

**Comment by ljbade** [comment]
Working on it in https://github.com/mapbox/mapbox-gl-native/tree/2354-android-image

**Comment by incanus** [comment]
We need to ship 0.1.0 first before working on new functionality / 0.2.0 :point_right: https://github.com/mapbox/mapbox-gl-native/milestones/android-v0.1.0

**Comment by jfirebaugh** [comment]
Fixed in #7828.
