### ISSUE TITLE
Android Unicode handling

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2355]
From #2037 we should implement Unicode `uppercase` and `lowercase` for Android using Java framework.

Allows us to drop `nunicode` dependency.

**Comment by mikemorris** [comment]
Refs https://github.com/mapbox/mapbox-gl-native/issues/309

**Comment by kkaefer** [comment]
Android collator is added in https://github.com/mapbox/mapbox-gl-native/issues/2355, which could make this a lot easier to do.

**Comment by tobrun** [comment]
PR in https://github.com/mapbox/mapbox-gl-native/pull/12497 is leveraging `java/lang/String#toUpperCase` and `java/lang/String#toLowerCase`.

**Comment by tobrun** [comment]
PR above also integrated collator support on the java side. nunicode was removed as result. Closing.
