### ISSUE TITLE
InfoWindow customization in Android

### ISSUE THREAD

**Issue by erf** [mapbox/mapbox-gl-native#2362]
Is there a way to customize the info window? 

Should there be a onMarkerClick event so you could add your own popup?

I'm on the 'release-android-v0.1.0' branch

**Comment by ljbade** [comment]
I think this is planned.

@bleege Is that right?

**Comment by bleege** [comment]
Yep, our long term goal is to [mirror the Raster SDK support](https://github.com/mapbox/mapbox-android-sdk/blob/fe4f3696ea6f9e36da3cd8aee91dd8d0f1f259df/MapboxAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/android/testapp/CustomMarkerTestFragment.java) for this.  So far what we've already backed in can be found [in the TestApp](https://github.com/mapbox/mapbox-gl-native/blob/1d565a515953432ef9dc79fadaf62e3217c42920/android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MainActivity.java#L403-L416)

**Comment by tobrun** [comment]
I like the builder pattern on MarkerOptions, we could improve this to allow setting the content programatically. Eg. AlertDialog can create a standard dialog with title/message, but also allows to set the content through setView().

I also like the idea of adapter support for Markers but maybe this is going a bridge too far.

**Comment by tobrun** [comment]
I have been looking at Google Maps and see how they are implementing this.

For parity I created:
 -#2450 
 -#2447 
 -#2448 
 -#2451 

@erf if #2451 lands you will have the ability to customise InfoWindow views

**Comment by ljbade** [comment]
#2451 landed
