### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by djensenius** [mapbox/mapbox-gl-native#2363]
tvOS does not have MapKit, and would love to have MapBox as an alternative.

**Comment by friedbunny** [comment]
tvOS seems rather fun and Mapbox does run on it, but time and device limitations may prevent us from doing much more than non-interactive maps (in the short-to-midterm).

Interested parties should see @webventil's fork (https://github.com/webventil/mapbox-gl-native/commits/tvOS), which adds a build target. There's been some implementation discussion in #2340, as well.
