### ISSUE TITLE
avoid recreating Android map view upon device rotation

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2364]
Thinking up the chain from #2295 (which still needs to be fixed), if you look at, say, Google Maps, the map view _does not appear to be_ recreated upon device rotation. It may be that a new activity is created, then revealed, and/or the map view is moved between them, but something non-trivial is going on. 

Even solving #2295, having to reload all the tiles, even from cache, is a distracting delay. We should look into ways to make this better. 

/cc @bleege @ljbade

**Comment by incanus** [comment]
Also, this is beyond the level of the `MapView` and may require app coordinate, but we could at least provide a best practice example by doing so.

**Comment by incanus** [comment]
https://developer.android.com/guide/topics/resources/runtime-changes.html#RetainingAnObject

This may be what @bleege was referring to in https://github.com/mapbox/mapbox-gl-native/issues/2295#issuecomment-141100428. 

This seems to be done at the `Fragment` design level. 

> When the Android system shuts down your activity due to a configuration change, 

The system seems to be able to detect this sort of pending `Activity` destroy and recreate.

**Comment by incanus** [comment]
Refs https://github.com/mapbox/mapbox-gl-native/issues/911#issuecomment-75549591

**Comment by incanus** [comment]
Skipping the `Fragment` route, I also tried the https://developer.android.com/guide/topics/resources/runtime-changes.html#HandlingTheChange

```diff
diff --git a/android/java/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml b/android/java/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
index f91c57e..56eb0a5 100644
--- a/android/java/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
+++ b/android/java/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
@@ -11,7 +11,8 @@
         android:supportsRtl="true">
         <activity
             android:name="com.mapbox.mapboxgl.testapp.MainActivity"
-            android:label="@string/app_name">
+            android:label="@string/app_name"
+            android:configChanges="orientation|screenSize">
             <intent-filter>
                 <action android:name="android.intent.action.MAIN" />
                 <category android:name="android.intent.category.LAUNCHER" />
diff --git a/android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MainActivity.java b/android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MainActivity.java
index eb5d891..b1cf8c3 100644
--- a/android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MainActivity.java
+++ b/android/java/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxgl/testapp/MainActivity.java
@@ -3,6 +3,7 @@ package com.mapbox.mapboxgl.testapp;
 import android.Manifest;
 import android.content.Intent;
 import android.content.pm.PackageManager;
+import android.content.res.Configuration;
 import android.graphics.Color;
 import android.graphics.PointF;
 import android.location.Location;
@@ -218,6 +219,11 @@ public class MainActivity extends AppCompatActivity {
         outState.putInt(STATE_SELECTED_STYLE, mSelectedStyle);
     }
 
+    public void onConfigurationChanged(Configuration newConfig) {
+        super.onConfigurationChanged(newConfig);
+        Log.d(TAG, "onConfigurationChanged");
+    }
+
     // Called when the system is running low on memory
     @Override
     public void onLowMemory() {
```

This behaves much like Google Maps, as well as sidesteps the crash problems in #2295.

**Comment by incanus** [comment]
Unraveling https://github.com/mapbox/mapbox-gl-native/issues/2364#issuecomment-141535682 though, @ljbade has the valid point that as a view, we don't have control over the implementor's activity handling of such configuration changes. It's nice to know a bit more about the problem, though.

**Comment by incanus** [comment]
Going back to the `Fragment` route, this seems the most promising. It's also what a [Google Maps sample project](https://developers.google.com/maps/documentation/android-api/start) does, and it this looks pretty good when rotating the device.

**Comment by incanus** [comment]
Related to the fragment approach, one note in the docs: 

> While you can store any object, you should never pass an object that is tied to the `Activity`, such as a `Drawable`, an `Adapter`, a `View` or any other object that's associated with a `Context`. If you do, it will leak all the views and resources of the original activity instance.

It seems we would want to pass our `MapView`, so this is likely also a no-go. 

It then becomes the question of what map views such as `GoogleMap` do to avoid this activity recycling, as sample apps don't require the manifest override of configuration change handling, nor do they use the `Fragment` retain approach, yet still device rotations don't seem to recreate the map. Private API?

**Comment by ljbade** [comment]
@incanus Wait you say `GoogleMaps` can rotate fine even after removing rotate config handling stuff?

**Comment by ljbade** [comment]
Like as in no visible reload?
Do they keep the map data/tiles in memory between changes?

**Comment by incanus** [comment]
There is no `GoogleMaps` rotate config handling stuff. You just use their sample activity, which is a subclass of `FragmentActivity`, and don't do anything related to config handling in your manifest for the activity.

**Comment by incanus** [comment]
> Do they keep the map data/tiles in memory between changes?

Very likely, but it doesn't seem possible for third-parties to do this outside of the retainable `Fragment` business, which isn't designed for `View` retaining.

**Comment by incanus** [comment]
I mean, maybe you could somehow keep the framebuffer contents or something and pass _those_, but it seems awful heavy. 

Regardless, I'm going to jump off of this now as an `0.2.0` task for better rotation behavior. We still need to fix #2295 for `0.1.0` for general stability, not only device rotations.

**Comment by bleege** [comment]
I'm not sure "avoid recreating Android map view upon device rotation" is realistic as this is how Android works.  [Activities](http://developer.android.com/reference/android/app/Activity.html#ActivityLifecycle) and [Fragments](http://developer.android.com/reference/android/app/Fragment.html#Lifecycle) share a similar lifecycle process that is wired into how Android operates.  Limiting the ability of MapViews to rotate is a non starter as apps need to be able to do that / developers _expect this_.

The 2 primary strategies for working with this are 1) saving and recreating data via the Bundle mechanism in the lifecyle and 2) stateless controllers (using ApplicationContext or static classes to maintain a reference and therefore keeping it from being garbage collected).  It looks like [HTTPContext has gone down the static route](https://github.com/mapbox/mapbox-gl-native/blob/0f80fb9103a3e014f82c7d4990b401706a0430fd/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/http/HTTPContext.java#L33-L39) on the Java side (which I think is the way to handle this case), the question is whether or not the C++ side is working in concert with it.

**Comment by ljbade** [comment]
@bleege Yeah I keep static copy of HTTPContext to stop it getting GC. This was to keep OkHTTP around to avoid crashes...

@bleege @incanus If you look at the Google Mas API, specifically the [`MapView.getMapsAsync()`](https://developers.google.com/android/reference/com/google/android/gms/maps/MapView.html#getMapAsync%28com.google.android.gms.maps.OnMapReadyCallback%29)

What I suspect is happening here is that `GoogleMaps` is a static object that stays in memory between activity destruction/recreation and that MapView very quickly hooks back into it. Thus all tiles and data is still in memory.

It might be possible to restructure our API to use a similar pattern. Unknown is what changes this requires in the core C++ layer since our other platforms to not work this way.

**Comment by bleege** [comment]
@ljbade Cool.  Thanks for confirming and the R&D on what Google is up to.

> It might be possible to restructure our API to use a similar pattern.

Exactly.  Let's take a crack at this by [using both state tracking strategies](https://github.com/mapbox/mapbox-gl-native/issues/2364#issuecomment-141837662).  Let's keep HTTPContext in singleton mode and then see if we can make use of [ApplicationContext](http://developer.android.com/reference/android/content/ContextWrapper.html#getApplicationContext%28%29) as the "application permanent" object that we can hang off of to keep the object reference alive between Activity / Fragment creation / destruction / recreation efforts.

**Comment by incanus** [comment]
>  Let's take a crack at this

Post-`0.1.0` ;-)

**Comment by bleege** [comment]
> Post-0.1.0

Normally I'd agree but I think this is the same issue as what's plaguing #2295.

**Comment by incanus** [comment]
>  this is the same issue as what's plaguing #2295 

I think this is just _a cause_ of the conditions for #2295, but you can replicate similarly by creating a map activity that is destroyed  before HTTP requests  comes back, even without rotating the device. 

That is, rotating is the easiest way to replicate the crash, but is not the cause of it.

**Comment by tobrun** [comment]
Jumping in the conversation and wanted to clarify some things mentioned in this post:

#### Google Maps Application 

>  if you look at Google Maps, the map view does not appear to be recreated upon device rotation.

I'm pretty sure that Google Maps application is using `onConfigChanges` and no fragments
 - by the way the ui behaves while rotating device
 - by the way they support activity transitions

#### Google Maps SDK 

>  Wait you say GoogleMaps can rotate fine even after removing rotate config handling stuff?

No, you can see the map being recreated if you don't add `onConfigChanges` while using their SDK

#### Retained fragments

>  use the Fragment retain approach

If you call `setRetainInstance(true)` in `onCreate` of a Fragment, the fragment will not be recreated if the hosting Activity is recreated. Recreating in this context means retaining state and not retaining views. The fragment view hierarchy will always be recreated.

This results in following lifecycle pattern:
 - `onCreate` (only called once!)
 - `onCreateView`(multiple times possible)
 - .... 
 - `onDestroyView` (multiple times possible)
 - `onDestroy` (only called once!)

**Comment by ljbade** [comment]
@tobrun If we implement a refactor to use something like `GoogleMaps` object we could implement retained fragments. We can even use one of TextureView's features to keep the last rendered frame for immediate display.

**Comment by tobrun** [comment]
> We can even use one of TextureView's features to keep the last rendered frame for immediate display.
That would be awesome! super excited about that feature

**Comment by tobrun** [comment]
As mentioned in https://github.com/mapbox/mapbox-gl-native/issues/2364#issuecomment-150168620, a end-developer can use `onConfigChanges` to do this. This is not something we can manage at SDK level.
