### ISSUE TITLE
Updating Android Install Instructions

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2369]
Update INSTALL.md to avoid using homebrew and instead focus on:

* [x] installing the full Java SDK (aka JDK) from Oracle (latest from Oracle, currently JDK 8)
* [x] installing Android Studio from Google
* [x] install the Android SDK using Android Studio (ideally the "Standalone Option" and not the new internal GUI).

**Comment by jfirebaugh** [comment]
I definitely feel more comfortable installing things via homebrew than using manual downloads and click through installers. Is there a specific reason to avoid homebrew in this case?

**Comment by adam-mapbox** [comment]
Just as an FYI, I never did get the emulator path to work on my machine.  In general, I think we should advise people strongly that finding an actual Android device is the best path to joy and satisfaction.  I've never had much luck with the emulator, and this recent experience only cements that.  Conversely, getting it working on a device was almost trivial.

**Comment by bleege** [comment]
@jfirebaugh Normally I'd agree with you about preferring to use homebrew instead of manual downloads and installs.  That said in this case there's issues with Homebrew not installing Java at all.  Based on [the current instructions given](https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md#build-os-x-host), it should be possible to install Java using `brew cask install java` but that doesn't work at all.  When using `brew install java` no formulas are found.  Please see screenshot below:

![screen shot 2015-09-21 at 2 27 17 pm](https://cloud.githubusercontent.com/assets/989928/10002488/07669728-606d-11e5-8817-fe54ad98dc28.png)

As for Android Studio and the Android SDK in general, Google has since added the ability to install and update both directly to Android Studio.  This makes it easier to stay up to date for both Android Studio and Android SDK as well as have a more widely consistent place for the Android SDK to be located on the filesystem.  By default Android Studio wants to act as the Android SDK manager for developers (ie, initially asks you to install the Android SDK) and doesn't know to look for the Android SDK installed elsewhere.  This forces the developer to 1) know that they've already install Android SDK, 2) the exact path to it, and 3) be able to update the Android Studio preferences to connect Android Studio to the locally installed Android SDK.  This makes it easier to debug issues that @adam-mapbox ran into last week as he had both the Android SDK installed via Homebrew and via Android Studio.

**Comment by jfirebaugh** [comment]
The Java instructions might just be incomplete / out of date.

```
brew tap caskroom/cask
brew install brew-cask
brew cask install java
```

For the Android Studio / SDK issues, are you suggesting that Android Studio acting as the Android SDK manager is incompatible with a homebrew install?

**Comment by tobrun** [comment]
just verified and you can open the project with 
- Open an existing Android Studio Project

instead of using 
- Import project...

**Comment by ljbade** [comment]
@tobrun Interesting that must be a new feature. Never used to work way back.

**Comment by bleege** [comment]
While updating the OS X docs this afternoon, I experimented with the homebrew install commands.  It turns out that homebrew gets Java from Oracle and Android Studio directly from Google.  Once they're downloaded they'll go through the standard install process as defined by Oracle and Google on OS X so that should keep software in more traditional known file system locations rather than getting buried in homebrew's `/usr/local/Cellar`.  Installing the Android SDK via Android Studio's install process should complete things and have the system setup with pretty traditional locations.

<img width="1172" alt="screen shot 2015-11-09 at 3 57 08 pm" src="https://cloud.githubusercontent.com/assets/989928/11050074/8198176c-8708-11e5-993c-b203ec17c698.png">
