### ISSUE TITLE
BoundingBox using wrong latitude/longitudes

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2374]
While implementing #1948, I noticed strange results in my testcases.
Looking into this, I'm thinking that BoundingBox is using incorrect latitudes/longitudes.

For example take following BoundingBox:

<img width="407" alt="screen shot 2015-09-21 at 11 51 08" src="https://cloud.githubusercontent.com/assets/2151639/9989231/144ab336-6057-11e5-8eb4-eda939187706.png">

Using current implementation the 4 arg constructor would be:
>  BoundingBox(10,5,0,5) 

and using the 2 arg constructor:
> BoundingBox( {20,10} , {0,0} )  
-> this will call the 4 arg as BoundingBox(20,10,0,0) 

Which gives us a different BoundingBox

##### Reason
We are currently using:
 > mLatNorth,  mLonEast, mLatSouth, mLonWest

But I think this should be:
 > mLonNorth, mLatEast,  mLonSouth, mLatWest

**Comment by ljbade** [comment]
Good catch!

**Comment by tobrun** [comment]
Will add supporting testcases and change the implementation

**Comment by tobrun** [comment]
While working on this, I'm noticing that calling intersect always returns a [new BoundingBox](https://github.com/mapbox/mapbox-gl-native/blob/1d565a515953432ef9dc79fadaf62e3217c42920/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/geometry/BoundingBox.java#L216). 
In case two rectangles don't intersect we should return null or throw an exception.

**Comment by ljbade** [comment]
@tobrun I'd say we should return null.
