### ISSUE TITLE
Programatically setting the pitch to 0 via the camera also moves the map

### ISSUE THREAD

**Issue by maciekish** [mapbox/mapbox-gl-native#2375]
If i run the following code in your test app (via `make iproj`) and the pitch isn't already 0, it will jump to some arbitrary coordinate.

    [self.mapView setCamera:[MGLMapCamera cameraLookingAtCenterCoordinate:self.mapView.centerCoordinate fromDistance:self.mapView.camera.altitude pitch:0 heading:0] animated:NO];

As you can see I'm reusing the current centerCoordinate and altitude. All i want is to set the pitch to 0. Am i doing it wrong or is this a bug?

If you just expose the `mbgl::Map->setPitch` function it works perfectly fine.

    - (void)setPitch:(double)pitch
    {
        _mbglMap->setPitch(pitch);
    }
cc @zakay

**Comment by 1ec5** [comment]
Can you provide a coordinate pair and pitch to test with? I do see that the map effectively zooms out when starting out tilted, due to #2139 and the use of “fit bounds” when applying a camera, but the center coordinate stays fixed.

**Comment by maciekish** [comment]
It appears like this was caused by my new `userConstrain` function. I updated my PR with a bugfix #2341. I was incorrectly assuming that `Cc` and `Bc` in `TransformState` always correspond to the current zoom level, but it appears like they sometimes change before `constrain` and `userConstrain` are called which produced incorrect `x_` and `y_`.
