### ISSUE TITLE
Drifting should send -mapView:regionDidChangeAnimated: with animated = YES

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#2379]
When drift-panning (or drift-pinching etc.), MGLMapViewDelegate should receive the following messages, for consistency with MapKit (which by the way lacks an “is changing” delegate method):

```
-mapView:regionWillChangeAnimated:, animated = NO
-mapViewRegionIsChanging:
-mapViewRegionIsChanging:
-mapViewRegionIsChanging:
…
-mapView:regionDidChangeAnimated:, animated = YES
```

Instead, the final `-mapView:regionDidChangeAnimated:`, has `animated = NO`.

/cc @jfirebaugh @incanus

**Comment by 1ec5** [comment]
`-[MGLMapView notifyMapChange:]` currently prefills `regionChangeDelegateQueue` with a `didChangeAnimated` operation at the time the `regionWillChangeAnimated` operation is queued, ensuring that the two calls have the same value for `animated`. But that’s incorrect. Whenever a gesture recognizer initiates a drift animation, it should cancel the prefilled `didChangeAnimated` operation and create a new one with `YES` for `animated`.

**Comment by incanus** [comment]
Is that how MapKit works? In past I've thought of "animated" as meaning "programmatically-induced"; that may be incorrect though.

**Comment by 1ec5** [comment]
I stand corrected: MapKit reports a non-animated change at the end of a drift. It does report an animated change for a double-tap, and so do we. So we’re good here.
