### ISSUE TITLE
add Settings.bundle to distribution? 

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2380]
Should we add our [settings bundle](https://www.mapbox.com/guides/first-steps-ios-sdk/#settings) to the binary and CocoaPods distributions to ease installation for folks who need it? 

/cc @friedbunny @1ec5

**Comment by 1ec5** [comment]
Yes, let’s include the example settings bundle in the binary. It’ll get pulled down by CocoaPods, too, but I don’t think we need to have CocoaPods automatically add it to the host application target.

**Comment by incanus** [comment]
Right, I agree, because it could clobber a user’s existing bundle.

**Comment by friedbunny** [comment]
Yes, we should include the example `Settings.bundle` in the pod and binary distributions — will remove a small amount of friction in our setup process, I think.

**Comment by 1ec5** [comment]
Added in f2a28f095bd36a0126ca63160f4aa941a24dfc50. Added a better way in #3183.
