### ISSUE TITLE
iOS 9 low latency touch

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2384]
I was watching some WWDC videos on how iOS handles touch input for #553.

I was watching this one on iOS 9: https://developer.apple.com/videos/wwdc/2015/?id=107

It talks about how reduce input touch latency.

I noticed it says on iOS 9 you should disable CA and UIKit animations during touch gestures.

Do we do this?

**Comment by ljbade** [comment]
It also talks about a `CAEAGLLayer` setting that controls syncing of CA animations and GL.

**Comment by 1ec5** [comment]
Currently, we do continue to animate the user dot using Core Animation while handling gestures. The CAEAGLLayer setting is one we'd like to investigate for #1125.

**Comment by incanus** [comment]
See https://github.com/mapbox/mapbox-gl-native/issues/1125#issuecomment-111636947 for our original investigations into this when it came out.

**Comment by ljbade** [comment]
Ah cool.
