### ISSUE TITLE
End developers can override library resources on Android

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2385]
There are currently items that end developers can change that should not be changeable:
 - findViewById(R.id.logoView).setVisibility(View.GONE)
 - override ic_mapbox_logo
 - ....

Two things to investigate:
 - ~~check if #2223 will disable overriding resources~~
 - check if #2222 can resolve certain cases

**Comment by mb12** [comment]
@tobrun, For projects that use multiple libraries,  if the same resource id is defined in two library projects,  which one takes preference.  Is that something one should be concerned about or is it a non issue?

**Comment by tobrun** [comment]
@mb12 the resource merger selects a resource based on the order of dependencies in your project structure. The following screenshot illustrates that resource from myLibrary will be used over the one defined in myLibrary2:

<img width="822" alt="screen shot 2015-09-23 at 20 22 17" src="https://cloud.githubusercontent.com/assets/2151639/10054412/328baf4a-6231-11e5-99fd-82546c21bf99.png">

This issue is actually related to something else. We don't want developers to override certain SDK resources. For example the Mapbox logo.

**Comment by tobrun** [comment]
I will first look into #2223 

Here is a screenshot showing that an end developer could override the mapbox logo
![override](https://cloud.githubusercontent.com/assets/2151639/10098105/cec9cb1e-637e-11e5-984c-d72ee5ee2a1c.png)

**Comment by tobrun** [comment]
Being trying to prevent changing behaviour by using a custom ImageView:
- Always Visible 
```java
   @Override
    public void setVisibility(int visibility) {
        super.setVisibility(View.VISIBLE);
    }
```
- Will throw an exception if R.drawable.ic_logo_mapbox would be overridden

```java
     @Override
    public void setImageDrawable(Drawable drawable) {
        if (LogoValidator.validate(getContext(), R.drawable.ic_logo_mapbox)) {
            super.setImageDrawable(drawable);
        } else {
            throw new RuntimeException("Not possible to change the MapboxLogo");
        }
    }
 ```

@bleege is this overkill? or should we go this far to prevent them?

**Comment by bleege** [comment]
@tobrun This looks good for some core images (Mapbox Logo and Attribution logos being the biggest).  The rest of the images let's not worry too much about.  We shouldn't have to worry too much about this as branding and attribution are part of Mapbox TOS.

**Comment by incanus** [comment]
Not sure I'm following this issues — users _should_ be able to hide the Mapbox logo and the attribution button if they choose. We support this on iOS and have back in the raster SDKs as well.

**Comment by ljbade** [comment]
@incanus is that on all plans or only higher ones?

**Comment by tobrun** [comment]
I will add methods setLogoVisbility and setAttributionVisibility.
Will revert custom ImageView

**Comment by incanus** [comment]
We've never linked logo hiding to plan on mobile native, and we allow for attribution to be provided elsewhere in the app to work around UX concerns.

**Comment by incanus** [comment]
> I will add methods setLogoVisbility and setAttributionVisibility.

Happening in https://github.com/mapbox/mapbox-gl-native/pull/2468. Nothing else actionable here.
