### ISSUE TITLE
Add vector drawable and rippleDrawable for attribution icon

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2386]
After Android Studio 1.4 is in place (#2268).

Adjustments for attribution icon:
 - provide support for vector icons 
 - provide background drawable:
  - rippleDrawable for lollipop and higher
  - circle shape for lower versions
 - allow tinting through material theme

**Comment by ljbade** [comment]
Should fix https://github.com/mapbox/mapbox-gl-native/issues/2690

**Comment by tobrun** [comment]
This is already in place with #3125
