### ISSUE TITLE
[iOS] Calling `mapView.styleURL` in early `regionDidChangeAnimated` hangs

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#2387]
0. Call `mapView.styleURL` in `regionDidChangeAnimated`
1. Open iosapp
2. Rotate screen
3. Close app (while still rotated)
4. Unrotate (e.g., go back to portrait from landscape)
5. Open app — app is frozen and mapview is cropped/stretched to previous orientation

This is sufficient to freeze the app:
```objc
- (void)mapView:(MGLMapView * )mapView regionDidChangeAnimated:(__unused BOOL)animated
{
    NSLog(@"URL: %@", mapView.styleURL.absoluteString);
}
```

Workaround is:

```objc
- (void)mapView:(MGLMapView * )mapView regionDidChangeAnimated:(__unused BOOL)animated
{
    if ([UIApplication sharedApplication].applicationState == UIApplicationStateActive)
    {
        NSLog(@"URL: %@", mapView.styleURL.absoluteString);
    }
}
```
![img_3555](https://cloud.githubusercontent.com/assets/1198851/10022886/184ca77a-611d-11e5-80a0-070e06b9a0c9.PNG)

/cc @1ec5 @incanus

**Comment by 1ec5** [comment]
Yes, we should avoid sending out these delegate callbacks when the application is in the background. The `mbgl::Map` at that point is paused, yet many seemingly innocuous methods on MGLMapView call through to `mbgl::Map` methods that only work when active.

**Comment by friedbunny** [comment]
Code in `viewDidLoad` can also trigger this, apparently.

**Comment by 1ec5** [comment]
Sure, the root of the problem is that you can't do much with mbgl::Map when it's paused, yet MGLMapView always calls through to Map because MGLMapView doesn't maintain any of its own state.

MGLMapView could "cache" values for styleURL etc., but that would muddy up the code quite a bit.

**Comment by incanus** [comment]
> Yes, we should avoid sending out these delegate callbacks when the application is in the background. 

This should be pretty easy to fix, no? Stuff like this? 

```diff
diff --git a/platform/ios/MGLMapView.mm b/platform/ios/MGLMapView.mm
index 0a42f8f..bfd4391 100644
--- a/platform/ios/MGLMapView.mm
+++ b/platform/ios/MGLMapView.mm
@@ -2901,7 +2901,7 @@ CLLocationCoordinate2D MGLLocationCoordinate2DFromLatLng(mbgl::LatLng latLng)
                     {
                         dispatch_async(dispatch_get_main_queue(), ^
                         {
-                            if ([self.delegate respondsToSelector:@selector(mapView:regionDidChangeAnimated:)])
+                            if ( ! _mbglMap->isPaused() && [self.delegate respondsToSelector:@selector(mapView:regionDidChangeAnimated:)])
                             {
                                 [self.delegate mapView:self regionDidChangeAnimated:animated];
                             }
```

**Comment by 1ec5** [comment]
That will help, but that won’t address the identical hang you’d get from accessing the style URL etc. from within `-viewDidLoad` (just as common) or any other time the application is inactive. The right fix, though messy, will be to add the `isPaused()` check to all the accessors and return some default value or a cached value, or to make `mbgl::Map` more robust while paused.

**Comment by jfirebaugh** [comment]
This was fixed with the removal of the map thread.
