### ISSUE TITLE
Disable unused local typedef warnings to fix OS X builds

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#2390]
Due to [ticket #11240 in Boost](https://svn.boost.org/trac/boost/ticket/11240), we may need to disable `-Wunused-local-typedef` to fix `make osx` builds in Xcode 7.

/cc @mikemorris @jfirebaugh

**Comment by mikemorris** [comment]
Should we do this in gypfiles or code? It looks like [we're already disabling this flag for GCC builds](https://github.com/mapbox/mapbox-gl-native/blob/d89aa51e0f59b2465dbbe5e56dd7c59ed88b2e86/macosx/main.mm#L17).
