### ISSUE TITLE
Add test support for proguard configuration

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2395]
We need to setup some kind of testing to prevent regression on proguard (implemented with #2130).
If it breaks it has high impact on end developers and will be unnoticed by us during development.

**Comment by ljbade** [comment]
Can you enable this in the gradle files?

**Comment by tobrun** [comment]
Yes, mimifyEnabled=true, if we setup cloud ui-testing we should use release builds with this enabled.

**Comment by ljbade** [comment]
Perhaps enable it for the TestApp and Sirius.

**Comment by tobrun** [comment]
Will add it to Sirius, hence we will always do dogfooding before releasing
