### ISSUE TITLE
Android has no frame rate limit

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2396]
If you enable debug mode in the test app to show the FPS counter you will see that when using gestures the frame rate jumps way above 60.

This means we are rendering far more freshness than necessary increasing CPU and GPU usage and battery drain.

It also results in stuttering such as seen in https://github.com/mapbox/mapbox-gl-native/issues/2290

I think this happened after the invalidate loop was changed.

We need to enable vsync.

**Comment by ljbade** [comment]
Possibly `eglSwapInterval` or the Android view invalidate process.

**Comment by ljbade** [comment]
http://developer.android.com/reference/android/view/Choreographer.FrameCallback.html

**Comment by ljbade** [comment]
If you read https://source.android.com/devices/graphics/architecture.html#texture it seems we need to use View invalidate as swap buffers will never stall.

**Comment by ljbade** [comment]
Did some testing. Currently pans and animations are mostly limited to 60fps I assume because of the touch input update rate. However with two finger rotate it jumps towards 200fps.

I found on `TextureView` that `postInvalidate` and `onDraw` to not work.

However `postOnAnimation` seems promising but only on API 16.

**Comment by ljbade** [comment]
`postAnimation` makes panning rather janky whereas currently it is smooth. It does lower the rotation frame rate but it seems to still spike rather high.

**Comment by ljbade** [comment]
I wonder if the problem is that two finger touch activates both rotate and zoom gesture listeners which set two different map properties and this then generates two render frames.

@jfirebaugh If `map.scaleBy` and `map.zoomBy` are both called at 60 times per second, do I get two frames rendered thus 120 FPS?

**Comment by jfirebaugh** [comment]
The frequency of calling `scaleBy` and `zoomBy` doesn't directly translate to a frame rate. These calls post updates via uv_async which has a built in form of deduplication.

**Comment by mikemorris** [comment]
Is there something going on here where the framerate is not independent of user input processing?
https://www.scirra.com/tutorials/67/delta-time-and-framerate-independence
http://gafferongames.com/game-physics/fix-your-timestep/

**Comment by ljbade** [comment]
@mikemorris It appears so. The frame rate for rotation gestures is much higher than for pan gestures.

**Comment by ljbade** [comment]
Also noting that my Samsung S6 is currently flagging Mapbox GL as slowing the phone down and recommending I delete it.

Not good for customer's apps.

**Comment by ljbade** [comment]
@jfirebaugh Is that dedupe reliable? What happens if we manage to process one render frame so quickly the second frame isn't a dupe?

**Comment by ljbade** [comment]
Confirmed disabling the zoom gesture drops frame rate to 60. Seems to be a result of updating the map twice per frame.

**Comment by ljbade** [comment]
@kkaefer What would be the best way to limit how many times the map redraws per frame?

I might be able to work around this specific problem by combining scale and rotate updates into one call.

**Comment by ljbade** [comment]
Worked out the behaviour `TextureView`:
- It creates a `SurfaceTextre` we use with EGL to render too.
- Every time we finish a render and `eglSwapBuffers()` it will return us a recycled `Surface` buffer to render into. It will keep providing new buffers as fast as we call `eglSwapBuffers()`. Basically we cannot rely on `eglSwapBuffers()` for frame limiting.
- When `TextureView.draw()` is called each vsync frame, it grabs whatever buffer is the latest, and draws this to the View. It then calls `invalidate()` to trigger a new `draw()` on the next vsync, then calls `SurfaceTextureListener.onSurfaceTextureUpdated()`. Currently our `onSurfaceTextureUpdated()` does nothing.

It seems we need to use `onSurfaceTextureUpdated()` as a signal when our previous frame made it to the screen, and should be the basis of our draw timing.

**Comment by ljbade** [comment]
I ended up using `postOnAnimate()` as it gives good results. I created a dirty flag in the Android side and removed the dirty flag that was in `NativeMapView` C++ side.

Going to need alternative to `postOnAnimate()` for pre-Jellybean devices. Likely one of the timer based methods.

**Comment by ljbade** [comment]
At some stage we should look at plumping `Choreographer`'s frame times into the map animation system to get smoother animations.

Will also look at fixing GPS dot sync.

**Comment by ljbade** [comment]
Creating PR
