### ISSUE TITLE
Latitude is set to 0 when calling setCenterCoordinate in ServiceConnection.onServiceConnected

### ISSUE THREAD

**Issue by erf** [mapbox/mapbox-gl-native#2397]
I have a use case where i set the MapView.setCenterCoordinate in ServiceConnection.onServiceConnected (as i'm using a service for syncing settings), but the latitude is always set to 0 ! ( as i see in the map and is what is returned in getCenterCoordinate ).

I'm on the: 'release-android-v0.1.0' branch, commit 4b58760

**Comment by ljbade** [comment]
@erf Do you know what order onCreate etc is called?

It might be getting reset in the map or stye loading.

**Comment by tobrun** [comment]
I was not able to reproduce this issue, reopen if still applicable.
