### ISSUE TITLE
Change node-pre-gyp trigger from "[publish binary]" to "[publish node-v...]"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-native#2402]
Per discussion [here](https://github.com/mapbox/mapbox-gl-native/commit/b81f7967134d5404950c693caaeebe177b92e1b3#commitcomment-13397364)

Presently, the presence of the string `[publish binary]` in a commit message triggers a node-pre-gyp build. This is ambiguous in a project that builds for several different platforms. We should use the `[publish platform-version]` convention established by iOS binary builds [here](https://github.com/mapbox/mapbox-gl-native/blob/d89aa51e0f59b2465dbbe5e56dd7c59ed88b2e86/scripts/ios/run.sh#L11).

ref #2365

**Comment by lucaswoj** [comment]
cc @incanus

**Comment by mikemorris** [comment]
https://github.com/mapbox/mapbox-gl-native/issues/2365 would be an alternative to this I think

**Comment by jfirebaugh** [comment]
Yeah, I'd rather have publishing triggered by tags than by magic commit strings.

**Comment by incanus** [comment]
Well, technically this is a combo of new tag + magic string about the tag, but I think it's :ok_hand: given that the commit log is very clear.

**Comment by incanus** [comment]
Ah, you mean https://github.com/mapbox/mapbox-gl-native/issues/2365 @jfirebaugh. Got it.

**Comment by lucaswoj** [comment]
@incanus @jfirebaugh I'm :+1: on closing this in favor of #2365 if you are
