### ISSUE TITLE
Subclassing MGLPointAnnotation

### ISSUE THREAD

**Issue by brittanygraft** [mapbox/mapbox-gl-native#2403]
In order to add a custom property to an annotation (outside of coordinate, title, subtitle that we are given), I subclassed MGLPointAnnotation. Upon importing the custom class into my view controller, I immediately got the failure: "Reference to MGLCoordinateBounds is ambiguous". Odd... but seems like a minor bug that could easily be fixed

**Comment by incanus** [comment]
Per support, I recommend trying to subclass `MGLShape`, then adding `coordinate` as well as your own property. 

But this root cause should be fixed, or if it can't (?) we should note that `MGLPointAnnotation` can't be subclassed.

**Comment by friedbunny** [comment]
Noting that we have an example for subclassing/reimplementing annotation classes: https://www.mapbox.com/ios-sdk/examples/annotation-models/

**Comment by lilykaiser** [comment]
Closing due to ticket age. If this is still a problem, please re-open
