### ISSUE TITLE
Builds broken due to llvm package source changes

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#2407]
See conversation from https://github.com/mapbox/mapbox-gl-native/pull/2391#issuecomment-142706082. Splitting out because it's an independent issue from that PR and affecting all builds now.

We've tried switching to clang-3.6 with both the `llvm-toolchain-precise` and `llvm-toolchain-precise-3.6` sources without luck.

I emailed the maintainer of these sources, Sylvestre Ledru, and the llvm-dev mailing list:

> Hi,

> At Mapbox we have been using the llvm-toolchain-precise-3.5 package
source to install clang-3.5 on Travis CI VMs for testing purposes
(Travis VM images are Ubuntu 12.04). This has worked fairly well for
us; thanks for providing it. However, the 3.5 source seems to have
recently disappeared, breaking our builds. No problem, we thought,
we'll update to 3.6. However, this doesn't seem to work either. When
using either the llvm-toolchain-precise or llvm-toolchain-precise-3.6
sources, no clang-3.6 package can be found:

> ```
$ sudo -E apt-add-repository -y "deb http://llvm.org/apt/precise/
llvm-toolchain-precise main"
Installing APT Packages (BETA)
$ export DEBIAN_FRONTEND=noninteractive
$ sudo -E apt-get -yq update &>> ~/apt-get-update.log
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends
--force-yes install gdb clang-3.6 libstdc++-4.9-dev libstdc++6
libllvm3.4 xutils-dev libxxf86vm-dev x11proto-xf86vidmode-dev
mesa-utils
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package clang-3.6
```

> Full output here: https://travis-ci.org/mapbox/mapbox-gl-native/jobs/81888110
Similar output when using the llvm-toolchain-precise-3.6 source here:
https://travis-ci.org/mapbox/mapbox-gl-native/jobs/81865117

> Are there packages missing from these sources? What version is the
unsuffixed llvm-toolchain-precise source expected to contain? And for
the future avoidance of unexpected build breakage, is there a setup we
can use where packages won't disappear from underneath us?

> Thanks!

**Comment by jfirebaugh** [comment]
Message approved for the mailing list: http://lists.llvm.org/pipermail/llvm-dev/2015-September/090712.html

**Comment by mikemorris** [comment]
The `llvm-toolchain-precise-3.5` repository was back up again and working fine this morning (https://github.com/mapbox/mapbox-gl-native/pull/2391#issuecomment-142976727), but looks like `-3.6` is down again now (https://github.com/mapbox/mapbox-gl-native/pull/2416#issuecomment-143005150).

**Comment by jfirebaugh** [comment]
[Current failure:](https://travis-ci.org/mapbox/mapbox-gl-native/jobs/82007747)

```
$ echo '"deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main"' | sudo tee -a /etc/apt/sources.list > /dev/null
Installing APT Packages (BETA)
$ export DEBIAN_FRONTEND=noninteractive
0.01s$ sudo -E apt-get -yq update &>> ~/apt-get-update.log
0.04s$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gdb clang-3.5 libstdc++-4.9-dev libstdc++6 libllvm3.4 xutils-dev libxxf86vm-dev x11proto-xf86vidmode-dev mesa-utils
Reading package lists...
E: Type 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' is not known on line 55 in source list /etc/apt/sources.list
E: The list of sources could not be read.
E: The package lists or status file could not be parsed or opened.
```

**Comment by mikemorris** [comment]
From support@travis-ci.com:

> Sorry for the continued issue. This appears to be something out of our reach at the moment. I am trying to find anyone who is involved in the LLVM project to see if we can resolve this problem soon.

**Comment by jfirebaugh** [comment]
No response on the mailing list. I also opened [an issue in the Travis source whitelist repo](https://github.com/travis-ci/apt-source-whitelist/issues/1560) and cc'd some people who potentially have the same issue as us.

**Comment by jfirebaugh** [comment]
The sources and packages are there. Travis just can't connect:

```
W: Failed to fetch http://llvm.org/apt/precise/dists/llvm-toolchain-precise-3.6/Release.gpg  Connection failed
W: Failed to fetch http://llvm.org/apt/precise/dists/llvm-toolchain-precise-3.6/Release  
W: Failed to fetch http://llvm.org/apt/precise/dists/llvm-toolchain-precise-3.6/main/binary-amd64/Packages  Unable to connect to llvm.org:http:
W: Failed to fetch http://llvm.org/apt/precise/dists/llvm-toolchain-precise-3.6/main/binary-i386/Packages  Unable to connect to llvm.org:http:
```

**Comment by jfirebaugh** [comment]
http://llvm.org/apt/precise/dists/llvm-toolchain-precise-3.5/ still exists BTW, so we shouldn't necessarily need #2416. It's just no longer listed on http://llvm.org/apt/.

**Comment by jfirebaugh** [comment]
So in the end all the failures were due to llvm.org being slow: #1828.
