### ISSUE TITLE
Use Android Choreographer to smooth Map animations

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2410]
In Android's Project Butter (for Jelly Bean) they introduced `Choreographer` for animations to keep them synced with the rest of the system.

We should use `postFrameCallback()` method which provides an accurate frame time stamp to drive animations inside `Map`.

**Comment by ljbade** [comment]
@jfirebaugh How does the current C++ animation system work? What would it take to plump the frame time stamp for the *next* frame that will be drawn (so basically what the state should be for the upcoming `renderSync` as we get from Android.

**Comment by ljbade** [comment]
Here is the reasoning from the Android docs:
> Using the frame time helps to reduce inter-frame jitter because the frame time is fixed at the time the frame was scheduled to start, regardless of when the animations or drawing callback actually runs. All callbacks that run as part of rendering a frame will observe the same frame time so using the frame time also helps to synchronize effects that are performed by different callbacks.

**Comment by ljbade** [comment]
Taking a look at the Android animation code, you do something like this:
- someone requests an animated change - you *schedule* a `postFrameCallback`
- on your first `postFrameCallback` you save that time stamp as the animation start time
- subsequent animation updates use new `postFrameCallback` times

**Comment by ljbade** [comment]
`Transform` would be easy to modify to use ^, basically don't set `transitionStart` until first call to `updateTransitions`. The `updateTransitions` would receive it's frame time from an optional parameter to `renderSync`

**Comment by ljbade** [comment]
It would be interesting to see if iOS also provides a similar synced time source for driving animations.

**Comment by bleege** [comment]
@ljbade I believe most of this work on the iOS side was put down into the Core GL level as they originally tried using the rough iOS equivalent called [CADisplayLink](https://developer.apple.com/library/prerelease/ios/documentation/QuartzCore/Reference/CADisplayLink_ClassRef/index.html).  Let's work with @1ec5 @incanus @friedbunny to see what they've done on the iOS side already and then reuse that if possible.

**Comment by incanus** [comment]
I'm not sure I understand the actual problem that this would solve in our particular case. Animations in the map view are entirely self-contained and don't need to be synced with anything as the map view itself handles updating native views atop (long stable in iOS, just recently synced on Android in https://github.com/mapbox/mapbox-gl-native/pull/2409).

**Comment by ljbade** [comment]
@incanus The more I think about it, I think you are right that this wont fix the sync issues, which really requires GL side user dot and InfoViews (even if just render them to bitmap then pass to GL texture).
