### ISSUE TITLE
Make map more fluid

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2411]
Even after #2409 there is still some work to be done.

Google Maps still feels much more fluid in response to gestures and animations.

#2410 should improve animations, but gestures are still a bit janky.

I don't think this is a GL performance issue as it seems we can easily hit 140 FPS on my Samsung S6.

This is more about avoiding any frame skipping and improving the lag between touch input and pixels on the screen.

There is also still a very small 1-2 frame lag between the map and the GPS marker position,

**Comment by ljbade** [comment]
Did some logging and found the delay between map and the GPS marker.

TextureView has a 1 frame lag between a a render and when it appears on screen.

Only way I can see to fix this would be to capture the calculated positions of the GPS

**Comment by ljbade** [comment]
Didn't seem to make a difference.

I wonder if it's possible to capture the GPS marker, or render it into a offscreen buffer then overlay it in GL.

@incanus How much lag does iOS now have with the GPS marker?

**Comment by incanus** [comment]
> I wonder if it's possible to capture the GPS marker, or render it into a offscreen buffer then overlay it in GL.

This is the approach I tried in https://github.com/mapbox/mapbox-gl-native/issues/1125#issuecomment-117471812. It's a proven concept and needs development time, which will probably be easier on iOS. 

> How much lag does iOS now have with the GPS marker?

None, nor has it had any in any release. We solved this problem. The trick is updating the GPS marker position using the geo-to-pixel conversion routines with the same iteration of `TransformState` as the GL frame was drawn. Has to be exact.

**Comment by tobrun** [comment]
I tried pinpointing some stuff using the improved [GPU profiler](https://www.youtube.com/watch?v=VzYkVL1n4M8) on Marshmallow. 
I also did a benchmark with Google Maps and they rarely drop a frame.

## Legenda:
In upcoming screenshots you will see bars. A bar represents the frame time, the horizontal green line represents the magic 16ms border. A frame going above this border will be dropped and the user will notice a stutter. A bar consist out of multiple colors, below is the related legenda:

<img width="177" alt="screen shot 2015-09-27 at 11 54 41" src="https://cloud.githubusercontent.com/assets/2151639/10122176/836b3332-650f-11e5-8662-de0e3a6105b3.png">

## Panning 
This feels responsive and the profiler shows the same:

![panning_around_map_same_zoom_level](https://cloud.githubusercontent.com/assets/2151639/10122190/355cf1fc-6510-11e5-8875-2ca35bfe8b1b.png)

## Double tap zoom
This feels responsive and the profiler shows the same:

![zooming_double_tap](https://cloud.githubusercontent.com/assets/2151639/10122207/baf776fc-6510-11e5-9fb8-f158423da130.png)

## Loading new tile
Occasionally you see spikes in Swapping Buffers.

![loading_new_tile](https://cloud.githubusercontent.com/assets/2151639/10122218/3083fd1e-6511-11e5-99f0-a87fb922b6f1.png)

## Pinch zoom on higher zoomlevel
It rarely drops a frame (multiple zoom actions recorded)
 
![normal_zooming](https://cloud.githubusercontent.com/assets/2151639/10122254/ff0f1618-6512-11e5-9e09-a68f3f4f2060.png)

## Pinch zoom on lower zoomlevel
It drops frames more often (multiple zoom actions recorded)

![normal_zooming_higher_level](https://cloud.githubusercontent.com/assets/2151639/10122260/46404ade-6513-11e5-967f-d19ba3df7c4a.png)

## Pinch zooming slowly for some time
When zooming slowly, I noticed stuttering in the ui, the profiler shows the same.

![pinch_zoom_out_slowely](https://cloud.githubusercontent.com/assets/2151639/10122231/c94c83cc-6511-11e5-9050-7c61051d6edb.png)

## Rotate slowly on same zoom level
When rotating slowly, I noticed stuttering in the ui, the profiler shows the same.

![rotate_same_zoom_level](https://cloud.githubusercontent.com/assets/2151639/10122234/e950dd76-6511-11e5-94c6-221e03a06660.png)

**Comment by ljbade** [comment]
Nice work @tobrun that matches the observations I had made.

Sounds like we need to look at optimising higher zoom levels.

@kkaefer Do you have any thoughts on what we could improve?

**Comment by ljbade** [comment]
@tobrun Do you know much about the GPU tools built into Android Studio? I recall 1.3 or 1.4 improved these.

**Comment by tobrun** [comment]
It is actually the same thing as in the screenshot, only visualised in the IDE.
You can enable it by: 

Settings > Developer options > Profile GPU rendering:
 - in adb shell dumpsys gfxinfo 

Normally you should see it visualise in the IDE under:
Android Monitor > CPU | GPU tab > GPU tab

I initally wanted to try out this feature but couldn't get it to work. 
I used the other option in Profile GPU rendering instead.

**Comment by ljbade** [comment]
I tested this today. You can very easily see when we get the hitches. Now we need to work out what is causing them.

**Comment by ljbade** [comment]
Some refactoring I have been working over in #2049 seems to have fixed the worst of this. Gestures are smooth again.
