### ISSUE TITLE
[Android] MapView.MapChange has private access again.

### ISSUE THREAD

**Issue by mayardb** [mapbox/mapbox-gl-native#2413]
Hello mapbox-gl team!

In the current Snapshot version (from the 23rd of September), MapView.MapChange has private access. This makes the MapView.OnMapChangedListener useless from outside of the MapView.

In the master branch, MapView.MapChange has public access, and the code was ok before this Snapshot version (ok in my code the 09/23 before the snapshot deployment). This was fixed with the Pull Request https://github.com/mapbox/mapbox-gl-native/pull/2291.

Which branch are you using for the deploys ? Will the visibility be fixed soon ?
Thanks for your answers.
Bastien.

**Comment by ljbade** [comment]
@mayardb SNAPSHOT releases for v0.1.0 are built from the https://github.com/mapbox/mapbox-gl-native/tree/release-android-v0.1.0 branch.

Looks like this PR missed getting cherry picked.

@bleege Should we cherry pick https://github.com/mapbox/mapbox-gl-native/commit/8d322c65728ffe0d4f69fcd3b73b007a53eb505a

**Comment by bleege** [comment]
Thanks for bringing this to our attention @mayardb.  We'll make sure to address it in `0.2.0`.

**Comment by mayardb** [comment]
Thank you to you to add it to the next Snapshot. That unlocks me.

And thank you for your works.

**Comment by mayardb** [comment]
Still not done in the 0.1.0 version. I reopen the issue not to forget to add it.

**Comment by bleege** [comment]
@mayardb Thanks for following up on this.  We've changed the distribution naming of the SNAPSHOTS and are no longer using the `com.mapbox.mapboxgl` structure that produced the [`0.1.0-SNAPSHOT`](https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxgl/mapbox-gl-android-sdk/0.0.1-SNAPSHOT/) instead we're using `com.mapbox.mapboxsdk` that's producing [`2.1.0-SNAPSHOT`](https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-android-sdk/2.1.0-SNAPSHOT/).  The latest version of this `com.mapbox.mapboxsdk` SNAPSHOT should work the way you need.

We've also refactored how the MapChange enum is setup using `@IntDef` for performance reasons.  Everything is `public` so there should be no issue making use of this.  For more information please see the [`MapChange` Enum](https://github.com/mapbox/mapbox-gl-native/blob/67f0108389cdd51f3c59ae7638ea2ecd1c4fa899/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L254-L356) and the [`OnMapChangedListener`](https://github.com/mapbox/mapbox-gl-native/blob/67f0108389cdd51f3c59ae7638ea2ecd1c4fa899/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L443-L456) in `MapView`.

Thanks again!

**Comment by mayardb** [comment]
Thank you. Every works fine.

**Comment by bleege** [comment]
Awesome!  Thanks for confirming and for using the SDK @mayardb!
