### ISSUE TITLE
Create Android EventManager

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2422]
For metrics (#2421) we need an Android equivalent of Mapbox's `MGLMapboxEvents`.

Following Android conventions it will be called `EventManager`.

Features:
- performs event queue processing on a background low priority thread
- all functions are threadsafe
- uses OkHTTP along with SSL pinning for upload
- uses network request coalescing to reduce battery drain
- can be paused and resumed
- fulfils our data lifetime guarantees
- checks network status before upload

**Comment by ljbade** [comment]
Will be working on the `android-metrics` branch.

First step will be to define a POJ `Events` object that will hold our supported data.

**Comment by ljbade** [comment]
Next is to create the singleton `EventManager`.

**Comment by ljbade** [comment]
Hmm looking at the Android docs we want to use a [background service](https://developer.android.com/training/run-background-service/index.html) to handle event processing and uploading.

**Comment by ljbade** [comment]
I created a `EventService` that end developers will have to add to their application manifest.

It is started by `EventManager.pushEvent` and will return a status via `LocalBroadcastManager`.

The `EventService` will handle the data upload.

**Comment by tobrun** [comment]
This is great :thumbsup:
Just one minor remark:
> end developers will have to add to their application manifest.

I'm personally not a big fan of this, if end developer ignore this we will not receive any metrics..

**Comment by ljbade** [comment]
@tobrun Unfortunately I can't see a way around this. Using background services on Android requires a `<service>` in the manifest.

We can add a check in `MapView` that will throw if the service has not started with a description that explains they need to add the service to the manifest.

**Comment by ljbade** [comment]
Anyway current branch has very rough `EventManager` that manages to upload a turnstile event and gets a HTTP 400 back from the server.

Things to work on:
- pause/resume
- better way to get access token - might move this into pushEvent since multiple MapViews could mean multiple keys...
- automatically fire turnstile event on either creation of `EventManager` or `MapView`
- make `EventManager` singleton again (once we remove access key to `pushEvent`)

**Comment by tobrun** [comment]
- If we execute an Asynctask in pushEvent() we could remove Service

- Singleton creation should enforce the application context
 ```
public static synchronized EventManager getInstance(Context context) {
    if (sInstance == null) {
       sInstance = new EventManager(context.getApplicationContext());
    }
    return sInstance;
  }
```

- better way to get access token - why are we not placing the token in resources?

**Comment by tobrun** [comment]
I believe this issue is out of date and is tracked elsewhere.

cc @bleege
