### ISSUE TITLE
addMarkers in JNI

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2428]
Add markers to JNI

Original post:
List missing features:
 ~~- [add Z index](https://github.com/mapbox/mapbox-gl-native/blob/8e5bbb062cd75bdaac4b0bb76b608e9165eb649b/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/annotations/Annotation.java#L55-L63)~~
 ~~- #1726~~
 ~~- #1882~~

**Comment by tobrun** [comment]
Jake Wharton gave a nice [presentation]((https://speakerdeck.com/jakewharton/eliminating-code-overhead-square-hq-2015) about eliminating code overhead in Android applications. He has some nice pointers that will improve scalability.

**Comment by ljbade** [comment]
@tobrun Big improvment will be to use arrays/lists to pass markers to JNI in bulk rather than having to loop in Java.

**Comment by tobrun** [comment]
@ljbade inline with your comment I want to add an adapter approach on the java side. This is also inline of improving scalability. 

Reasons:
 - Adapter approach is known pattern for Android developers
 - Developers will use bulk insert of markers to JNI through adapter interface
  - setAdapter(MarkerAdapter extends BaseAdapter)
 - Recycling InfoWindow* 
 - Allows customisation of the InfoWindow view, see request at #2362 
 - Exposes onItemClicked interface (request of @erf for onMarkerClicked like method)

*=  View inflation on every click is expensive task, recycling will be improve performance

**Comment by tobrun** [comment]
@ljbade 
Will add addMarkers function in jni.cpp
Will add addPointAnnotations function in annotation_manager.cpp

**Comment by ljbade** [comment]
@tobrun That error is because you need to add an entry to https://github.com/mapbox/mapbox-gl-native/blob/master/android/cpp/jni.cpp#L1614

Loop looks good.

You should be fine with the local refs. JNI automatically releases any local references on return from the C++ function (that is why you see `NewGlobalRef` for long lived objects). However `DeleteLocalRef` does allow the JVM to reduce how much memory is used during the function call, particularly inside a loop where you might get 1000s of live objects.

**Comment by incanus** [comment]
Z-index, great circles, and even circle primitives are non-essential right now. Let's step back and consider more carefully what we focus on in Android — full parity with the raster SDK isn't necessarily the goal. 

/cc @bleege

**Comment by bleege** [comment]
@incanus Thanks for the direction.  That said Z-Index I believe is [coming from the Google Maps API](https://developers.google.com/android/reference/com/google/android/gms/maps/model/Circle) for Annotations.

**Comment by incanus** [comment]
Refs https://github.com/mapbox/mapbox-gl-native/issues/991

**Comment by bleege** [comment]
Ah... thanks for clarifying @incanus.  :+1:

**Comment by ljbade** [comment]
@tobrun Can we close this now PR landed?
