### ISSUE TITLE
Set version number in code

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#2430]
We're currently pulling the version number from Git tags. That means we'd have to be very stringent with creating tags. In the past, this has proven to be very difficult. Instead, we should hardcode the version number into a file checked into the repository that we manually update when releasing new software.

**Comment by ljbade** [comment]
:+1:

**Comment by brunoabinader** [comment]
> we should hardcode the version number into a file checked into the repository that we manually update when releasing new software.

:+1: can we start doing this now?

**Comment by jfirebaugh** [comment]
We're now using only the commit SHA, which is set automatically by the cmake script.
