### ISSUE TITLE
Add test support for gestures

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2432]
Currently is not possible to write tests for CompassView because espresso [doesn't expose advanced gestures](https://code.google.com/p/android-test-kit/source/browse/espresso/lib/src/main/java/com/google/android/apps/common/testing/ui/espresso/action/ViewActions.java). We need to add support for gestures in espresso. We could possibility also use another framework to do View integration testing eg. [http://robolectric.org/](RoboElectric).

**Comment by tobrun** [comment]
Espresso exposes [MotionEvents](https://android.googlesource.com/platform/frameworks/testing/+/android-support-test/espresso/core/src/main/java/android/support/test/espresso/action/MotionEvents.java) methods for triggering MotionEvent for
 - MotionEvent.ACTION_DOWN
 - MotionEvent.ACTION_UP
 - MotionEvent.ACTION_MOVE

But does not support:
- MotionEvent.ACTION_POINTER_DOWN

This means that multi touch events are currently not supported.

**Comment by bleege** [comment]
This is good to know @tobrun!  Thanks for looking into this and documenting it for everyone.  :+1: 

Maybe @zugaldia has some ideas about this [from his Espresso work](https://github.com/mapbox/mapbox-gl-native/issues/2317)?

**Comment by tobrun** [comment]
We will be moving away from espresso and use another framework to test this. Closing

**Comment by bleege** [comment]
> We will be moving away from espresso and use another framework to test this. Closing

@tobrun Can you help me understand why moving to a different testing framework obviates the need for this issue?

**Comment by tobrun** [comment]
Espresso is a black box testing framework which doesn't allow us to call methods directly on objects.
I'm currently looking at other frameworks where that is possible. Note that we don't need to test gestures themselves but the business logic behind them in other words test our SDK and not the Android SDK.

**Comment by bleege** [comment]
> Note that we don't need to test gestures themselves but the business logic behind them in other words test our SDK and not the Android SDK.

Exactly.  This is why this ticket should remain open so that we remember to test the full stack from "gesture occurred" to "Mapbox SDK responded by doing x".  :wink:

**Comment by tobrun** [comment]
This ticket is about the ability to do integration testing and not about `from "gesture occurred" to "Mapbox SDK responded by doing x"` because this is something that is covered by unit testing. Feel free to create issues for missing parts in integration or unit testing.

**Comment by bleege** [comment]
Hrm... I'm even more confused now.  :smile:  Integration testing is  `from "gesture occurred" to "Mapbox SDK responded by doing x"` while unit testing is isolating business logic and testing it.  Let's chat about this IRL and get on the same page.  :+1:

**Comment by tobrun** [comment]
Not relevan
