### ISSUE TITLE
iOS tilt gesture should only activate for horizontal placement

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2435]
Unlike Apple Maps, if you have two fingers aligned vertically and pan down, our map tilts. This should only happen when two fingers are aligned horizontally. 

/cc @friedbunny @1ec5

**Comment by friedbunny** [comment]
I hadn't noticed, but this is true of both Apple and Google. What's the rationale behind this limitation?

**Comment by 1ec5** [comment]
This is how MapKit manages to allow two-finger panning.

**Comment by incanus** [comment]
I noticed this today when I attempted two-finger panning & zooming but instead tilted the map.

**Comment by friedbunny** [comment]
Fixed in #9571, will be in v3.6.1.
