### ISSUE TITLE
Animating region change causes map's regionDidChange delegate to fire before visible bounds is updated

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-gl-native#2436]
I have an MGLMapView from the iOS SDK version 2.1.2 and when I use the method:
```objective-c
- (void)setCenterCoordinate:(CLLocationCoordinate2D)centerCoordinate zoomLevel:(double)zoomLevel animated:(BOOL)animated;
```
to set the region, the map's delegate method:
```objective-c
- (void)mapView:(MGLMapView *)mapView regionDidChangeAnimated:(BOOL)animated;
```
seems to fire before the animation finishes.

For an example, I'm starting with the map's `visibleCoordinateBounds` over Minneapolis:
NE: 45.504836, -92.822243
SW: 44.412456, -93.691998

And I'm using `setCenterCoordinate:zoomLevel:animated` with coordinate
(39.139900207519531, -84.506446838378906), zoom level 9, and animated YES to center just north of Cincinnati.

When the `regionDidChangeAnimated:` delegate fires, the map's `visibleCoordinateBounds` are:
NE: 43.993361, -90.614903
SW: 43.016909, -91.373379

This is between Minneapolis and Cincinnati.  `regionDidChangeAnimated:` doesn't fire again once the visible region becomes Cincinnati.  If I wait a second and log the visible coordinates, they are correct:
NE: 39.441747849507863, -84.286720360868812
SW:  38.836752832118236, -84.726173315888658

So the visible region eventually gets updated, just not before the `regionDidChangeAnimated:` delegate is called. We use the visible region to refresh our pins.  Should the `visibleCoordinateBounds` be updated before the delegate is notified of the region change finishing?

**Comment by 1ec5** [comment]
#2373 looks like it’ll fix this issue.

**Comment by johnnewman** [comment]
[#2373](https://github.com/mapbox/mapbox-gl-native/pull/2373) was merged a few weeks ago but this issue is still happening on ios-v3.0.0-pre.4.  Is this a different issue?  Thanks.

**Comment by 1ec5** [comment]
My bad, #2373 / #2700 were limited to fixing these notifications when triggered by gesture recognizers, not programmatic use of `-setCenterCoordinate:zoomLevel:animated:`.
