### ISSUE TITLE
APK size limit in Google Play bumped to 100MB

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#2441]
This should allow us to de-prioritize 'move xxx from C++ to java'  issues.

http://android-developers.blogspot.com/2015/09/support-for-100mb-apks-on-google-play.html

**Comment by tobrun** [comment]
Current AAR size is 3 MB :+1:

**Comment by ljbade** [comment]
We have a minimal footprint but I'd still like to get it smaller and remove the large number of static libraries we depend on.
