### ISSUE TITLE
Android Project Code Style

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2443]
Currently the Android repo supports multiple formatting styles. Only be looking at the MapView class I can identify 3-4 different ones. If I format code on master using the Intelij hotkey it generates 70 changes. My personal belief is that this shouldn't generate a change at all and that we should aim for a consistent style throughout the repo. 

We can customise AndroidStudio be introducing custom styles, code inspections & save macro's. 

These can be added to the development setup and guidelines for contributing. 

@ljbade @bleege

**Comment by ljbade** [comment]
Yeah we could hit this as we make a pass over all the files for JavaDoc

**Comment by ljbade** [comment]
Yeah we could hit this as we make a pass over all the files for JavaDoc

**Comment by ljbade** [comment]
Yeah we could hit this as we make a pass over all the files for JavaDoc

**Comment by ljbade** [comment]
Yeah we could hit this as we make a pass over all the files for JavaDoc

**Comment by bleege** [comment]
Good catch @tobrun!  We've used Checkstyle for this purpose [on the Raster SDK](https://github.com/mapbox/mapbox-android-sdk/blob/26d8857786856e5bd933ef6ad28b1d359b2a342a/checks.xml) in the past and it worked well.  It flags style violations as warnings in Android Studio which helps keep everyone honest.  The only question is which style we want to use:

```java
public void foo() {

}

public void foo()
{

}
```

Let the debate begin!  :smile:

**Comment by ljbade** [comment]
I'd say most existing code using brackets inline

**Comment by ljbade** [comment]
I'd say most existing code using brackets inline

**Comment by bleege** [comment]
We already have [`checks.xml`](https://github.com/mapbox/mapbox-gl-native/blob/1c8256fa9bde9ca684843fe73a02b993056c57c7/android/java/checks.xml) so we can hook this up in Android Studio to help us develop / enforce styles.  JetBrains offers the [following plugin](https://plugins.jetbrains.com/plugin/1065) to do so.  The SDK's build.gradle should already [be configured to enforce this](https://github.com/mapbox/mapbox-gl-native/blob/40b29a5ce4ae46aa7631ed30c77e27df131f23f9/android/java/MapboxGLAndroidSDK/build.gradle#L93-L96).

**Comment by tobrun** [comment]
Reopening this because I believe we can do more than just enforcing a checkstyle.

#### Codestyle:
We are enforcing the same [codestyle](https://source.android.com/source/code-style.html) as for Android platform development. One thing this will fix:
- Code generation setup doesn't respect the default naming conventions of the Android platform eg. a setter for `String mText` will be generated as `setMText(String mText)`, the correct way would be`setText(String text)` instead

I'm suggesting using the one Google provides for [platform development](https://raw.githubusercontent.com/android/platform_development/master/ide/intellij/codestyles/AndroidStyle.xml):

You need to place this file 
> ~/Library/Preferences/AndroidStudio1.4/codestyles

Select the correct codestyle in the dropdown option in preferences:

![screen shot 2015-10-22 at 10 00 11](https://cloud.githubusercontent.com/assets/2151639/10659959/ea2ed72a-78a3-11e5-9471-0c1884242195.png)


#### Macro's:
Macro's in AndroidStudio can be used to perform multiple actions on a Keyboard shortcut.
Some save actions I mis from the Eclipse days are:
 - formatting on save 
 - optimising imports 

macros.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<application>
  <component name="ActionMacroManager">
    <macro name="MapboxSaveActions">
      <action id="ReformatCode" />
      <action id="OptimizeImports" />
      <action id="SaveAll" />
    </macro>
  </component>
</application>
```

You need to place this file under: 

> ~/Library/Preferences/AndroidStudio1.4/options

Assign a keyboard shortcut in Preferences:

![screen shot 2015-10-22 at 09 29 42](https://cloud.githubusercontent.com/assets/2151639/10659427/fffbd674-789f-11e5-9497-eb434f4eeefe.png)
![screen shot 2015-10-22 at 09 33 11](https://cloud.githubusercontent.com/assets/2151639/10659430/034ad74e-78a0-11e5-9d07-0aad0b19a5bb.png)

**Comment by tobrun** [comment]
I created my own [codestyle](https://gist.github.com/tobrun/08e0761850a5b4ea5771) and ran it over the whole project in https://github.com/mapbox/mapbox-gl-native/commit/497f7ebf5f50b4ea2ad6c277229f69584bfc57c7

**Comment by tobrun** [comment]
I'm currently thinking that tabs size should be left default, will try again

**Comment by tobrun** [comment]
Ok, finalized it with [this codestyle](https://gist.github.com/tobrun/fb9e380d2c4f3f83f775) as shown in https://github.com/mapbox/mapbox-gl-native/commit/83fbddec55de6aa72ce2b43aaa8698294e91443a.

@ljbade @bleege 
Could you go over the commit and give feedback on things you like/dislike?

**Comment by bleege** [comment]
This is a good thing, but I'd like to see it in one place.  Specifically, we have Checkstyle that's part of the Gradle build process already.  Ideally we could get Android Studio's Code Style to be driven by that `checks.xml` file so that we could keep all this information in one spot.

**Comment by ljbade** [comment]
@tobrun Can we keep the existing tab width? it would save a lot of code churn

**Comment by tobrun** [comment]
We can add it to gradle using `idea` plugin, as shown in this [SO-post](http://stackoverflow.com/questions/26108228/pass-custom-code-style-xml-to-gradle-idea-plugin)

**Comment by bleege** [comment]
@tobrun Cool.  Let's try that then.

**Comment by tobrun** [comment]
@bleege I have been looking at integrating this in `gradle` but having no succes, 
solution in link above is not working and googling for this only returns checkstyle setup.

**Comment by tobrun** [comment]
Going to close this down for now, will be on the lookout if anything changes in this space
