### ISSUE TITLE
Efficiently apply style changes

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#2445]
In JS, we have [a way to compute the difference between two styles](https://github.com/mapbox/mapbox-gl-js/pull/1348), and only selectively reparse tiles. This is very useful in Native as well, as it'd allow us to rapidly switch styles without seeing a flash of an empty map. Also see https://github.com/mapbox/mapbox-gl-js/issues/1341.
- [ ] Figure out a way to reparse individual layers of a tile and how buffer uploads are handled
- [ ] Compute differences between style objects, e.g. by creating a hash of all properties of a layer

**Comment by mourner** [comment]
cc @scothis

**Comment by jfirebaugh** [comment]
Note that style diffing is not currently built in to mapbox-gl-js: it's an [external function](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/lib/diff.js) which produces a set of commands to run in a [batch style change](https://www.mapbox.com/mapbox-gl-js/api/#map/batch).

**Comment by scothis** [comment]
Batching style mutations is what gave us the greatest perf boost, followed by the style diff. Diff'ing without batching is most likely a perf hit rather than a gain (for a non-trivial delta).

I'd like to keep the diff format compatible between JS and native if at all possible, although the JS diff is biased towards the mapbox-gl-js API.

**Comment by jfirebaugh** [comment]
> I'd like to keep the diff format compatible between JS and native if at all possible, although the JS diff is biased towards the mapbox-gl-js API.

Me too, which means the first part of this change is porting all the JS style mutation APIs. It's something we've been meaning to do for quite some time, but a substantial change in and of itself.

**Comment by scothis** [comment]
It's also worth mentioning that mapbox-gl-js does not support every diff operation. In studio when we apply the diff, we fall back to a full setStyle if a particular operation is unsupported.

The most important operations to support are:
- addLayer
- removeLayer
- setLayoutProperty
- setPaintProperty

From there add support for any operation you see that frequently causes a setStyle fallback.

The semantics around add/removeLayer are particularly important to get right as the diff is optimized to avoid unnecessary work. For example, if you move a layer and change a property the diff will be two operations: removeLayer and addLayer.

**Comment by jfirebaugh** [comment]
Depends on #837, more or less.

**Comment by jfirebaugh** [comment]
⇢ #7893
