### ISSUE TITLE
Add marker clustering

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2446]
Needed for parity with Raster SDK.
Note: [Google Maps](https://www.youtube.com/watch?list=PLOU2XLYxmsIKgVkdTcsULfTIIsKz4n-I8&t=108&v=FFm9NmSfjw0) is currently animating cluster and markers while zooming

**Comment by incanus** [comment]
:point_right: https://github.com/mapbox/mapbox-gl-native/issues/320
