### ISSUE TITLE
Move/Enlarge touch target Marker

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2454]
While testing I noticed that the touch target of the marker is lower than the actual sprite. This resulted in not handled click events. Touch target of marker should be moved higher or/and enlarged.

**Comment by ljbade** [comment]
@incanus are you scaling the target hit box with the DPI?

**Comment by tobrun** [comment]
Missing the touch target occurs more on Emerald styled map than MapboxStreets 
 - Marker is larger on Emerald

**Comment by ljbade** [comment]
Ah yeah.

@tobrun You think this is a quick fix?

**Comment by incanus** [comment]
Dupe of #1504
