### ISSUE TITLE
Sporadic missing sprites

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-gl-native#2455]
In the iOS GL SDK 2.1.2, we sometimes see console logs about missing sprites:
```
[INFO] {Worker}[Sprite]: Can't find sprite named 'com.mapbox.sprites._motoring_'
```

To double check that we are providing valid images to the map, we log the MGLAnnotationImage, its UIImage, and the reuse identifier in the `mapView:imageForAnnotation:` delegate.  This is what our current `imageForAnnotation` body looks like:
```objective-c
- (nullable MGLAnnotationImage *)mapView:(MGLMapView * __nonnull)mapView imageForAnnotation:(id<MGLAnnotation> __nonnull)annotation
{
    if ([annotation isKindOfClass:[RT_MapAnnotation class]])
    {
        RT_MapAnnotation *mapAnnotation = (RT_MapAnnotation *)annotation;
        MGLAnnotationImage *annotationImage = [self.map dequeueReusableAnnotationImageWithIdentifier:mapAnnotation.reuseIdentifier];
        if (annotationImage == nil)
        {
            annotationImage = [mapAnnotation annotationImage];
            NSLog(@"generated: %@\timage: %@\tidentifier: \"%@\"", annotationImage, annotationImage.image, mapAnnotation.reuseIdentifier);
        }
        return annotationImage;
    }
    return nil;
}
```
Here is a log pulled from an iPhone 5:
```
2015-09-29 14:07:04.366 [2214:958551] generated: <MGLAnnotationImage: 0x1d276d10>	image: <UIImage: 0x1b5d54e0>, {27, 78}	identifier: "_motoring_"
2015-09-29 14:07:04.369 [2214:958724] [INFO] {Worker}[Sprite]: Can't find sprite named 'com.mapbox.sprites._motoring_'
```

**Comment by jfirebaugh** [comment]
Do you change the style while there are point annotations on the map? That's known to trigger the "Can't find sprite" log message. See #1488.

**Comment by johnnewman** [comment]
The style hadn't changed, it was on Mapbox Streets.

**Comment by jfirebaugh** [comment]
This was likely a race condition with adding an annotation icon while the style was loading. With #3049, annotations have their own sprite atlas and the race condition has been eliminated, so I'm pretty confident it is fixed. This will be part of the 3.1.0 SDK release.

**Comment by 1ec5** [comment]
3.1.0 is coming soon. In the meantime, please verify the fix with [this prerelease](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.1.0-pre.2) ([podspec](https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.0.0-pre.2/ios/Mapbox-iOS-SDK.podspec) for CocoaPods) and let us know if you still see the issue. Thanks!
