### ISSUE TITLE
Let MGLMapViewDelegate cancel region changes

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#2457]
`-[MGLMapViewDelegate mapView:regionWillChangeAnimated:]` should return a Boolean, so that delegates can cancel impending viewport changes by return `NO`. If the viewport change was initiated programmatically, perhaps the return value should be ignored, but it should at least be honored for viewport changes initiated by gesture recognizers.

/cc @friedbunny @incanus

**Comment by 1ec5** [comment]
Instead of overloading `-mapView:regionWillChangeAnimated:`, I think it would be better to have a `-mapView:shouldChangeToCamera:animated:` that takes an additional MGLMapCamera object, so that the implementer can make an informed decision about the animation that will take place. Or, following NSAnimationDelegate in AppKit, we could pass in an MGLMapAnimation object that encapsulates all the known information about an animation: its start and endpoints as well as the action that triggered the animation.

**Comment by 1ec5** [comment]
#3090 would serve as a model for this method.

**Comment by 1ec5** [comment]
On iOS, the map view would ideally allow the user to pan to a disallowed region but quickly snap back to within the allowed region as soon as the gesture is complete. So if `-mapView:shouldChangeToCamera:animated:` returns `NO`, the transition should continue but a bounce-back transition should be queued up, to be run immediately after the disallowed change.

**Comment by Zakay** [comment]
+1 This is a great addition!

**Comment by dsmitchell** [comment]
Hey, I'm new here. As a possible variation/update to this proposal, UIScrollView has a delegate method called: - (void)scrollViewWillEndDragging:(UIScrollView *)scrollView
                     withVelocity:(CGPoint)velocity
              targetContentOffset:(inout CGPoint *)targetContentOffset

which lets the implementor provide a replacement offset to complete the animation with. What if the implementor can provide an alternate MGLCamera to animate to?

**Comment by 1ec5** [comment]
For starters, I’ve implemented the simplest possible API in #5584.

The camera-redirecting API proposed in https://github.com/mapbox/mapbox-gl-native/issues/2457#issuecomment-222051074 would be more complex both to implement and use effectively, but I’m not opposed to that design if we can make it work. The current mbgl transform API is the limiting factor right now.
