### ISSUE TITLE
Support prerender: true for other layer types

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#246]
We need to implement prerender support for other layer types:

* [ ] Composited (render all child layers, need to figure out what tile sizes to use?)
* [ ] Lines
* [ ] Icons? (probably not; may not make much sense)
* [ ] Text? (probably not; may not make much sense)

It doesn't make much sense to prerender icons, text and raster layers (the latter one is already "rendered").

**Comment by ansis** [comment]
prerender was killed https://github.com/mapbox/mapbox-gl-native/pull/769
