### ISSUE TITLE
Restructure Android TestApp

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2462]
As discussed with @bleege:

We need to make room in the sample app to allow more features to be showcased.
I will introduce the same pattern as with Raster.
 - refactor Activities into fragments*
 - make 3 sections in nav drawer
  - map options
  - map styles
  - map features

*exception of 2nd Map activity, this must remain in place for testing Activity lifecycle

**Comment by tobrun** [comment]
Doesn't it make more sense moving the MapFragment into the SDK itself?
- End developers can use this, instead of copy/paste inside their own project
- Google allows following integration possibilities
  - integrate MapView
  - integrate MapFragment

**Comment by tobrun** [comment]
Currently Fabric is created with Crashlytics in onCreate of MainActivity, going to move this to Application object instead

**Comment by ljbade** [comment]
@tobrun I had originally thought to do this, but not sure what @bleege thoughts are.

**Comment by tobrun** [comment]
@ljbade will wait for feedback from @bleege.
Need to add if metrics will land, we might be required to initialise something in Application object ourselves (for example starting LocationService). This pattern is common among other Android libraries, and Google Maps would do the same if they hadn't had Google Play Services.

**Comment by tobrun** [comment]
When moving between 'feature'-fragments the selected style, state compass/debug are persisted.

**Comment by tobrun** [comment]
Current progress on this [branch](https://github.com/mapbox/mapbox-gl-native/tree/2462-Restructure-Sample-App)

**Comment by tobrun** [comment]
The code is not finalised but gives an overview of possible improvements.
Need to do some testing on orientation change etc.
Would love to get some feedback and have :eyes: on the progress.

### Options are persistent 
If you enabled a option in one feature fragment than it will also be enabled in the other ones
  - style
  - debug mode
  - compass visibility

### Management Activity - Fragment: 
I had to introduce a layer between the MapFragment and the actual feature fragment. This fragment is responsible for following items:

- Fragment communication with activity - through interfaces
  - FloatingActionButtonDelegate
  - OnFpsChangedListener

- Communication from Activity to fragment
  - setMapStyle
  - toggleDebugMode
  - toggleCompass

Fab interaction is implemented similar to hasOptionsMenu(true) in the Android SDK. You call setHasFloatingActionButton(true) in onCreate and this will result in a callback for onCreateFAB(FloationActionButtonDelegate delegate). 


### Fragment package
I introduced packaging for fragment based on type of feature. This will make it easier to categorise the different features and will make it easier for the end developer to find a specific feature. This was one of the problems I had with the Raster SDK, hard to find the code you are actually interested in. 

![screen shot 2015-09-30 at 16 16 34](https://cloud.githubusercontent.com/assets/2151639/10195593/b3356ffc-678e-11e5-8075-d6f3fc625265.png)

**Comment by incanus** [comment]
Guiding principle on this app should be what we need for bare minimum feature testing. Don't think of it as a user-facing or demo app. On the iOS side, everything in the app is designed to test functionality (manual or automated) relating to core functionality of the library. We have guides, examples, and API docs for showing users how to use things. 

In short, don't overthink it :smile:

**Comment by bleege** [comment]
Yep, what @incanus said ^^ is :100: .  This is only to be used for development / testing / example code.

The [TestApp in the Raster SDK](https://github.com/mapbox/mapbox-android-sdk/tree/26d8857786856e5bd933ef6ad28b1d359b2a342a/MapboxAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/android/testapp) would be a good guide as it provides support for the key features here:

* Using MapView in a Fragment
* Using MapView in an Activity
* Navigation Drawer provides room to grow / add tests for future features

**Comment by tobrun** [comment]
Maybe I overthought the architecture on this is a bit, too much DRY and not enough KISS!

**Comment by tobrun** [comment]
To make it a bit simpler, I just refactored the MainActivity code into a separate Fragment. Result of this refactor is viewable in [this](https://github.com/mapbox/mapbox-gl-native/tree/2467-Restructure-Android-TestApp) branch. 

@bleege: we need to discuss base setup, the hosting Activity will always be bound to shown fragment (NavigationView) and as a result will introduce unneeded boiler plate. I think we need to drastically simplify the app OR introduce 2 apps (1 sample app and 1 test app).

**Comment by bleege** [comment]
I'm taking a look at the [2462-Restructure-Android-TestApp](https://github.com/mapbox/mapbox-gl-native/tree/2462-Restructure-Android-TestApp) per @tobrun's request earlier today.

**Comment by bleege** [comment]
I'm :+1: on this.  My only suggestion would be that we should some how note that the 2 top menu groups are related to the MainActivity, while the last menu group will continue to grow with standalone examples.  I think a basic heading of some sort would do.

![device-2015-10-07-151958](https://cloud.githubusercontent.com/assets/989928/10349966/046b6584-6d07-11e5-8d01-a53c9b6af9b8.png)

**Comment by tobrun** [comment]
@bleege was thinking the exact same, the UX currently doesn't add up..

**Comment by bleege** [comment]
@tobrun I've gotten the Navigation Drawer annotated with Titles now (Main Activity Controls, Main Activity Styles, Individual Tests) but am running into an issue with maintaining check state in the Main Activity Styles.  Specifically the default style that's selected (Streets currently) will be checked at app launch time and then when I tap on another (for example Dark) Dark will be selected but Streets will also stay selected.  This goes on until Streets is tapped itself and then future taps to other styles all produce the desired behavior (ie, only the tapped style stays checked).  I've tried a bunch of different options (removing state tracking in `MainActivity` via `mSelectedStyle`, removing the `android:checkableBehavior="single"` option and brute forcing things, etc) but none have worked.  I'm pushing the code up to GitHub so that you can take a look.  I must be missing something.  Anyway, hopefully your fresh :eyes: can help.  Thanks!

![device-2015-10-07-174316](https://cloud.githubusercontent.com/assets/989928/10353315/0a56ee0a-6d1b-11e5-8180-f4723528f180.png)

**Comment by ljbade** [comment]
@bleege That is a behaviour they changed in support library version 23. I noted it over in Sirius. To get old behaviour back you need to edit Gradle files to use version 22.

I have seen a few Google bug reports about this change but so far they have been ignored.

**Comment by bleege** [comment]
Thanks for the background @ljbade.  I couldn't find the link to bug report that you mentioned, but I was able to find the following.  It's related to 22.2 and not 23 so it seems like this issue has been around for awhile.

https://code.google.com/p/android/issues/detail?id=184089

Regardless, @tobrun and I discussed this and for the time being we'll disable the checkable behavior for Styles to avoid confusion.

@ljbade Can you attach the link to the bug reports that you're referring to to this ticket?  I want to make sure that we can track this going forward as well as make sure everyone knows / remembers why we ended up going this way.  Thanks!

**Comment by bleege** [comment]
Rebased, Merged, and Pushed.  Great job @tobrun!

**Comment by ljbade** [comment]
@bleege If I recall the bug in 23 came about as a result of them trying to fix that one in 22. You can see the change they made in the Android git repo.
