### ISSUE TITLE
Prerender at the beginning of a frame

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#247]
Currently, we prerender a tile bucket when we want to draw the prerendered bitmap, and see that it has not been prerendered yet. This requires pushing an FBO with the new texture, rendering everything, then popping the FBO, which requires another FBO load because we have previously drawn something to the main FBO. This is expensive on some platforms, like iOS.

While we don't prerender very often (only once per tile bucket), we should introduce a "prerendering pass" that is at the beginning of a render call. This means that we can first draw all textures required for the subsequent render passes, then discard/clear the base FBO to avoid reloading of the FBO contents.

**Comment by ansis** [comment]
removed in https://github.com/mapbox/mapbox-gl-native/pull/769
