### ISSUE TITLE
Annotation callout hides when map zooms/moves iOS

### ISSUE THREAD

**Issue by zuziakaxel** [mapbox/mapbox-gl-native#2479]
After zooming map (with selected (both programatically and manually) annotation) callout disappears and         
```
func mapView(mapView: MGLMapView, didDeselectAnnotation annotation: MGLAnnotation
```
is called.
Is there any way to turn off auto-deselecting annotation?

**Comment by friedbunny** [comment]
Tracking the callout view as the map is panned/zoomed is not implemented yet — see #1784.
