### ISSUE TITLE
Update layers/tiles while displaying

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#2481]
We should support updating tiles/layers while they are being displayed. This can happen when the tile data expires while it is still being displayed. It's also a prerequisite for #2445.

Prerequisites:
* [x] Complete #2103 so we can drop GL buffers of old tiles

Likely obstacles:
* Figure out how to safely swap out buffers
* Tile data lifetimes
* Should API work on a per-layer or a per-tile level? Maybe both?

**Comment by willwhite** [comment]
@kkaefer what is your latest thinking around how to decide when to refresh the map? Will this be triggered manually or could we keep track of all tiles that have an `Expires` header and force a refresh when that date is hit? This would let the server decide when/if data should be refreshed.

**Comment by kkaefer** [comment]
The idea of this feature is to respect the Expires/max-age headers the server sends.  We already do that today, but we never update a tile after it is being displayed. That means, that in situations where we display tiles or maps for a very long period of time, like in visualizations,  we will continue to show a tile despite it being outdated.  So ultimately, when we display a tile, we will also set a timer that will trigger a refresh once the server sent expires header is done.

**Comment by willwhite** [comment]
Gotcha, will it do the same for `max-age` or will the auto-refresh behavior be limited to `expires`?

**Comment by kkaefer** [comment]
On the client side, we calculate an absolute date when receiving the data, `Expires` will be taken verbatim; `max-age` will be added to the current time. After that, we don't discriminate between those two headers.

**Comment by kkaefer** [comment]
Subsumed by #2617.
