### ISSUE TITLE
Set Android To Be 2.0.0

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2486]
Android GL will be Mapbox for Android 2.0.0.  In order to make this happen we need to change the packaging on both the Maven artifact and root Java package to match what the Android Raster SDK uses.

* Maven Central
    * Group Id: `com.mapbox.mapboxsdk`
    * Artifact: `mapbox-android-sdk`
* Java root package name
  * `com.mapbox.mapboxsdk`

/cc @mapbox/mobile @mapbox/gl

**Comment by bleege** [comment]
Waiting for Travis to :+1: and then will merge.

**Comment by bleege** [comment]
Issue with `CompassView` during merge.  Need to fix.

**Comment by bleege** [comment]
Successfully published SNAPSHOT 1 as a test this afternoon.  It's from `master` and based on https://github.com/mapbox/mapbox-gl-native/commit/212c7ed8da899034561b94bbf0c962644d2885ff

https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-android-sdk/2.0.0-SNAPSHOT/

**Comment by bleege** [comment]
Discovered some issues with JNI not working with the new package naming conventions.

**Comment by bleege** [comment]
Built and pushed SNAPSHOT 2 after JNI fix.

https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-android-sdk/2.0.0-SNAPSHOT/

**Comment by ljbade** [comment]
@bleege Found you missed one reference in the SDK manifest file so `R` classes were still being generated in the old `mapboxgl` package.

Making PR.

**Comment by brunoabinader** [comment]
We've been using `git describe --tags --abbrev=0 |cut -dv -f2 |cut -d- -f1` to obtain the current _version_ of Mapbox GL in some occasions. Previous one was `2.1.0`, any reason why not going for `2.2.0` instead of `2.0.0`?

**Comment by ljbade** [comment]
@brunoabinader Hmm you need to be careful both iOS, Android, and node has independent version tags.

**Comment by kkaefer** [comment]
Referencing #2430

**Comment by bleege** [comment]
@brunoabinader There's also a difference between Core GL and the Binding version names / numbering.
