### ISSUE TITLE
make clean shouldn't delete Xcode workspaces

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#2493]
I fixed this at one point but it seems to have regressed. Having `make clean` delete Xcode workspaces is annoying because it means your schemes get blown away, which includes the `MAPBOX_ACCESS_TOKEN` environment variable.

**Comment by mikemorris** [comment]
I think this was intentional because finding the hidden `MAPBOX_ACCESS_TOKEN` in Xcode was a pain for folks not familiar with it, but it was originally in `distclean` instead of `clean`.

**Comment by 1ec5** [comment]
iosapp should prompt for an access token at launch if it's absent from the environment and user defaults, just like osxapp does.

**Comment by 1ec5** [comment]
Filed #4696 for prompting for an access token.

**Comment by 1ec5** [comment]
As of #4641, ios.xcworkspace is checked in, so you can set the `MAPBOX_ACCESS_TOKEN` environment variable on a non-gyp-generated scheme (such as iosapp, ios-bench, CI, or a duplicate of a GYP-generated scheme), and that variable will persist even if you delete and regenerate platform.xcodeproj.

/cc @kkaefer @boundsj @friedbunny

**Comment by friedbunny** [comment]
We’ll have to be careful to not check in access tokens:

```diff
diff --git a/platform/ios/ios.xcodeproj/xcshareddata/xcschemes/iosapp.xcscheme b/platform/ios/ios.xcodeproj/xcshareddata/xcschemes/iosapp.xcscheme
index 064add0..802daeb 100644
--- a/platform/ios/ios.xcodeproj/xcshareddata/xcschemes/iosapp.xcscheme
+++ b/platform/ios/ios.xcodeproj/xcshareddata/xcschemes/iosapp.xcscheme
@@ -61,6 +61,13 @@
             ReferencedContainer = "container:ios.xcodeproj">
          </BuildableReference>
       </BuildableProductRunnable>
+      <EnvironmentVariables>
+         <EnvironmentVariable
+            key = "MAPBOX_ACCESS_TOKEN"
+            value = “pk.dodododoodbobodbdobdodboiebdoobiedoobiedo.blahbalh"
+            isEnabled = "YES">
+         </EnvironmentVariable>
+      </EnvironmentVariables>
       <AdditionalOptions>
       </AdditionalOptions>
    </LaunchAction>
```

**Comment by jfirebaugh** [comment]
We can probably change `make clean` back to a simple `rm -rf build/*` now.

**Comment by jfirebaugh** [comment]
> We’ll have to be careful to not check in access tokens:

Should we _not_ mark the `iosapp` and `osxapp` schemes as shared, to avoid this? It looks like the only schemes that need to be shared are `CI`, `dynamic`, and `static`.

**Comment by jfirebaugh** [comment]
#4737
