### ISSUE TITLE
UserLocationAnnotationView's radius is different in the near and far.

### ISSUE THREAD

**Issue by conpota** [mapbox/mapbox-gl-native#2499]
Circle is same in the near and far.
![near2](https://cloud.githubusercontent.com/assets/135109/10236549/bd27a12a-68e1-11e5-881e-91d875993e54.png)
![far2](https://cloud.githubusercontent.com/assets/135109/10236552/c286e644-68e1-11e5-8b2a-196fc36c9e38.png)

**Comment by incanus** [comment]
Captured in https://github.com/mapbox/mapbox-gl-native/issues/2186#issuecomment-139633343.

**Comment by 1ec5** [comment]
This behavior is inconsistent with other annotations as well as POIs on the map. On the other hand, it ensures the user dot remains prominent no matter how far back it is. In addressing this issue, it'll be useful to have a function that computes the scale of a feature at a given distance away from the viewpoint.

**Comment by 1ec5** [comment]
The saga continues in #5040.

**Comment by boundsj** [comment]
To expand on what @1ec5 said, once the user dot annotation is an annotation view (https://github.com/mapbox/mapbox-gl-native/issues/5039) and is customizable by the application developer (https://github.com/mapbox/mapbox-gl-native/issues/5037) then the implementation to address https://github.com/mapbox/mapbox-gl-native/issues/5040 (default scale with API to not scale) will fix this bug.

**Comment by 1ec5** [comment]
We'd probably want the user dot to scale by default; otherwise, the accuracy halo can be inaccurate whenever it's away from the center of the view.
