### ISSUE TITLE
Support layers with extent != 4096

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#250]
We currently hard code the assumption that vertices in a layer span the extent of 0..4096. This may not be true for all tiles, so we should either make our renderer aware of that, or normalize vertices to that extent when decoding layers that specify a different extent.

**Comment by bsudekum** [comment]
I'm seeing a lot of errors coming up from tiles generated in [tippecanoe](https://github.com/mapbox/tippecanoe) as the default setting is not 4096.

@kkaefer has there been any headway on this issue?

**Comment by kkaefer** [comment]
No
