### ISSUE TITLE
Add OnMapClickListener and OnMapLongClickListener

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2507]
For parity with Google Maps API and OnMarkerClickListener/OnInfoWindowClickListener.

**Comment by ljbade** [comment]
@bleege If we finish the other v2.1.0 tickets I think we should add this. Currently TestApp and Sirius have to override onTouchEvent to detect a long click for adding a marker, whereas this provides an easier to use method similar to Google Maps.

I will push the changes to a branch but not merge for the moment.

**Comment by bleege** [comment]
@ljbade Since this one was already in progress, let's go ahead and push it into `master` now.  I'll switch it to `android-v2.1.0` and we can go from there.  Please merge it ASAP.  Thanks!

**Comment by bleege** [comment]
@ljbade Actually, after looking at this it was already merged into `master` via #2529.  It should have been switched to `android-v2.1.0` already so that we knew about this.  Gotta be careful!

**Comment by ljbade** [comment]
@bleege Yeah I forgot to change it!
