### ISSUE TITLE
 the map display black,is a bug?

### ISSUE THREAD

**Issue by zochunhua** [mapbox/mapbox-gl-native#2513]
test android phone: xiaomi HM note 1TD
android version:  4.2.2 

![screenshot_2015-10-02-22-35-22](https://cloud.githubusercontent.com/assets/3861966/10249297/17f8f4e4-6957-11e5-8504-43f830f86530.png)

**Comment by bleege** [comment]
@zochunhua Thanks for reporting this.  Does the code above set a map style?  It not this is a known issue in #2463.

**Comment by tobrun** [comment]
@zochunhua 
Are you still having the problem with current release? 
What version of the library are you using?

**Comment by ljbade** [comment]
@zochunhua Can you try https://github.com/mapbox/mapbox-gl-native/pull/2810 to see if it fixes this issue?

**Comment by bleege** [comment]
Duplicated in #2802 with work being tracked on that ticket.

**Comment by zochunhua** [comment]
Now, the map display normal
![screenshot_2015-10-29-08-55-55](https://cloud.githubusercontent.com/assets/3861966/10807595/46055056-7e1c-11e5-8f3c-b688421942fe.png)

**Comment by bleege** [comment]
Awesome!  Thanks for testing @zochunhua!

**Comment by zochunhua** [comment]
now display black!@bleege
![screenshot_2016-04-25-14-19-51_com mapbox mapboxsdk testapp](https://cloud.githubusercontent.com/assets/3861966/14775369/4fc14854-0af1-11e6-9bab-b9a7ff368b2f.png)

**Comment by bleege** [comment]
@zochunhua Can you tell us what version of the Mapbox Android SDK the app is using, what style is trying to be set, and confirm that the Access Token is being set?  Thanks!

**Comment by tobrun** [comment]
@zochunhua we are looking into this issue in #4779
