### ISSUE TITLE
Modifying annotation should not require removing it and adding it again (iOS)

### ISSUE THREAD

**Issue by futureshape** [mapbox/mapbox-gl-native#2517]
Currently, the only way to get the map to show changes in an annotation (especially its image) is is to remove it and add it again i.e. 

```
[self.mapView removeAnnotation:annotation];
[self.mapView addAnnotation:annotation];
```

This causes flickering (see #1688) but also has the side effect of de-selecting an annotation that was previously selected by the user. There is a workaround for this:

```
BOOL annotationWasSelected = [self.mapView.selectedAnnotations containsObject:annotation];
[self.mapView removeAnnotation:annotation];
[self.mapView addAnnotation:annotation];
if(annotationWasSelected) [self.mapView selectAnnotation:annotation animated:false];
```

But ideally it should be possible to modify an annotation is a simpler way.

**Comment by 1ec5** [comment]
Related to #1980, which is about moving the annotation.

**Comment by RomainQuidet** [comment]
related to #2210 
Solved by pull request #3146 
Waiting for code review.
annotation will be updated by modifying its annotationImage.image property which is no more read only (based on native MapKit interface)

**Comment by 1ec5** [comment]
This was fixed in #3146 and will be in the next release.

**Comment by t-yoshii** [comment]
Does #3146 also fix to allow annotation coordinate to be updated?

**Comment by 1ec5** [comment]
Oh you're right, that hasn't been addressed yet.

**Comment by jfirebaugh** [comment]
#1980 is related / could be considered a duplicate.

**Comment by 1ec5** [comment]
OK, duplicate of #1980.
