### ISSUE TITLE
Create Android 2.1.0 release branch

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2518]
Next steps after #2515 to create `release-android-v2.1.0` branch:
- start with `release-android-v2.0.0-redo-working`
- cherry pick:
- https://github.com/mapbox/mapbox-gl-native/commit/92b0ddec267f209172a10e5b5c08563f1b186966
- https://github.com/mapbox/mapbox-gl-native/commit/73a3377d56febd114ce014bdfe29f19ae3836722
- https://github.com/mapbox/mapbox-gl-native/commit/44f9ebdaec381511d5b491fc335ae3c6c67c9b2b
- https://github.com/mapbox/mapbox-gl-native/commit/343419634f8292a1ba5158635e39bccb25ab67a5
- https://github.com/mapbox/mapbox-gl-native/commit/206f9f2258410c98ea492aacde73f5b7c691c63a
- https://github.com/mapbox/mapbox-gl-native/commit/cdf38ff1384b45c99a956a36b004666196642d8d
- https://github.com/mapbox/mapbox-gl-native/commit/623fec368718608c76c457197b2ddf69f7837fba
- https://github.com/mapbox/mapbox-gl-native/commit/02bc2bd7bef98f330356c30562038813b22a0fdc

@bleege Check that list to see if it is right. Another cleaner alternative would be to just branch current master to v2.1.0

**Comment by bleege** [comment]
As discussed earlier today `2.1.0` will start from `master`.  This means that all work on the `android-2.1.0` milestone should be merged to `master` when completed.

We'll look to create a `release-android-v2.1.0` branch when we get closer to release so that it can have as short of TTL as possible.

/cc @incanus @jfirebaugh @tobrun

**Comment by ljbade** [comment]
@bleege Sounds like a great plan. For next 3 weeks we will only commit Android changes to master that directly relate to the open 2.1.0 tickets, everything else can sit in branches and be merged once 2.1.0 is out the door.

**Comment by bleege** [comment]
@ljbade :+1:

**Comment by ljbade** [comment]
Closing for now.
