### ISSUE TITLE
Map should centre on marker when clicked

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2520]
Currently the default marker click action just shows the `InfoWindow`. To match Google Maps we should also initiate an animated scroll to centre the marker in the map.

However this is not currently possible as we hide the `InfoWindow` in response to a scroll because we haven't yet implemented InfoWindow tracking.

**Comment by tobrun** [comment]
I had this in place for #2273 but was held off due to focus on other [things](https://github.com/mapbox/mapbox-gl-native/issues/2273#issuecomment-143787796) first.

**Comment by ljbade** [comment]
@tobrun Excellent!

**Comment by tobrun** [comment]
I believe that this is not on our current list of requirements.
Technically this is possible. Closing for now.
