### ISSUE TITLE
Spurious wakeups

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#2522]
We're using `std::condition_variable` to ensure `MapContext` pauses. However, [`wait()`](http://en.cppreference.com/w/cpp/thread/condition_variable/wait) sometimes spuriously wakes up without having received an actual notification. In other words, there is no 1:1 mapping between a `notify` call and a `wait` being canceled. We should add a boolean state variable as shown in the example to make sure that we don't unpause too early.

/cc @ljbade @bleege

**Comment by ljbade** [comment]
Interesting find @kkaefer. Going to make a PR.

**Comment by ljbade** [comment]
Moving `paused` to `MapData` and use this as the predicate for both waits.

**Comment by ljbade** [comment]
I managed to simplify the code to use only one condition variable.

**Comment by ljbade** [comment]
@kkaefer Notes I need to add some extra locks.

**Comment by ljbade** [comment]
@kkaefer I merged a fix for the missing locks.
