### ISSUE TITLE
Toolbar title in Android Sample app alignment bug

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2523]
In landscape mode the title is not vertically aligned in the Toolbar:

https://code.google.com/p/android/issues/detail?id=77874

<img width="706" alt="screen shot 2015-10-05 at 14 30 16" src="https://cloud.githubusercontent.com/assets/2151639/10280457/aba8210c-6b6d-11e5-80d8-4c9ee203bec9.png">

Replace:
> android:minHeight="?attr/actionBarSize"

with:
> android:layout_height="?attr/actionBarSize"

**Comment by ljbade** [comment]
@tobrun Can you PR this?

**Comment by ljbade** [comment]
Also check Sirius, might have same error.
