### ISSUE TITLE
Move MapFragment from Test to SDK module 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2524]
Integrating GoogleMaps into a project is generally done using their [MapFragment](https://developers.google.com/android/reference/com/google/android/gms/maps/MapFragment?hl=en). 
See this [getting started guide](https://developers.google.com/maps/documentation/android-api/map) for reference.

In those cases you will extend MapFragment and hook into the [getMapAsync](https://developers.google.com/android/reference/com/google/android/gms/maps/MapFragment.html#getMapAsync(com.google.android.gms.maps.OnMapReadyCallback)) callback to get a GoogleMap object and then start customising the map with markers etc. On older implementations they exposed a getMap method but this has been deprecated. 

To make it easier for end developers to setup or migrate:
 - move MapFragment up the hierarchy into the SDK itself.
 - expose both getMapAsync and getMap (deprecated)
 - automatically load accessToken through Android resources

**Comment by ljbade** [comment]
Hmm I'd just implement `getMap`, until when/if we actually support it (see https://github.com/mapbox/mapbox-gl-native/issues/2042)

accessToken changes are being discussed in https://github.com/mapbox/mapbox-gl-native/issues/713

We might want to hit this at the same time we implement the general refactor in https://github.com/mapbox/mapbox-gl-native/issues/2480

Then we can just make `MapView` and `MapFragment` simple shim's to handle the lifecycle methods and both have `getMap`.

**Comment by ljbade** [comment]
At the same time also need to add a `SupportMapFragment` to support people using Android support library.

**Comment by ljbade** [comment]
Another important part of Google Map API is the `useViewLifecycleInFragment` option. This enables the map to stay loaded in memory when a fragment is detached. It has been requested before in https://github.com/mapbox/mapbox-gl-native/issues/2042

**Comment by tobrun** [comment]
@ljbade  :+1: 

About:
>useViewLifecycleInFragment

This will probably be a retained fragment, but to clarify this only will keep the map data in memory, views will always be destroyed/recreated.

**Comment by ljbade** [comment]
@tobrun Interesting I guess that's why the `GoogleMap` object exists. It can out live the `View` it is attached to.

**Comment by tobrun** [comment]
Closing, implemented in #2567
