### ISSUE TITLE
Removing legacy token.txt 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2526]
Currently we are loading the access token by reading the token.txt file in the raw folder.

I have 2 suggestions to make this process more Android developer friendly:
 - migrate token to res/config.xml into a non-translatable String resource
 - migrate token to AndroidManifest into a meta-data tag

This change is needed for #2524 due to possibility of resource merging/overriding.

**Comment by jfirebaugh** [comment]
Ref #713 for previous discussion about Android access token mechanism.

**Comment by tobrun** [comment]
@jfirebaugh thank for referencing, will continue discussion there
