### ISSUE TITLE
Align annotation rotation and pitch with map

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#2528]
Annotations maintain their perspective even as you rotate and pitch the map. But sometimes you want an annotation to stay fixed, so that it rotates and tilts with the map. A contrived example would be an arrow that points in a particular direction – you’d want the direction to be in sync with the map’s direction.

/cc @incanus @ansis

**Comment by incanus** [comment]
Meaning symbols, not shapes. Another related issue here is raster ground overlays, as they're called in other frameworks, which work similarly to the not-yet-ported-here `video` source type — rectangles or other polygons of outside material stuck to the panning, zooming, rotating map.

**Comment by incanus** [comment]
Sorry, I do mean rasters here, not vector-drawn shapes in geo terms as a hack to stick things to the map. 

Here is a good illustrative example from another toolkit: 

![](https://www.nutiteq.com/media/Ground_overlay_example.png)

**Comment by ansis** [comment]
This can be done internally by setting the "icon-rotation-alignment" style property to "map" instead of the default "viewport". I'm not sure how you want to expose the option though

**Comment by 1ec5** [comment]
If it were just about point annotations, I’d say we could add a `rotates` property to `MGLAnnotationImage`. But we don’t have an equivalent interface for overlays, so we’ve been cramming methods into MGLMapViewDelegate for various sundry overlay properties. I’m hesitant to keep doing that.

**Comment by aksonov** [comment]
@1ec5 Could you check that commit https://github.com/mapbox/react-native-mapbox-gl/pull/280/commits/bbb704091f4671e1a875acdc292e325d875afbfa ? It adds 'rotatedImage!' with rotation param.

**Comment by 1ec5** [comment]
mapbox/react-native-mapbox-gl#280 modifies an MGLAnnotationImage’s image to compensate for the map’s rotation. That approach breaks down as soon as the map is rotated, whether programmatically or due to a user gesture.

We don’t intend to support this feature for MGLAnnotationImage right now. Instead, we should implement a new property on MGLAnnotationView (#4801) that causes it to ignore the map’s rotation, similar to #5085 and #5067.

For non-view-backed point annotations, we’re waiting on #837 to enable full styling of arbitrary features on the map; once that works, it’ll be trivial to keep a point annotation from rotating using the approach outlined in https://github.com/mapbox/mapbox-gl-native/issues/2528#issuecomment-175846495, no transforms needed.

**Comment by 1ec5** [comment]
> For non-view-backed point annotations, we’re waiting on #837 to enable full styling of arbitrary features on the map; once that works, it’ll be trivial to keep a point annotation from rotating using the approach outlined in https://github.com/mapbox/mapbox-gl-native/issues/2528#issuecomment-175846495, no transforms needed.

Use the [`MGLSymbolStyleLayer.iconRotationAlignment`](https://www.mapbox.com/ios-sdk/api/3.6.2/Classes/MGLSymbolStyleLayer.html#/c:objc%28cs%29MGLSymbolStyleLayer%28py%29iconRotationAlignment) property to make the icon’s rotation match the map. mapbox/mapbox-gl-native#9479 implements an `iconPitchAlignment` property for matching the map’s pitch; it’ll be in the next release (tentatively versioned v3.7.0).
