### ISSUE TITLE
Map zoom control UI

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2537]
Considering we provide several other pieces of default UI (compass, logo, attribution button), we should we also provide a default zoom control UI.

Google Maps provides this. Not sure about MapKit.

**Comment by friedbunny** [comment]
Neither Apple nor Google provide stock zoom controls for their iOS SDKs — perhaps because excellent touch response is a given.

**Comment by ljbade** [comment]
@friedbunny Interesting, perhaps we will only need this on Android.

**Comment by ljbade** [comment]
Technically it is possible to get a one or no touch device on Android. Android API supports that at least. Perhaps when you plug a mouse into one of those Android on a USB stick computers.

**Comment by ljbade** [comment]
@tobrun what are you thoughts for this?

**Comment by mb12** [comment]
I thought the sdk automatically adds a zoom control if the device isn't multi touch capable.  Never tested it though.
https://github.com/mapbox/mapbox-gl-native/blob/master/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L636

**Comment by tobrun** [comment]
Yeah we could definitely add one. Would make it easier to test on emulator.
I have a Android USB stick laying around here somewhere.
@ljbade what are those ZoomControls @mb12 is talking about?

**Comment by ljbade** [comment]
@tobrun if you look for `ZoomControls` in `MapView` you will see there are some backup zoom controls added when the device reports as being "one finger" touch only. Which apparently the emulator lies about.

Last time I tested it (well over a year) these zoom controls looked like they were straight from Android 2.0 design wise and hadn't been updated.

We should replace them with our own and add a `MapView` property to turn them on and off.

**Comment by ljbade** [comment]
@tobrun it is actually `ZoomButtonsController`

Here is a screenshot after forcing the zoom controls on:
![device-2015-11-02-150925](https://cloud.githubusercontent.com/assets/1215089/10874190/ed81970e-8173-11e5-9ca3-2dd1894d8d68.png)

You can see they are Android 2.0 looking and not in the best location.

**Comment by tobrun** [comment]
These buttons are in place and can be activated by calling `mMapView.setZoomControlsEnabled(true)`

**Comment by mrameera** [comment]
i want the code please

**Comment by mrameera** [comment]
full project code please
