### ISSUE TITLE
Use single package for SDK

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2538]
There are a number of public functions and constructors (particularly in the annotations API) that should be made package private.

For example all the `set...` functions in `Marker` etc since these objects should currently be immutable. Calling these functions after `addMarker` etc will not update the marker on the map. Even worse `setId` will completely break things.

To make these package private we need everything in one package (annotations and view). The other packages I think we can leave alone at this stage.

**Comment by tobrun** [comment]
Linking #2480 because I feel that this should be tackled simultaneously

**Comment by ljbade** [comment]
I am proposing merging the annotations and views packages, perhaps just putting them under the base package. Google Maps API seems to happily keep everything in one package.

**Comment by ljbade** [comment]
@tobrun @bleege @zugaldia Are there Java patterns for exposing private implementation detail to other packages, but not to the public? Google Maps API must be doing this, along with the Android framework.

**Comment by ljbade** [comment]
Hmm a solution might be to create a public interface in a "internal" package, which exposes the implementation methods. Create a private inner class implementation of this in MapView, then pass this in the constructor or some such.

**Comment by tobrun** [comment]
> To make these package private we need everything in one package (annotations and view). The other packages I think we can leave alone at this stage.

This is the current situation, this might change with #3485 but will close this for now.
