### ISSUE TITLE
Organise annotations function definitions

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2539]
While working on #2002 I noticed the `MapView` annotation functions need a bit of a tidy up as they do not follow a logical pattern.

E.g. `addMarker` is the only function that takes a `Marker` object directly not a `...Options` object. Important for this API which is supposed to take a mutable object and return a immutable object (#2538 will need this).

I made a pass at fixing this and will push to a branch.

**Comment by ljbade** [comment]
@bleege @tobrun Can you take a look at https://github.com/mapbox/mapbox-gl-native/commit/fdcef9a60cd17e7e70e268a59d169b5de3ae4023

I think we will want this in 2.1.0 to avoid a breaking change to the API in 2.2.0

**Comment by ljbade** [comment]
Doing some testing and noticed we get crash due to unmodifiable lists. Will convert everything to use normal lists and make `getAllAnnotations` return a shallow copy to `mAnnotations`.

**Comment by tobrun** [comment]
Ah addMarkers should use a List of MarkerOptions, my bad!

Just one remark to the commit: 
there is a legitimate reason why I was doing this 
```java
Marker m;
int count = markers.size();
for (int i = 0; i < count; i++) {
   m = markers.get(i);
   m.setId(ids[i]);
   m.setMapView(this);
   mAnnotations.add(m);
```
Instead of:
```java
for (int i = 0; i < markers.size(); i++) {
    markers.get(i).setId(ids[i]);
    markers.get(i).setMapView(this);
    mAnnotations.add(markers.get(i));
}
```

The whole reason behind this is that this code needs to be scalable,  eg iOS sample is adding 1000 markers. In second code snippet this will result in a lot of garbage objects while in first snippet this will not.  

Jake Wharton has created a nice [presentation](https://www.youtube.com/watch?v=b6zKBZcg5fk) on this subject.

**Comment by ljbade** [comment]
@tobrun Ah interesting. I'll copy your code to the other methods then.

I also optimised our `ArrayList` constructors to pre-allocate the correct amount of memory.

**Comment by ljbade** [comment]
@tobrun I changed to use the faster for loop for markers, and polylines.

I changed to use shallow List copies.

Finally I renamed `getAnnotationsInBounds` to `getMarkersInBounds` and changed the code that uses it to talk about "markers" instead of "annotation" just to make it clearer that we only consider markers when selecting.

**Comment by ljbade** [comment]
Changed the milestone as I think this is something we should get in to v2.1.0 so that I can JavaDoc the tidier functions.
