### ISSUE TITLE
Xcode7 : Build fails because Mapbox.framework/Mapbox (No such file or directory)

### ISSUE THREAD

**Issue by dagatsoin** [mapbox/mapbox-gl-native#2540]
Under Xcode7, iphone 4S(9.0.2)

The build fails because this error:
```
PhaseScriptExecution Embed\ Pods\ Frameworks /Users/vikti/Library/Developer/Xcode/DerivedData/MapboxGLNative-ebsodbjqtnvumbhinxhtraqlvmne/Build/Intermediates/MapboxGLNative.build/Debug-iphoneos/MapboxGLNative.build/Script-E842C7E292798862804E5841.sh
    cd /Users/vikti/dev/MapboxGLNative
    /bin/sh -c /Users/vikti/Library/Developer/Xcode/DerivedData/MapboxGLNative-ebsodbjqtnvumbhinxhtraqlvmne/Build/Intermediates/MapboxGLNative.build/Debug-iphoneos/MapboxGLNative.build/Script-E842C7E292798862804E5841.sh

mkdir -p /Users/vikti/Library/Developer/Xcode/DerivedData/MapboxGLNative-ebsodbjqtnvumbhinxhtraqlvmne/Build/Products/Debug-iphoneos/MapboxGLNative.app/Frameworks
rsync -av --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/vikti/Library/Developer/Xcode/DerivedData/MapboxGLNative-ebsodbjqtnvumbhinxhtraqlvmne/Build/Products/Debug-iphoneos/Pods/Mapbox.framework" "/Users/vikti/Library/Developer/Xcode/DerivedData/MapboxGLNative-ebsodbjqtnvumbhinxhtraqlvmne/Build/Products/Debug-iphoneos/MapboxGLNative.app/Frameworks"
building file list ... done
Mapbox.framework/

sent 115 bytes  received 26 bytes  282.00 bytes/sec
total size is 726  speedup is 5.15
Code Signing /Users/vikti/Library/Developer/Xcode/DerivedData/MapboxGLNative-ebsodbjqtnvumbhinxhtraqlvmne/Build/Products/Debug-iphoneos/MapboxGLNative.app/Frameworks/Mapbox.framework with Identity iPhone Developer: Hihfhku Dubois (R6R7QJ66NV)
/usr/bin/codesign --force --sign BE6ED7B69BD84EBCE631F9FB70227C899DE43C03 --preserve-metadata=identifier,entitlements "/Users/vikti/Library/Developer/Xcode/DerivedData/MapboxGLNative-ebsodbjqtnvumbhinxhtraqlvmne/Build/Products/Debug-iphoneos/MapboxGLNative.app/Frameworks/Mapbox.framework"
/Users/vikti/Library/Developer/Xcode/DerivedData/MapboxGLNative-ebsodbjqtnvumbhinxhtraqlvmne/Build/Products/Debug-iphoneos/MapboxGLNative.app/Frameworks/Mapbox.framework: replacing existing signature
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: can't open file: /Users/vikti/Library/Developer/Xcode/DerivedData/MapboxGLNative-ebsodbjqtnvumbhinxhtraqlvmne/Build/Products/Debug-iphoneos/MapboxGLNative.app/Frameworks/Mapbox.framework/Mapbox (No such file or directory)

```

**Comment by 1ec5** [comment]
Is that the full build log? Are there any other errors further up?

**Comment by dagatsoin** [comment]
I edit to add some logs.

No, this is the only error.

**Comment by 1ec5** [comment]
It looks like you’re using CocoaPods and the pods haven’t built. Just to be sure, are you building the right scheme inside your .xcworkspace (as opposed to the standalone .xcodeproj)?

**Comment by dagatsoin** [comment]
What do you mean exactly by scheme? I have double clicked on the .xworkspace to build the app.
Excuse me but Xcode environment is new for me.

**Comment by 1ec5** [comment]
A scheme is a set of targets (say, the Mapbox iOS SDK library plus your application) that gets built together in the workspace. The scheme picker is to the right of the Stop button in the toolbar. If you followed the [CocoaPods installation instructions on our website](https://www.mapbox.com/ios-sdk/#cocoapods), it should be set to the correct scheme.

Do any errors or warnings appear in the Issues navigator (left sidebar)?

<img width="260" alt="Issues navigator" src="https://cloud.githubusercontent.com/assets/1231218/10317522/aac394fe-6c19-11e5-91ec-d2aa1ea76fac.png">

Feel free to attach a screenshot of the issues you see.

**Comment by dagatsoin** [comment]
I modified cocoa pods instruction to this because I had the bitcode issue https://github.com/mapbox/mapbox-gl-native/issues/2205#issuecomment-136175220
```
pod 'Mapbox-iOS-SDK'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

use_frameworks!
```
Here is the screenshot
![xcode](https://cloud.githubusercontent.com/assets/3670794/10317843/a861646e-6c66-11e5-9cf9-cee407feb25e.jpg)

**Comment by 1ec5** [comment]
Sorry for the game of 20 Questions here. The error you’re seeing indicates that a dependency (in this case, the dynamic framework that CocoaPods wraps the Mapbox.a static library in) didn’t get built for some reason. Since you aren’t seeing any errors from the Pods target in the issue navigator, let’s verify that Xcode is even building that target in the first place. Can you clean your build products (⌥⇧⌘K), try building again, then screenshot the following?

* The Report navigator (last left sidebar).
* The “Pods” section of the Project navigator (first left sidebar), expanded so we can see the Pods/Mapbox-iOS-SDK folder and the Products folder in there.

Lastly, what version of CocoaPods do you have?

**Comment by dagatsoin** [comment]
No problem for the step by step game :) I am very good at it.

I have clean the build and re rebuild and it works like a charm ! It is something I will never find myself, so thank you very much @1ec5

**Comment by 1ec5** [comment]
Ah, good to hear! I usually say ⌥⇧⌘K, but “hold down Option and go to Products ‣ Clean Build Folder” is probably easier to remember, even if it’s a bit of a mouthful.
