### ISSUE TITLE
Make Annotation objects immutable

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2546]
In the various annotation objects (`Marker` etc) we have a number of `set...` functions. These need to be removed so that they are immutable for the moment.

Main reason is the expected behaviour from developers is that for example `Marker.setColor()` will change the existing marker's colour. Instead nothing happens.

Full support for mutable annotations is not in the core layer at this stage. Even on iOS you can't update existing markers.

@bleege I think this is good candidate for 2.1.0

**Comment by bleege** [comment]
@ljbade Sounds good.  How about just commenting them out?

**Comment by ljbade** [comment]
@bleege I'm not a huge fan of commenting code out. core/iOS seem to avoid commented code but we are getting it scattered in Android.

I think correct fix here is to make them package private so the `MarkerOptions` class can still use set.

**Comment by bleege** [comment]
@ljbade Can you help me understand how making them package private so that `MarkerOptions` can still use them solves this issue?  I'm just confused as the original recommendation was "These need to be removed so that they are immutable for the moment."

**Comment by ljbade** [comment]
@bleege I mean immutable in the "public API". in #2551 you say we should prefer to use `set` methods over field access. Package private means `MarkerOptions` can use them to create the `Marker` object, but once we return the `Marker` object to the end developer, they can't make any further changes to the object.

**Comment by ljbade** [comment]
@bleege I also noticed that some of the annotation object expose properties from Google Maps API we don't support in core. These should be made private.

**Comment by ljbade** [comment]
Fixing up a few other things I noticed:
- mark `Marker`, `Polygon` `Polyline` as `final`.
- mark `Annotation`, `AnnotationOptions`, `MultiPoint` and `MultiPointOptions` constructors `protected`.
- change `Circle` and `CircleOptions` to package private as they are currently unimplemented in native layer

**Comment by ljbade** [comment]
Hmm looks like MapView needs to be able to set the ID field on the objects. We might have to implement #2538

**Comment by ljbade** [comment]
Current WIP is in https://github.com/mapbox/mapbox-gl-native/tree/2546-fix-annotations

**Comment by ljbade** [comment]
Moving this to 2.2.0 as I don't think we have enough time to make all these changes. It is looking like the next version will include a number of refactors anyhow.

@bleege Do you agree?

**Comment by ljbade** [comment]
On second thought now that we have #2631 I might as well roll a fix for that into this branch.

**Comment by ljbade** [comment]
Pending https://github.com/mapbox/mapbox-gl-native/issues/2538 I have marked all the public methods that should only be used internally by the SDK with JavaDoc that says "Do not use this X. Used internally by the SDK."

Only way to prevent this is to move to a single package SDK.

**Comment by ljbade** [comment]
This branch ended up being quite a bit of work.

Full details in the PR.

**Comment by bleege** [comment]
@ljbade This is a LARGE change and rushing it doesn't make sense.  Let's put this back into `android-v2.2.0` so that we have time to test it properly.

**Comment by ljbade** [comment]
Further work could be to make setId/getId, set/getMapView etc private by directly accessing them in JNI where needed.

To do this nativeAddMarker could be refactored to take a MarkerOptions and return a Marker.

**Comment by ljbade** [comment]
Going to need to remove anchor per https://github.com/mapbox/mapbox-gl-native/issues/2652 in this 2.2.0 PR.
