### ISSUE TITLE
Extraneous one-way arrows on tile boundaries

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#2547]
Even after merging #2530, there will be one-way arrows on tile boundaries that appear too close to one-way arrows from adjacent tiles, ignoring any symbol spacing those arrows are supposed to respect.

![bumper boxes](https://cloud.githubusercontent.com/assets/1231218/10323396/9f3f681a-6c37-11e5-85f3-3d1601b79c3b.png)

This happens at any zoom level above z15 due to overscaling.

It’s probably infeasible to share information about anchor points between tiles, so `getAnchors()` should avoid placing any anchors too close to the tile boundary.

/cc @nickidlugash @ansis

**Comment by ansis** [comment]
I'm not seeing this anymore. I think it might have been fix by a combination of 0fda834397b5d937fb5843143ae8df8b27dd8954 and d9244cc973cacb454960838287c8c47482b20e34
Reopen if you see it again.
