### ISSUE TITLE
Add a location listener

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2549]
Currently the app can poll `getMyLocation` but we should have a location listener.

**Comment by tobrun** [comment]
I need to this for User tracking sample.

Location is always null in onCreate method.
```java
    Location location = mMapView.getMyLocation();
    if (location != null) {
         mMapView.setZoomLevel(8);
         mMapView.setCenterCoordinate(new LatLng(location));
     }
}
```

 Required to listen async to location updates.

**Comment by ljbade** [comment]
@tobrun should be easy to whip up then, move this to 2.1.0?

**Comment by ljbade** [comment]
@tobrun this will be in my UserLocationView refactor
