### ISSUE TITLE
Encapsulate Marker position and sprite

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2551]
As #2535 showed us bad things can happen when field level access to Java objects is allowed.  Let's double back and tighten this up.  In order to do this we're going to have to first [refactor the JNI bindings as described](https://github.com/mapbox/mapbox-gl-native/issues/2535#issuecomment-146243307).

Going forward let's all @mapbox/mobile try to use the stock Java get/set encapsulation construct when possible.  It'll help with automated testing when that rolls around as well as make life a little less dangerous.

**Comment by ljbade** [comment]
@bleege I'll hit moving the other `...Options` classes to use get/set in the PR for #2546. Will keep an eye out for other JNI gremlins too.

**Comment by ljbade** [comment]
Landed in #2592

**Comment by bleege** [comment]
Updated to `android-v2.1.0` as this was done early.
