### ISSUE TITLE
Support 10000 Annotations In Android

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2552]
iOS has the ability to parse and render 10000 Annotations at a time.  We need to [bring this over](https://github.com/mapbox/mapbox-gl-native/blob/3a1f62e6b9e1e204dde3dd3cf3736cebc1ac0f45/ios/app/MBXViewController.mm#L254-L297) to Android.

NOTE:
10000 is not an exact number nor should be the outcome.  It's just a large number that we've used internally to test / refer to this feature.

**Comment by ljbade** [comment]
Yeah @tobrun and I chatted about needing a test for this yesterday.

**Comment by tobrun** [comment]
Without limiting input (27267 markers) from `points.geojson` 
I'm getting following [stacktrace](http://pastebin.com/BYH9TgQP)

**Comment by tobrun** [comment]
Test with limited input:
Succes with `150` markers
Fails with `175` markers

**Comment by tobrun** [comment]
This [SO-post](http://stackoverflow.com/questions/11079912/android-ndk-overflows-dalvik-jni-local-reference-table) indicates that I need delete local refs as soon as they are handled.

**Comment by tobrun** [comment]
Test with fixes:
Succes with `500` markers
fails with `750` markers

Will finalise this into a PR and will open a new issue for fixing local refs overflow.
