### ISSUE TITLE
gcc-5

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#2553]
Any objections to moving from `gcc-4.9` to `gcc-5` for the gl-native Travis matrix? i haven’t been able to track down why `gcc-4.9/stdlibc++` [isn’t working with `clang/stdlibc++` binaries](https://github.com/mapbox/mapbox-gl-native/pull/2489), but `gcc-5` is compiling with them just fine.

/cc @mapbox/gl

**Comment by mikemorris** [comment]
This seems relevant https://developerblog.redhat.com/2015/02/10/gcc-5-in-fedora/

**Comment by ljbade** [comment]
Only issue I can think of is people compiling the Linux app on their own systems. Not sure which OS releases have GCC 5 packages.

**Comment by jfirebaugh** [comment]
I've hit a few annoying bugs in GCC 4.9 in the last couple weeks. Considering the latest release is now 6.1, I'd say it's time to upgrade and require GCC >= 5.

**Comment by jfirebaugh** [comment]
Just hit another one. I'm gonna JFDI this.
