### ISSUE TITLE
flyTo equivalent

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-native#256]
It would be nice to port ballistic zoom-pan from llmr, as it is usually very useful in demos. I might look into it.

**Comment by jfirebaugh** [comment]
We should emulate https://github.com/mapbox/mapbox-gl-js/pull/1215 here for all the methods related to map view options. It would be nice if C++14 supported C99's designated initializers. In lieu of that we'll probably want to support a chaining syntax:

```
map.jumpTo(mbgl::ViewOptions().center({lat, lng}).zoom(4.2).bearing(45));
```

**Comment by 1ec5** [comment]
How about a struct (call it `Viewport` or somesuch) that specifies center, zoom, and bearing (and someday pitch)? It would be analogous to the `MGLCoordinateRegion` or `MGLMapCamera` that we’ll need to address #1092 and #1643.

**Comment by 1ec5** [comment]
> It would be nice if C++14 supported C99's designated initializers.

Ah, using a struct would be less convenient in the absence of designated initializers or compound literals. clang++ supports both in C++14, but we’ve enabled pedantic warnings as errors, forbidding their use in this codebase.

**Comment by jfirebaugh** [comment]
A struct what I was implicitly going for with `ViewOptions` -- the question is what syntax is most convenient for setting some, but not all, of its members, where the unspecified members use the current map values.

**Comment by incanus** [comment]
Camera API is close to landing: https://github.com/mapbox/mapbox-gl-native/pull/2193

**Comment by 1ec5** [comment]
`flyTo` still needs to be implemented. `jumpTo` is implemented though.

**Comment by incanus** [comment]
Whoops, good catch.

**Comment by incanus** [comment]
Piggybacking off of @adam-mapbox's work in this branch in https://github.com/mapbox/mapbox-gl-native/commit/c788cea7927e4377204524e654a4dbe9046b12f2 and some chat discussion, we might look into temporarily disabling compression in our SQLite caching backend to see if it helps with drawing after jumps. Profiling would probably be in order too, just to see what _is_ the bottleneck (if possible).

**Comment by incanus** [comment]
That'd be around [here](https://github.com/mapbox/mapbox-gl-native/blob/8afa14fa78e628007a983d00efa336674e499735/platform/default/sqlite_cache.cpp#L187) and [here](https://github.com/mapbox/mapbox-gl-native/blob/8afa14fa78e628007a983d00efa336674e499735/platform/default/sqlite_cache.cpp#L126).

**Comment by incanus** [comment]
Per some chat discussion, we could also look into loading 1/4 as many parent tiles or even 1/16 as many grandparent tiles for the destination as a way to quickly warm the cache so that _something_ could be drawn closer to as soon as we land.

**Comment by jfirebaugh** [comment]
#3171
