### ISSUE TITLE
Location setting disabled + last known location

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2564]
When location setting is disabled and we press the FAB to enable user location, nothing happens.

Google maps shows a dialog to enable these settings:

![device-2015-10-08-132500](https://cloud.githubusercontent.com/assets/2151639/10364996/13d21efa-6dc0-11e5-84c8-1a28039d1abb.png)

If you select No, it uses a fallback location known as the last known location from google play services. This api is mirrored in [LOST](https://github.com/mapzen/LOST/blob/master/lost/src/main/java/com/mapzen/android/lost/api/FusedLocationProviderApi.java#L11) and we should add similar behaviour.

**Comment by ljbade** [comment]
@tobrun I opened a ticket over in https://github.com/mapzen/LOST/issues/35

**Comment by tobrun** [comment]
@ljbade is their already a ticket for this in our issue tracker?

**Comment by ljbade** [comment]
Not here, I think this first came up in Sirius, but let's leave this open for tracking.

**Comment by tobrun** [comment]
I reached out to Mapzen to ask them about ETA for this dialog

**Comment by tobrun** [comment]
@bleege @zugaldia, I reached out to them and they would love to add this if we PR it. Is this something we want to do at this time? postpone after `4.0.0`?

**Comment by bleege** [comment]
@tobrun This would be ideal to have in the Mapbox Android SDK.  Can this be done in the SDK or does it need to be done in LOST?

**Comment by tobrun** [comment]
@bleege, the reasons why I asked LOST was because it's currently integrated in Google Play Services. 
We can definitely make this happen from within our SDK! :rocket:

**Comment by bleege** [comment]
@tobrun Cool.  We should definitely look to collaborate with LOST, but for the sake of timing it seemed more appropriate to build this in the Mapbox Android SDK first and then send it to LOST.

**Comment by zugaldia** [comment]
Just noting this landed on LOST 2.0 with https://github.com/mapzen/lost/issues/64 and https://github.com/mapzen/lost/issues/65.

**Comment by tobrun** [comment]
We have deprecated LocationView with #9771, closing.
