### ISSUE TITLE
FAB should move up when Snackbar is shown

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2566]
![device-2015-10-08-172543](https://cloud.githubusercontent.com/assets/2151639/10371004/a7523e0a-6de1-11e5-9aeb-314aa600c851.png)

**Comment by ljbade** [comment]
Should port to Sirius too.

**Comment by ljbade** [comment]
This was quite easy: http://stackoverflow.com/questions/27912656/moving-floating-action-button-up-and-down-to-avoid-getting-blocked-by-a-snackbar

We even had the `CoordinatorLayout` already. Will be in UserLocationView refactor.
