### ISSUE TITLE
Arrange Exceptions

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2579]
As of 01f242cbd98fb110e8f084d7507b7fabd02fecbd the SDK has it's first custom `Exception`.  However it's located in the `com.mapbox.mapboxsdk.views` package which is a bit confusing.  Let's create a `com.mapbox.mapboxsdk.exceptions` package for custom `Exception` classes.  This will keep things logically more organized as well as help keep the custom `Exception` classes from integrating too tightly with whatever is used to throw them.

This is related to #2570 and #2563.

/cc @ljbade @tobrun @zugaldia

**Comment by ljbade** [comment]
Good idea!
