### ISSUE TITLE
mapbox-gl-styles submodule is out of date

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#2585]
We're linking to `mapbox-gl-styles@19dde3cb1c36fe5f42dafc78c806fd7aca98126c`. Taking a look at `streets-v8` at this commit, the style is out of date compared to what is in master. Specifically, we're requesting the old sprite sheet: https://github.com/mapbox/mapbox-gl-styles/blob/19dde3cb1c36fe5f42dafc78c806fd7aca98126c/styles/streets-v8.json#L10. 

/cc @bleege @jfirebaugh @incanus

**Comment by 1ec5** [comment]
@nickidlugash did this recently in #2323, but we had to revert it due to #2106, which is now fixed. So let’s do it all over again. :smile:

**Comment by ljbade** [comment]
@1ec5 @bsudekum I'm sorry to stop the party but Android still relies on "default_marker" due to https://github.com/mapbox/mapbox-gl-native/issues/2506

/cc @bleege

**Comment by bleege** [comment]
Thanks @bsudekum!  @ljbade let's make sure that the proper version of the styles submodule is loaded for `android-v2.1.0` and then we'll deal with #2506 in `android-v2.2.0`.

**Comment by ljbade** [comment]
@bleege Yeah good idea.

**Comment by ljbade** [comment]
After discussion with @1ec5 it appears we are already on the latest pin that has "default_marker", but that also doesn't break the Satellite style.

The options we have to choose from as far as I see them:
1. Create android release branch with old styles pin and update master to styles 1.1.0 (ignore lesson we learnt with 2.0.0 about messy release branches)
3. Bring back default_marker in styles 1.1.0 (is this bad?)
2. Fix #2506 and update to styles 1.1.0 (biggest lift - requires Core GL resources)
4. Be happy with old styles in mobile (worst outcome - no change)

/cc @bsudekum @bleege @1ec5

**Comment by mikemorris** [comment]
Now that mapbox-gl-styles has some tagged [releases](https://github.com/mapbox/mapbox-gl-styles/releases), could we move this to an npm package as part of the ongoing quest to eliminate submodules?

**Comment by jfirebaugh** [comment]
@mikemorris Once the default_marker issue is fully resolved, we're going to go further and remove the styles entirely in favor of using the API: #2239.

**Comment by ljbade** [comment]
@bleege What are we going to do with this ticket? I think we will just have to move it to 2.2.0 as we need #2506 before we can update the pin.

**Comment by bleege** [comment]
> What are we going to do with this ticket?

Let's bump this to `android-v2.2.0` so that we can work with the API as @jfirebaugh suggests.  In the mean time, [I'm still of the idea](https://github.com/mapbox/mapbox-gl-native/issues/2585#issuecomment-147128702) that we "make sure that the proper version of the styles submodule is loaded for `android-v2.1.0`".

**Comment by ljbade** [comment]
I managed to find a fix for https://github.com/mapbox/mapbox-gl-native/issues/2506 so once that lands I will look at updating the style pin. I will set it to whatever the latest "release" tag in styles is.

**Comment by ljbade** [comment]
Going to use the `v1.1.2` tag.

**Comment by ljbade** [comment]
PR made.
