### ISSUE TITLE
Replace MapChange enum with ints

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2586]
Over in #2049 @tobrun noted that Google reccomend `int` constants instead of `enums`: https://www.youtube.com/watch?v=Hzs6OBcvNQE

We should at least switch over MapChange.

@tobrun @bleege @zugaldia Are there any other enums we could change?

**Comment by tobrun** [comment]
One thing I need to mention about this is that you can't always provide the type safety the IDE wants. 

For example: following line will give a lint error:
```java        
setUserLocationTrackingMode(savedInstanceState.getInt(STATE_USER_LOCATION_TRACKING, TRACKING_NONE));
```

You can locally disable this inspection using:
```java              
//noinspection ResourceType       
setUserLocationTrackingMode(savedInstanceState.getInt(STATE_USER_LOCATION_TRACKING, TRACKING_NONE));
```

**Comment by tobrun** [comment]
I was thinking about StyleUrls, we could replace
 > MapView.StyleUrls.MAPBOX_STREETS

With this:
> MapView.STYLE_MAPBOX_STREETS

But I'm not sure if this is what we need for the long term objectives related to styles

**Comment by bleege** [comment]
TBH, I kind of like the idea of like the idea of separating `MapView` from `Styles` altogether.  Something like:

```java
Styles.MAPBOX_STREETS

// Usage
MapView mv = ...
mv.setStyle(Styles.MAPBOX_STREETS);
```

**Comment by tobrun** [comment]
@bleege 
something like in https://github.com/mapbox/mapbox-gl-native/commit/b6eb431d3d828e18a2cbd413264afbd9ff397e4d?

**Comment by tobrun** [comment]
Refactored MapChange:
<img width="573" alt="screen shot 2015-10-11 at 10 16 58" src="https://cloud.githubusercontent.com/assets/2151639/10415961/8d0a3526-7001-11e5-9608-b4ccf0800c4c.png">

I left MapChange inside of MapView but could be moved to a dedicated class as well (eg. Style)

**Comment by bleege** [comment]
@tobrun I :heart: the Style refactor.  :+1: to the MapChange refactor too.  This is good to get this into `2.1.0`.
