### ISSUE TITLE
Move InfoWindow Classes To annotations Package

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2588]
As discussed https://github.com/mapbox/mapbox-gl-native/pull/2478#issuecomment-145920849 it makes for a more robust API and ease of developer use to have the InfoWindow classes in the `annotations` package instead of the `views` package.

I had gotten started on this in #2448 before deciding that the ticket didn't need addressing now.  I'll update the [original commit message on the branch](https://github.com/mapbox/mapbox-gl-native/commit/b990d31ae3184da903fc5b426ea980f3d85c4cc4) and associate it with this ticket for better tracking.

/cc @ljbade @tobrun

**Comment by bleege** [comment]
Hmm... ran into some local issues [amending the commit message](https://help.github.com/articles/changing-a-commit-message/).  At this stage it's just easier to forget about the [`2448-infowindowontouchlistener`](https://github.com/mapbox/mapbox-gl-native/compare/2448-infowindowontouchlistener) and redo the changes in a new branch.

**Comment by bleege** [comment]
Ok, I just got it redone on `2588-move-infowindow-classes` branch and successfully tested locally.  Will let Travis CI do it's thing and when it's ready to go will merge to `master`.

**Comment by ljbade** [comment]
@bleege I'm going to make another PR that makes `getTopOffsetPixelsForAnnotationSymbol` private by passing it to `Marker` in `addMarker`. This makes more sense in the OOP idea that this should be a property of the `Marker` not the `MapView`.

**Comment by ljbade** [comment]
PR made: https://github.com/mapbox/mapbox-gl-native/pull/2592

**Comment by ljbade** [comment]
Merged.
