### ISSUE TITLE
mapbox-gl-native vs. mapbox-ios-sdk-legacy

### ISSUE THREAD

**Issue by AskinOharis** [mapbox/mapbox-gl-native#2593]
Hi guys,
in my project I use mapbox-ios-sdk-legacy which is deprecated by now and there I use external raster tilesources like "OpenCycleMap" via RMAbstractWebMapSource. Can anyone please tell me if this is still possible in mapbox-gl-native and if yes how its done?

Thanks a lot,
Askin

**Comment by friedbunny** [comment]
Yup, raster tiles can be loaded via a custom style — see [this example](https://www.mapbox.com/ios-sdk/examples/raster-styles/) for how to get started with that.

**Comment by AskinOharis** [comment]
Tx for your quick response ...but one more thing. The legacy version was always free to use, meaning no accesstoken and no payment. Just to get it right ..the new native version just works with accesstoken and therefor payment (I know there is a free starter plan/pricing), also when I just use external tilesources like "OpenCycleMap"?
Thanks for clarification,
Askin

**Comment by mdakram** [comment]
@AskinOharis +1

**Comment by friedbunny** [comment]
Looks like access token questions were answered in #2996.
