### ISSUE TITLE
Current state of offline maps

### ISSUE THREAD

**Issue by aschuch** [mapbox/mapbox-gl-native#2594]
Given the current discussion in #584, I was wondering if there is already an ETA of the offline feature in the new GL SDK. Since the old SDKs are deprecated there is currently no way to download and use offline maps. For example, I wasn't able to e.g. render or download the `mapkit.emerald` map (404 API errors) with the latest version of `MBXMapKit`.

What is the current recommendation or options to implement offline maps until this feature has been added to the new SDK?

**Comment by Name-less** [comment]
+1 !

**Comment by incanus** [comment]
Until it's in this SDK, you can continue to use MBXMapKit or the 1.x version of the SDK. Offline ticket is happening here — stay tuned for an ETA soon. 

#584
