### ISSUE TITLE
Labels should line break at hyphens

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#2595]
Labels are often line-wrapped at spaces but never at hyphens, resulting in unwieldy or unbalanced labels. POIs like place names are often hyphenated, particularly in French-speaking countries but pretty much anywhere.

![issy-les-moulineaux](https://cloud.githubusercontent.com/assets/1231218/10434264/5f45ac48-70cd-11e5-8e8b-1fb340a1e8db.PNG)  
![columbia-tusculum](https://cloud.githubusercontent.com/assets/1231218/10434145/afc83380-70cc-11e5-929a-ff1fcd952fbe.PNG)

#1223 is similar, but hyphens are probably a more manageable problem at this stage.

/cc @ansis @mikemorris @nickidlugash

**Comment by peterqliu** [comment]
js equivalent https://github.com/mapbox/mapbox-gl-js/issues/1115
