### ISSUE TITLE
InfoWindowAdapterActivity freezes on open

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2602]
The master branch with latest commit 67f0108389cdd51f3c59ae7638ea2ecd1c4fa899 freezes when opening the InfoWindowAdapter Activity. I'm not seeing any java or native errors. Adding a marker with a InfoWindow in MainActivity with long press works.

**Comment by ljbade** [comment]
I'll look into it.

**Comment by ljbade** [comment]
Been looking into it, it freezes in `nativeGetTopOffsetPixelsForAnnotationSymbol()` at the first `addMarker` in the `InfoWindowAdapterActivity`.

**Comment by ljbade** [comment]
I think this is a bug not specific to my changes in the ref'd commit, but a more general bug. If you clicked on a Marker fast enough with the old code you could trigger this freeze too.

**Comment by ljbade** [comment]
So far I suspect the https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/map/map_context.cpp#L265 line is where it is freezing. `getSprite` obtains a lock in `SpriteStore`

**Comment by ljbade** [comment]
I worked it out, issue is in `map.cpp`.

`Map::getTopOffsetPixelsForAnnotationSymbol` uses `invokeSync` which will hang if the map is paused (which it is during an Activity's `onCreate()`)

@jfirebaugh This is one of only 5 `Map` functions that use `invokeSync` (all getters). Whose responsibility is it to check `isPaused()`? The code calling `getTopOffsetPixelsForAnnotationSymbol` (in this case the Java code) or the `Map` functions (and just return 0 if map is paused).

**Comment by jfirebaugh** [comment]
Right now it's the Mapbox programmer's responsibility to avoid calling `invokeSync` while the map is paused. :) Can you avoid doing that? It looks like `getTopOffsetPixelsForAnnotationSymbol` is used to determine the y-offset for an annotation callout -- seems like that should only be happening while the map is unpaused, no?

**Comment by ljbade** [comment]
@jfirebaugh Yeah I added a check in Java for `isPaused()` and will use a zero offset, until such time as the initial map has finished loading which case there will be valid value.

**Comment by ljbade** [comment]
This is solved in https://github.com/mapbox/mapbox-gl-native/pull/2627
