### ISSUE TITLE
Have Test Activity Use Object Instantiation

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2606]
To cover our bases, we should have an Activity in the TestApp that instantiates it's MapView programmatically instead of loading it via Layout XML.  This is to test for regressions as development continues as well to serve as a simple example to developers.

This can be done by creating a new Activity or by refactoring an existing one (`PressForMarkerActivity.java` maybe?).

/cc @tobrun @ljbade

**Comment by ljbade** [comment]
Good idea!

**Comment by bleege** [comment]
@tobrun :+1:
