### ISSUE TITLE
Dotted lines aren't consistently round

### ISSUE THREAD

**Issue by systemed** [mapbox/mapbox-gl-native#2607]
Dotted lines ([raster example](http://tile.cycle.travel/topoclassical/16/32500/21679.png)) are traditionally (Illustrator, CartoCSS, etc.) achieved with zero-width dashes, round line caps, and a significant gap, like so:

```ruby
	layer(:paths, :zoom=>13..22) {
		line_color 0x777777
		line_width 10
		line_dasharray [0,2]
		line_cap :round
	}
```

([Glug](https://github.com/systemed/glug)-formatted but you get the idea.)

Doing this in Mapbox GL can produce really entertainingly misshaped dots:

![screen shot 2015-10-13 at 22 06 43](https://cloud.githubusercontent.com/assets/694425/10468392/b7563f86-71f6-11e5-841e-e79d41a2688f.png)

(Much though I like the :heart: :heart: :heart: linestyle!)

The dots look fine when the line is at a multiple of 45°, but become lozengy or <3-like at other angles. Even at 45° multiples, the dots get stretched at fractional zoom levels - I guess the 'smart resizing' should only stretch gaps, not dashes, if the dash length is 0.

Tested with 2.1.2 on iOS; I haven't checked Mapbox GL JS to see if it exhibits the same behaviour.

**Comment by ansis** [comment]
this is related to this -js issue: https://github.com/mapbox/mapbox-gl-js/issues/967

**Comment by mmt8** [comment]
@ansis we have the same problem, we are not able to render dots in all zoom levels, it is usually a pill shape (dash size is 0). We tried to increase the gap but that didn't work either.
