### ISSUE TITLE
Markers across the date line behave strangely

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2608]
@BergWerkGIS discovered a bug when markers are placed across the date line.

Android:
![image](https://cloud.githubusercontent.com/assets/4549888/10306972/1d453e9a-6c2b-11e5-9dfc-43f6e061bd64.png)

after panning around the world:

![image](https://cloud.githubusercontent.com/assets/4549888/10306990/37f8abe6-6c2b-11e5-8ee4-70706158ed73.png)

Again `Clear annotations` is somewhat inconsistent: 
* all pins never disappear after one click
* sometimes half of them do
* sometimes none
* sometimes some do, but reappear after zoom/pan
* ...

iOS:

IPad2, Sirius 1.0v50:
![image](https://cloud.githubusercontent.com/assets/4549888/10452479/8c3761c8-71a5-11e5-8c03-498c1889a428.png)

**Comment by tobrun** [comment]
It is not possible anymore to have a map repeat himself, see screenshot in #922
