### ISSUE TITLE
fall back to bundled default marker for MGLAnnotationImage

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2610]
We should make use of the iOS bundled images from https://github.com/mapbox/mapbox-gl-native/pull/2440 and fall back to them when the delegate isn't implemented. Providing `nil` in an existing delegate method works fine (and is presumably what we tested already). 

This should have tests written for it since the test app doesn't hit this use case.

**Comment by jfirebaugh** [comment]
I was under the impression that this was already implemented, but if not: :+1:.

**Comment by incanus** [comment]
This works if you implement the delegate method and return `nil`, but not if you don't implement it.

**Comment by incanus** [comment]
I'm currently working through a local setup caching issue, I think. The GL code looks correct as far as falling back if the delegate isn't implemented or returns `nil` for a point.

**Comment by incanus** [comment]
Yep; all good here, sorry about the false alarm.
