### ISSUE TITLE
User dot callout view dismisses when user location changes slightly

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#2618]
On iOS, the user dot's callout view is automatically dismissed whenever the user location changes. It should not be dismissed when the location change is small, because that's usually just the result of Core Location refining its location.

/cc @friedbunny

**Comment by 1ec5** [comment]
Keeping the callout view open in this case does not expose any view syncing performance issues, because the user dot itself isn't animated (see #1582).

**Comment by friedbunny** [comment]
Sounds good to me. We show the accuracy pulse (`haloLayer`) [when location accuracy is <10 meters](https://github.com/mapbox/mapbox-gl-native/blob/5b9deae95709ea557f28e4a5dcbe3ac8fd47023e/platform/ios/MGLMapView.mm#L2776-L2777), but I'm thinking perhaps an additional screen distance threshold may be better for the callout — unless potentially jumping all the way across the screen doesn't look that bad.

**Comment by incanus** [comment]
We should just ensure that the dot isn't in fact moving perceptibly, since we can't yet reposition callouts (or other views) synced to the map yet (https://github.com/mapbox/mapbox-gl-native/issues/1125).

**Comment by 1ec5** [comment]
@incanus, I don't think that's a problem in this case: https://github.com/mapbox/mapbox-gl-native/issues/2618#issuecomment-148074417.

**Comment by incanus** [comment]
Right, so I guess we use `-[MGLMapView metersPerPixelAtLatitude:]` combined with changes of < 1 pixel.

**Comment by friedbunny** [comment]
Is this adequately addressed by your recent changes in #3589, @1ec5?

**Comment by 1ec5** [comment]
No, not until #1582 lands.

**Comment by 1ec5** [comment]
I stand corrected: even though the user dot and its callout don’t animate around yet outside of user tracking mode, the callout view does stay open. Closing.
