### ISSUE TITLE
Creating and implementing custom map styles

### ISSUE THREAD

**Issue by mitchellporter** [mapbox/mapbox-gl-native#2621]
Hi,

I'm trying to create and implement a custom style for my map inside of an iOS app. A designer I work with followed a tutorial, downloaded Mapbox Studio Classic, created a map style, and then uploaded it to our account.

For some reason, I can't for the life of me find this page anymore, but when researching how to implement the map style for iOS I came across a page that said something along the lines of "Mapbox Studio Classic is not fully compatible with the Mapbox GL SDK but can still be used by using raster styles."

So that page had a link that led me here: https://www.mapbox.com/ios-sdk/examples/raster-styles/

And I followed those instructions, included the file locally in the "styles" folder of the Mapbox SDK in my Xcode project, and was successfully able to load the custom map style. The only problem with this is that the map loads in chunks now. If I scroll the map and try to move on it, there will be black squares that have not been drawn yet, and then after a second or so they will fill in with the map.

I am guessing that this is what was meant by Mapbox Studio Classic maps not being fully compatible with this new Mapbox GL SDK. So after researching more how to do this properly I've come to the conclusion that there are two ways to do this:

1. Use the following guidelines to create a fully compatible map style by hand: https://www.mapbox.com/mapbox-gl-style-spec/ 

2. Gain access to the private beta for the new Mapbox Studio: https://www.mapbox.com/mapbox-studio/

Am I correct about number 1, will that solve my black squares issue? And as for number 2, is there any way I can gain access to the beta for the new Mapbox Studio? I remember seeing on a separate page that the estimated release date is fall, I'd love to give some final feedback before it ships in exchange for access.

Thanks for the help.

**Comment by friedbunny** [comment]
Raster tiles are images that must be loaded entirely before they can be displayed, hence the black voids you're observing. Maps that are exported from Mapbox Studio Classic are rasters, generally speaking.

Mapbox GL focuses on vector maps. While raster tiles are supported (mostly for the satellite use case), as static pixels they inherently lack the flexibility of [vector tiles](https://www.mapbox.com/developers/vector-tiles/). Our raster maps actually use vector data behind the scenes, but Mapbox GL is about moving entirely to a vector stack.

You're correct that your map style must be recreated following the [GL Style Spec](https://www.mapbox.com/mapbox-gl-style-spec/), either by hand or using the new Mapbox Studio. It's tedious to create styles manually, so I'd recommend trying to get into the beta.

**Comment by jfirebaugh** [comment]
@mitchellporter If you email help@mapbox.com referencing this ticket, we'll get you access to the [Mapbox Studio beta](https://www.mapbox.com/mapbox-studio/).

**Comment by mitchellporter** [comment]
Just sent in that email thanks for the help guys!
