### ISSUE TITLE
Use Maki Icon In TestApp

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2624]
The project claims that ["Developers can still use the Maki sprites from the styles just like Sirius does."](https://github.com/mapbox/mapbox-gl-native/issues/2506#issuecomment-145298477), however Sirius is only using the `default_marker` sprite.  In order for this claim to be true, [Maki icons](https://www.mapbox.com/maki/) should be loadable.  Let's add a test / example of this in the TestApp.

/cc @ljbade @tobrun

**Comment by tobrun** [comment]
@bleege
So far I was able to identify the code example in Sirius:
```java
Marker marker = mapView.addMarker(new MarkerOptions()
                    .position(point)
                    .title("Dropped Pin")
                    .snippet("Tap for x")
                    .sprite("default_marker"));
```
For different styles this will give me different icons, which makes me think that these icons aren't packaged with the aar but are fetched on the fly. I was able to identify a default_marker entry in [emerald.json](https://github.com/mapbox/mapbox-gl-styles/blob/mb-pages/sprites/emerald.json).

I tried replacing "default_marker" with "camera", but this gives me "Can't find sprite named 'camera'".
in [sprite_store.cpp](https://github.com/mapbox/mapbox-gl-native/blob/ddc4a8193e775d9cd9280ad7d9bb6975b4a323ee/src/mbgl/annotation/sprite_store.cpp#L58).

I also looked at raster SDK and their you have [Icon](https://github.com/mapbox/mapbox-android-sdk/blob/26d8857786856e5bd933ef6ad28b1d359b2a342a/MapboxAndroidSDK/src/main/java/com/mapbox/mapboxsdk/overlay/Icon.java#L104) and [MapBoxUtils](https://github.com/mapbox/mapbox-android-sdk/blob/26d8857786856e5bd933ef6ad28b1d359b2a342a/MapboxAndroidSDK/src/main/java/com/mapbox/mapboxsdk/util/MapboxUtils.java#L113) class.

Could you give me a bit more information how a maki icon should be resolved?

**Comment by bleege** [comment]
@tobrun Yep, I went through the same fun yesterday afternoon and [came to the same conclusion](https://github.com/mapbox/mapbox-gl-native/issues/2506#issuecomment-148223279).  This turned out to be a communications / expectations issue.  What this means for now is:

1. Only Style Specific Sprites are supported for `android-v2.1.0`
  1. Ex: Only Sprites from [emerald.json](https://github.com/mapbox/mapbox-gl-styles/blob/mb-pages/sprites/emerald.json) are available for rendering when using the [Emerald Style](https://github.com/mapbox/mapbox-gl-native/blob/e63fb444993c16b158cf833ba4c4e66f81943fba/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/Style.java#L33).
1. Maki support will be an example of custom raster image support that is blocked in #2506.
1. Move this ticket / addition of testing to `android-v2.2.0`

**Comment by ljbade** [comment]
@bleege In the "Toggle point annotations" action I loaded the Maki dog icon. To do this I downloaded the PNG from the Maki page then added it to the app and loaded with `fromBitmap`.

It is a bit blurry as Maki only provide 1x and 2x. We could render more from the SVG using the upcoming VectorDrawable (). Or we could use the SDF files and expose the Core GL support for this.

@tobrun Had suggested perhaps we could automate the addition of Maki more. Perhaps providing a function that goes off and loads a Maki icon from a string.

@bleege Is manually adding Maki PNGs enough or do we need to go further.

**Comment by bleege** [comment]
@ljbade No further action is needed here.  This ticket was to clarify the original statement of ["Developers can still use the Maki sprites from the styles just like Sirius does."](https://github.com/mapbox/mapbox-gl-native/issues/2506#issuecomment-145298477)  Now that this is better understood to mean `Style Specific Sprites` and [Add Support For Marker Bitmaps](https://github.com/mapbox/mapbox-gl-native/issues/2744) has been completed we should be good.
