### ISSUE TITLE
How to draw MKCirlcle on Mapbox GL

### ISSUE THREAD

**Issue by changcode** [mapbox/mapbox-gl-native#2629]
I have migration MKMapView to Mapbox GL in one project recently, But I didn't find some class like MKCirlcle for drawing circle on map. Is there some way to draw circle on map?

**Comment by friedbunny** [comment]
`MGLCircle` hasn't been implemented yet (#2167), though the [circle layer type exists in the spec](https://www.mapbox.com/mapbox-gl-style-spec/#circle) and in the renderer. If you don't need to draw circles dynamically, adding them in the style is a viable option.

**Comment by changcode** [comment]
Thanks firedbunny, what I want to implement are each markers with different radius circle on map view, is that possible to do that through edit render style?

**Comment by incanus** [comment]
Yep @changcode, here's the spec doc: https://www.mapbox.com/mapbox-gl-style-spec/#circle
