### ISSUE TITLE
CATransformLayer: changing property masksToBounds in transform-only layer, will have no effect

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#2633]
Warning shows up three times in the iOS 9.0 iPad Retina simulator, around the same time as the user location annotation is being setup with a simulated location. May have something to do with the simulator not reporting heading, which is where we use masking.

```
<CATransformLayer: 0x7dea6880> - changing property masksToBounds in transform-only layer, will have no effect
```

As of: a422a1d3763e7acfa5f82041f727037b4399c991

**Comment by SunithaSenthil** [comment]
Once Close and execute again in same simulator.

**Comment by friedbunny** [comment]
Can't reproduce this after #2181 and #2643.

**Comment by iceman201** [comment]
I think thats Simulator bug from Apple, and it's not fix yet even on iOS 9

**Comment by jeremie-movify** [comment]
In case anybody is facing the same issue on iOS 14 using UIStackViews, please have a look at the following article:

[Stack View Background Color in iOS 14](https://useyourloaf.com/blog/stack-view-background-color-in-ios-14/)

Long story short:
In iOS 14, UIStackView has changed from using a CATransformLayer to using a CALayer. I saw this first mentioned by Renaud Lienhart (@layoutsubviews) and then confirmed by David Duncan (@rincewindsama). This change is not (yet) mentioned in any release note or documentation (bug report FB8363575).
