### ISSUE TITLE
InfoWindow tip sometimes has a 1 pixel gap

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2636]
Sometimes (must depend on rounding somewhere) there is a small but noticeable 1 pixel gap between the InfoWindow tip triangle and the main rectangle.

I have attached a screenshot showing this, but you need to zoom in to see it clearly:
![device-2015-10-16-114002](https://cloud.githubusercontent.com/assets/1215089/10531242/2be0a99e-73fb-11e5-923e-7c1e8f25b205.png)

I noticed this on my Samsung S6.

/cc @tobrun

**Comment by tobrun** [comment]
@ljbade well spotted ;)

**Comment by ljbade** [comment]
I found a quick fix (nothing else seemed to work) of setting the `topMargin` for the tip view to -1 px.

**Comment by tobrun** [comment]
@ljbade 
Setting margins to negative values is considered bad practice.. 
Personally I find it acceptable to get 2.1.0 out the door but should be fixed in 2.2.0.
I'm thinking about creating 1 shape for the whole background, 
then we can also implement same rounded bordes as iOS.

**Comment by ljbade** [comment]
@tobrun Yeah I did some Googling on negative margins, and found a comment from one of the Android engineers that it is supported on relative layout.

I agree correct way to address this would be to combine everything into just one custom view.

**Comment by tobrun** [comment]
@ljbade Didn't know about support for relative layout. Interesting. 
Do we want the same design for our InfoWindow as iOS?

**Comment by ljbade** [comment]
@tobrun Hmm, not sure can you take screenshots that compare our current InfoWindows with iOS and Google Maps?
