### ISSUE TITLE
Finish off JavaDocs for v2.2.0

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2650]
Continuing from #2002 where we got to in v2.1.0.

Remaining work:
- [x] document annotations
- [x] document geometry
- [x] document constants
- [x] document MapFragment

**Comment by tmcw** [comment]
@bleege I can help out with this. Are there docs on running JavaDoc with the right config for gl-native?

**Comment by bleege** [comment]
Thanks @tmcw!  Here's how to generate and then view them locally in a Web browser:

```sh
// Generate JavaDoc
cd android
./gradlew javadocRelease

// View Generated JavaDocs In Web Browser
open MapboxGLAndroidSDK/build/docs/javadoc/release/index.html
```

**Comment by tobrun** [comment]
document annotations was done in #3338

**Comment by tobrun** [comment]
document geometry, current state for release `3.1.0` in #3537 

![screen shot 2016-01-18 at 15 29 54](https://cloud.githubusercontent.com/assets/2151639/12393821/75834948-bdf8-11e5-9e9a-d2c1fd1e6063.png)

**Comment by tobrun** [comment]
document `MapFragment` still needs work.

**Comment by tobrun** [comment]
I have added documentation to geometry:

![screen shot 2016-01-18 at 15 45 42](https://cloud.githubusercontent.com/assets/2151639/12394217/ca648d4e-bdfa-11e5-8ac0-831efd1f3e96.png)

**Comment by tobrun** [comment]
I have added class documentation to `MapFragment`:

![screen shot 2016-01-18 at 15 56 29](https://cloud.githubusercontent.com/assets/2151639/12394441/24603da6-bdfc-11e5-8648-1e6176222e04.png)

Going to close this issue, will land with #3338.
