### ISSUE TITLE
Remove android.permission.WRITE_EXTERNAL_STORAGE from TestApp

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2655]
Just noticed in the TestApp manifest there is an unused `android.permission.WRITE_EXTERNAL_STORAGE` permission.

I tried commenting it out and it didn't break anything.

**Comment by ljbade** [comment]
I discovered that this is used for generating trace files so I will just comment it out.

I think this is left over from when I used to have to redirect stdout to a file in order to read C++ logs.

**Comment by bleege** [comment]
@ljbade Can you help me understand this?  If the SDK is not using this permission why not just remove it completely?

**Comment by ljbade** [comment]
Hmm yeah I suppose we should just delete it then... I guess if you use the 'Trace' Android debug class you would know to add in the permission anyway.

**Comment by ljbade** [comment]
Completely removing it in https://github.com/mapbox/mapbox-gl-native/pull/2794

**Comment by ljbade** [comment]
Merged.
