### ISSUE TITLE
OnMarkerClick not called after returning to Activity

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2657]
When you navigate back from another Activity, it seems that marker clicks are broken.
Debugged that selectMarker in MapView is not called in that case.

**Comment by ljbade** [comment]
@tobrun Can you give more details on how to reproduce this? (or a video)

Testing current master on my Samsung with this:
- add a few long press markers to main activity
- open InfoWindow acitivity, press the markers
- click the back arrow
- click on the long pressed markers

When I do that I still get the InfoWindow popup, and the Custom Marker Click Listener

**Comment by tobrun** [comment]
@ljbade I noticed this in Sirius, since you are not able to reproduce this in a general setup. Makes me believe this bug may be caused by something else. As a result I'm lowering the priority and moving this back to 2.2.0 hence most implementations will not have this problem.

**Comment by ljbade** [comment]
Does this still happen?

**Comment by tobrun** [comment]
Haven't noticed it and this piece was now removed from Sirius, will close it down for now
