### ISSUE TITLE
Improve InfoWindow background

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2658]
Currently our background of the InfoWindow is constructed out of 2 objects:
 - White background of the LinearLayout wrapping the content of InfoWindow
 - InfoWindowTipView

I'm suggesting to create 1 background object to solve issue (#2636)
While doing this we also can add rounded corners (cfr. iOS)

**Comment by tobrun** [comment]
#### Google Maps: 

![infowindow_gmaps](https://cloud.githubusercontent.com/assets/2151639/10658674/5f51aea2-7899-11e5-9833-d608bd65a2da.png)

@ljbade:
> so to match them we need adjust the shape of the triangle, and a slight gap, drop shadow, and match the font size/bold/centre (with subtitle grey and smaller)

#### Mapbox iOS:

![untitled](https://cloud.githubusercontent.com/assets/2151639/10658738/e16f5bdc-7899-11e5-9c80-ca62f6fc66b7.png)

@tobrun:
> this looks very slick, we could add rounded corners for Android, Google itself is also adding more  rounded corners to their designs (see CardView or new Google Play design)

**Comment by bleege** [comment]
The Mapbox iOS InfoWindow is from https://github.com/nfarina/calloutview.  

As for Mapbox Android, I'd like to see something that is more [in line with Material Design](https://www.google.com/design/spec/material-design/introduction.html) so that it "fits the platform".  This is something that @tatsvc could help review.

**Comment by tatsvc** [comment]
I don't know much (anything) about android so I don't know if this would fit in at all :grimacing: but I'm happy to rework it with some concrete feedback!

### Option 1: stroke + drop shadow
![option1](https://cloud.githubusercontent.com/assets/2894119/10698164/99910cea-797d-11e5-9f3f-273e7eabd006.png)

### Option 2: Thick opaque stroke + drop shadow
![option2](https://cloud.githubusercontent.com/assets/2894119/10698163/998d5398-797d-11e5-8c01-2c2ca0a2fe2c.png)

**Comment by tobrun** [comment]
@tatsvc this already looks great,
I personally prefer the first one. The shadow in the second one is a bit heavy.
only other remark I have is making the gap between infowindow and marker a bit smaller.

About designing for Android:
 - [Guidelines](http://www.google.be/design/spec/material-design/introduction.html)
 - [Inspiration](https://www.materialup.com/)

I have a ton of more of these resources/vids related to Android design, 
ping me if you would like to have more.

**Comment by ljbade** [comment]
I prefer the top one two, makes it look like it floating more.

**Comment by tatsvc** [comment]
![option1](https://cloud.githubusercontent.com/assets/2894119/10699203/265824e2-7983-11e5-8628-7f63e50fda96.png)
![option1cropped](https://cloud.githubusercontent.com/assets/2894119/10699204/2659c284-7983-11e5-8878-63447d218896.png)

**Comment by tatsvc** [comment]
It's going to be important to make sure the paddings are nicely balanced, to make it look more elegant! Let me know if you have any questions about this! Main point: give the text enough space to breathe!

![paddings](https://cloud.githubusercontent.com/assets/2894119/10699269/8c354c90-7983-11e5-8a2b-d121bc715b37.png)

**Comment by ljbade** [comment]
@tobrun if I understand what we need is a nine patch of the corners. And then another bit map clipped to the triangle.

Do you also know what DPI those screen shots are so we can calculate the pixels dimensions?

Then we can give @tatsvc a nice clear set of instructions.

**Comment by ljbade** [comment]
@tobrun if I understand what we need is a nine patch of the corners. And then another bit map clipped to the triangle.

Do you also know what DPI those screen shots are so we can calculate the pixels dimensions?

Then we can give @tatsvc a nice clear set of instructions.

**Comment by tobrun** [comment]
:+1:

**Comment by ljbade** [comment]
Here is a rough nine patch I made from @tatsvc PNG:
![info_window_background 9](https://cloud.githubusercontent.com/assets/1215089/11088033/39cd8c58-88b3-11e5-93f7-be33dfd409b0.png)
![info_window_tip](https://cloud.githubusercontent.com/assets/1215089/11088035/3f8bb066-88b3-11e5-9317-c935f4f691ec.png)

**Comment by ljbade** [comment]
@tobrun Do you want to experiment with the nine patch ^ and see what you come up with?

Otherwise if you think it might be better implemented using other techniques, see what you find.

**Comment by tobrun** [comment]
:+1:  

yeah will do, will try to whip up some custom drawing as wel.

**Comment by tobrun** [comment]
Might take up leaving InfoWindow open when panning the map.

**Comment by ljbade** [comment]
@tobrun yep should be possible now

**Comment by tobrun** [comment]
@ljbade when I use the resources found ^ and changing their filename to `.9.png`, 
I'm gettinga malformed ninepatch error:

![image](https://cloud.githubusercontent.com/assets/2151639/11145363/062811d6-8a05-11e5-8337-769f29a0f43a.png)

**Comment by tobrun** [comment]
Current progress, I'm not :100: on board, I think drawing it ourselves will give best experience and will remove the negative margin. The code below besides nine patch image contains a bugfix for wrongly positioned InfoWindowTipView.

Will PR this and make an issue for drawing instead of nine patch.

![device-2015-11-13-172405](https://cloud.githubusercontent.com/assets/2151639/11151171/d63917e6-8a2b-11e5-81be-26f580c8d9c4.png)

![device-2015-11-13-172358](https://cloud.githubusercontent.com/assets/2151639/11151177/de6cefc8-8a2b-11e5-8403-515ac90e68d0.png)

**Comment by bleege** [comment]
> Current progress, I'm not :100: on board, I think drawing it ourselves will give best experience and will remove the negative margin.

This is a great start @tobrun.  Getting a base level in sooner rather than later is a good move.  We can always iterate to make it better over time.  `#SoftwareIsNeverDone`

**Comment by ljbade** [comment]
@tobrun While you are at it, support for the blue arrow (possibly optional via a property setting on Marker) will be great for highlighting when clicking on an InfoWindow will result in something happening, e.g. directions.
