### ISSUE TITLE
Can't build static library

### ISSUE THREAD

**Issue by MathieuBrousse** [mapbox/mapbox-gl-native#2671]
I've got an error when i try to build the static library for iOS with "make ipackage"

The terminal indicate ; libtool:   error: unrecognised option: '-static'

I updated libtool and autoconf to the latest version but the result is the same.

Here are some info about the configuration : 
host-triplet:   x86_64-apple-darwin14.5.0
       shell:          /bin/sh
       compiler:       gcc
       compiler flags: -g -O2
       linker:         /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld (gnu? no)
       version:        libtool (GNU libtool) 2.4.6
       automake:       automake (GNU automake) 1.13
       autoconf:       autoconf (GNU Autoconf) 2.69

I can make iproj without any issues. I followed the build instructions at https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md#ios-your-app.

Thanks for your help.

Regards,

**Comment by friedbunny** [comment]
This appears to happen when a non-Apple `libtool` is used; we want the one that's placed automatically at `/usr/bin/libtool.

**Comment by MathieuBrousse** [comment]
That's it /usr/local/bin was the first line in /etc/paths causing the issue.
There is an error when generating the doc but not related with libtool, i'm closing the issue.

Thank you!
