### ISSUE TITLE
Check for View leaks

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2675]
Was catching up on the Android performance videos.

This one is on leaking Views: https://www.youtube.com/watch?v=BkbHeFHn8JY

I think we hold referenced to MapView in NativeMapView, and possibly inside the JNI.

We should change these to weak references.

**Comment by tobrun** [comment]
Yep, good catch.

An example of a weak reference can be found in [CompassClickListener](https://github.com/mapbox/mapbox-gl-native/blob/ddc4a8193e775d9cd9280ad7d9bb6975b4a323ee/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/CompassView.java#L144)

**Comment by ljbade** [comment]
Found one leak in the code I was using to test Choreographer.

Something else is leaking too.
