### ISSUE TITLE
Use onTrimMemory

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2676]
From https://www.youtube.com/watch?v=x8Hddx1eOZo

We use onLowMemory, but should also support onTrimMemory.

We should also look at the settings we use for the cache memory size.

**Comment by tobrun** [comment]
Some extra info from the docs:

> Preferably, you should implement onTrimMemory(int) from ComponentCallbacks2 to incrementally unload your resources based on various levels of memory demands. That API is available for API level 14 and higher, so you should only use this onLowMemory() method as a fallback for older versions, which can be treated the same as onTrimMemory(int) with the TRIM_MEMORY_COMPLETE level.

**Comment by ljbade** [comment]
There is also a function they mention in the video for determining low memory devices.

**Comment by cammace** [comment]
@tobrun should we look into adding this into the SDK for `5.0.0`?
