### ISSUE TITLE
Use setFastestInterval

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2677]
From https://www.youtube.com/watch?v=81W61JA6YHw

Stops other apps bombarding us with location updates

**Comment by tobrun** [comment]
This is already in [place]( https://github.com/mapbox/mapbox-gl-native/blob/release-android-v2.1.0/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L634) for 2.1.0.

**Comment by ljbade** [comment]
@tobrun Ah nice! I missed that. Do we not also need setInterval? or does setFastestInterval also set that?
