### ISSUE TITLE
Map View Zoom Limitations

### ISSUE THREAD

**Issue by XienenTWC** [mapbox/mapbox-gl-native#2682]
You guys are probably already working on this, but I ran into something that seemed inconsistent to me. While trying to limit the zooming for our MGLMapView to values greater than 0.5, I was attempting to set the zoomLevel property to 0.5, but it kept jumping to 3. I eventually tracked down the constant MGLMinimumZoom, which I reduced to 0.5 instead of 3 and that resolved the issue for me. The inconsistency, though, is that the map view isn't limiting itself to this value as users use pinching to zoom out. It seems to me that zoom limits should be a settable property via MGLMapView and that pinching should respect this setting.

**Comment by lilykaiser** [comment]
Closing due to ticket age. If this is still a problem, please re-open
