### ISSUE TITLE
MGLMapboxEventsData crashes on launch with simulator

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#2683]
Crashes on every launch when using simulator. It seems to be trying to get the carrier name, which may not exist on the simulator.

https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/MGLMapboxEvents.m#L80-L89

Commit:
https://github.com/mapbox/mapbox-gl-native/commit/28be82c1c19505abb47ca1c03fd069cc4a015ec6

**Comment by friedbunny** [comment]
Thanks for the report, going to lead this up in #2687.
