### ISSUE TITLE
Social

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2684]
/cc @incanus

**Comment by bleege** [comment]
Integrated with Mapbox for Android 2.1.0.

**Comment by bleege** [comment]
Officially announced today that the Mapbox iOS and Android SDKs will be [available via Twitter Fabric](https://www.mapbox.com/blog/fabric/).

![21718459683_996d47d486_b](https://cloud.githubusercontent.com/assets/989928/10651967/92c2fc4c-7807-11e5-9535-58d4643fdf6a.jpg)

**Comment by 1ec5** [comment]
:icecream:
