### ISSUE TITLE
Add xxxhdpi for compass

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2690]
Noticed compass image is missing xxxhdpi.

We are also missing ldpi for a number of the other images too.

**Comment by ljbade** [comment]
Also we are missing the different Mapbox logo densities.

**Comment by tobrun** [comment]
I would hold this off until we have vector support and replace all images
with SVGs?
These densities will be automatically generated at build time.

2015-10-21 0:55 GMT+02:00 Leith Bade <notifications@github.com>:

**Comment by ljbade** [comment]
@tobrun Yeah I was having a look at the vector stuff, too bad they still haven't released the 1.4 gradle plugin!

It should also reduce the size of our aar.

**Comment by ljbade** [comment]
If https://github.com/mapbox/mapbox-gl-native/issues/2736 is not possible before next release (ie gradle plugin still not out) I will implement this.

**Comment by ljbade** [comment]
@tatsvc While you hitting the GPS marker resize, can you also provide a `xxxhdpi` image of the compass from https://github.com/mapbox/mapbox-gl-native/issues/2182

It should be 192 x 192 pixels.

Can you also attach the SVG file too, so I can save it in the repo (which already has the marker and GPS SVGs for safe keeping and future work in https://github.com/mapbox/mapbox-gl-native/issues/2736)

**Comment by ljbade** [comment]
@tobrun Do you know where you got the PNG for the Mapbox logo overlay from?

**Comment by ljbade** [comment]
@1ec5 Where did you get the updated Mapbox :dog: from? (see https://github.com/mapbox/mapbox-gl-native/pull/1079)

I want the SVG source for #2736 as well as to generate some resized PNGs.

**Comment by 1ec5** [comment]
https://github.com/mapbox/mapbox-press-assets/blob/master/logos/mapbox-logo/attribution-logo.svg

**Comment by ljbade** [comment]
@1ec5 excellent ill generate the missing ones
