### ISSUE TITLE
Improve testing documentation

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#2701]
The testing documentation currently states

> make test-\* Builds and runs all tests. You can specify individual tests by replacing \* with their name.

This doesn't seem to work:

the suggestion:

```
~/src/mapbox-gl-native〉make test-*
zsh: no matches found: test-*
```

just make test:

```
~/src/mapbox-gl-native〉make test
build: osx/x86_64
host: osx/x86_64
libs: headless=cgl  platform=osx  asset=fs  http=nsurl  cache=sqlite
* Recreating project...
* Building target test...
make[2]: Nothing to be done for `test'.
```

trying to run a platform of tests:

```
~/src/mapbox-gl-native〉make test-osx
build: osx/x86_64
host: osx/x86_64
libs: headless=cgl  platform=osx  asset=fs  http=nsurl  cache=sqlite
* Recreating project...
* Building target test...
make[2]: Nothing to be done for `test'.
./scripts/run_tests.sh "build/osx-x86_64/Release/test" --gtest_filter=osx
ulimit -c: unlimited
npm WARN package.json mapbox-gl-native@2.0.0-pre.10 No license field.
npm WARN installMany node-pre-gyp was bundled with mapbox-gl-native@2.0.0-pre.10, but bundled package wasn't found in unpacked tree
express@4.11.1 ../node_modules/express
├── utils-merge@1.0.0
├── merge-descriptors@0.0.2
├── methods@1.1.1
├── cookie@0.1.2
├── fresh@0.2.4
├── escape-html@1.0.1
├── range-parser@1.0.2
├── vary@1.0.1
├── cookie-signature@1.0.5
├── finalhandler@0.3.3
├── media-typer@0.3.0
├── parseurl@1.3.0
├── serve-static@1.8.1
├── content-disposition@0.5.0
├── path-to-regexp@0.1.3
├── depd@1.0.1
├── on-finished@2.2.1 (ee-first@1.1.0)
├── qs@2.3.3
├── debug@2.1.3 (ms@0.7.0)
├── etag@1.5.1 (crc@3.2.1)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── send@0.11.1 (destroy@1.0.3, ms@0.7.0, mime@1.2.11)
├── type-is@1.5.7 (mime-types@2.0.14)
└── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.7)
Note: Google Test filter = osx
[==========] Running 0 tests from 0 test cases.
[==========] 0 tests from 0 test cases ran. (0 ms total)
[  PASSED  ] 0 tests.
```

**Comment by mikemorris** [comment]
+1, I've never found a way to specify individual tests either.

**Comment by tmcw** [comment]
Does anyone know how to run the core tests for mapbox-gl-native?

**Comment by kkaefer** [comment]
the `*` is a placeholder for Google Test case names

**Comment by kkaefer** [comment]
@tmcw: run `make test-* -j8`

**Comment by jfirebaugh** [comment]
```
~/src/mapbox-gl-native〉make test-*
zsh: no matches found: test-*
```

I think this may be an incompatibility with zsh. `make test-*` works in bash. @tmcw does something like `make 'test-*'` work in zsh?

**Comment by mikemorris** [comment]
> you can do things like `make test-Storage.*`
note that the casing has to be exact

**Comment by tmcw** [comment]
Yes: quoting the `*` works - I made a note of this in the docs refactor https://github.com/mapbox/mapbox-gl-native/blob/redo-docs/docs/DEVELOP_LINUX.md#test

**Comment by jfirebaugh** [comment]
I'd like to deprecate `make test-*`, `make itest`, `make xctest`, and any other test targets we have in favor of:

```
PLATFORM=osx make test
PLATFORM=ios make test
PLATFORM=node make test
PLATFORM=linux make test
PLATFORM=android make test
```

Each of these would build and run the maximal test suite for the given platform: i.e. the complete set of tests that are expected to work on that platform, including core unit tests (as we get them up and running on each platform), headless rendering tests (ditto), and all platform-specific tests that may exist.

Hopefully we can support cross-compilation and native/simulator/emulator execution for all five platforms, at least on an OS X host.

**Comment by kkaefer** [comment]
Sounds good. What's your plan for limiting test suite runs to certain kinds of tests (e.g. when developing)?

**Comment by jfirebaugh** [comment]
Run in Xcode with an `--gtest_filter=...` argument set in the schema, or run the appropriate command by hand from the command line.
