### ISSUE TITLE
iosapp: Failed to load [mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6]

### ISSUE THREAD

**Issue by iDevelopper** [mapbox/mapbox-gl-native#2713]
When i try to execute the iOS application, i can see this error in the console :

2015-10-22 09:49:06.221 Mapbox GL[43335:2498349] [ERROR] {Map}[Style]: Failed to load [mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6]:

What i'm doing wrong ?

**Comment by iDevelopper** [comment]
What does it means? You have transmit this issue to them or do i write to them ?

**Comment by ljbade** [comment]
Sorry @iDevelopper for the confusion.

I /cc'd my iOS colleagues so they can answer your question when they read this issue tomorrow.

**Comment by iDevelopper** [comment]
Thank you very much :)

**Comment by friedbunny** [comment]
We currently do not know what causes this intermittent failure, which is being tracked in #2012.

**Comment by iDevelopper** [comment]
Ah OK, but for me it is not intermittent, i tried several times on simulator an on device

**Comment by 1ec5** [comment]
Are you seeing the issue in the iosapp application that's part of this repository, or in an application you've written based on the iOS SDK? If the latter, are you using one of the built in styles or a custom style?

**Comment by iDevelopper** [comment]
In the iosapp (example) clowned from github and compile with "make iproj". 
Currently I have an application that runs with the deprecated MapBox SDK and displays offline maps (mbtiles). So as this SDK is obsolete, I just started to get interested in the new SDK.

But i can't see the map at screen : Failed to load [mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6]:

**Comment by 1ec5** [comment]
Per case 3 in #1647, please double-check that you’ve [set a valid access token](https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md#mapbox-api-access-tokens) in your environment.

**Comment by iDevelopper** [comment]
I ave a valid access token

**Comment by bkaradzic** [comment]
I have the same issue on Linux. If token is invalid error is:

    [ERROR] {Map}[Style]: Failed to load [mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6]: 
    [ERROR] {Map}[Style]: Failed to load [mapbox://sprites/mapbox/streets-v8.png]: HTTP status code 401
    [ERROR] {Map}[Style]: Failed to load [mapbox://sprites/mapbox/streets-v8.json]: HTTP status code 401

If token is valid only one line is printed:

    [ERROR] {Map}[Style]: Failed to load [mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6]:

**Comment by jfirebaugh** [comment]
We were caching TileJSON with tile URL templates that had embedded access tokens, and then using those URL templates.

As of 025375ad0b365a06e0742b92fecc9bc538b5a6e0, we always canonicalize tile URL templates to a form that does not include an access token, fixing this issue.
