### ISSUE TITLE
Local reference table overflow while adding markers in bulk

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2726]
Documented at original ticket #2552 
Stacktrace is located [here](http://pastebin.com/BYH9TgQP)

After resolving JNI issue:
 - add a Spinner to add 100, 1000 or 10000 markers (cfr. iOS)
 - add a progress indicator for AsyncTask

**Comment by ljbade** [comment]
@tobrun You need to call `DeleteLocalRef` on any objects that are created in a loop in the JNI.

JNI only deletes "local refs" (ie Objects) at the exit of a JNI method, so if you generate a lot of objects before you return, you can overflow the local ref table.

**Comment by ljbade** [comment]
In this case from the log, it is `Sprite` and `LatLng` objects.

**Comment by ljbade** [comment]
Deleting `jid` fixed the overflow.

1,000 markers works:
![device-2015-10-23-154345](https://cloud.githubusercontent.com/assets/1215089/10684767/f3a39148-799c-11e5-8735-53dfe04898fc.png)

10,000 markers freezes after it gets this far:
![device-2015-10-23-154345](https://cloud.githubusercontent.com/assets/1215089/10684771/0485ffa0-799d-11e5-8149-f977e18aa279.png)

**Comment by ljbade** [comment]
Making a PR now.

Still leaves:
 - add a Spinner to add 100, 1000 or 10000 markers (cfr. iOS)
 - add a progress indicator for AsyncTask 
 - fix freeze with 10,000 markers

**Comment by ljbade** [comment]
@tobrun Can we also add an option to switch between `addMarker()` one at a time, and `addMarkers()` to stress test both ways.

**Comment by ljbade** [comment]
Been investigating the 10,000 stall.

I can repro with just 2,000 markers.

Loading the GeoJSON into `MarkerOption` list takes 1.3 seconds.
Adding the markers to the map with `addMarkers` takes 0.3 seconds.

This happens in a async task so doesn't freeze the Android UI.

What happens next is that the Core GL threads process the markers, and stalls `renderSync`, which in turn freezes the map.

@kkaefer Is this a known problem in CoreGL?

If we could solve the 30fps issue in Android then we could punt `renderSync` onto a separate Java thread and not freeze the rest of the app's UI while the map does it's thing. However this presents user location dot sync issues that I have not figure out yet.

**Comment by ljbade** [comment]
@kkaefer by the way it only uses 1/8th of the CPU cores

**Comment by ljbade** [comment]
Testing with 10k markers:

![device-2015-10-23-182045](https://cloud.githubusercontent.com/assets/1215089/10686746/fb74c4b2-79b2-11e5-8201-6ea9e74a2d60.png)

Loading the GeoJSON into `MarkerOption` list takes 1.3 seconds.
Adding the markers to the map with `addMarkers` takes 0.7 seconds.

**Comment by ljbade** [comment]
Testing with the maximum in the GeoJSON (27,267 markers):


Loading the GeoJSON into `MarkerOption` list takes 2.0 seconds.
Adding the markers to the map with `addMarkers` takes 2.5 seconds.

**Comment by ljbade** [comment]
Once loaded, perf is not too bad. It is quite jesky to gesture when zoomed right out, but zoom to street level and it is very smooth.

@adam-mapbox Do you know if we take advantage of geometry instancing in GL?

**Comment by tobrun** [comment]
Will fix the remaining todo's

**Comment by tobrun** [comment]
Apparently I need to optimise input, some markers red from the geopoints.json are the same:

>10-23 20:53:12.849 6565-7455/? V/LoadBulkMarkerTask: marker 0 of 10 added with 38.87031006108791 -77.00896639534831
10-23 20:53:12.850 6565-7455/? V/LoadBulkMarkerTask: marker 1 of 10 added with 38.87031006108791 -77.00896639534831
10-23 20:53:12.851 6565-7455/? V/LoadBulkMarkerTask: marker 2 of 10 added with 38.87031006108791 -77.00896639534831
10-23 20:53:12.851 6565-7455/? V/LoadBulkMarkerTask: marker 3 of 10 added with 38.89569665945388 -76.91636206355402
10-23 20:53:12.851 6565-7455/? V/LoadBulkMarkerTask: marker 4 of 10 added with 38.89569665945388 -76.91636206355402
10-23 20:53:12.851 6565-7455/? V/LoadBulkMarkerTask: marker 5 of 10 added with 38.89569665945388 -76.91636206355402
10-23 20:53:12.851 6565-7455/? V/LoadBulkMarkerTask: marker 6 of 10 added with 38.908392080284656 -77.0238724795834
10-23 20:53:12.852 6565-7455/? V/LoadBulkMarkerTask: marker 7 of 10 added with 38.908392080284656 -77.0238724795834
10-23 20:53:12.853 6565-7455/? V/LoadBulkMarkerTask: marker 8 of 10 added with 38.908392080284656 -77.0238724795834
10-23 20:53:12.853 6565-7455/? V/LoadBulkMarkerTask: marker 9 of 10 added with 38.8489449722363 -76.97787257022829

**Comment by ljbade** [comment]
Ha-ha hmm
