### ISSUE TITLE
Remove FileSource pluggability

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#2729]
We currently have pluggability in the `FileSource` system on two different levels: We can swap out the `FileSource` altogether, or we can use the `DefaultFileSource`, and compile Mapbox GL with different backends for *HTTP requests* (NSURL, cURL), *File requests* (libuv/filesystem, libzip), and *Cache lookups* (sqlite).

The only current user of swapping out the entire FileSource are the node bindings, and the preliminary implementation of the Qt FileSource. We should remove this level of pluggability, and hard-code the `DefaultFileSource` as the only allowed FileSource (we should drop the `Default` in the process).

Then, our only level of pluggability is by using platform-specific backends:

* **HTTP**: NSURL\*, cURL, Qt, Java (OkHttp), Node.js
* **Asset**: fs (libuv), zip, Java, Node.js
* **Cache**: sqlite, Qt, Java, Node.js

The advantage of this system is that we will always have the logic that we're implementing in the FileSource (retrying, persistent monitoring) with any given backend.

**Comment by jfirebaugh** [comment]
:+1:

**Comment by mikemorris** [comment]
> Our usage of Node.js bindings has outlier requirements: doesn't always use http to make requests, never wants caching, change monitoring, or retries. DefaultFileSource behavior would not be appropriate there.
