### ISSUE TITLE
Double-tap followed by horizontal drag should not zoom the map

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#2731]
A double-tap followed by a horizontal drag should not zoom the map. We should require the drag to be vertical to zoom the map, like in Google Maps.

/cc @incanus @ljbade

**Comment by ljbade** [comment]
Android seems to already be doing it correctly, though double tap does seem to also trigger the long press to add a marker in the test app.

**Comment by friedbunny** [comment]
It looks like Google Maps (iOS) cancels the gesture if the first motion after the double-tap-hold is horizontal. If you succeed in quick-zooming, horizontal movement is still accepted.
