### ISSUE TITLE
Incorporate New User Dot Artwork

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2732]
Incorporate new User Dot artwork from @tatsvc.  This will also be used in #2049.  Artwork can [be found here](https://github.com/mapbox/gl-internal/issues/262#issuecomment-150346293).

**Comment by ljbade** [comment]
@tatsvc Can you also attach the XML source for the three icons (if you have them) - at some point in the future we will switch to VectorDrawables instead of bitmaps

**Comment by ljbade** [comment]
Work is progressing but I need to tweak some sizes a bit.

Sorry @tatsvc if this sounds a bit pedantic...

First I need the base image to be 40 dp wide/high.
I also need the dot with no arrow, and the grey dot to be the same size - with padding to account for the invisible transparent ring. Basically if you swap the two images the dot in the middle stays the same size

I created an image to help explain:
![gps](https://cloud.githubusercontent.com/assets/1215089/10682648/fccda4f2-7983-11e5-859c-7e426b0c21af.png)
(ignore the fact that there are no drop shadows in ^ I used the SVG files - the PNGs should still ahve the same shadow)

Now for the image sizes in pixels from smallest to largest (note there is one more at each end):
- ldpi = 30 x 30
- mdpi = 40 x 40
- hdpi = 60 x 60
- xhdpi = 80 x 80
- xxhdpi = 120 x 120
- xxxhdpi = 160 x 160

Also can you stick them in a Dropbox folder, be much faster than saving one image at a time.
