### ISSUE TITLE
Replace bitmap assests with vector drawable

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2736]
Once the new Android Gradle 1.4 plugin is released (#2268) we should replace the existing bitmaps with vector assets.

This allows Android to always correctly generate the right sized image no matter what DPI current or future devices are. It is backwards compatible with old Android versions via the support library.

At the moment we have to add a new set of bitmaps every year or two to keep up with the latest high resolution devices. This is time consuming and also increases our AAR size.

Google has a video explaining it: https://www.youtube.com/watch?v=wlFVIIstKmA

The main requirement to implement is that we have SVG files for all the current drawables. We should keep these in a directory.

This will unblock https://github.com/mapbox/mapbox-gl-native/issues/2386

**Comment by tatsvc** [comment]
@ljbade the svg files are here: https://www.dropbox.com/sh/hr6rwyvg4z5gtyi/AADlzuKmW6O8SxEYJhtE3OZ2a?dl=0

I wasn't sure what to do with the drop shadow on the user dot. It doesn't seem like something that should be in the svg? Can you add that with code?

As for this guy:
![direction-72](https://cloud.githubusercontent.com/assets/2894119/10679671/13a33d3c-78e8-11e5-8876-9a222c2f58fa.png)

the semi-transparent circle is 50% opacity. All the other stuff are solid shapes.

Let me know if you need more information, or different assets.

**Comment by tobrun** [comment]
Linking #2386

**Comment by tobrun** [comment]
This issue has gone out of date, we are drawing the UserLocationView programatically.
