### ISSUE TITLE
make always rebuilds everything

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2738]
For some reason in the last week or so, `make android` now rebuilds all the C++ files when switching between git branches, even if there are no C++ file differences between them

This is very annoying and time consuming.

@kkaefer @jfirebaugh Do either of you know of any changes that might be causing this?

**Comment by kkaefer** [comment]
I can't reproduce this issue. `make android` still does incremental builds for me. Any chance that the differences between both branches are so big that it seems like a full rebuild, when in fact just a widely used header file changed?

**Comment by kkaefer** [comment]
Please reopen if you continue to observe this behavior.

**Comment by ljbade** [comment]
Interesting, I'll keep an eye on it.
