### ISSUE TITLE
Add all official styles to Styles

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2739]
From https://github.com/mapbox/mapbox-gl-native/pull/2714#issuecomment-150370112

There is a list of official styles in https://github.com/mapbox/mapbox-gl-styles

We should add them all to our `Styles` constants, and add the useful ones to the test app and Sirius.

@1ec5 is there any update to ios test app needed too?

**Comment by 1ec5** [comment]
Yes, we need to update both iosapp and scripts/ios/package.sh.

**Comment by ljbade** [comment]
I slipped in the change needed for `default_style.cpp`
