### ISSUE TITLE
Add all official styles to styles

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2740]
From https://github.com/mapbox/mapbox-gl-native/issues/2739#issuecomment-150385722

> we need to update both iosapp and scripts/ios/package.sh.

/cc @1ec5

**Comment by ljbade** [comment]
@1ec5 was looking at the iosapp code and it currently in `cycleStyles` assumes that the style file name is the lowercase+hyphenated version of the human name.

Satellite Streets == `satellite-hybrid-v8`

Breaks that.

**Comment by ljbade** [comment]
@1ec5 Can you update the logic + name of the style in iOS for "Satellite Streets"

I don't have much of a clue in ObjC and I dont have iOS test setup handy

**Comment by 1ec5** [comment]
Taken care of in #2771.
