### ISSUE TITLE
Add Support For Marker Bitmaps

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2744]
Now that the [`setSprite()` issue has been resolved](https://github.com/mapbox/mapbox-gl-native/issues/2506#issuecomment-149868602) we need to add support for custom images (aka `Drawable`) in the Marker API.

**Comment by ljbade** [comment]
@bleege I have already implemented this via `Marker.setIcon(Sprite icon)`. I called it `setIcon` to remain consistent with Google Maps.

To get

**Comment by ljbade** [comment]
I added a `fromDrawable`.

I used it in the `InfoWindowAdapter` activity to add colored city markers that match the color of the InfoWindow.

![device-2015-10-23-163206](https://cloud.githubusercontent.com/assets/1215089/10685283/f8354d12-79a3-11e5-8b64-208d71f1fbf8.png)
