### ISSUE TITLE
Add CoordinateBoundsTest to unit test

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2748]
Need to add test support for CoordinateBounds introduced in #2613

**Comment by tobrun** [comment]
Also seeing that that class is using sw and ne as class members, will make these more java compliant

**Comment by tobrun** [comment]
Is also missing the crucial java Object methods as toString, hashCode, equals etc

**Comment by ljbade** [comment]
And Javadoc?

**Comment by tobrun** [comment]
> And Javadoc?

well played

**Comment by tobrun** [comment]
Closing by https://github.com/mapbox/mapbox-gl-native/commit/0ff57342fd4de9a912d6e82c37665f8878c0716e
