### ISSUE TITLE
Add follow user tracking mode

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2758]
This ticket is a part of #2049 and focuses purely on follow mode user tracking. 
@ljbade has made great progress on GPS marker in #2712.
I'm dividing this ticket to provide correct integration within the system @ljbade provided there.
After related code is validated we can integrate bearing.

**Comment by ljbade** [comment]
:+1:

**Comment by haydenkaizeta** [comment]
Is this functionality possible with the new `LocationLayerPlugin`? Also is it possible to track bearing?
