### ISSUE TITLE
Implement MapChangeDidFailLoadingMap event notification

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#2762]
#630 got us `willStartLoading` and `didFinishLoading`, but [`MapChangeDidFailLoadingMap`](https://github.com/mapbox/mapbox-gl-native/blob/ba4a2965c75c7455f133c78d5c0dcea192e4b874/include/mbgl/map/view.hpp#L22) is somewhat more complicated and remains to be implemented.

This delegate method already exists on [iOS](https://github.com/mapbox/mapbox-gl-native/blob/ba4a2965c75c7455f133c78d5c0dcea192e4b874/platform/ios/MGLMapView.mm#L2983-L2991) and probably does on Android (@ljbade?), it's the core logic that needs doing.

/cc @jfirebaugh

**Comment by 1ec5** [comment]
#1804

**Comment by ljbade** [comment]
This failure should also include malformed URLs

**Comment by ljbade** [comment]
And yes Android plumbing is done

**Comment by friedbunny** [comment]
@1ec5 this issue refers to `mapViewDidFailLoadingMap:withError:`, while #1804 is `mapViewDidFinishRenderingMap:fullyRendered:NO`. These both exist in MapKit, though I'm unsure what the effective difference is right now.

**Comment by bleege** [comment]
> And yes Android plumbing is done

@ljbade Could you provide a link to the issue / commit where this was done?  That way we all can track this better in the future.  :+1:

**Comment by ljbade** [comment]
The two relevant PRs are https://github.com/mapbox/mapbox-gl-native/pull/2255 and https://github.com/mapbox/mapbox-gl-native/pull/2591

Although we will need to change the Android Javadoc for that event to indicate it is now implemented.

**Comment by bleege** [comment]
Cool!  Thanks for the links @ljbade!  Makes remembering what was done much easier.  :+1:

**Comment by tmpsantos** [comment]
`MapChangeDidFailLoadingMap` is currently never emitted by `mbgl-core`. I'm proposing on #6142 to emit it at least when the style fails to load.

**Comment by friedbunny** [comment]
#6142 added this to core and #6145 finished up the iOS/macOS implementations.

@tobrun, if you could confirm that [`DID_FAIL_LOADING_MAP`](https://github.com/mapbox/mapbox-gl-native/blob/e759f1c948ab3ec4cd8b2e1b2a515b799449e924/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java#L2928-L2936) is successfully received on Android and then update the docs, I think we can close this issue. :bow:

**Comment by tobrun** [comment]
Confirming that this is implemented. Closing.
