### ISSUE TITLE
Help on selecting buildings

### ISSUE THREAD

**Issue by EBermudezCDS** [mapbox/mapbox-gl-native#2767]
Hi, we wanted to know if there is a way to highlight a building on the map. Basically we are working on an iPad app and we want to allow the users to select buildings by pressing over them. Our idea is to highlight a building when is selected, Let's say something like this:

![screen shot 2015-10-21 at 9 54 43 am](https://cloud.githubusercontent.com/assets/4991659/10702507/e6895158-79a8-11e5-8dc8-d91931261003.png)

We notice that mapbox can show the building boundaries but we couldn't figured out a way to interact with them.

We will really appreciate any help on this.

Thanks!

**Comment by 1ec5** [comment]
This is currently possible in GL JS but not the iOS SDK. #352 will add an API for detecting that a building is under the tapped coordinate and get its coordinates. (Also, in #837 we’re working towards the ability to change the style dynamically at runtime, which could be useful.) In the meantime, to do this, you’ll need to load the data from a source like OpenStreetMap manually.
