### ISSUE TITLE
crash in glDiscardFramebufferEXT

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-gl-native#277]
Logging a crash I hit for further investigation:

  - iphone retina 4 in simulator
  - debug build
  - running with all schema diagnostics
  - crash happened when panning after zooming to location (which appeared to be SF, though why would that be used for the sim location?)
  - maybe this is just because the simulator is so slow and not cause for concern?

![screenshot 2014-05-29 14 43 03](https://cloud.githubusercontent.com/assets/20300/3124204/76f10d34-e77a-11e3-96d3-2e53c3ffb2e9.png)

![screenshot 2014-05-29 14 39 42](https://cloud.githubusercontent.com/assets/20300/3124205/7c8e9932-e77a-11e3-9390-ea6ce9693b90.png)

**Comment by jfirebaugh** [comment]
Stale.
