### ISSUE TITLE
Android x86 does not run

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2772]
Tried loading up an x86 build in the emulator.

Got this crash:
`Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.mapbox.mapboxgl.testapp-1/lib/x86/libmapbox-gl.so: has text relocations`

I should go and retest the other ABIs too.

**Comment by ljbade** [comment]
Looks like this is specific to M:
https://code.google.com/p/android-developer-preview/issues/detail?id=3028

**Comment by ljbade** [comment]
> note to self: http://b/20013628 was the internal bug this work was done under, and there's more information there about the bad NDK version that caused otherwise innocent apps to get this. folks who really do have assembler with text relocations are presumably hairy enough to look after themselves.

> because once I got rid of the text relocations in my library, my random explosions on x86 emulators seemed to be fixed. 

Could be related to OkHTTP crash.

**Comment by ljbade** [comment]
http://slowbutdeadly.blogspot.com.au/2015/09/javalangunsatisfiedlinkerror-dlopen.html

**Comment by ljbade** [comment]
https://wiki.gentoo.org/wiki/Hardened/Textrels_Guide

**Comment by ljbade** [comment]
Running `readelf -a libuv.a | grep TEXTREL` against the mason modules did not find anything. Now going to check core GL .a

@kkaefer What would be the easiest way to add a `readelf -a libmapbox-gl.so | grep TEXTREL` check to the build system so we can catch this in the future.

**Comment by ljbade** [comment]
Interesting `ld` has a `--warn-shared-textrel` option.

**Comment by ljbade** [comment]
Must be OpenSSL
```
leith@leith-xps:~/mb/mapbox-gl-native/build/android-x86/Release/lib.target$ scanelf -qT libmapbox-gl.so 
  libmapbox-gl.so: .LCPI415_0 [0x561940] in (optimized out: previous CAST_encrypt) [0x561900]
...
```

**Comment by ljbade** [comment]
Im testing the `--with-pic` flag.

**Comment by ljbade** [comment]
I discovered setting the OpenSSL configure `-no-asm` flag fixes the TEXTREL problem.

I will update Android to use latest OpenSSL and CURL at the same time.

I will also add the linker error that checks for TEXTREL and will break the build if it finds it.

**Comment by tobrun** [comment]
This issue triggered me to test on Genymotion machines:
 - Google Nexus 4: 4.1.1
   - java.lang.UnsatisfiedLinkError: Couldn't load mapbox-gl: findLibrary returned null

**Comment by tobrun** [comment]
Seeing some other behaviour on the 5.+ machines:
 - First time installing
   - seeing `app running` message but nothing happens
   - can't see the app in list of installed apps

 - Second time
  - 
![screen shot 2015-10-24 at 08 04 03](https://cloud.githubusercontent.com/assets/2151639/10709247/cf392aa0-7a25-11e5-8ff7-6381bf8826d2.png)
  - 
![screen shot 2015-10-24 at 08 04 30](https://cloud.githubusercontent.com/assets/2151639/10709249/e0bcfc66-7a25-11e5-8aa0-3ef50c99fae8.png)

**Comment by ljbade** [comment]
@tobrun Are you compiling the x86 binaries?

You have to run `make android-lib-x86`

**Comment by tobrun** [comment]
@ljbade I was not, I'm now looking at the make file and pieces are falling together. 
We should maybe add some extra information to contributor setup? 

BTW Genymotion paid version has great tools for developing location based apps.
This will make development and testing location tracking a whole lot easier!

![screen shot 2015-10-24 at 08 21 20](https://cloud.githubusercontent.com/assets/2151639/10709319/453b62d4-7a28-11e5-8f43-d9c97bd6959f.png)
:trollface:

**Comment by butaca** [comment]
Thanks to this thread I was able to resolve a similar issue in other project. I just wanted to let you know that the actual flag is no-asm instead of -no-asm, at least according to [the documentation](https://wiki.openssl.org/index.php/Compilation_and_Installation). Maybe this is useful to other readers.
