### ISSUE TITLE
Android runs at 30fps

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2773]
After https://github.com/mapbox/mapbox-gl-native/pull/2680 the Android map only renders at 30fps. It should be able to run at 60fps.

I had a long look at this before but I couldn't figure out a way to fix this *and* keep the map and GPS marker synced.

I posted an email to the Android developers Google Group with no success.

Any help on this will be appreciated.

**Comment by joecacc** [comment]
@ljbade - I'll try to link you up with someone here in Boulder who can maybe help

**Comment by ljbade** [comment]
I just realised I forgot to put the PR (https://github.com/mapbox/mapbox-gl-native/pull/2680) in ^ where I first encountered the issue.

**Comment by ljbade** [comment]
@joecacc Thanks!

**Comment by ljbade** [comment]
Turns out 30 fps is actually the desired frame rate.

So this ticket is super seeded by #2931
