### ISSUE TITLE
Make iOS delegate notifications consistent with MapKit

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#2775]
[MapKit](https://developer.apple.com/library/prerelease/ios/documentation/MapKit/Reference/MKMapViewDelegate_Protocol/index.html) `loading` delegate callbacks are exclusively about fetching map data, while `rendering` ones are exclusively the drawing of the map.

The flow for Mapkit looks like this on initialization:

```
2015-10-23 19:39:28.470 start RENDERING
2015-10-23 19:39:28.503 start LOADING
2015-10-23 19:39:29.435 finish LOADING
2015-10-23 19:39:30.470 finish RENDERING fullyRendered: YES
```

Panning around continues to issue the same notification flow.

**We don't follow MapKit conventions currently.** Instead, at the core-level:
- :x: `MapChangeWillStartLoading` notifications are fired [when the style is set](https://github.com/mapbox/mapbox-gl-native/blob/ffb02d1b83c28ef32176f92fe1dcea3abbfc5526/src/mbgl/map/map.cpp#L99-L107)
- :x: `MapChangeDidFinishLoading` is fired after the map is fully rendered, in [`Map::renderSync()`](https://github.com/mapbox/mapbox-gl-native/blob/ffb02d1b83c28ef32176f92fe1dcea3abbfc5526/src/mbgl/map/map.cpp#L79), not at the point where data is finished loading
- :x: `MapChangeWillStartRendering` is sent in [`Map::renderSync()`](https://github.com/mapbox/mapbox-gl-native/blob/ffb02d1b83c28ef32176f92fe1dcea3abbfc5526/src/mbgl/map/map.cpp#L58-62) but only initially (it should always come before `DidFinish`, but it does not)
- :white_check_mark: `MapChangeDidFinishRenderingMapFullyRendered` [is sent](https://github.com/mapbox/mapbox-gl-native/blob/54858dae8cb92ba3e111422cdc8188f6d38ab4a9/src/mbgl/map/map.cpp#L76) when rendering is done
  - :x: but does not handle the non-fully-rendered case (#1804)
- :x: `MapChangeDidFailLoadingMap` is not implemented (#2762)

Our initialization flow looks like:

```
2015-10-23 19:42:21.695 start RENDERING
2015-10-23 19:42:24.260 finish RENDERING fullyRendered: YES
2015-10-23 19:42:24.262 finish LOADING
```

Panning around our map subsequently only sends more `DidFinishRenderingMap`, nothing else.

Making our iOS map delegate notifications consistent with MapKit will require core changes, rather than iOS changes, which will in turn affect Android. Should Android follow these conventions, too?

/cc @mapbox/mobile

**Comment by ljbade** [comment]
For Android, the main concern is the loading/failed loading events are the only way to return an error about loading the style to the app since everything is async.

@friedbunny How does iOS return async style load failures?

**Comment by friedbunny** [comment]
`MapChangeDidFinishRenderingMapFullyRendered` with a `false` value would indicate some tile(s) failed to render, while `MapChangeDidFailLoadingMap` would fire when map data failed to load from the network. Neither of these are implemented.

We could also potentially use `MapChangeDidFailLoadingMap` to indicate that styles have failed to load. Currently, we throw somewhat cryptic errors [from `MapContext::setStyleURL`](https://github.com/mapbox/mapbox-gl-native/blob/e5aab73b604cb723742ead8a7762e7c8430853bf/src/mbgl/map/map_context.cpp#L119-L126) — usually just the HTTP error code.

**Comment by ljbade** [comment]
As for async style load failures, both iOS and Android are going to implement proper C++ exception handling for this in https://github.com/mapbox/mapbox-gl-native/issues/2825

**Comment by 1ec5** [comment]
@ljbade, #2762 is the most likely way for this to be implemented in iOS, although we could take an approach similar to #2825 to turn exceptions into NSExceptions, which would result in a slightly improved experience. But #2825 is about Android, which needs this much more than iOS right now.

**Comment by 1ec5** [comment]
#4527 proposes an additional mbgl notification for when the style has finished loading that could be useful for MGLMapViewDelegate.

**Comment by lightandshadow68** [comment]
It also appears the order in which `mapView:didDeselectAnnotationView` and `mapView:didDeselectAnnotationView` is different. in MapKit, `didDeselect` is called first and then `didSeselect`. However, the opposite order is used with MGLMapView. 

For example, I show a UICollectionView when an annotation is tapped and hide it when a user taps on an empty area of the map. To accomplish this, I start a timer in `didDeselect` to hide the view, which is invalidated in `didSelect`. However, this strategy no longer works since `didSelect` is called first.

**Comment by lightandshadow68** [comment]
Actually, looks like update code called from my implementation of `didSelectAnnotationView` has started causing `didDeselectAnnotationView` to be called with Mapbox GL. So, it only appeared that the order had changed. I'll try to track down where the actual behavior differs. But, as of now, the order in which `didSelect` and `didDeselect` is called no longer appears to be where the difference lies.

**Comment by lightandshadow68** [comment]
It looks like one of these two cases are causing `mapView:didDeselectAnnotationView` to be called when changing the region of the map via `[MGLMapView showAnnotations:edgePadding:]`.

```
case mbgl::MapChangeRegionWillChange:
        case mbgl::MapChangeRegionWillChangeAnimated:
        {
            if ( ! _userLocationAnnotationIsSelected
                || self.userTrackingMode == MGLUserTrackingModeNone
                || self.userTrackingState != MGLUserTrackingStateChanged)
            {
                UIView<MGLCalloutView> *calloutView = self.calloutViewForSelectedAnnotation;
                BOOL dismissesAutomatically = (calloutView
                                               && [calloutView respondsToSelector:@selector(dismissesAutomatically)]
                                               && calloutView.dismissesAutomatically);
                // dismissesAutomatically is an optional property and we want to dismiss
                // the callout view if it's unimplemented.
                if (dismissesAutomatically || ![calloutView respondsToSelector:@selector(dismissesAutomatically)])
                {
                    [self deselectAnnotation:self.selectedAnnotation animated:NO];
                }
                else
                {
                    // Deselect annotation if it lies outside the viewport
                    if (self.selectedAnnotation) {
                        MGLAnnotationTag tag = [self annotationTagForAnnotation:self.selectedAnnotation];
                        MGLAnnotationContext &annotationContext = _annotationContextsByAnnotationTag.at(tag);
                        MGLAnnotationView *annotationView = annotationContext.annotationView;
                        
                        CGRect rect = [self positioningRectForCalloutForAnnotationWithTag:tag];
                        
                        if (annotationView)
                        {
                            rect = annotationView.frame;
                        }
                        
                        if ( ! CGRectIntersectsRect(rect, self.frame)) {
                            [self deselectAnnotation:self.selectedAnnotation animated:NO];
                        }
                    }
                }
            }

            if ( ! [self isSuppressingChangeDelimiters] && [self.delegate respondsToSelector:@selector(mapView:regionWillChangeAnimated:)])
            {
                BOOL animated = change == mbgl::MapChangeRegionWillChangeAnimated;
                [self.delegate mapView:self regionWillChangeAnimated:animated];
            }
            break;
        }
```

When tapping on an annotation that is in the center of the screen, and remains there throughout the region change, the annotation is still deselected. I'm not sure if the viewport check or callout deselection is being incorrectly triggered. 

I attempted to set a flag in my delegate to ignore the deselection callback when the region is changing, but deselection occurs before `regionWillChangeAnimated` is called.
