### ISSUE TITLE
Optimise layout for tablet

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2780]
![screen shot 2015-10-24 at 10 36 30](https://cloud.githubusercontent.com/assets/2151639/10709783/4187485c-7a3b-11e5-9f0d-781a154dcd38.png)

We need to add some padding to Android View elements for larger screen devices:
 - Mapbox logo 
 - attribution icon 
 - floating action button

We can provide this using specific resource folders.
We could also provide a default zoom level per device size.

**Comment by ljbade** [comment]
Do we need to make stuff bigger?

Can you capture a Google Maps screenshot.

**Comment by tobrun** [comment]
![image](https://cloud.githubusercontent.com/assets/2151639/10711551/7392dfca-7a7f-11e5-9c01-0e8536544146.png)

**Comment by tobrun** [comment]
I think we can use same margins/paddings as FAB provided by activity creation wizard in Android studio.

**Comment by ljbade** [comment]
@tobrun Great idea! Just copy them.

**Comment by tobrun** [comment]
Strange, the wizard doesn't generate extra margins for the fab.
You can see in screenshot below that Google Maps has extra margin right.

MapBox FAB  | Google Maps Fab
------------- | -------------
<img width="76" alt="screen shot 2015-10-25 at 10 47 23" src="https://cloud.githubusercontent.com/assets/2151639/10715009/63fc280a-7b06-11e5-9606-c729a9777fd5.png">  | <img width="82" alt="screen shot 2015-10-25 at 10 49 54" src="https://cloud.githubusercontent.com/assets/2151639/10715016/7ec391e6-7b06-11e5-9854-55425083f24c.png">

**Comment by tobrun** [comment]
Tablet 

Size of logo's should not be increased

Mapbox | Google
------------- | -------------
<img width="121" alt="screen shot 2015-10-25 at 11 04 51" src="https://cloud.githubusercontent.com/assets/2151639/10715072/66fbafba-7b08-11e5-8501-18631e4d9f85.png"> | <img width="166" alt="screen shot 2015-10-25 at 11 07 05" src="https://cloud.githubusercontent.com/assets/2151639/10715075/917e97f2-7b08-11e5-8568-7fc4764cd5ba.png">


Phone:

Mapbox | Google
------------- | -------------
![untitled 3](https://cloud.githubusercontent.com/assets/2151639/10715050/a2f6f5c0-7b07-11e5-9517-e8576d7d679c.png) | ![untitled 4](https://cloud.githubusercontent.com/assets/2151639/10715055/dee9e7f4-7b07-11e5-9364-d436a0d3d28c.png)

**Comment by tobrun** [comment]
Been going through design documents and nothing concrete came up related to margins fab. 
Going to close this as end developer responsibility, we just follow Android activity wizard or guidelines.
