### ISSUE TITLE
Move API Minimum Back To 15

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2784]
The Android minimum API level was moved to 14 in 4af979799479541858825ac13f4294417aecd343.  This should be restored to 15 as discussed in #934.

/cc @ljbade

**Comment by ljbade** [comment]
@bleege When I choose API 15 I thought that was ICS. But ICS actually starts at API 14.

I think it is confusing only supporting from a specific point release (4.0.3) vs the major release (4.0).

I have ordered an old Galaxy Nexus that I am going to load with stock API 14 image to test our SDK on since the Android emulator does not support OpenGL below Jelly Bean.

However since it is hard for most of the team to test API 14/15 due to emulator limitations, should be instead target Android 4.1 Jelly Bean?

**Comment by ljbade** [comment]
Another reason for using API 14 is that is the current default when you start a new app. So the average developer investigating using us for a new app tries to add our SDK they will immediately get a compile error with the default settings.

Also, I noticed we don't really say what API level we support on https://www.mapbox.com/android-sdk/

Going to make a ticket for that. 

![screenshot from 2015-10-25 23 27 27](https://cloud.githubusercontent.com/assets/1215089/10715589/feb8661a-7b6f-11e5-885f-396f7f47d87e.png)

**Comment by bleege** [comment]
@ljbade I agree that technically Ice Cream Sandwich does start with API 14 and not API 15.  :smile:   

However, looking at they way Google refers to Ice Cream Sandwich these days it's all API 15 and above.  Specifically in it's [Market Share Dashboard from August](https://github.com/mapbox/mapbox-gl-native/issues/934#issuecomment-130759209), it's [Market Share Dashboard from today](http://developer.android.com/about/dashboards/index.html), and it's Android SDK Manager download (see screenshot below).  FWIW, when I create a new project it defaults to API 15 (see second screenshot).  I think this is just a "remembered preference" from previous new apps.

Speaking of the Market Share Dashboard Ice Cream Sandwich (API 15+) is at 4.1% in August, and 3.4% as of today.  If there were numbers to indicate that adding API 14 would increase adoption / usage of Mapbox for Android then we should absolutely look at it.  In the meantime, we've launched `2.1.0` at API 15 as of last week and by staying at API 15 we don't have to now go back and test against 14 plus we get to work with a more current API, especially since it's one that has the [`CATEGORY_APP_MAPS` Intent](http://developer.android.com/reference/android/content/Intent.html#CATEGORY_APP_MAPS) included according [to the release notes](http://developer.android.com/about/versions/android-4.0.3.html).

![screen shot 2015-10-26 at 1 09 59 pm](https://cloud.githubusercontent.com/assets/989928/10738255/83b1d58a-7be4-11e5-8fa8-28204e9dc150.png)
_Android SDK Manager Screenshot From Today Goes From 10 to 15_

![screen shot 2015-10-26 at 1 08 51 pm](https://cloud.githubusercontent.com/assets/989928/10738325/e248eafc-7be4-11e5-9b41-65bbdcca28eb.png)
_Default API 15 For New Android Studio Projects_

**Comment by ljbade** [comment]
Sure fair enough. If Google has nuked the use of API 14 then I suppose we can call it "officially obsolete"

**Comment by ljbade** [comment]
Sure fair enough. If Google has nuked the use of API 14 then I suppose we can call it "officially obsolete"
