### ISSUE TITLE
Remove internal use only methods from main Annotation classes

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2787]
I think I have found a solution for the internal use only methods we expose but document in Javadoc as do not use.

We subclass the annotation classes in a `.internal` package (that we can filter from Javadoc) and move the internal methods to them. Then internally in the options classes we create instances of these classes, but return them as the super class.

Then in the`MapView` we can cast (with a check) them to the internal class and use the internal functions.

By moving these functions to internal package and removing from Javadoc we can strongly signal to developers to not use them.

@bleege @tobrun Thoughts?

**Comment by tobrun** [comment]
This ticket has gone stale and is made obsolete with #7192 and #6912. Closing.
