### ISSUE TITLE
Add bearing to location tracking mode

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2797]
This ticket is a part of #2049 and focuses on bearing in user tracking. 
This ticket follows after #2758 and #2712.

Discussed this with @ljbade and we came to the conclusion it would be better to divide bearing from tracking modes hence these can work separately from each other. For this I will add a `BearingTracking.Mode` class conform to `MyLocationTracking.Mode`.

**Comment by ljbade** [comment]
The idea is this:

With location tracking off, bearing mode will change how the user location marker arrow behaves.

With location tracking on, bearing mode will change how the map rotates.

**Comment by tobrun** [comment]
This ticket is almost complete, will wait to PR this until #2813 has been resolved.
Currently no able to do proper testing.
