### ISSUE TITLE
Android Camera API (aka Tilt)

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2805]
The [Core GL work to support perspective](https://github.com/mapbox/mapbox-gl-native/pull/2116) was done by @ansis at the end of August.  @1ec5 added iOS bindings for it #2159 and #2193.  Now that the initial version of the Android SDK (v 2.1.0) has been released (as of 21-Oct-2015) we should add support in Android.

/cc @mapbox/mobile @twbell

**Comment by ljbade** [comment]
@1ec5 From my reading of relevant tickets, there are still a few bugs and functions that don't take into account tilt?

Just want to make sure we have a list of the ones that have not been fixed to include as known issues with tilt in the release notes.

**Comment by 1ec5** [comment]
Now that #2770 is merged, the biggest known issues are #2266, #2259, and possibly #2139. #256 is unimplemented.

**Comment by bleege** [comment]
Looking at the how iOS implemented tilt in https://github.com/mapbox/mapbox-gl-native/pull/2159/files and https://github.com/mapbox/mapbox-gl-native/pull/2193/files it appears that the Core GL has the necessary API for Android implementation.  We _should_ be able to wire this up with JNI and have what we need for the Android bindings API.

The outstanding question is going to be how much will the Android bindings API look like the [Google Maps for Android Camera API](https://developers.google.com/maps/documentation/android-api/views)?  Google Maps Android API uses.  I _think_ we can get by (for now) with simply implementing `CameraPosition`, `CameraPosition.Builder`, and `MapView.animateCamera(CameraPosition cp)` as their example (see below) does.  The "extra" API that we don't need for now (as it'll change the Mapbox API) is `MapView.animateCamera(CameraUpdate cu)` as it deals with zoom, center location, etc.

```java
// Construct a CameraPosition focusing on Mountain View and animate the camera to that position.
CameraPosition cameraPosition = new CameraPosition.Builder()
    .target(MOUNTAIN_VIEW)      // Sets the center of the map to Mountain View
    .zoom(17)                   // Sets the zoom
    .bearing(90)                // Sets the orientation of the camera to east
    .tilt(30)                   // Sets the tilt of the camera to 30 degrees
    .build();                   // Creates a CameraPosition from the builder
map.animateCamera(CameraUpdateFactory.newCameraPosition(cameraPosition));
```

/cc @zugaldia @tobrun @1ec5

**Comment by 1ec5** [comment]
On iOS, we modeled MGLMapCamera after MKMapCamera, since the goal is to more or less match MapKit. The APIs there are intent-driven. You don’t need a lesson on zoom levels and viewing angles to come up with the right values; instead, you decide how high the viewpoint is and what it’s looking at. But if the Google Maps SDK provides literal access to zoom levels and tilt, I think it’d be perfectly reasonable (and more expedient) for the Mapbox Android SDK to do likewise.

**Comment by bleege** [comment]
I've started building out the CameraPosition API bindings.  There's still a bit more work to be done on them, but once finished I'll then look to create the JNI bindings and then tie the two layers together.

**Comment by zugaldia** [comment]
I just added a sample `TiltActivity` to the `TestApp` to help test this functionality once is ready. For now it's just a basic map ready to enable a tilt based on the [API decisions](https://github.com/mapbox/mapbox-gl-native/issues/2805#issuecomment-160743475) described above.

**Comment by bleege** [comment]
From chat earlier today @zugaldia and I decided to punt on full Camera API support for the time being.  Instead the focus of this ticket / feature will be the Gesture support and the stock `getTilt()` and `setTilt(Double pitch, Long duration)` methods on `MapView`.

**Comment by bleege** [comment]
Rebase, Merge, Done.

**Comment by zugaldia** [comment]
Bravo.
