### ISSUE TITLE
Dotted Polyline on Android

### ISSUE THREAD

**Issue by svendroid** [mapbox/mapbox-gl-native#2812]
Is it possible to set a dotted line style for a `Polyline`?

So far I only found methods on the `PolylineOptions` to set width, color and alpha values.

I'm thinking of a similiar function as in the `PathOverlay` of the deprecated mapbox-android-sdk which offered a method `setPaint`. For a dotted line e.g. I could do this:

    Paint paint = new Paint();
    paint.setAntiAlias(true);
    paint.setStrokeWidth(10.0f);
    paint.setStyle(Paint.Style.STROKE);
    paint.setPathEffect(new DashPathEffect(new float[]{10, 10}, 0));
    PathOverlay segmentOverlay = new PathOverlay();
    segmentOverlay.setPaint(paint);

**Comment by tobrun** [comment]
Difference between Polylines on Raster vs GL SDK is that `Polylines` are now GL drawn components.
Looping in @bleege and @ljbade for more information

**Comment by bleege** [comment]
Thanks for the suggestion @svendroid!  Yes, @tobrun is correct about this.  We'll consider adding it in a future release.

**Comment by ljbade** [comment]
Yeah we currently don't support dotted polylines in the core C++ annotations API. However the GL renderer can do it (since it used in map styles).

@incanus Do you know what plans there are to expand annotation styling? A few ideas:
- polyline and polygon dotted lines
- polygon stroke width
- alpha on markers
- z index
- polygon holes

**Comment by jfirebaugh** [comment]
We don't have plans to expand annotation styling per se. Instead, we're going to build out an API to the style itself -- https://github.com/mapbox/mapbox-gl-native/issues/837.

**Comment by incanus** [comment]
Also refs https://github.com/mapbox/mapbox-gl-native/issues/1734.

**Comment by ljbade** [comment]
And ref https://github.com/mapbox/mapbox-gl-native/issues/1734

**Comment by svendroid** [comment]
just to summarize, so it is not possible to draw a dotted line with a Polyline object with the Android SDK. What would be the way to achieve this? By referring to the style api, do you mean generating a new style in form of a json file and add a geojson layer with a line feature?

**Comment by ljbade** [comment]
@svendroid once #837 support for the Style API lands it should be possible to add a polyline then add the dotted line style property to it
