### ISSUE TITLE
Emulator crash part 2

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2813]
Regression found for solution at #2807.

The fix solved the problem of running on ICS but created a crash on Marshmallow:
>E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
E/mbgl: {Main}[OpenGL]: eglMakeCurrent(EGL_NO_CONTEXT) returned error 12296
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 29835 (apboxgl.testapp)

@ljbade @bleege @zugaldia

**Comment by ljbade** [comment]
Interesting, might need to check for `EGL_NO_DISPLAY`

**Comment by sebastialonso** [comment]
Sorry to bother, but this is still happening.

~~~
 E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
 E/mbgl: {Main}[OpenGL]: eglCreateWindowSurface() returned error 12296
 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadcab1 in tid 350
~~~

Any idea why?

**Comment by bleege** [comment]
@sebastialonso Can you provide some details on the setup where this occurring?  For example:

* Which version of the Mapbox Android SDK is being used?
* What device / emulator is being used?
* What version of Android is being run on the device / emulator?

**Comment by sebastialonso** [comment]
I was using Mapbox AndroidSDK 3.0, the device was a Genymotion emulation,
device Nexus 5 running Android 5.1.

I also tried with my physical device, Moto G 2nd Generation running Android
5.1 and the result was the same. Couldn't test on other devices
unfortunately.

**Comment by bleege** [comment]
@sebastialonso The next step is to confirm that the app is setup and using all the lifecycle methods as [outlined in the Examples](https://www.mapbox.com/android-sdk/examples/) as that controls how OpenGL behaves in device.

Please also note that emulators can have issues with their OpenGL and graphics card setup.
