### ISSUE TITLE
Check if savedInstanceState bundle contains MapView keys

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2816]
To make the MapView class a bit more robust, we should check if the bundle from `onCreate` contains  any MapView keys before trying to load them. This will prevent the app from crashing as in #2801 and will result in ignoring saved state in case that the end developer has not called the onSaveInstanceState method.

**Comment by ljbade** [comment]
The bundle functions do allow a default value for missing keys. I am going to look at this.

**Comment by tobrun** [comment]
yeah, but you can't cover all the use cases. If the end developer doesn't override onsaveinstancestate we should just ignore the [whole block](https://github.com/mapbox/mapbox-gl-native/blob/master/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L770)  by checking if bundle contains certain keys.

**Comment by ljbade** [comment]
@tobrun True.  I am thinking we stash a magic key/value and check we get the same value back.

**Comment by tobrun** [comment]
I'm adding:
```java
        outState.putBoolean(MapboxConstants.STATE_HAS_SAVED_STATE, true);
```

to be able to check this in onCreate:
```java
        if (savedInstanceState != null && savedInstanceState.getBoolean(MapboxConstants.STATE_HAS_SAVED_STATE)) {
```
