### ISSUE TITLE
Place symbols in correct order

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#2820]
As a regression from #2617 (see https://github.com/mapbox/mapbox-gl-native/pull/2617/files#r43035678), we no longer respect the order of placement during the initial parse step. Parsing order doesn't matter, but as part of the parse step, we're also placing labels.

We could either make sure that we stop placing labels after a symbol layer wasn't parsed yet, or stop parsing layers after a symbol layer wasn't parsed.

**Comment by jfirebaugh** [comment]
Fixed as part of #2873.
