### ISSUE TITLE
Rendering differences in still images

### ISSUE THREAD

**Issue by miccolis** [mapbox/mapbox-gl-native#2821]
When rendering several dozen still images a second I can pretty reliably trigger differences/bugs in the output. For example, missing lables, labels that are faded (prehaps related to #2264)and missing patterns.

For random captures are below - all slightly different.

<img width="727" alt="screen shot 2015-10-27 at 1 17 11 pm" src="https://cloud.githubusercontent.com/assets/77205/10766358/91563f72-7cad-11e5-9601-5948789a002e.png">

@mikemorris suggested we may need to be more careful about including more funtionality is a isStill check.

**Comment by mikemorris** [comment]
I think this may be related to calling [`view.readStillImage()`](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/map/map_context.cpp#L245-L248) before kicking off [async transitions and animations](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/map/map_context.cpp#L252-L260).

/cc @brunoabinader

**Comment by jfirebaugh** [comment]
Pretty sure this is #2264. Let's track there.

**Comment by mikemorris** [comment]
@jfirebaugh Does the background texture in the images above pass though `Painter::renderSDF` as well?

**Comment by jfirebaugh** [comment]
No, pattern cross-fading happens elsewhere, and also needs to be disabled in Still mode.

**Comment by jfirebaugh** [comment]
@miccolis @bsudekum Was this from when you had reverted from pre.10 back to pre.9? I'm pretty sure that the background fading issue was fixed by 9a97333e852fe81fff9c1f84f6ae30bfb7966ff9 (pre.10).

**Comment by mikemorris** [comment]
@miccolis @bsudekum Can you confirm if this is fixed in `pre.11`?

**Comment by bsudekum** [comment]
This has been fixed in pre16
