### ISSUE TITLE
write iOS heading tests

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2823]
Refs https://github.com/mapbox/mapbox-gl-native/commit/48d6d039ed8a42891bd591d7eab34de7e1d3dec4 and https://github.com/mapbox/mapbox-gl-native/pull/2769.

**Comment by 1ec5** [comment]
Blocked by #3155.

**Comment by jfirebaugh** [comment]
Closing; this has been open for a long time without progress and isn't likely to happen.
