### ISSUE TITLE
NullPointerException in Android studio layout designer

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2830]
From https://github.com/mapbox/mapbox-gl-native/issues/2802

![](https://cloud.githubusercontent.com/assets/12969249/10772773/a44e3a90-7cc5-11e5-92ea-7591a6e55c39.png)

Fix here is to check for layout editor mode in `onDraw`

**Comment by ljbade** [comment]
Added some checks but doesn't seem to make a difference...

Going to clean and rebuild.

**Comment by ljbade** [comment]
That worked. Making PR.

**Comment by acarlstein** [comment]
On Android Studio 3.1.3, when I create an empty project and create a Custom View, I get to a point where the layout editor tells me that there is a NullPointerException on this line:

        // Draw the text.
        canvas.drawText(mExampleString,
                paddingLeft + (contentWidth - mTextWidth) / 2,
                paddingTop + (contentHeight + mTextHeight) / 2,
                mTextPaint);

Here is the error:

> java.lang.NullPointerException   at android.graphics.BaseCanvas.drawText(BaseCanvas.java:405)   at android.graphics.Canvas.drawText(Canvas.java:1820)   at com.acarlstein.org.customview.custom.view.CustomView.onDraw_Original(CustomView.java:100)   at com.acarlstein.org.customview.custom.view.CustomView.onDraw(CustomView.java:-1)   at android.view.View.draw_Original(View.java:19192)   at android.view.View_Delegate.draw(View_Delegate.java:56)   at android.view.View.draw(View.java:19162)

What takes my attention is the "CustomView.java:-1" which when clicked jumps to this line:

        protected void onDraw(Canvas canvas) {

Do anyone knows a tutorial that shows all the modification that you need to do, after the developer uses the feature of creating a Custom View (New -> UI Component -> Custom View), so it the layout editor of Android Studio stop showing errors?

Thanks for your time.
