### ISSUE TITLE
Replace @NonNull NullPointerExceptions with warning logs

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2831]
Following from https://github.com/mapbox/mapbox-gl-native/issues/2801#issuecomment-151665632

I'm going to continue and replace all runtime `NullPointerExceptions` in `MapView` with warning logs.

This is similar to how Android SDK handles `@NonNull` annotation. They just let the code crash naturally where ever something first encounters a `null` that should not have been passed.

/cc @bleege @tobrun

**Comment by bleege** [comment]
:+1:
