### ISSUE TITLE
Add zoom events

### ISSUE THREAD

**Issue by altafrm3d** [mapbox/mapbox-gl-native#2837]
Add something like onZoom() event for Mapview like there is a MapListener in the other version of MapBoxSdk for android, thanks.

**Comment by altafrm3d** [comment]
would somebody be kind enough to label it as a new feature request for android version of mapbox gl native? thanks.

**Comment by tobrun** [comment]
@ljbade 
This one would be good for me to do a deep dive into C++
Will take this up when other PR/Issues have landend.

**Comment by tobrun** [comment]
Closing this in favor of #3751
