### ISSUE TITLE
Filtering features at runtime

### ISSUE THREAD

**Issue by franckt** [mapbox/mapbox-gl-native#2840]
Hi, 

We are working on a outdoor / indoor offline rendering project based on mapbox gl native for IOS and Adnroid, 

Offline works in our prototype by using locally extracted vector tiles served by a local http server

Our vector tiles contains "buildingpart:floor=<floorlevel>" tags to specify the floor of features (rooms, walls, ...)

We search how and where in source code to implement a runtime filter based on the selected floor level without using a gl style file per level and avoid using setStyleUrl that introduce flickering

Maybe there is a way to filter (exclude or not) at runtime based on data read in the source ?

Any helps appreciated

**Comment by jfirebaugh** [comment]
Good question. Dynamic data filtering is not something that's currently supported in mapbox-gl-native. It's a feature that will be enabled by the [Style API](https://github.com/mapbox/mapbox-gl-native/issues/837), currently in development.

**Comment by franckt** [comment]
ok, 
is there a branch that can be used for testing what we want to do ?
have you got a roadmap on this feature, even in alpha stage ?

**Comment by ljbade** [comment]
@jfirebaugh Would style classes help here? (I know they are kinda deprecated) To avoid completely reloading a new style per floor.

**Comment by franckt** [comment]
Hi, 
any news ?

**Comment by jfirebaugh** [comment]
No definite timeline available, but we're still working on the style API.

**Comment by nicolasfavier** [comment]
Hi @franckt ,
I am currently stuck in the same kind of problem. 
Did you found any solution or work around?

**Comment by franckt** [comment]
Hi @nicolasfavier,

i currently use multiple styles, one layer per floor so i duplicate layer for all floors with a filter per floor

and i use classes to display or not a layer

for example a fill layer with 

      "filter": [
                "all",
                [
                 "==",
                 "floor",
                 "0"
                 ]
                ],
      "paint": {
        "fill-opacity": 0
      },
      "paint.floor0": {
        "fill-color": "#9d8e7a",
        "fill-opacity": 1        
      }

is not displayed by default

but only when i use mapView.setClasses ( "floor0" ) 

for a symbol layer i use

       "paint":{
         "text-opacity":0,
         "icon-opacity":0,
         "text-halo-width": 0
       },
       "paint.floor0": {
         "text-color": "#65513d",
         "text-halo-color": "#ffffff",
         "text-halo-width": 1,
         "text-opacity":1,
         "icon-opacity":1
       }
