### ISSUE TITLE
Versioning: how does it work?

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#2841]
mapbox-gl-native has a bunch of node-style tags

```
v0.5.2
v0.5.3
v0.5.4
v0.5.5
v0.5.6
```

But also tags prefixed with ios, android, and node

```
ios-v0.2.12
ios-v0.2.13
ios-v0.2.14
ios-v0.2.15
android-v2.0.0
android-v2.1.0
node-v2.0.0-pre.7
node-v2.0.0-pre.8
node-v2.0.0-pre.9
```

How does this work? For instance, if I implement the [homebrew formula](https://github.com/mapbox/mapbox-gl-native/issues/1677), what kind of tag should it use to grab a tarball of source?

**Comment by mikemorris** [comment]
The platform tags follow semver WRT the public API for that platform. The core tags roughly follow semver for the core C++ API (which is consumed by the platform bindings).

**Comment by jfirebaugh** [comment]
Currently, we are versioning the three SDK platforms -- iOS, Android, and node -- independently. We don't have a versioning system or release process for GL core as an independent C++ library. I believe the platformless tags like `v0.5.2` are actually old iOS versions from a time when iOS was the only SDK getting released out of this repository (Android wasn't released yet, node was in a separate repository).
