### ISSUE TITLE
add [skip ci] obedience to Bitrise iOS

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2843]

**Comment by friedbunny** [comment]
Also `[ci skip]` and `[DON'T EVEN THINK ABOUT IT CI]`.

**Comment by incanus** [comment]
This may need to happen at the Bitrise feature level. Otherwise, we could make a custom step in our `bitrise.yml` that checks `$GIT_CLONE_COMMIT_MESSAGE_SUBJECT` for the patterns, but at that point, the repo would have already been cloned and a job would have been started. We could abort early (albeit with success) but the real point here is not to consume CI resources at all.

**Comment by incanus** [comment]
Confirmed: 

![screen shot 2015-11-02 at 2 19 24 pm](https://cloud.githubusercontent.com/assets/17722/10896102/bf7dd072-816c-11e5-90a1-3cf16c2b37e1.png)

When I have votes again, I'll post to https://bitrise.uservoice.com/forums/235233-general?query=Allow%20for%20configurable%20pattern(s)%20to%20skip%20CI%20altogether.

**Comment by incanus** [comment]
Ok, workaround done as of 8bcf7dcc7d42c485393d8866d4dee807fd2b2023, tested in 1c13fa25b912f427207331a20a064f5147c74c17, proof in https://www.bitrise.io/build/1382f98b35e51334. 

Squashing and merging.

**Comment by incanus** [comment]
Reclaimed some votes and opened https://bitrise.uservoice.com/forums/235233-general/suggestions/10519956-allow-for-configurable-commit-message-pattern-s-t for a long-term fix here.
