### ISSUE TITLE
replicate iOS release build process on Bitrise

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2844]

**Comment by 1ec5** [comment]
I attempted to implement the release build as a chain of workflows on Bitrise, but the resulting build blows way past our build timeout. We’ll need to reimplement it as independent workflows, ideally all triggered simultaneously whenever a new iOS release is tagged.

**Comment by 1ec5** [comment]
We’ve been using a full-service deployment script for the past few releases. It runs locally, rather than on Bitrise, but it’s good enough for now.

**Comment by friedbunny** [comment]
We’re going to be looking at automating the deployment process on CI this week. Initially, I think we’ll keep it more or less the same, but move the build step onto Bitrise. Goals will be to make this deployment process as reasonably automated as possible, while not tying it too closely to any particular CI platform.

So, the deployment process will probably look something like:

1. Release manager bumps versions and updates release notes; gets that merged.
2. Release manager tags the release.
3. Bitrise receives the tag hook and starts the release build using the deployment script.
4. Release manager updates the Github release with notes, checks that binaries are 👍, then pushes publish.
5. Release manager handles the various other docs updates elsewhere.

Eventually we’d like to automate the docs updates, too, but that probably won’t be covered in the initial go.

**Comment by friedbunny** [comment]
Done in #10170 — will be used onward from 3.7.0-beta.2.
