### ISSUE TITLE
node-mapbox-gl-native make center [lng, lat]

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#2846]
We should make the center argument of the node native bindings match those of the JavaScript API

**Comment by bsudekum** [comment]
Conflicting feelings:

* I agree, :+1: to lng lat
* But node will be the only platform in this repo which is lng/lat. Internally it will have to account for lng/lat coming in and interacting with lat/lng in core.

**Comment by mikemorris** [comment]
gl-native core currently uses lat/lng, as do all the other platform bindings to gl-native. We can flip the interface in the node bindings layer to be consistent with gl-js, but then we'd be inconsistent with every other platform binding to gl-native.

Disclaimer: I really don't care, and will implement whatever people who care decide is best.

**Comment by incanus** [comment]
I think consistency across language (JS client and Node both) in the form of `lng/lat` is more important than internal consistency within `gl-native`. The other platforms in `gl-native` _should_ remain `lat/lng` to meet platform expectations there.

**Comment by jfirebaugh** [comment]
`lng, lat`. For a JS API, it's most convenient to have the order that matches GeoJSON.
