### ISSUE TITLE
rethink partial tiles

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#2851]
The logic around partial tiles is complex and brittle. We need to rethink this, maybe do it in a totally different way.

cc @tmpsantos @kkaefer

**Comment by kkaefer** [comment]
What aspect of it is causing problems for you?

**Comment by jfirebaugh** [comment]
Our current implementation is [highly stateful](https://github.com/mapbox/mapbox-gl-native/blob/d20bcb07957edc008d452db8ef5c91baa117bce6/src/mbgl/map/tile_data.hpp#L22-L60), and it is difficult to reason about the order or timing of state transitions. This has given rise to pattern of issues where tiles either never finish parsing or are parsed _ad infinitum_:

* https://github.com/mapbox/mapbox-gl-native/issues/2808
* https://github.com/mapbox/mapbox-gl-native/issues/1565
* https://github.com/mapbox/mapbox-gl-native/issues/1458
* https://github.com/mapbox/mapbox-gl-native/pull/2393
* https://github.com/mapbox/tilelive-gl/issues/25

These issues are often very difficult and time consuming to debug.

Yet despite its complexity, our current strategy is still inefficient:

* https://github.com/mapbox/mapbox-gl-native/issues/2511

I'm not sure what the right approach is yet, however.

**Comment by tmpsantos** [comment]
We need a way of making tiles subscribe to the resources they need and get notified when they arrived. And I'm all in for getting rid of tile states. They will probably still exist, but IMO they could be inferred at runtime.

**Comment by kkaefer** [comment]
Partially addressed by #5139

**Comment by tmpsantos** [comment]
> Partially addressed by #5139

:+1:

**Comment by jfirebaugh** [comment]
Lots of refactoring here lately. Fixing #667 will likely fix #2511 and then things will be pretty clean.
