### ISSUE TITLE
Still getting node Travis failures

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2860]
@jfirebaugh There are still occasional failures in node jobs in my PRs. Restarting them a few times fixes it.

It is lot better than yesterday when Linux was also failing. Linux is stable now.

**Comment by jfirebaugh** [comment]
I fixed one flapping test in #2872. The remaining issues I've seen seem to be networking related. Sometimes they hit `npm install`, sometimes gradle installs in Android builds. Let's try to capture log snippets here as we see them.

**Comment by ljbade** [comment]
Just had a linux clang debug job fail. Sorry I totally forgot to grab the log before I hit restart

**Comment by jfirebaugh** [comment]
Just got the following:

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/travis/.nvm/versions/node/v4.2.1/bin/node" "/Users/travis/.nvm/versions/node/v4.2.1/bin/npm" "install" "--build-from-source"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

Above repeats a dozen times or so, then there's some npm output, then:

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/travis/.nvm/versions/node/v4.2.1/bin/node" "/Users/travis/.nvm/versions/node/v4.2.1/bin/npm" "install" "--build-from-source"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! Callback called more than once.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/travis/build/mapbox/mapbox-gl-native/npm-debug.log
```

**Comment by ljbade** [comment]
`ECONNRESET` sounds like network issues

**Comment by mikemorris** [comment]
Kept hitting the same `ECONNRESET` followed by `Callback called more than once.` errors as @jfirebaugh on Travis OS X boxes running Node.js tests today.

**Comment by jfirebaugh** [comment]
https://travis-ci.org/mapbox/mapbox-gl-native/jobs/90756260 got "Error: unable to open display :99.0". Don't think I've seen that one before.

**Comment by mikemorris** [comment]
> Error: unable to open display :99.0

Sounds like an issue starting up xvfb/X11 https://github.com/mapbox/mapbox-gl-native/blob/master/scripts/linux/setup.sh#L14-L22

**Comment by jfirebaugh** [comment]
Seems more stable lately.
