### ISSUE TITLE
User location/bearing tracking modes to not switch properly

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2862]
When changing between the different modes, things get a bit mixed up.

First if you set compass, then change to GPS, the old compass arrow still exists and is not replaced with the GPS right away. This means we need to separate the GPS and compass bearings into separate variables.

If you set compass (or gps) bearing mode, then enable location tracking the map is not instantly rotated.

When bearing mode is enabled with user location tracking on, the arrow is not drawn, this should always be drawn directly north in this mode.

/cc @tobrun

**Comment by tobrun** [comment]
yeah, making separate variables will be the way to go!

**Comment by tobrun** [comment]
I will take up the remaining remarks (javadoc etc) in this ticket

**Comment by tobrun** [comment]
@ljbade did you have time to take the related PR for a spin?
