### ISSUE TITLE
PressForMarkerActivity is not calling MapView.onSaveInstanceState

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2865]
Application crashes when rotating the PressForMarkerActivity with following stacktrace:

>  Caused by: com.mapbox.mapboxsdk.exceptions.InvalidAccessTokenException: Using MapView requires setting a valid access token. See the README.md

`OnSaveInstanceState` method should be added to PressForMarkerActivity

A similar crash is already being tracked in #2816.

**Comment by ljbade** [comment]
Oh I forgot to close this in https://github.com/mapbox/mapbox-gl-native/pull/2878
