### ISSUE TITLE
Merge Android 2.2.0 Release Branch Back In To Master

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2868]
After it's merged back in we'll also need to update the [version in gradle.properties](https://github.com/mapbox/mapbox-gl-native/blob/978da4224e20c01efb01efe95bbfe51a45c6087d/android/MapboxGLAndroidSDK/gradle.properties#L2) to `2.3.0-SNAPSHOT`.

Related to #2847 

/cc @incanus @jfirebaugh

**Comment by ljbade** [comment]
Should be fairly smooth.

**Comment by bleege** [comment]
Thanks for the vote of confidence.  :smile: 

Merged and pushed as of 25c8eeecf9245cbabdc592c959a56a7c50451315

**Comment by bleege** [comment]
Done.  All new SNAPSHOTS for the next release will be called `2.3.0-SNAPSHOT`.
