### ISSUE TITLE
make ipackage error message out of date

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-gl-native#2871]
Running `make ipackage` failed for me at the "Creating API Docs.." step with:

```
Unable to find appledoc. See https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md
```

But there is no mention of `appledoc` in that file, but rather its in https://github.com/mapbox/mapbox-gl-native/blob/master/docs/BUILD_IOS_OSX.md

**Comment by incanus** [comment]
Refs https://github.com/mapbox/mapbox-gl-native/pull/2800
