### ISSUE TITLE
Remove style class support

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2875]
It is time to mark the style class APIs as deprecated in iOS and Android.

Mapbox Studio does not support creating styles with classes in them. None of the bundled styles uses them. Neither the iOS nor Android test apps/Sirius touch these APIs.

As far as I know they could be completely broken and we would not even notice.

We should first update the documentation to mark them as deprecated.

Eventually we can remove them entirely.

This does not require any changes to core GL at this stage. Basically will only affect the higher level OS specific wrappers.

This will allow us to close:
https://github.com/mapbox/mapbox-gl-native/issues/794
https://github.com/mapbox/mapbox-gl-native/issues/1744
https://github.com/mapbox/mapbox-gl-native/issues/2077

@mikemorris Does node still need to support style classes?

@1ec5 Are there any open iOS tickets this will close?

**Comment by mikemorris** [comment]
Nope, Node doesn't use these APIs.

**Comment by tobrun** [comment]
This will be picked up transitioning API from MapView to MapboxMap with #3145

**Comment by jfirebaugh** [comment]
Let's hold on removing any features around this. The final status of style classes has not been decided yet.

**Comment by tobrun** [comment]
I removed the public java API since it was crashing, the jni code is still there.

**Comment by cammace** [comment]
@tobrun can we remove the Android tag from this ticket?

**Comment by tobrun** [comment]
Don't think this is relevant anymore. Closing
