### ISSUE TITLE
Question: Third party tile source support.

### ISSUE THREAD

**Issue by mdakram** [mapbox/mapbox-gl-native#2879]
Is Mapbox planning to add Third party source for raster tiles as well as vector tiles?

**Comment by friedbunny** [comment]
Check out [this example](https://www.mapbox.com/ios-sdk/examples/raster-styles/) for how to use raster tiles from Mapbox and elsewhere. This is code for iOS, but the basic style can be used in Android, Mapbox GL JS, and anything else that conforms to the [Mapbox GL style spec](https://www.mapbox.com/mapbox-gl-style-spec/).

**Comment by friedbunny** [comment]
Oh, as for third-party vector tiles: we support and encourage them, provided they follow the [vector tile spec](https://github.com/mapbox/vector-tile-spec).

**Comment by sepion02** [comment]
Hi, how should we proceed to display tiles from that kind of servers :
http://c.tile.openstreetmap.org/{z}/{x}/{y}.png

**Comment by Stophface** [comment]
@sepion02 any progress on this?

**Comment by sepion02** [comment]
Nope,
I completly changed my approach.
I imported a world tileset of the needed data ( from openseamap actualy ) in a custom style in mapbox studio. Manualy stylised data dots from their attributes.
Then access this style from mapbox-gl-native

**Comment by Stophface** [comment]
@sepion02 Hm, that wont work for me. Thanks for the reply!

**Comment by Stophface** [comment]
@friedbunny Is there an example how to use third-party vector tiles?

**Comment by zhdh2008** [comment]
Hi, there. 

I have the same question. How to use tiles like 'http://c.tile.xxx.org/{z}/{x}/{y}.png' . For the map data is only released in local network.
