### ISSUE TITLE
Rename SymbolBucket::addFeatures and SymbolBucket::placeFeatures

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#2884]
From https://github.com/mapbox/mapbox-gl-native/pull/2873#issuecomment-152588322:

There are actually three steps:

* **`parseFeatures`**: determines the text we need to display by replacing tokens and applying text transformations, and the glyphs we need
* **`addFeatures`**: determines the potential position of labels
* **`placeFeatures`**: actually places them and adds them to a buffer

`placeFeatures` is currently called as the [last step in `addFeatures`](https://github.com/mapbox/mapbox-gl-native/blob/1688-monitor-annotation-tiles/src/mbgl/renderer/symbol_bucket.cpp#L269), but there's no good reason to; we could separate that out and call the `addFeatures` without placing as soon as we have the symbols. Then we would have less work to do later. However, it means we'd have to introduce a third step beyond `pending`.

**Comment by jfirebaugh** [comment]
Also @kkaefer says "`addFeatures` is poorly named" -- we should rename it to something better.

**Comment by lucaswoj** [comment]
I agree that we should develop some better terminology around this API. How about

 - `resolveText`
 - `calculateTextPlacement`
 - `placeFeatures`

**Comment by kkaefer** [comment]
`text` => `symbol`, but otherwise good

**Comment by ansis** [comment]
they were separated in https://github.com/mapbox/mapbox-gl-native/pull/3543 but not renamed
