### ISSUE TITLE
Aborted Bitrise builds still show as pending

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#2886]
Such as in #2885, which is a docs-only pull request that I manually cancelled CI builds for:

<img width="784" alt="screen shot 2015-10-30 at 4 47 00 pm" src="https://cloud.githubusercontent.com/assets/1198851/10857721/19353fa4-7f26-11e5-940f-fded896d5962.png">

Probably an upstream Bitrise issue (and a minor one at that), but /cc @incanus anyway.

**Comment by jfirebaugh** [comment]
Upstream issue; not much we can do about this other than bug Bitrise.

**Comment by incanus** [comment]
Keep in mind that you can submit feature requests to Bitrise directly and publicly and that we track the status of these internally in a wiki.
