### ISSUE TITLE
iOS Overzooming

### ISSUE THREAD

**Issue by lzumbach** [mapbox/mapbox-gl-native#2887]
Hope this is not a repeat issue. But, is overzooming available for iOS?
ala https://www.mapbox.com/mapbox.js/example/v1.0.0/overzoom/

**Comment by ljbade** [comment]
Yes our vector rendering technology allows overzooming. It even does a better job than mapbox.js since we don't stretch the tile images, we just zoom the vector features.

**Comment by friedbunny** [comment]
Note that overzooming may be affected by #2761.

**Comment by millenbop** [comment]
Yeah to my knowledge this have never been fixed, posting here too. Using `3.1.2 beta 2`.

[Untitled.mp4.zip](https://github.com/mapbox/mapbox-gl-native/files/186025/Untitled.mp4.zip)
