### ISSUE TITLE
make ipackage should ensure particular Xcode versions

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2888]
Either a minimum (e.g. 7.x) or a locked version (e.g. 7.1).

**Comment by 1ec5** [comment]
Should it? It’s fine for a developer to build it themselves in Xcode 6.4 if their projects are in Xcode 6.4. We need to distribute a build w/ Bitcode for developers who require Bitcode, but that’s not everyone. Also, depending on how #2332 plays out, Xcode 6.4 may end up being half of our toolchain.

**Comment by incanus** [comment]
Well, I’m more thinking our own release process, not the general case. Yes, other folks may use `make ipackage`, but they could always comment out or adjust the lock.

**Comment by friedbunny** [comment]
This is taken care of now by building for distribution on CI.
