### ISSUE TITLE
Lots of dsymutil errors

### ISSUE THREAD

**Issue by parrots** [mapbox/mapbox-gl-native#2890]
Using the latest branch podspec (ios-v3.0.0-pre.3/ios/Mapbox-iOS-SDK.podspec) I'm getting new build warnings when building with mapbox seems it can't find files for the required architecture. This seems to be a regression as the error is not in the current public SDK.

FYI I am running with bitcode turned _off_ for my builds.

![screen shot 2015-10-30 at 7 36 57 pm](https://cloud.githubusercontent.com/assets/171163/10860581/9e62db90-7f40-11e5-9f09-de6b92618a79.png)

**Comment by 1ec5** [comment]
This was another local build, apparently. @parrots, can you confirm that the pre.1 build builds cleanly?

/cc @incanus

**Comment by incanus** [comment]
Yeah, it was, but I don't see what the problem is in the setup. I think @parrots that this is not a blocker for you? But we should get to the bottom of it. 

Maybe building on Bitrise will sidestep this. https://github.com/mapbox/mapbox-gl-native/issues/2844

**Comment by parrots** [comment]
Not a blocker, pending Apple not rejecting my app submission ;)

**Comment by incanus** [comment]
Do you still see this at all @parrots? We are on `3.0.0-pre.8` now. We also provide a build now without Bitcode (see e.g. https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.0.0-pre.8).

**Comment by incanus** [comment]
Moving off milestone since no one else is seeing this.

**Comment by parrots** [comment]
Sorry for the delay. I just linked against pre-8 and I still see the errors
at build time.

**Comment by parrots** [comment]
Scratch that, kinda. I don't see the warnings when building for device
anymore, I only see it when building for the sim.

**Comment by 1ec5** [comment]
If this hasn’t gone away with the switch to a static framework and more aggressive stripping in 3.0.1, the switch to a dynamic framework in #3183 probably will.

**Comment by 1ec5** [comment]
> FYI I am running with bitcode turned _off_ for my builds.

I missed this detail. 3.0.0 and above have Bitcode enabled; to build without Bitcode, you need to use a different “[no-bitcode](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.0.1)” binary that isn’t referenced by the Mapbox iOS SDK podspec – you’ll have to install the framework manually.

Once #3183 lands for 3.1.0, we aren’t planning to produce official, Bitcode-free builds, but the build system will still support that configuration: you’d run `make ipackage BITCODE=NO`. Does that sound feasible to you?

**Comment by parrots** [comment]
Yep, that works!

**Comment by 1ec5** [comment]
Great!
