### ISSUE TITLE
Update to build tools 23.0.2

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2891]

**Comment by bleege** [comment]
I need to temporarily revert this back to using Android Build Tools 23.0.1 to [test an internal issue](https://github.com/mapbox/gl-internal/issues/340#issuecomment-153389490).  Will go back to 23.0.2 when completed.

**Comment by bleege** [comment]
Waiting for Travis CI to approved the changes in #2911.  Will leave this ticket open after merge as we'll need to go to `23.0.2` at some point.

**Comment by bleege** [comment]
Just merged in #2911.  Will conduct the internal tests now.

**Comment by ljbade** [comment]
@bleege We can bring this back now.
