### ISSUE TITLE
Bitrise failing due to missing mason iOS 9.1 binary

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2894]
@incanus Bitrise is currently failing due to missing `automake` when trying to build libuv 1.7.5

It appears the problem is that a ios/9.1 mason binary is missing.

See https://www.bitrise.io/build/32f126b6001d6717

**Comment by mikemorris** [comment]
We added `automake` to the list of deps in https://github.com/mapbox/mapbox-gl-native/pull/2622, however we should be able to use the iOS 9.0 binary on 9.1.

/cc @incanus @1ec5 for thoughts on how specific we need to be regarding iOS versioning in context of https://github.com/mapbox/mason/issues/38

**Comment by ljbade** [comment]
Hmm I rebased my branch to pull in the new `bitrise.yml` file from https://github.com/mapbox/mapbox-gl-native/issues/2898

It now makes it past the previous stopping point and fails at a test.

**Comment by ljbade** [comment]
@incanus confirmed there are still random test failures.

It looks like someone added a iOS 9.1 mason binary.

@mikemorris Should I keep this open for iOS versioning discussion, or move that to new ticket?

**Comment by mikemorris** [comment]
Tracking iOS/OS X versioning in https://github.com/mapbox/mason/issues/38 @ljbade

**Comment by mikemorris** [comment]
Hit this again with iOS 9.2 @springmeyer https://github.com/mapbox/mapbox-gl-native/pull/3301#issuecomment-164820040
