### ISSUE TITLE
Custom overlays on Android

### ISSUE THREAD

**Issue by kaoskorobase** [mapbox/mapbox-gl-native#2895]
We're currently using the legacy Android SDK (0.7.4) with a custom map style and custom overlay classes (subclasses of `SafeDrawOverlay`). I can't find anything regarding drawing custom overlays in the GL SDK, any hints how we can make the transition from the old to the new SDK?

We probably can't continue to use the old SDK as there seems to be a marker drawing bug on Android 6.0 that we hope to get rid of by upgrading.

**Comment by ljbade** [comment]
We don't directly support custom layers currently.

However you should be able to implement a custom `View` subclass that draws on top of `MapView`. Similar to how we implement the GPS marker (see `UserLocationView`).

The trick though is to sync the overlay and map views to avoid jumpiness and lag. I found the best place to read the map's view transform (ie the `to/fromScreenLocation` functions) is in the `onSurfaceTextureUpdated` callback inside `MapView`. We don't currently have this exposed as a public function, but it would be easy to make a PR for this.

/cc @bleege @tobrun @zugaldia

**Comment by kaoskorobase** [comment]
Thanks, we'll try that! For the bug I've mentioned there's actually a quick workaround (https://github.com/mapbox/mapbox-android-sdk-legacy/issues/725), but in the long run we'll have to port our app to the new SDK.

**Comment by ljbade** [comment]
Closing this issue for now, reopen if you have issues implementing a custom View overlay.

**Comment by DavidMont** [comment]
I'm now porting my legacy map to this wonderful gl map , but one of my problems is overlay, I badly needed this overlay , is it ok if I ask some guidance on creating such overlay?

**Comment by tobrun** [comment]
@DavidMont, have you taken a look at MarkerViews? these can be used to overlay a View object on a LatLng on a map.

**Comment by DavidMont** [comment]
@tobrun ok thanks for the info, ill be back if i have problem.

**Comment by DavidMont** [comment]
@tobrun bro, Im having problem `MarkerViews` only allows bitmap images right? But I want to customize an overlay that has a dynamic radius. Where should I start? I've been reading `Annotations` but I cant seem to find the `onDraw`.

**Comment by tobrun** [comment]
MarkerView, allow any kind of View object to be shown as an annotation. This Activity contains multiple examples: https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java

**Comment by DavidMont** [comment]
@tobrun wow thanks

**Comment by DavidMont** [comment]
@tobrun do I need an adapter everytime I add a new Custom Annotation? kind of weird , I thought I would see `paint` or `onDraw` stuff

**Comment by DavidMont** [comment]
@tobrun im having problem with 

> updating Custom Annotations if camera or radius changes

Do you have an example how do I mitigate this"?

**Comment by tobrun** [comment]
You can use the following interface:

```java

    /**
     * Interface definition for a callback to be invoked when the camera changes position.
     */
    public interface OnCameraChangeListener {
        /**
         * Called after the camera position has changed. During an animation,
         * this listener may not be notified of intermediate camera positions.
         * It is always called for the final position in the animation.
         *
         * @param position The CameraPosition at the end of the last camera change.
         */
        void onCameraChange(CameraPosition position);
    }
```

You can register that interface in `MapboxMap#setOnCameraChangeListener`, the `CameraPosition` object passed in as param in `onCameraChange` exposes `position.zoom`.

@cammace: maybe an idea to add an example showcasing this interaction?

**Comment by DavidMont** [comment]
@tobrun yes i know that , but how do I update the adapter?  because inside the adapter only I can access the custom-view.

**Comment by tobrun** [comment]
you can implement that interface on the adapter itself:

eg. `MyCustomAdapter extends ViewMarkerAdapter implements OnCameraChangeListener`

**Comment by DavidMont** [comment]
oh that was stupid of me, thank you

**Comment by DavidMont** [comment]
hmm I hope adding `OnCameraChangeListener` should be array, cause I might be using it for other classes

**Comment by BharathMG** [comment]
@tobrun Thanks for this awesome sdk :) I want to add custom Polyline in my mapview. For this, can I add a View on top of Mapview without specifying any location as my polyline points would have locations in it? In the previous SDK (deprecated one), I would get addOverlay which would take care of calling my onDraw method. How can I achieve this now? I see only MarkerView for using custom annotations in Mapview but that needs fixed geographic location.

**Comment by BharathMG** [comment]
Never mind, I can see the ViewMarker adapter implementation. I think I will be able to use getView method to add an overlay.

**Comment by DavidMont** [comment]
@tobrun i has a problem, It does not update but I can create.  here is the [link](spurdow/SimpleCircleView) could you help me out?

**Comment by DavidMont** [comment]
@tobrun it seems like I have to create over and over again, when progress changes in the slider, I think its too soon to convert all of my mapping strategy (from legacy to gl) to this new one. Theres some bugs also when I put a marker into a specific location when I drag the camera the marker follows, it doesnt stick to the location unless i refresh their location again.

**Comment by cammace** [comment]
@BharathMG: adding an addition overlay/layer on top of the map is something we are currently working on, you can follow along the ticket [here](https://github.com/mapbox/mapbox-gl-native/issues/5610).

@DavidMont: If I understand correctly, you are trying to update a marker view property depending on the state of the slider? Sorry to hear this SDK isn't ready for your app needs, If you spot a bug such as the one you mentioned, it's always a good idea to open a issue so we can get it fixed. It sounds like you might have been anchoring your marker incorrectly or the icon has padding surrounding it though. The marker views currently consume touch events, but we have an [open issue to fix this](https://github.com/mapbox/mapbox-gl-native/issues/5388). 

For future support questions, please reach out through the [Mapbox contact page](https://www.mapbox.com/contact/).

**Comment by DavidMont** [comment]
@cammace yes correct, Yes about the bug I will be replicating it as soon as I can. I think the marker bug on not locking on map (I encountered also) is fixed when upgrading mapbox to snapshot releasee.
