### ISSUE TITLE
Missing Labels at Initial Zoom Level

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#2897]
I started seeing missing labels at the initial zoom level. Zooming either in or out causes them to appear.
The screen shots below have "Los Angeles" missing from the initial zoom level.

![simulator screen shot nov 2 2015 1 31 30 pm](https://cloud.githubusercontent.com/assets/417933/10893455/0ede8e4c-8166-11e5-9635-505216f031a4.png)
![simulator screen shot nov 2 2015 1 31 37 pm](https://cloud.githubusercontent.com/assets/417933/10893454/0ecf6020-8166-11e5-933c-dc9154939c8d.png)
![simulator screen shot nov 2 2015 1 31 34 pm](https://cloud.githubusercontent.com/assets/417933/10893456/0ee087a6-8166-11e5-8230-6ea709229ddc.png)

**Comment by ljbade** [comment]
@jfirebaugh could this be from label fading (eg https://github.com/mapbox/mapbox-gl-native/issues/2264)

**Comment by picciano** [comment]
Seems to have been fixed by https://github.com/mapbox/mapbox-gl-native/issues/2897

**Comment by picciano** [comment]
Thanks!

**Comment by mikemorris** [comment]
Yay, glad that fixed it @picciano!

**Comment by mb12** [comment]
@mikemorris how did #2901 fix it? It does not seem to impact the code path in ios/continuous mode.

**Comment by jfirebaugh** [comment]
Yeah, I'd be surprised if #2901 actually fixed this. It's a change of behavior only for `MapMode::Still`.

**Comment by picciano** [comment]
Odd. Reopen this if you want. I was unable to reproduce the problem after getting the commits from the past ~day.
