### ISSUE TITLE
move Bitrise iOS config to bitrise.yml

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2898]
See https://github.com/bitrise-io/bitrise-yml-collection/blob/master/general/use-bitrise-yml-from-repo/bitrise.yml. Already moved secret variables into Bitrise's secure variables section.

**Comment by incanus** [comment]
Ok @mapbox/gl, here's the deal with Bitrise. 

1. As of https://github.com/mapbox/mapbox-gl-native/commit/f59d4ba920bcd132a9e0841a993f1559d96fd480 (already in `master`), the config for running thorough our steps for Bitrise has been moved out of their GUI workflow builder and into [`bitrise.yml`](https://github.com/mapbox/mapbox-gl-native/blob/f59d4ba920bcd132a9e0841a993f1559d96fd480/bitrise.yml) in the repo root (for whatever branch). 

1. The Bitrise config for the repo has been set to just run the relevant branch's `bitrise.yml`. 

1. If you want to change the `bitrise.yml`, do so and use the `bitrise` CLI tool (`brew install bitrise` or [manual install](https://github.com/bitrise-io/bitrise/releases)) to `bitrise validate`. 

1. Change the [`primary`](https://github.com/mapbox/mapbox-gl-native/blob/f59d4ba920bcd132a9e0841a993f1559d96fd480/bitrise.yml#L17) workflow in your branch to see how changes will be run on Bitrise before merging them to `master`, affecting all branches (since all branches run their respective `primary` workflow). 

1. You can also create custom workflows in the `bitrise.yml` beyond the default `primary` one, such as eventually where we will have a `roll_build` or similar workflow to address https://github.com/mapbox/mapbox-gl-native/issues/2844. 

More on Bitrise's steps library (for example, we use the `select-xcode-version`, `script`, `xcode-test`, and `slack` steps): https://github.com/bitrise-io?utf8=✓&query=steps

**Comment by 1ec5** [comment]
When the dust settles, can you check this information into the repo or the wiki repo? It’ll be easier to find that way.

**Comment by incanus** [comment]
Will do.

**Comment by incanus** [comment]
:point_right: https://github.com/mapbox/mapbox-gl-native/wiki/Bitrise-workflow-details

**Comment by ljbade** [comment]
There is now a new "rebuild" button top right.
