### ISSUE TITLE
Update make Wrapper Gradle Tasks

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2899]
The `make` wrappers from #2434 no longer work after #2032.  Let's update the `workingDir` values to get them working again.

Will also move these wrappers to `MapboxGLAndroidSDK` so that they're self contained and easier for CI servers to access them.

**Comment by ljbade** [comment]
Ah sorry @bleege I totally overlooked these wrappers in the move.

**Comment by bleege** [comment]
Rebased and merged.
