### ISSUE TITLE
addMarker Crash on Unrooted device.

### ISSUE THREAD

**Issue by cablegunmaster** [mapbox/mapbox-gl-native#2910]
I tested the mapbox Android 5.1 (unrooted) with Android SDK 2.2.0

Situation:
the map is loaded and we called 'addmarker' function.
NativeMapview.class line 342 setSprite this.nativesetSprite has a issue which crashes the mapbox.
I can't debug further as it is a private class.

Line in application:
```php
mapView.addMarker(new MarkerOptions().title("Test 500").snippet("xxxxx").icon(kazerne_sprite).position(new LatLng(65.218834, 6.589681)));
```
Works on: Api 16.

unrooted device*

**Comment by tobrun** [comment]
@cablegunmaster,

I was not able to reproduce your issue on Android 5.1.0, see screenshot below.

<img width="528" alt="screen shot 2015-11-03 at 21 50 33" src="https://cloud.githubusercontent.com/assets/2151639/10921287/fe0c4f86-8274-11e5-819b-f434c2819a41.png">

This is the code I used to create this marker:
```java
Sprite sprite = new SpriteFactory(mMapView).fromResource(android.R.drawable.ic_delete);
mMapView.addMarker(new MarkerOptions().title("Test 500").snippet("xxxxx").icon(sprite).position(new LatLng(65.218834, 6.589681)));
```

Could you give me more information on how you are creating your `kazerne_sprite`?

**Comment by ljbade** [comment]
Also a the crash stack trace from logcat will be valuable.

**Comment by cablegunmaster** [comment]
Too bad I can't reproduce it, as the device itself has been flashed with a new version. 

I haven't saved the tomcat log but the debugger pointed to NativeMapview.class line 342 setSprite this.nativesetSprite. I have no idea what the problem might be, but without the addMarker code the mapbox works as intended. the errorcode from top of my head had something to do with UI Thread system call and garbage collection. and finally it crashed because the app presumably was onresponsive according to Android.

as for the ```kazerne_sprite```
```JAVA
kazerne_sprite = spriteMaker.fromDrawable(ContextCompat.getDrawable(this, R.drawable.kazerne_klein));
```
This is just a picture file. png. works with all the other versions. nonissue.

Close until further tomcat logs, and relevancy.
