### ISSUE TITLE
Make Marker.getId not internal

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2914]
Currently `Marker.getId` is internal as we have a note as such in the JavaDoc. This was to provide flexibility to change how core GL tracks markers. Instead it is possible to use `hashMap()` to generate a unique ID.

However after a customer support request I noticed that Google does exposes a `String getId()`. From https://developers.google.com/android/reference/com/google/android/gms/maps/model/Marker.html#getId%28%29

We should document getId() as usable.

**Comment by ljbade** [comment]
Does everyone agree?

**Comment by tobrun** [comment]
:+1:

**Comment by zugaldia** [comment]
+1

**Comment by ljbade** [comment]
@tobrun @bleege @zugaldia see the comment from https://github.com/mapbox/mapbox-gl-native/commit/83cf2197fa544481295d62221d7d7f294d466d6f

The best way I can think is to build a layer of indirection between public and internal IDs via a `SparseArray`? (however this might hurt performance in the bulk markers test)

Otherwise we will just have to forget about exposing IDs until improvements to the core GL layer in this aspect make it to our roadmap.

**Comment by tobrun** [comment]
>The best way I can think is to build a layer of indirection between public and internal IDs via a SparseArray? (however this might hurt performance in the bulk markers test)

Go with `SparseArray` this is what Google advices. FWIW an end user will probably use a custom WindowAdaper, linking issue #264 for this. This WindowAdapter should use this id system as well.

**Comment by tobrun** [comment]
Google uses a [HashMap<String, Collection>](https://github.com/googlemaps/android-maps-utils/blob/master/library/src/com/google/maps/android/MarkerManager.java#L41) to store markers

**Comment by tobrun** [comment]
Instead of only exposing `getId`, I think we should open this up to allow subclassing of Markers.
This is something that is [possible with the iOS library](http://stackoverflow.com/questions/34425217/ios-mapbox-pass-custom-info-through-annotation) and this would solve initial issue as well.

**Comment by zugaldia** [comment]
Related: https://github.com/mapbox/mapbox-gl-native/issues/3382

**Comment by tobrun** [comment]
My suggestion from https://github.com/mapbox/mapbox-gl-native/issues/2914#issuecomment-172842032 landed with #3756. Now we can experiment with subclassing and allowing end developers to have their own id set, Internally we are using a LongSparseArray for managing our Annotations. Closing for now.

**Comment by zugaldia** [comment]
@tobrun Do you see this code affecting or fixing https://github.com/mapbox/mapbox-gl-native/issues/3382 ?

**Comment by tobrun** [comment]
@zugaldia not affecting but also not fixing :)
