### ISSUE TITLE
Remove Fabric Crashlytics Key From TestApp

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2915]
Related to #1668, `io.fabric.ApiKey` does not need to be in `AndroidManifest.xml`.

**Comment by bleege** [comment]
The Travis CI build is failing for #2917 on the Android parts because it can't find the `io.fabric.ApiKey` in `AndroidManifest.xml`.  

<img width="838" alt="screen shot 2015-11-03 at 4 20 57 pm" src="https://cloud.githubusercontent.com/assets/989928/10923655/d7c9cbf0-8247-11e5-9238-9de98c9bb8ed.png">

**Comment by bleege** [comment]
Confirmed that it's crashing on `gradle assembleRelease` flavor of build.

<img width="601" alt="screen shot 2015-11-03 at 4 43 17 pm" src="https://cloud.githubusercontent.com/assets/989928/10924069/012f9252-824a-11e5-9ff2-6212b2b5f67b.png">

**Comment by bleege** [comment]
Changing Fabric setup to only run when in `Debug` flavor Gradle builds.  This allows it to be enabled in local development environments (where it's needed), but NOT run in CI environments where it won't have access to credentials and it's not needed as the TestApp is not intended for distribution / release anyway.

Will see how Travis CI likes this.

**Comment by bleege** [comment]
So Travis CI doesn't like this one bit.  For whatever reason it's non plussed about the `Release` builds (even though they work just fine locally), but after further inspection even if it wasn't grumbling about `Release` builds there's still a `Debug` build in the matrix which means that it'd have a legitimate reason to not work.  So this means are options are:

1. Remove the `Debug` build from the Travis CI build matrix
1. Leave things as is with the Fabric ApiKey

![screen shot 2015-11-04 at 10 12 59 am](https://cloud.githubusercontent.com/assets/989928/10944049/d9073418-82dc-11e5-9d9e-02089c9144ac.png)

/cc @jfirebaugh @incanus

**Comment by jfirebaugh** [comment]
What's the error? Can we fix the root cause?

**Comment by bleege** [comment]
The error is that the Fabric engine can't find an apiKey so that it can work properly when it's compiled into the TestApp.  This is due to it being removed from the TestApp's `AndroidManifest.xml` and because the other option of saving it in `fabric.properties` defeats this whole purpose if we commit it to GitHub.  The only way to fix this is to remove the `Debug` build, leave things as is, or remove Fabric from the TestApp which impacts day to day development.

The `Release` flavor failures are somehow else off and shouldn't be.  Fabric is only setup to run in `Debug` mode in [this branch](https://github.com/mapbox/mapbox-gl-native/compare/2915-remove-public-key).  I'm chalking this up to Travis being Travis.

`Debug` flavor example --> https://travis-ci.org/mapbox/mapbox-gl-native/jobs/89119327

```java
ERROR - Crashlytics Developer Tools error.
java.lang.IllegalArgumentException: Crashlytics found an invalid API key: null. 
Check the Crashlytics plugin to make sure that the application has been added successfully! 
Contact support@fabric.io for assistance.
	at com.crashlytics.tools.android.DeveloperTools.processApiKey(DeveloperTools.java:326)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:466)
	at com.crashlytics.tools.android.DeveloperTools.processArgs(DeveloperTools.java:299)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:270)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
```

**Comment by ljbade** [comment]
@bleege you might be able to use a Travis secure environment variable and in the Travis build script just write it out to a `fabric.properties` file via `echo`

**Comment by tobrun** [comment]
> @bleege you might be able to use a Travis secure environment variable and in the Travis build script just write it out to a fabric.properties file via echo

:+1:

**Comment by danielgomezrico** [comment]
@ljbade but then the key will not be on the repo?

**Comment by bleege** [comment]
The combination of not using the NDK support as originally thought in #1668 and the `ApiKey` being publicly visible in GitHub has made this something that we should revisit at a later date.  So for the time being I've removed Crashlytics from the TestApp and changed the `apiKey` and `buildSecret` so that Mapbox can continue to use Fabric / Crashlytics internally.

**Comment by mumayank** [comment]
@bleege I'm going thorough the same problem. ApiKey in Manifest is not secure even after obfuscation, is it? What is the alternate?

**Comment by bleege** [comment]
@mumayank We ended up removing it from the TestApp.  That said it looks like the Fabric feature set has been updated, so I'd recommend reviewing the new [Fabric Documentation](https://docs.fabric.io/android/crashlytics/introduction.html).
