### ISSUE TITLE
MapView.setAccessToken() should trim whitespace

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#2919]
Per #2912, [`MapView.setAccessToken()`](https://github.com/mapbox/mapbox-gl-native/blob/2b5b6fad96a38837da21300e8541a7c9a69c19a5/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L1564) should trim whitespace from either end before validating the access token. It doesn’t look like `MapView` needs to do any style URL validation independently of mbgl, since it traffics in `String`s the whole way.

/cc @ljbade

**Comment by bleege** [comment]
Rebased, discussed the finer points of Java Annotations with @1ec5, and merged.
