### ISSUE TITLE
Update Gradle Wrapper To 2.8

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2921]
The current wrapper is on Gradle 2.5.  Let's update to 2.8 which was released in October.

**Comment by ljbade** [comment]
Hmm I need to sign up for gradle update emails.

**Comment by ljbade** [comment]
OK I set up an IFTTT for https://docs.gradle.org/current/release-notes (as well as ones for the other bits of Android SDK and NDK).

At some stage I should set up emails for all the other dependencies...

**Comment by ljbade** [comment]
Changes from 2.5 to 2.8 to note:
- Gradle wrapper can now verify the sha hash - https://docs.gradle.org/2.6/userguide/gradle_wrapper.html#sec:verification
- we strongly recommend you regenerate your gradle-wrapper.jar with Gradle 2.7

Expect more frequent releases:
> With this release, the Gradle team moves into a more rapid release cycle, with a goal to release a new version of Gradle every 4-6 weeks

**Comment by tobrun** [comment]
Gradle 2.8 introduces the `--continuos` flag, which allows to automatically rebuild on file change.
OK, not really applicable for Android Development but will be super cool for many other projects!

**Comment by bleege** [comment]
Faster build script compilation and incremental builds.  \o/

![screen shot 2015-11-05 at 3 12 48 pm](https://cloud.githubusercontent.com/assets/989928/10981863/cb9d40e4-83cf-11e5-9ca7-eac326d7abe8.png)


I'm also setting this up to pull the `-bin` version instead of `-all` as it saves 20 MB of download time and bandwidth.

**Comment by bleege** [comment]
Doh!  Just noticed @ljbade's PR #2940.  I see that it didn't regenerate the `gradle-wrapper.jar` so I'll continue on with PR #2947 and make it do so.

**Comment by bleege** [comment]
Rebased and merged.
