### ISSUE TITLE
Mark state as invalid instead of restoring

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#2925]
In when the `GLContextMode` is `Shared`, we're restoring the GL state at the previous frame's end. Instead of actually setting the old values again, we should mark all of these values as invalid so that the first attempt to set the GL state always goes through (== ignore the cached value).

When we find that this causes interoperability issues, it means we're not setting enough state prior to our draw calls, and we should fix that instead of always blindly restoring the state.

**Comment by jfirebaugh** [comment]
Fixed in #2943.
