### ISSUE TITLE
share custom Bitrise step(s)

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#2927]
See `bitrise share`. We could consider our own `mapbox` StepLib or sending a PR upstream to https://github.com/bitrise-io/bitrise-steplib, but either way, we can share this out to make it easier on our own other repos.

**Comment by jfirebaugh** [comment]
I think we should avoid the Bitrise workflow as much as possible, in favor of running shell scripts checked into to the repo. This keeps things simple and avoids CI vendor lock in.
