### ISSUE TITLE
MGLPointAnnotation bearing / rotation 

### ISSUE THREAD

**Issue by iCyberon** [mapbox/mapbox-gl-native#2929]
Hey guys,

I'm tying to set the bearing or rotate the MGLPointAnnotation. Any suggestions? Also, when I rotate the map, markers automatically rotate, is there any way to disable this behavior?

**Comment by incanus** [comment]
This translates to [`icon-rotation-alignment`](https://www.mapbox.com/mapbox-gl-style-spec/#icon-rotation-alignment) and [`icon-rotate`](https://www.mapbox.com/mapbox-gl-style-spec/#icon-rotate) under the hood in the style. I think this will lean on #837, which is in active development, but will need to be plumbed through to the annotations API for such functionality.

**Comment by 1ec5** [comment]
Also relates to #2528.

**Comment by iCyberon** [comment]
Hey guys, any news?

cc @1ec5 @incanus

**Comment by 1ec5** [comment]
@iCyberon, we’re actively working on #837. Once that work is finished and we have an Objective-C API for runtime style manipulation, you’ll be able to configure point annotations in [a number of ways](https://www.mapbox.com/mapbox-gl-style-spec/#symbol).

**Comment by friedbunny** [comment]
Runtime styling exists now — please use that if you require icon rotation.
