### ISSUE TITLE
Parts of polyline not appearing initially

### ISSUE THREAD

**Issue by 3ph** [mapbox/mapbox-gl-native#2936]
I'm drawing trail (polyline) and sometimes bits of it doesn't seem to be displayed on some tiles. When I zoom in slightly it does appear but when I zoom out again it would disappear. Attached screenshots to demonstrate. No debug messages from Mapbox appear in the console... I'm using 2.1.2 pod.

![img_1064](https://cloud.githubusercontent.com/assets/6635044/10955180/dfe34bca-83b6-11e5-9701-56fd392b812e.PNG) ![img_1065](https://cloud.githubusercontent.com/assets/6635044/10955181/dfeaab5e-83b6-11e5-8331-5a74f5415b31.PNG)

**Comment by friedbunny** [comment]
@incanus @jfirebaugh Could this be a simplification error?

**Comment by jfirebaugh** [comment]
Looks more like a race condition with vector tile generation from the shape or something.

@3ph Is it possible to test this with current master? The code that could be causing this has changed quite a bit recently.

**Comment by incanus** [comment]
@3ph You could grab the latest prerelease like so: https://github.com/mapbox/mapbox-gl-native/issues/2205#issuecomment-153878309

**Comment by 3ph** [comment]
I've tried it with pre3.0.0 and the problem seems to be gone.

**Comment by 1ec5** [comment]
Thanks for verifying!
