### ISSUE TITLE
iOS GL - Using Your Location blue status bar on iOS 8

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-gl-native#2945]
After upgrading to GL, if the user sets location preferences to `While Using the App` on iOS 8, they will get the blue status bar that reads `xxx is Using Your Location` when they leave our app.  This does not happen on iOS 9.  This was also not happening on 8 with the non-GL version of MBXMapKit.

Is this expected behavior or can we get this banner to go away?  We've seen it on v2.1.2 and v3.0.0-pre4.

**Comment by johnnewman** [comment]
I'm still seeing a blue bar in iOS 8.4 using Mapbox 3.1.1.  Any ideas?

**Comment by friedbunny** [comment]
The second part to this, #3641, unfortunately didn't make it in to v3.1.x. I'm going to finish up #3641 and get it merged as soon as possible, but we're not sure yet when the next release will be. If there's a 3.1.2, it should be included.

**Comment by friedbunny** [comment]
Fixed for good by #4115.
