### ISSUE TITLE
Programmatic animations fail to recalculate zoom-dependent properties

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-gl-native#2946]
Animating a region change sometimes doesn't redraw the map's streets/text for the correct level.  When zoomed into Chicago and animating to the state of New York, the map initially renders like below:

![newyork1](https://cloud.githubusercontent.com/assets/1591735/10981006/052b0aaa-83d3-11e5-9d55-a8f53649f86c.png)

After slightly pinch zooming, the map will redraw itself at the correct level:

![newyork2](https://cloud.githubusercontent.com/assets/1591735/10981021/10ece8ae-83d3-11e5-9dc3-846480610fb7.png)

This happens when calling `setCenterCoordinate:zoomLevel:animated:` with `YES` for animated.  We've seen it on v2.1.2 and v3.0.0-pre4.

**Comment by 1ec5** [comment]
This would be caused by MGLMapView issuing an `update()` of type `Update::Render` instead of `Update::Zoom`.

**Comment by 1ec5** [comment]
Reproduces with the following code:

```objc
[self.mapView setCenterCoordinate:CLLocationCoordinate2DMake(41.87542, -87.62497) zoomLevel:18 animated:NO];
```

then:

```objc
[self.mapView setCenterCoordinate:CLLocationCoordinate2DMake(42.908, -75.388) zoomLevel:6 animated:YES];
```

**Comment by 1ec5** [comment]
`-setCenterCoordinate:zoomLevel:animated:` uses `easeTo()`, which does use `Update::Zoom` at every step along the way, just like the pinch gesture recognizer. So I’m not sure what’s missing.
