### ISSUE TITLE
Building with Source Instructions Unclear, links broken. 

### ISSUE THREAD

**Issue by bessermt** [mapbox/mapbox-gl-native#2953]
Can someone explain:

https://github.com/mapbox/mapbox-gl-native/blob/master/docs/DEVELOP_ANDROID_LINUX.md

In particular the section on Building:

"You can then open android/java in Android Studio via "Import project (Eclipse ADT, Gradle, etc.)"."

I don't see the "android/java" in Android Studio. 

The links below that are broken, so I'm not sure where to get help.

"Next: get your app running on a hardware Android Device or simulator"

**Comment by ljbade** [comment]
@bessermt We moved the location from `android/java` to `android/` recently.

We forgot to update the docs.

**Comment by bessermt** [comment]
Thank you. I'm new to working on github projects. Do I fix the doc or does someone else do that?

**Comment by tobrun** [comment]
@bessermt 
We are already grateful that you have opened an issue for this. Thank you for that!
You can always fix the doc and make a Pull Request for it ([guidelines related for contributing](https://github.com/mapbox/mapbox-gl-native/blob/master/CONTRIBUTING.md)).

**Comment by bleege** [comment]
Thanks for pointing this out @bessermt.  Can you tell us more about why you're looking to integrate the SDK via building from the source code vs [installing a prebuilt SNAPSHOT build](https://www.mapbox.com/android-sdk/#gradle)?

**Comment by bessermt** [comment]
Sure. I want to create maps that allow for a couple of features I can't find anywhere (including Mapbox). My hope is that since this is open source, I can modify the code to do what I want. The features I want are:

1. Rectangular sized tiles.
2. Feeding tiles from local source with starter map included in app.
3. Sync local tiles with web when a web connection is available (even if app isn't running). 
4. Customized projection algorithm to allow for non-Mercator projection. 
5. Limit data to small subset of the world with limited zoom (approx 5 zoom levels, < 100 mi^2, and that is an extreme case). 

Did that help explain? Think this is possible?

I hope to change the code and make it available, so even if I can only do a few of these, maybe someone can help with other parts.

**Comment by mb12** [comment]
@bessermt is it possible to provide more details regarding  what you mean by "rectangular size tiles"?

**Comment by bleege** [comment]
That sounds awesome @bessermt!  Thanks for clarifying.  Please feel free to submit PRs in the future as this is definitely an open source project and we love working with others.  :+1: 

I was more curious as sometimes Android devs still prefer to compile everything themselves and may not know about the pre built library with built in dependency management.

**Comment by bleege** [comment]
I just updated the DEVELOP_ANDROID_LINUX.md to have the correct path.

Thanks again @bessermt!

**Comment by bessermt** [comment]
Thanks @bleege, I'm new to maps and open source development, so hopefully I can pull this off. We'll see. Any help is appreciated. Of course I'd share what might be helpful to others in return. 

Can you explain what a "PR?" is... Sounds like Change Request?

@mb12, I mean any tile that is not square. For example 256x256 is square, but a 128x256 tile is rectangular. I understand that squares are by definition rectangles, but that's not what I mean. Maybe I'm better off describing them as "non-square tiles", but that leaves open hexagons and other types of tiles. Does that help?

**Comment by bleege** [comment]
Fantastic!  Welcome to maps and open source development @bessermt!  We're happy to help.

> Can you explain what a "PR?" is... Sounds like Change Request?

PR is a [Pull Request](https://help.github.com/articles/using-pull-requests/).  It's a way for you to submit changes back to the original project [from your fork](https://help.github.com/articles/fork-a-repo/).

If this is new to you, don't worry.  GitHub has some great [Help Documents](https://help.github.com/) to you learn how this all works.

Welcome!
