### ISSUE TITLE
Respect order of executed lifecycle methods

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#2957]
In the testapp and later copied to the [documentation](https://www.mapbox.com/android-sdk/examples/), 
We are not respecting the order of the executed lifecycle methods of Activity.
This is a small adjustment but will lower friction with end developers.

Currently we have:
```java
    onCreate();
    onStart(); 
    onStop();
    onPause();
    onResume();
    onDestroy();
```

This should be adjusted to:
```java
    onCreate();
    onStart();
    onResume();
    onPause();    
    onStop();
    onDestroy();
```

@bleege 
@danswick

**Comment by bleege** [comment]
To clarify this is a cosmetic thing in the source code and documentation.  It has no impact on the SDK, apps, or runtime.

**Comment by tobrun** [comment]
Yes, this is purely to dot the i's and cross the t's.

**Comment by ljbade** [comment]
Yeah this makes sense. I originally just wrote them in the order I was reading the Android docs.

**Comment by bleege** [comment]
> Yes, this is purely to dot the i's and cross the t's.

Cool.  Thanks for clarifying this for everyone!  :+1:

**Comment by bleege** [comment]
This looks like @danswick finished this.
