### ISSUE TITLE
Serve iOS pod download from HTTPS

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#2961]
We currently serve our CocoaPod download from HTTP.

[Mapbox-iOS-SDK.podspec#L16](https://github.com/mapbox/mapbox-gl-native/blob/cb92290f9d486b7ece7168e1b42e5572a2b2c40c/ios/Mapbox-iOS-SDK.podspec#L16):

```ruby
  m.source = {
    :http => "http://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-#{m.version.to_s}.zip",
    :flatten => true
  }
```

/cc @incanus

**Comment by incanus** [comment]
Good call. I will hit this for next release.
