### ISSUE TITLE
merge SpriteAtlas+SpriteStore, GlyphAtlas+GlyphStore

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#2965]
For discussion. These classes don't really have a clear separation of responsibilities, and `SymbolBucket` depends on all of them, making for large parameter lists and the need for cross-thread synchronization in all four. Although there _should_ probably be more than two classes, it's not clear how to best divide them. I think if we merge them first, it will be easier to see how to split them up again in a better way.

cc @brunoabinader @kkaefer

**Comment by tmpsantos** [comment]
I do agree that they seem redundant, but IIRC we have mutexes for accessing the data on all of these classes, so merging them can potentially increase thread contention.

**Comment by mb12** [comment]
@jfirebaugh these should not be merged.  Sprite Atlas contains the actual image/texture that is uploaded to GPU. GL Native does not upload the entire sprite image to the GPU.  Individual symbol images are Bin packed into a sprite Atlas and the Atlas is uploaded to GPU. With this design one could potentially use multiple sprite images and still have one sprite Atlas for the map.

There is an unrelated  correctness bug in the usage of sprite atlas. We allow it to grow unbounded. This results in symbols not rendering on the map. You would have to enable debugSpritewarnings  to true to see these errors. I've filed a separate issue to track this.

**Comment by jfirebaugh** [comment]
Ok, thanks folks. I still think the current factoring is less than ideal, given that most clients of `*Store` are also clients of `*Atlas`, and vice versa. However, it looks like for the styles API I don't face any immediate blockers from this, so I'll leave it be for now.
