### ISSUE TITLE
ARM v5 is broken

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#2983]
I just tried the ARM v5 build on my Galaxy Nexus, and it is currently broken and only rendering black.

**Comment by ljbade** [comment]
It works on my Galaxy S6 however.

**Comment by bleege** [comment]
@ljbade Can you provide more details about the Galaxy Nexus?  What version of Android is it running?

**Comment by ljbade** [comment]
@bleege It is on 4.04 API 15. Running a clean image downloaded from the Google website.

**Comment by tobrun** [comment]
This issue was fixed with reintegration of `armeabi` in #3985 , closing.
