### ISSUE TITLE
Move Develpment Access Token ( token.txt ) Back To TestApp

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#2989]
As discussed in #2974 we should refactor `ApiAccess` so that we can move the Developer Access Token (aka `token.txt`) back to the TestApp.  This is because runtime configuration parameters should not be located in the SDK proper.  Instead they should always be located in external implementing apps.

This ticket will have similar goals as #1929 in that in order for it to be considered "done" it needs to support the following configurations:

* [x] Activity via XML Layout
* [x] Activity via Programmatically set (ie, MapView.setAccessToken())
* [x] App via `AndroidManifest.xml`
* [x] Fragment via XML
* [x] Fragment via Programmatically set

Access Tokens should be storable in the following manners:

* App's `R.string.*`
* App's Code
* App's `token.txt` (with corresponding .gitignore so it's not commit-able)

/cc @tobrun @ljbade @zugaldia

**Comment by ljbade** [comment]
@tobrun Nice work finding a work around. `getIdentifier` is something I did not know about.

**Comment by tobrun** [comment]
I'm not :100: sure that this will work for raw files :) 
Else I might need to introduce xml instead

**Comment by bleege** [comment]
@tobrun No worries.  Take a run at this and see where it leads.  The most important goal is to get any access token stuff out of the SDK proper.  :+1:

**Comment by tobrun** [comment]
Picking this as highest priority to fix

**Comment by tobrun** [comment]
Changes to current setup:
 - moved token.txt to testapp
 - replaced token.txt with config.xml
 - replaced ApiAccess internal system to resolve resources with getIdentifier
 - removed build.gradle generation of token.txt

These changes will not impact SDK users,
