### ISSUE TITLE
accesstoken needed?

### ISSUE THREAD

**Issue by AskinOharis** [mapbox/mapbox-gl-native#2996]
The legacy version was always free to use, meaning no accesstoken and no payment. Just to get it right ..the new native version just works with accesstoken and therefor payment (I know there is a free starter plan/pricing), also when I just use external tilesources like "OpenCycleMap"?
Thanks for clarification,
Askin

**Comment by 1ec5** [comment]
An access token is always required for accessing Mapbox-hosted maps, whether in the old raster SDK or this vector-based SDK. This is to prevent third-parties from hotlinking your Mapbox account's maps and racking up views on them. If you load a map not hosted by Mapbox (both the style and data source), then no access token is required, and it's up to the map's host to prevent any hotlinking if that matters to them.

To my knowledge, OpenCycleMap is still a raster style, so you'll need a compatibility shim like [this one for iOS](https://www.mapbox.com/ios-sdk/examples/raster-styles/).

**Comment by 1ec5** [comment]
To be clear, when it comes to vector tiles on iOS or Android, Mapbox does not count map views but rather counts monthly active users of your application – it's free up to 50,000 monthly active users. And all Mapbox accounts have access to default style such as Streets and Satellite.

**Comment by AskinOharis** [comment]
Ok ..thanks for your clarification ..helped me a lot!

**Comment by WrathChaos** [comment]
> An access token is always required for accessing Mapbox-hosted maps, whether in the old raster SDK or this vector-based SDK. This is to prevent third-parties from hotlinking your Mapbox account's maps and racking up views on them. If you load a map not hosted by Mapbox (both the style and data source), then no access token is required, and it's up to the map's host to prevent any hotlinking if that matters to them.
> 
> To my knowledge, OpenCycleMap is still a raster style, so you'll need a compatibility shim like [this one for iOS](https://www.mapbox.com/ios-sdk/examples/raster-styles/).

Hello @1ec5,
Sorry for resurrecting this issue. However, I need to know how to use the Mapbox without accessToken. We just want to use Mapbox's Camera and UserLocation modules. Is there any chance to use it without access token and use it our own tile server or another one?

Thank you so much.
