### ISSUE TITLE
bad label collision

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#2998]
The label collision in the top left seen here does not seem to happen in the same style viewed with gl-js. Needs investigation.

![mapbox-bad-labels](https://cloud.githubusercontent.com/assets/14778/11006401/dca2a918-8480-11e5-9c7e-c13a5e92e486.png)

**Comment by ansis** [comment]
https://github.com/mapbox/mapbox-gl-native/pull/3623 fixes the "University of Colorado Boulder" collision. The style uses `symbol-avoid-edges` and it was taking a [shortcut](https://github.com/mapbox/mapbox-gl-native/blob/ed0488d2e0e2166f5e2708abc34abe471b39c4ba/src/mbgl/renderer/symbol_bucket.cpp#L319) that assumes symbol-avoid-edges is working.

https://github.com/mapbox/mapbox-gl-native/pull/3640 fixes the "Central Campus Mall" bug
