### ISSUE TITLE
Android Style-Specific-Marker example is out of date

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-native#2999]
Copied from a bug report submitted through http://www.mapbox.com/contact: 

---------

The android SDK example for creating a Style specific marker contains an error. 
https://www.mapbox.com/android-sdk/style-specific-marker/

```
mapView.addMarker(new MarkerOptions()
  .position(new LatLng(-33.8999983, 18.4158234))
  .title("Cape Town Harbour")
  .sprite("harbor_icon"));
```

---------

This example should be updated to use `.icon()` instead. 

cc: @bleege

**Comment by ljbade** [comment]
@danswick I created an issue in the relevant doc repo.

**Comment by danswick** [comment]
:+1: thanks, @ljbade!
