### ISSUE TITLE
Add onConfigChanges as a feature Activity to test app

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3001]
Need to test orientation changes under this configuration, focus on restoring View-Gl elements correctly.

**Comment by ljbade** [comment]
Ideally we can test both flows for rotation, when we handle it, and when system handles it...

@tobrun Is this possible?

**Comment by tobrun** [comment]
Yeah, we can setup per activity how it handles configuration changes in the Manifest.
Is that what you mean with?
 > we handle it, and when system handles it
