### ISSUE TITLE
Shields are rotated along line

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3004]
Highway shields are being rotated like road labels:

![streets](https://cloud.githubusercontent.com/assets/1231218/11103279/55da9c7a-8876-11e5-9d3b-adb34d221cef.PNG)
![emerald](https://cloud.githubusercontent.com/assets/1231218/11103280/5a0a9908-8876-11e5-9b5f-331a55757560.PNG)

This regression appeared sometime within the past day or so. It does not reproduce in GL JS or in Mapbox iOS SDK v3.0.0-pre.5. It reproduces in both Streets and Emerald, so it isn’t related to mapbox/mapbox-gl-styles#227.

/cc @jfirebaugh

**Comment by jfirebaugh** [comment]
Bisected to a5625675890213f94de7632d4ef152ade627c9a5.

**Comment by 1ec5** [comment]
Only reproduces at z11 and above.

**Comment by ajashton** [comment]
(at z10 and below shields are attached to points, not lines)

**Comment by jfirebaugh** [comment]
I gave up on adding a test to the test-suite after a 4 hour yak shave.
