### ISSUE TITLE
iPhone 6 animation performance cut in half

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3005]
To state the obvious, #2922 cuts the maximum framerate down from 60fps to 30fps. Prior to #2922, MGLMapView would pan smoothly at 60fps (as confirmed by Xcode) on my iPhone 6 running iOS 9.1. Now it maxes out at 30fps, causing every animation to be choppy to an extent that’s difficult to ignore. (An `MGLTargetFrameInterval` of 1 unsurprisingly feels great.) Perhaps 30fps is beneficial for the iPod touch @adam-mapbox was testing on, but that should not come at the cost of performance on more current or more powerful hardware, where there is a greater expectation of smooth animations.

/cc @adam-mapbox @incanus @friedbunny @jfirebaugh

**Comment by incanus** [comment]
Maybe we can take a naive first cut at dividing devices into two camps — lower-end and higher-end — and choosing 30 or 60 as a result. Lower-end would probably include: 

- Both iPod touch generations
- iPad <= 3
- iPad mini <= 2
- iPhone <= 5

Something like that?

**Comment by adam-mapbox** [comment]
We can also try just making it 60 fps.  The essence of the fix is to do
things on a regular basis, not necessarily what exactly that basis is.  It
might be "good enough", even on slower devices.  I can take a look at this.

A better fix would be to do what Justin suggested.

**Comment by 1ec5** [comment]
I’ve been playing around with `MGLTargetFrameInterval` set to 1 all day on the aforesaid iPhone 6, and it feels great. Let’s treat 60fps as the default, then blacklist devices that are known to perform poorly, such as iPod touch.

**Comment by adam-mapbox** [comment]
Sure, sounds good.  I'd like to do a little bit of testing on my own time
about this, but I think this should work for now.

**Comment by adam-mapbox** [comment]
@1ec5 I went ahead and did some testing on this on the iPod touch, and it's going to be totally fine on all devices.  As I suspected, it's the act of doing things on a regular tick that helps the framerate's visible appearance, not so much when the tick arrives.  So even if the device can't quite keep up, it still is visually pleasing.

**Comment by 1ec5** [comment]
:tada:
