### ISSUE TITLE
raster-alpha test hangs

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#3007]
The raster-alpha test from test-suite hangs and has been disabled. We need to investigate and fix the hang.

**Comment by lucaswoj** [comment]
ref https://github.com/mapbox/mapbox-gl-test-suite/pull/57

**Comment by jfirebaugh** [comment]
Enabled and passing in e326d4972f6320c53be6ac0c696688f4918d4614.
