### ISSUE TITLE
Drawing two polylines simultaneously in iOS

### ISSUE THREAD

**Issue by beev** [mapbox/mapbox-gl-native#3010]
Is it possible to draw two polylines at once with the iOS SDK? I'm finding that adding a polyline (according to the method described in the quick start guide) is working fine, but trying to add an additional polyline is removing the previous one so I can never have two drawn on the map at the same time.

**Comment by incanus** [comment]
This doesn't sound right @beev. You are adding annotations? Are you sure you're not replacing them? Can you share some of you add code?

**Comment by beev** [comment]
Thanks very much for the reply. It turns out I was trying to reuse the same ivar for the two routes, so one was always replacing the other and the two could never exist at the same time. All sorted now :)
