### ISSUE TITLE
Excessive display of highway shields when using pitch

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#3014]
Is there a way to reduce the number of Highway shields displayed? Seems a bit overkill. :)

![slack_for_ios_upload png](https://cloud.githubusercontent.com/assets/417933/11132682/930d7bac-894e-11e5-85af-c16bd9107949.jpeg)

![screen shot 2015-11-12 at 3 04 15 pm](https://cloud.githubusercontent.com/assets/417933/11132697/acd5448e-894e-11e5-80d0-f554874b6c82.png)

**Comment by friedbunny** [comment]
There's a stale ticket about this here: https://github.com/mapbox/mapbox-gl-styles/issues/159

@nickidlugash may be able to offer some insight, as she's worked to improve shield over-density previously in #1840 and https://github.com/mapbox/mapbox-gl-style-spec/issues/269.

Also, I'm trying really, really hard not to make a Los Angeles traffic/freeways jab here — having just spent a good portion of my vacation this week on the 405. :grin:

**Comment by friedbunny** [comment]
Stale.
