### ISSUE TITLE
Tapping point annotation does not select it at z0

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3027]
Tapping a point annotation on iOS does not select it when the map is at zoom level 0.

/cc @incanus

**Comment by incanus** [comment]
Interesting. Previously, we've had render issues in that department (https://github.com/mapbox/mapbox-gl-native/issues/1279) and also, I would have suspected something in the original memory tile-based storage of points, but @jfirebaugh has refactored that into an R-tree recently (https://github.com/mapbox/mapbox-gl-native/pull/2673). I don't have much more to provide other than that context, though.

**Comment by RomainQuidet** [comment]
Globally tapping annotation should not only suppose user tapped near the annotation's coordinate. As with annotationImage offset, it should take it into account too. 
Internal code should be reworked for that.

**Comment by 1ec5** [comment]
This is fixed in the OS X port. Backporting to iOS is blocked on #3159.

**Comment by 1ec5** [comment]
This will be fixed in #3261.
