### ISSUE TITLE
Securely Accessing Android Signing File On AWS

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#3028]
To successfully publish the Android SDK as an `.aar` file the CI Server ([Bitrise](https://www.bitrise.io/)) needs to be able to download the GPG Secret token that's stored on AWS S3 using [AWS CLI](https://aws.amazon.com/cli/).  In order to do that a restricted AWS account needs to be configured that _can only download the file_ from the following location:

https://s3.amazonaws.com/mapbox-android-sdk/secring.gpg

@miccolis has graciously volunteered to help make this a reality.

**Comment by bleege** [comment]
Per discussion with @miccolis offline, the new URL is:

https://s3.amazonaws.com/mapbox/android/signing-credentials/secring.gpg

**Comment by bleege** [comment]
@miccolis Now that the CloudFormation file has been created, what needs to be done so that AWS knows about it and configures itself accordingly?

**Comment by miccolis** [comment]
@bleege we need to update the cloudformation in AWS, this is done via [mapbox-cli](https://github.com/mapbox/mbxcli#wave-the-travis-flag). We can get this doing real quick, just ping me when you get in.

**Comment by miccolis** [comment]
@bleege I updated the `travis-mapbox-gl-native` cloudformation template on AWS in `us-east-1`. If you look at the outputs you'll see `BitriseAccessKeyId` and `BitriseSecretAccessKey`. You can use the values of these to get the file from s3. with a command like;

```
AWS_ACCESS_KEY_ID=$BitriseAccessKeyId AWS_SECRET_ACCESS_KEY=$BitriseSecretAccessKey aws s3 cp s3://mapbox/android/signing-credentials/secring.gpg .
```

**Comment by bleege** [comment]
@miccolis Thanks for hooking up CloudFormation to AWS and for the CLI command.  I see the `BitriseUser` user in IAM and it's Access Key, however I don't see the Secret Access Key.  [According to the AWS Docs](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSGettingStartedGuide/AWSCredentials.html) it says I should click `Create Access Key` and then it'll tell me both the Access Key and the Secret Access Key.  This doesn't seem correct to me as there's already an Access Key in there that CloudFormation created.  Any advice on where to look to get the Secret Access Key for the CloudFormation created Access Key?

**Comment by miccolis** [comment]
@bleege the credentials are available as "Outputs" for the Cloudformation stack. To find them go to the  [Cloudformation console](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks?filter=active&tab=outputs) and filter for `travis-mapbox-gl-native`. You'll need to click  the stupid "View More Stacks" button twice to see it, but it's there. Click on the stack name and you should see the "Outputs" pane populate. The `BitriseAccessKeyId` and `BitriseSecretAccessKey` are what you're after.

**Comment by bleege** [comment]
Ah ha!  There they are!  I'll plug 'em into Bitrise as Secret Variables and give the whole process a spin this morning.

**Comment by bleege** [comment]
That did the trick!  I was able to have Bitrise run it's build and publish workflow and it worked great.  Thanks for making this happen and for the AWS education @miccolis!
