### ISSUE TITLE
Polyline and markers drawn underneath road in Streets style

### ISSUE THREAD

**Issue by tomtaylor** [mapbox/mapbox-gl-native#3037]
I've just built CityCyclist against c35f18fdbc, and I managed to get it into a situation, shortly after launch, where the route polyline and marker were drawn underneath the roads, but above the background colour. I quit and restarted and the issue went away, and I can't reproduce it again.

![img_9536](https://cloud.githubusercontent.com/assets/565/11169700/320a3af0-8bb7-11e5-8af6-5a77807ef6b2.jpg)

**Comment by friedbunny** [comment]
Interesting! /cc @jfirebaugh

**Comment by jfirebaugh** [comment]
Looks like this bug can happen when annotations are added before the style finishes loading. In that scenario, it's possible for the annotation layers to get added first, and then when the style JSON loads, the style layers get appended.

**Comment by tomtaylor** [comment]
@jfirebaugh that seems likely in this situation. Is it possible to serve the style JSON locally to reduce the likelihood of this?

**Comment by friedbunny** [comment]
Loading styles locally is broken (#3050) at the moment.

**Comment by Zakay** [comment]
+1 I'm having the same issue, is there no way to play with z indices as a temporary fix?

**Comment by Zakay** [comment]
@tmpsantos This commit seems to have created this issue: 36581f3d3015d525db92248004e9dc7477705694

**Comment by Zakay** [comment]
I have been rolling back commit after commit to find the commit that caused this issue, and I found a candidate: f9ebe54a6336431af98ebfb428d28a0513b2522d @jfirebaugh

**Comment by Zakay** [comment]
This happens also when adding annotations after loading the map.

**Comment by Zakay** [comment]
@jfirebaugh I've updated to latest and still get this issue, but much less now. I have re-place an annotation by long-press on the map. The annotation is sometimes visible and sometimes not.

**Comment by tomtaylor** [comment]
Yeah, I also managed to get an invisible annotation that became visible when I removed and readded it.

**Comment by Zakay** [comment]
To reproduce modify handleLongPress on the demo app to remove other annotations.
And then randomly place dropped pins on the map.

It's tiresome but sometimes it happens a lot and sometimes you need to give in some time.

This issue is the only blocking issue we have left before releasing a major version of our app, and really look forward to have this fixed. Rolling back is no option as latest commits also have fixed serious crashing issues we've had.

```objc
- (void)handleLongPress:(UILongPressGestureRecognizer *)longPress
{

    if (longPress.state == UIGestureRecognizerStateBegan)
    {
        MGLPointAnnotation *point = [MGLPointAnnotation new];
        point.coordinate = [self.mapView convertPoint:[longPress locationInView:longPress.view]
                                 toCoordinateFromView:self.mapView];
        point.title = @"Dropped Marker";
        point.subtitle = [NSString stringWithFormat:@"lat: %.3f, lon: %.3f", point.coordinate.latitude, point.coordinate.longitude];

        [self.mapView removeAnnotations:self.mapView.annotations];

        [self.mapView addAnnotation:point];
        [self.mapView selectAnnotation:point animated:YES];
    }
}
```


![850637981_15152414392574149406](https://cloud.githubusercontent.com/assets/315159/11273928/4403b21e-8ed6-11e5-9883-e9ff5ac1ef70.jpg)
![851333090_478228348502922907](https://cloud.githubusercontent.com/assets/315159/11273932/4a2a70a6-8ed6-11e5-94ba-7f633197b3e3.jpg)
![850632842_5503142534887511869](https://cloud.githubusercontent.com/assets/315159/11273940/54111c5a-8ed6-11e5-9ac1-58b1a5f0f355.jpg)

**Comment by jfirebaugh** [comment]
Please try out https://github.com/mapbox/mapbox-gl-native/commit/afa04de15286cdfa1cedc756d8fbe46a42e319a5 (`master`) or https://github.com/mapbox/mapbox-gl-native/commit/462af73b7eab4b568779fc3a13adcca009db84e1 (`release-ios-v3.0.0`) -- I believe that resolves the remaining issue.

**Comment by Zakay** [comment]
@jfirebaugh This seems to fix the case I mentioned in above post (re-adding an annotation when tile layer is fully loaded).

But can happen still when tile layer hasn't yet loaded fully. I have a test case, where I switch tile layer, and remove and re-add annotations. These annotations are now hidden and were not before.

(Its not related to this issue #1488, as I have a patch locally to re-add sprites to the spritestore when they are missing as an dirty fix until #1488 is fixed)

**Comment by jfirebaugh** [comment]
@Zakay, the original issue here is fixed. Can you please file a new issue, and include your test case?

**Comment by Zakay** [comment]
@jfirebaugh just got it working with removing and re-adding them with our own local patch. We of course look forwards remove our own patch when #1488 is fixed. Thanks for your solving this issue so quickly! Going to submit to Apple today, major release!
