### ISSUE TITLE
implement pulse effect on annotations

### ISSUE THREAD

**Issue by odedharth** [mapbox/mapbox-gl-native#3039]
Is there a way to implement a pulse effect on annotations in mapbox?

(something like this https://github.com/TransitApp/SVPulsingAnnotationView)

thanks

**Comment by friedbunny** [comment]
Except for the user location dot and the callout view, all annotations are drawn at the GL level and aren't readily accessible for these types of effects. The [user dot](https://github.com/mapbox/mapbox-gl-native/blob/c35f18fdbc94917c20cb675b6510c9feaed40f0c/platform/ios/MGLUserLocationAnnotationView.m)  currently does what you're asking, but drawing it on screen relies on [hardcoded updates](https://github.com/mapbox/mapbox-gl-native/blob/c35f18fdbc94917c20cb675b6510c9feaed40f0c/platform/ios/MGLMapView.mm#L3071-L3095) in `MGLMapView`.

Implementing arbitrary native views is covered in #1784.
