### ISSUE TITLE
Transparent Background In Android

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#3040]
@incanus is working on the [iOS version of this feature](https://github.com/mapbox/mapbox-gl-native/issues/3038).  Android [`SurfaceView`](http://developer.android.com/reference/android/view/SurfaceView.html) should be able to provide similar support as it extends from View.  Let's look into it and see if we can make it happen.

**Comment by tobrun** [comment]
Cool!

**Comment by ljbade** [comment]
Main change is to select a GL surface that is argb instead of the current rgb in C++ code

**Comment by cammace** [comment]
This works for texture view and was always possible if I understand correctly:

![ezgif com-video-to-gif 30](https://cloud.githubusercontent.com/assets/5652865/20157518/7a10f732-a6a3-11e6-89ca-b465d36aa3b3.gif)

But doesn't seem to be working using the new SurfaceView. If you set alpha on the map view to anything less then 1 it will be completely transparent, only displaying the widgets.

**Comment by snowpong** [comment]
@tobrun why was this closed?

**Comment by tobrun** [comment]
this was closed as part of an issue cleanup. As @cammace pointed out you can achieve this effect with a TextureView (this is something you can activate through mapboxmapoptions or xml). What would be the use-case for this feature? I could imagine this would have been usefull in the past before we had background layers.

**Comment by snowpong** [comment]
@tobrun I ask because I want to change the default black background of MapBox, and https://github.com/mapbox/mapbox-gl-native/issues/6575 pointed to this task as the solution to that issue. Now both of those are closed and I'm wondering what the proper way to set the background color is.

**Comment by tudormarze** [comment]
For whoever might come across this, I solved the black background problem using the following XML attributes:


<attr name="mapbox_renderTextureMode" format="boolean"/>
<attr name="mapbox_renderTextureTranslucentSurface" format="boolean"/>
<attr name="mapbox_foregroundLoadColor" format="color"/>

This also solved another problem where I had a transition between activities with .makeSceneTransitionAnimation, the map loaded in a fragment in the second activity, and it stayed black afterwards

**Comment by andrewharvey** [comment]
@snowpong Just to add to @tudormarze's answer, specifically:

In your activity_main.xml in your `    <com.mapbox.mapboxsdk.maps.MapView ...` you can add

```xml
        mapbox:mapbox_renderTextureMode="true"
        mapbox:mapbox_renderTextureTranslucentSurface="true"
        mapbox:mapbox_foregroundLoadColor="@color/colorWhite"
```

where colorWhite is a color you've set in values/colors.xml.
