### ISSUE TITLE
Include Mapbox SDK in existing OS X Application

### ISSUE THREAD

**Issue by tkrajacic** [mapbox/mapbox-gl-native#3043]
Is it possible to easily™ include mapbox-gl in an existing OS X application.
I could build the sample app and re-use its Xcode project but that really is unwieldy.
I am using Swift and Storyboards which might pose another problem?

An SDK like the one for iOS would be nice (cocoapods or carthage would be even better) but I understand that this is not the focus right now.

Can I just link the build-products of the osx Xcode project statically and be done with it?
Kind of like with the prebuilt binaries for iOS.

Any hints or pointers?
Any help is greatly appreciated.

**Comment by incanus** [comment]
The big lift here @tkrajacic is that aside from iOS, Android, and Node.js, we don't have bindings atop the C++ code at all. This includes the Mac. So the Mac project (e.g. `make xproj`) compiles the core GL library in C++, then stands it up similar to the Linux desktop version using [GLFW](http://www.glfw.org) to create a "dumb OpenGL window" to draw in, plus takes care of basic debug keybindings. 

So, short version: you should be able to create an OS X app which creates its own e.g. `NSOpenGLView` for GL to draw into, but also takes responsibility for swapping buffers, calls `mbgl::Map::renderSync()`, and otherwise interfaces directly with the C++ API (stuff like the `mbgl::Map` object and `mbgl::LatLng` structures). 

It's not really in the cards right now for anything more advanced for OS X or Linux or bindings for Cocoa manipulation. 

I think that's the closest I can get you, but I'll let @kkaefer add any other details if he has them.

**Comment by tkrajacic** [comment]
Thanks for the great walkthrough.

I just wonder - The iOS Bindings should be 99% reusable for OS X or not?
All the frameworks except  `MobileCoreServices.framework` are on OS X as well.

**Comment by 1ec5** [comment]
> The iOS Bindings should be 99% reusable for OS X or not?

It may be possible, with a bit of trial and error, to get it to work on OS X, but code changes would definitely be required because AppKit differs from UIKit in many ways.

**Comment by tkrajacic** [comment]
So if one would translate `/platform/ios` to AppKit, what else would be missing to just make the iOS bindings spit out an OSX version?
The `/ios` directory contains the podspec and example app?

**Comment by 1ec5** [comment]
The ios/ directory contains the example application, while include/mbgl/ios/, platform/ios/, mbgl/platform/darwin/, and platform/darwin/ contain the actual library code. (The last two use only Foundation, so they should be compatible with OS X already.) The meat of the code is in MGLMapView.m. Note our use of SMCalloutView in platform/ios/vendor/ – on OS X, it’d be better to use NSPopover.

**Comment by 1ec5** [comment]
There’s a lot of code that’s specific to UIKit in MGLMapView, MGLUserAnnotationView, etc. I haven’t tried, but https://github.com/mapbox/mapbox-gl-native/issues/3043#issuecomment-157205405 sounds like a good summary of what would be required for the bare minimum to display a draggable/zoomable map.

**Comment by 1ec5** [comment]
@tkrajacic, please take a look at the [1ec5-osx branch](https://github.com/mapbox/mapbox-gl-native/tree/1ec5-osx) I just pushed. It adds a new MGLMapView class analogous to the MGLMapView for iOS, as well as a pure Cocoa osxapp. It’s exceptionally rough around the edges: in particular, it tends to spin up the fan even when idle, and annotations and the user dot aren’t yet implemented. But if you’re interested in hacking on it, run `make xproj` and build the osxapp target.

To integrate this library into a separate project:

1. Run `make xpackage`.
1. Pull build/osx/pkg/static/{Headers,libMapbox.a} into your project.
1. Add `libz.tbd`, `libsqlite3.tbd`, and `libc++.tbd` to the Linked Frameworks and Libraries section of the project editor.
1. In your main XIB or storyboard, drag in a Custom View and set its custom class to MGLMapView.

Please note that OS X is not officially supported at the same level as iOS (yet?), but I hope this branch in a good enough state that you can run with it. Good luck!

**Comment by tkrajacic** [comment]
Wow, you guys are absolutely awesome! Setting aside even a few minutes to work on something that is clearly not the focus at all is ... well incredible. I'll buy you all a beer should I be in the area ;)

I'll take it for a spin, but I'm swamped with other work at the moment.
Thanks again!

**Comment by tkrajacic** [comment]
Had to include SystemConfiguration.framework as well and create a bridging-header since I am using Swift.
I am getting a lot of duplicate symbols error on linking though like:

    duplicate symbol _uv__udp_send in:
    .../libMapbox.a(udp.o)
    .../libMapbox.a(libuv_la-udp.o)

Seems that `make xpackage` should not include both object files (there is always a `libuv_la` variant for the duplicates) but I'll investigate further.

**Comment by 1ec5** [comment]
I forgot to mention that Bitcode is enabled, in case you're still using Xcode 6.x. Not sure if that's related at all to this error, though.

**Comment by tkrajacic** [comment]
I am using latest Xcode 7.1.1

I thought Bitcode wasn't available for OS X targets. No setting in `Build Settings`

**Comment by 1ec5** [comment]
Ah, you’re right. :smile:

**Comment by 1ec5** [comment]
I’m not getting those warnings after a full `make clean && make distclean && rm -rf gyp/build/`. I did forget to mention that `-ObjC` is required in `OTHER_LD_FLAGS`, however.

**Comment by tkrajacic** [comment]
The cleaning before building did the trick and got rid of the duplicate symbols.
Now the view stays black though and the console displays `loading style failed: HTTP status code 401`.
ATS is disabled.
I tried a local URL, and a style URL from my mapbox account, but neither worked so far.
Where does the MGLMapView look for a style?

**Comment by 1ec5** [comment]
MGLMapView supports style from various locations. If you designed a style in Mapbox Studio, the “style ID” that begins with mapbox:// should work. If you want to load a local style, a relative URL or one beginning with asset:// would be relative to your application’s Resources folder. (Drag the JSON file into your project’s Supporting Files group.)

If you’re using a Mapbox-hosted style, make sure your access token is set, either in the `MGLMapboxAccessToken` key in the Info.plist file or by setting `-[MGLAccountManager setAccessToken:]` before setting the style.

**Comment by tkrajacic** [comment]
Yeah I thought the access token still had to be set via environment variable. Setting it via the manager works now.

**Comment by 1ec5** [comment]
#3135 landed.
