### ISSUE TITLE
clean up iOS versioning in scripts

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#3046]
Too many version determinations! 

- https://github.com/mapbox/mapbox-gl-native/blob/c35f18fdbc94917c20cb675b6510c9feaed40f0c/scripts/ios/package.sh#L124
- https://github.com/mapbox/mapbox-gl-native/blob/c35f18fdbc94917c20cb675b6510c9feaed40f0c/ios/docs/install_docs.sh#L10
- https://github.com/mapbox/mapbox-gl-native/blob/5d56131eb48dfd1adc1135a8d061ee3bed8c5802/scripts/ios/framework.sh#L29

**Comment by incanus** [comment]
This should also expose the option to tack on any `-pre.X` or `-rc.Y` designation, if desired.

**Comment by 1ec5** [comment]
Not critical for 3.0.0.

**Comment by incanus** [comment]
Also useful here is `git tag --sort=-v:refname` to combat the semantic versioning problem, but that still puts something like `ios-v3.0.0-pre.10` ahead of `ios-v3.0.0` final.

**Comment by incanus** [comment]
We may want to grab something like [node-semver](https://github.com/npm/node-semver) as a packaging dependency rather than reinvent the wheel for version comparisons.

**Comment by 1ec5** [comment]
Not critical for 3.1.0.

**Comment by 1ec5** [comment]
We still have a bunch of version-calculating code scattered about, but now it’s all based on `git describe` instead of fragile sorting. I think we’re good here.
