### ISSUE TITLE
Benchmark OkHTTP vs curl

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#3048]
From #2400 

@mb12 would like us to benchmark the difference between the two libraries

/cc @tobrun @zugaldia @bleege

**Comment by zugaldia** [comment]
Just for background purposes, this is what @mb12 suggests:

> Is it possible to measure the performance overhead of OkHttp as well? In this case we will be copying 25K to 100K+ bytes for each tile from java to native using JNI versus the older one where this copy and the additional overhead of managed code(GC, etc.) is missing.
