### ISSUE TITLE
Failed to load "asset://styles/light-v8.json". Did I do something wrong?

### ISSUE THREAD

**Issue by sy-tang** [mapbox/mapbox-gl-native#3051]
I followed the get started guide of iOS SDK. When I tried to custom the map style, I get this error: " {Map}[Setup]: loading style failed: no such file or directory" . Then I tried to use this url : "mapbox://styles/mapbox/light-v8", It worked! Did I do something wrong with the asset url?

**Comment by friedbunny** [comment]
Styles were recently unbundled in #2239. We recommend most developers use the [current stable release](https://www.mapbox.com/ios-sdk/#installation) (v2.1.2, as of today) and not the undocumented, unstable pre-release builds here on Github.

If you are interested in following our pre-release progress, please be sure to read our [changelog](https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md#ios-master).

**Comment by 1ec5** [comment]
@sy-tang, if you _are_ using version 2.1.2 and still getting this error, are you installing the library [using CocoaPods](https://www.mapbox.com/ios-sdk/#cocoapods) or [manually](https://www.mapbox.com/ios-sdk/#binary)? If the latter, make sure Mapbox.bundle is in your project’s Copy Resource Files build phase.
