### ISSUE TITLE
Upgrade to Gradle 2.9

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#3052]
Gradle 2.9 was just released.

Main features over at https://docs.gradle.org/current/release-notes

Of notable interest is:
> Explicit declaration of library API with the experimental Java software model
> Developing with the experimental Java software model is now more powerful, with the ability to explicitly declare which packages and dependencies make up the API of a library.

This should help us solve the internal method problem we have in the annotation library.

/cc @bleege @tobrun @zugaldia

**Comment by tobrun** [comment]
:+1:
Looking forward how this translates to the actual code

**Comment by tobrun** [comment]
Gradle 2.10 has been released, will upgrade to that instead

**Comment by tobrun** [comment]
This landed with 3fa63fa5e8fb59daef86ad267d39c2b45e9b6a22 in the release branch of 3.1.0 #3537

**Comment by bleege** [comment]
@tobrun Looks like there are still a few things left to be done:

1. [ ] The [Gradle wrapper files]() will also need to be regenerated.  This can be done by running `./gradlew wrapper` in the project root.  It'll update the `gradle-wrapper.properties` file, specifically the [`distributionURL`](https://github.com/mapbox/mapbox-gl-native/blob/957415823a003111f6efecd1a1552a30f999235a/platform/android/gradle/wrapper/gradle-wrapper.properties#L6).  Use the `-bin` version even if Android Studio suggests the `-all`.  Without this update the wrapper still runs 2.8.
1. [ ] Comms about why the decision not to implement the 2.9 features mentioned in the original comment were not implemented.
1. [ ] Comms about anything in the new features in 2.9 or 2.10 that will make our project better (speed, etc?).  This can either be "there were no automatic ones" or "feature x looks interesting and we should use that".

**Comment by tobrun** [comment]
##### List of notable features of gradle 2.10:

>Performance improvements for native compilation
TestKit dependency is decoupled from Gradle core classes and dependencies
New task for visualising a buildScript dependencies
HTML report for Checkstyle
Tooling API exposes Java source language level for Eclipse projects
Dependency management for the Java Software Model
DSL improvements for the Software Model
Better support for developing plugins with the Software Model

##### Why notable interest from above was not implemented from 2.8 release:

The [feature](https://docs.gradle.org/2.9/release-notes#explicit-declaration-of-library-api-with-the-experimental-java-software-model) mentioned above, went stable in 2.9 but I'm not finding a proper use case for it in the GL-Native project. This setup is ideal for creating layered architectures with small scopes. This is something useful for enterprise applications, no so much for this Android project.

**Comment by bleege** [comment]
Perfect!  Thanks for the insight as to why this was simply a bump to `2.10` and not anything more.  :+1:

**Comment by bleege** [comment]
Merged on to `release-android-3.1.0` via #3578
