### ISSUE TITLE
mbtiles

### ISSUE THREAD

**Issue by iDevelopper** [mapbox/mapbox-gl-native#3053]
MapBox iOS is deprecated and unmaintained. Will you develop in MapBox GL the possibility to display  offline maps according the mbtiles specification?

**Comment by friedbunny** [comment]
We're committed to adding robust offline support — see https://github.com/mapbox/mapbox-gl-native/issues/584#issuecomment-155845085. Some variation of MBTiles is very likely to be supported, but it's too early in the process to say when or what that will look like.

**Comment by iDevelopper** [comment]
Why not support mbtiles specifications? It is use by a lot off applications...

**Comment by friedbunny** [comment]
We like (and invented) [MBTiles](https://github.com/mapbox/mbtiles-spec), but adapting them for vector data has not happened yet and it's undetermined exactly how our offline format should/will work. See #2939 for recent progress.
