### ISSUE TITLE
Show keybindings in OSX/Linux applications

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#3054]
Instead of only showing our keybindings in Markdown documentation, we should make them obvious within the UI of the test applications themselves.

**Comment by 1ec5** [comment]
The OS X and Linux applications are currently using GLFW, which doesn’t offer much in the way of UI customization.

**Comment by tkrajacic** [comment]
I'll happily pitch in when it comes to UIKit to AppKit stuff as far as I can. Did some OpenGL and C++ but that's a few years back, so the hardest part for me is below the UIKit/AppKit Layer.
Now mostly Swift ;)
Not sure how much help I can be.

**Comment by incanus** [comment]
Some back discussion in https://github.com/mapbox/mapbox-gl-native/commit/3293f32fefe5d970e2e0a2e6389cbe39475e4c32. 

We should not be splitting out from GLFW at this time as 1) it works great for our OS X & Linux needs 2) we've put a good amount of time into making it do so 3) it's cross-platform, reducing non-critical code and 4) we aren't focusing on desktop bindings or maintenance right now (cf #3043). 

Proposed fix in https://github.com/mapbox/mapbox-gl-native/pull/3058.

**Comment by tmpsantos** [comment]
I once suggested we could just add a sprite to the map with an image with the key bindings mappings. :smile:
