### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#306]
Add a benchmark mode that allows us to benchmark various aspects of the renderer:
- [ ] tile parse time
- [ ] stylesheet parse
- [ ] stylesheet cascade time
- [ ] render time

This requires building uncoupling of these components, and making sure that neither of these actions waits for any I/O, e.g. by implementing a custom mock HTTP object that reads the responses from memory (make sure to preload it from disk).

**Comment by jfirebaugh** [comment]
From https://github.com/mapbox/mapbox-gl-native/pull/9257#pullrequestreview-43829095:

> It seems like having a benchmark that includes this significant cost [of uploading `FrameHistory`] would be good. Should the benchmark be changed to include zooming?
