### ISSUE TITLE
Pod

### ISSUE THREAD

**Issue by kopacabana** [mapbox/mapbox-gl-native#3067]
Please update pod spec to version 2.2
I need 
- (void)mapView:(MGLMapView *)mapView tapOnCalloutForAnnotation:(id <MGLAnnotation>)annotation

or
- (void)mapView:(MGLMapView *)mapView tapOnLabelForAnnotation:(id <MGLAnnotation>)annotation

Thanks

**Comment by incanus** [comment]
We are close to 3.0.0 release for iOS; in the meantime you can use this in your `Podfile` to run the pre-releases: 

```ruby
pod 'Mapbox', :podspec => 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/release-ios-v3.0.0/ios/Mapbox-iOS-SDK.podspec'
```

**Comment by kopacabana** [comment]
Thanks !

There's an error in code below. Right code is :
pod 'Mapbox-iOS-SDK', :podspec => 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/release-ios-v3.0.0/ios/Mapbox-iOS-SDK.podspec'

**Comment by friedbunny** [comment]
> It's work but markers are under road map layer and stroke layer !

Yup, the joy/danger of using pre-release builds. :grin: That issue is over in #3037.
