### ISSUE TITLE
Performance regression from pre-3 to pre-8

### ISSUE THREAD

**Issue by parrots** [mapbox/mapbox-gl-native#3069]
Pre-3 fixed the flickering issue for adding/removing annotations on iOS, and the performance was stellar. A matter of milliseconds to make annotation changes and see them in the UI.

Using pre-8 (may have happened earlier, haven't updated since pre-3) annotation changes now take ~1 second to reflect in the UI. There is no flickering or main-thread hanging, that's still all good, but the redraw now takes over a second to complete async.

**Comment by parrots** [comment]
From @incanus via email conversations: I bet it’s related to https://github.com/mapbox/mapbox-gl-native/commit/656cb4c9a4cee0010e52daa70127306fe564b318

**Comment by 1ec5** [comment]
A rebase will say for sure, but #2951 is also a possibility.

**Comment by incanus** [comment]
I'm definitely seeing this in @parrots's app using `3.0.0-pre.8`. Working on profiling now.

**Comment by incanus** [comment]
And definitely still not seeing the problem with `3.0.0-pre.3` on the same codebase.

**Comment by incanus** [comment]
Simply moving https://github.com/mapbox/mapbox-gl-native/commit/656cb4c9a4cee0010e52daa70127306fe564b318 back to `enableSetNeedsDisplay = YES` and having `invalidate` call `setNeedsDisplay` again is enough to make this go away, so it does seem to be related to https://github.com/mapbox/mapbox-gl-native/commit/656cb4c9a4cee0010e52daa70127306fe564b318 / `CADisplayLink`. 

Trying to figure out what update case we're missing there and how to fix it. 

/cc @adam-mapbox

**Comment by incanus** [comment]
Ah! The `CADisplayLink` is only added to `NSDefaultRunLoopMode`, but scrolling animations and such by Apple block that run loop so that normal activities suspend and scrolls are performant.

**Comment by incanus** [comment]
We need `UITrackingRunLoopMode` as well. 

http://stackoverflow.com/questions/7551411/uiscrollview-blocks-run-loop

**Comment by incanus** [comment]
NAILED IT

:point_right: https://github.com/mapbox/mapbox-gl-native/pull/3072

**Comment by incanus** [comment]
Merged #3072 into release branch & cherry-picked to master.
