### ISSUE TITLE
Make docs navigation more obvious

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-native#3071]
As per discussion with @bleege, let's tighten up API docs for the next release to make it more obvious how to navigate the docs themselves. For example, it's hard to know where to go from `MapView.OnMapChangedListener` to read more about `int change`: 

![image](https://cloud.githubusercontent.com/assets/2365503/11260152/55b93538-8e1d-11e5-8388-e7071017d69d.png)

There are comments from the [source code](https://github.com/mapbox/mapbox-gl-native/blob/a6e639b79401c57f403dd6a2ec73396727375e19/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L252-L358) on the [MapView page](https://www.mapbox.com/android-sdk/api/2.2.0/com/mapbox/mapboxsdk/views/MapView.html), but no obvious way to get there.

**Comment by tobrun** [comment]
![screen shot 2015-11-19 at 21 53 18](https://cloud.githubusercontent.com/assets/2151639/11284043/f86c3ace-8f07-11e5-9418-3a86d89d7d8b.png)

**Comment by tobrun** [comment]
Aha, now noticing that this was only one example, 
will check the whole API when traveling by train in next upcoming days.

**Comment by bleege** [comment]
Looking good @tobrun!

**Comment by tobrun** [comment]
^ will be adding more commits as above in the upcoming days. Will wait with rebasing until validated.

**Comment by bleege** [comment]
@tobrun Let's not make perfect the enemy of the good.  We can start with getting the `OnMapChangeListener` code in now (avoid painful rebases later) and add to this effort with a new branch and PR for other Enums in the code that need similar treatment.  Sound good?

**Comment by tobrun** [comment]
This is already on master, closing

**Comment by bleege** [comment]
@tobrun Can you confirm that all the enums used in the project know have been documented like this?  IIRC we were keeping this open as only `OnMapChangeListener` had been done.

**Comment by tobrun** [comment]
@bleege 
Yes I can, here is the list of all classes in the constant package:
 - [GeoConstants](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/GeoConstants.java)

 - [MapboxConstants](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java)

- [MathConstants](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MathConstants.java)

- [MyBearingTracking](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MyBearingTracking.java)

- [MyLocationTracking](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MyLocationTracking.java)

- [Style](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/Style.java)

Other constants in MapView can be found under [this line](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L286).

**Comment by bleege** [comment]
@tobrun Awesome man!  Thanks for the details on this.  I didn't see a PR or commit SHA so was wondering where things stood on this.  :+1:
