### ISSUE TITLE
Support kml, kmz layer

### ISSUE THREAD

**Issue by hoanvuso** [mapbox/mapbox-gl-native#3076]
Currently the plugin does not support kmz/kml layer, can we add this feature?

https://www.mapbox.com/mapbox.js/example/v1.0.0/omnivore-kml/

**Comment by friedbunny** [comment]
We plan to support GeoJSON sources (#2161) but I doubt there will ever be direct support for KML.

It's possible to [parse out GeoJSON files](https://www.mapbox.com/ios-sdk/examples/line-geojson/) on-the-fly right now and a similar approach would work just fine for KML.

**Comment by friedbunny** [comment]
Or, the ideal approach would be to import your KML data using [the new Mapbox Studio](https://www.mapbox.com/studio), which would create and host vector tiles that you could then use efficiently/worry-free in a GL style.

**Comment by percula** [comment]
For anyone else wondering how to do this, I am using the [OSMBonusPack library ](https://github.com/MKergall/osmbonuspack/wiki/Tutorial_4)to import KML and export to GeoJson. It works really well. Just like Mapbox's toGeoJson repo, you will need to manually add styling but the OSMBonusPack does a wonderful job parsing all the styling attributes for you so it's rather painless.
