### ISSUE TITLE
Harden glyph loading

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#308]
- [ ] Make sure that we still draw a map, e.g. without labels, or with only some labels, if glyph PBFs fails to load. This likely requires implementing incremental parsing and updatable buckets (#163)
- [ ] Cache glyph images indefinitely
- [x] Retry glyph loading when a request fails (e.g. due to shaky connection)

**Comment by jfirebaugh** [comment]
I don't think there's anything actionable here.
