### ISSUE TITLE
Consider miniutf over boost::locale

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-gl-native#309]
[miniutf](https://github.com/dropbox/miniutf) looks like it got its start for the same reason we fell back to using `boost::locale` on linux (#270): because libstdc++ is still missing full `codecvt_utf8 / codecvt_utf16` support.

TODO: 

  - [ ]  - benchmark to make sure miniutf is as fast as boost::locale/icu/std:: - https://github.com/mapnik/mapnik/commit/0859a74f81fc1f3fa5c3ebbbd3388df721d55e4f

**Comment by kkaefer** [comment]
This is merged and we're using nunicode.
