### ISSUE TITLE
Annotations not showed on the Map

### ISSUE THREAD

**Issue by YBthebest** [mapbox/mapbox-gl-native#3091]
Hi,

I am initialising the map like this:
```
    #import "Mapbox.h"

    @interface ShowEtablissementViewController () <UIActionSheetDelegate,       MFMailComposeViewControllerDelegate, MGLMapViewDelegate>

    @property (nonatomic) MGLMapView *mapView;

    @end

    @implementation ShowEtablissementViewController

    - (void)viewDidLoad {
        [super viewDidLoad];
        self.mapView = [[MGLMapView alloc] initWithFrame:self.mapBoxView.bounds];
        self.mapView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
        self.mapView.delegate = self;
        [self.view addSubview:mapView];
    }
```
If I add an annotation directly here in viewDidLoad, like this:
```
    MGLPointAnnotation *hello = [[MGLPointAnnotation alloc] init];
    hello.coordinate = CLLocationCoordinate2DMake(40.7326808, -73.9843407);
    hello.title = @"Hello world!";
    hello.subtitle = @"Welcome to my marker";
    [self.mapView addAnnotation:hello];
```
It doesn't appear on the map.

If I use the CLLocationManager, it doesn't appear either.

But if I do: 
```
NSLog(@"%@", self.mapView.annotations);
```
There is an annotation. It does exist: it just isn't displayed.
```
(
    "<MGLPointAnnotation: 0x141c6ce00>"
)
```
What am I missing here? Is this a real bug or an implementation error from my part?

**Comment by 1ec5** [comment]
This bug was most likely fixed in #2322, which will make it into the next release of the Mapbox iOS SDK. In the meantime, please refer to this workaround: https://github.com/mapbox/mapbox-gl-native/issues/2693#issuecomment-150090842.

**Comment by YBthebest** [comment]
Hi,

I added the new release but the issue is still there. Am I missing something?

Thanks a lot

**Comment by 1ec5** [comment]
Thanks for the report. This sounds like the regression we're tracking in #2956. In the meantime, the workaround above should work.

**Comment by YBthebest** [comment]
Yep it does work. The only thing that still doesn't work is the showAnnotations method, that seems to randomly zoom in somewhere, way too close to earth, not taking into account the annotations at all...

**Comment by 1ec5** [comment]
Please open a separate bug about showAnnotations (with details on how to reproduce the issue). Thanks!
