### ISSUE TITLE
Style load failed event handling

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3094]
When loading a invalid style through `setStyleUrl` on Android, I'm seeing a log message indicating the style load failed but I'm not able to hook into that event to show an error message.

Is iOS SDK exposing this functionality?

cc @friedbunny @1ec5

**Comment by friedbunny** [comment]
#2762 covers this — core mbgl doesn't yet emit a `MapChangeDidFailLoadingMap` event (and style loading failure is one time that we should).

**Comment by tobrun** [comment]
@friedbunny 
Thank you for linking that, I was able to find the android equivalent:
```java
   /**
     * Currently not implemented.
     * <p/>
     * This event is triggered when the map has failed to load a new map style.
     */
    public static final int DID_FAIL_LOADING_MAP = 7;
```

Will close this issue down, 
I remember a ticket already being opened related to adding the not implemented ones.
