### ISSUE TITLE
Reloading a failed MGLMapView

### ISSUE THREAD

**Issue by tomtaylor** [mapbox/mapbox-gl-native#3102]
If a `MGLMapView` fails to load (due to not being able to fetch the styles, usually for network reasons), is there a recommended way of trying again, other than unsetting and setting the `styleURL`?

**Comment by 1ec5** [comment]
If MGLMapView fails to load the style due to network issues, it uses Reachability to try again when the network connection comes back. Is that not working for you?

**Comment by tomtaylor** [comment]
I've seen situations where I end up with a blank, black map, and no way of explicitly retrying. Temporary DNS outages, etc. It might be handy to have an explicit method to retry for situations Reachability can't cover?

**Comment by 1ec5** [comment]
A general-purpose reload method could be helpful, especially in light of the offline features that @incanus is working on for #584.

**Comment by tomtaylor** [comment]
Mostly for my own memory: to reproduce this, start a `MGLMapView` on a device in airplane mode, wait for it to log that the internet connection appears to be offline, and then disable airplane mode. The map doesn't attempt to load the style.

@1ec5 is this expected? I'd have thought Reachability would cover this.

**Comment by 1ec5** [comment]
This simple API exists [in the Mapbox OS X SDK](https://github.com/mapbox/mapbox-gl-native/blob/656eb8766c147f4429115b8431511d6213859684/include/mbgl/osx/MGLMapView.h#L117) and needs to be ported over to the iOS version.

**Comment by 1ec5** [comment]
Until this is fixed, the workaround is to set the style URL to a bogus local relative URL, such as `[NSURL URLWithString:@"issue-1302"]`, then set it back to the original style URL.
