### ISSUE TITLE
[Android] Double-tap zoom should not be called when quickzooming

### ISSUE THREAD

**Issue by brewin** [mapbox/mapbox-gl-native#3104]
When trying to quickzoom out (double-tap and drag up), the double-tap gesture is detected and the map immediately zooms in. This makes it nearly impossibly to quickzoom out.

**Comment by tobrun** [comment]
@brewin: I believe you are referring this iOS feature https://github.com/mapbox/mapbox-gl-native/pull/2153?
Currently this is not yet supported on Android.

**Comment by brewin** [comment]
Yes, that's the same feature. It actually does mostly work on Android, except for this small bug. I'm currently working on a fix for it.

**Comment by tobrun** [comment]
:+1:
