### ISSUE TITLE
[ios] Using different images for each annotation results crash

### ISSUE THREAD

**Issue by Sh1mor1nka** [mapbox/mapbox-gl-native#3109]
here how i'm trying to use different images, also it can be the same images for annotations but at most they are different
```Objective-C
- (MGLAnnotationImage *)mapView:(MGLMapView *)mapView imageForAnnotation:(id <MGLAnnotation>)annotation {
    YPointAnnotation *pin = annotation; // Subclass of MGLAnnotation with only one NSInteger property - identifier
    Landmarks *landmark = [[self.fetchedResultController.fetchedObjects filteredArrayUsingPredicate:[NSPredicate predicateWithFormat:@"theId == %d", pin.identifier]] firstObject];
    NSString *url = [YControl getIconFromObject:landmark.icon]; // aka Key for image
    MGLAnnotationImage *annotationImage = [mapView dequeueReusableAnnotationImageWithIdentifier:url];
    
    if (!annotationImage) {
        UIImage *image = [[SDImageCache sharedImageCache] imageFromDiskCacheForKey:url];
        if (image == nil) {
            // if i don't have cached image i use my default image
            annotationImage = [mapView dequeueReusableAnnotationImageWithIdentifier:@"pin_g"];
            if (!annotationImage) {
                annotationImage = [MGLAnnotationImage annotationImageWithImage:[UIImage imageNamed:@"ping_g"] reuseIdentifier:@"pin_g"];
            }
            return annotationImage;
        }
        annotationImage = [MGLAnnotationImage annotationImageWithImage:image reuseIdentifier:url];
    }
    
    return annotationImage;
}
```

here is error i got:

"Nov 24 16:57:40 CyberMac.berloga.lan Project[16143] <Error>: CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
libc++abi.dylib: terminating with uncaught exception of type mbgl::util::SpriteImageException: Sprite image dimensions may not be zero"

What can it be? Thank you.

**Comment by 1ec5** [comment]
What does `image` report its width and height as?

**Comment by 1ec5** [comment]
Same with the other call to `+[UIImage imageNamed:reuseIdentifier:]` – can you verify that these images have nonzero area?

**Comment by Sh1mor1nka** [comment]
Image with zero size, that's it, thank you!
