### ISSUE TITLE
[iOS] showAnnotations not working with two points

### ISSUE THREAD

**Issue by YBthebest** [mapbox/mapbox-gl-native#3110]
When I add multiple annotations using dispatch_asynch, all the annotations are correctly added to the Map, and the basic zoom level shows the whole world map.

![simulator screen shot 24 nov 2015 17 03 38](https://cloud.githubusercontent.com/assets/1565896/11372393/8388f2c8-92cd-11e5-94f1-f838c33e3058.png)

Yet when I try to use:
```[mapBox showAnnotations:mapBox.annotations animated:YES];```

It zooms in on a street that IS in the same CITY as all the annotations, but it still clearly does not accomplish what it should.
![simulator screen shot 24 nov 2015 17 04 20](https://cloud.githubusercontent.com/assets/1565896/11372404/976b8d64-92cd-11e5-92db-c2d6c2076c3b.png)

**Comment by 1ec5** [comment]
In #3111, I modified iosapp to similarly add annotations using `dispatch_async()` then show annotations on the main thread. Are there any differences in how you’re adding and showing the annotations?

**Comment by 1ec5** [comment]
Correction: in that PR, iosapp is still adding the annotations on the main thread. But if you move that line into the surrounding block, it still zooms in to the right area.

**Comment by incanus** [comment]
Yeah, I would ensure that you are calling UI code on the main thread/queue, as well as possibly post your setup code here @YBthebest if you are still seeing problems.

**Comment by YBthebest** [comment]
```
    [mapBox removeAnnotations:[mapBox annotations]];
    dispatch_group_t group = dispatch_group_create();
    for(int i = 0;i<[tableNoms count];i++){
        dispatch_group_enter(group);
        MGLPointAnnotation *point = [[MGLPointAnnotation alloc] init];
        point.coordinate = coordinate;
        point.title = tableNoms[i];
        [mapBox addAnnotation:point];
        dispatch_group_leave(group);
    }
    while (dispatch_group_wait(group, DISPATCH_TIME_NOW)) {
        [[NSRunLoop currentRunLoop] runMode:NSDefaultRunLoopMode
                                 beforeDate:[NSDate dateWithTimeIntervalSinceNow:1.f]];
    }
    [mapBox showAnnotations:mapBox.annotations animated:YES];
    [self.myTableView reloadData];
```

This is my code. I have deleted some of the code that isn't important here.
What is your idea? Where should I put the showAnnotations line to be sure that it is called correctly after all the annotations are added?

Thanks

**Comment by YBthebest** [comment]
Hi,

I am still having this issue with multiple annotations.
When I use one single annotation, it actually works perfectly.

But whenever I use TWO annotations, I get zoomed in just like I showed in the picture above.

```
    [self.mapView addAnnotation:point];
    [self.mapView showAnnotations:[self.mapView annotations] animated:YES];
```

This works fine. If I add a second annotation, it does the weird zoom in thing.

Are you able to reproduce this?

**Comment by friedbunny** [comment]
> Are you able to reproduce this?

No, I'm not able to reproduce — `-[MGLMapView showAnnotations:animated:` works as expected, with any number of annotations.

Here's my test case, adapted from your code: 

```objc
#import "ViewController.h"
#import <Mapbox/Mapbox.h>

@interface ViewController () <MGLMapViewDelegate>

@property MGLMapView *mapView;

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];

    self.mapView = [[MGLMapView alloc] initWithFrame:self.view.bounds];
    self.mapView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    [self.view addSubview:self.mapView];
    
    UIButton *button = [UIButton buttonWithType:UIButtonTypeSystem];
    button.backgroundColor = [UIColor whiteColor];
    [button addTarget:self action:@selector(addAnnotations) forControlEvents:UIControlEventTouchUpInside];
    [button setTitle:@"Add Annotations" forState:UIControlStateNormal];
    button.frame = CGRectMake(20.0, 20.0, 160.0, 40.0);
    [self.view addSubview:button];
    
    [self addAnnotations];
}

- (void)addAnnotations {
    [self.mapView removeAnnotations:[self.mapView annotations]];
    
    CLLocationCoordinate2D coordinates[] = {
        CLLocationCoordinate2DMake(45.522585, -122.685699),
        CLLocationCoordinate2DMake(45.534611, -122.708873),
        CLLocationCoordinate2DMake(45.530883, -122.678833),
        CLLocationCoordinate2DMake(45.547115, -122.667503),
        CLLocationCoordinate2DMake(45.530643, -122.660121),
        CLLocationCoordinate2DMake(45.533529, -122.636260),
        CLLocationCoordinate2DMake(45.521743, -122.659091),
        CLLocationCoordinate2DMake(45.510677, -122.648792),
        CLLocationCoordinate2DMake(45.515008, -122.664070),
        CLLocationCoordinate2DMake(45.502496, -122.669048),
        CLLocationCoordinate2DMake(45.515369, -122.678489),
        CLLocationCoordinate2DMake(45.506346, -122.702007),
        CLLocationCoordinate2DMake(45.522585, -122.685699),
    };
    
    int r = arc4random() % (sizeof(coordinates) / sizeof(CLLocationCoordinate2D));
    NSLog(@"SHOWING %i ANNOTATION%@", r, r == 1 ? @"":@"S");
    
    dispatch_group_t group = dispatch_group_create();
    for (int i = 0; i < r; i++) {
        dispatch_group_enter(group);
        
        MGLPointAnnotation *point = [[MGLPointAnnotation alloc] init];
        point.coordinate = coordinates[i];
        
        NSLog(@"%i: %.5f, %.5f", i, point.coordinate.latitude, point.coordinate.longitude);
        
        [self.mapView addAnnotation:point];
        
        dispatch_group_leave(group);
    }
    
    while (dispatch_group_wait(group, DISPATCH_TIME_NOW)) {
        [[NSRunLoop currentRunLoop] runMode:NSDefaultRunLoopMode
                                 beforeDate:[NSDate dateWithTimeIntervalSinceNow:1.f]];
    }
    
    [self.mapView showAnnotations:self.mapView.annotations animated:YES];
}

@end
```

**Comment by YBthebest** [comment]
I really don't get it. I am using the very last release and copying your exact code and I have the same issue...completely zoomed in onto nothing. I literally copied your code. What could go wrong?

**Comment by 1ec5** [comment]
The MGLMapView depicted in the screenshot above appears to be less than 200 points tall, which means the diagnosis in #3392 applies here too. Let’s track the issue there for clarity.

**Comment by klauswaiss** [comment]
I just had the same problem.

Solution: Use mapViewDidFinishLoadingMap (MGLMapViewDelegate) to showAnnotations(). You can add annotations in viewDidLoad (UIViewController), but you can't showAnnotations() in viewDidLoad.
