### ISSUE TITLE
Interface Builder doesn't recognize classes without -ObjC linker flag

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#3113]
Discovered by @friedbunny and applies to any manual binary install method. You can't use `MGLMapView` from IB without referencing it elsewhere in code. 

Should be able to fix this with a combo of `+load` and calling `MGLMapView` from our category loader from #2967. 

/cc @friedbunny @1ec5

**Comment by 1ec5** [comment]
This issue was introduced in #2967. The call to `+[MGLCategoryLoader loadCategories]` should move from `+[MGLAccountManager sharedManager]` to `+[MGLAccountManager load]`, so that it runs before the storyboard loads, even if the access token isn’t set in the Info.plist.
