### ISSUE TITLE
Allowing multiple InfoWindows to be visible at a time

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#3115]
At the moment, only one InfoWindow can be visible at a time. We want to be able to show multiple at once.

**Comment by incanus** [comment]
To analog (verb?) the iOS side, the `selectAnnotations:` API there allows for multiple annotations to be passed to selection but, like Apple Maps, to only set `selected` state on the first one (see [here](https://www.mapbox.com/ios-sdk/api/3.0.0/Classes/MGLMapView.html#//api/name/selectedAnnotations)). 

I think it's best on iOS to probably stick to that, but since on Android we have some needs for multiple popups, we can maybe use that API as a model, albeit with slightly different behavior.

**Comment by zugaldia** [comment]
In that case, and to mimic `selectedAnnotations` we could just move from a `private Marker mSelectedMarker;` to a `private List<Marker> mSelectedMarkers  = new ArrayList<>();` and change the internal `MapView` logic accordingly. API-wise, `public Marker getSelectedMarker()` will become `public List<Marker> getSelectedMarkers()`.

I'll try that approach in https://github.com/mapbox/mapbox-gl-native/tree/3115-multiple-infowindows

**Comment by zugaldia** [comment]
Good progress on both keeping the InfoWindow open and also [allowing an InfoWindow to be open while panning](https://github.com/mapbox/mapbox-gl-native/issues/3121).

* It works for default InfoWindows: https://www.dropbox.com/s/yj6kzmmjvichkp4/movie1.mp4?dl=0
* As well as for custom InfoWindows: https://www.dropbox.com/s/kthg70njitwqm2l/movie2.mp4?dl=0

Before having a PR ready we need to do some small refactoring. [As discussed](https://github.com/mapbox/mapbox-gl-native/issues/3116), we don't see a performance hit  for such a small number of InfoWindows.

**Comment by bleege** [comment]
@zugaldia @tobrun FWIW, let's leave the "default" mode to be just 1 `InfoWindow` open at a time per MapView as this is likely to be the majority of desired use cases for developers.  This means that we'll want to have a flag of some sort on the `MapView` to enable multiple visible `InfoWindow` support.  Something like `setAllowConcurrentMultipleOpenInfoWindows(boolean allow)`.  Thoughts?

**Comment by tobrun** [comment]
@bleege seems logical, I consider having multiple open to be a special kind of requirement.
@zugaldia can you take this up? currently not on the project.

**Comment by zugaldia** [comment]
@bleege @tobrun I like it and it changes the API in a consistent way. I'll give it a pass today.

**Comment by zugaldia** [comment]
Flag implemented in https://github.com/mapbox/mapbox-gl-native/commit/e9d749b775e2284b6866d362d4588a847a178e98.

You can test it on TestApp's `InfoWindowActivity` and `InfoWindowAdapterActivity` commenting out the following line in `onCreate`:

```
mMapView.setAllowConcurrentMultipleOpenInfoWindows(true);
```

**Comment by tobrun** [comment]
@zugaldia :rocket:

**Comment by incanus** [comment]
We'll need some thinking about the UI interactions here. For example, I'm guessing that when one or more info windows are up and you tap on a non-interactive part of the map, all are dismissed? We should probably keep it that way for simplicity.

**Comment by zugaldia** [comment]
@incanus that's right, tapping on a non-interactive part of the map dismisses them all. It feels pretty natural right now, but we can definitely learn with usage.

**Comment by zugaldia** [comment]
I'm reopening this issue. Although the basic functionality is there and performing well for a low number of InfoWindows, there're still a few related things that need to be addressed:

* [Layering issues](https://github.com/mapbox/mapbox-gl-native/pull/3152#issuecomment-160765293) when doing position syncing as shown by @incanus.
* `onSingleTapConfirmed()` logic needs to be updated: #3156
* Follow the work that it's being done on iOS for a larger number of callouts (see summary on https://github.com/mapbox/mapbox-gl-native/issues/3116) as it eventually needs to be replicated on Android.

**Comment by zugaldia** [comment]
@Piusin thanks for the feedback. Could you open a [new ticket](https://github.com/mapbox/mapbox-gl-native/issues/new) explaining the issue that you're encountering? Thanks.
