### ISSUE TITLE
Rename access_token resource

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3119]
Been thinking a bit about this and it might be a good idea to rename `access_token` resource:

```xml
<resources>
    <string name="access_token">null</string>
</resources>
```

to

```xml
<resources>
    <string name="mapbox_access_token">null</string>
</resources>
```

Their is always the possibility that the end user or another library, that the end user is using, is overriding the resource by using resource merging. By prepending mapbox to the key we are making a more unique identifier.

**Comment by mb12** [comment]
Or we can just add namespace map box to all sdk strings.
<resources>
    <mapbox name="access_token">null</mapbox>
</resources>

**Comment by tobrun** [comment]
namespace strings are now a supported feature in build.gradle

<img width="1055" alt="screen shot 2015-12-01 at 20 42 42" src="https://cloud.githubusercontent.com/assets/2151639/11511993/5af159aa-986c-11e5-9a07-04f51d535e25.png">

**Comment by tobrun** [comment]
![screen shot 2016-02-17 at 09 09 08](https://cloud.githubusercontent.com/assets/2151639/13103348/24ae996c-d556-11e5-8a25-6772eb58f26a.png)

**Comment by bleege** [comment]
This is causing an error when at build time, meaning that it's not possible to build from `master` right now.

```java
/Users/brad/development/mapbox-gl-android/platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/fragment_double_map.xml:11:30-57 : AAPT: No resource found that matches the given name (at 'access_token' with value '@string/mapbox_access_token').

/Users/brad/development/mapbox-gl-android/platform/android/MapboxGLAndroidSDKTestApp/src/main/res/layout/fragment_double_map.xml:25:34-61 : AAPT: No resource found that matches the given name (at 'access_token' with value '@string/mapbox_access_token').

:MapboxGLAndroidSDKTestApp:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':MapboxGLAndroidSDKTestApp:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/local/android/build-tools/23.0.2/aapt'' finished with non-zero exit value 1
```

**Comment by bleege** [comment]
The error turned out to be that when running it locally the key in `developer-config.xml` needed to be renamed from `access_token` to `mapbox_access_token`.  I've updated the install docs to better communicate this.

**Comment by tobrun** [comment]
@bleege, I didn't came to mind that others had to remove/regenerate the file (because it's gitignored..). Apologies!
