### ISSUE TITLE
Increase viewport max zoom to render indoor osm data

### ISSUE THREAD

**Issue by franckt** [mapbox/mapbox-gl-native#3120]
Hi, 
I want to render indoor osm data, so zoom 18 is not enough
I put max_scale to zoom 22 instead of zoom 18 for the maximum viewport zoom in
https://github.com/mapbox/mapbox-gl-native/blob/adfac6f0615b7f79da2c80d0580428a92e9f0089/src/mbgl/map/transform_state.hpp#L81
On IOS, It introduce some lag or freeze when panning or zooming the map for a few second when over zoom 18, after it works well, and after the lag / freeze comes again.
Not tested on Android.

Any idea on that issue ?

**Comment by 1ec5** [comment]
There’s some additional discussion in #509. The lagging hasn’t been reported before.

**Comment by jfirebaugh** [comment]
Let's track in #509. We can investigate the lag when we test the fix there.
