### ISSUE TITLE
Allow InfoWindow to be open while panning

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3121]
We’re hearing of the need to improve our InfoWindow setup.

We identified two improvements:
 - Showing multiple InfoWindows at the same time (handled in #3115)
 - Having the InfoWindow remain opened while panning (handled in this issue)

I'm working on the same branch as #3115 to be able to identify performance problems early on.
 
cc @zugaldia @incanus @bleege

**Comment by tobrun** [comment]
I was able to sync `SurfaceView` changes to the overlain default `InfoWindow` while still being performant. Now I need to investigate if it is still performant to sync a repositioned InfoWindow as landed in #2273. 

The code required to reposition in #2273 is more complex as used in current progress, because this is a hot code path we need to watch out for performance loss.

Current progress can be viewed [here](https://youtu.be/F67yfQ8GOrA).

**Comment by tobrun** [comment]
I was able to also sync the repositioned InfoWindow from #2273 

Progress can be viewed [here](https://youtu.be/NTZZDQfKbfA)

Just need to clean up the code and will PR.

**Comment by tobrun** [comment]
@zugaldia I already pushed the code to your branch. So we can have :eyes: on progress and you can continue your work. Will clean up / optimise later today

**Comment by tobrun** [comment]
@zugaldia I already pushed the code to your branch. So we can have :eyes: on progress and you can continue your work. Will clean up / optimise later today

**Comment by zugaldia** [comment]
@tobrun Great job, let's clean up the code and make sure we aren't creating any unexpected leaks and then we're ready for a PR.
