### ISSUE TITLE
[Android] Perspective view

### ISSUE THREAD

**Issue by franckt** [mapbox/mapbox-gl-native#3122]
Hi, 
Is perpective view available on Android ?

**Comment by tobrun** [comment]
@franckt 
do you mean the [Tilt](https://www.mapbox.com/blog/ios-sdk-2.1.0/) feature that iOS is currently exposing? 
For Android we have this ticket https://github.com/mapbox/mapbox-gl-native/issues/2805

**Comment by franckt** [comment]
Yes exactly, is it working ?

**Comment by tobrun** [comment]
It hasn't been implemented yet, it is on our priority list, closing this down in favor of #2805
