### ISSUE TITLE
Implement standalone geometry drawing tests

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#3126]
We should have standalone tests for geometry drawing: Tests that create individual buckets, load custom data that is not from a vector tile, then draw those buckets to a blank canvas. This

* enforces good separation between individual components of the renderer
* allows easier testing of edge cases of polygon rendering
* allows implementing a visual debug mode for adding new features

**Comment by jfirebaugh** [comment]
Do you see the "standalone" part of this as essential? The way I would probably go about this is to implement GeoJSON sources in native and then add geometry tests to mapbox-gl-test-suite using GeoJSON sources with inline data. That way both native and js could benefit.

**Comment by kkaefer** [comment]
Not sure whether it's essential; I find it easier to work on shaders and geometry debugging if I cut out the map part in between and have a 1:1 relation between the vertices I use and the ones displayed on the screen.

**Comment by jfirebaugh** [comment]
Let's stick with mapbox-gl-test-suite for now.
