### ISSUE TITLE
Memory leak with V3.0.0 iOS SDK

### ISSUE THREAD

**Issue by Dwar3xwar** [mapbox/mapbox-gl-native#3130]
I've noticed a memory leak while using ```MGLMapView``` within a navigation controller.

To Recreate:
1) Create 2 view controllers in a navigation controller, with VC A segueing to VC B, containing a ```MGLMapView```.
2) Go back to the original view controller, VC B is deinitialized but memory is not freed at all.

Instruments:

![screen shot 2015-11-25 at 3 09 10 pm](https://cloud.githubusercontent.com/assets/12078810/11408351/87235d9c-9386-11e5-8976-dec68c64aac7.png)

**Comment by 1ec5** [comment]
@adam-mapbox, `SpriteAtlas` is being leaked. Would #3049 address this issue?

**Comment by fezzik21** [comment]
I'm not sure.  If anything, https://github.com/mapbox/mapbox-gl-native/compare/tmpsantos-1488_annotations_survive_style_change would perhaps fix it; but I think that only deals with leaking the SpriteAtlas that was created for that PR.  So it wouldn't fix existing issues.  It makes me think though that something very similar to what @tmpsantos fixed for #3049 is going on here.

**Comment by syedhali** [comment]
Hey guys, I'm also experiencing this (just updated from 2.1.2 to 3.0.0). Really love the release, but we've rolled back our app to 2.1.2 because the leak is too large for now.

**Comment by 1ec5** [comment]
Any idea what could’ve caused this @jfirebaugh? If not, I can bisect later today.

**Comment by jfirebaugh** [comment]
Please do. I don't immediately see any issues in the code.

**Comment by jfirebaugh** [comment]
I suspect that `SpriteAtlas` is a symptom of a larger, parent object being leaked.

**Comment by jfirebaugh** [comment]
#3204 has a test app.

**Comment by sebyddd** [comment]
Experiencing the same issue. Tried all obvious fixes you would think off. Deallocation, autorelease pool, singleton instance, but still nothing.

**Comment by vyshane** [comment]
Any news on this? This issue blocking our adoption of MapBox.

**Comment by 1ec5** [comment]
Sorry for the silence on this issue. I've been trying to shepherd my PRs to completion lately. This is the next thing on my list.

**Comment by Dwar3xwar** [comment]
Keep up the good work :+1:

**Comment by 1ec5** [comment]
This regression was introduced in #2922. Removing the CADisplayLink nearly eliminates the heap growth:

<img width="257" alt="normalcy" src="https://cloud.githubusercontent.com/assets/1231218/12140163/8c71b78a-b41a-11e5-9b92-2fd44e39efe2.png">

**Comment by 1ec5** [comment]
I have a possible fix in #3448 and would appreciate any help verifying that redrawing continues to work in edge cases around changes in the view hierarchy or foregrounding/backgrounding.

**Comment by syedhali** [comment]
Hey @1ec5 , any chance a new iOS cocoapods release is coming by the end of Jan? We've adopted 3.0.0, but we're constantly running into memory related crashes and it looks like your fix has already been integrated into master.

**Comment by 1ec5** [comment]
@syedhali, we’re optimistically shooting for the end of next week, but as you can see from [the milestone](https://github.com/mapbox/mapbox-gl-native/milestones/ios-v3.1.0), we’ve got several issues that need to be fixed or merged first. We’ll try to get a prerelease out in the meantime. Thanks for your patience!

**Comment by ultranano** [comment]
HI @1ec5!
How much time for 3.1 on iOS?
Best regards and good work to all of us Mapbox Team

**Comment by 1ec5** [comment]
@ultranano, almost there! In the meantime, you can try out a [prerelease](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.1.0-pre.1). We'll publish another prerelease with additional improvements today or tomorrow.

**Comment by syedhali** [comment]
@1ec5 Great work on the pre-release! Memory leak seems to be fixed :) :tada:

**Comment by ultranano** [comment]
Great @1ec5!
How I can update the prerelase with cocoapods?

**Comment by 1ec5** [comment]
To install this weekend's prerelease via CocoaPods, point your Podfile to [this Podspec](https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.1.0-pre.1/ios/Mapbox-iOS-SDK.podspec). Note that, if you use Swift, you may run into #3300, which will be fixed in the next prerelease.

**Comment by chriszhang4213** [comment]
is that possible we can get a static binary release for 3.1 soon? looks like 3.01 has a huge memory leak whenever i use the map in my app, and it is not convince for use to use the CocoaPods since we don't want to make a lot of change for some other old sdk in CocoaPods,

**Comment by friedbunny** [comment]
Have a look at the [releases page](https://github.com/mapbox/mapbox-gl-native/releases) for links to (pre-)release binaries.

**Comment by chriszhang4213** [comment]
@friedbunny I am now using the mapbox-ios-sdk-3.0.1-no-bitcode.zip version now, i did download the pre-release version trying to use that in our test project. just wonder if you guys can have a sane kind of 3.1 no-bitcode version release soon

**Comment by 1ec5** [comment]
@chriszhang4213, you can obtain a Bitcode-free binary by [building from source](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md) (`make ipackage BITCODE=NO`). I’m curious what’s preventing you from adopting Bitcode in your project. Is it a particular third-party framework, perhaps, or iOS 7 support?

**Comment by chriszhang4213** [comment]
@1ec5 @friedbunny . ok, we did use some third-party framework. I am new in this part. when I download the 3.01 I follow the guide https://www.mapbox.com/ios-sdk/#binary  which is working fine on my project. then I feel like you guys didn't put new release on that download link, so i went to the Pre-release 3.1 and download the dynamic framework instead of a static library. follow the read me.txt guide ...trying to make  this work in my testing project.

then it shows #import "Mapbox.h" file not found...
I have no idea why. here is the guide i found :

### Dynamic framework

This is the recommended workflow for manually integrating the SDK into an application targeting iOS 8 and above:

1. Open the project editor and select your application target. Drag `Mapbox.framework` from the `dynamic` folder into the “Embedded Binaries” section of the General tab. In the sheet that appears, make sure “Copy items if needed” is checked, then click Finish.

1. In the Build Phases tab, click the + button at the top and select “New Run Script Phase”. Enter the following code into the script text field:
```bash
bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Mapbox.framework/strip-frameworks.sh"
```
(The last step, courtesy of [Realm](https://github.com/realm/realm-cocoa/), is required for working around an [iOS App Store bug](http://www.openradar.me/radar?id=6409498411401216) when archiving universal binaries.)

is that the right one??

**Comment by 1ec5** [comment]
@chriszhang4213, please note that 3.1.0-pre.1 is a prerelease – we’re still readying it for a final release that’ll come out soon.

**Comment by nzhuk** [comment]
Thanks for fixing the issue. Current pre-release version seems to be ios-v3.1.0-pre.3. Do you have some estimate of when we could expect 3.1.0 final release?

**Comment by ultranano** [comment]
Hi All! I see that for milestone 3.1 there is only one issue on going.
Do you have an estimate date for final release 3.1?

**Comment by 1ec5** [comment]
[Version 3.1.0 is out](https://www.mapbox.com/blog/ios-sdk-3.1.0/). CocoaPods has been updated, and the [online installation instructions](https://www.mapbox.com/ios-sdk/) have been updated for anyone installing manually. Thanks for your patience everyone!

**Comment by jasonlosito** [comment]
I am using the latest Mapbox iOS SDK and I am still experiencing memory leaks. I have a table where you can select a location and when you tap on item, it will go to a map to display the location. When I go back and forth, the memory keeps adding up and my app crashes.

**Comment by 1ec5** [comment]
@jasonlosito, it's likely that the memory leak you're experiencing is distinct from the issue that was reported here and long ago fixed. Please open a new issue, and be sure to link to an instruments trace and/or sample code that reproduces the problem, so we can be sure we're looking at the same thing as you are. Thank you!

**Comment by Craz3d** [comment]
I'm having this exact same problem as Dwar3xwar: 
1. Create 2 view controllers in a navigation controller, with VC A segueing to VC B, containing a MGLMapView.
2.Go back to the original view controller, VC B is deinitialized but memory is not freed at all.
// 
I'm on the newest softer version

**Comment by 1ec5** [comment]
Tracking in #7991.
