### ISSUE TITLE
[Android] Double-taps are sometimes mistaken for quickzooms

### ISSUE THREAD

**Issue by brewin** [mapbox/mapbox-gl-native#3132]
With ad0b37f I've noticed double-tap zooming is a little more difficult than it is on Google Maps. I think Google Maps measures the distance between double-tap ACTION_DOWN and ACTION_UP. If it's under a certain threshold (maybe getScaledTouchSlop) then it doesn't count as a quickzoom. Right now, if your finger strays a few pixels after ACTION_DOWN, it's considered a quickzoom even though it was probably just a sloppy double-tap.

**Comment by tobrun** [comment]
Closed with https://github.com/mapbox/mapbox-gl-native/commit/60b0e78e0ef7357cf6ef260a6df4241b2c5503db
