### ISSUE TITLE
Document `asset://` URL scheme for MGLMapView.styleURL

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#3134]
[`MGLMapView.styleURL`](https://www.mapbox.com/ios-sdk/api/3.0.0/Classes/MGLMapView.html#//api/name/styleURL) should additionally state that `asset://localStyle.json` is accepted.

[MGLMapView.h#L230-L235](https://github.com/mapbox/mapbox-gl-native/blob/e3992c41c354e70f2c6762690b428f0ebbe362f4/include/mbgl/ios/MGLMapView.h#L230-L235)

/cc @1ec5 @incanus

**Comment by 1ec5** [comment]
And point out that relative URLs are relative to the application bundle. It’s more natural to use relative URLs than asset: URLs with NSURL. On the other hand, styles can only refer to sprites by asset: URLs rather than relative URLs, because the conversion from relative to asset: happens in MGLMapView rather than mbgl.

**Comment by 1ec5** [comment]
As of #3203, both the iOS and OS X versions of `MGLMapView.styleURL` mention that the URL can be a relative URL. Given that, I think we should treat the acceptance of asset: URLs as an implementation detail, in case we have to change the asset: URL format in the future. asset: URLs are used in stylesheets, but anyone rolling a stylesheet by hand would need more guidance than we can offer in this documentation anyways.

**Comment by friedbunny** [comment]
Yup, I think you're right. [Here's where we're at](https://github.com/mapbox/mapbox-gl-native/blob/9d6cb1361c84fbc6736b2842037d8a3cff580d1a/include/mbgl/ios/MGLMapView.h#L101-L111):

```objc
/**
 URL of the style currently displayed in the receiver.
 
 The URL may be a full HTTP or HTTPS URL, a Mapbox URL indicating the style's
 map ID (`mapbox://styles/{user}/{style}`), or a path to a local file
 relative to the application's resource path.
 
 If you set this property to `nil`, the receiver will use the default style
 and this property will automatically be set to that style's URL.
 */
@property (nonatomic, null_resettable) NSURL *styleURL;
```
