### ISSUE TITLE
Collision debug does not properly repaint upon toggling

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#3140]
Collision debug toggling should trigger a repaint once the symbol buckets have been updated. This doesn't seem to be the case as the collision boxes are only visible e.g. when enabling collision debug after a second call to `MapContext::update()`.

Current behavior _feels_ correct because usually we are causing more repaints due to e.g. mouse gestures. In GLFW example, if we keep pressing `C` key the behavior also _feels_ correct because each time we press the shortcut, the previous repaint gives the wrong impression that collision debug state is the same as visible on-screen.

/cc @mapbox/gl

**Comment by kkaefer** [comment]
\o/
