### ISSUE TITLE
Integrate MapboxMap class

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3145]
Copies GoogleMap implementation as indicated by @bleege in https://github.com/mapbox/mapbox-gl-native/issues/2616#issuecomment-160478281.
This will boil down to applying composition/delegation to our current MapView class.
This is the first step towards making the project more modular and testable.

**Comment by tobrun** [comment]
I have been trying to migrate the whole MapView class to a separate MapboxMap class. This refactor seems a bit big to handle at once. Will granularly move code and start with integrating MapboxMap as a facade interface.

**Comment by tobrun** [comment]
Current progress can be viewed here:
https://github.com/mapbox/mapbox-gl-native/tree/3145-Mapbox-class-refactor

**Comment by tobrun** [comment]
@bleege @zugaldia 
Would love some :eyes: on progress above.

Let me explain the why, what changed and whats needs to be done to finish this:

#### Why
The gist behind the MapboxMap class is having more` partity with Google` and `more simple feature activities in testapp` but most importantly this will allow our code to be `more testable` because we can test against an non Android SDK component and we can stub out the actual Views eg. MapView.

#### What changed
 - MapboxMap is a `facade like implementation` of the old MapView.
 - Old MapView methods are hidden due to package visibility
 - Expose different methods names for #3327  and #3309
 - MapboxMap can be retrieved using the `getAsyncMap()` from #2042 
 - Feature activities are using MapFragment for better readability/simplicity

#### What needs to happen to finish
 - actual code needs to migrate from MapView into MapboxMap (current just facading)
 - feature activity for an Activity hosting a MapView (non fragment approach)
 - write tests on the new architecture

**Comment by bleege** [comment]
@tobrun It looks like the whole refactor is done in 1 commit ( 0dcc5b36e056708c073f62a9dab5a2af99b237a4 )... is this accurate?

**Comment by tobrun** [comment]
@bleege yeah, I shouldn't have rebased before pushing

**Comment by bleege** [comment]
@tobrun NP... just wanted to make sure I was looking at all the changes.

It looks like the TestApp has been refactored to only use `MapFragment`.  We'll still need some examples that use `MapView` too.  Many developers don't use Fragments and we don't want to give the incorrect impression that they have to use Fragments.

**Comment by tobrun** [comment]
As discussed with @bleege and @zugaldia. We are going for full backwards compatibility for next release (no need for version bump needed for convention semver). More relevant information and discussion points will be added to related PR so we have one place to do discussion and follow up.

**Comment by bleege** [comment]
> We are going for full backwards compatibility for next release (no need for version bump needed for convention semver)

I think there's some confusion about this.  While `MapView` will continue to exist once `MapboxMap` is created, it won't be used by developers as it currently is.  In other words the `MapboxMap` class will be used as the controller class for the map while the `MapView` will revert to more of a traditional `View` class.  This WILL require a SemVer bump as it'll be breaking an API because all the existing control methods currently in `MapView` will be moved to `MapboxMap`.

The goal of all this work is to make Mapbox Android SDK mirror the Google Maps API.  See the Google Maps [`MapView`](https://developers.google.com/android/reference/com/google/android/gms/maps/MapView) and [`GoogleMap`](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap) for more details.

**Comment by bleege** [comment]
Noting that we'll also want to remove the methods (aka, not copy them to `MapboxMap`) that were marked `@Deprecated` in #3309 and 703ccbd727561c7127aecb3455f90f7fa3eeb51f.

**Comment by tobrun** [comment]
@bleege that was my idea as well. I'm going to hold off working on this until release in #3537 has landed. Current progress has given me enough insights on how to properly tackle this.

**Comment by bleege** [comment]
@tobrun Sounds great!  Yep, `MapboxMap` is going to be the big feature for the `4.0.0` release.
