### ISSUE TITLE
Allow setting custom User-Agent for HTTP requests.

### ISSUE THREAD

**Issue by dbrant** [mapbox/mapbox-gl-native#3149]
It would be great if the SDK allowed the developer to set a custom user-agent to be used with the HTTP requests that the SDK makes. (e.g. to measure proportions of traffic coming from different versions of our app)

**Comment by friedbunny** [comment]
For reference: iOS includes the app name and version in the user agent automatically.

/cc @bleege @zugaldia @tobrun

**Comment by nyurik** [comment]
hi, any updates on this? We could really use some KPI that this feature would allow us to collect.

**Comment by bleege** [comment]
We'll be customizing User Agent strings for Android in a similar manner as iOS does.  The ticket where this is tracked is --> https://github.com/mapbox/mapbox-gl-native/issues/1993#issuecomment-221167839
