### ISSUE TITLE
Can't inherit from final MapView class

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#3150]
The `MapView` class is declared as `final`. This prevents the override of some useful methods like `onSizeChanged()` or `setZoomLevel()`. Unless there's a good technical reason not do so, we should make the class non-final.

**Comment by tobrun** [comment]
Yes I would like to see this happen, but we need to take into account how this will affect our refactor to a more loosely coupled architecture. Linking issue #3145 for that.

**Comment by tobrun** [comment]
As mentioned above: this issue is not longer relevant due to refactor in #3145, closing.
