### ISSUE TITLE
Android token not picked up

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#3153]
```sh
$ export MAPBOX_ACCESS_TOKEN=pk.<snip>
$ make android
build: osx/x86_64
host: android/arm-v7
libs: headless=none  platform=android  asset=zip  http=android  cache=sqlite
* Recreating project...
* Building target androidapp...

<snip>

BUILD SUCCESSFUL

Total time: 8.742 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.8/userguide/gradle_daemon.html
$ cat android/MapboxGLAndroidSDKTestApp/src/main/res/values/developer-config.xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="access_token">null</string>
</resources>$ 
```

**Comment by tobrun** [comment]
@incanus 
How did you set up the env. variable? 

The first time compiling the project, a couple of months ago, I initially defined an entry in my `.bash_profile`. Android studio was not able to read out that value, it would always return `null`. I found some resources that indicate that not all env. vars are automatically [available in GUI applications](http://stackoverflow.com/questions/135688/setting-environment-variables-in-os-x/588442#588442).

I resolved above by using [EnvPane](https://github.com/hschmidt/EnvPane), this worked after a reboot.

Even though above might be a solution, the setup is currently not robust enough.

**Comment by incanus** [comment]
Not a high priority here, and not sure of repro, but let's look into this again (perennial issue on both mobile platforms, it seems).

**Comment by incanus** [comment]
> How did you set up the env. variable?

Oh, and simply: 

```bash
$ export MAPBOX_ACCESS_TOKEN=pk.<snip>
```

Per above.

**Comment by tobrun** [comment]
Documentation now clearly indicates the problem mentioned above. 
Currently nothing more actionable to do with this. Closing for now.
