### ISSUE TITLE
Telemetry logging

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3155]
The iOS SDK should have a debug mode that writes the following information to a file accessible via iTunes:

* Each launch due to a background location update
* Each request the SDK makes against the events API

This will help us better diagnose and verify fixes for bugs such as #1792.

/cc @incanus @friedbunny @bleege @lxbarth

**Comment by friedbunny** [comment]
I've done something similar to this for my own debug purposes, was definitely useful. I went as far as showing the log in app, which we could think about implementing in `iosapp` or elsewhere.

**Comment by friedbunny** [comment]
Done in #3553.
