### ISSUE TITLE
onSingleTapConfirmed() logic needs to be updated

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#3156]
After implementing the ability to [allow multiple InfoWindows to be visible at a time](https://github.com/mapbox/mapbox-gl-native/issues/3115) the method `onSingleTapConfirmed()` to respond to a single tap has to be either updated or simplified.

The current solution covers the basic case (select the first marker) but doesn't seem to include other cases that the previous implementation was handling: https://github.com/mapbox/mapbox-gl-native/blob/master/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L2502

**Comment by tobrun** [comment]
After landing bugfixes related to Marker click events in #3573,
I tried running at this issue and did some manual testing:

I was able to select the correct marker almost every time in the grey circle:

![device-2016-01-19-082304](https://cloud.githubusercontent.com/assets/2151639/12412483/24fef67c-be87-11e5-94f2-d971d680b829.png)

**Comment by tobrun** [comment]
I have taken a look at the code that was already there and was placed in comment, but I'm not convinced by it. It is not actually calculation chance or distances, it is just taking into account the previous selected marker and iterating over the possible markers. 

I'm going to see if I'm able to improve current experience by calculating the distance between the click event and the marker.

**Comment by tobrun** [comment]
I started by visualising current touch area:
In this image you see 2 already selected areas and an actual down event. I believe current touch area is too big and I think we should limit this to 48dp ->min. requirement width/height touch surface on Android.

![device-2016-01-19-090626](https://cloud.githubusercontent.com/assets/2151639/12413056/2d48ad00-be8c-11e5-94a4-57b2f20b8cd8.png)

**Comment by tobrun** [comment]
I lowered the bounds of the touch area, which automatically improves selection criteria without using an algorithm to determine distance between touch event and marker.

![device-2016-01-19-094201](https://cloud.githubusercontent.com/assets/2151639/12413702/1b79528c-be91-11e5-96ad-f9a1d26be4ec.png)

**Comment by tobrun** [comment]
To demonstrate how this improves selection:

![device-2016-01-19-095451](https://cloud.githubusercontent.com/assets/2151639/12413941/b57106fe-be92-11e5-9df5-2dfda712eb27.png)

If I debugged this type of interaction with initial configuration, I would receive a callback with 3 possible touch targets. Now I'm only receiving one!

**Comment by tobrun** [comment]
One thing I will implement in `singleTapConfirmed` is if there are 2 side by side and one marker is already selected, I'm going to select the other marker. That is the only use-case that I'm currently seeing that needs improvement.

**Comment by tobrun** [comment]
You can see above implemented here:
https://www.dropbox.com/s/ycucb7t92c7nu1s/device-2016-01-19-101337.mp4?dl=0

**Comment by tobrun** [comment]
It even manages overlapping markers very well:
https://www.dropbox.com/s/cp25y7mr7p243l3/device-2016-01-19-102250.mp4?dl=0

**Comment by tobrun** [comment]
Going to commit and PR

**Comment by tobrun** [comment]
This will land in the release branch of `3.1.0` from #3537

**Comment by tobrun** [comment]
Landed with 6b3745c in branch mentioned above.

**Comment by zugaldia** [comment]
@tobrun Love it, I didn't know our touch area was so wide. By the way, this ticket is a great candidate for the 3.1.0 blog post (https://github.com/mapbox/mapbox-gl-native/issues/3537).

**Comment by tobrun** [comment]
@zugaldia 
yeah that was a surprise for me as well!

cc @bleege

**Comment by bleege** [comment]
Yep, this is likely technical debt from the original default marker implementation which was bigger than the current red one.  Good :eyes: to spot this and fix it!  :+1:
