### ISSUE TITLE
MGLMapView should map annotation IDs to annotation metadata

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3159]
MGLMapView holds an NSMapTable mapping MGLAnnotation objects to dictionaries containing IDs and other metadata. The problem is that IDs aren’t metadata; they’re the unique key. So many operations that should be simple lookups end up requiring expensive loops or are simply impossible. For example, [this loop through all annotation metadata](https://github.com/mapbox/mapbox-gl-native/blob/e7b6d72cd12aae845f56c92db53dad608217726a/platform/ios/MGLMapView.mm#L1103) can be very expensive, and it isn’t possible to put a fix for #1504 in there because a) we’re iterating over all the annotations, not just the nearby ones, and b) the annotation ID is inaccessible.

I ran into this issue while working on #1496 and again while trying to port the fix for #1504 back from OS X to iOS. For the OS X version of MGLMapView in #3135, I started out with a mapping from annotation IDs (`MGLAnnotationTag`) to annotation context objects, and it has worked out very well. There are couple places where I need to get an ID from an annotation, and performance is fine in those places.

/cc @incanus

**Comment by tyoshii-uie** [comment]
After this change, removeAnnotation() and removeAnnotations() of MGLMapView crashes when annotation has not been added, with following assertion.

NSAssert(annotationTag != MGLAnnotationTagNotFound, @"No ID for annotation %@", annotation);

I think removeAnnotation can be called whether the annotation is added or not.

**Comment by 1ec5** [comment]
Thanks, @tyoshii-uie. Fixed in #3685.

**Comment by t-yoshii** [comment]
Thank you for your quick response!
