### ISSUE TITLE
Automate access token setup when installing via CocoaPods

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3160]
To eliminate any friction that might arise from having to set an access token, the Mapbox iOS SDK should automate the recommended process for completely private access tokens.
1. In the podspec’s [`prepare_command`](https://guides.cocoapods.org/syntax/podspec.html#prepare_command), run a script that opens the [access token manager](https://www.mapbox.com/studio/account/tokens/), prompts for an access token, and writes it to a file in the user’s home directory.
2. In a Run Script build phase, read that file and [put its contents into the application’s Info.plist](https://www.mapbox.com/help/ios-private-access-token/). (Does CocoaPods support this?)

This approach will facilitate sharing Mapbox-powered code bases with others as open source projects, if desired, [without compromising access token security](https://www.mapbox.com/help/ios-private-access-token/).

/cc @incanus @lxbarth @friedbunny @bsudekum

**Comment by 1ec5** [comment]
CocoaPods purposely doesn’t provide a way to add a build phase to the application target (CocoaPods/CocoaPods#2326), but it might be possible to do it ourselves [via the `xcodeproj` gem](http://stackoverflow.com/a/20505234/4585461).

**Comment by Snorlock** [comment]
Did you ever end up using the prepare_command? To get the runscript build phase up and running? Couldnt find in your PR which was merged

**Comment by 1ec5** [comment]
We haven't landed any work related to this PR, which is why the issue is still open. One of the unresolved questions around this idea is that the first `pod install` would require user intervention. That could be a dealbreaker for any application that needs to run in an automated fashion, whether on Xcode Server or Bitrise.

**Comment by Snorlock** [comment]
Yeah i just was led here by another issue talking about prepare_command and Runscripts, so thought you might had done something about it in the merged PR on this issue.

**Comment by 1ec5** [comment]
Ah, sorry, https://github.com/mapbox/mapbox-gl-native/pull/3183#issuecomment-166713154 merely referred to this idea as an alternative to displaying a checklist for the developer to follow in the IB designable that this framework vends.
