### ISSUE TITLE
explore framework install for iOS

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#3161]
We have a framework script as of https://github.com/mapbox/mapbox-gl-native/commit/01b4f160d40b5899ed455e02bd673deca96b3a36. If we were to modify our CocoaPods spec to allow install from this framework, could we: 

1. Provide symbolicated/stripped `Mapbox.framework` zips instead of our current static library zips? 
1. Avoid use of `use_frameworks!` in users' `Podfile` because we already have a namespaced framework? 
1. Make drag and drop install with auto-linking of dependencies more of a reality? 

@1ec5 @friedbunny

**Comment by 1ec5** [comment]
With #3183, we’re moving to a dynamic framework as the preferred installation method, so the answer will be yes, yes, and yes.
