### ISSUE TITLE
never scale images when copying them into the SpriteAtlas

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#3164]
Currently we bilinearly scale images that are not at the native pixel ratio up or down when adding them to the SpriteAtlas. This has led to code that is more complex than necessary and produced issues like #3031 and #2198.

Instead, we should copy images into the SpriteAtlas pixel-for-pixel, and let up/down sampling happen in the shaders.

@kkaefer @ansis -- am I missing anything that would make this non-viable?

**Comment by ansis** [comment]
> Instead, we should copy images into the SpriteAtlas pixel-for-pixel, and let up/down sampling happen in the shaders.
> @kkaefer @ansis -- am I missing anything that would make this non-viable?

I agree that we should do it this way. This is what we're still doing in -js. The scaling was never ported. relevant discussion: https://github.com/mapbox/mapbox-gl-js/issues/1124

**Comment by jfirebaugh** [comment]
@kkaefer @ansis Is there any significance to the use of `2` here:

https://github.com/mapbox/mapbox-gl-js/blob/abe3512815032f02a0edefe38c732b4431535b3a/js/symbol/sprite_atlas.js#L114

While 1 is used everywhere else:

https://github.com/mapbox/mapbox-gl-js/blob/abe3512815032f02a0edefe38c732b4431535b3a/js/symbol/sprite_atlas.js#L91
https://github.com/mapbox/mapbox-gl-js/blob/abe3512815032f02a0edefe38c732b4431535b3a/js/symbol/sprite_atlas.js#L173
https://github.com/mapbox/mapbox-gl-native/blob/2a0d2b7f0bb655607f4104b1d22b23d4cd1d6e2b/src/mbgl/sprite/sprite_atlas.cpp#L99
https://github.com/mapbox/mapbox-gl-native/blob/2a0d2b7f0bb655607f4104b1d22b23d4cd1d6e2b/src/mbgl/sprite/sprite_atlas.cpp#L120
https://github.com/mapbox/mapbox-gl-native/blob/2a0d2b7f0bb655607f4104b1d22b23d4cd1d6e2b/src/mbgl/sprite/sprite_atlas.cpp#L134

If not, I'm going to use `1` everywhere and remove the duplication.

**Comment by ansis** [comment]
I'm not sure, but I think the `2` means 1px padding on each of the two sides. I think it's correct but not clear.

**Comment by jfirebaugh** [comment]
native definitely uses 1 at the [equivalent spot](https://github.com/mapbox/mapbox-gl-native/blob/2a0d2b7f0bb655607f4104b1d22b23d4cd1d6e2b/src/mbgl/sprite/sprite_atlas.cpp#L34-L35).

**Comment by jfirebaugh** [comment]
This is getting bumped from my priorities.
