### ISSUE TITLE
How to set Openstreetmap layer

### ISSUE THREAD

**Issue by Mizuki123** [mapbox/mapbox-gl-native#3166]
Hi everyone.

I'm working on an android application using Mapbox android sdk 2.2.0.

I want to use openstreetmap for layer source of my MapView but i don't know how to set this source without the WebSourceTileLayer that seems to be deleted in this new sdk version. Is anyone know the way to set openstreetmap source for my mapview ?

In addition, I want to add another layer over my openstreetmap layer but I didn't see anywhere a method to do that. So, is anyone know how to do this feature ?

Thanks for your help.

**Comment by jfirebaugh** [comment]
For creating map styles, including using OpenStreetMap data and your own data, the best method is to use [Mapbox Studio](https://www.mapbox.com/mapbox-studio/).

If you have further questions, check out https://www.mapbox.com/help/. Thanks for using Mapbox!

**Comment by Mizuki123** [comment]
Thanks for your answer.

But I need to access my maps from one of my custom web service. Is there a way to set the MapView with my maps without using Mapbox Studio ?

Best regards

**Comment by friedbunny** [comment]
@Mizuki123 If you're looking to show OSM raster tiles, check out this example: https://www.mapbox.com/android-sdk/custom-raster-style/
