### ISSUE TITLE
Show / Hide a layer programmatically

### ISSUE THREAD

**Issue by franckt** [mapbox/mapbox-gl-native#3169]
Hi, 
Is it possible to show or hide a layer at runtime identified by an id ?

for example this style by "landcover_crop"
               {
               "id": "landcover_crop",
               "type": "fill",
               "source": "composite",
               "source-layer": "landcover",
               "filter": [
                          "==",
                          "class",
                          "crop"
                          ],
               "maxzoom": 14,
               "layout": {
               "visibility": "visible"
               },

**Comment by 1ec5** [comment]
Not yet, but we’re working on it for #837.
