### ISSUE TITLE
icon alignment differences in tests

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#3175]
Moved from https://github.com/mapbox/mapbox-gl-js/issues/1569 now that this happens only in native.

icon-offset/literal:

http://mapbox.s3.amazonaws.com/mapbox-gl-native/render-tests/8219.6/index.html

![image](https://cloud.githubusercontent.com/assets/98601/11576748/e444e890-99cd-11e5-8e92-f124a58ef964.png)

**Comment by brunoabinader** [comment]
Possibly Fixed in 5e7736ce87f558e2d57869efef9512bcc3d2d1a5.

**Comment by brunoabinader** [comment]
Fixed in #6899.
