### ISSUE TITLE
Tilt user dot on Android

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3189]
The user dot or at least its accuracy circle should be transformed to appear flat against the map. See #2233 for the iOS equivalent.

/cc @zugaldia @friedbunny

**Comment by zugaldia** [comment]
@1ec5 Yes.

Also, related: Is iOS doing the same thing with InfoWindows (callouts), i.e. those farther look smaller, closer InfoWindows look bigger? I noticed we aren't changing those either and we might extend this ticket to native (as in Android) annotations.

**Comment by tobrun** [comment]
@zugaldia 
I have been thinking about introducing a generic system around the whole View versus GL interaction..
The most of these Android Views will support the same behaviour.

**Comment by 1ec5** [comment]
It probably doesn't make sense for the InfoWindows to shrink into the distance, becoming illegible. #2186 tracks shrinking the iOS user dot and its accuracy circle as it goes farther away. Ideally the Android version would too. This would be a good opportunity to introduce a "pixels per meter at distance from center" method in mbgl along the lines of the existing metersPerPixelAtLatitude().

**Comment by tobrun** [comment]
@1ec5 
thank you for adding the `pixels per meter at distance from center` explenation, will get back to you if I can't figure it out on myself using `metersPerPixelAtLatitude()` as an example.

**Comment by bleege** [comment]
Related to #2233 (user puck / hoverdot)

**Comment by tobrun** [comment]
Been looking into titling the `UserLocationView` itself without suggested methods. 
Currently facing the problem that the height and width of `UserLocationView` is match_parent.
The normal way of calling setRotationX will not work in that case.

**Comment by tobrun** [comment]
I'm tackling this issue in #4396.

You can see the tilted UserLocationView in the 4th row:

![device-2016-04-08-083143](https://cloud.githubusercontent.com/assets/2151639/14375808/71f0a022-fd64-11e5-9f0d-f2d5a7462e60.png)

**Comment by tobrun** [comment]
Landed in https://github.com/mapbox/mapbox-gl-native/pull/4695

**Comment by bleege** [comment]
:rocket:
