### ISSUE TITLE
Multiple Custom Icons 

### ISSUE THREAD

**Issue by scottfoltz** [mapbox/mapbox-gl-native#3196]
Trying to add two different markers with different icons, but every time I try both markers are set to the same image.. Don't know why this is happening...

**Comment by 1ec5** [comment]
Hi @scottfoltz, first of all, this repository covers a variety of platforms, including iOS and Android. Which Mapbox SDK are you using (and which version)?

**Comment by scottfoltz** [comment]
Android, sorry for not specifying.

**Comment by 1ec5** [comment]
No problem. (@zugaldia @bleege, could you help here? I’m not really familiar which questions to ask for Android. :smile:)

**Comment by scottfoltz** [comment]
Nevermind fixed it. thanks anyways

**Comment by zugaldia** [comment]
Scott and I were in touch via the tweets. Glad to hear this was fixed, ping us again if you run into any issues.
