### ISSUE TITLE
Disable annotationCanShowCallout for userLocation

### ISSUE THREAD

**Issue by AdamBCo** [mapbox/mapbox-gl-native#3201]
I looked through the documentation and couldn't find a way to specifically disable the annotationCanShowCallout for the userLocation annotation.

Could someone please help me achieve this result?

Thank you

**Comment by 1ec5** [comment]
Your map view delegate can check whether the passed-in annotation is the `userLocation` annotation:

```
- (BOOL)mapView:( MGLMapView *)mapView annotationCanShowCallout:(id <MGLAnnotation>)annotation {
    return annotation != self.mapView.userLocation;
}
```

**Comment by AdamBCo** [comment]
@1ec5 Thank you!
