### ISSUE TITLE
Add support for tinting UserLocationView and Attribution icon

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3231]
iOS currently exposes a feature that allows tinting the UserLocationView and the Attribution Icon.

On Android we can support automatic tinting by using:
```xml
<resources>
  <!-- inherit from the material theme -->
  <style name="AppTheme" parent="android:Theme.Material">
    <!-- Main theme colors -->
    <!--   your app branding color for the app bar -->
    <item name="android:colorPrimary">@color/primary</item>
    <!--   darker variant for the status bar and contextual app bars -->
    <item name="android:colorPrimaryDark">@color/primary_dark</item>
    <!--   theme UI controls like checkboxes and text fields -->
    <item name="android:colorAccent">@color/accent</item>
  </style>
</resources>
```

cc @bleege @zugaldia

**Comment by tobrun** [comment]
I have seen requests for this feature, going to add it now

**Comment by tobrun** [comment]
I'm able to reference the client app from the lirary using `colorPrimary`, `colorPrimaryDark` and `colorAccent` as attributes:

```java
    @ColorInt
    public static int getPrimaryColor(@NonNull Context context) {
        TypedValue typedValue = new TypedValue();
        Resources.Theme theme = context.getTheme();
        theme.resolveAttribute(R.attr.colorPrimary, typedValue, true);
        return typedValue.data;
    }
```

**Comment by tobrun** [comment]
Tinting the attribution icon will require creating a state selector with tinted drawables.

Tinting the UserLocationView will require some refactoring, it is using an image with [multiple colors](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/res/drawable-xxxhdpi/my_location.png).

**Comment by tobrun** [comment]
Here is an example where I changed the colors of the testapp:
 - primary: #F44336
 - primaryDark: #D32F2F
 - accent: #536DFE

![device-2016-01-13-104553](https://cloud.githubusercontent.com/assets/2151639/12290583/e5c1dc48-b9e2-11e5-8e7d-a8dad953bb69.png)


As you can see, we need to refactor `UserLocationView` to draw the outer white circle programatically.

**Comment by tobrun** [comment]
I forgot to mention the update to attribution dialog:

![device-2016-01-13-105203](https://cloud.githubusercontent.com/assets/2151639/12290743/b603aa3a-b9e3-11e5-9d7a-2cead69ce7ca.png)

**Comment by tobrun** [comment]
Above tests where done on a Marshmallow device containing the newer attributes, a quick test on a older device shows that this is not working on device prior to Lollipop:

![device-2016-01-13-110359](https://cloud.githubusercontent.com/assets/2151639/12291116/ab626cb8-b9e5-11e5-84d4-2719c046ad73.png)

**Comment by tobrun** [comment]
My initial idea that attributes are not available is incorrect, these will probably be added by the `support-v7` dependency. The code mentioned [here](https://github.com/mapbox/mapbox-gl-native/issues/3231#issuecomment-171222488) is returning the correct value after I debugged it with `Integer.toHexString(typedValue.data)` -> #fff44336.

**Comment by tobrun** [comment]
Items required to close this issue:
 - [ ] test without having a `support-v7` dependency
 - [ ] refactor `UserLocationView` to draw a white circle pragmatically

**Comment by mayardb** [comment]
Hi @tobrun,

in our application, we are facing kind of the same issue: customizing the `UserLocationView`.
In our case, we do not want a circle for the bearing and prefer use an arrow.

I have been able to reach the goal by adding some setters in `UserLocationView`.

Here is the interface in MapView:
```
    public void setUserLocationDrawable(@NonNull Drawable drawable);
    public void setUserLocationDrawable(@DrawableRes int drawableId);
    public void setUserLocationBearingDrawable(@NonNull Drawable drawable);
    public void setUserLocationBearingDrawable(@DrawableRes int drawableId);
    public void setUserLocationStaleDrawable(@NonNull Drawable drawable);
    public void setUserLocationStaleDrawable(@DrawableRes int drawableId);
    public void setUserLocationAccuracyColor(int fillColor, int strokeColor);
    public void setUserLocationAccuracyColor(int fillColor, int fillAlpha, int strokeColor, int strokeAlpha);
```

I think it is more generic than using the primaryColor, and you can still expose a Shape in drawable like this to reach the tinting:
```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
        android:shape="oval">

    <size android:width="18dip" android:height="18dip"/>
    <solid android:color="@color/primary" />
    <stroke android:color="@android:color/white" android:width="1dp"/>
    <padding android:left="10dip" android:top="10dip" android:right="10dip" android:bottom="10dip" />

</shape>
```

Here is what I am getting (not using "@color/primary" but another custom color) :
![image](https://cloud.githubusercontent.com/assets/6266608/12295457/70507e0a-ba01-11e5-8b59-a2a648a6ddb0.png)


What do you think about these ideas ?
By the way, I can do a pull request if you need so.

**Comment by zugaldia** [comment]
@tobrun: Love how it's looking like.

@tobrun @mayardb: I think we should keep the API compatible with our iOS offering whenever possible (adjusting it to Android specifics). Would this be the case?

**Comment by RomainQuidet** [comment]
@zugaldia Which iOS API are you talking about?

**Comment by tobrun** [comment]
@zugaldia  @mayardb 
Since I'm already obliged to refactor UserLocationView for tinting, I might take up the possibility to use resource overloading to change the image. I always keep in mind to be on par with iOS but I feel this feature is easy to implement and gives our users the customisability they deserve. 

Note:
Users have rebuild the SDK from source to do this themselves.  Let us make it easier for them. 

cc @bleege

**Comment by tobrun** [comment]
Been thinking about which API we are going to expose and eventually commit to. 

I'm confident on the non-Java API:
 -  exposing different tint color [attributes](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml) for UserLocationView
   - If unavailable, use color attributes defined by the [theme](https://github.com/mapbox/mapbox-gl-native/issues/3231#issue-121144298) of the client application.
     -  if still unavailable, don't tint or use Mapbox colors.
 - allow resource overloading by client application
  - the developer adds an image with a specific name, the build system will use that one and will remove the one from this library.

I'm still thinking about what we are exposing on the java side:
 - @mayardb shows [above](https://github.com/mapbox/mapbox-gl-native/issues/3231#issuecomment-171289976) how the Java API will look like with current `UserLocationView`.
 - A lot will depend on how `UserLocationView` will be refactored. Some things I'm thinking about:
   -  Dropping drawables all together and drawing this ourselves
   -  Replace current 3 drawable setup by one
   -  Expose 3 drawable setup
   - ....

**Comment by tobrun** [comment]
Putting a note here that iOS also uses the tint for default colour of Polylines and Polygons.

**Comment by tobrun** [comment]
The blocking part for this issue was not being able to tint UserLocationView.
I'm picking that up as part of #4396 and I will merge in this functionality as part of that PR.

Current tinting result can be seen in the third row:

![device-2016-04-08-084817](https://cloud.githubusercontent.com/assets/2151639/14376076/ab03c342-fd66-11e5-9586-efe4a65932cf.png)

**Comment by tobrun** [comment]
User Location View tinting has landed in https://github.com/mapbox/mapbox-gl-native/pull/4695. 
We can now start with integration of this feature.

**Comment by tobrun** [comment]
I resurrected the code form the related PR and cherrypicked in onto current master:

Our testapp styles are now automatically applied using the `primary`,`primaryDark` and `primaryAccent`:

![device-2016-04-26-085020](https://cloud.githubusercontent.com/assets/2151639/14809234/f5490fc4-0b8b-11e6-8e3a-4d71295238c3.png)

![device-2016-04-26-085616](https://cloud.githubusercontent.com/assets/2151639/14809352/c1927336-0b8c-11e6-877b-01d932284f05.png)

Changing our theme colors to red, darkRed and yellow:

![device-2016-04-26-085401](https://cloud.githubusercontent.com/assets/2151639/14809315/757e6ce8-0b8c-11e6-9ebf-255c69042a8d.png)


![device-2016-04-26-085432](https://cloud.githubusercontent.com/assets/2151639/14809319/83bb0bea-0b8c-11e6-8c57-a8a25b4aa72f.png)

**Comment by bleege** [comment]
:rocket: :rocket: :rocket: :rocket:

**Comment by p-fischer** [comment]
Automatic tinting worked great when I was using mapbox version 4.2.2. I just made a big version jump to 6.6.0 and the attribution icon as well as the dialog window ignore the app's primary color. 
@tobrun Is automatic tinting in primary color still supposed to work?
