### ISSUE TITLE
How to expose the camera and compile a special version?

### ISSUE THREAD

**Issue by dagatsoin** [mapbox/mapbox-gl-native#3233]
I am trying to get the camera exposed to React Native but the current version of MapboxGL does not seem to expose the MGLMapCamera. So I am trying to modify the source to expose it.
But What scheme do I have to compile and what resulting file I have to import in the React Native project?
Plus, do you know what file I have to tweak to expose the camera properties?

**Comment by 1ec5** [comment]
MGLMapCamera should definitely be visible, as should the -camera, -setCamera:, and -setCamera:animated: (etc.) methods on MGLMapView. MGLMapCamera is defined in MGLMapCamera.h. Do you have this project checked out directly, or the version that react-native-mapbox-gl pulls down?

/cc @bsudekum

**Comment by dagatsoin** [comment]
To be more precise: I need a reference to the camera for binding it to React Native. I need to use pitch and maybe other properties from the MGLView always in sync with other part of my React Native code.

**Comment by dagatsoin** [comment]
Ho. I think I am wrong. Indeed the reference is passed correctly. The nil value is caused by the camera initialization. So it is OK I don't need to dig in the MapboxGL Native project.
