### ISSUE TITLE
Inconsistent package name for TestApp

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#3238]
In `AndroidManifest.xml` we're using `com.mapbox.mapboxsdk.testapp` as the package name, while the `build.gradle` file uses `com.mapbox.mapboxgl.testapp`.

I found out about this when manually launching the app using `adb`, which needs something like this:

```
$ adb shell am start  -n "com.mapbox.mapboxgl.testapp/com.mapbox.mapboxsdk.testapp.MainActivity"
```

Any reason for this? Otherwise, we should decide on just one.

/cc: @bleege @tobrun

**Comment by tobrun** [comment]
@zugaldia 
Nice catch, I believe it should be `com.mapbox.mapboxsdk.testapp`, the `com.mapbox.mapboxgl.testapp` is an artefact from prior the decision reusing the raster SDK package.

**Comment by bleege** [comment]
> com.mapbox.mapboxsdk.testapp

Yep, this is the one to use.  `com.mapbox.mapboxgl.testapp` was the original package name that we used before we refactored it to fit into the existing raster Mapbox Android SDK package name.
