### ISSUE TITLE
-[MGLMapView selectAnnotation:animated:] does not pan map to fit callout view

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3249]
When YES is passed into `-[MKMapView selectAnnotation:animated:]`, MKMapView automatically pans so that the entire callout view fits in the viewport. Instead, `-[MGLMapView selectAnnotation:animated:]`’s `animated` parameter controls whether the callout view fades in.

A fix for this discrepancy may have to wait until we fix #3154 and #2618.

/cc @incanus @friedbunny

**Comment by 1ec5** [comment]
Now that #6676 has landed, this is no longer blocked.

**Comment by 1ec5** [comment]
This could just be a matter of calling `-showAnnotation:` within `-selectAnnotation:animated:`. However, we’d have to take care not to reenter `-selectAnnotation:animated:` and cause infinite recursion.

**Comment by 1ec5** [comment]
`-showAnnotation:` puts the annotation in the center of the viewport, which for point annotations would lead to an undesirable wandering effect as the user selects various annotations. But we could craft a simple method that pans the map only enough to show the point annotation and its callout.

**Comment by 1ec5** [comment]
https://github.com/mapbox/mapbox-gl-native/issues/2600#issuecomment-357845624 illustrates what the fix for this issue might look like inside MGLMapView.

**Comment by julianrex** [comment]
Closing since this was addressed in #11442
