### ISSUE TITLE
Migrate iOS targets to checked-in Xcode projects

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3275]
Currently, on OS X, all libraries and executables are built by Xcode projects generated by gyp. This system is ill-suited for iOS and OS X development: for instance, to add a file to the iOS SDK, you need to move the file to the right folder, `git add` the file, and finally edit the appropriate .gypi file to include it. The process gets even more involved when adding a new target, such as a test bundle: you need to essentially reverse-engineer Xcode’s template for that target to ensure that all the required build settings are persisted across invocations of `make iproj`.

We should migrate the platform-ios and iosapp targets to a checked-in Xcode project, similar to the [ios-tests.xcodeproj](https://github.com/mapbox/mapbox-gl-native/tree/master/test/ios/ios-tests.xcodeproj) that’s already checked in. Adding a new file thus becomes a matter of adding it in Xcode (which handles git and any required build phase updates automatically). If folks are uncomfortable with the idea of maintaining build settings in a .pbxproj file, we can put those settings in .xcconfig files ([example](https://github.com/realm/realm-cocoa/blob/master/Configuration/Realm/Realm.xcconfig)), which are less prone to conflicts.

The new Xcode project would continue to depend on the output of gyp-generated core projects. We’d probably check in a workspace that ties together all the projects to ensure that they get built together. With these changes, we’ll also be able to remove much of the shell scripting that forms the final part of the iOS SDK build process.

/cc @mapbox/gl

**Comment by 1ec5** [comment]
GitHub, that was the subjunctive mood, not the indicative.

**Comment by kkaefer** [comment]
lol
