### ISSUE TITLE
setCenterCoordinate doesn't animate

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3283]
While investigating #2791 I noticed that `setCenterCoordinate(latLng, true /*animated*/)` doesn't work. I have added an example feature activity to help out debug this in https://github.com/mapbox/mapbox-gl-native/issues/3270. I created this separate feature activity because their are too many moving parts in user location tracking to debug this efficiently.

**Comment by tobrun** [comment]
cc @bleege @zugaldia

**Comment by tobrun** [comment]
Linking #2049

**Comment by tobrun** [comment]
I'm taking a look a this, will try out the new camera api from #3244

**Comment by tobrun** [comment]
Using following methods did not give the expected results:
  - flyTo() 
  - jumpTo()
  - easeTo()

I was able to animate it correctly using higher level api:

```java
 @UiThread
    public void setCenterCoordinate(@NonNull LatLng centerCoordinate, boolean animated) {
        if (centerCoordinate == null) {
            Log.w(TAG, "centerCoordinate was null, so just returning");
            return;
        }

        CameraPosition cameraPosition = new CameraPosition.Builder(getCameraPosition())
                .target(centerCoordinate)
                .build();

        animateCamera(CameraUpdateFactory.newCameraPosition(cameraPosition),
                (int) ANIMATION_DURATION, null);

}
```

You can see above result [here](https://www.youtube.com/watch?v=uA4DgyiMfMk&feature=youtu.be)

**Comment by tobrun** [comment]
Next things to do are optimising, backporting and deprecating the `setCenterCoordinate` method and see how this implementation stacks up in the `UserLocationTracking` issue

**Comment by tobrun** [comment]
Backporting will look like this:

```java
    public void setCenterCoordinate(@NonNull LatLng centerCoordinate, boolean animated) {
        if (centerCoordinate == null) {
            Log.w(TAG, "centerCoordinate was null, so just returning");
            return;
        }

        if (animated) {
            CameraPosition cameraPosition = new CameraPosition.Builder(getCameraPosition())
                    .target(centerCoordinate)
                    .build();
            animateCamera(CameraUpdateFactory.newCameraPosition(cameraPosition),
                    (int) ANIMATION_DURATION, null);
        } else {
            jumpTo(mNativeMapView.getBearing(), centerCoordinate, mNativeMapView.getPitch(), mNativeMapView.getZoom());
        }
    }
```

For and end-developer the API is unchanged but underneath we are using the newer Camera API.

**Comment by tobrun** [comment]
Will not add deprecation notice until validated by co-workers and other methods to be deprecated with replaced implementations are in place (eg. bearing, tilt, etc.).

Will PR current `setCenterCoordinate` so this issue van be closed down, 
will test out user location tracking in its own issue #2791

**Comment by bleege** [comment]
This looks like it's coming along nicely @tobrun.  :+1: 

> Will not add deprecation notice until validated by co-workers and other methods to be deprecated with replaced implementations are in place (eg. bearing, tilt, etc.).

Feel free to roll the replacement of `setCenterCoordinate()` with `moveCamera()` from #3309 in with this fix.  No need to solve the animation issue for the `setCenterCoordinate()` methods if those methods are going away.
