### ISSUE TITLE
What is MultiPoint

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#3288]
Something seems off about this

https://github.com/mapbox/mapbox-gl-native/blob/master/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MultiPoint.java
- The docs refer to it as being a 'polyline'
- There's a MultiPoint.java, but not a Point.java
- Besides geometry, it also manages alpha, but just alpha.

What's up with this?

**Comment by tmcw** [comment]
Reading into this, yeah, it's a coordinate-container abstract class that's extended by Polygon and Polyline. That shouldn't be the case, it should be named something else and more obviously documented.

**Comment by tobrun** [comment]
@tmcw 
> The docs refer to it as being a 'polyline'

Can you show me what you which docs you are referring to? 

> it's a coordinate-container abstract class that's extended by Polygon and Polyline.

Where are you reading this, this is not part of the javadoc. 
I created #3338 to improve javadoc for the annotations package.

**Comment by tmcw** [comment]
It's referred to as a polyline here: https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MultiPoint.java#L28

It's extended at https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Polyline.java and https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Polygon.java

There's isn't necessarily a logic problem here, but the usage of MultiPoint really conflicts with its usage elsewhere, in the Simple Features Spec, GeoJSON, and other geo standards.

**Comment by tobrun** [comment]
@tmcw 
Current gameplan is to refactor annotations with the `4.0.0` release.

I'm looking into the possibility to:
 - remove Multipoint & Annotation base classes (not that logical)
 - remove Icon and Iconfactory (obsolete, not needed)
 - streamline with requirements coming from geo standards

**Comment by zugaldia** [comment]
@tmcw After releasing the directions and geocoder libraries we've noticed that there's some work we need to do to streamline our geographic data structures. See for example the unnecessary conversion we need to do [in this example](https://github.com/mapbox/mapbox-directions-android#draw-the-route-on-a-map) from `List<Waypoint>` into `LatLng[]` (not to mention that Android has its own [`Location`](http://developer.android.com/reference/android/location/Location.html) object).

I want to put some effort into fixing this and I'd love your feedback. What would be in your opinion the best approach here? Would be using the GeoJSON standard as our objects building block the way to go?

**Comment by zugaldia** [comment]
Related: https://github.com/mapbox/mapbox-gl-native/issues/3630

**Comment by 1ec5** [comment]
The iOS and OS X SDKs have a similar class naming issue, captured in #3288.

**Comment by tobrun** [comment]
This change didn't land with `4.0.0`, we need to look into with next semver-major release

**Comment by ivovandongen** [comment]
Removed the current milestone as this requires breaking changes to the api
