### ISSUE TITLE
No clear way for Polygon to support inner rings

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#3289]
MultiPoint supports a singly-nested array of coordinates; this is not enough for a Polygon with rings. Most (all) geographical formats supports inner rings, so we should too.

**Comment by 1ec5** [comment]
Also on iOS: #1729.

**Comment by jfirebaugh** [comment]
Let's track full multipolygon/holed polygon support across all platforms at #1729.
