### ISSUE TITLE
make osx builds OS X framework without Xcode, fails

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3293]
`make osx` attempts to build the OS X framework using make instead of `xcodebuild`. The framework target relies on Xcode-specific build settings, so it fails to build under make:

```
../../platform/osx/sdk/Mapbox.m:1:9: fatal error: 'Mapbox/Mapbox.h' file not found
#import <Mapbox/Mapbox.h>
        ^
1 error generated.
```

If `make osx` is useful in its own right, it should avoid building the framework and osxapp and limit itself to just the headless parts. Otherwise, we should remove the target because we already have `make ipackage` and `make xosx`.

/cc @brunoabinader @kkaefer

**Comment by kkaefer** [comment]
It's fine to remove that now that we have made the packt with the devil^H^H^H use Xcode.

**Comment by 1ec5** [comment]
Hey now. :wink:

**Comment by brunoabinader** [comment]
We're handling `make linux` build on OSX in #3294.
