### ISSUE TITLE
`make linux` should work on OSX

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#3294]
OSX also supports GLFW, which is the base for `linux` build target.

Extra: @kkaefer and @1ec5 spoke about changing that target name to `glfw` if that makes sense.

/cc @tmpsantos

**Comment by brunoabinader** [comment]
`make linux` is working mostly fine in OSX, with exception to these interesting warning messages (might be specific to my environment):
> ld: warning: object file (./Release/libmbgl-cache-sqlite.a(sqlite_cache.o)) was built for newer OSX version (10.10) than being linked (10.9)

**Comment by 1ec5** [comment]
That’s similar to mapbox/mapbox-gl-native#1707. In #3135, I changed the minimum OS X deployment target from 10.9 to 10.10. It’s possible that I missed a spot.

**Comment by brunoabinader** [comment]
`make linux` now works fine on OSX.
