### ISSUE TITLE
Re-enable CoreTelephony.framework telemetry

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#3295]
Linking CoreTelephony.framework was broken in v3.0.0 and removed entirely in v3.0.1. Cellular carrier and network statistics are still useful, so let's bring it back.

We never pinned down exactly why it was crashing (#3112), but I suspect the situation will be improved by moving to a dynamic framework distribution (#3183) and we should reinvestigate after that happens.

[Last included code.](https://github.com/mapbox/mapbox-gl-native/blob/43ca910f5484c15830a0fc24164df1799a17b6ca/platform/ios/MGLMapboxEvents.m#L79-L94)

/cc @incanus @1ec5

**Comment by 1ec5** [comment]
@friedbunny, does #3183 address this issue?

**Comment by friedbunny** [comment]
I'll look at how the conditional CoreTelephony code performs in our dynamic framework, but I wouldn't be opposed to requiring CT again if it still proves buggy.

**Comment by friedbunny** [comment]
Going to move this to the next release (currently v3.2.0) to let the dust settle on all the telemetry changes and dynamic framework'ing.

**Comment by mikemorris** [comment]
I've been testing re-adding conditional CoreTelephony support, but can't seem to get past the crash in https://github.com/mapbox/mapbox-gl-native/issues/3112. It looks like the public CoreTelephony classes might be defined in header files (and as such are always present so the `NSClassFromString` check passes), but private, internal classes depend on symbols in CoreTelephony.framework and are therefore missing when it's not linked.
<img width="647" alt="screen shot 2016-02-16 at 6 17 16 pm" src="https://cloud.githubusercontent.com/assets/1149913/13094580/9376e6a6-d4d9-11e5-9d91-8ca3669601fc.png">

**Comment by friedbunny** [comment]
Went ahead and removed this from the v3.3.0 milestone. At this point, I think we should close this issue — CT has proven difficult to use optionally and it’s a feature we can live without. @boundsj?

**Comment by boundsj** [comment]
I agree -- let's close this.

**Comment by 1ec5** [comment]
> It looks like the public CoreTelephony classes might be defined in header files (and as such are always present so the `NSClassFromString` check passes), but private, internal classes depend on symbols in CoreTelephony.framework and are therefore missing when it's not linked.

`NSClassFromString()` doesn’t care where a symbol is defined; it only matters whether a class has been loaded into the Objective-C runtime. There’s no such thing as a “false positive”. The stack trace indicates that Core Telephony is making an assumption about its environment, perhaps assuming that the framework’s initializer has already been called. (We have no idea what’s in the initializer.)
