### ISSUE TITLE
flyTo launches into geosynchronous orbit

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3296]
If I start out at zoom level _A_ and invoke `mbgl::Map::flyTo()` with a zoom level _B_, such that _B_ > _A_, the viewpoint ends up at zoom level _A_. Moreover, the trajectory isn’t capped at the minimum zoom level. So when flying from San Francisco at about z7 to Washington, D.C., at z18, the zoom level quickly goes into NaN territory:

```
8.864151
8.864048
8.864014
8.863978
8.863908
<snip>
7.761990
7.715285
7.634145
7.585074
7.440956
7.289616
7.224786
7.116410
7.056992
6.781923
6.344395
6.152671
5.933951
5.434996
1.683239
nan
nan
<snip>
nan
nan
1.752706
4.793166
6.483146
6.859785
7.262993
7.402360
7.712066
7.781944
7.873764
7.889215
7.942035
7.958733
8.016303
8.134719
8.194865
8.200802
8.254453
<snip>
8.867422
8.867423
8.867423
8.867423
8.867423
8.867423
8.867423
```

/cc @adam-mapbox

**Comment by lucaswoj** [comment]
![na](https://cloud.githubusercontent.com/assets/281306/11819306/ff785a4e-a313-11e5-8baf-2c976216c963.png)

**Comment by 1ec5** [comment]
As @adam-mapbox pointed out, we aren’t calculating quite the right zoom levels. After removing the zoom level clamp I added in #3301, I was able to fly from California to D.C., causing the zoom level to vary from 6.475008 to -8.283377 to 23.004506.

**Comment by 1ec5** [comment]
For my own reference, `flyTo()` was originally introduced in mapbox/mapbox-gl-js@da42a4a503dfaa21b6b717ccdcf6aaf71f3a3ab2 as an implementation of [van Wijk ‎2003](https://www.win.tue.nl/~vanwijk/zoompan.pdf#page=5) “optimal path” animations.
