### ISSUE TITLE
MGLMapCamera negative heading doesn't rotate correctly

### ISSUE THREAD

**Issue by cellininicholas** [mapbox/mapbox-gl-native#3299]
I'm animating from heading=0, and want my destination heading to be in the range -180>heading>=180 so there is never more than 180deg of rotation from 0.

But when I set the map camera when the camDir<0
MGLMapCamera *camera = [MGLMapCamera cameraLookingAtCenterCoordinate:camCoord fromDistance:camDist pitch:0 heading:camDir];

The map doesn't rotate in it's animation.

**Comment by cellininicholas** [comment]
MGLMapView.mm
```
- (void)_setCamera:(MGLMapCamera *)camera withDuration:(NSTimeInterval)duration animationTimingFunction:(nullable CAMediaTimingFunction *)function completionHandler:(nullable void (^)(void))completion useFly:(BOOL)fly {
// ...
double angle = -1;
    if (camera.heading >= 0)
    {
        angle = MGLRadiansFromDegrees(-camera.heading);
    }
//...
}
```

**Comment by 1ec5** [comment]
`MGLMapCamera.heading` is of type [`CLLocationDirection`](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CoreLocationDataTypesRef/#//apple_ref/c/tdef/CLLocationDirection). According to the documentation, a negative `CLLocationDirection` indicates an invalid direction. You should specify a value between 0° and 180°; MGLMapView will take the shortest path around the circle.
