### ISSUE TITLE
Error building after installing via CocoaPods — Include of non-modular header inside framework module 'Mapbox'

### ISSUE THREAD

**Issue by lucacorti** [mapbox/mapbox-gl-native#3300]
Hello,

I am not able to use the Cocoapods pckages framework with Xcode 7.2 and Swift. When building the application I get:

```Pods/Mapbox-iOS-SDK/Mapbox.framework/Headers/Mapbox.h:16:9: Include of non-modular header inside framework module 'Mapbox'```

![screen shot 2015-12-15 at 04 24 46](https://cloud.githubusercontent.com/assets/1076999/11801198/f6068510-a2e3-11e5-82d7-4582b8a12070.png)
![screen shot 2015-12-15 at 04 25 07](https://cloud.githubusercontent.com/assets/1076999/11801197/f6062e58-a2e3-11e5-9fa9-9a7ccff85f29.png)

**Comment by 1ec5** [comment]
Pretty sure this is CocoaPods/CocoaPods#4420, which is fixed in CocoaPods master. It’s tripping up because we now include a module map that’s redundant with the one CocoaPods creates for us.

/cc @incanus

**Comment by lucacorti** [comment]
Is there any workaround to make it work right now? The Pod is unusable in its current state and the Cocoapods fix is not released yet.

**Comment by Sh1mor1nka** [comment]
I also have issue with mapbox imports, fix it by ```#import <Mapbox/Mapbox.h>```

**Comment by lucacorti** [comment]
I tried importing the header in the the Objective-C bridging header. Stile gettoni the dame error though.

**Comment by 1ec5** [comment]
I haven’t tried it out yet, but as several commenters in CocoaPods/CocoaPods#4420 point out, you should be able to use something like this to “fix” the Mapbox iOS SDK headers for now:

```ruby
post_install do |installer|
    `find Pods -regex 'Pods/Mapbox-iOS-SDK/.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)Mapbox\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end
```

/cc @friedbunny

**Comment by friedbunny** [comment]
That `post_install` bit does appear to work, got around the `Include of non-modular header inside framework module 'Mapbox'` build error.

**Comment by 1ec5** [comment]
Fixed in #3183. If you still run into this error, make sure your bridging header isn’t importing an individual header but rather the umbrella header (`Mapbox/Mapbox.h`) or module (`Mapbox`).

**Comment by 1ec5** [comment]
Actually, I still get this error in at least one CocoaPods project written in Swift after upgrading to [3.1.0-pre.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.1.0-pre.1) (which is out now, by the way!). The workaround is to add `#import <Mapbox/Mapbox.h>` to a bridging header. You may need to clear your module cache before rebuilding.

**Comment by 1ec5** [comment]
[v3.1.0-pre.2](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.1.0-pre.2) ([podspec](https://raw.githubusercontent.com/mapbox/mapbox-gl-native/ios-v3.1.0-pre.2/ios/Mapbox-iOS-SDK.podspec)) is out with the fix for this issue. Please let us know if you still see the errors. Thanks!
