### ISSUE TITLE
Using own tiles

### ISSUE THREAD

**Issue by Buminta** [mapbox/mapbox-gl-native#3302]
Hi pro.
I'm used Mapbox SDK for my projects.
And now, Your have Tiles vector for SDK. I'm very happy.
However i hope using own tiles for display map.
I had api for tiles with response JSON.
I can using it? Can u help me? Thank so much.

**Comment by jfirebaugh** [comment]
Yes, see [this example](https://www.mapbox.com/ios-sdk/examples/raster-styles/).
