### ISSUE TITLE
[Android] Custom Markers Clickable Region

### ISSUE THREAD

**Issue by mikeringrose** [mapbox/mapbox-gl-native#3306]
I have created custom markers from a Bitmap and the entire marker is not clickable. Only the bottom portion of the marker is able to be clicked.

**Comment by tobrun** [comment]
@mikeringrose 
thank you for reaching out and reporting this problem.
 - which version of the lib are you using? 
 - could you add the bitmap to this issue? 
 - or the dimensions of the bitmap?

**Comment by tobrun** [comment]
Linking https://github.com/mapbox/mapbox-gl-native/issues/1504 as it could be source of the problem, 
will wait for details on bitmap to perform some tests

**Comment by mudar** [comment]
@mikeringrose I'm guessing you're using a marker with the top half being transparent?
If that's the case, would feature #2916 (once implemented) fix the issue?

**Comment by tobrun** [comment]
I have been documenting this problem here https://github.com/mapbox/mapbox-gl-native/issues/3643.
Closing this in favour of that one.
