### ISSUE TITLE
Should there be a default BoundingBox constructor?

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#3308]
https://github.com/mapbox/mapbox-gl-native/blob/ba3608ba3ed65f71c2c9909c2b3201652a130100/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/BoundingBox.java#L60-L66

Right now if you create a `new BoundingBox()`, it'll give you an invalid bbox around null island. Is this ever useful? Can we remove the no-argument constructor?

**Comment by tobrun** [comment]
@tmcw 
I also see no added value for having this, 
If @bleege and @zugaldia do not object to this, 
I will remove it in next few days.

**Comment by bleege** [comment]
Usually it's good practice in Java to include a default Constructor, but in this case since there are no setter methods for the final private fields it's essentially useless.

Let's knock it out.

**Comment by tobrun** [comment]
> Let's knock it out.

:facepunch: :boom:
