### ISSUE TITLE
"LatLngZoom" & "Coordinate": do they mean the same thing?

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#3309]
Our external-facing API has `Map.setCenterCoordinate(LatLngZoom)` that dispatches to `Map.setLatLng` and `Map.setLatLngZoom`. We don't have a class called 'Coordinate' anywhere.

Should LatLng be derived from a Coordinate class? Should it be renamed Coordinate? The two names seem to correspond to the same thing.

**Comment by tobrun** [comment]
#### Center Coordinate
I'm not really sure where the naming of `setCenterCoordinate` comes from. Using `setLatLng` would make more sense over `setCenterCoordinate`. For parity with iOS and Google maps I'm suggesting to keep `LatLng` and remove `Coordinate` references. 

#### Google Maps
I'm seeing that Google Maps SDK is using a [Camera](https://developers.google.com/android/reference/com/google/android/gms/maps/model/CameraPosition) object for this.

@bleege 
 - Is this something that will be changed with your Camera implementation?
 - What are your thoughts on this subject?

##### Side note
I want to add to this discussion we are sometimes calling a LatLng instance `point`:

```java
mMapView.setOnMapLongClickListener(new MapView.OnMapLongClickListener() {
         @Override
         public void onMapLongClick(@NonNull LatLng point) {
             // awesome code here
         }
});
```
This is something that needs to be changed as well.

@tmcw thank you for this valuable feedback, always good to have some extra :eyes:

**Comment by bleege** [comment]
> I'm not really sure where the naming of `setCenterCoordinate` comes from.

I did some sleuthing and found [that it comes from 5-Nov-**2014**](https://github.com/mapbox/mapbox-gl-native/commit/bff63d44c62cea75e2e5162e7c46cd1fbf8ef4c1#diff-f0d580918def92232c8bf9df0e9630eaR199).... aka "the first Android PR".  It's odd as usually there's been a one to one mapping between `MapView.java` and `NativeMapView.java` for Core GL methods (which will be changing as we continue to mirror the Google Maps API).  Perhaps this was just a more "human friendly" name?

Regardless, let's move away from this now.  With the [Mapbox Camera API now in](https://github.com/mapbox/mapbox-gl-native/issues/3358), we can mirror [Google's approach by using `moveCamera()`](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html#moveCamera%28com.google.android.gms.maps.CameraUpdate%29).  The only thing that will have to be managed is the removal of `setCenterCoordinate()` from `MapView` as `setLanLng()` and `setLatLngZoom()` are both only in `NativeMapView` which is not accessible.  This is not a big deal at all, but **it will cause a SemVer major version to be needed.**

**Comment by tobrun** [comment]
This will be resolved if #3145 lands

**Comment by bleege** [comment]
@tobrun Since #3145 is a [bit of a bigger lift](https://github.com/mapbox/mapbox-gl-native/issues/3145#issuecomment-169974498) that may or may not be ready by the time we're ready to release the next PROD version of the SDK let's knock this issue out first as getting things named consistently is important. Cool?

**Comment by tobrun** [comment]
Agreed, will pick this up now
