### ISSUE TITLE
First sprite is ignored when creating multiple marker icon sprites with SpriteFactory

### ISSUE THREAD

**Issue by tnightingale** [mapbox/mapbox-gl-native#3317]
Platform: Nexus 5, Android 6.0.1
Versions: Master (as of today) and 2.3.0

When creating markers with custom icons, the first sprite created via the SpriteFactory's fromDrawable() or fromAsset() methods doesn't render. Instead the default icon is displayed. The following warning is logged:

    com.mapbox.mapboxsdk.testapp W/mbgl: {Map}[Sprite]: Can't change sprite dimensions for 'com.mapbox.sprites.sprite_1'

Source: [/src/mbgl/sprite/sprite_store.cpp#L131](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/sprite/sprite_store.cpp#L131).

This can be observed in the ['custom_marker' branch of my fork](https://github.com/mapbox/mapbox-gl-native/compare/master...tnightingale:custom_marker#diff-06c1a91dba5d82bd0dd547e376ff043cR44) which adds an example map called 'Custom Marker' to the test application demonstrating this bug.

**Comment by tnightingale** [comment]
I think this is a duplicate of #3239.

**Comment by tnightingale** [comment]
Another observation: If the first marker you add to the map has a custom icon, any subsequent markers added without an icon set will use the same custom icon and **not** the default 'red marker' icon.

Can be seen if you comment out [these lines](https://github.com/tnightingale/mapbox-gl-native/blob/cf20421e67215a751bdc0d33da7ec997fd74c9b0/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/CustomMarkerActivity.java#L49-L51) and run.

**Comment by tnightingale** [comment]
Looks like this problem is the result of using two different SpriteFactory instances.

If [MapView.getSpriteFactory()](https://github.com/mapbox/mapbox-gl-native/blob/8a208133db3e8b6530373f1b5974548bbd0db46d/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L1835-L1840) is used instead of creating a new one (the approach used in the [custom markers example code](https://www.mapbox.com/android-sdk/custom-marker-icon/)) then markers are rendered as expected.

**Comment by esisa** [comment]
Thank you @tnightingale! Changing to getSpriteFactory() fixed this for me. This issue was driving me crazy :-)

The Android examples should be updated.

**Comment by tobrun** [comment]
@tnightingale 
Thank you for investigating this for us!
I will look into this the following days and see if how we can optimise both the code and documentation.

**Comment by tobrun** [comment]
> Looks like this problem is the result of using two different SpriteFactory instances.

I'm suggesting refactoring `SpriteFactory` to be a singleton instance. This will also introduce the requirement of making SpriteFactory context safe -> we need to replace the `MapView` argument with a `Context` and calling `context.getApplicationContext()` in the `getInstance(context)`.

When this is done, we will also need to update our documentation

cc @bleege @zugaldia

**Comment by tobrun** [comment]
Will add an example to the test app as well

**Comment by tobrun** [comment]
I'm adjusting the current feature activities in the sample app instead of creating a new one.
`InfoWindowActivity` will support both the Default marker versus a Maki icon.

**Comment by zugaldia** [comment]
Awesome. Do we need to update any of the samples in
https://www.mapbox.com/android-sdk/examples/ too?

**Comment by tobrun** [comment]
@danswick 

Can you update the `onCreate` method in the [examples](https://www.mapbox.com/android-sdk/custom-marker-icon/) to:

Replace:
```
SpriteFactory spriteFactory = new SpriteFactory(mapView);
```
With:
```
SpriteFactory spriteFactory = mapView.getSpriteFactory();
```

This code is valid for both SNAPSHOT as stable versions

**Comment by danswick** [comment]
awesome, @tobrun. I think this change will help alleviate a lot of confusion over adding marker icons. I'll update the docs later today. :+1:
