### ISSUE TITLE
How to set map boundaries in android ?

### ISSUE THREAD

**Issue by Mizuki123** [mapbox/mapbox-gl-native#3321]
Hi everyone,

I'm working on an android application that display a portion of world map (including part of United Kingdom, part of France and part of Span) and I want to restrict the moving on the map to only this portion of map.

In my android code, I used setVisibleCoordinateBounds to define Porto as south-west bounds and Utrecht to north-east bounds but I can still moving out of this bounds.

In addition, I set those bounds in my stylesheet using the "bounds" property of the source node but that does not working. Seems the default boundaries are set to my map.

So Is it possible to set the bound of my mapView and how to do that ?

I notice there is a way to do that in javascrip using the maxBounds : https://www.mapbox.com/mapbox.js/example/v1.0.0/maxbounds/

Is there a equivalent of this in Android ?

**Comment by tobrun** [comment]
@Mizuki123 
Sorry for getting back to you this late. 
Currently this is not supported yet.
There is a feature request for this in issue #3602.

**Comment by cyrusesolz** [comment]
Hi , i am also facing this problem . Is there any alternative way to limit the viewport in android
?

**Comment by bodhidipta** [comment]
Hi, can you please give us an alternative for it?

**Comment by tobrun** [comment]
Listen to OnCameraChangeListener events. Detect if the camera position is contained within this LatLngBounds and move camera if not.

**Comment by bodhidipta** [comment]
Thank you .

**Comment by sddamico** [comment]
Having implemented something to do this recently, the callbacks from onCameraChange do not align with the drawing frames and this can lead to "bouncing" on the edge of the bounded area. I recommend using a Runnable that performs the check on each choreographer frame by using postOnAnimation on the MapView itself
