### ISSUE TITLE
Android is inconsistent about “zoom” versus “zoomLevel”

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3327]
`MapView` has [`getZoomLevel()`](https://github.com/mapbox/mapbox-gl-native/blob/13d5b18ebaeb330f05c4abfc04e0247222e038ba/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L1293), while `NativeMapView` and `LatLngZoom` both have [`getZoom()`](https://github.com/mapbox/mapbox-gl-native/blob/13d5b18ebaeb330f05c4abfc04e0247222e038ba/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/NativeMapView.java#L304). The Android bindings should standardize on one term to avoid confusion. The iOS SDK and OS X port have standardized on “zoom level”, to avoid situations where “zoom” is used as a noun in places where verbs can also be used.

/cc @bleege

**Comment by bleege** [comment]
Sounds good @1ec5.  Let's tee this up for the next version of the Android SDK.

/cc @zugaldia @tobrun

**Comment by tobrun** [comment]
This will be resolved if #3145 lands

**Comment by bleege** [comment]
@tobrun Since #3145 is a [bit of a bigger lift](https://github.com/mapbox/mapbox-gl-native/issues/3145#issuecomment-169974498) that may or may not be ready by the time we're ready to release the next PROD version of the SDK let's knock this issue out first as getting things named consistently is important.  Cool?

**Comment by tobrun** [comment]
@bleege agreed, taking this up now

**Comment by tobrun** [comment]
Added new methods:
 - void setZoom(zoomLevel)
 - void setZoom(zoomLevel, duration)
 - float getZoom

Deprecated old methods:
 - void setZoomLevel(zoomLevel)
 - void setZoomLevel(zoomLevel, duration)
 - float getZoom()

Added new attribute:
 - zoom (old one is zoom_level)

I replaced all occurrences in test app with new methods,
I replaced all occurrences in MapView class except the one loading the old attribute.
