### ISSUE TITLE
Map Thread Crashing Repeatedly - Fatal signal 6 (SIGABRT)

### ISSUE THREAD

**Issue by TangoJLabs** [mapbox/mapbox-gl-native#3332]
I have tried adding a mapview to both an activity and a fragment and I am consistently getting the following error:

    A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 23944 (Map Thread)

When the activity reloads (automatically), I get these error messages:

    E/GMPM: getGoogleAppId failed with status: 10
    E/GMPM: Uploading is not possible. App measurement disabled

I am not sure if those subsequent errors are related - all solutions I can find focus on android wearables or a google API, both of which I am not using.

The activity crashes the majority of the time (70-80%?), although it remains stable occasionally, so it seems that if it is overloading a thread, it does not do this every time.

**Comment by bleege** [comment]
> A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 23944 (Map Thread)

Can you share the code that's being used / causing this issue?  Are the lifecylce methods being overridden as [shown in the example](https://www.mapbox.com/android-sdk/examples/)?

> E/GMPM: getGoogleAppId failed with status: 10
E/GMPM: Uploading is not possible. App measurement disabled

This isn't related to the Mapbox Android SDK, as it doesn't upload anything nor does it have any connection with Google Play Services.

**Comment by TangoJLabs** [comment]
I'm sorry for the delay.  Because of the response delay I had actually moved on to integrating Google Maps with my app due to this issue, but I would prefer to stay with MapBox - I prefer your map style options for Android.

Understood on the second two errors - I just wanted to make sure that I wasn't missing something that MapBox was doing in the background.

I did override all of those lifecycle methods, but looking back at my old code, I had two maps in the activity, one as the main fullscreen map, and the other as a mini-map showing a zoomed out view.  I did include the mini-map in the lifecycle methods except for the "onSaveInstanceState" method.  However, even after adding the second map to that method, I am still having this issue.  Here is the relevant code:

MapActivity.java:
```
private MapView mv, miniMap;
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_map);
        mv = (MapView) findViewById(R.id.map_view);
        mv.setStyleUrl(Style.MAPBOX_STREETS);
        mv.setCenterCoordinate(new LatLng(38.889, -77.019));
        mv.setRotateEnabled(true);
        mv.setScrollEnabled(true);
        mv.setCompassEnabled(true);
        mv.setLogoVisibility(View.VISIBLE);
        mv.setAttributionVisibility(View.VISIBLE);
        mv.setZoomLevel(16);
        mv.onCreate(savedInstanceState);

        miniMap = (MapView) this.findViewById(R.id.mini_map);
        miniMap.setStyleUrl(Style.MAPBOX_STREETS);
        miniMap.setCenterCoordinate(new LatLng(38.889, -77.019));
        miniMap.setRotateEnabled(false);
        miniMap.setScrollEnabled(false);
        miniMap.setCompassEnabled(false);
        miniMap.setLogoVisibility(View.GONE);
        miniMap.setZoomLevel(6);
        miniMap.onCreate(savedInstanceState);

@Override
    protected void onStart() {
        super.onStart();
        mv.onStart();
        miniMap.onStart();
    }
    @Override
    protected void onStop() {
        super.onStop();
        mv.onStop();
        miniMap.onStop();
    }
    @Override
    protected void onDestroy() {
        super.onDestroy();
        mv.onDestroy();
        miniMap.onDestroy();
    }

@Override
    protected void onResume() {
        super.onResume();
        mv.onResume();
        miniMap.onResume();
        }
    }

@Override
    protected void onPause() {
        super.onPause();
        mv.onPause();
        miniMap.onPause();
        }
    }

@Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mv.onSaveInstanceState(outState);
        miniMap.onSaveInstanceState(outState);
    }
```

activity_map.xml
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:mapbox="http://schemas.android.com/apk/res-auto"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent" >

    <com.mapbox.mapboxsdk.views.MapView
        android:id="@+id/map_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        mapbox:access_token="@string/access_token"/>

    <RelativeLayout
        android:layout_width="104dp"
        android:layout_height="104dp"
        android:background="#FFFFFF"
        android:layout_alignParentTop="true"
        android:layout_alignParentLeft="true"
        android:layout_marginLeft="5dp"
        android:layout_marginTop="5dp"
        android:id="@+id/relative_layout_mini_map">

        <com.mapbox.mapboxsdk.views.MapView
            android:layout_width="100dp"
            android:layout_height="100dp"
            android:id="@+id/mini_map"
            android:layout_centerVertical="true"
            android:layout_centerHorizontal="true"
            mapbox:access_token="@string/access_token"/>
    </RelativeLayout>
</RelativeLayout>
```

I just re-ran the app and got this error again:
```...com.example.exampleapp A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 2526 (Map Thread)```

However, when I re-open the app, sometimes the map works, but when I completely stop the app and start it again, it crashes again.  The map crashes the majority of the time.

**Comment by bleege** [comment]
Thanks for the code and an overview of what the app was trying to accomplish.  I'd tried reproducing the issue locally but was unable to.  The project setup, code, and screenshot is [available on GitHub here](https://github.com/bleege/TwoMaps).

The next step is to learn more about the SDK version, device, and version of Android that you're using.  For comparison, the project that I built is using Mapbox Android 3.0.0 and I tested it on a Nexus 5X that's running Android 6.0.1.

> I'm sorry for the delay. Because of the response delay I had actually moved on to integrating Google Maps with my app due to this issue, but I would prefer to stay with MapBox - I prefer your map style options for Android.

For faster turnaround on questions, please always feel free to contact Mapbox Help team first via:

https://www.mapbox.com/contact/

**Comment by TangoJLabs** [comment]
Thanks bleege; I have contacted the MapBox Help team before and received excellent service.  I wasn't sure when to use them vs. these issue threads.

I am currently running Android 5.1 on a Moto X (2nd Gen) and I was using Mapbox 2.2.0.  I tried Mapbox 3.0.0, but it did not build correctly - it said it could not find the Sprite classes.  I am now using Mapbox 2.3.0 (the one shown on the [Mapbox SDK tutorial](https://www.mapbox.com/help/first-steps-android-sdk/)), and I am not able to produce the same issue so far.

I had stripped down the code to run this test again, so I am going to change a few things and test it some more to see if I can produce that error again, but it seems to be working so far.

**Comment by TangoJLabs** [comment]
bleege, I have tested the map on my usual app and I cannot reproduce the error.  It seems to have been limited to Mapbox 2.2.0.  Thanks for your help!

**Comment by tobrun** [comment]
@TangoJLabs Thank you for reporting that back, will close this issue.

**Comment by bleege** [comment]
@TangoJLabs Glad to hear that things are working for you now!

> I have contacted the MapBox Help team before and received excellent service. I wasn't sure when to use them vs. these issue threads.

Generally speaking, if your project is on any sort of deadline the best bet is usually to [contact the Mapbox Help Team first](https://www.mapbox.com/contact/).  They're equipped to respond in a much more reliable (and short) time frame.

>  I tried Mapbox 3.0.0, but it did not build correctly - it said it could not find the Sprite classes.

Yep, Sprites got renamed to Icons in `3.0.0`.  The details and reasoning behind this is in #3304 if you're interested.

**Comment by TangoJLabs** [comment]
Thanks Brad, I appreciate the info on the Sprites.  I'll take a look at the Icons and the new documentation.
