### ISSUE TITLE
[Android] MapFragment null pointer exception in onCreateView

### ISSUE THREAD

**Issue by oguzbabaoglu** [mapbox/mapbox-gl-native#3333]
Code below fails with a null pointer exception in some use cases with the `<fragment>` tag.

```java
mMap.setAccessToken(ApiAccess.getToken(container.getContext()));
```

This is because of `container` being null in these cases.

It is marked as **`@Nullable`**, and docs also state _"If **non-null**, this is the parent view that the fragment's UI should be attached to."_
See: http://developer.android.com/reference/android/app/Fragment.html

`inflater` can be used instead, as it is guaranteed to be Non-Null and provides the same context.

**Comment by tobrun** [comment]
Merged with https://github.com/mapbox/mapbox-gl-native/commit/9e90934438e18f8512c9d7775bb8ed3389e46627
