### ISSUE TITLE
When I change the map style in iOS，the annotation was disappeared.

### ISSUE THREAD

**Issue by Kelanlee** [mapbox/mapbox-gl-native#3345]
I add a normal MGLPointAnnotation into the Mapview,it works.But when I try to change the style, the annotation is disappeared. I log the mapview.annotations.count, it was 1, it did not change. 
But I saw a log 
"2015-12-18 18:03:59.685 MapboxDemo[2025:702201] [INFO] {Worker}[Sprite]: Can't find sprite named 'com.mapbox.sprites.default_marker' "

**Comment by 1ec5** [comment]
Duplicate for #1488. Fixed in #3049, which will be in the next release.
