### ISSUE TITLE
Isometric view

### ISSUE THREAD

**Issue by dagatsoin** [mapbox/mapbox-gl-native#3347]
Is it possible to set the GL camera perspective to isometric?

**Comment by jfirebaugh** [comment]
No -- with the camera tilted, you get a perspective projection. We don't currently have plans to add an isometric option.

**Comment by mb12** [comment]
@dagatsoin  You can add MGLMapView to a container UIView and apply any transformations to it (incl. perspective or isometric etc).  It would be nice if you could explain why you need it (screenshots etc.) and if there are any other  mapping SDKs that provide it.
