### ISSUE TITLE
[iOS] MapBox doesn't release memory

### ISSUE THREAD

**Issue by Sh1mor1nka** [mapbox/mapbox-gl-native#3353]
Each time i present ViewController with mapBox my memory increases by ~20 mb, i'm sure it's mapbox because if i remove them i don't have such memory behaviour. 
I try to add mapBox as view in my storyboard and connect it by weak reference to my viewController, also i try add mapbox in my view programmatically, but bought times i have the same memory increasing...

On my map i only show pin annotations with different images, but even if i show empty map, it is still don't releasing.

What i'm ding wrong? Thank you.

**Comment by jfirebaugh** [comment]
This is likely #3130.
