### ISSUE TITLE
Refine Camera API

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#3358]
The fundamentals of the Camera API were built in #3244 , now the developer API can be refined to be more consistent with the Google Maps API.  This means the following:

**Make Core GL Methods Private**

The Core GL animation methods are [`jumpTo()`](https://github.com/mapbox/mapbox-gl-native/blob/ec5afdd8b78224593bc9f29ef2c6e7c6cde60579/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L2414), [`easeTo()`](https://github.com/mapbox/mapbox-gl-native/blob/ec5afdd8b78224593bc9f29ef2c6e7c6cde60579/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L2429), and [`flyTo()`](https://github.com/mapbox/mapbox-gl-native/blob/ec5afdd8b78224593bc9f29ef2c6e7c6cde60579/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L2442).  They are currently `public` methods which means developers can access them directly.  They need to be made private and only accessible via the Google Maps like API wrapper methods ( `animateCamera()`, `moveCamera()`, and `easeCamera()` ). 

**Add moveCamera() Method**

The Google Maps API has a [`moveCamera()`](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html#moveCamera%28com.google.android.gms.maps.CameraUpdate%29) method which should be the wrapper method for Core GL's `jumpTo()`.

**Create easeCamera() Method**

The Google Maps API does not have a method for "easing the camera", only for animation (aka `animateCamera()`).  Create a new `easeCamera()` method to wrap Core GL's `easeTo()` method.  This will expose Mapbox's additional functionality, while sticking with the familiar naming convention.

**Update TestApp's CameraActivity Buttons**

The three buttons in the CameraActivity currently call the three different iterations of the `animateCamera()` method.  Update them to directly invoke: `moveCamera()`, `easeCamera()`, and `animateCamera()`.

**Comment by 1ec5** [comment]
> The Google Maps API does not have a method for "easing the camera", only for animation (aka `animateCamera()`).

So Google’s [`animateCamera()`](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap#animateCamera%28com.google.android.gms.maps.CameraUpdate%29) produces a zoom-out-pan-zoom-in motion like `flyTo()` does?

**Comment by bleege** [comment]
> So if you call Google’s animateCamera() with a CameraUpdate that changes the LatLng, you get a zoom-out-pan-zoom-in motion like with flyTo()?

Yep.  I built an [example app using the Google Maps API](https://github.com/bleege/GoogleMapCamera) which on load centers on a Marker in Sydney, Australia.  I added an "Animate" button which calls the [exact 1 argument `animateCamera()` method](https://github.com/bleege/GoogleMapCamera/blob/f0334f331d7fc2bedc8ee4618f44d939b3e595cd/app/src/main/java/com/bradleege/googlemapcamera/MapsActivity.java#L38).  The result is that it does a `flyTo()` animation from Sydney to new location in Green Bay, Wisconsin.

**Comment by bleege** [comment]
My first iteration made the Core GL camera methods private, added `moveCamera()`, and updated the TestApp's CameraActivity to only use `moveCamera()` and `animateCamera()`.  As part of this I also [changed the `animateCamera()` zero second duration choice to use `easeTo()` instead of `jumpTo()`](https://github.com/mapbox/mapbox-gl-native/commit/8f532eeefa72ec92bbb61d6f3a12c78e2bd181cd#diff-9a56c33fed48a96e48cfe8d8f0559511R1569).  However when testing it, it still behaved as an immediate move so it looks like a standalone `easeCamera()` method is going to be needed as originally thought.

**Comment by bleege** [comment]
I created the following screen recording videos to help illustrate the differences between what the Camera API methods do:

* [moveCamera()](https://vimeo.com/149564311)
* [easeCamera()](https://vimeo.com/149564419)
* [animateCamera()](https://vimeo.com/149564460)

**Comment by bleege** [comment]
I just rebased and merged these into `release-android-v2.4.0`.  I'll produce a new `2.4.0-SNAPSHOT` now so that others can test the API out.

**Comment by bleege** [comment]
Just started the SNAPSHOT build process on Bitrise.  Should be on Maven Central's SNAPSHOT server in 30 minutes.

/cc @zugaldia @1ec5 @tobrun
