### ISSUE TITLE
Vector vs Raster tiles required space

### ISSUE THREAD

**Issue by jzarzuela** [mapbox/mapbox-gl-native#3363]
Hi,
I read that vector tiles would be much more space efficient than raster tiles. But comparing what your HTML or iOS demo apps are downloading it doesn't look like so.

For example:

http://a.tiles.mapbox.com/v4/mapbox.mapbox-streets-v6/14/4823/6160.vector.pbf?access_token={token}

https://api.mapbox.com/v4/mapbox.streets/14/4823/6160.png?access_token={token}

Results in downloading 16.725 bytes PNG versus 35.206 bytes PBF file.

How is it possible?

**Comment by friedbunny** [comment]
Was in the process of answering this and found that @flippmoke had already answered it (in much better detail than I ever could): https://github.com/mapbox/vector-tile-spec/issues/53

**Comment by 1ec5** [comment]
Regarding one of @flippmoke’s points, Mapbox GL JS supports inspecting feature attributes in the layer via the [`featuresAt()`](https://www.mapbox.com/mapbox-gl-js/example/featuresat/) and [`featuresIn()`](https://www.mapbox.com/mapbox-gl-js/api/#Map.featuresIn) APIs. We’re working to port that to the iOS SDK in #3172.
