### ISSUE TITLE
how can i show my location button like google map

### ISSUE THREAD

**Issue by ragummrsa2930** [mapbox/mapbox-gl-native#3365]
in google map if i open there is a function to set my location button enable and disable "gmaps.getUiSettings().setMyLocationButtonEnabled(false);" same way is there any function in mapbox sdk to enable or disable? or we need to write our own logic?

**Comment by cammace** [comment]
I've implemented something similar to what I believe you are trying to accomplish. I don't think there's a "setMyLocationButtonEnabled" method so the way I did it is I just create a Floating Action Button and on its click I just get the users location. From that I move the camera to the new position. 

A couple things to note are that if you're using android 6.0 (API 23) or higher you need to [get location permission at runtime](https://developer.android.com/training/permissions/requesting.html) else you can just put these permissions in the manifest:

```xml
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
```

When you create your MapView within the onCreate method also include:

```java
mapView.setMyLocationEnabled(true); 
```

From the Docs "While setMyLocationEnabled enabled, the my-location layer continuously draws an indication of a user's current location and bearing." After that I add the FAB view in xml and create the method in java and just call it within the onCreate method.

```xml
<!-- Implementation of find my location button -->
    <android.support.design.widget.FloatingActionButton
        android:id="@+id/myLocationButton"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|right"
        android:layout_marginBottom="20dp"
        android:layout_marginRight="20dp"
        android:src="@android:drawable/ic_menu_mylocation"
        app:borderWidth="0dp"
        app:elevation="6dp"
        app:pressedTranslationZ="12dp"
        app:fabSize="normal" />
```

```java
private void userLocationFAB(){
        FloatingActionButton FAB = (FloatingActionButton) findViewById(R.id.myLocationButton);
        FAB.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                if(mapView.getMyLocation() != null) { // Check to ensure coordinates aren't null, probably a better way of doing this...
                    mapView.setCenterCoordinate(new LatLngZoom(mapView.getMyLocation().getLatitude(), mapView.getMyLocation().getLongitude(), 20), true);
                }
            }
        });
    }
```

The end result gives you something like this:

<img src="https://cloud.githubusercontent.com/assets/5652865/11941683/0254335e-a7f7-11e5-9432-1373700bef28.png" width="350">

Now there's probably a better way to move the camera besides "setCenterCoordinate" but I'm still transitioning from the old Android SDK (where I simply used goToUserLocation). Anyones welcome to correct me on this.

**Comment by bleege** [comment]
@ragummrsa2930 User location is enabled / disabled via the [`MapView.setMyLocationEnabled(boolean enabled)`](https://github.com/mapbox/mapbox-gl-native/blob/4c90f63c6dc07080c279c26f1ff7da78f1aa1b2f/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L3780-L3795) method.  There is no Mapbox specific UI component though for turning it on / off (we don't want to force a UI on apps).  That said we have an [example in the TestApp](https://github.com/mapbox/mapbox-gl-native/blob/4c90f63c6dc07080c279c26f1ff7da78f1aa1b2f/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MainActivity.java#L184-L191) using the FloatingActionButton similar to @cammace's example.

**Comment by ragummrsa2930** [comment]
Hi Brad Leege,

I have one problem while using mapbox sdk. getting following error

Caused by: com.mapbox.mapboxsdk.exceptions.InvalidAccessTokenException:
Using MapView requires setting a valid access token. See the INSTALL.md

i will explain you this error step by steps.

1) it happens in android 6.0 Marshmallow (23)
2) open the app with map view its working fine.
3) go to app setting and click app permission
4) turn off any permission and open app its crashing getting the above
crash report.
5)  again open app it will work fine..


Thanks,
M M Ragupathy

**Comment by ragummrsa2930** [comment]
Problem solved, after adding onSaveInstanceState method. Anyway thanks.

**Comment by bleege** [comment]
@ragummrsa2930 Glad to hear that things are working.  :+1: 

Yep, the lifecycle methods are _critically important_ to implement.  We have a full list showing which ones and how to set them up in the Mapbox Examples documentation for future reference.

https://www.mapbox.com/android-sdk/examples/

**Comment by ragummrsa2930** [comment]
Hi Brad Leege,

hope you are doing good.

im getting following crash some times


   1. java.lang.NullPointerException: Attempt to invoke virtual method
   'void com.mapbox.mapboxsdk.views.NativeMapView.cancelTransitions()' on a
   null object reference
   2. at com.mapbox.mapboxsdk.views.MapView.zoom(MapView.java:1373)
   3. at com.mapbox.mapboxsdk.views.MapView.zoom(MapView.java:1368)
   4. at com.mapbox.mapboxsdk.views.MapView.access$3300(MapView.java:101)
   5. at
   com.mapbox.mapboxsdk.views.MapView$OnZoomListener.onZoom(MapView.java:2955)
   6. at
   android.widget.ZoomButtonsController$3.onClick(ZoomButtonsController.java:268)
   7. at android.view.View.callOnClick(View.java:5225)
   8. at android.widget.ZoomButton$1.run(ZoomButton.java:33)
   9. at android.os.Handler.handleCallback(Handler.java:739)
   10. at android.os.Handler.dispatchMessage(Handler.java:95)
   11. at android.os.Looper.loop(Looper.java:148)
   12. at android.app.ActivityThread.main(ActivityThread.java:5417)
   13. at java.lang.reflect.Method.invoke(Native Method)
   14. at
   com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
   15. at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by bleege** [comment]
@ragummrsa2930 This looks like another lifecycle issue.  I'd review the examples again and if there are still issues please open a new ticket with information about the version of the SDK in use, the device that your experiencing this issue on, and a code sample.  Thanks!

**Comment by Dharma237** [comment]
@bleege . I am using mapview in fragment.

I am assigning map view in different fragmet life cycles as below:


 ```
@Override
    public void onStart() {
        super.onStart();


        if (mapView != null) {
            mapView.onStart();
        }
    }
```
```
` @Override
    public void onResume() {
        super.onResume();

            if (mapView != null) {
                mapView.onResume();
            }
    }`
```


where to `destroy() `the` mapview`. Means in what life cycle is it in `onDetach() `method to destroy the `mapview`

**Comment by bleege** [comment]
@Dharma237 I'd recommend using the [`MapFragment`](https://github.com/mapbox/mapbox-gl-native/blob/fa210516834feada45d69e218f9c1dce2d2ee6f6/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapFragment.java) class that's part of the SDK instead of the MapView in the Fragment.  There's an [example in the TestApp](https://github.com/mapbox/mapbox-gl-native/blob/fa210516834feada45d69e218f9c1dce2d2ee6f6/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapFragmentActivity.java) that shows how to use it.

**Comment by Dharma237** [comment]
@bleege ,
I have already implemented the code by adding `mapview` in fragment in my project and its has many classes to change into `Fragment Activity`.

But when I using `mapview`, I am getting error like below

> Caused by: com.mapbox.mapboxsdk.exceptions.InvalidAccessTokenException:
Using MapView requires setting a valid access token. See the INSTALL.md.

Whenever this error comes, **my app gets closed and reopens from home screen**. Can you please help me out from this problem?

**Comment by bleege** [comment]
> I have already implemented the code by adding mapview in fragment in my project and its has many classes to change into Fragment Activity.

Yep, just to clarify but the recommendation was to use `MapFragment` from the SDK.  The name of the example in the TestApp is called `MapFragmentActivity`.

> Caused by: com.mapbox.mapboxsdk.exceptions.InvalidAccessTokenException:
Using MapView requires setting a valid access token. See the INSTALL.md.

> Whenever this error comes, **my app gets closed and reopens from home screen**. Can you please help me out from this problem?

The access token needs to be set in the MapView.  It can either be set programmatically via `MapView.setAccessToken()` of in the [Layout.xml as shown in the Examples](https://www.mapbox.com/android-sdk/examples/).

**Comment by Joeeeyy** [comment]
in xml file it keeps showing:

The following classes could not be instantiated:
- com.mapbox.mapboxsdk.maps.widgets.UserLocationView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE  Exception Details java.lang.UnsupportedOperationException: Unsupported Service: location   at com.android.layoutlib.bridge.android.BridgeContext.getSystemService(BridgeContext.java:570)   at com.mapzen.android.lost.internal.FusionEngine.<init>(FusionEngine.java:38)   at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.<init>(FusedLocationProviderApiImpl.java:27)   at com.mapzen.android.lost.internal.LostApiClientImpl.connect(LostApiClientImpl.java:21)   at com.mapbox.mapboxsdk.location.LocationServices.toggleGPS(LocationServices.java:81)   at com.mapbox.mapboxsdk.maps.widgets.UserLocationView.toggleGps(UserLocationView.java:378)   at com.mapbox.mapboxsdk.maps.widgets.UserLocationView.setEnabled(UserLocationView.java:251)   at com.mapbox.mapboxsdk.maps.widgets.UserLocationView.initialize(UserLocationView.java:119)   at com.mapbox.mapboxsdk.maps.widgets.UserLocationView.<init>(UserLocationView.java:109)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.inflate(LayoutInflater.java:492)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397)   at com.mapbox.mapboxsdk.maps.MapView.initialize   ... (MapView.java:179)   at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:158)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) Copy stack to clipboard  

How can I solve this and display my maps activity?

**Comment by moslem72** [comment]
hi
cannot find symbol method setMyLocationEnabled(boolean)
cannot find symbol method getMyLocation()
cannot find symbol class LatLngZoom
cannot find symbol method getMyLocation()
The error picture is below
![capture](https://user-images.githubusercontent.com/17636574/35429317-d26cc1ee-0288-11e8-986b-3ccf0f5bae03.PNG)

Thank you for help

**Comment by FarrukhDilawar007** [comment]
@moslem72 code this as true in MapReady method in the bottom of mainActivity:
Like mMapView.setMyLocationEnabled(true) etc

**Comment by Muhammad-Imtiaz** [comment]
> I've implemented something similar to what I believe you are trying to accomplish. I don't think there's a "setMyLocationButtonEnabled" method so the way I did it is I just create a Floating Action Button and on its click I just get the users location. From that I move the camera to the new position.
> 
> A couple things to note are that if you're using android 6.0 (API 23) or higher you need to [get location permission at runtime](https://developer.android.com/training/permissions/requesting.html) else you can just put these permissions in the manifest:
> 
> ```
> <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
> <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
> ```
> 
> When you create your MapView within the onCreate method also include:
> 
> ```java
> mapView.setMyLocationEnabled(true); 
> ```
> 
> From the Docs "While setMyLocationEnabled enabled, the my-location layer continuously draws an indication of a user's current location and bearing." After that I add the FAB view in xml and create the method in java and just call it within the onCreate method.
> 
> ```
> 
>     <android.support.design.widget.FloatingActionButton
>         android:id="@+id/myLocationButton"
>         android:layout_width="wrap_content"
>         android:layout_height="wrap_content"
>         android:layout_gravity="bottom|right"
>         android:layout_marginBottom="20dp"
>         android:layout_marginRight="20dp"
>         android:src="@android:drawable/ic_menu_mylocation"
>         app:borderWidth="0dp"
>         app:elevation="6dp"
>         app:pressedTranslationZ="12dp"
>         app:fabSize="normal" />
> ```
> 
> ```java
> private void userLocationFAB(){
>         FloatingActionButton FAB = (FloatingActionButton) findViewById(R.id.myLocationButton);
>         FAB.setOnClickListener(new View.OnClickListener() {
>             @Override
>             public void onClick(View v) {
> 
>                 if(mapView.getMyLocation() != null) { // Check to ensure coordinates aren't null, probably a better way of doing this...
>                     mapView.setCenterCoordinate(new LatLngZoom(mapView.getMyLocation().getLatitude(), mapView.getMyLocation().getLongitude(), 20), true);
>                 }
>             }
>         });
>     }
> ```
> 
> The end result gives you something like this:
> 
> <img alt="" width="350" src="https://cloud.githubusercontent.com/assets/5652865/11941683/0254335e-a7f7-11e5-9432-1373700bef28.png">
> 
> Now there's probably a better way to move the camera besides "setCenterCoordinate" but I'm still transitioning from the old Android SDK (where I simply used goToUserLocation). Anyones welcome to correct me on this.

Your description looks very nice, but mapView.setCenterCoordinate not working?

**Comment by arildojr** [comment]
Hello,

I need this also and I can't find a property in Mapbox to make this button show up to be able to get back to the current location centered.

Please fix this,

**Comment by tobrun** [comment]
Our SDK doesn't make any assumptions about the end user UI as floating action buttons.
You probably however can reuse some examples around this listed in https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location
