### ISSUE TITLE
[iOS] Zoom action changes center of map

### ISSUE THREAD

**Issue by alphatroya** [mapbox/mapbox-gl-native#3367]
When I use a pinch gesture (or double tap) to change zoom lever of the map, it's center shifts to the zone of touch. Is there any way to provide the only zoom without map moving?

**Comment by 1ec5** [comment]
Currently you’d have to zoom in programmatically, using the `-[MGLMapView setZoomLevel:animated:]` method. You can add UI that calls this method, but all the gesture recognizers for zooming in do consider the location of the gesture. What’s your intended use case for always zooming into the center?

**Comment by alphatroya** [comment]
Map view using for address choosing. I added overlay marker view at the center of the map, but client complaints about moving "cursor" after zoom. Well, it's very sad and I'll try to found programmatical solution

**Comment by 1ec5** [comment]
Another option may be for your MGLMapViewDelegate to respond to `-mapView:didSelectAnnotation:` by programmatically zooming into the overlay using `-[MGLMapView showAnnotations:animated:]`.
