### ISSUE TITLE
Can't access MGLStyle in Swift

### ISSUE THREAD

**Issue by sirljan** [mapbox/mapbox-gl-native#3369]
In your example https://www.mapbox.com/ios-sdk/examples/default-styles/ it should be possible to get default styles from MGLStyle class but it's not. All other classes work fine.
Following code emits error: "Use of unresolved identifier 'MGLStyle'"
mapView = MGLMapView(frame: view.bounds, styleURL: MGLStyle.lightStyleURL())

I'm using versions 3.0.1 and 2.1.2. Both has same issue.

When I jump to definition from "import Mapbox" I see there isn't MGLStyle included.
![screen shot 2015-12-21 at 19 54 36](https://cloud.githubusercontent.com/assets/419850/11938674/b5063c3e-a81c-11e5-87f2-4c7997e2caa2.png)

**Comment by 1ec5** [comment]
Weird, we definitely include MGLStyle.h in the [umbrella header](https://github.com/mapbox/mapbox-gl-native/blob/49bfdd662ff37ac77cd702c2cef92d2de8874be9/include/mbgl/ios/Mapbox.h#L15).

**Comment by 1ec5** [comment]
MGLStyle is new in 3.0.0, so it wouldn’t be in 2.1.2. The workaround, by the way, is to construct the URL manually, for instance: `NSURL(string: "mapbox://styles/mapbox/streets-v8")`. Here’s a selection of [style IDs](https://www.mapbox.com/developers/api/styles/#styleids) you can put in the URL.

**Comment by sirljan** [comment]
Thanks for advice :)

**Comment by 1ec5** [comment]
Hm, I can’t reproduce this issue in Xcode 7.2:

<img width="294" alt="Mapbox" src="https://cloud.githubusercontent.com/assets/1231218/11939497/5ca73d62-a7d7-11e5-8ab0-456c73679876.png">

What version of Xcode are you using? Does the issue persist after you clean the target? (There’s also a more aggressive option to clean the build folder; hold down Option and go to the Product menu.)

**Comment by sirljan** [comment]
I'm using xcode 7.2. Wow, that aggressive clean worked!
