### ISSUE TITLE
Merge Android 3.0.0 Release Branch Back To Master

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#3372]
Mapbox Android 3.0.0 was released in #3354 and now it's release branch needs to be merged back into `master` for development to continue.

The release branch was label `release-android-v2.4.0` as it was originally thought to be version `2.4.0`.

https://github.com/mapbox/mapbox-gl-native/commits/release-android-v2.4.0

/cc @mapbox/mobile

**Comment by bleege** [comment]
The only conflict while merging was to `src/mbgl/map/transform.cpp`, to which my solution was to accept the changes from `master` completely so there should be no change at all to it.  Other than that the merge was clean.

/cc @jfirebaugh @1ec5

**Comment by 1ec5** [comment]
Yep, that’s good because I merely cherry-picked some changes over to the release branch from master. :+1:
