### ISSUE TITLE
Support many markers with custom icon on Android

### ISSUE THREAD

**Issue by esisa** [mapbox/mapbox-gl-native#3379]
I am having a problem when I try to add 500 markers with a custom icon on Android. I am aware of #2552 and this seems to work fine as long as I do not use custom icons. I currently use version 3.0.0.

For creating the custom icon I do the following:
```java
IconFactory mIconFactory = IconFactory.getInstance(MapActivity.this);
Drawable drawable = ContextCompat.getDrawable(MapActivity.this, R.drawable.tmp_cat_badeplass_kart_1);
Icon icon = mIconFactory.fromDrawable(drawable);
MarkerOptions markerOptions  = new MarkerOptions().position(new LatLng(lat, lon)).icon(icon);
mapView.addMarker(markerOptions);
```

If I do not append the custom icon to MarkerOptions everything seems to work just fine. Is there a way I can avoid this problem with custom markers?

Standard icon:
![2015-12-22 09 02 03](https://cloud.githubusercontent.com/assets/660586/11951749/d1af80b2-a893-11e5-88a9-7d540db0b006.png)

Custom icon:
![2015-12-22 09 09 00](https://cloud.githubusercontent.com/assets/660586/11951791/251b37dc-a894-11e5-8af9-2bcf675ab611.png)

**Comment by bleege** [comment]
Are you reusing the `Icon icon = mIconFactory.fromDrawable(drawable);` object for each marker or is it also being created for each Marker?

**Comment by esisa** [comment]
That helped a lot :-) No, I was not reusing the markers. The main reason for that was that I have about 80 different markers to place out on the map. That makes it a bit more hassle to reuse the icon.

Is there a limit on how many unique icons I can add to the map?

**Comment by bleege** [comment]
> Is there a limit on how many unique icons I can add to the map? 

There isn't any specific limit count put in the SDK for number of unique icons.  That said loading images into memory does take up more space, especially at a higher resolution with large image files.  So if you have 80 different images to use as icons to load it may work just fine.  It's a Your Mileage May Vary situation.  :smile:

**Comment by tobrun** [comment]
This problem is resolved with the introduction of the Marker View API in `4.1.0`. Closing
