### ISSUE TITLE
Add GLSLang to build

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#339]
To reduce the chance of undetected GLSL errors the official GLSL validating compiler should be run on the shaders during the build to ensure that they are valid.

You can download it from http://www.khronos.org/opengles/sdk/tools/Reference-Compiler/
Linux binary: https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/tools/glslang/Install/Linux/glslangValidator

**Comment by ljbade** [comment]
@kkaefer I am starting to take a look at this.

Which mason branch is the best example of how to build a binary that will be 'installed'? Mesa?

**Comment by springmeyer** [comment]
@ljbade both the 7z and the ragel scripts offer examples I've created that trick mason into packaging the `bin/` directory: https://github.com/mapbox/mason/blob/ragel-6.9/script.sh. Then I put ragel, for example, on PATH for the host arch like this: https://github.com/mapbox/mason/blob/harfbuzz-2cd5323/script.sh#L23-L24

**Comment by ljbade** [comment]
Having problems building glslang

It has this script: https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/tools/glslang/

That when runs does build correctly, but also tries to install to system and run tests.

So I tried just `make -C Standalone` but this then gives me a link error.

Anyone see what else I need from that script?

**Comment by jfirebaugh** [comment]
This doesn't seem like a priority. If the shaders are busted we will see it.
