### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ragummrsa2930** [mapbox/mapbox-gl-native#3410]
Hi, 

Im getting following error, when the app gets called onResume().

com.mapbox.mapboxsdk.exceptions.InvalidAccessTokenException: Using MapView requires setting a valid access token. See the INSTALL.md

**Comment by tobrun** [comment]
The exception`invalidAccessTokenException` indicates that you have not provided a valid access token.
Are you calling `setAccessToken()` or using the xml attribute? 
Here is some [sample code](https://gist.github.com/tobrun/60f020cfee91507d59fe
) for an Activity:
