### ISSUE TITLE
Remove REGION_DID_CHANGE Check From Camera Callback

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#3412]
The original Camera API Refinements from #3358 had Callback checks for both `REGION_DID_CHANGE_ANIMATED` and `REGION_DID_CHANGE`.  The check for `REGION_DID_CHANGE` was put in for the `animateCamera (CameraUpdate update, MapView.CancelableCallback callback)` method as it had a 0 time length duration for animation and therefore technically never animated and therefore the Callback was never called.  However, this check is leading to some inconsistencies with the full `animateCamera (CameraUpdate update, int durationMs, MapView.CancelableCallback callback)` method.  To solve both problems let's remove the `REGION_DID_CHANGE` checks in both `animateCamera()` and `easeCamera()` AND change the `animateCamera()` methods sans duration time parameter to use a 1 millisecond duration to trigger the animation functionality but do so in a way that's not noticeable to humans.

/cc @zugaldia

**Comment by zugaldia** [comment]
:+1:

**Comment by bleege** [comment]
@zugaldia I just started a new `3.1.0-SNAPSHOT` build on Bitrise.  Should be ready in about 30 minutes and will likely be [version 3 on the SNAPSHOT repo](https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-android-sdk/3.1.0-SNAPSHOT/).
