### ISSUE TITLE
Polyline fill color

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#3417]
For equity with iOS MapKit, it should be possible to have a fill color in addition to the stroke color for any polyline. Android and other platforms should benefit from it too.
This feature is missing for the moment.
It will offer a nice path drawing with an inner color and a stroke color.

**Comment by jfirebaugh** [comment]
It's unlikely we'll add this feature to the existing annotation API. Implementing it efficiently requires https://github.com/mapbox/mapbox-gl-style-spec/issues/223. Once that's implemented, then the [style API](https://github.com/mapbox/mapbox-gl-native/issues/837) will expose the polygon layer type, which will be the preferred way to accomplish this.

**Comment by RomainQuidet** [comment]
Hi @jfirebaugh thanks for the feedback. Where can we find your roadmap for the new API ? If I understand well, you'll draw paths with the polygons ?

**Comment by jfirebaugh** [comment]
We'll have API documentation when it's finished. Until then, https://github.com/mapbox/mapbox-gl-native/issues/837 is the best reference. If you're familiar with the gl-js Style API ([`Map#addLayer`](https://www.mapbox.com/mapbox-gl-js/api/#Map.addLayer) and related methods), this is the gl-native equivalent.

**Comment by aditmer** [comment]
Hi @jfirebaugh, just checking, is it still not possible to set the fill color of a polyline in MapBox on iOS and Android?  This is kind of a blocker for the app we are building.
