### ISSUE TITLE
[osx] Pressing on buttons should not pass event to map view

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#3418]
Long-pressing on any of the buttons (compass, zoom, etc) will drop a marker at that point, when one would expect the button to completely consume the press/touch.

/cc @1ec5

**Comment by 1ec5** [comment]
Yep. We don’t have this problem on the iOS side because the gesture recognizers are added to the GLKView subview. There isn’t an equivalent subview on OS X because MGLMapView itself handles drawing the map in a layer.
