### ISSUE TITLE
Support for heat map

### ISSUE THREAD

**Issue by pablobaldez** [mapbox/mapbox-gl-native#3420]
Is possible to use heat maps in MapView widget from Android SDK like Google Maps api?

**Comment by tobrun** [comment]
@pablobaldez 
Thank you for reaching out and requesting this feature.
This is currently not supported and also not on the roadmap for the near future.
Closing this until it becomes a required feature.

**Comment by friedbunny** [comment]
Check out [Mapbox Studio](https://www.mapbox.com/studio/) for all your map-styling needs — it shouldn't be too difficult to create a faux-heatmap with static data.

**Comment by pablobaldez** [comment]
It's true, but the problem is the data isn't static. I'm thinking to use the native google map (has support for heatmaps), and use an UrlTileProvider to load my custom tile from MapBox WS, but the this tile is loaded with low quality from http://api.tiles.mapbox.com/v4/mysource/z/x/y.png

**Comment by 1ec5** [comment]
See https://github.com/mapbox/mapbox-gl-native/issues/6304#issuecomment-246146553 for an approach for faux heat maps that should work in the latest Android SDK beta and iOS SDK alpha.
