### ISSUE TITLE
UserLocationView top left corner when location tracking is enabled

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3425]
As mentioned here https://github.com/mapbox/mapbox-gl-native/issues/2049#issuecomment-168422751 and by @bsudekum.

#### Use-case:
You enable user location tracking when the current viewport is not showing the user location.

#### Current output:
The UserLocationView is drawn in the top left corner. 

#### Required output:
The UserLocationView is not visible.

**Comment by tobrun** [comment]
Might be related to not receiving any location updates

**Comment by tobrun** [comment]
This will be fixed when #3425 lands

**Comment by Buckley404** [comment]
Thanks tobrun, when is the eta for that drop?
