### ISSUE TITLE
Migrate iOS and OS X from libuv to GCD

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3434]
We should move the iOS and OS X SDKs from libuv to GCD. We’ll need to reimplement `mbgl::util::RunLoop`, `mbgl::util::Timer`, and `mbgl::util::AsyncTask`.

/cc @tmpsantos

**Comment by tmpsantos** [comment]
Any volunteer to do something similar for Android? /cc @zugaldia @bleege

**Comment by mb12** [comment]
This will be a high impact project for Android in terms of increasing reliability across a range of devices since it would allow MapView to be implemented as a GLSurfaceView and get rid of all the calls to eglCreateContext, eglSwapBuffers etc. Please refer to the following issue for more details.

https://github.com/mapbox/mapbox-gl-native/issues/1662

Given the high impact, it makes more sense to do this project for Android first instead of iOS.

**Comment by zugaldia** [comment]
Corresponding Android effort ticketed: https://github.com/mapbox/mapbox-gl-native/issues/3440

**Comment by 1ec5** [comment]
Some additional context in #3139 and https://github.com/mapbox/mapbox-gl-native/pull/2909#issuecomment-156210849.

**Comment by tmpsantos** [comment]
As a reference, this is how it was done for Qt: https://github.com/mapbox/mapbox-gl-native/commit/f5cb832590a03adafd06551fd7c05c262bf72d04

Note that on the `RunLoop`, `RunLoop::addWatch` and `RunLoop::removeWatch` is only needed if you want to support `libcurl` as network backend.

**Comment by jfirebaugh** [comment]
I think `CFRunLoop` or `NSRunLoop` is going to be a better fit than GCD for how mbgl's `RunLoop` and `Thread` are currently structured.

@1ec5 Do you know particular reasons whether `CFRunLoop` or `NSRunLoop` should be preferred over the other for mbgl?

**Comment by 1ec5** [comment]
At a quick glance, the biggest difference between the two is that CFRunLoop is a C API that follows Core Foundation / Carbon memory management conventions, while NSRunLoop is an Objective-C API that follows Cocoa conventions. Since we’re able to write the adapter in Objective-C++, either would technically work. Much like the CFURL / NSURL choice, I’m guessing it comes down to configurability versus elegance.

**Comment by jfirebaugh** [comment]
This is now included in #2909.
