### ISSUE TITLE
[Android] Add an API for setting the cache size

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#3436]
After 6d0b01c5fb1e07 it is possible to define a maximum cache size. This API should be exported otherwise the cache will grown indefinitely.

**Comment by tobrun** [comment]
@tmpsantos 
I'm seeing 2 additions in  6d0b01c
 - Maximum cache size
 - Maximum cache size entry

Couple questions:
 - Should I expose only the former as an API or both?
 - Should I provide a default value for `maximum cache size` myself or is `indefinitely` the default?

TODO:
- [ ] expose API in  `MapView.java` through setter/getter (attribute?)
- [ ] incase of default, add that one to `MapboxConstants`
- [ ] expose API in `NativeMapView.java`
- [ ] take a trip down C++ land and add to `jni.cpp`, `native_map_view.cpp`,..

**Comment by tmpsantos** [comment]
> Maximum cache size entry

I don't think this one is needed. The default (5MB) is mostly for "protecting" the cache from adding an entry that is way too big. We don't have tiles that big.

**Comment by jfirebaugh** [comment]
Please hold on this until design and implementation of offline settles down. We have too much already moving in this area.

**Comment by 1ec5** [comment]
> After 6d0b01c it is possible to define a maximum cache size.

This API is going away in #9371.
