### ISSUE TITLE
[ios] Add an API for setting the ambient cache size

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#3437]
After 6d0b01c it is possible to define a maximum cache size. This API should be exported otherwise the cache will grown indefinitely.

**Comment by 1ec5** [comment]
Should the SDK pick a default (other than `kMaximumCacheEntrySize`)? This doesn’t sound like something we could include in setup steps, because developers would have no feel for a good maximum cache size, at least initially.

**Comment by tmpsantos** [comment]
`kMaximumCacheEntrySize` stands for the maximum size of the an individual entry in the cache. The default today is `5MB` which is quite big and very unlikely to hit considering that our vector tiles and raster tiles are relatively small.

The default size for the cache is `0` which stands for unlimited (like it was before). iOS could set its own default at the moment it creates the `SQLiteCache` object.

**Comment by 1ec5** [comment]
OK, so we need to come up with a reasonable default to bake into the iOS SDK. What factors should we account for?

**Comment by jfirebaugh** [comment]
Please hold on this until design and implementation of offline settles down. We have too much already moving in this area.

**Comment by friedbunny** [comment]
This feature does not appear to currently exist for Android, so I’ve changed the issue name and added the Android tag.

**Comment by jfirebaugh** [comment]
I think #3436 was intended to be the parallel issue for Android.

**Comment by friedbunny** [comment]
Errg, OK. Let’s proactively link these issues, if we’re going to cut platform-specific tickets.

**Comment by 1ec5** [comment]
> After 6d0b01c it is possible to define a maximum cache size.

This API is going away in #9371.
