### ISSUE TITLE
[Android] Remove unused parameters in HTTPAndroidRequest

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#3438]
Via @mikemorris, there seem to be some unused parameters in `HTTPAndroidRequest` creating some warnings.

Related commit: https://github.com/mapbox/mapbox-gl-native/commit/03cf403be7677d5420d0b91351029cd8397d8cb6#commitcomment-14539204

/cc: @bleege @tobrun

**Comment by tobrun** [comment]
As a workaround I have silenced this warning in #3539 because this was breaking our builds on CI, 
the actual issue should be addressed here.
