### ISSUE TITLE
Migrate Android from libuv

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#3440]
We should move the Android SDK from libuv to a native Android solution. We’ll need to reimplement `mbgl::util::RunLoop`, `mbgl::util::Timer`, and `mbgl::util::AsyncTask`.

Related: https://github.com/mapbox/mapbox-gl-native/issues/3434

/cc @tmpsantos @1ec5

**Comment by 1ec5** [comment]
Some additional context in #3139 and https://github.com/mapbox/mapbox-gl-native/pull/2909#issuecomment-156210849.

**Comment by bleege** [comment]
Confirmed that `mbgl::util::RunLoop`, `mbgl::util::Timer`, and `mbgl::util::AsyncTask` have been implemented in #4280.

**Comment by tmpsantos** [comment]
Fixed by #4280
