### ISSUE TITLE
Stop user tracking if a gesture occurs

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3444]
Currently the iOS and Android library are handling location tracking differently. 
 - Android disables certain gestures when locational tracking is enabled
 - iOS enables gestures but will disable tracking if a gesture occurs

We need parity on this for React Native as documented in https://github.com/mapbox/react-native-mapbox-gl/issues/222

**Comment by tobrun** [comment]
I will have to add a listener to react to state changes for both location tracking as for direction tracking.

**Comment by tobrun** [comment]
You can see the result of this change here:
https://www.dropbox.com/s/noxfuzpetgh6rk8/device-2016-01-06-091241.mp4?dl=0
In the clip you can see that location tracking is enabled and when you pan it becomes disabled.

**Comment by tobrun** [comment]
Going to pickup #3435 now, this is the same feature

**Comment by Tyler-V** [comment]
@tobrun sorry for commenting in a very old PR but I couldn't find any updated references.

How do we go about solving this in iOS? The location libraries appear to be so different, I'm unable to apply any custom zoom/tilt operators to the ios map and even stop tracking / remove the user tracking annotation on the Map.
