### ISSUE TITLE
Add test documentation and test scripts

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3447]
This issue focusses on adding documentation about AWS device farm and performance testing in `platform/android/tests`. I will migrate the contents of the files in the `AWS-devicelab` branch to this issue hence the structure of the project has changed in the meantime.

cc @zugaldia

**Comment by tobrun** [comment]
Linking https://github.com/mapbox/gl-internal/issues/379

**Comment by tobrun** [comment]
I now have found https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/README.md, Will use that as an entry point instead of the `platform/android/tests` mentioned above.

**Comment by tobrun** [comment]
We used to have all documentation in that one `README.md` file from above. I'm going to create a `docs` folder in the root directory of the Android project and separate the contents in to different files.

**Comment by tobrun** [comment]
Going to migrate the AWS script form the stale SF-sprint branch. 

Will need to create a different structure in folders:

`platforms > android > tests > docs`
`platforms > android > tests > scripts`

**Comment by tobrun** [comment]
Need to add a script for performance testing to complete this issue (documentation is already provided)

**Comment by zugaldia** [comment]
@tobrun All looking good. Feel free to delete my original `aws-devicelab` branch once you've moved all the files to the new tree structure.

**Comment by tobrun** [comment]
Landed in #3449
