### ISSUE TITLE
Android Bug: the map rotates on enabling tracking

### ISSUE THREAD

**Issue by lgeromegnace** [mapbox/mapbox-gl-native#3450]
Hi,
We are working on adding insets to the map (#2600) and we notice an unexpected behavior with the test app.

### How to:
After rotating the map, press the user location button several times.

### Observed:
The map rotates each time we press the user location.

### Expected:
The map should not rotate.

**Comment by tobrun** [comment]
@lgeromegnace 
Could you add some code to test with?
Which version of the SDK are you using?

**Comment by lgeromegnace** [comment]
@tobrun 
I observed the bug on version 3.1.0-SNAPSHOT of MapboxGLAndroidSDK.
You asked for code but I had the issue without any modification of mine.

**Comment by tobrun** [comment]
@lgeromegnace 
I was able to reproduce it, looking..

**Comment by tobrun** [comment]
When debugging I'm noticing that the `MyBearingTracking` value was equal to `MyBearingTracking.GPS`. I believe the problem is coming from not saving the `MyBearingTracking` state in `onSaveInstanceState`. With that in place I'm unable to reproduce it. Reopen if incorrect.

**Comment by tobrun** [comment]
@lgeromegnace 
Note that this will be merged in release branch of 3.1.0 and will not be available in SNAPSHOT.

**Comment by lgeromegnace** [comment]
Okay ! Thanks @tobrun

**Comment by tobrun** [comment]
Landed in release branch with d764e9829eab48d2b6122ce2285f5ed95a366c6f
