### ISSUE TITLE
Changing pixel density in GL test app makes map go blank

### ISSUE THREAD

**Issue by danpat** [mapbox/mapbox-gl-native#3451]
I just built `make run-osx` from 9d6cb1361c84fbc6736b2842037d8a3cff580d1a to test some map rendering using GL-native on OSX.

I have a MBP 13" with a Retina display, and an external Dell monitor running at 2560x1440 (non-retina):
![screen shot 2016-01-06 at 9 39 46 am](https://cloud.githubusercontent.com/assets/1892250/12149620/7e7cd922-b459-11e5-8ddc-d973a4b90f22.png)

If I drag the Mapbox GL app from the retina display to the non-retina display, the map goes blank, and won't come back unless I restart the app.  Interaction seems to still work and all the controls are still there:

Launched on the non-retina display:
![screen shot 2016-01-06 at 9 42 45 am](https://cloud.githubusercontent.com/assets/1892250/12149677/dd358f18-b459-11e5-8ffa-3597b33f2a74.png)

Launched on the retina display:
<img width="703" alt="screen shot 2016-01-06 at 9 45 18 am" src="https://cloud.githubusercontent.com/assets/1892250/12149736/397caa2c-b45a-11e5-9b60-bbfa09923c91.png">

Moved from Retina to non-Retina:
<img width="352" alt="screen shot 2016-01-06 at 9 41 19 am" src="https://cloud.githubusercontent.com/assets/1892250/12149649/b02d7bc0-b459-11e5-8692-2c983f7ba47c.png">

In addition, the following warning is printed to the console when I move between from the launch pixel density to a different pixel density:

```
2016-01-06 09:43:16.702 Mapbox GL[27089:22073075] Unable to simultaneously satisfy constraints:
(
    "<NSLayoutConstraint:0x7fe02bf99190 NSSlider:0x7fe02bc6d3e0.centerX == NSSegmentedControl:0x7fe02bc82b40.centerX>",
    "<NSLayoutConstraint:0x7fe02bca1ba0 NSSlider:0x7fe02bc6d3e0.centerX == NSSegmentedControl:0x7fe02bc82b40.centerX>"
)

Will attempt to recover by breaking constraint
<NSLayoutConstraint:0x7fe02bf99190 NSSlider:0x7fe02bc6d3e0.centerX == NSSegmentedControl:0x7fe02bc82b40.centerX>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
```

**Comment by danpat** [comment]
Note: the "Launched on non-retina display" image also seems to have poor antialiasing on the edges of lines and fonts.

**Comment by jfirebaugh** [comment]
⇢ #6654
