### ISSUE TITLE
How should offline APIs handle asynchronicity?

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#3455]
For example, consider a method that creates a new offline region. Here's what a synchronous API might look like:

```c++
OfflineRegion
createOfflineRegion(const OfflineRegionDefinition&,
                    const OfflineRegionMetadata&);
```

This is not a good solution. This method needs to perform disk I/O in order to write information about the region (the definition and metadata) into the offline database. That's slow, and should not be executed on the main thread.

(You might argue that with ubiquitous SSDs that this example would be fast enough to execute on the main thread. But it's just an example -- there are certainly offline use cases where asynchronicity is essential, e.g. calculating the total size of an offline region.)

We could require the caller to execute the call off the main thread. But that makes life difficult for the implementation: it must assume it can be called from any thread. Since database handles can't safely be used from multiple threads, access must be protected by a mutex, and so on.

Here's another possibility:

```c++
std::unique_ptr<WorkRequest>
createOfflineRegion(const OfflineRegionDefinition&,
                    const OfflineRegionMetadata&,
                    std::function<void (std::exception_ptr, OfflineRegion)>);
```

Instead of returning an `OfflineRegion` directly, the method accepts a callback conforming to a node-like error convention. The implementation ensures that the actual work occurs off the main thread, and when a result (or error) is ready, schedules the callback for execution on the thread that originally called `createOfflineRegion`. (The latter requires that that the calling thread is running an event loop.)

Notice that this method still returns a value: `std::unique_ptr<WorkRequest>`. This reflects the fact that the method is effectively _creating a resource_ whose lifetime must be managed: the pending future execution of the callback. In all but trivial cases, the callback will reference objects with their own lifetimes. Those objects must outlive the future execution of the callback -- if they don't, they are by definition invalid references when the callback executes. Returning an ownership object both helps ensure the lifetimes line up, and provides a means to cancel the callback should it no longer be necessary.

We're successfully using this pattern in mapbox-gl-native internals, but so far not in a public API. There are two issues with introducing it to a public API:

1. It's complex and non-idiomatic C++. Perhaps we can alleviate this at the SDK level by wrapping it in async conventions that are idiomatic for the SDKs' respective platforms. I'd be interested to hear from @1ec5, @tobrun, @zugaldia, et al if they believe that's the case.
2. As noted before, it requires the calling thread to be running an event loop. Right now, that means "libuv event loop" specifically. Our internal use is only on threads that actually have a libuv event loop, and we have a fair bit of work to do to make it workable on the main thread with a native event loop.

Here's the idiomatic C++ interface:

```c++
std::future<OfflineRegion>
createOfflineRegion(const OfflineRegionDefinition&,
                    const OfflineRegionMetadata&);
```

This interface will be pleasing and familiar to C++-niks. But in order for it to be a convenient API, there needs to be some way of integrating C++ futures with the native event loop, such that a task can be scheduled on the event loop when the future resolves. I'm not aware of such a convenience -- I couldn't find any nice looking solutions in a few searches. But again, I might be overlooking platform-specific possibilities (GCD?).

/cc @kkaefer @tmpsantos @brunoabinader @adam-mapbox

**Comment by mb12** [comment]
@jfirebaugh What is 'OfflineRegion' and what does it model?

**Comment by jfirebaugh** [comment]
It's part of #584. An offline region will be defined by a style URL, bounding box, zoom range, and device pixel ratio, and form a self-contained unit for the purposes of downloading and storing of all resources (styles, sprites, glyphs, TileJSON, GeoJSON, and vector and raster tiles) required to render that region.

**Comment by daniel-j-h** [comment]
I would advise against C++11 / C++14 `std::future` --- it is broken in so many ways.
[N3721](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3721.pdf) is a proposal for a better future, quick and good read.

The main problem is composability. There's no `.then` (monadic bind), `.when_any`, `.when_all` and similar. This makes futures useless for everything that is not just a one-off computation on the side.

Bartosz Milewski has a series of [blog post and a talk](http://bartoszmilewski.com/2014/02/26/c17-i-see-a-monad-in-your-future/) on exactly this.

Boost's future already provides those extensions. Also interesting, the folly implementation: there is a really good blog post on introducing advanced futures features, such as `collect` (transform a collection of futures to a single future of the collection, which really is Haskell's `sequence :: Monad m => [m a] -> m [a]` if you squint hard enough --- yes, futures are monads):

- https://code.facebook.com/posts/1661982097368498/futures-for-c-11-at-facebook/
- https://github.com/facebook/folly/blob/master/folly/futures/README.md

**Comment by tmpsantos** [comment]
`std::unique_ptr<WorkRequest>` pattern is definitely my favorite.

I do agree with `1.` that any issues with not being C++ idiomatic could be addressed by the bindings layer, although I find this pattern quite straightforward (or maybe I got used to it). Regarding `2.`, it would create a dependency on https://github.com/mapbox/mapbox-gl-native/issues/3440 and https://github.com/mapbox/mapbox-gl-native/issues/3434.

Another option would be do like we do for `void Map::renderStill(StillImageCallback callback);` that takes a callback that should be threadsafe and will somehow notify the main thread. The issue here is that the task can no longer be canceled.

**Comment by 1ec5** [comment]
It’s already common for mbgl to call callback functions passed in from the iOS side. If it’s on a background thread, MGLMapView just turns around and calls user code on the main thread using Grand Central Dispatch ([example](https://github.com/mapbox/mapbox-gl-native/blob/aa76b680ef989e3b2984a49452434b78ba5d18f6/platform/ios/src/MGLMapView.mm#L1677-L1681)).

**Comment by jfirebaugh** [comment]
Right, so what @tmpsantos and @1ec5 are getting at is a fourth possibility:

```
void
createOfflineRegion(const OfflineRegionDefinition&,
                    const OfflineRegionMetadata&,
                    std::function<void (std::exception_ptr, OfflineRegion)>);
```

In this case, the callback is not scheduled to be called on the thread that called `createOfflineRegion`; instead it's called from the implementation thread and it is the callback's responsibility to reschedule execution on the main thread if desired. In practice, the SDK bindings handle doing so transparently.

The other difference is that the operation is not cancellable, and the callback must ensure that any resources it uses are guaranteed to still exist for as long as the operation might take. In C++ this is typically problematic, but in Obj-C or Java less so, since their ARC/GC semantics ensure that if the callback is called later than you expected, the effect is merely a prolonged lifetime for the referenced object, rather than an invalid memory access.

Overall I like this strategy the best.

**Comment by 1ec5** [comment]
> The other difference is that the operation is not cancellable, and the callback must ensure that any resources it uses are guaranteed to still exist for as long as the operation might take. In C++ this is typically problematic, but in Obj-C or Java less so, since their ARC/GC semantics ensure that if the callback is called later than you expected, the effect is merely a prolonged lifetime for the referenced object, rather than an invalid memory access.

In Objective-C++, that is only the case for Objective-C objects. C++ objects and structs behave the same way they do in C++.

**Comment by jfirebaugh** [comment]
@1ec5 Correct. In practice, I hope that the SDK bindings will look like [the example you linked](https://github.com/mapbox/mapbox-gl-native/blob/aa76b680ef989e3b2984a49452434b78ba5d18f6/platform/ios/src/MGLMapView.mm#L1677-L1681), and not need any references of those types.
