### ISSUE TITLE
Limit ccache on Travis

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#3464]
Currently, ccache limit is set at 1 GB, which is probably too high so Travis caches too much unneeded data. We should figure out how big the build cache of a clean build is approximately, and lower it to just above that number.

**Comment by jfirebaugh** [comment]
Current actual cache size is ~700-900 MB, so 1GB seems like a reasonable buffer.

**Comment by kkaefer** [comment]
Yeah, but is dragging along many outdated objects. We should only cache the 200-300 object files used in the current build.
