### ISSUE TITLE
Slow internet connection can result in an ANR

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3465]
This was mentioned by one of our users on helpscout.
We should be able reproduce similar scenarios using tooling as [AT&T ARO](https://developer.att.com/application-resource-optimizer).

**Comment by tobrun** [comment]
Since related #3998 was marked as resolved, going to close this, will reopen if we hear new reports of this.

**Comment by whyzjl** [comment]
I have this problem：Slow internet connection results can result in an ANR。My mapbox version is: v5.5.1. 
have you solved this？
