### ISSUE TITLE
Take Snapshot of MapView

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3466]
I have noticed that users are requesting this feature.

Users would like to create a bitmap of an active `MapView` and use that in a place where a `MapView` would not be appropriate to use eg. `Notification` or `Listview`.  
 
Linking:
 - iOS discussion in https://github.com/mapbox/mapbox-gl-native/issues/1701
 - [Google Maps](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap#snapshot%28com.google.android.gms.maps.GoogleMap.SnapshotReadyCallback%29) functionality for parity

**Comment by s3r6** [comment]
Snapshot taken does not contain markers that are MarkerViews and info windows above them. How can I take snapshot with markers?
