### ISSUE TITLE
Storage.HTTPNetworkStatusChangePreempt is flaky

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#3471]
```
[ RUN      ] Storage.HTTPNetworkStatusChangePreempt
../../test/storage/http_retry_network_status.cpp:72: Failure
Expected: (0.39) < (duration), actual: 0.39 vs 0.381111
Preempted retry triggered too early
[  FAILED  ] Storage.HTTPNetworkStatusChangePreempt (385 ms)
```

https://travis-ci.org/mapbox/mapbox-gl-native/jobs/100963208

cc @kkaefer

**Comment by tmpsantos** [comment]
Not sure if this is the case here, but everything using `timer` + `libuv` can expect it to fire a bit earlier due to how timer is implemented on `libuv` (using some caching for optimization).

**Comment by jfirebaugh** [comment]
We should really try to avoid timing-based tests. They are difficult to write in a way that guards against flakiness on different platforms or when the test environment is under load.

**Comment by jfirebaugh** [comment]
Haven't seen this recently.
