### ISSUE TITLE
[ios] how to make a route?

### ISSUE THREAD

**Issue by Sh1mor1nka** [mapbox/mapbox-gl-native#3482]
Sorry but how can i make a route from my location to some point?

**Comment by Sh1mor1nka** [comment]
Knock knock...

**Comment by friedbunny** [comment]
Check out [MapboxDirections.Swift](https://github.com/mapbox/MapboxDirections.swift), a fairly simple wrapper for Mapbox's [Directions web API](https://www.mapbox.com/developers/api/directions/).

**Comment by Sh1mor1nka** [comment]
@friedbunny Sorry Jason, but as I understand there are no possibility to make route in offline mode now?

**Comment by friedbunny** [comment]
@Sh1mor1nka Offline routing isn't possible currently.

I'm also unsure if caching responses from the Directions API is permissible under our [Terms of Service](https://www.mapbox.com/tos/); directions may be considered as similar to geocoding, which has special requirements for caching.

If storing routes is a requirement, [please get in touch with us](https://www.mapbox.com/contact/).

**Comment by Sh1mor1nka** [comment]
@friedbunny Hello Jason, sorry but how can I add show route on map? I see example **MapboxDirections.Swift** but there are only console results and no map example.

**Comment by 1ec5** [comment]
Followed up in mapbox/MapboxDirections.swift#21.
