### ISSUE TITLE
[android] Update TestApp to use new Directions SDK

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#3484]
Related: https://github.com/mapbox/mapbox-directions-android

**Comment by bleege** [comment]
Screen shot of the example showing walking directions from Dupont Circle to the gates of the White House in Washington, DC.

![device-2016-01-12-105154](https://cloud.githubusercontent.com/assets/989928/12270871/e0f8f4aa-b91d-11e5-91fb-c6a093871705.png)

**Comment by bleege** [comment]
Rebased and pushed to `master`.  Directions are good to go!  :rocket:
