### ISSUE TITLE
Mapbox iOS SDK with serious memory leak issues

### ISSUE THREAD

**Issue by massifor** [mapbox/mapbox-gl-native#3502]
I wrote a view controller,  just within  a single view of MGLMapView ,  it will increase 36M memory when I pop from it.

It would received memory warnings when I repeat that several times, and app did crashed when I continue。

**Comment by 1ec5** [comment]
Fixed in #3448. The fix will be in the next release.

**Comment by linqiang** [comment]
But I'm not use  CADisplayLink,mapbox memory leadk too

**Comment by 1ec5** [comment]
You aren't using CADisplayLink directly, but MGLMapView does, in order to drive animations smoothly.

**Comment by linqiang** [comment]
I see,THX for your answer
