### ISSUE TITLE
Double serialisation of classes in geometry package

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3503]
Classes found in `geometry` package are implementing both Serializable as Parceable.
We should remove Serializable in favour of Parceable.
More information [why](http://www.developerphil.com/parcelable-vs-serializable/) Parceable > Serializable

**Comment by tobrun** [comment]
It seems that all the CoordinateX classes have not been updated with Parceable interfaces.

**Comment by tobrun** [comment]
I'm also changing class members signature to be Android code convention compliant.

**Comment by tobrun** [comment]
This landed with 8ffe776 on release branch of `3.0.1` in #3537

**Comment by bleege** [comment]
Love the reasoning behind this:  Parcelable is more performant (aka speedy) than Serialization.

:+1:
