### ISSUE TITLE
Leaking LocationListener on Android

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3507]
Memory leak detected with integration of LeakCanary in #2184.

![device-2016-01-11-154224](https://cloud.githubusercontent.com/assets/2151639/12236432/f8cb91cc-b879-11e5-8a9a-9d54e7299519.png)

**Comment by tobrun** [comment]
I have created a `static innerclass` to handle location updates given to `UserLocationView`.
I'm now unable to reproduce this leak. Going to commit and PR this.
If you are able to reproduce this later on, reopen this issue.

**Comment by tobrun** [comment]
This landed with 0ebf5fc on release branch `3.0.1` for #3537

**Comment by MrDazt** [comment]
Still leaking

* GC ROOT android.location.LocationManager$ListenerTransport.mListener
* references kg.nambaapps.taxidriver.services.LocationService.locationServiceInterfaces
* references java.util.ArrayList.elementData
* references array java.lang.Object[].[1]
