### ISSUE TITLE
Download tiles for offline usage

### ISSUE THREAD

**Issue by AskinOharis** [mapbox/mapbox-gl-native#3508]
Hi guys,
I was reading through #584 and #2939 and I am still not sure if there will be some method for downloading tiles like this one in the old raster SDK <code>-beginDownloadingMapID:mapRegion:minimumZ:maximumZ:</code>

Thanks for clarification,
Askin

**Comment by friedbunny** [comment]
Offline support isn't available yet, but we're working on it. See #584 for more information.

**Comment by friedbunny** [comment]
Whoops, didn't actually answer your question — the implementation details of the API will likely follow what we've done in the past, but that's also yet to be hammered out.
