### ISSUE TITLE
Expose GPS Interval And Displacement Settings

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#3515]
The LocationServices class is currently hardwired to use a specific [`fastestInterval`](https://github.com/mapbox/mapbox-gl-native/blob/13d5b18ebaeb330f05c4abfc04e0247222e038ba/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationServices.java#L73) and [`smallestDisplacement`](https://github.com/mapbox/mapbox-gl-native/blob/13d5b18ebaeb330f05c4abfc04e0247222e038ba/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationServices.java#L74) when setting up the GPS for location tracking.  Enable setting custom values for this while leaving the defaults if not specified.

/cc @zugaldia @tobrun

**Comment by tobrun** [comment]
:+1:

**Comment by bleege** [comment]
Upon further reflection, I think this should be built out as a [`meta-data`](http://developer.android.com/guide/topics/manifest/meta-data-element.html) option to be set in `AndroidManifest.xml` instead of a direct programmatic method.  Reason being is that User Location should be something that is app wide and consistent.

**Comment by cammace** [comment]
Would this be resolved/included in `LocationSource` @tobrun? Something to add to `5.0.0`?

**Comment by tobrun** [comment]
I consider this becoming obsolete with #4331. While this issue goes about tweaking the current location provider, #4331 will allow replacing the whole provider itself. Closing..
