### ISSUE TITLE
make TileID more similar to -js's TileCoord

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#3529]
- `x` values are wrapped by worlds in -js but not in -native
- `w` value doesn't make sense in -native
- names are different

**Comment by jfirebaugh** [comment]
Regarding tile wrapping, the changes I would like to see are:

* Two different types: `TileID` (wrapped x coordinate; prefer this type unless you specifically need an unwrapped ID) and `UnwrappedTileID` (unwrapped x coordinate + `w`)
* `UnwrappedTileID` has `TileID wrap() const` method; no other conversions are available
* `tileCover` returns `UnwrappedTileID`s
* Remove `Source::getLoadedTiles()` and `Source::getTiles()`
* Add `Source::getCoveringUnwrappedTileIDs()`, `Source::getTile(const TileID&)` and _maybe_ `Source::getTile(const UnwrappedTileID&)`
* Change `TransformState::matrixFor` parameter to `UnwrappedTileID`
* Fix ripples from those changes

**Comment by jfirebaugh** [comment]
The names `TileCoordinate` and `UnwrappedTileCoordinate` would be ok with me too, but we'll need to clear away the existing `TileCoordinate` type first.

**Comment by jfirebaugh** [comment]
⇢ #3834
