### ISSUE TITLE
[Android][Bug] Bearing Mode is disabled when touching the MapView

### ISSUE THREAD

**Issue by mayardb** [mapbox/mapbox-gl-native#3535]
Hi MapBox team,

In the `MyLocationTrackingModeActivity` sample, I noticed that the bearing mode is disabled when touching the MapView.

```
@Override
        public boolean onDown(MotionEvent event) {
            // Show the zoom controls
            if (mZoomControlsEnabled && mZoomEnabled) {
                mZoomButtonsController.setVisible(true);
            }

            // Disable tracking mode if a gesture occurs
            try {
                setMyLocationTrackingMode(MyLocationTracking.TRACKING_NONE);
                setMyBearingTrackingMode(MyBearingTracking.NONE);
            }catch(SecurityException ignore){
                // User did not accept location permissions
            }

            return true;
        }
```

Is it possible to change it just to disable Tracking only when running a gesture :
* pan
* scale
* rotate
* tilt / pitch

and not in the `onDown` method anymore ?

**Comment by tobrun** [comment]
I have taken a closer look at [iOS](https://github.com/mapbox/mapbox-gl-native/blob/e26b218883c3357f38dd8ff5490b453dabffc590/platform/ios/src/MGLMapView.mm#L931) and they are doing the same thing you are suggesting, 
will take this up now.

**Comment by tobrun** [comment]
This will probably result in the requirement to subclass the gesturedetector from almeros

**Comment by tobrun** [comment]
Been looking at integrating this requirement but this won't be an easy fix hence we rely on external gesturedetectors and these are not always compliant with returning a correct boolean value if a gesture starts. Ideally I would love to pick this up with https://github.com/mapbox/mapbox-gl-native/issues/553.

Since we are going to release 3.1.0 #3537 next week, I'm going to refocus on other issues first.

@mayardb
Feel free to tackle this issue and provide a PR. 
We at Mapbox :heart:  PR's.

**Comment by tobrun** [comment]
@mayardb 
I just gave it a 2nd look and was able to find a easy solution.

**Comment by mayardb** [comment]
@tobrun 
If I am right, you are still disabling the bearing when updating the map.

I think you just have to reset the `MyTrackingMode` and let the `MyBearingMode` in the same state.

**Comment by tobrun** [comment]
@mayardb 
To be on par with iOS, I have to disable them both (this is required for [react-native](https://github.com/mapbox/react-native-mapbox-gl))
Feel free to create a builder pattern to make this configurable,
with default configuration reflecting current setup.

**Comment by mayardb** [comment]
@tobrun 
If [react-native](https://github.com/mapbox/react-native-mapbox-gl) uses [mapbox-gl](https://github.com/mapbox/mapbox-gl-native) and requires the bearing not to remain enable when interacting with the `MapView`, I think that using a listener to detect map bounds change and reseting the bearing might do the same and let [mapbox-gl](https://github.com/mapbox/mapbox-gl-native)  users free to do what they want when map bounds change.

Unfortunately there is no possibility to undo a reset with a listener on the bearing changes because of the accuracy reset (by the way, it might be another bug).
