### ISSUE TITLE
Custom icons not working

### ISSUE THREAD

**Issue by Jonfor** [mapbox/mapbox-gl-native#3536]
The error, which happens right on the addMarker line:
`01-13 12:08:18.627 18751-18751/com.test.test A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 18751 (test.test)`

I am running Android 6.0.1.

Here is my what i'm including:
```
compile('com.mapbox.mapboxsdk:mapbox-android-sdk:3.0.0@aar') {
        transitive = true
}
```

Here is my code:

```
private void displayCoords() {
List<LatLng> latLngs = new ArrayList<>();
        Double latTotal = 0.0;
        Double lngTotal = 0.0;

        for (int i = 0; i < list.size(); i++) {
            Obj curr = list.get(i);
            LatLng latLng = new LatLng(curr.getLat(), curr.getLng());
            latLngs.add(latLng);

            IconFactory mIconFactory = IconFactory.getInstance(this);
            Drawable mIconDrawable = ContextCompat.getDrawable(this, R.drawable.ic_directions_boat_black_18dp);
            Icon icon = mIconFactory.fromDrawable(mIconDrawable);

            mapView.addMarker(new MarkerOptions()
                    .title(curr.getName())
                    .snippet(curr.getDescription())
                    .position(latLng)
                    .icon(icon));
}
```

I have the ic_directions_boat_black folders (drawable-hdpi, drawable-mdpi, etc.) in res/drawable.

Also, your Android tutorial, https://www.mapbox.com/help/first-steps-android-sdk/#getting-started says to use SpriteFactory while your example, https://www.mapbox.com/android-sdk/custom-marker-icon/ uses IconFactory.

**Comment by tobrun** [comment]
What are the dimensions of `ic_directions_boat_black`? 
Would you be able to share this image with us?
This will probably be related to https://github.com/mapbox/mapbox-gl-native/issues/3031

**Comment by Jonfor** [comment]
Sure. it's the same images that you use in the example. https://www.mapbox.com/android-sdk/files/ic_directions_boat_black_18dp.zip

**Comment by tobrun** [comment]
@Jonfor that image should not give any problems.
Could you add a bit more of the stacktrace? 

I won't be able to identify the problem by only having this information:
> 01-13 12:08:18.627 18751-18751/com.test.test A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 18751 (test.test)

**Comment by rafjp** [comment]
I am having this issue as well.

There is no stack trace and all I get is 
01-19 17:01:05.907 31009-31009/com.navico.gofreehooked A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 31009 (co.xxx_myappname)

Any ideas?

**Comment by tobrun** [comment]
This should be fixed with https://github.com/mapbox/mapbox-gl-native/pull/3561, We are trying to get this in the `3.1.0` release. 

@Jonfor @rafjp:
Would you be able to retest when we release the new version?
I will ping you when that happens.

**Comment by Jonfor** [comment]
Will do.

**Comment by rafjp** [comment]
yes of course.

Looking forward to it.



On Thu, Jan 21, 2016 at 4:06 AM, Jonathan Forscher <notifications@github.com

**Comment by rafjp** [comment]
sorry but its still crashing as above.

**Comment by tobrun** [comment]
@rafjp the fix [did not land](https://github.com/mapbox/mapbox-gl-native/issues/3537#issuecomment-173259381) with `3.1.0`. You should be able to try out the fix in the upcoming SNAPSHOT.

**Comment by rafjp** [comment]
great, could you please let me know when it is available for me to test?

**Comment by tobrun** [comment]
@rafjp:
You should be able to test this with the SNAPSHOT:
Checkout [these](https://www.mapbox.com/android-sdk/#gradle) build instructions.

**Comment by rafjp** [comment]
thanks, I have tested and it has fixed the issues but I am now noticing crashes occurring when performing other operations now which which 3.0 were working.

**Comment by tobrun** [comment]
@rafjp 
Thank you for taking the time to retest this. 
could you open a new ticket for the other crash?
I really want to know what is going wrong and what we can do to help resolve this.

Closing since the main issue is resolved.

**Comment by rafjp** [comment]
"could you open a new ticket for the other crash?" - sorry but we are on a really tight deadline and just do not have the time to help you track down map box issues.

Even upgrading from 3.0 to 3.1 has had to be put on hold due to us experiencing crashes with map box when it had been working OK.

**Comment by Jonfor** [comment]
I upgraded to version 3.2 and the issue has been fixed.
