### ISSUE TITLE
Add geocoder sample to the Test App

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#3538]
We need to add a new sample activity to the Test App to demonstrate the new geocoder library.

**Comment by bleege** [comment]
Work is being done on https://github.com/mapbox/mapbox-gl-native/tree/3538-geocoder-sample

**Comment by bleege** [comment]
Rebased and merged into `release-android-3.1.0`

**Comment by zugaldia** [comment]
Thank you @bleege !
