### ISSUE TITLE
Add possibility to fix the pixelsize of rendered raster tiles

### ISSUE THREAD

**Issue by pergustas** [mapbox/mapbox-gl-native#3544]
We are using MapboxGL native for iOS. The number of screen-pixels covered by a raster tile seems to vary quite a lot and is depending on the zoom level. Sometimes a single tile (a jpg image of 256 by 256 pixels) will cover an area of 512 by 512px on an iPad screen. The result is a blurry map. 

It would be nice to be able to set the behavior to be the same as for Apples built in map component. That its, a raster tile is always displayed as 256 by 256 pixels on screen. 
![skarmavbild 2016-01-14 kl 09 32 46](https://cloud.githubusercontent.com/assets/1084275/12319856/4df7b9d2-baa5-11e5-951b-10f0299020b7.png)

**Comment by pergustas** [comment]
A second thought. Isn't it just so that mbgl, for the moment, ignores tileSize in the source and scales raster tiles to 512px no matter their actual size?

**Comment by mikemorris** [comment]
Blurry raster layers looks like a regression to me, I'm seeing this in downstream tests with 5119ce8155713e9f601b2a5dd6c6dc5aefcb93ed, where raster layers were previously rendering fine on 0ef257bfc623b1c68eeb9a60dad9c8dd18a7befb. I can try bisecting to find the commit that introduced this.

**Comment by pergustas** [comment]
Would it be possible that this issue is caused by the bug described in https://github.com/mapbox/mapbox-gl-native/issues/3552 ?

**Comment by jfirebaugh** [comment]
@pergustas Potentially, although that was introduced in the last 24 hours. Are you using a build that's that recent?

**Comment by pergustas** [comment]
We are, but the problem surfaced last week. So the cause must be older than that.

**Comment by mikemorris** [comment]
Hmm, `git bisect` gave me `e8705d535d56415ff8f97db1ad6b5a77ed3fcd4a is the first bad commit` so I'm inclined to think this is caused by https://github.com/mapbox/mapbox-gl-native/issues/3552

**Comment by pergustas** [comment]
Oh. #3552 may have been a real bug. But I am afraid the issue behind my report was caused by a mistake made by ourselves. Sorry for taking up your time. We´ll be more careful to do our homework before posting another issue. (I guess I will have to pay for the beer if we meet sometime ;-)
