### ISSUE TITLE
Setting the center coordinate is ignored while map is decelerating

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-gl-native#3557]
Calling `setCenterCoordinate:zoomLevel:animated:` while the map is decelerating from a pan gesture will cause the assigned center coordinate to be ignored.  This can also cause the wrong zoom level to render (in screenshot).  I'm using `false` for the animated flag.  This is on the Mapbox iOS SDK 3.0.1.

Not sure if this is related to https://github.com/mapbox/mapbox-gl-native/issues/2204.
Also, I've seen the zoom issue here: https://github.com/mapbox/mapbox-gl-native/issues/2946.
Thanks!

![screen shot 2016-01-14 at 6 12 32 pm](https://cloud.githubusercontent.com/assets/1591735/12340716/93978b8a-baea-11e5-9970-b0b5932b69f6.png)

**Comment by RomainQuidet** [comment]
Facing same issue here if a setZoomLevel follows a setCenterCoordinate. The zoomLevel is not correct.

**Comment by lilykaiser** [comment]
Closing due to ticket age. If this is still a problem, please re-open
