### ISSUE TITLE
Issue with numeric labels

### ISSUE THREAD

**Issue by jmcazaux** [mapbox/mapbox-gl-native#3566]
I have uploaded a shp dataset that contains decimal properties.

I have used this property in my style in a label combined with a text property as `{text_property} {decimal_property}`.

The label displays well in Mapbox Studio, but there are added decimal places in iOS (double conversion ?).

See attached images.
![decimal](https://cloud.githubusercontent.com/assets/2640502/12348312/44ff6ef8-bb66-11e5-8de0-4045599f0825.png)

![decimal_studio](https://cloud.githubusercontent.com/assets/2640502/12348322/5ac722f8-bb66-11e5-8635-388cba2a7b0b.png)

Hope this helps,
JM

**Comment by friedbunny** [comment]
Thanks for the report. This bug has been with us for quite some time — see #998. Until there's a fix, one workaround is to substitute strings for numeric properties.

**Comment by jmcazaux** [comment]
Unfortunately the issue is that I have no control over the data...

The initial issue has been opened for 9 month... You think it is going to be much longer ?

**Comment by friedbunny** [comment]
As a fairly uncommon bug with a known workaround, I would have to say that this is a low priority.

**Comment by kkaefer** [comment]
@jmcazaux Could you please provide me with a vector tile that contains these numbers? I'm interested in the binary representation of the number encoded in the vector tile. If possible, either post the link here, or mail to konstantin@mapbox.com

**Comment by jmcazaux** [comment]
@kkaefer I have corrected my "extraction" program in the meantime.

Let me go back a few commits, regenerate it and I'll mail it over to you.
