### ISSUE TITLE
Zoom based text anchor ignored

### ISSUE THREAD

**Issue by jmcazaux** [mapbox/mapbox-gl-native#3568]
Hi again,
in my style I have a label and I want the text anchor to change at a given zoom level.

That works well in studio, but is ignored in iOS.

Please see screen shots below, this is pretty self explanatory.

How it appears in the app...
![alignment](https://cloud.githubusercontent.com/assets/2640502/12348477/255c3fa2-bb68-11e5-9d48-649c3a5699f4.png)

How it appears in Studio...
![alignment_studio](https://cloud.githubusercontent.com/assets/2640502/12348512/6063ba3a-bb68-11e5-8445-11c28ed1f3e3.png)

How the label position is defined...
![untitled2](https://cloud.githubusercontent.com/assets/2640502/12348517/6fd7c9d4-bb68-11e5-9f8a-0a98a9be7870.png)

Thanks for your help,
JM

**Comment by jmcazaux** [comment]
I can confirm the behaviour is the same on Android (I assume this will be no surprise for the developers).

**Comment by jfirebaugh** [comment]
This was fixed by #6328.
