### ISSUE TITLE
Correctly handle errors in static rendering case

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#3569]
There are many different states in our loading/rendering pipeline, and it's generally designed for the continuous use case. As @jfirebaugh noted in https://github.com/mapbox/mapbox-gl-native/commit/0348c6933cd03f2c6aefbaf1ef227636bd809a7f#commitcomment-15461954, we should make sure that we're correctly aborting when we encounter errors, and add more tests for it.

It's unclear what we should do in certain situations, in particular around stale data and waiting for network connections. In the node.js rendering scenario, network blips are generally handled on the node.js side, but when we use a DefaultFileSource, what should we do in case of Server/Connection errors?
- Do not render when we get stale data
- Abort rendering when we get an error response for a particular resources (Style, TileJSON, glyphs, sprite JSON, sprite PNG, vector tiles, raster tiles)
- Stop all other requests when one request fails

/cc @mikemorris

**Comment by mikemorris** [comment]
> Abort rendering when we get an error response for a particular resources

This is generally the correct response for static rendering in Node.js, as in most cases we will be caching responses and failing early is better than getting malformed images stuck in an server- or client-side cache.

> Stop all other requests when one request fails

The main reason we don't do this in Node.js is (AFAIK) that we don't have communication between multiple requests from a single map. This could be a performance bump for invalid requests, but may be undesirable/unnecessary if we're caching the responses to these requests and expect the originating request to be retried shortly.

> Do not render when we get stale data

This seems unnecessary, as I don't think it would be possible for a stale response to contain data OLDER than what would already be in a cache. Settings cache headers that reflect how stale the underlying data is could alleviate concerns of cached stale renders blocking fresh renders.

**Comment by kkaefer** [comment]
> This seems unnecessary, as I don't think it would be possible for a stale response to contain data OLDER than what would already be in a cache.

You're thinking about the node.js use case where we use a dedicated Javascript-based filesource. However, you can also render static maps via the C++ API and use the built-in filesource. In that case, the built-in filesource can return stale data before it verified that the data is still fresh (and returns it again).

**Comment by jfirebaugh** [comment]
I think we're good here with the tests in https://github.com/mapbox/mapbox-gl-native/blob/ed29dfce436cb68c91fa2a1bdaa995124121c218/platform/node/test/js/request.test.js and https://github.com/mapbox/mapbox-gl-native/blob/ed29dfce436cb68c91fa2a1bdaa995124121c218/test/map/map.test.cpp.
