### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#3572]
[WebP](https://developers.google.com/speed/webp/?hl=en) is an image format employing both lossy and lossless compression. WebP is both efficient like JPEG and supports alpha like PNG.

We currently support WebP server-side, as well as [Mapbox GL JS](https://github.com/mapbox/mapbox-gl-js/issues/1725). [WebP 0.4.2](https://github.com/mapbox/mason/tree/webp-0.4.2) is the current version listed in our mason package manager. We should detect WebP support and use WebP tiles if the server advertises them.

Overall plan is:
- [x] Generate a mason branch for WebP 0.5.0 - latest stable version listed [here](https://storage.googleapis.com/downloads.webmproject.org/releases/webp/index.html).
- [x] Add WebP dependency in Mapbox GL native build system.
- [x] Provide support for WebP in `mbgl::decodeImage`.
- [ ] Modify sources for default styles in [Mapbox GL styles](https://github.com/mapbox/mapbox-gl-styles) to use WebP instead of PNG.

@mapbox/gl @mapbox/mobile

**Comment by brunoabinader** [comment]
WebP 0.5.0 mason branch is now live in https://github.com/mapbox/mason/tree/webp-0.5.0.

**Comment by brunoabinader** [comment]
#3599 provided support for Linux target. Branch https://github.com/mapbox/mapbox-gl-native/tree/webp-darwin provides WebP support for iOS and OS X, but is most probably going to land after the next Mapbox iOS SDK release. Android support is currently on-hold due to a build issue with libwebp for Android.

**Comment by roblabs** [comment]
A solution for `webp` on iOS using `WebP.framework`, https://github.com/roblabs/mapbox-gl-native#mapbox-gl--webp-for-ios

Thanks to @brunoabinader for notes and the `webp-darwin` branch
