### ISSUE TITLE
Add debug options to node bindings

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#3579]
Add a `debug` option to [`map.render`](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/node#rendering-a-map-tile) with the following sub-options, corresponding to [`MapDebugOptions`](https://github.com/mapbox/mapbox-gl-native/blob/a88e58ef3a90225fcfafca1efab996de6a827b72/include/mbgl/map/mode.hpp#L31-L37):

```
debug: {
  tileBorders: true/false,
  parseStatus: true/false,
  timestamps: true/false,
  collision: true/false
}
```

cc @mikemorris @bsudekum

**Comment by mikemorris** [comment]
:+1:
