### ISSUE TITLE
Misleading exemple on https://www.mapbox.com/android-sdk/

### ISSUE THREAD

**Issue by jmcazaux** [mapbox/mapbox-gl-native#3580]
The [first page of the Android SDK](https://www.mapbox.com/android-sdk/) documentation exhibit the following code bloc for the layout:

> <com.mapbox.mapboxsdk.views.MapView
> android:id="@+id/mapview"
> android:layout_width="fill_parent"
> android:layout_height="fill_parent"
> mapbox:accessToken=<access token>/>

The last line should actually read `mapbox:access_token=<access token>`.
It took me a while to figure out what was wrong.

**Comment by abhinav-adtechs** [comment]
It's written accurately here: https://www.mapbox.com/help/first-steps-android-sdk

Import this: xmlns:mapbox="http://schemas.android.com/apk/res-auto" to get auto-complete suggestions in the newer versions of Android Studio.

**Comment by tobrun** [comment]
It seems that someone has picked this up and replaced that line with an actual access token:

![screen shot 2016-01-18 at 09 18 04](https://cloud.githubusercontent.com/assets/2151639/12386264/76182bdc-bdc4-11e5-8349-02945d3f1767.png)

Closing for now, nothing actionable left to do.

**Comment by jmcazaux** [comment]
@tobrun and if you check it out I think you'll find out that this is your own token ;).

This is a bit surprising indeed...

**Comment by friedbunny** [comment]
If the user is logged in to their Mapbox account, we try to insert their access token wherever relevant.

**Comment by sirvon** [comment]
this issue doesnt address the REAL issue...
the documentation has this:

```java
...
mapbox:accessToken=<access token>
```

but it really should be this, no camelCase on the key:
```java
...
mapbox:access_token=<access token>
```
as @jmcazaux noted above

**Comment by tobrun** [comment]
@danswick could you pick this up?

**Comment by danswick** [comment]
This was fixed today. 

![image](https://cloud.githubusercontent.com/assets/2365503/13942886/95c610bc-efb4-11e5-86a8-93c52a7674cb.png)

**Comment by tobrun** [comment]
@danswick, you are my hero! 
thank you for taking that up
