### ISSUE TITLE
be more strict about line symbols that cross tile edges

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#3582]
The 395 shields are clipped:
![](https://cloud.githubusercontent.com/assets/1149913/12361706/a8c4c844-bb8d-11e5-91d5-f1df4cd653fe.png)

We should check if line symbols cross tile boundaries, and if they do, prevent them from being rendered.

**Comment by jfirebaugh** [comment]
This is specific to `Still` rendering mode, right? Isn't the right solution (the one that makes the behavior consistent with `Continuous`) to place and render the shields in _both_ tiles?

**Comment by ansis** [comment]
> Isn't the right solution (the one that makes the behavior consistent with Continuous) to place and render the shields in both tiles?

Unfortunately it isn't possible to place shields in the same location in both tiles using our vectortiles. The point positions for line labels are calculated by finding the points every __px along the line. Since the **same line could be clipped differently in both tiles**, it is pretty likely that these calculated points won't be the same in both tiles.

I think in mapnik maps we just avoid placing any line labels that cross boundaries. In the equivalent mapnik map the vertical stretch of 395 would have no shields, right @yhahn?

---

other ideas for fixing this:

A) If the vectortiles contained the length of the line that was clipped off of the beginning of the line, then that could be used to make the placement the same in both tiles. But that seems like a pretty huge thing to ask from the vectortiles.

B) It might be possible to fix this by changing how we turn lines into points. If we found all the points the line intersects with a tile edge and then started calculating point positions by moving in both directions then the positions would be the same. I think we'd need a larger data buffer for the road label vectortile layers though. I haven't thought carefully about this approach, but I think there would still be some broken cases.

C) Converting lines -> points before creating vector tiles for any critical layers like highway shields.

**Comment by yhahn** [comment]
> I think in mapnik maps we just avoid placing any line labels that cross boundaries. In the equivalent mapnik map the vertical stretch of 395 would have no shields, right @yhahn?

We rely on the style creator to make this decision, but it's really always the right decision given the limitations above.

All your **FutureIdeas** make sense but I think as a stopgap/triage/intermediate phase this approach would be :+1:

**Comment by jfirebaugh** [comment]
:+1: Thanks for the additional details. I understand enough to agree with your and @yhahn's assessment now.
