### ISSUE TITLE
mapbox 3.0 android sdk set minimum zoom and maximum zoom

### ISSUE THREAD

**Issue by kevincyh** [mapbox/mapbox-gl-native#3590]
Can i ask how am i able to limit the user being able to zoom too far from the map? i am currently using mapbox android sdk 3.0 "https://www.mapbox.com/android-sdk/". i recall from mapbox 0.7.4 it was able to set the minimum zoom via mapview.setMinimumZoom().

**Comment by tobrun** [comment]
@kevincyh this issue is similar to the one you created here #3591. I'm going to close this one down as well in favour of a new general one requesting this feature for both iOS and Android.

**Comment by tobrun** [comment]
@kevincyh I created https://github.com/mapbox/mapbox-gl-native/issues/3602 to follow op on this issue.
