### ISSUE TITLE
mapbox 3.0 android sdk set bounding box

### ISSUE THREAD

**Issue by kevincyh** [mapbox/mapbox-gl-native#3591]
Can i ask how am i able to set the bounding box for mapbox 3.0 android sdk. i recalled from version 0.7.4 it was to create a bounding box object and set into the mapview via setScrollableAreaLimit(BoundingBox boundingbox);

**Comment by tobrun** [comment]
@kevincyh 
Thank you for reaching out and reporting your problem. Notice that the `3.0.0` is very different from the `0.7.4` version. The former uses Vector tiles while the latter is using raster tiles. The big change required us to rebuild the SDK from scratch and some functionality might not yet have been ported.

For next action, I'm going to take a look at iOS and see if this is parity request or a feature request.

**Comment by kevincyh** [comment]
@tobrun 
Thanks for the information, i will be looking forward to up coming version :D.

**Comment by tobrun** [comment]
@kevincyh I created https://github.com/mapbox/mapbox-gl-native/issues/3602 to follow op on this issue.
