### ISSUE TITLE
[Android][Bug] Upgrade to OKHttp 3.0.1

### ISSUE THREAD

**Issue by mayardb** [mapbox/mapbox-gl-native#3608]
Related to "Upgrade to OKHttp 3.0 (#3461)".

Extract of the [Okhttp Change log](https://github.com/square/okhttp/blob/master/CHANGELOG.md) : 

> ## Version 3.0.1
>
> ### 2016-01-14
>
>Rollback OSGi support. This was causing library jars to include more classes than expected, which interfered with Gradle builds.

**Comment by tobrun** [comment]
Nice catch @mayardb!
Will pick this up as part of the release for `3.0.1` in #3537

**Comment by tobrun** [comment]
This landed with fa84283 on release branch mentioned above
