### ISSUE TITLE
GeoJSON overlay on map

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#3612]
Is there a way to display GeoJSON programmatically on top of a map? I see that there is support for adding GeoJSON layers to the style, but I'm not sure that's what I want.

My goal is to display realtime traffic and accidents on a Mapbox map.

**Comment by tobrun** [comment]
@picciano
Thank you for reaching out and requesting this feature. Support for GeoJSON is something we have been discussing but was not tracked anywhere in this repo. To properly track this, I created a feature request in #3630. FWIW we are already supporting GeoJSON as a part of our style spec natively but we are not exposing any APIs for our mobile end users just yet.

Closing this in favour of feature request in #3630.

**Comment by friedbunny** [comment]
You'll need to fetch and parse the GeoJSON yourself if you want to add it at runtime, but it's definitely possible: https://www.mapbox.com/ios-sdk/examples/line-geojson/

Another option is to use a [GeoJSON source in your GL style](https://www.mapbox.com/mapbox-gl-style-spec/#sources-geojson), which will be supported in iOS v3.1.0. If you're dealing with dynamic data, setting a low `expires` time on the served file should theoretically prompt us to reload it.

**Comment by picciano** [comment]
Thanks, that looks like two workable options until #3630 is ready.
+1 for that though!

Thanks
