### ISSUE TITLE
GeoJSON not removed from map

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#3613]
On the node platform, after creating a map with GeoJSON as a source, I'm seeing the shapes stick around for any subsequent creation.

![](https://cldup.com/jwYB9OwgTY.png)

The image above is a style **without** GeoJSON in the style. A handful of requests were made before this one, each time the next request has all GeoJSON sources from the previous requests. 

/cc @mikemorris @kkaefer

**Comment by mikemorris** [comment]
Determined that earlier requests were mutating the cached style object.
