### ISSUE TITLE
Rename MyX to UserX

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3628]
Currently we are prefixing everything related to user location with `My`.

Examples:
 - `setMyLocationEnabled`
 - `setMyBearinTrackingMode`
 - `setMyLocationTrackingMode`

From a developer perspective, this is strange, I have never referred the `user` as `my` in code.
With the `4.0.0` release we are breaking the API. This is something we could pick up at the same time.

Result:
 - `setUserLocationEnabled`
 - `setUserBearingTrackingMode`
 - `setUserLocationTrackingMode`

@bleege @zugaldia:
What are your thoughts on this?

**Comment by zugaldia** [comment]
@tobrun As strange as it sounds, isn't this naming convention something we're doing to keep [API compatibility](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html#setMyLocationEnabled(boolean)) with Google's?

**Comment by tobrun** [comment]
@zugaldia 
Yes it is true that Google exposes same naming but take a look at their javadoc. 
You can see they are struggling with this naming as well:

> While enabled and the location is available, the **my-location layer** continuously draws an indication of a **user's** current location and bearing, and displays UI controls that allow a user to interact with their location (for example, to enable or disable camera tracking of their location and bearing).

I'm all for having parity with Google expect when imho it doesn't make sense and it confuses me.

**Comment by bleege** [comment]
> I'm all for having parity with Google expect when imho it doesn't make sense and it confuses me.

Normally, I agree with this.  However, remember the big goal with using Google's API for naming is to make switching from Google to Mapbox easy for developers.  In other words having to make minimal changes to their existing code bases.

**Comment by tobrun** [comment]
The people have spoken, let's focus on parity for the `4.0.0` release!

**Comment by zugaldia** [comment]
@tobrun I hear you. At some point we should consider having our own object that does it The Right Way :)
