### ISSUE TITLE
Smooth animation in user tracking mode 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3629]
Currently on Android the UserLocationView animates from one location update to another.
You can clearly see the different location updates coming in and the it doesn't seem that the user is traveling at a constant speed. To properly support the idea of implementing navigation, we should streamline location updates/animation.

There are two ways to improve this user experience:
 - Entity interpolation
 - Dead reckoning

On iOS they have chosen to implement Entity interpolation which means that the user dot is actually one step behind the actual location, it is always trying to catch up.

@1ec5 @bleege @zugaldia

**Comment by 1ec5** [comment]
> On iOS they have chosen to implement Entity interpolation

#3589 and #1582

**Comment by bleege** [comment]
This is going to be a _very useful_ thing to have.  @tobrun do you want to run at this after the dust settles a bit more after MapboxMap was introduced in #3145.

**Comment by tobrun** [comment]
The first iteration landed with https://github.com/mapbox/mapbox-gl-native/pull/4695

The following items should be resolved to close this issue:
 - [ ] While in follow location mode, we are using the the easeTo animate the map under the user location view. The easeTo method uses an easing interpolator and this makes the animation a bit jumpy. Having a linear interpolator variant would resolve this. 
 - [ ] While in non follow location mode. The user location view  is animated with the Android animator framework. The animator framework is time based which makes an animation to have a start and end state. This currently results in a very jumpy animation at high zoom levels, we should probably look in alternative ways of doing this outside the animator framework or write a custom animator from scratch.

**Comment by 1ec5** [comment]
> The easeTo method uses an easing interpolator and this makes the animation a bit jumpy. Having a linear interpolator variant would resolve this.

You’ll want to set [`easing`](https://github.com/mapbox/mapbox-gl-native/blob/d9a2a845dec1697f6b68b6aa4c4a49b0c2738329/include/mbgl/map/camera.hpp#L59) on `easeTo()`’s optional `AnimationOptions` parameter. See #3589 for more details.

**Comment by tobrun** [comment]
@1ec5 thank you for the always helpfull comments 🙇

**Comment by tobrun** [comment]
I have been looking into adding an own supplied UnitBezier as:

```cpp
animationOptions.easing.emplace(mbgl::util::UnitBezier(0, 0, 1, 1));
```

Which matches the Linear interpolator found in the [Apple docs](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/CAMediaTimingFunction_class/#//apple_ref/doc/constant_group/Predefined_Timing_Functions).


After adding this it seems the easing interpolation is still there. You can see a clear difference in acceleration at start and deceleration at end. See this clip [here](https://www.dropbox.com/s/4homib8mgvt8d71/device-2016-04-26-230228.mp4?dl=0).

@1ec5 any hints on what I'm doing wrong here?

**Comment by 1ec5** [comment]
You should just be able to assign the `UnitBezier` to that field. But I’m not sure why it isn’t working for you regardless. That recording makes it look like the custom easing is being ignored.

**Comment by tobrun** [comment]
Revisiting this and this time around I was able to remove interpolation. You can see this in action [here](https://www.dropbox.com/s/p24l3sfkxuing1d/device-2016-05-26-130004.mp4?dl=0). This video was taken on a high zoomlevel were easing used to be very visible.

**Comment by tobrun** [comment]
I'm going to PR the smooth animation for tracking mode separately from the non-tracking. In code these are completely different things and I want to include 49aae67 in the next SNAPSHOT.

**Comment by tobrun** [comment]
I was able to get the non-tracking to work as well:

![ezgif com-video-to-gif 25](https://cloud.githubusercontent.com/assets/2151639/15575289/43e1ffdc-2352-11e6-9363-c07e1538ed0d.gif)
![ezgif com-video-to-gif 24](https://cloud.githubusercontent.com/assets/2151639/15575290/43f6626a-2352-11e6-9abc-d1b173a80ea5.gif)

**Comment by tobrun** [comment]
With above in place, I'm going to cleanup the `MyLocationView` class a bit and PR it.
