### ISSUE TITLE
`make linux` on OS X should build with http=curl, not http=nsurl

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#3634]

**Comment by brunoabinader** [comment]
Related: #3821

**Comment by kkaefer** [comment]
As per #3821, `linux` here refers to the frontend application (soon to be renamed `glfw`), and not to `platform-linux`. In line with this, I think the target name after `make` shouldn't imply components different from the default on the current platform. If you want to specify other components, you'll be able to build with `make glfw HTTP=curl`.
