### ISSUE TITLE
getAnnotationsInBounds not returning in bounds annotations

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3643]
#### Prior
In the Android release 3.1.0 we made the touch target of touch event smaller #3156. 

![2d48ad00-be8c-11e5-94a4-57b2f20b8cd8](https://cloud.githubusercontent.com/assets/2151639/12476275/8adbeda4-c028-11e5-82e1-ea93ac5717ab.png)

This was needed to be able to properly select annotations when they are just side by side. 

![screen shot 2016-01-21 at 10 22 47](https://cloud.githubusercontent.com/assets/2151639/12476340/f61f570e-c028-11e5-833b-f001a524f30a.png)

See the result from that issue [here](https://www.dropbox.com/s/ycucb7t92c7nu1s/device-2016-01-19-101337.mp4?dl=0&preview=device-2016-01-19-101337.mp4).

#### Issue
While making touch target smaller was great for selecting annotations side by side. It did make selecting annotations in general more difficult. I believe the source of this problem can be found in C++ implementation of `getAnnotationsInBounds`. 

#### Visual
In next screenshot I visualised the `BoundingBox` passed to the `getAnnotationsInBounds`: 

![screen shot 2016-01-21 at 10 39 54](https://cloud.githubusercontent.com/assets/2151639/12476734/768e4830-c02b-11e5-8590-62ee33b6585f.png)

In that case an `InfoWindow` is not shown because `getAnnotationsInBounds` returns an empty list.

More examples shown in this [clip](https://www.dropbox.com/s/3hg9ju7glc02613/device-2016-01-21-095454.mp4?dl=0).

#### Problem
I'm currently not sure where to pinpoint this on:
 -  Is the C++ code not taking the size of the Marker image in account? only the base of the marker?
 - Is the C++ code not taking in account the current zoom level when determining?
 - Should the java code calculate a different bounding box based on zoom level?

**Comment by tobrun** [comment]
Let's take a trip down to C++ land and figure this out:

 - `getAnnotationsInBounds()` is calling `nativeGetAnnotationsInBounds()` in jni.cpp
 - `nativeGetAnnotationsInBounds()` is calling `getMap().getPointAnnotationsInBounds()` on native_map_view.cpp / map.cpp
 - `getPointsAnnotationsInBounds()` is calling `getPointAnnotationsInBounds` in annotation_manager.cpp

```cpp
AnnotationIDs AnnotationManager::getPointAnnotationsInBounds(const LatLngBounds& bounds) const {
    AnnotationIDs result;

    pointTree.query(boost::geometry::index::intersects(bounds),
        boost::make_function_output_iterator([&](const auto& val){
            result.push_back(val->id);
        }));

    return result;
}
```

**Comment by tobrun** [comment]
As mentioned in the follow up ticket, we should look into fixing this at the Android SDK level by introducing appropriate padding. We used to do fixed padding but that is not the way iOS or OS X are handling this.

**Comment by tobrun** [comment]
To resolve above I will calculate the average width and average height of a marker icon and take that in account when calculation the touch area.

**Comment by tobrun** [comment]
I initially wanted to manage this in IconFactory, but this will indicate the average will be used in all maps in one application. The average should only be used per map.

**Comment by tobrun** [comment]
I'm starting to understand why I was not really able to get the same ux with the default marker vs custom:

<img width="441" alt="screen shot 2016-03-05 at 11 01 32" src="https://cloud.githubusercontent.com/assets/2151639/13548594/bc2739f2-e2c1-11e5-85f5-4b7ca2aa43ad.png">

This should be changed to a `normal` image as a end developer would also use.

**Comment by tobrun** [comment]
After changing the default marker image, the markers are placed to low on the map.
To workaround this I used `setTopOffsetPixels` with the height of the marker.
In the same way an end developer would do.

**Comment by tobrun** [comment]
It seems I'm currently not able to use setTopOffsetPixels.. this is one the adjustments needed for dynamic marker support.

**Comment by tobrun** [comment]
Since this fits more in the story of `4.1.0`, I'm going to postpone this.

**Comment by vfaSonnt** [comment]
Hope this will be released soon.

**Comment by tobrun** [comment]
The idea here is to add a fixed amount of padding + an average padding calculated from all the different icons used. For the default icon (that has extra whitespace to work around not having the anchor method from #2916) I'm just subtracting the whitespace from bit before calculating the average padding (iOS is doing the same).

**Comment by tobrun** [comment]
The calculated padding in action: 
https://www.dropbox.com/s/f6do1utnqdad4sm/device-2016-04-06-121147.mp4?dl=0
