### ISSUE TITLE
PolylineOptions disappear at unsupported zoom levels

### ISSUE THREAD

**Issue by franckt** [mapbox/mapbox-gl-native#3644]
Hi, 
I currently diplays PolylineOptions on Android with hardcoded max zoom level set to 22 (#509)
the polyline displays at zoom 18, 19, not at 20, not at 21, but appears again at 22,
Any idea about that ?

**Comment by tobrun** [comment]
Linking #4168

**Comment by brunoabinader** [comment]
This is now handled in #5138.
