### ISSUE TITLE
Enable HTTP pipelining on iOS

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#3647]
The default is set to `NO`

/cc @1ec5

**Comment by kkaefer** [comment]
This might explain why cURL is faster than NSURL*

**Comment by jfirebaugh** [comment]
It sounds to me like HTTP pipelining is too new/dangerous to use. If the server you're connecting to (or proxy you're connecting through) doesn't implement it, you can get incorrect results without warning.

http://stackoverflow.com/questions/14810890/what-are-the-disadvantages-of-using-http-pipelining

**Comment by kkaefer** [comment]
Interesting, I thought it was accepted standard practice, but apparently not.

**Comment by friedbunny** [comment]
iOS 9 and OkHTTP both have HTTP/2 enabled by default, which implements multiplexing. When Mapbox content servers start supporting HTTP/2, we should get it for free.
