### ISSUE TITLE
Move inflate/deflate in FileSource to separate thread

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#3648]
We're currently calling `inflate`/`deflate` synchronously in the SQLiteCache. Instead, we should reserve this cache for SQLite operations exclusively and do other time-consuming tasks in a separate thread.

Once this is asynchronous, we can no longer guarantee an order of `get`/`put` operations, since compress tasks might run in parallel and can take more or less time compared to other cache tasks.

**Comment by jfirebaugh** [comment]
What's the rationale?

**Comment by kkaefer** [comment]
It takes some time to decompress/compress the data. During this time, we can't do I/O with the the database.

**Comment by jfirebaugh** [comment]
If we do #3722, we can't have asynchronicity within the database code. Instead, we should do #3886.
