### ISSUE TITLE
In mapbox SDK 0.7.4 for loading local map we use the setTileSource  ,as like which method is used to load local map in mapbox android SDK 0.7.4

### ISSUE THREAD

**Issue by vijay765** [mapbox/mapbox-gl-native#3651]
Sorry for late reply , as u know the solution please suggest the answer

**Comment by jfirebaugh** [comment]
Mapbox SDK 0.7.4 is deprecated, and this repository is for newer versions of the SDK.

For support questions please contact us here: https://www.mapbox.com/help/
