### ISSUE TITLE
Fire events when map finishes loading

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3653]
The Android SDK doesn’t appear to respond to a notification of `mbgl::MapChangeDidFinishRenderingMapFullyRendered`. This would be useful in order for an application to perform an action only once all the visible tiles have finished loading and rendering. This notification is supported on iOS, other than in the case where one of the tiles failed to load for some reason (#1804).

/cc @bleege @danswick

**Comment by tobrun** [comment]
GoogleMaps exposes  `OnMapLoadedCallback`:
>	Callback interface for when the map has finished rendering.

**Comment by tobrun** [comment]
Ignore my comment above, still needs to be implemented in `OnMapOnChangeListener`

**Comment by fauger** [comment]
Hello,

Any news about this issue ?

**Comment by tobrun** [comment]
This was implemented a while ago: 

```java
        /**
     * This event is triggered when the map is fully rendered.
     * <p>
     * Register to {@link MapChange} events with {@link MapView#addOnMapChangedListener(OnMapChangedListener)}.
     * </p>
     *
     * @see MapChange
     * @see MapView.OnMapChangedListener
     */
    public static final int DID_FINISH_RENDERING_MAP_FULLY_RENDERED = 13;
```

and is available in latest stable. Closing.
