### ISSUE TITLE
Static framework installation fails due to codesigning error

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3656]
If you drag and drop the official 3.0.1 static framework into a project, then build for a device, the application fails to install and run on a device because of a codesigning error:

```
streaming_zip_conduit[261] <Warning>: __dispatch_source_read_socket_block_invoke:296: Failed to install application at file:///var/mobile/Media/PublicStaging/manualestframework.app/ : Error Domain=LaunchServicesError Code=0 "(null)" UserInfo={Error=ApplicationVerificationFailed, ErrorDetail=-402620415, ErrorDescription=Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.vOdKnt/extracted/manualestframework.app/Frameworks/Mapbox.framework : 0xe8008001 (An unknown error has occurred.)}
```

The problem seems to be that not all of [these variables](https://github.com/mapbox/mapbox-gl-native/blob/874ff24d8cda6be1a3463b9614862ec186db6f40/ios/framework/Info.plist#L8) are getting replaced in the Info.plist that we manually generate for the static framework.

/cc @friedbunny

**Comment by silviokuehn** [comment]
**Still getting this error**

I have a brandnew created project here with iOS 7 as target. I added mapbox 3.1.0 manually as it is descripted in the "how to install" for iOS 7 apps. When launching app on emulator everything is fine, but launching on a device (iPhone 5C with iOS8) will abort with "The application does not have a valid signature". When I remove mapbox framework from "embedded frameworks", it works on device, too.

**Comment by 1ec5** [comment]
@silviokuehn, I’m unable to reproduce the issue you’re describing on an iPhone 6 running iOS 9.2. What kind of provisioning profile or team are you building against? When I built with the free “Personal Team” provisioning profile and “iOS Developer” code signing identity, for example, I had to open Settings, go to General, then Profiles & Device Management, and trust my account before I could run the application.

**Comment by silviokuehn** [comment]
At least, that could be a reason. I have "iOS Developer" as code signing identity, but I did not choose any team because at the moment this is just a small (new created) test project to see how mapbox will work with iOS 7 target. First, the app is running on a device even without a team - but after adding mapbox it does not work. So I'm wondering why this requirement does appear first with adding mapbox.

On the other side I have created another test project with target iOS 8 and including mapbox by Podfile (CocoaPods) which is not possible on iOS7. Here everything is fine and the app is working on a device without a specified team but also with mapbox.

**Comment by lmengozzi** [comment]
I'm having the same issue as @silviokuehn here, using static Mapbox framework and on iOS 8. Installing through any means logs the following on the device:

```
... {LibMISErrorNumber=-402620391, LegacyErrorString=ApplicationVerificationFailed, FunctionName=-[MICodeSigningVerifier performValidationWithError:], NSLocalizedDescription=Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.WQYQ07/extracted/MapsquareSDKTestApp.app/Frameworks/Mapbox.framework identifier = com.mapbox.sdk.ios type = Framework> : 0xe8008019 (Application signature not valid), SourceFileLine=192}
```

Installation works fine without embedding the framework, using the dynamic framework, or using other versions of iOS.

**Comment by 1ec5** [comment]
One workaround is to replace the static framework with the static library we build for Fabric users. The current version of the static library is [3.1.3](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.1.3-fabric.1). Unlike the static framework, the static library should go in “Linked Frameworks and Libraries”, _not_ “Embedded Binaries”.

**Comment by ultranano** [comment]
Hi @1ec5 
Sorry but i try this morning this workaround and doesn't work

**Comment by 1ec5** [comment]
I forgot to mention that 3.1.3 comes with an extra step (since it wasn’t originally intended for manual installation): there’s a Mapbox.bundle inside the Mapbox.framework. You need to add that to your project’s Copy Resource Files build phase.

**Comment by ultranano** [comment]
OK Thanks @1ec5 now seems works fine!
Of course it's better to have a more easy solutions to integrate it.
Best!

**Comment by 1ec5** [comment]
This will be fixed by #4455.

**Comment by boundsj** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/4455

**Comment by Xgamefactory** [comment]
we get same problem on xcode 9
solution was to import framework with + sign on build phase **not drag and drop**
