### ISSUE TITLE
[Question] Is this possible to match the MGL view point in another opengl/webgl view? 

### ISSUE THREAD

**Issue by dagatsoin** [mapbox/mapbox-gl-native#3668]
This is not an issue or maybe a lack of information about the rendering design. (Or I miss some docs?)

My goal is to put 3D models on the map. I know it is not possible to draw 3D objects for now in Mapbox.

I plan to use another view on top of the MGLView. I will start with a cordova wkwebview + webgl canvas for cross plateform concern.

This 3D canvas will have a camera that I need to match to the MGLView.

I would like to know what should be a good starting point to do this with mapboxgl design in mind.

**Comment by jfirebaugh** [comment]
Unfortunately this isn't something that's possible with the iOS SDK at this time.

**Comment by 1ec5** [comment]
To clarify, it isn't possible to place 3D models directly in the map, to have the Mapbox iOS SDK render it for you. If you wanted to synchronize some other view with the map view, that would be a pretty manual affair, but take a look at the documentation for MGLMapCamera as well as the geometric conversion methods in MGLMapView; maybe you could piece it together with those APIs.

**Comment by dagatsoin** [comment]
@1ec5 It is exactly my point. I am aware that mapboxgl can't render 3D objects. It is for this reason that I need an interface to retrieve the global space and camera information to reproduce a 3D overlay with another view (wkwebview + tree.js or native gl View). Could you plz leave this issue opened until I figure it out?

**Comment by dagatsoin** [comment]
Are you talking about the doc in the source code or somewhere else?

**Comment by 1ec5** [comment]
Yes, I’m referring to the documentation in the source code, which is also [available online](https://www.mapbox.com/ios-sdk/api/3.1.2/). Specifically, take a look at:

* [`-[MGLMapViewDelegate mapViewRegionIsChanging:]`](https://www.mapbox.com/ios-sdk/api/3.1.2/Protocols/MGLMapViewDelegate.html#/c:objc%28pl%29MGLMapViewDelegate%28im%29mapViewRegionIsChanging:)
* [`-[MGLMapView camera]`](https://www.mapbox.com/ios-sdk/api/3.1.2/Classes/MGLMapView.html#/c:objc%28cs%29MGLMapView%28py%29camera)
* [MGLMapCamera Class Reference](https://www.mapbox.com/ios-sdk/api/3.1.2/Classes/MGLMapCamera.html)

**Comment by dagatsoin** [comment]
Thx you, this is a good starting point.

**Comment by suzukieng** [comment]
Hi @dagatsoin. I recently did something similar to what you describe using MapBox and a transparent overlay view for drawing 3D objects on top of the map. I blogged about it [here](https://blog.classycode.com/how-to-write-a-pokémon-go-clone-for-ios-edf1cf1cf5ce#.f1wkn9ga6).
