### ISSUE TITLE
MapBox Black screen while capturing screen shot(Programmatically)

### ISSUE THREAD

**Issue by MavyaSoni** [mapbox/mapbox-gl-native#3677]

**Comment by MavyaSoni** [comment]
![1](https://cloud.githubusercontent.com/assets/16849751/12529388/f070fb84-c1d9-11e5-9b45-f3655dde9f8c.jpg)


MapBox shows black screen while capturing screenshot. Please refer image.

**Comment by MavyaSoni** [comment]
![1](https://cloud.githubusercontent.com/assets/16849751/12529406/8c34cb22-c1da-11e5-8d59-051ce9cfef7e.jpg)

MapBox shows black screen while capturing screenshot. Please refer image

**Comment by MihirPal** [comment]
Ohh same problem with me.
Is there any approach to solve this issue?

**Comment by tobrun** [comment]
Thank you for reaching out and reporting your problem. We also faced this problem while taking screenshots in espresso test cases. @zugaldia workaround this by creating this [ScreenShotUtil](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/utils/ScreenshotUtil.java).  Currently that code is not part of the SDK, but we are planning to include this for a snapshot API as documented in #3466.

**Comment by MavyaSoni** [comment]
Thanks for replay.
We have implemented as you suggested. We are getting screenshot with out info window. We are capturing screenshot with info window.

<b> Screenshot is captured by as you suggested. </b>
![4](https://cloud.githubusercontent.com/assets/16849751/12545536/39449d80-c369-11e5-89b6-724157af1605.jpg)

<b>Actual screenshot taken by device default screen shot option</b>

![3](https://cloud.githubusercontent.com/assets/16849751/12545554/597d68b6-c369-11e5-8f40-f7d02ba9fc61.png)

**Comment by tobrun** [comment]
Great that you were able to use some code from snippet. 
Reach out if you have other questions!

**Comment by MavyaSoni** [comment]
@tobrun  i guess you misunderstood. Code is only capturing screen shot of map with pins. But if my info window for some pin is open it is not coming in that result screen shot. 

i.e Info window is missing from screen shot.

**Comment by tobrun** [comment]
@MavyaSoni Yes indeed I misunderstood that you were able to fix it.

Current issue is a logical since that snippet is only capturing from TextureView as seen [here](
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/utils/ScreenshotUtil.java#L56)
You just need to capture your other views as well.
