### ISSUE TITLE
Drawing Circle For Geo Fencing

### ISSUE THREAD

**Issue by kevincyh** [mapbox/mapbox-gl-native#3682]
Is it possible to draw a circle at a point in Android Mapbox SDK 3.1.0 ? Like radius from a point ?

**Comment by 1ec5** [comment]
Per #2167, a circle marker type hasn’t been implemented at the cross-platform level yet, but you can approximate a circle with a many-sided polygon. There’s an example implementation for iOS in https://github.com/mapbox/mapbox-gl-native/issues/2167#issuecomment-169265375; you may be able to use the same approach on Android.

**Comment by kevincyh** [comment]
@1ec5  Thank it was a great help

**Comment by YogarajRajendran** [comment]
Hi All,
how to find when a point on map enters a polygon(circle) and when a point on map leaves a polygon(circle). I need to implement geofencing feature in IOS app. how to achieve this using mapbox ios sdk
Any help would be greatly appreciated.

**Comment by 1ec5** [comment]
Hi @YogarajRajendran, despite the title of this issue, it was originally a request for a way to draw a circle on the map that corresponds to a geofence, not to actually implement geofencing.

The Core Location framework has a CLCircularRegion class that you can use to check whether a location is within a certain radius of a center location. For example, if user location tracking is enabled in your MGLMapView, your MGLMapViewDelegate can respond to `-mapView:didUpdateUserLocation:` by checking whether a CLCircularRegion you define contains the user’s new location.

Note that the Mapbox iOS SDK isn’t a general-purpose geofencing library. If you need a geofence to work even when the map isn’t following the user, or when a map isn’t visible on the screen, you can set up your own CLLocationManager or use EventKit or a third-party geofencing library.

**Comment by bilthon** [comment]
So what happened to this issue? seems like a pretty important functionality. Do I have to create a polygon?

**Comment by 1ec5** [comment]
@bilthon, yes, currently the workaround is to create a polygon. If you’re writing your application in Swift, [turf-swift](https://github.com/mapbox/turf-swift)’s `coordinate(at:facing:)` method would come in handy:

https://github.com/mapbox/turf-swift/blob/857e2e8060678ef4a7a9169d4971b0788fdffc37/Turf/Turf.swift#L36

#2167 tracks adding a proper circle shape type.
