### ISSUE TITLE
Rotation, Direction, Heading or Bearing?

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3688]
Currently the Android SDK uses these 4 words to describe the same thing.

For example this code snippet contains all these synonyms:

![screen shot 2016-01-25 at 11 24 12](https://cloud.githubusercontent.com/assets/2151639/12548384/329f2d32-c356-11e5-8a74-805a14a43734.png)

We should choose a name for it and use it consistently.

cc @bleege @zugaldia

**Comment by 1ec5** [comment]
FYI, on the iOS side, we’ve generally made the following distinctions, for consistency with Core Location and MapKit:

* rotation — the act of rotating using two fingers
* direction — degrees clockwise from due north in 2D space
* heading — degrees clockwise from due north in 3D space

And these are the terms used by mbgl:

* rotation — act of rotating by any means
* angle — radians counterclockwise from due north
* bearing — degrees clockwise from due north

That said, feel free to use whatever terminology feels most natural on Android.

**Comment by tobrun** [comment]
@1ec5 that is great info to have!

**Comment by bleege** [comment]
This isn't too surprising as different parts of the stack were developed by different people with different terms.  Basically the telephone game gone amok.

> That said, feel free to use whatever terminology feels most natural on Android.

This is also my recommendation.  The Android binding API and JavaDocs should line up with Google's Android Maps API and that should be the focus.  This means that we'll keep the "translation layer" within the Android methods themselves.  ie...

```java
// Translation Layer concept

// getDirection() aligns with Google Maps
public double getDirection() {
  // getBearing() aligns with CoreGL
  return -mNativeMapView.getBearing();
}
```

**Comment by tobrun** [comment]
@bleege agreed!
