### ISSUE TITLE
[Android] [HTTP] Request with response code = 304

### ISSUE THREAD

**Issue by mayardb** [mapbox/mapbox-gl-native#3689]
Hello MapBox Team!

I just noticed that I get lots of logs even if I do not interact with the `MapView`:
````
01-25 15:20:34.794 D/com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest: [HTTP] Request with response code = 304: Not Modified
```


Do you have any idea why I am getting so much requests ?

**Comment by tobrun** [comment]
@mayardb thank you for reaching out about this problem.
This issue is also being metioned in #3667.

**Comment by mayardb** [comment]
Since it is already mentioned, I close this issue not to duplicate.

Thank you.
