### ISSUE TITLE
[Android] Crash when using UserLocationView

### ISSUE THREAD

**Issue by mayardb** [mapbox/mapbox-gl-native#3690]
OS : 4.4.2
Device : Galaxy S4 mini GT-i9195
From a fork of `master`.

On the test sample application, right after the `UserLocationView` prompts on screen (after `FusedLocationAPI` reaches a Location), the application crashes :

```
01-25 16:29:36.605 23129-23129/com.mapbox.mapboxsdk.testapp A/libc: Fatal signal 11 (SIGSEGV) at 0x00000004 (code=1), thread 23129 (pboxsdk.testapp)
```

**Comment by tobrun** [comment]
@mayardb 
I wanted to look into this but I'm unable to find that fork. Without seeing the code or knowing anything about the fork. It's impossible to resolve this issue. Are you seeing this behaviour on `master` as well?

**Comment by tobrun** [comment]
One crash we resolved in latest weeks related to UserLocationView https://github.com/mapbox/mapbox-gl-native/commit/1738a9e200f20c4b382271376cd69a7b0d53ed7c

**Comment by mayardb** [comment]
The fork is currently pointing to the `head` of `master`.

This is not crashing anymore with the last commits.
