### ISSUE TITLE
java.lang.NullPointerException: String cannot be null.

### ISSUE THREAD

**Issue by webliupeng** [mapbox/mapbox-gl-native#3692]
I got this exception

>`java.lang.NullPointerException: String cannot be null.
>	at com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest.nativeOnFailure(Native Method)
>	at com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest.onFailure(SourceFile:122)
>	at com.mapbox.mapboxsdk.http.HTTPContext$HTTPRequest.onResponse(SourceFile:99)
>	at a.aq$b.f(SourceFile:133)
>	at a.a.k.run(SourceFile:33)
>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>	at java.lang.Thread.run(Thread.java:818)`

I see, some one has commited this issue. but this issue is very serious to me. cause our APP is a ski tracker .I need use mapbox to display users' location and tracks.if user have unstable network this exception maybe occur.So . is there a solution can resolve this issue? thanks a lot

**Comment by jfirebaugh** [comment]
What version of the Android SDK are you using?

**Comment by jfirebaugh** [comment]
It looks like `jstring message` can be null [here](https://github.com/mapbox/mapbox-gl-native/blob/a877b9b192fb199b8ec6379551b3fb81e13d673d/platform/android/src/http_request_android.cpp#L224-L224), causing `std_string_from_jstring` to throw [here](https://github.com/mapbox/mapbox-gl-native/blob/d34f8eb674b9753c47616f37ae88ff7a02f61ba0/platform/android/src/jni.cpp#L177-L177).

cc @tobrun

**Comment by tobrun** [comment]
@jfirebaugh may we just ignore that occurrence?

**Comment by webliupeng** [comment]
I using the Android SDK 3.1.0

**Comment by webliupeng** [comment]
@jfirebaugh I using the Android SDK 3.1.0

**Comment by tobrun** [comment]
Going to patch this

**Comment by webliupeng** [comment]
@tobrun patch in 4.0?

**Comment by tobrun** [comment]
@webliupeng yes, this should be fixed with 4.0.0.  I might discuss releasing a more stable Android SDK 3.1.1 first. Reasons behind this: multiple fixes have landed + the features in 4.0.0 will break the api completely.

**Comment by webliupeng** [comment]
@tobrun thanks a lot. I'm waiting for new version

**Comment by tobrun** [comment]
This will land with the 3.2.0 release

**Comment by bleege** [comment]
This landed in PR #3719.

**Comment by webliupeng** [comment]
@tobrun @batpad  thank you guys . I'm going to update.
