### ISSUE TITLE
[bug][android] Vector tiles not correctly order of layers on CPU K3V2 (Hi3620)

### ISSUE THREAD

**Issue by dan4ik95dv** [mapbox/mapbox-gl-native#3693]
Hi, my device (Huawei p2-6011) based on K3V2 (Hi3620). Vector tiles drawing is not correctly. Layer background over on layer streets etc..
I think that your renderer engine not correctly processing blend layouts on my GPU "Vivante GC4000". 

![screenshot_2016-01-26-12-52-08](https://cloud.githubusercontent.com/assets/7045168/12572397/37e7e890-c42f-11e5-9004-7da6598a7ed0.png)
![screenshot_2016-01-26-12-53-00](https://cloud.githubusercontent.com/assets/7045168/12572396/37e722ca-c42f-11e5-8c8b-8592543d424c.png)
![screenshot_2016-01-26-12-53-31](https://cloud.githubusercontent.com/assets/7045168/12572398/37eaa512-c42f-11e5-95ee-6938c963f0b7.png)
![screenshot_2016-01-26-14-39-33](https://cloud.githubusercontent.com/assets/7045168/12572674/a6f52b96-c432-11e5-960e-e9b319935123.png)

Thanks

**Comment by daniilr** [comment]
++

**Comment by tobrun** [comment]
@dan4ik95dv @daniilr are you still seeing this with newer versions of the SDK?

**Comment by cammace** [comment]
Not enough context to help debug, closing ticket. For future issues or if this issue is still occurring feel free to either comment on this issue or contact us using [Mapbox's contact page](https://www.mapbox.com/contact/).

**Comment by AlexeyIke** [comment]
Hi, issue still on latest Mapbox-demo from google play. Video of  map render  with bugs  - https://drive.google.com/open?id=0B3U64R1No4k8enZNdE04R0F2dmc

**Comment by cammace** [comment]
@AlexeyIke This looks like a similar issue to https://github.com/mapbox/mapbox-gl-native/issues/5443.

**Comment by AlexeyIke** [comment]
Yes, very similar. But i see it only on huawai devices like Huawei p2 and  based on K3V2 (Hi3620) processor with GPU "Vivante GC4000" (no that information in #5443.). If fix of #5443  helps, then well.
