### ISSUE TITLE
No info window on Android

### ISSUE THREAD

**Issue by esisa** [mapbox/mapbox-gl-native#3694]
Is there any way to not show the info window when tapping a marker? I have my own custom info window, but I cannot find a way to turn off the default one.

**Comment by tobrun** [comment]
You can define you own `OnMarkerClickListener` and return true to indicate that click has been handled.
```java         
        mMapView.setOnMarkerClickListener(new MapboxMap.OnMarkerClickListener() {
            @Override
            public boolean onMarkerClick(@NonNull Marker marker) {
                // do nothing 
                return true;
            }
        });
```

That code will override the default behaviour as seen in `MapView`:

```java
        boolean handledDefaultClick = false;
        if (mOnMarkerClickListener != null) {
            // end developer has provided a custom click listener
            handledDefaultClick = mOnMarkerClickListener.onMarkerClick(marker);
        }

        if (!handledDefaultClick) {
            if (isInfoWindowValidForMarker(marker)) {
                mInfoWindows.add(marker.showInfoWindow(this));
            }
        }
```

Is this what you are looking for?

**Comment by tobrun** [comment]
@esisa 
Just rereading this:
> I have my own custom info window

Are you using the InfoWindowAdapter?

**Comment by esisa** [comment]
Ok, thanks @tobrun! Should have spotted that one I guess. 

No, I am not using InfoWindowAdapter, just some custom view instead.
