### ISSUE TITLE
Consider releasing a 3.1.1 Android version

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3696]
Before merging #3500 back to master, I think we should discuss releasing a stability update to our 3.1.0 version. Many users are currently using our 4.0.0 SNAPSHOT to bypass some problems with 3.1.0.
 
Eg. I have had to indicate the following multiple times to users here on Github:
> Yes that fix will land with 4.0.0, you can use the SNAPSHOT to retest this.

Merging #3500 will completely break their code and without adapting their code they will have no proper version to develop against . Also the API can still change a lot over different versions of the SNAPSHOT. IMHO it's our responsibility to provide a stable version before breaking the API.

Some Important fixes that come to mind since release:
 - Fixes to marker icons
 - Improved JPEG library
 - Fixes to LocationTracking and BearingTracking
 - Bad internet connection crash
 - ...

I'm not indicating to releasing a 3.1.1 right now, but we should make a release branch before merging.

@bleege @zugaldia 
What are your thoughts on this?

**Comment by bleege** [comment]
Discussed internally this morning with @tobrun @zugaldia and we've decided that we'll release a `3.2.0` to get these fixes out the door officially.  We'll also look to land #3627 / #3687 for content insets as part of this.

I'll create a `3.2.0` release ticket when we're ready to go.  :rocket:
