### ISSUE TITLE
Map content insets should offset compass, logo, attribution beyond layout guides

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#3697]
With current version the map insets on iOS work (user center is moved correctly) but the compass view is not moved inside the insets.
Same with the mapbox logo.
Insets are mostly used because another view hides temporally a part of the map. Users still want to see its compass.

**Comment by 1ec5** [comment]
> Insets are mostly used because another view hides temporally a part of the map. Users still want to see its compass.

I agree – good idea. Currently, `-[MGLMapView updateConstraints]` only [respects the top and bottom layout guides](https://github.com/mapbox/mapbox-gl-native/blob/9418f9a9870dc5b23c150fa9dc017e101582db30/platform/ios/src/MGLMapView.mm#L631).

**Comment by RomainQuidet** [comment]
Working on it

**Comment by RomainQuidet** [comment]
PL #4219 done, a little bit more than compass only, I also added the logo + attribution as all needs to be displayed on manual insets.
