### ISSUE TITLE
Heading tracking mode sometimes fails to rotate map after device rotation

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#3710]
Haven't pinned down exact reproduction steps, but flipping through the tracking modes in iosapp and rotating the device back-and-forth, landscape-portrait will sometimes result in this behavior in heading tracking mode:

![flashlight](https://cloud.githubusercontent.com/assets/1198851/12623287/660556e0-c4f7-11e5-92cc-3b9ba9589979.gif)

... a non-rotating map and a jerky (but cool) "flashlight".

**Comment by 1ec5** [comment]
I’m finally able to reproduce this issue for the first time, but it took a _lot_ of rotating and flipping through user tracking modes in quick succession. I’m guessing `userTrackingState` is stuck on `MGLUserTrackingStateBegan`.

**Comment by 1ec5** [comment]
In iosapp:

1. Switch to location tracking mode.
1. Switch to heading tracking mode.
1. Before the first heading update, rotate the device.
