### ISSUE TITLE
MGLMapboxEvents should run on the main thread

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3717]
MGLMapboxEvents is far more complex than it needs to be. There are `atomic` properties and lots of wrapper methods and synchronization to ensure that individual methods can be called from any thread, yet the class’s entry points are only ever called from MGLMapView and MGLAccountManager on the main thread. If there’s any concern about rapid-fire events code hurting performance, then we should isolate the potentially costly code (like the code that interfaces with System Configuration or sets up the network request) and run only that code asynchronously.

/ref #3704
/cc @boundsj @bleege

**Comment by bleege** [comment]
> MGLMapboxEvents is far more complex than it needs to be.

+1 to this statement.  Now that the use case has matured for iOS Telemetry lets look to simplify it for better developer understanding (internally and externally) and better performance.  Hope you brought your :machete: and :pithhelmet: @boundsj!
