### ISSUE TITLE
Heading accuracy indicator is too wide

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3718]
The user dot’s heading accuracy indicator appears to be twice as wide as it should be, assuming MapKit’s representation is correct:

![mapbox](https://cloud.githubusercontent.com/assets/1231218/12637207/356fc668-c548-11e5-8c2d-bd6e1943330a.PNG) ![mapkit](https://cloud.githubusercontent.com/assets/1231218/12637210/37a09174-c548-11e5-9cc6-6b8258ddc1fa.PNG)

/cc @friedbunny

**Comment by friedbunny** [comment]
It's [1.5x larger](https://github.com/mapbox/mapbox-gl-native/blob/e2a3c02d1a9f280badd9c1c2a9063aa2afdac7ab/platform/ios/src/MGLUserLocationAnnotationView.m#L489-L490), if MapKit is using the raw heading accuracy. I opted to exaggerate the heading indicator because 1. I thought it looked better and 2. how accurate is the heading accuracy number, anyway. :wink:

Looking at these images, it would be good to revisit this and make the accuracy indicator look better:

- Clip the heading indicator's wide end to the accuracy circle.
- Does size matter? Maybe constrain to a minimum, but don't exaggerate.

**Comment by Bluezen** [comment]
Hi! How did you manage to show the heading indicator?

Setting the following properties display the user location but not it's heading:
```objc
[self.mapboxView setShowsUserLocation:YES];
[self.mapboxView setUserTrackingMode:MGLUserTrackingModeFollowWithHeading];
```
Can you tell me what am I missing? Thank you in advance.

**Comment by 1ec5** [comment]
Are you running in a simulator? Simulator.app's implementation of Core Location doesn't support heading or course, even when simulating models that do support heading and course in real life.

**Comment by Bluezen** [comment]
My previous test was on an iPhone with sdk 3.2.3. 
I only have an iPad with me right now but I have created an empty project using sdk v3.3.0-beta.2 to quickly test it again. The only code in the project is an MGLMapView and the two lines above to set `showUserLocation` and `userTrackingMode`.

The user location is correctly displayed but the heading indicator isn't there and the map doesn't rotate when the heading changes. (Just for peace of mind I checked heading is showed correctly on Plan & Google Map).

I wonder what I'm not doing to make it work.

**Comment by 1ec5** [comment]
Unless you’re using a cellular-capable iPad, it also doesn’t support heading updates. But I’m unsure why it isn’t working on an iPhone. Is it possible that something else (like a gesture) is causing the map view to automatically exit user tracking mode? Also, enabling user tracking mode automatically sets `showsUserLocation`, so that first line should be unnecessary.

**Comment by Bluezen** [comment]
So does that mean MapBox doesn't rely solely on the compass to display the heading?

I tried again with an iPhone and like you said setting the `userTrackingMode` alone is enough to display the user location but still, no heading indicator is visible.

I walked a bit outside just to be sure, the user dot follows me correctly but the map doesn't rotate with heading changes and no indicator is visible. 
I guess I am still missing something but just to be sure could you make a quick test from an empty project using sdk 3.2.3? You can try with [this repo](https://github.com/Bluezen/MapBox-Experiments) if you want, just add a MapBoxAccessToken.

**Comment by Bluezen** [comment]
Alright I played a bit with `userTrackingMode` on my [empty project](https://github.com/Bluezen/MapBox-Experiments) and it seems that something automatically exit tracking mode (like you said).. but I don't know what and why yet.

**Comment by Bluezen** [comment]
I would like to have the indicator displayed without all the behavior of the tracking (map that rotates and center on user location).
Do you know if it is possible to display the heading indicator without having to set `userTrackingMode` to `MGLUserTrackingModeFollowWithHeading`?

**Comment by 1ec5** [comment]
@Bluezen, Let’s keep this ticket focused on the width of the existing heading accuracy indicator. I’ve filed #5523 to track the feature you’re requesting.
