### ISSUE TITLE
Temporarily Comment Out Java API for Content Insets

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#3723]
As work started on #3627 the initial API was contributed by the community in #3687.  After reviewing the [work needed to make this functional](https://github.com/mapbox/mapbox-gl-native/issues/3627#issuecomment-175908733) @tobrun and I decided to punt on this until `4.0.0` so that we can get `3.2.0` released sooner and so that repeat work wouldn't have to be done as part of MapboxMap work in #3145.  To enabled the punt :football: we'll comment out the `setContentPadding()` method in MapView for `3.2.0` so that developers don't try to use an API that isn't fully functional.  This is still very useful code and we'll bring it back as the basis of this work in `4.0.0`.

/cc @zugaldia @tobrun @lgeromegnace

**Comment by bleege** [comment]
Commented out the getter and setter methods for ContentPadding in MapView.  Verified that the Javadoc generated did not include it after being commented out.  Left the things as is with the methods in NativeMapView as there was instability when commenting them out due to JNI.  The only way to try to use these methods is via MapView and it's a private field, making it unlikely to be used at best.

**Comment by bleege** [comment]
Merged into `release-android-v3.2.0`.

**Comment by lgeromegnace** [comment]
Hi @bleege! 
I was unfortunately away from work for some personals matters.
Never the less I am glad that you take the time to look at this PR. I understand your considerations about the API and the need to make it once and clear for the `4.0.0` release.

**Comment by bleege** [comment]
@lgeromegnace Yep, this [was a timing thing](https://github.com/mapbox/mapbox-gl-native/issues/3627#issuecomment-175908733) as the core API that you submitted will definitely be used.  You are more than welcome to pitch in there too if you have the cycles.  Thanks again!
