### ISSUE TITLE
./platform/ios/scripts/document.sh: line 8: step: command not found

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#3725]
I'm guessing this might be a minor dependency that's missing from https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md#additional-dependencies-for-os-x?

/cc @friedbunny @1ec5

**Comment by 1ec5** [comment]
`make idocument` was factored out of `make ipackage` but I forgot to remove usage of the `step` function that’s defined in package.sh. This line automatically installs jazzy in the event that you’re missing it. jazzy is not a core dependency for building projects on OS X, but it is listed in [the build instructions for the iOS SDK](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/INSTALL.md#build).
