### ISSUE TITLE
strip-frameworks.sh contains extra /

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#3730]
I'm getting the error 

```
bash: /Users/bobby/Library/Developer/Xcode/DerivedData/testbed-dlvlckwctnwizihhxbdmejlwakfq/Build/Products/Debug-iphonesimulator//Mapbox.framework/strip-frameworks.sh: No such file or directory
```

It looks like there is an extra slash in bash command 

```bash
bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Mapbox.framework/strip-frameworks.sh"
```

Which should be

```bash
bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}Mapbox.framework/strip-frameworks.sh"
```

/cc @1ec5

**Comment by bsudekum** [comment]
Nevermind, wrong location.

**Comment by anshulkumar189** [comment]
I have issue like this
/Users/apple/Library/Developer/Xcode/DerivedData/Demo-flekbzdkkgorqqcnvyuekpvqmivl/Build/Products/Debug-iphoneos/Demo.app/Frameworks/Mapbox.framework/strip-frameworks.sh: No such file or directory
