### ISSUE TITLE
MGLPointAnnotation category stopped working after update

### ISSUE THREAD

**Issue by 3ph** [mapbox/mapbox-gl-native#3741]
I've been using category on MGLPointAnnotation for a while now - just needed to add more data to point annotation. The problem is that it only works up to version 3.0.0. Once I try to update to 3.0.1 or newer suddenly it stops working - added properties are ignored (I'm getting MGLPointAnnotation has no member '...'). I cannot figure out why - the category header file is definitely visible to the class throwing these errors, I've tested that.
Any ideas what changed from 3.0.0 to 3.0.1 which could case that?

**Comment by 1ec5** [comment]
When is this error occurring: when compiling, or at runtime? Are you setting or getting this property immediately after creating an MGLPointAnnotation instance, or in a delegate method?

**Comment by 3ph** [comment]
At compile time - so wherever it's being used, straight after creation and also in delegate methods

**Comment by 1ec5** [comment]
If this error is appearing at compile time, I’m not sure how the SDK could be causing it. Did you import the header containing the category into the file that’s using the properties that header declares? Perhaps you could post your code (or a reduced test case) in a gist?

**Comment by 1ec5** [comment]
Also, out of curiosity, is there a reason you’re categorizing MGLPointAnnotation instead of subclassing it?

**Comment by 3ph** [comment]
Yeah, me neither but as I said works in 3.0.0 but not in later version (I've cleaned, etc. every time). The code using the category is written in Swift but the bridging header works - there is enum defined in the category and that is recognised. It's only the added properties.
I've only needed few more properties so why subclass. 

This is the category https://gist.github.com/3ph/4fcb85055aa0af184444

**Comment by 1ec5** [comment]
Ah, in a bridging header. I do reproduce this issue with the bridging header and Swift. I believe it has something to do with the fact that 3.0.1 is distributed as a static framework (and 3.1.0 as a dynamic framework), whereas 3.0.0 and below were static libraries. Xcode 7.2 and above are getting more strict about modules being self-contained, so maybe this is related.

As a workaround, could you implement the category as a Swift extension instead?

**Comment by 3ph** [comment]
I've actually tried that before - but the swift header was generated incorrectly so I never got that working. I've tried again now and it works! I guess same change was affecting that as well. Thanks for your assistance.
