### ISSUE TITLE
Polygon Within Polygon, Shade everything except the intersection

### ISSUE THREAD

**Issue by kevincyh** [mapbox/mapbox-gl-native#3744]
I am curious if polygon options is able for me to shade only the area that is not in the intersection ?
![polygon](https://cloud.githubusercontent.com/assets/12988766/12668848/bfeb624a-c695-11e5-9d91-c22be4a5800d.png)

**Comment by 1ec5** [comment]
Polygon holes aren’t supported yet in annotations (#1729), but they are supported in any [GeoJSON](https://www.mapbox.com/help/define-geojson/) source that you include in the style.
