### ISSUE TITLE
CameraUpdateFactory.newLatLngBounds

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3754]
Currently not yet implemented:

```java
    /**
     * Returns a CameraUpdate that transforms the camera such that the specified latitude/longitude
     * bounds are centered on screen at the greatest possible zoom level.
     * You can specify padding, in order to inset the bounding box from the map view's edges.
     * The returned CameraUpdate has a bearing of 0 and a tilt of 0.
     *
     * @param bounds
     * @param padding
     * @return
     */
    public static CameraUpdate newLatLngBounds(@NonNull LatLngBounds bounds, int padding) {
        throw new UnsupportedOperationException("Not implemented yet");
    }

    /**
     * Returns a CameraUpdate that transforms the camera such that the specified latitude/longitude
     * bounds are centered on screen within a bounding box of specified dimensions at the greatest
     * possible zoom level. You can specify additional padding, to further restrict the size of
     * the bounding box. The returned CameraUpdate has a bearing of 0 and a tilt of 0.
     *
     * @param bounds
     * @param width
     * @param height
     * @param padding
     * @return
     */
    public static CameraUpdate newLatLngBounds(@NonNull LatLngBounds bounds, int width, int height, int padding) {
        throw new UnsupportedOperationException("Not implemented yet");
    }
```

We also need to expose one extra for setting content insets as documented in #3583 
- [x] Write unit tests for `LatLngBounds` and `LatLng`
- [x] Revisit old `setVisibleCoordinateBounds` and see how we can hook this up with camera api
- [x] Add new `CameraUpdate` type
- [x] Investigate/patch #2719 while I'm at it
- [x] make it work with camera api
- [x] refactor camera api to correctly use Factory pattern
- [x] ~~Write unit tests for `MapboxMap` integration~~
  - one does not simply write test for something that uses MapView directly.
- [ ] Remove old methods + model classes in java
- [x] ~~Remove obsolete methods in jni/c++~~ 
 - will be handled in #3791

**Comment by tobrun** [comment]
While working on the first item on the checklist I was able to bring up `LatLng` code coverage from : 

![screen shot 2016-02-02 at 09 28 38](https://cloud.githubusercontent.com/assets/2151639/12744451/a0bfd7f0-c994-11e5-91fa-a3875e25239f.png)

to:

![screen shot 2016-02-02 at 09 40 38](https://cloud.githubusercontent.com/assets/2151639/12744454/a3b76f86-c994-11e5-9bda-8b18844c2403.png)

I'm not able to hit :100: , because of the Parceable interface. This can only be tested on a real device or using a Mockito mock. I might look into the latter sometime. Fur now continuing with unit tests for `LatLngBounds`

**Comment by tobrun** [comment]
While implementing test cases, I have simplified `LatLngBounds`. We now enforce the usage of a Builder pattern. This will make the API more clear and this will do the heavy work for end developers (calculate NorthEastLatLng and SouthWestLatLng). Also this is in parity with Google.

**Comment by tobrun** [comment]
While revisiting the old `setVisibleCoordinates` method in jni.cpp:

```cpp
void JNICALL nativeSetVisibleCoordinateBounds(JNIEnv *env, jobject obj, jlong nativeMapViewPtr,
        jobjectArray coordinates, jobject padding, jdouble direction, jlong duration) {
    mbgl::Log::Debug(mbgl::Event::JNI, "nativeSetVisibleCoordinateBounds");
    assert(nativeMapViewPtr != 0);
    NativeMapView *nativeMapView = reinterpret_cast<NativeMapView *>(nativeMapViewPtr);

    jfloat left = env->GetFloatField(padding, rectFLeftId);
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        return;
    }

    jfloat right = env->GetFloatField(padding, rectFRightId);
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        return;
    }

    jfloat top = env->GetFloatField(padding, rectFTopId);
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        return;
    }

    jfloat bottom = env->GetFloatField(padding, rectFBottomId);
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        return;
    }

    jsize count = env->GetArrayLength(coordinates);

    mbgl::EdgeInsets mbglInsets = {top, left, bottom, right};
    mbgl::AnnotationSegment segment;
    segment.reserve(count);

    for (int i = 0; i < count; i++) {
        jobject latLng = reinterpret_cast<jobject>(env->GetObjectArrayElement(coordinates, i));
        jdouble latitude = env->GetDoubleField(latLng, latLngLatitudeId);
        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            return;
        }
        jdouble longitude = env->GetDoubleField(latLng, latLngLongitudeId);
        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            return;
        }
        segment.push_back(mbgl::LatLng(latitude, longitude));
    }

    mbgl::CameraOptions cameraOptions = nativeMapView->getMap().cameraForLatLngs(segment, mbglInsets);
    if (direction >= 0) {
        // convert from degrees to radians
        cameraOptions.angle = (-direction * M_PI) / 180;
    }
    mbgl::AnimationOptions animationOptions;
    if (duration > 0) {
        animationOptions.duration.emplace(mbgl::Milliseconds(duration));
        // equivalent to kCAMediaTimingFunctionDefault in iOS
        animationOptions.easing = mbgl::util::UnitBezier(0.25, 0.1, 0.25, 0.1);
    }

    nativeMapView->getMap().easeTo(cameraOptions, animationOptions);
}
```

I'm noticing that it's already using the easeTo from the camera api.

```cpp
    nativeMapView->getMap().easeTo(cameraOptions, animationOptions);
```

 We need to fix this that we can use all the different ones defined in `MapboxMap`:
 - move
 - ease
 - animate

We also need to fit this in nicely with a call coming from `MapboxMap`.

**Comment by tobrun** [comment]
I was able to resolve #2719, by pushing our `OnMapReadyCallback` at the end of the message queue:

```java
    /**
     * Sets a callback object which will be triggered when the {@link MapboxMap} instance is ready to be used.
     *
     * @param callback The callback object that will be triggered when the map is ready to be used.
     */
    @UiThread
    public void getMapAsync(final @NonNull OnMapReadyCallback callback) {

        // We need to put our callback on the message queue
        post(new Runnable() {
            @Override
            public void run() {
                callback.onMapReady(mMapboxMap);
            }
        });
    }
```

**Comment by tobrun** [comment]
Currently I have a working version, but it is not updating the state of CameraPosition. To have this I will have to extract some code form the original `setVisibleCoordinateBounds` and use that in java instead. So all the methods can use the same `moveTo`, `easeTo` and `animateTo`. After that we can remove all the old methods.

**Comment by tobrun** [comment]
I was able to port above C++ code to an java equivalent.  We now should be able to user the Camera API directly and we can manage our CameraPosition state in java.

**Comment by tobrun** [comment]
Before refactor mentioned above:
![screen shot 2016-02-02 at 15 28 29](https://cloud.githubusercontent.com/assets/2151639/12752216/be075892-c9c1-11e5-86c8-4dadfe1aeebb.png)

After refactor:
![screen shot 2016-02-02 at 15 30 08](https://cloud.githubusercontent.com/assets/2151639/12752240/df4a7142-c9c1-11e5-8236-727275367cce.png)


The logic for each type of Update is abstracted away in it's own type, 
No need for silly if-else constructions. Long live the factory pattern!

**Comment by mudar** [comment]
related to #3794: the only issue I can think of is handling polylines or polygons that would be partially visible. Not sure how GMaps handles this these days. Thanks!
