### ISSUE TITLE
Remove camera package

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3755]
Google hides their `CameraUpdate` implementations using package visibility. CameraUpdate and CameraUpdateFactory are placed in the same package as the MapView and others.

**Comment by tobrun** [comment]
We should hold off on implementing other  `CameraUpdateFactory` issues are fixed, see if still relevant and discuss the need for this.

**Comment by tobrun** [comment]
Issues:
 - https://github.com/mapbox/mapbox-gl-native/issues/3754
 - https://github.com/mapbox/mapbox-gl-native/issues/3753
 - https://github.com/mapbox/mapbox-gl-native/issues/3752

**Comment by tobrun** [comment]
it's time to investigate this again. Going to try moving all the classes back to the camera package. Would be cool if we are not required to use package visibility for this. Not sure at this time if that will work out.

**Comment by tobrun** [comment]
I was able to move all required components back to the `camera` package. no need to remove it. 
Only downside is that I had to expose the following method in `Projection.java`:

```java
    /**
     * Calculates a zoom level based on minimum scale and currently used scale
     *
     * @param minScale The minimum scale to take into account.
     * @return A zoom level that will fit the mapview.
     */
    public double calculateZoom(float minScale) {
        return Math.log(mMapView.getScale() * minScale) / Math.log(2);
    }
}
```

**Comment by tobrun** [comment]
@bleege update on this after we discussed this offline, 

I was able to **not** require having `CameraUpdate`, `CameraUpdateFactory`  and `CameraPosition` in the same package as `MapboxMap`, `MapView` etc. 

Only downside is documented [above](https://github.com/mapbox/mapbox-gl-native/issues/3755#issuecomment-188161452)

**Comment by bleege** [comment]
@tobrun Thanks for the update.  I think you did the right thing.  We can certainly live with having those methods be public.  This is still Java and isn't the first project to have to deal with things like this.  :+1:
