### ISSUE TITLE
Annotations refactoring for 4.0.0

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3756]
We should refactor the annotations package before freezing the api with the  `4.0.0` release:
 - [x]  discuss the need for IconFactory and see if we can remove it
   - we can't remove this, needed for JNI
 - [x]  support inheritance (iOS parity) or provide an alternative for https://github.com/mapbox/mapbox-gl-native/issues/3041
 - [x]  ~~provide a way to pass in custom data to a marker. (equivalent of `setTag` in Android SDK)~~
 - [x]  convention names/models with GeoJSON https://github.com/mapbox/mapbox-gl-native/issues/3288
  -  going to punt on this until roadmap GeoJSON is more clear
 - [x] add getters for different subtypes of annotation
 - [x] add a removeAnnotation(id) method
 - [x] add unit tests!

**Comment by mudar** [comment]
about inheritance, I remember that GMaps didn't allow that either, where markes is a `final` class. I guess it's for preformance issues, but most of the time my only need was to store my external ID (from API) into the marker (related to my #3796).

So inheritance sounds great, but if performance doesn't allow it, setting an external ID (can be string or long) would still be helpful without breaking things

Thanks!

**Comment by tobrun** [comment]
> discuss the need for IconFactory and see if we can remove it

Been looking into this before discussing and we need this for the bridge with JNI.

>  support inheritance (iOS parity) or provide an alternative for #3041
 
Been looking in how Google Maps supports this, apparently they don't and you need to do the same tricks as developers are doing now for this SDK. An example of this see [here](http://bon-app-etit.blogspot.be/2012/12/add-informationobject-to-marker-in.html). 

>  convention names/models with GeoJSON #3288

TODO

>  provide a way to pass in custom data to a marker. (equivalent of setTag in Android SDK)

I have been playing around with the idea of supporting a `setTag` method but this will not work well with `Parceable` interface.

**Comment by tobrun** [comment]
I'm going to start adding unit tests for integration within `MapboxMap`

**Comment by tobrun** [comment]
Providing a way to pass in data that is compliant with our `Parceable` interface without using generics is very very hard! We always need a reference to ClassLoader to recreate the parceable implementation.

**Comment by tobrun** [comment]
I'm going to try and see if the inheritance approach is feasible with out current API and builder pattern approach. This would grant our users the same flexibility as with the iOS SDK.

**Comment by tobrun** [comment]
I investigated above what the possibilities are to open up Markers for end developers:
 - we can use a setTag(object o) but this will mean we will have problems supporting `Parceable`, only solution found for this was using `serialisable`
 - we use inheritance to allows subtypes of marker to be used as annotations. Problems here is the the enforcement of Parceable interface (end developer is required to implement and support basic marker-parceable interactions).

I'm going to support the second idea since this will give us parity with iOS.

**Comment by tobrun** [comment]
I must admit, the way you need to work around some things is a bit strange:
 - creating a custom builder requires itself as second generic argument
 - custom marker constructors require the base builder class + everything added to the custom marker 
 - parceable interface is required to parcel every field even superclass fields.

**Comment by ouska** [comment]
Hello,
don't know whether this is the best place where to comment but I also ran into that problem with custom ID (or tag). Just want to say that I tried the approach with the class extension but there is a problem with line
Icon icon = new Icon(iconId, iconBitmap);
because the constructor is not public.

Would not be easier to add simple extra String field called tag to the basic Marker implementation than to force people to subclass the Marker whenever they want to pass some extra identificator.
Thank you.

**Comment by FabbyD** [comment]
Hi,
I second @ouska. Just wondering if there is still work being done in order to attach custom information to a marker. Are there any plans to add the `setTag(Object o)` method you mentioned @tobrun ? Or is the official way inheritance?
Thank you for your work :)

**Comment by tobrun** [comment]
I would love to add the setTag method but that wasn't possible due the contract with Parceable inteface :disappointed:. That said, if inheritance is too much hassle and you aren't creating an insane amount of annotations I would suggest using `Map<Annotation,Object>` or `LongSparseArray<Object>` where the  key = id of the Annotation.

**Comment by FabbyD** [comment]
Ok! Thank you for your suggestions

**Comment by neonwarge04** [comment]
I made a very stupid methodology to tackle all the hassle and effort. There is a setSnippet method on MarkerOption, I have json string and set it there since I am not using getSnippet() anywhere in my app. I don't recommend this though. 

Have this been resolved? Any ideas if I can attach a json data to a marker? I have some data that describe a marker and I just took advantage of putting my json data where its not suppose to be.

**Comment by bhargavms** [comment]
@neonwarge04 I have tried attaching the json string to the marker title, but I am not sure if the snippet and the title of the marker won't get modified by the sdk.

**Comment by bhargavms** [comment]
@tobrun Also for the `setTag()` not being parcelable problem, why not have `setTag(Parcelable)` instead of object? Then the extra work that the user would need to do is just implement Parcelable for his class that he wants to push to the marker
