### ISSUE TITLE
Projection + VisibleRegion

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3758]
We should introduce the `Projection` class for the `4.0.0` release.

```java
LatLng fromScreenLocation(Point point)
VisibleRegion getVisibleRegion()
Point toScreenLocation(LatLng location)
```

The first and last method are currently implemented in `MapboxMap`,
VisibleRegion model + implementation should be added. 

- [x] add model classes
- [x] ~~write unit tests~~
- [x] migrate old methods to new
- [x] update test app 
- [x] clear checklist below for `VisibleRegion`

**Comment by tobrun** [comment]
Projection:
> A projection is used to translate between on screen location and geographic coordinates on the surface of the Earth (LatLng). Screen location is in screen pixels (not display pixels) with respect to the top left corner of the map (and not necessarily of the whole screen).

VisibleRegion:
> Contains the four points defining the four-sided polygon that is visible in a map's camera. This polygon can be a trapezoid instead of a rectangle, because a camera can have tilt. If the camera is directly over the center of the camera, the shape is rectangular, but if the camera is tilted, the shape will appear to be a trapezoid whose smallest side is closest to the point of view.

**Comment by tobrun** [comment]
While implementing this, I'm not sure why there is a separate class for VisibleRegion instead of using LatLngBounds instead.. As long as I don't see a need for this I'm going to implement that method with following signature:  `LatLngBounds getVisibleRegion()`

**Comment by tobrun** [comment]
There is actually no way of writing unit tests for these except for a sanity check, this is because all 3 methods from Projection are using the underlying native library.

**Comment by jfirebaugh** [comment]
> While implementing this, I'm not sure why there is a separate class for VisibleRegion instead of using LatLngBounds instead.

Rotation and tilt? `LatLngBounds` is axis aligned and rectangular; the region visible in a viewport is not necessarily so.

**Comment by tobrun** [comment]
@jfirebaugh Yes, that makes a lot of sense! will add that

**Comment by tobrun** [comment]
Today I will add `VisibleRegion` but will do a cleanup of the old geometry classes as well.

**Comment by tobrun** [comment]
Damn it, shooting myself in the foot here with `Remove BoundingBox` class, 
I will have to update `jni.cpp` and update related methods to us `LatLngBounds` instead.
