### ISSUE TITLE
Add map padding to the MapboxMap object

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#3761]
When padding is added to a map, the map continues to fill the entire container, but text and control positioning, map gestures, and camera movements will behave as if it has been placed in a smaller space. Android's corresponding implementation is [described here](https://developers.google.com/maps/documentation/android-api/map?hl=en#map_padding).

Related (MapboxMap class): https://github.com/mapbox/mapbox-gl-native/issues/3145

/cc: @tobrun @bleege

**Comment by tobrun** [comment]
Will be added as:

```java
MapboxMap.setPadding()
```

Other methods mentioned in that section are here:
-  ProjectionVisibleRegion #3758 
-  newLatLngBounds #3754

**Comment by bleege** [comment]
Will this be related to Content Insets in #3627?

**Comment by tobrun** [comment]
@bleege they seem related, 
I need to do some testing with Google Maps first giving a definite answer on this.

**Comment by tobrun** [comment]
Been looking into the setPadding by playing around with Google maps SDK in a sample app, 
and it seems that setPadding is the actual method for content insets on Google Maps!
[Youtube video](https://youtu.be/HSCsdiqNjGo) showcasing this.

**Comment by tobrun** [comment]
This is an example of the feature activity for without calling `setPadding`:
![device-2016-02-10-100109](https://cloud.githubusercontent.com/assets/2151639/12942689/3d1745d6-cfdd-11e5-8905-fb5dbc430a33.png)\


What needs to happen:
 - [ ] expose setPadding in MapboxMap
 - [ ] Map itself should be offset (the marker must be in the center of the non blue area)
 - [ ] Overlayn items as MapboxLogo should take this padding into account

**Comment by tobrun** [comment]
After hooking up the setPadding method. I'm not seeing any changes with prior screenshot..
Also looking into screenshots posted in #3627, I'm not seeing any differences as well.. 
Not sure if this has actually has worked before..

**Comment by tobrun** [comment]
Now that I have a better understanding about the missing pieces required to have this on Android:
 - [ ]  fix API that we can always call setPadding without requirement of calling camera api
 - [ ]  Overlain views should take in account the map padding
 - [ ]  Expose a setPadding on UserLocationView separately (for navigation)

**Comment by lgeromegnace** [comment]
Hi @tobrun, it's good to see this subject come back to front.

About your comment, I was thinking may be setPadding should update camera once it has been set ?
This should avoid the feeling the insets are not taken into account immediately.

**Comment by lgeromegnace** [comment]
Ha I see your last comment too late :).

**Comment by tobrun** [comment]
@lgeromegnace, awesome and thanks again for the contribution!

**Comment by tobrun** [comment]
For the overlain views I'm going to introduce a new class for general management of an overlain view.
This will be managed by `UiSettings` class and will expose 3 attributes:
 - enabled
 - gravity
 - margins

The margins from above must be updated if we set a certain padding, but most importantly it must only update margins in a certain direction (based on gravity attribute).

**Comment by tobrun** [comment]
We will need to provide a way to invalidate the margins/gravity associated with a `ViewSettings`. After calling `setPadding` on `MapboxMap`

**Comment by tobrun** [comment]
This is the result with invalidate in place:

![device-2016-02-10-131146](https://cloud.githubusercontent.com/assets/2151639/12946885/e6b109aa-cff7-11e5-9fc0-dc382c18c3d6.png)

**Comment by tobrun** [comment]
![device-2016-02-10-163225](https://cloud.githubusercontent.com/assets/2151639/12951747/0c54d59e-d014-11e5-99f1-7c64037ccb66.png)

I was not able to find any strange edge cases. Next up is UserLocationView.

**Comment by tobrun** [comment]
`UserLocationView` with padding, next up is exposing an API to offset `UserLocationView`

**Comment by tobrun** [comment]
Noticing that I also need to update some code related to gestures 
 > eg. zoom should take in account the padding.

**Comment by tobrun** [comment]
To correctly manage the change in #3899 I need to find some code on a stale branch.

**Comment by tobrun** [comment]
This is the refactored stale code:

```java
    private void validateGesturesForTrackingModes() {
        if(!dismissTrackingOnGesture) {
            int myLocationTrackingMode = getMyLocationTrackingMode();
            int myBearingTrackingMode = getMyBearingTrackingMode();

            // Enable/disable gestures based on tracking mode
            if (myLocationTrackingMode == MyLocationTracking.TRACKING_NONE) {
                uiSettings.setScrollGesturesEnabled(true);
                uiSettings.setRotateGesturesEnabled(true);
            } else {
                uiSettings.setScrollGesturesEnabled(false);
                uiSettings.setRotateGesturesEnabled((myBearingTrackingMode == MyBearingTracking.NONE));
            }
        }
    }
```

Code above will enable/disable certain gestures if we are not automatically dismissing tracking modes.

**Comment by tobrun** [comment]
I was able to correctly calculate center of gesture in case of tracking mode :boom: 
See result here:
https://www.dropbox.com/s/p95k6qh7z6kdsxc/device-2016-02-12-130800.mp4?dl=0

**Comment by tobrun** [comment]
All usecases of gestures are working except for tilt..
https://www.dropbox.com/s/0q0wh6asjgokfpa/device-2016-02-12-145442.mp4?dl=0

**Comment by tobrun** [comment]
Apparently to fix above we first need to expose this through `jni`:

```cpp
void Map::setPitch(double pitch, const PrecisionPoint& anchor, const Duration& duration) {
    transform->setPitch(pitch * M_PI / 180, anchor, duration);
    update(Update::Repaint);
}
```

currently we are using:

```cpp
void Map::setPitch(double pitch, const Duration& duration) {
    setPitch(pitch, {NAN, NAN}, duration);
}
```

**Comment by tobrun** [comment]
After :facepunch:  with JNI I was able to compile and call the native method.
Only the anchor point used should not be the same as with the other gestures. there we are rotating/scaling around `UserLocationView-center`...

**Comment by tobrun** [comment]
Going to punt on above and move back to `fix API that we can always call setPadding without requirement of calling camera api`

On iOS this is handled here https://github.com/mapbox/mapbox-gl-native/commit/6a0b7f8eb308c1c03a4013cff7e830c42924ce77#diff-20502b6bc02986a4398d0da84b2d4b94R808

We just need to reset CameraPosition to current position.

**Comment by tobrun** [comment]
:boom: I was able to implement above:
See result here:
https://www.dropbox.com/s/b9ea31qteyb6oii/device-2016-02-12-175452.mp4?dl=0

We now just need 2 more things to close this:
 -[ ] support map padding when doing a tilt gesture
 -[ ] add UserLocationView padding (attributes are in place but need to shuffle with calculations)

**Comment by tobrun** [comment]
Going to punt on current progress and add a PR for current progress. 
Will create 2 other issues for above.

**Comment by tobrun** [comment]
Follow up issues:
Tilt gesture with padding and user location tracking Android bug #3947 
Add padding to UserLocationView Android feature request #3946

**Comment by bleege** [comment]
@tobrun Good call on breaking this issue up into smaller tasks.  Gets the working code in quicker and brings more clarity to the remaining issues.  :+1:
