### ISSUE TITLE
Test App's Main Activity Controls Aren't Consistently Working

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#3762]
For example, it's possible to turn the "Debug Mode" on by tapping on the Menu Item but it won't turn off by tapping on the same Menu Item again.  I've also noticed that Toggle Compass seems to have a similar error where the Menu Item is always highlighted even when the Compass isn't being used.

These are all likely caused by the the big lift for MapboxMap in #3145 and just need a second pass of TLC to get them back on track.

/cc @zugaldia @tobrun

**Comment by tobrun** [comment]
obsolete due to test app refactor occurring in #4365
