### ISSUE TITLE
[android] Change marker icon without remove/add workaround

### ISSUE THREAD

**Issue by mpuchala** [mapbox/mapbox-gl-native#3775]
Hi Guys,

I'm using your map with more or less 500 - 1k markers at a time. There are few types of icons. Some of them are just made from resources and cached, but I'm using clustering as well. That’s why many of them have to be created as a new Bitmap.

My issue is about changing marker icon during the runtime. On Github I saw this thread: https://github.com/mapbox/mapbox-gl-native/pull/3146. Does it mean it would be possible to change icon on Android in different way than removing/changing/adding new marker? In fact this solution is problematic  - it can take up to 1000ms and looks awful (tested on Nexus 4, Android 5.1). It blocks UI thread so despite the fact clustering is slow and setting different icons according to zoom doesn’t work smooth it affects another views (ex. animations). Actually even this code can take up to 200ms:

```
mMapView.removeAnnotation(mMarkerOptions.getMarker());
mMarkerOptions.icon(...);
mMapView.addMarker(mMarkerOptions);
```

 Maybe you have any idea how can I improve it?

**Comment by 1ec5** [comment]
The iOS SDK supports changing marker images without adding and removing markers (#3146, #3320). [`-[MGLMapView annotationImageNeedsRedisplay:]`](https://github.com/mapbox/mapbox-gl-native/blob/e8b8f5e49306e3cc80c2692575703e49129dcb84/platform/ios/src/MGLMapView.mm#L2989-L2996) should be ported to the Android SDK.

**Comment by socketbind** [comment]
Hi,

I have been actually working on this (+ the ability to set the position also) but my code is a bit crude (see referenced pull request). I would love to improve upon it and make this happen.
