### ISSUE TITLE
StyleParser::parseTileJSON(json, sourceURL) breaks vector URLs

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#3786]
The newly factored-out `StyleParser::parseTileJSON(json, sourceURL)` from #3771 applies [raster URL normalization to vector URLs](https://github.com/mapbox/mapbox-gl-native/blob/8aa3359ff00332ef17157bf3c4452e710cc10b23/src/mbgl/style/style_parser.cpp#L271-L276), which results in vector URLs with `{ratio}` erroneously inserted. This means that map styles load but vector data does not — the user sees the background color but no content. Raster tiles continue to load.

[Here](https://github.com/mapbox/mapbox-gl-native/blob/b41a73e1c1dfea982df4a0326d45a48babc22dd4/src/mbgl/map/source.cpp#L123-L128) is the original raster URL normalization from `Source::load()`.

/cc @jfirebaugh @boundsj

**Comment by friedbunny** [comment]
No errors or console output of any kind, by the way — just blankness.

**Comment by jfirebaugh** [comment]
Fixed in 52689796dfed796a1e949d39be411ccca3041933.
