### ISSUE TITLE
Suggestions for getAnnotations() and annotation ID

### ISSUE THREAD

**Issue by mudar** [mapbox/mapbox-gl-native#3793]
Working with the android library, I've run into some limitations using `MapView.getAnnotations()`. Here are some suggestions:
- [x] add other methods like `getMarkers()`, `getPolylines()`, `getPolygons()` or `getAnnotations(type)`: Currently I need to loop over all annotations, and validate `instanceof` of each item
- [x] add `MapView.getAnnotation(long id)`: when adding annotations to the map, we can store the ID. But in the current state, it seems its only use is to loop over all annotations and verify each ID.
- [x] add `MapView.removeAnnotation(long id)`: same as above

**Comment by tobrun** [comment]
Thank you for reaching out and giving these remarks.
For now I'm going to link #3756.
I will be aiming at having parity with Google for the `4.0.0` release.
Will need to investigate what they are exposing.

**Comment by tobrun** [comment]
### Related to first suggestion:
Have a look at this [SO-post](http://stackoverflow.com/questions/16367594/google-maps-v2-android-get-a-list-of-markers). 
 - apparently Google doesn't even expose getAnnotations/getMarkers
 - people have written wrappers to add this functionality.

This gives me enough reason to support this. Will add that to #3756.

### Related to second/third suggestion:
Those seem logical to have as well. Will add those to #3756.

**Comment by tobrun** [comment]
@mudar, I have added related methods in #3756. 
This was great feedback to have, thanks again!
