### ISSUE TITLE
Suggestions for map's CoordinateBounds

### ISSUE THREAD

**Issue by mudar** [mapbox/mapbox-gl-native#3794]
With the android library, we currently have `MapView.setVisibleCoordinateBounds()`, but that's a bit limited. I suggest
- [ ] adding a `MapView.getVisibleCoordinateBounds()` method.
- [ ] adding a `Annotation.isVisible()` or `Annotation.isInsideVisibleCoordinateBounds()`. This could be a duplicate of other tickets though..

**Comment by tobrun** [comment]
@mudar, 
Thank you for reaching out and requesting these features.

Before getting in to the details, everything what used to be called `VisibleCoordinateBounds` will be replaced with `LatLngBounds` from the `4.0.0` release on. This was needed to have better parity with the Google Maps SDK for Android. Related issue is [here](https://github.com/mapbox/mapbox-gl-native/issues/3754)

> adding a MapView.getVisibleCoordinateBounds() method.

This will not be exposed through a `getLatLngBounds()` but through the `Projection` class from #3758. We will expose this in same manner as Google Maps as seen [here](http://stackoverflow.com/a/16064924/1281750).

> Annotation.isVisible() or Annotation.isInsideVisibleCoordinateBounds()

There is a method called `including(ILatLng latLng)` from `LatLngBounds`, With this method you can determine if a certain LatLng is inside a certain bounds. This could be useable for annotation (target) as well.

Let me know what you think,
Thanks again for reaching out. 
This is valuable feedback!

**Comment by mudar** [comment]
That sounds great! Closing this issue and adding a small comment to #3754
