### ISSUE TITLE
Suggestions for Map Annotations

### ISSUE THREAD

**Issue by mudar** [mapbox/mapbox-gl-native#3796]
This is also related to my other suggestions in #3793 

Could we allow the map annotations (or just Markers) to store some extra data? This could be done using `setCustomId()`, or something similar to android's `view tags` or or any other solution.

At the time, I had the same issue with GMaps, and my bad solution has always been to store my id in the unused `snippet`... I know :-(

In its current state, `onMarkerClick(Marker)` must be used with an ListArray that links the native ID to my own ID. And this ListArray needs to be synced on map udpates that happen in the background on map scroll. Add app lifecycle and possible API errors into the equation and the snippet solution starts to seem cleaner to me (I'm exagerating a bit!).

Sorry if this is a duplicate request

**Comment by tobrun** [comment]
Thank you for reaching out and requesting this feature. This is known issue and limitation of the current SDK. On iOS for example you can just use inheritance to pass this information on Android this is not possible yet. Their have been some discussions about this in #2914. I ideally want to pick this up with #3756.

**Comment by mudar** [comment]
Closing and adding comment on #3756.
