### ISSUE TITLE
Add additional callbacks for OnScrollListener()

### ISSUE THREAD

**Issue by mudar** [mapbox/mapbox-gl-native#3797]
Related to #1942
For the android library, it would be nice to have `onScrollStarted()` and `onScrollEnded()` added to the `OnScrollListener`.

Usually the map needs to be updated when the user stops panning (or zooming). So I cannot use onScroll. Instead I rely on `MapView.onMapChanged(int change)`, and trigger updates on region change, with a `postDelayed()` runnable to try to fetch the map's last coordinates.

Another useful callback (or argument) could also provide the scroll distance (in meters?)

**Comment by tobrun** [comment]
We are currently exposing `OnCameraChangeListener`, this gives you the callbacks needed for requirements mentioned above. 

I'm still leaving it on the `4.1.0` milestone but don't consider this a high priority.

**Comment by tobrun** [comment]
At this point all use cases could be possibly handled with `OnCameraChangeListener`. Going to close, feel free to comment on this if it should still be considered a requirement.
