### ISSUE TITLE
[Android] Click on Marker does not work with 3.2.0

### ISSUE THREAD

**Issue by crzo** [mapbox/mapbox-gl-native#3799]
Hello,

after upgrading to 3.2.0, i have some trouble with the marker click-handling.

I registered a custom MapView.InfoWindowAdapter by using the MapView.setInfoWindowAdapter(...) method. However, the custom view won't appear nor the breakpoint will pause in getInfoWindow(). 
Am i missing smth. here in 3.2.0? Probably a bug?

Thanks for help!

**Comment by tobrun** [comment]
@crzo 
Yes this is a known bug and was fixed in this issue https://github.com/mapbox/mapbox-gl-native/issues/3736. 
You can work around this issue if you set a title or snippet on you marker object.
