### ISSUE TITLE
Hide the ℹ️ attribution button if map isn't interactive

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#3804]
When a map view has `userInteractionEnabled=NO`, the :information_source: button isn't tappable. It doesn't make much sense to have a non-tappable button, so we should hide it.

When there is no attribution button (or effectively none), we may also want to re-check for a telemetry opt-out.

/cc @1ec5 @boundsj

**Comment by friedbunny** [comment]
Instead of just hiding the button, we should switch to text-only attribution in non-interactive maps.

**Comment by 1ec5** [comment]
For the textual attribution, most of https://github.com/mapbox/mapbox-gl-native/blob/2988ca16c1bfa8f00518411d2a711113fe88d13f/platform/macos/src/MGLMapView.mm#L364-L391 and https://github.com/mapbox/mapbox-gl-native/blob/2988ca16c1bfa8f00518411d2a711113fe88d13f/platform/macos/src/MGLMapView.mm#L427-L492 should port pretty straightforwardly to iOS.
