### ISSUE TITLE
Crash when exit app after start and zoom in/zoom out map

### ISSUE THREAD

**Issue by DucHM** [mapbox/mapbox-gl-native#3806]
I'm tried to run https://github.com/mapbox/mapbox-android-demo/ and crash when exit app after start and zoom in/zoom out map with appear error following:

Unfortunately, Mapbox Dev Preview has stopped --> OK

The console logcat information:
com.mapbox.mapboxandroiddemo E/IMGSRV: kickresource.c:1130: Debug assertion failed!
com.mapbox.mapboxandroiddemo A/libc: Fatal signal 6 (SIGABRT) at 0x00001c2b (code=-6), thread 7211 (pboxandroiddemo)

My device using for test:

Model numer: ASUS_T00J
Android version: 4.4.2
Please support this issues. Any help will be appreciated.

**Comment by bleege** [comment]
@DucHM Can you [tell us more about what version](https://github.com/mapbox/mapbox-android-demo/issues/48#issuecomment-179346135) of the demo app that you were running?

**Comment by DucHM** [comment]
I downloaded the demo from https://github.com/mapbox/mapbox-android-demo/ and run it after changing the version of mapbox to 3.2.0

**Comment by bleege** [comment]
This is being discussed over on the Demo ticket at --> https://github.com/mapbox/mapbox-android-demo/issues/48#issuecomment-179904451
