### ISSUE TITLE
InfoWindow on Android (enforcing title and snippet on Marker)

### ISSUE THREAD

**Issue by dariav** [mapbox/mapbox-gl-native#3814]
There are 2 things I found strange when it comes to InfoWindow (I am using InfoWindowAdapter to customize it and that works fine)
- In case I don't fill in `title` and `snippet` on the `MarkerOptions` , InfoWindow won't be shown because of `isInfoWindowValidForMarker` **Are there plans to not enforce this rule?**
- old SDK had one handy method on `Marker` called `.setRelatedObject` **Is there anything similar in new SDK?**

Thanks

**Comment by tobrun** [comment]
@dariav 
Thank you for reaching out and asking for these features.

##### Related to first question:
This was resolved in https://github.com/mapbox/mapbox-gl-native/issues/3736 and will be in the next release.

##### Related to second question:
We are aware that current `Marker` API is very limited in comparison to the old sdk or the current iOS SDK and we are working on this to improve it. We are currently discussing what API we are going to expose. A `.setRelatedObject` or `.setTag` are very good candidates to make that API. You can follow up on this issue in #3756, which redirects to other smaller issues.

Reach out if you have any other questions/suggestions,
This is very valuable feedback to have!

**Comment by dariav** [comment]
@tobrun Thanks for reaching back so quickly! It's great to see this kind of activity on the project.

Thanks for all the answers, and I hope we'll get `.setTag` in near release. Continuing to follow referenced issues!
