### ISSUE TITLE
get latLngBounds in Mapbox

### ISSUE THREAD

**Issue by tuanht53** [mapbox/mapbox-gl-native#3816]
hi, i want to get latLngBounds on Android.
What is code to get LatLngBounds for Mapbox Android?
eg: google map have code: googleMap.getProjection().getVisibleRegion().latLngBounds

**Comment by tobrun** [comment]
@tuanht53 
Thank you for reaching out and requesting this feature.
Currently we don't expose the class `LatLngBouns` but we will in next release (see #3754).
You will be able to use the same API as with Google Maps SDK to retrieve this (see #3758).

##### Workaround:
Get the `LatLng` value from the 4 corners:

```java
        int viewportWidth = mMapView.getWidth();
        int viewportHeight = mMapView.getHeight();

        LatLng topLeft = mMapView.fromScreenLocation(new PointF(0, 0));
        LatLng topRight = mMapView.fromScreenLocation(new PointF(viewportWidth, 0));
        LatLng bottomRight = mMapView.fromScreenLocation(new PointF(viewportWidth, viewportHeight));
        LatLng bottomLeft = mMapView.fromScreenLocation(new PointF(0, viewportHeight));
```
Feed these values in `CoordinateBounds`, which is actually the same thing as a `LatLngBounds`.

I hope this solves your problem for now, reach out if you have any other questions.

**Comment by tuanht53** [comment]
thanks @tobrun
