### ISSUE TITLE
How to set BoundingBox to MapView

### ISSUE THREAD

**Issue by DucHM** [mapbox/mapbox-gl-native#3818]
Dear,
I want to set BoundingBox for MapView (Android).
How to set it?
Example GoogleMap:
LatLngBounds.Builder builder = new LatLngBounds.Builder();
...............
Bounds bounds = builder.build();
mGoogleMap.moveCamera(CameraUpdateFactory
                    .newLatLngBounds(bounds, AppConf.dpToPx(72, getResources())));
mGoogleMap.moveCamera(CameraUpdateFactory.zoomOut());

Thanks!

**Comment by tobrun** [comment]
@DucHM thank you for reaching out.
With the `3.2.0` relaese you can do this using the `MapView.setVisibleCoordinateBounds` method.
In next releases you will be able to use the same syntax as Google (see #3754 for more information).

Reach out if you have any more questions!
