### ISSUE TITLE
Query for zoomin

### ISSUE THREAD

**Issue by gurumaheshPCS** [mapbox/mapbox-gl-native#3822]
Hi Mapbox,
I am facing some issue in iOS.I am loading map with annotations with zoom level =18, when i do double tap it should increase zoom level. But it is getting zoom out. if i check the zooomlevel property it is showing zoom level 18 only. Please suggest me to solve this issue.

**Comment by 1ec5** [comment]
We’re adding support for zooming in past z18 in version 3.1.0 of the Mapbox iOS SDK (#3712). You try out a [prerelease](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.1.0-pre.3) in the meantime. By default, the map zooms in up to z20, but you can increase the maximum zoom level to z25.
