### ISSUE TITLE
Response should be a variant type

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#3825]
`Response` should be a variant type with the following variants:
- Success
- NoContent
- NotModified
- Error

**Comment by kkaefer** [comment]
@jfirebaugh Do you still think this is necessary?

**Comment by jfirebaugh** [comment]
It's not a high priority, but I think it would clarify intent in a lot of places and eliminate some state combinations that are possible right now but not expected to happen, like having both `Response::error` and `Response::data` present.
