### ISSUE TITLE
Multiple calls to removeAnnotations: leaves some annotation images on the map

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-gl-native#3826]
On Mapbox iOS SDK 3.0.1, quickly stacking multiple calls to `removeAnnotations:` can cause some pins to stay rendered on the map.  Tapping them won't fire the `mapView:didSelectAnnotation:` delegate method.  Also, they disappear when you move to a different zoom level and reappear when you go back to the original zoom.

When we get to this state with rogue annotations, the map's `.annotations.count` is 0.

**Comment by jfirebaugh** [comment]
Is this still reproducible with the latest version (v3.3.4)?
