### ISSUE TITLE
Map flashing on iPhone 6+/iOS 9.3 with 3.1 prerelease builds

### ISSUE THREAD

**Issue by quicklywilliam** [mapbox/mapbox-gl-native#3836]
I tested our app with the latest (3.1.0 pre3) release of Mapbox:

- On an iPhone 6+ running iOS 9.3, the map exhibited the strange flashing I've attached a zipped screencast of (basically the tiles flash in and out of visibility). Reproduces every time, and doesn't stop after loading tiles etc.
- On an iPhone 5S running iOS 9.2.1, the map behaves as expected.
- Using the the latest production release (3.0.1) of Mapbox, the map behaves as expected on both devices.

Unfortunately I don't have another iPhone 6+ or 5S sitting around so I cannot confirm whether the bug was due to the hardware or software.
[flashingmap.mov.zip](https://github.com/mapbox/mapbox-gl-native/files/119900/flashingmap.mov.zip)

**Comment by 1ec5** [comment]
Thanks for the report, @quicklywilliam! Do you reproduce it also with 3.1.0-pre.2 or -pre.1? (I’m about to roll a -pre.4 build that you can also try.) Just trying to narrow the window here because 3.1.0 has seen a lot of changes.

**Comment by friedbunny** [comment]
Hrm, I haven't seen this on my iPhone 5 running the 9.3 betas. I'm not aware of any recent changes related to pixel ratio, but that seems like a reasonable enough starting point for investigations.

**Comment by friedbunny** [comment]
This doesn't reproduce on iPhone 6 Plus, iOS 9.2.1.

**Comment by friedbunny** [comment]
Incidentally @quicklywilliam: congratulations on the launch!

**Comment by quicklywilliam** [comment]
Thanks, @friedbunny!

**Comment by quicklywilliam** [comment]
Update: after the weekend I'm no longer able to reproduce the original symptoms on any build. Perhaps a device restart did it? In any case, I'm going to close this issue for now.
