### ISSUE TITLE
Unable to drag the annonation pin through diduserupdatelocation delegate and get details of respective location like: country name, street.

### ISSUE THREAD

**Issue by abhinesh01** [mapbox/mapbox-gl-native#3843]

**Comment by 1ec5** [comment]
If I understand correctly, you’re asking about getting data from the map in textual form. #3172 will add an API called “featuresAt” that will let you get a limited amount of data about individual features that are visible on the map. However, generally speaking, if you want to get address data about a particular point on the map, please consider using the [Mapbox Geocoding API](https://www.mapbox.com/developers/api/geocoding/).

**Comment by abhinesh01** [comment]
@1ec5 
how could i move annonation marker over the map ?

**Comment by friedbunny** [comment]
@abhinesh01 Dragging or animating annotation movement is not supported yet.

Theoretically you could implement your own pan gesture recognizer and remove/re-add the annotation whenever the gesture point moved ([something like this](https://www.mapbox.com/ios-sdk/examples/point-conversion/)), but performance will almost certainly suck and I would not recommend it.

**Comment by abhinesh01** [comment]
@1ec5 @friedbunny 
Is it possible to drag map while keeping annotation pin static? if it is possible  i like to  get data from annotation pin with[ mapbox Geocoding api](https://www.mapbox.com/developers/api/geocoding/)when updating coordinates.

**Comment by 1ec5** [comment]
> you’ll need to implement the marker as a UIView that’s positioned above the map

Instead of using an MGLAnnotation, create a UIView (perhaps a UIImageView) and center it over the MGLMapView. This UIView doesn’t have anything to do with the map view; it’s just an ordinary view that sits atop the map view. Then in the `-mapView:regionDidChangeAnimated:` method of your MGLMapViewDelegate, get the map view’s `centerCoordinate` property and look up that coordinate in the Geocoding API.

**Comment by abhinesh01** [comment]
Thanks so much, Got what i am looking for. 
 And i like to confirm is below coding is correct to get data fromGeocoding API.  Most of the time i am getting  empty json or something like below image.

**Comment by abhinesh01** [comment]
Got it, I made mistake by interchanging long and latitude value in api. Now
its working fine
Thanks.

**Comment by abhinesh01** [comment]
All of sudden when i am trying to run the app its shows as below screenshot
it doesn't appear anything blank map.
It used to work  good perviously  but now its doesnt load map and Does it
make any issue using API access token for two projects?


[image: Inline image 1]
