### ISSUE TITLE
How to know when MapView is ready for manipulation (Android)

### ISSUE THREAD

**Issue by dariav** [mapbox/mapbox-gl-native#3846]
I initialise `MapView` in fragment's `onCreateView`.

If I call any action (setLatLng, add Markers etc) on my map within onCreate (after I initialise `MapView`) it doesn't work, basically nothing happens.

I tried debugging it but no luck.

My feeling is that my map get's initialised at some later point but I can't figure out how to catch that.

**Is there a way to hook on event/listener which would be triggered once map is ready for manipulation?**

**Comment by tobrun** [comment]
@dariav Which version of the library are you using?

This sample code works with the `3.2.0` release:

```java
public class MapFragmentActivity extends AppCompatActivity {

    private static final String TAG_FRAGMENT = "map";
    private MyMapFragment mMapFragment;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_map_fragment);

        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        ActionBar actionBar = getSupportActionBar();
        if (actionBar != null) {
            actionBar.setDisplayHomeAsUpEnabled(true);
            actionBar.setDisplayShowHomeEnabled(true);
        }

        if (savedInstanceState == null) {
            FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
            transaction.add(R.id.fragment_container, mMapFragment = new MyMapFragment(), TAG_FRAGMENT);
            transaction.commit();
        } else {
            mMapFragment = (MyMapFragment) getSupportFragmentManager().findFragmentByTag(TAG_FRAGMENT);
        }
    }

    public static class MyMapFragment extends MapFragment {

        @Override
        public void onViewCreated(View view, Bundle savedInstanceState) {
            super.onViewCreated(view, savedInstanceState);

            MapView mapView = getMap();
            mapView.setStyleUrl(Style.EMERALD);
            mapView.setZoom(12);
            mapView.setLatLng(new LatLng(50.853658, 4.352419));

            // move attribution control to right of screen
            mapView.setAttributionGravity(Gravity.BOTTOM | Gravity.END);
            int tenDp =  (int) getResources().getDimension(R.dimen.attr_margin);
            mapView.setAttributionMargins(0, 0, tenDp, tenDp);
        }
    }
```

For the `4.0.0` release we are thinking making small changes to this interaction. 
Sample code for the related SNAPSHOT can be found [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/MapFragmentActivity.java)

I hope this helps resolving your problem, if not please could you add some more code to this issue. This would make investigating this a bit more efficient.  Reach out if you have any other questions.
