### ISSUE TITLE
How do i get userlocation longitude and latitude? 

### ISSUE THREAD

**Issue by abhinesh01** [mapbox/mapbox-gl-native#3850]
I like to get currentlocation longitude and latitude i even set showsUserLocation to yes, always output shows 0.00,0.000
![viewDidLoad](https://cloud.githubusercontent.com/assets/16958309/12884407/08261208-ce84-11e5-8092-46eff99e04cd.png)

**Comment by friedbunny** [comment]
`-viewDidLoad` is too early to receive user location updates, it takes at least a few cycles for the GPS/etc to return a result. Instead, listen for updates in the [`mapView:didUpdateUserLocation:`](https://www.mapbox.com/ios-sdk/api/3.1.0/Protocols/MGLMapViewDelegate.html#/c:objc(pl)MGLMapViewDelegate(im)mapView:didUpdateUserLocation:) delegate method.
