### ISSUE TITLE
Convert iOS SDK readme to native format

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3853]
It's 2016, and OS X still doesn't come with built-in Markdown rendering support. We should convert the Markdown-flavored readme and changelog bundled with the iOS SDK to HTML or RTF at build time, so developers don't have to encounter a potentially unfamiliar markup language just to get started. The readme and changelog checked into the repository would remain in Markdown format, of course.

/cc @friedbunny @boundsj

**Comment by friedbunny** [comment]
Markdown continues to serve us well and this would add complication for minimal benefit.

**Comment by 1ec5** [comment]
Maybe we could add a note to each GitHub release that links to a Markdown reader like [QLMarkdown](https://github.com/toland/qlmarkdown/) that the user could install before reading our readme?
