### ISSUE TITLE
Quickly showing and hiding a mapview results in tile not loading

### ISSUE THREAD

**Issue by quicklywilliam** [mapbox/mapbox-gl-native#3855]
If I quickly show and hide the mapview in my app over and over, eventually I'll get it into a state where the tiles will not load (or load only after an extremely long time). I cannot reproduce this issue on 3.0.1 but it reproduces on 3.1 as far back as prerelease 1.
![tilefail](https://cloud.githubusercontent.com/assets/2109/12894617/b74f97dc-ce4c-11e5-9d98-0f00ed39f22d.gif)

**Comment by 1ec5** [comment]
Possibly caused by #3448.

**Comment by 1ec5** [comment]
Are you setting the `hidden` property, or merely pushing and popping view controllers?

**Comment by quicklywilliam** [comment]
Just pushing and popping.

**Comment by quicklywilliam** [comment]
Despite the behavior changing in 3.2, this was my bug (retain cycle in one of my View Controllers). Closing.
