### ISSUE TITLE
Does the Node implementation of mapbox-gl-native support GeoJSON files with each polygon having different color/opacity?

### ISSUE THREAD

**Issue by kylehotchkiss** [mapbox/mapbox-gl-native#3857]
I am learning how to make weather maps and would like to pre-generate the images with mapbox-gl-native because trying to build an animation with them in browser can be pretty sluggish. 

I have a GeoJSON file with a bunch of polygons, and want each polygon to have different colors or opacities. It would look something like this in practice:

<img src="http://cl.ly/3R0d2m3Z2a0G/Screen%20Recording%202016-01-12%20at%2007.29%20PM.gif" width="500" />

Can mapbox-gl-native node support this (single geojson with a bunch of polygons with different display properties)?

**Comment by jfirebaugh** [comment]
Yes. To do so, add a separate layer to the style for each set of different display properties, with a `"filter"` property that selects the data from the GeoJSON source that you want to be rendered with those properties.
