### ISSUE TITLE
OnlineFileSource should throttle the number of concurrent requests

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#3858]
[Offline downloads](https://github.com/mapbox/mapbox-gl-native/pull/3715) can produce a large number of concurrent requests, bloating memory, overloading the network connection, and causing many of the requests to time out. In order to avoid these problems, OnlineFileSource should throttle concurrent requests at a reasonable number, placing throttled requests in a queue for execution once existing requests have completed.

This could be implemented in the offline code itself, but I think it makes more sense in OnlineFileSource, because there could be non-offline corner cases that also generate a large number of simultaneous requests, for example with huge screens. These should also be throttled.

**Comment by jfirebaugh** [comment]
Included in #3715.

**Comment by tmpsantos** [comment]
:+1:
