### ISSUE TITLE
NodeJS: document how to use mapbox:// tile source

### ISSUE THREAD

**Issue by abuchanan** [mapbox/mapbox-gl-native#3862]
The node readme has some example code for handling HTTP requests for tiles, and there's a section about mapbox:// style URLs, but I think it's incorrect. As far as I can tell, there's nothing about converting a mapbox:// URL into an actual URL.

Does the node library need a binding to normalize{Source,Style, etc}URL in /src/mbgl/util/mapbox.cpp?

**Comment by abuchanan** [comment]
I've used this code for now (not 100% sure it works because I get a segfault, but in theory it's good)

```npm install --save mapbox-gl```

```javascript
var request = require("request");
var mbutil = require("mapbox-gl/js/util/mapbox");

var accessToken = 'TODO KEY HERE';

var options = {
    request: function(req, callback) {

        req.url = mbutil.normalizeSourceURL(req.url, accessToken);

        var opts = {
            url: req.url,
            encoding: null,
            gzip: true
        };

        request(opts, function (err, res, body) {
            if (err) {
                callback(err);
            } else if (res.statusCode == 200) {
                var response = {};

                if (res.headers.modified) { response.modified = new Date(res.headers.modified); }
                if (res.headers.expires) { response.expires = new Date(res.headers.expires); }
                if (res.headers.etag) { response.etag = res.headers.etag; }

                response.data = body;

                callback(null, response);
            } else {
                callback(new Error(JSON.parse(body).message));
            }
        });
    },
    ratio: 1
};
```

**Comment by jfirebaugh** [comment]
@abuchanan -- Wanted to flag https://www.mapbox.com/blog/mapbox-studio-tiles-static/ for you if you hadn't seen it already. If you're trying to render tiles or static images from hosted styles, this API might make things way easier for you.

**Comment by mikemorris** [comment]
Thanks for flagging this and sorry for the slow response here @abuchanan. You're right that the section about `mapbox://` style URLs is incorrect, "converting a `mapbox://` URL into an actual URL" is something that used to happen internally, [before the `FileSource` object was given the responsibility of handling these URLs](https://github.com/mapbox/mapbox-gl-native/pull/1607). This example was added in https://github.com/cutting-room-floor/node-mapbox-gl-native/pull/130 and looking back now I'm guessing it never worked as expected.

If you're just looking to render tiles or static images from hosted styles, I'll reiterate that https://www.mapbox.com/api-documentation/#static would be the easiest way to do this. If your needs are more complex, then you're correct that you will have to implement the conversion from `mapbox://` URLs in the `FileSource` manually. I think writing Node.js bindings to [src/mbgl/util/mapbox.cpp](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/util/mapbox.cpp) would be a bit of a wasted effort, as this is pretty straightforward to handle in JavaScript, as you found in [`require('mapbox-gl/js/util/mapbox')`](https://github.com/mapbox/mapbox-gl-js/blob/master/js/util/mapbox.js).

It's possible that breaking this normalization out into a standalone module like `mapbox-gl-url` would make this a bit simpler, I opened an issue proposing this at https://github.com/mapbox/mapbox-gl-js/issues/2416

**Comment by charandas** [comment]
For anyone else, who trips on here looking to load `mapbox://` style URLs, this package does a lot of heavy lifting, and you may wanna try it out.

https://github.com/consbio/mbgl-renderer
