### ISSUE TITLE
Mapbox 3.1 dynamic framework has minimum deployment target of iOS 9.3; should be 8.0

### ISSUE THREAD

**Issue by parrots** [mapbox/mapbox-gl-native#3870]
When trying to archive for TestFlight today after updating MapBox, I received a validation warning when submitting to the App Store. Looks like MapBox is referencing 9.3 in the target? Was the dynamic framework you're referencing in the podspec created using the Xcode beta?

![screen shot 2016-02-09 at 5 05 10 pm](https://cloud.githubusercontent.com/assets/171163/12932138/4ac18ed2-cf4f-11e5-8fa5-d73484d9a21b.png)

**Comment by 1ec5** [comment]
You caught me red-handed! Looks like my `xcode-select` was set to Xcode 7.3 beta 1 and I hadn’t noticed. The real bug, though, is that the dynamic framework’s build configuration doesn’t have `IPHONEOS_DEPLOYMENT_TARGET` set to 8.0 as it should. Looks like we only set that in the gyp files for the static library and iosapp targets, but not the intervening dynamic framework target.

**Comment by parrots** [comment]
I assume we'll see a quick 3.1.1 release or will this be able to be re-deployed for 3.1?

**Comment by 1ec5** [comment]
Yes, I have a fix in #3872 and we’ll roll it into 3.1.1 this week. Thank you for your timely report.
