### ISSUE TITLE
Tapping the callout view no longer notifies the delegate

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#3871]
Tapping the callout view no longer notifies the delegate because the delegate method name was changed in MGLMapView.mm. (Note that tapping the accessory views still work, but not the callout itself.)

The delegate method is defined here: https://github.com/nfarina/calloutview/blob/2aede5d8d1577101bf18405246220e7a710df607/SMCalloutView.h#L115

See comment:
https://github.com/mapbox/mapbox-gl-native/commit/11d99bd890ef2cbadc16beb7289dd818fa86c9df#commitcomment-15993054

**Comment by 1ec5** [comment]
Fixed in #3875, which will appear in a 3.1.1 release this week.
