### ISSUE TITLE
How do I use CustomLayers in mapbox android sdk (3.2.0)?

### ISSUE THREAD

**Issue by MiguelFale** [mapbox/mapbox-gl-native#3884]
Hello. I'm initializing the constructor like this:

CustomLayer c = new CustomLayer("Things",getActivity(),initializeFunc,renderFunc,deinitFunc);

I'm just not sure what I'm supposed to do for each of the three functions?

**Comment by jfirebaugh** [comment]
Sorry, this isn't a public API.
