### ISSUE TITLE
iOS bindings for offline API

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#3892]
Previously: #584, #3715.

We now have an mbgl-core offline API for which iOS bindings need to be written.

**Comment by igrrik** [comment]
@jfirebaugh Hello!

I have a question about offline maps. How will it work? Will there be a possibility to download specific region on a map, that I can choose, or just standard download of full area like state or province?

**Comment by jfirebaugh** [comment]
@igrrik -- You'll be able to choose a bounding box and zoom range.

**Comment by skelevra** [comment]
What about downloading multiple areas ? Will it be possible to download for example an area A with bounding box SW: 9.123456, 54.123456 NE: 9.654321, 54.654321 with the zoom range of 11 to 15 and then select another area B like SW: 7.123456, -60.123456 NE: 7.654321, -60.654321 with zoom range 13 to 17 ?

**Comment by jfirebaugh** [comment]
@skelevra Yes, that's possible, and where the regions overlap, they'll share resources.

**Comment by RomainQuidet** [comment]
@1ec5 Hi, anyone working on that on your side? I've seen an Android branch. What's the strategy for iOS?

**Comment by 1ec5** [comment]
Yes, I'm working on this now. (The Android side has been making more progress at the moment because I've been focused on getting 3.1.x out the door.)

**Comment by RomainQuidet** [comment]
@1ec5 no problem, I was wondering if I could do it.
