### ISSUE TITLE
Adding layers in mapbox

### ISSUE THREAD

**Issue by divya1c** [mapbox/mapbox-gl-native#3893]
Hi! 

I am trying to understand mapbox gl, so as to shift from mapnik. I was looking into how layers are added and couldn't figure out how to add a layer based on some values in my data, without using mapbox studio. 

I have data with a value x, and i want to add a layer that represents all points with x=0. How do I create a layer without using the studio gui? Thanks!

**Comment by jfirebaugh** [comment]
Hi @divya1c. Adding layers dynamically is not yet possible with mapbox-gl-native. We're working on a "Style API" that will have this feature: #837.

**Comment by divya1c** [comment]
Is it possible to add a style to a layer based on if x=0? I see its possible in CartoCSS this way - #world[population > 100]

**Comment by jfirebaugh** [comment]
@divya1c Check out https://www.mapbox.com/help/ if you have further support questions.
