### ISSUE TITLE
Implement App Turnstile Event

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#3897]
As part of [Android Telemetry](https://github.com/mapbox/mapbox-gl-native/issues/2421), the SDK needs to implement the App Turnstile event.  This is similar to #3889, but should be implemented first.

**Comment by bleege** [comment]
Documenting current setup in iOS:

* [`MGLEventTypeAppUserTurnstile`](https://github.com/mapbox/mapbox-gl-native/blob/44ec2ad0ee644322d433d16875301a1398fb4253/platform/ios/src/MGLMapboxEvents.m#L19)
* [`pushTurnstileEvent:`](https://github.com/mapbox/mapbox-gl-native/blob/44ec2ad0ee644322d433d16875301a1398fb4253/platform/ios/src/MGLMapboxEvents.m#L428-L464)
* ["Ensure that the Turnstile Event is sent even if Telemetry is paused"](https://github.com/mapbox/mapbox-gl-native/blob/44ec2ad0ee644322d433d16875301a1398fb4253/platform/ios/src/MGLMapboxEvents.m#L605-L618)
 * ["Turnstile Event sent on MapLoad"](https://github.com/mapbox/mapbox-gl-native/commit/9891d0eb794df7a6fa69afd5c56bc371101d41fc#diff-6e8e31cd0ffe52aeda9c8b2671bcea19)
  * [Code](https://github.com/mapbox/mapbox-gl-native/blob/9891d0eb794df7a6fa69afd5c56bc371101d41fc/platform/ios/src/MGLMapboxEvents.m#L489-L492)

**Comment by bleege** [comment]
Initial implementation of Turnstile and Map Load are built.  Testing is needed to verify.  Also, I punted on the the "Push Enabled" key on the Map Load event as this is iOS in nature.  Need to confirm that on Android we'll use this to mean [Cloud Messaging](https://developers.google.com/cloud-messaging/).

**Comment by bleege** [comment]
Google's [example code](https://github.com/googlesamples/google-services/tree/master/android/gcm) for how to implement Google Cloud Messaging in Android apps.  Will investigate to see what hooks / tech is being used that Telemetry can detect for.

**Comment by boundsj** [comment]
@bleege I'm not sure if this is useful info for you but I recently merged https://github.com/mapbox/mapbox-gl-native/pull/3713

The idea is that we now only send turnstile when the map loads instead of when telemetry is inited

**Comment by boundsj** [comment]
Oh! Nvm, I see you listed it above now.

**Comment by bleege** [comment]
@boundsj Actually, thanks for the link to the ticket #3713!  I discovered the commit in `master` the other day but couldn't find the larger ticket.

**Comment by bleege** [comment]
Discovered in Google's sample app, that the client requires [Google Play Services library](https://github.com/googlesamples/google-services/blob/c307cf392a975e1a38596011b28a6951ba92cff5/android/gcm/app/build.gradle#L29) to run.  Based on this we can do a runtime classpath search for a member class of this library (such as [`GcmListenerService`](https://github.com/googlesamples/google-services/blob/c307cf392a975e1a38596011b28a6951ba92cff5/android/gcm/app/src/main/java/gcm/play/android/samples/com/gcmquickstart/MyGcmListenerService.java#L29) and if it's found then mark "Push Enabled" as `true` otherwise default it to `false`.

**Comment by bleege** [comment]
Just looking now at the newly minted V2 of the Events API, `Push Enabled` is no longer in it so there's no need to worry about this attribute.  Next action will be to confirm that `Map Load` and `Turnstile` are being sent as expected and then merge.

The plan will be to double back after initial implementation of these events and the remaining Interaction Events in #3889 and convert them and the server URL to V2.

/cc @camilleanne @mick

**Comment by bleege** [comment]
I refactored the control logic for sending in the Turnstile Event and confirmed that it sends it in at Map Load time.  I also confirmed that Map Load only is sent when the MapView is initially created and won't resend on device rotation which recreates the MapView instance as that's just how the Android lifecycle rolls.

The Turnstile Event and Map Load events use the same "send data to Mapbox" HTTP infrastructure as the Location events do.  However during testing the server responds with an HTTP 500 error code when Turnstile and Map Load are sent in, but HTTP 204 all good code when Location is sent in (see below).  This tells me that there's still some validation logic that's getting tripped up on the server.  I'm not too worried about this as this is V1 of the API and the staging server is in a bit of transient state these days.  I'm going to merge this code in now and will confirm that everything is 100% A-OK when the migration to V2 happens.

```
02-18 10:50:34.044 22101-22486/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: url = https://cloudfront-staging.tilestream.net/events/v1?access_token=sk.eyJ1IjoiYmxlZWdlIiwiYSI6InNpcml1c2x5In0.KyT-boMyC_xZYTYojTc8zg
02-18 10:50:40.864 22101-22486/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: Response Code from Mapbox Events Server: 500 for 3 events sent in.
02-18 10:51:14.662 22101-22101/com.mapbox.mapboxsdk.testapp I/LocationServices: onLocationChanged()...Location[network 43.054829,-89.443154 acc=18 et=+4d13h40m52s958ms {Bundle[mParcelledData.dataSize=696]}]
02-18 10:51:14.665 22101-22101/com.mapbox.mapboxsdk.testapp D/TelemLocationReceiver: location received = Location[network 43.054829,-89.443154 acc=18 et=+4d13h40m52s958ms {Bundle[mParcelledData.dataSize=696]}]
02-18 10:52:15.851 22101-23867/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: original = 8a07f5a6-cde5-4aea-a083-c81c2938fe3f; hex = 2E7BD9E094FF09ADCCFA8312897DB49E0DAA5182
02-18 10:52:18.642 22101-23867/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: url = https://cloudfront-staging.tilestream.net/events/v1?access_token=sk.eyJ1IjoiYmxlZWdlIiwiYSI6InNpcml1c2x5In0.KyT-boMyC_xZYTYojTc8zg
02-18 10:52:23.871 22101-23867/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: Response Code from Mapbox Events Server: 204 for 1 events sent in.
```

**Comment by bleege** [comment]
Rebased and Merged.
