### ISSUE TITLE
[iOS] Invalid sdk value

### ISSUE THREAD

**Issue by BFTE** [mapbox/mapbox-gl-native#3902]
Hi, I got some troubles when uploading binary to testflight. Last version of 3.1.0 (https://github.com/mapbox/mapbox-gl-native/commit/8f48d64c0f16a2d0ba73affe62d6da68ca6f3fcd) linked (using dynamic framework).
For some reason the downloaded Mapbox.framework is built agains iOS 9.3:

> ERROR ITMS-90512: "Invalid sdk value. The value provided for the sdk portion of LC_VERSION_MIN_IPHONEOS in myappname.app/Frameworks/Mapbox.framework/Mapbox is 9.3 which is greater than the maximum allowed value of 9.2."

**Comment by 1ec5** [comment]
Fixed in #3872, which is in [v3.1.1-pre.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.1.1-pre.1).
