### ISSUE TITLE
tapOnCalloutForAnnotation not working on 3.1

### ISSUE THREAD

**Issue by ultranano** [mapbox/mapbox-gl-native#3906]
Hi All!

I use delegate method "tapOnCalloutForAnnotation" on markers for open Viewcontrollers clicking on tooltip with description. It's working well on 3.0 but now with version 3.1 seems that the method is never called. Only "didSelectAnnotation" work fine.

Platform: iOS 
Xcode: 7.2
Tested on iOS 9

i'll wait your comments.

Thanks!

**Comment by 1ec5** [comment]
Fixed in #3875, which is in [v3.1.1-pre.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.1.1-pre.1).

**Comment by ultranano** [comment]
Thanks @1ec5! How I can download this version on cocoapods?

**Comment by 1ec5** [comment]
```ruby
pod 'Mapbox-iOS-SDK', :podspec => 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/ios-v3.1.1-pre.1/ios/Mapbox-iOS-SDK.podspec'
```
