### ISSUE TITLE
Android Telemetry User Opt Out UI

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#3907]
Users of apps running Mapbox Android SDK should always have the ability to opt out of [Telemetry data collection](https://github.com/mapbox/mapbox-gl-native/issues/2421).

This ticket will be about building an Opt Out control into the Mapbox Android TestApp that can be used as an example to implementing developers of how to do this.

**Comment by mikemorris** [comment]
On iOS, we [moved the telemetry opt-out](https://github.com/mapbox/mapbox-gl-native/pull/3445) into the :information_source: button so that developers integrating the SDK don't have to go through an extra step of configuring their own opt-out - it's just there already by default.

**Comment by bleege** [comment]
Will follow iOS lead and build this into the MapView itself.  Here's what it'll look like on the Map Attribution list:

![device-2016-02-11-121108](https://cloud.githubusercontent.com/assets/989928/12989100/9b111d3e-d0b8-11e5-8a23-5b28352ba224.png)

**Comment by bleege** [comment]
Refactored Telemetry infrastructure to support enabling and disabling.  Added UI to allow end users to toggle between the two choices.  The choice is persisted in the SDK's private SharedPreferences file.

![device-2016-02-11-182732](https://cloud.githubusercontent.com/assets/989928/12997340/2315039c-d0ed-11e5-832b-53a6e17a9d8e.png)
_UI To Enable / Disable Telemetry_

**Comment by bleege** [comment]
Tested, Rebased, and Merged!  :ballot_box_with_check:

**Comment by bleege** [comment]
As @mikemorris points out I forgot to put Telemetry explanatory text into the dialog.  Will take care of that.

**Comment by bleege** [comment]
Goal -->

![screen shot 2016-02-12 at 9 52 28 am](https://cloud.githubusercontent.com/assets/989928/13015511/5e50dcfc-d16e-11e5-8e64-e3bae90ab89f.png)

**Comment by bleege** [comment]
Added description to mirror content and layout of iOS.

<img width="499" alt="screen shot 2016-02-12 at 4 23 07 pm" src="https://cloud.githubusercontent.com/assets/989928/13024103/41718334-d1a5-11e5-97ec-6e3f93045719.png">

**Comment by bleege** [comment]
Tested, Rebased, and Merged.
