### ISSUE TITLE
Static framework can't find bundled resources

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#3910]
Our `NSBundle` category `mgl_frameworkBundle` currently looks in `privateFrameworksPath` for the static framework's bundled resources, but this does not exist and crashes at launch:

```
*** Terminating app due to uncaught exception 'Resource not found', reason: 'The resource named “mapbox.png” could not be found in the Mapbox framework bundle.'
```

Logging:

```
staticframework[2749:963222] bundle path: /var/mobile/Containers/Bundle/Application/0CED4132-F626-4ACF-BFDB-647E498E1207/staticframework.app/PrivateFrameworks/Mapbox.framework
staticframework[2749:963222] bundle: (null)
```

It looks like we may want to include a separate Mapbox.bundle that gets copied into the app bundle, [specifically defined](https://guides.cocoapods.org/syntax/podspec.html#resources) in our podspec.

Refs https://github.com/mapbox/mapbox-gl-native/issues/3656#issuecomment-182941278, which also points out that our installation instructions appear to be wrong for the static framework.

/cc @1ec5

**Comment by 1ec5** [comment]
> It looks like we may want to include a separate Mapbox.bundle that gets copied into the app bundle, [specifically defined](https://guides.cocoapods.org/syntax/podspec.html#resources) in our podspec.

That wasn’t necessary for 3.0.1, which was distributed only as a static framework with no standalone bundle.

**Comment by 1ec5** [comment]
As long as Mapbox.framework is embedded in the application bundle, there’s no need for a separate Mapbox.bundle. That’s the whole point of distributing a static framework as opposed to a static library.

**Comment by millenbop** [comment]
We used to use `cocoapods` but cannot anymore since we need iOS7 support (MGL is set to iOS8 now), so need to manually add the static library instead, and I get the same error @friedbunny initially posted. How should the project be configured for this to work? I just dragged and dropped the framework but doesn't seem to be enough.

**Comment by 1ec5** [comment]
@millenbop, please refer to the installation instructions in the README.md included in the download. Make sure to add all the frameworks and flags listed there.

**Comment by millenbop** [comment]
Thanks! I just looked at the doc at `cocoapods`, my bad, thanks for pointing me to the README.md :)
