### ISSUE TITLE
enabled property of MGLAnnotationImage is being ignored

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-gl-native#3912]
I'm seeing this on the Mapbox iOS SDK 3.1.0.  Every MGLAnnotationImage instance on the map with `enabled = NO` will still hit the `mapView:didSelectAnnotation:` delegate method when tapped.

**Comment by 1ec5** [comment]
This was fixed in #3898. Please see if the problem reproduces in [v3.1.1-pre.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.1.1-pre.1). We’ll have 3.1.1 out soon.
