### ISSUE TITLE
App crashing saying:[mapbox://sprites/mapbox/streets-v8@2x.json]: The request timed out.

### ISSUE THREAD

**Issue by abhinesh01** [mapbox/mapbox-gl-native#3918]
libc++abi.dylib: terminating with uncaught exception of type mbgl::util::SpriteLoadingException: Failed to load [mapbox://sprites/mapbox/streets-v8@2x.json]: The request timed out.

![screen shot 2016-02-12 at 12 37 34 pm](https://cloud.githubusercontent.com/assets/16958309/13000839/7a8bad90-d185-11e5-983f-950c26c74f50.png)

**Comment by 1ec5** [comment]
The code you’ve included above probably doesn’t have anything to do with the error you’re seeing. We’ve received reports of this error under a slow Internet connection (#2328) or in Airplane Mode (#3280), but have been unable to reproduce it so far. Was the debugger stopped on a breakpoint before this happened, by any chance?
