### ISSUE TITLE
Custom InfoWindowAdapter

### ISSUE THREAD

**Issue by kevincyh** [mapbox/mapbox-gl-native#3920]
How do i achieve the speech bubble pointy side when i am making a custom InfoWindowAdapter ??

![screenshot_2016-02-12-15-41-58](https://cloud.githubusercontent.com/assets/12988766/13001420/9c33bc88-d1a0-11e5-98bf-ebe800738bb4.png)

![screenshot_2016-02-12-15-49-02](https://cloud.githubusercontent.com/assets/12988766/13001419/9c304d64-d1a0-11e5-9e8e-81de1424f7b2.png)

**Comment by kevincyh** [comment]
Currently using android sdk 3.2.0

**Comment by tobrun** [comment]
@kevincyh, you can have a look how we are implementing this in the SDK:

The InfoWindow shown in the first screenshot is constructed out of 2 views:
 - InfoWindowView
 - InfoWindowTipView (the pointy part)

Note that there are multiple ways of achieving this effect and we are currently not :100: satisfied with current implementation.

If you want more information about this or other ways,  I would suggest searching on StackOverflow. 
This request is related to the Android SDK related and not Mapbox SDK. 

Reach out if you have any other questions!
