### ISSUE TITLE
SDK can manage permission check/result

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3921]
Currently the SDK has made managing permissions a responsibility of the end developer. We should make it able to manage the permission checks and result from the SDK. This will mean we are going to add another lifecycle method: `onRequestPermissionsResult`. 

I'm going to base my solution on `LeakCanary`, where they are doing something similar with the write external storage permission. I'm also going to take a look at Google Maps SDK and how they are managing this. 

The use-case we should be able to cover is:
 - user location enabled attribute for MapView
 - SDK shows dialog to accept permission
 - SDK receives result from Activity and will enable/disable based on result

/cc @bleege

**Comment by bleege** [comment]
Closing this in favor of https://github.com/mapbox/mapbox-gl-native/issues/3895#issuecomment-183426333
