### ISSUE TITLE
[iOS] map consumes 40% CPU continuously — mbgl::Painter::render()

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#3922]
On master branch, with our own samples app we can navigate between different view controllers presenting a Mapbox map view.
Sometimes (I can't get the exact reproduce steps), when creating the view controller and presenting it the map starts to consumes CPU for no reason. It never stops.
See the instruments trace provided.
[InstrumentsSamples.trace.zip](https://github.com/mapbox/mapbox-gl-native/files/127699/InstrumentsSamples.trace.zip)

**Comment by 1ec5** [comment]
```
Running Time	Self (ms)		Symbol Name
36468.0ms   68.0%	85,0	 	          mbgl::MapContext::renderSync(mbgl::TransformState const&, mbgl::FrameData const&)
36253.0ms   67.6%	898,0	 	           mbgl::Painter::render(mbgl::Style const&, mbgl::FrameData const&, mbgl::SpriteAtlas&)
24947.0ms   46.5%	1311,0	 	            void mbgl::Painter::renderPass<std::__1::__wrap_iter<mbgl::RenderItem const*> >(mbgl::RenderPass, std::__1::__wrap_iter<mbgl::RenderItem const*>, std::__1::__wrap_iter<mbgl::RenderItem const*>, int, signed char)
7260.0ms   13.5%	4310,0	 	            mbgl::Style::getRenderData() const
1497.0ms    2.7%	263,0	 	            mbgl::Painter::drawClippingMasks(std::__1::set<mbgl::Source*, std::__1::less<mbgl::Source*>, std::__1::allocator<mbgl::Source*> > const&)
884.0ms    1.6%	87,0	 	            void mbgl::Painter::renderPass<std::__1::reverse_iterator<std::__1::__wrap_iter<mbgl::RenderItem const*> > >(mbgl::RenderPass, std::__1::reverse_iterator<std::__1::__wrap_iter<mbgl::RenderItem const*> >, std::__1::reverse_iterator<std::__1::__wrap_iter<mbgl::RenderItem const*> >, int, signed char)
177.0ms    0.3%	15,0	 	            mbgl::Source::updateMatrices(std::__1::array<double, 16ul> const&, mbgl::TransformState const&)
```

**Comment by RomainQuidet** [comment]
@1ec5 Seems to be a bug (for the tags), not a performance request. The maps mostly consume 1% CPU while doing nothing. The 40% case is anormal.

**Comment by 1ec5** [comment]
Had you been performing any animations up to the point where this issue began reproducing? Also, were the different view controllers sharing a single MGLMapView, or did they have different instances?

**Comment by RomainQuidet** [comment]
No animation, just creating the mapview and pushing the view controller to the navigation view controller. Each view controllers has one instance of a mapview. 
It's not happening often, I created a test app for that, got the CPU issue with 1 over 8 mapview creation.

**Comment by tmpsantos** [comment]
@RomainQuidet do you see any network activity? I'm debugging an issue where we keep requesting the same tile forever (and that would cause a repaint when the tile arrives).

**Comment by RomainQuidet** [comment]
Hi,
As you can see in the trace there’s nothing else than repaint loop. The only thread used is the map one, with the callback on the main thread. Any other threads are quiet.

**Comment by RomainQuidet** [comment]
@tmpsantos Seems to be corrected with the release 3.1.1 + master branch now.

**Comment by RomainQuidet** [comment]
The map still consumes 2% continuously, which is not great for battery life.

**Comment by 1ec5** [comment]
Did the 40% CPU usage only appear in 3.1.x? If so, it was likely fixed in #3448, and the remaining 2% would likely be addressed by #2985.

**Comment by RomainQuidet** [comment]
@1ec5 Yes it seems to be the case. Great to see that #2985 is also in the pipe !

**Comment by 1ec5** [comment]
Closing; remaining work is being tracked in #2985.
