### ISSUE TITLE
Map is is not zoom to user location 

### ISSUE THREAD

**Issue by abhinesh01** [mapbox/mapbox-gl-native#3935]
I have set setCenterCoordinate:CLLocationCoordinate2DMake coordinate point to user location
but still its zooming into some another place.
    _mapViewMB.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    
    [self.mapViewMB setCenterCoordinate:CLLocationCoordinate2DMake(_locationManager.location.coordinate.longitude, _locationManager.location.coordinate.latitude)
                            zoomLevel:11
                             animated:YES];

**Comment by 1ec5** [comment]
The easiest way to point to the user location is to set `mapViewMB.userTrackingMode = MGLUserTrackingModeFollow`. The code above appears to be using a CLLocationManager that isn’t provided by the Mapbox iOS SDK. If you need to use that location manager, please refer to Apple’s Core Location documentation.

**Comment by 1ec5** [comment]
Also, the root cause of your bug is that `CLLocationCoordinate2DMake()` takes a latitude in the first parameter and a longitude in the second parameter, not the other way around.

**Comment by abhinesh01** [comment]
How could i remove user location blue dot, i want to show only once not always?

**Comment by friedbunny** [comment]
@abhinesh01 Github is not generally meant for support (as Mapbox uses Github, in any case). The first and best place to look if you're having implementation issues is [our API docs](https://www.mapbox.com/ios-sdk/api/). If you're having trouble starting out with our iOS SDK, give [our first steps guide](https://www.mapbox.com/help/first-steps-ios-sdk/) a try.

Of course, if you find a bug, we'd always love to hear about it.
