### ISSUE TITLE
Update OkHttp To 3.1.2 To Fix Security Vulnerability

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#3938]
@swankjesse at Square just posted that they've had a [Certificate Pinning vulnerability discovered in OkHttp](https://publicobject.com/2016/02/11/okhttp-certificate-pinning-vulnerability/) and that projects using OkHttp should update to `3.1.2` immediately if on the `3.x` version of OkHttp like Mapbox is.  Mapbox Android SDK is [currently on `3.1.1` of OkHttp](https://github.com/mapbox/mapbox-gl-native/blob/f37093e108646aa1b91ea61c2456867841a29002/platform/android/MapboxGLAndroidSDK/build.gradle#L28).

Related Issues:

* #2421 
* #3888

/cc @zugaldia @tobrun

**Comment by tobrun** [comment]
Great catch @bleege!
