### ISSUE TITLE
Offline support doesn't work correctly with tile expiration

### ISSUE THREAD

**Issue by brewin** [mapbox/mapbox-gl-native#3940]
Nice work on adding offline support. It's much appreciated! Unfortunately, it is causing some problems with displaying layers that are updated very frequently, such as weather layers.
- Expires is set to -1 on the tile server, but Mapbox GL does not honor it. The tiles are cached anyway and will load with airplane mode enabled.
- The tiles are downloaded continuously and indefinitely. (Related to #3667)
- There is no way to manually refresh a layer, either by invalidating the cache or just by updating the layer on screen if there is no cache.

**Comment by jfirebaugh** [comment]
I'm not sure what you mean by "Expires is set to -1". If you mean that your tile server is sending `Expires: -1` as a response header, that is not a valid `Expires` value. The value must be an RFC 1123 formatted date.

The intended behavior for frequently updated layers requires the cooperation of the tile server:

* The tile server should send caching headers (`Expires` or `Cache-Control`) that reflect when new data will be available. I.e., an `Expires` header with the date when a new tile will be available, or a `Cache-Control` `max-age` value that is the actual refresh interval.
* When one of those headers is present, mapbox-gl-native will refresh the tile accordingly, even while that tile is visible on screen.

Sending no cache headers (or an invalid cache header such as `Expires: -1`) doesn't give mapbox-gl-native any information about when to refresh the tile, so it can only fall back to refreshing it when the map is recreated or the application is relaunched.

**Comment by brewin** [comment]
Thanks for the help. Sorry, I meant `expires` is set to -1 in the nginx configuration. According to the [docs](http://nginx.org/en/docs/http/ngx_http_headers_module.html#expires), this causes `Cache-Control: no-cache` to be sent and the `Expires` time is always the time when the tile is accessed. 

Here are all the headers sent:
```
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Mon, 15 Feb 2016 18:23:57 GMT
Content-Type: image/png
Content-Length: 320
Last-Modified: Mon, 15 Feb 2016 18:22:16 GMT
Connection: keep-alive
ETag: "56c21758-140"
Expires: Mon, 15 Feb 2016 18:23:56 GMT
Cache-Control: no-cache
Accept-Ranges: bytes
```
With these headers, the following happens:
- Dozens of tiles requests per second until the app is closed. I feel like in most cases new requests should only be made when the map is being interacted with. I know this isn't really a problem when the `Expires` time is more reasonable though.
- Tiles are cached and they are displayed even in airplane mode. For a near-realtime weather layer, cached tiles aren't useful. Upon further investigation, maybe `Cache-Control: no-store, no-cache, must-revalidate` is what I really want, but that doesn't seem to prevent caching in mapbox-gl-native either.
- Tiles are downloaded when they expire but are not refreshed on screen. Zooming in and out several times seems to refresh some of them, but not all. Closing the app and relaunching it doesn't help either. This is the main reason why I was trying to avoid caching. I want new tiles every time the app is opened. You can test it with this radar tile server that updates every 5 minutes:

source:
```json
"radar": {
      "tiles": [
          "http://mesonet.agron.iastate.edu/cache/tile.py/1.0.0/nexrad-n0q-900913/{z}/{x}/{y}.png"
      ],
      "type": "raster",
      "tileSize": 256
}
```

layer:
```json
{
      "id": "radar",
      "type": "raster",
      "source": "radar",
      "paint": {
          "raster-opacity": 0.6
      }
}
```

**Comment by brewin** [comment]
Thinking more about this, maybe an in-memory cache is the missing piece here? Tiles would be pulled from in-memory cache first. If they're missing and there is no disk cache (due to Cache-Control), then they're downloaded from the server. When the map is destroyed, the tiles are cleared. This would also benefit layers that do have a disk cache, since it would reduce the number of disk reads and should make panning and zooming the map smoother.

**Comment by jfirebaugh** [comment]
> the `Expires` time is always the time when the tile is accessed

Thanks, this is a key detail. That means the "dozens of tile requests per second" issue is the same issue as #4019.

> Tiles are cached and they are displayed even in airplane mode.

@kkaefer, what do you think about supporting some combination of `no-store` / `no-cache` / `must-revalidate` as a means of forcibly opting out of showing cached tiles while revalidation is attempted?

> Tiles are downloaded when they expire but are not refreshed on screen.

This sounds like a bug. Any tile that is successfully refreshed is supposed to be repainted immediately.

**Comment by kkaefer** [comment]
> @kkaefer, what do you think about supporting some combination of no-store / no-cache / must-revalidate as a means of forcibly opting out of showing cached tiles while revalidation is attempted?

Yes, I think we considered (implemented?) this once, but I can't find it in the current source code. Let's do this.

**Comment by brewin** [comment]
> This sounds like a bug. Any tile that is successfully refreshed is supposed to be repainted immediately.

Yeah, looks like a bug. Tiles are only repainted after zooming in and back out. You can see in the screenshot where I zoomed in on the right side and then zoomed out and panned left. The tiles on the right are fresh, while the ones on the left have been expired for 20 minutes. This is with the radar tile server I mentioned above and is using the latest 4.0.0-SNAPSHOT on a Nexus 7. Let me know if you need any more information.

![image](http://i.imgur.com/oaB9eml.jpg)

**Comment by edpop** [comment]
Hi.
Did you find any solutions to not showing old tiles?
I don't want to show traffic tiles for android when he loses internet connection.
My header `Cache-Control:no-store, no-cache, max-age=60, must-revalidate`.

**Comment by kkaefer** [comment]
We've implement support for `must-revalidate` in https://github.com/mapbox/mapbox-gl-native/pull/9670. There's no support for `no-cache`/`no-store` yet though. We highly recommend against using `no-store`. In our interpretation of the HTTP spec, `must-revalidate` implies `no-store`.
