### ISSUE TITLE
MapboxEventManager Context Leak

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3944]
`MapboxEventManager` is a **singleton** class that will live as long as the hosting application. This means that the singleton should be instantiated with the application context and not an Activity context else a memory leak will occur as shown in the screenshot below.

See this fix from `LocationServices` how to cleanly manage this https://github.com/mapbox/mapbox-gl-native/issues/3248.

![device-2016-02-15-114127](https://cloud.githubusercontent.com/assets/2151639/13046431/173461f0-d3d9-11e5-8916-ba126091056d.png)

cc @bleege @zugaldia

**Comment by bleege** [comment]
Good catch @tobrun!
