### ISSUE TITLE
Annotation detail view height not able to change

### ISSUE THREAD

**Issue by gurumaheshPCS** [mapbox/mapbox-gl-native#3950]
Hi Mapbox,

I just updated my map box framework with latest for iOS native. Still i am facing issue that i am not able add custom AccessoryView For Annotation. i can't able to increase the height of accessory view.
Please help me.

Thanks,
Gurumahesh

**Comment by 1ec5** [comment]
@gurumaheshPCS, can you provide some code to explain what you’re doing right now? Depending on what you’re trying to do with the callout view, the answer may be to use a [custom callout view](https://www.mapbox.com/ios-sdk/examples/custom-callout/). (This use case will be streamlined in #4392.)

**Comment by gurumaheshPCS** [comment]
i have tried as there in above example https://www.mapbox.com/ios-sdk/examples/custom-callout/ . But i want to increase the custom callout view height and need to show multiple buttons in the call out. but i am not able to increase the height and width.

**Comment by 1ec5** [comment]
The example uses a single UIButton for `mainBody` and fits to that view. But you could use any UIView, and instead of calling `-sizeToFit` on it, you’d give it a custom size too.
