### ISSUE TITLE
Web instructions are less clear than github instructions

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#3952]
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/INSTALL.md#dynamic-framework

Specifies to check copy items

<img width="993" alt="2016-02-15 at 11 07 am" src="https://cloud.githubusercontent.com/assets/32314/13053788/5ce2c318-d3d4-11e5-8c1f-38a667a2cc2b.png">

<img width="750" alt="2016-02-15 at 11 07 am" src="https://cloud.githubusercontent.com/assets/32314/13053792/61ae92dc-d3d4-11e5-81ef-93c20ce896b7.png">

https://www.mapbox.com/ios-sdk/#manual does not.

**Comment by friedbunny** [comment]
Fixed in the docs repo.
