### ISSUE TITLE
Don't use and/or in documentation

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#3953]
<img width="712" alt="2016-02-15 at 11 10 am" src="https://cloud.githubusercontent.com/assets/32314/13053868/b871a92e-d3d4-11e5-8b4b-419c3a7de026.png">

Why is this an and/or? This doesn't explain to users why they'd choose one, the other, or both. Be specific and helpful instead.

**Comment by friedbunny** [comment]
These instructions are intentionally minimal; if the user needs a primer on iOS development we have the first steps guide. (Which should be linked in the overview better... or at all.)

That said, we could link these keys to Apple's docs.

**Comment by friedbunny** [comment]
Going to look at removing this step from the install instructions and fleshing out the later Location services section.

**Comment by friedbunny** [comment]
Fixed in the docs repo.
