### ISSUE TITLE
Dash documentation is 404

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#3954]
<img width="876" alt="2016-02-15 at 11 11 am" src="https://cloud.githubusercontent.com/assets/32314/13053911/f44409d8-d3d4-11e5-8948-9a89c36ef8b3.png">

https://www.mapbox.com/ios-sdk/docsets/Mapbox.xml -> 404

Let's add the documentation feed or remove the link.

**Comment by 1ec5** [comment]
Good catch: the feed needs to be moved from https://www.mapbox.com/ios-sdk/api/3.1.0/docsets/Mapbox.xml to this location.

**Comment by 1ec5** [comment]
Fixed.
