### ISSUE TITLE
Inspectables for direction & pitch

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#3955]
<img width="277" alt="2016-02-15 at 11 48 am" src="https://cloud.githubusercontent.com/assets/32314/13054923/3b4d2f3a-d3da-11e5-8421-f53f87efc7a1.png">

If we add lon/lat/z, we should add pitch & bearing as well here.

**Comment by 1ec5** [comment]
I'm onboard with adding a Direction inspectable, although pitch will be a bit more interesting. MGLMapCamera exposes pitch in the context of a physical camera object located at a specific altitude above mean sea level. We can expose a simple pitch property here, but it'll be difficult to convey all the nuances without some way to provide more context.
