### ISSUE TITLE
Making documentation make sense for both obj-c and swift

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#3956]
<img width="725" alt="2016-02-15 at 12 01 pm" src="https://cloud.githubusercontent.com/assets/32314/13055182/e099d6f4-d3db-11e5-9e8a-049acd80f90b.png">

This documentation keeps mentioning `YES` as the positive value for this option, but YES is an objective-c'ism - for swift users, the value would be `true`. How do write documentation in a language-neutral way, or split suggestions like these by language?

**Comment by 1ec5** [comment]
This is essentially upstream in realm/jazzy#353, but we probably could roll our own language support using custom templates and some shell scripting.

**Comment by 1ec5** [comment]
The upstream issue is now realm/jazzy#136.

**Comment by 1ec5** [comment]
realm/jazzy#136 is fixed. We still need to replace `YES` and `NO` with `true` and `false`, respectively. For Swift 3, we may also need to remove the `NS` class prefix from Foundation classes like `NSArray` and `NSString`.

**Comment by 1ec5** [comment]
Another thing that may confuse some developers is that enumerations are respelled when bridged to Swift, for example `MGLSymbolPlacementLine` as `MGLSymbolPlacement.line`, but our documentation doesn’t mention the respelling.

**Comment by 1ec5** [comment]
This is [still on our wishlist](https://github.com/mapbox/mapbox-gl-native/projects/9#card-1170837).

**Comment by tmcw** [comment]
Please re-open under a different user, then - I don't want to be the owner of this issue.

**Comment by 1ec5** [comment]
Looks like realm/jazzy#136 tracks this issue adequately. 👍

By the way, @tmcw, you can click Unsubscribe to stop receiving notifications about this issue or others like it in the future. Hope that helps!
