### ISSUE TITLE
"Other Type Definitions" link is a 404

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#3957]
<img width="488" alt="2016-02-15 at 12 30 pm" src="https://cloud.githubusercontent.com/assets/32314/13055889/e1f1b180-d3df-11e5-9350-17a8ab82ee96.png">

goes to https://www.mapbox.com/ios-sdk/api/3.1.0/Other%20Type%20Definitions.html

**Comment by 1ec5** [comment]
jazzy thinks a couple typedefs need documentation, even though they're just typedefs of structs that are documented. We've hidden undocumented methods (to hide deprecated methods), so apparently there's nothing for the page to show.

**Comment by 1ec5** [comment]
This should be fixed upstream by realm/jazzy#475.

**Comment by friedbunny** [comment]
Confirmed fixed by jazzy 0.7.0.

**Comment by 1ec5** [comment]
We also allowed MGLOfflinePackAdditionCompletionHandler and MGLOfflinePackRemovalCompletionHandler to fall into the “Other type Definitions” section, so the section now exists with content.
