### ISSUE TITLE
Require a coordinate in the MGLPointAnnotation constructor

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#3959]
A coordinate is required to use a point annotation: let's ensure that annotations are created correctly off the bat.

**Comment by 1ec5** [comment]
A coordinate isn’t strictly required to use an MGLPointAnnotation. Unlike an MGLShape that’s initialized with no points, an MGLPointAnnotation does render on screen (at Null Island). This is probably why MapKit’s MKPointAnnotation also lacks an `-initWithCoordinate:` constructor. Such a constructor would be convenient, but we don’t need to mark it as an `NS_DESIGNATED_INITIALIZER`.

**Comment by tmcw** [comment]
Okay, cool.
