### ISSUE TITLE
XCode inline documentation shows uninterpreted Markdown

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#3961]
<img width="467" alt="2016-02-15 at 4 08 pm" src="https://cloud.githubusercontent.com/assets/32314/13060308/6aef2e2c-d3fe-11e5-9e3f-e7ec2eb790d3.png">

Lots of links that aren't links here. Would it be possible to remove or interpret Markdown in this view?

**Comment by 1ec5** [comment]
Quick Help is generated by Xcode (via Clang for Objective-C and SourceKit for Swift) based on the documentation comments in the header.

These documentation comments were copied over from the OS X SDK and were written with appledoc’s Markdown support in mind. That was before we switched from appledoc to jazzy in #3203. I think it’s unlikely that we’ll wind up with a syntax that’s simultaneously compatible with Clang’s Doxygen/HeaderDoc, SourceKit’s reStructuredText, and jazzy’s Markdown. Perhaps we can put Doxygen syntax in the header and transform it at build time for jazzy, but I’m not sure where that leaves Swift users.
