### ISSUE TITLE
My Location Turns Off But Not Back On

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#3963]
While using the 4.0.0-SNAPSHOT in an internal application tonight, I noticed that once the user location was enabled and then subsequently disabled it was impossible to re-enable it.  The app is using `MapboxMap.setMyLocationEnabled()` and was working fine up through `master` on 13-Feb-2016.  My hunch is that this has something to do with #3895.

/cc @tobrun @zugaldia

**Comment by tobrun** [comment]
Looking at this and with first tests the test app doesn't have this problem.
Will investigate edge cases.

**Comment by tobrun** [comment]
Always deny flow:
https://www.dropbox.com/s/mk9m4mbmw431yag/device-2016-02-16-095443.mp4?dl=0

**Comment by tobrun** [comment]
Accept permission flow:
https://www.dropbox.com/s/yukr4juq63u1xb7/device-2016-02-16-095625.mp4?dl=0

**Comment by tobrun** [comment]
Stripped down version (app has accepted permissions, is only calling setMyLocationEnabled(true/false):
https://www.dropbox.com/s/t77jtk490c16g75/device-2016-02-16-095840.mp4?dl=0

**Comment by tobrun** [comment]
@bleege where you able to reproduce it on master? only with this internal application?

**Comment by tobrun** [comment]
Note that this is the only line changed in the mentioned issue #3895:
 - https://github.com/mapbox/mapbox-gl-native/blob/d06a7c4b8685887cada0c5a03d7c47a7365b4f36/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java#L2552

**Comment by tobrun** [comment]
The referenced internal application has following permission enabled in `AndroidManifest`:
 >     <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

**Comment by tobrun** [comment]
I noticed that we are requiring having both permissions enabled, while having one is sufficient. I have relaxed the if check mentioned here https://github.com/mapbox/mapbox-gl-native/issues/3963#issuecomment-184586071 and moved the check from MapView to MapboxMap.
Still not sure what the problem on the internal application is..

**Comment by tobrun** [comment]
I found the problem in the code of the internal application itself.

**Comment by bleege** [comment]
Thanks for looking into this @tobrun.  Things are working in the TestApp's MainActivity as they should be.  :+1:
