### ISSUE TITLE
Course tracking should be able to go in reverse

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3964]
In MGLMapView's course tracking mode, the user puck spins around when you back up in a car, causing the map to jarringly spin around. We should notice that the bearing hasn't changed even though the course has and avoid spinning around.

/cc @zugaldia @friedbunny

**Comment by lilykaiser** [comment]
Closing due to ticket age. If this is still a problem, please re-open

**Comment by 1ec5** [comment]
This feature hasn’t been implemented yet, but the iOS navigation SDK’s (re)implementation of course tracking is much more stable, based on the route line, so I’m not sure the effect would be quite as jarring as what we saw when using the map SDK’s built-in course tracking.

/cc @ericrwolfe
