### ISSUE TITLE
Test coverage metrics

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#3973]
Whilst using GCC, there is a tool called [gcov](https://gcc.gnu.org/onlinedocs/gcc/Gcov.html) that generates test coverage data. Another tool, [lcov](http://ltp.sourceforge.net/coverage/lcov.php), generates HTML pages out of gcov data containing the source code annotated with coverage information - see this [example](http://ltp.sourceforge.net/coverage/lcov/output/index.html) of the generated HTML:
![screen shot 2016-02-16 at 2 10 44 pm]
(https://cloud.githubusercontent.com/assets/76133/13075874/2002ff38-d4b7-11e5-926c-a10fdf1dfdc5.png)
My proposal is: Add a new build targets: `check`, that ultimately runs all unit tests, collects coverage data and generates these handy HTML pages.

/cc @mapbox/mobile @mapbox/gl

**Comment by mb12** [comment]
@brunoabinader Why not just use the built in code coverage tools available under xcode?

https://developer.apple.com/videos/play/wwdc2015-410/

**Comment by tmpsantos** [comment]
> @brunoabinader Why not just use the built in code coverage tools available under xcode?
> 
> https://developer.apple.com/videos/play/wwdc2015-410/

Don't forget about us, Linux users. :wink:

Mapbox GL Native supports Linux as development platform.

**Comment by mb12** [comment]
Using xcode I would assume that we will be able to generate code coverage metrics for core, ios specific bindings as well as the ios test app and osx test app.  would gcov work for ios bindings and ios test app?

**Comment by zugaldia** [comment]
> Don't forget about us, Linux users. :wink:

Exactly. And FWIW, Android too. I like the approach of attaching the gcov and lcov targets to core, and leave the clients handle their testing (which would likely include [UI testing](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android/tests)) separate.

**Comment by brunoabinader** [comment]
> would gcov work for ios bindings and ios test app?

Yes. Both GCC and clang are capable of generating coverage files required by `lcov`.

It is important to mention that the current setup with Xcode remains unaffected by the proposed build targets.

**Comment by 1ec5** [comment]
Xcode’s code coverage functionality only works with XCTest, which at the moment we’re only using for unit tests of code shared between the iOS and OS X SDKs. mbgl tests are currently handled by gtest – would gcov and lcov be compatible with gtest?

**Comment by brunoabinader** [comment]
> would gcov and lcov be compatible with gtest?

Yes, that's precisely the intended usage - collect coverage data from on our unit tests.
