### ISSUE TITLE
Remove annotations doesn't remove polylines

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3976]
As noticed in `PolylineActivity`, the trash icon doesn't remove the polylines anymore.

**Comment by bleege** [comment]
I just successfully tested the fix using the BulkMarkerActivity in the TestApp.  The process was to add 10 markers, then switch to 1000 using the UI, then switch back to 10 using the UI.  Next up is the Polyline test.

**Comment by bleege** [comment]
Yep, PolylineActivity in the TestApp is also behaving itself.  It's removing Polylines individually and en masse.

I think we're good to go here.  :+1:
