### ISSUE TITLE
gzip telemetry events

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapbox-gl-native#3979]
Make sure that we gzip telemetry events before sending them. gzip could reduce the time the mobile radio is working, especially on slower connections, and thus reduce battery impact.

/cc @boundsj

**Comment by friedbunny** [comment]
I'm surprised that we don't do this already.

**Comment by tobrun** [comment]
If content encoding is set to gzip, this is automatically handled in the background by `Okhttp` on Android.
You can verify this is the related [unit-test](https://github.com/square/okhttp/blob/00c9db7859ed4edac380b25c3be61afd9ece0e5d/okhttp-tests/src/test/java/okhttp3/CallTest.java#L1830-L1856), here they are showing Okhttp transparent gzipping in action.

**Comment by boundsj** [comment]
There are 3rd party libs that make this transparent for iOS, too (https://github.com/AFNetworking/AFgzipRequestSerializer/blob/master/AFgzipRequestSerializer/AFgzipRequestSerializer.m?#L57) but we don't use a 3rd party dep in the iOS bindings

**Comment by mawajdak** [comment]
الشبكات
لا توجد شبكات

**Comment by friedbunny** [comment]
Resources that we can draw upon for our own GZIP implementation:

- https://github.com/mattt/Godzippa (used in AFNetworking, per above)
- https://github.com/nicklockwood/GZIP

**Comment by tobrun** [comment]
What I mentioned in https://github.com/mapbox/mapbox-gl-native/issues/3979#issuecomment-185063771 is not true. 

To GZIP our communication we need to implement the following request interceptor on OkHttp: https://github.com/square/okhttp/blob/3f7a3344a4c85aa3bbb879dabac5ee625ab987f3/samples/guide/src/main/java/okhttp3/recipes/RequestBodyCompression.java#L73

**Comment by ivovandongen** [comment]
@tobrun We're using something similar in Human too. Can take a look at that too if you want.

**Comment by mick** [comment]
The api already excepts gzip'd JSON as long as the following headers are set on the POST request:

```
Content-type: application/json
Content-Encoding: gzip
```

**Comment by bleege** [comment]
I've ticketed out the Android work in #5536.

**Comment by friedbunny** [comment]
This is done on the iOS side (#5490) and will be in the final v3.3.0 release.

**Comment by zugaldia** [comment]
Work for Android was done in https://github.com/mapbox/mapbox-gl-native/issues/5536 and for iOS in https://github.com/mapbox/mapbox-gl-native/pull/5490. I think we're good to close here.
