### ISSUE TITLE
Revisit std::map and std::set usage

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#3980]
As flagged by https://github.com/mapbox/mapbox-gl-native/issues/3179, we use `std::set` and `std::map` in places where ordering is not important. In these cases, we should replace with the `unordered` versions of these containers (faster).

/cc @daniel-j-h

**Comment by bleege** [comment]
Based on some initial testing @lucaswoj and I have discovered that not all `std::set` and `std::map` can be converted to their `unordered` versions as there still is code in Core GL that relies on their implicit ordering.  @jfirebaugh also mentioned that there are places were this is explicitly noted in the source code as well.  To make life easier and more transparent, @lucaswoj and I will document these cases as we encounter them in the table below:

map or set | file
---------- | ----
map | mbgl::annotation::annotatation_manager.hpp

**Comment by lucaswoj** [comment]
Here's a checklist of all uses of `std::set` and `std::map`. We'll check each off as we switch it to  the unordered version or discover a reason that it cannot be switched.

- [ ] `./src/clipper/clipper.cpp:4707:                                std::set<int> & visited,`
- [ ] `./src/clipper/clipper.cpp:4830:        std::set<int> visited;`
- [ ] `./src/clipper/clipper.hpp:387:                         std::set<int> & visited,`
- [ ] `./src/mbgl/algorithm/generate_clip_ids.cpp:34:std::map<UnwrappedTileID, ClipID> ClipIDGenerator::getStencils() const {`
- [ ] `./src/mbgl/algorithm/generate_clip_ids.cpp:35:    std::map<UnwrappedTileID, ClipID> stencils;`
- [ ] `./src/mbgl/algorithm/generate_clip_ids.hpp:20:        std::set<CanonicalTileID> children;`
- [ ] `./src/mbgl/algorithm/generate_clip_ids.hpp:31:    std::map<UnwrappedTileID, ClipID> getStencils() const;`
- [ ] `./src/mbgl/algorithm/update_renderables.hpp:24:    std::set<UnwrappedTileID> checked;`
- [ ] `./src/mbgl/annotation/annotation_manager.hpp:70:    using SymbolAnnotationMap = std::map<AnnotationID, std::shared_ptr<SymbolAnnotationImpl>>;`
- [ ] `./src/mbgl/annotation/annotation_manager.hpp:71:    using ShapeAnnotationMap = std::map<AnnotationID, std::unique_ptr<ShapeAnnotationImpl>>;`
- [ ] `./src/mbgl/annotation/annotation_manager.hpp:76:    std::set<std::string> obsoleteShapeAnnotationLayers;`
- [ ] `./src/mbgl/annotation/annotation_manager.hpp:77:    std::set<AnnotationTile*> tiles;`
- [ ] `./src/mbgl/geometry/glyph_atlas.cpp:33:    const std::map<uint32_t, SDFGlyph>& sdfs = glyphSet.getSDFs();`
- [ ] `./src/mbgl/geometry/glyph_atlas.cpp:55:    std::map<uint32_t, GlyphValue>& face = index[fontStack];`
- [ ] `./src/mbgl/geometry/glyph_atlas.cpp:114:        std::map<uint32_t, GlyphValue>& face = faces.second;`
- [ ] `./src/mbgl/geometry/glyph_atlas.hpp:49:        std::set<uintptr_t> ids;`
- [ ] `./src/mbgl/geometry/glyph_atlas.hpp:58:    std::unordered_map<FontStack, std::map<uint32_t, GlyphValue>, FontStackHash> index;`
- [ ] `./src/mbgl/geometry/line_atlas.hpp:45:    std::map<size_t, LinePatternPos> positions;`
- [ ] `./src/mbgl/gl/gl.cpp:101:static std::map<GLint, unsigned int> bindingToSizeMap;`
- [ ] `./src/mbgl/gl/gl.cpp:105:static std::map<GLint, GLsizeiptr> bufferBindingToSizeMap;`
- [ ] `./src/mbgl/gl/gl.cpp:109:static std::map<GLuint, GLuint> vertexArrayToArrayBufferMap;`
- [ ] `./src/mbgl/renderer/painter.cpp:83:    const std::set<Source*>& sources = renderData.sources;`
- [ ] `./src/mbgl/renderer/painter.hpp:108:    void drawClippingMasks(PaintParameters&, const std::map<UnwrappedTileID, ClipID>&);`
- [ ] `./src/mbgl/renderer/painter_clipping.cpp:12:void Painter::drawClippingMasks(PaintParameters& parameters, const std::map<UnwrappedTileID, ClipID>& stencils) {`
- [ ] `./src/mbgl/renderer/render_item.hpp:34:    std::set<style::Source*> sources;`
- [ ] `./src/mbgl/renderer/symbol_bucket.hpp:100:    std::map<std::u32string, std::vector<Anchor>> compareText;`
- [ ] `./src/mbgl/renderer/symbol_bucket.hpp:130:    std::set<GlyphRange> ranges;`
- [ ] `./src/mbgl/sprite/sprite_atlas.hpp:91:    std::map<Key, Holder> images;`
- [ ] `./src/mbgl/sprite/sprite_atlas.hpp:92:    std::set<std::string> uninitialized;`
- [ ] `./src/mbgl/sprite/sprite_parser.hpp:27:using Sprites = std::map<std::string, SpriteImagePtr>;`
- [ ] `./src/mbgl/sprite/sprite_store.hpp:17:    using Sprites = std::map<std::string, std::shared_ptr<const SpriteImage>>;`
- [ ] `./src/mbgl/storage/network_status.cpp:14:std::set<util::AsyncTask *> NetworkStatus::observers;`
- [ ] `./src/mbgl/style/paint_property.hpp:99:    std::map<ClassID, PropertyValue<T>> values;`
- [ ] `./src/mbgl/style/paint_property.hpp:100:    std::map<ClassID, TransitionOptions> transitions;`
- [ ] `./src/mbgl/style/parser.cpp:237:    std::set<FontStack> result;`
- [ ] `./src/mbgl/style/source_impl.cpp:76:const std::map<UnwrappedTileID, RenderTile>& Source::Impl::getRenderTiles() const {`
- [ ] `./src/mbgl/style/source_impl.cpp:108:    std::set<OverscaledTileID> retain;`
- [ ] `./src/mbgl/style/source_impl.hpp:62:    const std::map<UnwrappedTileID, RenderTile>& getRenderTiles() const;`
- [ ] `./src/mbgl/style/source_impl.hpp:99:    std::map<OverscaledTileID, std::unique_ptr<Tile>> tiles;`
- [ ] `./src/mbgl/style/source_impl.hpp:100:    std::map<UnwrappedTileID, RenderTile> renderTiles;`
- [ ] `./src/mbgl/style/update_batch.hpp:11:    std::set<std::string> sourceIDs;`
- [ ] `./src/mbgl/text/collision_tile.cpp:159:    std::unordered_map<std::string, std::set<std::size_t>> sourceLayerFeatures;`
- [ ] `./src/mbgl/text/glyph.hpp:43:typedef std::map<uint32_t, Glyph> GlyphPositions;`
- [ ] `./src/mbgl/text/glyph_set.cpp:29:const std::map<uint32_t, SDFGlyph> &GlyphSet::getSDFs() const {`
- [ ] `./src/mbgl/text/glyph_set.cpp:74:void justifyLine(std::vector<PositionedGlyph> &positionedGlyphs, const std::map<uint32_t, SDFGlyph> &sdfs, uint32_t start,`
- [ ] `./src/mbgl/text/glyph_set.hpp:11:    const std::map<uint32_t, SDFGlyph> &getSDFs() const;`
- [ ] `./src/mbgl/text/glyph_set.hpp:19:    std::map<uint32_t, SDFGlyph> sdfs;`
- [ ] `./src/mbgl/text/glyph_store.cpp:31:bool GlyphStore::hasGlyphRanges(const FontStack& fontStack, const std::set<GlyphRange>& glyphRanges) {`
- [ ] `./src/mbgl/text/glyph_store.hpp:37:    bool hasGlyphRanges(const FontStack&, const std::set<GlyphRange>&);`
- [ ] `./src/mbgl/text/glyph_store.hpp:55:    std::unordered_map<FontStack, std::map<GlyphRange, std::unique_ptr<GlyphPBF>>, FontStackHash> ranges;`
- [ ] `./src/mbgl/tile/tile_cache.hpp:25:    std::map<OverscaledTileID, std::unique_ptr<Tile>> tiles;`
- [ ] `./src/mbgl/tile/tile_worker.cpp:58:    std::set<std::string> parsed;`
- [ ] `./src/mbgl/tile/vector_tile.cpp:52:    std::map<std::string, uint32_t> keysMap;`
- [ ] `./src/mbgl/tile/vector_tile.cpp:71:    mutable std::map<std::string, VectorTileLayer> layers;`
- [ ] `./src/mbgl/util/merge_lines.cpp:8:using Index = std::map<size_t, unsigned int>;`
- [ ] `./src/mbgl/util/merge_lines.hpp:12:                            std::map<std::string, unsigned int> &rightIndex,`
- [ ] `./src/mbgl/util/merge_lines.hpp:13:                            std::map<std::string, unsigned int>::iterator left,`
- [ ] `./src/mbgl/util/merge_lines.hpp:18:                           std::map<std::string, unsigned int> &leftIndex,`
- [ ] `./src/mbgl/util/merge_lines.hpp:20:                           std::map<std::string, unsigned int>::iterator right,`
- [ ] `./src/mbgl/util/url.cpp:23:            encoded << '%' << std::setw(2) << int(c);`
- [ ] `./include/mbgl/storage/network_status.hpp:31:    static std::set<util::AsyncTask*> observers;`

**Comment by lucaswoj** [comment]
- [ ] `./src/clipper/clipper.cpp:4707:                                std::set<int> & visited,`
 - [ ] `./src/clipper/clipper.cpp:4830:        std::set<int> visited;`
 - [ ] `./src/clipper/clipper.hpp:387:                         std::set<int> & visited,`
 - [ ] `./src/mbgl/algorithm/generate_clip_ids.hpp:20:        std::set<CanonicalTileID> children;`
 - [ ] `./src/mbgl/algorithm/update_renderables.hpp:24:    std::set<UnwrappedTileID> checked;`
 - [ ] `./src/mbgl/geometry/glyph_atlas.hpp:49:        std::set<uintptr_t> ids;`
 - [ ] `./src/mbgl/renderer/painter.cpp:83:    const std::set<Source*>& sources = renderData.sources;`
 - [ ] `./src/mbgl/renderer/render_item.hpp:34:    std::set<style::Source*> sources;`
 - [ ] `./src/mbgl/renderer/symbol_bucket.hpp:130:    std::set<GlyphRange> ranges;`
 - [ ] `./src/mbgl/sprite/sprite_atlas.hpp:92:    std::set<std::string> uninitialized;`
 - [ ] `./src/mbgl/storage/network_status.cpp:14:std::set<util::AsyncTask *> NetworkStatus::observers;`
 - [ ] `./src/mbgl/style/parser.cpp:237:    std::set<FontStack> result;`
 - [ ] `./src/mbgl/style/source_impl.cpp:108:    std::set<OverscaledTileID> retain;`
 - [ ] `./src/mbgl/style/update_batch.hpp:11:    std::set<std::string> sourceIDs;`
 - [ ] `./src/mbgl/text/collision_tile.cpp:159:    std::unordered_map<std::string, std::set<std::size_t>> sourceLayerFeatures;`
 - [ ] `./src/mbgl/text/glyph_store.cpp:31:bool GlyphStore::hasGlyphRanges(const FontStack& fontStack, const std::set<GlyphRange>& glyphRanges) {`
 - [ ] `./src/mbgl/text/glyph_store.hpp:37:    bool hasGlyphRanges(const FontStack&, const std::set<GlyphRange>&);`
 - [ ] `./src/mbgl/tile/tile_worker.cpp:58:    std::set<std::string> parsed;`
 - [ ] `./src/mbgl/util/url.cpp:23:            encoded << '%' << std::setw(2) << int(c);`

**Comment by jfirebaugh** [comment]
`src/clipper` is third-party code and as a rule we avoid modifying it. `std::setw` is a false positive. All the others look like legitimate candidates.

**Comment by lucaswoj** [comment]
# High Level Todo

 - [ ] audit and fix all uses of `std::set`
 - [ ] audit and fix all uses of `std::map`
 - [x] audit and fix all uses of `std::multimap`
 - [ ] explore static analysis tools to check future uses

**Comment by lucaswoj** [comment]
Re-opening. @bleege has merged his PR addressing `std::map` usage. My PR addressing `std::set` usage is still pending. There are also a few cases that were not resolved in either PR that should 

 - be ticketed out separately
 - keep this Issue open
 - be commented in the source with an explanation of why they are ordered (if not obvious)

**Comment by bleege** [comment]
Re-opening as my fixit PR #6336 closed this automatically.
