### ISSUE TITLE
worker usage should be customizable

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#3982]
For node, we don't want to spawn four threads for each Map instance. Instead, the node thread pool should be used.

Worker needs to be more like FileSource -- an abstract interface that can be replaced with different implementations depending on the platform.

**Comment by tmpsantos** [comment]
Wouldn't make `mbgl::Worker` thread-safe (it is almost already) and share it across all the map objects a more maintainable option?

**Comment by jfirebaugh** [comment]
It wouldn't be ideal for node. Node already has a built-in concept of a thread worker pool, which native extensions are expected to use for CPU-intensive tasks. The right thing for an extension to do is use that pool, not launch its own threads.

**Comment by jfirebaugh** [comment]
We now have an abstract interface that can facilitate this: [`Scheduler`](https://github.com/mapbox/mapbox-gl-native/blob/740c995c2b37bd896c87b2d8e22d644e09bc3e42/src/mbgl/actor/scheduler.hpp). We could, for example, write a subclass that implements `Scheduler::schedule` via `Nan::AsyncQueueWorker`. The worker `Execute` implementation would do:

```
if (auto locked = mailbox.lock()) {
    locked->receive();
}
```

(Actually this logic is already repeated [here](https://github.com/mapbox/mapbox-gl-native/blob/740c995c2b37bd896c87b2d8e22d644e09bc3e42/include/mbgl/util/run_loop.hpp#L86-L88) and [here](https://github.com/mapbox/mapbox-gl-native/blob/740c995c2b37bd896c87b2d8e22d644e09bc3e42/src/mbgl/actor/thread_pool.cpp#L25-L27) and we should extract it as `static void Mailbox::maybeReceive(std::weak_ptr<Mailbox>)`.)

The other thing we need to do is externalize the dependency, passing a `Scheduler&` into the `Map` constructor as we do `View&` and `FileSource&`, rather than creating it internally. This will need to be a coordinated change across all SDKs.
