### ISSUE TITLE
Text label rendering fuzzy when map is tilted

### ISSUE THREAD

**Issue by haoshengfucn** [mapbox/mapbox-gl-native#3987]
Hi, I am very interest in mapbox and it was rendered beautifully. 

There are two problems i found.

1.There may be a bug when you zoom in to the max level and tilt to max angle , some roads looks fuzzily,but other roads looks sharply. when you drag the map, sometimes it's ok.

The location is at the bottom of the screenshot.
![screenshot](https://cloud.githubusercontent.com/assets/1198851/13150182/b3060628-d632-11e5-827e-0f194a340fe1.jpg)

2.When i open the map in my Android, drag to china, it crashed. but if i zoom in and drag,it works.

**Comment by haoshengfucn** [comment]
hi,i upload the screenshot to github,but always failed.  please see
the attachment.

**Comment by friedbunny** [comment]
Still no screenshot. :(

**Comment by haoshengfucn** [comment]
do you have a gmail ?

**Comment by friedbunny** [comment]
You can use [our contact form](https://www.mapbox.com/contact/) to send us an image. Be sure to link to this issue.

**Comment by friedbunny** [comment]
Thanks, here's your screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/1198851/13150182/b3060628-d632-11e5-827e-0f194a340fe1.jpg)

**Comment by jfirebaugh** [comment]
#3057 is supposed to fix this.

**Comment by aldo-jlaurenstin** [comment]
@friedbunny Hi, This might not be the place to ask you this. But I was wondering if there's a tvOS version of the SDK available? Even if experimental.
Thanks
