### ISSUE TITLE
variable naming style

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#399]
We're currently using a mix of [camel-case](https://github.com/mapbox/mapbox-gl-native/blob/5f208c268b28d93027d9178ac4642a7b269db380/include/mbgl/map/map.hpp#L171-L175) and [underscore](https://github.com/mapbox/mapbox-gl-native/blob/5f208c268b28d93027d9178ac4642a7b269db380/include/mbgl/map/map.hpp#L193-L195) variable names. My vote is for camel-case simply to be consistent with JS.

**Comment by jfirebaugh** [comment]
We're getting to be in good shape here. Let's continue to make things camel-case when we encounter variables that aren't.

**Comment by tmpsantos** [comment]
I would like to suggest suffixing class attributes with a `_` as in `myAttribute_`.

**Comment by jfirebaugh** [comment]
@tmpsantos If we were starting from scratch, I'd agree. But none of the existing code uses that convention, and in fact much of it uses a `_` suffix on parameters to avoid shadowing a member (the opposite convention). I think it's too much churn to make a change here.
