### ISSUE TITLE
AnnotationIDs Map::getShapeAnnotationsInBounds(const LatLngBounds& bounds)

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3990]
##### getPointAnnotationsInBounds
In map.cpp we have `getPointAnnotationsInBounds`:

```cpp
AnnotationIDs Map::getPointAnnotationsInBounds(const LatLngBounds& bounds) {
    return data->getAnnotationManager()->getPointAnnotationsInBounds(bounds);
}
```

On Android, this is used to determine marker clicks, if true invoke `OnMarkerClickListener`.

##### getShapeAnnotationsInBounds
To be able to implement `OnPolygonClickListener` and `OnPolylineClickListener` from #3720, we would need an equivalent that works with shape annotations or is able to take in account both types of annotations.

**Comment by jfirebaugh** [comment]
Tracking this in #2082.
