### ISSUE TITLE
AnnotationManager::getPointAnnotationsInBounds

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#3991]
In annotation_manager.cpp:

```cpp
AnnotationIDs AnnotationManager::getPointAnnotationsInBounds(const LatLngBounds& bounds) const {
    AnnotationIDs result;

    pointTree.query(boost::geometry::index::intersects(bounds),
        boost::make_function_output_iterator([&](const auto& val){
            result.push_back(val->id);
        }));

    return result;
}
```
When determining if a point annotation is found in a certain bounds, the method above is not taking into account the width/height of the marker image (in case that the point annotation is a marker). This will result in behaviour as documented in https://github.com/mapbox/mapbox-gl-native/issues/3643.

**Comment by jfirebaugh** [comment]
This is by design. The expected behavior is that the SDK bindings should add padding to the bounds parameter, or simply pass the entire viewport bounds, and then do more precise hit testing on the results. See the iOS bindings for an example.

**Comment by 1ec5** [comment]
Let me know if you think any of the logic in `-[MGLMapView annotationTagsInBounds:]` (can't recall the exact name off the top of my head) should be pushed down into mbgl for your use. It didn't seem like there was any Android analogue to alignment rect insets. Also note that the OS X SDK does even more sophisticated, alpha-based hit testing on annotations.

**Comment by tobrun** [comment]
Thanks for the input @jfirebaugh and @1ec5. This clears things up.
