### ISSUE TITLE
Location mark (not drawn) disappears when view crosses international date line.

### ISSUE THREAD

**Issue by manimaul** [mapbox/mapbox-gl-native#3995]
Given the view crosses the international date line (180 degrees E)
Given the center of the screen is right/east of the dateline
When the user location is east of the dateline
Then the user location should be drawn (but is not drawn)

See below screenshots where the location is: 16.85 S , 179.89 W
![device-2016-02-17-162405](https://cloud.githubusercontent.com/assets/229469/13129740/cee630f6-d593-11e5-8bc2-c611c8b0a980.png)
![device-2016-02-17-162442](https://cloud.githubusercontent.com/assets/229469/13129743/d0f0280c-d593-11e5-982d-679016fbfd9d.png)

**Comment by tobrun** [comment]
@manimaul thank you for reporting this edge-case, this is great information to have.

**Comment by friedbunny** [comment]
> edge-case

There's no edge like the dateline edge. 🤔

**Comment by manimaul** [comment]
@tobrun yes, dealing with the dateline is always fun.  I'm wondering if you're willing to escalate this issue as it is a blocker for me.  I have a large audience in New Zealand who use my app (MX Mariner) on the water, near the dateline.  I'm currently using the previously deprecated Mapbox SDK and this is the remaining issue before making the switch to Mapbox GL.  Thank you,
Will

**Comment by mb12** [comment]
@manimaul    I would recommend looking at the following known issues for Android before switching over to new SDK. Your application will stop working on certain devices (where it previously worked including older Google Galaxy Nexus).  

https://github.com/mapbox/mapbox-gl-native/issues/2980
https://github.com/mapbox/mapbox-gl-native/issues/4037
https://github.com/mapbox/mapbox-gl-native/issues/3693
https://github.com/mapbox/mapbox-gl-native/issues/1702

**Comment by manimaul** [comment]
@mb12 thanks, I'll definitely keep an eye on those issues before making the leap.

**Comment by tobrun** [comment]
@manimaul I added this issue to the higher priority list of bugs to solve. Sorry for not being able to give you a concrete ETA. It is not the only issue on that list. For now I'm doing some small tests around this issue to identify the source and determine the amount of work needed to get a fix in.

**Comment by tobrun** [comment]
@manimaul could you give me some more information how you are setting this test up? 
All the mock GPS apps I have tested, don't work with this dateline issue. 
Example of this [here](https://www.dropbox.com/s/2lk12jt0wt5zu8j/device-2016-02-25-111712.mp4?dl=0), where you can see it's going the opposite direction.

**Comment by manimaul** [comment]
@tobrun I'm using the Genymotion Android emulator which makes it easy to set the device's location.  

other options:
1. Use the standard Android emulator and send a mock "geo" command via adb described here: http://developer.android.com/guide/topics/location/strategies.html
2. Use the "new" beta Android emulator which has a GUI similar to Genymotion for setting the mock location.  http://tools.android.com/tech-docs/emulator

**Comment by tobrun** [comment]
@manimaul 
thank you for adding that information. I was tackling this issue from the perspective of having a route/gps trace. Looking into manually setting the location reveals the following:

![screen shot 2016-03-01 at 11 02 17](https://cloud.githubusercontent.com/assets/2151639/13423763/24b4fdec-df9d-11e5-8858-e2fd35417c0f.png)


if you pan the map a bit to the right, the UserLocationView disappears:

![screen shot 2016-03-01 at 11 02 25](https://cloud.githubusercontent.com/assets/2151639/13423772/34489ac0-df9d-11e5-9f49-8642f96704cc.png)

The source of that issue will be the solution to what is mentioned above.

**Comment by tobrun** [comment]
I was able to pinpoint this to `toScreenLocation` method returning the wrong values when crossing the dateline. This `toScreenLocation` is used in the following method:

```java
    public PointF getMarkerScreenPoint() {
        if (mMyLocationTrackingMode == MyLocationTracking.TRACKING_NONE) {
            mMarkerScreenPoint = mProjection.toScreenLocation(mMarkerCoordinate);
        } else {
            // tracking the user
        }
        return mMarkerScreenPoint;
    }
```

This method is being called on every update call, to get the correct x,y coordinates for the UserLocationView. Currently not the correct values are returned.

For example:
before crossing the dateline:
> MarkerScreenPoint 455.80133:746.6456

after
> MarkerScreenPoint 393667.44:747.1837

**Comment by tobrun** [comment]
Been trying to locate this problem in C++.

It is going through `map.cpp`, `transform.cpp` and `transform_state.cpp`.

In `transform_state.cpp` it is using the following method:

```cpp
PrecisionPoint TransformState::latLngToPoint(const LatLng& latLng) const {
    return coordinateToPoint(latLngToCoordinate(latLng));
}
```

which on his turn calls `coordinateToPoint` and `latLngToCoordinate`:

```cpp
PrecisionPoint TransformState::coordinateToPoint(const TileCoordinate& coord) const {
    mat4 mat = coordinatePointMatrix(coord.zoom);
    matrix::vec4 p;
    matrix::vec4 c = {{ coord.column, coord.row, 0, 1 }};
    matrix::transformMat4(p, c, mat);
    return { p[0] / p[3], height - p[1] / p[3] };
}
```

```cpp
TileCoordinate TransformState::latLngToCoordinate(const LatLng& latLng) const {
    const double tileZoom = getZoom();
    const double k = zoomScale(tileZoom) / worldSize();
    return {
        lngX(latLng.longitude) * k,
        latY(latLng.latitude) * k,
        tileZoom
    };
}
```

**Comment by tobrun** [comment]
I made a follow up issue #4155, since this problem is found in `mbgl` instead of `Android SDK`.

**Comment by tobrun** [comment]
I'm closing this issue in favour of #4155
