### ISSUE TITLE
Polygon filled region not anti-aliasing well.

### ISSUE THREAD

**Issue by shantanu-vyas** [mapbox/mapbox-gl-native#3996]
When creating a new polygon with a stroke and a fill, the stroke of the border will get anti-aliased but the filled region will not. This leads to small gaps between the border and the filled region. 
`mv.addPolygon(new PolygonOptions().addAll(latlnglist).strokeColor(Color.BLUE).fillColor(Color.parseColor("navy")));`

![mapbox](https://cloud.githubusercontent.com/assets/1009536/13133763/cb3fac8c-d5cc-11e5-8deb-378981ffe027.png)

**Comment by friedbunny** [comment]
Thanks for the report!

/cc @kkaefer @ansis

**Comment by jfirebaugh** [comment]
This is a known deficiency of fill layers. For more control over fill and stroke rendering, you can add a separate line layer or line annotation with a thicker width.
