### ISSUE TITLE
User agent strings are too generic

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3997]
Mapbox GL and the various SDKs built atop it are sending overly generic user agent strings in style and tile requests:

* Mapbox iOS and OS X SDKs: [`MapboxGL`](https://github.com/mapbox/mapbox-gl-native/blob/a331e94b1b8d7fcdffe7ef757f4f4c56c9307e8e/platform/darwin/src/http_request_nsurl.mm#L64)
* Mapbox Android SDK: [`MapboxGL/1.0`](https://github.com/mapbox/mapbox-gl-native/blob/20be32f217b860bb0b5af3b32cea2d928b091d29/platform/android/src/http_request_android.cpp#L128), where 1.0 is hard-coded and remains constant across versions
* All other Mapbox GL: [`MapboxGL/1.0`](https://github.com/mapbox/mapbox-gl-native/blob/20be32f217b860bb0b5af3b32cea2d928b091d29/platform/default/http_request_curl.cpp#L390), where 1.0 is hard-coded and remains constant across versions

This stands in contrast to the legacy Mapbox iOS SDK, which [allowed applications to fully customize the user agent string](https://github.com/mapbox/mapbox-ios-sdk-legacy/blob/78ee633d76ed7f088c8747801f60af3d86eb52cc/MapView/Map/RMConfiguration.h#L63), and the legacy Mapbox Android SDK, which used [`Mapbox Android SDK/0.7.0`](https://github.com/mapbox/mapbox-android-sdk-legacy/blob/26d8857786856e5bd933ef6ad28b1d359b2a342a/MapboxAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java#L15), where 0.7.0 was the SDK version.

Telemetry events are currently sent over a different code path that specifies a more specific user agent string: `MyTelemetricApp/2.0/3737 MapboxEventsPlatform/1.1`, where MyTelemetryApp is the bundle identifier, 2.0 is the bundle version, 3737 is the build number, _Platform_ is either `iOS` or `Android`, and 1.1 gets incremented every time we change the event format.

The SDKs should be using more specific user agent strings that at least identify the platform and SDK version. Some other attributes (such as the application name and version and the hardware model) can easily be obtained and are customarily included in the user agent string; however, these attributes are already being sent as part of the turnstile event and telemetry.

/cc @mapbox/gl @mapbox/telemetry

**Comment by tobrun** [comment]
Linking #1993
