### ISSUE TITLE
Android Polygon Inside Polygon

### ISSUE THREAD

**Issue by bondbabu** [mapbox/mapbox-gl-native#4002]
I am able to draw a polygon using android sdk inside my android app.
But here the sdk allows user to drawn another polygon over or inside the already existing polygon.
Is there any process to restrict user to not draw another polygon inside or over existing polygon.

**Comment by tobrun** [comment]
@bondbabu thank you for reaching out and asking this question. The requested feature is something we are currently not supporting. It should be feasible to implement this yourself by validating a polygon before adding it using `fromScreenLocation` & `toScreenLocation` methods.

Reach out if you have any other questions!

**Comment by bondbabu** [comment]
Thanks for the response @tobrun 
As per my requirement i have to show multiple polygons on the map. as there are multiple i am not able to get the exact region of the polygon using  fromScreenLocation & toScreenLocation methods.
