### ISSUE TITLE
Support coveralls.io

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#4014]
Follow-up from https://github.com/mapbox/mapbox-gl-native/issues/3973 - I believe we can start generating coverage reports for Mapbox GL Native in https://coveralls.io :chart_with_upwards_trend: 

Initial plan is to provide coverage data from the Linux Debug build we have at Travis CI. Then we can proceed with Android, iOS & OS X-specific coverage reports.

/cc @mapbox/gl @mapbox/mobile

**Comment by tmcw** [comment]
They've also got a competitor, [codecov.io](https://codecov.io/), which has been better in my experience - albeit super similar.

**Comment by brunoabinader** [comment]
> They've also got a competitor, codecov.io

That looks good :+1: Both provides free accounts for open source projects, so I guess we could try both and check out which one provides a better report for us.

**Comment by willwhite** [comment]
FYI we just [removed coveralls](https://github.com/mapbox/mapbox-core/pull/413) from mapbox-core because it's down quite often and was breaking builds.

**Comment by brunoabinader** [comment]
Examples for both [coveralls.io](https://coveralls.io) and [codecov](https://codecov.io) can be seen below:

https://coveralls.io/github/mapbox/mapbox-gl-native
https://codecov.io/github/mapbox/mapbox-gl-native?ref=86845b6e19cbdd45640a5abaff147c51f9cc9973

From what I've experienced:

# Coveralls.io:
Pros:
- Easy follow-up of coverage statistics based on previous builds.
- Backed by important tech players.
- Heavily used by other Mapbox repositories: https://coveralls.io/github/mapbox

Cons:
- Had to use a non-default uploader - https://github.com/okkez/coveralls-lcov - that requires a few extra dependencies in Travis CI.
- Had some maintenance breaks during my investigation - last month's uptime around 97%: http://status.coveralls.io/#month

# Codecov.io
Pros:
- Easy setup: Just download their shell shell script via curl and run - it automagically finds the coverage data.

Cons:
- Not used by other Mapbox repositories.

**Comment by brunoabinader** [comment]
I have added [coveralls.io](https://coveralls.io/github/mapbox/mapbox-gl-native) support. This involved adding a new debug build on Travis CI. I believe we could start with that in the hope that their uptime tends to 100%. If not, we can easily switch to [codecov.io](https://codecov.io) anytime.

**Comment by springmeyer** [comment]
@brunoabinader - great work on this.

>  I believe we could start with that in the hope that their uptime tends to 100%. If not, we can easily switch to codecov.io anytime.

Sounds good. I'm a big reason we have so many repos in coveralls and I was not familiar with `codecov.io` before now so good to know about it. Let us know if you see other CONS otherwise let's keep it as an option to try out.
