### ISSUE TITLE
Library resource prefix breaks current attrs.xml

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4021]
For #3119 it seemed a great improvement to add `resourcePrefix` to build.gradle.
This enforces that resources should start with a certain prefix.
For this project I have chosen for the `mapbox_` prefix.

This resulted in following `strings.xml`:

```xml
 <?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="mapbox_compassContentDescription">Map compass. Click to reset the map rotation to North.</string>
    <string name="mapbox_attributionsIconContentDescription">Attribution icon. Click to show attribution dialog.</string>
    <string name="mapbox_attributionsDialogTitle">Mapbox Android SDK</string>
    <string name="mapbox_attributionTelemetryTitle">Make Mapbox Maps Better</string>
    <string name="mapbox_attributionTelemetryMessage">You are helping to make OpenStreetMap and Mapbox maps better by contributing anonymous usage data.</string>
    <string name="mapbox_mapboxIconContentDescription">The Mapbox logo.</string>
    <string name="mapbox_infoWindowTitle">Title</string>
    <string name="mapbox_infoWindowDescription">Description</string>
    <string name="mapbox_infoWindowAddress">Address</string>

    <!-- these are public -->
    <string name="mapbox_style_mapbox_streets">mapbox://styles/mapbox/streets-v8</string>
    <string name="mapbox_style_emerald">mapbox://styles/mapbox/emerald-v8</string>
    <string name="mapbox_style_light">mapbox://styles/mapbox/light-v8</string>
    <string name="mapbox_style_dark">mapbox://styles/mapbox/dark-v8</string>
    <string name="mapbox_style_satellite">mapbox://styles/mapbox/satellite-v8</string>
    <string name="mapbox_style_satellite_streets">mapbox://styles/mapbox/satellite-hybrid-v8</string>
</resources>
```

This is a great improvement in comparison with before, the resource prefix requires us to follow certain guidelines. Now with implementing #4018, I'm noticing this is required also for other types of resources: 
eg `attrs.xml`:

![screen shot 2016-02-18 at 16 36 34](https://cloud.githubusercontent.com/assets/2151639/13148475/d7782aba-d65d-11e5-8b8e-d76e585b784b.png)

At first this doesn't seem a problem, but when you look at the end result in java code:

```java
typedArray.getBoolean(R.styleable.mapbox_MapView_mapbox_zoom_enabled, true));
```

instead of

```java
typedArray.getBoolean(R.styleable.MapView_scroll_enabled, true)
```

I'm personally not a big fan of this, but this API is only for internal use. 
End users will only see the following API:

![screen shot 2016-02-18 at 16 40 50](https://cloud.githubusercontent.com/assets/2151639/13148633/72d56176-d65e-11e5-9b22-d8018c935171.png)

What are your opinion on this? @bleege  @zugaldia

**Comment by bleege** [comment]
@tobrun Let's hold on this for time being as there are more immediate needs that require our bandwidth, namely better testing support.

**Comment by tobrun** [comment]
@bleege agreed! I'm quickly going to disable this for now in #4040. Not cool having errors/warnings in the IDE. This is still something that we should discuss before releasing `4.0.0` since as you noticed can be a breaking change.

**Comment by zugaldia** [comment]
> I'm personally not a big fan of this, but this API is only for internal use. 

If it's only for internal use, not a major problem. However, let's avoid unnecessary `mapbox_` prefixes like in `mapbox_style_mapbox_streets` and let's stick to one kind of capitalization (`mapbox_compassContentDescription ` vs `mapbox_style_mapbox_streets`).

> This is still something that we should discuss before releasing 4.0.0 since as you noticed can be a breaking change.

If the only public facing change is for `mapbox_access_token`, can we just implement manually that one, and leave the larger lift for after 4.0.0?

**Comment by tobrun** [comment]
@zugaldia 
both the styles and the attributes you mentioned [above](https://github.com/mapbox/mapbox-gl-native/issues/4021#issuecomment-187277018) are public.
You can see all our public resources in [public.xml](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/res-public/values/public.xml)

For now I'm going to drop the `mapbox_` prefix for all resources except for `mapbox_access_token`.

**Comment by zugaldia** [comment]
@tobrun :+1:
