### ISSUE TITLE
Annotations not rendering correctly until interacting with map

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-gl-native#4024]
On iOS SDK 3.1.1, sometimes annotations don't update immediately/fully and require interacting with the map to render them correctly.  The polylines in the image below show the issue.  I added them the map, but they both cut off at the same Y location.  After a slight pan interaction, they show in full.

<img width="363" alt="beforepan" src="https://cloud.githubusercontent.com/assets/1591735/13157355/6c69b020-d655-11e5-8524-66e0059028ec.png">
<img width="361" alt="afterpan" src="https://cloud.githubusercontent.com/assets/1591735/13157357/6f2a9aea-d655-11e5-8e2a-2583425af64b.png">

I tried calling `setNeedsDisplay` on the map after updating annotations, but this didn't seem to help.  I've seen the same thing with pin images.

**Comment by morgz** [comment]
I am also seeing this issue. Did you find a fix?

**Comment by johnnewman** [comment]
I haven't found a workaround other than panning the map.

**Comment by friedbunny** [comment]
@johnnewman Are you adding+removing these polylines rapidly, or do you see this clipping behavior on the initial add?

**Comment by johnnewman** [comment]
@friedbunny Sorry for the delay.  It wasn't directly after the first add.  I added the polylines/pins and it rendered OK, then edited the route which removed/added the polylines to redraw them.  After repeating that process a few times I saw the issue again in 3.1.2.  There were 2 polylines and 3 pins in my repro.  The screenshots below are from a 6+ running iOS 8.4.

<img width="364" alt="screen shot 2016-03-17 at 1 52 08 pm" src="https://cloud.githubusercontent.com/assets/1591735/13855581/86bcfe48-ec47-11e5-86ca-5f792be0ef4c.png">
<img width="363" alt="screen shot 2016-03-17 at 1 52 18 pm" src="https://cloud.githubusercontent.com/assets/1591735/13855584/8a5caa12-ec47-11e5-818d-b23483ceb177.png">

The bottom image is after initiating a pan gesture.

**Comment by jlansing** [comment]
We are running into this issue as well. It seems to only happen on device as we don't see it on the simulator. Couple of scenarios we use it for:

1. Changing the visuals of a point annotation when it is selected. We will remove the annotation, and re add it so it refreshed the MGLAnnotationImage to the proper visual. In this event, occasionally the new annotation doesn't display making it look as if the pin disappeared. Once you tap the map again at all it pops right in.

2. Similarly when toggling between multiple polylines, we change the visual style to indicate one of multiple routes that could be taken. In this case the routes sometimes won't re-draw, or will partially draw (per @johnnewman) until the map is touched/panned.

Some workarounds we've tried that don't work:
1. Calling setNeedsDisplay on MGLMapView
2. Calling the private setNeedsGLDisplay on MGLMapView
3. Introducing an "atomic" add/remove annotations call that only makes a single call to update(Update::Annotations); on the underlying native map.
4. Using dispatch_after on the re-add of the annotation.

It definitely feels like a racing condition of some kind - like all of the annotation data isn't quite in the right state as the last frame gets rendered, and then the entire system is stuck in a "clean" state that no longer needs updates. Not really sure what more information would be helpful to you, but this is pretty critical for us and would love to see some movement.

Let us know how we can help!

**Comment by jfirebaugh** [comment]
Is this reproducible for anyone on the latest release (v3.3.4)?

**Comment by johnnewman** [comment]
@jfirebaugh Sorry for the delay.  I haven't been seeing this issue in 3.3.4!

**Comment by jfirebaugh** [comment]
Glad to hear it, thank you!
