### ISSUE TITLE
Avoid recomputing tile cache size on every redraw

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#4026]
The tile cache size is [recomputed and reset on every redraw](https://github.com/mapbox/mapbox-gl-native/blob/13e2acbc754893efb945fe02d20824698415dcdb/platform/ios/src/MGLMapView.mm#L764-L770), which seems wasteful considering that the minimum and maximum zoom levels, processor count, processor memory, and view size rarely change. (We don’t support hot-swapping RAM on your iPhone!) We should recompute the tile size only when `-setMinimumZoomLevel:`, `-setMaximumZoomLevel:`, `-setFrame:`, and `-setBounds:` are called.

/cc @ansis @tmpsantos

**Comment by tmpsantos** [comment]
:+1:
