### ISSUE TITLE
Roads not rendering on Samsung device

### ISSUE THREAD

**Issue by preetb123** [mapbox/mapbox-gl-native#4037]
Road network is not rendering on Samsung device

![device-2016-02-19-162812](https://cloud.githubusercontent.com/assets/4496555/13173877/1805cede-d726-11e5-88ad-e108d2020126.png)
![device-2016-02-19-162829](https://cloud.githubusercontent.com/assets/4496555/13173880/18091ed6-d726-11e5-88b4-69fa86c09e97.png)
![device-2016-02-19-162917](https://cloud.githubusercontent.com/assets/4496555/13173878/1807fbe6-d726-11e5-8448-114ae1b6e8bb.png)

**Comment by tobrun** [comment]
@preetb123 
thank you for reaching out and reporting this problem.
Could you add some more information how to reproduce?
Where you able to reproduce this on other devices?

**Comment by preetb123** [comment]
They render properly on Nexus 5, MotoG and other devices. This was the only device that caused the issue.

**Comment by tobrun** [comment]
Related graphics card from this issue is `Broadcom VideoCore IV HW`

**Comment by jfirebaugh** [comment]
@preetb123 Are you still experiencing this issue with version 5.0.2 of the Mapbox Android SDK?

**Comment by preetb123** [comment]
Don't have those samsung device now. It was issue with older OpenGL versions in those devices.

**Comment by jfirebaugh** [comment]
#6454
