### ISSUE TITLE
PolygonOptions with empty LatLng list causes SIGSEGV

### ISSUE THREAD

**Issue by shantanu-vyas** [mapbox/mapbox-gl-native#4038]
While creating an polygon if the list of points is empty it causes 

> A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 32115 (Map)

Doesn't provide stacktrace as well.

Reproduce by passing an empty ArrayList of LatLng to the addAll parameter of polygon options.

**Comment by tobrun** [comment]
@shantanu-vyas 
thank you for reaching and reporting this crash.
Going to pick this up now.

**Comment by tobrun** [comment]
I'm going to ignore polylines and polylines with empty `LatLng`s. 
Business logic wise this makes most sense. (An shape without a point is not a shape).

**Comment by tobrun** [comment]
I updated the unit tests to reflect changes + catch problem from this issue.
