### ISSUE TITLE
Map goes blank when annotations are replaced

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#4045]
We are noticing that when we have to redraw the polyline annotations (due to the user being rerouted), the map momentarily goes blank before the new annotations are displayed. We are not removing the map from the view hierarchy, just removing the annotations and replacing them. We are using version 3.1.1.

Here is a video showing the issue:
https://dl.dropboxusercontent.com/u/361341/mapbox%20map%20redraw.mov

**Comment by friedbunny** [comment]
Here's a super-lossy GIF version!

![ezgif com-crop](https://cloud.githubusercontent.com/assets/1198851/13192249/ef17ae90-d737-11e5-823a-0d7ca5f9c990.gif)

**Comment by friedbunny** [comment]
Going to close this as stale — please feel free to report back with new information and we’ll reopen.
