### ISSUE TITLE
How do you reset the map to North when leaving FollowWithHeading

### ISSUE THREAD

**Issue by johnnewman** [mapbox/mapbox-gl-native#4053]
On Mapbox iOS 3.1.1, where is the best location to reset the map to North after leaving `MGLUserTrackingModeFollowWithHeading` due to a pan gesture?

When I call `[mapView resetNorth]` in the delegate method `mapView:didChangeUserTrackingMode:` the map's ongoing pan gesture seems to ignore the call to reset direction.

Using a different approach to reset North when leaving FollowWithHeading below:

``` Objective-C
- (void)mapView:(MGLMapView *)mapView regionDidChangeAnimated:(BOOL)animated;
{
    if (mapView.userTrackingMode != MGLUserTrackingModeFollowWithHeading && mapView.direction != 0.0)
    {
        [mapView resetNorth];
    }
}
```

results in the app crashing because calling `resetNorth` or `setDirection:0 animated:NO` doesn't immediately change `direction` to 0 and instead will loop over and over, locking the main thread until the app crashes.

Is there an easy way to do this?

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
