### ISSUE TITLE
Quick zooming zooms in on (0,0) instead of center of viewport [Android]

### ISSUE THREAD

**Issue by brewin** [mapbox/mapbox-gl-native#4057]
A recent change (probably the introduction of MapboxMap) is causing the quick-zooming gesture to zoom in on (0,0) off the coast of Africa instead of on the center of the viewport.

**Comment by tobrun** [comment]
@brewin 
thank you for reaching out and reporting your problem.
Will patch this up.

**Comment by tobrun** [comment]
The source of the bug is the introduction of map padding

**Comment by tobrun** [comment]
I verified that `scale` was the only gesture impacted by this bug
