### ISSUE TITLE
MapboxEventManager is using ApiAccess class

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4077]
I noticed that `ApiAccess` class is being used by the `MapboxEventManager`.

This means we are forcing our end users to use one of the following:

 - Configuration of their access token in AndroidManifest.xml
 
  ```
   <meta-data
       android:name="com.mapbox.AccessToken"
       android:value="" />
   ```

-  Configuration of their access token as string resource with key:
    
    ```
      R.string.mapbox_access_token
    ```

@bleege 
you always indicated to me that we should not enforce this.
If this requirement has changed we should update the rest of classes to reflect this.

**Comment by tobrun** [comment]
Leaving a note here, that the previous requirement of having the `ApiAccess` class in the SDK itself could be removed with introduction of `MapboxMapSettings` in #4076 . This will cover 99% of our use-cases. (need to double check during implementation of that feature).

**Comment by bleege** [comment]
Yep this needs to be removed.  Good catch.

**Comment by bleege** [comment]
To solve this issue, I created `configureAndStartMapboxEventManager()` startup method that needs to be called first.  It's probably not ideal in the long term, but it comes with the big benefit of removing the need for every call to `getMapboxEventsManager()` to have pass in the `Context` for every time its used.  This is extra helpful in classes that don't have access to `Context` and would have to be reconfigured to provide it.

The ability to configure the MapboxEventsManager to still use Staging remains, by [setting them in AppManifest](https://github.com/mapbox/mapbox-gl-native/blob/e5e1fa81393bc53daa79ca60c001c7462095215c/platform/android/MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml#L101-L107).
