### ISSUE TITLE
Message of exceptions redirecting users to .md files

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4078]
This type of message is found in `InvalidAccessTokenException`:
```
/**
 * A {@code InvalidAccessTokenException} is thrown by {@link MapView} when there is either no access
 * token set before {@link MapView#onCreate(Bundle)} or an invalid access token is set in {@link MapView#setAccessToken(String)}
 *
 * @see MapView#onCreate(Bundle)
 * @see MapView#setAccessToken(String)
 */
public class InvalidAccessTokenException extends RuntimeException {

    public InvalidAccessTokenException() {
        super("Using MapView requires setting a valid access token. See the INSTALL.md");
    }

}
```

And in `TelemetryServiceNotConfiguredException`:

```
/**
 * A {@code TelemetryServiceNotConfiguredException} is thrown by {@link MapView} when it checks and finds that
 * TelemetryService has not been configured in the app's AndroidManifest.xml {@link MapView#onCreate(Bundle)}
 *
 * @see MapView#onCreate(Bundle)
 */
public class TelemetryServiceNotConfiguredException extends RuntimeException {

    public TelemetryServiceNotConfiguredException() {
        super("Using Mapbox Android SDK requires configuring TelemetryService. See the INSTALL.md");
    }

}
```

This is giving our users a bad user experience. Take for example someone that installs our SDK through `mapbox.com`. They will not know where to locate this `INSTALL.md` file. Unexperienced users might even not know what an `.md` file is. The general rule I apply on writing good exception message is that a user need to know directly **what to fix** and **where to fix it**.

@danswick: can you reflect on this with things you are seeing on support side?

cc @bleege @zugaldia

**Comment by cammace** [comment]
Removes referring to install.md when access token and telemetry exception occurs. Instead it now describes the steps to take in order to resolve the problem.
