### ISSUE TITLE
marker.showInfoWindow() cause crash about Android SDK

### ISSUE THREAD

**Issue by Trinea** [mapbox/mapbox-gl-native#4096]
```
marker.hideInfoWindow();
marker.showInfoWindow();
```

crash log is below:
![](https://github.com/Trinea/trinea-download/blob/master/temp/mapbox-bug1.png?raw=true)

**Comment by tobrun** [comment]
@Trinea 
As mentioned [here](https://github.com/mapbox/mapbox-gl-native/issues/4074#issuecomment-187685604). You should not be using those methods directly. Those are for internal use only.

**Comment by Trinea** [comment]
ok, I'll have a try
