### ISSUE TITLE
Inject MapboxMap with NativeMapView

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4100]
To limit the overhead associated with a method call on Android. We should inject `MapboxMap` with a `NativeMapView` dependency. This will result in the removal of many, package hidden, facade methods we are currently exposing in `MapView`. 

Since this hasn't have an impact on public API. Going to wait with this until `4.0.0` is released.

**Comment by mikemorris** [comment]
Curious to hear more about this implementation - I implemented something similar a while ago (and [plan to revisit soon](https://github.com/mapbox/mapbox-gl-native/issues/3837) for performance reasons) with [exposing `NodeView` in the bindings and adding a `mbgl::Map::setView` method](https://github.com/mapbox/mapbox-gl-native/pull/1964).

**Comment by tobrun** [comment]
Happened in https://github.com/mapbox/mapbox-gl-native/pull/7189
