### ISSUE TITLE
Issue with SpriteFactory /IconFactory

### ISSUE THREAD

**Issue by MiguelFale** [mapbox/mapbox-gl-native#4105]
Hello.

In the mapbox android sdk, there used to be a class called SpriteFactory that allowed icons to be assigned to map markers. It was used like this: new SpriteFactory(mapview)

However, in the newest build, this class no longer exists. There's IconFactory, but I can't seem to use it, since it has private access.

Are there any alternatives?

Thanks in advance!

**Comment by tobrun** [comment]
An IconFactory example:
```java
IconFactory mIconFactory = IconFactory.getInstance(this);
Drawable mIconDrawable = ContextCompat.getDrawable(this, R.drawable.ic_awesome);
Icon icon = mIconFactory.fromDrawable(mIconDrawable);

 ```

**Comment by MiguelFale** [comment]
Hello.

It was helpful! Thank you!
