### ISSUE TITLE
Support an OfflineRegionDefinition defined by an arbitrary shape

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#4106]
At this moment we only support an `OfflineTilePyramidRegionDefinition` defined by a bounding box. We should let developers use arbitrary shapes to match, for example, the shape of a state, province, etc.

/cc: @jfirebaugh @1ec5

**Comment by jfirebaugh** [comment]
The pieces that we would need to support this are:

* A set of C++ types representing geographic features. Probably strongly GeoJSON influenced so we could reuse these types for `featuresAt` results and `geoJSONLayer.setData()`. Could potentially be extracted from geojsonvt-cpp. (cc @springmeyer)
* For each platform, bindings to the above.
* An implementation of `tileCover` for the above.

**Comment by twbell** [comment]
Polygons are P1; let's also consider polyline-as-input in this ticket as a P2.  The primary use case for the latter is pre-caching tiles along a route.

**Comment by 1ec5** [comment]
#5707 and #8012 take slightly different approaches to enabling the developer to define an arbitrary shape for offline download.

**Comment by 1ec5** [comment]
#11447 adds mbgl and Android support for offline regions that cover non-pyramidal geometries.

**Comment by 1ec5** [comment]
Fixed in #11447. Thanks @ivovandongen!
