### ISSUE TITLE
Upgrade support libraries

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4112]
New versions of support library have been released.
https://twitter.com/yigitboyar/status/702634654742872064

**Comment by bleege** [comment]
Let's hold off on this until after `4.0.0` drops.

/cc @zugaldia

**Comment by tobrun** [comment]
Since schedule has changed will pick this up now.

**Comment by tobrun** [comment]
I you would like to know what is included in these libs:
https://www.youtube.com/watch?v=7E2lNBM38IE

**Comment by tobrun** [comment]
We will need to update our ImageView source tags to leverage the power of Vector Drawables Compat:
<img width="436" alt="screen shot 2016-03-06 at 17 08 47" src="https://cloud.githubusercontent.com/assets/2151639/13557427/3090381e-e3be-11e5-933a-0642362e65c1.png">

**Comment by tobrun** [comment]
Now noticing the requirements mentioned on the [official blogpost](http://android-developers.blogspot.com/2016/02/android-support-library-232.html), it would make more sense holding this off until gradle plugin 2.0.0 is out of beta.

**Comment by bleege** [comment]
I'm picking this back up as the SDK now uses Gradle Plugin 2.0.0 and Google has released [Android Support Library v 23.3.0](https://plus.google.com/+AndroidDevelopers/posts/iTDmFiGrVne).
