### ISSUE TITLE
Cannot submit app with static lib to App Store

### ISSUE THREAD

**Issue by millenbop** [mapbox/mapbox-gl-native#4118]
When trying to upload to the App Store, I get the following message:

`Couldn't find platform family in Info.plist CFBundleSupportedPlatforms or Mach-O LC_VERSION_MIN for Mapbox.framework.`

I'm using the static library (version 3.1.0) since we need iOS 7 support.

**Comment by millenbop** [comment]
3.0.1 works fine, integrated using cocoapods.

**Comment by 1ec5** [comment]
Can you try the latest release, 3.1.2? We fixed some issues related to archiving the static framework in that release.

**Comment by millenbop** [comment]
I can't use that version, see #4119. Already uploaded the build with 3.0.1 to the App Store. But I guess I can try to upload a new build and reject it.

**Comment by ultranano** [comment]
i'm trying now with version ios-v3.2.0-pre.1
Same error :-(

See screenshot attached
<img width="644" alt="screen shot 2016-03-04 at 15 53 14" src="https://cloud.githubusercontent.com/assets/4621104/13530377/620ec6f6-e221-11e5-9356-0e9b1261e774.png">

**Comment by ultranano** [comment]
works with 3.0.1 but all the updates (memory leak, annotation etc) are lost... we need asap an update to solve this issue

Thanks for your collaboration!

**Comment by ultranano** [comment]
Hi @1ec5 any news about that?

**Comment by ultranano** [comment]
@1ec5 we can't use 3.0.1 due to important memory leak on this version but we still need static library to support our user on iOS7. If we don't have a good solution we must switch to Apple maps in the meantime :-(

**Comment by 1ec5** [comment]
@ultranano, as an immediate workaround, can you add the following entry to the Info.plist inside Mapbox.framework?

```xml
<array>
	<string>iPhoneOS</string>
</array>
```

**Comment by ultranano** [comment]
Hi @1ec5! I can't fing Info.plist under Mapbox.framework... where is?

**Comment by friedbunny** [comment]
@ultranano Open Mapbox.framework in Finder.

**Comment by ultranano** [comment]
thanks @friedbunny!

**Comment by 1ec5** [comment]
Another workaround is to replace the static framework with the static library we build for Fabric users. The current version of the static library is [3.1.3](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.1.3-fabric.1). Unlike the static framework, the static library should go in “Linked Frameworks and Libraries”, _not_ “Embedded Binaries”.

**Comment by boundsj** [comment]
This should be fixed in https://github.com/mapbox/mapbox-gl-native/pull/4455
