### ISSUE TITLE
Framework not found Mapbox for architecture i386 / linker command failed with exit code 1

### ISSUE THREAD

**Issue by edward-at-intelex** [mapbox/mapbox-gl-native#4125]
Hi everyone -

I am attempting to test run the example provided with the mapbox-gl-native repo for iOS. While building the example in xCode (7.2, latest).

I am getting a warning  

**'Framework not found Mapbox for architecture i386' **

followed by an error

**linker command failed with exit code 1. use -v to see invocation. **

I followed the steps for described here in the repo, also restarted xCode, and also checked deadcode stripping feature (which I read on the web could be related to the architecture issue - setting it to _no_), and even just changed the version number of the project just to update it .

any thoughts or comments appreciated.

**Comment by 1ec5** [comment]
Hi @edward-at-intelex, `make iproj` generates a project that’s stuck on the “My Mac” build destination by default. If you change that to a simulator or connected device using the toolbar button next to the scheme picker, the error should go away. Please let us know if the error persists.

**Comment by 1ec5** [comment]
Clarified these instructions in fe7b52e79222f45119b8195841d08e535478c6ef.
