### ISSUE TITLE
Make setZoom and setMinZoom package private

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4126]
With a [rebase](https://github.com/mapbox/mapbox-gl-native/commit/01e55f183e4468d040e7b144536ca592c9b64cb5#diff-886ea28eab2480af0b2b70f0b5c78898L620) the setZoom/setMinZoom method were reverted back to being public.
These are no longer part of our public API for this reason should remain package private.

cc @zugaldia

**Comment by zugaldia** [comment]
@tobrun I'm the one to blame for this, thanks for fixing it. This change was necessary for an older version of the offline activity in the testapp, that doesn't apply anymore now that [the new API is available](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/OfflineActivity.java#L258-L259).

**Comment by tobrun** [comment]
FWIW I would have chosen the same snippet from that rebase. Selecting a
full javadoc version versus non documented code is 99.99% the correct
choice :) this happens

**Comment by bleege** [comment]
:+1:
