### ISSUE TITLE
Getting started: OS X and C++?

### ISSUE THREAD

**Issue by mattfelsen** [mapbox/mapbox-gl-native#4133]
Hi all. I've been taking a look at repo, docs, examples, etc. and am hoping for some pointers with getting started on OS X with C++, not ObjC/Swift.

The readme mentions a GLFW demo for OS X but I can only seem to find that for Linux. PR https://github.com/mapbox/mapbox-gl-native/issues/3294 suggests that it existed at one point, but got converted to a Cocoa app, so maybe the readme is just out of date? And this issue https://github.com/mapbox/mapbox-gl-native/issues/3294 suggests that `make linux` on OS X will actually build the GLFW app?

Just want to make sure I'm on the right track before running into walls :blush: Also if there are any guides that I'm missing, please do share. Thanks!

**Comment by 1ec5** [comment]
Yep, `make linux` (of all things) should build and run on OS X. I don't think we have anything more in terms of documentation on that frontend, but let us know if you do run into any walls, and we'll update the documentation accordingly.
