### ISSUE TITLE
Managing markers on the interface

### ISSUE THREAD

**Issue by MiguelFale** [mapbox/mapbox-gl-native#4140]
Hello!

I've been using mapbox android sdk to manage a series of markers. So far, the basic methods I'm using are mapview.removeannotation(m) and mapview.addmarker(new MapOptions...).
Is there an easier way to do this? For instance, methods that hide/show markers, or that retrieve the state of those markers (i.e. isShown)?

Thanks!

**Comment by tobrun** [comment]
@MiguelFale 

What version of the SDK are you using?

The `3.2.0` version doesn't have any support for dynamically changing the marker.
The `4.0.0` release is trying to improve this by allowing to update the following items dynamically:
 - Icon
 - Position

Hiding and showing can currently only be done through adding and removing a marker.

*To finalize:*
There is a feature request requesting to allow all other methods to be dynamically changed https://github.com/mapbox/mapbox-gl-native/issues/4150.
And I just created this #4156 to request the feature of `visibility`.
