### ISSUE TITLE
Remove Partial Wake Lock From Telemetry

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#4142]
We've decided to remove the use of the app session based Partial Wake Lock in Telemetry.  While Internal testing has shown that it is comparable to Google Play Services in terms of battery usage and performance, removing it will further minimize configuration for developers.

/cc @mapbox/telemetry

**Comment by mikemorris** [comment]
:+1:

**Comment by bleege** [comment]
Rebased and Merged!
