### ISSUE TITLE
Offline Observer.onStatusChanged stops notifications before requiredResourceCount is reached

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#4147]
This is a typical output when trying to download a region using the Android bindings:

```
D  1285/1322 resources; 73386975 bytes downloaded.
D  1286/1322 resources; 73411136 bytes downloaded.
D  1287/1322 resources; 73443462 bytes downloaded.
D  1288/1322 resources; 73448515 bytes downloaded.
D  1289/1322 resources; 73466983 bytes downloaded.
D  1290/1322 resources; 73487939 bytes downloaded.
D  1291/1322 resources; 73528712 bytes downloaded.
D  1292/1322 resources; 73542565 bytes downloaded.
D  1293/1322 resources; 73564559 bytes downloaded.
D  1294/1322 resources; 73590820 bytes downloaded.
D  1295/1322 resources; 73617637 bytes downloaded.
```

The logs stop there, in other words, we never see a `1296/1322` line or further. Interestingly though, if we browse the resulting sqlite database, we seem to have all the resources downloaded (1284 + 38 = 1322):

![image](https://cloud.githubusercontent.com/assets/6964/13407519/d1c78c68-def6-11e5-8bc5-a36fdb47c87c.png)

Extra information:
* Different regions will show different outputs. For example, a larger zoom could end at something like this: `D/OfflineActivity: 2472/2523 resources; 80827784 bytes downloaded.`
* The `bin/offline.cpp` tool shows the expected output (`1322/1322 resources`)
* If we switch the `assetRoot` to another Android folder (e.g. `Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DCIM).getAbsolutePath()`) the output is still the same.
* There're no apparent missing tiles when browsing in airplane mode
* I've verified that the JNI `createOfflineRegion` method is seeing the right numbers.

So far it seems there's no loss of data, but at some point we're misreporting the progress.

/cc: @jfirebaugh @1ec5

**Comment by bleege** [comment]
Tagging myself here for updates on this.

**Comment by bleege** [comment]
I just tested this in the latest SNAPSHOT build and it works like a champ!  Great job @jfirebaugh!
