### ISSUE TITLE
Centered the marker on the map when dragging map about Android SDK

### ISSUE THREAD

**Issue by Trinea** [mapbox/mapbox-gl-native#4149]
Centered the marker on the map when dragging map，Like below, the pin is a marker, It is always in the middle of the map no matter how I dropping the map.

![](https://github.com/Trinea/trinea-download/blob/master/temp/center-marker.gif?raw=true)

**Comment by Trinea** [comment]
@jjhurlock

**Comment by tobrun** [comment]
I will be adding an example demonstrating this kind of functionality in our test app.
This will not require any changes to the SDK itself.

**Comment by tobrun** [comment]
@Trinea 

I have created an example on our `GeocoderActivity`


![ezgif-2129914349](https://cloud.githubusercontent.com/assets/2151639/13487533/073b7ea6-e11b-11e5-8699-279b53c66857.gif)


Note that we are now only requesting the centre of the map when we click, from your gif above I see you want a constant stream of updates when the map is panned. For this you will need to use the `OnCameraChangeListener` introduced with `4.0.0`.

**Comment by Trinea** [comment]
Thank you

**Comment by bleege** [comment]
Very cool!  Great job @tobrun!  :rocket:

**Comment by Trinea** [comment]
@tobrun  I cannot find GeocoderActivity in mapbox-android-demo

**Comment by bleege** [comment]
> I cannot find GeocoderActivity in mapbox-android-demo

It's not located in that project.  It's instead located in the primary project's repository, and specifically the [TestApp](https://github.com/mapbox/mapbox-gl-native/tree/d10d3eef432ff5a3b161e87e7653bb902b86a32d/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp).  The TestApp contains many examples of how to use different features of Mapbox Android SDK.  Please feel free to explore and build it when you're looking for ideas / solutions.  :rocket: 

As an aside [`Mapbox Android Demo`](https://github.com/mapbox/mapbox-android-demo) is simply a demonstration app that uses the latest Mapbox Android SDK that we [publish on Google Play](https://play.google.com/store/apps/details?id=com.mapbox.mapboxandroiddemo&hl=en).

**Comment by Trinea** [comment]
Thank you, we will have a try.

**Comment by Trinea** [comment]
@tobrun  I have see that you added the centered marker like this.
```
        final ImageView dropPinView = new ImageView(this);
        dropPinView.setImageResource(R.drawable.ic_droppin_24dp);
        FrameLayout.LayoutParams params = new FrameLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT, Gravity.CENTER);
        dropPinView.setLayoutParams(params);
        mapView.addView(dropPinView);
```
But this is not what we want, we want a marker that be centered, not a view, because we need its infowindow to be showthen.

**Comment by tobrun** [comment]
@Trinea  
This is not something we are going to support on gl level, integrating an InfoWindow on that marker is fairly easily accomplished since the location of the InfoWindow should not be kept in sync with the InfoWindow. FWIW The InfoWindow itself is also an Android SDK View.

**Comment by Trinea** [comment]
@tobrun Do you means you don't support this feature, need ourself to accomplish by view?

**Comment by tobrun** [comment]
Yes this is very straightforward to do. Reach out if you have trouble implementing this.

**Comment by Trinea** [comment]
ok
