### ISSUE TITLE
Modify info of Marker after added About Android SDK

### ISSUE THREAD

**Issue by Trinea** [mapbox/mapbox-gl-native#4150]
We can add a marker like:
```
    Marker marker = mv.addMarker(new MarkerOptions().title("Edinburgh").snippet("Scotland").position(new LatLng(55.94629, -3.20777)));
```
But we cannot change the marker info after added, we need
```
    marker.setTitle("")
    marker.setPosition()
    marker.setSnippet("")
```
to change the info of marker after the marker added.

**Comment by Trinea** [comment]
@jjhurlock

**Comment by tobrun** [comment]
With the upcoming release of 4.0.0 we are making marker interaction a bit more dynamic by allowing the position and the icon to be update dynamically (This feature landed with https://github.com/mapbox/mapbox-gl-native/commit/b3953029909cbb6d4d8cc48fc95acf71523f941b).

I just verified that the other mentioned methods (`setTitle` and `setSnippet`) will require some extra work.

Before getting into this, could you reply if you:

- need to have the InfoWindow open while changing the title/snippet?
- or will the InfoWindow be closed first before changing the titlte/snippet?

cc @bleege @zugaldia

**Comment by bleege** [comment]
@tobrun Let's have the InfoWindow close when any changes happen as it'll minimize distraction in the UI.

**Comment by tobrun** [comment]
@bleege the reason why I asked is that we currently allow multiple InfoWindows open at the same time + @Trinea made a feature request of not closing the infowindows on touch..

**Comment by Trinea** [comment]
Hi, @tobrun @bleege  We need have the InfoWindow open while changing the title.  
It looks like this, the InfoWindow keep open after showInfoWindow(), and content of the infoWindow will change at the same time.  
![](https://github.com/Trinea/trinea-download/blob/master/temp/center-marker.gif?raw=true)

**Comment by tobrun** [comment]
With next release all the MarkerView methods are updatable except for the setTitle/setSnippet. These are ticketed out in https://github.com/mapbox/mapbox-gl-native/issues/5237. Going to close this issue in favour of that one.
