### ISSUE TITLE
Always zoom by the center of screen, wherever the point I clicked

### ISSUE THREAD

**Issue by Trinea** [mapbox/mapbox-gl-native#4151]
Always zoom by the center of screen, wherever the point I clicked
Like below, The map is zoomed always from the middle of the map, no matter where I clicked on the map.
![](https://github.com/Trinea/trinea-download/blob/master/temp/center-zoom.gif?raw=true)

**Comment by Trinea** [comment]
@jjhurlock

**Comment by tobrun** [comment]
@Trinea 
This effect can be achieved without making any changes to the SDK.
I will add an example to our test app since this will be a typical feature users would like to implement.

**Comment by tobrun** [comment]
I was able to make it partially work: 
- https://www.dropbox.com/s/hdol2emuyzppumy/device-2016-03-03-102206.mp4?dl=0

but there are some edge cases as rotate that aren't working as expected and will be more work than I initially anticipated. I'm thinking about picking this up as part of #3276.

**Comment by Trinea** [comment]
ok, Thank you very much.

**Comment by bleege** [comment]
I tested this again using the latest in the `release-android-v4.1.0` branch (where `4.1.0 Final` will be built from) and discovered that the zoom on single tap is now using a `scaleBy()` call to make the zoom towards where the tap was made but not directly on it.  From what I understand the need is for the zoom to happen directly on where the tap was made.  @Trinea @tobrun Is this correct?

![20160606-4-1-test](https://cloud.githubusercontent.com/assets/989928/15831951/9ab4a21a-2be5-11e6-9fa1-d7ae4f988907.gif)

**Comment by tobrun** [comment]
@bleege this is about altering the focal point of the a gesture. In current implementation we take x,y from the motion event and only support a limited API on MyLocationView for tracking modes:

```java
     // Single finger double tap
                    if (mMapboxMap.getTrackingSettings().isLocationTrackingDisabled()) {
                        // Zoom in on gesture
                        zoom(true, e.getX(), e.getY());
                    } else {
                        // Zoom in on user location view
                        zoom(true, mMyLocationView.getCenterX(), mMyLocationView.getCenterY());
                    }
```

Instead of using user location we use a user configurable focal point

I'm going to add more information in the related feature ticket. Going to close this in favour of https://github.com/mapbox/mapbox-gl-native/issues/4924
