### ISSUE TITLE
setZIndex、setRotation method for Marker

### ISSUE THREAD

**Issue by Trinea** [mapbox/mapbox-gl-native#4152]
There may be some markers on the same position, We want to change the zIndex of markers.
We want to change the direction of the marker, like rotating the marker.

**Comment by Trinea** [comment]
@jjhurlock

**Comment by jfirebaugh** [comment]
Thanks for the feature requests! We have separate tickets tracking both these features:

* [zIndex](https://github.com/mapbox/mapbox-gl-native/issues/1728)
* [Rotation](https://github.com/mapbox/mapbox-gl-native/issues/4207)

**Comment by Trinea** [comment]
Thank you.

**Comment by wanggang316** [comment]
+1
