### ISSUE TITLE
iOS Telemetry posting empty objects

### ISSUE THREAD

**Issue by camilleanne** [mapbox/mapbox-gl-native#4154]
Seeing some errors coming through to the telemetry server:

`[Mon, 29 Feb 2016 17:00:27 GMT] [error] [default] Request body data is the wrong type`

This means that an object (mostly likely an empty object) is being sent to the events endpoint, instead of an array of objects. This has been happening for a while, and doesn't seem to have origins in recent code changes.

**Comment by boundsj** [comment]
The prerelease for iOS v3.2.0 has several refactors to events and related networking that should hopefully address any issues (or at least make issues we do have easier to debug). Relatedly work continues on the update to the V2 spec in https://github.com/mapbox/mapbox-gl-native/issues/4148. Getting the SDK version in the user agent string will help us link any future errors to specific releases.

**Comment by boundsj** [comment]
@camilleanne or @mick do you think this is ok to close? Have their been any of these errors from events sent by the iOS SDK when the version is 3.2.0 or greater?

**Comment by camilleanne** [comment]
Out of curiosity I checked the logs again -- seeing a small handful of these errors for:

* `MapboxEventsiOS/3.2.3` and below
* `MapboxEventsAndroid/4.0.0-beta.2`

Not seeing any sort of pattern, and the number of events is low, but I'm going to keep this open for now.

**Comment by friedbunny** [comment]
@camilleanne Checking in — are empty posts still an issue? I’d guess that those SDK versions have largely faded from use.

**Comment by boundsj** [comment]
Closing as stale. Please reopen if this is still an issue @l-r @mick
