### ISSUE TITLE
PrecisionPoint TransformState::latLngToPoint dateline issue

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4155]
Issue in `mbgl` when calculating points based on LatLng from the left side of the dateline after crossing the dateline from left to right. This is a follow up issue for https://github.com/mapbox/mapbox-gl-native/issues/3995.

An example:

Take this LatLng:
> LatLng [longitude=-179.64576449708883, latitude=-16.83408606795382, altitude=0.0]

before crossing the dateline `latLngToPoint` is giving us Point[**x=455.80133**, y= 746.6456]
while after crossing the dateline `latLngToPoint` is giving us Point[**x=393667.44**, y=747.1837].
Normally we should see a small decrease in value not a big increase.

**Comment by tobrun** [comment]
Related method in `transform_state.cpp`:

```cpp
PrecisionPoint TransformState::latLngToPoint(const LatLng& latLng) const {
    return coordinateToPoint(latLngToCoordinate(latLng));
}
```

which on his turn calls:

```cpp
PrecisionPoint TransformState::coordinateToPoint(const TileCoordinate& coord) const {
    mat4 mat = coordinatePointMatrix(coord.zoom);
    matrix::vec4 p;
    matrix::vec4 c = {{ coord.column, coord.row, 0, 1 }};
    matrix::transformMat4(p, c, mat);
    return { p[0] / p[3], height - p[1] / p[3] };
}
```
and 
```cpp
TileCoordinate TransformState::latLngToCoordinate(const LatLng& latLng) const {
    const double tileZoom = getZoom();
    const double k = zoomScale(tileZoom) / worldSize();
    return {
        lngX(latLng.longitude) * k,
        latY(latLng.latitude) * k,
        tileZoom
    };
}
```

**Comment by 1ec5** [comment]
I can reproduce this issue in the iOS SDK. From my location in California, if I zoom out to z0 and pan west, the user location annotation disappears as soon as the map view’s center point crosses the antimeridian. The iOS SDK similarly positions the user location annotation using `Transform::latLngToPoint()` (via [`Map::pixelForLatLng()`](https://github.com/mapbox/mapbox-gl-native/blob/09c91008910746667b26d04eca679dfa5bb6b03b/platform/ios/src/MGLMapView.mm#L2178) and [`-[MGLMapView convertCoordinate:toPointToView:]`](https://github.com/mapbox/mapbox-gl-native/blob/09c91008910746667b26d04eca679dfa5bb6b03b/platform/ios/src/MGLMapView.mm#L3745)).

**Comment by tobrun** [comment]
To make [this](https://youtu.be/JCSLamLWle4) problem a bit more visual

**Comment by brunoabinader** [comment]
@tobrun @1ec5 this should have been fixed in fd123de8ad060441cdd318091531653df4cbcc79 - could you please test using this hash?

**Comment by tobrun** [comment]
@brunoabinader I'm on it, currently building specifically from that branch.

**Comment by tobrun** [comment]
The user location and camera are **LatLng [longitude=179.931, latitude=-16.945]**
At that time the user location is converted to **x: 77.64928** and **y: 918.33923**

Just before crossing the dateline the camera is on **LatLng [longitude=179.99965655644286, latitude=-16.91392665410768]** the values are **x: 40.649273** and **y: 906.33923**.

Just after crossing the dateline the camera is on **LatLng [longitude=-179.99907836847547, latitude=-16.91429282823615]** the values are **x: 3601749.0** and **y: 618666.6**

While it should be almost the same as before crossing, the x value should be a bit lower.

**Comment by tobrun** [comment]
Here is the related [video](https://youtu.be/vlN-BLCpe5M) showing it,
note that the hash mentioned above contained this flashing regression from #4174.
which is no longer a problem on master.

**Comment by brunoabinader** [comment]
On it :+1:

**Comment by brunoabinader** [comment]
:point_right: #4214.
