### ISSUE TITLE
How to avoid deselect the infowindow of  marker when click the map About android sdk

### ISSUE THREAD

**Issue by Trinea** [mapbox/mapbox-gl-native#4159]
the infowindow of  marker will dismiss when click the map, how to avoid this. 

like this:
![](https://github.com/Trinea/trinea-download/blob/master/temp/center-marker.gif?raw=true)

**Comment by tobrun** [comment]
We currently don't expose a configuration to leave them open, 
Current implementation always calls `mMapboxMap.deselectMarkers()`
To have this feature, we should expose this as a flag in `UiSettings.java`.

**Comment by Trinea** [comment]
ok, thank you.

**Comment by zugaldia** [comment]
Picking this one up.

**Comment by zugaldia** [comment]
https://github.com/mapbox/mapbox-gl-native/pull/5312 exposes an API to make this possible. With this new behavior, developers can decide whether to close or not the infowindows under a map single tap:

![video](https://cloud.githubusercontent.com/assets/6964/15973863/912aed86-2f13-11e6-847e-58de39c0a1e3.gif)

**Comment by zugaldia** [comment]
@Trinea this is now implemented and it'll be part of the next release 4.1. Please let us know if you're still missing any functionality here.
