### ISSUE TITLE
How to display location errors 

### ISSUE THREAD

**Issue by KaiWangCanada** [mapbox/mapbox-gl-native#4160]
Like this in google map:

![screenshot_20160301-113605](https://cloud.githubusercontent.com/assets/10340634/13433911/f2090528-dfa1-11e5-8977-980454e00bb7.png)

**Comment by tobrun** [comment]
Currently we don't expose an API to achieve that functionality, I have added the label `feature request` to this issue. Thank you @KaiWangCanada for reaching out!

**Comment by cammace** [comment]
@KaiWangCanada can you clarify on this feature? The issue title is `How to display location errors` yet you are only showing a screenshot. You could also do this using marker views and the latest SDK correct @tobrun?

**Comment by tobrun** [comment]
This is currently possible with MarlerViews, runtimestyling or roll you own implementation. Closing for now as I don't see this feature land as part of the SDK.
