### ISSUE TITLE
Android SDK crash for jni

### ISSUE THREAD

**Issue by Trinea** [mapbox/mapbox-gl-native#4162]
Sometimes map will crash, log is
```
libc: Fatal signal 6 (SIGABRT), code -6 in tid
```

It'a may be caused by jni lib.

**Comment by tobrun** [comment]
@Trinea 
Thank you for reaching out and reporting this crash.
- could you give us the full stacktrace? (their should be additional items in the log)
- do you have a use-case to reproduce this?
- are you using the `3.2.0` version of the SDK?

**Comment by Trinea** [comment]
We are using 3.1.0.

I will reproduce this later.

**Comment by tobrun** [comment]
Thank you that will be very helpful.

Just a small note about `3.1.0`, I highly recommend you upgrading to `3.2.0`. This release contains multiple bugfixes. Also small note about `4.0.0`, this version is going to bring a big API change. IMHO the sooner you migrate the better (using the SNAPSHOT).

**Comment by Trinea** [comment]
ok, thank you

**Comment by Trinea** [comment]
@tobrun  where is 4.0.0-SNAPSHOT ?
```
dependencies {
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:4.0.0-SNAPSHOT@aar') {
        transitive = true
    }
}
```
If this, cannot found it, do i need add other maven address

**Comment by jjhurlock** [comment]
Hi @Trinea. Here's the 4.0.0-SNAPSHOT: https://www.mapbox.com/android-sdk/#gradle.

Make sure you add:

```
repositories {
    mavenCentral()
    maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
}
```

to your gradle file.

**Comment by Trinea** [comment]
Thank you very much.

**Comment by tobrun** [comment]
This crash was reported for an older version. Reopen if still reproducible with SNAPSHOT.
