### ISSUE TITLE
Support overzooming raster 

### ISSUE THREAD

**Issue by jonkan** [mapbox/mapbox-gl-native#4167]
My understanding is that overzoomed rendering of raster-tiles within a source's min/max-zoom is currently not supported?.
The particular issue we're experiencing is that, when panning around offline, tiles disappear. For example:
- A raster source with minZoom:5, maxZoom:18.
- A cache (offline database) containing tiles for z5-16.
- Pan around on z > 16 while offline.

While zooming in everything is fine, e.g. a z16 tile gets rendered and gets overzoomed when continuing to z > 16. But when panning, any overzoomed tiles that leave the screen don’t get re-rendered and we’re left with a blank map.

One could argue that this is not an issue since the source is specified to have z5-z18 and we’re missing z17-18. However, allowing overzoomed rendering would have the following benefits:
- Allow downloading part of a source’s zoom levels for offline, e.g. z5-16, while still allowing higher zoom levels, e.g. z17-18, to be downloaded on-demand (when a network connection is available).
- Handles poor/lost network connections better by rendering a lower zoom level tile while waiting for the "correct one” (that might not come).

What are you thoughts on this?
Would it be possible to render the "parent-tile" where the expected tile don't yet exist?

**Comment by jfirebaugh** [comment]
This is being tracked in #123.
