### ISSUE TITLE
Marker disappears at high zoomlevel

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4168]
When you zoom in enough on a marker it disappears.
It reappears when you zoom back out.

See this clip:
- https://www.dropbox.com/s/1lvxnlcqgt6fru2/device-2016-03-02-105751.mp4?dl=0

**Comment by jfirebaugh** [comment]
Confirmed. Seems Android specific -- not reproducible in OS X test app.

**Comment by tobrun** [comment]
Per suggestion from @jfirebaugh in https://github.com/mapbox/mapbox-gl-native/issues/4272#issuecomment-199468525 
Going to scale back on the maxzoomlevel. 
Picking this up tomorrow.

**Comment by jfirebaugh** [comment]
Removing from 4.0.0 milestone; we're going to work around this issue by limiting the maximum maximum zoom level to 21.

**Comment by cammace** [comment]
https://github.com/mapbox/mapbox-gl-native/pull/4417 seems to have fixed this issue? I'm unable to reproduce with either gl markers or marker views on Android. Safe to close?

**Comment by tobrun** [comment]
We have increased maxZoom back in #7155, will reopen if still reproducible.
