### ISSUE TITLE
make setInfoWindowAdapter return null

### ISSUE THREAD

**Issue by KaiWangCanada** [mapbox/mapbox-gl-native#4173]
I have some markers on mapView. I use setInfoWindowAdapter to customize info window. For mylocation marker, when clicked, I don't want to display any info window. I make setInfoWindowAdapter return null when the marker is mylocation, but it still display an empty info window.
how to make it display no window?
![device-2016-03-02-164502](https://cloud.githubusercontent.com/assets/10340634/13476567/6a1c54e4-e096-11e5-89e9-83c1acc770ed.png)

**Comment by KaiWangCanada** [comment]
my code:
mMapView.setInfoWindowAdapter(new MapView.InfoWindowAdapter() {

            @Override
            public View getInfoWindow(@NonNull final Marker marker) {

                // click my place, exit
                // no title, getTitle() returns null
                if (null == marker.getTitle()) {
//                    Logger.v("my place");
                    View _view = null;
                    return _view;
                }
...

**Comment by tobrun** [comment]
@KaiWangCanada which version of the SDK are you using?

**Comment by KaiWangCanada** [comment]
@tobrun 
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:3.0.0@aar') {
        transitive = true
    }

**Comment by tobrun** [comment]
@KaiWangCanada 

the logic behind this internally is:

```java

        boolean handledDefaultClick = false;
        if (mOnMarkerClickListener != null) {
            // end developer has provided a custom click listener
            handledDefaultClick = mOnMarkerClickListener.onMarkerClick(marker);
        }

        if (!handledDefaultClick) {
            if (isInfoWindowValidForMarker(marker) || getInfoWindowAdapter() != null) {
                mInfoWindows.add(marker.showInfoWindow(this, mMapView));
            }
        }
```

If you don't want a certain Marker's InfoWindow to show up, you should add an OnMarkerClickListener and return true to indicate to the system that the marker click was handled.

**Comment by KaiWangCanada** [comment]
@tobrun thank you, tobrun. totally missed this point!
