### ISSUE TITLE
Greenland rendering artifacts when pitching

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#4176]
You can notice the rendering artifacts from the screenshot below:
![greenland](https://cloud.githubusercontent.com/assets/76133/13479341/ca80888a-e0de-11e5-847a-ae9d4deba2ba.png)

Notice that while Greenland has it, Antarctica doesn't.

/cc @mapbox/gl

**Comment by jfirebaugh** [comment]
@brunoabinader Is this still reproducible?

**Comment by brunoabinader** [comment]
@jfirebaugh I wasn't able to reproduce it on macOS w/ retina screen, so closing for now.

Once I have access to my Linux desktop I'll test it there to double check.
