### ISSUE TITLE
Offline Maps: Timing, Launch, and Feedback

### ISSUE THREAD

**Issue by twbell** [mapbox/mapbox-gl-native#4178]
Offline Maps will be available March 15 in Android 4.0.0 and iOS 3.2.0.  

[Android Offline is available now as a snapshot](https://www.mapbox.com/android-sdk/#gradle); iOS Offline is forthcoming.  We have [posted preview documentation](https://www.mapbox.com/help/mobile-offline/) with an overview of features and capabilities, plus code examples for iOS and Android.  

We are heads-down with internal testing for the next two weeks, but welcome comments and questions here that help us improve the code, the feature, and the documentation.

**Comment by zugaldia** [comment]
Please tag your tickets with `offline`. This is a list of known issues: https://github.com/mapbox/mapbox-gl-native/issues?q=is%3Aissue+is%3Aopen+label%3Aoffline

**Comment by davidchiles** [comment]
[We're](https://github.com/Burning-Man-Earth) looking forward to how the discussion of MBTiles and consuming pre-built databases shakes out. Thinking of running a 'server' on the device to mimic API endpoints to access a pre-built database in the meantime.

**Comment by twbell** [comment]
We launched today: https://www.mapbox.com/blog/offline-mobile-maps/  I'm closing this ticket; please add issues seperately tagged with `offline`. Known issues are here: https://github.com/mapbox/mapbox-gl-native/issues?q=is%3Aissue+is%3Aopen+label%3Aoffline
