### ISSUE TITLE
Can't resolve marker from emerald style

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4180]
![untitled](https://cloud.githubusercontent.com/assets/2151639/13487228/7e6f12a6-e118-11e5-86fb-bf7add6fdad5.png)

The emerald style used to have it own marker, now I'm always seeing the default marker. 
In my logcat I'm seeing:

![screen shot 2016-03-03 at 08 11 34](https://cloud.githubusercontent.com/assets/2151639/13487156/e21756a2-e117-11e5-9937-ee08065c69f3.png)

There are two things:
 - fixing why he can't find the sprite
 - fixing the way it's constantly logging these items, this is making the map laggy.

**Comment by jfirebaugh** [comment]
This was fixed in the style: https://github.com/mapbox/mapbox-gl-styles/issues/288
