### ISSUE TITLE
[android] [bug] UserLocationView Compass Mode and Map Rotation + Accuracy Path too big

### ISSUE THREAD

**Issue by mayardb** [mapbox/mapbox-gl-native#4186]
Hello Mapbox team!

While implementing #4137 and #4136, I find two major bugs:

- The test sample is crashing when using a high zoom and the accuracy is not precise:
```
03-03 15:52:10.747 20439-20439/com.mapbox.mapboxsdk.testapp W/OpenGLRenderer: Path too large to be rendered into a texture
03-03 15:52:10.747 20439-20439/com.mapbox.mapboxsdk.testapp W/OpenGLRenderer: Path too large to be rendered into a texture
03-03 15:52:11.357 20439-20439/com.mapbox.mapboxsdk.testapp A/libc: Fatal signal 11 (SIGSEGV) at 0x00000058 (code=1), thread 20439 (pboxsdk.testapp)
```
Don't know if it is related, but that's the way I always reproduce this crash.

-  When Map is not facing the North, UserLocationView is not rightly orientated.

I am using Google Maps as reference:
![maps location](https://cloud.githubusercontent.com/assets/6266608/13497689/0137d568-e157-11e5-992d-3b75bf9cdbea.png)

Then, without moving the phone, but changing the map orientation (see the compass view)
Mapbox User Tracking Mode sample pointing the north:
![mapbox north](https://cloud.githubusercontent.com/assets/6266608/13498194/42932c0e-e159-11e5-9128-26dffe2f7d2c.png)

Mapbox User Tracking Mode sample pointing the east:
![mapbox east](https://cloud.githubusercontent.com/assets/6266608/13498193/428e9d06-e159-11e5-949e-539f88733c33.png)

Mapbox User Tracking Mode sample pointing the south:
![mapbox south](https://cloud.githubusercontent.com/assets/6266608/13498195/42a0ddf4-e159-11e5-9bd5-06c5d9ebc03c.png)

Mapbox User Tracking Mode sample pointing the west:
![mapbox west](https://cloud.githubusercontent.com/assets/6266608/13498196/42a5f780-e159-11e5-92aa-f0b6c992a704.png)

**Comment by tobrun** [comment]
@mayardb thank you for writing this up and adding screenshots. This is super helpful. If I understand correctly this is the last bug to be resolved to get #4137 in? I will try looking at this in the next days.

**Comment by mayardb** [comment]
I think #4137 is over as it covers all the needed functionality. But while I can rotate the map and display the bearing drawable at the same time, #4137 highlights this orientation bug.


Concerning the accuracy crash, we have been thinking about two things:

1. We could use the best estimate Algorithm that is recommended by Google: http://developer.android.com/guide/topics/location/strategies.html#BestEstimate. It will grant use not to display inaccurate location if a more precise location was known few seconds ago

2. If the location is too inaccurate, we could display the stale drawable. (but I have not investigated to know what means "too inaccurate")

**Comment by tobrun** [comment]
@mayardb yeah, I wanted to take a look at improving the accuracy circle for some time now in #3078, now that we can zoom even further the problem has only gotten worse until the point it even crashes. FWIW I would like to rewrite `UserLocationView` from scratch since it has multiple problems with it. 

Thank you for sharing that link, that is great information to have! But I wanted to point out that we try to limit our interaction with location improvements as much as possible. Since, in my opinion, should be optimised by Mapzen LOST (the framework we use to get location updates).

**Comment by tobrun** [comment]
Closing for now as non-actionable, the `best estimate` is something I will take with me for when we decouple from Mapzen LOST.
