### ISSUE TITLE
mapview horizontally squeezed in Navigation Drawer Activity

### ISSUE THREAD

**Issue by KaiWangCanada** [mapbox/mapbox-gl-native#4187]
I'm using navigation drawer. I created a new project using android studio default navigation drawer template (file->new->new project->...->navigation drawer activity), add mapbox (v 3.2.0) example code (https://www.mapbox.com/android-sdk/examples/), the map looks like horizontally squeezed.
(The only thing I do myself is putting a marker. )
![device-2016-03-03-102742](https://cloud.githubusercontent.com/assets/10340634/13499281/8d938ea2-e12b-11e5-9ec6-e739f837ae8c.png)

**Comment by KaiWangCanada** [comment]
tested on Nexus LG. when not using drawer, everything is fine.

**Comment by tobrun** [comment]
@bleege could this be related to resize issue?

**Comment by bleege** [comment]
It may be related to #3622 , but before know for sure can @KaiWangCanada confirm that the activity is not using the following in the AppManifest:

`android:configChanges="orientation|keyboardHidden|screenSize"`

The `screenSize` attribute is known troublemaker for this while not providing much benefit to the app.

**Comment by KaiWangCanada** [comment]
@bleege It is basically an android template project, so I am not sure exactly what is happening there. But I checked the Manifest file, there is no android:configChanges. I also searched screenSize in the whole project, there is no screenSize. Hope that helps!

**Comment by tobrun** [comment]
This will need to be retested if #4225 lands, I believe this will fix the issue since the padding will probably trigger a resize after the layout has been created.

**Comment by tobrun** [comment]
Retested and this bug is resolved with above.

![device-2016-03-08-132931](https://cloud.githubusercontent.com/assets/2151639/13611721/eb103968-e531-11e5-84f2-b14c340f1198.png)

**Comment by KaiWangCanada** [comment]
Thank you guys :+1:
