### ISSUE TITLE
Allow C99 extensions in iOS and OS X SDK targets

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#4191]
C99 extensions are currently disallowed throughout the project due to pedantic warnings being enabled. This makes no sense in Objective-C code, since we’ve been able to depend on C99 support for years. At the least, the iOS and OS X SDK targets should get a `-Wno-c99-extensions` flag. This will enable us to remove a fair amount of redundant code in MGLMapView.

If any non-SDK Objective-C code needs to use C99-specific features like designated initializers or the Elvis operator, we can selectively turn off the Clang warning via `#pragma clang diagnostic ignored "-Wc99-extensions"` on a case-by-case basis.

/cc @jfirebaugh @boundsj

**Comment by boundsj** [comment]
:+1:
