### ISSUE TITLE
Scheduled nightly Bitrise builds

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#4196]
We should have Bitrise build the iOS SDK and iosapp nightly via a scheduled build and keep the artifacts around. The Android SDK already has nightly snapshots hooked up this way.

Blocked by #3388 and #3275.

/cc @zugaldia @boundsj @tmcw

**Comment by friedbunny** [comment]
👍👍👍👍👍

**Comment by 1ec5** [comment]
We can also consider running the static analyzer in this nightly build (reviving #1562), as long as it doesn’t cause builds to time out.

**Comment by 1ec5** [comment]
Nightly builds are implemented on Bitrise, but the artifacts currently live on Bitrise. Leaving this issue open until we have a way to upload the artifacts somewhere more discoverable.
