### ISSUE TITLE
Verify Mapbox SDK on Samsung flagship's device( Galaxy S7 )

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#4197]
It would be great if  Mapbox SDK could be verified as working on Samsung's flagship device (Galaxy S7).
I also checked if the device was available at AWS device farm before filing this issue(it is not).

- Samsung broke some popular apps (like Flipboard) and some of their own apps on this device.
- It uses latest Adreno 530 GPU.

**Comment by bleege** [comment]
Thanks for the report on Samsung S7 @mb12 .  Is there any links to details about why it's crashing or what Samsung changed?  Specifically are these apps using Samsung API in their apps?

The Mapbox Android SDK relies on core Android AOSP and Support Library API so is generally reliable across devices.  It also uses OpenGL 2 for rendering which is pretty widely used and battle tested.

**Comment by mb12** [comment]
I was able to find an on display unit in a store this afternoon. Mapbox Demo App is working great.

**Comment by bleege** [comment]
Fantastic!  Thanks for doing this @mb12.  :rocket:
