### ISSUE TITLE
[android] Add centerOffset and infoWindowOffset properties to Annotation 

### ISSUE THREAD

**Issue by mayardb** [mapbox/mapbox-gl-native#4218]
Android counterpart of #2151.

### Goal:
Avoid making `Marker` `Icon` symmetric with lots of transparent pixels to center it at the right `LatLng`. (because markers potentially have shadows, and increasing the marker height increases the click area)

### Possibility:
@RomainQuidet submitted a pull request: #3220
Do you think it is a good idea to start from this PR ?

**Comment by tobrun** [comment]
This request has now been fulfilled with the introduction of Marker View API in `4.1.0`
