### ISSUE TITLE
Offline [Android]: Make it possible to store (and load) maps on more than just the first of externalFilesDirs()

### ISSUE THREAD

**Issue by rm3dbeckers** [mapbox/mapbox-gl-native#4223]
I just browsed through the code and it looks like currently it is only possible to download regions to the externalFilesDir (i.e. the first result of getExternalFilesDirs(), which means that right now it's not possible to store an OfflineRegion on an external sdcard).
Would it be possible to allow creation of an OfflineRegion and providing a preferred/mandatory storage location?
#584

**Comment by jfirebaugh** [comment]
No, sorry. The offline implementation depends on all offline regions being placed into the same database file on disk.
