### ISSUE TITLE
Fit bounds in mobiles

### ISSUE THREAD

**Issue by vns-cuong** [mapbox/mapbox-gl-native#4251]
Hi, 
I found this topic for web, but I can't implement it in mobile (android, iOs): https://www.mapbox.com/mapbox.js/example/v1.0.0/fit-map-to-markers/
I found this for android, but it seems not available anymore: http://stackoverflow.com/questions/26173010/mapbox-android-determine-zoom-level-that-contain-all-markers
Please let me know how can I implement it in android and iOs?
Thank you so much.

**Comment by 1ec5** [comment]
In the iOS SDK, call [`-[MGLMapView showAnnotations:animated:]`](https://www.mapbox.com/ios-sdk/api/3.1.2/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)showAnnotations:animated:) to fit to a specific set of annotations. You can pass in the map view's `annotations` property to fit to all the existing annotations. More generally, you can fit to any arbitrary bounding box using [`-setVisibleCoordinates:`](https://www.mapbox.com/ios-sdk/api/3.1.2/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)setVisibleCoordinateBounds:animated:) or one of its variations.

**Comment by vns-cuong** [comment]
Thank you so much. I don't see any method in android as showAnnotations in iOs, but I already saw setVisibleCoordinates in android. I'll try it now.

**Comment by dstiglr** [comment]
Wow, Mapbox sdk for ios is awesome. Thank you
