### ISSUE TITLE
provide an estimation of total size for offline regions

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#4258]
Tile sizes are variable, so there is no way to calculate the precise size of an arbitrary offline region other than downloading it and then summing the actual size. However, we can make several types of estimates. In descending order of likely accuracy:
- Estimates based on the size of tiles already downloaded. We could assume that the remainder of the tiles will be a similar size, and estimate accordingly.
- Estimates based on average tile sizes for particular sources. For frequently used sources such as `mapbox-streets-v7`, we can calculate typical tile sizes. To be useful, they would need to have at least zoom-level granularity: an estimated average tile size for each zoom level from 0 to 16. Then we could estimate by multiplying by the number of tiles in the region at each zoom level.
- A nominal "typical tile size" estimate. Likely broken down at least to: 512px vector tile, 256px raster tile, 512px raster tile, 256px@2x raster tile, 512px@2x raster tile. This would be a fairly inaccurate fallback for unknown sources.

**Comment by mb12** [comment]
@jfirebaugh Why can't you do it on the server side?

**Comment by jfirebaugh** [comment]
You might be under the impression that offline is implemented by requesting some sort of single archive from the server. That isn't the case: an offline "download" is just a bunch of individual requests for each of the required resources. The server doesn't have any special knowledge of the offline region as a whole which it could use to calculate the total size. Among other benefits, this means that offline features aren't limited to Mapbox APIs. A server side implementation that was able to calculate a total size would either be proprietary, or require some sort of open protocol specification.

**Comment by mb12** [comment]
Without server side support, how do you compute what code points to download for a font set?

**Comment by jfirebaugh** [comment]
We download them all: https://github.com/mapbox/mapbox-gl-native/issues/4069.

**Comment by daniel-choi** [comment]
Hi all! Any updates on this issue or https://github.com/mapbox/mapbox-gl-native/issues/9460?

**Comment by emtjoshhart** [comment]
This should be reopened, there is a huge use case for this and Mapbox could provide an easier way to estimate the file size.
