### ISSUE TITLE
Project warnings in Xcode 7.3b5 — ALWAYS_SEARCH_USER_PATHS

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#4264]
I get several of these warnings building the iOS or OS X SDK in Xcode 7.3b5:

```
warning: using 'ALWAYS_SEARCH_USER_PATHS = YES' while building targets which define modules ('DEFINES_MODULE = YES') may fail. Please migrate to using 'ALWAYS_SEARCH_USER_PATHS = NO'.
```

/cc @kkaefer

**Comment by AdrianaPineda** [comment]
I'm having the same issue. Do you have any updates?

**Comment by 1ec5** [comment]
I’m overhauling the SDK project in #4641. The new SDK targets on that branch no longer trigger this warning.

**Comment by AdrianaPineda** [comment]
Thanks!
