### ISSUE TITLE
Map becomes unresponsive at high zoom levels

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4272]
When you zoom in on zoom levels > 22 the map becomes unresponsive and start skipping frames.

**Comment by tobrun** [comment]
Since we have bad performance on high zoomlevels and there are some know bugs with this as well #4168. We could opt scaling back the maxim zoomlevel a bit for `4.0.0` release.

@bleege @zugaldia

**Comment by jfirebaugh** [comment]
Yeah, let's set the max zoom to 21 for now and avoid this bug, #4416, and #4168.

**Comment by tobrun** [comment]
@jfirebaugh thank you for the feedback, I will pick this up tomorrow

**Comment by jfirebaugh** [comment]
Removing from 4.0.0 milestone; we're going to work around this issue by limiting the maximum maximum zoom level to 21.

**Comment by bleege** [comment]
Maximum Zoom level back to 21 is happening in #4417 .

**Comment by tobrun** [comment]
Merged with ca8212d
