### ISSUE TITLE
it crashed when i set debug

### ISSUE THREAD

**Issue by haoshengfucn** [mapbox/mapbox-gl-native#4276]
mapboxgl crashed when i debug the GlyphSource. the code as these:(glyph_source.js)
        var glyphAtlas = new GlyphAtlas(512, 512);
        glyphAtlas.debug=true;
        this.atlases[fontstack] = glyphAtlas;

**Comment by 1ec5** [comment]
Hi @haoshengfucn, this looks like JavaScript code. The JavaScript version of Mapbox GL is maintained over in the mapbox/mapbox-gl-js repository. Please refile your issue there. Thank you!
