### ISSUE TITLE
can mapbox search place by types?

### ISSUE THREAD

**Issue by KaiWangCanada** [mapbox/mapbox-gl-native#4278]
like search "gas_station", return a list of gas stations nearby sorted by distance? using android sdk

it is not a request, just want to know for sure. looks like google map sdk can't do that now, anyway...

**Comment by jfirebaugh** [comment]
@KaiWangCanada, check out https://github.com/mapbox/mapbox-geocoder-android for geocoding support.

**Comment by KaiWangCanada** [comment]
Thank you guys^^
