### ISSUE TITLE
Android MapView getVisibleCoordinateBounds missing?

### ISSUE THREAD

**Issue by OnlyInAmerica** [mapbox/mapbox-gl-native#4290]
I've been unable to find the Android counterpart to [MapView#visibleCoordinateBounds](https://github.com/mapbox/mapbox-gl-native/blob/1ee7264b0edf6601a8170a30c40af4282679f495/platform/osx/src/MGLMapView.mm#L1080). 

Am I missing something, or is MapView? ;)

Thanks! ❤️ your work!

**Comment by tobrun** [comment]
@OnlyInAmerica 
What version of the SDK are you using?

- for the upcoming `4.0.0` release you can use:
  - `mMapboxMap.getProjection().getVisibleRegion()`
- for `3.2.0` there is [this](https://github.com/mapbox/mapbox-gl-native/issues/3863#issuecomment-181825298) workaround.

Reach out if you have any other questions!
