### ISSUE TITLE
(Android) Crash when on map click, to select a location

### ISSUE THREAD

**Issue by ThinkingMonkey** [mapbox/mapbox-gl-native#4292]
(Android) Crash when on map click, to select a location. When the touch is repeated with slightly high frequency.

Device: Motorola xt1068 (Motorola Moto G Dual SIM (2nd gen) )
OS.Android 6

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.mapboxsdk.geometry.LatLng com.mapbox.mapboxsdk.views.NativeMapView.latLngForPixel(android.graphics.PointF)' on a null object reference
>        at com.mapbox.mapboxsdk.views.MapView.fromScreenLocation(MapView.java:2274)
>        at com.mapbox.mapboxsdk.views.MapView$GestureListener.onSingleTapConfirmed(MapView.java:3196)
>        at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:148)
>        at android.app.ActivityThread.main(ActivityThread.java:5443)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by tobrun** [comment]
@ThinkingMonkey thank you for reporting this. Will look into this asap.

**Comment by tobrun** [comment]
Looking at the stacktrace, I'm noticing you are using `3.2.0` version of the library.
With upcoming release we have made this interaction a bit robuster in https://github.com/mapbox/mapbox-gl-native/pull/4212.
I retested on master and was not able to reproduce. 
Feel free to retest this with our [SNAPSHOT](https://www.mapbox.com/android-sdk/#gradle).
Reopen if you can reproduce this.

**Comment by ThinkingMonkey** [comment]
@tobrun Thanks for the tip. I ported to 4.0.0-SNAPSHOT. 

I retested this and the issue isn't coming up.

2 questions:
I have a couple of issues on 4.0.0-SNAPSHOT. Is reporting this now in the development stages fine?

Is there a page(roadmap) where I can find ballpark release dates?

Thanks!

**Comment by tobrun** [comment]
@ThinkingMonkey 
please report as many as you possibly can, user like you make our SDK much better!
We currently don't have such a page publicly available, 
we are aiming at an beta version of `4.0.0` somewhere this week, 
The related stable release doesn't have an ETA yet.
