### ISSUE TITLE
Javadoc Telemetry package for 4.0.0

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4294]
We are missing class javadoc for `telemetry` package and we should validate the method javadoc.

<img width="1079" alt="screen shot 2016-03-12 at 17 05 49" src="https://cloud.githubusercontent.com/assets/2151639/13725626/cdf28426-e874-11e5-9c8b-67e4c403ee4a.png">

**Comment by bleege** [comment]
JavaDocs have been implemented.  The PR #4381 will put them into `master`.  Once there I'll cherry pick them to `release-ios-3.2.0-android-4.0.0` branch.

/cc @jfirebaugh

**Comment by bleege** [comment]
Merged to `master` and cherrypicked to the release branch.

<img width="1189" alt="screen shot 2016-03-18 at 2 26 40 pm" src="https://cloud.githubusercontent.com/assets/989928/13888049/85042eae-ed15-11e5-9bed-11b443c1fa5f.png">
