### ISSUE TITLE
Save actions, code formatting, lint warnings and annotations

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4299]
To improve our code quality and cohesion of this project. I want to introduce a strict system that will enforce code conventions for the produced java code. The main goal here is to automate this as much as possible and enforce certain project specific things through custom lint warnings/annotations. Automation will primarily done through save actions / code formatting features from Android Studio.

In the end of this investigation, we should have some clear guidelines, that we could include `how to write good code - android specific` in our `hey` section. 

Lastly we should also look into enforcing one code style. Currently there are classes with Hungarian notation and others without. There are some classes that add an extra whitespace before starting the method other classes not. We should sit down and discuss a general convention around this.

@bleege @zugaldia @cammace @danswick

**Comment by tobrun** [comment]
Small draft of rules:

#### Rule 1:
Do not talk about Fightclub.

#### Rule 2:
Have automatic save actions/formatting enabled. (setup TBD).

#### Rule 3:
Follow project code convention. (conventions TBD).

#### Rule 4:
Resolve all warnings before committing code.

**Comment by tobrun** [comment]
This is an example of what I want to resolve with this:

<img width="625" alt="screen shot 2016-03-13 at 15 11 58" src="https://cloud.githubusercontent.com/assets/2151639/13731688/ca738472-e945-11e5-87f2-0cf388468115.png">

**Comment by bleege** [comment]
> The main goal here is to automate this as much as possible

Yep.  This whole effort will fail if there isn't a built in tool for checking and flagging this on every commit.  We previously used [Checkstyle in the Raster SDK](https://github.com/mapbox/mapbox-android-sdk-legacy/blob/b5cf38106fae0c475b11059100259b37d8a5776d/MapBox.xml) as it integrates into Android Studio for error checking at commit time.

**Comment by tobrun** [comment]
Discussed and agreed: we are removing Hungarian notation and going for lower classnames

**Comment by zugaldia** [comment]
Now that #5342 has landed enforcing code style with clang-format in core, I think we should start thinking of implementing a similar approach in our Android code.

Of all the ideas presented in this ticket I believe we should start with enforcing code style at build time, integrated with our CI. @bleege mentions we've used [`checkstyle`](http://checkstyle.sourceforge.net/) in the past. I also have had experience using it in other projects with good results.

I suggest we start with the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html), which is reasonable and it's easy to start with as it comes [prebundled](https://github.com/checkstyle/checkstyle/tree/master/src/main/resources) with `checkstyle`, and adapt it to our specific needs. Note that AFAIK this is different from the [Android code style](https://github.com/android/platform_development/tree/master/ide/intellij/codestyles).

Thoughts?

/cc: @ivovandongen

**Comment by ivovandongen** [comment]
A common formatting style would be great. Saves me a lot of work manually formatting and/or merging.

I always liked the plain java style guide as it is quite common knowledge, but updated with at least 100-120 character column width. The Google style guide looks very comparable and suits me fine. And I prefer both over the Android code style for member variable naming.

**Comment by tobrun** [comment]
We have been doing multiple actions to improve the experience. Not seeing much actionable left to do. Closing.
