### ISSUE TITLE
Need the ability to customize the attribution button

### ISSUE THREAD

**Issue by postmechanical** [mapbox/mapbox-gl-native#4313]
On iOS the default info light style is not suitable for all designs. `UIButton` instances initialized with `UIButtonType`s other than `UIButtonTypeCustom` are basically non-customizable with respect to the button image.

**Comment by 1ec5** [comment]
If contrast is an issue, you can change the attribution button’s tint color to something that contrasts better against the map.

**Comment by postmechanical** [comment]
Thanks for the recommendation @1ec5 but we'd prefer to not use an image at all and just title text.

**Comment by 1ec5** [comment]
I see. We went with an info button so it would fit in constrained spaces. A workaround for now would be to hide the attribution button (by setting its `hidden` flag) and roll your own label to put in its place. I'll leave this issue open to track adding more options for displaying attribution, particularly for displaying it as text.

**Comment by lilykaiser** [comment]
Closing due to ticket age. If this is still a problem, please re-open

**Comment by friedbunny** [comment]
With 3.7.0 and https://github.com/mapbox/mapbox-gl-native/pull/10085, it’s possible to use `-[MGLMapView showAttribution:]` to show the default attribution interface.
