### ISSUE TITLE
One-finger pinch gesture moves zoom origin in opposite direction

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-native#4315]
- **Steps to reproduce:** put two fingers on the map and then pinch by moving one of the fingers
- **Expected behavior:** geographic locations under both fingers stay approximately the same as the map zooms
- **Actual behavior:** the locations are off under the fingers, so it appears to be using an incorrect zoom origin

You can confirm that this is a bug by doing the same in Apple/Google maps — they behave correctly in this case.

I'm not sure whether this is reproducible on Android since I'm only testing on iOS, but it's worth making sure too. cc @bleege 

cc @1ec5

**Comment by 1ec5** [comment]
Are you testing on master or on the release-ios-3.2.0-android-4.0.0 branch? Is user tracking enabled? (When the map is tracking the user location, pinching, rotating, and tilting gestures are all centered around the user dot.)

**Comment by mourner** [comment]
@1ec5 user tracking disabled, and I'm using the latest Sirius for iOS.

**Comment by 1ec5** [comment]
I still can’t reproduce. Can you link to a screen recording? Does it seem to matter what area the map is showing?

**Comment by bleege** [comment]
Confirming that I'm also not seeing this in the latest TestApp (which is basically Android 4.0.0-beta.2 in #4419 ).  Happy to investigate further if a screen recording can be made.

**Comment by mourner** [comment]
Unfortunately QuickTime iPhone screen recorder doesn't show touches, so it's hard to demonstrate a video where you can see the problem, but it's definitely there. I'm coming to SF next week so I can demonstrate to @1ec5 live.

**Comment by 1ec5** [comment]
I can reproduce a discrepancy after all. If you place two fingers on the screen such that they straddle a coordinate on the map, then move _one_ of the fingers outward – not both – then the zoom anchor moves in a direction opposite to how it moves in MapKit and Google Maps. For example, if you place your index finger to the left of a POI and your middle finger to the right of it, then move your middle finger to the right, the POI should move to the right as the map zooms in. Instead, it moves to the left.

**Comment by mourner** [comment]
@1ec5 exactly, that's what I described in the initial report:

>  put two fingers on the map and then pinch by moving **one of the fingers**

**Comment by friedbunny** [comment]
Fixed by #4427.
