### ISSUE TITLE
OnDoubleTap doesn't trigger OnCameraChangeListener

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4327]
When you perform a double tap, you are not receiving any `OnCameraChangeListener` updates.

**Comment by tobrun** [comment]
After double checking the commit above doesn't fix it mainly because `zoom` is an animated transition and we should only invalidate after this.

**Comment by tobrun** [comment]
Might need to look into a more general invalidate approach here eg. `OnMapChangeListener`.

**Comment by mpuchala** [comment]
Looks like it sometimes appears on double tap and swipe gesture (changing zoom using swipe) as well.

**Comment by tobrun** [comment]
I'm working around this issue with a runnable/postdelayed solution for now.This has allmost no impact on the codebase for future releases we should migrate the zoom API to use the camera API but for this release it has too high impact to change it.

**Comment by tobrun** [comment]
Created a new ticket to solve this for `4.1.0` in #4406

**Comment by bleege** [comment]
Merged into `release-ios-3.2.0-android-4.0.0`.
