### ISSUE TITLE
Compiler warnings with installed static framework — Module debugging should be disabled when shipping static libraries

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#4338]
When I install the Mapbox iOS SDK static framework into a project and build in Xcode 7.3b5, I get 21 errors that look like this:

```
while processing /Users/mxn/Documents/Playroom/Sedan/Mapbox.framework/Mapbox(reachability.o):
warning: /var/folders/cl/8cgpg37n5cl78pjkbpgml94w0000gn/C/org.llvm.clang.mxn/ModuleCache/2M9FX5S5W7EA5/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: Module debugging should be disabled when shipping static libraries.
```

I’m unaware of any other symptoms, but we should set `CLANG_ENABLE_MODULE_DEBUGGING=NO` when building the static framework with debug symbols:

> When this setting is enabled, clang will use the shared debug info available in clang modules and precompiled headers. Results in smaller build artifacts, faster compile times, and more complete debug info. This should only be disabled when building static libraries with debug info for distribution. [`CLANG_ENABLE_MODULE_DEBUGGING`, `-gmodules`]

/cc @boundsj @friedbunny

**Comment by boundsj** [comment]
@1ec5 I'm unable to repro when building the SDK with Xcode 7.3 and compiling the static Mapbox.framework in client Objective-C or Swift apps in Xcode 7.2.x or Xcode 7.3. I'm also unable to repro the issue when building the SDK with Xcode 7.2.x and compiling in client apps in 7.2 or 7.3.

Closing now and will reopen and look again if a clear repro is found.
