### ISSUE TITLE
setCenterCoordinate should center in MGLMapView bounds instead of screen bounds

### ISSUE THREAD

**Issue by martin-frostware** [mapbox/mapbox-gl-native#4345]
I have a view where the Map is only on the top part of the screen, if i set the center coordinate of the map view, the actual center seems to be set on the center of the screen, not in the bounds of the MGLMapView. This worked fine in 3.0.1, but after updating to 3.1.2 it fails.

**Comment by 1ec5** [comment]
I’m unable to reproduce this issue in 3.1.2. Does the map view’s frame occupy only part of the window, or is it the case that the map view occupies the full window but is obscured by other content (like a bottom bar)? The logical center point can be influenced by the `contentInset` property, which by default automatically accommodates any top and bottom bars.

**Comment by martin-frostware** [comment]
The view had the same size as the screen, but had it's frame offset in negative y.
I tried also setting the contentInset. See the attached image.
Steps i do in viewDidLoad:
1. Set the y constraint constant of the mapView to a negative value. (Default is centerY on parent)
2. call layoutIfNeeded
3. setCenterCoordinate:zoomLevel:animated.

The attached image is the result. The annotation is the lat long that i send as center coord.
Below is a screenshot of the result:
<img width="376" alt="screen shot 2016-03-17 at 09 55 04" src="https://cloud.githubusercontent.com/assets/4425412/13841037/ba94000c-ec26-11e5-9987-9f8b7fd19105.png">

**Comment by 1ec5** [comment]
The `contentInset` property is probably getting overridden by the presence of the top bar. You can turn off that behavior by setting the view controller’s `automaticallyAdjustsScrollViewInsets` property to `NO`.

**Comment by martin-frostware** [comment]
Of course! 
Sorry i didn't pick it up in your previous comment. 
Setting the `automaticallyAdjustsScrollViewInsets ` to `NO` worked.

**Comment by 1ec5** [comment]
That’s great to hear!
