### ISSUE TITLE
How can I know that the offline map was downloaded completely in obj-c MGLOfflinePackDelegate functions?

### ISSUE THREAD

**Issue by jinjinsong** [mapbox/mapbox-gl-native#4358]
How are you?
I implemented module for downloading the offline map.
(I referenced several guides of strong reference of MGLOfflinePack on here.)
My issue is to know when the offline map is downloaded fully.
In swift delegate, it has the explicite function, but In obj-c delegate, I'm not clear which function I have to use. I think it would be progressDidChange function. But I want to know the right way to know the complete status.

Another issue,
If I successfully downloaded offline map and wifi is off(data network is also off), then map is shown automatically on the downloaded offline map region?

Thank you for your trying.
Have a good day.

**Comment by 1ec5** [comment]
> In swift delegate, it has the explicite function, but In obj-c delegate, I'm not clear which function I have to use. I think it would be progressDidChange function.

That’s correct. MGLOfflinePackDelegate can be implemented in either Objective-C or Swift. You can [follow the guide](https://www.mapbox.com/help/mobile-offline/), which contains examples in both languages, or refer to [this Objective-C code](https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.2.0-beta.1/platform/ios/app/MBXOfflinePacksTableViewController.m#L210) that implements the Offline Packs table in the iosapp demo application.

`-offlinePack:progressDidChange:` gets called whenever the pack’s state or progress changes. `pack.state` becomes `MGLOfflineStateComplete` when the download is complete.

> If I successfully downloaded offline map and wifi is off(data network is also off), then map is shown automatically on the downloaded offline map region?

Yes, the SDK should automatically show the downloaded tiles when it’s unable to fetch the tiles online. Please let us know if this is not the case.

**Comment by jinjinsong** [comment]
Thank you for your answer. I'm clear about all issues.
