### ISSUE TITLE
Rotating Annotation in MGLMapView of ios

### ISSUE THREAD

**Issue by jinjinsong** [mapbox/mapbox-gl-native#4360]
How are you?
Is there any way to rotate current annotation when user rotates current screen?
Thank you for your answer.

**Comment by 1ec5** [comment]
This isn’t currently supported for annotations; see #2528. If your application always places this annotation in the same location, you could use a point feature in a GeoJSON source, then include that GeoJSON source in a custom style.

**Comment by jinjinsong** [comment]
Well.
The position and shape is changed dynamically when screen is opened in app.
Is there any other way to rotate the custom annotation according the direction of map in ios?

**Comment by 1ec5** [comment]
#2528 tracks adding this functionality to MGLPointAnnotation. The only other workaround I can think of is to use a UIImageView instead of an MGLPointAnnotation and synchronize the image view with the map view’s `camera` in `-[MGLMapViewDelegate mapView:regionDidChangeAnimated:]`.

**Comment by Juber99** [comment]
Is there any other way to rotate the custom annotation according the direction of map in ios?

**Comment by 1ec5** [comment]
There are now two ways: you can use either a view-backed point annotation or a symbol style layer. For details, see [this guide](https://www.mapbox.com/ios-sdk/api/3.6.2/adding-points-to-a-map.html)’s “Annotation Views” and “Runtime Styling” sections, respectively.

With a view-backed annotation, you’d still have to implement code in `-[MGLMapViewDelegate mapView:regionDidChangeAnimated:]`, or `-[MGLMapViewDelegate mapViewRegionIsChanging:]`, but you’d be able to rotate the view directly, which would be easier than synchronizing an unrelated UIImageView.

With a symbol style layer, use the [`iconRotationAlignment`](https://www.mapbox.com/ios-sdk/api/3.6.2/Classes/MGLSymbolStyleLayer.html#/c:objc%28cs%29MGLSymbolStyleLayer%28py%29iconRotationAlignment) property to make the icon’s rotation match the map. mapbox/mapbox-gl-native#9479 implements an `iconPitchAlignment` property for matching the map’s pitch; it’ll be in the next release (tentatively versioned v3.7.0).

**Comment by iTumbleweed** [comment]
I'm developing a taxi app for iOS and I would like to rotate the annotations, which represent cars on the map, independently based on the data received from the server. Actually I'm switching to Mapbox from Google Maps and I would like an equivalent of `GMSMarker` `rotation` property. Is this possible in any way? Thanks.
