### ISSUE TITLE
[iOS] [Offline] embedded style can not be used for offline cache

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#4361]
On iOS V3.2.0-pre3 branch, I'm using an embedded style file (map styleUrl like "asset://myfile.json"). The cache is working correctly, but creating a pack results in an error callback with the error "URL not managed".
The style displays 2 rasters layers (custom png tiles) if it matters.

The offline storage must be able to use embedded styles.

**Comment by jfirebaugh** [comment]
`asset://` URLs are not supported for offline; you'll need to host the style somewhere. Our plan is to deprecate the `asset://` URL scheme in favor of pre-packaged offline databases that can be merged into the main database: #3894.

**Comment by 1ec5** [comment]
> Our plan is to deprecate the `asset://` URL scheme in favor of pre-packaged offline databases that can be merged into the main database: #3894.

For local styles, I’d recommend specifying a relative NSURL that contains just the file name (or file path relative to the resource bundle). Use of the asset: URL scheme for style URLs is undocumented and not guaranteed to work in the future, whereas I expect that we’ll continue to support local URLs in some form or another.

**Comment by RomainQuidet** [comment]
I agree with you, embedded style file should be supported. In iOS, I don't add myself the scheme asset://, it's in your code (setStyleUrl: in MGLMapView). If there is no scheme, one is added with asset://.
