### ISSUE TITLE
User tracking mode is not KVO-compliant

### ISSUE THREAD

**Issue by JThramer** [mapbox/mapbox-gl-native#4363]
Hey guys,

# The Problem
Apple requires any class that overrides a property setter to call NSKeyValueObserving lifecycle methods before and after setting the iVar. `MGLMapView`'s `- (void)setUserTrackingMode:` does not do this. Thus, anyone who tries to observe the `userTrackingMode` key on `MGLMapView` will never see their `observeValueForKeyPath:ofObject:change:context:` method fire.

# The Fix
In `MGLMapView.m`, in `- (void)setUserTrackingMode:`, add the following lines:
*  Before the ` _userTrackingMode = mode;` assignment on line `3150`, add `    [self willChangeValueForKey:NSStringFromSelector(@selector(userTrackingMode))];`
*  After the ` _userTrackingMode = mode;` assignment on line `3150`, add `    [self didChangeValueForKey:NSStringFromSelector(@selector(userTrackingMode))];`

**Comment by 1ec5** [comment]
Good catch! We should also review any other properties whose setters have corresponding `…animated:` methods, since the setter in that case calls the `…animated:` method. If you see any other properties that aren’t KVO-compliant, please file a separate bug so they don’t fall through the cracks.
