### ISSUE TITLE
TestApp refactor

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4365]
#### Test App Refactor

Currently our test nav drawer is like:

![options](https://cloud.githubusercontent.com/assets/2151639/13855821/88127c36-ec48-11e5-850e-fa5354894afb.png)
![device-2016-03-17-140230](https://cloud.githubusercontent.com/assets/2151639/13855897/ea7674cc-ec48-11e5-9963-e74c18f83489.png)
![device-2016-03-17-140046](https://cloud.githubusercontent.com/assets/2151639/13855898/ea79a516-ec48-11e5-9cd8-7178ba03fe42.png)

The main goal here is to hit the following things:
 - [x] make more clear feature activities for our users
 - [x] organise it in categories and add some explanation
 - [x] make it easier for our users to play around with the app without having to build from source

##### Make more clear feature activities for our users
Simplify the examples we expose, make them a bit more smart eg:

> InfoWindowActivity and InfoWindowConcurrentActivity can be merged together and we can define an OptionsMenu to switch the state

Update outdated examples eg:

> CameraActivity is only show casing ease, move etc. and is not show casing how to use it for other CameraUpdateFactory or allow to change variables.

##### Organise it in categories and add some explanation

Currently the testapp  shows a map, we discussed that having a list of different feature activities, showing 2 lines, could be more usefull for external people. It also removes the need to having different icons for our testactivity and add the test case that people are coming from and moving back to an Activity. Just in the same way our users are doing. 

An example of Material design list with 2 lines + header:
![components_lists_usage3](https://cloud.githubusercontent.com/assets/2151639/13855712/2040f060-ec48-11e5-929f-8f15fb865e40.png)

##### Make it easier for our users to play around with the app without having to build from source

Find a way to expose a ready build apk for our users. This step must be automated and must not interfere with git. The most feasible solution would be to upload the the testapk from Bitrise when doing a nightly build.

**Comment by tobrun** [comment]
cc @bleege @zugaldia @cammace @danswick

**Comment by zugaldia** [comment]
:+1: :+1: :+1:

**Comment by tobrun** [comment]
First up to tackle is `providing a downloadble apk file`:
 - make it easy for users to test out our example app without building from source
 - will be part of our bitrise SNAPSHOT build
 - versioning could be a nice to have (eg. git bisect)
 - may not interfere with our git workflow

Their are many ways to do this.

- Serve it as release on github
  - [example](https://github.com/shadowsocks/shadowsocks-android/releases)
  - **cons**: not ideal for daily builds, this will flood the releases every day.
  - **pros**:  versioning
- Commit it daily to the github repo 
 - **cons**: can't be on master (interference git workflow), limits visibility
- Use an external service to host the APK, provide a fixed link to download
  - AWS
  - Dropbox
  - ...
  - **pros**: doesn't interfere with github, no increased repo size

--

Pseudo code how this will be a step in our `bitrise.yml` flow:
```
    - script:
        title: Publish APK
        inputs:
        - content: |-
            #!/bin/bash

            // upload APK
            upload platform/android/MapboxGLAndroidSDKTestApp/apk/MapboxGLAndroidSDKTestApp-debug.apk
```

--

Something cool I found is that an apk file [automatically generates a QR code on Github](https://github.com/blog/665-apk-downloads-for-android-projects).

**Comment by tobrun** [comment]
I'm currently looking at AWS s3 for uploading the file using AWS CLI. We are already using this dependency in Bitrise to retrieve our signing key. No extra steps needed for configuration.

To upload the APK we will use something as following command:

```
 aws s3 cp platform/android/MapboxGLAndroidSDKTestApp/apk/MapboxGLAndroidSDKTestApp-debug.apk s3://mybucket/MapboxGLAndroidSDKTestApp-debug.apk
```

We should be able to share this file in following manner:

```
http://mybucket.s3-website-us-east-1.amazonaws.com/MapboxGLAndroidSDKTestApp-debug.apk
``

I need to get my AWS authentication setup again before investigating this further.

**Comment by bleege** [comment]
@tobrun This is a great start to this, but please also remember our conversation last week in DC about needing to ship 4.0.0 before we work on anything on the 4.1.0 milestone.  As I type this we still have [8 open tickets on the 4.0.0 milestone](https://github.com/mapbox/mapbox-gl-native/milestones/android-v4.0.0) that need addressing.  :wink:

**Comment by tobrun** [comment]
I was able to a manually upload an .apk and make it publicly download able:
 - http://mapbox-android-sdk.s3-website-us-west-2.amazonaws.com/MapboxGLAndroidSDKTestApp-debug.apk

**Comment by tobrun** [comment]
I was able to upload it via AWS CLI locally by:

 - aws s3 cp /path/mapbox-gl-native/platform/android/MapboxGLAndroidSDKTestApp/build/outputs/apk/MapboxGLAndroidSDKTestApp-debug.apk s3://mapbox-android-sdk/

**Comment by tobrun** [comment]
I just did a run with the same command as bitrise:

> make apackage -j4

After compiling the C++ sources, it seems to do a release build and the file I mentioned above is not valid anymore. The structure of the build folder is looking like this:

![screen shot 2016-03-22 at 09 36 18](https://cloud.githubusercontent.com/assets/2151639/13945962/bf555606-f011-11e5-9a8a-b99183374519.png)

The used command to upload will be:

```
aws s3 cp /path/mapbox-gl-native/platform/android/MapboxGLAndroidSDKTestApp/build/outputs/apk/MapboxGLAndroidSDKTestApp-release-unsigned.apk s3://mapbox-android-sdk/
```

And the downloadable link is:	
- https://s3-us-west-2.amazonaws.com/mapbox-android-sdk/MapboxGLAndroidSDKTestApp-release-unsigned.apk

**Comment by tobrun** [comment]
Game plan related to `MainActivity`:

The MainActivity should never be touched when adding a new FeatureActivity. 
It will generate a list from the `AndroidManifest.xml`:

```xml
        <activity
            android:name=".activity.MapboxMapActivity"
            android:description="@string/description_mapboxmap"
            android:label="@string/activity_mapboxmap">
            <meta-data
                android:name="category"
                android:value="other" />
        </activity>
```

 - Label will be used a the first line in the list item
   - if missing Class.getSimpleName() will be used
 - Description will be used as second line in the list item
   - if missing "-" will be shown
 - Category will be used as header 
   - Items will be sorted by categories
   - If missing category other will be used

**Comment by tobrun** [comment]
First iteration of the list has landed in #4428

**Comment by tobrun** [comment]
Will have to wait with SNAPSHOT build to publish artefact on s3, our SNAPSHOT is currently being build with the release branch for `4.0.0` and not master. I'm now going to focus on the feature activities. I'm going to follow these steps:

- [ ] optimise the usage of early initialisation through xml attrs or MapboxMapOptions
- [ ] merge some examples together
- [ ] remove obsolete examples
- [ ] make some examples more smart
- [ ] cleanup resources

**Comment by tobrun** [comment]
I'm back at this, going to merge some examples together, remove obsolete ones and make some examples a bit smarter.

**Comment by tobrun** [comment]
- [ ] API
- [ ] Markers
- [ ] Camera
- [ ] InfoWindow
- [ ] Other

**Comment by tobrun** [comment]
Activities are updated, I created 2 follow up issues, going to finish this issue

**Comment by tobrun** [comment]
Now that SNAPSHOTS are build from master again we can test out our AWS s3 file sharing setup.
My first tests shows that it's not working due access policies. 

> upload failed: platform/android/MapboxGLAndroidSDKTestApp/build/outputs/apk/MapboxGLAndroidSDKTestApp-release-unsigned.apk to s3://mapbox-android-sdk/MapboxGLAndroidSDKTestApp-release-unsigned.apk
A client error (AccessDenied) occurred when calling the CreateMultipartUpload operation: Access Denied


I tested the script locally and it worked. I'm guessing there will be a difference between my AWS-cli user versus the one used by Bitrise. I will have to ping someone with some to help me resolve this.

**Comment by tobrun** [comment]
Did some extra cleanup, we need to update some Activities with some better ui controls. (eg. ManualZoomActivity) to close this issue.

**Comment by bleege** [comment]
Rebased and Merged!  Great job @tobrun!  :rocket:
