### ISSUE TITLE
Multi problems when do things while map is still loading

### ISSUE THREAD

**Issue by KaiWangCanada** [mapbox/mapbox-gl-native#4367]
Android, version 3.2.0

I am working with a long json style, which takes 1~2 seconds to load the map.

when move the map before it is fully loaded, will black screen.

when display infowindow with selectMarker, inforwindow of the marker will freeze to that position.

both works fine if I do them after the map fully loaded.

if we have FinishedLoading listener, these might be easy to solve.

**Comment by cammace** [comment]
Hey thanks for reaching out, the Android SDK 4.0.0 has resolved this issue which you can read about in this [pull request](https://github.com/mapbox/mapbox-gl-native/pull/4169). Checkout [this guide](https://www.mapbox.com/android-sdk/#gradle) on updating to the 4.0.0 beta. You can get the callback by using `MapView.getMapAsync` were you will be able to begin interacting with the map by placing markers, moving the camera, etc. 
Hope you check it out!
