### ISSUE TITLE
Style::onSpriteError is apparently sometimes called with a null exception_ptr

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#4369]
`Style::onSpriteError`, and probably other `on*Error` methods, are apparently sometimes called with a null `std::exception_ptr`. This conclusion is based primarily on the fact that adding a guard clause for this solved the crash in #4330.

We expect `on*Error` methods to be called only when there is a legitimate error to report, so something is off here and needs to be investigated.

This may also be the root cause of the mysterious crashes reported in #3280. (If so, it would be a relief to know that the cause isn't related to RTTI.)

**Comment by jfirebaugh** [comment]
I'm not seeing how this is possible. Either `std::make_exception_ptr` would have to return a null `std::exception_ptr`, or `std::current_exception()` would, when called inside a `catch` block.

**Comment by jfirebaugh** [comment]
Some log output from when this occurs, from https://github.com/mapbox/mapbox-gl-native/issues/4382#issuecomment-199682258:

```
W/com.mapbox.mapboxsdk.http.HTTPRequest(14356): [HTTP] Request could not be executed: Failed to connect to /192.168.0.4:8080
W/com.mapbox.mapboxsdk.http.HTTPRequest(14356): [HTTP] Request could not be executed: Failed to connect to /192.168.0.4:8080
E/mbgl    (14356): {Map}[Setup]: loading style failed: Failed to connect to /192.168.0.4:8080
E/mbgl    (14356): {Map}[Style]: Failed to load sprite: (null)
E/mbgl    (14356): {Map}[Style]: Failed to load sprite: (null)
```

**Comment by brunoabinader** [comment]
I grabbed a similar situation while running the Android test app via simulator. Unfortunately I can't reproduce the issue anymore after upgrading my Android Studio, but I was using a x86 build running on a x86_64 simulator environment - `Nexus 4 API 22 (Android 5.1.1)`. I got the following output when trying to open any of the activities from the test app:
```
com.mapbox.mapboxsdk.testapp A/libc: ../../include/mbgl/util/string.hpp:38: std::string mbgl::util::toString(std::exception_ptr): assertion "error" failed
com.mapbox.mapboxsdk.testapp A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 3038 ()
```
