### ISSUE TITLE
Drop node 5 from build matrix

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#4370]
Node 5 is currently intermittently failing CI builds because of bugs in npm 3.

In my experience, npm 3 is slower and buggier than npm 2; I've returned to node 4 and npm 2 for local development. There's apparently no way to use node 5 + npm 2, and to my knowledge we're not actively needing support for node 5 -- can we drop it from the build matrix?

cc @mikemorris

**Comment by mikemorris** [comment]
We don't currently need support for Node 5, so I'd be alright dropping it from CI builds, but [according to the release schedule](https://github.com/nodejs/LTS), Node 6 is due out next month as the next LTS release.
