### ISSUE TITLE
Storing offline.db in user caches directory bad idea on OS X

### ISSUE THREAD

**Issue by postmechanical** [mapbox/mapbox-gl-native#4371]
The caches directory may get purged by the system at any time. It is not hard to imagine a case where a user is offline, depending on their offline map regions, and fills up their device in some other way (e.g., taking a lot of photos). In such a case the system could and would purge the user cache directory and remove the Mapbox SDK's offline db.

See: https://github.com/mapbox/mapbox-gl-native/blob/1ee7264b0edf6601a8170a30c40af4282679f495/platform/darwin/src/MGLOfflineStorage.mm#L33-L34

**Comment by 1ec5** [comment]
The code linked above places the offline.db file inside the Documents directory, not the Caches directory. MGLMapView [does place the cache.db file inside the Caches directory](https://github.com/mapbox/mapbox-gl-native/blob/1ee7264b0edf6601a8170a30c40af4282679f495/platform/ios/src/MGLMapView.mm#L309), but that file is used for ambient caching and can be regenerated cheaply.

In #4362, @jfirebaugh pointed out that both files should be unified, which probably means the unified cache would go in the Documents directory. Unfortunately this means that an application that doesn’t use offline packs will nonetheless have a cache.db file hanging around in its documents list in iTunes. But we are currently avoiding using the Caches directory for offline downloads and will continue to avoid it for the reason you point out.

**Comment by 1ec5** [comment]
However, [this code](https://github.com/mapbox/mapbox-gl-native/blob/1ee7264b0edf6601a8170a30c40af4282679f495/platform/darwin/src/MGLOfflineStorage.mm#L36-L48) does store the offline cache in the Caches directory on OS X. Although OS X isn’t nearly as aggressive as iOS in purging the Caches directory, we should be putting the OS X offline cache in Application Support, not Caches.

**Comment by 1ec5** [comment]
Closing in favor of #4362.

**Comment by postmechanical** [comment]
@1ec5 Thanks! Sorry for misreading the linked lines of code. I saw the OS X lines and :boom:.
