### ISSUE TITLE
[core] Implement mbgl::Projection::angleForLatLng

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#4373]
This function takes a `LatLng`, and returns the bearing (in degrees) of a distant object relative to the current course.

Example: Camera is set to a position in SFO, but wants the map bearing set to LAX destination before calling `flyTo`.

/cc @mapbox/gl

**Comment by 1ec5** [comment]
I think this function would be a lot more useful outside of `mbgl::Transform`, perhaps in `mbgl::Projection`, and generalized as a function that computes the bearing from one coordinate to another.

**Comment by 1ec5** [comment]
For example, the iOS SDK’s MGLMapCamera class implements an initializer, [`+[MGLMapCamera cameraLookingAtCenterCoordinate:fromEyeCoordinate:eyeAltitude:]`](https://github.com/mapbox/mapbox-gl-native/blob/cd1a06c2dc209da81b3d745c088e568b3b14809f/platform/darwin/src/MGLMapCamera.mm#L17) that would let you create a camera located at SFO that faces LAX. If all you care about is the bearing, you could get that with the `heading` property.

**Comment by brunoabinader** [comment]
Agreed @1ec5 - thanks!
