### ISSUE TITLE
Add API to clear ambient cache

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#4376]
As of #4376, all cached resources are located in a file in Application Support instead of Caches, so any disk space taken up by ambient caching cannot be automatically reclaimed by iOS when disk space runs low. These resources are only removed when the application is deleted. This would become more of a problem if the application is permitted to raise the ambient cache size (#3437).

Perhaps MGLOfflineStorage should have a method that clears the ambient cache contents in the unified cache file, leaving any downloaded offline content intact. The application could provide UI for reclaiming the space taken up by ambient caching.

/cc @jfirebaugh

**Comment by zugaldia** [comment]
Adding the `android` tag as the current situation affects Android similarly.

**Comment by tsemerad** [comment]
Is there still no way to clear the ambient cache, other than reinstalling the app? I'm finding that when I update a tileset, my iOS client is still holding onto the previous tiles. Previously-cached tiles still show the old data, but fetching new tiles show the new data.

**Comment by 1ec5** [comment]
Is this tile set hosted by Mapbox or by you? If you’re hosting your own tile set, you can set a caching header in the HTTP response to force regular refreshes: https://github.com/mapbox/mapbox-gl-native/issues/4446#issuecomment-200583990.

**Comment by 1ec5** [comment]
Is this tile set hosted by Mapbox or by you? If you’re hosting your own tile set, you can set a caching header in the HTTP response to force regular refreshes: https://github.com/mapbox/mapbox-gl-native/issues/4446#issuecomment-200583990.

**Comment by tsemerad** [comment]
It's hosted on Mapbox. Do you know what `Cache-Control: max-age` header Mapbox serves the tiles with?

Hosting the tiles myself wouldn't be ideal, but I can do so if necessary. But doesn't the new offline caching functionality (where you set a region) require that the tiles be hosted by Mapbox? Maybe I'm misremembering.

**Comment by zugaldia** [comment]
Just noting that, on Android, this is something that can easily be implemented by the developer today. For reference, we currently have a private method [`deleteAmbientDatabase`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineManager.java#L168-L185) that deletes the database that we used to use before offline landed. (This method name needs to be clarified once this new API is introduced.)

To delete the current database, the developer would use similar code. The path could be obtained from ` OfflineManager.getDatabasePath()` and the filename from ` OfflineManager.DATABASE_NAME`.

In any case, I like the idea of adding a specific API in the SDK.

**Comment by 1ec5** [comment]
Similarly, on iOS and macOS, it’s possible to delete the database (which contains all cached content, including downloaded offline packs) by pointing NSFileManager to [this path](https://github.com/mapbox/mapbox-gl-native/blob/234f6caf7c1e6435f4ad96a8773575a8aad2aa8f/platform/darwin/src/MGLOfflineStorage.mm#L51). But the location of that file may change in a future release without notice, it’s probably only safe to touch this file before you use MGLMapView or MGLOfflineStorage in any way, and we don’t make any promises about how well this workaround would work even today. I’d expect the same caveats to apply to the Android SDK. So I’m pretty sure deleting the database isn’t an option for the use case described in https://github.com/mapbox/mapbox-gl-native/issues/4376#issuecomment-245083388.

**Comment by RomainQuidet** [comment]
Hi,
Any news about when this feature will be added ? which milestone ?
Thanks.

**Comment by Superfuture** [comment]
Hi, any ETA on when this will be fixed? Thanks!

**Comment by haydenkaizeta** [comment]
Android ETA?

**Comment by rinigus** [comment]
If such API will be developed, would be great to get it for Qt as well.

**Comment by masterjefferson** [comment]
+1 We'd love to have this feature.

**Comment by kkaefer** [comment]
PR is in https://github.com/mapbox/mapbox-gl-native/pull/14365

**Comment by brunoabinader** [comment]
Worth noticing that #14365 resets the entire database, including ambient cache and offline regions. As per discussions with @kkaefer, we should be able to clear ambient cache independently from offline regions via SQL queries.
