### ISSUE TITLE
[android] upgrade to 4.0.0 beta.1 problems

### ISSUE THREAD

**Issue by KaiWangCanada** [mapbox/mapbox-gl-native#4380]
After upgrading, example here doesn't work: https://www.mapbox.com/android-sdk/examples/

can't import: 
import com.mapbox.mapboxsdk.views.MapView;

when import this instead,
import com.mapbox.mapboxsdk.maps.MapView;
these lines are not working:
        mapView.setCenterCoordinate(new LatLng(40.73581, -73.99155));
        mapView.setZoomLevel(11);

**Comment by tobrun** [comment]
@KaiWangCanada 
We are currently updating our examples to match the new API. 
Sorry for net getting these up there faster.

**Comment by tobrun** [comment]
Some tips already for:

```java
mapView.setCenterCoordinate(new LatLng(40.73581, -73.99155));
mapView.setZoomLevel(11);
```

All these interactions have been replaced with our new [Camera API](https://www.mapbox.com/android-sdk/api/4.0.0-beta.1/).

You should be able to use:

```java
 mapboxMap.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(40.73581, -73.99155), 11));

// or

 mapboxMap.animateCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(40.73581, -73.99155), 11));

//or

 mapboxMap.easeCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(40.73581, -73.99155), 11));


```

**Comment by KaiWangCanada** [comment]
That's OK :) Really glad to have the new version on board.
