### ISSUE TITLE
OfflineManager and MapView should share a singleton DefaultFileSource

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#4386]
As of #4383, all instances of `mbgl::DefaultFileSource` in the Android SDK are backed by the same file on disk. Per #4362, the singleton `OfflineManager` and all `mbgl::View` instances managed by `MapView`s should ideally share the same instance of `mbgl::DefaultFileSource`, so that the 20-connection throttle can be applied to the whole process instead of on a map-by-map basis.

In the iOS and OS X SDKs, in #4377, we made the singleton MGLOfflineStorage object responsible for the singleton `mbgl::DefaultFileSource` instance. Thus MGLMapView depends on MGLOfflineStorage (as ambient caching is just a special case of offline caching), but not the other way around.

/cc @zugaldia @jfirebaugh

**Comment by tobrun** [comment]
This landed as part of https://github.com/mapbox/mapbox-gl-native/pull/8083
