### ISSUE TITLE
ViewSettings default values when creating MapView programatically

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4398]
When creating a MapView programatically as:

>  new MapView(context, options)

The attribution icon, mapbox logo and compassview are not correctly positioned in their default location.

![device-2016-03-19-215152](https://cloud.githubusercontent.com/assets/2151639/13901223/e3740dda-ee1c-11e5-86fc-e760b3b88d75.png)

**Comment by tobrun** [comment]
Now double checking MapFragment/SupportMapFragment, It's an issue for this as well. 
Because of this I'm proposing adding this to the `4.0.0` milestone.

@bleege @zugaldia

**Comment by tobrun** [comment]
![device-2016-03-23-101245](https://cloud.githubusercontent.com/assets/2151639/13980623/ef62fdc0-f0df-11e5-9569-9aebf60617e1.png)

**Comment by jfirebaugh** [comment]
Looks like this was fixed. Good to close?

**Comment by bleege** [comment]
LGTM.  Good catch @jfirebaugh!
