### ISSUE TITLE
API to retrieve screen position of markers.

### ISSUE THREAD

**Issue by dagatsoin** [mapbox/mapbox-gl-native#4399]
Related: https://github.com/mapbox/mapbox-gl-native/issues/3116.
I have a scenario where a single wkwebview (or crosswalk) view would track Mapbox dummies markers (maybe 100 max). It is for a RPG game.

My goal is to separate the heavy computing (sprites, collision, particules, etc.) for characters and monsters from the map background.

I think that the only thing I need is an API which exposes the screen position of the MB dummies markers. Is there such API?
cc @incanus

**Comment by tobrun** [comment]
@dagatsoin that is a cool use-case. Would love to see the end result.

>  API which exposes the screen position of the MB dummies markers

Currently our markers don't expose screen position as an attribute but a LatLng.
We support a conversion method in `map.cpp` that will return the screen position:
 
```cpp
PrecisionPoint Map::pixelForLatLng(const LatLng& latLng) const {
    return transform->latLngToPoint(latLng);
}
```

The mentioned method is found in our core, but you are probably looking for a method found in one of our bindings (Android, iOS, OSX,..). Could you mention the binding you are using?

**Comment by friedbunny** [comment]
Screen position ↔ map coordinate conversion functions are available in iOS — you’ll probably want [`-convertCoordinate:toPointToView:`](https://www.mapbox.com/ios-sdk/api/3.1.2/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)convertCoordinate:toPointToView:).

Here’s an [interactive example](https://www.mapbox.com/ios-sdk/examples/point-conversion/) of how to do point/coordinate conversion.

**Comment by UmairKhalid786** [comment]
Is there any way to do so in Android SDK ?

**Comment by tobrun** [comment]
@UmairKhalid786 You can use `Projection#toScreenLocation` and `Projection#fromScreenLocation` to convert LatLng into pixels on screen or reversed.
