### ISSUE TITLE
Slow animation for markers

### ISSUE THREAD

**Issue by leye0** [mapbox/mapbox-gl-native#4401]
I've spent the last couple of days analyzing the java and native code to find a way to improve the performance when an Annotation position changes (I'm in a context where around 10 to 15 annotations are moving, think about an usage similar to Uber), without any success. I previously had GoogleMap, which was incredibly fast with 20+ annotations (probably more than 30 fps), and currently, having more than 1 or 2 animated pins in our respectably big application results in pins flickering a lot. 

I've tried different approaches, like relying on timers, ObjectAnimator, ValueAnimator, checked to just linearly modify the value in a loop in another thread, and I always got the same bad performances when animating 10-15 pins.

Do you plan to add native animation functionalities or some optimizations?

Thanks,
Leon

**Comment by tobrun** [comment]
@leye0 Thank you for reaching out and reporting your problem. We aware that current setup isn't performant, note that we just recently allowed changing the position of the marker dynamically in b3953029909cbb6d4d8cc48fc95acf71523f941b and need to iterate on the implementation details to make it work in the way you are currently requesting. I created https://github.com/mapbox/mapbox-gl-native/issues/4402 as a feature request that should make this solution workable.

Another approach would be to implement a View Marker API as mentioned in #3276, at this point it's unsure if this solution would scale as requested above.
