### ISSUE TITLE
Animated annotations

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4402]
##### Background info
The possibility to change a marker LatLng landed in master with d742c2d3eb3b8f669f0df9c6e5f6596eaf8fb616. A typical use-case users have been reporting is having a ride sharing app that shows cars driving around on the map. I tried implementing this on the java side using Android SDK animations ([code](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/AnimatedMarkerActivity.java#L51)). This works for 1-2 markers but is not performant. Each [animation update](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/AnimatedMarkerActivity.java#L61) will set a new position to the Marker and will have to go through JNI to update it. Without analysing it with some tools, I'm guessing that the overhead associated with JNI is causing the performance problem.

##### Feature request
Suggested solution is to allow having a moveToLatLng method on PointAnnotation in core. This will calculate and update an annotation position until it reaches the destination. From binding perspective we just pass of the information to core and core handles updating the position.

##### Other approaches
Note that we have been thinking about other approaches to this problem. Until now we have always  indicated that animations is something that should be done through the native animation framework of the bindings using the native views from that binding. This approach is ticketed in for Android in #3276. This would also use jni in the process and will probably not scale very well. This approach could benefit from #4384 that would limit the round tripping currently needed.

**Comment by leye0** [comment]
Do you know (how can I see) if this feature has been associated with an upcoming version? 

And out of curiosity, is there already something like an interpolation timer or an animation API in the native part of the Mapbox?

**Comment by leye0** [comment]
@tobrun

**Comment by tobrun** [comment]
@leye0 
Currently this is not on our GL core roadmap. 
I just added this feature request since I feel this would make a useful feature.

**Comment by leye0** [comment]
Thanks!

**Comment by jfirebaugh** [comment]
Core now has `Map#updateAnnotation`, which allows any property of any annotation type to be updated. We should implement animations at the SDK level using `Map#updateAnnotation` as the primitive, and see what performance is like.

**Comment by tobrun** [comment]
@jfirebaugh we are running with this approach in https://github.com/mapbox/mapbox-gl-native/issues/5299. Next steps is to profile and see why `updateAnnotation` are slow for us. Another approach to solving this is into animating the ViewMarker as an overlay using Android SDK animations and only cal updateAnnotation when we end the animation.

**Comment by jfirebaugh** [comment]
We optimized annotation animation in #5385.
