### ISSUE TITLE
Implement pulsing effect for annotations.

### ISSUE THREAD

**Issue by dmitrysavin** [mapbox/mapbox-gl-native#4404]
Hi,

is there way to implement pulsing animation for annotations, like this:
https://github.com/TransitApp/SVPulsingAnnotationView

As I see currently I can only set icon for annotation.
If you have in plans have updated with this functionality, could you share how long to wait for it?
As I'm currently looking for solution for this implementation.

**Comment by 1ec5** [comment]
It isn't clear which SDK (Android, iOS, OS X) you're using, but the iOS SDK currently only represents the user location annotation as a native UIView. (It has a pulsing effect built in.) #1784 tracks adding an API for any annotation to be backed by a UIView, which would allow you to adopt an approach similar to SVPulsingAnnotationView for your own annotations.

**Comment by dmitrysavin** [comment]
I need pulsing animation for Android maps.
