### ISSUE TITLE
Ambient caching disabled when the database contains 50 MB+ of offline resources

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#4411]
Once an offline database contains 50 MB or more of offline resources, it effectively no longer permits any ambient caching. Any attempt to add an ambiently-cached resource to the database will evict any existing ambiently-cached resources, fail to get the database below 50 MB, and log the error "Unable to make space for entry".

The 50 MB limit should be treated as the size limit for ambiently-cached resources only, not as a size limit on the complete database.

**Comment by RomainQuidet** [comment]
Confirmed, seeing a lot of logs
2016-04-04 11:45:17.778 Mapbox GL[6813:244371] [WARNING] {DefaultFileSource}[Database]: Unable to make space for entry

When the 50MB limit is reached, I have the feeling that the map lags a lot, showing new tiles is really slow.

**Comment by halset** [comment]
Is this to expensive to run instead of the pragma trick?
```
sqlite> select coalesce(sum(length(data)),0) from tiles where id not in (select tile_id from region_tiles);
0
Run Time: real 0.013 user 0.005565 sys 0.004869
```

**Comment by tmpsantos** [comment]
> The 50 MB limit should be treated as the size limit for ambiently-cached resources only, not as a size limit on the complete database.

Unless we split this into two different databases, I see this as a feature not as a bug. Otherwise we would have to calculate "offline size + ambient size" to make sure it fits into the space you want to reserve for caching.

It is convenient to download a 600 MB offline data and set the total size to 1 GB and forget about it. The current implementation will make sure we stay within limits.

**Comment by jfirebaugh** [comment]
I think the behavior most end user / developers would expect is:

* Use up to X MB of space for ambiently cached data.
* Store all the requested offline regions, without limit.

That's not possible right now.

**Comment by halset** [comment]
@tmpsantos you wrote "It is convenient to download a 600 MB offline data and set the total size to 1 GB and forget about it". Is there an API to set a custom max cache size from the iOS API?

**Comment by friedbunny** [comment]
@halset Nope, maximum cache size is current defined as [a constant in mbgl](https://github.com/mapbox/mapbox-gl-native/blob/eb1b385e50f783e33bb500693977f7bf45f4126e/include/mbgl/util/constants.hpp#L39).

**Comment by halset** [comment]
@friedbunny thanks.

Trying to figure out the best way to fix this for mye users with more than 50MB of offline data. 

A more correct way to calculate the ambient cache size will lead to a more expensive evict. And that will lead too slower put for non-regional tiles/resources.

Would it be possible to run the evict on a different thread and not that often? Or perhaps not at all? Perhaps there could be a separate mode where the application developer takes the responsibility to call clean up the ambient cache? Either by number of MB or by deleting old tiles.

**Comment by ericrwolfe** [comment]
Is there an advantage to running `evict()` on every `put`? 

I'm thinking we could run evict less frequently with a more accurate (and slightly more expensive) size query e.g. https://github.com/mapbox/mapbox-gl-native/issues/4411#issuecomment-225344654. We could call evict, say, every 100th call to `put` (or, more likely, randomly on 1% of calls to `put`).

**Comment by jfirebaugh** [comment]
If it's a question constant time factors, that would be fine. What I want to avoid is making the eviction algorithm linear (or worse) in the size of the tiles/resources tables. Those tables can get big, a linear factor alone is problematic, and eviction can easily compose with operations that do a lot of `put`s to go exponential.

**Comment by ericrwolfe** [comment]
By limiting the query to only those resources in the ambient cache and not in the offline regions as is hinted at in https://github.com/mapbox/mapbox-gl-native/issues/4411#issuecomment-225344654, the query time will never really grow beyond what's performed on a full 50mb cache (~1000 resources).

**Comment by jfirebaugh** [comment]
I think those queries would have to do a table scan on either `tiles` or `region_tiles` -- that's the linear factor I'm referring to.

**Comment by ericrwolfe** [comment]
Ah yes, you're right. I can't think of a solution that avoids a full table scan without storing size statistics in a separate metadata table.

Nonetheless, as it's currently implemented, once a single offline region is stored and the 50mb database size limit is exceeded, the inner while loop inside of evict is called _every single time_ and a full table scans effectively happens anyway as resources are deleted. 

Until we can come up with a better solution, an occasional full table scan via a reduced evict rate would still be orders of magnitude better than what's happening currently.

**Comment by halset** [comment]
I would prefer the ability for the developer to implement a evict policy. In my hugely offline app, I use a branch with an empty evict method. That could be the no-evict strategy.

**Comment by guyinn** [comment]
Any update on this issue?

**Comment by halset** [comment]
@rolandpeelen Hello. I am in a similar situation. I work around the problem by not doing any evicting at all. That works fine for my app. https://github.com/halset/mapbox-gl-native/commit/dbe4786d2b416b82577e05b5058b534e280baab9

**Comment by DhbStudy** [comment]
For mapbox maps, downloading works and can store more than 50MB data.
For third-party style maps, it can only store 50MB data. 

Do I have to fork it and change the DEFAULT_MAX_CACHE_SIZE?
How the mapbox style break through the limit, a parameter within a flat file?

**Comment by natalia-osa** [comment]
Hi, I also am facing this issue. I get a lot of these logs with each scroll using iOS API (around 10 per second). Happens only during scrolling. The app also crashes eventually after some scrolling, I'm now checking if that's connected with this console output or that's not related.
