### ISSUE TITLE
MGLOfflinePack suspend has no effect in `mapbox-ios-sdk-3.2.0-beta.2`

### ISSUE THREAD

**Issue by postmechanical** [mapbox/mapbox-gl-native#4418]

**Comment by jfirebaugh** [comment]
Can you please provide a more detailed description for the issue? What did you do, what did you expect to happen, what happened instead?

**Comment by postmechanical** [comment]
@jfirebaugh `[someOfflinePack suspend]` was working in `3.2.0-beta.1` but not in `3.2.0-beta.2`. I've verified this by setting a break point in the delegate method `- (void)offlinePack:(MGLOfflinePack *)pack progressDidChange:(MGLOfflinePackProgress)progress` which continues to be called.

**Comment by jfirebaugh** [comment]
What you are observing may be an expected consequence of the asynchronous nature of offline downloads. The download is conducted on a background thread, and the cross-thread messaging can result in a delay between the call to `[someOfflinePack suspend]`, the suspend message getting delivered to the background thread, and the acknowledgement and final status notification getting sent back to the main thread. The pack's `state` tracks the _acknowledged_ state of the download, i.e. the state last reported from the background download thread.

There's more discussion of this in #4229.

**Comment by postmechanical** [comment]
@jfirebaugh The `suspend` has no effect in the sense that the download never, even eventually, stops. The offline pack continues until the download is completed.

**Comment by 1ec5** [comment]
Has this pack previously been downloaded to completion? If you resume a complete pack, the download will start from 0 but pausing won’t stop until the pack has accounted for all the resources that have already been downloaded – that is, all the pack’s resources.

**Comment by postmechanical** [comment]
@1ec5 I don't recall unfortunately. I've paused working with the Mapbox SDK for now. I will try again once a stable 3.3.0 release is available.

**Comment by friedbunny** [comment]
Closing as stale, but please feel free to post more information as it becomes available.
