### ISSUE TITLE
NPE happens when closing fragment while map scrolling

### ISSUE THREAD

**Issue by vzenrhen** [mapbox/mapbox-gl-native#4424]
NPE happens when closing fragment while map scrolling
Version: 4.0.0.beta2
Android 6.0/Galaxy S7

> 03-22 15:03:01.914 24720-24720/lime.taxi.key.izh43 E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'double com.mapbox.mapboxsdk.maps.NativeMapView.getBearing()' on a null object reference
>                                                                          at com.mapbox.mapboxsdk.maps.MapView.getDirection(MapView.java:587)
>                                                                          at com.mapbox.mapboxsdk.maps.MapView$SurfaceTextureListener.onSurfaceTextureUpdated(MapView.java:1284)
>                                                                          at android.view.TextureView.applyUpdate(TextureView.java:443)
>                                                                          at android.view.TextureView.getHardwareLayer(TextureView.java:388)
>                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16441)
>                                                                          at android.view.View.draw(View.java:17238)
>                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
>                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
>                                                                          at android.view.View.draw(View.java:17472)
>                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16464)
>                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
>                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
>                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16424)
>                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
>                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
>                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16424)
>                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
>                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
>                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16424)
>                                                                          at android.view.View.draw(View.java:17238)
>                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
>                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
>                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16459)
>                                                                          at android.view.View.draw(View.java:17238)
>                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
>                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3735)
>                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16459)
>                                                                          at android.view.View.draw(View.java:17238)
>                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
>                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
>                                                                          at android.view.View.draw(View.java:17472)
>                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16464)
>                                                                          at android.view.View.draw(View.java:17238)
>                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
>                                                                          at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1369)
>                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
>                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16459)
>                                                                          at android.view.View.draw(View.java:17238)
>                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
>                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
>                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16459)
>                                                                          at android.view.View.draw(View.java:17238)
>                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
>                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
>                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16459)
>                                                                          at android.view.View.draw(View.java:17238)
>                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
>                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
>                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16459)
>                                                                          at android.view.View.draw(View.java:17238)
>                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
>                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
>                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16459)
>                                                                          at android.view.View.draw(View.java:17238)
>                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
>                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
>                                                                          at android.view.View.draw(View.java:17472)
>                                                                          at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:3205)
>                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16464)
>                                                                          at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
>                                                                          at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
>                                                                          at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
>                                                                      	at android.view.ViewRootImpl.draw(ViewRootImpl.java:

**Comment by tobrun** [comment]
@vzenrhen 
thank you for reaching out this is very valuable feedback.

**Comment by bleege** [comment]
Rebased and merged!  Thanks @vzenrhen!
