### ISSUE TITLE
 'The resource named “mapbox.png” could not be found in the Mapbox framework bundle.'

### ISSUE THREAD

**Issue by ultranano** [mapbox/mapbox-gl-native#4425]
On MapBox 3.2.0 device iPhone 6

```
*** First throw call stack:
(0x180a42e38 0x1800a7f80 0x180a42d80 0x10072b7b4 0x100719018 0x100718540 0x100212534 0x1002116b4 0x185b8ca6c 0x185b8c670 0x185c4cd50 0x185c4c000 0x185c4bba4 0x185c4b7cc 0x185c4b734 0x185b88010 0x18352eac0 0x1835296cc 0x18352958c 0x183528bbc 0x183528904 0x183521e70 0x1809f87b0 0x1809f6554 0x1809f6984 0x180920d10 0x182208088 0x185bf5e54 0x1001ddb10 0x1804be8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

Terminating app due to uncaught exception 'Resource not found', reason: 'The resource named “mapbox.png” could not be found in the Mapbox framework bundle.'
```

**Comment by 1ec5** [comment]
Did you install the SDK manually or using a package manager like CocoaPods or Fabric? If you installed it manually, are you using the dynamic framework or the static framework? Is Mapbox.framework listed in the “Embedded Binaries” section of the project editor, or just “Linked Frameworks and Libraries”?

**Comment by ultranano** [comment]
Hi @1ec5 manually - static framework
I can't find "Embedded Binaries" or "Linked Frameworks and Libraries"  in xCode 7.3

**Comment by ultranano** [comment]
Checked & found "Linked Frameworks and Libraries" on Targets (not on Project)
![screen shot 2016-03-22 at 18 19 18](https://cloud.githubusercontent.com/assets/4621104/13960967/bc140aa2-f05a-11e5-805c-a21f69f0eb3e.png)

Mapbox is present and required

**Comment by 1ec5** [comment]
Mapbox.framework needs to be added to the “Embedded Binaries” section just above this section. Please let us know if the issue persists after doing adding it there. Thanks!

**Comment by ultranano** [comment]
Hi @1ec5 if i put the Mapbox.framework into the “Embedded Binaries” section

![screen shot 2016-03-22 at 18 54 29](https://cloud.githubusercontent.com/assets/4621104/13962079/af38d2b8-f05f-11e5-9a20-30d2f350103d.png)

when i try to build & run my projects on device i receive this error

![screen shot 2016-03-22 at 18 55 02](https://cloud.githubusercontent.com/assets/4621104/13962091/c6adc5ac-f05f-11e5-8436-436b93218b9d.png)

if I remove the framework from “Embedded Binaries” section everything works fine.

**Comment by 1ec5** [comment]
This sounds like #3656.

**Comment by ultranano** [comment]
@1ec5 same problem with 3.1.3 :-(
1) if you don't add framework to embedeed binares > crash with “mapbox.png” could not be found in the Mapbox framework bundle
2) if you add framework to embedded binares you can't install on device due to signature problem

**Comment by 1ec5** [comment]
Followed up in https://github.com/mapbox/mapbox-gl-native/issues/3656#issuecomment-200282070.
