### ISSUE TITLE
Currently added marker's position

### ISSUE THREAD

**Issue by dgngulcan** [mapbox/mapbox-gl-native#4430]
Using Mapbox Android SDK 

I'm developing a tracker app, which requires to update the same marker indicates user's location?

Firstly, I've tried to update by `userMarker.position(mapData.latLngMapbox);` where userMarker is the marker I've given to map before but it did not workout. 

Secondly, removed marker and added new one but unfortunately it causes a flickering like situation.

How can I achieve this elegantly?
Thanks in advance

**Comment by tobrun** [comment]
@dgngulcan 
Thank you for reaching out.

It depends on which version of the SDK are you using. With `3.2.0` we did not support changing the position dynamically and you could only add/remove the marker. From `4.0.0` we are supporting the idea of dynamically updating a marker position. [Here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/DynamicMarkerChangeActivity.java) you can find some sample code to achieve this.

The `4.0.0` isn't fully released yet but we just did release the `beta2` version. 
Install instructions can be found [here](https://www.mapbox.com/android-sdk/#gradle).

Reach out if you have any other questions or you find any bugs!

**Comment by dgngulcan** [comment]
I am currently using SDK version 3.2.0, I'll move to 4.0.0 today then!
Thank you for fast and informative reply @tobrun.

I'll definitely reach out since we are moved on mapbox from google maps :)
