### ISSUE TITLE
Create Android Changelog

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#4432]
We've been [talking about breaking the all platform CHANGELOG.md up](https://github.com/mapbox/mapbox-gl-native/issues/3068) into platform specific CHANGELOG for awhile now.  Android 4.0.0 seems like a good time to start this practice.  Let's put it in /platform/android/CHANGELOG.md

/cc @mapbox/mobile @mapbox/support

**Comment by 1ec5** [comment]
Remember to add a link in CONTRIBUTING.md and also ensure that the iOS SDK’s package.sh script still extracts the right section for the What’s New section in the jazzy documentation.

**Comment by bleege** [comment]
I just split iOS and Android in #4466 and merged them into `release-ios-3.2.0-android-4.0.0` in #4466.  I saw @mikemorris's request for Node afterwards but will take care of that now in a new branch.

Please note though that any of these links won't be ready for use until `release-ios-3.2.0-android-4.0.0` is merged back into `master` after the final releases of Android 4.0.0 and iOS 3.2.0.

**Comment by bleege** [comment]
Node has now landed too.  We're officially all split now.  :+1:

**Comment by bleege** [comment]
@1ec5 reports a silent bug on the iOS side.

**Comment by 1ec5** [comment]
Filed as #4469.
