### ISSUE TITLE
getMapAsync() does not work when offline.

### ISSUE THREAD

**Issue by vfaSonnt** [mapbox/mapbox-gl-native#4438]
The function getMapAsync() doesn't work on Fragment and SupportFragment when turn off network.
On activity, it seem to work fine.
Please, have a look at this problem.

**Comment by tobrun** [comment]
Thank you for reaching out and reporting your problem.
 I'm also noticing this without turning off network. 
I already created an issue related to adding a MapView programatically. 
 Going to use #4439 in favour of this.

**Comment by vfaSonnt** [comment]
@tobrun I add SupportFragment progammatically, and it work fine with the network. I get the source from github and add log at getMapAsync() on example of FragmentActivity and SupportFragmentActivity. When network is on, it work OK. Turning network off, it can not show log.

**Comment by tobrun** [comment]
@vfaSonnt thank you clarifying that for me. Besides https://github.com/mapbox/mapbox-gl-native/issues/4393 there is already a https://github.com/mapbox/mapbox-gl-native/issues/4393 ticket open that should cover your use-case. You are using the `offline` functionality and downloaded a region locally?

**Comment by vfaSonnt** [comment]
No, I test on Mapbox Examples source code.

**Comment by tobrun** [comment]
@vfaSonnt 

I produced this clip with the `SupportMapFragmentActivity ` when I have no internet, IMHO this is working as designed. If there is not internet connection we are not able to load content. If I turn on my WiFi and I have a new connection it downloads the content and calls the onMapReady callback.

Please elaborate what you expect it should do, I'm open to suggestions. 

https://www.dropbox.com/s/o39dw9s6vhmwehh/device-2016-03-24-102121.mp4?dl=0

**Comment by vfaSonnt** [comment]
@tobrun 
Thank you for your support.
Sorry ,my bad. It seem to happen only on Android OS < 5.0. 
I test on Galaxy S4, OS 4.4.2, this bug will appear.
I test on Nexus5, android OS 5.0. It is OK in this case but if you restart app again, it happen.
I found this bug will appear in 2 cases:
- Android OS <5.0, do steps like your video, it not animate.
- Android OS above 5.0, do steps like your video, then exit app completely, open it again. It not animate.

**Comment by vfaSonnt** [comment]
Sometime, it happen on OS5.0 too.  
https://drive.google.com/file/d/0B6QuWvSOy6oYVDVpMlpodC1Hazg/view?usp=sharing

**Comment by Fintasys** [comment]
Is this issue resolved? I still got this problem with MapBox 4.0.0 Android SDK
Testet on Samsung Galaxy A3 Android 5.1.1.
