### ISSUE TITLE
AnnotationManager::getPointAnnotationsInBounds() should map IDs to screen coordinates

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#4443]
For view-based annnotations (#1784 and #3276) to be performant, especially on Android, `AnnotationManager::getPointAnnotationsInBounds()` needs to supply the screen coordinates of each annotation whose ID it returns. That way we can call `getPointAnnotationsInBounds()` on each region change and avoid a potentially expensive series of calls to `Map::pixelForLatLng()` for each annotation in the returned list of annotations.

/cc @tobrun

**Comment by 1ec5** [comment]
This API would also greatly improve performance in the OS X SDK when any annotation supplies a tooltip or cursor, since we need to [update tooltip and cursor rects](https://github.com/mapbox/mapbox-gl-native/blob/f854368f2906f89caa55cad150f3d86409ef9c0a/platform/osx/src/MGLMapView.mm#L2068) on each region change, just like we intend to do for view-based annotations.

**Comment by jfirebaugh** [comment]
Any implementation of this would likely just call `Map::pixelForLatLng()` for each annotation itself. Is there reason to believe this would be faster than having the SDK call it?

**Comment by 1ec5** [comment]
This ticket has a big question mark on it because I filed it proacively before there were view-backed annotations to profile. @boundsj @tobrun, are you seeing this as a bottleneck currently? If not, we can close and move on.

**Comment by boundsj** [comment]
@1ec5 @jfirebaugh the implementation in https://github.com/mapbox/mapbox-gl-native/pull/4801 only uses `getPointAnnotationsInBounds` to hit test visible annotation views at a touch point. If I select annotations over and over again for 30 seconds, `getPointAnnotationsInBounds` does not even register in the time profiler. For the same user activity, on the other end of the spectrum is `SMCalloutView:presentCalloutFromRect:inLayer:ofView: constrainedToLayer:animated` at about 30% and most of that is is a transparent image mask operation in a CALayer.

For testing if a view is in the viewport [we currently use CGRectContainsRect](https://github.com/mapbox/mapbox-gl-native/pull/4801/commits/fb759e8475906aa6ff6c8aa035446d801216beaf) and avoid `getPointAnnotationsInBounds` entirely. The expensive parts of this approach are currently:

- `MGLAnnotationView:setCenter`: 27%
- `_mbglMap->getCameraOptions(padding)`: 17.2%
- `_mbglMap->pixelForLatLng(latLng)` (via `MGLMapView:convertLatLng:toPointToView`): 13.3%

**Comment by jfirebaugh** [comment]
It sounds like the current implementation of `getPointAnnotationsInBounds` is not a bottleneck, so closing here.
