### ISSUE TITLE
zoom - Inconsistent variable type (double vs float)

### ISSUE THREAD

**Issue by dariav** [mapbox/mapbox-gl-native#4445]
Looking at Mapbox SDK seems like zoom variable type is not consistent and that's causing me issues.

If I am to retrieve zoom level I would do:

```
double zoomLevel = mapboxMap.getCameraPosition().zoom;
```

If I want to change zoom level I would do:

```
 mapboxMap.animateCamera(CameraUpdateFactory.zoomTo(zoomLevel));
```

However, latter will result with an exception because `CameraUpdateFactory.zoomTo` expects `float`

Looking at google documentation, I see that getCameraPosition actually holds `zoom` as `float`.
https://developers.google.com/android/reference/com/google/android/gms/maps/model/CameraPosition#field-summary

Now, there might be pretty good reason for us changing this in Mapbox SDK and I would love to hear it, I just wasn't able to find the answer anywhere.

**Comment by tobrun** [comment]
Our old system was build on doubles, the newer Camera API that mimics Google started with float and we are granularly trying to move back to double.
