### ISSUE TITLE
How to get blue dot always in center of screen?

### ISSUE THREAD

**Issue by sirvon** [mapbox/mapbox-gl-native#4449]
How to get blue dot always in center of screen?

**Comment by 1ec5** [comment]
Which platform is this for?

* For the Mapbox Android SDK, see [`MapboxMap.getTrackingSettings()`](https://www.mapbox.com/android-sdk/api/4.0.0-beta.2/com/mapbox/mapboxsdk/maps/MapboxMap.html#getTrackingSettings()) and [`TrackingSettings.setMyLocationTrackingMode()`](https://www.mapbox.com/android-sdk/api/4.0.0-beta.2/com/mapbox/mapboxsdk/maps/TrackingSettings.html#setMyLocationTrackingMode(int)).
* In the Mapbox iOS SDK, you’d set MGLMapView’s [`userTrackingMode`](https://www.mapbox.com/ios-sdk/api/3.1.2/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)userTrackingMode) property.
* The Mapbox OS X SDK doesn’t currently support showing the user’s location as a blue dot on the map.

**Comment by aroldanju** [comment]
Where is TrackingSetings now? I can't find it.
