### ISSUE TITLE
How to import Mapbox-GL-native to Android Studio?

### ISSUE THREAD

**Issue by zhangzhuowh** [mapbox/mapbox-gl-native#4452]
I want to import [mapbox-gl-native Android SDK](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android) to Android Studio.

- if I direct import this project, it doesn't work. 

- If I use `make android` command in Ubuntu, it generate a `.so' file, but I can't do anything about C++ files.
[![enter image description here][1]][1]
**I want have C++ files in project after import to Android Stuido, like this:**
[![enter image description here][2]][2]

**How can I do that?**

  [1]: http://i.stack.imgur.com/FCoCo.png
  [2]: http://i.stack.imgur.com/2fFzV.png

**Comment by zhangzhuowh** [comment]
Is t use `GYP`?

**Comment by tobrun** [comment]
@zhangzhuowh 
Thank you for reaching out, yes we use GYP to generate our projects for multiple platforms.
Installation instructions to build from source can be found [here](https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md).  

**Note** just want to use our library without building from source (see [here](https://www.mapbox.com/android-sdk/#gradle).
