### ISSUE TITLE
addOnMapChangedListener() with SupportMapFragment

### ISSUE THREAD

**Issue by vfaSonnt** [mapbox/mapbox-gl-native#4453]
Method addOnMapChangedListener() is only exist on MapView.
How can I use this with MapFragment? Or how can I get the MapView in MapFragment?

**Comment by tobrun** [comment]
@vfaSonnt 
Thank you for reaching out. There is a method called:

```java
    /**
     * Sets a callback object which will be triggered when the MapboxMap instance is ready to be used.
     *
     * @param onMapReadyCallback The callback to be invoked.
     */
    public void getMapAsync(@NonNull final OnMapReadyCallback onMapReadyCallback) {
        mOnMapReadyCallback = onMapReadyCallback;
    }
```
You can use this to get a reference to  `MapboxMap`. From the `4.0.0` release user will no longer interact with the MapView directly, but with the `MapboxMap`. Look at this as a separation of concerns, `MapboxMap` is the controller, `MapView` is the view. 

All our activities in our TestApp are updated to reflect these changes:
  - [SupportMapFragmentActivity](https://github.com/mapbox/mapbox-gl-native/blob/b8aeb1a9f8a576de69956847fc265ea2668f62dc/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/SupportMapFragmentActivity.java)
