### ISSUE TITLE
Cannot build mapbox after "[core] Update to variant 1.1.0"

### ISSUE THREAD

**Issue by AlexeyIke** [mapbox/mapbox-gl-native#4454]
Cannot build mapbox after "[core] Update to variant 1.1.0" (https://github.com/mapbox/mapbox-gl-native/commit/39cbfcb5c9db479f833b05e622a64d768e8a4450)

No https://github.com/mapbox/mason/blob/variant-1.1.0/script.sh file on github.

**Comment by jfirebaugh** [comment]
Have you updated the `.mason` git submodule?

```
git submodule update
```
