### ISSUE TITLE
Crash on android  x86 processor

### ISSUE THREAD

**Issue by AlexeyIke** [mapbox/mapbox-gl-native#4456]
Our maps on mapbox crash sometimes on x86 processors - emulator anf phones.

Log from emulator :
03-24 16:10:59.742 16819-16906/ru.vl.map A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadcab1 in tid 16906 (Map Thread)
03-24 16:10:59.844 1193-1193/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-24 16:10:59.844 1193-1193/? A/DEBUG: Build fingerprint: 'Android/sdk_google_phone_x86/generic_x86:6.0/MASTER/2524533:userdebug/test-keys'
03-24 16:10:59.844 1193-1193/? A/DEBUG: Revision: '0'
03-24 16:10:59.844 1193-1193/? A/DEBUG: ABI: 'x86'
03-24 16:10:59.844 1193-1193/? A/DEBUG: pid: 16819, tid: 16906, name: Map Thread  >>> ru.vl.map <<<
03-24 16:10:59.844 1193-1193/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdeadcab1
03-24 16:10:59.850 1193-1193/? A/DEBUG:     eax a107c9d0  ebx a11b7ff4  ecx a107c9d0  edx b40447c0
03-24 16:10:59.851 1193-1193/? A/DEBUG:     esi a0ab9e20  edi a0ab9e98
03-24 16:10:59.851 1193-1193/? A/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 000000af  xss 0000007b
03-24 16:10:59.851 1193-1193/? A/DEBUG:     eip a107c9e6  ebp a0ab9d98  esp a0ab9d80  flags 00210292
03-24 16:10:59.854 1193-1193/? A/DEBUG: backtrace:
03-24 16:10:59.854 1193-1193/? A/DEBUG:     #00 pc 003c09e6  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so
03-24 16:10:59.854 1193-1193/? A/DEBUG:     #01 pc 003c0a25  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so
03-24 16:10:59.854 1193-1193/? A/DEBUG:     #02 pc 003c09c6  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (std::terminate()+38)
03-24 16:10:59.854 1193-1193/? A/DEBUG:     #03 pc 003c15b7  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (std::rethrow_exception(std::exception_ptr)+39)
03-24 16:10:59.854 1193-1193/? A/DEBUG:     #04 pc 000f9bf2  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (mbgl::util::toString(std::exception_ptr)+66)
03-24 16:10:59.854 1193-1193/? A/DEBUG:     #05 pc 0014508f  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (mbgl::Style::onGlyphsError(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::pair<unsigned short, unsigned short> const&, std::exception_ptr)+111)
03-24 16:10:59.854 1193-1193/? A/DEBUG:     #06 pc 001f5e86  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so
03-24 16:10:59.855 1193-1193/? A/DEBUG:     #07 pc 0022c9c3  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so
03-24 16:10:59.855 1193-1193/? A/DEBUG:     #08 pc 0021ccee  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (mbgl::util::RunLoop::process()+318)
03-24 16:10:59.855 1193-1193/? A/DEBUG:     #09 pc 0021f450  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (std::__1::__function::__func<std::__1::__bind<void (mbgl::util::RunLoop::*)(), mbgl::util::RunLoop*>, std::__1::allocator<std::__1::__bind<void (mbgl::util::RunLoop::*)(), mbgl::util::RunLoop*> >, void ()>::operator()()+48)
03-24 16:10:59.855 1193-1193/? A/DEBUG:     #10 pc 0021c6e9  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (mbgl::util::AsyncTask::Impl::asyncCallback(uv_async_s*)+41)
03-24 16:10:59.855 1193-1193/? A/DEBUG:     #11 pc 003a234c  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so
03-24 16:10:59.855 1193-1193/? A/DEBUG:     #12 pc 003a257c  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so
03-24 16:10:59.855 1193-1193/? A/DEBUG:     #13 pc 003ac5c5  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so
03-24 16:10:59.855 1193-1193/? A/DEBUG:     #14 pc 003a2adb  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (uv_run+427)
03-24 16:10:59.855 1193-1193/? A/DEBUG:     #15 pc 0021d39c  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (mbgl::util::RunLoop::run()+60)
03-24 16:10:59.855 1193-1193/? A/DEBUG:     #16 pc 0019b4d2  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (void mbgl::util::Thread<mbgl::MapContext>::run<std::__1::tuple<mbgl::View&, mbgl::FileSource&, mbgl::MapMode&, mbgl::GLContextMode&, float>, 0u, 1u, 2u, 3u, 4u>(mbgl::util::ThreadContext, std::__1::tuple<mbgl::View&, mbgl::FileSource&, mbgl::MapMode&, mbgl::GLContextMode&, float>&&, std::__1::integer_sequence<unsigned int, 0u, 1u, 2u, 3u, 4u>)+162)
03-24 16:10:59.855 1193-1193/? A/DEBUG:     #17 pc 0019b3db  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (mbgl::util::Thread<mbgl::MapContext>::Thread<mbgl::View&, mbgl::FileSource&, mbgl::MapMode&, mbgl::GLContextMode&, float>(mbgl::util::ThreadContext const&, mbgl::View&&&, mbgl::FileSource&&&, mbgl::MapMode&&&, mbgl::GLContextMode&&&, float&&)::'lambda'()::operator()() const+283)
03-24 16:10:59.855 1193-1193/? A/DEBUG:     #18 pc 0019b26b  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (std::__1::__thread_proxy<std::__1::tuple<mbgl::util::Thread<mbgl::MapContext>::Thread<mbgl::View&, mbgl::FileSource&, mbgl::MapMode&, mbgl::GLContextMode&, float>(mbgl::util::ThreadContext const&, mbgl::View&&&, mbgl::FileSource&&&, mbgl::MapMode&&&, mbgl::GLContextMode&&&, float&&)::'lambda'()> >(void*, void*)+123)
03-24 16:10:59.855 1193-1193/? A/DEBUG:     #19 pc 00080a93  /system/lib/libc.so (__pthread_start(void*)+56)
03-24 16:10:59.855 1193-1193/? A/DEBUG:     #20 pc 00021952  /system/lib/libc.so (__start_thread+25)
03-24 16:10:59.855 1193-1193/? A/DEBUG:     #21 pc 000170b6  /system/lib/libc.so (__bionic_clone+70)

Log from  phones:
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'asus/WW_a501cg/ASUS_T00J:5.0/LRX21V/WW_user_3.24.40.87_20151222_34:user/release-keys'
Revision: '0'
ABI: 'x86'
pid: 19558, tid: 19699, name: Map Thread  >>> ru.vl.map <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdeadcab1
    eax a1330da0  ebx a1462cf4  ecx a1330da0  edx b86db9c0
    esi a0e752d0  edi a0e75348
    xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000013f  xss 0000007b
    eip a1330db6  ebp a0e75248  esp a0e75230  flags 00210292

backtrace:
    #00 pc 003b9db6  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so
    #01 pc 003b9df5  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so
    #02 pc 003b9d96  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (std::terminate()+38)
    #03 pc 003ba987  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (std::rethrow_exception(std::exception_ptr)+39)
    #04 pc 000f5222  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (mbgl::util::toString(std::exception_ptr)+66)
    #05 pc 001cb72f  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (mbgl::Style::onGlyphsError(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::pair<unsigned short, unsigned short> const&, std::exception_ptr)+111)
    #06 pc 001dd966  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so
    #07 pc 00225ea3  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so
    #08 pc 002161ce  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (mbgl::util::RunLoop::process()+318)
    #09 pc 00218930  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (_ZNSt3__110__function6__funcINS_6__bindIMN4mbgl4util7RunLoopEFvvEJPS5_EEENS_9allocatorIS9_EEFvvEEclEv+48)
    #10 pc 00215bc9  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (mbgl::util::AsyncTask::Impl::asyncCallback(uv_async_s*)+41)
    #11 pc 0039b71c  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so
    #12 pc 0039b94c  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so
    #13 pc 003a5995  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so
    #14 pc 0039beab  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (uv_run+427)
    #15 pc 0021687c  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (mbgl::util::RunLoop::run()+60)
    #16 pc 00171b92  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (_ZN4mbgl4util6ThreadINS_10MapContextEE3runINSt3__15tupleIJRNS_4ViewERNS_10FileSourceERNS_7MapModeERNS_13GLContextModeEfEEEJLj0ELj1ELj2ELj3ELj4EEEEvNS0_13ThreadContextEOT_NS5_16integer_sequenceIjJXspT0_EEEE+162)
    #17 pc 00171a9b  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (_ZZN4mbgl4util6ThreadINS_10MapContextEEC1IJRNS_4ViewERNS_10FileSourceERNS_7MapModeERNS_13GLContextModeEfEEERKNS0_13ThreadContextEDpOT_ENKUlvE_clEv+283)
    #18 pc 0017192b  /data/app/ru.vl.map-1/lib/x86/libmapbox-gl.so (_ZNSt3__114__thread_proxyINS_5tupleIJZN4mbgl4util6ThreadINS2_10MapContextEEC1IJRNS2_4ViewERNS2_10FileSourceERNS2_7MapModeERNS2_13GLContextModeEfEEERKNS3_13ThreadContextEDpOT_EUlvE_EEEEEPvSO_+123)
    #19 pc 00037cdb  /system/lib/libc.so (__pthread_start(void*)+59)
    #20 pc 00032fba  /system/lib/libc.so (__start_thread+26)
    #21 pc 00011df6  /system/lib/libc.so (__bionic_clone+70)
phone - Asus Zenphone 5

**Comment by tobrun** [comment]
@AlexeyIke 
thank you for reaching out, can you describe us an use-case to reproduce? 
Which version of our library are you using?

**Comment by jfirebaugh** [comment]
This was fixed with #4339.
