### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#446]
This is a caching master ticket:

* #308: Cache glyph PBFs indefinitely
* #90: Cache tessellated polgyon data
* #123: Load non-matching tiles from cache to cover up lack of data

**Comment by mb12** [comment]
@kkaefer 
1.) Is it possible to add support for tessellation to the following mapbox projects?
https://github.com/mapbox/mapnik-vector-tile
https://github.com/mapnik/node-mapnik

**Comment by ansis** [comment]
The individual issues are still open. All of them are fairly separate in terms of implementation so I don't think we need this master ticket anymore
