### ISSUE TITLE
[iOS] documentation build fails with Xcode 7.3

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#4468]
Jazzy 0.50 fails searching for an Xcode with swift 2.1.1 when using Xcode 7.3 (which provides swift 2.2)

/usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.5.0/lib/jazzy/sourcekitten.rb:137:in `run_sourcekitten': Unable to find an Xcode with swift version 2.1.1. (RuntimeError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.5.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

**Comment by RomainQuidet** [comment]
adding --swift-version 2.2 in documents.sh solves the issue

**Comment by 1ec5** [comment]
Thanks for the report! Fixed in #4470.
