### ISSUE TITLE
iOS SDK resource bundle includes SVGs

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#4481]
The iOS SDK’s resource bundle is pulling in platform/default/resources/ for the .der files, but it’s inadvertently pulling in SVG files as well. The iOS SDK has no use for these SVG files; it uses PNGs rasterized from them.

@bleege, does the Android SDK need the SVG files? If not, we should move them to common/.

/cc @boundsj

**Comment by bleege** [comment]
@1ec5 Looking through the file list from `platform/default/resources` Android is in the same boat with iOS.  It's all about the `.der` files for Certificate Pinning.

![screen shot 2016-03-28 at 9 42 34 am](https://cloud.githubusercontent.com/assets/989928/14080257/73c021be-f4c9-11e5-8519-87584e828511.png)
_/platform/default/resources/ File List_
