### ISSUE TITLE
Missing mapbox.png resource after updating to Mapbox-iOS-SDK 3.1.2 w/ Fabric integration

### ISSUE THREAD

**Issue by stcleezy** [mapbox/mapbox-gl-native#4483]
I've updated to Mapbox-iOS-SDK 3.1.2  w/ Fabric according to the instructions here:
https://fabric.io/kits/ios/mapbox/install

However, whenever I try to instantiate MGLMapView, I get the following error:
Terminating app due to uncaught exception 'Resource not found', reason: 'The resource named “mapbox.png” could not be found in the Mapbox resource bundle.'

I see some people had issues w/ earlier version of Mapbox (https://github.com/mapbox/mapbox-gl-native/issues/3281), but I am using the following:

Cocoapods 0.39.0
Mapbox-iOS-SDK (3.1.2)

This is what my Pods tree looks like:
<img width="251" alt="screen shot 2016-03-27 at 7 36 13 pm" src="https://cloud.githubusercontent.com/assets/2244094/14069789/39a721d8-f453-11e5-9f66-7ea2dcb24721.png">

Any help would be greatly appreciated!

**Comment by 1ec5** [comment]
In the project editor, is Mapbox.framework listed in the “Embedded Binaries” section or the “Linked Frameworks and Libraries” section? It should be listed under both if you used CocoaPods to install the dynamic framework. (On the other hand, if you use Fabric’s Mac application, you’d get the 3.1.3 static framework, which should only be listed under “Linked Frameworks and Libraries”.)

**Comment by stcleezy** [comment]
I'm using CocoaPods, not the Mac app.

The Mapbox.framework wasn't in either "Embedded Binaries" or "Linked Frameworks and Libraries". I've manually added the dynamic framework to both, but I am still getting the same error.

<img width="680" alt="screen shot 2016-03-27 at 9 13 38 pm" src="https://cloud.githubusercontent.com/assets/2244094/14070854/ff56066c-f460-11e5-8f1d-55c0043d791f.png">

**Comment by stcleezy** [comment]
Some more info that is hopefully helpful:

- I upgraded from pre-GL version 1.6.1, also via CocoaPods. Not sure if this left some cruft in the project.
- The Fabric app doesn't recognize that Mapbox is installed. When I go through the steps to install version 3.1.3 (which references adding Fabric and Mapbox-iOS-SDK to my pdodfile and adding my account key) I also get an error:
<img width="307" alt="screen shot 2016-03-29 at 8 02 33 am" src="https://cloud.githubusercontent.com/assets/2244094/14112695/9ff960a4-f584-11e5-9abf-31aba7306bf2.png">

**Comment by 1ec5** [comment]
> I upgraded from pre-GL version 1.6.1, also via CocoaPods. Not sure if this left some cruft in the project.

It may have. The raster SDK was very different in terms of its dependencies.

> The Fabric app doesn't recognize that Mapbox is installed.

The Fabric application uses a very different workflow than the CocoaPods-based instructions on the site. In fact, the CocoaPods-based workflow installs a dynamic framework, while the Mac app installs a static framework. Both workflows add a scripted onboarding step that CocoaPods itself doesn’t. The onboarding functionality is a bit opaque to me, but it’s probably not a good idea to combine the CocoaPods and Mac app installation methods.

**Comment by stcleezy** [comment]
I am at a total loss... I remove all references to Mapbox, reinstall, and I still get the same error. I've tried both the dynamic and static frameworks with the same result. 

If I start a new project everything works fine, so I know it's some build / configuration setting.

Any additional guidance here?

**Comment by stcleezy** [comment]
I essentially started from scratch and removed all linked binaries, pods, etc. Re-installed everything and did a clean build, and now I am up and running. No clue what the actual root cause was here... hope nobody else has this issue!
