### ISSUE TITLE
Jank during scroll

### ISSUE THREAD

**Issue by justasm** [mapbox/mapbox-gl-native#4488]
There is noticeable jank / stuttering when scrolling the map on Android, both when triggered by gesture and programmatically.

This can be observed with both debug and release builds of the test app as well as with the Mapbox Dev Preview app published on the Play Store.

Tested on Nexus 5, Samsung Galaxy S3 and Nexus 5X.

Note that this seems to be an issue specifically with the Android SDK. There is minimal to no observed jank during scrolling with the iOS test app on an iPhone 5.

- - -

It may be of interest that the issue is greatly reduced when using a MapView backed by [`SurfaceView`](http://developer.android.com/reference/android/view/SurfaceView.html) (as opposed to the current implementation which uses [`TextureView`](http://developer.android.com/reference/android/view/TextureView.html)).

A minimal sample that allows to quickly toggle between the two implementations and makes the jank during scrolling apparent can be found at justasm/mapbox-gl-native@19c528b859ab74af5480024fe3d01ebed130d641

Some stats were calculated using the sample, a Nexus 5 running Android 6.0.1 Marshmallow and [`adb shell dumpsys gfxinfo`](http://developer.android.com/training/testing/performance.html). 

Methodology:

1. Load up respective version of the MapView using the linked sample.
2. Tap the `SCROLL` button to programmatically scroll the map horizontally back and forth 3 times to ensure the map tiles have loaded.
3. Reset the frame stats data using `adb shell dumpsys gfxinfo com.mapbox.mapboxsdk.testapp reset`.
4. Tap the `SCROLL` button to programmatically scroll the map horizontally back and forth until a sufficient number of frames have been captured.
5. Retrieve the frame stats using `adb shell dumpsys gfxinfo com.mapbox.mapboxsdk.testapp framestats`.

Results / observations:
- [Raw data](https://docs.google.com/spreadsheets/d/1jsDr498wAz1kzXTwC2UAnCfdkbU_2rhWYKeoJsPXj50/edit?usp=sharing).
- Short video (not a great representation of the issue): [TextureView](https://drive.google.com/file/d/0B6I6R4406QUzR3VHd1dxeWd5NkU/view?usp=sharing) vs [SurfaceView](https://drive.google.com/file/d/0B6I6R4406QUzb2gzbk9Pb2J1bDg/view?usp=sharing).
- Despite the appearance of jank, neither implementation has frame latency that exceeds 16ms.
- The TextureView implementation has, on average, a lower (i.e. better) frame latency.
- The SurfaceView implementation has a more stable frame latency.

![TextureView- vs SurfaceView-backed MapView frame latency](https://cloud.githubusercontent.com/assets/1081815/14079823/50aa7fea-f509-11e5-9290-6490b1143478.png)

**Comment by bleege** [comment]
@justasm This is great information.  Thank you for putting the time and energy into researching this and documenting it.  I'm CCing the team so that we can join your efforts to resolve this.  Thanks again!

/cc @zugaldia @tobrun @jfirebaugh @tmpsantos @brunoabinader

**Comment by bleege** [comment]
Here's some [context on why we switched to using TextureView](https://github.com/mapbox/mapbox-gl-native/issues/2244) last Fall.

**Comment by zugaldia** [comment]
@justasm Thank you so much again for this great report. We should extract the methodology that you describe here into a wiki page so that we can give it continuity and expand it over time.

Regarding the original point in OP, we're now shipping a `SurfaceView` implementation since `v4.2.0-beta.2` (see https://github.com/mapbox/mapbox-gl-native/issues/5000) that's bringing increased performance to the map. The longer term plan is to continue this optimization path using a `GlSurfaceView` https://github.com/mapbox/mapbox-gl-native/issues/5766. Let's continue the conversation there.

#### Next steps

- [ ] Extract performance measurement methodology into a wiki page @cammace

**Comment by cammace** [comment]
I've created a new wiki entry on how to test performance. Thanks @justasm.
https://github.com/mapbox/mapbox-gl-native/wiki/Testing-Android-map-performance
