### ISSUE TITLE
[question] How to test if a coordinates is inside a lake, a forest, etc.?

### ISSUE THREAD

**Issue by dagatsoin** [mapbox/mapbox-gl-native#4489]
Is there a way to access vector data to test if a coordinates is inside a forest zone, a lake or a building?

**Comment by 1ec5** [comment]
Not currently. This would be implemented as the fabled “featuresAt” function, which needs to be ported from GL JS. We’re tracking the feature in #352. There’s a rough cut implementation in #3172, which needs to be cleaned up, updated, and given functional tests before it can land.
