### ISSUE TITLE
InfoWindow always shown

### ISSUE THREAD

**Issue by dariav** [mapbox/mapbox-gl-native#4491]
I am using custom InfoWindowAdapter.

Wanted behaviour is that I do not want to show InfoWindow always, but just for some markers.

Problem is that even if I return `null` from my custom InfoWindowAdapter Mapbox will show an empty info window.

Let's say I have this code
```
mMapboxMap.setInfoWindowAdapter(new MapboxMap.InfoWindowAdapter() {
    @Override
    public View getInfoWindow(@NonNull Marker marker) {
      return null;
    }
});
```

I would expect no info window is show - even though I have set custom adapter.

**Possible solution**
Following changes in https://github.com/mapbox/mapbox-gl-native/issues/3736 I see that in SDK code today we have https://github.com/mapbox/mapbox-gl-native/blob/616a77202d3a87ed3121045105977038956876f2/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java#L993
```
if (isInfoWindowValidForMarker(marker) || getInfoWindowAdapter() != null) {
    mInfoWindows.add(marker.showInfoWindow(this, mMapView));
}
```

Which is obviously not checking for the actual content of info window view being returned.

I'm not sure if something like this would be legit (performance wise) but this is what I am using at the moment:
```
if (isInfoWindowValidForMarker(marker) || (getInfoWindowAdapter() != null && getInfoWindowAdapter().getInfoWindow(marker) != null )) {
  mInfoWindows.add(marker.showInfoWindow(this, mMapView));
}
```

It'd be great if you could squeeze this in 4.0.0 release. :+1:

**Comment by tobrun** [comment]
@dariav thank you for reaching out. We are actually managing this step through `OnMarkerClickListener`. This interface has a method `boolean onMarkerClick(Marker marker)`.

```
        boolean handledDefaultClick = false;
        if (mOnMarkerClickListener != null) {
            // end developer has provided a custom click listener
            handledDefaultClick = mOnMarkerClickListener.onMarkerClick(marker);
        }

        if (!handledDefaultClick) {
            if (isInfoWindowValidForMarker(marker) || getInfoWindowAdapter() != null) {
                mInfoWindows.add(marker.showInfoWindow(this, mMapView));
            }
        }
```


If you return `true` from this method, you are indicating to the system that you  have handled the click event. If you return `false`, you are indicating the click is not handed and should be handled by another component. For example an `InfoWindowAdapter`.

 - does this make sense that we have implemented in this way? 
 - does this cover the requirements you have? 

Reach out if you have other questions/suggestions!

**Comment by dariav** [comment]
@tobrun 
Thanks for the explanation and your time. I just wasn't focused enough when looking through the code.

Yes, it does make sense to have it implemented that way and I can easily apply my logic to `onMarkerClick`.
