### ISSUE TITLE
Polyline rendering on Samsung Galaxy Trend Plus

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-native#4494]
Per a help request: 
---

We have some issue drawing a polyline. It works on all devices we tested, except a **Samsung Galaxy Trend Plus (GT-S7580)** with Android 4.2.2 and we are using the 4.0.0-beta2 version of Mapbox. In the previous Mapbox version (3.2) we had the same problem.

If we zoom in the map, we can see a portion of the polyline (please see the attached screenshots). As you can see, the markers are correctly drawn.

![image](https://cloud.githubusercontent.com/assets/2365503/14088748/035f7f56-f4e6-11e5-95c0-5fb8db2a11fa.png)
![image](https://cloud.githubusercontent.com/assets/2365503/14088754/08577090-f4e6-11e5-971c-c55d9b4557d3.png)

This is the source code:

``` java
PolylineOptions options = new PolylineOptions();
  for(Point point : route.getJsonpoints()){
    for(PointLatLng latLng : point.getPath()){
      options.add(new LatLng(latLng.getLat(), latLng.getLng()));
  }
}
options.color(ContextCompat.getColor(getContext(), R.color.path_color));
options.width(15);

map.addPolyline(options);
```

cc @bleege

**Comment by cammace** [comment]
Is there a way we could test this using the latest SDK beta version `4.2.0-beta.4` @danswick? Never seen this issue and with runtime styling there might be a workaround now.

**Comment by danswick** [comment]
We haven't been able to confirm this issue. Closing for now. We can reopen if there are future reports.

**Comment by jonbe242** [comment]
We see the this issue too on this device. Not strictly the same problem, though, but more generic. The device draws NO lines at all in the map, no matter how wide they are styled. Tested with MBGL from this spring and from master-branch about a month ago.
