### ISSUE TITLE
Methods for taking screenshots of Map

### ISSUE THREAD

**Issue by olegosipenko** [mapbox/mapbox-gl-native#4513]
Since MapboxView uses OpenGL to render map it is impossible to use Android's view's `getDrawingCache()` to get screenshot of the map cause it's operating on Canvas.
Is it possible to add native call to take map's screenshot? Or any suggestions how to take screenshot of the MapboxView?

**Comment by tobrun** [comment]
@olegosipenko 
Thank you for reaching out. This feature request is being tracked in https://github.com/mapbox/mapbox-gl-native/issues/3466.

You are right, you can use the `getDrawingCache` for that. We are using this in our [ScreenShotUtil](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/espresso/utils/ScreenshotUtil.java) which we use to take screenshots during espresso testing. Feel free to start working on the feature in #3466 and make a PR for it.

We at Mapbox :heart:  PR's. 

Reach out if you have any other questions!
