### ISSUE TITLE
Updating markers in real time causes major UI lag

### ISSUE THREAD

**Issue by shantanu-vyas** [mapbox/mapbox-gl-native#4514]
When updating the position of a marker using marker.SetPosition(location) is done at a frequency < 1 second I noticed huge amounts of UI lag as well as the map panning slow. Using the Android Studios method tracer it shows that Marker.setPosition MapboxMap.updateMarker and Mapview.updateMarker take a significant amount of time.

**Comment by tobrun** [comment]
@shantanu-vyas thank you for reaching out and reporting your problem. Dynamically updating a Marker position/icon is something we recently added and are still finding ways to improve performance for making animation possible. At this point I'm confident to say an user can update a position of a marker but we not in way it resembles an fluent animation.

**Comment by jfirebaugh** [comment]
This was optimized in #5385.
