### ISSUE TITLE
Do not automatically update camera after setPadding

### ISSUE THREAD

**Issue by justasm** [mapbox/mapbox-gl-native#4520]
Changing the padding with the Android SDK's `MapboxMap#setPadding()` should not automatically move the camera.

Motivation:
- More flexible API. The user can always make a subsequent call to update the camera if necessary.
- Parity with the Google Maps Android API v2, which does not move the camera in response to `GoogleMap#setPadding()`.

The change would require [removing this line](https://github.com/mapbox/mapbox-gl-native/blob/a4b83a439cfaf67c653999cfc6f89bfa3ef8551e/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java#L1056).

I have tested this in justasm/mapbox-gl-native@cb2c2b24930760318182650481f800fccb199ac4 and the `MapPaddingActivity` in the test app continues to function as previously with no additional changes.

**Comment by tobrun** [comment]
@justasm 
I have thought about this as well, but in the end I copied iOS behaviour and that was to update the camera position. @1ec5 how do you feel about this on the iOS side? Would it make sense having 2 methods one that has an optional parameter to invalidate camera position?

**Comment by 1ec5** [comment]
Consistency with the Google Maps SDK may be more important than consistency with the Mapbox iOS and OS X SDKs in this case. It makes sense for the iOS and OS X SDKs to update the center automatically because that’s how scroll views and other inset views work on those platforms.

**Comment by tobrun** [comment]
@1ec5 makes sense in this case. @justasm thank you for reaching out and reporting this!
