### ISSUE TITLE
Enforce Wrap At Java LatLng Level

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#4522]
While working on #4444 we discovered that Core GL is no longer wrapping all Longitude values for the C++ `LatLng` objects that it generates and then passes to the Java `LatLng` ([done for anti merdian](https://github.com/mapbox/mapbox-gl-native/pull/4275)), which means that the SDK can't guarantee that they're wrapped.  This is important as it's been a tacitly compatible with the [Google Maps API `LatLng`](https://developers.google.com/android/reference/com/google/android/gms/maps/model/LatLng) until then.

To resolve this let's make sure that both `Latitude` and `Longitude` values are clamped to their respective ranges and deprecate the stopgap `LatLng.wrap()` method.  Let's also do a thorough dependency evaluation to ensure that all uses are covered.

Related Issues:  #4475 and #4477 

/cc @mapbox/mobile

**Comment by jfirebaugh** [comment]
For better or worse, we committed to unwrapped `LatLng` for 4.0.0, and that forms part of the public API. We can't change the wrapping semantics again until the next major version: 5.0.

**Comment by bleege** [comment]
> We can't change the wrapping semantics again until the next major version: 5.0.

Yep.  This is a semver change.

**Comment by cammace** [comment]
Added to `5.0.0` Milestone.

cc: @mapbox/android
