### ISSUE TITLE
Is there a way to render to off-screen buffer?

### ISSUE THREAD

**Issue by mattak** [mapbox/mapbox-gl-native#4525]
Is it possible to make 'mapbox-gl-native' to support off-screen rendering?
I'd like to use the generated texture in Unity 3D.

If supporting off-screen rendering requires some patching to 'mapbox-gl-native', will it still be priced by `mobile-users count`? 

apology for cross-posting.
- https://github.com/mapbox/mapbox-gl-native/issues/1631#issuecomment-202205209

**Comment by 1ec5** [comment]
> Is it possible to make 'mapbox-gl-native' to support off-screen rendering?

Yes! [node-mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/node) does just that, and [so does the OS X SDK](https://github.com/mapbox/mapbox-gl-native/blob/0539f7b4cb49e0690b9654f57fe9e2f724e14903/platform/osx/src/MGLMapView.mm#L2362-L2380) when you print the view.

**Comment by mikemorris** [comment]
@mattak We currently support offscreen rendering (which is used by the Node.js bindings) on Linux through [GLX](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/default/headless_view_glx.cpp) rendering to a virtual framebuffer with XVFB, on OS X through [CGL](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/headless_view_cgl.cpp) and on iOS through [EAGL](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/headless_view_eagl.mm). I'm currently working on [adding support for rendering with OSMesa](https://github.com/mapbox/mapbox-gl-native/issues/4498) as well.

**Comment by 1ec5** [comment]
By the way, if you only need static images of Mapbox-hosted styles and data, you might be interested in the [Mapbox Static API](https://www.mapbox.com/api-documentation/#static), which is included in all Mapbox plans.

**Comment by mattak** [comment]
@mikemorris 
My target platforms are Android and iOS.
Is headless view for Android support on the road map?
If there's no plan for it, we'd like to implement it contribute to the project.

@1ec5 
We considered static map as well.
However pricing for 'mobile-user count' is better suited for us.

**Comment by tobrun** [comment]
> Is headless view for Android support on the road map?

This is something that @tmpsantos is looking at and is tracked in #2150.

**Comment by msirenko** [comment]
Hey @mattak, Max from the business side here. Apologies if I miss some of the technical nuances here.

Currently, mobile-user count pricing applies only to our native iOS and Android SDKs, as well as a few hybrid platforms https://www.mapbox.com/help/hybrid-app-pricing/ that interact directly with our mobile SDKs.  Is this something that would work for your use case?

**Comment by mattak** [comment]
@tobrun
Thanks, I will follow the issue.

@msirenko
We are planing on developing a game app for iOS and Android which heavily uses map data.

Because of ecosystems, implementation costs and team resources,
Unity is our choice for time being. 
(React, Cordova or Xamarin is not best fit for us.)

We could build the app with Unity and MapBox's static tile api, but estimated running cost for 'map-view pricing' was too steep for us.
Hence we thought the answer to our problem was to implement mapbox-gl-native's offscreen texture rendering.
​
By the way, Is [Qt implementation](https://github.com/tmpsantos/qmapboxgl/) priced as 'mobile user count'?
Our customization may looks like a Qt's implementation.

**Comment by pine613** [comment]
:+1:

**Comment by friedbunny** [comment]
@mattak @pine613 The mobile pricing ([MAU](https://www.mapbox.com/help/define-monthly-active-users/)) currently does not apply to the Qt implementation. That said, we’re always excited to work with users to meet their specific needs — the folks at sales@mapbox.com may be able to help you. よろしくお願いします。:grin:

**Comment by mattak** [comment]
@friedbunny
Thanks, my question was resolved. and we quit the way.
So, I close this issue.
どうもありがとうございました! :bow:
