### ISSUE TITLE
Add User Location example to the test app

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4531]
Our old `MainActivity` was removed in favour of a `FeatureOverviewActivity` in #4365.
Currently we have no way of showcasing the possibility to toggle the user location on/off.
We should add a separate Feature activity covering this.

I'm suggesting to add a new Category `User Location` and move the `UserLocationTracking` with the new created Activity for this feature to that category.

This issue should also implement a clean way to handle runtime permissions and port that solution to `UserLocationTracking` example.

**Comment by bleege** [comment]
Closing as the work is being done in #4835 .
