### ISSUE TITLE
Release Android 4.0.0 Final

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#4535]
Mapbox Android 4.0.0 is the most ambitious Android release to date with 3 major new features being released.  These new features are part of our ongoing efforts focused on providing a premiere navigation experience in-car and on-dash for Android.  

To help us produce the highest quality SDK possible we've previously released 2 Beta builds and 1 Release Candidate.  The First beta was released on 15-March-2016 in #4334 and the Second beta was released on 21-March-2016 in #4419.  The Release Candidate was on 25-March-2016 in #4478.

#### Highlights

* [MapboxMap API Change](https://github.com/mapbox/mapbox-gl-native/issues/3145)
* [Offline Maps](https://github.com/mapbox/mapbox-gl-native/issues/3891)
* [Telemetry](https://github.com/mapbox/mapbox-gl-native/issues/2421)

Full Change Log: https://github.com/mapbox/mapbox-gl-native/issues?q=milestone%3Aandroid-v4.0.0

Release Branch: https://github.com/mapbox/mapbox-gl-native/commits/release-ios-3.2.0-android-4.0.0

#### The TODO list for making this happen:

- [x] Change Version Name to `4.0.0` in [`gradle.properties`](https://github.com/mapbox/mapbox-gl-native/blob/925687ab06892528f25fd4a79d27a55560634d96/platform/android/MapboxGLAndroidSDK/gradle.properties#L2)
- [x] Update version info in [Twitter Fabric metadata file](https://github.com/mapbox/mapbox-gl-native/blob/925687ab06892528f25fd4a79d27a55560634d96/platform/android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties#L2)
- [x] Publish `4.0.0` artifact to Maven Central
- [x] Updating Mapbox.com JavaDoc Documentation
- [x] Update [CHANGELOG.md](https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md)
- [x] Tag `android-v4.0.0` in GitHub
- [ ] Close Milestone `android-v4.0.0` in GitHub
- [x] Blog Post on https://www.mapbox.com/blog/
- [x] Tweet release
- [ ] Alert Twitter Fabric team of new release
- [x] Create ticket to merge `release-ios-3.2.0-android-4.0.0` branch back into `master`
- [x] Change Version Name _BACK to SNAPSHOT after release and release branch merge_ to support daily development.  In this case set to  `4.1.0-SNAPSHOT` in [`gradle.properties`](https://github.com/mapbox/mapbox-gl-native/blob/925687ab06892528f25fd4a79d27a55560634d96/platform/android/MapboxGLAndroidSDK/gradle.properties#L2)
- [x] Update [Mapbox Demo App](https://github.com/mapbox/mapbox-android-demo) to use `4.0.0` and release on Google Play

/cc @mapbox/mobile @mapbox/support @mapbox/sales @gundersen @lxbarth  @twbell @jfirebaugh @Lndsay

**Comment by bleege** [comment]
Mapbox Android 4.0.0 has just been released to Maven Central.  It should show up as published on Maven Central within the hour.

**Comment by bleege** [comment]
JavaDocs are ready to go once SDK is published on Maven Central.

**Comment by bleege** [comment]
Woo hoo!  Mapbox Android 4.0.0 was [just published on Maven Central!](https://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-sdk/4.0.0/).  I'll finish with the technical aspects of the release while it's now safe to start the Comms and Documentation portions of the Release.

**Comment by bleege** [comment]
Tagged release at https://github.com/mapbox/mapbox-gl-native/commits/android-v4.0.0

**Comment by bleege** [comment]
The [Demo App has been updated](https://github.com/mapbox/mapbox-android-demo/issues/57) and will be live on Google Play within a few hours.

**Comment by bleege** [comment]
Blog Post --> https://www.mapbox.com/blog/android-4/

**Comment by bleege** [comment]
Tweeted --> https://twitter.com/Mapbox/status/715290000871428096

**Comment by bleege** [comment]
I'm working directly with the Twitter Fabric team now to get this release and the new content on Fabric.

**Comment by Lndsay** [comment]
@bleege awesome -- do you have an ETA on that? (want to coordinate some light comms aka tweets)

**Comment by bleege** [comment]
@Lndsay Should be later today.

> want to coordinate some light comms aka tweets

Would love to!

**Comment by tobrun** [comment]
@bleege can we close the milestone?

**Comment by bleege** [comment]
@tobrun Nope.  Still working with Twitter on the Fabric issue.  Once that's done @Lndsay will be firing off some Tweets.

**Comment by bleege** [comment]
Just got confirmation from the team at Twitter that Mapbox Android 4.0.0 has now been released publicly.  All that remains is to work with @Lndsay to get some promotional Tweets tweeted and then we can officially close this ticket and milestone!  :rocket:

**Comment by bleege** [comment]
The Fabric Announcement Tweet has now shipped --> https://twitter.com/Mapbox/status/717718106819268608

Mapbox Android 4.0.0 is officially out the door.  :rocket:
