### ISSUE TITLE
Include podspec for static framework in iOS releases

### ISSUE THREAD

**Issue by postmechanical** [mapbox/mapbox-gl-native#4536]
Including the podspec file in iOS releases will make it simpler to install releases as local development pods.

**Comment by 1ec5** [comment]
It’s possible to point a podfile to a tagged podspec in this repository. For example, beta 3’s podspec is at https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.2.0-beta.3/platform/ios/Mapbox-iOS-SDK.podspec. We’ll mention this fact in prerelease pages on GitHub going forward.

Or are you asking for the ZIP itself to include a podspec file?

**Comment by postmechanical** [comment]
@1ec5 I'm not aware of any podfile options that allow one to reference a podspec that is not at the root of the repo: http://guides.cocoapods.org/using/the-podfile.html. I'm asking for the release zip archives themselves to include a podspec file so that, for example, the release with symbols can be installed as a local development pod.

**Comment by 1ec5** [comment]
Thanks for the clarification. That should be doable. For now, it's a bit involved, but here's a workaround: https://guides.cocoapods.org/making/private-cocoapods.html

**Comment by postmechanical** [comment]
@1ec5 So the podspec you provided actually is the debug symbols build. Unfortunately, since we commit our pods, this creates a problem because it contains files which exceed GitHub's 100 MB file size limit.

**Comment by 1ec5** [comment]
So far, we’ve always used the symbols build for prereleases, to increase the likelihood of actionable crash reports, but the symbol-less build for stable releases. Even so, we always publish both flavors for every prerelease and stable release. For now, can you use [this gist](https://gist.github.com/1ec5/397a19284103702cd771e2afa565b1f3) based on that file? (Click the Raw button to get a URL you can use in a Podfile.) It wouldn’t be difficult to provide both podspecs in the future.

**Comment by postmechanical** [comment]
@1ec5 Providing both podspecs in the future would be great. Thanks for the gist.

**Comment by 1ec5** [comment]
In a70928c995504567e85d0b34c2e10c104a72634c, I removed `-symbols` from the main podspec and added a `-symbols` podspec alongside it. You’ll be able to use either for RC 1 and all future releases and prereleases. The build scripts are being revamped for the next release, so we’ll revisit packaging podspecs in the build packages themselves later.

**Comment by 1ec5** [comment]
Between #5569 and #5595, we’re going to include podspecs for the dynamic framework in the v3.3.0 distribution, starting with RC 1. We’ll revisit podspecs for the static library, which is slightly more complex, in v3.3.1.
