### ISSUE TITLE
Merge iOS 3.2.0-Android-4.0.0 Release Branch Into Master

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#4538]
iOS 3.2.0 and Android 4.0.0 shared the same release branch, `release-ios-3.2.0-android-4.0.0` due to the launch off the Offline API in both.  When both platforms have been released we need to merge the combined release branch back into `master`.

* [x] Android 4.0.0 Release [Ticket](https://github.com/mapbox/mapbox-gl-native/issues/4535)
* [ ] iOS 3.2.0 Release

@mapbox/mobile

**Comment by jfirebaugh** [comment]
I merged `release-ios-3.2.0-android-4.0.0` to `master` in #4544, and reset the scheduled Android build on Bitrise to build from `master`.

We'll merge again after the iOS release.

**Comment by bleege** [comment]
Cool.  Thanks @jfirebaugh.  All future Android work should go back to being branched off of `master` then.

**Comment by boundsj** [comment]
@jfirebaugh @bleege @1ec5 for the record, I merged the last two commits from `release-ios-3.2.0-android-4.0.0` into master and deleted `release-ios-3.2.0-android-4.0.0`. I also deleted the GL Native – iOS Nightly that pointed to `release-ios-3.2.0-android-4.0.0` and replaced with a nightly that runs against `master` (same schedule).

**Comment by bleege** [comment]
Great work @mapbox/mobile for managing these complicated releases!  :rocket:
