### ISSUE TITLE
How to listen to telemetry data as user moves when follow me tracking is turned on?

### ISSUE THREAD

**Issue by sirvon** [mapbox/mapbox-gl-native#4541]
I would like to listen to the data/events ( location, speed, etc ) while a user moves through their environment while follow tracking is turned on, using mapbox's telemetry service.

Is this possible?

Thanks!

**Comment by boundsj** [comment]
Hi @sirvon. Are you using the iOS or Android version of the SDK, or both?

**Comment by 1ec5** [comment]
If you’re using the iOS SDK, you can get these notifications by implementing [`-[MGLMapViewDelegate mapView:didUpdateUserLocation:]`](https://www.mapbox.com/ios-sdk/api/3.1.2/Protocols/MGLMapViewDelegate.html#/c:objc(pl)MGLMapViewDelegate(im)mapView:didUpdateUserLocation:). The passed-in CLLocation object has properties that indicate the location and speed.

**Comment by tobrun** [comment]
On Android you can register a listener there to receive location updates. 

```java
LocationServices.addLocationListener(this);
```
