### ISSUE TITLE
create github issue template

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#4542]
https://help.github.com/articles/creating-an-issue-template-for-your-repository/

It's been working well in mapbox-gl-js.

**Comment by friedbunny** [comment]
[GL-JS’s issue template:](https://github.com/mapbox/mapbox-gl-js/blob/7b61aa9888bd98c3b6be0a9150225a1871fdae31/ISSUE_TEMPLATE.md)

```
<!--
Hello! Thanks for contributing. To help us diagnose your problem quickly, please:

 - include a link to a minimal demonstration of the bug; we recommend using https://jsbin.com
 - ensure you can reproduce the bug using the latest release
 - only post to report a bug or request a feature; direct all other questions to https://stackoverflow.com/questions/tagged/mapbox-gl-js
-->

**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1.
 2.
 3.

### Expected Behavior

### Actual Behavior
```

We would want to ask about platform, as well. Anything else?

**Comment by 1ec5** [comment]
Beyond that, it really depends on the platform, so probably not. I don't think we should make contributors wade through a flowchart to report an issue. So just the platform is fine.

**Comment by friedbunny** [comment]
Thanks for the kick @ansis, the GL-JS template looks really solid (and the commented instructions block is :100:). Let’s move implementation discussion to the pull request I just opened: #4545.
