### ISSUE TITLE
Controlling draw order of custom layers

### ISSUE THREAD

**Issue by PaulZed** [mapbox/mapbox-gl-native#4543]
Ideally we'd be able to specify where in the style our custom layer lands so we can control draw order. With the current implementation we're required to know out-of-band what layer we want to be before (or after? the language in the code is actually contradictory), or not specify a layer name and have the custom style be placed in a non-deterministic location based on what layers exist in the style. If the layer is added before the style finishes loading, it will likely land in a place where it will be drawn over, resulting in a custom layer that isn't visible.

I think ideally we would add the custom layer to the style definition in studio, and conditionally draw it if the map has a custom layer with the corresponding name. This way we can create our custom layer at map initialization time and not worry about draw order being disrupted when the map changes style. This doesn't really fix the problem that custom layer names must still be known out-of-band, but it does allow for flexible ordering.

@jfirebaugh @ansis @kkaefer Thoughts?

**Comment by brunoabinader** [comment]
Currently, whenever we switch the style, the layers are cleaned up (including custom layers), so we have to re-add if we want to continue using them. If we store custom layers in a separate container from the other regular layers (inside `Style`), we could force the custom layers to be drawn e.g. after the regular layers, and also keep them when switching styles. Do you folks see any drawbacks with this?

**Comment by PaulZed** [comment]
That's what I'm doing locally as a work-around, but that wouldn't allow for placing the layer above the base map, and below the labels. I think controlling the order via studio is still necessary without some serious run-time hacks.

**Comment by brunoabinader** [comment]
Related: https://github.com/mapbox/mapbox-gl-native/pull/4775

**Comment by jfirebaugh** [comment]
Z-ordering of custom layers is controlled by the final argument to `map.addCustomLayer`. This is a string which names the layer that the custom layer should be inserted immediately before. So, to get a custom layer to show immediately beneath labels, pass the layer ID of the labels layer.
