### ISSUE TITLE
Map loading in poor Internet connection conditions

### ISSUE THREAD

**Issue by NamtarR** [mapbox/mapbox-gl-native#4569]
**Platform: Android**
**Mapbox SDK version: 4.0.0**

### Steps to trigger behavior

 1. Open an app and download an offline region. (I don't think this is necesssary, but anyway).
 2. Somehow get your internet connection weak. I got such behavior while being on the ground floor. My device showed EDGE-connection with medium power and it seems the connection was present but had huge latency.
 3. Open the app and try to load a map.

### Expected behavior

The map loads fine and the app is fully functional.

### Actual behavior

The app knows about Internet connection presence and tries to connect to Mapbox servers, which could take a great amount of time. In my case I shut down the app after a minute of loading. I believe this is an extremely bad user experience when an offline map gets stuck loading with bad Internet connection.

**Comment by RomainQuidet** [comment]
@1ec5 Same behavior on iOS, map is lagging a lot

**Comment by 1ec5** [comment]
Does the lag only occur once offline regions (offline packs on iOS) have been downloaded? I tried a debug build of 3.2.0-beta.3 on an EDGE connection the other day and didn’t see any lag beyond the usual performance hit when running a debug build – certainly nothing in the ballpark of a minute.

**Comment by 1ec5** [comment]
Tracking iOS performance issue in #4613.

**Comment by NamtarR** [comment]
I haven't tested the issue on iOS yet but concerning Android:
1. The lag depends on connection speed. I have tested this by changing speed limit on my router and got the following results: on 10 kbps the lag was about 7-8 seconds long, on 1 kbps - more than 30 seconds.
2. The issue occurs both when the offline pack is downloaded and not downloaded.

**Comment by cammace** [comment]
Hey @NamtarR, came across this ticket and wanted to checkin to see if this issue is still occurring. If so, i'd love to look over your code and test to see if i'm able to reproduce. Also if you could provide device information so I can better troubleshoot it'd help. Closing this issue for now.
