### ISSUE TITLE
How to set line-join style of polyline? [iOS SDK]

### ISSUE THREAD

**Issue by harri121** [mapbox/mapbox-gl-native#4571]
How can I set the line-join style of a polyline overlay in the iOS SDK?

**Comment by friedbunny** [comment]
It’s currently not possible to set this type of styling property for annotations — this is a use case the programmatic style API (https://github.com/mapbox/mapbox-gl-native/issues/837) will address.

**Comment by valeriyvan** [comment]
Two years later, in April 2018, this seems not possible either.
