### ISSUE TITLE
Android TelemetryService Crashes App 4.0.0 snapshot

### ISSUE THREAD

**Issue by ThinkingMonkey** [mapbox/mapbox-gl-native#4572]
> 04-01 17:06:58.741 23317-23317/me.myapp.myappE/AndroidRuntime: FATAL EXCEPTION: main
>
>java.lang.RuntimeException: Unable to start service com.mapbox.mapboxsdk.telemetry.TelemetryService@1aea58f7 with Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=me.myapp.myapp/.ActivitySignIn (has extras) }: java.lang.IllegalArgumentException: Receiver not registered: com.mapbox.mapboxsdk.telemetry.TelemetryLocationReceiver@22ed5364
>at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2941)
>at android.app.ActivityThread.access$2100(ActivityThread.java:155)
>at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
>at android.os.Handler.dispatchMessage(Handler.java:102)
>at android.os.Looper.loop(Looper.java:135)
>at android.app.ActivityThread.main(ActivityThread.java:5356)
>at java.lang.reflect.Method.invoke(Native Method)
>at java.lang.reflect.Method.invoke(Method.java:372)
>at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
>at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
>Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.mapbox.mapboxsdk.telemetry.TelemetryLocationReceiver@22ed5364
>at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:765)
>at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1831)
>at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:511)
>at com.mapbox.mapboxsdk.telemetry.TelemetryService.shutdownTelemetry(TelemetryService.java:146)
>at com.mapbox.mapboxsdk.telemetry.TelemetryService.onTaskRemoved(TelemetryService.java:84)
>at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2926)
>at android.app.ActivityThread.access$2100(ActivityThread.java:155) 
>at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415) 
>at android.os.Handler.dispatchMessage(Handler.java:102) 
>at android.os.Looper.loop(Looper.java:135) 
>at android.app.ActivityThread.main(ActivityThread.java:5356) 
>at java.lang.reflect.Method.invoke(Native Method) 
>at java.lang.reflect.Method.invoke(Method.java:372) 
>at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
>at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 

**Platform:** 
Android 5.1
**Mapbox SDK version:**
4.0.0 snapshot
**Device**
Motorola Droid Turboxt1254

### Steps to trigger behavior

 1. app to pause(hit home button)
 2. app launch
 3. immediate crash

### Expected behavior
Not to crash
### Actual behavior
Crash

**Comment by bleege** [comment]
@ThinkingMonkey Thanks for the report about this issue.  It was resolved in 34cea826b9ae4d2fb9d713415c21880e195941cf which first shipped in RC 1 and then ultimately in Mapbox Android 4.0.0 last week.  Please give 4.0.0 a try and let us know if it's still an issue for you.  Thanks again!
