### ISSUE TITLE
Console full of warnings

### ISSUE THREAD

**Issue by postmechanical** [mapbox/mapbox-gl-native#4573]
**Platform:** iOS
**Mapbox SDK version:** 3.2.0-beta.3

### Steps to trigger behavior

 1. Download one or more offline packs
 2. Stop and re-run app

### Expected behavior

Console not littered with warnings.

### Actual behavior

Console littered with warnings `[WARNING] {DefaultFileSource}[Database]: Unable to make space for entry`.

**Comment by 1ec5** [comment]
Duplicate of #4411.
