### ISSUE TITLE
`run-linux` exits immediately on osx

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#4578]
### Steps to trigger behavior

 1. `make linux run-linux`

### Expected behavior

It runs.

### Actual behavior

It exits immediately without error.

`make linux run-linux` is supposed to work on osx, right?

It broke for me in 879382f72405edd1840d2f37744bcba49131859a . It looks like the view's RunLoop exits immediately. @jfirebaugh

**Comment by jfirebaugh** [comment]
I think this is essentially the same issue as #3634. `make linux` should build with linux-appropriate `loop_lib`, `http_lib`, etc -- not the host defaults.

**Comment by kkaefer** [comment]
This only seems to be an issue when building with `loop=darwin`. In particular, it looks like the single timer isn't enough to keep the cfrunloop alive.

**Comment by kkaefer** [comment]
In a similar vein, node.js tests on OS X (when built with Xcode and using `loop=darwin` are failing to complete and hang indefinitely when rendering.

**Comment by jfirebaugh** [comment]
Normally a timer is enough to keep a CFRunLoop alive. We have existing unit tests that verify that. The issue with the GLFW app seems to be specifically triggered by the use of `glfwCreateWindow` -- it must do something internally to the main run loop that triggers this behavior.

**Comment by jfirebaugh** [comment]
I set a breakpoint on `CFRunLoopStop` and this is what I see:

```
#0	0x00007fff8e81c050 in CFRunLoopStop ()
#1	0x0000000100515547 in _glfwPlatformPostEmptyEvent at /Users/john/Development/mapbox-gl-native/mason_packages/.build/glfw-3.1.2/src/cocoa_window.m:1142
#2	0x0000000100515429 in -[GLFWApplicationDelegate applicationDidFinishLaunching:] at /Users/john/Development/mapbox-gl-native/mason_packages/.build/glfw-3.1.2/src/cocoa_window.m:287
#3	0x00007fff8e8a770c in __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ ()
#4	0x00007fff8e8a767f in ___CFXRegistrationPost_block_invoke ()
#5	0x00007fff8e8a6d47 in _CFXRegistrationPost ()
#6	0x00007fff8e8a6ab2 in ___CFXNotificationPost_block_invoke ()
#7	0x00007fff8e8a0d42 in -[_CFXNotificationRegistrar find:object:observer:enumerator:] ()
#8	0x00007fff8e78f145 in _CFXNotificationPost ()
#9	0x00007fff9a00e921 in -[NSNotificationCenter postNotificationName:object:userInfo:] ()
#10	0x00007fff92c9b65d in -[NSApplication _postDidFinishNotification] ()
#11	0x00007fff92c9b3d3 in -[NSApplication _sendFinishLaunchingNotification] ()
#12	0x00007fff92c9888d in -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] ()
#13	0x00007fff92c98337 in -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] ()
#14	0x00007fff9a040861 in -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] ()
#15	0x00007fff9a0406db in _NSAppleEventManagerGenericHandler ()
#16	0x00007fff99952231 in aeDispatchAppleEvent(AEDesc const*, AEDesc*, unsigned int, unsigned char*) ()
#17	0x00007fff99951fb8 in dispatchEventAndSendReply(AEDesc const*, AEDesc*) ()
#18	0x00007fff99951ed4 in aeProcessAppleEvent ()
#19	0x00007fff9d782af9 in AEProcessAppleEvent ()
#20	0x00007fff92c92588 in _DPSNextEvent ()
#21	0x00007fff9305e943 in -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] ()
#22	0x00007fff92c87fc8 in -[NSApplication run] ()
#23	0x0000000100516d8c in initializeAppKit at /Users/john/Development/mapbox-gl-native/mason_packages/.build/glfw-3.1.2/src/cocoa_window.m:829
#24	0x0000000100516bad in _glfwPlatformCreateWindow at /Users/john/Development/mapbox-gl-native/mason_packages/.build/glfw-3.1.2/src/cocoa_window.m:939
#25	0x0000000100511f7f in glfwCreateWindow at /Users/john/Development/mapbox-gl-native/mason_packages/.build/glfw-3.1.2/src/window.c:178
#26	0x000000010000b183 in GLFWView::GLFWView(bool, bool) at /Users/john/Development/mapbox-gl-native/platform/default/glfw_view.cpp:59
#27	0x000000010000de04 in GLFWView::GLFWView(bool, bool) at /Users/john/Development/mapbox-gl-native/platform/default/glfw_view.cpp:24
#28	0x0000000100002b1a in std::__1::__unique_if<GLFWView>::__unique_single std::__1::make_unique<GLFWView, bool&, bool&>(bool&&&, bool&&&) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3075
#29	0x0000000100002ab1 in main at /Users/john/Development/mapbox-gl-native/bin/glfw.cpp:106
```

[Here's `_glfwPlatformPostEmptyEvent`](https://github.com/glfw/glfw/blob/3.1.2/src/cocoa_window.m#L1130-L1144), and [here's `[GLFWApplicationDelegate applicationDidFinishLaunching:]`(https://github.com/glfw/glfw/blob/3.1.2/src/cocoa_window.m#L283-L288). @1ec5 Any idea why this code is triggering `CFRunLoopStop`?

**Comment by jfirebaugh** [comment]
It looks to me like glfw purposefully stops the main run loop, via `[NSApp stop:]`, as soon as it is initialized. The assumption is that the application is going to loop using `glfwWaitEvents` later on, which waits on `[NSApp nextEventMatchingMask:]`, which apparently works even if `[NSApp stop:]` has been called. But we don't do that -- we use `CFRunLoopRun` instead. And whatever `[NSApp stop:]` does causes subsequent calls to `CFRunLoopRun` to return immediately.

**Comment by jfirebaugh** [comment]
I'm getting really skeptical about the value of maintaining glfw-app compatibility on OS X. It's proving to be something we sink _a lot_ of time into maintaining. I think we should just drop support in favor of the Cocoa OS X app.

**Comment by kkaefer** [comment]
I'm not sure what the source is, but every time I've used the osxapp, I've found it to be slower/sluggish compared to the GLFW app, so I'm wary of dropping it as a subjective performance measurement tool.

**Comment by 1ec5** [comment]
@kkaefer, if you can attach a sample of what you're seeing, I'd be happy to dive in and address the issue. It might just be a product of the compositing OS X needs to do for the fancy toolbar effect that's common for native applications. If that's the case, we could nix the toolbar or introduce a simpler window that lacks one (a simple copy-paste job in the main XIB). Otherwise, you might be seeing a real issue that affects the iOS SDK, since the two share a lot in common.

**Comment by brunoabinader** [comment]
> we could nix the toolbar or introduce a simpler window that lacks one

For comparison purposes, I think we should introduce the same frame rate output to stdout we currently have in the GLFW client.

**Comment by 1ec5** [comment]
I filed #4667 for a benchmarking application based on the OS X SDK, similar to the “Bench GL” application that’s based on the iOS SDK. Creating the application should be quite straightforward once I bring the improvements in #4641 over to OS X. In the meantime, Xcode’s Debug navigator has a framerate gauge you can use.
