### ISSUE TITLE
[android] Time to add marker on map hugely increased.

### ISSUE THREAD

**Issue by zikil** [mapbox/mapbox-gl-native#4581]
In new API(addMarker via MapboxMap), it takes around 100ms to add one marker on map on my nexus 5.
To reproduce:
```
       for (int i = 0; i < 100; i++) {
         map.addMarker(/*marker here*/);
       }
```
App will hung up for second or two.

**Comment by tobrun** [comment]
Thank you for reaching out, #4100 should revert those changes.
I will try to git bisect from previous release and see where the decrease in speed is coming from.

**Comment by tobrun** [comment]
This could be related to https://github.com/mapbox/mapbox-gl-native/issues/4553 and https://github.com/mapbox/mapbox-gl-native/issues/4534. Would you be able to verify this be using the latest SNAPSHOT? build instructions can be found in https://www.mapbox.com/android-sdk/#gradle

**Comment by tobrun** [comment]
@zikil one tip on this topic is to group all of your markers into a List and call `addMarkers` instead.
Closing as non actionable for now.
