### ISSUE TITLE
Eliminate gyp/build output

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#4582]
Some build products get output to `gyp/build` rather than `build`. This is probably a historical accident or quirk of gyp. We should adjust the build to eliminate this special case output directory -- everything should go to `build`.

**Comment by jfirebaugh** [comment]
gyp is involved here, but this largely seems to be a quirk of `xcodebuild -target foo` versus `xcodebuild -scheme foo`. The former seems to set `SYMROOT` to `$SRCROOT/build` (and `SRCROOT` is indeed set to `./gyp` by gyp), while the latter uses a directory in `~/Library/Developer/Xcode/DerivedData` (the same one that builds from within Xcode use). I can't find this difference between `-target` and `-scheme` documented anywhere, and it's contrary to the output of `xcodebuild -showBuildSettings`, which says that `SYMROOT` is the `~/Library/...` path in either case.

**Comment by mikemorris** [comment]
IIRC this was a result of some refactoring I did on the Node.js bindings when we integrated them into this repository.

**Comment by jfirebaugh** [comment]
The key here seems to be that `SYMROOT` needs to be an _absolute_ path. If it's a relative path, it's ignored by `xcodebuild -target ...`, but if it's absolute, it's respected.

In #4608 I'm setting up the ios and osx gyp files to force an absolute path.
