### ISSUE TITLE
flickering markers, removal broken

### ISSUE THREAD

**Issue by mastrgamr** [mapbox/mapbox-gl-native#4584]
**Platform:** Android (6.0.1 Nexus 6P)
**Mapbox SDK version:** 4.0.0

### Steps to trigger behavior
See [Gist](https://gist.github.com/mastrgamr/cab875c15ca1ae97efb0d6fe163ceac9)

 1. Initializing Marker and MarkerOptions
 2. Once map fully loaded move to target location
 3. click on FAB to remove marker

### Expected behavior
Simple marker removal, and steady animation while panning/zooming.

### Actual behavior
Marker constantly flickers while panning/zooming map. If I remove the marker by clicking on the FAB (provided in the Gist) it removes the marker initially, *but* when I begin panning/zooming again the marker appears again (in its same flickering glory).

The behavior doesn't seem to be happening if the marker position is initialized from some sort of InputStream (i.e. a Json, XML, CSV).

**Comment by tobrun** [comment]
@mastrgamr thanks for writing up this bug report. We noticed and fixed this in https://github.com/mapbox/mapbox-gl-native/issues/4553. You can work around this issue for now using our SNAPSHOT. Install instructions can be found [here](https://www.mapbox.com/android-sdk/#gradle).
