### ISSUE TITLE
how can i add GPS Location with app 4.0.0 for Android

### ISSUE THREAD

**Issue by kuraii3** [mapbox/mapbox-gl-native#4592]
hello , 
please how can i get my location with mapbox-android-sdk:4.0.0 cause the API look not the same as GpsMyLocationProvider doesn't exist anymore.
thanks.

**Comment by tobrun** [comment]
@kuraii3 
you can use `LocationServices.getLocationServices()` for that and manipulate the state with `toggleGps(enabled)` and `addLocationListener(listener)`. Reach out if you have any other questions.
