### ISSUE TITLE
linuxapp exits immediately

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#4597]
There seems to be a bug in our CoreFoundation based runloop/timer implementation, which was exposed by https://github.com/mapbox/mapbox-gl-native/commit/baf30cd1f776ec0a44688c12580bacf45e33c93c: The single timer added to the runloop is not enough to keep the loop alive; and it exits immediately.

/cc @1ec5 @tmpsantos

**Comment by ansis** [comment]
duplicate of https://github.com/mapbox/mapbox-gl-native/issues/4578?

**Comment by kkaefer** [comment]
Yes.
