### ISSUE TITLE
Bitrise OS X node tests should fail if output fails

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#4600]
Bitrise reports https://www.bitrise.io/build/6933d45bafef6b66 as successful despite having failing test comparisons (`14 failed (4.7%)`)

**Comment by jfirebaugh** [comment]
The OS X build script needs some error handling fixes [here](https://github.com/mapbox/mapbox-gl-native/blob/65acf35dcfa3784de7e522926469083068599550/platform/node/bitrise.yml#L42-L43). It should run `after_script.sh` always, and then exit with the status from `run.sh`.
