### ISSUE TITLE
Add Hugo for logging and measuring execution time

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4604]
I'm suggesting adding this not only to MapboxGLAndroidSDKTestApp but also the lib itself.

Example of Hugo in action:

```java
@DebugLog
public String getName(String first, String last) {
  SystemClock.sleep(15); // Don't ever really do this!
  return first + " " + last;
}
```

results in

```java
V/Example: ⇢ getName(first="Jake", last="Wharton")
V/Example: ⇠ getName [16ms] = "Jake Wharton"
```

The logging will only happen in debug builds and the annotation itself is never present in the compiled class file for any build type. This means you can keep the annotation and check it into source control. It has zero effect on non-debug builds.

More information: https://github.com/JakeWharton/hugo

**Comment by tobrun** [comment]
I initially thought the scope would be perfect for the whole project, Now it seems it can't be used in library projects without adding multiple hacks https://github.com/JakeWharton/hugo/issues/31. Going to try finding an alternative that can be used in our library project.

**Comment by tobrun** [comment]
@zugaldia 
I remember a person at GDG DC talking about a library that could measure execution time automatically. Do you remember which one that was?

**Comment by bleege** [comment]
Subscribing for updates.

**Comment by zugaldia** [comment]
@tobrun I believe this was @Jayroo5245. Do you have more details to help us find the library?

**Comment by bleege** [comment]
@tobrun Could you provide some context as to what exactly we're looking to have measured?

**Comment by Jayroo5245** [comment]
Hey all,

I believe I mentioned a library that does some of this automatically. Since it is "automatic" it will not have the granularity of an actual production level analytic library. However we have found it quite useful.

https://www.gryphonet.com/

The CEO is a friend of my CTO's so we have played with it a good amount. The key to their business model is to automatically figure out performance issues, report crashes (Java and Native layers), memory issues, battery etc. Its literally a few lines of code for most of it. You can use it as a full analytics library as well.

Tell them Jared from Driversiti sent you.

**Comment by Jayroo5245** [comment]
@bleege @tobrun and @zugaldia ^^

**Comment by tobrun** [comment]
@bleege I'm trying to find a time measurement solution that does the magic for us automatically. Currently we are timing method execution with: `TimingLogger` but this requires adding it manually to a method and that code is also included in a release build.

The reason why I want to add such a thing is `You can't manage what you don't measure` or `Do not optimise without measuring`. When trying to improve performance, analysing and quantifying time is very important and will help us a lot on the long run.

**Comment by bleege** [comment]
I'm totally with ya @tobrun on `You can't manage what you don't measure`.  ;-)  I'm just trying to learn what specific part of the SDK we're looking to have measured.  Is their something specifically lagging right now that we should be worried about or is this just for general good hygiene?

**Comment by bleege** [comment]
Discussed internally with @tobrun and this has to do with OpenGL rendering performance.  He'll be publishing more technical data on this soon.

**Comment by tobrun** [comment]
@bleege FWIW the use-case separate from OpenGL rendering is the time needed to add a marker to a map or measure the time needed to update an existing one.

**Comment by tobrun** [comment]
I haven't found an open source alternative that does what we need. I'm currently going to stick with using TimingLogger and will keep 👀  if anything changes with Hugo or alternative libs. Closing for now.

**Comment by zugaldia** [comment]
> Currently we are timing method execution with: TimingLogger but this requires adding it manually to a method and that code is also included in a release build.

@tobrun How about a custom annotation that does nothing in release mode?

**Comment by tobrun** [comment]
@zugaldia, I see where you are going with this :)

**Comment by pedrocactus** [comment]
@tobrun i am pretty sure you can build libs in debug. At least with the last versions of gradle. So hugo seems to get the job done ☺

**Comment by tobrun** [comment]
@pedrocactus yeah, I tried doing that but didn't receive any output from Hugo at the time of testing https://github.com/mapbox/mapbox-gl-native/issues/4604#issuecomment-205772640 but since then we upgraded our gradle version so it could be resolved. I will try to revisit testing Hugo.

**Comment by tobrun** [comment]
Still an issue, closing..
