### ISSUE TITLE
Make TestApp Example Names More Discoverable

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#4609]
As part of #4365 #4570 the functionality examples where compressed a bit into more general examples and names.  This can lead to discoverability issues that we should address.  For example, there used to be a "Bulk Marker" example that's now bundled into the activity known as "Add Markers".  Let's make this specific one more clear as well as review the previously named Activities in the screenshot below:

<img width="1385" alt="screen shot 2016-04-05 at 9 13 20 pm" src="https://cloud.githubusercontent.com/assets/989928/14303839/67268794-fb73-11e5-8836-e5c547dd399c.png">
_Pre TestApp Refactor Example Activities_

/cc @zugaldia @tobrun @cammace @danswick

**Comment by tobrun** [comment]
Feel free to rename them in anyway you like :+1:

**Comment by bleege** [comment]
Thanks @tobrun!  Naturally, this came up immediately after we merged #4570 when someone asked me where `BulkMarkerActivity` went as it was a reference for them.

**Comment by bleege** [comment]
I just :eyes: the rest of the Activities in the screenshot above and it looks like `BulkMarkerActivity` was the only one that got renamed.  I'll merge this back in and hopefully everyone should be able to find what they were looking for again.

This is a classic case of "no good deed goes unpunished."  :smile:
