### ISSUE TITLE
Clicking on point annotations near dateline

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4612]
To visualise this issue see next clip:
 * https://www.dropbox.com/s/a85qbltqev6yyk9/device-2016-04-06-112039.mp4?dl=0

The problem is that we are calculating a LatLng from screencoordinates left of the dateline while using a LatLng from screencoordinates from the right side of the dateline. This conflicts and results in a incorrect touch target.

Discussed this a bit with @brunoabinader and decided this is a platform specific problem and should be solved in the Android SDK itself.

**Comment by bleege** [comment]
This is likely related to the wrapping issue that we've looked at in #4275 and #4444.  It'll also likely be part of the Sem Ver changing fix in #4522.

/cc @jfirebaugh @zugaldia

**Comment by 1ec5** [comment]
Even if you address the platform-specific problem, you’ll still run into #4974 in mbgl.

**Comment by bleege** [comment]
Duplicate of #4974.  Discussed with @tobrun @cammace on scrum today.
