### ISSUE TITLE
[iOS] Bad overall performances

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#4613]
Platform: iOS 8.1 on iPhone 5
Mapbox SDK version: 3.2.0
### Steps to trigger behavior
1. Delete previous MapboxGL demo app on iOS device
2. Compile and install demo app from 3.2.0 branch (release tag)
3. Run the demo app, with a solid wifi connection
### Expected behavior

Double tap on map to zoom in, the map should show data without freezing.
Once tiles downloaded, pan around to see the maps details should be fluid.
### Actual behavior

The map lags a lot, panning the
 map with downloaded and cache tiles show micro freezes. Details on map like road names, signs can appear after 4 or 5 seconds.
Zooming, panning often consumes more than 180% of CPU on this device (2 CPU). 
Doing nothing still consume 1% CPU.
The FPS never reach 60, stuck below 50.

![mapboxgl2](https://cloud.githubusercontent.com/assets/8179069/14312611/3f0ed43a-fbed-11e5-9849-ee96e93c7991.jpg)

**Comment by friedbunny** [comment]
This sounds like typical debug build behavior (which is much less optimized during compilation) — can you confirm that you're using the release build configuration?

**Comment by 1ec5** [comment]
Also, can you attach a sample of a process (preferably in a gist)? I can’t find the issue number right now, but debug builds have had noticeable lag compared to release builds when panning for a couple releases now. Samples usually indicate that the Map thread is busy parsing tiles.

**Comment by RomainQuidet** [comment]
Hi,
Thanks for your feedback. I've always tested new versions the same way, pulling the tag and running the demo app on several devices. I've seen since 3.2.0 early releases a performance decrease, it seems to be very visible now.
I'll try to compare with releases version to see if the performance issue disappear, but it's not a good sign to have lags like this when a few releases again we hadn't.

**Comment by incanus** [comment]
@RomainQuidet How are things for you currently? Can this be closed?

**Comment by RomainQuidet** [comment]
Sorry for this very late response, but yes it was a bug in the build process, it tested a debug version. Release version is solid and quick. Thanks !
