### ISSUE TITLE
make idocument fails due to incompatible jazzy

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-gl-native#4620]
**Platform:** iOS
**Mapbox SDK version:** 3.2.0

### Steps to trigger behavior

 1. Trigger GL Native iOS build
 2. Observer failure on bitrise

### Expected behavior

Bitrise should not fail on the `make ipackage-sim` step.

### Actual behavior

iOS build fails

cc @1ec5

**Comment by 1ec5** [comment]
`make idocument`’s invocation of `jazzy` is failing because jazzy has released a [new version](https://github.com/realm/jazzy/releases/tag/v0.6.0) with some breaking changes, and we aren’t pinning to a specific version.
