### ISSUE TITLE
Better documentation for the difference between easeCamera and animateCamera for Android

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-native#4624]
The documentation for these methods does little to explain any difference between their behavior. It needs to be much more clear.

**Comment by 1ec5** [comment]
For reference, here are the [corresponding iOS SDK methods along with documentation](https://github.com/mapbox/mapbox-gl-native/blob/e7ac0f6d4c39fed294effaed3ccd1d423fb4d913/platform/ios/include/MGLMapView.h#L631-L718).
