### ISSUE TITLE
Add print functionality

### ISSUE THREAD

**Issue by snodnipper** [mapbox/mapbox-gl-native#4628]
**Background info**
Many users like to print maps, especially when they cannot rely on technology being available.  For example: a hiker travelling for several days with limited equipment and battery life.  For those situations, they print the area of interest onto paper, [tea towel](http://www.splash-maps.com/) etc.

**Feature Request**
Provide a convenience method to create an image suitable for print.
* output params: width, height, DPI of the image.
* input params: style, center and scale of the map (or use the MapView as param input).

On Android, this code would fit in well with [Printing Content](http://developer.android.com/training/printing/index.html).

**Comment by tobrun** [comment]
@snodnipper 

thanks for reaching out and requesting this feature. 

We actually expose such a thing via a webservice. See [here](https://www.mapbox.com/help/create-a-static-map/) for more information. If you feel the static-api is too limited feel free to open a feature request there.

Note: their is a way to take a snapshot from a currently visible Map. 

```java
 /**
     * Takes a snapshot of the map.
     *
     * @param callback Callback method invoked when the snapshot is taken.
     */
    @UiThread
    public void snapshot(@NonNull SnapshotReadyCallback callback) {
        mMapView.snapshot(callback, null);
    }
```

Since we support a websevice to do this, we will have no intention of adding it to this SDK at this point.

**Comment by friedbunny** [comment]
[Here’s a link to Mapbox’s print help and guidelines.](https://www.mapbox.com/help/print-policy/)

**Comment by snodnipper** [comment]
Thanks folks for the comments.  I accept that there are existing solutions _but_ there are issues:

1) Client-side maps:  some users may create points, polygons etc. on the device.
   They would like points and polygons to be printed on the map.  I don't believe this is possible with the static maps API (snapshot functionality does).

2) Privacy: assuming folk could add points, polygons etc. to the map there are instances where customers won't accept such data to be transmitted to MB servers.  For instance, in Public Health it would be inappropriate to share locations of those suffering from illnesses (e.g. STIs) outside validated networks.

I'll take a closer look at the snapshot code.

Cheers.
