### ISSUE TITLE
Telemetry events buffer should be capped

### ISSUE THREAD

**Issue by vkurchatkin** [mapbox/mapbox-gl-native#4629]
We've started noticing `OutOfMemoryError` with the following stack trace:

<img width="960" alt="screen shot 2016-04-07 at 14 07 59" src="https://cloud.githubusercontent.com/assets/2993861/14349221/3a743c70-fcca-11e5-9418-8f13efcc0a18.png">

It seems that it happens when device is offline for too long and have collected too much events. Even if it succeedeed, I'm not sure that Mapbox servers would be happy with parsing enormous JSONs. 

I see a couple of options:

 - use capped buffer for events (maybe some flavour of ring buffer); there is a chance to drop some events, but if we crash we drop all of them anyway;
 - send events in chunks; it would solve serialization problem, but  `OutOfMemoryError` could still happen because of excessive buffer growth;
 - flush some part of events to flash, while offline.

**Platform:** Android (but probably applies to iOS as well)
**Mapbox SDK version:** 4.0.0

**Comment by tobrun** [comment]
We should look into what is causing this by monitoring memory footprint over time. We shouldn't be allocated new memory every update if possible reuse objects.

**Comment by boundsj** [comment]
> Platform: Android (but probably applies to iOS as well)

This does not apply to iOS  -- in [iOS v3.2.0](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.2.0) the queue is flushed every 180 events or 3 minutes

**Comment by bleege** [comment]
@vkurchatkin Thanks for reviewing this and the suggestions.  You're exactly right when you say "device is offline for too long and have collected too much events" as the `FlushTheEventsTask` has an Internet Connectivity test in it and [if it determines it's not connected it simply returns and keeps the event data in RAM memory](https://github.com/mapbox/mapbox-gl-native/blob/cee1b0b526dbec0dea9c4daaac94f333395062e2/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java#L535-L541).

> flush some part of events to flash, while offline.

Yep, in the future we want to be able to better handle Offline but that will entail persisting data to disk which will involve encrypting the data for privacy and security reasons.  For now though, let's remove the Network Check and bump the flush time to 3 minutes to mirror how iOS is handling this.

**Comment by bleege** [comment]
I ended up doing 2 things to address this issue in the short term.  The first was to bump the flush time to 3 minutes to mirror iOS as well as reduce the potential maximum number of network calls from 30 per hour to 20 per hour.  The second was to still keep the Network Connectivity check to prevent unnecessary attempts to send data when it's not possible (aka save battery life), but add the instruction to remove all previously stored events in memory to keep the `OutOfMemory` situation that @vkurchatkin describes from happening.  This dispatching of data also mirrors the iOS approach that @boundsj describes.

**Comment by bleege** [comment]
Encapsulated the clearing of the events queue to `finally` block to ensure that it'll get cleared out on every HTTP attempt per @vkurchatkin suggestion.

Tested, Rebased, Merged.

Thanks again for everything @vkurchatkin!  :rocket:
