### ISSUE TITLE
[ios] black screen with offline maps

### ISSUE THREAD

**Issue by rsimenok** [mapbox/mapbox-gl-native#4643]
iOS
MapBox 3.2.0

Hello, i have problems with downloading offline package.

Firstly I hope i check right if offline pack available, because if i had offline pack i don't need to download it again.
```Objective-C
if ([[MGLOfflineStorage sharedOfflineStorage] packs].count == 0) {
    NSLog(@"START OFFLINE PACK DOWNLOAD");
    [[YMapDownloader downloader] startOfflinePackDownload];
}
```

```YMapDownloader``` is my ```NSObject```, where i put code from official [example](https://www.mapbox.com/ios-sdk/examples/offline-pack/), here is full code of [my class](https://gist.github.com/rsimenok/9a2db13fd8bf7e6111b0cd448a31b327)

how i create region
```Objective-C
CLLocationCoordinate2D sw = CLLocationCoordinate2DMake(32.147344404778963, -64.89344945400417);
CLLocationCoordinate2D ne = CLLocationCoordinate2DMake(32.471673244603323, -64.643860247099894);
    
id <MGLOfflineRegion> region = [[MGLTilePyramidOfflineRegion alloc] initWithStyleURL:nil
                                                                              bounds:MGLCoordinateBoundsMake(sw, ne)
                                                                       fromZoomLevel:9.8
                                                                         toZoomLevel:20.0];
```

so when i call ```startOfflinePackDownload``` i start downloading
```
// Start downloading.
[pack resume];
```
But i don't get any notification about progress, even no ```NetworkActivityIndicator``` in status bar.
After i don't see any activity i try to open map and it was black, i mean black screen, no map. When i commented pack downloading, recompile app and open map i start get warnings:
```
Unable to make space for entry
2016-04-08 02:11:54.316 MyApp[420:64640] [WARNING]
```
so as i understand it's connected #4411 

### Steps to trigger behavior

Use code from [example](https://www.mapbox.com/ios-sdk/examples/offline-pack/) but with this region:
```Objective-C
CLLocationCoordinate2D sw = CLLocationCoordinate2DMake(32.147344404778963, -64.89344945400417);
CLLocationCoordinate2D ne = CLLocationCoordinate2DMake(32.471673244603323, -64.643860247099894);
    
id <MGLOfflineRegion> region = [[MGLTilePyramidOfflineRegion alloc] initWithStyleURL:nil
                                                                              bounds:MGLCoordinateBoundsMake(sw, ne)
                                                                       fromZoomLevel:9.8
                                                                         toZoomLevel:20.0];
```

### Expected behavior
Downloaded offline pack.

### Actual behavior
No pack downloaded.

**Comment by 1ec5** [comment]
Where are you checking the number of packs? That array is populated asynchronously and may be nil for an undefined period of time after launch. You should register for KVO change notifications on that key path and only start the download when the change kind is NSChangeKindSetting.

The SDK doesn't handle displaying the network activity indicator – your application can manage that.

/cc @friedbunnu

**Comment by rsimenok** [comment]
> Where are you checking the number of packs?

@1ec5 in ```viewWillAppear``` of my initial ViewController. He doesn't contains MapBox map.

**Comment by 1ec5** [comment]
I wonder if that's too soon. Can you check whether packs is in fact nil rather than empty? (The code you posted above doesn't distinguish.) If it's nil, you should try KVO to detect when the packs are discovered. See [MBXOfflinePacksTableViewController](https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.2.0/platform/ios/app/MBXOfflinePacksTableViewController.m) for inspiration.

**Comment by rsimenok** [comment]
@1ec5 not nil...(

![screen shot 2016-04-08 at 11 27 34](https://cloud.githubusercontent.com/assets/2759167/14378382/47aafa6a-fd7d-11e5-9082-f6a287ae3634.png)
I wonder why after ```[pack resume];``` i doesn't get any notifications.

Well i think i found problem.
```Objective-C
[[YMapDownloader downloader] startOfflinePackDownload];
```
```Objective-C
+(YMapDownloader *)downloader {
    return [[YMapDownloader alloc] init];
}
```
YMapDownloader instance dying very fast, so i didn't get notifications, but as i understand pack was loading.
So i take strong ref on YMapDownloader instance and **all is working**, but i get warnings:
```[WARNING] {DefaultFileSource}[Database]: Unable to make space for entry```

And the last question, is it possible to check for packs on application start?

**Comment by 1ec5** [comment]
It isn't possible to check synchronously at application launch, unfortunately.

**Comment by rsimenok** [comment]
@1ec5 Two more question please :)
1) How to get all size of region(all packs)?
2) How to detect if user downloaded all packs for region or no? Or detect if region was downloaded?

**Comment by lethianqt94** [comment]
I have same questions: 
1) How to get all size of region(all packs)?
2) How to detect if user downloaded all packs for region or no? Or detect if region was downloaded?

**Comment by 1ec5** [comment]
1. For each offline pack in MGLOfflineStorage.packs, call -requestProgress. The progress arrives asynchronously, so register for MGLOfflinePackProgressChangedNotification notifications, which come with progress information including the size taken up by the region. You'll need to sum up the sizes yourself.
2. Call -requestProgress on the pack, as above.

See the [offline storage documentation](https://www.mapbox.com/ios-sdk/api/3.2.2/Offline%20Storage.html) for more information about notifications and progress.
