### ISSUE TITLE
Move binding.gyp to platform/node/platform.gyp

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#4646]
For consistency with the other platforms, `binding.gyp` should be named `platform/node/platform.gyp`. Does node-gyp / node-pre-gyp support this?

If not, `binding.gyp` could be a stub that just includes `platform/node/platform.gyp`.

**Comment by mikemorris** [comment]
I originally wanted to do this but ran into upstream issues (I think the problem was actually in npm, not node-gyp, IIRC was related to https://github.com/npm/npm/issues/8411)

**Comment by jfirebaugh** [comment]
👍  This isn't at all essential, so closing.
