### ISSUE TITLE
are classes still supported?

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#4657]
If not, the documentation at https://github.com/mapbox/mapbox-gl-native/blame/master/platform/node/README.md#L66 and the Node.js bindings support in https://github.com/mapbox/mapbox-gl-native/blob/master/platform/node/src/node_map.cpp#L235-L242 should be removed.

**Comment by jfirebaugh** [comment]
They're still supported in core. Let's keep this around for now.
