### ISSUE TITLE
Raster tiles offline from sdcard or internal storage

### ISSUE THREAD

**Issue by NasH5169** [mapbox/mapbox-gl-native#4660]
Hi all,

I'm coming from legacy/deprecated Android SDK.

I'm discovering Android SDK for MapBox GL.

I've seen that it is possible to use raster tiles by using json file like:

```
{
  "version": 8,
  "name": "Raster Tiles",
  "sources": {
    "yourTileLayer": {
      "type": "raster",
      "tiles": [
        "http://a.tileserver....../{z}/{x}/{y}.png"
      ],
      "tileSize": 256
    }
  },
  "layers": [{
    "id": "yourTileLayer",
    "type": "raster",
    "source": "yourTileLayer",
    "paint": {
      "raster-fade-duration": 0
    }
  }]
}
```

But can I use some local tiles (from internal storage or sdcard). I think it is not possible right now. My english skill do not permit me to understand all the issues i've read and to be sure what is it possible or not.

Thanks for helping.

**Comment by jfirebaugh** [comment]
No, it is not possible to supply local tiles for offline usage. Offline depends upon all resources being available in an efficient, central database, and it populates that database by making requests to the source listed in the style.

For potential future "sideloading" features for offline, see #3894.
