### ISSUE TITLE
mapView.setClusteringEnabled() is not available!

### ISSUE THREAD

**Issue by subashsn** [mapbox/mapbox-gl-native#4661]
Hello, I am using Mapbox Android SDK 4.0.0. I am not able to do clustering anymore with mapView.setClusteringEnabled(). 

Has this feature been removed?
Thank you

**Comment by 1ec5** [comment]
Were you previously using the raster Mapbox Android SDK (version 0.7.4 or below)? We rewrote the SDK from the ground up several months ago to support vector tiles and OpenGL-based rendering. The new SDK doesn’t currently support marker clustering, but we do plan to add that feature. Please keep track of #320 for progress updates.
