### ISSUE TITLE
Offline Map Defination

### ISSUE THREAD

**Issue by kevincyh** [mapbox/mapbox-gl-native#4662]
Hi,

I am currently working on an android application using mapbox android SDK 4.0. I want to enquirer on loading the cached map back to the map view. I have downloaded the data using the OfflineManager and the definition using OfflineTilePyramidRegionDefinition. But i was unable to retrieve this save data and load it back to the map when the device is offline from network connection. Any ideas how?

**Comment by jfirebaugh** [comment]
Offline resources are used automatically by your application whenever a map is required at a location and zoom level included in an offline region.

For more information, see the [documentation](https://www.mapbox.com/help/mobile-offline/).

**Comment by kevincyh** [comment]
@jfirebaugh I download the map but when i off my wi-fi close the app and restart it gives me a grey screen.
