### ISSUE TITLE
Loading mbtilies offline (android)

### ISSUE THREAD

**Issue by kevincyh** [mapbox/mapbox-gl-native#4663]
Hi,

Is there any ways i can load mbtilies locally? i have tried using it this way but it seems like its not able to open the file setStyleUrl("assets://test.mbtiles"); 

*using android 4.0 sdk

**Comment by friedbunny** [comment]
Nope, there is currently no way to provide a pre-populated offline database. See https://github.com/mapbox/mapbox-gl-native/issues/3894 for future plans.
