### ISSUE TITLE
API.Offline is flaky on Bitrise OS X

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#4665]
```
[ RUN      ] API.Offline
make: *** [test-osx] Segmentation fault: 11
```

See https://www.bitrise.io/build/9c38311ed1453d25 for full log.

👀  @jfirebaugh @tmpsantos

**Comment by brunoabinader** [comment]
Caught this also:
```
[ RUN      ] OfflineDatabase.ConcurrentUse
libc++abi.dylib: terminating with uncaught exception of type mapbox::sqlite::Exception: UNIQUE constraint failed: resources.url
make: *** [test-osx] Abort trap: 6
```
Ref: https://www.bitrise.io/build/8731103bc21b6812

**Comment by brunoabinader** [comment]
One more:
```
[ RUN      ] AsyncTask.ThreadSafety
/Users/vagrant/git/test/util/async_task.cpp:125: Failure
Expected: (count) > (1), actual: 1 vs 1
[  FAILED  ] AsyncTask.ThreadSafety (47 ms)```
Ref: https://www.bitrise.io/build/0a43b6b55c4a457c

**Comment by jfirebaugh** [comment]
> make: *** [test-osx] Segmentation fault: 11

For this one, we need to get a stack trace. For linux, we do this via running under scripted gdb. @ansis was working on something similar for OS X / lldb.

> libc++abi.dylib: terminating with uncaught exception of type mapbox::sqlite::Exception: UNIQUE constraint failed: resources.url

This one is #4422.

> /Users/vagrant/git/test/util/async_task.cpp:125: Failure
> Expected: (count) > (1), actual: 1 vs 1

[Famous last words](https://github.com/mapbox/mapbox-gl-native/blob/5471122079b9e882917c148fa443024d3918ddec/test/util/async_task.cpp#L123-L124)

**Comment by jfirebaugh** [comment]
Looks like the lldb that comes with Xcode does not support `-batch` or `--batch` (if it does, I can't find any documentation -- it's not listed, e.g. [in the man page](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/lldb.1.html)).

Another approach would be to `cat` the most recently created file in `~/Library/Logs/DiagnosticReports/` after the crash occurs. @1ec5 does this sound reasonable or is there a better way?

**Comment by 1ec5** [comment]
LLDB is scripted via Python: http://lldb.llvm.org/scripting.html

> Another approach would be to `cat` the most recently created file in `~/Library/Logs/DiagnosticReports/` after the crash occurs.

Sure, that works.

**Comment by jfirebaugh** [comment]
Just saw another one:

> [ RUN      ] Map.Offline
> Assertion failed: (response), function handleResponse, file /Users/vagrant/git/platform/darwin/src/http_request_nsurl.mm, line 122.

**Comment by jfirebaugh** [comment]
> Another approach would be to `cat` the most recently created file in `~/Library/Logs/DiagnosticReports/` after the crash occurs.

This [didn't work](https://www.bitrise.io/build/6a337c01cf0ad38d):

> /bin/sh: line 1:  3120 Segmentation fault: 11  build/osx-x86_64/Debug/test
> ls: /Users/vagrant/Library/Logs/DiagnosticReports/*: No such file or directory
> make: *** [test-osx] Error 1

**Comment by 1ec5** [comment]
Depending on system preferences, the file may reside in ~/Library/Logs/DiagnosticReports/, /Library/Logs/DiagnosticReports/, or another location that I can’t recall off the top of my head.

**Comment by 1ec5** [comment]
It looks like the `lldb` that comes with Xcode 7.x does support `--batch`, [as described here](http://stackoverflow.com/a/26875348/4585461). The fact that it’s undocumented is probably a bug.

**Comment by jfirebaugh** [comment]
Indeed, `--batch` _is_ documented in `lldb --help`. However it has a caveat that makes it useless for this purpose:

```
       -b 
       --batch 
            Tells the debugger to running the commands from -s, -S, -o & -O,
            and then quit.  However if any run command stopped due to a signal
            or crash, the debugger will return to the interactive prompt at the
            place of the crash.
```

I'll look into python scripting, though it also seems to be quite sparsely documented.

**Comment by jfirebaugh** [comment]
Ah:

```
       -k 
       --one-line-on-crash 
            When in batch mode, tells the debugger to execute this one-line
            lldb command if the target crashes.
```

**Comment by jfirebaugh** [comment]
But then there's no way to get lldb to exit with a non-zero exit code (equivalent of gdb's `-return-child-result`).

**Comment by jfirebaugh** [comment]
https://llvm.org/bugs/show_bug.cgi?id=27326

**Comment by 1ec5** [comment]
Could you get lldb to print something special out on a crash and pipe to grep?

**Comment by jfirebaugh** [comment]
I think I've finally cracked it, using core files.

https://www.bitrise.io/build/a215632e27f97a1d

**Comment by jfirebaugh** [comment]
The remaining issues here will likely be resolved with the fix for #4687.

**Comment by 1ec5** [comment]
Is the core file guaranteed to exist? [This build failed](https://www.bitrise.io/build/9333140bd9ad9a40) to find it:

```
error: file specified in --core (-c) option doesn't exist: '/cores/core.3186'
make: *** [test-osx] Error 1
```

**Comment by jfirebaugh** [comment]
One of the tests failed:

```
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Timer.DestroyShouldStop
 1 FAILED TEST
```

Pedantically, there should be a file existence test before the `lldb` command, but since this code only runs if there was a test failure, the build would fail either way.
