### ISSUE TITLE
Mapbox loses CoreLocation Heading Updates when coming back from background

### ISSUE THREAD

**Issue by JThramer** [mapbox/mapbox-gl-native#4668]
**Platform:** iOS 9.3.1 (13E238)
**Mapbox SDK version:** 3.1.0
### Abstract
   While Mapbox is in a `MGLUserTrackingModeFollowWithHeading` tracking mode, backgrounding the app causes the app to lose heading updates.
### Steps to trigger behavior

 1. Build, Install, and run the Mapbox Test app.
 2. Set tracking mode to `MGLUserTrackingModeFollowWithHeading`.
 3. Background the App.
 4. Foreground the App.

### Expected behavior
Expecting to see Mapbox restored to its previous state before backgrounding.
### Actual behavior
Although the tracking mode doesn't change, the map no longer updates its orientation to match the orientation of the phone. Re-toggling the tracking mode fixes the problem.
### Suggested Fix
in `MGLMapView.mm`, Add the following to `wakeGL:` (or do what I did and make a new `handleWake:` method that calls `wakeGL:` and includes the following code:)

```if (self.userTrackingMode == MGLUserTrackingModeFollowWithHeading) {
        [self.locationManager startUpdatingHeading];
    }```

**Comment by 1ec5** [comment]
`-validateLocationServices` is unbalanced: it [stops updating heading](https://github.com/mapbox/mapbox-gl-native/blob/5471122079b9e882917c148fa443024d3918ddec/platform/ios/src/MGLMapView.mm#L3054) but never reenables it, even though it reenables location updates.

/cc @friedbunny

**Comment by JThramer** [comment]
@1ec5 Oh man, thats a _way_ better fix than the one I suggested. Now i'm all self-conscious :P
