### ISSUE TITLE
vertex attrib arrays aren't disabled when VAOs aren't used

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#4681]
`glDisableVertexAttribArray` is never called.

When the vertex array object extension is available (it often is) then attributes never need to be disabled. Attribute enabled/disabled status scoped to VAOs so there is never a need to call `glDisableVertexAttribArray`.

When VAOs are not available, attribute enabled/disabled status is scoped globally. This means that attributes not used by the current shader might be enabled when drawing.

If VAOs aren't present, all attribute indexes not used by the the current shader need to be disabled.

@kkaefer

**Comment by kkaefer** [comment]
Last attempt to implement this is at https://github.com/mapbox/mapbox-gl-native/pull/2038
