### ISSUE TITLE
Change default BUILDTYPE to Debug

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#4683]
`BUILDTYPE` currently [defaults to `Release`](https://github.com/mapbox/mapbox-gl-native/blob/c3bed1dab8ec429d100d383ad93410d1cfaa16fb/Makefile#L1), and I frequently find myself forgetting the `BUILDTYPE=Debug` in `BUILDTYPE=Debug make <platform>` until halfway through the build.

Since in CI `BUILDTYPE` will always be explicitly specified, does anyone object to changing the default to `Debug` for the convenience of running `make` locally?

**Comment by tmpsantos** [comment]
I always only build debug.

**Comment by mikemorris** [comment]
`make node` doesn't seem to respect this (defaulting to `Release` still) and requires calling `npm install --build-from-source --debug` to set `BUILDTYPE=Debug` through `node-pre-gyp`...
