### ISSUE TITLE
Map performance with polylines containing many thousands of points

### ISSUE THREAD

**Issue by akbsteam** [mapbox/mapbox-gl-native#4688]
**Platform:**  iOS9+
**Mapbox SDK version:** ios-v3.2.0-rc1

The application we are developing needs to show historic movement data consisting of hundreds of thousands of points. Performance degrades as the number of points per polyline increases, or the number of polylines increases. What is the best way of improving performance in this instance?

Perhaps somehow baking the polylines into maptiles and including these as additional layers?

(also posted here: http://stackoverflow.com/questions/36438274/map-performance-with-polylines-containing-many-thousands-of-points)

**Comment by sunzhec2702** [comment]
I met the same issue on the Android platform as well. Would you please help to tell me that there is a way to backup my history lines into maptiles?
Thanks a lot.

**Comment by friedbunny** [comment]
[Mapbox Studio](https://www.mapbox.com/studio/) is our solution for managing huge data, generally speaking. You upload your data, [create a tileset](https://www.mapbox.com/help/getting-started-mapbox-studio-1/#tilesets-1), add that tileset to a style, and then use your new style in your native app.
