### ISSUE TITLE
Add Debug Mode Example To TestApp

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#4689]
The ability to test the Map Renderer using the Debug Mode option got lost in the TestApp Refactor shuffle in #4365.

/cc @zugaldia @tobrun @cammace

**Comment by bleege** [comment]
Added a basic MapView with FAB for cycling through the 4 different debug modes.  See screenshots below for what changes at each press:

![device-2016-04-12-163731](https://cloud.githubusercontent.com/assets/989928/14476400/30dfd622-00cd-11e6-9ee2-e073a56a12ac.png)
_Press One - Red Lines_

![device-2016-04-12-163743](https://cloud.githubusercontent.com/assets/989928/14476407/3976b4ae-00cd-11e6-8ffb-bd3cec79e4ed.png)
_Press Two - Tile Number Added_

![device-2016-04-12-163758](https://cloud.githubusercontent.com/assets/989928/14476415/44b9e8d6-00cd-11e6-8883-265ce3ba2bf4.png)
_Press Three - Tile Modified and Expiration Date Added_

![device-2016-04-12-163815](https://cloud.githubusercontent.com/assets/989928/14476429/523767d6-00cd-11e6-884c-f1ecf58978d2.png)
_Press Four - Return To Default State_

**Comment by bleege** [comment]
Added the ability to cycle through the 6 Default Styles while Debug Mode is in different states to be able to test different styles.

Squashed and Merged!

**Comment by zugaldia** [comment]
Thanks @bleege !
