### ISSUE TITLE
[Android] Freeze on zoom out gesture

### ISSUE THREAD

**Issue by mpuchala** [mapbox/mapbox-gl-native#4692]
**Platform: Android**
**Mapbox SDK version: 4.1.0-SNAPSHOT (9)**

### Steps to trigger behavior

 1. Zoom out

### Expected behavior
Zoom out map with no lag

### Actual behavior
Sometimes map doesn't work smoothly

### Comment
My issue is about performance. I'm testing my app on Nexus 4 (quite old device in fact) and on zooming out (using two fingers gesture) sometimes there is a lag/freeze. Below there is info from logcat:

```InputDispatcher: Window 'Window{39f5bb3 u0 ...}' spent 6487.6ms processing the last input event: MotionEvent(deviceId=6, source=0x00001002, action=2, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, edgeFlags=0x00000000, xPrecision=2.0, yPrecision=2.0, displayId=0, pointers=[0: (589.5, 851.0), 1: (150.5, 614.0)]), policyFlags=0x62000000```

I'm setting my own ``onTouchListener`` but problem occurs without it as well. 
It's not a critical issue but would be nice to avoid it for better performance (I haven't recreated it on zoom in event so I'm not sure if it happens then). From my observation it's easier to see it on smaller zoom value like 8 and below (maybe it's about downloading map or sth and only logs here?).

**Comment by jfirebaugh** [comment]
Tracking in #4777
