### ISSUE TITLE
Android Point Clustering Implementation

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#4693]
[Point Clustering in the native SDKs](https://github.com/mapbox/mapbox-gl-native/issues/320) is going to make use of @mourner's [Supercluster work from GL JS](https://www.mapbox.com/blog/supercluster/).  The [Supercluster library will be first ported to Core GL in C++](https://github.com/mapbox/mapbox-gl-native/issues/320#issuecomment-197048565) and then the Android bindings will be written on top to expose it for use in the Mapbox Android API.  An example activity will also be created in the Android TestApp for development and general demonstration purposes.

@mapbox/mobile @twbell

**Comment by tobrun** [comment]
Linking #320

**Comment by shfishburn** [comment]
When is this going to be implemented for the iOS SDK and released?

**Comment by twbell** [comment]
@shfishburn working on timing now; forthcoming.

**Comment by shfishburn** [comment]
UGH

**Comment by 1ec5** [comment]
@shfishburn, we’re planning to tackle this on both platforms roughly in tandem. Both SDKs are blocked on support at the core, cross-platform level, however. We’re tracking that work in #320.

**Comment by shfishburn** [comment]
Assuming the architect of an iOS or Android client implements a lazy loading pattern for POIs to be displayed in a list or map view, then the need to cluster markers at the scope of (say) North America is a bit of overkill (IMHO). Don't think a bit circle with a massive integer is necessary over the United States to inform a user "there be dragons here." That's not a great user experience. I understand doing this work in the core and in tandem, but "forthcoming" and "soon" are variables that contribute to difficult decision on allocating resources and just doing something outside the MapBox SDK.

**Comment by 1ec5** [comment]
This is a little off-topic for this issue, but lazily loading annotations is somewhat orthogonal to clustering. The Android and iOS SDKs already allow you to add and remove annotations/markers relatively efficiently. #4694 would make it easier for you to know when to add or remove an annotation. Or is https://github.com/mapbox/mapbox-gl-native/issues/320#issuecomment-197049642 still representative of what you’re hoping to accomplish? As demonstrated in [this blog post](https://www.mapbox.com/blog/supercluster/), Supercluster can also be useful for heat map–style visualizations in addition to traditional, numbered clustering.

**Comment by shfishburn** [comment]
Lazy loading is appropriate even with clustering in very high density, ubran areas. Think of Manhattan where it takes almost a street level zoom on the map to de-cluster and present discrete markers that represent the POIs. Smart, lazy loading based on certain conditions along with clustering is generally our approach because of density. Yes, #320 is what we're trying to accomplish. 

By the by numbered clustering is not our fave. We've implemented something in a prior version of our platform called dots and markers. It works well but the port from Google Maps to Mapbox is quite an effort. Perhaps we should get started :)

**Comment by subashsn** [comment]
Please add this feature soon! Faced too many issues with legacy sdk, so using googleMaps for now :/

**Comment by AAverin** [comment]
Just started developing a new app and was surprised to find out that clusters are not yet supported.
Will be definitively waiting for this feature to appear.

**Comment by abhinav-adtechs** [comment]
Waiting desperately for this feature to be added ASAP! 
Please give an ETA.

**Comment by shfishburn** [comment]
Mapbox has gone dark on a date.

**Comment by twbell** [comment]
@shfishburn, @abhinav-adtechs, @AAverin:

@bleege's [notes in his OP](https://github.com/mapbox/mapbox-gl-native/issues/4693#issue-148093104) are still valid.  In absolute terms we are working on the Core GL work for this feature now, and you'll see the capability expose in the Next +1 Release: iOS 3.4/Android 4.2.  We are targeting Q3 for this feature, so somewhere in the July/August timeframe.

A broader note on timing and release dates: we do not post a Release Date until we can be fairly confident of hitting it; this usually means that the release is fully scoped and the necessary research is completed.  We've all been on the receiving end of delayed releases, so we're trying to avoid being overly optimistic.  I appreciate that the other end of the spectrum is opacity, which is equally unhelpful, so I'll work more to give what guidance we can as soon as we can give it.

**Comment by 2ndGAB** [comment]
Hello,
Just to give my 2 cents because I'm using clustering on Android and I'm very interesting to get it on iOS, clustering goal is not to hide markers/annotations but to reduce their number in high annotations density areas.

I mean, as Google Map API does, it's necessary to define a minimal number of annotations to cluster (by default 5 for example) to prevent to have to deeply zoom an area to see just 2 annotations close together.

**Comment by zugaldia** [comment]
Support for clustering via a GeoJson source has been brought to Android in https://github.com/mapbox/mapbox-gl-native/issues/5852. The equivalent iOS approach (via a `MGLGeoJSONSource`) was done in https://github.com/mapbox/mapbox-gl-native/issues/5962.

We've also published a sample [`CreateHeatmapPointsActivity`](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/CreateHeatmapPointsActivity.java) that shows how to use this new API:

![ezgif com-video-to-gif 3](https://cloud.githubusercontent.com/assets/6964/18673008/439b264e-7f18-11e6-8497-ef4a4e740061.gif)

Closing this now as all tasks listed in OP have been completed.

**Comment by 1ec5** [comment]
Also note #5814 and #5815 in case you need interactivity.

**Comment by vikoo** [comment]
@1ec5 How to get the geo points from cluster click? Do you have any example for this?

**Comment by 1ec5** [comment]
@vikoo, [the Android demo repository](https://github.com/mapbox/mapbox-android-demo/) would be the place to look for examples. mapbox/mapbox-android-demo#560 might be of interest to you.
