### ISSUE TITLE
Automatically query point annotations in region when region changes

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#4694]
Along the lines of #4384, mbgl should automatically call `Map::getPointAnnotationsInBounds()` within the visible region whenever the region changes and include the resulting annotation IDs in the region change notification. The query would only take place if client code registers for it somehow.

This additional context would greatly speed up tooltip and cursor rect calculations in the OS X SDK. It would also be important for implementing annotations as native views (#1784, #3276) while still relying on `mbgl::AnnotationManager` to manage the locations of those views.

Per https://github.com/mapbox/mapbox-gl-native/issues/4693#issuecomment-209520787, it might also be desirable for the SDK to optionally expose this information in its delegate callbacks, to allow the developer to lazily load information related to the current viewport.

/cc @tobrun @boundsj

**Comment by jfirebaugh** [comment]
What's the advantage to including annotation IDs in the region change notification, versus calling `getPointAnnotationsInBounds()` from a change notification handler? I would prefer not to couple map notifications and annotations.

**Comment by 1ec5** [comment]
I just realized there would be no benefit to the iOS SDK, since `AnnotationManager` runs on the main thread rather than the Map thread. For the Android SDK, the advantage would be fewer trips across the JNI boundary, although I suppose jni.cpp could manage calling `getPointAnnotationsInBounds()` itself. @tobrun, does this sound feasible to you?

The performance hit I’ve been seeing in the OS X SDK with tooltip and cursor rects will manifest itself with native annotation views, but we’ll have to address that issue in other ways.

**Comment by jfirebaugh** [comment]
Per discussion, we can start out by relying on notification handlers to call `getPointAnnotationsInBounds()`, and optimize when profiling reveals that to be a bottleneck.
