### ISSUE TITLE
Add version argument to class members of Style, deprecate older ones

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4702]
> ~~Add a version argument to the Style class members. Each member documentation would say what the current latest version is, “as of” a certain date. Deprecate the unversioned methods.~~

**Update**:

For iOS:
> Add a version argument to the MGLStyle class methods. Each method’s documentation would say what the current latest version is, “as of” a certain date. Deprecate the unversioned methods.

For Android:
> Use same system as iOS, deprecate old `Style.java` class. 

In line with deprecation of the Emerald style in #4577 .

**Comment by jfirebaugh** [comment]
For Android, we should switch to a function-based approach like iOS: `Style.mapboxSatelliteStyleURL(int version)`. That way we don't have to modify `Style` for each new style version release.

**Comment by tobrun** [comment]
@jfirebaugh thank you for the input, 
I updated the requirements above and divided them in `iOS` and `Android` specifically.

**Comment by 1ec5** [comment]
Style URL APIs are getting versioned in the iOS and OS X SDKs in #4759.

**Comment by tobrun** [comment]
@1ec5 great, 
I will create a branch from #4759 and create a PR to get the Android changes in the same PR.
