### ISSUE TITLE
Devices without a magnetometer

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4703]
I noticed while developing on a 80 dollar device that cheaper devices not always have magnetometer. We currently use this with `UserLocationView` in combination with `MyBearingTracking.Compass` to determine the position of the device versus the map. In those cases I would suggest not showing the drawable with the arrow. (it currently always points up).

**Comment by vacxe** [comment]
@tobrun In addition, im 3 years ago developing on device without GPS. Only A-GPS. It's been cheaper china device, when "OK" button was translated to "Oklahoma". Siriously. Cancel and Oklahoma button...

**Comment by vacxe** [comment]
@tobrun for cheap device without accelerometer we can use bearing from gps Location. For feature navigation in map. I mean that better have not the best feature, than have nothing.

**Comment by tobrun** [comment]
@vacxe thank you for reaching out and contributing. I will have 👀  on this after I finish up some other, more prioritised, work first. FWIW Already some feedback on this is that I was seeing  `mLastMagnetometerSet` was never set to true during debugging.

**Comment by vespakoen** [comment]
Actually, using the GPS for determining the bearing is far more reliable then using the magnetometer,
I attached my phone to a scooter (vespa) and the vibrations (and/or maybe other factors) make the magnetometer go crazy.

I noticed google maps actually uses the GPS in stead of the magnetometer (maybe when the speed is higher than some value?)

Anyways, I was going to open an issue for being able to choose GPS for determining the bearing. It works a lot better on motorcycles.

**Comment by vacxe** [comment]
@tobrun maybe use smoothing filter? For example Kalman?

**Comment by cammace** [comment]
@vespakoen: You should be able to use `mapboxMap.getTrackingSettings().setMyBearingTrackingMode(MyBearingTracking.GPS);`  for GPS bearing tracking.

@tobrun we've been making changes to how we handle the user bearing tracking including changing the sensor type to fusion (see https://github.com/mapbox/mapbox-gl-native/issues/5861) Is this still an issue?

**Comment by tobrun** [comment]
Did some google searches around the configuration we currently use `TYPE_ROTATION_VECTOR`. It seems that this sensor returns null when a device doesn't have a magnetometer (but has an accelerometer/gyroscope). The code is currently not optimised to handle sensors not being available so I think this is still relevant.
