### ISSUE TITLE
Drop support for armv7s?

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#4704]
We should consider dropping support for the `armv7s` architecture and measuring the impact on iPhone 5 devices. Based on what I’m seeing in #4641, I believe omitting support for this architecture (by setting `ARCHS=$(ARCHS_STANDARD)`) will contribute to a significant reduction in the built framework’s size and shave a bit of time off the build.

Major iOS frameworks have already dropped support for `armv7s`. As noted in [this PSPDFKit knowledge base topic](https://pspdfkit.com/guides/ios/current/usage-issues/about-armv7s-support/), Apple no longer requires or encourages building for that architecture, which is only applicable to iPhone 5 and 5c. Those models will fall back to the `armv7` slice, which may be slower with floating-point-heavy operations.

/cc @mapbox/mobile

**Comment by bleege** [comment]
Man, I'm so envious of a single hardware OEM business model.  :smile:

**Comment by friedbunny** [comment]
I ran the bench target in #4641 on my iPhone 5, five times per architecture:

| | `armv7`  | `armv7s`  |
|---|:---:|:---:|
| Avg FPS | 58.7  | 59.1  |

[Raw benchmark results here.](https://gist.github.com/friedbunny/e5f94a5245835c9d739c4b3fbad18750)

**Comment by friedbunny** [comment]
Just realized the `armv7` tests were run with a debug build (the default) of core, while `armv7s` was release — will rerun `armv7` in release.

**Comment by friedbunny** [comment]
The initial 0.4 FPS gap looks like it can be attributed to the debug/release mistake, as the rerun tests indicate there is effectively no difference. 👍

**Comment by kkaefer** [comment]
Let's do this!
