### ISSUE TITLE
Custom Layer add pixelmatrix and projectionmatrix to CustomLayerRenderParameters

### ISSUE THREAD

**Issue by mozinator** [mapbox/mapbox-gl-native#4720]
When drawing items to a custom layer I have to recalculate the projection matrix and pixelmatrix based on the parameters passed by CustomLayerRenderParameters.

It would be much easier if the pixelmatrix and projectionmatrix are passed as a float array. Which I can convert to a GLKMatrix4 on iOS.

I think the change would be fairly easy but helps a lot with custom drawing on a map.
in types.h @ CustomLayerRenderParameters add 
float[16] pixelmatrix
float[16] projectionmatrix

and in custom_layer.cpp
void CustomLayer::render(const TransformState& state) const {
pass the pixelmatrix and projectionmatrix to the CustomLayerRenderParameters from transform state.

**Comment by mozinator** [comment]
I made a pull request for this:
https://github.com/mapbox/mapbox-gl-native/pull/4732

**Comment by jfirebaugh** [comment]
Closing; see https://github.com/mapbox/mapbox-gl-native/pull/4732#issuecomment-223108134.
