### ISSUE TITLE
Proguard configuration for 4.1.0 release

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4727]
Ticket to track the proguard configuration for the `4.1.0` release.
Proguard related issues from during development can be added to this ticket in the meantime.

**Comment by tobrun** [comment]
When I enable proguard in testapp and make a release build:

![screen shot 2016-05-31 at 18 15 37](https://cloud.githubusercontent.com/assets/2151639/15681970/b9131be4-275b-11e6-9a70-a47804cbbe7e.png)

**Comment by tobrun** [comment]
I was able to build a signed apk when I added:

```java
-keep class com.google.**
-dontwarn com.google.**
```

This resulted in:
![Uploading Screen Shot 2016-05-31 at 18.30.18.png…]()

**Comment by tobrun** [comment]
Since the fix shown above only impacts test app, I'm creating a PR from master instead of `4.1.0-release`

**Comment by bleege** [comment]
The TestApp is part of the release so the commit has been cherry picked over to the release branch.
