### ISSUE TITLE
App Store upload fails 

### ISSUE THREAD

**Issue by Ramshandilya** [mapbox/mapbox-gl-native#4729]
**Platform: iOS**
**Mapbox SDK version: 3.2**

I added the SDK using the dynamic framework package, and added to the project as Embedded Binary.
The SDK works perfectly.
But I encounter this issue when I upload to AppStore,

<img width="1047" alt="screen shot 2016-03-30 at 4 54 37 pm" src="https://cloud.githubusercontent.com/assets/2031908/14600655/7bb7825a-057b-11e6-9a5b-5bef9454eaca.png">

Any idea what I'm doing wrong?

Thanks in advance.

**Comment by mozinator** [comment]
You forgot the buildphase that strips the mapbox framework from the i386 and x86_64 architecture. See 
![screen shot 2016-04-18 at 13 21 56](https://cloud.githubusercontent.com/assets/57530/14602496/92c23e30-0568-11e6-9579-a80e47ec76e7.png)

**Comment by Ramshandilya** [comment]
Hi @mozinator, 
Thanks for the quick reply.
I did indeed add the script, but the project doesn't build and throws me an error like so - 
> /Users/ramsundar.narayanan/Library/Developer/Xcode/DerivedData/AppName/Build/Intermediates/ArchiveIntermediates/AppName/BuildProductsPath/Release-iphoneos/AppName.app/Frameworks/Mapbox.framework/strip-frameworks.sh: No such file or directory

**Comment by 1ec5** [comment]
@Ramshandilya, how did you install the SDK? Manually, or via a package manager like Fabric or CocoaPods? If you installed it manually, which ZIP file did you download from the release page?

**Comment by Ramshandilya** [comment]
I did it manually. Using the **mapbox-ios-sdk-3.2.0-dynamic.zip**

**Comment by Ramshandilya** [comment]
@1ec5 Any pointers to where I'm going wrong?

**Comment by Ramshandilya** [comment]
@1ec5 @mozinator Thanks for the help! I tried again with the build phase script, and it worked.
