### ISSUE TITLE
Output from builds in Xcode is not going to build directory

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#4738]
From a clean checkout, I ran `make xproj` and then built the `osxapp` target. I expected derived data to go to `build/osx-x86_64`, but instead it's going to `~/Library/Developer/Xcode/DerivedData/osx-boomqfdljdofupbolhbelbzoedvb`.

cc @1ec5

**Comment by 1ec5** [comment]
Looks like there’s no real way to force a workspace’s derived data settings for all users. I tried sharing the settings, but Xcode isn’t recognizing the shared settings. You can go to File ‣ Workspace Settings, change Derived Data to “Workspace-relative Location”, and set the location to `../../build/DerivedData`.

**Comment by jfirebaugh** [comment]
Can we force it on a per-target basis?

**Comment by 1ec5** [comment]
Unfortunately, no. There’s a “legacy” setting in Workspace Settings, but even that is per-user. I haven’t looked into whether upgrading the projects from 3.x format to 6.x format would help, but gyp is generating 3.x projects anyways.

**Comment by 1ec5** [comment]
A hacky way would be to copy our desired WorkspaceSettings.xcsettings to a path based on the current user name at the end of the make rule.

**Comment by jfirebaugh** [comment]
> A hacky way would be to copy our desired WorkspaceSettings.xcsettings to a path based on the current user name at the end of the make rule.

I think it would be worth doing that. We rely on getting build output to `build` so that command line and Xcode builds share the same output, and `make clean` works as advertised.

**Comment by jfirebaugh** [comment]
Related: can we flip `OSX_DERIVED_DATA_PATH = build/DerivedData/osx` in the Makefile to `build/osx-x86_64/DerivedData`, or even simply `build/osx-x86_64`, keeping it consistent with other output for the platform?

**Comment by 1ec5** [comment]
> Related: can we flip `OSX_DERIVED_DATA_PATH = build/DerivedData/osx` in the Makefile to `build/osx-x86_64/DerivedData`, or even simply `build/osx-x86_64`, keeping it consistent with other output for the platform?

If we do that, Xcode will never match `xcodebuild`, because Xcode puts the name of the workspace there. I guess we could rename the workspace. Note that `build/ios/` (used by package.sh) also doesn’t match `build/ios-all` (used by gyp).

If the DerivedData folder differs between iOS and OS X builds, iOS and OS X builds in Xcode also won’t share a ModuleCache. I’m not sure how much of an impact that would have on build times.

**Comment by jfirebaugh** [comment]
I'm fine with changing the gyp output to unsuffixed `osx` and `ios`, if that would help. I don't think having `-x86_64` and `-all` respectively tacked on there is essential.

cc @kkaefer

**Comment by jfirebaugh** [comment]
After #4744, switching between command line and Xcode builds still results in some things getting rebuilt. But not everything. Closing here in the name of progress.
