### ISSUE TITLE
Custom marker not easy to click

### ISSUE THREAD

**Issue by vruc** [mapbox/mapbox-gl-native#4747]
Using Mapbox Android SDK

**Mapbox SDK version:** 4.0.0

I'm developing a tracker app, which requires to update the same marker indicates user's home location. 

When I use custom marker icon, I find it not easy to click the marker, but If when I use default marker, I can click it 100%. 

Finally I find out if I click the marker inside the default marker area, I can click it 100%, but if I click the marker outside of default marker area, then the custom marker will not response for my click.

This is the compare image to show the size of default marker and my custom marker.
![Image of Markers](https://bytebucket.org/vruc/gradle_example/raw/d29d5c58f3e4d8e5b17118ef96845775b9527614/Screenshot_20160419091413.png)

Thanks in advance

**Comment by tobrun** [comment]
@vruc 
Thank you for reaching out and reporting your problem. With the `4.0.0` version of the library the touch area was not dynamically calculated, we just added a fixed padding to the xy coordinates returned from onTouch listener. With the upcoming `4.1.0` release we tried improving this experience by taking in account the width/height of the used icons. 

You can read more about this in https://github.com/mapbox/mapbox-gl-native/issues/3643.

**Comment by vruc** [comment]
@tobrun 
Thanks for your answer, I am look forward to the new version 4.1.0.

**Comment by tobrun** [comment]
If you like you can test out the `4.1.0` version through our [SNAPSHOT](https://www.mapbox.com/android-sdk/#gradle). Reach out if you have any other questions or remarks. Closing this issue as this will be handled in `4.1.0`.
