### ISSUE TITLE
Memory leak when using LocationServices

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4748]
![device-2016-04-19-165434](https://cloud.githubusercontent.com/assets/2151639/14643637/7449f1c2-064f-11e6-829a-acbd4230f4b0.png)

Code used in that Activity:

```java
        LocationServices locationServices = LocationServices.getLocationServices(this);
        locationServices.addLocationListener(this);
        locationServices.toggleGPS(true);
```

I'm guessing that I need to explicilty remove the listener. 
Adding a note here that if prior is a requirement we should reflect that in the javadoc.

**Comment by bleege** [comment]
> I'm guessing that I need to explicilty remove the listener. 

Correct.  `LocationServices` is a static class that lives throughout the lifecycle of the app, not just an Activity.  If apps make use of it for GPS data they'll want / need to remove their listener classes when they're doing using it in an activity.  Another option is for apps to use access Location data directly themselves using the Android Location API and not use `LocationServices`.

**Comment by bleege** [comment]
@tobrun Is it okay to close this ticket?

**Comment by tobrun** [comment]
@bleege I added some javadoc in 	de16237 indicating to explicitly remove the listener in javadoc based on some javadoc from [broadcast receivers](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/content/BroadcastReceiver.java) (component which has the same requirement). If that lands we can close this ticket 😉

**Comment by bleege** [comment]
Yep, always a good idea to have the code clean up after it self.  👍
