### ISSUE TITLE
updatePointAnnotation is not implemented on iOS

### ISSUE THREAD

**Issue by mozinator** [mapbox/mapbox-gl-native#4749]
On android updatePointAnnotation is implemented as updateMarker. There is no implementation for updatePointAnnotation on iOS.

![screen shot 2016-04-19 at 16 56 56](https://cloud.githubusercontent.com/assets/57530/14643739/d3ba2bb8-064f-11e6-8b27-af9e5cc23377.png)

**Comment by friedbunny** [comment]
This is happening in https://github.com/mapbox/mapbox-gl-native/pull/3835.
