### ISSUE TITLE
PointAnnotation extra symbol properties

### ISSUE THREAD

**Issue by mozinator** [mapbox/mapbox-gl-native#4751]
PointAnnotation is rendered as a symbol layer. 
A symbol layer has many attributes. 
It would be nice to be able to pass these attributes via the iOS and Android API.
For instance this would make it possible to rotate an annotation.

**Comment by boundsj** [comment]
Hi @mozinator platform annotation views for iOS is tracked in https://github.com/mapbox/mapbox-gl-native/issues/1784. The Android analog is tracked in https://github.com/mapbox/mapbox-gl-native/issues/3276. Platform annotations will allow for using existing platform APIs for things such as rotation animations.  

Work has started for the implementations on both platforms so please monitor those tickets for updates.
