### ISSUE TITLE
BaseMarkerOptions.java breaks NativeScript compatibility

### ISSUE THREAD

**Issue by EddyVerbruggen** [mapbox/mapbox-gl-native#4761]
Hi folks,

Since Mapbox for Android 4.0.0 the annotation logic has been partially moved to a new `BaseMarkerOptions` superclass. This class has a [`title` property](https://github.com/mapbox/mapbox-gl-native/blob/f3c64a4c95947768fd9a695744f9fe0965134c55/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerOptions.java#L19) as well as a [`title` setter](https://github.com/mapbox/mapbox-gl-native/blob/f3c64a4c95947768fd9a695744f9fe0965134c55/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/BaseMarkerOptions.java#L32).

I understand why it was changed in the way it is, but it breaks using markers for the [Mapbox NativeScript plugin](https://github.com/EddyVerbruggen/nativescript-mapbox) as the NativeScript runtime can't distinguish the property from the setter.

**Platform:** Android (NativeScript)
**Mapbox SDK version:** 4.0.0

### Steps to trigger behavior

Please check [my description in the NativeScript issue tracker](https://github.com/NativeScript/android-runtime/issues/424) for a way to reproduce this in a NativeScript app.

### Possible solution

We don't need the current setters like `title(..)` removed, but we'd be very much helped if regular Java setters like `setTitle` are added to `BaseMarkerOptions.java`. Until that's added I'm afraid we can't update the Android version of our plugin.

**Comment by bleege** [comment]
@EddyVerbruggen I think this is doable as our primary concern is to be API compatible at the [`MarkerOptions` level with the Google Maps API](https://developers.google.com/android/reference/com/google/android/gms/maps/model/MarkerOptions#public-method-summary).  We can create convenience wrapper methods for `position`, `snippet`, `title`, and `icon` called `setPosition()`, `setSnippet()`, `setTitle()`, and `setIcon()`.

Is there any other API breakages that you know of now or is `BaseMarkerOptions` the only one?

/cc @rdlauer @tobrun @cammace @zugaldia

**Comment by EddyVerbruggen** [comment]
Hey @bleege thanks for taking note! AFAIK `BaseMarkerOptions` is the only problem for us.

**Comment by EddyVerbruggen** [comment]
Hey @bleege thanks for taking note! AFAIK `BaseMarkerOptions` is the only problem for us.

**Comment by bleege** [comment]
@EddyVerbruggen I just created some wrappers for this and submitted PR #5367.  Can you verify that this is what you'll need?  If so @zugaldia can work with you to get this into the next `4.1.0` build.  Thanks!

**Comment by zugaldia** [comment]
@EddyVerbruggen we've now merged @bleege's PR into the release branch. You can expect a release candidate tomorrow or early next week that you can use to test the fix. Thanks again for your feedback.

**Comment by EddyVerbruggen** [comment]
Looks good guys, I'll check the RC shortly, thanks!

**Comment by zugaldia** [comment]
@EddyVerbruggen We release `beta3` yesterday, feel free to give it a test https://github.com/mapbox/mapbox-gl-native/issues/5415

**Comment by bleege** [comment]
Awesome!  Thanks for making this happen @EddyVerbruggen @zugaldia!  I'm excited about getting the Cordova and NativeScript plugins back up to the latest code!  🚀

**Comment by EddyVerbruggen** [comment]
@bleege @zugaldia I waited a bit for 4.1.0 and had a great time implementing some new features for the [NativeScript plugin](https://github.com/EddyVerbruggen/nativescript-mapbox) today. Your setters worked perfectly, thanks a LOT!

The next thing I'll be adding is offline maps support, and then give the Cordova plugin some love.

**Comment by bleege** [comment]
@EddyVerbruggen That's great to hear!  Thanks so much for your work keeping the NativeScript and Cordova plugins up to date!  🚀
