### ISSUE TITLE
Unable to build `glfw-app` in OS X

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#4765]
Commit https://github.com/mapbox/mapbox-gl-native/commit/a883ac9253f19a850fe9d60e5479428cfc8fb54d breaks `make glfw-app` on OSX. This is due to using `build/osx/config.gypi` instead of `build/osx-x86_64/config.gypi` in `platform/osx/platform.gyp`.

Getting rid of `PLATFORM_SLUG` doesn't work because we rely on subplatform to separate build outputs when cross-compiling. We could add a special GYP variable and make it select the include file according to a condition, but that can bloat the buildsystem a bit.

Do you have something else in mind @jfirebaugh? I'm aware `make osx` also build the GLFW binary.

**Comment by jfirebaugh** [comment]
I think we should `make glfw-app` a linux-only target, and use the Xcode project to build it on OS X.
