### ISSUE TITLE
Async glReadPixels() in HeadlessView?

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#477]
Does this make sense or seem worthwhile @kkaefer?

https://www.opengl.org/discussion_boards/showthread.php/144238-asynchronous-readback-that-call-glReadPixels%28%29-with-PBO?highlight=multithread%2A

**Comment by adam-mapbox** [comment]
https://github.com/mapbox/mapbox-gl-native/tree/adam_477_pbo_read_pixels

**Comment by adam-mapbox** [comment]
After talking with @mikemorris , it's not clear that doing `readStillImage` asynchronously is a win for us.  The current context where this is used is already "asynchronous" in a sense; we don't have useful work to do while we wait for the image that we're getting on that thread.

**Comment by mikemorris** [comment]
Tried reimplementing this over in https://github.com/mapbox/mapbox-gl-native/compare/pbo-read-pixels in hopes of alleviating the 1000ms+ GPU hang we've been seeing on `glReadPixels` in the Node.js bindings that permanently stalls *all* renders currently in progress, even on other processes.

This does successfully change `glReadPixels` to happen asynchronously, but the hang is still present - deferred to `glClientWaitSync` if a [fence](https://github.com/mapbox/mapbox-gl-native/commit/d90b5ffe649b89cd1d48c4829469d212d3bf842f) is inserted before `glReadPixels`, or at some other point inside `HeadlessView::readStillImage` if not (didn't have proper logging in place to detect precisely when).

Not sure if this is a hardware or GPU driver issue or if we're just stalling the pipeline somehow. We've been consistently reproducing this on a GRID K520 GPU running version 367.27 of the NVIDIA Linux drivers.

**Comment by tiagovignatti** [comment]
chiming in... are you also seeing the stalls on Intel hardware, @mikemorris?

**Comment by tiagovignatti** [comment]
I tried to track down what's going on but it will require a bit more work. If I switch on debug in Intel Mesa driver it captures the pipeline stall with the following output:
```    Flushing before mapping a referenced bo.```
```    CPU mapping a busy miptree BO stalled and took 0.126 ms.```

That's definitely a problem cause if we have to flush the batchbuffer early that has implications on performance. I'm not seeing other programs dumping anything, so I have to imply that it's a result of a bad stream that mbgl is sending to the hardware.

That said I don't think that changing to use PBO will help anything in this case. Somehow the GPU is stalled on a busy buffer object and another technique of downloading pixels won't help out.

**Comment by mikemorris** [comment]
@tiagovignatti Are you seeing the same ~1 second hang I'm describing above, or is this a possible cause that manifests differently on Intel hardware?

I'm actually not too familiar with the GPU pipeline - is a stall something that could break unrelated in-progress renders or drop previously queued GL calls?

The idea with switch to the async `glReadPixels` was to eliminate the implicit flush - it sounds like there's still a flush happening though, which I think could be from [`glXMakeContextCurrent`](https://www.opengl.org/sdk/docs/man2/xhtml/glXMakeContextCurrent.xml) at https://github.com/mapbox/mapbox-gl-native/blob/5588935412fbf6c62f88d92f4685e517a7bb84c1/platform/default/headless_view_glx.cpp#L116-L126

**Comment by tiagovignatti** [comment]
I don't think this would drop/break previously GL calls. What I am seeing on Intel is subtle stalls in many subtests of ```mbgl-test```, but none of them takes more than 0.3 ms. Still, It might be that we're stepping in the same problem, cause I'd guess that when using discrete GPUs (your case, right?) it takes longer to synchronize the states.

This bug called my attention cause I am seeing really huge stalls (of several seconds!) when running ```mbgl-test``` with software rasterizer, but that seems orthogonal to all of this.
