### ISSUE TITLE
Viewport labeling in mapbox-gl-native

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#4817]
**Platform:All**
**Mapbox SDK version: N/A**
### Steps to trigger behavior

I came across this post on Mapbox blog today. Is the any plan to make it available on publicly available mapbox-gl-native repository?
https://www.mapbox.com/blog/labels-for-navigation/
### Expected behavior

Viewport labeling is available in mapbox-gl-native.
### Actual behavior

Viewport labeling is not available in mapbox-gl-native.

**Comment by yhahn** [comment]
@mb12 working on a branch + PR for GL JS this week and then you can expect a port for native as well. Will post back here once that's up.

**Comment by jfirebaugh** [comment]
This happened.
