### ISSUE TITLE
Background color rendering broken on my machine

### ISSUE THREAD

**Issue by freenerd** [mapbox/mapbox-gl-native#482]
Compiled and got the following zoom level 0 screen:

![screen shot 2014-10-08 at 11 56 19](https://cloud.githubusercontent.com/assets/25713/4557250/6c2f6e54-4ed1-11e4-8cc8-de38137d76a6.png)

Looks like the background image is missing. When I zoom in other things are there:
![screen shot 2014-10-08 at 12 00 08](https://cloud.githubusercontent.com/assets/25713/4557287/e79a8560-4ed1-11e4-8721-caa7f330cf9d.png)

I'm on latest master. Graphics card is NVIDIA GeForce 320M 256 MB

**Comment by jfirebaugh** [comment]
@freenerd - still seeing this?
