### ISSUE TITLE
Enlarge user puck’s accessibility frame

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#4823]
The user puck has the same accessibility frame as the user dot, even though the former appears larger and has a much larger hit target:

![puck](https://cloud.githubusercontent.com/assets/1231218/14777195/7351d6ba-0a80-11e6-9301-1a4ad94f1731.PNG)

/cc @friedbunny

**Comment by friedbunny** [comment]
The frame size comes from `MGLUserLocationAnnotationPuckSize` and `MGLUserLocationAnnotationDotSize`, which we use in `-accessibilityFrame`, too.
