### ISSUE TITLE
Make LocationServices LocationListeners ThreadSafe

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#4829]
The [`locationListeners` Collection in LocationServices](https://github.com/mapbox/mapbox-gl-native/blob/c4089b60bc630ee78c6755ebd7702943a30dd07d/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/location/LocationServices.java#L33) currently uses an ArrayList as it's implementation which is not thread safe.  This can cause `ConcurrentModificationException` especially when working with something like RxAndroid.

```java
java.util.ConcurrentModificationException
     at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
     at com.mapbox.mapboxsdk.location.LocationServices.onLocationChanged(LocationServices.java:130)
```

/cc @tobrun @zugaldia @cammace

**Comment by bleege** [comment]
I originally was going to replace the `ArrayList` with a `Vector` but the JavaDoc for `Vector` said "you should also consider CopyOnWriteArrayList" so I did.  After testing it out it does exactly what's needed, namely ensure that the Location updates in `onLocationChanged()` will always execute without blocking and without the additional overhead of fully synchronized `Vector`.  Will try this way first and if need be can go to using the full `Vector` replacement if this proves problematic.

![screen shot 2016-04-25 at 2 39 54 pm](https://cloud.githubusercontent.com/assets/989928/14796570/aea87cb4-0af3-11e6-9b19-436d39b1bace.png)

**Comment by zugaldia** [comment]
_Roger, Roger. What's our vector, Victor?_

**Comment by tobrun** [comment]
Nice choice on CopyOnWriteArraylist, I did the same for MapChangeListeners with previous release ! :rocket:
