### ISSUE TITLE
Simplify HTTP resource requesting

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#4844]
Currently, the requests we issue to obtain data via HTTP first get an (optional) response served from the cache, no matter whether the data in the cache was expired. They also (optionally) get a second response with data that is always fresh. Instead of having two responses per request, we should always exactly return one response and change the behavior so that the first request is always served from cache (if possible). When the client got a stale resource, it should make a second request with appropriate headers that force a non-stale response.

**Comment by jfirebaugh** [comment]
I don't think I understand the change you're proposing, or what part of HTTP requesting it would simplify. Can you explain again?

**Comment by kkaefer** [comment]
We're currently outsourcing the retry logic into the HTTP source. However, for #123 to work, we need to make the decision of whether to attempt to verify data freshness directly inside the renderer. I'm envisioning this order of attempting to load resources:

![a](https://cloud.githubusercontent.com/assets/52399/15153085/35a472f0-16d8-11e6-8e86-73985a285b84.png)

This would mean that we'll need closer control over the order these requests happen in.

**Comment by kkaefer** [comment]
In particular, cache lookups and HTTP requests need to be decoupled so that we can first do a cache lookup, and once the tile becomes an ideal tile (through zooming), we'll want to go the second step and ensure freshness.

**Comment by kkaefer** [comment]
Blocked by #5023

**Comment by jfirebaugh** [comment]
#5027 implemented what we needed for #5143.
