### ISSUE TITLE
[Support] POI interaction on vector map

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#4848]
Our web team seems to be able to recover information from poi embedded in the map (like train station name etc) thanks to the web js SDK.
I was wondering if it is also a feature you want to implement in the mobile SDK. It would be nice to get a pop up when user tap on metro stations etc. 

We added the keywork "interactive" on the map layer, but we are not sure if it is the way to get interaction with a POI.

**Platform: mobile**
**Mapbox SDK version: latest**

### Steps to trigger behavior

 1. Browse a map 
 2. Tap on a POI (like train station)

### Expected behavior
Get information from the map source 

### Actual behavior
No interactivity available

**Comment by tobrun** [comment]
@RomainQuidet 
This feature is on our Roadmap. The initial version of this feature was created in https://github.com/mapbox/mapbox-gl-native/pull/3172 but was never merged. We now are revisiting that implementation with the improvements landed in JS found in https://github.com/mapbox/mapbox-gl-native/pull/3172.  You can view/verify current progress for the GL counterpart here https://github.com/mapbox/mapbox-gl-native/pull/4656.

Reach out if you have any other questions!
