### ISSUE TITLE
ccache is not working for qt5 build

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#4855]
The qt5 build on Travis consistently takes 11-12 minutes, in comparison to other builds that are typically 3-5 minutes. It appears that this is because ccache isn't working. In the build output:

```
$ ccache --show-stats
cache directory                     /home/travis/.ccache
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                           228
called for link                        3
files in cache                      1986
cache size                         857.7 Mbytes
max cache size                       1.0 Gbytes
```

cc @brunoabinader @tmpsantos

**Comment by tmpsantos** [comment]
That is mostly because of this:
https://github.com/mapbox/mapbox-gl-native/commit/42043599ffca9658d47792a85c136cb2384e35ed

I will have a look tomorrow on how to get ccache running on Travis with Ubuntu Trusty.

**Comment by tmpsantos** [comment]
Argh, there is a typo on the changelog, but in a short Trusty requires root and won't run in a container. 

Limitations are described here:
https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

We need Trusty because the best Qt5 we can get on 12.02 is 5.0 with a PPA and we need 5.2+.

**Comment by jfirebaugh** [comment]
So the issue here is that caching in Travis's trusty beta infrastructure is only available for private repositories. 😭

**Comment by tmpsantos** [comment]
Not running unit tests on the Qt5 bot anymore. The Qt-specific code tested by the unit tests is exactly the same for Qt4. Time dropped to 8 minutes.

![screenshot from 2016-04-27 16-04-52](https://cloud.githubusercontent.com/assets/996307/14853016/62df1f9a-0c92-11e6-8d24-c38aed1d8adf.png)

**Comment by tmpsantos** [comment]
Not sure what happened but it is now taking about 2~3 min. :open_mouth:

**Comment by tmpsantos** [comment]
ccache got enabled it seems

```
cache directory                     /home/travis/.ccache
cache hit (direct)                   173
cache hit (preprocessed)               0
cache miss                             9
called for link                        3
files in cache                       641
cache size                         190.4 Mbytes
max cache size                     512.0 Mbytes
```
