### ISSUE TITLE
Port data-driven styling (property functions) from GL JS

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#4860]
Port data-driven styling from GL JS (see mapbox/mapbox-gl-js#1626). DDS is currently exposed as [property functions](https://www.mapbox.com/mapbox-gl-style-spec/#types-function) in the style specification.

Master list of what's needed. Not necessarily in implementation order.

* [x] Refactor existing `LayoutProperty` and `PaintProperty` classes such that unevaluated and evaluated properties live in separate structures (in progress, @jfirebaugh).
* [x] `gl::Drawable`/`gl::Context` need support for multiple vertex buffers.
* [x] Rename `Function` ⇢ `ZoomFunction`.
* [x] Add `PropertyFunction` and `ZoomPropertyFunction`. Add evaluators for them.
* [x] Add `PropertyFunction` and `ZoomPropertyFunction` as variant types for `PropertyValue`.
  * Might need to split `PropertyValue` into one variant for properties that are known to be feature-constant (undefined, constant, or zoom function) and one for properties that are data-driven (property function or zoom property function).
* [x] Paint properties can no longer be fully evaluated by `Style`. Instead, pass cascaded paint properties into the bucket. Bucket figures out which are feature constant and which are data-driven, producing a `ProgramConfiguration` (or `PaintConfiguration`?). In the `ProgramConfiguration`:
  * constant properties have a `ZoomFunction` which will be evaluated by the main thread and the result bound to a uniform
  * data-driven properties have a vertex buffer
* [x] Decision: for feature-constant properties, should we use `glDisableVertexAttribArray`/`glVertexAttrib*` or dynamically-generated shader uniforms?
* [x] Decision: single "interleaved" vertex buffer for all data-driven paint properties of a layer (requires implementing a custom vector type with runtime-sized elements), or one vertex buffer per data-driven property (can keep using `std::vector`).
* [x] Changing a paint property needs to do a worker round trip (if changing to or from data-driven property or updating a data-driven property), or update the `PaintConfiguration` for each bucket in place (if not).
* [x] Implement support in SDK bindings.

**Comment by nitrag** [comment]
Awesome!

So this will this allow MGLShapeSource parsing (mapbox built-in) to dynamically style a MGLPolyline based on `feature.properties.line-color` from the geojson source?

https://www.mapbox.com/mapbox-gl-js/style-spec/#paint-line-color

**Comment by boundsj** [comment]
Yes @nitrag. Platform specific documentation for iOS and macOS is still being worked on in https://github.com/mapbox/mapbox-gl-native/issues/7924 but you can [check out the examples in the tests](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/test/MGLStyleValueTests.swift#L105) and the [test app](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/app/MBXViewController.m#L1202) today.
