### ISSUE TITLE
Change Location tracking marker design

### ISSUE THREAD

**Issue by kevincyh** [mapbox/mapbox-gl-native#4861]
How do i change the location tracking marker from the first one to the second one you can see on the picture?

Working on android sdk 4.0.
Samsung S5.
![screenshot_2016-04-27-08-48-33](https://cloud.githubusercontent.com/assets/12988766/14838683/44ce6222-0c56-11e6-825e-369e0df5ea19.png)
![done](https://cloud.githubusercontent.com/assets/12988766/14838695/5f2344a8-0c56-11e6-9638-63b67671c376.png)

**Comment by tobrun** [comment]
@kevincyh this feature isn't a part of the public api in `4.0.0` but will be in the `4.1.0` release. In #4396 we fixed multiple bugs related to the user location view and  started to expose api to customise the view itself. You will be able to do this through xml attributes or use the MapboxMapOptions class.

This is what we are thinking to expose:

```
       <!--MyLocation-->
        <attr name="my_location_enabled" format="boolean" />
        <attr name="my_location_foreground" format="reference" />
        <attr name="my_location_foreground_bearing" format="reference" />
        <attr name="my_location_foreground_tint" format="color" />
        <attr name="my_location_background" format="reference" />
        <attr name="my_location_background_tint" format="color" />
        <attr name="my_location_background_left" format="dimension" />
        <attr name="my_location_background_top" format="dimension" />
        <attr name="my_location_background_right" format="dimension" />
        <attr name="my_location_background_bottom" format="dimension" />
        <attr name="my_location_accuracy_tint" format="color" />
        <attr name="my_location_accuracy_alpha" format="integer" />
```

If you need a workaround for `4.0.0` you can use resource overloading to provide a own drawable or you can build the project from source and replace the resource.

Reach out if you have any other questions!

**Comment by mdakram** [comment]
@tobrun i was just checking SDK and seems like location marker is not synced with map movement.There is a minor lag. Is this know issue?

**Comment by tobrun** [comment]
@mdakram which version of the sdk are you using?
