### ISSUE TITLE
[Android] Critical bug (lower Android versions), GL problem

### ISSUE THREAD

**Issue by mpuchala** [mapbox/mapbox-gl-native#4875]
**Platform: Android 4.2.2, Samsung GT-I8200, 4.3 GT-I9300**
**Mapbox SDK version: 4.1.0 - SNAPSHOT (26.04)**
### Steps to trigger behavior
1. Create MapBox map
2. Prepare simple app
### Expected behavior

Properly working app
### Actual behavior

Views are broken, OpenGL problem
### Comment

Guys, there is a critical bug on current snapshot (I'm working with up to date version).

While on Android 4.4.2 (Kazam), 5.1 (Nexus 4), 6.0 (HTC One M8) app works fine, there is a problem on lower Android Devices.

On Android 4.2.2 (Samsung S3 mini) app works totally unstable, below there is an example from logcat (it's constantly error - take a look on date/time):

```
04-27 22:38:25.054 12435-12435/... E/OpenGLRenderer:   GL_INVALID_OPERATION
04-27 22:38:25.070 12435-12435/... D/v_gal: [tid=12435] gl2mERROR: result=0x0502 @ glshSetUniformData(4050)
04-27 22:38:25.070 12435-12435/... D/OpenGLRenderer: GL error from OpenGLRenderer: 0x502
04-27 22:38:25.070 12435-12435/... E/OpenGLRenderer:   GL_INVALID_OPERATION
04-27 22:38:25.101 12435-12435/... D/v_gal: [tid=12435] gl2mERROR: result=0x0502 @ glshSetUniformData(4050)
04-27 22:38:25.101 12435-12435/... D/OpenGLRenderer: GL error from OpenGLRenderer: 0x502
04-27 22:38:25.101 12435-12435/... E/OpenGLRenderer:   GL_INVALID_OPERATION
04-27 22:38:25.117 12435-12435/... D/v_gal: [tid=12435] gl2mERROR: result=0x0502 @ glshSetUniformData(4050)
04-27 22:38:25.117 12435-12435/... D/OpenGLRenderer: GL error from OpenGLRenderer: 0x502
04-27 22:38:25.117 12435-12435/... E/OpenGLRenderer:   GL_INVALID_OPERATION
04-27 22:38:25.140 12435-12435/... D/v_gal: [tid=12435] gl2mERROR: result=0x0502 @ glshSetUniformData(4050)
04-27 22:38:25.140 12435-12435/... D/OpenGLRenderer: GL error from OpenGLRenderer: 0x502
04-27 22:38:25.140 12435-12435/... E/OpenGLRenderer:   GL_INVALID_OPERATION
04-27 22:38:25.179 12435-12435/... D/v_gal: [tid=12435] gl2mERROR: result=0x0502 @ glshSetUniformData(4050)
04-27 22:38:25.179 12435-12435/... D/OpenGLRenderer: GL error from OpenGLRenderer: 0x502
```

And here is result (ex. black rectangles instead of views): 
![S3 mini - bug](https://cloud.githubusercontent.com/assets/5737669/14868031/c1d5b278-0ccb-11e6-8fb7-2f8de5d59a92.png)

On Android 4.3 app doesn't work as well. 
- Map is invisible (there is white screen, probably my background color)
- Buttons look a bit better instead of those rectangles, but some of views aren't shown at all or are corrupted.
- I can't find anything (related to this bug) in logs

Another example of similar issue was reported here:
https://github.com/mapbox/mapbox-gl-native/issues/4779

**IMPORTANT INFORMATION**
I've just checked my app (devices with Android 4.2.2, 4.3) with 4.0.0 Mapbox stable version - it works fine and stable.

@tobrun 
I don't know what has been changed recently and now have influence on current Mapbox version, but I think it's urgent and important issue. I hope you're able to reproduce it (I did it on 3 devices). Maybe it's related to OpenGL changes on Android 4.4 and there is problem with support prior versions? 

Thanks in advance!

**Comment by cammace** [comment]
This is a similar issue to https://github.com/mapbox/mapbox-gl-native/issues/5443. Closing in favor.
