### ISSUE TITLE
MyLocation Accuracy Ring Doesn't Match User Dot

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#4878]
The new MyLocationView API introduced the ability to tint the User Dot and Accuracy Ring.  However the current setup in the TestApp is using a blue User Dot and red Accuracy Ring.  By default, the Accuracy Ring should share the same Tint (blue in this case) as the User Dot.

**Comment by bleege** [comment]
I've reset the Accuracy Ring to use the default Mapbox Blue style, however when run in the TestApp it's still being overwritten somewhere as red continues to be the color used.  Will continue to investigate.

**Comment by q296789611** [comment]
could you please let me know how does the Mapbox support the customer made Maker which not only includes the customer made Marker Icon, but also put the object or text into the Marker and customer made Infowindow? thanks ahead. please answer me and send me email: 296789611@qq.com . thanks very much sincerely.

**Comment by tobrun** [comment]
@bleege this was done for supporting the material theme colors (primary, primaryDark and accent) and automatically tint all the different UI components. I have no problem changing this to blue but please use the `ColorUtils.getPrimaryColor(context))` instead. What you are now proposing, defeats the whole automatic tinting and will result in everybody having a blue accuracy circle. While it should be extracted from the users theme.

**Comment by tobrun** [comment]
@bleege I'm looking into why the changes aren't overwritten

**Comment by tobrun** [comment]
I'm seeing that the accuracy color method is being called twice for `MyLocationToggleActivity` with the following values:
```
 V/MapboxMap: ACCURACY #1E8CAB -> blue
 V/MapboxMap: ACCURACY #E55E5E -> red
```
My initial guess is that the default red is coming from MapboxMapOptions and I'm also guessing we can remove the following section in the `init` method form `MyLocationView` because defaults will be provided by `MapboxMapOptions`.

```
        // default implementation
        setShadowDrawable(ContextCompat.getDrawable(context, R.drawable.ic_userlocationview_shadow));
        setForegroundDrawables(ContextCompat.getDrawable(context, R.drawable.ic_userlocationview_normal), ContextCompat.getDrawable(context, R.drawable.ic_userlocationview_bearing));
        setAccuracyTint(ColorUtils.getPrimaryColor(context));
        setAccuracyAlpha(100);
```

**Comment by tobrun** [comment]
I found another issue where tint wasn't applied in `MapboxMapOptions` because we aren't providing a drawables in that place. I optimised `MyLocationView` to store the tint values and apply them everytheme a drawable has been set for foreground or background.

**Comment by tobrun** [comment]
I did some fixes to initial state, used resources and clean up the old resources from previous implementation.

**Comment by tobrun** [comment]
@bleege 
This is the current default `MyLocationView`:

![screen shot 2016-04-28 at 09 04 30](https://cloud.githubusercontent.com/assets/2151639/14877887/40e477b2-0d20-11e6-90b0-c547073d5c30.png)

Color palette:
 - Center is colorPrimary
 - Edge is colorPrimaryDark
 - Accuracy is colorPrimary with alpha 100/255

Attribution:
 - Dialog bg is colorPrimary
 - Icon is a selector using colorPrimary 

cc @zugaldia @cammace 


To have the UserLocationView compliant to our old design I added the following in xml:

```xml
mapbox:my_location_background_tint="@android:color/white"
```

![screen shot 2016-04-28 at 09 56 29](https://cloud.githubusercontent.com/assets/2151639/14879102/82cd7fdc-0d27-11e6-9543-7a0383c13bc6.png)

**Comment by tobrun** [comment]
I'm noticing an issue with:
```java         mapboxMapOptions.myLocationForegroundTintColor(typedArray.getColor(R.styleable.MapView_my_location_foreground_tint, -1));
```
Because the `getColor` method always requires a return value and it seems that -1 equals `Color.White`. I looked into applying `Integer.MAX_VALUE` but that seems to be equal to `Color.Black`. Need to check if `getColorStateList` provides a workaround because tinting should remain optional and not forced.

**Comment by tobrun** [comment]
Instead of checking against -1, I'm checking against 0 which is equal to `Color.Transparent`

**Comment by tobrun** [comment]
@bleege I PR'ed changes to resolve above in #4878 feel free to test and review it.
Also feel free to provide feedback on the tinting we are exposing for end developers.

**Comment by zugaldia** [comment]
@tobrun thanks so much for the detailed report.

@cammace because of the new behavior, an the new ways to customize the location view, this looks like a great candidate for a guide and/or a dedicated sample.

**Comment by bleege** [comment]
I just ran the the code from #4878 / brach `4878-mylocationview-tint` and the red accuracy circle still remains (see below).  I'm thinking that there's still some trouble in `MapboxMapOptions` as I also notice that the FAB's background tint is also getting overwritten somewhere along the line too as it's set to use the primary color in the Layout XML.

![device-2016-04-28-103543](https://cloud.githubusercontent.com/assets/989928/14891633/11794432-0d2d-11e6-92f8-cf025a016914.png)

**Comment by bleege** [comment]
> @cammace because of the new behavior, an the new ways to customize the location view, this looks like a great candidate for a guide and/or a dedicated sample.

Most definitely.  For functionality like this we should have this in the TestApp as well.  I'm thinking that we'll need a 3 option toggle to show the different options and how they work to developers:

1. Regular
  * Blue User Dot and Blue Accuracy Ring
1. Changed Dot Tint (that also changes Accuracy Ring by default too)
  * Green User Dot and Green Accuracy Ring
1. Changed Accuracy Ring Tint (that leaves the User Dot it's current color)
  * Blue User Dot and Red Accuracy Ring

**Comment by tobrun** [comment]
@bleege could you try again?

I'm seeing this without doing any changes on c126994dafe1636b5c3e90e1196431682c5b4a7e

![device-2016-04-28-175843](https://cloud.githubusercontent.com/assets/2151639/14892388/e1f29b12-0d6a-11e6-9016-c271737c5dcd.png)

**Comment by bleege** [comment]
@tobrun Will do.

**Comment by bleege** [comment]
Sure enough.  I removed the app from my device, did a full clean build, and deployed again.  Computers.  ¯\_(ツ)_/¯

That said, we need to fix the [`mapbox:my_location_background_tint` attribute issue](https://github.com/mapbox/mapbox-gl-native/pull/4885/files#diff-ca46d207870fd595fbb646e9b015f661R25).  When it's removed the circle is stroked with black when it should be white by default.  It's ok to leave this API option in there for app's that want total control, but the SDK shouldn't force users to add it to get the default white stroke.

![device-2016-04-28-110432](https://cloud.githubusercontent.com/assets/989928/14892589/17a65120-0d31-11e6-89a9-d88caacee1b2.png)
_As Is_


![device-2016-04-28-111015](https://cloud.githubusercontent.com/assets/989928/14892817/331e3f0c-0d32-11e6-810b-29c22c8ddf12.png)
_Removed Stroke Tint In XML _

**Comment by bleege** [comment]
I found the issue that was forcing the `mapbox:my_location_background_tint` attribute to have to be set in order to get the white ring around the user dot.  It had to do with when MapboxMapOptions was initially setting up it's values by checking the attributes list and if it didn't find this attribute being set (which is likely the be the majority use case) it was defaulting to `Color.TRANSPARENT` which is why it was showing as dark blue / black.  Now that it default loads white so the User Dot will match the iOS SDK.

```java
// Original
mapboxMapOptions.myLocationBackgroundTintColor(typedArray.getColor(R.styleable.MapView_my_location_background_tint, Color.TRANSPARENT));

// White
mapboxMapOptions.myLocationBackgroundTintColor(typedArray.getColor(R.styleable.MapView_my_location_background_tint, Color.WHITE));
```

**Comment by bleege** [comment]
Rebased and Merged!  Thanks everyone!
