### ISSUE TITLE
customer Maker label:Android

### ISSUE THREAD

**Issue by q296789611** [mapbox/mapbox-gl-native#4883]
could you please let me know how does the Mapbox support the customer made Maker which not only includes the customer made Marker Icon, but also put the object or text into the Marker and customer made Infowindow? thanks ahead.
Android SDK;
![_ _](https://cloud.githubusercontent.com/assets/8074125/14874433/7b984d86-0d32-11e6-9f99-a69512ca8516.jpg)
![default](https://cloud.githubusercontent.com/assets/8074125/14874436/8b8c8f54-0d32-11e6-958b-df1f54b6dd4c.jpg)

**Comment by tobrun** [comment]
@q296789611 

With `4.0.0` we don't allow such customisation yet. The marker icon can only be replaced with another bitmap and the InfoWindow itself is a separate UI component. 

With the upcoming `4.1.0` release we are working on supporting this type of interaction through MarkerViews on Android and AnnotationViews on iOS. You can read more about these in #3276 and #1784. It boils down to having the ability to shown any kind of Andriod/iOS view as a marker on the map. It has some downsides as you will not be able to show that many on one screen but it exposes the flexibility you want as shown above,

**Comment by q296789611** [comment]
@tobrun   thanks your answer very much. but one more question, when will you release the stable channel of 4.1.0?

**Comment by tobrun** [comment]
There is current no eta because of some issues on current master but somewhere aiming at the next month.
