### ISSUE TITLE
[Qt] Use QQuickItem + QSGRenderNode when it is available

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#4884]
We should use a low level `QQuickItem` combined with `QSGRenderNode` because it is probably faster than `QQuickFramebufferObject` and will involve less copies.

Unfortunately it will be ready by Qt5.8 (and the long term supported version of Qt is 5.6).
https://bugreports.qt.io/browse/QTBUG-52913

This test case is a good usage example:
http://code.qt.io/cgit/qt/qtdeclarative.git/tree/tests/auto/quick/rendernode/tst_rendernode.cpp

I don't think it could be backported also because requires changes in the QtQuick core.

**Comment by brunoabinader** [comment]
We are using a QSGRenderNode-based implementation for the plugin that goes into Qt framework.
