### ISSUE TITLE
Use LZFSE for payload compression

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#4888]
Given that we can't use the original compressed response (https://github.com/mapbox/mapbox-gl-native/issues/3886) on iOS, we should use Apple's [LZFSE algorithm](https://developer.apple.com/library/ios/documentation/Performance/Reference/Compression/) introduced in iOS 9 and OS X 10.11.

**Comment by jfirebaugh** [comment]
Use it where? For resources stored in the database? I don't think we should make the database storage platform-specific -- people want to be able to transfer offline caches between devices, which potentially includes transfers between iOS and Android devices.

**Comment by Motti-Shneor** [comment]
As of yesterday, Apple open-sourced lzfse! I don't yet know where to find the sources... but I heard the announcement.

**Comment by kkaefer** [comment]
It's open source: https://github.com/lzfse/lzfse

**Comment by kkaefer** [comment]
> people want to be able to transfer offline caches between devices, which potentially includes transfers between iOS and Android devices.

I haven't encountered this use case so far; the only transfer I've seen is from a pre-built database (on desktop) to phones. Adding support for LZFSE would only take effect for new items stored in the cache, and we'd still be able to decompress gzip-compressed responses.
