### ISSUE TITLE
Increase sprite atlas capacity

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-native#489]
"fill-image" fails when image >510px on either dimension

**Comment by samanpwbb** [comment]
:+1: for tripling the dimensions.

**Comment by incanus** [comment]
There are GL texture implications here to which @kkaefer or @adam-mapbox could likely speak. We need to go with a safe, conservative max texture size across iOS and Android.

**Comment by jfirebaugh** [comment]
> triple the dimensions 

I've since learned that we can't increase the size beyond 1024x1024 without changing how sprite alas coordinates are packed in vertex attributes. (Icons are aligned to multiples of 4 pixels, each coordinate is packed into a single byte, and multiplied by 4 in the shader.)

**Comment by 1ec5** [comment]
#3703 increases the SpriteAtlas size to 1024×1024.

**Comment by samanpwbb** [comment]
I'm recommending users to create sprites that are `1360 × 400` at `@2x` in this tutorial: https://www.mapbox.com/blog/location-based-game-map/, which may be the cause of why maps made with this tutorial are rendering incorrectly:

![2016-08-05 10 47 21](https://cloud.githubusercontent.com/assets/108094/17440663/8e720854-5afb-11e6-860a-ef953729e1ae.png)

If we want to take textures serious we need bigger sprite atlas sizes. 1024 x 1024 is not enough space. Even in the tutorial, the textures feel too small (ideally they're all 512 x 512 to reduce how much repetition is apparent to the user.
