### ISSUE TITLE
Bug using MapboxMap.animateCamera() with CameraUpdateFactory.newLatLngBounds() in the android api

### ISSUE THREAD

**Issue by keco1249** [mapbox/mapbox-gl-native#4894]
I am seeing some issues with the animation not completing when making a call to `animateCamera()` using the `newLatLngBounds()` method. This only occurs when you are zoomed in past a certain point and the bounds are far away. When you are zoomed out far enough the animation works as expected. I modified the animate camera button in the `CameraAnimationTypeActivity` class in your sample application to reproduce the issue.

                // handle animate button clicks
                findViewById(R.id.cameraAnimateButton).setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {

                        LatLng latLng1 = new LatLng(40.0150f, -105.2705f);
                        LatLng latLng2 = new LatLng(39.7392f, -104.9903f);
                        LatLngBounds latLngBounds = new LatLngBounds.Builder()
                                .include(latLng1)
                                .include(latLng2)
                                .build();
                        mapboxMap.animateCamera(CameraUpdateFactory.newLatLngBounds(latLngBounds, 30), 2000, null);
                    }
                });

**Comment by tobrun** [comment]
@keco1249 thank you for reaching out and reporting you problem. Are you using the `4.0.0` version?

**Comment by keco1249** [comment]
Thank you, yes 4.0.0

**Comment by tobrun** [comment]
Adding some information you added elsewhere on this ticket:

>
Looks like the issue is caused by the method getCameraPosition() in the class CameraBoundsUpdate.  The line PointF nePixel = new PointF(Float.MIN_VALUE, Float.MIN_VALUE);
should be PointF nePixel = new PointF(-Float.MAX_VALUE, -Float.MAX_VALUE);


@keco1249 thank you for looking into this, will try to reproduce locally

**Comment by tobrun** [comment]
@keco1249 

I was able to produce this locally:

![ezgif com-video-to-gif 7](https://cloud.githubusercontent.com/assets/2151639/15025022/973d0842-1237-11e6-9b4f-7729acc3f811.gif)

After applying your suggestion, it's working as it should:

![ezgif com-video-to-gif 8](https://cloud.githubusercontent.com/assets/2151639/15025055/bd9b514c-1237-11e6-8ef3-9a75fb441bae.gif)

**Comment by keco1249** [comment]
@tobrun Sweet, thanks!
