### ISSUE TITLE
Add MyLocation Customization Example To TestApp

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#4896]
The recent rebuild of the MyLocation API (aka User Dot) has create the ability to more fully customize it's appearance (see #4878 ).  To show case how this works as well as help the project visually verify potential regressions going forward, there should be an a standalone example in the TestApp.  The example should allow the user to toggle / switch between the 3 primary use cases.

1. Regular (Basic MapView setup)
  * Blue User Dot and Blue Accuracy Ring
1. Changed Dot Tint (that also changes Accuracy Ring by default too)
  * Green User Dot and Green Accuracy Ring
1. Changed Accuracy Ring Tint (that leaves the User Dot it's current color)
  * Blue User Dot and Red Accuracy Ring

/cc @cammace @danswick @tobrun @zugaldia

**Comment by cammace** [comment]
@bleege I'll pick this ticket up.

**Comment by bleege** [comment]
@cammace 👍
