### ISSUE TITLE
"fill-image" tiles weirdly in native retina displays

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-native#490]
[See ocean pattern](https://www.mapbox.com/bites/00055/#7.45/48.159/-123.535)

![screen shot 2014-10-17 at 1 53 13 pm](https://cloud.githubusercontent.com/assets/4551508/4685937/d0b41774-563f-11e4-87e8-331f55e2c2c4.png)

cc/ @incanus

**Comment by jfirebaugh** [comment]
Stale.
