### ISSUE TITLE
Locale And Language Standardization

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#4902]
To produce a more unified and consistent SDK a common Locale and Language are needed.  This will help implementing developers better know what to expect as well as enhance technical integration with the existing Mapbox technology stack (ex: URL generation for Data APIs).  The Android Documentation specifically [warns: "Be wary of the default locale"](http://developer.android.com/reference/java/util/Locale.html).

![screen shot 2016-04-29 at 11 21 54 am](https://cloud.githubusercontent.com/assets/989928/14922397/033b9a3e-0dfd-11e6-83f0-56ea4ee5f026.png)
_Android Documentation On Locale_

@zugaldia @tobrun @bleege discussed this internally in Slack on Tuesday and decided upon the following:

* Language: American English
* Locale: [`Locale.US`](http://developer.android.com/reference/java/util/Locale.html#US)

/cc @mapbox/mobile @cammace @danswick @twbell

**Comment by zugaldia** [comment]
Totally +1. E.g. this was the cause of a recent problem in MAS too: https://github.com/mapbox/mapbox-java/pull/40/files#diff-7c86286b4fa5e982b5970d8b6302c86bL262.

**Comment by bleege** [comment]
I did a search for the following usual suspects when it comes to spelling differences as well as reviewed the class names across the SDK and TestApp.  I also looked for explicit usages of the default Locale, although there are likely implicit uses still in the code that we'll have to guard against.

* `-iour`
* `-isation`
* `Locale.getDefault()`

**Comment by bleege** [comment]
Squashed, Rebased, and Merged!
