### ISSUE TITLE
Overlapping transparent GeoJSON polygons

### ISSUE THREAD

**Issue by kaoskorobase** [mapbox/mapbox-gl-native#4904]
**Platform:** Android 5.0
**Mapbox SDK version:** mapbox-android-sdk 4.0.0 

When trying to visualise GeoJSON polygon features, there is a difference in visualisation between Mapbox Studio and the Android SDK.

### Steps to trigger behavior

 1. Load [this GeoJSON file](http://declaredvolatile.org/pub/locosonic_geojson_example.json) as a tile source into Mapbox Studio
 2. Style the layer using `fill-opacity`
 3. Use the [same style](http://declaredvolatile.org/pub/locosonic_mapbox_style.json) on Android

### Expected behavior

In Mapbox Studio the layer is displayed as a single transparent polygon, which is the behaviour I'd expect.

<img width="522" alt="Mapbox Studio screenshot" src="https://cloud.githubusercontent.com/assets/484494/14925653/c199ccf8-0e48-11e6-8dcc-5fa7b5808f32.png">

### Actual behavior

With the Android SDK, the layer is rendered as two overlapping transparent polygons. The result is the same when using the GeoJSON directly with a `geojson` source instead of the `vector` source.

<img height="522" alt="Android screenshot" src="https://cloud.githubusercontent.com/assets/484494/14925727/15b23794-0e49-11e6-994a-7d68d80dc576.png">

Is this a bug or intended behaviour? Thanks!

**Comment by bleege** [comment]
@kaoskorobase Thanks for reporting this issue with how the GeoJSON is rendered.  To confirm, the code in the Android SDK that is being used in the app is only `MapboxMap.setStyleUrl()` correct?

/cc @jfirebaugh @ansis @kkaefer

**Comment by jfirebaugh** [comment]
I believe the native rendering is the intended rendering, and GL JS rendering will match once we switch to earcut.

**Comment by kaoskorobase** [comment]
@bleege Yes, correct. I've just noticed that the link to the style was incorrect, here it is for the record: http://declaredvolatile.org/pub/locosonic_mapbox_style.json

**Comment by kaoskorobase** [comment]
@jfirebaugh OK, fair enough. Any ideas how I can achieve the current GL JS behaviour? Thanks again!

**Comment by kkaefer** [comment]
@kaoskorobase you'll need to union both polygons before adding them.

**Comment by kaoskorobase** [comment]
OK, thanks!

I've also been trying to use GeoJSON's `MultiPolygon` but with overlapping polygons a "hole" appears where they overlap (see screenshot below). Is this intended behaviour or should I submit another issue?

![screenshot_20160502-123948](https://cloud.githubusercontent.com/assets/484494/14952737/57e4f536-1063-11e6-822d-368fa863dab6.png)

**Comment by kkaefer** [comment]
Technically, it's invalid geometry, but the rendering is expected. You'll need to use something like Clipper or Boost::Geometry to union them.

**Comment by kaoskorobase** [comment]
OK thanks, closing this issue then.
