### ISSUE TITLE
GeoJSON features disappear in zoom level 15

### ISSUE THREAD

**Issue by kaoskorobase** [mapbox/mapbox-gl-native#4907]
**Platform:** Android 5
**Mapbox SDK version:** mapbox-android-sdk 4.0.0

### Steps to trigger behavior

 1. Use [this style](http://declaredvolatile.org/pub/locosonic_mapbox_style_with_geojson.json) in the Android SDK (via `setStyleUrl`). It includes a GeoJSON source definition.
 2. Zoom the GeoJSON features into view until they disappear

### Expected behavior

GeoJSON features should be visible up to max zoom level unless otherwise specified.

### Actual behavior

The GeoJSON features are visible up to zoom level 14 and disappear with zoom level 15. For debugging, we logged the current zoom level inside an `OnCameraChangeListener`.

Specifying the "maxzoom" attribute in the layer doesn't seem to make a difference.

**Comment by cammace** [comment]
Thanks for reporting this issue, I have tested using your style and was unable to reproduce the issue. I was using Mapbox Android SDK verision `4.0.1`. 

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5652865/15553031/38f90e66-228b-11e6-8552-d5ec6af3b3eb.gif)

Feel free to open again if you are still having issues.

**Comment by kaoskorobase** [comment]
Thanks for looking into this. I've tried the style in our app with SDK version `4.0.1` and it still exhibits the same behaviour. Would it be possible to share the code you tested with in order to spot any possible differences? Thanks!

**Comment by micahcatlin** [comment]
I had a similar problem, which was correctable by specifying a "maxZoom" option when configuring Leaflet.VectorGrid.slicer.  It passes its 'options' object into geojson-vt (geojsonvt or toposon), whose default "maxZoom" is 14.

So this is isn't a problem with mapbox, but you might be running into it because of the way your vector tiles are being sliced.  Good luck!
