### ISSUE TITLE
Remove boost iostreams dependency

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#4915]
jpeg_reader.cpp and png_reader.cpp use boost iostreams for simple buffer reads. Bringing in boost requires some warning-disabling boilerplate and even then causes a bunch of compile spew about deprecated headers.

It looks like the use of boost can be replaced with a simple buffer and current location; let's do so.

**Comment by springmeyer** [comment]
👍

**Comment by brunoabinader** [comment]
👉 #5417
