### ISSUE TITLE
Native and JS uses different encoding for fontstack URL

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-native#4926]
**Platform:** iOS and Mac
**Mapbox SDK version:** Native: ios-v3.2.1 and JS: v0.18.0

### Steps to trigger behavior

 1. Create your own glyph with build-glyphs and upload it to a webserver. {fonstack} part of URL should be "Open%20Sans%20Regular,Arial%20Unicode%20MS%20Regular".
 2. Create your own GL style using that glyph
 3. Test in GL JS and Native

### Expected behaviour
Should work fine in both JS and Native

### Actual behaviour
Works fine in JS only. Need to create a copy of the pbf files in a directory with name "Open%20Sans%20Regular%2c%20Arial%20Unicode%20MS%20Regular" to make them work in Native (iOS) as well. 

GL JS and GL Native should use the same url encoding for the {fontstack} part of the glyph URL.

**Comment by jfirebaugh** [comment]
The web server serving the glyphs should not make assumptions about what URL characters clients choose to percent-encode; it's legal for any path character to be percent-encoded. The server should percent-decode the incoming path, re-encode or escape any characters that are reserved in the target filesystem, and locate the glyphs using the resulting name.

**Comment by halset** [comment]
Thank you, @jfirebaugh. And Sorry for the noise.
