### ISSUE TITLE
User dot not changing colors immediately

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#4930]
When changing the user dot color or accuracy color, it sometimes wont immediately show the change. Maybe this has to do with location becoming stale or invalidate needing to be called?

**Comment by tobrun** [comment]
Great find, I'm guessing that we are missing a `invalidate` somewhere. The invalidate method will result in calling `onDraw` which should change the color.

**Comment by tobrun** [comment]
Refs #4897

**Comment by tobrun** [comment]
My hunch was right, I added an invalidate and everything is working as designed.

**Comment by bleege** [comment]
@tobrun Is this ready to be merged via #4940 and closed then?

**Comment by tobrun** [comment]
@bleege, I was holding off on doing that so I could talk through the changes with @cammace. 
That happened yesterday so going to merge it now.

**Comment by bleege** [comment]
👍
