### ISSUE TITLE
Tracking C++ code sharing opportunities

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-gl-native#4946]
I plan to edit this ticket in place as I notice places we can potentially abstract c++ headers to be used outside of Mapbox GL Native (and outside of other projects, that Mapbox GL Native can use). This list is not meant to be directionally actionable and precise but rather to track opportunities and rough similarities in code.

  - [mbgl minmax/clamp.hpp](https://github.com/mapbox/mapbox-gl-native/blob/fbeb934f9d88a85a7df65a95d2cc4c88250e76dc/src/mbgl/math/minmax.hpp) and [mapnik's safe_cast](https://github.com/mapnik/mapnik/blob/52df451ee33f0b8e642fdddd2a7f150f4a04a219/include/mapnik/safe_cast.hpp)

**Comment by jfirebaugh** [comment]
@springmeyer We try to keep tickets in this repository actionable. Maybe https://github.com/mapbox/cpp/issues is a better place for it?

**Comment by springmeyer** [comment]
:+ @jfirebaugh, closing.
