### ISSUE TITLE
Line tests failing on Linux with Mesa 10.3.1 Xlib software rasterizer

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#495]
Running headless tests with Mesa 10.3.1 built from scratch, I'm seeing [unexpected failures around the line- tests](https://mapbox-gl-testing.s3.amazonaws.com/headless/mapbox/mapbox-gl-native/907.1/index.html). End caps get drawn but the lines themselves don't.

~~One substantial change in my build of Mesa was that I omitted ES2 support in order to build Mesa with the software rasterizer. I can't seem to find a configuration that works to enable `shared-glapi` (developer comments indicate that it's forcibly disabled when using the software rasterizer) in order to compile with ES2 support (if indeed that's actually the underlying issue).~~

Relevant mesa bugs:
~~[Undefined references linking libGLESv2 when configured with --disable-dri](https://www.libreoffice.org/bugzilla/show_bug.cgi?id=61750)~~
~~[OpenGL ES2 with fbdev - link error](https://www.libreoffice.org/bugzilla/show_bug.cgi?id=75098)~~

/cc @kkaefer @ansis

**Comment by mikemorris** [comment]
Having trouble tracking down when exactly this was fixed, but lines are now rendering as expected in https://travis-ci.org/mapbox/mapbox-gl-native/jobs/48839942 https://mapbox-gl-testing.s3.amazonaws.com/headless/mapbox/mapbox-gl-native/2061.8/index.html

**Comment by brunoabinader** [comment]
Related: https://github.com/mapbox/mapbox-gl-native/issues/1555.
