### ISSUE TITLE
Extra space on an InfoWindow without a snippet

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#4959]
When you create a marker with a `title` but without a `snippet`. You will see a empty space below the `title` in the InfoWindow. This should be optimised to fit nicely in the InfoWindow.

Current behaviour:
![image](https://cloud.githubusercontent.com/assets/2151639/15070339/f3b6f7ca-1383-11e6-9d2c-f726183b0f75.png)

**Comment by bleege** [comment]
Discussed with @zugaldia @tobrun @ivovandongen @cammace this morning and we'll add this to `4.1.0` to support #5282.

**Comment by bleege** [comment]
Will be working in the Standard InfoWindow Example to build this out.

![device-2016-06-13-144327](https://cloud.githubusercontent.com/assets/989928/16020795/3c768872-3175-11e6-89e3-8a1718e3d4c6.png)

**Comment by bleege** [comment]
Title only InfoWindow sizing....

![device-2016-06-13-145240](https://cloud.githubusercontent.com/assets/989928/16021129/a0c6066c-3176-11e6-9ae1-abe1f554353a.png)
_The Ellipse Title Only Example_

**Comment by bleege** [comment]
I added Sherman Park marker example to show that no InfoWindow is displayed if there's no Title nor Snippet.  I added the Lafayette Square marker example to show what happens in Snippet only mode.  I think it makes the most sense for the the snippet only example to render as a snippet and not be forced to render as a Title if there is no title.  This provides more flexibility within the controls.

![device-2016-06-13-151149](https://cloud.githubusercontent.com/assets/989928/16021595/32f554a0-3179-11e6-8b20-a4d9eb8dcab9.png)
_Sherman Park and Lafayette Square_

**Comment by bleege** [comment]
Squash, Rebased, and Merged into `release-android-v4.1.0`.

**Comment by tobrun** [comment]
@bleege looks great!

**Comment by cammace** [comment]
Wooo! Thanks for hitting this 🎫 @bleege, looks much better!
