### ISSUE TITLE
ios benchmark.sh script broken

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-gl-native#4964]
It looks like https://github.com/mapbox/mapbox-gl-native/blob/666c2658b86cd73b8f144f628c52d21894e0ebea/platform/ios/scripts/benchmark.sh is out of date as `make ibench` went away in https://github.com/mapbox/mapbox-gl-native/commit/f964e40e7e9220d08751d8607af61ac5a7c0794c

context: I'm a noob trying to learn how to run benchmarks and found `platform/ios/scripts/benchmark.sh`, ran it and hit `make: *** No rule to make target`ibench'.  Stop.`

**Comment by 1ec5** [comment]
The workaround for now is to run `make iproj`, switch to the bench scheme, and run it from there. You'll need to enter your access token at the prompt.

**Comment by springmeyer** [comment]
closing as I presume this is stale now/no longer relevant.
