### ISSUE TITLE
[node-mapbox-gl-native] npm install error

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-native#4971]
I can not install node-mapbox-gl-native using `node-mapbox-gl-native`
Error says: Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/mapbox-gl-native/v3.1.2/node-v47-linux-x64.tar.gz

It seems that I can not download this package. please check it out, thanks

**Comment by mikemorris** [comment]
We stopped building binaries for Node.js v5.x in https://github.com/mapbox/mapbox-gl-native/issues/4370 because of npm3 bugs. Now that Node.js v6 is out we can look at adding that to the build matrix, but we'll probably be sticking with only LTS releases for publishing binaries.

You should still be able to [build from source](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/node/README.md#installing) with `npm install --build-from-source` after ensuring all dependencies are in place.

**Comment by jingsam** [comment]
OK，I get it. Now I can download it from this link:
https://mapbox-node-binary.s3.amazonaws.com/mapbox-gl-native/v3.1.2/node-v46-linux-x64.tar.gz.

I also want to know weather node-mapbox-gl-native provides binaries for Windows?

**Comment by mikemorris** [comment]
> I also want to know weather node-mapbox-gl-native provides binaries for Windows?

Nope, sorry, we haven't done any work on adding Windows support to the codebase yet.

**Comment by twisig** [comment]
Same issue with Mac:

```
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/mapbox-gl-native/v3.4.2/node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/user/node_modules/mapbox-gl-native/node_modules/node-pre-gyp/lib/install.js:98:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:188:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/user/node_modules/mapbox-gl-native/node_modules/request/request.js:986:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:362:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Darwin 16.1.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/user/node_modules/mapbox-gl-native/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /Users/user/node_modules/mapbox-gl-native
node-pre-gyp ERR! node -v v7.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok 
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/mapbox-gl-native/v3.4.2/node-v51-darwin-x64.tar.gz
mkdir -p "platform/macos/macos.xcworkspace/xcuserdata/user.xcuserdatad"
cp platform/macos/WorkspaceSettings.xcsettings "platform/macos/macos.xcworkspace/xcuserdata/user.xcuserdatad/WorkspaceSettings.xcsettings"
mkdir -p build/macos
(cd build/macos && cmake -G Xcode ../..)
/bin/sh: cmake: command not found
make: *** [build/macos/mbgl.xcodeproj] Error 127
npm WARN enoent ENOENT: no such file or directory, open '/Users/user/package.json'
npm WARN user No description
npm WARN user No repository field.
npm WARN user No README data
npm WARN user No license field.
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mapbox-gl-native"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! mapbox-gl-native@3.4.2 install: `node-pre-gyp install --fallback-to-build=false || make node`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the mapbox-gl-native@3.4.2 install script 'node-pre-gyp install --fallback-to-build=false || make node'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapbox-gl-native package,
npm ERR! not with npm itself.
```

**Comment by jfirebaugh** [comment]
@twisig We don't have a prebuilt version for node v7. If you want to use it with node v7, you'll need to have the build dependencies available: https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md. Or use node v4.

**Comment by anees042** [comment]
Same Issue on node 4.4.4 on Windows 10

 `@mapbox/mapbox-gl-native@3.4.4 install C:\Users\acer\AppData\Roaming\npm\node_modules\tileserver-gl\node_modules\@mapbox\mapbox-gl-native
> node-pre-gyp install --fallback-to-build=false || make node

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v3.4.4/node-v46-win32-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (C:\Users\acer\AppData\Roaming\npm\node_modules\tileserver-gl\node_modules\@mapbox\mapbox-gl-native\node_modules\node-pre-gyp\lib\install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:82:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:169:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (C:\Users\acer\AppData\Roaming\npm\node_modules\tileserver-gl\node_modules\request\request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:77:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:419:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:309:20)
node-pre-gyp ERR! stack     at emitOne (events.js:77:13)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\acer\\AppData\\Roaming\\npm\\node_modules\\tileserver-gl\\node_modules\\@mapbox\\mapbox-gl-native\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd C:\Users\acer\AppData\Roaming\npm\node_modules\tileserver-gl\node_modules\@mapbox\mapbox-gl-native
node-pre-gyp ERR! node -v v4.4.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v3.4.4/node-v46-win32-x64.tar.gz
makefile:20: *** Cannot determine host platform.  Stop.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "tileserver-gl"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! @mapbox/mapbox-gl-native@3.4.4 install: `node-pre-gyp install --fallback-to-build=false || make node`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @mapbox/mapbox-gl-native@3.4.4 install script 'node-pre-gyp install --fallback-to-build=false || make node'.
npm ERR! This is most likely a problem with the @mapbox/mapbox-gl-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build=false || make node
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @mapbox/mapbox-gl-native
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls @mapbox/mapbox-gl-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log`

**Comment by bsudekum** [comment]
@anees042 can you try installing the latest version. Just `npm install @mapbox/mapbox-gl-native --save`?

v3.4.4 is very old at this point.

**Comment by anees042** [comment]
@bsudekum Windows Support??
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: connect ETIMEDOUT 54.231.49.210:443
node-pre-gyp ERR! stack     at Object.exports._errnoException (util.js:870:11)
node-pre-gyp ERR! stack     at exports._exceptionWithHostPort (util.js:893:20)
node-pre-gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\git\\gis\\node_modules\\@mapbox\\mapbox-gl-native\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd E:\git\gis\node_modules\@mapbox\mapbox-gl-native
node-pre-gyp ERR! node -v v4.4.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
connect ETIMEDOUT 54.231.49.210:443
      0 [main] sh 29524 sync_with_child: child 31440(0x1CC) died before initialization with status code 0xC0000142
    550 [main] sh 29524 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
makefile:23: *** Cannot determine host platform.  Stop.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@mapbox/mapbox-gl-native" "--save"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! @mapbox/mapbox-gl-native@3.5.4 install: `node-pre-gyp install --fallback-to-build=false || make node`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @mapbox/mapbox-gl-native@3.5.4 install script 'node-pre-gyp install --fallback-to-build=false || make node'.

**Comment by danger89** [comment]
Please support npm 6
