### ISSUE TITLE
Forcing accessToken on Android

### ISSUE THREAD

**Issue by dariav** [mapbox/mapbox-gl-native#4972]
Hi!

I am reading around and trying to find out but without any luck.

Why is Mapbox' `AccessToken` required on Android SDK?
I see we are having 
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java#L357

```
// Force a check for an access token
        validateAccessToken(getAccessToken());
```

What if we are not trying to use any of the Mapbox' tiles (services) but just the engine? If we are not going to consume any of the Mapbox's resources, could we bypass token validation?

Thanks

**Comment by jfirebaugh** [comment]
Looks like this may date from 8ed1dc9f7412d61a66bae576346f2674e6ab3926.

@tobrun Is it necessary? We've been trying to keep mapbox-gl-native usable without an access token when no Mapbox services are used.

**Comment by tobrun** [comment]
@jfirebaugh thanks for 👀, I was wrong to assume this was a requirement. 
I'm going to add this to next milestone since this is an easy fix with no impact.

cc @bleege @zugaldia @cammace @danswick

**Comment by bleege** [comment]
> I'm going to add this to next milestone since this is an easy fix with no impact.

I'm not so sure about that... let's discuss this internally.

**Comment by tobrun** [comment]
> We've been trying to keep mapbox-gl-native usable without an access token when no Mapbox services are used.

Capturing from chat with @bleege. He felt this wasn't an easy fix and disagreed on statement above. I removed it from the milestone. He will be running point on this issue.

**Comment by nw31304** [comment]
I was just curious if there is an update on this.  Specifically, I have a need to use the MapBox Android SDK to display locally-produced, custom vector tiles, with my own glyphs, sprites, and stylesheet.  In short, I only need the MB Android SDK engine and do not need to access any other MapBox resources.   My app works fine without a MapBox-provided access token as long as I pass a string as the second parameter to MapBox.getInstance() that meets the requirements of MapBox.validateAccessToken().  Is this permitted?

**Comment by ychescale9** [comment]
@nw31304  I have very similar requirements to what you've described, but I wasn't able to bypass the token validation when I provided an arbitrary string as the second parameter in `MapBox.getInstance()` as it throws an exception saying token is invalid.

Even when I provide a valid token, when the app is launched the first time, `onMapReady()` won't get called until there's valid internet connection. So it looks like you have to validate your access token against the MapBox server before you can use the SDK.

I'm wondering which version of the SDK you were using when you were able to bypass the access token validation? I've been testing with **v5.2.0-beta.2**. Thanks.

**Comment by nw31304** [comment]
@ychescale9 I'm using v5.1.1 of the SDK.  I looked at the validateAccessToken() code, and it requires the token to begin with the string "pk.", so I used a dummy token like "pk.Not needed".  Since I'm not using any MapBox assets other than the SDK itself, I'm hoping that this is acceptable.

**Comment by ychescale9** [comment]
Thanks for that, I was able to bypass the validateAccessToken, but couldn't get anything to display on the map - `loading style failed: HTTP status code 401`

Are you using a local style for the map?

**Comment by nw31304** [comment]
@ychescale9 Yes, I'm styling our home-grown vector tiles using a custom stylesheet that I serve over HTTP/S.

**Comment by nw31304** [comment]
@ychescale9 My custom style pulls in glyphs from https://github.com/openmaptiles/fonts, which was sufficient for the text / label rendering I do in the stylesheet.

**Comment by ychescale9** [comment]
@nw31304 Thanks! I’m able to do the same now. Hopefully this doesn’t have any legal implications. But I know the iOS sdk doesn’t require you to validate the access token at all so should be ok.

**Comment by monashri** [comment]
Is there any update on this. Am using the Mapbox sdk 5.2.0-beta.3@aar - to render my own tiles without consuming any of the mapbox services and api . 

 Is there any legal implications in proceeding with the dummy token("pk.mymap") ? 
 Is this an acceptable way to bypass token validation?

**Comment by danswick** [comment]
Noting that we've received a few requests regarding this issue in Mapbox support channels lately.

**Comment by yang-owl** [comment]
Any update on this issue? We are look at options for rendering offline maps would like to know if this is going to be supported by mapbox.

**Comment by tobrun** [comment]
This was initially on hold due to [telemetry](https://github.com/mapbox/mapbox-gl-native/issues/4972#issuecomment-218064332). Yesterday we merged the beta version of the new telemetry library and I would like to start removing the requirement laid out in OP for the upcoming 6.0.0 release.

cc @boundsj @electrostat @Guardiola31337  for impact on the telem side.

**Comment by gruelfin** [comment]
Is there any update to this? I would like to know if we need to have a commercial plan if we use the sdk to display local/offline tiles in a commercial app

**Comment by ychescale9** [comment]
This change is now causing a crash if `null` is passed in `Mapbox.getInstance(context, null)`:

```
FATAL EXCEPTION: main
                  Process: com.xxx, PID: 8883
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx/com.xxx.MapActivity}: java.lang.NullPointerException
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: java.lang.NullPointerException
                      at com.mapbox.mapboxsdk.storage.FileSource.initialize(Native Method)
                      at com.mapbox.mapboxsdk.storage.FileSource.<init>(FileSource.java:125)
                      at com.mapbox.mapboxsdk.storage.FileSource.getInstance(FileSource.java:52)
                      at com.mapbox.mapboxsdk.maps.MapView.onStart(MapView.java:362)
                      ...
```
Crash happens at `private native void initialize(String accessToken, String cachePath, AssetManager assetManager);` in `FileSource`
