### ISSUE TITLE
Zooming to "max" freezes map view

### ISSUE THREAD

**Issue by millenbop** [mapbox/mapbox-gl-native#4976]
Platform: iOS
Mapbox SDK version: 3.2.1-static

When zooming in to the max zoom level (set by the lib), the map "freezes" and you cannot zoom out anymore or pan around. It feels like it ends up in a while-true loop. See attached vid.

[mapbox-zoom.mp4.zip](https://github.com/mapbox/mapbox-gl-native/files/254503/mapbox-zoom.mp4.zip)

A work around for now is to just set the max zoom level manually before hitting the wall.
### Steps to trigger behavior
1. Zoom in as long as mapbox lets you
2. Try to zoom out or pan
### Expected behavior

Map should be zoomed out or panned around
### Actual behavior

Map "freezes" and you cannot interact with the map anymore

**Comment by millenbop** [comment]
If I limit zoom to 19 then it works fine, but not 20 (guess that's the internal limit)

**Comment by kkaefer** [comment]
I can't reproduce this behavior either with the default maxzoom, or with a manually set maxzoom. Does this also happen an a physical device?

**Comment by millenbop** [comment]
On device as well (iPhone 6, latest iOS). It actually crashes then. I'll make an isolated example and upload (will remove our token though).

**Comment by millenbop** [comment]
I forgot to mention that we have a custom vector tile layer as well. I tried it without the style and then it works. Attaching it here.

[emerald-ios-edited.json.zip](https://github.com/mapbox/mapbox-gl-native/files/255083/emerald-ios-edited.json.zip)

**Comment by 1ec5** [comment]
This sounds reminiscent of #4508.

**Comment by friedbunny** [comment]
Closing as unreproducible, but please feel free to post more information as it becomes available.
