### ISSUE TITLE
Annotation image replacement on macOS

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#4985]
The OS X SDK needs the equivalent of #3146 #3835, in which an annotation image’s image can be modified and the annotation itself can be moved to a different coordinate using KVO.

**Comment by 1ec5** [comment]
I was mistaken: #3835 added point annotation relocation to the OS X SDK, but #3146 has not been ported over. I’m not entirely satisfied with the design of #3835 (see #4723 for example), so the fix for this issue might look a lot different than #3835.

**Comment by rhuttenh** [comment]
Is there a swift example of updating the annotation coordinate? 
When do you think replacing the annotation image will be implemented?

**Comment by 1ec5** [comment]
> Is there a swift example of updating the annotation coordinate in iOS?

Updating an annotation’s coordinate looks like this:

```swift
pointAnnotation.coordinate = CLLocationCoordinate2D(latitude: …, longitude: …)
```

> When do you think replacing the annotation image will be implemented?

It’s already possible to replace an annotation’s image on iOS. This issue tracks implementing the same functionality on macOS; I don’t have a date to share with you for macOS at the moment.
