### ISSUE TITLE
[Android] std::exception at NativeMapView.nativeRenderSync

### ISSUE THREAD

**Issue by Schumi09** [mapbox/mapbox-gl-native#4991]
**Platform:**
Android 4.4.2
**Mapbox SDK version:**
4.0.1-SNAPSHOT
### Steps to trigger behavior

I could not reproduce it yet and saw it only once today, so maybe related to today's Snapshot (10/05/16). Basically my app is setting the cameraposition on every onMyLocationChange to the location (and some more stuff in background). As I have implemented some location mock based on a gpx  gps track everything is more or less deterministic. My app keeps the screen awake and there was no interaction with the screen. According to the logcat the issue is not caused by my code. For now I can only leave you the log here ;)
### Actual behavior

> 05-10 15:58:06.962 8510-8510/ifgi.wayto_navigation E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                      Process: ifgi.wayto_navigation, PID: 8510
>                                                                      java.lang.Error: std::exception
>                                                                          at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRenderSync(Native Method)
>                                                                          at com.mapbox.mapboxsdk.maps.NativeMapView.renderSync(NativeMapView.java:139)
>                                                                          at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:1225)
>                                                                          at android.view.View.draw(View.java:14489)
>                                                                          at android.widget.FrameLayout.draw(FrameLayout.java:472)
>                                                                          at android.view.View.getDisplayList(View.java:13386)
>                                                                          at android.view.View.getDisplayList(View.java:13428)
>                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>                                                                          at android.view.View.getDisplayList(View.java:13324)
>                                                                          at android.view.View.getDisplayList(View.java:13428)
>                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>                                                                          at android.view.View.getDisplayList(View.java:13324)
>                                                                          at android.view.View.getDisplayList(View.java:13428)
>                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>                                                                          at android.view.View.getDisplayList(View.java:13324)
>                                                                          at android.view.View.getDisplayList(View.java:13428)
>                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>                                                                          at android.view.View.getDisplayList(View.java:13324)
>                                                                          at android.view.View.getDisplayList(View.java:13428)
>                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>                                                                          at android.view.View.getDisplayList(View.java:13324)
>                                                                          at android.view.View.getDisplayList(View.java:13428)
>                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
>                                                                          at android.view.View.getDisplayList(View.java:13324)
>                                                                          at android.view.View.getDisplayList(View.java:13428)
>                                                                          at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1568)
>                                                                          at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1448)
>                                                                          at android.view.ViewRootImpl.draw(ViewRootImpl.java:2380)
>                                                                          at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2252)
>                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1882)
>                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
>                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5603)
>                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
>                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:574)
>                                                                          at android.view.Choreographer.doFrame(Choreographer.java:544)
>                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
>                                                                          at android.os.Handler.handleCallback(Handler.java:733)
>                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                          at android.os.Looper.loop(Looper.java:136)
>                                                                          at android.app.ActivityThread.main(ActivityThread.java:5146)
>                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
>                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
>                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
>                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by tobrun** [comment]
@Schumi09 thank you for testing the `SNAPSHOT-4.0.1` and reporting this issue back.

**Comment by jfirebaugh** [comment]
@Schumi09 Do you have a way to reliably reproduce this issue? There's probably not enough information in the log to allow us to track this down.

**Comment by Schumi09** [comment]
Sorry, completetly forgot about this issue. Unfortunately I don't remember anymore what the circumstances were but it just happened randomly a couple of times on that phone (that I don't use anymore). I just left it here to let you know that something is strange ;)
However, someone opened a maybe similar issue some days ago #5350. Maybe he can provide more information.

**Comment by jfirebaugh** [comment]
Closing; not reproducible.
