### ISSUE TITLE
CocoaPods: Unable to satisfy the following requirements...

### ISSUE THREAD

**Issue by imrmaximus** [mapbox/mapbox-gl-native#4992]
Hi,
I try to install Mapbox iOS SDK 3.2 through Cocoapods (0.39.0) but i have this error :
[!] Unable to satisfy the following requirements:
- `Mapbox-iOS-SDK (~> 3.2.0)` required by `Podfile`

Have you any idea of the problem?
Do i need to install the pre-version 1.0.0.beta.6 of Cocoapods to use your last version of Mapbox ?

**Comment by 1ec5** [comment]
I’m able to install 3.2.2 using `~> 3.2.0` with CocoaPods 0.39.0. Do you see any other error messages?

**Comment by friedbunny** [comment]
Please post your entire `Podfile` — I suspect this has to do with the minimum platform version being lower than 8.

(You should typically never install a CocoaPods beta as an enduser. 😬)

**Comment by imrmaximus** [comment]
Here's my podfile:
`platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://iMrMaximus@bitbucket.org/xpdigitdevteam/ios-cocoapods-private-repo-specs.git'

xcodeproj 'APP-FS.xcodeproj'

use_frameworks!

def share_pods
    pod 'XPDTheSidebarController'
    pod 'Mapbox-iOS-SDK', '~> 3.2.0'
    pod 'NMRangeSlider', '1.2.1'
    pod 'MagicalRecord', '2.2'
    pod 'MBProgressHUD', '0.9.1'
    pod 'AFNetworking', '2.5.4'
    pod "SDWebImage", "3.7.3"
    pod "Reachability", "3.2"
    pod 'XPDPDTSimpleCalendar'
    pod 'Alamofire', '~> 2.0'
    pod 'SwiftFilePath'
    
end

#target 'CDT76' do
#    share_pods
#end

target 'Guyane' do
    share_pods
end

#target 'Martinique' do
#    share_pods
#end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
    end
end`

(For "never install a CocoaPods beta as an enduser", i understand :-D)

**Comment by 1ec5** [comment]
Not sure if it matters, but the build of the Mapbox iOS SDK that we distribute over CocoaPods is built with Bitcode enabled. We don’t distribute a Bitcode-disabled build, although it’s possible to build one from source. Is there anything in particular keeping you from building with Bitcode?

**Comment by friedbunny** [comment]
@imrmaximus I would guess this has to do with the `source` definitions, though the [CocoaPods docs](https://guides.cocoapods.org/syntax/podfile.html#source) indicate that including their official spec first should get you the latest public version of our pod.

In any case, I was able to successfully `pod install` after commenting out your private source and the private pods.

**Comment by imrmaximus** [comment]
I create a new project to test the integration of the latest version of Mapbox.
With this simple podfile:
```ruby
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'Mapbox-iOS-SDK', '3.2.0'
```

But that does not work either.

**Comment by friedbunny** [comment]
Seeing as the pods [definitely exist](https://github.com/CocoaPods/Specs/tree/master/Specs/Mapbox-iOS-SDK) in the CocoaPods/Specs repo, I would suggest that this is a local cache problem for you, @imrmaximus.

The common (only?) way to clear CocoaPods cache is to delete the relevant folders, mainly `~/Library/Caches/CocoaPods`.

**Comment by friedbunny** [comment]
We’ve had another user report that they encountered this issue, with a completely fresh install, without even having CocoaPods installed previously.

As ever, I’m inclined to blame CocoaPods, but I don’t have anything to back that up yet.

**Comment by friedbunny** [comment]
This issue seems to have been resolved — chalking it up to the CocoaPods.

**Comment by timautin** [comment]
I had the same problem, running "pod repo update" (and re-rennung "pod install") fixed it.

**Comment by Dipak113** [comment]
Do not try to edit podfile with Textedit ,for editing tool.It will add some extra data in podfile.Try to edit with xcode only.[!] Your Podfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

**Comment by yuanjilee** [comment]
update cocopods version first with "pod repo update"!

**Comment by arsimpa90** [comment]
I am getting this error when i am trying to install via pod. I have tried repo update also but nothing worked.

pod 'MapboxNavigation', '~> 0.12'

[!] Unable to satisfy the following requirements:

- `SDWebImage (= 4.0.0)` required by `Podfile.lock`
- `SDWebImage (= 4.0.0)` required by `IDMPhotoBrowser (1.11.3)`
- `SDWebImage (~> 4.1)` required by `MapboxNavigation (0.12.0)`

**Comment by 1ec5** [comment]
@arsimpa90, this repository is for the Mapbox Maps SDK. Please open issues regarding the Mapbox Navigation SDK for iOS in the [mapbox-navigation-ios](https://github.com/mapbox/mapbox-navigation-ios/) repository. Thanks!
