### ISSUE TITLE
Error with mapBox 

### ISSUE THREAD

**Issue by HoussemHfaidh** [mapbox/mapbox-gl-native#4999]
Hi,
I try to install Mapbox mapbox-gl-native Android   but i have this error :
" Couldn't load mapbox-gl from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mapbox.mapboxsdk.testapp-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.mapbox.mapboxsdk.testapp-2, /vendor/lib, /system/lib]]]: findLibrary returned null"

Have you any idea of the problem?

**Comment by Schumi09** [comment]
Hi, looks quite familiar I believe, when it happened to me sometimes I already had the app installed but tried to install a newer version from android studio. Manually uninstalling the app from the device and trying again helped.

**Comment by HoussemHfaidh** [comment]
Hi,
Thank you ,but the version of android studio is 1.5.1 ?

**Comment by Schumi09** [comment]
The latest version of Android Studio is [2.1](http://developer.android.com/sdk/index.html)

**Comment by tobrun** [comment]
@HoussemHfaidh 
To run the sample app from the repository you need to build the AAR from source first. 
[Here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/CONTRIBUTING_OSX.md) are the installation instructions for the OSX platform to install the dependencies. Afterwards you can execute `make android` in the root of the project to build the AAR file. 

If you just want to use the library, you can follow [these](https://www.mapbox.com/android-sdk/#gradle) instructions.

**Comment by HoussemHfaidh** [comment]
Thanks for your help @Schumi09  @tobrun
