### ISSUE TITLE
Introduce MapboxAccountManager

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#5004]
`MapboxAccountManager` will be a centralized place for developers to configure their apps to use Mapbox technology on Android.  This will be the preferred (and ultimately only as of `5.0.0`) place to set the app's Access Token.  The use case for the developer will be to configure it in the `onCreate()` method of either:

1. The App's Custom `Application` object (if app uses one)
1. The App's launch `Activity`

```java
// Setup call
MapboxAccountManager.start("Mapbox Access Token");
```

While implementing this we'll immediately mark the `setAccessToken()` and `getAccessToken()` in `MapView` and `MapboxMap` as deprecated starting in `4.1.0` with the goal of removing them as of `5.0.0`.

**Comment by tmcw** [comment]
@zugaldia you can subscribe with the button on the right :)

**Comment by bleege** [comment]
I've built out the basic `MapboxAccountManager` API and refactored the Telemetry initialization process to support being started in multiple locations (`MapboxAcccountManager` and `MapView`).  I've successfully tested the `MapView` setup to confirm that it still starts and stops as it's always done.  Next up is to convert the TestApp to use `MapboxAccountManager` and confirm that Telemetry works as desired there too.

**Comment by bleege** [comment]
I have now added `MapboxAccountManager.start()` to the TestApp's custom Application object called `MapboxApplication` while leaving the Access Token setup in the TestApp's activities that contained `MapView`s.  Afterwards I successfully tested the Telemetry process and confirmed that it did start from the Application object and stopped itself from restarting when the different `MapView`s loaded.

Next up is to remove all the Access Token's from the TestApp's activities so that only `MapboxAccountManager.start()` is used.  Once this is done we'll have both use cases implemented and tested.

**Comment by bleege** [comment]
I just refactored the TestApp to remove `MapView.setAccessToken()` uses, both programmatically and via Layout XML.  The TestApp continued to work as expected relying on the `MapboxAccountManager.start()` in the Application object.

Things are looking pretty good overall.  Just need to do another round of testing to confirm that things are as good as they currently appear as well as one last specific test of setting `MapboxAccountManager.start()` in an Activity's `onCreate()` method instead of the Application's.

**Comment by bleege** [comment]
Documenting Workflows

**Ways To Set Access Token**
* MapboxAccountManager
* MapView.setAccessToken()
* MapboxMap.setAccessToken()
* XML Layout

**MapView Flow Chart (Each Step Is Progressive From Top To Bottom**
* MapView Constructors
  * Processes XML Layout via AttributeSet
  * Process MapboxMapOptions
* MapView.initialize()
  * Common initialization routine for all constructors
* MapView.setInitialState()
  * Sets Access Token via MapboxMap.setAccessToken()
    * Looks for MapboxAccountManager first
    * Looks for MapboxMapOptions (XML attributes or MapboxMapOptions Builder)
* onCreate()
	* Validate Access Token

**MapView.setAccessToken()**
* Called from MapboxMap.setAccessToken()
  * XML Layout is routed through MapboxMapOptions now

**What Access Token Source Of Truth Is Being Used?**
* If `MapboxAccountManager.getInstance()` is null then it's MapView style.
* If `MapboxAccountManager.getInstance()` is NOT NULL then it's MapboxAccountManager.

**Deprecated Now, Will Be Removed in 5.0.0**
* MapboxMap.setAccessToken()
* MapboxMap.getAccessToken()
* MapView.setAccessToken()
* MapView.getAccessToken()

**Comment by bleege** [comment]
Squashed, Rebased, and Merged!
