### ISSUE TITLE
Port pitched circle rendering from gl-js

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#5006]
https://github.com/mapbox/mapbox-gl-js/pull/2544
https://github.com/mapbox/mapbox-gl-test-suite/issues/87

**Comment by jfirebaugh** [comment]
Looks like https://github.com/mapbox/mapbox-gl-js/commit/eab813ce5da40be91aeac6e26a80a849967f1dce needs to be ported as a prerequisite.

**Comment by brunoabinader** [comment]
> Looks like mapbox/mapbox-gl-js@eab813c needs to be ported as a prerequisite.

Done in 62b4dd554ab4df891221b1e43bda5a0f5dc1741a.
