### ISSUE TITLE
Mapbox 4.0.0 Changes NativeLibraryDir

### ISSUE THREAD

**Issue by afathman** [mapbox/mapbox-gl-native#5009]
When comparing two version of my app (where the only diff is I'm using Mapbox 4.0 instead of 3.2), calling  getApplicationInfo().nativeLibraryDir returns two different values. This causes my app to crash as I'm using native libraries, and it can no longer find those libraries.

**Platform:Android** 
**Mapbox SDK version:4.0.0**

### Expected behavior
getApplicationInfo().nativeLibraryDir should return the same value.

**Comment by bleege** [comment]
Can you tell us more about what devices you're testing on as well as what ABIs the native code is compiled for?  Also, does the app have any other dependencies that ship with native code?  Please note that as of `4.0.0` the SDK ships both arm32 and arm64 ABI, while `3.2.0` only had arm32.  Android only uses 1 ABI at runtime so depending on the app's configuration and ABI support this could likely be the issue.
