### ISSUE TITLE
osxapp crashes moving window to LoDPI monitor

### ISSUE THREAD

**Issue by geografa** [mapbox/mapbox-gl-native#5010]
When moving an application's window from one window to next (either LoDPI to HiDPI or vice versa) the application crashes. The following report was generated:
https://gist.github.com/geografa/4206e6542ee3d9102e0e5b0eabed92df

Latest commit from @brunoabinader `12258215af1cee598c203b85e9c342bd9900b088`

**Platform:** OSX
### Steps to trigger behavior

move window from one low or high DPI display to another.
### Expected behavior

Window stays open.
### Actual behavior

Window disappears and application crashes

**Comment by 1ec5** [comment]
A previous issue reported that the map would go blank but not crash: #3451.

**Comment by jfirebaugh** [comment]
⇢ #6654
