### ISSUE TITLE
Clamping line-width to 16?

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-native#502]
@kkaefer any particular reason why we do this [here](https://github.com/mapbox/mapbox-gl-native/blob/master/src/renderer/painter_line.cpp#L23-L27)? We don't do it in [js](https://github.com/mapbox/mapbox-gl-js/blob/mb-pages/js/render/draw_line.js#L14-L15) and it seems to me there are plenty of styles with larger line widths. Can I axe the limit or does it need to stay?

**Comment by ansis** [comment]
Clamping to 16 was fixed in https://github.com/mapbox/mapbox-gl-native/commit/166a3e21fac8632cdf5afdf4d38bf429e45dc699.

https://github.com/mapbox/mapbox-gl-native/pull/1343 switches away from GL_POINTS.
