### ISSUE TITLE
Annotation views on macOS

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5035]
The iOS and OS X versions of MGLMapView had nearly identical annotation implementations up until annotation views landed on iOS in #4801. @boundsj did a great job keeping the implementation clean, so porting it to OS X should mostly be a copy-paste job.

Along the way, it may be possible to directly share MGLAnnotationImage and MGLAnnotationView between the two SDKs in platform/darwin/ the way the other annotation classes are shared. The downside to sharing MGLAnnotationView would be limited Interface Builder support. We’d need to conditionally make MGLAnnotationView inherit from UIView on iOS and NSView on OS X with conditional compilation, yet IB lost the ability to understand preprocessor commands in Xcode 6.

**Comment by Zakalicious** [comment]
Am I correct that MGLAnnotationViews have not made it into the 0.15.1 release of the macos SDK?
