### ISSUE TITLE
Draggable annotation views

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5036]
Like MKAnnotationView in MapKit, MGLAnnotationView should have a `draggable` property that, when set to `YES`, allows the user the relocate the annotation by long-pressing on it and dragging it. During the dragging gesture, the map remains still. (MKPinAnnotationView additionally levitates slightly above the map while being dragged and animates the beginning and end of the gesture.)

The Android SDK equivalent of this feature is being tracked in #2450.

/cc @boundsj

**Comment by 1ec5** [comment]
Until this feature is implemented, the workaround is to keep track of the annotation yourself; when the user long-presses at a given location, check if the gesture took place at the annotation’s coordinates. If it did, set the map view’s `scrollEnabled` to `NO` and install your own pan gesture recognizer that changes the annotation’s coordinates.

**Comment by frederoni** [comment]
Just pushed a branch that seems to be working well. It's still WiP as I'm not aware of all the implications.
I'm hesitating about if the view should handle updating the position or if that should be delegated back to the implementer through `MGLMapViewDelegate` or `MGLAnnotationViewDelegate` (`annotationViewWasDraggedToLocation:`)

I do get the concerns about using two gesture recognizers per view but I don't see any performance decrease comparing 1000 draggable vs 1000 non-draggable annotation views.

Not a fan of updating the `mapView` property on the annotationView in `MGLMapView -updateAnnotationViews` so let me know if you have any good ideas how to get around that.
