### ISSUE TITLE
Custom user location annotation view

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5037]
MGLMapView should call `-[MGLMapViewDelegate mapView:viewForAnnotation:]` to get the MGLAnnotationView to display for MGLUserLocation. This would allow client code to completely customize the user dot’s appearance. If `-mapView:viewForAnnotation:` returns `nil`, MGLMapView should use an MGLUserLocationAnnotationView by default.

/cc @boundsj @friedbunny

**Comment by 1ec5** [comment]
This will be a lot more elegant once we implement #5039.

**Comment by KevinHu2014** [comment]
@1ec5 
How about Android?
Is it possible to custom user location annotation view?

**Comment by tobrun** [comment]
@KevinHu2014 at this point we haven't migrated the `MyLocationView` component on Android to use annotation views yet but we expose some API to customise it. Take a look at [MyLocationViewSettings](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationViewSettings.java), this class contains our public API to change the appearance of `MyLocationView`.

**Comment by KevinHu2014** [comment]
@tobrun Thanks a lot~

**Comment by friedbunny** [comment]
Fixed by #5882.
