### ISSUE TITLE
When map is tilted, annotation views don’t scale by distance from camera

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5040]
When the map is tilted, an GL icon or point annotation grows as the camera moves toward it and shrinks as the camera moves away from it (#2186). However, annotation views maintain their size. This behavior is consistent with the user dot, but scaling would help by reinforcing the illusion of a tilted map.

/cc @boundsj @friedbunny

**Comment by friedbunny** [comment]
This will be a good option to have. MapKit maintains constant size, while Google scales by distance — neither gives you a choice.

**Comment by 1ec5** [comment]
I think the default should be to scale, for consistency with GL annotations.

**Comment by boundsj** [comment]
@1ec5 @friedbunny while https://github.com/mapbox/mapbox-gl-native/pull/5085 offers a solution it is not one that can be shared with @tobrun. It also defaults to not scale by default -- for consistency with other SDKs and also because [there is an ongoing discussion and it seems like things may eventually change in GL annotation land](https://github.com/mapbox/mapbox-gl-native/issues/2186).

Example of 1000 scaled, flattened annotation views:

![scaled_flat_annotations](https://cloud.githubusercontent.com/assets/63186/15440991/374ecc4c-1e8d-11e6-9422-c716a750a450.gif)

**Comment by 1ec5** [comment]
> It also defaults to not scale by default -- for consistency with other SDKs and also because [there is an ongoing discussion and it seems like things may eventually change in GL annotation land](https://github.com/mapbox/mapbox-gl-native/issues/2186).

I’ve come around to the idea that unscaled annotations are more useful to more use cases than scaled annotations, despite scaling making for better demos. However, point annotations are still rendered by GL by default, and GL-rendered annotations are unconditionally scaled. I think it would be a jarring experience for you to adopt annotation views and suddenly see behaviors like scaling change.

**Comment by friedbunny** [comment]
I don’t think we should constrain view-based annotations based on the current (in)capabilities of GL annotations. The difference may be potentially jarring, but unscaled is the default we’re converging on for both, even if we don’t know when GL will support it.

I wonder how common mix-and-match views-and-GL annotations will be. If a developer uses both and thinks the scale difference is unsightly, they’re likely to seek out the `MGLViewAnnotation.scaled` option. I’m not sure that the opposite will be true — I’d be afraid developers won’t know the unscaled option exists.

**Comment by 1ec5** [comment]
What if we default to scaling for now but change the default for both types of annotations when GL annotations gain that capability too?

**Comment by boundsj** [comment]
> What if we default to scaling for now but change the default for both types of annotations when GL annotations gain that capability too?

I've been thinking about it and while there does not seem to be a perfect solution here, I think that aiming for as much consistency as possible between GL and view annotations makes the most sense. So, I will rework https://github.com/mapbox/mapbox-gl-native/pull/5085 to default to scaling and we can sync up again in the future when GL default behavior changes (as @1ec5 suggested). The downside of this is that is that the flip will fundamentally change how applications built on this strategy behave when they adopt some future version that does not scale by default. So, we will need to take care to document that change and respond to inevitable bug reports.

**Comment by jfirebaugh** [comment]
Given that the consensus in https://github.com/mapbox/mapbox-gl-js/issues/2541 was that scaling by default was better, I suspect it will always be the style spec default.

**Comment by 1ec5** [comment]
Wouldn’t it be possible for `mbgl::PointAnnotation`s (whose styling is ultimately determined by the SDK) to default to a different scaling behavior than GL circle features?
