### ISSUE TITLE
Add Checks To Start Telemetry In Android 6+ After Permissions Granted

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#5045]
Prior to Android 6.0 user granted permissions were granted at app install time which means that Ambient Telemetry would start immediately as part of the Telemetry start up process.  This is not the case with Android 6.0 as permissions are now approved in app via dialog (similar to iOS).  This change makes it likely that app's starting for the first time may not have had location permissions approved, thus making it that Ambient Telemetry mode doesn't start the first time the app is run.

Unfortunately the Android API for listening for Permissions granted is [tied specifically to Activities](http://developer.android.com/reference/android/support/v4/app/ActivityCompat.OnRequestPermissionsResultCallback.html#onRequestPermissionsResult%28int,%20java.lang.String[],%20int[]%29) and not generic callbacks (ie, Anonymous Classes).  This leaves two options available for implementing this is in a manor that doesn't impose any responsibilities upon implementing app developers:

* Run a timed loop at startup (if permission not already generated) that checks for permissions granted status
* Have Mapbox ask for Location Permissions

I believe the timed loop option is the better choice as it doesn't force the developer's hand as to when the Location permissions would be requested (ie, shown to the user) in Android 6+.

**Comment by bleege** [comment]
Documenting the current lay of the land both for how Mapbox Telemetry currently work as well as how Android 6 Run time permissions work.

#### Current Location Startup Flow (top to bottom)

1. `MapboxAccountManager.start()`  ||  `MapView.onCreate()`
1. `MapboxEventManager.initialize()`
1. `MapboxEventManager.setTelemetryEnabled()`
  * If GPS enabled (all good), if not then try to Start Ambient Mode
1. `LocationServices.toggleGPS()`
  * Check permissions first
  * If true, then enable either GPS or Ambient
  * If false, then return before trying to start Location to prevent Exception from being thrown

#### Android 6 User Granted Permissions

There are 2 scenarios that must be accounted for in this environment, namely **the End User approves the permission** and **the End User revokes the permission**.  The End User will **approve or reject the permission in the app via a system dialog** that appears when the app developer requests it.  To **revoke a permission however, the End User needs to open the App Permissions UI in the Android Settings app**.  According to [different sources](https://inthecheesefactory.com/blog/things-you-need-to-know-about-android-m-permission-developer-edition/en) around [the Web](http://stackoverflow.com/questions/32958449/android-marshmallow-callback-when-user-revokes-permissions-from-settings) when a Permission is revoked for an app [that app's process is immediately terminated](http://stackoverflow.com/questions/32718933/broadcast-action-on-permission-change-in-android-m).  I looked for official confirmation on the [Android developer site](https://developer.android.com/)... but didn't find anything.  However, I did test this on a Nexus 5x with Location Permission and found that it is true as removing the Location Permission immediately terminated the app.

**Comment by bleege** [comment]
I added a Handler that checks every 30 seconds for approval of Location permissions so that Ambient Telemetry can be started asynchronously.  This Handler ONLY RUNS if at the initial setup time of Telemetry the Location Permissions haven't been granted.  I successfully tested the setup flow (see logs below) by doing the following:

1. Remove TestApp from Device (Nexus 5x running API 23)
1. Install TestApp on Device
1. Open `MyLocationToggleActivity` first with no permissions granted
1. Confirm that Telemetry Service has started, but no Ambient nor GPS LocationServices are running
1. Tap My Location FAB to enable Location.
  * This triggers the Android System Dialog for approving Location permissions
1. Accept Location permission
  * GPS Started via LocationServices
1. Location Data is recorded
1. Tap My Location FAB to disable Location
1. GPS Mode switches to Ambient Mode

```
05-16 18:54:03.708 11471-11471/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Telemetry initialize() called...
05-16 18:54:03.710 11471-11471/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Right before Telemetry set enabled in initialized()
05-16 18:54:03.711 11471-11471/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: setTelemetryEnabled(); this.telemetryEnabled = false; telemetryEnabled = true
05-16 18:54:03.711 11471-11471/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: Starting Telemetry Up!
05-16 18:54:03.717 11471-11471/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions are not good.  Need to do some looping to check on stuff.
05-16 18:54:13.727 11471-11886/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: No events in the queue to send so returning.
05-16 18:54:13.755 11471-11471/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions not granted yet... let's try again in 30 seconds
05-16 18:54:14.208 11471-11471/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Telemetry initialize() called...
05-16 18:54:14.208 11471-11471/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Mapbox Telemetry has already been initialized.
05-16 18:54:14.251 11471-11471/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: flushEventsQueueImmediately() called...
05-16 18:54:14.252 11471-11471/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: turnstile event pushed.
05-16 18:54:15.103 11471-11907/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: response code = 204 for events 2
05-16 18:54:43.787 11471-11471/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions not granted yet... let's try again in 30 seconds
05-16 18:55:13.816 11471-11471/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions not granted yet... let's try again in 30 seconds
05-16 18:55:43.818 11471-11471/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions finally granted, so starting Ambient if GPS isn't already enabled
05-16 18:57:14.408 11471-14700/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: response code = 204 for events 27
05-16 19:00:14.431 11471-17493/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: response code = 204 for events 33
```

**Comment by bleege** [comment]
Verified that restarting the app once the app has been installed and location permissions were approved in a previous run that the Handler DOES NOT run and Ambient Telemetry runs immediately at startup just as it does in < Android 6.

```
05-16 19:23:42.663 24342-27106/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: response code = 204 for events 1
05-16 19:24:24.252 24342-24342/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: flushEventsQueueImmediately() called...
05-16 19:24:24.254 24342-27913/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: No events in the queue to send so returning.
05-16 19:24:43.393 27990-27990/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Telemetry initialize() called...
05-16 19:24:43.397 27990-27990/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Right before Telemetry set enabled in initialized()
05-16 19:24:43.399 27990-27990/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: setTelemetryEnabled(); this.telemetryEnabled = false; telemetryEnabled = true
05-16 19:24:43.399 27990-27990/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: Starting Telemetry Up!
05-16 19:24:43.406 27990-27990/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions are good, see if GPS is enabled and if not then setup Ambient.
05-16 19:24:53.431 27990-28166/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: No events in the queue to send so returning.
```

**Comment by bleege** [comment]
While running the TestApp again (Location permissions approved in a previous run) I then open the App Permissions UI in the Android Settings widget and then removed Location permissions from the TestApp.  As expected the TestApp's process terminated, the app restarted, and at startup the permission wasn't found so the Async Location Permissions Handler started running again as it should.

```
05-16 19:20:32.297 24342-26275/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: response code = 204 for events 5
05-16 19:23:42.663 24342-27106/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: response code = 204 for events 1
05-16 19:24:24.252 24342-24342/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: flushEventsQueueImmediately() called...
05-16 19:24:24.254 24342-27913/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: No events in the queue to send so returning.
05-16 19:24:43.393 27990-27990/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Telemetry initialize() called...
05-16 19:24:43.397 27990-27990/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Right before Telemetry set enabled in initialized()
05-16 19:24:43.399 27990-27990/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: setTelemetryEnabled(); this.telemetryEnabled = false; telemetryEnabled = true
05-16 19:24:43.399 27990-27990/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: Starting Telemetry Up!
05-16 19:24:43.406 27990-27990/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions are good, see if GPS is enabled and if not then setup Ambient.
05-16 19:24:53.431 27990-28166/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: No events in the queue to send so returning.
05-16 19:27:38.909 30063-30063/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Telemetry initialize() called...
05-16 19:27:38.912 30063-30063/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Right before Telemetry set enabled in initialized()
05-16 19:27:38.913 30063-30063/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: setTelemetryEnabled(); this.telemetryEnabled = false; telemetryEnabled = true
05-16 19:27:38.913 30063-30063/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: Starting Telemetry Up!
05-16 19:27:38.919 30063-30063/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions are not good.  Need to do some looping to check on stuff.
05-16 19:27:48.930 30063-30063/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions not granted yet... let's try again in 30 seconds
05-16 19:27:48.944 30063-30239/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: No events in the queue to send so returning.
05-16 19:28:18.965 30063-30063/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions not granted yet... let's try again in 30 seconds
```

**Comment by bleege** [comment]
Things appear to be working as expected / needed.  I'm going to pause work on this for a night and review it with fresh 👀 before merging.  I'm also open to using different handler time delay for the Handler than the initial 10 second delay and 30 second loop.

**Comment by mikemorris** [comment]
Is there any way to register an event listener for a `GPS permission granted` event instead of checking every 30 seconds for a permission which may never be granted?

**Comment by bleege** [comment]
@mikemorris Nope.  I wish there were.  See my [original comment in the ticket description](https://github.com/mapbox/mapbox-gl-native/issues/5045#issue-154944108) for more information.

**Comment by bleege** [comment]
Ran through the same [test scenario](https://github.com/mapbox/mapbox-gl-native/issues/5045#issuecomment-219585138) as the original implementation and confirmed that the Telemetry infrastructure started as expected and the Ambient Location loop checker worked as expected.  The second to last lines of the first log block show the touch and my user location data sent in when the FAB was first pushed.  The last line of the first log block shows two ambient location data events recorded after the FAB was pressed again to disable user location tracking.  Those two location events are shown in the second log block below and are "ambient location events" that fired and that Telemetry picked up.

```java
05-17 11:25:47.606 30386-30386/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Telemetry initialize() called...
05-17 11:25:47.608 30386-30386/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Right before Telemetry set enabled in initialized()
05-17 11:25:47.609 30386-30386/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: setTelemetryEnabled(); this.telemetryEnabled = false; telemetryEnabled = true
05-17 11:25:47.609 30386-30386/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: Starting Telemetry Up!
05-17 11:25:47.618 30386-30386/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions are not good.  Need to do some looping to check on stuff.
05-17 11:25:57.631 30386-30386/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions not granted yet... let's try again in 30 seconds
05-17 11:25:57.651 30386-30768/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: No events in the queue to send so returning.
05-17 11:26:27.635 30386-30386/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions not granted yet... let's try again in 30 seconds
05-17 11:26:30.017 30386-30386/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Telemetry initialize() called...
05-17 11:26:30.018 30386-30386/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Mapbox Telemetry has already been initialized.
05-17 11:26:30.066 30386-30386/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: flushEventsQueueImmediately() called...
05-17 11:26:30.067 30386-30386/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: turnstile event pushed.
05-17 11:26:30.956 30386-31264/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: response code = 204 for events 2
05-17 11:26:57.647 30386-30386/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions not granted yet... let's try again in 30 seconds
05-17 11:27:27.683 30386-30386/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions not granted yet... let's try again in 30 seconds
05-17 11:27:57.717 30386-30386/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions not granted yet... let's try again in 30 seconds
05-17 11:28:27.742 30386-30386/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions not granted yet... let's try again in 30 seconds
05-17 11:28:57.777 30386-30386/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions not granted yet... let's try again in 30 seconds
05-17 11:28:58.723 30386-1320/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: response code = 204 for events 82
05-17 11:29:27.808 30386-30386/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions not granted yet... let's try again in 30 seconds
05-17 11:29:57.834 30386-30386/com.mapbox.mapboxsdk.testapp I/MapboxEventManager: Permissions finally granted, so starting Ambient if GPS isn't already enabled
05-17 11:31:58.331 30386-4491/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: response code = 204 for events 20
05-17 11:34:58.661 30386-7282/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: response code = 204 for events 2
```
_Full Test Run_

```java
05-17 11:32:17.802 30386-30386/com.mapbox.mapboxsdk.testapp D/LocationServices: onLocationChanged()...Location[network 37.775691,-122.413676 acc=20 et=+20h21m1s940ms {Bundle[mParcelledData.dataSize=736]}]
05-17 11:32:17.805 30386-30386/com.mapbox.mapboxsdk.testapp D/TelemLocationReceiver: location received = Location[network 37.775691,-122.413676 acc=20 et=+20h21m1s940ms {Bundle[mParcelledData.dataSize=736]}]
05-17 11:34:05.693 30386-30386/com.mapbox.mapboxsdk.testapp D/LocationServices: onLocationChanged()...Location[network 37.775663,-122.413765 acc=20 et=+20h22m49s830ms {Bundle[mParcelledData.dataSize=736]}]
05-17 11:34:05.696 30386-30386/com.mapbox.mapboxsdk.testapp D/TelemLocationReceiver: location received = Location[network 37.775663,-122.413765 acc=20 et=+20h22m49s830ms {Bundle[mParcelledData.dataSize=736]}]
```
_Ambient Location Updates Picked Up By Telemetry (Sent In Via Last Line in First Block)_

**Comment by bleege** [comment]
While typing in the previous comment the same Ambient Location events (Network based) fired again and the Telemetry infrastructure picked them up as expected.  +1 to taking a long time to type.  😄 

```java
05-17 11:37:58.374 30386-9049/com.mapbox.mapboxsdk.testapp D/MapboxEventManager: response code = 204 for events 2
```

```java
05-17 11:36:36.717 30386-30386/com.mapbox.mapboxsdk.testapp D/LocationServices: onLocationChanged()...Location[network 37.775691,-122.413676 acc=20 et=+20h25m20s849ms {Bundle[mParcelledData.dataSize=736]}]
05-17 11:36:36.724 30386-30386/com.mapbox.mapboxsdk.testapp D/TelemLocationReceiver: location received = Location[network 37.775691,-122.413676 acc=20 et=+20h25m20s849ms {Bundle[mParcelledData.dataSize=736]}]
05-17 11:37:36.782 30386-30386/com.mapbox.mapboxsdk.testapp D/LocationServices: onLocationChanged()...Location[network 37.775663,-122.413765 acc=20 et=+20h26m20s913ms {Bundle[mParcelledData.dataSize=928]}]
05-17 11:37:36.788 30386-30386/com.mapbox.mapboxsdk.testapp D/TelemLocationReceiver: location received = Location[network 37.775663,-122.413765 acc=20 et=+20h26m20s913ms {Bundle[mParcelledData.dataSize=928]}]
```

**Comment by bleege** [comment]
Squashed and Merged!
