### ISSUE TITLE
cannot load mapview 

### ISSUE THREAD

**Issue by greasonGuo** [mapbox/mapbox-gl-native#5046]
**Platform:** Android
**Mapbox SDK version:** 4.0.1

### Steps to trigger behavior

 1. build.gradle
```
    compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:4.0.1@aar'){
        transitive=true
    }
```

 2.xml
```
<com.greason.mapbboxtest3.MapViewSelf
        android:id="@+id/mapview"
        android:layout_width="match_parent"
        android:layout_height="100dp"
        mapbox:style_url="@string/style_mapbox_streets"
        />
```

then , findViewById(R.id.mapview) and set  mapView.setAccessToken 

in this case , mapview can load data and show successfully.

but if i add the below content in build.gradle ,i won't work  . because I have to use the below setting in my project .
```
splits {
        abi {
            enable true
            reset()
            include 'armeabi'
            universalApk true
        }
    }
```

### Expected behavior
 mapview can load data and show successfully in my expect.
### Actual behavior
mapview is black in screen.

**Comment by tobrun** [comment]
@greasonGuo 
thank you for reaching out and reporting your problem. 
Will need to do some tests related to [ABI splitting](http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits).

**Comment by tobrun** [comment]
@greasonGuo 
Which device are you testing on?

First tests with this setup on a Nexus 6P is working as designed:

```
    splits {
        abi {
            enable true
            reset()
            include 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a' //select ABIs to build APKs for
            universalApk true //generate an additional APK that contains all the ABIs
        }
    }
```

Since this will output:

![screen shot 2016-05-17 at 09 14 50](https://cloud.githubusercontent.com/assets/2151639/15314061/dafeadec-1c0f-11e6-9bbd-636f235e84af.png)

**Comment by tobrun** [comment]
I also did a test with:

```
    splits {
        abi {
            enable true
            reset()
            include 'armeabi' //select ABIs to build APKs for
            universalApk true //generate an additional APK that contains all the ABIs
        }
    }
```

That is indeed resulting in black screen.

@greasonGuo 
 - what is the use case of the need for `armeabi`? 
 - is it possible to use `armeabi-v7` instead? (v7 was introduced in 2010-2011)

**Comment by greasonGuo** [comment]
@tobrun  
Mi note  , sansung , meizi ,etc , almost all android phones i have .
The setting i refer to is just used to make the app in small size reduced by half almost.

 Recently , i find a reason may lead to this case that mapview canot load datas correctly. That's the code System.loadLibrary("mapbox-gl")  in NativeMapView class . Mobile-App canot load the file libmapbox-gl.so , could you send  me this .os file , i will appreciate it for your help , and looking for your response . Thanks .

**Comment by greasonGuo** [comment]
@tobrun  sorry ,it's my fault , it should be  " universalApk false "
 splits {
        abi {
            enable true
            reset()
            include 'armeabi' //select ABIs to build APKs for
            universalApk false
        }
    }

**Comment by greasonGuo** [comment]
@tobrun sorry ,it's my fault , it should be " universalApk false "
splits {
       abi {
              enable true
              reset()
             include 'armeabi' //select ABIs to build APKs for
             universalApk false
           }
}

**Comment by greasonGuo** [comment]
@tobrun  more unused things in armeabi-v7 , so i must remove that.

**Comment by tobrun** [comment]
@greasonGuo great to hear you were able to [resolve it](https://github.com/mapbox/mapbox-gl-native/issues/5046#issuecomment-219707110). Going to close

**Comment by greasonGuo** [comment]
@tobrun  
Ok , help a lot , thanks .
