### ISSUE TITLE
Mapbox-GL why not using AGG for map rendeing?

### ISSUE THREAD

**Issue by kevin4z** [mapbox/mapbox-gl-native#5052]
- [AGG (Anti-Grain Geometry)](http://www.antigrain.com/) is a High Quality Rendering Engine for C++.
 - [OpenGL ES](https://www.khronos.org/opengles/) is a royalty-free, cross-platform API for full-function 2D and 3D graphics on embedded systems.

But AGG seems more efficient than OpenGL ES in map rendeing, like [Mapnik](http://mapnik.org) is using AGG.

**Q1:**  [Mapbox-GL](https://github.com/mapbox/mapbox-gl-native) why not use AGG but use OpenGL? 

**Q2:**  What's the difference between AGG and OpenGL ES?

Thanks! **:)**

**Comment by mourner** [comment]
Thanks for looking into Mapbox GL! This is a place to report issues though, not to ask questions about rendering engines. Try StackOverflow for this instead.
