### ISSUE TITLE
Restore PressForMarker To TestApp

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#5060]
The PressForMarkerActivity is used as a test for tap recognition as well as removal of Markers / Annotations from the map.  It was removed as part of the Great TestApp Refactoring of #4365 #4570 and now needs to be brought back.

**Comment by tobrun** [comment]
I removed this from the test app since the functionality is also found in [InfoWindowActivity](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/infowindow/InfoWindowActivity.java#L104).
