### ISSUE TITLE
RTL language support

### ISSUE THREAD

**Issue by moallemi** [mapbox/mapbox-gl-native#5072]
**Platform:** Android
**Mapbox SDK version:** 4.0.1

### Steps to trigger behavior

 1. Open Sample App and set center of mapView to `35.6961, 51.4231` and zoom level 12

```java
mapboxMap.setCameraPosition(new CameraPosition.Builder()
      .target(new LatLng(35.6961, 51.4231))
      .zoom(12)
      .bearing(0)
      .tilt(0)
      .build());
```
output is: 

![mapbox](https://cloud.githubusercontent.com/assets/1250691/15394556/e669f170-1de8-11e6-9a1d-4997493e591b.png)

As you see in screenshot the titles or rendered wrong in `Persian` Language. for example I marked 3 labels:
 `بهارستان` is wrongly rendered as `ن ا ت س ر ا ه ب` 
 `بازار` is wrongly rendered as `ر ا ز ا ب` 
 `سنگلج` is wrongly rendered as `ج ل گ ن س` 

Would you please add RTl Language support for mapbox-gl-native?

**Comment by tobrun** [comment]
Quoting @mikemorris from https://github.com/mapbox/mapbox-gl-native/issues/1259#issuecomment-92280172:

> Known issue, we haven't added support for text shaping (connected characters) or right-to-left scripts yet. 

You can follow up on this issue in https://github.com/mapbox/mapbox-gl/issues/4
