### ISSUE TITLE
Optimise view reuse cache with Marker Views

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5076]
Marker view integration on Android landed with #3276.

This integration is backed up by an adapter approach that uses view recycling. Currently there is no limit on the amount of Views in the cache (child views of MapView) and there is a behaviour when panning in and out the viewport that results in growing the cache while it should be reusing the items in the cache.

**Example**:
We show 100 view marker but panning quickly a couple of times results in a cache with 147 views.

![device-2016-05-20-132241](https://cloud.githubusercontent.com/assets/2151639/15426315/044c557a-1e8e-11e6-92f0-fd5734fad225.png)

**Comment by bleege** [comment]
@tobrun Do we want to impose a limit on the number of items in the cache or is this issue simply stating that the current implementing isn't re-using items already in the cache and that needs to be changed to do so?

**Comment by tobrun** [comment]
@bleege 

Below you see the problem in action, you can see our viewcache size increasing to values above 100 while there are only 100 MarkerViews.

![ezgif com-video-to-gif 31](https://cloud.githubusercontent.com/assets/2151639/15819025/f70f6d92-2be0-11e6-8830-2a82d9f324ab.gif)

this is now resolved eb5ff35 with an increased cache size as seen here, where the size doesn't go over the 100 markers.

![ezgif com-video-to-gif 30](https://cloud.githubusercontent.com/assets/2151639/15819032/fedd20e6-2be0-11e6-867e-442c5cb2c389.gif)

**Comment by tobrun** [comment]
Merged in #5250 onto `release-v4.1.0` branch
