### ISSUE TITLE
Japanese label is sometimes broken

### ISSUE THREAD

**Issue by epsg3857** [mapbox/mapbox-gl-native#5077]
Platform: iOS
Mapbox SDK version: 3.2.2

For example,
latitude=35.649471
longitude=139.749626
zoomLevel=17

Broken
![label_broken](https://cloud.githubusercontent.com/assets/19490953/15428832/a8c3a0aa-1ed8-11e6-8ceb-84b3f410752d.png)

Become OK when you reload
![label_ok](https://cloud.githubusercontent.com/assets/19490953/15428889/f7deddf8-1ed8-11e6-9181-678bd2422ad2.png)

Occur in various places.
also mapbox-gl-js.

**Comment by friedbunny** [comment]
Thanks for the report — this is #1444 and #1681, the root issue being with how we store CJK characters in memory. We’re working on improving CJK support (see https://github.com/mapbox/mapbox-gl/issues/4), but it’s a difficult, long-term collection of tasks.

**Comment by 1ec5** [comment]
mapbox/mapbox-gl#4 is unrelated to this issue.

**Comment by friedbunny** [comment]
Err, suppose I should have couched that more generally.
