### ISSUE TITLE
Add rotation to MarkerView

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5081]
Google exposes customization of **rotation**:

> The orientation of the marker, specified in degrees clockwise. The default position changes if the marker is flat. The default position for a flat marker is north aligned. When the marker is not flat, the default position is pointing up and the rotation is such that the marker is always facing the camera.

Now that #3276 landed we can implement this in MarkerView/MarkerViewOptions.

**Comment by tobrun** [comment]
Example of rotation set to `45`:

![device-2016-05-20-180847](https://cloud.githubusercontent.com/assets/2151639/15434167/ee59179e-1eb5-11e6-8d30-a981ab40bc4d.png)

**Comment by tobrun** [comment]
The above works for setting it up once:

```java
        mMapboxMap.addMarkerView(new MarkerViewOptions()
                            .position(LAT_LNGS[i])
                            .title(String.valueOf(i))
                            .infoWindowOffset(new Point(0, 86))
                            .selectAnimatorResource(R.animator.scale_up)
                            .deselectAnimatorResource(R.animator.scale_down)
                            .rotation(45)
```

but doesn't do anything immediately when we call `marker.setRotation(90)`. 
Also it would be nice to be able to animate this change.

**Comment by tobrun** [comment]
I created a link between calling `setRotation` and `MapboxMap`. If you call `setRotate` periodically, eg:

```java
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                currentDegree = currentDegree + 45;
                for (MarkerView m : mList) {
                    m.setRotation(currentDegree);
                }
                rotate();
            }
        }, 1500);
```

You will see this result:

![ezgif com-video-to-gif 17](https://cloud.githubusercontent.com/assets/2151639/15434672/4f287702-1eb8-11e6-918d-5c4aba96cbea.gif)

**Comment by Schumi09** [comment]
Hi @tobrun ,

thanks for your work on the roation, this should help me a lot and I can't wait to try it out with the setting of alpha level (didn't seem to be included in today's snapshot).
However, I got a little request. Would it be possible to pass float or double to the MarkerViewOptions constructor? I have seen that all the methods in the background take float anyway.

**Comment by Schumi09** [comment]
Nevermind, found out that there is some workaround probably
`MarkerView marker = map.addMarker(markerViewOptions);
            marker.setAlpha(0.95);`
