### ISSUE TITLE
[Offline] Add possibility to know how many tiles are used by the current packs

### ISSUE THREAD

**Issue by mathieugerard** [mapbox/mapbox-gl-native#5086]
The size of the offline database is limited to 6000 tiles. However, when a pack is downloaded, many more resources than just tiles are downloaded. We know the number of resource from the download progress but we have no way to know how many of those resources actually count towards our limit.

Please let me know if there is any alternative way of computing the number of offline tiles already used.
Does the number of tiles downloaded depend on the screen density (normal vs retina)?

**Comment by 1ec5** [comment]
This information was added to the Android and iOS SDKs in #4874. You can try it out in Android SDK snapshots or [iOS SDK v3.3.0 alpha releases](https://github.com/mapbox/mapbox-gl-native/releases/).

> Does the number of tiles downloaded depend on the screen density (normal vs retina)?

No, but a Retina device will download different tiles than a non-Retina device.

**Comment by mathieugerard** [comment]
Awesome!
Sorry I didn't find #4874 before.
