### ISSUE TITLE
Satellite Styles V9 URL Is Incorrect

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#5087]
The new Mapbox V9 Styles were updated for Android in #4812, however the Satellite Streets style was not upgraded to use the new V9 style name which causes a black screen to show when used.  The style names are as follows:

**V8**
`satellite-hybrid-v8`

**V9**
`satellite-streets-v9`

/cc @tobrun

**Comment by tobrun** [comment]
:rocket:
