### ISSUE TITLE
max zoom > 18

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#509]
This was changed back in https://github.com/mapbox/mapbox-gl-native/issues/178 but should: 

1. Allow for zoom > 18
1. Allow for setting min/max from external API

**Comment by manuelwenner** [comment]
What about max zoom Level in mapbox-gl-native for android? When i try to set zoom level >18.0 it's ignored. 

Thanks in advance for your answers.

**Comment by tmpsantos** [comment]
> What about max zoom Level in mapbox-gl-native for android? When i try to set zoom level >18.0 it's ignored.
> 
> Thanks in advance for your answers

@manuelwenner It is currently hardcoded. Until we provide an API for that, you can tweak it at this variable here: https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/map/transform.hpp#L87

**Comment by manuelwenner** [comment]
Thanks @tmpsantos that worked perfect for me.

**Comment by petaren** [comment]
Is there an estimated time as to when an increase in max zoom level might be available? We would need a max zoom level of around 20 in my current project. Without it, it's unfortunately useless for us :(

**Comment by tmpsantos** [comment]
> Is there an estimated time as to when an increase in max zoom level might be available? We would need a max zoom level of around 20 in my current project. Without it, it's unfortunately useless for us :(

Not on the roadmap AFAIK, but you can change that on the code for now.

**Comment by petaren** [comment]
Okey, L87 in transform.hpp is blank. So what do I need to change to get it to work?

**Comment by mourner** [comment]
It's hardcoded here now: https://github.com/mapbox/mapbox-gl-native/blob/e63fb444993c16b158cf833ba4c4e66f81943fba/src/mbgl/map/transform_state.hpp#L76-L77

I think we should address this issue sooner, shouldn't be hard and is an often requested feature.

**Comment by franckt** [comment]
Hi, 
Any news about providing an api to set max zoom ?

**Comment by ansis** [comment]
@franckt max zoom is implemented in master and should be available in the next release

**Comment by bleege** [comment]
Re-opening as discussion with @kkaefer this morning revealed that the max zoom level in `mgbl` is actually 25.5.  We'll need to update the iOS and Android bindings added in PR #3712 to support this.

/cc @mapbox/mobile

**Comment by bleege** [comment]
Capturing discussing with @1ec5 this afternoon where he confirmed that the [20 in `transform_state.hpp`](https://github.com/mapbox/mapbox-gl-native/blob/b738087080b924061c4e6ce4c8b60ae4573f4f10/src/mbgl/map/transform_state.hpp#L88) is simply a default value and that if the bindings set a zoom higher (example 23) then Core GL will use and go to 23.

**Comment by bleege** [comment]
The new code in PR #3812 adds min and max zoom controls to Core GL so that all platforms will benefit.  It also updated the values in the Android annotation warnings.  The new values are:

```
MIN_ZOOM = 0.0
MAX_ZOOM = 25.5
```

**Comment by brunoabinader** [comment]
Possibly related: https://github.com/mapbox/mapbox-gl-native/issues/4168 / https://github.com/mapbox/mapbox-gl-native/issues/3644.
