### ISSUE TITLE
Can Mapbox GL Native run on windows how can i do it?

### ISSUE THREAD

**Issue by TGISer** [mapbox/mapbox-gl-native#5093]
**Platform:**
**Mapbox SDK version:**

### Steps to trigger behavior

 1.
 2.
 3.

**Comment by zuo1188** [comment]
anybody  want to launch the project?

**Comment by dbskccc** [comment]
the qt port compiled with mingw.
https://doc-snapshots.qt.io/qt5-5.9/location-plugin-mapboxgl.html
https://bugreports.qt.io/browse/QTBUG-60110

**Comment by tmpsantos** [comment]
Mapbox GL Qt now has a build that works with MSVC.
