### ISSUE TITLE
onCameraChangeListener

### ISSUE THREAD

**Issue by tuanht53** [mapbox/mapbox-gl-native#5095]
Platform:android
Mapbox SDK version: 4.0.1

i use onCameraChangeListener:
mapbox: called continuity when camera changing 
google map: only called to onCameraChange when camera actually changed and stopped move it

**Comment by tobrun** [comment]
Thanks for reaching out and reporting your problem.  Another user mentioned this in #4746, I'm going to close this as a duplicate. Putting this on my radar to look at for next release.
