### ISSUE TITLE
Animated Marker Example App Not Working

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#5107]
The `AnimatedMarkerActivity` test example is currently not working.  It should show a default marker moving on a straight line between Brussels and Washington, DC.  Currently however the marker is not displayed on the map.  This is likely due to changes from the build out of the View Based Annotations.

We also should remove the phrase `Experimental` from the Activity name as this should be a supported feature as part of the View Base Annotations API.

![device-2016-05-23-145256](https://cloud.githubusercontent.com/assets/989928/15482598/116f4662-20f6-11e6-9c6b-e6274222a8ed.png)

**Comment by tobrun** [comment]
I noticed this also, when zooming in a bit you can see the marker appearing again. My first guess is that this  isn't related to changes made by view annotations and this is an issue with gl based annotations.

**Comment by tobrun** [comment]
Confirming that his seems to be related to zoomlevel. I did a test animating at higher value:

![ezgif com-video-to-gif 19](https://cloud.githubusercontent.com/assets/2151639/15485510/08d64a4c-2140-11e6-8211-5e9291bc1628.gif)

**Comment by tobrun** [comment]
> We also should remove the phrase Experimental from the Activity name as this should be a supported feature as part of the View Base Annotations API.

This feature is both part of the GL based Annotations as the View based Annotations API. Both Marker as MarkerView expose `setPosition(LatLng position) and both will need to call the same JNI methods. The reason why I marked it experimental is that animations aren't smooth yet. This is something I'm trying to profile/measure and hoping that perf best practices as #5103 will resolve it.

**Comment by tobrun** [comment]
With help from @1ec5, we were able to find this is core bug and created a follow up issue in #5109. Going to close this in favour of #5109.
