### ISSUE TITLE
Javadoc for 4.1.0 release

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5113]
Ticket to track the javadoc for the 4.1.0 release:
 - [x] MyLocationView
  - [x] MyLocationViewSettings
  - [x] MapboxMap API
 - [x] View Annotations - https://github.com/mapbox/mapbox-gl-native/pull/5168
  - [x] MarkerViewManager
  - [x] MarkerViewAdapter
  - [x] MarkerViewClickListener
  - [x] MarkerView
  - [x] BaseMarkerViewOptions
  - [x] MarkerViewOptions
  - [x] MapboxMap API
 - [x] Snapshot API

**Comment by tobrun** [comment]
I'm applying the following [rules & conventions](http://blog.joda.org/2012/11/javadoc-coding-standards.html) when it comes to javadoc writing.

cc @bleege @zugaldia @cammace

**Comment by tobrun** [comment]
First PR for javadoc landed covering everything related to view annotations in https://github.com/mapbox/mapbox-gl-native/pull/5168

**Comment by tobrun** [comment]
Looked into javadoc for the snapshot API -> 👍  -> no actions required

**Comment by bleege** [comment]
@tobrun Remember that we need to get these PRs against the `4.1.0 Release` branch now and not `master` as that's what is producing the daily snapshots and what we'll use to produce future `4.1.0` releases.  I'll cherry pick the 2 commits from #5168 over to the release branch now.

**Comment by bleege** [comment]
I just completed cherry picking both commits from #5168 ( 5202effde524057a761e06805282fc2e339d3b7f and 6cfee1db7cade57fcf3a9d4a6dfbf3e90a85ea75) to the `release-android-v4.1.0` branch.

![screen shot 2016-05-27 at 10 28 30 am](https://cloud.githubusercontent.com/assets/989928/15612811/e22487ac-23f5-11e6-96e7-6a9146a339db.png)

**Comment by tobrun** [comment]
@bleege thanks for noticing and cherry picking.

**Comment by tobrun** [comment]
I validated the last remaining item (public API on MapboxMap). It seems that checklist is done and we can close this. For later reference these PRs were used: #5189 #5168. Closing
