### ISSUE TITLE
Update Android NDK - Take 2

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#5123]
We tried to update the NDK to the latest version (11c) in #5092 but ultimately had to rollback ( 6abd3d70beb9233262fbbb2de1f780cdfc29bb5c ) as it crashed the TestApp at runtime ( #5108 ).  Let's try to update again after `Android 4.1.0 FINAL` ships.

/cc @mapbox/mobile @kkaefer @jfirebaugh @tmpsantos @brunoabinader

**Comment by Fintasys** [comment]
Thanks for the information!
I still get the error when I try to run my android app. I already cleaned all caches & rebuild. Can anyone tell me what to do to get my app working again?

**Comment by bleege** [comment]
@Fintasys Can you tell us more about your app?  Specifically which version of the SDK are you using?

**Comment by Fintasys** [comment]
@bleege sure, I work with the Mapbox SDK 4.1.0-SNAPSHOT. It's at the moment only the map and I tested it on Android 5.1.1. If you need more specific information, let me know. 
I understood that you rolled back, doesn't that mean the SNAPSHOP should work again?

**Comment by bleege** [comment]
Thanks for the specifics about what version of the SDK the app is using.  Yep, the latest SNAPSHOT was built using the new (and now reverted) NDK.  We tried releasing a new SNAPSHOT this afternoon but ran into another issue in #5126 that is currently preventing us from releasing a new version.  We hope to have this resolved ASAP and have a new working SNAPSHOT available.

**Comment by bleege** [comment]
@Fintasys FYI... I just published a new `4.1.0-SNAPSHOT` and [things are working again](https://github.com/mapbox/mapbox-gl-native/issues/5126#issuecomment-221688182).  We'll revisit this ticket and the new NDK in the next release.

**Comment by bleege** [comment]
For more back story on the current process and timing --> https://github.com/mapbox/mapbox-gl-native/issues/5126#issuecomment-221658049

**Comment by tmpsantos** [comment]
@kkaefer we should probably update to NDK 12 that was just released.

See https://code.google.com/p/android/issues/detail?id=212637#c2 for details. It could potentially remove some hacks we have on the code.

The NDK download website was not updated yet (as of now) but the download link works:
http://dl.google.com/android/repository/android-ndk-r12-linux-x86_64.zip

**Comment by bleege** [comment]
Good catch @tmpsantos on NDK 12.  Google's been pushing it via Android Studio automatic updates for the past week (no direct download).

**Comment by bleege** [comment]
Related ticket is #5521

**Comment by bleege** [comment]
Now that Mapbox Android 4.1.0 has been released ( #5510 ) we'll need to update the NDK in order to get the nightly SNAPSHOTS building again (either that or revert the `Makefile`'s build type to `Release`).  Since this has to do with updating things in Mason I've asked @tmpsantos @kkaefer if they have time to implement this.

**Comment by kkaefer** [comment]
#5533

**Comment by bleege** [comment]
@kkaefer is working on upgrading the project to NDK 12 in #5533.  Closing this issue in favor of his work there.
