### ISSUE TITLE
Add enabled property to MGLAnnotationView

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-gl-native#5127]
MapKit has an [`enabled` property](https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKAnnotationView_Class/#//apple_ref/occ/instp/MKAnnotationView/enabled) on the annotation view base class. This property informs touch behavior and subclasses can use it has a hint for content display. MGLAnnotationView should have a similar property.

**Comment by 1ec5** [comment]
MGLAnnotationImage also has this property, so we’ll need it for parity with the preexisting API.

**Comment by 1ec5** [comment]
[MGLAnnotationImage also has this property](https://www.mapbox.com/ios-sdk/api/3.2.2/Classes/MGLAnnotationImage.html#/c:objc(cs)MGLAnnotationImage(py)enabled), so we’ll need it for parity with the preexisting API.
