### ISSUE TITLE
Add annotationView to mapView's didSelectAnnotation and didDeselectAnnotation protocol methods

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-gl-native#5130]
MapKit passes back the annotation view that was (de)selected in `- mapView:did(De)SelectAnnotationView`. To maintain backwards compatibility with annotation views not backed by an MGLAnnotationView, the Mapbox API currently (and for now must continue to) pass the annotation object itself as in: `- mapView:did(De)SelectAnnotation:`. However, the Mapbox API can gain the `annotationView` for a fully formed `- mapView:did(De)SelectAnnotation:annotationView:`. The annotationView parameter can be nil when it does not make sense to send in (in the context of a non-MGLAnnotationView backed annotation).

This will make it easier for application developers to interact with views that are involved with selection and deselection.

**Comment by 1ec5** [comment]
`- mapView:did(De)SelectAnnotationView:` would be more elegant once #5129 is implemented.
