### ISSUE TITLE
Raster/TexturePoolHolder leaks textures

### ISSUE THREAD

**Issue by jonkan** [mapbox/mapbox-gl-native#5136]
We're seeing a lot of "out of memory"-crashes after a while of heavy panning (iPad Air 2, a raster only stylesheet containing two raster-layers, both using 1024px tiles). 

Trying to track down what's eating all the memory I found that in gl_object_store.cpp, `TexturePoolHolder::reset()` it seems textures are never deleted due to the line [`if (!bool()) return;`](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/gl/gl_object_store.cpp#L63).
There's also the line [`if (bool()) return;`](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/gl/gl_object_store.cpp#L57) which to me seems to have no purpose?
Or am I missing something?

I can also add that, with those lines removed `TexturePoolHolder::reset()` seems to always be called having a NULL `objectStore` when called from [`Raster::~Raster()`](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/util/raster.cpp#L18)...

**Comment by jfirebaugh** [comment]
`if (bool())` originates in 124173080f35d4a53e24790c0ad2cf2687d35836 -- cc @brunoabinader.

**Comment by jonkan** [comment]
Tested with latest master now and the crashes are easily reproducible with the "iosapp"-target and the default "Satellite"-style by constantly panning in one direction, takes a while though..

<img width="2039" alt="screen shot 2016-05-25 at 20 04 03" src="https://cloud.githubusercontent.com/assets/3512794/15550975/17477cb6-22b4-11e6-8e74-5e9d1b02699b.png">

**Comment by brunoabinader** [comment]
>There's also the line if (bool()) return; which to me seems to have no purpose? Or am I missing something?

Oh my, this looks like my eyes missed this while batch replacing strings on my IDE. Will send a patch soon.

**Comment by brunoabinader** [comment]
Checking the code, the `bool()` is not a typo - it is using the `bool()` from https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/gl/gl_object_store.hpp#L114.

**Comment by jonkan** [comment]
Oh, that I'd missed.. I tested again with a clean master (as I had commented out just that line last time) and the memory-leak/crashing is still there.

**Comment by brunoabinader** [comment]
@jonkan can you please verify the patches from https://github.com/mapbox/mapbox-gl-native/pull/5141?

**Comment by jonkan** [comment]
> @jonkan can you please verify the patches from #5141?

👍 For the purpose of readability `if (!created()) return;` is more clear to me than `if (!bool()) return;`, not sure I understand if the PR was intended to fix more than just the readability aspect. The memory-leaking/crashing is still present, but might have its cause somewhere else..

**Comment by brunoabinader** [comment]
Reopening for verification - @jonkan can you please verify?

**Comment by friedbunny** [comment]
We will want to include an iOS changelog entry for this fix, as it affected iOS 3.2.x.

Android 4.0.x is also affected, but I’m not sure if 4.1.0 will include this? /cc @bleege

**Comment by bleege** [comment]
@friedbunny Thanks for the ping.  I branched `4.1.0-beta.1` off of 26a425fa6d0386aa59027b1b5813edd781f460ed before the final two commits ( b2b2797c2a30b8085683935d760c45284c639e96 and c111250fcccaf5e57154852606ee740f0db242c1 ) had been pushed to `master`.  We'll have to cherry pick them to the [`release-android-v4.1.0`](https://github.com/mapbox/mapbox-gl-native/commits/release-android-v4.1.0) branch when it's been verified and @brunoabinader closes this issue.

/cc @tobrun @cammace

**Comment by jonkan** [comment]
@brunoabinader Awesome! That solved it, not seeing any crashes or leaks. 👍

**Comment by brunoabinader** [comment]
Thank you @jonkan!

**Comment by bleege** [comment]
Thanks for confirming and getting this fixed @jonkan @brunoabinader.  I'll cherry pick the remaining two commits into the `release-v4.1.0` branch now so that they'll ship with future `4.1.0` builds and releases.

**Comment by brunoabinader** [comment]
Awesome @bleege, thanks!

**Comment by bleege** [comment]
Cherries have been picked!

![screen shot 2016-05-27 at 10 43 22 am](https://cloud.githubusercontent.com/assets/989928/15613198/e0cf644c-23f7-11e6-85ce-a899a4d9744d.png)

**Comment by friedbunny** [comment]
Updated the iOS changelog in 2f25c1ac43b1fc43fb32a094815b809cae8c6a70 — this issue will be fixed in the v3.3.0 release (and whichever pre-release comes after alpha 3).
