### ISSUE TITLE
Shape annotations disappear at z19

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5138]
When zooming in a high zoom levels polygons disappear. This potentially could be related to https://github.com/mapbox/mapbox-gl-native/issues/5109. 

![ezgif com-resize](https://cloud.githubusercontent.com/assets/5652865/15551600/c1e9d6d0-2284-11e6-8d20-445cc131d7d1.gif)

cc: @tobrun @bleege

**Comment by 1ec5** [comment]
What zoom level does it disappear at? (Turn on the tile boundary and tile info debug flags so it’s clear.)

**Comment by cammace** [comment]
>20 zoom level and it disappears.

**Comment by 1ec5** [comment]
Is #4907 related?

**Comment by cammace** [comment]
Doesn't look like it, I just tested their style and was unable to reproduce.

**Comment by bleege** [comment]
@1ec5 @friedbunny @boundsj Is this reproducible on iOS or is this just and Android thing?

**Comment by 1ec5** [comment]
I’m seeing this in iosapp on master at z19 and above, after choosing “Add Test Shapes” and zooming into the red triangle overlay over Oregon.

**Comment by 1ec5** [comment]
Still reproduces following #5175.

**Comment by brunoabinader** [comment]
👉 #5418.

**Comment by megraham** [comment]
I'm seeing this same issue on both our internal app (zoom level ~19) and on the Mapbox Dev Preview app (not sure what zoom level).

**Comment by 1ec5** [comment]
It looks like this fix won’t make it into the iOS SDK until v3.4.0, whereas we’re getting reports of the regression in v3.3.0 (#5715). @brunoabinader, how feasible would it be to backport a fix to the release-ios-v3.3.0 branch for v3.3.1?

**Comment by brunoabinader** [comment]
> how feasible would it be to backport a fix to the release-ios-v3.3.0 branch for v3.3.1?

I've backported the patch from https://github.com/mapbox/mapbox-gl-native/pull/5418/commits/e1be2c45c1efdbb5d6e14e9431444292adaf3c9a in `release-ios-v3.3.0` branch: committed in https://github.com/mapbox/mapbox-gl-native/commit/2a0e2961992be22aa0cc4c394a00ef09b0fe3d71 👍
