### ISSUE TITLE
mbgl::AnnotationManager should use mapbox::geometry types

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5158]
`mbgl::AnnotationManager` should use the `mapbox::geometry` types that are being used e.g. as return values for `mbgl::Map::queryRenderedFeatures()` (#5066). This would give us the ability to add any kind of geometry to the annotation layer, unblocking #1729.

/cc @jfirebaugh

**Comment by jfirebaugh** [comment]
In https://github.com/mapbox/mapbox-gl-native/commit/3f17b63e16c9326436534075930ecca44c0ab3d0 and https://github.com/mapbox/mapbox-gl-native/commit/30ec9c6ec9003e8ad56cc960223b20532703b029 I sketched out a couple potential redesigns that accomplish this. I think I slightly prefer the latter.

Both designs will be significantly easier to implement once https://github.com/mapbox/geojson-vt-cpp/pull/45 lands. Currently a bunch of conversion code would be required.

**Comment by 1ec5** [comment]
I think I’d prefer the latter option too. It wouldn’t feel right to restrict this API to just the three geometry types (point, line, polygon) in core, given that core can actually handle any of the geometry types.

**Comment by jfirebaugh** [comment]
The above approach expands into much more work than I'm comfortable biting off right now, given the release schedule and certainty of introducing conflicts with https://github.com/mapbox/mapbox-gl-native/pull/4839.

We can switch the interface to geometry.hpp types with less effort: https://github.com/mapbox/mapbox-gl-native/compare/5158-minimal. Note that this approach does not itself fix #1729 or even expand the actual range of supported geometry types. Unsupported types become a runtime error, rather than not being expressible in the API.

@1ec5 WDYT?

**Comment by jfirebaugh** [comment]
Actually, it shouldn't be hard to expand the geometry support to polygon holes, `MultiLineString`, and `MultiPolygon`. What looks difficult is `Point`, `MultiPoint`, and `GeometryCollection`.

**Comment by 1ec5** [comment]
Is `Point` difficult because point annotations and shape annotations have different tile and layer implementations?

**Comment by jfirebaugh** [comment]
* A line or fill layer -- the only options for `ShapeAnnotation` -- displaying a single `Point` isn't a useful combination. It won't render anything.
* A line or fill layer displaying a `MultiPoint` isn't particularly sensical. I _think_ it will render the same as a `LineString` with the same coordinates, so you might as well just use that.
* The version of geojson-vt-cpp currently in use [privatizes the method](https://github.com/mapbox/geojson-vt-cpp/blob/3b72e4e000c47ff12512236f4b3171581146fa67/include/mapbox/geojsonvt/convert.hpp#L43) we'd want to use for conversion.

**Comment by jfirebaugh** [comment]
We could however, switch `PointAnnotation` from `LatLng` to `Point<double>`, if that would help the SDKs with consistency.
