### ISSUE TITLE
When map is tilted, Marker Views don’t scale by distance from camera

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5169]
Android equivalent of #5040, capturing from that issue:

> When the map is tilted, an GL icon or point annotation grows as the camera moves toward it and shrinks as the camera moves away from it (#2186). However, annotation views maintain their size. This behavior is consistent with the user dot, but scaling would help by reinforcing the illusion of a tilted map.

Also capturing that scaling should be default to follow the style spec:

> Given that the consensus in mapbox/mapbox-gl-js#2541 was that scaling by default was better, I suspect it will always be the style spec default.

**Comment by dylan-chong** [comment]
Any progress on this for Android? It looks like the iOS has been updated a while ago  https://github.com/mapbox/mapbox-gl-native/pull/5085

**Comment by tobrun** [comment]
MarkerView is going to be deprecated with https://github.com/mapbox/mapbox-gl-native/pull/9782. We are no longer maintaining this API and will remove it in future versions of the SDK. As noted in the deprecation message. We are advising users to leverage SymbolLayer instead (you can use the sample code in #9782 to convert Android SDK views to an Image to be used as a Symbol). While we no longer maintain the API we are happy to accept any PRs on it.
