### ISSUE TITLE
Call (or expose?) onLowMemory() in renderStill to cull TexturePool

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#5173]
Without a guarantee in that a `NodeMap` will consistently render images from the same style, it's quite likely that textures will be unnecessarily retained in an internal cache on the `mbgl::Map` object, which could be exacerbated by rotating through a pool of `NodeMap` objects as opposed to continuously rendering on a single `mbgl::Map`.

Is this a concern for rasters too? Even rendering from the same style, it's highly unlikely a raster would ever be reused if any sort of caching is placed in front.

/cc @brunoabinader @tmpsantos

**Comment by tmpsantos** [comment]
Side note here, it won't invalidate the style. It will only clear the tile cache, so the cache in this case is only useful if the `NodeMap` object happens to render the same tile again.

**Comment by mikemorris** [comment]
Implemented in https://github.com/mapbox/mapbox-gl-native/pull/5217, will try to determine if this is useful before merging.

**Comment by brunoabinader** [comment]
I found out I actually caused a memory leak in 61dad6eae59e284fdba63fcd76d9192aba900db4 last week. I fixed that today in https://github.com/mapbox/mapbox-gl-native/pull/5269 /cc @mikemorris

**Comment by brunoabinader** [comment]
@mikemorris is this still relevant?

**Comment by mikemorris** [comment]
@brunoabinader Testing this never showed any significant impact, gonna close this out.
