### ISSUE TITLE
Investigate different tessellation libraries

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-native#518]
In particular, https://code.google.com/p/poly2tri/. It's better quality triangulation than libtess (meaning that rendering will be faster in theory), and it might be faster because it doesn't try to handle degenerate cases (already covered by preprocessing with clipper)

**Comment by jfirebaugh** [comment]
We're planning to switch to https://github.com/mapbox/earcut.hpp eventually.
