### ISSUE TITLE
mapbox-gl-native (node) crashes on high res maps

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-native#5184]
**Platform: Linux 64bit (under xvfb)**
**Mapbox SDK version: mapbox-gl-native@3.1.3 (node)**

### Steps to trigger behavior

 1. Try to generate a map image with very high resolution, say width: 7016, height: 9922

### Expected behavior
That the image is generated (in due time..) or that it at least fails gracefully with an error.

### Actual behavior
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Couldn't create framebuffer: incomplete attachment
Aborted (core dumped)
```

This could very well be because I depend on emulated GL capabilities using xvfb, however it does work fine with lower resolutions. Are there any known hard limitations when it comes to resolution?

**Comment by tmpsantos** [comment]
@averas I would say the highest resolution you can render would be a combination of hardware in use + style + area being rendered. Some areas can have more glyphs and geometries for instance.

If you really need a 7k x 10k rendering but the hardware is not up to the task, I recommend splitting in smaller pieces and merging back using image editing tools.

**Comment by averas** [comment]
> I would say the highest resolution you can render would be a combination of hardware in use + style + area being rendered. Some areas can have more glyphs and geometries for instance.

Alright, but would you say that the kind of error and crash that follows is legit under such circumstances? (since you closed the issue) Could it be caught and handled gracefully?

> If you really need a 7k x 10k rendering but the hardware is not up to the task, I recommend splitting in smaller pieces and merging back using image editing tools.

Yep, this is my backup plan, however I suspect that, say a 2x2 mosaic, will look different than a single rendering because of different results from label positioning, collision detection etc. It might still be good enough though.

**Comment by tmpsantos** [comment]
> Alright, but would you say that the kind of error and crash that follows is legit under such circumstances? (since you closed the issue) Could it be caught and handled gracefully?

It is not crashing as in a SEGV, but rather throwing an exception when it fails at resizing the framebuffer (so we check the error code and throw). We could catch this exception and try to recover from that, but IMO it could potentially complicate the normal code path (and introduce more bugs) for something that is a very extreme use case.

> Yep, this is my backup plan, however I suspect that, say a 2x2 mosaic, will look different than a single rendering because of different results from label positioning, collision detection etc. It might still be good enough though.

It might be different but probably barely noticeable. We use it for 512x512 tiles on our raster fallback and the results are very good compared to rendering a 2000x2000 map.

**Comment by averas** [comment]
Great feedback, thanks!
