### ISSUE TITLE
MGLPolyline not taking shortest path.

### ISSUE THREAD

**Issue by mrdavidrees** [mapbox/mapbox-gl-native#5190]
**iOS**
**3.2.2**

Hello I have been working with Mapbox over the last month or so for an app. The client has complained that when drawing a line between two points where the line crosses over +-180 longitude it will take the longest path to draw the line. 
For example a line between Australia and the USA will pass through Africa rather than the South Pacific Ocean. I'm assuming you guys already know about this issue but it would be great if I could get an ETA on this issue for the client.

I have also found one more issue.
When showing a modal viewcontroller over the map and then returning to the map, didSelectAnnotation will not trigger unless the map is panned.

And finally, Is there any plan to implement lines with a dash pattern or similar? it would be great to be able to supply a dash pattern with our polylines.

Thanks,

David.

**Comment by 1ec5** [comment]
> For example a line between Australia and the USA will pass through Africa rather than the South Pacific Ocean. I'm assuming you guys already know about this issue but it would be great if I could get an ETA on this issue for the client.

This is covered by #4974. We don’t have an ETA on this issue right now, but we can investigate further. In the meantime, one workaround would be to use two polylines that meet each other at the antimeridian.

> Is there any plan to implement lines with a dash pattern or similar?

This is blocked on #837.

**Comment by mrdavidrees** [comment]
Hi guys I still have one more issue that wasn't responded too,

When showing a modal viewcontroller over the map and then returning to the map, didSelectAnnotation will not trigger unless the map is panned.

Any ideas?

**Comment by 1ec5** [comment]
I’m unable to reproduce that issue in either v3.2.2 or v3.3.0-alpha.3. What kind of segue are you using exactly? A reduced test case may help us better understand how you’re running into this issue.
