### ISSUE TITLE
setting tilt in xml doesn't tilt the user location

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5197]
Setting camera tilt in xml like so: `mapbox:tilt="25"` and enabling the user location in java wont tilt to user dot in `4.1.0`

![screenshot_20160531-135748](https://cloud.githubusercontent.com/assets/5652865/15685163/8bc6ff66-2738-11e6-8ecd-9ce6b21ef351.png)

@tobrun

**Comment by tobrun** [comment]
Adding a note here that configuration changes has the same issue

**Comment by tobrun** [comment]
Picked this up as part of #5192. Closing
