### ISSUE TITLE
Tracking user location doesn't update until zoom changes

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5199]
When using user tracking:

```
mapboxMap.getTrackingSettings().setMyLocationTrackingMode(MyLocationTracking.TRACKING_FOLLOW);
```

without changing the zoom level, the user dot won't change positions. Only after zooming in does it change to the correct location.

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/5652865/15693033/28d6d692-2760-11e6-9a4a-b1bfb2369aa0.gif)

cc @tobrun

**Comment by tobrun** [comment]
I remember reading in the iOS code that they auto zoom in when you enable user location tracking (the user location view should always be centered with tracking enabled).

@cammace note that when you perform a gesture tracking mode is disabled automatically you can change this behaviour in the `TrackingSettings` class.

**Comment by tobrun** [comment]
I'm not picking this up for `4.1.0`, this behaviour has always been there since tracking mode was introduced. Setting an initial zoom level can be used as a workaround.

**Comment by cammace** [comment]
This appears to not be an issue anymore:

![ezgif com-video-to-gif 29](https://cloud.githubusercontent.com/assets/5652865/20156172/43d7982a-a69d-11e6-8a98-12c364a728b9.gif)
