### ISSUE TITLE
Crashing after switch to other activity contain MapView and back press

### ISSUE THREAD

**Issue by DucHM** [mapbox/mapbox-gl-native#5202]
I uploaded my demo on Android platform as link below:
https://drive.google.com/file/d/0BxCyRfBVwdSuRjluOWp0SGQ2VEk/view?usp=sharing
This is link screen record when crashing:

https://www.youtube.com/watch?v=PMfwxt78qiA

Start app demo
Click to Switch button on the top screen
After new activity started --> Click to back press or back button --> crashed with content in logcat as ported on https://github.com/mapbox/mapbox-gl-native/issues/5094

Please check and support help me.

**Comment by tobrun** [comment]
Thank you for reaching out and adding source code and a clip showing the issue. 
This will make reproducing a bit easier.

**Comment by ugurcany** [comment]
I'm also having this issue on Asus Zenfone 6 (Android 5.0) for both `4.1.0-beta.1` and `4.1.0-SNAPSHOT` versions. However, it works fine on Samsung Galaxy S7.

**Comment by tobrun** [comment]
@bleege @cammace:

I believe this is a valid bug that would block `4.1.0`, this type of behaviour is something we don't have in the test app anymore. 

- Activity with Mapview 
- go to another Activity 
- press back to return to Mapview Activity

We should look into adding such an Activity for future reference + try reproducing it.

**Comment by jfirebaugh** [comment]
This is the same as #5094 right? Can we keep the discussion on a single ticket please?

**Comment by tobrun** [comment]
@jfirebaugh you are right. Closing this in favor of #5094
