### ISSUE TITLE
The presence of image backed annotations should not trigger log messages

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-gl-native#5210]
Once a GL sprite backed annotation is added to the map, the message `[INFO] {Worker}[Sprite]: Can't find sprite named 'default_marker'` is seen for every tile parse that has a UIView backed annotation in it. The message comes from [this line in sprite_store.cpp](https://github.com/mapbox/mapbox-gl-native/blob/7272d7c84cf6e874b417ecd165f46f26ae7729c9/src/mbgl/sprite/sprite_store.cpp#L145) but the underlying issue is that annotations that are are actually backed by UIViews are not fully understood by core implementation.

**Comment by jfirebaugh** [comment]
The SDK is trying to add a point annotation with the `icon` property set to an empty string, thinking that that will result in a point annotation without an icon, as described [here](https://github.com/mapbox/mapbox-gl-native/pull/5165#issuecomment-222034113). But in fact mbgl core doesn't have a concept of "point annotation without an icon". For historical reasons, the empty string is [mapped to the `"default_marker"` icon](https://github.com/mapbox/mapbox-gl-native/blob/f41546e61456ff85d07c4b21ada54ae7b2709b87/src/mbgl/annotation/point_annotation_impl.cpp#L14), and any other string that doesn't have a matching icon will result in this debug message.

I think you should find another way to implement what you need for annotation views. This isn't an intended use for the core annotations API.

**Comment by boundsj** [comment]
Thanks @jfirebaugh. Noting that we discussed the workaround of using a transparent image with a specific name until we nail down exactly what the true fix will be.

cc @1ec5

**Comment by boundsj** [comment]
This was recently fixed in https://github.com/mapbox/mapbox-gl-native/pull/5461 for iOS and [Android was already using the same same solution](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerView.java#L299).
