### ISSUE TITLE
Android integration tests

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#5211]
In order to prevent regressions like #5108, we need Android integration tests that test actually running a test app.

**Comment by tobrun** [comment]
I have been trying to avoid them a bit because they tend to be a bit flaky. In this multi platform project with multi contributors it makes sense requiring them on every commit. I'm suggesting to look into the Bitrise emulator approach first before taking the AWS device farm route.

**Comment by tobrun** [comment]
I have been working on a testapp to test scripts and was able to run it on Bitrise. 
Next steps is porting these workflows to gl-native bitrise.yml file.

**Comment by tobrun** [comment]
I was able to store the API access token on s3 and copy it to the correct location in the test app. 

Now I'm running into:
```java
com.mapbox.mapboxsdk.testapp.espresso.LatLngBoundsActivityTest > testSanity[test(AVD) - 6.0] FAILED 
	java.lang.Error: eglChooseConfig() failed
	at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(Native Method)
Tests on test(AVD) - 6.0 failed: Instrumentation run failed due to 'java.lang.Error'
:MapboxGLAndroidSDKTestApp:connectedDebugAndroidTest FAILED
```

**Comment by tobrun** [comment]
I reached out to Bitrise to see if they can help resolve the issue with the emulator in https://github.com/bitrise-steplib/steps-start-android-emulator/issues/22.

**Comment by tobrun** [comment]
I have been looking into how Bitrise is setting up their emulator and was able to reproduce the issue on Bitrise locally. After trying out some configurations I'm starting to think the issue comes from not enabling `GPU emulation`. Will look into this in more detail and see if I can create an emulator through command line that is able to show our maps.

**Comment by tobrun** [comment]
Been following up with Bitrise folks [here](https://github.com/bitrise-steplib/steps-start-android-emulator/issues/22#issuecomment-232365389). We were able to get  GPU emulation configured but now are still hitting a timeout when starting an emulator.

**Comment by tobrun** [comment]
I reached out to Bitrise after I tried running an emulator with GPU emulation in a separate project. 
See https://github.com/bitrise-steplib/steps-start-android-emulator/issues/22#issuecomment-237421908

**Comment by zugaldia** [comment]
Good progress here @tobrun. Let me know if you see Bitrise's current state as a blocker, I'm happy to help with the AWS Device Farm approach instead.

**Comment by tobrun** [comment]
@zugaldia  after a couple of failed attempts creating an own Bitrise docker image that supports GPU emulation. I'm going to look into AWS device farm by leveraging their gradle integration. This is on my plate to pick up next monday. Current workstation doesn't have aws credentials configured. I'm handling this as highest priority to be able to catch regressions as we have seen with beta release and as mentioned in OP.

**Comment by zugaldia** [comment]
@cammace Fantastic 👍

**Comment by tobrun** [comment]
I'm currently working on integrating Firebase device lab in our CI workflow, 
if everything goes well this will be finished later today.

**Comment by tobrun** [comment]
Proposed PR for new workflow in #6073
