### ISSUE TITLE
Flat markers should have screen-centered vanishing point

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5218]
As seen in https://github.com/mapbox/mapbox-gl-native/issues/3276#issuecomment-223452965, the vanishing point for a flat marker view on a tilted map is always somewhere directly above the marker view. So in the screenshot above, the flag to the right is symmetrical across the y axis, whereas you’d expect both the left and right sides of the flag to parallel the north-south streets they’re being drawn atop:

![device-2016-06-02-183106](https://cloud.githubusercontent.com/assets/989928/15764390/339ee61e-28f0-11e6-98d5-4838d101579b.png)

If the perspective transformation is executed correctly, you shouldn’t be able to tell that the flag is a marker view. As you pan the map from side to side, the streets shouldn’t appear to be moving relative to the flag. In graphics terms, the vanishing point for the transform should be horizontally centered; it shouldn’t vary by the x position of the marker view.

Due to #5090, we haven’t run into this issue on iOS yet, but it’s something to be aware of.

/cc @tobrun @bleege @boundsj @friedbunny

**Comment by tobrun** [comment]
Thank for the 👀  @1ec5, getting this in will probably require the addition of a container view since we need to be able to control the `onDraw` and do the projection ourselves. (instead of relying on setRotationX of the user provided view).

**Comment by tobrun** [comment]
with #9782 we have deprecated MarkerView, closing.
