### ISSUE TITLE
Update README files for Android

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5226]
I was searching for some docs related to iOS for a user on IRC and noticed that iOS has a great way of showing the content at the right spot at the right time. For consistency and improving the Android docs I'm suggesting we reproduce a large part of their setup/content for the Android platform.

**Comment by bleege** [comment]
Can you help me understand what "great way of showing the content at the right spot at the right time" means?  Are you suggesting that the existing iOS README be mimicked in Android?

https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/README.md

**Comment by tobrun** [comment]
<img width="490" alt="screen shot 2016-06-05 at 08 16 18" src="https://cloud.githubusercontent.com/assets/2151639/15803909/e5f6e5bc-2af5-11e6-822f-b7414a19cefe.png">

The first page gives a guidance for between:
 - Use our SDK in an application
 - Contribute to development

**Comment by tobrun** [comment]
<img width="330" alt="screen shot 2016-06-05 at 08 16 30" src="https://cloud.githubusercontent.com/assets/2151639/15803913/28a45354-2af6-11e6-8c18-77639bc637d4.png">

 - I like the how the content is structured
 - having only one link here to: `Install core dependencies first` makes the link jump out as important.

**Comment by bleege** [comment]
Cool!  Thanks for clarifying... that makes a lot of sense now.  @cammace do you have some bandwidth to work on this?

**Comment by cammace** [comment]
Is this still relevant? Our readme provides all the necessary information at first glance and has changed a lot since the screenshot @tobrun provided.

**Comment by tobrun** [comment]
Yes, you are killing it @cammace! closing
