### ISSUE TITLE
Rendering Problems MapBoxAndroidDemo in Android Studio 2.1.1

### ISSUE THREAD

**Issue by kjetila** [mapbox/mapbox-gl-native#5228]
I started with trying to make my own demo of mapbox-android-sdk, but kept getting rendering problem with MyLocationView not being instantiated. 

Then I tried to just run the MapBoxAndroidDemo project run in Android Studio, but I keep getting rendering problems with MyLocationView. I have checked permission and these seem to be correct, it builds fine with gradle but looking at the preview I this error is still there. I have changed api between 21 and 23 and still not working. Any ideas whats wrong? Full error message is posted below.

Rendering Problems The following classes could not be instantiated:
- com.mapbox.mapboxsdk.maps.widgets.MyLocationView (Open Class, Show Exception, Clear Cache)

 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE  Exception Details java.lang.UnsupportedOperationException: Unsupported Service: location   at com.android.layoutlib.bridge.android.BridgeContext.getSystemService(BridgeContext.java:571)   at com.mapzen.android.lost.internal.FusionEngine.<init>(FusionEngine.java:38)   at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.<init>(FusedLocationProviderApiImpl.java:27)   at com.mapzen.android.lost.internal.LostApiClientImpl.connect(LostApiClientImpl.java:21)   at com.mapbox.mapboxsdk.location.LocationServices.toggleGPS(LocationServices.java:88)   at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.toggleGps(MyLocationView.java:323)   at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.setEnabled(MyLocationView.java:294)   at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.init(MyLocationView.java:107)   at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.<init>(MyLocationView.java:98)   at java.lang.reflect.Constructor.newInstance(Constructor.java:422)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.inflate(LayoutInflater.java:492)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397)   at com.mapbox.mapboxsdk.maps.MapView.initialize   ... (MapView.java:188)   at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:166)   at java.lang.reflect.Constructor.newInstance(Constructor.java:422)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) Copy stack to clipboard

**Comment by bleege** [comment]
@kjetila Can you share some of the code that your app is using so that we can help you diagnose the problem?  You mentioned `MapBoxAndroidDemo`, are you referring to the the `master` branch on https://github.com/mapbox/mapbox-android-demo ?

**Comment by kjetila** [comment]
Yes, I am referring to the master branch. Trying to preview or install this app gives me same error as my test app.

There isnt much code to include really. 

The activity_main.xml looks like: `<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:mapbox="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="no.ecc.navida.MainActivity">

    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapview"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        mapbox:style_url="@string/style_mapbox_streets"
        mapbox:access_token="pk.eyJ1Ijoia2plYW5kZXIiLCJhIjoiTE1JV2FnTSJ9.XTdwJflhqjYYTXtASoYh7A"/>
</RelativeLayout>

And main activity ` @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }`

Gradle builds fine and includes:
`dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:4.1.0-beta.1@aar'){
        transitive=true
    }
    compile ('com.mapbox.mapboxsdk:mapbox-android-services:1.1.0@aar'){
        transitive=true
    }
}`

Manifest file includes: 
 <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.INTERNET" />

**Comment by bleege** [comment]
@kjetila It looks like some changes have been made to the source code as evidence by the `tools:context="no.ecc.navida.MainActivity">` and that it's not simply the `master` branch as is.  Can you share what else has changed?

/cc @mapbox/support

**Comment by kjetila** [comment]
Yes, I changed some class names. But you can close this, it works fine now. 

Not sure what actually fixed it, might have been some old gradle version or maybe just me doing something wrong in the android studio.

Anyway it all looks good now, thanks for your help.

**Comment by bleege** [comment]
Glad to learn that things are working again @kjetila!  Please let us know if we can be of further assistance in the future.
