### ISSUE TITLE
Add View Annotations Z ordering

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5238]
We have been hearing about the need to be able to order Markers. For View based Markers an end developer should be able to indicate to a marker to be placed on top of another marker.  This system must integrate with other already shown View elements as CompasView, MyLocationView etc. This could be made part or based on current implementation of MarkerViewAdapter, as a separate ViewOverlay implementation or exposed in Marker itself.

This should solve the issues we have been seeing related to overlapping views.
This issue doesn't cover z-ordering or layering from core in https://github.com/mapbox/mapbox-gl-native/issues/991

**Comment by tobrun** [comment]
Instead of calling it layers, the term `Overlay` is more appropriate. This naming doesn't conflict with the layers we have in core and the view based components will always be on top of the map (overlain on top of the map).

**Comment by tobrun** [comment]
> This should solve the issues we have been seeing related to overlapping views.

If you currently pan an MarkerView towards the CompassView you will see that the MarkerView goes over the CompassView instead of going underneath.

**Comment by zugaldia** [comment]
Related: https://github.com/mapbox/mapbox-gl-native/issues/5285

**Comment by tobrun** [comment]
@ivovandongen has been picking related items up in #5298 & #5294.
We need to validate if those fixes fulfil the requirements of this ticket.

**Comment by zugaldia** [comment]
@tobrun These are limited scale implementation of this ticket.

In particular, https://github.com/mapbox/mapbox-gl-native/pull/5294 only brings the selected marker to front, which is a common usecase for the larger need of Z-ordering. iOS recently did the same with https://github.com/mapbox/mapbox-gl-native/issues/991.

**Comment by tobrun** [comment]
Moving this of the milestone, what we want for 4.1.0 is place. 
TBD what we want to add in future releases.

**Comment by zugaldia** [comment]
> Moving this of the milestone, what we want for 4.1.0 is in place. 

👍

**Comment by tobrun** [comment]
A user reached out in #5451 requesting the possibility to assign a MarkerView to a layer and manipulate layers completely (eg. hide a layer).

**Comment by guruduttstay** [comment]
Do we know if there is a plan to add this feature request to Milestone :)

**Comment by zugaldia** [comment]
> Do we know if there is a plan to add this feature request to Milestone :)

@guruduttstay I'd say that we aren't gonna add any more features to `4.1.0` as we are already getting ready for a final release once we published `beta3` earlier this week. The good news is that as discussed above, `4.1.0` will bring some partial improvements to this feature via https://github.com/mapbox/mapbox-gl-native/pull/5294.

**Comment by incanus** [comment]
I'm going to take a look at this. In the raster iOS SDK, I had implemented a delegate pattern callback for simple comparator-based two-at-a-time sorting of annotations (all of which were native-side views at the time), encapsulated in https://github.com/mapbox/mi-sdk-legacy/pull/491. I will see what sort of API makes sense in Android land for something like this.

**Comment by incanus** [comment]
To break down the implementation I will likely model this from (found [here](https://github.com/mapbox/mi-sdk-legacy/blob/4a26c6d979ea4687cc6a6b8e226ebed1625137ab/MapView/Map/RMMapView.m#L3098-L3182)), the API could work like this: 

1. Each frame update, run through the native-side view ordering routine. 
1. If the client doesn't implement a custom callback, fall back to a built-in algorithm. This would sort such things as: 
  1. Existing views by top-to-bottom of screen order.
  1. Any selected view(s). 
  1. Shapes. 
  1. Core-side sorting. 
1. If the client *does* implement a custom callback, call out to it for native-side view sorting instead. 
  - The callback can consist of a `java.util.Collections` `Comparator` interface. 

Does this sound like a good design? Will it meet the needs we've outlined?

**Comment by incanus** [comment]
I guess the broader question here is: do callers want to be able to provide an algorithm for sorting, or to indicate this upfront and be hands off afterwards?

**Comment by incanus** [comment]
If the answer to the above is an algorithm, it looks like with the `ViewGroup` API that we are using for our `mMarkerViewContainer`, we can use [`setChildrenDrawingOrderEnabled(true)`](https://developer.android.com/reference/android/view/ViewGroup.html#setChildrenDrawingOrderEnabled(boolean)) and then override [`getChildDrawingOrder()`](https://developer.android.com/reference/android/view/ViewGroup.html#getChildDrawingOrder(int,%20int)) in order to provide a builtin, or to call out to a user's custom, view sorting operation.

**Comment by incanus** [comment]
Sounds like an algorithm such as above is a second-stage goal here, first stage being simply passing an index (or, more conveniently, a reference to another marker) which we want the new marker to be atop. Let's start with that first.

**Comment by incanus** [comment]
I plumbed the requisite argument down through the JNI in https://github.com/mapbox/mapbox-gl-native/compare/94a5869...fb4e607 then got into C++ `Map::addAnnotation()` before realizing that this only needs to exist in Java land due to the view bounds checking and view hierarchy adds & deletes in the `MarkerViewManager`, so I'm working on a simpler implementation now. Stay tuned.

**Comment by incanus** [comment]
Ok, this seems to work ok, though I want to test some more edge cases around view recycling as this requires the `aboveMarkerView` to currently be in the view hierarchy. 

Using a modification such as this quickie to `MarkerViewActivity.java` in the test app: 

```diff
diff --git a/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java b/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java
index 0c4eeae..d8bd767 100644
--- a/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java
+++ b/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java
@@ -111,19 +111,20 @@ public class MarkerViewActivity extends AppCompatActivity {
                         .position(new LatLng(38.902580, -77.050102))
                 );
 
-                mMapboxMap.addMarker(new TextMarkerViewOptions()
-                        .text("A")
+                MarkerView a = mMapboxMap.addMarker(new TextMarkerViewOptions()
+                        .text("Aardvark")
                         .position(new LatLng(38.889876, -77.008849))
                 );
 
                 mMapboxMap.addMarker(new TextMarkerViewOptions()
-                        .text("B")
+                        .text("Beethoven")
                         .position(new LatLng(38.907327, -77.041293))
                 );
 
                 mMapboxMap.addMarker(new TextMarkerViewOptions()
-                        .text("C")
+                        .text("Calumet")
                         .position(new LatLng(38.897642, -77.041980))
+                        .aboveMarkerView(a)
                 );
 
                 // if you want to customise a ViewMarker you need to extend ViewMarker and provide an adapter implementation
```

Orders things as `A`, `C`, `B`, despite adding `C` after `B`. 

<img width="149" alt="screen shot 2016-08-02 at 5 24 43 pm" src="https://cloud.githubusercontent.com/assets/17722/17349822/04d2cb96-58d6-11e6-9b80-b58a68f07066.png">

**Comment by incanus** [comment]
I'm having a tough time creating a scenario where this doesn't work. The following scenario worried me at first, but I think it's solid: 

1. Two markers, `A` and `B`, far apart on the map, with a particular ordering (`A` under `B`). 
1. Marker `B` gets removed when far enough out of viewport. 
1. When it comes back into relevance, its view is re-added to the hierarchy automatically. 
1. Since the reference is there to its `aboveMarkerView` (i.e. `A`), `A` is found in the hierarchy, its index is pulled, and `B` is re-added, still under `A` if it still exists. 
1. If `A` ever goes away, that's fine since `B` only specifies `A` as relevant if it exists. 

As far as I can tell with the code and my tests, we are good to go here. 

@tobrun @zugaldia Care to weigh in on https://github.com/mapbox/mapbox-gl-native/pull/5862?

**Comment by incanus** [comment]
_Copying comment from https://github.com/mapbox/mapbox-gl-native/pull/5862#issuecomment-239164783 since we're abandoning that._

@tobrun and I voiced on this at length and worked through some consideration of both an API design like I've proposed as well as a callback-based sort comparator. The short is that it probably makes sense to skip right to the comparator as fetching it from a callback is a lesser consideration on performance than the actual sorting. Additionally, we could add `Parcelable` to `Marker` in order to make the proposed solution work, but the API is still limiting in referring to only one other marker, when marker add order needs to remain flexible.

**Comment by tobrun** [comment]
I'm trying out the most simplistic ordering possible and that is using ordering based on the used adapter. This solves the follow use-case:

> Cars markers should always be shown on top of buildings markers.

Put it other words, a collection of markers should be able to be shown on top or bellow another collection of markers. Currently the different markers need to be implemented with 2 MarkerViewAdapters and I'm thinking of assigning each adapter with it's own FrameLayout (as it now already has it's own view reuse pool). Now an adapter can be added with an index. Where the index is the order in the parent FrameLayout.

To put it in code and images:

```java
addMarkerViewAdapter(new BackgroundViewAdapter(this, 0 /* bottom */);
addMarkerViewAdapter(new TextAdapter(this), 1 /* I'm in front of above */);
```

![device-2016-08-24-131319]
(https://cloud.githubusercontent.com/assets/2151639/17928807/dc4c9ee4-69fc-11e6-9ec5-35ab1ef03707.png)

```java
addMarkerViewAdapter(new BackgroundViewAdapter(this, 0 /* bottom */);
addMarkerViewAdapter(new TextAdapter(this), 0 /* I'm in below of above */);
```

![device-2016-08-24-131550](https://cloud.githubusercontent.com/assets/2151639/17928809/e7288d82-69fc-11e6-8f4b-01ec0b68fbf3.png)

**Comment by tobrun** [comment]
Above comment solves the use-case of ordering different types of MarkerViews, it doesn't encapsulate ordering the same type of MarkerViews. My first attempt will involve using float as z index, this will determine the order how the children are drawn. Since this involves dispatching the draw calls ourselves, we might need to look into create are own ViewGroup and make it possible to do order based on the zIndex value of the MarkerViews.

The difficult part to this system is that views can be recycled when the viewport changes and these need to be restored in correct drawing order. Probably this will result doing the ordering during drawing what could result in a performance hit.

**Comment by zugaldia** [comment]
> Put it other words, a collection of markers should be able to be shown on top or bellow another collection of markers.

I like this approach, even if it's a first iteration. It's consistent with what we do in the Runtime Style API where the z-ordering is attached to the layer, not the annotations. In this case, the adapter (if I understand correctly) would be the equivalent of the layer.

Looking good.

**Comment by tobrun** [comment]
Been testing out the concept of changing the order marker views are drawn. You can do this by calling `setChildrenDrawingOrderEnabled(true)` and overriding `getChildDrawingOrder(int childCount, int i)` on any ViewGroup.

To make this work in MarkerViewManager, we need to maintain a drawing order based on a float. Current thinking is to use the zIndex keyset value of `Map<MarkerView, View>` for this. With this we also have a parity with Marker from Google. If this solution works out we might need to look into not merging https://github.com/mapbox/mapbox-gl-native/issues/5238#issuecomment-242032267 since this will be all inclusive solution and could work for all MarkerViews at the same time.

**Comment by tobrun** [comment]
I got the sorting implemented with a `compareTo`:

```java
   @Override
            public int compare(MarkerView lhs, MarkerView rhs) {
                int compare = Float.compare(lhs.getzIndex(), rhs.getzIndex());
                if (compare == 0) {
                    return Long.valueOf(lhs.getId()).compareTo(rhs.getId());
                }else{
                    return compare;
                }
            }
```

This will sort the keys of a TreeMap based on MarkerView zIndex value, if they are equal we compare using id instead. The last remaining tasks is making actually changing the drawing order for this we need to map to original drawing order on our ordered keys.

**Comment by zugaldia** [comment]
@tobrun is `zIndex == other.getzIndex()` a possibility?

**Comment by tobrun** [comment]
yes, in that case it is calling `super.compareTo(annotation)`  which falls back on the Annotation compareTo which uses comparison on id.  In other words, in case we have the same zIndex, we will layer those MarkerViews based on when it was added to the map.

**Comment by zugaldia** [comment]
@tobrun 👍

**Comment by altafrm3d** [comment]
Is there something to give Z values to Polylines/Polygons to defines in which order should they show up on MapView? If not, does this ticket cover this feature request?

**Comment by hanspeide** [comment]
From what I understand this issue tracks z ordering for `MarkerView`s. Is z ordering for `Marker`s being tracked anywhere?

**Comment by zugaldia** [comment]
@hanspeide This is a good ticket to read about ordering of annotations, particularly this comment: https://github.com/mapbox/mapbox-gl-native/issues/1728#issuecomment-250844066. 

Runtime styling is now available in the latest version of the SDK and can help with some of the use cases described in this ticket. [This activity](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/GeojsonLayerInStackActivity.java), for example, shows how to add a layer below another layer using `mapboxMap.addLayerBelow()`.

**Comment by hanspeide** [comment]
@zugaldia Do layers support adding `Marker`s? If not, what is the alternative?

**Comment by zugaldia** [comment]
@hanspeide You can add a symbol layer with a marker source. There's a [`SymbolLayerActivity`](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/SymbolLayerActivity.java) example in the demo app that shows how to do it. It looks like this:

![SymbolLayerActivity](http://i.imgur.com/TQ4iA0L.png)

In general, the [demo app](https://play.google.com/store/apps/details?id=com.mapbox.mapboxandroiddemo) is a great resource to get a good sense of what's possible using the current APIs (and it's completely open source).

**Comment by tobrun** [comment]
MarkerView is going to be deprecated with https://github.com/mapbox/mapbox-gl-native/pull/9782. We are no longer maintaining this API and will remove it in future versions of the SDK. As noted in the deprecation message. We are advising users to leverage SymbolLayer instead (you can use the sample code in #9782 to convert Android SDK views to an Image to be used as a Symbol). While we no longer maintain the API we are happy to accept any PRs on it.
