### ISSUE TITLE
[Android] Set MarkerViewOptions Rotation as Float-Value

### ISSUE THREAD

**Issue by Schumi09** [mapbox/mapbox-gl-native#5241]
**Platform:**
Android 
**Mapbox SDK version:**
4.1.0-Snapshot

### Expected behavior

Setting the MarkerViews's roation as float via MarkerViewOptions
markerViewOptions.rotation(42.42f)

### Actual behavior

It takes an integer, however the calculations behind are in float anyway and you could set the rotation as float by applying `map.addMarker(markerViewOptions).setRotation(42.42f);` I guess this should be consistent.

**Comment by tobrun** [comment]
This should indeed be float, great catch @Schumi09

**Comment by tobrun** [comment]
Merged with #5251 onto `release-v.4.1.0` branch
