### ISSUE TITLE
Custom LatLngBounds

### ISSUE THREAD

**Issue by kevincyh** [mapbox/mapbox-gl-native#5265]
Hi, is there any way to use custom LatLngBound for OfflineRegion rather than mMapboxMap().getProjection().getVisibleRegion().latLngBounds.
As i notice quite a few of the objects are all default local files and cannot be accessed.

I didn't used the latestMapbox Android SDK v4.1.0-beta.1 because there seems to be conflicting libraries with android libraries. As it will screw the application.

    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:support-v4:23.3.0'
    compile 'com.android.support:cardview-v7:23.0.+'
    compile 'com.android.support:recyclerview-v7:23.0.+'

If i used it i would have some error like this:

    Error:Execution failed for task ':app:transformClassesWithDexForDebug'. >             com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException:     Process 'command 'C:\Program Files\Java\jdk1.8.0_77\bin\java.exe'' finished with non-zero exit value 2

Which  then i try to add this to app build.gradle: 

    defaultConfig {
        multiDexEnabled true
    }

Manage to build and run the app but the cardview will go crazy, e.g the gap between the cardview becomes very far apart like one page only one cardview.

Most importantly is is there anyway i can achieve custom latlngbounds for version 4.0.1 ?

**Mapbox Android SDK v4.0.1
Samsung S5 v5.0**

**Comment by jfirebaugh** [comment]
Hi @kevincyh. Yes, you can pass any `LatLngBounds` object you like to [`OfflineTilePyramidRegionDefinition`](https://www.mapbox.com/android-sdk/api/4.0.1/com/mapbox/mapboxsdk/offline/OfflineTilePyramidRegionDefinition.html). See [here](https://www.mapbox.com/android-sdk/examples/offline-map/) for an example.
