### ISSUE TITLE
Creating an OfflineTilePyramidRegionDefinition crashes with asset:// URL

### ISSUE THREAD

**Issue by rm3dbeckers** [mapbox/mapbox-gl-native#5271]
We've recently tested the offline download on Android and although it looks like the mapView itself accepts styleURLs looking like "asset://style.json" (they load and the tiles are being requested correctly), but the class OfflineTilePyramidRegionDefinition only seems to accept styleUrls of the form "mapbox://styles/mapbox/streets-v9". styleURLs pointing into the assets seem to later cause an error like getHost() called on null reference (or something along that line) and then result in a termination from within the mapbox-gl.so

**Comment by jfirebaugh** [comment]
`asset://` URLs are not supported for offline. You'll need to use a `mapbox://` URL, or have the style hosted somewhere else and use a regular URL.

That said, the expected behavior is an error message, not a crash. Leaving this issue open to investigate that problem.

**Comment by glegrain** [comment]
Hi, I am currently having the same issue on iOS. mapView accepts `asset://` URLs but `MGLTilePyramidOfflineRegion`  does not allow local file URL. 

Looking at the [MGLTilePyramidOfflineRegion](https://www.mapbox.com/ios-sdk/api/3.3.3/Classes/MGLTilePyramidOfflineRegion.html#/c:objc(cs)MGLTilePyramidOfflineRegion(im)initWithStyleURL:bounds:fromZoomLevel:toZoomLevel:) documentation and [code](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/MGLTilePyramidOfflineRegion.mm#L40-L45):

> Relative file URLs cannot be used as offline style URLs.

Why is that?

**Comment by jussirantala** [comment]
Why is this? If I want to serve offline tiles, I need to run a http server on the phone...
