### ISSUE TITLE
Allow for annotation selection z-order change on Android

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#5285]
This is the Android equivalent of what iOS has recently done with https://github.com/mapbox/mapbox-gl-native/issues/991 so that to when you mark an annotation as selected, it comes to the front of the z-order.

/cc: @ivovandongen @bleege @tobrun @cammace @1ec5

**Comment by tobrun** [comment]
This was picked up in #5285 and landed in the release branch of `4.1.0`. Closing.
