### ISSUE TITLE
User dot drawable is not changing in some of Android devices.

### ISSUE THREAD

**Issue by NikunjDave** [mapbox/mapbox-gl-native#5295]
I am using following line of code to change to user (green)dot drawable,

 Drawable myDrawable = ContextCompat.getDrawable(mActivity, R.drawable.map_icon_dummy);
 mMapboxMap.getMyLocationViewSettings().setForegroundDrawable(myDrawable,myDrawable); 

but it is not working with samsung and lenovo devices. i am using mapbox  SDK version 4.1.0-beta.1.
please help me.

**Comment by tobrun** [comment]
@NikunjDave thank you for reaching out, would you abel to retest with **beta2**? I have been doing some fixes on this feature in #5192.

**Comment by NikunjDave** [comment]
@tobrun Thanks a lot. you saved my day. its working perfectly now after update SDK to beta2.
