### ISSUE TITLE
Marker views float over the attribution controls

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#5296]
The new Marker Views float over the attribution controls where the controls should always remain on top.

<img width="176" alt="screen shot 2016-06-09 at 10 52 17" src="https://cloud.githubusercontent.com/assets/64527/15924054/8b81599e-2e30-11e6-9ff3-5f21b2fbd49d.png">

The markers are appended to the same FrameLayout as all the other components. With FrameLayout the order of the children determines the drawing order. An inner layout to contain the Marker Views would do the trick.

**Comment by ivovandongen** [comment]
With container:
<img width="137" alt="screen shot 2016-06-09 at 12 25 05" src="https://cloud.githubusercontent.com/assets/64527/15926711/e8a6147c-2e3d-11e6-8674-84c9ef458732.png">

**Comment by tobrun** [comment]
This was resolved in #5296 and merged into the `release-android-v4.1.0` branch. Closing.
