### ISSUE TITLE
Fix Merge Issue In nativeUpdateMarker

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#5303]
During the merging of `release-android-v4.1.0` back into `master` after Beta 2 shipped ( PR #5291 ) part of the code from #5076 got overridden and needs to be returned.  Specifically, `jni.cpp` had changed in `nativeUpdateMarker` in both branches which led to the confusion.

/cc @jfirebaugh @tobrun

**Comment by bleege** [comment]
Rebased and Merged!

**Comment by jfirebaugh** [comment]
👍
