### ISSUE TITLE
"Downloaded Tiles" count fixed at zero

### ISSUE THREAD

**Issue by mapsam** [mapbox/mapbox-gl-native#5305]
The recent addition of extra data columns to the offline packs 7329a40e73cc5816d7a758282dff8a8eb3af748e doesn't seem to be counting the tiles, and stays at `0`. 

**Platform:** OS X
**Mapbox SDK version:** master

### Steps to trigger behavior

 1. Download an offline map pack
 2. 👀 

### Expected behavior

I would expect the number to be greater than zero.

### Actual behavior

Says `0` tiles downloaded, which doesn't seem right considering there's a calculated size of tiles.

![screen shot 2016-06-09 at 3 44 43 pm](https://cloud.githubusercontent.com/assets/1943001/15949040/5e6a18dc-2e59-11e6-8175-c91aae0a6fa3.png)

cc @1ec5

**Comment by 1ec5** [comment]
Closing and reopening the window updates the cell. I’m not sure why it’s failing to update, but the bug definitely lies in the UI rather than the underlying offline storage implementation.

**Comment by 1ec5** [comment]
Actually, if that were the case, selecting the row would update the cell. With a breakpoint in `-[MGLOfflinePack offlineRegionStatusDidChange:]`, I can see that `mbgl::OfflineRegionStatus`es passed into `mbgl::OfflineRegionObserver::statusChanged()` during download have `completedTileCount` at 0 even after `completedTileSize` begins to increase:

<img width="349" alt="completedTileCount" src="https://cloud.githubusercontent.com/assets/1231218/15949486/be97295e-2e5c-11e6-8645-3c1cbd0aa58e.png">

The reason closing and reopening the window causes the cell to get populated is that `mbgl::DefaultFileSource::getOfflineRegionStatus()` comes back with an `mbgl::OfflineRegionStatus` that does have `completedTileCount` set.

/cc @jfirebaugh
