### ISSUE TITLE
Define Anchor for info window (adapters)

### ISSUE THREAD

**Issue by p-fischer** [mapbox/mapbox-gl-native#5309]
Hi,
this is a feature request.
I'd like to be able define the exact position for an info window.
I can imagine to do this in two steps: 
1. Define first anchor relative to the marker (i.e. the reference point for the info window)
2. Define second anchor relative to the info window (i.e. the info window is drawn starting at the reference point using the latter anchor for the info window position)

**Comment by cammace** [comment]
Don't we give this option using marker views `.setInfoWindowAnchor(float u, float v);`?

**Comment by p-fischer** [comment]
Yes, but this covers only half of my request.
Imagine you have two paper notes and stick them to a wall with a pin. (The bottom note is the marker and the note on top is the info window.) The pin will make a hole in both of the paper notes. So we actually need to be able to define two anchor positions - one for each note.

**Comment by cammace** [comment]
You can set anchoring for both the marker `.anchor()` and info window `.setInfoWindowAnchor()`. This should allow for position customization for each. You can also create a custom marker view and info window and add the necessary anchoring needed.

**Comment by tobrun** [comment]
We currently not thinking about adding this in the near future as there are ways to achieve the desired result and we expose the needed api to make this happen. Closing for now, will reopen if there are more request on this feature.
