### ISSUE TITLE
Update Directions Example In TestApp To V5

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#5319]
While working on #5282 I discovered that the TestApp was still using the original Directions and Geocoding libraries and hadn't been updated to MAS yet.  I did the upgrade in #5282 but left the Directions example using the V4 version as that's what the original Directions library was using and I had other fish to fry.  Once #5282 lands we should double back and update the Directions example to use the V5 API.

**Comment by cammace** [comment]
The directions example was updated in https://github.com/mapbox/mapbox-gl-native/pull/6843. Closing.
