### ISSUE TITLE
Crash when enabling MyBearingTracking

### ISSUE THREAD

**Issue by justasm** [mapbox/mapbox-gl-native#5331]
**Platform:** Android
**Mapbox SDK version:** 4.1.0-beta.2

### Steps to trigger behavior

 1. `mapboxMap.getTrackingSettings().setMyBearingTrackingMode(MyBearingTracking.GPS);`

or

1. `mapboxMap.getTrackingSettings().setMyBearingTrackingMode(MyBearingTracking.COMPASS);`

or

1. Open `User tracking mode` demo (i.e. `MyLocationTrackingModeActivity`) in Mapbox Android SDK TestApp.
2. In top right dropdown, select `GPS bearing` or `Compass bearing`.

### Expected behavior
Bearing tracking enabled.

### Actual behavior
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.trafi.android.dev, PID: 24710
                  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.animation.ValueAnimator.getAnimatedValue()' on a null object reference
                  at com.mapbox.mapboxsdk.maps.widgets.MyLocationView.onDraw(MyLocationView.java:264)
                  at android.view.View.draw(View.java:17469)
                  ... etc
```

**Comment by zugaldia** [comment]
Confirmed crash and fix. I just merged the PR via https://github.com/mapbox/mapbox-gl-native/pull/5381 and the code will be available in the next Android 4.1 release.

Thank you @justasm !
