### ISSUE TITLE
Unresponsive MyBearingTracking.COMPASS behavior

### ISSUE THREAD

**Issue by justasm** [mapbox/mapbox-gl-native#5335]
**Platform:** Android
**Mapbox SDK version:** 4.1.0-beta.2 + #5333 
### Steps to trigger behavior
1. Open `User tracking mode` demo (i.e. MyLocationTrackingModeActivity) in Mapbox Android SDK TestApp.
2. In top right dropdown, select `Compass bearing`.
### Expected behavior

Bearing indicator starts responding immediately and correctly indicates the device's bearing.
### Actual behavior

Bearing indicator remains stuck indicating north for multiple seconds. The indicator updates occasionally but eratically, and does not correctly indicate the device's bearing for the majority of the time.

There are two issues at play here:
1. The logic in the [`CompassListener#onSensorChanged(SensorEvent)`](https://github.com/mapbox/mapbox-gl-native/blob/041a351fb279751ede35fc0860651176ec0ca292/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java#L524) callback [is throttled](https://github.com/mapbox/mapbox-gl-native/blob/041a351fb279751ede35fc0860651176ec0ca292/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java#L531) according to [`UPDATE_RATE_MS`](https://github.com/mapbox/mapbox-gl-native/blob/041a351fb279751ede35fc0860651176ec0ca292/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java#L500). Two types of events (accelerometer and magnetometer) are sent to this callback, but the arrival of either one subsequently blocks processing for `UPDATE_RATE_MS`. In my testing, it was common for e.g. multiple seconds of magnetometer events only to be processed. This would simultaneously block any accelerometer data for that period of time. If this happens at the start when either sensor value array is zeroed, the bearing output remains zero until both types of sensor data are processed. If this happens at a later time, either the magnetometer or the accelerometer data may become multiple seconds out-of-date, resulting in an incorrect bearing calculation.
2. The bearing indicator rotation is reflected in [`MyLocationView#onDraw(Canvas)`](https://github.com/mapbox/mapbox-gl-native/blob/041a351fb279751ede35fc0860651176ec0ca292/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java#L264). `MyLocationView#setCompass(float)` [starts an animator](https://github.com/mapbox/mapbox-gl-native/blob/041a351fb279751ede35fc0860651176ec0ca292/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java#L447) to update the bearing indicator rotation. However, this animator does not call `MyLocationView#invalidate()` during the animation. This results in the bearing indicator updating only when something else coincidentally invalidates `MyLocationView`.

**Comment by justasm** [comment]
On a somewhat related note, the bearing indicator animation may appear more continuous if the [animation duration][animation-duration] matches the [update rate][update-rate], instead of using a seemingly arbitrary value of `375`.

[animation-duration]: https://github.com/mapbox/mapbox-gl-native/blob/release-android-v4.1.0/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java#L446
[update-rate]: https://github.com/mapbox/mapbox-gl-native/blob/release-android-v4.1.0/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java#L500

**Comment by tobrun** [comment]
Still need to pick up suggestion in https://github.com/mapbox/mapbox-gl-native/issues/5335#issuecomment-225684078 to close this issue.

**Comment by cammace** [comment]
The bearing indicator animation has been changed recently to be more continuous.
