### ISSUE TITLE
Enforce code style with clang-format

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#5342]
We've [re-enabled clang-tidy checks](https://github.com/mapbox/mapbox-gl-native/pull/5325) as part of establishing good practices in our code changes. Keeping in line with that, we should start using `clang-format` - it automatically formats C++ code according to a set of configuration options - we actually maintain a [.clang-format](https://github.com/mapbox/mapbox-gl-native/blob/master/.clang-format) config already.

As @kkaefer suggested, we should have a bot that:

1. Runs `clang-format -i` over `mapbox-gl-native` codebase;
2. Runs `git diff`, then fails if there are any differences (showing diff output for reference).

:eyes: @mapbox/gl

**Comment by mikemorris** [comment]
Any way that we could script this into `make test` instead of relying on CI?

**Comment by brunoabinader** [comment]
> Any way that we could script this into make test or npm test instead of relying on CI?

Yes, there will be a Makefile target for that - I suggest `make check` to separate it from unit test runs 👍 .

Intent of adding it to CI is to prevent people from committing code that would eventually need to be sanitized later. Unlike `clang-tidy`, though, `clang-format` runs pretty fast (takes a couple seconds to perform) so I believe that won't be an issue.
