### ISSUE TITLE
Can't run make tidy locally

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#5344]
Running `make tidy` on macOS produces:

```
~/Development/mapbox-gl-native $ make tidy
deps/run_gyp --depth=. -Goutput_dir=. -f ninja -I build/osx/config.gypi \
	  --generator-output=build/osx platform/osx/platform.gyp
deps/ninja/ninja-osx -C build/osx/Debug \
		-t compdb cc cc_s cxx objc objcxx > build/osx/Debug/compile_commands.json
deps/ninja/ninja-osx -C build/osx/Debug headers
ninja: Entering directory `build/osx/Debug'
ninja: no work to do.
scripts/clang-tidy.sh build/osx/Debug
/Users/john/Development/mapbox-gl-native/build/osx/Debug
Running clang-tidy checks... (this might take a while)
Error: A clang-tidy warning/error happened:
/Users/john/Development/mapbox-gl-native/mason_packages/osx-x86_64/clang-tidy/3.8/bin/../include/c++/v1/wchar.h:119:15: error: 'wchar.h' file not found [clang-diagnostic-error]
#include_next <wchar.h>
              ^
Error: A clang-tidy warning/error happened:
/Users/john/Development/mapbox-gl-native/mason_packages/osx-x86_64/clang-tidy/3.8/bin/../include/c++/v1/ctime:48:10: error: 'time.h' file not found [clang-diagnostic-error]
#include <time.h>
         ^
Error: A clang-tidy warning/error happened:
/Users/john/Development/mapbox-gl-native/mason_packages/osx-x86_64/clang-tidy/3.8/bin/../include/c++/v1/ctime:48:10: error: 'time.h' file not found [clang-diagnostic-error]
#include <time.h>
         ^
Error: A clang-tidy warning/error happened:
../../../include/mbgl/platform/default/headless_view.hpp:4:10: error: 'TargetConditionals.h' file not found [clang-diagnostic-error]
#include <TargetConditionals.h>
         ^
Error: A clang-tidy warning/error happened:
/Users/john/Development/mapbox-gl-native/mason_packages/osx-x86_64/clang-tidy/3.8/bin/../include/c++/v1/ctime:48:10: error: 'time.h' file not found [clang-diagnostic-error]
#include <time.h>
         ^
[etc]
```

**Comment by jfirebaugh** [comment]
cc @brunoabinader

**Comment by brunoabinader** [comment]
That happens because you are not using the `clang-tidy` binary provided via mason. We intentionally left the mason install of it out of Makefile/configure scripts because we don't want all builds (incl. Travis, Bitrise, etc.) to download a binary package if only `clang-tidy` bot uses it - it gets downloaded in `https://github.com/mapbox/mapbox-gl-native/blob/master/platform/osx/bitrise-tidy.yml#L34`.

If you want to use a different `clang-tidy` version other than the mason one, you can change it by passing CLANG_TIDY to `make tidy`:
```
$ CLANG_TIDY=<full/path/to>/clang-tidy make tidy
```

The errors you see are caused by lack of knowledge of standard C++ headers, you can fix those by adding an additional parameter to clang-tidy:
```
$ CLANG_TIDY="clang-tidy -extra-arg=-I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1" make tidy

**Comment by brunoabinader** [comment]
We're now installing mason `clang-tidy` if CLANG_TIDY is not set in https://github.com/mapbox/mapbox-gl-native/pull/5347.

**Comment by jfirebaugh** [comment]
Still happening on lastest `master`, with the same error messages.

**Comment by brunoabinader** [comment]
These are now fixed by using @springmeyer's `clang-tidy` build - fix in https://github.com/mapbox/mapbox-gl-native/commit/ca7330a9b4fc99f55063d59e5831dbe84bd8edba - PR https://github.com/mapbox/mapbox-gl-native/pull/5341.

**Comment by jfirebaugh** [comment]
Nope, still happening.

**Comment by brunoabinader** [comment]
I've just tested running `make tidy` after a clean build without issues. I can only guess you have an old version of the `clang-tidy` mason package that was built before https://github.com/mapbox/mason/commit/ab45a54aaa4d9d68b7bb936ec729470a26564338 & https://github.com/mapbox/mason/commit/56e8cd4b8128f456356f999d215816618f47e571. It's unfortunate that we can't control the _version_ of a mason binary package itself (and not the version it represents).

@jfirebaugh can you please run `mason remove clang-tidy 3.8.0 && make tidy` and see if that fixes the issue?

**Comment by jfirebaugh** [comment]
No, that's not it -- I have been testing from a fresh `make clean && make distclean` repo each time.

@springmeyer was doing some poking around and thought that it was the fact that my laptop doesn't have `/usr/include/wchar.h`.

**Comment by springmeyer** [comment]
> @springmeyer was doing some poking around and thought that it was the fact that my laptop doesn't have /usr/include/wchar.h.

Yes, this was the problem. The clang-tidy binary is expecting C headers in  `/usr/include/`. @jfirebaugh did not have them here and only in `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/wchar.h`.

My understanding is that the Xcode command line install puts things in `/usr/include` and that the command line tools are required for building gl-native. But perhaps not and @jfirebaugh has been doing just fine without them installed?

**Comment by brunoabinader** [comment]
@jfirebaugh is this still an issue?

**Comment by jfirebaugh** [comment]
Nope, it's working now.
