### ISSUE TITLE
[tidy] Run clang-tidy checks for platform-specific code

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#5349]
Follow-up for #5341 - there are some platform-specific code not being verified by the clang-tidy bot because it doesn't get compiled for Linux.

To address that, we'd need to run `clang-tidy` checks for each supported platform (Android, iOS, Node, Qt, Linux, macOS...). While it seems like a lot of extra effort, the runtime for platform-specific checks would be quite low because we'd only need to scan `platform/*.cpp` for each of these platforms.

My idea is to add an extra step on each of the build bots we have for this, and have a separate `clang-tidy` bot that only checks `src/mbgl/*.cpp` & `test/*.cpp`.

Thoughts?

:eyes: @jfirebaugh @kkaefer

**Comment by jfirebaugh** [comment]
Is there no way to integrate the clang tidy checks in the normal compile process. Ideally they just work like other compiler warnings/errors:

* No duplicated parsing / analyzing work
* All existing clang builds are tidied
* Integrated in normal development workflow -- e.g. errors show up in Xcode, no need to wait for CI

**Comment by brunoabinader** [comment]
@jfirebaugh I am proposing a `lint` target that can be integrated with regular build process in https://github.com/mapbox/mapbox-gl-native/pull/5411.
