### ISSUE TITLE
builds may break due to mapbox_time script

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-gl-native#535]
I've run into two circumstances where the `mapbox_time` travis wrappers may break:

1) Build is abruptly stopped with 137 (and no visible error)

This one is completely mysterious to me. All I know is that when using `mapbox_time` within the  [android-mason branch](https://github.com/mapbox/mapbox-gl-native/tree/android-mason) 9 times out of 10 I see:

```
$ sudo apt-get -y install gcc-4.8 g++-4.8

The command "./scripts/travis_before_install.sh" failed and exited with 137 during .
```

The only workaround I've found is removing `mapbox-time` usage from https://github.com/mapbox/mapbox-gl-native/blob/android-mason/scripts/travis_before_install.sh. 

My guess is that another workaround might be removing the `set -e` but I've not tried this.

2) Commands that need to set an ENV variable

This breaks:

    mapbox_time "message" FOO=bar ./program

With:

```
./scripts/travis_helper.sh: line 20: 1414960028723466010-: syntax error: operand expected (error token is "-")
```

Because it appears somehow [$end_time is undefined](https://github.com/mapbox/mapbox-gl-native/blob/551ff954a5e30c89c27f59a9848ba0a9be871adc/scripts/travis_helper.sh#L20)

This workaround does not work (same error):

    mapbox_time "message" $(FOO=bar ./program)

**Comment by jfirebaugh** [comment]
Haven't seen this issue recently.
