### ISSUE TITLE
Make InfoWindowAdapter dynamically updateable

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#5353]
Analog to https://github.com/mapbox/mapbox-gl-native/issues/5237.

Add the possibility to invalidate the `InfoWindowAdapter` so that the content is refreshed on the map. As the `InfoWindowAdapter` is an interface and we don't want to break the api, the easiest way to provide this would probably be add an abstract class extending `InfoWindowAdapter`  with an  `invalidate()` method that may be called so that the infowindow contents is refreshed.

**Comment by ivovandongen** [comment]
Added an example on how to dynamically update the InfoWindow contents on some trigger (map clicks in this example).

Did have to change up the placement update code on InfoWindow a bit. All-in-all, I think this needs a bit of an overhaul as there are already too many exceptions in there and it's not really meant for updating (only initial placement).

**Comment by tobrun** [comment]
This was merged with `4.1.0` release branch in https://github.com/mapbox/mapbox-gl-native/pull/5375, adding milestone and closing.
