### ISSUE TITLE
Enable overdraw debug mode API on Android

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#5363]
We now have a wireframe debug mode via https://github.com/mapbox/mapbox-gl-native/pull/4359 which iOS is now exposing in the iOS and OS X SDKs and their demo applications via https://github.com/mapbox/mapbox-gl-native/commit/22ef615f360bb5e0ea58491620f0fc59da8f491b.

This ticket focuses on bringing this to Android.

/cc: @brunoabinader

**Comment by brunoabinader** [comment]
__Note__: We're going to modify the internal implementation of wireframe to use JS's `OVERDRAW_INSPECTOR` - see https://github.com/mapbox/mapbox-gl-native/issues/5371 - but that won't affect the way how we expose the feature for platforms 👍.

**Comment by zugaldia** [comment]
@brunoabinader 👍 thanks for the heads up.

**Comment by brunoabinader** [comment]
We decided to rename this to `overdraw` to match JS implementation.

**Comment by brunoabinader** [comment]
With https://github.com/mapbox/mapbox-gl-native/issues/5435 fixed, we have cleared the way to enable this in Android.

**Comment by tobrun** [comment]
Looked into this and we do not expose enabling specific debug options, only integration with Map::cycleDebugOptions. As overdraw was added there we are good to close. 
Thank you @brunoabinader for implementing this!

```cpp
void Map::cycleDebugOptions() {
#if not MBGL_USE_GLES2
   if (impl->debugOptions & MapDebugOptions::StencilClip)
       impl->debugOptions = MapDebugOptions::NoDebug;
   else if (impl->debugOptions & MapDebugOptions::Overdraw)
       impl->debugOptions = MapDebugOptions::StencilClip;
#else
   if (impl->debugOptions & MapDebugOptions::Overdraw)
       impl->debugOptions = MapDebugOptions::NoDebug;
#endif // MBGL_USE_GLES2
   else if (impl->debugOptions & MapDebugOptions::Collision)
       impl->debugOptions = MapDebugOptions::Overdraw;
   else if (impl->debugOptions & MapDebugOptions::Timestamps)
       impl->debugOptions = impl->debugOptions | MapDebugOptions::Collision;
   else if (impl->debugOptions & MapDebugOptions::ParseStatus)
       impl->debugOptions = impl->debugOptions | MapDebugOptions::Timestamps;
   else if (impl->debugOptions & MapDebugOptions::TileBorders)
       impl->debugOptions = impl->debugOptions | MapDebugOptions::ParseStatus;
   else
       impl->debugOptions = MapDebugOptions::TileBorders;

   impl->onUpdate(Update::Repaint);
}
```
