### ISSUE TITLE
Marker - extra object

### ISSUE THREAD

**Issue by tomlocks** [mapbox/mapbox-gl-native#5370]
Hi,

I have a problem with MapBox marker API. I've added few markers to my app, but when onMarkerClick is called I cannot distinguish between them. I mean is there any method to put some extra object to Marker object to have it back easily during onMarkerClick? Something like setTag in Android's views. For example I want to open webpage with link, when Marker has one.  Is It possible to do something like that?

I use 4.1.0-beta.2 version for Android;

Thanks.

**Comment by tobrun** [comment]
@tomlocks thank you for reaching out.

If you are using GL Markers, the marker object itself is passed in the OnClick:

```java
    /**
     * Interface definition for a callback to be invoked when the user clicks on a marker.
     *
     * @see MapboxMap#setOnMarkerClickListener(OnMarkerClickListener)
     */
    public interface OnMarkerClickListener {
        /**
         * Called when the user clicks on a marker.
         *
         * @param marker The marker the user clicked on.
         * @return If true the listener has consumed the event and the info window will not be shown.
         */
        boolean onMarkerClick(@NonNull Marker marker);
    }
```

If you want to reference an extra attribute in that onMarkerClick. You can extend Marker and add a String attribute to it:

```java
public class UrlMarker extends Marker {

    private String url;

    public UrlMarker(BaseMarkerOptions baseMarkerOptions, String url) {
        super(baseMarkerOptions);
        this.url = url;
    }

    public String getUrl() {
        return url;
    }
}
```

Builder for it:

```java
public class UrlMarkerOptions extends BaseMarkerOptions<UrlMarker, UrlMarkerOptions> {

    private String url;
    
   public UrlMarkerOptions url(String name) {
        url = name;
        return getThis();
    }

    public UrlMarkerOptions() {
    }

    private UrlMarkerOptions(Parcel in) {
        position((LatLng) in.readParcelable(LatLng.class.getClassLoader()));
        snippet(in.readString());
        String iconId = in.readString();
        Bitmap iconBitmap = in.readParcelable(Bitmap.class.getClassLoader());
        Icon icon = IconFactory.recreate(iconId, iconBitmap);
        icon(icon);
        url(in.readString());
    }

    @Override
    public UrlMarkerOptions getThis() {
        return this;
    }

    @Override
    public UrlMarker getMarker() {
        return new UrlMarker(this, url);
    }

    public static final Parcelable.Creator<UrlMarkerOptions> CREATOR
            = new Parcelable.Creator<UrlMarkerOptions>() {
        public UrlMarkerOptions createFromParcel(Parcel in) {
            return new UrlMarkerOptions(in);
        }

        public UrlMarkerOptions[] newArray(int size) {
            return new UrlMarkerOptions[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel out, int flags) {
        out.writeParcelable(position, flags);
        out.writeString(snippet);
        out.writeString(icon.getId());
        out.writeParcelable(icon.getBitmap(), flags);
        out.writeString(url);
    }

}

```

Note that I haven't validated the code above in an IDE, code is based on CountryMarker and CountryMarkerOptions found in our testapp. In the OnMarkerClick listener you can cast the Marker to a UrlMarker and fetch the url you need.

Reach out if you have any other questions!

**Comment by tomlocks** [comment]
Thanks for your answer. It helped me a lot.

I have one more question about markers. Is there a way to show Markers only for specific zoom level. I.e. to show markers only if zoom is bigger than 11? Or even something like hiding added markers based on conditions? Does API expose that kind of methods, or do I have to register listener for camera changes and add/remove based on this event?

**Comment by tobrun** [comment]
Ideally what you are indicating is having support for clustering which will incorporate these type of features. While we haven't implemented support for it yet, it's coming in the next months. 

For now you definitly can implement the requirements you mention above by using components as OnCameraChangeListener to listen to zoom level changes and by using the ViewMarker API instead of the Marker API you can use the visible attribute to hide the markers.
