### ISSUE TITLE
Select marker view annotation not working properly

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5384]
When calling `MapboxMap.selectMarker()` on a view annotation the info window isn't placed above the marker like it is when you click the marker yourself:

![2016-06-16 16_56_01](https://cloud.githubusercontent.com/assets/5652865/16132911/44487a9a-33e3-11e6-8747-86af084d4ca1.gif)

cc: @tobrun @zugaldia @ivovandongen @bleege

**Comment by tobrun** [comment]
@cammace I guess the ViewMarker is not measured yet and thus resulting in a offset of {0,0}. 
From end user perspective there are two workarounds:
 - global layout change listener
 - delaying the selectMarker call with something as a Handler

**Comment by cammace** [comment]
> delaying the selectMarker call with something as a Handler

selectMarker was already being called after a short delay (in the geocoding onResponse) but I added a handler anyways and the problem still persist. 

```java
final Handler handler = new Handler();
handler.postDelayed(new Runnable() {
    @Override
    public void run() {
        map.selectMarker(droppedMarker);
    }
}, 500);
```

**Comment by tobrun** [comment]
@ivovandongen is investigating this and it's correct that delaying does not resolve it.
We need to migrate code from the internal onClick listener to the `selectMarker` method.

**Comment by ivovandongen** [comment]
@cammace Found the problem. Is coming together with https://github.com/mapbox/mapbox-gl-native/issues/5282

**Comment by zugaldia** [comment]
@cammace The PR has now landed via https://github.com/mapbox/mapbox-gl-native/pull/5391, please reopen if you still observe this issue happening in the release branch.
