### ISSUE TITLE
Tilt: Location accuracy circle behaves weird/wrong when map is tilted

### ISSUE THREAD

**Issue by rm3dbeckers** [mapbox/mapbox-gl-native#5395]
Hi guys,

we have discovered that the accuracy circle drawn around the current (gps) location behaves extremely weird when the map is tilted (feels like the inverse of what should happen). It's hard to explain (but I think the following screenshots should illustrate the problem), but it looks like the perspective distortion of the circle causes the circle to grow (relative to its size when looking at it top-down).
![tilt_2](https://cloud.githubusercontent.com/assets/17709375/16160085/795beee0-34c6-11e6-8b29-849d4b6c11fd.png)
![tilt_1](https://cloud.githubusercontent.com/assets/17709375/16160086/795e921c-34c6-11e6-8d33-447acfa27537.png)

This was observed on Android, but I guess it is a problem affecting all platforms, as it should be part of the native part of the map view.

Best regards

**Comment by zugaldia** [comment]
@rm3dbeckers Thanks for the report, which version of the Android SDK are you using? We recently performed an `UserLocationView` refactor https://github.com/mapbox/mapbox-gl-native/issues/4396 but I can't observe this behavior with the latest version of the code. Could you try with `beta2` as described in https://www.mapbox.com/android-sdk/#gradle?

![screenshot_20160617-152508](https://cloud.githubusercontent.com/assets/6964/16162193/ed6d548a-349f-11e6-8f87-742f82380e8d.png)

/cc: @tobrun

**Comment by tobrun** [comment]
This was fixed with https://github.com/mapbox/mapbox-gl-native/pull/5192.
