### ISSUE TITLE
[Android 4.1.0-beta.2] Mapbox Marker render error

### ISSUE THREAD

**Issue by cbiao** [mapbox/mapbox-gl-native#5401]
1. Code do: Every 3 second draw 10~20 new Bitmap or Drawable >  factory.fromBitmap(...) create Icon > map.removeAnnotations(); > addMarker(...) > Loop...;
2. In the first ~1min all icon render right, then some icon begin appear render error, few minutes later all icon disappeared.

![2016-06-18_223637](https://cloud.githubusercontent.com/assets/11626084/16171602/93569a2c-35a5-11e6-9556-4eae10b5703b.png)

**Comment by Schumi09** [comment]
Hi,

just use MarkerViews instead of Markers #5019 :+1:

**Comment by cbiao** [comment]
Thank you, but MarkerViews have bug https://github.com/mapbox/mapbox-gl-native/issues/5402

**Comment by vfaSonnt** [comment]
I saw this bug from many previous version. I can not screenshot my app because the policy with my client doesn't allow. I think there is a problem with reusing sprite marker, I have to write my own sprite management. After that it work fine.

**Comment by zugaldia** [comment]
This originally looked like a recent regression, but it isn't. I'm removing it from the current milestone and we'll tackle it at a future release.

**Comment by tobrun** [comment]
This as mentioned by others a bug that has been around for quit some time with gl based markers. For now I would suggest to use View Markers for your use case. The #5402 issue is resolved, and PR'ed in https://github.com/mapbox/mapbox-gl-native/pull/5484.

**Comment by jfirebaugh** [comment]
Is this still an issue in version 5.0.0 of the Android SDK?
