### ISSUE TITLE
[Android 4.1.0-beta.2] Mapbox LatLngBounds longitude and 'contains' algorithm error

### ISSUE THREAD

**Issue by cbiao** [mapbox/mapbox-gl-native#5402]
1. When 'west' longitude is positive, 'east' longitude is negative, LatLngBounds will invert west and east values.

2. This error make MarkerView (may only visiable in LatLngBounds by default) not show.

3. After fix this bug, the 'contains' method of LatLngBounds also needs to be changed:

- The current algorithm:
![2016-06-18_233237](https://cloud.githubusercontent.com/assets/11626084/16172530/5a5ac5d6-35be-11e6-9733-6cdb7bec3517.png)

- The right way (longitude part):
![2016-06-18_234426](https://cloud.githubusercontent.com/assets/11626084/16172536/80cc246c-35be-11e6-820a-d8896a9af444.png)

4. sample:

- log: [N:77.02707134184479; **E:177.68434665041946**; S:-53.55760179239366; **W:33.0421182655507**]

![2016-06-19_005652](https://cloud.githubusercontent.com/assets/11626084/16172333/f850f3ec-35b8-11e6-9734-51572f5e6603.png)

- log: [N:77.40489180472454; **E:41.58002794488527**; S:-52.53107115100817; **W:-173.77774367024602**]

> (should be: [N:77.40489180472454; **E:-173.77774367024602**; S:-52.53107115100817; **W:41.58002794488527**])

![2016-06-19_015903](https://cloud.githubusercontent.com/assets/11626084/16172774/a77dbbe0-35c1-11e6-9175-2dac1d2c796d.png)

**Comment by tobrun** [comment]
This is due calling `nativeGetAnnotationsInBounds` on the dateline, this is something that should be resolved with https://github.com/mapbox/mapbox-gl-native/issues/4522.

**Comment by zugaldia** [comment]
#4242 requires a semver change, removing from this milestone for now.

**Comment by cbiao** [comment]
if "_We can't change the wrapping semantics again until the next major version: 5.0_", is it possible to **make MarkerView visiable out of LatLngBounds**? Thank you!

**Comment by tobrun** [comment]
Issue:
![ezgif com-video-to-gif 11](https://cloud.githubusercontent.com/assets/2151639/16364980/2ee74c08-3bf4-11e6-80b2-c3e3d1153dda.gif)

Solution:
![ezgif com-video-to-gif 13](https://cloud.githubusercontent.com/assets/2151639/16364977/1f4cf96e-3bf4-11e6-81be-a2d2fc718ebb.gif)

@cbiao thank you for reaching out and help resolving the bug.

**Comment by zugaldia** [comment]
Fixed via https://github.com/mapbox/mapbox-gl-native/pull/5484.
