### ISSUE TITLE
-[MGLMapView viewForAnnotation:]

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5406]
For parity with MapKit, we should add a method to MGLMapView that looks like:

```objc
- (nullable MGLAnnotationView *)viewForAnnotation:(id<MGLAnnotation>)annotation SWIFT_NAME(view(for:));
```

which would bridge to Swift as:

```swift
func view(for annotation: MGLAnnotation) -> MGLAnnotationView?
```

/cc @frederoni @boundsj

**Comment by docterd** [comment]
The same should apply to 

`- (void)mapView:(MGLMapView *)mapView didAddAnnotationViews:(NSArray<MGLAnnotationView *> *)views`

**Comment by boundsj** [comment]
> @docterd The same should apply to

> - (void)mapView:(MGLMapView *)mapView didAddAnnotationViews:(NSArray<MGLAnnotationView *> *)views

Noting that this was picked up in https://github.com/mapbox/mapbox-gl-native/issues/5465
