### ISSUE TITLE
loading style failed

### ISSUE THREAD

**Issue by Fresi** [mapbox/mapbox-gl-native#5420]
**Platform:** IOS (Swift)
**Mapbox SDK version:** 3.2.3

I am a begginer in IOS and I'm trying to include a Mapbox in my project, but I have a problem and I can't find a solution.

### Steps to trigger behavior

 1.  I included a UIView with the MGLMapView class.
 2.  I added the Access Token
 3.  Added the Style URL

![accesstoken](https://cloud.githubusercontent.com/assets/20064186/16225322/693df336-37a6-11e6-954f-647022dd5d37.png)
![styleurl](https://cloud.githubusercontent.com/assets/20064186/16225421/b3e0a99c-37a6-11e6-9a37-bc94453233cf.png)

### Expected behavior
It should show the map.

### Actual behavior
But instead the UIView shows a black screen and shows the next fail in the console:
**[ERROR] {Map}[Setup]: loading style failed: HTTP status code 401**

![screen](https://cloud.githubusercontent.com/assets/20064186/16225571/94ed1060-37a7-11e6-977f-d3180427807e.png)

The Access Token and the Style URL are right because in Android works fine.

**Comment by 1ec5** [comment]
Is there any whitespace before or after the access token in the text field?

**Comment by friedbunny** [comment]
Indeed, that access token and style combination also works on iOS when entered correctly.

**Comment by Fresi** [comment]
There was a whitespace after the token, thank you, I would never have thought of that. Now it's working.

**Comment by friedbunny** [comment]
👌

**Comment by ducmaxime** [comment]
Hello everybody,

I try to use map box inside QT project. I'm on MACOXS.

When I run the project on Desktop version It's working find.

But on iOS I have a white screen.

any idea ?

**Comment by 1ec5** [comment]
Hi @ducmaxime, please open a separate issue or [contact our support team](https://www.mapbox.com/contact/support/). What you’re experiencing sounds unrelated to the issue that was reported here.
