### ISSUE TITLE
Simplify marker position animation

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5422]
Now that animating a marker to a new location performs better, we should use `setPosition()` to take in more parameters. For example, it would be great if I could call `marker.setPosition(new LatLng(), 5000);` and the marker would animate linearly using the time. Also including a callback would be good so I could perform an action when the animation finishes. 

cc: @zugaldia @tobrun @bleege @ivovandongen

**Comment by zugaldia** [comment]
I really like this. FWIW, I don't see any equivalent methods in the [Google Maps API](https://developers.google.com/android/reference/com/google/android/gms/maps/model/Marker.html#public-methods).

**Comment by bleege** [comment]
Great idea to extend the base Google Maps API into something that Mapbox provides @cammace!

**Comment by tobrun** [comment]
Plan is to deprecate annotation api and we will address this use-case with symbol manager work happening in https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-annotation
