### ISSUE TITLE
User location detached from map when tracking

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5426]
When my location tracking is enabled (following) and you zoom in and out or rotate the map, the user location becomes detached from the map.

![tracking_gesture_error](https://cloud.githubusercontent.com/assets/5652865/16239548/45d8438a-37b3-11e6-8b0a-a81b69bc59e9.gif)

cc: @tobrun @zugaldia

**Comment by cammace** [comment]
Further testing this appears to only happen in landscape mode.

**Comment by tobrun** [comment]
Nice find @cammace, I will look into reproducing before the actual release.
 I'm adding it to the milestone for that reason.

**Comment by tobrun** [comment]
I'm not able to reproduce this with the test app. 

![ezgif com-video-to-gif 40](https://cloud.githubusercontent.com/assets/2151639/16301375/680301b4-3945-11e6-8045-4f3199134b47.gif)

 - What version are you using?
 - Can you point me to the code where this is occuring?

**Comment by tobrun** [comment]
Since I'm not able to reproduce with release branch, removing it from the milestone

**Comment by cammace** [comment]
Not sure what was causing this issue @tobrun, haven't been able to reproduce this since. Closing for now.
