### ISSUE TITLE
Marker view flat bug

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5427]
When an activity initiates the map with a tilt with a marker view flat set to true the icon isn't flattened until the user tilts the map manually. 

Purple marker in this gif shows what happens:
![ezgif com-video-to-gif 3](https://cloud.githubusercontent.com/assets/5652865/16242918/ce230c8e-37c2-11e6-8841-0d1823369f46.gif)

cc: @tobrun @zugaldia

**Comment by tobrun** [comment]
Fixed this with adding:

```java
 if (marker.isFlat() && marker.getTilt() == 0) {
      marker.setTilt((float) mapboxMap.getCameraPosition().tilt);
 }
```

Result:

![ezgif com-video-to-gif 39](https://cloud.githubusercontent.com/assets/2151639/16296118/e6999f8a-392a-11e6-90e7-5cceeaa6c009.gif)

**Comment by zugaldia** [comment]
Fixed via https://github.com/mapbox/mapbox-gl-native/pull/5449.
