### ISSUE TITLE
Snap current GPS location before updating my location view

### ISSUE THREAD

**Issue by kingfisherphuoc** [mapbox/mapbox-gl-native#5430]
**Platform: Android**
**Mapbox SDK version:  4.1.0-beta.3**
### Steps to trigger behavior
1. Enable tracking mode in MapboxMap:
   <br><code>final TrackingSettings trackingSettings = mapboxMap.getTrackingSettings();
   trackingSettings.setMyBearingTrackingMode(MyBearingTracking.GPS);
   trackingSettings.setMyLocationTrackingMode(MyLocationTracking.TRACKING_FOLLOW);</code>
2. Draw routes from my current position to a specific location with: <code>mapboxMap.addPolyline(polylineOptions);</code>
3. Start driving, following the routes in map. 
### Expected behavior

The location icon is drawn and animated in center of the routes
### Actual behavior

the location icon (circle shape) is usually drawn beside the routes. 
### How to solve?

Is there a way to snap GPS to the icon to the center of the routes? After looking at the source code of the android sdk, I saw the position icon is updated automatically by <code>GpsLocationListener</code>. Is there any way to disable it, and update the position myself? like the code below:
<code>
 private LocationListener mLocationListener = new LocationListener() {

```
    @Override
    public void onLocationChanged(Location location) {
            mSnapLocation = calculateSnapePosition(location, routes);
            mMap.getMapView().getUserLocationView().setLocation(mSnapLocation)
    }
};
```

</code>

**Comment by cammace** [comment]
If you'd like to customize the user location position the best solution would be using markers to represent the user location. For snapping of the user location, you can use our Map Matching API to snap coordinates to the closest road (won't take into consideration your route). This is something we will most likely implement for navigation and you'll find it inside [mapbox-java](https://github.com/mapbox/mapbox-java). Feel free to reach out through [our contact page](https://www.mapbox.com/contact/) if you have any additional questions on this.
