### ISSUE TITLE
Two finger zoom bug with markers.

### ISSUE THREAD

**Issue by Buminta** [mapbox/mapbox-gl-native#5433]
**Android:**
**Mapbox SDK version: 4.1.0-beta3**

Hi Mapbox Team. I had a problem when finger touch for zoomin, zoomout, moveCamera, or scaleZ view
If i hold one finger on one marker and do it. Mapbox camera doesn't change with touch move event.

That's not true for performance when i'm use add large count of markers!

### Steps to check bug

```
1. Add marker to MapboxMap.
2. Touch one finger on Marker and one finger on Map or other marker
3. And move two finger to zoomin or zoomout Mapview.
```

Thanks for supports!.

**Comment by zugaldia** [comment]
@Buminta Thank you for the report. This looks like another instance of https://github.com/mapbox/mapbox-gl-native/issues/5388.

**Comment by tobrun** [comment]
This is indeed a duplicate, closing this is favour of #5388
