### ISSUE TITLE
[linux] Overdraw mode crashes with GL_INVALID_OPERATION

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#5435]
Console output:
```
[ERROR] {mapbox-glfw}[OpenGL]: GL_DEBUG_SOURCE_API GL_DEBUG_TYPE_ERROR 1282 GL_DEBUG_SEVERITY_HIGH - GL_INVALID_OPERATION error generated. <location> is invalid.
terminate called after throwing an instance of 'mbgl::gl::Error'
  what():  glUniformMatrix4fv(location, 1, GL_FALSE, t.data()): Error GL_INVALID_OPERATION - ../../src/mbgl/shader/uniform.cpp:49
Aborted (core dumped)
```

Problem seems related to the location of uniforms from a shader using two quasi-identical programs. In macOS, it looks like those uniforms locations are the same, but it doesn't seem to be the case on Linux.

**Comment by mikemorris** [comment]
FWIW I was only seeing this error on `BUILDTYPE=Debug` Linux builds, and not on OS X at all.

**Comment by brunoabinader** [comment]
@mikemorris yep - macOS GL drivers appears to behave differently from others in that sense.
