### ISSUE TITLE
ViewMarkers show up in top left corner before moving to the correct location

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5439]
When you open a map containing View Markers, those markers show up in the top left of the screen before teleporting to the correct LatLng location. These should remain hidden until the first invalidation occurs.

**Comment by tobrun** [comment]
The issue visualised:
![ezgif com-video-to-gif 36](https://cloud.githubusercontent.com/assets/2151639/16294026/7b682710-391e-11e6-8ded-99ec24056ebc.gif)

**Comment by tobrun** [comment]
Solution:

![ezgif com-video-to-gif 37](https://cloud.githubusercontent.com/assets/2151639/16294169/73145a6a-391f-11e6-88a6-dd3d86e2f7ca.gif)

Since this is a one line fix and improves the UX a lot, I'm adding this to the `4.1.0` milestone.

cc @cammace @ivovandongen @zugaldia

**Comment by tobrun** [comment]
I'm adding the same fix for views that were panned out of the viewport and were prepared for reuse. I noticed some cases where we had some artifacts remaining from previous use and you were able to see it restoring to the correct state. Changing the View.GONE fixes this issue. Later on when we invalidate, we are changing this to View.VISIBLE.

**Comment by zugaldia** [comment]
Fixed via https://github.com/mapbox/mapbox-gl-native/pull/5447.
