### ISSUE TITLE
Symbols not loading

### ISSUE THREAD

**Issue by phelpsiv** [mapbox/mapbox-gl-native#5443]
**Platform: Android**
**Mapbox SDK version: 4.1.0-beta.3**
### Steps to trigger behavior
1. Load mapview
2. Load markers onto mapview

This occurred after upgrading from 4.0.1, but seems to persist after downgrading.
### Expected behavior

Map with path and markers displayed
### Actual behavior

This occurs with both online and offline maps. I've also tested with several map styles.
The map is displayed, as is the path, but any place there's a marker or symbol is a black box.
You can see in the background of the attached image (behind the progressdialog box) Three tall black rectangles in the place the markers are supposed to be located. the smaller rectangles are symbols for road direction and what I believe is a highway.

![screenshot_2016-06-22-11-22-36](https://cloud.githubusercontent.com/assets/4522589/16278507/17be692a-386c-11e6-86d4-7bfc60298d06.png)

**Comment by tobrun** [comment]
@phelpsiv thank you for reaching out, could you add the code how you are adding these markers?

**Comment by phelpsiv** [comment]
@toburn I actually got it to work again by falling back to version 4.0.1, don't know why it didn't work the last time I tried this. I'm adding markers to the map as follows:

```java
mapView.getMapAsync(new OnMapReadyCallback() {
    @Override
    public void onMapReady(MapboxMap mapboxMap) {
        map = mapboxMap;
        map.getUiSettings().setAttributionEnabled(false);
        map.getUiSettings().setAllGesturesEnabled(false);
        map.setMyLocationEnabled(true);

        // Add prompts as markers
        for (Marker m : prompts)
            map.addMarker(new MarkerOptions().position(new LatLng(m.getLat(), m.getLng())));
    }
}
```

To note in the code the variable `prompts` is a [realm](http://realm.io) object containing floating point lat and lng properties. Also, it seemed that no symbols were rendering (including symbols for highways or arrows for road directions). I did a test where I loaded the map without any markers and all symbols were appearing as black rectangles. My guess is it has something to do with how the 4.1.0 SDK is rendering symbols on the map, maybe it's trying to reference them at a wrong location?

**Comment by tobrun** [comment]
@zugaldia have you been seeing this behaviour anywhere?
@phelpsiv is this reproducible on more than 1 device? which device are you using for testing?

**Comment by zugaldia** [comment]
> @zugaldia have you been seeing this behaviour anywhere?

 I have not. I just tried to reproduce the issue, unsuccessfully.

@phelpsiv just to clarify, those black boxes aren't just the markers you added, you can't see either the standard Mapbox Streets symbols for POI, like a restaurant, right?

**Comment by phelpsiv** [comment]
@tobrun I'm testing on a few Samsung Galaxy Tab 4's all running Android 4.4.2, the issue appeared on all 4 tablets I installed the app on. 

@zugaldia that's correct all symbols on the maptiles show up as black boxes.

**Comment by zugaldia** [comment]
@phelpsiv thanks for clarifying.

I still can't reproduce the issue. I added Realm to our test app to see if we had some kind of incompatibility, but that doesn't seem to be it. I don't have a Samsung Galaxy Tab 4 at hand, could you check if the issue still appears in the emulator or in another device?

**Comment by phelpsiv** [comment]
Unfortunately I can't get my computer to run the emulator. One thing I realize I didn't  mention is that I'm caching maptiles for offline use using the offline manager. I'm caching the map on the apps landing page. A good chunk of Portland, Oregon is being cached from zoom 20-25.

Well, I ran a test where I removed the offline manager, and it didn't seem to have an impact. It might just be the tablets. I'll be able to see if I can get the emulator running on another computer tomorrow.

Thank you both for the help so far.

**Comment by phelpsiv** [comment]
Ok I tested this morning and it seems like it's likely an issue with the Samsung Galaxy tab 3 and 4. I have it running just fine in an emulator of a Nexus 7 on a mac.

Thanks again for all the help.

**Comment by zugaldia** [comment]
> Ok I tested this morning and it seems like it's an issue with the Samsung Galaxy tab 3 and 4

Thanks @phelpsiv for your help debugging it. This seems related to https://github.com/mapbox/mapbox-gl-native/issues/1649.

/cc: @kkaefer for his 👀 .

**Comment by cammace** [comment]
Hey @phelpsiv were you ever able to get this working correctly on the Samsung Galaxy tab 3 and 4? One thing you can try would be to upgrade to `4.2.0-beta.1` and see if the issues resolved. This version switches from using a texture view to a surface view (different renderer).

**Comment by phelpsiv** [comment]
@cammace I was hopeful, but the issue's still there. My I'm currently using 4.0.1, which has it's own bugs but I'm aware of them and have work arounds. I'm unfortunately too busy with other projects to dive in and look to see if I can find the bug myself, though I'd like to. If I can be of more help though please let me know.

**Comment by phelpsiv** [comment]
Just so you all know I'm pretty convinced this is a tablet specific issue. I just saw you're developer preview app in the play store, downloded it and it has the same issue as my app.

**Comment by dazza5000** [comment]
Experiencing this issue on a Samsung tablet running 4.4.2 on 4.2.0-beta.1. Has anyone found a solution to this?

**Comment by phelpsiv** [comment]
Unfortunately not to my knowledge, I had to fall back to 4.0.1. As a more permanent solution my group is getting different tablets. Let me know if you figure something out though!

**Comment by dazza5000** [comment]
Buying different tablets won't be a solution for us. We are building a consumer facing product and need to support 4.4 on smartphones and tablets.

**Comment by Emeritus-DarranKelinske** [comment]
Can we please get this labelled as a bug?

**Comment by phelpsiv** [comment]
I've got my app running on a new tablets with sdk version 4.2.2. The old tablet had the same issue. I'm thinking this has more to do with Android version than specific tablets. I have no issues with any device running Android 5.0 or newer. Anything running a version prior to Android 5.0 has the blacked out symbol issue. 

Worst case this issue will fix itself when people upgrade their devices, though I've recently seen some die hard Android Gingerbread users out in the wild.
