### ISSUE TITLE
(Android) Cancel or pause offlineRegion download.

### ISSUE THREAD

**Issue by vfaSonnt** [mapbox/mapbox-gl-native#5445]
I know many people ask for this feature but there is no answer. So I need to ask again.

In issue #5408 ,he suggest to stop offlineRegion on next one. 
I think he don't get the point. We want to stop/pause on current offlineRegion, not the next one. I only download 1 offline region, it took more than 3 minutes for 600 resources. If in the middle of downloading process, I press back to Android HomeScreen and launch app again. My activity can not start, it have to wait until previous offlineRegion finish download. This is a real problem because it freeze my app. My user can not use the app until downloading process finish.

I try these on onDestroy() function. But it is no help.
```
            mOfflineRegion.setDownloadState(OfflineRegion.STATE_INACTIVE);
            mOfflineRegion.setObserver(null);
            mOfflineRegion.delete(new OfflineRegion.OfflineRegionDeleteCallback() {
                @Override
                public void onDelete() {

                }

                @Override
                public void onError(String error) {

                }
            });
```

**Comment by jfirebaugh** [comment]
`mOfflineRegion.setDownloadState(OfflineRegion.STATE_INACTIVE);` is the correct way to pause the download of an offline region. Can you describe more precisely what is the issue you are having with it?

**Comment by zugaldia** [comment]
As @jfirebaugh points out above, `mOfflineRegion.setDownloadState(OfflineRegion.STATE_INACTIVE)` is a valid strategy to pause the region download in your activity. Are you getting any errors in the log that you could share with us? I'm curious if its async nature isn't working well with the Android lifecycle.

Another possible strategy that we see often in these situations is to use a `Service` to handle the download in the background. That way the download can continue even if the activity goes inactive, and it doesn't get affected by a new activity launch. In your particular use case, a simple [`IntentService`](https://developer.android.com/guide/components/services.html#ExtendingIntentService) should be able to do the trick.

**Comment by vfaSonnt** [comment]
Thank you! I use Service to handle Download.
