### ISSUE TITLE
[iOS]Cocoa pods spec for ios-v3.3.0 

### ISSUE THREAD

**Issue by andrewstay** [mapbox/mapbox-gl-native#5446]
Please update appropriate cocoapods spec so clients using cocoapods could install Mapbox-iOS-SDK v3.3.0

**Platform:** iOS
**Mapbox SDK version:** ios-v3.3.0

### Steps to trigger behavior

Try to install ios-v3.3.0 via cocoapods

### Expected behavior
Mapbox-iOS-SDK is successfully installed

### Actual behavior
Appropriate spec is not found in cocoapods DB. Mapbox-iOS-SDK is not installed.

**Comment by 1ec5** [comment]
Version 3.3.0 is still in beta. We’ll update the official CocoaPods.org repository when we publish the final release; at that point, you’ll automatically get the final release of version 3.3.0. In the meantime, you can point your client to either of these podspecs:

```podspec
# Without debug symbols
pod 'Mapbox-iOS-SDK', :podspec => 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/ios-v3.3.0-beta.1/platform/ios/Mapbox-iOS-SDK.podspec'
# With debug symbols
pod 'Mapbox-iOS-SDK', :podspec => 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/ios-v3.3.0-beta.1/platform/ios/Mapbox-iOS-SDK-symbols.podspec'
```

Please check [our Releases page](https://github.com/mapbox/mapbox-gl-native/releases/) regularly to find out about new betas, or use either of these podspecs to automatically update to the newest beta (will work until we release):

```podspec
# Without debug symbols
pod 'Mapbox-iOS-SDK', :podspec => 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/release-ios-v3.3.0/platform/ios/Mapbox-iOS-SDK.podspec'
# With debug symbols
pod 'Mapbox-iOS-SDK', :podspec => 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/release-ios-v3.3.0/platform/ios/Mapbox-iOS-SDK-symbols.podspec'
```



Thank you for your patience!

**Comment by andrewstay** [comment]
Great!
Thanks for pointing out.
