### ISSUE TITLE
No Bitcode in simulator removes bitcode in fat dynamic library

### ISSUE THREAD

**Issue by kenji21** [mapbox/mapbox-gl-native#5448]
**Platform:** iOS
**Mapbox SDK version:** master@3459b83736f0e4eedfb95a1394d9e4ee1523b917

### Steps to trigger behavior

 1. `git clone in /tmp`
 2. `export BITCODE=YES`
 3. `export BUILDTYPE=Release`
 4. `make iframework`
 5. `for file in $(ls ./build/ios/Build/Products/Release-*/*.a ./build/ios/Build/Products/Release-*/Mapbox.framework/Mapbox build/ios/pkg/dynamic/Mapbox.framework/Mapbox  ) ; do echo $file ; otool -l $file |grep __LLVM |uniq ; done`

### Expected behavior

Last command should show 'segname __LLVM' for each dependencies (.a / framework), like for libmbgl-core.a:

```
./build/ios/Build/Products/Release-iphonesimulator/libmbgl-core.a
   segname __LLVM
```

Grep comes from an apple member indications (https://forums.developer.apple.com/thread/3971) :

>Searching for a “bitcode” section is not a reliable way to detect if your files contain embedded bitcode. If you want to do that, search for the “__LLVM” segment. You should be aware that a normal build with the -fembed-bitcode-marker option will produce minimal size embedded bitcode sections without any real content. This is done as a way of testing the bitcode-related aspects of your build without slowing down the build process. The actual bitcode content is included when you do an Archive build.

### Actual behavior

````
$ for file in $(ls ./build/ios/Build/Products/Release-*/*.a ./build/ios/Build/Products/Release-*/Mapbox.framework/Mapbox build/ios/pkg/dynamic/Mapbox.framework/Mapbox  ) ; do echo $file ; otool -l $file |grep __LLVM |uniq ; done
./build/ios/Build/Products/Release-iphoneos/Mapbox.framework/Mapbox
  segname __LLVM
   segname __LLVM
  segname __LLVM
   segname __LLVM
./build/ios/Build/Products/Release-iphoneos/libmbgl-core.a
   segname __LLVM
./build/ios/Build/Products/Release-iphoneos/libmbgl-platform-ios.a
   segname __LLVM
./build/ios/Build/Products/Release-iphonesimulator/Mapbox.framework/Mapbox
./build/ios/Build/Products/Release-iphonesimulator/libmbgl-core.a
./build/ios/Build/Products/Release-iphonesimulator/libmbgl-platform-ios.a
build/ios/pkg/dynamic/Mapbox.framework/Mapbox
````

After forcing the -fembed-bitcode on the CFLAGS, and changing some compilation flags (CLANG_ENABLE_MODULES=NO, CLANG_ENABLE_MODULE_DEBUGGING=NO, GENERATE_MASTER_OBJECT_FILE=NO, GCC_PRECOMPILE_PREFIX_HEADER=NO, gathered from https://forums.developer.apple.com/message/64552, LINK_WITH_STANDARD_LIBRARIES=NO to avoid failure on 'ld: 
```
'/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a(arclite.o)' does not contain bitcode.'), compilation still fails, now showing the dependency that do not contains bitcode :

ld: '/tmp/mapbox-gl-native/mason_packages/ios-9.3/geojsonvt/4.1.2/lib/libgeojsonvt.a(convert.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture x86_64
```

**Comment by 1ec5** [comment]
Just to make sure I understand this bug report correctly: the fat binary contains the expected Bitcode-enabled content for the device, but you’re expecting it to also contain Bitcode-enabled content for the simulator as well, correct?

**Comment by kenji21** [comment]
Original issue is when sending an app to the App Store (having the build phase to remove the simulator slices) make app upload fail due to bitcode absent of Mapbox.framework.

**Comment by 1ec5** [comment]
`make iframework` produces a fat binary that contains slices for the simulator as well as the device. Simulator slices can’t be built with Bitcode support, because the x86_64 architecture doesn’t support it. (The iTunes Connect error could be clearer about this.) In our [installation instructions](https://www.mapbox.com/ios-sdk/#manual), one of the steps is to add a Run Script build phase that runs strip-frameworks.sh. That script strips the simulator slices when archiving.

If you add that build phase, archive, and resubmit, do you still get the same error?

**Comment by kenji21** [comment]
x86_64 architecture supports bitcode, checked with a internal library project (no issue with it):
````
otool -l MyLib/simulator/libMyLib-x64.a |grep __LLVM |uniq
   segname __LLVM
````

Also checked with openssl (compiled using https://gist.github.com/steipete/ce09ba176a4b8ef66b2d) :
````
$ file ./vendor/ios-openssl/lib/libssl_iOS.a
./vendor/ios-openssl/lib/libssl_iOS.a: Mach-O universal binary with 4 architectures
./vendor/ios-openssl/lib/libssl_iOS.a (for architecture armv7):	current ar archive random library
./vendor/ios-openssl/lib/libssl_iOS.a (for architecture i386):	current ar archive random library
./vendor/ios-openssl/lib/libssl_iOS.a (for architecture x86_64):	current ar archive random library
./vendor/ios-openssl/lib/libssl_iOS.a (for architecture arm64):	current ar archive random library

$ lipo -remove i386 ./vendor/ios-openssl/lib/libssl_iOS.a -output ./vendor/ios-openssl/lib/libssl_iOS-x64-v7-arm64.a
$ lipo -remove arm64 ./vendor/ios-openssl/lib/libssl_iOS-x64-v7-arm64.a -output ./vendor/ios-openssl/lib/libssl_iOS-x64-v7.a
$ lipo -remove armv7 ./vendor/ios-openssl/lib/libssl_iOS-x64-v7.a -output ./vendor/ios-openssl/lib/libssl_iOS-x64.a
$ lipo -info ./vendor/ios-openssl/lib/libssl_iOS-x64.a
Architectures in the fat file: ./vendor/ios-openssl/lib/libssl_iOS-x64.a are: x86_64
$ otool -l ./vendor/ios-openssl/lib/libssl_iOS-x64.a |grep __LLVM |uniq
   segname __LLVM
````

We have added the strip-frameworks.sh build phase, extracting the slice and checking like above can reveal the issue. We also use Carthage and no issue with libraries compiled with it.

**Comment by boundsj** [comment]
This should be fixed by https://github.com/mapbox/mapbox-gl-native/pull/5586 in the next beta or release candidate.
