### ISSUE TITLE
Change icon of a Marker when zoomlevel changes

### ISSUE THREAD

**Issue by guruduttstay** [mapbox/mapbox-gl-native#5451]
**Platform: Android**
**Mapbox SDK version:4.1.0-beta**
### Steps to trigger behavior
1. Allow setting/adding multiple Icons to Marker and allow setting to display it at certain zoom level.
2. For e.g. if added two Icons iconA, iconB then Display iconA from zoom level 1 to 9 and display iconB from Zoom level 9 to 21
3. Best would be allow adding different layers to map, all markers added to those layers and it should be possible to control those layers dynamically (e.g. show, hide layers based on Zoom level and other callbacks )
### Actual behavior

I found clustering but that's not what we want :(

Let me know if this is already possible. ... I didn't found it in code or doc yet

**Comment by tobrun** [comment]
@guruduttstay thank you for reaching out, what you are requesting is indeed support for z-layers. We are tracking this feature in #5238. With the `4.1.0-beta` we are exposing some support for z-ordering but not in a way that would solve your request in this issue. Closing as a duplicate with #5238.

**Comment by 1ec5** [comment]
This request is about varying a marker icon based on the zoom level, not about arranging multiple markers in z-space.

Once #837 is fully implemented in the SDK, it’ll be possible to do this with GeoJSON point features and potentially GL-rendered markers, but those changes alone won’t make it possible with marker views.

**Comment by tobrun** [comment]
@1ec5 thank you for the info on #837. I initially thought this part of the feature request was not something that the SDK would expose and that end developers would implement theirselves using OnCameraChangeListener. I'm going to change the title to make the request itself a bit more clear.

**Comment by tobrun** [comment]
@guruduttstay if urgent, you could try using the `OnCameraChangeListener` to determine changes in zoom level and update your markers accordingly. We currently don't expose an API to do this on large scale (using the concept of a layer) but the feature itself should be possible.

**Comment by guruduttstay** [comment]
@1ec5 thank you for reopening issue :)
@tobrun  it is kind of urgent ... this is one of the strongest feature in our App we want to implement in  MapBox :(

I will try OnCameraChangeListener and get back here if that solves our issue, I am concern about performance :)

**Comment by 1ec5** [comment]
Can you give us more details about the effect you're trying to achieve with zoom-dependent icons in marker views? For example, are you trying to have the icon's size vary? That information could help us decide on a better API, if any.

**Comment by guruduttstay** [comment]
Hi @1ec5 

Just recorded screen for current implementation :)
http://bit.ly/28XZPyi

For more info may be you can try Stay.com App from playstore or app store :)

**Comment by SylvainHocq** [comment]
I'm also interested by this feature.

**Comment by 1ec5** [comment]
Android SDK v4.2.0-beta.1 and iOS SDK v3.2.0-alpha.1 both have support for runtime styling. As long as the icons in question are baked into the style at design time (for example in Mapbox Studio), you can have symbol features transition between the icons based on zoom levels using a zoom function on the `iconImage` property.

Note that the runtime styling API only supports symbol features, not marker views (Android) or annotation views (iOS). At runtime, you can put point data inside a GeoJSON source and style it using a symbol layer. If you need this functionality for marker views or annotation views, please try the approach described in https://github.com/mapbox/mapbox-gl-native/issues/5451#issuecomment-228282926.

**Comment by cammace** [comment]
@guruduttstay and @SylvainHocq, like @1ec5 mentioned, runtime styling has been implemented in the Android SDK now which supports symbol layers. You might find [this example](https://github.com/mapbox/mapbox-android-demo/pull/173) particularly useful, along with the other many examples you can [find here](https://github.com/mapbox/mapbox-android-demo/tree/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles). Feel free to reach out through [our contact page](https://www.mapbox.com/contact/) if you guys have any additional questions on how to achieve this. Happy to help.
