### ISSUE TITLE
[iOS]How to update cocoaPods in this task????

### ISSUE THREAD

**Issue by ganjmeng** [mapbox/mapbox-gl-native#5454]
Help me!!!!  How to update cocoaPods in this task????where is the podfile??

![image](https://cloud.githubusercontent.com/assets/12026835/16299770/87ac2922-396e-11e6-84db-c9907f8d70fe.png)

**Comment by friedbunny** [comment]
That directory is not a CocoaPods project — it contains files that we use to generate our iOS framework. See our [First Steps guide](https://www.mapbox.com/help/first-steps-ios-sdk/) for how to create an Xcode project; or [follow these instructions](https://www.mapbox.com/ios-sdk/#cocoapods) if you need CocoaPods.
