### ISSUE TITLE
Set map boundaries / regions / bounding box to avoid moving outside boundaries 

### ISSUE THREAD

**Issue by guruduttstay** [mapbox/mapbox-gl-native#5455]
**Platform:Android**
**Mapbox SDK version:4.0.1**

### Steps to trigger behavior

We want to display city maps up to certain boundaries only, set those city boundaries with latitude and longitude (left, top,right,bottom) and do not allow pan/scroll over those boundaries and let user stay focused within those boundaries.

NB : Wish to offline maps within these boundaries as well :)

**Comment by tobrun** [comment]
@guruduttstay thank you for reaching out, this feature is being tracked in #3602. Closing as a duplicate.
