### ISSUE TITLE
crash when i build iOS dynamic framework with source code (iOS)

### ISSUE THREAD

**Issue by wangjinyu** [mapbox/mapbox-gl-native#5457]
I build the source code create dynamic framework on branch master.

follow is error info:

<img width="1270" alt="2016-06-23 20 28 10" src="https://cloud.githubusercontent.com/assets/3033623/16303281/6fdabac0-3982-11e6-98cc-7ca6b49f5c4e.png">

<img width="1087" alt="2016-06-23 20 28 19" src="https://cloud.githubusercontent.com/assets/3033623/16303291/7b7d57b6-3982-11e6-99f2-4b1ac76fd2ce.png">

<img width="1340" alt="2016-06-23 20 28 28" src="https://cloud.githubusercontent.com/assets/3033623/16303321/a05aa69c-3982-11e6-8e3b-e87e1942bb99.png">

Why?  

Who can help me.

**Comment by ChenJian345** [comment]
I met the same problem, Hope solve ASAP.

**Comment by ChenJian345** [comment]
I build the ios library according this guide. 
https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md

**Comment by friedbunny** [comment]
@wangjinyu Please provide more information about when and how you encountered this issue — including code that will reproduce it, if at all possible.

@ChenJian345 See [these instructions](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md) if you’re interested in **develop**ing and contributing to this project.

**Comment by wangjinyu** [comment]
@friedbunny I use the dynamic framework that build with source code on branch master.

When i addSubview on view.

![2016-06-24 11 05 21](https://cloud.githubusercontent.com/assets/3033623/16326792/431475b0-39fc-11e6-95a8-5d787003ce3c.png)

I only do this. I get the crash above.

**Comment by wangjinyu** [comment]
@friedbunny This is the framework i build.

[Mapbox.framework.zip](https://github.com/mapbox/mapbox-gl-native/files/331160/Mapbox.framework.zip)

**Comment by friedbunny** [comment]
@wangjinyu A few questions and one request:

1. What build command are you using to create the dynamic framework?
2. Have you successfully built it before?
3. Does the demo app (“iosapp”) in `make iproj` work for you?
4. Please post the build output here, after running `make clean && make distclean` and rebuilding.

**Comment by ChenJian345** [comment]
@friedbunny I use the `make iproj` command to start up the ios xcode project and build in the xcode.

Here is the output when I use `make clean && make distclean` command.
```
➜  mapbox-gl-native git:(release-ios-v3.2.2) make clean && make distclean
rm -f ~/Library/Application\ Support/Mapbox\ GL/cache.db
clearing files in ~/Library/Developer/Xcode/DerivedData/{mapboxgl-app,osxapp}-* older than one day
find: /Users/mark/Library/Developer/Xcode/DerivedData/mapboxgl-app-*: No such file or directory
find: /Users/mark/Library/Developer/Xcode/DerivedData/osxapp-*: No such file or directory
find ./deps/gyp -name "*.pyc" -exec rm {} \;
find ./build -type f -not -path '*/*.xcodeproj/*' -exec rm {} \;
rm -rf ./gyp/build/
rm -rf ./config/*.gypi
rm -rf ./platform/android/MapboxGLAndroidSDK/build \
	        ./platform/android/MapboxGLAndroidSDKTestApp/build \
	        ./platform/android/MapboxGLAndroidSDK/src/main/jniLibs \
	        ./platform/android/MapboxGLAndroidSDK/src/main/obj.target \
	        ./platform/android/MapboxGLAndroidSDK/src/main/assets
rm -f ~/Library/Application\ Support/Mapbox\ GL/cache.db
clearing files in ~/Library/Developer/Xcode/DerivedData/{mapboxgl-app,osxapp}-* older than one day
find: /Users/mark/Library/Developer/Xcode/DerivedData/mapboxgl-app-*: No such file or directory
find: /Users/mark/Library/Developer/Xcode/DerivedData/osxapp-*: No such file or directory
find ./deps/gyp -name "*.pyc" -exec rm {} \;
find ./build -type f -not -path '*/*.xcodeproj/*' -exec rm {} \;
rm -rf ./gyp/build/
rm -rf ./config/*.gypi
rm -rf ./platform/android/MapboxGLAndroidSDK/build \
	        ./platform/android/MapboxGLAndroidSDKTestApp/build \
	        ./platform/android/MapboxGLAndroidSDK/src/main/jniLibs \
	        ./platform/android/MapboxGLAndroidSDK/src/main/obj.target \
	        ./platform/android/MapboxGLAndroidSDK/src/main/assets
rm -rf ./mason_packages
```

**Comment by ChenJian345** [comment]
Anyone can help?

**Comment by ChenJian345** [comment]
2016-06-25 23:51:58.779 beastsbike[1564:809300] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x137cd42b0> to GL_RENDERBUFFER 1
2016-06-25 23:51:58.779 beastsbike[1564:809300] Failed to make complete framebuffer object 8cd6
2016-06-25 23:51:58.856 beastsbike[1564:809300] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x137d7f530> to GL_RENDERBUFFER 1
2016-06-25 23:51:58.857 beastsbike[1564:809300] Failed to make complete framebuffer object 8cd6
2016-06-25 23:51:58.907 beastsbike[1564:809300] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x137cd42b0> to GL_RENDERBUFFER 1
2016-06-25 23:51:58.907 beastsbike[1564:809300] Failed to make complete framebuffer object 8cd6
2016-06-25 23:51:58.967 beastsbike[1564:809300] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x137d7f530> to GL_RENDERBUFFER 1
2016-06-25 23:51:58.967 beastsbike[1564:809300] Failed to make complete framebuffer object 8cd6
libc++abi.dylib: terminating with uncaught exception of type mbgl::gl::Error: glStencilFunc(value.func, value.ref, value.mask): Error GL_INVALID_ENUM - ../include/mbgl/gl/gl_values.hpp:104

**Comment by kvurd** [comment]
The issue in the first post occurs for me too, but only if my `MGLMapView` has a `CGRect.zero` frame when added to a view. Perhaps try instantiating your `MGLMapView` with a non-zero frame.

**Comment by friedbunny** [comment]
Ah, sorry I missed [that](https://github.com/mapbox/mapbox-gl-native/issues/5457#issuecomment-228247894) — failing to `init` with `frame:CGRectZero` is a known issue (#1572).

**Comment by ChenJian345** [comment]
@friedbunny Yes, when will you fix it?
