### ISSUE TITLE
Can I catch MGLAnnotationImage what I created?

### ISSUE THREAD

**Issue by Paladinfeng** [mapbox/mapbox-gl-native#5463]
**Platform: iOS
**Mapbox SDK version: v3.3.0-beta1

**Comment by Paladinfeng** [comment]
I have another question, when i create a MGLMapView, and set scrollEnabled to no, i can't be penetrated

**Comment by 1ec5** [comment]
Regarding MGLAnnotationImage, are you asking whether there's a way to cache the MGLAnnotationImage? You can create an MGLAnnotationImage with a reuse identifier. In -[MGLMapViewDelegate mapView:imageForAnnotation:], you should first call -[MGLMapView dequeueReusableAnnotationImageWithIdentifier:] and return that value if it's non-null; then you only need to create a new MGLAnnotationImage if no image with that identifier could be dequeued.

Regarding scrollEnabled, what is the expected result and what is the behavior you're seeing instead?

**Comment by Paladinfeng** [comment]
I know how to use it, but when i creatd a MGLAnnotationImage over, can i find it using some method like [imageForAnnotation:annotation] ? it will returm me a MGLAnnotation

**Comment by Paladinfeng** [comment]
scrollEnabled, i mean, if i put a MGLMapView into a ScrollView, the MGLMapView doesn't affect the scrollView scrolling, u can see it in MKMapView

**Comment by 1ec5** [comment]
I suppose we could add an -imageForAnnotation: method to MGLMapView, but it's a low priority given that MGLAnnotationView has a richer API that probably meets your needs better anyways.

Can you open a separate bug about the scrolling issue, so we can keep the conversation clear? Thanks!

**Comment by Paladinfeng** [comment]
ok, thanks for asking my question, u could refer to MKMapView, it has a property named image, instead of using a special MGLAnnotationImage. Maybe mix MGLAnnotationImage and MGLAnnotationView is better. Sorry for my poor English

**Comment by 1ec5** [comment]
No problem! Good idea about adding `image` to MGLMapView; let’s track that in #5469.
