### ISSUE TITLE
FlushTheEventsTask borked

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#5470]
The latest 4.1.0-SNAPSHOT logs the following message:

```
06-24 18:38:39.462 21952-26026/co.human.android E/MapboxEventManager: FlushTheEventsTask borked: org.json.JSONException: Forbidden numeric value: NaN
06-24 18:38:39.463 21952-26026/co.human.android W/System.err: org.json.JSONException: Forbidden numeric value: NaN
06-24 18:38:39.505 21952-26026/co.human.android W/System.err:     at org.json.JSON.checkDouble(JSON.java:25)
06-24 18:38:39.506 21952-26026/co.human.android W/System.err:     at org.json.JSONObject.put(JSONObject.java:262)
06-24 18:38:39.507 21952-26026/co.human.android W/System.err:     at org.json.JSONObject.putOpt(JSONObject.java:276)
06-24 18:38:39.507 21952-26026/co.human.android W/System.err:     at com.mapbox.mapboxsdk.telemetry.MapboxEventManager$FlushTheEventsTask.doInBackground(MapboxEventManager.java:621)
06-24 18:38:39.507 21952-26026/co.human.android W/System.err:     at com.mapbox.mapboxsdk.telemetry.MapboxEventManager$FlushTheEventsTask.doInBackground(MapboxEventManager.java:585)
06-24 18:38:39.508 21952-26026/co.human.android W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
06-24 18:38:39.508 21952-26026/co.human.android W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-24 18:38:39.509 21952-26026/co.human.android W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
06-24 18:38:39.509 21952-26026/co.human.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-24 18:38:39.509 21952-26026/co.human.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-24 18:38:39.511 21952-26026/co.human.android W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

No crashes though.

**Comment by ivovandongen** [comment]
cc @zugaldia

**Comment by bleege** [comment]
Thanks for spotting this @ivovandongen.  This is a blocker to 4.1.0 Final.  I'll pick it up.

**Comment by bleege** [comment]
The code that matches up with the stacktrace points to `MapboxEventManager.java:621` is related to sending the event's latitude information in to the server (see code block below).  This data is generated from the stock Android [`Location.getLatitude()`](https://developer.android.com/reference/android/location/Location.html#getLatitude()).  According to the documentation if the Location is generated by the stock LocationManager there will always be "valid latitude".

The next step is to learn more about how the App in question is generating Location data as well as adding an explicit `NaN` check to Latitude and Longitude to keep the SDK from trying to send data like this.  The good news is that SDK behaved exactly as required in this situation in that it handled the error but did not crash the app.

```java
// Line 621
jsonObject.putOpt(MapboxEvent.KEY_LATITUDE, evt.get(MapboxEvent.KEY_LATITUDE));
```

![screen shot 2016-06-27 at 12 26 48 pm](https://cloud.githubusercontent.com/assets/989928/16389241/ab06fca2-3c62-11e6-9d8f-82e5572771fb.png)

**Comment by bleege** [comment]
I found out from @ivovandongen that the App generates Location data using the stock [Android Location API](https://developer.android.com/reference/android/location/package-summary.html), [Google Play Services Location API](https://developers.google.com/android/reference/com/google/android/gms/location/package-summary), and [Google Fit](https://developers.google.com/fit/android/).  This means that the data sources are going to be pretty reliable / consistent in terms of what is presented.  Since the crash itself actually occurred at the JSONObject level I added checks for `NaN` and `Infinite` values for latitude, longitude, and altitude during the Location Event processing to make the whole process more efficient.  The result is if any of those 3 values are `NaN` or `Infinite` then the Location event is ignored and not processed, thus keeping the JSONObject from having troubles [per it's documentation](https://developer.android.com/reference/org/json/JSONObject.html#put(java.lang.String,%20java.lang.Object)).

**Comment by bleege** [comment]
I just merged this into the `release-android-v4.1.0` branch and will now kick off a new SNAPSHOT so that we can make use of it sooner.

![screen shot 2016-06-27 at 2 11 39 pm](https://cloud.githubusercontent.com/assets/989928/16392364/2fde87d4-3c71-11e6-8a48-0bd2ec889fee.png)

**Comment by ivovandongen** [comment]
@bleege Just had another one. Is this merged back in master correctly?

```
07-15 18:07:09.770 18827-22372/com.mapbox.mapboxsdk.testapp E/MapboxEventManager: FlushTheEventsTask borked: org.json.JSONException: Forbidden numeric value: NaN
07-15 18:07:09.771 18827-22372/com.mapbox.mapboxsdk.testapp W/System.err: org.json.JSONException: Forbidden numeric value: NaN
07-15 18:07:09.771 18827-22372/com.mapbox.mapboxsdk.testapp W/System.err:     at org.json.JSON.checkDouble(JSON.java:25)
07-15 18:07:09.772 18827-22372/com.mapbox.mapboxsdk.testapp W/System.err:     at org.json.JSONObject.put(JSONObject.java:262)
07-15 18:07:09.772 18827-22372/com.mapbox.mapboxsdk.testapp W/System.err:     at org.json.JSONObject.putOpt(JSONObject.java:276)
07-15 18:07:09.772 18827-22372/com.mapbox.mapboxsdk.testapp W/System.err:     at com.mapbox.mapboxsdk.telemetry.MapboxEventManager$FlushTheEventsTask.doInBackground(MapboxEventManager.java:631)
07-15 18:07:09.773 18827-22372/com.mapbox.mapboxsdk.testapp W/System.err:     at com.mapbox.mapboxsdk.telemetry.MapboxEventManager$FlushTheEventsTask.doInBackground(MapboxEventManager.java:595)
07-15 18:07:09.774 18827-22372/com.mapbox.mapboxsdk.testapp W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
07-15 18:07:09.775 18827-22372/com.mapbox.mapboxsdk.testapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-15 18:07:09.775 18827-22372/com.mapbox.mapboxsdk.testapp W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
07-15 18:07:09.780 18827-22372/com.mapbox.mapboxsdk.testapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-15 18:07:09.781 18827-22372/com.mapbox.mapboxsdk.testapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-15 18:07:09.781 18827-22372/com.mapbox.mapboxsdk.testapp W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

**Comment by bleege** [comment]
@ivovandongen Which version of the SDK are you seeing this on?

**Comment by bleege** [comment]
Also #5682 found some extra NaN issues related to Gestures and is now in `master`.

**Comment by ivovandongen** [comment]
@bleege This was on master.

**Comment by bleege** [comment]
@ivovandongen Are you still experiencing this on `master` or have things smoothed out since #5682 was introduced?

**Comment by ivovandongen** [comment]
@bleege Haven't been on master recently or actively running the test-app. Will need to do that soon anyway to work on examples, I'll let you know.

**Comment by zugaldia** [comment]
We haven't seen this recently, closing. Feel free to reopen if the problem resurfaces.
