### ISSUE TITLE
Is there any way to get altitude for the center coordinate?

### ISSUE THREAD

**Issue by difficultashish** [mapbox/mapbox-gl-native#5471]
I am sure I can get the altitude of the user from CLLocation object inside MGLUserLocation. I was wondering if I can get it for any point on the map.

Thanks!

iOS SDK
v 3.2

**Comment by friedbunny** [comment]
You’ll need to use an external web API — such as [Mapbox’s Surface API](https://www.mapbox.com/developers/api/surface/) — if the point you want altitude for is not the current user location.
