### ISSUE TITLE
mmap failed errno 12 Out of memory

### ISSUE THREAD

**Issue by kingfisherphuoc** [mapbox/mapbox-gl-native#5478]
**Platform: Android**
**Mapbox SDK version:4.1.0-beta.3**

### Steps to trigger behavior

 1. Using below code to draw polylines :
<code>
private void drawRoute(LatLng... points) {

        PolylineOptions polylineOptions = new PolylineOptions()
                .add(points)
                .color(routeColor)
                .alpha(0.3f)
                .width(routeWidth);
        // Draw Points on MapView
        mapboxMap.addPolyline(polylineOptions);
        showLog("Draw routes list size: " + points.length);
} 
</code>
 2.  Clear the previous routes. Using routing and re-routing features which need to draw routes and re-draw routes many times in small amout of time (like 10 times in 1 minute)
 3. App crash after near 5 minutes.

### Expected behavior
App do not crash

### Actual behavior
App crashed with out of memory error:
> <sharedmem_gpumem_alloc_id:1554>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
><gsl_memory_alloc_pure:1576>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
>libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x2c in tid 7170

**Comment by zugaldia** [comment]
/cc: @jfirebaugh for your 👀, as per chat with @tmpsantos this might be something you've addressed recently.

**Comment by jfirebaugh** [comment]
Nothing comes immediately to mind. @kingfisherphuoc would you be able to provide a test application that demonstrates the issue -- perhaps a modification of the [default test app](https://github.com/mapbox/mapbox-gl-native/tree/61a5bea043e35e21a5d8eebf762d16bb9971fa0a/platform/android/MapboxGLAndroidSDKTestApp)?

**Comment by kingfisherphuoc** [comment]
I am trying to force it make it occur again in demo app. Please wait.

**Comment by kingfisherphuoc** [comment]
@jfirebaugh Please check the demo android application. I'm testing with "Lockito": `https://play.google.com/store/apps/details?id=fr.dvilleneuve.lockito` to mock up location:
###Step to trigger:
 1. Open "Lockito" to fake gps location: a long distance (my test case is 11km) with "Allow Mockup" in "developer" options.
 2. Start faking "Lockito" 
 3. Open the android sample app.
 4. Open "User tracking mode".
 5. Allow "Follow tracking" and "GPS bearing".
 6. wait a while (few minutes), app will crash with above error.

Note: I'm using version 4.1.0 release mapbox version. Device: Nexus 4, Android version 5.1.1

![device-2016-07-15-140319]
(https://cloud.githubusercontent.com/assets/962484/16866287/10e46a2e-4a95-11e6-8dc4-d7e40d169937.png)
![device-2016-07-15-140358](https://cloud.githubusercontent.com/assets/962484/16866377/bf89333e-4a95-11e6-8da8-ea1c497fb9b2.png)

**Comment by zugaldia** [comment]
@cammace could you help reproducing this issue using the Android demo app, as described by @kingfisherphuoc ?

**Comment by zugaldia** [comment]
@cammace Thanks for looking into this.

@kingfisherphuoc Thanks again for the report. Are you getting this crash on this device only, or are you seeing it on other devices? Is there any other code that you could share with us to reproduce this issue?

**Comment by kingfisherphuoc** [comment]
@cammace did you try to change the tilt of camera? If I do not change the camera tilt everything sees ok. However, if I change the tilt, the error occurs after few minutes (about 5,7 minutes).

**Comment by cammace** [comment]
Hey @kingfisherphuoc, I ran this test again using the `4.2.0-SNAPSHOT`, the code snippet I posted above, and the map tilted. after ~10 minutes of adding and then removing the line the app didn't crash and performance didn't deteriorate either. I then tested the user location tracking along a route and the app didn't crash either. Closing this issue for now, if you are still having issues using the SNAPSHOT feel free to reopen and provide any additional information describing your test environment so I can better troubleshoot this issue.
