### ISSUE TITLE
Offline routing / geocoding mapbox

### ISSUE THREAD

**Issue by raku** [mapbox/mapbox-gl-native#5481]
Is possible to use offline routing or geocoding in mapbox?

**Comment by 1ec5** [comment]
Routing and geocoding are handled by separate libraries, such as the [Mapbox Java SDK](https://github.com/mapbox/mapbox-java/) on Android and [MapboxGeocoder.swift](https://github.com/mapbox/MapboxGeocoder.swift/) and [MapboxDirections.swift](https://github.com/mapbox/MapboxDirections.swift/) on Apple platforms. However, with these libraries, you still need to make an HTTP request at the beginning of a route; from that point onward, you can use the returned route or geocoding results even after going offline. Fully offline routing and geocoding – in which no communication with the server is ever required – is currently unsupported by either of these libraries, and we don’t have a timetable for implementing it.

**Comment by mlgnnr** [comment]
@1ec5 any new information about this subject ?

**Comment by whisper-bye** [comment]
+1
route offline required

**Comment by 1ec5** [comment]
> I have the data what I needed, so It's possible create a route object by my self?

Yes: see https://github.com/mapbox/MapboxDirections.swift/issues/121#issuecomment-326526836.
