### ISSUE TITLE
Android build SDK source 'arm-v5' compile error

### ISSUE THREAD

**Issue by cbiao** [mapbox/mapbox-gl-native#5482]
Due to https://github.com/mapbox/mapbox-gl-native/issues/5401 and https://github.com/mapbox/mapbox-gl-native/issues/5402, I have to build android SDK source to change `invalidateViewMarkersInBounds` to show MarkerView. '**arm-v7**' and '**x86**' abis build success, but '**arm-v5**' build error:
> ```
CXX(target) Release/obj.target/core/src/mbgl/annotation/annotation_source.o
In file included from ../../src/mbgl/annotation/annotation_source.cpp:1:
In file included from ../../src/mbgl/annotation/annotation_source.hpp:4:
In file included from ../../src/mbgl/style/source_impl.hpp:7:
In file included from ../../src/mbgl/tile/tile.hpp:8:
../../src/mbgl/renderer/bucket.hpp:53:35: error: chosen constructor is explicit
      in copy-initialization
    util::Atomic<bool> uploaded = { false };
                                  ^~~~~~~~~
../../src/mbgl/util/atomic.hpp:19:14: note: constructor declared here
    explicit Atomic(const T& data_) : data(data_) {}
             ^
In file included from ../../src/mbgl/annotation/symbol_annotation_impl.cpp:2:
In file included from ../../src/mbgl/annotation/annotation_tile.hpp:3:
In file included from ../../src/mbgl/tile/geometry_tile.hpp:3:
In file included from ../../src/mbgl/tile/tile.hpp:8:
../../src/mbgl/renderer/bucket.hpp:53:35: error: chosen constructor is explicit
      in copy-initialization
    util::Atomic<bool> uploaded = { false };
                                  ^~~~~~~~~
../../src/mbgl/util/atomic.hpp:19:14: note: constructor declared here
    explicit Atomic(const T& data_) : data(data_) {}
             ^
1 error generated.
platform/android/core.target.mk:285: recipe for target 'Release/obj.target/core/src/mbgl/annotation/annotation_source.o' failed
make[1]: *** [Release/obj.target/core/src/mbgl/annotation/annotation_source.o] Error 1
make[1]: *** Waiting for unfinished jobs....
1 error generated.
platform/android/core.target.mk:285: recipe for target 'Release/obj.target/core/src/mbgl/annotation/symbol_annotation_impl.o' failed
make[1]: *** [Release/obj.target/core/src/mbgl/annotation/symbol_annotation_impl.o] Error 1
make[1]: Leaving directory '/home/ubuntu/mapbox-gl-native/build/android-arm-v5'
Makefile:187: recipe for target 'android-lib-arm-v5' failed
make: *** [android-lib-arm-v5] Error 2
```

Any help? Thank you!

**Comment by tobrun** [comment]
@cbiao 
which make command are you using?
which gradle configuration are to get armeabi?
 - ndk tag?
 - apk split?

**Comment by cbiao** [comment]
I follow the https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md, make command is `make android-lib-arm-v5` or `make apackage`. I'm new for this, am I doing right? No change to gradle configuration.

**Comment by tobrun** [comment]
@cbiao 
I can compile `make android-lib-arm-v5` locally from `release-android-4.1.0` without an issue.

Some follow up questions:
- Why do you need to have an arm-v5?
- Do you still have such a device?

As work around I would suggest building with `make apackage -j4 BUILDTYPE=Release` and [ABI splits](http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits#TOC-ABIs-Splits) method if you want generate different apk for different abi. You are intersted in the `armeabi` one since that is compatible with armv5.

**Comment by cbiao** [comment]
@tobrun 
If possible, could you please help build the android sdk source and share the .aar file (include all abis: _arm64-v8a, armeabi, armeabi-v7a, mips, x86, x86_64_) to me with below change, I really want add mapbox to my app, thank you so much!

> only change `public List<MarkerView> getMarkerViewsInBounds(@NonNull LatLngBounds bbox)` method of **MapView.java** from:


```
public List<MarkerView> getMarkerViewsInBounds(@NonNull LatLngBounds bbox) {
        if (mDestroyed || bbox == null) {
            return new ArrayList<>();
        }

        // TODO: filter in JNI using C++ parameter to getAnnotationsInBounds
        long[] ids = mNativeMapView.getAnnotationsInBounds(bbox);

        List<Long> idsList = new ArrayList<>(ids.length);
        for (int i = 0; i < ids.length; i++) {
            idsList.add(ids[i]);
        }

        List<MarkerView> annotations = new ArrayList<>(ids.length);
        List<Annotation> annotationList = mMapboxMap.getAnnotations();
        int count = annotationList.size();
        for (int i = 0; i < count; i++) {
            Annotation annotation = annotationList.get(i);
            if (annotation instanceof MarkerView && idsList.contains(annotation.getId())) {
                annotations.add((MarkerView) annotation);
            }
        }

        return new ArrayList<>(annotations);
    }
```

to

```
public List<MarkerView> getMarkerViewsInBounds(@NonNull LatLngBounds bbox) {
        if (mDestroyed || bbox == null) {
            return new ArrayList<>();
        }

        List<MarkerView> annotations = new ArrayList<>();
        List<Annotation> annotationList = mMapboxMap.getAnnotations();
        int count = annotationList.size();
        for (int i = 0; i < count; i++) {
            Annotation annotation = annotationList.get(i);
            if (annotation instanceof MarkerView) {
                annotations.add((MarkerView) annotation);
            }
        }

        return new ArrayList<>(annotations);
    }
```

 I truly appreciate it!
