### ISSUE TITLE
Open GeoJSON

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5483]
In macosapp, it should be possible to go to File ‣ Open and select a GeoJSON file to open the GeoJSON in a new map window. If macosapp registers as a viewer for GeoJSON files, you’d also be able to open GeoJSON from the command line via the `open` command. This would address one of the use cases for [Geojson.app](https://github.com/mick/geojsonapp).

Blocked by #837, specifically hooking up the runtime source API added in #5368 to the macOS SDK.

/cc @mick

**Comment by tmpsantos** [comment]
You can get this one almost for free like we did on the Qt port:

https://github.com/mapbox/mapbox-gl-native/blob/cc3a81291a124db9e1dd6921616869631863ab61/platform/qt/src/qt_geojson.hpp

This currently works on Qt:
```
QFile geojson("source.geojson");
geojson.open(QIODevice::ReadOnly);

QVariantMap testSource;
testSource["type"] = "geojson";
testSource["data"] = geojson.readAll();

map.addSource("testSource", testSource);
```

The API was originally designed for setting a data structure as "data", this came a bit by accident but tuned out to be useful. The original intent is going to be implement but we are probably going to keep accepting raw geojson as an option.

**Comment by 1ec5** [comment]
Now blocked by #5626.

**Comment by 1ec5** [comment]
No longer blocked.
