### ISSUE TITLE
Pass custom parameters to styleURL

### ISSUE THREAD

**Issue by ambientlight** [mapbox/mapbox-gl-native#5485]
I need to integrate the Bing Maps datasource into the styleURL, however instead of /z/x/y.png it uses quadKey indexing, where quadKey can be defined as:

```javascript
_quadKey: function (x, y, z) {
    var quadKey = [];
    for (var i = z; i > 0; i--) {
        var digit = '0';
        var mask = 1 << (i - 1);
        if ((x & mask) != 0) {
            digit++;
        }
        if ((y & mask) != 0) {
            digit++;
            digit++;
        }
        quadKey.push(digit);
    }
    return quadKey.join('');
}
```

How can I make the styleURL eat a custom parameter in iOS and Android SDK? say for example something like:
`https://somedatasource.com/{quadKey}.png`

**Comment by 1ec5** [comment]
The `styleURL` property takes a URL to a [Mapbox GL stylesheet](https://www.mapbox.com/mapbox-gl-style-spec/), not a tile URL template. It is possible to craft a stylesheet that [includes a raster tile layer](https://www.mapbox.com/ios-sdk/examples/raster-styles/), but raster tile layers currently only support a limited set of tokens such as `{x}`, `{y}`, and `{z}`. There’s no API for extending that tokenization – the relevant code lives deep down in [src/mbgl/util/mapbox.cpp](https://github.com/mapbox/mapbox-gl-native/blob/b8326870e1f3960b169746b0473326060bb6cf54/src/mbgl/util/mapbox.cpp).

**Comment by ambientlight** [comment]
@1ec5 Thank you.

Ok I guess I therefore need to setup the apache server with request redirecting...

**Comment by 1ec5** [comment]
mapbox/mapbox-gl-js#2805 proposes adding support for `{quadkey}` specifically in Mapbox GL JS. I don’t know whether or not that’s the right approach, but the equivalent code in the mapbox-gl-native codebase would be located in [`Resource::tile()`](https://github.com/mapbox/mapbox-gl-native/blob/021d4199cb9ee754e9f0f5bc42f7f75285afd405/src/mbgl/storage/resource.cpp#L60).

**Comment by 1ec5** [comment]
#5628 implements `{quadkey}` support in tile URLs, as requested.
