### ISSUE TITLE
crashed when I init a MapView

### ISSUE THREAD

**Issue by Paladinfeng** [mapbox/mapbox-gl-native#5486]
**Platform: iOS 7
**Mapbox SDK version: v3.3.0-beta2

-  ##Is it not support iOS7 at beta version?

**Comment by 1ec5** [comment]
Please provide the stack trace of the crash and indicate how you set up the SDK (static, dynamic, or Fabric; Objective-C, Swift, or Interface Builder). Thanks!

**Comment by Paladinfeng** [comment]
I use static SDK, coding by Objective-C, release SDK-v3.2.3 is ok

**Comment by Paladinfeng** [comment]
![image](https://cloud.githubusercontent.com/assets/15520106/16377153/f6e07c5a-3c96-11e6-9fa6-24af3cdade46.png)

**Comment by 1ec5** [comment]
The stack trace indicates a crash getting the image for the compass button. Based on previous reports we've gotten with this stack trace, I'm assuming the SDK is unable to find the resource bundle. Make sure Mapbox.bundle is in your project and that your application target has a Copy Files build phase that includes the bundle, and let us know whether that fixes the issue.

**Comment by Paladinfeng** [comment]
Sorry, it doesn't work. I'm sure that Mapbox.bundle is in your project. Mapbox's logo was shown. defaultAnnotationImage was ok. it's all works at v3.2.3. Did u setting special at release version?

**Comment by 1ec5** [comment]
What appears in the console at the time of the crash? (You may need to disable breakpoints in order to see the exception message in the console.)

**Comment by friedbunny** [comment]
If Xcode paused at the crash and you’re able to interact with the console, typing `bt` (or `bt all`) will get you a backtrace of the crash.

**Comment by 1ec5** [comment]
I'm pretty sure `bt` will print out the same thing as the screenshot above. 😉

@Paladinfeng, can you go to the Build Phases tab of the project editor and take a screenshot of the copy files and compile sources phase? Sometimes Xcode puts the bundle in the wrong phase.

**Comment by Paladinfeng** [comment]
![image](https://cloud.githubusercontent.com/assets/15520106/16402370/a575fc7c-3d1e-11e6-87a7-3d77deca2add.png)
That's all about Mapbox

**Comment by 1ec5** [comment]
#5497 has a fix for this crash.

Thanks for your patience @Paladinfeng. Often this method is where the SDK crashes due to missing resources, but you found a real bug in the same method. In the future, instead of taking a screenshot of Xcode’s Debug navigator, hold down Shift and select all the rows in that table view, then copy-paste them into your browser. That way, we can see specifically which line contains the crashing code.

**Comment by friedbunny** [comment]
Fixed by #5497 in the `release-ios-v3.3.0` branch, which will eventually make its way back to `master`.

**Comment by wanggang316** [comment]
@1ec5 When release next version include this fixed issue?

**Comment by 1ec5** [comment]
Yes, the next v3.3.0 beta or release candidate will have the fix, and so will the final release.
