### ISSUE TITLE
Same size in memory for different MGLOfflineRegions.

### ISSUE THREAD

**Issue by Gurbo** [mapbox/mapbox-gl-native#5487]
**Platform:** ios 9.3
**Mapbox SDK version:** 3.3

Everytime when i try to download offline pack - it is the same size and doesn't depends on coordinates i pass to the MGLOfflineRegion creating method, doesn't depends on max/min zoom level. For example:  sw = (latitude = -26.236137332675895, longitude = 28.011853889607568)
 ne = (latitude = -26.172545749728137, longitude = 28.08272393243562)
min zoomlevel = 17, maxzoom level 18. And the result is - 69.9 MB, 1284 resources. Why such a small region is so big in memory?

**Comment by jfirebaugh** [comment]
Offline packs contain not only tiles but other resources such as font data, which contributes to the size of small regions. The 69.9 MB number is the total size for the region including all resources. However, many of these resources will be shared between regions in the event that you create more than one.

**Comment by Gurbo** [comment]
@jfirebaugh can you answer me - is it okay size (about 70mb) for a small region on map with only 1 step of zoom?

**Comment by jfirebaugh** [comment]
Yes, 60-70 MB is approximately the overhead for the first offline region regardless of the size of the region, due to font glyphs. If you create a second region for the same style, that 60-70 MB will be reused, and the new region will download only the new tiles. #4069 details future plans for reducing the glyph overhead for the first region.

**Comment by Gurbo** [comment]
@jfirebaugh " If you create a second region for the same style, that 60-70 MB will be reused, and the new region will download only the new tiles." hi! unfortunately i have the same issue: every time the same size of region - 69.9mb (not only at the first time). And then - [WARNING] {DefaultFileSource}[Database]: Unable to make space for entry
