### ISSUE TITLE
Add Non English Language Example To Test App

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#5493]
The world is a big place with many different languages spoken.  We should better highlight (and have an automated test) that the Mapbox Android SDK supports different languages both at the Core GL and with the View based levels.  While RTL support hasn't landed (yet) #5072 we can certainly show an example that uses a language like French, Spanish, or German to illustrate how this would work.

As we discussed internally this morning, this would also be a great example to port to the [Mapbox Android Demo app](https://github.com/mapbox/mapbox-android-demo).

/cc @zugaldia @cammace

**Comment by 1ec5** [comment]
Would this use the same approach as [this GL JS example](https://www.mapbox.com/mapbox-gl-js/example/language-switch/) (which requires #837), or would it use a separate Mapbox Studio style for now?

**Comment by tmpsantos** [comment]
:hand: volunteer for portuguese translation, just ping me.

**Comment by 1ec5** [comment]
I _think_ this ticket is about map localization. [Mapbox Streets source](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#overview) unfortunately doesn't include Portuguese names outside of Portuguese-speaking areas.

**Comment by tmpsantos** [comment]
@1ec5 oh, I took it as for translating the app itself. My bad.

**Comment by cammace** [comment]
This is an example that is better suited for the [Android demo app](https://github.com/mapbox/mapbox-android-demo). Here's the example I've built:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5652865/17370116/cebe01a4-5968-11e6-86d2-acc846019a07.gif)

Note that the tiles aren't refreshing currently like they should be, [ticketed here](https://github.com/mapbox/mapbox-gl-native/issues/5701). Closing issue.

**Comment by bleege** [comment]
> the Mapbox Android SDK supports different languages both at the Core GL and with the View based levels. 

I'm re-opening this as it's still missing the View based level examples (thinking InfoWindows).  It's also something that we can add unit tests to be more complete and help minimize regressions.

**Comment by cammace** [comment]
Different languages at the view based levels are controlled by Android, not Mapbox therefore adding more to the example would only complicate things instead of keeping it simple. The example found in the demo app is adequate enough for testing and demoing that we support this.
