### ISSUE TITLE
Release Android 4.1.0 Final

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#5510]
Mapbox Android 4.1.0 builds off our ambitious [`4.0.0` version](https://github.com/mapbox/mapbox-gl-native/issues/4535) with 3 major new features being released.  These new features are part of our ongoing efforts focused on providing a premiere navigation experience in-car, on-dash, and on the street for Android.

To help us produce the highest quality SDK possible we've previously released a series of 3 Beta versions and incorporated feedback from the community.  For more information about these Betas please see the links below:

* `4.1.0-beta.1` was released on 26-May-2016 in #5160 
* `4.1.0-beta.2` was released on 8-June-2016 in #5284 
* `4.1.0-beta.3` was released on 20-June-2016 in #5415

#### Mapbox for Android 4.1.0 Highlights

* [View Based Annotations](https://github.com/mapbox/mapbox-gl-native/issues/3276)
* [UserLocationView Refactor](https://github.com/mapbox/mapbox-gl-native/issues/4396)
* [MapboxAccountManager](https://github.com/mapbox/mapbox-gl-native/issues/5004)

Full Change Log: https://github.com/mapbox/mapbox-gl-native/issues?q=milestone%3Aandroid-v4.1.0

Release Branch: https://github.com/mapbox/mapbox-gl-native/commits/release-android-v4.1.0

#### The TODO list for making this happen:

- [x] Change Version Name to `4.1.0` in [`gradle.properties`](https://github.com/mapbox/mapbox-gl-native/blob/925687ab06892528f25fd4a79d27a55560634d96/platform/android/MapboxGLAndroidSDK/gradle.properties#L2)
- [x] Update version info in [Twitter Fabric metadata file](https://github.com/mapbox/mapbox-gl-native/blob/925687ab06892528f25fd4a79d27a55560634d96/platform/android/MapboxGLAndroidSDK/src/main/resources/fabric/com.mapbox.mapboxsdk.mapbox-android-sdk.properties#L2)
- [x] Publish `4.1.0` artifact to Maven Central
- [x] Updating Mapbox.com JavaDoc Documentation
- [x] Update [CHANGELOG.md](https://github.com/mapbox/mapbox-gl-native/blob/master/CHANGELOG.md)
- [x] Tag `android-v4.1.0` in GitHub
- [x] Close Milestone `android-v4.0.0` in GitHub
- [x] Blog Post on https://www.mapbox.com/blog/
- [ ] Alert Twitter Fabric team of new release
- [x] Tweet Release Announcement from `@mapbox`
- [x]  Merge `release-android-v4.1.0` back into `master`
- [x] Change Version Name _BACK to SNAPSHOT after release and release branch merge_ to support daily development.  In this case set to  `4.2.0-SNAPSHOT` in [`gradle.properties`](https://github.com/mapbox/mapbox-gl-native/blob/925687ab06892528f25fd4a79d27a55560634d96/platform/android/MapboxGLAndroidSDK/gradle.properties#L2)
- [x] Update [Mapbox Demo App](https://github.com/mapbox/mapbox-android-demo) to use `4.1.0` and release on Google Play

/cc @mapbox/mobile @mapbox/support @mapbox/sales @mapbox/communications

**Comment by bleege** [comment]
The SDK has been built, uploaded, and published on Maven Central.  It should be live to the world within an hour.

**Comment by bleege** [comment]
Mapbox Android 4.1.0 is now live on Maven Central!

https://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-sdk/4.1.0/

**Comment by bleege** [comment]
Tagged --> https://github.com/mapbox/mapbox-gl-native/commits/android-v4.1.0

**Comment by cammace** [comment]
Blog post is live: https://www.mapbox.com/blog/android-4.1.0/

**Comment by jfirebaugh** [comment]
🎉

**Comment by bleege** [comment]
I've alerted the team at Twitter Fabric about the new version and have asked them for some help to update the version on Fabric.  Will report back more when I hear from them.

**Comment by bleege** [comment]
@cammace alerted the Twitter masses via --> https://twitter.com/Mapbox/status/748227139355447297

**Comment by bleege** [comment]
The Demo App has been update and published on Google Play.  Details are found --> https://github.com/mapbox/mapbox-android-demo/pull/97

**Comment by bleege** [comment]
All that remains of the release at this time is for Twitter to update the plugin in Fabric and for PR #5512 to merge.

**Comment by bleege** [comment]
PR #5512 has landed, the release branch has now been deleted, and the Nightly SNAPSHOT CI process is now running off of `master` per usual again.  I've also emailed the team at Twitter to approve the release of the new version on Fabric (per their process).  In other words, everything that Mapbox can control in this release is officially complete!  🎉 

Great job everybody!

**Comment by bleege** [comment]
The team at Twitter just emailed me to let us know that Mapbox Android 4.1.0 is now live on Twitter Fabric.  Things are now 💯 done.
