### ISSUE TITLE
Marker view ignoring anchor when maps first created

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5513]
When the map is first created with a marker view, it ignores the anchor if set, shown in the GIF are two examples both using the anchor. Code for both can be found in the [demo app](github.com/mapbox/mapbox-android-demo). 

![ezgif com-video-to-gif 3](https://cloud.githubusercontent.com/assets/5652865/16465439/b44127ce-3e0c-11e6-8ab9-211a1e04f564.gif)

cc: @tobrun @zugaldia @bleege @ivovandongen

**Comment by tobrun** [comment]
Visualisation of the issue:

![device-2016-07-07-102812](https://cloud.githubusercontent.com/assets/2151639/16647222/77bd60b0-442e-11e6-85ac-d29b85cbd7a4.png)

**Comment by tobrun** [comment]
after fix the gl and view marker overlap:

![device-2016-07-07-104738](https://cloud.githubusercontent.com/assets/2151639/16647599/466f8b4e-4430-11e6-921b-ba1407a7b375.png)

**Comment by tobrun** [comment]
The issue came from the view not being measured first when determining the anchoring offset
