### ISSUE TITLE
Draw routes with directions (polylines with arrow icons)

### ISSUE THREAD

**Issue by kingfisherphuoc** [mapbox/mapbox-gl-native#5515]
**Platform: Android**
**Mapbox SDK version: 4.1.0 final**

### Steps to trigger behavior

 1. Get routes via routing api

 2. Draw routes as:<br>
<code>
 PolylineOptions polylineOptions = new PolylineOptions()
.add(points)
.color(routeColor)
.alpha(0.8f)
.width(routeWidth);
mapboxMap.addPolyline(polylineOptions);
</code>

### Expected feature
Is there any way to draw route (line) with direction in each line? As an arrow Icon?

### Images:

This is the current routes:
<img width="288" alt="screen shot 2016-06-30 at 2 51 15 pm" src="https://cloud.githubusercontent.com/assets/962484/16480820/74a039cc-3ed2-11e6-94bc-5969f034e1ac.png">

This is the expected routes:
![route_sign_road_direction-512](https://cloud.githubusercontent.com/assets/962484/16480878/b9a32dfe-3ed2-11e6-8f81-58db4af0683f.png)

**Comment by 1ec5** [comment]
You’d have to draw the arrow as a separate marker.

**Comment by tobrun** [comment]
@kingfisherphuoc: at this time we are not thinking about exposing this as an API (@1ec5 please correct me if I'm wrong on this). Were you able to resolve this using markers as @1ec5 suggested?

**Comment by 1ec5** [comment]
Also, it’s worth noting that, once #837 lands in a future release, it’ll be possible to add the route line using GeoJSON; you’d add the arrows as a symbol layer with [`symbol-placement: line`](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-symbol-placement) and [`icon-image`](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-icon-image).
