### ISSUE TITLE
How to build a framework that iOS7 can use

### ISSUE THREAD

**Issue by Paladinfeng** [mapbox/mapbox-gl-native#5516]
**Platform: iOS
**Mapbox SDK version: ios-3.3.0

We have no time wating for your v3.3.0-beta3. So, We decide to get framework from the project. But, I can only get dynamic. How to build a framework that iOS7 can use? 

![image](https://cloud.githubusercontent.com/assets/15520106/16481471/0421f80a-3ede-11e6-8d62-76d48eff52b0.png)

**Comment by friedbunny** [comment]
Please read the [packaging section](https://github.com/mapbox/mapbox-gl-native/blob/ad081e698a463ed943327ee6a4457f92e9434dd1/platform/ios/DEVELOPING.md#packaging-builds) of the development instructions. The `make ipackage` command will do what you want, but there are several other options available that you may be interested in.
