### ISSUE TITLE
Annotation text is completely invisible

### ISSUE THREAD

**Issue by lyptt** [mapbox/mapbox-gl-native#5519]
With a completely barebones Android Mapbox v4.1.0 integration we're seeing that all of the text that Mapbox renders is white, causing issues with annotations and the attributions views.

Is there a way of making the text be dark instead? See screenshot for one example (the annotation has text, but you can't see it)

![screen shot 2016-06-30 at 15 27 46](https://cloud.githubusercontent.com/assets/346710/16491870/7f60b6f2-3ed7-11e6-83ed-6bce28fdd264.png)

**Comment by tobrun** [comment]
@lyptt thank you for reaching out but we don't explicitly set the text color of the textview of an InfoWindow. My guess is that this comes from the theme you are using in your application. For now I would advice you to override the default style of your theme or apply a different theme for the Activity hosting your MapView. Reach out if you have any other questions!

**Comment by lyptt** [comment]
Yeah I've just noticed that myself. Turned out to be some strange caching issue - reinstalling the app solved it. Thanks for the response!
