### ISSUE TITLE
Feature parity on Android with iOS

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#552]
Need to catch up to features in the iOS map.

- [x] make list of iOS features
 - [x] make list of MGLMapView methods and properties
- [x] work out what is missing in Android
 - [x] compare methods and properties
- [ ] add missing features
 - [ ] add methods and properties

**Comment by jfirebaugh** [comment]
Closing here; this is old and should be covered in individual tickets.
