### ISSUE TITLE
User dot should show minimal heading indicator outside of tracking mode

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5523]
Per https://github.com/mapbox/mapbox-gl-native/issues/3718#issuecomment-229624719, it would be useful, either as an option or by default, for the user dot to show a heading indicator when user tracking mode is not enabled. The indicator should be minimal, much less obvious than the “flashlight” during heading tracking. On iOS 10, Apple Maps appears to be doing something like this already:

![heading-arrow](https://cloud.githubusercontent.com/assets/1231218/16500003/92695cce-3eb7-11e6-9238-f1ab7d213197.jpg)

This is also how Google Maps’s heading indicator always looks.

/cc @friedbunny @bsudekum

**Comment by 1ec5** [comment]
Until #5037 is implemented, the workaround would involve maintaining a custom annotation view and repositioning it every time `-[MGLMapViewDelegate mapView:didUpdateUserLocation:]` is called.

**Comment by friedbunny** [comment]
We currently pause heading updates when the user tracking mode is not `.FollowWithHeading`. 

We’ll need to expose a setting that allows a developer to override this behavior, something like `MGLMapView.alwaysUpdateHeading = YES`.

**Comment by friedbunny** [comment]
Done in #9886 — will be in v3.6.3.
