### ISSUE TITLE
Archive for iTunes Connect fails with `./Mapbox.framework/Mapbox' was built without full bitcode`

### ISSUE THREAD

**Issue by roblabs** [mapbox/mapbox-gl-native#5526]
Attempting to build Mapbox iOS 3.3.0 for sending app out for TestFlight, then to customers on the App Store.

I am receiving the below error regarding 'not built with full bitcode'.  Our last App Store build was 3.2.2 and `make ipackage` worked without any flags.  Now we are seeing the issue, and the flag `BITCODE=YES` does not solve anything.

Any suggestions or workarounds?  We have bitcode on in our app, and we prefer to have bitcode on [due to its advantages from Apple](https://developer.apple.com/library/prerelease/content/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html#//apple_ref/doc/uid/TP40012582-CH35-SW2). 

Issue looks similar to #5448.  

*Platform: iOS*
*Mapbox SDK version: 3.3.0*
*SHA = 5389f04da5f66c5e26d71e761a0fcda4d8382581*
*Xcode Version 7.3.1 (7D1014)*

### Steps to trigger behavior

 1. `make clean`
 2. [Make with BITCODE=YES](https://github.com/mapbox/mapbox-gl-native/blob/bc24da11b27b6e180ab1716e57caa751eb4f5f00/Makefile#L154)
 3. `make ipackage BITCODE=YES`
 4.  copy `mapbox-gl-native/build/ios/pkg/dynamic` to my project
 5.  From Xcode for my target, `Product` > `Archive`

### Expected behavior
Happy Archive, ready for iTunes Connect and the App Store

### Actual behavior
Archive failed with this error

```
ld: bitcode bundle could not be generated because '/Users/me/bitbucket/project/Mapbox.framework/Mapbox' was built without full bitcode. 
All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by 1ec5** [comment]
`make ipackage` produces a fat binary that contains slices for the simulator as well as the device. Simulator slices can’t be built with Bitcode support, because the x86_64 architecture doesn’t support it. In our [installation instructions](https://www.mapbox.com/ios-sdk/#manual), one of the steps is to add a Run Script build phase that runs strip-frameworks.sh. That script strips the simulator slices when archiving.

If you add that build phase, archive, and resubmit, do you still get the same error?

**Comment by roblabs** [comment]
Yes, the above was using strip-frameworks.sh.

`make ipackage` is part of my release to App Store process, so things have been working since releasing with Mapbox 3.2.1 & 3.2.2 builds.  That is 3 months of product releases on the App Store with strip-frameworks working as expected.

I've also tried `make iframework BITCODE=YES`, with no luck.

**Comment by 1ec5** [comment]
Have you always had to pass in `BITCODE=YES` as part of your build process? [platform/ios/scripts/package.sh](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/scripts/package.sh) used to recognize the `BITCODE` flag as a way to support building _without_ Bitcode. All it did was set the `ENABLE_BITCODE` compiler flag when invoking `xcodebuild`. In f791eb32b9ebe96845e87e5a6acd3ee46182c1d5 for #4641, we streamlined package.sh by removing the `BITCODE` override. `ENABLE_BITCODE=YES` should be set in the Xcode projects anyways; is this not the case?

**Comment by roblabs** [comment]
Our build process has only used `make ipackage` since Mapbox 3.2.1.  The `BITCODE=YES` is my attempt get around the today's Archive issue.

I did search in `platform/ios/ios.xcworkspace` and found that the KIF project has `ENABLE_BITCODE=NO`.  That is the only reference to bitcode in the workspace.  I apologize, I don't know what KIF does.

Could that be the problem?

![kif-enable_bitcode](https://cloud.githubusercontent.com/assets/118112/16507583/b2d003aa-3edf-11e6-9d13-1b4bdfc2e302.png)

**Comment by 1ec5** [comment]
That’s unlikely, because KIF is only included in the UI test bundle, not the dynamic or static framework targets.

**Comment by boundsj** [comment]
This should be fixed by https://github.com/mapbox/mapbox-gl-native/pull/5586 in the next beta or release candidate.
