### ISSUE TITLE
Rotation doesn't work on Android when map is not full screen

### ISSUE THREAD

**Issue by dapetcu21** [mapbox/mapbox-gl-native#5528]
From my debugging, `RotateGestureDetector` doesn't seem to detect any gesture (`onRotateBegin` never gets called).

The issue is in `TwoFingerGestureDetector.getRawX()`. See my comment below.

**Platform:** Android - Samsung Galaxy S5
**Mapbox SDK version:** 4.1.0

### Steps to trigger behavior

 1. Position MapView in the bottom half of the screen
 2. Run app

### Expected behavior

MapView should rotate when rotating 2 pinched fingers on the screen

### Actual behavior

MapView just zooms with no rotation

**Comment by danswick** [comment]
Thanks for the report, @dapetcu21. Rotation should be enabled by default. Can you test without setting `uiSettings.isRotateGesturesEnabled(true)` and report back with your findings? If you test out this [example](https://www.mapbox.com/android-sdk/examples/), does rotation work?

**Comment by dapetcu21** [comment]
Off the bat, the example wouldn't start, as `MapboxAccountManager.start()` would only get called after the `MapView` got initialized. I solved this by moving `start()` before the call to `super.onCreate()`. You should fix your example.

With that being said, in the example, rotation works. This probably means I'm doing something wrong. I can't test without `uiSettings.isRotateGesturesEnabled(true)` right now, as I don't own an Android device and my roommate went to sleep (as should I). Meanwhile, I'll describe my setup:

```java
// Create map options with defaults
_mapOptions = MapboxMapOptions.createFromAttributes(context, null);
// Set some options on _mapOptions, like the map style and initial camera

// When it's time to render the map, I do the following:
_mapView = new MapView(this.getContext(), _mapOptions);
_mapView.getMapAsync(this); // Maybe I should move this after onCreate?
this.addView(_mapView);
_mapView.onCreate(null);

// In onMapReady, I set some more options. I currently do this:
_map.setMyLocationEnabled(_showsUserLocation);
_map.setPadding(_paddingLeft, _paddingTop, _paddingRight, _paddingBottom);
TrackingSettings trackingSettings = _map.getTrackingSettings();
trackingSettings.setMyLocationTrackingMode(_locationTrackingMode);
trackingSettings.setMyBearingTrackingMode(_bearingTrackingMode);
UiSettings uiSettings = _map.getUiSettings();
uiSettings.setZoomGesturesEnabled(_zoomEnabled);
uiSettings.setScrollGesturesEnabled(_scrollEnabled);
uiSettings.setRotateGesturesEnabled(_rotateEnabled);
```

**Comment by dapetcu21** [comment]
Ok. After further investigation, it seems it has nothing to do with what options I give to the map. Even if I just do `new MapView(getContext())`, it still doesn't work. I'm trying to integrate the map in a React Native component. Maybe it has something to do with the way the view is added to the view hierarchy.

Any suggestions for why might the gesture responders not work properly in these circumstances?

**Comment by dapetcu21** [comment]
I am not very familiar with Android, but after some debugging, it seems that something weird happens with the second touch:

<img width="393" alt="screen shot 2016-07-02 at 15 04 52" src="https://cloud.githubusercontent.com/assets/428060/16540259/7acd3364-4066-11e6-962a-e651ebaf79af.png">

The Map view occupies the lower half of the screen.

**Comment by dapetcu21** [comment]
I've found the bug and I managed to reproduce the problem with the standard example. It only happens if the Map View is not positioned near the screen origin (`event.getY() - event.getRawY()` close to 0).

The bug is in `TwoFingerGestureDetector.getRawX` and `getRawY`:

```
protected static float getRawX(MotionEvent event, int pointerIndex) {
        float offset = event.getX() - event.getRawX(); // This should be event.getRawX() - event.getX()
        if (pointerIndex < event.getPointerCount()) {
            return event.getX(pointerIndex) + offset;
        }
        return 0.0f;
    }
```

**Comment by tobrun** [comment]
@dapetcu21 
I was able to reproduce this issue using the `Snaphot Activity` and the proposed PR resolves this.
