### ISSUE TITLE
Tidy up touch on Android

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#553]
My touch input handling code needs a lot of work. It is very messy and should perhaps be moved into another class.

We also need to add any missing gestures from Google Maps eg fling. We should match their 'feel' so that Android users can pick up and use our map with minimal learning

Finally the two finger rotation gesture is broken.

**Comment by ljbade** [comment]
As I mentioned to @bleege I don't like the design of the gesture library as I don't think it scales with lots of gestures.

I think it needs a good redesign but will take a lot of thinking and work to come up with a really top notch gesture library for Android.

**Comment by 1ec5** [comment]
I'd also be interested in working on Android gesture support eventually, mainly to bring over the drifting implemented in #1292.

**Comment by bleege** [comment]
> I'd also be interested in working on Android gesture support eventually

Woo hoo!  Another new Java person on the team!  :-)

**Comment by ljbade** [comment]
Haha yeah I'd love an iOS view on how to do gesture detection on Android. The current Android model is just not as flexible/extendable as how it works on iOS.

Ideally we just implement something like the iOS gesture detection framework on top of the raw Android touch events.

@bleege What has your experience with touch been like on the raster SDK?

**Comment by ljbade** [comment]
@tobrun Some useful WWDC links for background on iOS touch model:
https://developer.apple.com/devcenter/download.action?path=/videos/wwdc_2010__hd/session_121__advanced_gesture_recognition.mov
https://developer.apple.com/devcenter/download.action?path=/videos/wwdc_2011__hd/session_118__making_the_most_of_multitouch_on_ios.m4v
https://developer.apple.com/devcenter/download.action?path=/videos/wwdc_2012__hd/session_233__building_advanced_gesture_recognizers.mov
https://developer.apple.com/videos/wwdc/2015/?id=107

**Comment by ljbade** [comment]
Google list the Android gestures here: https://www.google.com/design/spec/patterns/gestures.html#gestures-drag-swipe-or-fling-details

**Comment by ljbade** [comment]
Also interesting note about using `Scroller` to compute fling animation: http://developer.android.com/training/gestures/scroll.html

We should use this.

**Comment by tobrun** [comment]
@ljbade Indeed, Scroller will be the way to go if we want [interpolation](http://developer.android.com/reference/android/widget/Scroller.html#Scroller(android.content.Context, android.view.animation.Interpolator)) in the animations. I think Google is using a AccelerateDecelerateInterpolator for their flings. (same interpolators for zoom and rotate). They are also applying some techniques seen in the WWDC video that are not standard available in GestureDetectorCompat (eg. removing jitter,..).

I have been trying to get Scroller/VelocityTracker stuff working but failed to get positive results. MapView is no ordinary Android SDK View.. I'm going to postpone this a bit until I have a better grasp on what's possible with NativeMapView. 

Below I listed some personal pro vs cons on writing a touch model ourselves. 
 - more control + flexibeler for tweaking simultaneous gestures
 - write it from scratch indicates implementing even the most basic gestures 
 - time to develop / get it to production worthy level
 - harder to get identical UX as in Google Maps

To make this a all a bit more concrete, I think we should make a list of items that need work so we can build a strategy on top of that.

**Comment by incanus** [comment]
> MapView is no ordinary Android SDK View.

![](https://i.imgflip.com/rhw3b.jpg)

**Comment by ljbade** [comment]
Do we have any contacts that have gone the route of replacing the stock (and terrible) Android gesture libs with their own?

**Comment by tobrun** [comment]
When comparing Google Maps with Mapbox I notice following items:
 - They remove jitter
 - Fling decelerates (scroller)
 - Rotate/Zoom uses velocity trackers because it continues when we lift our fingers 
 - Double tap + drag is a zoom gesture
 - Rotation/zoom gestures don't overlap that easily
 - Tilt 

@ljbade are there any items missing from this list?

I will start working on a gesture framework in my own free time in the next weeks, so I can be as productive as possible during my Mapbox hours. Excited about this!

**Comment by ljbade** [comment]
@tobrun yeah I think you got main ones. There are a few existing tickets for some on them I'll come back later and link them.

**Comment by ljbade** [comment]
@tobrun yeah I think you got main ones. There are a few existing tickets for some on them I'll come back later and link them.

**Comment by ljbade** [comment]
@tobrun One more that Google Maps does.

They detect the start a gesture based on velocity, whereas we wait for a minimum movement distance. You will notice this if you try the pinch zoom very slowly on Google, it just ignores it.

Im going to remove the TODO comments and see if I can hit https://github.com/mapbox/mapbox-gl-native/issues/813 which is the most annoying of our bugs.

**Comment by tobrun** [comment]
A user reached out and gave us some detailed information as seen [here](https://github.com/mapbox/mapbox-gl-native/issues/3176)

**Comment by tobrun** [comment]
Closing, we are looking into improving our currently used dependency from Almeros.
