### ISSUE TITLE
[Android] Addmarkers() with markerview ?

### ISSUE THREAD

**Issue by benjisora** [mapbox/mapbox-gl-native#5530]
Hello there,

I'm using MapBox in an Android app to render a lot of markers on a map, and to do so, I was creating a List of MarkerOption, and I was using the 'addmarkers' function then. By using 'addmarker' and adding them one by one, it weirdly takes way to long, as explained (and solved) in #5390 

The problem is, I have to add a custom icon to each of them, and it seems like when I do so, some markers disappear kinda like seen in #3379, and I end up with a memory leak if I refresh several times even though I use "removeAnnotations" to make sure it cleans the map when I refresh the data. (I think my code needs some correcting, but still, the disappearance of the markers I had before when not adding a custom icon is a bit problematic...)

I saw that MapBox 4.1.0 introduced the markerviews, but I have troubles adding them like I previously did with simple markers (in a list and then using addmarkers). Is there any way to add multiple markerview at once on a map ?

Thank you.

**Comment by tobrun** [comment]
Backstory why we currently aren't exposing the following signature:

```java
addMarkers(@NonNull List<? extends BaseMarkerViewOptions> markerOptionsList)
```

Is because it collides with:

```java
addMarkers(@NonNull List<? extends BaseMarkerOptions> markerOptionsList)
```

At this point I only think exposing a different signature would resolve this:

```java
addMarkerViews(@NonNull List<? extends BaseMarkerViewOptions> markerOptionsList)
```

**Comment by shiyuankao** [comment]
I also have this problem, when to solve this BUG

**Comment by SylvainHocq** [comment]
I folow this issue carrefuly, because actually when i use MarkerView, I have performance problems when I use about 100 MarkerView.

**Comment by tobrun** [comment]
@SylvainHocq we are aware of the performance issues with MarkerView. MarkerViews are Android SDK View objects synchronised above a SurfaceView. They are extremely flexible when it comes to functionality but are limited in performance. We hope to solve this use-case some day with Marker View clustering. GL based markers on the other hand scale much better, they are drawn as part of our gl rendering but they do not expose all the basic functionality yet.

**Comment by Mandrakia** [comment]
@tobrun There's a problem with GL Markers if mass refresh icons every seconds there will be a memory corruptions resulting in all markers disappearing.

**Comment by cammace** [comment]
We now include [`.addMarkerViews()`](https://www.mapbox.com/android-sdk/api/4.2.0-beta.4/com/mapbox/mapboxsdk/maps/MapboxMap.html#addMarkerViews-java.util.List-) in the SDK for easier adding of markers. 

@Mandrakia You should only remove and re-add markers as a last resort. It's much better just to update their location, icon, etc. 

Closing ticket since nothing else seems to be actionable here. If anyone has questions, feel free to reach out through [our contact page](https://www.mapbox.com/contact/) and I'l be happy to help.
