### ISSUE TITLE
GZIP Telemetry Events In Android

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#5536]
Per @willwhite's request in #3979 we should GZIP Telemetry Events to reduce the size of data being transported across HTTP.  iOS is being implemented in PR #5490 .

/cc @mapbox/telemetry

**Comment by frederoni** [comment]
Note that in iOS, we're not using a gzip wrapper for zlib as we didn't want to rely on additional dependencies. Instead, we reused the implementation in `compression.cpp`
When compressing with zlib, `Content-Encoding` on the request should be set to `deflate`

That being said, gzip vs zlib is still not settled.

**Comment by bleege** [comment]
Integrated the `GzipRequestInterceptor` with the Telemetry OkHttp client and successfully tested on both the Staging and Production endpoints (see images below).  I'll do a spot check in the Staging data pond to make sure that the data showed up as expected.  If so then things should be good to go.

![screen shot 2016-07-18 at 9 37 56 am](https://cloud.githubusercontent.com/assets/989928/16918709/59963a48-4ccc-11e6-9c90-17c67aeca808.png)
_Staging Server Successful Test_

![screen shot 2016-07-18 at 9 41 38 am](https://cloud.githubusercontent.com/assets/989928/16918720/686ba42c-4ccc-11e6-8a8e-aeb77dd34d4f.png)
_Production Server Successful Test_

**Comment by bleege** [comment]
Confirmed in Staging data pond that the data made it in as expected.  I'm (thankfully) unable to confirm the data itself in Production due to [Mapbox's Telemetry privacy policy](https://www.mapbox.com/telemetry/).

**Comment by bleege** [comment]
Rebased and Merged!
