### ISSUE TITLE
Marker view disappearing when zoom level is low. 

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5537]
Marker view disappears when you zoom in and then back out. If you already zoomed out and add the marker it will appear, this only happens when zooming in and back out.

![ezgif com-video-to-gif 8](https://cloud.githubusercontent.com/assets/5652865/16532950/6511e86c-3fa3-11e6-9c61-edb75a11350f.gif)

cc: @tobrun

**Comment by tobrun** [comment]
This is related to the dateline issue from #5402 and not related to zoom levels. It seems that the changes from https://github.com/mapbox/mapbox-gl-native/pull/5484 got lost while merging `release-v4.1.0` back to `master`.
