### ISSUE TITLE
MapboxAccountManager not correctly initialised 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5541]
Capturing from @geohacker that some people were having trouble setting up a working Mapview using the MapboxAccountManager setup. They were running into an invalid access token exception. This is the code they were using:

```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        MapboxAccountManager.start(MainActivity.this, "somekey");
        mapView  = (MapView) findViewById(R.id.mapview);
        mapView.onCreate(savedInstanceState);
    }
```

I asked if they could move the initialisation code to the Application object but that didn't resolve the issue. We need to look into reproducing this by setting up a new android project from scratch using `4.1.0` dependency.

**Comment by dapetcu21** [comment]
It worked for me when I moved `MapboxAccountManager.start()` before `super.onCreate()`, since `start()` needs to be called before the `MapView` is instantiated.

**Comment by jfirebaugh** [comment]
@dapetcu21 This is the same issue with the example code as you mentioned in https://github.com/mapbox/mapbox-gl-native/issues/5528#issuecomment-230078529, right?

**Comment by dapetcu21** [comment]
Yes. I suppose so.

**Comment by tobrun** [comment]
@dapetcu21 thank you for adding that information but this should also work just before calling onCreate.

@bleege I have been debugging [this](https://github.com/asifali22/MapboxTest/blob/master/app/src/main/java/com/hybrid/mymapboxapp/MainActivity.java) and noticed that `MapboxAccountManager` is not correctly initialised:

![screen shot 2016-07-04 at 07 51 46](https://cloud.githubusercontent.com/assets/2151639/16551947/56aef3d4-41bd-11e6-8241-ddbd8dde8689.png)

As workaround people can setup MapboxAccountManager in their application object but we need to fix this for next release.

**Comment by bleege** [comment]
If I understand things correctly, `MapboxAccountManager.start()` does not work when initialized when used in `Activity.onCreate()`?  Is it working when used in `Application.onCreate()`?  Also, is there a stack trace of the error available?

>  since start() needs to be called before the MapView is instantiated.

Yep.  That's the key.  The code from the OP should be rewritten to put the `MapboxAccountManager.start()` above the `setContentView(R.layout.activity_main)` if that layout xml file contains a MapView in it.

The rule of thumb is: Put `MapboxAccountManager.start()` in the code before ANY other Mapbox tech is instantiated.

```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        MapboxAccountManager.start(MainActivity.this, "somekey");
        setContentView(R.layout.activity_main);
        mapView  = (MapView) findViewById(R.id.mapview);
        mapView.onCreate(savedInstanceState);
    }
```

**Comment by tobrun** [comment]
@bleege thank you for looking into this and clarifying that `        MapboxAccountManager.start(MainActivity.this, "somekey");` should be positioned before `setContentView(R.layout.activity_main);`. That said, this isn't a requirement and is removable. This will result in the same user experience as we used to have (users should can provide their `accesstoken` between findViewById and onCreate). 

I'm also thinking about improving our user facing messages around this. This can either be done through by showing a concrete exception or improving our messages for InvalidAccessTokenException.

**Comment by bleege** [comment]
>  That said, this isn't a requirement and is removable. 

@tobrun Can you speak more to this?

> I'm also thinking about improving our user facing messages around this. This can either be done through by showing a concrete exception or improving our messages for InvalidAccessTokenException.

Totally!  👍   @cammace updated https://www.mapbox.com/android-sdk/examples/ last week to get us started on this.  I like the `MapboxAcountManagerNotStartedException` idea that you started quite a bit.  I wonder if now is the right time for this though as `MapboxAccountManager` won't officially become the one and only way for access tokens until the deprecated Access Token methods are fully removed in #5621.  #5621 is a SemVer bump which means it'll happen in `5.0.0` at the soonest.

**Comment by tobrun** [comment]
@bleege 

>>That said, this isn't a requirement and is removable.

>@tobrun Can you speak more to this? 

Let me reverse the question. Why should it be required to call `MapboxAccountManager.start(MainActivity.this, "somekey")` before `setContentView(R.layout.activity_main)`?  Proposed solution in #5541 showcases a way that you can configure your accesstoken just until the point of MapView#onCreate (this is the same as with our older system, why would we change this?)

> I wonder if now is the right time for this though as MapboxAccountManager won't officially become the one and only way for access tokens until the deprecated Access Token methods are fully removed in #5621.

I'm not seeing any reason why not to include it. I'm not forcing,  removing or breaking anything. I'm only making it easier for our users to integrate. This is unrelated to any SemVar or the deletion in #5621.

**Comment by bleege** [comment]
@tobrun Thanks for clarifying what the proposed code does and the thinking behind it.  That makes much more sense now.  👍
