### ISSUE TITLE
Compatibility with older devices

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#555]
- [ ] compile both armeabi and armeabi-v7
- [ ] Use Android support libraries
 - [ ] for 3.x
 - [ ] for 2.x (android support lib v4)
- [ ] Test Android versions in emulator
 - [x] 5.0 (API 21)
 - [x] 4.4 (API 19)
 - [x] 4.3 (API 18)
 - [x] 4.2 (API 17)
 - [x] 4.1 (API 16)
 - [x] 4.0.3 (API 15)
 - [x] 4.0 (API 14)
 - [ ] 3.x (API 13-11)
 - [ ] 2.3.3  (API 10)
 - [ ] 2.3.0  (API 9)
- [ ] Test for Android versions on real devices
 - [ ] 5.0 (API 21)
 - [x] 4.4 (API 19)
 - [ ] 4.3 (API 18)
 - [ ] 4.2 (API 17)
 - [ ] 4.1 (API 16)
 - [ ] 4.0.3 (API 15)
 - [ ] 4.0 (API 14)
 - [ ] 3.x (API 13-11)
 - [ ] 2.3.3  (API 10)
 - [ ] 2.3.0  (API 9)
- [ ] Test different screen sizes and densities
- [ ] Test different GPUs
- [ ] List any problems found
- [ ] Fix any problems
- [ ] Test again

**Comment by ljbade** [comment]
Starting to see unusual errors on devices I haven't tested such as https://github.com/mapbox/mapbox-gl-native/issues/738 and https://github.com/mapbox/mapbox-gl-native/issues/608

I think we need to start expanding our range of test devices and start writing unit tests.

This will likely need to wait until after merge though.

**Comment by ljbade** [comment]
I should make a note that now we build arm-v5 I need to get the Java side working on Android 2.x and make it an officially supported platform.

**Comment by bleege** [comment]
> get the Java side working on Android 2.x and make it an officially supported platform.

[This Week In Android API Marketshare](https://developer.android.com/about/dashboards/index.html) is reporting that API 10 is the only 2.x level with any significant usage (it's at 7%).  Just something to keep in mind so that we don't spend cycles on something that won't be used.

![20150210-android-api-markershare](https://cloud.githubusercontent.com/assets/989928/6140202/da63c020-b149-11e4-82f0-e053ac00f6f7.png)

**Comment by ljbade** [comment]
@bleege last time I looked the work required to get API 10 supported also supported API 9 (and 8? can't remember) for free

**Comment by bleege** [comment]
@ljbade Cool!  Just wanted to make sure that we were careful and didn't accidentally go down a rabbit hole that we didn't need to.

**Comment by erf** [comment]
Rendering of some tiles fails on my Samsung S3 (4.4.4)

**Comment by ljbade** [comment]
@erf can you provide more details/screenshots in a new ticket?

**Comment by erf** [comment]
added a new issue #1776

**Comment by ljbade** [comment]
@bleege I think we can close this now after https://github.com/mapbox/mapbox-gl-native/issues/934
