### ISSUE TITLE
Tapping on markers doesn't relayout.

### ISSUE THREAD

**Issue by dapetcu21** [mapbox/mapbox-gl-native#5560]
In my particular scenario, I'm trying to port Mapbox to React Native (see [this huge PR](https://github.com/mapbox/react-native-mapbox-gl/pull/365) for what I'm trying to do).

The problem is that markers don't show up unless I manually trigger a re-layout:

[Workaround here](https://github.com/dapetcu21/react-native-mapbox-gl/blob/master/android/src/main/java/com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLView.java#L532-L548)

I haven't managed to reproduce this on the [example](
https://www.mapbox.com/android-sdk/examples/), but I tried stripping my code bare and I can only conclude it probably has something to do to React's internal view hierarchy.

**Platform:** Android
**Mapbox SDK version:** 4.1.0

### Steps to trigger behavior

 1. Initialize map inside React Native component.
 2. Add markers to the map.
 3. Tap on a marker to show its tooltip.

### Expected behavior

The tooltip should show up.

### Actual behavior

The tooltip doesn't show up, but if a relayout is triggered (by rotating the screen, for example), the tooltip is rendered in its correct position.

**Comment by tobrun** [comment]
@dapetcu21 thank you for reaching out. As mentioned by you this isn't an issue with the Android SDK but a react related issue. Feel free to open an issue downstream in https://github.com/mapbox/react-native-mapbox-gl/issues. Closing for now.

**Comment by dapetcu21** [comment]
You have misunderstood me. I'm not talking about finding a bug while using `react-native-mapbox-gl`. I'm talking about the fact that I found a bug in `mapbox-gl-native` while working on `react-native-mapbox-gl`.

It could be a `react-native` issue, at most, but I think it's very unlikely for it to be that. The easiest explanation is that the issue is most likely in `mapbox-gl-native` and that happens to manifest when being used with RN.

**Comment by dapetcu21** [comment]
I'll investigate further and try to reproduce it without RN, though.
