### ISSUE TITLE
Latitude <+90 and >-90

### ISSUE THREAD

**Issue by bessermt** [mapbox/mapbox-gl-native#5564]
**Platform: Android**

public class Projection {
...
public double getMetersPerPixelAtLatitude(@FloatRange(from = -180, to = 180) double latitude) {

Normalized latitudes <=+90 and >=-90 for all degrees regardless of projection. Many projections are even more restrictive. If not normalized, then no restrictions are expected. Not sure what this code does, but it makes no sense to list a range of latitude restriction at +-180 degrees.

**Comment by tobrun** [comment]
@bessermt thank you for reaching out, your analysis is spot on, patching up now
