### ISSUE TITLE
the action that move mapView is conflicted with selected Annotation

### ISSUE THREAD

**Issue by Paladinfeng** [mapbox/mapbox-gl-native#5565]
**Platform: iOS 9.3.2
**Mapbox SDK version: v3.3.0-beta2

When I moved the mapView, the selected annotationView would be deselected. So, I can't selected an annotation forever?

**Comment by Paladinfeng** [comment]
And, if the annotation is out of screen, it can't be selectd. is this a bug?

**Comment by boundsj** [comment]
This is a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/4389 and the solution will be part of the implementation of https://github.com/mapbox/mapbox-gl-native/issues/3154.
