### ISSUE TITLE
Add a fromList method in LatLngBound

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5574]
Currently the only way to add points to a LatLngBound object is to using the `.include()` method which only takes in individual latlng points. It would be useful to also expose a method that consumes a list of latlng points. An example use would be when you want to fit the map to a polyline, you would only need to pass in the list of points rather then creating a for loop and using the include. 

cc: @tobrun

**Comment by tobrun** [comment]
Capturing from chat with @cammace that this could be exposed in the `LatLngBounds.Builder#includes(List<LatLng>)`

**Comment by bleege** [comment]
It looks like this was added after `4.1.1` shipped so I'll milestone this as part of `4.2.0` release for tracking.
