### ISSUE TITLE
On first app run, cache.db is backed up to iCloud

### ISSUE THREAD

**Issue by dapetcu21** [mapbox/mapbox-gl-native#5577]
I found the following bug:

When you first open the app, there is no `cache.db` to begin with. `setResourceValue:forKey:NSURLIsExcludedFromBackupKey` is getting [called](https://github.com/mapbox/mapbox-gl-native/blob/9c9140595e9c1d9a12120e167421034f6036b08a/platform/darwin/src/MGLOfflineStorage.mm#L94) on the file, but you have no guarrantees that the file is created at that point and the call won't fail silently.

So, on the first run, `NSURLIsExcludedFromBackupKey` might be set before `cache.db` is created, hence being left with `cache.db` being backed up by iCloud, automatically rejecting your app when reviewed on the App Store.

A simple and effective solution (that I employed in my app) is to set `NSURLIsExcludedFromBackupKey` on the cache directory, which is [ensured to exist](https://github.com/mapbox/mapbox-gl-native/blob/9c9140595e9c1d9a12120e167421034f6036b08a/platform/darwin/src/MGLOfflineStorage.mm#L60), instead of on the file.

I'll submit a PR in a sec.

**Platform:** iOS
**Mapbox SDK version:** 3.2.0

### Steps to trigger behavior

 1. Use offline maps in your app
 2. Download a big enough offline pack in the first run of the app
 3. Publish the app to the App Store

### Expected behavior

Though big in size, `cache.db` will be marked with `NSURLIsExcludedFromBackupKey`, so it will not be backed up. Hence, your app will pass the review process with flying colors.

### Actual behavior

Your app will get rejected because `cache.db` is not properly excluded and you'd end up saving hundreds of MB on the user's iCloud account.

**Comment by dapetcu21** [comment]
If you want to try to reproduce, I suggest using
```
xattr -l ~/Library/Developer/CoreSimulator/Devices/${DEVICE_UUID}/data/Containers/Data/Application/${APP_UUID}/Library/Application\ Support/${APP_BUNDLE_ID}/cache.db
```
to test.

**Comment by friedbunny** [comment]
Thanks again for reporting this and proposing #5578, @dapetcu21.
