### ISSUE TITLE
Building on/for Raspberry Pi 3

### ISSUE THREAD

**Issue by danzel** [mapbox/mapbox-gl-native#5582]
Are there any details on how to build for Raspberry PI 3?
Either setting up a cross compile environment on another machine, or what distro and extra pieces to install?

I can successfully build natively on a x64 linux machine, but RPi is causing me troubles.

I started a machine with latest raspbian. Installed the linux requirements and qt requirements (Except qtlocation5-dev, which isn't available), then ran `make qt-lib`.
This dies without a good error, I tracked it down to `https://github.com/mapbox/mapbox-gl-native/blob/master/scripts/check-cxx11abi.sh`
The `ldd` command doesn't work by the looks, so I hardcoded the location to get past this.

Next it dies inside npm install, which I haven't solved yet.

Going to try set up an ubuntu 16.04 install on the pi and try that. But maybe someone has some advice?
Thanks!

**Comment by danzel** [comment]
Set up ubuntu 16.04 on the rpi, followed all the normal build steps.

Had to do the following hacks:

`check-cxx11abi.sh` hack as above ^^

`Makefile` manually set `export JOBS ?= 1` otherwise we run out of memory and crash while building.

Add `#define MBGL_USE_GLES2 1` to `include/mbgl/gl/gl.hpp`

Waiting on it to rebuild now... zzz...

**Comment by jfirebaugh** [comment]
Did you see https://www.mapbox.com/blog/native-gl-yocto/?

**Comment by danzel** [comment]
Yep, have been figuring out some of the bits from the patches in there.
I'm trying to build it without using yocto however.

More hack instructions:
`include/mbgl/platform/default/headless_view.hpp`
Comment out the first ifdef block (all of it).

Manually remove the `headless_view.o` and `headless_view_glx.o` lines from `build/qt-linux-armv7l/platform/qt/core.target.mk`
(May not need the above headless_view hack if you do this)
^^ I Couldn't figure out a nice way to tell it not to build these (they don't seem to be required).

This allowed me to complete the build and run the app!
It runs really poorly though, like the GL isn't being hardware accelerated. I'll investigate a bit more but any advice would be great, possibly my GL just isn't enabled or something.

**Comment by tmpsantos** [comment]
@danzel thanks for the feedback. You are right about the `headless_view`. We use it on Qt for running the unit tests and should not be built/linked together with the example app or being part of the shared library

I will track this issue here -> https://github.com/mapbox/mapbox-gl-native/issues/5603
