### ISSUE TITLE
Fix screenshot/snapshot api for SurfaceView

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5587]
SurfaceView implementation was merged with 99a4850, this resulted in a not supporting a correctly working snapshot api. We need to look into fixing this to work with a SurfaceView implementation. Original ticket of Snapshot functionality: https://github.com/mapbox/mapbox-gl-native/issues/3466.

**Comment by tobrun** [comment]
I'm currently looking into the code from [Grafika](https://github.com/google/grafika). This is repo from google where you can find a lot different code snippets related to graphics on Android.

**Comment by tobrun** [comment]
The most promising snippet I could found was `saveFrame` in [EglSurfaceBase](https://github.com/google/grafika/blob/master/src/com/android/grafika/gles/EglSurfaceBase.java#L157). I'm looking into if that is useable for our use-case.

**Comment by tobrun** [comment]
This [blog](https://mkonrad.net/2014/12/08/android-off-screen-rendering-using-egl-pixelbuffers.html) gives some insights into achieving off screen rendering into a bitmap.

**Comment by tobrun** [comment]
I'm currently looking into a `glReadPixels` approach. This seems promising but wasn't able yet to pass back the bytes buffer through JNI to Java.

**Comment by tobrun** [comment]
Been getting some tips on how `glReadPixels` is used in this projec. Nodejs is using it through `headless_view.ccp` but more interesting is that macos is using it their print feature [here](https://github.com/mapbox/mapbox-gl-native/blob/d0766120ca2513e44584f12014283de4c361372b/platform/macos/src/MGLMapView.mm#L729-L735). You can see there that the printing is executed as part of the render call, this ensures that the state is activated. Now looking into bringing that in.

**Comment by zugaldia** [comment]
Fixed via https://github.com/mapbox/mapbox-gl-native/pull/5826.
