### ISSUE TITLE
Offline Region Searching [Feature Request]

### ISSUE THREAD

**Issue by tcolligan-ap** [mapbox/mapbox-gl-native#5590]
**Platform:Android and iOS**
**Mapbox SDK version: 4.1**

As far as I am aware, there is currently no way to do geocoding using offline regions. Here is my potential use-case:

1. Using a mobile app, a user downloads the area of Cuba as an offline region.
2. The user is now offline, and wishes to navigate to a specific address/street using their offline map. But they do not know exactly where said address/street is located relative to their current position in the offline map.
3. Adding a search bar that would allow them to search for where the street is located in their offline region would be extremely helpful for the user, so that they could figure out how to navigate there using the offline map.

As far as I can tell, it is not currently possible to implement something like this. Is a feature such as this on the MapBox teams radar at all? Thanks!

**Comment by jfirebaugh** [comment]
See #5481.

**Comment by lhorus** [comment]
I'm gonna go ahead and bump this for you @tcolligan-ap, as I have been looking for this for quite some time now as well, and it proved to be a rather futile search. Some other open-source libs have this implemented, [in a fairly clear fashion](https://github.com/CartoDB/mobile-carto-libs/tree/cbd712aaf09b745d59f586f9c6f8512480836fa4/geocoding/src/geocoding). However, they use their own [SQLLite-based structure](https://github.com/CartoDB/mobile-sdk/wiki/Nutigeodb-format), for which, generating tools are not available. Might serve as an inspiration for you!

Let us know if you make any progress on the subject, perhaps the MB team might feel like implementing your thoughts!
