### ISSUE TITLE
Polygon outlines using line style rule are not closed

### ISSUE THREAD

**Issue by herrapa** [mapbox/mapbox-gl-native#5591]
**Platform: iOS**
**Mapbox SDK version: 99a4850 (master as of today)**

Since earcut landed we're seing a similar results as #1467 and #1450 when we're styling polygon outlines with a separate line style rule. The outlines appear with a gap.

We ran a bisect and found the commit that caused the new behaviour: a475f1d81397bc79731e6392692420bd1aa29c41

Specifically, [this line](https://github.com/mapbox/mapbox-gl-native/blob/99a4850613931059174ecf0c6a41af4690481e3a/src/mbgl/tile/geometry_tile_data.cpp#L67) causes the removal of the last coordinate, as it is a duplicate of the first one. However, if we change the "closed" argument to `false`, and uncomment [this line](https://github.com/mapbox/mapbox-gl-native/blob/99a4850613931059174ecf0c6a41af4690481e3a/src/clipper/clipper.hpp#L47), we get the desired result. 

Is this only a performance optimisation, or are we missing something obvious? Our app relies heavily on styling polygon outlines as lines.

Simple style used to test this and resulting images [here](https://gist.github.com/herrapa/6be5c795e0b549dbe0c0fe91c4c3e740)

### Expected behavior
![Polygon](https://cloud.githubusercontent.com/assets/5419651/16624373/ad2c19e0-43a1-11e6-8528-29942c53f0fe.png)
### Actual behavior
![Broken polygon](https://cloud.githubusercontent.com/assets/5419651/16624274/5a30256a-43a1-11e6-9f27-a424c4cf5a96.png)

**Comment by jfirebaugh** [comment]
Thanks for the detailed issue report @herrapa! I'm investigating now.
