### ISSUE TITLE
Offline Region Completed Resource Size Inaccurate

### ISSUE THREAD

**Issue by tcolligan-ap** [mapbox/mapbox-gl-native#5597]
**Platform: Android**
**Mapbox SDK version: 4.1**

In a project I created, I am downloading offline regions. The mapbox sdk allows me to display the size of the offline regions in bytes by using `OfflineRegion.getCompletedResourceSize()`.

However the values I am receiving for this value seems to be inaccurate. I record the offline region's area in terms of mi^2, and a 5.78 mi^2 region is show as being 71MB, while a 799 mi^2 region is shown as being 82.42 MB. This doesn't seem right, the second region should be much larger in size I would think?

Are the map tiles not being included in the byte size calculation due to the bug found in this issue? https://github.com/mapbox/mapbox-gl-native/issues/5305

My example project can be found [here](https://github.com/tcolligan/AndroidMapBoxText) with the relevant code in `MainActivity.java` at function `showOfflineMapRegionList`.

![Image of MapBoxTestt](http://i930.photobucket.com/albums/ad141/CloneCommando/Screenshot_2016-07-06-17-32-24_zpsgajvlaji.png)

**Comment by jfirebaugh** [comment]
See https://github.com/mapbox/mapbox-gl-native/issues/5487#issuecomment-228783368 and #4069. If you want just the tile size, use `OfflineRegion.getCompletedTileSize()`.

**Comment by tcolligan-ap** [comment]
@jfirebaugh Both `getCompletedTileSize()` and `getCompletedTileCount()` currently return 0 in `4.1`, so that isn't super helpful, but ok.

The comment about the shared resources makes some sense, thank you.
