### ISSUE TITLE
icon-text-fit rendering does not match gl-js

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#5602]
Usually we write these kinds of subtle differences off to GPU implementations, but in this case the differences are reproducible locally, using the same GPU.

![image](https://cloud.githubusercontent.com/assets/98601/16639040/d38f70a6-43a0-11e6-94b9-d8f56b9c4a0d.png)
![image](https://cloud.githubusercontent.com/assets/98601/16639043/d94786aa-43a0-11e6-8a33-f69c33e4b74b.png)
![image](https://cloud.githubusercontent.com/assets/98601/16639044/dbccc412-43a0-11e6-82e5-be1633100d3a.png)
![image](https://cloud.githubusercontent.com/assets/98601/16639046/df9098e4-43a0-11e6-899e-72e345c399c6.png)
![image](https://cloud.githubusercontent.com/assets/98601/16639053/e2cad1be-43a0-11e6-9fb2-1704df863650.png)

cc @yhahn

**Comment by ChrisLoer** [comment]
@ansis I think you may have fixed this by changing `Shaping` to use floats. The tests are passing now on #10103.
