### ISSUE TITLE
Attribution and logo

### ISSUE THREAD

**Issue by p-fischer** [mapbox/mapbox-gl-native#5618]
Hi, I have a legal question concerning the logo and the attribution overlays. 

On the Android SDK page is written:

> Attribution

> 
You must comply with the licensing terms of any map data in your application, including Mapbox Streets or other Mapbox maps if used. A small attribution control will be displayed on the map view automatically. The attribution control may be moved or removed as necessary, so long as the required attribution is reasonably provided in your app.

Looking at  [UISettings](https://www.mapbox.com/android-sdk/api/4.1.0/com/mapbox/mapboxsdk/maps/UiSettings.html) attribution refers to the info icon, while logo refers to the "Mapbox" text.

(On Android) Is it allowed use the default attribution, but to hide the "Mapbox" logo to save display space?

**Comment by cammace** [comment]
Thanks for reaching out to us today and your interest in the Mapbox SDK. All [non-Enterprise accounts](https://www.mapbox.com/pricing/) are required to display the Mapbox logo when using a Mapbox map within your application. Like mentioned in the quote above, you are allowed to move the attribution (info button). For future information and questions, please [contact us here](mapbox.com/contact) for a fast reply.
