### ISSUE TITLE
minZoom issue on some displays/browsers

### ISSUE THREAD

**Issue by jordanbommelje** [mapbox/mapbox-gl-native#5619]
### Steps to trigger behavior

 1. Set minZoom in map attributes
 2. Visit map 

### Expected behavior
Zoom level should be limited to what's set in the JS attributes.
### Actual behavior
On larger/hi-res screens, the minZoom value isn't followed. I thought this was a Chrome specific issue, however one of my maps it happens in Safari as well. All seem to yield different looking maps, however.

### Environment
15" Retina MacBook Pro with 27" 4k Monitor running Mac OS 10.11.5
12" Retina MacBook running Mac OS 10.11.5

### Example outputs
**15" MacBook Pro on 4k**
http://weareroberts.com/maps/chrome-15.png
http://weareroberts.com/maps/safari-15.png
http://weareroberts.com/maps/firefox-15.png

**12" MacBook**
http://weareroberts.com/maps/chrome-12.png
http://weareroberts.com/maps/safari-12.png
http://weareroberts.com/maps/firefox-12.png

### Link for testing
http://weareroberts.com/maps/satellite-test.html

**Comment by kkaefer** [comment]
Looks like you're talking about [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js).

**Comment by jordanbommelje** [comment]
Moving over to mapbox-gl-js
