### ISSUE TITLE
Include example application in distribution

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5622]
We should include an example application (as source code) in the iOS SDK distribution. Other map SDKs do this already to help developers get a feel for the basic feature set and difficulty level before diving in. CocoaPods has formalized this approach with its `try` subcommand that relies on source code inside the archive that the podspec points to:

```
$ pod try Mapbox-iOS-SDK
Updating spec repositories

Trying Mapbox-iOS-SDK
[!] Unable to find any project in the source files of the Pod: `/private/var/folders/cl/…/T/CocoaPods/Try/Mapbox-iOS-SDK`
```

The example application doesn’t even have to be as full-featured as iosapp. To minimize the download size, we could make it a simple full-screen application with pin-dropping functionality.

/cc @friedbunny @frederoni @boundsj

**Comment by friedbunny** [comment]
I prepared the barest of demo apps last year in [friedbunny/mbgl-demo-ios](https://github.com/friedbunny/mbgl-demo-ios), but creating another, bespoke demo would take probably a few minutes.

**Comment by friedbunny** [comment]
How would we reconcile this proposed demo app with the examples we show people on our website? My expectation as a user would be parity between what I see on the site and what I find in the demo app.

I’m also unsure about how we would avoid confusion between iosapp and this new app that would also live in this repository.

**Comment by 1ec5** [comment]
I’m not sure. All I know is that [our pod](https://cocoapods.org/pods/Mapbox-iOS-SDK) got three `try`s today alone, and the experience is better with the Nutiteq and ArcGIS pods. Maybe we should literally package up [ios-sdk-examples](https://github.com/mapbox/ios-sdk-examples/) for this purpose.

**Comment by incanus** [comment]
From chat: 

> i wonder.... would adding a `showDemoTour` to `MGLMapView` or something like that be worthwhile?
> imagine getting the sdk into your app, then calling that method to see it do cool stuff / console log the methods/apis involved
> it’s like one method that visually shows you things, with branching out points

This would be lighter and less complex than an additional app. Basically a public method on the map view with a routine that works through some interesting use of the other public API.
