### ISSUE TITLE
[core] Create a generic conversion algorithm for Object -> GeoJSON

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#5623]
Port https://github.com/mapbox/geojson-cpp/blob/master/include/mapbox/geojson_impl.hpp to the conversion functions at https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/style/conversion.hpp

/cc @jfirebaugh

**Comment by dagatsoin** [comment]
Tons of kittens could be saved with that. Plz.

**Comment by springmeyer** [comment]
Can this be closed now that #10075 has landed?

**Comment by jfirebaugh** [comment]
No -- though touching on some of the same areas of code, #10075 was not related to this issue.

**Comment by springmeyer** [comment]
Okay, thanks.
