### ISSUE TITLE
Setting MapBoundaries in Ionic framework for android & iOS

### ISSUE THREAD

**Issue by jeremiasgoh** [mapbox/mapbox-gl-native#5627]
I have implemented this script from (https://www.mapbox.com/mapbox.js/example/v1.0.0/maxbounds/  )
 on android studio in the ionic's angularJS ,however maxbounds doesn't seem to work, I'm still able to move out of the boundaries. 

This is the code in the controller.
 **var bounds = [
        [1.327966, 103.770487], // Southwest coordinates
        [1.337868, 103.780757]  // Northeast coordinates
    ];**

L.tileLayer('https://api.mapbox.com/styles/v1/xxxxxx/ciq1noy05003ldtnpwpkkeea4/tiles/256/{z}/{x}/{y}?access_token=pk.exxxxxxxxxQnKVA', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
    center: [1.332796,103.775193],
    zoom: 17,
    minZoom: 17,
    maxZoom: 20,
    **maxBounds: bounds,**
    id: 'ciq1noy05003ldtnpwpkkeea4',
    accessToken: 'pk.eyJ1IjoiamVyZW1pYXNnb2giLCJhIjoiY2lxYzVrenIwMDFtZWZybTExejhjN3RheiJ9.6Dv-027CiApS9XuzaG0QKA'
}).addTo(map1);

Is there anything I'm doing wrong?

**Comment by 1ec5** [comment]
You’re using Mapbox GL JS, not the Mapbox Android SDK or iOS SDK, which are for native applications. Please [reopen your issue here](https://github.com/mapbox/mapbox-gl-js/issues/new/). Thank you.

**Comment by 1ec5** [comment]
Actually, you’re using an older JavaScript library, [mapbox.js](https://github.com/mapbox/mapbox.js/), which is built atop [Leaflet](https://github.com/Leaflet/Leaflet/). One of those repositories is the right place for your issue. Sorry for the confusion.

**Comment by jeremiasgoh** [comment]
got it, thanks!
