### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5630]
The macOS SDK supports [rudimentary printing](https://github.com/mapbox/mapbox-gl-native/blob/d0766120ca2513e44584f12014283de4c361372b/platform/macos/src/MGLMapView.mm#L729-L735) of MGLMapView’s current viewport. Judging from [this document](https://developer.apple.com/library/prerelease/content/documentation/2DDrawing/Conceptual/DrawingPrintingiOS/Printing/Printing.html#//apple_ref/doc/uid/TP40010156-CH12-SW1), supporting printing in the iOS SDK’s implementation of MGLMapView would involve similar logic.

/cc @friedbunny

**Comment by friedbunny** [comment]
This would be cool in theory, but as a user I’ve never once considered printing from an iOS device. Is this something people do? As it stands, I’m not even sure how to test an iOS printing implementation (though I imagine obtaining a printer is the first step).

**Comment by lilykaiser** [comment]
Closing due to ticket age. If this is still a problem, please re-open

**Comment by 1ec5** [comment]
Not implemented yet. Should be easier to implement than what we did on macOS, now that we support static snapshots.
