### ISSUE TITLE
Create a marker with empty MarkerOptions may crash.

### ISSUE THREAD

**Issue by dagatsoin** [mapbox/mapbox-gl-native#5631]
**Platform: Android**
**Mapbox SDK version: 4.1.beta-3**

### Steps to trigger behavior

 1. Create a marker (running on the ui thread) with empty options.

Marker marker = _mapboxMap.addMarker(new MarkerOptions());
... //whatever instruction 

### Excepted behavior
Throwing an exception (marker must have at least a position).

### Actual behavior
A non so useful message, not easy to track because unrelated to the marker creation.
```
07-10 07:59:56.308 23190-23190/io.cordova.hellocordova W/dalvikvm: JNI ERROR: GetDoubleField on invalid reference (0x0)
07-10 07:59:56.308 23190-23190/io.cordova.hellocordova E/dalvikvm: VM aborting
07-10 07:59:56.308 23190-23190/io.cordova.hellocordova A/libc: Fatal signal 6 (SIGABRT) at 0x00005a96 (code=-6), thread 23190 (va.hellocordova)

```

**Comment by tobrun** [comment]
@dagatsoin thank you for reaching out. Make sense adding a concrete exception for those cases. I'm currently thinking about `InvalidMarkerPositionException`.

**Comment by tobrun** [comment]
The user will now see the following:

>Pending exception com.mapbox.mapboxsdk.exceptions.InvalidMarkerPositionException: Adding an invalid Marker to a Map. Missing the required position field. Provide a non null LatLng as position to the Marker.
