### ISSUE TITLE
[node]The format of raw image

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-native#5635]
I am trying to save the image of `mbgl.render()` using `gm`, here is my code:
```
gm(buffer).rawSize(512, 512).bitdepth(8).write('image.png', function(err) {
    if (err) throw err;
})
```
The error says: `gm convert: Improper image header`

`sharp` works good. But I want to port it to `gm`. Any suggestions?

**Comment by mikemorris** [comment]
The data returned from `map.render` is a raw RGBA pixel buffer captured from the GPU - it is likely missing the appropriate header information [used by `gm` to identify the file format](https://github.com/aheckmann/gm#custom-identify-format-string).
