### ISSUE TITLE
MGLMapviewDelegate pan event protocol

### ISSUE THREAD

**Issue by azyet22** [mapbox/mapbox-gl-native#5636]
Is there any protocol that handles panning for IOS?

**Comment by 1ec5** [comment]
Do you have a particular method in mind? #5584 would add a method to MGLMapViewDelegate for preventing panning (or zooming, rotating, tilting) on a case-by-case basis. #5504 added a method to MGLMapView that subclasses can override to adjust the focal point of a zoom or rotation gesture. Besides these APIs, MGLMapViewDelegate already has methods for detecting when the viewport will change, is changing, or did change.

**Comment by lilykaiser** [comment]
Closing due to ticket age. If this is still a problem, please re-open
