### ISSUE TITLE
How can I implement drag annotation feature in Mapbox SDK? (iOS)

### ISSUE THREAD

**Issue by yurymirkin1989** [mapbox/mapbox-gl-native#5637]
Hi 

I am using MGLMapView instead of MKMapView now. In MKMapView, I can see draggable for annotation.

Then I can detect drag status in mapview delegate.

- (void)mapView:(MKMapView *)mapView
 annotationView:(MKAnnotationView *)annotationView
didChangeDragState:(MKAnnotationViewDragState)newState
   fromOldState:(MKAnnotationViewDragState)oldState
{
    if (newState == MKAnnotationViewDragStateEnding)
    {
        CLLocationCoordinate2D droppedAt = annotationView.annotation.coordinate;
        int nIndex = [(BasicMapAnnotation*)annotationView.annotation mIndex];
        
        for(BasicMapAnnotation* anno in arrPins)
        {
            if(nIndex == anno.mIndex)
            {
                anno.coordinate = droppedAt;
                [self updateRegion];
                break;
            }
        }
    }
}

But I can't find way in Mapbox. how can I implement dragable feature in Mapbox.

Thanks.

**Comment by 1ec5** [comment]
[A similar API](https://www.mapbox.com/ios-sdk/api/3.3.0-rc.1/Classes/MGLAnnotationView.html#/Supporting%20Drag%20Operations) has been added to the Mapbox iOS SDK in v3.3.0, which will be released shortly. In the meantime, please try out [the latest release candidate](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.3.0-rc.1) and let us know if you run into any issues. Thanks!

**Comment by yurymirkin1989** [comment]
I have installed SDK by using Fabric before 3 days. But I can't find didDragAnnotationView function. 
Also how can I get version number for installed SDK?

**Comment by 1ec5** [comment]
Fabric is currently distributing Mapbox iOS SDK v3.2.3. As soon as we officially release v3.3.0, we’ll upload the new version to Fabric. If you’re using Fabric’s Mac application to install the SDK, that application shows the SDK version when you check for updates. Otherwise, if you’re using CocoaPods via Fabric’s website, you can run `pod update` to see the installed versions of all your pods.

**Comment by yurymirkin1989** [comment]
Hi 

I had updated v3.3.0 in Fabric. But I can't find delegate function for dragging. I can see drag functions for MGLAnnotationView.

But I need to customize drag delegate for MGLMapview. 

void)mapView:(MKMapView )mapView
annotationView:(MKAnnotationView *)annotationView
didChangeDragState:(MKAnnotationViewDragState)newState
fromOldState:(MKAnnotationViewDragState)oldState

When user will change pin's position, I need to customize pin data. 
Could you give me example and more detail description?

Thanks.
Yury

**Comment by friedbunny** [comment]
We decided to go with a simpler implementation (https://github.com/mapbox/mapbox-gl-native/pull/5561) that does not use delegation. Instead, you should override [`-[MGLAnnotationView setDragState:animated:]`](https://www.mapbox.com/ios-sdk/api/3.3.0/Classes/MGLAnnotationView.html#/c:objc(cs)MGLAnnotationView(im)setDragState:animated:) — as in [this example](https://www.mapbox.com/ios-sdk/examples/draggable-views/).

**Comment by yurymirkin1989** [comment]
I had integrated dragging in MGLAnnotationView. But How can I get changed coordinate after dragging?

**Comment by friedbunny** [comment]
Check [`MGLAnnotationView.annotation`](https://www.mapbox.com/ios-sdk/api/3.3.1/Classes/MGLAnnotationView.html#/c:objc(cs)MGLAnnotationView(py)annotation)’s `coordinate` property after the drag state has changed to `Ending`.
