### ISSUE TITLE
Lazy tiles load

### ISSUE THREAD

**Issue by Buminta** [mapbox/mapbox-gl-native#5640]
**Platform: Android**
**Mapbox SDK version: 4.1.0 beta 3 **

Hi Mapbox team.
I'm using Mapbox Studio and upload Tilesets with Shapefile, after i create new my style with my Data.
And create more default style with Mapbox style origin.

However, when i'm used Mapbox style origin. Everything always quickly. (Time for request to API, And Render map vector in client)

But when i'm used My Style Custom with My data (shapefile). Everything always slowly (Time for request and render vector tiles.) -> Not good for performance.
So i wanna fix it. What's need to change my data for performance quickly.
Thanks so much!

**Comment by friedbunny** [comment]
Please provide the URL for your custom Mapbox style that includes the slow layer(s). It would also be very useful if you could quantify what “slow” means in this case — exactly how slow is it?

**Comment by Buminta** [comment]
@friedbunny 
My URL:
```
https://api.mapbox.com/styles/v1/nhannt/ciprtppwx001jainl2aagzloj.html?title=true&access_token=pk.eyJ1Ijoibmhhbm50IiwiYSI6ImNpbXZmOGZiNTAycnN1cmtrcW4yZXJhMngifQ.O12BZRPNvlRfX7t4grP66w#9.63/10.8121/106.8658
```
My Data only use in Vietnam.
U can move to Hanoi or Ho Chi Minh City for check it.
Thanks for support!

**Comment by friedbunny** [comment]
@Buminta Your style is reasonably performant on the iPhone 6s and on the web. Which Android devices are you using?

/cc @cammace

**Comment by Buminta** [comment]
Everyone devices Android i'm using always load very slow.
I'm checked with *.pbf file on the response from api, Size of files very large.
I think that's problem of me!
U had a trick for upload data tile sets or edit styles for good performance. Help me please. Thanks!

**Comment by cammace** [comment]
Hey @Buminta, I ran your style on a Nexus 5x and load times seemed pretty reasonable. If you're interested in optimizing your map you might find [this guide](https://www.mapbox.com/help/data-optimize/) useful. [Optimizing your fontstacks](https://www.mapbox.com/help/manage-fontstacks/) might help load times as well. Lastly, i'd like to point out our [help page](https://www.mapbox.com/help/) which host a lot more guides. 

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5652865/16821913/12e39eb8-4927-11e6-9af0-6be47fef170b.gif)

Hope these guides help, Closing this ticket now but feel free to continue contacting us here or through [our contact page](https://www.mapbox.com/contact/).
