### ISSUE TITLE
Visible Region : bounds are the same

### ISSUE THREAD

**Issue by elguigou** [mapbox/mapbox-gl-native#5652]
#Platform: Android
Mapbox SDK version: com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0-SNAPSHOT@aar

Hi, 

I'm currently developping an app to display markers on a map using GoogleMaps for Online Mode and Mapbox for Offline Mode. 

I want to create a list which contains all markers that are display on screen. For that, I use "_getProjection().getVisibleRegion().latLngBounds_" of GoogleMaps to get actual bounds of the map on screen and I check, for each of my markers, if it contains the LatLng.

I saw that Mapbox also have this property "_getProjection().getVisibleRegion().latLngBounds_" which gave me four coordonates : "N: ...; E: ...; S: ...; W: ...;". My problem is that, each time I use this method, N equals S and E equals W. So it didn't gave me an area with bounds but a point ...

Am i the only one to have this problem ? 
Is there a workaround for this case ?

Thanks for reading me.

**Comment by tobrun** [comment]
@elguigou thank you for reaching out.
I have been looking into this issue and noticed that the Map wasn't measured yet at the time you are calling `getProjection().getVisibleRegion().latLngBounds`. In the following code block `getWidth` and `getHeight` are returning 0. 

```java

    /**
     * Gets a projection of the viewing frustum for converting between screen coordinates and
     * geo-latitude/longitude coordinates.
     *
     * @return The projection of the viewing frustum in its current state.
     */
    public VisibleRegion getVisibleRegion() {
        LatLngBounds.Builder builder = new LatLngBounds.Builder();

        float left = mMapView.getContentPaddingLeft();
        float right = mMapView.getWidth() - mMapView.getContentPaddingRight();
        float top = mMapView.getContentPaddingTop();
        float bottom = mMapView.getHeight() - mMapView.getContentPaddingBottom();

        LatLng topLeft = fromScreenLocation(new PointF(left, top));
        LatLng topRight = fromScreenLocation(new PointF(right, top));
        LatLng bottomRight = fromScreenLocation(new PointF(right, bottom));
        LatLng bottomLeft = fromScreenLocation(new PointF(left, bottom));

        builder.include(topLeft)
                .include(topRight)
                .include(bottomRight)
                .include(bottomLeft);

        return new VisibleRegion(topLeft, topRight, bottomLeft, bottomRight, builder.build());
    }
```

I'm going to patch this up. For now, a workaround would be to force a measure of the MapView or use a delayed runnable to postpone the calculcation.

**Comment by tobrun** [comment]
I did some tests and it seems that `fromScreenLocation`, which is used by VisibleRegion, is not returning the correct value when you call it immediately from the `OnMapReady` callback. Delaying this action seems to resolve it (Handler#postDelayed).

**Comment by tobrun** [comment]
Looking a bit more deep into the details. At time of calling those methods, the map was still animating: for example take these points:

> 07-13 11:30:19.397 20857-20857/com.mapbox.mapboxsdk.testapp E/MapboxMap: From screen location PointF(0.0, 0.0) LatLng [latitude=85.05127407791747, longitude=-122.68771517890514, altitude=0.0]

and

> 07-13 11:30:21.725 20857-20857/com.mapbox.mapboxsdk.testapp E/MapboxMap: From screen location PointF(0.0, 0.0) LatLng [latitude=45.25846730673058, longitude=5.650997113888366, altitude=0.0]

The former was done on Map start up, the other was done with a delayed runnable. You can see the returned values are different for the same point.

**Comment by tobrun** [comment]
@elguigou I did some tests by optimising the way we setup the initial map location, with that in place I'm getting the correct values since the map animation occurs before `OnMapReady` is called. 

##### Option 1:
Define your location in xml:

```xml
    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/pressForMarkerMapView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:center_latitude="45.1855569"
        app:center_longitude="5.7215506"
        app:zoom="11"
        app:style_url="@string/style_mapbox_streets"
        android:layout_below="@id/toolbar"/>
```

#### Option 2:
If your start location is dynamic, you can use MapboxMapOptions instead:

```java
        // configure inital map state
        MapboxMapOptions options = new MapboxMapOptions()
                .attributionTintColor(Color.RED)
                .accessToken(getString(R.string.mapbox_access_token))
                .styleUrl(Style.MAPBOX_STREETS)
                .camera(new CameraPosition.Builder()
                        .target(new LatLng(45.520486, -122.673541))
                        .zoom(12)
                        .tilt(40)
                        .build());

        // create map
        mapView = new MapView(this, options);
```

If you don't want to change your current setup, than I would advice you to wait until the map becomes idle or use a Handler#postDelayed setup. Reach out if you have any other questions or need clarification on above.

**Comment by elguigou** [comment]
Thanks for your answer.

I modified my gradle to use _com.mapbox.mapboxsdk:mapbox-android-sdk:4.1.0@aar_ instead of the snapshot and it's works now.
