### ISSUE TITLE
MGLOfflineStorage changePack

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-native#5657]
It would be nice to be able to change the boundary of a offline pack without having to remove and add it once more. 

My app has lots of small packs. Sometimes some of the areas change. With the current removePack+addPack, the app could/will loose some of its tiles. 

The temporarily solution would be to just add new packs when an area change.

**Comment by jfirebaugh** [comment]
> With the current removePack+addPack, the app could/will loose some of its tiles.

The recommended procedure is the reverse: add the new pack and then remove the old one. This will preserve all existing tiles needed by the new pack.

**Comment by halset** [comment]
Thanks. I will remove the old when the new is complete.
