### ISSUE TITLE
Hang on each tile load

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5659]
On macOS, panning or zooming – anything that causes mbgl to need to load a new tile – [hangs the application](https://gist.github.com/1ec5/e6ae92cf6239ef4fb4e463e563a37f0c). Now it’s difficult to interact with the application, because just about every user interaction results in a 3–10 second hang.

Reproduces in both macosapp and glfw-app.

Bisect implicates b9702ef41a4cfdd0ab3107cfe5cec16ba3a4c230 (#5343), and I’ve verified that it is indeed the change that introduced the regression. But that change was merely renaming the SDK from “OS X” to “macOS”, which shouldn’t have caused anything like this issue. Moreover, the change was cherry-picked into the release-ios-v3.3.0 branch as 061854990ffe495910a5f0dc7c6bb5d394f772e9, and the issue does not reproduce as of 5ede3dd16f673151a6cd34fc78fbdaa08e227449 on that branch.

/cc @kkaefer

**Comment by jfirebaugh** [comment]
Is this region specific? I don't see anything like this in either macosapp or glfw-app.

**Comment by 1ec5** [comment]
No, this reproduces everywhere. If you were seeing this issue, you’d first experience it as a several-second hang on launch.

Worth noting that this only happens in Debug, not Release. That would make it similar to #3636, but that doesn’t explain why it only started happening in #5343 or why it doesn’t happen on the release-ios-v3.3.0 branch.

**Comment by 1ec5** [comment]
Oh dear. You’ll love this one: I had a conditional breakpoint set [on this line](https://github.com/mapbox/mapbox-gl-native/blob/5c037f4745e5a9a3c5f5d050c59d39e3f763bb5a/src/mbgl/renderer/symbol_bucket.cpp#L109), conditioned on `bucketName == "road-shields-white"`. It didn’t reproduce when I checked out anything before #5343 because the workspace was named osx.xcworkspace at that time. It also didn’t appear to reproduce on the release branch because I was verifying that branch in a separate checkout. Sorry for the confusion!
