### ISSUE TITLE
Inconsistent marker draw after removeMarker() call

### ISSUE THREAD

**Issue by josiahcampbell** [mapbox/mapbox-gl-native#5664]
**Platform: Android**  
**Mapbox SDK: 4.1.0**

### Steps to trigger behavior

 1. Call `addMarker` on a LatLng underneath the center of the screen
 2. Call `removeMarker` on the same marker without moving the MapView
 3. Call `addMarker` in the same position, same LatLng

### Expected behavior
We expect the marker to placed on the center of the MapView, in the center of the icon.

### Actual behavior
After removing a marker and adding another one, the marker aligns in the bottom-right corner instead of the center.

Notably, the PointF is always the same, and method calls made to the MapBox's 
projection are always consistent. My thought is that something goes awry when 
mapBox.addMarker(Marker) is called inside `getNewPinLatLng()`.

Here's the following code, in order of calls:

```java
/**
 * Method called when user saves a new marker
 */
 public void savePin(String pinName) {
    // getNewPinLatLng() is shown below
    LatLng centerLatLng = getNewPinLatLng();
    Drawable icon = ContextCompat.getDrawable(getContext(), R.drawable.pin);
    // MapView is called from within a fragment
    IconFactory factory = IconFactory.getInstance(getActivity());

    MarkerViewOptions markerOptions = new MarkerViewOptions()
            .position(centerLatLng)
            .icon(factory.fromDrawable(icon))
            .title(pinName);
    
    mapboxMap.addMarker(markerOptions);
}

/**
 * Get the approximate LatLng at the center of the MapView
 */
private LatLng getNewPinLatLng() {
    // getMapCenter(view) is shown below
    PointF center = getMapCenter(mapView);
    float iconY = icon.getIntrinsicHeight();
    float iconX = icon.getIntrinsicWidth();

    float newX = center.x - iconX / 2;
    float newY = center.y - iconY / 2;

    return mapboxMap.getProjection().fromScreenLocation(new PointF(newX, newY));
}

/**
 * Called by getNewPinLatLng to determine the center of the
 * screen. The result is always the same in testing the issue 
 * noted above
 */
 private PointF getMapCenter(View view) {
    float x = view.getX() + view.getMeasuredWidth() / 2;
    float y = view.getY() + view.getMeasuredHeight() / 2;

    return new PointF(x, y);
}
```
Am I missing something in the way addMarker operates? Any subsequent `addMarker` calls created 
after a `removeMarker` and `addMarker` sequence are position correctly. 
It is only after a marker is removed that the new marker's icon is position at 
the bottom-right corner of the specified PointF.

**Comment by tobrun** [comment]
@josiahcampbel the anchoring was not correct initialised because the MarkerView wasn't measured first. We fixed this in #5513 and you can work around this issue by using the [SNAPSHOT](https://www.mapbox.com/android-sdk/#gradle) for now. Thank you for reaching out and reporting your issue!
