### ISSUE TITLE
Saved Offline Map and used it regardless if theres internet connection(just to make sure it doesnt redownload anything).

### ISSUE THREAD

**Issue by DavidMont** [mapbox/mapbox-gl-native#5667]
Saved Offline Map and used it regardless if theres internet connection.

I have seen samples of Offline Map without data connection, but what I want is that:

*Is it possible to used the map _saved-as-offline_ regardless if theres internet connection (data or wifi)
*Does it download whenever it connects back and erases the previous _downloaded-map_
*Is it possible 

1. To download map(the backbone or light version without styles) one time and redistribute it to disk(by copying and pasting)?
2. To update styles whenever the application(my applictaion) wants it? 

It is because , I don't want users to download the same map over and over again in remote places where internet connection is scarce.

**Comment by jfirebaugh** [comment]
Please see our [help documentation](https://www.mapbox.com/help/mobile-offline/) for details about the offline features.
