### ISSUE TITLE
Set forest background top for map view

### ISSUE THREAD

**Issue by Buminta** [mapbox/mapbox-gl-native#5669]
**Platform: Android**
**Mapbox SDK version:4.0.1 beta3**

Hi mapbox team. 
I wanna use background top with forest or sky with cloud for mapview.
How do it? Thanks for support!

Like this.
![navmii-navigation](https://cloud.githubusercontent.com/assets/5722956/16801272/ed905384-4923-11e6-8e30-3a7685edc41f.jpg)

**Comment by tobrun** [comment]
@Buminta 

A MapView is a View object that extends from FrameLayout and you are able to add any kind of View to its hierarchy. Here is an example:

![device-2016-07-13-140247](https://cloud.githubusercontent.com/assets/2151639/16802729/8b1a80f6-4902-11e6-908e-5a89fc455378.png)


The code for this is:

```java
mapView = (MapView) findViewById(R.id.pressForMarkerMapView);
ImageView imageView = new ImageView(this);
imageView.setBackgroundResource(R.drawable.gradient);
imageView.setAlpha(0.8f);
imageView.setLayoutParams(new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, 512 /* replace with correct converted dp value*/));
mapView.addView(imageView);
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape>
            <gradient
                android:angle="90"
                android:startColor="#00FFFFFF"
                android:endColor="#7ec0ee"
                android:type="linear" />
        </shape>
    </item>
</selector>
```

**Note:**
Here that you can use `MapboxMap#setPadding` and pass in the height of the sky view to adjust the bounds of the map.

Reach out if you have any other questions! Closing for now.

**Comment by friedbunny** [comment]
If you're looking to tilt the map so that the horizon is visible, that is not something that's currently possible.
