### ISSUE TITLE
[IOS] Issue with callout view

### ISSUE THREAD

**Issue by DemianSteelstone** [mapbox/mapbox-gl-native#5674]
**Platform:** IOS
**Mapbox SDK version:** 3.2.3

Hi, I have troubles with callout view.
Your code in MGLMapView.mm

```
- (void)calloutViewTapped:(__unused MGLCompactCalloutView *)calloutView
{
   if ([self.delegate respondsToSelector:@selector(mapView:tapOnCalloutForAnnotation:)])
   {
       id <MGLAnnotation> selectedAnnotation = self.selectedAnnotation;
       NSAssert(selectedAnnotation, @"Selected annotation should not be nil.");
       [self.delegate mapView:self tapOnCalloutForAnnotation:selectedAnnotation];
   }
}
```

But calloutView has representedObject  property, but you're use selected on map, why so?

```
@protocol MGLCalloutView <NSObject>

/**
 An object conforming to the `MGLAnnotation` protocol whose details this callout view displays.
 */
@property (nonatomic, strong) id <MGLAnnotation> representedObject;
```

It cause some troubles for me.

**Comment by boundsj** [comment]
Hi @DemianSteelstone. I think the intention here is that a there should be one and only one callout shown at any point in time and that callout should be associated with the selected annotation.

Can you please provide more details about what you are trying to do with annotations and callouts and the trouble you are having?

**Comment by 1ec5** [comment]
I think the code was written this way so that the map view would set the represented object to the annotation when showing the callout view; it isn't meant to be set by the developer. The fact that the property is publicly writable is a bug.

**Comment by DemianSteelstone** [comment]
I have 
~~~
_tapRecognizer = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(tappedOnMap:)];
~~~
It deselects annotations.

But it some times conflicts with tap gesture on callout. 
Deselect is called before it and I got nil here:
~~~
- (void)mapView:(MGLMapView *)mapView tapOnCalloutForAnnotation:(id <MGLAnnotation>)annotation;
~~~
