### ISSUE TITLE
Polygon strokeColor doesn't show

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5676]
We currently expose `.strokeColor()` on polygon but the stroke width isn't able to be set, this means the stroke color doesn't show. The documentation for this method:

>Sets the color of the stroke of the polygon.

Here's what the polygon looks like when stroke color is suppose to be purple:

<img src="https://cloud.githubusercontent.com/assets/5652865/16810684/e63adfb8-48f2-11e6-9420-46006ae35c8f.png" width=360/>

cc: @tobrun

**Comment by jfirebaugh** [comment]
There is a purple stroke there, though it's barely visible because it's only 1 pixel wide.

Related issues: https://github.com/mapbox/mapbox-gl-style-spec/issues/199, https://github.com/mapbox/mapbox-gl-style-spec/issues/240, https://github.com/mapbox/mapbox-gl-style-spec/issues/223.

**Comment by tobrun** [comment]
As mentioned by above, there is a bother, just not that wide, closing
