### ISSUE TITLE
Control z-elevation of Polygons and Markers (on Android)

### ISSUE THREAD

**Issue by p-fischer** [mapbox/mapbox-gl-native#5678]
Hi, I'm having a bit of trouble with the overlapping of polygons and markers on a map.

I saw that polygons and markers do not interfere strangely but polygons are drawn on the map and markers always are on top.

With polygons I assume that those are on top which are drawn at a later point of time.

Markers confuse me. I want to be able to draw two markers at the same position and control their z-elevation. More precisely, I want to draw a dot-like marker and a balloon-like marker on top of it. (I want to draw two markers since they are applied in different combinations.) I'm afraid that the order in which the markers are drawn does not guarantee, which one appears in the foreground. 

I saw the experimental method addCustomLayer - however, could not find a lot of documentation. Is there a concept of layers lying on top of the map I could use for polygons and/or markers?

**Comment by cammace** [comment]
Thanks for reaching out @p-fischer, for future support questions use our [support page](https://www.mapbox.com/contact/) to quickly get help. 

For marker views, z ordering is coming in [this PR](https://github.com/mapbox/mapbox-gl-native/pull/6137). If you are looking to add layers, don't use the CustomLayer, instead use the new style API we've introduced in `4.2.0` to add layers. A few examples can be found in [this issue](https://github.com/mapbox/mapbox-android-demo/issues/115) and if you want to try them out download the [demo app](https://play.google.com/store/apps/details?id=com.mapbox.mapboxandroiddemo).

Closing issue in favor of https://github.com/mapbox/mapbox-gl-native/issues/5238.
