### ISSUE TITLE
Mapbox Logo And Info Button Alignment Example After Orientation Change

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5679]
When a orientation change occurs and the logo is found in the top right corner. 
The top margin is not correctly reconstructed. 

![ezgif com-video-to-gif 48](https://cloud.githubusercontent.com/assets/2151639/16814369/c5934668-4935-11e6-9ceb-9e157f20c45b.gif)

**Comment by bleege** [comment]
Hey @tobrun, it looks like there are a couple of issues still remaining with this ticket before it can be closed.  First off we should up the communications here and make it abundantly clear to everyone that the code changes made here ONLY AFFECT the `PressForMarkerActivity` example in the TestApp and not a the default behavior for `MapView` which still has both Mapbox name and Info button in the lower left corner as it's always been.  Secondly, while the top margin may be better aligned with the initial code the layout still needs to be worked on.  Specifically, the Mapbox name and the Info button text overlap in both portrait and landscape modes in the upper right hand corner (see screenshots below).  What needs to happen is for the Mapbox name and Info button to be able to moved to the upper right corner (or upper left or lower right) and still be displayed separately as they do in the default lower left corner (see bottom screenshot for example).

![device-2016-07-24-155535](https://cloud.githubusercontent.com/assets/989928/17086494/28825756-51b9-11e6-815a-737635611fdd.png)
_Current PressForMarkerActivity Upper Right Corner Portrait Mode_

![device-2016-07-24-155552](https://cloud.githubusercontent.com/assets/989928/17086501/38db3ac8-51b9-11e6-8e06-ad945a24f9ed.png)
_Current PressForMarkerActivity Upper Right Corner Landscape Mode_

![device-2016-07-24-160652](https://cloud.githubusercontent.com/assets/989928/17086502/44806376-51b9-11e6-895a-013c87f3720e.png)
_Mapbox Name and Info Button Default Display And Desired Layout Spacing_

**Comment by tobrun** [comment]
@bleege this issue is about saving the state of the top margin. Nothing more, nothing less.

```java
outState.putInt(MapboxConstants.STATE_LOGO_MARGIN_TOP, uiSettings.getLogoMarginTop());
```
Any other issue you have with this:
 - if it's related to any comms
 - if the value of the margin is incorrect
 - if the api should be handled in a different way

Please create another issue for this.
