### ISSUE TITLE
Send Android Telemetry Events Automatically When Count Reaches 1000

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#5680]
The Android Telemetry systems should add a cap to the number of events stored before automatically triggering a push to the server.  Currently, the Android Telemetry system attempts to send data every 3 minutes in an effort to minimize the number of power consuming networking calls.  However this can have the effect of allowing large numbers of events to queue up resulting in larger data sets, longer networking calls, and issues processing the number of events at the server.

/cc @mapbox/telemetry

**Comment by l-r** [comment]
I'm interested in knowing what happens when this call to publish with 1000 events fails? Do we just wipe out the data, or do we hang out to it to try later?

**Comment by bleege** [comment]
@l-r The current setup is fire and forget.  As soon as the client attempts to send the data (or the 3 minutes pass) the data is immediately forgotten on device.  For information about this can be found https://github.com/mapbox/mapbox-gl-native/issues/4629#issuecomment-206978388

**Comment by bleege** [comment]
Squashed and Merged!
