### ISSUE TITLE
Optimize image assets

### ISSUE THREAD

**Issue by frederoni** [mapbox/mapbox-gl-native#5688]
Noticed that there are room for improvements in terms of image assets:
- `Compass.png` is incorrect scale (2x = 1,8x, 3x = 2,81) (3x downscaling should be handled automatically) which results in half pixels when loading from resources.
- Logo is positioned on half pixels which prevents pixel perfect rendering.
- App Thinning cannot slice resources unless they're in an asset catalog. (would save ~12KB on 2x devices) (Cocoapods supports asset catalogs as of version 1.0)

**Comment by friedbunny** [comment]
Sounds great. Asset catalogs are iOS 7+, so we’re good there.

**Comment by 1ec5** [comment]
> Logo is positioned on half pixels which prevents pixel perfect rendering.

We mitigate this with [fractional alignment rect insets](https://github.com/mapbox/mapbox-gl-native/blob/765e8d2be18411cc13438cb4c723b6a6658b8c10/platform/ios/src/MGLMapView.mm#L432). It would be great to get these images and their insets into an asset catalog.

**Comment by 1ec5** [comment]
Using an asset catalog would also allow us to replace the existing default_marker.png with [default_marker.pdf](https://github.com/mapbox/mapbox-gl-native/blob/44406e91de97132e18494fb1d3353ce00726f192/platform/macos/sdk/default_marker.pdf), which is scalable.

**Comment by 1ec5** [comment]
#8703 proposes to replace these PNGs with PDFs.

**Comment by friedbunny** [comment]
Fixed by #9060, will be in v3.6.0-beta.1.
