### ISSUE TITLE
MapboxEventManager encodeString allocates too much heap memory

### ISSUE THREAD

**Issue by kingfisherphuoc** [mapbox/mapbox-gl-native#5690]
**Platform: Android**
*_Mapbox SDK version: 4.1.0-beta.3 *_
### Steps to trigger behavior
1. Enable user location and tracking mode to update location frequently
2. Using "Allocation Tracking" of Android studio to track memory allocating.
3. Check the captured files and see a lot of calling the function: `addLocationEvent`. Calling this function too many times caused the heap memory allocated too much. 
4. this is the encode function:

```
private String encodeString(String string) {
        try {
            if (messageDigest != null) {
                messageDigest.reset();
                messageDigest.update(string.getBytes("UTF-8"));
                byte[] bytes = messageDigest.digest();

                // Get the Hex version of the digest
                StringBuilder sb = new StringBuilder();
                for (byte b : bytes) {
                    sb.append( String.format("%02X", b) );
                }
                String hex = sb.toString();

                return hex;
            }
        } catch (Exception e) {
            Log.w(TAG, "Error encoding string, will return in original form." + e);
        }
        return string;
}
```
### Expected behavior

The function should be improved to avoid too much heap memory allocation. The `String.format` is the root cause and it's much slower than normal `StringBuilder.append` (about 5 times), then I think we can avoid it by remove `String.format` function.
You can look at this link for comparing: `http://stackoverflow.com/questions/513600/should-i-use-javas-string-format-if-performance-is-important`
### Actual behavior

I saw a large amount of memory allocated by function `encodeString()` of `MaxboxEventManager` class (look at the images below).

<img width="1056" alt="screen shot 2016-07-15 at 12 11 17 am" src="https://cloud.githubusercontent.com/assets/962484/16848722/5972e28a-4a21-11e6-9dc2-ef6c7ce39d09.png">
<img width="1048" alt="screen shot 2016-07-15 at 12 11 37 am" src="https://cloud.githubusercontent.com/assets/962484/16848727/5dac84fa-4a21-11e6-9f1e-8a756fb28e6b.png">

**Comment by zugaldia** [comment]
It looks like using something similar to [`org.apache.commons.codec.binary.Hex`](https://github.com/apache/commons-codec/blob/trunk/src/main/java/org/apache/commons/codec/binary/Hex.java#L175-L197) would be more performant.

**Comment by zugaldia** [comment]
With the introduction of https://github.com/mapbox/mapbox-gl-native/pull/7892, [`MapboxTelemetry`](https://github.com/mapbox/mapbox-java/blob/master/mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java) is no longer using `MessageDigest`. Thanks @kingfisherphuoc again for your report.
