### ISSUE TITLE
Scale map icons and fonts based on screen resolution of device

### ISSUE THREAD

**Issue by troyibm** [mapbox/mapbox-gl-native#5692]
The current default icons and font sizes used in MGLMapView look tiny and difficult to distinguish when viewed on the iPad Pro 12.9 model.

This issue is to request that the map styling change dynamically based on the resolution of the device by perhaps providing vector based PDFs for icons similar to how image assets are handled in iOS.

Some related issues are #2429 and #5626

**Comment by 1ec5** [comment]
I got a chance to check out v3.6.x on an 12.9″ iPad Pro the other week and didn’t see anything amiss. If you’re still seeing this issue, would you mind posting a screenshot so we can figure out what specifically needs to be scaled up?
