### ISSUE TITLE
Info window anchoring not adjusting when map's moved

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5694]
When GL markers are used and an info windows selected while tilted, the info window wont remain positioned correctly above the marker icon.

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/5652865/16852889/f7cdab76-49d7-11e6-931e-7455156cb7c0.gif)

**Comment by 1ec5** [comment]
The equivalent issue on iOS and macOS is #5695.

**Comment by tobrun** [comment]
This is potentially fixed with #10449

**Comment by 1ec5** [comment]
> This is potentially fixed with #10449

In that implementation, the info window’s size is aligned to the viewport rather than the map. Are we sure the offset is scaled along with the marker symbol as the marker symbol recedes into the background?

**Comment by tobrun** [comment]
Closing this in favor of #10499

**Comment by 1ec5** [comment]
@tobrun, are you sure you meant #10499, which is a Qt bug?
