### ISSUE TITLE
Map debug options in release mode

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#5699]
We use map debug options mainly as a mechanism to inspect our rendering engine. This usually comes with additional overheads that potentially affects metrics like binary size and memory footprint - see #5555 as example. In light of this, I see two possibilities in which we could avoid exposing this in release mode:
- Make all `MapDebugOptions` no-ops in release mode - this way we'd still have functions like `Map::setDebug` available in release mode to avoid any binary incompatibility, but their internal implementation would provoke no effects in the engine.
- Do not expose `MapDebugOptions`, `Map::setDebug` and related public API functions in release mode - this adds extra complexity for platform-specific code that would also need to remove their related functions in release mode.

I'm inclined to accept the former option due to its low complexity and maintenance - however I'd love to read your thoughts before proceeding with this.

@mapbox/gl

**Comment by kkaefer** [comment]
> no-ops in release mode

We could log a message to warn the user that this doesn't do anything to avoid confusion.

**Comment by 1ec5** [comment]
These are public APIs in the iOS and macOS SDKs, documented as aids for debugging styles. We'll need to update the documentation to note that they're no longer functional, are deprecated, and exist only for backwards compatibility.

**Comment by brunoabinader** [comment]
Per conversation with @1ec5 - it turns out that the tile boundary and tile info debug flags are currently being very useful for bug reporting. It seems reasonable then to make `MapDebugOptions::Overdraw` and `MapDebugOptions::StencilClip` no-ops and remove those from the public SDKs.

**Comment by 1ec5** [comment]
They're already public, and I don't think it's worth breaking backwards compatibility over these flags, so we'd mark them as deprecated and document them as nonfunctional for now.

**Comment by mikemorris** [comment]
These are all currently exposed in the Node.js bindings as well, and we've used them a little for debugging, but they're not clearly documented anywhere AFAIK.

**Comment by brunoabinader** [comment]
I believe we have general consensus to make both `overdraw` and `stencil clip` debug options no-ops in release mode. This is now being proposed in #5555.
