### ISSUE TITLE
Regression - PrecisionPoint TransformState::latLngToPoint dateline issue

### ISSUE THREAD

**Issue by manimaul** [mapbox/mapbox-gl-native#5709]
There is a regression on issue #4155 / #3995 

Version 4.1.0 - Release

>  Issue in mbgl when calculating points based on LatLng from the left side of the dateline after crossing the dateline from left to right. This is a follow up issue for #3995.
> 
> An example:
> 
> Take this LatLng:
> 
> LatLng [longitude=-179.64576449708883, latitude=-16.83408606795382, altitude=0.0]
> before crossing the dateline latLngToPoint is giving us Point[x=455.80133, y= 746.6456]
> while after crossing the dateline latLngToPoint is giving us Point[x=393667.44, y=747.1837].
> Normally we should see a small decrease in value not a big increase.

**Comment by cammace** [comment]
I believe we are tracking the fix for this in https://github.com/mapbox/mapbox-gl-native/issues/4522 if it isn't already resolved? Closing in favor of that ticket.
