### ISSUE TITLE
Error when rendering sprites with mapbox-gl-native for node

### ISSUE THREAD

**Issue by Maarius** [mapbox/mapbox-gl-native#5711]
This is a follow up of issue: https://github.com/mapbox/mapbox-gl-native/issues/4922

Environment:
```
Ubuntu: 16.04 LTS
node: v6.3.0
npm: 3.10.5
```
packages:
```
"gl": "^4.0.2",
"mapbox": "^1.0.0-beta1",
"mapbox-gl": "^0.21.0",
"mapbox-gl-native": "^3.3.0",
"minimist": "^1.2.0",
"node-png": "^0.4.3",
"png-js": "^0.1.1",
"request": "^2.73.0",
"sharp": "^0.15.1",
"url": "^0.11.0",
"util": "^0.10.3"
```

I use the following script to create an image from a map:

```
// requirements
var fs = require('fs');
var gl = require('gl');
var mapbox = require('mapbox');
var mapboxgl = require('mapbox-gl');
var mbgl = require('mapbox-gl-native');
var mbutil = require("mapbox-gl/js/util/mapbox");
var PNG = require('png-js');
var request = require('request');
var sharp = require('sharp');
var url = require('url');
var util = require('util');
var zlib = require('zlib');

var map = new mbgl.Map({
  request: function(req, callback) {
    request({
        url: req.url,
        encoding: null,
        gzip: true
    }, function (err, res, body) {
        if (err) {
          console.log('err');
          callback(err);
        } else if (res.statusCode == 200) {
          var response = {};

          if (res.headers.modified) { response.modified = new Date(res.headers.modified); }
          if (res.headers.expires) { response.expires = new Date(res.headers.expires); }
          if (res.headers.etag) { response.etag = res.headers.etag; }

          response.data = body;

          callback(null, response);
        } else {
          console.log(body);
          callback(new Error(JSON.parse(body).message));
        }
    });
  },
  ratio: ratio
});

map.load(/styles/streets-v9.json);

map.render({
  zoom: zoom,
  width: width,
  height: height,
  center: [longitude, latitude],
}, function(err, pixels) {
  if (err) throw err;

  var image = sharp(pixels, {
    raw: {
      width: Math.floor(width * ratio),
      height: Math.floor(height * ratio),
      channels: 4
    }
  });

  // Convert raw image buffer to PNG
  image.toFile(path, function(err, info) {
    if (err) throw err;
  });
});
```

The original content of `streets-v9.json` when downloaded from mapbox.com is:

```
{
  "version": 8,
  "name": "Mapbox Streets",
  "metadata": {
      "mapbox:autocomposite": true,
      "mapbox:type": "default",
      [...]
  },
  "sources": {
      "composite": {
          "url": "mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v7",
          "type": "vector"
      }
  },
  "sprite": "mapbox://sprites/mapbox/streets-v9",
  "glyphs": "mapbox://fonts/mapbox/{fontstack}/{range}.pbf",
  [...]
}
```
which, when used like this, results in the following error:

```
ERROR (Style): Failed to load sprite: Invalid protocol: mapbox:
{ class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load sprite: Invalid protocol: mapbox:' }
```
So I used the following short script to generate the proper urls:

```
var argv = require('minimist')(process.argv.slice(2));

var mbutil = require("mapbox-gl/js/util/mapbox");

var accessToken = 'pk.eyxxx';
console.log(mbutil.normalizeSourceURL(argv.sourceUrl, accessToken));
console.log(mbutil.normalizeSpriteURL(argv.spriteUrl, '', '', accessToken));
console.log(mbutil.normalizeGlyphsURL(argv.glyphsUrl, accessToken));
```

Which produces:
```
sourceUrl: https://api.mapbox.com/v4/mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v7.json?access_token=pk.xxx&secure
spriteUrl: https://api.mapbox.com/styles/v1/mapbox/streets-v9/sprite?access_token=pk.xxx
glyhpsUrl: https://api.mapbox.com/fonts/v1/mapbox/{fontstack}/{range}.pbf?access_token=pk.xxx
```
I replaced the respective urls in `streets-v9.json` with these urls so that it looks like:
```
{
  "version": 8,
  "name": "Mapbox Streets",
  "metadata": {
      "mapbox:autocomposite": true,
      "mapbox:type": "default",
      [...]
  },
  "sources": {
      "composite": {
          "url": "https://api.mapbox.com/v4/mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v7.json?access_token=pk.xxx&secure",
          "type": "vector"
      }
  },
  "sprite": "https://api.mapbox.com/styles/v1/mapbox/streets-v9/sprite?access_token=pk.xxx",
  "glyphs": "https://api.mapbox.com/fonts/v1/mapbox/{fontstack}/{range}.pbf?access_token=pk.xxx",
  [...]
}
```
When I run the script afterwards, I get the following error:
```
ERROR (Style): Failed to load sprite: unsupported image type
{ class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load sprite: unsupported image type' }
```

As suggested by @mikemorris, I tried the following variations of the sprite url.

1. `https://api.mapbox.com/styles/v1/mapbox/streets-v9/sprite?access_token=pk.xxx`
Produces error above.

2. `https://api.mapbox.com/styles/v1/mapbox/streets-v9/sprite.json?access_token=pk.xxx`

Produces error:
```
ERROR (Style): Failed to load sprite: unsupported image type
{ class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load sprite: unsupported image type' }
```
3. `https://api.mapbox.com/styles/v1/mapbox/streets-v9/sprite.png?access_token=pk.xxx`
```
Produces error:
ERROR (Style): Failed to load sprite: Failed to parse JSON: Invalid value. at offset 0
{ class: 'Style',
  severity: 'ERROR',
  text: 'Failed to load sprite: Failed to parse JSON: Invalid value. at offset 0' }
```

However, when I open 2. or 3. in a browser, I see either the correct JSON file or the png file.

Also, if I remove the "sprite" entry from `streets-v9.json` completely, the image is rendered, however naturally the sprite images are missing completely.

Is there any way to get the sprites rendered properly in this setup?

**Comment by jfirebaugh** [comment]
The `sprite` property in the style serves as the base of two URLs: one for image PNG data, and one for JSON metadata such as size information. At runtime, Mapbox GL adds the extensions `.png` or `.json` (as well as a scale factor `@2x`), and makes a request for each. (This is documented  [here](https://www.mapbox.com/mapbox-gl-style-spec/#root-sprite), although it could definitely be clarified.)

It won't work to modify the URL in the style beforehand, because the implementation will always append and request both extensions. If your implementation of `request` needs to do something different depending on whether the PNG or JSON is being requested, it should look at `req.kind`, where `5` means "SpriteImage" and `6` means "SpriteJSON". [Ref](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/node/README.md#implementing-a-file-source).

As an aside, do you mind if I ask why you are implementing handling for `mapbox://` URLs? We generally encourage people to use the Mapbox [Static API](https://www.mapbox.com/api-documentation/#static) for this sort of thing, and expect the node bindings to be used more for rendering _non_-Mapbox hosted styles.

**Comment by Maarius** [comment]
Hey @jfirebaugh thanks for chiming in and helping out. I adjusted my implementation of `request` according to your recommendations and now it works fine for sprites.

I am implementing handling for `mapbox://` URLs because I would like to generate large map images for printing purposes. As the images generated through the Static API are limited to 1280x1280, they are far too small for high quality prints.
