### ISSUE TITLE
Error:(73, 25) error: cannot find symbol method includes(List<LatLng>)

### ISSUE THREAD

**Issue by DavidMont** [mapbox/mapbox-gl-native#5712]
/home/davidluvellejoseph/AndroidStudioProjects/android-mapboxgl/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/LatLngBoundsActivity.java
Error:(73, 25) error: cannot find symbol method includes(List<LatLng>)

I forked [mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native) and changed the `build.gradle` in testApp using maven [prebuilt](https://www.mapbox.com/android-sdk/#gradle) . But this error just occured, How do I mitigate with this?

**Comment by cammace** [comment]
By default, the Android testapp is built using the other module in the project `MapboxGLAndroidSDK`, which is the SDKs source code. This means the testapp will typically use code not avaliable in the prebuilt stable versions. You can try using the `SNAPSHOT` which is a built from the source code nightly, revert the testapp back to building from source (using [these instructions](https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md) might help), or if you are just trying out the SDK you can download the Mapbox demo app from the [Google PlayStore](https://play.google.com/store/apps/details?id=com.mapbox.mapboxandroiddemo) or view the [project code here](https://github.com/mapbox/mapbox-android-demo).
