### ISSUE TITLE
Changing coordinate of custom class conforming to MGLAnnotation does not move annotation on map

### ISSUE THREAD

**Issue by charliecliff** [mapbox/mapbox-gl-native#5720]
If I call:
    [self.locationAnnotation setCoordinate:((MDRLocationCondition *)self.condition).location.coordinate];

I expect that method to be KVO Compliant, as you guys said it is. But it ain't...

**Platform:**
**Mapbox SDK version:**
### Steps to trigger behavior
1. Add an MGLPointAnnotation to the Map
2. Change it's Coordinate Property
   3.
### Expected behavior

The MGLPointAnnotation Should Move.
### Actual behavior

The MGLPointAnnotation does not Move.

**Comment by 1ec5** [comment]
What version of the SDK are you using?

Also, is locationAnnotation an instance of MGLPointAnnotation or is it an instance of a subclass of MGLPointAnnotation? (Be sure to verify that it's the type you expect at runtime.) MGLPointAnnotation itself does have a [KVO-compliant implementation](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/MGLPointAnnotation.h#L21), but it's possible for a subclass to have a non-compliant implementation.

**Comment by Gerz-inc** [comment]
@charliecliff I have the same problem as you have won it?

**Comment by 1ec5** [comment]
Via #5755, there are also reports of the annotation image also failing to update. (Both the image and coordinate are updated via the same mechanism.)

**Comment by Gerz-inc** [comment]
@1ec5, what about this bug?

**Comment by ChrisXu1221** [comment]
It's also not working for me.
```Swift
class Annotation: NSObject, MGLAnnotation {
...
}
```

The workaround is to subclass by `MGLPointAnnotation`, then it's working now.
```Swift
class Annotation: MGLPointAnnotation {
...
}
```

**Comment by Gerz-inc** [comment]
@ChrisXu1221 @1ec5 that's not helped in my case

**Comment by Gerz-inc** [comment]
@1ec5 
`[self setCoordinate:coord];`
Help me

**Comment by 1ec5** [comment]
I’m unable to reproduce this problem in iOS SDK v3.4.0-beta.7 or macOS SDK v0.3.0-rc.1. I tried setting the `coordinate` property of an instance of MGLPointAnnotation, an instance of a subclass of MGLPointAnnotation, and an instance of a subclass of NSObject that conforms to MGLAnnotation. In all three scenarios, the annotation correctly moves on both iOS and macOS.

@Gerz-inc, I don’t see any issues with the code that you’ve posted, but have you verified that the `-setPosition:` setter you’ve implemented gets called at the expected times?
