### ISSUE TITLE
com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request with response code = 401: Unauthorized

### ISSUE THREAD

**Issue by DavidMont** [mapbox/mapbox-gl-native#5733]
com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request with response code = 401: Unauthorized

Map is Black Screen.

**Comment by friedbunny** [comment]
This very likely means that your access token was entered incorrectly or it is otherwise invalid.

**Comment by DavidMont** [comment]
@friedbunny hmm kind of weird because I have a debug access and release access(which is paid), either of these two are currently spitting out `401:Unauthorized`, Is there anyway I could identify the problem here?

**Comment by DavidMont** [comment]
@friedbunny I generated another access token still the same problem, I still don't get it how do I debug this. the release, debug and the new generated debug access token doesnt work, Its all black, It so frustrating, I changed my wifi.

**Comment by DavidMont** [comment]
@friedbunny  registered a new account(so total account I currently have is 3) , Still the same.

**Comment by DavidMont** [comment]
```
    <string name="map_box_id">pk.eyJ1IjoibW9udGVjaWxsb2Rhdmlkc3BpbmdpbmUiLCJhIjoiZjZjZGY2YTk3YTQzNGRjNjU1OGE4NTFhYWQ0OWQzNTMifQ.3dvDVArhWzHqsnVyVhfu7Q</string>
    <string name="style_mapbox">mapbox://styles/mapbox/satellite-v9</string>
```
above is my debug 2nd account

```
<string name="mapbox_style_id">pk.eyJ1IjoiY2N1cmF0byIsImEiOiJkMGZhMDYxNDE4ODZiN2JkM2RlMTI0NTVhODI5MmY5OCJ9.RxwP837dNa7rFT8IBxnbBQ</string>
 ```
my debug on 1st account
