### ISSUE TITLE
[Android] Blackbox marker at 4.1.0 ver

### ISSUE THREAD

**Issue by vacxe** [mapbox/mapbox-gl-native#5735]
@bleege @tobrun guys, Im update version from 4.0.1 to 4.1.0. Problem occurred on the device Samsung GalaxyTab (SM-T111)  osVer 4.2.2. Custom marker drawable displayed as black box image. But on other devices all correct.

At 4.0.1
![device-2016-07-20-135550](https://cloud.githubusercontent.com/assets/2812510/16984488/f442c2a2-4e82-11e6-9be6-bae1888bb0c5.png)

At 4.1.0
![device-2016-07-20-135906](https://cloud.githubusercontent.com/assets/2812510/16984487/f4424ad4-4e82-11e6-9a79-fe1fb2afecc1.png)

**Comment by bleege** [comment]
@vacxe Thanks for the report.  Can you share the code used to generate this so that we can try to replicate it and have everyone work from the starting point?  Thanks!

**Comment by vacxe** [comment]
```java
map.addMarker(new MarkerOptions()
                .position(latLng.latLng())
                .icon(IconFactory.recreate(String.valueOf(resource), BitmapFactory.decodeResource(App.getInstance().getResources(), resource)))));
```

**Comment by cammace** [comment]
Hey @vacxe happy to help you out here. Could you try using Marker views instead of GL markers and see if this resolves the issue. I tested using this code and it worked:
```java
mapboxMap.addMarker(new MarkerViewOptions()
                        .position(new LatLng(-37.821629, 144.978535))
                        .icon(IconFactory.recreate(String.valueOf(R.drawable.purple_marker), BitmapFactory.decodeResource(getResources(), R.drawable.purple_marker))));
```
Could you test on a different device and see if the issue still occurs? You could also try setting up your icon like so:
```java
// Create an Icon object for the marker to use
                IconFactory iconFactory = IconFactory.getInstance(MainActivity.this);
                Drawable iconDrawable = ContextCompat.getDrawable(MainActivity.this, R.drawable.purple_marker);
                Icon icon = iconFactory.fromDrawable(iconDrawable);
``` 
and then passing the icon to the marker. Please let me know if this works for you and for future support feel free to reach out using [our contact page](mapbox.com/contact).

**Comment by cammace** [comment]
@vacxe let me know if my snippet above didn't fix the missing icon and if this issues still a blocker. It sounds like the same issue found here https://github.com/mapbox/mapbox-gl-native/issues/5443, closing in favor of it.
