### ISSUE TITLE
User location moves with camera while tracking enabled

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5737]
When user location tracking's enabled, the marker will follow where ever the camera moves to until a user performs a map gesture disabling tracking. In the gif below, I first don't have tracking enabled and works as expected, then I enable and the bug occurs. 

![ezgif com-video-to-gif 3](https://cloud.githubusercontent.com/assets/5652865/16991373/52da6640-4e69-11e6-9125-9f1069307c02.gif)

cc: @tobrun

**Comment by tobrun** [comment]
Proposed solution in #6414. Adding to current milestone.
