### ISSUE TITLE
SurfaceView rendering with NavigationDrawer and statusbar

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5738]
**update**: reopened to investigate issues related to nav drawer and snackbar.

**original**:
Feedback from latest SNAPSHOT indicates that we are seeing the same bug with SurfaceView as mentioned in https://github.com/mapbox/mapbox-gl-native/issues/2244#issuecomment-138904413. 

Next actions:
  - [x] add example to TestApp with an NavigationDrawer
  - [x] reproduce issue on multiple android versions
  - [x] look into [setZorderOnTop](https://developer.android.com/reference/android/view/SurfaceView.html#setZOrderOnTop(boolean)) or related Android SDK methods.
  - [x] revert back to TextureView if issue still exists

**Comment by tobrun** [comment]
First tests show that I'm not able to reproduce an rendering artefact when I have the basic Navigation Drawer setup (cfr. Android Studio Acitivity creation wizard) on Android N or KitKat.

**Comment by tobrun** [comment]
I tried converting the standard Navigation Drawer setup with a translucent statusbar. My focus here is to recreate the same experience as Google maps exposes on that Platform. 

#### Android Nougat:
![device-2016-07-21-132457](https://cloud.githubusercontent.com/assets/2151639/17021189/8fbecca8-4f46-11e6-9286-aabbbee63dce.png)

#### Android Lollipop:
<img width="523" alt="screen shot 2016-07-21 at 13 29 05" src="https://cloud.githubusercontent.com/assets/2151639/17021252/2bc5b634-4f47-11e6-9b46-574ab2a89956.png">

#### Android KitKat:
![image](https://cloud.githubusercontent.com/assets/2151639/17021220/dbeb6618-4f46-11e6-8d03-daeb1d6d86c0.png)

**Comment by tobrun** [comment]
The NavigationDrawer itself isn't an issue but the status bar is:

![ezgif com-video-to-gif 16](https://cloud.githubusercontent.com/assets/2151639/17022477/6abc21be-4f4e-11e6-80ac-25ec55507297.gif)

![ezgif com-video-to-gif 17](https://cloud.githubusercontent.com/assets/2151639/17022486/75f60572-4f4e-11e6-8aeb-72dd9a108980.gif)

**Comment by tobrun** [comment]
I have been trying out some things to get the desired result. With a couple of window flags I was able to show NavigationDrawer correctly but you can see it clipped at the bottom.

![ezgif com-video-to-gif 18](https://cloud.githubusercontent.com/assets/2151639/17023901/fb7e12f0-4f55-11e6-958b-323543961c63.gif)

**Comment by tobrun** [comment]
Progress update: I was able to get it working on Android N without issue from https://github.com/mapbox/mapbox-gl-native/issues/5738#issuecomment-234237466. It boils down brining the navigation drawer to front while doing the animation:

```java
  @Override
  public void onDrawerSlide(View drawerView, float slideOffset) {
        mDrawerLayout.bringChildToFront(drawerView);
        mDrawerLayout.requestLayout();
   }
```

![ezgif com-video-to-gif 19](https://cloud.githubusercontent.com/assets/2151639/17024763/69015136-4f59-11e6-8954-5692e7dea21c.gif)

**Comment by tobrun** [comment]
Looking at testing with KitKat now and seeing that the animation is not occurring full width:

![ezgif com-video-to-gif 20](https://cloud.githubusercontent.com/assets/2151639/17025395/eb6d9a7e-4f5b-11e6-9f77-f6d3ee7876f3.gif)

Hiding the SurfaceView showing the animation:

![ezgif com-video-to-gif 21](https://cloud.githubusercontent.com/assets/2151639/17025397/f1519df0-4f5b-11e6-90ac-b3097977bde1.gif)

**Comment by bleege** [comment]
Seeing similar issues when testing on Samsung S5 running API 21

![device-2016-07-22-110043](https://cloud.githubusercontent.com/assets/989928/17063224/db3f0642-4ffb-11e6-9280-58fd90471001.png)


![device-2016-07-22-110214](https://cloud.githubusercontent.com/assets/989928/17063231/e06383c8-4ffb-11e6-90e7-c76a4a4feac3.png)

**Comment by tobrun** [comment]
We have reverted back to TextureView #5765. Reopening this as I create a separate branch to track down clipping issues with NavDrawer and Snackbar with SurfaceView.

**Comment by tobrun** [comment]
I have been searching the web to find some hints on how to resolve this. After trying a couple of things I came across this http://stackoverflow.com/questions/20373529/navigationdrawer-under-mapfragment-and-cameraview-surfaceview.

That SO answer indicates to add a transparent background color on a overlain layout. We already have a markerViewContainer layout there so I adjusted `mapview_internal.xml` to:

```xml
<?xml version="1.0" encoding="utf-8"?>
<merge xmlns:android="http://schemas.android.com/apk/res/android">

    <SurfaceView
        android:id="@+id/surfaceView"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <FrameLayout
        android:id="@+id/markerViewContainer"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clickable="false"
        android:background="@android:color/transparent"/>

    ....

</merge>
```

This does not only solve our issue on older devices it also remove the requirement that a user needs to work around this issue themselves as with https://github.com/mapbox/mapbox-gl-native/issues/5738#issuecomment-234255917 or https://github.com/mapbox/mapbox-gl-native/issues/5738#issuecomment-234264793/


-----

#### Before

![ezgif com-video-to-gif 54](https://cloud.githubusercontent.com/assets/2151639/17145779/f6e906a0-535b-11e6-8c70-28307a985dd3.gif)


#### After

![ezgif com-video-to-gif 55](https://cloud.githubusercontent.com/assets/2151639/17145835/43012766-535c-11e6-9c77-5a3bc5f7b098.gif)

**Comment by tobrun** [comment]
#5804 was merged into the development branch of SurfaceView. Closing
