### ISSUE TITLE
[iOS]UIPickerView.reloadAllComponents() hides all MGLPolygons

### ISSUE THREAD

**Issue by YoungxHelsinki** [mapbox/mapbox-gl-native#5739]
**Platform:iOS 9.3**
**Mapbox SDK version:3.2.2 & 3.2.3**

### Steps to trigger behavior
**1** Create and draw a polygon
```swift
@IBOutlet weak var picker: UIPickerView!
let p1 = MGLPolygon()
let m1 = MGLPointAnnotation()
mapView.addAnnotations( [p1,m1] )    // Draws a new polygon on map
mapView.annotations.count     // 2
```

**2** Polygons are hiddend after the picker is reloaded
```swift
picker..reloadAllComponents()    // Hides all polygons but not points
mapView.annotations.count     // 2
mapView.removeAnnotation(p1)
mapView.annotations.count     // 1
mapView.addAnnotation(p1)    // Polygon is not displayed still.
mapView.annotations.count     // 2. Polygon is added but not displayed
```

**3** Is it only with the existing polygons? => No. It's with all polygons
```swift
let p2 = MGLPolygon()
mapView.addAnnotation(p2)    // Polygon is not displayed still.
mapView.annotations.count     // 3. Polygon is added but not displayed
```

### Expected behavior
UIPickerView reload shouldn't affect polygon display status.

### Actual behavior
UIPickerView reload hides MGLPolygon objects and cannot display them anymore.

**Comment by 1ec5** [comment]
Can you describe MGLMarker (which isn't a built-in class)? How does it differ from, say, MGLPointAnnotation? Also, what zoom level(s) are the map showing?

**Comment by YoungxHelsinki** [comment]
Sorry about that. It was MGLPointAnnotation() not MGLMarker. Zoom level doesn't affect the issue.

**Comment by 1ec5** [comment]
Ah, OK. In that case, could you provide the full code you're using to create the polygon and point annotation? Perhaps it's something specific to the coordinates you're creating them with?

**Comment by YoungxHelsinki** [comment]
Sorry. I came back from my holiday and I forgot that my old code was deliberately deleting polygons when I touch a UIPicker.

**Comment by 1ec5** [comment]
Good to hear that the mystery is solved!
