### ISSUE TITLE
Adjust CocoaDocs style

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5741]
CocoaDocs generates [its own Mapbox iOS SDK documentation](http://cocoadocs.org/docsets/Mapbox-iOS-SDK/) using appledoc. We don’t have much control over the content, but they do have [options for customizing the look and feel](https://github.com/CocoaPods/cocoadocs.org#what-control-do-i-have-over-cocoadocs-as-a-library-author). We should make the color scheme match the theme we implemented in #5306. We’ll need to put a hidden configuration file in the root of this repository.

/cc @friedbunny @tmcw

**Comment by friedbunny** [comment]
Even better would be if this line in the CocoaDocs readme were true:

> If you host your own documentation, and/or just prefer to not use CocoaDocs you can use the `documentation_url` reference in your Podspec.

We [do this](https://github.com/mapbox/mapbox-gl-native/blob/03ebae0f2ed0e5ff2c4fe284d8d3db8960ae4938/platform/ios/Mapbox-iOS-SDK.podspec#L13), but CocoaDocs still generates its own version of our docs.

**Comment by friedbunny** [comment]
Low priority and blocked upstream — closing.
