### ISSUE TITLE
[Android] Calling selectMarker from MapboxMap doesn't select custom MarkerView

### ISSUE THREAD

**Issue by BharathMG** [mapbox/mapbox-gl-native#5745]
When calling 

mapboxMap.selectMarker(customMarkerView);

It does not set selected state of this Marker. It just calls onMarkerClick event. I need to return views from my Custom MarkerViewAdapter depending on this selection state. Pls help.

**Comment by tobrun** [comment]
@BharathMG 
You need to use the MarkerViewManager for that:
```
mapboxMap.getMarkerViewManager().selectMarker(customMarkerView);
```

We need to route the `selectMarker` to use MarkerView equivalent.

Thank you for reaching out and reporting this issue.

**Comment by BharathMG** [comment]
Thank you!
