### ISSUE TITLE
Rapid calls to IconFactory fromResource causes all marker icons to disappear

### ISSUE THREAD

**Issue by lyptt** [mapbox/mapbox-gl-native#5746]
**Platform:** Android
**Mapbox SDK version:** 4.1.0

### Steps to trigger behavior

 1. Create two buttons, with their click handlers set to update two markers' icons to different drawables
 2. Rapidly alternate between tapping each button

### Expected behavior

The markers update as expected

### Actual behavior

All of the markers on the map disappear

Obviously this is pretty edge-casey, but it seems to happen sometimes apparently at random, so the above steps aren't the only way to reproduce the issue. I assume there's a race condition with the loading of drawables from a resource id for an icon.

In terms of how I'm actually using this, my markers have a 'selected' and 'unselected' image that I switch between in my UI, like so:

```java
marker.setIcon(IconFactory.getInstance(context).fromResource(
    selected ? selectedMarkerDrawableId : markerDrawableId
))
```

This gets triggered directly from UI click handlers. I'm not seeing any exceptions in the logs, so it's hard to pinpoint what the actual issue is. I've verified that this bug does not occur when using the default marker provided by the `defaultMarker()` method call, so it appears that caching the icons could help mitigate the issue.

**Comment by tobrun** [comment]
@lyptt are you using Marker or MarkerView? From the looks of it you are using the former and I would advice you to try out the latter to workaround this issue.

**Comment by lyptt** [comment]
@tobrun I'm using Marker, I'll give MarkerView a go thanks.

**Comment by tobrun** [comment]
This is a known issue with gl markers, we have a workaround for this. Closing.

**Comment by lyptt** [comment]
Yes, from further testing it appears that caching the mabpox icon objects locally resolves this when using standard markers.
