### ISSUE TITLE
Bring marker to front

### ISSUE THREAD

**Issue by lyptt** [mapbox/mapbox-gl-native#5747]
Is there a way to manually adjust the z-order of a marker? 

Currently on Android with v4.1.0 of the SDK if you tap on a marker that's slightly behind another, it remains underneath that marker. It'd be nice if it was possible to bring that marker to the front in response to a click event.

**Comment by tobrun** [comment]
**Re z-order:**
We haven't provided support to expose z-ordering yet of Marker Views, feature request for this in https://github.com/mapbox/mapbox-gl-native/issues/5238.

**Re: select**
This should be normally the case:

```java
   /**
     * Animate a MarkerView to a selected state.
     * <p>
     * The {@link com.mapbox.mapboxsdk.maps.MapboxMap.MarkerViewAdapter#onSelect(MarkerView, View, boolean)} will be called to execute an animation.
     * </p>
     *
     * @param marker      the MarkerView object to select
     * @param convertView the View presentation of the MarkerView
     * @param adapter     the adapter used to adapt the marker to the convertView
     */
    public void select(@NonNull MarkerView marker, View convertView, MapboxMap.MarkerViewAdapter adapter) {
        if (convertView != null) {
            if (adapter.onSelect(marker, convertView, false)) {
                mapboxMap.selectMarker(marker);
            }
            marker.setSelected(true);
            convertView.bringToFront();
        }
    }
```

Could you add some code how you are handling the click event?

**Comment by tobrun** [comment]
Proposed fix to cover all the different ways in #5761, for now if you use MarkerViews with `4.1.0` please use `MarkerViewManager#selectMarker` instead. Reach out if you have any other questions!

**Comment by lyptt** [comment]
@tobrun This is specifically with a normal Marker rather than a MarkerView. I'm not explicitly selecting the marker, I was kind of expecting it to happen automatically in response to the onclick event. I'm guessing I can just call `mapboxMap.getMarkerViewManager().select();` in my click handler to achieve the reordering?

**Comment by EvangelosG** [comment]
Now that markerview is deprecated, how can this be accomplished with MarkerOptions? I'd like the Marker I click to overlay surrounding markers when clicked. I've found myself going in a circle of issues and deprecations looking this one up, any help would be greatly appreciated! Also please do not suggest I utilize the locationlayer plugin, that plugin was causing many of my users signal-11 crashes.

**Comment by tobrun** [comment]
Would suggest using 2 SymbolLayers with a GeoJSON Source. 

You create 2 symbol layers, one that shows the selected state the other that shows the non selected state. You add the selected state above the non selected state when adding them to the map. You create a geojson source with a geojson property "selected". you can reference this property in your filter configuration.

An example using this can be seen [here](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/SymbolLayerMapillaryActivity.java).
