### ISSUE TITLE
Mapbox rotation degree value is missing

### ISSUE THREAD

**Issue by mikemilla** [mapbox/mapbox-gl-native#5750]
Yo, how can I get the value of the current mapView rotation?

**Comment by friedbunny** [comment]
Please use the issue template when reporting issues — that way we know how to properly and efficiently address them.

If you’re using our iOS SDK, [`mapView.direction`](https://www.mapbox.com/ios-sdk/api/3.3.1/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)direction) will get the map’s current rotation.

**Comment by mikemilla** [comment]
It is an issue. 

You have `mapView.allowRotating` and `mapView.direction`. The issue being the naming isn't consistent.

**Comment by 1ec5** [comment]
The properties are named this way for consistency with MapKit. To wit:

* “Rotation” is the two-finger gesture. Rotating with VoiceOver enabled opens the rotor, for example.
* “Direction” is the orientation of the map around the center point along the ground plane. MGLMapView itself only has 2D properties, so consider this the 2D concept. `MGLMapView.direction` is of type `CLLocationDirection`. The naming of that type is outside our control – it’s defined by Core Location.
* “Heading” is the orientation of the map camera along a plane parallel to the ground. MGLMapCamera has a third degree of freedom, `pitch`, so consider this a 3D concept.

**Comment by 1ec5** [comment]
`allowsRotating` is an undocumented property that exists only to enable an “Allows Rotating” inspectable in Interface Builder (matching the name used by MKMapView). If you want to disallow the rotation gesture, use the [`rotateEnabled`](https://www.mapbox.com/ios-sdk/api/3.3.1/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)rotateEnabled) property ([cf. MapKit](https://developer.apple.com/reference/mapkit/mkmapview/1452274-rotateenabled?language=objc)).
