### ISSUE TITLE
offline styleUrl error

### ISSUE THREAD

**Issue by MadeByDouglas** [mapbox/mapbox-gl-native#5751]
so in the example code here https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.3.1/platform/ios/app/MBXOfflinePacksTableViewController.m

on line 25 you set `mapView.styleURL = self.styleURL;` but where does `self.styleURL` come from? I could not find it anywhere and you inherit UITableViewController. (EDIT: Oh i see, you are extending the MGLTilePyramidOfflineRegion essentially with a convenience method, and using the region from the pack to set the mapView how you want.)

Anyways just looking how to setup a mapView that takes cached map data when there is no network and just applies the default style.

right now with no network i get the following errors:
`loading style failed: The Internet connection appears to be offline.`
`Failed to load sprite: The Internet connection appears to be offline.`

which is expected except i want it to then pull from a `MGLOfflineStorage.sharedOfflineStorage()` pack which i have set previously. I suppose what ultimately I am asking is how do i retrieve those packs once i have set them? Also how do I delete them, modify them, see how much space they are taking? (I see basics of how you are adding them and deleting them in tableView, but how do you tell the mapView to use that `MGLOfflineStorage.sharedOfflineStorage()` pack instead of network?)

**Comment by 1ec5** [comment]
If you specify `nil` as the style URL when intializing an MGLTilePyramidOfflineRegion, it’ll use the same default style as MGLMapView does when you don’t explicitly set a style URL.

[This example](https://www.mapbox.com/ios-sdk/examples/offline-pack/) covers the most common things developers do with offline packs, while MBXOfflinePacksTableViewController is a more advanced example for creating a download manager.

MGLMapView automatically uses any offline packs the user has already downloaded – no need to retrieve them yourself. For the purposes of managing existing offline packs, check out the [`MGLOfflineStorage.packs`](https://www.mapbox.com/ios-sdk/api/3.3.1/Classes/MGLOfflineStorage.html#/c:objc(cs)MGLOfflineStorage(py)packs) property (but see the notes in that documentation). To find out the space taken up by an individual pack, see [`MGLOfflinePack.progress`](https://www.mapbox.com/ios-sdk/api/3.3.1/Classes/MGLOfflinePack.html#/c:objc(cs)MGLOfflinePack(py)progress).

**Comment by MadeByDouglas** [comment]
Hmm ok interesting, I will need to do more testing to see it automatically use the cached tiles. Now if I tell MapView to download a region with `addPackForRegion` and its a region i have already downloaded is it smart enough to not download it again, or no? Also does it take up more space now or just overwrite what was there since its the same region?

**Comment by 1ec5** [comment]
Yes, if you add a pack that overlaps an existing pack (with the same style URL), the new pack will automatically reuse any relevant tiles and resources that are already downloaded as part of the existing pack – so no extra downloads. See [this help document](https://www.mapbox.com/help/mobile-offline/) for additional information on offline maps. If you have any further questions, please [contact our Support team](https://www.mapbox.com/contact/), who can better assist you (but feel free to report bugs or request features here in the future).

**Comment by MadeByDouglas** [comment]
ok sure, thanks!
