### ISSUE TITLE
[Qt] Building the Qt SDK for use on iOS and Android

### ISSUE THREAD

**Issue by bernhardHartleb** [mapbox/mapbox-gl-native#5759]
Hello, first of all thank you for supporting Qt! We were able to build and test the Mapbox QML components on x86 Linux quickly with only minor build issues.

The problem started when trying to build the qt-qml-app target for iOS.
It seems that building the qt-lib for iOS is simply not supported yet.

Unfortunately we were not able to add this ourselves, as the build system is quite complex.
My impression is that somebody with better knowledge could accomplish this with moderate effort.

Android was net tested yet, but I think there will be similar issues as on iOS:

- Wrong dependencies in platform/qt/scripts/ configure.sh
- No mason binaries for the nunicode-1.6 dependency and maybe others
- Missing handling for iOS / Xcode / Android NDK in the build system

Please add support for building the Qt SDK on iOS and Android, so that we can integrate Mapbox in our cross-platform applications.

Thanks!

**Comment by friedbunny** [comment]
Hi, @bernhardHartleb! Thanks for your enthusiastic request. For background, you may be interested in reading https://github.com/mapbox/mapbox-gl-native/issues/1286.

Though it may be technically possible to build mobile Qt SDKs, our native iOS and Android SDKs will remain the best way to integrate Mapbox on those platforms.

Maintaining parallel Qt SDKs would be duplicative work that our small team cannot justify. Contributors here already spend a great deal of effort developing and tuning our mobile SDKs, where the vast majority of users will receive the greatest benefit. For similar reasons, we do not officially support Xamarin, Cordova, and other hybrid/pseudo-hybrid frameworks.

All of that said, @brunoabinader and @tmpsantos continue to improve the general Qt build environment: https://github.com/mapbox/mapbox-gl-native/pull/5757 removes nunicode, while the switch to CMake in https://github.com/mapbox/mapbox-gl-native/pull/5359 should make compilation more broadly compatible.

We enjoy tinkering on other platforms and encourage outside developers to do the same. Third-party hybrid support exists and I’m sure we’d be interested to see you or someone else develop and maintain a similar presence on Qt.
