### ISSUE TITLE
Markers are not added at the correct location

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5762]
Adding a gl marker to the map ontap/click just after starting up the map places a marker at the wrong location. See this example gif where it is first placed wrong and second attempt the behaviour is correct.

**Note** that this is a different issue as #5717.

![ezgif com-video-to-gif 49](https://cloud.githubusercontent.com/assets/2151639/17063043/c2912e4c-5035-11e6-955e-635da60acf2a.gif)

**Comment by bleege** [comment]
Was also able to recreate this on the `PressForMarkerActivity` activity this afternoon.

**Comment by bleege** [comment]
Specifically, when I long pressed on `Echirolles` the red default marker instead showed up near `Voreppe`.

![2016-07-23 14_13_17](https://cloud.githubusercontent.com/assets/989928/17079774/a7c584f0-50df-11e6-8368-22c4e3f7b7af.gif)

**Comment by bleege** [comment]
Looking at the `PressForMarkerActivity` code it appears that the issue could be caused in either `MapboxMap.OnMapLongClickListener().onMapLongClick()` or `MapboxMap.getProjection().toScreenLocation()`

![screen shot 2016-07-23 at 2 33 22 pm](https://cloud.githubusercontent.com/assets/989928/17079853/7093c926-50e2-11e6-87b9-749784fdf855.png)

**Comment by bleege** [comment]
Using the `Gare d'Echirolles` as a base test I was able to confirm that the `LatLng` passed into `onMapLongClick()` was accurate at Lat = 45.15834327099316 and Lon = 5.713247070277475.

![screen shot 2016-07-23 at 2 40 29 pm](https://cloud.githubusercontent.com/assets/989928/17079895/84d69462-50e3-11e6-9ed6-a4e51e7dae8c.png)
_Values Returned for Gare d'Echirolles`

![device-2016-07-23-143903](https://cloud.githubusercontent.com/assets/989928/17079888/3d83f56e-50e3-11e6-84d8-b5b7606b22cd.png)
_Gare d'Echirolles Location On Screen_

**Comment by bleege** [comment]
Following the method flow the LatLng on the Marker / MarkerOptions is still correct all the way through the Java portion which ends at `NativeMapView.addMarker()` which calls `NativeMapView.nativeAddMarkers()` to pass the data into Core GL.  The next action is to confirm that the JNI translation from Java to C++ is still good and if so then review the Core GL code.  If it's a Core GL issue then this problem is likely to show up on the other @mapbox/mobile platforms too.

**Comment by bleege** [comment]
At first glance it doesn't look like the jni.cpp's nativeAddMarkers method has changed since 4.1.0 was released.

![screen shot 2016-07-23 at 3 07 54 pm](https://cloud.githubusercontent.com/assets/989928/17080029/42af15ba-50e7-11e6-9a63-09e2e2fd5eda.png)

**Comment by 1ec5** [comment]
Doesn’t reproduce in iOS SDK v3.3.1.

**Comment by BharathMG** [comment]
I guess the PointF being passed to Core GL could be wrong. Will have to test to confirm. I'm debugging this issue now and found that sometimes I'm getting NaN LatLng values from onMapLongClick listener. And sometimes getting weird LatLng values while debugging at this method https://github.com/mapbox/mapbox-gl-native/blame/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java#L922 .

**Comment by BharathMG** [comment]
@bleege I guess here is an issue, https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java#L442 . Should be changed to 

       ` return nativeLatLngForPixel(mNativeMapViewPtr, pixel.x, pixel.y);`


for these changes, https://github.com/mapbox/mapbox-gl-native/issues/5104 . Submitted a PR https://github.com/mapbox/mapbox-gl-native/pull/5776

**Comment by tobrun** [comment]
@BharathMG thank you for contributing, first tests indicate that #5776 resolves the issue!

**Comment by bleege** [comment]
@BharathMG Thanks for tracking down the bug from #5104 and getting things back on track!  Thanks also to @1ec5 for helping us narrow to focus to Android and @tobrun for getting this into `master` ASAP.  👍
