### ISSUE TITLE
add dates to platform changelogs

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#5771]
In doing lots of back reading lately, it would be handy to have dates alongside version numbers in the changelogs. 

Need to also update process docs like https://github.com/mapbox/mapbox-gl-native/wiki/Releasing-the-Mapbox-iOS-SDK to mention this addition.

**Comment by friedbunny** [comment]
This would nice. We could also backfill dates from [the releases page](https://github.com/mapbox/mapbox-gl-native/releases).

**Comment by incanus** [comment]
```bash
for i in `git tag` ; do echo $i; git log $i | sed -n 3p; echo; done
```

💃

**Comment by incanus** [comment]
First cut above. I don't think we need to update any release docs as they generically say things like "update the changelog", which with context has previous releases' dates. 

@mikemorris Do you know where I can find release dates for the older version of the Node bindings, the ones that are missing [here](https://github.com/mapbox/mapbox-gl-native/blob/fbd478d912f69d7dd549bc8e25dbcc57817f542b/platform/node/CHANGELOG.md#113) and below? Can't seem to find the old repo.

**Comment by mikemorris** [comment]
@incanus the old repo was moved to https://github.com/cutting-room-floor/node-mapbox-gl-native, thanks for adding this!
