### ISSUE TITLE
Rethink how JNI and Map interact in lifecycle

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#578]
A careful analysis needs to be made of the interaction between the Android activity lifecycle, GL lifecycle and the way Map handles it.

My code is currently very complex to handle every possible order of calls since it seems to be somewhat chaotic as to what order Android calls things. I also have to work around many problems in getting Map to survive context deletion.

@kkaefer @incanus do you mind reading these to see if you can think of a way to handle it better?:
- [Activity Lifecycle](http://developer.android.com/training/basics/activity-lifecycle/index.html)
- [More detailed activity lifecycle](http://developer.android.com/guide/components/activities.html#Lifecycle)
- [Activity](http://developer.android.com/reference/android/app/Activity.html#ActivityLifecycle)
- [NVIDIA's guide to GL and activity lifecycle](http://developer.download.nvidia.com/assets/mobile/files/AndroidLifecycleAppNote_v100.pdf)
- [More notes from NVIDIA](http://docs.nvidia.com/tegra/Content/Android_Application_Lifecycle_Practice.html)
- [Even more!](http://docs.nvidia.com/gameworks/index.html#technologies/mobile/lifecycle_main.htm)
- [SurfaceHolder callbacks we need to listen to](http://developer.android.com/reference/android/view/SurfaceHolder.Callback.html)

How does the iOS version handle this?

**Comment by ntop001** [comment]
> OK from analysing GLSurfaceView
> I have discovered the secret of setPreserveEGLContextOnPause:
> As long as we have GLES 2.0 we are allowed to have multiple EGL contexts!
> Thus I no longer need to delete (and recreate later) the GL context and state when switching between apps. It should be possible to preserve Map's state by simply pausing the render thread without worrying about the GL objects it is holding becoming invalid.

Very old post, but I just come cross the same question. How did you solve the problem? In the old way, Surface and eglContext are created and destroyed at the same time, so, the glcontext lost. After some research, I found that, I can only destroy Surface when application paused, then create new surface and use the old context when resumed, is that right?
