### ISSUE TITLE
unnecessary performance overhead for non-view annotations on iOS

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#5787]
Looking separately into the perf issues mentioned in https://github.com/mapbox/mapbox-gl-native/pull/5786, it seems that `-[MGLMapView updateAnnotationViews]` is called as a result of `-[MGLMapView notifyMapChange]`. This appears to run through every annotation on every frame update, doing unnecessary logic for annotations which are sprite-backed. In my testing of an entirely sprite-backed map, I am getting about 16% of time profiling spent on rendering the whole map and _the same amount_ just to run through `-[MGLMapView convertCoordinate:toPointToView:]` when this is completely unnecessary for thousands of annotations. 

![screen shot 2016-07-25 at 12 00 44 pm](https://cloud.githubusercontent.com/assets/17722/17113391/72187aac-525f-11e6-99f7-9f64bc2c2604.png)

/cc @1ec5 @boundsj

**Comment by 1ec5** [comment]
`-updateAnnotationViews` iterates over all the annotations, not just view-backed annotations and not just the annotations within the viewport. #5165 would provide a more reliable way to query for annotations in the current viewport than what we have now. Moving over to that new API should eliminate all the coordinate conversions when none of the annotations are view-backed.

**Comment by incanus** [comment]
Ah nice, good that we're tracking this already. Will leave this open as a todo. 👍
