### ISSUE TITLE
No Windows Build Configuration

### ISSUE THREAD

**Issue by longlostbro** [mapbox/mapbox-gl-native#5789]
**Platform:** Windows
Is there a build configuration for Windows Desktop or an alternative library?

**Comment by friedbunny** [comment]
We don’t currently support compiling on or for Windows platforms, though it may be technically possible. There aren’t any plans to actively implement support, but we’re always improving the build system. See also: #1421

Incidentally, @longlostbro, what would you want to do with a hypothetical Windows SDK?

**Comment by 1ec5** [comment]
Another option, if you’re developing a Windows desktop application or unified Windows app, is to embed [Mapbox GL JS](https://www.mapbox.com/mapbox-gl-js/) in a Web browser control.

**Comment by longlostbro** [comment]
@friedbunny I am working on an offline maps solutions for a C# wpf Desktop Application, using vector tiles. @1ec5 I was successfull in embedding Mapbox GL JS but my employer would like a solution that doesn't require Node JS. If I could get it to compile for windows then I could work on a CLR port that would make it accessible to my C# application. Otherwise it seems my only option is to do a full port to C#.

**Comment by 1ec5** [comment]
As far as C# is concerned, there is a community-maintained C# wrapper around the Android and iOS SDKs for the Xamarin environment. But at a glance, it seems like the challenge beyond getting the build system to work is that Mapbox GL relies on OpenGL (or OpenGL ES or WebGL) for graphics; you'd need to ensure a smooth translation to DirectX.

As for GL JS, I'm not sure I understand – are you using Node to power the map itself inside the client, or to serve up vector tiles to GL JS? If Node itself is the problem, perhaps there's a solution that doesn't require a full port of the native library.

**Comment by longlostbro** [comment]
Actually I misspoke. I haven't used GL JS, instead I used [tileserver-mapnik](https://github.com/klokantech/tileserver-mapnik). What is the solutions that you suggest that doesn't require a full port? (I am trying to serve vector-tiles from an mbtiles file to a WPF map control, which I am currently able to do, but the styling is slow and inaccurate)

**Comment by mb12** [comment]
@1ec5 GL JS feels  extreeeemely slow esp on phones and tablets. For eg try out this sample on a tablet. For this sample, it gets  slow to the point of being unusable when one tries to zoom out or pan after zoom out.

https://www.mapbox.com/mapbox-gl-js/example/set-perspective/

**Comment by longlostbro** [comment]
That's acceptable. My implementation is very rudimentary, with labels not functioning correctly at all and still takes about 2 whole minutes to load.
![image](https://cloud.githubusercontent.com/assets/5777927/17143038/61ee5b82-530f-11e6-9d4b-dda5a95fe364.png)

**Comment by 1ec5** [comment]
@mb12, I'm aware of that; that's why this project exists. The original question here is about Windows support, presumably for desktops.

**Comment by tmpsantos** [comment]
Mapbox Qt has now a MSVC Win64 build https://ci.appveyor.com/project/Mapbox/mapbox-gl-native/build/54/artifacts
