### ISSUE TITLE
Load map resources from local assets

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#579]
Currently takes the app a second or two to load.

This is due to extracting the asset folder from APK.

Need to make this faster, get rid of it (by reading directly from APK), or only do it once at install time (can hook this), or only if the files are not there.

TODO: more detail on this so you guys understand what I am talking about

**Comment by ljbade** [comment]
@kkaefer So where did this get to? I think Android was done right?

**Comment by kkaefer** [comment]
This is implemented in other systems as well. OS X  and iPhone bundles load data from the resources folder, Linux builds well load assets relative to the binary's location
