### ISSUE TITLE
How do you get `MGLUserLocationAnnotationView`?

### ISSUE THREAD

**Issue by mikemilla** [mapbox/mapbox-gl-native#5790]
Not only does this view lay on top of all other markers (which is incorrect for my use), but it's ring (The blue radius around it) steals the touch event for the markers within the radius.

How can I disable the view's interaction?

Bonus: How can I place the view above all other annotations?

**Comment by 1ec5** [comment]
> it's ring (The blue radius around it) steals the touch event for the markers within the radius.

This is being tracked in #5571. It’s on the v3.4.0 milestone right now, but I’m hoping to pull it into a v3.3.2 bugfix release if we can find a low-risk fix.

> How do you get `MGLUserLocationAnnotationView`?
> How can I disable the view's interaction?

Unfortunately, it isn’t possible to get the view directly via publicly documented APIs. We’ve got a fix for #5039 baking in #5573.

In the meantime, assuming you’re using MGLAnnotationViews, one workaround would be to find the view within MGLMapView’s view hierarchy and send it below the container view that holds your annotation views. (It isn’t possible to display the user location annotation view beneath MGLAnnotationImages.)

Another option, which won’t be forwards-compatible, would be to use KVO: [`(UIView *)[mapView valueForKey:@"userLocationAnnotationView"]`](https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.3.1/platform/ios/src/MGLMapView.mm#L238). Even if you don’t have access to all of MGLUserLocationAnnotationView’s members, you could disable interaction with it by setting its `userInteractionEnabled` property.

These are all kludges, of course, and they’ll be completely unnecessary once #5573 lands in v3.4.0.

> How can I place the view above all other annotations?

If you have a reference to the annotation view you want to send to the front:

```objc
[annotationView.superview bringSubviewToFront:annotationView];
```

**Comment by mikemilla** [comment]
@1ec5 Thanks. How can I use the `valueForKey`? When I try `mapView.valueForKey("userLocationAnnotationView")` I get an error that say `-[MGLUserLocationAnnotationView swizzledDescription]: unrecognized selector sent to instance 0x140180580`

**Comment by 1ec5** [comment]
I'm unfamiliar with swizzledDescription, but I'm guessing that exception is masking another one that may mean the KVO approach won't work in Swift. Another way to accomplish this might be to extend MGLMapView in your Objective-C bridging header to declare a userLocationAnnotationView method, then call that method in Swift.
