### ISSUE TITLE
Query all features in sources (querySourceFeatures)

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#5792]
Breaking out porting `querySourceFeatures` from JS land separate from the all-encompassing ticket https://github.com/mapbox/mapbox-gl-native/issues/352. 
- Larger PR bringing it to JS: https://github.com/mapbox/mapbox-gl-js/pull/2224
- JS API docs: https://www.mapbox.com/mapbox-gl-js/api/#Map#querySourceFeatures

**Comment by cammace** [comment]
My understanding of this method is that it is needed so we can get the complete feature information query by feature ID. Currently this is happening:

![ezgif com-video-to-gif 5](https://cloud.githubusercontent.com/assets/5652865/17716732/ef5990a8-63d7-11e6-91ea-2cc5c15ac2fd.gif)

cc: @mapbox/android

**Comment by tobrun** [comment]
@cammace that is a separate issue about rendered features and unrelated to source features. I created a follow up ticket in https://github.com/mapbox/mapbox-gl-native/issues/6044.

**Comment by zugaldia** [comment]
@cammace @tobrun Cool if we close this in favor of #6044 then?

**Comment by tobrun** [comment]
@zugaldia, this feature still needs to be implemented ;)

**Comment by zugaldia** [comment]
@tobrun Oops, I mistakenly took @cammace's comment in https://github.com/mapbox/mapbox-gl-native/issues/5792#issuecomment-240250580 as OP. I said nothing :)
