### ISSUE TITLE
black square before map render

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#5795]
Haven't been able to confirm on Android yet, but I see this almost every time on iOS. 

Just before the map appears, a black square smaller than the map view shows up. 

![anigif-1469496685](https://cloud.githubusercontent.com/assets/17722/17123107/1ed426d4-5296-11e6-8784-0ce6649f5d2f.gif)

**Comment by tobrun** [comment]
Verified that I'm not seeing this on Android. 
Start up frame-by-frame:

![ezgif com-video-to-gif 52](https://cloud.githubusercontent.com/assets/2151639/17132193/f0b18b3a-5320-11e6-8ad3-7166966de010.gif)

idk but could be related to drawing before setting up the view correctly (related to glViewport or mbgl::Update::Dimensions?).

**Comment by friedbunny** [comment]
My guess is that this has to do with the storyboard initialization.

**Comment by friedbunny** [comment]
Setting `MGLMapView.opaque = NO` fixes the initial black flash — indeed, this issue (https://github.com/mapbox/mapbox-gl-native/issues/3101) was the impetus for implementing `opaque`.

One idea I bounced off of @1ec5 was to set `opaque = NO` until `mapDidFinishLoading` fires, but that would have likely performance implications and complicate the situation where developers wanted to keep `opaque = NO` enabled themselves.

**Comment by friedbunny** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/7859 for most use cases.
