### ISSUE TITLE
MapboxEventManager SSL error

### ISSUE THREAD

**Issue by TostF** [mapbox/mapbox-gl-native#5797]
My maps are not loading on Samsung Galaxy S4. On Galaxy S7 everything works fine.
Error: 

    E/MapboxEventManager: FlushTheEventsTask borked: javax.net.ssl.SSLPeerUnverifiedException:
    Filed to find a trusted cert that signed X.509 Certificate: 
    [
    [
           Version: V3
           Subject: CN=DigiCert SHA2 Extended Validation
           Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US
           Signature Algorithm: SHA256WithRSA, params
           unparsed, OID = 1.2.840.113549.1.1.11
           Key: OpenSSLRSAPublicKey{modulus={I'VE
           REMOVED KEY THAT WAS HERE},publicExponent=10001}
           Validity: [From: Tue Oct 22 14:00:00 CEST 2013
           To: Sun Oct 22 14:00:00 CEST 2028]
           Issuer: CN=DigiCert High Assurance EV Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
           Serial Number: 16582437038678467094619379592629788035
           Extensions: ...                                                                                     
                                                                                      
**Platform:** Android 4.3 
**Mapbox SDK version:** 4.1.1@aar

### Expected behavior

Map appearing.

### Actual behavior

Gray area instead of a map.

**Comment by tobrun** [comment]
Removing `telemetry` tag, as I now see it's related to map loading which is different with the shown logcat output (but will have the same root issue).

**Comment by tobrun** [comment]
```java
10-07 13:09:13.570 28478-29399/com.mapbox.mapboxsdk.testapp E/MapboxEventManager: FlushTheEventsTask borked: javax.net.ssl.SSLPeerUnverifiedException: Certificate pinning failure!
                                                                                    Peer certificate chain:
                                                                                      sha256/3euxrJOrEZI15R4104UsiAkDqe007EPyZ6eTL/XxdAY=: CN=*.tilestream.net,O=Mapbox Inc.,L=Washington,ST=District of Columbia,C=US
                                                                                      sha256/5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=: CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US
                                                                                      sha256/r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E=: CN=DigiCert Global Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
                                                                                    Pinned certificates for cloudfront-staging.tilestream.net:
                                                                                      sha256/kR9ysyN/lzBl/ecearDERV7qO7xqSN4jt6XuQjIVL0I=
                                                                                      sha256/sPbNCVpVasMJxps3IqFfLTRKkVnRCLrTlZVc5kspqlkw
                                                                                      sha256/h6801m+z8v3zbgkRHpq6L29Esgfzhj89C1SyUCOQmqU=
```

**Comment by tobrun** [comment]
Capturing what I was able to identify:
 - The pinning is failing on the certificate from staging env.
 - Certificates from all envs are pinned (it should only check the current configured applicable env.).

@mick Any idea what is wrong with certificate from staging?

cc @l-r

**Comment by mick** [comment]
@tobrun We did recently update the cert because it expired on staging so we'll need to update the pinning. The staging endpoint should only be used in testing the sdk, and shouldnt impact map loading during testing or in a released version.  Unclear if that is causing the issue here, or if this error message is happening in addition to some other issue.

**Comment by zugaldia** [comment]
> Certificates from all envs are pinned (it should only check the current configured applicable env.).

Yep - from [looking at the code](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/telemetry/MapboxEventManager.java#L718-L731), the `CertificatePinner` object is unnecessarily including all stages for all requests.

> We did recently update the cert because it expired on staging so we'll need to update the pinning.

Right. Per chat with @mick the `sha256` value changed when the certificate was updated and we need to reflect that change in the code linked above. This is likely what we're seeing here.

**Comment by tobrun** [comment]
#6766 got merged, closing!
