### ISSUE TITLE
[android] getMarkerViewsInBounds() returns all the marker views irrespective of LatLngBounds

### ISSUE THREAD

**Issue by BharathMG** [mapbox/mapbox-gl-native#5799]
getMarkerViewsInBounds() method returns all the MarkerView annotations irrespective of LatLngBounds being passed. 

I need to do markerHitTest to see if a user tapped point falls on any MarkerView. Because of getting all MarkerViews, I cannot use this method.

P.S :  This also causes invalidateViewMarkersInBounds() not do anything as the above method will always return all the MarkerViews. But I can see the `contains` check was intentionally removed to fix #5402 .

cc @tobrun  Looks like I have to wait till #4522 is resolved ?
### Steps to trigger behavior
1. Ask getMarkerViewsInBounds(latLngBounds);
2. All MarkerViews are returned even if they are outside bounds.
### Expected behavior
1. Only MarkerViews within bounds should be returned
### Actual behavior
1. All MarkerViews are returned even if they are outside bounds.

**Comment by cammace** [comment]
We've removed `getMarkerViewsInBounds()` in the `4.2.0`. Two solutions for this could be using the new query map features introduced (see https://github.com/mapbox/mapbox-gl-native/pull/5165) or a better option might be using the [Turf inside method](https://github.com/mapbox/mapbox-java/blob/master/libandroid/app/src/main/java/com/mapbox/services/android/testapp/turf/TurfInsideActivity.java#L122) found in mapbox-java (also included in the maps SDK).
