### ISSUE TITLE
iOS MGLOfflineRegions size is very huge for small regions 

### ISSUE THREAD

**Issue by Gurbo** [mapbox/mapbox-gl-native#5803]
Hi everyone! I'm trying to download map regions to use them in offline (iOS 9.3) and have some problems with it. So, If i try to download a small region (default Mapbox Streets style, 200 х 200 meters in real life, the zoom level from 18 to 20) - the downloading pack is about 1284 resources and 73.6 mb (i think it is very huge size for a small region on the map). If i try to download a big region (such as a city of Barcelona) - the download pack is about 83mb. I thought that the problem was in my code - so i clone the source code from this repository and launched iOS test application - and it gave the same result as mine. I tried to download packs with different settings - min/max zoom level, bounds coordinates - but everytime **the result download pack was not less than 70mb**. Can you explain me what am I doing wrong? Thanks!

**Comment by friedbunny** [comment]
This question was already answered in #5487. This is the expected behavior, currently — the first offline download will include additional resources necessary to render that map offline, including fonts and sprites.

**Comment by Gurbo** [comment]
@friedbunny so may be you can help me - how can i handle downloading process (for example, i want to show download progress) and show REAL size of download pack? (and remaining download size)? Thanks!
