### ISSUE TITLE
Raster layers with fixed extents appear on all zooms

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-native#5811]
I have a map style that adds a raster layer between `z14 - z22` 

<img width="1280" alt="372e822a-5344-11e6-921e-184b4b8284de" src="https://cloud.githubusercontent.com/assets/61150/17184107/9217f8e2-53f8-11e6-873b-e638beecd34d.png">

But the output from our Static API and on native displays the raster layer at all zoom levels.

**Comment by tmpsantos** [comment]
@tristen can you give us the link to the original style or style "testcase reduction" that we could use to reproduce the bug?

**Comment by tristen** [comment]
Sure thing! Here's a link to a style that uses Streets + Satellite. I have set the extents of the satellite raster to `z10 - z22`: https://api.mapbox.com/styles/v1/tristen/cir5cblqw0018bom4rraa321m.html?fresh=true&title=true&access_token=pk.eyJ1IjoidHJpc3RlbiIsImEiOiJiUzBYOEJzIn0.VyXs9qNWgTfABLzSI3YcrQ#3.68/41.81/-85.13

You can see it works fine in gl-js but as raster fallback it looks like this:
https://api.mapbox.com/styles/v1/tristen/cir5cblqw0018bom4rraa321m.html?fallback=true&title=true&access_token=pk.eyJ1IjoidHJpc3RlbiIsImEiOiJiUzBYOEJzIn0.VyXs9qNWgTfABLzSI3YcrQ#3.68/41.81/-85.13

And here's a screenshot of it on mobile:

![img_0476](https://cloud.githubusercontent.com/assets/61150/17191379/bba4eed0-5417-11e6-9846-48e10d2e51cb.PNG)

**Comment by tmpsantos** [comment]
On it.

**Comment by tmpsantos** [comment]
Have a fix, working on tests cases to validate the fix.

**Comment by tmpsantos** [comment]
![out](https://cloud.githubusercontent.com/assets/996307/17251072/ea5a71b6-55af-11e6-8974-b3173688fcab.gif)
