### ISSUE TITLE
[iOS] How to calculate REAL size of downloading offline map pack?

### ISSUE THREAD

**Issue by Gurbo** [mapbox/mapbox-gl-native#5817]
Hi! I have such case: after the first downloaded map offline-pack (it is usually about 70mb) - subsequent downloads are also report their total size about 70mb as including extra resources. But their real size is not 70mb - for the small region it is about 0.2mb. So the question is: how can I calculate the real downloading size of oflline map pack? Here you can see similar issue: https://github.com/mapbox/mapbox-gl-native/issues/5803 Thanks!

**Comment by 1ec5** [comment]
Given that overlapping offline packs share resources among themselves, do you want only the additional size incurred by the pack? I don't think we have any support for that.

On the other hand, it sounds like you may be trying to determine the overall space used up by offline downloads. In that case, [`-[MGLOfflineStorage countOfBytesCompleted]`](https://www.mapbox.com/ios-sdk/api/3.3.1/Classes/MGLOfflineStorage.html#/c:objc(cs)MGLOfflineStorage(py)countOfBytesCompleted) may be what you're looking for.

**Comment by jfirebaugh** [comment]
Even "the additional size incurred by the pack" is an ambiguous measure. Does it mean the additional size incurred at the time the pack was created, even if subsequent packs share these additional resources? Or the size of the resources in the offline pack not in use by any other pack? This would be an expensive calculation, and doesn't strike me as particularly informative.
