### ISSUE TITLE
Thread safety of sqlite usage?

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#582]
Did this change recently? Seeing `mapbox::sqlite::Exception "database is locked"` downstream in multi-threaded use.

/cc @mapbox/gl

**Comment by robipresotto** [comment]
if you dismiss the view with map view and reopen it the sql crash!
throw std::runtime_error("failed to run statement");
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: failed to run statement

**Comment by jfirebaugh** [comment]
@robipresotto Can you please open a new issue? A comment on a closed issue such as this is likely to get lost.

**Comment by robipresotto** [comment]
Okay, here we go!! 
https://github.com/mapbox/mapbox-gl-native/issues/1071
