### ISSUE TITLE
Offline region download hits Mapbox API rate limits for sprites

### ISSUE THREAD

**Issue by dpieri** [mapbox/mapbox-gl-native#5821]
**Platform:** Android
**Mapbox SDK version:** 4.1.0

### Steps to trigger behavior

 1. Create a new offline region of any size using a style that relies on Mapbox-hosted sprites and tilesets.
 2. Start downloading it.
 3. Watch for error message `Failed to load sprite: HTTP status code 429`

### Expected behavior
SDK does not trigger API rate limits.

### Actual behavior
Sometimes, but not always, you see the 429 response, which must mean that the SDK is kicking off requests faster than the API allows.

### Question
We are killing the offline download whenever an error occurs. For errors like this, does the SDK retry downloading the asset after reporting the 429 response, or is killing on the first error the correct way to handle them?

**Comment by 1ec5** [comment]
I’m seeing the same thing on iOS, and it’s leading to a crash: #5827.

**Comment by 1ec5** [comment]
As a temporary measure, we’ve increased the rate limit on non-tile resources (including sprites) on the server side.

**Comment by jfirebaugh** [comment]
Currently, a 429 response produces a `response.error` value of [`Error::Reason::Other`](https://github.com/mapbox/mapbox-gl-native/blob/e1a6795a73af844ff63d99b35fb4695177d9494d/platform/darwin/src/http_file_source.mm#L301-L303), which is [not retried](https://github.com/mapbox/mapbox-gl-native/blob/e1a6795a73af844ff63d99b35fb4695177d9494d/platform/default/online_file_source.cpp#L212-L213).

We need to add an enumeration value to `Response::Error::Reason` representing a rate-limiting situation, include the value of any `Retry-After` response header somewhere (with a fallback to the non-standard [`x-rate-limit-reset` header used by Mapbox APIs](https://www.mapbox.com/api-documentation/#rate-limits)), and handle this situation in `OnlineFileRequest` by retrying according to the specified `Retry-After` value or a reasonable default.
