### ISSUE TITLE
`text-allow-overlap` isn't correctly set on zoom functions

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-native#5823]
I have the following properties set for [`text-allow-overlap`](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-text-allow-overlap):

```json
"text-allow-overlap": {
  "base": 1,
  "stops": [
    [0, false],
    [10, true]
  ]
}
```

But if I test the published style natively on iOS at lower zooms where overlap should _not_ be set it's appearing:

![img_0484](https://cloud.githubusercontent.com/assets/61150/17233042/a0d613fc-54fa-11e6-8a0c-6290e35630e7.PNG)

See: __mapbox://styles/tristen/cir6y946p0000g8m7jvp8ucfe__ for reference.

**Comment by jfirebaugh** [comment]
Fixed in #6328.
