### ISSUE TITLE
Dynamically change line width of MGLPolyline

### ISSUE THREAD

**Issue by iBinh** [mapbox/mapbox-gl-native#5835]
I call the delegate `mapView:lineWidthForPolylineAnnotation:` in `regionDidChangeAnimated`
When the mapZoom changed I return a float value for polyline width but it not changed.

**Comment by 1ec5** [comment]
It isn’t currently possible to vary the line width, color, etc. of an MGLPolyline or MGLPolygon after adding it to the map. One option is for your MGLMapViewDelegate to implement `-mapView:regionDidChangeAnimated:` to remove and re-add the polyline.

If the polyline’s shape doesn’t change and you always want it to be visible, another option is to use a custom style that includes a GeoJSON layer. In Mapbox Studio, upload the GeoJSON to your account, then add a layer that uses the uploaded GeoJSON. In Studio, you can style the line width to vary by zoom level. Then, after publishing the style, you can use it with the SDK.

In #5626, we’re working on a runtime styling API that will make it possible to add and style a GeoJSON layer directly inside the SDK, without requiring a custom style from Mapbox Studio. MGLPolyline will remain separate from that API, but we should expose a way to dynamically change the width of a polyline, for parity with MapKit’s `MKOverlayPathRenderer.lineWidth` property.

**Comment by makinggainz** [comment]
Is this still true?
