### ISSUE TITLE
[docs][android] Feature — add support for OS X Dash similar to Mapbox iOS.

### ISSUE THREAD

**Issue by roblabs** [mapbox/mapbox-gl-native#5837]
**Feature request — add Dash support for Mapbox Android SDK** 

As an Android Developer on macOS, [Dash](https://kapeli.com/dash) is a great tool for offline caching and searching documentation.  The [Mapbox iOS SDK](https://www.mapbox.com/ios-sdk/api/3.3.3/index.html) has a way to install dash directly from mapbox.com

![ios-dash](https://cloud.githubusercontent.com/assets/118112/17278624/2865c340-5716-11e6-98a4-6a1f44abe3a9.png)

---

Clearly a low priority issue, as it benefits Android developers on macOS.
- [ ] add Dash support for Mapbox Android SDK
- [ ] Add link for Dash at https://www.mapbox.com/android-sdk/api/4.x.x
- [ ] Will also need to update the Dash icon to distinguish between Mapbox iOS & Mapbox Android SDK's
## ![dash](https://cloud.githubusercontent.com/assets/118112/17278659/ead593d8-5716-11e6-8b13-a036fc9e57ce.png)

Some `mapbox-gl-native` discussion on Dash and docs, in general
- #5306 — side discussion on making [Mapbox iOS SDK discoverable in Dash](https://github.com/mapbox/mapbox-gl-native/pull/5306#issuecomment-225079938)
- #3954 — Dash discussion
- #5226 — discussion on improving Android Docs

**Comment by friedbunny** [comment]
This is a feature that we get for free by using [jazzy](https://github.com/realm/jazzy) to generate our iOS documentation. Android uses javadoc/doclava (https://github.com/mapbox/mapbox-gl-native/pull/5337), which offer no such convenience by default.

It looks like a tool exists to generate dash docsets, though: https://github.com/Kapeli/javadocset

**Comment by tobrun** [comment]
IMHO Dash isn't a popular tool among the Android developers community. Since implementing and maintaining such a solution would require bandwith from the android team, I'm going to close this feature request for the time being and revisit if a need for this would arise.
