### ISSUE TITLE
showAnnotations with completion handler

### ISSUE THREAD

**Issue by Gerz-inc** [mapbox/mapbox-gl-native#5839]
**Platform:** iOS

Will be cool add to this method - completion handler
- (void)showAnnotations:(NS_ARRAY_OF(id <MGLAnnotation>) *)annotations animated:(BOOL)animated;

**Comment by 1ec5** [comment]
Great idea. There are some other methods as well that could benefit from completion handlers (#5840).

**Comment by 1ec5** [comment]
For completeness after implementing #5840.
