### ISSUE TITLE
Create test for TileJson from json file

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#5851]
To show off the tilejson loading in the runtime style api, add an example where the tilejson file is loaded with gson and added to a Source.

Atm there is one example where it's done programatically in the [test app](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RuntimeStyleActivity.java#L342)

**Comment by zugaldia** [comment]
@ivovandongen Does this need to be a core GL or SDK level test?

**Comment by ivovandongen** [comment]
@zugaldia An SDK Level test so that the bindings are exercised.
