### ISSUE TITLE
Add clustering support to GeoJson source

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#5852]
Since starting on the android runtime style api #5610, Clustering support has been brought to core by @mourner in #5724.

Add support for it in the Android binding and a [sample](https://www.mapbox.com/mapbox-gl-js/example/cluster/) in the test app.

**Comment by ivovandongen** [comment]
Initial clustering support. Filters don't have the right effect yet (circles don't appear at all when filters are set).

**Comment by 1ec5** [comment]
#5962 tracks the iOS/macOS equivalent to this work.

**Comment by ivovandongen** [comment]
Fix in https://github.com/mapbox/mapbox-gl-native/issues/5978 also fixed filtering on geojson sources. Separated the test in a new activity for clarity.

cc @mourner

**Comment by ivovandongen** [comment]
![geojson-clustering](https://cloud.githubusercontent.com/assets/64527/17643988/a180b492-6148-11e6-95fe-d99cda8f0b36.gif)

**Comment by ivovandongen** [comment]
Merged
