### ISSUE TITLE
Registry returned 404 for GET on https://registry.npmjs.org/mapbox-gl-test-suite

### ISSUE THREAD

**Issue by momin96** [mapbox/mapbox-gl-native#5866]
Hi I clone the latest code from release-ios-v3.3.0. I want Build the SDK and followed
[Building the SDK](https://github.com/mapbox/mapbox-gl-native/blob/e9dcfa0ed627ecb8783d1ac7f38a24db51cf8cb8/platform/ios/DEVELOPING.md#building-the-sdkl)

But when use 

`make ipackage`
or
`make iproj`

I get below result.
**Platform: OS X 10.11.2**
**Mapbox SDK version: release-ios-v3.3.0**

### Expected behavior
as described in INSTALL.md or [Building the SDK](https://github.com/mapbox/mapbox-gl-native/blob/e9dcfa0ed627ecb8783d1ac7f38a24db51cf8cb8/platform/ios/DEVELOPING.md#building-the-sdkl)

### Actual behavior
./scripts/export-xcconfig.py build/ios/config.gypi build/ios/mbgl.xcconfig
npm update # Install dependencies but don't run our own install script.
mapbox-gl-style-spec@8.8.0 node_modules/mapbox-gl-style-spec
├── minimist@0.0.8
├── rw@0.1.4
├── sort-object@0.3.2 (sort-desc@0.1.1, sort-asc@0.1.0)
├── lodash.isequal@3.0.4 (lodash._bindcallback@3.0.1, lodash._baseisequal@3.0.7)
└── jsonlint-lines-primitives@1.6.0 (JSV@4.0.2, nomnom@1.8.1)
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/mapbox-gl-test-suite
npm ERR! 404 
npm ERR! 404 'mapbox-gl-test-suite' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'mapbox-gl-native'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Nasir/Music/mapbox/mapbox-gl-native/npm-debug.log
make: *** [node_modules] Error 1

and one more same error is 

Registry returned 404 for GET on https://registry.npmjs.org/mapbox-gl-shaders

Any idea will be helpful.
Thanks.

**Comment by mikemorris** [comment]
Huh, both of those packages should be installed [directly from GitHub](https://github.com/mapbox/mapbox-gl-native/blob/release-ios-v3.3.0/package.json#L24-L26), so `npm update` shouldn't be attempting to download them from the npm repository. I just tried `make distclean && make iproj` on the `release-ios-v3.3.0` branch with Node.js v4.4.7/npm v2.15.8 (same as you) and it worked as expected for me.
