### ISSUE TITLE
Offline example should use a backwards compatible ProgressBar style

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5867]
In `activity_offline.xml`:

<img width="718" alt="screen shot 2016-08-04 at 10 01 37" src="https://cloud.githubusercontent.com/assets/2151639/17404662/8a9183e4-5a2a-11e6-9b0d-9064555ae31d.png">

**Comment by jingsam** [comment]
Repalece it with @android:style/Widget.DeviceDefault.ProgressBar.Horizontal

**Comment by zugaldia** [comment]
Fixed via https://github.com/mapbox/mapbox-gl-native/issues/5929.
