### ISSUE TITLE
E/emuglGLESv2_enc: a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute.

### ISSUE THREAD

**Issue by saadfarooq** [mapbox/mapbox-gl-native#5868]
I'm getting the subject error when doing a camera update. This is with 4.1.1.

I'm still looking into what exactly might be causing the error, or warning I should say. It doesn't really seem to effect functionality at all. But if someone knows more about this problem, it would be great to know. I should also say that it appears like a gazillion times in the log, which is the really annoying part of this warning.

**Comment by cammace** [comment]
Could you test this on `4.2.0-beta.4` or using the SNAPSHOT and see if you are still getting the same output? If so any additional information would help. I haven't seen this.
