### ISSUE TITLE
Visible Feature querying

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#5869]
This ticket is the android implementation of #352 or query rendered features. 

In order to implement this we need to lay some groundwork, mostly because we already have a full geometry implementation in https://github.com/mapbox/mapbox-java/ that we will want to re-use. At first we resisted adding MAS as a dependency since it currently has a dependency on rxjava, which is quite big. However, work is underway as we speak to remove that dependency in: https://github.com/mapbox/mapbox-java/issues/131.

This implementation will add methods to query the layers currently rendered (or a subset of layers) and retrieve the GeoJson Features present either for a point or area.

**Comment by ivovandongen** [comment]
Little update: Initial querying is done:
- point query -> returns features, incl:
    - id
    - properties as JsonObjects
    - geometry as MAS GeoJson types

Todo:
- [ ] box query - much re-use
- [ ] update mas to new snapshot
- [ ] Opimization: use primitive double arrays instead of typed objects from jni


Beside the above. Do we need any other conversions from/to geojson in the sdk? 

cc @zugaldia

**Comment by zugaldia** [comment]
@ivovandongen Love it.

I can take care of the latest two items in that checklist.

**Comment by ivovandongen** [comment]
@zugaldia @cammace prepared the second item on https://github.com/mapbox/mapbox-gl-native/pull/5927

If you don't mind picking up https://github.com/mapbox/mapbox-java/issues/171 that would be great!

**Comment by zugaldia** [comment]
@ivovandongen https://github.com/mapbox/mapbox-java/issues/171 ✅

**Comment by ivovandongen** [comment]
Squashed: https://github.com/mapbox/mapbox-gl-native/pull/6012

Needs some testing on older devices to make sure were not using top many local references in conversion.

**Comment by ivovandongen** [comment]
![highlight-buildings](https://cloud.githubusercontent.com/assets/64527/17667643/febd3ebe-6305-11e6-8a2c-223c7ebbf0c6.gif)

**Comment by ivovandongen** [comment]
Merged

**Comment by mkv123** [comment]
@ivovandongen: Is it intentional that using this feature requires pulling in mapbox services as a new dependancy? Or is there a plan/ticket to move the geojson classes this feature requires into the normal mapbox sdk?

**Comment by ivovandongen** [comment]
@mkv123 Yes, this is intentional. If you're worried about apk size, proguard has you covered.
