### ISSUE TITLE
Cache shaders

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#588]
We should use [GL_ARB_get_program_binary](https://www.opengl.org/registry/specs/ARB/get_program_binary.txt) and [GL_OES_get_program_binary](https://www.khronos.org/registry/gles/extensions/OES/OES_get_program_binary.txt) if available to cache the compiled shaders so a subsequent launch is a lot faster.

**Comment by ljbade** [comment]
We decided to remove this due to many issues with it. https://github.com/mapbox/mapbox-gl-native/pull/778
