### ISSUE TITLE
Javadoc gradle task output

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5880]
When you execute the gradle task `javadocrelease`, you will output containing errors/warnings.

<img width="1311" alt="screen shot 2016-08-05 at 17 35 58" src="https://cloud.githubusercontent.com/assets/2151639/17451244/5e20c018-5b33-11e6-9e23-c595eb231d41.png">

Thank you @cammace for running point on this.

**Comment by tobrun** [comment]
The errors should be resolved already with the release of beta.1 in #5871

**Comment by tobrun** [comment]
A part of this is handled in #5880. We will need a couple more cleanups before we can close.
We should look into making this part of our Checkstyle to prevent regressions. 

cc @zugaldia

**Comment by tobrun** [comment]
Warnings have been resolved, in #5912, we just need to revisit the public javadoc when we are going to release 4.2.0 but this is normal way of working and doesn't require this ticket anymore. closing.

**Comment by zugaldia** [comment]
@tobrun I'll make sure this is in our release checklist, thanks for taking care of it.
