### ISSUE TITLE
Test app: Dynamic marker example broken

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#5889]
The dynamic marker example shows that the info windwo position is not always correctly updated. See screenshot.
![screenshot_20160806-131852](https://cloud.githubusercontent.com/assets/64527/17458418/62662320-5bdd-11e6-91b8-42a676cb27b2.png)

**Comment by tobrun** [comment]
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/2151639/17528869/12461026-5e3f-11e6-9a66-f8e43820aae7.gif)
