### ISSUE TITLE
Test app: Geocoder example broken

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#5890]
The button doesn't react and nothing happens.

**Comment by tobrun** [comment]
@cammace is upgrading MAS in #5927. Good to close when this lands?

**Comment by cammace** [comment]
Tested using MAS 2.0-SNAPSHOT and had no issues.

**Comment by tobrun** [comment]
![gif-keyboard-13628640571139384229](https://cloud.githubusercontent.com/assets/2151639/17569825/e80bd820-5f17-11e6-9c9d-88711baff1b1.gif)
