### ISSUE TITLE
Requires location permissions on Android

### ISSUE THREAD

**Issue by zlsa** [mapbox/mapbox-gl-native#5898]
**Platform:** Android

### Steps to trigger behavior

 1. Create a map without the `ACCESS_COARSE_LOCATION` and `ACCESS_FINE_LOCATION` permissions.
 
### Expected behavior

Displaying a map should not require any location permissions.

### Actual behavior

Mapbox requires location permissions to display a map.

**Comment by tobrun** [comment]
@zlsa thank you for reaching out, I verified your use-case with the `4.1.1` version and was able to display the map without any locational permissions. Below you will find the AndroidManifest.xml I was using:

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.tobrun.mapboxtest">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:theme="@style/AppTheme.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <service android:name="com.mapbox.mapboxsdk.telemetry.TelemetryService" />
    </application>

</manifest>
```

![device-2016-08-08-065626](https://cloud.githubusercontent.com/assets/2151639/17477796/473cd6a8-5d35-11e6-9a96-0abe279be10e.png)


My initial guess is that something else is going wrong for you. Would you be able to share your logcat output so we can help you get tot the bottom of this? Thank you again for reaching out but going to close as not reproducible for now.

**Comment by zlsa** [comment]
Can confirm, this works for me despite the instructions specifying otherwise. Who would I contact to discuss the legalities of not providing the location permission?

**Comment by tobrun** [comment]
Don't hesitate to contact us through https://www.mapbox.com/contact/

Thanks you for reaching out!
