### ISSUE TITLE
Fabric build output should be compatible with Fabric distribution system

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-gl-native#5903]
I'm finding that the last iOS release that appears to be compatible with Fabric is [ios-v3.2.3](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.2.3). In [ios-v3.3.0-alpha.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.3.0-alpha.1) we [migrated iOS and macOS targets to checked in Xcode projects](https://github.com/mapbox/mapbox-gl-native/pull/4641). Some part of this change appears to have broken the way an app using the Mapbox SDK via Fabric pulls in Objective-C categories. This results in a runtime error:

`[NSProcessInfo mgl_isInterfaceBuilderDesignablesAgent]: unrecognized selector sent to instance ...`

Digging a bit deeper, [ios-v3.3.0-alpha.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.3.0-alpha.1) actually broke projects that use the static framework entirely. So, if you used 3.3.0-alpha.1 to 3.3.0-alpha.3 you could not even build an app using the Fabric project template.

In [ios-v3.3.0-beta.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.3.0-beta.1) we [fixed an issue where applications could not link to the Mapbox library as a static lib](https://github.com/mapbox/mapbox-gl-native/pull/5209). However, it appears that more changes are probably required to regain compatibility with Fabric.

cc @friedbunny @1ec5 @incanus

**Comment by 1ec5** [comment]
Probably related to 7a38e568191a68e3311d36296e14c105b12c051c. We should verify the statement in that commit message that `-ObjC` in the static framework build target is sufficient for getting the SDK’s category methods into the final built binary.

**Comment by boundsj** [comment]
@1ec5 @incanus adding `-ObjC` to the Fabric generated project allows an app made with the project to run fine using the latest Fabric build output from master. I get the sense from looking at the [add/remove -ObjC flag oscillations over the last year](https://github.com/search?q=user%3Amapbox+fabric+objc&ref=cmdform&type=Issues) that we should probably go ahead and revert https://github.com/mapbox/mapbox-gl-native/commit/7a38e568191a68e3311d36296e14c105b12c051c, unfortunately, just for Fabric. Ok?

**Comment by 1ec5** [comment]
We'd have to add a whole lot more of the C function hack because we have a lot more categories than we used to.

**Comment by pveugen** [comment]
Fabric didn't get back to us yet – https://github.com/mapbox/twitter-collab/issues/28. I'll post an update to that ticket.

Given movement with Twitter (https://github.com/mapbox/sales/issues/2385) it would be wonderful if we can postpone or avoid any discussion for dropping Fabric's Mac app as a distribution channel just a little longer. As long as we're rolling beta's we should be fine.

**Comment by boundsj** [comment]
Closing ref https://github.com/mapbox/mapbox-gl-native/issues/8969
