### ISSUE TITLE
Map "settling" animation doesn't cancel with cancelTransitions

### ISSUE THREAD

**Issue by sddamico** [mapbox/mapbox-gl-native#5905]
I'm writing a method to prevent the camera from exiting a certain bounds (workaround for #3602). "Pseudocode":

```
Bounds constraintBounds = new Bounds(...);

mapView.postOnAnimation(() -> {
  checkBounds();
  mapView.postOnAnimation(this);
});

checkBounds() {
  CameraPosition cameraPosition = map.getCameraPosition();
  Bounds visibleBounds = map.getVisibleBounds(); 

  if (visibleBounds.outside(constraintBounds)) {
    map.moveCamera(CameraUpdateFactory.newLatLng(cameraPosition.plus(contraintBounds.diff(visibleBounds)));
  }
}
```

This works for the most part except for during the "settling" animation that occurs after a swipe.

![swipe_animation_bug_mapbox](https://cloud.githubusercontent.com/assets/1250383/17494655/b15f8d70-5d83-11e6-80f8-38951c55c019.gif)

**Platform:** Android
**Mapbox SDK version:** 4.2.0-SNAPSHOT
### Steps to trigger behavior
1. Write bounds checking/camera updating method similar to above
2. Try to enable settling animation by swiping rapidly on map view
### Expected behavior

`moveCamera()`'s call to `cancelTransitions()` would cancel settling animation, preventing camera from exiting bounds.
### Actual behavior

Animation continues.

**Comment by tobrun** [comment]
Adding this to the 4.2.0 milestone since we have heard some requests around this feature.

**Comment by tobrun** [comment]
Looked into this and seemed different than I initially thought. Moving it of the milestone for now, the issue I looked in is PR'ed in https://github.com/mapbox/mapbox-gl-native/pull/6891. @sddamico have you tried hooking into using `MapboxMap.OnFlingListener`? This is called as part of the swipe/fling.

**Comment by sddamico** [comment]
@tobrun I had tried the fling listener previously, yes. My issue here was that calling `moveCamera` on every frame should cancel a running animation.

**Comment by sddamico** [comment]
The thing that I was trying to do is now solved with viewport restrictions, closing.
