### ISSUE TITLE
Runtime Styling API - mutable GeoJsonSource

### ISSUE THREAD

**Issue by sddamico** [mapbox/mapbox-gl-native#5906]
This is really a feature request for two methods:

0. `MapboxMap#getSource(String sourceId)`
0. `GeoJsonSource#setData(String rawJson)` or, better, `#setData(Object jsonObject)` so that the caller doesn't need to serialize to `String` every time.

Intended use here is the ability to dynamically update GeoJson sources. Specifically, this includes things like adding/removing Features from FeatureCollections, etc. and, also, being able to modify the data in sources that are pre-defined in the map style.

Currently, I'm needing to `removeSource()` and then `addSource()` when I want to update source data.

**Comment by sddamico** [comment]
Tangentially, adding a first-party GeoJson implementation might be useful. I've started adapting https://github.com/filosganga/geogson to remove the guava dependency in my own project.

**Comment by ivovandongen** [comment]
@sddamico Thanks for the report.

The api around sources is immutable on purpose ATM as the underlying resources are immutable. Adding a getter + `setData()` would still need to do add and remove the source.

Concerning the gson support. Currently we're bringing in GSon specifically for GeoJson in https://github.com/mapbox/mapbox-gl-native/issues/5869 from https://github.com/mapbox/mapbox-java. I like your idea and I added a ticket for it: https://github.com/mapbox/mapbox-gl-native/issues/5941

**Comment by sddamico** [comment]
Great! Thanks @ivovandongen.

Interesting choice on the immutable sources, I was observing the js api and the geojson source there has a `setData()`. What was the reasoning there?

Somehow I missed the GeoJSON implementation in mapbox-java, I'll be moving my project over to that shortly.

**Comment by ivovandongen** [comment]
@sddamico Digging further into this, I see now that it should be possible to add a getter for the source and  setters for the data/url.  Seems like I missed that in the initial implementation.

> Somehow I missed the GeoJSON implementation in mapbox-java, I'll be moving my project over to that shortly.

The dependency on mapbox-java is new since https://github.com/mapbox/mapbox-gl-native/pull/6012 .

**Comment by sddamico** [comment]
Awesome, thanks!

**Comment by 1ec5** [comment]
Tracking the iOS/macOS equivalent in #6159.

**Comment by ivovandongen** [comment]
We need to wait on #5701 for this as the changes in the source are not reflected on the map at this time.

**Comment by jfirebaugh** [comment]
> `#setData(Object jsonObject)`

Agreed that this signature would be ideal; it requires #5623.

**Comment by ivovandongen** [comment]
@jfirebaugh For java, Object parameters make less sense. I've added a setter for GeoJson types to accomplish the same thing [here](https://github.com/mapbox/mapbox-gl-native/blob/f1b9ffbdc069d995653a55d3fb1575dcf3b52e18/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.java#L120).

Besides untyped parameters not being common in java, it would require some nasty reflection from jni as there is no way to access an Object as a map like in some other languages.

**Comment by jfirebaugh** [comment]
Sorry, I should have been more clear. My point was, ideally neither the API nor implementation require a round trip through stringified JSON. The function signature you linked to looks good, but I want to avoid the `features.toJson()` in the implementation.

**Comment by tobrun** [comment]
Core integration has landed with 7df9a21
