### ISSUE TITLE
setCenterCoordinate:zoomLevel:animated Does Not Set The Center Coordinate Properly

### ISSUE THREAD

**Issue by frowing** [mapbox/mapbox-gl-native#5913]
**Platform:**
iOS
**Mapbox SDK version:**
3.3.3

### Steps to trigger behavior

 1. Call `setCenterCoordinate:zoomLevel:animated` with a specific coordinate but a different zoom level than the current map view's `zoomLevel`. `animated` is set to `YES`.
 2. Wait for the animation to finish.
 3. Check the mapView `centerCoordinate` property. 

### Expected behavior
The coordinate should be the one specified in the call.

### Actual behavior
It's not.

**Comment by boundsj** [comment]
Hi @frowing 

> Wait for the animation to finish.

How are you currently determining when the animation is finished? 

In the example below, when the `center` button is tapped, I send `CLLocationCoordinate2D newCenter = CLLocationCoordinate2DMake(37.5, -122.5);` to the map's `setCenterCoordinate:zoomLevel:animated` (where animated is true) and then check the center of the map in delegate method `mapView:regionDidChangeAnimated:` and update the label next to the round dot in the middle of the map. It always correctly reflects the exact coordinate (`newCenter`) that I pass in.

![set_center](https://cloud.githubusercontent.com/assets/63186/17633969/fa5c282c-6084-11e6-99b0-b7e6a37ccca5.gif)

**Comment by frowing** [comment]
Hi @boundsj after checking again I'm no longer able to reproduce the issue :/ I was executing a block on `dispatch_after` but I guess that I wasn't giving enough time for the animation to complete, that's why I was seeing wrong coordinates.

You can experience it when opening and closing our map multiple times. When you open the map, we zoom in a little bit, and when you close it, we zoom out a little bit. We must have a teeny tiny rounding error or something like that somewhere because the difference in coordinates is very small

```
before animation latitude:52.341381 longitude:4.893975 zoomLevel:12.944709
regionDidChange latitude:52.341381 longitude:4.893975 zoomLevel:11.444709
after dispatch after latitude:52.341381 longitude:4.893975 zoomLevel:11.444709

before animation latitude:52.350935 longitude:4.893975 zoomLevel:11.444709
regionDidChange latitude:52.350935 longitude:4.893975 zoomLevel:12.944709
after dispatch after latitude:52.350935 longitude:4.893975 zoomLevel:12.944709

before animation latitude:52.340692 longitude:4.893975 zoomLevel:12.944709
regionDidChange latitude:52.340692 longitude:4.893975 zoomLevel:11.444709
after dispatch after latitude:52.340692 longitude:4.893975 zoomLevel:11.444709
```

**Comment by boundsj** [comment]
Thanks @frowing. The block you dispatch won't necessarily run after (or before) the centering animation. I think that using the map lifecycle hooks (i.e. `mapView:regionDidChangeAnimated:`) will help make your feature more reliable.
