### ISSUE TITLE
Camera LatLngBounds not fitting correctly when maps tilted

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#5914]
Could be fixed when [this issue's](https://github.com/mapbox/mapbox-gl-native/issues/4796#issuecomment-229481550) resolved. In the gif, the entire state of Texas should fit. Code from the [demo app](https://github.com/mapbox/mapbox-android-demo)

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/5652865/17528470/988b3ec4-5e3d-11e6-9d0f-0a9d0fb0d9e0.gif)

**Comment by tobrun** [comment]
Closing in favour of  #2259 in combination with https://github.com/mapbox/mapbox-gl-native/issues/4796
