### ISSUE TITLE
Markers can get out of sync when added/removed regularly

### ISSUE THREAD

**Issue by sddamico** [mapbox/mapbox-gl-native#5915]
I'm writing code to add/show markers on my map based on a zoom threshold. e.g. one set of markers is shown until zoom > 2.0, then show the other set.

I've coded up a demo project with essentially what I'm doing:

https://github.com/sddamico/mapbox-marker-bug

The issue seems to be that the markers that are "removed" cannot be removed again when they are added a second time. I've provided an example gif as well:

![zoom-bug](https://cloud.githubusercontent.com/assets/1250383/17528653/38a95472-5e3e-11e6-941e-054d3c585c38.gif)

**Platform:** Android
**Mapbox SDK version:** 4.2.0-SNAPSHOT

### Steps to trigger behavior

 1. Run example app above (after inserting own access token into start call)
 2. Zoom in and out

### Expected behavior
Based on zoom level, one marker is shown and the other is not

### Actual behavior
Both markers end up showing

**Comment by tobrun** [comment]
@sddamico thank you for reaching out. I think there is a mismatch with the annotation id. For now I would advice you to work around this issue using a MarkerView (a view based marker). That class exposes a `visible` parameter that will not add/remove the annotation in the way as with gl based markers.

**Comment by sddamico** [comment]
@tobrun gave the view-based approach a go, the performance just isn't there. I've got ~800 markers that are being added to the map and it seems like it's iterating the full list of them many, many times as each one is added/updated with data.

**Comment by sddamico** [comment]
It seems like a mostly-viable workaround right now is creating new MarkerOptions when the zoom threshold changes.

**Comment by tobrun** [comment]
> I've got ~800 markers that are being added to the map 

This doesn't seem like a good fit when it comes to ViewMarker. These are highly flexible but aren't as performant as gl based markers. I will try looking into this issue asap.

**Comment by mkv123** [comment]
I may be hitting this issue, or a related one:  

I remove and add a polyline regularly and change the style url, it appears that an annotations ID is actually changing! Once the annotation id has changed, the removal no longer works with the old or the new ID.   

This is happening with the latest snapshot of 4.2. 

Should I open a separate bug or do you think it is this one?
