### ISSUE TITLE
Selective headless rendering for tests

### ISSUE THREAD

**Issue by tiagovignatti** [mapbox/mapbox-gl-native#5926]
With the [experimental](https://github.com/mapbox/mapbox-gl-native/tree/tiagovignatti-egl-headless-view_v2) EGL / GBM headless platform, different Mesa OpenGL backends can be used. So besides avoiding a windowing system and also other non-standard-not-so-interesting APIs (like the OSMesa. See  https://github.com/mapbox/mapbox-gl-native/issues/4498 and https://github.com/mapbox/mapbox-gl-native/pull/4638), this new platform can be used to easily select the rendering configurations:

Mesa rendering configuration | Shaders execution | Mesa environmental variable
------------ | ------------- | -------------
DRI hardware accelerated | GPU | (this is the default, in case the system has a dedicated GPU hardware)
llvmpipe | CPU | GALLIUM_DRIVER=llvmpipe GBM_ALWAYS_SOFTWARE=1
softpipe | CPU | GALLIUM_DRIVER=softpipe GBM_ALWAYS_SOFTWARE=1
OpenSWR | CPU | GALLIUM_DRIVER=swr GBM_ALWAYS_SOFTWARE=1

I've tried all configurations on my Broadwell machine using ```mbgl-test``` and each takes a different amount of time depending the test suite, subtests and so on -- llvmpipe (which I understand is being used in Travis now) seems the best _on average_ still.

This popped an idea that maybe the ```test/``` directory could be split based on the rendering capability e.g. tests/ (for tests that don't render at all), ```tests-render-gpu/```, ```tests-render-cpu-swr/```, ```tests-render-cpu-*``` and so on. So for example if a fill color test behaves the same using software or GPU rasterizer (I'm guessing!) then [general purpose EC2 instances](https://aws.amazon.com/ec2/pricing/) would be fine for that. But in the case of a more complex test, say, involving alpha blending or something, then maybe that could pay off the price of using a GPU instance instead. The point is: everything is easily configurable now.

@mikemorris @brunoabinader @tmpsantos

**Comment by jfirebaugh** [comment]
Thanks @tiagovignatti, we'll keep this suggestion in mind for https://github.com/mapbox/mapbox-gl-test-suite. I don't think we'd want to change the actual directory structure, because we use it for other purposes and the test suite is not specific to mapbox-gl-native, but we could certainly record the preferred backend in another way, e.g. in the `metadata` key of the style under test.
