### ISSUE TITLE
LeakCanary report for MyLocationView

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#5934]
An user reached out and passed us a LeakCanary report for MyLocationView.

![image](https://cloud.githubusercontent.com/assets/2151639/17570037/c6cf4808-5f18-11e6-8457-194b2be824d9.png)

This report is found in the SDK and not in our testapp, higher priority to resolve than others.

**Comment by tobrun** [comment]
I wasn't able to reproduce the exact same case but I have a possible fix ready. Also was able to resolve 2 other memory leaks related `LocationListener`.

**Comment by Larnoo** [comment]
[Android] MyLocationView memory leak

MapboxSDK v5.0.1
![0fe01b31-5ac8-4ab9-bd4a-049c6e4df4fc](https://user-images.githubusercontent.com/15139682/29705683-c4fd4aba-89b1-11e7-8cb4-6818d262b5e0.png)

@tobrun
