### ISSUE TITLE
Fix clipped label in GeoJSON source

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-native#5936]
**Platform:** node bindings
**Mapbox SDK version:** `master` circa c354ae523a00b4c0e0577c4784b53553ea1a1cb7
### Steps to trigger behavior

Render [this test `style.json`](https://github.com/mapbox/mapbox-gl-test-suite/blob/7643b7c48cead1e860e5eaeba486b89b95538a63/render-tests/text-font/cjk-mixed/style.json) with [this geojson source data](https://github.com/mapbox/mapbox-gl-test-suite/blob/7643b7c48cead1e860e5eaeba486b89b95538a63/data/cjk-mixed.geojson)
### Expected behavior vs Actual behavior

![cjk-mixed](https://cloud.githubusercontent.com/assets/281306/17574220/45a1eb2c-5f14-11e6-86ba-2354888e35d8.gif)

☝️ the label is clipped

cc @mikemorris @amyleew @xrwang @1ec5 @ansis

**Comment by amyleew** [comment]
Another issue with the same style and data source here is the 3 points, as shown on the diff, shift slightly from expected to actual. And after removing the clipped label, these shifting points still fail the test.
