### ISSUE TITLE
GeoJsonSource - Add GeoJson typed methods

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#5941]
Since we're bringing in GeoJson classes to support feature querying in https://github.com/mapbox/mapbox-gl-native/issues/5869 we can now also support GeoJson directly on the GeoJsonSource instead of raw json strings. See original request here: https://github.com/mapbox/mapbox-gl-native/issues/5906#issuecomment-238379167

**Comment by 1ec5** [comment]
#5966 tracks the equivalent on iOS and macOS.

**Comment by ivovandongen** [comment]
merged
