### ISSUE TITLE
Blinking text sporadically around high-density at mid-zoom 

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-gl-native#5946]
**Platform:** iOS
**Mapbox SDK version:** `master` previously b0cb8715ed74678b4d0f05829fa71a590e41b2f6
### Steps to trigger behavior
1. Low to mid zoom into high-density city like New Taipei City
2. Pan to either side on map
3. Zoom in and out a bit more
### Expected behavior

Normal seamless zoom around the map.
### Actual behavior

Blinking place and street labels, however I only saw this happen a few time on the first load. Now I can't reproduce enough to record gif.

![image](https://cloud.githubusercontent.com/assets/4587826/17600197/3ff76744-5fb7-11e6-94e1-93eddd0afd10.png)

/cc @1ec5 @lucaswoj @brunoabinader

**Comment by brunoabinader** [comment]
I've experienced this a few times too - but it looks to me that it happens when we rapidly animate below and above integer zoom levels that triggers _label opacity transitions_ as specified on the style. @amyleew @1ec5 is that what you both experienced too?

**Comment by amyleew** [comment]
@brunoabinader - this definitely happened only during zoom, but it only happened a few times.

**Comment by brunoabinader** [comment]
> this definitely happened only during zoom

_Zooming_ triggers a new placement calculation (for detecting colliding labels). Placement updates are asynchronous and prone to inconsistencies due to floating precision issues 

Related: #3841

**Comment by jfirebaugh** [comment]
⇢ #7026
