### ISSUE TITLE
Class-specific paint properties in runtime styling API

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5948]
Per https://github.com/mapbox/mapbox-gl-native/pull/5727#discussion_r71736017, paint attributes are exposed, unparameterized, at the top level of each style layer class. For non-default, [style class–specific paint properties](https://www.mapbox.com/mapbox-gl-style-spec/#layer-paint.*), we should add an additional pair of getters and setters for each attribute. For example, the `circleBlur` property should be accompanied by `-circleBlurForStyleClass:` and `-setCircleBlur:forStyleClass:`.

/cc @frederoni @jfirebaugh

**Comment by jfirebaugh** [comment]
What if we didn't expose class-specific paint properties in the SDK? Android doesn't, and I'm 95% sure that we'll be removing them from the style specification in a future revision.

**Comment by 1ec5** [comment]
Style classes have been in limbo for well over a year. The point of this ticket is that, if we intend to keep style classes around, then we should make them usable. If they're deprecated, though, I agree that we should focus our efforts elsewhere.

**Comment by jfirebaugh** [comment]
Let's focus our efforts elsewhere.
