### ISSUE TITLE
Runtime styling enumerations are undocumented

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5953]
Per https://github.com/mapbox/mapbox-gl-native/pull/5727#discussion_r71797200, all the runtime styling enumerations are undocumented. We need to come up with documentation comments for each enumeration typedef as well as each individual enumeration value. I think it’ll be fine to let these enumerations fall into the default enumeration bucket in the jazzy table of contents.

For starters, we could generate the comments by parsing the documentation for the attributes that use the enumerations. But we should eventually have a mechanism for specifying overrides of style specification documentation where we can manually draft these comments.

/cc @frederoni @friedbunny

**Comment by 1ec5** [comment]
Blocked by mapbox/mapbox-gl-style-spec#497. Given that proposal, I don’t think we should bother doing any fancy parsing of English text to come up with enum documentation, as I proposed above.

**Comment by incanus** [comment]
@1ec5 Can we close this here then since #6508 landed?

**Comment by 1ec5** [comment]
Yes, and #6107 will implement an override mechanism for remaining edge cases. Thanks for taking care of that!
