### ISSUE TITLE
Runtime styling changes should take effect immediately

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5957]
Per https://github.com/mapbox/mapbox-gl-native/pull/5727#commitcomment-18577738 and https://github.com/mapbox/mapbox-gl-native/pull/5727#discussion_r74302320, changes to layer and source attributes should take effect immediately. We should offer a block-based transaction API for cases in which the developer needs to change multiple attributes in tandem.

/cc @incanus @frederoni

**Comment by incanus** [comment]
Per voice with @frederoni, the impact here is code gen to essentially call `update()` for each style property setter, which is verbose but, well, code gen, so not a big deal. 

I'm 👍
