### ISSUE TITLE
MGLBaseStyleLayer needs documentation

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5959]
Per https://github.com/mapbox/mapbox-gl-native/pull/5727#discussion_r74301831, MGLBaseStyleLayer and its `visible` property are missing documentation comments.

/cc @frederoni

**Comment by incanus** [comment]
We need to hit the base style layer subclasses as well (fill, line, etc.). Relies on https://github.com/mapbox/mapbox-gl-native/issues/5954.

**Comment by boundsj** [comment]
> We need to hit the base style layer subclasses

@incanus note that this started in https://github.com/mapbox/mapbox-gl-native/pull/6107

**Comment by incanus** [comment]
Subclasses handled in ticket at https://github.com/mapbox/mapbox-gl-native/issues/6467 for clarity.
