### ISSUE TITLE
MGLSource and subclasses need documentation

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5960]
Per https://github.com/mapbox/mapbox-gl-native/pull/5727#discussion_r74305314 and https://github.com/mapbox/mapbox-gl-native/pull/5727#issuecomment-238978850, MGLSource and its symbols, as well as each of MGLSource’s subclasses, need documentation comments. This may require #5954.

/cc @frederoni @friedbunny

**Comment by 1ec5** [comment]
Until this documentation is added, developers are going to get confused by MGLRasterStyle’s `URL` property, thinking it’s for tile sets (#6245).

**Comment by boundsj** [comment]
https://github.com/mapbox/mapbox-gl-native/pull/6316 adds the ability to create raster and vector sources with a new `MGLTileSet` object. The documentation in `MGLTileSet` plus the new initializers in `MGLRasterSource` and `MGLVectorSource` may help mitigate confusion until documentation for the sources lands.
