### ISSUE TITLE
MGLStyleAttributeFunction.functionType should be MGLStyleAttributeFunctionType

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5969]
[`MGLStyleAttributeFunction.functionType`](https://github.com/mapbox/mapbox-gl-native/blob/0ae941d2a8a89276e1f0c2cf3870104d0e94fbc4/platform/darwin/src/MGLStyleAttributeFunction.h#L22) should be of type `MGLStyleAttributeFunctionType`, not NSNumber. The style specification [allows](https://www.mapbox.com/mapbox-gl-style-spec/#types-function) the `type` property to be omitted, but the value is actually `exponential` (`MGLStyleAttributeFunctionTypeExponential`) or `interval` (`MGLStyleAttributeFunctionTypeInterval`) by default, depending on the property, and it’s meaningless for a function to have no type. So there’s no need for a nullable object here.

/cc @frederoni

**Comment by frederoni** [comment]
`type` is omitted or not yet implemented in [function.hpp](https://github.com/mapbox/mapbox-gl-native/blob/0ae941d2a8a89276e1f0c2cf3870104d0e94fbc4/include/mbgl/style/function.hpp) so I suggest we remove MGLStyleAttributeFunction.functionType and the other unused types until we can make use of them.

**Comment by 1ec5** [comment]
Is there a ticket tracking that core work? Seems like it'd be important for style specification compliance and GL JS parity.

**Comment by 1ec5** [comment]
Per @lucaswoj, function `type`s are only relevant for property functions, so we’ll only need SDK support for them once #4860 is implemented.
