### ISSUE TITLE
Add predicate property to MGLStyleLayer

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#5973]
MGLStyleLayer should have a `predicate` property that translates to a filter in mbgl. The developer would create a predicate like so:

```objc
[NSPredicate predicateWithFormat:@"name == 'USA'"]
```

The returned value would be an instance of NSComparisonPredicate with `leftExpression.keyPath` being `name`, `predicateOperatorType` being `NSEqualToPredicateOperatorType`, and `rightExpression.constantValue` being `USA`. We’d translate that into an `mbgl::style::EqualsFilter`.

[Here’s a full correspondence](https://gist.github.com/1ec5/3d81399e11ff45ee86d482cac25a0493) between NSPredicate types and style specification filter forms.

/cc @frederoni @incanus

**Comment by boundsj** [comment]
This was completed by @frederoni in https://github.com/mapbox/mapbox-gl-native/pull/6049 🎉
