### ISSUE TITLE
MyLocationViewSettings#setPadding example

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#5977]
We support setting a padding to the `MyLocationView` object via `MyLocationViewSettings#setPadding` (the settings object can be obtained from `mapboxMap.getMyLocationViewSettings()`). However, we don't have any examples about usage.

It'd be great if we could add an example about this feature to either the TestApp or the DemoApp.

/cc: @cammace @tobrun

**Comment by cammace** [comment]
I've been working on this example showing off how to use `getMyLocationViewSettings` to set the foreground/accuracy tint color and padding but when setting the value for padding, nothing is changing. 

This gif uses a marker to show the current user location (without any padding) and then user location view with a padding of 500 and it doesn't seem to behave any different:

![ezgif com-video-to-gif 2](https://cloud.githubusercontent.com/assets/5652865/17683451/ea76cfd6-6320-11e6-8423-e5be7048ff65.gif)
