### ISSUE TITLE
Attribution control on Qt

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6000]
`QQuickMapboxGL::setCopyrightsVisible()` is [unimplemented](https://github.com/mapbox/mapbox-gl-native/blob/472ab7442f566e6d2e8f1b67282d8394d0394de6/platform/qt/src/qquickmapboxgl.cpp#L140-L144). The Qt SDK should automatically provide an attribution control that displays copyright statements and links to further information.

/cc @tmpsantos

**Comment by tmpsantos** [comment]
Depends on #5999

**Comment by 1ec5** [comment]
This work was actually unblocked by #6431.

**Comment by brunoabinader** [comment]
As part of the shift towards the `QGeoMap` plugin for Mapbox GL as a replacement for `QQuickMapboxGL`, we provide a signal `copyrightsChanged(QString)` in #7347.
