### ISSUE TITLE
Map feedback view controller

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6001]
The “Improve This Map” item in the attribution action sheet opens the [Map Feedback](https://www.mapbox.com/map-feedback/) tool in the default Web browser. This Web application is difficult to use on a mobile device. Meanwhile, the SDK has a lot more context about the current view that could lead to more actionable feedback.

The SDK should vend a view controller that allows the user to fill out all the same information that the existing Map Feedback tool collects, but using native controls. Additionally, it could allow the user to select the problematic map feature from a map view using feature querying and send along the feature’s OpenStreetMap ID. Upon sending the feedback, the user would automatically be taken back to the map. This would be an improvement over the current workflow, which requires the user to manually return to the Mapbox-powered application.

This functionality would have to live in a view controller because MGLMapView could be arbitrarily small and incapable of hosting a complex form layout. We’d expose a method in MGLMapViewDelegate to give the map view’s host view controller the opportunity to choose between segueing to the feedback view controller or opening the existing tool in the default browser (useful for maps contained in embedded view controllers or other non-obvious configurations).

I’m keeping this ticket limited to iOS for the moment, because the view controller consideration is an important one on iOS. (On macOS, for instance, it’d trivial for a view to open a sheet or modal window large enough to host the entire feedback experience.)

/cc @mapbox/mobile

**Comment by zugaldia** [comment]
The Android equivalent is tracked in https://github.com/mapbox/mapbox-gl-native/issues/6013.
