### ISSUE TITLE
How to different  miles wise radius draw in GL-Mapbox

### ISSUE THREAD

**Issue by achalnexus** [mapbox/mapbox-gl-native#6005]
I want to draw radius in mapbox with different miles.
foe eg:- if Zoom Level 8 then draw 100 miles and zoom level 9 then draw 80 miles radius.

**Comment by jfirebaugh** [comment]
Have a look at [zoom functions](https://www.mapbox.com/mapbox-gl-style-spec/#types-function) and the [circle-radius](https://www.mapbox.com/mapbox-gl-style-spec/#paint-circle-radius) style property.
