### ISSUE TITLE
Cleanup + refactor gradle files

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#6009]
Our gradle files are growing large and complex. 
I suggest refactoring some `tasks` into external build scripts:
- [ ] javadoc.gradle
- [ ] maven.gradle
- [ ] make.gradle
- [ ] dev_config.gradle
- [ ] ...
### [How to config project using external build script](https://docs.gradle.org/current/userguide/userguide_single.html#sec%3aconfiguring_using_external_script)

build.gradle

```
apply from: 'other.gradle'
```

other.gradle

```
println "configuring $project"
task hello << {
    println 'hello from other script'
}
```

Additional tasks:
- [ ] Reevaluate every code block
- [ ] Remove Android Plugin Manager https://github.com/mapbox/mapbox-gl-native/issues/5930

cc @mapbox/android

**Comment by zugaldia** [comment]
👍 I really like doing this to my `.gradle` files and also makes sense from a consistency point of view as we're already following this approach on MAS. E.g.: https://github.com/mapbox/mapbox-java/blob/master/libandroid/lib/build.gradle#L47-L49.

**Comment by tobrun** [comment]
Ah now I remember where I had seen that before, :bow: @zugaldia

**Comment by tobrun** [comment]
Moving of the milestone, no requirement
