### ISSUE TITLE
Support "video" source type

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#601]
https://github.com/mapbox/mapbox-gl-js/blob/mb-pages/js/source/video_source.js

I'm imagining this is going to work totally differently than JS. That AFAICT uses an out-of-view video `<div>` that plays back and whose content snapshot is grabbed periodically to use in GL frames. 

On native we'd likely have to decode video directly and get frames that way.

**Comment by dylan-chong** [comment]
Is this issue dead? :|

**Comment by ChrisLoer** [comment]
@asheemmamoowala Do I remember you had an example of how to include video support via custom layers?

**Comment by asheemmamoowala** [comment]
There's a demo of how to do this using custom layers at: https://github.com/asheemmamoowala/MapboxMapVideoLayer

The video is jittery at high zooms when being interacted with, and it consumes a lot of energy.
![ezgif com-resize](https://user-images.githubusercontent.com/11619675/44181475-d56d4400-a0b6-11e8-8efd-2b450c15188a.gif)
