### ISSUE TITLE
add test for Android runtime styling non-string type filters

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#6014]
https://github.com/mapbox/mapbox-gl-native/pull/5979 was meant to fix filters of this sort: 

```java
LineLayer segments = mapboxMap.getLayerAs("segments");
segments.setFilter(eq("uniqid", new Integer(10191020)));
segments.setProperties(lineColor(Color.GREEN),
    lineWidth(10f),
    lineOpacity(0.5f));
```

However, it still doesn't seem to work (nor does `eq("uniqid", 10191020)`). Regardless, we should add a test scenario for a non-string type filter so that [this one](https://github.com/mapbox/mapbox-gl-native/blob/52134eb8fd99527e084c6fc9ec2926057c593d4d/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RuntimeStyleActivity.java#L248) isn't the only thing being exercised (as well as fix the core issue, if it's really still happening). 

/cc @ivovandongen

**Comment by ivovandongen** [comment]
@incanus See the example with numerical filters here: https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/GeoJsonClusteringActivity.java#L170

But I'll happily add another one.

**Comment by ivovandongen** [comment]
Merged example
