### ISSUE TITLE
allow for more efficient batch runtime style API changes

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#6017]
We want a transaction block model such as `CATransaction` which will defer calls to `-[MGLBaseStyleLayer update]` until the transaction is completed, allowing for many setters to be called which are all made effective with one `-update` call. 

A model for design here might be a singleton which counts to `1` when the transaction `begin`s, decrements to `0` when the transaction `commit`s, and throws an exception if it is ever tried to be nested with a secondary or later `begin` (though, that would probably be harmless—`commit` could just always reset to `0`). 

/cc @frederoni @1ec5

**Comment by 1ec5** [comment]
(Spun out from #5957.)

**Comment by 1ec5** [comment]
> A model for design here might be a singleton which counts to `1` when the transaction `begin`s, decrements to `0` when the transaction `commit`s, and throws an exception if it is ever tried to be nested with a secondary or layer `begin`.

With a block-based design, we can allow the counter to increment past 1 and only update when it falls to 0. Nesting transactions should be no problem.

**Comment by frederoni** [comment]
Perfect case for the recently introduced class properties:
```
@property (class) NSUInteger batchedTransactions;
```
Though, it's unfortunate that we can't make use of this yet as it would mean dropping support for Xcode 7.x

**Comment by jfirebaugh** [comment]
I don't think we want an explicit transactional API; we had that in gl-js but replaced it with automatic batching, which works well and requires less API surface area (https://github.com/mapbox/mapbox-gl-js/pull/2355).

**Comment by jfirebaugh** [comment]
Automatic batching is part of #6201, I'm going to mark this to close when that's merged.
