### ISSUE TITLE
Map layer stops updating after user interaction

### ISSUE THREAD

**Issue by mikkoto** [mapbox/mapbox-gl-native#6031]
**Platform:** Oneplus 2, android 5.1.1, OxygenOs 2.2.1
**Mapbox SDK version:** 4.2.0-beta1

On Oneplus 2, android 5.1.1 map layer stops updating after user pans or zooms. Only markers are updated based on user interaction. Also occasionally map layer is not displayed at all i.e. only black screen is displayed with markers on top of it.

The issue can be reproduced using the Mapbox Dev Preview app found on Google Play.

![oneplus2_mapbox_420beta](https://cloud.githubusercontent.com/assets/369359/17692798/6facfe54-63a4-11e6-9b23-5c959591193e.gif)

**Comment by cammace** [comment]
Thanks for reporting this, were you able to reproduce this issue on any device besides the Oneplus 2? I'm seeing two issues here, one with the markers becoming unattached from the mapview like you demonstrate in the gif. The other issue being that sometimes the map style doesn't load in correctly, is this also reproducible in the demo app? Also was this an issue introduces in `4.2.0-beta` or has it always been an issue? If you're unsure, switching to a lower SDK version such as `4.1.1` and testing will help out tremendously!

**Comment by mikkoto** [comment]
I just tested this with couple of development devices we have around. I couldn't reproduce this using any of the following:

- Samsung Galaxy SII, android 4.1.2
- Nexus 5, android 4.4
- Sony Xperia m4 aqua (e2303), android 5.0
- Nexus 5X, android 6.0.1

Also I haven't seen this behaviour with older Mapbox (e.g. 4.1.1.) when testing our own app with Oneplus 2.

The other issue of map style not loading can also be reproduced using the demo. See attached gif.
![oneplus2_mapbox_420beta_2](https://cloud.githubusercontent.com/assets/369359/17882140/3f7c4676-6913-11e6-9ba1-d5b8d930731f.gif)

**Comment by zugaldia** [comment]
Assigning @ivovandongen to help reproducing the issue.

**Comment by langsmith** [comment]
I was unable to reproduce the problem using the current Android demo app on my OnePlus 3. The markers appear to stay attached to the mapview.

![giphy](https://cloud.githubusercontent.com/assets/4394910/23714965/f9b8b2ec-03df-11e7-99de-69b1dd02361c.gif)

**Comment by HappyDr0id** [comment]
I got exactly the same issue : I have a map in a bottomsheet, which is in textureMode because of visual glitches when I drag the bottomsheet, and if I collapse the bottomsheet and expand it back, the map is totally frozen, not responding to user interaction, but MarkersViews are moving okay.
Finally the map is only working correctly on the first display.

I retrieved these logs when it happens :
```
01-18 14:49:19.297 15642-17390/fr.xpdigit.apptourism E/BufferQueueProducer: [SurfaceTexture-0-15642-2] dequeueBuffer: BufferQueue has no connected producer
                                                                            
                                                                            [ 01-18 14:49:19.297 15642:17390 D/         ]
                                                                            NULL == surf->write_back_color_buffer
01-18 14:49:19.300 15642-17390/fr.xpdigit.apptourism E/BufferQueueProducer: [SurfaceTexture-0-15642-2] dequeueBuffer: BufferQueue has no connected producer
                                                                            
                                                                            [ 01-18 14:49:19.301 15642:17390 D/         ]
```

I am using the last MapBox Android SDK Version (5.3.1) and I reproduced the issue on multiple devices : Samsung A3 (2016) SM-1310F on Android 7.0, Samsung S7 on Android 7.0, Moto E on Android 4.4.4, Nexus 5 on Android 6.0.1. But the issue is not reproduced on the Nexus 5X on Android 8.0.

I hope that it will help you to resolve this issue guys.
