### ISSUE TITLE
How to draw a dashed line on iOS app? 

### ISSUE THREAD

**Issue by chatwyn** [mapbox/mapbox-gl-native#6033]
# How to draw a dashed line on iOS app ?

**Comment by incanus** [comment]
Hi @chatwyn. Please send usage questions in to https://www.mapbox.com/help/ per the [contributing guidelines](https://github.com/mapbox/mapbox-gl-native/blob/master/CONTRIBUTING.md).

**Comment by chatwyn** [comment]
# I have't find setting lind dashed in the **MGLMapViewDelegate ** . I only find color alpha and lineWidth.

**Comment by 1ec5** [comment]
#1734 tracks adding a dedicated API for this. In the meantime, in iOS SDK v3.4.0 (currently in alpha testing):

1. Create an MGLGeoJSONSource containing the line data.
1. Create an MGLLineStyleLayer based on that source, and set its `lineDasharray` property to something like `@[@1, @2]`.
1. Add the style layer to the map view.

**Comment by chatwyn** [comment]
thanks

**Comment by eimantas** [comment]
@1ec5 I couldn't find any references to `MGLGeoJSONSource`. Is the described approach still relevant?

**Comment by jmkiley** [comment]
You may find this example helpful: https://www.mapbox.com/ios-sdk/examples/runtime-add-line/

**Comment by 1ec5** [comment]
MGLGeoJSONSource was renamed MGLShapeSource in #7334 because developers usually interact with it in conjunction with MGLShapes rather than GeoJSON source.

**Comment by songyuyang0918** [comment]
@1ec5 Hello! Now if you want to make the fillLayer edges into dotted lines, can you still add another layer of lineLayer?
If so, I will do so, but I wonder if there is an expression in lineDashPattern that allows me to match attributes in Source to show dashed lines.
