### ISSUE TITLE
MyLocationView padding not working correctly

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#6037]
I've been working on [this example](https://github.com/mapbox/mapbox-gl-native/issues/5977) showing off how to use `getMyLocationViewSettings` to set the foreground/accuracy tint color and padding but when setting the value for padding, nothing is changing. 

This gif uses a marker to show the current user location (without any padding) and then user location view with a padding of 500 and it doesn't seem to behave any different:

![ezgif com-video-to-gif 2](https://cloud.githubusercontent.com/assets/5652865/17683451/ea76cfd6-6320-11e6-8423-e5be7048ff65.gif)

cc: @mapbox/android

**Comment by tobrun** [comment]
Thank you for reaching out. 

I retried recreating your use-case with:

>                 mapboxMap.getMyLocationViewSettings().setPadding(0, getWindow().getDecorView().getMeasuredHeight() * 3 / 8, 0, 0);

Result:

![device-2016-08-16-173250](https://cloud.githubusercontent.com/assets/2151639/17705120/89b58f0e-63d7-11e6-858a-dd41f68a7bc6.png)

With tilt:

![device-2016-08-16-173353](https://cloud.githubusercontent.com/assets/2151639/17705150/a80f061a-63d7-11e6-94c5-bc0711d84d5c.png)
