### ISSUE TITLE
[Android][MapBox SDK:last version] Markers refreshing bugs using addMarkers with BaseMarkerOptions

### ISSUE THREAD

**Issue by 13kz** [mapbox/mapbox-gl-native#6038]
Hello,

We're working on our android project and we use MapBox SDK. We got a problem on adding marker on the map. At first we use MarkerViewOptions to add them but we got performance problem. We know that you are working on this to make it more robust and performant.

As workaround, we use addMarkers method to add all markers at once. Performance side, everything all right but the problem we got is something (after adding and removing markers) no markers are added on the map.

Otherwise we got this error: libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x54 in tid 14311 (RenderThread)

Is this a known bug in your side? 
Is there a way to fix this (kind of workaround)?

**Comment by tobrun** [comment]
@13kz this is because we currently don't expose an MarkerView equivalent of addMarkers. This feature is currently tracked in #5530. I'm putting this on my radar of items to look at. Closing in favor of #5530. Thank you for reaching out and pinging us on this!
