### ISSUE TITLE
Android runtime style API bug with filters & numbers

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#6040]
Per extended chat with @ivovandongen—writing this up so we have a concrete place for it on which to hang commits and eventually mark it resolved. 

Here is a sample data file: 

https://gist.github.com/incanus/0607dccb035cd9b55ff95faa1b60cf8c

I've added this to a basic Mapbox Studio style at `mapbox://styles/justin/cirnit09r000bg1mb4kxqmvwi`. 

Each segment of the data file is addressable by a `uniqid` numeric field, e.g. `10191020`. Something like this should be possible: 

```java
LineLayer segments = mapboxMap.getLayerAs("segments");
        segments.setFilter(eq("uniqid", 10191020));
        segments.setProperties(lineColor(Color.GREEN),
                lineWidth(10f),
                lineOpacity(0.5f));
```

This is the analog to doing it via the GUI in Studio: 

<img width="1340" alt="screen shot 2016-08-11 at 5 29 53 pm" src="https://cloud.githubusercontent.com/assets/17722/17711971/d8f42028-63a8-11e6-93e5-1b67c0156787.png">

However, all segments will get their style changed, not just the single one of the ~20 with that `uniqid`. The filter seems to be ignored. 

Numeric comparison, either types or precision, seems to be at fault. @ivovandongen tried a fix at https://github.com/mapbox/mapbox-gl-native/commit/ddf0d25845177d3a3e865dd7e64cf98cf6b8a7d7 but it still doesn't seem to do it. 

I will also test https://github.com/mapbox/mapbox-gl-native/commit/c34130ac6d968a3ff636af71e19893d22c2faa99 and see why it might be working but my example isn't. Is it maybe the size of the number in my data field? 

/cc @frederoni just for when we might hit this on iOS filters.

**Comment by incanus** [comment]
Confirmed that I am seeing the parks example in c34130a work just fine in my setup, so it's something more unique about my data set.

**Comment by ivovandongen** [comment]
@incanus I've tried out your json and code snippets by working it into the test app and it just seems to work. Can't say what's going wrong with your example based on the information you provided. See the patch here for more information: https://gist.github.com/ivovandongen/f6ac2d5edd66844f853126759134bc82

![segments](https://cloud.githubusercontent.com/assets/64527/17730234/313fbd9a-6468-11e6-9b75-e8518d7c8fc7.gif)

Hope that helps you.

**Comment by incanus** [comment]
@ivovandongen You are adding a new layer rather than changing an existing one in Studio. See my original code in https://github.com/mapbox/mapbox-gl-native/issues/6040#issue-171481717: 

```java
LineLayer segments = mapboxMap.getLayerAs("segments");
        segments.setFilter(eq("uniqid", 10191020));
        segments.setProperties(lineColor(Color.GREEN),
                lineWidth(10f),
                lineOpacity(0.5f));
```

This is finding the style layer which was created in Studio server-side from the source GeoJSON, not in the app. It uses `getLayerAs()` rather than your example of `new LineLayer()`. We should be able to query this existing layer, then change its properties. 

Try this patch exactly to reproduce the problem: 

https://gist.github.com/incanus/b89e1b07bdbcc921b4ae928901584e93

What should happen is a styling similar to what's seen in Studio above, but what actually happens is that the whole of the `segments` layer is styled green.

**Comment by incanus** [comment]
This may actually be rendering related, not filter. See https://github.com/mapbox/mapbox-gl-native/issues/5701.

**Comment by incanus** [comment]
That's exactly what we're seeing here. 

![anigif-1471550047](https://cloud.githubusercontent.com/assets/17722/17788544/05a30ab2-6543-11e6-9f32-8adafe59839c.gif)

I've confirmed that things work with both the primitive as the value as well as an `Integer`. Closing here and picking up in #5701. Thanks for your work @ivovandongen!
