### ISSUE TITLE
Query rendered features with tile boundaries

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#6044]
Capturing from @cammace in https://github.com/mapbox/mapbox-gl-native/issues/5792#issuecomment-240250580 :

It seems that features are broken on the border of tile, see this example:

![ef5990a8-63d7-11e6-91ea-2cc5c15ac2fd](https://cloud.githubusercontent.com/assets/2151639/17729787/1e60bfc8-6466-11e6-9505-ba857006cb7b.gif)

**Comment by jfirebaugh** [comment]
This is expected behavior for tile-based feature querying. The same caveats apply as listed in the [GL JS documentation](https://www.mapbox.com/mapbox-gl-js/api/#Map#queryRenderedFeatures).
