### ISSUE TITLE
embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/Mapbox.framework/Mapbox) for architecture x86_64

### ISSUE THREAD

**Issue by chatwyn** [mapbox/mapbox-gl-native#6045]
* The Mapbox iOS SDK is an open-source framework for embedding interactive map views with scalable, customizable vector maps into Cocoa Touch applications on **iOS 7.0** and above using Objective-C, Swift, or Interface Builder. 
* When I build project on iOS 7 ,Xcode warning ` embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/Mapbox.framework/Mapbox) for architecture x86_64`.How can I solve it?

**Comment by frederoni** [comment]
iOS 7.0 doesn't support dynamic frameworks. Please try one of the following solutions:

1. Install static framework manually
    - [Follow these instructions](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/INSTALL.md#static-framework)

2. Cocoapods (local podspec)
    - Download a release from [mapbox-gl-native/releases](https://github.com/mapbox/mapbox-gl-native/releases). (i.e mapbox-ios-sdk-3.3.4.zip)
    - Point your Podfile to a relative path
```
pod 'Mapbox-iOS-SDK', :path => "../path/to/static/Mapbox-iOS-SDK.podspec"
```
