### ISSUE TITLE
Black space (blink) when Mapview is moved

### ISSUE THREAD

**Issue by kingfisherphuoc** [mapbox/mapbox-gl-native#6048]
**Platform: Android**
**Mapbox SDK version: 4.2.0-beta.1**
### Steps to trigger behavior
1. Using Drawer layout with custom animations to scale MapView and translate MapView position.
2. Swipe left to open left navigation drawer 
3. There's black space while opening/swiping left navigation drawer 
### Expected behavior

The blink effect should not happen.
### Actual behavior

A black space (blink) occurs in the mapview in few miliseconds as below image. The error only occurs in 4.2.0, in the previous version 4.1 (released version), there's no such blink effect.
![device-2016-08-17-171819](https://cloud.githubusercontent.com/assets/962484/17734138/81b43a9e-64a4-11e6-849d-6a553b72e764.png)

**Comment by cammace** [comment]
This sounds like an issue related to the surface view, @tobrun can you confirm?

**Comment by tobrun** [comment]
Yes correct @cammace, a SurfaceView implementation is not able to handle this kind of Animation. We used to use TextureView which can do this but  is slower in rendering, which made the map feel very sluggish.

**Comment by Jaythaking** [comment]
I have the same issue on fragment transition and i'm not even scaling the MapView. It happens at the bottom for me.

**Comment by cammace** [comment]
I haven't noticed this issue in awhile, we have a [NavigationDrawerActivity](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/NavigationDrawerActivity.java) which we have been using to test this experience. Feel free to reach out on this ticket or through [our contact page](https://www.mapbox.com/contact/) if you are still having issues, happy to help.
