### ISSUE TITLE
App Crash between zoom 7 and 8 with custom tiles style

### ISSUE THREAD

**Issue by tommybuonomo** [mapbox/mapbox-gl-native#6051]
**Platform: Android
Mapbox SDK version: 4.2.0-beta.1**

Hi,
The app crash when i'm between zoom 7 and 8. I have custom style .json file located in the assets folder. On previous version (4.1.0) or with default style, all work fine, but the problem occurs on the 4.2.0-beta.1 version. 

Here the log crash : 
```A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 24885 (Worker)```

**Comment by kkaefer** [comment]
Could you please supply more information, such as an extended crash log with the backtrace, as well as the style JSON file and any assets you were loading, including the tiles? If you don't want to upload them, you can also upload them at https://www.mapbox.com/contact/. Please include a note that they should be forwarded to @kkaefer.

**Comment by tommybuonomo** [comment]
I send you the JSON file to the contact address. 
I've no more stacktrace than the previous error message...

**Comment by cammace** [comment]
Hey @tommybuonomo, thanks for sending over the JSON file for testing. I loaded up the style using `4.2.0-beta.1` and was unable to reproduce the crash. Here's the line I used:
```java
mapView.setStyleUrl("asset://osmMapStylejson");
```

![ezgif com-video-to-gif 7](https://cloud.githubusercontent.com/assets/5652865/17741948/1f190622-646c-11e6-83da-f6daa080787f.gif)

I tested all zoom levels. Could you provide more information like the device model and Android version used when the crash occurs along with any additional information that might help us troubleshoot the issue. Thanks

**Comment by tommybuonomo** [comment]
Hey @cammace, thank you for considering my issue.
I'm using a One Plus 3 with Android 6.0.1 version.
I've tested on an emulator on 6.0.0 version and the problem is the same.

**Comment by tommybuonomo** [comment]
![ezgif com-crop](https://cloud.githubusercontent.com/assets/15737675/17743457/18cc1ff6-64a4-11e6-900b-e03c5c7694a5.gif)

**Comment by cammace** [comment]
Tested this out again using a nexus 5x and wasn't able to produce:
![ezgif com-video-to-gif 8](https://cloud.githubusercontent.com/assets/5652865/17816705/96d31b56-6608-11e6-98d8-a5826be8180d.gif)

Enabled my location (As shown in your gif above) and still couldn't get the app to crash:
![ezgif com-video-to-gif 13](https://cloud.githubusercontent.com/assets/5652865/17816790/08b4a046-6609-11e6-80b8-830e5cdc6769.gif)

I then proceeded to try reproducing on an emulator device and no crash occurred (couldn't record video 😞 ). Could you send me the activity code through our [contact page](https://www.mapbox.com/contact/) so I can better troubleshoot the issue.

**Comment by tommybuonomo** [comment]
The bug is gone after re-installing the app, I think it was the Instant Run with Android Studio.
Thanks for your help !
