### ISSUE TITLE
Offsets should be flipped vertically on macOS

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6066]
In the style specification, the `y` value of a property like `fill-translate` is defined as the number of pixels from the top. By contrast, offsets are normally measured from the bottom of the screen or view on macOS. In order to simplify calculations, the value exposed to the developer via the runtime styling API should be consistent with the system’s standard origin. This will become especially important once we replace the NSArray representation with a `CGVector` (#5947).

/cc @frederoni

**Comment by jfirebaugh** [comment]
Adding to the 3.4.0 milestone -- we need to implement this now or keep the existing behavior at least until a semver major version.

**Comment by 1ec5** [comment]
This only applies to macOS; the origin is at the top-left on iOS. The macOS SDK hasn't reached v1.0.0 yet, so I'm not terribly concerned about backwards compatibility there.

**Comment by boundsj** [comment]
In that case, I'm going to remove the 3.4.0 milestone.

**Comment by 1ec5** [comment]
Fixed in #7636 on the release-ios-v3.4.0 branch.
