### ISSUE TITLE
Remove self update mechanism from annotations

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#6068]
Currently all annotations keep reference to Mapview/MapboxMap. This is required since the annotations have a self update mechanism. 

> `Polygon.addPoint` will add a point immediately when it's executed. This is not very effective when it comes to adding multiple points or multiple properties.

To be able to allow update-on-demand/transaction model. We should look into removing the reference to MapView/MapboxMap and introduce update methods on MapboxMap instead. 

``` java

Now:
marker.setPosition(new LatLngI());
marker.setTitle("null_island");
-> updates 2x

Proposition:
marker.setPosition(new LatLng();
marker.setTitle("null_island");
mapboxMap.updateMarker(Marker marker);
-> update once
```

This system allows the user to choose when to execute the update. 
I feel this concept fits well with the Builder pattern we use for creation.

**Comment by ivovandongen** [comment]
Noting that we have similar patterns in use in the Runtime Style api. Most notably Layers Sources are  mutable in the same way right now. We might want to align these api's.

**Comment by zugaldia** [comment]
@tobrun @ivovandongen Do you think we can align the APIs while keeping Google Maps Android API compatibility? (Basically providing two ways of doing the same thing.)

**Comment by tobrun** [comment]
Closing this in favour of the symbol manager plugin work happening downstream in https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-annotation
