### ISSUE TITLE
How to take a screenshot of mapview in a iOS App?

### ISSUE THREAD

**Issue by chatwyn** [mapbox/mapbox-gl-native#6070]
```
UIGraphicsBeginImageContextWithOptions(self.mapView.bounds.size, NO, 0.0);
    [self.mapView.layer renderInContext:UIGraphicsGetCurrentContext()];
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    UIImageView *imageView = [[UIImageView alloc] initWithImage:image];
    imageView.frame = self.view.bounds;
    [self.view addSubview:imageView];
```
when I use this method to take screenshoot. I got a wrong image.So how can I solve this problem.

**Comment by incanus** [comment]
@chatwyn An `MGLMapView` isn't a normal layer-backed view, but rather based on `GLKView` for OpenGL rendering. See #1701 for more background, but you can probably use a combo of `-[GLKView snapshot]` and your current approach for the parts atop the GL view for now.
