### ISSUE TITLE
Update Proguard rules

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#6077]
Discovered an issue when using Proguard and the SDK that might be because of MAS becoming a dependency or the new styles. Current work around's to keep everything:

```pro
-keep class com.mapbox.mapboxsdk.** { *; }
```

cc: @mapbox/android

**Comment by tobrun** [comment]
Thanks for noticing @cammace, need to pick this up for next release.

**Comment by tobrun** [comment]
Proposed solution in #6085
