### ISSUE TITLE
How to set z-index to a marker in a Android App?

### ISSUE THREAD

**Issue by zhangkaiyue0701** [mapbox/mapbox-gl-native#6083]
How to set z-index to a marker? And how to draw a circle on the mapview?

**Comment by tobrun** [comment]
### Re. Z-index marker
Can you clarify which type of marker you are using? Marker extending from Marker of MarkerView?

### Re. Circle
we currently don't expose a addCircle method directly on MapboxMap but we support adding circles through runtime styling. I made an example for this in #8086. The feature request to add this as a separate feature is tracked in #2167 .

**Comment by zhangkaiyue0701** [comment]
Marker extends from Annotation.

**Comment by jfirebaugh** [comment]
#1728 is the issue that tracks a z-index API for annotations.
