### ISSUE TITLE
Configure should exit 1 if an error occurs

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-gl-native#609]
Currently configure keeps on truckin even if a call to mason fails, say if `pkg-config` is not found.

**Comment by springmeyer** [comment]
also noticing that failing calls to install deps, say `mason install curl system` might have fatal errors but appears silent currently.

**Comment by jfirebaugh** [comment]
Fixed in 009a28943c510b0de93b903ca191e586d08cd2e9.
