### ISSUE TITLE
Memory issue adding thousands of annotations

### ISSUE THREAD

**Issue by catual** [mapbox/mapbox-gl-native#6091]
Hello!

Don't  know if it is possible, but i have tried to add 30,000 marker to the mapView in iOS but i get a memory issue. If i try adding 2,000 markers, i see the memory growing, but when the markers are shown, the memory goes back to a minimum. Is there a possibility to add that many markers at once?

```
@IBAction func addALotOfMarkers(sender: AnyObject) {
        let annos = PoisAndLinesFactory.generate30000Pois() //[MGLPointAnnotation]

        let everyXthElement = 100
        let iteration = annos.count / everyXthElement

        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), {

            for i in 0...iteration {
                let startIndex = i*everyXthElement
                let endIndex = startIndex+everyXthElement - 1 > annos.count-1 ?
                startIndex+everyXthElement - 1 : annos.count-1

                dispatch_async(dispatch_get_main_queue(), {
                let subArray = Array(annos[startIndex...endIndex])

                    autoreleasepool({
                        let subArray = Array(annos[startIndex...endIndex])
                        self.mapView.addAnnotations(subArray)
                    })
                })
            }
        })
    }
```

the heap produced by the function on a iPad air 2:

![untitled 8 copy](https://cloud.githubusercontent.com/assets/20861425/17815391/7108c9e4-6634-11e6-9fb8-117a28cae1cb.jpg)

Thanks for the amazing framework!

**Comment by jfirebaugh** [comment]
For large numbers of points, you'll get best performance by creating and populating a symbol layer using the runtime styling API, [such as in this example](https://www.mapbox.com/ios-sdk/examples/runtime-multiple-annotations/).
