### ISSUE TITLE
Unrecognized selector crash when suspending and removing MGLOfflinePack

### ISSUE THREAD

**Issue by Jackhammer42** [mapbox/mapbox-gl-native#6092]
Platform: iOS 9.3.4
Mapbox SDK version: 3.3.1
### Steps to trigger behavior

When I try to cancel the download of an MGLOfflinePack, i get this error:

```
-[NSTaggedPointerString offlineRegionStatusDidChange:]: unrecognized selector sent to instance 0xa0000000148344a4
2016-08-19 16:53:08.187 ChemPark[659:57661] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString offlineRegionStatusDidChange:]: unrecognized selector sent to instance 0xa0000000148344a4'
*** First throw call stack:
(0x181aa6db0 0x18110bf80 0x181aadc4c 0x181aaabec 0x1819a8c5c 0x100f484e4 0x102ba9a7c 0x102ba9a3c 0x102baf4e4 0x181a5cd50 0x181a5abb8 0x181984c50 0x18326c088 0x186c6e088 0x1002b1c70 0x1815228b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

I am using this code for the task:

```
let packs = MGLOfflineStorage.sharedOfflineStorage().packs

        for pack in packs! {

            pack.suspend()

            MGLOfflineStorage.sharedOfflineStorage().removePack(pack, withCompletionHandler: nil)

        }
```

It seems similar to https://github.com/mapbox/mapbox-gl-native/issues/4394, except this issue only seems to happen if i cancel the download, not after successfully completing the download.
### Expected behavior

I was hoping to stop the download.
### Actual behavior

Crash

**Comment by 1ec5** [comment]
Related to #5538.

**Comment by 1ec5** [comment]
Does the crash occur if you only remove the pack instead of canceling it? Removing the pack should cancel it automatically, if asynchronously.

**Comment by Jackhammer42** [comment]
I tried 

```
let packs = MGLOfflineStorage.sharedOfflineStorage().packs

        for pack in packs! {


            MGLOfflineStorage.sharedOfflineStorage().removePack(pack, withCompletionHandler: nil)

        }
```

Same crash, after a few starting and canceling cycles.


When I trie

```
let packs = MGLOfflineStorage.sharedOfflineStorage().packs
        
        for pack in packs! {
            
            
            let priority = DISPATCH_QUEUE_PRIORITY_DEFAULT
            dispatch_async(dispatch_get_global_queue(priority, 0)) {
                
                MGLOfflineStorage.sharedOfflineStorage().removePack(pack, withCompletionHandler: nil)
                dispatch_async(dispatch_get_main_queue()) {
                    
                }
            }
         
         
         
         
         }
```

It seems to work for a little more starting a canceling cycles, but it crashes in the end as well.

**Comment by marceln** [comment]
This isn't fixed in any of the latest versions, right?

**Comment by 1ec5** [comment]
#6186 should’ve made this crash less likely to occur; as a stale pointer issue, it’s difficult to say for sure that the crash is fixed.

**Comment by Jackhammer42** [comment]
I will try to produce the error with the latest version and give you feedback about the result.

**Comment by Jackhammer42** [comment]
sorry, still seeing this error :( (v. 3.5.0)

**Comment by 1ec5** [comment]
MGLOfflinePack would really benefit from the sort of `std::any` usage being introduced to MGLStyleLayer and MGLSource in #8626 for #7375.

/cc @boundsj @jfirebaugh

**Comment by georgejlee** [comment]
I have seen this crash as well. I am on Mapbox-iOS-SDK-3.6.4. I've attached a stack trace. The line that crashes is `[pack offlineRegionStatusDidChange:status];`:

```
void MBGLOfflineRegionObserver::statusChanged(mbgl::OfflineRegionStatus status) {
    dispatch_async(dispatch_get_main_queue(), ^{
        [pack offlineRegionStatusDidChange:status];
    });
}
```

I have tried suspending the offline pack before removing as well as removing the offline pack without suspending, crashes occur in both cases. Can you help? This is one of the most frequent crashes in our app now.

[Unknown.txt](https://github.com/mapbox/mapbox-gl-native/files/1395468/Unknown.txt)

**Comment by georgejlee** [comment]
This is still happening for me on 3.7.0. Any updates on this? Thanks.
