### ISSUE TITLE
gleRunVertexSubmitARM

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#61]
I started to benchmark the poor performance we have on iOS. To benchmark this, I created a small set of scripts that can programatically generate vector tiles: https://gist.github.com/kkaefer/378bd150fe52de8e74b1

I found that our drawing is completely bound by the CPU. We aren't doing anything fancy on the CPU, so that shouldn't be the case. Instruments revealed that the calls to `gleRunVertexSubmitARM` are taking up most of the time. This function shouldn't be called by `glDrawArrays` because it means that it's transferring all vertices to the GPU on every frame, which of course bogs down rendering tremendously.

I'm not sure why this is happening. Does anyone have ideas?

**Comment by jfirebaugh** [comment]
@kkaefer Is this still relevant?

**Comment by kkaefer** [comment]
Haven't seen this in a while. My hunch is that it only happens on memory-constraint devices when the GPU memory is too small to hold all of the geometries.
