### ISSUE TITLE
Move Annotation animate like userLocation

### ISSUE THREAD

**Issue by iBinh** [mapbox/mapbox-gl-native#6103]
I want to move a custom annotation like MGLUserLocation when user is moving. How can I do this?
@1ec5

**Comment by 1ec5** [comment]
In v3.4.0-alpha.2, you can implement `-[MGLMapViewDelegate mapView:viewForAnnotation:]` to return a custom subclass of MGLUserLocationAnnotationView when the annotation is equal to `mapView.userLocation`. Official examples haven’t been posted yet, but see [MBXViewController](https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.4.0-alpha.2/platform/ios/app/MBXViewController.m#L712-L722) and [MBXUserLocationAnnotationView](https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.4.0-alpha.2/platform/ios/app/MBXUserLocationAnnotationView.m) for an example of how to use this new API.
