### ISSUE TITLE
MGLStyle.styleClasses should be an NSSet

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6104]
We moved the style class API to MGLStyle for #5974. While we’re at it, we should change the type of `MGLStyle.styleClasses` from an NSArray of NSStrings to an NSSet of NSStrings, because the order doesn’t matter.

/cc @frederoni

**Comment by jfirebaugh** [comment]
> the order doesn’t matter

I believe the order does matter. If multiple style classes set the same property, one of them wins, and this defines an ordering.

**Comment by 1ec5** [comment]
Ah, that makes sense. In that case, we’ll eventually need to add more KVO accessors along the lines of #6097. We’re good here for the time being, though.
