### ISSUE TITLE
iOS Annotation Callout Delay

### ISSUE THREAD

**Issue by Jackhammer42** [mapbox/mapbox-gl-native#6106]
**Platform:** iOS 9.3.4
**Mapbox SDK version:** 3.3.1

### Steps to trigger behavior

I show only the title of the marker within the callout view, so nothing fancy is done here. After a fresh start of the app, the touch on the Annotation works as expected: The callout appears immediately.

But after i used the app a few minutes, there is a increasing delay between touch of the annotation an the appearence of the callout.

I implemented 

`mapView(mapView: MGLMapView, leftCalloutAccessoryViewForAnnotation annotation: MGLAnnotation) -> UIView?`

and

`mapView(mapView: MGLMapView, annotationCanShowCallout annotation: MGLAnnotation) -> Bool`

both are called immediately after the touch.

FYI: I use a custom image for the annotation in:

`mapView(mapView: MGLMapView, imageForAnnotation annotation: MGLAnnotation) -> MGLAnnotationImage?`

**Comment by 1ec5** [comment]
I’m unable to reproduce this issue in v3.3.4 on iOS 9, but I don’t think we fixed anything of this nature between v3.3.1 and v3.3.4. Are other touch gestures being recognized on a delay? Other animations?

**Comment by Jackhammer42** [comment]
I was able to trace down the issue: there was an unintentional interaction with an external project i used. Once i abandoned the project, everything is working fine.

**Comment by 1ec5** [comment]
Glad to hear the mystery is solved.
