### ISSUE TITLE
Optimise APK download size

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#611]
This is a catch all for ways to optimise the APK download size. We want to make Android GL a reasonably light download and dependency to attract developers to use it vs something that comes preinstalled e.g Google Maps API.

- [ ] Optimise native code - investigate compiler/linker flags
- [ ] Separate APKs for different CPU architectures - rather than having several copies of the native code in the APK
- [ ] ProGuard and other Android minification/optimisation tools should be enabled in the gradle build config

Currently we are sitting at a 8.7MB APK

**Comment by ljbade** [comment]
Some tips at http://blog.algolia.com/android-ndk-how-to-reduce-libs-size/

**Comment by Namec** [comment]
Thank You
