### ISSUE TITLE
[Android] Receiver not registered: null

### ISSUE THREAD

**Issue by DmitryTankovich** [mapbox/mapbox-gl-native#6113]
Caused by java.lang.IllegalArgumentException: Receiver not registered: null
       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:878)
       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1279)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:601)
       at com.mapbox.mapboxsdk.maps.MapView.onPause(SourceFile:547)

    @UiThread
    public void onPause() {
        // Register for connectivity changes
        getContext().unregisterReceiver(mConnectivityReceiver);
        mConnectivityReceiver = null;

        mMyLocationView.onPause();
    }

**Comment by tobrun** [comment]
Aren't able to reproduce locally, I'm guessing this bug report comes from a crash reporting tool, I'm handling this as an Android platform bug and working around this for now with:

```java
    /**
     * You must call this method from the parent's {@link Activity#onPause()} or {@link Fragment#onPause()}.
     */
    @UiThread
    public void onPause() {
        // Register for connectivity changes
        if (mConnectivityReceiver != null) {
            getContext().unregisterReceiver(mConnectivityReceiver);
            mConnectivityReceiver = null;
        }

        mMyLocationView.onPause();
    }

``` 
If this doesn't resolve the issue we should look into adding a `try-catch` block.

@DmitryTankovich feel free to review and add more information about the issue
