### ISSUE TITLE
Add support for pole-of-inaccessibility symbol placement

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-native#6115]
GL JS now supports pole-of-inaccessibility symbol placement for polygon geometries. We need to port this feature over to GL Native. 
- https://github.com/mapbox/mapbox-gl-js/issues/1231
- https://github.com/mapbox/mapbox-gl-js/pull/2678
- https://github.com/mapbox/mapbox-gl-test-suite/pull/111

cc @blanchg @jfirebaugh @mourner

**Comment by 1ec5** [comment]
The pole of inaccessibility algorithm will also come in handy for callout placement on selected shape annotations, as envisioned for #2082.

**Comment by 1ec5** [comment]
The first step is to port [Polylabel](https://github.com/mapbox/polylabel/) to C++ for use in this project.
