### ISSUE TITLE
Move class state back to Map

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#6118]
01edd4503c5b78a73ac8ce1ee1de8b403d76d4fc moved the state holding the list of active classes to `Style`. In gl-js, we had had previously (https://github.com/mapbox/mapbox-gl-js/issues/911, https://github.com/mapbox/mapbox-gl-js/pull/916) decided that `Map` was the correct holder of this state, because it is desirable for it to persist across style loads or reloads. This is particularly true on native, where reloads of a style can happen implicitly during revalidation. In that case, having the class list state reset, as currently happens, is unexpected.

If we make this change, we'll need to revert #5974.

cc @brunoabinader @1ec5 @frederoni

**Comment by jfirebaugh** [comment]
At a minimum, we need to remove [this line](https://github.com/mapbox/mapbox-gl-native/blob/cb33c861b4cfa82d7afcb5b9ec85d7797679a7d8/src/mbgl/style/style.cpp#L90) and add a test that a style reloaded due to revalidation does not reset the class list.

**Comment by 1ec5** [comment]
> If we make this change, we'll need to revert #5974.

MGLStyle accesses the class list through (a weak pointer to) MGLMapView and therefore through `mbgl::Map`, so there wouldn’t be a technical need to move the class methods back to MGLMapView. Semantically, would there be a problem with keeping the style class methods on MGLStyle?

**Comment by jfirebaugh** [comment]
> Semantically, would there be a problem with keeping the style class methods on MGLStyle?

Yes -- if the state belongs to the map object, it's misleading for the accessors to live on the style object (https://github.com/mapbox/mapbox-gl-js/pull/916#issuecomment-69059863).

**Comment by 1ec5** [comment]
OK, fair enough. (Annotation layers do persist across style changes, so it isn't unprecedented to have some style-related settings carry over. But I can't think of any downsides to keeping the class API on MGLMapView.)

**Comment by brunoabinader** [comment]
Good to know @jfirebaugh - I'm going to forward these changes into our Qt API - specifically `QQuickMapboxGLStyle`, putting class handling back to `QQuickMapboxGL` (Map).
