### ISSUE TITLE
implement proper error handling for attempts to mutate an unloaded style

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#6121]
#5753 is is lenient about the case where the style is mutated between when the loading of a style URL is requested and when it completes. GL JS throws in this case, and native should prohibit it as well.

Since this is a somewhat common developer error, we need to be particularly careful that whatever error core emits is properly translated into SDK-appropriate errors.

**Comment by 1ec5** [comment]
#3063 might be a model for surfacing this error as an Objective-C exception in the iOS and macOS SDKs.

**Comment by jfirebaugh** [comment]
This is no longer relevant after smart style diffing.
