### ISSUE TITLE
Jump to style’s default viewport on initialization

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6129]
The map should jump to the default center coordinates, zoom level, bearing, and pitch as soon as the first style loads after initialization. Switching from one style to another probably shouldn’t change the viewport.

Complicating matters, the initial viewport may be overridden for various reasons. For example, state restoration would take place upon initialization. Or the developer may programmatically set the viewport immediately after initializing the map view but before the style loads. The style shouldn’t be able to clobber a viewport set this way.

In the iOS and macOS SDKs, MGLMapView’s initial center coordinates, zoom level, and direction can be specified in a storyboard. Unfortunately, storyboard-defined properties are set [asynchronously, in piecemeal fashion](https://github.com/mapbox/mapbox-gl-native/blob/63cce78cf1597ba5879227f2298bda52e91e4e04/platform/ios/src/MGLMapView.mm#L4983-L4988), after the MGLMapView object is initialized and thus sometime after `mbgl::Map` is initialized. The style’s default viewport shouldn’t clobber this asynchronously set viewport, either.

In https://github.com/mapbox/mapbox-gl-native/pull/6127#issuecomment-241899812, @jfirebaugh suggests implementing the initial viewport behavior in core. That could work for the iOS and macOS SDKs, as long as we account for the cases above. Perhaps methods like `mbgl::Map::setLatLng()` and `easeTo()` could shut off any style-default-viewport functionality for the lifetime of the map.

/cc @friedbunny @tobrun

**Comment by tobrun** [comment]
Linking the related properties van style spec [here](https://www.mapbox.com/mapbox-gl-style-spec/#root-center)

> In #6127 (comment), @jfirebaugh suggests implementing the initial viewport behavior in core. That could work for the iOS and macOS SDKs, as long as we account for the cases above.

For Android this would work as well, this requirement fits well in the Android concept of `OnMapReady`, this is a callback that is called after the style has loaded. Until that point a user can't instantiate any animations or do camera manipulations other than the initial camera position (this can be set in layout xml or using the `MapboxMapOptions` using `Lat`, `Lng`, `zoom` en `tilt`). In case a user provides another initial camera position, it should override the data coming from the style.

API wise, how do you see this happening? add parameters to `setStyleUrl` to have an opptional moveViewport? make style loading a multi step process (calling multiple methods instead of one)?

**Comment by 1ec5** [comment]
Ideally there would be no API change, even at the core level. Core would jump to the default viewport internally upon loading the first style. Only the first style ever loaded would ever cause a jump, and setters on mbgl::Map like setLatLng() would automatically turn off that functionality. So if the developer calls MapView.setLatLng() before the style finishes loading, the end result would be just as it is today.

**Comment by incanus** [comment]
One idea: this could be as simple as a `Map` property called e.g. `initialCameraOptions`, perhaps as a `util::optional` or `boost::optional`, that begins as the same default viewport that we are using now, gets set atomically by the style parse if non-`NULL` at that point, and that any of the relevant setters would just `NULL` out, preventing such auto-load (either style-backed or default) behavior.

**Comment by tobrun** [comment]
Looked into where the values are being set:

> Style::setJSON(const std::string& json)

This function is responsible for parsing a style and setting up Style values: eg.

```cpp
defaultLatLng = parser.latLng;
defaultZoom = parser.zoom;
defaultBearing = parser.bearing;
defaultPitch = parser.pitch;
```

This function than notifies an observer letting map.ccp know that the style has been loaded.

**Comment by tobrun** [comment]
I have something working:

Not manipulating the camera results in showing the default from the style:

![device-2016-10-06-103047](https://cloud.githubusercontent.com/assets/2151639/19145642/2b72f23c-8bb0-11e6-87b4-065c3d4e8027.png)

Manipulating the camera in java:

```java
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(@NonNull MapboxMap mapboxMap) {
                DynamicMarkerChangeActivity.this.mapboxMap = mapboxMap;
                mapboxMap.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(51.506675, -0.128699), 10));
            }
        });
```

Results in:

![device-2016-10-06-102437](https://cloud.githubusercontent.com/assets/2151639/19145659/4223e194-8bb0-11e6-8b9f-3cc02830d9b0.png)

or manipulating in xml:

```xml
           <com.mapbox.mapboxsdk.maps.MapView
                app:center_latitude="51.506675"
                app:center_longitude="-0.128699"
                app:zoom="10" />
```

Results in:

![device-2016-10-06-103433](https://cloud.githubusercontent.com/assets/2151639/19145701/7d9d6d9e-8bb0-11e6-986a-0cf3ceb6adb9.png)

or manipulating via MapboxMapOptions:

```java
        MapboxMapOptions options = new MapboxMapOptions()
                .camera(new CameraPosition.Builder()
                        .target(new LatLng(51.506675, -0.128699))
                        .zoom(10)
                        .build());
```

Results in:

![device-2016-10-06-104326](https://cloud.githubusercontent.com/assets/2151639/19146081/388f30d2-8bb2-11e6-8467-fab1c5c36895.png)
