### ISSUE TITLE
Convert all stdout/stderr prints to use Log functions

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#613]
There is still some code that writes to stdout/stderr instead of the Log functions. For example `tile_parser.cpp`

This means important error messages never make it to the log on Android and makes debugging harder.

So all code using some sort of print function needs to be found and changed to Log.

Also anywhere that throws a C++ exception needs to also print a Log::Error before it throws in case we don't catch the exception and we crash instead.

**Comment by ljbade** [comment]
Still need to get on to this.

However I notice some more printfs have crept in, /cc @ansis

**Comment by tmpsantos** [comment]
@ljbade I can take this one as I'm working also on #882

**Comment by ljbade** [comment]
Cool @tmpsantos that would be awesome. I found their was a mix of C++ style `cout`/`cerr` and the various C APIs such as `*printf` and a few others.

You will probably want to regex the repo to find them all.

**Comment by ljbade** [comment]
@jfirebaugh after they have been converted, we will have to make sure everyone knows not to commit code not using the `Log`. I will try to keep an eye on this in PRs.
