### ISSUE TITLE
Markers are created at the wrong place

### ISSUE THREAD

**Issue by Pilou44** [mapbox/mapbox-gl-native#6131]
I've got an issue on Android with mapbox 4.1.0: when I add markers they are often displayed at the wrong place. But as soon as I pan the map they move to the right place.
I join screen captures of my example. I calculate an itinerary and display it with a polyline. Markers A an B represent start and end of itinerary. 
Here it what it looks like on creation: 
![1](https://cloud.githubusercontent.com/assets/10031050/17923953/c1885b54-69e6-11e6-801b-f728de24883e.png)
Here is what it looks like just after I move the map a little:
![2](https://cloud.githubusercontent.com/assets/10031050/17923957/c96a5c8c-69e6-11e6-9162-90375acfbb36.png)
I've seen it with Android 4.4 .

**Comment by tobrun** [comment]
@Pilou44 thanks for reaching out and reporting your issue.
Are these markers extending from Marker or MarkerView?
Have you tried using `4.2.0-beta1` to see if this resolves your issue?

The related gradle dependency for this is:
```
compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0-beta.1@aar'){
```

**Comment by Pilou44** [comment]
These markers are extending from MarkerView.
I've not tried 4.2.0-beta1. I come back to you as soon as I've tested.

**Comment by Pilou44** [comment]
Yes, this issue is reproducible with 4.2.0-beta1

**Comment by tobrun** [comment]
Could you test if `mapboxMap.getMarkerViewManager().invalidateViewMarkersInVisibleRegion()` after adding them resolves it?

**Comment by Pilou44** [comment]
I've tried doing it after adding the two markers but doesn't resolve the issue.

**Comment by tobrun** [comment]
Could you maybe show me the code how you are adding them to the map?

**Comment by Pilou44** [comment]
I've identified the problem. Here si how my application works:
- I display the map
- I display a fragment to configure an itinerary that hides the map
- I add polylines, markers and move the camera to a position that fit the itineraries using 'easeCamera' function whereas the map is still hidden
- I remove the fragment : the map is displayed but markers are at the wrong position, as if they were displayed with the previous camera position and zoom. As soon as I pan the map the markers show at the right positions.

To fix it, I simply replace 'easeCamera' by 'moveCamera'. There's no visual difference a the camera is moved while the map is hidden but markers are now shown at the right positions from the start.

I cannot share the code as I work for a company, but I hope this will help.

**Comment by cammace** [comment]
The camera should always be set initially in xml or `MapboxMapOptions`. This should set the camera position of the map before the tiles are downloaded. Sounds like you have resolved this issue and I have not been able to reproduce.
