### ISSUE TITLE
[Android] How to refer to drawable in background-pattern?

### ISSUE THREAD

**Issue by s3rge** [mapbox/mapbox-gl-native#6134]
**Platform: Android 4**
**Mapbox SDK version: 4.2.0-beta.1**

How to refer drawable resource in `background-pattern` layer style param?
https://www.mapbox.com/mapbox-gl-style-spec/#paint-background-pattern

Tried  `drawable://` scheme - it does not work.

**Comment by jfirebaugh** [comment]
This isn't possible: values from `background-pattern` must refer to identifiers of icons already contained within the style's sprite. You'll need to add the image to the style.

See https://github.com/mapbox/mapbox-gl-style-spec/issues/485 for an issue tracking support for URL-valued icon/pattern properties.
