### ISSUE TITLE
Android Styling API Availability

### ISSUE THREAD

**Issue by lyptt** [mapbox/mapbox-gl-native#6135]
Hi there, I've noticed that for #2812 you mentioned that this functionality would be available once #5610 and #5642 were done. These tickets are now closed and the milestone is set for the 4.2.0 version of the SDK, but I don't see the functionality mentioned in the latest beta/SNAPSHOT versions.

Is there any word on when this functionality will land in a release of the Android SDK?

**Comment by cammace** [comment]
Thanks for reaching out, you're correct that the style API has been merged. You can take a look at [this issue](https://github.com/mapbox/mapbox-android-demo/issues/115) showing off a bunch of the examples you can make with the API or download the [Demo app](https://play.google.com/store/apps/details?id=com.mapbox.mapboxandroiddemo) to try them out. To create a dotted line, you can add a LineLayer and there should be a property similar to `line-dasharray` that you can use. For future support questions, please contact us through our [support page](https://www.mapbox.com/contact/).
