### ISSUE TITLE
polyline is broken in a Android app?

### ISSUE THREAD

**Issue by zhangkaiyue0701** [mapbox/mapbox-gl-native#6136]
I use addPolyline() to draw line on the mapview.

`mapView.getMapAsync(mapboxMap -> lastPolyline = mapboxMap.addPolyline(
            new com.mapbox.mapboxsdk.annotations.PolylineOptions().add(latLngs).color(color).width(4)));`

Because I need show pace through colors of line, I add a line through two points. First, I draw a line through first point and second point. Then, I draw a line through second point and third point. But result is unexpected. The line is broken. How to solve it?

![device-2016-08-24-190314](https://cloud.githubusercontent.com/assets/13346163/17928789/10e09016-6a2f-11e6-9b0e-cfece9ed43e3.png)

**Comment by cammace** [comment]
Hey @zhangkaiyue0701 thanks for reaching out, could you more additional code, everything in that snippet looks correct. I created something similar to what you described and got it working correctly:

```java
List<LatLng> points = Some list of points making up route

...

if (points.size() > 0) {

                lastPoint = points.get(0);

                for(LatLng point : points) {

                    // Create a random color for polyline segment
                    Random rnd = new Random();
                    int color = Color.argb(255, rnd.nextInt(256), rnd.nextInt(256), rnd.nextInt(256));

                    // Draw segment on map
                    map.addPolyline(new PolylineOptions()
                            .add(lastPoint)
                            .add(point)
                            .color(color)
                            .width(4));
                    
                    lastPoint = point;
                }
            }
```

and the result looks like:
<img src="https://cloud.githubusercontent.com/assets/5652865/17933547/782b9330-69e2-11e6-8d09-c3fa61aae573.png" width=360/>

**Comment by zhangkaiyue0701** [comment]
The mean is that the joint of two lines is not combined closely, there is a blank space, especially when line is thick.

**Comment by jfirebaugh** [comment]
@zhangkaiyue0701 This is expected behavior -- because you are creating multiple lines, there are no line joins between them.

It sounds like what you want to do is vary the color along a single line. Unfortunately, we don't have support for that right now. We're tracking that request in https://github.com/mapbox/mapbox-gl-style-spec/issues/349.
