### ISSUE TITLE
Possibly release Android version on Maven

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#614]
We should evaluate whether this is a good idea and then do it when it is. I'm not sure what the tone of doing so indicates (stability? or just a convenience?) but we do a similar thing with [iOS in CocoaPods](https://github.com/mapbox/mapbox-gl-cocoa#installation) albeit not in the central repository yet.

**Comment by ljbade** [comment]
@bleege Just mentioning that your work should close this.

**Comment by bleege** [comment]
Yep, #826 will take care of this.  For the sake of clarity we're going to mirror what the Raster SDK has done for formats (.aar as primary) and distribution (via Maven Central).  We still need to research `.apklib` to see how it plays with JNI.
