### ISSUE TITLE
[node] Style parse errors are not handled

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#6143]
Parsing errors won't throw an exception but rather a `MapChange` signal. Node bindings will never detect this error and potentially starve waiting.

Depends on #6142

/cc @mikemorris

**Comment by mikemorris** [comment]
Simple invalid style errors should be caught preemptively in https://github.com/mapbox/mapbox-gl-native/blob/master/platform/node/src/node_map.cpp#L190-L208. What sort of condition could cause this state? I would think something like an invalid URL would be the responsibility of the `FileSource` implementation to handle.

**Comment by tmpsantos** [comment]
@mikemorris You are right about requests errors being already handled. This issue is the unlikely parse error that is currently tested by checking the error log.

I pushed a PR on #6151 adding a exception for it with tests.
