### ISSUE TITLE
Map markers rendered beneath polygon layer

### ISSUE THREAD

**Issue by damianflannery** [mapbox/mapbox-gl-native#6157]
I'm trying to render map markers on top of some polygons I have added as layers from geojson but they are currently being rendered below (and masked by) the polygon layers - see screenshot below:

[https://dl.dropboxusercontent.com/u/27007357/mapbox/device-2016-08-25-162716.png
](url)

Is this a bug or am I missing something?

**Platform:**
Android 6.0.1

**Mapbox SDK version:**
Release Android v4.2.0-beta.2

### Steps to trigger behavior

```
//Add polygons
                String json = getJson(getResources().openRawResource(R.raw.westfield_units_zero));
                GeoJsonSource urbanAreasSource = new GeoJsonSource("westfield-geojson", json);
                mapboxMap.addSource(urbanAreasSource);
                FillLayer fillLayer = new FillLayer("westfield", "westfield-geojson");
                fillLayer.setProperties(
                    fillColor(ContextCompat.getColor(this, R.color.colorPrimary)),
                    fillOpacity(0.7f)
                );
                mapboxMap.addLayer(fillLayer);

                //Add polygons again as linelayer because I cant see a way to set the stroke width of the fill layer
                Layer linesLayer = new LineLayer("lines", "westfield-geojson");
                mapboxMap.addLayer(linesLayer);

                //Add markers
                String jsonPoi = getJson(getResources().openRawResource(R.raw.poisym));
                GeoJSONObject geoJSON = GeoJSON.parse(jsonPoi);
                GeoJsonParser parser = new GeoJsonParser(geoJSON.toJSON());
                for (GeoJsonFeature feature : parser.getFeatures()) {
                    if (feature.getGeometry().getType().equals("Point")) {
                        GeoJsonPoint point = (GeoJsonPoint) feature.getGeometry();

                        IconFactory iconFactory = IconFactory.getInstance(this);
                        Drawable iconDrawable = ContextCompat.getDrawable(this, R.drawable.purple_marker);
                        Icon icon = iconFactory.fromDrawable(iconDrawable);
                        LatLng latLng = new LatLng(point.getCoordinates().latitude, point.getCoordinates().longitude);

                        // Add the custom icon marker to the map
                        mapboxMap.addMarker(new MarkerOptions()
                            .position(latLng)
                            .title("Hello")
                            .snippet("Test")
                            .icon(icon));
                    }
                }
```

### Expected behavior
I would expect markers to be rendered on top

### Actual behavior
Markers are rendered below polygon layers

**Comment by tobrun** [comment]
@damianflannery thank you for reaching out. When it comes to runtime styling, there is only 1 way to manipulate the ordering o flayers an this through the 2 param add method as:

```java

    @UiThread
    public void addLayer(@NonNull Layer layer, String before) {
        getMapView().getNativeMapView().addLayer(layer, before);
    }

```
Where the before string is the id of the layer that was already added. To move your polylines below markers the only thing we need to find out is the name of the markers layer. I took a peek at the `annotation_manager.cpp` class and there I'm seeing `const std::string AnnotationManager::PointLayerID = "com.mapbox.annotations.points";`. Without trying this out, my guess is that we can use that String as id for `before` in `addLayer`

Would you be able to try this out?
Could you let us know if this resolves the issue?

Thanks!

**Comment by damianflannery** [comment]
@tobrun thanks, that worked! 

I attempted to solve it that way originally but I couldn't find any documentation on what layers are rendered in the map and there doesn't seem to be an api call to list them (only get them by name).

Would it be possible to add a method  `List<Layer> getLayers()` and / or some docs on the layers that are in the map? I think this would be extremely useful.
