### ISSUE TITLE
MGLGeoJSONSource.geoJSONData should be writeable

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6159]
MGLGeoJSONSource’s `geoJSONData` property should be read-write. (Should the `URL` property be read-write too?)

This is the iOS/macOS counterpart to #5906 on Android.

/cc @frederoni @ivovandongen

**Comment by ivovandongen** [comment]
@1ec5 There is a setter for `URL` in the core class, so it can be read-write as well. 

Atm, this is blocked as the updates aren't handled properly yet. I think this might be related to #5701

**Comment by boundsj** [comment]
ref: https://github.com/mapbox/mapbox-gl-native/issues/6264

**Comment by 1ec5** [comment]
Unblocked by #6347.

**Comment by boundsj** [comment]
Android implementation landed in https://github.com/mapbox/mapbox-gl-native/pull/6054

**Comment by boundsj** [comment]
iOS implementation done in https://github.com/mapbox/mapbox-gl-native/pull/6793
