### ISSUE TITLE
Map::setStyleJSON crashes if given malformed JSON

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#616]
Currently if you pass Map::setStyleJSON some malformed JSON it crashes.

I have traced it to the JSON parsing code throwing a C++ exception that is never caught by Map::setStyleJSON.

We should add a try/catch here.

The flow I was thinking was:
- try to load JSON
- if exception, catch, switch back to the previously loaded style, and print an error message

Thoughts?

**Comment by jfirebaugh** [comment]
We have a test for this [here](https://github.com/mapbox/mapbox-gl-native/blob/master/test/api/set_style.cpp) and it doesn't crash.
