### ISSUE TITLE
Feature querying should return existing annotations

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6178]
When the feature querying API detects a feature in an annotation layer, it should somehow return the MGLAnnotation object that the feature represents – that is, the same MGLAnnotation object that was added to the map to place the feature on the map.

/cc @boundsj

**Comment by 1ec5** [comment]
In particular, the returned feature must not be tiled. Otherwise, the developer will immediately run into a roadblock: #6538.

**Comment by friedbunny** [comment]
This also includes annotations that happened to conform to `MGLFeature` — the additional `identifier` and `attributes` properties will not be persisted if such an object is added as an annotation.

To make full use of `MGLFeature`-conforming annotations, instead add them to the map using the runtime styling API.

**Comment by 1ec5** [comment]
> This also includes annotations that happened to conform to `MGLFeature` — the additional `identifier` and `attributes` properties will not be persisted if such an object is added as an annotation.

This will become apparent to the developer at compile time once we fix #7454.

**Comment by 1ec5** [comment]
Still needed as a prerequisite for #6181.
