### ISSUE TITLE
Depend on URL parsing library

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6183]
We’ve had some hairy issues with the code in `mbgl::util::mapbox` that relies on artisanal string parsing to manipulate URL components. For example: #5554 #5723. At one point, it was manageable because we were only manipulating schemes and paths. But increasingly we need to work with query parameters as well (#6182). I guess I’m spoiled by the robustness of `URL` on the Web and NSURL and NSURLComponents on Apple platforms, which provide object-oriented, RFC-compliant URL parsing. Could we make `mbgl::util::mapbox` depend on a similarly robust, well-tested URL parsing library for C++?

/cc @kkaefer @jfirebaugh

**Comment by jfirebaugh** [comment]
I'd love to use a well-tested URL parsing library for C++, providing it meets other quality metrics. The `uri` class from [cpp-netlib](http://cpp-netlib.org/) seems to be the leading contender. I can't find any official API reference for it, but it was the basis for a [standards proposal](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2012/n3420.html) and there is [standalone code](https://github.com/cpp-netlib/uri) floating about.

It looks promising, but I also see some warning signs. We'd probably need to devote some time to trying it out and seeing if it meets our quality bar, or whether we'd need to write something from scratch.

**Comment by 1ec5** [comment]
I wonder how much trouble it would be to extract [`WebCore::URLParser`](https://github.com/WebKit/webkit/blob/3711f967d0e7942ed92bf3b82203765706d9c507/Source/WebCore/platform/URLParser.h) from the WebKit project. It depends on WTF for a StringBuilder class, but that doesn’t seem like a showstopper.

**Comment by springmeyer** [comment]
Does not appear maintained, so not a viable contender (https://github.com/bnoordhuis/uriparser2), but dropping here nonetheless for reference.

**Comment by jingsam** [comment]
How about [http-parser](https://github.com/nodejs/http-parser). It has a function called `http_parser_parse_url`. Since it is used by Nodejs, so we can keep consistency with mapbox-gl-js in URL handling

**Comment by kkaefer** [comment]
Node.js' `url` module parsing functionality is done in https://github.com/nodejs/node/blob/master/lib/url.js, and mapbox-gl-js doesn't use Node.js at all since it's typically run in the browser. That being said, we could look at porting the JavaScript code in Node.js to C++.

As far as the scope of this goes: Do we need Punycode parsing/normalization? IPv6 IP support? Auth (`https://foo:bar@example.com`) handling?

**Comment by jingsam** [comment]
Another thing I was worried about is an object-oriented, RFC-compliant URL parsing library would be too heavy for Mapbox GL Native. Benchmarks would also affected. So I would rather suggest to keep it simple.

@kkaefer I do not think we need these Punycode staff features until some use cases come out.

**Comment by jfirebaugh** [comment]
Good here with #7464.

**Comment by kkaefer** [comment]
https://daniel.haxx.se/blog/2018/09/09/libcurl-gets-a-url-api/
