### ISSUE TITLE
[Android] Expose additional features for marker InfoWindow

### ISSUE THREAD

**Issue by chewbyte** [mapbox/mapbox-gl-native#6184]
I'm currently making heavy use of InfoWindow, overriding the default View to display my own custom layouts. Currently the nature of the application I'm creating requires these InfoWindows to stay open at all times. So far I've managed to get all markers selected by looping through the markers and using mapboxMap.selectMarker(m); to open them all in conjunction with mapboxMap.setAllowConcurrentMultipleOpenInfoWindows(true); to allow more than one marker to have an InfoWindow open at a time.

The issue however is that whenever the map is clicked all the InfoWindows close, and clicking any InfoWindow will close it. Is there any current functionality that forces InfoWindows open, to the point of never being able to close them if desired, or if not, may such functionality be considered for  implementation in a future release?

**Comment by tobrun** [comment]
@chewbyte thank you for reaching out. We currently support this configuration in the `UiSettings#setDeselectMarkersOnTap(boolean)` method. Calling this and passing false should avoid closing the InfoWindow for the described use-case. Reach out if you have any other questions!

**Comment by chewbyte** [comment]
Thank @tobrun, that's a very useful method. That works great for stopping the InfoWindows from closing when the map is touched. However if the InfoWindows are touched themselves they still close. I'm currently using the following code, but I'm now wondering whether there's a more glamorous way of doing this other than ovveriding the OnTouch of the InfoWindow.

```
m.getInfoWindow().getView().setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View view) {
                            mapboxMap.selectMarker(m);
                        }
                    });
```

**Comment by tobrun** [comment]
You should be able to control that event through `Mapbox#setOnInfoWindowClickListener` and return true to indicate the event is handled thus the system will not handle it as the default implementation.
