### ISSUE TITLE
Add mapbox_ prefix in front of resource IDs

### ISSUE THREAD

**Issue by vanshg** [mapbox/mapbox-gl-native#6190]
```
The resource @color/black is marked as private in com.mapbox.mapboxsdk:mapbox-android-sdk. 

Private resources should not be referenced; they may not be present everywhere, and even where they are they may disappear without notice. 
```

Not a huge deal, but if I have my own color resource called black (or white) I get this warning. Considering that my value and the mapbox value are the same, this isn't a huge deal, but I believe the warnings would go away if there was some kind of a prefix in front of the color resource in the library (such as `mapbox_`)

**Comment by tobrun** [comment]
We tried out using the libPrefix setup with this isssue https://github.com/mapbox/mapbox-gl-native/issues/3119: 

```groovy
android {
  resourcePrefix 'mylib_'
}
```

While we were satisfied with the access token resource name, we were not so much with the rest of the requirements in https://github.com/mapbox/mapbox-gl-native/issues/4021. I think it's time to look into abovegain and possibly making it happen.

cc @mapbox/android

**Comment by tobrun** [comment]
this has happened in #6593, closing
