### ISSUE TITLE
Remove SupportMapFragment and support for v4

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#6192]
Capturing from https://developer.android.com/topic/libraries/support-library/revisions.html:

Note: Release 24.2.0 removes support for Android 2.2 (API level 8) and lower. Classes and methods that exist only to serve those system versions are now marked as deprecated and should no longer be used. These deprecated classes and methods may be removed in a future release.

We should look into removing the dependency and the related classes in our SDK. If not we should at least look into refactoring some code from both SupportMapFragment or MapFragment in https://github.com/mapbox/mapbox-gl-native/pull/5984#issuecomment-243095002.

Thoughts @mapbox/android?

**Comment by cammace** [comment]
It doesn't look like `android.support.v4.app.Fragment` is deprecated but the documentation for it says:
> Used to write apps that run on platforms prior to Android 3.0

thats API 11 while our SDK only supports 15 and higher. I'm all for removing it just note that [Google](https://developers.google.com/android/reference/com/google/android/gms/maps/SupportMapFragment) still offers this API.

Also noting that we should allow users to extend `MapFragment` (currently it's final).

**Comment by kjkrum** [comment]
The basic ability to use fragments isn't the only thing that the support library brings to lower API levels.  It also provides features such as nested fragments, which are otherwise unavailable below API 17.

**Comment by tobrun** [comment]
Thank you for the input! Not actionable, closing.
