### ISSUE TITLE
Static framework requires -ObjC linker flag

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#6195]
**Platform:** iOS
**Mapbox SDK version:** v3.3.4 through v3.4.0-alpha.2

Attempting to use the static framework results in a blank view and `Unknown class MGLMapView in Interface Builder file.`. Adding the `-ObjC` linker flag in Build Settings fixes this.

We’ve flipped back and forth between requiring this flag or not. [INSTALL.md](https://github.com/mapbox/mapbox-gl-native/blob/8deb7aaa79ccb96812d94d3d49e13bf49fe9308f/platform/ios/INSTALL.md) and [pod-README.md](https://github.com/mapbox/mapbox-gl-native/blob/8deb7aaa79ccb96812d94d3d49e13bf49fe9308f/platform/ios/docs/pod-README.md) don’t currently mention it, but they evidently should.

**Comment by 1ec5** [comment]
Reopening to fix the static flavor of the podspec too, per https://github.com/mapbox/mapbox-gl-native/pull/6213#issuecomment-243693614.
