### ISSUE TITLE
Target API 24 (Android Nougat)

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#6197]
The Mapbox Android SDK [currently targets](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/gradle.properties) API level 23 (Marshmallow) but Android Nougat (API level 24) has just been released. We should eventually set `android:targetSdkVersion` to API 24. Let's use this ticket to track this progress

A few things to note:
1. Targeting API 24 will force us to update to version 24.x of the Android Support libraries accordingly. This requires changes from developers (i.e. update to API 24 or add exclusion rules).
2. In order to properly target API level we need API breaking changes (e.g. https://github.com/mapbox/mapbox-gl-native/issues/5910). Therefore, we won't be doing this as part of the 4.x series.
3. Note that this does not affect `android:minSdkVersion` which remains at API level 15.

/cc: @mapbox/android

**Comment by zugaldia** [comment]
Related, we might be able to optimize our use of the support libraries (it's being chopped up into smaller modules): https://commonsware.com/blog/2016/08/30/breaking-up-artifact-is-not-that-hard-to-do.html.

**Comment by zugaldia** [comment]
Related: Update to LOST 2.0 https://github.com/mapbox/mapbox-gl-native/issues/6537.

**Comment by zugaldia** [comment]
Speaking of Android 7.0, [Android 7.1 will be entering into Developer Preview](http://android-developers.blogspot.com/2016/10/android-71-developer-preview.html) mode later this month.

**Comment by tobrun** [comment]
Only lost in #6537 needs to be fixed before closing this ticket, other related tickets have been PR'ed in #6390 and #6830.

**Comment by tobrun** [comment]
Lost is PR'ed in https://github.com/mapbox/mapbox-gl-native/pull/7494. No actions left to pick up. Closing.
