### ISSUE TITLE
User dot doesn’t animate between locations

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6203]
#1582 has regressed. While user tracking mode is off, the user location annotation view no longer animates between locations as location updates come in.

This issue reproduces in v3.4.0-alpha.3 but not v3.4.0-alpha.2.

/cc @friedbunny @incanus

**Comment by friedbunny** [comment]
Tracked this down to https://github.com/mapbox/mapbox-gl-native/pull/5550/commits/bb2f627b1287483749487e405931d3cbe2c5363e#diff-1994707fb909ec523ea083950eac603eR246, where we exclude `position` from being animatable. This change was meant to only exclude implicit animations, but it is also canceling our UIView animation in `updateUserLocationAnnotationViewAnimatedWithDuration:`.

**Comment by 1ec5** [comment]
bb2f627b1287483749487e405931d3cbe2c5363e went into v3.3.0-beta.3.

**Comment by incanus** [comment]
Right, this is correct, but now affects the user dot since we've moved it to `MGLAnnotationView`. We can make an exclusion for the user dot class and subclasses?

**Comment by friedbunny** [comment]
The simplest fix is to allow `position` animations in MGLAnnotationView, if the class is a kind of MGLUserLocationAnnotationView:

```diff
diff --git a/platform/ios/src/MGLAnnotationView.mm b/platform/ios/src/MGLAnnotationView.mm
index c37adc5..352e1d3 100644
--- a/platform/ios/src/MGLAnnotationView.mm
+++ b/platform/ios/src/MGLAnnotationView.mm
@@ -249,7 +249,8 @@ - (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecogni
 - (id<CAAction>)actionForLayer:(CALayer *)layer forKey:(NSString *)event
 {
     // Allow mbgl to drive animation of this view’s bounds.
-    if ([event isEqualToString:@"bounds"] || [event isEqualToString:@"position"])
+    if ([event isEqualToString:@"bounds"] ||
+        ([event isEqualToString:@"position"] && ! [self isKindOfClass:MGLUserLocationAnnotationView.class]))
     {
         return [NSNull null];
     }
```

... but special-casing the user location annotation doesn’t strike me as a good fix. Moving other custom annotation views around the map has proven difficult and I think that’s a problem we need to solve.

**Comment by friedbunny** [comment]
That you can’t use UIView block-based animations on your annotation views doesn’t seem correct to me, either. Is that how we want it to work?

**Comment by 1ec5** [comment]
No, that's definitely a bug. I think the override in question is unnecessary as long as we bracket `-updateAnnotationViews` with a transaction that disables animations.

**Comment by friedbunny** [comment]
> I think the override in question is unnecessary as long as we bracket -updateAnnotationViews with a transaction that disables animations.

It looks like we already do that: [MGLMapView.mm#L4548](https://github.com/mapbox/mapbox-gl-native/blob/c075386a984cd5de21f6201341d360a5c1039b67/platform/ios/src/MGLMapView.mm#L4548)

**Comment by incanus** [comment]
Ah, yes! We should be ok here without doing anything for the layer actions directly.
