### ISSUE TITLE
Rotate Markers with map

### ISSUE THREAD

**Issue by vanshg** [mapbox/mapbox-gl-native#6204]
Is it possible to automatically rotate markers when the map is rotated on Android? I have markers that I am adding that depend on the direction they are facing, and so right now I am simply not allowing the user to rotate the map, but I'd like to allow it

**Comment by cammace** [comment]
I assume something similar to this is happening:

![ezgif com-video-to-gif 2 9 41 19 pm](https://cloud.githubusercontent.com/assets/5652865/18071012/37c5f0b4-6e20-11e6-8cd6-f480a37a28ab.gif)


The solution for now would be to use a camera change listener and update the marker rotation within it. We'll eventually hook up the camera object to view annotations. For future support questions please reach out through our [contact page](https://www.mapbox.com/contact/).

**Comment by t-yoshii** [comment]
I also would like to rotate MarkerView simultaneously with map rotation.
I tried to call MarkerView.setRotation() inside onCameraChangeListener, however, it causes some delay before rotating MarkerView.

Is there any way to update MarkerView rotation immediately not to cause delay?
