### ISSUE TITLE
Crash mapbox::sqlite::Exception authorisation denied on iOS with Data Protection enabled

### ISSUE THREAD

**Issue by macteo** [mapbox/mapbox-gl-native#6205]
**Platform: iOS**
**Mapbox SDK version: 3.3.4**
### Steps to trigger behavior
1. Integrate MapBox (through CocoaPods).
2. Enable background location updates with `CoreLocation`.
3. Enable [Data Protection](https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/AddingCapabilities/AddingCapabilities.html).
4. Create a controller with a `MGLMapView` instance visible that appears as soon as you launch the app.
### Expected behaviour

The app will be relaunched in background by the system as soon as a location update is available. The device can be locked and the data will be encrypted.
The app should be able to run anyway in background.
### Actual behaviour

The app crashes as with a `mapbox::sqlite::Exception` _authorization denied_.
I suppose that it is caused by MapBox trying to access a sqlite database that is present but not accessible as Data Protection kicks in.

If you really need to be always able to access the database, you should consider to create the file with no file protection specifying `FileProtectionType.none`:

``` swift
FileManager.default.createFile(atPath: path, contents: data, attributes: [FileAttributeKey.protectionKey.rawValue: FileProtectionType.none])
```

It would even better if you check if the file is available and use it only if the app is in foreground, so its content stays encrypted.

[mapbox-crashlog.txt](https://github.com/mapbox/mapbox-gl-native/files/444169/mapbox-crashlog.txt)

**Comment by 1ec5** [comment]
The SQLite database is created in C++ code that the Objective-C code has no control over, but maybe we can set the attribute on the directory containing it like we do for [excluding the database from backups](https://github.com/mapbox/mapbox-gl-native/blob/5588935412fbf6c62f88d92f4685e517a7bb84c1/platform/darwin/src/MGLOfflineStorage.mm#L80).

**Comment by jfirebaugh** [comment]
Previously: #4841.

**Comment by macteo** [comment]
I've got another crash, with different exception, but I think the cause is the same.

[mapbox-crashlog-2.txt](https://github.com/mapbox/mapbox-gl-native/files/450231/mapbox-crashlog-2.txt)

**Comment by macteo** [comment]
I'm not interacting with the map or other MapBox APIs while the app is in background. 
Do you think that removing the map from it's superview before entering background can solve the issue?
Or there still can be some other orphaned object (a singleton maybe) that will cause the issue?

The app dying while in background is a real blocking issue as the app itself won't be wake-up again to receive location updates until the user taps again on the icon.

**Comment by friedbunny** [comment]
For searchability, here’s the crashed thread from https://github.com/mapbox/mapbox-gl-native/issues/6205#issuecomment-244135765:

```
Fatal Exception: mapbox::sqlite::Exception: disk I/O error

#10. Crashed: DefaultFileSource
0  Tralio                         0x100096ae4 CLSProcessRecordAllThreads + 1572
1  Tralio                         0x100096ae4 CLSProcessRecordAllThreads + 1572
2  Tralio                         0x1000969a0 CLSProcessRecordAllThreads + 1248
3  Tralio                         0x1000868ec CLSHandler + 48
4  Tralio                         0x1000949b8 __CLSExceptionRecord_block_invoke + 92
5  libdispatch.dylib              0x1804fd1c0 _dispatch_client_callout + 16
6  libdispatch.dylib              0x18050a860 _dispatch_barrier_sync_f_invoke + 84
7  Tralio                         0x10009445c CLSExceptionRecord + 212
8  Tralio                         0x100093f8c CLSTerminateHandler() + 616
9  libc++abi.dylib                0x18009b66c std::__terminate(void (*)()) + 16
10 libc++abi.dylib                0x18009b234 __cxa_rethrow + 144
11 libobjc.A.dylib                0x1800ac71c objc_exception_rethrow + 44
12 CoreFoundation                 0x18154e0bc CFRunLoopRunSpecific + 560
13 CoreFoundation                 0x18159b8d4 CFRunLoopRun + 112
14 Mapbox                         0x10054b348 void mbgl::util::Thread<mbgl::DefaultFileSource::Impl>::run<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long long&>, 0ul, 1ul>(std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long long&>&&, std::__1::integer_sequence<unsigned long, 0ul, 1ul>) + 156
15 Mapbox                         0x10054b268 std::__1::__thread_proxy<std::__1::tuple<mbgl::util::Thread<mbgl::DefaultFileSource::Impl>::Thread<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long long&>(mbgl::util::ThreadContext const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&&&, unsigned long long&&&)::'lambda'()> >(void*, void*) + 136
16 libsystem_pthread.dylib        0x180707860 _pthread_body + 240
17 libsystem_pthread.dylib        0x180707770 _pthread_body + 282
18 libsystem_pthread.dylib        0x180704dbc thread_start + 4
```

**Comment by boundsj** [comment]
We expect that this issue will be resolved by https://github.com/mapbox/mapbox-gl-native/pull/8125 that is in the Mapbox iOS SDK as of [3.5.0 beta 2](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.5.0-beta.2). I'll leave this issue open for tracking until we can collect more evidence that the sqlite errors noted here no longer occur.
