### ISSUE TITLE
Document animated annotation views on iOS

### ISSUE THREAD

**Issue by Buminta** [mapbox/mapbox-gl-native#6206]
**Platform: iOS**
**Mapbox SDK version: 3.3.4**

Hi everybody!
I'm developing realtime application with mapbox like "Uber, Grab".
However I had a problem with animate moving marker on map.
I can't find example for moving position of marker for this!
Who can do it? Help me please!
Thanks for supported!

**Comment by mdakram** [comment]
Uber does not move marker but it allow user to pan mapview.

**Comment by Buminta** [comment]
@mdakram I don't understand, what do u mean?

**Comment by Buminta** [comment]
I want create some marker with icon car, bike,... run and run on map view!!!

**Comment by 1ec5** [comment]
We’re currently working on an example of animating an annotation, but the gist of it is that you’ll need to use an [annotation view](https://www.mapbox.com/ios-sdk/examples/annotation-views/) along with UIView animation or Core Animation implicit animation.

**Comment by 1ec5** [comment]
Note that animating annotation views via implicit animation may not work as expected: we’re tracking a fix in #6203.

**Comment by Buminta** [comment]
Thanks @1ec5

**Comment by friedbunny** [comment]
Tracked in https://github.com/mapbox/ios-sdk-examples/issues/24.
