### ISSUE TITLE
[iOS] Can MGLAnnotationView show callout

### ISSUE THREAD

**Issue by iBinh** [mapbox/mapbox-gl-native#6219]
My question is can an annotation view show callout?
 @1ec5

**Comment by 1ec5** [comment]
Yes. Similarly to our [non-view-backed annotation example](https://www.mapbox.com/ios-sdk/examples/marker/), set the `title` and/or `subtitle` property on the annotation and implement `-[MGLMapViewDelegate mapView:annotationCanShowCallout:]` to return `YES`. Then the user can show the callout view by tapping on the annotation, or you can show it programmatically by calling `-[MGLMapView selectAnnotations:]`.

In the future, if you have a question about our SDK or need some help getting started, please [reach out to our support team](https://www.mapbox.com/contact/). (Bug reports and feature requests are always welcome here on GitHub, of course.)
