### ISSUE TITLE
Scroll gesture disabling works until a different gestures performed

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#6228]
Using `mapboxMap.getUiSettings().setScrollGesturesEnabled(false);` works until a gesture such as zooming or tilting is performed on the map. Note that disabling scrolling using `mapbox:scroll_enabled="false"` in XML still works as intended.

![ezgif com-video-to-gif 2](https://cloud.githubusercontent.com/assets/5652865/18147703/e2869100-6fa3-11e6-849d-5a4babae0202.gif)

cc: @mapbox/android

**Comment by tobrun** [comment]
Adding to next milestone for visibility to investigate.

**Comment by tobrun** [comment]
Not reproducible on master:

![ezgif com-video-to-gif 43](https://cloud.githubusercontent.com/assets/2151639/25335646/32094bc8-28f4-11e7-9e74-7125db54fedd.gif)

Since this is an old issue, going to mark this as resolved.
