### ISSUE TITLE
Support for using in Notification Content Extensions

### ISSUE THREAD

**Issue by quicklywilliam** [mapbox/mapbox-gl-native#6230]
I've been able to get Mapbox compiling and more or less running in my Notification Content Extension (iOS 10), but the map simply comes up blank.

A similar issue was filed for Action Extensions and later closed:

https://github.com/mapbox/mapbox-gl-native/issues/4734

With the prevalence of Notification Content Extensions, many developers are likely going to want to do this. Using static maps is a fairly inflexible and limited work-around.

**Comment by quicklywilliam** [comment]
Just wanted to add that we implemented this feature using static maps (as per https://www.mapbox.com/blog/ios-10-notifications/) for now. It's not nearly as powerful or pretty as using real native maps =(.

**Comment by friedbunny** [comment]
Unfortunately, this isn’t actionable given platform constraints. Fortunately, [MapboxStatic.swift](https://github.com/mapbox/MapboxStatic.swift) and the underlying static API continue to improve.
