### ISSUE TITLE
Clean Android code to comply with checkstyle rules

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#6232]
Now that checkstyle's been added, the code needs to be cleaned up before integration with bitrise and failing builds. Using this ticket to track progress. Follow this [new wiki guide](https://github.com/mapbox/mapbox-gl-native/wiki/Setting-up-Mapbox-checkstyle) to setup Android Studio for easy formatting. 

Related ticket: #6109 

cc: @mapbox/android

**Comment by tobrun** [comment]
Merged with #7442, closing
