### ISSUE TITLE
Add VT options to GeoJsonSource

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-gl-native#6237]
In https://github.com/mapbox/mapbox-gl-native/pull/6217 we are adding support for clustering and VT options to MGLGeoJSONSource (the iOS SDK's version of the Android SDK's [GeoJsonSource](https://github.com/mapbox/mapbox-gl-native/blob/01a33749f9cd05f4b78c0463327821a47ae96baf/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.java)). While working on that, I noticed that GeoJsonSource does not appear to support [ VT options available in core](https://github.com/mapbox/mapbox-gl-native/blob/df3b44531e1c2a95edd2a035d3744f34ebb8d0e9/include/mbgl/style/conversion/geojson_options.hpp#L17-L42). Defaults [are provided in core](https://github.com/mapbox/mapbox-gl-native/blob/df3b44531e1c2a95edd2a035d3744f34ebb8d0e9/include/mbgl/style/sources/geojson_source.hpp#L28-L30) but an Android developer has no way to provide their own.

In addition, GeoJsonSource does not seem to currently provide documentation for the clustering related options it does support. In https://github.com/mapbox/mapbox-gl-native/blob/249514389a77cdb15eee779a332876eea06cdcfa/platform/darwin/src/MGLGeoJSONSource.h the iOS SDK gained some documentation that mirrors the [style spec](https://www.mapbox.com/mapbox-gl-style-spec/#sources-geojson) and the Android SDK should probably have at least that, too. However, note that a discussion about how to improve the documentation for a platform is happening in https://github.com/mapbox/mapbox-gl-native/issues/6236

@ivovandongen @cammace @zugaldia

**Comment by ivovandongen** [comment]
@boundsj I'm actually working on this in https://github.com/mapbox/mapbox-gl-native/issues/5906, but got blocked on #5701 (probably). Will pick this back up once that lands in master.
