### ISSUE TITLE
Snapshot blocks UI thread for 800ms

### ISSUE THREAD

**Issue by mkv123** [mapbox/mapbox-gl-native#6238]
**Platform:** Android
**Mapbox SDK version:** Latest 4.2 snapshot
### Steps to trigger behavior
1. mapboxMap.snapshot(new SnaphshotReadyCallback() { public void onSnapshotReady(Bitmap snapshot){} } );
### Expected behavior

Snapshot is taken while application usage remains silky smooth
### Actual behavior

All animations etc stop for a significant amount of time (800ms on a high end phone, Nexus 5X).

Alternatively if I try to excute the snapshot() from a non-ui thread I get a crash.

Test code.

``` java
final long start = SystemClock.currentThreadTimeMillis();

mapboxMap().snapshot(new SnapshotReadyCallback() {
    @Override
    public void onSnapshotReady(Bitmap snapshot) {
        Log.d(TAG, "onSnapshotReady: " + (SystemClock.currentThreadTimeMillis() - start));
    }
}); 
```

This makes using the snapshotting pretty useless as there are very few cases where blocking the UI thread for such a long time would be ok.

**Comment by jfirebaugh** [comment]
Fixed in #7828.
