### ISSUE TITLE
[Android] LineLayer not appearing on map

### ISSUE THREAD

**Issue by lyptt** [mapbox/mapbox-gl-native#6240]
**Platform:** Android
**Mapbox SDK version:** 4.2.0-beta2

Based on recommendations I'm attempting to display a dotted line via a LineLayer based on a series of Lat/Long coordinates.

The way I've gone about it is to construct a `List` of `Position` objects, create a `Feature` via its `fromGeometry()` method passing in this `List`, then construct a `GeoJsonSource` with a `FeatureCollection` containing this single feature.

I then add this source to the map, then construct a `LineLayer` passing in the source's identifier, configure its styling properties, then add it to the map.

I'd expect this to be enough to display a line on the map, but this isn't visible unfortunately.

Here's the code I'm using to achieve this:

```java
        final List<Position> mapboxCoordinates = new ArrayList<>(coordinates.size());

        for (int i = 0; i < coordinates.size(); i++) {
            final CoordinatePair pair = coordinates.get(i);
            mapboxCoordinates.add(
                Position.fromCoordinates(pair.getLongitude(), pair.getLatitude())
            );
        }

        final Feature lineFeature =
            Feature.fromGeometry(LineString.fromCoordinates(mapboxCoordinates));

        final GeoJsonSource source = new GeoJsonSource(
            "route", FeatureCollection.fromFeatures(new Feature[] { lineFeature })
        );

        mMapboxMap.addSource(source);

        final LineLayer layer = new LineLayer("routeLayer", "route");
        layer.setProperties(
            PropertyFactory.lineDasharray(
                new Float[] {
                    0.01f, 2f
                }),
            PropertyFactory.lineCap("round"),
            PropertyFactory.lineJoin("round"),
            PropertyFactory.lineWidth(5f),
            PropertyFactory.lineColor(
                context.getResources().getColor(R.color.colorValidationError)
            ),
            PropertyFactory.lineOpacity(1f)
        );

        mMapboxMap.addLayer(layer);
```

I've looked at examples that make use of LineLayer and I can't see much difference between what they're doing and what I'm doing. Is there something noticeably wrong with my approach?

**Comment by cammace** [comment]
I looked into this issue and it appears that the GeoJSON isn't formatting correctly. I got your code to work by creating the FeatureCollection this way:

```java
FeatureCollection featureCollection = BaseFeatureCollection.fromJson("{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"LineString\",\"coordinates\":["
          + "[" + origin.getLongitude() + "," + origin.getLatitude() + "]" + ","
          + "[" + destination.getLongitude() + "," + destination.getLatitude() + "]"
          + "]},\"properties\":{}}]}");
```

It's a messy work around but until I figure out why the properties:{} isn't being added in the geojson, its the best work around. Here's what the dashed line looks like:

<img src="https://cloud.githubusercontent.com/assets/5652865/18217674/3ace21dc-712c-11e6-91b3-94e3dbf48f02.png" width=360/>

**Comment by lyptt** [comment]
Ah great! Thanks for offering a workaround, that's really helpful :+1: Glad to know it wasn't just me!

**Comment by zugaldia** [comment]
When we build a new `Feature` using `Feature.fromGeometry(Geometry geometry)` we [set the value](https://github.com/mapbox/mapbox-java/blob/master/libjava/lib/src/main/java/com/mapbox/services/commons/geojson/Feature.java#L94-L103) of the `JsonObject properties` field as `null` if no value is specified. Is it that what's causing the problem? Is there another default value that we should be specifying for the Runtime Style API to work?

If so, another potential workaround would be to call `Feature.setProperties(JsonObject properties)` to set an empty object (`{}`) and replace the default `null` value.

**Comment by jfirebaugh** [comment]
https://tools.ietf.org/html/rfc7946#section-3.2:

> A Feature object has a member with the name "properties".  The
      value of the properties member is an object (any JSON object or a
      JSON null value).

So the serializer should ensure that it outputs either `"properties": null` or `"properties": {...}`.

**Comment by zugaldia** [comment]
Turns out GSON ignores `null` values at serialization, and therefore, when setting `properties` as `null` they were missing in the JSON output.

With https://github.com/mapbox/mapbox-java/pull/194 we're now explicitly setting `properties` to an empty `new JsonObject()` to make sure JSON contains the `"properties":{}` string.
