### ISSUE TITLE
mapView setStyleUrl method not loading in style

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#6242]
`mapView.setStyleUrl(Style.SATELLITE);` isn't rendering the style, just getting a 401 error:

```
loading style failed: HTTP status code 401
```

Example of this can be found in the `ManualZoomActivity` found in the [testapp](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/ManualZoomActivity.java#L41). Setting the map style using mapboxMap or through XML still works as expected.

cc: @mapbox/android

**Comment by tobrun** [comment]
401 - unauthorized indicates that the access token is not correctly loaded. Looking into this.

**Comment by zugaldia** [comment]
> Setting the map style using mapboxMap or through XML still works as expected.

Right @tobrun , this sounds like `MapboxAccountManager` isn't setting the token properly.
