### ISSUE TITLE
MGLRasterSource and MGLVectorSource tile sets

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6245]
MGLRasterSource needs support for the `tiles`, `minzoom`, and `maxzoom` style specification properties. We’ll need to add `tileURLTemplates`, `minimumZoomLevel`, and `maximumZoomLevel` properties to MGLRaster(Vector)Source, which we’ll use to create an `mbgl::style::TileSet` to pass into the `mbgl::style::RasterSource` constructor.

/cc @frederoni @boundsj

**Comment by boundsj** [comment]
I think that MGLVectorSource needs the same treatment.
