### ISSUE TITLE
Add initializer to set sourceLayer in MGLStyleLayer

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-gl-native#6252]
In the [GL JS example for adding a third party vector source](https://www.mapbox.com/mapbox-gl-js/example/third-party) and also in [this Android demo app example](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/VectorSourceActivity.java#L39) the `source-layer` property can be set to a specific layer.

The iOS MGL*StyleLayer classes do not offer a way to set this value either in the initializers in the `MGLStyleLayer` protocol or via a property or setter method. This feature is important for styling sources that have many layers.

cc @1ec5 @frederoni

**Comment by jfirebaugh** [comment]
Note that the core setter isn't hooked up internally to cause a refresh, so it only works when called prior to adding the source to the style. I don't foresee any technical blocker to allowing on-the-fly mutation, but it's probably not a big priority (GL JS doesn't have such an API for example).

**Comment by boundsj** [comment]
Thanks for pointing that out @jfirebaugh. I adjusted the title of this issue and also proposed a fix (to add an init method only, no setter) in https://github.com/mapbox/mapbox-gl-native/pull/6269
