### ISSUE TITLE
Source and layer ownership is inconsistent (from style versus from developer)

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6254]
MGLSource and the MGLStyleLayer classes manage their underlying C++ objects inconsistently depending on the task. For example, when getting an MGLSource object from an MGLStyle, the MGLSource object holds a strong reference to an `mbgl::style::Source` object in its `source` property. On the other hand, when the developer initializes an MGLSource object from scratch in order to add it to an MGLMapView, `-[MGLSource mbglSource]` creates the `mbgl::style::Source` object lazily when adding it to the style and never holds a reference to it. If the developer attempts to get an MGLSource from the style and add it back to the style, a brand-new `mbgl::style::Source` object is created and added to the map, discarding any modifications that the developer may have made on the MGLSource object.

We should remove `-[MGLSource mbglSource]`. MGLSource should create the `mbgl::style::Source` upfront in its initializers. (There should be an additional private initializer that accepts an `mbgl::style::Source`.) This means all the source options need to be immutable. Currently, the only mutable source option is the `sourceIdentifier` property, but I think that should be read-only anyways.

The catch is that a source added to the map really shouldn’t be owned by the MGLSource object. Could we treat the `source` property as holding only a “pending” source and always access the `mbgl::style::Source` object via `mbgl::Map::getSource()`? What happens if the developer attempts to add the same MGLSource to the MGLStyles of two different MGLMapViews?

/cc @frederoni @boundsj

**Comment by jfirebaugh** [comment]
To expand on https://github.com/mapbox/mapbox-gl-native/pull/6269#issuecomment-245364132, objects wrapping `mbgl::style::Layer` and `mbgl::style::Source` domain objects need to have two internal members:

* A `std::unique_ptr<>`, which is present only for objects that were created independently (not obtained by `Map#getLayer` or `Map#getSource`) and have not yet been added via `Map#addLayer` or `Map#addSource`.
* A raw pointer to the `mbgl` object, which is always initialized, either to the result of `Map#getLayer` or `Map#getSource`, or for independently created objects, to the pointer value held in the `unique_ptr`. In the latter case, this raw pointer value stays even after _ownership_ of the object is transferred via `Map#addLayer` or `Map#addSource`.

This is the approach that the Android bindings follow.

**Comment by jfirebaugh** [comment]
Note that after a source or layer is removed from the style, you don't get ownership of that object _back_, and any raw pointers you retained are invalid. This has implications for documentation of the SDK bindings for the removal methods.

**Comment by 1ec5** [comment]
By the way, a somewhat orthogonal idea: for MGLStyleLayers obtained from the MGLStyle, the only state MGLStyleLayer maintains would be the layer identifier, and it always uses that identifier to obtain the `mbgl::style::Layer` and manipulate it locally. This sort of proxy pattern is common in frameworks like Scripting Bridge.

**Comment by 1ec5** [comment]
Textbook example of what developers face with the current inconsistency: #6460.

**Comment by boundsj** [comment]
The layer portion of this was fixed by https://github.com/mapbox/mapbox-gl-native/pull/6904 and the source portion in https://github.com/mapbox/mapbox-gl-native/issues/6793.
