### ISSUE TITLE
Widgets/Views

### ISSUE THREAD

**Issue by Rasive** [mapbox/mapbox-gl-native#6261]
Hello

So, I've been looking through the source code of Mapbox on Android, and was wondering if it was intentional that you are not adding a functionality to add extra views to the Mapbox MapView? Considering that it is not exposed, I suppose this would be a nice way to add extra functionality (eg. another compass, or a brand new one).

I am trying to add view objects to an overlay and sync those with the draw calls of the underlying MapView. Been looking at the widgets you have under maps, and was thinking, maybe this would be a good idea to do it, but sadly I could not see you have added this functionality (really need something less sluggish than OnCameraChangeListener)

Or maybe I am just blind and cannot see what I am looking for, is already there :)

**Comment by Rasive** [comment]
Oh... ok I just figured it out by myself, sorry.

I was loading the MapView as a Fracktal, and didn't spot the getView() method on the MapFracktal object.

**Comment by tobrun** [comment]
> a functionality to add extra views to the Mapbox MapView? 

You can addViews to the MapView by calling `MapView.addView(customView)`.

>  add extra functionality (eg. another compass, or a brand new one).

One of the items we discussed internally is allowing to set a custom view for compass and related overlays this would allow integrating these into a coordinatorlayout. We haven't ticketed this feature out but I'm putting it on my backlog. 

> I am trying to add view objects to an overlay and sync those with the draw calls of the underlying MapView.

The easiest way is to add a map change listeners and update the location of these widgets with:

```java
mapboxMap.getProjection().toScreenLocation(latLng);
```

Let us know if you have any issues implementing this! 
Closing this issue for now.
