### ISSUE TITLE
Reload source tiles when GeoJSON data is mutated

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#6264]
Followup from #6201.

**Comment by jfirebaugh** [comment]
GeoJSON tile reloading will be similar to reloading for style changes in #6201, but also different.

The pathway for reloading for style changes is:

1. A layout property or layer filter is changed
1. Triggering `LayerObserver::onLayer{Filter,Visibility}Changed
1. Triggering `Style::onLayer{Filter,Visibility}Changed
1. Style queues the layer source ID in `updateBatch.sourceIDs` and triggers `style::Observer::onUpdate` with `Update::Layout`
1. `Map::Impl::onUpdate` adds `Update::Layout` and triggers an asyncUpdate signal (if not already triggered)
1. The signal is processed; `Map::Impl::update` is called
1. Triggering `Style::relayout`
1. Loop over `updateBatch.sourceIDs`, calling `Source::Impl::reloadTiles` for each
1. `Source::Impl::reloadTiles` loops over tiles, calling `Tile::redoLayout` for each
1. Which is overridden in `GeometryTile::redoLayout` to trigger the workers to reprocess with a new copy of the style layers

All this only handles changes to style layers. It's fairly complex in order to support batching multiple updates into a single `redoLayout` operation. For GeoJSON data changes, maybe we can get away without batching, and instead just add a loop over tiles in `GeoJSONSource::Impl::setGeoJSON`, calling `GeometryTile::setData` on each one with the new data.

**Comment by tobrun** [comment]
I have been working with @mollymerp to get this feature in. 
We were able to get the the following working:

> For GeoJSON data changes, maybe we can get away without batching, and instead just add a loop over tiles in GeoJSONSource::Impl::setGeoJSON, calling GeometryTile::setData on each one with the new data.

An example of this can be seen in:

![ezgif com-video-to-gif 5](https://cloud.githubusercontent.com/assets/2151639/18559618/f3d24672-7b2c-11e6-99b4-fe463d89054d.gif)


Which is the equivalent of the GL-JS example [here](https://www.mapbox.com/mapbox-gl-js/example/live-geojson/).

**Comment by tobrun** [comment]
@jfirebaugh would you like to see the improved version happening? 
(implementing the observer approach with batching)

**Comment by jfirebaugh** [comment]
No, I think we're good here unless we encounter a concrete performance
issue.
