### ISSUE TITLE
Add test app activity for loading a local style.json file

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-native#6265]
I have seen a handful of requests recently to use local style JSON files in Android applications. This is useful for apps that require third-party tiles or lower quality mapbox tiles (in jpg70 format, for example). The [current example](https://www.mapbox.com/android-sdk/examples/custom-raster/) points to a hosted asset. It would be helpful to have an example activity showing how this is done. 

cc @tobrun @cammace @bleege

**Comment by 1ec5** [comment]
The iOS SDK automatically converts relative URLs to asset: URLs, which are relative to the asset directory that is set when initializing the `mbgl::DefaultFileSource`. It also prepends the asset: scheme to absolute file URLs so that mbgl treats them as absolute file URLs.

**Comment by cammace** [comment]
In the demo app using a local json style is [explained in a comment](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/CustomRasterStyleActivity.java#L23-L25). If this is adequate, I can update the example found on our site.

**Comment by bleege** [comment]
> In the demo app using a local json style is explained in a comment. If this is adequate, I can update the example found on our site. 

Yeah, that JSON file should be fine.  The key is to embed it locally in the file system and then build out the TestApp example that reads from the file system.  This will provide and example for customers, but even more importantly give us something that we can write test cases for to ensure that this continues to work over time.  😉

**Comment by ivovandongen** [comment]
@danswick https://github.com/mapbox/mapbox-gl-native/pull/6497 brings a test Activity that loads a style file from the file system (opposed to a packaged asset). See the specific [commit](https://github.com/mapbox/mapbox-gl-native/pull/6497/commits/39dfb4d7e113fb79f3a898c62eaeaf60b1999062) for details.
