### ISSUE TITLE
Add JavaDocs for public API of MapView

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#627]
Need to add JavaDoc annotations for MapView's public API. Similar to what iOS has.

We should compile this into static HTML javadoc with gradle too.

**Comment by ljbade** [comment]
@bleege You think that we should add this to your maven build?

**Comment by bleege** [comment]
Yep, JavaDocs will automatically be generated and released via Maven Central with what I'm setting up in #826.  They can be reused for documentation on Mapbox.com like what we just did for the Android Raster SDK at https://www.mapbox.com/mapbox-android-sdk/api/0.7.0/.

**Comment by bleege** [comment]
Confirmed earlier today!
