### ISSUE TITLE
Move calloutview when update annotation coordinate

### ISSUE THREAD

**Issue by iBinh** [mapbox/mapbox-gl-native#6270]
Callout view disappear when update annotation coordinate

**Comment by jfirebaugh** [comment]
Hi @iBinh, please use the [provided issue template](https://raw.githubusercontent.com/mapbox/mapbox-gl-native/master/ISSUE_TEMPLATE.md) when reporting issues. This issue does not contain the necessary information to allow us to help you with your problem.

**Comment by 1ec5** [comment]
#6284 might be what you intended to report. In the future, providing a code sample may help us know for sure what you mean. Thank you.
