### ISSUE TITLE
location text is reversed in arabic text

### ISSUE THREAD

**Issue by RezaOruji** [mapbox/mapbox-gl-native#6271]
**Platform:** Android
**Mapbox SDK version:** 4.2.0-beta.2

### Steps to trigger behavior
look at the image below : 
![problem](https://cloud.githubusercontent.com/assets/4154232/18311424/682931bc-7519-11e6-905b-659dcb2618e8.png)
as you see the text in arabic is appearing revered and user can not read it.
is there any way to fix this ? 

### Expected behavior
for example the texts on the image should be : قدس ، میخک but they  appear reversed .

**Comment by jfirebaugh** [comment]
Thanks for the report. We're tracking this issue in https://github.com/mapbox/mapbox-gl/issues/4.
