### ISSUE TITLE
Callout dismisses when annotation coordinate changes slightly

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6284]
We should avoid deselecting an annotation (closing its callout) when its `coordinate` property changes, as long as the annotation remains within the viewport. We did this for the user dot (#2618), but not for annotations in general. #3154 is related in the sense that changing the viewport also shouldn’t close the callout.

/cc @boundsj @friedbunny

**Comment by 1ec5** [comment]
@frederoni, does #6676 fix this issue?

**Comment by frederoni** [comment]
Unfortunately, it gets dismissed when its coordinate changes.

**Comment by bulbuliator** [comment]
Also interested in staying callout and follow the annotation while coordinate changes. Does this issue already fixed? Or can somebody give a hint about quick possibility of fixing this issue in future releases?

**Comment by 1ec5** [comment]
A fix for this issue is proposed in #8269.

**Comment by 1ec5** [comment]
Fixed in #8269 on the release-ios-v3.5.0-android-v5.0.0 branch.
