### ISSUE TITLE
Add API to MGLSource to discover source layers

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-gl-native#6285]
To help the developer discover the layers of a source we could add a new method on MGLSource for getting an MGLSourceLayer by identifier or a property that returns all the source layers.

ref https://github.com/mapbox/mapbox-gl-native/pull/6269#issuecomment-245324108

cc @1ec5

**Comment by jfirebaugh** [comment]
This isn't possible with current Mapbox Web APIs -- source JSON doesn't include a list of possible layers. There's only [prose documentation](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/).

**Comment by jfirebaugh** [comment]
I take that back, there is `vector_layers` key -- but it isn't standardized or documented, and the core implementation doesn't parse or store it.
