### ISSUE TITLE
[android] Broken links at CONTRIBUTING_MACOS.md documentation

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#6297]
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/CONTRIBUTING_MACOS.md

"Next: get your app running on a hardware Android Device or simulator" at the end of the page is br0ken.

/cc @bleege @tobrun @zugaldia

**Comment by tobrun** [comment]
cc @cammace

**Comment by friedbunny** [comment]
Noticed this recently as I was getting set up. These instructions were apparently rolled into the main readme.
