### ISSUE TITLE
I want to hide the navigation button in android .. is there any way to acheive this ?

### ISSUE THREAD

**Issue by rajat028** [mapbox/mapbox-gl-native#6299]
**Platform:**
**Mapbox SDK version:**

### Steps to trigger behavior

 1.
 2.
 3.

**Comment by friedbunny** [comment]
Thanks for using our Android SDK. Per [our contribution guidelines](https://github.com/mapbox/mapbox-gl-native/blob/master/CONTRIBUTING.md), this repository is intended for development and bug reports. For support, please see our [help docs](https://www.mapbox.com/help/#build-a-mobile-app) and [Android SDK](https://www.mapbox.com/android-sdk/) pages.

If you have a bug to report or a feature to request, please fill out the issue template. Thanks!
