### ISSUE TITLE
'load' or 'ready' event

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#630]
It would be useful to have a way to know when the map has finished loading.

My first use would be as part of the automated Testmunk testing.

Inspired by https://github.com/mapbox/mapbox-gl-js/issues/826

**Comment by ljbade** [comment]
@jfirebaugh I suppose something similar to you JS event would work here?

**Comment by ljbade** [comment]
Ah I see I just need to hook this up.

**Comment by bleege** [comment]
@ljbade Still feeling this is necessary?

**Comment by ljbade** [comment]
Yeah I think we will need this when it comes time to run automated testing.

**Comment by incanus** [comment]
You want https://github.com/mapbox/mapbox-gl-native/blob/2f30dfe97d851f2a2bb4141dc234013b01f8afd3/include/mbgl/map/view.hpp#L26-L28.

**Comment by bleege** [comment]
GTK.  Let's still leave it for `0.2.0` as we need to :ship: `0.1.0` sooner rather than later.

**Comment by jfirebaugh** [comment]
To implement this, keep a flag of whether or not a load event has been previously fired. If, when dispatching the other render events, the flag is not set and `MapContext::isLoaded()` / `Map::isFullyLoaded()` is true, also dispatch the "loaded" event.

Use the [JS implementation](https://github.com/mapbox/mapbox-gl-js/blob/a7092c2d52a9d04fd845cd671b7bcd8192aa5d77/js/ui/map.js#L749-L752) as a reference.

**Comment by ljbade** [comment]
@jfirebaugh Ah excellent, will try that out.

**Comment by ljbade** [comment]
Got it working, thanks @jfirebaugh

**Comment by bleege** [comment]
I'm moving this back to `android-v2.2.0` due to timing.  While this is a useful feature there won't be sufficient enough time to finish building it nor testing it before we need to ship.

**Comment by ljbade** [comment]
Fair enough

**Comment by ljbade** [comment]
After discussion with @jfirebaugh the PR https://github.com/mapbox/mapbox-gl-native/issues/2599 will only implement the start and successful load events.

Failure event needs some work due to interaction with how `setStyleUrl` clears the set JSON but doesn't trigger an `update()`.

So going to leave this issue open until then.

@1ec5 or @incanus: Is there any work needed on iOS side now that the start and success events are hooked up? Documentation?

**Comment by 1ec5** [comment]
The methods do need to be documented still so that they show up in the API documentation.

**Comment by ljbade** [comment]
@1ec5 some tests would be good too. Does iOS/core have any tests for the existing map change events?

**Comment by friedbunny** [comment]
We have [region change delegate tests for iOS](https://github.com/mapbox/mapbox-gl-native/blob/6c49f8a5789698225442430737b5b4b083edea77/test/ios/MapViewTests.m#L454-L609), but they've been flaky and are mostly disabled at the moment. We should add add new tests for map change, see what happens. :boom:

**Comment by friedbunny** [comment]
It looks like `willStart` and `didFinish` landed in master via #2627 last week, and in Android v2.1.0 via 66c3fe2e1f0b8a2f8ca4db4e8ec3555ceed60705. 

What is left to do? `failedToLoad` probably deserves its own ticket and we can close here.

iOS next steps are in #2706.

@bleege @ljbade This belongs on the `android-v2.1.0` milestone, no?

**Comment by ljbade** [comment]
@friedbunny Yes, put this issue on v2.1.0 make a new ticket for `failedToLoad` where can be assigned a milestone at some stage.

**Comment by friedbunny** [comment]
`MapChangeDidFailLoadingMap` is happening in #2762.
