### ISSUE TITLE
[android] Option to disable InfoWindows?

### ISSUE THREAD

**Issue by chewbyte** [mapbox/mapbox-gl-native#6305]
Hi, apologies if such an option already exists, but shouldn't there be an option in UiSettings that disables marker InfoWindows completely?

**Comment by tobrun** [comment]
If you don't want to show a InfoWindow when a marker is clicked. You can return true in `OnMarkerClickListener#OnMarkerClick(Marker)`. This notifies the system that the marker click event is handled. Reach out if you have any other questions!

**Comment by PhanVanLinh** [comment]
It seem not work in mapbox 5.0

**Comment by fredriks** [comment]
Works fine in 5.1.0 but it took me a while to realize that `OnMarkerClickListener` will only consume events on `Marker` and not on `MarkerView`.

To consume `MarkerView` events use [MarkerViewManager.setOnMarkerViewClickListener](https://www.mapbox.com/android-docs/api/map-sdk/5.1.0/com/mapbox/mapboxsdk/annotations/MarkerViewManager.html#setOnMarkerViewClickListener-com.mapbox.mapboxsdk.maps.MapboxMap.OnMarkerViewClickListener-).

The `MarkerViewManager` is accessible on the map instance, eg:
```java
mapboxMap.getMarkerViewManager().setOnMarkerViewClickListener()
```
