### ISSUE TITLE
[node] only renders gray tiles when built from source

### ISSUE THREAD

**Issue by rastapasta** [mapbox/mapbox-gl-native#6306]
**Platform:** OS X 10.11.6, OS X 10.10.5, Ubuntu 14.04 - Node v.4.5.0, Npm 3.10.4

### Steps to trigger behavior

 1. clone the repo, successfully compile, successfully run the tests
 2. compile the node binding/code, successfully run the tests
 2. render a tile using the node module

### Expected behavior

Getting a rendered tile, as it works perfectly with the pre-built node version.

### Actual behavior

As soon as using the self-compiled version of the node module, returned rendered tiles are just gray filled. No errors are being logged.

While compiling and running the OS X Debug App works smooth and fine at the same time.

Thanks in advance!

**Comment by jfirebaugh** [comment]
Can you provide a sample project that demonstrates the issue you're seeing? Our automated tests of the node bindings test rendering; if this was a general issue, we likely would have noticed already.

**Comment by asalliou** [comment]
I had the same issue because the current map zoom level was not inside the range of minzoom & maxzoom configured on my raster layer.
This behaviour was introduced at commit e643ffe7f43786fb0b60c09c681d5360c9485fc4 and seems to be intended.
