### ISSUE TITLE
Changing the style via setStyleURL does not trigger a style reload

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#631]
Currently the style URL is only checked after the map is first started.

So if you try to interactively switch the style via setStyleURL nothing happens.

Also if you do not set a style URL before you start, you will get a black map and an error message in the log about in invalid URL from curl. Should the map should load an empty white style when you have not already set a style?

**Comment by jfirebaugh** [comment]
This should be fixed.
