### ISSUE TITLE
Mapbox SQLite::Exception Unable to open Database File Crashes.

### ISSUE THREAD

**Issue by shantanu-vyas** [mapbox/mapbox-gl-native#6315]
On starting the application I'm met with a crash a couple seconds after. I have run the app on a galaxy s2 tablet and did not run into the issue.

**Platform:**
Kindle Fire HD10
**Mapbox SDK version:**
4.2.0 beta 2
### Steps to trigger behavior

 1. Start Application
 2. Wait a couple seconds

### Expected behavior
Mapbox should display and you should be able to interact with it
### Actual behavior
Does not block dragging/panning of the map for a moment then hangs and crashes.
Logcat displays:

 A/libc: /Volumes/Android/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type mapbox::sqlite::Exception: unable to open database file" failed
 A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 26000 (DefaultFileSour)

Logcat with no filter also displays: 
E/libEGL: error opening cache file /data/data/com.platypus.android.tablet/cache/com.android.opengl.shaders_cache: Permission denied (13)

Might be related to #6205

**Comment by manatrex** [comment]
Damn I thought I fixed this in my old account. Be right on it!

**Comment by friedbunny** [comment]
Thanks for the report — this is #6193.
