### ISSUE TITLE
Lots of rendering issues for some styles

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#632]
I added a dropdown to select different map styles, however other than bright all the other styles have rendering issues.

## Basic
![basic](https://cloud.githubusercontent.com/assets/1215089/5156664/497bb61e-732b-11e4-979e-e118faf0e213.png)

- The POI icons are clipped on the right side
- The text labels overlap
- Missing labels, e.g. country names and cities
- Missing road lines when zoomed out
- Missing coastal territory lines

## Bright

- The POI icons are clipped on the right side
- Missing coastal territory lines

## Outdoors (Vector)

- ~~lots of corrupted fills~~ - fixed
- no hill shade - same on linux, new style coming
- no thick blue outline on water polygons

## ~~Outdoors (Raster)~~

- ~~same problems as vector~~ - going to be deleted

## Pencil
![pencil](https://cloud.githubusercontent.com/assets/1215089/5156672/fbd9966e-732b-11e4-997e-cded0d333c25.png)

- very broken

## Satellite

- ~~stays a black fill~~ - fixed by libjpeg
- ~~spews lots of `E/Image﹕ image is not a valid PNG image` (libpng error message?)~~

Any ideas as to what is causing all the problems?

**Comment by ljbade** [comment]
Pencil now completely kills the map and no longer loads tiles when you switch back to other styles.

Satellite has broken labels that show up as black text with no halo.

**Comment by jfirebaugh** [comment]
Seems like this is now covered by #636 and #635. Let's revisit when we officially launch these styles.
