### ISSUE TITLE
Making a layer invisible doesn't stop tiles from being requested

### ISSUE THREAD

**Issue by Pilou44** [mapbox/mapbox-gl-native#6329]
Hello,
I've got two issues with layers. I use android 4.2.0 beta 2.

My first issue is that when I manipulate layers (getLayer then modify properties), if I close the app and launch it again I've got a crash with this trace : 
A/libc: /Volumes/Android/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type mapbox::sqlite::Exception: unable to open database file" failed
If I don't manipulate layers the issue doesn't occur. 

My second issue is that when I make a layer invisible using setProperties(visibility(NONE)), I can see that the tiles used by this layer are still requested even if they are not displayed.

**Comment by jfirebaugh** [comment]
The first issue is #6193.

**Comment by jfirebaugh** [comment]
Second issue was fixed in 91272992f3a7ca7baa124c3378f1c1e2b3e5bb76.
