### ISSUE TITLE
Labels pop in and out when you rotate

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#633]
If you rotate the map (without touching zoom) labels will pop in and out at different angles.

This occurs even when the labels would not overlap.

When when they do overlap it does not turn off the less important label.

**Comment by ljbade** [comment]
@ansis Let me know when you improve the labelling algo, particularly with high DPI and I will come back to this.

**Comment by ljbade** [comment]
After the fix to label density rotations are still wrong.

**Comment by ansis** [comment]
#1666 should fix this
