### ISSUE TITLE
Different decelerationRate for pan and zoom

### ISSUE THREAD

**Issue by antontupikov** [mapbox/mapbox-gl-native#6330]
Is there any way to set different values of decelerationRate for pan and zoom for iOS SDK?

**Comment by 1ec5** [comment]
No, it appears that MGLMapView is using the same `decelerationRate` property for panning, pinching, and rotation gestures. Can you describe your use case?

**Comment by antontupikov** [comment]
It will be much better to set them differently. In my case I want to set up panning with a smoothing and zoom without it.
