### ISSUE TITLE
Location view with padding moves with camera

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#6343]
Adding my location view padding and rotating/zooming the camera causes the marker to move:

![ezgif com-video-to-gif 3](https://cloud.githubusercontent.com/assets/5652865/18555887/773297e2-7b37-11e6-948d-90a096f303df.gif)

Reproducible using [this example](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/location/CustomizeUserLocationActivity.java) from demo app

cc: @tobrun

**Comment by 1ec5** [comment]
Related: #6257.

**Comment by tobrun** [comment]
Found the issue:

This works:
```java
final MyLocationViewSettings myLocationViewSettings = mapboxMap.getMyLocationViewSettings();
myLocationViewSettings.setPadding(0, 500, 0, 0);     
map.getTrackingSettings().setMyLocationTrackingMode(MyLocationTracking.TRACKING_FOLLOW);

```
While this doesn't:

```java
map.getTrackingSettings().setMyLocationTrackingMode(MyLocationTracking.TRACKING_FOLLOW);
final MyLocationViewSettings myLocationViewSettings = mapboxMap.getMyLocationViewSettings();
myLocationViewSettings.setPadding(0, 500, 0, 0);
               
```

Setting the padding doesn't recalculate the focal point.
