### ISSUE TITLE
Configurable API hostname

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6346]
#6309 is adding the ability to customize the meaning of mapbox: URLs to mbgl. We should offer a convenient way for the developer to modify the API hostname. Two options:

1. Add a `hostname` property to MGLOfflineStorage whose setter calls `mbgl::DefaultFileSource::setAPIBaseURL()`.
2. Have MGLOfflineStorage call `mbgl::DefaultFileSource::setAPIBaseURL()` automatically based on an `MGLMapboxAPIHostname` user default.
3. Same as (2), but as an Info.plist entry.

I prefer either (2) or (3) because MGLOfflineStorage is largely asynchronous and therefore easy to use incorrectly.

It’d be nice to call this option a “hostname” for consistency with the Mapbox Swift libraries’ existing API hostname options. However, “base URL” would be more correct since it looks like you can provide an arbitrary path and scheme in addition to the hostname. MGLAPIClient already has support for a `MGLTelemetryTestServerURL` user default that defaults to `MGLAPIClientBaseURL`, so I guess we can follow that naming scheme.

/cc @boundsj @tobrun

**Comment by 1ec5** [comment]
Also, if we end up making this a user default, we should provide constants for `api.mapbox.com` and any alternative hostnames we might need to support publicly.

**Comment by incanus** [comment]
Thoughts on moving this off of the milestone though @1ec5?
