### ISSUE TITLE
Camera start, ongoing, and end events notifications

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#6350]
The latest Google Maps has added camera change listeners for camera start, ongoing, and end events notifications. The interfaces are `OnCameraMoveStartedListener`, `OnCameraMoveListener`, `OnCameraMoveCanceledListener`, `OnCameraIdleListener`. This is how it's described in the [announcement](https://googlegeodevelopers.blogspot.com/2016/08/keep-users-focused-on-whats-important.html):

> As one of our top requests, developers have been asking for a better way to track camera movements and the ability to see why the camera is moving, whether caused by user gestures, built-in API animations or developer controlled movements [Issue 4636]. Our new camera change listeners support you in doing this. Your app can now receive notifications for camera start, ongoing, and end events.

I hear these are useful and we should consider supporting them as well for API parity.

/cc: @cammace @tobrun

**Comment by tobrun** [comment]
This landed on the release branch. Closing.
