### ISSUE TITLE
Can't find sprite named 'markerViewSettings' in Android

### ISSUE THREAD

**Issue by kingfisherphuoc** [mapbox/mapbox-gl-native#6352]
**Platform: Android**
**Mapbox SDK version: 4.1.1**

### Steps to trigger behavior

 1. Add mapview to fragment.
 2. The logcat logs too many info about: 

> I/mbgl: [Sprite]: Can't find sprite named 'markerViewSettings'
I/mbgl: [Sprite]: Can't find sprite named 'markerViewSettings'
I/mbgl: [Sprite]: Can't find sprite named 'markerViewSettings'
I/mbgl: [Sprite]: Can't find sprite named 'icon'
I/mbgl: [Sprite]: Can't find sprite named 'icon'

What is the problem of my mapbox map? is it just a debug log and how to turn it off?

**Comment by tobrun** [comment]
@boundsj this is because of annotations views ghosting annotations. I remember this also occurring on iOS and remember a PR coming by that resolved this. I'm unable to locate that one, could you link it? or explain the changes?

**Comment by kingfisherphuoc** [comment]
@tobrun I upgraded mapbox sdk to `4.2.0-beta.3@aar`, but nothing has changed. The errors above are logged even more when I add some markers to the map.
Can you give me a suggestion?

**Comment by klblk** [comment]
"Can't find sprite named 'icon'" call when Marker created MarkerOptions (not MarkerViewOptions). 
In issue #6422 logs:
```
{pboxandroiddemo}[JNI]: nativeUpdateMarker
{pboxandroiddemo}[JNI]: nativePixelForLatLng
{pboxandroiddemo}[JNI]: nativeRender
{pboxandroiddemo}[Android]: NativeMapView::activate
{pboxandroiddemo}[Sprite]: Can't find sprite named 'icon'
{pboxandroiddemo}[Android]: NativeMapView::notifyMapChange()
{pboxandroiddemo}[Android]: NativeMapView::notifyMapChange()
{pboxandroiddemo}[Android]: NativeMapView::updateFps()
{pboxandroiddemo}[Android]: NativeMapView::deactivate
{pboxandroiddemo}[Sprite]: Can't find sprite named 'icon'
{pboxandroiddemo}[Sprite]: Can't find sprite named 'icon'
{pboxandroiddemo}[Android]: NativeMapView::invalidate()
{pboxandroiddemo}[JNI]: nativeUpdateMarker
{pboxandroiddemo}[JNI]: nativePixelForLatLng
{pboxandroiddemo}[JNI]: nativeQueryPointAnnotations
{pboxandroiddemo}[JNI]: nativePixelForLatLng
```

**Comment by boundsj** [comment]
@tobrun 

>  I remember this also occurring on iOS and remember a PR coming by that resolved this. I'm unable to locate that one, could you link it? or explain the changes?

I'm sorry I missed this before. I think the iOS PRs you were thinking of are:

https://github.com/mapbox/mapbox-gl-native/pull/5461
https://github.com/mapbox/mapbox-gl-native/pull/5509

They add an invisible pixel so that the existing annotation management system has a way to track annotations at the GL level (as it always has) even though the the actual annotation is represented with a native view. I'm not certain that is the issue in this report although it may be.
