### ISSUE TITLE
Possibility to cancel downloading of offline pack.

### ISSUE THREAD

**Issue by dMozz** [mapbox/mapbox-gl-native#6353]
**Platform:** iOS
**Mapbox SDK version:** latest version

### Steps to trigger behavior

 1. Start downloading of offline pack
 2. Try to suspend or remove downloading pack.

### Expected behavior
Pack downloading stop and downloading process remove from downloading queue.
### Actual behavior
Downloading continuous. If at that point I try to open another screen with map I see black view. Map appears only when pack downloading finished.

![img_0241](https://cloud.githubusercontent.com/assets/21098201/18577474/9612ab46-7bf2-11e6-8db3-3c1f29994ebb.jpg)

**Comment by boundsj** [comment]
This is tracked in https://github.com/mapbox/mapbox-gl-native/issues/5538

**Comment by boundsj** [comment]
Actually, @1ec5 dropping notifications (https://github.com/mapbox/mapbox-gl-native/issues/5538#issuecomment-242944157) will appear to allow canceling a download but it probably won't solve the black map issue noted here, will it?

**Comment by friedbunny** [comment]
Offline downloading blocking maps from being displayed is over in #4414.
