### ISSUE TITLE
Pencil and satellite styles are broken

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#636]
On both Linux and Android at least, the pencil and satellite styles are broken.

Both only render black fill.

Satellite generates lots of `image is not a valid PNG image` errors. (libpng error message?)

**Comment by ljbade** [comment]
Satellite works now, but not labels.

Pencil is even worse.

**Comment by picciano** [comment]
Just confirming this is still an issue as of the latest build.

**Comment by thomas-huet** [comment]
Pencil is broken but there is more: it also breaks other styles. When I switch back to other styles, they no longer display contours, just labels.

**Comment by ljbade** [comment]
Yeah pencil style does mess up the other styles.

**Comment by bleege** [comment]
Removing from Android B1 Milestone as Pencil isn't being shipped and Satellite is working as expected.

**Comment by ljbade** [comment]
Hmm yeah, do we even need to test/support pencil any more? If not might as well close this.

**Comment by bleege** [comment]
Nope.  We're not shipping Pencil.
