### ISSUE TITLE
Custom Drawing Over Map

### ISSUE THREAD

**Issue by Reafidy** [mapbox/mapbox-gl-native#6365]
Im using the android SDK.

In Googlemaps I can use a [tile overlay](https://developers.google.com/maps/documentation/android-api/tileoverlay) and override the onDraw event to basically draw whatever I need onto a canvas which then gets overlayed onto the map.

This functionality does not seem to exist in MapBox.   There seems to be no way to override the ondraw event, and manually draw shapes with a canvas.   

I need to draw complex shapes like polygons with many small diamonds or circles creating the borders.  The native Mapbox polygons do not cut it.  

All if this can be done easily in Googlemaps.   I simply use the projection to convert lat/lngs to points on each tile bitmap.

See the image below.
![airspace](https://cloud.githubusercontent.com/assets/13157603/18624395/768f43fa-7e9b-11e6-99c0-239c6c4fd66d.jpg)

**Comment by vanshg** [comment]
+1

**Comment by Reafidy** [comment]
Is there currently anyway at all to draw on the canvas?  

If not I'm going have to revert to google maps which I really don't want to do.

**Comment by snowle0pard** [comment]
I am looking for that solution too!

**Comment by incanus** [comment]
Would something like https://github.com/mapbox/mapbox-gl-native/issues/1350 meet the use case?
