### ISSUE TITLE
selectAnnotation(annotation:, animated:) calls delegate method

### ISSUE THREAD

**Issue by marius-serban** [mapbox/mapbox-gl-native#6368]
**Platform: iOS**
**Mapbox SDK version: 3.3.4**

### Steps to trigger behavior

 1. call `selectAnnotation(annotation:, animated:)` on a `MGLMapView` instance

### Expected behavior
`mapView(mapView: MGLMapView, didSelectAnnotation annotation: MGLAnnotation)` should not be called
Generally throughout UIKit's API, delegate methods aren't called for programatically triggered events. It would be valuable if MapKit's API with be consistent with UIKit's behaviour in this aspect as well.

### Actual behavior
`mapView(mapView: MGLMapView, didSelectAnnotation annotation: MGLAnnotation)` is called

**Comment by 1ec5** [comment]
Just to be clear, the current behavior is consistent with MapKit but inconsistent with UIKit, correct?

We could easily make this change (same for deselection), but it'd probably count as a backwards-incompatible change, so it'd have to wait until the next major version.

**Comment by marius-serban** [comment]
Yes, that is correct. I realise it's a breaking change so it's not going to come out soon, just wanted to raise it. 👍

**Comment by jfirebaugh** [comment]
Thanks for the suggestion. I think in this case it's a higher priority for our SDK to retain consistency with MapKit; besides which, as mentioned, changing this behavior would be a breaking change. Therefore I'm going to close this issue -- we're not realistically planning to change this behavior.
