### ISSUE TITLE
Smooth animation longer than 200ms

### ISSUE THREAD

**Issue by donpark** [mapbox/mapbox-gl-native#637]
I having difficulty smoothly zooming for longer than 200ms. Call to scale with duration animates briefly then abruptly ends. Working around this with timer to make same call every 150ms results in lurching animation.

Reading the code, looks like all if not most animations are limited by this 200ms timeout. Is this true? If so, how can we implement smoothly animating maps?

**Comment by jfirebaugh** [comment]
This should be fixed by #1155.
