### ISSUE TITLE
Replace Log With Timber To Reduce Log Noise

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#6372]
Logging is an important day to day development tool used to build the Mapbox Android SDK, however as @clydebarrow notes in #6363 it can be a bit overwhelming when used in an actual app.  Thankfully Jake Wharton (who else?) has a very lightweight solution for this problem in his Timber library.  Timber achieves this by separating the actual Log statements from the Log output functionality.  In other words, the SDK will only emit log statements when configured to do so and not at all in Prod / `release` builds by default.  This will let Mapbox Android SDK developers continue to use log statements for their work (ie, in development mode), but will dramatically decrease the log statements that Mapbox Android SDK implementing developers will see in their apps.

https://github.com/JakeWharton/timber

/cc @mapbox/android

**Comment by clydebarrow** [comment]
I like it.

Two points - as I read the Timber code the default for _any_ build is no output at all. The "debug-build only" feature is required to be implemented by the app developer, as in the sample code where either a DebugTree or a custom crash reporter is installed by the application class's onCreate() based on the build status. 

I'd also make the observation while the methods that take arguments with format specifiers are very handy, I know from experience implementing my own logging library there is a potential gotcha when converting from Log.d calls which take a single literal message string. The Lint rules in Timber appear to address that, but it's still worth bearing in mind.

**Comment by masterjefferson** [comment]
I've been using Timber for a few weeks in our own app. No issues yet, and the format specifier support is worth it alone IMO.

**Comment by tobrun** [comment]
Noting here that most log currently shown in logcat are coming from jni/core and that these use `log_android.cpp`. Switching this with Timber is possible but not worth spending too much time on. Using Timber in java code of test app and sdk code is 👍

**Comment by zugaldia** [comment]
Timber is also pretty lightweight, 19K in `4.3.1`.

**Comment by Guardiola31337** [comment]
It is pretty small as well. It only adds 88 methods:
![timbermethodcount](https://cloud.githubusercontent.com/assets/1668582/20502740/884c09e0-b00d-11e6-9b56-9569e7ff9409.png)

**Comment by Guardiola31337** [comment]
Do we want to maintain former `TAG`s?
By default `Timber` uses the class name as `TAG`, but you can customize it.

cc/ @tobrun @zugaldia

**Comment by tobrun** [comment]
@Guardiola31337 using default would be great, clearly shows where the log is coming from.
