### ISSUE TITLE
beef up runtime styling test cases

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#6379]
On both iOS and Android in-repo test apps, we currently test: 

- Source/layer addition (GeoJSON, raster)
- Existing Studio-made layer style changes (colors, antialiasing, widths)

However, we don't yet exercise filters, which would have revealed #6233 earlier. 

I'm still possibly seeing an issue with filters and styling of existing layers even after #6233 was fixed, so rather than build a test case, I'm going to add one to the framework app. 

/cc @ivovandongen @frederoni @jfirebaugh

**Comment by jfirebaugh** [comment]
If you want to get really beefy, we could write a harness that can execute the [test-suite runtime styling tests](https://github.com/mapbox/mapbox-gl-test-suite/tree/master/render-tests/runtime-styling) against the platform SDK APIs.

**Comment by incanus** [comment]
Apparently the subject line wasn't enough to auto-close, so: got this in https://github.com/mapbox/mapbox-gl-native/pull/6433 with https://github.com/mapbox/mapbox-gl-native/pull/6433/commits/b846f543b02d088f68a32b1d24b29530c53ab346.

**Comment by incanus** [comment]
Re: test harness @jfirebaugh, will keep this in mind as we continue to near runtime styling release.
