### ISSUE TITLE
Replace MapChange enum and `Backend::notifyMapChange` with dedicated observer interface

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#6383]
The `MapChange` enumeration values have their roots in MapKit semantics -- yet are increasingly deviating from those semantics, or expanding on them. We should replace them with an API that is less influenced by the API of a particular platform, and more influenced by the pattern we use elsewhere for observation, e.g. [the style observer](https://github.com/mapbox/mapbox-gl-native/blob/23eaf6fb86644f036d8f09e5f8f80a116518bb84/src/mbgl/style/observer.hpp). It should be general enough that MapKit-like change notifications can be built on top of it.

**Comment by 1ec5** [comment]
In particular, it should be possible to include relevant information, such as an error pointer, along with a change notification. Awhile back, I started experimenting with making map change notifications more object oriented in the [1ec5-delegate-fail-loading-6142](https://github.com/mapbox/mapbox-gl-native/tree/1ec5-delegate-fail-loading-6142) branch, but imitating the style observer would be even better.

**Comment by jfirebaugh** [comment]
Related: https://github.com/mapbox/mapbox-gl-js/pull/3244
