### ISSUE TITLE
Multiple vector tile sources?

### ISSUE THREAD

**Issue by MH6** [mapbox/mapbox-gl-native#6384]
Is it possible to add multiple style URLs to a Mapbox map (Android)? I don't mean one style JSON pointing at different sources, but one map using multiple map style JSONs simultaneously. 

I have MBTiles for both a base map (OSM) and an overlay, both of which are in Mapbox vector format.  I want to add both layers to the map for **offline** use, but I see no way to do so--I can only set one "style" at a time. Each style has its own custom sprite sheet which further complicates things, meaning I'd have to composite them together. The only way to add extra layers (that I can see) involves GeoJSON. 

Is this just not possible with Mapbox GL? Can it only render one main style JSON at a time? 

I tried merging both vector styles together into one single style with two vector sources, but it spams _stencil mask overflow_ errors and the tiles do not render properly. Is this the "proper" way to have multiple vector tile layers in Mapbox?

**Comment by 1ec5** [comment]
mapbox/mapbox-gl#25

**Comment by jfirebaugh** [comment]
> Is this just not possible with Mapbox GL? Can it only render one main style JSON at a time?

That's correct. See the issue @1ec5 linked for some tentative ideas as to how we might support this in the future.
