### ISSUE TITLE
Annotations aren' t selected when map is rotated.

### ISSUE THREAD

**Issue by yarry** [mapbox/mapbox-gl-native#6393]
**Platform:** iOS
**Mapbox SDK version:** Built from source, commit f3b38df

### Steps to trigger behavior

 1. Add annotation views or sprites
 2. Rotate map more than 45 degrees CW or CCW
 3. Tap on an annotation

### Expected behavior
The annotation should be selected
### Actual behavior
The annotation isn't selected

**Comment by jfirebaugh** [comment]
@boundsj This is a duplicate of #6055, right?

**Comment by boundsj** [comment]
I'm pretty sure it is @jfirebaugh. I'll close this.
