### ISSUE TITLE
Update MAS 1.3.1 dependency

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#6394]
MAS 1.3.1 (`libjava`) was released yesterday https://github.com/mapbox/mapbox-java/issues/198. It's a maintenance release that brings a small fix for https://github.com/mapbox/mapbox-gl-native/issues/6240 that also unblocks https://github.com/mapbox/mapbox-android-demo/pull/139.

Let's update our dependency in MAS to the latest version.

/cc: @cammace @ivovandongen

**Comment by ivovandongen** [comment]
Done in #6398
