### ISSUE TITLE
Allow setting a custom CompassListener

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#6396]
We currently provide a `CompassListener` that makes use of a `Sensor.TYPE_ROTATION_VECTOR` to set the compass orientation in the user `MyLocationView`:

```
public CompassListener(Context context) {
    sensorManager = (SensorManager) context.getSystemService(Context.SENSOR_SERVICE);
    rotationVectorSensor = sensorManager.getDefaultSensor(Sensor.TYPE_ROTATION_VECTOR);
}
```

However, this only works for devices with a rotation vector sensor (e.g. gyroscope). For hardware without the required sensor, but with other sensors that could be used to detect the user orientation (e.g. 3 axis accelerometer, magnetometer), we should expose an API that let the developer set a custom listener.

This could be done in the following way:
1. Rename `CompassListener` to e.g. `RotationVectorListener` and make it our default implementation to provide compass functionality when the developer doesn't provide its own.
2. Make `CompassListener` an interface that the developer can implement.
3. Add a setter to `MyLocationView` that lets the developer set their own `CompassListener` implementation.
4. When `MyLocationView` gets instantiated, we can check if a custom `CompassListener` has been provided or, otherwise, create a fallback instance of `RotationVectorListener`.

Because the current `CompassListener` is internal, these changes are not breaking any existing API and it won't require a SEMVER change.

/cc: @mapbox/android

**Comment by tobrun** [comment]
MyLocationView is going to be replaced with [LocationLayer](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/locationlayer). Feel free to recreate this ticket in that repo.
