### ISSUE TITLE
Migrate iosapp action table to storyboard

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6401]
As discussed in https://github.com/mapbox/mapbox-gl-native/pull/6389#pullrequestreview-678053, after #6389 lands, I think we should consider migrating the action table to the storyboard, as a table with a series of static sections and static cells. Each static cell would be connected to a separate IBAction. This will prevent the cells and their actions from getting out of sync or out of order when new actions are added by contributors and automerged by Git.

(I also want to take the opportunity to celebrate the fact that you can now scroll table views in Interface Builder! 🎉)

/cc @incanus

**Comment by friedbunny** [comment]
The current programmatic system has been working well enough, it seems.

**Comment by 1ec5** [comment]
We’ve had a lot of bad merges involving switch statements in MBXViewController.m in the past. While the new case statements aren’t positional like the old ones, the enums are. If anything, the new system exacerbates the issue, but we haven’t been hitting it lately because we haven’t been adding demos in simultaneous PRs. If you’re sure the current approach is the right one, we’ll need to be extra vigilant about any PR involving iosapp.
