### ISSUE TITLE
test-suite text-rotation-alignment tests are failing

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#6410]
Three `text-rotation-alignment` tests in the test-suite are rendering differently than gl-js. This is fallout of #6253 but appears to be related to the placement algorithm or `symbol-spacing` rather than `text-rotation-alignment` itself.

### text-rotation-alignment/{auto,map}-symbol-placement-line

These two tests are expected to produce the same output.

Expected (with/without collison debug):

![image](https://cloud.githubusercontent.com/assets/98601/18694290/9c0617b8-7f5d-11e6-8f59-696e43a36886.png) ![image](https://cloud.githubusercontent.com/assets/98601/18759785/0bb8adae-80b3-11e6-9154-fc550d96af5a.png)

Actual (with/without collison debug):

![image](https://cloud.githubusercontent.com/assets/98601/18694277/7b2448b2-7f5d-11e6-8d7c-7f8e3e45de5e.png) ![image](https://cloud.githubusercontent.com/assets/98601/18759794/1c2214f0-80b3-11e6-9e82-ad4b3a98b0a5.png)

### text-rotation-alignment/viewport-symbol-placement-line

Expected (with/without collison debug):

![image](https://cloud.githubusercontent.com/assets/98601/18694317/d8ca53da-7f5d-11e6-86b8-d93dd2a5274c.png) ![image](https://cloud.githubusercontent.com/assets/98601/18759761/e00bc0ce-80b2-11e6-9e8c-30f06667dc47.png)

Actual (with/without collison debug):

![image](https://cloud.githubusercontent.com/assets/98601/18694318/deec1bb8-7f5d-11e6-9769-855f9b2592d7.png) ![image](https://cloud.githubusercontent.com/assets/98601/18759764/e549be6a-80b2-11e6-91e7-2341ec82a4dc.png)

**Comment by jfirebaugh** [comment]
It looks like the root of this problem may be the use of `float` rather than `double` for symbol layout properties such as `text-line-height`. The default value for `text-line-height` is `1.2`, which cannot be represented precisely by a `float`. This cascades into significant errors in subsequent computations compared to gl-js, which is using doubles exclusively.

**Comment by jfirebaugh** [comment]
Another issue is that native [`Shaping` uses `int32_t` coordinates](https://github.com/mapbox/mapbox-gl-native/blob/c20c1d6a6b3eb301db88ca3e74993f445cc4d839/src/mbgl/text/glyph.hpp#L62-L65), while JS [uses unrounded doubles](https://github.com/mapbox/mapbox-gl-js/blob/c01fec109804c1e1955c62e6aec4b506f6d94691/js/symbol/shaping.js#L140-L143).

**Comment by jfirebaugh** [comment]
[gl-native `CollisionTile::minScale = 0.5f`](https://github.com/mapbox/mapbox-gl-native/blob/4d3356dc1e1239d8f4fb985d2f584a403aea8521/src/mbgl/text/collision_tile.hpp#L48). [gl-js `CollisionTile.prototype.minScale = 0.25`](https://github.com/mapbox/mapbox-gl-js/blob/7ca58c020bcb9f3eb3ab9eb8b7d704db9ee2023c/js/symbol/collision_tile.js#L95-L95)

@ansis is there any reason for these not to be the same? Should it be 0.25 or 0.5?

**Comment by jfirebaugh** [comment]
Another float vs integer discrepancy, this one going in the opposite direction: gl-js [round trips collision box coordinates through Int16](https://github.com/mapbox/mapbox-gl-js/blob/f8aeecfccf0c06ae716207febef13f01c8ab108e/js/symbol/collision_box.js#L45-L53), while native [keeps them floating point](https://github.com/mapbox/mapbox-gl-native/blob/4d3356dc1e1239d8f4fb985d2f584a403aea8521/src/mbgl/text/collision_feature.hpp#L16-L23).

**Comment by ansis** [comment]
> is there any reason for these not to be the same? Should it be 0.25 or 0.5?

I think they should be the same.

I think 0.5 seems good. I think maybe it should be sharing a constant value with the minScale used in quads.js/cpp. But maybe they can be different and the CollisionTile version can be changed to 0 and eliminated completely?

The only thing I think this affects is whether labels are visible when you quickly zoom out and underscale a tile.

I don't think this should have any effect on placement in a tile's intended zoom range.

**Comment by jfirebaugh** [comment]
Fixed by tweaking the test case. Using #3841 to track the above issues.
