### ISSUE TITLE
make qt-lib missing

### ISSUE THREAD

**Issue by ro-ka** [mapbox/mapbox-gl-native#6415]
**Platform:** OSX
**Mapbox SDK version:** Current master / `3.3.3` in `package.json`

### Steps to trigger behavior

 1. Checkout repository
 2. Run `make qt-lib`

### Expected behavior

Building the library.

### Actual behavior

An error:

```sh
make: *** No rule to make target `qt-lib'.  Stop.
```

**Comment by tmpsantos** [comment]
Thanks for reporting this issue, the target is indeed missing. Probably went away when we migrated the build system to `cmake`. Gonna add it back.

**Comment by Eth4nZ** [comment]
Encountered the same issue.

**Platform:** OSX
**Mapbox SDK version:** Current master / 3.5.5 in package.json

### Steps to trigger behavior

Checkout repository
Run make qt-lib
### Expected behavior

Building the library.

### Actual behavior

An error:

```
make: *** No rule to make target 'qt-lib'.  Stop.
```
