### ISSUE TITLE
make run-qt-app crashes

### ISSUE THREAD

**Issue by ro-ka** [mapbox/mapbox-gl-native#6416]
**Platform:** OSX
**Mapbox SDK version:** Current master / 3.3.3 in package.json

### Steps to trigger behavior

 1. Checkout repository
 2. `make qt-app`
 3. `make run-qt-app`

### Expected behavior

A new window with the Qt example opens.

### Actual behavior

Crashes:

```sh
platform/macos/ninja  -j8 -C build/qt-macos-x86_64/Debug mbgl-qt
ninja: Entering directory `build/qt-macos-x86_64/Debug'
[3/3] Automatic moc and rcc for target mbgl-core
build/qt-macos-x86_64/Debug/mbgl-qt
[INFO] {DefaultFileSource}[Database]: statement aborts at 37: [UPDATE resources SET accessed = ?1 WHERE url = ?2] attempt to write a readonly database (Code 8)
libc++abi.dylib: terminating with uncaught exception of type mapbox::sqlite::Exception: attempt to write a readonly database
make: *** [run-qt-app] Abort trap: 6
```

**Comment by ro-ka** [comment]
Ahh, just figured that it’ll need to be run with `sudo`. Maybe handling that would clarify it? Or at least explain it in the Readme?

**Comment by tmpsantos** [comment]
> Ahh, just figured that it’ll need to be run with sudo.

No, you don't need to use `sudo`. The cache is set by default to `/tmp/mbgl-cache.db`. Check if you have permissions on this directory, if not, you can change the defaults here:

```
platform/qt/app/main.cpp:10:    settings.setCacheDatabasePath("/tmp/mbgl-cache.db");
platform/qt/src/qquickmapboxglrenderer.cpp:18:    settings.setCacheDatabasePath("/tmp/mbgl-cache.db");
```

Note: The QML API has the cache hardcoded and it is under heavy development at the moment.
