### ISSUE TITLE
Missing styles in Qt examples

### ISSUE THREAD

**Issue by ro-ka** [mapbox/mapbox-gl-native#6417]
**Platform:** OSX
**Mapbox SDK version:** Current master / 3.3.3 in package.json

### Steps to trigger behavior

 1. Checkout repository
 2. `make qt-app` or `make qt-qml-app`
 3. `sudo make run-qt-app` or `sudo make run-qt-qml-app`

### Expected behavior

A new window with the Qt example opens and shows the map. 

### Actual behavior

A new window opens but there is no map visible.

```sh
[ERROR] {QSGRenderThread}[Setup]: loading style failed: HTTP status code 401
```

**Comment by tobrun** [comment]
401 indicates you are not authorized. I think you missed this part from the readme:

> Both QMapboxGL and QQuickMapboxGL requires a Mapbox access token at runtime - you need to provide it by setting the environment variable MAPBOX_ACCESS_TOKEN:
>`export MAPBOX_ACCESS_TOKEN=MYTOKEN`

**Comment by ro-ka** [comment]
Good point. I’ve set the token now but the error remains. Using my standard token shown in Studio should work, right?

**Comment by tobrun** [comment]
Yes, that should work ;) were you able to display a map?

**Comment by ro-ka** [comment]
No sadly not. Error is still the `401` from above. The error is logged out when I move the invisible app or want to change the map style.

<img width="1136" alt="bildschirmfoto 2016-09-22 um 11 17 37" src="https://cloud.githubusercontent.com/assets/840022/18742756/34b05bb4-80b6-11e6-9a88-26d41ef926f2.png">

**Comment by tmpsantos** [comment]
> sudo make run-qt-app or sudo make run-qt-qml-app

You should not use `sudo` here. It is not required for building our project. This could be interfering with carrying on the `MAPBOX_ACCESS_TOKEN` variable (i.e. it is set to your user but not to `root`).

**Comment by tmpsantos** [comment]
Closing as the probably cause is the `sudo`. Please reopen if you can still see this happening after a clean build without `sudo`.

**Comment by ro-ka** [comment]
That’s possible. But running without sudo crashes (see #6416).

**Comment by tmpsantos** [comment]
> That’s possible. But running without sudo crashes (see #6416).

I replied there, but seems to me that you don't have permission to open/create a database at `/tmp/mbgl-cache.db`.

**Comment by tmpsantos** [comment]
@ro-ka you can also disable the disk cache by setting it to `:memory:`.
