### ISSUE TITLE
Qt missing from contribution page

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#6424]
From https://github.com/mapbox/mapbox-gl-native/blob/master/CONTRIBUTING.md:

![screen shot 2016-09-22 at 12 02 18](https://cloud.githubusercontent.com/assets/2151639/18744049/7a2e3e3a-80bc-11e6-9d21-9d67b3bef731.png)

We are missing documentation for contributing to the Qt binding. 

cc @brunoabinader @tmpsantos

**Comment by tmpsantos** [comment]
We have not released any stable versions yet. That said, we are going to do it for:
https://codereview.qt-project.org/#/c/170890/

After the release we add a `platform/qt/CHANGELOG.md` and an entry to this document.
