### ISSUE TITLE
[android] Bearings calculation does not match documentation in CameraPosition.Builder

### ISSUE THREAD

**Issue by lkho** [mapbox/mapbox-gl-native#6430]
**Platform:**  Android
**Mapbox SDK version:** 4.2.0-beta.3

Referenced SO thread: http://stackoverflow.com/questions/37972357/what-are-the-correct-units-when-dealing-with-camerapostion-camerapostion-builde

### Steps to trigger behavior
according to https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java#L34-L37:

>     /**
     * Direction that the camera is pointing in, in degrees clockwise from north.
     */
    public final double bearing;

test 1:
```java
double degree = 90;
CameraPosition position = new CameraPosition.Builder(false).bearing(degree).build();
Assert.assertEquals(degree, position.bearing, 0.01);
```
test 2:
```java
double degreeClockwise = 90;
double radianClockwise = degreeClockwise / 180 * Math.PI;
CameraPosition positionDegree = new CameraPosition.Builder(false).bearing(degreeClockwise).build();
CameraPosition positionRadian = new CameraPosition.Builder(true).bearing(radianClockwise).build();
Assert.assertEquals(positionDegree.bearing, positionRadian.bearing, 0.01);
```

### Expected behavior
both tests pass.

### Actual behavior
test 1 throws `AssertionFailedError: expected:<90.0> but was:<-1.5707963705062866>`
test 2 throws `AssertionFailedError: expected:<-1.5707963705062866> but was:<1.5707963267948966>`, and the `positionDegree.bearing` becomes anti-clockwise.

**Comment by tobrun** [comment]
This should be fixed with https://github.com/mapbox/mapbox-gl-native/pull/6641
