### ISSUE TITLE
Add API for managing a style’s icon images

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6436]
MGLStyle should have methods for managing a style’s images based on the mbgl support added in #6375. This will make it easier to work with style properties such as `iconImage`.

We could either implement `-imageNames`, `-image:forName:`, and `-setImage:forName:` or a single, mutable `imagesByName` dictionary property along the lines of #6097. Images would be straight-up NSImages (on macOS) or UIImages (on iOS). Style images are very closely related to `MGLAnnotationImage.image`, but I don’t think we should tangle this API with MGLAnnotationImage at all, because MGLAnnotationImage is sort of a proxy view object while style images only last for the lifetime of the style.

/cc @incanus @frederoni

**Comment by rmnblm** [comment]
I am facing this problem right now. Styling the points with a `MGLCircleStyleLayer` works perfectly:

```
let geoJSONURL = Bundle.main.url(forResource: "siliconvalley", withExtension: "geojson")!

let geoJSONSource = MGLGeoJSONSource(sourceIdentifier: "sv", url: geoJSONURL)
mapView.style().add(geoJSONSource)

let cafeStyleLayer = MGLCircleStyleLayer(layerIdentifier: "sv-cafe-layer", sourceIdentifier: "sv")!
cafeStyleLayer.predicate = NSPredicate(format: "amenity == 'cafe'")
cafeStyleLayer.circleColor = UIColor.brown
mapView.style().add(cafeStyleLayer)

...
```

I tried to replace the `MGLCircleStyleLayer` with a `MGLSymbolStyleLayer` and setting the `iconImage` but couldn't get it to work. What is the recommended way to do this atm?

One possible solution: I could parse the GeoJSON manually (like this: https://github.com/rmnblm/mapbox-ios-examples/blob/master/src/Examples/AsyncPinDroppingViewController.swift) and filter each annotation inside the delegate method `public func mapView(_ mapView: MGLMapView, imageFor annotation: MGLAnnotation) -> MGLAnnotationImage?`. Any other ideas?

**Comment by 1ec5** [comment]
Note that iconImage is actually the name of a sprite in the style's sprite sheet, not any arbitrary image in the resource bundle. The feature proposed here would add a way to add an image from your resource bundle to the sprite sheet programmatically.

In the meantime, you could use point annotations if you're OK with the differences in behavior.

**Comment by rmnblm** [comment]
If I use point annotations I'd lose the support of clustering, which means, I can only have _clustering support with style layers without custom marker_ or _no clustering without style layer with custom markers_, right? 🙈 

Which leads me to the question on how you're going to implement this proposed feature: Which `iconImage` are you going to display on a clustered point?

**Comment by 1ec5** [comment]
Ah, if you need clustering, then annotations aren’t an option yet: #5814. We don’t expect to implement that in time for the v3.4.0 release, so the short answer to your question is that clustering uses the `iconImage` property, which is a sprite name rather than a file name. (See also #6098, wherein I complain about this confusing property name.)

It is currently possible to take advantage of the fact that annotations are implemented using ordinary style layers. It’s a real kludge, but as a workaround, you could force your own images to be installed as sprites and use them for clustered GeoJSON points: add a dummy MGLPointAnnotation for each image you want to install, so that you can provide an MGLAnnotationImage; from then on, you can use that image as an `iconImage` or `backgroundPattern`. Prepend [`com.mapbox.sprites.`](https://github.com/mapbox/mapbox-gl-native/blob/922bb3bc37696b736fe383f1347d007a423512f5/platform/ios/src/MGLMapView.mm#L109) to the MGLAnnotationImage’s reuse identifier to get the sprite name.

Note that this approach relies on several implementation details that can and probably will change without notice in a future release. If you can wait for this issue to be resolved, simply calling `-[MGLStyle setImage:forName:]` would be _much_ better. 😄

**Comment by nitrag** [comment]
+1 on this!

Sprite: So if I have an image, how is it converted to a (vector?) sprite? Quality / performance degradations/improvements in doing this? How does it know the appropriate size?

`iconImage` vs `clusterImage`. I've seen other SDK's have ability to have a different cluster view. Either bubbles, bubbles /w text, or a different image than the marker/annotation themselves.

While simple and performant, circle annotations aren't that pretty/usable in some real life apps and I'd very much like to see this implemented!

**Comment by 1ec5** [comment]
> Sprite: So if I have an image, how is it converted to a (vector?) sprite? Quality / performance degradations/improvements in doing this? How does it know the appropriate size?

Sprites are raster images. They are baked into the style, and you can provide them at runtime via MGLAnnotationImage for point annotations. The proposed API will allow you to add sprites for more general usage. The quality and performance characteristics are equivalent to MGLAnnotationImage usage, except that sprites get wiped away when you switch styles. No resizing takes place.

> `iconImage` vs `clusterImage`. I've seen other SDK's have ability to have a different cluster view. Either bubbles, bubbles /w text, or a different image than the marker/annotation themselves.

`iconImage` (which is already implemented) is equivalent to the [`icon-image`](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-icon-image) property in the style specification. Sprites are also used for other properties, such as `fillPattern` ([`fill-pattern`](https://www.mapbox.com/mapbox-gl-style-spec/#paint-fill-pattern)). No style specification changes will be made within the scope of this iOS/macOS-specific issue.

Nevertheless, [as demonstrated by this GL JS example](https://www.mapbox.com/mapbox-gl-js/example/cluster/), it’s already possible to make a cluster look different than the individual points it represents. A bubble or bubble with text would use an MGLCircleStyleLayer, while a point-placed image would require an MGLSymbolStyleLayer instead.

**Comment by rmnblm** [comment]
So I tried your workaround @1ec5 but still get `Can't find sprite named 'custom-bank'`

Here's how I implemented it:

1. I added a PNG image to the Assets.xcassets folder (actually, I added two images, one 1x and one 2x). Let's name this image "custom-bank".
2. In the `viewDidLoad()` method, I'm adding a dummy annotation:

    ```
    let point = MGLPointAnnotation()
    point.title = "custom-bank"
    mapView.addAnnotation(point)
    ```

3. The delegate function gets called

  ```
  public func mapView(_ mapView: MGLMapView, imageFor annotation: MGLAnnotation) -> MGLAnnotationImage? {
      let reuseIdentifier = "com.mapbox.sprites.\(annotation.title!!)"
      var annotationImage = mapView.dequeueReusableAnnotationImage(withIdentifier: reuseIdentifier)
      
      if annotationImage == nil {
          let image = UIImage(named: annotation.title!!)!
          annotationImage = MGLAnnotationImage(image: image, reuseIdentifier: reuseIdentifier)
      }
      
      return annotationImage
  }
  ```

4. Adding an MGLSymbolStyleLayer

  ```
  let styleLayer = MGLSymbolStyleLayer(layerIdentifier: "bank", sourceIdentifier: "sv")!
  styleLayer.iconImage = "custom-bank" as MGLStyleAttributeValue!
  mapView.style().add(styleLayer)
  ```

**Comment by 1ec5** [comment]
You’ve got it backwards: internally, `com.mapbox.sprites.` is prepended to the reuse identifier to form the sprite name. So `com.mapbox.sprites.custom-bank` would be the `iconImage` value.

**Comment by rmnblm** [comment]
Still no luck when I change it to 

```
styleLayer.iconImage = "com.mapbox.sprites.custom-bank" as MGLStyleAttributeValue!
```

😞

**Comment by 1ec5** [comment]
The reuse identifier shouldn’t have that prefix, though. If it doesn’t, you’ll have to wait for the fix outlined here.

**Comment by rmnblm** [comment]
I doesn't have that prefix. Full implementation details can be found [here](https://github.com/rmnblm/mapbox-ios-examples/blob/7554943d11c78136277b34ec7112b08ab4c70eae/src/Examples/FilteringViewController.swift). You may find a mistake or I may have to wait until this fix is outlined and implemented.
