### ISSUE TITLE
Elevation at Tilt (3D)

### ISSUE THREAD

**Issue by nitrag** [mapbox/mapbox-gl-native#6445]
I noticed by default the map can tilt with two fingers. What's the point of tilting the map without terrain data? I guess I was hoping there would be 3D/terrain for mountains. What would it take to make this possible? Is this on the roadmap somewhere? (Link to roadmap?)

I'm using the Mapbox Streets standard style. 

Thanks!

**Comment by boundsj** [comment]
@nitrag thanks for your interest. You can follow along with the work in https://github.com/mapbox/mapbox-gl-style-spec/issues/456 for 3d extrusions and the conversation about support for 3d terrain in https://github.com/mapbox/mapbox-gl-js/issues/1489. There is no current ETA for when these features will land in GL native. You can monitor our GitHub release milestones to get a sense for what's next.
