### ISSUE TITLE
iOS Xcode "unknown schema version"

### ISSUE THREAD

**Issue by rmnblm** [mapbox/mapbox-gl-native#6450]
**Platform:** iPhone 6, iOS 10.0.1, Xcode 8.0, Swift 3
**Mapbox SDK version:** 3.3.4

### Steps to trigger behavior

 1. Install Mapbox with CocoaPods
 2. Run on iPhone (not simulator!)
 3. App crashes when displaying the MGLMapView with following error `libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: unknown schema version`

### Expected behavior

Well, no crash 👀 

### Actual behavior

The app crashes

### Additional information

Running the app in the simulator works fine. My Podfile looks like this

```
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MyApp' do
  project 'MyApp.xcodeproj'
  pod 'Mapbox-iOS-SDK', '~> 3.3.4'
end
```

**Comment by rmnblm** [comment]
Deleting and rebuilding the app fixed the issue.

**Comment by Phrogz** [comment]
I was just having this same error on Qt 5.9 (but not Qt 5.10.0a) on Linux:

```
QML debugging is enabled. Only use this in a safe environment.
terminate called after throwing an instance of 'std::runtime_error'
  what():  unknown schema version
Aborted (core dumped)
```

Cleaning and rebuilding with Qt Creator did not fix the problem.  
Reinstalling all of Qt did not fix the problem.
Deleting `~/.cache/QtLocation` fixed the problem.
