### ISSUE TITLE
Testing the built in GeoJSON functionality

### ISSUE THREAD

**Issue by nitrag** [mapbox/mapbox-gl-native#6451]
In iOS, using the latest alpha and Swift, I'm trying to test adding a GeoJSON source from a file and loading all the markers within (10k points). End goal is a clustered marker view.

[✓] Copy valid geojson file into resources
[✓] Load geojson file
[✓] Create GeoJSON Source
[] Add layers?
[] Change annotations/markers from circles to images
[] Experiment with clustering

I've been using this Test as my [guide](https://github.com/mapbox/mapbox-gl-native/blob/4c8d61abf18fc5fde07c53b520eb0696d138106c/platform/darwin/test/MGLBackgroundStyleLayerTests.m) but I don't see ANYTHING on the map. Zero errors.

```Swift
func addGeoJSONSource(){

    let options: [String : Any] = [
        "cluster" : true,
        "clusterRadius" : 42,
        "clusterMaxZoom" : 11,
        "maxzoom" : 20,
        "buffer": 1976,
        "tolerance" : 0.42
    ]
    
    let jsonPath = Bundle.main.path(forResource: "markers", ofType: "geojson")
    let filePath = URL(fileURLWithPath: jsonPath!)
    let geoJsonSource = MGLGeoJSONSource(sourceIdentifier: "markers", url: filePath, options: options)
    self.mapView.style().add(geoJsonSource);
    NSLog("Source has been created and added");
    
    let fillLayer = MGLFillStyleLayer(layerIdentifier: "fill-geojson", sourceIdentifier: "markers")
    fillLayer?.fillColor = UIColor.purple
    self.mapView.style().add(fillLayer!);

    let circleLayer = MGLCircleStyleLayer(layerIdentifier: "circle-geojson", sourceIdentifier: "markers")
    circleLayer?.circleColor = UIColor.purple
    self.mapView.style().add(circleLayer!);

    let lineLayer = MGLLineStyleLayer(layerIdentifier: "line-geojson", sourceIdentifier: "markers")
    lineLayer?.lineColor = UIColor.purple
    self.mapView.style().add(lineLayer!);
    
    NSLog("Done adding GeoJSON");
}
```

As I said, I don't get any errors and nothing appears on the map. What am I missing?

Also, I know the API docs are [here](https://www.mapbox.com/ios-sdk/api/3.3.4/), but is there a hosted version for Alphas?

**Comment by friedbunny** [comment]
API documentation for pre-releases is available: https://www.mapbox.com/ios-sdk/api/3.4.0-alpha.4/

See [the Github release](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.4.0-alpha.4) for more information about changes, installation, and docs.

**Comment by rmnblm** [comment]
I'm currently building an iOS app with some examples built with Swift 3 and the newest Mapbox 3.4.0-alpha.4. 

Clustering works with my example see: https://github.com/rmnblm/mapbox-ios-examples/blob/master/src/Examples/ClusteringViewController.swift

I'm going to put in some work the next few days and weeks. 😁

**Comment by boundsj** [comment]
Thanks for sharing your example @rmnblm. 

@nitrag [here is another example](https://gist.github.com/boundsj/1a239f5f3e4d27eb7a4fba54db328152) of using a GeoJSON source combined with filters (predicates) and clustering to create an earthquake map. We will be sharing many more examples in the coming weeks. Thanks for helping us test!

**Comment by nitrag** [comment]
@boundsj You helped me pinpoint the issue with your example. Apparently I can't call my function within `viewDidAppear()` (no errors thrown). I used your `func mapViewDidFinishLoadingMap(_ mapView: MGLMapView)` and it loads great. Also worth noting that my `mapView` is a subclass of my view controller. Is this a bug? Perhaps a warning should be thrown when trying to add a style/layer before the view is initialized?

**Comment by boundsj** [comment]
@nitrag 

> Apparently I can't call my function within viewDidAppear() (no errors thrown). I used your func mapViewDidFinishLoadingMap(_ mapView: MGLMapView) and it loads great.

These APIs are new in the 3.4.0 alpha releases and will be better documented by the time of the final release. Relatedly, see https://github.com/mapbox/mapbox-gl-native/issues/6412 and https://github.com/mapbox/mapbox-gl-native/issues/6386#issuecomment-249033669 for some preview of new APIs we intend to expose that'll make runtime styling APIs easier to use

> Also worth noting that my mapView is a subclass of my view controller. Is this a bug?

It is expected that an instance of `MGLMapView` will be owned by (but definitely not a subclass of) a view controller, just like any other `UIView`. It is also common for the view controller to be the delegate of the map view.

> Perhaps a warning should be thrown when trying to add a style/layer before the view is initialized?

Thanks for the suggestion! I hope that APIs like the one mentioned in https://github.com/mapbox/mapbox-gl-native/issues/6386#issuecomment-249033669 once implemented and documented will help here.
