### ISSUE TITLE
Android - restoring tilt after screen rotate

### ISSUE THREAD

**Issue by tomlocks** [mapbox/mapbox-gl-native#6453]
Platform: Android 6.0.1
Mapbox SDK version: 4.2.0-beta.3

### Steps to trigger behavior

 1. Start Mapbox Dev Preview
 2. Start simple map view.
 3. Tilt map using two finger gesture just a little bit.
 4. Rotate screen.

### Expected behavior
 Saving and restoring last tilt value.

### Actual behavior
 Tilt is set to maximum(59.99999999999999).

Screenshots:
Before screen rotation(tilt value: approx. 5).
![screenshot_20160926-095812](https://cloud.githubusercontent.com/assets/9156700/18826987/a2273aba-83d0-11e6-8daa-433dd58c2287.png)
After rotation(tilt = 59.99999999999999).
![screenshot_20160926-095818](https://cloud.githubusercontent.com/assets/9156700/18826991/a7f893e4-83d0-11e6-972a-abefa870a18b.png)

**Comment by tobrun** [comment]
I have looked into this and validated that the oncreate and onsaveinstance state are correctly working. Now noticed that incorrect behaviour by setting the tilt in xml. There seems to be a problem with jumpTo implementation.
