### ISSUE TITLE
Custom annotation views disappear after scrolling map down and then return back

### ISSUE THREAD

**Issue by aksonov** [mapbox/mapbox-gl-native#6458]
**Platform:** iOS
**Mapbox SDK version:** latest

### Steps to trigger behavior

 1. Create custom annotation class
```
@interface CustomAnnotation : MGLAnnotationView<MGLAnnotation>

@property (nonatomic, readonly) CLLocationCoordinate2D coordinate;

@end

@implementation CustomAnnotation

-(id)init {
    self = [super init];
    self.frame = CGRectMake(0, 0, 300, 300);
    self.backgroundColor = [UIColor blackColor];
    UILabel *label = [[UILabel alloc] initWithFrame:CGRectMake(0, 0, 300, 300)];
    label.text = @"TEST";
    [self addSubview:label];
    return self;
}

-(CLLocationCoordinate2D)coordinate {
    CLLocationCoordinate2D coords;
    coords.latitude = 37.33233141;
    coords.longitude = -122.0312186;
    return coords;
}
```
2. Add custom annotation to map:
```
- (nullable MGLAnnotationView *)mapView:(MGLMapView *)mapView viewForAnnotation:(id <MGLAnnotation>)annotation {
  return annotation;
}

- (void)viewDidLoad {
  [super viewDidLoad];
  NSURL *styleURL = [NSURL URLWithString:@"mapbox://styles/mapbox/streets-v8"];
  
  MGLMapView *mapView = [[MGLMapView alloc] initWithFrame:self.view.bounds styleURL:styleURL];
  
  mapView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
  mapView.delegate = self;
  
  // Set the map’s center coordinate and zoom level.
  [mapView setCenterCoordinate:CLLocationCoordinate2DMake(37.33233141, -122.0312186)
                     zoomLevel:17
                      animated:NO];
  [mapView addAnnotation:[[CustomAnnotation alloc] init]];
  [self.view addSubview:mapView];
}
```

3. Run, saw annotation successfully, but it disappears once scroll it away and then scroll back

### Expected behavior
Custom annotation still visible

### Actual behaviour
Annotation disappears

Am I doing something wrong?

**Comment by boundsj** [comment]
Hi @aksonov. `-[MGLMapViewDelegate mapView:viewForAnnotation:]` should return an MGLAnnotationView. Xcode should warn you that `MGLAnnotation` is incompatible. Please check out the [annotation view example](https://www.mapbox.com/ios-sdk/examples/annotation-views) for more details about how to build the functionality you are looking for.

**Comment by aksonov** [comment]
@boundsj Thanks for the answer! Actually my CustomAnnotation implements MGLAnnotation protocol (to provide coordinate). After more debug i've found the reason of failure - dequeueReusableAnnotationViewWithIdentifier call is _required_ for proper work. I believe you must state it somewhere in docs. Once I remove it from your Example custom annotations are not shown.

**Comment by boundsj** [comment]
> dequeueReusableAnnotationViewWithIdentifier call is required for proper work

Thanks agian @aksonov. Although it is a good idea to use the reuse queue and call `dequeueReusableAnnotationViewWithIdentifier:` as shown in the example, I don't think we intended to force developers to use the reuse queue. 

I'm calling this a bug for now and I've proposed a fix in https://github.com/mapbox/mapbox-gl-native/pull/6485. Please follow along there for additional updates.
