### ISSUE TITLE
What does MGLMapView.metersPerPointAtLatitude return?

### ISSUE THREAD

**Issue by jameshfisher** [mapbox/mapbox-gl-native#6463]
I'm trying to understand [the documentation for `metersPerPointAtLatitude`](https://www.mapbox.com/ios-sdk/api/3.3.4/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)metersPerPointAtLatitude:). It says:

> Returns the distance spanned by one point in the map view’s coordinate system

What I don't understand is, what is "one point in the map view’s coordinate system"? If this is a *point*, shouldn't it always return 0, because a point spans no distance?

What I'm looking for is a method telling me `metersPerPixel` or `pixelsPerMeter`.

**Comment by jameshfisher** [comment]
I've just discovered that what I want already exists, but it's deprecated!

```
    @available(*, deprecated, message: "Use -metersPerPointAtLatitude:.")
    open func metersPerPixel(atLatitude latitude: CLLocationDegrees) -> CLLocationDistance
```

The message is not helpful - again, what is a "point"? How do I convert a "point" to pixels?

**Comment by friedbunny** [comment]
Drawing code on iOS should not typically deal in pixels — you should use points. Read [Apple’s iOS Drawing Concepts](https://developer.apple.com/library/content/documentation/2DDrawing/Conceptual/DrawingPrintingiOS/GraphicsDrawingOverview/GraphicsDrawingOverview.html) guide for more information, but points are essentially a collection of pixels that take into account density scaling. 

See [our point conversion example](https://www.mapbox.com/ios-sdk/examples/point-conversion/) for more information on how to convert points ↔ geographic coordinates.

**Comment by jameshfisher** [comment]
@friedbunny got it, thanks! Perhaps this could be made more clear in the "Converting Geographic Coordinates" section of the docs? The docs freely mix using the term "point" to refer to this "collection of pixels" but also to `CgPoint`s. Perhaps "point" could link to [this section](https://developer.apple.com/library/content/documentation/2DDrawing/Conceptual/DrawingPrintingiOS/GraphicsDrawingOverview/GraphicsDrawingOverview.html#//apple_ref/doc/uid/TP40010156-CH14-SW7).

**Comment by friedbunny** [comment]
Thanks for your feedback — please feel free to propose PRs, even if they’re just clarifications to the documentation. 😄

In this case, CGPoint and our mentions of “one point in the map view’s coordinate system” are the same thing (and this isn’t contradictory to my [very simplistic] “collection of pixels” definition). Indeed, [CGPoint is defined as](https://developer.apple.com/reference/coregraphics/cgpoint):

> A structure that contains a point in a two-dimensional coordinate system.

Pixels underlie this 2D coordinate system, but that’s an abstracted implementation detail that’s beyond the scope of this project.

**Comment by PandaraWen** [comment]
@jameshfisher Same confusion here! I am also not understand what the document of `metersPerPointAtLatitude` means, and I have read through your conversation, but still not found the answer, so have I found the usage of this method? thx!
