### ISSUE TITLE
How should I intercept MapBox's map, in the code.

### ISSUE THREAD

**Issue by HatBoys** [mapbox/mapbox-gl-native#6472]
Hello ！ I am a Android Developer, I tried to start from the SurfaceView, but the process of drawing the map is called Jni implementation, I do not know if you have any programs to solve this problem? Looking forward to reply, thank you!

**Comment by tobrun** [comment]
This repo is for tracking bugs, crashes and feature requests.
Feel free to ask any questions you have on https://www.mapbox.com/contact/.

**Comment by HatBoys** [comment]
ok，thank you for your suggestion！
