### ISSUE TITLE
Methods count in mapbox android 4.0.x vs 4.1.x

### ISSUE THREAD

**Issue by ntoskrnl** [mapbox/mapbox-gl-native#6473]
I have noticed that methods count in mapbox android library has significantly increased by ~10k when upgrading from 4.0x to 4.1.x. I'm not completely sure though. Could anyone confirm that?

If this is the case, what happened?

**Comment by tobrun** [comment]
Thank you for reaching out. I believe we added Mapbox Android services.

```
    // Mapbox Android Services
    compile('com.mapbox.mapboxsdk:mapbox-java-services:1.3.1@jar') {
        transitive = true
    }
```
We are aware of the increase and will work on lowering the count in upcoming releases. For now, I can advice you running proguard which strips out unused code. Going to close in favor of creating a ticket in [mapbox-java](https://github.com/mapbox/mapbox-java/issues).

**Comment by ntoskrnl** [comment]
Thank you!
