### ISSUE TITLE
Programmatically changing the visible map region deselects selected annotation

### ISSUE THREAD

**Issue by danielamitay** [mapbox/mapbox-gl-native#6483]
**Platform:** iOS
**Mapbox SDK version:** v3.3.4

### Steps to trigger behavior

 1. Have annotations on screen, with callouts supported
 2. Tap on an annotation, `-mapView:didSelectAnnotationView:` will be called
 3. Programmatically center the map on the selected annotation

### Expected behavior

You should be able to move the map around (at a minimum programmatically, but even user interaction) while an annotation is selected, and it should remain selected. This is also how `MKMapView` works, you can select an annotation and programmatically center/move the map, and it will remain active. Even user map moves allows the annotation to remain active unless programmatically deselected or a user tap, or another annotation being selected.

### Actual behavior

The annotation will be immediately deselected.

`MGLMapView` is deselecting the annotation here: https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/src/MGLMapView.mm#L4432-L4437

**Comment by danielamitay** [comment]
I believe mapbox-gl-js supports this use case of "select an annotation -> center it on screen"

**Comment by boundsj** [comment]
Thanks @danielamitay. This is tracked in https://github.com/mapbox/mapbox-gl-native/issues/3154 and a related issue is https://github.com/mapbox/mapbox-gl-native/issues/6284.

**Comment by danielamitaysc** [comment]
Ah sorry my search-fu isn't what it used to be! :(

**Comment by danielamitay** [comment]
Ah sorry my search-fu isn't what it used to be! :(
