### ISSUE TITLE
Unable to symbolicate crashes from Mapbox 3.3.3 dynamic framework release

### ISSUE THREAD

**Issue by erichoracek** [mapbox/mapbox-gl-native#6502]
When downloading the "mapbox-ios-sdk-3.3.3-dynamic.zip" release attachment on [Mapbox 3.3.3](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.3.3), the UUIDs from the dSYM do not match the UUIDs from the dynamic framework:

```
$ dwarfdump --uuid mapbox-ios-sdk-3/dynamic/Mapbox.framework/mapbox
UUID: FF7BEA5C-FCB4-3035-A1DF-83707E41ACF1 (i386) mapbox-ios-sdk-3/dynamic/Mapbox.framework/mapbox
UUID: 1E2D5B1D-12AB-3286-8A4D-58B2D417B31C (x86_64) mapbox-ios-sdk-3/dynamic/Mapbox.framework/mapbox
UUID: 71EB9FB8-C32E-3C21-9684-CE53AAAFCB95 (armv7) mapbox-ios-sdk-3/dynamic/Mapbox.framework/mapbox
UUID: 85CF2FD7-622D-3201-90CE-22C24825C0C1 (arm64) mapbox-ios-sdk-3/dynamic/Mapbox.framework/mapbox
```

```
dwarfdump --uuid mapbox-ios-sdk-3/dynamic/Mapbox.framework.dSYM/ 
UUID: E7CE30F1-7197-3155-9A0A-D384EA79502E (armv7) mapbox-ios-sdk-3/dynamic/Mapbox.framework.dSYM/Contents/Resources/DWARF/Mapbox
UUID: 8CADAD54-2FA2-31E7-B73C-81EFC3B55F7D (arm64) mapbox-ios-sdk-3/dynamic/Mapbox.framework.dSYM/Contents/Resources/DWARF/Mapbox
```

I've looked through the other release attachments on 3.3.3, and I'm unable to find any dSYM with the `85CF2FD7-622D-3201-90CE-22C24825C0C1`/`71EB9FB8-C32E-3C21-9684-CE53AAAFCB95` UUIDs.

Unfortunately, because of this, we're unable to report ~7 unique crashes that we're receiving in 3.3.3, since we can't symbolicate them.

**Comment by rmnblm** [comment]
Do you get the same error with the [symbols version](https://github.com/mapbox/mapbox-gl-native/releases/download/ios-v3.3.3/mapbox-ios-sdk-3.3.3-symbols-dynamic.zip)? If yes, try the [newer version](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.4.0-alpha.4) of Mapbox. Do you still get the same error?

**Comment by erichoracek** [comment]
I haven't checked with other versions—since we already have a fair amount of crashes with the 3.3.3 dynamic framework, we were hoping that the missing symbols could somehow be recovered so we're able to make sure the crashes are fixed before we next update Mapbox.

If this isn't possible, this issue can be closed and we'll attempt to resubmit new (hopefully symbolicated) crashes if they occur pin 3.4.0.

**Comment by friedbunny** [comment]
Thanks for reporting this, @erichoracek. It does indeed appear that the dSYMs included in the dynamic, non-symbol releases aren’t viable for symbolication. We’ll have to go through and take a look at the dSYM generation process...

(The UUIDs do match in the `-symbols` versions and those can and have been used for symbolication.)

Unfortunately this means that your Mapbox-related crashes probably can’t be fully symbolicated. 🙇

**Comment by friedbunny** [comment]
My initial guess was that this was caused by [our `strip -Sx` invocation](https://github.com/mapbox/mapbox-gl-native/blob/9a41b8abaf75a344bd86d55878ee87179eb63d95/platform/ios/scripts/package.sh#L182-L190), but tests show this doesn’t modify UUIDs. Instead, this seems to be because `make iframework SYMBOLS=NO` doesn’t generate a dSYM at all.

The dSYM that’s included with plain `-dynamic` builds is actually from the `-symbols-dynamic` build:

```
dwarfdump -u --arch armv7 mapbox-ios-sdk-3.3.3-dynamic/dynamic/Mapbox.framework.dSYM/Contents/Resources/DWARF/Mapbox 
UUID: E7CE30F1-7197-3155-9A0A-D384EA79502E (armv7) mapbox-ios-sdk-3.3.3-dynamic/dynamic/Mapbox.framework.dSYM/Contents/Resources/DWARF/Mapbox

dwarfdump -u --arch armv7 mapbox-ios-sdk-3.3.3-symbols-dynamic/dynamic/Mapbox.framework.dSYM/Contents/Resources/DWARF/Mapbox 
UUID: E7CE30F1-7197-3155-9A0A-D384EA79502E (armv7) mapbox-ios-sdk-3.3.3-symbols-dynamic/dynamic/Mapbox.framework.dSYM/Contents/Resources/DWARF/Mapbox
```
