### ISSUE TITLE
How to select POI point from own style map on mobile?

### ISSUE THREAD

**Issue by infinitysky** [mapbox/mapbox-gl-native#6509]
Hi all,
I am trying to use Mapbox mobile SDK to shows my information.
I just confused for How to select a POI on map,

Here is my problem:
I am using my style map, which is had combined my data inside. I wish to show the detail of the POI point by touch the point.
I have implemented this feature on my website version.

![image](https://cloud.githubusercontent.com/assets/1997572/18939429/95ef0e6a-8643-11e6-9b44-eb2786ea399d.png)

Now, I want to apply this feature on my mobile version.

![image](https://cloud.githubusercontent.com/assets/1997572/18939460/e3f5c6a8-8643-11e6-8e47-c03389d99198.png)

and I have no idea that how to select a POI point from the map....

anyone can help me to workout It, please???

Also, my POI points are over 600000+. It is not possible to query a GEOJSON from a server. Especially, I have got so many points, and the GEOJSON file is extremely large than any other project (800MB). I can not make the POI like a simple "Annotation".

I am working with swift now..

**Comment by jfirebaugh** [comment]
Hi @infinitysky. This issue tracker is for reporting bugs and feature requests. For support question, please use https://www.mapbox.com/contact/. Thanks!
