### ISSUE TITLE
[android] Reference sprites from GL Markers API

### ISSUE THREAD

**Issue by sddamico** [mapbox/mapbox-gl-native#6517]
I was examining the `Icon` API for markers and there did not seem to be a way to have a GL marker reference a sprite for its icon.

It'd be great to have this functionality to cut down on the assets that I need to package with my application.

**Comment by tobrun** [comment]
We currently do not expose this functionality, but this would make a more complete api. For future releases we are thinking to refactor a big part of this and this is an option that should be included.

Just out of curiosity: have you tried working out your use case with runtime styling? I remember you playing with different markers for different zoomlevels (filters from runtime styling are ideal for this). Showing many markers and having clustering are also benefits from using runtime styling. LMK if you need any guidance on this.

**Comment by sddamico** [comment]
@tobrun Yeah, the goal in the long run is to display these markers with runtime styling so the sprites will be easily accessible. The issue with doing that, currently, is the need for querying features, which is still in beta. Once 4.2 ships, we'll be moving over to that style implementation as it'll better mirror what our team is doing [on the js side](http://chairnerd.seatgeek.com/vector-venue-maps-using-mapboxgl/)

**Comment by tobrun** [comment]
This functionality is possible with symbol layer and the plan is to deprecate Marker annotation in favor of the SymbolManager plugin in https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-annotation. Closing as not actionable.
