### ISSUE TITLE
possibly generate types.cpp automatically

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#6519]
The `enum` values in `src/mbgl/style/types.cpp` predate runtime styling, but could be auto-generated from the style spec much like the platform SDK code is. This isn't high-priority or a release blocker, though. 

/cc @jfirebaugh @1ec5

**Comment by jfirebaugh** [comment]
These change infrequently enough that it's not a big deal that they're not auto-generated. If we end up adding lots of enumeration values in the future, we can revisit this.
