### ISSUE TITLE
[Android] Added layers appear above markers

### ISSUE THREAD

**Issue by lyptt** [mapbox/mapbox-gl-native#6528]
**Platform:** Android
**Mapbox SDK version:** 4.2.0-beta3

Using the same code from #6240, when adding the layer I'm observing that the layer appears above the layers containing the markers. This occurs even if my custom layer is added to the map before the annotations are added to the map.

Additionally, I can't seem to find a way of sending the layer to the back, or below the annotation layers.

Is there a way of achieving this?

**Comment by tobrun** [comment]
@lyptt 

At this moment there is only one way to manipulate the layer ordering. 
You need to use 2 param method of addLayer:

```java
    @UiThread
    public void addLayer(@NonNull Layer layer, String before) {
        getMapView().getNativeMapView().addLayer(layer, before);
    }
```

With this method you add your line layer before another layer.


----


Are talking about GL based markers that are added with `View addMarker(MarkerOptions)`? If yes than you can position them with using the following id:

```cpp
const std::string AnnotationManager::PointLayerID = "com.mapbox.annotations.points";
```

If no, are talking these added through a GeoJSON source? You should be able to use the corresponding layer to position you line layer behind that one.

LMK if this resolved your issue, closing as answered.

**Comment by chris-praxis** [comment]
This helped me draw my poly-line layer below markers on iOS; I just want to point out that this is not specific to Android:
```map.addLayer(layerData, "com.mapbox.annotations.points");```
