### ISSUE TITLE
JNI cleanup/refactor

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#6533]
We need to find a way to make our current `jni.cpp` implementation a bit more manageable. 
Using [jni.hpp](https://github.com/mapbox/jni.hpp) has given us a modern type safe wrapper c++14 approach to the jni but it doesn't help us manage the amount of configuration we currently need to do. We should look into structuring the content differently or approach the idea in a different way.

cc @mapbox/android

**Comment by jfirebaugh** [comment]
* Most of jni.cpp is using the [low-level wrappers](https://github.com/mapbox/jni.hpp#low-level-wrappers). Switching to the [high-level wrappers](https://github.com/mapbox/jni.hpp#high-level-wrappers) will cut down on a lot of boilerplate.
* Code in jni.cpp should be split out into individual files for each native type.
