### ISSUE TITLE
Updating sprite image is not reflected in currently rendered layers

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#6536]
In https://github.com/mapbox/mapbox-gl-native/pull/6375 an api is added to add and remove Sprite images.  While implementing the bindings for Android (https://github.com/mapbox/mapbox-gl-native/pull/6513) I noticed that updating a sprite doesn't affect anything visually.

**Initial situation**
- Add a sprite image
- Add a geojson source with a point
- Add a symbol layer with that source and `source-image` set to the sprite image identifier

_Sprite is displayed correctly,_

**Updating the sprite by adding a new image with the same identifier**
_Image is not updated_

As the size of the sprite cannot be changed, a log entry is shown, nothing more. This might be confusing for developers. See: https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/sprite/sprite_atlas.cpp#L132

**Update the sprite by first removing and then adding a sprite with the same identifier**
_Image is not updated_

In this case; no log entry is shown, nothing happens visually.

cc @tmpsantos

**Comment by jfirebaugh** [comment]
> Updating the sprite by adding a new image with the same identifier

I don't think we should allow this. If we want an update API, let's make it an explicit `updateImage` method.

**Comment by 1ec5** [comment]
Related: #6536.
