### ISSUE TITLE
Update to LOST 2.0

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#6537]
The Mapzen team has announced the availability of [LOST 2.0](https://mapzen.com/blog/open-source-location-services-with-lost/) with a number of improvements (Background location updates via PendingIntent, Geofencing API, Settings API, Location Availability, Permissions). Let's update our dependency to its latest version.

Related: https://github.com/mapbox/mapbox-gl-native/issues/6462.

/cc: @mapbox/android

**Comment by clydebarrow** [comment]
I have created pull request #6548 that updates LOST to 2.0, along with updates to the Android SDK.
