### ISSUE TITLE
Missing coordinates in MGLPolylineFeature

### ISSUE THREAD

**Issue by rmnblm** [mapbox/mapbox-gl-native#6538]
**Platform:** iOS 10, Swift 3
**Mapbox SDK version:** 3.4.0-alpha.4

I'm currently facing a problem with above solution: The function `mapView.visibleFeatures(in:)` correctly returns all features inside my touchable square. The problem is: there are some coordinates missing in the `MGLPolylineFeature` depending on the zoom level I'm currently at. See examples below:

**ZoomLevel between 12-13**

![line1](https://cloud.githubusercontent.com/assets/5942764/19006212/abd0ba14-875e-11e6-8d7c-f0a4b980bc21.gif)

```
<MGLPolylineFeature: 0x1740be1e0; count = 81; bounds = { sw = {47.1, 8.6}, ne = {47.1, 8.6}}>
```

**ZoomLevel between 13-14**

![line2](https://cloud.githubusercontent.com/assets/5942764/19006205/a7514418-875e-11e6-9139-f2ed211e628b.gif)

```
<MGLPolylineFeature: 0x1742b5480; count = 66; bounds = { sw = {47.1, 8.6}, ne = {47.1, 8.6}}>
```

Is this a bug or am I doing something wrong? 🙈

**Comment by 1ec5** [comment]
As noted in [the documentation](https://www.mapbox.com/ios-sdk/api/3.4.0-alpha.4/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)visibleFeaturesInRect:inStyleLayersWithIdentifiers:):

> Features come from tiled vector data or GeoJSON data that is converted to tiles internally, so feature geometries are clipped at tile boundaries and features may appear duplicated across tiles. For example, suppose the specified rectangle intersects with a road that spans the screen. The resulting array includes those parts of the road that lie within the map tiles covering the specified rectangle, even if the road extends into other tiles. The portion of the road within each map tile is included individually.

Unfortunately, this means that the returned feature can’t correspond to an entire annotation. You’ll have to do some custom logic to match the returned feature to the original annotation.
