### ISSUE TITLE
offline raster tiles only shown on some zoom levels

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-native#6547]
**Platform:** iPhone/iPad
**Mapbox SDK version:** master as of 132954b56340ff6d883a325c0f64ed7ce1aa3072

### Steps to trigger behavior

 1. create app with style consist of some raster (aerial) tiles and some vector tiles
 2. load tiles for offline with MGLOfflinePack
 3. go offline
 4. zoom in/out

### Expected behavior

Both raster and vector tiles should display across all zoom levels both online and offline.

### Actual behavior

When offline, the raster tiles flicker on/off when zooming in. Much more off than on. The vector tiles show nicely all the time.

When online, both the raster and vector tiles are shown when zooming. Good.

![out](https://cloud.githubusercontent.com/assets/445229/19017033/7c8645a2-882c-11e6-8ab0-87fd073e639d.gif)

**Comment by ANSB** [comment]
Do you have one area o more than one? Can you have a look at the message in your debugger to see if the app try to search for style?

**Comment by halset** [comment]
@ANSB I have around 500 offline packs for the current style. No logging message related to search for style.

**Comment by halset** [comment]
This bug was introduced by 41bbd4e4f7d66465433e370ca024ab0239fcace3. 0bd66d40ddf9e75f860fe18e7c80de9c840f48ac just before it was the last to have this working. This is just as the other tile related bug I reported in #6506.
