### ISSUE TITLE
overlaped offlines maps with different styles are confusing

### ISSUE THREAD

**Issue by ANSB** [mapbox/mapbox-gl-native#6550]
Platform: Android
Mapbox SDK version: com.mapbox.mapboxsdk:mapbox-android-sdk:4.1.1@aar

 1. download map with style number 1 and zoom min and max
 2. dowload map with style number 2 and zoom min and max which overlap the first Map
 3. Turn Wifi Off
 4. Have a look at the map

Seems to always use the style number 2 (so last used) and of course Lib is confused when you reach part of the map which don't belong to this style:
_W/com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request could not be executed: Unable to resolve host "api.mapbox.com": No address associated with hostname
E/mbgl: [Style]: Failed to load tile 14/6005/8922=>14 for source composite: Unable to resolve host "api.mapbox.com": No address associated with hostname_

Expected behavior: 
Would be nice to have the ability to activate or desactivate display of map. So:
1) save long the_new_id = offlineRegion.getID(); when download
2) loop over maps before displaying to activate the one you want. A "bit like that" (of course, it don't work!):

 ```
offlineManager = OfflineManager.getInstance(My_Map_Display.this);
        offlineManager.listOfflineRegions(new OfflineManager.ListOfflineRegionsCallback()
        {
            @Override
            public void onList(final OfflineRegion[] offlineRegions)
            {
                if (offlineRegions == null || offlineRegions.length == 0)
                {
                    
                } else
                {
                    for (OfflineRegion offlineRegion : offlineRegions)
                    {
                        long the_id = offlineRegion.getID();
                        if (the_id == the_id_I_want_to_activate)
                        {
                            offlineRegion.setDisplayState(OfflineRegion.STATE_ACTIVE);
                        }
                      else
                        {
                            offlineRegion.setDisplayState(OfflineRegion.STATE_INACTIVE);
                        }
                    }
                }
            }
        });
```
In that case, the display will show ONLY the activated Map. Using such a trick, it would be possible to have different part of the Map with different styles. Eg a Road map for traveling to a place and then a local Map of this place, with different style.

A detail: with the ability to activate of desactivate each map, this will also allow the display to accept only zoom in the range of the data.

**Comment by jfirebaugh** [comment]
Sorry, I can't understand what issue you are reporting here, or feature you are requesting. For documentation on offline see, https://www.mapbox.com/help/mobile-offline/.

**Comment by ANSB** [comment]
Try to answer this:
1) road from a town to the center of a second town using "street style"
2) view of the center of second town using "satellite style"
So you need to have two maps; one in street, second in satellites and the second overlap the first one.
So question: with the actual LIB how can you do that, all offline?
