### ISSUE TITLE
Display SDK version in action sheet title

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6551]
When the user taps the ℹ️ button in the corner of a map view, an action sheet appears with “Mapbox iOS SDK” in faint text in the title bar. Should this title indicate the SDK version? That would make it easier to diagnose issues in shipping applications, although it might be less aesthetically pleasing.

/cc @friedbunny

**Comment by friedbunny** [comment]
I’ve thought that this would be nice in the past, but I agree that it would be an unnecessary (if minor) aesthetic blemish in most cases.

It adds some complexity and overhead, but we could show the version if the attribution button is long pressed: https://github.com/mapbox/mapbox-gl-native/compare/fb-attribution-version-longpress

**Comment by incanus** [comment]
What about getting rid of the action sheet title and add a new first row with it instead, its action being to show the version? 

![one](https://cloud.githubusercontent.com/assets/17722/19050420/5964c9c6-8963-11e6-888b-2d8505a310c0.gif)

Discoverable, no major change in current appearance, and easy to direct folks to. 

We could also get fancier and advertise a bit to all developers and users if they happen to take a peek. 

![two](https://cloud.githubusercontent.com/assets/17722/19050440/719af466-8963-11e6-86c2-79b4c67a04bb.gif)

(Imaging this as an attributed, clickable link, or even a custom view, maybe showing multiple styles in a small four-square pattern?)

**Comment by friedbunny** [comment]
Whether or not discoverability is a major concern depends on what problem we’re trying to fix:

### A. Mapbox developers diagnosing issues in apps we don’t control.

This is something I do somewhat frequently. Usually it means downloading the app through iTunes and spelunking the package. Discoverability: not important.

### B. Developers figuring out which version of our SDK they’re using.

Developers should already know? Not sure that this is a common use case. Discoverability: somewhat important.

### C. Users of apps reporting issues.

We don’t really want this happening — developers should be taking reports. Discoverability: not important.

**Comment by friedbunny** [comment]
Let’s consider extended silence here as a consensus “meh” vote against this feature.

**Comment by andrewcar** [comment]
Why did you reopen it? Was it A, B, or C?

**Comment by 1ec5** [comment]
I suspect it’s mostly A, since it’s a little more difficult to download .ipas through iTunes these days.

> it would be an unnecessary (if minor) aesthetic blemish in most cases

I can think of two ways to make the version aesthetically unobtrusive while remaining relatively convenient to Mapboxers trying to determine the map SDK version, at least compared to downloading an .ipa through iTunes 12.7:

* Add a `mapSdkVersion` query parameter to the URL of the © Mapbox or Improve This Map action buttons.
* Omit the version from the action sheet title the _first_ time the action sheet appears but include the version on each subsequent appearance.
