### ISSUE TITLE
MapBox 4.1.1 black screen in api 21

### ISSUE THREAD

**Issue by EzlyJohnnie** [mapbox/mapbox-gl-native#6552]
Update:
I tried on some other devices with the same code, it just works fine.
But not working on samsung note 3 (need to check later) api level 21.

I do set the accessToken. and called this in Application class
`MapboxAccountManager.start(this, Config.MAPBOX_ACCESS_TOKEN);`

Gradle: 
```
compileSdkVersion 23
    buildToolsVersion "23.0.3"
    defaultConfig {
        applicationId "com.xxx.xxx"
        minSdkVersion 19
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

repositories {
    mavenCentral()
}

dependencies {
    ......
    //Mapbox
    compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:4.1.1@aar'){
        transitive=true
    }

}
```

xml:
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:mapbox="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        mapbox:style_url="@string/style_mapbox_streets"
        mapbox:center_latitude="-36.846407"
        mapbox:center_longitude="174.765931"
        mapbox:zoom="12"/>

</LinearLayout>
```

Fragment:
```
    @BindView(R.id.mapview) MapView mapView;
    private MapboxMap map;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View root = inflater.inflate(R.layout.fragment_map_main, container, false);
        ButterKnife.bind(this, root);
        mapView.onCreate(savedInstanceState);
        return root;
    }

    @Override
    public void onResume() {
        super.onResume();
        mapView.onResume();
    }

    @Override
    public void onPause() {
        super.onPause();
        mapView.onPause();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        mapView.onDestroy();
    }

    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mapView.onSaveInstanceState(outState);
    }
```

Can someone help please.
Thanks so much

**Comment by tobrun** [comment]
@EzlyJohnnie thank you for reaching out and reporting your problem. Could you paste your logcat output? That would make tracking down the issue a bit easier. I'm interested in the http logging part since the style seems to be not loading.

**Comment by EzlyJohnnie** [comment]
@tobrun Yes you are right...seems some connection error
Is there anything be wrongly set on that device?
here is the log:
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug E/MapboxEventManager: FlushTheEventsTask borked: javax.net.ssl.SSLHandshakeException: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Mon May 23 12:00:00 GMT+12:00 2016 (compared to Sun Feb 23 19:10:30 GMT+13:00 2014)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err: javax.net.ssl.SSLHandshakeException: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Mon May 23 12:00:00 GMT+12:00 2016 (compared to Sun Feb 23 19:10:30 GMT+13:00 2014)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:239)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at okhttp3.internal.io.RealConnection.establishProtocol(RealConnection.java:196)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:171)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:187)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:123)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:93)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:296)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:243)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at okhttp3.RealCall.execute(RealCall.java:57)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at com.mapbox.mapboxsdk.telemetry.MapboxEventManager$FlushTheEventsTask.doInBackground(MapboxEventManager.java:719)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at com.mapbox.mapboxsdk.telemetry.MapboxEventManager$FlushTheEventsTask.doInBackground(MapboxEventManager.java:595)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at java.lang.Thread.run(Thread.java:818)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err: Caused by: java.security.cert.CertificateException: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Mon May 23 12:00:00 GMT+12:00 2016 (compared to Sun Feb 23 19:10:30 GMT+13:00 2014)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:344)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:113)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:574)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:320)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err: 	... 21 more
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err: Caused by: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Mon May 23 12:00:00 GMT+12:00 2016 (compared to Sun Feb 23 19:10:30 GMT+13:00 2014)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at com.android.org.bouncycastle.jce.provider.RFC3280CertPathUtilities.processCertA(RFC3280CertPathUtilities.java:1492)
02-23 19:10:30.575 19676-19742/com.ezly.ezly_android.debug W/System.err:     at com.android.org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi.engineValidate(PKIXCertPathValidatorSpi.java:305)
02-23 19:10:30.585 19676-19742/com.ezly.ezly_android.debug W/System.err:     at com.sec.android.security.pkix.SecCertPathValidatorSpi.engineValidate(SecCertPathValidatorSpi.java:100)
02-23 19:10:30.585 19676-19742/com.ezly.ezly_android.debug W/System.err:     at java.security.cert.CertPathValidator.validate(CertPathValidator.java:191)
02-23 19:10:30.585 19676-19742/com.ezly.ezly_android.debug W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:331)
02-23 19:10:30.585 19676-19742/com.ezly.ezly_android.debug W/System.err: 	... 26 more
02-23 19:10:30.585 19676-19742/com.ezly.ezly_android.debug W/System.err: Caused by: java.security.cert.CertificateNotYetValidException: Certificate not valid until Mon May 23 12:00:00 GMT+12:00 2016 (compared to Sun Feb 23 19:10:30 GMT+13:00 2014)
02-23 19:10:30.585 19676-19742/com.ezly.ezly_android.debug W/System.err:     at com.android.org.conscrypt.OpenSSLX509Certificate.checkValidity(OpenSSLX509Certificate.java:230)
02-23 19:10:30.585 19676-19742/com.ezly.ezly_android.debug W/System.err:     at com.android.org.bouncycastle.jce.provider.RFC3280CertPathUtilities.processCertA(RFC3280CertPathUtilities.java:1483)
02-23 19:10:30.585 19676-19742/com.ezly.ezly_android.debug W/System.err: 	... 30 more
02-23 19:10:31.205 19676-19723/com.ezly.ezly_android.debug W/com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request could not be executed: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Sat Apr 18 12:00:00 GMT+12:00 2015 (compared to Sun Feb 23 19:10:31 GMT+13:00 2014)
02-23 19:10:31.205 19676-19676/com.ezly.ezly_android.debug E/mbgl: [Setup]: loading style failed: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Sat Apr 18 12:00:00 GMT+12:00 2015 (compared to Sun Feb 23 19:10:31 GMT+13:00 2014)
02-23 19:10:31.885 19676-19676/com.ezly.ezly_android.debug V/ActivityThread: updateVisibility : ActivityRecord{3f19cf49 token=android.os.BinderProxy@359a225 {com.ezly.ezly_android.debug/com.ezly.ezly_android.UI.MainActivity}} show : false
02-23 19:10:32.945 19676-19676/com.ezly.ezly_android.debug I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@359a225 time:4416253
02-23 19:10:32.965 19676-19723/com.ezly.ezly_android.debug W/com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request could not be executed: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Sat Apr 18 12:00:00 GMT+12:00 2015 (compared to Sun Feb 23 19:10:32 GMT+13:00 2014)
02-23 19:10:32.975 19676-19676/com.ezly.ezly_android.debug E/mbgl: [Setup]: loading style failed: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Sat Apr 18 12:00:00 GMT+12:00 2015 (compared to Sun Feb 23 19:10:32 GMT+13:00 2014)
02-23 19:10:37.125 19676-19723/com.ezly.ezly_android.debug W/com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request could not be executed: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Sat Apr 18 12:00:00 GMT+12:00 2015 (compared to Sun Feb 23 19:10:37 GMT+13:00 2014)
02-23 19:10:37.125 19676-19676/com.ezly.ezly_android.debug E/mbgl: [Setup]: loading style failed: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Sat Apr 18 12:00:00 GMT+12:00 2015 (compared to Sun Feb 23 19:10:37 GMT+13:00 2014)
02-23 19:10:39.435 19676-20080/com.ezly.ezly_android.debug D/MapboxEventManager: No events in the queue to send so returning.
02-23 19:10:45.275 19676-19723/com.ezly.ezly_android.debug W/com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request could not be executed: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Sat Apr 18 12:00:00 GMT+12:00 2015 (compared to Sun Feb 23 19:10:45 GMT+13:00 2014)
02-23 19:10:45.275 19676-19676/com.ezly.ezly_android.debug E/mbgl: [Setup]: loading style failed: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Sat Apr 18 12:00:00 GMT+12:00 2015 (compared to Sun Feb 23 19:10:45 GMT+13:00 2014)
02-23 19:10:51.235 19676-19676/com.ezly.ezly_android.debug I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@359a225 time:4434549
02-23 19:10:51.365 19676-19723/com.ezly.ezly_android.debug W/com.mapbox.mapboxsdk.http.HTTPRequest: [HTTP] Request could not be executed: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Sat Apr 18 12:00:00 GMT+12:00 2015 (compared to Sun Feb 23 19:10:51 GMT+13:00 2014)
02-23 19:10:51.365 19676-19676/com.ezly.ezly_android.debug E/mbgl: [Setup]: loading style failed: com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Sat Apr 18 12:00:00 GMT+12:00 2015 (compared to Sun Feb 23 19:10:51 GMT+13:00 2014)

**Comment by tobrun** [comment]
@EzlyJohnnie Could you validate if your time / date is correctly set on that device?

**Comment by EzlyJohnnie** [comment]
@tobrun you are genius!!!
I don't even notice that.
it works perfectly, I will close this issue.
Thanks a lot.

**Comment by cvance** [comment]
Is there a suggested fix or workaround for this? Is the only solution to direct users who don't have "Automatic Date/Time" enabled to enable it, [using this](http://stackoverflow.com/questions/23075446/how-to-check-automatic-date-and-time-is-enabled-or-not)? Is there a way to tell that map didn't load correctly?

**Comment by tobrun** [comment]
@cvance you can verify if a style failed to load with an MapView.OnMapChangeListener and checking for `MapView.DID_FAIL_LOADING_MAP`

**Comment by cvance** [comment]
Awesome! Is there somewhere we can make this more visible? We ran into the issue for some users but always chalked it up to internet connection or a specific device issue.

**Comment by ahmadezoji** [comment]
> @EzlyJohnnie Could you validate if your time / date is correctly set on that device?

thanks
