### ISSUE TITLE
Style sprite image not cached

### ISSUE THREAD

**Issue by marius-serban** [mapbox/mapbox-gl-native#6560]
**Platform:**
iOS
**Mapbox SDK version:**
3.3.4
### Steps to trigger behavior
1. Instantiate and display a MGLMapView
2. Use a tool to inspect network requests traffic
3. Observe a GET request going out to `/styles/v1/[...]/[...]/sprite@2x.png?access_token=[...]`
4. Repeat steps 1-3, and observe the request going out again
5. Observe that the sprite image in the response is the same every time, and it does not depend on the map style
### Expected behavior

The image should be cached
### Actual behavior

There is no cache control set on the response. The same 1024x1024 image is fetched over the network every time the map view is created causing ~200KB of unnecessary network traffic.
### Request headers:

```
GET /styles/v1/[...]/[...]/sprite@2x.png?access_token=[...]&events=true HTTP/1.1
Host: api.mapbox.com
Connection: keep-alive
Accept-Encoding: gzip, deflate
User-Agent: [...]/1.0 Mapbox/3.3.4 MapboxGL/3.3.4 (c64a0c24) iOS/10.1.0 (arm)
Accept-Language: en-gb
Accept: */*
Pragma: no-cache
Cache-Control: no-cache
```
### Response headers:

```
HTTP/1.1 200 OK
Content-Type    image/png
Content-Length    225091
Connection    keep-alive
Date    Mon, 03 Oct 2016 12:38:43 GMT
X-Powered-By    Express
Access-Control-Allow-Origin    *
Cache-Control    max-age=900
X-Cache    Miss from cloudfront
Via    1.1 bf16c73ec621c935d5b8f6c85097580f.cloudfront.net (CloudFront)
X-Amz-Cf-Id    dQuSvbtn8BnAzOALctwP8UsnG3LQgn80j0-2kzyzwOUoR-PfpYeSsg==
Expires    0
Cache-Control    no-cache
```

**Comment by jfirebaugh** [comment]
@marius-serban Your example request headers include `Pragma: no-cache` and `Cache-Control: no-cache`, and your example request headers include both `Cache-Control: max-age=900` and `Cache-Control: no-cache`. Mapbox GL does make requests with either `Pragma: no-cache` and `Cache-Control: no-cache`, and our server API sends responses with `Cache-Control: max-age=900`, not `Cache-Control: no-cache`. I suspect that whatever tool you are using to perform network capture is modifying the headers so as to prevent caching.

**Comment by marius-serban** [comment]
That may be possible, the capture was done by one of our testers. The tool was Charles Proxy which I just noticed it has a "No caching tool" which might have been turned on at the time of the capture.

Thanks!
