### ISSUE TITLE
It's too easy to rotate the map

### ISSUE THREAD

**Issue by mayagao** [mapbox/mapbox-gl-native#6562]
When I pinch the screen to zoom in and out of the map, it's too easy to trigger map rotation, which is usually not the intended behavior. This is especially true when I zoom in and out very quickly. Is there anyway we can make it less sensitive? Maybe delay sending the pinch event https://developer.apple.com/reference/uikit/uigesturerecognizer/1624234-delaystouchesbegan or only start rotating when it's more than x degrees?

cc @1ec5 @pveugen

**Comment by incanus** [comment]
We could listen to the pinch + rotate combination and set a timer in the pinch recognizer. If the rotate recognizer is not _also_ recognized in, say, one full second, disable the rotate recognizer until the pinch is complete. 

This will allow folks who do immediately pinch + rotate to freely do so in combination.

**Comment by incanus** [comment]
Or, as @mayagao suggests, only recognize rotate more than x degrees if the pinch is also current in progress.

**Comment by friedbunny** [comment]
My personal perception is that Apple Maps has a slightly higher threshold for engaging rotation during pinches — perhaps ~3-5 degrees. [We don’t have any threshold](https://github.com/mapbox/mapbox-gl-native/blob/280fd8c28ed670418954e0a6e2f26292419103d6/platform/ios/src/MGLMapView.mm#L1312), currently.

I would not be in favor of ignoring rotation during pinch zooms — this is Google’s behavior and I’m often frustrated by not being able to transition into a rotation while zooming.

**Comment by clydebarrow** [comment]
The Android implementation has the opposite problem - rotations are quite hard to trigger.

**Comment by milo-trujillo** [comment]
I am seeing this behavior on iOS *and* Android: users frequently rotate the map by accident while zooming in and out. It would be great if we could add a detection threshold for rotations during pinches, or even make that threshold configurable through the API. If the API is configurable then the developer can choose whether to keep the Google Maps "rotate while zoom" behavior or not.

**Comment by Petrulak** [comment]
@friedbunny are there any plans to increase rotation threshold in Android SDK ? Or is it possible to disable  map rotation at all ? Zooming in/out with one hand is almost impossible without rotating the map. I have to use 110 % of my "mental capabilities" to not rotate the map and i am not focusing on the data in the map at all.  It would be nice to have some consistency with Google Maps since 95% of app out there are using them and user are familiar with certain behavior. It is quite annoying for me that i am always rotating the map while zooming with one hand and i am tilting the map while zooming with 2 fingers.
We are using `com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.2@aar`
Thank You :)

**Comment by percula** [comment]
I would also like the ability to increase the rotation threshold and/or the option to disable rotation while pinch-zooming.

**Comment by andrewharvey** [comment]
I'm also seeing this on Android too. Zooming in a few times and my map is upside down from the rotations.

**Comment by LukasPaczos** [comment]
@andrewharvey [new gestures implementation](https://github.com/mapbox/mapbox-gl-native/pull/11221) for Android just landed on `master`. Please feel free to retest with `6.0.0-SNAPSHOT` or upcoming `6.0.0-beta.3` and let us know whether that's still an issue for you.

**Comment by jmkiley** [comment]
Addressed in #15562 

Please comment or reopen if this doesn't seem to be resolved.
