### ISSUE TITLE
Only Street style Offline

### ISSUE THREAD

**Issue by ANSB** [mapbox/mapbox-gl-native#6563]
Platform: Android
Mapbox SDK version: com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0-beta.3@aar
But other Lib have same problem.

Offline works like a charm, but ONLY with streetmaps. 

Here is what I notice and why I think we are fooled by the cache:

My app need to download map about accidents. So depending on the accident, I need a different zoom range an a different style. Eg outdoor for forest fire, satelites for structural fire and so on.

I init the Lib at App level, then get data from a web server. I get zoom range and the Mapbox style URL. I perform a Log.i and see the URL is OK.
As I want to work offline, I do: 
```
 OfflineTilePyramidRegionDefinition definition = new OfflineTilePyramidRegionDefinition(
                the_mapbox_style,
                latLngBounds,
                the_mapbox_zoom_min,
                the_mapbox_zoom_max,
                (Init_Carte.this).getResources().getDisplayMetrics().density);
```
then download the map. Download seems to be OK (no error and time seems to be OK according to the size, % display and so on)

At the end, two cases:
Case 1:  I cut the Wifi BEFORE displaying the Map. In that case, if style is Street, I get the Map and it's OK. But If the download was made using Outdoor or other style, map stay black.
Case 2: I start to display, see the map, cut the Wifi and continue using the map. In that case I can believe it's OK. But not. The map is always in street style.

Notice than at display, I don't set the style. Because in real offline it's not possible as style is set using URL.
Each time I had the correct map (outdoor, satelites...) in fact I was online.

**Comment by jfirebaugh** [comment]
Offline regions are tied to a specific style. If you want to use multiple styles offline, you need to create a region for each one. (Note that internally, this will share tiles and other resources between the regions where possible.)

**Comment by ANSB** [comment]
If yours areas are overlapping (which is my case) the Lib is confused. Also, as a map is "earth", you will in ALL cases being able to overlap: if I want New York in satelites and Moscou in Street, I can of course open the map and scroll from New York to Moscou.
As the lib you let dev download areas in different style, this create problem while displaying as the display is done according to GPS coord and NOT according to the pack of data from the area.

The solution would be to consider each area as "pack of files from different server": each folder is a "server" than you can switch ON or OFF. In that case it would be possible to download area in one style, another area in another style even if they overlap. Then switch ON the one we want to display. 
Think it must be a major change in the lib.

**Comment by jfirebaugh** [comment]
The map renders one style at a time -- that's a fundamental constraint. However, you can switch styles at any time. See https://www.mapbox.com/android-sdk/api/4.2.0-beta.3/com/mapbox/mapboxsdk/maps/MapView.html#setStyleUrl-java.lang.String-

**Comment by ANSB** [comment]
Hmmm... But setStyleUrl() is an on line feature. And examples about changing style use "mapboxMap.setStyleUrl(Style.LIGHT);"
As there is void setStyle(String style) this means we can use this call for offline but only with "bundled style". That's it?

**Comment by jfirebaugh** [comment]
No, you can pass any style URL that you've previously created an offline region with.

**Comment by ANSB** [comment]
OK, get it! Would be nice to have smalls examples in which the download part of the offline system is in one activiy and the display on another. 
Thanks for your help!
