### ISSUE TITLE
set a background color 

### ISSUE THREAD

**Issue by fauger** [mapbox/mapbox-gl-native#6575]
Hello,

Is there a way to set a background color when no style is loaded. It's currently black.

I see you use a SurfaceView in your MapView:
 SurfaceView surfaceView = (SurfaceView) view.findViewById(R.id.surfaceView);

- Setting a background color goes on top of the map when the style is loaded.
- I tried to make it "PixelFormat.TRANSLUCENT" but it's not working either.

The last thing would be to override the surfaceView (and the ondraw). or maybe i miss something ?

Thanks

Platform : Android
mapbox version : 4.2.0

**Comment by fauger** [comment]
I also tried 

<com.mapbox.mapboxsdk.maps.MapView
            android:background="@color/map_background"

not working, still black color.

**Comment by tobrun** [comment]
@fauger thank you for reaching out, Ideally the black background would be transparent. We are tracking this feature in https://github.com/mapbox/mapbox-gl-native/issues/3040. iOS has it implemented in https://github.com/mapbox/mapbox-gl-native/issues/3038#issuecomment-158555239. Closing as a duplicate.

**Comment by fauger** [comment]
Thanks @tobrun for your answer. 
Meantime i have found another way by overriding the config.cleanColor directly in  painter.cpp.

But your approach seems much better. I hope you will fix it quickly

` {
        MBGL_DEBUG_GROUP("clear");
        config.stencilFunc.reset();
        config.stencilTest = GL_TRUE;
        config.stencilMask = 0xFF;
        config.depthTest = GL_FALSE;
        config.depthMask = GL_TRUE;
        config.colorMask = { GL_TRUE, GL_TRUE, GL_TRUE, GL_TRUE };

        if (isOverdraw()) {
            config.blend = GL_TRUE;
            config.blendFunc = { GL_CONSTANT_COLOR, GL_ONE };
            const float overdraw = 1.0f / 8.0f;
            config.blendColor = { overdraw, overdraw, overdraw, 0.0f };
            config.clearColor = Color::black();
        } else {
            config.clearColor = background;
        }
        config.clearStencil = 0;
        config.clearDepth = 1;
        MBGL_CHECK_ERROR(glClear(GL_COLOR_BUFFER_BIT | GL_STENCIL_BUFFER_BIT | GL_DEPTH_BUFFER_BIT));
    }
`
