### ISSUE TITLE
Tilting the camera

### ISSUE THREAD

**Issue by maciekish** [mapbox/mapbox-gl-native#658]
Hi,
will mapbox-gl support tilting the camera to provide turn-by-turn navigation in "3d" like Waze for example?

Thanks
Maciej

**Comment by maciekish** [comment]
Hi, any news on this please? We are trying to figure out a time plan for migrating from mapbox-ios to mapbox-gl-native.

**Comment by incanus** [comment]
No work on this in the current development cycle. We have some solid foundations for it on the JS side in https://github.com/mapbox/mapbox-gl-js/pull/1049 though.

**Comment by incanus** [comment]
Canonical spot for this is now https://github.com/mapbox/mapbox-gl-native/issues/1140.
