### ISSUE TITLE
Use std::vector for MGLMultiPoint coordinate storage

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6580]
MGLMultiPoint represents its coordinates internally as a C array of `CLLocationCoordinate2D` instances. This was fine at first, because the coordinates were immutable once MGLMultiPoint was created. Making the coordinates mutable (#6565) is forcing us to reckon with manual C memory management. Any errors there could potentially turn into security vulnerabilities.

We should convert the internal `_coordinates` array into an `std::vector<CLLocationCoordinate2D>` and let that object handle heap allocations for us. The public `coordinates` property would be implemented as `_coordinates.data()`, and `pointCount` as `_coordinates.size()`. The upshot is that the `memcpy()` grunt work in #6565 could be replaced with nothing more than `std::vector::reserve()` and [`std::copy_backward()`](http://www.cplusplus.com/reference/algorithm/copy_backward/).

/cc @incanus @boundsj @alulsh

**Comment by 1ec5** [comment]
Putting this on the v3.4.0 milestone. #6565 and #6583 only increase the risk of making an off-by-one error that can’t be detected by unit tests yet could lead to security vulnerabilities.

**Comment by incanus** [comment]
Re: being on the milestone, the original feature in https://github.com/mapbox/mapbox-gl-native/pull/6565 was driven by a customer request and is "gravy" of a sort (mmmmm) beyond the focus on 3.4.0, which is runtime styling. 

Maybe consider this a loose milestone issue that can be punted on? We can always tighten things up in a point release. 

/cc @boundsj

**Comment by 1ec5** [comment]
Even if we punt on #6583, I think we should keep this refactoring on the milestone. It’s small and necessary given that we have no tests of this functionality. (Or we can add tests!) https://github.com/mapbox/mapbox-gl-native/pull/6565#discussion_r82091206 is illustrative of the murky waters we’re in right now.

**Comment by boundsj** [comment]
Adding `release blocker` tag due to the safety concerns raised here

**Comment by boundsj** [comment]
This was fixed in https://github.com/mapbox/mapbox-gl-native/pull/6890
