### ISSUE TITLE
setAppliedClasses sets wrong class

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#660]
I have a problem where using setAppliedClasses sets the 'wrong' class. It seems the classes are getting mixed up, as setting the 'wrong' class will then set the 'correct' class.

Restarting the app can cause the order of classes to fluctuate randomly too.

Has anyone tested this function recently?

**Comment by ljbade** [comment]
This still seems to be a problem. Satellite labels + contours style shows only labels, no contours. Labels only shows nothing.

Outdoor day/night works until I also enable satellite class switching. I think it is related to changing styles.

**Comment by ljbade** [comment]
@jfirebaugh Found this ticket I had created ages ago.

**Comment by jfirebaugh** [comment]
Can you provide a set of steps to replicate this please?

**Comment by jfirebaugh** [comment]
Based on #1744 it seems setting the wrong class is no longer a problem, and we're down to a repaint issue.
