### ISSUE TITLE
MGLLocationManagerRegionIdentifier.fence.center catches kCLErrorRegionMonitoringFailure

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#6602]
If an app maxes out its [20 available monitoring regions](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/LocationAwarenessPG/RegionMonitoring/RegionMonitoring.html#//apple_ref/doc/uid/TP40009497-CH9-SW2), it appears that our lone region,`MGLLocationManagerRegionIdentifier.fence.center`, can fail to initialize with [`kCLErrorRegionMonitoringFailure`](https://developer.apple.com/reference/corelocation/clerror/kclerrorregionmonitoringfailure?language=objc) (also known as: `Error Domain=kCLErrorDomain Code=5`).

When we catch this error, it would be prudent to temporarily(?) stop trying to drop our geofence.

/cc @boundsj

**Comment by boundsj** [comment]
Closing here to track in https://github.com/mapbox/mapbox-events-ios
