### ISSUE TITLE
z-fighting on layers with overlapping polygons

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-native#6604]
**Platform:** Android, iOS, macOS
**Mapbox SDK version:** 4.2.0-beta.3 on Android and iOS v3.4.0-alpha.5
### Steps to trigger behavior
1. Ensure your style contains a fill layer with some transparency at least one incidence of overlapping polygons.
2. Bring overlapping polygons into view.
3. Tilt the map. 
### Expected behavior

Area of overlap between polygons should be less transparent than non-overlapping areas. 
### Actual behavior

Area of overlap flickers as the map is moved and evidence of [z-fighting](https://en.wikipedia.org/wiki/Z-fighting) is visible (see screenshots below). 

I went ahead and created some overlapping polygons in the dataset editor and added them to the Mapbox Light style (html embed page [here](https://api.mapbox.com/styles/v1/danswick/citnij4yl005r2ipa2jhoybjm.html?fresh=true&title=true&access_token=pk.eyJ1IjoiZGFuc3dpY2siLCJhIjoieUZiWmwtVSJ9.0cPQywdbPVmvHiHJ6NwdXA#18.28/39.74046/-104.98473/13.6/60)). z-fighting is not present on the web using Mapbox GL JS, but is visible on an Android device (Nexus 5x running Android 7) as well as on macOS: 

![image](https://cloud.githubusercontent.com/assets/2365503/19137792/651e67da-8b2b-11e6-9119-a648b63490ef.png)
_Android_

![image](https://cloud.githubusercontent.com/assets/2365503/19137809/778a8660-8b2b-11e6-8837-b9d3c5d8f00a.png)
_[macOS](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/macos)_

cc @1ec5 @alinapaz

**Comment by alinapaz** [comment]
@boundsj Clarifying we're seeing this issue with some custom styles as well.

**Comment by jfirebaugh** [comment]
@ansis @kkaefer Thoughts?

**Comment by foundryspatial-duncan** [comment]
This issue mentions iOS, Android, and OSX; I just wanted to add that it happens in Ubuntu as well. Here are some more screens:
![screen shot 2017-07-17 at 11 28 34 am](https://user-images.githubusercontent.com/13056053/28284225-1a72bd04-6ae5-11e7-8723-fb28e822d5db.png)
(Not tilted)

![screen shot 2017-07-17 at 11 28 23 am](https://user-images.githubusercontent.com/13056053/28284226-1a75a2da-6ae5-11e7-8bf4-1627466f3efe.png)
(Tilted)
![screen shot 2017-07-17 at 11 28 07 am](https://user-images.githubusercontent.com/13056053/28284227-1a7eb794-6ae5-11e7-9c84-a2769552984c.png)
(Tilted more)

**Comment by jfirebaugh** [comment]
Fixed by #9930 on master and #9942 for iOS 3.6.3 / Android 5.1.4.
