### ISSUE TITLE
Mapbox Studio vs GL-Native Style default camera 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#6607]
While looking into https://github.com/mapbox/mapbox-gl-native/issues/6129, I noticed different bearing behaviour in studio versus gl-native.

This is the initial default camera configuration I have done in studio:

<img width="1077" alt="screen shot 2016-10-06 at 09 23 16" src="https://cloud.githubusercontent.com/assets/2151639/19143818/8f9c9916-8ba6-11e6-89c6-91c4f02d2ab8.png">

This results in following behaviour on macOS (same as on Android):

<img width="514" alt="screen shot 2016-10-06 at 09 25 30" src="https://cloud.githubusercontent.com/assets/2151639/19143870/d693ad6e-8ba6-11e6-81e3-44d2a5841429.png">

Here is the some debugging information showing the data from studio matches:

<img width="440" alt="screen shot 2016-10-06 at 09 26 56" src="https://cloud.githubusercontent.com/assets/2151639/19143924/0c94abfc-8ba7-11e6-9f34-1ab9d71ca011.png">

**Comment by 1ec5** [comment]
This is on your #6608 branch, right? If so, see https://github.com/mapbox/mapbox-gl-native/pull/6608#discussion_r82233863 for a diagnosis and proposed fix.

**Comment by tobrun** [comment]
off course, that was obvious! thanks for 👀 ! will attempt fixing it up.

**Comment by tobrun** [comment]
Applied suggestions, and issue is resolved:

<img width="511" alt="screen shot 2016-10-07 at 11 04 03" src="https://cloud.githubusercontent.com/assets/2151639/19184504/ca1f3594-8c7d-11e6-8d0f-756441026a29.png">

Closing.
