### ISSUE TITLE
Is there a built-in way to display the point count on top of each cluster point?

### ISSUE THREAD

**Issue by rmnblm** [mapbox/mapbox-gl-native#6609]
**Platform:** iOS 10, Swift 3
**Mapbox SDK version:** 3.4.0-alpha.5

I couldn't find a way to display the point count on top of each cluster point so I built a more-or-less performant workaround. Did I miss something in the docs?

![cluster_point_count](https://cloud.githubusercontent.com/assets/5942764/19147002/523d6450-8bb6-11e6-8e0b-b7148262bb38.gif)

(For performance reasons I remove the UILabels on top of each cluster point when the MapView starts rendering, that's why the numbers disappear on zoom/dragging)

**Comment by jfirebaugh** [comment]
Yes, you can see the technique in [this GL JS example](https://www.mapbox.com/mapbox-gl-js/example/cluster/): add a symbol layer with text-field set to `"{point_count}"`.

**Comment by rmnblm** [comment]
Nice, thanks for clarification, works like a charm! 🙏
