### ISSUE TITLE
Add tapGesture to MGLMapView

### ISSUE THREAD

**Issue by iBinh** [mapbox/mapbox-gl-native#6610]
**Platform:** iOS
**Mapbox SDK version:**3.4.0 alpha 5

### Steps to trigger behavior

 1. Add tap gesture to mapBoxView

### Expected behavior
I want to handle my tap gesture with some UI changes
### Actual behavior
My tap gesture duplicate with gesture when click on annotation or double tap to quick zoom

**Comment by boundsj** [comment]
This is a duplicate of https://github.com/mapbox/mapbox-gl-native/issues/2278
