### ISSUE TITLE
macOS build is compiling mbgl-core twice

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#6615]
Once for the `mbgl-benchmark` target:

```
set -o pipefail && xcodebuild -derivedDataPath build/macos -configuration Debug -workspace platform/macos/macos.xcworkspace -scheme 'mbgl-benchmark' build | xcpretty
...
▸ Building mbgl/mbgl-core [Debug]
▸ Check Dependencies
▸ Compiling headless_view_cgl.cpp
▸ Compiling http_file_source.mm
...
```

And once for the `mbgl-test` target:

```
set -o pipefail && xcodebuild -derivedDataPath build/macos -configuration Debug -workspace platform/macos/macos.xcworkspace -scheme 'mbgl-test' build | xcpretty
...
▸ Building mbgl/mbgl-core [Debug]
▸ Check Dependencies
▸ Compiling headless_view_cgl.cpp
▸ Compiling http_file_source.mm
...
```

This is duplicate work that's making our build take longer than necessary.

**Comment by jfirebaugh** [comment]
@brunoabinader, since you recently added the benchmark step, could you please take a look at this?

**Comment by 1ec5** [comment]
The macOS workspace has a CI scheme. Can we copy whatever targets are in the mbgl-test and mbgl-benchmark schemes into the CI scheme? A subsequent step already tests the CI scheme using XCTest, so anything in the CI scheme will get built along with the SDK content.
