### ISSUE TITLE
Add method to set connectivity status manually

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-native#6617]
We've heard from a few SDK users that the recently added [ConnectivityManager check](https://github.com/mapbox/mapbox-gl-native/blob/2b05776f978c7759824bce1c4fc89d67cc00d332/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/MapboxAccountManager.java#L92-L102) in Android is too aggressive for devices using alternate methods to connect to a network. These users would benefit from a method that manually sets connectivity status. @tobrun recommended looking into https://developer.android.com/training/monitoring-device-state/manifest-receivers.html as a starting point. 

cc @zugaldia @ivovandongen

**Comment by zugaldia** [comment]
Picking this one up.
