### ISSUE TITLE
Run style-code-darwin on Bitrise

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6621]
The Bitrise bots for iOS and macOS should run `make style-code-darwin` and fail if `git diff` produces anything afterwards. This will ensure that a contributor who updates the mapbox-gl-style-spec version takes care to update the SDK and its documentation at the same time.

We could go a step further and automatically run `style-code-darwin` as part of `make xproj` and `make iproj`. However, I don’t think that’s necessary yet, because generating the runtime styling API is intended to be a fairly intentional action at the moment.

@ivovandongen, would something similar be useful for the Android SDK, given #6573?

/cc @friedbunny

**Comment by ivovandongen** [comment]
@1ec5 Since #6573 we run the style generation as a dependency for the native libraries. This ensures that developers will spot updates even before committing changes. I like the addition of a git diff check, but I focussed on spotting it before reaching the CI.

**Comment by jfirebaugh** [comment]
I don't think it's essential or even desirable to test this in CI. We don't necessarily want to update the generated code every time we update the submodule, and we're not likely to forget to do so when we do.
