### ISSUE TITLE
Crash if font name is empty in style JSON (i.e. bad URL to glyphs)

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#663]
I was helping @peterqliu with a crash in his style JSON that was caused by a bad URL to a glyph PBF file, eg.: `https://mapbox.s3.amazonaws.com/gl-glyphs-256//8448-8703.pbf`

Instead of `https://mapbox.s3.amazonaws.com/gl-glyphs-256/Open%20Sans%20Italic%2C%20Arial%20Unicode%20MS%20Regular/1024-1279.pbf`

I think the code is getting a 404 message then trying to interpret as a PBF file then crashing as well as smashing the stack at the same time.

We need to detect invalid PBF and either print a error log message, abort() or throw and exception. That was it is easy to find the error in the JSON and fix it.

@jfirebaugh what method of error reporting do you prefer for this?

**Comment by bleege** [comment]
@ljbade Still seeing any trouble with this?

**Comment by ljbade** [comment]
Haven't heard of this for a long time.
