### ISSUE TITLE
MGLGeoJSONSource should have a constructor without options:

### ISSUE THREAD

**Issue by rmnblm** [mapbox/mapbox-gl-native#6639]
Is there a reason that MGLGeoJSONSource hasn't a constructor without `options:`? 
Because I often find my self using the constructor without the need of providing options.

``` swift
MGLGeoJSONSource(identifier: "destinations", url: geoJSONURL, options: nil)
```

**Comment by boundsj** [comment]
Hi @rmnblm. `MGLGeoJSONSource` lost its option-less initializers in https://github.com/mapbox/mapbox-gl-native/pull/6588. It will gain another initializer in https://github.com/mapbox/mapbox-gl-native/issues/6302. We currently don't plan to add an option-less version of each designated initializer.  

Happily, in Swift, you can mitigate this in your app by extending `MGLGeoJSONSource` and adding a convenience initializer to wrap `MGLGeoJSONSource(identifier:URL:options:)`.
