### ISSUE TITLE
Invisible satellite tiles are downloaded even if opacity = 0

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#664]
Working with @peterqliu I discovered that if you have a style with invisible satellite tiles (e.g. you have a dynamic class you can turn on and off) the renderer still fetches the tiles even if opacity is 0.

JS renderer is smart enough to detect this and not download the tiles.

**Comment by bleege** [comment]
@ljbade Is this still an issue?

**Comment by ljbade** [comment]
I'm not sure we still have a style where you can turn on and off the satellite layer via a class change?

**Comment by jfirebaugh** [comment]
Fixed in 93725e062a3f506fc829c9da4649c9ce032b4067.
