### ISSUE TITLE
What editor to use when using this code?

### ISSUE THREAD

**Issue by spurdow** [mapbox/mapbox-gl-native#6644]
I just want to ask this question because im very curious on what youve been using all these times.
Is it ok to ask this question here? 

so sorry to ask this kind of question here. I hope you dont mind. 

thanks

**Comment by tobrun** [comment]
Depends on target platform and development environment. Most of these items are covered in the `README.md` & `CONTRIBUTING_*.md` files found in each respective sub directories of `/platform`. 

Thank you for reaching out, closing as non actionable.

**Comment by tobrun** [comment]
examples from macOS:
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/macos/README.md
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/macos/INSTALL.md
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/macos/DEVELOPING.md
