### ISSUE TITLE
Location View animation not synchronized with current locattion

### ISSUE THREAD

**Issue by tomlocks** [mapbox/mapbox-gl-native#6649]
**Platform: Android 6.0.1**
**Mapbox SDK version: 4.2.0-beta.3**

### Steps to trigger behavior
 1. Set location Tracking mode to: TRACKING_FOLLOW;
 2. MyBearingTrackingMode to: GPS.
 3. Set OnMyLocationChangeListener on map and add every location sample to map as a marker - something like:

                map.setOnMyLocationChangeListener(new MapboxMap.OnMyLocationChangeListener() {
                    @Override
                    public void onMyLocationChange(@Nullable Location location) {

                        map.addMarker(new MarkerOptions()
                                .position(new LatLng(location.getLatitude(), location.getLongitude()))
                                .title("Hello World!")
                                .snippet("Welcome to my marker."));

                    }
                });
               

4. Location view is not synchronized with the markers that indicate the new location. Moreover the cursor view does not end the animation at the current location(please see below).

### Actual behavior
![locationviewbug_1](https://cloud.githubusercontent.com/assets/9156700/19265337/17a32468-8fa5-11e6-86e2-028fec750564.gif)
![locationviewbug_2](https://cloud.githubusercontent.com/assets/9156700/19265344/1aa0e3e4-8fa5-11e6-8207-f434f2cce0f8.gif)

After some digging I've found out that this line in MyLocationView is a problem:
`  interpolatedLocation = new LatLng((latLng.getLatitude() + previousLocation.getLatitude()) / 2, (latLng.getLongitude() + previousLocation.getLongitude()) / 2);`
After changing it to:
`interpolatedLocation = new LatLng(latLng.getLatitude(), latLng.getLongitude());`

It's working as below:
![locationviewfix_1](https://cloud.githubusercontent.com/assets/9156700/19265350/2227a256-8fa5-11e6-9ed6-be17c5df09e2.gif)
![locationviewfix_2](https://cloud.githubusercontent.com/assets/9156700/19265351/2361c80e-8fa5-11e6-99a6-725f5e098a90.gif)

**Comment by tobrun** [comment]
Thank you for reaching out and digging into this, that addition and division by 2 is calculating averages but that shouldn't happen in that case. Feel free to PR this, else I will pick this up in next days.

**Comment by tobrun** [comment]
Closed with #6668
