### ISSUE TITLE
rapidjson fails to parse otherwise valid JSON

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#665]
Working with @peterqliu I discovered that rapidjson was giving this error:
```
terminate called after throwing an instance of 'mbgl::error::style_parse'
  what():  Nothing should follow the root object or array.
```

The JSON was valid as far as we could tell. Ping me if you want link to the JSON that was failing.

The strange this is that it was working in the Android emulator with speific edits, but crashing on real devices and in Linux. Depending on the edits it would then not work on anything.

Is there a bug in rapidjson?

**Comment by bleege** [comment]
Haven't seen this in awhile.  It's also at the Core GL level and not the Android bindings.
