### ISSUE TITLE
iOS build times out 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#6653]
Seen this a couple of times in the last few weeks. The iOS build occasionally gets aborted by Bitrise after running for 45 minutes (while a normal build takes 12 minutes). You can spot these builds easily in the Bitrise overview with the yellow color labeling. An example of a build can be seen [here](https://www.bitrise.io/build/e829f7dd41cdd826).

**Comment by friedbunny** [comment]
Hrm, can’t tell what happened in [the build you linked to](https://www.bitrise.io/build/e829f7dd41cdd826) — xcpretty could have swallowed messages about the timeout, or Bitrise could have completely died.

It (and [one other](https://www.bitrise.io/build/e92ba550c5ad6d51)) died while compiling storyboards:
```
▸ Building ios/iosapp [Debug]
▸ Check Dependencies
▸ Compiling MBXUserLocationAnnotationView.m
▸ Compiling main.m
▸ Compiling MBXAppDelegate.m
▸ Compiling MBXOfflinePacksTableViewController.m
▸ Compiling MBXCustomCalloutView.m
▸ Compiling MBXViewController.m
▸ Compiling MBXAnnotationView.m
▸ Linking Mapbox\ GL
▸ Copying /Users/vagrant/git/build/ios/Debug-iphonesimulator/Settings.bundle
▸ Copying app/numeric_filter_style.json
▸ Copying app/points.geojson
▸ Copying /Users/vagrant/git/platform/darwin/test/amsterdam.geojson
▸ Copying app/polyline.geojson
▸ Copying app/line_filter_style.json
▸ Copying app/threestates.geojson
▸ Copying app/fill_filter_style.json
▸ Compiling Main.storyboard
```

Several of the other recent cases I can find have to do with [legitimate](https://www.bitrise.io/build/f941d1243dab630b) [failures](https://www.bitrise.io/build/5057d43778a2620d) from #6468 not causing the build to stop, which should not happen.

[This build](https://www.bitrise.io/build/82e3fa21dc9cd711) timed-out while installing build dependencies, which looks like Bitrise networking instability we’ve seen in the past.

**Comment by tobrun** [comment]
Seeing a weird failing macos build  [here](https://www.bitrise.io/build/fabd208037e314da).

**Comment by tobrun** [comment]
Not seen any reports of this anymore, closing.
