### ISSUE TITLE
mbgl/test.hpp: No such file or directory

### ISSUE THREAD

**Issue by AndersBillLinden** [mapbox/mapbox-gl-native#6657]
Using qt creator 4.0.0, the file test/src/main.cpp gives me the error
mbgl/test.hpp: No such file or directory

**Comment by jfirebaugh** [comment]
This is an internal file that's part of mapbox-gl-native's self-test infrastructure. It's not intended for use in qt creator. See https://github.com/mapbox/mapbox-gl-native/blob/master/platform/qt/README.md for documentation on the Qt SDK.

**Comment by AndersBillLinden** [comment]
Thanks for the answer! That documentation did not mention how to write one or two lines in my pro-file to accomplish make qt-lib via qt creator. Is how to do this is a totally ignorant newcomer question?

**Comment by jfirebaugh** [comment]
@brunoabinader @tmpsantos Do you know the answer to this question?

**Comment by AndersBillLinden** [comment]
Is it possible to make the project compilable even if I am including all files raw like I did? After all, I only encountered one compilation error (this far).

**Comment by brunoabinader** [comment]
@AndersBillLinden our code uses [CMake](https://cmake.org/) as build system - which Qt Creator supports. It should be possible to import the project, as documented in Qt docs: 

http://doc.qt.io/qtcreator/creator-project-cmake.html

**Comment by AndersBillLinden** [comment]
So I need to create a whole new project of this then? Instead of having the files in a dir pointed to by a .pro file?

**Comment by AndersBillLinden** [comment]
I tried this (as per the link you gave me).
1. Right click my existing project in the "projects view" in qt creator.
2. New subproject
3. Choose Non-Qt Project, Plain C++ Application, Choose
4. Put the name mapboxgl, Create in is left unchanged, it is the root directory of my existing project, checking "Use as default project location", next
5. Build system "cmake", next
6. Choosing kit, here I am suspicious, why do I have to do this? I already specify kit in the main project next
7.  Finish
8. The dropdown "Add as a subproject to project:" is disabled with the text <none>, finish

Result of this is that I instead get a sibling project. No reference is made to it in my main project and if I close qt creator and open it again, I see no reference to it in the projects view.

Suggestion: would it be possible to change the build process and include a pro file in your project? Then I can add mapbox-gl-native as a subdir project, like many other libs I am using?

**Comment by tmpsantos** [comment]
> Suggestion: would it be possible to change the build process and include a pro file in your project? Then I can add mapbox-gl-native as a subdir project, like many other libs I am using?

I'm not keen on maintaining two buildsystems because the core part of Mapbox GL Native is shared with Android, iOS, node, etc. That would force people to update the QMake files whereas the CMake we get for free.

What I think is really missing is proper packaging. I have a branch for creating Debian packages and that would make a lot easier to include QMapboxGL on a project as a external dependency (and could be used as basis for RPM and other packaging systems). Would that help?

**Comment by AndersBillLinden** [comment]
Maybe I can solve the problem I had with including the project as a sub project instead, or more correctly qt creators problems with that. So you do not need to do anything, at least not for my sake at the moment.

**Comment by tmpsantos** [comment]
@AndersBillLinden thanks for the feedback. We are working with Qt upstream to get the Mapbox SDK as a plugin of Qt itself, in the future this will be a lot easier I hope.

**Comment by AndersBillLinden** [comment]
make qt-lib resulted in this:
matrix_expression.hpp:2227:21: note. ...this statement, but the latter is misleading indented as if it is guarded by the 'tf'.

Warnings are also treated as errors, I do not know why.

**Comment by AndersBillLinden** [comment]
I added {} around the two ifs, and the build continued. Can I have warnings not treated as errors?

**Comment by AndersBillLinden** [comment]
We had to use this to get rid of errors caused by warnings:
`grep -rl "\-Werror" . | xargs sed -t 's/'-Werror//g'`
Managed to build the project.

This is however not a work method that I find acceptable, so if there is another way of buildig mapboxgl-native, please let me know!
