### ISSUE TITLE
MGLMapView should notify map regionIsChanging when setCenterCoordinate

### ISSUE THREAD

**Issue by iBinh** [mapbox/mapbox-gl-native#6659]
**Platform:** iOS
**Mapbox SDK version:** 3.4.0 alpha 5
### Steps to trigger behavior
1. set mapbox center coordinate
### Expected behavior

MGLMapView delegate regionIsChanging should be called
### Actual behavior

MGLMapView delegate regionIsChanging not called
//cc @1ec5

**Comment by 1ec5** [comment]
mapViewRegionIsChanging is only called when animating the viewport. If you set the centerCoordinate property directly, it won't get called, but if you pass YES or true to setCenterCoordinate:animated:, it will be. If you need to know when the viewport changes without animation, or when the viewport animation finishes, implement mapView:regionDidChangeAnimated:.
