### ISSUE TITLE
Getting Error in getting the plugin for Unity.

### ISSUE THREAD

**Issue by nikbn29** [mapbox/mapbox-gl-native#6664]
Hello,

I have been trying to get Unity plugin for the mapbox which is in branch tmpsantos-unity_plugin branch.

I have OS X Yosemite. apt-get command does not work for the Mac OS X so I am using homebrew instead. But I am getting an error for build-essential when I run the command. Please have a look into the screenshot. Help me regarding this problem. Also, when I run make command, I am getting an error it may be because the first command is not working.

![screen shot 2016-10-12 at 11 13 17 am](https://cloud.githubusercontent.com/assets/22710193/19298643/f80be3b0-906c-11e6-8b87-d70d9de2fb4b.png)

Thanks,
Nikunj.

**Comment by tobrun** [comment]
The `tmpsantos-unity_plugin` branch is part of a forked version of this repo in  https://github.com/tmpsantos/mapbox-gl-native. You currently can't call `make unity` in this repo.

**Comment by nikbn29** [comment]
I have found this doc. https://github.com/tmpsantos/mapbox-gl-native/blob/tmpsantos-unity_plugin/INSTALL.md

Installed Cmake, Node.js, Homebrew, cask and xcpretty. Also got the cURL and pkg-config .tz files and extracted them into mapbox-gl-native-tmpsantos-unity_plugin folder. Still the same error. Please have a look into the new screenshot.

![screen shot 2016-10-12 at 12 03 18 pm](https://cloud.githubusercontent.com/assets/22710193/19299760/e4f3b4ae-9073-11e6-9691-9b595bcc1329.png)

**Comment by tmpsantos** [comment]
@nikbn29 @tobrun is right. This Unity Plugin is a fork and not officially supported, was made as tech demo.

That said, what you are trying to do is install Debian packages on your macOS and that won't work.

The build instructions are here, but they cover Linux.
https://github.com/tmpsantos/mapbox-gl-native/tree/tmpsantos-unity_plugin/platform/unity

On macOS you need a compiler and CMake.

**Comment by nikbn29** [comment]
I have installed all the components as well as some other executables which
are mentioned. I have mentioned that into another comment in the same
issue. Still Its not working. I have shared the screenshot as well.

*Regards,*

*Nikunj Brahmbhatt.*
*Co-Founder at NikSan Tech.*
*Skype : nikbn29.*
*http://www.niksantech.com <http://www.niksantech.com>*

*Contact Number: +919427417755*

Legal Disclaimer: This electronic message and all contents contain
information from www.niksantech.com which may be privileged, confidential,
or otherwise protected from disclosure. The information is intended to be
for the addressee(s) only. If you are not an addressee, any disclosure,
copy, distribution, or use of the contents of this message is strictly
prohibited. If you have received this electronic message in error please
notify the sender by reply e-mail to and destroy the original message and
all copies. NikSan Tech has taken every reasonable precaution to minimize
the risk of malicious content in the mail, but is not liable for any damage
you may sustain as a result of any malicious content in this e-mail. You
should carry out your own malicious content checks before opening the
e-mail or attachment.
www.niksantech.com

**Comment by tmpsantos** [comment]
> I have shared the screenshot as well.

The last screenshot you shared shows you don't have `cmake` installed or `cmake` is not in your `PATH`.

**Comment by nikbn29** [comment]
I am trying this into new machine now. I have run the command.  Cmake & git
are installed successfully. But Curl, build-essential, zlib1g-dev & npm is
not available.

[image: Inline image 1]

**Comment by nikbn29** [comment]
I am able to install curl, npm individually using brew command. But still facing problems for build-essential, zlib1g-dev.

**Comment by nikbn29** [comment]
Finally, make unity works but getting an error of access rights. Can you tell me what is the problem now?
![screen shot 2016-10-12 at 4 04 14 pm](https://cloud.githubusercontent.com/assets/22710193/19306934/a0e4ae54-9095-11e6-983d-50c6401016f8.png)

**Comment by tmpsantos** [comment]
Hmm, could be the way you installed the dependencies. I would assume you previously tried to build as `root` (and you should not do that) and now you are building as your user and it is complaining when trying to overwrite files previously created.
