### ISSUE TITLE
Remove concurrent access to objects from worker threads

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#667]
Currently, we have a number of objects that are shared across threads. This means we're locking these objects when accessing them. To remove lock contention, and to align the architecture with JS, we should move away from shared memory objects.

The way JS (web workers) operates is by having a read-only state of the object in question (e.g. the sprite/glyph atlas). When a write access is required, the worker thread is suspended and the operation is carried out in the main thread (e.g. adding glyphs to the glyph atlas). Then, the updated state is sent to the worker thread again.

**Comment by ChrisLoer** [comment]
Fixed with #8341.
