### ISSUE TITLE
[iOS] crash while getting source from map style 

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#6680]
**Platform: ios**
**Mapbox SDK version: 3.4.0 alpha 5**
### Steps to trigger behavior
1. Load a map
2. try to get a source from the map style
### Expected behavior

The map style returns the source (MGLSource object)
### Actual behavior

The SDK crash.
The crash occurs in MGLStyle.mm, in sourceWithIdentifier: method. It tries to apply a source s to the newly created MGLSource.
MGLSource is an "abstract" class, and a private category is created to expose a method mbglSource. It also creates a property source. This property is never used. Furthermore categories do not allow to add property, even if you have the source code. Private category (extension) allows it.

I removed the declaration of the property source of MGLSource (Private), it works correctly. 
What is the purpose of this property ?

**Comment by frederoni** [comment]
Are you trying to get the source after 
`-[MGLMapViewDelegate mapView:didFinishLoadingStyle:]` has been called?

There's a big rework of runtime styling happening in https://github.com/mapbox/mapbox-gl-native/pull/6601 which would take care of the crash but make sure you're trying to access the source after the style has been loaded.

**Comment by RomainQuidet** [comment]
Yes I access the sourceWithIdentifier: method in manual test, long after the map is loaded. Thanks for this information anyway, I'll add this check in our app.

**Comment by RomainQuidet** [comment]
@frederoni by the way I can't find the callback you referenced in the alpha 5 source code (didFinishLoadingStyle)... Is it in a new branch ?

**Comment by RomainQuidet** [comment]
I checked in MGLMapView.mm, in notifyMapChange: method, 2 enumerations are missing in the switch case: MapChangeDidFinishLoadingStyle and MapChangeSourceDidChange.

**Comment by frederoni** [comment]
You're right, it should be in the upcoming release. For now, make sure you're accessing the source after `-[MGLMapViewDelegate mapViewDidFinishLoadingMap:]`

**Comment by friedbunny** [comment]
Is this still an issue?
