### ISSUE TITLE
Trigger an Event when map is rendered

### ISSUE THREAD

**Issue by fauger** [mapbox/mapbox-gl-native#6682]
Hello,

Is there any to be notified when the map is fully rendered (idle state) after moving it ?

I look into your code, you foresee to implement such event in onMapChanged(@MapView.MapChange int change) but theses events are still indicated as _currently not implemented._

```
 /**
 * <p>
 * This {@link MapChange} is currently not implemented.
 * </p>
 *
 * @see MapView.OnMapChangedListener
 */
public static final int DID_FINISH_RENDERING_MAP = 12;

/**
 * <p>
 * This {@link MapChange} is currently not implemented.
 * </p>
 *
 * @see MapView.OnMapChangedListener
 */
public static final int DID_FINISH_RENDERING_MAP_FULLY_RENDERED = 13;
```

*_Platform: Android
*_Mapbox SDK version: 4.2.0-snapshot

Thanks

**Comment by cammace** [comment]
This looks to be a duplicate issue of https://github.com/mapbox/mapbox-gl-native/issues/3653. Let me know if I misunderstood you and I'll be happy to reopen.
