### ISSUE TITLE
Using MapBox in an iMessage Extension 

### ISSUE THREAD

**Issue by xanderbuck** [mapbox/mapbox-gl-native#6685]
We followed MapBox's example on how to get a simple MGLMapView to display coordinates on a map found [here](https://www.mapbox.com/ios-sdk/examples/), but we were unable to get this to work. Instead, all we got was a clear map view to display that doesn't show any map data at all (the blue color is something I set myself, not map box):

<img width="320" alt="m1 2" src="https://cloud.githubusercontent.com/assets/5334018/19325877/bbe39038-908d-11e6-85ac-aa12528d983d.png">

To trouble shoot it, I used the exact same code in a standard iOS app and map box worked just fine. Plug and Play. Which makes me think its an iMessage extension only issue.

On the iMessage extension side, we get a warning stating:

> "linking against a dylib which is not safe for use in application extensions: /Users/ajbuck/Downloads/MapBoxIMessageExtensionPractice/MapBoxIMessageExtensionPractice/Mapbox.framework/Mapbox"

When looking up this error message in Apple's documentation says:

![m1 3](https://cloud.githubusercontent.com/assets/5334018/19325900/d7fcd568-908d-11e6-9836-cd9a6fa4d6e1.png)

Does this mean MapBox's SDK isn't compatible with iMessage extensions and with its current state it would get our app rejected from the app store? Any suggestions on how to fix this?

Thanks,
Alex

**Comment by incanus** [comment]
Some background here @xanderbuck in https://github.com/mapbox/mapbox-gl-native/issues/4734 & https://github.com/mapbox/mapbox-gl-native/issues/6230. Doesn't appear to work right now; not sure if it's a dynamic library issue or memory constraints or what. I was experimenting with this a few weeks ago and saw similar results as you. 

Note that per https://www.mapbox.com/blog/ios-10-notifications/ you could do this with our [static API](https://www.mapbox.com/api-documentation/#static) or [this library](https://github.com/mapbox/MapboxStatic.swift).

**Comment by friedbunny** [comment]
The Mapbox iOS SDK does not currently support extensions of any sort — action, notification, iMessage, etc. We would certainly like to support these use cases (because they are cool and, theoretically, useful), but platform limitations that are beyond our control have thus far prevented us from offering support.

That’s not to say extensions can’t be supported, but I’ve not seen much to indicate heavy GL-based extensions will work — historically, MapKit hasn’t even been available.

**Comment by friedbunny** [comment]
Closing, this isn’t currently actionable.
