### ISSUE TITLE
-[MGLMapView didReceiveMemoryWarning] should MGLAssertIsMainThread()

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#6688]
`-[MGLMapView didReceiveMemoryWarning]` should `MGLAssertIsMainThread()`, as do other selectors observing `[NSNotificationCenter defaultCenter]`,  such as `sleepGL` and `wakeGL`. Or alternatively, it should dispatch itself back to the main thread.

`UIApplicationDidReceiveMemoryWarningNotification` is not specifically documented as being posted on the main thread, and if `_mbglMap->onLowMemory()` were called from a thread that's not the main thread, that would be bad.

**Comment by incanus** [comment]
This should just be as simple as merely adding the assertion and making sure our tests pass. While in there, I will add an assertion to our response to reachability also given https://github.com/tonymillion/Reachability/blob/bb1b2e1784c2a78c0817c084f6ca98c2f6055f0f/Reachability.m#L459-L463.

**Comment by incanus** [comment]
This is fixed in the `release-ios-v3.4.0` branch.

**Comment by 1ec5** [comment]
Fixed in #7838 on the release-ios-v3.4.0 branch.
