### ISSUE TITLE
Restore gl::debugging::enable() in release mode

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#6689]
8c4da72d09e585bd10d030129c99e1e609a2d2f9 disabled OpenGL `GL_KHR_debug`-type messages in release mode. But we want to keep these -- they may help diagnose issues like #5731. We should revert this change.

cc @kkaefer

**Comment by kkaefer** [comment]
Ah, I disabled them because I assumed that they were slowing things down, but I didn't actually check.

**Comment by kkaefer** [comment]
Can you elaborate what the consequences of enabling debug mode are? Do we want to enable it for all release builds or should it be hidden behind a compile flag?

**Comment by jfirebaugh** [comment]
When enabled, if there is a misuse of OpenGL API, then diagnostic messages will be logged describing the issue. As I understand it, overhead is expected to be low -- the intent of this extension is that it can remain enabled in release builds as a minimal overhead alternative to glGetError. http://stackoverflow.com/a/30559966
