### ISSUE TITLE
Build errors on linux

### ISSUE THREAD

**Issue by ax487** [mapbox/mapbox-gl-native#6693]
I have checked out the repository and I would like to just build the project. Unfortunately, the compilation fails. This is due to the fact that you use "-Werror", and the code triggers a lot of warnings which cause the compile errors. This includes both the code that you wrote yourself as well as the dependencies (boost for example).

**Platform:** Current arch linux, c++ (GCC) 6.2.1 20160830
**Mapbox SDK version:** git revision: 19d3c5ca25519cdbc00ded2323cd1a737711439d

### Steps to trigger behavior

 1. git clone --depth=1 https://github.com/mapbox/mapbox-gl-native.git && cd mapbox-gl-native
 2. make glfw-app 

### Expected behavior

The compilation succeeds.

### Actual behavior

Many compilation errors, such as

    FAILED: CMakeFiles/mbgl-core.dir/src/mbgl/annotation/annotation_tile.cpp.o
    /usr/bin/c++    -I../../../include -I../../../src -Igenerated/./include -I../../../mason_packages/headers/geometry/0.8.0/include -I../../../mason_packages/headers/variant/1.1.0/include -I../../../mason_packages/headers/unique_resource/dev/
    include -I../../../mason_packages/headers/rapidjson/1.1.0/include -I../../../mason_packages/headers/boost/1.60.0/include -I../../../mason_packages/headers/geojson/0.3.2/include -I../../../mason_packages/headers/geojsonvt/6.1.3/include -I..
    /../../mason_packages/headers/supercluster/0.2.0/include -I../../../mason_packages/headers/kdbush/0.1.1/include -I../../../mason_packages/headers/earcut/0.12.1/include -I../../../mason_packages/headers/protozero/1.4.2/include -I../../../pl
    atform/default -I../../../mason_packages/linux-x86_64/sqlite/3.14.2/include -I../../../mason_packages/linux-x86_64/nunicode/1.7.1/include -I../../../mason_packages/linux-x86_64/libpng/1.6.25/include/libpng16 -I../../../mason_packages/linux
    -x86_64/libjpeg-turbo/1.5.0/include -I../../../mason_packages/linux-x86_64/webp/0.5.1/include -std=c++14 -Wall -Wextra -Wshadow -Werror -Wno-variadic-macros -Wno-unknown-pragmas -g   -fPIC -fvisibility-inlines-hidden -MD -MT CMakeFiles/mbg
    l-core.dir/src/mbgl/annotation/annotation_tile.cpp.o -MF CMakeFiles/mbgl-core.dir/src/mbgl/annotation/annotation_tile.cpp.o.d -o CMakeFiles/mbgl-core.dir/src/mbgl/annotation/annotation_tile.cpp.o -c ../../../src/mbgl/annotation/annotation_
    tile.cpp
    In file included from ../../../mason_packages/headers/boost/1.60.0/include/boost/numeric/ublas/matrix.hpp:19:0,
                     from ../../../mason_packages/headers/boost/1.60.0/include/boost/geometry/strategies/transform/matrix_transformers.hpp:41,
                     from ../../../mason_packages/headers/boost/1.60.0/include/boost/geometry/strategies/strategies.hpp:85,
                     from ../../../mason_packages/headers/boost/1.60.0/include/boost/geometry/geometry.hpp:50,
                     from ../../../mason_packages/headers/boost/1.60.0/include/boost/geometry.hpp:17,
                     from ../../../src/mbgl/annotation/symbol_annotation_impl.hpp:21,
                     from ../../../src/mbgl/annotation/annotation_manager.hpp:4,
                     from ../../../src/mbgl/annotation/annotation_tile.cpp:2:
    ../../../mason_packages/headers/boost/1.60.0/include/boost/numeric/ublas/matrix_expression.hpp: In member function ‘void boost::numeric::ublas::matrix_binary<E1, E2, F>::const_iterator1::increment(boost::numeric::ublas::sparse_bidirectiona
    l_iterator_tag)’:
    ../../../mason_packages/headers/boost/1.60.0/include/boost/numeric/ublas/matrix_expression.hpp:2224:17: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
                     if (it2_ != it2_end_)
                     ^~
    ../../../mason_packages/headers/boost/1.60.0/include/boost/numeric/ublas/matrix_expression.hpp:2227:21: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
                         if (it2_ != it2_end_) {

**Comment by tobrun** [comment]
Did you install the required dependencies as documented [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/linux/README.md)?

**Comment by ax487** [comment]
Well, I installed what I think are the equivalent packages for my distribution. Just saying though that this does not look like an include / library not found problem to me

**Comment by tmpsantos** [comment]
@ax487 we are treating all the compilation warnings as errors. Maybe you are using a compiler that is more picky that what Ubuntu 16.04 is using. Try changing it here or exporting `-Wno-error` as `CXXFLAGS`.

```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -38,7 +38,7 @@ endif(WITH_COVERAGE)
 
 set(CMAKE_CONFIGURATION_TYPES Debug Release)
 
-set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -Wall -Wextra -Wshadow -Werror -Wno-variadic-macros -Wno-unknown-pragmas")
+set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -Wall -Wextra -Wshadow -Wno-variadic-macros -Wno-unknown-pragmas")
 if(APPLE)
     # -Wno-error=unused-command-line-argument is required due to https://llvm.org/bugs/show_bug.cgi?id=7798
     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-error=unused-command-line-argument")
diff --git a/platform/ios/vendor/SMCalloutView b/platform/ios/vendor/SMCalloutView
index d6ecaba..2aede5d 160000
--- a/platform/ios/vendor/SMCalloutView
+++ b/platform/ios/vendor/SMCalloutView
@@ -1 +1 @@
```

**Comment by ax487** [comment]
Well, as I said I am using the current version of the GNU compiler collection. Maybe ubuntu is a bit behind in that regard. As far as I know new versions of the compiler tend to include new warning messages. In this case the same problem will appear in ubuntu at some point in the near future.

**Comment by ax487** [comment]
Well, this did get me further, however, there are some linker errors:

    FAILED: mbgl-render
    : && /usr/bin/c++   -std=c++14 -Wall -Wextra -Wshadow -Wno-variadic-macros -Wno-unknown-pragmas -g   CMakeFiles/mbgl-render.dir/bin/render.cpp.o  -o mbgl-render  -rdynamic libmbgl-core.a ../../../mason_packages/linux-x86_64/boost_libprogra
    m_options/1.60.0/lib/libboost_program_options.a libmbgl-loop.a ../../../mason_packages/linux-x86_64/sqlite/3.14.2/lib/libsqlite3.a -ldl -lpthread ../../../mason_packages/linux-x86_64/nunicode/1.7.1/lib/libnu.a ../../../mason_packages/linux
    -x86_64/libpng/1.6.25/lib/libpng.a -lz -lm ../../../mason_packages/linux-x86_64/libjpeg-turbo/1.5.0/lib/libjpeg.a ../../../mason_packages/linux-x86_64/webp/0.5.1/lib/libwebp.a -pthread -lm -lz -lcurl -lGL -lX11 ../../../mason_packages/linu
    x-x86_64/libuv/1.9.1/lib/libuv.a -lrt -lpthread -lnsl -ldl && :
    CMakeFiles/mbgl-render.dir/bin/render.cpp.o: In function `main':
    ./mapbox-gl-native/build/linux-x86_64/Debug/../../../bin/render.cpp:39: undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char
    >, std::allocator<char> > const&, unsigned int, unsigned int)'
    CMakeFiles/mbgl-render.dir/bin/render.cpp.o: In function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<
    char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
    ./mapbox-gl-native/build/linux-x86_64/Debug/../../../mason_packages/headers/boost/1.60.0/include/boost/program_options/errors.hpp:373: undefined reference to `boost::program_options::validation_error::get_template[a
    bi:cxx11](boost::program_options::validation_error::kind_t)'

It seems linking to the boost program_options library does not work properly.

**Comment by tmpsantos** [comment]
@ax487 boost program_option is broken because of this https://github.com/mapbox/mason/issues/157

**Comment by andrewharvey** [comment]
I ran into this issue with gcc6, seems to be an upstream boost issea?

Using gcc5 with `export CXX=g++-5` and `make clean` fixed it.

**Comment by hrefhref** [comment]
I'm having the same issue on debian stretch.
