### ISSUE TITLE
Update to NDK r13

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#6694]
A new version of NDK (r13) was released last week. [The changelog is here](https://github.com/android-ndk/ndk/wiki/Changelog-r13).

Let's check any potential issues with this release and update when we're ready.

/cc: @mapbox/android

**Comment by tobrun** [comment]
This happened in https://github.com/mapbox/mason/pull/346, when building master you will see:
<img width="853" alt="screen shot 2017-03-01 at 15 23 43" src="https://cloud.githubusercontent.com/assets/2151639/23479674/3abf91ae-fe93-11e6-8292-f37d4381361d.png">
