### ISSUE TITLE
Decouple MyBearingTracking from MyLocationTracking

### ISSUE THREAD

**Issue by ahuang13** [mapbox/mapbox-gl-native#6704]
**Platform: Android**
**Mapbox SDK version: 4.2.0-beta.3**

This is a feature request.

The current `TrackingSettings.setMyBearingTrackingMode(...)` API behaves like this...

> When location tracking is disabled the direction of UserLocationView is rotated When location tracking is enabled the MapView is rotated based on bearing value.

(Minor aside... the above API documentation is missing a couple of commas and a period.)

The feature request is to completely decouple the location tracking and bearing tracking. It confuses things to have bearing tracking depend on location tracking.

Semantically, if you are "tracking" the bearing, the map should _follow_ the bearing regardless of location tracking. 

Coupling the two also leads to issues like the following...
### Steps to trigger behavior

Start to track location and bearing, then turn off location tracking, and then turn it back on...
1. `trackingSettings.setMyLocationTrackingMode(MyLocationTracking.TRACKING_FOLLOW)`
2. `trackingSettings.setMyBearingTrackingMode(MyBearingTracking.COMPASS);`
   => The map is following (moving along with) both location and bearing at this point.
3. `trackingSettings.setMyLocationTrackingMode(MyLocationTracking.TRACKING_NONE)`
4. `trackingSettings.setMyLocationTrackingMode(MyLocationTracking.TRACKING_FOLLOW)`
### Expected behavior

I expect the map to resume following (moving along with) _both_ location and bearing. 
### Actual behavior

The map _only_ follows location and does _not_ follow bearing even though `TrackingSettings.getMyBearingTrackingMode()` returns `MyBearingTrackingMode.COMPASS`.

**Comment by cammace** [comment]
Hey, I've made some javadoc edits in https://github.com/mapbox/mapbox-gl-native/pull/7013, thanks for pointing that out! We've recently made significant changes to the behavior of the `TrackingSettings`. It sounds like the behavior is now identical or very similar to what you are describing. Could you check using either `beta.4` or the `SNAPSHOT` and see if this is an improvement.

**Comment by ahuang13** [comment]
@cammace, bearing tracking doesn't even work anymore in `4.2.0-beta.4`. The map no longer turns with the bearing (although I can see the little triangle above the blue dot that rotates along with bearing). I noticed several recent issues/regressions in the issue tracker around bearing that may be related.

Also, I couldn't test with SNAPSHOT. I get the following gradle error...
```
Error: 
Could not find com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0-SNAPSHOT.
Required by: map:app:unspecified
Search in build.gradle files
```

**Comment by ahuang13** [comment]
Update to my last comment... bearing tracking does work. However, it didn't seem to work because immediately after setting bearing tracking, I performed an animation which seemed to undo bearing tracking. I don't think this should happen.

**Comment by cammace** [comment]
If you'd like the map to turn while bearing tracking is enabled you'll also need to enable `map.getTrackingSettings().setMyLocationTrackingMode(MyLocationTracking.TRACKING_FOLLOW);`. You can also set whether the tracking is disabled on user gesture or not within `getTrackingSettings()`. It is assumed that when you perform a camera movement in the code that you want to disable location tracking.

For the `SNAPSHOT` you'll also need to include an additional repository: `maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }` in Gradle.

cc: @zugaldia

**Comment by ahuang13** [comment]
@cammace, my animation only specified zoom/tilt, so my thinking was that this would not affect location/bearing tracking. (Currently, when the user manually zooms the map, the location/bearing tracking is not affected.)

**Comment by cammace** [comment]
I agree that user location tracking should only be disabled when the camera position or bearing is changed, zoom and tilt should have no effect on disabling the user location tracking. Thoughts @tobrun?

**Comment by tobrun** [comment]
> I agree that user location tracking should only be disabled when the camera position or bearing is changed, zoom and tilt should have no effect on disabling the user location tracking. Thoughts @tobrun?

Yes, feel free to ticket that out.

----

I went through the steps to reproduce in OP and seeing the bearing correctly restored:

![ezgif com-video-to-gif 11](https://cloud.githubusercontent.com/assets/2151639/22152744/9af416a0-df24-11e6-8dfc-f1a20d66b835.gif)

Calling this issue resolved. Closing.

**Comment by zugaldia** [comment]
> Yes, feel free to ticket that out.

@cammace Could you cut the ticket when you have a chance? Thanks!

**Comment by cammace** [comment]
Ticketed in https://github.com/mapbox/mapbox-gl-native/issues/7878.
