### ISSUE TITLE
Use "categorical" function type by default when input values are strings

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-native#6708]
A common mistake when using functions is to fail to specify the `categorical` type when values in the input domain are strings. This need not be a mistake. We can do what the user intended by default.

See https://github.com/mapbox/mapbox-gl-function/issues/19 and https://github.com/mapbox/mapbox-gl-function/pull/29
### Expected behavior

When a function's input values are strings and no `type` is specified, the function works as expected.
### Actual behavior

When a function's input values are strings and no `type` is specified, an exception is thrown. If `type` is set to `categorical`, everything works as expected.

**Comment by jfirebaugh** [comment]
Note that this only applies to data-driven properties: #4860.

**Comment by jfirebaugh** [comment]
Not going to do this. We should revert to making "type": "categorical" required: https://github.com/mapbox/mapbox-gl-js/issues/3948.
