### ISSUE TITLE
MGLStyleFunction needs a colorSpaceModel property

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6721]
The iOS and macOS SDKs need to support the new color interpolation option being added in ~~#6442~~ #8720 via a new `colorSpaceModel` property on MGLStyleFunction. No need to extend the initializers, since we can assume a default color space model of [RGB](https://developer.apple.com/reference/coregraphics/cgcolorspacemodel/1408867-rgb).

Ideally, the property would be of type [CGColorSpaceModel](https://developer.apple.com/reference/coregraphics/cgcolorspacemodel) or [NSColorSpaceModel](https://developer.apple.com/reference/appkit/nscolorspacemodel). However, we’d have to provide our own HCL color space model and document the fact that some of the common color space models provided by Core Graphics or AppKit, like grayscale, are unavailable. So it might be easier, if less cool, to define our own enumeration.

/cc @friedbunny @tmcw @zugaldia

**Comment by 1ec5** [comment]
I think we probably will have to provide our own enumeration for this type, because CGColorSpaceModel is new as of iOS 9 and macOS 10.11, and NSColorSpaceModel is new as of macOS 10.10. But we can be consistent with naming at least.

**Comment by jfirebaugh** [comment]
We removed functions. If we bring back color spaces, it'll be as an expression.

**Comment by 1ec5** [comment]
#8720 has been repurposed to track the addition of an expression operator. There would still need to be some platform-specific work, so this issue could be reopened to track that when the time comes.
