### ISSUE TITLE
Update CONTRIBUTING_MACOS.md to reflect latest Android buildchain

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#6722]
Current version of `CONTRIBUTING_MACOS.md` lists `brew cask install android-studio` as the preferred way to install Android Studio, which is outdated (v1.4 vs v2.2.1). Let's review the document and update it accordingly.

/cc: @cammace

**Comment by tobrun** [comment]
FWIW I think installing AS through brew is not really common. 
Haven't seen setting up Android env through before this project.

**Comment by zugaldia** [comment]
@tobrun Same experience as you.
