### ISSUE TITLE
Add support for color interpolation

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#6724]
https://github.com/mapbox/mapbox-gl-native/pull/6442 is introducing support for color interpolation in parity with GL JS' https://github.com/mapbox/mapbox-gl-js/pull/3245. We should support this on Android as part of the Runtime Style API.

This is the Android equivalent of https://github.com/mapbox/mapbox-gl-native/issues/6721 for iOS.

/cc: @ivovandongen @tmcw  @1ec5

**Comment by tobrun** [comment]
The PR in OP was replaced with https://github.com/mapbox/mapbox-gl-native/issues/8720.

**Comment by jfirebaugh** [comment]
We removed functions. If we bring back color spaces, it'll be as an expression.
