### ISSUE TITLE
Unrecognized selector exception when incorrectly using style layers

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#6736]
**Platform:iOS**
**Mapbox SDK version:3.4.0.beta-1**

### Steps to trigger behavior

 1. Create a geojson source
 2. Get a style layer within the current style (labels for example)
 3. Add geojson source to map
 4. Insert geojson below the labels

Example code:

```Swift
let geoJSON = GeoJSONRoute(coordinates: routes.first!.coordinates! )
let geoJSONSource = MGLGeoJSONSource(identifier: "routeSourceID", geoJSONData: geoJSON.asData()!, options: nil)
let line = MGLLineStyleLayer(identifier: "routeLine", source: geoJSONSource)
        
let labels = MGLStyleLayer(identifier: "road-label-small")
        
style().add(geoJSONSource)
style().insert(line, below: labels)
```

### Expected behavior

The geojson layer would be inserted below the labels

### Actual behavior

Fatal error at `MGLStyle insertLayer`; `-[MGLStyleLayer layer]: unrecognized selector sent to instance 0x608000216cf0`

![](https://cldup.com/h-zYqC_CSi.png)

/cc @boundsj @1ec5

**Comment by 1ec5** [comment]
> ```swift
let labels = MGLStyleLayer(identifier: "road-label-small")
```

This line _creates_ a layer; it doesn’t get a layer. To get an existing layer from the style, call `style().layer(identifier: "road-label-small")`.

Also, if you want to _create_ a style layer, never initialize an MGLStyleLayer directly. Read the MGLStyleLayer documentation for more information.

**Comment by 1ec5** [comment]
The bug here is that the check itself throws an exception rather than taking us far enough to [raise a more informative exception](https://github.com/mapbox/mapbox-gl-native/blob/0ccc7f51ba1d3377b93b4dddc3a4a03d0fda2260/platform/darwin/src/MGLStyle.mm#L195).
