### ISSUE TITLE
styles GYP should bundle sprites

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#674]
Currently the `gyp/styles.gypi` only bundles the stylesheets, not the sprites. It we add the sprites, plus finish up `asset://` handling over in https://github.com/mapbox/mapbox-gl-native/issues/579, we can modify the styles to read local sprite assets and save on load time in most use cases. 

Probably doesn't make sense to mirror this whole bundling + `asset://` handling in `gl-js` since resources there will always be remote. 

/cc @mapbox/gl

**Comment by 1ec5** [comment]
We’re getting rid of style bundling altogether in #674.
