### ISSUE TITLE
Rename identifier to name

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6743]
Currently, in the iOS and macOS SDKs:

* MGLStyleLayer, MGLSource, and MGLFeature have identifiers
* MGLStyle’s images have names
* MGLAnnotationImage and MGLAnnotationView have reuse identifiers
* NSImage and UIImage have names

Should we rename `MGLStyleLayer.identifier` and `MGLSource.identifier` to `name`? Then `-[MGLStyle layerWithIdentifier:]` could become `-[MGLStyle layerNamed:]` in Objective-C and `MGLStyle.layer(named:)` in Swift, and `-[MGLSource initWithIdentifier:]` could become `-[MGLSource initWithName:]` in Objective-C and `MGLSource(name:)` in Swift.

Identifiers and reuse identifiers seem like they always refer to optional identifiers for convenience and/or performance, whereas names are intrinsic to the resource and always exist. The current “identifier” naming can lead to less than idiomatic constructions in Swift such as `MGLStyle.layer(withIdentifier:)`. On the other hand, maybe “name” doesn’t imply “unique” strongly enough. They are unique in the case of NSImage/UIImage, but not in the case of MGLStyle.

/cc @boundsj @incanus @frederoni @friedbunny

**Comment by friedbunny** [comment]
The proposed renaming to `name` makes sense to me, though I wouldn’t make a fuss if we stayed with `identifier`. The Swift syntax would be a definite improvement.

The style spec seems largely agnostic, but does refer to layers by `id`:

```json
"layers": [
  {
    "id": "water",
    "source": "mapbox-streets",
    "source-layer": "water",
    "type": "fill",
    "paint": {
      "fill-color": "#00ffff"
    }
  }
]
```

**Comment by 1ec5** [comment]
> The style spec seems largely agnostic, but does refer to layers by `id`

We always have to avoid the term “id” because it’s also an Objective-C keyword. So there will always be a mismatch of some sort. (I filed this ticket just as food for thought. I don’t have a strong opinion one way or another.)

**Comment by friedbunny** [comment]
Right, my point was that this use of `id` in the style spec hews closer to "id(entifier)" than "name". 😉

**Comment by incanus** [comment]
> The proposed renaming to name makes sense to me, though I wouldn’t make a fuss if we stayed with identifier. 

Same here.

**Comment by 1ec5** [comment]
OK, closing because the weak support here isn’t enough to outweigh momentum. Swift 3.0.0’s bridging leaves something to be desired, but we don’t need to make this invasive change because of it.

**Comment by boundsj** [comment]
Sorry I'm late to the party. I was going to say I like how this sort of optimizes for clarity and ease of use at the call site. I also agree it is not absolutely required now. But it'd be interesting to keep in mind as part of a semver change in the future.
