### ISSUE TITLE
Modifying GeoJsonSource data does not invalidate layers

### ISSUE THREAD

**Issue by sddamico** [mapbox/mapbox-gl-native#6744]
**Platform:** Android
**Mapbox SDK version:** 4.2.0-beta.3

### Steps to trigger behavior

Copied from https://github.com/mapbox/mapbox-gl-native/issues/6612#issuecomment-254669786
>It should be noted that the same behavior is seen if one changes the backing data in a geojson source
(e.g. layers not not invalidating until the map is invalidated by zoom or some other event)

>```java
String serializedGeoJsonData = getNewGeoJsonData();
final GeoJsonSource source = mapboxMap.getSourceAs("geoJsonData");
source.setGeoJson(serializedGeoJsonData);
```

A perhaps important note is that the source that I am modifying the data of is initialized as an empty feature collection in our style:

```json
"geoJsonData": {"data": {"type": "FeatureCollection", "features": []}, "type": "geojson"}
```

### Expected behavior
Layers invalidate when their backing source data changes

### Actual behavior
Layers do not invalidate

**Comment by ivovandongen** [comment]
@sddamico I've tried to reproduce this, but it works fine for me. If I create an empty style, with only an empty geojson source and a single layer referencing it ([json file](https://gist.githubusercontent.com/ivovandongen/5f3e84f59be43c069b4feb5c62841526/raw/c44ba758e707e5ef846df71e113cb5271545d928/6744-style.json)), I can update it from code like:

```
GeoJsonSource source = map.getSourceAs("parks-source");
String json = readRawResource(R.raw.amsterdam);
source.setGeoJson(json);
```

(where readRawResource reads the json from somewhere)

Additional updates also take immediate effect.

Please create a minimal case to reproduce if this remains an issue after reviewing your code/style. Closing for now.
