### ISSUE TITLE
3D extrusion

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6745]
~~This issue tracks porting mapbox/mapbox-gl-js#3223, which implements the [`fill-extrude-height`](https://www.mapbox.com/mapbox-gl-style-spec/#paint-fill-extrude-height) and [`fill-extrude-base`](https://www.mapbox.com/mapbox-gl-style-spec/#paint-fill-extrude-base) properties and [`light`](https://www.mapbox.com/mapbox-gl-style-spec/#root-light) root property added to the style specification in mapbox/mapbox-gl-style-spec#495.~~

This issue tracks porting mapbox/mapbox-gl-js#3487, which implements the [`fill-extrusion`](https://www.mapbox.com/mapbox-gl-style-spec/#layers-fill-extrusion) layer type added to the style specification in mapbox/mapbox-gl-style-spec#554, as well as the [`light`](https://www.mapbox.com/mapbox-gl-style-spec/#root-light) root property added to the style specification in mapbox/mapbox-gl-style-spec#495.

The SDKs will also need to expose APIs for these properties. On iOS and macOS, the `light` root property will likely look like separate `lightAnchor`, `lightPosition`, etc. properties on MGLStyle.

Since most use cases for 3D extrusion, particularly 3D buildings (but not [Unix](http://i.stack.imgur.com/VSkCU.jpg)), require the heights to vary feature by feature, this issue essentially depends on data-driven styling: #4860. Note that the scope of this issue is limited to parity with GL JS. mapbox/mapbox-gl#17, mapbox/mapbox-gl#18, and mapbox/mapbox-gl-js#1489 track some future directions for this technology.

/cc @jfirebaugh @lbud

**Comment by lbud** [comment]
🙏 thanks for opening this @1ec5. 

I wrote a branch earlier this summer (based on the original spec proposal, a separate `extrusion` type) to make sure I could do this, and got to the point of rendering non-data-driven extrusions just fine. It's a very [stale branch](https://github.com/mapbox/mapbox-gl-native/tree/extrusions-stale), but once we have the DDS infrastructure in the works I'm excited to revive it 👹

**Comment by matsbov** [comment]
Hi! Will this include 3d-support for node-mapbox-gl-native? I've tried using it for rendering static images from a vector-map and it does not include the `fill-extrusion` layers.

**Comment by 1ec5** [comment]
Yes. This issue tracks implementing `fill-extrusion` layers, which replaced the `fill-extrude-height` and `fill-extrude-base` properties in mapbox/mapbox-gl-style-spec#554. `fill-extrusion` support will be implemented primarily in the cross-platform mbgl library. All the frontends like node-mapbox-gl-native will get that feature “for free” (other than any runtime styling–related updates that might be needed on some platforms).

**Comment by nitrag** [comment]
Terrain visualization is more important to me. Hoping this will get us there. Thanks @lbud!

Maybe MapBox Studio editor will have more control with terrain visualization in the future so we can get a map that looks like http://maps.stamen.com/terrain/#12/37.6439/-122.4346 instead of just a flat/shaded map?

**Comment by jdr6** [comment]
Hi, has anyone found a way to raise polygons with the fill-extrusion layer in iOS? We are finding that 3D buildings created in MapBox studio are flat when the map is used with the iOS SDK. Has anyone got a way around this? Cheers.

**Comment by 1ec5** [comment]
Hi @jdr6, that's what this issue is about. Please see the original description up top for information on the scope of this issue and its prerequisites.

**Comment by 1ec5** [comment]
Note that Mapbox Studio provides an option for hiding options that are incompatible with certain SDKs. You may want to consider enabling that option if you need to ensure compatibility with the iOS SDK.

**Comment by 1ec5** [comment]
> It's a very [stale branch](https://github.com/mapbox/mapbox-gl-native/tree/extrusions-stale), but once we have the DDS infrastructure in the works I'm excited to revive it 👹 

The functionality needed for parity with GL JS is being developed in #8431, now that data-driven styling is implemented.

**Comment by jfirebaugh** [comment]
Support for fill extrusions was added in #8431 and will be in the iOS 3.6.0 and Android 5.1.0 releases.

**Comment by 1ec5** [comment]
We’re tracking runtime styling support for style-wide light settings in #8840 (for iOS and macOS) and #8841 (for Android).

@brunoabinader, I’m not sure where these options would live, so please feel free to open a corresponding ticket for Qt.

**Comment by brunoabinader** [comment]
@tmpsantos is providing extrusion support for Qt in https://github.com/mapbox/mapbox-gl-native/issues/6745#issuecomment-297866793.
