### ISSUE TITLE
[iOS] Wrong annotation tap detection

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#6749]
**Platform: iOS 9/10**
**Mapbox SDK version: 3.4.0 alpha 5**
### Steps to trigger behavior
1. add several annotations (annotation View, native) to the map
2. tap to select an annotation
### Expected behavior

The only annotation(s) selected is (are) the annotation under the finger
### Actual behavior

the selection by a single tap feels strange and selects too many annotations.

After reviewing the code, I feel that there are several points to enhance:
1- 
In the method `handleSingleTapGesture:(UITapGestureRecognizer *)singleTap`, the code tries to take into account a possible offset of any MGLAnnotation by setting the tap point as the annotation coordinate, which is a bad approximation. Later in method `annotationTagAtPoint:(CGPoint)point persistingResults:(BOOL)persist`, it recreates a rectangle centered around the tap point, but if the image was offset by image height for example, the code is wrong.

2- 
Again in `annotationTagAtPoint:(CGPoint)point persistingResults:(BOOL)persist`, the first queryRect creates a rectangle around the tap point with a size which is double of unionedAnnotationRepresentationSize...
I have my annotations, 48p x 48p. The queryRect is then created around the tap point with a size of 96p x 96p. This rect is then enlarged by a padding for hit test, 5 points (x2)... the final queryRect is then 106p x 106p ... which is quite too large !!! The iphone 5 screen is 320p large.
You write in the comment of the method: 

> An annotation is “near” if the distance between its center and the tap is less than the maximum height or width of an installed annotation image or annotation view.

I think the near means half of the maximum height or width... as you can see in the images. Annotations are blue. Query rect is red, and orange with enlarge hit padding.
![currentstateselection](https://cloud.githubusercontent.com/assets/8179069/19514258/3058914c-95f3-11e6-961f-539f3cf5d521.png)

queryRect CGRect must then be created with this size:

`CGRect queryRect = CGRectInset({ point, CGSizeZero },
                                   -_unionedAnnotationRepresentationSize.width/2.0,
                                   -_unionedAnnotationRepresentationSize.height/2.0);
`
Even there the maximum distance between the queryRect center and an annotation center will be 1.41 x unionedAnnotationRepresentationSize (it's a rectangle query rect, not a circle...). 
![correctselection](https://cloud.githubusercontent.com/assets/8179069/19514267/35d10866-95f3-11e6-9c06-5fd5ee327de9.png)
I don't think padding hit test enlarge is necessary. If you feel to keep it, divide by 2 also it's size creation.

3- 
the usage of unionedAnnotationRepresentationSize in annotationTagAtPoint:(CGPoint)point persistingResults:(BOOL)persist feels wrong in a heterogenous annotations sizes environment. I agree that it was the only solution when you only had openGL annotation, but now with native annotation views, tap detection on view is made really simple, and real. I think code detection on native annotation (MGLAnnotationView) and openGL image (MGLAnnotationImage) must be separated completely.

**Comment by RomainQuidet** [comment]
PR available: #6756

**Comment by 1ec5** [comment]
I agree that the current heuristics for annotation hit testing are a bit generous. One thing to keep in mind is that we do want the user to be able to select an annotation (view-backed or otherwise) by tapping slightly outside the annotation’s bounds, which is why we don’t just ask MGLAnnotationView to hit-test the raw tap location. To compensate for that fuzziness, we also allow the user to cycle among nearby annotations by tapping repeatedly in the same location.

**Comment by RomainQuidet** [comment]
Of course, that's why in my PR I use the hitTest rect, not directly the tap point. But when you have a lot of annotations around your finger, it's also annoying to select too many annotations. A correct hit test around your finger tap point is nice.

**Comment by 1ec5** [comment]
Another thing to note is that you can tap multiple times to cycle among nearby annotations. This is roughly how MapKit works as well.
