### ISSUE TITLE
Remove all C style casts

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#675]
From discussion with @artemp we should replace all C style casts with the correct C++ cast.

It may be possible to use g++'s `-Wold-style-cast` flag to find them. Clang might also support this too.

**Comment by jfirebaugh** [comment]
Reopening, since #2034 was reverted. Perhaps we can pursue a more targeted set of changes.

**Comment by ljbade** [comment]
Hmm OK.

It sounds like objective C should be ignored to start with.

**Comment by ljbade** [comment]
Proposal is to get gyp to only apply the `-Wold-stlye-cast` flag to `*.cpp` files.

@incanus What about the changes to remove the use of `malloc` in `MGLMapView` and `MGLMapPoint`?

I replaced it with `std::unique_ptr` but is this too C++y and no ObjCy?

**Comment by ljbade** [comment]
OK I restored the branch and will start removing the ObjC changes.

**Comment by incanus** [comment]
> What about the changes to remove the use of `malloc` in `MGLMapView` and `MGLMapPoint`?

Nah, I think this is ok. Anything which results in less manual memory management is :+1: in my book.

**Comment by ljbade** [comment]
@kkaefer Do you know much about how to apply compile flags based on file extension?

**Comment by mb12** [comment]
In Xcode, you can apply compile flags on a per file basis. Its frequently used to integrate older non-ARC code with ARC codebase. I am not sure if gyp supports this.

http://stackoverflow.com/questions/6646052/how-can-i-disable-arc-for-a-single-file-in-a-project

**Comment by jfirebaugh** [comment]
These are pretty much gone.
