### ISSUE TITLE
CompassView doesn't update position when turning device from landscape to portrait mode

### ISSUE THREAD

**Issue by rmnblm** [mapbox/mapbox-gl-native#6755]
**Platform:** iOS 10.1
**Mapbox SDK version:** 3.4.0-beta.1

Startup the device in **portrait** mode and make the compass view appear:

![portrait1](https://cloud.githubusercontent.com/assets/5942764/19520034/dc328034-960e-11e6-9989-567b87b5b009.png)

Turn the device to **landscape** mode, the compass view still has the same distance to top like in portrait mode, which is wrong:

![landscape](https://cloud.githubusercontent.com/assets/5942764/19520046/f0922ffc-960e-11e6-8269-d8f90f06d5d5.png)

Turn the device back to **portrait**, the compass view distance to top would now be correct when in landscape, but is again wrong in portrait:

![portrait2](https://cloud.githubusercontent.com/assets/5942764/19520063/0c3955c8-960f-11e6-97af-3716077bfdfa.png)

**Comment by friedbunny** [comment]
This is an iOS 10 issue that we’ll probably address as part of fixing #5549.

**Comment by frederoni** [comment]
Fixed in #6776
