### ISSUE TITLE
Marker clickable area

### ISSUE THREAD

**Issue by mpuchala** [mapbox/mapbox-gl-native#6761]
**Platform: Android**
**Mapbox SDK version: 4.2.0 SNAPSHOT**
### Steps to trigger behavior
1. Create Map
2. Click Markers
### Actual behavior

I'm using resources without transparency. Clickable region seems to be much more bigger than image and this is important issue when we have a lot of markers. Also, on 4.1.0 it works fine and area contains only marker.

Example:
https://www.dropbox.com/s/6zin9c8guvrcy6y/clickable_area.mp4?dl=0

Regards!

**Comment by tobrun** [comment]
@mpuchala thank you for reaching out. To give you a some background on marker click handling. Currently we take Android motionEvent and calculate a rectangle from it. The rectangle size is based on the average icon width/height and some additional tolerance:

```java
float left = (tapPoint.x - averageIconWidth / 2 - toleranceSides);
float top = (tapPoint.y - averageIconHeight / 2 - toleranceTopBottom);
float right = (tapPoint.x + averageIconWidth / 2 + toleranceSides);
float bottom = (tapPoint.y + averageIconHeight / 2 + toleranceTopBottom);

RectF tapRect = new RectF(left / screenDensity, top / screenDensity, right / screenDensity, bottom / screenDensity);
```

This rectangle is passed into cpp code and we will be returned all the markers in that rectangle. Using averages here is a very basic way of solving this issue and we could definitely use a more complex approach here.  

> this is important issue when we have a lot of markers

If possible I would advice you to look into using markers of a similar size. This will improve the clickable area issue but imo also improve consistency in your map design.

**Comment by mpuchala** [comment]
@tobrun  thanks for clarification.

Despite the fact I have usually same size icons sometimes it works unstable. When I was analyzing your code I found potential bug. Please take a look on MapView class.  In ``loadIconForMarker(Marker marker)`` method we have:

```
        if (icon == null) {
            icon = IconFactory.getInstance(getContext()).defaultMarker();
            Bitmap bitmap = icon.getBitmap();
            averageIconHeight = averageIconHeight + (bitmap.getHeight() / 2 - averageIconHeight) / iconSize;
            averageIconWidth = averageIconHeight + (bitmap.getWidth() - averageIconHeight) / iconSize;
            marker.setIcon(icon);
        } else {
            Bitmap bitmap = icon.getBitmap();
            averageIconHeight = averageIconHeight + (bitmap.getHeight() - averageIconHeight) / iconSize;
            averageIconWidth = averageIconHeight + (bitmap.getWidth() - averageIconHeight) / iconSize;
        }
```

``averageIconWidth`` is mixed with ``averageIconHeight`` when you're setting it.  I don't think it's kind of workaround more like oversight, isn't it?

**Comment by tobrun** [comment]
I noticed the same thing today, I have a fix for that in https://github.com/mapbox/mapbox-gl-native/pull/5639

**Comment by tobrun** [comment]
Adding a note here that improving this system should also take in account anchoring as noted in https://github.com/mapbox/mapbox-gl-native/issues/7307.

**Comment by pnull** [comment]
Any chance that this will be fixed soon? We have serious problems with this offset bug..

**Comment by MikeKasperlik** [comment]
Yep we see this too in our App

**Comment by neonwarge04** [comment]
when tobrun explained how the code works I was really scratching my head. I just don't really know how everything works under the hood. I was thinking that the pin has width and height and position forming a rect, i tapped the map, I clicked on a pin (touch/mouse position x and y) and then check if that (x,y) is within the bounds of that pin.

I just realized, this works fine on a very very small environment just like on video games. But we are talking about a very very large map and we can't just check all pins on the map if the touch location is within a rect. So at least how it originally works made sense to me.

**Comment by MariusBoepple** [comment]
This thing is a severe bug... Anyone who is using clickable markers, which are anchored at the bottom (that's a really common case) must accept the bad user experience (#7307).

This should be of higher priority...

**Comment by tobrun** [comment]
Small update on this issue:
 - MarkerView clicks are now handled back on the Android SDK View level since #8272, this gives you the expected UX and this approach doesn't suffer from anchoring or average size icons. Feel free to test out beta.3 for this.
 - Marker clicks are still using the system shown above, next actions are ticketed in #8159.

**Comment by neonwarge04** [comment]
Has this been implemented on the v5.0.2? Please confirm. If so close this issue.

**Comment by tobrun** [comment]
Apologies @neonwarge04, I still had to update this issue to the latest state. With 5.0.2 we reverted the changes made for onTouch in the migration of 4.x -> 5.x (#8585). This issue is still applicable for both Markers as MarkerViews.

**Comment by tobrun** [comment]
Tracking latest state in #8159
