### ISSUE TITLE
Document units for MyLocationViewSettings.setPadding()

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#6765]
Currently, [the documentation](https://www.mapbox.com/android-sdk/api/4.2.0-beta.3/com/mapbox/mapboxsdk/maps/widgets/MyLocationViewSettings.html#getPadding--) for `MyLocationViewSettings.setPadding(int left, int top, int right, int bottom)` says the following:

> Set the MyLocationView padding.
> Parameters:
> left - the padding left of MyLocationView
> top - the padding top of MyLocationView
> right - the padding right of MyLocationView
> bottom - the padding bottom of MyLocaionView

(also, note the typo in that last `MyLocaionView`).

The documentation doesn't say the units for these parameters, let's add it. This is confusing, for example, because if we set a padding like:

```
map.getMyLocationViewSettings().setPadding(0, mapView.getHeight() / 2, 0, 0);
```

We'd expect the `MyLocationView` object to be at the bottom of the screen. However, the result is slightly different:

![screenshot_20161019-153126](https://cloud.githubusercontent.com/assets/6964/19534497/fc67a84a-9611-11e6-9005-d963acda2164.png)

/cc: @tobrun @cammace

**Comment by tobrun** [comment]
we divide the padding immediately by 2 when setting, this is needed for correctly calculating the center point for tilt offset later on but is now also taking into account when caculating location on screen. Workaround for now is doubling the value.

**Comment by tobrun** [comment]
MyLocationView is going to be replaced with [LocationLayer](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/locationlayer).
