### ISSUE TITLE
LatLngBounds not applied in OnMapReady

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#6769]
Current:
![device-2016-10-20-124107](https://cloud.githubusercontent.com/assets/2151639/19556692/8734db54-96c2-11e6-9f77-dc4b7c2bf29c.png)

Desired result:
Map centers around 🇺🇸

**Comment by tobrun** [comment]
Noticing that viewportheight is 0, which means the MapView hasn't been measured yet.

**Comment by tobrun** [comment]
Workaround for now is posting the update on the main thread:

```java
        new Handler().post(new Runnable() {
            @Override
            public void run() {
                // Move camera to the bounds with added padding
                int padding = (int) getResources().getDimension(R.dimen.coordinatebounds_margin);
                mapboxMap.animateCamera(CameraUpdateFactory.newLatLngBounds(bounds, padding));
            }
        });
```

![device-2016-10-20-133547](https://cloud.githubusercontent.com/assets/2151639/19558325/22d3aac0-96ca-11e6-8ea0-a1004d6ed742.png)

**Comment by tobrun** [comment]
Ideally this is fixed with a more robust camera system in #6532 (+ improvement over current implementation in #4796). One solution for now would be post every `CameraUpdate` we receive or selectively delay it for LatLngBoundsUpdate. The other option of forcing a measure on MapView didn't work since it triggers a render on core.

cc @mapbox/android

**Comment by tobrun** [comment]
Capturing from @ivovandongen to do a small test with the reverted OnMapReadyCallback (hooking into DID_FINISH_LOADING_MAP instead). This correctly animates the map:

![ezgif com-video-to-gif 71](https://cloud.githubusercontent.com/assets/2151639/19682288/2f3e9afe-9aad-11e6-84b6-7d29fbfb2772.gif)

**Comment by gerhardol** [comment]
From the (duplicate) #6855 
The workaround with post does not work for me. I have to retry a couple of times (as described in the duplicate issue).
Testing on GenyMotion, Android N preview.
While I believe the final solution will work, the workaround may not work for everybody.

**Comment by gerhardol** [comment]
From the (duplicate) #6855 
The workaround with post does not work for me (probably because the map is not visible at creation). I have to retry a couple of times (as described in the duplicate issue).

While I believe the final solution will work, the workaround may not work for everybody.

**Comment by tobrun** [comment]
@gerhardol I would suggest using a `addOnGlobalLayoutListener `. When you receive this callback you are sure the view is measured and you can execute the LatLngBounds Camera update.

**Comment by gerhardol** [comment]
Thanks
The following works for me

                    //Since MapBox 4.2.0-beta.3 moving the camera in onMapReady is not working if map is not visible
                    //The workaround (so far) is to try move the camera at view updates as long as position is 0,0
                    //https://github.com/mapbox/mapbox-gl-native/issues/6855#event-841575956 (and related issues)
                    mapView.getViewTreeObserver().addOnGlobalLayoutListener(
                            new ViewTreeObserver.OnGlobalLayoutListener() {
                                @SuppressWarnings("deprecation")
                                // We check which build version we are using.
                                @Override
                                public void onGlobalLayout() {
                                    if (map.getCameraPosition().target.getLatitude() != 0 ||
                                            map.getCameraPosition().target.getLongitude() != 0) {
                                        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN) {
                                            mapView.getViewTreeObserver()
                                                    .removeGlobalOnLayoutListener(this);
                                        } else {
                                            mapView.getViewTreeObserver()
                                                    .removeOnGlobalLayoutListener(this);
                                        }

                                    }
                                    map.moveCamera(initialCameraPosition);
                                }
                            });

**Comment by tobrun** [comment]
In https://github.com/mapbox/mapbox-gl-native/pull/6919 I'm introducing the runnable around the camera methods for another issue (running an animation in onFinish). To resolve this issue we need to optimise the OnMapReadyCallback to take in account if style is loaded but also if the view is measured yet.

**Comment by tobrun** [comment]
#6999 is the issue tracking the solution for this. Closing as  a duplicate
