### ISSUE TITLE
Limit viewport of visible region on mapbox android native.

### ISSUE THREAD

**Issue by bodhidipta** [mapbox/mapbox-gl-native#6772]
Hi ,
i am trying to limit the viewport of the map , so a user can pan and scroll on my bounded area only.
But in android mapbox i could not found any option for limit the viewport or set maximum bound .
Please provide me an alternative for it in native android.
**Platform:Android**
**Mapbox SDK version:4.1.1**

**Comment by tobrun** [comment]
duplicate #3602
