### ISSUE TITLE
Features added to a mapView through addAnnotation appear below raster tyle sources

### ISSUE THREAD

**Issue by Jmaguerre** [mapbox/mapbox-gl-native#6774]
**Platform:** 
iOS
**Mapbox SDK version:** 
https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.4.0-beta.1
### Steps to trigger behavior

Using the new styles API adding a raster source to the map style makes any annotation appear below the tiles
1. Create a new MGLRasterSource with an URL
2. Create a new MGLRasterStyleLayer with the previously created source
3. Add annotations to mapView
### Expected behavior

Annotations should appear on top of the raster layers
### Actual behavior

I have a glimpse of the annotations appearing on the map before the tiles load. After tiles finish loading annotations do not show.

It happens either adding annotations conforming to MGLAnnotation protocol or MGLPointFeatures.

I don't know if there's anything I'm doing wrong or it is a bug. We have an app using the old RMTileSources and RMMapLayer where it works as expected.

Thanks

**Comment by incanus** [comment]
@Jmaguerre To speed this along, could you whip up a quick code demo? Based on the loading behavior, it does sound like a possible bug.

**Comment by Jmaguerre** [comment]
Okay so while trying to reproduce I think I know what's happening but don't know why. 
Basically what I'm doing is the following:
In the viewDidLoad I have a network call and in the callback I add a raster source and layer to the map.
As the mapView initializes before the call finishes it is loaded with the default mapbox streets base layer.
Once the call finishes I add the new source and layer (mapbox streets satellite) and also any annotation and I can see the annotation drawn over the mapbox street default layer and afterwards , when the other source loads the annotation is covered.

```
  @IBOutlet var mapView: MGLMapView!

  override func viewDidLoad() {

    self.client.doSomeNetworkCall(completion: { () -> Void in 
      let source = MGLRasterSource(identifier: "base", url: URL(string: "mapbox://mapbox.streets-satellite")!, tileSize: 256)
    mapView.style().add(source)

      let layer = MGLRasterStyleLayer(identifier: "base", source: source)
    mapView.style().add(layer)

      mapView.setCenter(CLLocationCoordinate2D(latitude: 40.7326808, longitude: -73.9843407), zoomLevel: 12, animated: false)
    view.addSubview(mapView)

      // Declare the marker `hello` and set its coordinates, title, and subtitle.
      let hello = MGLPointAnnotation()
      hello.coordinate = CLLocationCoordinate2D(latitude: 40.7326808, longitude: -73.9843407)
      hello.title = "Hello world!"
      hello.subtitle = "Welcome to my marker"
    
      // Add marker `hello` to the map.
      mapView.addAnnotation(hello)
    }
  }

```
Result:

![mapboxsatellitewcall](https://cloud.githubusercontent.com/assets/961227/19599384/f0e1a0f0-9776-11e6-89fe-71dee20219ce.gif)

So here comes another posible bug. If I do the same thing without having the network call the source added is never loaded.

```
  @IBOutlet var mapView: MGLMapView!

  override func viewDidLoad() {
    let source = MGLRasterSource(identifier: "base", url: URL(string: "mapbox://mapbox.streets-satellite")!, tileSize: 256)
    mapView.style().add(source)

    let layer = MGLRasterStyleLayer(identifier: "base", source: source)
    mapView.style().add(layer)

    mapView.setCenter(CLLocationCoordinate2D(latitude: 40.7326808, longitude: -73.9843407), zoomLevel: 12, animated: false)
    view.addSubview(mapView)
    
    // Declare the marker `hello` and set its coordinates, title, and subtitle.
    let hello = MGLPointAnnotation()
    hello.coordinate = CLLocationCoordinate2D(latitude: 40.7326808, longitude: -73.9843407)
    hello.title = "Hello world!"
    hello.subtitle = "Welcome to my marker"
    
    // Add marker `hello` to the map.
    mapView.addAnnotation(hello)
  }

```
Result:

![mapboxsatellite](https://cloud.githubusercontent.com/assets/961227/19599398/fd31b9ee-9776-11e6-8d06-493bb31bf076.gif)

**Comment by lilykaiser** [comment]
Closing due to ticket age. If this is still a problem, please re-open

**Comment by amphib** [comment]
this is still a problem. I am running the IOS SDK version 3.7.0 B1. I have several MGLPointAnnotation added to my MGLMapView. They are visible on top of the default streetmap. I use the following code to add a raster layer to the map and the raster layer appears over top of the MGLPointAnnotations. The MGLPointAnnotations are no longer visible. This is also true of MGLPolyline that I have added to the map. The raster layer also hides them.

	MGLRasterSource *source = [[MGLRasterSource alloc] initWithIdentifier:@"onlinemapssource" tileURLTemplates:tileSources options:nil];
	MGLRasterStyleLayer *layer = [[MGLRasterStyleLayer alloc] initWithIdentifier:@"onlinemapslayer" source:source];
	[_map.style addSource:source];
	[_map.style addLayer:layer];

**Comment by Jmaguerre** [comment]
Perfectly understood, thanks for the details of the explanation.
