### ISSUE TITLE
Open callout programmatically immediately after adding a MGLPointAnnotation

### ISSUE THREAD

**Issue by rmnblm** [mapbox/mapbox-gl-native#6775]
I am trying to find the best solution to show a calloutView for a MGLPointFeature coming from a style layer. My idea was to add a `MGLPointAnnotation` to the location the user tapped and delete the point annotation after he tapped on another location, repeating these steps. Sadly, the CalloutView doesn't open directly after adding the point to the map view and I can't find a way to open the CalloutView programmatically.

Are there any other possible or even better solutions for this use case?

PS: Of course I added the delegate method

``` swift
func mapView(_ mapView: MGLMapView, annotationCanShowCallout annotation: MGLAnnotation) -> Bool {
    return true
}
```

**Comment by boundsj** [comment]
How about [-[MGLMapView selectAnnotation:animated:]](https://www.mapbox.com/ios-sdk/api/3.3.4/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)selectAnnotation:animated:)?

**Comment by friedbunny** [comment]
Select the annotation using [`-[MGLMapView selectAnnotation:animated:]`](https://www.mapbox.com/ios-sdk/api/3.4.0-beta.1/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)selectAnnotation:animated:) and the callout view will appear (presuming `-mapView:annotationCanShowCallout:` allows it).

Eventually style layer interactivity will improve, as outlined in https://github.com/mapbox/mapbox-gl-native/issues/6505.

**Comment by rmnblm** [comment]
Oops, that was an easy one, thanks @boundsj and @friedbunny. 

Yesterday was an exhausting day, it would've been better to go to sleep than working on my side-project last night 🙈
