### ISSUE TITLE
expose property transitions to platform SDKs

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#6779]
As in GL JS, we support paint property transitions (i.e animations over time) in core (see [here](https://github.com/mapbox/mapbox-gl-native/blob/7bbd49c72c0daa7036a575a49f6cf13bf8a7020e/src/mbgl/style/paint_property.hpp#L32)) but not yet in the platform SDKs. 

This is an enhancement to runtime styling, but not needed to ship that feature. 

/cc @1ec5 @mollymerp @peterqliu

**Comment by 1ec5** [comment]
mbgl does support paint property transitions baked into the style. However, as far as I can tell, the concrete `mbgl::style::Layer` classes don’t support transitions as part of runtime styling. (They also doesn’t support setting properties per style class: #5948.)

**Comment by 1ec5** [comment]
Also, mbgl does support setting a global paint property duration and delay, via `mbgl::Map::setTransitionOptions()`. However, in the iOS and macOS SDKs, `-[MGLStyle setStyleClasses:transitionDuration:]` is currently private; its only caller is `-[MGLStyle setStyleClasses:]`.

**Comment by incanus** [comment]
I've done some experiments with this using the approach outlined in https://www.objc.io/issues/12-animations/animating-custom-layer-properties/ (_Animating Non-Visual Properties_), which leverages `CALayer`'s ability to interpolate various _types_ of values (numbers, colors, etc.) and, on within a `CABasicAnimation`, repeatedly sets them in the runtime styling API through the use of the `presentationLayer` values. 

![pulse](https://cloud.githubusercontent.com/assets/17722/19875815/3c115a02-9f8d-11e6-8075-487be105ffef.gif)

![rotate](https://cloud.githubusercontent.com/assets/17722/19875830/60748e64-9f8d-11e6-8f1b-ff6a049a35a9.gif)

This isn't high priority right now, but I will get back to this in the near future.

**Comment by incanus** [comment]
Similarly, @cammace was able to do something a lot like this on Android using `ValueAnimator` in [the demo app](https://github.com/mapbox/mapbox-android-demo/blob/b300ce6f6e89fd959de40b4bab6ecc79909dd4c6/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/LasVegasTourismActivity.java#L61-L78). We could probably build out similar APIs on both platforms using the built-in animators of each.

**Comment by incanus** [comment]
Re: https://github.com/mapbox/mapbox-gl-native/issues/6779#issuecomment-255332794, I'm going to sidestep anything related to style classes right now due to https://github.com/mapbox/mapbox-gl-native/issues/5948#issuecomment-243934074. 

Instead, I'm working on global/per-map setters & getters that can be used for broad style URL changes as well as runtime styling. I've confirmed that such things work when set globally (so, you could set a global duration of five second, then change a runtime styling property and see it animate in over that duration).
