### ISSUE TITLE
Document platform requirements for activation/deactivation

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#678]
Following up from @jfirebaugh in https://github.com/mapbox/mapbox-gl-native/pull/676 I am going to start a write up of Android's context activation/deactivation.

Where should it be written? A wiki page?

@incanus You should handle the iOS side (and possibly OSX?). I can work on Linux unless there is someone more knowledgeable who uses Linux too?

**Comment by ljbade** [comment]
Currently WIP:
https://gist.github.com/ljbade/a0df17470dd33601440f

**Comment by jfirebaugh** [comment]
Nice, that looks like it's going to be super informative and useful.

**Comment by jfirebaugh** [comment]
pause/resume is going away with #2909 so this isn't that important anymore.
