### ISSUE TITLE
Style layer predicates should support NSContainsPredicateOperatorType operator

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6784]
In #6586, I was wrong about being wrong about the `CONTAINS` operator in NSPredicate. Whereas the “[Predicate Format String Syntax](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Predicates/Articles/pSyntax.html#//apple_ref/doc/uid/TP40001795-SW1)” chapter of the _Predicate Programming Guide_ only lists `CONTAINS` under the string operators, the [BNF definition](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Predicates/Articles/pBNF.html#//apple_ref/doc/uid/TP40001796-218407) explicitly states:

> `CONTAINS` and `IN` serve both as aggregate operators and string operators, depending on the types of their arguments.

So we should revert #6590 and list the `CONTAINS` operator as an aggregate operator in the `MGLVectorStyleLayer.predicate` documentation comment.

/cc @boundsj @incanus

**Comment by boundsj** [comment]
Fixed by https://github.com/mapbox/mapbox-gl-native/pull/7232
