### ISSUE TITLE
TextMarkers not added to correct position

### ISSUE THREAD

**Issue by altafrm3d** [mapbox/mapbox-gl-native#6785]
I add TextMarkers (created exactly the way you did in TestApp) to mapview, remove them if the zoom level goes below 7, and add them again once the zoom level changes >= 7 using the same options that i have stored. The TextMarkers are not drawn on the correct position once re-added.

**Platform:**
**Mapbox SDK version:**

### Steps to trigger behavior

 1. Create options for TextMarkers, add them to mapView
 2. Remove them on camera change (in my case below zoom level 7)
 3. Add using the same options (in my case at or over zoom level 7)

(Red markers also use the same latLon values as the TextMarkers and they are drawn at correct position)

### Initial correct behavior 
![correct_behaviour](https://cloud.githubusercontent.com/assets/13051552/19597006/365ea93c-9792-11e6-9f50-9b8b856e460f.png)

### After remoing and adding again using the same options
![after_re-adding](https://cloud.githubusercontent.com/assets/13051552/19597019/4438dac8-9792-11e6-9a4b-0b23fe77e6c3.png)

**Comment by cammace** [comment]
Can you confirm this is the same issue reported in https://github.com/mapbox/mapbox-gl-native/issues/6684 on Android?

**Comment by asifaltaf13** [comment]
Yeah, this is the same issue as the gif you entered two days ago

**Comment by tobrun** [comment]
dupe #6684
