### ISSUE TITLE
Windows Build Error

### ISSUE THREAD

**Issue by mariantonia** [mapbox/mapbox-gl-native#6792]
Platform: Windows
Mapbox SDK version: Qt

Steps to trigger behavior

I've triyng to build Mapbox Qt SDK on Windows
1. Checkout repository
2. Installed the dependencies required (install.md)
3. Run make qt-lib

 Expected behavior
 Library builded
 
 Actual behavior
 error: make: *** No rule to make target `qt-lib'.
 
Is there a configuration for Windows Desktop?

**Comment by jfirebaugh** [comment]
Hi @mariantonia -- we don't currently support the Windows platform. Sorry!

**Comment by brunoabinader** [comment]
@mariantonia see https://github.com/mapbox/mapbox-gl-native/issues/7269#issuecomment-265742267 and https://github.com/mapbox/mapbox-gl-native/issues/7269#issuecomment-265832011 for comments on experimental Windows support.
