### ISSUE TITLE
Bitrise Qt5 build bot is failing

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#6794]
This is probably caused by a wrong selection of the clang compiler version:

These errors started to pop up on Bitrise and also on my macOS:
```
In file included from ../../../include/mbgl/util/constants.hpp:3:
../../../include/mbgl/util/chrono.hpp:36:49: error: no template named 'enable_if_t' in namespace 'std'; did you mean 'enable_if'?
template <class Rep, class Period, class = std::enable_if_t<
```
```
../../../include/mbgl/util/optional.hpp:8:37: error: no type named 'optional' in namespace 'std::experimental'
using optional = std::experimental::optional<T>;
                 ~~~~~~~~~~~~~~~~~~~^
```
I'm going to disable Qt5 build bot until we find a fix for this.

/cc @tmpsantos @kkaefer

**Comment by assanegu** [comment]
Good evening,

I am getting this error when i try to run "make qt-lib".
I am using a MacOS Sierra; and Qt5.7 professional.
Do you have any workaround or solution to this?
thank you for your time.

**Comment by brunoabinader** [comment]
Once #6804 gets merged, we can re-enable the Bitrise Qt5 build bot.

@assanegu - yes, see https://github.com/mapbox/mapbox-gl-native/pull/6804/commits/2d908c87d35bf4e7cd9a92144eacef08ebde15df.

**Comment by brunoabinader** [comment]
#6804 is now merged, I'm going to re-enable our Bitrise Qt5 bot :+1:

**Comment by brunoabinader** [comment]
Bitrise Qt5 macOS build bot is now back on track :100:

**Comment by assanegu** [comment]
Thank you for the update. 
The error is no longer happening; but I am still getting a different error that might not related to Mapbox.

FYI, here is the error:
/Users/systemName/Qt/5.7/ios/include/QtGui/qopengl.h:69:13: fatal error: 'OpenGLES/ES3/gl.h' file not found

**Comment by brunoabinader** [comment]
@assanegu this looks like something is missing on your environment setup - can you please provide details e.g. what operating system and build commands are you using to build?

**Comment by assanegu** [comment]
Hi Bruno, 
Thank you for your prompt reply. I am using a MacOS Sierra; and Qt5.7 professional.
As for the issue, I think I resolved the issue. The Qt5Core_DIR was pointing to iOS directory not to the clang_64 directory. meaning: 
Qt5Core_DIR = /Users/myMac/Qt/5.7/ios/lib/cmake/Qt5Core 
so I change it to:
Qt5Core_DIR =/Users/myMac/Qt/5.7/clang_64/lib/cmake/Qt5Core 
and I was able to build it using "make qt-lib".
**However**, I did get the following warnings at the end of the build:
----beginning of the warning -----------
3 warnings generated.
[206/214] Linking CXX static library libmbgl-core.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmbgl-core.a(circle_vertex.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmbgl-core.a(collision_box_vertex.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmbgl-core.a(fill_vertex.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmbgl-core.a(line_vertex.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmbgl-core.a(raster_vertex.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmbgl-core.a(symbol_vertex.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmbgl-core.a(circle_vertex.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmbgl-core.a(collision_box_vertex.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmbgl-core.a(fill_vertex.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmbgl-core.a(line_vertex.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmbgl-core.a(raster_vertex.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmbgl-core.a(symbol_vertex.cpp.o) has no symbols
[214/214] Linking CXX shared library libqmapboxgl.dylib
clang: warning: argument unused during compilation: '-pthread'

----end of the warning -----------

**Also after building the library**,  and running  make run-qt-app; i got the error:
myMac-MBP:mapbox-gl-native assanegueye$ make run-qt-app
platform/macos/ninja  -j4 -C build/qt-macos-x86_64/Debug mbgl-qt
ninja: Entering directory `build/qt-macos-x86_64/Debug'
[3/9] Generating CMakeFiles/mbgl-qt.dir/qrc_common.cpp
Generating moc_mapwindow.cpp
[9/9] Linking CXX executable mbgl-qt
build/qt-macos-x86_64/Debug/mbgl-qt
[ERROR] {}[Setup]: loading style failed: HTTP status code 401

**Comment by jfirebaugh** [comment]
You need to provide an environment variable with your Mapbox access token [as described in the README](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/qt/README.md#developing).

**Comment by assanegu** [comment]
You are right, I did not set the MAPBOX_ACCESS_TOKEN. now it's working. Thank you for your assistance.

**Comment by ducmaxime** [comment]
Hello !

Can you explain me How you set access_token ?

Is it in .pro or directly in the QML ?

Thx

**Comment by brunoabinader** [comment]
Hi @ducmaxime, this repository only contains the C++ API (QMapboxGL), whereas the QML one is hosted in QtLocation repository.

You can find documentation about the Mapbox GL QtLocation plugin here: https://doc.qt.io/qt-5.10/location-plugin-mapboxgl.html#parameters

See below an example on how to provide access token information in QML:

```qml
    Map {
        plugin: Plugin {
            name: "mapboxgl"
            PluginParameter {
                name: "mapboxgl.access_token"
                value: <access token goes here>
            }
        }
    }
```
