### ISSUE TITLE
Still mode should clear the rendered result upon recall

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#6796]
I believe this is what causes the duplicated painting in `regressions/mapbox-gl-js#3365`:

| actual | expected |
| :-: | :-: |
| ![actual](https://cloud.githubusercontent.com/assets/76133/19623674/d3c9c7d4-98db-11e6-85af-9004c0b64a83.png) | ![expected](https://cloud.githubusercontent.com/assets/76133/19623675/d6220f64-98db-11e6-8897-f942ca08a67a.png) |

**Comment by jfirebaugh** [comment]
This test case is designed to test that text collisions are recalculated when rotating the map (a.k.a. `redoPlacement`). The "actual" result looks like what happens if that doesn't happen.
