### ISSUE TITLE
Round latitude/longitude values 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#6800]
While writing some instrumentation tests on the Camera API. I noticed that latitude/longitude coming from core needs to be rounded. Eg. setting a camera position at latitude = 1.0 results in getting core values equal to 1.0000000000000142. I'm suggesting to round this value to 10 decimals.

**Comment by tobrun** [comment]
Same goes for zoom: eg.
> Moved zoom should match expected:<12.500000000000057> but was:<12.5>

**Comment by tobrun** [comment]
Using 10 decimals results in precision of:

> 0.011132 mm

**Comment by tobrun** [comment]
Same issue with bearing:
![screen shot 2016-10-24 at 11 46 27 1](https://cloud.githubusercontent.com/assets/2151639/19641022/8f09eaf2-99df-11e6-94d2-58e80741ffd0.png)

**Comment by tobrun** [comment]
It seems that using 10 decimals is not ideal. For example take a LatLngBounds with corners equal to `{0,0}` and `{2,2}`. This should obviously result in a center of {1,1} but instead I'm hitting:

![screen shot 2016-10-24 at 12 05 17](https://cloud.githubusercontent.com/assets/2151639/19641703/2930469c-99e2-11e6-9626-b3d8eb7763fb.png)

In this case we should round with 3 decimals, which results in a precision of 111m at equator...

**Comment by tobrun** [comment]
Similar issue with `moveTo(x,y):

![screen shot 2016-10-24 at 12 25 35](https://cloud.githubusercontent.com/assets/2151639/19642310/05382cc0-99e5-11e6-9d17-f7cc7876cdc8.png)

**Comment by tobrun** [comment]
Capturing from internal discussions this is expected behaviour from doubles and we/endusers should take this in account when working with the core api. Eg. when comparing two doubles we should always take in account a delta.

Closing for now and will fix up tests #6803 following these guidelines.

**Comment by 1ec5** [comment]
The imprecision described here occurs when you take a `float` and cast it to `double`. In fact, in the iOS and macOS SDKs, [we warn the developer](https://github.com/mapbox/mapbox-gl-native/blob/4fe071b518e792fdf069eb81ac326cf0f27f5e73/platform/darwin/src/NSExpression%2BMGLAdditions.mm#L39-L47) if they attempt to use a `float` in a format string because of this potential to introduce imprecision. To my knowledge, mbgl uses `double`s consistently for geographic values (but `float`s for non-geographic values like color alpha components and symbol offsets).

**Comment by tobrun** [comment]
I have been looking into this issue is more depth by reading up on it and debugging core. I was able to verify the following statement:

> The difference you are observing, will be due to differences in the formatting code that turns the double values into digits for output. In the Java case, the code is giving the most accurate decimal representation of the actual double that it can achieve. In the C++ case, it is rounding off the least significant digits ... which gives the number you expect, but not the most accurate decimal representation.

This is the output produced by java vs c++:

#### Zoom
```
C++ =  1.216975
java =  1.216975118093277
```

#### Latitude
```
C++ = -21.798482
java = -21.798481588640755
```

#### Longitude
```
C++ = 6.316062
java = 6.316062123791681
```

I'm now thinking about rounding the values coming from core to the same decimal amount as I'm currently seeing while debugging.

**Comment by 1ec5** [comment]
> This is the output produced by java vs c++:

That’s an apples-to-oranges comparison of the default display formats for floating-point numbers: by default, C/C++ APIs like `sprintf` and `cout` round to six decimal places, whereas Java apparently goes out to 15:

```c
printf("%g", M_PI);
// => 3.14159
printf("%f", M_PI);
// => 3.141593
printf("%.15f", M_PI);
// => 3.141592653589793
```

**Comment by 1ec5** [comment]
I’m suspicious of [lines like this](https://github.com/mapbox/mapbox-gl-native/blob/b6894dd4fc24f93c77b1ad39f466997f1525f2bd/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/camera/CameraPosition.java#L201-L202) that appear to reinterpret a `float` as a `double`, guaranteeing a bit of cruft in the double-precision decimal places.

**Comment by tobrun** [comment]
>> This is the output produced by java vs c++:
> That’s an apples-to-oranges comparison of the default string conversion formats for floating-point numbers: by default, C/C++ APIs like sprintf and cout round to six decimal places, whereas Java apparently goes out to 15:

Thank you for 👀, was able to verify that they are the same if I increased the decimals while logging. I have now a setup to do some more testes while consecutive zooming isn't resulting in rounded zoom levels.

> I’m suspicious of lines like this that appear to reinterpret a float as a double, guaranteeing a bit of cruft in the double-precision decimal places.

Yes, this is could definitely be an issue, but not the issue for which I reopened this ticket as the code shown there is only used at map startup. I have commented this code out to do additional test on this issue. Will pick this up in a follow up.

**Comment by tobrun** [comment]
First thing I'm noticing is that a map that is initialised with zoom level 0 is set to 0.236014191900084796538195064386

Second thing I noticed is that if you zoom in by 1 using the on screen zoom control you get:
1.23601419190008487980492191127 while you would expect 1.236014191900084796538195064386.

**Comment by 1ec5** [comment]
> First thing I'm noticing is that a map that is initialised with zoom level 0 is set to 0.236014191900084796538195064386

That could be due to mbgl::TransformState constraining the map so that we don't show anything beyond ±180° latitude don't show more than 180° of longitude at the same time (avoiding "world copying").

**Comment by tobrun** [comment]
Figured this one out, it's not related to floating point, our camera change listener was not hooked into the correct MapChange events.
