### ISSUE TITLE
After updating geoJson the map shows old data at previous zoom levels

### ISSUE THREAD

**Issue by mattijsf** [mapbox/mapbox-gl-native#6801]
**Platform:** Android
**Mapbox SDK version:** mapbox-android-sdk:4.2.0-beta.3

### Steps to trigger behavior

 1. Add runtime GeoJson source + layer for visualization (e.g Dataset# 1)
 2. Zoom a bit in/out (otherwise the bug doesn't manifest itself)
 3. Update the source using `setGeoJson` (e.g Dataset# 2)
 4. Zoom in / out.

### Expected behavior

At step 4 visualized data from dataset# 1 should be gone and data from dataset# 2 should be visible at all zoom levels

### Actual behavior

After step 3 the visualized data is correctly replaced with data from dataset# 2. But at step 4 the data is visually alternating between data from dataset# 1 and dataset# 2 at various zoom levels. See gif demo:

![2016_10_24_09_59_23_10_03_11](https://cloud.githubusercontent.com/assets/706368/19637894/8075a5de-99d1-11e6-85ba-dd76affa022f.gif)

```java
@Nullable
private MapboxMap mMap;

private boolean mGeoJsonAlt = false;
private final static String GEOJSON_SOURCE_ID = "test-source";
private final static String GEOJSON_DATA_1 = "{\"type\": \"Feature\",\"geometry\": {\"type\": \"Point\",\"coordinates\": [4.880762, 52.384372]},\"properties\": {}}";
private final static String GEOJSON_DATA_2 = "{\"type\": \"Feature\",\"geometry\": {\"type\": \"Point\",\"coordinates\": [4.908400, 52.35953]},\"properties\": {}}";

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    MapboxAccountManager.start(this, BuildConfig.MAPBOX_ACCESS_TOKEN);

    setContentView(R.layout.activity_main);

    View buttonSwapData = findViewById(R.id.button_swap_data);
    buttonSwapData.setOnClickListener(this);

    SupportMapFragment mapFragment = (SupportMapFragment) getSupportFragmentManager().findFragmentById(R.id.map);
    mapFragment.getMapAsync(this);
}


@Override
public void onMapReady(MapboxMap mapboxMap) {
    mMap = mapboxMap;
    mapboxMap.setCameraPosition(new CameraPosition.Builder()
            .target(new LatLng(52.370216, 4.895168))
            .zoom(10)
            .build()
    );

    // init with GEOJSON_DATA_1
    mapboxMap.addSource(new GeoJsonSource(GEOJSON_SOURCE_ID, GEOJSON_DATA_1));
    mapboxMap.addLayer(new CircleLayer("test-layer", GEOJSON_SOURCE_ID)
            .withProperties(
                    PropertyFactory.circleColor(Color.RED),
                    PropertyFactory.circleRadius(10f),
                    PropertyFactory.circleOpacity(0.8f))
    );

    Toast.makeText(this, "Loaded: GEOJSON_DATA_1", Toast.LENGTH_LONG).show();
}

@Override
public void onClick(View view) {
    if (R.id.button_swap_data == view.getId()) {
        if (mMap != null) {
            mGeoJsonAlt = !mGeoJsonAlt;
            GeoJsonSource geoJsonSource = mMap.getSourceAs(GEOJSON_SOURCE_ID);
            if (geoJsonSource != null) {
                // swap data between GEOJSON_DATA_1 and GEOJSON_DATA_2
                geoJsonSource.setGeoJson(mGeoJsonAlt ? GEOJSON_DATA_2 : GEOJSON_DATA_1);
                Toast.makeText(this, "Loaded: " + (mGeoJsonAlt ? "GEOJSON_DATA_2" : "GEOJSON_DATA_1"), Toast.LENGTH_LONG).show();
            }
        }
    }
}
```

**Comment by ivovandongen** [comment]
@mattijsf Could you verify if you see this when you update to the latest snapshot as well? We just made some changes in this area.

**Comment by mattijsf** [comment]
@ivovandongen just tried it with 4.2.0-SNAPSHOT and I see the same behavior

**Comment by jfirebaugh** [comment]
This would likely be fixed by adding `cache.clear()` to `GeoJSONSource::Impl::setGeoJSON`. (Will require making `cache` protected.)

**Comment by mattijsf** [comment]
For the time being is there any other workaround possible? Currently I'm removing the source including all it's related layers and then re-add the source + layers in order to have it working. But I see some flickering happening every now and then when doing it that way using 400+ lines on the map (a traffic feed at country level).

**Comment by ivovandongen** [comment]
@mattijsf Fix is coming shortly. See #6810
