### ISSUE TITLE
Marker view adapter layout needs a view parent to anchor correctly

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#6805]
When inflating a custom layout in a marker view, the layout must have a view parent to anchor itself correctly, otherwise the marker moves depending on the zoom and never reaches to correct given position.

In both GIFs you'll notice both a cat marker (custom layout marker) and a default marker using the same position. I'm centering both the markers using `0.5f, 0.5f` for the anchor value.
#### Without view parent:

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/5652865/19655982/ee262364-99eb-11e6-8ce1-6650bd23d4f4.gif)
#### With view parent:

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5652865/19655930/b46f678e-99eb-11e6-9de9-b27e2b3be10b.gif)

cc: @mapbox/android

**Comment by dylan-chong** [comment]
For me, I was using my own MarkerViewAdapter that uses an ImageView, and had a sort of similar problem (also same problem when using the MarkerViewManager.ImageMarkerViewAdapter class): When the creating a new marker (inside the getView method of the adapter) the position is offset, but when I am able to reuse the convertView in getView, then the position is fine. 

Do you have something similar if you say: create the cat, wait a second, remove the cat, then create the cat marker again.

**Comment by Guardiola31337** [comment]
Hey 👋  @dylan-chong 
First of all, thanks a lot for reaching out and report your problem.

This should be fixed with #9282. Feel free to test out the latest `5.1.0-beta.5` or the `SNAPSHOT` to verify if it's fixed.

**Comment by Guardiola31337** [comment]
Going ahead and closing here.

@dylan-chong thanks again for using Mapbox and feel free to open new tickets if you find any other issues 😉
