### ISSUE TITLE
ClassNotFoundException raised when catching MapBoxMap.removeSource()

### ISSUE THREAD

**Issue by mattijsf** [mapbox/mapbox-gl-native#6807]
**Platform:** Android
**Mapbox SDK version:** 4.2.0-SNAPSHOT

### Steps to trigger behavior

 1. Wrap `removeSource` with a try-catch that catches `NoSuchSourceException`
 2. Try removing a layer that doesn't exist 
 3. Trigger the `removeSource` with a source id that doesn't exist

### Expected behavior

The NoSuchSourceException catch block is executed.

### Actual behavior

> A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethodV called with pending exception java.lang.ClassNotFoundException: Didn't find class "com.mapbox.mapboxsdk.style.layers.NoSuchSourceException" on path: ...

I noticed that [jni.cpp](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/src/jni.cpp#L1148-L1156) throws: `com/mapbox/mapboxsdk/style/layers/NoSuchSourceException`

While [MapBoxMap.java](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java#L46) throws: `com.mapbox.mapboxsdk.style.sources.NoSuchSourceException`

**Comment by mattijsf** [comment]
Quick workaround: Catch generic Exception

**Comment by tobrun** [comment]
@mattijsf thank you for reaching out an noticing this! It seems that the package name is not correct in `jni.cpp`. cc @ivovandongen
