### ISSUE TITLE
Offline Freezes

### ISSUE THREAD

**Issue by nitrag** [mapbox/mapbox-gl-native#6814]
I am using a stock version of https://github.com/rmnblm/mapbox-ios-examples to test offline downloads. 
1. \- Agnostic of location, when downloading a large area (>6000 resources?) the download reaches 1284 and freezes.  Does "resources" == "tiles"? Is this the 6,000 tile limit?
2. [Feature Request] If "resources" == "vector features", Can we choose to exclude resource types? For instance for offline I would only be interested in streets/roads, parks names....and not stores/buildings, etc. All in the name of "saving resources".
3. \- We need an estimator to warn the users that the `bbox`+`minZoom`+`maxZoom` they are attempting to download will be too large and not complete. I'm aware of how to calculate tile count based on these variables (assuming resources == tiles) so if that's the case never mind.

![download_offline_error](https://cloud.githubusercontent.com/assets/197010/19702045/006d652e-9acc-11e6-8c6c-5e3f7ab3aeb0.jpg)

**Comment by jfirebaugh** [comment]
1. This is likely a network error or some other error. You should register for notifications from [`MGLOfflinePackErrorNotification`](https://www.mapbox.com/ios-sdk/api/3.7.0-alpha.1/Other%20Constants.html#/c:@MGLOfflinePackErrorNotification) to see if that's the case.
2. Yes, if you use a tile source which includes a `style=...` query parameter, the tiles will be style-optimized. See the "Style-optimized vector tiles" section of https://www.mapbox.com/api-documentation/#retrieve-tiles for details.
3. Tracking this request in #9460.
