### ISSUE TITLE
User location tracking bearing camera off by 90 degrees

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#6815]
With the latest beta.4 release, with user bearing tracking enabled, the camera seems to be off by 90 degrees. Icon arrow is pointing in the correct direction. Reproducible in [`LocationTrackingActivity `](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/location/LocationTrackingActivity.java) found in the demo app.

![ezgif com-video-to-gif 4](https://cloud.githubusercontent.com/assets/5652865/19703060/62422b0a-9ad0-11e6-84ee-ea52b2fdf6ac.gif)

cc: @mapbox/android

**Comment by tobrun** [comment]
This is the combination of `MyLocationTracking.TRACKING_FOLLOW` and `MyBearingTracking.COMPASS` not behaving correctly. Normally the compass view should face up and the map should adjust the camera position accordingly.

**Comment by tobrun** [comment]
![ezgif com-video-to-gif 16](https://cloud.githubusercontent.com/assets/2151639/19722335/77d54e74-9b76-11e6-83ae-858a8ddb0cb7.gif)

**Comment by mdakram** [comment]
@tobrun in my case it was with GPS.

**Comment by tobrun** [comment]
@mdakram, was able to reproduce an issue with GPS, the bearing is flipped is, the view is facing north but the map is going south. Is this the issue you are having?

**Comment by mdakram** [comment]
@tobrun exactly.

**Comment by tobrun** [comment]
Proposal to fix both issues in #6829.

**Comment by tobrun** [comment]
Merged in release branch 4.2.0 with https://github.com/mapbox/mapbox-gl-native/pull/6829. Closing
