### ISSUE TITLE
Marker view rotation not working correctly

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#6816]
Marker view rotation is off by ~90 degrees from the expected value. Reproducible in the [`OffRouteActivity`](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/OffRouteActivity.java) in the demo app

cc: @mapbox/android

**Comment by tobrun** [comment]
![ezgif com-video-to-gif 14](https://cloud.githubusercontent.com/assets/2151639/19717513/3c6f6244-9b61-11e6-8034-3453411d6c54.gif)

Not reproducible with suggested OffRouteActivity and latest beta. You probably have animations disabled in developer options?

**Comment by tobrun** [comment]
I had @ivovandongen retest and he is seeing something different:
![image](https://cloud.githubusercontent.com/assets/2151639/19718457/ad9938d8-9b65-11e6-8c2b-b0bd5c5145d3.png)

**Comment by mdakram** [comment]
hi @tobrun can you please check why user tracking mode in current beta 4.UserLocation marker's heading is always facing up. thanks

**Comment by tobrun** [comment]
Tracked it down to updating the rotation while the animation is still ongoing. Regression from commit https://github.com/mapbox/mapbox-gl-native/commit/e598bbfa7c29ad3a384e157b504c4509f1fcdbb5. I'm going to keep the input limitation from that commit but replace the `rotateBy` with a `rotate` animation. This was initially implemented on request from a client but is no longer needed. The requested use-case from them was solved by using `MarkerViewManager.getView(MarkerView marker)` and calling rotation directly on the view instead.

**Comment by tobrun** [comment]
@mdakram
When you have LocationTracking enabled and combine this with a tracking mode, the heading should always face up. The underlying map should adapt the camera position to match the direction you are going to (gps) or your device is pointing to (compass).

**Comment by tobrun** [comment]
Instead of applying https://github.com/mapbox/mapbox-gl-native/issues/6816#issuecomment-256283540, now thinking of fixing up `rotateBy` with:

```java
    /**
     * Animate a MarkerView with a given rotation.
     *
     * @param marker   the MarkerView to rotate by
     * @param rotation the rotation by value
     */
    public void animateRotationBy(@NonNull MarkerView marker, float rotation) {
        View convertView = markerViewMap.get(marker);
        if (convertView != null) {
            convertView.animate().cancel();
            // calculate new direction
            float diff = rotation - convertView.getRotation();
            if (diff > 180.0f) {
                diff -= 360.0f;
            } else if (diff < -180.0f) {
                diff += 360.f;
            }
            AnimatorUtils.rotateBy(convertView, diff);
        }
    }
```

This will cancel the ongoing animation, take the current rotation and calculate the difference. In previous versions we used the previous set rotation.

**Comment by tobrun** [comment]
Merged in release branch with https://github.com/mapbox/mapbox-gl-native/pull/6826.
