### ISSUE TITLE
GL native should match GL JS query feature order

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#6817]
This is the reason for some query tests to be ignored on GL native. Query ordering differs between GL native and GL JS implementation. The flow below from GL JS should be adapted in GL native:
- For each (filtered) style source, query each of its render tiles for features, sorting render tiles based on `zoom`, `y`, `wrap` and `x`, respectively; then
- For each tile containing a feature index, query for its indexed features, sort them, then query for symbols using data from collision tile, sort them too, and merge results; then
- Merge the results from each render tile, and store them on a hash containing feature buckets for each respective layer; then
- Merge the results from each (filtered) style source, applying a sorting scheme that uses the order from which each layer and source have been inserted into the style, resulting in a feature ordering that encompasses _layer_, then _source_ ordering.

This satisfies that _the topmost rendered feature appears first in the returned array, and subsequent features are sorted by descending z-order_.

/cc @jfirebaugh @ansis

**Comment by ChrisLoer** [comment]
Oops, I just spent two hours figuring out this bug existed. The only thing I have to add is that `FeatureIndex` sort indices depend on order of insertion, which is partially determined by `groupByLayout`. On the gl-native side, the ordering of layout groups is currently based on the order of keys in an `unordered_map`, so it's effectively undefined. To bring gl-native and gl-js into sync, we'll want the `groupByLayout` implementation in both of them to sort by `layoutKey`, and we'll need to make sure their implementations of `layoutKey` match.
