### ISSUE TITLE
Syntax error in MGLSymbolStyleLayer.textField documentation

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#6821]
The documentation comment for MGLSymbolStyleLayer’s `textField` property contains a Markdown error. The default value of this paint attribute is the empty string. generate-style-code.js [wraps this default value in two backticks](https://github.com/mapbox/mapbox-gl-native/blob/a4d259c33f9bb890bba97fd89552720e3e0ec09b/platform/darwin/src/MGLSymbolStyleLayer.h#L391), breaking the rest of the paragraph:

![empty](https://cloud.githubusercontent.com/assets/1231218/19714506/bb544cb8-9b03-11e6-81b2-7b4034b29862.png)

/cc @friedbunny

**Comment by incanus** [comment]
This landed in the release branch in https://github.com/mapbox/mapbox-gl-native/pull/6822.
