### ISSUE TITLE
Updated dependencies to 4.2.0 beta4 and map never loads

### ISSUE THREAD

**Issue by naveenorem** [mapbox/mapbox-gl-native#6825]
I was using stable version(4.1.1) of map in my android application and it was working great but I needed this `com.mapbox.mapboxsdk.style` package APIs to toggle layers of the map which I couldn't find in the stable version . Then I came to know that this package is in 4.2.0 beta4 version and I updated my dependencies, though I got the required APIs but my map never loads . 

I reverted back to stable version and it again started working fine
My Question is Can you please guide me if there is any extra steps that are needed to implement 4.2.0 beta4 version in my android app (if any) and if not then what could be the reason for such behavior from my app ?

Tell me if you need any code snippet or log cat output for better understanding the issue.

**Comment by tobrun** [comment]
@naveenorem would you be able to post your logcat output, that would help to diagnose the issue!

**Comment by naveenorem** [comment]
Sorry but right now I can't provide you any log cat .. but if you can tell me which are the areas that I can check which might be causing this problem ?

**Comment by tobrun** [comment]
Without having any additional information and without seeing any other users reporting this issue I'm not able to resolve this. Closing for now.
