### ISSUE TITLE
Incorrect behavior of mbgl-qt example

### ISSUE THREAD

**Issue by eek001c** [mapbox/mapbox-gl-native#6827]
**Platform:**
Environment:
Ubuntu 16.04
uname -a
Linux pc22 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Mapbox SDK version:**
Qt SDK
Build according Qt instruction from master branch (sha a4d259c33f9bb890bba97fd89552720e3e0ec09b)

### Steps to trigger behavior

 1. Execute qt example application mbgl-qt

### Expected behavior
Window is displayed with map sized entire window.
### Actual behavior
Window is displayed with small map in left bottom corner.
![screenshot from 2016-10-26 13-00-06](https://cloud.githubusercontent.com/assets/22762176/19722117/492ac9ae-9b86-11e6-89bc-b8d7ec8d7780.png)

It was working fine last week (before backend refactoring).
QML example(mbgl-qt-qml) works fine.

This is how it works with  2 commits before version (sha 45f4dc0166f2d609d014d2174209fdbe1994c943)
![screenshot from 2016-10-26 13-22-58](https://cloud.githubusercontent.com/assets/22762176/19722465/e7c5095c-9b87-11e6-85f4-552f14931077.png)

**Comment by kkaefer** [comment]
Can't reproduce this in on macOS. What Qt version are you using?

**Comment by brunoabinader** [comment]
I was able to reproduce it on Linux - proposed fix in #6848.
