### ISSUE TITLE
Add user-facing Qt SDK docs

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/mapbox-gl-native#6834]
We have a Qt SDK, but there is not comprehensive documentation on how to use it. @tmpsantos I know we talked about this before -- opening this ticket to track. cc @1ec5

**Comment by brunoabinader** [comment]
@lyzidiamond - tracking this in https://github.com/mapbox/mapbox-gl-native/projects/7.

**Comment by brunoabinader** [comment]
Related work done in https://github.com/mapbox/mapbox-gl-native/pull/7571 and https://github.com/mapbox/mapbox-gl-native/pull/7594 (cc @tmpsantos) - @lyzidiamond I wonder if we could expose the generated HTML documentation somewhere?

**Comment by 1ec5** [comment]
We have mapbox.github.io, if you need a place to hang generated documentation off of. The [macOS SDK documentation](https://mapbox.github.io/mapbox-gl-native/macos/) lives there.

**Comment by tmpsantos** [comment]
For the record, the Qt plugin docs are going to live on the Qt website:
https://doc-snapshots.qt.io/qt5-5.9/location-plugin-mapboxgl.html

**Comment by tmpsantos** [comment]
Done.
