### ISSUE TITLE
Bound Intersection with MGLCoordinateInCoordinateBounds

### ISSUE THREAD

**Issue by naluhh** [mapbox/mapbox-gl-native#6837]
**Platform:**
iOS 10

**Mapbox SDK version:**
Current Master
### Steps to trigger behavior
1. Center the viewport on France
2. Tilt all the way
3. Rotate 90 degree clockwise

Current bounds (returned by [self convertRect:viewPort toCoordinateBoundsFromView:self]) is :
ne:(82.963484, -12.947227) sw:(5.370562, -74.491754)
Zoom:3.975370 
Pitch:60.000000
Direction:85.136936
### Expected behavior

MGLCoordinateInCoordinateBounds(bounds, (49.082393, 5.784256)) should return true, it's inside the screen.
### Actual behavior

MGLCoordinateInCoordinateBounds(bounds, (49.082393, 5.784256)) return false when it's inside the screen

Is there a quick method to check if a specific coordinate is shown in the screen ?

**Comment by jfirebaugh** [comment]
`MGLCoordinateInCoordinateBounds` implements an axis-aligned rectangular bounds, so it's not suitable for checking inclusion of the visible region in a tilted map. For that, you can use [`-convertCoordinate:toPointToView:`](https://www.mapbox.com/ios-sdk/api/4.0.0/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)convertCoordinate:toPointToView:) and check the result against the view extent.
