### ISSUE TITLE
Travis failures setting up android environment

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-gl-native#684]
@ljbade is hitting:

```
./scripts/travis_before_install.sh: line 83:  2479 Killed                  $SEVEN_ZIP_PATH x ./android-ndk-r10c-linux-x86_64.bin > .tmp-ndk-log
```

https://travis-ci.org/mapbox/mapbox-gl-native/jobs/42874715#L128

My sense is that the 7z decode is either taking to much memory or too long and therefore the OOM or travis is killing it. We should look at better ways to set up the NDK.

Ideas include:

 - repack the NDK as a tar.gz to see if that format does not trigger OOM
 - repack the NDK after trying to remove things inside we don't need
 - email travis support about whether they could include the NDK pre-installed
 - ???

Some background:

Older NDK versions used to be available at tarballs but somewhere along the way (Revision 9 or 10?) google started shipping `.bin` files which are self-extracting 7z archives. In the works of the NDK docs:

> Run chmod a+x on the downloaded package.
> Execute the package. For example:
> ndk$ chmod a+x android-ndk-r10c-darwin-x86_64.bin
> ndk$ ./android-ndk-r10c-darwin-x86_64.bin
          
> The folder containing the NDK extracts itself.
> Note that you can also use a program like 7z to extract the package.

I've found that most linux versions cannot self extract the NDK so you need to use 7z to unpack directly due to this bug: https://code.google.com/p/android/issues/detail?id=78148

**Comment by ljbade** [comment]
Moved everything to EC2 now.
