### ISSUE TITLE
Marker info window offset not working correctly

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#6859]
When creating a marker and using `mapboxMap.selectMarker()` while the markers not in view will result in the info window not being positioned correctly.

<img src="https://cloud.githubusercontent.com/assets/5652865/19859948/709ab9ce-9f5d-11e6-996c-ae9fdcd10138.png" width=360/>

cc: @mapbox/android

**Comment by tobrun** [comment]
To make this work we will have to either dynamically recalculate the offset or we need to make InfoWindow a part of our ViewMarker API (this will allow view recycling and calculating the offset only when the views becomes visible on screen).

**Comment by tobrun** [comment]
Instead of approaches mentioned above.
 Not calculating offsets when the Marker is not on screen seems to give the required UX. 

For example:

![ezgif com-video-to-gif 72](https://cloud.githubusercontent.com/assets/2151639/19920190/695ef532-a0d7-11e6-942c-ec77e7e63b39.gif)

**Comment by cammace** [comment]
This was fixed in #6877, closing
