### ISSUE TITLE
Require Xcode 8.0 to build iosapp

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-gl-native#6873]
In https://github.com/mapbox/mapbox-gl-native/pull/6819 we introduced a method in iosapp that uses [[NSLocale languageCode] an iOS 10 only API](https://github.com/mapbox/mapbox-gl-native/blob/2901bc0f6825f426cbcfd2a9ed78648dc81ab665/platform/ios/app/MBXViewController.m#L1123).

Since we intend for iosapp to work with the oldest supported iOS SDK that the Mapbox iOS SDK supports, we should find an alternative solution for `languageCode` that works with iOS 7 and up.

cc @friedbunny @1ec5

**Comment by 1ec5** [comment]
By the way, iosapp requires iOS 8, since it embeds a dynamic framework.

**Comment by 1ec5** [comment]
Instead of `-[NSLocale languageCode]`, we can split `-[NSLocale localeIdentifier]` by `-` and take the first component.

**Comment by boundsj** [comment]
On the 3.4.0 release branch, I'm not seeing this error, too:

![screen shot 2016-11-03 at 6 07 05 pm](https://cloud.githubusercontent.com/assets/63186/19991141/63680924-a1f0-11e6-8302-caf0de6dfd6f.png)

**Comment by 1ec5** [comment]
Can we require Xcode 8.0 to build the SDK? The storyboard format in Xcode 8.0 change means that either we have to require contributors to edit the storyboard in Xcode 7.x otherwise.

**Comment by 1ec5** [comment]
Note that, even though Xcode 8 complains about a minimum deployment target of iOS 7.0, it seems to work just fine. So requiring Xcode 8.0 to build the SDK doesn't necessarily mean dropping support for iOS 7. (Although we should drop iOS 7 support too…)

**Comment by boundsj** [comment]
> Can we require Xcode 8.0 to build the SDK?

I'm 👍  for requiring Xcode 8.0 to develop with the iosapp. We need to support 7.3.1 for the SDK itself as noted in https://github.com/mapbox/mapbox-gl-native/issues/6906#issuecomment-258320302

**Comment by 1ec5** [comment]
`languageCode` usage will be removed in #7400.

**Comment by 1ec5** [comment]
Fixed in b6cf87f5e763ec6849e4fe34f2dd20fc8a0d0d52 on the release-ios-v3.4.0 branch.
