### ISSUE TITLE
[android][release-v4.2.0] MapView resizing not working

### ISSUE THREAD

**Issue by 13kz** [mapbox/mapbox-gl-native#6898]
**Android:release-v4.2.0**

### MapView bounds refreshing

 I'm working on an application which give the user the possibility to make map on fullscreen.  I've a view (kind of form) on the left and a FrameLayout to his right which is the placeholder of my fragment MapFragment. Mapview is added in MapFragment's layout.

### Expected behavior
So to handle fullscreen I just need to change left view visibility (GONE) and automatically mapview should be in fill parent with right bounds.

### Actual behavior
Since I make a tag on release version 4.2.0, on fullscreen the mapview bounds is compress, the street name is compress too. The mapview is not in fill parent.

**Comment by cammace** [comment]
Correct me if I miss understood but I believe you are trying to do something like this. When a click on the map (tested also with `onScroll` event) I have a FrameLayout which becomes visible:

![ezgif com-video-to-gif 10](https://cloud.githubusercontent.com/assets/5652865/19810464/8cd1650c-9cfb-11e6-811b-0d22a5fd06d4.gif)

Here's the code I have placed in the onMapReady call, it toggles the view visibility and invalidates the entire activity layout:
```java
mapboxMap.addMarker(new MarkerViewOptions().position(new LatLng(40.73581, -73.99155)));

        mapboxMap.setOnMapClickListener(new MapboxMap.OnMapClickListener() {
          @Override
          public void onMapClick(@NonNull LatLng point) {
            if (hiddenView.getVisibility() == View.VISIBLE) {
              hiddenView.setVisibility(View.GONE);
              findViewById(R.id.view_container).invalidate();
            } else {
              hiddenView.setVisibility(View.VISIBLE);
              findViewById(R.id.view_container).invalidate();
            }

          }
        });
```

and lastly here's the XML layout I am using:
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:mapbox="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/view_container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".examples.basics.SimpleMapViewActivity">
    
    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapView"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        mapbox:center_latitude="40.73581"
        mapbox:center_longitude="-73.99155"
        mapbox:style_url="@string/style_mapbox_streets"
        mapbox:zoom="11"/>

    <FrameLayout
        android:id="@+id/hidden_view"
        android:layout_width="match_parent"
        android:layout_height="250dp"
        android:layout_gravity="bottom"
        android:visibility="gone">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="center"
            android:text="Hello World"/>

    </FrameLayout>

</LinearLayout>
```

**Comment by 13kz** [comment]
@cammace thanks for your response. I'm trying to do something like that. But instead of declaring MapView directly on activity layout I use a fragment. 
I try to invalidate the entire activity layout, the entire fragment layout but not really helpful. 
Did you work on MapView class on this version that can cause this bug?

**Comment by cammace** [comment]
Could you clarify whether you are using the MapFragment found in the SDK or including the map view inside a custom fragment? I tried my code out using the MapFragment and got identical results to the one found above (no compressing of the map occurred). Going ahead and closing this issue out since it doesn't seem to be a bug in the SDK itself.
