### ISSUE TITLE
Replace Boost.Program_options with POSIX getopt

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#6905]
[Boost.Program_options](http://www.boost.org/doc/libs/1_62_0/doc/html/program_options.html) has been a source of many compilation warnings/errors e.g. targets `offline` and `render` are currently not building on Ubuntu Linux 16.04 due to C++11 ABI incompatibility.

To avoid dealing with extra dependencies like these, we can opt for implementing the program options using POSIX [getopt](http://pubs.opengroup.org/onlinepubs/000095399/functions/getopt.html) - currently used in GLFW.

**Comment by tmpsantos** [comment]
We got the CXXABI working fine here: https://github.com/mapbox/mason/pull/268
