### ISSUE TITLE
SDK won't compile with Xcode 7.3.1

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-gl-native#6906]
Changes introduced in https://github.com/mapbox/mapbox-gl-native/commit/e2797d1f24ac9ea5436921f97fbdac0ddc39d51b broke the project when using Xcode 7.3.1. Specifically:

- In `MGLGeoJSONSource.h`, `const` was moved so that `MGLOfflinePackProgressChangedNotification`, `MGLOfflinePackErrorNotification`, and `MGLOfflinePackMaximumMapboxTilesReachedNotification` are pointers to constant NSString instead of constant pointers to NSString. This fails to compile in Xcode 7.3.1 at the call site
- In `MGLTypes` 
  - the new shim does not define `NSErrorDomain` and is not above where `NSErrorDomain` is used
  - `#if !defined(FOUNDATION_SWIFT_SDK_EPOCH_LESS_THAN) || FOUNDATION_SWIFT_SDK_EPOCH_LESS_THAN(8)` actually uses `FOUNDATION_SWIFT_SDK_EPOCH_LESS_THAN` which is not defined before iOS 10.0

cc @1ec5

**Comment by boundsj** [comment]
7.3.1 is required as noted in https://github.com/mapbox/mapbox-gl-native/issues/6842

**Comment by 1ec5** [comment]
> `#if !defined(FOUNDATION_SWIFT_SDK_EPOCH_LESS_THAN) || FOUNDATION_SWIFT_SDK_EPOCH_LESS_THAN(8)` actually uses FOUNDATION_SWIFT_SDK_EPOCH_LESS_THAN which is not defined before iOS 10.0

Shouldn't it short-circuit on the first clause?

**Comment by boundsj** [comment]
> Shouldn't it short-circuit on the first clause?

It did not appear to do that

**Comment by boundsj** [comment]
Fixed by https://github.com/mapbox/mapbox-gl-native/pull/6923
