### ISSUE TITLE
Expose runtime style properties on PointAnnotations

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#6909]
With the upcoming mobile SDK releases, we're adding support for runtime styling. This adds capabilities as adding layers, sources and changing underlying properties dynamically. One thing that we haven't updated with these capabilities is our (point) annotations API. 

Underneath the public API, our annotations API is using a SymbolLayer and a source with id `com.mapbox.annotations`. We should be able to leverage changing a couple of the symbol properties dynamically and expose some of them as an public API. 

Some examples:
 - [icon-rotate](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-icon-rotate)
 - [icon-offset](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-icon-offset)
 - ...

Exposing these properties will allow gl based annotations to be on par with view based annotations  on terms of public API. For me, view annotations should be a lost resort solution when gl based markers don't fulfil the requirements. For every other case, users should use gl based markers instead.

cc @jfirebaugh @mapbox/mobile

**Comment by tobrun** [comment]
Since the possibilities are allmost endless what to support as a basic API, 
I would try to have parity with Google Maps and expose the following for Android:
 - Alpha
 - Anchor
 - Flat or Billboard
 - Rotation
 - ~~Position~~
 - ~~Title~~
 - ~~Snippet~~
 - ~~Icon~~

**Comment by 1ec5** [comment]
(#6172 would've been a related but more ambitious approach. #1734 would've been the same thing for iOS and macOS.)

**Comment by tobrun** [comment]
Capturing from https://github.com/mapbox/mapbox-gl-native/issues/1734#issuecomment-249967602 that this isn't a priority. Noting that this feature would allow us to support the same API as ViewMarkers ( we can advice to only use ViewMarkers for very limited cases) and it would allow us to have parity with Google Maps SDK. Closing for now..
