### ISSUE TITLE
Style difference between native MapView and Static Maps API

### ISSUE THREAD

**Issue by dgngulcan** [mapbox/mapbox-gl-native#6911]
**Platform:** Android
**Mapbox SDK version:** 4.1.1

### Steps to trigger behavior

 1. Native MapView with default dark theme in Android app
![untitled](https://cloud.githubusercontent.com/assets/1465496/19999341/7bc4dcba-a27a-11e6-8e8f-4a565ede6846.png)

2. Static map obtained through static map api with default dark theme
![screenshot_20161104-113046-2](https://cloud.githubusercontent.com/assets/1465496/19999346/7fc8a09e-a27a-11e6-8acd-201eb39b8aef.png)

### Expected behavior
Same style to be applied in both dynamic and static map

### Actual behavior
Static map image's default dark theme is different than native MapView's default dark theme

**Comment by jfirebaugh** [comment]
Can you post the code you are using to initialize the map style in the Android app, and the URL you're using to request the static map (can omit `access_token`)?

**Comment by dgngulcan** [comment]
Sorry for the late response @jfirebaugh. 

Static map example
https://api.mapbox.com/v4/mapbox.dark/path-5+519D9E-1+519D9E-0(u%7CfzFu%60ipDxDrJzDbH%7CEjDhK%60ZxGn%5CdI~JzH%7D%40hEyDl%40v%40)/29.043575,41.159025,16/1280x720.png?access_token=ACCESS_TOKEN

In java class
```
...
  mMapView.setStyleUrl(Style.DARK);
  mMapView.onCreate(savedInstanceState);
  mMapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(@NonNull MapboxMap mapboxMap) {
                 mMapboxView.getUiSettings().setAllGesturesEnabled(true);
       }
 });
...
```

**Comment by jfirebaugh** [comment]
The static URL you are using is a URL for the ["classic" Static API](https://www.mapbox.com/api-documentation/#static-classic). The classic API uses different styles and a different rendering technology than Mapbox GL and the Mapbox Android SDK, and it is expected that it will not produce identical results to the rendering in the Android SDK. To obtain closer correspondence, use the (regular) [Static API](https://www.mapbox.com/api-documentation/#static). (This API doesn't yet have support for GeoJSON overlays, but we're working on it.)

**Comment by dgngulcan** [comment]
Does GeoJSON includes path drawing too? If not I couldn't find a way to add paths on the regular static map.
Thanks in advance @jfirebaugh !

**Comment by dgngulcan** [comment]
Any news on GeoJSON overlays on [Static API](https://www.mapbox.com/api-documentation/#static)?
