### ISSUE TITLE
Zoom level of loaded tiles is different from CameraPosition's zoom level

### ISSUE THREAD

**Issue by altafrm3d** [mapbox/mapbox-gl-native#6914]
I am showing the zoom level of camera position in DebugModeActivity of Test App.  

### Expected behavior
Tiles of another zoom level should load whenever there is an integral change of zoom level of CameraPosition

### Actual behavior
but actually the loading of new tiles does not happen exactly at that point. (As you can see in the screenshots the new tiles loaded while the zoom level is still at 12)

### Screenshots  

![before](https://cloud.githubusercontent.com/assets/13051552/20005891/20818ac2-a295-11e6-95e5-32f5ddb24018.png)
(Zoom level is 12)

![after](https://cloud.githubusercontent.com/assets/13051552/20005890/207801aa-a295-11e6-93dc-2c4d802219f3.png)
(Zoom level is still 12 but the new tiles load)
 

**Platform: Android** 
**Mapbox SDK version: **

link to my question at stackoverflow: 
https://stackoverflow.com/questions/40285702/why-is-the-camera-position-zoom-different-from-tiles-zoom-level-in-mapbox-gl-an

**Comment by jfirebaugh** [comment]
This is the intended behavior for raster tiles. They transition on half-zoom level boundaries in order to show the sharpest imagery across the fractional zoom range.

**Comment by altafrm3d** [comment]
Thanks for your reply, in our app the user has to download tiles and we need the current zoom level of the tiles that are being shown on the mapview to show the user so that he/she has a better idea about the detail of the tiles he/she is downloading, is there an api or some way of finding out the current zoom level of the tilesource?

**Comment by jfirebaugh** [comment]
I see in your screenshots you've enabled tile debug mode, which displays that information. Is that sufficient?

**Comment by altafrm3d** [comment]
In debug mode cycleDebugOptions() is being called on NativeMapView and rest is handled in native code i suppose, as you are already showing tileSource's zoom level in debug mode on tiles, i am sure you already have an implementation in native code to get the current zoom level for the tiles being shown.

My request is, as there is a way of getting zoom level of camera position with mapBoxMap.getCameraPosition().zoom ... Can you provide a similar call for getting the zoom level of the tilesource for the tiles being shown on the map?

**Comment by jfirebaugh** [comment]
There isn't a built in API, but you can calculate it pretty simply from the map zoom level:

* At map zoom `N`, vector tiles are loaded at zoom `floor(N)`
* At map zoom `N`, 256px raster tiles are loaded at zoom `round(N + 1)`
