### ISSUE TITLE
Lots of rendering tests are failing in android-mason branch

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#692]
From https://github.com/mapbox/mapbox-gl-native/pull/676

Need to figure out the problem. Possibly https://github.com/mapbox/mapbox-gl-native/issues/683

**Comment by ljbade** [comment]
@mikemorris at some stage I am gonna have to work with you to get to the bottom of this, or prehaps I should join the dark side (buy a Mac).

**Comment by ljbade** [comment]
@mikemorris OK I ran debug tests.

I get the same 43 failures on `master` as `android-mason` which I indicated nothing is broken in my code.

Can you re-run and confirm you get the same failures?

Here is my test log to compare: https://gist.github.com/ljbade/74f919eb2036babe15f1

**Comment by mikemorris** [comment]
I'm seeing the exact same failures between `master` and `android-mason` with `BUILDTYPE=Debug` now too, whatever was previously causing this seems to have been fixed.

**Comment by ljbade** [comment]
So close to merge now, I can taste it!
