### ISSUE TITLE
mapbox android SDK (4.2_beta4) - wrong orientation of street labels

### ISSUE THREAD

**Issue by Kra-Kra** [mapbox/mapbox-gl-native#6922]
**Platform:** Android 

**Mapbox SDK version:** 4.2_beta4

My test app displays basic map, but the orientation of most of street labels seems to be wrong (direction of labels do not match the direction of the street).

I see similar problem in the demo Mapbox app available in Google Play.

JavaScript demos which render the same region seem to render the labels correctly.

Screenshot attached:

![screenshot_11](https://cloud.githubusercontent.com/assets/4506802/20013819/3fd0697a-a2bd-11e6-97e1-58972338ace4.png)

**Comment by Kra-Kra** [comment]
This region looks differently when you view it in this the online demo

https://www.mapbox.com/mapbox-gl-js/example/point-from-geocoder-result/

<img width="254" alt="web" src="https://cloud.githubusercontent.com/assets/4506802/20014180/9afffc92-a2be-11e6-9390-d8e819ec8400.png">

you can see how the difference in the way street labels are rendered in first and second screenshot

**Comment by jfirebaugh** [comment]
Another example from #6974:

![image](https://cloud.githubusercontent.com/assets/98601/20196237/a6c4ffa2-a74e-11e6-8441-cffa95e2eaea.png)

@Kra-Kra @muesliq -- have you observed this only on a single device or model, or does it occur on any Android phone?

**Comment by johannesanderwald** [comment]
@jfirebaugh - I have observed this on the Recon Instruments Airwave, which runs at API level 16. I refer to ticket #6974

**Comment by jfirebaugh** [comment]
This is reproducible on the Galaxy S4 GT-I9500 we got for #8658.

**Comment by jfirebaugh** [comment]
This was fixed by #9009.
