### ISSUE TITLE
fill-outline-color render tests failing locally on OS X

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#6927]
The following render tests, which were unignored as part of #6899, are failing locally for me on OS X, although they are [passing on OS X CI](https://www.bitrise.io/build/b5fb2512c0ae28c2):

* failed fill-outline-color function
* failed fill-outline-color literal
* failed fill-outline-color multiply
* failed fill-outline-color opacity
* failed regressions mapbox-gl-js#2305

Here's what the first one looks like:

Expected
![image](https://cloud.githubusercontent.com/assets/98601/20021490/3e280738-a293-11e6-8dd8-d41acb6ecef3.png)

Actual
![image](https://cloud.githubusercontent.com/assets/98601/20021499/468ece7a-a293-11e6-9e18-68606e8e02f4.png)

Diff
![image](https://cloud.githubusercontent.com/assets/98601/20021504/49e8da52-a293-11e6-8720-50cd1d5f4909.png)

The diff on macOS CI, where these are passing, is:
![image](https://cloud.githubusercontent.com/assets/98601/20021578/a4001af0-a293-11e6-80c2-b60b9b24c9cf.png)

I'm currently at 6c30105a5390b1821ba698d6b9c05c4c24294db6 and https://github.com/mapbox/mapbox-gl-test-suite/commit/d27aab1c74f0f0462e19d4aa5700fb2127567f87, macOS 10.11.6 (15G1108).

**Comment by jfirebaugh** [comment]
At least part of the difference seems to be due to the following:

* Mapbox GL JS renders both fill outline (when `fill-outline-color` is set) and fill antialias (when it isn't) _after_ the fill.
* Mapbox GL Native renders fill outline before the fill, or fill antialias after.

When I change native to work like js does, it reduces the difference to:

![image](https://cloud.githubusercontent.com/assets/98601/21121215/fb08443a-c07f-11e6-9be2-b2fb76355976.png)

But the corners are still off.

**Comment by jfirebaugh** [comment]
The remaining difference is due to `glLineWidth`s other than 1 not being supported by the headless rendering in GL-JS test environment.

**Comment by kkaefer** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/9699
