### ISSUE TITLE
make v1 vector tile cleanup with ClipperLib configurable

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#6929]
We've seen significant performance implications in downstream implementations of the Node.js bindings when cleaning up complex v1 vector tiles at runtime. Given that the ClipperLib pathway is primarily intended for maintaining backward compatible rendering for offline databases containing v1 tiles, we should make this code path configurable for implementations where this isn't a concern.

**Comment by jfirebaugh** [comment]
In #8191 we switched to wagyu for clipping v1 tiles, and are going to try to keep it in use universally.
