### ISSUE TITLE
Unable to see rightAccessoryView or rightAccessoryView within custom MGLCalloutView

### ISSUE THREAD

**Issue by iphilgood** [mapbox/mapbox-gl-native#6930]
**Platform: iOS 10.1**
**Mapbox SDK version: 3.4.0-beta.1**

### Steps to trigger behavior

 1. Create custom MGLCalloutView
 2. Define leftAccessoryView and/or rightAccessoryView
 3. Return custom MGLCalloutView from delegate

### Expected behavior

The leftAccessoryView or rightAccessoryView appears in callout.

### Actual behavior

I've defined a UIButton for rightAccessoryView. The style of the callout appears as it was defined in my custom class but I'm not able to see the button within the rightAccessoryView.

I've followed your example [from the Mapbox Examples](https://www.mapbox.com/ios-sdk/examples/custom-callout/).

``` swift
class CustomCalloutView: UIView, MGLCalloutView {
    var rightAccessoryView = UIView()

    init(representedObject: MGLAnnotation) {
        self.representedObject = representedObject
        let detailButton = UIButton(type: .custom)
        detailButton.frame.size.height = 30
        detailButton.frame.size.width = 30
        detailButton.backgroundColor = Colors.TDOrange
        self.rightAccessoryView = detailButton
    }
}
 ```

**Comment by friedbunny** [comment]
When using a custom implementation of MGLCalloutView, you must also implement any accessory views yourself — these are part of the protocol, but cannot be positioned automatically within an arbitrary custom view.
