### ISSUE TITLE
iOS addOverlays when the network is not good

### ISSUE THREAD

**Issue by chatwyn** [mapbox/mapbox-gl-native#6935]
When I use mapbox to addOverlays ,it will be black screen if the network is not good. I want to know how can I addOverLays If the map have not load completed.

**Comment by jfirebaugh** [comment]
@chatwyn In my tests, adding an overlay such as `MGLPolygon` or `MGLPolyline` works as expected without network access. If you're still having a problem with this with the latest version of the Mapbox iOS SDK (3.4.0), please open a new ticket and fill out the complete issue template, including a code sample which replicates the issue.
