### ISSUE TITLE
API Inconsistency for selected annotations

### ISSUE THREAD

**Issue by andrewstay** [mapbox/mapbox-gl-native#6937]
**Platform: iOS**
**Mapbox SDK version: 3.4.0-beta.1**

### Steps to trigger behavior
```MGLMapView``` allows the receiver to obtain a list of selected annotations: 

```-[MGLMapView selectedAnnotations]```

Although, API in the ```MGLMapView``` interface allows to select/deselect only 1 annotation at a time.

### Expected behavior
Please make the API consistent. Either allow multiple annotations to be selected at the same time or correct ```-[MGLMapView selectedAnnotations]``` to return only 1 selected annotation.

**Comment by fphilipe** [comment]
This is expected, I'd say. Mapbox is just following MapKit's `MKMapView` interface, which only has a `selectedAnnotations` property and no single `selectedAnnotation`, while also only allowing a single annotation to be selected at a time.

Knowing this, you can extend `MGLMapView`, making it simpler to work with the selected annotation:

```swift
extension MGLMapView {
    /// Returns the currently selected annotation, if there is one.
    var selectedAnnotation: MGLAnnotation? {
        // `selectedAnnotations` will only ever have at most one element.
        return selectedAnnotations.first
    }

    /// Deselect the currently selected annotation, if there is one.
    func deselectAnnotation(animated: Bool) {
        deselectAnnotation(selectedAnnotation, animated: animated)
    }
}
```
