### ISSUE TITLE
Animate Camera (JNI Error)

### ISSUE THREAD

**Issue by heitorzc** [mapbox/mapbox-gl-native#6951]
Hi guys!

I am having some problems with the method animateCamera. It crashes the app and give me a long log saying "JNI DETECTED ERROR IN APPLICATION" at:

com.mapbox.mapboxsdk.maps.NativeMapView.nativeFlyTo(Native method)
at com.mapbox.mapboxsdk.maps.NativeMapView.flyTo(NativeMapView.java:484)
at com.mapbox.mapboxsdk.maps.MapView.flyTo(MapView.java:1395)
at com.mapbox.mapboxsdk.maps.MapboxMap.animateCamera(MapboxMap.java:565)
and at com.mapbox.mapboxsdk.maps.MapboxMap.animateCamera(MapboxMap.java:507)

It is working fine if I'm using the version **4.0.1** of the SDK, but if I compile the project using the version **4.1.1** or **4.2.0-beta**, I get the error.

Follow a snippet of the code I'm using to animate the camera:

`
CameraPosition cp = new CameraPosition.Builder().zoom(15).target(new LatLng(000, 111)).build();
`
`
mapboxMap.animateCamera(CameraUpdateFactory.newCameraPosition(cp), 5000);
`

I've tested in many different Android devices with different O.S. versions (Android 4.1, 5.0 and 6.0) and I got the problem in all of them.

Please, help! =)
Thanks guys! Keep up the good work.

**Comment by cammace** [comment]
Using the latest `SNAPSHOT` i'm unable to produce this crash:

![ezgif com-video-to-gif 27](https://cloud.githubusercontent.com/assets/5652865/20080234/8c95f3fa-a516-11e6-94df-39da45bfdd2f.gif)

In the GIF, I modified the [`AnimateMapCameraActivity`](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/camera/AnimateMapCameraActivity.java) to use the same coordinate and zoom level you are. Is there any additional information you can give?

**Comment by tobrun** [comment]
@heitorzc are you executing `MapboxMap#animateCamera` on the UI-Thread?

**Comment by heitorzc** [comment]
@cammace unfortunately, I couldn't get my code to work even with the latest snapshot version (4.2.0-SNAPSHOT@aar). =/

@tobrun yes, I am calling the method on the UI-Thread.

I don't know which additional info I could give to you guys because the implementation is pretty simple. Follow a link to the full error log: https://i.imgsafe.org/114ff53988.png

As I said, it is working fine using the version 4.0.1, so do you guys think that I might be missing something here? Is there anything that changed from the version 4.0.1 to the version 4.1.1 that I could be missing?

Thanks guys for the prompt response!
\m/

**Comment by tobrun** [comment]
@heitorzc could you paste me the full first line of the logcat output? and the full implementation of `addMarkerOnMap`? Thank you you for reaching out and reporting your issue.

**Comment by heitorzc** [comment]
Hey @tobrun ... good morning!

OK .. 
This is the first line of the logcat output:
`JNI DETECTED ERROR IN APPLICATION: thread Thread[117,tid=6598,Native,Thread*=0x694f3c80,peer=0x13347760,"pool-11-thread-1"] using JNIEnv* from thread Thread[117,tid=6598,Native,Thread*=0x694f3c80,peer=0x13347760,"pool-11-thread-1"]`

This is the full `addMarkerOnMap` method: http://pastebin.com/05EpNEnF


Thanks for all your help.

**Comment by heitorzc** [comment]
What's up guys!
Any update on this?

Thanks.

**Comment by cammace** [comment]
I've tested your code `addMarkerOnMap` method and didn't run into any issues. How frequent are you calling calling this method?

Closing this issue since it doesn't appear to be an issue in the SDK itself.
