### ISSUE TITLE
InfoWindow does not get inflated with a XML 

### ISSUE THREAD

**Issue by Leminur** [mapbox/mapbox-gl-native#6960]
**Platform: Android**
**Mapbox SDK version: 4.2.0-beta 4**

Good evening!

In the past month I have been trying to inflate a XML into a custom infowindow that I have been developing. I did not succeed doing so, in fact I thought that I was having problem related to the image itself, but the XML was not getting inflated at all. Cammace have been helping me, but we did not succeed yet. 

Here is the java (getInfoWindow) code:
`public View getInfoWindow(@NonNull Marker marker) {

                        **View v = getLayoutInflater().inflate(R.layout.janela_infowindow, null);**

                        TextView titulo = (TextView) v.findViewById(R.id.titulo);
                        TextView desc = (TextView) v.findViewById(R.id.descricao);

                        titulo.setText(marker.getTitle());
                        desc.setText(marker.getSnippet());

                        ImageView countryFlagImage = (ImageView) v.findViewById(R.id.imagem_local);
                        countryFlagImage.setImageDrawable(ContextCompat.getDrawable(Mapa.this, R.drawable.agenciaunb));

                        switch (marker.getTitle()) {
                            case "ICC Centro":
                                desc.setText(marker.getSnippet());
                                break;
                                //and so on...
                        }

                        titulo.setTextColor(Color.WHITE);
                        desc.setTextColor(Color.WHITE);
                 
                        v.setBackgroundColor(Color.rgb(27,77,62));
                        v.setPadding(10, 10, 10, 10);

                        return v;`

Here is the XML code: 

` <?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="200dp"
    android:layout_height="270dp"
    android:weightSum="1">

    <ImageView
        android:id="@+id/imagem_local"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="end"
        android:adjustViewBounds="true"/>

    <TextView
        android:id="@+id/descricao"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:textAlignment="center"
        android:textAppearance="?android:attr/textAppearanceLarge"
        android:textStyle="bold"
        android:typeface="serif"/>

    <TextView
        android:id="@+id/titulo"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textAppearance="?android:attr/textAppearanceLarge"/>

</LinearLayout> `

### Expected behavior
I expected it to show me the custom infowindow with the inflated XML, letting me set with whatever image I wanted. 
### Actual behavior
I am obviously having a pointer error at the image setting due to the fact that there is no place for the image to go. After a few tests, I realized that the custom XML is not getting inflated at all. I am getting this instead of an inflated XML: (Ignore the colors, I just set that up for a better reading)

![zyrkw](https://cloud.githubusercontent.com/assets/9650859/20103800/91ff7572-a5b2-11e6-8503-fb37f366f228.png)

This is not the XML I want to inflate, in fact, I have changed the ids (titulo and desc) from their positions and it did not affected the infoWindow at all. 

Is the latest version of the MapBox capable to inflate XML in an InfoWindow? If so, did I miss something or am I facing a reckless bug that have been chasing me for over a month?

Thanks!

**Comment by cammace** [comment]
Hey @Leminur, sorry to hear this is still an issue for you. Your XML is indeed being inflated and passed in as the info window. I was able to pass in a drawable (blue marker in screenshot):

<img src="https://cloud.githubusercontent.com/assets/5652865/20105931/87983012-a5a1-11e6-8d34-b977b1eece26.png" width=360/>

The latest version is capable of inflating XML. I removed the info window color and padding you were setting and it resulted in this: 

<img src="https://cloud.githubusercontent.com/assets/5652865/20106033/cff92b36-a5a1-11e6-8051-eda6606bf890.png" width=360/>

Let me know if I'm missing something here

**Comment by tobrun** [comment]
@Leminur this issue you are facing is not related to this SDK but I think this is a misconfiguration of your LinearLayout. I would advice you to optimise the LinearLayout (not sure what is going wrong but something with that weightsum and having your children match parent could be something to  look at) or look into replacing it with an alternative layout as a RelativeLayout. Closing as this is not an SDK bug. Thank you for reaching out!
