### ISSUE TITLE
Android tests should be integrated into Travis CI

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#697]
Ideally we want Travis CI builds to fail if someone on OSX breaks iOS or Android.

Steps:
- [ ] create Android testcases
- [ ] add Android emulator to Travis
- [ ] run Android testcases

**Comment by incanus** [comment]
iOS todo for this is already at https://github.com/mapbox/mapbox-gl-native/issues/830. These are very platform-specific, so I'm refining this ticket to just target Android.

**Comment by ljbade** [comment]
Consolidating at https://github.com/mapbox/mapbox-gl-native/issues/1667
