### ISSUE TITLE
Label placement along geometry broken despite symbol-placement:line

### ISSUE THREAD

**Issue by johannesanderwald** [mapbox/mapbox-gl-native#6974]
Hello,

We are developing an app and the problem is that the label placement is broken. The label is not rendered according to the line it belongs. However, it works fine in GL JS.

We are using Android API Level 16.

What can we do about it?

![device-2016-10-25-170039](https://cloud.githubusercontent.com/assets/3831724/20131535/5e983082-a65e-11e6-95d2-1f2dff3f3204.png)

**Comment by muesliq** [comment]
Here the same area rendered in GL JS:
![screen shot 2016-11-09 at 15 24 34](https://cloud.githubusercontent.com/assets/1606618/20141459/bad0c30a-a690-11e6-94ed-6f40f5264396.png)

**Comment by jfirebaugh** [comment]
Can you please provide the style and code used in those two screenshots?

**Comment by jfirebaugh** [comment]
Also, can you be more specific about what rendering you expected in the first case?

**Comment by johannesanderwald** [comment]
Hello,

we are using the style http://vtile01.maptoolkit.net/styles/terrainwinter-v2.json. 

The descriptions are not aligned to the line. In the screenshot posted by muesliq, the descriptions are properly aligned to the line.

**Comment by muesliq** [comment]
Hi @jfirebaugh, look at the labels (ski pistes and lifts) here:

![mapbox-gl-bug](https://cloud.githubusercontent.com/assets/1606618/20170738/bddf2be8-a72d-11e6-9fbe-27e33df76d21.png)

Style:

```
    {
      "source": "pistes",
      "type": "symbol",
      "layout": {
        "text-field": "{name}",
        "text-font": ["Open Sans Regular"],
        "symbol-spacing": 400,
        "text-size": {"stops": [[8, 8], [20, 20]], "base": 1.2},
        "text-padding": 2,
        "text-letter-spacing": 0.05,
        "symbol-placement": "line",
        "text-max-angle": 40
      },
      "id": "pistes-label",
      "source-layer": "road_label",
      "paint": {
        "text-halo-width": {"stops": [[13, 1], [20, 2]]},
        "text-halo-color": "hsla(0, 0%, 100%, 1)",
        "text-color": "hsla(0, 0%, 0%, 0.8)"
      },
      "minzoom": 13,
      "filter": ["in", "class", "aerialway", "piste"]
    },
```
 
(In case you wonder: The colors of the lines were changed between the two versions, yet the labels weren't changed.)

**Comment by jfirebaugh** [comment]
Thank you for the clarification. I see what you're referring to now and it looks like the same issue as #6922. I'm going to close this issue and ask for additional information in #6922.
