### ISSUE TITLE
Android - Camera rotation disabled while bearing tracking

### ISSUE THREAD

**Issue by tomlocks** [mapbox/mapbox-gl-native#6976]
**Platform: Android 6.0.1**
**Mapbox SDK version: 4.2.0@beta4**

### Steps to trigger behavior

 1. Enable bearing tracking using this code:
`        map.setMyLocationEnabled(true);
        map.getTrackingSettings().setDismissBearingTrackingOnGesture(false);
        map.getUiSettings().setRotateGesturesEnabled(true);
        map.getTrackingSettings().setMyBearingTrackingMode(MyBearingTracking.GPS);`

### Expected behavior
Two finger rotation gesture should work and the cursor should follow the gps bearing.
### Actual behavior
Two finger rotation is not working.

**Comment by tobrun** [comment]
Pinpointed as regression in https://github.com/mapbox/mapbox-gl-native/pull/6569.
