### ISSUE TITLE
mapbox compiled failed on ubuntu failed for android

### ISSUE THREAD

**Issue by mrrichardli** [mapbox/mapbox-gl-native#6993]
**Platform:Android**
**Mapbox** SDK version:**
**Ubuntu Version
kernel version:Linux version 4.4.0-21-generic (buildd@lgw01-21) 
gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2) )**_ jfirebaugh

- hello,

     I compiled the mapbox-gl-native on ubuntu by "sudo make android", it almost compiled succesfully,
but at last, it got the failed information as below and got no 'so' files in corresponding folder.I'm not sure what's going wrong, and this has confused me for a long time! @jfirebaugh @kkaefer @boundsj Thank you very much!
![Uploading clipboard.png…]()
![Uploading clipboard.png…]()

> sudo make android
> mkdir -p build/android-arm-v7/Debug
> platform/android/scripts/toolchain.sh arm-v7 > build/android-arm-v7/Debug/toolchain.cmake
> Loading options from /etc/masonrc...Check vars...ipchains was not found in your path or in /sbin. You may need to copy it
> or add an explicit path to it in the following commands.
> ipfwadm was not found in your path or in /sbin. You may need to copy it
> or add an explicit path to it in the following commands.
> Editor default of /usr/bin/vi taken.
> Load IPs, networks and nameservers...Done.
> This kernel does not support ipchains, ipfwadm or iptables!
> ---- Mason firewall builder for Linux                         ----
> ---- see http://www.pobox.com/~wstearns/mason/ **for** more info. ----
> ---- William Stearns <wstearns@pobox.com>                     ----
> (This is release 1.0.0-11 - 2008-06-27 )

> Mason is exiting because of an end of input data.
> platform/android/scripts/toolchain.sh: line 15: mason: No such file or directory
> platform/android/scripts/toolchain.sh: line 15: which: No such file or directory
> platform/android/scripts/toolchain.sh: line 16: mason: No such file or directory
> platform/android/scripts/toolchain.sh: line 16: which: No such file or directory
> platform/android/scripts/toolchain.sh: line 17: mason: No such file or directory
> platform/android/scripts/toolchain.sh: line 19: mason: No such file or directory
> platform/android/scripts/toolchain.sh: line 20: mason: No such file or directory
> platform/android/scripts/toolchain.sh: line 21: mason: No such file or directory
> platform/android/scripts/toolchain.sh: line 22: mason: No such file or directory
> platform/android/scripts/toolchain.sh: line 23: mason: No such file or directory
> platform/android/scripts/toolchain.sh: line 23: which: No such file or directory
> cd build/android-arm-v7/Debug && cmake ../../.. -G Ninja -DCMAKE_TOOLCHAIN_FILE=build/android-arm-v7/Debug/toolchain.cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DMBGL_PLATFORM=android
> CMake Error: Error: generator : Ninja
> Does not match the generator used previously: Unix Makefiles
> Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
> Makefile:507: recipe for target 'build/android-arm-v7/Debug/Makefile' failed
> make: *** [build/android-arm-v7/Debug/Makefile] Error 1

**Comment by jfirebaugh** [comment]
It looks like the `.mason` git submodule is missing. Did you clone the repository from git?

**Comment by kkaefer** [comment]
Please don't use `sudo` for building; it'll create all sorts of files as the root user, which makes it harder to read/delete later on as a regular user. Not even speaking of all of the security implications.

**Comment by xiaosenlin** [comment]
hello,I met same problem,Can you help me?@ mrrichardli
