### ISSUE TITLE
Cherry pick #6828 (Line-break ideographic text by character)

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#6996]
Capturing from @1ec5  that Android will need a port of https://github.com/mapbox/mapbox-gl-native/pull/6828. That PR allows to:

> Automatically insert a line break after any supported Chinese, Japanese, or Yi character in a point-placed label as needed to stay within the text-max-width. Balance the lines unless non-ideographic text such as Latin letters are present.

Possibly also a port of https://github.com/mapbox/mapbox-gl-js/pull/3438 is also needed. 

**Update**: confusion from my end, we just need to cherry pick #6828 into the release-v4.2.0 branch. Using this ticket to track it.

**Comment by 1ec5** [comment]
A port of mapbox/mapbox-gl-js#3438 is tracked in #1682. Neither #6828 nor #1682 requires any SDK work, other than to chery-pick the changes into the release branches.

**Comment by tobrun** [comment]
Commits were cherrypicked into release brach, closing.

**Comment by 1ec5** [comment]
@tobrun, #6828 has not yet landed in master. I suggest backing out the cherry-picked commits and waiting until my PR passes a code review, because it'll get rebased before merging to master.

**Comment by 1ec5** [comment]
Looks like these commits got rewritten out of the branch already. 👍 Closing.

**Comment by 1ec5** [comment]
And reopening to track the _eventual_ cherry-picking.

**Comment by jfirebaugh** [comment]
Per chat, this feature is not required for the 4.2.0 release. Closing.
