### ISSUE TITLE
[Android] Updating camera zoom sets bearing to 0

### ISSUE THREAD

**Issue by tomlocks** [mapbox/mapbox-gl-native#7001]
**Platform: Android 6.0.1**
**Mapbox SDK version: 4.2.0@beta4**

### Steps to trigger behavior

 1. Use the code below:
```
        CameraPosition cameraPosition = new CameraPosition.Builder()
                .zoom(map.getCameraPosition().zoom + 1)  // set the camera's zoom level
                .build();

        map.easeCamera(CameraUpdateFactory.newCameraPosition(cameraPosition));
```

### Expected behavior
Previous camera bearing should stay untouched.
### Actual behavior
Camera bearing is set to 0.

Edit:
I've just noticed that location tracking is dismissed after setting the camera zoom using above code. As far as I remember beta3 didn't act like that.

**Comment by tobrun** [comment]
As a workaround you can use:

```
  CameraPosition previousPosition = mapboxMap.getCameraPosition();
  CameraPosition cameraPosition = new CameraPosition.Builder(previousPosition)
                            .zoom(previousPosition.zoom + 1)  // set the camera's zoom level
                            .build();
```

Looking more into the source.

**Comment by tobrun** [comment]
Proposed fix in #7002, the defaults values were trimmed by the builder methods.

**Comment by tomlocks** [comment]
Thanks for quick response.

Is the location tracking problem also induced by the builder?

**Comment by tobrun** [comment]
No, initial guess that this comes from https://github.com/mapbox/mapbox-gl-native/pull/6569. Since that commit we aren't dismissing bearing tracking when panning the map, I'm guessing this is a side effect.

**Comment by tobrun** [comment]
Looked into it and not seeing it being reset with gesture zooming, in case of `easeCamera`, we now support al alternative method that negates resetting of location tracking.

Updating your code to a working version for beta4 is:

```java
  CameraPosition previousPosition = mapboxMap.getCameraPosition();
  CameraPosition cameraPosition = new CameraPosition.Builder(previousPosition)
                            .zoom(previousPosition.zoom + 1)  // set the camera's zoom level
                            .build();
  map.easeCamera(CameraUpdateFactory.newCameraPosition(cameraPosition),300,true,false,null);
```
