### ISSUE TITLE
[iOS] Highway shields sometimes dont render properly when map is first displayed

### ISSUE THREAD

**Issue by JesseCrocker** [mapbox/mapbox-gl-native#7003]
**Platform:**
iOS simulator, iOS 10.1

**Mapbox SDK version:**
master at https://github.com/mapbox/mapbox-gl-native/commit/d0e8ed4bc30c62b5b6894534e4cf816acb414efa

### Steps to trigger behavior

 1. Launch iosapp target
 2. Navigate map to location shown in screenshot
 3. Background to cause state to be saved
 4. Relaunch app

### Expected behavior
Map Renders properly
![screen shot 2016-11-10 at 7 09 55 am](https://cloud.githubusercontent.com/assets/2048291/20180092/320f11a8-a716-11e6-8295-f7528b3d8635.png)

### Actual behavior
Occasionally, maybe 1 out of 5 launches, the highway shield do not render. Zooming in and out causes them to render.
![screen shot 2016-11-10 at 7 05 59 am](https://cloud.githubusercontent.com/assets/2048291/20180101/3e06b18c-a716-11e6-82cf-0c43a689c91c.png)

#### Notes
Im having a hard time reproducing this one, I had the map state saved where this was happening approximately one out of 5 app launches, But it doesn't seem to happen in all locations, and after trying to get the saved state back to the location shown in the screenshot I couldn't reproduce the problem.

**Comment by JesseCrocker** [comment]
Camera position that reproduces this:
```
  camera = [MGLMapCamera cameraLookingAtCenterCoordinate:CLLocationCoordinate2DMake(36.905919, -122.125451)
                                                                    fromDistance:524659
                                                                           pitch:0
                                                                         heading:0];
```
when added to `MBXViewController -restoreState:`

**Comment by kkaefer** [comment]
Does this always happen with this camera position? Or is it a temporary flicker?

**Comment by JesseCrocker** [comment]
It's not flickering, it stays that way until the tile is re-painted, either due to zooming, or panning the tile off screen. But it doesn't always happen, it only happens about 25% of app launches
![nov-11-2016 10-26-34](https://cloud.githubusercontent.com/assets/2048291/20223991/5dd47d44-a7f9-11e6-92ed-83c7b57f1914.gif)

**Comment by jfirebaugh** [comment]
@JesseCrocker Is this still happening in 3.4.0?

**Comment by friedbunny** [comment]
Closing, but please feel free to post more information if this still occurs.
