### ISSUE TITLE
MGLStyle needs style image accessor

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7012]
MGLStyle has `-setImage:forName:` and `-removeImageForName:` methods but no `-imageForName:` method to get an existing style image. One use case would be to embed a Maki icon from Mapbox Streets into an annotation image (#4750), annotation view, or callout view.

/cc @frederoni @incanus

**Comment by rmnblm** [comment]
I just saw this issue and I'm working on it because I already implemented `-setImage:forName:` and `-removeImageForName:`, PR coming soon (might have a few questions). 👀

**Comment by 1ec5** [comment]
Fixed in #7096 on the v3.4.0 release branch.
