### ISSUE TITLE
Provide a surfaceless EGL headless backend

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#7020]
This recent [Mesa extension](https://www.khronos.org/registry/egl/extensions/MESA/EGL_MESA_platform_surfaceless.txt) - __MESA_platform_surfaceless__ - provides a native display independent of any native window system. Given this solution already works and is testable via CI, we can pursuit this as a follow-up work.

My initial tests on this were not successful - I've been building mesa with EGL surfaceless support - see https://github.com/mapbox/mason/tree/mesa-13.0.0-egl-surfaceless - and using the [example usage from the specification author](https://www.mail-archive.com/piglit@lists.freedesktop.org/msg17829.html) but so far no luck in initializing an EGL display.

Follow-up from #5843 and #7007.

/cc @mikemorris @kkaefer

**Comment by jfirebaugh** [comment]
Current implementation suffices and is stable; this doesn't seem necessary.
