### ISSUE TITLE
Mapbox crashes after calling showInfoWindow() with custom InfoWindowAdapter on Android

### ISSUE THREAD

**Issue by nkuznetsow** [mapbox/mapbox-gl-native#7022]
**Platform:** Android 4.2.2 
**Mapbox SDK version:** 4.1.1

### Steps to trigger behavior

 1. Wait for MapBox initialization
 2.  Set custom InfoWindowAdapter 
 2. Add marker
 3. Click on marker or call marker.showInfoWindow()

### Expected behavior
InfoWindow must be shown 

### Actual behavior

A/libc: Fatal signal 11 (SIGSEGV) at 0x00000023 (code=1), thread 12545

**Comment by tobrun** [comment]
Hey @nkuznetsow, thank you for reaching out and reporting your issue. 
Could you paste the full logcat output?

**Comment by nkuznetsow** [comment]
It is log:

W/System.err: java.lang.NullPointerException
W/System.err:     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:529)
W/System.err:     at android.view.View.measure(View.java:15775)
W/System.err:     at com.mapbox.mapboxsdk.annotations.InfoWindow.open(InfoWindow.java:109)
W/System.err:     at com.mapbox.mapboxsdk.annotations.Marker.showInfoWindow(Marker.java:166)
W/System.err:     at com.mapbox.mapboxsdk.annotations.Marker.showInfoWindow(Marker.java:153)
W/System.err:     at my.app.map.BaseMapActivity.showInfoWindow(BaseMapActivity.java:107)
W/System.err:     at my.app.map.BaseMapActivity$6.onFinish(BaseMapActivity.java:291)
W/System.err:     at com.mapbox.mapboxsdk.maps.MapboxMap$2.onFinish(MapboxMap.java:446)
W/System.err:     at com.mapbox.mapboxsdk.maps.MapView$4.onMapChanged(MapView.java:1253)
W/System.err:     at com.mapbox.mapboxsdk.maps.MapView.onMapChanged(MapView.java:2400)
W/System.err:     at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:481)
W/System.err:     at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
W/System.err:     at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:128)
W/System.err:     at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:1327)
W/System.err:     at android.view.View.draw(View.java:13917)
W/System.err:     at android.widget.FrameLayout.draw(FrameLayout.java:467)
W/System.err:     at android.view.View.getDisplayList(View.java:12832)
W/System.err:     at android.view.View.getHardwareLayerDisplayList(View.java:12861)
W/System.err:     at android.view.View.getHardwareLayer(View.java:12548)
W/System.err:     at android.view.View.getDisplayList(View.java:12795)
W/System.err:     at android.view.View.getDisplayList(View.java:12876)
W/System.err:     at android.view.View.draw(View.java:13621)
W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2901)
W/System.err:     at android.view.View.getDisplayList(View.java:12827)
W/System.err:     at android.view.View.getDisplayList(View.java:12876)
W/System.err:     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3019)
W/System.err:     at android.view.View.getDisplayList(View.java:12755)
W/System.err:     at android.view.View.getDisplayList(View.java:12876)
W/System.err:     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3019)
W/System.err:     at android.view.View.getDisplayList(View.java:12755)
W/System.err:     at android.view.View.getDisplayList(View.java:12876)
W/System.err:     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3019)
W/System.err:     at android.view.View.getDisplayList(View.java:12755)
W/System.err:     at android.view.View.getDisplayList(View.java:12876)
W/System.err:     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3019)
W/System.err:     at android.view.View.getDisplayList(View.java:12755)
W/System.err:     at android.view.View.getDisplayList(View.java:12876)
W/System.err:     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3019)
W/System.err:     at android.view.View.getDisplayList(View.java:12755)
W/System.err:     at android.view.View.getDisplayList(View.java:12876)
W/System.err:     at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1249)
W/System.err:     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2521)
W/System.err:     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2388)
W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2190)
W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1181)
W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4943)
W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:579)
W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:548)
W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:800)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err:     at android.os.Looper.loop(Looper.java:194)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5391)
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
W/System.err:     at dalvik.system.NativeStart.main(Native Method)
W/dalvikvm: JNI WARNING: JNI method called with exception pending
W/dalvikvm:              in Lcom/mapbox/mapboxsdk/maps/NativeMapView;.nativeRender:(J)V (CallVoidMethodV)
W/dalvikvm: Pending exception is:
A/libc: Fatal signal 11 (SIGSEGV) at 0x00000023 (code=1), thread 27762 (my.app)
A/libc: Send stop signal to pid:27762 in debugger_signal_handler 

I tried to insert my info InfoWindow layout to Activity, it working fine. Problem exists only when I try to open info window.

**Comment by nkuznetsow** [comment]
Hi. I have changed layout from RelativeLayout to LinearLayout and now it is working.

Also, I noticed that with ConstraintLayout in popup window it crashes too.

RelativeLayout and ConstraintLayout broke popup window on some devices.
