### ISSUE TITLE
removeMarker example

### ISSUE THREAD

**Issue by ANSB** [mapbox/mapbox-gl-native#7024]
Just ask a question on Stack and Cameron give the right answer (thanks a lot!). After that I suggest a **change in the example page** about markers.
On this page:
https://www.mapbox.com/help/android-markers/
we have the "Add a marker"  part with:
_MarkerViewOptions marker = new MarkerViewOptions()
        .position(new LatLng(-33.85699436, 151.21510684));
mapboxMap.addMarker(marker);_

And then we have the "Remove a marker" with:
 _Remove a single marker: call the removeMarker() method with the name of the marker you would like to remove to remove as the parameter.
mapboxMap.removeMarker(marker);_

But if you try to mix the two (so Add code + Remove code) it doesn't work because in order to Remove a maker (same as moving it) you need to have a MarkerView and not a MarkerViewOptions marker.

So I suggest to indicate this and give a "Add+Remove" small example.

**Comment by cammace** [comment]
Hey, thanks for pointing this out, I've made some slight changes to that help doc which should show up soon, mainly with the naming of variables.
