### ISSUE TITLE
Flickering labels for overzoomed tiles

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#7027]
Here's what happens:

- Step 1: previous state; all tiles at z16 are loaded
- Step 2: zoom in so that z16 tiles are overzoomed to z17. All labels vanish, since the overzoomed tiles aren't parsed/placed yet.
- Step 3: First overzoomed tile is ready
- Step 4: Two more tiles are ready
- Step 5: All overzoomed tiles are ready and all labels are visible again

What should happen is that we continue to show the non-overzoomed z16 symbols until all of the z17 tiles are available.

![zoom1](https://cloud.githubusercontent.com/assets/52399/20223647/dca51bd8-a83a-11e6-80a7-9858b3b93652.jpg)
![zoom2](https://cloud.githubusercontent.com/assets/52399/20223648/dca8f9ce-a83a-11e6-9331-dcb81715a728.jpg)
![zoom3](https://cloud.githubusercontent.com/assets/52399/20223650/dcaa454a-a83a-11e6-95b4-1c1d42ac0b8a.jpg)
![zoom4](https://cloud.githubusercontent.com/assets/52399/20223651/dcabd32e-a83a-11e6-8c70-24c6025fa17d.jpg)
![zoom5](https://cloud.githubusercontent.com/assets/52399/20223649/dca998c0-a83a-11e6-925b-244d010afacd.jpg)

**Comment by jfirebaugh** [comment]
@kkaefer This is the same underlying issue as #7026, right?

**Comment by kkaefer** [comment]
Yup

**Comment by jfirebaugh** [comment]
Closing as duplicate.
