### ISSUE TITLE
[ANDROID] MapboxMap#getLayerAs(layerId) NPE when NativeMapView is null

### ISSUE THREAD

**Issue by sddamico** [mapbox/mapbox-gl-native#7028]
**Platform:** Android
**Mapbox SDK version:** 4.2.0-beta.4

### Steps to trigger behavior

 1. Load a map style and hold a reference to the `MapboxMap` in a field
 2. Call `MapView#onDestroy()`
 3. Call `MapboxMap#getLayerAs(layerId)`

### Expected behavior
Return null or throw helpful exception

### Actual behavior
NPE

I assume this same issue occurs for other runtime styling methods as well. I only noticed this because I was animating a property of a layer and wasn't properly cancelling the animation before `onDestroy()`

**Comment by tobrun** [comment]
This issue should be resolved with https://github.com/mapbox/mapbox-gl-native/pull/7613. 
Thank you for reporting @sddamico!
