### ISSUE TITLE
Investigate dSYM size decrease between v3.3.6 and v3.4.0

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7029]
Building the iOS SDK with Xcode 8 would decrease the framework size significantly. Unfortunately, #6842 is keeping us on Xcode 7.3.

Since it’s only the dynamic framework that’s giving Xcode 7.3 users problems, I’m wondering whether we could ship an _unstripped_ dynamic framework and add code in strip-frameworks.sh to strip that framework (in addition to stripping out irrelevant architecture slices as it does now). As it is, you can’t submit to the App Store without having strip-frameworks.sh in a Run Script build phase, so this should cover anyone who needs to use the dynamic framework in a simulator that comes with Xcode 7.3.

Putting on the 3.4.0 milestone for consideration for a beta.

/cc @boundsj

**Comment by boundsj** [comment]
Here are some notes I took while investigating this a bit more yesterday

- The 3.3.x series branch, when built with Xcode 7.3.1 produces a 50 MB symbol stripped dynamic framework and a 190 MB dSYM
- The 3.3.x series branch when built with Xcode 8.0 produces a 38 MB symbol stripped dynamic framework and a 190 MB dSYM
- The latest 3.4.0 beta, built with Xcode 7.3.1 has a 49 MB symbol stripped dynamic framework and a 34.5 MB dSYM
- The latest 3.4.0 beta, built with Xcode 8.0 has a 37.5 MB symbol stripped dynamic framework and a 36.7 MB dSYM

I think we should use Xcode 8.0+ for future builds. Although we are left with the issue for Xcode 7.3.1 users.

> @1ec5 I’m wondering whether we could ship an unstripped dynamic framework and add code in strip-frameworks.sh to strip that framework

I'm not sure if I understand how to pull this off. We currently ship an unstripped  (i.e. does not have `strip -Sx` run on it) `mapbox-ios-sdk-#..3#-symbols-dynamic.zip` output that works fine in an Xcode 7.3.1 swift environment. But it would fail if we suggested stripping it in a build phase, I think. But I'm sure I'm missing something.

I'd also like to investigate the large **decrease** in dSYM size when Xcode 8.0 is used to make the build. We've gone from ~100 MB to close to 200 MB (in more recent 3.3.x version built with Xcode 7.3.1) to ~37 MB in the 3.4.0 branch using Xcode 8.0

**Comment by 1ec5** [comment]
We shipped v3.3.7 built in Xcode 8; there’s no going back to Xcode 7.3. ⏩ It’s too late in the game to try shipping an unstripped dynamic framework. Do we need to investigate the dSYM size decrease as part of this task for the v3.4.0 release?

**Comment by boundsj** [comment]
> Do we need to investigate the dSYM size decrease as part of this task for the v3.4.0 release?

At this point I'd say no (at least I would not want to block the release on this investigation). A size decrease is a good thing and we seem to be getting nicely symbolicated crash reports from the latest version.

**Comment by 1ec5** [comment]
OK, I pushed this investigation to v3.4.1.

**Comment by 1ec5** [comment]
Closing; we can reopen if we see any issues related to the size decrease.
