### ISSUE TITLE
Automatically adapt Mapbox Streets–sourced layers for user preferred language

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7031]
When a user adjusts the Preferred Language Order setting in the Language & Region section of Settings to a language supported by the Mapbox Streets source, any style based on the Mapbox Streets source should automatically adjust by localizing the labels.

MGLMapView can observe [`NSCurrentLocaleDidChangeNotification`](https://developer.apple.com/reference/foundation/nscurrentlocaledidchangenotification) and respond by obtaining [`NSLocale.autoupdatingCurrentLocale`](https://developer.apple.com/reference/foundation/nslocale/1856125-autoupdatingcurrentlocale), determining the `identifier`s of the sources whose `URL` matches `mapbox://mapbox.mapbox-streets-v*`, and replacing `{name*}` tokens in the `textField` of any MGLSymbolStyleLayer whose `sourceIdentifier` is one of those source identifiers. We already do something similar in iosapp on demand: #6819.

We could also offer a way to extend this feature to arbitrary sources, by allowing the developer to specify which fields in the source correspond to which languages (see also mapbox/mapbox-gl#21).

Iterating over all the sources and style layers will require #6097. Discovering whether a source is Mapbox Streets will require #6584. #7030 would rely on a similar mechanism.

/ref #1108
/cc @incanus @pveugen @boundsj @frederoni

**Comment by 1ec5** [comment]
We should expose a style-wide setting that allows the developer to turn automatic localization on and off (for supported sources). I think it should be on by default, for parity with MapKit and the Google Maps SDK, but there definitely needs to be a way to turn the feature off, in case the developer wants a specific language to be displayed.

**Comment by 1ec5** [comment]
Note that macosapp already performs this automatic localization, as of #6097 and #7398, so this ticket tracks upstreaming that code to the iOS and macOS SDKs.

**Comment by evgzor** [comment]
Are any estimations when the issue would be fixed?

**Comment by boundsj** [comment]
This was done in https://github.com/mapbox/mapbox-gl-native/pull/9582 on the `release-ios-v3.6.0-android-v5.1.0` branch and is expected to be in the 3.6.2 release. cc @fabian-guerra

**Comment by evgzor** [comment]
Could u please provide any estimation when 3.6.2 would be released?

**Comment by boundsj** [comment]
@evgzor patch releases for v3.6.x are going out every 2 to three weeks so it should be this week or next.

**Comment by evgzor** [comment]
@boundsj please look:

<img width="347" alt="screen shot 2017-08-28 at 13 59 34" src="https://user-images.githubusercontent.com/5227456/29770781-3cf2f076-8bf9-11e7-8ad5-80386b337329.png">

Localization still does not work on iOS.

**Comment by fabian-guerra** [comment]
Hi @evgzor did you set `mapView.style.localizesLabels` to `YES`?

![localize](https://user-images.githubusercontent.com/2745166/29773672-6f09e146-8bcc-11e7-877e-096f1674b5b9.png)

**Comment by friedbunny** [comment]
> did you set `mapView.style.localizesLabels` to `YES`?

Additionally, this should be done in `-[MGLMapViewDelegate mapView:didFinishLoadingStyle:]` or later.

**Comment by evgzor** [comment]
@friedbunny @fabian-guerra on iOS all good but on Android Mapbox 5.1.3 still an issue: 
![device-2017-09-01-134409](https://user-images.githubusercontent.com/5227456/29966737-e97109e4-8f1b-11e7-99e2-c0eff0b5af7c.png)
Could u help me and tell what could be wrong?

**Comment by Guardiola31337** [comment]
Hey @evgzor 👋

That feature is not included in the Android binding and the idea to cover that functionality is implementing it as a plugin.
👀 https://github.com/mapbox/mapbox-plugins-android/issues/36

That ticket is still opened so in the meantime you could do it manually:
- Listen to `locale` config changes 👀 [`android:configChanges`](https://developer.android.com/guide/topics/manifest/activity-element.html#config)
- Get the current language in device
```java
Locale.getDefault().getDisplayLanguage();
```
- Change label language dynamically
```java
Layer mapText = map.getLayer("place-city-lg-n");
mapText.setProperties(textField("{name_ru}"));
```

If you know the language in advance you could directly change label language as shown above ☝️ 

For further information check [Change your map’s label language](https://www.mapbox.com/help/change-language/) and the [language switch example](https://github.com/mapbox/mapbox-android-demo/blob/72f1f41346bb34dd300375ef2760a0778a54d757/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/LanguageSwitchActivity.java).

Contributions are more than welcome so I encourage you to take a stab at https://github.com/mapbox/mapbox-plugins-android/issues/36 and send a PR fixing it (follow the steps mentioned above) 😛 

Thanks Eugene!
