### ISSUE TITLE
Map Box static Maps with annotation

### ISSUE THREAD

**Issue by aish504** [mapbox/mapbox-gl-native#7038]
Hey Map Box,
                   I am using MapBox static maps in my App, is there any possibility that I can get the static maps with annotation. 

Cheers,
Aish

**Comment by jfirebaugh** [comment]
Hi @aish504, this is the issue tracker for mapbox-gl-native, for reporting bugs and requesting features. Please direct support requests to https://www.mapbox.com/help/.
