### ISSUE TITLE
[iOS][BUG] Bounds/cameras animations unreliable 

### ISSUE THREAD

**Issue by naluhh** [mapbox/mapbox-gl-native#7043]
Doing a transition when you are far from the destination make a weird result

Reproducible with both:
[MGLMapCamera cameraLookingAtCenterCoordinate..]
[mapView setCenterCoordinate.. animated:YES]

![animation](https://cloud.githubusercontent.com/assets/4512251/20267731/5ae3b6ec-aa7c-11e6-9c9a-1b9a3a55757b.gif)

**Comment by boundsj** [comment]
Hi @naluhh can you please say the Mapbox iOS SDK version you are using? Also, it is not clear to me from the gif what the exact issue is (although I do agree it looks weird). Can you please provide more details / code sample and explain exactly what you are expecting and exactly what is wrong?

**Comment by naluhh** [comment]
Sorry the framerate of the gif is really low that's why. Basically I animate to the position of the Annotation, . I've tried on both master and v 3.4.0.

It always do a weird transition when you animate from a low level zoom to an high level zoom

**Comment by boundsj** [comment]
Thanks for the additional details @naluhh

**Comment by jfirebaugh** [comment]
@naluhh Could you provide a fully-fleshed out code sample that triggers the issue?

**Comment by jfirebaugh** [comment]
We'll need a more detailed description of the code involved here, ideally in the form of a sample application. Please reopen if you can provide this information. Thanks!
