### ISSUE TITLE
Removing of  markers not works but why?

### ISSUE THREAD

**Issue by 4BooM04** [mapbox/mapbox-gl-native#7046]
**Platform:** Android 
**Mapbox SDK version:** 4.2.0-beta.4

### Steps to trigger behavior

 1. Add markers to the map
 2. Get list of markers from the map
 3. Try to remove this list or some of markers from list  throw removeMarker/removeAnnotation/s

### Expected behavior
markers will delete from map
### Actual behavior
markers not deleted

only works mapView.clear();

**Comment by 4BooM04** [comment]
maybe i'm wrong but map not cleared markers when trying to remove them

**Comment by tobrun** [comment]
Are you using MarkerView or Marker subclass? 
In case of the former, you should be using `MarkerViewManager#removeMarkerView(MarkerView markerView)`. You can get a reference to MarkerViewManager from MapboxMap by calling `MapboxMap#getMarkerViewManager()`.

**Comment by 4BooM04** [comment]
I was using Markers added throw map.addMarker, and after that i changed id of marker so thats why it doesn't work. So i realy don't know is id need to be updated in the map system when you set new id of marker

**Comment by tobrun** [comment]
We internally use those IDs for housekeeping internally. You are not allowed to change these. closing as source of issue has been identified.

**Comment by 4BooM04** [comment]
thanks
