### ISSUE TITLE
Cherry pick 7025

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#7050]
https://github.com/mapbox/mapbox-gl-native/pull/7025

This PR fixes flickering of symbol layers.

cc @kkaefer @boundsj

**Comment by boundsj** [comment]
This will be fixed by https://github.com/mapbox/mapbox-gl-native/pull/7049

**Comment by boundsj** [comment]
Fixed https://github.com/mapbox/mapbox-gl-native/pull/7049
