### ISSUE TITLE
Random gray screen in onMapReady

### ISSUE THREAD

**Issue by lcerveau** [mapbox/mapbox-gl-native#7055]
When calling mapboxMap.animateCamera(CameraUpdateFactory.newLatLngZoom(LATLNG, 18f)) in the onMapReady method, there can be a random gray screen. It can however be workarounded using mapboxMap.setCameraPosition(new CameraPosition.Builder().target(LATLNG).zoom(18).build());

**Platform:**
Android
**Mapbox SDK version:**

**Comment by cammace** [comment]
`animateCamera` has a default animation of 1 second. If you want to instantly move the camera instead of animating or easing, you need to use `setCameraPosition` or `moveCamera`. Please reach out through [our contact page](https://www.mapbox.com/contact/) if you have any additional questions.
