### ISSUE TITLE
Possible improper selection of marker

### ISSUE THREAD

**Issue by lcerveau** [mapbox/mapbox-gl-native#7057]
In 
mapbox-gl-native/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java

In selectMarker independantly of what is returned by onMarkerClickListener.onMarkerClick(marker), the marker is added to the list of selectedMarker. 
This issue may be covered by https://github.com/mapbox/mapbox-gl-native/issues/3176

**Platform:**
Android
**Mapbox SDK version:**

### Steps to trigger behavior

 1.
 2.
 3.

**Comment by cammace** [comment]
This issue should indeed be covered by https://github.com/mapbox/mapbox-gl-native/issues/3176. Thanks for reporting though.
