### ISSUE TITLE
When doing a Pinch To Zoom Out movement, a rotation can occur

### ISSUE THREAD

**Issue by lcerveau** [mapbox/mapbox-gl-native#7058]
On Android platform, when pinching to zoom out, as fingers are getting further from each others a rotation movement can appear

**Platform:**
Android
**Mapbox SDK version:**

### Steps to trigger behavior

 1.
 2.
 3.

**Comment by cammace** [comment]
This issue is being tracked in https://github.com/mapbox/mapbox-gl-native/issues/6870. Closing
