### ISSUE TITLE
Add submodules pull to make

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#706]
We keep seeing people miss the submodules step when building a freshly cloned repo.

Perhaps we should just add the submodules init commands to the Makefile?

(Follow up after I messed #704) /cc @ljbade

**Comment by ljbade** [comment]
We now checkout the styles automatically: https://github.com/mapbox/mapbox-gl-native/commit/329f617ae84bea17cfaa7247d0450d4ec966dd2c

**Comment by incanus** [comment]
We are also doing `SMCalloutView` (for iOS callouts) and, in the https://github.com/mapbox/mapbox-gl-native/pull/1168 PR, `KIF` for integration testing. Once the latter lands, we should just [consolidate all of these](https://github.com/mapbox/mapbox-gl-native/blob/62d780103b4bc6fe78bd754f7fb9141ead1a0dd6/Makefile#L25-L32).

**Comment by jfirebaugh** [comment]
Doesn't seem like this is much of an issue now that we've reduced the number of submodules. I believe the current submodules will be initialized automatically.
