### ISSUE TITLE
.mbtiles format file loading in Android Mapbox maps

### ISSUE THREAD

**Issue by naveenorem** [mapbox/mapbox-gl-native#7064]
I've been trying to load ".mbtiles" format file in Mapbox MapView for offline maps in Android using "4.2.0 beta 4" version of the dependency.

Can someone guide me how to do that ?

I'm downloading this ".mbtiles" file from the URL .

**Comment by jfirebaugh** [comment]
.mbtiles format is not supported for offline. See https://www.mapbox.com/help/mobile-offline/ for documentation of offline.
