### ISSUE TITLE
Marker Views occasionally not showing up until a gesture occurs

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#7072]
![ezgif com-video-to-gif 2](https://cloud.githubusercontent.com/assets/5652865/20314434/7dfa44b4-ab5a-11e6-8def-c6dc273602d6.gif)

cc: @mapbox/android

**Comment by tobrun** [comment]
It seems that `queryPointAnnotations` is not returning the recently added marker yet.

**Comment by tobrun** [comment]
closing in favor of #7074 which is the source of this issue.
