### ISSUE TITLE
make clean does not remove node-modules

### ISSUE THREAD

**Issue by Phrogz** [mapbox/mapbox-gl-native#7073]
**Platform:** Xubuntu 14.04 x64
**Mapbox SDK version:** Cloned from master

### Steps to trigger behavior

 1. Clone repo
 2. `cd mapbox-gl-native`
 3. `make qt-qml-app`
 4. `make clean`

### Expected behavior
Repo is returned to pristine clone state

### Actual behavior
`node-modules` directory left populated

**Comment by mikemorris** [comment]
`node-modules` is removed with [`make distclean`](https://github.com/mapbox/mapbox-gl-native/blob/master/Makefile#L559)

**Comment by jfirebaugh** [comment]
Yes, this is the intended behavior: `make clean` removes build output, `make distclean` removes build output plus cached dependencies.

**Comment by Phrogz** [comment]
Thank you :)
