### ISSUE TITLE
queryPointAnnottions don't return recently added PointAnnotations

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#7074]
When looking into https://github.com/mapbox/mapbox-gl-native/issues/7072, I noticed that a recently added point annotation isn't returned as a result of queryPointAnnotations.

What I do is add a point annotation to the map and almost immediately execute a query with:

```
nativeMapView.queryPointAnnotations(rect)
```

This currently results in returning 0 annotations, 
if I delay this action this results in returning 1 annotation. 

cc @brunoabinader

**Comment by jfirebaugh** [comment]
Pretty sure this is expected behavior. `queryPointAnnotations` relies on `queryRenderedFeatures`, and a point annotation isn't rendered until it has a chance to pass through the worker layout step, which is an asynchronous operation.

**Comment by tobrun** [comment]
Thank you for explanation, makes sense that the marker will not show up until they are actually rendered. I'm converting this issue to an `android`-`docs` issue.

**Comment by tobrun** [comment]
Changing this to the 4.2.0 milestone since this behavior affects our examples and code we have been using so far in relation to MarkerView.  

We used to be able to:

```java
MarkerView markerView = mapboxMap.addMarker(markerViewOptions);
View view = markerViewManager.getView(markerView);
```

And the returned View wouldn't be null if the MarkerView was found in the current Viewport. With above described behavior the user needs to wait since adding one is a asynchronous operation. To make this easier for integrating I'm providing an additional `addMarker` method with a callback interface that is invoked when `getView()` wouldn't return null anymore. This would end up in using an API as:

```java
createCarMarker(getLatLngInBounds(), R.drawable.ic_car_top, new MarkerViewManager.OnMarkerViewAddedListener(){
      @Override
      public void onViewAdded(@NonNull MarkerView markerView) {
          randomlyMoveMarker(markerView);
      }
});
```
Besides above we need tests for regressions and an update to documentation around the asynchronous behavior of adding markers for the `4.2.0-release`.

**Comment by tobrun** [comment]
Related PR for this has landed on release branch, closing
