### ISSUE TITLE
Cannot find node-cmake when building qt-qml-app

### ISSUE THREAD

**Issue by Phrogz** [mapbox/mapbox-gl-native#7076]
**Platform:** Xubuntu 14.04 x64
**Mapbox SDK version:** f7db6cf7601e5d97492622cab76ed38ce692b37c

### Steps to trigger behavior

 1. Clone https://github.com/mapbox/mapbox-gl-native/commit/f7db6cf7601e5d97492622cab76ed38ce692b37c
 2. `make qt-qml-app`

### Expected behavior
Successful compilation.

### Actual behavior
```
CMake Error at cmake/mbgl.cmake:16 (message):
  Can't find node-cmake
```

`npm update` does not appear to be installing `node-cmake`.
If I install it manually via `npm install node-cmake`, it has a `NodeJS.cmake` file, but no `FindNodeJS.cmake` file.

Full transcript can be found here: https://gist.github.com/Phrogz/079c45bc73ea536176f21d0e6f48e7a0

---

This is almost a duplicate of Issue #6847, except that applies to Linux, not Android. And, I believe that the repro steps are simple :)

**Comment by Phrogz** [comment]
This is almost a duplicate of Issue #6847, except that applies to Linux, not Android.

**Comment by jfirebaugh** [comment]
Node 4.2.1 or later is required. I've opened #7081 to document this explicitly.

**Comment by Phrogz** [comment]
Thanks @jfirebaugh, upgrading Node got me one step farther in the build process.
