### ISSUE TITLE
[Feature] [core] Scale GL annotations

### ISSUE THREAD

**Issue by chronos83** [mapbox/mapbox-gl-native#7077]
Add scale ability to marker annotations, to for example, update the marker's size on zoom level changes

**Comment by cammace** [comment]
On Android using the latest `beta.5` you can add a symbol layer that displays markers (see [this example](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/SymbolLayerActivity.java)) and use the `zoom` method to change the icon size depending on the zoom level (see [this example](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/ZoomDependentFillColorActivity.java#L48-L53)) Not sure if we want to add support for this on the core side.

**Comment by chronos83** [comment]
Thank you for your answer ! I will try that soon.
