### ISSUE TITLE
Building qt-qml-app fails attempting to download mason

### ISSUE THREAD

**Issue by Phrogz** [mapbox/mapbox-gl-native#7085]
**Platform:** Ubuntu 14.04 x64
**Mapbox SDK version:** f7db6cf7601e5d97492622cab76ed38ce692b37c

### Steps to trigger behavior

 1. Clone f7db6cf7601e5d97492622cab76ed38ce692b37c
 2. `make qt-qml-app`

### Expected behavior
Successful build

### Actual behavior

```
...
-- Found NodeJS: node.js linux/x64 (found version "6.9.1") 
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/headers/geometry/0.8.0.tar.gz...
CMake Error at .mason/mason.cmake:118 (message):
  [Mason] Failed to download
  https://mason-binaries.s3.amazonaws.com/headers/geometry/0.8.0.tar.gz:
  curl: (35) Unknown SSL protocol error in connection to
  mason-binaries.s3.amazonaws.com:443

Call Stack (most recent call first):
  CMakeLists.txt:35 (mason_use)
```

Trying to fetch `https://mason-binaries.s3.amazonaws.com` from multiple Internet connections and OS all result in 443 (Access Denied).

**Comment by jfirebaugh** [comment]
`https://mason-binaries.s3.amazonaws.com` isn't publicly listable, but `https://mason-binaries.s3.amazonaws.com/headers/geometry/0.8.0.tar.gz` is. Can you visit that URL in a browser?

**Comment by Phrogz** [comment]
@jfirebaugh Yes, I am able to download that particular file successfully.

**Comment by Phrogz** [comment]
Uh...now the build is successfully downloading all the files. Perhaps just a temporary Amazon S3 problem? I guess we can close this bug?

(And now I'll open a new bug for the next failure in the build process. Thanks for your patience.)
