### ISSUE TITLE
My Location indicator does not get tilted

### ISSUE THREAD

**Issue by ahuang13** [mapbox/mapbox-gl-native#7086]
Tilting the map does not immediately tilt the My Location blue dot indicator. (However, tilting the map a second time will then cause the My Location indicator to get tilted.)

**Platform:** Android
**Mapbox SDK version:** `4.2.0-beta.5`

### Steps to trigger behavior

 0. Start out with map showing the My Location indicator.

![device-2016-11-15-161227](https://cloud.githubusercontent.com/assets/2015033/20329935/35905772-ab50-11e6-84fe-3abe151bf1a4.png)

 1. Tilt the map by calling the following `tiltCamera()` method.
```
private void tiltCamera() {
    final CameraPosition cameraPosition = new CameraPosition.Builder().tilt(MapboxConstants.MAXIMUM_TILT).build();
    final CameraUpdate cameraUpdate = CameraUpdateFactory.newCameraPosition(cameraPosition);
    mMapboxMap.moveCamera(cameraUpdate);
}
```
### Expected behavior
I expect both the map and the My Location indicator to be tilted as such... (note that calling `tiltCamera()` a second time will achieve this result.)

![device-2016-11-15-161248](https://cloud.githubusercontent.com/assets/2015033/20329960/5329e7f8-ab50-11e6-8a33-ba5a29052112.png)

### Actual behavior
Only the map gets tilted. The My Location indicator remains in its original perspective as seen here...

![device-2016-11-15-161239](https://cloud.githubusercontent.com/assets/2015033/20329976/6945a860-ab50-11e6-977b-3899a7e04b0b.png)

**Comment by ahuang13** [comment]
I noticed that this happens with all of the below camera methods...

- `moveCamera(CameraUpdate)`
- `easeCamera(CameraUpdate)`
- `animateCamera(CameraUpdate)`

However, when I add a sufficiently long duration (~1 second or more) to `easeCamera(...)` and `animateCamera(...)`, the My Location indicator will get tilted.

**Comment by tobrun** [comment]
Thank you for the detailed explanation @ahuang13. It seems that setting tilt while out of screen is not getting applied. Tilt isn't changed as part of `onDraw` and is only set when we explicitly call `setTilt`.
