### ISSUE TITLE
How to run iOS sample project?

### ISSUE THREAD

**Issue by hashemp206** [mapbox/mapbox-gl-native#7090]
I can't run MapBoxGL iOS sample project!

<img width="262" alt="screen shot 2016-11-16 at 4 25 23 pm" src="https://cloud.githubusercontent.com/assets/3206748/20348132/4faeec1c-ac19-11e6-8719-ee703b82aa38.png">

It seems mapbox gl xcode project is missing. how can I resolve that?

**Comment by kkaefer** [comment]
If you're developing on mapbox-gl-native, please follow the instructions here: https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md

If you want to integrate Mapbox GL into your own app, you don't need to download this project at all. Instead, please follow the instructions in https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/INSTALL.md

**Comment by hashemp206** [comment]
thanks for help. I have followed those instructions but no chance!!

I have cloned the project.  and in terminal I have entered `cd: /path to/MapBoxGL/mapbox-gl-native/platform/ios` the I have typed: `make iproj` but I got error `make: *** No rule to make target `iproj'.  Stop.`

would you mind to explain more? or a simple and fast step by step instruction.

**Comment by kkaefer** [comment]
you'll have to to run `make iproj` from the root folder

**Comment by hashemp206** [comment]
thanks for hint, I installed CMake, but I encountered error: `/bin/sh: cmake: command not found`
also I used CMake GUI, but I faced some issues:
<img width="693" alt="screen shot 2016-11-16 at 6 13 48 pm" src="https://cloud.githubusercontent.com/assets/3206748/20351566/a5776282-ac28-11e6-9a56-3fbddfee87e8.png">

I think building this sample app is too complicated! I want to modify the source code to fix some issues I face in the SDK

**Comment by kkaefer** [comment]
How did you install `cmake`? It works best when installed with Hombrew (`brew install cmake`) so it'll be available system-wide. This project needs `cmake` as a command line and using CMake GUI isn't officially supported. Also note that spaces in the build path (`Xcode Projects`) aren't supported either.

**Comment by kkaefer** [comment]
You're also welcome to create tickets with the issues you're seeing on this repository.

**Comment by kkaefer** [comment]
Did you follow the guide in https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md that is linked as the first step in https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md?

**Comment by hashemp206** [comment]
Yes I've seen those instruction.  but didn't lead me to a runnable project!

thanks, I installed CMake via homebrew, 
but another error appeared:
what should I do?

<img width="898" alt="screen shot 2016-11-16 at 7 22 08 pm" src="https://cloud.githubusercontent.com/assets/3206748/20354022/0bd98830-ac32-11e6-9f6a-efd6d19468fa.png">

**Comment by kkaefer** [comment]
There are spaces in your directory. Try moving the project to a directory that doesn't include any space either in the hard drive name (`Hashem HD`) or directories (`Xcode Projects`).

**Comment by hashemp206** [comment]
thanks it worked well, but I saw this error too!
<img width="1135" alt="screen shot 2016-11-16 at 7 41 41 pm" src="https://cloud.githubusercontent.com/assets/3206748/20355526/d380a78e-ac36-11e6-9bab-56689ebbbd80.png">

however I just deleted setting bundle!
