### ISSUE TITLE
Build QML app using QQuickMapboxGL plugin as precompiled library

### ISSUE THREAD

**Issue by Phrogz** [mapbox/mapbox-gl-native#7099]
**Platform:** Xubuntu 14.04 x64
**Mapbox SDK version:** f7db6cf7601e5d97492622cab76ed38ce692b37c

### Steps to trigger behavior

 1. Clone f7db6cf7601e5d97492622cab76ed38ce692b37c
 2. `make qt-qml-app` in Release mode
 3. In `platform/qt/qmlapp` add the one directory and two files described in [this gist](https://gist.github.com/Phrogz/5096b53ee08173ee3eca59805e48fe29)
 4. Copy `libqmapboxgl.so` from `build/<platform>/Release` to `/platform/qt/qmlapp/QQuickMapboxGL/` 
 5. Modify `platform/qt/qmlapp/main.cpp` to remove explicit inclusion of the Mapbox code via [this patch](https://gist.github.com/Phrogz/7a924fa7996c4a836d3d6b3349264c38). (It just removes the lines for `#include <QMapbox>` and `QMapbox::registerTypes();`.)
 6. Open `MapApp.pro` in Qt Creator; ensure that the Kit used by Qt uses the same version of g++ and same Qt libraries as were used to compile the plugin in step 2.
 7. In the Projects/Build Settings/Release/Build Steps/Make section of Qt Creator, click the Details button and add the Make argument `install`.
 8. Switch the project to Release and build
    * _This creates an `install` directory as a sibling of `qmlapp`._
 9. In `platform/qt/install` run `./MapApp`.

### Expected behavior
The qt-qml-app application runs and launches, resolving `import QQuickMapboxGL 1.0` in `main.qml` to correctly load the MapboxGL plugin.

### Actual behavior
```
QQmlApplicationEngine failed to load component
qrc:/main.qml:8 plugin cannot be loaded for module "QQuickMapboxGL": Plugin verification data mismatch in '/var/git/mapbox-gl-native/platform/qt/install/QQuickMapboxGL/libqmapboxgl.so'
```

---

Per step 6, I have ensured that:
* I used the same version of g++ for both compilations: `g++-5 (Ubuntu 5.4.1-2ubuntu1~14.04) 5.4.1 20160904`
* I used the same Qt install for both compilations (5.7.0)
* I built both the plugin and Qt in Release

To be clear, I don't need the above steps to work exactly. What I want/need is to be able to precompile `libqmapboxgl.so` and then include it in another QML application without requiring the full mapbox-gl-native project to be cloned as a submodule.

---

If I add `Q_PLUGIN_METADATA(IID "com.mapbox.QQuickMapboxGL")` at line 22 of `platform/qt/src/qquickmapboxgl.hpp` (per [the second comment on this bug](https://bugreports.qt.io/browse/QTCREATORBUG-8500?focusedCommentId=194959&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-194959)) then I get new and exciting errors:

```
QQmlApplicationEngine failed to load component
qrc:/main.qml:8 plugin cannot be loaded for module "QQuickMapboxGL": Module loaded for URI '' does not implement QQmlTypesExtensionInterface
```

**Comment by Phrogz** [comment]
Note: was able to workaround this by:

* Adding the header files for MapboxGL to my project
* In `main.cpp`:
  * `#include "3rdparty/mapbox-gl-native/platform/qt/include/qmapbox.hpp"`
  * `QMapbox::registerTypes();` (inside `main`)
* Copying `libmapboxgl.so` (built via make/cmake) to my project
* In my QML code:
  * `import QQuickMapboxGL 1.0` and then use `MapboxMap`
* In `myproject.pro`:
  * `LIBS += -L/abs/path/to/libs -lqmapboxgl`
* Copying the `libmapboxgl.so` file somewhere that is referenced by `LD_LIBRARY_PATH`

**Comment by brunoabinader** [comment]
> However, I'd far prefer a real QML plugin that I can load without requiring the header files.

This is what we are currently working together with the Qt company - you can track progress here:
https://codereview.qt-project.org/#/c/177175
