### ISSUE TITLE
Newly added MarkerViews are not visible immediately

### ISSUE THREAD

**Issue by tomlocks** [mapbox/mapbox-gl-native#7101]
**Platform: Android 6.0.1**
**Mapbox SDK version: 4.2.0beta5**

### Steps to trigger behavior

 1. Use BasicMarkerViewActivity from MapboxAndroidDemo.
 2. Simulate some delay in onMapReady, something like that:
```
    mapView.getMapAsync(new OnMapReadyCallback() {
      @Override
      public void onMapReady(final MapboxMap mapboxMap) {
        Handler h = new Handler();
        h.postDelayed(new Runnable() {
          @Override
          public void run() {
            IconFactory iconFactory = IconFactory.getInstance(BasicMarkerViewActivity.this);
            Drawable iconDrawable = ContextCompat.getDrawable(BasicMarkerViewActivity.this, R.drawable.purple_marker);
            Icon icon = iconFactory.fromDrawable(iconDrawable);

            // marker view using all the different options available
            final MarkerView markerView = mapboxMap.addMarker(new MarkerViewOptions()
                    .position(new LatLng(-37.822829, 144.981842))
                    .icon(icon)
                    .rotation(90)
                    .anchor(0.5f, 0.5f)
                    .alpha(0.5f)
                    .title("Hisense Arena")
                    .snippet("Olympic Blvd, Melbourne VIC 3001, Australia")
                    .infoWindowAnchor(0.5f, 0.5f)
                    .flat(true));

          }
        }, 2000);

      }
    });
```
 3. In above example, wait 2 seconds.

### Expected behavior
MarkerView should appear on the map after 2 seconds.
### Actual behavior
MarkerView appears on the map after camera change.

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/9156700/20388053/6540a1c4-acc3-11e6-94ae-a1d0d4df9873.gif)

**Comment by tobrun** [comment]
@tomlocks 
thank you for the write up, we noticed this in https://github.com/mapbox/mapbox-gl-native/issues/7072 and I'm working on a fix in https://github.com/mapbox/mapbox-gl-native/pull/7075. Closing as duplicate and thank you again for testing and reporting!
