### ISSUE TITLE
Please clarify ToS and plans/pricing

### ISSUE THREAD

**Issue by timautin** [mapbox/mapbox-gl-native#7102]
Don't know if this is the correct place, sorry if it's not.

I'm evaluating the possibility to switch to MapBox for my mobile app (Android, iOS being under development), but when reading plans/pricing and ToS, some fundamental questions comes to my mind:
- my app is available in free (with ads) and pro ($4.99) version. Is it considered as a paid app (do I need the premium plan)? On iOS there will be only one version with ads and an in-app purchase to remove them.
- are the SDKs free if we don't use your maps?
- do we need an access token if we don't use your maps?
- will the SDK send usage and location data if we don't use your maps?
- is it possible to disable by default that data sending?

Thanks

**Comment by cammace** [comment]
For pricing details, the best place to reach out would be [our contact page](https://www.mapbox.com/contact/). To briefly answer your questions:

- my app is available in free (with ads) and pro ($4.99) version. Is it considered as a paid app (do I need the premium plan)? On iOS there will be only one version with ads and an in-app purchase to remove them.
Please reach out to our sales team on this one.
- are the SDKs free if we don't use your maps?
The SDKs just expose the tools for you to include in your application. Depending on the API you are calling (whether that be maps or directions) you get charged after so many. Please refer to our [pricing page](https://www.mapbox.com/pricing/) for exact numbers. 
- do we need an access token if we don't use your maps?
You'll need an access token to hit any of our APIs
- will the SDK send usage and location data if we don't use your maps?
Can you clairify on what you mean by don't use our maps when contacting us through our website? Does this mean our styles?
- is it possible to disable by default that data sending?
Data is a broad term, do you mean telemetry? Users can disable it individually but you cannot disable it in code.

**Comment by timautin** [comment]
Thanks. I contacted the sales team for the 1st question.

By "not using your maps", I mean using the MapBox SDK to display only (for instance) OSM map (from http://{a|b|c}.tile.openstreetmap.org/{z}/{x}/{y}.png). Or to display my own vector source, with my own vector style. On this page: https://github.com/mapbox/mapbox-gl-native/issues/2996, I see that no access token should be needed for that usage, is this still the case?

For the two last questions, yes I was referring to telemetry. Does the SDK sends telemetry data when we display (for instance) OSM maps?

**Comment by fukemy** [comment]
hmm. i think it's not free, even load OSM map, when u call some action like put a marker, or zoom map, change camera, set center,.... i will count map download, .... then u need pay price for it
