### ISSUE TITLE
[feature] [core] SVG rendering output?

### ISSUE THREAD

**Issue by muesliq** [mapbox/mapbox-gl-native#7108]
Would it be possible to have Mapbox GL Native draw results as SVGs instead of raster?

Ideally SVGs would come layered (layers from stylesheet) to support editing in Adobe Illustrator or Inkscape.

**Comment by jfirebaugh** [comment]
The rendering models of GL and SVG are quite different, meaning this would amount to a reimplementation of most of the layout and rendering pipeline: essentially a separate renderer altogether. It's outside the scope of the project for the foreseeable future.

**Comment by muesliq** [comment]
Thanks!
