### ISSUE TITLE
setCameraPosition not working in Android 4.2.0-beta.5

### ISSUE THREAD

**Issue by vanshg** [mapbox/mapbox-gl-native#7113]
The line `map.setCameraPosition(new CameraPosition.Builder().target(new LatLng(coordinate.getLatitude(),coordinate.getLongitude())).build());` works in version 4.2.0-beta.4. When I upgrade to beta.5, it just takes me to the middle of the ocean, every time. Doesn't seem like correct behavior.

**Comment by vanshg** [comment]
To clarify, this bug appeared in beta.5. The line of code I posted above works in beta.4

**Comment by tobrun** [comment]
@vanshg thank you for testing, I did a test locally here with:

```java
mapboxMap.setCameraPosition(new CameraPosition.Builder().target(new LatLng(52.371206, 4.897147)).build());
```

And I'm seeing the Camera changing correctly to Amsterdam:

![device-2016-11-18-090819](https://cloud.githubusercontent.com/assets/2151639/20423080/9357a624-ad6e-11e6-8f4b-db41fa8832ac.png)


Do you have anymore information how we can reproduce this?

**Comment by vanshg** [comment]
I moved that line from the beginning of my onMapReady to the end, and it seemed to fix the issue. Not sure why it was happening or what the bug was (since it was reproducibly working in beta 4, and not in beta 5)
