### ISSUE TITLE
Showing 2 mapview at once, second mapview cannot rotate by finger

### ISSUE THREAD

**Issue by kochizufan** [mapbox/mapbox-gl-native#7115]
**Platform:Android (using via Xamarin binding**
**Mapbox SDK version:4.1.1.1**

### Steps to trigger behavior

 1. Put two mapview in same activity
 2. Launch the app
 3. On Second mapview, try to rotate map by two-finger-rotation

### Expected behavior

The map in both mapview can rotate by finger.

### Actual behavior

Map in second mapview cannot rotate by finger (First mapview works well).

**Comment by tobrun** [comment]
This was fixed in the 4.2.0 release, see gif below.

![ezgif com-video-to-gif 6](https://cloud.githubusercontent.com/assets/2151639/21382616/ef335e40-c761-11e6-9186-edca99b5670d.gif)

Closing
