### ISSUE TITLE
Marker is overlapped by a layer

### ISSUE THREAD

**Issue by s3r6** [mapbox/mapbox-gl-native#7117]
**Platform: Android 4.4.4**
**Mapbox SDK version:4.2.0 beta 3**

### Steps to trigger behavior

 1. Add raster layer [like in demo](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/AddWmsSourceActivity.java) but without `before` param and call `getMapAsync` after `onCreate`, e.g. by clicking on button
 2. Place a simple marker as it will appear over the added layer

### Expected behavior
Marker is shown over the layer

### Actual behavior
Marker is under the layer and you can see it if added layer if semi-transparent. Newly added markers appear under layer too. Marker callouts appear over the layer. "My location" marker (green) is shown correctly. No matter markers are customized or not.
![_004](https://cloud.githubusercontent.com/assets/4716175/20427743/da65c14c-ad9e-11e6-8119-e6af5b93a862.png)
![_003](https://cloud.githubusercontent.com/assets/4716175/20427744/da69da5c-ad9e-11e6-9088-50ac55201c4a.png)

**Comment by tobrun** [comment]
@s3r6 can you show elaborate how you are adding the raster layer? 


Note that their is a addLayer that alllows you to add a layer behind another one:

```java
/**
     * Inserts a new layer below another layer. The layer must be newly created and not added to the map before
     * <p>
     * Layer identifiers are not guaranteed to exist across styles or different versions of the
     * same style. Applications that use this API must set the style URL to an explicitly versioned
     * style either by passing in the URL String using {@link MapboxMapOptions#styleUrl(String)} or
     * setting through XML using {@link com.mapbox.mapboxsdk.R.attr#style_url}. This approach
     * also avoids layer identifier name changes that will occur in the default style’s layers over
     * time. These default styles can be found in the {@link Style} class.
     * </p>
     *
     * @param layer  a {@link Layer} to be added to map style.
     * @param before a String layer identifier that's already found in the map view style. If the
     *               layer is not found in the current map style the layer will be added to the top
     *               of the map.
     */
    @UiThread
    public void addLayer(@NonNull Layer layer, String before) {
        getMapView().getNativeMapView().addLayer(layer, before);
    }
```

The String id used by annotations = `const std::string AnnotationManager::PointLayerID = "com.mapbox.annotations.points";`

**Comment by s3r6** [comment]
I am adding it without `before`, the code is exact as in demo only without that param. I am using custom map style with the only raster backgroud and no layers I can add the layer before. 

If to use `mapbox:style_url="mapbox://styles/mapbox/light-v9"` and add `before` like `mapboxMap.addLayer(webMapLayer, "aeroway-taxiway");` the marker is shown correctly.

**Comment by tobrun** [comment]
Can you paste your style.json? normally the annotationManager is updated with the style in `AnnotationManager::updateStyle`. This is the place where we add the annotation on top of the style. 

A couple of workaounds:
- use SymbolLayer, an example of this can be found [here](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/SymbolLayerActivity.java).
- use a MarkerView, which works similar to the user location indicator

**Comment by s3r6** [comment]
```json
{
  "version": 8,
  "name": "2gis tiles",
  "sources": {
    "2gisStreetsLayer": {
      "type": "raster",
      "tiles": [
        "http://tile0.maps.2gis.com/tiles?x={x}&y={y}&z={z}&v=1"
      ],
      "tileSize": 256
    }
  },
  "layers": [
    {
      "id": "noTilesBackground",
      "type": "background",
      "paint": {
        "background-color": "#9AB3D2"
      }
    },
    {
      "id": "2gisStreetsLayer",
      "type": "raster",
      "source": "2gisStreetsLayer",
      "paint": {
        "raster-fade-duration": 100
      }
    }
  ]
}
```

As quick solution I'm trying adding layers `onCreate` and toggling visibility later.
