### ISSUE TITLE
-[MGLMapViewDelegate mapView: regionDidChangeAnimated:] redundant calls

### ISSUE THREAD

**Issue by andrewstay** [mapbox/mapbox-gl-native#7119]
**Platform:** iOS
**Mapbox SDK version:** ios-v3.4.0-beta.2

### Steps to trigger behavior
`-[MGLMapViewDelegate mapView: regionDidChangeAnimated:]` method is called every time a bounds is set, even if the bounds is the same as before.

 1. Implement delegate's method as following:
```
- (void)mapView:(MGLMapView *)aView regionDidChangeAnimated:(BOOL)animated
{
    CLLocationCoordinate2D sw = {.latitude = 52.685389098664004, .longitude = 5.2769973809771002};
    CLLocationCoordinate2D ne = {.latitude = 52.036343013055998, .longitude = 4.4359466497847002};
    MGLCoordinateBounds bounds = {.sw = sw, .ne = ne};
    [self.mapView setVisibleCoordinateBounds:bounds animated:YES];
}
```

### Expected behavior
Delegate's method should not be called if the bounds are not actually changed as the same bounds is set as before. 
### Actual behavior
Delegate's method is called every time. The code above cycles the stack.

**Comment by 1ec5** [comment]
This is one symptom of #5983 that #6060 aims to address.

**Comment by andrewstay** [comment]
@1ec5 The workaround suggested by you will not work as the newly set bounds are simply not "updated" immediately and on the next delegate call I still get the old ones.

```
        MGLCoordinateBounds visibleBounds = self.mapView.visibleCoordinateBounds;
        Stay_LogStruct(visibleBounds);
        Stay_LogStruct(self.limitedBounds);
        if (!MGLCoordinateBoundsEqualToCoordinateBounds(self.limitedBounds, visibleBounds))
        {
             [self.mapView setVisibleCoordinateBounds:self.limitedBounds animated:YES];
        }
```

Generates the following output after first call:
```
visibleBounds = {
  sw = (latitude = 52.330219750804105, longitude = 4.8401534999993601)
  ne = (latitude = 52.445483002278053, longitude = 4.9679914999995844)
}
limitedBounds = {
  sw = (latitude = 52.685389098664004, longitude = 5.2769973809771002)
  ne = (latitude = 52.036343013055998, longitude = 4.4359466497847002)
}
```
After second call:
```
visibleBounds = {
  sw = (latitude = 52.330219750804105, longitude = 4.8401534999993601)
  ne = (latitude = 52.445483002278053, longitude = 4.9679914999995844)
}
limitedBounds = {
  sw = (latitude = 52.685389098664004, longitude = 5.2769973809771002)
  ne = (latitude = 52.036343013055998, longitude = 4.4359466497847002)
}
```

**Comment by lilykaiser** [comment]
Closing due to ticket age. If this is still a problem, please re-open

**Comment by 1ec5** [comment]
This issue was originally filed due to difficulty constraining gestures to an offline region. As of #5584, you can implement the `-[MGLMapViewDelegate mapView:shouldChangeFromCamera:toCamera:]` to achieve this effect. [Here’s an example](https://www.mapbox.com/ios-sdk/examples/constraining-gestures/) of the delegate method in action.
