### ISSUE TITLE
Android app won't run in emulator on OSX

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#712]
Running via Run ⇢ Run 'app' in Android Studio. Output from the 'app' tab:

```
Waiting for device.
/usr/local/android-sdk-macosx/tools/emulator -avd Nexus_5_API_21_x86 -netspeed full -netdelay none
Device connected: emulator-5554
Device Nexus_5_API_21_x86 [emulator-5554] is online, waiting for processes to start up..
Device Nexus_5_API_21_x86 [emulator-5554] is online, waiting for processes to start up..
Device Nexus_5_API_21_x86 [emulator-5554] is online, waiting for processes to start up..
Device is ready: Nexus_5_API_21_x86 [emulator-5554]
Target device: Nexus_5_API_21_x86 [emulator-5554]
Uploading file
    local path: /Users/john/Development/mapbox-gl-native/android/java/app/build/outputs/apk/app-debug.apk
    remote path: /data/local/tmp/com.mapbox.mapboxgl.app
Installing com.mapbox.mapboxgl.app
DEVICE SHELL COMMAND: pm install -r "/data/local/tmp/com.mapbox.mapboxgl.app"
pkg: /data/local/tmp/com.mapbox.mapboxgl.app
Failure [INSTALL_FAILED_NO_MATCHING_ABIS]
```

Emulator shows the lock screen, no sign of an app in the home screen.

cc @ljbade

**Comment by murtuzakhalid** [comment]
my android's studio emulator is not working....because I have core i5 first generation don't have visualization technology...thats why Intel hexm is not installing...tell me alternate way to run my android code please....!

**Comment by badassben** [comment]
No emulators found as an output of `emulator -list-avds`.
<img width="819" alt="Screenshot 2020-04-14 at 11 05 15 AM" src="https://user-images.githubusercontent.com/43489202/79189647-eba94580-7e3f-11ea-81e8-fd2cfff2118f.png">
My emulator is still opened on the side
