### ISSUE TITLE
Incorrect scroll direction when map tilted

### ISSUE THREAD

**Issue by blueberry6401** [mapbox/mapbox-gl-native#7126]
**Platform:** Android
**Mapbox SDK version:** 4.2 beta 5

### Steps to trigger behavior

 1. Make map tilt.
 2. Swipe down the map fast enough.

### Expected behavior
Map scrolls down.

### Actual behavior
Map scrolls up after released finger.

![2016_11_20_20_22_44_20_23_12_20_24_24](https://cloud.githubusercontent.com/assets/7337535/20463147/041548e2-af60-11e6-8868-69f0e34cd1e0.gif)

**Comment by tobrun** [comment]
Thank you for reaching out, we are tracking this issue in https://github.com/mapbox/mapbox-gl-native/issues/5281. Closing as a duplicate.
