### ISSUE TITLE
Crash: When Attempting to Download Offline Region

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#7137]
Original post https://github.com/mapbox/mapbox-java/issues/215:
> I receive this error when I attempt to download an Offline Region:
> 
> ```
> 11-21 12:32:01.558 com.offgrid.electric.zola.sales.staging A/libc: /usr/local/google/buildbot/src/android/ndk-r12-release/ndk/sources/cxx-stl/llvm-libc++abi/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type std::bad_alloc: std::bad_alloc" failed
> 11-21 12:32:01.559 com.offgrid.electric.zola.sales.staging A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 12494 (DefaultFileSour)
> ```
> 
> I'm using the following version:
> ```
> compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0-beta.5@aar') {
>         transitive = true
>         exclude group: "com.google.guava"
>     }
> ```
> 
> Here's the code:
> 
> ```
> public void createOfflineRegion (String styleUrl, LatLngBounds latLngBounds, float density)
>     {
>         offlineManager.createOfflineRegion(
>                 getDefinition( styleUrl, latLngBounds, density ),
>                 getMetaData(),
>                 new OfflineManager.CreateOfflineRegionCallback()
>                 {
>                     @Override
>                     public void onCreate (OfflineRegion offlineRegion)
>                     {
>                         offlineRegion.setDownloadState( OfflineRegion.STATE_ACTIVE );
>                         offlineRegion.setObserver( new OfflineRegion.OfflineRegionObserver()
>                         {
>                             @Override
>                             public void onStatusChanged (OfflineRegionStatus status)
>                             {
>                                 if ( status.isComplete() )
>                                 {
>                                     Timber.i( "Region downloaded successfully." );
>                                 }
>                             }
> 
>                             @Override
>                             public void onError (OfflineRegionError error)
>                             {
>                                 Timber.e( "onError reason: " + error.getReason() );
>                                 Timber.e( "onError message: " + error.getMessage() );
>                             }
> 
>                             @Override
>                             public void mapboxTileCountLimitExceeded (long limit)
>                             {
>                                 // Notify if offline region exceeds maximum tile count
>                                 Timber.e( "Mapbox tile count limit exceeded: " + limit );
>                             }
>                         } );
>                     }
> 
>                     @Override
>                     public void onError (String error)
>                     {
>                         Timber.e( "Error: " + error );
>                     }
>                 } );
>     }
> ```
> 
> Pretty much just copied from the Sample. Any ideas what could be causing this crash? Thanks

Hey @adavis, I modified the sample code a bit using the same code you provided and wasn't able to reproduce the crash. Could you provide the `getMetaData()` and `getDefinition()` methods also along with what parameters you are passing into `createOfflineRegion()`. If you are getting any additional logcat output when the crash occurs, that might help. 

cc: @zugaldia

**Comment by adavis** [comment]
Parameters:

```        
String styleUrl = Style.SATELLITE;

LatLngBounds latLngBounds = new LatLngBounds.Builder()
          .include( new LatLng( -2.6740, 35.977 ) )
          .include( new LatLng( -4.0559, 37.142 ) )
          .build();

float density = 2.0f;

offlineManager.createOfflineRegion( styleUrl, latLngBounds, getDensity() );
```

The other methods:

```
private OfflineRegionDefinition getDefinition (String styleUrl, LatLngBounds latLngBounds, float density)
    {
        return new OfflineTilePyramidRegionDefinition( styleUrl,
                                                       latLngBounds,
                                                       MIN_ZOOM,
                                                       MAX_ZOOM,
                                                       density );
    }

    private byte[] getMetaData ()
    {
        byte[] metadata;
        try
        {
            JSONObject jsonObject = new JSONObject();
            jsonObject.put( JSON_FIELD_REGION_NAME, SALES_AREA );
            String json = jsonObject.toString();
            metadata = json.getBytes( JSON_CHARSET );
        }
        catch ( Exception e )
        {
            Timber.e( e, "Failed to encode metadata: " + e.getMessage() );
            metadata = null;
        }

        return metadata;
    }
```

**Comment by adavis** [comment]
@cammace I also see this in the logs:

```
11-21 18:11:14.021 com.offgrid.electric.zola.sales.staging D/libc-netbsd: [getaddrinfo]: hostname=api.mapbox.com; servname=(null); netid=0; mark=0
11-21 18:11:14.021 com.offgrid.electric.zola.sales.staging D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
11-21 18:11:14.022 com.offgrid.electric.zola.sales.staging D/libc-netbsd: [getaddrinfo]: hostname=api.mapbox.com; servname=(null); netid=0; mark=0
11-21 18:11:14.022 com.offgrid.electric.zola.sales.staging D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
11-21 18:11:14.022 com.offgrid.electric.zola.sales.staging D/libc-netbsd: getaddrinfo: api.mapbox.com get result from proxy gai_error = 0
11-21 18:11:14.024 com.offgrid.electric.zola.sales.staging D/Posix: [Posix_connect Debug]Process com.offgrid.electric.zola.sales.staging :443 
11-21 18:11:14.032 com.offgrid.electric.zola.sales.staging D/libc-netbsd: getaddrinfo: api.mapbox.com get result from proxy gai_error = 0
11-21 18:11:14.033 com.offgrid.electric.zola.sales.staging D/Posix: [Posix_connect Debug]Process com.offgrid.electric.zola.sales.staging :443 
11-21 18:11:14.062 com.offgrid.electric.zola.sales.staging D/libc-netbsd: [getaddrinfo]: hostname=api.mapbox.com; servname=(null); netid=0; mark=0
11-21 18:11:14.062 com.offgrid.electric.zola.sales.staging D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
11-21 18:11:14.070 com.offgrid.electric.zola.sales.staging D/libc-netbsd: [getaddrinfo]: hostname=api.mapbox.com; servname=(null); netid=0; mark=0
11-21 18:11:14.071 com.offgrid.electric.zola.sales.staging D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
```

**Comment by cammace** [comment]
I've been tweaking around with the `OfflineTilePyramidRegionDefinition` parameters using the same bounding box, style, and pixel density provided by @adavis (thanks!). While I can't produce the exact same crash, if I tweak the max zoom level beyond 18 the region fails to complete downloading and results in the activity being destroyed:

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5652865/20532483/31efc7a8-b0a8-11e6-91c5-d3e3c3519869.gif)

No logcat errors are shown.

**Comment by adavis** [comment]
Thanks @cammace, so I reduced the `MAX_ZOOM` to `18` and now the crash is gone. Would be useful to have some logs around it though.

**Comment by zugaldia** [comment]
> No logcat errors are shown.
> Would be useful to have some logs around it though.

The absence of any logs is truly strange.

**Comment by ivovandongen** [comment]
@cammace Have you tried to get the error by disabling the filters in Android Studio? The native crash stacktrace usually doesn't show up with the filters enabled.

![screen shot 2016-11-28 at 10 41 03](https://cloud.githubusercontent.com/assets/64527/20661404/4ad9391c-b557-11e6-84de-5c9a214a9975.png)

**Comment by cammace** [comment]
Yes @ivovandongen, I'll try reproducing this in the testapp on a branch later today.

**Comment by abourtema** [comment]
I have problem , I use Mapbox in android , the app run good but when download map show me Mapbox tile count limit exceeded: 6000 , I use less 400 tile

**Comment by zugaldia** [comment]
@cammace Any luck getting further crash logs as suggested by @ivovandongen ?

@abourtema Your issue seems to be a different one. Do you mind [opening a separate ticket](https://github.com/mapbox/mapbox-gl-native/issues/new) including the code or settings that you're using to download the offline region so that we can reproduce it? Thanks.

**Comment by tobrun** [comment]
@cammace Any update on this?

**Comment by abourtema** [comment]
Thank you very mach
