### ISSUE TITLE
Failing to load style from offline db

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#7138]
Running into issues when device is in airplane mode and attempting to load in a side loaded offline database. I get this log output:

```
11-21 17:54:40.901 17567-17617/mapbox.debugme I/com.mapbox.mapboxsdk.http.HTTPRequest: Request failed due to a connection error: No Internet connection available.
11-21 17:54:40.926 17567-17567/mapbox.debugme E/mbgl: {mapbox.debugme}[Setup]: loading style failed: No Internet connection available.
```

resulting in a black screen (no style loaded).

cc: @ivovandongen @zugaldia

**Comment by zugaldia** [comment]
@cammace Is this happening for styles generated from the `mapbox.com` endpoint or from other endpoints? Did this happen for styles generated with `mbgl-offline` or other tools?

**Comment by cammace** [comment]
Yes this is happening using both the `mapbox.com` endpoint and `mbgl-offline` tool.

**Comment by ivovandongen** [comment]
@cammace Just to be sure, did you set the `MapView` style url to the same one as used for the downloaded offline database?

You can check the database with any kind of SQLite browser and you should find the style in the resources table:

![screen shot 2016-11-22 at 17 23 23](https://cloud.githubusercontent.com/assets/64527/20529348/7ef5e188-b0d8-11e6-811a-5bd46d086efd.png)


Just tested this with an offline database in flight mode, seems to work fine. Could you check the style url for your particular case?

**Comment by cammace** [comment]
I was using different style URLs for my offline download and the map style. Matching the URL fixed the issue. Thanks @ivovandongen.
