### ISSUE TITLE
MGLMapView not show user location after Disable/Enable Location Service

### ISSUE THREAD

**Issue by iBinh** [mapbox/mapbox-gl-native#7142]
**Platform:** iOS
**Mapbox SDK version:** 3.4.0-beta.3

### Steps to trigger behavior

 1. Open my map app
 2. Turn off location service in iOS Privacy setting
 3. Back to app

### Expected behavior
MGLMapView should show user location and detect location exactly
### Actual behavior
There are 2 behavior
1. MGLMapView detected user location but doesn't show user location dot. 
2. MGLMapView doesn't show and detect user location, although i wait for minutes 
`<MGLUserLocation: 0x174254be0; location = 340282346638528859811704183484516925440.000000, 340282346638528859811704183484516925440.000000; updating = no; altitude = 0m; heading = 0°; title = "You Are Here"; subtitle = (null)>
`
@1ec5

**Comment by friedbunny** [comment]
From your reproduction steps, this is the inevitable behavior — if the device has location services disabled, it is impossible to then use location services.

Assuming you meant to add a Step 4 that re-enables location services, I tried that: it also works as expected — the location dot reappears.
