### ISSUE TITLE
Fix activity sanity tests documentation

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#7147]
The way of generating sanity tests changed so the documentation has become out of the date.
Now generation is done by executing:

> make test-code-android

cc/ @tobrun @zugaldia

**Comment by zugaldia** [comment]
Besides updating [`tests/README.md`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/tests/README.md) is there anything else that we should do here?
