### ISSUE TITLE
All NSValue methods live in an MGLGeometryAdditions category in documentation

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7153]
In #4802, I meant to work around realm/jazzy#539 but putting all the NSValue category methods in the same `MGLAdditions` category. But I accidentally left a rump category interface in MGLGeometry.h that’s causing the jazzy documentation to put all the NSValue category methods under `NSValue (MGLGeometryAdditions)`, even though some of the methods have nothing to do with geometry. The MGLGeometryAdditions interface should be removed.

/cc @boundsj

**Comment by boundsj** [comment]
This was fixed in https://github.com/mapbox/mapbox-gl-native/pull/7061
