### ISSUE TITLE
Allow zoom levels beyond 21 on Android

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7155]
#4417 capped the maximum zoom level at 21 to work around #4416, #4272, and #4168. Of these issues, #4416 was fixed in #4508, #4168 was Android-specific, and it isn’t clear whether the root cause behind #4272 was ever fixed. This ticket tracks allowing zoom levels greater than 21 again.

/cc @jfirebaugh @ansis

**Comment by ansis** [comment]
There is a another limit at z25.5. We store zoom levels in the symbol buffers in a single byte to the tenth of a decimal place. This makes the max possible value 255/10 = 25.5. This could be changed by using more bits but I don't think we have any reason to support zooms > 25.5

**Comment by 1ec5** [comment]
#4417 decreased `MapboxConstants.MAXIMUM_ZOOM` (on Android) and `mbgl::util::MAX_ZOOM` (across all platforms) from 25.5 down to 21.0. Yet I see no trace of the latter change in the commit histories in include/mbgl/util/constants.hpp or src/mbgl/util/constants.cpp on master. `mbgl::util::MAX_ZOOM` is still 25.5.

#7306 decreased `MapboxConstants.MAXIMUM_ZOOM` further to 20.0 without explanation. @tobrun, do you recall why you did this?

**Comment by jfirebaugh** [comment]
Looks like the change to `constants.cpp` in #4417 conflicted with ee651d783238ab9e3d69028f43795a62c91e58b9 during the merge of the release branch to master, and the latter won.

**Comment by emerciercontexeo** [comment]
It's becoming critical on our side to be able to zoom at least to 22 (better to 23)

Are you planing something for this issue ?

**Comment by 1ec5** [comment]
On iOS as of 40e47556214e999c952c1e88e026d673cdd96c72, I’m able to set the `maximumZoomLevel` to 25.5 and pinch out to 23.90 (in the D.C. area) before the map gets stuck:

![z23 90](https://user-images.githubusercontent.com/1231218/27497389-357e7fe0-580f-11e7-8a6b-5113bce43bf5.png)

**Comment by 1ec5** [comment]
Tracking the hang on iOS in #9359. If you hide the scale bar, it should go further without any problems.
