### ISSUE TITLE
Dynamically grant permissions in UI tests

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#7159]
There are some tests excluded from being generated and/or ignored because a way to grant permissions dynamically in tests wasn't implemented.

There are some workarounds to grant permissions dynamically in tests.
Including:
* `adb install -g`
* [PermissionGranter](https://gist.github.com/rocboronat/65b1187a9fca9eabfebb5121d818a3c4)
* [Grant permissions before tests](https://github.com/googlesamples/android-testing/blob/ed62c450e43f859333b3113d44dd59f75971b529/ui/espresso/IntentsBasicSample/app/src/androidTest/java/com/example/android/testing/espresso/BasicSample/DialerActivityTest.java#L94)

I think the latter would be the best approach.

Below all the activities that request Location permissions:
`MyLocationTrackingModeActivity`, `MyLocationToggleActivity`, `MyLocationTintActivity`, `MyLocationDrawableActivity`, `LocationPickerActivity` and `MyLocationViewTest`.

Cc/ @tobrun @zugaldia

**Comment by zugaldia** [comment]
> I think the latter would be the best approach.

👍 Great thinking here, the wider the coverage the better.

**Comment by Guardiola31337** [comment]
> 👍 Great thinking here, the wider the coverage the better.

That's the point!

**Comment by Guardiola31337** [comment]
We should revisit this now that the [Android Testing Support Library 1.0 is here](https://android-developers.googleblog.com/2017/07/android-testing-support-library-10-is.html) 🎉 because it includes a [`GrantPermissionRule`](https://developer.android.com/reference/android/support/test/rule/GrantPermissionRule.html).

**Comment by tobrun** [comment]
Closing as this is no longer relevant for the Maps SDK. We are deprecating everything related to location and moving that into a [LocationLayerPlugin](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-locationlayer). That plugin is already using the `GrantPermissionRule` mentioned above.
