### ISSUE TITLE
Draw context is NULL

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#716]
After getting Android Studio setup and [setting an access token](https://github.com/mapbox/mapbox-gl-native/issues/713), opening the Mapbox GL app loads the following screen, then prints "Draw context is NULL" in the studio log and exits.

![](https://s3.amazonaws.com/uploads.hipchat.com/81832/591983/qIVfYs5XG0r67xE/Screen%20Shot%202014-12-11%20at%202.18.37%20PM.png)

/cc @ljbade

**Comment by ljbade** [comment]
I have not seen any issues on my Mac Mini with the OSX emulator. Closing for now.
