### ISSUE TITLE
Backend::activate/deactivate need to be reentrant

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#7163]
In some contexts, `Backend::activate` can be called when the backend is already active. One example is if `Map::addLayer` is called during notifications such as `MapChangeWillStartRenderingFrame` and `MapChangeRegionDidChangeAnimated`.

Therefore `Backend::activate` / `Backend::deactivate` need to count the number of calls in a reference counting manner. Deactivation should happen only when the count reaches 0.

I feel like we did this at one point. Did it regress as part of the `Backend` changes?

cc @kkaefer @boundsj

**Comment by jfirebaugh** [comment]
#5874, #5836, #5721

**Comment by jfirebaugh** [comment]
Ok, looks like we refcount on Android but not iOS.

**Comment by boundsj** [comment]
This was fixed by https://github.com/mapbox/mapbox-gl-native/pull/7208
