### ISSUE TITLE
Uncaught exception when database or disk is full

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#7164]
We should gracefully handle situations where the database/disk is reportedly full. For now, we crash with: 

`*** Terminating app due to uncaught exception 'mapbox::sqlite::Exception', reason: 'database or disk is full’`

/cc @jfirebaugh @hjudge

**Comment by kkaefer** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/12224
