### ISSUE TITLE
How to add more then one annotation?

### ISSUE THREAD

**Issue by mukeshtaurus** [mapbox/mapbox-gl-native#7165]
Hi Everyone,

In the below code, I am reading data from json and based on the customer type i want to change the annotation. It shows custom image but doesnt change as per type.

Need Help.

Thanks 

//
//

import UIKit
import Mapbox
import CoreData
import CoreFoundation
import Foundation

class ViewController: UIViewController, MGLMapViewDelegate {

    var custtype = ""
    
    @IBOutlet var mapView: MGLMapView!

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        mapView.delegate = self
        
        var pointAnnotations = [MGLPointAnnotation]()
        
        if let path = Bundle.main.url(forResource: "customerdata", withExtension: "json") {
            
            do {
                let jsonData = try Data(contentsOf: path, options: .mappedIfSafe)
                do {
                    if let jsonResult = try JSONSerialization.jsonObject(with: jsonData, options: JSONSerialization.ReadingOptions(rawValue: 0)) as? NSDictionary {
                        if let personArray = jsonResult.value(forKey: "custdata") as? NSArray {
                            for (_, element) in personArray.enumerated() {
                                if let element = element as? NSDictionary {
                                    let custaddress = element.value(forKey: "address") as! String
                                     custtype = element.value(forKey: "customertype") as! String
                                    let custname = element.value(forKey: "customername") as! String
                                    let companycode = element.value(forKey: "companycode") as! String
                                    let custcode = element.value(forKey: "customercode") as! String
                                    let lat = element.value(forKey: "latitude") as! Double
                                    let lng = element.value(forKey: "longitude") as! Double
                                    let cordinate = CLLocationCoordinate2DMake(lat, lng)
                                    //print("Name: \(custname),  address: \(custaddress), type: \(custtype), Company Code: \(companycode), Customer code: \(custcode), Cordinate: \(cordinate)")
                                    let point = MGLPointAnnotation()
                                    point.coordinate = cordinate
                                    point.title = "Name: \(custname)"
                                    
                                    point.subtitle = "address: \(custaddress), type: \(custtype), Company Code: \(companycode), Customer code: \(custcode)"
                                    pointAnnotations.append(point)
                                    
                                    //mapView.addAnnotations(pointAnnotations)
                                }
                            }
                        }
                    }
                } catch let error as NSError {
                    print("Error: \(error)")
                }
            } catch let error as NSError {
                print("Error: \(error)")
            }
        }
        
        mapView.addAnnotations(pointAnnotations)
        
        
    }
    func mapView(_ mapView: MGLMapView, imageFor annotation: MGLAnnotation) -> MGLAnnotationImage? {
        
        var annotationImage = mapView.dequeueReusableAnnotationImage(withIdentifier: "cycle")
        //var image
        //print("cutype" + custtype)
        if annotationImage == nil {
            if custtype == "dealer"{
                let _image = UIImage(named: "acl_d")!
                annotationImage = MGLAnnotationImage(image: _image, reuseIdentifier: "point")
                print("dealer: \(custtype)")
            }
            else if custtype == "retailer" {
                let _image = UIImage(named: "acc_r")!
                annotationImage = MGLAnnotationImage(image: _image, reuseIdentifier: "point")
                print("retailer: \(custtype)")
            }
        }
        return annotationImage
    }
    // Return `nil` here to use the default marker.
    func mapView(_ mapView: MGLMapView, viewFor annotation: MGLAnnotation) -> MGLAnnotationView? {
        return nil
    }
    
    func mapView(_ mapView: MGLMapView, annotationCanShowCallout annotation: MGLAnnotation) -> Bool {
        // Always try to show a callout when an annotation is tapped.
        return true
    }
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    
    @IBAction func setMap(_ sender: UISegmentedControl) {
        if sender.selectedSegmentIndex == 0{
            mapView.styleURL = MGLStyle.streetsStyleURL(withVersion: 9)
        }else{
            mapView.styleURL = MGLStyle.satelliteStreetsStyleURL(withVersion: 9)
        }
        
    }

}

**Comment by frederoni** [comment]
`custtype` is global. Whatever the last customer type is when the for-loop finishes will be the customer type for all annotations. You should store the personArray somewhere in order to access it  in `mapView(_:imageFor:)` later.

**Comment by mukeshtaurus** [comment]
Thanks Frederoni....

I am new to Mapbox ... I tried what you suggested by not getting the desired output. Will it be possible for you to do the correction in the above code.

Thanks
