### ISSUE TITLE
overlay style url?

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-native#7167]
Is there a way to have one iOS app with two styleURL based base layers that the user can switch between and then one style URL based overlay that the user can turn on/off regardless of the base layer? All of the layers are vector layers with styling in the json files.

**Comment by mb12** [comment]
@halset one option would be to logically cat all the three styles into one json file. Then you can add logic to dynamically toggle visibility property of layers to hide/show them.

**Comment by jfirebaugh** [comment]
This is not currently possible as describe. Equivalent functionality can be achieved with the upcoming runtime styling API, though perhaps not as conveniently. https://github.com/mapbox/mapbox-gl/issues/25 tracks a similar request.
