### ISSUE TITLE
NSValue (MGLStyleEnumAttributeAdditions) declares unprefixed properties

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7168]
#7061 added category properties on NSValue with names like `lineCap`. When categorizing a class we don’t declare, we need to use a class prefix to avoid conflicts. `lineCap` should be renamed to `MGLLineCapValue` for consistency with existing category properties on NSValue like `MGLCoordinateValue` and `MKCoordinateValue`.

/cc @boundsj

**Comment by boundsj** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/7171
