### ISSUE TITLE
Java 8 Language features with Jack compiler

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#7169]
On Google I/O 2016, Google announced support for Java 8 language features by using the new Jack compiler toolchain. The Jack compiler behaves differently than the legacy javac:

<img width="377" alt="screen shot 2016-11-23 at 12 17 56" src="https://cloud.githubusercontent.com/assets/2151639/20559930/2bcb1d58-b177-11e6-959b-35678d0cf056.png">

The jack toolchain doesn't generate class files and as a side effect this will break instant run and any component that uses a class file (eg. lint, code coverage, etc). @ivovandongen would this also impact how we are currently setting up our android core tests?

Read more about this [here](https://developer.android.com/guide/platform/j8-jack.html). 

cc @mapbox/android

**Comment by ivovandongen** [comment]
>  would this also impact how we are currently setting up our android core tests?

@tobrun Yes, but only if we start to use java 8 features. Either we need to use the jack compiler (if possible) to create the dex files then or use retrolambda.

**Comment by tobrun** [comment]
Picking this up when we have a need for this, nothing actionable left to do. Closing.
