### ISSUE TITLE
MapboxMapOptions don't include a default CameraPosition

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#7174]
I run into a NPE when launching `MyLocationDrawableActivity` because it uses `setInitialState` method from `MapView` and it tries to access to the `CameraPosition` from `MapboxMapOptions`.

I could add the `CameraPosition` in the example using `camera` method to solve the example.
But maybe the SDK should have that into account having a default implementation of `CameraPosition` so users don't run into this issue.

**Comment by tobrun** [comment]
Thank you for flagging
