### ISSUE TITLE
[Android] How can i using a custom view instead of marker 

### ISSUE THREAD

**Issue by GianhTran** [mapbox/mapbox-gl-native#7178]
**Platform:**
**Mapbox SDK version:**
Marker can not using drawable animation, so i want to add a view like way marker do, any way?
I know mapbox for Ios can do that, but i cant find way to add a view to mapbox android!
Thanks you in advance !

**Comment by tobrun** [comment]
@GianhTran thank you for using our tools! You can add a standard Android View to the Map by using MarkerView. An example of this can be found [here](https://www.mapbox.com/android-sdk/examples/marker-view/). More in detail examples can be found [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java).
