### ISSUE TITLE
Remove HTTP requests from Gradle build

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#7180]
Every gradle invocation seems to try to download a few URLS:

```
https://jcenter.bintray.com/org/apache/maven/maven-plugin-api/$%7Bproject.prerequisites.maven%7D/maven-plugin-api-$%7Bproject.prerequisites.maven%7D.pom
https://jcenter.bintray.com/org/apache/maven/maven-plugin-api/$%7Bproject.prerequisites.maven%7D/maven-plugin-api-$%7Bproject.prerequisites.maven%7D.jar
https://jitpack.io/org/apache/maven/maven-plugin-api/$%7Bproject.prerequisites.maven%7D/maven-plugin-api-$%7Bproject.prerequisites.maven%7D.pom
https://jitpack.io/org/apache/maven/maven-plugin-api/$%7Bproject.prerequisites.maven%7D/maven-plugin-api-$%7Bproject.prerequisites.maven%7D.jar
https://jcenter.bintray.com/org/apache/maven/reporting/maven-reporting-api/$%7Bproject.prerequisites.maven%7D/maven-reporting-api-$%7Bproject.prerequisites.maven%7D.pom
https://jcenter.bintray.com/org/apache/maven/reporting/maven-reporting-api/$%7Bproject.prerequisites.maven%7D/maven-reporting-api-$%7Bproject.prerequisites.maven%7D.jar
https://jitpack.io/org/apache/maven/reporting/maven-reporting-api/$%7Bproject.prerequisites.maven%7D/maven-reporting-api-$%7Bproject.prerequisites.maven%7D.pom
https://jitpack.io/org/apache/maven/reporting/maven-reporting-api/$%7Bproject.prerequisites.maven%7D/maven-reporting-api-$%7Bproject.prerequisites.maven%7D.jar
```

Given that they're all 404s, we should find the source of these requests and remove them.

**Comment by tobrun** [comment]
These downloads are invoked as part of `gradle-publish.gradle`, more specifically in:
```
apply plugin: 'maven'
```
Their isn't much we can do from our side as this is coming form an external dependency. One thing I noticed is that we could move to the [more official](https://docs.gradle.org/current/userguide/publishing_maven.html) `apply plugin:'maven-publish` instead but as long as current setup is working, I'm not seeing much added value for changing this.

cc @mapbox/android

**Comment by zugaldia** [comment]
> One thing I noticed is that we could move to the more official apply plugin:'maven-publish instead but as long as current setup is working, I'm not seeing much added value for changing this.

Same, happy to use the newer plugin but also noting that such a solution should be ported to github.com/mapbox/mapbox-java which uses the same plugin as the SDK.

**Comment by rahul-a** [comment]
I had a similar issue, because i had a classpath dependency on spoon-runner's older version (was coming as a transitive dependency from https://github.com/stanfy/spoon-gradle-plugin), on putting latest spoon-runner in the classpath it got resolved for me, not sure if y'all use it just my two cents...
