### ISSUE TITLE
[iOS]Callout for feature annotation is not presented

### ISSUE THREAD

**Issue by andrewstay** [mapbox/mapbox-gl-native#7182]
**Platform:** iOS
**Mapbox SDK version:** ios-v3.4.0-beta.2

### Steps to trigger behavior

 1. Setup a tap recognizer in map view and implement the following once the tap is recognized:
```
    CGPoint touch = [aRecognizer locationOfTouch:0 inView:self.mapView];
    NSArray <id<MGLFeature>> *features = [self.mapView visibleFeaturesAtPoint:touch];
    id<MGLFeature> transport = nil;
    for (id<MGLFeature> feature in features)
    {
        if (feature.attributes[@"network"] != nil)
        {
            transport = feature;
            break;
        }
    }
    if (transport != nil)
    {
        [self.mapView selectAnnotation:transport animated:YES];
    }
```

### Expected behavior
Delegate's method ```-mapView:calloutViewForAnnotation:``` should be called

### Actual behavior
Delegate's method ```-mapView:calloutViewForAnnotation:``` is not called, callout is not presented

**Comment by lilykaiser** [comment]
Closing due to ticket age. If this is still a problem, please re-open
