### ISSUE TITLE
[Android][Bug] MapPaddingActivity not working properly

### ISSUE THREAD

**Issue by mayardb** [mapbox/mapbox-gl-native#7183]
Hello and thanks for the great job you do.

I encounter some problems with the padding in the Android SDK.

When I start the MapPaddingActivity, the marker Bangalore is not in the middle of the active map area.

![mappaddingactivity](https://cloud.githubusercontent.com/assets/6266608/20605181/54b64730-b26a-11e6-9423-10b95db669f2.png)

If the padding is greater than half screen size, you cannot see your target.

Mapbox SDK version: **android-v4.2.0-beta.5**

**Comment by tobrun** [comment]
Thank you for flagging @mayardb, this seems like a regression.

**Comment by tobrun** [comment]
Confirmed seeing both on release as master branch, brief java debugging didn't show the issue. 
@mapbox/ios are you seeing the same on your end?

**Comment by frederoni** [comment]
@tobrun I've tried with pitch 0 and 50 and the annotation it's properly center-aligned in both cases on iOS.

**Comment by tobrun** [comment]
@frederoni thank you for testing!

**Comment by 1ec5** [comment]
The issue here is unrelated to pitch, isn't it? Seems like the bug is that setting the center coordinate isn't accounting for padding.

**Comment by tobrun** [comment]
Retested on release branch/master and issue seem to have been resolved :thinking: 

![device-2016-11-29-123840](https://cloud.githubusercontent.com/assets/2151639/20708570/c9606c7c-b630-11e6-9c76-bf7b6d2ebb96.png)

@mayardb 
would you be able to validate that your initial issue is resolved by testing with the latest 4.2.0 SNAPSHOT?

```
 compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0-SNAPSHOT@aar') {
        transitive=true
    }
```

**Comment by mayardb** [comment]
I pulled the branch/master too.
I validate that the map is well centered.


But, I have noticed that we are pointing the North, so I clicked on the compass and we are not rotating the map around the center of the active map area.


In the same time, I have tried to get the active map area center `LatLng`. 
I also add this line to the `moveToBangalore` method in `MapPaddingActivity` : 

```
mapboxMap.moveCamera(CameraUpdateFactory.newCameraPosition(cameraPosition), new MapboxMap.CancelableCallback() {
    @Override
    public void onCancel() {
    }

    @Override
    public void onFinish() {
        Log.e("MapPaddingActivity", "new Center : " + mapboxMap.getCameraPosition().target + " | Bangalore : " + bangalore);
    }
});
        mapboxMap.addMarker(new MarkerOptions().title("Center map").position(bangalore));
```


On my Nexus 6P, the log is :
```
11-29 15:32:00.691 17308-17308/com.mapbox.mapboxsdk.testapp E/MapPaddingActivity: new Center : LatLng [latitude=12.981081600000053, longitude=77.63680339999905, altitude=0.0] | Bangalore : LatLng [latitude=12.9810816, longitude=77.6368034, altitude=0.0]
```

I think the gap is acceptable and we can get the right value.



When will the branch/master be merged into the **android-v4.2.0-beta.X** ?

**Comment by mayardb** [comment]
I think I have my response : 

pulling the **branch/release-android-v4.2.0** and using 

```
compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0-SNAPSHOT@aar') {
        transitive=true
    }
```

as indicated by @tobrun, I get the right active map area center.

**Comment by tobrun** [comment]
@mayardb any update on this? any actions required or good to close?
