### ISSUE TITLE
Emulator shows vertex attribute out of boundary

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#7185]
When running the test app on an Android emulator and make it render, I'm seeing it constantly log:

```java
11-25 08:30:27.244 3122-3122/com.mapbox.mapboxsdk.testapp E/emuglGLESv2_enc: a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute.
```

**Comment by jimandreas** [comment]
I am seeing this error on Android Emulators also - but with a different app.   No complaints from my Nexus 4 phone.   I see it on both API19 and API25 emulators.   Still digging into the issue.

**Comment by tobrun** [comment]
thank you for confirming that this bug is unrelated to this project! Closing

**Comment by manh-tran** [comment]
Opengles 2.0 on Android does not support VAO, draw by VBO instead.
