### ISSUE TITLE
Tap gesture recognizer should fail unless annotation is nearby

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7194]
MGLMapView’s built-in UITapGestureRecognizer should set its state to `UIGestureRecognizerStateFailed` as soon as it discovers that no annotations are nearby. Combined with #2278, the developer would be able to install their own “fallback” tap gesture recognizer that handles taps when the built-in gesture recognizer, meant for annotation selection, has nothing to select.

/cc @danpat @incanus

**Comment by danpat** [comment]
I hit this.  I have annotations on the map, but I would also like to allow the user to tap elsewhere on the map and perform a feature lookup using `visibleFeaturesAtPoint:`.

**Comment by 1ec5** [comment]
Note that the recognizer should _not_ fail if an annotation is already selected and tapping closes the annotation’s callout view.

**Comment by 1ec5** [comment]
Fixed in #7246.
