### ISSUE TITLE
provide own tile archives?

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-native#7195]
I would like to download a large amount of tiles+resources at once and use that within the app. The current offline pack method is not working fast and interactive enough. And MBTiles are not supported.

A very simple way could be to let developers control the tile+resource evict *and* let the developers insert tiles manually by exposing the putTile/putResource methods.

That way, I could download a MBTile archive and copy the tiles in place or perhaps use some other streaming tile archive thing.

Would it make sense to expose putTile/putResource via the iOS SDK?

**Comment by jfirebaugh** [comment]
Thanks for the suggestions @halset. #3894 tracks our likely future work in this area.
