### ISSUE TITLE
SNAPSHOT version

### ISSUE THREAD

**Issue by jemshit** [mapbox/mapbox-gl-native#7198]
I have a question, i use this version below:
```java
compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0-SNAPSHOT@aar') {
        transitive=true
}
```
I am planning to use this in release version of app. Does this SNAPSHOT disappear from your maven after you put 4.2.0 stable version ?

**Comment by tobrun** [comment]
Correct @jemshit, note that the beta releases will remain available.

**Comment by jemshit** [comment]
Really? that snapshot fixes some error, what i use in production then?
