### ISSUE TITLE
-[MGLStyle removeLayer:] relies on undefined behavior

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7211]
Per https://github.com/mapbox/mapbox-gl-native/pull/6097#discussion_r89903599, the `-removeFromMapView:` method in each of the concrete MGLStyleLayer subclasses relies on undefined behavior by `reinterpret_cast`ing a `unique_ptr` to the `mbgl::style::Layer`. This code was added to the iOS and macOS SDKs in #7048. The Android SDK is doing something a bit different in #7039: `move`-ing a `unique_ptr` but not `reinterpret_cast`ing it.

/cc @jfirebaugh @boundsj

**Comment by boundsj** [comment]
This was fixed by https://github.com/mapbox/mapbox-gl-native/pull/7227
