### ISSUE TITLE
How toı change styling of MAKI icons at runtime ? 

### ISSUE THREAD

**Issue by cranberriess89** [mapbox/mapbox-gl-native#7216]
Hi,
Is it possible to change the styling of maki icons at runtime according to the data ?
Here is the code of how I put the icons on the map ; 

    <style>
        .my-icon {
            border-radius: 100%;
            width: 15px;
            height: 15px;
            text-align: center;
            line-height: 15px;
            color: white;
        }

        .icon-dc {
            /*background: #3ca0d3; /*blue*/
            background: #ffd11a; /*yellow*/
            /*background: #ff5c33; */ /*red*/
        }

        .icon-sf {
            /*background: #63b6e5;*/
            background: #ff5c33;
        }
    </style>

    function loadUsers( users ){

            var list = [];
            
            for (var i = 0; i < users.length; i++) {
              
                //Generate geographical data using the longitude & latitude points of users 
                var geoData = {
                    type: 'Feature',
                    geometry: {
                        type: 'Point',
                        coordinates: [users[i].Longitude, users[i].Latitude]
                    },
                    properties: {
                        id: users[i].Id,
                        icon: {
                            className: 'my-icon icon-dc', // class name to style
                            html: '&#9733;', // add content inside the marker
                            iconSize: null // size of icon, use null to set the size in CSS
                        }
                    },
                    onEachFeature: onEachFeature
                };
                list.push(geoData);
            }
            return list;
        }

I mean **icon-dc.backgroud color** should be changed contextually according to the given data at runtime. How can I change the styling ?

**Comment by tobrun** [comment]
This repository is dedicated to gl-native and not gl-js. Feel free to reach out to us through https://www.mapbox.com/contact/ with any technical questions you have or feel free to open a ticket on the https://github.com/mapbox/mapbox-gl-js in case of a bug or a feature request. Closing since this is not the correct repo. Thank you for reaching out and using our products!
