### ISSUE TITLE
MapBox in UIScrollView, scrolling behavior

### ISSUE THREAD

**Issue by standers67** [mapbox/mapbox-gl-native#7217]
**Platform: iOS 10 
**Mapbox SDK version: 3.3.7

We have an IOS project where we have migrated to the MapBox iOS SDK, currently on version 3.3.7

We have identified one behavior related to the scrolling that differs from the MKMapView. We want to present the map without letting the user pan (scroll) the map. For this we set the property self.mapView.allowsScrolling to NO. This works as intended, the user is not able to pan the map.

However, the problem we have is that the MGLMapView is presented in a UIScrollView. When we have disabled the scrolling as above, the map seems to ignore the swipe gesture that would normally be detected by the UIScrollView.

To scroll the view presented in the scrollview you need to touch the screen either above or below the MGLMapView. Swiping on the map do not cause the UIScrollView to move.

This works with the regular MKMapView, setting the scrolling to disabled there, still let it send the received gestures to the underlying UIScrollView.

**Comment by standers67** [comment]
There has not been any activity for this issue. Do I need to provide more input? This problem is very annoying and we have not been able to find a workaround either. I have not tried any of the latest builds, but I assume that if this problem would have been corrected - it should somehow be noted here.

Thanks,
Stefan

**Comment by friedbunny** [comment]
Hi @standers67, it would be useful if you could:

- Provide a minimal test case that reproduces the issue.
- Confirm that this issue still exists in the latest [v3.4.0 pre-release](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.4.0-beta.6).

If you haven’t already, you might also try different means of disabling the [map view’s interactivity](https://www.mapbox.com/ios-sdk/api/3.4.0-beta.6/Classes/MGLMapView.html#/Configuring%20How%20the%20User%20Interacts%20with%20the%20Map). Specifically:

- [`MGLMapView.scrollEnabled`](https://www.mapbox.com/ios-sdk/api/3.4.0-beta.6/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)scrollEnabled)
- `MGLMapView.userInteractionEnabled`

**Comment by standers67** [comment]
Hi Jason / MapBox,

Thanks for coming back so quickly regarding this.

The easiest way to reproduce  the problem, is to add a UIScrollView to a regular ViewController. In the scrollview, you then add a MGLMapBox (together with other content, to make sure that the content is larger than the current view).

We have found that when we use any of the methods provided to prevent panning the Mapboxview, the touch events are not forwarded to the underlying UIScrollView. To be able to scroll, you must either touch the area just above or below the map.

The problem should be really easy to re-create, if you find it necessary it can surely create a small project that illustrates the issue.

Please let me know if I have been able to clearly describe the issue, or if there are more details that I need to explain.

Thanks a lot,
Stefan

**Comment by boundsj** [comment]
>  also wonder if it may be worth opening a ticket to change MGLMapView so that it disables all of its gesture recognizers when the map view's user interactivity is disabled

Actually, this should not be necessary since setting `userInteractionEnabled` would cancel out all touch events. So, this might be another workaround if no interaction with the map is desired. 

Otherwise, I think that disabling just the relevant recognizers when APIs like `scrollEnabled`, `rotateEnabled`, etc. are set to false, for now in application code, and eventually in `MGLMapView` itself, may help here.

**Comment by incanus** [comment]
I think both using `userInteractionEnabled = false` (as in e.g. https://github.com/mapbox/MapboxTableViewDemo) as well as improving our `..Enabled` APIs to actually disregard input are good ideas.

**Comment by standers67** [comment]
Just as follow-up to this problem. If we use the userInteractionEnabled = NO, it actually works in one aspect, but then we have the issue that we cannot respond to map annotation events.  Our mapView have annotations that the users can interact with so we still have the issue. This does not work if we completely disable user interaction with the mapView.

**Comment by 1ec5** [comment]
To clarify, would setting `scrollEnabled` to `NO` work for you? It should disable pan gestures but still ensure that the user can select annotations by tapping.

**Comment by standers67** [comment]
That was what we tried initially, but the problem was then that the scrolling gesture was not sent to the underlying scrollView that the mapBox is contained in. Have any changes been made in the component to fix this problem? We are not running on the very latest release, but if nothing has been changed in the component, it would probably not matter.
