### ISSUE TITLE
How to make markers resizable when the zoom leven changed?

### ISSUE THREAD

**Issue by cranberriess89** [mapbox/mapbox-gl-native#7219]
Hi,
I want the MAKI icons resizable according to the zoom level.  Here is how I put the markers( with custom MAKI icons ) on the map ;

<style>
    .my-icon {
        border-radius: 100%;
        width: 15px;
        height: 15px;
        text-align: center;
        line-height: 15px;
        color: white;
    }

    .icon-dc {
        background: #ffd11a; 
    }

    .icon-sf {
        background: #ff5c33;
    }
</style>

function loadUsers( users ){

        var list = [];
        
        for (var i = 0; i < users.length; i++) {
          
            //Generate geographical data using the longitude & latitude points of users 
            var geoData = {
                type: 'Feature',
                geometry: {
                    type: 'Point',
                    coordinates: [users[i].Longitude, users[i].Latitude]
                },
                properties: {
                    id: users[i].Id,
                    icon: {
                        className: 'my-icon icon-dc', // class name to style
                        html: '&#9733;', // add content inside the marker
                        iconSize: null // size of icon, use null to set the size in CSS
                    }
                },
                onEachFeature: onEachFeature
            };
            list.push(geoData);
        }
        return list;
    }

Is there **any way of exploring the markers on the current layer** and so update the size of these markers on zoomend event of map ?

**Comment by tobrun** [comment]
This repository is dedicated to gl-native and not gl-js. Feel free to reach out to us through https://www.mapbox.com/contact/ with any technical questions you have or feel free to open a ticket on the https://github.com/mapbox/mapbox-gl-js in case of a bug or a feature request. Closing since this is not the correct repo. Thank you for reaching out and using our products!
