### ISSUE TITLE
[iOS]Crash in -[MGLMapView addAnnotations:]

### ISSUE THREAD

**Issue by andrewstay** [mapbox/mapbox-gl-native#7224]
**Platform:** iOS
**Mapbox SDK version:** ios-v3.4.0-beta.2

**Regression:** This issue is not reproducible with 3.3.4

### Steps to trigger behavior

 1. Create an instance of MGLMapView
 2. Add annotations with random data
 3. Provide view for the created annotations via
```-[MGLMapViewDelegate mapView:viewForAnnotation:]```
4. Observe views are correctly instantiated and displayed in the map.
5. Remove existing annotations as following:
```[self.mapView removeAnnotations:self.mapView.annotations];```
6. Instantiate new random annotations and set them up into the instance of the map view
```[self.mapView addAnnotations:annotations];```

### Expected behavior
Application should not crash
### Actual behavior
Application crashes.

Please review the crash log and the test application attached.
Please read "readme.txt" for details on how to run the test application.

[StayMapboxAnnotationIssue.zip](https://github.com/mapbox/mapbox-gl-native/files/619168/StayMapboxAnnotationIssue.zip)

**Comment by frederoni** [comment]
I was able to reproduce the crash with `ios-v3.4.0-beta.2` but not beta 3 or 4.
Most likely fixed by https://github.com/mapbox/mapbox-gl-native/pull/6957
