### ISSUE TITLE
preinstall: `npm install node-pre-gyp` error

### ISSUE THREAD

**Issue by 603e** [mapbox/mapbox-gl-native#7234]
#Windows_NT 6.3.9600，node v6.9.1:
mapbox 4.6.0
 1.npm install --save mapbox-gl
 2.npm install -g tileserver-gl
### Expected behavior
install success
### Actual behavior
default,
stack Error: mapbox-gl-native@3.3.3 preinstall: `npm install node-pre-gyp`
35771 error Windows_NT 6.3.9600
35772 error argv "F:\\node\\nodejs\\node.exe" "F:\\node\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "tileserver-gl"
35773 error node v6.9.1
35774 error npm  v3.10.8
35775 error code ELIFECYCLE
35776 error mapbox-gl-native@3.3.3 preinstall: `npm install node-pre-gyp`
35776 error Exit status 4294963214
35777 error Failed at the mapbox-gl-native@3.3.3 preinstall script 'npm install node-pre-gyp'.
35777 error Make sure you have the latest version of node.js and npm installed.
35777 error If you do, this is most likely a problem with the mapbox-gl-native package,
35777 error not with npm itself.
35777 error Tell the author that this fails on your system:
35777 error     npm install node-pre-gyp
35777 error You can get information on how to open an issue for this project with:
35777 error     npm bugs mapbox-gl-native
35777 error Or if that isn't available, you can get their info via:
35777 error     npm owner ls mapbox-gl-native
35777 error There is likely additional logging output above.
35778 verbose exit [ 1, true ]

**Comment by friedbunny** [comment]
This project does not support Windows.
