### ISSUE TITLE
[iOS] Allow annotations zOrder change

### ISSUE THREAD

**Issue by andrewstay** [mapbox/mapbox-gl-native#7243]
**Platform:** iOS
**Mapbox SDK version:** ios-v3.4.0-beta.4

Please expose API to manipulate zOrder of already added annotations.
```-[MGLMapView bringAnnotationsToFront:annotations]```

Video reference:
https://www.dropbox.com/s/jvcx380342x71fd/zOrder.mov?dl=0

**Comment by jfirebaugh** [comment]
Thanks -- we're tracking this request in #1728.
