### ISSUE TITLE
Hide/Show Markers based on priority on visible map resion

### ISSUE THREAD

**Issue by guruduttstay** [mapbox/mapbox-gl-native#7245]
Platform: Android 
Mapbox SDK version: 4.2.0-beta.4 

### Steps to trigger behavior

We want to show top 20 highest rated POIs/places in visible map region on screen

While changing/Zooming/Panning map region : 
 - Find top 20 high rated POI's / places in visible map region on screen
 - Check if Markers for those POI's :
    - If exists : Do Nothing
    - If not :  Add them
    - If not needed : Remove them
Result : https://www.dropbox.com/s/o2p8k5kzplqyhs6/AddRemoveMarkersDynamically.mp4?dl=0

### Expected behavior
 - Add markers gracefully (Animated way) while adding start from zero opacity to 100% visible withing few milli second 
 - No flickering while zooming/panning

### Actual behavior
 - As shown in above Video

I tried to replace Marker with MarkerView but MarkerView is lagging 
MarkerView looks like : https://www.dropbox.com/s/v9g5tl8o0qj9qah/MarkerView.mov?dl=0

Looks like MarkerView is not in Sync with OpenGL

What is best way of Adding/removing OR Hiding/Showing Markers in Map Dynamicelly while zooming / Panning ?

**Comment by guruduttstay** [comment]
Hi

I have introduced a Symbollayer now and not using Marker 


 - I have followed e.g. https://goo.gl/mXoBQW

 - I added one layer for each Pin ( there are 300 to 700 pins for each city bounding-box)
 - Now based on visible map on screen I find top 20 places/pins I show or hide the pin.
    Here I set visibility of layer since each layer is one pin

bit whole map is little sluggish/ performance is compromised here  :(

Is it possible to add bunch or layers together to map ... I am adding one by one for now ?
that might boost performance

**Comment by guruduttstay** [comment]
Hi

I did some optimisation  but still maps seems to be little bit lagging 

Performance : http://bit.ly/2gUpVpN

NB : I have added one SymbolLayer for each Pin, but if you notice in video Dot pins are over bigger Pins  :(

Is is possible to set Z-Order index for Symbol Layer ?

**Comment by jfirebaugh** [comment]
Hi @guruduttstay. We discussed performance implications of many layers over in #7348. Please note that this issue tracker is for reporting bugs or requesting features. If you have further questions about how to _use_ Mapbox products, please refer to our [support resources](https://www.mapbox.com/help/).
