### ISSUE TITLE
MGLStyleFunction must have at least one stop

### ISSUE THREAD

**Issue by frederoni** [mapbox/mapbox-gl-native#7249]
Raise an exception if MGLStyleFunction is initialized without any stops.

ref #7248

**Comment by 1ec5** [comment]
Is #6095 still an issue? Can `mbgl::style::StyleLayer` property accessors return unset optionals these days, or do hey still return stopless functions?

**Comment by jfirebaugh** [comment]
To my knowledge, they've never returned stopless functions. When a property is unset, the accessor returns a `PropertyValue` set to the ["undefined"](https://github.com/mapbox/mapbox-gl-native/blob/5f29c3ba26f84c8aea6f70640c348b32cdf397bf/include/mbgl/style/property_value.hpp#L27) variant value.

**Comment by boundsj** [comment]
This was fixed by https://github.com/mapbox/mapbox-gl-native/pull/7309
