### ISSUE TITLE
Support MapItemView, MapQuickItem, MapPolyline, etc.

### ISSUE THREAD

**Issue by Phrogz** [mapbox/mapbox-gl-native#7252]
**Platform:** Ubuntu 14.04, Qt 5.7
**Mapbox SDK version:** ToT

### Steps to trigger behavior

Create QML using one of the [QML Maps types](http://doc.qt.io/qt-5/qtlocation-qmlmodule.html#maps-qml-types) as a child of a `MapboxMap`, e.g.:

```qml
MapboxMap {
  center: QtPositioning.coordinate( 37.373110, -121.966708 )
  MapQuickItem {
    coordinate: parent.center
    sourceItem: Image { ... }
  }
}
```
### Expected behavior
The ability to display QML items over the map whose location is determined by GPS coordinates, and which pan and zoom along with the map.

### Actual behavior
`MapQuickItem` and `MapPolyline` do not show anything on screen.

**Comment by brunoabinader** [comment]
@Phrogz we don't currently support map items for `QQuickMapboxGL`.

However, we are working together with Qt Company developers to provide Mapbox GL as a plugin for QtLocation Map QML item - which provides supports for all QML map items as documented. As an example, the screenshot below shows Mapbox GL plugin with a QML map item pointing to Qt Company's HQ in Oslo:
<img width="562" alt="screen shot 2016-12-08 at 12 31 50 pm" src="https://cloud.githubusercontent.com/assets/76133/21094091/e8407088-c05d-11e6-85cb-1b7d713795b5.png">

You can follow our progress here:
https://codereview.qt-project.org/#/c/173790/
https://codereview.qt-project.org/#/c/177175/

(cc @tmpsantos)

**Comment by Phrogz** [comment]
@brunoabinader Thanks for the answer. Can you clarify:

1. If not `MapQuickItem`, how do you suggest that we overlay QML items on a `MapboxMap`?
2. When GL works as a QML `Map` plugin, what are the tradeoffs for using `Map` vs. `MapboxMap`? Under what circumstances would you recommend using a `MapboxMap` instead of a `Map`?

**Comment by tmpsantos** [comment]
> If not MapQuickItem, how do you suggest that we overlay QML items (or other custom content) geolocated on a MapboxMap?

You could do like we did for the blue route line example (with start/finish markers). The limitation is they are not user interactive.

> When GL works as a QML Map plugin, what are the tradeoffs for using Map vs. MapboxMap? Under what circumstances would you recommend using a MapboxMap instead of a Map?

When GL works on QML Map and the integration is completed on the Qt SDK, there is no need for using MapboxMap anymore since all the features will be on QML Map after selecting the "mapboxgl" plugin. We can probably get rid of MapboxMap and the main challenge would be backport the work done on 5.9 to an older version of Qt like 5.6 since not everyone will be upgrading to 5.9 immediately.

@Phrogz That said, how willing are you to try Qt 5.9? The current status of the Mapbox integration is quite functional and we just got tilt and pitch working today. You will get the QML Item integration for free on the 5.9 branch.

**Comment by joeroback** [comment]
Is 5.9 in the public Qt5 repo? I only see 5.8 stuff.

Additional question, are routes functioning (via QtRoute) in 5.9?

**Comment by tmpsantos** [comment]
@joeroback 5.9 is the `dev` branch.

Before building, you have to checkout the qtlocation submodule to:
https://github.com/tmpsantos/qtlocation/tree/mapboxgl

Or the latest on (we are keeping both in sync):
https://codereview.qt-project.org/#/c/177175/

Mapbox GL Native is a git submodule of this qtlocation branch, so when you build qtlocation, it should build the plugin + mapbox stuff automatically.

All the QML models for route and polylines should work.

**Comment by tmpsantos** [comment]
What is not implemented in this branch is any of the runtime style extensions exposed via MapParameter, but for what you want (QML Item) it won't be needed.

**Comment by thawfeekyahya** [comment]
Hello,

I am trying to use the heat map feature of mapbox , but I couldn't find a way to do with the Map Plugin or the MapParameter Plugin.  I am trying to do this 

MapParameter { 
type:"layer";
property var name:"heatmapLayer";
property var layerType : "heatmap";
property var source: "geoDataSource":
}

**Comment by brunoabinader** [comment]
Hi @thawfeekyahya, the current Qt QML plugin does not support heatmaps. We are in the process of updating the Mapbox GL version there to get this feature on the next Qt 5.11.1 release: 

https://codereview.qt-project.org/#/c/221316

Please keep in mind that this repository contains only the C++ API (`QMapboxGL`). QML-related bugs can be opened in http://bugreports.qt.io - thanks!
