### ISSUE TITLE
Make gl-native handling of newlines conform to gl-js behavior

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native#7253]
When I ported my recent gl-native line breaking changes to gl-js, I found that gl-js has tests for labels with newlines in them (https://github.com/mapbox/mapbox-gl-js/blob/master/test/js/symbol/shaping.test.js). The gl-js tests expect each newline to cause a new line to be created, while gl-native will just treat them like whitespace (so two newlines in the middle of your label will be collapsed down to just one breaking point instead of inserting a blank line).

I'm not sure when we would expect labels to have newlines in them, but we should probably standardize on one behavior or the other.

cc @ansis @1ec5

**Comment by 1ec5** [comment]
The GL JS behavior sounds more correct.

**Comment by ChrisLoer** [comment]
Ah, I just had to look through the file history to see it was recently added as an enhancement: https://github.com/mapbox/mapbox-gl-js/issues/955

**Comment by ChrisLoer** [comment]
I'll address this with a port of https://github.com/mapbox/mapbox-gl-js/pull/3743 to gl-native. I have the code ready, but waiting for the first PR to go in before making a new PR to keep the test changes from conflicting.

**Comment by 1ec5** [comment]
This is happening in mapbox/mapbox-gl-native#7446.

**Comment by ChrisLoer** [comment]
Closed with mapbox/mapbox-gl-native#7446.
