### ISSUE TITLE
MGLMapView should be non-opaque by default

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7256]
In https://github.com/mapbox/mapbox-gl-native/issues/3101#issuecomment-263752036, @mxcl argues that MGLMapView’s `isOpaque` property should be set to `NO` by default on iOS. In #3096, I originally defaulted `isOpaque` to `NO` but switched it back to `YES` out of concern that performance might be impacted. Assuming the flash of black is still a problem, I’m in favor of making the map view non-opaque by default. On macOS, we render the map in an NSOpenGLLayer, which like all CALayers is transparent by default, and I haven’t noticed any problems stemming from that choice.

Alternatively, we could mitigate the flash without impacting performance by defaulting `isOpaque` to `NO` at initialization, then switching it to `YES` as soon as the style finishes loading for the first time (unless the developer has manually set `isOpaque` in the meantime).

/cc @incanus @frederoni

**Comment by friedbunny** [comment]
I’m also in favor of moving ahead with the switch to `MGLMapView.opaque = NO`. Being that this  change that would be trivial to revert in a patch release, would there be any issues with putting this on the v3.4.0 or v3.4.1 milestones?

**Comment by 1ec5** [comment]
I’d be fine with either v3.4.0 or v3.4.1. Any PR that changes the default should come with profiles comparing performance before and after (just due diligence, nothing extremely detailed).

**Comment by friedbunny** [comment]
Certainly we should run iosbench, but I suspect the results will be inconclusive as to the absolute effect — last time I ran it, we were maxing out at 60 FPS consistently. Perhaps an impetus to expand iosbench.

**Comment by incanus** [comment]
> last time I ran it, we were maxing out at 60 FPS consistently

Hmm, this is in conflict with #5489. Are we sure about this, or am I misunderstanding what we're talking about?

**Comment by friedbunny** [comment]
@incanus [iosbench](https://github.com/mapbox/mapbox-gl-native/blob/2cf238f74eef021b5dd097822ceafc6da83cf4d3/platform/ios/benchmark/MBXBenchViewController.mm) doesn’t stress the map terribly these days — it doesn’t add any sort of annotation and focuses almost solely on core rendering performance. The goal has always been to expand the range of tests in iosbench, and perhaps this is a good opportunity.

**Comment by incanus** [comment]
Right, but my point is that even bare, we have not been hitting 60fps, hence the annotation sync problem root. Are we now reliably doing that?

**Comment by 1ec5** [comment]
All iosbench does is render the same viewport over and over again. The framerate issues we were seeing over in #5489 are only triggered when panning, zooming, or rotating the map.

**Comment by 1ec5** [comment]
Fixed in #7859 on the release-ios-v3.4.0 branch.
