### ISSUE TITLE
Standardize NSException names

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7258]
Most of the NSExceptions we raise in the iOS and macOS SDKs are named with ad-hoc names such as “Value not handled”. Instead, we should either use one of the [predefined exception names](https://developer.apple.com/reference/foundation/1613022-foundation_constants/1660462-general_exception_names?language=objc) or define a string constant such as “MGLIdentifierCollisionException” in MGLTypes.h for use with these exceptions. This way, test code can more easily check for the exception with `XCTAssertThrowsSpecificNamed()`, and we could start adding notes about exception conditions in our method documentation.

/cc @incanus @frederoni

**Comment by fabian-guerra** [comment]
[Predefined exception names](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Exceptions/Concepts/PredefinedExceptions.html#//apple_ref/doc/uid/20000057-BCIGHECA) link update.
