### ISSUE TITLE
Slow tiles rendering

### ISSUE THREAD

**Issue by Daard** [mapbox/mapbox-gl-native#7260]
**Android:**
**com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0-beta.5@aar:**

### Steps to trigger behavior

 1. After zoom in / zoom out tiles render slowly. 
 2. Can't set cache size or clear it. 
 3. If I change raster tiles on server, they would be changed only after user interacts with map and tries to move camera position.
 4. I have tried to run clear, invalidate, remove raster layer and add new one, but tiles will be replaced only after user interactions are done. 

### Expected behavior
Week design patterns, developer could not set TileProvder for custom tiles. This could be reached only by mocking server side or launching device server.

**Comment by jfirebaugh** [comment]
Sorry, I can't understand the issue you're reporting here.
