### ISSUE TITLE
Problems we encounter in our qmake project

### ISSUE THREAD

**Issue by rasmusgissweden** [mapbox/mapbox-gl-native#7263]
Hello team!

We have a project that we do not want to convert to cmake (or can't, we already include other qmake projects and we see no gain in converting them). This is the problems we encounter:

* We do not know how to cross-compile mapbox-gl-native for the QT platform in the current configuration.
* We do not know how to include mapbox-gl-native in our project.

best regards
/Anders/Rasmus/Johan

**Comment by brunoabinader** [comment]
Hi @rasmusgissweden :-) @tmpsantos made a development branch that provides QMake support: https://github.com/mapbox/mapbox-gl-native/tree/tmpsantos-qt_vendor

Please notice this is still a work-in-progress.

**Comment by rasmusgissweden** [comment]
Hello!

Thanks a lot!

I will test it now!

Best Regards
/ Rasmus

Den 2016-12-08 kl. 14:23, skrev Bruno de Oliveira Abinader:

**Comment by tmpsantos** [comment]
@rasmusgissweden do not forget to give us feedback :smile:
