### ISSUE TITLE
Marker My location above popup

### ISSUE THREAD

**Issue by dsilvera** [mapbox/mapbox-gl-native#7264]
**Platform:** Android
**Mapbox SDK version:** 4.2.0

### Steps to trigger behavior

 1. Localize my position
 2. Open a popup around my position marker

### Expected behavior
My position marker is behind the popup

### Actual behavior
The popup is behind my position marker

### Fix
To fix it, we can inverse the block with id "userLocationView" and the block with id "markerViewLayout" on mapview_internal.xml file.

**Comment by cammace** [comment]
I wasn't able to reproduce this issue could you clarify how you are adding the user location marker. 

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5652865/20805620/6c68b6dc-b7c5-11e6-9b31-b969377964fb.gif)

**Comment by dsilvera** [comment]
Sorry.... I don't have the good version of Mapbox...
It's ok.
