### ISSUE TITLE
Document MapParameter usage

### ISSUE THREAD

**Issue by Phrogz** [mapbox/mapbox-gl-native#7268]
**Platform:** Ubuntu 14.04, Qt 5.7
**Mapbox SDK version:** b1068b432ee17c14ea756b7c48be4c955303de95

### Steps to trigger behavior

1. Build `qt-qml-app` demo app.
   * _It works! Yay!_
2. Attempt to use in a real project in a non-trivial manner.
3. Get confused about the proliferation of `MapParameter` elements with generic `property` that use metaprogramming to perform some magic.
4. Search for documentation on `MapParameter` options.

### Expected behavior

Documentation about all the legal `type` properties for a `MapParameter`, and the sub-properties required or allowed for each. Perhaps expose `type` as an actual property on `MapParameter` so that real usage would be:

```qml
MapParameter {
   type: 'pitch' // Note: no "property var" prefix
   property real angle: 15
}
```

### Actual behavior
No way of knowing what `type` are allowed, what values they use. No way to figure out how to (for example) dynamically change a `routeSource` to new data as it arrives, instead of a static JSON file as shown in the demo QML.

**Comment by tmpsantos** [comment]
This was done here:
https://doc-snapshots.qt.io/qt5-5.9/location-plugin-mapboxgl.html#optional-map-parameters

**Comment by ducmaxime** [comment]
Hello, I try 
MapParameter {
      type: 'pitch'
 property real angle: 15
}

But it's not working.

Any idea ?

Thx
