### ISSUE TITLE
"Cannot determine host platform"

### ISSUE THREAD

**Issue by AndersBillLinden** [mapbox/mapbox-gl-native#7269]
**Platform: Windows 10**

### Steps to trigger behavior

 1. run bash in windows 10
 2. In the folder where the Makefile is, run `make qt-lib`

### Expected behavior
I expect this operation to create a mapbox library, useable in a QT application.

### Actual behavior
This error message comes up:
````
Cannot determine host platform.  Stop.
````

**Comment by jfirebaugh** [comment]
Windows is not a supported platform at this time.

**Comment by AndersBillLinden** [comment]
Thanks for the information. Do you know if it will be supported at any time?

**Comment by AndersBillLinden** [comment]
Also, is there a reason for Windows to not be supported?

**Comment by AndersBillLinden** [comment]
If this was a qmake project, it would automatically be possible to build on windows. So why did you convert it to cmake?

**Comment by brunoabinader** [comment]
@AndersBillLinden @tmpsantos made a development branch that provides QMake support: https://github.com/mapbox/mapbox-gl-native/tree/tmpsantos-qt_vendor

Please notice this is still a work-in-progress.

**Comment by tmpsantos** [comment]
@AndersBillLinden I did manage to build Mapbox GL Native + Qt on Windows 10 but using CMake and Visual Studio + CodeGen. This is not supported though, and it was done as a personal side project.

**Comment by AndersBillLinden** [comment]
I will try myself. But you did not write a cmake to qmake converter?

**Comment by tmpsantos** [comment]
> I will try myself. But you did not write a cmake to qmake converter?

No, tried that but it was getting too complicated so I just made a `.pro` from scratch and it turned out to be rather simple.
