### ISSUE TITLE
Fatal Exception: java.lang.Error No config chosen

### ISSUE THREAD

**Issue by DmitryTankovich** [mapbox/mapbox-gl-native#7273]
com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay (SourceFile)
com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay (SourceFile:100)
com.mapbox.mapboxsdk.maps.MapView.onCreate (SourceFile:435)

MapBox 'com.mapbox.mapboxsdk:mapbox-android-sdk:4.1.1@aar'
Samsung Galaxy Tab P7500
OS 4.0.4
Screen 10.1", 1280x800

**Comment by cvance** [comment]
Getting the same crash on 4.2.0 on the following devices:

Motorola XOOM MZ601
Sony Tablet S
Asus Transformer TF101

all running Android 4.0.4 or 4.0.3

**Comment by Namarcil** [comment]
Hello !

This crash is the top crash of our application. It is happening quite often and we would like to get rid of it.

Here is some information about it : 
![fabric_screenshot](https://cloud.githubusercontent.com/assets/4331720/23652574/bdcd61da-0329-11e7-87ac-bdd207bb42a8.png)

We are using Mapbox 4.2.2

Impacted devices are tablets. 

I'll be available if you need more infos.

**Comment by SylvainHocq** [comment]
Getting the same crash

**Comment by algoroq** [comment]
For Mapbox **v5.1.0-beta.1** there is still this issue. Is this issue in ralation with this one #8810 ?

Sony Tablet S (Android 4.0.3):
```
Fatal Exception: java.lang.Error: No config chosen
at com.mapbox.mapboxsdk.maps.NativeMapView.nativeInitializeDisplay(NativeMapView.java)
at com.mapbox.mapboxsdk.maps.NativeMapView.initializeDisplay(NativeMapView.java:130)
at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(MapView.java:205)
at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:200)
```

**Comment by tobrun** [comment]
We recently revamped our egl setup with the introduction of GlSurfaceView, feel free to report if this is still an issue. Closing for now.
