### ISSUE TITLE
Error: mapbox-gl-native@3.3.3 preinstall: `npm install node-pre-gyp`

### ISSUE THREAD

**Issue by 603e** [mapbox/mapbox-gl-native#7277]
**Platform:windows 8 **
### Steps to trigger behavior
1、Node v6.2.0
2、Python27
3、npm install -g tileserver-gl

 35816 verbose lifecycle mapbox-gl-native@3.3.3~preinstall: unsafe-perm in lifecycle true
35817 verbose lifecycle mapbox-gl-native@3.3.3~preinstall: PATH: F:\node\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\liulx\AppData\Roaming\npm\node_modules\.staging\mapbox-gl-native-b5cbd091\node_modules\.bin;C:\Users\liulx\AppData\Roaming\npm\node_modules\.bin;F:\node\nodejs;C:\Program Files (x86)\Common Files\NetSarang;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\research\tomcat-7.0.64\bin\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\TortoiseSVN\bin;D:\research\study\instantclient12_1-x64;D:\Program Files\TortoiseGit\bin;F:\node\nodejs\;C:\Program Files\Java\jdk1.8.0_112\bin;D:\GreenSoft\elasticsearch-5.0.1;C:\Users\liulx\AppData\Roaming\npm;D:\Program Files\Git\cmd
35818 verbose lifecycle mapbox-gl-native@3.3.3~preinstall: CWD: C:\Users\liulx\AppData\Roaming\npm\node_modules\.staging\mapbox-gl-native-b5cbd091
35819 silly lifecycle mapbox-gl-native@3.3.3~preinstall: Args: [ '/d /s /c', 'npm install node-pre-gyp' ]
35820 silly lifecycle uglify-js@2.7.5~preinstall: no script for preinstall, continuing
35821 silly lifecycle handlebars@4.0.5~preinstall: no script for preinstall, continuing
35822 silly lifecycle tileserver-gl@1.1.5~preinstall: no script for preinstall, continuing
35823 silly lifecycle mapbox-gl-native@3.3.3~preinstall: Returned: code: 4294963214  signal: null
35824 info lifecycle mapbox-gl-native@3.3.3~preinstall: Failed to exec preinstall script
35825 verbose unlock done using C:\Users\liulx\AppData\Roaming\npm-cache\_locks\staging-89f629d240db16ce.lock for C:\Users\liulx\AppData\Roaming\npm\node_modules\.staging
35826 silly rollbackFailedOptional Starting
35827 silly rollbackFailedOptional Finishing
35828 silly runTopLevelLifecycles Starting
35829 silly runTopLevelLifecycles Finishing
35830 silly install printInstalled
35831 verbose stack Error: mapbox-gl-native@3.3.3 preinstall: `npm install node-pre-gyp`
35831 verbose stack Exit status 4294963214
35831 verbose stack     at EventEmitter.<anonymous> (F:\node\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
35831 verbose stack     at emitTwo (events.js:106:13)
35831 verbose stack     at EventEmitter.emit (events.js:191:7)
35831 verbose stack     at ChildProcess.<anonymous> (F:\node\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
35831 verbose stack     at emitTwo (events.js:106:13)
35831 verbose stack     at ChildProcess.emit (events.js:191:7)
35831 verbose stack     at maybeClose (internal/child_process.js:850:16)
35831 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
35832 verbose pkgid mapbox-gl-native@3.3.3
35833 verbose cwd F:\node\nodejs
35834 error Windows_NT 6.3.9600
35835 error argv "F:\\node\\nodejs\\node.exe" "F:\\node\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "tileserver-gl"
35836 error node v6.2.0
35837 error npm  v3.8.9
35838 error code ELIFECYCLE
35839 error mapbox-gl-native@3.3.3 preinstall: `npm install node-pre-gyp`
35839 error Exit status 4294963214
35840 error Failed at the mapbox-gl-native@3.3.3 preinstall script 'npm install node-pre-gyp'.
35840 error Make sure you have the latest version of node.js and npm installed.
35840 error If you do, this is most likely a problem with the mapbox-gl-native package,
35840 error not with npm itself.
35840 error Tell the author that this fails on your system:
35840 error     npm install node-pre-gyp
35840 error You can get information on how to open an issue for this project with:
35840 error     npm bugs mapbox-gl-native
35840 error Or if that isn't available, you can get their info via:
35840 error     npm owner ls mapbox-gl-native
35840 error There is likely additional logging output above.
35841 verbose exit [ 1, true ]

**Comment by jfirebaugh** [comment]
Windows is not a supported platform at this time.
