### ISSUE TITLE
Many visibility warnings building macOS SDK

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7281]
As of 84038832e45c2445b43b39ccb2f9e29c8646dac0 on master, a clean build of the macOS SDK in Xcode 8.2 results in 136 warnings of the following form:

```
ld: warning: direct access in function 'mbgl::Tileset const& mapbox::util::variant<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mbgl::Tileset>::get<mbgl::Tileset, (void*)0>() const' from file '/Users/mxn/hub/mapbox-gl-native/build/macos/Debug/libmbgl-core.a(offline_download.o)' to global weak symbol 'typeinfo for mapbox::util::bad_variant_access' from file '/Users/mxn/hub/mapbox-gl-native/build/macos/macos.build/Debug/dynamic.build/Objects-normal/x86_64/NSArray+MGLAdditions.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

`GCC_SYMBOLS_PRIVATE_EXTERN` is `YES` for the dynamic target in macos.xcodeproj (whereas it’s `NO` for the dynamic and static targets in ios.xcodeproj), but setting it to `NO` doesn’t address the issue.

This issue doesn’t reproduce on the release-ios-v3.4.0 branch.

/cc @kkaefer

**Comment by 1ec5** [comment]
Actually, setting `GCC_SYMBOLS_PRIVATE_EXTERN` to `NO` does address the issue. It appears to have been set to `YES` in #7188.

**Comment by kkaefer** [comment]
`GCC_SYMBOLS_PRIVATE_EXTERN` adds `-fvisibility=hidden` for static libraries/executables, but apparently doesn't do this for dynamic libraries.

**Comment by 1ec5** [comment]
What about the iOS dynamic framework? I haven’t noticed these warnings there.

**Comment by kkaefer** [comment]
That's because we're not yet compiling iOS with `-fvisibility=hidden` for the core library. PR for iOS is at https://github.com/mapbox/mapbox-gl-native/pull/7131
