### ISSUE TITLE
MapboxMap should have methods to list layers and sources

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7285]
`MapboxMap` should have the following methods, which are possible now that #6097 has landed in master:

* `List<Layer> getLayers()`
* `void addLayerAfter(Layer, String)` (not sure about the naming, but adding a layer _above_ a particular layer is more commonplace than adding one _below_ it)
* `void addLayer(int, Layer)`
* `Layer removeLayer(int)`
* `List<Source> getSources()`

Additionally, `removeLayer(Layer)` and `removeLayer(String)` should return `Layer`.

These methods will all be present in iOS SDK v3.4.0 and macOS SDK v0.3.0. Labeling as <kbd>GL JS parity</kbd> because these operations are also possible in GL JS using `getStyle()` and `setStyle()`.

/cc @ivovandongen

**Comment by tobrun** [comment]
Capturing from talks with @ivovandongen that we should hold on implementing this until #6533 lands else this would result in doing the work twice.
