### ISSUE TITLE
MGLMapView causes "Allow x to access your location" popup to disappear if showUserLocation is enabled

### ISSUE THREAD

**Issue by danpat** [mapbox/mapbox-gl-native#7286]
**Platform:** iOS 10.1
**Mapbox SDK version:** 3.4.0-beta.4

### Steps to trigger behavior

 1. Add an MGLMapView to a storyboard, and set the "Show User Location" property to "yes".
 2. In `viewDidLoad()`, execute a snippet like this:
```
        locationManager = CLLocationManager.init()
        locationManager!.delegate = self
        locationManager!.desiredAccuracy = kCLLocationAccuracyNearestTenMeters

        let authstatus = CLLocationManager.authorizationStatus()
        if (authstatus == .authorizedAlways || authstatus == .authorizedWhenInUse ) {
            locationManager!.startUpdatingLocation()
            mapView!.showsUserLocation = true
        } else {
            locationManager!.requestWhenInUseAuthorization()
            mapView!.showsUserLocation = false
        }
```
 3.  App will start and "Allow x to access your location" will appear.  Wait 10-20 seconds and the popup will disappear without user interaction.

Disabling the "Show User Location = YES" default appears to fix the problem - the popup stays visible indefinitely.

### Expected behavior

The status of "Show User Location" shouldn't affect the authorization popup visibility.

### Actual behavior

The popup disappears without user interaction, leaving the app in an undetermined authorization state.

**Comment by lilykaiser** [comment]
Closing due to ticket age. If this is still a problem, please re-open
