### ISSUE TITLE
High level API around Offline

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#7289]
The `4.0.0` release introduced the offline feature in the Android SDK. This allows developers to download and use maps in situations where no internet is available. While the implementation meets the requirements for developers. It's isn't as easy to implement since the user is required to do the state management themselves. I'm proposing to write an API layer on top of this by using a Service. This would provide the end user of an experience similar to what other map apps are doing. Allowing them to hook into a sticky Android Service and show a notification. What concretely is added to this API in terms of GUI is TBD.

Will update this ticket with some screenshots to make the suggested UX more obvious.

@mapbox/android

**Comment by tobrun** [comment]
I believe the following use-case fits the UX that developers want to achieve with offline:

### List regions: 

![device-2016-12-06-000013](https://cloud.githubusercontent.com/assets/2151639/20906151/fe086e3c-bb46-11e6-81b8-c8da657994b4.png)

Not sure if we need to support adding an UI for ease of integration, we already support the low level API of retrieving regions/renaming them.

### Select a region

![device-2016-12-05-233546](https://cloud.githubusercontent.com/assets/2151639/20906098/c5ce4b36-bb46-11e6-90cb-f427bcf08dd5.png)

As with screenshot before, not sure if we should add an UI for ease of integration, the user can provide a LatLngBounds as a region definition with the low level API. 

### Show progress as a notification

![device-2016-12-05-233854](https://cloud.githubusercontent.com/assets/2151639/20906111/dee6492a-bb46-11e6-8b10-aabdd161c79e.png)

This step is the part for which I created this ticket. When we click download an Android SDK Service should be started and show the download progress to the user. The benefit of using a Service here is that the service is retained even if the app goes to background (it will show a notification to show download progress). Clicking the progress brings the user back to the region selection screen with an optional cancel (or this can be integrated as part of the notification).

**Comment by cammace** [comment]
I like the idea of the notification and download of the region being done in the background. When it comes to the list and region selection, I think this should be left to the developers since it's already simple to grab the list of regions downloaded, navigate to that region, etc.

**Comment by abourtema** [comment]
I have problem , I use Mapbox in android , the app run good but when download map show me Mapbox tile count limit exceeded: 6000 , I use less 400 tile

**Comment by zugaldia** [comment]
> I'm proposing to write an API layer on top of this by using a Service. 

Agreed with the approach. Wondering though if this is something worth adding to the SDK, or if the Android demo app + Mapbox.com docs would be a better location for this code (at least on a first iteration). Thoughts?

**Comment by tobrun** [comment]
> Agreed with the approach. Wondering though if this is something worth adding to the SDK, or if the Android demo app + Mapbox.com docs would be a better location for this code (at least on a first iteration). Thoughts?

Agreed with that approach as well 👍 Will try creating follow up tickets so we can close this one.

**Comment by 1ec5** [comment]
> the user can provide a LatLngBounds as a region definition with the low level API.

Users might appreciate being able to specify the minimum and maximum zoom levels via a double-ended slider, thereby cutting down on data usage and storage.

**Comment by tobrun** [comment]
This issue is going to be implemented as a plugin. See https://github.com/mapbox/mapbox-plugins-android/issues/19
