### ISSUE TITLE
Text field in symbol layer not updating at current zoom level

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#7294]
Similar to https://github.com/mapbox/mapbox-gl-native/issues/7225, Using the symbol layer and updating the text field doesn't change on the current zoom level. Only when zooming in or out the new text is displayed. 

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5652865/20902215/24e886ec-bb04-11e6-8095-dd661130ca42.gif)

_in the gif, clicking the symbol layer calls the distance API and changes the time field._

cc: @ivovandongen

**Comment by ivovandongen** [comment]
@cammace Do you have a example/branch where you've reproduced this?

**Comment by cammace** [comment]
This looks to be resolved in master after adding [this code](https://github.com/mapbox/mapbox-gl-native/pull/7318) to the symbol layer example. I'll need to check tomorrow to see if the SNAPSHOT (which is building from release branch) contains the fix or not.

**Comment by jfirebaugh** [comment]
@cammace Good to close here?
