### ISSUE TITLE
MarkerViewOptions.anchor() moves the clickable area

### ISSUE THREAD

**Issue by MariusBoepple** [mapbox/mapbox-gl-native#7307]
**Platform:** Android
**Mapbox SDK version:** 4.2.0-beta.5

### Steps to trigger behavior

 1. Create a Marker with <code>MarkerViewOptions</code>, a Bitmap icon and set <code>.anchor(0.5f, 1f)</code> to center the pin's needle.
 2. Set a <code>OnMarkerClickListener</code> to receive clicks.

### Expected behavior
The clickable area are the Bitmap's bounds.

### Actual behavior
The clickable area is shifted to the bottom centering the anchor - therefore the upper area of the marker is not clickable.

**Comment by tobrun** [comment]
@MariusBoepple thank you for reaching out! This issue and a general improvement to our click handling system related to Marker and MarkerViews is documented in #6761. I now have added a note in https://github.com/mapbox/mapbox-gl-native/issues/6761#issuecomment-265453234 to look into anchoring while looking into that issue. Closing as a duplicate and thanks again for taking the time to report this issue.
