### ISSUE TITLE
consider dev update notification in IDE

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#7311]
Noticed something in the Realm Swift SDK the other day which I thought was pretty cool and could be useful for our mobile SDKs. 

When you fire up your app (at least in Xcode) it lets you know if there is a new version available each and every launch: 

```
2016-12-05 14:20:17.662 AppName[10934:484937] Version 2.1.1 of Realm is now available: https://github.com/realm/realm-cocoa/blob/v2.1.1/CHANGELOG.md
```

This is a nice feature and is both a notification as well as a subtle reminder to keep up to date. We could probably do it on Android, too (though IIRC the console is usually more verbose there and it might be missed). 

@mapbox/ios @mapbox/android

**Comment by 1ec5** [comment]
Realm runs a version-checking Web service. Here’s the [client-side code](https://github.com/realm/realm-cocoa/blob/216333cf82e1afcba5e6c4547e6fb983165d510f/Realm/RLMUpdateChecker.mm#L41), which runs only in the Simulator.

**Comment by incanus** [comment]
> runs only in the Simulator

Ooh, neat. 👍

**Comment by tobrun** [comment]
That is pretty cool, for android we could hook into the `BuildConfig.DEBUG`.

Side note: below is the most straightforward way of notifying users directly in the IDE:

<img width="700" alt="screen shot 2016-12-06 at 18 45 08" src="https://cloud.githubusercontent.com/assets/2151639/20936783/3c5b37d0-bbe4-11e6-90aa-00b76fe944db.png">

It seems that this configuration isn't enabled by default for non-Google dependencies and requires the developer to enable this  😞.

**Comment by friedbunny** [comment]
I really like this idea, especially as Realm has implemented it (e.g., simulator-only). Google Maps iOS SDK prints a similar message:

> New version of Google Maps SDK for iOS available: 2.1.28321.0

**Comment by tobrun** [comment]
Noticed today that Realm is showing an update notice it in the gradle console:

<img width="813" alt="screen shot 2017-03-03 at 10 18 09" src="https://cloud.githubusercontent.com/assets/2151639/23556489/d2d97816-fffa-11e6-9a3f-003a27874531.png">

**Comment by friedbunny** [comment]
This happened for iOS in #8282.

**Comment by tobrun** [comment]
Capturing from convo with @chloekraw and @LukasPaczos that default setup in https://github.com/mapbox/mapbox-gl-native/issues/7311#issuecomment-265222813 is sufficient for Android. Removing label

**Comment by friedbunny** [comment]
Cool, then I think we’re done here (unless @1ec5 has plans for this?).

**Comment by 1ec5** [comment]
> unless @1ec5 has plans for this? feel free to reopen

It’s tracked [on this project board](https://github.com/mapbox/mapbox-gl-native/projects/10#card-2132229) for macOS, just so it doesn’t fall off my radar as a theoretical improvement. But I don’t see a practical need for it at this time, given that any macOS map SDK clients are likely to be using either CocoaPods or Carthage.
