### ISSUE TITLE
Misspelled exception name when reusing source identifier

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7314]
`MGLRedundantSourceIdentiferException` should be spelled `MGLRedundantSourceIdentifierException`.

/ref #7272 https://github.com/mapbox/mapbox-gl-native/pull/7257#discussion_r91108771
/cc @boundsj @ivovandongen

**Comment by boundsj** [comment]
Fixed by https://github.com/mapbox/mapbox-gl-native/pull/7315
