### ISSUE TITLE
Logo and Attribution margins not working correctly

### ISSUE THREAD

**Issue by MariusBoepple** [mapbox/mapbox-gl-native#7322]
**Platform:** Android
**Mapbox SDK version:** 4.2.0-SNAPSHOT

### Steps to trigger behavior

 1. Set logo or attribution margins in dp.

### Expected behavior
Margins are set properly.

### Actual behavior
Margins are way too big. 

I think the cause is multiplying with the screen density when getting the dimensions.

`MapboxMapOptions.java` line 211

    mapboxMapOptions.attributionMargins(new int[]{(int) (typedArray.getDimension(R.styleable.MapView_attribution_margin_left, DIMENSION_SEVENTY_SIX_DP) * screenDensity)
                    , (int) (typedArray.getDimension(R.styleable.MapView_attribution_margin_top, DIMENSION_SEVEN_DP) * screenDensity)
                    , (int) (typedArray.getDimension(R.styleable.MapView_attribution_margin_right, DIMENSION_SEVEN_DP) * screenDensity)
                    , (int) (typedArray.getDimension(R.styleable.MapView_attribution_margin_bottom, DIMENSION_SEVEN_DP) * screenDensity)});

**Comment by tobrun** [comment]
@MariusBoepple I think you are correct, the dimensions retrieved from resources are already taking in account the screendensity.

**Comment by tobrun** [comment]
Looking into this, the brackets aren't correctly placed, fixing up.
