### ISSUE TITLE
Tiles loaded for rendering are inconsistent with what is specified via setZoomLevel. (Inconsistency between Source::getZoom and Map::getZoom)

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#733]
To reproduce the issue do the following:

1.) Call MGLMapView::setZoomLevel -- 13
2.) Change your emulator to retina. <==  This step is critical.
3.) Tap on toggle debug button. This would display tiles at level 14 instead of 13.

Now change the emulator to iPad/non-retina. and repeat steps 2) and 3). After step 3), you would see tiles at level 13.

Because of this issue, same map source would show different detail at same zoomlevel across devices.

The inconsistency happens because when computing the set of covering tiles at zoomlevel Source::getZoom aritifically increments it by 1 if contentScale ratio is higher than 1.

double Source::getZoom(const TransformState& state) const {
    double offset = std::log(util::tileSize / info.tile_size) / std::log(2);

   // Incrementing zoom aritificially for conent scale ration.
    offset += (state.getPixelRatio() > 1.0 ? 1 :0);
    return state.getZoom() + offset;
}

**Comment by incanus** [comment]
> The inconsistency happens because when computing the set of covering tiles at zoomlevel Source::getZoom aritifically increments it by 1 if contentScale ratio is higher than 1.

This happens for reasons of raster tiles, which are drawn 1/4 the size on retina and thus grab one lower-numbered zoom level.

**Comment by 1ec5** [comment]
This is the same thing as #907, right?

**Comment by jfirebaugh** [comment]
I believe so. Behavior I see currently is that z13 tiles are displayed for both retina and non-retina devices.
