### ISSUE TITLE
Restore -Wl,-bind_at_load to node OS X build

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#7332]
We used to set `-Wl,-bind_at_load` for the node OS X build, so that missing symbols would be caught at launch rather than when they are first needed at runtime. Without this flag, if unit tests fail to cover a particular code path, missing symbols can be overlooked.

It looks like this flag [got lost](https://github.com/mapbox/mapbox-gl-native/commit/692fe1f3ffc8f4364b39c14aa7d90cec2ff5c0a6#diff-21e418851ae48f9b11907837add9e39aL91) in the switch to CMake. We should restore it.

cc @kkaefer

**Comment by kkaefer** [comment]
This is easy to test e.g. by commenting back in the call to `showColorDebugImage` in `sprite_atlas.png`. That function is only defined when building with GLFW and should produce a missing symbol error for node.
