### ISSUE TITLE
[iOS]Missing markers after removeAnnotations/addAnnotations is called

### ISSUE THREAD

**Issue by andrewstay** [mapbox/mapbox-gl-native#7342]
**Platform:**iOS
**Mapbox SDK version:** ios-v3.4.0-beta.4

### Steps to trigger behavior

1. Create an instance of MGLMapView
2. Add annotations with random data
3. Provide view for the created annotations via
```-[MGLMapViewDelegate mapView:viewForAnnotation:]```
4. Observe views are correctly instantiated and displayed in the map.
5. Remove existing annotations as following:
```[self.mapView removeAnnotations:self.mapView.annotations];```
6. Instantiate new random annotations and set them up into the instance of the map view
```[self.mapView addAnnotations:annotations];```

### Expected behavior
All newly added annotations which fit the visible coordinates should be displayed.
### Actual behavior
The annotations which are located close the the edge of the visible bounds are not displayed. Only few annotations are visible in the map.

Please review the video  and the test application attached.
Please read "readme.txt" for details on how to run the test application.
[TestMapbox.zip](https://github.com/mapbox/mapbox-gl-native/files/638726/TestMapbox.zip)

https://www.dropbox.com/s/gnka3kf89bw0rup/AnnotationsIssue.mov?dl=0

**Comment by 1ec5** [comment]
Fixed in #7423 on the v3.4.0 release branch.

**Comment by boundsj** [comment]
Also, thanks so much @andrewstay for the detailed description and attaching the repro app. That was very helpful! [Beta 5](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.4.0-beta.5) is available so please test again with that version.
