### ISSUE TITLE
Update Marker Icon doesn't result in AnnotationManager::removeAnnotationIcon

### ISSUE THREAD

**Issue by AlexeyIke** [mapbox/mapbox-gl-native#7343]
Platform:Android
Mapbox SDK version:android-v4.2.0-beta.4

### Steps to trigger behavior

 1. Create many markers on map by using  MapboxMap.addMarkers(List<? extends BaseMarkerOptions> markerOptionsList); - for example 200 markers;
 2. Change all markers position and  icon  every second (icon - new bitmap)
### Expected behavior
Markers change icon and  position
### Actual behavior
Memory leak - used memory grows on every icon change.

When i use  mapboxMap.addMarker(new MarkerViewOptions().position(position))  for each marker    add - everything works well.  

For my project i need to draw many markers (about 200 - 300) and periodicaly change its position and icon. 
With  mapboxMap.addMarker(new MarkerViewOptions().position(position)) func adding  i has memory leak. May be  not using addMarkers  method?

Example with memory leak i've make base on mapbox demo // AnimatedIconActivity:

package com.mapbox.mapboxandroiddemo.examples.annotations;

import android.animation.ObjectAnimator;
import android.animation.TypeEvaluator;
import android.animation.ValueAnimator;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Rect;
import android.os.Bundle;
import android.os.Handler;
import android.support.annotation.NonNull;
import android.support.v7.app.AppCompatActivity;

import com.mapbox.mapboxandroiddemo.R;
import com.mapbox.mapboxsdk.MapboxAccountManager;
import com.mapbox.mapboxsdk.annotations.Icon;
import com.mapbox.mapboxsdk.annotations.IconFactory;
import com.mapbox.mapboxsdk.annotations.Marker;
import com.mapbox.mapboxsdk.annotations.MarkerOptions;
import com.mapbox.mapboxsdk.annotations.MarkerViewOptions;
import com.mapbox.mapboxsdk.geometry.LatLng;
import com.mapbox.mapboxsdk.maps.MapView;
import com.mapbox.mapboxsdk.maps.MapboxMap;
import com.mapbox.mapboxsdk.maps.OnMapReadyCallback;

import java.util.ArrayList;
import java.util.List;

public class AnimatedMarkerActivity extends AppCompatActivity {

  private MapView mapView;
  Handler handler = new Handler();
  List<MarkerOptions> mlist = new ArrayList<>();
  Paint paint;
  static  int i=0;
  Runnable runnable;
  MapboxMap mmapboxMap;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    runnable = new Runnable() {
      @Override
      public void run() {
        i++;

        for (Marker marker: mmapboxMap.getMarkers()) {

          marker.setIcon(getIcon(i, paint));

          LatLng position = marker.getPosition();
          position.setLatitude(position.getLatitude() + 0.001);
          position.setLongitude(position.getLongitude() + 0.001);
          marker.setPosition(position);
        }

        handler.postDelayed(runnable, 2000);

      }
    };

    // Mapbox access token is configured here. This needs to be called either in your application
    // object or in the same activity which contains the mapview.
    MapboxAccountManager.start(this, getString(R.string.access_token));

    // This contains the MapView in XML and needs to be called after the account manager
    setContentView(R.layout.activity_annotation_animated_marker);

    mapView = (MapView) findViewById(R.id.mapView);
    mapView.onCreate(savedInstanceState);

    paint = new Paint(Paint.ANTI_ALIAS_FLAG);
    paint.setColor(Color.WHITE);
    paint.setTextAlign(Paint.Align.LEFT);
    paint.setTextSize(10 * getResources().getDisplayMetrics().density);

    mapView.getMapAsync(new OnMapReadyCallback() {
      @Override
      public void onMapReady(MapboxMap mapboxMap) {
        mmapboxMap = mapboxMap;

        final ArrayList<MarkerOptions> buffer = new ArrayList<>();

        for (int i=0;i< 200; i++) {
          LatLng position = new LatLng(64.900932, -18.167040);
          position.setLatitude(position.getLatitude() - 0.2 * i);
          position.setLongitude(position.getLongitude() + 0.2 * i);

          MarkerOptions marker = new MarkerOptions()
                  .title("")
                  .position(position);

          buffer.add(marker);

        }

        mapboxMap.addMarkers(buffer);
        handler.postDelayed(runnable, 3000);
      }
    });
  }

  @Override
  public void onResume() {
    super.onResume();
    mapView.onResume();
  }

  @Override
  public void onPause() {
    super.onPause();
    mapView.onPause();
  }

  @Override
  public void onLowMemory() {
    super.onLowMemory();
    mapView.onLowMemory();
  }

  @Override
  protected void onDestroy() {
    super.onDestroy();
    mapView.onDestroy();
  }

  @Override
  protected void onSaveInstanceState(Bundle outState) {
    super.onSaveInstanceState(outState);
    mapView.onSaveInstanceState(outState);
  }

  private static class LatLngEvaluator implements TypeEvaluator<LatLng> {
    // Method is used to interpolate the marker animation.

    private LatLng latLng = new LatLng();

    @Override
    public LatLng evaluate(float fraction, LatLng startValue, LatLng endValue) {
      latLng.setLatitude(startValue.getLatitude()
        + ((endValue.getLatitude() - startValue.getLatitude()) * fraction));
      latLng.setLongitude(startValue.getLongitude()
        + ((endValue.getLongitude() - startValue.getLongitude()) * fraction));
      return latLng;
    }
  }

  private Icon getIcon(int i, Paint paint){
    Bitmap bitmap;

      bitmap = BitmapFactory.decodeResource(
              getResources(),R.drawable.green_marker);
    Icon icon = IconFactory.getInstance(this).fromBitmap(drawTextOnBitmap(String.valueOf(i), paint, bitmap));
    return icon;
  }

  public static Bitmap drawTextOnBitmap(String text, Paint paint, Bitmap source) {
    Bitmap mutableBitmap = source.copy(Bitmap.Config.ARGB_8888, true);
    Canvas canvas = new Canvas(mutableBitmap);

    // draw text to the Canvas center
    Rect boundsText = new Rect();
    paint.getTextBounds(text, 0, text.length(), boundsText);
    int x = (mutableBitmap.getWidth() - boundsText.width()) / 2;
    int y = (mutableBitmap.getHeight() + boundsText.height()) / 2;
    canvas.drawText(text, x, y, paint);
    return Bitmap.createBitmap(mutableBitmap, 0, 0, mutableBitmap.getWidth(), mutableBitmap.getHeight());
  }
}

**Comment by tobrun** [comment]
@AlexeyIke 
thank you for reaching out and using our products! Can you explain me what you mean with memory leak in this situation? From my perspective a memory leak and memory growing/churning aren't the same thing.

Looking at the code you posted I'm seeing that you are constantly creating new bitmaps/icons. These are memory intensive tasks and you should optimise your code to avoid creating new objects if not needed.

Could you provide us so more information on this by profiling the code an seeing where the large amounts of memory allocations are occurring?

**Comment by AlexeyIke** [comment]
Hello,
in my application i've show city buses (about 200 markers), it positions, route number and its direction, and update it every 8 seconds  
(that's why i generate new icon if bus drive direction has been changed)  (in my app it happen after some minutes - no fail,  but markers became invisible, example that i made on mapbox_demo fail in a minute)

I mean memory leak beacause if i change icon for marker previous icon should be delete by GC, but no free happen for markers - used memory grows up and even when i init GC from AndroidStudio not free memory.

Screenshot - https://drive.google.com/open?id=0B3U64R1No4k8NmdIcjNpcUNfT2c 
dump scr - https://drive.google.com/open?id=0B3U64R1No4k8NmdIcjNpcUNfT2c 
dump file - https://drive.google.com/open?id=0B3U64R1No4k8T2JNdm14NTZvdVk
most allocation for icons with it bitmap (2401 objects on )
(all for example that i've send early)

Another way for my project - instead if changind icon delete and add markers. I've try to implement it if will be no memory grow.

**Comment by tobrun** [comment]
Thank you for clarifying those statements, very helpful! The reason why you don't see memory being freed with invoking a java gc is that the Bitmap is passed through jni as a bytebuffer and is than is placed in a SpriteAtlas with `AnnotationManager::addIcon`. I will not be possible to let the java gc clean that up. The only way would be to explicitly call `AnnotationManager::removeIcon`, while this is supported in the C++ we still need to expose the proper binding for it. We also need to check if we can automatically hook this up when you are replacing an icon.

Re. your use-case, I would highly advice you to look at runtime styling API instead of using the marker API. This API is much more flexible and you should be able to handle your use-case without creating any bitmaps at all. I think [this](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/GeoJsonClusteringActivity.java#L121) cluster example should help you get started.

Thanks again for taking the time to write this up and making our SDK better.

**Comment by AlexeyIke** [comment]
Hello, thanks for cluster example! Works well.
Can i reach additional functionality?
- define custom icon for cluster/icon (i saw define iconImage"marker-15"
but how define own image),
-  change  cluster icon programatically (for example i want to hightligh
"touched" cluster)
- animate re-clustering
May be some examples exists?

2016-12-09 17:16 GMT+10:00 Tobrun <notifications@github.com>:
