### ISSUE TITLE
It's Slow to add Layers to map 

### ISSUE THREAD

**Issue by guruduttstay** [mapbox/mapbox-gl-native#7348]
**Platform: Android **
**Mapbox SDK version: mapbox-android-sdk:4.2.0-beta.5 **

### Steps to trigger behavior

I followed this [doc](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/SymbolLayerActivity.java) to add Layers to Map

 1. I added one Layer for each Place/Icon/Marker
 2.  It is adding more than 850 Places to the map in a loop so it adds more thant 850 Layers to the map
3.  NB : Each place belongs to some category so POI/Image it use it for that category and there are only 20 categories so there are no more than 20 images source added to map
 3. It takes around 3 seconds to complete procedure :(

Is there any faster way ?

```

Code something like 
        for (POI poi : mList) {
                    updateMapWithLayer(mapboxMap, poi); // This function create a layer, source, image and add it to map 
            }

```
### Expected behavior
Expecting faster addition of map may be less than 1 second 

### Actual behavior
It takes up to 3 seconds before all layers are added to the map

**Comment by guruduttstay** [comment]
Also while adding layers it is not panning or zooming :(
seems app is hanged :(

**Comment by jfirebaugh** [comment]
Hi @guruduttstay, thanks for the report. If all your layers are the same type, consider adding a single layer and setting the `icon-image` property to a string with feature interpolation like `{image}`. Then the layer will use the value of the `image` property from each feature as the icon. This is much more efficient than 850 individual layers.

**Comment by guruduttstay** [comment]
Hi @jfirebaugh 
Thank you for quick response

If you see here : http://bit.ly/2gIinXu
We have special need ....
   - Based on current viewPort we want to display top 20 high ranked places pins visible 
  -  We also animates pins to hide/display and that is individual pin
 
If we add more than one coordinates to feature to same layer then animation will takes place for all pins ... we want to act on single coordinate pin 

 - is it possible to hide/show single pins if I add several coordinates/feature/pins to single layer ?

 - Also notice white map while loading and it takes almost 3 seconds to load map because adding one by one layer to map is slow process 

 - Is it possible to add bunch of layers in one call to mapBoxMap?

**Comment by tobrun** [comment]
- is it possible to hide/show single pins if I add several coordinates/feature/pins to single layer ?

yes, you can use [filters](https://www.mapbox.com/mapbox-gl-style-spec/#types-filter) for that. 

 - Also notice white map while loading and it takes almost 3 seconds to load map because adding one by one layer to map is slow process. Is it possible to add bunch of layers in one call to mapBoxMap?

as suggested, add one layer instead of 850, adding a couple of layers shouldn't be a problem.

**Comment by guruduttstay** [comment]
Thank you for quick response :)

is there any good e.g. of use of Filters with layers  ?

**Comment by tobrun** [comment]
You can apply filters to Layers, we still lack some examples around this feature but here is an example with [clustering](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/GeoJsonClusteringActivity.java#L155).

**Comment by guruduttstay** [comment]
Hi @tobrun 

Thank you for your quick response and help 

Just applied filters ti layers 
For now I have max 10 Layers and group all Features based on category.

Though creating features takes some time which makes first map load slow a bit 


but overall filter appearance is bit fuzzy 

Filter applied to each layers : http://bit.ly/2hlzEt7
It flickers everytime it apply filter :(

I wish to animate markers/pins for it's appearance and disappear  for e.g. : http://bit.ly/2gIinXu


Any clue if I am doing something wrong ?

**Comment by guruduttstay** [comment]
It seems like while applying Filter to Layers 
 - First it Hides all pins/features and then shows all pins and that's why it flickers 
 - While it should not do anything with pins/features which is already visible and and should be visible after applying new filter  + it should hide those pins which is not in new filter list + show which is in the list and not visible 

 - I did not found possibility to animate markers :(

**Comment by tobrun** [comment]
@guruduttstay thank you for the feedback, I'm trying to reproduce and pinpoint.
