### ISSUE TITLE
In Follow Location Mode, At Zoom Level Zero, Location Marker is drawn Incorrectly

### ISSUE THREAD

**Issue by altafrm3d** [mapbox/mapbox-gl-native#7349]
### Steps to trigger behavior

![zoomlevelzero-userfollowlocation-markerdrawnincorrectly](https://cloud.githubusercontent.com/assets/13051552/21013057/e2daf26a-bd58-11e6-8a35-8f3d25365224.gif)

### Expected behavior
In Follow Location Mode, at Zoom level Zero, the marker for User's location should be drawn at his/her location
### Actual behavior
In Follow Location Mode, at Zoom level Zero, the marker for User's location is drawn in the center of the screen

**Platform:** Android
**Mapbox SDK version:**

**Comment by tobrun** [comment]
I remember seeing something in the iOS code about zooming to at least 2 in this case.
