### ISSUE TITLE
onCameraChange is not always called for the final position in the animation

### ISSUE THREAD

**Issue by altafrm3d** [mapbox/mapbox-gl-native#7350]
### Steps to trigger behavior

![oncamerachange-behavingstrangely](https://cloud.githubusercontent.com/assets/13051552/21013375/21c4a4a2-bd5a-11e6-9a8f-5286a2f1a112.gif)

onCameraChange i am calculating the Zoom level of Raster Tiles (using Math.round(cameraPosition.zoom)) and labeling it as shown 

### Expected behavior
onCameraChange is always called for the final position in the animation, so in my case, it should always update the label when the camera change is completed and the tiles are updated
### Actual behavior
onCameraChange is not always called for the final position in the animation, but it misses a frequent number of times as shown in the gif

**Platform:** Android
**Mapbox SDK version:**

**Comment by tobrun** [comment]
@altafrm3d thank you adding a gif to explain the issue, could you add the version where you are having this issue?

**Comment by altafrm3d** [comment]
@tobrun I am not sure what you meant by the version, this is the last commit in the logs, maybe that is already enough for you

commit 11229d72f50048a83a8f90210436052d4b1c051b
Author: Konstantin Käfer <mail@kkaefer.com>
Date:   Wed Dec 7 12:37:52 2016 +0100

    [build] bump mason to update Android compile flags

**Comment by tobrun** [comment]
Thank for confirming that you are building from master. Note that you can also use stable versions that will not have this issue or build from the release branch `release-android-v4.2.0`. I changed the invalidation recently in #6532 to not refresh the camera position too much, it seems that gestures aren't always covert. I'm going to patch this up by hooking into `setGestureInProgress(false)` to determine if we need to notify OnCameraChangeListener for a change.
