### ISSUE TITLE
Drawing of the Markers behave strangely

### ISSUE THREAD

**Issue by altafrm3d** [mapbox/mapbox-gl-native#7352]
**Platform:** Android
**Mapbox SDK version:**

### Steps to trigger behavior

![setposition-onmarkers-duringdragging-makesthemflicker](https://cloud.githubusercontent.com/assets/13051552/21013856/ce1d5b8a-bd5b-11e6-9083-43242859d5d6.gif)

We have an overlay of polygon and polyline and four markers on them to resize the drawn rectangle. All these items are added once on the mapview and later on only new positions are set on them. Whenever any of the markers is dragged, all other items are readjusted. Code itself is not very complex and seems to work smoothly on mapbox android legacy library. Unfortunately, in the new android library, these markers flicker when new positions are set on them.

![drawingofmarkers-behavingstrangely](https://cloud.githubusercontent.com/assets/13051552/21014081/d67b8cba-bd5c-11e6-965b-df1e5c958462.gif)

I created a Test (you can find it [here](http://stackoverflow.com/questions/41042604/markers-are-not-drawn-instantaniously-when-enter-the-mapview-and-sometimes-they))

I have ten markers, each one of them at a distance of 0.01 longitude, and upon dragging anyone of them, i am setting new positions on all of these markers. Upon camera position change, if they go out of the mapview and enter again, they take a moment before they are drawn, Moreover, i found out that sometimes, they are not even drawn when they are supposed to be shown on the mapview as you can see it in the gif.

I have not been able to figure out the flickering, but i suspect that issues found out in the test are linked to flickering in my case.

**Comment by tobrun** [comment]
@altafrm3d the reason why the markers behave different that the legacy sdk is that these aren't View but gl drawn markers. I would highly advice you to implement that use case with a custom Android SDK View which you can add to the Map with `MapView.addView(View view)`. You can hook into methods as `Projection.fromScreenLocation(Pointf point)`to determine that `LatLngBounds` when needed.

Flickering itself has been reported in https://github.com/mapbox/mapbox-gl-native/issues/6762 already, closing as a duplicate.
