### ISSUE TITLE
allow for nullable style layer predicate

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#7359]
As with Core Data's `NSFetchRequest`, we should allow removal of a style layer predicate by setting it to `nil`. That other API also converts the `TRUE` (always on) predicate to `nil` upon roundtripping. Otherwise, there's not an obvious way to remove the predicate (Studio analog: filters) from a layer.

**Comment by 1ec5** [comment]
Fixed in #6588, which made it into v3.4.0.
