### ISSUE TITLE
New outdoors style flickers

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#736]
Just tested the updated outdoors style on my phone and I am noticing tile sized flickers of black when zoomed in and panning.

Do not see this in the other styles.

**Comment by ljbade** [comment]
@nickidlugash Was there any significant changes to the way the new outdoor style gets rendered?

**Comment by peterqliu** [comment]
@ljbade likely terrain. check out https://github.com/mapbox/mapbox-gl-styles/issues/22

**Comment by ljbade** [comment]
@peterqliu I wonder if the style is taxing the GL renderer a bit like the flicker you saw on you demo the other day.

It seems to flicker a bit of a black rectangle/border so I wonder if it is trying to show the tile before it has finished rendering?

**Comment by nickidlugash** [comment]
@ljbade is this still an issue? I'm not sure what's going on, but the major difference with the terrain was to remove the pre-rendered layer, which I *thought* would make it less taxing on the renderer.

**Comment by ljbade** [comment]
@bleege and @incanus: It would be nice to know if you also see this on your devices?

I may have to show in person at SF since it is hard to describe.

**Comment by bleege** [comment]
The build that I installed yesterday doesn't seem to have trouble with this style (or at least I'm not seeing it).  Happy to let you drive though in SF.

**Comment by incanus** [comment]
Still relevant @ljbade?

**Comment by ljbade** [comment]
Hmm I will check once I fix these storage-refactor crashes since it is stopping me switching to outdoor

**Comment by ljbade** [comment]
@incanus @ansis Still happening.

**Comment by ansis** [comment]
the might be the same problem as https://github.com/mapbox/mapbox-gl-native/issues/806

**Comment by bleege** [comment]
@ljbade @ansis Is this still happening or can we close this issue?

**Comment by bleege** [comment]
No longer using Outdoor style.  Likely, why no one has commented on this in awhile.  :-)
