### ISSUE TITLE
3D Tiles for Mobile

### ISSUE THREAD

**Issue by Buminta** [mapbox/mapbox-gl-native#7365]
Hi Mapbox Team.
Before i'm say thanks to Mapbox Team.
Your team so great! And i had follow and use any of Mapbox Team about three year.
I'm so very happy!
I'm interesting with 3D buildings tiles. However that had only website with Mapbox-GL-JS.
I waiting use that with mobile device + mapbox-gl-native.
How about time for your team develop it? I hope it's very quickly!
Thanks for all!
😄

**Comment by jfirebaugh** [comment]
See issue #6745.
