### ISSUE TITLE
Controlling CLLocationManager

### ISSUE THREAD

**Issue by nitrag** [mapbox/mapbox-gl-native#7369]
From what I can tell, MGLMapView creates its own CLLocationManager and we don't have access to it, correct?

I have a feature in my app that requires "Privacy - Location Always Usage Description" (Background Location) for a specific feature in my app that is disabled 90% of the time. I noticed on several occasion after picking up my phone that I get a warning saying "AppName has been using your location in the background" when I have not enabled my background feature (which I use a separate LocationManager instance for anyway). 

I don't want my users to freak out thinking stuff is going on when there isn't.  If what I suspect is correct (Mapbox is continuing to update locations in the background - not wanted (by me at least)), we need:

- Constants to control mapView location behavior when in background
- Expose Start/Stop for LocationManager
- Completely expose LocationManager (so I don't need to two instances getting user's location)

iOS
Beta 4

**Comment by nitrag** [comment]
Well, here's a good reason.

Telemetry. TOS says you collect info on users. Well, seeing as I'm in beta, I'm 100% sure the following image are my "tracks". I did not have the app open but the app must have been running in the background, since I have "Always Background" GPS privileges (for a separate, limited use, function that is manually enabled).

![image](https://cloud.githubusercontent.com/assets/197010/21745940/01db7de8-d504-11e6-83c7-285f30b3c3cb.png)

I have two concerns with this:

- The app is running in the background. Per T.O.S: "provide information back to you about how your app is being used"...well no you aren't. I wasn't actively using the app, so the SDK is collecting **irrelevant** data. I only need to know when my users are actively using the app. Not opened the app 8 hours ago for 30 seconds and haven't used the app since.
- This data is unnerving.
- Battery implications.

My suggestion would be to limit this "data collection" (telemetry) to Foreground Only. Or at least give the developer the option to set this manually.

**Comment by boundsj** [comment]
Thanks for your feedback @nitrag. This is intended behavior and is the result of the telemetry module's location manager (not the map view location manager) running in the background in a host application that has been given `always` location permissions from the user.

As developers we understand the constraints of resources on mobile. Our data collection has been optimized in collaboration with developers in our community and has been field tested with millions of users to make sure we can improve maps without noticeable impact on the battery for applications that use the Mapbox Map SDKs.

You’ve already poked through the source and you can also check out [our telemetry overview](https://www.mapbox.com/telemetry/) for more information on how we use this aggregated data (_spoiler: to improve OSM_) and about how fiercely we keep it anonymous and private. You're always welcome to get in touch with us [through our website](https://www.mapbox.com/contact/) about specific concerns you have about your particular application.

**Comment by nitrag** [comment]
Well if it is intended behavior, ok. Thanks for clarifying.
