### ISSUE TITLE
Traditional Chinese localization

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7370]
Now that #7316 has landed, it should be pretty straightforward to implement a Traditional Chinese localization based on the Simplified one. As a starting point, we can run each .strings file through [OpenCC](https://github.com/BYVoid/OpenCC/):

```bash
$ brew install opencc
$ echo 汉语 | opencc -c s2t
漢語
```

/cc @YunjieLi @friedbunny

**Comment by YunjieLi** [comment]
Sounds good. Can also 👀 from the traditional Chinese ~speakers~ writers.

cc @lily-chai @virginiayung @jenyuhk
