### ISSUE TITLE
MGLSource should not maintain parallel state

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7375]
MGLSource and its subclasses, particularly MGLShapeSource, currently hang onto objects passed into their initializers in order to return them in their properties’ getters. This is a workaround for #6584, but it’s problematic because MGLSource objects don’t necessarily know the canonical value of these properties. For example, if you get a source via `-[MGLStyle sourceWithIdentifier:]`, the properties are all unset because the source was initialized via `-[MGLSource initWithRawSource:]`. You can then proceed to modify the source’s contents behind the backs of any other MGLShapeSource instances that wrap that source:

```swift
let one = MGLShapeSource(identifier: "one", shape: MGLPointFeature(), options: nil)
mapView.style.addSource(one)
// a short while later…
let uno = mapView.style.source(withIdentifier: "one")
uno.shape = someOtherFeature
// finally…
assert(one.shape is MGLPointFeature)
// 💣💥
```

/cc @boundsj

**Comment by 1ec5** [comment]
This is essentially blocked by #7376, because otherwise we can continue to expose an `-[MGLShapeSource setShape:]` but we’d have to eliminate `-[MGLShapeSource shape]`. A write-only property is theoretically possible but unheard of in Objective-C and Swift. (The closest thing I can think of is `-[NSView setNeedsDisplay:]`, which isn’t a property and which no one thinks is a good design.)

**Comment by 1ec5** [comment]
#7377 will eliminate `MGLShapeSource.geoJSONData` and make `MGLShapeSource.URL`’s getter computed, but `MGLShapeSource.shape` remains.

**Comment by boundsj** [comment]
I updated the example in the original description above:
 s/`let uno = mapView.style.layer(withIdentifier: "one")`/`let uno = mapView.style.source(withIdentifier: "one")`

**Comment by boundsj** [comment]
This gets into https://github.com/mapbox/mapbox-gl-native/issues/7376 and the memory concerns noted there, but would it make sense for `MGLStyle` to keep references to the source and layer objects in use? Then, asking the style for a source would/could always return the same source instance.

**Comment by 1ec5** [comment]
It's definitely possible and it'd solve several problems associated with these wrappers. We already do that for MGLOpenGLStyleLayers, which are entirely managed by the style. I wanted to avoid doing that for sources and layers in general, since there may be ways for the style to change behind MGLStyle's back, whereas a custom layer can only come from application code.

**Comment by jfirebaugh** [comment]
I'm open to adding a `void* peer` member to `mbgl::Style::Source`, `mbgl::Style::Layer`, etc., as a place where SDKs could stash a pointer to the SDK-level object, so that they can ensure that methods like `getLayer()` always returns the same object for a given identifier. Would that help?

**Comment by 1ec5** [comment]
The more I think about this, the more attractive @boundsj’s idea in https://github.com/mapbox/mapbox-gl-native/issues/7375#issuecomment-266528289 looks. The only catch is that we have to be absolutely certain MGLStyle knows exactly when a source or layer goes away, such as due to polyline/polygon annotation removals.

A `void* peer` member on `Source` and `Layer` wouldn’t be a complete solution, because ARC doesn’t track ownership in `void*` pointers – the pointer would immediately become stale without some other Objective-C object hanging onto the object. However, a general-purpose `void* context` member would probably be useful for associating (non-object) data with any mbgl object that the SDK might need to wrap.

**Comment by jfirebaugh** [comment]
What does ARC do if you use a type-erasure-based `any` type instead of `void*`? http://www.artima.com/cppsource/type_erasure2.html

**Comment by 1ec5** [comment]
Still the biggest pain point with runtime styling in Objective-C and Swift.

**Comment by 1ec5** [comment]
> A `void* peer` member on `Source` and `Layer` wouldn’t be a complete solution, because ARC doesn’t track ownership in `void*` pointers – the pointer would immediately become stale without some other Objective-C object hanging onto the object.

This might not be a problem anymore if ARC [can track ownership](https://developer.apple.com/videos/play/wwdc2018/409/?time=494) of Objective-C objects within C/C++ structs. The only unknown, then, is whether that also extends to `void *` or `any` pointers.
