### ISSUE TITLE
Add support parameters "property", "type", "colorSpace" in Function

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#7379]
**Platform:** Android
**Mapbox SDK version:** 4.2.0

https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/Function.java
Function supports parameters "stops" and "base". But does not support the "property", "type", "colorSpace"
https://www.mapbox.com/mapbox-gl-style-spec/#types-function

**Comment by cammace** [comment]
This is a data driven style feature we are already looking to add in a future release of the Android SDK. Follow [this ticket](https://github.com/mapbox/mapbox-gl-native/issues/4860) for status on this feature. Closing as it's a duplicate.
