### ISSUE TITLE
Map::getAppliedStyleClasses crashes if called before style finishes loading

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#739]
I have encountered a crash if `Map::getAppliedStyleClasses` is called before the style finishes loading.

The only way around this is to either change `getAppliedStyleClasses` to return a pointer so null means the style hasn't loaded or to add a new function that returns a status to indicate the style has finished loading.

**Comment by ljbade** [comment]
We should also add an assert(style) to all functions that should not be called until the style has loaded.

**Comment by ljbade** [comment]
I should mention that I have had to disable style class state saving in the Android code at https://github.com/mapbox/mapbox-gl-native/blob/android-mason/android/java/lib/src/main/java/com/mapbox/mapboxgl/lib/MapView.java#L408 to work around the crash.

**Comment by ljbade** [comment]
@jfirebaugh Was this taken care of in your recent changes to the style functions?

**Comment by jfirebaugh** [comment]
Indeed it was.
