### ISSUE TITLE
tile 404 fallback mask level

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#74]
Per @yhahn Mapnik has the concept of a fallback to a lower-numbered zoom level on blank tile 404s. 

If we get a 404 around https://github.com/mapbox/llmr-native/blob/master/src/map/tile.cpp#L75-L85 we should reach back up to `z8` similarly. I was getting bitten by this earlier and thought the tile server was messed up.

**Comment by jfirebaugh** [comment]
Fixed on the tile-serving side.
