### ISSUE TITLE
Rename base to interpolationBase

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7421]
`MGLStyleFunction.base` should be renamed to `MGLStyleFunction.interpolationBase`, to emphasize that it is only used with (exponentially) interpolated functions, as discussed in mapbox/mapbox-gl-style-spec#613. This property will become more important with the arrival of data-driven styling (#4860). We should try to head off a situation where `base` has to be deprecated shortly after its introduction.

/cc @boundsj

**Comment by boundsj** [comment]
Renamed in https://github.com/mapbox/mapbox-gl-native/pull/7486
