### ISSUE TITLE
Readded style layers lose all paint properties

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7437]
If you remove a layer from a style and add it back in, all its former paint properties are reset to the default values.

To reproduce this issue in macosapp:

1. Change the style to Streets.
1. In the Layers sidebar, right-click a symbol layer such as `country-layer-lg` and go to Delete.
1. Go to Edit ‣ Undo.

The layer comes back with the right layout properties but the wrong paint properties. For example, the readded symbol layer has the right `textField`, `textSize`, `textFont`, etc. but the wrong `textHaloBlur`:

![before](https://cloud.githubusercontent.com/assets/1231218/21195478/cb74ae2e-c1e8-11e6-9332-ac335887eb6f.png)
![after](https://cloud.githubusercontent.com/assets/1231218/21195479/cb7552a2-c1e8-11e6-822d-8c5de7eab64c.png)

Essentially what macosapp does is to [hold onto](https://github.com/mapbox/mapbox-gl-native/blob/e182731092e62441da8545121b469a22cb5116c1/platform/macos/app/MapDocument.m#L314) the selected layers for later insertion before removing them from the style. Given that the layout properties are persisted, I’d imagine the problem lies in core rather than at the SDK or application level.

/cc @boundsj

**Comment by 1ec5** [comment]
Moving to v3.5.0 because mbgl changes are needed.

**Comment by jfirebaugh** [comment]
`-[MGLStyle layerFromMBGLLayer:]` calls `[MGL*StyleLayer initWithIdentifier:source:]`, which sets `_pendingLayer` to a new `mbgl::style::*Layer`. This seems like a bug. Among other things `rawLayer` and `_pendingLayer` will wind up pointing to different objects, which appears to be the cause of this bug.

**Comment by 1ec5** [comment]
Basically https://github.com/mapbox/mapbox-gl-native/blob/dfb737ee0fcae49a4cbe2d9fabbea939642d94d8/platform/darwin/src/MGLStyle.mm#L356 needs to be folded into the initializers for the various style layers. We did this more correctly in https://github.com/mapbox/mapbox-gl-native/blob/dfb737ee0fcae49a4cbe2d9fabbea939642d94d8/platform/darwin/src/MGLStyle.mm#L168 for wrapping sources.
