### ISSUE TITLE
port matrix creation cleanup from -js

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#7439]
port https://github.com/mapbox/mapbox-gl-js/pull/3790.

> This cleans up a bunch of matrix and antialiasing code.
>
> - removes the confusing altitude and replaces it with fov
> - fixes text blurriness at non-default FOVs
> - removes the hack added in #3740 and adds a different fix
> - makes pitched line antialiasing clearer and removes lineStretch and lineAntialiasingMatrix

**Comment by jfirebaugh** [comment]
@ansis Now that both https://github.com/mapbox/mapbox-gl-js/pull/3790 and https://github.com/mapbox/mapbox-gl-native/pull/7419 have been merged, can you work on this, so native doesn't start falling behind?
