### ISSUE TITLE
Location marker drifts several kilometers

### ISSUE THREAD

**Issue by kjkrum** [mapbox/mapbox-gl-native#7441]
The "my location" marker sometimes drifts several kilometers away.  This is accompanied by the accuracy circle becoming very large, on the order of hundreds of meters.  I've seen this in my own apps using 4.2.0 beta 5, as well as in a third-party app that uses an unknown version.  I cannot reproduce it deliberately.

While this is happening, other apps fix my location correctly.  I have a test app that displays a `GoogleMap` and a `MapboxMap` side by side with their camera positions synchronized.  The location marker on the `GoogleMap` remains steady while the marker on the `MapboxMap` drifts away.

Possible clue: I've only seen the marker drift E/NE, which happens to be the direction of the nearest cell towers.  In the one example I got a screenshot of, the marker had stopped almost exactly at the location of a cell tower.

**Comment by tobrun** [comment]
@kjkrum thank you for the detailed explanation. We need to look into if this problem originates from LOST and if that is fixed with the update to 2.0.0 or that this comes from using entity interpolation to provide driving animation.

**Comment by tobrun** [comment]
@kjkrum the source of this comes from the location provider dependency (in our case this is by defualt lost). Starting the 5.0.0 release we are allowing you to provide you own through the LocationSource class. For example you could swap out LOST for a Google Play Services alternative.

Going to close this issue as we can't fix the issue from OP and a workaround was provided. Feel free to reach out if you have any other questions!
