### ISSUE TITLE
Hitbox for CustomAnnotationView not respecting centerOffset

### ISSUE THREAD

**Issue by arbitur** [mapbox/mapbox-gl-native#7450]
**Platform: iOS**
**Mapbox SDK version: 3.3.7**

When tapping the map on on the annotationView it does not select the annotationView when tapping the upper half of the view and does select half height below the visual view

### Image
![screen shot 2016-12-15 at 12 28 58 2](https://cloud.githubusercontent.com/assets/1361280/21222576/cc01fc18-c2c2-11e6-94db-fafa769bd1b6.png)

Red is the real bounding box of the view and  and the green is the actual hitbox for touches.
This should not happen

### Code
```swift
    class CustomAnnotationView: MGLAnnotationView {
	
        override init(reuseIdentifier: String?) {
            super.init(reuseIdentifier: reuseIdentifier)
        }
	
        override init(frame: CGRect) {
            super.init(frame: frame)
		
            let image = UIImage(named: "map_pin")!
            self.frame.size = image.size
            self.centerOffset.dy = -image.size.height/2
            self.backgroundColor = UIColor(patternImage: image)
            self.isOpaque = false
        }
    }


	func mapView(_ mapView: MGLMapView, viewFor annotation: MGLAnnotation) -> MGLAnnotationView? {
		if annotation is PendingAnnotation {
			if let view = mapView.dequeueReusableAnnotationView(withIdentifier: "map_pin") {
				return view
			}
			else {
				return CustomAnnotationView(reuseIdentifier: "map_pin")
			}
		}
		else {
			return nil
		}
	}
```

**Comment by huynhduyson** [comment]
@arbitur Check here: https://www.mapbox.com/ios-sdk/examples/marker-image/

**Comment by huynhduyson** [comment]
I have same issue on iOS with Mapbox version 3.6.2. But i can tap on both red & green box. It should exclude the bottom half of green box.

**Comment by tobrun** [comment]
fwiw, we faced the same issue on the Android binding and fixed it with hit testing in https://github.com/mapbox/mapbox-gl-native/pull/9424.
