### ISSUE TITLE
Tiles are cached by url template in the database

### ISSUE THREAD

**Issue by wibge** [mapbox/mapbox-gl-native#7455]
Tilesets are cached by url template, if the url to a tile source changes previously cached and downloaded maps are not seamlessly loaded. 

We have tile sources that have frequently changing API keys as part of the URL.

**Platform:** ios 
**Mapbox SDK version:** 3.4

### Steps to trigger behavior

 1. Create a tileset with a URL containing an API key
 2. Cache tiles from the tileset
 3. Change the API key in the URL

### Expected behavior
Cached tiles are displayed when the tileset is on screen
### Actual behavior
Cached tiles are not displayed

I'd propose adding an optional tilecachekey parameter to use to override caching by url template.

**Comment by jfirebaugh** [comment]
#8084 adds a feature that provides the ability to modify the URL independently of the value used for a cache key. Per https://github.com/mapbox/mapbox-gl-native/pull/8041#issuecomment-281738359, I believe this addresses your use case.
