### ISSUE TITLE
MGLShapeCollection.shapes should be writable

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7458]
MGLShapeCollection’s `shapes` property should be a read-write mutable array, so that the developer can (for example) append a shape to the collection directly rather than having to create a new MGLShapeCollection to change the shapes within an MGLShapeSource.

The implementation would be similar in scope to #6160, although without any C++ wrangling.

/cc @bsudekum

**Comment by andrewstay** [comment]
@1ec5 It is very risky and considered as a bad design to provide mutable containers in the interface. Please consider adding following methods instead:
```
- (void)addShape:
- (void)removeShape:
```

**Comment by 1ec5** [comment]
Thanks @andrewstay, in that case, we can certainly provide individual getters and setters without making the array mutable. This will likely be the solution to #7459 as well.

**Comment by 1ec5** [comment]
I think we should consider implementing the [KVO methods](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/KeyValueCoding/Compliant.html#//apple_ref/doc/uid/20002172) for mutable containers. That way the developer can call the standard `-[NSObject mutableArrayValueForKey:]` then efficiently add and remove from that NSMutableArray without having to then set the `shapes` property at the end. We follow this pattern in MGLStyle.

**Comment by andrewgubanov** [comment]
@1ec5 The solution suggested by you looks like encapsulation violation as it exposes internal logic to the client.

**Comment by 1ec5** [comment]
Would it be? I thought `-mutableArrayValueForKey:` etc. are intended to be used that way; implementing KVO methods like `-insertObject:inShapesAtIndex:` only improves their performance, but the developer doesn’t need to know about the KVO methods.

**Comment by andrewgubanov** [comment]
To make things cleaner:
1. ```-mutableArrayValueForKey:``` is a part of the KVC, not KVO
2.  ```insertObject:inShapesAtIndex:``` is not a KVO
3. KVC and KVO were intended to be used in unittests initially, but somehow migrated to the production code.

When user of your objects access private property with the knowledge that it is a mutable container and can modify it using KVC it is a direct violation of encapsulation and should be avoided as much as possible.

**Comment by 1ec5** [comment]
Sorry for being thick: I was conflating KVC and KVO. In fact, I’m also overthinking things: the collection methods needed for `-mutableArrayValueForKey:` (if any) would be autosynthesized anyhow, since `shapes` itself is autosynthesized. If methods like `-appendShape:` and `-removeShapeAtIndex:` would be more discoverable and convenient than `-mutableArrayValueForKey:`, we can certainly do that – and it’d be consistent with MGLMultiPoint to boot.
