### ISSUE TITLE
App freezes with no drawing to screen

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#746]
When the app starts the window opens and nothing gets drawn. The apps seems to freeze.

I examined the back trace and it was sitting in the Map UV loop doing nothing.

A few debug prints that the first call to `asyncRender()` does not trigger a `render()` which stops the rendering loop starting.

The issue appears that the check at https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/map/map.cpp#L164:
`if (state.hasSize())` which is `false`

**Comment by ljbade** [comment]
`state` is set at https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/map/map.cpp#L602

**Comment by ljbade** [comment]
It seems `resize()` is called with 0 width and height which is why `hasSize` fails.

**Comment by ljbade** [comment]
Resizing the window does trigger `resize()` with valued but only `transform` gets updated not `state` so `render()` still does not get called.

@jfirebaugh This doesn't seem right?

**Comment by ljbade** [comment]
Here is the zero resize offender: https://github.com/mapbox/mapbox-gl-native/blob/master/platform/default/glfw_view.cpp#L67

**Comment by jfirebaugh** [comment]
Looks like this regressed as part of #718. We have two PRs for this now, #742 and #747. :)

**Comment by ljbade** [comment]
@jfirebaugh oh did not see the dupe, lol
