### ISSUE TITLE
Best Practice to add Annotations to map and update them while zooming / panning 

### ISSUE THREAD

**Issue by guruduttstay** [mapbox/mapbox-gl-native#7461]
**Platform: Android **
**Mapbox SDK version: 4.2.1-SNAPSHOT **

### Background

I have been trying to implement MapBox on Android for last few weeks but didn't found the best way to add annotations to map and use it as per our need. I have read some docs and followed many discussion here and few on stackoverflow discussions as well.
Few discussion are still going on for e.g. [here ](https://github.com/mapbox/mapbox-gl-native/issues/7348)

### Our requirement 
1. Display up to 800 annotations
2. Each annotation has it's own priority value and based on current visible view Port on mobile screen we want to show top 20 highest priority annotations.

Now for adding all above average 800 Annotations to map I tried different methods

## 1. Markers
Using Markers on Map works fine but  
1. It flickers as shown in [Video](http://bit.ly/2h87qyD)
2. It is not possible animate markers to show/hide/change icon

## 2. MarkerView
Performance is not good [video ](http://bit.ly/2gIFRL7)
Looks like Marker View and GL are not in sync 

## 3. SymbolLayers
Added one layer for each annotation/pins so ended up adding 800 Layers to map 
 NB : I have to add one layer for one Annotation because I wanted to animate while showing and hiding and animation is possible on layer not on annotation level so I have to add one layer for each annotation
 - It worked well as per our expectation including animation 
 - Performs is okey on Samsung S6 [Video](http://bit.ly/2hOe8xG)
 - Slow on Samsung S4 [Video](http://bit.ly/2hF42fr)
 - Slow on Nexus 5 and many other devices
 - Adding more than 800 Layers to map takes some time even on S7, need faster way of doing it.

## 4. Apply Filter to layers 
So it require to add only few layers based on [discussion here](https://github.com/mapbox/mapbox-gl-native/issues/7348)
I ended up adding max 20 Layers to map which boosted the performance a bit but
After Applying Filter to map while zooming/panning map 
1. Map Flickers as shown in [video]( http://bit.ly/2hlzEt7) 
2. Animation is not possible for show/hide pins

What is best way for me ?

Thank you for reading long post :)

**Comment by cammace** [comment]
Your best option will be to make use of symbol layers but tweak it slightly from the way you describe it above. Instead of creating a layer for each marker, you can make use of just two layers by first adding all the markers to one layer and then when a user "clicks" a marker (using query map API) you can move that marker source to a different layer and animate that layer. This will result in this:

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5652865/21317947/db8c24d0-c5cc-11e6-8303-07895b83bfb4.gif)

Code for this can be [seen here](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/SymbolLayerActivity.java).

The marker flickering issues mentioned and shown in the videos is being tracked in [this ticket](https://github.com/mapbox/mapbox-gl-native/issues/6762). I haven't noticed this issue on the symbol layer however.

**Comment by asgeirhoem** [comment]
@cammace Thanks for the feedback!

We are not animating individual markers on click, so the suggested solution will unfortunately not address our problem.

We have POIs of different categories (presented with different marker styles). All POIs are subject to animation, depending on their rank among all POIs currently within the viewport. POIs that rank above the threshold are displayed using the expanded marker style; the rest are displayed using the collapsed marker style. As you change the visible map area, the selection of POIs to be expanded will continuously change. The goal is to always display a manageable amount of information in the map.

See our implementation on iOS, to better understand the desired behavior: https://www.dropbox.com/s/nzpp4ec5tr32y61/mapbox-ios.mov?dl=0

As you can see, the performance on iOS is fine.

**Comment by guruduttstay** [comment]
Thank you @cammace for response :)

I just tried your solution and reduced from 800 layers to 68 layers now 

###  What I did 
 As We have 48 different types of icons/categories so created 48 Symbol layers and assigned icons to those fixed layers and sources too
 
- Also added 20 more layers for which I keep updating source and image for layers and then animate it while zooming and panning and it worked :)

It is working on my slowest mobile too (Still I feel some time sluggish), for normal phone for e.g. Nexus and S5 it is working fine.

I am still testing and will update here again if found some issue here soon.


Still wondering if it is possible to apply multiple images to same SymbolLayer so it can be possible to reduce total number of layers, that will boost the performance bit more :)

**Comment by cammace** [comment]
Thanks for the information @asgeirhoem and that's great to hear @guruduttstay. I imagine you won't need as many layers when data driven styling arrives on Android. Happy to help you out if you run into any issues, can't wait to see the results of doing this. Closing ticket for now.

**Comment by guruduttstay** [comment]
Hi @cammace 

I just found bit better way to reduce number of layers for my case.

Following code is adding several images to same layers, so instead of creating one layer for one Image I am creating one Layer for all images and images are assigned to feature which reduced almost 40 layers in my case.

Can you confirm if this is right way of using layers for Android since I didn't found this in android doc but similar code works for javascript in some other documentation and it works for Android too?

Here in the following code I am assigning image to feature 
`feature.addStringProperty("image", symbolImageId);
`
and then while creating layer 

```
 SymbolLayer layer = new SymbolLayer(layerId, sourceId).withProperties(
                PropertyFactory.iconImage("{image}"),
                PropertyFactory.iconAllowOverlap(true)
        );
```

Simplified working code  looks like : 

```
    List<Feature> markerCoordinates = new ArrayList<>();
        for (POI poi : list) {
            String symbolImageId = poi.getID();
            AddUpdateImageToMapIfNeeded(mapboxMap, poi, symbolImageId); // Here I am creating image and adding to map if needed 

            Feature feature = Feature.fromGeometry(Point.fromCoordinates(coordinates), new JsonObject());
            feature.addStringProperty("image", symbolImageId);
            markerCoordinates.add(feature);
        }

        mapboxMap.addSource(new GeoJsonSource(sourceId, FeatureCollection.fromFeatures(markerCoordinates)));

        // Create a symbol layer which will use the image IDs from the image property in each feature.
        SymbolLayer layer = new SymbolLayer(layerId, sourceId).withProperties(
                PropertyFactory.iconImage("{image}"),
                PropertyFactory.iconAllowOverlap(true)
        );
        mapboxMap.addLayer(layer);

```

**Comment by cammace** [comment]
Initial impression is that this should work since we do something similar with the [text field here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolLayerActivity.java#L90). 

> Following code is adding several images to same layers

Are you using `mapboxMap.addImage()`? This currently takes in a bitmap which might be costly on performance if you need to do conversions vs just having the 40 layers.

**Comment by guruduttstay** [comment]
Thank you @cammace for response :)

Yes I am adding image with addImage() as per suggested [example link](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/SymbolLayerActivity.java)

```
Bitmap symbolImage = MyLocalUtil.generateBitMap(poi);
if (symbolImage != null) {
    mapboxMap.addImage(symbolImageId, symbolImage);
}

```

Performance is most important for us 
What is best for me, which one will perform better ?

40 bitmaps with one layer 
or 
40 layers with .....

**Comment by cammace** [comment]
The Android team hasn't tested this use case yet for performance, i'd recommend trying both cases out and doing benchmarking on each method to see which one is more performant. You might also find that they are both equal in performance, in this case, the one which requires less boilerplate code would be the one i'd go with.

**Comment by guruduttstay** [comment]
Thank you @cammace for help :)

I decided to go with many pois with Single layer :)
This works and implemented and works in all my testing devices :)

I was looking for if possible to add icon instead of BitMaps to MapBox but I will start another thread for that if needed  :)
