### ISSUE TITLE
clarify what removePack does, and if it needs to be resumed after app close

### ISSUE THREAD

**Issue by wibge** [mapbox/mapbox-gl-native#7466]
I am looking for clarification on using removePack.

When I create an offline region, download it, and then removePack, the tiles are not removed from the tiles table in cache.db, sometimes the expires column is changed but not always. 

If I remove a pack containing 100,000 tiles, the completion handler takes 20+ seconds to  be called. If I force close the app in that time, the pack and region are gone. Is there anyway to resume the removal of tiles?

**Platform:** ios
**Mapbox SDK version:** 3.4

### Steps to trigger behavior

 1. Download a (large) offline region
 2. remove the pack
 3.

### Expected behavior
The database becomes smaller

### Actual behavior
The database does not become smaller

**Comment by jfirebaugh** [comment]
[The documentation](https://www.mapbox.com/help/mobile-offline/#removing-offline-regions) is accurate as far as it goes:

> When you remove an offline region, any resources that are required by that region, but not other regions, become eligible for removal from the offline database. Because the offline database is also used as a general purpose cache for map resources, such resources may not be immediately removed if the implementation determines that they remain useful for general performance of the map.

Currently, there is an eviction process that is triggered when an offline region is removed. If the app exits before this process completes, it will be triggered again the next time a resource is added to the database. The eviction strategy and timing may change in future releases.

Does this answer your questions?

**Comment by wibge** [comment]
Yes, that answers my questions. Thank you. 

We would use an option for a more aggressive eviction strategy if one were available.
