### ISSUE TITLE
Reduce size of Mapbox.framework.dSYM/Contents/Resources/DWARF/Mapbox file

### ISSUE THREAD

**Issue by efrankenberger** [mapbox/mapbox-gl-native#7470]
**Platform:** iOS 10.0, Xcode 8.2
**Mapbox SDK version:** 3.3.7

### Steps to trigger behavior

 1. Add Mapbox 3.3.7 to Podfile
 2. Run pod install
 3. Add and commit changes in git
 4. Attempt to push changes to Github
 5. Encounter error 
File Pods/Mapbox-iOS-SDK/dynamic/Mapbox.framework.dSYM/Contents/Resources/DWARF/Mapbox is 180.38 MB; this exceeds GitHub's file size limit of 100.00 MB

### Expected behavior
The Mapbox file should not exceed 100 MB. This issue began after upgrading to 3.3.7 from 3.3.0.

### Actual behavior
The Mapbox file is over 100 MB, preventing it from being pushed to Github.

**Comment by 1ec5** [comment]
Per https://github.com/mapbox/mapbox-gl-native/issues/7029#issuecomment-261405921, the dSYM size will go down to around 36.7 MB in v3.4.0.
