### ISSUE TITLE
Mapbox vector tile server

### ISSUE THREAD

**Issue by JihadIsmail** [mapbox/mapbox-gl-native#7476]
**Platform:**
**Mapbox SDK version:**

### Steps to trigger behavior

 1. I am using mapbox Android SDK source code and try to customize it, but I can't run my project because of the "native" methods in "com.mapbox.mapboxsdk.http".
 2. I have added your mapbox-gl-native code in my project and built the c++ files, but still the code has undefined "JNI" function error! I don't know why?

### Expected behavior
<Rendering the geoJson Data from my own servers>
what I am trying to do is:
customize your source code so that instead of using the geojson data from your servers, I want to use my own servers, and use your sdk for only rendering my data. Is it available to do that with your SDK? Is there any commercial state here?

### Actual behavior
Error in native functions.
![screenshot from 2016-12-18 15-22-20](https://cloud.githubusercontent.com/assets/9353783/21293813/7022e2fa-c537-11e6-96ab-ce3d0b646258.png)

**Comment by jfirebaugh** [comment]
Hi @JihadIsmail -- you don't need to make a custom build in order to use your own servers for GeoJSON data. You can use a [GeoJSON source](https://www.mapbox.com/mapbox-gl-style-spec/#sources-geojson) with any URL.

**Comment by truonghandang** [comment]
Hi @jfirebaugh -- If I use GeoJSON source with my data, what is the price paid?

**Comment by thdpt** [comment]
Hi @JihadIsmail -- If I use GeoJSON with my data, what is the price paid?
