### ISSUE TITLE
Tile server

### ISSUE THREAD

**Issue by JihadIsmail** [mapbox/mapbox-gl-native#7482]
**Platform:**
**Mapbox SDK version:**

### Steps to trigger behavior

 1. First I have my own tile server which contain the map data from OSM , and I want to use your AndroidSDK to present this data. the question is where to put my own URL?.
2. 

### Expected behavior
use my own tile server with my data instead of yours

### Actual behavior
the sdk use your servers

**Comment by friedbunny** [comment]
Hi @JihadIsmail, have a look at [our Android SDK documentation](https://www.mapbox.com/android-sdk/). Specifically, it sounds like you’ll want [this custom raster tiles example](https://www.mapbox.com/android-sdk/examples/custom-raster/).

Please note, however, that this GitHub project is not a support forum. If you have questions about how to use our SDK or other Mapbox products, feel free to [contact our support staff](https://www.mapbox.com/help/).
