### ISSUE TITLE
GeocoderAutoCompleteView missing in 4.2.0

### ISSUE THREAD

**Issue by vanshg** [mapbox/mapbox-gl-native#7489]
Mapbox SDK version: 4.2.0

One of the features of the 4.2.0 release was to have "Integrated support for Mapbox Android Services". I was previously including MAS as a separate dependency and was using the GeocoderAutoCompleteView from MAS. However, when I upgraded to 4.2.0 and removed the MAS dependency, GeocoderAutoCompleteView does not seem to exist anymore. Has it been removed?

**Comment by tobrun** [comment]
Hi @vanshg, that widget is actually coming from another dependency, you can find the repository here https://github.com/mapbox/mapbox-java. The 4.2.0 uses the 1.3.1 version of that library. Here is an [example](https://github.com/mapbox/mapbox-java/blob/master/libandroid/app/src/main/java/com/mapbox/services/android/testapp/geocoding/GeocodingWidgetActivity.java) of the Geocoder widget. Feel free to open a ticket on that repo if this hasn't resolved the issue. 
Thank you for reaching out!
