### ISSUE TITLE
Old token cached in XCode

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#749]
When running `make xproj`, then clicking the Run button in XCode, vector tile request URLs have an old (revoked) access token attached. Exporting a valid access token as an env var and running `make lproj` works fine.

I've been struggling with this and can't find any trace of where this might be hidden, tried wiping the `mapbox-gl-native` repo and re-cloning to no avail. Even tried grepping my entire system that turned up no trace of the old token in any files, yet it still shows up in vector tile request URLs, and setting a new env var in `Scheme > osxapp` doesn't seem to have any effect, nor does deleting all the existing schemes and auto-recreating. Not seeing this token ANYWHERE.

@incanus Help?

**Comment by springmeyer** [comment]
@mikemorris maybe it is in ~/Library/Developer/Xcode/DerivedData/ ?

**Comment by ljbade** [comment]
Seems like a bit of a virtual witch hunt. Surprised grep did not pick it up, they must encode the value or something.

**Comment by incanus** [comment]
The environment variable is cached by our app, which @kkaefer added as a convenience. Easiest fix is to reset settings in iOS Simulator. =

**Comment by incanus** [comment]
Specifically, see the top of viewDidLoad here: 

https://github.com/mapbox/mapbox-gl-cocoa/blob/master/app/MBXViewController.mm=

**Comment by ljbade** [comment]
Ah I see, but it should pull in the new value and overwrite the cached one from environment right?

**Comment by kkaefer** [comment]
Hm, sounds like the steps you did should clear the token, @mikemorris. Can you also try to delete the derived data by opening the Organizer in Xcode, and deleting the project from the list?

![](http://i.kkaefer.com/74wyn.png)

**Comment by ljbade** [comment]
@kkaefer I think @mikemorris fixed it by clearing the settings from his iOS emulator - he said you cache the key somewhere

**Comment by kkaefer** [comment]
Maybe, but he was running `make xproj`, which shouldn't pull any values from the iOS project.

**Comment by mikemorris** [comment]
So I've been running `make distclean && make xproj` which runs the `clear_xcode_cache` task which wipes the `DerivedData` folder (I confirmed this was actually happening), yet the old token still persists. I actually can't run the app after running `make iproj` to open in the simulator because I hit this error:

![screen shot 2015-01-13 at 11 35 55 am](https://cloud.githubusercontent.com/assets/1149913/5724360/f96f0d04-9b18-11e4-9168-a52334acf74a.png)
![screen shot 2015-01-13 at 11 36 22 am](https://cloud.githubusercontent.com/assets/1149913/5724359/f96ee7ac-9b18-11e4-8846-2bbfc9ee5a3f.png)

**Comment by mikemorris** [comment]
Ran `Reset Content and Settings` in the iOS Simulator app too, still seeing the expired token when running `make xproj`.
![screen shot 2015-01-13 at 11 44 34 am](https://cloud.githubusercontent.com/assets/1149913/5724472/c714bda8-9b19-11e4-8845-bef1408bd077.png)

**Comment by incanus** [comment]
Does step debugging not reveal when in the URL formation process this is getting setup? I can try to help you tomorrow am @mikemorris. =

**Comment by mikemorris** [comment]
I'll try stepping through in the debugger @incanus, was hoping there might be an easier fix.

**Comment by incanus** [comment]
I can't comprehend just thinking about it why this would happen, but then again: pretty much all bugs. 

¯\_(ツ)_/¯=

**Comment by mikemorris** [comment]
Looks like the token somehow ended up in `~/Library/Application\ Support/Mapbox\ GL/cache.db`, will add purging this file to the `clear_xcode_cache` make task.

**Comment by mikemorris** [comment]
The damn indentation on the `clear_xcode_cache` task seems to have been making the task not run, possible that something else was actually clearing out derived data.

**Comment by mikemorris** [comment]
FWIW this seems to be working with an actual `export MABOX_ACCESS_TOKEN=xxx && make xproj`, I don't seem to have to edit the scheme at all.

**Comment by jfirebaugh** [comment]
> Looks like the token somehow ended up in ~/Library/Application\ Support/Mapbox\ GL/cache.db

@kkaefer Is this intentional? Caching the token anywhere seems counterintuitive to me.

**Comment by kkaefer** [comment]
@mikemorris: do you have more intelligence on where it was in the cache database? I don't think there's code that puts it there and there's code that specifically removes it before writing the URLs in the cache db.

**Comment by mikemorris** [comment]
@kkaefer Unfortunately no, I didn't feel like spending time figuring out sqlite query syntax so I just deleted the whole database.

**Comment by 1ec5** [comment]
> Looks like the token somehow ended up in ~/Library/Application\ Support/Mapbox\ GL/cache.db

I wouldn’t be surprised if `NSUserDefaults` puts stuff in there. The iOS demo app [caches the access token using a user default](https://github.com/mapbox/mapbox-gl-native/blob/256b748458571201fe2b64bdf84dae6ec9b5932e/ios/app/MBXAppDelegate.m#L15). Clearing your derived data has no effect on what’s installed on the Simulator or device – you need to hold down the app on the home screen and delete it from there.
