### ISSUE TITLE
Compass click rotates around center

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#7493]
When we click the compas we call into `Map::resetNorth` but this doesn't take in account the SDK provided focal point. As a result the map is rotated on the center instead around a focal point as the MyLocationView. 

![ezgif com-video-to-gif 5](https://cloud.githubusercontent.com/assets/2151639/21352343/692d5ada-c6c1-11e6-9bb8-cbffabb7d0d9.gif)

**Comment by jl-skyline** [comment]
wasn't able to work properly with rotateBy(sx, sy, ex, ey, (optional) d);
I was assuming sx, sy be focal location but i wasn't able to find what ex, ey should be.

it worked with setBearing(degree, sx, sy) but there isn't any animation.
setBearing(degree, duration) provided animation but showing the same original issue.
it would be better to have something takes sx, sy and duration at the same time.

**Comment by jl-skyline** [comment]
I'm not sure if you have this captured as an issue, it doesn't seem to rotate around my location when I manually rotate the map.  user's location moves while rotating.

**Comment by tobrun** [comment]
Sorry if I have put you on the wrong track, it should be indeed setBearing instead of rotateBy. It's correct that we don't expose in the Android binding atm but we do expose this on the C++ side in map.cpp:

```cpp
void Map::setBearing(double degrees, optional<ScreenCoordinate> anchor, const Duration& duration) {
    impl->cameraMutated = true;
    impl->transform.setAngle(-degrees * util::DEG2RAD, anchor, duration);
    impl->onUpdate(Update::Repaint);
}
```

What needs to happen is to expose this function in jni.cpp, NativeMapView.java and transform.java.
LMK if you need more information on this.

**Comment by jl-skyline** [comment]
Just a thought, why not just create
```
void Map::resetNorth(anchor, duration) {
  hideCompass();
  setBearing(0, anchor, duration);
}
```
