### ISSUE TITLE
Show checkstyle faillures in CI

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#7495]
We recently added checkstyle configuration on CI in #7442, when someone commits code that doesn't apply our code style the CI build will fail. Currently it shows the follow output:

```
* What went wrong:
Execution failed for task ':MapboxGLAndroidSDK:checkstyle'.
> Checkstyle rule violations were found. See the report at: file:///bitrise/src/platform/android/MapboxGLAndroidSDK/build/reports/checkstyle/checkstyle.html
```

This is not very useful since the report file above will be deleted after the workflow has finished running and the current output doesn't say what the cause of the faillure was.  

I'm seeing two possibilities here:
 - show the output directly in the CI console 
 - add as part of the build artifact 

cc @cammace

**Comment by cammace** [comment]
You can also just scroll up slightly in bitrise and it will give you the violation that caused the fail.

**Comment by tobrun** [comment]
:facepalm:
