### ISSUE TITLE
SupportMapFragment doesn't have setStyle method.

### ISSUE THREAD

**Issue by xam0n** [mapbox/mapbox-gl-native#7496]
Android 6.0
MapBox sdk version: 4.2.0-beta

MapView has method:` public void setStyle(@Style.StyleUrl String style)`, but SupportMapFragment doesn't have. I think map fragment must support it too. I found the following workaround:    `((MapView)mMapFragment.getView()).setStyle(isSatellite ? Style.SATELLITE : Style.MAPBOX_STREETS);`

**Comment by tobrun** [comment]
@xam0n you can use `SupportMapFragment.newInstance(@Nullable MapboxMapOptions mapboxMapOptions)` and provide a style inside the MapboxMapOptions parameter. Thank you for reaching out!
