### ISSUE TITLE
Mapbox vector tiles attributes search (Swift-3)

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [mapbox/mapbox-gl-native#7504]
**Platform**:   Swift
    **Mapbox SDK version:**   ios-v3.4.0-beta.5

Hi,
  
I am looking for vector tiles attribute search using mapbox. We also aware of MapboxGeocoder search which is used to search for placemarks, country, state etc. But how to search our custom tiles attributes.

**Example** :  We have loaded a list of school vector layer on a map which contains school name, location and etc. as attributes, now we need to search for school names from it.

Please help me. Thanks

**Comment by 1ec5** [comment]
Currently, the iOS SDK only provides methods to inspect the attributes of visible features at a given point or within a given bounding box in the current map viewport. #7319 would allow you to filter the results by attributes, while #5792 would add a version of these methods that would include features that are present in the source but not currently visible in a layer. However, feature querying is fundamentally limited to the current viewport. It isn’t intended as a general-purpose search tool.

It sounds like you’re looking for something more like the [Mapbox Tile Query API](https://www.mapbox.com/api-documentation/#retrieve-features-from-vector-tiles), which works with any data set uploaded to Mapbox Studio and can query any part of the world. It only lets you filter by source layer, not by attribute, however.

**Comment by ThiyagarajanShivSankaran** [comment]
Hi Minh,
 
Thank you for the quick reply. It seems like "queryRenderedFeatures" and "querySourceFeatures" is not available with MGLMapView. So how we have to implement the custom search tool, or we can't.

Also, is there any way to use filters for searching attributes.

**Comment by friedbunny** [comment]
@ThiyagarajanShivSankaran Please see [`-[MGLMapView visibleFeaturesAtPoint:]`](https://www.mapbox.com/ios-sdk/api/3.4.0-beta.5/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)visibleFeaturesAtPoint:) and similar methods.

When v3.4.0 is officially released, [look to our website](https://www.mapbox.com/ios-sdk/examples/) for examples of how to use these methods in conjunction with runtime styling.

**Comment by 1ec5** [comment]
As @friedbunny mentions, `-visibleFeaturesAtPoint:` and related methods are the iOS SDK’s equivalent to `queryRenderedFeatures()` in GL JS.

#5792 tracks adding an equivalent to GL JS’s `querySourceFeatures()`. #7319 tracks adding a predicate option that would work similarly to GL JS’s filter option.

**Comment by ThiyagarajanShivSankaran** [comment]
Thank you **@friedbunny** and **@Minh** for the reply.

Actually, I am already using -[MGLMapView visibleFeaturesAtPoint:], and it works well no problem with that.

But i need to search by attribute values , not by latlong or rect.
