### ISSUE TITLE
Boolean functions are incorrectly interpolated

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#7525]
When evaluated at `2`, the function `{stops: [[1, false], [3, true]]}` should be `false`. But mapbox-gl-native currently evaluates it to `true`. This is because there's no explicit specialization for `Interpolator<bool>`, so the default formula `a * (1.0 - t) + b * t` is used.

**Comment by brunoabinader** [comment]
Great finding, @jfirebaugh!
