### ISSUE TITLE
Upgrade to NDK r10d

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#753]
New NDK is out: https://developer.android.com/tools/sdk/ndk/index.html

- [x] update mason to use latest compilers etc
- [x] upgrade all mason libs and rebuild
- [x] upgrade build AMI
- [ ] upgrade dev team to latest NDK

**Comment by ljbade** [comment]
Shouldn't need to use 7z to extract the NDK anymore, self-extracting should work

**Comment by springmeyer** [comment]
> update mason to use latest compilers etc

:+1: 

> upgrade all mason libs and rebuild

Cool, just created https://github.com/mapbox/mason/issues/46 to help with this.

> upgrade build AMI

Please take advantage of this second pass to document your steps well so others can know how it is done and help in the future.

> Shouldn't need to use 7z to extract the NDK anymore, self-extracting should work

Sure, if it works better now (still makes sense to have 7z packaged for other stuff though).

**Comment by bleege** [comment]
> Please take advantage of this second pass to document your steps well so others can know how it is done and help in the future.

+1

This could be super useful for the Android Raster SDK as Travis can be a bit slow to update Android Libraries, which produce failing builds.

**Comment by ljbade** [comment]
OK everything updated.

@incanus and @bleege be sure to update you local NDK installs.
