### ISSUE TITLE
Android: too many state updates prior to rendering

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#7536]
On Android, we seem to be doing way too many state updates: I'm seeing 30+ calls to `setScalePoint` with minor differences, which are followed immediately with a call to `update()` (meaning we recalculate the style + tiles, a relatively expensive operation). We should track down the source that leads to `setScalePoint` being called to many times within one frame.

**Comment by tobrun** [comment]
I'm able to trace that this comes from MapGestureDetector#onScroll while we pan the map. I'm now looking into limiting the amount of updates we pass to core. This will require us to keep state of the amount of pixels scrolled in x,y and time the duration since previous moveBy.

**Comment by tobrun** [comment]
One thing I'm also noticing is that setScalePoint is called multiple times after the gesture has finished. Those updates are originating from somewhere else.

**Comment by tobrun** [comment]
A lot has moved since 2016, please reopen if still an issue. Closing as stale.
