### ISSUE TITLE
mapbox android

### ISSUE THREAD

**Issue by abourtema** [mapbox/mapbox-gl-native#7538]
I have problem , I use Mapbox in android , the app run good but when download map show me Mapbox tile count limit exceeded: 6000 , I use less 4000 tile can use help me

**Comment by friedbunny** [comment]
Hello @abourtema, thanks for reaching out. While we’re happy to help with difficult implementation details, this GitHub project is not the place. Please [have a look at our help resources](https://www.mapbox.com/help/) and contact us through the form there if you cannot find a solution to your issue.

Specifically, if you haven’t already read our [offline guide](https://www.mapbox.com/help/mobile-offline/), check that out first.
