### ISSUE TITLE
-[MGLShape geoJSONDataUsingEncoding:] should encode bounding box

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7541]
Classes conforming to the MGLOverlay protocol should implement `-[MGLShape geoJSONDataWithEncoding:]` to set the optional [`bbox`](https://tools.ietf.org/html/rfc7946#section-5) member to the value of the `MGLOverlay.overlayBounds` property.

/cc @tmcw

**Comment by eimantas** [comment]
Do you mean the `geoJSONDataUsingEncoding:`? I looked at `MGLShape` and it seems the default implementation attempts to use `geoJSONObject` that in turn gets the `geometryObject`. However I also noticed there are `geoJSONDictionary` methods that return what you're probably looking for and is used in all `*Feature` related classes.

Can you clarify if my assumption regarding the `geoJSONDictionary` is correct?

**Comment by 1ec5** [comment]
Yes, I meant `-geoJSONDataUsingEncoding:`. This method uses `-geoJSONObject` in conjunction with `mapbox::geojson::stringify()` to avoid the overhead of serializing Objective-C representations of everything inside of the shape. So this task is blocked by mapbox/geometry.hpp#21.
