### ISSUE TITLE
Fling gesture works differently in 4.2.1

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#7549]
**Platform:** Android
**Mapbox SDK version:** 4.2.1

### Steps to trigger behavior

MapboxMap -> Fling gesture -> camera very twitches. 

not reproduced on 4.2.0

**Comment by tobrun** [comment]
@klblk we changed this interaction to work around https://github.com/mapbox/mapbox-gl-native/issues/5281. As [noted](https://github.com/mapbox/mapbox-gl-native/pull/7383#pullrequestreview-12495973) by @cammace, we will be revisiting this. Let us know in what way you think the gesture needs improvement on. Feel free to try run with this yourself and create a PR for it.

**Comment by klblk** [comment]
I don't like fixed animation time that does not depend on the velocities.

**Comment by andrei-egeniq** [comment]
Second vote for the issue, small movements cause large scrolls in 4.2.1
Our designers decided to keep using 4.2.0 because of this.

**Comment by tobrun** [comment]
#7676 got merged, feel free to try this fix out with the new SNAPSHOT next week (build is currently broken, see #7640). Closing.
