### ISSUE TITLE
Memory leak in 4.2.0

### ISSUE THREAD

**Issue by olliSP** [mapbox/mapbox-gl-native#7551]
**Platform: Android**
**Mapbox SDK version: 4.2.0**

Two Activities:
1. MainActivity, does not use Mapbox, only launches MapActivity (no android:configChanges in Manifest)
2. MapActivity, uses Mapbox (no android:configChanges in Manifest). MapActivity.onBackPressed() calls Activity.finish();

### Steps to trigger behavior

 1. Launch MapActivity and rotate screen to trigger Activity recreation.
 2. adb shell dumpsys meminfo <my.demo.app> is used to monitor Activity count.
 3. Causing GC (with Android Device Monitor) does not decrease Activity count.

### Expected behavior
If MainActivity and MapActivity are launched, number of Activities should be 2 after screen rotation.

### Actual behavior
With Mapbox 4.2.0 Activity count is 3 after screen has been rotated. Subsequent screen rotations does not increase the Activity count, so looks like a reference to first instance of MapActivity is kept somewhere. When MapActivity.onBackPressed() invokes finish(), Activity count decreases to 2 (it should be 1).

Can be reproduced with 4.2.1.

4.2.0-beta.3 works ok.

**Comment by jfirebaugh** [comment]
Haven't heard of this occurring in 5.1.0 or later; please report back if it's still an issue.
