### ISSUE TITLE
Data property-based circle-color steps ignored in iOS

### ISSUE THREAD

**Issue by mirkokiefer** [mapbox/mapbox-gl-native#7554]
**Platform:** iOS
**Mapbox SDK version:** v3.3.7

### Steps to trigger behavior

Rendering a circle with circle-color depending on a data property:

``` json
{
    "circle-color": {
        "property": "value",
        "stops": [
            [
                0,
                "#ffffff"
            ],
            [
                100,
                "#ff0000"
            ]
        ]
    },
    "circle-opacity": 0.02,
    "circle-radius": 50
}
```

The rendering works correctly with the js SDK but the color steps are ignored on iOS.

Web screenshot:
![screen shot 2016-12-28 at 19 11 43](https://cloud.githubusercontent.com/assets/315252/21521728/2fb927c6-cd32-11e6-847e-41cc77ed0822.png)

native iOS screenshot:
![img_8456](https://cloud.githubusercontent.com/assets/315252/21521784/96a9dc00-cd32-11e6-977b-bd25120f0ef2.PNG)

**Comment by 1ec5** [comment]
Property functions are not yet supported in the iOS SDK. This feature is scheduled for the upcoming v3.5.0 release. Please see mapbox/mapbox-gl-native#4860 for current progress.
