### ISSUE TITLE
Android Layer Filtering - Not working

### ISSUE THREAD

**Issue by nitrag** [mapbox/mapbox-gl-native#7555]
Filtering in Android is not working as easily (or at all for that matter) as Predicates in iOS. 

I get the following error:

```
E/mbgl: {app}[JNI]: Error setting filter: filter operator must be a string
```

The code is:
```
public class TrailData {
	...
	...

	public Filter.Statement[] getFilterStatement() {
        return filterStatement;
    }

    public TrailData setFilterStatement(Filter.Statement[] filterStatement) {
        this.filterStatement = filterStatement;
        return this;
    }
}

Filter.Statement easylt = Filter.lt("difficulty", 4);
Filter.Statement easygt = Filter.gt("difficulty", 0);
Filter.Statement truck = Filter.eq("truck", true);

dataSources.add(new TrailData()
                .setTitle("truck-easy")
                .setFilterStatement(new Filter.Statement[]{truck, easylt, easygt}));
```

The geojson looks like the following, with Bool and Number.

```
{
    "properties": {
        "truck": true,
        "difficulty": 3
    }
}
```

Implementation:
```
for(TrailDataSource.TrailData trailData : new TrailDataSource().getDataSource(getApplicationContext())) {
    LineLayer lineLayer = new LineLayer(trailData.getTitle(), "trail-data");
    lineLayer.setFilter(trailData.getFilterStatement());
    map.addLayer(lineLayer);
}
```

I realize this is still beta, but Documentation says the operator should be a string??

Android
4.2.0-beta5

### Expected behavior

Have one data source, 12 different/filtered layers, so I can toggle the layers on and off.

### Actual behavior

Filters do not work so all geojson data get drawn on all layers in result.

**Comment by nitrag** [comment]
It might be related to setting multiple filters at once. `setFilter(Object[] filter)`...

`{app}[JNI]: Error setting filter: filter operator must be a string` 
only shows if adding multiple filter statement ...but if adding only a single filter statement it doesn't give an error.


```
fillLayer.setFilter(Filter.lt("bar", true)); [works]
fillLayer.setFilter(new Filter.Statement{Filter.eq("foo", true), Filter.gt("bar", false)}); [doesnt work]
fillLayer.setFilter(new Object[][]{Filter.eq("foo", true).toArray(), Filter.gt("bar", false).toArray()}); [doesnt work]
```

**Comment by jfirebaugh** [comment]
@zugaldia @tobrun What's the purpose of the `void setFilter(Object[] filter)` signature? Aren't compound filters covered via `Filter.all`, `Filter.any`, or `Filter.none` and `void setFilter(Filter.Statement filter)`?

**Comment by tobrun** [comment]
@nitrag 
The syntax for having multiple filters should be something like:
```
layer.setFilter(all(in("number", STOPS_FOR_ROUTE), eq("name","Changi Chapel Museum")));
```

In your code this would mean changing:

```
new Filter.Statement[]{truck, easylt, easygt}
to
all(truck, easylt, easygt)
```

@jfirebaugh idk, I believe these are obsolete with using compound statements. cc @ivovandongen

**Comment by nitrag** [comment]
Ah yes, thank you!

**Comment by jfirebaugh** [comment]
Filed a followup issue. ☝️

**Comment by kavathiyamahesh** [comment]
Hello @tobrun 

Thanks for your supporting. 
It's not working for me.

Please check my gsonsource [Here](http://prntscr.com/g9nb76)
You can see RED box type_ct=0 means [Red], 1 means [Blue], 2 means [Green]

I have to add 3 type of PIN in mapbox. 

below is my code:

`       Bitmap red = BitmapFactory.decodeResource(this.getResources(), R.drawable.redicon);
        mapboxMap.addImage("red", red);

        Bitmap blue = BitmapFactory.decodeResource(this.getResources(), R.drawable.blueicon);
        mapboxMap.addImage("blue", blue);

        Bitmap green = BitmapFactory.decodeResource(this.getResources(), R.drawable.greenicon);
        mapboxMap.addImage("green", green);
        
       SymbolLayer unclustered = new SymbolLayer("red", sourceID);
        unclustered.withProperties(PropertyFactory.iconImage("red"));
        unclustered.setFilter(Filter.eq("type_ct", "0"));
        mapboxMap.addLayer(unclustered);

`
Clustering is working fine, but when I doing Zoom after I can't able to see RED PIN. If i remove ** unclustered.setFilter(Filter.eq("type_ct", "0"));** line then i able to see red pin but it's for all type not specific 0,1,2.

Thanks
