### ISSUE TITLE
How to purge cache or change change policy?

### ISSUE THREAD

**Issue by mirkokiefer** [mapbox/mapbox-gl-native#7556]
When making changes to data sets or layers, it sometimes takes hours until the data appears on the rendered map.

This only happens if the areas have previously been viewed and must therefore be cached.

Is it possible to change the cache policy?

How to purge the tile cache?

**Comment by jfirebaugh** [comment]
Vector and raster tiles will be refreshed on the schedule defined by the standard HTTP response headers (`Cache-Control` and `Expires`). #4376 tracks adding an API for purging the cache.

**Comment by mirkokiefer** [comment]
I'm hosting the maps on mapbox using mapbox studio. What are their default cache policies? Is there a way to modify it?
