### ISSUE TITLE
MGLForegroundStyleLayer.sourceIdentifier is unimplemented

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7557]
MGLForegroundStyleLayer declares a `sourceIdentifier` property, but its concrete subclasses (such as MGLLineStyleLayer) don’t implement a getter or setter for the property, so attempting to use the property will trigger a crash. The underlying mbgl classes do expose getters and setters for this property, so it should just be a matter of hooking them up in the generated source code.

/cc @frederoni

**Comment by frederoni** [comment]
Resolved in #7570
