### ISSUE TITLE
how to change mapbox user location image

### ISSUE THREAD

**Issue by Bicubiciosdev** [mapbox/mapbox-gl-native#7562]
Plateform=IOS,Objective c
I need to set a custom image for the user location annotation. This is not a problem to implement both in MapKit or GoogleMaps but how do I deal with this using Mapbox? i will try this code but change user location image only display blue dot.

[- (MGLAnnotationImage *)mapView:(MGLMapView *)mapView imageForAnnotation:(id <MGLAnnotation>)annotation
{

        // Try to reuse the existing ‘pisa’ annotation image, if it exists.
    MGLAnnotationImage *annotationImage = [mapView dequeueReusableAnnotationImageWithIdentifier:@"annotation"];

    if (self.mapview.userLocation == annotation ) {

        UIImage *image = [UIImage imageNamed:@"Tutorial_Map_checkpoint_blue.png"];

        image = [image imageWithAlignmentRectInsets:UIEdgeInsetsMake(0, 0, image.size.height/2, 0)];

        annotationImage = [MGLAnnotationImage annotationImageWithImage:image reuseIdentifier:@"challenge1"];
    }

return annotationImage;
}

]

![screen shot 2017-01-02 at 1 41 43 pm](https://cloud.githubusercontent.com/assets/24543108/21588080/091f040c-d109-11e6-801b-a2aec327ef38.png)

**Comment by friedbunny** [comment]
Custom user location annotation views are a feature of the upcoming v3.4.0 release, which you can try out [in beta now](https://github.com/mapbox/mapbox-gl-native/releases). 

Once v3.4.0 is officially available there will be public documentation and examples [on our website](https://www.mapbox.com/ios-sdk/). Until then, hopefully [this debug code](https://github.com/mapbox/mapbox-gl-native/blob/eefbb754d0ef98af39f9b2dac8dc0a471dc41d27/platform/ios/app/MBXViewController.m#L1424-L1436) will be enough to point you in the correct direction. Note that plain images are not supported — you should wrap any image you wish to use in a view.

**Comment by Bicubiciosdev** [comment]
in dynamic framework release (v3.4.1) is available in mapbox.in this sdk i need change userlocation image if possible please give some hint code ..

**Comment by Bicubiciosdev** [comment]
hiii,

1)in  mapbox website dynamic framework release (v3.4.1) is available in
mapbox.if possible to change userlocation image than please send me some
code and link i will read github issue but not getting any idea.
2)how can i store tiles in sqlite database and load in mapbox
3)mapbox provide called didupdate location method without internet because
i will try but not getting
4)if i want to remove mapbox watermark logo than what was the process

please check and reply as soon as possible
