### ISSUE TITLE
[IOS] MGLMapViewDelegate "strokeWidthForPolygon" && "strokeColorForPolygon"

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [mapbox/mapbox-gl-native#7567]
Hi there, how can we highlight a polygon with different "stroke color" and "stroke width" along with "fill colors".

 MGLMapViewDelegate don't have "strokeWidthForPolygon" and "strokeColorForPolygon.

Help me, Thanks.

**Comment by friedbunny** [comment]
Polygons are considered shapes and are thusly also configured via those delegate methods: in this case, you’ll want [`-[MGLMapViewDelegate mapView:strokeColorForShapeAnnotation:]`](https://www.mapbox.com/ios-sdk/api/3.3.7/Protocols/MGLMapViewDelegate.html#/c:objc(pl)MGLMapViewDelegate(im)mapView:strokeColorForShapeAnnotation:).

It is currently not possible to change the stroke width of shape annotations. The typical work around is to use a separate polyline around the edge of your shape. Runtime styling in v3.4.0 will enable other implementations, so watch for examples of those once it’s released.

**Comment by ThiyagarajanShivSankaran** [comment]
Thanks @friedbunny for your reply.
