### ISSUE TITLE
MarkerView update lag

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#7568]
Recent refactors has tried limiting the amount of map change events we push to components in the Android SDK. This resulted in changing the map change events emitted to MarkerViewManager. This component is responsible for triggering updates on MarkerViews. Capturing from @kkaefer that this has regressed. Note that this is not the same issue as the jiggling/wiggling issue.

**Comment by Emeritus-DarranKelinske** [comment]
I've noticed if you touch the map the markers tend to reflect their latest updates.
