### ISSUE TITLE
Remove all deprecated methods

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#7575]
The next Android release cycle (5.x) will break SEMVER compatibility with previous versions. This is a good moment to remove all `@Deprecated` members from the codebase. 

I'm still seeing 7 matches across 5 files:

![image](https://cloud.githubusercontent.com/assets/6964/21594509/5b14c91c-d0f1-11e6-9dff-7d07db66d406.png)

@mapbox/android: Any good reasons to keep any of these methods around one more version?

**Comment by tobrun** [comment]
- [ ] Deprecation Emerald-v8:
    - good to remove, it was replaced with outdoors in v9
- [ ] Deprecation setStyleUrl:
  - there is some confusion related to this deprecation after discussing this with @cammace . This deprecation was valid if we didn't revert versioned styling methods in https://github.com/mapbox/mapbox-gl-native/issues/5193. If we decide to keep as-is implementations we should remove deprecation, if we would move to versioned style methods in Style.java we can remove the method fully.
- [ ] Deprecation textureMode:
   - I wouldn't mind keeping this around until it starts blocking implementation of other features (eg. GLSurfaceView). We currently advice using the texture mode to workaround the issue of showing a map in a dialog #6101 or if ViewMarker synchronisation should be more performant. 
- [ ] Deprecation dismiss tracking on gesture
   - need to double check but I think these are good to remove. They were replaced with methods specific to certain gestures for more granular control. 
- [ ]  setAccessToken/getAccessToken in OfflineManager
   - Other deprecations related to accesstoken have been rerouted to use `Mapbox.java`. It seems that this occurrence was missed. Will create a PR and link to this issue and the other accesstoken deprecation issue in #5621 for MapView and MapboxMap.

**Comment by olliSP** [comment]
Before deprecated methods are removed, please take this issue into account:

https://github.com/mapbox/mapbox-gl-native/issues/7584
