### ISSUE TITLE
[android] MapboxAccountManager cannot be restarted

### ISSUE THREAD

**Issue by olliSP** [mapbox/mapbox-gl-native#7584]
**Platform: Android**
**Mapbox SDK version: 4.2.1**

MapboxAccountManager is singleton and can be started only once with given access token. This is a problem for "showcase" apps which uses multiple Mapbox accounts (access token + style url combinations) in different Activities.

```
public static MapboxAccountManager start(Context context, String accessToken) {
        if (mapboxAccountManager == null) {
             // init some stuff
        }
        return mapboxAccountManager;
    }
```

Workaround would be to use MapboxMapOptions.accessToken() but it is deprecated and assumably going away in the future. However, it can be used to initialise MapboxMap and MapView with different access tokens within the same app.

Suggested solutions:

1. check accessToken in MapboxAccountManager.start(). If it was different than in previous run, reset whole thing.

or

2. Implement MapboxAccountManager.stop() which would reset whole thing.

**Comment by tobrun** [comment]
@olliSP thank you for reaching out and explaining your issue. Note that we have removed MapboxAccountManager on the master branch and now working towards using [Mapbox](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java#L21) instead. I think exposing a setter their would solve the issue for you. Before loading a MapView you can call into `Mapbox#setAccessToken(String)` to change the current active accesstoken.

**Comment by olliSP** [comment]
Hi @tobrun , 

Thank you for the heads-up! I think public setter would work for us.

Cheers!

**Comment by lilykaiser** [comment]
Closing because this ticket refers to deprecated code. If this is still a problem, please feel free to reopen. Thanks!
