### ISSUE TITLE
Improve error for view annotations with invalid coordinates

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-gl-native#7597]
**Platform:** iOS
**Mapbox SDK version:** 3.3.7, 3.4.0-beta.6
### Steps to trigger behavior

 1. Create a fresh application with the Mapbox framework
 2. Add a new `MGLPointAnnotation`, specifying an invalid coordinate (ex `(-200,-200)`), and adding a corresponding `MGLAnnotationView` ([full Gist here](https://gist.github.com/captainbarbosa/15cd62b4aca65555c6bbddf66f7512a9))
 4. Observe resulting error

### Expected behavior
The console should display a more informative error stating the coordinates, perhaps by discarding the invalid annotation and producing a warning instead.

### Actual behavior
The console produces an error that doesn't particularly help the user know that their coordinate is invalid:
```
*** Terminating app due to uncaught exception 'CALayerInvalidGeometry', 
reason: 'CALayer position contains NaN: [nan nan]'
*** First throw call stack:
(
    0   CoreFoundation                      0x0000000110e8bd4b __exceptionPreprocess + 171
    1   libobjc.A.dylib                     0x00000001108ed21e objc_exception_throw + 48
    2   CoreFoundation                      0x0000000110ef52b5 +[NSException raise:format:] + 197
    3   QuartzCore                          0x0000000111b31f92 _ZN2CA5Layer12set_positionERKNS_4Vec2IdEEb + 152
    4   QuartzCore                          0x0000000111b32107 -[CALayer setPosition:] + 44
    5   UIKit                               0x000000011218ddea -[UIView setCenter:] + 233
    6   Mapbox                              0x000000010fefbb87 -[MGLAnnotationView setCenter:] + 61
    7   Mapbox                              0x000000010fee1b07 -[MGLMapView addAnnotations:] + 3056
    8   Examples                            0x000000010fcff1e8 -[AnnotationViewMultipleExample viewDidLoad] + 1576
```

cc @boundsj @1ec5

**Comment by julianrex** [comment]
Still valid.

**Comment by captainbarbosa** [comment]
This will be fixed in a future project.
