### ISSUE TITLE
Aliased text

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#7599]
iOS, master @ 4d6c5b2d3b982c7836ea3bf32d5ee8d0c4c699f8:

![image](https://cloud.githubusercontent.com/assets/98601/21663173/4ec3ca7a-d293-11e6-9c41-5a1d150d42bb.png)

**Comment by jfirebaugh** [comment]
This bisects to 38b5cb0c7766152f7e49cce8bd6c5d3e04dd0663.

cc @ansis

**Comment by jfirebaugh** [comment]
I haven't been able to reproduce this in macosapp or the simulator. Only seems to happen on a device.

**Comment by anandthakker** [comment]
Regressed due to https://github.com/mapbox/mapbox-gl-native/commit/f901e776b3e63aaaa6bc0cc4476624bf84127fe6

**Comment by boundsj** [comment]
Closing as re-fixed in https://github.com/mapbox/mapbox-gl-native/pull/8423 that was merged into the `release-ios-v3.5.0-android-v5.0.0` release branch.

**Comment by anandthakker** [comment]
@boundsj should I open a new PR cherry picking the fix into master?  Or do
we already have a more general process for syncing the release branch back
to master?

**Comment by 1ec5** [comment]
We’ll merge the release branch back into master after either SDK is released. There are other changes that only went into the release branch that we’ll want to keep around. If you need the changes sooner, we can do an extra merge ahead of the releases.
