### ISSUE TITLE
CI build for ProGuard

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#7608]
When preparing for a new release, we tend to run into a few ProGuard issues that require fixing beforehand. If we add a task in our CI to test while ProGuard is enabled we can catch any issues quicker. Thoughts @mapbox/android?

**Comment by tobrun** [comment]
This is great idea as long as it doesn't impact us while developing locally. I'm suggesting to have `mimifyEnabled=true` for release builds. This requires some changes to our current make command since they be default build release (if I can remember correctly from https://github.com/mapbox/mapbox-gl-native/issues/3531).

**Comment by tobrun** [comment]
Something else that could possibly be an issue is the usage of reflection in our instrumentation tests.

**Comment by tobrun** [comment]
Confirming that we build by default the debug flavor for make commands, no extra actions needed there.

**Comment by tobrun** [comment]
Capturing from PR in #7656 that it will not be possible to run a release APK on firebase as the instrumentation runner uses the debug package which isn't configurable. One thing that possibly could work is if we enable proguard for debug builds but we need to find a way that this is enabled only on CI and not while developing locally.

**Comment by cammace** [comment]
Couldn't we create a build Variant specific for CI which enables proguard?

**Comment by tobrun** [comment]
@cammace good call, let me try that out

**Comment by tobrun** [comment]
Going to close, only way to test this would be manually with a daily build to google play beta.
