### ISSUE TITLE
Remove Object[] based filter methods

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#7617]
The following filter methods appear to be type-unsafe (#7555) and duplicative of the functionality of other runtime styling API methods:

* `*Layer::setFilter(Object[] filter)`
* `*Layer::withFilter(Object[] filter)`

If so, we should remove them.

cc @tobrun @ivovandongen

**Comment by tobrun** [comment]
Capturing from conversation with @ivovandongen that these are good to remove. 
Will probably be revisited when DDS is going to be added.
