### ISSUE TITLE
Configure iOS project such that manual adjustments of signing settings are not required

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#7620]
Running the iosapp requires adjusting the project settings in a way that generates changes that are prone to accidentally getting checked in, hinders switching between branches or bisecting, and is generally inconvenient. Let's find a way to make the checked-in project artifacts Just Work for day to day development by their primary developers.

cc @1ec5 @friedbunny

**Comment by 1ec5** [comment]
I’m able to build and run iosapp in both the simulator and on an iPhone using Xcode 8.2 without making any changes to the project file. I know I’ve run into the same issue as you in the past and ended up needing to set the development team build setting, but I’m not sure under what circumstances that occurs.

**Comment by 1ec5** [comment]
I’ve got three checkouts, one of master and two of release-ios-v3.4.0. The master checkout always reproduces this issue, while the two release-ios-v3.4.0 checkouts never do. I’ve tried opening one project at a time and all at the same time. I can’t find any relevant differences in ios.xcodeproj or ios.xcworkspace (taking gitignored and xcuserdata files into account).

**Comment by friedbunny** [comment]
Key points we discovered in trying to figure this out:

- Always be on the latest stable Xcode release.
- Make sure you’re a member of the relevant Apple developer accounts.

**Comment by jfirebaugh** [comment]
I'm now satisfying both of those points, but still having this issue.

**Comment by friedbunny** [comment]
...
