### ISSUE TITLE
Assertion failure when creating empty shape collection — -[MGLShapeCollection initWithShapes:]

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7628]
`-[MGLShapeCollection initWithShapes:]` [asserts](https://github.com/mapbox/mapbox-gl-native/blob/53eddafd3c374ebc80233ba9d10c5ec71a08e774/platform/darwin/src/MGLShapeCollection.mm#L15) if the shapes array is empty (or nil). According to [RFC 7946](https://tools.ietf.org/html/rfc7946#section-3.1.8), it’s valid for a `GeometryCollection` object to be empty, and geometry.hpp seems to allow empty geometry collections as well.

/cc @incanus @boundsj

**Comment by boundsj** [comment]
Fixed by https://github.com/mapbox/mapbox-gl-native/pull/7632
