### ISSUE TITLE
User interaction guide

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7635]
The iOS and macOS SDK generated docsets should include a guide listing the many gestures supported by MGLMapView and, in the case of macOS, the keyboard shortcuts as well. For example, a developer who wants to implement a tap gesture recognizer will need to know that there’s more than one tap gesture recognizer installed so they can disable any conflicting gesture recognizers (#7246).

/cc @incanus @friedbunny

**Comment by 1ec5** [comment]
The iOS gestures are being documented in #7937.

**Comment by jmkiley** [comment]
#7937 landed.
