### ISSUE TITLE
MBGLView::nativeView needs to have __weak attribute to resolve cyclic reference for ARC.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#764]
Data member nativeView in class MBGLView needs to be declared with __weak attribute so that ARC can correctly reclaim memory for MGLMapView. Without it memory for MGLMapView will never be reclaimed.

MGLMapView contains reference to  MBGLView.
MBGLView contains reference to MGLMapView

**Comment by incanus** [comment]
Thanks @mb12, I'll check this out.
