### ISSUE TITLE
Nightly builds failing with no space left

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#7640]
Both the [snapshot](https://www.bitrise.io/build/44159a74382dbb1d)  as [metrics build](https://www.bitrise.io/build/d8f9581ecd27f2ef) are failing with:

```
Error: No space left on device
```

cc @mapbox/android

**Comment by zugaldia** [comment]
I just did a local fresh build and we're taking 1.7G:

```
$ du -s -h
1.7G	.
```

Is that over the CI limit? Have you noticed an increase recently?

**Comment by tobrun** [comment]
This is what we can expect from bitrise:

>We're still experimenting with new VM providers and VM configurations, but in general, what you can expect:
at least 7.5GB RAM
at least 2 CPU cores
64 bit CPU
at least 10GB free disk space

**Comment by tobrun** [comment]
Capturing from chat that `make apackage` target used during publishing results in 6.7G.

**Comment by tobrun** [comment]
Contacted bitrise on the subject and it seems that the partition we are working on has 6.4GB free space even though the docker image itself has 60GB free. I need to look into moving CI building from `/bitrise` to `/temp`. Bitrise has noted to look into increasing the partition size to resemble the 10GB mentioned above.

**Comment by tobrun** [comment]
Bitrise got back to me with an eta on the issue, they are deploying new stacks on Saturday that will increase the current 6.4GB size (we need 6.7GB). We are opting to not workaround the issue and wait untill Saturday for having new SNAPSHOTS. Will close on Saturday if issue is resolved.

**Comment by tobrun** [comment]
Bitrise has updated the stack on Saturday, builds are running successful again 👍 , closing
