### ISSUE TITLE
Question about localFileSource platform suport

### ISSUE THREAD

**Issue by briancalvium** [mapbox/mapbox-gl-native#7644]
I thought I would try asking about this here before taking the time to fork react-native-mapbox-gl to include the change...

Is it possible on both iOS and android to load files (`style.json` and the tiles themselves) from the App documents directory using the recently added `localFileSource`? We have apps with custom raster map tiles that we currently have to include with the app and access using the `assets://` protocol. It would be great to be able to download them on first launch and use `file://`. 

Thanks, any pointers in the right direction would be appreciated!

**Comment by kkaefer** [comment]
This should work if you use `file://` as the URL. Note that you'll need to use absolute paths, which means you'll typically end up with URLs that start with `file:///var/mobile/...` (note the 3 slashes).

**Comment by 1ec5** [comment]
As @kkaefer notes, you can use an absolute file: URL to access a file in the documents directory. However, it sounds like you may find it more convenient to use the offline maps API (`OfflineRegion` on Android, MGLOfflineStorage on iOS) to download the styles and tiles directly into the SDK. RNMBGL has rudimentary support for the Android and iOS SDKs’ offline maps APIs.

**Comment by briancalvium** [comment]
Thanks for the help @1ec5 and @kkaefer! Just as reference for anyone else: currently react-native-mapbox-gl would need to be forked to build against mapbox-gl-native >= 3.4. There is a pre-build script specified in package.json that downloads the compiled native library for iOS (currently set to 3.3.1). Not sure yet whether RNMBGL would build against that without further changes.

**Comment by SeanChristopherConway** [comment]
@kkaefer This is working for me on Android but not on iOS. On iOS, for example, this does not work in my JSON style file(have confirmed the folders exist):

```
  "tiles": [
              "file:///Users/Sean/Library/Developer/CoreSimulator/Devices/FBBFDD4B-82EB-46FF-ADF2-A0D0747C66BB/data/Containers/Data/Application/C7B169EB-DC3A-47C8-85FB-1347E13A517D/Documents/221_7/{z}/{x}/{y}.pbf"
          ]
```

**Comment by 1ec5** [comment]
Your application is sandboxed, so it has no access to your home directory. Within the sandbox, the root directory `/` is mapped to a physical directory somewhere within that device folder. You need to figure out the path as your application, running in the simulator, sees it. See “[Locating Items in the Standard Directories](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/AccessingFilesandDirectories/AccessingFilesandDirectories.html#//apple_ref/doc/uid/TP40010672-CH3-SW3)” for more information. Hopefully either React Native or a third-party component exposes these file system APIs for your application’s use.

**Comment by 1ec5** [comment]
Without knowing exactly what you’re trying to do, I think the offline map API would probably be a better way to do it. 😄 (Unfortunately, RNMBGL doesn’t do a great job of exposing this API to React Native on iOS.) If you really do need to manage tile downloads yourself, rather than relying on the offline map API to download the tiles as part of the style, then eventually https://github.com/mapbox/mapbox-gl-native/issues/7471#issuecomment-268722312 in conjunction with the runtime styling API (mapbox/react-native-mapbox-gl#416) would make it possible for you to specify these on-disk tiles without having to modify a JSON file.

**Comment by AEiosApp** [comment]
@SeanChristopherConway 
Have you managed finally, how to use tiles from documents directory?

**Comment by mflint** [comment]
Team, I'm also trying to custom load vector tiles from my application bundle, but with no success.

This is in my source definition:
```
"tiles": ["/var/containers/Bundle/Application/{guid}/MyApp.app/MapData.bundle/{z}-{x}-{y}.pbf"],
"type": "vector"
```

The files exist at that path.

I've tried:
* absolute paths (`/var/containers...`)
* file URL scheme (`file:///var/containers...`)
* asset URL scheme (`asset:///var/containers...`) - I can't find _any_ documentation about that URL scheme

None of these seem to work, and there's no output in the console to give any hints about why tiles aren't loading. I know that my `style.json` is being read correctly.

Does anyone - please - have working example for iOS?

(My backup plan is to embed a small web server in the app, which is a _terrible_ idea...)
