### ISSUE TITLE
clear_xcode_cache in makefile causes error on Linux

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#766]
When I run `make clean` on Linux I get these errors:
```
/bin/sh: 2: [[: not found
/bin/sh: 6: [[: not found
/bin/sh: 10: [[: not found
```
Seems to be caused by `clear_xcode_cache` target. Probably shouldn't be running on Linux anyway.

**Comment by mikemorris** [comment]
Fixed this in the `boringssl` branch, cherry pick https://github.com/mapbox/mapbox-gl-native/commit/8d82f0bdb04615e273f38d12156f7cfd8bae229a into `master` or just wait for the merge.

**Comment by ljbade** [comment]
I might cherry pick.

**Comment by mikemorris** [comment]
Merged it into `master` already with the `clear_sqlite_cache` fix @ljbade
