### ISSUE TITLE
Add autocompleting search bar to jazzy theme

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#7673]
Local search has landed in jazzy (https://github.com/realm/jazzy/pull/725). To support it, we’ll need to update our theme to include the new UI elements and JS dependencies.

/cc @mayagao @captainbarbosa

**Comment by 1ec5** [comment]
The search bar feature is described in [this blog post](https://pspdfkit.com/blog/2016/adding-live-search-to-jazzy/) by its original implementer.

**Comment by friedbunny** [comment]
Pushed this to v3.4.1, but if @mayagao has the bandwidth to land it in the next day or two then it could still make v3.4.0.

**Comment by mayagao** [comment]
woah I will do this tomorrow 😳

**Comment by friedbunny** [comment]
The [v3.5.0 docs on our website](https://www.mapbox.com/ios-sdk/api/3.5.0/) have been updated to use search, via a theme specific to that site. Those changes will be ported here to gl-native, but local search may be broken on some browsers due to CORS.
