### ISSUE TITLE
build source code

### ISSUE THREAD

**Issue by yangxuanlun** [mapbox/mapbox-gl-native#7695]
**Platform:IOS**
**Mapbox SDK version:**

### Steps to trigger behavior

 1.install all dependencies
 2. run  ### make iproj 
I run "make iproj" in the terminal,and the terminal display as the "Actual behavior", and  after two hours ,there is nothing happened anymore,what should I do? Is there anything wrong?

### Expected behavior
build success
### Actual behavior

zx-yxldeMac-mini:mapbox-gl-native zx-yxl$ make iproj
mkdir -p build/ios
(cd build/ios && cmake -G Xcode ../.. \
		-DCMAKE_TOOLCHAIN_FILE=../../platform/ios/toolchain.cmake \
		-DMBGL_PLATFORM=ios)
-- Found NodeJS: node.js darwin/x64 (found version "5.10.0") 
ln: node_modules/node_modules: File exists
npm WARN deprecated feature-filter@2.2.0: This package has been merged into the 'mapbox-gl-style-spec' package
npm WARN deprecated geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead

**Comment by kkaefer** [comment]
`make iproj` generates the iOS projects and opens Xcode. You will need to continue the build process in Xcode. Please follow the guide in https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md

If you just want to use Mapbox GL in your app, you don't need to compile it yourself (and you don't need to check out this repository). Instead, please follow the guide at https://www.mapbox.com/ios-sdk/
