### ISSUE TITLE
App uses location in the background

### ISSUE THREAD

**Issue by wibge** [mapbox/mapbox-gl-native#7718]
**Platform:** ios
**Mapbox SDK version:** 3.4.0

### Steps to trigger behavior

 1. Add Mapbox to an app has location services permission to 'always'
 2. background the app

### Expected behavior
The arrow in the top bar would disappear, and the app would stop using location services when backgrounded. 

### Actual behavior
The location services arrow is always on. 

We have the 'always' permission because we allow recording tracks in the background, but our users expect us to not use GPS in the background if they are not currently recording. This is also a large battery drain for backcountry use.

**Comment by nitrag** [comment]
@wibge See https://github.com/mapbox/mapbox-gl-native/issues/7369. 

Are you sure there is battery drain though? I haven't been able to confirm this.

> but our users expect us to not use GPS in the background if they are not currently recording. This is also a large battery drain for backcountry use.

I agree 100%.

**Comment by wibge** [comment]
You're right, I looked at the implementation, and it uses location services very conservatively, and I don't think it will affect the battery much.  But it will be confusing for our users, and I think reflect poorly on our app.

**Comment by nitrag** [comment]
Yes, I cringe every time I see the "Your app has been using your location in the background" message. Potentially since Google Maps and Waze shows those too I can hope that users are desensitized? Doubt it though. It's going to be difficult to educate them on the matter. I'm in a similar boat as you and users are going to be extra paranoid about this.

**Comment by boundsj** [comment]
Closing in favor of https://github.com/mapbox/mapbox-gl-native/issues/7831 that was addressed by https://github.com/mapbox/mapbox-gl-native/pull/7833.
