### ISSUE TITLE
Timeout Offline Pack Download

### ISSUE THREAD

**Issue by nitrag** [mapbox/mapbox-gl-native#7726]
While testing a "Simulated 3G" internet connection on my device and downloading offline packs I get timeouts (`The request timed out.`) so frequently, I'm not even sure anything is being downloaded...

Thoughts? Does each "resource" get re-tried on a timeout? Am I going to have to restrict downloads to WiFi-only?

```
func offlinePackDidReceiveError(notification: NSNotification) {
        if let pack = notification.object as? MGLOfflinePack,
            let userInfo = NSKeyedUnarchiver.unarchiveObject(with: pack.context) as? [String: String],
            let error = notification.userInfo?[MGLOfflinePackErrorUserInfoKey] as? NSError {
            print("Offline pack “\(userInfo["name"])” received error: \(error.localizedFailureReason)")
        }
    }
```

**Platform:** iOS
**Mapbox SDK version:** 3.4.0-beta6

**Comment by jfirebaugh** [comment]
> Does each "resource" get re-tried on a timeout?

Yes, network timeouts in an offline download will be retried, with an exponential backoff algorithm.

> Am I going to have to restrict downloads to WiFi-only?

You certainly do have that option. It may make sense depending on the size of the offline region and expected cellular bandwidth.
