### ISSUE TITLE
Could you provide node binaries for node 6

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-native#7727]
Currently only provide node 4 binaries. As node 6 has became lts for a period, could you consider provide node 6 binaries?

**Comment by jfirebaugh** [comment]
We're trying to keep our CI matrix as small as possible due to Travis CI load constraints, so for the time being node 4 will be the only version for which we provide binaries.

**Comment by jingsam** [comment]
Travis says:
>All build matrixes are currently limited to a maximum of 200 JOBS for both private and public repositories. If you are on an open-source plan, please remember that Travis CI provides this service free of charge to the community. So please only specify the matrix you actually need.

So the maximum jobs of travis ci is 200, and mapbox-gl-native only has 7 jobs. To be frankly, I really like node 6 because of many new features such as destructive assignment、integrated node inspect. Using npm 2 is painful and I don't like yarn. All mapbox maintained node binaries such as fontnik, mapnik, gdal, osrm, sqlite3, zipfile have provide node 6 binaries except mapbox-gl-native.

So would you reconsider to add support for node 6, please! many thanks.

**Comment by jfirebaugh** [comment]
"200 maximum jobs" isn't meaningful because we are limited to 10 _concurrent_ jobs at a time, across _all_ the projects Mapbox uses Travis for (several hundred). Adding more rows to the build matrix means we are waiting longer to see the results for any commit.

**Comment by bsudekum** [comment]
Node v4 will be entering maintenance mode in April. I think it's now time to start thinking about, testing and building binaries for node v6.

ref https://github.com/nodejs/LTS

**Comment by bsudekum** [comment]
We're now testing node v6 https://github.com/mapbox/mapbox-gl-native/pull/8884. Will close this once we publish node v6 binaries.
