### ISSUE TITLE
[Android] Gesture on a Mapbox map with View Marker is interrupted

### ISSUE THREAD

**Issue by xam0n** [mapbox/mapbox-gl-native#7735]
Hello, I'm trying to insert Mapbox view into ListView header:
```
View mapHeader = inflater.inflate(R.layout.expanded_map_header, null);
listView.addHeaderView(mapHeader);
```

Then I added View Marker using MarkerViewOptions() on map:
```
mapboxMap.addMarker(new MarkerViewOptions()
                        .position(location));
```

Action:
Move map by swipe to hide this marker behind the map border (or vice versa to move marker into shown area).
Result: gesture is interrupted at the moment when the marker disappears (or appears) and I cannot move map until I repeat gesture again.

Platform: Android
Mapbox SDK version: 4.2.1

**Comment by Guardiola31337** [comment]
Hey 👋 @xam0n 
First of all, thanks for reaching out and report your problem.

Do you still experience this issue? Could you retest with latest version `5.1.0-beta.4`?

**Comment by tobrun** [comment]
Showing a MapView in a ListView doesn't fall under the supported use-cases. 
For that use-case we advice using the static api as images give a better UX.
