### ISSUE TITLE
[ios] Using file:// or asset:// to load locally stored tiles in a {style}.json file

### ISSUE THREAD

**Issue by SeanChristopherConway** [mapbox/mapbox-gl-native#7744]
Using the most recent build of android I am able to use file urls within my style JSON file to load locally stored tiles, eg.  
```
 "sources": {
        "mapbox": {
          "type": "vector",
          "tiles": [
              "file://{path}/{z}/{x}/{y}.pbf"
          ],
          "minzoom": 0,
          "maxzoom": 20
        }
    }
```

Using the most recent iOS build I can use asset:// but not file://, eg.

```
      "tiles": [
              "file:///Users/Sean/Library/Developer/CoreSimulator/Devices/FBBFDD4B-82EB-46FF-ADF2-A0D0747C66BB/data/Containers/Data/Application/C7B169EB-DC3A-47C8-85FB-1347E13A517D/Documents/221_7/{z}/{x}/{y}.pbf"
          ]
```

**Comment by 1ec5** [comment]
This is expected behavior for a sandboxed application. See https://github.com/mapbox/mapbox-gl-native/issues/7644#issuecomment-273038578 for the correct way to refer to a local file.

**Comment by jeeftor** [comment]
I'm kind of guessing you may need to write out your `style.json` file on the fly - taking into account the actual installed path.  Of course I could be wrong :)

**Comment by 1ec5** [comment]
No need to write out the file on the fly. Per https://github.com/mapbox/mapbox-gl-native/issues/7644#issuecomment-273038578:

> Your application is sandboxed, so it has no access to your home directory on your Mac. Within the sandbox, the root directory `/` is mapped to a physical directory somewhere within that device folder. You need to figure out the path as your application, running in the simulator, sees it. See “[Locating Items in the Standard Directories](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/AccessingFilesandDirectories/AccessingFilesandDirectories.html#//apple_ref/doc/uid/TP40010672-CH3-SW3)” for more information.
