### ISSUE TITLE
Flickering with translucent raster style layer

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-gl-native#7760]
If you add a translucent raster layer, tiles are double rendered during tile loading. For example if you add a layer with 50% opacity, there are moments of flickering where the layer renders out at 100% opacity.

![translucent raster 2](https://cloud.githubusercontent.com/assets/664805/22043649/74f82ef2-dcc5-11e6-9256-544d2d619ec8.gif)

 1. Add a raster layer with a semi-opaque opacity value (e.g. 50%):
```objective-c
NSURL *rasterURL = [NSURL URLWithString:@"mapbox://mapbox.satellite"];
MGLRasterSource *rasterSource = [[MGLRasterSource alloc] initWithIdentifier:@"my-raster-source" configurationURL:rasterURL tileSize:512];
[self.mapView.style addSource:rasterSource];
    
MGLRasterStyleLayer *rasterLayer = [[MGLRasterStyleLayer alloc] initWithIdentifier:@"my-raster-layer" source:rasterSource];
rasterLayer.rasterOpacity = [MGLStyleValue valueWithRawValue:@0.5];
[self.mapView.style addLayer:rasterLayer];
```
 2. Pan around in areas where tiles haven't been loaded

**Comment by kkaefer** [comment]
Fixed by #9468.
