### ISSUE TITLE
[Android] Fling gesture has wildly different physics than Google Maps

### ISSUE THREAD

**Issue by petedoyle** [mapbox/mapbox-gl-native#7761]
**Platform:**
Android 7.1.1 / Nexus 6P

**Mapbox SDK version:**
Mapbox Dev Preview app, version 4.2.1 (per the Google Play store app "Read More" section)

### Steps to trigger behavior
 1. Do a small, short fling (~1/4 - 1/2 inch on screen)
 2. Compare scrolling physics vs Google maps

### Expected behavior
- Scrolling behavior should feel somewhat "normal" for Android (effectively, similar to Google Maps)

### Actual behavior
- Short flings result in much too long of a scroll (feels *really* weird. One of those bugs your brain gets used to after a bit, so it may not feel weird to you guys. But to me, on my first try, it took about 1/4 sec for my brain flip out as not "feeling" normal.)

Video / Comparison with Google Maps (is more apparent if you watch it scaled to about the size of a phone):
http://s3.amazonaws.com/doylemedia.com/temp/github/mapbox-gl-native/2017-01-17-Mapbox4.2.1vsGoogleMaps-Android-ShortFling.mp4

**Comment by tobrun** [comment]
Since the 4.2.1 release we have made 2 improvements here:
 - #7675
 - https://github.com/mapbox/mapbox-gl-native/pull/7676

Feel free to test this out with the 5.0.0-SNAPSHOT and provide feedback.
Closing for now.
