### ISSUE TITLE
[Android] Double-tap+drag-to-zoom physics are less than ideal

### ISSUE THREAD

**Issue by petedoyle** [mapbox/mapbox-gl-native#7762]
**Platform:**
Android 7.1.1 / Nexus 6P

**Mapbox SDK version:**
Mapbox Dev Preview app, version 4.2.1 (per the Google Play store app "Read More" section)

### Steps to trigger behavior
 1. Double tap, hold, then drag up or down to zoom in or out.
 2. Without releasing, drag up and down a few times to repeat

### Expected behavior
- Physics should feel platform-native (probably similar to Google Maps)
- Zoom should be repeatable as you drag your finger up and down
- Zoom should zoom linearly (I think, not 100% sure) with distance dragged up/down

### Actual behavior
- Zoom is much more sensitive than expected
- Once you pass the starting point (e.g. start at 0, drag down to N, drag up past 0), zoom flips out (see video)
- Zoom seems to speed up drastically (not linearly) as the distance from the initial double-tap location increases (this might be normal, just felt more extreme than Google Maps) (may just be the previous bullet above getting triggered)

Video / Comparison with Google Maps (is more apparent if you watch it scaled to about the size of a phone):
http://s3.amazonaws.com/doylemedia.com/temp/github/mapbox-gl-native/2017-01-17-Mapbox4.2.1vsGoogleMaps-Android-DoubleTapZoom.mp4

**Comment by tobrun** [comment]
@petedoyle thanks for reaching out, we recently changed this behaviour in https://github.com/mapbox/mapbox-gl-native/pull/7580. You can test this out using the 5.0.0-SNAPSHOT. Closing as this is already been handled/
