### ISSUE TITLE
Node map.render is off by one zoomlevel compared to static map API

### ISSUE THREAD

**Issue by felixLam** [mapbox/mapbox-gl-native#7768]
**Platform: Node**
**Mapbox SDK version: 3.4.4**

### Steps to trigger behavior

 1. Render a map using `map.render`:
```js
map.render({
        zoom: 9,
        width: 200,
        height: 200,
        center: [-122.4313, 37.7571],
        bearing: 0, 
        pitch: 0,
    }
```
 2. Compare the result against the image returned from the map box static map url service.
 3. Find that the region displayed do not align

This is a problem as it does not allows us to overlay the static map with markers using the same projection as we would using the static map url service. Furthermore it does not allow us to precisely choose the zoom level AND region that we expect to see in the rendering.

Using the same rendering configuration with one zoom level lower (in the example that would be 8) aligns the two outputs.

### Expected behavior

The expected image should be identical in the covered area to the one returned from the static map API:

![](https://api.mapbox.com/v4/examples.map-zr0njcqy/-122.4313,37.7571,9/200x200.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpbG10dnA3NzY3OTZ0dmtwejN2ZnUycjYifQ.1W5oTOnWXQ9R1w8u3Oo1yA)

### Actual behavior

![render](https://cloud.githubusercontent.com/assets/1178566/22071038/35eda276-dd9e-11e6-88e2-8fbfb9295ac1.png)

**Comment by jfirebaugh** [comment]
This is the expected behavior -- Mapbox GL uses size 512px tiles, so for instance the world at zoom level 0 is rendered in 512px instead of 256px. For more information about the reasons for this and techniques for interoperating with 256px tiles, see [this blog post](https://www.mapbox.com/blog/512px-map-tile/).

**Comment by felixLam** [comment]
@jfirebaugh Thanks for the fast response, you have helped me a lot. I must have missed this. 

It might be a nice opportunity to improve the documentation of the static maps url api though, to inform users that the area covered will be based on 256pt tiles as opposed to 512pt used elsewhere. I could also not find any documentation on the `render` function. Is this forthcoming or did I miss it?
