### ISSUE TITLE
onMapReady(..) is not called when app is offline and style url is not set when getMapAsync(..) is called

### ISSUE THREAD

**Issue by snowpong** [mapbox/mapbox-gl-native#7783]
**Platform:** Android
**Mapbox SDK version:** 4.2.1

### Steps to trigger behavior

 1. Offline a region with a non-default style
 2. Go offline
 3. Show map with the same non-default style

### Expected behavior

I get the map rendered

### Actual behavior

I get a black map and onMapReady(..) is never called

I narrowed it down to the following:

- onMapReady(..) is only called once a style is loaded
- if no style is set by the developer when getMapAsync(..) is called, it will fallback to the default style
- as we have offlined the region with our non-default style, the fallback will never work
- calling setStyleUrl(...) before onCreate(..) or getMapAsync(..) don't seem to be a good fix, most likely because setStyleUrl is async AFAIK
- setting the style_url in XML layout fixes the issue

See my fix for my app here https://github.com/Turistforeningen/SjekkUT/commit/e0afe15fb08ab7351a2871e8bb5427807be8f9bf

**Comment by tobrun** [comment]
> onMapReady(..) is only called once a style is loaded

This is correct and is a work as designed.

> if no style is set by the developer when getMapAsync(..) is called, it will fallback to the default style

If no style has been set by the time you call `MapView#onResume`, it will load the default style

> as we have offlined the region with our non-default style, the fallback will never work

Just set your style before onResume and the offline region should load

> calling setStyleUrl(...) before onCreate(..) or getMapAsync(..) don't seem to be a good fix, most likely because setStyleUrl is async AFAIK

The download of the style is asynchronous but setting the style url isn't. 

> setting the style_url in XML layout fixes the issue

It's advised to initialize your style as soon as possible, either in xml or just after inflating MapView. 

@snowpong I'm not seeing any actionable bugs in this report, we are aware that the system could be made more robust as you could be running in situations with unexpected behavior. We will definitely take the feedback above into account when refactoring this feature in the future but not seeing any actions for now. Thank you for reaching out and feel free to do again with any comments or questions!

**Comment by snowpong** [comment]
@tobrun Thanks for clarifying. It took me forever to debug the issue. If there is a way to inform the developer either in log output or in the docs that might be a good idea.

Actually, the docs for setStyleUrl says: "If the style fails to load or an invalid style URL is set, the map view will become blank. An error message will be logged in the Android logcat and DID_FAIL_LOADING_MAP event will be sent." but I don't seem to have gotten a DID_FAIL_LOADING_MAP in this case. See my log output here https://github.com/mapbox/mapbox-gl-native/issues/7045#issuecomment-273493441

Might be worth looking into.

**Comment by tobrun** [comment]
@snowpong it seems that we need to update the documentation as this behaviour has changed since we introduced automatic loading of Mapbox Streets if no style was provided. Will takes this account with upcoming refactors! thanks you for taking time to write up this issue and providing feedback!
