### ISSUE TITLE
redraw continuously long enough for dash transitions to finish

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#779]
Dashed lines sometimes get stuck in the middle of a transition. It should repaint long enough for the transition to finish. I think this might also be a problem with labels fading in.

from @ljbade:
![screen shot 2015-01-26 at 6 28 26 pm](https://cloud.githubusercontent.com/assets/1421652/5912458/2acd7136-a589-11e4-9924-b251bc985c82.png)

**Comment by ljbade** [comment]
Adding to the list that faded labels also need to redraw long enough.

**Comment by brunoabinader** [comment]
#1548 should fix this.
