### ISSUE TITLE
Calling MapboxMap.setMyLocationEnabled(true) doesn't show immidatelly

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#7796]
when calling MapboxMap.setMyLocationEnabled(true), the MyLocationView is is only shown when we start we receiving our first GPS update. We should be able to use the last known location to initialize the MyLocationView and afterwards update it with the values coming from the LocationListener.

**Comment by zugaldia** [comment]
Fixed via https://github.com/mapbox/mapbox-gl-native/pull/7892.
