### ISSUE TITLE
Cannot animate MarkerView rotation

### ISSUE THREAD

**Issue by zakgof** [mapbox/mapbox-gl-native#7798]
Observed in mapbox-android-sdk 4.2.1

I'm trying to animate a MarkerView rotation.
Using the example code from https://www.mapbox.com/android-sdk/examples/animated-marker/
with "position" animation replaced by "rotation" animation in onMapClick:

```
   ValueAnimator markerAnimator = ObjectAnimator.ofObject(marker, "rotation", new FloatEvaluator(), -90, 90);
   markerAnimator.setDuration(5000);
   markerAnimator.start();
```

### Expected behavior
Marker rotates slowly from -90 to 90
### Actual behavior
Nothing happens for 5 sec, then marker rotates quickly to the end angle (90)

My suggestion is that internal animation implemented in MarkerView.setRotation does not work correctly when rotation is set every frame by the external animation.
There is a workaround: get a View and apply animation directly to that View.

**Comment by tobrun** [comment]
Thanks you for the report, the current implementation already use an animator so no need to use an additional animator. The proposed change makes sense and I have PR'ed them in #7907.

**Comment by nijs9** [comment]
zakgof suggest to use 'a View and apply animation directly to that View'. Is there an example available please?

**Comment by tobrun** [comment]
No specific example but this code should get you going:

```java
    MarkerView markerView = null;
    View view = mapboxMap.getMarkerViewManager().getView(markerView);
    if (view != null) {
      view.animate();
    }
```

**Comment by nijs9** [comment]
Thank you tobrun!
