### ISSUE TITLE
Dashed lines are broken on Android

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#780]
Dashed lines do not have dashes and are transparent.
![device-2015-01-27-115109](https://cloud.githubusercontent.com/assets/1215089/5912504/405731b8-a629-11e4-8bcb-027a704166ab.png)

Happened after the changes to dashed lines @ansis made.

I think this may be a desktop GL vs GLES issue.

@incanus Can you check what the lines look like on iOS since that is GLES too.

**Comment by incanus** [comment]
I can check this out once we un-block https://github.com/mapbox/mapbox-gl-native/issues/782. 

LOL love the nav buttons @ljbade! :european_castle:

**Comment by ljbade** [comment]
![device-2015-01-30-111307](https://cloud.githubusercontent.com/assets/1215089/5968984/4f46cbd4-a872-11e4-9f49-7b51da634a5a.png)

It seems the dashed lines are now working, but transparent lines are wrong.

Not sure why it started working except that I did update to latest v7 styles.

**Comment by ljbade** [comment]
@nickidlugash says she changed this recently:
https://github.com/mapbox/mapbox-gl-styles/commit/54a65d03e906ce516db1150e1a532c6a51796376

Might be clue to what the bug is.

**Comment by ljbade** [comment]
No longer an issue
