### ISSUE TITLE
Offscreen InfoWindow not anchored correctly 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#7809]
### Expected behavior
![device-2017-01-22-122717](https://cloud.githubusercontent.com/assets/2151639/22182150/34425a5e-e09e-11e6-8054-f76b0fbe08f9.png)

### Actual behavior
![device-2017-01-22-122642](https://cloud.githubusercontent.com/assets/2151639/22182149/31c97aaa-e09e-11e6-9239-9ac6390ecf94.png)

**Comment by tobrun** [comment]
The source of this issue seems to be #6999

**Comment by austinoneil** [comment]
What branch is this on?

**Comment by tobrun** [comment]
Fixed with https://github.com/mapbox/mapbox-gl-native/issues/6999
cc @Guardiola31337
