### ISSUE TITLE
Large Memory leaks in Map start/stop logic (App terminated due to memory pressure).

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#781]
This consistently reproduces on iPhone 4S. Here are the steps to reproduce the issue.

1. Launch sample iosapp. (Memory footprint is around 21MB).
2. Douple press the home button and switch to any other app.
3. Double press again and switch back to sample app. (Footprint goes to 25MB).

Every  time one switches back to the glclient, memory footprint goes by 4MB. Most of the leaks are in  HTTP request logic. I can also provide an instrumentation trace showing the leaks. Its around 121M. Please let me know where I should copy it if you need it.  The leaks are very consistently reproducible.

**Comment by kkaefer** [comment]
Yeah, there are all sorts of memory leak in the app. Please bear with us while we continue to improve Mapbox GL native.

**Comment by mb12** [comment]
This is most likely a regression. I profiled this because on an iPhone 4S, OS was consistently terminating the app when switching between apps with the message "App terminated due to memory pressure".
I never ran into this issue with an older version (the one which does not have CachingHttpFileSource/HttpRequestBaton changes).

**Comment by jfirebaugh** [comment]
This is likely fixed by #1065.
