### ISSUE TITLE
iOS: Map Canvas Auto-Resizing Issues

### ISSUE THREAD

**Issue by lagst3r** [mapbox/mapbox-gl-native#7814]
UI objects in the view seems to be affecting the map canvas causing it to resize by itself.
(I've unchecked Auto Layout in storyboard, I didn't face this issue in all previous versions)

![simulator screen shot 24 jan 2017 12 19 57 am](https://cloud.githubusercontent.com/assets/23474104/22212383/77bc9208-e1cb-11e6-9ba8-b489eb61c977.png)

**Comment by friedbunny** [comment]
Thanks for the report. Before we can begin triaging this issue, we’ll need more information — please follow the guidelines [in the issue template](https://raw.githubusercontent.com/mapbox/mapbox-gl-native/master/ISSUE_TEMPLATE.md).

**Comment by lagst3r** [comment]
I found the issue in my project that caused it and fixed it. Previously in order to shift the compass position on the screen, I had to change compassView.superview's frame in the older versions of iOS MapBox SDK. 

Now in v3.4.0 to shift the compass, I simply shift the compassView.

Sorry for the troubles.

**Comment by friedbunny** [comment]
@lagst3r Cool, glad to hear you were able to resolve the issue. 👍
