### ISSUE TITLE
Document that clustering requires GeoJSON sources

### ISSUE THREAD

**Issue by jmkiley** [mapbox/mapbox-gl-native#7821]
The [documentation](https://www.mapbox.com/ios-sdk/api/3.4.0/Other%20Constants.html#/c:@MGLShapeSourceOptionClustered) for `MGLShapeSourceOptionClustered` does not mention that you currently can only cluster shapes with a GeoJSON source. This may be confusing for users who want to cluster point annotations ([#5814](https://github.com/mapbox/mapbox-gl-native/issues/5814)), for example. 

/cc @1ec5 @friedbunny

**Comment by 1ec5** [comment]
#7821 is adding this documentation.

**Comment by friedbunny** [comment]
Fixed in #7837.

**Comment by nitrag** [comment]
Why is clustering only available in `MGLShapeSource` and not `MGLVectorSource`? Is there some limitation?

**Comment by 1ec5** [comment]
@nitrag, great question. According to @mourner, it has to do with the fact that the clustering algorithm needs all the data to be loaded, whereas with vector sources, tiles come in asynchronously. Please open a separate issue to request this feature. Be sure to explain your use case so we can discuss the best way to support it.

**Comment by jbarros35** [comment]
I wanted to do that dynamically. Using geoJSON files it's just stupid.

**Comment by michzio** [comment]
No it works for me with MGLPointFeature 
I am doing MGLPointAnnotation to MGLPointFeature simple conversion 
```
 let features = Array(mapPoints.values).map { $0.pointFeature }
        let source = MGLShapeSource(identifier: "clusteredRestaurantsSource",
                                    //url: url,
                                    features: features,
                                    //shapes: Array(mapPoints.values),
                                    options: [.clustered : true,
                                              .clusterRadius : icon.size.width,
                                              .maximumZoomLevelForClustering: 16])
```

**Comment by vikihleblya** [comment]
@michzio please, can you say what type is mapPoints in your code? Do you request your points once or you do it periodically? My problem is that I request all my points for some area on screen and when I drag to other location, I request points again. That's why I can't fully understand at which sequence I need to code.
