### ISSUE TITLE
iOS: Region monitoring is not disabled when telemetry is disabled

### ISSUE THREAD

**Issue by JesseCrocker** [mapbox/mapbox-gl-native#7831]
**Platform: iOS**
**Mapbox SDK version: 3.4.0rc1**

### Steps to trigger behavior

 1. Launch iOS app
 2. Press locate button
 3. Authorize always location access
 4. Disable telemetry from menu
 5. Press home button to background app

### Expected behavior
After approximately 15 seconds the location services indicator in the status bar will turn off.

### Actual behavior
The location services indicator continues to show geofencing mode. It's an outline instead of a filled arrow.

**Comment by lm2s** [comment]
As a workaround for this issue while 3.5.0 isn't release.

```
let locationManager = CLLocationManager()
let regions = locationManager.monitoredRegions
for region in regions {
    if region.identifier == "MGLLocationManagerRegionIdentifier.fence.center" {
        locationManager.stopMonitoring(for: region)
    }
}
```

My suggestion is to implement this code in `applicationDidEnterBackground(_ application: UIApplication)`

**Comment by boundsj** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/7833 on the master branch.
