### ISSUE TITLE
MoveCamera, EaseCamera, and Update are not working using LatLngBounds.Builder on 4.2.1

### ISSUE THREAD

**Issue by dazza5000** [mapbox/mapbox-gl-native#7832]
I'm trying to update the map position using a LatLngBounds.Builder on Android, but the position of the map is not changed. When I use a CancellableCallback I can tell that in the callback that the onCancel is being called when I touch the map.

The animate/update duration is 1 ms which I think should make the animation instantaneous.

**Platform:** Android
**Mapbox SDK version:** 4.2.1

### Steps to trigger behavior

 1. Create a bounds builder and add points to it using: boundsBuilder.include(LatLng);
 2. Call update on the mapboxMap using any of the methods mentioned in the title 
 3. 

CameraUpdate currentCameraUpdate = newLatLngBounds(boundsBuilder.build(), 777);

mapboxMap.easeCamera(currentCameraUpdate, 7, new MapboxCameraAnimationListener());

    private class MapboxCameraAnimationListener implements MapboxMap.CancelableCallback {

        public MapboxCameraAnimationListener() {
            Log.d(TAG, "Animating camera position.");
            mMapAnimating = true;
        }

        @Override
        public void onCancel() {
            Log.d(TAG, "Animating camera position was cancelled.");
        }

        @Override
        public void onFinish() {
            Log.d(TAG, "Animating camera position was finished.");
            mMapAnimating = false;
        }
    }

### Expected behavior

The map is positioned to show the included points.

### Actual behavior

The map maintains the original position before the update was issued. The moment the user touches the map the onCancel method of the AnimationListener is called.

**Comment by dazza5000** [comment]
This is not detailed enough to find the root cause. Apologies. Will update when I get closer to what this is.

**Comment by dazza5000** [comment]
What's weird is when I step the padding down to 100 or 300 the update works, but at 777 it does nothing.

**Comment by tobrun** [comment]
The implementation details related to this method in OP have been revisited with 5.1.0 in #4796. Closing, feel free to reach out if this is still an issue.
