### ISSUE TITLE
Change to std::chrono::duration for all time use

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#784]
We need to convert all our use of `double nanoseconds` and `uint16_t milliseconds` to `std::chrono::duration` to avoid bugs and provide consistency.

One example is `setDefaultTransitionDuration` which takes `uint64_t milliseconds` which is coerced into a `uint16_t milliseconds` and inconsistent with all the other functions that use `double nanoseconds`.

At the same time need to implement https://github.com/mapbox/mapbox-gl-native/issues/783 for Android.

**Comment by springmeyer** [comment]
:+1:  on using `std::chrono`

**Comment by jfirebaugh** [comment]
Looks like `std::chrono::duration` is a template, and the actual concrete duration type we'd want to standardize on is `std::chrono::milliseconds`. (I'm not sure why we started using double precision nanoseconds in many places; that seems way overkill for our particular problem domain. If it's a libuv thing we can convert at the uv interface.)

@ljbade I'd love for you to work on this.

**Comment by kkaefer** [comment]
> If it's a libuv thing
it is

**Comment by ljbade** [comment]
@kkaefer I didn't actually find any interaction with libuv in our code to do with time.
