### ISSUE TITLE
Warning in MGLShapeSource documentation: Parameter 'URL' not found in the function declaration

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7840]
`-[MGLShapeSource initWithIdentifier:URL:options:]` says `@param URL` instead of `@param url`, leading to this warning when the `CLANG_WARN_DOCUMENTATION_COMMENTS` build setting is enabled:

```
/path/to/Mapbox.framework/Headers/MGLShapeSource.h:119:9: Parameter 'URL' not found in the function declaration
```

This warning occurs when building an application that links against the SDK.

/cc @bsudekum @jmkiley

**Comment by jmkiley** [comment]
Closed #7841
