### ISSUE TITLE
Printing is disabled

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7845]
@kkaefer pointed out that File ‣ Print is always disabled in macosapp. I’m also unable to get anything hooked up to the `print:` action to light up in a standalone application linked against macOS SDK v0.3.0. This feature obviously worked in #4962, and I’m pretty sure it worked just a few months ago.

**Comment by 1ec5** [comment]
This only seems to be an issue in terms of menu item or toolbar validation. If you call `-[MGLMapView print:]` manually, the print dialog does appear.

**Comment by kkaefer** [comment]
Short term fix merged in #7848, but as @1ec5 notes, we should resolve the issues in the responder chain.
