### ISSUE TITLE
[iOS] viewForAnnotation blocking the main thread

### ISSUE THREAD

**Issue by Gerz-inc** [mapbox/mapbox-gl-native#7849]
**Platform: iOS**
**Mapbox SDK version: 3.4**

I have a test app to try out the annotations feature of Mapbox with our mapping solution that is currently in progress. I am mapping about 20 or 30 (maybe more) annotations and constructing their views in the call to viewForAnnotation per query. When I pan the map and at this time are added the markers, the main thread is blocked while they addings. If used imageForAnnotation - all ok.

**Comment by Gerz-inc** [comment]
@tobrun, that issue is not for android platform

**Comment by boundsj** [comment]
`-[MGLMapViewDelegate mapView:viewForAnnotation:]` adds instances of `UIView` subclasses to the map to represent annotations. This work must be done on the main thread on iOS. `-[MGLMapViewDelegate mapView:imageForAnnotation:]` adds sprite images that represent annotations at the OpenGL level and is more performant. In general, use image backed annotations when performance is more of a concern and `MGLAnnotationView` backed annotations when more interactivity and the `UIView` API is required for your use case.
