### ISSUE TITLE
Missing POI text label

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#785]
Found this in Canberra:
![image](https://cloud.githubusercontent.com/assets/1215089/5929376/581c5748-a6d7-11e4-9bbd-2587e29435eb.png)

The "ANZ" POI (see screenshot from raster map) is missing the text label in GL. However the icon appears.

**Comment by friedbunny** [comment]
[Here](http://www.openstreetmap.org/edit?editor=id&node=341027596#map=19/-35.27894/149.13374) is the relevant node on OSM, I believe. The node (which is a bank with an ATM) lacks a `name` tag but has the "ANZ" `operator` tag.

**Comment by ansis** [comment]
Yes, the feature just doesn't have a name in the vectortiles we're is using right now. If other mapbox maps have it, it's probably because they are using a more up to date vectortile source that uses operator if name is missing.
