### ISSUE TITLE
Add an actionable next step from iOS Runtime Styling guide

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-native#7855]
The iOS [runtime styling guide](https://www.mapbox.com/ios-sdk/api/3.4.0/runtime-styling.html) does a nice job of explaining the _capabilities_ of runtime styling, but left me not knowing how to actually _do_ it (nor where to look to find out).

There's a very good chance that my feeling that this is missing stems from my total lack of familiarity w/ iOS programming paradigms.  Would a typical iOS developer's 'natural' expectations lead them just fine?  If so, perhaps this is a nonissue.

**Comment by ericrwolfe** [comment]
Good point @anandthakker. The likely next step would probably be pointing developers to runtime styling-focused examples. Those haven't been added to the website yet (http://mapbox.com/ios-sdk/examples) yet, but once they're live we can update with a blurb and a link.
