### ISSUE TITLE
Sensor.TYPE_ROTATION_VECTOR is not working on every device

### ISSUE THREAD

**Issue by fauger** [mapbox/mapbox-gl-native#7858]
Hello,

Actually in mapbox the bearing is fully based on Sensor.TYPE_ROTATION_VECTOR

`rotationVectorSensor = sensorManager.getDefaultSensor(Sensor.TYPE_ROTATION_VECTOR);`

This sensor type is not available on every device. I've juste faced the case with a galaxy A3 (not a old device yet) Will you provide some fallbacks in the futur ?
There are others implementations based on others types of sensor (accelerometer, magnetometer...)

Thanks.

**Platform:Android**
**Mapbox SDK version:4.2.1**

JFYI, the galaxy A3 sensors list : 

BOSCH Accelerometer Sensor    	   |         android.sensor.accelerometer
Samsung Significant Motion Sensor  |   	 android.sensor. Samsung Step Detector Sensor    
Samsung Step Counter Sensor   	   |     android.sensor.step_counter
BOSCH Tilt Detector Sensor    	   |	android.sensor.tilt_detector
BOSCH Pick Up Gesture Sensor      | 	 android.sensor. Samsung AutoRotation    
YAS537 Magnetic field Sensor    	  |	 android.sensor. YAS537 Uncalibrated Magnetic field Sensor    
TMD3700 Light Sensor    		  |	android.sensor.light
Samsung Geomagnetic Rotation Vector Sensor    |  android.sensor Orientation Sensor

**Comment by tobrun** [comment]
> Samsung Geomagnetic Rotation Vector Sensor

Isn't the last item in your list the rotation vector?
What behavior are you seeing when you enable any of these options in the SDK?
Thank you for reaching out and reporting this issue!

**Comment by fauger** [comment]
Yes it's my last item given by the following piece of code :

`            sensorManager = (SensorManager) context.getSystemService(Context.SENSOR_SERVICE);
            List<Sensor> sensors = sensorManager.getSensorList(Sensor.TYPE_ALL);
            for (Sensor sensor : sensors) {
                Log.i("sensor","name " + sensor.getName() + "    type " + sensor.getStringType());
            }
`

I have done a little pull request in order to display the foregroundDrawable instead of foregroundBearingDrawable when the sensor are not available.

See : https://github.com/mapbox/mapbox-gl-native/pull/7922
