### ISSUE TITLE
Per-property transitions are not parsed from style

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#7863]
16c435b1517b15a5ea8654987979ef58800b838b inadvertently removed the call to `parseTransitionOptions()` and thus support for per-property transitions in style JSON. This would represent a regression from iOS SDK v3.3.x and Android SDK v4.1.0.

Per mapbox/mapbox-gl-js#2788, mapbox/mapbox-gl-style-spec#171, and mapbox/mapbox-gl-test-suite#116, the current plan is to give per-property transitions all the trappings of a formal style specification feature, so here’s one more: the developer might expect to be able to configure per-property transitions using the runtime styling API, now that they can configure style-wide transitions (#7711).

/cc @jfirebaugh @incanus

**Comment by 1ec5** [comment]
> the developer might expect to be able to configure per-property transitions using the runtime styling API

#8010 tracks adding runtime styling support for per-attribute transitions to the iOS and macOS SDKs.

**Comment by incanus** [comment]
Just as a point of clarification, since _I_ was a little fuzzy on this, having e.g. a value for `text-color-transition` in the original style would cause runtime styling changes to `text-color` to transition. And then #8010 exposes such transition properties in code.
