### ISSUE TITLE
npm install mapbox-gl-native failes due to missing tarball

### ISSUE THREAD

**Issue by skyhoshi** [mapbox/mapbox-gl-native#7864]
**Platform: Windows And Linux (Windows 10, Ubuntu Server 16.04)**
**Mapbox SDK version: Windows: 3.4.2, Linux: 3.4.4**

### Steps to trigger behavior

 1. with both systems clean installs an attempt to install the latest nodejs and npm. 
 2. After No error installs of nodeJS and npm attempting command: "npm intstall -g mapbox-gl-native" 
 3.

### Expected behavior
error free install on Linux (i'm rather sure it's not compatible with windows systems) 
### Actual behavior
> mapbox-gl-native@3.4.2 install /var/www/tilesvr/node_modules/mapbox-gl-native
> node-pre-gyp install --fallback-to-build=false || make node

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/mapbox-gl-native/v3.4.2/node-v51-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/var/www/tilesvr/node_modules/mapbox-gl-native/node_modules/node-pre-gyp/lib/install.js:120:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:188:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/var/www/tilesvr/node_modules/mapbox-gl-native/node_modules/request/request.js:986:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:362:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Linux 4.4.0-31-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/var/www/tilesvr/node_modules/mapbox-gl-native/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /var/www/tilesvr/node_modules/mapbox-gl-native
node-pre-gyp ERR! node -v v7.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/mapbox-gl-native/v3.4.2/node-v51-linux-x64.tar.gz
mkdir -p build/linux-x86_64/Debug
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
(cd build/linux-x86_64/Debug && cmake -G Ninja ../../.. \
	-DCMAKE_BUILD_TYPE=Debug \
	-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
	-DWITH_CXX11ABI=ON \
	-DWITH_COVERAGE= \
	-DIS_CI_BUILD= \
	-DWITH_OSMESA=)
/bin/sh: 1: cmake: not found
Makefile:291: recipe for target 'build/linux-x86_64/Debug/build.ninja' failed
make: *** [build/linux-x86_64/Debug/build.ninja] Error 127
npm WARN enoent ENOENT: no such file or directory, open '/var/www/tilesvr/package.json'
npm WARN tilesvr No description
npm WARN tilesvr No repository field.
npm WARN tilesvr No README data
npm WARN tilesvr No license field.
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "mapbox-gl-native"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! mapbox-gl-native@3.4.2 install: `node-pre-gyp install --fallback-to-build=false || make node`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the mapbox-gl-native@3.4.2 install script 'node-pre-gyp install --fallback-to-build=false || make node'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapbox-gl-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build=false || make node
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapbox-gl-native
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapbox-gl-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/tilesvr/npm-debug.log
[npm-debug.txt](https://github.com/mapbox/mapbox-gl-native/files/731082/npm-debug.txt)

**Comment by jfirebaugh** [comment]
The error indicates that the precompiled binaries aren't available for the version of node you're using (v7.4.0), and that the necessary prerequisites for building from source aren't installed (cmake). Please try with node v4.x for precompiled binaries, or see https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md for dependencies for building from source.
