### ISSUE TITLE
Enable data-driven property functions for symbol paint properties

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-gl-native#7866]
Any potential blockers to getting these in to the upcoming data-driven styling releases on iOS and Android?

* icon-opacity
* icon-color
* icon-halo-color
* icon-halo-width
* icon-halo-blur
* icon-translate
* icon-translate-anchor
* text-opacity
* text-color
* text-halo-color
* text-halo-width
* text-halo-blur
* text-translate
* text-translate-anchor

Corresponding ticket in https://github.com/mapbox/mapbox-gl-js/issues/2730

/cc @lucaswoj

**Comment by lucaswoj** [comment]
No big blockers. This is long overdue. I'll start working on the GL JS side in the next couple days.

**Comment by jfirebaugh** [comment]
These are complete, with the exception of `*-translate-*`, which is tracked in https://github.com/mapbox/mapbox-gl-js/issues/2731 (we're using gl-js tickets to track DDS support across both implementations).
