### ISSUE TITLE
Globalize the iOS screenshot

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#7877]
The current screenshot used in the API docs and on the iOS readme here looks quite nice, but it lacks geographic diversity:

[![](https://github.com/mapbox/mapbox-gl-native/raw/00598432b0cc7b8aefd63b5162ad317917eb1154/platform/ios/docs/img/screenshot.png)](https://github.com/mapbox/mapbox-gl-native/blob/00598432b0cc7b8aefd63b5162ad317917eb1154/platform/ios/docs/img/screenshot.png)
_[Sketch file is available here.](https://github.com/mapbox/mapbox-gl-native/blob/00598432b0cc7b8aefd63b5162ad317917eb1154/platform/ios/originals/screenshot.sketch)_

Let’s broaden the scope of these screens beyond San Francisco (or even the US).

/cc @mayagao @1ec5

**Comment by 1ec5** [comment]
For comparison, for the [macOS SDK screenshot](https://mapbox.github.io/mapbox-gl-native/macos/), I was more interested in capturing eye-catching forms than particular geographies. The shot of New Orleans is dominated by a meandering (Saints-colored) Mississippi River; the complex highway interchange in Cincinnati accentuates Blueprint’s various line weights; and the aerial overview of the San Francisco Bay Area (not just San Francisco) provides a mix of mountains, urban jungle, and salt marshes.

**Comment by 1ec5** [comment]
#9397 updates the macOS SDK screenshot with views of Hong Kong’s buildings and Chinese street names (demonstrating our 3D extrusion and vertical CJK text support) and the Great Lakes region in Arabic (demonstrating our right-to-left text support). Victoria Harbour served as the backdrop this time.

**Comment by 1ec5** [comment]
#11746 updates the macOS map SDK screenshot with Denali, as seen in both Satellite and a modified Outdoors that replaces the Terrain layers with a Terrain RGB–backed terrain layer and converts the elevation from meters to smoots (demonstrating functionality made possible by expressions).

**Comment by friedbunny** [comment]
Still needs to happen, @stale[bot].

**Comment by friedbunny** [comment]
_Still_, still needs to happen.
