### ISSUE TITLE
Don't disable location tracking on all gestures

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#7878]
While location tracking is enabled and disable on gesture is true, you should still be able to change the zoom and tilt without disabling the tracking. 

cc: @tobrun

**Comment by tobrun** [comment]
To put in other words the tracking should only be disabled with `onScroll`?

**Comment by cammace** [comment]
Right even rotating shouldn't dismiss it therefore, only `onScroll` makes sense.

**Comment by tobrun** [comment]
Adding this to 5.0.0 milestone, changing this kind of business logic would require a semver change.

**Comment by tobrun** [comment]
Adding here from conversation with @cammace that this is related to changing the camera position and not related to the gestures:

```
/**
   * Reset the tracking modes as necessary. Animated camera position changes can reset the underlying tracking modes.
   *
   * @param cameraPosition the changed camera position
   */
  void resetTrackingModesIfRequired(CameraPosition cameraPosition) {
    if (isDismissTrackingModesForCameraPositionChange()) {
      resetTrackingModesIfRequired(cameraPosition.target != null, cameraPosition.bearing != -1);
    }
  }
```

cc @Guardiola31337
