### ISSUE TITLE
Add map padding to MGLMapView

### ISSUE THREAD

**Issue by vivienlegrand** [mapbox/mapbox-gl-native#7883]
I've a transparent menu at the bottom of my iOS application, and I've found no easy way to add a padding in my map for centering element in the visible part.
The MGLUserLocationAnnotationView is not centered, and Mapbox image and Attribution button are not visible.
The problem has been solved in Android in the issue #3761.

**Comment by 1ec5** [comment]
This feature was implemented for iOS in #3583 and #3589. See [`-[MGLMapView setContentInset:animated:]`](https://www.mapbox.com/ios-sdk/api/3.4.1/Classes/MGLMapView.html#/c:objc%28cs%29MGLMapView%28im%29setContentInset:animated:) and [`-[MGLMapView setUserLocationVerticalAlignment:animated:]`](https://www.mapbox.com/ios-sdk/api/3.4.1/Classes/MGLMapView.html#/c:objc%28cs%29MGLMapView%28im%29setUserLocationVerticalAlignment:animated:).
