### ISSUE TITLE
Can't upload to AppStore (due to Simulator slice files) - strip-framework.sh failed

### ISSUE THREAD

**Issue by csauvage** [mapbox/mapbox-gl-native#7894]
Main issues : 

```bash
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
         Referenced from: /usr/local/bin/bash
         Reason: image not found
```

**Platform: iOS **
**Mapbox SDK version: lastest (3.4.1)**

### Steps to trigger behavior

 1. Download lastest release
 2. Import to XCode 8.2 as __Embed Framework__
 3. Add run script : `bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Mapbox.framework/strip-frameworks.sh"`

### Expected behavior
App build and launch 

### Actual behavior
App failed to build due to *Run Script* 
App builds & works well when removing this script, but can't upload to iTC (using 🚀 Fastlane.tools)

![capture d ecran 2017-01-28 a 16 24 29](https://cloud.githubusercontent.com/assets/3155160/22397645/919039c4-e576-11e6-84d7-785561fed6b8.png)

![capture d ecran 2017-01-28 a 16 24 58](https://cloud.githubusercontent.com/assets/3155160/22397651/a54374cc-e576-11e6-82e2-956d287b055c.png)

**Comment by 1ec5** [comment]
The script is required for successful App Store submission. (It strips out the simulator slice that the submission validation complains about.) The libreadline error seems to suggest a problem with your Homebrew installation. If you installed readline via Homebrew, please ensure that you've installed and linked it, and that `brew doctor` doesn't turn up any issues.

**Comment by csauvage** [comment]
> The script is required for successful App Store submission. 
Yup, I know that 😊

> The libreadline error seems to suggest a problem with your Homebrew installation.

The clue you gave me helped me solving that issue, it was effectively an issue with Homebrew, but not due to the lack of readline, but it's version ! 

I had to perform a :
```bash
brew switch readline 6.3.8
brew unlink readline && brew link readline --force
```

And now it works like a charm ! 

Thx Minh !

**Comment by 1ec5** [comment]
Glad to hear it works!
