### ISSUE TITLE
IconFactory should only support bitmaps

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#7897]
If you use the Google Maps SDK for Android and pass in a drawable resource that isn't a BitmapDrawable it will throw an exception indicating only Bitmaps are supported (thus BitmapDrawable and no ShapeDrawable or VectorDrawable). Supporting these other types of drawables is something we currently do but as a side effect we are drawing bitmaps ourselves, The code used for this is often the source of memory leaks and memory churn.  I think we are good to remove support for these and go for a Bitmap only approach with a dedicated exception. 

cc @mapbox/android

**Comment by zugaldia** [comment]
@tobrun This makes sense. Would it make sense to move the current SDK code that is more flexible to a testapp activity to show how to handle other drawables?

**Comment by tobrun** [comment]
That was added to the PR, for visibility also copying in this ticket:

```
  /**
   * Demonstrates converting any Drawable to an Icon, for use as a marker icon.
   */
  public static Icon drawableToIcon(@NonNull Context context, @DrawableRes int id, @ColorInt int colorRes) {
    Drawable vectorDrawable = ResourcesCompat.getDrawable(context.getResources(), id, context.getTheme());
    Bitmap bitmap = Bitmap.createBitmap(vectorDrawable.getIntrinsicWidth(),
      vectorDrawable.getIntrinsicHeight(), Bitmap.Config.ARGB_8888);
    Canvas canvas = new Canvas(bitmap);
    vectorDrawable.setBounds(0, 0, canvas.getWidth(), canvas.getHeight());
    DrawableCompat.setTint(vectorDrawable, colorRes);
    vectorDrawable.draw(canvas);
    return IconFactory.getInstance(context).fromBitmap(bitmap);
  }
```
