### ISSUE TITLE
[Qt] Dark labels when rendering traffic-night style

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#7898]
Qt renders this:

![screenshot from 2017-01-30 16-50-54](https://cloud.githubusercontent.com/assets/996307/22427581/6c29039a-e70c-11e6-9515-c7c238c60fb4.png)

GLFW renders correctly:

![screenshot from 2017-01-30 16-50-43](https://cloud.githubusercontent.com/assets/996307/22427596/7b44695a-e70c-11e6-820c-179ffd660ada.png)

**Comment by brunoabinader** [comment]
@tmpsantos this could be related to your Qt version and/or graphics driver, it renders correctly in macOS:
![screen shot 2017-02-06 at 4 04 02 pm](https://cloud.githubusercontent.com/assets/76133/22649983/f1f55504-ec85-11e6-89ca-d45d2a1f86a9.png)

**Comment by tmpsantos** [comment]
> graphics driver

Could be this. I tested on Qt-dev and Qt 5.5 and got the same results on my laptop.

**Comment by tmpsantos** [comment]
This is a graphics driver bug.

**Comment by kkaefer** [comment]
How did you evaluate that this is a graphics driver bug?

**Comment by tmpsantos** [comment]
> How did you evaluate that this is a graphics driver bug?

I can only reproduce this on a "Intel Iris 6100". Tried on "Intel HD 620" and "ATI" on Linux and Windows and it works just fine. It could also be something that Qt is doing that is triggering the bug, because GLFW works.
