### ISSUE TITLE
Crash when removing nonexistent layer from style

### ISSUE THREAD

**Issue by jmkiley** [mapbox/mapbox-gl-native#7900]
**Platform:** iOS
**Version:** v3.4.1

**How to reproduce:**
Attempt to remove a layer that does not exist in the `MGLMapView`'s style.

**Expected Behavior:** 

Either should catch the C++ exception and either rethrow it as an NSException or ignore it.

**Actual Behavior:** 

The app crashes with error:
`libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: no such layer`

**Comment by eimantas** [comment]
I have an implementation where the exception is caught with logging a warning and returning `nullptr`. Would that be acceptable way of handling this situation?

**Comment by boundsj** [comment]
Hi @eimantas. I think that approach is reasonable. If you want to create a pull request with that change against the master branch we would appreciate it. Thanks!

**Comment by eimantas** [comment]
PR #7962

**Comment by boundsj** [comment]
This was fixed by https://github.com/mapbox/mapbox-gl-native/pull/7962.
