### ISSUE TITLE
[iOS] Mapbox Offline storage does not follow the notification usage pattern

### ISSUE THREAD

**Issue by eimantas** [mapbox/mapbox-gl-native#7908]
In documentation the `MGLOfflinePackProgressChangedNotification` notification is described as being posted by `MGLOfflineStorage` instance, however when notification arrives the `object` attribute of notification is the actual pack who's progress has changed. However in Apple's documentation on `NotificationCenter`, it states that the `object` parameter must contain the object performing the post.

I think one of the following two implementations would be better and more consistent with rest of the codebase posting/observing notifications:

1. The notification should be posted by the `MGLOfflinePack` instance that has its progress updated.
2. The `object` attribute of the notification should be the storage and the `MGLOfflinePack` should be stored in the `userInfo` dictionary (thus removing the need for redundant `progress` and `state` attribute storage under same `userInfo` instance).

I understand that this is a very breaking change and should (if at all released) follow the semantic versioning.

**Comment by 1ec5** [comment]
> The notification should be posted by the `MGLOfflinePack` instance that has its progress updated.

This is feasible: methods like `-[MGLOfflineStorage offlinePack:progressDidChange:]` would simply call methods on MGLOfflinePack. I think this approach would have the benefit of being backwards compatible.

**Comment by eimantas** [comment]
I took a look at the code, it seems that the private `MGLOfflinePackDelegate` becomes obsolete. I'd be willing to make a PR for this change.

**Comment by 1ec5** [comment]
A PR would be welcome – thanks!

**Comment by eimantas** [comment]
PR #7952
