### ISSUE TITLE
[iOS] desynchro on user annotation

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#7910]
**Platform: iOS 9, 10**
**Mapbox SDK version: 3.4.1 **

### Steps to trigger behavior

 1. Swipe far away from your location 
 2. Set the user tracking mode to follow
 3. Immediately tap on screen to stop the animation

### Expected behavior
The map should starts to fly to your location. The tap on screen stops the map and the user location is not visible (as it is far from the bounding box)

### Actual behavior
The map starts to fly to the user location. The tap on screen stops the map but the user location is shown on the middle of the map where it should not be. It stays there as long a new location is received.

The bug comes from the user location considered as centered from the start of the action but it is not yet centered before the end of animation.

I don't know yet how to correct that.

**Comment by RomainQuidet** [comment]
One way would to allow tap recognizer to handle the tap if the tracking mode is not none and state is began. This way, the map knows the user stopped the map from scrolling then fall back to tracking state none.
I can try this solution.

**Comment by RomainQuidet** [comment]
I fall in a problem: a touch is detected, the map engine stop the movement and the fly camera completion is called before the tap gesture recognizer is fired. So the fly camera completion does not inform us if the animation completed or have been interrupted by user tap...

**Comment by RomainQuidet** [comment]
the completion handler of the MGLMapView.mm method _flyToCamera:::: should have a boolean parameter indicating if the animation fully finish or has been interrupted by the _mbglMap->cancelTransitions() call (from touchBegan:).
I trie to use only tap recognizer from ObjC level but it seems that the only clean solution is to go deeper into the c++ engine.

**Comment by RomainQuidet** [comment]
I succeeded into getting a correct behavior here by adding simples lines before the cancelTransistions():

`- (void)touchesBegan:(__unused NS_SET_OF(UITouch *) *)touches withEvent:(__unused UIEvent *)event
{
    _changeDelimiterSuppressionDepth = 0;
    _mbglMap->setGestureInProgress(false);
    if (self.userTrackingState == MGLUserTrackingStateBegan)
    {
        [self setUserTrackingMode:MGLUserTrackingModeNone];
    }
    _mbglMap->cancelTransitions();
    
}`

I'm not sure if you like it.

**Comment by 1ec5** [comment]
Related to #4781.

**Comment by eimantas** [comment]
Another one may be to ignore user interaction until animation is complete.

**Comment by RomainQuidet** [comment]
I disagree, a user must be able to stop a map scrolling by a tap.

Romain

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/7916
