### ISSUE TITLE
Cannot initialize a MGLShapeSource with array of MGLFeatures 

### ISSUE THREAD

**Issue by jmkiley** [mapbox/mapbox-gl-native#7913]
**Platform:** iOS
**Mapbox SDK version:** v3.4.1

### Steps to trigger behavior

 1. Using Swift, create an array of objects that conform to `MGLFeature`.

 `let features = [MGLFeature]()`

 2. Try to initialize a shape source with it using `MGLShapeSource initWithIdentifier:features:options:`

`let source = MGLShapeSource(identifier: "features", features: features, options: nil)`

### Expected behavior
The `MGLShapeSource` would accept the array (similar to how `MGLGeoJsonSource` did). This 
would be helpful if you want to use multiple types of feature objects in the same shape source, for example.

### Actual behavior
The initializer cannot convert the array of MGLFeatures into MGLShapes.

<img width="873" alt="screenshot 2017-01-31 13 37 33" src="https://cloud.githubusercontent.com/assets/12474734/22479077/78fde410-e7ba-11e6-8fa1-a86a56ebec3f.png">

<img width="899" alt="screenshot 2017-01-31 12 43 39" src="https://cloud.githubusercontent.com/assets/12474734/22478635/c1e00066-e7b8-11e6-9fd1-4cb54db8d61d.png">

**Comment by 1ec5** [comment]
Possibly due to the changes made as a result of https://github.com/mapbox/mapbox-gl-native/pull/7665#discussion_r95509462.

**Comment by boundsj** [comment]
Noting a possible workaround for now:

```
let feature = MGLPolygonFeature(coordinates: coords, count: UInt(coords.count))
let features: [MGLFeature] = [feature]
let shapeFeatures = features.map { return $0 as! MGLShape }
```

I think you can also pass an array that is typed like `let features: [MGLShape] = [feature]` where `feature` is actually an `MGLFeature`

**Comment by iDevid** [comment]
Use a MGLPointFeature sequence instead
