### ISSUE TITLE
Add documentation for data-driven styling

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-gl-native#7924]
Support for data-driven styling for iOS and macOS is being added in https://github.com/mapbox/mapbox-gl-native/pull/7596. After we have used the API proposed there and before the final Mapbox iOS SDK 3.5.0 beta, we will fully document the new APIs added for DDS.

#### This will include (at least):

- [x] MGLStyleFunctionOption string enum
  - [x] MGLStyleFunctionOptionInterpolationBase
  - [x] MGLStyleFunctionOptionDefaultValue
- [x] MGLInterpolationMode enum
  - [x] MGLInterpolationModeExponential
  - [x] MGLInterpolationModeInterval
  - [x] MGLInterpolationModeCategorical
  - [x] MGLInterpolationModeIdentity
- [x] Update class documentation for `MGLStyleValue` (as a class cluster it represents something different now)
- [x] +[MGLStyleValue valueWithInterpolationMode:cameraStops:options:]
- [x] +[MGLStyleValue valueWithInterpolationMode:sourceStops:attributeName:options:]
- [x] +[MGLStyleValue valueWithInterpolationMode:compositeStops:attributeName:options:]
- [x] MGLCameraStyleFunction (and all methods and properties)
- [x] MGLSourceStyleFunction (and all methods and properties)
- [x] MGLCompositeStyleFunction (and all methods and properties)
- [x] Update generated code examples in `MGLDocumentationExampleTests.swift` to use camera functions and maybe add examples for `source` and `composite` functions
- [ ] Update `guides/For Style Authors.md` with DDS specific terminology differences
- [ ] Update `guides/Runtime Styling.md` with information about DDS (or add a DDS specific guide)

cc @friedbunny @jmkiley @1ec5 @incanus @ericrwolfe @pveugen

**Comment by 1ec5** [comment]
We should fill out the documentation before the _first_ beta, because that's when we tell developers to start coding against new features in nontrivial projects. We can ship an alpha without the documentation if necessary to meet time commitments, however.

**Comment by 1ec5** [comment]
* [ ] Update the iOS and macOS changelogs to discuss all that’s changed

**Comment by boundsj** [comment]
#7931, #7943, and #7960 added API documentation that should be suitable for the beta release. We still need a PR to update the guides but I don't consider that a requirement for the beta.

Before I create the beta, I will wait for:

- https://github.com/mapbox/mapbox-gl-native/pull/7993 that adds a changelog updates for iOS and macOS.
- https://github.com/mapbox/mapbox-gl-native/pull/7958 that adds notes about the possible function and interpolation modes combinations that are valid for each property

**Comment by 1ec5** [comment]
#8025 will update the MGLFeature documentation to discuss more ways a feature’s attributes can be used, including in source functions.

**Comment by boundsj** [comment]
I'm removing `release blocker` and closing this issue. The work to update and add guides continues in https://github.com/mapbox/mapbox-gl-native/pull/8354 and it is possible that that PR may also be sufficient for https://github.com/mapbox/mapbox-gl-native/issues/8192.

cc @jmkiley
