### ISSUE TITLE
[ios, macos] Create an example about how to use the new delegate to restrict camera movement.

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/mapbox-gl-native#7927]
With the introduction of this feature, we must provide non trivial examples about how this may be implemented, some use cases we have thought:

- [ ] Block camera for tiles we don't have information (offline maps).
- [ ] Block camera outside a specific boundary.

cc @boundsj @1ec5

**Comment by 1ec5** [comment]
The jazzy-generated documentation is typically limited to very brief examples that can be contained within a single method implementation. For anything more substantial, we typically add an example to the [ios-sdk-examples](https://github.com/mapbox/ios-sdk-examples/) project and pull it into the [online examples](https://www.mapbox.com/ios-sdk/examples/) from there.

**Comment by 1ec5** [comment]
This is happening in mapbox/ios-sdk-examples#65. We can track this work there.
