### ISSUE TITLE
Crash when transitioning class changes

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#794]
If I set `setDefaultTransitionDuration` before calling `setClasses` I get a crash:
```
01-30 11:52:33.113      274-274/? I/DEBUG﹕ #00  pc 0010fc20  /data/app-lib/com.mapbox.mapboxgl.app-2/libmapbox-gl.so (mbgl::StyleLayer::setClasses(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, unsigned long long, mbgl::PropertyTransition const&)+604)
01-30 11:52:33.113      274-274/? I/DEBUG﹕ #01  pc 001101bc  /data/app-lib/com.mapbox.mapboxgl.app-2/libmapbox-gl.so (mbgl::StyleLayer::applyClassProperties(mbgl::ClassID, std::__1::set<mbgl::PropertyKey, std::__1::less<mbgl::PropertyKey>, std::__1::allocator<mbgl::PropertyKey> >&, unsigned long long, mbgl::PropertyTransition const&)+1336)
```

/cc @incanus

**Comment by incanus** [comment]
This API may be rusty; I will add it to the iOS app and poke at this a bit soon.

**Comment by bleege** [comment]
@ljbade Is this still an issue or can we close this?

**Comment by ljbade** [comment]
I need to test this. We haven't used the classes stuff for a while on Android.

**Comment by bleege** [comment]
@ljbade K.  I'll move this to `android-0.2.0` for future :eyes: .

**Comment by ljbade** [comment]
Related to https://github.com/mapbox/mapbox-gl-native/issues/1744

**Comment by ljbade** [comment]
@jfirebaugh Do any of the `mapbox-gl-styles` still have classes I can use to test these functions?

If not, are classes going to be removed from the style spec? If that is the case I might as well just remove these functions.

**Comment by jfirebaugh** [comment]
I don't think any `mapbox-gl-styles` styles have classes. You can create a small test style that transitions say `background-color` to test this though.

We're not sure what the long term future of style classes is yet. We'll need to have a full Style API in native before we can make the call one way or the other.

**Comment by tobrun** [comment]
I have played around with this API and I believe it's broken.

If I run the testapp with `MAPBOX_STREETS` style and call `getStyleClasses()`, I'm returned a empty list. 
I checked if `setStylesClasses` with duration is still throwing an exception and it still does.

@bleege 
- Is there a backstory/reason for this API?
- If not, can we remove it?

**Comment by tobrun** [comment]
@bleege I have found this [issue](https://github.com/mapbox/mapbox-gl-native/issues/2875), making this API obsolete. Closing down.

**Comment by bleege** [comment]
:+1:
