### ISSUE TITLE
Gradle (missing dependency) error: telemetry:2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by ragaisis** [mapbox/mapbox-gl-native#7950]
**Platform:** Android
**Mapbox SDK version:** 4.2.2 (but I forked latest version from github)

### Steps to trigger behavior

 1. Updated forked mapbox library
 2. Tried to sync project 
 3. Graddle error:

```
Error:Could not find com.mapbox.mapboxsdk:mapbox-android-telemetry:2.0.0-SNAPSHOT.
Required by:
    MyApp:app:unspecified > com.mapbox.mapboxsdk:MapboxGLAndroidSDK:5.0.0-SNAPSHOT
<a href="searchInBuildFiles">Search in build.gradle files</a>
```

### Expected behavior

Mapbox SDK should work with latest version on master.

### Actual behavior

Can't build project due gradle error (missing telemetry services dependency)

### Comments

How can I add telemetry services to my project? Or it's impossible and I should be patient and just check for latest public Mapbox release in git history (currently it's 4.2.2 on Android) and use that version and wait for a new public release?

**Comment by tobrun** [comment]
@ragaisis this is an issue I have seen myself and is related to gradle not correctly downloading/finding the depencies. I worked around this by blowing away my gradle cache:

> http://stackoverflow.com/a/30450020/1281750

Feel free to reach out if above doesn't resolve your issue.
Closing for now

**Comment by ragaisis** [comment]
Thanks for suggestion. I tried several times: 

- File | Invalidate Caches/Restart
- rm -rf $HOME/.gradle/caches/

But error still exists. 

```
Error:Could not find com.mapbox.mapboxsdk:mapbox-java-geojson:2.0.0-SNAPSHOT.
Required by:
    Loisto:app:unspecified > com.mapbox.mapboxsdk:MapboxGLAndroidSDK:5.0.0-SNAPSHOT
<a href="searchInBuildFiles">Search in build.gradle files</a>
```

**Comment by tobrun** [comment]
You can see that this dependency is available on maven central [here](https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-java-geojson/2.0.0-SNAPSHOT/)

**Comment by ragaisis** [comment]
Thanks, last hint give me idea, that something is missing in my top level gradle file and it was:

        maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }

Thanks again, and sorry for disturbing
