### ISSUE TITLE
MarkerView's rotation is not preserved once the view goes outside of viewable area.

### ISSUE THREAD

**Issue by ntomizawa** [mapbox/mapbox-gl-native#7951]
**Platform: Android 5.0.1 (Zenfon 2) **
**Mapbox SDK version: Android SDK 4.2.2 **

MarkerView could not preserve rotation by View.setRotatation(float) once the view goes outside of current viewable area. I'm not sure this behavior is bug or not.

### Steps to trigger behavior

 1. Build small test program.

```
    private MapView mapView;

    private MarkerView marker;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        MapboxAccountManager.start(this, "MY TOKEN!!");

        setContentView(R.layout.activity_main);
        mapView = (MapView) findViewById(R.id.mapview);
        mapView.onCreate(savedInstanceState);
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {

                MarkerViewOptions markerViewOptions = new MarkerViewOptions()
                        .icon(IconFactory.getInstance(MainActivity.this).fromResource(R.mipmap.ic_launcher))
                        .position(new LatLng(0, 0));
                marker = mapboxMap.addMarker(markerViewOptions);

            }
        });

        mapView.addOnMapChangedListener(new MapView.OnMapChangedListener() {
            @Override
            public void onMapChanged(int change) {
                if (change == MapView.DID_FINISH_RENDERING_MAP_FULLY_RENDERED) {
                    mapView.getMapAsync(new OnMapReadyCallback() {
                        @Override
                        public void onMapReady(MapboxMap mapboxMap) {
                            View markerView = mapboxMap.getMarkerViewManager().getView(marker);
                            if (markerView != null) {
                                markerView.setRotation(180);
                            }
                        }
                    });
                }
            }
        });
    }

```

 2. Execute the test program.
 3. Scroll map, make the icon go outside of visible area and back.

### Expected behavior

The icon is still upside-down (by preserved rotation with markerView.setRotation(180);)

### Actual behavior

The icon DOES NOT look like upside-down.

**Comment by tobrun** [comment]
@ntomizawa thank you for reporting this issue, apologies for only getting back to you now. 

The MarkerView system uses View recycling which is very similar to the system that Android uses for a ListView. This system will reuse views for multiple markers and thus we aren't able to keep state for views. All logic related to state should be managed by the model (in this case MarkerView#setRotation). 

Side note is that with the 5.0.0  release we have changed the interaction model with MarkerView#setRotation in https://github.com/mapbox/mapbox-gl-native/pull/7907.

Feel free to reach out if you have any more questions or if something is unclear.

Closing as non-actionable.
