### ISSUE TITLE
MGLMapView leaks MGLReachability objects

### ISSUE THREAD

**Issue by danielmatzke** [mapbox/mapbox-gl-native#7955]
**Platform:**
macOS 10.12.3 

**Mapbox SDK version:**
0.3.0-rc.1

### Steps to trigger behavior

 1. create and destroy MGLMapView
 2. create and destroy MGLMapView
 3. see that number of persistent MGLReachability objects in Instruments is 2

### Expected behavior

MGLReachability should be released when MGLMapView object is destroyed. 

### Actual behavior

MGLReachability is not released when MGLMapView object is destroyed. Note that the MGLMapView.commonInit creates a MGLReachability object which is not shared and never released.

**Comment by 1ec5** [comment]
Fixed in #7956.
