### ISSUE TITLE
Provide more descriptive error message when removing a marker that doesn't exist

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-native#7961]
**Platform:** Android
**Mapbox SDK version:** 4.2.2

### Steps to trigger behavior

Attempt to remove a marker that does not exist.

### Expected behavior

Graceful failure with descriptive error message and/or Java exception (instead of native). 

### Actual behavior

Crash with an error message similar to: 

```
void mbgl::AnnotationManager::removeAnnotation(const AnnotationID &): assertion "false" failed
```

**Comment by tobrun** [comment]
We should prevent calling into core when the marker hasn't been added to the map. Adding this to the next milestone for visibility.
