### ISSUE TITLE
Android 5.0 Docs

### ISSUE THREAD

**Issue by nitrag** [mapbox/mapbox-gl-native#7965]
Would like to go ahead and start working with Android 5.0.0-SNAPSHOT but I can't find the docs posted anywhere.

I've tried (like iOS docs) but it's a No-Go. 
https://www.mapbox.com/android-sdk/api/5.0.0/
https://www.mapbox.com/android-sdk/api/5.0.0-SNAPSHOT/

@tobrun

**Comment by tobrun** [comment]
Hey @nitrag, thank you for requesting documentation for the upcoming android release. We do not publish any documentation for snapshots as they change daily. Once all features for 5.0.0 are developed we will start releasing beta versions. These releases will result in publishing javadoc on the website. FWIW You are able to generate the javadoc yourself locally through gradle.

Feel free to reach out if you have any more questions. 

cc @cammace

**Comment by cammace** [comment]
We've prepared a document pointing out many of the changes you'll need to make when updated from 4.x to 5.0. Check it [out here](https://github.com/mapbox/mapbox-gl-native/wiki/Android-4.x-to-5.0-update).
