### ISSUE TITLE
Error gl ndk 13

### ISSUE THREAD

**Issue by fabricio1993** [mapbox/mapbox-gl-native#7967]
**Platform: Android**
**Mapbox SDK version:5.0.0**

### Steps to trigger behavior

 1. Run testapp in Tablet androdi 4.4.2 model SM-T231

### Actual behavior
#v02-07 13:14:32.022 20698-20698/com.mapbox.mapboxsdk.testapp A/libc: /usr/local/google/buildbot/src/android/ndk-r13-release/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type mbgl::gl::Error: glBindAttribLocation(id, location, name): Error GL_INVALID_VALUE at /home/mapas/mapbox-gl-native/src/mbgl/gl/attribute.cpp:12" failed

#02-07 13:14:32.022 20698-20698/com.mapbox.mapboxsdk.testapp A/libc: Fatal signal 6 (SIGABRT) at 0x000050da (code=-6), thread 20698 (pboxsdk.testapp)

**Comment by jfirebaugh** [comment]
Thanks for the report. We don't have access to that device to test, but based on the error message there may be an issue with the OpenGL implementation.

We don't have the team bandwidth to debug compatibility issues with individual Android device models, but if you find a solution to this we'd certainly be interested to know about it.

**Comment by fabricio1993** [comment]
I have not found a solution yet, but I decided to use the branch https://github.com/mapbox/mapbox-gl-native/tree/branch-2017-01-16 in this version is very good and does not present problems, I think it was A posteroir modification that causes the problem in the master branch.
By limiting this device also presented this problem for a long time https://github.com/mapbox/mapbox-gl-native/issues/5443 and that in version 4.2.2 is still, but in version 5.0.0 this is Solved

Is it something special with this tablet model?
