### ISSUE TITLE
Remove WindingType

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-native#797]
[`WindingType`](https://github.com/mapbox/mapbox-gl-native/search?utf8=%E2%9C%93&q=WindingType) is defined in style_bucket but not actually used anywhere, right? Can we remove?

**Comment by jfirebaugh** [comment]
:+1:, delete it.

**Comment by lbud** [comment]
Cool —I'll do this after merging https://github.com/mapbox/mapbox-gl-native/pull/799 to avoid some unnecessary conflicts.
