### ISSUE TITLE
Could not load MapView due crash: GL_ARB_vertex_array_object extension is required

### ISSUE THREAD

**Issue by ragaisis** [mapbox/mapbox-gl-native#7970]
**Platform:** Android
**Mapbox SDK version:** 4.2.2 (but really it's freshly forked from the github)

### Steps to trigger behavior

 1. Run the app on Lenovo TB3-710F
 2. Mapbox SDK crash on loading MapView (stacktrace added as attachment)

Here is crash log: 
[crash_stacktrace.txt](https://github.com/mapbox/mapbox-gl-native/files/759023/crash_stacktrace.txt)

### Expected behavior

Mapbox SDK should work on all Android devices

### Actual behavior

It's not working on  Lenovo TB3-710F

### Comments

From the Fabric crashlytics I see that problem is here:

`Non-fatal Exception: java.lang.Error GL_ARB_vertex_array_object extension is required`

```
com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender (NativeMapView.java)
com.mapbox.mapboxsdk.maps.NativeMapView.render (NativeMapView.java:175)
com.mapbox.mapboxsdk.maps.MapView.onDraw (MapView.java:444)
```

**Comment by RJiryes** [comment]
Hey, Is this fixed on the current snapshot on Android? Thanks!
