### ISSUE TITLE
[WARNING] {}[Render]: can't find source for layer - IOS

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [mapbox/mapbox-gl-native#7976]
Hi, 

I am getting this warning in console `[WARNING] {}[Render]: can't find source for layer ` when i tried to add `MGLStyleLayer ` on mapview, 
   

       func handleLongTap(longRecog: UILongPressGestureRecognizer) {
        
           let location = longRecog.location(in: self.mapView)
           let touchableSquare = buffer(location: location, length: 10.0)

           let features = self.mapView.visibleFeatures(in: touchableSquare)
           let shapeFeatures = features.map { return $0 as! MGLShape }
        
           let source = MGLShapeSource(identifier: "features", features: shapeFeatures, options: nil)
          
           let styleLayer = MGLCircleStyleLayer(identifier: "features", source: source)

           styleLayer.circleColor = MGLStyleValue(rawValue: .cyan)
           styleLayer.circleRadius = MGLStyleValue(stops: [
               1: MGLStyleValue(rawValue: 5),
               18: MGLStyleValue(rawValue: 3),
               ])
           styleLayer.circleOpacity = MGLStyleValue(rawValue: 0.5)
           self.mapView.style?.addLayer(styleLayer)
       }

       private func buffer(location: CGPoint, length:Double) -> CGRect {
           return CGRect(x: Double(location.x - CGFloat(length / 2)), y: Double(location.y - CGFloat(length / 2)), width: length, height: length)
       }

**Comment by boundsj** [comment]
Hi @ThiyagarajanShivSankaran, thanks for reaching out. Please have a look at our help resources and [contact us through the form there](https://www.mapbox.com/contact/) if you cannot find a solution to your issue.

Specifically, please [check out the relevant API documentation](https://www.mapbox.com/ios-sdk/api/3.4.1/Classes/MGLShapeSource.html) and [guides](https://www.mapbox.com/ios-sdk/api/3.4.1/working-with-geojson-data.html).

In this case, it looks like you did not add your source to the mapView's style (via `addSource()`).

**Comment by 1ec5** [comment]
#7988 would help developers avoid the mistake demonstrated in this issue.
