### ISSUE TITLE
Add filter accessor to layer

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#7978]
ATM there is only a setter for filters on `Layer` classes, no getter, eg `Layer#getFilter()`.

**Comment by Jukurrpa** [comment]
Hi, I just wanted to know what is the priority on this?

We built most of our design using Mapbox Studio and having access to a layer's filters would be very useful when making changes to it, for example when adding/removing filters on an existing layer while keeping the ones defined through Studio. Storing these base filters in the app or through remote config would somewhat defeat the purpose of Studio.

In the same vein, it'd also be greatly appreciated if layers exposed their source's identifier (in addition to the source layer's identifier).

**Comment by tobrun** [comment]
We are going to add expression filter support to core soon and add Android accessors for it. 
This issue has become obsolete.

**Comment by 1ec5** [comment]
> We are going to add expression filter support to core soon and add Android accessors for it.

#10720
