### ISSUE TITLE
Using `fill-image` and `background-image` creates visible borders

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-native#798]
See JS issue https://github.com/mapbox/mapbox-gl-js/issues/972

**Comment by springmeyer** [comment]
Noting this brought in a new warning that results in an error on travis:

```
../../src/mbgl/geometry/sprite_atlas.cpp: In function ‘void copy_bitmap(const uint32_t*, int, int, int, uint32_t*, int, int, int, int, int, bool)’:
../../src/mbgl/geometry/sprite_atlas.cpp:78:35: error: ‘srcI’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
                 dst[x] = src[srcI + ((x + width) % width)];
                                   ^
cc1plus: all warnings being treated as errors
```

**Comment by springmeyer** [comment]
@ansis setting `int srcI = 0;` I think would be a reasonable way to fix this: https://github.com/mapbox/mapbox-gl-native/commit/23dd403a25938f3257b63e3b6a8721d62afaa4ce#diff-592b2ff2c29a04d22d8e3064bcf128beR74

**Comment by ansis** [comment]
@springmeyer thanks for noticing. https://github.com/mapbox/mapbox-gl-native/commit/3de43f5f5813465cd1c4ccdeeffa829fd0258fbc
