### ISSUE TITLE
Recently used tiles do not cache if you have more than 30MB downloaded

### ISSUE THREAD

**Issue by wibge** [mapbox/mapbox-gl-native#7984]
**Platform:** ios
**Mapbox SDK version:** 3.4

### Steps to trigger behavior

 1. Download map packs more than 30 MB
 2. Pan back and forth around the map in non-downloaded area

### Expected behavior
Tiles that were viewed 10 seconds ago will be cached and not re-downloaded
### Actual behavior
No tiles are cached and are redownloaded on every pan back and forth

This happens because the function that checks if there is space in the database to cache recently used tiles counts the downloaded tiles as well 

https://github.com/mapbox/mapbox-gl-native/blob/master/platform/default/mbgl/storage/offline_database.cpp#L784

The ideal solution to this is probably to have separate databases for a recently used tile cache, and the downloaded tiles.

**Comment by ericrwolfe** [comment]
Related: https://github.com/mapbox/mapbox-gl-native/issues/4411

**Comment by friedbunny** [comment]
Thanks for the report — let’s continue tracking this in #4411.
