### ISSUE TITLE
InfoWindow doesn't follow map

### ISSUE THREAD

**Issue by elevenetc** [mapbox/mapbox-gl-native#7985]
Not sure if it's a feature or a bug, but if you override `setOnMarkerClickListener` and call `marker.showInfoWindow` infoWindow is shown but it doesn't follow map. If I comment `marker.showInfoWindow` call then infoWindow is not shown at all.

```java
mapboxMap.setOnMarkerClickListener(new MapboxMap.OnMarkerClickListener() {
    @Override
    public boolean onMarkerClick(@NonNull Marker marker) {
        marker.showInfoWindow(mapboxMap, mapView);
        return true;
    }
});

mapboxMap.setInfoWindowAdapter(new MapboxMap.InfoWindowAdapter() {
    @Nullable
    @Override
    public View getInfoWindow(@NonNull Marker marker) {
        return null;
    }
});
```
Video: https://dl.dropboxusercontent.com/u/4125923/mapbox-info-window-drag.mp4

**Platform:** android 
**Mapbox SDK version:** 4.2.2

### Expected behavior
InfoWindows follows map
### Actual behavior
InfoWindow has fixed location

**Comment by tobrun** [comment]
@elevenetc thank you for reaching out. ShowInfoWindow is marked as private api:

```
/**
   * Do not use this method, used internally by the SDK. Use {@link MapboxMap#selectMarker(Marker)}
   * if you want to programmatically display the markers info window.
   */
```

Please use `MapboxMap#selectMarker` instead.

Thank you for reaching out!
