### ISSUE TITLE
[Android] Crash app when using both of Mapbox SDK and Realm database 

### ISSUE THREAD

**Issue by GianhTran** [mapbox/mapbox-gl-native#8000]
Platform: Android
**Mapbox SDK version:**4.2.2

Hi Mapbox Team,

I using mapbox SDK v.4.2.2 and realm database v2.2.0, map crash with log:

`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/jp.co.test.android.app.testimplmapsdk-1/base.apk"],nativeLibraryDirectories=[/data/app/jp.co.test.android.app.testimplmapsdk-1/lib/arm64, /data/app/jp.co.test.android.app.testimplmapsdk-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libmapbox-gl.so"`

However, if I using mapbox SDK v.4.4.2.0-beta.*, its okey.

How can I fix this issue? 

Thanks you in advance!

Update: if I try to build on 32bit device , its work well, looklike https://github.com/Telerik-Verified-Plugins/Mapbox/issues/72

**Comment by tobrun** [comment]
@GianhTran thank you for reaching out and reporting this issue. This is the first report we had on this type of issue. @kkaefer this seems to be one of the issues that could be resolved using [ReLinker](https://github.com/KeepSafe/ReLinker)? cc @ivovandongen

**Comment by kkaefer** [comment]
@GianhTran did you compile the 64 bit version of the SDK prior to building the APK?

**Comment by MariusBoepple** [comment]
@kkaefer We're using Mapbox + Realm and face similar issues:
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/hero2ltexx/hero2lte:7.0/NRD90M/G935FXXU1DQBX:user/release-keys'
Revision: '9'
ABI: 'arm64'
pid: 10364, tid: 10364, name: com.example.app  >>> com.example.app <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xa5e43816021
    x0   00000a5e43815f59  x1   00000071963c8600  x2   0000000000000000  x3   000000719a829f80
    x4   00000071965fafa0  x5   00000071d569eb0b  x6   00000071f7a0c788  x7   00000071c39fb7e0
    x8   00000a5e43815f59  x9   0000000000000000  x10  000000000000fffa  x11  00000000000000ff
    x12  000000000dbd2eb0  x13  00000000f242d150  x14  0000007197870c00  x15  0000000000000000
    x16  00000071cad6f9d8  x17  00000071fad159c4  x18  0000000000ffffeb  x19  00000a5e43815f59
    x20  00000071962b3008  x21  27e5e925699cc5ee  x22  00000071965fafa0  x23  00000071962b3118
    x24  00000071962b3160  x25  27e5e925699cc5ee  x26  27e5e925699cc5ee  x27  0000000000000000
    x28  0000000000000000  x29  0000007ff6358f30  x30  00000071ca8b20fc
    sp   0000007ff6358ee0  pc   00000071ca8d0638  pstate 0000000020000000

backtrace:
    #00 pc 00000000000d4638  /data/app/com.example.appr-2/lib/arm64/libmapbox-gl.so
    #01 pc 00000000000b60f8  /data/app/com.example.app-2/lib/arm64/libmapbox-gl.so
    #02 pc 00000000000acaa4  /data/app/com.example.app-2/lib/arm64/libmapbox-gl.so
    #03 pc 000000000007b4f4  /data/app/com.example.app-2/lib/arm64/libmapbox-gl.so
    #04 pc 0000000000086a54  /data/app/com.example.app-2/lib/arm64/libmapbox-gl.so
    #05 pc 000000000115a270  /data/app/com.example.app-2/oat/arm64/base.odex (offset 0xf62000)
```
There are some inconsistencies in the Play Console reports (with the Android/ABI versions):

![screen shot 2017-04-28 at 10 09 38](https://cloud.githubusercontent.com/assets/11991870/25520159/3983e17e-2bfb-11e7-8c79-090c9ec610cc.png)

Could this have something to do with #3128? Or maybe these devices have some strange custom configurations? Because we weren't able to reproduce it with a bunch of devices and it seems to be something with the ABIs...
