### ISSUE TITLE
Build failure due to boost warnings

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-gl-native#801]
Warnings are coming from the jpeg and png image readers based on boost headers when compiled with g++-4.8. Unclear what changed (boost, g++, compile flags, or something else?) Anway, we'll need to look into silencing these warnings from boost. Until we do, this ticket is to track the breakage:

```
make[1]: *** [../Release/obj.target/mbgl-linux/platform/default/png_reader.o] Error 1
In file included from /home/travis/build/mapbox/mapbox-gl-native/mason_packages/linux-x86_64/boost/system/include/boost/iostreams/stream_buffer.hpp:21:0,
                 from /home/travis/build/mapbox/mapbox-gl-native/mason_packages/linux-x86_64/boost/system/include/boost/iostreams/stream.hpp:21,
                 from ../../include/mbgl/platform/default/jpeg_reader.hpp:12,
                 from ../../platform/default/jpeg_reader.cpp:1:
/home/travis/build/mapbox/mapbox-gl-native/mason_packages/linux-x86_64/boost/system/include/boost/iostreams/detail/streambuf/direct_streambuf.hpp: In instantiation of ‘void boost::iostreams::detail::direct_streambuf<T, Tr>::set_auto_close(bool) [with T = boost::iostreams::basic_array_source<char>; Tr = std::char_traits<char>]’:
../../platform/default/jpeg_reader.cpp:203:2:   required from here
/home/travis/build/mapbox/mapbox-gl-native/mason_packages/linux-x86_64/boost/system/include/boost/iostreams/detail/streambuf/direct_streambuf.hpp:64:10: error: declaration of ‘close’ shadows a member of 'this' [-Werror=shadow]
     void set_auto_close(bool close) { auto_close_ = close; }
          ^
At global scope:
cc1plus: error: unrecognized command line option "-Wno-unknown-warning-option" [-Werror]
cc1plus: error: unrecognized command line option "-Wno-unknown-warning-option" [-Werror]
cc1plus: all warnings being treated as errors
```

refs https://travis-ci.org/mapbox/mapbox-gl-native/jobs/49249432#L1219

**Comment by ljbade** [comment]
Yeah I started getting lots of these warning on my local Linux system which did not happen the other week.

I got around it by setting some CXXFLAGS but is giving me headaches on Travis betweem clang and gcc supporting a different set of compile flags and each complaining about the other's.

**Comment by ljbade** [comment]
For example https://travis-ci.org/mapbox/mapbox-gl-native/jobs/49277140 and https://travis-ci.org/mapbox/mapbox-gl-native/jobs/49277142

**Comment by ljbade** [comment]
Turns out the problem is GCC with `boost/iostreams/stream.hpp` in `png_reader.hpp`.

On @kkaefer I am removing global `-Wno-error` flags and instead using `#pragma`s in the correct places.

The changes are currently in my `chrono` branch.

**Comment by jfirebaugh** [comment]
I pulled those changes into a separate commit.

Top priority right now should be getting the build green. Then we can start merging PRs again.
