### ISSUE TITLE
Per-attribute transition properties on MGLStyleLayer

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8010]
MGLStyleLayer’s concrete subclasses should allow the developer to set transitions that affect individual layout or paint attributes.

We could pair every layout or paint attribute with a `transitionFor…` property. Or we could fight property proliferation by adding `-transitionForKey:` and `-setTransition:forKey:` methods to MGLStyleLayer itself (along the lines of `-[CALayer addAnimation:forKey:]`). (The downside would be pushing validation of the key until runtime.)

Either way, we should add an MGLTransition class or struct to encapsulate the details of a transition. We’ll want to refine the MGLStyle methods added in #7711 to make use of MGLTransition instead of working with durations and delays directly.

/ref #7863
/cc @incanus @boundsj @jfirebaugh @tobrun

**Comment by 1ec5** [comment]
`mbgl::Layer` subclasses expose properties for setting transitions on individual layout and paint properties ([example](https://github.com/mapbox/mapbox-gl-native/blob/9ffbfdc7b94ec60bc0a5253a56121b7bf707a23f/include/mbgl/style/layers/circle_layer.hpp#L35)). However, there don’t appear to be any getters. We should add transition getters too.

**Comment by boundsj** [comment]
This was added in https://github.com/mapbox/mapbox-gl-native/pull/8225 that has landed on the `release-ios-v3.5.0-android-v5.0.0` release branch and will be in the next iOS 3.5.0 beta 3 release.
