### ISSUE TITLE
Bundle constants aren't prefixed in MapboxConstants

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8016]
There are situations that a user could save a key inside his Activity bundle with the same value as one of ours keys in `MapboxConstants`. This could result in overwriting our saved state and thus we would be unable to restore our state correctly. To avoid such issues we should prefix the constant values ,as we have been doing for our resources, with a unique mapbox prefix. 

cc @mapbox/android

**Comment by cammace** [comment]
We should probably do the same in mapbox-java right @zugaldia?

**Comment by zugaldia** [comment]
@cammace Looks like we're good on the MAS side: https://github.com/mapbox/mapbox-java/blob/master/mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/constants/TelemetryConstants.java#L35-L40
