### ISSUE TITLE
Map not showing for several hours

### ISSUE THREAD

**Issue by erifa** [mapbox/mapbox-gl-native#8019]
Description:
Map is not showing for several hours in both the released app and when I create a test build with Xcode. Sometimes the map is showing again, but most of the time the map is not showing. The access token appears to be correct.

Platform: iOS
Mapbox SDK version: 3.3.1 (via Fabric)

Steps to trigger behavior:
 1. Open map 

Expected behavior:
Map showing. 

Actual behavior:
Map not showing.

Debug printout:
[Style]: Failed to load source composite: HTTP status code 401.

Code: 
mapView.styleURL = MGLStyle.lightStyleURL(withVersion: 9)

**Comment by captainbarbosa** [comment]
Thanks for providing a detailed report! This is a known issue currently affecting our platform - please see our [status page](http://status.mapbox.com/) for more details.
