### ISSUE TITLE
Build failure on android/mips-64 related to system zlib

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-gl-native#802]
Ticket to track this build failure we're seeing on travis/master:

```
/android/mapbox-gl-native/mason_packages/android-mips-64-21/zlib/system/lib/libz.so: error adding symbols: File in wrong format
clang35++: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [out/Release/obj.target/android/libmapbox-gl.so] Error 1
make[1]: Leaving directory `/android/mapbox-gl-native/build/android/mips-64'
```

**Comment by ljbade** [comment]
This indicates to me that different ABIs (perhaps host system libs) are getting mixed with the Android compiled libs.

**Comment by kkaefer** [comment]
Seeing this too locally. Not sure about different ABIs being mixed; all of the other builds work just fine.

**Comment by kkaefer** [comment]
Actually, it looks like mips-64 tries to link the mips 32 bit libs:

```
/Users/kkaefer/Code/gl/native/mason_packages/android-mips-64-21/zlib/system/lib/libz.so: ELF 32-bit LSB shared object, MIPS, MIPS32 version 1 (SYSV), dynamically linked, with unknown capability 0xf41 = 0x756e6700, with unknown capability 0x70100 = 0x5040000, not stripped
```

**Comment by kkaefer** [comment]
I might interpret the output of file wrong, but it looks like the NDK ships with 32 bit .so files rather than 64 bit .so files in the mips64 sysroot.

**Comment by jfirebaugh** [comment]
The build used to be green on mips-64. What changed to break it? Can we revert it?

**Comment by ljbade** [comment]
Hmm, that is interesting @kkaefer. Maybe I need to take a closer look at it.

**Comment by ljbade** [comment]
@kkaefer is the NDK sysroot being built correctly? Perhaps it is copying the wrong libs.

**Comment by kkaefer** [comment]
I thought that too, but the original download contained the wrong binaries

**Comment by ljbade** [comment]
@kkaefer say what

**Comment by springmeyer** [comment]
I think I've gotten to the bottom of this. The Mips android toolchain seems to ship with both 32 bit and 64 bit binaries. The 32 bit ones are at `sysroot/usr/lib/libz.so` while the 64 bit ones are at `sysroot/usr/lib64/libz.so`. This worked before because mason was not even trying to provide the correct paths for android (and so the compiler toolchain was defaulting to its internal paths).

**Comment by ljbade** [comment]
@springmeyer can you check for lib64 on the other ABIs? Particularly x86-64

**Comment by ljbade** [comment]
@springmeyer can you check for lib64 on the other ABIs? Particularly x86-64

**Comment by springmeyer** [comment]
confirmed that this will be fixed (https://travis-ci.org/mapbox/mapbox-gl-native/builds/49406232) by fixes upstream in mason to the `zlib-system` package. So, I'll update both of those now and close this up when I'm done.

**Comment by springmeyer** [comment]
fixed by merging https://github.com/mapbox/mason/pull/66
