### ISSUE TITLE
Strange gap when using offsets

### ISSUE THREAD

**Issue by maitl** [mapbox/mapbox-gl-native#8028]
When I set a y-offset at the buildings-layer greater than 8px I get a gap in my map, which (i think) goes along the boarder of the map tiles.

Does anyone know how to prevent this problem?

![mapbox](https://cloud.githubusercontent.com/assets/14168596/22854896/01791a66-f077-11e6-8a49-a1662d709d77.png)

**Comment by boundsj** [comment]
Hi @maitl this GitHub repo is where we develop the Mapbox native SDKs. For questions about other tools like Mapbox Studio and general support queries, please use https://www.mapbox.com/help and contact support using the button at the bottom of that page.
