### ISSUE TITLE
MarkerView disappear after update position in Android

### ISSUE THREAD

**Issue by dickyleehk** [mapbox/mapbox-gl-native#8032]
**Platform:** Android
**Mapbox SDK version:** release-android-v4.2.2

### Steps to trigger behavior

 1. Add a MarkerView on a random position.
 2. Move the map to show the MarkerView on map.
 3. Move the map a little bit away from the MarkerView ( Cannot see the MarkerView create at 1 )
 4. Update the MarkerView position to a visible position ( Visible in current camera position )

### Expected behavior
The MarkerView show at the new position.

### Actual behavior

First add the MarkerView at this position
![screenshot_20170213-155648](https://cloud.githubusercontent.com/assets/13723900/22875537/436f7d8e-f207-11e6-989c-41906f8057c0.png)

After update the position of MarkerView, it disappear
![screenshot_20170213-155712](https://cloud.githubusercontent.com/assets/13723900/22875510/19b4f3e8-f207-11e6-813a-c5015d4196a4.png)

But:
1. if the bounding box of the camera include the last position of the MarkerView, the MarkerView show on the updated position.
![screenshot_20170213-155721](https://cloud.githubusercontent.com/assets/13723900/22875519/26a020fa-f207-11e6-9972-67a59761f221.png)

2. when camera move away from the last position, MarkerView disappear
![screenshot_20170213-160552](https://cloud.githubusercontent.com/assets/13723900/22875521/2a4d95ac-f207-11e6-9172-b535689c4537.png)

Here is the code  I added in the MarkerViewActivity:

On the top of the class:
`private MarkerView marker;`

Inside the onMapReadyCallBack:
`mapboxMap.setOnMapClickListener(new MapboxMap.OnMapClickListener() {
                    @Override
                    public void onMapClick(@NonNull LatLng point) {

                        if (marker != null) {
                            marker.setPosition(point);
                        }else{
                            MarkerViewOptions options = new MarkerViewOptions();
                            options.position(point);
                            options.icon(IconFactory.getInstance(MarkerViewActivity.this).fromResource(R.drawable.ic_circle));
                            options.anchor(0.5f, 0.5f);
                            marker =
                                    MarkerViewActivity.this.mapboxMap.addMarker(options);
                        }
                    }
                });`

Is there any quick solution to fix it or am I doing it wrong?

**Comment by tobrun** [comment]
@dickyleehk thank you for the detailed report, it seems that the MarkerViews aren't invalidated correctly when the initial MarkerView wasn't found in the viewport. For a workaround what you could try doing is manually invoking `MarkerViewManager#scheduleInvalidateMarkerViewsInBounds`. This should trigger an update and draw the MarkerView.

**Comment by dickyleehk** [comment]
@tobrun 
Thanks for the answer, but I cannot found a method with name "scheduleInvalidateMarkerViewsInBounds", what I found is this method inside the MarkerViewManager
`public void scheduleViewMarkerInvalidation() {
        if (!markerViewAdapters.isEmpty()) {
            long currentTime = SystemClock.elapsedRealtime();
            if (currentTime < viewMarkerBoundsUpdateTime) {
                return;
            }
            invalidateViewMarkersInVisibleRegion();
            viewMarkerBoundsUpdateTime = currentTime + 250;
        }
    }`

Do you mean that I should add this line
`mapboxMap.getMarkerViewManager().scheduleViewMarkerInvalidation();`
after this line?
`marker.setPosition(point);`

I try to add it after set position, but it seems doesn't help...
