### ISSUE TITLE
Crash when download offline pack

### ISSUE THREAD

**Issue by phucnd0604** [mapbox/mapbox-gl-native#8045]
im using the offline pack in an offline map feature but after download and resume i get this crash log

libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Malformed offline region definition

version 3.4
 1. download a pack
 2. pause
 3. resume pack

**Comment by nitrag** [comment]
Can you post some sample code? It's working fine for me.

**Comment by friedbunny** [comment]
Closing, but if this is still an issue feel free to post more information and we’ll reopen.

**Comment by jfirebaugh** [comment]
It means the offline database is corrupted. Can we have the user send us their database?

**Comment by boundsj** [comment]
Unfortunately the db would be on an end user device so we don't have access to it. We've not been able to reproduce locally yet.

**Comment by jfirebaugh** [comment]
We'll need a database to be able to diagnose this.
