### ISSUE TITLE
Android: Remove SQLite library

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#8048]
In https://github.com/mapbox/mapbox-gl-native/issues/2856, we removed cURL in favor of native Android APIs. However, we're still using a compiled version of SQLite, since the SQLite library that ships with Android is inaccessible and only exposed in Java.

There are two ways to accomplish this:
- Implement the low-level API ([`sqlite3.hpp`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/default/sqlite3.hpp) with a backend that uses Ithe Java API calls
- Implement the [`OfflineDatabase`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/default/mbgl/storage/offline_database.hpp) object in Java

#2356

**Comment by kkaefer** [comment]
I got started on implementing the low-level API, but the Java bindings are a little overengineered and it doesn't seem to be possible to replicate the interface we're using in `sqlite3.hpp` with the Java bindings without massive changes. That leaves implementing `OfflineDatabase` as the only alternative. I'm not feeling super good about adding a second implementation that needs to maintain parity. Thoughts @jfirebaugh?

**Comment by kkaefer** [comment]
For reference, progress stored in https://github.com/mapbox/mapbox-gl-native/tree/8048-android-sqlite, but I don't think it's viable as per the comment above.

**Comment by jfirebaugh** [comment]
If using Java bindings for SQLite isn't viable, then I recommend we simply stick with the current implementation.
