### ISSUE TITLE
'make apackage' does not generate proper aar file for Distributing Mapbox GL Native for Android

### ISSUE THREAD

**Issue by guruduttstay** [mapbox/mapbox-gl-native#8050]
**Platform: Android **
**Mapbox SDK version: Latest source code from git repo **

### Steps to trigger behavior

I am generating '.aar' file for using it in my project.

 1. git clone https://github.com/mapbox/mapbox-gl-native.git
 2. Do all necessary support installation for e.g. brew, make, node, openssl etc
 3. make (in root)
 4. make apackage
 5. This generate a aar file at : platform/android/MapboxGLAndroidSDK/build/outputs/aar/MapboxGLAndroidSDK-release.aar
6. copy this aar file to your project and include it to gradle
     compile(name: 'MapboxGLAndroidSDK-release', ext: 'aar')

### Expected behavior

It should work similar to 
```
 compile('com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.1@aar') {
        transitive = true
    }

```

### Actual behavior
It gives several errors for e.g. 
Error:(19) No resource identifier found for attribute 'style_url' in package ‘com.mytest.maptest'

Code looks like in layout 

```
 <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapview"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        mapbox:style_url="@string/style_mapbox_streets" />

```

Output for 'make' command looks like : [link](https://www.dropbox.com/s/tg1gwqdesf50cun/make.output.txt?dl=0)

Output for 'make apackage' looks like : [link](https://www.dropbox.com/s/i156r6w8w6u3iep/makeAPackage.success.txt?dl=0)

and AAR file : [link](https://www.dropbox.com/s/xuycq3us1s3rc4r/MapboxGLAndroidSDK-release.aar?dl=0)

Am I doing something wrong ?

Thank you in advance for your help and answer

**Comment by guruduttstay** [comment]
Hi @tobrun 
Thank you for adding labels 

I just created new project with single activity to make sure it is issue and found it same issue 

If I stop adding mapbox parameters via layout and add tocken from activity onCreate 

` MapboxAccountManager.start(this, getString(R.string.access_token));
`

it also give error 

![screen shot 2017-02-15 at 08 45 10](https://cloud.githubusercontent.com/assets/3405738/22964951/6d615afe-f35b-11e6-94ec-018b9347f635.png)

**Comment by tobrun** [comment]
@guruduttstay I'm starting to see what is going on, since the 4.2.1 release we are working towards a 5.0.0 release that changes the API drastically. More information in this [upgrade guide](https://github.com/mapbox/mapbox-gl-native/wiki/Android-4.x-to-5.0-update).

**Comment by guruduttstay** [comment]
Thank you @tobrun for quick response :)

I am going through upgrade guide just saw :)

![screen shot 2017-02-15 at 09 34 26](https://cloud.githubusercontent.com/assets/3405738/22966336/134a777e-f362-11e6-88be-b02fa67ae03b.png)

**Comment by guruduttstay** [comment]
hmm.... looks like I am in wrong branch (master) :(

**Comment by guruduttstay** [comment]
![screen shot 2017-02-15 at 10 45 14](https://cloud.githubusercontent.com/assets/3405738/22968800/2e658346-f36c-11e6-8b16-277aca867cf4.png)

**Comment by tobrun** [comment]
I'm thinking you are hitting [this](http://stackoverflow.com/questions/29857141/using-aar-noclassdeffounderror-but-class-exists-and-is-dexed) issue.

**Comment by guruduttstay** [comment]
Just rebuilt aar file with fresh clone still same issue 

dependencies  looks like

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    compile(name: 'MapboxGLAndroidSDK-release', ext: 'aar') {
        transitive = true
    }

    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    compile 'com.android.support:appcompat-v7:25.1.0'

/*    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.0-beta.1@aar') {
        transitive = true
    }
*/
    compile('com.mapbox.mapboxsdk:mapbox-android-services:1.3.1@aar') {
        transitive = true
    }

    testCompile 'junit:junit:4.12'
}

```

MainActivity 

```
public class MainActivity extends AppCompatActivity {
    private MapView mapView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Mapbox.getInstance(this, getString(R.string.access_token));

        setContentView(R.layout.activity_main);

        mapView = (MapView) findViewById(R.id.mapview);
        mapView.onCreate(savedInstanceState);
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {
                // Customize map with markers, polylines, etc.
            }
        });

    }
```

![screen shot 2017-02-15 at 13 17 44](https://cloud.githubusercontent.com/assets/3405738/22974120/384e5706-f381-11e6-94b2-14070100554c.png)




NB : Following setting works fine 

```
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.0-beta.1@aar') {
        transitive = true
    }

```


So it is either not building proper AAR file or am I missing some step while preparing AAR file  :(

**Comment by tobrun** [comment]
I think this is not an issue from your or our end. 
This is afaik an issue with dependency resolvement of gradle/maven.

**Comment by guruduttstay** [comment]
I am stuck :(

**Comment by tobrun** [comment]
I think setting up a local maven as in this [SO](http://stackoverflow.com/questions/29857141/using-aar-noclassdeffounderror-but-class-exists-and-is-dexed) should work though.

**Comment by tobrun** [comment]
@guruduttstay, @zugaldia noted to be using a similar setup in this [project](https://github.com/mapbox/mapbox-telemetry-android/blob/master/telemetry/app/build.gradle#L25-L28). You will need to include the depencencies from build.gradle from Android SDK manually as well. That should resolve your issue.

**Comment by guruduttstay** [comment]
Thank you @tobrun 

It did for me :)

I copied from current master branch so it may change in future but for now my test applications build gradle looks like 

NB : This is default app/project with single activity created from Android studio 

```
apply plugin: 'com.android.application'

ext {
    supportLibVersion = '25.1.0'
}

dependencies {

    compile fileTree(dir: 'libs', include: ['*.jar'])

    compile(name: 'MapboxGLAndroidSDK-release', ext: 'aar') {
        transitive = true
    }

    compile "com.android.support:support-annotations:${supportLibVersion}"
    compile "com.android.support:support-v4:${supportLibVersion}"
    compile "com.android.support:design:${supportLibVersion}"
    compile 'com.squareup.okhttp3:okhttp:3.5.0'
    compile 'com.mapzen.android:lost:2.0.0'
    compile 'com.jakewharton.timber:timber:4.3.1'

    // Mapbox Android Services (GeoJSON support)
    compile('com.mapbox.mapboxsdk:mapbox-java-geojson:2.0.0-beta.1@jar') {
        transitive = true
    }

    // Mapbox Android Services (Telemetry support)
    compile('com.mapbox.mapboxsdk:mapbox-android-telemetry:2.0.0-beta.1@aar') {
        transitive = true
    }

    compile 'com.android.support:appcompat-v7:25.1.0'
    testCompile 'junit:junit:4.12'
}

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    repositories {
        mavenCentral()
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

        }
    }
}

```
