### ISSUE TITLE
[ios SDK version:3.4.0]Can not tap annotationview sometimes

### ISSUE THREAD

**Issue by iseeicando** [mapbox/mapbox-gl-native#8059]
1. Add a new annotation which coincide with an old annotation
2.Remove the new added annotation
3.After step 2 ,the old annotationview cannot be selected forever

**Comment by fabian-guerra** [comment]
Hi @iseeicando,
I was not able to reproduce this issue. Could you please provide a sample project or code snippet that help us reproduce it?
