### ISSUE TITLE
tiles flicker while zooming

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-native#806]
From the screenshots it looks like a clipping issue. 7/34/39 should be getting clipped to it's tile boundaries but it isn't. The water is also lighter. I think this is caused by the tile being drawn over it's parent tile.

This happens pretty often. There are usually one or two fast flickers when I zoom in quickly.

Any ideas what this could be @kkaefer?

Three consecutive frames:

![vlcsnap-2015-02-03-10h02m38s238](https://cloud.githubusercontent.com/assets/1421652/6026045/1076d06c-ab8c-11e4-920d-97c0d99f3ac0.png)
![vlcsnap-2015-02-03-10h02m52s239](https://cloud.githubusercontent.com/assets/1421652/6026044/107593dc-ab8c-11e4-9d78-e4ea96914578.png)
![vlcsnap-2015-02-03-10h02m57s240](https://cloud.githubusercontent.com/assets/1421652/6026046/1077965a-ab8c-11e4-83e1-b221d6fee2fa.png)

**Comment by bleege** [comment]
Just tried this with latest from [`master`](https://github.com/mapbox/mapbox-gl-native/commits/4fd4351a2fafc8c4972f6fd0a57805869700ab1b) on my iPhone 5s running iOS 8.1.3 and **didn't see the issue**.

Will test next on OS X.

**Comment by bleege** [comment]
Tested using `asset://styles/outdoors-v7.json` on OS X using the same [`master`](https://github.com/mapbox/mapbox-gl-native/commits/4fd4351a2fafc8c4972f6fd0a57805869700ab1b) code.  Didn't see the issue either.

Will defer to @ansis to confirm if it's still a problem.

**Comment by ansis** [comment]
Yes, I'm still seeing this on master. The flicker is super fast but it's still there. If I zooming in very quickly on water I still see very short flashes of the background colour.

**Comment by bleege** [comment]
Thanks for confirming @ansis!  What platform / device are you seeing this on?

**Comment by ansis** [comment]
I'm seeing this on osx with both Debug and Release buildtypes

**Comment by bleege** [comment]
Ah... ok I see what you're referring to now @ansis and can confirm that it does exist in iOS Simulator too.  That said I still don't see it for either Bright nor Outdoors styles on my iPhone 5S.

Perhaps the best way forward is to see if @incanus and @1ec5 experience this on their iPhones / iPads too.  If they do see this issue we'll leave this on the iOS Beta Milestone, but if they don't we can remove it from Milestone and leave the issue open for @kkaefer to resolve at a later date.

Does this plan work for you @ansis?

**Comment by ansis** [comment]
I removed it from the milestone because I don't think it's that significant and fix will probably be fairly time consuming.

**Comment by bleege** [comment]
:+1: thanks for clarifying @ansis!

**Comment by kkaefer** [comment]
Seeing this too.

**Comment by incanus** [comment]
Is this still relevant?
