### ISSUE TITLE
[ios / Swift] Coerce zoom stops and exponential,interval stops to [Float:...]

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-native#8068]
While working on https://github.com/mapbox/mapbox-gl-native/pull/8026 I’ve encountered an issue w/ the Swift bridging for style function stops:
 - (a) in core, zoom stops & interval and exponential property stops are always `float`.
 - (b) in Swift, if you do `let stops = [ 0: value1, 10: value2 ]` and use those stops to set a style function value, then your stops are `[Int:MGLStyleValue]`.
 - (c) however, due to (a), if you then try to _get_ the stops back out of the layer, e.g. `myLayer.circleColor.stops`, you end up with `[Float:MGLStyleValue]`.  Because the declared type of those stops is `[AnyHashable:Any]`, it'll let you subscript them with an int: so, for instance, you could do `myLayer.color.stops[0]`, and, confusingly, you’d get `nil`.

Chatted with @1ec5 about this, and it seems like, since we aren't actually shipping Swift code in our SDK, there isn't a clear/immediate path to resolving this.  cc @boundsj

**Comment by 1ec5** [comment]
Until we can ship Swift code in this library, we could create a separate helper library that takes care of Swift-only issues: mapbox/mapbox-swift-core#3.
