### ISSUE TITLE
Upgrading gyp

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-gl-native#807]
@kkaefer mentioned wanting to pull in https://codereview.chromium.org/385963006/. This sounds good to me. I can't see any reason not to track upstream gyp (as long as we test that changes don't break travis). This ticket is to track upgrading the vendored gyp we use.

My sense is that once master is fully green we should:

 - fork latest gyp to a new github repo at mapbox/gyp and apply the few patches we need.
 - consider pulling in our gyp version via a submodule

As far as the patches we need to carry, I think the main one is to help linux linking order (#519):

```diff
diff --git a/deps/gyp/pylib/gyp/generator/make.py b/deps/gyp/pylib/gyp/generator/make.py
index b6f766d..0b515bc 100644
--- a/deps/gyp/pylib/gyp/generator/make.py
+++ b/deps/gyp/pylib/gyp/generator/make.py
-cmd_link = $(LINK.$(TOOLSET)) $(GYP_LDFLAGS) $(LDFLAGS.$(TOOLSET)) -o $@ -Wl,--start-group $(LD_INPUTS) -Wl,--end-group $(LIBS)
+cmd_link = $(LINK.$(TOOLSET)) -Wl,--start-group $(GYP_LDFLAGS) $(LDFLAGS.$(TOOLSET)) -o $@ $(LD_INPUTS) $(LIBS) -Wl,--end-group
```

But before upgrading I'd take a quick look through the history to catch any other changes we might want to keep: https://github.com/mapbox/mapbox-gl-native/commits/master/deps/gyp/

**Comment by ljbade** [comment]
Good idea, we should treat gyp like everything else.

I might even be able to use the submodule in the boringssl mason branch.

**Comment by springmeyer** [comment]
forked to https://github.com/mapbox/gyp. Going to enable travis, but synchronization is hanging:

![screen shot 2015-02-03 at 2 17 25 pm](https://cloud.githubusercontent.com/assets/20300/6030867/6f4ae81c-abaf-11e4-9e13-f47f23007ff9.png)

So I've emailed travis support and will pick this back up later on.

**Comment by springmeyer** [comment]
This is stale, so I'm going to close after a few remarks.

1) It would still be worthwhile to upgrade our bundled gyp version assuming we find a reason. The reason above was to try to support xcode schemes so that we don't need to re-add the MAPBOX token each time you do a full build clean. However it appears the patch to gyp to support schemes was never accepted into mainline gyp, so just upgrading would not get this functionality. Perhaps we should find a different way to pass in the token, like using an xcconfig. - refs #749 

2) https://github.com/mapbox/gyp exists but not had a chance to add travis or keep up to date. Will keep in mind doing this, but its not enough to keep this ticket open.
