### ISSUE TITLE
Rename MGLStyleConstantValue to MGLConstantStyleValue

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8072]
With the exception of the class prefix, a class name should read naturally in English. “Style constant value” sounds awkward, and MGLStyleConstantValue is inconsistent with MGLStyleFunction and MGL*StyleFunction. Let’s rename MGLStyleConstantValue to MGLConstantStyleValue and leave a compatibility alias for MGLStyleConstantValue.

/cc @jfirebaugh @boundsj

**Comment by boundsj** [comment]
Fixed by https://github.com/mapbox/mapbox-gl-native/pull/8090 that was merged into the `release-ios-v3.5.0-android-v5.0.0` branch
