### ISSUE TITLE
[core] Return NONE for invalid color strings in `Color::parse()`

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-native#8075]
[Color::parse](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/util/color.cpp#L9) (via [CSSColorParser::parse()](https://github.com/mapbox/mapbox-gl-native/blob/master/src/csscolorparser/csscolorparser.cpp#L226)) defaults to black for invalid / unparseable color strings.  This prevents us from correctly evaluating property functions for color values in the case where the property value is an invalid color string -- see https://github.com/mapbox/mapbox-gl-js/issues/4150

**Comment by jfirebaugh** [comment]
I'd be fine with modifying our vendored copy of CSSColorParser to support this.

**Comment by kkaefer** [comment]
Transferred the repo to https://github.com/mapbox/css-color-parser-cpp
