### ISSUE TITLE
Crash on Zoom - Android SDK 5.0.0-beta.1

### ISSUE THREAD

**Issue by aqsous** [mapbox/mapbox-gl-native#8079]
**Platform: Android**
**Mapbox SDK version: 5.0.0-beta.1**

### Steps to trigger behavior

 1. Open Example project on Android (5.0.1 or 7.0 emulator)
 2. Zoom out/in

### Expected behavior
Zoom
### Actual behavior
**Crashes** with log: 

`A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 5615 (com.example)
        [ 02-16 11:18:57.275  1237: 1237 W/         ]
        debuggerd: handling request: pid=5615 uid=10110 gid=10110 tid=5615`

**Comment by tobrun** [comment]
@aqsous thank you for trying out the beta1! would you be able to post the full stacktrace?

**Comment by aqsous** [comment]
@tobrun Here you go: 


02/16 12:36:29: Launching app
$ adb push /Users/al-adhamal-qsous/Documents/AndroidStudio/MyApplication/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.adham.myapplication
$ adb shell pm install -r "/data/local/tmp/com.adham.myapplication"
Success


$ adb shell am start -n "com.adham.myapplication/com.adham.myapplication.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: com.adham.myapplication | com.adham.myapplication.test
Waiting for application to come online: com.adham.myapplication | com.adham.myapplication.test
Connecting to com.adham.myapplication
I/art: Debugger is active
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
Connected to the target VM, address: 'localhost:8689', transport: 'socket'
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1445)
I/InstantRun: Instant Run Runtime started. Android package is com.adham.myapplication, real application class is com.adham.myapplication.App.
I/art: Do partial code cache collection, code=30KB, data=19KB
I/art: After code cache collection, code=21KB, data=15KB
I/art: Increasing code cache capacity to 128KB
I/art: Do partial code cache collection, code=58KB, data=44KB
I/art: After code cache collection, code=57KB, data=44KB
I/art: Increasing code cache capacity to 256KB
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/art: Thread[1,tid=7956,Native,Thread*=0x7c225ae95a00,peer=0x750ed000,"main"] recursive attempt to load library "/data/app/com.adham.myapplication-1/lib/x86_64/libmapbox-gl.so"
I/art: Thread[1,tid=7956,Native,Thread*=0x7c225ae95a00,peer=0x750ed000,"main"] recursive attempt to load library "/data/app/com.adham.myapplication-1/lib/x86_64/libmapbox-gl.so"
I/art: Thread[1,tid=7956,Native,Thread*=0x7c225ae95a00,peer=0x750ed000,"main"] recursive attempt to load library "/data/app/com.adham.myapplication-1/lib/x86_64/libmapbox-gl.so"
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
D/mbgl: {m.myapplication}[JNI]: nativeCreate
D/mbgl: {m.myapplication}[JNI]: nativeInitializeDisplay

        [ 02-16 12:36:38.782  7956: 7956 D/         ]
        HostConnection::get() New Host Connection established 0x7c22511d2d00, tid 7956


        [ 02-16 12:36:38.795  7956: 7956 W/         ]
        Process pipe failed
W/mbgl: {m.myapplication}[Android]: Running SDK in emulator!
D/mbgl: {m.myapplication}[JNI]: nativeInitializeContext
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1

                  [ 02-16 12:36:38.885  7956: 8256 D/         ]
                  HostConnection::get() New Host Connection established 0x7c22419ea1e0, tid 8256
D/mbgl: {m.myapplication}[JNI]: nativeViewResize
D/mbgl: {m.myapplication}[JNI]: nativeCreateSurface
E/EGL_emulation: tid 8256: eglSurfaceAttrib(1146): error 0x3009 (EGL_BAD_MATCH)
W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x7c22418e8d40, error=EGL_BAD_MATCH
D/mbgl: {m.myapplication}[JNI]: nativeFramebufferResize
I/art: Do full code cache collection, code=124KB, data=90KB
I/art: After code cache collection, code=94KB, data=59KB
W/mbgl: {m.myapplication}[OpenGL]: Not using Vertex Array Objects
I/art: Do partial code cache collection, code=110KB, data=78KB
I/art: After code cache collection, code=109KB, data=77KB
I/art: Increasing code cache capacity to 512KB
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 7956 (m.myapplication)

        [ 02-16 12:36:47.801  1237: 1237 W/         ]
        debuggerd: handling request: pid=7956 uid=10076 gid=10076 tid=7956
Disconnected from the target VM, address: 'localhost:8689', transport: 'socket'

**Comment by aqsous** [comment]
`
02-16 12:41:45.976 8416-8416/? I/art: Not late-enabling -Xcheck:jni (already on)
02-16 12:41:45.976 8416-8416/? W/art: Unexpected CPU variant for X86 using defaults: x86_64
02-16 12:41:46.029 8416-8423/? I/art: Debugger is no longer active
02-16 12:41:46.029 8416-8423/? I/art: Starting a blocking GC Instrumentation
02-16 12:41:47.263 8416-8416/com.adham.myapplication W/ActivityThread: Application com.adham.myapplication is waiting for the debugger on port 8100...
02-16 12:41:47.265 8416-8416/com.adham.myapplication I/System.out: Sending WAIT chunk
02-16 12:41:47.979 8416-8423/com.adham.myapplication I/art: Debugger is active
02-16 12:41:48.070 8416-8416/com.adham.myapplication I/System.out: Debugger has connected
02-16 12:41:48.070 8416-8416/com.adham.myapplication I/System.out: waiting for debugger to settle...
02-16 12:41:48.270 8416-8416/com.adham.myapplication I/System.out: waiting for debugger to settle...
02-16 12:41:48.473 8416-8416/com.adham.myapplication I/System.out: waiting for debugger to settle...
02-16 12:41:48.682 8416-8416/com.adham.myapplication I/System.out: waiting for debugger to settle...
02-16 12:41:48.885 8416-8416/com.adham.myapplication I/System.out: waiting for debugger to settle...
02-16 12:41:49.088 8416-8416/com.adham.myapplication I/System.out: waiting for debugger to settle...
02-16 12:41:49.290 8416-8416/com.adham.myapplication I/System.out: waiting for debugger to settle...
02-16 12:41:49.491 8416-8416/com.adham.myapplication I/System.out: debugger has settled (1435)
02-16 12:41:49.514 8416-8416/com.adham.myapplication I/InstantRun: Instant Run Runtime started. Android package is com.adham.myapplication, real application class is com.adham.myapplication.App.
02-16 12:41:49.862 8416-8416/com.adham.myapplication D/NetworkSecurityConfig: No Network Security Config specified, using platform default
02-16 12:41:49.937 8416-8416/com.adham.myapplication I/art: Thread[1,tid=8416,Native,Thread*=0x7c225ae95a00,peer=0x750ed000,"main"] recursive attempt to load library "/data/app/com.adham.myapplication-1/lib/x86_64/libmapbox-gl.so"
02-16 12:41:49.938 8416-8416/com.adham.myapplication I/art: Thread[1,tid=8416,Native,Thread*=0x7c225ae95a00,peer=0x750ed000,"main"] recursive attempt to load library "/data/app/com.adham.myapplication-1/lib/x86_64/libmapbox-gl.so"
02-16 12:41:49.940 8416-8416/com.adham.myapplication I/art: Thread[1,tid=8416,Native,Thread*=0x7c225ae95a00,peer=0x750ed000,"main"] recursive attempt to load library "/data/app/com.adham.myapplication-1/lib/x86_64/libmapbox-gl.so"
02-16 12:41:50.150 8416-8416/com.adham.myapplication W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
02-16 12:41:50.358 8416-8421/com.adham.myapplication I/art: Do partial code cache collection, code=26KB, data=18KB
02-16 12:41:50.359 8416-8421/com.adham.myapplication I/art: After code cache collection, code=26KB, data=18KB
02-16 12:41:50.359 8416-8421/com.adham.myapplication I/art: Increasing code cache capacity to 128KB
02-16 12:41:50.363 8416-8416/com.adham.myapplication D/mbgl: {m.myapplication}[JNI]: nativeCreate
02-16 12:41:50.463 8416-8416/com.adham.myapplication D/mbgl: {m.myapplication}[JNI]: nativeInitializeDisplay
                                                             
                                                             [ 02-16 12:41:50.484  8416: 8416 D/         ]
                                                             HostConnection::get() New Host Connection established 0x7c2251191b80, tid 8416
                                                             
                                                             
                                                             [ 02-16 12:41:50.495  8416: 8416 W/         ]
                                                             Process pipe failed
02-16 12:41:50.503 8416-8416/com.adham.myapplication W/mbgl: {m.myapplication}[Android]: Running SDK in emulator!
02-16 12:41:50.504 8416-8416/com.adham.myapplication D/mbgl: {m.myapplication}[JNI]: nativeInitializeContext
02-16 12:41:50.592 8416-8492/com.adham.myapplication I/OpenGLRenderer: Initialized EGL, version 1.4
02-16 12:41:50.592 8416-8492/com.adham.myapplication D/OpenGLRenderer: Swap behavior 1
                                                                       
                                                                       [ 02-16 12:41:50.593  8416: 8492 D/         ]
                                                                       HostConnection::get() New Host Connection established 0x7c2251191d60, tid 8492
02-16 12:41:50.606 8416-8416/com.adham.myapplication D/mbgl: {m.myapplication}[JNI]: nativeViewResize
02-16 12:41:50.723 8416-8416/com.adham.myapplication D/mbgl: {m.myapplication}[JNI]: nativeCreateSurface
02-16 12:41:50.753 8416-8492/com.adham.myapplication E/EGL_emulation: tid 8492: eglSurfaceAttrib(1146): error 0x3009 (EGL_BAD_MATCH)
02-16 12:41:50.753 8416-8492/com.adham.myapplication W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x7c2241ab7740, error=EGL_BAD_MATCH
02-16 12:41:50.793 8416-8416/com.adham.myapplication D/mbgl: {m.myapplication}[JNI]: nativeFramebufferResize
02-16 12:41:51.765 8416-8416/com.adham.myapplication W/mbgl: {m.myapplication}[OpenGL]: Not using Vertex Array Objects
02-16 12:42:04.915 8416-8421/com.adham.myapplication I/art: Do partial code cache collection, code=61KB, data=43KB
02-16 12:42:04.915 8416-8421/com.adham.myapplication I/art: After code cache collection, code=61KB, data=43KB
02-16 12:42:04.915 8416-8421/com.adham.myapplication I/art: Increasing code cache capacity to 256KB
02-16 12:42:05.406 8416-8416/com.adham.myapplication A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 8416 (m.myapplication)
                                                             
                                                             [ 02-16 12:42:05.406  1237: 1237 W/         ]
                                                             debuggerd: handling request: pid=8416 uid=10076 gid=10076 tid=8416
`

**Comment by tobrun** [comment]
Confirming that I'm seeing this issue on master for x86 devices (emulator + genymotion).
Adding it to the `android-v5.0.0` milestone.

**Comment by tobrun** [comment]
The x86 didn't show any stacktraces that could be symbolicated but I was able to reproduce this using an arm-v7 emulator (zooming and panning) and was able to symbolicate the stacktrace to:

```
********** Crash dump: **********
Build fingerprint: 'Android/sdk_phone_armv7/generic:7.0/NYC/3245079:userdebug/test-keys'
pid: 2080, tid: 2080, name: pboxsdk.testapp  >>> com.mapbox.mapboxsdk.testapp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Stack frame #00 pc 00000000  <unknown>
Stack frame #01 pc 00190ec8  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::gl::ExtensionFunction<void (int, unsigned int const*)>::operator()(int, unsigned int const*) const at /home/tvn/Mapbox/mapbox-gl-native/build/android-arm-v7-9/Debug/../../../src/mbgl/gl/extension.hpp:36 (discriminator 4)
Stack frame #02 pc 00061080  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::Map::Impl::render(mbgl::View&) at /home/tvn/Mapbox/mapbox-gl-native/build/android-arm-v7-9/Debug/../../../src/mbgl/map/map.cpp:283 (discriminator 1)
Stack frame #03 pc 0015f37c  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::android::NativeMapView::render() at /home/tvn/Mapbox/mapbox-gl-native/build/android-arm-v7-9/Debug/../../../platform/android/src/native_map_view.cpp:170
Stack frame #04 pc 0004925c  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine (anonymous namespace)::nativeRender(_JNIEnv*, jni::jobject*, long long) at /home/tvn/Mapbox/mapbox-gl-native/build/android-arm-v7-9/Debug/../../../platform/android/src/jni.cpp:374
Stack frame #05 pc 0051ce2f  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (offset 0x4f3000)
```

**Comment by jfirebaugh** [comment]
It's a bug in 0bbc6b814cbec44be7026a0bac83d56e4d71a287.
