### ISSUE TITLE
mbgl::AnimationOptions with mbgl::Transform::moveBy

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8081]
I'm proposing altering `Transfrom::moveBy` to allow using `AnimationOptions`:

```cpp
//before
void moveBy(const ScreenCoordinate& offset, const Duration& = Duration::zero());

//after
void moveBy(const ScreenCoordinate& offset, const AnimationOptions& options);
```

This allows for bindings to provide a `mbgl::util::UnitBezier` as interpolator to achieve more natural `moveBy` transformations. On Android this would benefit the user experience around the fling gesture.

Current linear interpolated moveBy:

![ezgif com-video-to-gif 18](https://cloud.githubusercontent.com/assets/2151639/23022276/39dc45f4-f450-11e6-948f-4da69454cbec.gif)

With a circular ease out interpolation: 

![ezgif com-video-to-gif 16](https://cloud.githubusercontent.com/assets/2151639/23022336/8c107f70-f450-11e6-93fe-281384c54ecf.gif)

cc @jfirebaugh

**Comment by jfirebaugh** [comment]
👍
