### ISSUE TITLE
Geometric Operations

### ISSUE THREAD

**Issue by gmribas** [mapbox/mapbox-gl-native#8085]
Is there a way to execute geometric operations (intersection, union, etc) using the Mapbox Android SDK?
I know there is `Wagyu`, my C++/NDK skills are 0 though. 

I'm using **mapbox-android-sdk:5.0.0-SNAPSHOT**.

**Comment by jfirebaugh** [comment]
No, the Mapbox Android SDK does include an implementation of geometric boolean operations. We're considering ways in which we could provide this, but it would likely be done outside of the Mapbox GL SDKs.
