### ISSUE TITLE
Move static packaging script into an Xcode workflow

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-gl-native#8089]
In https://github.com/mapbox/mapbox-gl-native/pull/7773 we sidestepped an issue with packaging the iOS static build by updating the way libtool is informed about mason dependencies. 

Longer term, we should [move the packaging step into Xcode itself](https://github.com/mapbox/mapbox-gl-native/pull/7773#pullrequestreview-17513548) and come up with some way to [test the integration of the static build in an app on CI](https://github.com/mapbox/mapbox-gl-native/pull/7773#issuecomment-273730883).

cc @kkaefer @1ec5

**Comment by 1ec5** [comment]
> In #7773 we sidestepped an issue with packaging the iOS static build by updating the way libtool is informed about mason dependencies.

Is this line still relevant, now that #12808 vendors ICU instead of pulling it in through Mason?

https://github.com/mapbox/mapbox-gl-native/blob/66e95ac2ab6260654ba09b26e83591e3d4334c02/platform/ios/scripts/package.sh#L109

**Comment by kkaefer** [comment]
Nope, let's ⛏ it
