### ISSUE TITLE
strange panning behavior - map just stops

### ISSUE THREAD

**Issue by peterneubauer** [mapbox/mapbox-gl-native#8091]
**Platform:** Android
**Mapbox SDK version:** 4.2.2

### Steps to trigger behavior

 1. Check out the Mapillary Android code
 2. go to the maps view
 3. pan around behavior is like https://www.dropbox.com/s/mr5xmet3u2kk0hv/ScreenRecord_2017-02-17-11-09-27.mp4?dl=0

### Expected behavior
Map and location marker should pan and zoom

### Actual behavior
Only location marker layer is behaving right - the actual map layer just stops responding after a second or so.

**Comment by tobrun** [comment]
@peterneubauer is this issue specific to a device or are you seeing this on multiple devices?

**Comment by SIKV** [comment]
@tobrun I have this issues too. Android 6.0.1, Nexus 5.

**Comment by peterneubauer** [comment]
Seems to be working with latest 5.0.0-beta.3

**Comment by tobrun** [comment]
Thanks for validating @peterneubauer!
