### ISSUE TITLE
Missing POI icons

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#810]
Icons for POIs no longer appear on Android. The labels are still there.

![device-2015-02-04-132953](https://cloud.githubusercontent.com/assets/1215089/6034045/f2af7ef8-ac71-11e4-953c-96480a9a5dd2.png)

/cc @ansis @lbud

**Comment by ljbade** [comment]
![device-2015-02-16-192153](https://cloud.githubusercontent.com/assets/1215089/6222897/68c0a83a-b611-11e4-934b-1b633bf63d14.png)

@ansis Got this on my Nexus 7, might provide a clue. Possible shader bug.

**Comment by mb12** [comment]
This is similar to the following issue:

https://github.com/mapbox/mapbox-gl-native/issues/843

**Comment by ansis** [comment]
Assume this was fixed by https://github.com/mapbox/mapbox-gl-native/pull/843. @ljbade re-open if it wasn't.
