### ISSUE TITLE
how to store offline map in sqlite and load in map.

### ISSUE THREAD

**Issue by Bicubiciosdev** [mapbox/mapbox-gl-native#8106]
**Platform:ios
**Mapbox SDK version:**

### Steps to trigger behavior

 1. i will try your mapbox offline demo but i am creating game app like finding object in to the map.game is playing different country.so i want to need store different city map download and store to sqlite database but in demo i can not find which place datas are stored.so please help how can i solved.i tried mapbox-gl-native but i can not run successfull. this file missing  'mbgl/style/filter.hpp' file not found display error.

 2.in offline map possible to call didupdatelocation method?
 3.offline map is only used in open street or another type of map
waiting for your response

**Comment by jfirebaugh** [comment]
Hi @Bicubiciosdev. This issue tracker is for coordinating development of Mapbox GL, not for support. Please refer to our [documentation on offline](https://www.mapbox.com/help/mobile-offline/).
