### ISSUE TITLE
Error on build mapbox-ql-native on windows 10 with QT 5.8

### ISSUE THREAD

**Issue by Grubequai** [mapbox/mapbox-gl-native#8109]
I want to build mapbox-ql-native-master with qt 5.8 on a windows 10 system. I use cmake 3.7. During build with Cmakelists.txt I get the following error:

Can't find node-Cmake Cmakelists.txt.

**Comment by TheHobb247** [comment]
Common

**Comment by TheHobb247** [comment]
Common

**Comment by Grubequai** [comment]
Sorry, but I'm a newbie in this theme. Perhaps someone could give me a clue.
