### ISSUE TITLE
throw in destructor of RunLoop

### ISSUE THREAD

**Issue by joto** [mapbox/mapbox-gl-native#8114]
**Platform:** Linux Debian Testing
**Mapbox SDK version:** master

### Steps to trigger behavior

 1. Call `make glfw-app`

Compiled with GCC v6.3.0. Clang doesn't complain.

### Expected behavior

Compiles

### Actual behavior

error message:

    /home/sqrt/sw/mapbox/mapbox-gl-native/platform/default/run_loop.cpp:136:57: error: throw will always call terminate() [-Werror=terminate]
         throw std::runtime_error("Failed to close loop.");

Throws are not allowed in a destructor.

**Comment by kkaefer** [comment]
Are you seeing this exception being thrown? Or just the compiler warning?

**Comment by joto** [comment]
Just the compiler warning.
