### ISSUE TITLE
Is it possible to show roads in lower zoom levels

### ISSUE THREAD

**Issue by kimmobrunfeldt** [mapbox/mapbox-gl-native#8115]
This is more of a question. Is there a way to draw roads even in lower zoom levels?

Screenshots are from Mapbox Studio, but I'm trying to generate large map image with nodejs. I'm printing this huge image in the end as a poster. 

Zoom level <=5 shows:
<img width="882" alt="screenshot 2017-02-19 18 38 52" src="https://cloud.githubusercontent.com/assets/1232405/23104274/41fbe44e-f6d3-11e6-9fa5-a5a203b31721.png">

Zoom level 5.1 shows *some* roads, but not all. I would like to be able to draw all/most roads in the country even in the lower zoom levels. 

<img width="881" alt="screenshot 2017-02-19 18 38 59" src="https://cloud.githubusercontent.com/assets/1232405/23104324/3bfae742-f6d4-11e6-92c8-f8871f3554a2.png">

**Comment by jfirebaugh** [comment]
Hi @kimmobrunfeldt. Thanks for using Mapbox. The issue tracker is for coordinating the development of Mapbox GL via bug reports and feature requests. General questions such as this should be asked via [Mapbox Support](https://www.mapbox.com/help/).
