### ISSUE TITLE
MarkerViewOptions.anchor doesn't affect to OnMarkerClickListener

### ISSUE THREAD

**Issue by SIKV** [mapbox/mapbox-gl-native#8118]
**Platform: Android 6.0.1**
**Mapbox SDK version: 4.2.2**

### Steps to trigger behavior

 1. Add a **custom marker** to the map
```
 MarkerViewOptions markerViewOptions = new MarkerViewOptions()
                .position(location.getLatLng())
                .icon(icon)
                .title("Test")
                .anchor(0.5f, 1f)
                .snippet("Test");

map.addMarker(markerViewOptions)
```
 2. Set marker click listener

`map.setOnMarkerClickListener(...);`

 3. Perform click on a marker.

### Expected behavior

I can click on a whole marker. Using .anchor(0.5f, 1f).

### Actual behavior

It seems when I change an anchor it doesn't affect to OnMarkerClickListener.

**Comment by tobrun** [comment]
Thank you for reaching out, follow up ticket in #8159.
