### ISSUE TITLE
make xdocument/idocument fails

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#8119]
```
~/Code/gl/native ▶ make xdocument
OUTPUT= ./platform/macos/scripts/document.sh

Using config file /Users/kkaefer/Code/gl/native/platform/macos/jazzy.yml
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/config.rb:431:in `read_config_file': undefined method `safe_load' for Psych:Module (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/config.rb:393:in `parse_config_file'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/config.rb:341:in `parse!'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
make: *** [xdocument] Error 1
```

**Comment by friedbunny** [comment]
`Psych.safe_load()` appears to have been introduced in Ruby 2.1.0.

**Comment by friedbunny** [comment]
This broke in v0.7.4 with https://github.com/realm/jazzy/commit/b0e5c4b7cfa05c41d43feb3b3e2ca2c9efbcd410#diff-598546a0c342527401dade0e669b6772R431.

**Comment by friedbunny** [comment]
@kkaefer Ruby 2.0 has been deprecated [for a year](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/), so I think the probable outcome here will be that jazzy bumps their minimum version requirement to 2.1.0. Are you able to update your local ruby version?

**Comment by kkaefer** [comment]
@friedbunny yeah, I'm able to update it, but I also think there's value in being able to run the stock ruby version of the macOS Sierra to reduce setup hurdles.

**Comment by friedbunny** [comment]
> but I also think there's value in being able to run the stock ruby version of the macOS Sierra to reduce setup hurdles

Agreed. https://github.com/realm/jazzy/pull/748 will fix Ruby 2.0.0 support, but it may be a little while before that gets packaged.

**Comment by kkaefer** [comment]
I installed Ruby 2.4 via Homebrew, but now I'm seeing this error when running `make ipackage/iframework`:

```
/usr/local/lib/ruby/gems/2.4.0/gems/jazzy-0.7.4/lib/jazzy/config.rb:298:in `block in <class:Config>': unexpected return (LocalJumpError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/jazzy-0.7.4/lib/jazzy/config.rb:36:in `instance_exec'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jazzy-0.7.4/lib/jazzy/config.rb:36:in `set'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jazzy-0.7.4/lib/jazzy/config.rb:55:in `block in attach_to_option_parser'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/optparse.rb:1552:in `block in parse_in_order'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/optparse.rb:1538:in `catch'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/optparse.rb:1538:in `parse_in_order'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/optparse.rb:1532:in `order!'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/optparse.rb:1626:in `permute!'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/optparse.rb:1648:in `parse!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jazzy-0.7.4/lib/jazzy/config.rb:383:in `parse_command_line'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jazzy-0.7.4/lib/jazzy/config.rb:340:in `parse!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jazzy-0.7.4/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:22:in `load'
	from /usr/local/bin/jazzy:22:in `<main>'
make[1]: *** [idocument] Error 1
```

**Comment by friedbunny** [comment]
That’s fixed by https://github.com/realm/jazzy/pull/753. Workaround is to use Ruby 2.3.

**Comment by 1ec5** [comment]
(You can also check out realm/jazzy@8c089f000f4858d0f9cc8972a86412432eb74be3 locally and edit document.sh to point to jazzy/bin/jazzy.)

**Comment by kkaefer** [comment]
lol

**Comment by friedbunny** [comment]
[jazzy 0.7.5 is available](https://github.com/realm/jazzy/releases/tag/v0.7.5) and fixes this issue.
