### ISSUE TITLE
 mbgl/style/filter.hpp file not found

### ISSUE THREAD

**Issue by Bicubiciosdev** [mapbox/mapbox-gl-native#8120]
Platform:IOS
Mapbox SDK version:4.0.1

please provide some useful step to tun demo.i check the step but i does not understand which dependencies installing.finaly i got this error how can i solved
please help me..

**Comment by jfirebaugh** [comment]
Hi @Bicubiciosdev. As we've told you before, this is not a support forum. Please refer to the [iOS SDK](https://www.mapbox.com/ios-sdk/) documentation and [INSTALL.md](https://github.com/mapbox/mapbox-gl-native/blob/master/INSTALL.md).
