### ISSUE TITLE
Android compass is backwards

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#8123]
The more you rotate e.g. counterclockwise (making map north point more and more NW) the more the compass points NE. 

![android](https://cloud.githubusercontent.com/assets/17722/23135861/341c61f6-f768-11e6-943d-230f2ba53ecf.gif)

Compare to Google Maps: 

![goog](https://cloud.githubusercontent.com/assets/17722/23135865/37254ef8-f768-11e6-8c70-c774e0e9479c.gif)

And our iOS behavior: 

![ios](https://cloud.githubusercontent.com/assets/17722/23135866/39f84cac-f768-11e6-9810-c667ce4be6bf.gif)

@mapbox/android

**Comment by incanus** [comment]
AFAICT, just negating the argument passed into `UiSettings.update()` in `UiSettings.java` should fix things without external impact.

**Comment by tobrun** [comment]
oh man, thanks for noticing!

**Comment by tobrun** [comment]
![ezgif com-video-to-gif 12](https://cloud.githubusercontent.com/assets/2151639/23155849/976e646e-f814-11e6-9ec3-cdc46e7d6aa6.gif)
