### ISSUE TITLE
unable to specify color as default value for source functions

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#8126]
This may be intentional, but it's not clear why. 

It seems that you can't specific a `Color` as a default value for a DDS source function. 

```java
FillLayer layer = new FillLayer("counties", "counties")
    .withSourceLayer(getString(R.string.counties_source_layer_id))
    .withProperties(
        fillColor(
            property(
                "GEOID",
                categorical(
                    stop("19345", fillColor(Color.RED)),
                    stop("20123", fillColor(Color.GREEN))
                )
            ).withDefaultValue(fillColor(Color.GREEN))
        ),
        fillOpacity(0.5f),
        fillOutlineColor(Color.DKGRAY)
);
```

This yields a compile-time error related to the use of `withDefaultValue()`: 

```
Error:(119, 61) error: incompatible types: PropertyValue<String> cannot be converted to String
```

Indeed, the API seems to want a `String`, not a `PropertyValue<String>` as returned by e.g. `fillColor()`. 

<img width="596" alt="screen shot 2017-02-20 at 3 41 32 pm" src="https://cloud.githubusercontent.com/assets/17722/23141534/3f38daf2-f785-11e6-94eb-5eba52715015.png">

Looking at the tests, which are generated by [`layer.junit.ejs`](https://github.com/mapbox/mapbox-gl-native/blob/62e8e64299ae1635e56df701a7c2264e8b37b77a/platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs), it specifically avoids testing colors as default values ([one](https://github.com/mapbox/mapbox-gl-native/blob/62e8e64299ae1635e56df701a7c2264e8b37b77a/platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs#L269-L277), [two](https://github.com/mapbox/mapbox-gl-native/blob/62e8e64299ae1635e56df701a7c2264e8b37b77a/platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/style/layer.junit.ejs#L307-L311)). 

How should this be done? Here is the equivalent in iOS: 

```swift
layer.fillColor = MGLSourceStyleFunction(interpolationMode: .categorical,
                                         stops: categoricalStops,
                                         attributeName: "GEOID",
                                         options: [.defaultValue: MGLStyleValue(rawValue: UIColor.clear)])
```

/cc @ivovandongen

**Comment by ivovandongen** [comment]
@incanus You can use the [utility method](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/PropertyFactory.java#L2136) to convert an Android Color int to rgba. We can add some extra wrappers to make this more clear.

**Comment by incanus** [comment]
Aha! So it does in fact need a `String`, of the format `rgba()` as in GL JS. 

Isn't this odd to specify a different type for the stop values and the default value, though?

**Comment by incanus** [comment]
👉 https://github.com/mapbox/mapbox-gl-native/issues/8136
