### ISSUE TITLE
Move two-map demo to split view

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8128]
The two-map demo in iosapp, added in #8122, relies on manually adding and removing constraints and referring to map views by tags. 🙀 Since iosapp is intended in part to be a showcase of good practices around using the SDK, and since the interface is already built using a storyboard, let’s replace this example with a two-map split view, ideally defined in the storyboard. A split view would look pretty good on an iPad, too.

/cc @incanus @friedbunny

**Comment by incanus** [comment]
Might be useful to clarify from @kkaefer whether he sees this as a long-term need or not.

**Comment by 1ec5** [comment]
I think it would be useful regardless to have a split view demo, to show that maps don’t have to be full-screen. It could be fun to compare two styles on an iPad with a resizable split view.

**Comment by kkaefer** [comment]
Not seeing a reason to *not* have this in the demo app permanently.

**Comment by incanus** [comment]
Cool, yeah then we should get this shored up as a split view. My original goal was quick-n-dirty, forgetting: 

> iosapp is intended in part to be a showcase of good practices around using the SDK

**Comment by incanus** [comment]
Looking into split view controllers more, does it make sense for that kind of overhead for such a feature? As in, do we really need a parent/child view controller setup plus the second view controller managed by its own view controller? With the amount of configuration we'd need for iPhone/iPad and orientation configurations, it seems kinda heavy. 

Could a valid middle road be just assigning the second map view (currently managed fairly dirtily with view tags) as a ` secondMapView` instance variable in `MBXViewController` and leave everything else the same? 

/cc @jmkiley

**Comment by 1ec5** [comment]
> As in, do we really need a parent/child view controller setup plus the second map view managed by its own view controller? With the amount of configuration we'd need for iPhone/iPad and various orientations, it seems kinda heavy.

We do much of this already for the offline feature. There was minimal (no?) setup code because it was all in the storyboard.
