### ISSUE TITLE
Lock rotation when pinch-zooming

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#813]
On Android, it is very easy to change the rotation of the map when zooming. iOS has some mechanism to prevent that. We should have the same behavior on Android too (Google Maps does the same).

**Comment by ljbade** [comment]
I had noted this in https://github.com/mapbox/mapbox-gl-native/issues/553#issuecomment-63438040 (comment). Touch events on Android are very hard due to the poor API Google have designed as you have to write pretty much *everything* from scratch.

Would love any touch experts (perhaps from JS side) to provide advice on this too.

**Comment by wsnook** [comment]
@ljbade, if you've got an Apple Developer membership, you might want to take a look at the video for the   2010 WWDC presentation called Advanced Gesture Recognition. It talks about how they implemented their gesture recognition system and the reasoning behind some of the design choices.

https://developer.apple.com/videos/wwdc/2010/

**Comment by ljbade** [comment]
@wsnook, cool I watch when I get to SF. For some reason United block *.mov files on their WiFi.

**Comment by incanus** [comment]
Thanks @wsnook for the insight — didn't realize they ever talked about these internals.

**Comment by ljbade** [comment]
Hmm I do like their design w.r.t. to gesture states and the interaction between different gesture recognisers. Much better than the stock Android model. I am wonder if we should implement something that operates like the Apple design on Android.

**Comment by incanus** [comment]
We should look high & low for any efforts to do this already outside of Google Play, then consider building it out ourselves as a standalone. IMHO it's something needed by top-notch Android apps and should exist.

**Comment by ljbade** [comment]
@bleege I see you use the same touch lib in the raster SDK. Did you ever search for other Android touch libs?

**Comment by bleege** [comment]
@ljbade Here's the background on the Rotation Library decision in Android Raster: https://github.com/mapbox/mapbox-android-sdk/issues/525
