### ISSUE TITLE
[Android] DDS api enhancements

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#8136]
A couple of areas remain a little rough in the DDS api:

- Specifying default values. Esp when needing conversion, eg for Color ints. Now values ares specified as literals, using `PropertyValue<>` wrappers here would make things much clearer.
- Getting color values from returned properties. We could add a convenience method to convert back to Color ints.

**Comment by incanus** [comment]
Carrying over from #8126, this avoids mismatches like the following in type between stop values (`fillColor(Color.RED)`) and default value (`colorToRgbaString(Color.BLUE)`). 

```java
FillLayer layer = new FillLayer("counties", "counties")
    .withSourceLayer(getString(R.string.counties_source_layer_id))
    .withProperties(
        fillColor(
            property(
                "GEOID",
                categorical(
                    stop("19345", fillColor(Color.RED)),
                    stop("20123", fillColor(Color.GREEN))
                )
            ).withDefaultValue(colorToRgbaString(Color.BLUE))
        ),
        fillOpacity(0.5f),
        fillOutlineColor(Color.DKGRAY)
);
```

**Comment by incanus** [comment]
🎉
