### ISSUE TITLE
Map View May Start Black

### ISSUE THREAD

**Issue by cansurmeli** [mapbox/mapbox-gl-native#8143]
Hello.

I've used the following code to initially display the current user location on my map view upon app launch.

```
DispatchQueue.main.asyncAfter(deadline: DispatchTime.now()) { 
  while true {
    if let userLocation = LocationService.shared.currentLocation {
      self.mapView.setCenter(userLocation, zoomLevel: 11, animated: true)
      break
    }
  }
}
```

This code may be stupid but I couldn't find another way to start my map view with the user location zoomed in. Even in the simulator, CoreLocation determining the current location takes couple of seconds.

Anyways, the app I'm working on has a sign in view which leads the user to the map view which makes use of the above code. If I come to my map view after signing in(map view gets initiated from a storyboard), the above block of code makes the map view appear blacked out. I know this is the cause for certain. Once it's removed, everything is fine.

![mapbox - black screen on launch](https://cloud.githubusercontent.com/assets/2464293/23182569/b26f4ba8-f881-11e6-9776-5c3f03e84287.png)

However, if I run my app when logged in and the map view directly gets viewed first, the map view works as expected.

There is only a problem when the map view gets initialised dynamically after signing in.

Is this a bug in the Mapbox SDK or am I doing something wrong?

**Platform:** iOS
**Mapbox SDK version:** 3.3.7

**Comment by friedbunny** [comment]
This feels like an issue with your specific implementation — I can’t recall seeing any similar issue. If you’re able to, I’d recommend enabling [`MGLMapView.showsUserLocation`](https://www.mapbox.com/ios-sdk/api/3.4.2/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)showsUserLocation) and then [setting some user tracking mode](https://www.mapbox.com/ios-sdk/api/3.4.2/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)setUserTrackingMode:animated:).

**Comment by cansurmeli** [comment]
Funny timing! I was just dealing with this issue and found [your SE question](http://stackoverflow.com/questions/35234869/how-should-i-find-the-correct-location-data-using-userlocation-in-mapbox-for-ios). Thanks for the tip, both times. :]
