### ISSUE TITLE
Eliminate mbgl/gl/context.hpp include from public includes

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#8148]
`mbgl/gl/context.hpp` and all of its dependencies are currently forced to be public headers because it is used by SDK files such as `native_map_view.cpp` in Android and `MGLMapView.mm` in iOS/macOS.

This needs to be refactored so that `mbgl/gl/context.hpp` is only exposed internally.

**Comment by kkaefer** [comment]
Fixed in #8214.
