### ISSUE TITLE
Mapbox Satellite tiles should be overzoomed when not available

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-gl-native#8151]
Satellite overzooming seems to be inconsistent, with areas outside of some metro areas returning empty black tiles when loading tiles z >= 18. 

![satellite overzoom](https://cloud.githubusercontent.com/assets/664805/23189010/c2e4b338-f845-11e6-95ea-ffeea207b6e8.gif)

Example cities where overzooming works: San Francisco, Los Angeles, Austin, Mexico City, Paris, Venice. 
Example cities where overzooming fails: Vancouver BC, Whistler BC, Lima Peru, Alamogordo NM, Mount Shasta CA, Truckee CA. (These same cities aren't an issue in gl-js)

A tile from an example failure area & zoom level returns a 404 and a json response:
```
GET https://api.mapbox.com/v4/mapbox.satellite/18/41541/88768@2x.png?access_token=ACCESS_TOKEN&events=true
HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8
{
    "message": "Tile does not exist"
}
```

In the major cities where overzooming does work, it seems the mapbox API does the overzooming itself: 
```
GET https://api.mapbox.com/v4/mapbox.satellite/19/83865/202642@2x.png?access_token=ACCESS_TOKEN&events=true
HTTP/1.1 200 OK
Content-Type: image/jpeg
```

**Comment by kkaefer** [comment]
> These same cities aren't an issue in gl-js

gl-js has a slightly different, but also incorrect behavior: it retains the most recent available tiles when zooming in, but doesn't actually load overzoomed lower zoom level tiles when starting out or panning into regions with no tile availability: https://github.com/mapbox/mapbox-gl-js/issues/4318
