### ISSUE TITLE
Build and Run From Source

### ISSUE THREAD

**Issue by bessermt** [mapbox/mapbox-gl-native#8153]
OS: **Linux:**
Building from source

### Steps to trigger behavior

 1. Follow Directions on [Android/Linux Contributing ](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/CONTRIBUTING_LINUX.md)
 2. BUILDTYPE=Debug make android as directed
 3. adb install -r platform/android/MapboxGLAndroidSDKTestApp/build/outputs/apk/MapboxGLAndroidSDKTestApp-debug.apk

I see how to install the test app apk, but I don't see any instructions on how to run it. I also don't see a list of expected debug outputs (*.so files?). It would also be nice to see instructions on how to include the generated library (or libraries) in a simple app if the Test App doesn't do that.

**Comment by tobrun** [comment]
Hi @bessermt, thank you for reaching out and requesting some insights on building.

> BUILDTYPE=Debug make android as directed

This specific command create the .so files for arm-v7 abi and creates an apk from the test app module. The .so file can be found in the `MapboxAndroidSDK/src/main/jnilibs/abi/..`.

That said we have other make commands for supporting other abi's:

```
make android-lib-arm-v5
make android-lib-arm-v7
make android-lib-arm-v8
make android-lib-x86
make android-lib-x86-64
make android-lib-mips
make android apackage (will build all above)
```

Also we have equivalent commands for also installing the result on a device with eg:

```
make run-android-lib-arm-v7
```

> how to include the generated library (or libraries) in a simple app

There are 3 ways of including the "generated" library in your app:
 - use the precompiled .aar file on maven (recommended)
 - run a release build on the MapboxGLAndroidSDK module and use the resulting .aar file
 - load the native .so library yourself 

Feel free to ask any follow up questions but closing this issue as resolved atm.
