### ISSUE TITLE
UI strings should be localizable

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8155]
Strings that appear in UI built into the Android SDK should be localizable in order to match the user’s system and the surrounding application UI. [This file](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/res/values/strings.xml) contains several strings that appear in UI. Perhaps we can manage translations [in Transifex](https://www.transifex.com/mapbox/mapbox-gl-native/), where we’re currently managing translations of the iOS and macOS SDKs.

/cc @zugaldia @tobrun @ragaisis

**Comment by tobrun** [comment]
Suggesting to pick up accessibility support in https://github.com/mapbox/mapbox-gl-native/issues/4857 first to avoid doing double translation work.

**Comment by 1ec5** [comment]
#8556 should’ve implemented the necessary Transifex integration, but we’ll want to do a `tx pull -a` before the next release to pull in any new translations.
