### ISSUE TITLE
onMarkerClick not call for MarkerView

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#8158]
**Platform:** Android
**Mapbox SDK version:** 5.0.0-beta.1 (and last SNAPSHOT)

### Steps to trigger behavior

 1.  add MarkerView to Map
 2. setOnMarkerClickListener
 3. click to marker 
 4. onMarkerClick not call

**Comment by tobrun** [comment]
Thank you for reaching out, follow up ticket in #8159.
