### ISSUE TITLE
MapBox 5.0.0 requires additional dependencies

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-gl-native#8167]
**android:**
**5.0.0:**

### Steps to trigger behavior

 1. Create new Project in Android Studio
 2. Add maven dependencies (MapBox)
 3. Click on compile!

**Comment by tobrun** [comment]
@genaray can you show me the dependency found in your build.gradle?
I think you are missing the `@aar` at the end:

```
 compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.0-beta.1@aar') {
        transitive=true
 }
```

**Comment by tobrun** [comment]
Since you have been creating newer issues that require you to run, I'm calling this resolved
