### ISSUE TITLE
Application randomly crashes

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-gl-native#8172]
**Android:**
**5.0.0:**

### Steps to trigger behavior

 1. Create a new Android Project
 2. Add dependencies
 3. Start the app and zoom in quickly !

**Comment by 1ec5** [comment]
If you can reproduce this crash again, please attach a crash report and information about your configuration (device, OS version, etc.), so we can be sure we’re looking at the same crash you’re seeing. Thanks!

**Comment by tobrun** [comment]
The explenation in this issue seems a lot like the one in #8079, this was fixed with https://github.com/mapbox/mapbox-gl-native/pull/8098.
