### ISSUE TITLE
Use animators for gestures and camera animations

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8175]
The Android SDK should use [animators](https://developer.android.com/reference/android/animation/Animator.html) to drive camera transitions in response to gestures and calls to methods like `animateTo()`. We should move off `mbgl::AnimationOptions` and use the `mbgl::Transform` methods only for incremental transform changes on each frame of the animation.

A key benefit is that the Android SDK will be able to implement concurrent animations (#3625) without us having to design an API around tweening, spring solving, or the like.

@tobrun started doing this as part of #8031. Perhaps there’s also prior art in the Qt SDK, where we’ve always relied on Qt animation APIs instead of mbgl’s.

/cc @zugaldia @ivovandongen @bsudekum

**Comment by 1ec5** [comment]
https://github.com/mapbox/mapbox-gl-native/issues/9808#issuecomment-324274671 demonstrates an implementation of animator-driven camera animations. 😍

**Comment by tobrun** [comment]
> #9808 (comment) demonstrates an implementation of animator-driven camera animations. :heart_eyes:

WIP code for that in https://github.com/mapbox/mapbox-gl-native/tree/tvn-android-animations

**Comment by tobrun** [comment]
The base API for this has landed in #10001, though we still need to hook our gestures and other animations into it. Reopening.

**Comment by tobrun** [comment]
To clarify that why this was closed:
 - gesture animators have landed as part of the gesture rework from @LukasPaczos 
 - camera animators are supported though need to be self written by end users and hooked up to `CameraUpdateFactory#moveCamera`. We will keep using the core animations mainly to allow prefetching tiles for doing flyTo at some point.
