### ISSUE TITLE
Enabling/disabling sources on demand. (Enhancement request).

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#818]
At the moment the only way to enable/disable sources is to change the style.json file. It would be useful to be able to do so programmatically via an API exposed through objective C wrapper.

**Comment by ljbade** [comment]
When you mean "enable/disable sources" what are you referring to?

You can currently enable/disable style classes and load different style.json files.

**Comment by mb12** [comment]
I experimented with getAppliedStyleClasses with bright style to figure out what it is. But it always returns an array with 0 objects.

I've included below specific uses cases.

1.) The style.json file has 3 different sources. These need to be enabled  conditionally.  When a source is enabled/disabled any layer referring to that source in style.json should get enabled/disabled.

The only way I have been able to figure out to do this is to create a new style.json and apply it. 

2.) For a layer  with specific "id" in style.json file, I need to do things like the following:
     - Change fill opacity dynamically for certain layers.
     - disable  layers with certain "ids".  By disable I mean all Buckets created for that style "id" are not rendered/deleted.

**Comment by ljbade** [comment]
So why are enabling disabling sources? What exactly are you trying to do?

The reason you get 0 length array is because bright does not have any classes in its style json.

Try it with outdoors and you will get night and day styles.

**Comment by mb12** [comment]
Thank you very much for the response. 
I believe I can use classes for my second use case. For the first case, I actually need to have the Source removed from Map::activeSources set. Enable/disable "classes" still keeps the "Source" under "activeSources" i.e. it continues to be rendered and tiles fetched for that source.

Use case #1:
I have "two" vector sources that are rendered over a base map. The base map can be changed dynamically to any of the following:

- A low scale base map bundled in the application.
- Regular vector street map
- Satellite imagery.

Of the two vector source rendered on the basemap, at least one will be active at any time.
I would like to disable a source specified in style.json in the sense that it gets removed from "Map::activeSources" set.

Dynamically generated style.json approach is cumbersome for modeling this (Also due to the start/stop bug, unreliable at the moment). Ideally I would like to have a static style.json and enable/disable Sources dynamically. 

Use case # 2:
A use case for dynamically changing opacity attribute for a layer within a source is the following. I believe this is something I could do with classes.

- When base map is satellite, I need to logically make certain area layers transparent. This is similar to overlaying only street names and POIs on satellite imagery.

**Comment by ljbade** [comment]
Thanks for the info I now see what you are trying to do.

I wonder if we can make the logic smarter to prevent loading sources not referenced in the current class.

Thoughts @jfirebaugh?

**Comment by jfirebaugh** [comment]
This is part of #837.
