### ISSUE TITLE
LineString coordinates from route are multiplied by 10

### ISSUE THREAD

**Issue by KatieBarnett** [mapbox/mapbox-gl-native#8180]
**Platform:** Android
**Mapbox SDK version:** Android SDK 5.0.0-beta.1, Android services 2.0.0-beta.2

### Steps to trigger behavior

After updating to the latest beta versions of the SDK & services today I found that the latitude and longitude coordinates from the generated route are off by a multiple of 10. This worked correctly with the Android SDK version 4.2.2. I can force the problem to fix by dividing my resulting latitude and longitude coordinates by 10. 

 1. Request a DirectionsResponse
 2. Get DirectionsRoute
 3. Get coordinates from route for display on the map. 

**Applicable code:**

    private void getRoute(Position origin, Position destination, ArrayList<Position> waypoints) throws ServicesException {

        MapboxDirections client = new MapboxDirections.Builder()
                .setOrigin(origin)
                .setDestination(destination)
                .setCoordinates(waypoints)
                .setProfile(DirectionsCriteria.PROFILE_DRIVING)
                .setSteps(true)
                .setAccessToken(Mapbox.getAccessToken())
                .build();

        client.enqueueCall(new Callback<DirectionsResponse>() {
            @Override
            public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
                // You can get the generic HTTP info about the response
                Log.d(TAG, "Response code: " + response.code());
                if (response.body() == null) {
                    Log.e(TAG, "No routes found, make sure you set the right user and access token.");
                    return;
                } else if (response.body().getRoutes().size() < 1) {
                    Log.e(TAG, "No routes found");
                    return;
                }
                currentRoute = response.body().getRoutes().get(0);
                drawRoute(currentRoute);
            }

            @Override
            public void onFailure(Call<DirectionsResponse> call, Throwable throwable) {
                Log.e(TAG, "Error: " + throwable.getMessage());
                Toast.makeText(TourActivity.this, "Error: " + throwable.getMessage(), Toast.LENGTH_SHORT).show();
            }
        });
    }

    private void drawRoute(DirectionsRoute route) {
        // Convert LineString coordinates into LatLng[]
        // ERROR IS OBSERVED HERE
        LineString lineString = LineString.fromPolyline(route.getGeometry(), Constants.OSRM_PRECISION_V5);
        List<Position> coordinates = lineString.getCoordinates();
        LatLng[] points = new LatLng[coordinates.size()];
        for (int i = 0; i < coordinates.size(); i++) {
            // CAN TEMPORARILY FIX HERE BY DIVIDING LAT & LONG BY 10
            points[i] = new LatLng(
                    coordinates.get(i).getLatitude(),
                    coordinates.get(i).getLongitude());
        }

        // Draw Points on MapView
        map.addPolyline(new PolylineOptions()
                .add(points)
                .color(Color.parseColor("#009688"))
                .width(5));
    }

### Expected behavior
Valid lat & longs are returned

### Actual behavior
Lat & longs are correct except that they have been multiplied by 10 (and are invalid)
e.g. 
Position [longitude=-1219.13402, latitude=365.80426, altitude=NaN]
should be:
Position [longitude=-121.913402, latitude=36.580426, altitude=NaN]

Errors such as the following are observed in the logs:
`02-23 17:15:10.744 25326-25326/com.ibm.events.android.pb W/Position: Latitude value seems to be out of range (found: 365.820400, expected: [-90, 90]). Did you accidentally reverse the longitude/latitude order?`
`02-23 17:15:10.744 25326-25326/com.ibm.events.android.pb W/Position: Longitude value seems to be out of range (found: -1219.695430, expected: [-180, 180]). Did you accidentally reverse the longitude/latitude order?`

Thanks, let me know if you need further info.
Katie

**Comment by tobrun** [comment]
@KatieBarnett Thank you for reaching out! the code found in this issue is related to the [mapbox-java](https://github.com/mapbox/mapbox-java/) repository, I have created a [follow up issue](https://github.com/mapbox/mapbox-java/issues/353) there. Closing, as upstream ticket has been created.

**Comment by KatieBarnett** [comment]
Thanks :-)
