### ISSUE TITLE
Revert diagnostic logging of GL_MAX_VERTEX_ATTRIBS

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-native#8184]
After we've gathered the info we need from users, we need to revert https://github.com/mapbox/mapbox-gl-native/pull/8177 before we release.

Possibly, in light of #8183, instead of reverting we should just change it from `Info` to `Debug`, so that we can get this value if/when we run into related issues in the future.

**Comment by jfirebaugh** [comment]
We didn't end up putting this logging in.
