### ISSUE TITLE
No possibility to move a marker with the same speed ?

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-gl-native#8186]
**android:**
**5.0.0**

### Steps to trigger behavior

 1. Create new Android Project
 2. Add MapBox as dependencie
 3. Create a marker and try to move him with the same speed !

### Marker moves fast and near the end point very slow ...

    ValueAnimator markerAnimator = ObjectAnimator.ofObject(playerMarker, "position",
                 new LatLngEvaluator(), playerMarker.getPosition(), point);
                markerAnimator.setDuration(2000);
                markerAnimator.start();

    @Override
    public LatLng evaluate(float fraction, LatLng startValue, LatLng endValue) {

        latLng.setLatitude(startValue.getLatitude()
                + ((endValue.getLatitude() - startValue.getLatitude()) * fraction));

        latLng.setLongitude(startValue.getLongitude()
                + ((endValue.getLongitude() - startValue.getLongitude()) * fraction));

        return latLng;
    }

**Comment by tobrun** [comment]
@genaray capturing from the android docs `When no interpolator is supplied, the default AccelerateDecelerateInterpolator will be used.`, you will need to specifically indicate you want to use an LinearInterpolator instead.

For future questions please contact us at https://www.mapbox.com/contact/.
This repo is used to report bugs and feature requests, not for giving support. 
Thank you!
