### ISSUE TITLE
Issues installing the node platform

### ISSUE THREAD

**Issue by juhanivl** [mapbox/mapbox-gl-native#8188]
**Platform: node**
**Mapbox SDK version: 3.4.2**

Hello!

I'm having trouble using the mapbox-gl-native node module in my webpack project. I had couple of issues with the installation which I managed to solve (hopefully the right way) but now I'm facing an issue I'm seeking your help with.

I'm using version 4.2.1 of node since you mentioned that v5+ is known to have issues. My version of npm is 2.14.7 and webpack 1.13.2. 

I installed the package via npm but importing/requiring the package gave me this error: 

>Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open "/node_modules/mapbox-gl-native/platform/node/index.js".

In order to solve this I ran "npm install" inside the mapbox-gl-native node-module directory. After this I ran the "npm test" and "npm run test-suite" commands and they all passed.

When I tried to build the project in webpack I got an error:

> ERROR in ./~/mapbox-gl-native/lib/mapbox-gl-native.node
> Module parse failed: /node_modules/mapbox-gl-native/lib/mapbox-gl-native.node Unexpected character '�' (1:0)
> You may need an appropriate loader to handle this file type.
> (Source code omitted for this binary file)
>  @ ./~/mapbox-gl-native/platform/node/index.js 5:11-53

I solved this error adding node-loaders in my webpack-config file and after this the project built successfully.

Now I still get an error when I try to require/import the module: 

> Uncaught Error: Cannot open /Users/juhani/testi/node_modules/mapbox-gl-native/lib/mapbox-gl-native.node: TypeError: Cannot read property 'dlopen' of undefined.

So far I've not been able to solve this issue and hope you could help me with it.

**Comment by jfirebaugh** [comment]
Hi @juhanivl. Using mapbox-gl-native in a webpack project doesn't make much sense: webpack is for creating bundles for web applications, and mapbox-gl-native uses native code. You might be looking for [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js), the WebGL-based rendering implementation.
