### ISSUE TITLE
Text is drifting around, when setted to marker position

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-gl-native#8189]
**android:**
**5.0.0**

### Steps to trigger behavior

 1. Create a new Project
 2. Add MapBox dependencies
 3. Try to set  the position of a TextWidget to the marker position each frame. Or just try to add an marker title. It will have the same effect!

### When the map moves, the text / title begins to drift around but only on Camera move.
       `playerMarker = mapboxMap.addMarker(new MarkerOptions().position(new  LatLng(40.73581,-73.99155)).icon(playerIcon)); 
        playerMarker.setTitle("Player");`

**Comment by steven-ha** [comment]
I created a simple android app trying to replicate this issue. I can say that when using the android emulator the text window for the marker seems like its drifting/floating off of the marker if the user is manipulating the view. I also ran the application on my android galaxy and the text window doesn't behave like the emulator. 

Genaray, have you tested your app on an android phone?

**Comment by tobrun** [comment]
Closing this in favor of #8224
