### ISSUE TITLE
[Android] SurfaceView Interoperability

### ISSUE THREAD

**Issue by tcolligan-ap** [mapbox/mapbox-gl-native#8197]
I am currently using the 4.1.1 Android SDK in my app. I tried to update to the most recent version 4.2.2 since it has a fix for https://github.com/mapbox/mapbox-gl-native/issues/5513 which I need.

I use both MapBox and [Skobbler](https://developer.skobbler.com/getting-started/android) in my app, and allow users to toggle between the two different maps.

It looks like in 4.2.2 you added https://github.com/mapbox/mapbox-gl-native/issues/5000 which switched the map from TextureView to SurfaceView. Skobbler uses GLSurfaceView.

I previously had both maps in the same layout ontop of each other, and simply animated their alpha to show/hide the appropriate map. Now that both maps use some for of SurfaceView it appears that will not work anymore. Both maps render into each other, it seems like they do not like sharing the same layout at all anymore.

For example in this situation

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:gotenna="http://schemas.android.com/apk/res-auto"
                xmlns:tools="http://schemas.android.com/tools"
                android:layout_width="match_parent"
                android:layout_height="match_parent">

    <com.skobbler.ngx.map.SKMapViewHolder
        android:id="@+id/skobblerMapViewHolder"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapBoxMapView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:animateLayoutChanges="true"
        gotenna:center_latitude="40.69230"
        gotenna:center_longitude="-73.98623"
        gotenna:style_url="@string/map_box_map_style"
        gotenna:zoom="@integer/default_zoom_level" />

</RelativeLayout>
```

The Skobbler map renders with the MapBox pins floating on top of it, with MapBox responding to touch events. Swapping the order does not help.

I played around with the Skobbler GLSurfaceView since they provide easy access to it, by calling methods like [SurfaceView.setZOrderMediaOverlay](https://developer.android.com/reference/android/view/SurfaceView.html#setZOrderMediaOverlay(boolean)) to no avail.

Is there anything I can try with the MapBox surface view that you know of that may help out here? Would really like to update to the latest SDK but this is proving a significant blocker for me right now. Perhaps separating those two map views into their own Fragments is a solution, but that would require significant work on my side since that map layout is already inside its own Fragment.

Alternatively, it I could get a 4.1.1 build with https://github.com/mapbox/mapbox-gl-native/issues/5513 fixed, that would help me out a lot. Would appreciate any insights or suggestions you have here. Thanks

**Comment by tobrun** [comment]
It's currently still possible to fallback using the TextureView by enabling it through xml attributes or MapboxMapOptions. The issue you are seeing is that both SurfaceView as GlSurfaceView are fighting over surface that is placed behind the Activity window. 

>  played around with the Skobbler GLSurfaceView since they provide easy access to it

You are able to to the same with our SurfaceView by calling `MapView.findViewById(R.id.surfaceView).` Note that we do not officially support putting the SurfaceView above the View hierarchy as this will break features that involve android SDK views (Logo, Attribution, ViewMarkers, InfoWindows and MyLocationView).

I hope this reply helps you finding a solution for your issue.  
Feel free to ask any follow up questions if you need more information.

**Comment by tcolligan-ap** [comment]
@tobrun Just got around to trying this out. The solution worked, thanks! The only issue now is that the synchronization between the markers and the map is not great as you mentioned in #5000 referring to the "jiggling". Any way to get around the jiggling or is that just the way things are now if I decided to use the texture view?

**Comment by tobrun** [comment]
@tcolligan-ap I fear this it just the way how these surfaces work. I'm trying to look more into improving this synchronisation in #8224, at some point I would like to move away of using View in total actually.

Note that most of the use-cases for MarkerViews can nowadays be implemented with runtime styling (using a SymbolLayer). We introduced MarkerViews to workaround the limited api of the "default" opengl based Marker until runtime styling landed.
