### ISSUE TITLE
[android] mapbox::sqlite::Exception: database is locked" failed when getting status of ofline regions

### ISSUE THREAD

**Issue by ouska** [mapbox/mapbox-gl-native#8201]
Platform: Android 5.1.1 - Sony D5803
Mapbox SDK version: 5.0.0-beta1

Having few offline regions downloaded, the following code throws this exception

A/libc: /usr/local/google/buildbot/src/android/ndk-r13-release/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type mapbox::sqlite::Exception: database is locked" failed
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 17938 (DefaultFileSour)

            @Override
            public void onMapReady(MapboxMap map) {
                OfflineManager offlineManager = OfflineManager.getInstance(getApplicationContext());
                offlineManager.listOfflineRegions(new OfflineManager.ListOfflineRegionsCallback() {
                    @Override
                    public void onList(OfflineRegion[] offlineRegions) {
                        if (offlineRegions != null) {
                            for (final OfflineRegion offlineRegion : offlineRegions) {
                              offlineRegion.getStatus(new OfflineRegion.OfflineRegionStatusCallback() {
                                  @Override
                                  public void onStatus(OfflineRegionStatus status) {
                                      Log.i("XXX", "status " + status.isComplete());
                                  }
  
                                  @Override
                                  public void onError(String error) {}
                              });
                            }
                        }
                    }
                }
            }

**Comment by tobrun** [comment]
@ivovandongen is this something that will be resolved with having an unified Filesource?

**Comment by ivovandongen** [comment]
@tobrun Very likely. Testing with the current snapshot would verify this.

**Comment by tobrun** [comment]
@ouska would you be able to retest with the latest snapshot?

```gradle
repositories {
    mavenCentral()
    maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
}

dependencies {
    compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.0-SNAPSHOT@aar') {
        transitive=true
    }
}
```

**Comment by ouska** [comment]
@tobrun Hi, I am currently testing it with 5.0.0-SNAPSHOT and haven't experienced the lock error yet.
O.

**Comment by tobrun** [comment]
Thank you for validating! Closing this as resolved.
