### ISSUE TITLE
Invalid Zoom level with CameraUpdateFactory.newLatLngBounds

### ISSUE THREAD

**Issue by kingfisherphuoc** [mapbox/mapbox-gl-native#8204]
**Platform : Android **
**Mapbox SDK version: 5.0.0-beta.1@aar'**

### Steps to trigger behavior

 1. Using below code block with list of LatLng points:
```
LatLngBounds.Builder builder = new LatLngBounds.Builder()
                .includes(Arrays.asList(routes));
        LatLngBounds latLngBounds = builder.build();
        CameraUpdate cameraUpdate = CameraUpdateFactory.newLatLngBounds(latLngBounds, getResources().getDimensionPixelSize(R.dimen.margin_50));
 mMapboxMap.animateCamera(cameraUpdate, 500);
```

### Expected behavior
Camera should change to a certain zoom level which contains all the LatLngs. It worked well with previous 4.2.2 version, but not with this beta version. (I also got an issue with `onMarkerClick` - the event is not fired!) 
### Actual behavior
Camera is changed to the lowest Zoom level.

**Comment by tobrun** [comment]
@kingfisherphuoc would you be able to retest this with latest SNAPSHOT? 

```java
repositories {
    mavenCentral()
    maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
}

dependencies {
    compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.0-SNAPSHOT@aar') {
        transitive=true
    }
}
```

These two commits should have resolved this issue:
 - https://github.com/mapbox/mapbox-gl-native/pull/8137
 - https://github.com/mapbox/mapbox-gl-native/pull/8133

**Comment by kingfisherphuoc** [comment]
@tobrun Thanks, I tested and the issue is fixed! How's about the `onMarkerClick` event issue? I checked and it's not resolved yet.

**Comment by tobrun** [comment]
Could you add some more information on the OnMarkerClick event issue? 
Feel free to open another issue for this, calling the LatLngBounds part of the issue resolved.
