### ISSUE TITLE
MarkerView disappears when map is moving and map is bigger than Screen.

### ISSUE THREAD

**Issue by kingfisherphuoc** [mapbox/mapbox-gl-native#8206]
**Platform: Android**
**Mapbox SDK version: 5.0 beta**

### Steps to trigger behavior

 1. Set `MapView` larger than `Screen height`: ` android:layout_marginBottom="-100dp" ` and `tilt=60`.
 2. Add a `MarkerView` into map:
 ```
CustomMarkerStreetViewOptions customMarkerStreetViewOptions = new
                        CustomMarkerStreetViewOptions()
                        .streetName((String) objectes[0])
                        .drawableIcon((int) objectes[1])
                        .position((LatLng) objectes[2])
                        .anchor(1f, 1f);
                markerStreet = mMapboxMap.addMarker(customMarkerStreetViewOptions);
```
 3. Touch the screen and move map up and down

### Expected behavior
The `MarkerView` should always be there. Is it a bug? Can I change focal point of `MapView` permanently? ( so I can zoom, move map, roate at a specific location in MapView and not at the center of the map).

![device-2017-02-27-180135](https://cloud.githubusercontent.com/assets/962484/23360236/df98a198-fd1c-11e6-9193-0dde87726fcc.png)
![device-2017-02-27-180206](https://cloud.githubusercontent.com/assets/962484/23360239/e11e7cea-fd1c-11e6-83d0-42a24b1dc0f0.png)
![device-2017-02-27-180307](https://cloud.githubusercontent.com/assets/962484/23360248/e6ed07a4-fd1c-11e6-8695-e026bfb012ac.png)

### Actual behavior
The `MarkerView` appears and disappears when moving.

**Comment by kingfisherphuoc** [comment]
@tobrun Would you please look at this issue?

**Comment by tobrun** [comment]
atm the bounds used for marker view invalidation is equal to the MapView size, the feature request to change this size is tracked in https://github.com/mapbox/mapbox-gl-native/issues/5440. Closing this in favor of that ticket, will be adding a comment there about using negative margins.
