### ISSUE TITLE
Improve JavaDocs for setFilter

### ISSUE THREAD

**Issue by elevenetc** [mapbox/mapbox-gl-native#8207]
The error is self-explanatory, but the behaviour is quite contradictive.
Adding images with this code:

```java
markerLayer.setFilter(
    all(
        eq("cluster", false),
        eq("id", item.getId()),
        eq("coordinates", stop.getLatLng())
    )
);
```
Everything looks fine, images on a proper locations, but I'm getting error messages.
If I comment the line `eq("coordinates", stop.getLatLng())` then error disappears, but images are not visible.

**Platform:** Android
**Mapbox SDK version:** 4.2.2

**Comment by incanus** [comment]
Similar to the iOS side of things (`NSPredicate` building for runtime styling filters), things aren't and can't really be extremely strict at compile-time. So good docs are essential. 

On iOS, we have a [runtime style guide](https://www.mapbox.com/ios-sdk/api/3.4.2/Classes/MGLVectorStyleLayer.html#/c:objc(cs)MGLVectorStyleLayer(py)predicate) (Jazzy documentation has the concept of _guides_ like this) which specifically calls out the RHS types allowed: 

> The predicate’s right-hand expression must be an `NSString` (to match strings) or `NSNumber` (to match numbers, including Boolean values) or an array of `NSString`s or `NSNumber`s, depending on the operator and the type of values expected for the attribute being tested. For floating-point values, use `-[NSNumber numberWithDouble:]` instead of `-[NSNumber numberWithFloat:]` to avoid precision issues.

@mapbox/android Is there a good place to do something similar in the [Android API docs](https://www.mapbox.com/android-sdk/api/5.0.0-beta.1/)? To my eyes, they appear to be strictly code-level API docs. 

/cc @1ec5 @friedbunny

**Comment by ivovandongen** [comment]
@elevenetc As you've already discovered, the filters are expressed in basic types. What is actually in the `coordinates` property on the Features? You could probably achieve what you want with the location split up into two fields (lat, long) and filtering on them with plain numbers. 

> The error is self-explanatory, but the behaviour is quite contradictive.

How do you mean, contradictive?

> If I comment the line eq("coordinates", stop.getLatLng()) then error disappears, but images are not visible.

Could you add a little more info like a snippet of the data you are using and the source and layer definitions?

**Comment by zugaldia** [comment]
> Can we do this on setFilter() or would it be too verbose there?

@incanus Do you mean the Javadoc? I don't see why not, we can be as explicit as we want there, we can even include code samples.

**Comment by tobrun** [comment]
closing as not-actiomable/stale, 
since last activity we rolled out expressions that replaced the filters mentioned in OP.
