### ISSUE TITLE
WMS/TMS Overlay

### ISSUE THREAD

**Issue by Namec** [mapbox/mapbox-gl-native#822]
is there any function to make add as many WMS/TMS layers that have transperence.

**Comment by Namec** [comment]
anyone here ??

**Comment by incanus** [comment]
No, there isn't. Isn't a priority, but pull requests are welcome and will be reviewed.

**Comment by thiagogcm** [comment]
Any updates on this issue ?

**Comment by 1ec5** [comment]
Mapbox GL JS has added WMS overlay support (mapbox/mapbox-gl-js#2612), so it needs to be ported over for parity.
