### ISSUE TITLE
Improve View synchronisation

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8224]
The Android SDK includes multiple features that show and synchronises an Android SDK view on top of the map. Some examples of such features are:
 - MarkerView
 - InfoWindow
 - MyLocationView

Our current setup uses `mapboxMap.getProjection().toScreenLocation(position)` to convert the position on the map to an actual screen coordinate. Afterwards we update the view with `View.setX(x)` and `View.setY(y)`. While this setup works, it introduces some kind of jiggling/wiggling on the view as the view is trying to catch up with the camera transformations. 

This issue primarily focusses on improving view synchronisation for gestures. The idea is to decouple the system of `toScreenLocation` and try to be smarter when dispatching updates. We could for example, for the pan gesture update the View directly with x,y from `moveBy` instead of relying on `toScreenLocation`.

Side note here is that this setup worked pretty well with our TextureView implementation but since a couple of releases we have moved rendering to a SurfaceView implementation. We haven't revisited our view synchronisation since that change.

**Comment by tobrun** [comment]
Even with the adding the approach mentioned in OP, I'm still seeing the View "jiggle", going to revisit the way we apply the transformation (currently with setX and setY).

**Comment by wbinarytree** [comment]
Any progress for this issue?

**Comment by tobrun** [comment]
General thinking around this issue is that we will start introducing plugins and all view synchronisation will be removed from the SDK with a major Semver. Non actionable for now. Closing.

**Comment by wbinarytree** [comment]
For MarkerView can be replaced by Marker without any drifting issue. Bus as for InfoWindow, is there a way to style an InforWindow via some other component like Layers?  Thanks.
