### ISSUE TITLE
Use mapbox_logo property of TileJSON to determine whether to include logo on map

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-native#8234]
Most other Mapbox tools use the `mapbox_logo` property in a source's TileJSON to determine whether or not to include the Mapbox watermark on a map. As far as I know the Android and iOS have the logo turned on always, but if you so desire you can now use this property to accurately determine if a user is required to display it.

Relevant PR for mapbox-gl-js https://github.com/mapbox/mapbox-gl-js/pull/3933
Not sure if I need to tag every platform we support on here but I assume its platform specific... 
@cammace @tobrun @1ec5

**Comment by 1ec5** [comment]
Relevant code for iOS and macOS:

https://github.com/mapbox/mapbox-gl-native/blob/cd5efab11e2ebd111428bba1144ff270b6cc51cc/platform/ios/src/MGLMapView.mm#L4852
https://github.com/mapbox/mapbox-gl-native/blob/cd5efab11e2ebd111428bba1144ff270b6cc51cc/platform/macos/src/MGLMapView.mm#L430

**Comment by mollymerp** [comment]
We should still do this for feature parity.

**Comment by friedbunny** [comment]
Still a thing Mapbox should do.
