### ISSUE TITLE
Text shown for bottom icon in SymbolLayer when textOptional(true)

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#8235]
**Platform:** Android (maybe other)
**Mapbox SDK version:** 5.0.0

### Steps to trigger behavior

Use **iconAllowOverlap(true)** (need show icon always) and **textOptional(true)** for my SymbolLayer

### Expected behavior
Show text for top Icon

### Actual behavior
Text shown for bottom icon
![7d57df0db9b3db3829cd46e47d93471f](https://cloud.githubusercontent.com/assets/6357562/23445607/24182c82-fe6f-11e6-9782-cbb737c1be43.png)

**Comment by klblk** [comment]
Again, it's important for me in version 6.4.0. 
My hack stopped working, because Projection.toScreenLocation() can be used only ui thread.

**Comment by riastrad** [comment]
This still is still a common developer pain point, so I recommend we keep it open.

**Comment by klblk** [comment]
"symbo-sort-key" solves this problem for me
