### ISSUE TITLE
Marker clicked event is not fired

### ISSUE THREAD

**Issue by kingfisherphuoc** [mapbox/mapbox-gl-native#8236]
**Platform: Android**
**Mapbox SDK version: 5.0 Snapshot**

### Steps to trigger behavior

 1. Set listener for Maker event:
```
mMapboxMap.setOnMarkerClickListener(new MapboxMap.OnMarkerClickListener() {
            @Override
            public boolean onMarkerClick(@NonNull final Marker marker) {
                LogUtils.e("OnMarkerClick!!!"); // never go here...
                return false;
            }
        });
```
 2. Add marker into MapView:
// add marker adapter
`mMapboxMap.getMarkerViewManager().addMarkerViewAdapter(new CustomMarkerAdapter(this.getContext()));`
// add new markerview into mapview
`new CustomMarkerViewOptions().anchor(0.5f, 0.5f).position(marker.getLatLng())`

### Expected behavior
The `onMarkerClick` is always called before `getInfoWindow(@NonNull final Marker marker)`
### Actual behavior
The `onMarkerClick` is never called in this version. Previous SDK version (4.2), the event is always fired before `getInfoWindow(@NonNull final Marker marker)`.

**Comment by tobrun** [comment]
@kingfisherphuoc thank you for reaching out. Instead of hooking into `MarkerClickListener` you will need to hook into `MarkerViewClickListener`.

```java
        mapboxMap.getMarkerViewManager().setOnMarkerViewClickListener(new MapboxMap.OnMarkerViewClickListener() {
          @Override
          public boolean onMarkerClick(@NonNull Marker marker, @NonNull View view, @NonNull MapboxMap.MarkerViewAdapter adapter) {
            Timber.e(marker.toString());
            return false;
          }
        });
```

**Comment by kingfisherphuoc** [comment]
@tobrun I tried with `MarkerViewClickListener` and I have other problems:
1. It's really hard to trigger this event when the `MarkerView` is big and complicated. (My Markerview is 100dp width, and I must click at near the bottom center of Marker to trigger the event, otherwise, nothing occurs).
.2 The `onMarkerClick` is called twice (I am trying to show a dialog when click --> double dialogs occur)
```
 mMapboxMap.getMarkerViewManager().setOnMarkerViewClickListener(new MapboxMap.OnMarkerViewClickListener() {
            @Override
            public boolean onMarkerClick(@NonNull Marker marker, @NonNull View view, @NonNull MapboxMap.MarkerViewAdapter adapter) {
                LogUtils.e("OnClick");
                return false;
            }
        });
```

**Comment by PhanVanLinh** [comment]
@kingfisherphuoc  The onMarkerClick is called twice (I am trying to show a dialog when click --> double dialogs occur). How do you solve this problem?

**Comment by AlexSheiko** [comment]
@kingfisherphuoc, I have the same problem. Using Mapbox 5.0.2

**Comment by grote** [comment]
> Instead of hooking into MarkerClickListener you will need to hook into MarkerViewClickListener.

@tobrun I just ran into this myself and would suggest you at least improve the documentation here.

[MapboxMap#setOnMarkerClickListener()](https://www.mapbox.com/android-docs/api/map-sdk/5.0.2/com/mapbox/mapboxsdk/maps/MapboxMap.html#setOnMarkerClickListener-com.mapbox.mapboxsdk.maps.MapboxMap.OnMarkerClickListener-) says:

    Sets a callback that's invoked when the user clicks on a marker.

This sounds like it would do what I want it to do. For me it is still not clear what the difference to the other method is.

**Comment by tobrun** [comment]
@grote thank you for the ping! I'm not going to add this to the javadoc as we are deprecating markerView in total and you won't be running in this issue anymore since #9365

**Comment by beefarm** [comment]
@tobrun just upgraded from 4.2.0 to 5.2.0, and like others I am seeing the issue of onMarkerCick no longer being fired as mentioned here and in [8159](https://github.com/mapbox/mapbox-gl-native/issues/8159).  My (previously working) code is essentially identical to that of the original poster.  Not clear what the solution is, as early suggestions were to instead use MarkerViewClickListener, but that is apparently being deprecated.

**Comment by tobrun** [comment]
MarkerViews in total have been deprecated not just the clicklistener

**Comment by igor-nm** [comment]
Hi guys, here may not be the right place for this question, but @tobrun would like to know if it is possible to identify a double click on the map marker, or on the map itself, since I need to do an action if a map item have a double click ....

**Comment by tobrun** [comment]
@igor-nm a double tap gesture is recognize as a zoom in gesture. Afaik we don't allow overriding that behaviour though you could try with `MapView#OnTouch`.

**Comment by igor-nm** [comment]
Thank you @tobrun, I go testing this method

**Comment by beefarm** [comment]
@tobrun wrote 

> MarkerViews in total have been deprecated not just the clicklistener

Understood, which is why I asked.  So how does one get a custom onMarkerClick to fire with 5.x (as it did in 4.x but no longer seems to), given that the previously-offered solution of using

`mapboxMap.getMarkerViewManager().setOnMarkerViewClickListener...`

has been deprecated?  I need to fire a custom behavior, and not show an InfoWindow, when a marker is clicked, and that no longer seems to work with 5.x.

Thanks -

**Comment by MAlexanderSalazar** [comment]
So, what should I do to handle the click event for a custom marker? Nothing works.
