### ISSUE TITLE
Changing symbol layer to SourceFunction with runtime styling fails to update rendered layer.

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-native#8237]
**Platform: macos**
**Mapbox SDK version: master**

### Steps to trigger behavior

1. Update the demo app by adding the following lines to `manipulateStyle`:
```objc
    MGLSymbolStyleLayer *labelLayer = (MGLSymbolStyleLayer *)[self.mapView.style layerWithIdentifier:@"country-label-lg"];
    MGLStyleValue *labelColorFunction = [MGLStyleValue<NSColor *> valueWithInterpolationMode:MGLInterpolationModeExponential sourceStops:@{
        @0.0: [MGLStyleValue<NSColor *> valueWithRawValue:[NSColor redColor]],
        @3.0: [MGLStyleValue<NSColor *> valueWithRawValue:[NSColor yellowColor]],
        @6.0: [MGLStyleValue<NSColor *> valueWithRawValue:[NSColor blackColor]],
    } attributeName: @"scalerank" options:nil];
    labelLayer.textColor = labelColorFunction;
```

2. Run the app and select Debug > Manipulate Style

### Expected behavior

The country labels change from black to (data-driven) color with no further user action.

### Actual behavior

Even after the paint transition ends, the country labels remain black.  However, if you use the layer list in the left-hand panel to hide and then re-show the `country-label-lg` layer, then it has the correct colors when it comes back.

**Comment by anandthakker** [comment]
Zooming in a bit after doing "Manipulate Style" does yield the correct colors, which suggests that the problem here involves failing to properly update saved state on the existing `GeometryTile` instances.

**Comment by anandthakker** [comment]
Appears to happen for a fill layer as well, so I think this is a general issue with changing a paint property from non-data-driven to data-driven.

**Comment by anandthakker** [comment]
Okay, so it looks like this issue is limited to setting a data-driven property with with a nonzero _transition_ (duration or delay): setting the following in `maniuplateStyle` avoids the bug.
```
self.mapView.style.transitionDuration = 0;
self.mapView.style.transitionDelay = 0;
```

I think the problem here is:
 - Populating property-function paint vertex buffers happens during (worker-side) layout -- invoked via `style->relayout()`.
 - Setting a paint property to a data-driven value does immediately trigger a relayout, but...
 - ...during a transition between a constant and data-driven property, `UnevaluatedPaintProperty::evaluate()` ==> `util::interpolate()` simply yields the prior value.
 - A property being in transition triggers `style->recalculate()`, to continuously re-evaluate transitioning values, but doesn't (and shouldn't) trigger the more expensive `relayout()`.

Until we're ready to support transitioning with data-driven style properties, I think the fix here is: if the final value is data-driven, then set `Update::Layout`  in `updateFlags`.

**Comment by jfirebaugh** [comment]
Good analysis @anandthakker.

>  if the final value is data-driven, then set `Update::Layout`  in `updateFlags`.

Set this where/when?

>  - ...during a transition between a constant and data-driven property, `UnevaluatedPaintProperty::evaluate()` ==> `util::interpolate()` simply yields the prior value.

([Here.](https://github.com/mapbox/mapbox-gl-native/blob/8a5bff8ee630673c6ebc496322eab94a41ae9353/src/mbgl/style/possibly_evaluated_property_value.hpp#L60-L60)) What does this mean for transitioning the opposite change (source function to constant)? If the `util::interpolate` always returns the initial value, does that mean that we try to use the source function but no longer have a vertex buffer for it?

**Comment by anandthakker** [comment]
> What does this mean for transitioning the opposite change (source function to constant)? If the util::interpolate always returns the initial value, does that mean that we try to use the source function but no longer have a vertex buffer for it?

Good question.  Unless I'm misunderstanding the flow, I think we're safe on this front, for two reasons:
1. The style has [different behavior](https://github.com/mapbox/mapbox-gl-native/blob/8a5bff8ee630673c6ebc496322eab94a41ae9353/src/mbgl/style/style.cpp#L661-L668) when observing a paint property setter, depending on whether the target value is data-driven or not.  If not, it doesn't invoke layout, so we'd still have the vertex buffers.
2. Even if it did invoke layout, the paint property binders are built using the _evaluated_ properties (E.g.: https://github.com/mapbox/mapbox-gl-native/blob/8a5bff8ee630673c6ebc496322eab94a41ae9353/src/mbgl/renderer/circle_bucket.cpp#L18) -- i.e., the output of `util::interpolate`.  So even if a paint property has been set to a constant value, the binder would still create & populate a vertex buffer, because it would see the prior, data-driven value.

**Comment by anandthakker** [comment]
@jfirebaugh here's a draft strategy for hooking into the end of each paint property transition:
 - At the end of `Map::Impl::render()`, save `timePoint` to `this->previousFrameTimePoint`.
 - Add a `previousTimePoint` parameter to `Style::recalculate()`.
 - To `PropertyEvaluationParameters`, add `previousTimePoint` and a `TransitionEndObserver`, whereby the style can get callbacks from its [calls](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/style/style.cpp#L331) to `layer->baseImpl->evaluate(parameters)`.
 - Pass through the `previousTimePoint` parameter to `UnevaluatedPaintProperty::evaluate()`, and use it to determine whether this call is an end-of-transition moment; if so, invoke the observer.

How does that sound?  How many c++/gl-native idioms does this violate 😄 ?
