### ISSUE TITLE
Rendering issues with background

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#825]
Just tested current master and I get this:
![image](https://cloud.githubusercontent.com/assets/1215089/6119210/af0c8756-b07a-11e4-8078-550248e3a378.png)

**Comment by ljbade** [comment]
@ansis Just noting that you said it was fixed in https://github.com/mapbox/mapbox-gl-native/pull/821

I tested on Linux and it was fixed in that PR.

**Comment by incanus** [comment]
That PR fixes it on iOS & OS X as well. Will close here when that merges.
