### ISSUE TITLE
Delay region-related delegate methods until after map view has loaded

### ISSUE THREAD

**Issue by jmkiley** [mapbox/mapbox-gl-native#8260]
`-mapView:regionDidChangeAnimated:` and `-mapViewRegionIsChanging:` (for example) can be called before the map view has finished loading. We may want to explore ways to prevent these methods from being called until after the map view has finished loading.

cc @boundsj

**Comment by boundsj** [comment]
I think that, currently, the region change delegate methods get called in response to application code setting the camera or the `MGLMapView` itself doing its initial camera setup. There is currently nothing that enforces any order of these calls and there is no mechanism to queue camera related calls until after the style / map has finished loading.

**Comment by 1ec5** [comment]
Does MapKit avoid calling `-mapView:regionDidChangeAnimated:` until after `-mapViewDidFinishLoadingMap:`?

**Comment by friedbunny** [comment]
>Does MapKit avoid calling `-mapView:regionDidChangeAnimated:` until after `-mapViewDidFinishLoadingMap:`?

No, MapKit can call `-mapView:regionDidChangeAnimated:` before `-mapViewWillStartRenderingMap:` and `-mapViewWillStartLoadingMap:`, so our current behavior is consistent.

We should probably keep reenforcing to developers that they should avoid using `-mapView:regionDidChangeAnimated:` for anything that requires a fully-loaded map — or that they’ll need to keep track of if the map is loaded themselves.
