### ISSUE TITLE
NSDate(MGLAdditions) turns seconds into nanoseconds

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8264]
`MGLDurationInSecondsFromTimeInterval()` converts an `NSTimeInterval` (measured in seconds) into an `mbgl::Duration` (measured in nanoseconds), but `MGLTimeIntervalFromDurationInSeconds()` reinterprets an `mbgl::Duration` (measured in nanoseconds) as an `NSTimeInterval` without changing its value. As a result, these functions don’t round-trip and `-[MGLStyle transitionDuration]` and `-[MGLStyle transitionDelay]` return the wrong values. We should fix `MGLTimeIntervalFromDurationInSeconds()` to convert back into seconds. [This page](http://en.cppreference.com/w/cpp/chrono/duration) has examples for working with `duration`. We should also add a unit test to ensure round-tripping.

Additionally, the functions’ names incorrectly imply that `mbgl::Duration` is measured in seconds. They should be renamed `MGLDurationFromTimeInterval()` and `MGLTimeIntervalFromDuration()`, respectively.

Finally, #5980 declared and defined these functions within `@interface` and `@implementation` blocks, as though they were category methods, but they aren’t even methods in the first place. The `NSDate(MGLAdditions)` category should be removed, because these functions have nothing to do with NSDate. (These functions should remain in NSDate+MGLAdditions.h, because they relate to `NSTimeInterval`, which is declared in NSDate.h.)

/cc @fabian-guerra @incanus

**Comment by 1ec5** [comment]
`MGLDurationInSecondsFromTimeInterval()` has quite a bit of history:

* mapbox/mapbox-gl-cocoa@08c15cac9df7ac13fa87f45427a9661658befd1d introduced `secondsAsDuration()` as a way to convert a `float` (measuring seconds) into an `std::chrono::steady_clock::duration` (measured in nanoseconds). It made sense to say “seconds” because `float` doesn’t specify any units.
* #3006 renamed it `durationInSeconds()`, since the return type should come before the argument type in a function name.
* #3135 renamed it `MGLDurationInSeconds()`.
* #3576 changed it to accept an `NSTimeInterval` and return an `mbgl::Duration`, making “in seconds” redundant, since `NSTimeInterval` is always measured in seconds.
* #7711 renamed it to `MGLDurationInSecondsFromTimeInterval()` to indicate the argument type explicitly.

Not to point any blame – the naming made sense at the time, but it’s a good thing that we can finally remove “in seconds”!

**Comment by jfirebaugh** [comment]
#8276 addressed the above issues but introduced others (https://github.com/mapbox/mapbox-gl-native/pull/8276/files#r104329402). Keeping this open until those are resolved.

**Comment by jfirebaugh** [comment]
Fixed in #8290.
