### ISSUE TITLE
Merge Android release branches back to master

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8268]
For the v4.2.x release series, @mapbox/android created a series of release branches but continued to commit all changes directly to master, cherry-picking changes that needed to go into the release. These branches were never merged back to master, so the tagged commits (such as 9be38c3586dce71f4ea673a71346d6956fe18876, tagged as android-v4.2.2) have been orphaned.

The release-android-v4.2.2 branch should be null-merged back to master so that the tagged commits can be part of the mainline commit history. (master will end up with a number of duplicate commits to mbgl and Android code. I don’t know of a way to avoid that, other than deleting and retagging those releases.)

/cc @mapbox/mobile @mapbox/gl

**Comment by 1ec5** [comment]
Looking ahead, we’ve branched release-ios-v3.5.0-android-v5.0.0 with the intention of developing the next set of Android and iOS releases in tandem, as with the former release-ios-3.2.0-android-4.0.0 branch. To avoid increasingly messy conflicts in mbgl code, both @mapbox/android and @mapbox/ios need to commit to the same commit strategy. Unless there are strong objections from the core team, I think we should follow the same approach that we did back then: commit most changes directly to the release branch, then merge frequently back to master. PRs merged to master can still be cherry-picked. If a change doesn’t need to go into the next set of releases, it can go into master.

**Comment by jfirebaugh** [comment]
If all the commits were made to master and then cherry-picked to the release branch, what's the purpose of merging the release branch back to master?

**Comment by boundsj** [comment]
My understanding of this issue is that the tags that are used in the GitHub releases are only on the release branch. If they don't make it to the master somehow and the release branch is deleted then the associated previous releases won't be usable anymore.

**Comment by jfirebaugh** [comment]
Tags are independent from branches, and tagged commits are considered reachable and won't be orphaned. (You can think of a tag as a branch that never moves.)

**Comment by zugaldia** [comment]
Thank you @jfirebaugh for the explanation. @1ec5 Based on https://github.com/mapbox/mapbox-gl-native/issues/8268#issuecomment-285743979, are we good to close here?

**Comment by 1ec5** [comment]
Yes, this was a misunderstanding on my part. Thanks for clearing it up, @jfirebaugh!
