### ISSUE TITLE
[iOS] Tracking course when mode is `.follow`

### ISSUE THREAD

**Issue by eimantas** [mapbox/mapbox-gl-native#8270]
**Platform:** iOS
**Mapbox SDK version:** iOS 3.4.2

How would I go about implementing user's course tracking when the tracking mode is `.follow`? The `MGLUserLocationAnnotationView` class that I subclass does not contain the `userLocation` property (it is set only when the tracking mode is `.followWithHeading`). But regardless of the tracking mode (with exception to `.none`) framework could provide the direction, heading and course data on the annotation view.

The reason I need this is to display the "north-up" map view with rotating user's annotation view. I could work around this by weakly capturing the user's annotation view and setting the custom course property on it and then leaving it to the framework to call `update()` but that doesn't feel as a clean solution to my problem.

Any advice is much appreciated.

**Comment by friedbunny** [comment]
You should be able to access `MGLUserLocationAnnotationView.userLocation.location.course` in any active tracking mode. [Here is how](https://github.com/mapbox/mapbox-gl-native/blob/8742dc852c82ef40003a22a8e0a764616d8beed1/platform/ios/src/MGLFaux3DUserLocationAnnotationView.m#L188-L191) we update the user location annotation in `.followWithCourse`, but this should be equally applicable in other modes.

(I verified this using our [custom dot example in iosapp](https://github.com/mapbox/mapbox-gl-native/blob/a5f6ee696367e3311334faa03fb55e215174997f/platform/ios/app/MBXUserLocationAnnotationView.m).)

Heading is not yet available outside of `.followWithHeading` — enabling it in other tracking modes is planned in https://github.com/mapbox/mapbox-gl-native/issues/5523.

**Comment by friedbunny** [comment]
Note that the addition of `MGLUserTrackingMode` to our macOS SDK was mistaken — it’s being made exclusive to iOS in https://github.com/mapbox/mapbox-gl-native/pull/8141. There is not yet any concept of user location in our macOS SDK.
