### ISSUE TITLE
dynamically-linked builds for iOS

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#828]
Carryover from https://github.com/mapbox/mapbox-gl-native/pull/824. We build statically, but we want a `MapboxGL.framework` again. 

 * Ease of installation
 * Swift support
 * CocoaPods simplification

**Comment by incanus** [comment]
See related scripts from old version at https://github.com/mapbox/mapbox-gl-cocoa/tree/f36ee137496c8cf11ab604cacbb63ca645e6741c/pkg.

**Comment by incanus** [comment]
Moving to b2... static is ok for b1, including for #829 CocoaPods.

**Comment by 1ec5** [comment]
We already have Swift support because CocoaPods repackages the static library inside a framework.

**Comment by incanus** [comment]
Good clarification.

**Comment by incanus** [comment]
@1ec5 is gonna take a peek at this for b3, mostly for Carthage https://github.com/mapbox/mapbox-gl-native/issues/1623.

**Comment by incanus** [comment]
Let's punt on this until another release.

**Comment by mikemorris** [comment]
After setting `-fvsibility=hidden` all over in https://github.com/mapbox/mapbox-gl-native/pull/2584, enabling dynamically-linked builds may require prefacing more methods with `MBGL_PUBLIC`.

**Comment by brennanMKE** [comment]
@incanus I have time this week and I'd like to move this forward. Could you task me with specific steps which would get this repo closer to making the build work for bitcode and Carthage? I've learned a lot in the past few weeks and studied the Mapbox build system and could start chipping away at what needs to be done to get it working.

**Comment by incanus** [comment]
Thanks for the offer of help @brennanMKE. I think part of the problem is we don't know the steps, or at least I don't. It probably involves the prebuilt dependencies that we pull down with [Mason](https://github.com/mapbox/mason) as well, and maybe building them in a special way. 

As much as you could put into this would be appreciated. @1ec5 might have some guidelines as he looked into it in the past.

**Comment by mikemorris** [comment]
The primary change to any upstream Mason modules would likely be setting `-fvisibility=hidden` and explicitly exposing a public API with `__attribute__((visibility ("default")))`, but I don't think this will be immediately necessary to resolve any linker issues now that I've taken care of it for GeoJSONVT.

**Comment by 1ec5** [comment]
I got this working for the OS X SDK in #3135. It now looks pretty straightforward to move the iOS SDK over to a proper framework too.

**Comment by mikemorris** [comment]
@1ec5 want to check if the resulting framework gets any smaller when rebasing onto [`898-visibility-hidden`](https://github.com/mapbox/mapbox-gl-native/tree/898-visibility-hidden)?

**Comment by 1ec5** [comment]
Will do. For now, I’ve tested setting `GCC_OPTIMIZATION_LEVEL=-Os` (per the value in Xcode’s framework template), and that has taken the OS X framework size down to 5 MB in Release, compared to 35 MB with `-O3`. So I expect the iOS framework to be smaller than the static library’s 55 MB regardless.
