### ISSUE TITLE
Android Local aar Dependency Can't Find MapboxAccountManager

### ISSUE THREAD

**Issue by bessermt** [mapbox/mapbox-gl-native#8283]
I'm following the First Step instructions for building an app:

[First steps with the Mapbox Android SDK](https://www.mapbox.com/help/first-steps-android-sdk/
)

This works fine, but when I attempt to use Mapbox as a local .aar or .jar, the build doesn't see the MapboxAccountManager.

The basic instructions for doing this are:

File > New > New module and choose Import .JAR/.AAR Package and add the compile dependency to the build.gradle. 

I attempted to grep for the MapboxAccountManager class source, but I don't see it. I assume there is something more I need when building locally in addition to the .aar.  

Note that the First Steps example imports the following:

import com.mapbox.mapboxsdk.maps.MapView;
import com.mapbox.mapboxsdk.maps.MapboxMap;
import com.mapbox.mapboxsdk.maps.OnMapReadyCallback;

If I use the .aar, these all resolve just fine. 

The local .aar resolves these so it is clear that the .aar is properly being referenced. 

However, the MapboxAccountManager isn't being resolved:

import com.mapbox.mapboxsdk.MapboxAccountManager;

How can I resolve the MapboxAccountManager? Where is it located in the source?

**Comment by tobrun** [comment]
Thank you for reaching out, the issue you are hitting seems to be the same as documented in https://github.com/mapbox/mapbox-gl-native/issues/8050. Also note that the MapboxAccountManager was removed in the upcoming release, see the [migration guide](https://github.com/mapbox/mapbox-gl-native/wiki/Android-4.x-to-5.0-update) for more information.

**Comment by bessermt** [comment]
Hi @tobrun, Thanks. 

Is there and example of a working program that uses the upcoming release? 

For example, one like is shown in:

[https://www.mapbox.com/help/first-steps-android-sdk/](https://www.mapbox.com/help/first-steps-android-sdk/)

The migration guide you mentioned isn't working for me. 

For example:

```
<?xml version="1.0" encoding="utf-8"?>

<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:layout="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:mapbox="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.mycompany.myfirstmapboxapp.MainActivityFragment"
    tools:showIn="@layout/activity_main">

    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapview"
        android:layout_width="337dp"
        android:layout_height="411dp"
        android:layout_marginLeft="8dp"
        mapbox:mapbox_cameraTargetLat="41.885"
        mapbox:mapbox_cameraTargetLng="-87.679"
        mapbox:mapbox_styleUrl="@string/mapbox_style_streets"
        mapbox:mapbox_cameraTilt="20"
        mapbox:mapbox_cameraZoom="12"
        layout:layout_constraintLeft_toLeftOf="parent"
        android:layout_marginRight="8dp"
        layout:layout_constraintRight_toRightOf="parent"
        layout:layout_constraintTop_toTopOf="parent"
        android:layout_marginTop="8dp"
        layout:layout_constraintBottom_toBottomOf="parent"
        android:layout_marginBottom="8dp" />

</android.support.constraint.ConstraintLayout>

produces errors like:

Error:(13) No resource identifier found for attribute 'mapbox_cameraTargetLat' in package 'com.example.mycompany.myfirstmapboxapp'

and 

        <service android:name="com.mapbox.services.android.telemetry.service.TelemetryService"/>

Isn't found

Thanks in advance for any assistance.



```

**Comment by tobrun** [comment]
Hey @bessermt, an example implementation can be found in the [mapbox-demo-repo](https://github.com/mapbox/mapbox-android-demo). Feel free to reach out if you have more questions or issues!

**Comment by bessermt** [comment]
@tobrun Cool. Thanks. I just re-did the first steps demo and this time it built. No idea why. I can't see any differences. 

I'll take a look at the mapbox-demo-repo too.

**Comment by bessermt** [comment]
Hi @tobrun, I couldn't get the mapbox-demo-repo to build. Even if I could, I was hoping for something closer to a First Steps. An Hello World for mapbox if you will. 

I also notice there is another .aar file beside mapbox-android-sdk-5.0.0-beta.2.aar. It is called mapbox-android-ui-2.0.0-beta.2.aar.

What is inside these 2 files? How are the different? Do I need both of them? Are there more files I need to build an Hello-Mapbox-World?

Thanks again.

**Comment by codedentwickler** [comment]
Please update the "First steps with the Mapbox Android SDK" on the website to reflect the recent changes in the Android SDK.
