### ISSUE TITLE
Add setMinZoom, setMaxZoom

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8287]
node-mapbox-gl-native should expose `setMinZoom()` and `setMaxZoom()`, as well as `minZoom` and `maxZoom` options, for parity with GL JS and the Android, iOS, and macOS SDKs. These options would be based on `mbgl::Map::setMinZoom()` and `mbgl::Map::setMaxZoom()`, respectively.

/cc @GretaCB @bsudekum

**Comment by GretaCB** [comment]
Thanks for flagging and opening an official ticket around this @1ec5 . I'm pretty bogged down in unpacker world, not sure when I'd be able to jump on this exactly. If you or @bsudekum see the clear path forward and have the bandwidth, that would be awesome, and would help move https://github.com/mapbox/api-gl/pull/727#issuecomment-284319311 across the finish line.

**Comment by jfirebaugh** [comment]
What would the use case for these APIs be? The node bindings are virtually always used in a static rendering context, whereas the typical use for setMin/MaxZoom is to impose constraints on interactive use.

**Comment by 1ec5** [comment]
In that case, should the node bindings unconditionally, automatically set the maximum zoom to the maximum allowed value?
