### ISSUE TITLE
re-enable CocoaPods support

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#829]
Carryover from https://github.com/mapbox/mapbox-gl-native/pull/824. We should install `MapboxGL.framework` when CocoaPods 0.36.0 lands. Depends on https://github.com/mapbox/mapbox-gl-native/issues/828.

**Comment by 1ec5** [comment]
Framework support has been moved to #828. We’re just looking at distributing a static library via CocoaPods for this ticket.

**Comment by incanus** [comment]
Yep, we'll eventually distribute both, I think? Not sure offhand how CocoaPods 0.36.0 (which *just* went stable) handles this.

**Comment by 1ec5** [comment]
I’d prefer to eventually move towards only distributing a framework, because that makes asset distribution easier, and because niceties like inspectables and designables are only possible with frameworks.

**Comment by incanus** [comment]
But then don't we drop iOS 7?

**Comment by 1ec5** [comment]
Yeah, I meant eventually as in someday, when we’re comfortable with dropping iOS 7.

**Comment by incanus** [comment]
Cool, agree :+1:

**Comment by 1ec5** [comment]
This pod depends on a prebuilt binary. See “[Releasing Mapbox GL for iOS](https://github.com/mapbox/mapbox-gl-native/wiki/Releasing-Mapbox-GL-for-iOS)” for release instructions.
