### ISSUE TITLE
Rotate icons relative to map, not screen

### ISSUE THREAD

**Issue by systemed** [mapbox/mapbox-gl-native#8303]
Rotating a symbol with icon-rotate is currently always relative to the screen. So an arrow icon at 45° will point to the same corner of the screen even when the map is rotated.

Example with the style `"icon-rotate": { "property": "ANGLE", "type": "identity" }`:

![upright](https://cloud.githubusercontent.com/assets/694425/23673984/39330f72-036c-11e7-8914-78765b3bc776.png)

The lock is pointing in the direction of the waterway, as it should do.

But when the map is rotated:

![rotated](https://cloud.githubusercontent.com/assets/694425/23674042/677ef5a8-036c-11e7-9930-006cb9765f80.png)

The lock is still pointing to the top left, when I'd like to rotate it with the rest of the map content so that it's still aligned to the waterway.

`"icon-rotation-alignment": "map"` would be the ideal way to specify that the icon should rotate with the map, but doesn't appear to apply to `icon-rotate`d items, only to provide an automatic alignment when no rotation angle is specified. (The above screenshots were taken with `"icon-rotation-alignment": "map"` in the stylesheet.)

Also, 👏👏 for data-driven styles!

(Using iOS SDK 3.5.0.)

**Comment by boundsj** [comment]
In https://github.com/mapbox/mapbox-gl-native/issues/8303#issue-212535557, it appears that you may be trying to add an attribute `"icon-rotation-alignment": "map"` to your feature JSON and you expect that the iOS runtime-styling implementation will discover that specific key value pair and apply it.

Although the data-driven styling functionality in the current Mapbox iOS 3.5.0 betas works somewhat like this (it uses arbitrary key/value pairs in features as input to style functions), the underlying runtime-styling API on iOS works with `MGLStyleLayer` objects and their associated properties.

For example, things works as expected when I set up the layer using the runtime styling API, something like:

```Swift
imageLayer.iconRotation = MGLStyleValue<NSNumber>(rawValue: 45)
imageLayer.iconRotationAlignment = MGLStyleValue<NSValue>(rawValue: NSValue.init(mglIconRotationAlignment: .map))
```

Can you please have a look at the [runtime styling guide](https://www.mapbox.com/ios-sdk/api/3.4.2/runtime-styling.html) and the [relevant API documentation for style layers on iOS](https://www.mapbox.com/ios-sdk/api/3.4.2/Style%20Layers.html) and let us know if using that API addresses this issue? If I'm misunderstanding what you explained in https://github.com/mapbox/mapbox-gl-native/issues/8303#issue-212535557 then please provide more Objective-C or Swift example code (or an example project) that'll help clarify things. Thanks!

**Comment by jfirebaugh** [comment]
I agree with @systemed's assessment as to how this should behave -- I think this may just be a bug in how `icon-rotation-alignment` is applied internally.

**Comment by jfirebaugh** [comment]
@systemed I created a minimal test case ☝️  that I think recreates the situation you're describing, and it renders as expected in both Mapbox GL JS and Mapbox GL Native (current `master`; should be equivalent to iOS SDK 3.5.0). The house icon would normally be upright -- it's rotated 90° by the identity function, and then another 180° by the map bearing:

![image](https://cloud.githubusercontent.com/assets/98601/23725379/255bfe52-0405-11e7-9458-2e6ebcc30133.png)

Are you seeing or wanting some other behavior?

**Comment by systemed** [comment]
Thanks greatly for the testcase which works correctly for me. Having poked around with my original stylesheet a bit, it's now working fine too and I'm not entirely sure what I've changed! I'll reopen if it reoccurs but for now it probably looks like some unspecified error on my part. Sorry for the noise.
