### ISSUE TITLE
Android markerView click listener called twice

### ISSUE THREAD

**Issue by 4BooM04** [mapbox/mapbox-gl-native#8309]
in method OnTap : 
  for (int i = 0; i < count; i++) {
        Annotation annotation = annotations.get(i);
        if (annotation instanceof Marker) {
          if (annotation.getId() == newSelectedMarkerId) {
            Marker marker = (Marker) annotation;
            if (marker instanceof MarkerView) {
              handledDefaultClick = markerViewManager.onClickMarkerView((MarkerView) marker); // here marker click called first time
            } else {
              if (onMarkerClickListener != null) {
                // end developer has provided a custom click listener
                handledDefaultClick = onMarkerClickListener.onMarkerClick(marker);
              }
            }

            if (annotation instanceof MarkerView) { // here marker view click called second time because annotation and marker view is the same object  and instance of MarkerView
              markerViewManager.onClickMarkerView((MarkerView) annotation);
            } else {
              if (!handledDefaultClick) {
                // only select marker if user didn't handle the click event themselves
                selectMarker(marker);
              }
            }

            return true;
          }
        }
      }

**Platform:*Android*
**Mapbox SDK version:*5.0.0-beta2*

### Steps to trigger behavior

 1.Use MarkerView click listener;
 2.Click marker view
 3.Enjoy 

### Expected behavior
marker view click listener called once
### Actual behavior
marker view click listener called twice

**Comment by tobrun** [comment]
@4BooM04 thank you for reaching out and reporting your problem. The PR in https://github.com/mapbox/mapbox-gl-native/pull/8272 will change the interaction MarkerView clicks are handled and will also resolve the twice invoking the MarkerViewClickListener.

**Comment by 4BooM04** [comment]
thanks!
