### ISSUE TITLE
Native marker z-ordering - iOS

### ISSUE THREAD

**Issue by lyptt** [mapbox/mapbox-gl-native#8312]
We're using a lot of native markers in iOS, one thing we're noticing is there's no way to control the z-ordering of markers, unlike MapKit where annotations are normal UIViews.

Is this possible to achieve? Ideally we'd be able to bring whichever annotations we need to the front after they've been added to the map.

**Comment by jfirebaugh** [comment]
Hi @lyptt -- thanks for your question. We're tracking this request in #1728.

**Comment by boundsj** [comment]
Just in case it is helpful, [this example](https://www.mapbox.com/ios-sdk/examples/annotation-views) shows how to use the Mapbox iOS SDK to add annotations backed by [MGLAnnotationView](https://www.mapbox.com/ios-sdk/api/3.4.2/Classes/MGLAnnotationView.html) which is a subclass of `UIView`.
