### ISSUE TITLE
add details on Android supported versions

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#834]
Similar to [`README#ios`](https://github.com/mapbox/mapbox-gl-native#ios) we should detail at least the oldest version supported. @ljbade @bleege

**Comment by ljbade** [comment]
So far it is Android 4.0+ (which maps to API level 14). I plan to expand this to Android 2.3 (API 9). See https://github.com/mapbox/mapbox-gl-native/issues/555

**Comment by ljbade** [comment]
Done.
