### ISSUE TITLE
Expose setStyleJson

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8347]
Atm users can only provide a style with `setStyleUrl(String url)`, capturing from iOS in https://github.com/mapbox/mapbox-gl-native/issues/6386#issuecomment-252351471 that they are planning to expose `setStyleJson()`. This feature would make our API more complete/flexible and would also be handy for debugging purposes.

cc @mapbox/android

**Comment by langsmith** [comment]
[Related demo app example to add](https://github.com/mapbox/mapbox-android-demo/issues/165)

**Comment by tobrun** [comment]
@langsmith the linked issue is related to loading a local style.json file, this issue is about loading a string. You should be able to implement linked issue with any of the 5.x releases.

**Comment by langsmith** [comment]
ah, ok
