### ISSUE TITLE
iOS tile source bridge API

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#836]
Easy to way to use old `RMTileSource` protocol on iOS.

**Comment by Navideck-fotis** [comment]
Definitely need that

**Comment by incanus** [comment]
Related to this, with the recent addition of `-[MGLMapView setMapID:]`, folks will probably expect SDK-style raster layers to work easily.

**Comment by incanus** [comment]
We are splitting the GL `ID`'s into `mapID` and `styleID`. Raster-based sources aren't a priority for b2, but in b3 and later we will be picking this back up.

**Comment by incanus** [comment]
The main problem here is that the `styleID` API expects an HTTP or local style URL. While we could generate a _style_, we can't actually easily host it in a place that GL could consume as a vector style. 

Other ideas: 

- Auto-parse return of `mapbox://` URLs and if TileJSON for rasters, just auto-build a style which shows them. Related: https://github.com/mapbox/mapbox-gl-native/pull/1841

- Add a new protocol (e.g. `mapbox-raster://`) for this. 

- Create a command line tool that helps generate the JSON style around a single raster source for inclusion in an app.

**Comment by incanus** [comment]
As an example, this is all that's required to use a legacy raster map ID in GL: 

```json
{
  "version": 7,
  "name": "Raster",
  "sources": {
    "raster": {
      "type": "raster",
      "url": "mapbox://examples.map-pgygbwdm",
      "tileSize": 256
    }
  },
  "layers": [{
    "id": "raster",
    "type": "raster",
    "source": "raster",
    "paint": {
      "raster-fade-duration": 100
    }
  }]
}
```

**Comment by incanus** [comment]
Use like so: 

```objc
[self.mapView setRasterMapID:@"examples.map-pgygbwdm"];
```

**Comment by incanus** [comment]
:point_right: https://github.com/mapbox/mapbox-gl-native/pull/1844

**Comment by incanus** [comment]
Let's push this from b3; it's a nice hack, but let's take the time to do this right.

**Comment by datwelk** [comment]
Is this work in progress or still waiting to be picked up?

**Comment by friedbunny** [comment]
So far we've not added a legacy-raster-specific API for setting the map style and, at this point, I don't think that we will.

Have no fear, though, because [this example](https://www.mapbox.com/ios-sdk/examples/raster-styles/) shows how to use a Mapbox-hosted raster tile map with this SDK via a custom GL style.
