### ISSUE TITLE
Nightly build workflow lacks s3 upload permissions

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#8364]
The nightly iOS build added in #8337 [fails to upload the result to s3](https://www.bitrise.io/build/6ac700c30bc309e6):

```
* Uploading mapbox-ios-sdk-nightly-dynamic-2017-03-10.zip to s3…
upload failed: ../mapbox-ios-sdk-nightly-dynamic-2017-03-10.zip to s3://mapbox/mapbox-gl-native/ios/builds/mapbox-ios-sdk-nightly-dynamic-2017-03-10.zip
An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Access Denied
```

This workflow appears to be missing the necessary permission to upload to `s3://mapbox/mapbox-gl-native/ios/builds/`, though it _can_ upload to `s3://mapbox/mapbox-gl-native/metrics/binary-size/`.

/cc @kkaefer

**Comment by 1ec5** [comment]
By the way, this is causing the Bitrise badge on the [homepage](https://github.com/mapbox/mapbox-gl-native/) to go red. We may want to disable the scheduled build on Bitrise until we have time to look into this failure.

**Comment by friedbunny** [comment]
Given that the nightly workflow is still generating valuable build size metrics and the fact that the badge doesn’t represent the state of our current working branch anyway, I’d vote to let it stay red for now. I’ll aim to fix this issue today.

**Comment by kkaefer** [comment]
The current [Cloudformation template](https://github.com/mapbox/mapbox-gl-native/blob/bce352bd86f7faf98b3ba5bbb31d3a7860533199/cloudformation/travis.template#L179) only allows uploading to `/mapbox-gl-native/metrics/`. You'll need to add the path here and run the Cloudformation deployment process.
