### ISSUE TITLE
Cannot vary alpha for view presented in MGLMapView

### ISSUE THREAD

**Issue by rchatham** [mapbox/mapbox-gl-native#8365]
Hi! I am trying to vary the alpha of the entire map view to have it fade in and fade out. It seems the view's that are being shown aren't actually exposed. Definitely would like to see this in a future release.

**Platform:** iOS
**Mapbox SDK version:** Latest

### Steps to trigger behavior

`mapView.alpha = 0.5`

### Expected behavior

Map view should fade to have an alpha of 0.5.

### Actual behavior

Map view does not fade.

**Comment by 1ec5** [comment]
`UIView.alpha` isn’t normally supposed to affect subviews, but MGLMapView is somewhat special in that its content is displayed by an embedded GLKView. So I agree that MGLMapView should override `-alpha` and `-setAlpha:` to pass through to the GLKView. As a workaround, you could dig through MGLMapVIew’s `subviews` hierarchy to find the GLKView, or perhaps you could modify MGLMapView’s `layer`’s `opacity` property.

**Comment by incanus** [comment]
@rchatham I just paired with @jmkiley on this to create a test case at https://github.com/incanus/alphatest and we are not seeing the problem. Could you please give that a look and see if that both replicates your scenario as well as works for you?
