### ISSUE TITLE
[iOS] ShowAnnotations incorrectly centered with insets and one annotation

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#8376]
**Platform: iOS 10**
**Mapbox SDK version: 3.4.1**

### Steps to trigger behavior

 1. Set insets to the map (in my case avoid left part of the map screen)
 2. Add an annotation to the map
 3. Show the annotation with ShowAnnotations: api to get centered on it.

### Expected behavior
The map center the annotation in the insets

### Actual behavior
The map center the annotation in the center of the frame

The ShowAnnotations: api (and more generally the _setVisibleCoordinatesBounds: methods) work fine with insets if the user provides more than one marker (more than one coordinate).
But providing only one marker to the ShowAnnotation api will not inset correctly the map. This issue should also be visible on Android.

See screenshots.

The simplest way to correct that is to make setVisibleCoordinatesBounds group of method use setCenterCoordinate in case of a unique coordinate. You might want to correct the algorithm of the 
method _mbglMap->cameraForLatLngs(latLngs, padding) instead.

![simulator screen shot 13 mars 2017 a 14 31 20](https://cloud.githubusercontent.com/assets/8179069/23857031/fd458cbc-07fb-11e7-8aff-291ccb33ec52.png)

![simulator screen shot 13 mars 2017 a 14 32 48](https://cloud.githubusercontent.com/assets/8179069/23857035/0458a304-07fc-11e7-8b6b-273c20c9d627.png)

**Comment by RomainQuidet** [comment]
cameraForLatLngs() method contains several issues with one coordinate:
zoom level computation contains a 0 division in case width and height are 0 (the or condition is incorrect). 
padding is always 0 as minScale is infinity

**Comment by 1ec5** [comment]
Related: #5693.

**Comment by beforeold** [comment]
+1
