### ISSUE TITLE
Animate MGLAnnotation coordinate changes

### ISSUE THREAD

**Issue by petrmanek** [mapbox/mapbox-gl-native#8378]
Hello there,

Is there a way to animate `MGLAnnotation` coordinate changes using Core Animation?

Currently, I'm doing it like this without any animations:
```swift
func changeCoordinate() {
    myAnnotation.coordinate = model.getCurrentCoordinate()
    mapView.setNeedsLayout()
    mapView.layoutIfNeeded()
}
```

I would love to do something like this:
```swift
func changeCoordinate() {
    UIView.animate(withDuration: 1.5, animations: { 
        self.myAnnotation.coordinate = self.model.getCurrentCoordinate()
        self.mapView.setNeedsLayout()
        self.mapView.layoutIfNeeded()
    })
}
```

**Comment by petrmanek** [comment]
Bumping this issue.

I don't need a final solution right now. Somebody please just comment whether animation of annotations has been attempted, and if so, what is the best way to do it at the moment.

Thanks in advance!
Petr

**Comment by boundsj** [comment]
Hi @petrmanek. Currently, an `MGLAnnotationView` can be [implicitly animated using Core Animation](https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.4.2/platform/ios/app/MBXAnnotationView.m#L52-L63). This would allow you to describe an animation that should occur for your view when its annotation coordinate changes like in `changeCoordinate()` above.

**Comment by boundsj** [comment]
Closing this put please feel free to [contact our support team](https://www.mapbox.com/contact) if you have additional questions about how to use our iOS SDK.

**Comment by petrmanek** [comment]
I went back and forth with MapBox support and got 2 takeaways to share:

1. Make sure your MapBox iOS SDK is updated. *(I was using v3.3.7 when v3.5 was the latest version)*
2. Make sure your annotation classes are subclasses of the `MGLPointAnnotation` class.

Then this code should work:

```swift
var myAnnotation = MGLPointAnnotation() // or a subclass

// ...

func changeCoordinate() {
    UIView.animate(withDuration: 1.5, animations: { 
        // Here Core Animation calls MapBox using an implicit animation.
        self.myAnnotation.coordinate = self.model.getCurrentCoordinate()
    })
}
```

**Comment by boundsj** [comment]
Thanks @petrmanek. You may be interested in following [this issue](https://github.com/mapbox/mapbox-gl-native/issues/8489) about an issue with using UIView animation blocks (such as the one in https://github.com/mapbox/mapbox-gl-native/issues/8378#issuecomment-289450780) when the annotation location change takes the annotation view out of the viewport.

**Comment by JanC** [comment]
Hi,
I'm also trying to animate the coordinate change of a `MGLPointAnnotation` subclass. While the above code kind of works, there is one drawback: When the animation takes place, it doesn't seem to be possible to select the annotation via a user tap.

**Comment by arbitur** [comment]
Putting the code where you update the coordinate in an animation block doesnt seem to animated the annotation image. Mapbox v4.1.1

**Comment by djdance** [comment]
this is good, but I cannot click on annotatiun during core animation :-(

**Comment by julianrex** [comment]
@djdance would you mind opening a new ticket? Thanks!
