### ISSUE TITLE
The markerview click area not change

### ISSUE THREAD

**Issue by hchy9777** [mapbox/mapbox-gl-native#8386]
Using Mapbox Android SDK
Mapbox SDK version: 4.2.1

### Steps to trigger behavior

Hi,I found a problem about the click area of the markerview. when the map zoom level change, my markers need become bigger(replaced by a big icon). but i find the click area of markerview is not become bigger, it is still the same as the area when it was created.

### Expected behavior
The click area should be the same size as the markerview icon at any time;
### Actual behavior
The click area is not change when the icon size of markerview change;

**Comment by tobrun** [comment]
@hchy9777 in the upcoming release we are moving click actions back to actual View object in https://github.com/mapbox/mapbox-gl-native/pull/8272. For gl based markers we are tracking optimizing the touch target in https://github.com/mapbox/mapbox-gl-native/issues/8159. Feel free to test out `beta.3` and check if this resolves your issue. Migration guide [here](https://github.com/mapbox/mapbox-gl-native/wiki/Android-4.x-to-5.0-update).Thank you for reaching out!
