### ISSUE TITLE
Remove deprecated notifyMapChange

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8389]
PR in https://github.com/mapbox/mapbox-gl-native/pull/8377 introduced a MapObserver in core with dedicated callback methods for each type of map change event. Our current implementation of notifyMapChange was [deprecated](https://github.com/mapbox/mapbox-gl-native/blob/de9c0748a216d05b15509f1a73086f70067643b2/platform/android/src/native_map_view.hpp#L57) and we should migrate to this new system.

**Comment by brunoabinader** [comment]
Worth noticing that once the `NativeMapView` no longer depens on `mbgl::MapChange`, we can safely remove `src/mbgl/map/change.hpp`.

**Comment by tobrun** [comment]
A follow up PR in https://github.com/mapbox/mapbox-gl-native/pull/8418 from @brunoabinader now also provides some additional error logging when a Map fails to load. While fixing up this issue we look into exposing that API for end developers as current implementation isn't very visible/discoverable for them.

**Comment by brunoabinader** [comment]
FWIW #8443 replaces `onSourceDidChange` with `onSourceAttributionChanged` passing both `sourceID` and `attribution`.

**Comment by tobrun** [comment]
I'm removing the semver-major as we could internally integrate this and keep exposing our public API around MapChange events. The internal integration will help improving gesture performance as noted in #9476.

**Comment by tobrun** [comment]
This has been handled in https://github.com/mapbox/mapbox-gl-native/pull/13050
