### ISSUE TITLE
gl::isPackedDepthStencilSupported & gl::isDepth24Supported on iOS

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#839]
Background in https://github.com/mapbox/mapbox-gl-cocoa/issues/74. 

@ljbade Is this still relevant?

**Comment by ljbade** [comment]
@incanus, without it you will reduce performance

**Comment by incanus** [comment]
Cool, didn't realize this was as simple as it was — just turning on extensions. Should've dug more. Once Travis is :+1: we'll :ship:.
