### ISSUE TITLE
Update project documentation

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8390]
Ticket tracking project documentation changes for `/platform/android`
The current .MD files in our repository for Android our outdated and we need to addmore usefull information for debugging, building and distributing .so and .aar files: 

  - [x] Update documentation with Android IDE integration from #8363
  - [x] Cleanup old wiki pages
  - [x] Review build requirements
  - [x] Cleanup CONTRIBUTING.MD
  - [x] Update test/run documentation in MapboxGLAndroidSDKTestApp
  - [x] ~~update `make android-help` - command with other targets~~
  - [x] ~~add make android-help to documentation~~
  - [x] update ndk-stack documentation 
  - [x] Update distributing with .aar section, apk split and abi filter configuration
      - [x] add link to: https://github.com/mapbox/mapbox-gl-native/wiki/Strategies-to-reduce-Android-APK-size.
  - [x] ~~Add information about style spec changes and code generation~~
  - [x] Update release documentation with Circle CI information
  - [x] Make checkstyle setup discoverable / part of getting started

**Comment by tobrun** [comment]
Added a section in OP, to update release documentation related to CircleCI migration (more specifcally about changing CircleCI config to build a release + changing the config to original state afterwards).

**Comment by zugaldia** [comment]
cc: @langsmith @cammace to help support the effort.

**Comment by cammace** [comment]
Also noting here (not sure if ticketed) that all public methods need to have the corresponding javadoc.

**Comment by tobrun** [comment]
Parts of this issue should still be picked up before a final 5.1.0 release (for this reason, keeping it to this milestone). After fixes have landed we can move this to a 5.2.0 milestone (though it would be great to resolve all the todo's).

**Comment by zugaldia** [comment]
> Parts of this issue should still be picked up before a final 5.1.0 release (for this reason, keeping it to this milestone). 

What work is left (if any) for the current 5.1?

**Comment by tobrun** [comment]
the javadoc was the missing part, that is fixed with #9266, moving to next milestone for now.

**Comment by tobrun** [comment]
NDK stack documentation has been updated [here](https://github.com/mapbox/mapbox-gl-native/wiki/Getting-line-numbers-from-an-Android-crash-with-ndk-stack) to reflect changes in our build system (the .so files are found in a different place).

**Comment by zugaldia** [comment]
@tobrun Looks like all items in OP are now checked, are we good to close?

**Comment by tobrun** [comment]
#9788 is targeting to close this, so once CI approves and PR is merged,  this will be closed ;)
