### ISSUE TITLE
Zoom animation duration

### ISSUE THREAD

**Issue by novo-dimaporo** [mapbox/mapbox-gl-native#8391]
**Platform: Android**
**Mapbox SDK version: Mapbox GL 5.0.0-SNAPSHOT**

Hi, I want to report a trivial bug. Its in animateCamera duration. its a _second_ and _millisecond_ bug.

_mapView lifecycle omitted_

    public class MainActivity extends AppCompatActivity implements OnMapReadyCallback {

    private static final int PERMISSIONS_LOCATION = 9910;
    private static final String TAG = MainActivity.class.getSimpleName();
    private MapboxMap map;
    private MapView mapView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Mapbox.getInstance(this, "TOKEN");

        setContentView(R.layout.activity_main);

        findViewById(R.id.zoom).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                map.animateCamera(CameraUpdateFactory.zoomTo(10), 1000);
            }
        });

        mapView = (MapView) findViewById(R.id.map_view);
        mapView.onCreate(savedInstanceState);
        mapView.getMapAsync(this);
    }

    @Override
    public void onMapReady(MapboxMap mapboxMap) {
        map = mapboxMap;
        Log.d(TAG, "Map ready");
        checkPermissionAndEnableLocation();
    }

    private void checkPermissionAndEnableLocation() {
        if (!PermissionsManager.areLocationPermissionsGranted(this)) {
            ActivityCompat.requestPermissions(this, new String[]{
                    Manifest.permission.ACCESS_COARSE_LOCATION,
                    Manifest.permission.ACCESS_FINE_LOCATION}, PERMISSIONS_LOCATION);
        } else {
            enableLocation();
        }
    }

    private void enableLocation() {
        map.setMyLocationEnabled(true);
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        if (requestCode == PERMISSIONS_LOCATION) {
            if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                enableLocation();
                Toast.makeText(this, "Location permission granted", Toast.LENGTH_LONG).show();
            }
        }
    }
    } 

### Expected behavior
1 second animation duration

### Actual behavior
seems animating forever

I tried settings the duration to 1, and it work.

**Comment by tobrun** [comment]
Thank you for reaching out but I'm not seeing this locally:

![ezgif com-video-to-gif 16](https://cloud.githubusercontent.com/assets/2151639/23907506/a80e412c-08d1-11e7-809a-00d5ea3b02f8.gif)

![ezgif com-video-to-gif 17](https://cloud.githubusercontent.com/assets/2151639/23907587/e6e2281e-08d1-11e7-8a31-22ebb4b60b9d.gif)

Feel free to add more information to the ticket, closing as non reproducible.

**Comment by novo-dimaporo** [comment]
Hello, yes, you're right. My bad, I put an animateCamera inside OnCameraChangeListener, my apology for being impulsive.
