### ISSUE TITLE
-[MGLMapViewDelegate mapViewDidFailLoadingMap:withError:] error is uninformative

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8398]
The error passed into `-[MGLMapViewDelegate mapViewDidFailLoadingMap:withError:]` is an uninformative error. We synthesize this generic error for compatibility with MapKit because mbgl doesn’t actually tell the SDK what went wrong. Per https://github.com/mapbox/mapbox-gl-native/pull/8377#discussion_r105758312, `mbgl::MapObserver::onDidFailLoadingMap()` should accept the error or error message as a parameter. This would allow all the SDKs – not only the iOS and macOS SDKs – to provide more information when the map fails to load for some reason.

/cc @brunoabinader @fabian-guerra

**Comment by brunoabinader** [comment]
👉  #8418.

**Comment by jfirebaugh** [comment]
Is this a duplicate of #8086?

**Comment by 1ec5** [comment]
Yes indeed!
