### ISSUE TITLE
[Android] Location marker not visible with app:mapbox_myLocation="true"

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-gl-native#8399]
**Platform:**  Android
**Mapbox SDK version:**  5.0.0-beta.2 

### Steps to trigger behavior

 1. Include following XML attribute to mapview in activity's layout 

app:mapbox_myLocation="true"

 2. Run Android app
 3. --

### Expected behavior

Visible marker shows user's current location

### Actual behavior

Visible doesn't appear at all

**Comment by mdakram** [comment]
If I see location dot, it's not moving when user's location changes.

**Comment by tobrun** [comment]
This should be actually fixed in beta.3 with https://github.com/mapbox/mapbox-gl-native/pull/8255, can you retest?

**Comment by tobrun** [comment]
Confirmed this shipped with beta.3. Closing.

**Comment by Guardiola31337** [comment]
Confirmed with `beta.3`.

![locationmarker](https://cloud.githubusercontent.com/assets/1668582/23959373/544bb004-09a5-11e7-8b03-10adf1c78b5e.gif)

@langsmith @mdakram Feel free to reach out if you have more questions or issues.

**Comment by langsmith** [comment]
Yes @tobrun and @Guardiola31337 , working for me too on beta.3
