### ISSUE TITLE
Allow null as a filter value

### ISSUE THREAD

**Issue by johanlunds** [mapbox/mapbox-gl-native#8404]
**Disclaimer:** I don't know if this is a bug or feature-request, however I seem to recall testing that this behavior worked on my map in either 5.0.0-beta.1 or if it was 4.2.2 or 4.2.1

**Platform:** Android
**Mapbox SDK version:** 5.0.0-beta.3

### Steps to trigger behavior

 1. Add a GeoJsonSource and a SymbolLayer
 2. Call SymbolLayer `setFilter` with `eq("property", null)` as argument

### Expected behavior

I would expect `eq` filters to be able to match `null` values in addition to the other types (bool, number, strings).

### Actual behavior

It logs:

`E/mbgl: {brain.app.debug}[JNI]: Error setting filter: filter expression value must be a boolean, number, or string`

**Comment by johanlunds** [comment]
After testing this, the actual filtering on the map works. So I guess the logging-statement is the incorrect (and misleading) bug here? Correct?

**Comment by jfirebaugh** [comment]
Not sure how the Android bindings handle this error, but `null` definitely is not currently supported in the core implementation. https://github.com/mapbox/mapbox-gl-js/issues/4410 tracks the equivalent feature request in gl-js.

**Comment by jfirebaugh** [comment]
Null values are now supported with [expressions](https://blog.mapbox.com/announcing-expressions-in-gl-js-a72b55d0a6af).
