### ISSUE TITLE
FocalPoint MyLocationView with padding

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8415]
![ezgif com-video-to-gif 20](https://cloud.githubusercontent.com/assets/2151639/23949273/fa390c6a-0986-11e7-9015-a0fa52d403bd.gif)

**Comment by giperwlad** [comment]
I have a similar problem. When you set padding and change tilt (through
 gesture or animation) location moves to the wrong position.

         Double topPadding = (mapboxMap.getHeight() * 0.80);
         mapboxMap.getMyLocationViewSettings().setPadding(0, topPadding.intValue(), 0, 0);
         mapboxMap.getUiSettings().setFocalPoint(new PointF(mapView.getWidth() / 2, topPadding.floatValue()));

SDK version 5.1.0-beta.4

![videotogif_2017 07 14_10 24 06](https://user-images.githubusercontent.com/20104243/28202550-8d34b7ca-687e-11e7-84d1-c133d33527c1.gif)

**Comment by tobrun** [comment]
@giperwlad that is indeed the same issue, note that we will be deprecating MyLocationView in upcoming releases and will be replacing it with https://github.com/mapbox/mapbox-plugins-android/pull/22. This implementation is build on runtime styling and doesn't have these transfrorm/synchronisation issues.

**Comment by tobrun** [comment]
MyLocationView is going to be replaced with [LocationLayer](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/locationlayer). Feel free to recreate this ticket in that repo.
