### ISSUE TITLE
[Question] Marker and routing limitations

### ISSUE THREAD

**Issue by emmajam** [mapbox/mapbox-gl-native#8417]
Wondering if it is possible to display 200+ markers with a route between them all in a single view?

Cheers!

**Comment by tobrun** [comment]
I advice you to look into [runtime styling](https://www.mapbox.com/blog/runtime-styling-release/):
![ezgif com-video-to-gif 21](https://cloud.githubusercontent.com/assets/2151639/23951157/a2a1cabc-098d-11e7-9256-029689603c69.gif)

If you have more questions feel free to reach out to us on https://www.mapbox.com/contact/.
