### ISSUE TITLE
Location tracking doesn't work

### ISSUE THREAD

**Issue by yperess** [mapbox/mapbox-gl-native#8428]
**Platform: Android 7.1.2 on Nexus 5x**
**Mapbox SDK version: 5.0.0-beta.3**

### Steps to trigger behavior

 1. Download the Mapbox Dev Preview App
 2. Navigate to the "User location" page
 3. Open the "Track user location" demo

### Expected behavior

The my location marker should be visible and the map should follow it

### Actual behavior

I find myself in the middle of Africa (I'm not actually there)

**Comment by tobrun** [comment]
beta.3 hasn't been published yet, see this PR [here](https://github.com/mapbox/mapbox-android-demo/pull/235), feel free to create issues for the demo on that repo. The mentioned issue should be fixed with #8255. Thank you for reaching out, closing this as already resolved.

**Comment by yperess** [comment]
That's strange, I filed this because on my app I tried using beta 3 (which
Gradle resolved) and for about 5 hours couldn't get tracking to work. If I
set a breaking point on MyLocationView's setter for the location I only see
it get called as a result of it registering itself as a listener to the
LocationEngine. No follow-up location updates come in. I replicate it by
doing the same thing, getting an instance of the LocationEngine from
LocationSource, activating it in onCreate, then adding/removing an update
listener in onResume/onPause respectively. What I see is that I get 2 calls
to the listener when I set it, then never again. This was the same in beta
2 and is consistent with what I see in the demo app.

**Comment by tobrun** [comment]
Thank you for adding that information, 
let me try reproducing this use-case, 
thanks again for taking time to report this issue!

**Comment by tobrun** [comment]
Confirmed that we only receive `Last Known Location` and do not receive any follow up events. Adding this to the milestone to be fixed before final release.

**Comment by tobrun** [comment]
Been debugging this on the SDK side and even after specifically requesting for location updates we are not receiving them. I tested the LocationEngine feature in mapbox-java and seeing the same behavior there. Going to create an issue upstream.

**Comment by tobrun** [comment]
Issue created upstream in https://github.com/mapbox/mapbox-java/issues/392

**Comment by tobrun** [comment]
![ezgif com-video-to-gif 27](https://cloud.githubusercontent.com/assets/2151639/24039452/82c12732-0b05-11e7-99a1-55c418f11cad.gif)

**Comment by yperess** [comment]
Nice! Will this be in beta 4?

**Comment by tobrun** [comment]
this will be in the next release, merged with #8445

**Comment by marconealberto** [comment]
I never receive the onLocationChanged events when I change location. I copied and pasted the code from the example, I only get the lastLocation at the beginning. What could it be?
