### ISSUE TITLE
[Android] crash with SIGABRT in release builds

### ISSUE THREAD

**Issue by dbrant** [mapbox/mapbox-gl-native#8432]
**Platform:** Android
**Mapbox SDK version:** 5.0.0.beta3

### Steps to trigger behavior

 1. Build the app as "release" flavor (minifyEnabled = true).
 2. Use MapView as intended.

### Logcat

03-15 17:29:30.396 5852-5852/? E/libc++abi: terminating with uncaught exception of type jni::PendingJavaException
03-15 17:29:30.396 5852-5852/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 5852 (wikipedia.alpha)
03-15 17:29:30.456 983-983/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-15 17:29:30.456 983-983/? A/DEBUG: Build fingerprint: 'Verizon/heroqltevzw/heroqltevzw:6.0.1/MMB29M/G930VVRU4API3:user/release-keys'
03-15 17:29:30.456 983-983/? A/DEBUG: Revision: '14'
03-15 17:29:30.456 983-983/? A/DEBUG: ABI: 'arm64'
03-15 17:29:30.456 983-983/? A/DEBUG: pid: 5852, tid: 5852, name: wikipedia.alpha  >>> org.wikipedia.alpha <<<
03-15 17:29:30.456 983-983/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
03-15 17:29:30.496 983-983/? A/DEBUG:     x0   0000000000000000  x1   00000000000016dc  x2   0000000000000006  x3   0000000000000000
03-15 17:29:30.496 983-983/? A/DEBUG:     x4   0000000000000000  x5   0000000000000001  x6   0000000000000000  x7   0000000000000000
03-15 17:29:30.496 983-983/? A/DEBUG:     x8   0000000000000083  x9   fefeff6d6e68736f  x10  7f7f7f7f7f7f7f7f  x11  0101010101010101
03-15 17:29:30.496 983-983/? A/DEBUG:     x12  0000000000000028  x13  0000000000000000  x14  0000000000000045  x15  0000007faf875888
03-15 17:29:30.496 983-983/? A/DEBUG:     x16  0000007faf86f568  x17  0000007faf80142c  x18  00000000ffffffe0  x19  0000007fafc91290
03-15 17:29:30.496 983-983/? A/DEBUG:     x20  0000007fafc911d0  x21  0000000000000002  x22  0000000000000006  x23  00000000ffffffc8
03-15 17:29:30.496 983-983/? A/DEBUG:     x24  0000007fc907e760  x25  0000007fc907e630  x26  0000007fc907e670  x27  000000000020001d
03-15 17:29:30.496 983-983/? A/DEBUG:     x28  0000007f9007c2cc  x29  0000007fc907e4f0  x30  0000007faf7febc8
03-15 17:29:30.496 983-983/? A/DEBUG:     sp   0000007fc907e4f0  pc   0000007faf801434  pstate 0000000020000000
03-15 17:29:30.506 983-983/? A/DEBUG: backtrace:
03-15 17:29:30.506 983-983/? A/DEBUG:     #00 pc 0000000000069434  /system/lib64/libc.so (tgkill+8)
03-15 17:29:30.506 983-983/? A/DEBUG:     #01 pc 0000000000066bc4  /system/lib64/libc.so (pthread_kill+68)
03-15 17:29:30.506 983-983/? A/DEBUG:     #02 pc 0000000000023a28  /system/lib64/libc.so (raise+28)
03-15 17:29:30.506 983-983/? A/DEBUG:     #03 pc 000000000001e358  /system/lib64/libc.so (abort+60)
03-15 17:29:30.506 983-983/? A/DEBUG:     #04 pc 0000000000437f38  /data/app/org.wikipedia.alpha-1/lib/arm64/libmapbox-gl.so
03-15 17:29:30.506 983-983/? A/DEBUG:     #05 pc 0000000000438060  /data/app/org.wikipedia.alpha-1/lib/arm64/libmapbox-gl.so
03-15 17:29:30.506 983-983/? A/DEBUG:     #06 pc 0000000000435988  /data/app/org.wikipedia.alpha-1/lib/arm64/libmapbox-gl.so
03-15 17:29:30.506 983-983/? A/DEBUG:     #07 pc 00000000004351b0  /data/app/org.wikipedia.alpha-1/lib/arm64/libmapbox-gl.so (__cxa_throw+204)
03-15 17:29:30.506 983-983/? A/DEBUG:     #08 pc 000000000006cd6c  /data/app/org.wikipedia.alpha-1/lib/arm64/libmapbox-gl.so
03-15 17:29:30.506 983-983/? A/DEBUG:     #09 pc 00000000000af7a4  /data/app/org.wikipedia.alpha-1/lib/arm64/libmapbox-gl.so
03-15 17:29:30.506 983-983/? A/DEBUG:     #10 pc 00000000000af6dc  /data/app/org.wikipedia.alpha-1/lib/arm64/libmapbox-gl.so
03-15 17:29:30.506 983-983/? A/DEBUG:     #11 pc 000000000006555c  /data/app/org.wikipedia.alpha-1/lib/arm64/libmapbox-gl.so
03-15 17:29:30.506 983-983/? A/DEBUG:     #12 pc 00000000000652d4  /data/app/org.wikipedia.alpha-1/lib/arm64/libmapbox-gl.so (JNI_OnLoad+8)
03-15 17:29:30.506 983-983/? A/DEBUG:     #13 pc 000000000030fefc  /system/lib64/libart.so (_ZN3art9JavaVMExt17LoadNativeLibraryEP7_JNIEnvRKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEP8_jobjectPS9_+1596)
03-15 17:29:30.506 983-983/? A/DEBUG:     #14 pc 00000000003af3a4  /system/lib64/libart.so (_ZN3artL18Runtime_nativeLoadEP7_JNIEnvP7_jclassP8_jstringP8_jobjectS5_+296)
03-15 17:29:30.506 983-983/? A/DEBUG:     #15 pc 000000000324ab6c  /system/framework/arm64/boot.oat (offset 0x2f5a000)

**Comment by tobrun** [comment]
@dbrant thank you for reaching out and reporting this proguard issue. 
Adding this to the 5.0.0 milestone to look into before the 5.0.0 release.

**Comment by tobrun** [comment]
You can workaround this issue for now by including:

```
-keep class com.mapbox.mapboxsdk.style.functions.** { *; }
-keep class com.mapbox.mapboxsdk.storage.** { *; }

```

in your proguard configuration.

**Comment by dbrant** [comment]
Thanks! The workaround works.

**Comment by tobrun** [comment]
Landed on release branch with #8437

**Comment by HovsepShhakaryan** [comment]
Hello 
I using Mapbox on android, when I don't touch device  5 to 10 minutes application is crashed and give me issue like this.
E/libc++abi: terminating
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 4987 (Worker 1), pid 19586 
How to fix it, thank you in advance.

**Comment by tobrun** [comment]
@HovsepShhakaryan instead of commenting on old closed issues could you open a new one instead? Comments on closed issues often go unnoticed. Would you be able to include the full stacktrace of your crash and mention the used library version? Thank you!

**Comment by HovsepShhakaryan** [comment]
One question more
MapboxGeocoding reverseGeocode = MapboxGeocoding.builder()
                    .accessToken(Config.MAP_BOX_KEY)
                    .query(Point.fromLngLat(-77.03655, 38.89770))
                    .geocodingTypes(GeocodingCriteria.TYPE_ADDRESS)
                    .build();
I want to get address from latitude and longitude but it give me
2020-01-09 18:02:07.821 21960-21960/com.hovsep.bestfleet4u D/Geocode:  MapboxGeocoding{query=-77.03655,38.8977, mode=mapbox.places, accessToken=pk.eyJ1IjoiaG92c2VwIiwiYSI6ImNrNTZiaGUxbTAxaG0zbW9kcHp0d3Bud3AifQ.SYgSqmVIcfAkLQ1EugF6Vg, baseUrl=https://api.mapbox.com, country=null, proximity=null, geocodingTypes=address, autocomplete=null, bbox=null, limit=null, languages=null, reverseMode=null, fuzzyMatch=null, clientAppName=null}

How to fix it???

**Comment by karanveer0802** [comment]
mapbox enable location generates  Crash and show error 
Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 11676 (Worker 1):-
 Code Example:- 
    @Override
    public void onMapReady(@NonNull MapboxMap mapboxMaps) {
        mapInProgress = true;
        mflightMap = mapboxMaps;
        isflightmap = true;
//        mflightMap.getUiSettings().setScrollGesturesEnabled(false);
        flightmapFragment = ((TouchableFlightMapFragment) getSupportFragmentManager().findFragmentById(R.id.map));

        mflightMap.getUiSettings().setZoomGesturesEnabled(false);
        mflightMap.getUiSettings().setTiltGesturesEnabled(false);
        mflightMap.getUiSettings().setCompassEnabled(false);

        mflightMap.setStyle(new Style.Builder().fromUri("https://maps.flightmap.io/styles//style-dark.json"),
                new Style.OnStyleLoaded() {
                    @Override
                    public void onStyleLoaded(@NonNull Style style) {



                                enableLocationComponent(style);


                    }
                });
        Location location = LocationUtils.getLastLocation(this);
        com.mapbox.mapboxsdk.geometry.LatLng currentLatlng = new com.mapbox.mapboxsdk.geometry.LatLng(location.getLatitude(), location.getLongitude());
        mflightMap.moveCamera(com.mapbox.mapboxsdk.camera.CameraUpdateFactory.newCameraPosition(new com.mapbox.mapboxsdk.camera.CameraPosition.Builder().target(currentLatlng).zoom(MAX_ZOOMFLIGHTMAP).tilt(42.25f).build()));
        mapInProgress = false;
        mflightMap.getMaxZoomLevel();

        mflightMap.setMaxZoomPreference(MAX_ZOOMFLIGHTMAP);

        new FlightMapStateListener(mflightMap, flightmapFragment, mActivity) {
            @Override
            public void onMapTouched() {// Map touched
                mapInProgress = true;
            }

            @Override
            public void onMapReleased() {// Map released
                Log.e("Map releasedflightmap", "===");
            }

            @Override
            public void onMapUnsettled() {
                Log.e("Map unsettledflightmap", "===");
                if (updateAddress) {
                    tvLocation.setHint(getStrings(R.string.getting_address_v2).replace(TerminologyStrings.ADDRESS, StorefrontCommonData.getTerminology().getAddress()));
                    tvLocation.setTag(tvLocation.getText());
                    tvLocation.setText("");
                }
            }

            @Override
            public void onMapSettled() {

                Log.e("Map settledflightmap", "===");
//                checkForMyLocationButtonVisibility();
                if (updateAddress) {

                    com.mapbox.mapboxsdk.geometry.LatLng latLng = mflightMap.getCameraPosition().target;
                    NumberFormat formatter = NumberFormat.getNumberInstance();
//
                    formatter.setMaximumFractionDigits(4);
                    String outputLat = formatter.format(latLng.latitude);
                    String outputLong = formatter.format(latLng.longitude);
                    Log.e("outputLat", "" + outputLat);
                    Log.e("outputLong", "" + outputLong);

                    Double distanceCalculated = Utils.getDistance(latitude, longitude, Double.valueOf(outputLat), Double.valueOf(outputLong));

                    tvLocation.setHint(getStrings(R.string.pick_up_location));

                    Log.e("Distance calculated flightmap ", "<<<<" + distanceCalculated);
                    mflightMap.getUiSettings().setScrollGesturesEnabled(true);
                    if (distanceCalculated > 0) {
                        Log.e("Distance", "new" + distanceCalculated);
//                        23173.94921875
//                        1.8658572464858025E-9
                        if (isHomeUpdate) {
                            homeLatLngFlightmp = new com.mapbox.mapboxsdk.geometry.LatLng(latLng.latitude, latLng.longitude);
                            homeLatLng = new LatLng(latLng.latitude, latLng.longitude);
                        } else if (isWorkUpdate) {
                            workLatLngFlightmp = new com.mapbox.mapboxsdk.geometry.LatLng(latLng.latitude, latLng.longitude);
                            workLatLng = new LatLng(latLng.latitude, latLng.longitude);

                        } else if (isOtherUpdate) {
                            otherLatLngFlightmp = new com.mapbox.mapboxsdk.geometry.LatLng(latLng.latitude, latLng.longitude);
                            otherLatLng = new LatLng(latLng.latitude, latLng.longitude);
                        } else {
                            latitude = latLng.latitude;
                            longitude = latLng.longitude;
                        }


                        executeSetAddress();
                        // String address = LocationUtils.getAddressFromLatLng(mActivity, latLng);
                        // tvLocation.setText(address.trim().isEmpty() ? getStrings(R.string.go_to_pin) : address.trim());
                    } else {
                        Log.e("Nodsitance", "===");
                        tvLocation.setText(tvLocation.getTag().toString());
                    }

                    tvLocation.setSelected(true);
                    tvLocation.setFocusable(true);
                }
                updateAddress = true;
                mflightMap.getUiSettings().setScrollGesturesEnabled(true);
                mapInProgress = false;
            }
        };
    }
    private void enableLocationComponent(Style style) {
        if (PermissionsManager.areLocationPermissionsGranted(this)) {
            LocationComponent locationComponent = mflightMap.getLocationComponent();

// Activate with options
            locationComponent.activateLocationComponent(
                    LocationComponentActivationOptions.builder(AddFromMapActivity.this, style).build());

// Enable to make component visible

            locationComponent.setLocationComponentEnabled(true);
        }else {
            permissionsManager = new PermissionsManager(this);
            permissionsManager.requestLocationPermissions(this);
        } }
