### ISSUE TITLE
MarkerView clicked

### ISSUE THREAD

**Issue by hchy9777** [mapbox/mapbox-gl-native#8444]
Using Mapbox Android SDK
Mapbox SDK version: 5.0.0-beta3

Steps to trigger behavior

when I click a markerview, the onMarkerClick and onMapClick method both are called。

Expected behavior

Only the onMarkerClick method is called；

i don't konw it is a bug or not.I just want distinguish the map or markerview is clicked，Is there any good way to do it?

**Comment by tobrun** [comment]
Thank you for the report, PR fixing this in #8447.

**Comment by tobrun** [comment]
Closed with #8447
