### ISSUE TITLE
Rotation bug

### ISSUE THREAD

**Issue by krsticdragan** [mapbox/mapbox-gl-native#8446]
Hi there, 
Im having a issue on Samsung S6 with MapBox 4.2.2 version (android). When im trying to rotate map it often zoom in and out, while in the other phone for example LG Spirit it works fine.

### Steps to trigger behavior

 1. Trying to rotate the map with 2 fingers

### Expected behavior

Rotation of a map

### Actual behavior

Zoom in and out on Samsung S6

**Comment by tobrun** [comment]
Thank you for reaching out, this looks like the same behaviour as mentioned [here](https://github.com/mapbox/mapbox-gl-native/issues/8403). This underlying issue is the way the scale gesture detector in newer Android OS'es. Closing as a duplicate.
