### ISSUE TITLE
Static Map API Draws Polyline as Polygon

### ISSUE THREAD

**Issue by dgngulcan** [mapbox/mapbox-gl-native#8450]
I've been using StaticMap API with no issues but since 2 days, it started to draw the given path unexpectedly.

### Expected behavior
Path to be drawn as polyline

### Actual behavior
Given path is drawn as polygon by connecting first and last points of the given polyline

### Example Request
https://api.mapbox.com/styles/v1/paxira/cizppcdnl00ha2rpdqmreanz0/static/path-5+519D9E-1+519D9E-0(utr%7DD%7BvhdV%7B%40SDAKFQ%5C%3FN%3FGEHWKkAb%40MEm%40NuAx%40%7D%40dAQAe%40SOcAPEOGAGRSEEHM%3Fm%40mAYe%40DD%3FKaAgBsDBcAQCeALmCr%40i%40US%40s%40Ze%40%60%40cDlA_ALi%40%5CsAPi%40h%40WLKEy%40f%40%7DCdAyBlAmEhAkCfAaF%60Bs%40b%40qAT_Bf%40_Bv%40OGG_%40MQk%40iBo%40_AWu%40gByBw%40wA%7B%40%7DC%5BQkAFq%40%60%40e%40SsBKcBb%40oBz%40cBFoOpA%7BDzA_Cb%40uIw%40wB%5BUMaAJcDKgFHoFOwABgAKiAHeFjAyAPSMCM%40%7BAq%40uEkA%7DEEIEDSIGM%40TIHcAp%40eBbBs%40d%40qAh%40aAl%40iCb%40EHaKtCyItCm%40XDFOLgAb%40KL_ALe%40P_GtCaB%60Ai%40d%40aEhC%40HaA%7C%40eAb%40yAbA%7DBjAwBfBqAx%40cAV_Aj%40uCfAa%40FMLuAf%40qAZyAVmD%5EeCJqCCe%40NiFJ_Kh%40oAI%7DDj%40cI%5EkE%5EyBFqATiBB_D%5EYJM%40BGQAm%40PuBVsCRgBd%40mBL_AVgAFa%40NwAPyADgAEk%40NFCIEk%40JeAZgAEaCh%40%7B%40FmACsHtAHHGDiN%5E%7DE%3FOKOF%5DMMD)/auto/1280x720?access_token=ACCESS_TOKEN

**Comment by jfirebaugh** [comment]
cc @bsudekum

**Comment by bsudekum** [comment]
We allow encoded polyline to also be rendered as polygons. The `519D9E-0` in `path-5+519D9E-1+519D9E-0` tells this to render as a polygon. If you remove this option is will render as only a line.
![1280x720](https://cloud.githubusercontent.com/assets/1058624/24058451/5eb15ef4-0b08-11e7-90f7-94d78ebae339.png)

Or if you do want to render this as an actual polygon, set the opacity to something other than 0
![1280x720 1](https://cloud.githubusercontent.com/assets/1058624/24058568/c781660e-0b08-11e7-9a2c-f143a42999cf.png)
