### ISSUE TITLE
Improve LICENSE.md

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#846]
Currently the android project depends on several 3rd party libs, including one that I just keep a copy of the source code in the repo.

Also native (and ios?) uses many 3rd party libs under various licences as well as some libs that we keep as source files.

We need to check what we need to do w.r.t to the different licenses.

Also we should make sure we are not using any GPL libs.

/cc @jfirebaugh @michaelsteffen

**Comment by incanus** [comment]
Per chat, if we include source, we should include the license info. Not sure of best practice re: including it in our own file, having a separate file, or some other approach. 

iOS uses no third-party currently, other than all of Darwin's (iOS & OS X) common usage (with modifications) of [Reachability](https://github.com/mapbox/mapbox-gl-native/blob/4fe94a202bb19499a0baf5795dede51550ee038c/platform/darwin/reachability.m).

**Comment by ljbade** [comment]
@incanus I was reviewing the licenses for a few of the libs we use and the way I read it some of them require a notice in the same location that other licenses are located (basically LICENSE.md) and also in the app. So that means a published demo app would need an about screen with the license text as well as something similar in all end user apps. This is triggered as soon as any bits are in the package. e.g. linking against the lib statically or bundling the lib inside an APK or whatever iOS packages are.

**Comment by ljbade** [comment]
OK going to start working on this and work on a list here:
- [ ]

**Comment by ljbade** [comment]
We should keep this file in alphabetical order.

Also a menu with links to each section would be useful.

**Comment by ljbade** [comment]
Also this file still calls this Mapbox GL.

@jfirebaugh What are we calling this repository/products now?

**Comment by ljbade** [comment]
I think I have covered everything.

Next questions might be around what we do with iOS/Android in-app licence screen.

**Comment by ljbade** [comment]
Oops forgot reachability
