### ISSUE TITLE
Log SDK version

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#8471]
It's sometimes difficult to diagnose an issue when we aren't certain about the version of the code the developer is using. This is particularly true when a developer is using a SNAPSHOT build and we don't know the date that build was published.

To help developers report their current version one solution would be to always log the current SDK version (including date information to help with SNAPSHOTs) during map instantiation. This could be low-priority `verbose` logging.

@mapbox/android Thoughts?

**Comment by tobrun** [comment]
Been thinking about this in context of triggering the user for an update of our library in #7311. Instead of logging the version into logcat we can output the version in the gradle console instead?

**Comment by zugaldia** [comment]
@tobrun That could work too, happy to see the outcome of https://github.com/mapbox/mapbox-gl-native/issues/7311 before moving forward further here.
