### ISSUE TITLE
Android version hud shows the problem

### ISSUE THREAD

**Issue by mister-tang** [mapbox/mapbox-gl-native#8480]
Platform: Android
Mapbox SDK version: 5.0.0

Steps to trigger behavior
1、Add a button

![pin 0 kuom 27mmksoxb7j](https://cloud.githubusercontent.com/assets/7007858/24140835/656fc1e8-0e5c-11e7-9397-5717dd89bede.png)

2、I set up the mapView.setScaleY (-1f)
![a47d4cd01d9aef9fa4e369f795352de4](https://cloud.githubusercontent.com/assets/7007858/24140847/726c2eae-0e5c-11e7-9282-100a66d90d51.jpg)

Flip when the black screen, and I flip how to do when the normal display, thank you

**Comment by tobrun** [comment]
This kind of animation is not supported with SurfaceView, though it should be possible with TextureView. You can enable this different drawing surface with MapboxMapOptions or xml attributes:

> Unlike SurfaceView, TextureView does not create a separate window but behaves as a regular View. This key difference allows a TextureView to be moved, transformed, animated, etc. For instance, you can make a TextureView semi-translucent by calling myView.setAlpha(0.5f).

**Comment by mister-tang** [comment]
@tobrun  Thank you for your reply！
1、Before I was a direct reference to development，for instance,
Compile ('com.mapbox.mapboxsdk: mapbox-android-sdk: version 5.0.0-beta.3@aar') {
         Transitive = true
     }

2、Now according to your suggestion, do I need to make changes in mapbox-gl-native?I tried, there were a lot of mistakes

**Comment by tobrun** [comment]
Here is an example of [TextureView](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java#L56)

**Comment by mister-tang** [comment]
@tobrun Thank you, I have solved, I can go early in the morning
