### ISSUE TITLE
How to shut down Telemtry and FusedLocation provider

### ISSUE THREAD

**Issue by peterneubauer** [mapbox/mapbox-gl-native#8481]
Hi there,
using the 2.0.0-beta.3 for Android, how do I switch off Telemetry when the map is not visible and the app is closed? Users have reported this to be hanging around on the phone.

**Comment by zugaldia** [comment]
Hey @peterneubauer , thanks for the report. There were no changes to how telemetry request location updates with this version (still using the passive location provider during the app's lifecycle). Are you observing anything different?

**Comment by zugaldia** [comment]
@peterneubauer I'm closing this now because this seems to be telemetry working like usual together with the app's lifecycle. Please feel free to reopen if you experience anything differently.
