### ISSUE TITLE
Speed up GeoJSON conversion in GeoJsonSource

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#8483]
Currently, when setting data as a FeatureCollection on a [GeoJsonSource](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.java#L135), the data is serialised to a string, transferred over JNI to the c++ peer object where it is deserialised with rapidJSON. This comes at a high performance penalty.

Instead we should convert straight from the [MAS GeoJson](https://github.com/mapbox/mapbox-java/tree/master/mapbox/libjava-geojson) to [mapbox::geojson::geojson](https://github.com/mapbox/geojson-cpp).

**Comment by jfirebaugh** [comment]
Related: #5623.

**Comment by nitrag** [comment]
Also noticed slow performance compared to iOS. Following.
