### ISSUE TITLE
GeoJSONSource update performance

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#8484]
At the moment, updating a GeoJSONSource with a great number of features takes a long time and blocks the main thread while doing so.

Profiling the current code reveals that for a 1000 features on a Google Pixel it takes around 400ms to update the source of which most time is spent in:

- Conversion to GeoJSONVT classes 139ms
- Setting tile data: 266ms
    - Per tile (slowest tile here):
        - GeoJSONVTPointer#getTile: 225ms
        - total: 228ms

There is a ticket open at https://github.com/mapbox/mapbox-gl-native/issues/6177 to allow for more granular manipulation of the GeoJSONSource's data, which would be beneficial for use cases where only a small amount of features get updated at a time.

For use cases where all the data needs to be replaced, we could consider a a-synchronous update so that at least the UI thread doesn't block while preparing the tiles. It would be important to have the make sure outstanding operations are cancelled when setting new data. It could be confusing to support this in tandem with https://github.com/mapbox/mapbox-gl-native/issues/6177 though as changes made through one api get overridden by the other.

**Comment by yang-owl** [comment]
Hi team, any plans to look at this in the near term?

**Comment by hurrba** [comment]
any updates on this?

**Comment by zugaldia** [comment]
@yang-owl @hurrba thanks for the note - there's still no additional information on our end but we'll make sure to report back as soon as we have more information to share.

**Comment by pozdnyakov** [comment]
GeoJSONSource does not block the main thread any more
