### ISSUE TITLE
Optimise Android Studio C++ formatting

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8485]
At the moment Android Studio indents the namespaces and underlying classes/structs automatically when saving a cpp/hpp file. We need to look into optimizing Android Studio settings and adding this to the project documentation in #8390.

**Comment by kkaefer** [comment]
https://plugins.jetbrains.com/plugin/8396-clangformatij looks like it might be what we're looking for.

**Comment by tobrun** [comment]
It seems that this plugin only does: `runs clang-format on the statement or selection.` What I mean is having a Mapbox C++ InteliJ code style . In AndroidStudio you can find this under `Settings>Editor>CodeStyle>C++`. I start working on one [here](https://gist.github.com/tobrun/b454990ddc58dd8a84ed32af4ca32ac8) but I don't know enough about our C++ code style though.

**Comment by leo-nullptr** [comment]
@tobrun Have you found any solutions?
