### ISSUE TITLE
Implementing Vector tiles on UWP platform

### ISSUE THREAD

**Issue by ImCarrot** [mapbox/mapbox-gl-native#8488]
Hi, I am working on a Universal Windows Platform(UWP) map based application. This issue is regarding the support for UWP platform. I want to know how can I implement MapBox vector tiles on my UWP application. I've gone through the sample projects from Git which allow me to decode .pbf data via a nugget package, the question is, is there any SDK or library I could refer to which would help me show vector tiles on my Bing Map Control? I also wanted to inquire about trying to implement Mapbox Vector tiles via Unity Framework if not the UWP application. Could you please tell me if there is any way to implement Mapbox Vector tiles on a windows 10 (UWP) machine in an app or Unity powered application

List of reference sample libraries and nugget:

1.  https://github.com/mapbox/awesome-vector-tiles
2.  https://www.nuget.org/packages/mapbox-vector-tile/3.1.3

**Comment by BergWerkGIS** [comment]
@ImCarrot This one https://www.nuget.org/packages/Mapbox.VectorTile/1.0.3-alpha1 has assemblies for
* Net20
* Net35
* Net462
* UWP

It will be open sourced in a few weeks.

----

>  I also wanted to inquire about trying to implement Mapbox Vector tiles via Unity Framework if not the UWP application.

`Unity Framework`: you mean `Unity Game Engine` (https://unity3d.com/)?

If yes, we have an SDK for that too: https://www.mapbox.com/unity/

Unfortunately the current version (`v0.4-beta`) is not yet compatible with `Windows Store` (UWP, HoloLens, , ...) export.

But we are working on it, also expect open sourcing in a few weeks.

**Comment by ImCarrot** [comment]
I wanted to know, that like the Android and iOS SDK, like we provide a style link. Will the same be possible for UWP apps as well? Or this will just decode the vector data for me and I'll have to handle map tile source setting by myself?

**Comment by BergWerkGIS** [comment]
> I wanted to know, that like the Android and iOS SDK, like we provide a style link. Will the same be possible for UWP apps as well?

Currently not. No time frame if/when this will be available in a future release.

> Or this will just decode the vector data for me and I'll have to handle map tile source setting by myself?

Yes, just decoding, you have to create and style the Unity objects yourself.
But there are some examples in the SDK how to do it.

If you just want to have a styled background map one option might be to fall back to raster tiles.

**Comment by ImCarrot** [comment]
So, to summarise, there is no SDK for windows platform that would directly interact with the map and provideq it a vector tile source. The link provided in the above comments, helps to decode the vector data into class structure but doesn't create a tile source. Once decoded I will have to convert the decoded data into tiles myself and then provide the map control with the tiles I created. Did I get it right? 

Just a few last ones: can you guide me to a link of the sample where it converts the decoded tile source to a tile?

**Comment by BergWerkGIS** [comment]
Correct, current C#/Unity SDKs only provide access to the raw data, no styling out of the box.

For a `map` implementation you might want to look at `mapbox-sdk-cs` (also to be open sourced within a few weeks): https://www.nuget.org/packages/MapboxSdkCs/ (includes source).

It contains a `map` implementation, but again:
* this takes care of just the data, no styling out of the box
* the `mapbox-sdk-cs` still has `pre-release` status: code itself and the structure of the nuget package (removal of source code) are going to change before being open sourced.

**Comment by ImCarrot** [comment]
oh! okay. Can you please share a sample project which implements the [nugget provided](https://www.nuget.org/packages/MapboxSdkCs/ ) in the last comment? It'll be of great help. Also, is there any timeline as to when would mapbox would support styling out of the box? Or will it even support styling out of the box. Thanks for all the help

**Comment by BergWerkGIS** [comment]
> Can you please share a sample project which implements the nugget provided in the last comment?

As of today `mapbox-sdk-unity` (linked above) is the only sample using `mapbox-sdk-cs`.
Both are still in alpha/beta status.

> Also, is there any timeline as to when would mapbox would support styling out of the box?

As I said above: No time frame if/when this will be available in a future release.
