### ISSUE TITLE
Set pivot (offset, origin) for Rotate Mapview

### ISSUE THREAD

**Issue by Buminta** [mapbox/mapbox-gl-native#8491]
**Platform: Android**
**Mapbox SDK version: 4.2.1**

Hi everybody!
I had a problem with rotate map view
Default Mapview rotate with pivot in centre view frame

![screen shot 2017-03-22 at 6 10 11 pm](https://cloud.githubusercontent.com/assets/5722956/24195466/7651056e-0f2c-11e7-89ac-25166af858ae.png)

But i want modify it!
I need pivot not in centre view frame.
![screen shot 2017-03-22 at 6 10 22 pm](https://cloud.githubusercontent.com/assets/5722956/24195589/e7d155a4-0f2c-11e7-80ff-043c993626b6.png)

However I don't know how to make it!

Can u help me! Thanks so much!

**Comment by tobrun** [comment]
@Buminta The concept you are looking for is focal point, you can overide the default focal point by calling `MapboxMap#getUiSettings().setFocalPoint(PointF focalPoint)`. Feel free to reach out through https://www.mapbox.com/contact/ if you have any other questions!

**Comment by Buminta** [comment]
Thank @tobrun
I'm found it! but I need it use with move camera had bearing!
When i try it. 
A problem conflix two method. Because camera update always use center point for pivot. So sometime pivot's not true when i'm use setFocal
