### ISSUE TITLE
Rendering off

### ISSUE THREAD

**Issue by peterneubauer** [mapbox/mapbox-gl-native#8494]
**Platform:** Huawei Honor 7
**Mapbox SDK version:** 2.0.0-beta.3

Seems on some devices the rendering is pretty off.

![screenshot_2017-03-21-18-12-21](https://cloud.githubusercontent.com/assets/11977/24161328/6060ce06-0e64-11e7-90ed-494c4097517e.png)

### Steps to trigger behavior

 1.
 2.
 3.

**Comment by jfirebaugh** [comment]
Same issue as #8385.
