### ISSUE TITLE
Data-driven runtime styling for Node

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8495]
Basic runtime styling support was added to the Node module in #5318, but it doesn’t include property functions, which were implemented in mbgl in #7372. Currently, you can set property functions via style JSON. This issue tracks adding a way to manipulate them via the runtime styling API.

/cc @kkaefer @bsudekum

**Comment by jfirebaugh** [comment]
Can you say more specifically what you see as missing? The existing bindings pass most of the tests in https://github.com/mapbox/mapbox-gl-js/tree/master/test/integration/render-tests/runtime-styling, which include tests that use property functions.

**Comment by 1ec5** [comment]
@jfirebaugh, I was referring to passing property functions into `setPaintProperty()` from the JavaScript side, going off the discussion in https://github.com/mapbox/mapbox-gl-native/pull/7372#issuecomment-288456557. From a cursory look at node_map.cpp, it didn’t look like there was support for property functions, but if there’s conversion magic going on, we can close this ticket and call it done. 😄

**Comment by jfirebaugh** [comment]
Yep, that should work -- it's handled by the logic in [`style/conversion/function.hpp`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/src/style/conversion/function.hpp).
