### ISSUE TITLE
Issue with S3 Rendering (#8144 Followup)

### ISSUE THREAD

**Issue by tikimcfee** [mapbox/mapbox-gl-native#8497]
**Platform: Android**
**Mapbox SDK version: 5.0.0 Release**

Greetings! This is the followup ticket for #8144 (sorry for the late response!). It looks like the S3 is still having the issues rendering satellite tiles. And, to answer the questions from the above issue:

```
Some follow up questions related to rendering on the s3.
1. Is this an emulator? If yes, are you able to reproduce the issue on an actual device?
2. What Android OS version does this s3 have?
```
1. Nope, it's an actual device - **SPH-L710** _[L710.14 HW Version]_
2. Android version is 4.4.2

Triggering seems pretty easy:
### Steps to trigger behavior

1. Either in the .xml of a MapView, or in the onFinishInflate (if inflating with a LayoutInflater), call `setStyle()` with a satellite-maps based style.
2. Wait for the map to show
3. Satellite imagery sorta pops into place, but is immediately replaced with black / empty tiles.. except it also shows road layer data should your from (1) style include those.

So waddya think?

**Comment by tobrun** [comment]
Could you retest with latest 5.0.1 release? That release addresses rendering issues on that type of devices though without a screenshot/video it's hard to tell. Thank you for reporting!
