### ISSUE TITLE
simplify new duration API

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#850]
While we have some nice shortcuts like iOS [`secondsAsDuration()`](https://github.com/mapbox/mapbox-gl-native/blob/4fe94a202bb19499a0baf5795dede51550ee038c/platform/ios/MGLMapView.mm#L101-L104), this is still really verbose. 

Example: search on `std::chrono::steady_clock::duration::zero()`, which basically means `zero`, used for animation durations: 

![screen shot 2015-02-10 at 5 17 08 pm](https://cloud.githubusercontent.com/assets/17722/6140113/be59f5e4-b148-11e4-993f-8777ddfd6efd.png)

We can `typedef` this or whatever, and it's not super high priority, but it will become more of a hassle once we get back into styling API and transitions a bit and use durations a lot.

**Comment by jfirebaugh** [comment]
Yes, :+1: for something like:

```
namespace mbgl {
  typedef std::chrono::steady_clock::duration duration;
  typedef std::chrono::steady_clock::time_point time_point;
}
```

**Comment by ljbade** [comment]
@jfirebaugh sounds like a good idea, perhaps we should create functions for the other common duration_casts patterns we are using?

**Comment by jfirebaugh** [comment]
Done in #1175.
