### ISSUE TITLE
Factor string ⇢ GeoJSON conversion

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#8500]
We have 4 different implementations of conversion from string to `mapbox::geojson::geojson`:

* [In `geojson.hpp`](https://github.com/mapbox/geojson-cpp/blob/b573989157b868911a4033ca1cd3737f3f0708a9/include/mapbox/geojson.hpp#L31). This should be the only implementation we need.
* In `geojson_source_impl.cpp` ([1](https://github.com/mapbox/mapbox-gl-native/blob/1f8910de186f35216791a17a683a55f01031ec81/src/mbgl/style/sources/geojson_source_impl.cpp#L125-L139), [2](https://github.com/mapbox/mapbox-gl-native/blob/1f8910de186f35216791a17a683a55f01031ec81/src/mbgl/style/sources/geojson_source_impl.cpp#L23-L31))
* In [`android/conversion/geojson.hpp`](https://github.com/mapbox/mapbox-gl-native/blob/62ea1f21858c69f6921c775ba7a3de201f0514d8/platform/android/src/style/conversion/geojson.hpp#L29-L43)
* In [`qt/src/qt_geojson.hpp`](https://github.com/mapbox/mapbox-gl-native/blob/d3ca6c67f1b8fbf5d71c307e71ba89a483ec75bc/platform/qt/src/qt_geojson.hpp#L201-L218)

**Comment by brunoabinader** [comment]
Isn't this the same as provided by https://github.com/mapbox/mapbox-gl-native/pull/8216/commits/84b67d6365f73394c394fd023e8d94f8034290a2 (from #8216)?

**Comment by jfirebaugh** [comment]
Yes, although even there it could be written as:

```C++
template <>
Result<GeoJSON> convertGeoJSON(const std::string& string) {
    try {
        return mapbox::geojson::parse(string);
    } catch (...) {
        return Error { util::toString(std::current_exception()) };
    }
}
```

**Comment by kkaefer** [comment]
The issue with `geojson::parse` is that it doesn't check for parsing errors of the actual JSON code.

**Comment by jfirebaugh** [comment]
That seems like a bug: https://github.com/mapbox/geojson-cpp/issues/31.
