### ISSUE TITLE
Polyline not working on Android

### ISSUE THREAD

**Issue by andresteves** [mapbox/mapbox-gl-native#8503]
**Platform:** Windows 10 / Android 5.1
**Mapbox SDK version:** 5.0.0

### Steps to trigger behavior

 1.  
```
map.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {

                // Customize map with markers, polylines, etc.
                mapboxMap.addMarker(new MarkerOptions()
                        .position(new LatLng(40.748473, -73.985591))
                        .title("Empire State Building")
                );

                mapboxMap.addMarker(new MarkerOptions()
                        .position(new LatLng(40.749237, -73.981410))
                        .title("Carnegie Hall")
                );

                mapboxMap.addMarker(new MarkerOptions()
                        .position(new LatLng(40.753130, -73.982193))
                        .title("Seagram Building")
                );

                mapboxMap.addMarker(new MarkerOptions()
                        .position(new LatLng(40.754159, -73.979797))
                        .title("New York State Theater")
                );

                mapboxMap.addMarker(new MarkerOptions()
                        .position(new LatLng(40.761354, -73.975613))
                        .title("Chrysler Building")
                );

                mapboxMap.addPolygon(new PolygonOptions().addAll(list).fillColor(Color.parseColor("#8A8ACB")));

                mapboxMap.addPolyline(new PolylineOptions()
                        .addAll(listTour)
                        .color(Color.parseColor("#3bb2d0"))
                        .width(2));
            }
        });
```
 2. Using a fragment (Markers are displaying correctly and so it is Polygon)
 3. Try and run

### Expected behavior
Polyline should appear

### Actual behavior
No visible polyline between markers (Polygon is the purple area)
![device-2017-08-02-185333](https://user-images.githubusercontent.com/645072/28887141-f9ea4f8a-77b3-11e7-881e-5777e0d3cafa.png)

**Comment by ivovandongen** [comment]
@andresteves I've tried out the example code in an Activity and a Fragment for mapbox 5.0.0 and 5.0.1 and it seems to work well. Could you provide a minimal reproduction case?

The changes I made to the test app on master to try and reproduce this:
[patch.diff.zip](https://github.com/mapbox/mapbox-gl-native/files/882249/patch.diff.zip)

**Comment by samvgorode** [comment]
Trying to add poly-line with two way points finishes without success. I see two markers, but line is not visible. Android 6.0.1, compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.2@aar')

**Comment by samvgorode** [comment]
I've deleted my last comment because I've found a mistake. 
You see, when I added 2 markers: 
my location & destination location, I got position of marker from LatLng object, where constructor is
`public LatLng(double latitude, double longitude)`. First LAT second LON!
BUT when I add polyline, I add it by Position object, constructor of position is 
`private Position(double longitude, double latitude, double altitude)`. First LON second LAT!

It confused me a lot.

**Comment by andresteves** [comment]
Hi @samvgorode and @ivovandongen,

I believe that was my mistake as well for not paying enough attention to how Position object is built.
I am working in another solution for now but always happy to know that was my mistake.

Thanks for the help

**Comment by ivovandongen** [comment]
@samvgorode @andresteves Glad you found the issue(s) yourself. The reason for the seemingly inverted coordinates is that Position is modelled after the GeoJSON standard which uses lon, lat ordered coordinates. Sorry for the confusion.

**Comment by andresteves** [comment]
Please read first post for the updates please. 
No polyline appearing just markers and polygon. 30 is the number of points that makes the polyline.

Thanks in advance.

**Comment by andresteves** [comment]
Hi,

I was finally able to show the Polyline on the map but there is a problem when creating the Polyline in the async method. So I end creating it outside in the onCreate method and adding it on the getMapAsync.

```
@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        polylineOptions = new PolylineOptions().addAll(listTour)
                .color(Color.parseColor("#3bb2d0"))
                .width(3);
    }
```

```
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_tour, container, false);

        map = (MapView) view.findViewById(R.id.mapTourView);

        map.onCreate(savedInstanceState);



        map.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {

                mapboxMap.addPolyline(polylineOptions);
            }
        });
```

Hope this helps someone with the same problem.
