### ISSUE TITLE
Long press triggered when tapping on a marker

### ISSUE THREAD

**Issue by jidesoft** [mapbox/mapbox-gl-native#8504]
**Platform:** 
Android
**Mapbox SDK version:**
5.0
### Steps to trigger behavior

 1. I called setOnMapLongClickListener and getMarkerViewManager().setOnMarkerViewClickListener to MapView. 
 2. When I tap a marker which will trigger my own callback to the marker as expect, butI noticed the LongClickListener is also called. 

### Expected behavior
I don't expect LongClickListener to be called

### Actual behavior
LongClickListener is always called

**Comment by Emeritus-DarranKelinske** [comment]
I have to long press a marker for it to stay displayed. If i just short press it goes away within less than a second. Not sure if they are related. Thank you!

**Comment by tobrun** [comment]
#8585 reverts touch changes made for the 5.0.0 release, we are planning a 5.0.2 shortly containing this fix. Thank you for reaching out closing.
