### ISSUE TITLE
Sync versions between platforms

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#851]
With @bleege' new gradle system that uploads builds to maven, we need to work out how to sync the versions codes so that the Android version matches whatever native is using.

Currently native pulls it's version from the last git tag. However it doesn't appear to support the snapshot vs release Android now has.

I think we need to work out how new releases of native will work too.

Should the npm package also use the same version as native and Android?

How do iOS releases work? Since they are just source (or will there be something like maven for iOS - cocoapods?)

**Comment by incanus** [comment]
Yes, CocoaPods is similar to Maven. We'd likely tag (i.e. name) a release, have a build generated automatically, and that would replace the old precompiled binary and update the version number in the podspec file (which is in this repo, at least until we release stable in the global CocoaPods specs database). 

> we need to work out how to sync the versions codes so that the Android version matches whatever native is using

Can't we just call them the same thing, i.e. Mapbox GL `x.y.z` regardless of platform? And snapshot vs. release would just be two different tags?

**Comment by ljbade** [comment]
@incanus Yeah I was wanting to keep the versions the same. I guess we will need to change `script/build-version.py` to handle release vs snapshot.

So what would the tags look like?

`v0.1.0` for release and `v0.1.0-snapshot` for snapshot?

**Comment by bleege** [comment]
**Stupid Question: Does it matter if GL iOS and GL Android releases always have the same version numbers?**

Over time release cycles for iOS and Android are likely to diverge due to bug fixes, platform specific features, etc just like the current raster SDKs.  I'm not sure it'll really matter to end users as long as we communicate with them.  That said we'll definitely need to keep an internal matrix of what version of GL Core is in what version of the the platform SDKs.

**Comment by incanus** [comment]
The way I used to do this in `gl-cocoa` was to include a `versions.txt` (but this could also be programmatic) that recorded the Git hashes for both it and `gl-native`. We could do a similar thing with tagging the repo as a whole, but then also tag like `x.y.z-ios` or whatever for specific OS releases. Yes @bleege, I do think they would likely want to naturally diverge.

**Comment by ljbade** [comment]
I think the release cycles may diverge over time. Perhaps we have separate version numbers for each component? e.g. if the native API has a breaking change then it's version is bumped, but if the Android/iOS API can mask it without breaking their APIs then we would not need to increase their version.

Question then is what do git tags become? Do we have separate tags for native, iOS and Android releases?

**Comment by ljbade** [comment]
Of course the other version in this mix is the currently supported style version which is an interesting question. When a new release comes out that adds some features that break existing styles so the style version increases, do developers have to update their map styles at the same time as they upgrade the library version?

**Comment by bleege** [comment]
Cool.  I'd just suggested we use `platform-x.y.z` instead of `x.y.z-platform` convention for tags as it'll help keep it more human friendly.

**Comment by ljbade** [comment]
@bleege makes sense

**Comment by bleege** [comment]
Looks like iOS is already using `vx.y.z` for milestones.  I'll switch Android to `android-vx.y.z` and see how it plays.

**Comment by incanus** [comment]
@mikemorris and I hashed this out in detail yesterday as relates to the mobile platforms and Node — doc forthcoming.

**Comment by incanus** [comment]
https://github.com/mapbox/mapbox-gl-native/wiki/Versions-and-tagging

**Comment by mikemorris** [comment]
Can we flip the "Core Tags" and "Per-platform Tags" sections? If we're working in feature branches, when a feature/fix is stable and merged we should probably increment the core tag. If we happen to release an iOS/Android/node build at the same time, tagging the same commit may make sense, but core tags should be driving the tagging, not just acting as duplicates of platform tags.

Example:
Changing the public JavaScript API of the node bindings would be a semver major breaking change, but if no code is changed in core, core would not need to be tagged.

**Comment by incanus** [comment]
I don't mind the idea of flipping the sections, but I want to clarify something. 

> If we're working in feature branches, when a feature/fix is stable and merged we should probably increment the core tag.

The way we've been doing this is to accumulate a number of features before tagging a release. People who want to use the bleeding-edge would then just follow `master` in between tags. Are you proposing then @mikemorris that we tag more frequently?

**Comment by jfirebaugh** [comment]
I think we need some clarification on what the purpose of "Core tags" is, exactly.

**Comment by mikemorris** [comment]
> Are you proposing then @mikemorris that we tag more frequently?

Eh, not necessarily. I've generally followed the "accumulate several features then tag a release" strategy for node too.

> I think we need some clarification on what the purpose of "Core tags" is, exactly.

My intent with core tags would be to capture new features or breaking changes in the core lib, such that developers working on platform implementations have a better idea of what's moved since their last release. `ios-v2.0.0` tells me the iOS public API changed, but it doesn't tell me that we moved from `v7` styles to `v8` for example.

**Comment by jfirebaugh** [comment]
Based on the last few releases, I think we want to allow the platform SDKs to bump their versions independently, though they may be kept roughly in sync as a function of our overall development and release cycle.
