### ISSUE TITLE
Marker#setIcon does not respect anchor points when changing to a larger icon

### ISSUE THREAD

**Issue by austinwulf** [mapbox/mapbox-gl-native#8511]
**Platform:** Android
**Mapbox SDK version:** 4.2

### Steps to trigger behavior

 1. Have a marker with a custom icon on the map with an anchor point at bottom center.
 2. Using `Marker#setIcon`, set the marker's icon to a larger image.
 3. The anchor point will be not be updated to the bottom center of the new, larger image.

### Expected behavior
The marker should be reanchored to the same anchor point on the new image.

### Actual behavior
The marker retains the anchor point on the old image.

![screen shot 2017-03-23 at 10 54 11 am](https://cloud.githubusercontent.com/assets/6163742/24259877/ce4ae920-0fb7-11e7-8823-78c192bbd8e0.png)
![screen shot 2017-03-23 at 10 54 26 am](https://cloud.githubusercontent.com/assets/6163742/24259878/ce4de864-0fb7-11e7-9c65-d35f1c7de248.png)

**Comment by tobrun** [comment]
Thank you for the report, PR fixing this in #8519
