### ISSUE TITLE
Changing content insets after setVisibleCoordinateBounds leads to the coordinate bounds to no longer match what was provided in setVisibleCoordinateBounds

### ISSUE THREAD

**Issue by ivanmkc** [mapbox/mapbox-gl-native#8512]
**Platform:** iOS
**Mapbox SDK version:** 3.4.2

### Steps to trigger behavior

 1. Call mapView.setVisibleCoordinateBounds with or without content insets
 2. Call self.mapView.setContentInset(edgeInsets, animated: true)

### Expected behavior
The coordinate bounds provided in step 1 should still be visible after step 2, and the edge insets updated.

### Actual behavior
Not sure exactly what happens, but coordinate bounds are off.

**Comment by boundsj** [comment]
Thanks for the report @ivanmkc. Can you please provide a few more details?

- What is the value of the `MGLCoordinateBounds` you are setting in step 1?
- What are the top, left, bottom, and right properties of the `edgeInsets` value in step 2?
- What is the value of the `automaticallyAdjustsScrollViewInsets` property on the view controller containing your map at the time `setContentInset()` is called?
- What is the value of the map view's `contentInsets` and `visibleCoordinateBounds` after you update them? 
- What values are you expecting to see?

If you can provide a code example that illustrates all of the above then it'll help us address this issue faster. Thanks!
