### ISSUE TITLE
Black Map after download offline regions

### ISSUE THREAD

**Issue by simonskali** [mapbox/mapbox-gl-native#8518]
Hello everybody,
I would like to use mapbox on xamarin.iOS platform. I found nuget that wraps native sdk into C#. 
I am trying to download offline regions via background thread. Immediately after that, when i am trying open (create) MapBox.MapView, map is not rendered (black). 
It takes ~2 minutes to refresh. After this period of time, everything works fine. When i don't use offline regions download, everything works just fine.
Has anybody idea what could be wrong? Any experience with xamarain & mapbox? 
Also tried download it on UIThread with same result (not ok).

*edit*
nuget i used was published 2/21/2017 by Xamarin

Thanks for any advice.

Simon

**Platform:**
Xamarin.iOS
**Mapbox SDK version:**
nuget version 3.3.7
### Steps to trigger behavior

 1.Set AccessKey in MapBox.AccountManager.AccessToken
 2.Download region in background thread ( OfflineStorage.Shared.AddPack() )
 3.Create instance of MapBox.MapView
 4.Black Map is displayed for ~2 minutes

### Expected behavior
Map rendered normally 
### Actual behavior
Black Map is displayed for ~2 minutes

**Comment by jfirebaugh** [comment]
Hi @simonskali. This issue was fixed in v3.4.0 of the iOS SDK, and there have been many other bug fixes and improvements since 3.3.7. I strongly encourage you to upgrade! :)
