### ISSUE TITLE
Auto Correct on Search cuts off after the word "and" iOS

### ISSUE THREAD

**Issue by JessicaG** [mapbox/mapbox-gl-native#8523]
**Platform:**
iOS
**Mapbox SDK version:**
ios-v3.4.2

### Steps to trigger behavior
 1. Search for a place with the word "AND" in it aka "Hand and Stone Massage"
 2. See results change after the word "Hand" to the word "and" and then "stone"
![output_cau4cu](https://cloud.githubusercontent.com/assets/957528/24315891/924bb00a-10af-11e7-90b3-e738c451669f.gif)

### Expected behavior
1. Search for a place with the word "AND" in it aka "Hand and Stone Massage"
2. See results change to include the first and the second word

### Actual behavior
See Triggered Behavior steps

**Comment by boundsj** [comment]
Hi @JessicaG. This repo is where we work on the vector map library for native applications. The map library itself does not offer geocoding APIs. Maybe you are asking about https://github.com/mapbox/MapboxGeocoder.swift?

**Comment by 1ec5** [comment]
Search term tokenization is controlled by the Mapbox Geocoding API on the server side; neither Mapbox GL Native nor MapboxGeocoder.swift has control over that behavior. Please report this issue to our geocoding team using the [Mapbox Geocoder Feedback](https://www.mapbox.com/geocoder-feedback/) tool. Thanks!
