### ISSUE TITLE
“Data-driven styling” guide discusses camera-driven styling

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8525]
The “[Data-driven styling](https://www.mapbox.com/ios-sdk/api/3.5.0/data-driven-styling.html)” guide talks about every kind of style function, including camera functions, which are driven by the camera rather than by data. To the extent that “data-driven styling” is useful terminology, we shouldn’t blur the lines between it and runtime styling as a whole. Either information about camera-driven styling should be pared back, or this guide should be renamed to “Setting style attribute values”. (The “Information for style authors” guide already has a “Setting attribute values” section, but that guide is focused on comparing the style JSON format to the runtime styling API.)

/cc @jmkiley @ericrwolfe @friedbunny

**Comment by jmkiley** [comment]
That makes sense. It may be worthwhile to convert it to a Working With Style Functions guide and expand the guide to include more about working with camera and composite style functions.

**Comment by boundsj** [comment]
For now, I made a few edit that I think may get us by in https://github.com/mapbox/mapbox-gl-native/pull/8627. I like the idea of adding more details about camera and composite functions specifically in the future but I don't think that needs to be done for the v3.5.1 patch release.

**Comment by boundsj** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/8627 on the `release-ios-v3.5.0-android-v5.0.0` on the release branch.
