### ISSUE TITLE
Version Branch

### ISSUE THREAD

**Issue by bessermt** [mapbox/mapbox-gl-native#8527]
I'm wondering how I can get the source for various version. For example, if I build the master branch, what version am I building? Also, if I want a specific version, how do I get that version? 

The answer may be obvious, but I'm reasonably new at git, so the answer may be staring me in the face an I'm not seeing it. 

Thanks.

**Comment by friedbunny** [comment]
On the [releases page](https://github.com/mapbox/mapbox-gl-native/releases), look at the individual releases — they will include tags and commit hashes that you can checkout locally. E.g., https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.5.0:

![screen_shot_2017-03-26_at_3_02_01_pm](https://cloud.githubusercontent.com/assets/1198851/24334257/51c02566-1235-11e7-85cd-892903f4fbbc.png)

You would then `git checkout ios-v3.5.0` and do all of the setup steps (`git submodule update && make clean && make distclean && make iproj`) to reset to that point in time.

**Comment by trasch** [comment]
I tried this, but it doesn't work...

> git clone https://github.com/mapbox/mapbox-gl-native.git && cd mapbox-gl-native
> git checkout ios-v3.5.0
> git submodule init && git submodule update && make clean && make distclean && make iproj
> make iframework

Lots of errors like this:
```
❌  /Users/me/test/mapbox-gl-native/include/mbgl/util/enum.hpp:22:32: instantiation of variable 'mbgl::Enum<mbgl::style::TranslateAnchorType>::begin' required here, but no definition is available [-Werror,-Wundefined-var-template]

        auto it = std::find_if(begin, end, [&] (const auto& v) { return s == v.second; });
```

or 

```
❌  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Users/me/test/mapbox-gl-native/build/ios/mbgl.build/Debug-iphonesimulator/mbgl-core.build/Objects-normal/x86_64/logging_nslog.o (No such file or directory)
```

or

```
▸ Linking Mapbox

❌  ld: library not found for -lmbgl-core

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

▸ Linking Mapbox

❌  ld: library not found for -lmbgl-core


❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

❌  fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/me/test/mapbox-gl-native/build/ios/ios.build/Debug-iphonesimulator/dynamic.build/Objects-normal/i386/Mapbox (No such file or directory)
```

Any ideas? (It does work for the *master* branch though)

**Comment by friedbunny** [comment]
@trasch That first issue is caused by new clang warnings in Xcode 8.3 — if you need to build `ios-v3.5.0`, you can use Xcode 8.2 or follow [these instructions](https://github.com/mapbox/mapbox-gl-native/issues/8561#issuecomment-290442639) to disable `-Werror`.

**Comment by trasch** [comment]
@friedbunny Thanks, that worked!
