### ISSUE TITLE
Issues building MapboxSDK for android due build changes

### ISSUE THREAD

**Issue by ragaisis** [mapbox/mapbox-gl-native#8531]
**Platform:** Android
**Mapbox SDK version:** 5.0.1

I need to build forked mapbox SDK for Android. Previously I was building with:

```
make  distclean
make android
make android-lib-x86

```

Then I copy pasted all MapboxSDK folder into my project. There where .so files that were build by calling above commands and building mapbox SDK for Android. And app was working with customized Mapbox SDK. 

Now Android MapboxSDK build has changed and I can't import SDK into my project, because it depends on mapbox-gl-native folder structure. The only way that I could make my app work is to put my application near the MapboxGLAndroidSDKTestApp, adapt app structure as TestApp has and launch project. 

But I want to have my project in separate folder, not in mapbox-gl-native/platform/android directory that is strongly dependant on mapbox updates.

Can you explain me if I'm building Android Mapbox SDK wrong? Or what steps should be taken to build a little bit customised (based on project needs)  Android MapboxSDK version and how should I import it into my project.

**Comment by tobrun** [comment]
The changes in the Android Build system were made to have Android Studio integration  (coding/compiling/debugging c++ directly in the IDE) for this project in  https://github.com/mapbox/mapbox-gl-native/pull/8363 . This requires us to hook into the C++ files found in folders outside of `platform/android`.I would advice you to make your changes in your fork build SDK into an `aar` and use that binary in your projects. Feel free to ask any follow up questions but closing this as non-actionable from our end as having AS integration is the way forward for us.
