### ISSUE TITLE
Add check for 16-bit `highp` value

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-native#8533]
Since #8183 (and the followup in #8496), we are packing pairs of colors into a single `highp vec4`. This strategy means that we have a hard requirement for `highp` providing at least 16 bits of precision.

It's possible that [this color bug](https://github.com/mapbox/mapbox-gl-native/issues/8385#issuecomment-289418069) _could_ be caused by a device that doesn't provide 16-bit `highp`s.

We can add a check at startup, using [`glGetShaderPrecisionFormat`](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glGetShaderPrecisionFormat.xml), so that if a device doesn't have enough precision, we fail with an error message instead of trying to proceed.

**Comment by tobrun** [comment]
LMK if you want to do some CI testing on this, very interested in running this against +220 devices.

**Comment by anandthakker** [comment]
Do we have any good way to expose a flag controlling whether or not this information gets logged?

Relatedly: there are a couple of unit tests that make assertions based on logging output, and adding this diagnostic logging will mess them up, e.g. [here](https://github.com/mapbox/mapbox-gl-native/blob/master/test/api/repeated_render.test.cpp#L80).
