### ISSUE TITLE
[ios] visibleFeatures:in: styleLayerIdentifiers returns duplicate features

### ISSUE THREAD

**Issue by idrougge** [mapbox/mapbox-gl-native#8537]
**Platform:** iOS
**Mapbox SDK version:** 3.5.0

### Steps to trigger behavior

 1. Create custom layer in a map style based on custom tilemap/dataset
 2. 

        func mapView(_ mapView: MGLMapView, regionDidChangeAnimated animated: Bool) {
        self.features = mapView.visibleFeatures(in: mapView.frame,
                                                styleLayerIdentifiers: layeridentifiers)
        }
3.
```
print(#function, "Number of visible features in MapView:", features.count)
for f in features {
            let featureLocation = CLLocation(latitude: f.coordinate.latitude, longitude: f.coordinate.longitude)
            let distance = location.distance(from: featureLocation)
            print("\(f.coordinate.latitude)°/\(f.coordinate.longitude) (\(Int(distance)) m. away)",f.identifier ?? "no identifier",f.attributes)
}
```

### Expected behavior
```
checkFeatures(in:against:) Number of visible features in MapView: 5
59.3271202297373°/18.0631005764008 (496 m away) 1 ["name": Strömsborg]
59.3259325323915°/18.0657076835632 (298 m away) 2 ["name": Riddarhuset]
59.324246697147°/18.0695271492004 (20 m away) 3 ["name": Bedoirgränd]
59.3260146326218°/18.0668449401855 (263 m away) 4 ["name": Bondeska palatset]
59.3232231135207°/18.0674564838409 (147 m away) 5 ["name": Gamla stans t-bana]
```
### Actual behavior
```
checkFeatures(in:against:) Number of visible features in MapView: 12
59.3271202297373°/18.0631005764008 (496 m away) 1 ["name": Strömsborg]
59.3259325323915°/18.0657076835632 (298 m away) 2 ["name": Riddarhuset]
59.3260146326218°/18.0668449401855 (263 m away) 4 ["name": Bondeska palatset]
59.3271202297373°/18.0631005764008 (496 m away) 1 ["name": Strömsborg]
59.3259325323915°/18.0657076835632 (298 m away) 2 ["name": Riddarhuset]
59.3260146326218°/18.0668449401855 (263 m away) 4 ["name": Bondeska palatset]
59.3271202297373°/18.0631005764008 (496 m away) 1 ["name": Strömsborg]
59.3259325323915°/18.0657076835632 (298 m away) 2 ["name": Riddarhuset]
59.3260146326218°/18.0668449401855 (263 m away) 4 ["name": Bondeska palatset]
59.3271202297373°/18.0631005764008 (496 m away) 1 ["name": Strömsborg]
59.3259325323915°/18.0657076835632 (298 m away) 2 ["name": Riddarhuset]
59.3260146326218°/18.0668449401855 (263 m away) 4 ["name": Bondeska palatset]
```

**Comment by jfirebaugh** [comment]
This is expected behavior, as described in [the documentation](https://www.mapbox.com/ios-sdk/api/3.5.0/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)visibleFeaturesAtPoint:inStyleLayersWithIdentifiers:predicate:):

> Features come from tiled vector data or GeoJSON data that is converted to tiles internally, so feature geometries are clipped at tile boundaries and features may appear duplicated across tiles. For example, suppose the specified point lies along a road that spans the screen. The resulting array includes those parts of the road that lie within the map tile that contain the specified point, even if the road extends into other tiles.

**Comment by idrougge** [comment]
Is this also the reason why `MGLVectorSource.features(sourceLayerIdentifiers: predicate:)` returns the same `MGLFeatures` with slightly differing coordinates upon each call?

**Comment by jfirebaugh** [comment]
The results from `MGLVectorSource.features` will be clipped at tile boundaries in the same way as the `visibleFeatures` APIs, yes.

**Comment by idrougge** [comment]
Thanks.

Is there any way to get at the underlying dataset so as to get definitive values for an MGLFeature? The GeoJSON API doesn't appear to have a Swift implementation yet.
