### ISSUE TITLE
Bitrise ⇢ CircleCI

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#8551]
We should investigate moving mapbox-gl-native builds off Bitrise and onto CircleCI's [2.0 Beta](https://circleci.com/beta-access/).

Bitrise:

* Does not provide a way to version control the root build script.
* Does not provide a way to version control the build image.
* Does not provide a way to control either of the above on a per-branch basis.
* Updates build images on a weekly basis, with no way to pin to a stable image.
* Has a clunky and slow UI.
* Does not offer auto-build cancelling.

These issues have and will continue to contribute to build instability and wasted team time. We've raised them to the Bitrise team on many occasions without satisfactory response.

cc @mapbox/gl @mapbox/android @mapbox/ios

**Comment by friedbunny** [comment]
According to the current [2.0 FAQ](https://circleci.com/docs/2.0/faq/), Android is “unofficially” supported and iOS is as-yet unsupported.

- [1.0 iOS docs](https://circleci.com/docs/1.0/ios-builds-on-os-x/)
- [1.0 Android docs](https://circleci.com/docs/1.0/android/)
- [Currently available macOS container](https://circleci.github.io/macos-image-tests/) — OS X 10.11.6. Xcode 8.2.1, no 8.3 betas. Pre-installed homebrew, fastlane, carthage, etc.

**Comment by jfirebaugh** [comment]
We switched Android over. Holding on other platforms until CircleCI has better multi-job and/or macOS/iOS support.

**Comment by jfirebaugh** [comment]
CircleCI workflows are here! We should switch over our Linux builds on Travis to Circle, since it's much faster.
