### ISSUE TITLE
[iOS] build fails with Xcode 8.3

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#8558]
**Platform: iOS 10.3**
**Mapbox SDK version: 3.4.2**

### Steps to trigger behavior

 1. launch make -f Makefile ipackage-strip FORMAT=static BUILDTYPE=Release
 2.
 3.

### Expected behavior
Compilation worked with Xcode 8.2

### Actual behavior
▸ Compiling log_nslog.mm

❌  /Users/mappy/Documents/mapbox-gl-native/include/mbgl/util/enum.hpp:17:32: instantiation of variable 'mbgl::Enum<mbgl::EventSeverity>::begin' required here, but no definition is available [-Werror,-Wundefined-var-template]

        auto it = std::find_if(begin, end, [&] (const auto& v) { return t == v.first; });
                               ^

▸ Compiling nsthread.mm
▸ Compiling reachability.m
▸ Compiling run_loop.cpp
** BUILD FAILED **

**Comment by kkaefer** [comment]
This build failure is due to Clang adding another warning and has been fixed in the 3.5.0 release.

**Comment by RomainQuidet** [comment]
ok thanks, moving to 3.5.0 then !

**Comment by friedbunny** [comment]
The [`ios-v3.5.0`](https://github.com/mapbox/mapbox-gl-native/tree/ios-v3.5.0) tag still exhibits this issue — if you need to build that version, use Xcode 8.2 or follow [these instructions](https://github.com/mapbox/mapbox-gl-native/issues/8561#issuecomment-290442639) to disable `-Werror`.
