### ISSUE TITLE
iOS Styles

### ISSUE THREAD

**Issue by onato** [mapbox/mapbox-gl-native#856]
I tried to set up an iOS project but ran into a number of issues around the style files.

The first issues is that MGLMapView will not read a style file out of a subdirectory of a .bundle file.

If I read the file myself and use setRawStyle to set the style it gets a step further but fails later inside Map::Map after successfully setting the style without supplying a useful error message.

I am using https://github.com/mapbox/mapbox-gl-native/commit/4a8311e838.

Also I didn't find any instructions as to which Libraries I should link with. Are these the right ones?

![bindwithlibraries](https://cloud.githubusercontent.com/assets/107999/6143634/83e6433e-b1cc-11e4-89af-b9518d73e847.png)

**Comment by onato** [comment]
Sorry, I started writing this last night. In the mean time this was posted. Same issue https://github.com/mapbox/mapbox-gl-native/issues/852.

**Comment by incanus** [comment]
@onato I don't think you need `CoreImage`, but otherwise, yes. 

For the styling stuff, stay tuned. This is getting shuffled around a bit right now. Anything related to setting style JSON as opposed to `useBundledStyleNamed()` or anything around programmatic style changes is in flux right now.
