### ISSUE TITLE
MyLocationTrackingMode changes unexpectedly

### ISSUE THREAD

**Issue by rlaendle** [mapbox/mapbox-gl-native#8560]
**Platform:** Android 7.1.1
**Mapbox SDK version:** 5.0.1

### Steps to trigger behavior

 1. In mapbox-android-demo project open the `LocationTrackingActivity` class (see https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/location/LocationTrackingActivity.java )
 2. In method `enableLocationTracking()` replace `map.getTrackingSettings().setDismissAllTrackingOnGesture(false);` by `map.getTrackingSettings().setDismissAllTrackingOnGesture(true);` 
 3. Start the LocationTrackingActivity and additional start a mock location app (e.g. Fake GPS).

### Expected behavior

If I do not execute any gesture on the screen of the android device, `MyLocationTrackingMode` should not change.

### Actual behavior

After a short time, without touching anything on the screen, `MyLocationTrackingMode` changes from `TRACKING_FOLLOW` to `TRACKING_NONE`.
Note that this behavior does not appear, when `MyBearingTrackingMode` is set to `NONE`.

**Comment by rlaendle** [comment]
The issue still is reproducible with latest Mapbox SDK release 5.0.2.

**Comment by tobrun** [comment]
Thank you for providing the information to reproduce. There is a race condition when MyLocationView sets dismissing tracking to disable while performing the animation (this animation is posted to the end of message queue). Posting dismissing the tracking mode resolves this. Ran a test for 10+ minutes without seeing the issue from OP.

**Comment by SylvainHocq** [comment]
Hello, 
i reproduce the bug again with v5.1.0-beta-1, in android 7.0

I have configured map to TRACKING_FOLLOW. 
And after 5mn the tracking was automatically set to NONE.
