### ISSUE TITLE
Change -Werror

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#8561]
Clang 3.9 added `-Wundefined-var-template` which made our older branches fail to build because we also use `-Werror`, which turns warnings (harmless in this case) into errors.

A blog post about this topic: https://blog.flameeyes.eu/2009/02/future-proof-your-code-dont-use-werror/

**Comment by jfirebaugh** [comment]
> Just add a switch, a know, a line to comment in and out, so that -Werror is used by default on developers builds but not on the normal user releases.

I think I agree with this post, in that it's saying to use `-Werror` during development (which I would say includes CI) but to omit it from released source packages (tarballs or similar). Is what you're saying? Or are you suggesting to drop it in development processes as well?

**Comment by kkaefer** [comment]
Yeah, I was thinking along those lines. The one thing I'm unsure about is enabling it on CI. Of course we would like to catch errors during development, and failing CI is a good way to enforce that, but it also means that it might become harder to build old branches on CI in a newer build environment (like the Clang 3.9 -`Wundefined-var-template` case) in case we have to patch an older branch.

**Comment by jfirebaugh** [comment]
I think we derive enough benefit from enforcing warning-free code via CI that it's worth keeping, even if that means we have to update the code when a new compiler version is released.

We should prevent it from breaking old branches in CI by using CI providers that allow us to strictly control the build environment on a per branch bases.

**Comment by roblabs** [comment]
After upgrading to Xcode 8.3, I was attempting to build iOS v3.4.1, SHA 01ceae1a8e1d64251744e357bd4f3335853ff663.  I needed to replicate this build to debug some changes I made in a personal branch.

With Xcode 8.3 (and hence, Clang), I was not able to build.

Thankfully, @kkaefer's notes helped give me a clue.   I edited this line in [CMakeLists.txt](https://github.com/mapbox/mapbox-gl-native/blob/a9896fa01b72f260940c3b5df4eec0c1b73dce26/CMakeLists.txt#L65)  and removed `-Werror`, and I was able to make a build.

Without the change to CMakeLists.txt, builds failed with older mapbox-gl-native branches.

This is the Clang version in macOS 10.12.4 + Xcode 8.3,

```
roblabs@air:~ $ clang --version
Apple LLVM version 8.1.0 (clang-802.0.38)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

----
Compiler warnings after removing `-Werror` were similar to 

```
⚠️  ~/mapbox-gl-native/include/mbgl/util/enum.hpp:22:39: instantiation of variable 'mbgl::Enum<mbgl::style::TextAnchorType>::end' required here, but no definition is available [-Wundefined-var-template]

        auto it = std::find_if(begin, end, [&] (const auto& v) { return s == v.second; });
                               ^
```

**Comment by jfirebaugh** [comment]
Per above, I don't think we want to make any changes here.
