### ISSUE TITLE
Add more node test

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-native#8564]
* all assets fail to load
* assets timeout
* release map before assets load

Doing all of these but at scale inside a large loop. Ideally, we could also monitor memory to make sure everything is released once the map is destroyed/released.

/cc @tmpsantos

**Comment by tmpsantos** [comment]
I have a few tests on the works here:
https://github.com/mapbox/mapbox-gl-native/tree/tmpsantos-node_tests
