### ISSUE TITLE
Static analyzer warning about memory management in -[UIImage(MGLAdditions) initWithMGLSpriteImage:]

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8570]
The static analyzer is reporting a memory management error [in `-[UIImage(MGLAdditions) initWithMGLSpriteImage:]`](https://github.com/mapbox/mapbox-gl-native/blob/1616140a95fce22d51ae13bcf3af36c0e9eea571/platform/ios/src/UIImage+MGLAdditions.mm#L21):

```
/path/to/mapbox-gl-native/platform/ios/src/UIImage+MGLAdditions.mm:21:5: Incorrect decrement of the reference count of an object that is not owned at this point by the caller
```

#7812 modified this method to split the call to `CGImageCreate()` out into a separate method, but it left the call to `CGImageRelease()` in place. In practice, there isn’t a problem with this arrangement right now because we release after every call to `CGImageFromMGLPremultipliedImage()`. But we’re violating [the Create rule](https://developer.apple.com/library/content/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029), and any future usage of this method will be more likely to leak memory as a result.

/cc @kkaefer

**Comment by 1ec5** [comment]
This also shows up as the following static analyzer warning in mbgl-core:

```
/path/to/mapbox-gl-native/platform/darwin/src/image.mm:50:5: Potential leak of an object
/path/to/mapbox-gl-native/platform/darwin/src/image.mm:33:9: Assuming the condition is false
/path/to/mapbox-gl-native/platform/darwin/src/image.mm:41:9: Assuming the condition is false
/path/to/mapbox-gl-native/platform/darwin/src/image.mm:50:12: Call to function 'CGImageCreate' returns a Core Foundation object of type CGImageRef _Nullable with a +1 retain count
/path/to/mapbox-gl-native/platform/darwin/src/image.mm:50:5: Object returned to caller as an owning reference (single retain count transferred to caller)
/path/to/mapbox-gl-native/platform/darwin/src/image.mm:50:5: Object leaked: allocated object is returned from a function whose name ('CGImageFromMGLPremultipliedImage') does not contain 'Copy' or 'Create'.  This violates the naming convention rules given in the Memory Management Guide for Core Foundation
```

**Comment by akitchen** [comment]
I might suggest two things here:

 - Rename `CGImageFromMGLPremultipliedImage()` to `CGImageCreateWithMGLPremultipledImage()` (in line with the Create Rule pointed to above)
 - If the rename doesn't provide enough of a hint to the static analyzer, we would also need to annotate the function so that the static analyzer can better understand what's going on. I forget if `__attribute((ownership_returns(malloc)))` is the way to go, or whether there's a CoreFoundation-specific annotation to use. 

/cc @1ec5

**Comment by akitchen** [comment]
Verified the rename is enough to satisfy the static analyzer here. I'll put a pr together.

**Comment by akitchen** [comment]
Fixed via https://github.com/mapbox/mapbox-gl-native/pull/10570
