### ISSUE TITLE
Static analyzer warnings — MGL*StyleFunction initializers

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8571]
The static analyzer in Xcode 8.2 caught several issues in `-[MGLCameraStyleFunction initWithInterpolationMode:stops:options:]`, `-[MGLSourceStyleFunction initWithInterpolationMode:stops:attributeName:options:]`, and `-[MGLCompositeStyleFunction initWithInterpolationMode:stops:attributeName:options:]`:

```
Core Foundation/Objective-C Group
/path/to/mapbox-gl-native/platform/darwin/src/MGLStyleValue.mm:144:5: Returning 'self' while it is not set to the result of '[(super or self) init...]'
/path/to/mapbox-gl-native/platform/darwin/src/MGLStyleValue.mm:144:5: Returning 'self' while it is not set to the result of '[(super or self) init...]'
/path/to/mapbox-gl-native/platform/darwin/src/MGLStyleValue.mm:187:9: Instance variable used while 'self' is not set to the result of '[(super or self) init...]'
/path/to/mapbox-gl-native/platform/darwin/src/MGLStyleValue.mm:187:9: Instance variable used while 'self' is not set to the result of '[(super or self) init...]'
/path/to/mapbox-gl-native/platform/darwin/src/MGLStyleValue.mm:207:5: Returning 'self' while it is not set to the result of '[(super or self) init...]'
/path/to/mapbox-gl-native/platform/darwin/src/MGLStyleValue.mm:207:5: Returning 'self' while it is not set to the result of '[(super or self) init...]'
/path/to/mapbox-gl-native/platform/darwin/src/MGLStyleValue.mm:257:9: Instance variable used while 'self' is not set to the result of '[(super or self) init...]'
/path/to/mapbox-gl-native/platform/darwin/src/MGLStyleValue.mm:257:9: Instance variable used while 'self' is not set to the result of '[(super or self) init...]'
/path/to/mapbox-gl-native/platform/darwin/src/MGLStyleValue.mm:277:5: Returning 'self' while it is not set to the result of '[(super or self) init...]'
/path/to/mapbox-gl-native/platform/darwin/src/MGLStyleValue.mm:277:5: Returning 'self' while it is not set to the result of '[(super or self) init...]'
```

The cause is lines [like this](https://github.com/mapbox/mapbox-gl-native/blob/1616140a95fce22d51ae13bcf3af36c0e9eea571/platform/darwin/src/MGLStyleValue.mm#L131) that check `self == [super init]` without explicitly setting `self = [super init]`. The only reason we avoid crashing in this case is that the super implementation in NSObject does set `self` explicitly.

Was this an oversight, or was it a way to circumvent the MGLStyleFunction initialization code? If the latter, we should find a way to silence the warnings, perhaps by calling a private MGLStyleFunction initializer.

/cc @boundsj

**Comment by boundsj** [comment]
Closed by https://github.com/mapbox/mapbox-gl-native/pull/9030 on the `release-ios-v3.6.0-android-v5.1.0` branch.
