### ISSUE TITLE
Not able to select MarkerView

### ISSUE THREAD

**Issue by IonAalbers** [mapbox/mapbox-gl-native#8573]
Using the latest SDK, I'm not able to keep the selected state of a `MarkerView`.
The `MarkerViewAdapter` received a `onSelect` which is followed by a `onDeselect`, therefor not possible to keep the selected state.

It can be avoided by setting `setDeselectMarkersOnTap(false)` because the GestureListener causes the `AnnotationManager.deselectMarkers()` to be called.

**Platform: Android 7.1**
**Mapbox SDK version: 5.0.1** 

### Steps to trigger behavior

 1. Use the MainActivity class that is added to this issue
 2. Tap the marker
 3. Marker gets selected, but immediately deselected 

[MainActivity.txt](https://github.com/mapbox/mapbox-gl-native/files/880655/MainActivity.txt)

### Expected behavior
Marker stays selected.

**Comment by Emeritus-DarranKelinske** [comment]
+1

**Comment by tobrun** [comment]
#8585 reverts touch changes made for the 5.0.0 release, we are planning a 5.0.2 shortly containing this fix. Thank you for reporting this!
