### ISSUE TITLE
[iOS] Get center of a MGLStyle & get layer of a MGLFeature?

### ISSUE THREAD

**Issue by fleuverouge** [mapbox/mapbox-gl-native#8574]
**Platform: iOS **
**Mapbox SDK version: 3.4.1**

Hi,
I know that we can get a style's center point via web services, however [the current API](https://www.mapbox.com/api-documentation/#retrieve-a-style) returns too much more information than needed (ie the very long list of layers). After loading a style, I need to move the map camera to that style's center. So I wonder if I can get this info from the style object itself, instead of sending request to the web services?

Also, in the `MapView.visibleFeaturesInRect:` method, which returns a list of MGLFeature objects,  I need to specify each object's layer for later use. Is there anyway to accomplish this?
Any suggestion is welcomed. Thanks in advance!

**Comment by jfirebaugh** [comment]
> After loading a style, I need to move the map camera to that style's center. So I wonder if I can get this info from the style object itself, instead of sending request to the web services?

Not directly, but you can call [`-[MGLMapView resetPosition]`](https://www.mapbox.com/ios-sdk/api/3.5.0/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)resetPosition) to reset the map to the current style’s default viewport.

> Also, in the `MapView.visibleFeaturesInRect:` method, which returns a list of MGLFeature objects, I need to specify each object's layer for later use.

If you're asking whether there's a way to obtain information about the layer to which the feature belongs, no, but we're tracking the request in #7162.
