### ISSUE TITLE
TransitionOptions conversion when set

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8575]
When looking into adding transition properties for layer attributes in #8015. I noticed that the style wide configuration of TransitionOptions in https://github.com/mapbox/mapbox-gl-native/pull/7711 is not returning the same values as the value set. Eg. following test is failing:

```java
long transitionDuration = 1;
mapboxMap.setTransitionDuration(transitionDuration);
assertEquals("TransitionDuration should match", transitionDuration, mapboxMap.getTransitionDuration(), 0);
```
with 
```
AssertionFailedWithCauseError: TransitionDuration should match expected:<1.0> but was:<1.0E9>
```
Looking at the [style specification](https://www.mapbox.com/mapbox-gl-js/style-spec/#transition-duration), it seems that the unit should be in milliseconds while it nows seems to be set in seconds and returned in nano seconds.

**Comment by 1ec5** [comment]
> it seems that the unit should be in milliseconds while it nows seems to be set in seconds and returned in nano seconds.

The intention was to match the expected time unit on the platform, regardless of the style specification’s units. On iOS and macOS, the expected unit would be seconds. It looks like the Android implementation suffered from the same issue as #8264, which was subsequently fixed on iOS and macOS by correctly round-tripping seconds values.
