### ISSUE TITLE
onCameraChange() called with GeoJsonSource.setGeoJson()

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#8579]
**Platform:** Android
**Mapbox SDK version:** 5.0.0-beta.3 - 5.0.1 (not reproduce on 5.0.0-beta.2)

### Steps to trigger behavior
call GeoJsonSource.setGeoJson(String json)

### Actual behavior
MapboxMap.OnCameraChangeListener.onCameraChange() is called (but real camera position not changed)

### Expected behavior
MapboxMap.OnCameraChangeListener.onCameraChange() not call with setGeoJson()

**Comment by tobrun** [comment]
We recently changed the map change event that we use to hook in our camera change listener. The previous implementation didn't succeed in delivering the final end position of the camera. I'm linking https://github.com/mapbox/mapbox-gl-native/issues/6350 as we are planning to improve our camera change listener experience. We will be picking up this as part of #6350. Thank you for the report @klblk!
