### ISSUE TITLE
[ios][swift] Make MGLFeature hashable

### ISSUE THREAD

**Issue by idrougge** [mapbox/mapbox-gl-native#8584]
**Platform:** iOS
**Mapbox SDK version:** 3.5.0

Classes conforming to `MGLFeature` (e.g. `MGLPointFeature`) conform to `Hashable` protocol by offering the `hashValue` property. The abstract `MGLFeature` class does not, however, even though it does have a property by the name `hash`.

**Comment by 1ec5** [comment]
MGLFeature is an Objective-C protocol, not a class. This could be a limitation of Swift bridging; none of the MGLFeature classes explicitly become hashable, since they inherit from NSObject.

**Comment by lightandshadow68** [comment]
Ran into this while Inserting a MGLPointFeature into a Set in swift, which is very expensive memory and time wise. Ended up subclassing MGLPointFeature and hashing the feature's identifier, which was set to a string identifier of the object it represents.

**Comment by lightandshadow68** [comment]
Went to remove my override from the subclass, as I'm no longer using Sets and the problem still persists with Array on Swift. Will file a separate bug.
