### ISSUE TITLE
POI and Highway Shields Chopped off at Tile Boundaries in Still mode

### ISSUE THREAD

**Issue by lincomatic** [mapbox/mapbox-gl-native#8587]
When rendering still images (rasters), symbols and text can get cut off at tile boundaries.

In zoom 16 image below note the park at the right tile boundary labeled "Sib"

![image](https://cloud.githubusercontent.com/assets/1422186/24521496/35662708-1541-11e7-85ab-bec31889b766.png)

Zoom to 17 and the full name, "Sibrie Park," appears

![image](https://cloud.githubusercontent.com/assets/1422186/24521562/6eacf8de-1541-11e7-93e2-7565d4abd03b.png)

The problem is caused by the fact that collisions are not coordinated between tiles. At zoom 16, the park is rendered in the left tile. However, in the right tile, due to collision with street names it doesn't render.

This phenomenon varies in frequency depending on theme. Here is a particularly nasty example:

![image](https://cloud.githubusercontent.com/assets/1422186/24520680/28f59c90-153e-11e7-9b73-5b856bdb9f0b.png)

**Comment by lincomatic** [comment]
Leaflet code to reproduce Sibrie Park sample above:

```
<!DOCTYPE html>
<html>
  <head>
    <title>GridLayer Test</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.1/dist/leaflet.css" />
    <style>
      body {
      padding: 0;
      margin: 0;
      }
      html, body, #map {
      height: 100%;
      width: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map"></div>

    <script src="https://unpkg.com/leaflet@1.0.1/dist/leaflet.js"></script>

    <script>
      var map = new L.Map('map', {  center: [33.916013, -118.245849], zoom: 16});

      var tiles = new L.GridLayer();
      tiles.createTile = function(coords) {
      var tile = L.DomUtil.create('canvas', 'leaflet-tile');
      var ctx = tile.getContext('2d');
      var size = this.getTileSize()
      tile.width = size.x
      tile.height = size.y

      // calculate projection coordinates of top left tile pixel
      var nwPoint = coords.scaleBy(size)

      // calculate geographic coordinates of top left tile pixel
      var nw = map.unproject(nwPoint, coords.z)
      ctx.strokeStyle = 'red';
      ctx.strokeText('(' + coords.z + ',' + coords.x + ',' + coords.y + ")", 10, 10);
      ctx.strokeText('lat: ' + nw.lat + ', lon: ' + nw.lng, 5, 20);
      ctx.beginPath();
      ctx.moveTo(0, 0);
      ctx.lineTo(size.x-1, 0);
      ctx.lineTo(size.x-1, size.y-1);
      ctx.lineTo(0, size.y-1);
      ctx.closePath();
      ctx.stroke();
      return tile;
      }
L.tileLayer('https://api.mapbox.com/styles/v1/mapbox/streets-v10/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoibGluY29tYXRpYyIsImEiOiJiUnpRRXZZIn0.GjtogvDfIEi
7odtxGA9_MQ',
      {
      tileSize: 256,
      maxZoom: 25
      }).addTo(map)
      tiles.addTo(map)
    </script>
  </body>
  </html>

```

**Comment by ChrisLoer** [comment]
https://github.com/mapbox/mapbox-gl-native/pull/12520 should ameliorate this problem by avoiding edge for labels with `symbol-placement: line`. Point labels can still have the problem, although if necessary using the `symbol-avoid-edges` style property can help.

**Comment by lincomatic** [comment]
The problem I was having was with point labels. symbol-avoid-edges reduced, but didn't solve the problem.

**Comment by ChrisLoer** [comment]
@lincomatic That's good to know -- could you show a screenshot (and the matching style) showing a tile boundary issue for a point label using `symbol-avoid-edges`?

For context: #12520 has merged to gl-native `master` but I don't believe it's live yet for our raster tile API (cc @jjanczyszyn). Also, the current server-side raster tile code is significantly different from what it was when you originally filed this issue in 2017. So there's a lot of room for confusion here! Nonetheless, I don't have an immediate explanation for why `symbol-avoid-edges` "reduced, but didn't solve the problem".

**Comment by lincomatic** [comment]
@ChrisLoer, I am pretty sure the above example had symbol-avoid-edges enabled.

**Comment by ChrisLoer** [comment]
I'm confused -- the example you posted looked like it was getting tiles from `https://api.mapbox.com/styles/v1/mapbox/streets-v10/tiles/256/{z}/{x}/{y}`, which doesn't use `symbol-avoid-edges`.

**Comment by lincomatic** [comment]
Oops, sorry! I had done the same test with my own map, and I forgot that when I posted this example, I used your api server to prove that it wasn't just some error on my part that was causing it. Unfortunately, my server crashed subsequently, and I lost all of my data. I will try to reproduce it again if I can find the time to rebuild the map... need start over from scratch.
