### ISSUE TITLE
Enumerate all MGLPointFeature of AnnotationViews by loading the Style Layer

### ISSUE THREAD

**Issue by rmnblm** [mapbox/mapbox-gl-native#8589]
**Platform:** iOS 10.3
**Mapbox SDK version:** 3.5.0

### Steps to trigger behavior

 1. Add an MGLPointFeature with Attributes `[ "nodeID": 1 ]` with `mapView.addAnnotation(pointFeature)`, this will add a custom MGLAnnotationView to the map
 2. Load special layer `mapView.style?.layer(withIdentifier: "com.mapbox.annotations.points")`
 3. Retrieve all Features in this layer (only one) and try to access `attribute(forKey: "nodeID")`

### Expected behavior

It returns the value `1`.

### Actual behavior

It returns `nil`. The whole `attributes` property is nil.

**Comment by rmnblm** [comment]
@boundsj Is this the same situation as mentioned from you in this comment? https://github.com/mapbox/mapbox-gl-native/issues/7949#issuecomment-278832601
But then I'm asking myself why I can query the attributes property in other style layers? 🤔

**Comment by dgccom** [comment]
You just can get attributes property when you set it.  You can not get the attributes property when you initialize with a style file or a geojson file and so on

**Comment by boundsj** [comment]
Probably @rmnblm. How exactly are you doing Step 3 (Retrieve all Features in this layer (only one))? And, I'm not sure what you mean by "I can query the attributes property in other style layers"
