### ISSUE TITLE
libmapbox-gl.so is not copied to android directory

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#859]
For some reason running `make clean && make -j8 android` results in `android/java/MapboxGLAndroidSDK/src/main/jniLibs/armeabi-v7a/libmapbox-gl.so` not being copied by the strip command in `mpbgl-android.gyp`.

If then run `make -j8 android` a second  time the file is copied correctly.

I am not sure what is going on as verbose `make` reveals that a `mkdir -p` command is generated by gyp that should make the directory. Also there is no error message produced by this command to indicate why it fails.

This is the command gyp generates:
`LD_LIBRARY_PATH=/home/leith/mb/mbgl-android/build/android-arm-v7/Release/lib.host:/home/leith/mb/mbgl-android/build/android-arm-v7/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../../android; mkdir -p /home/leith/mb/mbgl-android/android/java/MapboxGLAndroidSDK/src/main/jniLibs/armeabi-v7a; "/home/leith/mb/mbgl-android/mason_packages/.android-platform/arm-v7-9//bin/arm-linux-androideabi-strip" "/home/leith/mb/mbgl-android/build/android-arm-v7/Release/lib.target/libmapbox-gl.so" -o "/home/leith/mb/mbgl-android/android/java/MapboxGLAndroidSDK/src/main/jniLibs/armeabi-v7a/libmapbox-gl.so"`

/cc @kkaefer

**Comment by ljbade** [comment]
@bleege It just occurred to me that your `gradle` script might be somehow deleting the folder?

**Comment by ljbade** [comment]
@bleege just tested and it does seem to be `gradle` deleting the file.

**Comment by bleege** [comment]
Interesting.  What's the gradle command that's nuking it?  I'm running `./deploy.sh` which calls

```sh
../gradlew -b build.gradle clean assembleRelease uploadArchives
```
and afterwards all the architectures in jniLibs have their .so files

* arm64-v8a
* armeabi	
* armeabi-v7a
* mips
* mips64
* x86

**Comment by ljbade** [comment]
@bleege the command from the `make` file does it, however even a rebuild in Android Studio does it too.

**Comment by bleege** [comment]
Resolved in https://github.com/mapbox/mapbox-gl-native/issues/826#issuecomment-73998692 with @ljbade.
