### ISSUE TITLE
Add method to set user tracking mode as well as pitch, heading, and zoom in a single animation

### ISSUE THREAD

**Issue by n8chur** [mapbox/mapbox-gl-native#8609]
There is currently no way to set the user tracking mode to follow while also adjusting the pitch, heading, and zoom level using an animation. There is also no way to use a custom media timing function for the user tracking mode change animation.

I've tried setting the pitch, heading, and zoom to the user's location first, and then on completion setting the tracking mode to follow, but there is a noticeable jump as it starts following (especially if the user's location has changed significantly during the animation).

It would be nice to have a method to set the tracking mode with pitch, heading, and zoom level. Something like:
```
- (void)setUserTrackingMode:(MGLUserTrackingMode)mode pitch:(CGFloat)pitch heading:(CLLocationDirection)heading zoomLevel:(double)zoomLevel duration:(NSTimeInterval)duration animationTimingFunction:(nullable CAMediaTimingFunction *)function completion:(nullable void (^)(void))completion;
```

Another alternative could be to have a type of camera that always follows the user's location and where `centerCoordinate` is not settable.

**Comment by 1ec5** [comment]
As of #7856, programmatic camera changes no longer boot the user out of user tracking mode, but you’re right that there’s still a jarring transition whether you set the user tracking mode first or move the camera into place first. We’re hoping to improve transitions around user tracking mode in general by implementing concurrent animations (#3625). At this point, #8176 looks like the most likely path forward.
