### ISSUE TITLE
can not load wmts url

### ISSUE THREAD

**Issue by yangzhedeID** [mapbox/mapbox-gl-native#8612]
**Platform:Android**
**Mapbox SDK version:5.0.1**

### Steps to trigger behavior

 1.create Tile Json,like
`{
    "bounds": [
        113.989774,
        33.001323,
        114.009764,
        33.018672
    ],
    "center": [
        113.999769,
        33.0099975,
        0
    ],
    "created": 1486276187357,
    "description": "",
    "filesize": 357091,
    "format": "pbf",
    "id": "freewu.ciysacyq9000d2qo36w6gjdw7-9ep07",
    "mapbox_logo": true,
    "maxzoom": 20,
    "minzoom": 0,
    "modified": 1486276187007,
    "name": "hhxy",
    "private": false,
    "scheme": "tms",
    "tilejson": "2.1.0",
    "tiles": [
        "http://192.168.4.240/geoserver/gwc/service/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&LAYER=hhxymap_ditu&STYLE=&TILEMATRIX=EPSG:900913:{z}&TILEMATRIXSET=EPSG:900913&FORMAT=application/x-protobuf;type=mapbox-vector&TILECOL={x}&TILEROW={y}"
    ],
    "version": "1.1.0",
    "webpage": "https://a.tiles.mapbox.com/v4/freewu.ciysacyq9000d2qo36w6gjdw7-9ep07/page.html?access_token=pk.eyJ1IjoiZnJlZXd1IiwiYSI6ImNpdTR0cndlNDAwMWYyenM0emNlY2wzdXIifQ.b6ES6ewS-L7PXgrX4HoWUA"
}`

2.use mapbox-gl-js to load
3.use mapbox-gl-native to load

### Expected behavior

All platforms can be displayed

### Actual behavior

1.mapbox-gl-js can load
2.mapbox-gl-native can not load

log:
`Failed to load tile 15/26760/13197=>15 for source outdoor: HTTP status code 400`

**Comment by jfirebaugh** [comment]
Is there a publicly-accessible WMTS endpoint that I can use to reproduce this issue?
