### ISSUE TITLE
Display custom annotation for user location

### ISSUE THREAD

**Issue by superandrew** [mapbox/mapbox-gl-native#8620]
**Platform:**
iOs
**Mapbox SDK version:**
3.5.0

### Steps to trigger behavior

 1. Implement func mapView(_ mapView: MGLMapView, viewFor annotation: MGLAnnotation) -> MGLAnnotationView? 

### Expected behavior
I am expecting to see it called even when there are no other annotations than the user location
 in any case, receiving an annotation that *is* userLocation, so that I can provide a custom annotationview

### Actual behavior
The method gets called only with locations with the MGLPoint annotations that I append to the map.
As an example, if I have one pin on the map, the method gets fired once alone.

In general I probably didn't understand how to customize the user location AnnotationView, but from some research in s.o. and google this seems to be the proper way to do it. I noticed that in Android there is a very handy example in the documentation, that seems to be missing in iOs.

https://www.mapbox.com/android-sdk/examples/user-location/

Thanks!

**Comment by friedbunny** [comment]
`-mapView:viewForAnnotation:` is the correct place to set a custom user location annotation. [Here’s an in-progress example](https://github.com/mapbox/ios-sdk-examples/pull/50/files#diff-6774912319cb92bb7f8570144ca8002d) of a basic implementation.

If you’re not seeing `MGLUserLocation` in `-mapView:viewForAnnotation:`, make sure that `MGLMapView.showsUserLocation` is enabled.

**Comment by superandrew** [comment]
I must be doing something really wrong because I can see the blue slow flashing dot, so showsUserLocation is enabled.

Double checking now. Any other property that might influence this behavior?

3 apr 2017, 23:26 +0200, Jason Wray <notifications@github.com>, ha scritto:

**Comment by swasta** [comment]
Platform:
iOS
Mapbox SDK version:
3.5.2

I've been seeing the same behavior as @superandrew did. `-mapView:viewForAnnotation:` would get called only for custom MGLPoint annotations that I appended to the map. Then I turned off "Shows user location" for the mapView in Storyboard and added this

```swift
extension ViewController: MGLMapViewDelegate {
    func mapViewDidFinishLoadingMap(_ mapView: MGLMapView) {
        mapView.showsUserLocation = true
    }
```

Now it works as expected.

**Comment by ojseven** [comment]
I am seeing the same behavior that @superandrew is having and after updating to exactly as @swasta has stated I am still having the issue. I never see the user annotation come through.

**Comment by friedbunny** [comment]
It’s unnecessary to wait until `-[MGLMapViewDelegate mapViewDidFinishLoadingMap:]` — just be sure to set `MGLMapView.delegate` _before_ setting `MGLMapView.showsUserLocation` (or another property that implicitly enables it), otherwise `-[MGLMapViewDelegate mapView:viewForAnnotation:]` won’t be called as the user location annotation is initializing.

[Here is an example of how to implement a custom user location annotation.](https://www.mapbox.com/ios-sdk/examples/user-location-annotation/)

**Comment by Alqueraf** [comment]
I had the same issue and found a simple workaround.
For future reference, if you are setting the showUserLocation via code, make sure it is turned off in the storyboard; no need to implement mapViewDidFinishLoadingMap.

**Comment by philfi** [comment]
Encountering this issue on iOS. I have tried setting `showsUserLocation` after setting the `MGLMapView.delegate` as well as the suggestion from @swasta to no avail. The only real distinction I'm seeing between my code and the example code is that in my code, the delegate is a `UIView`, not `UIViewController`. Could this be the underlying issue?
