### ISSUE TITLE
Layer Property "lineOpacity" not worked

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#8628]
**Platform:** Android
**Mapbox SDK version:** 5.0.1

### Steps to trigger behavior
```
        LineLayer lineLayer = new LineLayer(LAYER_NAME_TIME_CIRCLE, SOURCE_NAME_TIME_CIRCLE);
        lineLayer.setProperties(
                PropertyFactory.lineColor(0x33000000), //color with alpha not worked
                PropertyFactory.lineOpacity(0.54f) //Opacity not worked
        );
```

**Comment by jfirebaugh** [comment]
Can you please elaborate on what you mean by "not worked"? What did you expect, and what happened instead? It would help if you provide a complete, self-contained example.

**Comment by klblk** [comment]
sorry, bug in my code
