### ISSUE TITLE
macos sdk fails to load library

### ISSUE THREAD

**Issue by AustinoBombino** [mapbox/mapbox-gl-native#8632]
**Platform: macosx**
**Mapbox SDK version: macos-v0.4.0**

### Steps to trigger behavior

 1. Follow installation steps
 2. Drop framework in embedded binaries
 3. Project builds successfully

### Expected behavior
Successful loading of resulting program
### Actual behavior
Program fails to load with: 
"The bundle couldn’t be loaded because it is damaged or missing necessary resources.."
or 
"Library not loaded: @rpath/Mapbox.framework/Versions/A/Mapbox"

**Comment by AustinoBombino** [comment]
not sure if relevant but my project involves three targets:
an app target which contains an xpc target which contains a .fxplug target.

after building, the .app contents include the mapbox.framework which only contains mapbox.exec, resources, and versions.

should there be more members to the resulting mapbox.framework?

**Comment by 1ec5** [comment]
What does your application target’s Runpath Search Paths (`LD_RUNPATH_SEARCH_PATHS`) build setting look like? Does this issue reproduce in [v0.3.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/macos-v0.3.1)?

Note that we’ve discovered that the framework contains duplicate copies of all the files where there should only be symlinks into Versions/A/: #8636. It’s unclear to me whether the issues you’re seeing will be resolved along with #8636.

**Comment by AustinoBombino** [comment]
Nailed it.
The .app and .pluginkit runpaths were set correctly, but the .fxplug was missing a runpath.
I set it to @loader_path/../Frameworks and everything's golden.

Not sure if the duplicate files issue will cause problems with my build down the line but this seems to have fixed my current issue.

Thanks for the paddle, I was up a creek.

**Comment by 1ec5** [comment]
Awesome, glad to hear it!

**Comment by AustinoBombino** [comment]
In case anyone has a similar issue at any point:
I did a clean and build and the problem came back.
I had to manually copy the mapbox.framework from the .app package into my .fxplug target package.

Not sure if i'm just missing a setting somewhere or if thats a necessary step when you have a target that doesn't allow embedded binaries.

**Comment by 1ec5** [comment]
> a target that doesn't allow embedded binaries

Xcode’s project editor only shows an Embedded Binaries section for application targets, but the Embedded Binaries section is just a fancy UI for a Copy Files build phase, which you can add to any target.

**Comment by AustinoBombino** [comment]
If it wasn't obvious, I'm an Xcode noob.
Thanks again
