### ISSUE TITLE
Documentation for abstract classes makes initialization unclear

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8635]
The documentation for abstract classes and their concrete subclasses make it very difficult for inexperienced developers to figure out how to initialize the concrete subclasses. We basically give the developer a bureaucratic runaround between the concrete and abstract class documentation.

For example, the documentation for [MGLVectorSource](https://www.mapbox.com/ios-sdk/api/3.5.0/Classes/MGLVectorSource.html) links to its superclass, MGLTileSource, and provides an example of using `-[MGLVectorSource initWithIdentifier:tileURLTemplates:options:]` in Swift. However, the link to MGLTileSource documentation is minimal, in a style that the developer is likely to miss (even after realm/jazzy#713), and the Swift example is of little use to Objective-C developers. Moreover, even if the developer follows the link to [MGLTileSource](https://www.mapbox.com/ios-sdk/api/3.5.0/Classes/MGLTileSource.html), that document says, “Do not create instances of this class directly … Instead, create instances of MGLRasterSource and MGLVectorSource.” An inexperienced developer is likely to misinterpret this warning to mean that they shouldn’t use any of the MGLTileSource methods at all.

We should continue to document abstract initializers where they’re declared, to reduce duplication. However, we should make it crystal clear how to initialize each of the concrete subclasses. For example:

> To create an MGLVectorSource in Objective-C, use the `-[MGLTileSource initWithIdentifier:tileURLTemplates:options:]` method on a newly-allocated MGLVectorSource object. In Swift, use the `MGLVectorSource(identifier:tileURLTemplates:options:)` initializer, seen in the example below.

jazzy will automatically link the reference to `-[MGLTileSource initWithIdentifier:tileURLTemplates:options:]`, whereas it’ll leave the Swift syntax unlinked. I think this is OK.

/cc @jfirebaugh @jmkiley @friedbunny

**Comment by jmkiley** [comment]
I agree that we should make it more prescriptive. If we start with what to do (as opposed to what not to do), it may be more clear and concise. For example:

> Create instances of `MGLRasterStyleLayer` and the concrete subclasses of `MGLVectorStyleLayer` in order to use `MGLForegroundStyleLayer`'s methods.

We would need to make sure users are directed to subclasses of relevant sources/layers from the beginning.

**Comment by 1ec5** [comment]
It’s worth noting that @jfirebaugh has moved most of the abstract classes’ initializers to their concrete subclasses in #8626.

**Comment by 1ec5** [comment]
What are the next steps following #8626? Do we still need to make this change for iOS SDK v3.6.0?

**Comment by jmkiley** [comment]
We should still make the documentation for these classes emphasize what to do (or how to use the properties from that class https://github.com/mapbox/mapbox-gl-native/issues/8635#issuecomment-294557402), rather than what not to do. I can do that today.

**Comment by jmkiley** [comment]
Addressed in #9095
