### ISSUE TITLE
Per-feature minZoom and maxZoom?

### ISSUE THREAD

**Issue by always-beta** [mapbox/mapbox-gl-native#8638]
Is it possible that define minZoom and maxZoom for each MGLPointFeature instance when adding multiple MGLPointFeature instances as a source? I found that I can set min/max zoom for the layer I used to render this source, but failed to find a way to set per-feature.

What I try to do is, I have lots of pois (5k ~ 10k) to display at runtime, and each of them has its own min/max zoom set to control which zoom level to begin/end render. 

With _iOS Mapkit_, I used to use annotation views to add and remove on every region did changed delegate callback. But now since I'm using vector tiles, I think annotation views might not be the best way to display this number of pois.

The workaround I can think of is, split those poi into different sources per zoom level, and define multiple layers respectively. E.g: collect all pois need to display at zoom 10, add them as a source of source-10, add a layer for source-10 and set min/max as 10 for the layer, repeat the same process for zoom 11, 12... 
But that way it would generate lots of duplicated data and layers.
So I'm wondering if there's a way to define min/max zoom for the data in order to cut off useless data before it reaches to rendering pipeline?

**Comment by jfirebaugh** [comment]
Another workaround would be to use a data-driven property function for the opacity property on the POIs, so that they are fully transparent outside the zoom range associated with each feature.

We're tracking a true data-driven min/maxzoom, or equivalent feature, in https://github.com/mapbox/mapbox-gl-js/issues/4288.

**Comment by stonetip** [comment]
I'm doing this for a single test point, but would appreciate any example for using a data-driven property for transparency so I can just create a single layer for all the points:

`I have a point dataset that is intended only as labels. Each label has a pre-calculated minZoom attribute to one decimal place, e.g. 6.1. While there are labels that share the same value, they vary considerably. I've figured out how to programmatically add a single label. It's workable, I suppose, to add a layer for each label. But performance may suffer. Is there a way, either via Mapbox Studio or programmatically (for the iOS SDK) to set the camera stops individually for each label but keep them within a single layer?

func mapView(_ mapView: MGLMapView, didFinishLoading style: MGLStyle)
{
    // Try adding point with label
    let coordinates: CLLocationCoordinate2D = CLLocationCoordinate2D(latitude: 49, longitude: -114)

    let testPt = MGLPointFeature()
    testPt.coordinate = coordinates
    testPt.title = "Testing label"
    testPt.attributes = ["title": testPt.title as Any]

    let src = MGLShapeSource(identifier: "testPtID", features: [testPt], options: nil)

    mapView.style?.addSource(src)

    let symbols = MGLSymbolStyleLayer(identifier: "testPtSym", source: src)

    let color = UIColor(red: 0.08, green: 0.75, blue: 0.96, alpha: 1.0)

    symbols.textColor = MGLStyleValue(rawValue: color)
    symbols.text = MGLStyleValue(rawValue: "{title}")
    symbols.textFontSize = MGLStyleValue(rawValue: 24)
    symbols.textOpacity = MGLStyleValue(interpolationMode: .exponential,
                                        cameraStops: [
                                            6: MGLStyleValue(rawValue: 0),
                                            6.1: MGLStyleValue(rawValue: 1)
        ], options: nil
    )

    mapView.style?.addLayer(symbols)
}`
