### ISSUE TITLE
FollowWithCourse missing in Android

### ISSUE THREAD

**Issue by krsticdragan** [mapbox/mapbox-gl-native#8642]
Hi there, 

In iOS there are functions that automatically switch a location icon and setup a follow with course mode? I couldnt find one in iOS, there are only MyLocationTracking.Tracking_FOLLOW .getTrackingSettings().setMyLocationTrackingMode(MyLocationTracking.TRACKING_FOLLOW) that are following and are not setting the padding or new icon. 

Is there any method like FollowWithCourse in android, that will automatically add padding and switch a user icon? 

Platform: Android
Mapbox SDK version: 5.0.1
![icon_ios](https://cloud.githubusercontent.com/assets/20177491/24699550/9ed2029a-19f4-11e7-8243-3aaa853a16fd.png)

**Comment by tobrun** [comment]
@krsticdragan on Android we expose the TrackingSettings class for managing the tracking modes and we expose MyLocationViewSettings to allow setting padding and changing the appearance of MyLocationView. Feel free to ask any follow up questions but closing this as answered.

**Comment by krsticdragan** [comment]
Hi there, yes, Im fammiliar with MyLocationViewSettings and TrackingSettings, just is there a possibility that there are a settings that change location icon like in FollowWithCourse mode in android?

**Comment by tobrun** [comment]
Not atm, though we are thinking about creating a facility navigation plugin that does such a thing.

**Comment by tobrun** [comment]
Not atm, though we are thinking about creating a facility navigation plugin that does such a thing.

**Comment by krsticdragan** [comment]
Ok, thank you very much for the info.
