### ISSUE TITLE
How to get the updating location on the bottom of the mapview when I'm navigating?

### ISSUE THREAD

**Issue by seeingann** [mapbox/mapbox-gl-native#8643]
Platform:iOS
Mapbox SDK version:3.5.0

Hi, there. I'm now using the Mpabox SDK, I have a problem to solve.When I'm navigating, i want to show the updating location on the bottom of the mapview, i use the method but it useless. eg:

  [self.mapView setCenterCoordinate:CLLocationCoordinate2DMake(naviInfo.carCoordinate.latitude, naviInfo.carCoordinate.longitude) zoomLevel:15 direction:naviInfo.carDirection animated:YES];

Thanks a lot.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by seeingann** [comment]
Thanks for answering, I'll try with your advice.
