### ISSUE TITLE
Move *FileSource + OfflineDatabase away from mbgl-core

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#8649]
We're currently building these as part of the `mbgl-core` target. However, that target also gets linked into the node bindings, which don't use or expose it. Instead, like the loop libraries, we should build it as a separate target and only link it into the targets that actually use it.

While we haven't had any reports, I'm concerned that we're statically linking libsqlite3 into the node bindings, which could cause issues when using `node-sqlite3` in the same process. Looking at the `nm` output, I'm not actually seeing any SQLite-related symbols in that binary, but it just seems like a better architecture.

**Comment by jfirebaugh** [comment]
Done in #10060.
