### ISSUE TITLE
Respect 'base' in composite functions

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-native#8654]
In GL JS, we use the `base` property to interpolate the zoom component of composite functions of all types (not just for `type: exponential`).  [Ref](https://github.com/mapbox/mapbox-gl-js/blob/a73a85b06b21b23814d30ca434b94040e9f26bb8/src/style-spec/function/index.js#L124)

Here, it looks like we [always assume a base of `1.0f`](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/style/function/composite_function.hpp#L109)

For consistency with GL JS, we should include a `base` property on each `Composite*Stops<T>` type--or maybe as a member of the function itself? I'm not sure--and use when we compute the interpolation factor.

**Comment by jfirebaugh** [comment]
I think there's an underlying design flaw with the current specification of composite functions at play here. You should be able to separately specify the types of the camera and source portions of composite functions -- and if both types are exponential, provide separate bases for each.

**Comment by anandthakker** [comment]
Agreed @jfirebaugh - though I think we should keep this issue open to track the short/medium-term  problem, since fixing the spec may take longer.

**Comment by jfirebaugh** [comment]
In https://github.com/mapbox/mapbox-gl-js/pull/4934 we switched gl-js to match native's linear interpolation for the zoom component. We'll defer to [expressions](https://github.com/mapbox/mapbox-gl-js/pull/4777) to provide sophisticated independent control over this.
