### ISSUE TITLE
Rendering artifacts with PowerVR SGX544 GPUs

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#8658]
**Platform:** Android 4.2 (reproduced only Alcatel one touch 6040x - MediaTek MT6589T, PowerVR SGX544)
**Mapbox SDK version:** 5.0.0-beta.3 - 5.0.2 (not reproduce on 5.0.0-beta.2)

### Steps to trigger behavior
Mapbox demo app -> Styles -> Mapbox Studio style (100% reproduced on this screen)

### Actual behavior
It's better to see:
![photo_2017-04](https://cloud.githubusercontent.com/assets/6357562/24736708/e0dd5dfa-1ab3-11e7-8f4a-f6f00c7f2f23.jpg)
![photo_2017-04-06_10-16-41](https://cloud.githubusercontent.com/assets/6357562/24736710/e73876d0-1ab3-11e7-9101-6f0f43d9b423.jpg)

In my app: 
![photo_2017-04-06_10-14-55](https://cloud.githubusercontent.com/assets/6357562/24736739/0a75e286-1ab4-11e7-852a-6388e8dfa52d.jpg)

device info: 
![photo_2017-04-06_10-14-30](https://cloud.githubusercontent.com/assets/6357562/24736746/1b6f52b6-1ab4-11e7-9972-935822435773.jpg)

**Comment by friedbunny** [comment]
I have to say, that is a magnificent rendering error. 👌

**Comment by jfirebaugh** [comment]
Retitled based on the commonality with #9306.

**Comment by jfirebaugh** [comment]
Pretty sure this is a driver / hardware bug relating to using a single VAO with distinct programs (which do use the same attribute layout).

Things I tried:

“fill-antialias”: false -- less artifacts, but still present
reversing layer order -- artifacts
removing either layer -- no artifacts
making second layer non-pattern -- no artifacts
making first layer pattern -- no artifacts
making layers non-ref’d -- no artifacts
disable VAOs -- no artifacts
force rebind attributes -- artifacts
force rebind element buffer --artifacts
force rebind attribute buffer -- artifacts
force rebind everything -- artifacts
recreate VAO every time -- no artifacts
separate VAO for each Program -- no artifacts

**Comment by jfirebaugh** [comment]
For posterity, the style I used for testing:

<details>
```
{
  "version": 8,
  "center": [-0.1076028852098716, 51.48775780296032],
  "zoom": 13.370586425682019,
  "sources": {
    "streets": {
      "url": "mapbox://mapbox.mapbox-streets-v7",
      "type": "vector"
    }
  },
  "sprite": "mapbox://sprites/mapbox/streets-v9",
  "layers": [
    {
      "id": "background",
      "type": "background",
      "paint": {
        "background-color": "black"
      }
    },
    {
      "id": "polygon-fill",
      "type": "fill",
      "source": "streets",
      "source-layer": "road",
      "filter": [
        "all",
        [
          "==",
          "$type",
          "Polygon"
        ],
        [
          "in",
          "class",
          "path",
          "pedestrian"
        ],
        [
          "==",
          "structure",
          "none"
        ]
      ],
      "paint": {
        "fill-color": "green",
        "fill-antialias": false
      }
    },
    {
      "id": "polygon-fill-pattern",
      "type": "fill",
      "source": "streets",
      "source-layer": "road",
      "filter": [
        "all",
        [
          "==",
          "$type",
          "Polygon"
        ],
        [
          "in",
          "class",
          "path",
          "pedestrian"
        ],
        [
          "==",
          "structure",
          "none"
        ]
      ],
      "paint": {
        "fill-pattern": "pedestrian-polygon",
        "fill-antialias": false
      }
    }
  ]
}
```
</details>
