### ISSUE TITLE
No resource identifier found for attribute

### ISSUE THREAD

**Issue by neonwarge04** [mapbox/mapbox-gl-native#8659]
Platform: Android
Mapbox SDK version: 5.0.2

Steps to trigger behavior
 1. Build with v5.0.2

Expected behavior
 1. Should build and run just fine

Actual behavior
 1. Throws an error indicating:
```
Error:(10) No resource identifier found for attribute 'style_url' in package (...)
Error:(10) No resource identifier found for attribute 'attribution_enabled' in package (...)
Error:(10) No resource identifier found for attribute 'attribution_gravity' in package (...)
Error:(10) No resource identifier found for attribute 'logo_gravity' in package (...)
Error:(10) No resource identifier found for attribute 'logo_enabled' in package (...)
Error:(14, 24) No resource found that matches the given name (at 'style_url' with value (...)
```

**Comment by neonwarge04** [comment]
Hi guys, please help, what did you changed? It can't seem to find the following:
```
app:mapbox_attributionEnabled="true"
        app:mapbox_attributionGravity="bottom|right"
        app:mapbox_logoGravity="bottom|left"
        app:mapbox_logoEnabled="true"/
```

Where are the documentation for MapView custom attributes? Please provide link

**Comment by tobrun** [comment]
Thank you for reaching out, this is documented [here](https://github.com/mapbox/mapbox-gl-native/wiki/Android-4.x-to-5.0-update#mapbox-attribution-name-changes). We will be adding more documentation on attributes to our website shortly. Apologies for the inconvenience.
