### ISSUE TITLE
Multiple maps not rendering

### ISSUE THREAD

**Issue by akbsteam** [mapbox/mapbox-gl-native#866]
Using the cocoapods installed version

I am instantiating 2 MGLMapView instances next to each other, the first doesn't render, the 2nd does.
Both show the mapbox logo and the (i)

**Comment by akbsteam** [comment]
Possibly; not seeing any errors in the logs, would there be?

**Comment by incanus** [comment]
Hmm, haven't ever tried two in the same app. Can you paste a simplified view controller code [gist](https://gist.github.com) and link here @akbsteam?

**Comment by akbsteam** [comment]
https://gist.github.com/akbsteam/2b43dcb95a31550c388b

**Comment by akbsteam** [comment]
Its just an NSObject, then I grab the 2 views and add them to my view

**Comment by incanus** [comment]
Hmm, the fact that you're using it in Swift @akbsteam makes me think you are on an older version? Are you building this yourself? I think the issue may be out of date.

**Comment by akbsteam** [comment]
I'm using the version on cocoapods; I can't get the mapbox-gl-native one to build

**Comment by incanus** [comment]
It shouldn't be on CocoaPods proper; it's a preview with the podspec just on GitHub for now. That's pretty old at this point, and right now we are only supporting building a static library, but stay tuned.

**Comment by incanus** [comment]
I'm going to close right now @akbsteam but once we have a Swift-compatible install again, let us know if you see this again.
