### ISSUE TITLE
Expose sourceLayerIdentifier on Layer

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8663]
A useful addition to our current Layer API is exposing `sourceLayerIdentfier`, while we use it internally we don't expose a getter for it. Such a getter can be useful to filter layers. For example take traffic, you want to add a traffic layer just above all other road layers. For this you would need to get all the style layers and filter out the ones with `sourceLayerIdentifier="road"`.

**Comment by tobrun** [comment]
Alternatively to exposing a getter we could also solve this use-case with a `getLayers(String sourceLayerIdentfier)` this might be a bit cleaner as we don't require the user to get all layers and do the filtering themselves. 

Thoughts @ivovandongen?

**Comment by ivovandongen** [comment]
@tobrun Let's start off with a getter and see if there are actual use cases for a filtered getter. If that's the case, I'd like to make it a little more extensible with a filter object that can have a number of properties to filter on (like the source name).

**Comment by tobrun** [comment]
Will work on adding the getter, :+1: on the filter idea.
