### ISSUE TITLE
Android version 5.0.2 attributes not getting suggested in XML

### ISSUE THREAD

**Issue by arbitur** [mapbox/mapbox-gl-native#8664]
**Platform: Android**
**Mapbox SDK version: 5.0.2**

I look in [Examples](https://www.mapbox.com/android-sdk/examples/) and you have changed the attributes from 4.x. You now use `mapbox_` prefix. But when I type `mapbox_` no suggestions related to MapView are shown, it makes it difficult to work with Mapbox.

**Comment by tobrun** [comment]
We started to require prefixing attributes as it a best practice for exposing library resources. How autpcompletion is implemented in AS is not in scope for this project. I consider the best practice more imprortant as the IDE integration as it resolves the issue of name conflicts. Thank you for the report but consider this non-actionable from our side. For a reference this is the [full list](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/res/values/attrs.xml) of attributes.

**Comment by arbitur** [comment]
I understand, thanks for the link to the attributes file. Would be nice if you could add them to the [Docs](https://www.mapbox.com/android-sdk/examples/)

**Comment by tobrun** [comment]
Great suggestion, will create a ticket in our documentation repository.
