### ISSUE TITLE
Allow setting of custom Location Engine

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#8668]
Currently, it doesn't appear to be a way to use a custom location engine rather then the Lost location provider. 

cc: @mapbox/android

**Comment by emerciercontexeo** [comment]
Is this issue mean that it will be possible to use MyLocationView without activate the LocationEngine ?

**Comment by zugaldia** [comment]
@emerciercontexeo It means that you can provide your own `LocationEngine` implementation, which can use another location provider, or do nothing at all, depending on your app needs.

You can see [two examples in this test app](https://github.com/mapbox/mapbox-java/tree/master/mapbox/app/src/main/java/com/mapbox/services/android/testapp/location). `GoogleLocationEngine.java` uses Google Play Services, while `MockLocationEngine.java` simply mocks locations and doesn't do any real location tracking.
