### ISSUE TITLE
Geo API Consistency

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#868]
Make Geo data API consistent with Mapbox Android SDK to make migration easier and consistent for end users.  See:

1. https://github.com/mapbox/mapbox-android-sdk/tree/mb-pages/MapboxAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry
1. https://github.com/mapbox/mapbox-android-sdk/tree/mb-pages/MapboxAndroidSDK/src/main/java/com/mapbox/mapboxsdk/api

**Comment by ljbade** [comment]
Adding note that https://github.com/mapbox/mapbox-gl-native/pull/853 also tidies up the C++ side to match too.

**Comment by bleege** [comment]
Good catch @ljbade.  I'll merge this in to Android GL now and when @incanus and @jfirebaugh finish their work on #853 we can re-glue the pieces together.
