### ISSUE TITLE
[android] Map not properly located

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#8693]
**Platform:** Android
**Mapbox SDK version:** `master` branch

### Steps to trigger behavior

 1. Open Test App
 2. Open `PolygonActivity` example

```
new CameraPosition.Builder()
        .target(new LatLng(45.520486, -122.673541))
        .zoom(12)
        .tilt(40)
        .build()
```

### Expected behavior
Map should be located in Portland.

![portland](https://cloud.githubusercontent.com/assets/1668582/24837916/071a9856-1d3f-11e7-9a8a-e14a4f329437.png)

### Actual behavior
Map is located in Russia.

![locationissue](https://cloud.githubusercontent.com/assets/1668582/24837921/1ee5003e-1d3f-11e7-9f9d-596dd11d9001.gif)

I did a fresh install of the repo to double check. I noticed that isn't happening in old branches. I reproduced it in a Nexus 5 and a Moto X (2nd gen) running Android 6.0 and 5.0 respectively.
The same thing happens in other activities: `BulkMarkerActivity`, `DynamicMarkerChangeActivity`, `PolylineActivity`.

**Comment by tobrun** [comment]
Git bisected it to 0314a46ee411b97810d49908ab110bbef049e7b7, going to debug.

cc @jfirebaugh

**Comment by tobrun** [comment]
I debugged it to `Tranform::easeTo` to the part of adding/applying padding. When commenting out [applying padding](https://github.com/mapbox/mapbox-gl-native/blob/0314a46ee411b97810d49908ab110bbef049e7b7/src/mbgl/map/transform.cpp#L149) as part of the transition, I'm seeing the correct result again. Not sure if this something that should be corrected in core code or the android binding.

**Comment by tobrun** [comment]
Looking into this more, making EdgeInsets also in the android binding code optional resolves the issue.

**Comment by jfirebaugh** [comment]
Good catch. I think this part of 0314a46ee411b97810d49908ab110bbef049e7b7 was misguided. The all-zeros instance of `EdgeInsets` is the natural default value, and using `optional` isn't necessary. Instead I should have replaced `operator bool()` with a named instance method like `isFlush()`. I opened a PR for that approach in #8716.

**Comment by tobrun** [comment]
Thank you for the :eyes: and patching this up!
