### ISSUE TITLE
Switch Mapbox logo to a universal PDF

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-gl-native#8703]
Currently the Mapbox logo is included as pngs at 1x, 2x, and 3x. Let's switch this to a vector PDF like our macOS implementation.

/cc @friedbunny

**Comment by 1ec5** [comment]
Per #5688, we might want to do the same for the other image assets, like the compass and the default pin.

**Comment by friedbunny** [comment]
Fixed by #9060, will be in v3.6.0-beta.1.
