### ISSUE TITLE
Can't seem to add Markers

### ISSUE THREAD

**Issue by neonwarge04** [mapbox/mapbox-gl-native#8704]
I am using this following code:

private void createMarker(final Recommendation recommendation)
    {
        if(!isVisible())
            return;

        mPinBitmapUtils.retrievePinBitmapAsync(getContext(), recommendation, new OnPinBitmapProcessed()
        {
            @Override
            public void onBitmapProcess(final Pin reco, PinType pinType, Map<String, String> directories)
            {
                if(!isVisible())
                    return;

                recommendation.setName(pinType.getName());

                new AsyncTask<String, Void, PinMarkerOptions>()
                {
                    @Override
                    protected PinMarkerOptions doInBackground(String... strings)
                    {
                        IconFactory iconFactory = IconFactory.getInstance(getContext());

                        Bitmap bitmap = Utils.getBitmapFromFile(getContext()
                                , new File(strings[0])
                                , (int) Utils.convertDpToPixel(48, getContext())
                                , (int) Utils.convertDpToPixel(48, getContext()));

                        Icon icon = iconFactory.fromBitmap(bitmap);

                        LatLng position = new LatLng();
                        position.setLatitude(recommendation.getLatitude());
                        position.setLongitude(recommendation.getLongitude());

                        PinMarkerOptions markerOption = new PinMarkerOptions();
                        markerOption.setPosition(position);
                        markerOption.setMetaData(recommendation.getJSON().toString());

                        if(icon != null)
                            markerOption.setIcon(icon);

                        return markerOption;
                    }

                    @Override
                    public void onPostExecute(PinMarkerOptions marker)
                    {
                       mMapboxMap.addMarker(marker);
                    }

                }.execute(directories.get(Constants.BLUE_PIN));
            }
        });
    }

When I checked the MapBox map instance, it does indeed increased in size but the pin I created is no where in sight.

I am still using 4.2.2 and in the process to migrating to 5.0.2 so I haven't check it on the latest version entirely.

Anything so basic I missed out on?

**Comment by neonwarge04** [comment]
Alright, it seems if I delete a bunch of Markers, and I re-add them back again, this happens. MapBox map sizes increases and but no markers were shown.

**Comment by neonwarge04** [comment]
Can someone please help? It doesn't seem to work, I cannot add Markers unless I restarted the whole map. Anyway I can get around this? Markers are not showing when I remove them (due to filtering) and add them (when they go unfiltered).

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by neonwarge04** [comment]
This is not a "how question". I am saying addMarker doesn't show the marker I added. It appears you didn't read my concern.
