### ISSUE TITLE
[support, ios] What's the preferred way to detect signle tap on MGLMapView?

### ISSUE THREAD

**Issue by eimantas** [mapbox/mapbox-gl-native#8706]
What is the preferred way to intercept a single tap on `MGLMapView`? I found Issue #1113, however I am not sure how the story ended there and what approach should I use (subclass MGLMapView, attach my own gesture recognizer or do method swizzling for touch event methods).

**Comment by friedbunny** [comment]
Adding your own gesture recognizer(s) and then iterating through `MGLMapView.gestureRecognizers` to handle conflicts is the general technique we’ve recommended. For a code snippet and a little bit more documentation, see the overview of [`MGLMapView`](https://www.mapbox.com/ios-sdk/api/3.5.2/Classes/MGLMapView.html).

[This page](https://www.mapbox.com/ios-sdk/api/3.5.2/gesture-recognizers.html) also outlines the default gestures.
