### ISSUE TITLE
Android: Build a real unit test application

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#8714]
We're currently [faking our way](https://github.com/mapbox/mapbox-gl-native/blob/1d33bf774f7d0248a72529840e155c4716a99851/platform/android/src/test/main.jni.cpp#L45-L76) to an Android application. Instead, we should build a real application that *only* contains `mbgl-test.so` (which includes `mbgl-android`, which includes `mbgl-core`, and starts up as a real application with the usual application launch mechanism.

Reasons for this are:

- Integration into Android Studio
- Run Google Unit Tests on Firebase
- Test JNI wrappers outside of the context of a regular Map workflow
- We need a `Context` handle for testing https://github.com/mapbox/mapbox-gl-native/pull/8712

/cc @mapbox/android

**Comment by tobrun** [comment]
Not linking https://github.com/fsbarata/ndktest-plugin as the solution, but there are some interesting parts in there that we could reuse.

**Comment by kkaefer** [comment]
Moving in https://github.com/mapbox/mapbox-gl-native/pull/13617
