### ISSUE TITLE
Split Andriod user-data script into a separate file

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapbox-gl-native#872]
Let's split the [user-data script](https://github.com/mapbox/mapbox-gl-native/blob/df57d6ee8b8eb04499385fa42466a8d165a9d829/android/scripts/run-build.sh#L16-L47
) that's used for Android builds out into a separate file so it's easier to maintain in the long run.

/cc @bleege  @ljbade

**Comment by ljbade** [comment]
Been working on this but having issues with bash.

**Comment by willwhite** [comment]
@ljbade can you recap the specifics of the issue you're running into?

**Comment by ljbade** [comment]
@willwhite I tried to use the `cat` command to pipe the user script into the variable `user_data` with the exact same text I had previously harded coded in the variable.

The script gets run but it fails on the last two `aws` and `shutdown` commands saying it can't find the commands, indicating something wrong with the `PATH`. However until the last two lines the script runs with no errors.

I have not yet tried with what @bsudekum had done in other similar script where he calls a script that just `echo`s the text and pipes that into a variable. However I can't see why the simpler `cat` approach does not work.

You can see my attempt in https://github.com/mapbox/mapbox-gl-native/pull/873/files

The annoying thing is this bug prevents the instances from self terminating and they are left running so I have to remember to go back and terminate them.

I may end up just switching to https://github.com/mapbox/cfn-ci

**Comment by jfirebaugh** [comment]
Obsoleted by subsequent changes.
