### ISSUE TITLE
Support interpolate-{hcl,lab} expression operators

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#8720]
Port https://github.com/mapbox/mapbox-gl-js/pull/7123 to mapbox-gl-native.

This issue replaces #6442. See that PR for some code that may be useful.

**Comment by 1ec5** [comment]
The platform-specific parts of this feature are tracked in #6724 for Android and #6721 for iOS and macOS.

**Comment by 1ec5** [comment]
#6721 was closed out in favor of this issue. There are some notes in #6721 regarding how the proposed expression operator would be exposed in NSExpression.
