### ISSUE TITLE
[Mason] Failed to download

### ISSUE THREAD

**Issue by qwe3243002** [mapbox/mapbox-gl-native#8721]
**Platform:** macOS 10.12.3
**Mapbox SDK version:** in master branch and latest

hello，in two weeks ago ，The command `make android` is ok，but when i pulled the latest code yesterday ，something is bad。
![image](https://cloud.githubusercontent.com/assets/3120265/24943013/0bd8e9c0-1f87-11e7-9eba-6de1da9d9476.png)
I don't know how to do !!!!

**Comment by friedbunny** [comment]
This appears to be an issue with your internet connection — [that link](https://mason-binaries.s3.amazonaws.com/headers/boost/1.62.0.tar.gz) exists, is reachable, and the file is not corrupt.
