### ISSUE TITLE
Network usage for an Offline Download is spiky instead of being smooth

### ISSUE THREAD

**Issue by altafrm3d** [mapbox/mapbox-gl-native#8724]
For offline tiles downloading, in android network monitor the network usage shows up as spiky instead of being smooth, my style json is pretty straight forward and is given below

`{
  "version": 8,
  "name": "Raster Tiles",
  "sources": {
    "osm": {
      "type": "raster",
      "scheme": "xyz",
      "tiles": [
        "http://a.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png",
        "http://b.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png",
        "http://c.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png",
        "http://d.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png"
      ],
      "tileSize": 256
    }
  },
  "layers": [
    {
      "id": "osm_layer",
      "type": "raster",
      "source": "osm",
      "paint": {
        "raster-fade-duration": 100
      }
    }
  ]
}`

I have tried other tile sources as well, 
could you please either explain this erratic network usage or look into it? thanks.

**Platform:** Android 
**Mapbox SDK version:** release-android-v4.2.2
(I have used this release version because release-android-v5.0.0 gives ANR input dispatching timed out error)

**Comment by jfirebaugh** [comment]
The pattern of network usage may depend on a number of factors such as network conditions, load on the tile server, load on the local device, and internal implementation details (offline downloads are designed not to consume all available network resources). In general, we can't guarantee a constant download speed for offline resources.
