### ISSUE TITLE
Unable to override default onMarkerClick behavior

### ISSUE THREAD

**Issue by guni82hu** [mapbox/mapbox-gl-native#8726]
I know that there is an existing ticket with a similar issue [(8159)](https://github.com/mapbox/mapbox-gl-native/issues/8159) but this one imho is not related to the touch area because the default info window appears when I tap on a marker. This is the proof that the sdk detects marker clicks well.  I've made a quick debug session and it seems the problem is the setOnMarkerViewClickListener in MarkerViewManager is never called. I would recommend the invocation from AnnotationManager.setOnMarkerClickListener().

**Platform:** Android
**Mapbox SDK version:** 5.0.2

### Steps to trigger behavior

```
mapFragment.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {

                mapboxMap.addMarker(new MarkerViewOptions()
                        .position(new LatLng(-33.85699436, 151.21510684))
                        .title("Sydney Opera House")
                        .snippet("Bennelong Point, Sydney NSW 2000, Australia"));

                mapboxMap.setOnMarkerClickListener(new MapboxMap.OnMarkerClickListener() {
                    @Override
                    public boolean onMarkerClick(@NonNull Marker marker) {
                        //...marker click handling code...
                        return true;
                    }
                });
```

### Expected behavior
onMarkerClick function should be called and the default info window shouldn't appear when the user clicks on the marker

### Actual behavior
onMarkerClick function is not called and default info window appears when the user clicks on the marker

**Comment by tobrun** [comment]
@guni82hu if you want to react on the MarkerView clicks you need to use `mapboxMap.getMarkerViewManager().setOnMarkerViewClickListener` instead of the default `OnMarkerClicklistener`. Feel free to reach out if you have any more questions!

**Comment by LukasPaczos** [comment]
I don't know when this behaviour was changed but upgrading from v4.2.0 where you could set `mapboxMap.setOnMarkerClickListener()` and click on any marker was handled, to now where you indeed need to set `mapboxMap.getMarkerViewManager().setOnMarkerViewClickListener()` to handle clicks on `MarkerView`, which I think is worth mentioning in [upgrade guide](https://github.com/mapbox/mapbox-gl-native/wiki/Android-4.x-to-5.0-update).

**Comment by tobrun** [comment]
Thanks for the ping on that LukasPaczos! Will add an entry
