### ISSUE TITLE
Showing black screen when i set HUD mode using scale value -1

### ISSUE THREAD

**Issue by erpratik7** [mapbox/mapbox-gl-native#8727]
Gradle file:
buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'
        classpath 'io.fabric.tools:gradle:1.+'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    mavenCentral()
    maven { url 'https://maven.fabric.io/public' }
}

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 22
        versionCode 21
        versionName "4.0.0-beta.2"
    }

/*
    signingConfigs {
       release {
           storeFile file(RELEASE_STORE_FILE)
           storePassword RELEASE_STORE_PASSWORD
           keyAlias RELEASE_KEY_ALIAS
           keyPassword RELEASE_KEY_PASSWORD
       }
    }
*/
    buildTypes {
        release {
            minifyEnabled false
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
//            signingConfig signingConfigs.release
        }
    }

}

dependencies {
    compile 'com.android.support:gridlayout-v7:25.2.0'
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.1@aar') {
        transitive = true
    }
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
}
---------------------------------------------------------------------

MainActivity.java
package com.mapbox.mapboxandroiddemo;

import android.Manifest;
import android.app.AlertDialog;
import android.content.DialogInterface;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.net.Uri;
import android.os.Bundle;
import android.provider.Settings;
import android.support.v4.app.ActivityCompat;
import android.support.v4.content.ContextCompat;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.RelativeLayout;

import com.crashlytics.android.Crashlytics;
import com.mapbox.mapboxsdk.Mapbox;
import com.mapbox.mapboxsdk.annotations.MarkerOptions;
import com.mapbox.mapboxsdk.camera.CameraUpdateFactory;
import com.mapbox.mapboxsdk.constants.Style;
import com.mapbox.mapboxsdk.geometry.LatLng;
import com.mapbox.mapboxsdk.maps.MapView;
import com.mapbox.mapboxsdk.maps.MapboxMap;
import com.mapbox.mapboxsdk.maps.OnMapReadyCallback;

import io.fabric.sdk.android.Fabric;

public class MainActivity extends AppCompatActivity implements OnMapReadyCallback {

    private static final int PERMISSIONS_LOCATION = 0;
    private MapView mv;
    private MapboxMap mapboxMap;
    private int scale = -1;
    private RelativeLayout baseLayout;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Fabric.with(this, new Crashlytics());
        Mapbox.getInstance(this, getString(R.string.testAccessToken));

        setContentView(R.layout.activity_main);

        mv = (MapView) findViewById(R.id.mapview);
        baseLayout = (RelativeLayout) findViewById(R.id.baseLayout);
        mv.onCreate(savedInstanceState);
        mv.getMapAsync(this);

        Button bugsBut = changeButtonTypeface((Button) findViewById(R.id.bugsButton));
        bugsBut.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                String url = "https://github.com/mapbox/mapbox-gl-native/issues?state=open";
                Intent i = new Intent(Intent.ACTION_VIEW, Uri.parse(url));
                startActivity(i);
            }
        });
    }

    @Override
    public void onMapReady(MapboxMap map) {
        mapboxMap = map;
        mapboxMap.setStyle(Style.MAPBOX_STREETS);
        mapboxMap.moveCamera(CameraUpdateFactory.newLatLng(new LatLng(0, 0)));

        // Show user location (purposely not in follow mode)
        if ((ContextCompat.checkSelfPermission(this, Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) ||
                (ContextCompat.checkSelfPermission(this, Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED)) {
            ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.ACCESS_FINE_LOCATION}, PERMISSIONS_LOCATION);
        } else {
            mapboxMap.setMyLocationEnabled(true);
        }

        // TODO - mv.loadFromGeoJSONURL("https://gist.githubusercontent.com/tmcw/10307131/raw/21c0a20312a2833afeee3b46028c3ed0e9756d4c/map.geojson");
        mapboxMap.addMarker(new MarkerOptions().title("Edinburgh").snippet("Scotland").position(new LatLng(55.94629, -3.20777)));
        mapboxMap.addMarker(new MarkerOptions().title("Stockholm").snippet("Sweden").position(new LatLng(59.32995, 18.06461)));
        mapboxMap.addMarker(new MarkerOptions().title("Prague").snippet("Czech Republic").position(new LatLng(50.08734, 14.42112)));
        mapboxMap.addMarker(new MarkerOptions().title("Athens").snippet("Greece").position(new LatLng(37.97885, 23.71399)));
        mapboxMap.addMarker(new MarkerOptions().title("Tokyo").snippet("Japan").position(new LatLng(35.70247, 139.71588)));
        mapboxMap.addMarker(new MarkerOptions().title("Ayacucho").snippet("Peru").position(new LatLng(-13.16658, -74.21608)));
        mapboxMap.addMarker(new MarkerOptions().title("Nairobi").snippet("Kenya").position(new LatLng(-1.26676, 36.83372)));
        mapboxMap.addMarker(new MarkerOptions().title("Canberra").snippet("Australia").position(new LatLng(-35.30952, 149.12430)));
    }

    /**
     * Dispatch onStart() to all fragments.  Ensure any created loaders are
     * now started.
     */

    @Override
    protected void onDestroy() {
        super.onDestroy();
        mv.onDestroy();
    }

    @Override
    protected void onStart() {
        super.onStart();
        mv.onStart();
    }

    protected void onStop() {
        super.onStop();
        mv.onStop();
    }

    /**
     * Dispatch onResume() to fragments.  Note that for better inter-operation
     * with older versions of the platform, at the point of this call the
     * fragments attached to the activity are <em>not</em> resumed.  This means
     * that in some cases the previous state may still be saved, not allowing
     * fragment transactions that modify the state.  To correctly interact
     * with fragments in their proper state, you should instead override
     * {@link #onResumeFragments()}.
     */

    @Override
    protected void onResume() {
        super.onResume();
        scale = scale * -1;
        Log.i("scale", String.valueOf(scale));
        mv.setScaleY(scale);
        mv.onResume();
    }

    /**
     * Dispatch onPause() to fragments.
     */
    @Override
    protected void onPause() {
        super.onPause();
        mv.onPause();
    }

    /**
     * Save all appropriate fragment state.
     *
     * @param outState outState
     */
    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mv.onSaveInstanceState(outState);
    }
/*
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater menuInflater = getMenuInflater();
        menuInflater.inflate(R.menu.menu_activity_main, menu);
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case R.id.menuItemStreets:
                mv.setStyle(Style.MAPBOX_STREETS);
                return true;
            case R.id.menuItemSatellite:
                mv.setStyle(Style.SATELLITE);
                return true;
            case R.id.menuItemEmerald:
                mv.setStyle(Style.EMERALD);
                return true;
            case R.id.menuItemDark:
                mv.setStyle(Style.DARK);
                return true;
            case R.id.menuItemLight:
                mv.setStyle(Style.LIGHT);
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }*/

    private Button changeButtonTypeface(Button button) {
        return button;
    }

    /**
     * Method to show settings  in alert dialog
     * On pressing Settings button will launch Settings Options - GPS
     */
    public void showSettingsAlert() {
        AlertDialog.Builder alertDialog = new AlertDialog.Builder(getBaseContext());

        // Setting Dialog Title
        alertDialog.setTitle("GPS settings");

        // Setting Dialog Message
        alertDialog.setMessage("GPS is not enabled. Do you want to go to settings menu?");

        // On pressing Settings button
        alertDialog.setPositiveButton("Settings", new DialogInterface.OnClickListener() {
            public void onClick(DialogInterface dialog, int which) {
                Intent intent = new Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS);
                getBaseContext().startActivity(intent);
            }
        });

        // on pressing cancel button
        alertDialog.setNegativeButton("Cancel", new DialogInterface.OnClickListener() {
            public void onClick(DialogInterface dialog, int which) {
                dialog.cancel();
            }
        });

        // Showing Alert Message
        alertDialog.show();
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        switch (requestCode) {
            case PERMISSIONS_LOCATION: {
                if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                    mapboxMap.setMyLocationEnabled(true);
                }
            }
        }
    }
}
-----------------------------------------------------------------------------
activity_main.xml

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:mapbox="http://schemas.android.com/apk/res-auto"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:id="@+id/baseLayout"
    android:orientation="vertical">

    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapview"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <Button
        android:id="@+id/bugsButton"
        style="?android:attr/buttonStyleSmall"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        android:layout_alignParentTop="true"
        android:text="@string/reportBugs" />

</RelativeLayout>
------------------------------------------------------------------------------
to reproduce:
just on and off the screen by clicking lock button which will call the method to trigger hud mode on and off.
------------------------------------------------------------------------------------
Screenshots are attached.check on a real device instead of emulator.device tested-moto g3,lg g4

![2017_04_12_20_38_01](https://cloud.githubusercontent.com/assets/8486978/24964887/1e3becd2-1fc0-11e7-9872-c328c1fda4bd.png)
![2017_04_12_20_38_13](https://cloud.githubusercontent.com/assets/8486978/24964889/1e9e7e2e-1fc0-11e7-988f-c56a6390fe98.png)

**Comment by tobrun** [comment]
@erpratik7 the rendering component used (SurfaceView) does not support View transformations as Scale. You can use TextureView for this though. You can enable this in MapboxMapOptions or through xml attributes. Closing as this is expected behaviour of a SurfaceView. Thank you for reporting, feel free to reach out if you have any other questions.

**Comment by erpratik7** [comment]
@tobrun Actually i wanted this feature in runtime instead of xml and using TextureView instead of SurfaceView is not in my hand rather its something regarding MapBox sdk implementation.And earlier it used to work so what is the best possible way to acheive this in my side

**Comment by erpratik7** [comment]
@tobrun can u provide the example for MapboxMapOptions regarding change of scale in mapBox.The main problem m having that am inverting the whole base layout together instead of doing it one by one for all the components....which has many imageviews and texts etc

**Comment by erpratik7** [comment]
@tobrun Thanks for the info

**Comment by erpratik7** [comment]
one more issue m facing is
app:texture_mode="true"
is working in sdk level 4.2.1 but not in 5.0.2.may be you have removed it in latest version.

**Comment by erpratik7** [comment]
@tobrun one more issue m facing is
app:texture_mode="true"
is working in sdk level 4.2.1 but not in 5.0.2.may be you have removed it in latest version.

**Comment by tobrun** [comment]
With 5.x versions it was renamed to `<attr name="mapbox_renderTextureMode" format="boolean"/>`

**Comment by erpratik7** [comment]
oh ok...Thanks @tobrun
