### ISSUE TITLE
Map does not respond after zoom

### ISSUE THREAD

**Issue by 3mph4515** [mapbox/mapbox-gl-native#8728]
**Galaxy S6 edge 10846 SM-G925F Android 5.1.1:**
**Mapbox SDK version: 5.0.2, google play samples version**

### Steps to trigger behavior

 1. Download official dev mapbox preview https://play.google.com/store/apps/details?id=com.mapbox.mapboxandroiddemo
 2. Launch "A simple map view"
 3. Zoom map 

### Expected behavior
Map works
### Actual behavior
Map doesn't work
Video :
https://www.youtube.com/watch?v=7VynW_5YRnk

**Comment by tobrun** [comment]
Thank you for reaching out and reporting this. 
Is this constantly reproducible?
Would you be able to retest this with disabling the overlay touch information?

**Comment by 3mph4515** [comment]
@tobrun Yes it is constantly reproducible. How can I disable the overlay touch?

**Comment by cvance** [comment]
We just got a user using s6 (Android 5.1) reporting the same issue. @3mph4515 do older versions of mapbox work?

**Comment by Guardiola31337** [comment]
It seems that #9299 is the same issue.

**Comment by tobrun** [comment]
Been doing tests on an s6 edge, not being able to reproduce this.
Can you compare device details with the device below?

![ezgif com-video-to-gif 64](https://user-images.githubusercontent.com/2151639/27952767-c204c320-6309-11e7-8ea0-eb0b5f99c61e.gif)

**Comment by tobrun** [comment]
Please let us know if this issue is still reproducible with latest 5.5.0 stable release. Closing as stale.
