### ISSUE TITLE
Map::cameraForLatLngBounds returns incorrect CameraOptions

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8737]
Been looking into an user reported bug that has the camera positioned above New York City  and is trying to move the camera to a `LatLngBounds` in China.

For the following China bounds:

![screenshot at 2017-04-13 10 10 42](https://cloud.githubusercontent.com/assets/2151639/24996087/d0b24f7a-2031-11e7-9b12-68e77ca6dcc9.png)

The following center coordinate is calculated with Map::cameraForLatLngBounds:

![screenshot at 2017-04-13 10 11 15](https://cloud.githubusercontent.com/assets/2151639/24996094/d5401676-2031-11e7-842a-f6c67a97b5f8.png)

This results in centering the camera on the east coast

![image](https://cloud.githubusercontent.com/assets/2151639/24996192/45420312-2032-11e7-86c7-5bf43c1a470e.png)

While we were expecting: [34.6212005,104.1363335]

![screenshot at 2017-04-13 10 22 10](https://cloud.githubusercontent.com/assets/2151639/24996448/30c460fa-2033-11e7-9b97-81c6cd7acaef.png)

#### Data to reproduce this with
New York City = [40.712730, -74.005953], z=12
China bounds =  [15.68169,73.499857], [53.560711, 134.77281]

GL-JS is handling the use-case described above correctly, see [here](http://jsfiddle.net/7jr0nbcv/).

**Comment by tobrun** [comment]
I added a unit test to validate the behaviour:

```cpp
TEST(Map, LatLngBoundsToCamera) {
    MapTest test;
    Map map(test.backend, test.view.getSize(), 1, test.fileSource, test.threadPool, MapMode::Still);

    map.setLatLngZoom({ 40.712730, -74.005953 }, 12);
    
    LatLngBounds bounds = LatLngBounds::hull({15.68169,73.499857},{53.560711, 134.77281});
    CameraOptions virtualCamera = map.cameraForLatLngBounds(bounds, {});
    ASSERT_NEAR(virtualCamera.center->latitude(), 34.6212005, 1e-7);
    ASSERT_NEAR(virtualCamera.center->longitude(), 104.1363335, 1e-7);
}
```



> Failure the difference between virtualCamera.center->latitude() and 34.6212005 is 2.2965077241166512, which exceeds 1e-7, where
virtualCamera.center->latitude() evaluates to 36.917708224116652,
34.6212005 evaluates to 34.6212005, and
1e-7 evaluates to 9.9999999999999995e-08.

>Failure the difference between virtualCamera.center->longitude() and 104.1363335 is 179.9999999999998, which exceeds 1e-7, where
virtualCamera.center->longitude() evaluates to -75.863666499999795,
104.1363335 evaluates to 104.13633350000001, and
1e-7 evaluates to 9.9999999999999995e-08.

This seems to produce the same results as what I had seen during debugging.

**Comment by jfirebaugh** [comment]
@brunoabinader, could you take a look here?
