### ISSUE TITLE
Delete mapbox-gl-ios bucket?

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapbox-gl-native#874]
Is anyone using the `mapbox-gl-ios` S3 bucket? It appears to be empty. Can this be removed? Any future work around this can be placed into the `mapbox` S3 bucket.

/cc @incanus @bleege @ljbade

**Comment by incanus** [comment]
Yes, I just created this a week or two ago to upload GL native builds to. I haven't done any work towards that yet, since we decided that providing `package_ios.sh` was enough for now.

**Comment by ljbade** [comment]
@incanus I think we will consolidate mapbox-gl stuff into https://github.com/mapbox/mapbox-gl-native/issues/875

**Comment by ljbade** [comment]
I will delete the bucket and we can upload iOS related files to `s3://mapbox/mapbox-gl-native/ios`

**Comment by ljbade** [comment]
Deleted.
