### ISSUE TITLE
Polygon coordinate order is not preserved in Geo JSON sources

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#8746]
I noticed while working on #8007 that the order of the coordinates in polygons is not always preserved correctly.

For example:
```
[
  [
    [-10, 10],
    [10, 10],
    [10, -10],
    [-10, -10],
    [-10, 10]
  ]
]
```

Is converted in:
```
[
  [
    [10, 10],
    [10, -10],
    [-10, -10],
    [-10, 10],
    [10, 10]
  ]
]
```

Which is functionally the same, but not identical. 

The bug seems to be caused in [GeoJSONTileFeature::getGeometries](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/tile/geojson_tile.cpp#L37)
 which calls [fixupPolygons](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/tile/geometry_tile_data.cpp#L39) as a workaround to https://github.com/mapbox/geojson-vt-cpp/issues/44.

**Comment by ivovandongen** [comment]
Closing as this is expected behaviour from https://github.com/mapbox/wagyu

**Comment by mourner** [comment]
I'd suggest looking into writing a custom comparator for rings that handles shifted coordinates.
