### ISSUE TITLE
Move mapbox-gl-testing bucket

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapbox-gl-native#875]
We should consolidate the contents of the S3 bucket `s3://mapbox-gl-testing` into the main `s3://mapbox` bucket if possible. Is there any reason to continue using a separate bucket?

/cc @ljbade

**Comment by ljbade** [comment]
Not as far as I am aware. Basically used to upload stuff per commit travis build for archiving etc.

So I suppose we would use `s3://mapbox/gl/`?

**Comment by willwhite** [comment]
> So I suppose we would use s3://mapbox/gl/?

Sure or `s3://mapbox/mapbox-gl-native/`. fwiw this is the pattern that `mapbox-studio` has established: `s3://mapbox/<repo_name>`.

**Comment by ljbade** [comment]
@willwhite I have moved everything over to the mapbox bucket, but will wait a few weeks incase anyone is still doing builds in a branch with the old bucket.

Then I can delete mapbox-gl-testing, and remove the references from the cloudformation templates.

**Comment by willwhite** [comment]
Awesome, sounds like a great plan. Thanks!

**Comment by jfirebaugh** [comment]
Bucket deleted.
