### ISSUE TITLE
Notification to keep Xamarin Bindings for both iOS and Android up-to-date

### ISSUE THREAD

**Issue by kanvuduc** [mapbox/mapbox-gl-native#8752]
Hi,

My team is using Mapbox for our projects. We are using Xamarin, so we have to do binding library ourselves to keep the library up-to-date with native SDKs.

[iOS Binding](http://github.com/naxam/xam-mapbox-ios)
[Android Binding](http://github.com/naxam/xam-mapbox-android)

Is there a way that I could get notification when your SDKs have new release?

Regards,
Tuyến

**Comment by friedbunny** [comment]
From iOS v3.5.0 onwards, the SDK checks for updates and puts a message in the console when a new release is available. See https://github.com/mapbox/mapbox-gl-native/issues/7311 for background and the status of this feature in Android.

### Other ways to check for updates
We tag and release on GitHub, so you should be able to use any of their available API — such as the [repos/releases endpoint](https://developer.github.com/v3/repos/releases/).

GitHub also offers RSS feeds for tags and releases:

https://github.com/mapbox/mapbox-gl-native/releases.atom
https://github.com/mapbox/mapbox-gl-native/tags.atom
