### ISSUE TITLE
Unable to npm install mapbox-gl-native (error 403)

### ISSUE THREAD

**Issue by Cube00** [mapbox/mapbox-gl-native#8753]
[cube@serv openmaptiles]$ sudo npm install -g mapbox-gl-native
npm WARN lifecycle mapbox-gl-native@3.4.2~preinstall: cannot run in wd %s %s (wd=%s) mapbox-gl-native@3.4.2 npm install node-pre-gyp /usr/lib/node_modules/.staging/mapbox-gl-native-ba8163c4

> mapbox-gl-native@3.4.2 install /usr/lib/node_modules/mapbox-gl-native
> node-pre-gyp install --fallback-to-build=false || make node

node-pre-gyp ERR! install error
**node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/mapbox-gl-native/v3.4.2/node-v48-linux-x64.tar.gz**
node-pre-gyp ERR! stack     at Request.<anonymous> (/usr/lib/node_modules/mapbox-gl-native/node_modules/node-pre-gyp/lib/install.js:120:27)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:188:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/usr/lib/node_modules/mapbox-gl-native/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:363:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Linux 4.10.9-200.fc25.x86_64
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/mapbox-gl-native/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /usr/lib/node_modules/mapbox-gl-native
node-pre-gyp ERR! node -v v6.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/mapbox-gl-native/v3.4.2/node-v48-linux-x64.tar.gz
which: no qmake in (/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/mapbox-gl-native/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/bin:/sbin:/bin:/usr/sbin:/usr/bin)
mkdir -p build/linux-x86_64/Debug
(cd build/linux-x86_64/Debug && cmake -G Ninja ../../.. \
        -DCMAKE_BUILD_TYPE=Debug \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DWITH_CXX11ABI=ON \
        -DWITH_COVERAGE= \
        -DIS_CI_BUILD= \
        -DWITH_OSMESA=)
-- The CXX compiler identification is GNU 6.3.1
-- The C compiler identification is GNU 6.3.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at cmake/mbgl.cmake:16 (message):
  Can't find node-cmake
Call Stack (most recent call first):
  CMakeLists.txt:5 (include)

-- Configuring incomplete, errors occurred!
See also "/usr/lib/node_modules/mapbox-gl-native/build/linux-x86_64/Debug/CMakeFiles/CMakeOutput.log".
Makefile:291: recipe for target 'build/linux-x86_64/Debug/build.ninja' failed
make: *** [build/linux-x86_64/Debug/build.ninja] Error 1
npm ERR! Linux 4.10.9-200.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "-g" "mapbox-gl-native"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! mapbox-gl-native@3.4.2 install: `node-pre-gyp install --fallback-to-build=false || make node`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mapbox-gl-native@3.4.2 install script 'node-pre-gyp install --fallback-to-build=false || make node'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapbox-gl-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build=false || make node
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapbox-gl-native
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapbox-gl-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cube/Downloads/openmaptiles/npm-debug.log

**Comment by jfirebaugh** [comment]
See #7727
