### ISSUE TITLE
NullPointerException when creating MapView from xml on android O

### ISSUE THREAD

**Issue by cezium** [mapbox/mapbox-gl-native#8766]
Bitmap copy(Config config, boolean isMutable) in android O returns null when trying to copy from bitmap with Bitmap.Config.ALPHA_8 to Bitmap.Config.ARGB_8888 resulting in NPE:

Tested using:
```
compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.2@aar'){
        transitive=true
    }
    compile ('com.mapbox.mapboxsdk:mapbox-android-services:2.0.0@aar'){
        transitive=true
    }

```

> 04-07 13:38:51.384 22717 22717 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{<ActivityClass>}: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class com.mapbox.mapboxsdk.maps.MapView
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2805)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(Unknown Source:0)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1537)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6408)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:232)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class com.mapbox.mapboxsdk.maps.MapView
04-07 13:38:51.384 22717 22717 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class com.mapbox.mapboxsdk.maps.MapView
04-07 13:38:51.384 22717 22717 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:326)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at <ActivityClass>.onCreate(LocationPickerActivity.java:191)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6767)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1195)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2805)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(Unknown Source:0)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1537)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6408)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:232)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getRowBytes()' on a null object reference
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.IconManager.loadIcon(IconManager.java:105)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.IconManager.<init>(IconManager.java:39)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.AnnotationManager.<init>(AnnotationManager.java:52)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView.initialise(MapView.java:143)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:93)
04-07 13:38:51.384 22717 22717 E AndroidRuntime: 	... 29 more

**Comment by tobrun** [comment]
Thank you for reaching out and testing our library with Android O, adding to next milestone to investigate.

**Comment by tobrun** [comment]
Confirming that I'm seeing the same crash when updating my `Nexus 6p` to `Android O Developer Preview 1`. It seems that the `Bitmap#copy` behaves differently on Android O. The following line produces a null bitmap when copying an ALPHA_8 bitmap to an ARGB_8888 one:

```
 bitmap = bitmap.copy(Bitmap.Config.ARGB_8888, false);
```
 
Will have to dig into the sources to see if this wanted behaviour or a bug in Android O.

**Comment by tobrun** [comment]
Created an upstream ticket in `[dev preview]` issue tracker [here](https://issuetracker.google.com/issues/37527627) to gather more information. I'm seeing that the Bitmap API is going to be changed though they should backport this behaviour.

**Comment by tobrun** [comment]
Capturing from the [upstream issue](https://issuetracker.google.com/issues/37527627):

> Thank you for reporting this issue. The issue has been fixed in our internal latest builds which will be the future android preview releases

Going to close this issue for now as no actions are required from our end. Will be retesting the SDK with next Android O preview 2. Thanks again for reporting this @cezium!
