### ISSUE TITLE
annotations plan

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#877]
"Annotations" is iOS-speak for points and polygons on the basemap with a high-level client-side API. 

* **Data** — This encapsulates such things as client-side data (#507) or formats like GeoJSON, and also includes programmatic addition of points and polygons that don't exist in files or formats at all (e.g. show user location, add these stores to the map, trace this route from parsed directions API). In fact, format-less features are the MVP for this. Spatial indexing falls under this category as well — the system needs to know what's on screen right now as well as be able to translate between pixel-space and geo-space (https://github.com/mapbox/mapbox-gl-native/pull/853). 

* **Design** — Polylines & polygons can get styling properties like width, fill color, opacity, and stroke color. This can change at runtime, so it's not part of the GL style. Markers can get a) static marker imagery, b) iOS `UIView` objects, or even c) animations of views. These can also all change / be provided at runtime. Markers always remain upright when the map rotates and order themselves in the z-axis from current top-to-bottom of screen, updating continuously as the map rotates. Lastly, marker annotations have callouts, which should be implemented specific to iOS (likely using [`SMCalloutView`](https://github.com/nfarina/calloutview) as our SDK does). 

* **Interaction** — Users can tap on poly & marker visuals and get callbacks with the associated data object referenced. 

* **API** — All APIs follow [Apple's MapKit](https://developer.apple.com/library/ios/documentation/MapKit/Reference/MapKit_Framework_Reference/index.html#//apple_ref/doc/uid/TP40008210), so relevant classes & protocols are `MKMapView`, `MKAnnotation`, `MKAnnotationView`, and `MKMapViewDelegate`. 

  - An `MKAnnotation`-derived data object is added (`map.addAnnotation(foo)`) .
  - An `MKMapViewDelegate` is set on a map (`map.delegate = bar`). 
  - When the visual for an annotation is relevant/on screen, a view is requested from the delegate, which creates it on the fly (`func mapView(map, viewForAnnotation: foo)`). 
  - The map maintains and responds to annotation selection state (`func mapView(map, didSelectAnnotation:foo)`)

Will kick off deeper tickets for each of these buildouts as we progress. 

![](https://github.com/mapbox/weekend-picks-template-ios/raw/master/screenshot.png)

**Comment by incanus** [comment]
[Conversion routines](https://github.com/mapbox/mapbox-gl-native/commit/6e41664cb033ee5edf6ae5ac66ed518d9f0d1f89) are in and [API](https://github.com/mapbox/mapbox-gl-native/blob/6e41664cb033ee5edf6ae5ac66ed518d9f0d1f89/include/mbgl/map/map.hpp#L132-L139) for mocking annotations atop the GL view is available. 

Next steps are @ljbade & @bleege checking out #756 on Android and I will start mocking markers (not spatially indexed, however, to start) to see how the FPS handles the compositing.

**Comment by incanus** [comment]
@kkaefer Here's a small sample project that does animated point markers and animated polygon rendering as an example of what an iOS developer might expect. 

## Markers

The [`ViewController` delegates](https://github.com/incanus/AniAnnoDemo/blob/4d86aa57a9a3db96d8c7d357bfc4963bbb229ec5/AniAnnoDemo/ViewController.swift#L44-L50) to the [`PointAnnotationView` class](https://github.com/incanus/AniAnnoDemo/blob/4d86aa57a9a3db96d8c7d357bfc4963bbb229ec5/AniAnnoDemo/PointAnnotationView.swift), which uses Core Animation to rotate itself over time (keyframe animations over a few seconds) and a repeating timer to alter its background color, alpha, and border thickness (eight or so animation steps). You could typically see something like this for a game or interactive app which uses keyframe animations at points on the map (animated oil wells or realtime pie charts, for example). 

## Polylines

The `ViewController` [also delegates](https://github.com/incanus/AniAnnoDemo/blob/4d86aa57a9a3db96d8c7d357bfc4963bbb229ec5/AniAnnoDemo/ViewController.swift#L52-L58) to the [`AnimatedRenderer` class](https://github.com/incanus/AniAnnoDemo/blob/4d86aa57a9a3db96d8c7d357bfc4963bbb229ec5/AniAnnoDemo/AnimatedRenderer.swift), which uses a timer to change the size of an image that is used as a tiled pattern fill color every few seconds. This is a bit of a contrived example, but you might do an animated radar overlay or a moving pattern animation to indicate flow across a map surface. 

--

The point is less about flashiness and more about the fact that an iOS dev will expect to author views and renderers as first-class Cocoa objects for the control of animations, colors, strokes, patterns, opacities, and timing.

**Comment by incanus** [comment]
Per voice with @1ec5, it might make sense to not necessarily adopt and either-or approach. For example, simple sprite-based markers (Maki or otherwise) could be done in the icon shader, but more complex views could be composited and tracked to the map per-platform. 

Of note in the simple use case is the fact that z-ordering matters; markers are ordered back-to-front (`z`) by order of top-to-bottom (`y`), including changing on the fly during map rotations. On iOS, when selected, a marker comes all the way to the front temporarily, then goes back in place on deselect.

**Comment by 1ec5** [comment]
> For example, simple sprite-based markers (Maki or otherwise) could be done in the icon shader, but more complex views could be composited and tracked to the map per-platform.

And ideally the heuristic would be on our end, not something the dev has to think about.

**Comment by mb12** [comment]
@incanus and @kkaefer Is it possible to share how you would synchronize between iOS UIView and GLViews. Otherwise there would always be a lag between overlay UIView (e.g. Bubble)  and underlying MGLMapView. Specifically this is the problem I am referring it.

http://stackoverflow.com/questions/12967340/how-to-synchronize-opengl-drawing-with-uikit-updates

**Comment by incanus** [comment]
> Is it possible to share how you would synchronize between iOS UIView and GLViews

I've had good luck using `CADisplayLink` for this in some old tests. 

https://github.com/incanus/FeaturesPlay

http://www.mobypicture.com/user/incanus771/view/17359491

I'm trying this again now in this project currently.

**Comment by incanus** [comment]
Pushed what I've been playing with at [`877-display-link` branch](https://github.com/mapbox/mapbox-gl-native/compare/877-display-link).

**Comment by incanus** [comment]
Per voice with @1ec5 @kkaefer, we decided the beta will not support full `UIView` objects passed by the delegate as annotation views, but rather only static imagery at this point. 

MapKit's delegate API, which we will model after, looks like this: 

```objc
- (MKAnnotationView *)mapView:(MKMapView *)mapView viewForAnnotation:(id<MKAnnotation>)annotation
```

When an annotation view is requested, you would return an `MKAnnotationView` or its subclass [`MKPinAnnotationView`](https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKPinAnnotationView_Class/index.html#//apple_ref/occ/cl/MKPinAnnotationView), which are all subclasses of `UIView`. 

What we can do as a first step is to only support an `MKPinAnnotationView`-like class which either: 

* Refers to known parameters such as Maki icon, color, or size (similar to `MKPinAnnotationView.pinColor`) and keys those to GL core routines to render those with the icon shader, or
* Accepts user-provided imagery which we pass across the boundary to the icon shader.

**Comment by mb12** [comment]
Is it possible to make the pins  draggable for iOS?

**Comment by incanus** [comment]
I'm not sure yet if we'll hit that for the beta, but eventually, yes. 
JM

**Comment by bleege** [comment]
Finished building the MapRegionIsChanging notification hook on `regionChanged` branch.  Waiting for Mr Travis to green light it and then I'll merge.

**Comment by incanus** [comment]
This is [looking good](https://github.com/mapbox/mapbox-gl-native/compare/regionChanged). However, do you get multiple fires of the region changing across animation durations? I think we need that. 

For example: animate the map view center over the default iOS duration (300ms). With the old callback methods, you get a ping at the start and a ping 300ms later. It seems like the same thing would happen with this added notification, too. What we should get instead is a ping per draw frame through that 300ms?

**Comment by incanus** [comment]
As for *how* to do this... I think it will involve looking into how the `transitions` are worked through on each frame, since that's where the state changing is happening. That is, `_moveBy()` sets up the animated change, but is not run through again; rather `transitions` are iterated on until complete, at which point they are removed. See around [here](https://github.com/mapbox/mapbox-gl-native/blob/0238e20c28839842eb9597928afa0f76b6516a40/src/mbgl/map/map.cpp#L670-L676).

**Comment by ljbade** [comment]
Yeah we need per frame callbacks, currently my Android app does not update the marker position during animation.

**Comment by 1ec5** [comment]
The 877-callout branch is all set with using delegate callbacks instead of `CADisplayLink`.

The last couple days I thought we were seeing that markers in the 877-display-link and 877-callout branches were jumping ahead of the map while panning. But it looks like the marker sometimes gets offset up to 50 meters after a drag, pinch, or rotation. That may point at a bug in the marker positioning rather than a synchronization issue.

**Comment by 1ec5** [comment]
But see also [this comment here](https://github.com/mapbox/mapbox-gl-native/commit/55ad2ee3b71b762a4e10ffba700b3949196e4fb5?diff=split#commitcomment-9852934).

**Comment by mb12** [comment]
@1ec5 
If you need to something per-frame, you can put your code in MBGLView::swap.(It **may** slow stuff down depending on what is done in the callback).
The overlay would still jitter, but it should get to the right location, when the  map animation finishes.

**Comment by incanus** [comment]
Interesting idea @mb12. I'm pretty sure Apple doesn't provide such a callback because of the potential to slow down rendering, but I think we may at least want this privately for such things as annotation sync. 

Only thing with `swap` though is that when we build up to more style transition animations & its API, that routine will run despite likely not needing annotation changes, i.e. `swap` will not be limited to merely zoom/pan changes.

**Comment by kkaefer** [comment]
Note that `::swap` is called in the Map rendering thread, so you'd need to dispatch to the UI thread, which would probably incur some lag as well, unless you block swap until the UI thread completed its actions.

**Comment by mb12** [comment]
Yes, that causes a really jarring jitter in the overlay view upon panning.

This is what others seems to be doing on iOS.

1.) Image pins and Polylines in opengl view.
2.) Detect tap and open either ActionSheet or some other UIView that does not need to pan with map.

Here is a link to the GMaps SDK for iOS. GMSMarker just shows the snippet in a static info window at the bottom instead of a pannable Apple Maps like Annotation View.

https://developers.google.com/maps/documentation/ios/reference/index

**Comment by incanus** [comment]
I'm curious if we've looked further into the per-animation-frame updates to the delegate callbacks? See https://github.com/mapbox/mapbox-gl-native/issues/877#issuecomment-75109583 above. @1ec5 @bleege can one of you look into this? I can possibly start to look into it next week but I'm tied up with GL-side annotation rendering right now. 

> Note that `::swap` is called in the Map rendering thread, so you'd need to dispatch to the UI thread, which would probably incur some lag as well, unless you block swap until the UI thread completed its actions.

Agreed, and I would say to probably at least try blocking swap to see how this fares.

**Comment by ljbade** [comment]
blocking swap could work, just make sure you don't do anything too heavy. need to see if it affects the smooth 60fps

**Comment by bleege** [comment]
Status Update: I've built the basic logging of an array of LatLng managed at the Core GL layer as directed by CADisplayLink in UIKit.  Initial indications are that they are firing per frame as desired.  More worked (see below) is required to finish this test off:

* [ ] Clean up array passing
* [ ] Implement conversion logic in Core GL
  * This will be the big "lag" test after it's completed.

**Comment by bleege** [comment]
Implemented tracking of and updating of Sample LatLngs (aka Features) converted to XY Points in the Core GL (on moveBy event) and displaying on the UIKit end by CADisplayLink.  Performance was just as smooth as as [original status update](https://github.com/mapbox/mapbox-gl-native/issues/877#issuecomment-76825286) of LatLng earlier today.  The only part of the process that was kept at the UIKit level was UIView's `- (CGPoint)convertPoint:(CGPoint)point toView:(UIView *)view;`

The next (and fingers crossed final) step in this test will be hook these coordinates up to annotations in the MapView and observe the performance.

FYI, all this work is on the [877-display-link](https://github.com/mapbox/mapbox-gl-native/compare/877-display-link) branch.

**Comment by 1ec5** [comment]
Status update: Worked towards pushing a generalized `calloutView` API down into `MGLMapView` à la `RMMapView` in mapbox-ios-sdk. Still need to figure out where best to initialize the callout view and associated markers so that `Map::state` is already set up with the correct coordinates. Got sidetracked by #924 again.

**Comment by bleege** [comment]
Just refactored the updating of annotations to be driven by Core GL computed locations via CADisplayLink.  Sadly, the annotations still lag noticeably on refresh when panning around on the map.

Next step is to consider possible things that can be refactored.

**Comment by bleege** [comment]
Converted drawing / updating of Annotations to be be placed on the GLKView instead of the UIView.  While not perfect it definitely showed some performance improvements in terms of animation updates when the map moved.  Will continue to work on this.

**Comment by bleege** [comment]
The UI is *MUCH* more responsive now with the hide / visible functionality added for the pins.  This is definitely getting closer to where things need to be.  I'm curious as to how big an impact a few optimizations could have (namely creating an annotation class to avoid all the dictionary lookups and geo object creations).  I'll try that next and see what happens.

**Comment by incanus** [comment]
This is sounding good @bleege. I'm curious what Instruments profiling turns up now? Might be an approach to check out.

**Comment by bleege** [comment]
@incanus I just profiled with Activity Monitor, Allocations, and GPU Driver.  Didn't turn up too much, although Allocations did hold pretty steady so I'm feeling pretty decent about that.  All in all I'm not sure how much more we can get considering that the app is crossing UIKit and OpenGL.  I'm curious how this behaves on actual iPhone / iPad compared to the emulator.

**Comment by incanus** [comment]
Give the Time Profiler a whirl and see what methods are taking up the most time — that might shed some light. It should also be a lot different on device — the simulator isn't GPU accelerated IIRC.

**Comment by bleege** [comment]
Nah.. the biggest time users are the MBGL drawing routines.

![20150303-timeprofile](https://cloud.githubusercontent.com/assets/989928/6473646/52e20a8a-c1c0-11e4-933f-5c7903ae5c1c.png)

**Comment by incanus** [comment]
Right, my point more is that if you filter out these routines that are known to be heavy and just focus on the Cocoa stuff, something *there* will be the "new heaviest" and you can see what that is. 

> You never really eliminate bottlenecks, you just move them around.

**Comment by bleege** [comment]
Yay!  I just ran it on my iPhone 5s with iOS 8.1.3 and it's smoooooooth.  I :heart: Apple hardware.

**Comment by bleege** [comment]
I'm going to pull the SampleLocation code out of Core GL codebase so that this branch can eventually be merged.

**Comment by incanus** [comment]
Sweet! This is great. Runs well for me, too. What is there to merge just yet, though @bleege? The actual driver of where the annotations should track to is coming in #893 and we have yet to architect what the annotation view classes look like, though they likely will be `UIImageView` like here, since we're only supporting Maki and user-inputted imagery (see https://github.com/mapbox/mapbox-gl-native/issues/941).

**Comment by bleege** [comment]
Awesome!  Thanks for testing it out @incanus.

As for what to merge the most important part is MGLMapView.h from 4ea6b2536f09883009bc004e383f5655cb8219eb where the GLKView is made accessible.  That said maybe the easiest way to get it in there would be to just cherrypick that file?

**Comment by incanus** [comment]
Ew, I think exposing the `GLKView` is confusing from a public API point of view. We should probably think about a class extension that's private that our own APIs can get to, as opposed to putting that in `MGLMapView.h`.

**Comment by incanus** [comment]
Or when we build out our actual annotation-adding API in Cocoa, it creates the subviews and adds them to the `GLKView` itself. The fact that this is in the view controller is an implementation detail *right now*, but consumers of our API need to be able to just run with `MGLMapView` and nothing else in their app.

**Comment by bleege** [comment]
Totally makes sense... I just had put it there more for expediency purposes when I was experimenting earlier today.  Maybe the best thing to do is just leave [this branch](https://github.com/mapbox/mapbox-gl-native/compare/877-display-link) as is and just use it to guide #893 and #941?

**Comment by incanus** [comment]
Yeah, that's kinda what I had in mind with the "what to merge" above. We figured out how we're going to do it technically, but let's get some other pieces into place first. 

I see next steps in this department as: 

1. Make a call on https://github.com/mapbox/mapbox-gl-native/issues/941 for the beta, or just Maki imagery / annotation marker imagery prebuilt into the style(s). 
1. Get #893 to land, providing API to say where annotations are at any given point. 
1. Write live annotation C++ API. 
1. Wrap API in MapKit-like Cocoa goodness.

**Comment by incanus** [comment]
> Markers always remain upright when the map rotates and order themselves in the z-axis from current top-to-bottom of screen, updating continuously as the map rotates.

We've got a ticket for this over in JS in https://github.com/mapbox/mapbox-gl-js/issues/470 but it seems to still be an issue: 

![screen shot 2015-03-11 at 1 48 02 pm](https://cloud.githubusercontent.com/assets/17722/6606717/ced43eec-c7f6-11e4-9e01-546b1e0728f7.png)

@kkaefer @ansis @jfirebaugh Any sense of how much work would be involved with this? We will likely also want the ability to temporarily bring a marker to the front upon selection. 

/cc @1ec5

**Comment by jfirebaugh** [comment]
Seem like it's time to unbundle this into separate followup tickets and close here.

**Comment by incanus** [comment]
Yep, agree. I will ticket some off now.

**Comment by incanus** [comment]
* Data backend is happening in https://github.com/mapbox/mapbox-gl-native/issues/893

* Annotation z-ordering is happening in https://github.com/mapbox/mapbox-gl-native/issues/988

Thus far Cocoa API is meant to work like Apple's, but we may modify that as @1ec5 and I discuss integration steps.

**Comment by maciekish** [comment]
@incanus Is it possible to draw routes in the current version? We are using an RMAnnotation with an array of CLLocations at the moment.

**Comment by incanus** [comment]
No, routes are coming later. Just points for now. Watch #893.

**Comment by picciano** [comment]
@incanus Any update on the work to support routes (polylines) now that Beta 1 is about wrapped up? This is our single biggest need right now and I would very much appreciate your thoughts on possible timing.

**Comment by incanus** [comment]
@picciano Shape annotations are one of the major focuses for b2. We'll have better timelines shortly, but we are thinking on the order of weeks.
