### ISSUE TITLE
GL program binaries not being used on any platform

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#8772]
Program binary caching is enabled only if `MBGL_HAS_BINARY_PROGRAMS` is true. It's defined in `mbgl/gl/features.hpp`, but the only file that includes that file is `mbgl/gl/program_binary.hpp`, and the only file that includes `mbgl/gl/program_binary.hpp` is the cpp file, which isn't in core-files.cmake.

Adding these files to core-files.cmake [produces CI failures](https://travis-ci.org/mapbox/mapbox-gl-native/jobs/223724885).

cc @kkaefer

**Comment by kkaefer** [comment]
There are a few other files that include `features.hpp`. The actual extension is in `src/mbgl/gl/program_binary_extension.hpp`; the files you were mentioning are from a bad merge after  https://github.com/mapbox/mapbox-gl-native/pull/8210 landed and can be removed safely.
