### ISSUE TITLE
Can't get my location

### ISSUE THREAD

**Issue by hchy9777** [mapbox/mapbox-gl-native#8778]
**Platform:android
**Mapbox SDK version:5.0.2

my phone is samsung s6,android 6.0.1

I follow the location example of the mapbox andorid demo,but can't get my location。

the pervious version of mapbox which i use is 4.2.1 ，everything is good.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by neonwarge04** [comment]
@jfirebaugh this should be open I am encountering same issue. LocationEngine.getLastLocation keeps returning null.

**Comment by neonwarge04** [comment]
I try to recreate this issue on Demo app and it still happens. All of sudden `getLastLocation` gets null. Try it on your demo app put line breaks in. It doesn't return anything. 

I've also checked if the apiClient is connected but the actual call to engine's `getLastLocation` is returning null:

`
  @Override
  public Location getLastLocation() {
    if (lostApiClient.isConnected() && PermissionsManager.areLocationPermissionsGranted(context.get())) {
      //noinspection MissingPermission
      return LocationServices.FusedLocationApi.getLastLocation(lostApiClient); // this line keeps returning null
    }

    return null;
  }
`

I also make sure that atleast MapBox is fully intialized but still can't get my location. Any thoughts?

**Comment by hchy9777** [comment]
i just copy the code of the user location demo on the official website  and can not get my location。for the 4.x.x version, it is good.

P.S:I am from china, the android phone in china don't have google play service.

**Comment by hchy9777** [comment]
For a day of check the code, i found the problem.       
In AndroidManifest.xml
`        tools:node="replace"
`
this line of code is redundant.
i delete it and i can get the location now.
