### ISSUE TITLE
Location requests remain on after app is hidden

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-gl-native#8787]
Test app:
![98c3a10a-2517-11e7-8394-33738f140d9f](https://cloud.githubusercontent.com/assets/4394910/25241912/8c3d6f34-25ac-11e7-98ce-1a5876392c2a.gif)

**Platform:** Android
**Mapbox SDK version:** 5.0.2

### Steps to trigger behavior

> 1. open your Dev-app and open any view, where the GPS-position is needed
> 2. Now close this view and/or minimize the whole app
> 3. As you can see in the upper infos from Android (where the time and signal strength is shown), there is also the GPS-icon
> 4. It only disappears, if you kill the „Mapbox Dev“-app

### Expected behavior

location tracking stops once app is hidden

### Actual behavior

location tracking continues even if app isn't in foreground

**Comment by zugaldia** [comment]
cc: @tobrun @Guardiola31337 for 👀

**Comment by tobrun** [comment]
Looks like this was already reported in https://github.com/mapbox/mapbox-gl-native/issues/8683. That issue has been added to the `v5.1.0` milestone and should get addressed for next release. Will  add a comment to #8683 for visibility. Closing as a duplicate.
