### ISSUE TITLE
split OS X & two-way iOS builds to three-point matrix on Travis

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#880]
https://github.com/mapbox/mapbox-gl-native/blob/6da0ef3d6df9fa559252d4922f22f0c160c50fa2/scripts/travis_script.sh#L37-L51

**Comment by jfirebaugh** [comment]
Let's wait to try this. Given how long OSX builds tend to be queued on Travis it could end up taking longer overall.

**Comment by incanus** [comment]
Testing here has gone well in e.g. https://travis-ci.org/mapbox/mapbox-gl-native/builds/57421692. This will get rolled in as part of #1219.
