### ISSUE TITLE
My location icon jumps when map is being dragged

### ISSUE THREAD

**Issue by hanspeide** [mapbox/mapbox-gl-native#8803]
**Platform:** Android 5.1 and 6.1.2
**Mapbox SDK version:** 5.0.2

### Steps to trigger behavior
 1. Set my location enabled with `map.setMyLocationEnabled(true);`
 2. Drag map back and forh

### Expected behavior
My location marker stays in the exact same position

### Actual behavior
My location marker jumps around. See https://www.youtube.com/watch?v=nKqKrVuV3uU

**Comment by tobrun** [comment]
More background on this issue in #8224, I'm seeing you are testing on an emulator, real device should deliver a better UX. At some point we are going to move from a Android SDK View to a core implementation. Though this will probably be implemented as a plugin at that time. Progress on the implemenation in https://github.com/mapbox/mapbox-gl-native/pull/7516

**Comment by hanspeide** [comment]
@tobrun This is from a real device, but looks like an emulator as I used Vysor to do the screen capture. Anyway, good to know that it's being addressed :)

**Comment by tobrun** [comment]
@hanspeide do you have more information on the device type?

**Comment by hanspeide** [comment]
Seeing it both on a LenovodPad YT3-X50L (Android 5.1.1) and a Google Pixel (Android 6.1.2). Here's an example from the Pixel: https://www.youtube.com/watch?v=UU1q83xvkuo&speed=0.25

**Comment by hanspeide** [comment]
@tobrun  I did by the way do a quick spike on `MarkerView`s the other day, and was seeing similar issues there. I guess the location icon is a `MarkerView`, and that it's therefore tracked in the issue you mentiode?
