### ISSUE TITLE
Navigating c++ source files in Android Studio

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8805]
We recently added integration for developing this project directly from Android Studio #5855. One of the difficulties is navigating the project when a core file matches a Android binding equivalent file. 

For example, when trying to open `background_layer.cpp`. It's currently not possible to differentiate between the core and the android binding file:

<img width="1105" alt="screen shot 2017-04-24 at 13 24 31" src="https://cloud.githubusercontent.com/assets/2151639/25335181/3ba4f29c-28f2-11e7-894a-ed3bb3a5019f.png">

This also partially shows in the project viewer. The directories are intermingled and it's hard to see at first glance if the file is found in core or not. 

<img width="615" alt="screen shot 2017-04-24 at 13 25 17" src="https://cloud.githubusercontent.com/assets/2151639/25335219/6bc805c2-28f2-11e7-9c5d-6795555b0396.png">

cc @ivovandongen

**Comment by jfirebaugh** [comment]
@tobrun Is there a next action here?

**Comment by tobrun** [comment]
I apparently misunderstood from @ivovandongen that there is a solution for this atm. No action needed. Closing.
