### ISSUE TITLE
Build error with NDK r15 beta1

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#8807]
`r15` will be the next NDK version, which is [currently in beta](https://developer.android.com/ndk/downloads/index.html#beta-downloads). A user is reporting the following compile error when trying to build the SDK with this version:

```
#include <experimental/optional>

namespace mbgl {

template <typename T>
using optional = std::experimental::optional<T>;

}  
```

```
In file included from /Users/xxx/projects/projects-android/maps-yyy-android/yyy-mapbox/src/main/jni/../../../../MapboxGLAndroidSDK-release/include/mbgl/map/map.hpp:
3:
/Users/xxx/projects/projects-android/maps-yyy-android/yyy-mapbox/src/main/jni/../../../../MapboxGLAndroidSDK-release/include/mbgl/util/optional.hpp:8:37: error: no type named 'optional' in namespace 'std::experimental'
using optional = std::experimental::optional<T>;
                 ~~~~~~~~~~~~~~~~~~~^
/Users/xxx/projects/projects-android/maps-yyy-android/yyy-mapbox/src/main/jni/../../../../MapboxGLAndroidSDK-release/include/mbgl/util/optional.hpp:8:45: error: expected ';' after alias declaration
using optional = std::experimental::optional<T>;
                                            ^
                                            ;
```

Let's use this ticket to kick off `r15`-related issues (we won't likely be upgrading until it reaches stable state).

**Comment by tobrun** [comment]
@kkaefer has started looking into this in #8705

**Comment by jfirebaugh** [comment]
This particular build error stems from building with a [NDK C++ runtime](https://developer.android.com/ndk/guides/cpp-support.html) other than the LLVM libc++ runtime. We support only the libc++ runtime.

**Comment by yoursungjin** [comment]
@jfirebaugh 
Hi, I'm struggling with the same compile error 
with the cmake arguments of "-DANDROID_STL=c++_static".

I'm at commit 787bbdfa51831fee5a9f6032c32e191677a802bd and using NDK 18.
I'd appreciate it if you could check it for me.
