### ISSUE TITLE
Every tile parser thread needs its own Style object

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#881]
Style objects are currently shared among several threads. They also modify the style object. #879 addresses some of this by locking `StyleBucket` objects. Instead, every tile worker should have its own copy of the Style object so that we can't mutate it while the tile parser is currently using it. In addition to that, Style objects should be fully `const`; right now we're resolving parse time constants depending on the current tile's zoom level and change the Style object.

**Comment by ljbade** [comment]
Not sure if this was fixed already but being able to load/save the style's state without waiting for the style JSON to load is needed for Android to restore state when a backgrounded application is terminated then restarted in the foreground.

**Comment by kkaefer** [comment]
Nope, we're currently parsing the Style object in the UI thread, unless it's loaded via HTTP. This is a different issue though and captured in #883.

**Comment by incanus** [comment]
@kkaefer How critical do you think this is? Is this something that we can push from the iOS beta milestone? What is the practical possibility of multi-threaded mutation right now?

**Comment by kkaefer** [comment]
Not critical for Beta. There are a few other patches (cf235c65926d72d00d2eb1a6ace9f9ab2d701a5c, e00bae4f1c9fed201dd01f641f7849d4178e0e7c, c30bb1a9f80a7a772578d8742e122c013a56202d, e8389d82cdd84d470deb072d82ee9a613cd15df8, 0151fe6c01367ef03a2ff282b90e32dd3785a7c2) in master that alleviate most of this.

**Comment by kkaefer** [comment]
This is no longer an issue.
