### ISSUE TITLE
Scope all Log::* messages to a Map object

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#882]
We are currently using global log messages, which makes it hard to find out what messages belong to which map object. Instead, we should associate these log messages with a particular Map object.

**Comment by ljbade** [comment]
Perhaps at the same time do https://github.com/mapbox/mapbox-gl-native/issues/613

**Comment by mikemorris** [comment]
:+1:

**Comment by kkaefer** [comment]
More background: Our Log::* output on a global level. When using multiple Map objects in one process, it's impossible to tell which Map object (or FileSource object) a log message is from. This makes it impossible to associate any errors with the correct object. In addition to that, many log messages should probably be turned into some sort of errors. Not sure if an additional error reporting facility is out of scope for this issue though.
