### ISSUE TITLE
I can't get the 'configuration.gradle'

### ISSUE THREAD

**Issue by StannyBing** [mapbox/mapbox-gl-native#8822]
I had tried to use 'make platform/android/configuration.gradle'.
but I use the Windows system,Even if I download the MinGw, I still can't make this file,so how can I build it?
Or You can upload a default file'configuration.gradle',so i can modify it ,could you help me?
thank you anyway.

**Comment by jfirebaugh** [comment]
Sorry, we don't support building the Android SDK from source on Windows. However, you don't have to build from source to use the SDK; see [our documentation](https://www.mapbox.com/android-sdk/).

**Comment by Xgamefactory** [comment]
that is very bad (
we were struggling trying to build from source on windows.
#13043
