### ISSUE TITLE
I cant build mapbox ql for qt

### ISSUE THREAD

**Issue by aktaytr** [mapbox/mapbox-gl-native#8827]
Hi all,

I am new at qt.I cant build mapbox gl for qt. Which use sub directory do I need to do Qt-lib and qt-app operations?
I get an error when I run qt-lib in the Mapbox folder:

`CMake Error at platform/qt/qt5.cmake:3 (find_package):
  By not providing "FindQt5Location.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Location", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Location" with
  any of the following names:

    Qt5LocationConfig.cmake
    qt5location-config.cmake

  Add the installation prefix of "Qt5Location" to CMAKE_PREFIX_PATH or set
  "Qt5Location_DIR" to a directory containing one of the above files.  If
  "Qt5Location" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  platform/qt/qt.cmake:82 (include)
  platform/qt/config.cmake:1 (include)
  CMakeLists.txt:84 (include)

-- Configuring incomplete, errors occurred!
See also "/home/abdullah/mapbox-gl-native/build/qt-linux-x86_64/Debug/CMakeFiles/CMakeOutput.log".
Makefile:380: recipe for target 'build/qt-linux-x86_64/Debug/build.ninja' failed
make: *** [build/qt-linux-x86_64/Debug/build.ninja] Error 1
`

**Comment by ibriq** [comment]
I am dealing with the exact same issue, @aktaytr. Any pointers?

**Comment by aktaytr** [comment]
@ibriq 
If you share the error I try to help you.

**Comment by ibriq** [comment]
@aktaytr It is just the same one. :-)

**Comment by aktaytr** [comment]
`sudo apt-get install curl git build-essential zlib1g-dev automake \
                     libtool xutils-dev make cmake pkg-config python-pip \
                     libcurl4-openssl-dev libpng-dev libsqlite3-dev \
                     libllvm3.4`
Change the above and install it.

`sudo apt-get install curl git build-essential zlib1g-dev automake \
                     libtool xutils-dev make cmake pkg-config python-pip \
                     libcurl4-openssl-dev libpng-dev libsqlite3-dev \`

**Comment by ibriq** [comment]
Thanks, man! Brilliant.
