### ISSUE TITLE
Requests to api.mapbox.com/styles/v1/ for raster tiles fail because of events=true query param added to url

### ISSUE THREAD

**Issue by JesseCrocker** [mapbox/mapbox-gl-native#8829]
**Platform:** iOS
**Mapbox SDK version:** 3.5.2

### Steps to trigger behavior

 1. Add a raster layer with a url like http://api.mapbox.com/styles/v1/XXX/XXX/tiles/256/{z}/{x}/y@2x?access_token=XXX

### Expected behavior
Tiles will load

### Actual behavior
Tiles fail to load.

The tiles fail to load, because `&events=true` is added onto the url, and that causes api.mapbox.com to respond with `{"message":"Invalid query param events"}`

The parameter is being added onto the url at https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/http_file_source.mm#L208

One answer to this is that i should loading that source as a style, instead of having the server rasterize it, and that makes sense, but i develop an application that allows users to add their own tile sources, and many of my users are Mapbox customers, and they want to use their own maps.

I see 2 solutions to this:
1. Only add events=true to requests that actually need it
2. Make api.mapbox.com not treat the extra parameter as an error

**Comment by kkaefer** [comment]
Android has the same behavior: https://github.com/mapbox/mapbox-gl-native/blob/839ad87f37a4880804fb4c79157d998ac59954b5/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HTTPRequest.java#L66-L74

**Comment by JesseCrocker** [comment]
Is there any chance this will get fixed server side, or do i need to fix it in the sdk if i want this to work?

**Comment by jfirebaugh** [comment]
Thanks for the report. We'll fix this server side.

**Comment by bsudekum** [comment]
The deploy is complete and static/tile requests with the `events` query param should work just fine now.
