### ISSUE TITLE
Don't parse Style object in the UI thread

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#883]
`Map::setStyleJSON()` currently parses a new stylesheet, while `Map::setStyleURL()` will parse the style in the Map thread.

**Comment by ljbade** [comment]
I think we should drop `setStyleJSON` for use outside of mbgl. https://github.com/mapbox/mapbox-gl-native/issues/900

**Comment by jfirebaugh** [comment]
Fixed in #1065.
