### ISSUE TITLE
IOS : App Crashing (Mapbox`___lldb_unnamed_symbol5144$$Mapbox) 

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [mapbox/mapbox-gl-native#8831]
**Platform**:  IOS
**Mapbox SDK version**:  3.5.0

### Steps to trigger behavior

 1. Tapped on map to get visible feature for two to three time continuously.

### Expected behavior
 1. To return the array of visible feature. 

### Actual behavior
 1.  App is Crashed, look at the below attached image,

<img width="332" alt="issue" src="https://cloud.githubusercontent.com/assets/17313049/25471260/e12b9fec-2b43-11e7-924d-8d36a227d2d7.png">

<img width="1043" alt="issue2" src="https://cloud.githubusercontent.com/assets/17313049/25471266/e8e72710-2b43-11e7-8b9f-085e7413d6b9.png">

Thanks,
Raju.

**Comment by jmkiley** [comment]
Hi @ThiyagarajanShivSankaran, 

Could you please share a small, isolated code sample that reproduces this issue? I have not been able to repro it. Also, are you seeing any other error messages?
