### ISSUE TITLE
How to use MapboxGL on Qt creator

### ISSUE THREAD

**Issue by aktaytr** [mapbox/mapbox-gl-native#8834]
How can I use the offline map for other location applications with qt creator?

Thanks.

**Platform:**
**Mapbox SDK version:**

### Steps to trigger behavior

 1.
 2.
 3.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by tmpsantos** [comment]
@aktaytr Mapbox GL is now part of the official Qt 5.9, if you simply download Qt 5.9 beta binaries using the official Qt installer, Mapbox GL will just work (Windows is not supported, but Linux, Android, macOS and iOS is).

See:
https://blog.qt.io/blog/2017/04/07/qt-5-9-beta-released/
https://doc-snapshots.qt.io/qt5-5.9/location-plugin-mapboxgl.html

**Comment by aktaytr** [comment]
@tmpsantos 
Thank you for your comment.
I want to use offline map in my qml application. I found mapboxGL native for this.But I have no idea how to include offline mapboxgl. 

Thanks.

**Comment by tmpsantos** [comment]
@aktaytr I will reply on the ticket you opened at our support channel.

**Comment by hakan9462** [comment]
Hello @tmpsantos,

i have the same Problem, i want to use the offline Tool in my qml application. I use the Mapboxgl plugin in QT, but i dont know how to create a offline database with the offline tool.

Can you help me?

Thanks!!

**Comment by tmpsantos** [comment]
Hi @hakan9462, we don't expose the offline API on the QML plugin, it is not a supported feature and cannot be used in runtime.

You can manually build the offline tool and do something like this to populate a database and preload with your app.
https://github.com/mapbox/mapbox-gl-native/blob/master/bin/offline.sh
