### ISSUE TITLE
Add light property to MGLStyle

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8840]
Per https://github.com/mapbox/mapbox-gl-native/pull/8431#issuecomment-295454244, MGLStyle needs a `light` property that lets the developer set [style-wide parameters](https://www.mapbox.com/mapbox-gl-js/style-spec/#light) like lighting color and intensity. We’ll need an MGLLight class to hold these individual properties. Hopefully we can make MGLLight consistent with SceneKit’s [SCNLight](https://developer.apple.com/reference/scenekit/scnlight?language=objc) and the style specification simultaneously.

One complication is that `mbgl::Map::setLight()` takes a `std::unique_ptr` instead of an `mbgl::style::Light` object by value (which is how `mbgl::CameraOptions` and `mbgl::AnimationOptions` work). Developers will expect MGLLight to be a value class along the lines of MGLMapCamera.

/cc @fabian-guerra @lbud @jfirebaugh

**Comment by ivovandongen** [comment]
@fabian-guerra FYI I'm making some slight adjustments to the light API in https://github.com/mapbox/mapbox-gl-native/pull/8889.

**Comment by 1ec5** [comment]
#8889 moves mbgl’s Light interface to codegen, which suggests that we should probably use codegen to build MGLLight.h and MGLLight.mm as well.

**Comment by 1ec5** [comment]
#8841 is the corresponding Android issue.

**Comment by 1ec5** [comment]
Fixed in #9043 on the release-ios-v3.6.0-android-v5.1.0 branch.
