### ISSUE TITLE
Add light settings to MapboxMap

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8841]
Per https://github.com/mapbox/mapbox-gl-native/pull/8431#issuecomment-295454244, `MapboxMap` needs `getLight()` and `setLight()` methods for setting [style-wide parameters](https://www.mapbox.com/mapbox-gl-js/style-spec/#light) like lighting color and intensity. We’ll need a `Light` class to hold these individual properties.

/cc @ivovandongen @tobrun @lbud @jfirebaugh

**Comment by tobrun** [comment]
The core implementation landed with https://github.com/mapbox/mapbox-gl-native/pull/8889 :tada:, I will now work on the Android binding of this.

**Comment by 1ec5** [comment]
#8840 is the corresponding iOS/macOS issue.

**Comment by tobrun** [comment]
This happened in #9013, closing.
