### ISSUE TITLE
MapboxMap.OnCameraChangeListener.onCameraChange() is called with a simple click on the map

### ISSUE THREAD

**Issue by TranThuong** [mapbox/mapbox-gl-native#8844]
**Platform:ANDROID**
**Mapbox SDK version:5.0.2**

### Steps to trigger behavior

Registre the mapbox camera change listener as below 

Mapbox.setOnCameraChangeListener(new MapboxMap.OnCameraChangeListener() {
            @Override
            public void onCameraChange(CameraPosition position) {
                Log.d(""," onCameraChange="+position);
            }
});

Start an application then click on the map or long press on the map

### Expected behavior
the method onCameraChange mustn't be called in the cases of a click or a long press on the map

### Actual behavior
Just a click on the map, I don't change the position of the camera, however the onCameraChange is called three time with a same position.

**Comment by tobrun** [comment]
with the upcoming `5.1.0` release we are deprecating the methods mentioned in OP and introducing a newer, finer grained camera change listener system. You can read more about it in #6350 and the WIP PR in #8644. Thank you for reaching out but closing this as non-actionable, API is going to become deprecated.
