### ISSUE TITLE
Release of stable artefacts through CI

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8858]
With the move from Bitrise to Circle CI in #8551 we lost the ability to use our CI to publish stable releases.  We used to do this by executing `scripts/release.py` on our development machines. This script would take care of creating a release branch, pushing release related changes and triggering a build on CI. We should look into reintegrating this script into Circle CI or find another way of doing automated releases.

cc @zugaldia

**Comment by kkaefer** [comment]
Noting here that Circle CI also supports triggered builds. Additionally, Circle CI also publishes the release APK at https://circleci.com/gh/mapbox/mapbox-gl-native/1837#artifacts/containers/0

**Comment by zugaldia** [comment]
Looks like CircleCI has the right [API for this](https://circleci.com/docs/api/v1-reference/):

> POST: /project/:vcs-type/:username/:project/tree/:branch
> Triggers a new build, returns a summary of the build. Optional build parameters can be set as well.

I can look into updating the Bitrise API call to CircleCI before `5.1.0-beta2`.

**Comment by tobrun** [comment]
This landed with #8950, closing
