### ISSUE TITLE
[Question] How to move Mapbox watermark to right corner in Android?

### ISSUE THREAD

**Issue by qasimalbaqali** [mapbox/mapbox-gl-native#8867]
How to move the Mapbox watermark from the left corner to the right or top right corner in Android using the latest version 5.0.2?

**Comment by tobrun** [comment]
@qasimalbaqali you can change this with `UiSettings#setLogo....` methods. You can get a reference to UiSettings through `MapboxMap#getUiSettings`. Going to close this as answered. If you have any follow up questions, please contact us through http://mapbox.com/contact
