### ISSUE TITLE
FillExtrusionLayer not shown for cached tile

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8871]
Use-case to reproduce this: 
 - startup a map and wait a few seconds
 - press a button to add a FillExtrusionLayer to the map

![ezgif com-video-to-gif 47](https://cloud.githubusercontent.com/assets/2151639/25655006/a15c3b10-2ff3-11e7-8a9b-fe3913d91d98.gif)

I'm noticing that 
 - FillExtrusionLayer isn't shown for the current cached tile
 - panning shows extrusions on other tiles
 - zooming out shows extrusions, zooming back in removes them again

Side-note, this doesn't occur if you add a FillExtrusionLayer as result of `onDidFinishLoadingStyle`.

**Comment by lbud** [comment]
🤕 
Does this problem also manifest if you add a different layer type (e.g. a fill layer) at runtime? I can't think of anything about fill extrusion layers that would make them behave differently than other types when it comes to tile parsing 😕

**Comment by ivovandongen** [comment]
> Does this problem also manifest if you add a different layer type

@lbud I have the strong suspicion that it does. See https://github.com/mapbox/mapbox-gl-native/issues/8833

**Comment by tobrun** [comment]
@lbud  to valiidate if this was a general issue with layers, I changed the FillExtrusionLayer with a FillLayer using [this](https://gist.github.com/tobrun/085903199b9926950bafe35d1b4f5ff5) geojson source. This seem to be added correctly to the map though the are some differences in setup (filter +  geojson source).

Code used:
```java
    try {
      GeoJsonSource jsonSource = new GeoJsonSource("uk-borders", new URL("https://gist.githubusercontent.com/tobrun/085903199b9926950bafe35d1b4f5ff5/raw/b67da310e4df0491899ba452f899d39c05370c32/gistfile1.geojson"));
      mapboxMap.addSource(jsonSource);
    } catch (MalformedURLException e) {
      throw new RuntimeException();
    }
    FillLayer fillLayer = new FillLayer("uk-borders", "uk-borders");
    fillLayer.setProperties(fillColor(Color.LTGRAY), fillOpacity(0.6f));
    fillLayer.setMinZoom(15);
    mapboxMap.addLayer(fillLayer);
```

@ivovandongen while they could be related. There is a small difference: the buildings disappear again when zooming to the initial zoom level. In #8833, the SymbolAnnotation don't disappear after they where rendered correctly by zooming.

**Comment by lbud** [comment]
I got this set up on the MacOS app where I used the same vector layer setup for both layers:
```
    MGLSource *streetsSource = [self.mapView.style sourceWithIdentifier:@"composite"];
    MGLFillStyleLayer *fillLayer = [[MGLFillStyleLayer alloc] initWithIdentifier:@"extrusions" source:streetsSource];
    fillLayer.sourceLayerIdentifier = @"building";
    fillLayer.fillColor = [MGLStyleValue valueWithRawValue:[NSColor blueColor]];
```
```
    MGLSource *streetsSource = [self.mapView.style sourceWithIdentifier:@"composite"];
    MGLFillExtrusionStyleLayer *fillExtrusionLayer = [[MGLFillExtrusionStyleLayer alloc] initWithIdentifier:@"extrusions" source:streetsSource];
    fillExtrusionLayer.sourceLayerIdentifier = @"building";
    fillExtrusionLayer.fillExtrusionColor = [MGLStyleValue valueWithRawValue:[NSColor blueColor]];
    fillExtrusionLayer.fillExtrusionHeight = [MGLStyleValue valueWithInterpolationMode:MGLInterpolationModeIdentity sourceStops:nil attributeName:@"height" options:nil];
```

When adding with the same vector source type, this issue is present in both fill and fill-extrusion layers, so I think it is an issue with parsing new buckets on cached tiles when using runtime styling:
![image](https://cloud.githubusercontent.com/assets/3170312/25923389/24f9833a-3592-11e7-84c2-b7f6a4beda60.png)

**Comment by jfirebaugh** [comment]
I first assumed this must be a regression, probably a recent one, but... I went back as far as the iOS 3.4.0 release (first release with runtime styling), and the bug is reproducible there. So surprisingly I think this has never worked -- addLayer needs to trigger redoing layout of the tiles from its source, and it never has. :man_facepalming:
