### ISSUE TITLE
custom layer .so shipped within .aar library

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8878]
An user reached out about a recent change in the amount of `.so` files we ship within our `.aar` library. It seems that with the Android Studio integration we are now building and shipping a custom layer example directly in the SDK while we used to only build this in the test application. This currently results in adding 4 MB to APK of the end developer.

cc @kkaefer @ivovandongen

**Comment by kkaefer** [comment]
We've previously built both of them as well, but only had a copy step for one of them. We could change our Gradle script to only include the example layer when building the Debug library, but not Release.

**Comment by tobrun** [comment]
Thank you for the pointers @kkaefer, PR in #8885.
