### ISSUE TITLE
Ocean polygon fill broken on Nexus 7

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#888]
I get his on my Nexus 7:
![device-2015-02-16-192639](https://cloud.githubusercontent.com/assets/1215089/6222911/c198a61a-b611-11e4-88bd-4a8f69ea64cf.png)

It is noticeable slower. I think it might be due to assuming a GL shader feature which is not available on this simpler GPU.

/cc @ansis

**Comment by ansis** [comment]
does https://github.com/mapbox/mapbox-gl-native/pull/843 fix this?

**Comment by incanus** [comment]
Yeah, I would assume this is a sprite/pattern fill issue.

**Comment by ansis** [comment]
@ljbade I'll assume this is fixed. Re-open if it isn't.
