### ISSUE TITLE
Enforce gl-js submodule pin rules

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#8895]
We should have a gl-native build bot that fails the build* if the gl-js submodule pin does not point to gl-js `master` or an ancestor thereof. This would prevent premature merges of gl-native PRs that update the pin (merging the gl-native PR before the gl-js PR has been merged, or forgetting to update the pin after a non-fast-forward gl-js merge).

\* Or perhaps just declines to report a build status, leaving it in the yellow "pending" state rather than the red "failed" state.

**Comment by tobrun** [comment]
@1ec5 has pointed me to [Danger](https://github.com/danger/danger) for another use-case, the functionality exposed there seems to match the enforcing requirements from above.

**Comment by asheemmamoowala** [comment]
Fixed in #9014
