### ISSUE TITLE
AnnotationView's reuseIdentifier is not working

### ISSUE THREAD

**Issue by hoangelec** [mapbox/mapbox-gl-native#8904]
**Platform: IOS 9
**Mapbox SDK version: 3.5

I have a custom annotation class as below: 

    class MYCustomAnnotation {
    var id:String!
    ... //Custom setup here
    func annotationView() -> MYCustomAnnotationView {
        let annotationView = MYCustomAnnotationView(reuseIdentifier: self.id);//Annotation view will have its identifier as the annotation's id
        return annotationView
    }
    
    func annotationView(fromMap mapView:MGLMapView) -> MYCustomAnnotationView {
        let reuseView = mapView.dequeueReusableAnnotationView(withIdentifier: self.id);//Always get nil here
        if let sReuseView = reuseView as? MYDriverAnnotationView {
            return sReuseView
        } else {
            return self.annotationView();
        }
    }
    }

And here's my viewForAnnotation method in the delegate class: 

    func mapView(_ mapView: MGLMapView, viewFor annotation: MGLAnnotation) -> MGLAnnotationView? {
            if annotation is MYCustomAnnotation {
                let driver = annotation as! MYCustomAnnotation;
                return driver.annotationView(fromMap: mapView);
            } else {
                return nil;
            }
        }

In the code above, each annotationView object will have its reuseIdentifer being equals to it's annotation object's id. And in my delegate's code, I want to reuse the annotationView that has been added to the map. However I always get a nil value at mapView.dequeueReusableAnnotationView(), and as a result, new annotations views are always created each time I add an annotation to my map. 

Can you check please? 

Thank you in advance.

**Comment by ThiyagarajanShivSankaran** [comment]
@hoangelec does this issue resolved for you? For me it's still exists!!!.
I am using **Mapbox SDK version: 3.6.4**.

**Comment by hoangelec** [comment]
@ThiyagarajanShivSankaran I haven't updated my app to the latest version yet. But in my case, I eventually implemented my own reuse mechanism instead of using Mapbox's APIs. 
Sorry for the late reply.

**Comment by ThiyagarajanShivSankaran** [comment]
@hoangelec Oh Okay. Thank you for your reply.

**Comment by hernangonzalez** [comment]
Hi, 
I am not seeing any reuse of the annotations views. They keep building up, no matter zoom or amount.
Thanks,
H.

**Comment by danomatika** [comment]
I'm also seeing this issue using version 4.5.0.

**Comment by danomatika** [comment]
It seems our issue was related to returning dummy AnnotatationViews in certain instances. Returning nil for this case fixes the issue we're seeing.

**Comment by Shockah** [comment]
I'm still having this issue. Removing all annotations and adding them back causes all my MGLAnnotationViews objects to be deallocated and created back. I'm using only one reuse identifier for all of them.

**Comment by Shockah** [comment]
Confirmed annotations views are not reused and are deinitialized on versions 5.5, 5.6.1 and 5.7.0-beta.1.

**Comment by hernangonzalez** [comment]
I don't understand why this would be let closed.

**Comment by raass-claat** [comment]
Any updates on this?

**Comment by Matejy** [comment]
Issue persist to this day.
