### ISSUE TITLE
Crash on Android 2 phone

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#891]
Just tested on my old LG phone and got a crash:
```
02-17 16:47:04.249    1566-6696/? I/ActivityManager﹕ Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.mapbox.mapboxgl.testapp/.MainActivity } from pid 1673
02-17 16:47:04.309    1566-1691/? I/ActivityManager﹕ Start proc com.mapbox.mapboxgl.testapp for activity com.mapbox.mapboxgl.testapp/.MainActivity: pid=7290 uid=10000 gids={3003}
02-17 16:47:04.479    7290-7290/com.mapbox.mapboxgl.testapp W/dalvikvm﹕ VFY: unable to resolve virtual method 11814: Landroid/widget/ImageView;.setRotation (F)V
02-17 16:47:04.539    7290-7290/com.mapbox.mapboxgl.testapp V/MainActivity﹕ <!>com.mapbox.mapboxgl.testapp.MainActivity 78<!> onCreate
02-17 16:47:04.649    7290-7290/com.mapbox.mapboxgl.testapp W/dalvikvm﹕ VFY: unable to resolve virtual method 11414: Landroid/view/ViewGroup;.onRtlPropertiesChanged (I)V
02-17 16:47:04.669    7290-7290/com.mapbox.mapboxgl.testapp W/dalvikvm﹕ VFY: unable to resolve virtual method 369: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
02-17 16:47:04.669    7290-7290/com.mapbox.mapboxgl.testapp W/dalvikvm﹕ VFY: unable to resolve virtual method 391: Landroid/content/res/TypedArray;.getType (I)I
02-17 16:47:04.699    7290-7290/com.mapbox.mapboxgl.testapp W/dalvikvm﹕ VFY: unable to resolve virtual method 9795: Landroid/support/v7/internal/widget/TintSpinner;.setPopupBackgroundDrawable (Landroid/graphics/drawable/Drawable;)V
02-17 16:47:04.699    7290-7290/com.mapbox.mapboxgl.testapp E/dalvikvm﹕ Could not find class 'android.widget.ListPopupWindow', referenced from method android.support.v7.internal.widget.TintSpinner.setPopupBackgroundDrawableV11
02-17 16:47:04.699    7290-7290/com.mapbox.mapboxgl.testapp W/dalvikvm﹕ VFY: unable to resolve instanceof 1439 (Landroid/widget/ListPopupWindow;) in Landroid/support/v7/internal/widget/TintSpinner;
02-17 16:47:04.709    7290-7290/com.mapbox.mapboxgl.testapp V/MapFragment﹕ <!>com.mapbox.mapboxgl.testapp.MapFragment 40<!> onCreateView
02-17 16:47:04.739    7290-7290/com.mapbox.mapboxgl.testapp W/dalvikvm﹕ VFY: unable to resolve virtual method 11143: Landroid/view/SurfaceView;.onGenericMotionEvent (Landroid/view/MotionEvent;)Z
02-17 16:47:04.739    7290-7290/com.mapbox.mapboxgl.testapp W/dalvikvm﹕ VFY: unable to resolve virtual method 11100: Landroid/view/MotionEvent;.getAxisValue (I)F
02-17 16:47:04.739    7290-7290/com.mapbox.mapboxgl.testapp W/dalvikvm﹕ VFY: unable to resolve virtual method 11143: Landroid/view/SurfaceView;.onGenericMotionEvent (Landroid/view/MotionEvent;)Z
02-17 16:47:04.739    7290-7290/com.mapbox.mapboxgl.testapp W/dalvikvm﹕ VFY: unable to resolve virtual method 11144: Landroid/view/SurfaceView;.onHoverEvent (Landroid/view/MotionEvent;)Z
02-17 16:47:04.739    7290-7290/com.mapbox.mapboxgl.testapp W/dalvikvm﹕ VFY: unable to resolve virtual method 11101: Landroid/view/MotionEvent;.getButtonState ()I
02-17 16:47:04.749    7290-7290/com.mapbox.mapboxgl.testapp V/MapView﹕ <!>com.mapbox.mapboxgl.views.MapView 132<!> initialize
02-17 16:47:04.809    1566-1760/? I/ActivityManager﹕ Process com.mapbox.mapboxgl.testapp (pid 7290) has died.
```

**Comment by bleege** [comment]
What version of Android is the LG phone running?

**Comment by ljbade** [comment]
2.3.3

**Comment by ljbade** [comment]
Seems to be this line:
`02-27 09:30:30.329  11471-11471/com.mapbox.mapboxgl.testapp E/dalvikvm﹕ Could not find class 'android.widget.ListPopupWindow', referenced from method android.support.v7.internal.widget.TintSpinner.setPopupBackgroundDrawableV11`

**Comment by bleege** [comment]
Confirmed that `ListPopupWindow` is android-support-v7-appcompat.jar.  It's package is `android/support/v7/widget/ListPopupWindow` though and not `android.widget.ListPopupWindow`.  Wonder if it's bad reference / bug from `android.support.v7.internal.widget.TintSpinner.setPopupBackgroundDrawableV11`?

**Comment by ljbade** [comment]
I will file a bug with Google and see what they say.

**Comment by bleege** [comment]
@ljbade I *think* I found the source code for this class, but it [looks like it should be protected from calling this](https://github.com/android/platform_frameworks_support/blob/master/v7/appcompat/src/android/support/v7/internal/widget/TintSpinner.java#L53) on anything lower than API 16.

That said, I see that the GLTestApp still had a minimum of API 14 on it?  Did you just switch it out to test with?

**Comment by ljbade** [comment]
OK I determined that was a red herring.

A sample app I made with the spinner spits out same message to the console but does not crash.

After looking more carefully there is an error message logged to the system (not under our app's filter) that the process died/terminated. I assume this is from a native crash.

Unfortunately it appears Android 2 does not dump the native stack trace to the console to the log. So it is impossible to know what caused the crash. Only hunch I have is that it is in the `JNI_OnLoad` function because it crashes before it calls `nativeCreate`.

I tried to get `gdb` working but kept running into a problem with `adb shell run-as` not finding the installed package. It looks like from Google that run-as in Android 2 had a few bugs so I could be hitting one of them.

**Comment by ljbade** [comment]
This trick might work: http://stackoverflow.com/questions/17219906/run-as-package-a-b-c-is-unknown-galaxy-s4-jellybean-or-android-4-3

**Comment by bleege** [comment]
Give it a shot / kick the tires, but don't spend too much time on it.  I get a little nervous when things like this are bolted on at the last minute for edge cases.

**Comment by ljbade** [comment]
@bleege I plan to only use it locally to find the crash, not something that I will commit

**Comment by ljbade** [comment]
After #934 we no longer supporting old phones.
