### ISSUE TITLE
iosapp link time is extremely high and question on info.plist (iosapp)

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#8914]
**Platform:**
iOS
**Mapbox SDK version:**
Master
### Steps to trigger behavior

Can someone please clarify the following regarding the iosapp?

1. The link time for iosapp is extreeemely high. Is there someway to reduce it or is there any other target that I should be building instead of iosapp? (It used to be super fast long time back).
The loooong link time makes it difficult to play/experiment since even a tiny change incurs a long link time.

2. The Info.plist makes an exception for stamen.com.  Is this intentional? 

https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/app/Info.plist

 

### Expected behavior

1. Link time should be average/low.

### Actual behavior

1. Link time is very high.

**Comment by 1ec5** [comment]
> The Info.plist makes an exception for stamen.com. Is this intentional?

Yes, it appears to be [used by an MGLRasterSource demonstration](https://github.com/mapbox/mapbox-gl-native/blob/8eb23cbac8a6c5821dc5935e27689700216c3f1a/platform/ios/app/MBXViewController.m#L1264).

**Comment by friedbunny** [comment]
The loooooong link time came about with Xcode 8.3 — compiling/linking with Xcode 8.2 on current master does not suffer from this issue.

**Comment by mb12** [comment]
My Xcode version is this. Should I upgrade to 8.2?
Version 8.1 (8B62)

**Comment by friedbunny** [comment]
@mb12 Interesting that you’re seeing the issue with 8.1, it’d be a useful datapoint to see what happens when you update.

**Comment by mb12** [comment]
Hopefully it doesn't require OS upgrade. I installed 8.1  (instead of latest 8.3.2)  because the latest version required OS upgrade as well.  (Luckily MacOS allows multiple xcode installs).

**Comment by friedbunny** [comment]
While link times can still be somewhat long, they’ve ceased to be an unusual annoyance. Hopefully Xcode’s linker will continue to see improvements.
