### ISSUE TITLE
Use GridIndex instead of boost rtree for symbol placement.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#8915]
**Platform:**
All
**Mapbox SDK version:**
Master

### Steps to trigger behavior

GL  Native is still using rtree for symbol placement. We should switch to GridIndex instead of rtree since its much faster spatial index than rtree. GL JS uses GridIndex for symbol placement.

https://github.com/mapbox/mapbox-gl-native/blob/e7778509c546f4d1e0dd73e2d1deceb146c90de2/src/mbgl/text/collision_tile.cpp#L90 

### Expected behavior

All references to boost rtree should be removed.

### Actual behavior

rtree is still being used in performance critical symbol placement code.

**Comment by jfirebaugh** [comment]
For reference, here's the gl-js commit making the switch (detailed rationale in the commit comment): https://github.com/mapbox/mapbox-gl-js/commit/b62895ab809b46a0341b943c29448dd5de788824

**Comment by ChrisLoer** [comment]
#10103 currently uses rtree for the new collision detection work, but the speed of the index will become even more performance critical, so we will probably end up looking more closely at whether rtree still makes sense.

/cc @ansis

**Comment by ChrisLoer** [comment]
PR #10436 (merging soon) switches from rtree to GridIndex. We never actually profiled rtree vs GridIndex in isolation.
