### ISSUE TITLE
Native crashes in /data/app/com.example.app-1/lib/arm64/libmapbox-gl.so

### ISSUE THREAD

**Issue by MariusBoepple** [mapbox/mapbox-gl-native#8916]
**Platform:** Android
**Mapbox SDK version:** `5.0.2`

We have a few native crashes caused by Mapbox. There is only a small number in the Play Console (6 in the last week) but the real number of crashes is much higher since only very few users report the crashes.

We're using Realm in our app, too (see https://github.com/mapbox/mapbox-gl-native/issues/8000).

Related: https://github.com/mapbox/mapbox-gl-native/issues/3128

Here are the stack traces:

First one:

    *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'samsung/hero2ltexx/hero2lte:7.0/NRD90M/G935FXXU1DQBX:user/release-keys'
    Revision: '9'
    ABI: 'arm64'
    pid: 30350, tid: 30350, name: example.app  >>> com.example.app <<<
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x922ebbcc67
    x0   000000922ebbcb9f  x1   0000007a4715d800  x2   0000000000000000  x3   
    0000007a470f0e00
    x4   0000007a470365a0  x5   0000007a5b5bc25a  x6   0000007a7d60c708  x7   
    0000007a3aa16c80
    x8   000000922ebbcb9f  x9   0000000000000000  x10  000000000000fffa  x11  
    00000000000000ff
    x12  000000000e48e570  x13  00000000f1b71a90  x14  0000007a3aa7a700  x15  0000000000000000
    x16  0000007a50c8c9d8  x17  0000007a8083c9c4  x18  0000000000ffffeb  x19  
    000000922ebbcb9f
    x20  0000007a3aadf008  x21  a7838147a30424a2  x22  0000007a470365a0  x23  
    0000007a3aadf118
    x24  0000007a3aadf160  x25  a7838147a30424a2  x26  a7838147a30424a2  x27  
    0000000000000000
    x28  0000000000000000  x29  0000007ffa6d5cf0  x30  0000007a507cf0fc
    sp   0000007ffa6d5ca0  pc   0000007a507ed638  pstate 0000000020000000

    backtrace:
        #00 pc 00000000000d4638  /data/app/com.example.app-1/lib/arm64/libmapbox-gl.so
        #01 pc 00000000000b60f8  /data/app/com.example.app-1/lib/arm64/libmapbox-gl.so
        #02 pc 00000000000acaa4  /data/app/com.example.app-1/lib/arm64/libmapbox-gl.so
        #03 pc 000000000007b4f4  /data/app/com.example.app-1/lib/arm64/libmapbox-gl.so
        #04 pc 0000000000086a54  /data/app/com.example.app-1/lib/arm64/libmapbox-gl.so
        #05 pc 000000000118d5b0  /data/app/com.example.app-1/oat/arm64/base.odex (offset 0xf80000)

Second one:

    *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'samsung/hero2ltexx/hero2lte:7.0/NRD90M/G935FXXU1DQBX:user/release-keys'
    Revision: '9'
    ABI: 'arm64'
    pid: 14402, tid: 14402, name: example.app  >>> com.example.app <<<
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x31e9c5d58134
    x0   000031e9c5d5806c  x1   00000072a61e4c00  x2   0000000000000000  x3       00000072b3e9ddc0
    x4   00000072b3e904a0  x5   00000072c414c25a  x6   00000072e640d5e8  x7       0000000000000000
    x8   000031e9c5d5806c  x9   0000000000000000  x10  000000000000fffa  x11  00000000000000ff
    x12  000000000b893f10  x13  00000000f476c0f0  x14  00000072b3f1da00  x15  0000000000000000
    x16  00000072b93f59d8  x17  00000072e870c9c4  x18  0000000000ffffeb  x19  000031e9c5d5806c
    x20  00000072b3741c08  x21  e424b326f3124e10  x22  00000072b3e904a0  x23  00000072b3741d18
    x24  00000072b3741d60  x25  e424b326f3124e10  x26  e424b326f3124e10  x27  0000000000000000
    x28  0000000000000000  x29  0000007fcec85d70  x30  00000072b8f380fc
    sp   0000007fcec85d20  pc   00000072b8f56638  pstate 0000000020000000

    backtrace:
        #00 pc 00000000000d4638  /data/app/com.example.app-1/lib/arm64/libmapbox-gl.so
        #01 pc 00000000000b60f8  /data/app/com.example.app-1/lib/arm64/libmapbox-gl.so
        #02 pc 00000000000acaa4  /data/app/com.example.app-1/lib/arm64/libmapbox-gl.so
        #03 pc 000000000007b4f4  /data/app/com.example.app-1/lib/arm64/libmapbox-gl.so
        #04 pc 0000000000086a54  /data/app/com.example.app-1/lib/arm64/libmapbox-gl.so
        #05 pc 00000000011891a0  /data/app/com.example.app-1/oat/arm64/base.odex (offset 0xf7e000)

Third one:

    *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'samsung/hero2ltexx/hero2lte:7.0/NRD90M/G935FXXU1DQBX:user/release-keys'
    Revision: '9'
    ABI: 'arm64'
    pid: 6522, tid: 6522, name: example.app  >>> com.example.app <<<
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x264a573cf1c5
    x0   0000264a573cf0fd  x1   000000726efd3000  x2   0000000000000000  x3       00000072b01f4e40
    x4   000000726ee3ad20  x5   00000072c419325a  x6   00000072e640c708  x7       00000072a5d9c780
    x8   0000264a573cf0fd  x9   0000000000000000  x10  000000000000fffa  x11      00000000000000ff
    x12  000000000c2efe90  x13  00000000f3d10170  x14  0000007299b4f800  x15      0000000000000000
    x16  00000072b98639d8  x17  00000072e870c9c4  x18  0000000000ffffeb  x19      0000264a573cf0fd
    x20  00000072a609f408  x21  e424b326f3124e10  x22  000000726ee3ad20  x23      00000072a609f518
    x24  00000072a609f560  x25  e424b326f3124e10  x26  e424b326f3124e10  x27      0000000000000000
    x28  0000000000000000  x29  0000007fcec85d70  x30  00000072b93a60fc
    sp   0000007fcec85d20  pc   00000072b93c4638  pstate 0000000020000000

    backtrace:
        #00 pc 00000000000d4638  /data/app/com.example.app-1/lib/arm64/libmapbox-gl.so
        #01 pc 00000000000b60f8  /data/app/com.example.app-1/lib/arm64/libmapbox-gl.so
        #02 pc 00000000000acaa4  /data/app/com.example.app-1/lib/arm64/libmapbox-gl.so
        #03 pc 000000000007b4f4  /data/app/com.example.app-1/lib/arm64/libmapbox-gl.so
        #04 pc 0000000000086a54  /data/app/com.example.app-1/lib/arm64/libmapbox-gl.so
        #05 pc 0000000001159b60  /data/app/com.example.app-1/oat/arm64/base.odex (offset 0xf69000)

**Comment by tobrun** [comment]
@MariusBoepple thank you for the report. Do you have some additional information around these crashes? the stacktraces shown above aren't symbolicated and thus aren't showing any actionable information (eg. line numbers and files).

**Comment by MariusBoepple** [comment]
We do not use any obfuscation at the moment (the stacktraces of other crashes aren't obfuscated). So that's not on our side. For me, this seems to be an underlying problem - maybe something with the ABIs (like the other issues indicate)?

**Comment by jfirebaugh** [comment]
Unfortunately there's no actionable information in these stack traces and realistically there's nothing we can do without additional information. However, if you have a way to reproduce this crash, please let us know.
