### ISSUE TITLE
Crash using Mapbox SDK-debug.arr android-arm-v7

### ISSUE THREAD

**Issue by javi2491** [mapbox/mapbox-gl-native#8923]
Generate an Android Mapbox SDK-debug.arr with android-armv7 architecture and sometimes when I start the application this causes crash. Help.
 
`mapbox-gl-native-android-v5.1.0-beta1/src/mbgl/util/tile_cover.cpp:159: std::vector<UnwrappedTileID> mbgl::util::tileCover(const mbgl::TransformState &, int32_t): assertion "state.valid()" failed`

**Platform:**
  Android 5.0
**Mapbox SDK version:**
  mapbox-gl-native-android-v5.1.0-beta1 -arm-v7

**Comment by tobrun** [comment]
@javi2491 we haven't seen this issue locally or on CI. Do you have a minimal example to reproduce? Are you seeing this issue with a fresh clone of this repository?

**Comment by ragaisis** [comment]
I can reproduce this crash if I zoom in as far as i could, then press back (Android application is closed). Then application is launched again by pressing launcher icon and *BAM* crash. 

```
06-27 15:19:15.812 14312-14312/com.our.app A/libc: /Users/jonas/Projects/mapbox-gl-native/src/mbgl/util/tile_cover.cpp:159: std::vector<UnwrappedTileID> mbgl::util::tileCover(const mbgl::TransformState &, int32_t): assertion "state.valid()" failed
06-27 15:19:15.812 14312-14312/com.our.app A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 14312 (takeskus.loisto)
```
