### ISSUE TITLE
Crash at startup in linb::any

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-gl-native#8927]
Seeing a startup crash using the macos app at e34d8b5.

To replicate:

  - Build the macos app `make xproj` and the run the app in xcode
  - Start the app, then stop the app, then start again

I'm seeing the app crash immediately at startup about 1 of 10 times I open the app.

The crash is not always the same. I captured 2 different backtraces:

 - https://gist.github.com/springmeyer/da5192c05e23a81522ab769f4eff007d
 - https://gist.github.com/springmeyer/c232500ff4493e3255c3b742c51800d4

Looks like this may be related to #8626

**Platform:**

OS X 10.12.4

**Comment by jfirebaugh** [comment]
I'm unable to reproduce this. Launched macos app ~50 times; no crashes. @springmeyer are you able to reproduce this with a clean build?

**Comment by springmeyer** [comment]
Thanks for trying @jfirebaugh - I also cannot reproduce now with a clean build. Closing, sorry for the noise.
