### ISSUE TITLE
TileCache::get resulting in too many cache misses and eviction even when its almost empty.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#8928]
**Platform:**
iOS and Android
**Mapbox SDK version:**
Master and v3.5.2

### Steps to trigger behavior

Currently TileCache::get also evicts tile from the cache everytime there is a cache hit. This results in too many redundant layout calls even though the cache is large enough to have avoided it. Its easy to reproduce these cache misses for a simple back and forth panning scenario. With tile boundaries turned on move a tile back and out of the viewport (<-----> ).

Here is one session with printfs.
```
With a cache size of 30,  the subsequent redoLayouts are not needed.

redoLayout 3/0/2=>3
redoLayout 3/1/1=>3
redoLayout 3/0/1=>3
redoLayout 3/2/2=>3
redoLayout 3/2/1=>3
ADD_TO_CACHE: 3/2/1=>3
ADD_TO_CACHE: 3/2/2=>3
CACHE_HIT_AND_REMOVE: 3/2/2=>3
CACHE_HIT_AND_REMOVE: 3/2/1=>3
redoLayout 3/2/2=>3<====== THIS SHOULD HAVE BEEN A HIT
redoLayout 3/2/1=>3<====== THIS SHOULD HAVE BEEN A HIT 
ADD_TO_CACHE: 3/2/1=>3
ADD_TO_CACHE: 3/2/2=>3
```

### Expected behavior

TileCache should not evict Tiles/buckets when its more than 90% empty.

### Actual behavior

TileCache is evicting tiles even when its almost empty.

**Comment by jfirebaugh** [comment]
I think you might be misreading the code. `TileCache::get` _moves_ a tile from the cache into the active state. When the tile is no longer used, it's transferred back to the cache. Also, `renderTiles` is by nature a transient data structure -- it doesn't contain data that's expensive to regenerate.

**Comment by mb12** [comment]
@jfirebaugh  Can you please re-review this code?

When tiles are no longer used, they are  *not* being moved back to the cache _in all the cases_ (see the specific scenarios I've identified above).  TileCache contains tiles that are complete/whose buckets are fully laid out.  Simple panning/zoom should not cause relayout of tiles that were recently used.

This bug causes intermittent/noticeable disappearing of symbols (glyphs as well as icons) when one zooms/pans because of unnecessary calls to redoLayouts which should have been cached.  This bug is responsible for the *blinking* of symbols when one zooms in/pans.

**Comment by jfirebaugh** [comment]
@mb12 We know what causes the symbol blinking -- it's not cache eviction. https://github.com/mapbox/mapbox-gl-native/issues/7026

**Comment by mb12** [comment]
@jfirebaugh  Can you please  confirm that the following is the expected behavior of the cache?  I've re-verified that tiles are being re-bucketed for a scenario like the one below.  

Tiles are being re-laid out for a trivial pan scenario that moves them back and forth into and out of the viewport like this (<-->) with no change in map state (zoom, pitch or angle). 

================================

If I am correct the "previously-rendered symbol data" is missing because of this cache bug, resulting in flickering behavior  in https://github.com/mapbox/mapbox-gl-native/issues/7026.

> The general principle is: continue rendering previously-rendered symbol data for a tile until such time as the tile can be fully covered by ideal tiles with ready-to-render symbol data.

**Comment by jfirebaugh** [comment]
Are you talking about annotation tiles? That's the one scenario where the behavior you describe is expected. I'm not observing that behavior for any other source type.
