### ISSUE TITLE
merge GeoJSON vector tiles work

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#893]
Picking up from https://github.com/mapbox/mapbox-gl-native/issues/507#issuecomment-69076871, we'll need to merge the `geojsonvt` branch, which will require it interfacing better with the library. 

* [x] match vector tile object structure with main library
* [x] allow for live reindexing when features are added/removed
* [x] handle non-GeoJSON (in-memory features)
* [x] nailing some hopefully-basic performance kinks
* [ ] `MultiGeometry` support
* [x] other API merging (e.g. `LatLng` struct)
* [x] figuring out how independent of or reliant on GL we want the library to be

/cc @mourner @1ec5

**Comment by incanus** [comment]
The library consists of [`geojsonvt.hpp`](https://github.com/mapbox/mapbox-gl-native/blob/a9cf3ffb6a88aca56ecdc838a1513557af069058/include/mbgl/util/geojsonvt.hpp) and [`geojsonvt.cpp`](https://github.com/mapbox/mapbox-gl-native/blob/a9cf3ffb6a88aca56ecdc838a1513557af069058/src/mbgl/util/geojsonvt.cpp).

**Comment by incanus** [comment]
@kkaefer @mourner Do you guys think this should be a part of GL itself, or should we try to keep it a separate library for general use of geo data `->` vector tiles?

**Comment by mourner** [comment]
@incanus it would be nice to have it as a separate library — easier to maintain this way, with separate tests etc. It could also grow into a useful standalone tool.

**Comment by incanus** [comment]
Related to https://github.com/mapbox/mapbox-gl-native/issues/904, we can't subclass `Source` to make e.g. a `LiveSource` (my first approach), so instead I am thinking: 

* Use `Source`, possibly with manually-created or passed `SourceInfo` related to the data (GeoJSON or other) setup. 
* Adapt `Source::addTile()` to handle `SourceType:GeoJSON` (currently unimplemented) as a first measure. 
* Above relies on a new `GeoJSONTileData` class which works similar to `VectorTileData`, but which pulls tiles from the `GeoJSONVT` structure. 
* A `Source` initialized in this way (perhaps with passed GeojSON) would async run the `GeoJSONVT` clipping & splitting algorithm upon creation so that it would be ready for these tile queries. This shouldn't take long, but maybe it will block `addTile()` calls until it's done?

**Comment by incanus** [comment]
FYI above I was speaking of GeoJSON only because that's what `GeoJSONVT` currently takes (a GeoJSON string) in its conversion, but ideally GL will go right at this conversion regardless of the format or of runtime-added features. We don't really care about GeoJSON file support right now in the iOS beta.

**Comment by incanus** [comment]
Current status: as of 988e64e04df84e3a00c9e7be01c05d1dd2b845b8, I have some semblance of an ever-present annotations layer atop the style layers, which generates tile coverage properly. Then, instead of kicking off async web loads for tile data, it queries a passes `GeoJSONVT` object. I can pan and zoom and observe the proper tiles being requested out of the object, including it auto-drilling down to slice up the GeoJSON. 

Next steps, roughly: 

* Bridge the `GeoJSONVT` `Tile` and `TileFeature` format into `VectorTileData` that we can render. 
* Cut my sample GeoJSON (or any passed GeoJSON, for that matter) out for now. 
* Write an API to expose direct writes/conversions into `Tile` and `TileFeature`.

**Comment by incanus** [comment]
Still making slow progress here. Current structure is a `LiveTileData` peer to `VectorTileData` & `RasterTileData`, which will support programmatic annotation adding as well as (eventually) GeoJSON file retrieval/parsing. Just as `VectorTileData` passes to `TileParser`, `LiveTileData` passes to `LiveTileParser`, which will get refactored using large parts of `TileParser` such as render bucket creation, but first I'm just getting through the functionality.

**Comment by incanus** [comment]
As of 645aeda I'm getting things to render a bit. 

![screen shot 2015-02-25 at 1 13 13 pm](https://cloud.githubusercontent.com/assets/17722/6380670/381f9732-bcf0-11e4-9da2-9406c8a5c67a.png)

**Comment by incanus** [comment]
Next up is some careful looking into the `GeoJSONVT` library and my use of move/copy and references. I got to the bottom of an issue that was causing modification to throwaway stack variables and thus losing fidelity. So... back to the porting drawing board a bit for some cleanups, then: 

* Get all shapes to render on first view. 
* Figure out what's causing pieces of PA and all of NJ to not show up (some sort of collision thing). 
* Cut out the hardcoded GeoJSON load and go right at the `GeoJSONVT` conversion routines with live-added data. 
[...]
* Add APIs to stick stuff into said conversion routines. 
* Layer iOS API on top of that plus add API for [currently hardcoded annotation styling](https://github.com/mapbox/mapbox-gl-native/blob/645aeda82037fbdff7e0df9164667deb8ee8fd97/src/mbgl/style/style_parser.cpp#L40-L46). 

That should keep me busy a while longer.

**Comment by incanus** [comment]
> Get all shapes to render on first view.

As of d36caee2a97e0e8a902eee637b22f3ea551744f6 this now works, at least within the limits of: 

> Figure out what's causing pieces of PA and all of NJ to not show up

That's next.

**Comment by incanus** [comment]
>  (some sort of collision thing or possibly actually losing data unintentionally during conversion)

It's the latter, as merely drawing `background` plus the data is no better. 

![screen shot 2015-02-26 at 11 34 07 am](https://cloud.githubusercontent.com/assets/17722/6400055/66c7ebb4-bdab-11e4-8a1c-b31afc26b6da.png)

**Comment by mb12** [comment]
1.) Collision detection happens only for Symbol Buckets (not lines or areas).

2.) If you want render something over all areas, lines and symbols, you would have to make sure that glDepthRange gets called with the right depth range. Painter uses a variable called strata for this.  You may want to review your changes around this area to debug this.

**Comment by incanus** [comment]
Thanks @mb12, I am fresh to this part of the code since much of the collision work so this is a good pointer. Also I think I've determined my problems are with actual geometry conversion, but I'm still digging in. 

I'm super interested in what you are up to with the code base — care to get in touch on my git email or my first name `@mapbox.com`?

**Comment by incanus** [comment]
Currently taking a side trip to work on symbols instead of merely lines, since this is a higher-priority item and everything thus far has been hardcoded for lines at the expense of symbols and fills. 

Longer term, we'll probably have a lines/polygons annotations layer and another, separate points layer dynamically added to the style. On iOS at least, the two groups — points and line/polygon shapes — are each relegated to their own z-ordering, which we'll likely start with. Eventually we can open up more control in the API for intermingling the two, as well as interleaving their component annotations between other layers of the map. 

That is, iOS model / first goal: 

```
— top
-
- annotation points
- annotation shapes
- base map labels
- base map shapes
- background
-
— bottom
```

Eventual goal, for example: 

```
— top
-
- annotation point A
- annotation shape A'
- base map labels
- annotation shape B'
- annotation point B
- base map shapes
- background
-
— bottom
```

**Comment by incanus** [comment]
As I've gotten into this, I've found that there's enough branching logic required to support both vector tiles as current and "live tiles" of annotation data that I'm thinking it makes more sense to adapt all of the live stuff *for* the vector tile construct. 

Right now, vector tiles are (rightly) expected to be created from PBF data, and then the various parsing buckets (fill/line/symbol) are coupled to that format, parsing and interpreting actual vector tile geometry commands individually. 

Instead of adding support for "manual" geometry to the buckets as I have been (where `GeoJSONVT` tiles give us "tiled vector data" in 4096 extents already), I'm thinking of: 

1. Adapting `VectorTile` and friends to provide their geometries to consumers, moving this step-by-step logic out of the parsing buckets. 
1. Allowing instantiating of `VectorTile` objects from `GeoJSONVT` `Tile` objects with `TileFeatures`, which also are 4096 extent-based geometries. 
1. Having the geometry routines  above just relate annotation `Tile` geometries directly behind the same abstraction as for vector tiles. 

This also moves towards a model of GeoJSON or live annotation features existing in multiple layers of one tile, which is how vector tiles work now. That way we can still apply filters to get `FilteredVectorTileLayer` for individual styling of annotations the same as our server data. 

![](http://adsoftheworld.com/sites/default/files/images/noise-cancelling-headphones-construction.jpg)

**Comment by incanus** [comment]
Spinning the tile refactoring out to https://github.com/mapbox/mapbox-gl-native/issues/928 for the next step.

**Comment by incanus** [comment]
#928 is dead! Back to this issue now, interfacing `GeoJSONVT` with `GeometryTile` and friends.

**Comment by incanus** [comment]
As of e5d8b7823240a649e81e521c27c01f0416f7475b we have GeoJSON fetched from local file, parsed in C++, and added as live tiles to a non-hacky rendering infrastructure. 

Next up: figuring out why labels get garbled and not all shapes show up initially. 

Video: https://dl.dropboxusercontent.com/u/575564/garble.mp4

**Comment by incanus** [comment]
Backlog: 

* Garble fix
* Get points to render, not just lines
* Come up with dynamic style layer addition/rearrangement/removal system
  - Layer group within hardcoded style layers
  - Separate layers for each shape overlay (to allow relative (re)ordering
  - Common layer for all point annotations (akin to Maki handling) for proper z-ordering
* API for adding/rearranging/removing annotation layers

**Comment by mb12** [comment]
The garbling in the posted video is similar to this issue. 

https://github.com/mapbox/mapbox-gl-native/issues/832

**Comment by incanus** [comment]
> I've also seen similar garbling when multiple Vector Sources are specified in the same `style.json` file.

`o_O`

**Comment by incanus** [comment]
Garble issue seems to be related to #957 (triggered by multiple vector sources). 

> not all shapes show up initially

This is related to the center-most tile showing up while the others get locked out via the `GeoJSONVT` mutex. 

Points render, but there seems to be a possible porting problem from Swift/JS.

**Comment by incanus** [comment]
Garble issue fixed in https://github.com/mapbox/mapbox-gl-native/pull/995, porting problems fixed in GeoJSONVT. Currently working on a fast subset of GeoJSONVT features for points (not yet shapes) to shore up client > map > annotation manager > source > tile > renderer pipeline.

**Comment by incanus** [comment]
Now going from Objective-C loading of a text file of lat/lngs & adding them inside `MGLMapView.mm`: 

```objc
std::vector<mbgl::LatLng> latLngs;
[...]
mbglMap->addPointAnnotations(latLngs, symbols);
```

To this: 

![anigif-1426433987](https://cloud.githubusercontent.com/assets/17722/6656694/ecb65de6-caee-11e4-8387-f1a7a871fd32.gif)

Keep in mind the glyph scrambling issue is fixed in `master`; I still need to merge.

**Comment by incanus** [comment]
Next steps: 

* [x] Use more realistic sprite image https://github.com/mapbox/mapbox-gl-native/commit/17b9b14379f5ab3b5f77596ec822220c970b83ca
* [ ] Get map to refresh upon addition of annotations without having to change zoom
* [ ] Address annotations in the style object with filter expressions
* [ ] Annotation removal

**Comment by incanus** [comment]
@kkaefer @ljbade Going to do some experimentation, but I'm looking for a good way to refresh the on-screen tiles, ideally only for one source (my annotations pseudo-source). None of the `Map` public methods are ideal, and the only ones which work are a `stop`/`start` sequence and a `setStyleJSON` of the current, unchanged object, but that's too drastic as it blinks and forces a refresh of all tiles. 

Currently looking into adapting an API on `Source` to empty `tiles`/`tile_data` and force a refresh that way.

**Comment by incanus** [comment]
I think something like this: 

```c++
void Source::clearTiles() {
    tiles.clear();
    tile_data.clear();
}
```

Followed by a `map.triggerUpdate()` will work for my needs for annotation tiles. Tiles aren't actually completely cleared but rather are created/stored/deleted by a primary annotation manager which vends them to the annotations `Source` object.

**Comment by incanus** [comment]
So far, pretty promising. 

![anigif-1426466883](https://cloud.githubusercontent.com/assets/17722/6659134/7ffaca46-cb3b-11e4-94a2-1092c056c49e.gif)

**Comment by mb12** [comment]
Just a general comment on clearTile method.
Any method that triggers TileData destructor must be called on the mapThread since it contains GL calls (glDeleteBuffers). 

2.)

**Comment by incanus** [comment]
Great catch, thanks @mb12! That's a subtle detail of the normal `Map::updateTiles()` that I had missed thus far.

**Comment by incanus** [comment]
BTW I'm going with a more conservation tile clearing routine now that only purges tiles affected by a particular annotation update. 

```c++
void Source::invalidateTiles(Map& map, std::vector<Tile::ID>& ids) {
    for (auto& id : ids) {
        tiles.erase(id);
        tile_data.erase(id);
    }
    map.triggerUpdate();
}
```

**Comment by incanus** [comment]
FWIW, the `TileData` destructor only involves `req`, which never exists for my subclass `LiveTileData` used for annotations. 

```c++
TileData::~TileData() {
    if (req) {
        env.cancelRequest(req);
    }
}
```

**Comment by mb12** [comment]
LiveTileData must have at least one "Buffer" object to hold vertex attributes such as position, extrude offsets etc. (For. e.g. VectorTileData has 4 buffer objects - IconVertexBuffer etc.).

**Comment by mb12** [comment]
Xcode debugger is really good at detecting this error (open gl calls across mutliple threads). Just add a breakpoint for open GL errors. 

https://developer.apple.com/library/mac/recipes/xcode_help-breakpoint_navigator/AddinganOpenGLESErrorBreakpoint/AddinganOpenGLESErrorBreakpoint.html

**Comment by incanus** [comment]
> LiveTileData must have at least one "Buffer" object

Cool, yeah it is a subclass and inherits all of the `VectorTileData` vertex buffers, since these live tiles are essentially the same sort of data, just decoded (4096-extent "grid values"). 

> Xcode debugger is really good at detecting this error

Thanks — I'm relatively inexperienced with OpenGL debugging but this will help.

**Comment by incanus** [comment]
Ok, once I figured out what was actually happening for point symbology, this proved to be quite easy in https://github.com/mapbox/mapbox-gl-native/commit/b061404. 

Now we can do this: 

```objc++
BOOL on = NO;

for (...) {
    latLngs.push_back(mbgl::LatLng(lat, lon));
    symbols.push_back((on ? "marker-red" : "marker-24"));
    on = !on;

    sleep(1);

    dispatch_sync(dispatch_get_main_queue(), ^{
        mbglMap->addPointAnnotation(latLngs.back(), symbols.back());
    });
}
```

![anigif-1426538281](https://cloud.githubusercontent.com/assets/17722/6675985/bae34984-cbe1-11e4-990e-c18ab4c995fc.gif)

**Comment by incanus** [comment]
Going to get annotation removal going next, then kick out a separate PR just for point-based annotations to get that merged sooner rather than later. Right now I'm not actually leveraging `GeoJSONVT` (not needed for points; polygon simplification is the real win there) so I'm gonna bring this over iteratively.

**Comment by mourner** [comment]
@incanus btw, I'm working on point filtering in geojson-vt now.

**Comment by incanus** [comment]
Cool, meaning what exactly? I've always thought that to be removing duplicate point dots on the map if sufficiently overlapping, but that involves knowing about the point imagery?

**Comment by mourner** [comment]
@incanus Something along the lines of https://github.com/mapbox/hey/issues/3712. We would not look at imagery, but try to reduce density for lower zoom tiles in places where points are too crowded, so that e.g. if we have 100,000 points, we don't have to render 100,000 on z0. Duplicate points filtering is not sufficient, because it's still potentially `(4096 + 64 * 2) ^ 2` = 17.8 million points.

**Comment by ljbade** [comment]
@mourner Yeah point filtering would be great for performance and allow a developer to throw lots of points at the map without having to worry about the performance impact.

@incanus I think you are on the right track with clearing tiles. You want to be able to say - these tiles are dirty, on next redraw, fetch new ones. That way only the tiles that need to be reloaded will be and it will happen as part of the normal update/render/swap flow.

**Comment by incanus** [comment]
Ok, point annotation removals now work as of https://github.com/mapbox/mapbox-gl-native/commit/e4da705e3c14f0d158dfcdbf16f69415df2ef8fb. That hits everything up in https://github.com/mapbox/mapbox-gl-native/issues/893#issuecomment-81295365, so I think we can say point features are complete.

Time now to clean, tidy up (e.g. https://github.com/mapbox/mapbox-gl-native/commit/fbd55115b2383d0c5a6d057fd3d539bdeb99e12e#commitcomment-10224463), and get a point annotations PR in.

**Comment by incanus** [comment]
Oops, forgot `getAnnotationsInBoundingBox` — doing that first.

**Comment by incanus** [comment]
Done in https://github.com/mapbox/mapbox-gl-native/commit/3ce0fb967374250eef6b67150b494645500125f4. Moving on to cleanup & separate PR for point API.

**Comment by incanus** [comment]
Point annotations PR `->` https://github.com/mapbox/mapbox-gl-native/pull/1018

**Comment by incanus** [comment]
Moving this ticket to the b2 milestone, since the real GeoJSONVT integration involves shapes; points are standalone.

**Comment by incanus** [comment]
For b2, need to port over some improvements from @mourner like https://github.com/mapbox/geojson-vt/commit/6f8295410c1dfb3d6e3a71b1947f74c2089f8792 when we get back to shapes.

**Comment by incanus** [comment]
General note to catch up with `2.0.0` in general when we're back on this: 

https://github.com/mapbox/geojson-vt#200-mar-20-2015

**Comment by incanus** [comment]
Picking up shape annotation work again for b2 in [`shape-annotations`](https://github.com/mapbox/mapbox-gl-native/compare/shape-annotations).

**Comment by incanus** [comment]
```c++
map.addPointAnnotation(mbgl::LatLng(45, -120), "default_marker");

map.addShapeAnnotation({
    mbgl::LatLng(44, -122),
    mbgl::LatLng(46, -122),
    mbgl::LatLng(46, -121),
    mbgl::LatLng(44, -122)
});
```

![screen shot 2015-05-22 at 4 31 46 pm](https://cloud.githubusercontent.com/assets/17722/7781260/3feb9d82-00a0-11e5-8273-22164a7ae49c.png)

**Comment by picciano** [comment]
pretty sweet! does that work with lines as well as closed shapes?

**Comment by incanus** [comment]
Yep, though still working through a fair number of issues. It’s looking like the first cut will support either open shapes with a variable-width border, closed shapes with a fill color and an optional, but fixed-width, border, and possibly cutout holes in closed shapes.

**Comment by incanus** [comment]
Currently working on multiple layers, styling, and laying foundation for relative ordering. 

Just to brain dump: 

* For points, we use one style layer which is added post-parse and contains all points when added/removed at runtime. Points are individually styled by passing their sprite image association in the `{sprite}` property, just as we do for map style POIs. 

* For shapes, each annotation will need its own layer in the style. This is for two reasons: 
  1. Each shape can be independently styled (stroke, color, alpha, etc.). 
  1. Shape layers can be ordered and reordered at runtime. 

  Passing styling properties in the annotation proprieties like we do with points won't work as-is since we don't parse tokens out of properties the same way we do in the symbol bucket. 

  This also means that we need to modify the style each time the client adds or removes a shape layer. I _think_ this will render alright (i.e. not flicker the basemap) since we're only modifying and invalidating the annotations layer tiles (fast `LiveTile`'s with no network component). 

/cc @jfirebaugh @kkaefer @ansis

**Comment by incanus** [comment]
Another approach, an alternative to each shape having a layer in the style, is to put all shapes in a single style layer like we do with points, make line and fill buckets parse out their `properties` for styling (modifying the `StyleLayer` on the fly), and punt relative ordering of shapes to however we will solve https://github.com/mapbox/mapbox-gl-native/issues/988, i.e. probably do it in the shaders?

**Comment by jfirebaugh** [comment]
> make line and fill buckets parse out their properties for styling 

That's a huge push, outlined in https://github.com/mapbox/mapbox-gl-style-spec/issues/249.

**Comment by incanus** [comment]
I was seeing it in terms of annotation layers only, but I see how this should be made generic and how it plays with data-driven styles now. Thanks for the reminder.

**Comment by incanus** [comment]
Shape work PR coming into place: https://github.com/mapbox/mapbox-gl-native/pull/1655

**Comment by incanus** [comment]
Shapes are just about set for b2, so I'm back looking into this ticket's branch ([`geojsonvt`](https://github.com/mapbox/mapbox-gl-native/tree/geojsonvt)) for shape simplification.

**Comment by incanus** [comment]
#1655 supersedes this now that GeoJSONVT as the underpinning of shape annotations has landed there.
