### ISSUE TITLE
Allow direct setting of MGLMapView.camera properties

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#8930]
If we can find a reasonably safe way, we should allow properties such as `MGLMapView.camera.pitch` and friends to be set directly, rather than via a round-about method.

This:
```swift
map.camera = MGLMapCamera(lookingAtCenter: startingCenter, altitude: altitude, heading: 0, pitch: 60)
```
... could become:
```swift
map.camera.pitch = 60
```

/cc @1ec5 @incanus

**Comment by 1ec5** [comment]
Off the top of my head, we could have MGLMapCamera maintain a backpointer to the MGLMapView that created it, or MGLMapView could observe changes to that MGLMapCamera’s properties. With KVO, it would be tricky to remove the observers at the right time.

With either approach, we’d need to figure out what to do when the same MGLMapCamera instance is set on two different MGLMapView’s – say, if the two map views are to be kept in sync. The developer would then expect a change to the camera’s property to affect both map views at the same time.

A third approach would be to use NSNotificationCenter somehow.

**Comment by jmkiley** [comment]
It is currently a little confusing, since you can type `mapView.camera.pitch = 40`, for example, but it doesn't change the pitch. 

It's [documented](https://www.mapbox.com/ios-sdk/api/3.5.4/Classes/MGLMapCamera.html#/c:objc(cs)MGLMapCamera(py)pitch) as being `readwrite`, so we may want to update documentation with how to actually set camera properties.

**Comment by 1ec5** [comment]
> we may want to update documentation with how to actually set camera properties.

I would agree if we intend to keep that behavior. But if we intend to make it possible to set the pitch directly like that, then I guess we’d consider the current behavior to be essentially a bug that isn’t to be documented.

**Comment by 1ec5** [comment]
This will surely exacerbate #3625: developers will attempt to set the center coordinate, heading, and pitch directly on the map view on separate lines, but each successive property write will cancel the previous one.

Essentially, the current behavior makes MGLMapCamera a transactional API, which suits our (hobbled) animation model well.
