### ISSUE TITLE
MapChange events not consistenly invoked

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#8932]
We have been hearing reports about `MapChange` events not been consistently invoked. 

For example when loading the default style, if the developer hasn't specified a style-url, the `DID_FINISH_LOADING_MAP` isn't always invoked. Only if you perform a map transformation afterwards the event will be delivered (eg. zoom/pan).

Another example would be the `DID_FINISH_RENDERING_FRAME_FULLY_RENDERED` event. I have heard about cases where this event isn't invoked and (+ isn't invoked after doing a map transformations).

**Comment by sddamico** [comment]
Seems I had a related issue, I noticed that when upgrading to 5.0 that the `DID_FINISH_LOADING_STYLE` event would not fire after a configuration change (such as rotation) and the same style url as the one that was restored was set on the map view.

**Comment by tobrun** [comment]
With https://github.com/mapbox/mapbox-gl-native/pull/9462, I'm attempting to rewire initialization so that style loading occurs after surface creation. This should resolve the issue from OP, need to validate if the comment from @sddamico is still present.

**Comment by Guardiola31337** [comment]
> need to validate if the use-case from @sddamico is still present.

I've checked ☝️ and now `DID_FINISH_LOADING_STYLE` is fired accordingly after a configuration change. We're good to close here.
#9462 landed and it'll be available in version `5.2.0`. 

Thanks @sddamico for your report. Feel free to open new tickets if you find any other issues 😉

cc/ @tobrun
