### ISSUE TITLE
Sometime Marker flash when change camera

### ISSUE THREAD

**Issue by Buminta** [mapbox/mapbox-gl-native#8933]
**Platform: Android**
**Mapbox SDK version: 5.0.2**

I had a problem with marker view in map.
The first i had some markers view in Mapview. However when i moved mapview, overall markers view would have gone, and re shown after many second!
I think something by when i moved mapview, camera had changed and new vector tiles have loading from server then render tiles for view. Bug markers flash had starting from that!

Everybody can help me?
Thanks so much!

**Comment by tobrun** [comment]
Thank you for the report @Buminta, this issue has been reported already in https://github.com/mapbox/mapbox-gl-native/issues/6762 and was added to the 5.1.0 milestone. Closing as a duplicate.
