### ISSUE TITLE
not hide InfoWindow android

### ISSUE THREAD

**Issue by chandreshandroid** [mapbox/mapbox-gl-native#8935]
**Platform:**
**Mapbox SDK version:**
com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.2

### Steps to trigger behavior

not hide InfoWindow 

i am using this code hide 
Add marker code
  mapboxMap.addMarker(new MarkerOptions()
                        .position(new LatLng(origin.getLatitude(), origin.getLongitude()))

                        .snippet(originTitle));

Hide InfoWindow like this
   map.setOnInfoWindowClickListener(new MapboxMap.OnInfoWindowClickListener() {
                 @Override
                 public boolean onInfoWindowClick(@NonNull Marker marker) {
                     marker.hideInfoWindow();
                     return true;
                 }
             });

### Expected behavior  
it should hide InfowWindow of marker
### Actual behavior
it is not hide infoWindow

**Comment by tobrun** [comment]
Closing it part of the onClick is done by the SDK itself. Return true to keep it open, return false to close it.
