### ISSUE TITLE
popups

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#894]
Popups, callouts, bubbles, whatever you want to call them, we need selection state and info bubbles on markers. 

Per @jfirebaugh (and I agree) we should do these for each platform because they are distinct and need to feel natural to the platform, such as being complex, even animated, views and being able to contain other platform-specific views. 

For this reason, I think we should only worry about this on Android and iOS. 

I've been very happy with [`SMCalloutView`](https://github.com/nfarina/calloutview), which we integrated into our iOS SDK, and I think we should continue to use that here.

**Comment by incanus** [comment]
Also of note is that the performance implications of not doing this in GL core itself will be small. At least on iOS, only one callout is present at a time (single selection) and just simply tracks on the map.

**Comment by ljbade** [comment]
On Android the OS uses GL anyway to render/draw overlaid views so unlikely to be slower then rendering in our GL context.

**Comment by incanus** [comment]
@1ec5 has been starting to look into this, tracking using `CADisplayLink` but going to try @bleege's work on a "region is actively changing" delegate method in iOS.

**Comment by incanus** [comment]
I'm grabbing this now to start on post-point annotations merge (#1021) since gestures, point-in-bounds, and platform-side callouts are all integrated.

**Comment by incanus** [comment]
Annotation selection should work something like this. Note that unlike MapKit, the z-index of the selected marker doesn't change (that's in #991). 

![anigif-1426651756](https://cloud.githubusercontent.com/assets/17722/6702518/f5c40346-cce9-11e4-9636-df4d67015f14.gif)

This is done with something like d53fb94c86773ea45fb6df39c96cfbe161f4aa3e, which just does a dumb `44px` box around the touch for point-in-bounds querying, then iterates selection state through the close-by annotations. It doesn't take marker icon size into account; likely we'll want to make this box a bit larger and emphasize in the top direction. 

This is kind of like JS's `featuresAt()`, since point annotations' tiles work like an R-Tree.

**Comment by incanus** [comment]
Summarizing state of popups. The tough nut to crack here is syncing pan and zoom — *including decelerated coasting* — between native iOS views and the GL view. We've tried this in three branches, with varying combos of `MGLAnnotation` protocol data objects or other placeholder markers. 

* [`877-display-link`](https://github.com/mapbox/mapbox-gl-native/compare/877-display-link) — using `CADisplayLink` callback to sync simple `UIImageView` markers with GL
* [`877-callout`](https://github.com/mapbox/mapbox-gl-native/compare/877-callout) — bringing in `SMCalloutView` popups & updating position of it and `UIImageView` markers using a new `mbgl::MapChangeRegionIsChanging` event coming out of GL
* [`877-point-callout`](https://github.com/mapbox/mapbox-gl-native/compare/877-point-callout) — same as above, but originally merging in GL-side point annotation work (@1ec5 I think we can fold this into the above branch now?)

All have been updated to `master` as of https://github.com/mapbox/mapbox-gl-native/commit/ae7bd9ac6ac12b37da0272ea7d1836f18a78ec10. 

The next approach I'm going to try is, since we're tracking annotations' positions GL-side, have GL update their screen position *values* every frame draw, and have Cocoa read out those values, translate to `CGPoint`, and update on screen. That is, the main difference between all of the above approaches is that we'd have GL update the non-geographic positions itself on frame draw rather than the non-GL parts update them on some sort of (likely delayed and/or not as frequent) callback.

**Comment by 1ec5** [comment]
@incanus Yes, let’s fold 877-point-callout into 877-callout. That’ll make merging for 756-gps-marker easier.

**Comment by incanus** [comment]
Visual syncing is currently blocked by #1026. In the meantime, I'm going to tighten up the annotation model API, get gestures/selection working, and roll a PR.

**Comment by incanus** [comment]
Per chat with @1ec5, we are going to move towards dismissing any active callout for map change events for b1. We'll get back to view syncing post-b1.

**Comment by incanus** [comment]
Point annotations Cocoa API for gestures and selection state is in as of https://github.com/mapbox/mapbox-gl-native/commit/eded1d90aa4fa607bb5bd804a9da2cdc690aa16d. Working on this next to integrate.

**Comment by incanus** [comment]
This last commit ^^ is feeling good on top of my nearly-merged annotation flexing in https://github.com/mapbox/mapbox-gl-native/pull/1061. We are close @1ec5!

**Comment by jfirebaugh** [comment]
Now that we've got a PR for iOS, I'm removing this from the milestone and untagging iOS, but keeping the bug open to track the Android implementation.

**Comment by erf** [comment]
Any idea if this feature is far away? Also curious on the progress for on-annotation-click event for Android.

**Comment by erf** [comment]
Maybe popup view for Android could be based on this -> 
https://github.com/jgilfelt/android-mapviewballoons

**Comment by incanus** [comment]
I am looking into this for Android.

**Comment by erf** [comment]
made a custom popup view pull request. maybe it will help. see #2064

**Comment by bleege** [comment]
Per chat with @incanus this morning we decided that we're going to reuse the Raster SDK's [implementation for InfoWindow](https://github.com/mapbox/mapbox-android-sdk/blob/mb-pages/MapboxAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/InfoWindow.java).  This will give us:

* Battle tested and familiar API for current Mapbox customers
* Existing [Customization Features](https://github.com/mapbox/mapbox-android-sdk/blob/5e783b852a70d186cfd3d05630e68e71354643ce/MapboxAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/android/testapp/CustomMarkerTestFragment.java)

**Comment by ljbade** [comment]
Good idea!

**Comment by bleege** [comment]
Picking popups back up.  Here's a screenshot of the starting point from 54ca9fa78780c947a6bd8041412fb49a759d9702 and a long press on the map.

![device-2015-09-02-140823](https://cloud.githubusercontent.com/assets/989928/9641392/1b6b074a-517c-11e5-8f31-b6e251c05a97.png)

**Comment by bleege** [comment]
Basic InfoWindow to Marker location setup.  Next step is to adjust placement based on InfoWindow size so that the bottom triangle loads from the top of the Marker.

![correct-math](https://cloud.githubusercontent.com/assets/989928/9642497/092640ee-5182-11e5-89f7-7d171f995076.png)

**Comment by incanus** [comment]
@bleege You may find [this](https://github.com/mapbox/mapbox-gl-native/blob/322e1aa2c3c2570554a2fe2bbfa733ab7bbd4e81/include/mbgl/map/map.hpp#L145) and its use in iOS interesting, since marker imagery can change per-annotation.

**Comment by bleege** [comment]
@incanus Thanks for the link.  I was just using LatLng ^^, but [this is more useful](https://github.com/mapbox/mapbox-gl-native/blob/0ff7cf20e971be584410973eb6727e12550604f9/platform/ios/MGLMapView.mm#L2160-L2167).  Off to JNILand to wire it up.

**Comment by incanus** [comment]
Yeah, good luck there.

**Comment by ljbade** [comment]
Let me know if you need any help.

**Comment by bleege** [comment]
Initial port of iOS way to align InfoWindows (on HTC M9).

![device-2015-09-03-135606](https://cloud.githubusercontent.com/assets/989928/9667870/fa027b06-5243-11e5-8996-2066babc2e01.png)

**Comment by bleege** [comment]
Updated the logic to get the InfoWindow view to measure itself before it's added to the MapView.  This enables width and height to be used to adjust placement of InfoWindow relative to Marker.  The screenshot below shows this now properly centering exactly on the Marker point.  Will add logic to include Marker's sprite offset to get it to display over the Marker. 

![device-2015-09-03-161558](https://cloud.githubusercontent.com/assets/989928/9671257/36da6968-5257-11e5-9c9a-241fd75143b4.png)

**Comment by bleege** [comment]
Placing InfoWindow directly on top of Marker's sprite!  \o/

Next Up: Making the InfoWindow stay with it when the map moves.

![device-2015-09-03-162509](https://cloud.githubusercontent.com/assets/989928/9671432/7b72d79e-5258-11e5-943c-e3a74c38605a.png)

**Comment by incanus** [comment]
> Next Up: Making the InfoWindow stay with it when the map moves.

Per chat, we can punt on that for `0.1.0`; we do on iOS currently. Just dismiss.

**Comment by bleege** [comment]
Yep.  Making the InfoWindow stay is related to https://github.com/mapbox/mapbox-gl-native/pull/1582 on the iOS side and https://github.com/mapbox/mapbox-gl-native/issues/2049 on the Android side.

**Comment by bleege** [comment]
When testing dismissal of InfoWindow on map movement via `MapView.onMapChanged()` which calls `updateMap()` it turns out that it's too frequent.  Looking at the iOS side [this functionality is handled in a newer version of `notifyMapChange`](https://github.com/mapbox/mapbox-gl-native/blob/49ade9d900f4859bf632b4028087751b9048063b/platform/ios/MGLMapView.mm#L2659) which has a `MapChanged` enum to delineate the types of changes.

**Comment by bleege** [comment]
Pausing work as @incanus is building out the new and improved `MapChange` infrastructure for Android in #2255.

**Comment by bleege** [comment]
InfoWindow is closed in iOS during [MapChangeRegionWillChangeAnimated event handling](https://github.com/mapbox/mapbox-gl-native/blob/15a66b8989645b702d207d96f6693ea3ddd93bdc/platform/ios/MGLMapView.mm#L2699-L2701).

**Comment by incanus** [comment]
Also `MapChangeRegionWillChange`.

**Comment by bleege** [comment]
@incanus :+1:

**Comment by bleege** [comment]
Next Up: Add Marker Tap listeners to open InfoWindow when tapped and close them when tap happens outside of Marker.

**Comment by bleege** [comment]
Porting iOS logic for tap listening and [determining if annotation is in bounds](https://github.com/mapbox/mapbox-gl-native/blob/15a66b8989645b702d207d96f6693ea3ddd93bdc/platform/ios/MGLMapView.mm#L1106-L1177).

**Comment by bleege** [comment]
I've got the basic tap listening for selection and deselection built and working for multiple markers.  I think the the nearbylist caching logic can be tightened up though as well as the acceptable height tolerance.  That said I think we're close to wrapping this one up.

![device-2015-09-04-185916](https://cloud.githubusercontent.com/assets/989928/9696550/1136d0da-5337-11e5-8635-b6432667d47b.png)

**Comment by incanus** [comment]
One thing this needs is to ignore double-taps for selection/deselection.

**Comment by incanus** [comment]
This also seems to have issues when the map is rotated.

**Comment by incanus** [comment]
Re: rotation, this is because "top right" and "bottom left" around the touch point aren't accounting for map rotation and should be determined _after_ the geo bounding box around the tap has been converted to screen coordinates. Will grab this.

**Comment by incanus** [comment]
This was my bad in porting from iOS. https://github.com/mapbox/mapbox-gl-native/commit/1886cfeab9efd2acafdf960f3172be8a185bfbac fixes things to extent to the rectangular bounds of the tap region regardless of rotation, as well as draws a debug box instead of diagonal (since we now have all four corners + it is easier to visualize). 

![screenshot_2015-09-07-11-26-38](https://cloud.githubusercontent.com/assets/17722/9721647/dac272f6-5553-11e5-89d2-4c58882a9be6.png)

(Larger regions are from lower-numbered-zoom taps.)

**Comment by incanus** [comment]
Ok, I think https://github.com/mapbox/mapbox-gl-native/pull/2260 is in good shape now. Cleaning up a bit — trying to squash but not steal all of @bleege's credit :wink:

**Comment by incanus** [comment]
Rebased, fixing a merge conflict against `master` @ https://github.com/mapbox/mapbox-gl-native/commit/7b931078695b6c69ceb6981f9034d7df1227a477`, and force-pushed. Going to fast-forward merge now as this looks great.

**Comment by incanus** [comment]
Merged as of https://github.com/mapbox/mapbox-gl-native/commit/704a4e499b4f73bf603974ef85e497c422100056.

**Comment by incanus** [comment]
![screenshot_2015-09-07-12-17-16](https://cloud.githubusercontent.com/assets/17722/9722031/7be44b18-555a-11e5-88b7-f29f18f36eda.png)

**Comment by tobrun** [comment]
Looks great :+1:

**Comment by tobrun** [comment]
One minor remark on [InfoWindow](https://github.com/mapbox/mapbox-gl-native/blob/704a4e499b4f73bf603974ef85e497c422100056/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxgl/annotations/InfoWindow.java#L35), I noticed that the View is inflated with the parent of MapView. This should be MapView itself hence it later added to the MapView. This could lead to setting the wrong LayoutParams for that View.

**Comment by ljbade** [comment]
@tobrun Nice catch will push fix.

**Comment by bleege** [comment]
> trying to squash but not steal all of @bleege's credit :wink:

Not a problem!  Always happy to have a tag team partner.

![hfd](https://cloud.githubusercontent.com/assets/989928/9738406/f8e4a156-5610-11e5-8bfc-ee612be47c15.jpg)
