### ISSUE TITLE
Feature Request: Can we have callback when user clicked MyLocationView

### ISSUE THREAD

**Issue by mdakram** [mapbox/mapbox-gl-native#8942]
Thank you mapbox for this awesome library. I have on question. Can we have callback when user clicked MyLocationView?

Use case: Like Google Maps app does when we click on blue dot it shows bottoms sheet.

**Comment by tobrun** [comment]
MyLocationView is going to be replaced with [LocationLayer](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/locationlayer). Feel free to recreate this ticket in that repo.
