### ISSUE TITLE
iOS SDK mapView double tap handling

### ISSUE THREAD

**Issue by yargeel** [mapbox/mapbox-gl-native#8945]
Hello!

I'm using Mapbox iOS SDK, making the next layout: mapView and two buttons ("zoom in" and "zoom out"). I can't figure out how to correctly handle double tap on buttons. Double tap on "zoom out" button zooms me in - as far as I understand, Mapbox's mapView intercept and handle my double tap.

I've tried the following code in viewDidLoad:

    let doubleTap = UITapGestureRecognizer(target: self, action: #selector(handleDoubleTap))
    doubleTap.numberOfTapsRequired = 2
    zoomOutButton.addGestureRecognizer(doubleTap)

    let singleTap = UITapGestureRecognizer(target: self, action: #selector(handleSingleTap))
    singleTap.numberOfTapsRequired = 1
    singleTap.require(toFail: doubleTap)
    zoomOutButton.addGestureRecognizer(singleTap)

and handlers (just to see it works):

func handleSingleTap(tap: UITapGestureRecognizer) {
    print("single")
}

func handleDoubleTap(tap: UITapGestureRecognizer) {
    print("double")
}

It doesn't work. How can I handle double tap on "zoom out" button to zoom out twice?

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
