### ISSUE TITLE
Drifting across the international dateline is sticky

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#8951]
**Platform:** iOS
**Mapbox SDK version:** v3.6.0-alpha.1 (does not reproduce in v3.5.4)

### Steps to trigger behavior

 1. Zoom to the max extents — ~z0-z1.
 2. Swipe or drift-pan the map horizontally.

The map sticks on the international dateline, centering on it before (sometimes) continuing the drift.

/cc @1ec5

**Comment by 1ec5** [comment]
Probably related: https://github.com/mapbox/mapbox-gl-js/pull/4540#issuecomment-297695218.

**Comment by friedbunny** [comment]
Bisecting this today.

**Comment by friedbunny** [comment]
Bisected back to c1c6c1e298521c177b64665b823d1444ce5e2cfe (#8583), which makes sense at a glance (without having tracked down a specific cause, yet).

Any ideas, @brunoabinader?

**Comment by brunoabinader** [comment]
@friedbunny yes - do you know if the coordinate values generated by the swipe gesture are unwrapped e.g. longitude < -180 or > +180?

I'll work on a test case to verify and a following fix.
