### ISSUE TITLE
Flickering in AnimatedMarkerActivity

### ISSUE THREAD

**Issue by ivovandongen** [mapbox/mapbox-gl-native#8956]
Animated markers seem to be flickering / disappearing (master):

![animated_markers-flickering](https://cloud.githubusercontent.com/assets/64527/25941586/afcf3f94-3642-11e7-9c70-311e46db6c78.gif)

**Comment by ivovandongen** [comment]
Checked, but https://github.com/mapbox/mapbox-gl-native/pull/8954 doesn't solve this.

**Comment by tobrun** [comment]
This issue is being tracked in https://github.com/mapbox/mapbox-gl-native/issues/8799 which is added to the next milestone for tracking. Closing as a duplicate.
