### ISSUE TITLE
Use cached tiles while doing a if-none-modified request

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#896]
We should show cached, but expired tiles immediately, do a `If-None-Modified` request meanwhile and update tile if changed. While this technically violates the HTTP spec, it will also ensure that the user sees a map as soon as possible. In most cases, the map is either fresh, or the visible differences are negligible.

**Comment by 2beaucoup** [comment]
It's either `If-None-Match` (ETag based) or `If-Modified-Since` (time based). Just sayin.

**Comment by kkaefer** [comment]
@2beaucoup you're right, and the code uses the correct header names:https://github.com/mapbox/mapbox-gl-native/blob/a3ea4acb7cb4d57ca2f5808b9b600d7c1b7b3cc7/platform/default/http_request_curl.cpp#L341-L348

**Comment by kkaefer** [comment]
This is implemented as part of #2617.
