### ISSUE TITLE
Remove Fabric specific build packaging

### ISSUE THREAD

**Issue by boundsj** [mapbox/mapbox-gl-native#8969]
Installation of the iOS SDK via Fabric is now done [completely with CocoaPods](https://fabric.io/kits/ios/mapbox/install). This includes the flow that involves the Fabric macOS app. We should remove the old Fabric specific parts of our release and process that includes:

* [x] The [release fabric script](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/scripts/release-fabric.sh)
* [x] The [ifabric line](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/scripts/deploy-packages.sh#L115) in our deploy script
* [x] The [ifabric command](https://github.com/mapbox/mapbox-gl-native/blob/master/Makefile#L256) in the makefile
* [x] The [fabric specific steps](https://github.com/mapbox/mapbox-gl-native/wiki/Releasing-the-Mapbox-iOS-SDK#fabric) of our release process 

The last one (the release process step) includes testing that an app that uses our SDK via Fabric works as expected. Since we have a Fabric specific implementation in `MGLAccountManager` that uses a library from Fabric to support the Fabric access token setting mechanism, we should probably continue to test it somehow but I'm not sure what the best way to do that is other than create a simple app using the [Fabric install instructions](https://fabric.io/kits/ios/mapbox/install).

Is there anything else required?

cc @friedbunny @incanus @1ec5

**Comment by friedbunny** [comment]
#9264 covers the first three checkboxes and I’ve [updated the release wiki page](https://github.com/mapbox/mapbox-gl-native/wiki/Releasing-the-Mapbox-iOS-SDK/_compare/87b9c6e48bcf68215db030680b28efc238c69ae7...4b0dbbf889ea608fe2c11c8010d7564267443730) to be plausibly realistic. The person who publishes v3.6.0 should be sure to run through these steps and update them with more detail.

/cc @fabian-guerra

**Comment by friedbunny** [comment]
Done in #9264.
