### ISSUE TITLE
Fix activity spinner on iOS

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#897]

**Comment by incanus** [comment]
Do you mean the one in the status bar up top? It's not common for frameworks to interact with this. We will provide delegate callbacks like `MGLMapViewDelegate.mapViewWillStartLoadingMap()` for the user to implement this if they choose. 

Related: https://github.com/mapbox/mapbox-gl-native/issues/56

**Comment by kkaefer** [comment]
Does MapKit interact with it?

**Comment by incanus** [comment]
No.
