### ISSUE TITLE
Install all ios specific submodules through makefile

### ISSUE THREAD

**Issue by asheemmamoowala** [mapbox/mapbox-gl-native#8970]
Instructions for setting up a development environment are missing steps to correctly initialize submodules required for the iOS project. These instructions were removed in #5232 in favor of the makefile initializing the submodules, but the submodules for iOS are not being initialized correctly.

**Platform:** iOS
**Mapbox SDK version:**

### Steps to trigger behavior

 1. On a clean machine, follow Install instruction for iOS SDK
 2. `>make iproj`

### Expected behavior
All required submodules are initialized and XCode project can be built successfully

### Actual behavior
XCode project is missing the SMCalloutView, KIF, and OHHTTPStubs projects

**Comment by jfirebaugh** [comment]
Duplicate of #8750, I think?

**Comment by asheemmamoowala** [comment]
Agreed, closing in favor of #8750
