### ISSUE TITLE
Warn when using runtime styling with unversioned style methods

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8971]
The iOS and macOS SDKs should warn developers when they try to use unversioned style URLs with the runtime styling API.

Per https://github.com/mapbox/mapbox-gl-native/pull/6301#issuecomment-297207860, the style URL factory methods on MGLStyle would append a query parameter like `?x-darwin-versioned=false` to the returned URL. `-[MGLMapView setStyleURL:]` would then detect that parameter, strip it, and set an ivar. `-[MGLStyle style]` would log a warning to the console if the ivar is set; similarly, we’d log a warning to the console just before calling `-[MGLMapViewDelegate mapView:didFinishLoadingStyle:]`. The warning would be throttled to once per session, and perhaps we could make it debug-only.

There’s a risk that the developer is relying on the absolute URLs returned by these factory methods, and this change would cause those URLs to change. That could be a good argument against implementing this proposal and instead waiting for #6386, which would change the factory methods to return MGLStyle objects instead of NSURLs.

/cc @kkaefer @boundsj

**Comment by kkaefer** [comment]
I'm not too keen on an additional parameter because it means we'll have to special case it when requesting + storing to the database.

**Comment by jfirebaugh** [comment]
Same, and I'm optimistic about having core support for #6386 soon.

**Comment by 1ec5** [comment]
This would be completely transparent to mbgl because MGLMapView would strip the parameter before calling setStyleURL.
