### ISSUE TITLE
MapBox.animateCamera or moveCamera could be fail in tracking mode

### ISSUE THREAD

**Issue by TranThuong** [mapbox/mapbox-gl-native#8977]
**Platform:Android**
**Mapbox SDK version: V5.0.2**

### Steps to trigger behavior

 1. Set Mapbox in tracking 
 2. Then do MapBox.animateCamera or moveCamera 

### Expected behavior
The map should be changed to new set position and the Mapbox shouldn't be in tracking mode any more

### Actual behavior
Sometime the mapbox still rest in tracking mode, then the map is alway on the current GPS position.

noted that It works well on the Mapbox V4.x

**Comment by tobrun** [comment]
Related to https://github.com/mapbox/mapbox-gl-native/issues/7878, we need to verify if this is a worked-as-designed or unwanted behaviour.
