### ISSUE TITLE
default to -fvisibility=hidden

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#898]
Expose symbols only for the public API.

From @springmeyer:

one gocha is that `-fvisibility=hidden` interacts in interesting ways with  `-flto`. I've gotten mapnik working with both combined but it required some careful usage of `__attribute__ ((visibility ("default")))` and `extern template`

Refs https://github.com/mapbox/mapbox-gl-native/issues/759.

**Comment by ljbade** [comment]
I did not realise you needed this flag Linux/OSX. I know on Windows the default is to only expose specifically marked symbols from shared lib.

**Comment by mikemorris** [comment]
https://gcc.gnu.org/wiki/Visibility has an example of macros with Windows support

**Comment by mikemorris** [comment]
Attempted setting this up in [`898-visibility-hidden`](https://github.com/mapbox/mapbox-gl-native/tree/898-visibility-hidden), seeing the follow two linker errors from Boost when running `make run-osx` that I'm attributing to the cross-lib exceptions issue with hidden symbols, but trying to track this down I can't find anywhere that we're using `boost::throw_exception`?

```
ld: warning: direct access in void boost::throw_exception<boost::bad_function_call>(boost::bad_function_call const&) to global weak symbol typeinfo for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_function_call> > means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_function_call> >::rethrow() const to global weak symbol typeinfo for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_function_call> > means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

**Comment by mikemorris** [comment]
Uh, my pull request unexpectedly passed CI when I assumed it wouldn't. Anyone want to review and see if it's actually doing what I think it is?

**Comment by mikemorris** [comment]
Rebasing [`geojsonvt-2.1.6-rapidjson`](https://github.com/mapbox/mapbox-gl-native/tree/geojsonvt-2.1.6-rapidjson) onto this branch doesn't solve the linker warnings during iOS tests - is visibility not actually set correctly here, or could the issue be that mason packages (like GeoJSONVT) are only built with `-fvisibility-inlines-hidden`?

**Comment by mikemorris** [comment]
Halfway there as of https://github.com/mapbox/mapbox-gl-native/pull/2584 with `-fvisibility-inlines-hidden`

**Comment by mikemorris** [comment]
Started work on this again today in [`898-visibility-hidden`](https://github.com/mapbox/mapbox-gl-native/tree/898-visibility-hidden) in light of needs for smaller binaries on Android and iOS.

**Comment by mikemorris** [comment]
Not seeing any reduction in iOS binary size from this yet, possible because we're still building a static library? Might need to revisit https://github.com/mapbox/mapbox-gl-native/issues/828

**Comment by zugaldia** [comment]
FWIW I just did a `make android` for both `master` and https://github.com/mapbox/mapbox-gl-native/tree/898-visibility-hidden and these are the results size-wise:

```
$ ls -l build/android-arm-v7/Release/lib.target/libmapbox-gl.so
Master: 91307852 Nov 20 15:46 build/android-arm-v7/Release/lib.target/libmapbox-gl.so
Branch: 90523492 Nov 20 15:46 build/android-arm-v7/Release/lib.target/libmapbox-gl.so
```

I see a smaller size (784,360 bytes less) or is there a better way to measure this impact?

**Comment by jfirebaugh** [comment]
Done for Android in #5656.

**Comment by kkaefer** [comment]
macOS PR in https://github.com/mapbox/mapbox-gl-native/pull/7509

**Comment by kkaefer** [comment]
iOS is in https://github.com/mapbox/mapbox-gl-native/issues/7604
