### ISSUE TITLE
Don't request glyphs for verticalized punctuation if feature can't be verticalized

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#8982]
**Platform:**
iOS and Android
**Mapbox SDK version:**
Master

### Steps to trigger behavior

For certain codepoints e.g. '.' , the corresponding verticalization char is also added to glyph dependencies. [This happens here](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/layout/symbol_layout.cpp#L143).

However the requested code point is not used if the placement is not along line. This happens [here](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/layout/symbol_layout.cpp#L252).

### Expected behavior

Only request code point ranges that will be used during placement.

**Comment by ChrisLoer** [comment]
It looks to me like fixing this just requires checking `allowsVerticalWritingMode` (and `textAlongLine`) for the feature before building the set of glyph dependencies.

/cc @1ec5

**Comment by jfirebaugh** [comment]
Fixed in #9033.
