### ISSUE TITLE
Migrate to GL JS–powered feedback form

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#8988]
A map feedback form powered by GL JS will be available as an alternative to the mapbox.js-powered [Map Feedback](https://github.com/mapbox/map-feedback/) tool. We’ll want to move the native SDKs over to the new tool, even when the relevant TileJSON attribution still specifies the original tool, because the new tool will more closely match what the user sees on screen before reporting an issue.

Just as mapbox.js was able to pass the map ID into the original tool, we’ll be able to pass a style ID into the new tool. mapbox/mapbox-gl-js#4685 passes in the (undocumented) `owner` and `id` properties at the root of the style JSON object. That would require adding additional parsing logic along the lines of mapbox/mapbox-gl-native#6002. But a simpler approach would be to extract the owner and ID from the style URL, as long as it’s a mapbox: URL. After all, the feedback tool would use that very mapbox: URL to load the style in GL JS.

There are separate implementations of the map feedback button on Android and iOS/macOS. Note that this work is distinct from mapbox/mapbox-gl-native#6001 for iOS and mapbox/mapbox-gl-native#6013 for Android, but it may help us prepare for those features.

/cc @mollymerp @tristen @tobrun

**Comment by 1ec5** [comment]
#9078 migrates iOS and macOS to the new feedback tool.

**Comment by zugaldia** [comment]
Tracking Android work on https://github.com/mapbox/mapbox-gl-native/issues/9090.

**Comment by mollymerp** [comment]
note that I've changed the hash order to match the gl-js hash class (`zoom, center latitude, center longitude, bearing, and pitch` ) and added user `access_token`  as an additional param (necessary to display the style the user is reporting feedback on).
> For example, http://path/to/my/page.html#2.59/39.26/53.07/-24.1/60 .

**Comment by mollymerp** [comment]
eeep sorry I had to revert this back to `#/lng/lat/zoom/bearing/pitch/` format due to constraints @tristen informed me of today. Apologies @1ec5 @zugaldia if this makes more work for you 🙈

**Comment by 1ec5** [comment]
No worries. I’ve been tracking the changes in mapbox/mapbox-gl-js#4685 and have an implementation in #9078. I noticed that the GL JS implementation has some pretty fancy logic for determining the latitude and longitude precision based on the zoom level. Out of expediency (so I could keep using a C format string), I went with a hard-coded five-decimal-place precision; do you think that would be a problem?

/cc @tristen

**Comment by 1ec5** [comment]
Fixed for iOS and macOS in #9078 on the release-ios-v3.6.0-android-v5.1.0 branch. The fix for Android is tracked in #9090.
