### ISSUE TITLE
[android]getMetersPerPixelAtLatitude

### ISSUE THREAD

**Issue by Larnoo** [mapbox/mapbox-gl-native#8990]
**Platform:** android
**Mapbox SDK version:** 5.0.0

### Steps to trigger behavior

 1. `getMetersPerPixelAtLatitude()`is 300.  This means  1px is 300 meters?
 Or 1dp is 300 meters?

I test result may be that 1dp is 300 meters.

But why the method name is `PerPixel`?

**Comment by Larnoo** [comment]
@tobrun `getMetersPerPixelAtLatitude` document said that `Returns the distance spanned by one pixel at the specified latitude and current zoom level.`  The `one pixel` means 1dp or 1px? Can you tell me?

**Comment by tobrun** [comment]
It should be 1px as the documentation and API would indicate. That said, I'm not seeing the required conversion in place to actually convert dp to px. Thank you for the report @Larnoo.

**Comment by tobrun** [comment]
#9048 landed on the release branch

**Comment by tobrun** [comment]
Reopening this, after cross comparing other bindings it seems that the assumptions in OP aren't correct. Going to revert this change before a final release.

**Comment by Dzhekson6000** [comment]
I checked it. It is really in DP.
```Kotlin
val countPx = 100f
val pointA: LatLng = mapboxMap.projection.fromScreenLocation(PointF(0f, 0f))
val pointB: LatLng = mapboxMap.projection.fromScreenLocation(PointF(countPx, 0f))
val metersInPixel = mapboxMap.projection.getMetersPerPixelAtLatitude(radiusPoint.latitude)

val distance = pointA.distanceTo(pointB)
val distanceOnScreen = metersInPixel * countPx
val distanceOnScreenInDp = metersInPixel * context.pxToDp(countPx)

assertEquals(distance, distanceOnScreen) // assert
assertEquals(distance, distanceOnScreenInDp) // good
```
