### ISSUE TITLE
Android MarkerView onMarkerClick fired only after second click

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#8991]
When clicking a MarkerView in de latest Android SDK, onMarkerClick event is not fired. On first click, an infowindow appears. Only on second click, the onMarkerClick event is fired.

**Comment by tobrun** [comment]
Thank for the report @nijs9, for MarkerView you should use `MapboxMap.OnMarkerViewClickListener` which you can set through `MapboxMap.getMarkerViewManager().setOnMarkerViewClickListener`.

The second part of the OP shouldn't happen. Going to use this issue to fix that part up.

**Comment by tobrun** [comment]
Fixed in #8996. Closing
