### ISSUE TITLE
UIView<MGLCalloutView> not tracking annotation

### ISSUE THREAD

**Issue by macro-shen** [mapbox/mapbox-gl-native#8993]
**Platform:** iOS SDK
**Mapbox SDK version:** 3.5.2

### Steps to trigger behavior

a question from a Mapbox iOS SDK user,  he used customized UIView<MGLCalloutView>, but the view didn’t move when moving the map to other palce, does anyone know why?

### Actual behavior
![image](https://cloud.githubusercontent.com/assets/1848550/26046069/c61c5d6e-397f-11e7-9612-fd094db00226.png)

Following is his sample code:
![image](https://cloud.githubusercontent.com/assets/1848550/26046192/50f22c66-3980-11e7-9b38-bd95f387683a.png)

![image](https://cloud.githubusercontent.com/assets/1848550/26046292/d4e8a98c-3980-11e7-9621-a0283e4a790f.png)

![image](https://cloud.githubusercontent.com/assets/1848550/26046113/edab4fb6-397f-11e7-89bc-2e3db69c697f.png)

**Comment by 1ec5** [comment]
`GDRealPositionCalloutHolidayView.anchoredToAnnotation` should be implemented to return `YES`. (Also see `dismissesAutomatically`.)

/ref #7646
