### ISSUE TITLE
MapKit and Mapbox in a single view controller (two protocols with same method signature, conflict)

### ISSUE THREAD

**Issue by alpennec** [mapbox/mapbox-gl-native#8994]
Hello,

I am trying to implement the Mapbox SDK into my iOS mobile application. In the app settings, the user can choose between 2 map providers: Apple Maps (MapKit) and Mapbox. Based on the chosen provider, my view controller adds either a MKMapView or a MGLMapView to the current visible view.

I have a problem because I want to implement the mapView(_:didUpdate:) method. However, this method is present in both MKMapViewDelegate and MGLMapViewDelegate protocols. It seems there is a conflict in my code when I want to have code for both methods in the same viewController class.

How would you design a view controller that could implement both MapKit and Mapbox protocols, if the method signature is the same?

Thanks! Axel

**Comment by frederoni** [comment]
In Objective-C you could just check the type of the mapView but you're right that it would conflict in Swift. You could split up the delegate methods into separate classes. Something along these lines:
```swift
class MyViewControllerMKMapViewDelegate: NSObject, MKMapViewDelegate {
    func mapView(_ mapView: MKMapView, didUpdate userLocation: MKUserLocation) { }
}

class MyViewControllerMGLMapViewDelegate: NSObject, MGLMapViewDelegate {
    func mapView(_ mapView: MGLMapView, didUpdate userLocation: MGLUserLocation?) { }
}

class MyViewController: UIViewController {
    let mapboxMapView = MGLMapView()
    let mapkitMapView = MKMapView()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        mapboxMapView.delegate = MyViewControllerMGLMapViewDelegate()
        mapkitMapView.delegate = MyViewControllerMKMapViewDelegate()
        …
    }
}
```

**Comment by alpennec** [comment]
@frederoni thanks for your nice answer.

This is one of the solutions I was thinking about. I like the approach, my main issue is that I will have a lot of classes because I actually have 4 viewControllers that need to conform to the map protocols... and each controller has its own implementation for the methods from the protocol.
