### ISSUE TITLE
Cache tessellated polygon data

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#90]
On mobile platforms, we should cache the polygon tessellation. Rather than storing the tiles as we received them, we should rewrite the geometry and use this field:

```
    // A list of indices to the geometry array that specify a triangulation of
    // this geometry. This must only exist if this feature is a polygon.
    // These are the valid indices for the example above:
    //     0 ==>  (3/6)
    //     1 ==>  (8/12)
    //     2 ==> (20/34)
    // Indices beyond 2 are invalid, as the total number of vertices is 3.
    repeated sint32 triangulation = 5 [ packed = true ];
```

Tessellation might add vertices. We can append them to the geometry and store them as `moveto` vertices, which won't generate `GL_LINES` when unpacking again.

**Comment by kkaefer** [comment]
Bogus close

**Comment by jfirebaugh** [comment]
No current plans to pursue this.
