### ISSUE TITLE
get/setStyleJSON should not be public API

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#900]
We only want to support setting a style via the URL (and `asset://`) mechanism provided by `get/setStyleURL`

Helps avoid issues with a style URL loading after the JSON is set directly.

Currently `get/setStyleJSON` is only needed in the tests to rewrite port numbers. We should find a way to expose this to the tests but not make it a public API.

/cc @kkaefer

**Comment by mikemorris** [comment]
How are you defining public API @ljbade? I'm currently using `setStyleJSON` at https://github.com/mapbox/node-mapbox-gl-native/blob/master/src/node_map.cpp#L132 to set data loaded from a custom `FileSource` implementation.

**Comment by incanus** [comment]
> Does `setStyleURL` correctly use the map's `FileSource` to load data?

Yes, this API now supports both regular HTTP URLs as well as `mapbox://user.style` map IDs.

**Comment by mikemorris** [comment]
What I was asking is if it supports the refactored `FileSource` interface @incanus, such that when used with Node.js bindings I can plug in a custom `FileSource` rather than having something like `curl` baked in.

**Comment by friedbunny** [comment]
We did this.
