### ISSUE TITLE
NullPointerException Transform.getZoom

### ISSUE THREAD

**Issue by andrei-egeniq** [mapbox/mapbox-gl-native#9000]
**Platform:**
Android, all versions
**Mapbox SDK version:**
5.0.2

### Steps to trigger behavior
Issue occurs in the wild or in very long monkey stress test.

### Expected behavior
SDK does not crash

### Actual behavior
SDK crash

java.lang.NullPointerException
//      at com.mapbox.mapboxsdk.maps.Transform.getZoom(Transform.java:175)
//      at com.mapbox.mapboxsdk.maps.MapGestureDetector$GestureListener.onScroll(MapGestureDetector.java:382)
//      at android.view.GestureDetector.onTouchEvent(GestureDetector.java:567)
//      at android.support.v4.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(GestureDetectorCompat.java:479)
//      at android.support.v4.view.GestureDetectorCompat.onTouchEvent(GestureDetectorCompat.java:542)
//      at com.mapbox.mapboxsdk.maps.MapGestureDetector.onTouchEvent(MapGestureDetector.java:202)
//      at com.mapbox.mapboxsdk.maps.MapView.onTouchEvent(MapView.java:296)
//      at android.view.View.dispatchTouchEvent(View.java:7706)
//      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
//      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
//      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
//      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
//      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
//      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
//      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
//      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
//      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
//      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
//      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
//      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
//      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
//      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
//      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
//      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
//      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
//      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
//      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
//      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
//      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
//      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
//      at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
//      at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
//      at android.app.Activity.dispatchTouchEvent(Activity.java:2458)
//      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
//      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
//      at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
//      at android.view.View.dispatchPointerEvent(View.java:7886)
//      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3954)
//      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3833)
//      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
//      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
//      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
//      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3525)
//      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
//      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3582)
//      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
//      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
//      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
//      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
//      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
//      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5602)
//      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5582)
//      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5553)
//      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5682)
//      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
//      at android.os.MessageQueue.nativePollOnce(Native Method)
//      at android.os.MessageQueue.next(MessageQueue.java:138)
//      at android.os.Looper.loop(Looper.java:123)
//      at android.app.ActivityThread.main(ActivityThread.java:5017)
//      at java.lang.reflect.Method.invokeNative(Native Method)
//      at java.lang.reflect.Method.invoke(Method.java:515)
//      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
//      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
//      at dalvik.system.NativeStart.main(Native Method)

**Comment by tobrun** [comment]
Thank you for the report, this was already reported in https://github.com/mapbox/mapbox-gl-native/issues/8650 and fixed in https://github.com/mapbox/mapbox-gl-native/pull/8767. Feel free to test out the latest 5.1.0-beta.2 or the SNAPSHOT to verify if it's fixed. Installation instructions can be found [here](https://www.mapbox.com/android-sdk/). Going a head and closing, feel free to retest!
