### ISSUE TITLE
When the map is not toward the North，zoomIn or zoomOut map

### ISSUE THREAD

**Issue by yangzhedeID** [mapbox/mapbox-gl-native#9011]
**Platform:Android**
**Mapbox SDK version:5.1.0-beta.1**

### Steps to trigger behavior

 1. Rotate map
 2. zoom In or Zoom Out map Twice 

### Expected behavior

Maps don't rotate

### Actual behavior

1.The first map rotates to the opposite angle
2.The second map turns to normal

**Comment by yangzhedeID** [comment]
zoom use api `mapboxMap.animateCamera(CameraUpdateFactory.zoomOut());` and `mapboxMap.animateCamera(CameraUpdateFactory.zoomIn());`

**Comment by tobrun** [comment]
Thank you for the report. I pinpointed to the conversion we do from Android SDK Bearing to the core equivalent. We were making the angle negative before setting which isn't required. This resulted in setting an angle of 220 but was returned as 140.

**Comment by tobrun** [comment]
#9050 merged to release branch. Closing.
