### ISSUE TITLE
Property function polygon overlap glitch on map move

### ISSUE THREAD

**Issue by aparlato** [mapbox/mapbox-gl-native#9016]
**Platform:** iOS
**Mapbox SDK version:** 3.52

### Steps to trigger behavior

 1. Have a property function for polygons where different classes overlap (eg property function for parks and cemeteries on landuse)
![image](https://cloud.githubusercontent.com/assets/15698320/26122965/1839f102-3a2e-11e7-8336-941b3e8d01d2.png)
 2. Make property function use two different colors
 3. Move the map

### Expected behavior
- Layer order should fall back to the data where park is over top of cemetery, only park should be visible

### Actual behavior
Screenshot mid glitch:
![img_4614](https://cloud.githubusercontent.com/assets/15698320/26122971/1ca462c2-3a2e-11e7-84ac-f8f6749f0c8b.PNG)

Looks correct on static map, but totally glitches out between the colors of the overlapping class polygons referenced in the property function when moving the map (pan or zoom)

**Comment by jfirebaugh** [comment]
Fixed in #9942.
