### ISSUE TITLE
Unnecessarily low memory usage

### ISSUE THREAD

**Issue by leelx78** [mapbox/mapbox-gl-native#9018]
Hi I noted an unnecessarily low memory usage in my application. I have a vector map and a tile map (jpeg, satellite, worldwide).

When I pan around I clearly see that tiles are not always cached and are often redrawn, with a lag and high GPU usage. Although keeping memory low **is VERY good practice in general**, this seems excessive in my case (32 MB max on a device with 2GB ram - see screenshot below). Note that this is for **private use** on a specific device so in **MY** specific case I don't need to worry about compatibility with older devices with low RAM etc. 

Can I tweak memory settings to avoid continuous redrawing when panning? I already tried to use the "largeHeap" option but made no difference

Thanks

![screen shot 2017-05-16 at 21 57 55](https://cloud.githubusercontent.com/assets/28741731/26128138/476c6aea-3a83-11e7-84a6-c81096482e7f.png)

**Comment by tobrun** [comment]
@leelx78 thank you for reaching out. The graph what you are showing is the Java heap and the amount of heap an application can address is limited by the manufacturer. It used to be 16 mb but now with larger screens (and larger bitmaps) this has increased to 32mb and sometimes even 64mb. That being said, native code (NDK) is not subject to the heap limit (which most of this Android SDK is made out of). Let us know if you have any more questions or feedback. Closing this is as non-actionable.

**Comment by leelx78** [comment]
Thanks. So any idea on why it keeps redrawing every time? Can I make it keep off-screen tiles in memory a bit longer? As I said this is a private app and I can use the extra speed and avoid having to redraw tiles every time I pan
