### ISSUE TITLE
[iOS] Static lib size x2 from 3.4.2 to 3.5.2

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#9021]
**Platform: iOS**
**Mapbox SDK version: 3.5.2**

### Steps to trigger behavior

 1. Build the static library in release mode
 2.
 3.

### Expected behavior
static lib size should be quite the same as previous 3.4.2 version (Mapbox.framework is 103MB).

### Actual behavior
static lib size of 3.5.2 Mapbox.framework is 264MB

Seems that strip is correctly run over the static lib, so the issue is somewhere else.

**Comment by RomainQuidet** [comment]
I gave a try with http://stackoverflow.com/questions/19992463/ios-static-library-compiled-with-xcode-remembers-its-source-files.
This works : In LLVM code generation, set Generate debug symbols to No and Symbols hidden by default to Yes. For some reason, even if you tell it to strip symbols, it's not going to do it unless these are set.

Static Mapbox lib went from 264MB to 163MB. Still bigger than 3.4.2, but much better.

**Comment by RomainQuidet** [comment]
Another strange behavior, if I extract slices from the static lib, arm slices are still twice the size of intel ones:

-rw-r--r--   1 mappy  staff   155M 17 mai 15:14 Mapbox
-rw-r--r--   1 mappy  staff    56M 17 mai 15:14 Mapbox-arm64
-rw-r--r--   1 mappy  staff    24M 17 mai 15:14 Mapbox-x86

I just 
'ran lipo -thin x86_64  Mapbox -output Mapbox-x86'
and the same with arm64 on the newly stripped Mapbox static lib (155MB)

**Comment by RomainQuidet** [comment]
I'm making some more tests about arm slices and will make a PR for the release static lib

**Comment by fabian-guerra** [comment]
Hi.
Thank you for reporting this issue, v3.5.1 was built with Xcode 8.3 that caused Mapbox iOS SDK 3.5.1 to be 2× larger than 3.5.0. Download v3.5.2 also you may need to update your Xcode to latest version.
As reference this is the [radar](http://www.openradar.me/31302382).

**Comment by RomainQuidet** [comment]
This is not related to this xcode issue. I just built both mapbox versions with xcode 8.3, the issue is there.

**Comment by RomainQuidet** [comment]
PR #9022

**Comment by RomainQuidet** [comment]
Just run
make ipackage-strip FORMAT=static BUILDTYPE=Release
before and after the PR, you'll see framework size going from 266MB to 162MB

**Comment by friedbunny** [comment]
Closing this as `won’t-fix` — see our [understanding framework size doc](https://www.mapbox.com/help/ios-framework-size/) for more information.
