### ISSUE TITLE
Markers are not drawn correctly

### ISSUE THREAD

**Issue by danielprudek** [mapbox/mapbox-gl-native#9026]
# Markers are not drawn correctly

Error after adding bigger amount of markers to the map. See screenshots and enclosed demo project. This behavior was not present in 5.0.2 (instead markers disappear completely).

**Platform: Android (3 devices + emulator, different OS versions)**
**Mapbox SDK version: 5.1.0-beta.2**

![screenshot_2017-05-17-21-03-01](https://cloud.githubusercontent.com/assets/19304877/26170386/90303b1c-3b41-11e7-9606-2196b448e657.png)
![screenshot_2017-05-17-21-03-05](https://cloud.githubusercontent.com/assets/19304877/26170387/9047bd1e-3b41-11e7-8ad6-5a2dc73f7614.png)

### Steps to trigger behavior

- In 5th cycle markers are draw incorrectly, in 6th and more (MARKERS_CNT = 150), it varies with the number of markers - about 800 black was happening in the first cycle!!!
- When zoom level is high enough, random marker sometimes becomes visible correctly.

Demo project: [mapboxDemo.zip](https://github.com/mapbox/mapbox-gl-native/files/1008858/mapboxDemo.zip)

Sample code:
 ```
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Mapbox.getInstance(this, "<key>");
        setContentView(R.layout.activity_main);
        mapView = (MapView) findViewById(R.id.mapview);
        mapView.onCreate(savedInstanceState);
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {
                mapBoxMap = mapboxMap;
                final Handler timerHandler = new Handler();
                updater = new Runnable() {
                    @Override
                    public void run() {
                        clearMap();
                        addMarkers();
                        timerHandler.postDelayed(updater,1000);
                    }
                };
                timerHandler.post(updater);
            }
        });
    }

  public void clearMap() {
        if (mapBoxMap != null) {
            mapBoxMap.clear();
        }
    }

    private static final int MARKERS_CNT = 150;
    
    public void addMarkers() {
        for (int i=0; i<MARKERS_CNT; i++) {
            Random r = new Random();
            double lat = r.nextDouble() * 50;
            double lon = r.nextDouble() * 50;
            IconFactory iconFactory = IconFactory.getInstance(MainActivity.this);
            Drawable drawable = ContextCompat.getDrawable(MainActivity.this, R.drawable.poi);
            Bitmap bitmap = ((BitmapDrawable) drawable).getBitmap();
            Icon icon = iconFactory.fromBitmap(bitmap);
            Marker marker = mapBoxMap.addMarker(new MarkerOptions()
                    .position(new LatLng(lat, lon))
                    .icon(icon));
        }
    }
```

### Expected behavior
Should draw markers correctly.

### Actual behavior
Doesn't draw markers correctly.

**Comment by Freytagberndt** [comment]
Hello,
we are also struggling with this critical problem. In fact this bug is a release blocker for our finished application! I consider inability of changing annotations as very serious problem for a map framework. Are you working on fix? Do you manage to make it until release of version 5.1.0?
Thank you very much for your help and cooperation.

**Comment by danielprudek** [comment]
Could someone, at least, provide some workaround or point me out to the solution (partional, not tested, dirty hack...). I am really desperate with this and it makes whole map framework useless for my scenario.
Thank you for your effort.

**Comment by ouska** [comment]
Hi,
this is the the killer, that stops me from using mapbox. It works fine when you use only few markers that are rendered just once. I work with hundreds of markers and I see the similar behavior. 

1) sometimes markers are rendered incorrectly - cut half and half
2) sometimes markers are black
3) sometimes markers use different icons than I specify - I also work with wide range of different icons and after while markers show wrong icons
4) sometimes the icons are not shown at all - but still info window opens when I click the space the marker should be.

It seams to me there must be some issue with releasing memory. It works fine at the beginning but after while map component gets broken.

Thank you for the help.

Vojtech

**Comment by tobrun** [comment]
Thank you all for reaching and adding detailed instructions. Since this is a regression from the 5.0.2 release. 
I'm adding it to the 5.1.0 milestone for :eyes:.

**Comment by danielprudek** [comment]
Thank you for that! Feel free to contact me in case you needed further assist.

**Comment by Guardiola31337** [comment]
@danielprudek thank you for reaching out and reporting your problem.
I was able to reproduce the issue. It seems there is an overflow when creating + adding lots of icons into a map ([#9101](https://github.com/mapbox/mapbox-gl-native/issues/9101)).

BTW, if you move `Icon` creation out of the `for` loop it works fine.
Actually, if you don't need to create a different `Icon` each time, you should implement it like this:

```java
public void addMarkers() {
       // Create Icon once so memory isn't waste it
       IconFactory iconFactory = IconFactory.getInstance(MainActivity.this);
       Drawable drawable = ContextCompat.getDrawable(MainActivity.this, R.drawable.poi);
       Bitmap bitmap = ((BitmapDrawable) drawable).getBitmap();
       Icon icon = iconFactory.fromBitmap(bitmap);
       //
       for (int i=0; i<MARKERS_CNT; i++) {
           Random r = new Random();
           double lat = r.nextDouble() * 50;
           double lon = r.nextDouble() * 50;
           
           Marker marker = mapBoxMap.addMarker(new MarkerOptions()
                   .position(new LatLng(lat, lon))
                   .icon(icon));
       }
   }
```

**Comment by giperwlad** [comment]
I have the same problem. I draw 200-300 markers. And I create Icon object inside loop. 
I solved the problem in the following way: 

`  Icon icon = iconFactory.fromBitmap(bitmap);
            for (int i = 0; i < challengePoints.size(); i++) {
                Marker marker = mapboxMap.addMarker(new MarkerOptions()
                        .setPosition(new LatLng(challengePoint.lat, challengePoint.lng))
                        .setIcon(icon));
                mapMarkers.add(marker);`

I create icon before loop and it works fine. But if you need use different icons for markers I recommended divide objects into several parts and call several loop.

I really hope that the problem will be solved in the next SDK versions

**Comment by Guardiola31337** [comment]
Going to close here because this is being tracked in #6988 and there are workarounds.

Thank you all for reaching! Feel free to open new tickets if you find any other issues.

**Comment by LakshmiKalyani93** [comment]
@Guardiola31337 : What if i need to create different icon based on any particular condition? It was still producing in 5.1.4 stable version also?

**Comment by leafygreens88** [comment]
I'm just using the default markers provided and it's still giving black bitmaps

![lol2](https://user-images.githubusercontent.com/27339162/77764476-efdd0280-6ff9-11ea-8c70-8adb4b8bcc56.png)
