### ISSUE TITLE
Removing marker does not deselect it, causing memory leak

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [mapbox/mapbox-gl-native#9028]
**Platform:** Android
**Mapbox SDK version:**  mapox-android-sdk-4.2.2, however, confirmed same behavior appears to be in the current code base in AnnotationManager; https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AnnotationManager.java

### Steps to trigger behavior

 1. Select marker on map
 2. remove Marker from Map
 3. check selectedMarkers list that marker still in list

### Expected behavior

removing a marker from the map also removes the marker from the selectedMarkers

### Actual behavior

removing a marker from the map hides the infowindow, removes it from the list of annotations but does not remove it from the selectedMarkers list.

**Comment by jonl-percsolutions-com** [comment]
workaround: before removing a marker, call deselectMarker.  If clearing the map, call map.deselectMakers()

**Comment by tobrun** [comment]
Thank you for the report @jonl-percsolutions-com, fix in #9047. Closing
