### ISSUE TITLE
Android build doesn't pick up CFLAGS set by android_env.sh

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#903]

**Comment by ljbade** [comment]
More context?

**Comment by kkaefer** [comment]
Mason sets [`CFLAGS`/`LDFLAGS`](https://github.com/mapbox/mason/blob/9df7373278b2167cc531da523e61cde99e006e99/mason.sh#L119-L120), which are being forwarded in our [`android-env.sh`](https://github.com/mapbox/mapbox-gl-native/blob/73f7db9af2f76593856d64349a376412d292cd15/scripts/android_env.sh#L22-L24) script. However, now that I think about it, the `CPPFLAGS` don't include the `CFLAGS`, which may be the reason why this isn't happening.

**Comment by ljbade** [comment]
Ah yeah, it's `CXXFLAGS` thought right? `CPPFLAGS` is for the preprocessor.

Normally you have to set both if you have mixed C and C++ files.

**Comment by jfirebaugh** [comment]
This is working now, right?

**Comment by ljbade** [comment]
Yeah I think so
