### ISSUE TITLE
Load lower resolution tiles for tilted views

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#9037]
We're currently loading tiles with a fixed zoom level for a particular view, regardless of whether it is tilted or not. This leads to too many tiles being loaded on the horizon, while potentially not enough tiles are loaded at the bottom of the viewport. This is especially true for raster images because they typically use smaller tile sizes.

![screen shot 2017-05-18 at 17 52 41](https://cloud.githubusercontent.com/assets/52399/26211476/cfc8e484-3bf2-11e7-93d9-ec85cd5838d2.png)

Instead, we should be loading lower zoom level tiles for places that are further away from the camera, and potentially higher zoom level tiles that are closer to the camera, in particular when we implement https://github.com/mapbox/mapbox-gl-native/issues/6908.

There are two ways for styles to handle this:

* Render all tiles with the evaluated style of the current zoom level: This is what we do right now when showing parent/child tiles when zooming/panning while waiting for the actual tiles to load. It requires tiles to be somewhat coherent across zoom levels
* Use a different zoom level throughout the screen: This means that we'll have to evaluate the stylesheet (based on zoom level) in the shader, and is probably out of scope for a first implementation.

**Comment by 1ec5** [comment]
Needed for #6908. Reopening.

**Comment by 1ec5** [comment]
Adaptive tile loading would be one way to address the runaway tile loading that occurs when increasing the top padding: #15163.
