### ISSUE TITLE
When placing labels automatically try multiple anchor and offset, to increase label density

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#9040]
**Platform:**
All
**Mapbox SDK version:**
Master
### Steps to trigger behavior
I've attached multiple screenshots illustrating what the problem is and how this will address this.

1. In the attached screenshot for 'mapbox street' style, one of the labels 'Subway' or 'Weinerschnitzel' will disappear upon rotation due to collision detcion. Moving one of the text labels  to east/west of the icon would have prevented  this.

2. Attached also are two screenshots for default iOS mapping application.  If you look at title 'Ol Republic Title co',  in one screenshot it is placed south of the icon. In another one it is placed west of the icon.

3. Currently the only way to model it in mapbox styles is to create multiple layers each differing just in offset and anchor values. This is extremely cumbersome.

Even just trying four different anchor/offset combination values would lead to dramatically improved POI renderings at higher zoom levels.

![img_0955](https://cloud.githubusercontent.com/assets/8890269/26227334/a4365966-3be6-11e7-9417-513d940678b8.PNG)
![img_0147](https://cloud.githubusercontent.com/assets/8890269/26227413/32755a60-3be7-11e7-9c94-29ce275a525b.PNG)
![img_0145](https://cloud.githubusercontent.com/assets/8890269/26227416/34babd4c-3be7-11e7-9953-0ec4ad884ece.PNG)

 

### Expected behavior
Increase label density by automatically shifting text to the west/east by trying multiple anchor values when placing text.

### Actual behavior
POIs are missing at higher zoom levels.

**Comment by kkaefer** [comment]
See https://github.com/mapnik/mapnik/wiki/TextSymbolizer#simple for prior art.
