### ISSUE TITLE
Parity with native iOS mapping application when map is pitched (iOS)

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#9041]
**Platform:**
iOS
**Mapbox SDK version:**
Master
### Steps to trigger behavior
When https://github.com/mapbox/mapbox-gl-native/pull/9009 lands, the quality of pitched maps would be much higher than it is today. It would be really nice if out of the box, when pitched MGLMapView worked like the one in default iOS mapping application  (For e.g. rotation of MGLMapView is very similar to the default iOS mapping application). 

1.)  2D button that automatically appears when map is pitched.
2.)  Disable pitch at lower zoom levels.

**Comment by kkaefer** [comment]
I believe this is in the realm of application developers, or possibly plugins, since all you'd need to implement that is the public API.

**Comment by mb12** [comment]
Yes, all the necessary events are available for it to be implemented outside the SDK as well. It a nice to have like the MGLScaleBar.

**Comment by 1ec5** [comment]
> Disable pitch at lower zoom levels

This functionality should be baked into the SDK: https://github.com/mapbox/mapbox-gl-native/issues/6908#issuecomment-290593356
