### ISSUE TITLE
Lines show aliasing artifacts when map is pitched.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#9042]
**Platform:**
All
**Mapbox SDK version:**
Master
### Steps to trigger behavior
I've attached a screenshot from retina screen illustrating what the issue is.

If you look at highway 505 at center of the viewport, the line looks like a thin strand of hair with lots of jagged edges.  

![img_0954](https://cloud.githubusercontent.com/assets/8890269/26227977/b9253730-3bea-11e7-9f44-fb5648d98892.PNG)

**Comment by jfirebaugh** [comment]
This was due to buggy data in the Mapbox Streets vector tiles; they've now been fixed.

**Comment by mb12** [comment]
@jfirebaugh This is still trivially reproducible.  I've attached another screenshot illustrating this. 

Can you please add more details as to what was the issue with data is that you think is causing this aliasing artifact and what was changed that fix this?  If possible can you please provide a screenshot illustrating that this has been fixed.
I can't think of any any reason how vector tile data can cause aliasing artifacts at certain sections of the viewport and not others.  Can you please provide explanation of how **buggy data** can cause aliasing artifacts at only certain sections of the viewport?


![screenshot 100](https://user-images.githubusercontent.com/8890269/27362404-1914db52-55e3-11e7-946d-4fd12fcd0818.png)

**Comment by jfirebaugh** [comment]
The tiles contained multiple stacked copies of certain features, notably highways.

**Comment by mb12** [comment]
This is reproducing with all vector  styles, with both GL JS as well as native. 

The aliasing artifact shows on all lines at the top of the viewport. The highways was just an example. When map is tilted it's very easy to notice the serrated tooth/jagged line for virtually all lines on top of the viewport.
