### ISSUE TITLE
Building shadows are missing

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#905]
For some reason the shadows on buildings are missing:
![device-2015-02-18-175439](https://cloud.githubusercontent.com/assets/1215089/6260690/62840a3e-b797-11e4-869d-24e1392b72d4.png)

**Comment by jfirebaugh** [comment]
This probably has the same root cause as #906.

**Comment by ljbade** [comment]
@jfirebaugh @ansis yeah I noticed it looks better on Linux. Just now testing if latest styles also fix Android.

**Comment by ljbade** [comment]
Works in master now.
