### ISSUE TITLE
Reduce compilation time

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#9055]
We should investigate ways to reduce compilation times.

Anecdotally, compilation time has been steadily creeping up — it currently takes ~10 minutes for a clean iOS debug build in Xcode to complete on my MacBook Pro (Retina, 13-inch, Early 2015, 3.1 Ghz). This is quite long and negatively affects productivity.

Breakdown by target, in the order they’re built when running ios-app:

| 🎯| ⏱ |
|---|---|
mbgl-core | 7 minutes
dynamic | 2 minutes
ios-app | 1 minute

/cc @mapbox/gl

**Comment by 1ec5** [comment]
If you see any opportunities to replace Objective-C++ files with pure Objective-C files in the dynamic target, we should look into doing so. Objective-C++ is known to be slow to compile due to those pluses.

**Comment by friedbunny** [comment]
This has been and is being addressed in several places:

- [x] https://github.com/mapbox/mapbox-gl-native/pull/9399 — Enable ccache
- [x] https://github.com/mapbox/mapbox-gl-native/pull/7388 — Only build active architecture when building Debug builds to speed up compile time
- [ ] https://github.com/mapbox/mapbox-gl-native/pull/7131 — Update compile flags for iOS
- [ ] Switch to Xcode 9 — waiting on its release this fall.
- [x] Get a computer with more cores. 😬

**Comment by friedbunny** [comment]
I think we’re in a decent place with ccache and other incremental improvements — nothing actionable left here.
