### ISSUE TITLE
[iOS] Predicate "extrude == true" does not correctly filter results

### ISSUE THREAD

**Issue by jmkiley** [mapbox/mapbox-gl-native#9056]
**Platform:** iOS 
**Mapbox SDK version:** v3.6.0-alpha.1

The [documentation](https://github.com/mapbox/mapbox-gl-native/blob/f6e79d70735361438655f279c8699a786d25458c/platform/darwin/src/MGLFillExtrusionStyleLayer.h#L49) for `MGLFillExtrusionStyleLayer` currently suggests that developers use the following predicate:

` layer.predicate = NSPredicate(format: "extrude == TRUE")`

However, this does not work. I have tested it out with different capitalizations as well. In order to correctly filter buildings/building parts, the predicate should be:
`layer.predicate = NSPredicate(format: "extrude == %@ AND height >= 0", "true")`

Is this is intended behavior, or is just correcting the documentation will be enough.

cc @1ec5 @incanus @boundsj

**Comment by 1ec5** [comment]
It turns out that the `extrude` property in the Mapbox Streets v7 source is a string (either `"true"` or `"false"`) rather than a Boolean value. So the documentation should be updated to use the format string `extrude == 'true'` rather than `extrude == TRUE`.

/cc @ajashton

**Comment by 1ec5** [comment]
Fixed in #9059 on the release-ios-v3.6.0-android-v5.1.0 branch.
