### ISSUE TITLE
Warning from ParseStyle with bright

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#906]
Seeing this in the logs:
`[WARNING] ParseStyle: value must be array of two numbers`

/cc @ansis

**Comment by jfirebaugh** [comment]
Are you on the v7 version of bright? Can you run the style through [`gl-style-validate`](https://github.com/mapbox/mapbox-gl-style-lint#validation)?

**Comment by ljbade** [comment]
Yep both Linux an Android load the v7 styles. Will try updating styles to latest master.

**Comment by ljbade** [comment]
Ah the style was 66 commits behind. One of many problems with using git submodules. Perhaps we need to pin to the branch.

**Comment by ljbade** [comment]
@jfirebaugh: Can we switch to pinning the `mb-pages` branch instead of specific commits? E.g see second answer at http://stackoverflow.com/questions/1777854/git-submodules-specify-a-branch-tag/1778247#1778247

We would need to use `git submodule update --remote` instead of the normal update.

**Comment by jfirebaugh** [comment]
Yes, we could try switching to tracking the mb-pages branch of mapbox-gl-styles. Though, if I understand how it works correctly, it might introduce _more_ confusion: two developers at the same mapbox-gl-js revision might have two different revisions of mapbox-gl-styles, depending on when they last ran `git submodule update --remote`.

**Comment by ljbade** [comment]
@jfirebaugh, yeah that is true. We really need a better way to handle mpbgl-native dependencies as git submodules seem to cause lots of problems.
