### ISSUE TITLE
[Android] MarkerViews blink when setup on map

### ISSUE THREAD

**Issue by memofr** [mapbox/mapbox-gl-native#9067]
**Platform:Android**
**Mapbox SDK version:5.1.0-beta.1**

### Steps to trigger behavior

 1. Create a Map
 2. Put some MarkerViews
 3. Animate them often

### Actual behavior
Hi! My markerViews blink randomly when I animate them (change position, apply animation, rotate), also I'm animating the camera to have the position of the user always in the center. MarkerView that represent the user is animated each time the position is updated (same for the camera), and other markerviews each 500ms.

**Comment by tobrun** [comment]
@memofr thank you for reaching out. We are tracking this issue in https://github.com/mapbox/mapbox-gl-native/issues/8799. Closing as a duplicate, feel free to reach out if you have any other issues!
