### ISSUE TITLE
[iOS] May I pre-cache the zoomLevel 0 map（thumbnail）contain all the world

### ISSUE THREAD

**Issue by iseeicando** [mapbox/mapbox-gl-native#9075]
before finish loading the map，the background is blank.
The experience is not very good
Can I pre-cache a thumbnail contain all world which used to be show before finish loading map？

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/). For this particular question, you might be interested in the Mapbox [static API](https://www.mapbox.com/api-documentation/#static) for generating the thumbnail. If you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
