### ISSUE TITLE
Why inline geojson source must have a properties property?

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-native#9076]
**Platform:**
**Mapbox SDK version:**
node-mapbox-gl-native 3.5.1
### Steps to trigger behavior
style.json:
```
{
  "name": "aaa",
  "verson": 8,
  "sources": {
    "geojson": {
      "type": "geojson",
      "data": {
        "type": "FeatureCollection",
        "features": [{
          "type": "Feature",
          "geometry": {
            "type": "Polygon",
            "coordinates": [
              [
                [
                  77.34374999999999,
                  19.973348786110602
                ],
                [
                  119.17968749999999,
                  19.973348786110602
                ],
                [
                  119.17968749999999,
                  50.28933925329178
                ],
                [
                  77.34374999999999,
                  50.28933925329178
                ],
                [
                  77.34374999999999,
                  19.973348786110602
                ]
              ]
            ]
          }
        }]
      }
    }
  },
  "layers": [{
    "id": "background",
    "type": "background",
    "paint": {
      "background-color": "#f00"
    }
  }, {
    "id": "polygon",
    "type": "fill",
    "source": "geojson",
    "paint": {
      "fill-color": "#0f0"
    }
  }]
}
```

### Expected behavior
![0](https://cloud.githubusercontent.com/assets/1522494/26339461/a3ecccc4-3fba-11e7-94eb-2e5be02f3f0b.png)

### Actual behavior
It complains:
```
'Feature must have a properties property'
```

![0 1](https://cloud.githubusercontent.com/assets/1522494/26339466/b5b95864-3fba-11e7-923b-385ffc51bab5.png)

When set the  `"properties": { "id": 1 },`, works as expected.
Note that mapbox-gl-js does not have this problem.

**Comment by kkaefer** [comment]
Upstream ticket: https://github.com/mapbox/geojson-cpp/pull/33

**Comment by jingsam** [comment]
Got it, 3ks

**Comment by kkaefer** [comment]
Upstream ticket merged. Remaining tasks on this ticket are:

- [ ] Create + publish Mason version of [geojson-cpp v0.4.2](https://github.com/mapbox/geojson-cpp/releases/tag/v0.4.2)
- [ ] Update CMake file to use new geojson-cpp version
- [ ] Add test case that parses a GeoJSON file that is missing the `properties` key
