### ISSUE TITLE
Map horizontally rotated in snapshot

### ISSUE THREAD

**Issue by danielprudek** [mapbox/mapbox-gl-native#9079]
**Platform: Android (different OS versions)**
**Mapbox SDK version: 5.1.0-SNAPSHOT from May 23**

With latest snapshot map became horizontally rotated (see screenshot). It was probably OK in  **5.1.0-beta.2**

![screenshot_2017-05-23-15-33-26](https://cloud.githubusercontent.com/assets/19304877/26356051/1755ec12-3fcb-11e7-9f83-3562cd6ebf8c.png)

**Comment by tobrun** [comment]
fixed with #9083, thank you for the report.

**Comment by danielprudek** [comment]
Thank you for fast reaction and fix. It is now OK when launched, but after calling `mapboxMap.easeCamera(CameraUpdateFactory.newLatLngBounds(bounds, 50), 1000, callback);` it gets rotated again during animation. After that map stays incorrect and another call has no rotating effect.

**Comment by danielprudek** [comment]
Thank you again, now it seem working fine!
