### ISSUE TITLE
Faded labels do not disappear automatically.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#908]
On zooming in and zooming out, labels fade as expected. However at times one of these faded labels persists until the screen is panned. I've attached a screenshot illustrating the issue. The label  "Gresham Ave" at center right illustrates a persisted faded label. I was expecting it to disappear. But it persists until the screen is touched again.

Is this a feature or a bug?

![faded_label_stays](https://cloud.githubusercontent.com/assets/8890269/6262167/d5aceace-b7b2-11e4-8046-6c6b68c3c12e.PNG)

**Comment by ljbade** [comment]
Its a bug. There is ready as ticket for this somewhere.

/cc @ansis

**Comment by ljbade** [comment]
Found the existing ticket -> https://github.com/mapbox/mapbox-gl-native/issues/779
