### ISSUE TITLE
Mapbox mapzen lost issues

### ISSUE THREAD

**Issue by krsticdragan** [mapbox/mapbox-gl-native#9084]
Hi there,

Im currently running 5.1.0=beta.2 version of mapbox and currently im getting this error. I havent noticed before this error prior to version 5.0.2, like in the issue (https://github.com/mapbox/mapbox-gl-native/issues/8999), but unlike then i havent manage to fix it using 5.1.0-SNAPSHOT and 5.1.0-beta.2 version. This is both logs and errors im curently facing:

> 
> USER_COMMENT=null
> PHONE_MODEL=Nexus 5X
> ANDROID_VERSION=7.1.2
> STACK_TRACE=java.lang.NullPointerException: Attempt to invoke interface method 'com.mapzen.android.lost.api.LocationAvailability com.mapzen.android.lost.internal.IFusedLocationProviderService.getLocationAvailability()' on a null object reference
> at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl$1$1.run(FusedLocationProviderApiImpl.java:51)
> at android.os.Handler.handleCallback(Handler.java:751)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at android.os.Looper.loop(Looper.java:154)
> at android.app.ActivityThread.main(ActivityThread.java:6121)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
> 
> CUSTOM_DATA=
> BRAND=google
> APP_VERSION_NAME=V1.1_b1.0.5
> 

> ANDROID_VERSION=7.1.2
> CUSTOM_DATA=
> APP_VERSION_NAME=V1.1_b1.0.5
> STACK_TRACE=java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.mapzen.android.lost.internal.FusedLocationProviderService$FusedLocationProviderBinder
> at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.onServiceConnected(FusedLocationProviderApiImpl.java:45)
> at com.mapzen.android.lost.internal.FusedLocationServiceConnectionManager.onServiceConnected(FusedLocationServiceConnectionManager.java:79)
> at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.onServiceConnected(FusedLocationProviderApiImpl.java:65)
> at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1453)
> at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1481)
> at android.os.Handler.handleCallback(Handler.java:751)
> at android.os.Handler.dispatchMessage(Handler.java:95)
> at android.os.Looper.loop(Looper.java:154)
> at android.app.ActivityThread.main(ActivityThread.java:6121)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
> 
> PHONE_MODEL=Nexus 5X
> BRAND=google
> USER_COMMENT=null

**Comment by tobrun** [comment]
@krsticdragan we are aware of the ongoing issues with the LOST dependency in our beta builds (this is being tracked in https://github.com/mapbox/mapbox-gl-native/issues/8999 & https://github.com/mapbox/mapbox-gl-native/issues/9068). We are waiting to see if this can be resolved with 2.3.0 else we need to revert to LOST 2.2.0. Thank you for the report, but closing this as a duplicate.

**Comment by krsticdragan** [comment]
Ok, thank you very much on your fast response @tobrun

**Comment by JigneshTank** [comment]
Hi there,

We are using the Mapbox for our product in Android Platform.

I am facing issue for method not found with following error:
java.lang.NoSuchMethodError: No interface method getLastLocation()Landroid/location/Location; in class Lcom/mapzen/android/lost/api/FusedLocationProviderApi; or its super classes (declaration of 'com.mapzen.android.lost.api.FusedLocationProviderApi' appears in /data/app/io.lattis.lattis.debug-2/base.apk:classes33.dex)

app gradle file to include mapbox:
compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.0@aar') {
        transitive = true
        exclude module: 'mapbox-java-geojson'
        exclude module: 'mapbox-android-telemetry'
    }

Application is crashing when I am writing below code:
android.location.Location lastLocation = locationEngine.getLastLocation();

Please give your guidance to overcome this problem.

Thanking you in advnace,
Jignesh

**Comment by tobrun** [comment]
you are probably inluding a newer version of LOST as 1.1.1, more information on trouble shooting dependencies in https://github.com/mapbox/mapbox-gl-native/issues/9408.

**Comment by JigneshTank** [comment]
Hi,

This works. Thank you for your instant help. I really appreciate it.

-Jignesh

**Comment by ctaggart** [comment]
@tobrun How do we know what the supported LOST version is? I appear to be using `3.0.4` and I am receiving similar crashes. https://github.com/mapbox/react-native-mapbox-gl/issues/1158
