### ISSUE TITLE
MGLLight.anchor should accept style functions

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#9085]
In #9043, `MGLLight.anchor` was typed as a raw `MGLLightAnchor`. It should be an MGLStyleValue because the anchor can be set to a style function. As it is, any functional anchor in the style JSON file will trip [this assertion](https://github.com/mapbox/mapbox-gl-native/pull/9043/files#diff-6e8c891babef8398cf6d15e3ca04b45aR51).

/cc @jfirebaugh @fabian-guerra @lbud

**Comment by fabian-guerra** [comment]
Fixed on https://github.com/mapbox/mapbox-gl-native/pull/9089
