### ISSUE TITLE
Generate MGLLight automatically from style specification

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#9086]
MGLLight.h and MGLLight.mm are hand-crafted but should be generated automatically from the style specification. This will help us avoid inconsistencies like #9085 and also future-proof the API for any future additions to this part of the style specification.

/ref #9043
/cc @fabian-guerra @ivovandongen

**Comment by ivovandongen** [comment]
Also take a look at what @tobrun is doing for Android: https://github.com/mapbox/mapbox-gl-native/pull/9013

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native/pull/9260
