### ISSUE TITLE
MGLLight missing from jazzy table of contents

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#9087]
#9043 added a couple new public APIs but didn’t [add them to the jazzy configuration file](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md#making-a-type-or-constant-public), so they appear under “Other Classes”, “Other Types”, etc.

/cc @fabian-guerra @jmkiley

**Comment by 1ec5** [comment]
Specifically, `MGLLightAnchor`, `MGLSphericalPosition`, `MGLSphericalPositionMake()`, and MGLLight were added to the public API. Not all of them need to be categorized, but MGLLight probably should be.

**Comment by jmkiley** [comment]
Added in #9111.
