### ISSUE TITLE
Reseting tracking mode with camera position change

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#9105]
**Platform:** Android
**Mapbox SDK version:** 5.1.0.beta.2

### Action
Changing zoom using:
`CameraPosition cameraPosition =
new CameraPosition.Builder(map.getCameraPosition()).zoom(newZoom).build();
map.easeCamera(CameraUpdateFactory.newCameraPosition(cameraPosition), duration, true, null);`
or
`map.animateCamera(CameraUpdateFactory.zoomTo(newZoom), duration);`

### Expected behavior
Change zoom and keep tracking mode.

### Actual behavior
Sometime tracking mode resets back from `TRACKING_FOLLOW` to `TRACKING_NONE` probably due to flag `TrackingSettings#isResetTrackingWithCameraPositionChange` being set to true when checking condition in `TrackingSettings#resetTrackingModesIfRequired(CameraPosition cameraPosition)`.

Might be connected with [#8738](https://github.com/mapbox/mapbox-gl-native/pull/8738)

**Comment by tobrun** [comment]
Source of this issue is related to posting animations to the message queue in  https://github.com/mapbox/mapbox-gl-native/pull/7000

**Comment by Guardiola31337** [comment]
Hey @LukasPaczos thanks for reaching out and reporting your problem.

This should be fixed with [#9133](https://github.com/mapbox/mapbox-gl-native/pull/9133). Would you be able to retest it?

**Comment by LukasPaczos** [comment]
@Guardiola31337 Hi, thanks for checking this out. I might have a moment later today to retest it.
