### ISSUE TITLE
Change priority of location tracking in MyLocationView

### ISSUE THREAD

**Issue by snowpong** [mapbox/mapbox-gl-native#9113]
**Platform:** Android
**Mapbox SDK version:** 5.x

### Steps to trigger behavior

 1. Use `setMyLocationEnabled(true)`

### Expected behavior

A sensible location accuracy depending on the phone state is selected.

### Actual behavior

It always uses `LocationEnginePriority.HIGH_ACCURACY`

### Suggestion

Allow us to specify the location priority.

Or, change behavior to only use `LocationEnginePriority.HIGH_ACCURACY` when the user if offline, otherwise scale down to `LocationEnginePriority.BALANCED_POWER_ACCURACY` since that works fine if mobile data / wifi is available.

Note: `LocationEnginePriority.HIGH_ACCURACY` forces the use of the GPS and draws the most battery (at least when using Google Play Services FusedLocationProviderApi). Also, `LocationEnginePriority.BALANCED_POWER_ACCURACY` doesn't work when the user is offline.

**Comment by tobrun** [comment]
MyLocationView is going to be replaced with [LocationLayer](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/locationlayer). Feel free to recreate this ticket in that repo.
