### ISSUE TITLE
removeAnnotation(s) crash when using subclass of MGLPolyline/MGLPolygon with Any? member

### ISSUE THREAD

**Issue by buganini** [mapbox/mapbox-gl-native#9123]
**Platform:**
iOS/Swift

**Mapbox SDK version:**
3.5.2

### Steps to trigger behavior

 1. Subclass MGLPolyline or MGLPolygon
 2. addAnnotation with instance of subclass
 3. removeAnnotation for the same instance

### Expected behavior
Annotation removed.

### Actual behavior
Crash.

Using MGLPolyline/MGLPolygon directly is fine.
Using subclassed MGLPointAnnocation is also fine.

**Comment by buganini** [comment]
Sample project: https://github.com/WhereIM/MapboxSample
![img_2316](https://cloud.githubusercontent.com/assets/72935/26532698/2de9f04e-443b-11e7-93f0-66bbaeef5a92.PNG)
There are 4 buttons: OrigPoly/OrigMarker/ExtendedPoly/ExtendedMarker
All of them will remove their own previous annotation and add a new one, OrigPoly/OrigMarker/ExtendedMarker are safe to click multiple times, but click on ExtendedPoly twice will crash.

**Comment by buganini** [comment]
Problem is gone if I comment out `var userData: Any?` in WimPolyline...
rename it doens't help.

Probably not a problem of mapbox itself but swift...

**Comment by buganini** [comment]
I just found out all my member variables in subclass is reset regardless of initial value.
Is it that all memory of the instance is reset by some obj-c code, including some runtime information for swift/arc ?

**Comment by incanus** [comment]
@jmkiley & I had a look at this @buganini and discovered that if your custom `userData` property on `WimPolyline` is an `AnyObject?`, there is no crash. We don't know why yet, but it's something to do with a Swift subclass of an Objective-C class (`MGLPolyline`) not being able to properly translate `Any` as a property.

**Comment by incanus** [comment]
We noticed that this doesn't happen with `Any` or `AnyObject` on the `MGLPointAnnotation` subclass, just on the `MGLPolyline` one. Looking at core differences in these classes, `MGLPolyline` makes use of `std::copy` for the internal `coordinates`, which may be a factor? The crash happens on this assignment: 

```swift
extendedPolyline = c
```

So when the object is copied, perhaps the combo of C++ `std::copy` internally and the `Any` blows up Swift somehow?

**Comment by incanus** [comment]
Update: perhaps not related to the `std::copy`, which is only for ranged coordinate replacement, but rather because all `MGLPolyline` have a `std::vector<CLLocationCoordinate2D>`, and *that* combined with `Any` is doing it?
