### ISSUE TITLE
Is it possible to turn off  https://events.mapbox.com/ logging in mapbox-android-services:2.1.0?

### ISSUE THREAD

**Issue by ragaisis** [mapbox/mapbox-gl-native#9125]
**Platform:**  Android
**Mapbox SDK version:** 5.1.0-beta2

After checking firebase performance tracking (beta) I saw that adding **mapbox-android-services:2.1.0@aar** as gradle dependency will send requests to **https://events.mapbox.com/****

The problem is that I'm using our custom map servers so I don't need access token from the mapbox. Instead we're using accessToken field for our custom confirmation in server side. But having wrong access token is the main problem of those unsuccessful requests (as i guess).

<img width="731" alt="screen shot 2017-05-29 at 08 33 32" src="https://cloud.githubusercontent.com/assets/2177892/26539259/26c89874-4454-11e7-8442-f6e4496a3ed9.png">

I need  **mapbox-android-services:2.1.0@aar** dependency because if I'll remove it, I could not use runtime styling, so those imports will be missing

```
import com.mapbox.services.commons.geojson.Feature;
 import com.mapbox.services.commons.geojson.FeatureCollection;
 import com.mapbox.services.commons.geojson.LineString; 
import com.mapbox.services.commons.models.Position; 

```

### Expected behavior

It would be nice to have possibility to turn off logging and sending data, because it distorts networking statistics. Or it's against Mapbox terms and conditions?

**Comment by Guardiola31337** [comment]
Hey @ragaisis 👋 
You're right. It's against Mapbox Terms of Service. More information below:

> Mapbox Telemetry is a [powerful location analytics platform](https://www.mapbox.com/telemetry/) included in this SDK. By default, anonymized location and usage data is sent to Mapbox whenever the host app causes it to be gathered. The [Mapbox Terms of Service](https://www.mapbox.com/tos/) require your app to provide users with a way to individually opt out of Mapbox Telemetry, which is provided automatically as part of the attribution control.

> Attribution
> You must comply with the licensing terms of any map data in your application, including [Mapbox Streets](https://www.mapbox.com/about/maps/) or other Mapbox maps if used. A small attribution control will be displayed on the map view automatically. [The attribution control](https://github.com/mapbox/mapbox-gl-native/blob/df07c99ddf3189d2ce503f86a846549f8a560bf6/android/java/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/views/MapView.java#L3097-L3141") may be moved or removed as necessary, so long as the required attribution is reasonably provided in your app.
> For more information on Mapbox’s attribution requirements, [click here](https://www.mapbox.com/help/attribution/).

Going ahead and close this as the question is answered.
Thanks for using Mapbox and feel free to open new tickets if you have any other questions 😉

**Comment by ParryQiu** [comment]
Have considered the usage scenarios of users' offline environment? 
There will always be errors in this request in the network request, how can the developer handle it?
