### ISSUE TITLE
Map not update after GeoJsonSource.setGeoJson()

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#9126]
**Platform:** Android
**Mapbox SDK version:** 5.1.0-beta.2, 5.1.0-beta.3 (not reproduce on 5.0.2 and 5.1.0-beta.1)

### Steps to trigger behavior

I animated SymbolLayer with GeoJsonSource.setGeoJson(): call it every 100-500 ms. 

### Expected behavior
Icons are animated and do not stop. 5.1.0-beta.1:
https://drive.google.com/open?id=0B1bUt15ODm_hVVFFQnktVThFZkE

### Actual behavior
Animation stops randomly. Continues after changing camera position. 5.1.0-beta.3:
https://drive.google.com/open?id=0B1bUt15ODm_hWWNmU3hRNjBKMHM

**Comment by tobrun** [comment]
The [example](https://www.mapbox.com/android-sdk/examples/add-live-realtime-data/) is working as expected though it's using `GeoJsonSource#seUrl()`.

**Comment by jfirebaugh** [comment]
This was fixed by #9303.
