### ISSUE TITLE
Making Mapbox GL Native (Mapbox Qt SDK) available for Windows

### ISSUE THREAD

**Issue by sfkeller** [mapbox/mapbox-gl-native#9134]
This is a feature request for a new platform (any future Mapbox SDK version):
I'd like to integrate Mapbox Qt SDK e.g. in QGIS which runs on many platforms too.
Are there plans to make Mapbox GL Native - especially Mapbox Qt SDK - available for Windows?
(I've heard, Esri did some work in ArcGIS Pro?).

**Comment by brunoabinader** [comment]
Hi @sfkeller - glad to see your interest in Mapbox Qt SDK :-)

We are now shipping a Mapbox GL GeoServices plugin, which provides a map that can be easily handled using QtLocation's QML Map. This is coming as part of Qt 5.9 LTS release, so you should be able to use it out of the box when downloading the Qt 5.9 SDK.

Windows support is currently limited to MingW + ANGLE - you can find more information on this thread: https://github.com/mapbox/mapbox-gl-native/issues/8429 - thanks!

**Comment by sfkeller** [comment]
Many thanks for your answer. 
MingW is bloated SW and out of the question to be bundled with the Windows binaries of QGIS. 
Did anyone ask Esri if they would contribute back their port in case they did some work in ArcGIS Pro?

**Comment by tmpsantos** [comment]
@sfkeller Mapbox Qt has now a MSVC Win64 build https://ci.appveyor.com/project/Mapbox/mapbox-gl-native/build/54/artifacts that could be used for a QGIS integration.

**Comment by sfkeller** [comment]
Thanks for pointing to this. We're already implemented a Mapbox Qt reader here: https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/issues/87 . I'd have to check if this makes a difference.
