### ISSUE TITLE
I quiet often receive memory warning.

### ISSUE THREAD

**Issue by CodeKunal** [mapbox/mapbox-gl-native#9135]
Platform:iOS10
Mapbox SDK version:3.5.4

### Steps to trigger behavior

 1.I have 2 viewcontroller in navigation stack. (Navigation controller -> controller1 -> controller2)
 2.Both controller 1 and controller 2 have mapview. Once I load mapview 1 in controller 1 I move to controller 2 mapview where I allow user to do freehand drawing using pan and touch gestures.   
 3. When the user is drawing I add custom annotation view and custom polyline on the map as overlay. But sometimes what happens is that the <b>user touches on the mapview are not recognised</b> and sometimes I do receive memory warnings(no crashes yet). Is this because I have 2 mapview loaded in the memory at the same time? And drawing(adding overlays) adds a lot to that memory? The debug navigator shows memory usage of more than 100 mb.  

Do I need to somehow unload controller 1 mapview when I am in controller 2 mapview to free up some memory? Please help me on how to get rid of these memory isuue.

PS Sorry for the way I might have presented my question. Please excuse my brevity.

**Comment by jfirebaugh** [comment]
⇢ #9203
