### ISSUE TITLE
[iOS] creating source from json string

### ISSUE THREAD

**Issue by ncryu2** [mapbox/mapbox-gl-native#9137]
First, I apologize for my poor English.
I do not know if I can ask you this question on this issues board, but...

I want to know how to create source from json string.

I know how to create source form url like this :

GLShapeSource *shapeSource = (MGLShapeSource*)[mglMapView.style sourceWithIdentifier:SOURCE_ID];
        if (shapeSource == nil) {
            shapeSource = [[MGLShapeSource alloc] initWithIdentifier: SOURCE_ID URL:[NSURL URLWithString:sourceUrlStr] options:nil];
}
...

but I don't know how to create source form a json string.

On android, I know how to create source from a json string like this:

GeoJsonSource  source = new GeoJsonSource(SOURCE_ID, string);

How can I create source from a json string on iOS?

**Platform:iOS
**Mapbox SDK version: 3.5.0

**Comment by frederoni** [comment]
You need to initialize an MGLShape with the GeoJSON data that you can use to initialize an MGLShapeSource. Something along these lines:
```objc
NSString *geoJSON = …
NSData *data = [geoJSON dataUsingEncoding:NSUTF8StringEncoding];
MGLShape *shape = [MGLShape shapeWithData:data encoding:NSUTF8StringEncoding error:NULL];
MGLShapeSource = [[MGLShapeSource alloc] initWithIdentifier:@"mysource" shape:shape options:nil];
```

Have a look at the examples for more information: https://www.mapbox.com/ios-sdk/examples/shape-collection/

**Comment by ncryu2** [comment]
Thank frederoni very much.

My geoJSON string has several features, but it seems to work fine because the shapeWithData method return MGLShapeCollectionFeature.
