### ISSUE TITLE
[iOS] adding a annotation(marker) with a sprite image

### ISSUE THREAD

**Issue by ncryu2** [mapbox/mapbox-gl-native#9150]
Thank for helping the other day. There is another question.

I want to know how to adding a annotation(marker) with a sprite image.

I know how to adding a annotation(marker) with custom image like this :

- (MGLAnnotationImage *)mapView:(MGLMapView *)mapView imageForAnnotation:(id <MGLAnnotation>)annotation
{
    if([annotation isKindOfClass:[CustomMarker class]]) {
        
        CustomMarker *marker = (CustomMarker *)annotation;
        
        // Try to reuse the existing annotation image, if it exists.
        MGLAnnotationImage *annotationImage = [mapView dequeueReusableAnnotationImageWithIdentifier:marker.name];
            if (!annotationImage)
            {
                UIImage *image = marker.img;
                annotationImage = [MGLAnnotationImage annotationImageWithImage:image reuseIdentifier:marker.name];
            }
        }
        
        marker.annotationImage = annotationImage;
        
        return annotationImage;
        
    }

    return nil;
    
}

but I don't know how to adding a annotation(marker) with sprite image.

How can I refer to sprite to return an sprite image on mapView:imageForAnnotation: method?

**Platform:iOS
**Mapbox SDK version: 3.5.0

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
