### ISSUE TITLE
Shareable offline databases between apps

### ISSUE THREAD

**Issue by pravishsainath** [mapbox/mapbox-gl-native#9152]
**Platform:** Android
**Mapbox SDK version:** 5.0.2

I am using the OfflineManager to cache the map tiles for a specified region.
It downloads the tiles and stores them into _mbgl-offline.db_ in the path _data/data/com.example.app/files_

**Is there a way to specify the path from which the map has to access the offline tiles to load?**

Currently there is only this meta-data field :
MapboxConstants.KEY_META_DATA_SET_STORAGE_EXTERNAL

It just uses a fixed path under the external storage directory.

I am implementing two different apps on an Android device, each of which use Mapbox maps. It would be convenient if I can set the file path for the maps on both apps to access a commonly saved _mbgl-offline.db_ so that the maps on both the apps can load tiles.  

This would avoid redundant map caching across both my apps.

**Comment by jfirebaugh** [comment]
Sorry, this isn't supported, and we're unlikely to add support for it. The reason being that if we had to support multiple applications simultaneously using the same database, it would limit what we can do in terms of in-memory caching for performance, and generally add complexity and potential concurrency issues.
