### ISSUE TITLE
[iOS] can't clear map removeAnnotations do not work properly

### ISSUE THREAD

**Issue by gulzatique** [mapbox/mapbox-gl-native#9160]
**Platform: xcode Version 8.3.2 (8E2002), ios swift 10.2 +
**Mapbox SDK version: latest one, i do not specify the version in pods

Hi 
I cannot remove all annotations from map.
Screenshot is provided: http://joxi.ru/8AnOOlvFq1774r

I tried codes like following: 
1) `if !points.isEmpty{
                    for point in points {
                    mapView.removeAnnotation(point as MGLAnnotation)
                    }
                }`
and `point : MGLPointAnnotation`

2) `func removeAllAnnotations() {
        
        guard let annotations = mapView.annotations else { return print("Annotations Error") }
        
        if annotations.count != 0 {
            for annotation in annotations {
                mapView.removeAnnotation(annotation)
            }
        } else {
            return
        }
    }`

3) `if let allmarkers = self.mapView.annotations {
                        if !allmarkers.isEmpty {
                            self.mapView.removeAnnotations(allmarkers)
                        }
                    }
`

they all work fine in terms of removing annotations but not views (those purple circles) from map itself. Although mapView.annotations shows nil, I still get views on map from the initial load.

I need to clear the map to show new set of annotations which user gets after applying filters

would highly appreciate any help

Update 1:
apparently it takes annotations from cache or something

I noticed that it clears the map but then again fills it with old annotations although I have removed annotations and sourceArray ob my objects on map

**Comment by boundsj** [comment]
Hi @gulzatique. I'm not seeing anything necessarily wrong with the example code you posted and I can't reproduce an issue like you describe. We did fix some issues with annotations recently and those fixes are in [iOS map SDK v3.6.0 beta 2](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.6.0-beta.2). Can you please try with that version and let us know if you still see the problem (instructions for using the beta with CocoaPods are in the release notes).

If you still see the problem after testing with beta 2, if you can provide an isolated sample project that reproduces the issue you see that would help speed up our investigation.

**Comment by gulzatique** [comment]
Sorry for taking your time, it was my mistake in the code
all the best

**Comment by binsnoel** [comment]
@gulzatique mind sharing what was your mistake here? I'm having the same problems. Thanks!
