### ISSUE TITLE
On Adreno 225 GPUs, only symbol layers are rendered

### ISSUE THREAD

**Issue by Namarcil** [mapbox/mapbox-gl-native#9164]
**Platform: Android 4.1.2**
**Mapbox SDK version: 5.1.0 beta.3**

### Steps to trigger behavior

When displaying map on a Motorola Razr HD on Android 4.1.2, the map is badly displayed.

### Expected behavior

Map tiles correctly displayed

### Actual behavior

Only label and images are displayed

![screenshot_2017-06-01-16-07-26](https://cloud.githubusercontent.com/assets/4331720/26684225/a565e7a6-46e6-11e7-9b6c-24d0074b5290.png)

![screenshot_2017-06-01-16-07-34](https://cloud.githubusercontent.com/assets/4331720/26684232/aa46c7cc-46e6-11e7-9869-eeb899e05f94.png)

![screenshot_2017-06-01-16-07-38](https://cloud.githubusercontent.com/assets/4331720/26684237/ad421ab2-46e6-11e7-95c7-fa12cb428645.png)

**Comment by mdakram** [comment]
Same with Samsung GT-19060.

**Comment by nevzorovsergey** [comment]
Same with Huawei U9508 (Android 4.2.2)

**Comment by danswick** [comment]
I have heard reports of this issue from a Ployer MOMO9 tablet running 4.1.1 as well. 

![image](https://user-images.githubusercontent.com/2365503/27463599-8b2f7742-577d-11e7-8a17-e5acac29bbd2.png)

**Comment by jfirebaugh** [comment]
Reported devices that use Adreno 22x GPUs and are probably the same as the original issue reported here:

* Motorola Razr HD -- Adreno 225
* Motorola DROID RAZR M -- Adreno 225
* Samsung Galaxy Tab (SC-01E) -- Adreno 220
* Samsung Galaxy Core Plus -- Adreno 203 or Adreno 220
* Samsung S3 -- Adreno 225

Reported devices that use some other GPU and are probably different issues:

* Samsung GT-19060 -- Mali-400MP2?
* Huawei U9508 -- Vivante GC4000
* Ployer MOMO9 -- SGX531

**Comment by jfirebaugh** [comment]
I reduced the issue to the following: on affected devices, if the depth range is anything other than {0, 1} at [the point where we render clipping masks](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/renderer/renderer_impl.cpp#L158-L189), then the draw calls for clipping masks will be affected by that depth range, _even though the depth test is disabled at that point_. This is clearly a driver issue, but easy enough to work around.
