### ISSUE TITLE
Remove verbose logging

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#917]
As we approach Android GL beta I need to remove the verbose loggin I have added for debugging various bugs.

**Comment by bleege** [comment]
Is this still an issue?

**Comment by ljbade** [comment]
I don't think so logging level seems OK for now.

You find any issues with the logging amount @bleege?

**Comment by bleege** [comment]
Nope.  Just wondering as this ticket had been open for awhile.  Let's close it now and if things get out of hand Log wise we can address it then.
