### ISSUE TITLE
Localization issue: German translations of city is wrong

### ISSUE THREAD

**Issue by evgzor** [mapbox/mapbox-gl-native#9171]
**iOS and Android:**
**3.5.4 / 5.0**

### Steps to trigger behavior

 1. Switch to the German localization
 2. Navigate to Germany - Cities (Munich, Cologne)
 3. Observe the result

### Expected behavior
Mapbox is displaying the names of Cities (München, Köln) in German.
### Actual behavior
Mapbox is displaying the names of some Cities (Munich, Cologne) in English.

<img width="362" alt="screenshot 2017-06-02 10 40 34" src="https://cloud.githubusercontent.com/assets/5227456/26716437/02a47176-4782-11e7-8558-a786eb961486.png">

**Comment by jfirebaugh** [comment]
Map labels are not automatically localized. This feature is being tracked in #7031.

**Comment by 1ec5** [comment]
In the meantime, see this example code that automatically localizes into the user’s locale:

https://github.com/mapbox/mapbox-gl-native/blob/66c2a2a0b7c42e1947f57a412ece66fa8eaac149/platform/macos/app/MapDocument.m#L346-L393
https://github.com/mapbox/mapbox-gl-native/blob/66c2a2a0b7c42e1947f57a412ece66fa8eaac149/platform/macos/app/MGLVectorSource+MBXAdditions.m

mapbox/mapbox-plugins-ios#2 tracks building a plugin that encapsulates this code, but for now, you can manually incorporate it into your application.

**Comment by evgzor** [comment]
@1ec5  I have no access to https://github.com/mapbox/mapbox-plugins-ios/issues/2
could u provide it?

**Comment by 1ec5** [comment]
Not much to see there yet. 😉 But we’re working on it and will open it up as soon as there’s something usable. In the meantime, please try copying the source code linked above.
