### ISSUE TITLE
Overlapping mapview in backstack fragment

### ISSUE THREAD

**Issue by giperwlad** [mapbox/mapbox-gl-native#9175]
Hello and thanks for contributing!

I created fragment with mapview. And added another fragment to backStack with another mapview.

And On the upper fragment Shows the map from the bottom fragment (as in the screenshots).

bottom fragment:
![c596fa4f-3146-4127-90d1-ff8a00935b1b png](https://cloud.githubusercontent.com/assets/20104243/26723933/880827c8-479f-11e7-922c-95c60905cd54.png)

upper fragment:
![ff215a08-4a1e-4b92-bbae-c1554bc367c8 png](https://cloud.githubusercontent.com/assets/20104243/26723936/8c489a52-479f-11e7-9e2c-21fec2f5f361.png)

Mapbox SDK version: 5.1.0-SNAPSHOT

Steps to trigger behavior

 1. Add mapview to first fragment
 2. Add mapview to second fragment
 3. Show first fragment
 4. Add to backstack second fragment

  I use support fragments.

`    MyFragment myFragment = new MyFragment();
        myFragment.setArguments(bundle);
        ((AppCompatActivity) context).getSupportFragmentManager().beginTransaction()
                .add(R.id.fragment, myFragment, MyFragment.class.getName())
                .addToBackStack(MyFragment.class.getName())
                .commit();`

**Comment by tobrun** [comment]
@giperwlad thank you for reaching out. In your code your are adding the fragment to a container instead of replacing the current one. This results in adding an additional viewhierachy on the already existing one and with the way SurfaceView works shows 2 surfaces. This should be resolved be replacing the fragment. Closing for now. Let us know if you have any other questions.

**Comment by hp-harsh** [comment]
@tobrun 
I am facing the same issue while adding a Fragment. To cope up with my functionality I must have to add Fragment instead of replacing one. Do you any hack or idea to deal with this issue?

**Comment by tobrun** [comment]
Using a textureview instead of glsufaceview will work for those use-cases. A textureview can be seen as part of the viewhierachy. This can be enabled through XML or with mapboxmapoptions
