### ISSUE TITLE
Mapbox Crash on Samsung galaxy tab 3

### ISSUE THREAD

**Issue by hchy9777** [mapbox/mapbox-gl-native#9176]
**Platform:android
**Mapbox SDK version:5.0.2

Mapbox crash on my device(samsung galaxy tab3,android 4.2.2,cpu:x86)

this is the crash log,wish it is helpful for you.
`# main(1)
SIGSEGV(UNKNOWN_SIGSEGV)
解析原始
1 #00 pc 0001c6d0 /data/app-lib/cn.fishtrip.apps.citymanager-1/libmapbox-gl.so [x86::5a83bbe0d3d9d938e7bda5ed0260d090]
2 #01 pc 00081690 /data/app-lib/cn.fishtrip.apps.citymanager-1/libmapbox-gl.so [x86::5a83bbe0d3d9d938e7bda5ed0260d090]
3 #02 pc 00061f98 /data/app-lib/cn.fishtrip.apps.citymanager-1/libmapbox-gl.so [x86::5a83bbe0d3d9d938e7bda5ed0260d090]
4 #03 pc 000754f7 /data/app-lib/cn.fishtrip.apps.citymanager-1/libmapbox-gl.so [x86::5a83bbe0d3d9d938e7bda5ed0260d090]
5 #04 pc 00075553 /data/app-lib/cn.fishtrip.apps.citymanager-1/libmapbox-gl.so [x86::5a83bbe0d3d9d938e7bda5ed0260d090]
6 #05 pc 0006809f /system/lib/libdvm.so (dvmPlatformInvoke+79) [x86::e41ff87970d732ee531d2bbc311145ff]
7 #06 pc 000b90c3 /system/lib/libdvm.so (_Z16dvmCallJNIMethodPKjP6JValuePK6MethodP6Thread+563) [x86::e41ff87970d732ee531d2bbc311145ff]
8 #07 pc 63f7e118 <unknown>
9 #08 pc 00077d4b /system/lib/libdvm.so (_Z12dvmInterpretP6ThreadPK6MethodP6JValue+203) [x86::e41ff87970d732ee531d2bbc311145ff]
10 #09 pc 000e6808 /system/lib/libdvm.so (_Z15dvmInvokeMethodP6ObjectPK6MethodP11ArrayObjectS5_P11ClassObjectb+2008) [x86::e41ff87970d732ee531d2bbc311145ff]
11 #10 pc 000f85d9 /system/lib/libdvm.so [x86::e41ff87970d732ee531d2bbc311145ff]
12 #11 pc 001adeec /system/lib/libdvm.so [x86::e41ff87970d732ee531d2bbc311145ff]
13 #12 pc 00077d4b /system/lib/libdvm.so (_Z12dvmInterpretP6ThreadPK6MethodP6JValue+203) [x86::e41ff87970d732ee531d2bbc311145ff]
14 #13 pc 000e56cf /system/lib/libdvm.so (_Z14dvmCallMethodVP6ThreadPK6MethodP6ObjectbP6JValuePc+687) [x86::e41ff87970d732ee531d2bbc311145ff]
15 #14 pc 000ae134 /system/lib/libdvm.so [x86::e41ff87970d732ee531d2bbc311145ff]
16 #15 pc 0005a84a /system/lib/libandroid_runtime.so (_ZN7_JNIEnv20CallStaticVoidMethodEP7_jclassP10_jmethodIDz+42) [x86::f8f7a60aa9247f683b15393e8dc43470]
17 #16 pc 0005c420 /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcS2_+944) [x86::f8f7a60aa9247f683b15393e8dc43470]
18 #17 pc 00000fef /system/bin/app_process [x86::6484ee45ecf543d5009f521fd853d0f7]
19 #18 pc 0002afd5 /system/lib/libc.so (__libc_init+69) [x86::0564fea6828b7abb039ab56b5901bf91]
20 #19 pc 00000a8c /system/bin/app_process [x86::6484ee45ecf543d5009f521fd853d0f7]
21 java:
22 com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddMarkers(Native Method)
23 com.mapbox.mapboxsdk.maps.NativeMapView.addMarker(NativeMapView.java:504)
24 com.mapbox.mapboxsdk.maps.AnnotationManager.addMarkerViews(AnnotationManager.java:247)
25 com.mapbox.mapboxsdk.maps.MapboxMap.addMarkerViews(MapboxMap.java:1138)
26 cn.fishtrip.apps.citymanager.ui.home.MapFragment$1.handleMessage(MapFragment.java:185)
27 android.os.Handler.dispatchMessage(Handler.java:99)
28 android.os.Looper.loop(Looper.java:176)
29 android.app.ActivityThread.main(ActivityThread.java:5279)
30 java.lang.reflect.Method.invokeNative(Native Method)
31 java.lang.reflect.Method.invoke(Method.java:511)
32 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
33 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
34 dalvik.system.NativeStart.main(Native Method)# main(1)
SIGSEGV(UNKNOWN_SIGSEGV)
解析原始
1 #00 pc 0001c6d0 /data/app-lib/cn.fishtrip.apps.citymanager-1/libmapbox-gl.so [x86::5a83bbe0d3d9d938e7bda5ed0260d090]
2 #01 pc 00081690 /data/app-lib/cn.fishtrip.apps.citymanager-1/libmapbox-gl.so [x86::5a83bbe0d3d9d938e7bda5ed0260d090]
3 #02 pc 00061f98 /data/app-lib/cn.fishtrip.apps.citymanager-1/libmapbox-gl.so [x86::5a83bbe0d3d9d938e7bda5ed0260d090]
4 #03 pc 000754f7 /data/app-lib/cn.fishtrip.apps.citymanager-1/libmapbox-gl.so [x86::5a83bbe0d3d9d938e7bda5ed0260d090]
5 #04 pc 00075553 /data/app-lib/cn.fishtrip.apps.citymanager-1/libmapbox-gl.so [x86::5a83bbe0d3d9d938e7bda5ed0260d090]
6 #05 pc 0006809f /system/lib/libdvm.so (dvmPlatformInvoke+79) [x86::e41ff87970d732ee531d2bbc311145ff]
7 #06 pc 000b90c3 /system/lib/libdvm.so (_Z16dvmCallJNIMethodPKjP6JValuePK6MethodP6Thread+563) [x86::e41ff87970d732ee531d2bbc311145ff]
8 #07 pc 63f7e118 <unknown>
9 #08 pc 00077d4b /system/lib/libdvm.so (_Z12dvmInterpretP6ThreadPK6MethodP6JValue+203) [x86::e41ff87970d732ee531d2bbc311145ff]
10 #09 pc 000e6808 /system/lib/libdvm.so (_Z15dvmInvokeMethodP6ObjectPK6MethodP11ArrayObjectS5_P11ClassObjectb+2008) [x86::e41ff87970d732ee531d2bbc311145ff]
11 #10 pc 000f85d9 /system/lib/libdvm.so [x86::e41ff87970d732ee531d2bbc311145ff]
12 #11 pc 001adeec /system/lib/libdvm.so [x86::e41ff87970d732ee531d2bbc311145ff]
13 #12 pc 00077d4b /system/lib/libdvm.so (_Z12dvmInterpretP6ThreadPK6MethodP6JValue+203) [x86::e41ff87970d732ee531d2bbc311145ff]
14 #13 pc 000e56cf /system/lib/libdvm.so (_Z14dvmCallMethodVP6ThreadPK6MethodP6ObjectbP6JValuePc+687) [x86::e41ff87970d732ee531d2bbc311145ff]
15 #14 pc 000ae134 /system/lib/libdvm.so [x86::e41ff87970d732ee531d2bbc311145ff]
16 #15 pc 0005a84a /system/lib/libandroid_runtime.so (_ZN7_JNIEnv20CallStaticVoidMethodEP7_jclassP10_jmethodIDz+42) [x86::f8f7a60aa9247f683b15393e8dc43470]
17 #16 pc 0005c420 /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcS2_+944) [x86::f8f7a60aa9247f683b15393e8dc43470]
18 #17 pc 00000fef /system/bin/app_process [x86::6484ee45ecf543d5009f521fd853d0f7]
19 #18 pc 0002afd5 /system/lib/libc.so (__libc_init+69) [x86::0564fea6828b7abb039ab56b5901bf91]
20 #19 pc 00000a8c /system/bin/app_process [x86::6484ee45ecf543d5009f521fd853d0f7]
21 java:
22 com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddMarkers(Native Method)
23 com.mapbox.mapboxsdk.maps.NativeMapView.addMarker(NativeMapView.java:504)
24 com.mapbox.mapboxsdk.maps.AnnotationManager.addMarkerViews(AnnotationManager.java:247)
25 com.mapbox.mapboxsdk.maps.MapboxMap.addMarkerViews(MapboxMap.java:1138)
26 cn.fishtrip.apps.citymanager.ui.home.MapFragment$1.handleMessage(MapFragment.java:185)
27 android.os.Handler.dispatchMessage(Handler.java:99)
28 android.os.Looper.loop(Looper.java:176)
29 android.app.ActivityThread.main(ActivityThread.java:5279)
30 java.lang.reflect.Method.invokeNative(Native Method)
31 java.lang.reflect.Method.invoke(Method.java:511)
32 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
33 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
34 dalvik.system.NativeStart.main(Native Method)`

**Comment by Guardiola31337** [comment]
@hchy9777 thanks for reaching out and reporting your problem.
Do you have a minimal example to reproduce the crash? If there is any sample or pseudo code you can provide, that would also be helpful.

**Comment by tobrun** [comment]
@hchy9777 without having any steps to reproduce or a symbolicated stack trace this issue is non actionable. Please let us know if you have any additional information. Closing for now.
