### ISSUE TITLE
Snapshot with markers

### ISSUE THREAD

**Issue by s3r6** [mapbox/mapbox-gl-native#9179]
**Platform: Android 4.4.4**
**Mapbox SDK version: Mapbox 5.0.2**

Snapshot #3466 taken does not contain markers that are MarkerViews and info windows above them. How can I take snapshot with markers?

**Comment by Reakleases** [comment]
agree same issue on android 5.1

**Comment by s3r6** [comment]
I tried to `getDrawableCache` from `MapView` to get bitmap with markers. 

1. Clicked on map to place the marker.
2. Bitmap created OK, but when I leave the activity #6647 `eglSwapBuffers` error occurs.

**Comment by sibuty** [comment]
Agree with this issue.
Very urgent task for me.
up

**Comment by tobrun** [comment]
If this is a high requirement you can work around this issue for now by opting in to use TexureView as a rendering surface. You can use this feature through xml or MapboxMapOptions. After you need to get a reference to TextureView and execute: `textureView.getBitmap();`

To resolve this issue for SurfaceView we will need to draw all overlain views to a bitmap and merge that bitmap with the current snapshotted bitmap.

**Comment by tobrun** [comment]
Been working on this, and was able to get it working with merging a bitmap of the snapshot with a bitmap of the View hierarchy. If needed you can use the following methods to work around the issue yourself:

```java
  public static Bitmap createBitmapFromView(@NonNull View view) {
    view.setDrawingCacheEnabled(true);
    view.setDrawingCacheQuality(View.DRAWING_CACHE_QUALITY_LOW);
    view.buildDrawingCache();

    if (view.getDrawingCache() == null) {
      return null;
    }

    Bitmap snapshot = Bitmap.createBitmap(view.getDrawingCache());
    view.setDrawingCacheEnabled(false);
    view.destroyDrawingCache();
    return snapshot;
  }

  public static Bitmap mergeBitmap(@NonNull Bitmap background, @NonNull Bitmap foreground) {
    Bitmap result = Bitmap.createBitmap(background.getWidth(), background.getHeight(), background.getConfig());
    Canvas canvas = new Canvas(result);
    canvas.drawBitmap(background, 0f, 0f, null);
    canvas.drawBitmap(foreground, 10, 10, null);
    return result;
  }
```

What you need to do is call into `createBitmapFromView` with `mapView` and call into `mergeBitmap` with the `bitmap` from the callback and the `bitmap` from `createBitmapFromView`

**Comment by tobrun** [comment]
![device-2017-06-13-102956](https://user-images.githubusercontent.com/2151639/27073325-b8a159d6-5023-11e7-871f-5eba5c8346ae.png)

**Comment by s3r6** [comment]
I used similar code 

```java
public void getScreenShotWithViews(MapboxMap.SnapshotReadyCallback snapshotReadyCallback) {
    if (mapboxMap != null) {
      mapView.setDrawingCacheEnabled(true);
      Bitmap drawingCache = mapView.getDrawingCache();
      MapboxMap.SnapshotReadyCallback cb = new MapboxMap.SnapshotReadyCallback() {
        @Override
        public void onSnapshotReady(Bitmap snapshot) {
          Bitmap bmOverlay =
              Bitmap.createBitmap(snapshot.getWidth(), snapshot.getHeight(), snapshot.getConfig());
          Canvas canvas = new Canvas(bmOverlay);
          canvas.drawBitmap(snapshot, new Matrix(), null);
          canvas.drawBitmap(drawingCache, new Matrix(), null);
          mapView.setDrawingCacheEnabled(false);
          snapshotReadyCallback.onSnapshotReady(bmOverlay);
        }
      };
      mapboxMap.snapshot(cb);
    }
  }
```

It works, but need to call `mapView.getDrawingCache()` before getting snapshot. If to call inside `SnapshotReadyCallback` got `eglSwapBuffers` error.

**Comment by tobrun** [comment]
Adding this to the 5.1.0 milestone
