### ISSUE TITLE
ImageView rotation requires Android 4.0

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#918]
The Android linter is complaining that ImageView.rotate() is only available after Android 4.0. Currently this is used to rotate the compass on the corner of the map and for the GPS marker.

An alternative is needed for the app to work on Android 2.0. Otherwise I could just disable rotation on older Android.

@bleege What do you think?

**Comment by incanus** [comment]
I don't know the APIs, but here are two ideas: 

1. Yes, just drop it the compass on older Android. For example, iOS didn't have the compass until iOS 6 (when Apple switch from Google) in 2012. 

1. Draw the image in a rotated graphics context and use that, i.e. don't rotate the image, but rather draw a new one for each angle needed on the fly. Maybe a dumb idea.

**Comment by ljbade** [comment]
I was thinking idea 2, but it would require a bit of effort and wasn't sure if I should bother.

If we decide to go the marker overlay route and move the GPS marker into MapView itself then we will likely use a graphics context to draw the markers.

**Comment by bleege** [comment]
@ljbade I don't see the `ImageView.rotate()` method in the Android JavaDocs so I can't speak to this particular issue.

That said the bridge to the Android Animation API gap is [NineOldAndroids](http://nineoldandroids.com) by Jake Wharton.  It's a mirror of the Animation API for the older Android Versions (hence the name).  It auto-detects the version of Android the app is running on and will use the stock Android Animation API if it's available and if not it'll use its ported version.  It's worked as desired on the Mapbox Android SDK.

**Comment by ljbade** [comment]
Interesting I will try that lib.

**Comment by mb12** [comment]
You can use ImageView.setImageMatrix to rotate image as well. Its available since API 1.

http://stackoverflow.com/questions/8981845/androidrotate-image-in-imageview-by-an-angle
