### ISSUE TITLE
Wrong route

### ISSUE THREAD

**Issue by Slik1002** [mapbox/mapbox-gl-native#9188]
**Platform:** Android
**Mapbox SDK version:** 5.0.2

I have a problem with routes. If I want add route through 180th meridians the route is breaking.

### Steps to trigger behavior

 1. Add few points: 
**mapboxMap.addPolyline(new PolylineOptions().add(points).color(color).width(3));**

### Expected behavior
The right route is being built.

### Actual behavior
The wrong route is being built
![example](https://cloud.githubusercontent.com/assets/10289384/26784223/2399f79a-4a05-11e7-832b-5240478b3834.png)

**Comment by Guardiola31337** [comment]
@Slik1002 thank you for reaching out and reporting your problem.

Could you add some more information on how you're defining the points? Do you have a minimal example? If there is any sample or pseudo code you can provide, that would also be helpful.

**Comment by Slik1002** [comment]
@Guardiola31337 I have the next array of points:

> Lon: 114.5983333333, Lat: -28.7733333333
> Lon: 114.5965333333, Lat: -28.7556833333
> Lon: 114.5283333333, Lat: -28.77
> Lon: 114.508450160814, Lat: -28.7748351847631
> Lon: 113.955, Lat: -29.22
> Lon: 113.2133333333, Lat: -28.79
> Lon: 112.4033333333, Lat: -25.5233333333
> Lon: 113.4166666667, Lat: -21.6683333333
> Lon: 122.1933333333, Lat: -10.9533333333
> Lon: 122.8933333333, Lat: -9.405
> Lon: 125.195, Lat: -8.4433333333
> Lon: 125.3166666667, Lat: -8.25
> Lon: 125.8633333333, Lat: -7.2333333333
> Lon: 127.2716666667, Lat: -4.575
> Lon: 127.4616666667, Lat: -3.5
> Lon: 127.2533333333, Lat: -3.1066666667
> Lon: 129.5033333333, Lat: -1.47
> Lon: 130.01, Lat: -1.2983333333
> Lon: 130.555, Lat: -0.9533333333
> Lon: 130.6416666667, Lat: -0.93
> Lon: 130.696983333333, Lat: -0.908816666666667
> Lon: 131.0433333333, Lat: -0.8333333333
> Lon: 131.145, Lat: -0.775
> Lon: 145.3216666667, Lat: 9.3983333333
> Lon: -178.75, Lat: 29.2666666667
> Lon: -124.984489779846, Lat: 34.2189607700184
> Lon: -124.984489779846, Lat: 34.2189607700184
> Lon: -121.1150333333, Lat: 33.63035
> Lon: -120.681168156573, Lat: 33.634640636726

and I add this array to route:
```
mapboxMap.addPolyline(new PolylineOptions()
                        .add(points)
                        .color(color)
                        .width(3));
```

**Comment by jfirebaugh** [comment]
Hi @Slik1002, thanks for using Mapbox. If you want to create a line that crosses the antimeridian, part of the line needs to use longitude coordinates greater than ±180°, e.g [182.75, 29.26] rather than [-178.75, 29.26]. That's the mechanism used to distinguish a line that crosses the antimeridian from a line that doubles back (after all, someone might want to plot either one).
