### ISSUE TITLE
Question: Raster entire map & export to pngs

### ISSUE THREAD

**Issue by AndrewDelposen** [mapbox/mapbox-gl-native#9189]
Greetings,

I am having  a lot of trouble figuring out exactly how you guys manged to get the raster images. I would love to be able to have the ability to push through a vector map and a json style to then get pngs of everything. tileserver-gl used this as a native to generate in raster form, but I need the actual pngs of everything.

Many Thanks

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
