### ISSUE TITLE
v4 raster layers load with low-resolution tiles on high-resolution screens

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#919]
#916 removed a special case for HiDPI that bumped up the zoom level, the idea being that vector tiles have a sufficiently high resolution that the HiDPI experience wouldn’t suffer. But this same code runs for raster layers. Now the Satellite layer is half as sharp:

![before](https://cloud.githubusercontent.com/assets/1231218/6382268/156e046a-bcfc-11e4-8fb4-5a84c4421e23.png) ![after](https://cloud.githubusercontent.com/assets/1231218/6382269/156e3c8c-bcfc-11e4-8810-fc6b5f37d0d8.png)

**Comment by 1ec5** [comment]
It should be possible to stick a “{ratio}” somewhere in the URL so that `TileData::request()` will insert `@2x`. The 2x variant does at least exist for mapbox.satellite – can we depend on its existence in general?

**Comment by incanus** [comment]
Yes, `@2x` is supported for any Mapbox-hosted raster tile. If it's a custom tile that's uploaded not from OSM-based stuff, it'll fail silently, but for everything else, [it'll work](https://www.mapbox.com/developers/api/maps/#format).

**Comment by 1ec5** [comment]
@incanus how silently? Will we need to fall back to a 1× URL or will mapbox just return a 1× tile anyways?

**Comment by incanus** [comment]
The latter. I'd say supporting non-auto-retina raster tiles in GL is not a major use case so this is fine.

**Comment by jfirebaugh** [comment]
All Mapbox v4 raster tiles support @2x.

Relevant JS code: [1](https://github.com/mapbox/mapbox-gl-js/blob/1c23ac3845bea760102b0e7d06e10febabdb7bee/js/util/mapbox.js#L61-L65), [2](https://github.com/mapbox/mapbox-gl-js/blob/1c23ac3845bea760102b0e7d06e10febabdb7bee/js/source/raster_tile_source.js#L41)

**Comment by incanus** [comment]
I'm talking about such cases as this [`justin.NACIS2012`](https://api.tiles.mapbox.com/v4/justin.NACIS2012/page.html?access_token=pk.eyJ1IjoianVzdGluIiwiYSI6Ijh1RmhSN2cifQ.-R7zSJ3glf2uXy5XzMWYnA#17/45.53070/-122.65550), which I created in TileMill and uploaded rasters of. 

`1x`: 

![](https://b.tiles.mapbox.com/v4/justin.NACIS2012/17/20878/46875.png?access_token=pk.eyJ1IjoianVzdGluIiwiYSI6Ijh1RmhSN2cifQ.-R7zSJ3glf2uXy5XzMWYnA)

`2x`:

![](https://b.tiles.mapbox.com/v4/justin.NACIS2012/17/20878/46875@2x.png?access_token=pk.eyJ1IjoianVzdGluIiwiYSI6Ijh1RmhSN2cifQ.-R7zSJ3glf2uXy5XzMWYnA)

So, the sizing is just naively blown up, but the URL works. 

I'd be on the creator to create a `2x` good-looking version (which I did at [`justin.NACIS2012Retina`](https://api.tiles.mapbox.com/v4/justin.NACIS2012Retina/page.html?access_token=pk.eyJ1IjoianVzdGluIiwiYSI6Ijh1RmhSN2cifQ.-R7zSJ3glf2uXy5XzMWYnA#17/45.53070/-122.65550)).
