### ISSUE TITLE
Adding multiple polygons on runtime

### ISSUE THREAD

**Issue by moax** [mapbox/mapbox-gl-native#9190]
I want to read data on runtime into an array and display it as multiple polylines. With the data I created a PolyLineFeature and added multiple of them into an Array ASPShape.
With this array, I created an MGLShapeSource and added it to the map, but I don't know how to display the data on the map. 

  var ASPShape = [MGLPolylineFeature]()
          coordinatesPoly.append(CLLocationCoordinate2D(latitude: CLLocationDegrees(csvRows[i][1])!, longitude: CLLocationDegrees(csvRows[i][0])!))
            
         var coordinates = coordinatesPoly
         let Lines = MGLPolylineFeature(coordinates: &coordinates, count: UInt(coordinates.count))
         ASPShape.append(Lines)
         let source = MGLShapeSource(identifier: "lines", features: ASPShape, options: nil)
         MapView.style?.addSource(source)
        
I would like to have different styles for different categories of the polylines to hide them if needed. How can I get the data displayed and how can I set a zoom filter on it? Thanks in advance

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
