### ISSUE TITLE
iOS:Union of multiple overlapping polygons to from single polygon.

### ISSUE THREAD

**Issue by CodeKunal** [mapbox/mapbox-gl-native#9193]
**Platform:iOS10
**Mapbox SDK version:Latest SDK version
Hi is there a way we could get the <b>Union</b> of multiple overlapping polygons to form single polygon(holes allowed in final polygon). Though individual polygons don't have holes?
Basically I need to find intersection points so that I could form a new polygon with the intersection points and old individual corner points(excluding points within other polygons).Thanks.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
