### ISSUE TITLE
iOS: Offline pack progress status

### ISSUE THREAD

**Issue by CristianSerea** [mapbox/mapbox-gl-native#9195]
Hi guys, i just downloaded some packs from mapbox platform...
I want to list them and get their progress info

` 

    for (MGLOfflinePack *pack in [[MGLOfflineStorage sharedOfflineStorage] packs]) {

        NSDictionary *userInfo = [NSKeyedUnarchiver unarchiveObjectWithData:pack.context];

        NSLog(@"Offline PackName: %@ ResourcesCompleted: %llu TilesCompleted: %llu PackState: %ld BytesCompleted: %llu Error: %@ Error: %@",

              userInfo[@"name"],

              pack.progress.countOfResourcesCompleted,

              pack.progress.countOfTilesCompleted,

              (long)pack.state,

              pack.progress.countOfBytesCompleted,

              userInfo[MGLOfflinePackUserInfoKeyError],

              userInfo[MGLOfflinePackErrorNotification]);

    }
`

so after i downloaded the new pack i just use this piece of code and get all details about pack that are good...this is the log

Offline PackName: ParisPack ResourcesCompleted: 2548 TilesCompleted: 1264 PackState: 3 BytesCompleted: 101517807 Error: (null) Error: (null)

ISSUE:
problem appear when i close and restart the app again, all infos about pack are 0 or null, and no error :(

Offline PackName: ParisPack ResourcesCompleted: 0 TilesCompleted: 0 PackState: 0 BytesCompleted: 0 Error: (null) Error: (null)

Does anyone have an idea what is happening the second time?
Thanks

**Comment by jfirebaugh** [comment]
You need to call [`-[MGLOfflinePack requestProgress]`](https://www.mapbox.com/ios-sdk/api/3.5.4/Classes/MGLOfflinePack.html#/MGLOfflinePack). From the documentation for this method:

> The state and progress of an inactive or completed pack are computed lazily. If you need the state or progress of a pack whose state property is currently set to `MGLOfflinePackStateUnknown`, observe KVO change notifications on this pack’s `state` key path, then call this method.

**Comment by CristianSerea** [comment]
thanks man, awesome :)
