### ISSUE TITLE
iOS: Offline Pack size issue after deleting

### ISSUE THREAD

**Issue by CristianSerea** [mapbox/mapbox-gl-native#9206]
Hi guys...i just downloaded a pack for a city and after the pack is complete download i got infos about it and all is fine. 

Offline PackName ResourcesCompleted: 1624 TilesCompleted: 340 PackState: 2 BytesCompleted: 80,3 MB

my app has 10 mb and after pack downloading has 96 mb (10app + 86 documents and data)...good

next i tried to delete this pack with [[MGLOfflineStorage sharedOfflineStorage] removePack:pack  withCompletionHandler:nil] but the app size now is 60 mb (10 app + 50 documents and data)
Where come from those 50 mb?

Can anyone help me or give me an advice about pack remove method or app size issue?

**Comment by jfirebaugh** [comment]
See the [documentation](https://www.mapbox.com/help/mobile-offline/#removing-offline-regions):

> When you remove an offline region, any resources that are required by that region, but not other regions, become eligible for removal from the offline database. Because the offline database is also used as a general purpose cache for map resources, such resources may not be immediately removed if the implementation determines that they remain useful for general performance of the map.

**Comment by CristianSerea** [comment]
hmm...ok...but this is weird...cause user maybe want to delete the pack with 86 mb and then when he looks in settings storage would see that app still has 60 mb from deleted pack...

there is no solutions to delete entire pack with all resources? maybe i don't want to improve performance of the map with the remaining resources :)

**Comment by asifjavaid** [comment]
Hi Guys,

We are using MapBox iOS SDK version 4.10. But we are still facing the same issue in our aap. Can you please guide us how to remove entire pack with entire resources? 

Thank you.

--
Regards,
Asif Javaid.
