### ISSUE TITLE
Lint error

### ISSUE THREAD

**Issue by thomas-huet** [mapbox/mapbox-gl-native#921]
When running `make android` on 380fd1fbf4c8d148bb231a99007498713a07829f, I have the following error:

```
:MapboxGLAndroidSDK:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':MapboxGLAndroidSDK:lint'.
> Lint found errors in the project; aborting build.
```

The reported lint error is:

>InvalidPackage: Package not included in Android
>../../../../../../../.gradle/caches/modules-2/files-2.1/com.squareup.okio/okio/1.2.0/c0b52915a48fa91b1b94a28d4a2997bac5f524df/okio-1.2.0.jar: Invalid package reference in library; not included in Android: java.nio.file. Referenced from okio.Okio.
>Priority: 6 / 10
>Category: Correctness
>Severity: Error
>Explanation: Package not included in Android.
>This check scans through libraries looking for calls to APIs that are not included in Android.
>
>When you create Android projects, the classpath is set up such that you can only access classes in the API packages that are included in Android. However, if you add other projects to your libs/ folder, there is no guarantee that those .jar files were built with an Android specific classpath, and in particular, they could be accessing unsupported APIs such as java.applet.
>
>This check scans through library jars and looks for references to API packages that are not included in Android and flags these. This is only an error if your code calls one of the library classes which wind up referencing the unsupported package.
>
>More info:
>
>To suppress this error, use the issue id "InvalidPackage" as explained in the Suppressing Warnings and Errors section.

**Comment by ljbade** [comment]
We are adding an exception to ignore this error in the android-conversions branch, since we can't do much to fix this in OkHTTP.
