### ISSUE TITLE
Artefacts if I switch to offline mode

### ISSUE THREAD

**Issue by algoroq** [mapbox/mapbox-gl-native#9211]
**Platform:** iOS 

**Mapbox SDK version:** v3.6.0-beta2

### Steps to trigger behavior
 1. turn on offline mode (airplane mode)
 2. zoom map slightly [watch the video](https://goo.gl/photos/Yqwz6cLJzEp5HJr29)

### Expected behavior
No artefacts. Version [3.5.4](https://github.com/mapbox/mapbox-gl-native/commit/db7bb509e9) works fine.

### Actual behavior
Problem is only in offline mode - [watch the video](https://goo.gl/photos/Yqwz6cLJzEp5HJr29). If I switch back to online mode everything is OK. The map can not be used in offline mode.

**Comment by fabian-guerra** [comment]
Hi @algoroq. Thank you for reporting this issue. Would you be able to provide a code sample we could use to test?

**Comment by algoroq** [comment]
Hi @fabian-guerra. Thank you for your interest. I found the reason for this problem myself. I show my custom data on the map and my server doesn't provide "Cache-Control" or "Expires" in response header. This custom data are cached in cache.db but the column "expires" was NULL. I tried to fill "expires" column for these data and everything has been working fine since.

**Comment by VTCoco** [comment]
@fabian-guerra @algoroq Could you elaborate a little more please? I have the same case (UI artefacts with v3.6.0) but I don't use an external server to display annotations.

**Comment by arnekaiser** [comment]
>  I tried to fill "expires" column for these data and everything has been working fine since.

How did you do that?
