### ISSUE TITLE
Make feedback button localizable

### ISSUE THREAD

**Issue by evgzor** [mapbox/mapbox-gl-native#9215]
**iOS 10.3**
**3.5.4**

### Steps to trigger behavior

 1. Change general language of iOS device to German
 2. Run app with mapbox integrated
 3.  Press info button
 4. Observe the result

### Expected behavior
All items is localized or at least allow to be localize with any workarounds
### Actual behavior
Some of the menu items are not localized: 
<img width="368" alt="screenshot 2017-06-08 10 09 32" src="https://user-images.githubusercontent.com/5227456/26916483-3eb762e4-4c33-11e7-8e32-0b68948e249a.png">

**Comment by 1ec5** [comment]
[The German localization](https://www.transifex.com/mapbox/mapbox-gl-native/language/de/) is incomplete. If you can, please consider contributing to the localization. Thank you!

**Comment by evgzor** [comment]
@1ec5 I requested access to join the team. Could u please approve?

**Comment by 1ec5** [comment]
Welcome to the translator team, @evgzor!

**Comment by evgzor** [comment]
@1ec5 Many thanks for the approvement of invitation. We will translate all German strings. However, I did not find for translation string "Improve This Map". Could u please explain how possible to add it or where is it?

**Comment by 1ec5** [comment]
Ah, I didn’t realize you were referring to that particular item. The attribution items, including the “Improve This Map” button, come from the TileJSON files used by the sources in the current style. (For example, the default Mapbox Streets v9 style uses the Mapbox Streets v7 source, which defines the top three attribution items.) mapbox/tilejson-spec#20 tracks allowing TileJSON sources to provide localized attribution items.

Given that we’re already overriding the feedback link’s URL as of #9078, it isn’t unrealistic to override the “Improve This Map” string and make it localizable like it used to be (before #5999 landed). In fact, that would enable us to remove the fancy capitalization code added in #7651.

**Comment by evgzor** [comment]
@1ec5 Could u please let me know when it woyuld be localized for "Improve This Map" – "Verbessere diese Karte" ?
