### ISSUE TITLE
How can I add two different style.json to MGLMapView at the same time on iOS device？

### ISSUE THREAD

**Issue by dgccom** [mapbox/mapbox-gl-native#9216]

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
