### ISSUE TITLE
CamerdaUpdateFactory.newLatLngBounds Padding Issue

### ISSUE THREAD

**Issue by JustSayBien** [mapbox/mapbox-gl-native#9218]
**Platform:** Android
**Mapbox SDK version:** 5.0.2

### Steps to trigger behavior

 1. set an asymmetric mapPadding to the Map, e.g. `mapBoxMap.setPadding(400, 0, 0, 0)`
 2. update the camera with a `CameraBoundsUpdate`, e.g. `mapBoxMap.moveCamera(CameraUpdateFactory.newLatLngBounds(bounds, 30))`

### Expected behavior
The map should move the camera to the provided bounds (respecting the map-padding) so that the bounds are completely visible.

### Actual behavior
The bounds are not completely visible. The map center is displaced too much on the x-axis while it has the right zoom-level to show the bounds. 

#### Note
We were able to fix this by writing our own `CameraBoundsUpdate` with following changes in `getCameraPosition(MapboxMap mapboxMap)`:
```java
        // Calculate the center point
        //PointF paddedNEPixel = new PointF(nePixel.x + padding.right / minScale, nePixel.y + padding.top / minScale);
        //PointF paddedSWPixel = new PointF(swPixel.x - padding.left / minScale, swPixel.y - padding.bottom / minScale);
        PointF paddedNEPixel = new PointF(nePixel.x, nePixel.y);
        PointF paddedSWPixel = new PointF(swPixel.x, swPixel.y);
```

**Comment by tobrun** [comment]
With the upcoming 5.1.0 release we have changed the way we handle LatLngBounds in https://github.com/mapbox/mapbox-gl-native/pull/8765. Feel free to test out the SNAPSHOT or any of the beta releases. More information on those [here](https://www.mapbox.com/android-sdk/). 

For reference: no map or latlngbounds padding:
![0padding](https://user-images.githubusercontent.com/2151639/26923453-6ce7c4c4-4c42-11e7-98cc-bb7195eb1864.png)

Map padding, no latlngbounds padding:
![device-2017-06-08-120240](https://user-images.githubusercontent.com/2151639/26923456-7044fbc8-4c42-11e7-910a-41402c4c0583.png)

Map and latlngbounds padding:
![device-2017-06-08-120342](https://user-images.githubusercontent.com/2151639/26923493-893c03c4-4c42-11e7-8b07-90ce3bd120a1.png)

Thank you for reaching out but closing this as resolved.
