### ISSUE TITLE
[glfw] Assertion failure when resizing the window on Linux debug

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#9219]
Got this when attempting to resize the window:

> mbgl-glfw: ../../../src/mbgl/map/backend.cpp:14: mbgl::gl::Context& mbgl::Backend::getContext(): Assertion `BackendScope::exists()' failed.

@tmpsantos can you please confirm this on your Linux machine?

/cc @kkaefer

**Comment by kkaefer** [comment]
See https://github.com/mapbox/mapbox-gl-native/pull/8550

**Comment by brunoabinader** [comment]
Thanks @kkaefer - closing this one.
