### ISSUE TITLE
Limit how far you zoom out to avoid map repeat problem

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-native#922]
When there are markers etc on the screen they don't repeat when zoom out far enough to see the map repeat.

We either need to handle the repeating or limit how far you can zoom out. Google Maps takes this approach.

**Comment by ljbade** [comment]
@bleege Should we implement this?

**Comment by bleege** [comment]
Let's punt on this for the time being.

**Comment by tobrun** [comment]
I believe this is no longer relevant. 
Verified this on an 10 inch tablet which used to give this problem. 
This screenshot is taken on high zoomlevel:

![device-2016-01-07-154206](https://cloud.githubusercontent.com/assets/2151639/12173123/4aec28e0-b555-11e5-9339-3022f0f0bc94.png)
