### ISSUE TITLE
MapboxMap final

### ISSUE THREAD

**Issue by emerciercontexeo** [mapbox/mapbox-gl-native#9221]
Hi,

I want to integrate Mapbox-gl-native in a sdk providing indoor feature.

In order to do this, I encapsulate the MapboxMap in a other class to provide my own methods.

A problem with this method is that I have to rewrite all usefull MapboxMap method to make them usable through my sdk.

A better solution could be to extend the MapboxMap but it is a final class.

Is it possible to remove the final attribute ? Or there is a technical or legal reason to do not ?

Thanks for your work on this wonderful library,

Etienne
Mapwize developer

**Comment by tobrun** [comment]
Even if we would allow to extend MapboxMap, how would you provide it to the MapView/NativeMapView instance? We currently don't expose a hook for this. In future versions we are looking into making our architecture more pluggable. Some initiatives for this can be found [here](https://github.com/mapbox/mapbox-plugins-android). I don't really see this issue as actionable though stay tuned for more development on the plugin side as this could facilitate your use-case.
