### ISSUE TITLE
IOS : Updating MGLShapeSource with MGLShape is not working.

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [mapbox/mapbox-gl-native#9229]
**IOS:**
**ios-v3.6.0-beta.2**

### Steps to trigger behavior

 1. Create MGLShapeSource with MGLSymbolStyleLayer.
 2. Add shape array to MGLShapeSource, at first time it is working.
 3. But, if you pan or zoom the map view then add the updated shape array to MGLShapeSource, now for second time shapes are not updating.
4. But if you click on map or tilt the map a bit then the old shapes are updating on map.

### Expected behavior
 1. While adding array of shapes to MGLShapeSource it should update everytime with new shapes.

### Actual behavior
 1. New shapes are not updating with MGLShapeSource.

Below is my code: 
    
     func mapView(_ mapView: MGLMapView, regionDidChangeAnimated animated: Bool) {
        
        if self.mapView.style?.source(withIdentifier: "my-source") == nil {
           
            self.mySource = MGLShapeSource(identifier: "my-source", features: [], options: nil)
            self.mapView.style?.addSource(mySource!)
        }
        
        if self.mapView.style?.layer(withIdentifier: "my-layer") == nil {
            
            let myLayer = MGLSymbolStyleLayer(identifier: "my-layer", source: self.mySource!)
            myLayer.sourceLayerIdentifier = "my-source"
            myLayer.iconImageName = MGLConstantStyleValue<NSString>(rawValue: "my-icon")
            myLayer.isVisible = true
            self.mapView.style?.addLayer(myLayer)
        }
        
        DispatchQueue.main.async(execute: { [weak self] in
            if let mySource = self?.mapView.style?.source(withIdentifier: "my-source") as? MGLShapeSource {
                mySource.shape = MGLShapeCollectionFeature(shapes: self?.getShapes())
            }
        })
    }

**Comment by jmkiley** [comment]
This should be fixed by #9110  https://github.com/mapbox/mapbox-gl-native/commit/37fa8adc41126b4cdef5f7ba3916787209a55714#diff-12f94a363ba006ac75e7fba4eef3129cR36

**Comment by boundsj** [comment]
Confirmed this issue using the `Update Shape: *` debugging tests in iosapp and just tagged this as a `release blocker`.

**Comment by jmkiley** [comment]
#9303 cherry-picks a fix for this issue into the v3.6.0 release branch.
