### ISSUE TITLE
Realign MapboxConstants and JavaFileSource

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#923]
Looks like these 2 got left behind in their own packages after #915.  Let's relocate them to a more germane space.

![screen shot 2015-02-26 at 3 57 18 pm](https://cloud.githubusercontent.com/assets/989928/6402850/796b0b64-bdd0-11e4-9bca-95e5c3f64e17.png)

**Comment by bleege** [comment]
Moved `MapboxConstants` to `com.mapbox.mapboxgl.constants` and `JavaFileSource` to `com.mapbox.mapboxgl.util`.

**Comment by ljbade** [comment]
Good catch, thanks.
