### ISSUE TITLE
Qt5 builds failing on Bitrise — missing /usr/local/.//mkspecs/macx-clang ... again ...

### ISSUE THREAD

**Issue by ConanHorus** [mapbox/mapbox-gl-native#9235]
Qt5 macOS builds have been failing on Bitrise for I don't know how long.

As you can see, this has been a recurring issue: [here](https://github.com/mapbox/mapbox-gl-native/issues/6712) and [here](https://github.com/mapbox/mapbox-gl-native/issues/8691).

Well, it's acting up again!

```
CMake Error at /usr/local/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:15 (message):
  The imported target "Qt5::Core" references the file

     "/usr/local/.//mkspecs/macx-clang"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/local/lib/cmake/Qt5Core/Qt5CoreConfigExtras.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/local/lib/cmake/Qt5Core/Qt5CoreConfigExtras.cmake:50 (_qt5_Core_check_file_exists)
  /usr/local/lib/cmake/Qt5Core/Qt5CoreConfig.cmake:167 (include)
  /usr/local/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:83 (find_package)
  /usr/local/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:83 (find_package)
  src/CMakeLists.txt:51 (find_package)
```

If this is a recurring issue, perhaps a more robust fix is in order? In October the issue was that homebrew was fetching a broken version. Is there a way to look for correct versions instead of simply assuming? Or am I just way off base here and that's not how things work?

**Comment by jfirebaugh** [comment]
Looks like Qt5 macOS builds are working right now.
