### ISSUE TITLE
libz-dev missing as a dependency

### ISSUE THREAD

**Issue by ericblade** [mapbox/mapbox-gl-native#9236]
Compilation fails without libz-dev installed

**Comment by jfirebaugh** [comment]
It's noted as a dependency the [linux README](https://github.com/mapbox/mapbox-gl-native/blob/033c7a8d3e7d05d71c796a0e95665257ce908bc3/platform/linux/README.md#L20-L20).

**Comment by ericblade** [comment]
Fair enough. Might be worth adding to the QT README, as well . . and including a check for it in CMakeLists ?
