### ISSUE TITLE
[android] Add IntelliJ live templates to remove boilerplate code

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#9241]
A great way of removing MapView-lifecycle boilerplate code included in activities is using an IntelliJ live template.
I toyed with them and created a simple map activity template which creates all that code for you.

Here is the template's text:

```java
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

import com.mapbox.mapboxsdk.maps.MapView;

$public$ $class$ $className$ $extends$ $compatClass$ $openBrace$

  private MapView $mapView$;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.$LAYOUT$);
    $mapView$ = (MapView) findViewById(R.id.$ID$);
    $mapView$.onCreate(savedInstanceState);
  }

  @Override
  protected void onStart() {
    super.onStart();
    $mapView$.onStart();
  }

  @Override
  protected void onResume() {
    super.onResume();
    $mapView$.onResume();
  }

  @Override
  protected void onPause() {
    super.onPause();
    $mapView$.onPause();
  }

  @Override
  protected void onStop() {
    super.onStop();
    $mapView$.onStop();
  }

  @Override
  public void onLowMemory() {
    super.onLowMemory();
    $mapView$.onLowMemory();
  }

  @Override
  protected void onDestroy() {
    super.onDestroy();
    $mapView$.onDestroy();
  }

  @Override
  protected void onSaveInstanceState(Bundle outState) {
    super.onSaveInstanceState(outState);
    $mapView$.onSaveInstanceState(outState);
  }
$closeBrace$
```

Screenshot of the configuration used: 

![map-activity-template](https://user-images.githubusercontent.com/1668582/27010847-87dbf85e-4eae-11e7-97cc-d16dff838aef.png)

Still needs to be tweaked but when finished we should add this to the documentation so devs could use it when creating Mapbox map activities.

cc/ @mapbox/android

**Comment by tobrun** [comment]
Looking forward using this once this lands

**Comment by tobrun** [comment]
stale

**Comment by keciciler** [comment]
Hello I have a new approach to this problem, you can check it out :)
https://medium.com/@altug.keciciler/another-approach-to-mapview-lifecycle-delegation-8a230b862706

**Comment by zugaldia** [comment]
Interesting, @keciciler, thanks for sharing! This could work because we already have a dependency on support fragment (`FragmentLifecycleCallbacks`) directly into the SDK. In any case, this could be an interesting example to add to our test app.
