### ISSUE TITLE
IOS: map above city

### ISSUE THREAD

**Issue by CristianSerea** [mapbox/mapbox-gl-native#9246]
Hi guys...i wanna know if there is any method to return the city where i am looking on the map...

i used these methods when user drag, move map to ask if a point is in rect of map...
```
-(void)mapView:(MGLMapView *)mapView regionWillChangeAnimated:(BOOL)animated {

-(void)mapView:(MGLMapView *)mapView regionDidChangeAnimated:(BOOL)animated {
```

```
CGPoint locationPoint = [self.mapView convertCoordinate: parisLocation.coordinate toPointToView: self.mapView];
    
CGRect locationRect = CGRectMake(locationPoint.x - parisLocation.horizontalAccuracy,
                                     locationPoint.y - parisLocation.horizontalAccuracy,
                                     parisLocation.horizontalAccuracy * 2,
                                     parisLocation.horizontalAccuracy * 2);
    
return CGRectIntersectsRect([self.mapView bounds], locationRect);
```

but this seem to be not good because the point is not always visible in all possibilities of user zooming in/out ..

i want to get the city where user looking on map from maximum level up to 8-10 minimum zoom level, where the city get out of screen...

thanks

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
