### ISSUE TITLE
Image Artifacts Remain After Adding/Removing Symbol Layer

### ISSUE THREAD

**Issue by otmanskim** [mapbox/mapbox-gl-native#9249]
We're trying to add and remove "image" layers (they are actually MGLSymbolStyleLayer's), using the workaround detailed [here](https://gist.github.com/incanus/8c277a0700c917ac58600d93cd849bb8). We have added a UIButton that will add and remove the image layer as appropriate when tapped. We are removing the images by removing the source, layer, and imageName from the map's style:

```
style.removeSource(source)
style.removeLayer(layer)
style.removeImage(forName: overlay.identifier)
```
The issue we are seeing is after removal, if we zoom in or out, when we re-add the layer, this time the image appears distorted, as though artifacts of the old image are still present on the map. Screenshots attached.

Original Image:
![original image](https://user-images.githubusercontent.com/4522164/27052283-d45261ac-4f7e-11e7-81e6-11be432150e5.png)

Image after removing, zooming, and re-adding:
![after removing zooming and readding](https://user-images.githubusercontent.com/4522164/27052285-d678ca7a-4f7e-11e7-9833-de8d9381c59e.png)

**Platform:** iOS (10)
**Mapbox SDK version:** 3.5.4

### Steps to trigger behavior

 1. Implement the workaround to add an image layer to the map, as described here: https://github.com/mapbox/mapbox-gl-native/issues/1350#issuecomment-283814642
 2. Also implement removal / re-adding of the image layer
 3. Run the app to add the image the first time
 4. Remove the image layer from the map's style (via button or other added interface)
 5. Zoom the map in or out
 6. Re-add the image layer (via button or other added interface)
 7. Notice extra border around the edges of the image looks like part of the original image

### Expected behavior
The image should appear the same the second time it's added as it did the first time.

### Actual behavior
The image appears distorted and artifacts from the original one remain.

**Comment by otmanskim** [comment]
@Guardiola31337 @fabian-guerra Is there any timeline for when someone will be able to take a look at this? It's blocking a release we have scheduled for next week, so we would greatly appreciate an expedited investigation. Thanks!

**Comment by friedbunny** [comment]
You might try this with the latest pre-release of v3.6.0, the stable release of which we’re in the last stages of finalizing. I don’t recall there being any relevant fixes included, but it would be good to confirm.

There’s also already been work done/planned for the release _after_ that to improve the rendering of textures and images, such as #9213 and #9110. Our release cadence is typically one every few months, with pre-releases coming sooner.

**Comment by otmanskim** [comment]
@friedbunny thanks for your response! I tried this with v3.6.0 and unfortunately saw the same issue. I notice that both the PR's you linked are now merged. When would you estimate these changes will make their way into a release, even if it's just a beta?

**Comment by friedbunny** [comment]
It’s still too early to say what the timeline will be for the release after v3.6.0 (tentatively titled v3.7.0).

Though not production quality, we do publish [nightly builds](https://github.com/mapbox/mapbox-gl-native/blob/a33cad98557f2d15bfb578e4795b130d25a2def2/platform/ios/INSTALL.md#nightly-builds). Today’s already includes #9213, and tomorrow’s will have #9110.

**Comment by otmanskim** [comment]
@friedbunny thanks for the help, I will definitely be taking a look at the nightly build soon to start playing around with this update. However we are scheduled to go to production in the next week, so do you think it would be at all possible to get the code merged in #9213 and #9110 into the next upcoming version, even if it's still a little rough around the edges?

**Comment by friedbunny** [comment]
> do you think it would be at all possible to get the code merged in #9213 and #9110 into the next upcoming version

Unfortunately, no. Those changes are substantial and bugs/performance issues are still being ironed out, while v3.6.0 is more-or-less frozen and readying for final release.

**Comment by 1ec5** [comment]
Does the issue reproduce if you give the image a new name every time you add it to the style? (I know this sounds kludgy, but it might help us narrow down where the problem lies.)

**Comment by jfirebaugh** [comment]
3.7.0 added `MGLImageSource` and likely fixed this bug as well.
