### ISSUE TITLE
Remove futures/promises during tile parsing

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#925]
We're currently [using futures/promises](https://github.com/mapbox/mapbox-gl-native/blob/e1ff75a47aa3893219e0a9842829e5566f26449a/src/mbgl/text/glyph_store.cpp#L261) to block tile parsing until the required glyph set has been loaded and added to the glyph atlas. However, this blocks our parsing threads. Instead, we should abort parsing the current layer and restart parsing once we have obtained the required resources.

Once this is done, we can remove the custom worker pool and instead use the worker pool provided by libuv.

**Comment by kkaefer** [comment]
This requires quite some refactoring: We probably first need to [split up](https://github.com/mapbox/mapbox-gl-native/issues/305) all layers into individual (dependent) parse tasks that can be rescheduled on their own.

**Comment by incanus** [comment]
What sort of timeline are you thinking about this? I'm in some parser refactoring to split out the common parts of `TileParser` for use by both a `VectorTileParser` and a `LiveTileParser`, which handles non-pbf data. Unless this is critical, we should probably wait a bit.

**Comment by kkaefer** [comment]
Just added the issue to capture it
