### ISSUE TITLE
Don't create GL objects in the tile worker thread

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#926]
We should check that we're not creating any GL objects or calling any GL functions in general in anything but the Map thread.

**Comment by ljbade** [comment]
Hmm, easiest way is it look at the attach/detach functions since any GL calls in a thread without a GL context bound will throw and exception.

**Comment by kkaefer** [comment]
FWIW, I don't think we're currently doing this, but we should do a proper review to avoid any undefined effects later on.

**Comment by ljbade** [comment]
Another trick would be to add a thread ID check to the GL function error check wrappers.

**Comment by jfirebaugh** [comment]
Creation of GL objects now requires a `GLObjectStore`, which the worker thread does not have access to, so we can be fairly certain this does not happen.
