### ISSUE TITLE
Validate javadoc as part of CI build

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9267]
With every release we need create additional PRs to fixup javadoc. Take for example https://github.com/mapbox/mapbox-gl-native/pull/9266, there we had to resolve 50 errors/ 100 warnings before being able to ship. I'm suggesting adding javadoc validation as part of our CI build. Such validation will probably require to inspect output from `make android-checkstyle` (afaik we can't rely on the exit code as it 's always succesfull even with errors). 

cc @mapbox/android

**Comment by zugaldia** [comment]
@tobrun 👍 x 100.

**Comment by cammace** [comment]
You can uncomment [these lines](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/checkstyle.xml#L203-L211) in the checkstyle file which sets a rule that requires all public methods to have javadoc.

**Comment by tobrun** [comment]
I tried running with suggestion above but it requires to also fix the javadoc on testapp. @cammace is their a more fine gran control over what a specific checkstyle module validates?

**Comment by Guardiola31337** [comment]
@tobrun we could use a [`SuppressionFilter`](http://checkstyle.sourceforge.net/config_filters.html#SuppressionFilter).

Suppressions are specified in a new xml file (e.g. `checkstyle-suppressions.xml`) and the filter has to be added under `Checker` in `checkstyle.xml`:

```xml
<module name="SuppressionFilter">
        <property name="file" value="checkstyle-suppressions.xml" />
</module>
```

**Comment by tobrun** [comment]
this is happening as part of https://github.com/mapbox/mapbox-gl-native/pull/14792
