### ISSUE TITLE
Refactor Style object hierarchy

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#927]
Our current Style object hierarchy is a little messy: Worker threads depend on it being immutable, but it really isn't. We don't have a clear concept for changing/swapping styles, and not a clear object ownership.

- #837: programmatic style API
- #904: Get rid of shared_ptr for Source objects
- #883: Don't parse Style object in the UI thread
- #900: get/setStyleJSON should not be public API
- #881: Every tile parser thread needs its own Style object

**Comment by ljbade** [comment]
My ideas:
- make style immutable, ie all the change functions return a new style object copied from the current with the changes
- have a single 'master' style object in map that gets atomically swapped (or locking swap)
- every worker job gets a copy of the 'master' style when it is created
- to update/load new styles you create the new style object with the change functions, then call some function that switches out the 'master' style

**Comment by mikemorris** [comment]
Mutable styles could be responsible for https://github.com/mapbox/node-mapbox-gl-native/issues/64

**Comment by jfirebaugh** [comment]
The dependent bugs above are now fixed. Remaining actions tracked in #667.
