### ISSUE TITLE
[Android] Showing infoWindow from outside of OnMarkerClickListener makes window "unlocked" from presenting marker.

### ISSUE THREAD

**Issue by arbitur** [mapbox/mapbox-gl-native#9277]
Platform: Android
Version: 5.0.2 (latest stable as of today)

In my case I have a `Marker` as a property for my `Fragment` subclass, I fetch some geolocation data and then move this marker to the address and want to present the markers `infoWindow` after animating the camera to the coordinate.

```java
public final class MapFragment extends Fragment {
    private Marker userMarker;

    // Called from onResponse from GeoLocationService
    private void gotAddressData(AddressData addressData) {
        userMarker.setPosition(addressData.getCoordinate());
        mapController.animateCamera(
            CameraUpdateFactory.newLatLng(
                addressData.getCoordinate()), new MapboxMap.CancelableCallback() {
			@Override
			public void onCancel() {
			}

			@Override
			public void onFinish() {
				userMarker.showInfoWindow(mapboxMap, mapView);
			}
		});
    }
}
```

The infoWindow is shown BUT the bottom arrow is not ABOVE the marker instead its pointing to the markers center. And when tapping somewhere else on the map like you want to dismiss any infoWindow, it doesnt hide, and opening other markers infoWindow also doesnt hide that one...
And when scrolling the mapView that infoWindow will stick to the center of the screen .

**Comment by Guardiola31337** [comment]
@arbitur thanks for reaching out and report your problem.

As indicated in the documentation [`showInfoWindow` method is used internally and shouldn't be used](https://github.com/mapbox/mapbox-gl-native/blob/release-ios-v3.6.0-android-v5.1.0/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/Marker.java#L205-L206). You should use `MapboxMap#selectMarker(Marker)` instead.

Could you try again using `MapboxMap#selectMarker(Marker)` and report back your findings?

**Comment by arbitur** [comment]
@Guardiola31337  Thanks, that worked as expected.

**Comment by Guardiola31337** [comment]
@arbitur awesome!
Feel free to open new tickets if you find any other issues :wink:
Thanks again.

Closing.
