### ISSUE TITLE
The best way to get size of offline region. Android SDK

### ISSUE THREAD

**Issue by giperwlad** [mapbox/mapbox-gl-native#9278]
Hello and thanks for contributing! 

How to get the size of offline region in kilobytes. Is there a way to get the size before starting the download?

Platform: Android
Version: 5.1.0-SNAPSHOT

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by jfirebaugh** [comment]
See also #4258.
