### ISSUE TITLE
Optimize Extrusion drawing

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#9286]
We should move the extrusion texture step to the beginning of a frame to improve rendering performance.

Right now, the workflow of a frame is like this:

* (main framebuffer is bound)
* Clear main framebuffer (✅ first operation is clear -> no restore)
* Render some layers
* Render extrusion layer
  * **Bind extrusions framebuffer**
  * Clear extrusions framebuffer (✅ first operation is clear -> no restore)
  * Draw extrusions
  * **Bind main framebuffer**
* Draw extrusions texture (:warning: FBO restore)
* Render remaining layers

When binding a framebuffer and rendering operations on it, the GPU has to restore the contents of the framebuffer. The driver can optimize that when we do a clear as the first drawing operation (since that discards the contents of the framebuffer). Therefore, drawing to the main framebuffer, then binding a *different* framebuffer, and rebinding the main framebuffer triggers a framebuffer load on the first draw call.

Instead, we could do all operations that require binding a separate framebuffer (i.e. drawing the extrusions texture) as the first thing when rendering a frame (i.e. before calling clear on the main framebuffer) and have the following order:

* (main framebuffer is bound)
* Create extrusion texture
  * **Bind extrusions framebuffer**
  * Clear extrusions framebuffer (✅ first operation is clear -> no restore)
  * Draw extrusions
  * **Bind main framebuffer**
* Clear main framebuffer (✅ first operation is clear -> no restore)
* Render some layers
* Render extrusion texture
* Render remaining layers

In addition to that, the iOS OpenGL inspector reports these issues when drawing extrusions:

* **Depth testing enabled without an attached depth buffer**: Your app rendered with DEPTH_TEST enabled into a framebuffer without an attached depth buffer.
* **Missing framebuffer attachments**: Framebuffer #2 has no attachments and therefore is not usable in its current state.

These two errors may be the reason for https://github.com/mapbox/mapbox-gl-native/issues/9279

**Comment by mourner** [comment]
GL JS would benefit from this too, right?

**Comment by kkaefer** [comment]
Yep

**Comment by lbud** [comment]
This sounds good. The one tradeoff here is that we may need to create and store multiple OffscreenTextures if there are multiple extrusion layers, but it sounds like the benefits here outweigh that.
