### ISSUE TITLE
Make MGLMapView IB_DESIGNABLE (for iOS XIBs)

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#929]
Developers who use XIBs or storyboards will find it more awkward to use `MGLMapView` than `MKMapView` because custom views such as `MGLMapView` are rendered as plain white squares by default:

![ib](https://cloud.githubusercontent.com/assets/1231218/6423698/c54eb854-be9e-11e4-9ade-6cf09188a6bb.png)
_Left: `MGLMapView`. Right: `MKMapView`._

`MGLMapView` should be marked [`IB_DESIGNABLE`](https://developer.apple.com/library/ios/recipes/xcode_help-IB_objects_media/chapters/CreatingaLiveViewofaCustomObject.html) and draw something recognizable inside Interface Builder. It would be impractical to load actual map content synchronously within the short timeout, but even something mimicking the `MKMapView`’s translucent “blue box” would be easier to work with.

**Comment by incanus** [comment]
:+1:

I started playing around in this direction a few weeks back but only got as far as https://gist.github.com/incanus/867e487146bb9695065a. I got blocked there by GL project restructuring and the loss of a dynamic framework that would work in Swift (#828). 

https://twitter.com/incanus77/statuses/563748947043164160

**Comment by ljbade** [comment]
Interesting Android has something similar for the UI editor: https://github.com/mapbox/mapbox-gl-native/issues/650

**Comment by 1ec5** [comment]
Also, we should have the box draw a little reminder when the inspectable access token isn’t filled in.

**Comment by ljbade** [comment]
@1ec5 great idea!

**Comment by DavidChouinard** [comment]
As user: this would be very useful!

**Comment by DavidChouinard** [comment]
@1ec5 What do you mean by inspectable access token?

**Comment by 1ec5** [comment]
`accessToken` doesn’t appear to be KVO-compliant at the moment. Additionally, if `accessToken` is unset, setting it should make the map use the default bundled style, just as `-initWithFrame:styleJSON:accessToken:` calls `-setStyleJSON:` with `nil` when there’s a token is specified.

**Comment by 1ec5** [comment]
![untokenized](https://cloud.githubusercontent.com/assets/1231218/6954590/4a364d4a-d888-11e4-840b-4801c497a924.png)
![tokenized](https://cloud.githubusercontent.com/assets/1231218/6954592/4c7b42ae-d888-11e4-85f6-b8530969556c.png)

**Comment by friedbunny** [comment]
Very nice. :metal:
