### ISSUE TITLE
Update Bitrise to Xcode 8.3.x

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#9291]
Bitrise currently uses Xcode ~8.2~ 8.1 — we should always be on the latest stable release, which happens to be 8.3.3.

New Xcode releases come with new compiler versions and new warnings/errors. Last time we updated Xcode, it was done (by me) somewhat haphazardly and ended up breaking CI builds until we made some changes. This time, we should try out the update on a test branch/workflow before switching all builds over.

/cc @1ec5 @jfirebaugh @kkaefer

**Comment by jfirebaugh** [comment]
> This time, we should try out the update on a test branch/workflow before switching all builds over.

Unfortunately, that's not possible with Bitrise. The stack selection is an app-wide setting, and can't be switched on a per-branch or per-workflow basis. This is one of the major reason I think we should transition off Bitrise as soon as practicable (#8551).

**Comment by friedbunny** [comment]
> The stack selection is an app-wide setting, and can't be switched on a per-branch or per-workflow basis.
Ah, yes. :( In that case, we should time the switch so that other development is minimally impacted.

**Comment by 1ec5** [comment]
Bitrise has deprecated the Xcode 8.2 stack that we’re currently on and plans to remove it when Xcode 9 is released later this year.

**Comment by friedbunny** [comment]
I’ve changed [the stack](https://github.com/bitrise-io/bitrise.io/blob/9f1a1832b8f00cab80689ed1e3595b15916f96f5/system_reports/osx-xcode-8.3.x.log) over to Xcode 8.3.x and run builds on master, the current iOS release branch, and the six most recently updated PRs. No new warnings or failures surfaced, so I’m going to call this a success.

**Comment by friedbunny** [comment]
- Updated macOS from Xcode 8.2.
- Updated Qt5 macOS from Xcode 8.0.
- Updated Node macOS from Xcode 8.0.
