### ISSUE TITLE
Layer fully loaded listener

### ISSUE THREAD

**Issue by s3r6** [mapbox/mapbox-gl-native#9300]
**Platform: Android**
**Mapbox SDK version: 5.0.2**

Is there an ability to get a listener for state when layer is fully loaded on screen? It means no empty not loaded tiles or scaled tiles from previous zoom level.

**Comment by jfirebaugh** [comment]
Listen for the `MapChange` event with value `DID_FINISH_RENDERING_MAP_FULLY_RENDERED`: https://www.mapbox.com/android-sdk/api/5.0.2/com/mapbox/mapboxsdk/maps/MapView.html#DID_FINISH_RENDERING_MAP_FULLY_RENDERED
