### ISSUE TITLE
New layers are interpolated from black when transitioning to a new style

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-native#9301]
When we set a new style, layers that exist on both styles do the transition fine. New layers apparently get their color interpolated from black. IMO they should interpolate only opacity in this case (i.e. full transparency -> current opacity of the layer).

![out](https://user-images.githubusercontent.com/996307/27294578-af3a6564-5522-11e7-84b9-3c42fadc6112.gif)

This is better seen with `DEFAULT_TRANSITION_DURATION` set to 10s.

/cc @jfirebaugh

**Comment by jfirebaugh** [comment]
@anandthakker Do you know how gl-js handles this case?

**Comment by anandthakker** [comment]
I believe it does not use a paint transition when a layer is first added.  (See: https://github.com/mapbox/mapbox-gl-js/blob/master/src/style/style_transition.js#L37)
