### ISSUE TITLE
Map bug (colored stripes) on samsung galaxy s4

### ISSUE THREAD

**Issue by salonkasoli** [mapbox/mapbox-gl-native#9306]
Hello, i met this map behavior on samsung galaxy s4 (android 5.0.1).
Application includes nothing, just map.
to include mapbox i did:

```
compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.2@aar'){
        transitive=true
    }
```

To trigger it i just zoomed camera close enought, no special stuff.
On my Huawei Honor 4c everything works fine.

![m9h2hs_sjsm](https://user-images.githubusercontent.com/22319813/27330392-65c41c10-55e3-11e7-8d1d-c3fa14c55857.jpg)
![-alo-avsnf0](https://user-images.githubusercontent.com/22319813/27330394-67b41156-55e3-11e7-9769-3033090bcd39.jpg)

**Comment by jfirebaugh** [comment]
Thanks for the report @salonkasoli. Can you provide the exact model number of the phone?

**Comment by salonkasoli** [comment]
@jfirebaugh samsung galaxy s4 GT-I9500
![9bqwu09y5mo](https://user-images.githubusercontent.com/22319813/27463124-cd7d06b0-57ef-11e7-8b7d-0d168b3f0485.jpg)
![a8of6gw2p5w](https://user-images.githubusercontent.com/22319813/27463125-cea7a5ea-57ef-11e7-89fe-8052b5ef5f4e.jpg)

**Comment by salonkasoli** [comment]
here is MainActivity
https://pastebin.com/Wy8YeyKq
activity_main.xml
https://pastebin.com/fYjpETt0
Every time i click a map ACTION_DOWN appears, every time i scroll TwScaleGestureDetector appears.
Here is Log
https://pastebin.com/3ZkxGgpB

**Comment by jfirebaugh** [comment]
Thanks! I had a hunch it was the GT-I9500; it seems to be specific to the PowerVR SGX544 GPU used by the GT-I9500, the Alcatel One Touch 6040x, and a few other models. We have a GT-I9500 on the way for testing locally.

This issue was previously reported in #8658 -- let's track it there.
