### ISSUE TITLE
Marker

### ISSUE THREAD

**Issue by qasimalbaqali** [mapbox/mapbox-gl-native#9310]
**Platform: Android**
**Mapbox SDK version: 5.0.2**

I'm trying to set up the MarkerOnClick listener. I set it up in getMapAsync method and I'm setting it up in the following way

```
map.setOnMarkerClickListener(new MapboxMap.OnMarkerClickListener() {
                        @Override
                        public boolean onMarkerClick(@NonNull Marker marker) {
                            Log.e("Marker Clicked", marker.getTitle());
                            return true;
                        }
                    });
```

Whenever I click on the marker or the snipper of the marker the method doesn't get triggered. How do set it up correctly?

**Comment by Guardiola31337** [comment]
@qasimalbaqali thanks for reaching out and report your question.

If you're using `MarkerView`s you should use [`MarkerViewManager#setOnMarkerViewClickListener`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java#L427-L434) instead. See [`OnMarkerViewClickListener`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java#L2319-L2333) for further information.

There are a couple of examples of usage in the test app ([`BulkMarkerActivity.java`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/BulkMarkerActivity.java#L243-L254) and [`MarkerViewActivity.java`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java#L159-L168)) that you can check.
