### ISSUE TITLE
Localisation API

### ISSUE THREAD

**Issue by andrei-egeniq** [mapbox/mapbox-gl-native#9321]
The IOS SDK/sample app checks the data before making a change
`if ([label.rawValue hasPrefix:@"{name"])`

The Android SDK/sample, just sets the value
`setProperties(textField("{name_ru}"));`

Setting the value with no check results in previously hidden text being shown.
See `Stairway` in attachments.

Is there a way to do the check on Android or the Android SDK is missing the feature?

![no_language_set](https://user-images.githubusercontent.com/10440542/27378713-016584d4-5679-11e7-8d40-f0d0a0b5959c.png)
![after_language_set](https://user-images.githubusercontent.com/10440542/27378716-03f458e2-5679-11e7-8341-38f1eaf7f0e0.png)

**Comment by jfirebaugh** [comment]
Hi @andrei-egeniq -- yes, you can implement the equivalent functionality with the Android SDK by testing the result of [`SymbolLayer::getTextField`](https://www.mapbox.com/android-docs/api/map-sdk/5.0.2/com/mapbox/mapboxsdk/style/layers/SymbolLayer.html#getTextField--) for that prefix.
