### ISSUE TITLE
Replace Toolbar With ActionBar / AppBar In GLTestApp

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#933]
The current test app makes use of a Toolbar on top of the existing ActionBar.  Let's go with the ActionBar on it's own as it offers more builtin features out of the box that will make adding features easier in the future.

http://www.google.com/design/spec/layout/structure.html

**Comment by ljbade** [comment]
Interesting. The reason I went with the toolbar is that it appears to be the proper way to have action buttons that can overflow into the drop menu.

Perhaps Google have changed the way ActionBar stuff is supposed to behave in Android 5?

**Comment by ljbade** [comment]
@bleege Did you do this in the Activity change?

**Comment by bleege** [comment]
This will implemented via Material Design refactor in #1856.
