### ISSUE TITLE
Use updated Ubuntu Trusty 14.04 images on Travis 

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#9332]
Travis rolled out [new Ubuntu Trusty 14.04 images](https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch). They broke our Qt4 build with errors like:

```
CMake Error at cmake/core.cmake:1 (add_library):
  Target "mbgl-core" links to target "Qt4::QtOpenGL" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

As a temporary workaround, we [reverted to the prior images](https://github.com/mapbox/mapbox-gl-native/pull/9329), but we should figure out how to get back on the newer images.

cc @tmpsantos @brunoabinader

**Comment by tmpsantos** [comment]
This should be fixed by https://github.com/mapbox/mapbox-gl-native/pull/9051 no?

**Comment by jfirebaugh** [comment]
Yes, it would be.

**Comment by jfirebaugh** [comment]
#9051 was merged.
