### ISSUE TITLE
OnCameraMoveStarted listener never gets invoked

### ISSUE THREAD

**Issue by cammace** [mapbox/mapbox-gl-native#9335]
When adjusting the camera position, the listener callback never gets invoked providing the reason.

cc: @tobrun @Guardiola31337

**Comment by tobrun** [comment]
All animateCamera, moveCamera and jumpCamera invocations call into the camera dispatcher as:

> cameraChangeDispatcher.onCameraMoveStarted(
OnCameraMoveStartedListener.REASON_API_ANIMATION);

The reason is provided, please clarify what you mean with `adjusting the camera position`.

**Comment by tobrun** [comment]
I'm going ahead and will look into this in function of https://github.com/mapbox/mapbox-gl-native/issues/9320.
