### ISSUE TITLE
Issue with shadow of Dialog when Map is inside

### ISSUE THREAD

**Issue by kfadli** [mapbox/mapbox-gl-native#9337]
Hi, i want to embed the map inside Android's Dialog and it seems the shadow behind the popup is in front of map.

In fact, the map is the only one component of my Dialog with shadow in front.

One picture for illustrate it:

![screenshot_20170622-120656](https://user-images.githubusercontent.com/275688/27428780-6535da02-5743-11e7-9af2-b2ab9dc7d238.png)

of course if i clear the flags FLAG_DIM_BEHIND with: `getWindow().clearFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);`

the shadow disappear in front of the Map and behind the Dialog.

![screenshot_20170622-120922](https://user-images.githubusercontent.com/275688/27429178-9941e22c-5744-11e7-854c-af67360b9a5f.png)

Same behaviour with 5.0.2 version.

**Platform:Android 7.1.2**
**Mapbox SDK version: 5.1.0-beta.5**

### Steps to trigger behavior

 1. Create class inherited of Dialog which load xml with MapView inside

**Comment by tobrun** [comment]
Thank you for the report @kfadli, the underlying issue is that the SurfaceView is placed behind the dialog container.  Linking #6634 as it contains a workaround. Maybe you can try out the following to have working with a SurfaceView:

```
    ((SurfaceView)findViewById(R.id.surfaceView)).setZOrderOnTop(true);
```

**Comment by kfadli** [comment]
Thanks @tobrun, it works as expected !!

![screenshot_20170622-163122](https://user-images.githubusercontent.com/275688/27439490-5a254812-5768-11e7-9290-1dcef767b61f.png)
