### ISSUE TITLE
Style.java

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9338]
With https://github.com/mapbox/mapbox-gl-native/pull/9280, style has been promoted to be part of the public api that core exposes for bindings. This change could be propagated to the Android binding by exposing Style.java to match the API and functionality more closely. Adding a semver label, though we could ship intermediate versions with deprecation notices. 

cc @mapbox/android

**Comment by tobrun** [comment]
I'm proposing the match the API exposed by [style.hpp](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/style/style.hpp). Concretely this will mean moving methods from `MapboxMap.java` to `Style.java`. With this move, I'm also suggesting to implement the native methods directly on `Style.java` instead of facading through `NativeMapView.java`.

**Comment by tobrun** [comment]
Additional API changes will need to occur around the OnMapReady and the OnStyleLoadedListener callback. These will be given an additional Style parameter:

```java
public interface OnMapReadyCallback {
  void onMapReady(MapboxMap mapboxMap, Style style);
}
```

**Comment by LukasPaczos** [comment]
Great idea @tobrun. With this change, we could restrict adding new style URL/path to the constructor or builder of the `Style` which would indicate that all the programmatically added components should be re-added, as we are creating a new `Style` object. This would easily resolve most of the issues from https://github.com/mapbox/mapbox-gl-native/issues/10947.

**Comment by tobrun** [comment]
done in #13484
