### ISSUE TITLE
Headless snapshots

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#9340]
We currently provide [`snapshot`](https://www.mapbox.com/android-docs/api/map-sdk/5.0.2/com/mapbox/mapboxsdk/maps/MapboxMap.html#snapshot-com.mapbox.mapboxsdk.maps.MapboxMap.SnapshotReadyCallback-), that allows developers to capture a `Bitmap` of the map asynchronously on the UI thread with `SnapshotReadyCallback`.

We hear from developers that it'd be useful if, in addition, the following use cases were supported:

- Ability to generate full snapshots of purely the map style
- Ability to do so without a view hierarchy
- Ability to do so on arbitrary threads

Related ticket on iOS: https://github.com/mapbox/mapbox-gl-native/issues/1701.

cc: @ivovandongen @tobrun @Guardiola31337

**Comment by tobrun** [comment]
This happened in https://github.com/mapbox/mapbox-gl-native/pull/9748, tail work is ticketed out in https://github.com/mapbox/mapbox-gl-native/issues/9916 and https://github.com/mapbox/mapbox-gl-native/issues/9914.
