### ISSUE TITLE
[android] Reduce Lint baseline

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#9342]
Follow up ticket https://github.com/mapbox/mapbox-gl-native/pull/9318#issuecomment-310077085

- [ ] Make the current baseline as small as possible

>  by looking at [the SDK file](https://github.com/mapbox/mapbox-gl-native/blob/6cdf3ead0bd8b954681b4a8404b2f8670f6ca4d4/platform/android/MapboxGLAndroidSDK/lint-baseline.xml), it seems to me that there're many issues that are easily fixable (e.g. setting a default Locale during logging, or using `@SuppressWarnings({"MissingPermission"})` when we're sure we don't need to check for a permission).

cc/ @zugaldia

**Comment by tobrun** [comment]
done in #9627
