### ISSUE TITLE
Integrate hybrid style

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#935]
Per discussion with @incanus, this issue tracks adding the “hybrid” style to the example apps. See mapbox/mapbox-gl-styles#35, mapbox/mapbox-gl-js#1041.

**Comment by incanus** [comment]
Idea here is parity with what devs expect of <code>-[MKMapView.mapType]</code>.

**Comment by 1ec5** [comment]
Depends on #939.

**Comment by 1ec5** [comment]
To your left, contours+labels. To your right, just labels:
![contours labels](https://cloud.githubusercontent.com/assets/1231218/6517809/9d44a882-c353-11e4-9a23-cfd015d4cdfd.png) ![labels](https://cloud.githubusercontent.com/assets/1231218/6517810/9d49ba52-c353-11e4-9a8d-5d57d7c31d3b.png)

**Comment by 1ec5** [comment]
Here’s what we’re getting out of the style .json: `http://a.tiles.mapbox.com/v4/mapbox.mapbox-terrain-v2/{z}/{x}/{y}.vector.pbf?access_token=…`. The vector glyph zoom level is always one lower than the raster tile zoom level.

**Comment by 1ec5** [comment]
At the initial viewport, `map.getState()` is 14.5. The `TileData`s are being created with z14 for the contours and labels and z15 for the satellite tiles, based on the return value of `Source::getZoom()`.

**Comment by incanus** [comment]
@jfirebaugh I believe you said you were going to take a look at this? Want to self-assign, or just take a peek?

**Comment by gundersen** [comment]
@incanus can we use Mapbox Terrain rather than Mapbox Outdoors in when we launch. Terrain gets us the wins of terrain w/ the wins of Mapbox Streets. 

@ajashton what are your thoughts here on the 1 style we should launch in GL w/ the iOS launch?

**Comment by jfirebaugh** [comment]
The rendering errors (black labels, missing contours) are reproducible on any platform.

9897ae74ecd7a81f250ee791be41fdf20727785c fixes contour rendering. fddd27f6c4b46aa8b164d2a5a97eb35ae3ef4cdc fixes label rendering but I'm not sure if it's correct. @kkaefer?

**Comment by incanus** [comment]
Splitting vector terrain out to https://github.com/mapbox/mapbox-gl-native/issues/964 to keep this ticket purely raster satellite + vector labels (i.e. "hybrid").

**Comment by incanus** [comment]
This will come in in b2.
