### ISSUE TITLE
Support drag-and-drop (iOS 11)

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#9350]
One of the primary new features in iOS 11 is inter-app [drag and drop](https://developer.apple.com/ios/drag-and-drop/). We should make any necessary changes so that our map view supports drag and drop well out of the box, without external dependencies or network calls.

### Considerations
- Rasterization — the snapshot workaround in https://github.com/mapbox/mapbox-gl-native/issues/1701 may be good enough, as users will be dragging from already-rendered foreground maps.
- Attribution — https://github.com/mapbox/mapbox-gl-native/issues/3804 would replace the ℹ️ button with text when a map is not interactive.

Marking this as “MapKit parity” on assumption, but I actually have no idea the extent to which they support drag and drop.

### Resources
- https://www.mapbox.com/blog/mapbox-drag-and-drop-ios11/
- [WWDC ’17: Data Delivery with Drag and Drop](https://developer.apple.com/videos/play/wwdc2017/227/)
- [UIKit docs: Adopting drag and drop in a custom view](https://developer.apple.com/documentation/uikit/drag_and_drop/adopting_drag_and_drop_in_a_custom_view)

/cc @jmkiley @captainbarbosa @mapbox/ios

**Comment by jmkiley** [comment]
Agreed! This is something I've been exploring, and can see a lot of potential uses. I think that the first step is to look into how/if we can make MGLMapViews conform to [NSItemProviderWriting](https://developer.apple.com/documentation/foundation/nsitemproviderwriting).

Attribution and map views are another challenge. We could adopt a similar approach as what was taken in @captainbarbosa's blog post and switch to static attribution once the drag/drop begins. If the map remains interactive, we could look into adapting the attribution button.
