### ISSUE TITLE
Default annotation image has shrunk

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#9361]
The default annotation image, depicting a red pin, has shrunk by half on iOS.

v3.5.0:

<img width="143" alt="before" src="https://user-images.githubusercontent.com/1231218/27512929-6c755d04-5907-11e7-8818-fe326e4dcf22.png">

v3.6.0-rc.1:

<img src="https://user-images.githubusercontent.com/1231218/27512923-3906f2fc-5907-11e7-88d6-af1db0f6f7df.PNG" width="375" alt="after">

This regression was probably introduced in #9060. There had probably been a size discrepancy between iOS and macOS, but the pointing device on macOS is usually more precise so it wouldn’t’ve posed as much of a problem.

/cc @friedbunny

**Comment by friedbunny** [comment]
Fixed in #9370 and whatever release comes after v3.6.0-rc.1.
