### ISSUE TITLE
Plugin Request: GPX/KML to GeoJSON

### ISSUE THREAD

**Issue by nitrag** [mapbox/mapbox-gl-native#9362]
Not sure where the proper place to request plugins but I'd like to be able to have my users open a GPX or KML file, convert to GeoJSON, then load into one of my map layers. I'm assuming this would be a plugin but natively would also be nice. Currently I'm having to send the data to a server to parse but this prevents offline functionality.

**Comment by tobrun** [comment]
@nitrag great to see you're interested in plugins! On the Android side of things, we have a separate repo for that  in https://github.com/mapbox/mapbox-plugins-android/issues. The iOS equivalent will  be made public soon! Would you be able to repost your request in those repositories instead? Thanks again for the input and sharing your use-case.

**Comment by 1ec5** [comment]
It’s rather long in the tooth, but [Simple-KML](https://github.com/mapbox/Simple-KML/) could be the basis for an implementation of this conversion step on iOS.

**Comment by nitrag** [comment]
@1ec5, would implementations in Swift be acceptable or does it need to be in Obj-C to match the SDK?

Also, I was thinking to keep it lightweight and keep the conversion to simple JSON structure and let `MGLShapeSource ` parse the GeoJSON. That way it can also be saved to disk or uploaded online somewhere.

**Comment by 1ec5** [comment]
I was leaning towards sticking to Objective-C, since the Swift-to-ObjC bridge often requires painful compromises and workarounds and the Swift runtime would end up bundled with otherwise Objective-C projects.
