### ISSUE TITLE
[android] Markers don't rendered correctly

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#9367]
**Platform:** Android 6.0 (Nexus 5)
**Mapbox SDK version:** `release-ios-v3.6.0-android-v5.1.0`

Same steps as #9366

### Steps to trigger behavior

 1. Open activity (Same [code](https://github.com/mapbox/mapbox-gl-native/issues/9366#issue-238509794) as in the first step of #9366)
 2. Click on `ADD` button
 3. App doesn't render correctly some markers

### Expected behavior
App does render all markers correctly

### Actual behavior

![marker_drawable_issue](https://user-images.githubusercontent.com/1668582/27537783-8ea5af2c-5a75-11e7-8326-791a99f401c5.gif)

Note that in this case when using `MarkerViewOptions` it blocks the UI (although after waiting a bit markers are rendered correctly).

**Comment by jfirebaugh** [comment]
Is this reproducible on `master`? It may have been fixed by #9213.

**Comment by Guardiola31337** [comment]
@jfirebaugh you're right, not reproducible on `master`.
Closing.
