### ISSUE TITLE
[ios] shouldChangeFromCamera doesn't allow for constraining the camera to specific bounds

### ISSUE THREAD

**Issue by epau** [mapbox/mapbox-gl-native#9368]
**Platform:** iOS
**Mapbox SDK version:** 3.5

I talked to @1ec5 about this a little bit at WWDC '17, my apologies for posting this so late!!

### The Problem
I want to constrain the viewport such as to not allow scrolling past some MGLCoordinateBounds (ie ne = (10,10) and sw = (-10,-10)).

I'm currently trying to implement this using the following delegate method:
```objective-c 
- (BOOL)mapView:(MGLMapView *)mapView shouldChangeFromCamera:(MGLMapCamera *)oldCamera toCamera:(MGLMapCamera *)newCamera
``` 

This falls short however because I cannot force the camera to move to the bounds, I can only tell it to not move at all (simplified example: bounds = 10, old = 0, new = 15. I'd want to move to 10 but that is not currently possible)

Modifying properties on the `newCamera` instance has no effect since it it's properties aren't used after the delegate call (from [MGLMapView.mm handlePanGesture](https://github.com/mapbox/mapbox-gl-native/blob/40e47556214e999c952c1e88e026d673cdd96c72/platform/ios/src/MGLMapView.mm#L1198))
```objective-c
CGPoint delta = [pan translationInView:pan.view];

MGLMapCamera *toCamera = [self cameraByPanningWithTranslation:delta panGesture:pan];
        
if (![self.delegate respondsToSelector:@selector(mapView:shouldChangeFromCamera:toCamera:)] ||
        [self.delegate mapView:self shouldChangeFromCamera:oldCamera toCamera:toCamera])
{
        _mbglMap->moveBy({ delta.x, delta.y });
        [pan setTranslation:CGPointZero inView:pan.view];
}
```

### Potential Solution

It would be great to have modifications to `newCamera` in the delegate method affect the final result or to have some property/delegate method to restrict the viewport.

**Comment by 1ec5** [comment]
> Modifying properties on the newCamera instance has no effect since it it's properties aren't used after the delegate call

MGLMapCamera is a value class. Merely modifying its properties won’t cause a map view to change: #8930. So you’d need to set the map view’s `camera` property to the modified camera in order to apply a change to any of that camera’s properties. Then return `NO` so to preempt the call to `moveBy()`.

**Comment by epau** [comment]
Setting the map view's `camera` property in `shouldChangeFromCamera` causes some pretty glitchy/jumpy behavior while the user is panning or zooming.
```objective-c
- (BOOL)mapView:(MGLMapView *)mapView shouldChangeFromCamera:(MGLMapCamera *)oldCamera toCamera:(MGLMapCamera *)newCamera {
    if (MGLCoordinateInCoordinateBounds(newCamera.centerCoordinate, self.mapManager.mapBounds)) {
        return YES;
    }
    
    MGLMapCamera *camera = newCamera.copy;
    CLLocationDegrees lat = camera.centerCoordinate.latitude;
    CLLocationDegrees lon = camera.centerCoordinate.longitude;
    
    if (camera.centerCoordinate.latitude < self.mapManager.mapBounds.sw.latitude) {
        lat = self.mapManager.mapBounds.sw.latitude;
    } else if (camera.centerCoordinate.latitude > self.mapManager.mapBounds.ne.latitude) {
        lat = self.mapManager.mapBounds.ne.latitude;
    }
    
    if (camera.centerCoordinate.longitude < self.mapManager.mapBounds.sw.longitude) {
        lon = self.mapManager.mapBounds.sw.longitude;
    } else if (camera.centerCoordinate.longitude > self.mapManager.mapBounds.ne.longitude) {
        lon = self.mapManager.mapBounds.ne.longitude;
    }
    
    camera.centerCoordinate = CLLocationCoordinate2DMake(lat, lon);
    [mapView setCamera:camera animated:NO];
    return NO;
}
```

**Comment by 1ec5** [comment]
I wonder if the glitchy/jumpy behavior is due to #9344.

**Comment by epau** [comment]
Will test with [ios-v3.6.0-rc.1](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.6.0-rc.1) and report back this week

**Comment by epau** [comment]
@1ec5 still seeing the same issues with 3.6

Would it be possible for MapView to have a `MGLCoordinateInCoordinateBounds` property that if set, the MapView would bound all viewport changes to?

**Comment by 1ec5** [comment]
> still seeing the same issues with 3.6

Could you post a screen recording showing the behavior you’re seeing? I tried the code above on both iOS and macOS (which has a slightly different implementation that might be more robust), but it didn’t look jumpy to me, so I’m probably missing something.

> Would it be possible for MapView to have a `MGLCoordinateInCoordinateBounds` property that if set, the MapView would bound all viewport changes to?

Given the existing delegate method, it would be unfortunate to expose a redundant property like the one proposed in #2341. However, I realize that the current workflow is tedious for the simple case of restricting to a particular bounding box. (#8499 would improve the ergonomics around this delegate method.) Hopefully we can make this API work as intended and improve the ergonomics so it feels as natural as a simple property would be.

**Comment by epau** [comment]
Sorry for the long update, but i think we can close this issue.

I am able to get what i want by clamping the `MGLMapView` to some bounds within the `mapViewRegionIsChanging` method. Thanks for looking into this and helping me get to this point.

**Comment by erikvdwal** [comment]
@epau Would you mind sharing your solution? I tried a similar approach, but it resulted in some undesired zooming behavior when hitting the outer bounds. Perhaps my approach was too naive, though. I've put up an [example project](https://github.com/erikvdwal/mapbox-region-example).

At this point, my guess is that the `setVisibleCoordinateBounds(animated:)` method slightly alters the bounds it's been given, which results in the calculated difference not being inaccurate, which in turn causes this behavior. I'm interested to see how your solution is different and if it maybe works around this issue.

**Comment by epau** [comment]
@erikvdwal my solution looks almost identical to yours. [Here's my clamping logc](https://gist.github.com/epau/496b8a464c5703ad1fa4cd4d6d0b2c60) fwiw. 

Could you explain the "undesired zooming behavior"?

**Comment by erikvdwal** [comment]
@epau Thanks!

You should be able to reproduce the behavior I was describing if you run that example project. Basically, If you aren't zoomed out entirely and you pan towards - and hit - one of the edges of the bounding box, the map will start zooming out until you hit the minimum zoomlevel.

**Comment by epau** [comment]
We're still struggling with a solution here.

Is there a way we can properly set a bounding box to restrict the camera to?
Using the delegate simply doesn't cut it since the camera doesn't change where as we want it to move to bounds but not go past it.

**Comment by 1ec5** [comment]
> Would you mind sharing your solution? I tried a similar approach, but it resulted in some undesired zooming behavior when hitting the outer bounds. Perhaps my approach was too naive, though. I've put up an [example project](https://github.com/erikvdwal/mapbox-region-example).

@erikvdwal, that project uses `mapViewRegionIsChanging(_:)`, whereas the suggestion above is to use `mapView(_:shouldChangeFrom:to:)`. Calling `setVisibleCoordinateBounds(_:)` from within `mapViewRegionIsChanging(_:)` is bound to start a feedback loop that’s only broken by hitting the minimum zoom level. [This call to `MGLCoordinateBoundsEqualToCoordinateBounds()`](https://github.com/erikvdwal/mapbox-region-example/blob/f58af1b1424c966759575b06c55758c637dcd36b/MapboxRegionExample/ViewController.swift#L66) attempts to stop the feedback loop as well, but `visibleCoordinateBounds` does differ from `adjusted` because the distance between two latitudes is not uniform. [This difference](https://github.com/erikvdwal/mapbox-region-example/blob/f58af1b1424c966759575b06c55758c637dcd36b/MapboxRegionExample/ViewController.swift#L43) corresponds to one screen distance when applied to the northeast coordinate and another screen distance when applied to the southwest coordinate.

I would recommend an implementation of `mapView(_:shouldChangeFrom:to:)` that steers clear of the `visibleCoordinateBounds` property. I haven’t tried the code below, but hopefully it serves as a useful starting point:

```swift
let clampedCamera = newCamera
// Lots of assumptions; the rest is left as an exercise to the reader.
if oldCamera.altitude == newCamera.altitude && oldCamera.heading == newCamera.heading && newCamera.heading = 0 && oldCamera.pitch == newCamera.pitch && newCamera.pitch == 0 {
    // If panning upward beyond the maximum coordinate bounds…
    if newCamera.ne.latitude > maximumCoordinateBounds.ne.latitude {
        // Where would the northernmost allowed coordinate be on screen before changing the camera?
        let clampedTopRight = mapView.convert(maximumCoordinateBounds.ne, toPointTo: mapView)
        // The map view is the same size regardless of latitude, so offset the top-right point to find the corresponding center point.
        let clampedCenter = CGPoint(x: clampedTopRight.x, y: clampedTopRight.y + mapView.bounds.midY)
        // What coordinate would that center point correspond to before changing the camera?
        clampedCamera.center = mapView.convert(clampedCenter, toCoordinateFrom: mapView)
    }
}
// …
```

Clamping the visible coordinate bounds on a rotated or tilted map would be a particular challenge. There may be an opportunity for [Turf](https://github.com/mapbox/turf-swift/) to provide helper methods to facilitate these calculations. Not sure if any [Turf.js](http://turfjs.org/) methods can be ported over for that.
