### ISSUE TITLE
Mapbox-gl-native does not build on Intel 32 and ARM 64 

### ISSUE THREAD

**Issue by Adrien-Atmosphere** [mapbox/mapbox-gl-native#9374]
I am willing to use tileserver-gl on Linux on different hardware such as Raspberry Pi (ARM 64) or PC 104 card (Intel 32). Tileserver-gl uses mapbox-gl-native as a dependency and the build fails on mapbox-gl-native.  
I came accross several issues during the installation process and I don't have any clue to make it work properly. 

From my understanding, mapbox-gl-native installation process tries to download the package from gyp repositories. This fails because no package version exists for such hardware/node version. 

As a fallback, the installation process does "make node" which fails during configure script because Ninja executable is Intel 64 (so Ninja version is not detected). I downloaded ninja source code and replaced ninja executable in platform/linux as a quick workaround. 

During the build process, it tries to access some binary packages using mason. Once again, this fails because no package exist for such hardware/package version. But it does not try to build those packages from source. So I downloaded mason repository and tried to build them myself using a small script. 

```
 ./mason build glfw 2017-02-09-77a8f10
./mason build mesa 13.0.4
./mason build boost_libprogram_options 1.62.0
./mason build sqlite 3.14.2
./mason build libuv 1.9.1
./mason build nunicode 1.7.1
./mason build libpng 1.6.25
./mason build libjpeg-turbo 1.5.0
./mason build webp 0.5.1
./mason build gtest 1.8.0
./mason build benchmark 1.0.0-1
./mason build icu 58.1-min-size
```

I get an error on clang 3.8 on the build of mesa : 

```
* Downloading https://github.com/include-what-you-use/include-what-you-use/archive/clang_3.8.tar.gz to /usr/src/mason/mason_packages/.cache/clang_3.8.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   152    0   152    0     0    119      0 --:--:--  0:00:01 --:--:--   119
100  419k    0  419k    0     0  48572      0 --:--:--  0:00:08 --:--:--  103k
Error: hash mismatch 7e5c73ce1a2fdd1ffd29fad1ae2628d0134368c6 (expected) != 2b5c5be3c7dcbe555a481083363408399b40e0c8 (actual)
```

And I am stuck at this step. 
Is there any way to build mapbox-gl-native from source without relying on downloads?

**Comment by jfirebaugh** [comment]
We don't provide support for these particular platforms, unfortunately. That said, you may be able to work around this issue by using mesa from a system package manager rather than mason. Try removing `mason_use(mesa VERSION 13.0.4)` and `target_add_mason_package(mbgl-core PUBLIC mesa)` from `linux/config.cmake`.

**Comment by jakehewitt** [comment]
@Adrien-Atmosphere Did you ever figure out running Tileserver-gl on ARM?
