### ISSUE TITLE
IOS: [ERROR] {}[Style]: Failed to load glyph range 0-255 for font stack Open Sans Bold,Arial Unicode MS Bold: The Internet connection appears to be offline.

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [mapbox/mapbox-gl-native#9375]
**Platform**:  *IOS*
**Mapbox SDK version:**   *ios-v3.6.0-rc.1*, but it's occurring in previous version too

### Steps to trigger behavior

 1. Turn off the Wifi and mobile data and open the application 
 2. Add `MGLSymbolStyleLayer ` on map it's not adding, its returning warning in console as.

Console:  

> [ERROR] {}[Style]: Failed to load glyph range 0-255 for font stack Open Sans Bold,Arial Unicode MS Bold: The Internet connection appears to be offline.

### Expected behavior

1. Need to add `MGLSymbolStyleLayer` on map in offline.

### Actual behavior

1. It's not adding the style layer on map in offline, but it's is adding in online.

Actually, I removed the below code then it's working,

`symbolGraphicsLayer?.textFontNames = MGLConstantStyleValue<NSArray>(rawValue: ["Open Sans Bold","Arial Unicode MS Bold"]!)`

But, it's adding the default "font" for text on map. Can anyone look into this. 

Thanks.

**Comment by jfirebaugh** [comment]
Hi @ThiyagarajanShivSankaran. The behavior you're describing is expected. Symbol layers with text rely on downloading glyph ranges to obtain the font stack data they need for rendering. If you need a symbol layer with the font stack `"Open Sans Bold","Arial Unicode MS Bold"` to be available offline, you'll need to create an offline pack with a style that uses that stack.

**Comment by AEiosApp** [comment]
@ThiyagarajanShivSankaran

Have you found a solution, can you share?
