### ISSUE TITLE
Map setOnCameraMoveStartedListener not working

### ISSUE THREAD

**Issue by musicha** [mapbox/mapbox-gl-native#9376]
**Platform:** Android
**Mapbox SDK version:** 5.1.0-beta.5

### Steps to trigger behavior

`map.setOnCameraMoveStartedistener {  ...  }`

### Expected behavior
Listener is triggered

### Actual behavior
Listener is not triggered

### Workaround
If you set idle listener, then it works as expected
`map.setOnCameraIdleListener {  ...  }`

Additionally there is a typo in map.setOnCameraMoveStarted **L** istener

**Comment by tobrun** [comment]
Validated that this is fixed with https://github.com/mapbox/mapbox-gl-native/pull/9339
Thank you for the report! and for testing out the beta.
