### ISSUE TITLE
Link style design guide to mobile design blog post

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#9377]
Let’s link the “[For Style Authors](https://www.mapbox.com/ios-sdk/api/3.5.4/for-style-authors.html#designing-for-ios)” guide ([source](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/docs/guides/For%20Style%20Authors.md.ejs)) to the “[Designing maps for mobile devices](https://www.mapbox.com/blog/designing-maps-for-mobile-devices/)” blog post that just went out.

/cc @jmkiley @natslaughter

**Comment by 1ec5** [comment]
Actually, this ticket tracks linking in the other direction, from the guide to the blog post, because the blog post is so thorough. 😄

**Comment by jmkiley** [comment]
Addressed in #9387
