### ISSUE TITLE
Zoom pivot ignores maps padding

### ISSUE THREAD

**Issue by johanneslaubermoovel** [mapbox/mapbox-gl-native#9382]
**Platform:** Android 
**Mapbox SDK version:**  5.1.0-beta.3

### Steps to trigger behavior
maps.setPadding(0, 0 ,0 ,600)

### Expected behavior
if the height of the screen would be 1200px, I would assume when zooming in, the pivot of the zoom would be at 300px from the top. But it's still at 600px, which would be correct if there is no padding.

An other expected behavior, which I would prefer, is what Gmaps is doing. The pivot of zooming is always at the position of the zoom gesture.

### Actual behavior
The pivot of zooming is at 600px from the top (On a 1200px heigh screen)

**Comment by tobrun** [comment]
> the height of the screen would be 1200px, I would assume when zooming in, the pivot of the zoom would be at 300px from the top

The focal point of the zoom = the place you double tapped or the center point of the scale gesture.
We don't override the focal point when setting a padding. You can achieve this effect yourself by setting the focal point manually with `UiSettings#setFocalPoint(PointF point)`.

Work around provided, not immediate plans of adding this as default behaviour, closing.
