### ISSUE TITLE
Several bugs in beta version 5.1.0-beta5

### ISSUE THREAD

**Issue by MateusCarvalho** [mapbox/mapbox-gl-native#9383]
Hello, I'm trying to use the last beta of Android, but I do not understand why there are several simple bugs that do not exist in the production version, for example the crash app sometimes starts and does not take the user's location when starting.
Does the beta require other external libraries?

**Comment by tobrun** [comment]
Thank you for your report, could you be more concrete in your issue creation?
For example fill in the following template:

```
<!--
Hello and thanks for contributing! To help us diagnose your problem quickly, please:

 - Include a minimal demonstration of the bug, including code, logs, and screenshots.
 - Ensure you can reproduce the bug using the latest release.
 - Only post to report a bug or request a feature; direct all other questions to: https://stackoverflow.com/questions/tagged/mapbox
-->

**Platform:**
**Mapbox SDK version:**

### Steps to trigger behavior

 1.
 2.
 3.

### Expected behavior

### Actual behavior

```
