### ISSUE TITLE
[android] highway-shield & highway number alignment/pitch issues

### ISSUE THREAD

**Issue by natslaughter** [mapbox/mapbox-gl-native#9395]
**Android**
**SDK 4.2.0-beta.1:**

### Steps to trigger behavior

While using an _internal map SDK testbed application_ for Android to test map styles, I noticed two highway shield related issues in all map styles. 

### Expected behavior
- highway shields and highway numbers to be aligned and centered
- highway numbers `text-pitch-alignment` = auto

### Actual behavior
- highway shields and highway numbers are not aligned
- highway numbers `text-pitch-alignment` = map

![highway-shields](https://user-images.githubusercontent.com/16616543/27706851-28cc1cfe-5ce1-11e7-8aa8-0a7d2e9eabcc.gif)

**Comment by jfirebaugh** [comment]
cc @ChrisLoer

**Comment by 1ec5** [comment]
I can’t reproduce this issue in the navigation styles included with our iOS navigation SDK, using iOS SDK v3.6.0-rc.1. iOS SDK v3.6.0-rc.1 and Android SDK 5.1.0-beta.3 are built from the same release branch, albeit from slightly different commits.

**Comment by 1ec5** [comment]
The behavior depicted in the screen recording looks a lot like #5683. If I’m not mistaken, this is an old internal application that has not been updated in several months. It’s unlikely that it has Android SDK 5.1.0-beta.3.

Additionally, @ChrisLoer’s work in #9009 hasn’t even landed in master, let alone the release branch.

**Comment by 1ec5** [comment]
Confirmed that this application uses Android SDK v4.2.0-beta.1. The fix for #5683 didn’t make it into the Android SDK until v4.2.0-beta.4.
