### ISSUE TITLE
[Android] In rare cases, anchoring of MarkerView behaves incorrectly.

### ISSUE THREAD

**Issue by oreyg** [mapbox/mapbox-gl-native#9407]
**Platform:Android**
**Mapbox SDK version:4.2.2**

### Steps to trigger behavior

 1. Place PulseMarkerView provided in [zip-archive](https://drive.google.com/file/d/0BzxqauCtVQrWVTgyQmNnNFZCejA/view?usp=sharing) on the map.
 2. Notice that anchoring doesn't work as expected. 

### Expected behavior

Anchor is expressed in two numbers from 0 to 1, where [0,0] is the upper-left corner.

### Actual behavior

Anchor is expressed in pixels, perhaps because the mapbox assumes that the View size is 1x1px.

P.S. addMarker pseudocode
```
 mapboxMap.addMarker(
                new PulseMarkerViewOptions()
                .setPosition(Position)
                .setAnchor(anchor, anchor)
                .setFlat(true));
```

P.S.S The files in the archive were stripped-down for nda considerations

**Comment by oreyg** [comment]
[zip-archive](https://drive.google.com/file/d/0BzxqauCtVQrWVTgyQmNnNFZCejA/view?usp=sharing)

**Comment by tobrun** [comment]
@oreyg could you retest with a more recent version. (e.g. 5.1.0?). The logic around anchoring has changed since the latest release. Going to close this for now, feel free to reach out if this is still an issue.
