### ISSUE TITLE
bug LineLayer update from setGeoJsonSource()

### ISSUE THREAD

**Issue by klblk** [mapbox/mapbox-gl-native#9409]
**Platform:** Android (tested on Nexus 4, Android 5.1.1)
**Mapbox SDK version:** 5.1.0 (reproduced on beta.2-stable, not reproduced beta.1)

### Steps to trigger behavior
One feature (for create and update geoJsonSouce): 
```
private static Feature getOneFeature(List<LatLong> path, int color) {
        List<Position> points = new ArrayList<>();
        for (LatLng latLng : path) {
            points.add(Position.fromCoordinates(latLng.getLongitude(), latLng.getLatitude()));
        }
        JsonObject jsonObject = new JsonObject();
        jsonObject.addProperty(PROPERTY_COLOR, PropertyFactory.colorToRgbaString(color));
        Feature feature = Feature.fromGeometry(LineString.fromCoordinates(points), jsonObject);
        return feature;
    }
```

Layer:
```
LineLayer lineLayer = new LineLayer(LAYER_NAME_TRANSPORTS_LINE, SOURCE_NAME_TRANSPORTS_LINE);
        lineLayer.setProperties(
                PropertyFactory.lineWidth(5f),
                PropertyFactory.lineColor(Function.property(PROPERTY_COLOR, Stops.<String>identity())),
                PropertyFactory.lineJoin(Property.LINE_JOIN_ROUND)
        );
```
Update source: transportLineSource.setGeoJson()
### Expected behavior
Remove old lines and draw new lines

### Actual behavior
Sometimes, old lines remains (as if GeoJson source not updated), but on other zoom draw new lines. 
Video example: 
https://drive.google.com/open?id=0B1bUt15ODm_hbVMzYXhwNEZDYlU
Since 25s: 
if zoom=14..15 draw old source lines, else new source lines. 
Layer does not depend on zoom.

**Comment by jfirebaugh** [comment]
This should be fixed in v5.2.0. Please open a new issue if you still encounter the issue.
