### ISSUE TITLE
Since 5.1.0 : Zoom + Dragging not working

### ISSUE THREAD

**Issue by paulVulog** [mapbox/mapbox-gl-native#9413]
Since the 5.1.0 update, I am no more able to zoom (in/out) **and** drag the map at the same time. 
This result in a weird gesture experience.

Waiting for someone else or the demo app  with the 5.1.0 release to confirm this issue.

**Comment by LukasPaczos** [comment]
@paulVulog I experience the same issue on 5.1.0.

**Comment by tobrun** [comment]
The behaviour was changed as part of https://github.com/mapbox/mapbox-gl-native/pull/9339, more specifically [this](https://github.com/mapbox/mapbox-gl-native/pull/9339/files#diff-dc8b8b458b4be05d4cfad1bbafea82aeL556) line. Note that we haven't removed support for it but this is rather a side-effect of not locking in rotation gestures anymore. This was needed to get a correct integration for the new camera change listeners + this part of the gesture handling is something we wanted to revisit for a while (you are often not able to do a rotate gesture in pre 5.1.0 versions, you can get stuck in scaling). Thank you for flagging this, I wasn't aware that users were expecting to scroll with a two finger drag.
