### ISSUE TITLE
Zoom level mapbox vs GoogleMaps web

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#9417]
**Platform: iOS 10.3**
**Mapbox SDK version: 3.5**

### Steps to trigger behavior

 1. launch the demo app with standard street style
 2. set a center and zoom level (17 for example)
 3. compare the map level compared to other providers

### Expected behavior
Zoom levels should be comparable

### Actual behavior
Mapbox GL zoom level 15 seems to correspond to GoogleMaps zoom level 17.
I just don't understand why is that. It's not a "bug", but if zoom levels can't be compared, it can be a concern for several people.
![simulator screen shot 5 juil 2017 a 10 33 08](https://user-images.githubusercontent.com/8179069/27856054-09623f66-616d-11e7-8d11-1aef16504351.png)
![capture d ecran 2017-07-05 a 10 34 02](https://user-images.githubusercontent.com/8179069/27856062-0e20eef8-616d-11e7-962a-78c127858f6b.png)

**Comment by jfirebaugh** [comment]
This is expected behavior; there's no universal standard for how big (in screen size) the mercator world should be at z0, hence no standard for other zooms.

**Comment by RomainQuidet** [comment]
Thanks for the feedback. Is it a design choice ?
It's even stranger on the web, many providers I tested at zoom 17 are equals, except Mapbox which is at zoom 16. There's an offset of one zoom on the web, 2 zoom levels on the mobile... 
![googlemaps 17](https://user-images.githubusercontent.com/8179069/27925736-298433fc-6286-11e7-8cfd-1284aa1ea548.jpeg)
![here 17](https://user-images.githubusercontent.com/8179069/27925734-297f927a-6286-11e7-9d71-8f4d14016d59.jpeg)
![mapbox 16z](https://user-images.githubusercontent.com/8179069/27925735-297fbe62-6286-11e7-909e-c2378fbfe618.jpeg)
![mappy 17z](https://user-images.githubusercontent.com/8179069/27925737-29847b82-6286-11e7-9f94-cf3d43d4df5f.jpeg)
