### ISSUE TITLE
[android] Performance issues when making markers invisible

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#9419]
After changes from #9282 there is a huge performance issue when we are trying to make `MarkerView`s inivisible (or rather `View.GONE`), because `ViewTreeObserver.OnPreDrawListener` will be continuously registered [here](https://github.com/mapbox/mapbox-gl-native/pull/9282/files#diff-955e62d3fd63822ca2375e74271ceb05R196) and trying to invalidate `MarkerView`.

**Comment by Guardiola31337** [comment]
Thanks for the contribution @LukasPaczos!
This has landed in #9420 closing.
