### ISSUE TITLE
Why do you need support 25.3.1?

### ISSUE THREAD

**Issue by andretietz** [mapbox/mapbox-gl-native#9429]
**Platform:** Android
**Mapbox SDK version:** 5.1.0

### Steps to trigger behavior

 1. try building a library project with mapbox on android using support libraries lower than 23.5.1

### Expected behavior
Especially when building libraries, I would expect mapbox to use the lowest possible version of the (android support) library, in order to build my library which will be used on apps that do not include the support library 

### Actual behavior
Getting dependency clashes on building my library because I cannot update my support libs to 23.1.0, since apps are building on downwards support

**Comment by Guardiola31337** [comment]
Hey @andretietz 👋 thanks for reaching out and report your problem.

Is there any sample of your `build.gradle` config that you can share? That would be really helpful.

BTW, you could exclude modules from being included this way:

```groovy
compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.0@aar'){
    transitive=true
    exclude module: 'support-compat'
}
```

**Comment by tobrun** [comment]
The support libraries can be seen as an extension of the general Android SDK and these libraries follow the same update cycles as the underlying tools. For this project we maintain the current stable versions. In general library development I would have agreed on the statement of using the lowest possible version but when it comes to android dependencies is strongly disagree. The reason for that is two fold: Android has been build up around backwards compatibility and gradle is flexible enough to handle dependency mismatching. 

Additionally, when are you hitting this error? when you are updating your project dependencies? You will not hit this error if you were able to compile it before. Only when you start tinkering with updating this lib dependency or others that you will start running in issues shown OP. As noted by @Guardiola31337, this shouldn't be blocking you. There are workaround and ways to force using the version you want. You can look more into the different dependencies that are pulled in with `./gradlew :module_name:dependencies` and exclude dependencies accordingly. 

Closing as non-actionable.
