### ISSUE TITLE
Make network interface more resilient to captive portals

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#943]
Some captive portals hijack DNS and use self-signed certificates to redirect the user to a log in. In this case, our requests will likely fail. We should treat certificate errors as temporary connection problems and back off exponentially to see whether the issue has been fixed.

**Comment by ljbade** [comment]
It would be interesting to see how Google and Apple maps behave with bad certificates.

**Comment by jfirebaugh** [comment]
We do use exponential backoff now.
