### ISSUE TITLE
Android black screen

### ISSUE THREAD

**Issue by thomas-huet** [mapbox/mapbox-gl-native#944]
I have cloned the latest master, updated submodules, run `make android` and installed `app-debug.apk` on a nexus 7 but when I launch the app it only displays a black map (that is I have the grey toolbar with the style selector and the "center on current position" button (plus a "i" button that doesn't seem to do anything) and the small compass but the map is black).
I can rotate the map (it makes the compass move) and maybe also zoom in and out (but for this there is no sign that it works). I can activate / deactivate tracking of position. I can change style (but then it crashes).
I have a valid mapbox token, I use mapbox studio on the same computer I use to compile mapbox GL.

**Comment by ljbade** [comment]
Yeah the master is a bit unstable on Android currently.

**Comment by thomas-huet** [comment]
I no longer have this problem with latest builds.
