### ISSUE TITLE
Animate marker Android sdk 5.1.0

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#9453]
Is there any way to animate a marker? I want to rotate the marker I added to the map:

spawnmarker = map.addMarker(new MarkerOptions()
                        .position(new LatLng(result.Lat + 0.0003, result.Lon + 0.0003))
                        .title(result.Name)
                        .snippet("spawnitem")
                        .icon(icon)
                );

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
