### ISSUE TITLE
selectAnnotation changes the tracking mode to None

### ISSUE THREAD

**Issue by davidovich** [mapbox/mapbox-gl-native#9455]
**Platform: ios**
**Mapbox SDK version: 3.6.0**

### Steps to trigger behavior

 1. Change the tracking mode to MGLUserTrackingModeFollow
 2. use the **- (void)selectAnnotation:(id <MGLAnnotation>)annotation animated:(BOOL)animated** API
 3. See the tracking mode change to MGLUserTrackingModeNone

### Expected behavior

Selecting an annotation should not be coupled with the tracking mode. In MKMapKit, you can show an annotation while tracking.

I have a use case where the annotations are shown automatically while the user walks. The current hard requirement to return to no tracking breaks this.

A user setting through delegate should allow backward compatible support for the current behavior, while allowing to decouple the tracking mode from the annotation presentation.

Relevant code: https://github.com/mapbox/mapbox-gl-native/blame/ios-v3.6.0/platform/ios/src/MGLMapView.mm#L3794-L3797

### Actual behavior

When the callout is shown, the tracking mode forcefully gets changed to MGLUserTrackingModeNone.

**Comment by 1ec5** [comment]
> A user setting through delegate should allow backward compatible support for the current behavior, while allowing to decouple the tracking mode from the annotation presentation.

The current behavior is a departure from MapKit's behavior that isn't documented anywhere. Originally selecting an annotation would disable user tracking because fallouts were unable to move with the annotation as the camera moves. However, we fixed that bug in #6676. I think we could reasonably switch to MapKit's behavior unconditionally without considering it a breaking change.

/cc @friedbunny

**Comment by friedbunny** [comment]
> I think we could reasonably switch to MapKit's behavior unconditionally without considering it a breaking change.

I’m not sure about how breaking it’ll be, but I agree that we should get rid of any obsolete selection/tracking mode interactions.
