### ISSUE TITLE
Map Freezing (Or Not Rendering) After Undefined Amount Of Time

### ISSUE THREAD

**Issue by mitchBlock** [mapbox/mapbox-gl-native#9459]
**Platform:** Android
**Mapbox SDK version:** 5.1.0

### Steps to trigger behavior

 1. Load map
 2. Zoom, move, or wait
 3. Map freezes, zooming no longer works, but rotating seems to register with the compass

### Expected behavior
Able to zoom, move, or rotate freely with no freezing

### Actual behavior
Map freezes after a few seconds

I've been trying to use a map in my app, but I'm getting the above behavior on a Sony Xperia Z5 (model E6653) with API 22. My app doesn't exhibit this behavior on any Samsung (S3 with API 18, S5 with APIs 19, 21, and 23) or any emulated device running API 22 or otherwise. I've looked around for a solution, and have found that issues [#8030](https://github.com/mapbox/mapbox-gl-native/issues/8030), [#9441](https://github.com/mapbox/mapbox-gl-native/issues/9441), [#9389](https://github.com/mapbox/mapbox-gl-native/issues/9389), and [#8728](https://github.com/mapbox/mapbox-gl-native/issues/8728) are all pretty much the behavior I'm seeing, but there are no resolutions. Logcat doesn't say anything when the map stops responding, and the behavior can be replicated with the most basic app from the [overview](https://www.mapbox.com/android-docs/map-sdk/overview/).

**Comment by kikothemaster** [comment]
For anyone with fragment map view not moving, use `app:mapbox_renderTextureMode="true"` inside MapView in xml.
