### ISSUE TITLE
How can load iconImage from url ?

### ISSUE THREAD

**Issue by wangtianming** [mapbox/mapbox-gl-native#9461]
**Platform: Android
**Mapbox SDK version:5.1.0
I want load iconImage from url (about properties),How do I implement it?

**Comment by tobrun** [comment]
To add images to be used by runtime style components use:

```java
/**
   * Adds an image to be used in the map's style
   *
   * @param name  the name of the image
   * @param image the pre-multiplied Bitmap
   */
  @UiThread
  public void addImage(@NonNull String name, @NonNull Bitmap image) {
    nativeMapView.addImage(name, image);
  }
```

The former parameter "name" is the id you will be using for referencing this image later on. The latter parameter requires using a bitmap so you need to download your bitmap first from your url. For this you can use open source libraries as [Picasso](http://square.github.io/picasso/) or [glide](https://github.com/bumptech/glide).

**Comment by wangtianming** [comment]
I know addImage method,but must download bitmap before addLayer ? I want use more than one icon，if must first download bitmap，that will be slow.Is there a solution?

**Comment by tobrun** [comment]
Yes, there are solutions for that but these are not related to the Mapbox SDK as this is a common issue you face while developing Android applications. For support on such issues, please search or post on https://stackoverflow.com/.
