### ISSUE TITLE
[iOS] Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by robipresotto** [mapbox/mapbox-gl-native#947]
Hello Guys,

I'm building for iOS (XCODE Version 6.1.1 (6A2008a)) and after link the libMapboxGL.a my project got a lot of "link" issues, see my screenshot.

I'm building the lib following the iOS Steps on readme and everything is linked on my project,
for build a clean project is needed auxiliar frameworks? Any idea?

Thanks in advance and congrats for the amazing job.

![by robitto 2015-03-05 at 16 11 53 2](https://cloud.githubusercontent.com/assets/3818948/6507613/72d8bfde-c353-11e4-9ef2-2dbbfe154160.png)

**Comment by robipresotto** [comment]
Missing frameworks

**Comment by picciano** [comment]
I am seeing this too. Which frameworks need to be added?

**Comment by friedbunny** [comment]
[According to the old docs that haven't quite made it over yet:](https://github.com/mapbox/mapbox-gl-cocoa/blob/f36ee137496c8cf11ab604cacbb63ca645e6741c/dist/README.md)
   - `CoreGraphics.framework`
   - `CoreLocation.framework`
   - `GLKit.framework`
   - `OpenGLES.framework`
   - `SystemConfiguration.framework`
   - `UIKit.framework`
   - `libc++.dylib`
   - `libsqlite3.dylib`
   - `libz.dylib`

**Comment by picciano** [comment]
Thank you so much. That saved a lot of trial and error.
One more: ImageIO.framework
