### ISSUE TITLE
LatLngBounds Builder in iOS SDK

### ISSUE THREAD

**Issue by lamhuynh96** [mapbox/mapbox-gl-native#9471]
I have developing an ios version of my app using Mapbox but I've faced some confusion between iOs and Android SDK. 
In **Android SDK**, I can use **LatLngBounds.Builder** to get bound of a **Multipolygon coordinates** which is from GeoJSON and move camera to it with **CameraUpdateFactory.newLatLngBounds**. 
But in **iOS SDK**, I can't find any builder like that, there is **MGLMapView.cameraThatFitsCoordinateBounds** but it needs **SouthWest** and **NorthEast** coordinates and I haven't found a way to calculate them from a **Multipolygon coordinates**.
Is there a solution to solve this problem? Thank you so much.

**Comment by tobrun** [comment]
I'm not aware of the iOS SDK capabilities on this topic but you can calculate this yourself. 
Below the java code used to calculate NorthWest and SouthEast:

```java
  static LatLngBounds fromLatLngs(final List<? extends ILatLng> latLngs) {
    double minLat = 90;
    double minLon = 180;
    double maxLat = -90;
    double maxLon = -180;

    for (final ILatLng gp : latLngs) {
      final double latitude = gp.getLatitude();
      final double longitude = gp.getLongitude();

      minLat = Math.min(minLat, latitude);
      minLon = Math.min(minLon, longitude);
      maxLat = Math.max(maxLat, latitude);
      maxLon = Math.max(maxLon, longitude);
    }

    return new LatLngBounds(maxLat, maxLon, minLat, minLon);
  }
```

I will let someone from @mapbox/ios add some context or code. Above code should unblock you for now.

**Comment by lamhuynh96** [comment]
Thank for your help @tobrun

**Comment by 1ec5** [comment]
[MGLMultiPolygon](https://www.mapbox.com/ios-sdk/api/3.6.0/Classes/MGLMultiPolygon.html) conforms to the MGLOverlay protocol, so it has an [`overlayBounds`](https://www.mapbox.com/ios-sdk/api/3.6.0/Protocols/MGLOverlay.html#/c:objc%28pl%29MGLOverlay%28py%29overlayBounds) property of type `MGLCoordinateBounds`.

MGLMultiPolygon is also a subclass of MGLShape, which conforms to the MGLAnnotation protocol, so you can pass the multipolygon into [`-[MGLMapView showAnnotations:animated:]`](https://www.mapbox.com/ios-sdk/api/3.6.0/Classes/MGLMapView.html#/c:objc%28cs%29MGLMapView%28im%29showAnnotations:animated:) to make the map’s viewport fit the multipolygon:

```swift
mapView.showAnnotations([multiPolygon], animated: true)
```

**Comment by kritiagarwal13** [comment]
> I'm not aware of the iOS SDK capabilities on this API but you can calculate this yourself.
> Below the java code used to calculate NorthWest and SouthEast:
> 
> ```java
>   static LatLngBounds fromLatLngs(final List<? extends ILatLng> latLngs) {
>     double minLat = 90;
>     double minLon = 180;
>     double maxLat = -90;
>     double maxLon = -180;
> 
>     for (final ILatLng gp : latLngs) {
>       final double latitude = gp.getLatitude();
>       final double longitude = gp.getLongitude();
> 
>       minLat = Math.min(minLat, latitude);
>       minLon = Math.min(minLon, longitude);
>       maxLat = Math.max(maxLat, latitude);
>       maxLon = Math.max(maxLon, longitude);
>     }
> 
>     return new LatLngBounds(maxLat, maxLon, minLat, minLon);
>   }
> ```
> 
> I will let someone from @mapbox/ios add some context or code. Above code should unblock you for now.

How am I supposed to get coordinates of all the points of each shape in a shape collection feature? 
Please, can you help me with this?
