### ISSUE TITLE
Bright Style Isn't On iPhone 6 Plus Simulator

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#948]
While looking into #843 I noticed that the Bright Style on iPhone 6 Plus simulator is rendering black for water as well as Interstate Symbols  I don't know enough about Sprites yet but am thinking that they're related.

![ios simulator screen shot mar 5 2015 4 53 31 pm](https://cloud.githubusercontent.com/assets/989928/6516583/d1b425fc-c358-11e4-852c-2f7d5ff7d30c.png)

/cc @incanus @kkaefer @ansis @ljbade

**Comment by 1ec5** [comment]
iPhone Plus is 3× rather than 2×. Could that be the problem?

**Comment by friedbunny** [comment]
The Bright style uses a cute wave sprite for the water, so I think this will be #843.

**Comment by incanus** [comment]
Yep, dupe.

**Comment by bleege** [comment]
Cool.  Thanks for confirming guys!
