### ISSUE TITLE
Preview image in Android Studio layout editor

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9480]
To support the visual layout editor in Android Studio. We currently package a preview image inside our SDK. This image isn't used at runtime and it's currently growing the resulting .aar file. We should look into hosting this image online and only download it when the visual layout editor is shown to the developer. 

The preview image can be found [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/res/drawable-xxhdpi/mapbox_mapview_preview.jpg)

**Comment by Guardiola31337** [comment]
We should consider using the new [`@sample` resource type](https://www.youtube.com/watch?v=Hx_rwS1NTiI&index=51&list=PLOU2XLYxmsIKC8eODk_RNCWv3fBcLvMMy#t=07m20s) included in [Android Studio 3.0](https://developer.android.com/studio/preview/features/index.html) as an option to tackle this one.

**Comment by tobrun** [comment]
I tried running with approach in OP but the IDE isn't able to perform network requests for content in the layout editor. For now I removed integration in #9657 (the preview image is taking up too much space in the aar). Let's wait until AS 3.0 is released with the `@sample` integration as mentioned in https://github.com/mapbox/mapbox-gl-native/issues/9480#issuecomment-318018132

**Comment by Guardiola31337** [comment]
Have you ever tried creating a custom layout which loads the preview image when `isInEditMode()`? i.e. something like this:

```java
public class CustomView extends View {
    public CustomView(Context ctx) {
        super(ctx);
	if(isInEditMode()) {
            loadResourceUrl();	
	}
    }
}
```
☝️ could be another solution ¯\\\_(ツ)\_/¯

**Comment by tobrun** [comment]
yes, see https://github.com/mapbox/mapbox-gl-native/issues/9480#issuecomment-319368606

**Comment by 1ec5** [comment]
How much of a size increase would be acceptable for this feature? I noticed that the [previously bundled preview images](https://github.com/mapbox/mapbox-gl-native/blob/11b8f2dcb23bc076a8e6f939de458d001f79eeeb/platform/android/MapboxGLAndroidSDK/src/main/res/drawable-nodpi/mapbox_mapview_preview.jpg) are JPEGs, whereas PNG or GIF would be more efficient representations of Streets style screenshots. Perhaps we could even switch to a less busy style like Light or Dark, or come up with a more abstract, stylized representation that could be represented as a vector drawable, to further reduce the file sizes?
