### ISSUE TITLE
Error when trying to update pod from version 3.5.4 to 3.6

### ISSUE THREAD

**Issue by druzo** [mapbox/mapbox-gl-native#9481]
**Platform:IOS**
**Mapbox SDK version:3.6**

### Steps to trigger behavior

when I'm trying to update using cocoa pods from version 3.5.4 to 3.6, i've received the following error:
[!] Error installing Mapbox-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/hc/srv3554s5flbn2gh0_jg5xh40000gn/T/d20170712-95798-1l6uxn8/file.zip https://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-3.6.0-dynamic.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 89 68.5M   89 61.3M    0     0   119k      0  0:09:48  0:08:46  0:01:02     0
curl: (56) SSLRead() return error -9806

### Expected behavior
Update to 3.6 version
### Actual behavior
Still on 3.5.4

**Comment by fabian-guerra** [comment]
Hi. Thank you for reporting this. Did you tried to `pod update` then `pod install`?

**Comment by druzo** [comment]
Hello, i try to do this before, but still on the older version, i think this error is because the package wasn't downloaded completed, but is not a network problem, because i've updated others PODS like FABRIC and Crashlytics today.

**Comment by fabian-guerra** [comment]
Does your pod looks like: `pod 'Mapbox-iOS-SDK', '~> 3.6'`? I'm able to witch between versions without a problem.

**Comment by emraz** [comment]
Same problem . Please see the below messages , which I got from terminal during pod update.
Installing Mapbox-iOS-SDK 4.4.1 (was 4.2.0)

[!] Error installing Mapbox-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/t3/0s41rl0x033_s0jy175td73m0000gn/T/d20180923-3259-1q3rmbk/file.zip https://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-4.4.1-dynamic.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 58 96.2M   58 55.8M    0     0  39139      0  0:42:59  0:24:56  0:18:03     0
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

**Comment by funmiayinde** [comment]
Facing same error @emraz, have you find a way around it

[!] Error installing Mapbox-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/mz/2j9v60_56kj135sjy93f3qxw0000gn/T/d20181227-11982-12kbqfs/file.zip https://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-3.7.8-dynamic.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

**Comment by muhammadrizwananjum** [comment]
Installing Mapbox-iOS-SDK (4.11.0)

[!] Error installing Mapbox-iOS-SDK
[!] /anaconda3/bin/curl -f -L -o /var/folders/md/8g5s4_fj1g1gl1mv8qz3wr680000gn/T/d20190520-45271-1o66vbq/file.zip https://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-4.11.0-dynamic.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  7  124M    7 9128k    0     0  13236      0  2:44:14  0:11:46  2:32:28     0
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
