### ISSUE TITLE
Markers disappear when zooming in/out fast

### ISSUE THREAD

**Issue by mrfaa** [mapbox/mapbox-gl-native#9487]
**Platform: Android **
**Mapbox SDK version: 5.1.0**

### Steps to trigger behavior

Hi Team,

attached you will find a short video, which shows the bug i have identified in the latest stable mapbox version. I used the Demo App. When I zoom out quickly some marker disappear. When i pan the map again the markers appear again. Is this a normal behavior? I have in my app round about 400 markers. Most of them disappear when zooming fast in/out and appear again when i pan the map.

Best
Fabian

### Expected behavior
All markers remain visible.

### Actual behavior
Markers disappear.
![videotogif_2017 07 12_18 39 07 1](https://user-images.githubusercontent.com/3984124/28129359-50b577b8-6733-11e7-9904-a5ed6d8240a0.gif)

**Comment by tobrun** [comment]
Thank you for the report @mrfaa, 
adding context here that the marker shown in the gif are MarkerViews.

**Comment by tobrun** [comment]
normally those markers should re show after a maximum of 250 ms (this is what I'm observing in the MarkerViewActivity) Though these are shown at a high zoomlevel, I'm guessing this issue only shows at low zoomlevel as we probably aren't hitting the correct map change events for triggering an update to MarkerViews.

**Comment by tobrun** [comment]
In any case, I would advice you to look into using SymbolLayer instead. We will be deprecating support for MarkerViews in an upcoming release. See #9365.

**Comment by tobrun** [comment]
MarkerView is going to be deprecated with https://github.com/mapbox/mapbox-gl-native/pull/9782. We are no longer maintaining this API and will remove it in future versions of the SDK. As noted in the deprecation message. We are advising users to leverage SymbolLayer instead (you can use the sample code in #9782 to convert Android SDK views to an Image to be used as a Symbol). While we no longer maintain the API we are happy to accept any PRs on it.
