### ISSUE TITLE
NullPointerException in onSaveInstanceState

### ISSUE THREAD

**Issue by PhanVanLinh** [mapbox/mapbox-gl-native#9491]
I face a strangle problem that I receive from my users via Crashlytic after I update mapbox from 4 to 5

**Here is my code**
```
public abstract class BaseMapFragment extends Fragment {
    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Mapbox.getInstance(getActivity(), BuildConfig.MAPBOX_TOKEN);
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        mMapView = view.findViewById(R.id.map);
        mMapView.onCreate(savedInstanceState);
    }

    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        mMapView.setStyleUrl(...);
        mMapView.getMapAsync(...);
    }

    @Override
    public void onStart() {
        super.onStart();
        mMapView.onStart();
    }

    @Override
    public void onResume() {
        super.onResume();
        mMapView.onResume();
    }

    @Override
    public void onPause() {
        mMapView.onPause();
        super.onPause();
    }

    @Override
    public void onStop() {
        mMapView.onStop();
        super.onStop();
    }

    @Override
    public void onDestroy() {
        mMapView.onDestroy();
        super.onDestroy();
    }

    @Override
    public void onLowMemory() {
        mMapView.onLowMemory();
        super.onLowMemory();
    }

    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mMapView.onSaveInstanceState(outState);
    }
}
```
**Error log in Crashlytics**

> Fatal Exception: java.lang.NullPointerException
> Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.MapView.onSaveInstanceState(android.os.Bundle)' on a null object reference
> com.lab.mapion.screen.BaseMapFragment.onSaveInstanceState (BaseMapFragment.java:101)
> android.support.v4.app.Fragment.performSaveInstanceState (Fragment.java:2244)
> android.support.v7.app.AppCompatActivity.onSaveInstanceState (AppCompatActivity.java:511)
> com.lab.mapion.screen.main.MainActivity.onSaveInstanceState (MainActivity.java:134)
> android.app.Activity.performSaveInstanceState (Activity.java:1439)
> com.android.internal.os.ZygoteInit.main (ZygoteInit.java:755)

After test I know, `onSaveInstanceState` always call after `onPause` and inside `onPause` I have use
` mMapView.onPause()`. Therefore I think if this NullPointerException happened it should happened inside `onPause()`. Do you know why this happened and how to prevent it.
I can never reproduce it on my device.
Any help or suggestion would be great appreciated. Thank you

**Platform: Android**
**Mapbox SDK version: 5.0.2

**Comment by tobrun** [comment]
This is fairly strange as the View object has already been destroyed by the time it hits onSaveInstanceState.

> onSaveInstanceState always call after onPause

This is true, but this can also happen before/after onStop. There is no strict time in the lifecycle of a fragment that the onSaveInstaceState is invoked. 

This seems like a Android platform bug and not an Mapbox SDK issue. Only thing I could advice is null checking the MapView in your OnSaveInstanceState.
