### ISSUE TITLE
Points are drawn from wrong GeoJsonSource

### ISSUE THREAD

**Issue by teresaholfeld** [mapbox/mapbox-gl-native#9505]
In our [example Android project](https://github.com/moovel/android-example-mapbox/tree/quad-tree), I have 3 SymbolLayers with different icons: a "NEW" marker, a red marker, and a blue marker. Each layer has a separate GeoJsonSource with 5 Points each, and we can toggle the visibility of each layer.

After I added all the points (5 for each layer, in the sequence NEW, red, blue), I'm toggling the visibility of new and red markers, only to discover that:
- under each "NEW" marker, there is a red marker, and
- under each red marker, there is a blue marker.
This means I have a total of 5 NEW markers, 10 red markers, and 15 blue markers.

<img src="https://user-images.githubusercontent.com/11841927/28173515-eef42fa8-67ee-11e7-911a-1c8341f1794c.png" width="200">&nbsp;<img src="https://user-images.githubusercontent.com/11841927/28173531-fc9e63e4-67ee-11e7-9fa2-a0f907887982.png" width="200">&nbsp;<img src="https://user-images.githubusercontent.com/11841927/28173543-078d75a6-67ef-11e7-8dbb-04847cc4dbcb.png" width="200">

I expected to see only 5 red markers and 5 blue markers. This is probably a bug in how it is handled in MapBox.
To see how we initialize our layers and put data on them, have a look at:
* [MainActivity](https://github.com/moovel/android-example-mapbox/blob/quad-tree/app/src/main/java/com/moovel/example/mapbox/MainActivity.java)
* [MainPresenter](https://github.com/moovel/android-example-mapbox/blob/quad-tree/app/src/main/java/com/moovel/example/mapbox/MainPresenter.java)

**Platform:** Android 7.1.1, OnePlus 3T
**Mapbox SDK version:** 5.1.0

### Steps to trigger behavior

 1. Add 5 points each to 3 different layers.
 2. Toggle the visibility of these layers.

### Expected behavior
I have 5 markers on each layer.

### Actual behavior
I have 5 markers on the first layer, 10 markers on the second layer (5 of which are exactly at the position of the points of the first layer), and 15 markers on the third layer (10 of which are exactly at the positions of the previous layer).

**Comment by klblk** [comment]
You addMarker() code uncorrected:
```
private void addMarker(Feature feature, String prefix) {
   featureMap.put(feature.getId(), feature);
   GeoJsonSource source = (GeoJsonSource) mapboxMap.getSource(prefix + "-marker-source");
   if (source != null) {
      List<Feature> features = new ArrayList<>(featureMap.size());
      features.addAll(featureMap.values());
      source.setGeoJson(FeatureCollection.fromFeatures(features));
   }
}
```
All features write in one featureMap for any sources. Next source contains all data of previous.

**Comment by teresaholfeld** [comment]
Yes that seems to be the issue. Thank you!
