### ISSUE TITLE
[iOS] Show multiple callouts at the same time

### ISSUE THREAD

**Issue by hfehrmann** [mapbox/mapbox-gl-native#9508]
It should be possible to show at the same time the callouts for a set of annotations (similar to #3115 I think). 
I see that is possible to have an array of selected annotations. Maybe show the callouts for every annotation in array?

As a proposal, have to kinds of callout: the first is like the current one and is showed when the annotation is first in the array, and the *small callout* is shown when is in any other position of the selectedAnnotations array.

**Comment by filletofish** [comment]
+1 for feature! 👍

**Comment by emtjoshhart** [comment]
Is this still not possible?
