### ISSUE TITLE
Create new GeoJsonSource takes long time (6-11 seconds) from FeatureCollection of 20000 items.

### ISSUE THREAD

**Issue by mypoiworld** [mapbox/mapbox-gl-native#9513]
**Platform: Android**
**Mapbox SDK version: 5.1.0**

### Steps to trigger behavior

I have a problem that blocks my project at the moment; creating a GeoJsonSource with 20000 features takes a lot of time. If anyone knows how to solve my problem or an alternative way to show clustered data on the map I would be very happy.

My code:
 1. Create a featurecollection of around 20000 items:

```
List<Feature> featureList = new ArrayList<>();
for (Poi poi : currentMapPoiList) {
	JsonObject properties = new JsonObject();
						
 	featureList.add(Feature.fromGeometry(
		Point.fromCoordinates(
			Position.fromCoordinates(poi.lon, poi.lat)), properties, Integer.toString(poi.id)
		)
	);
}

featureCollection = FeatureCollection.fromFeatures(featureList);

```

 2. Create a new GeoJsonSource object from the featureCollection. Just this line takes about 6 to 11 seconds to finish on a Nexus 6P:
```
GeoJsonSource newGeoJsonSource = new GeoJsonSource(
	"mapPois",
	featureCollection,
	new GeoJsonOptions()
		.withCluster(true)
		.withClusterMaxZoom(8)
		.withClusterRadius(50)
	);
```

### Expected behavior
I would expect the GeoJsonSource to be created within 0-1 seconds like iOS.

### Actual behavior
1. new GeoJsonSource takes between 6 and 11 seconds on a relative fast device like the Nexus 6P to be created witch is very long if you have to rebuild the data a lot. 
2. Also because new GeoJsonSource has to be run in de UI thread, it blocks the UI thread for 7-11 seconds. User thinks the device is frozen and has a bad experience.
3. GeoJsonSource can't be cached and has to be recreated every time the map style changes, this makes the problem a lot worse.

It would be great if a mapbox coder could look at it and maybe point to an alternative to show clusters. Thank you for any pointers.

**Comment by tobrun** [comment]
@mypoiworld Thank you for the report, we will be taking this benchmark in account when implementing performance improvements. That said, have you considered uploading your data as a dataset to Mapbox Studio and exposing it in a custom style? More information about this [here](https://www.mapbox.com/help/studio-manual-datasets/).

**Comment by mypoiworld** [comment]
@tobrun Thank you.
But the data to be displayed on the map is a result of a filter or a search so it changes with every new filter/search action, assuming that a dataset in mapbox studio is a static dataset.
Also for me the preferred method to display the map pois would be to use `addMarker` but I need clustering because of the high number of items.

**Comment by tobrun** [comment]
@mypoiworld if you would prefer the annotation api, you could look into using https://github.com/mapbox/mapbox-plugins-android/pull/49, we haven't released it on maven yet but it could unblock you for the time being.

**Comment by mypoiworld** [comment]
@tobrun Thank you 👍 . I will try the plugin.

**Comment by tobrun** [comment]
I'm going ahead and close this as non actionable. We are aware of the performance limitations and working on asynchronous rendering to meet the criteria set out in OP.
