### ISSUE TITLE
Not centered numbers in road signs

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9517]
Capturing from a user that road signs are not centered correctly,
Reproducible with latest master using a Samsung Galaxy S6 Edge, Android 7.0.
Other devices don't seem to be affected atm.

![image](https://user-images.githubusercontent.com/2151639/28221722-af2c7dd6-68c4-11e7-9f3b-b6d49e051ca9.png)

**Comment by zugaldia** [comment]
Adding that the issue doesn't seem to be showing on a Samsung Galaxy S6 (not Edge) with Android 7.0:

![screenshot_20170830-170352](https://user-images.githubusercontent.com/6964/29895201-3374a982-8da6-11e7-97a4-9a5633a7f3c9.png)

**Comment by tobrun** [comment]
Capturing from the user reporting this, that this isn't an issue anymore with 5.3.2
