### ISSUE TITLE
Icons don't work on Android

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#952]

**Comment by ljbade** [comment]
I assume you mean they show up as black boxes like https://github.com/mapbox/mapbox-gl-native/issues/843?

**Comment by ljbade** [comment]
Hmm is this the same as https://github.com/mapbox/mapbox-gl-native/issues/1649

**Comment by kkaefer** [comment]
Not sure, but this ticket is way too generic anyway.
