### ISSUE TITLE
[andorid] Why MAXIMUM_ZOOM is 20.0f?

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-native#9527]
In https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java#L58

`public static final float MAXIMUM_ZOOM = 20.0f;`

I would like to know why constrain to 20?

**Comment by tobrun** [comment]
More information in https://github.com/mapbox/mapbox-gl-native/issues/7155, closing as duplicate.
