### ISSUE TITLE
Second instance of mapbox shows only the current location indicator

### ISSUE THREAD

**Issue by johanneslaubermoovel** [mapbox/mapbox-gl-native#9528]
**Platform:** Android
**Mapbox SDK version:** 5.1.0

### Steps to trigger behavior

 1. Create an activity which shows a map
 2. Create an overlay as fragment, which also shows a map

### Expected behavior
Two instances of the map would be visible

### Actual behavior
The map in the fragment is transparent only the current location indicator is visble

**Comment by tobrun** [comment]
This is because of 2 SurfaceView fighting over the z positioning. 
More information in this issue https://github.com/mapbox/mapbox-gl-native/issues/6101.
