### ISSUE TITLE
Marker/MarkerView sync issue

### ISSUE THREAD

**Issue by mdakram** [mapbox/mapbox-gl-native#9531]
There is a big lag when we add marker view and pan the map. I was checking snapchat other day they are using mapbox sdk and they are also using marker view to display markers and their markers are perfectly synced with map pan.

![](http://i.imgur.com/qpwMXGT.jpg)

Any idea how they are doing it?

**Comment by tobrun** [comment]
afaik they aren't using MarkerView but a SymbolLayer with runtime styling. We are aware of the issue of degrated synchronisation and aiming at deprecating MarkerView in #9365.

**Comment by mdakram** [comment]
@tobrun but they are showing some animations as well. are animations supported with symbol layer?

**Comment by tobrun** [comment]
You can use the Android Animation framework for that. Eg. ObjectAnimators, ValueAnimators etc. 
An example, though this is with using a source, can be found [here](https://github.com/mapbox/mapbox-plugins-android/blob/master/plugins/locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin.java#L519). You are able to do the same with properties of a symbol layer.

**Comment by mdakram** [comment]
Thank you will give it a try.
