### ISSUE TITLE
Android onDestroy null object reference

### ISSUE THREAD

**Issue by jpshelley** [mapbox/mapbox-gl-native#9542]
When using Kotlin's android extensions I'm receiving the following stacktrace after leaving my maps fragments:
```
07-18 21:39:11.255 2779-2779/com.drivespotter.app E/InputEventSender: Exception dispatching finished signal.
07-18 21:39:11.255 2779-2779/com.drivespotter.app E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
07-18 21:39:11.256 2779-2779/com.drivespotter.app E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.MapView.onDestroy()' on a null object reference
```

As a work around I put the onDestroy call in my fragment's onStop method. I don't feel like this is preferred and is thus a code smell. Is this an actual bug or intended? I noticed chatter about onStart/onStop for Nougat's multi-window features so I wasn't sure if the Android demo's need updated, but I have put `mapBox.on{lifecycle}` for start,stop,pause,resume,destroy,create in my fragment the same way the bundled [SupportMapFragment](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/SupportMapFragment.java) works.

**Platform:**
Android (any OS)
Kotlin
Kotlin-Android-Extensions

**Mapbox SDK version:**
5.1.0

### Steps to trigger behavior

 1. put `map_box.onDestroy` in a fragment's `onDestroy` method
 2. start the app and access the fragments screen
 3. attempt to navigate away from the screen causing the onDestroy method to be called on a null object.

### Expected behavior
No null ptr crashing for placing onDestroy in the onDestroy method

### Actual behavior
Null ptr crash caused by stacktrace above.

**Comment by tobrun** [comment]
Thank you for the report @jpshelley, I will look into reproducing this.

**Comment by tobrun** [comment]
Can't reproduce, my hunch is that you hooking into the wrong lifecycle method:

`put map_box.onDestroy in a fragment's onDestroy method`

needs to be replaced with `onDestroyView`.

**Comment by jpshelley** [comment]
@tobrun 🤦‍♂️ thanks! Can't believe I missed that.
