### ISSUE TITLE
Android: setDrawAccuracyEnabled

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#9548]
In earlier versions you could set 'setDrawAccuracyEnabled' to true if jou want a accuracy circle around your location. Now I can't find how to configure this. Even when I configure this:

`map.getMyLocationViewSettings().setForegroundTintColor(Color.parseColor("#56B881"));
                map.getMyLocationViewSettings().setAccuracyTintColor(Color.parseColor("#FBB03B"));
                map.getMyLocationViewSettings().setAccuracyAlpha(100);`

I only see a small corle on my position, but accuracy circle is never drawed. Isn't it possible anymore to enable this?

**Comment by tobrun** [comment]
Your location updates are probably accurate enough so the radius is too small for the zoom level you are looking at. Note that there used to be a bug that made the accuracy value larger than it should be.

![ezgif com-video-to-gif 70](https://user-images.githubusercontent.com/2151639/28368932-55398988-6c96-11e7-8b24-992f6787f93a.gif)


Fwiw, we are working on a seperate location layer plugin in https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/locationlayer. Closing as non reproducible.
