### ISSUE TITLE
Persist location more frequently

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#955]
The Android test app doesn't persist the location across runs. When anything kills the app, the next launch will be back on the world view. Instead, we should persist the location after every change so that we can restore it even when the user killed the app, or the app crashed.

**Comment by ljbade** [comment]
The Android docs on [persistent state](http://developer.android.com/reference/android/app/Activity.html#SavingPersistentState) point to using  `getPreferences` but this is only available to `Activity` not `View` so we would have to add it to the demo app and not the Android library.

Should the `MapView` handle this or should developers be required to handle this them selves in their own Activities?

Should we also persist other state like the currently selected style?

@bleege What are your thoughts? How does the raster SDK handle crashes?

@incanus What does the iOS app do?

**Comment by kkaefer** [comment]
Yeah, I see this as a demo app feature, not a library feature.

**Comment by bleege** [comment]
> Yeah, I see this as a demo app feature, not a library feature.

Agreed.  Mapbox is just supplying Geo Legos here.... how individual developers / apps integrate them within their specific apps is their call.

GLTestApp is a great example of this and will be useful for customers when building their apps.

**Comment by zugaldia** [comment]
FWIW, GLTestApp already shows how to save the state of the GPS toggle in `onSaveInstanceState()`. That's a good example of how to save an Activity state.

Related, there was an small issue with that code: https://github.com/mapbox/mapbox-gl-native/pull/1807

**Comment by ljbade** [comment]
This is up to apps to implement.
