### ISSUE TITLE
Disappearing MarkerViews on phones with unusual aspect ratio

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native#9550]
![marker](https://user-images.githubusercontent.com/16925074/28368685-8a035f00-6c95-11e7-98cd-29bc27041260.gif)
![marker2](https://user-images.githubusercontent.com/16925074/28369830-004e6ea4-6c99-11e7-953a-8c4aa5038c19.gif)

Reproducible on Samsung Galaxy S8+. I wasn't able to reproduce it on any phone with 16:9.
- To make a marker disappear you have to tilt camera more than 55 degrees and find specific zoom level.
- It unfortunately isn't consistent. When there are many different markers visible at the same time some might disappear and others won't.
- Markers seem to start disappearing below center of the screen.

Problem originates in native code because markers are not made invisible, they are actually not returned at all in `NativeMapView#queryPointAnnotations()` (invoked in `AnnotationManager#getMarkersInRect()`).

Marker:
```
mapboxMap.addMarker(new MarkerViewOptions().position(new LatLng(51.015,16)));
```

Camera position:
```
//marker visible
D/onCameraIdle: Target: LatLng [latitude=51.01496666711435, longitude=16.000138947282153, altitude=0.0], Zoom:18.214754127766252, Bearing:107.13901185546955, Tilt:59.99999999999999

//marker invisible
D/onCameraIdle: Target: LatLng [latitude=51.014883108383664, longitude=16.000531546911475, altitude=0.0], Zoom:18.214754127766252, Bearing:107.13901185546955, Tilt:59.99999999999999
```

**Comment by tobrun** [comment]
> Problem originates in native code because markers are not made invisible, they are actually not returned at all in NativeMapView#queryPointAnnotations() (invoked in AnnotationManager#getMarkersInRect()).

This is the same issue as with MarkerView animations (noticed this myself in #8799 ). I would advice you to look into migrating to SymbolLayer instead of MarkerViews. Going to close this as a duplicate, thank you @LukasPaczos for testing!

**Comment by LukasPaczos** [comment]
Alright, thanks a lot for looking into this @tobrun! I'm looking forward to full rollout of location layer as well as #9365 to depracate all those Android views.
