### ISSUE TITLE
Optimise horizontal swipe in a ViewPager

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9561]
It's currently hard to pan the map horizontally because the wrapping ViewPager always consumes this touch event. Ideally we limit switching pages only to the edge of the ViewPager. We should look into using something as onTouchIntercept or at least provide an workaround for in our examples. 

![ezgif com-video-to-gif 71](https://user-images.githubusercontent.com/2151639/28409437-f8565df4-6d3a-11e7-9d36-f8cd24100f40.gif)

**Comment by tobrun** [comment]
we could try using `android.support.v4.widget.NestedScrollView`

**Comment by tobrun** [comment]
A workaround for end users is using a custom ViewPager and providing the following implementation:

```java
package com.mapbox.mapboxsdk.testapp.view;

import android.content.Context;
import android.support.v4.view.PagerTabStrip;
import android.support.v4.view.ViewPager;
import android.util.AttributeSet;
import android.view.SurfaceView;
import android.view.View;

public class MapViewPager extends ViewPager {

  public MapViewPager(Context context, AttributeSet attrs) {
    super(context, attrs);
  }

  @Override
  protected boolean canScroll(View v, boolean checkV, int dx, int x, int y) {
    return v instanceof SurfaceView || v instanceof PagerTabStrip || (super.canScroll(v, checkV, dx, x, y));
  }
}
```

![ezgif com-video-to-gif 75](https://user-images.githubusercontent.com/2151639/28560559-797a97ae-711b-11e7-8df3-8076c79bb762.gif)

**Comment by tobrun** [comment]
Valid workaround provided, don't feel this is a requirement to fix from SDK side. Closing.

**Comment by ArnyminerZ** [comment]
Is there any workaround using ViewPager2? Thank you
