### ISSUE TITLE
Allow compass visibility customization

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-native#9562]
Our users love the compass and want to have it visible all the time. I have added an parameter, `compassAlwaysVisible` to MGLMapView in our branch that fixes this. 

```
mapView.compassAlwaysVisible = YES;
```

Would it make sense to have this as an standard option i Mapbox GL Native? Do you want this minor thing as a pull-request?

**Comment by fabian-guerra** [comment]
Hi @halset. Thank you for asking. Even if this is a small change most of our users don't expect the compass to be displayed unless required. If we make this change it will require them to adjust their code.

**Comment by halset** [comment]
I have `compassAlwaysVisible` set to `NO` by default, so users would not need to change anything.

**Comment by friedbunny** [comment]
MapKit is adding this feature in iOS 11 via a separate [`MKCompassButton`](https://developer.apple.com/documentation/mapkit/mkcompassbutton), which includes a `compassVisibility` enum with adaptive, hidden, and visible options. That’s a nice approach.

In terms of our existing compass setup, I think it’d be better to add a `visibility` property on [`-[MGLMapView.compassView]`](https://www.mapbox.com/ios-sdk/api/3.6.0/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)compassView) with similar options.

**Comment by artemKatlenok** [comment]
I'd really like to have option to disable compass at all, totally. 
There is no way to do this in iOS SDK, so I have to cover compass with buttons %(

**Comment by halset** [comment]
@friedbunny 
* Should there be a new `MGLCompassView` class instead of the existing `UIImageView` for `MGLMapView.compassView`? Or should we just add a `MGLMapView.compassVisibility`
* What is a good name for the visibility enum? VisibilityType is already present, but should probably not be expanded with an `adaptive`-variant. Translating [`MKFeatureVisibility`](https://developer.apple.com/documentation/mapkit/mkfeaturevisibility?language=objc) to `MGLFeatureVisibility` is probably not the best as feature is something else? Perhaps `MGLVisibility` or would that be mixed up with `VisibilityType`?

**Comment by friedbunny** [comment]
@chloekraw I changed the title again, as my current intention is to implement `adaptive`, `hidden`, and `visible` options, which is more flexible than a single option to show the compass, even if it’s facing north.

**Comment by chloekraw** [comment]
Oh, @friedbunny, I think I had the tab open and changed the title without refreshing the page, so I didn't know that you had already changed it. I meant to override the original title, not yours!
