### ISSUE TITLE
Callback in FileCache?

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#958]
In [`FileSource`](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/storage/file_source.hpp#L27-37) we're doing this:
```
using Callback = std::function<void(const Response &)>;

virtual void request(const Resource &resource, const Environment &env, Callback callback) = 0;
```
While in [`FileCache`](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/storage/file_cache.hpp#L20-L21) the virtual `get` uses `std::unique_ptr` for callbacks:
```
virtual void get(const Resource &resource, std::function<void(std::unique_ptr<Response>)> callback) = 0;
```

- Should we align these to both use `std::unique_ptr`?
- Should we move this definition outside of `FileSource`?
- Why is it that `Callback` seems to escape the `mbgl` namespace [when used in Node.js bindings](https://github.com/mapbox/node-mapbox-gl-native/blob/master/src/node_file_source.hpp#L29-L30)?

/cc @kkaefer

**Comment by jfirebaugh** [comment]
We're probably making both of these `shared_ptr`s per #1180.

I'm guessing the namespacing issue was resolved, re-ticket if not.
