### ISSUE TITLE
Update to LOST 3.x

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#9581]
Once https://github.com/mapbox/mapbox-gl-native/pull/9488 lands we can return to use LOST 3.x again, and revert the changes from https://github.com/mapbox/mapbox-gl-native/issues/9404 where we needed to downgrade LOST to 1.1.1.

cc: @Guardiola31337 @tobrun

**Comment by tobrun** [comment]
I'm adding this to 5.2.0 milestone and going to bump LOST to the newest version on master. 
This buys us sometime to test it out before doing beta releases.

**Comment by paulVulog** [comment]
Does this issue will be fix in 5.2.0 ? It seems not to be part of 5.2.0 milestone as expected regarding the comments.

**Comment by tobrun** [comment]
#9844 landed including this in https://github.com/mapbox/mapbox-gl-native/pull/10354 but got reverted with https://github.com/mapbox/mapbox-gl-native/pull/10380. We are working on including it in the next beta release. Adding milestone 5.2.0.

**Comment by Guardiola31337** [comment]
Fixed via https://github.com/mapbox/mapbox-gl-native/pull/10355

It'll be available in the next beta release.

cc/ @paulVulog @grote
