### ISSUE TITLE
normalizeTileURL fails if access_token contains a period

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#959]
If passed a URL with an access_token parameter containing a period, the result looks like:

```
http://a.tiles.mapbox.com/v4/mapbox.satellite/2/0/0.png?access_token=pk.blah@2x.blah
```

**Comment by 1ec5** [comment]
Whoops, last-minute regression in 8804c47d2736e284bb3d6272a38ecc90797d01f0.
