### ISSUE TITLE
IOS: App Crashes while removing the extra MGLMapView's

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [mapbox/mapbox-gl-native#9600]
**Platform:** IOS
**Mapbox SDK version:** ios-v3.6.0

### Steps to trigger behavior

 1. Start app with a `MGLMapView`
 2. Open a `UIViewController` some more MGLMapView's
 3. Now, remove the extra `UIView` with those extra MGLMapView's.

### Expected behavior

Should work without crashing.

### Actual behavior

The app crashes with the below crash report,

`*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <MGLMapView 0x11d0b3e00> for the key path "bounds" from <_UILayoutGuide 0x11bd17280> because it is not registered as an observer.`

After this line,

`self.extraMapView.removeFromSuperview()`

I had this working in earlier version of SDK , but it is crashing after updating the SDK to **ios-v3.6.0** .

**Comment by frederoni** [comment]
Thank you for your report.
This is probably another case that is not covered by #9109 

Can you provide some more context? Do you pop the second view controller simultaneously as you remove the `UIView` that contains the additional `MGLMapView`’s? Do you keep a strong reference to the map view so that it's not released when you remove it from the super view?

**Comment by ThiyagarajanShivSankaran** [comment]
Hi @frederoni, I am using three `UIViewController`'s  with `MGLMapView`. If I try to close the last `UIViewController` which contains `MGLMapView` then it is crashing. 
It's seems to be a weird issue

Any way's, I found a solution, if I remove the existing `UIView` that contains the additional `MGLMapView`, before open a new `UIViewController`, then it is working fine.

**Comment by felixLam** [comment]
I had a similar issue where I returned a custom LayoutGuide object in my UIViewController's top and bottom layout guide without holding on to the returned instance. Returning a lazy loaded strong property fixed the issue.

**Comment by jojonarte** [comment]
I had this similar issue which occurs when I try to remove the MGLMapView's annotations while the UIView that contains the MGLAnnotation is not in the foreground.
