### ISSUE TITLE
E/UncaughtException: java.lang.NoSuchMethodError: No interface method requestLocationUpdates(Lcom/mapzen/android/lost/api/LocationRequest;Lcom/mapzen/android/lost/api/LocationListener;)

### ISSUE THREAD

**Issue by samvgorode** [mapbox/mapbox-gl-native#9604]
**Platform:**
**Mapbox SDK version:** `compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.2@aar') {
        transitive = true
    }`

### Steps to trigger behavior

 1. Create `private LocationEngine locationEngine`
 2. Initialize it as `locationEngine = LostLocationEngine.getLocationEngine(NavigationActivity.this);`
 3. 

### Expected behavior
No crash.

### Actual behavior
Crash. 
E/UncaughtException: java.lang.NoSuchMethodError: No interface method requestLocationUpdates(Lcom/mapzen/android/lost/api/LocationRequest;Lcom/mapzen/android/lost/api/LocationListener;)V in class Lcom/mapzen/android/lost/api/FusedLocationProviderApi; or its super classes (declaration of 'com.mapzen.android.lost.api.FusedLocationProviderApi' appears in /data/app/no.sammevei.app-2/base.apk:classes6.dex) at com.mapbox.services.android.location.LostLocationEngine.requestLocationUpdates(LostLocationEngine.java:123)  exactly this code "locationEngine.requestLocationUpdates();" please check it.

**Comment by samvgorode** [comment]
I didn't use any mapzen imports, problem is in your LostLocationEngine (from com.mapbox.services.android.location) which implements LocationListener (from com.mapzen.android.lost.api). I implemented just compile 'com.mapbox.mapboxsdk:mapbox-android-services:2.1.3' for your LostLocationEngine.

**Comment by tobrun** [comment]
@samvgorode could you update to the latest 5.1.1/5.1.0 release?

We have had some issues with lost in recent releases, with 5.1.0 we downgraded back to an older stable version. More information on how to trouble shoot issues with dependencies in https://github.com/mapbox/mapbox-gl-native/issues/9408. Closing this issue as answered.
