### ISSUE TITLE
SpriteAtlas.width is less than Sprite.Width (Feature or Bug)

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-native#961]
Can someone please comment on whether the following is correct?

1.) SpriteAtlas width is hardcoded to 512
2.) Sprite width for @2x is 752.

I am wondering why this works correctly. Whenever an icon sprite is needed during Symbol Bucket creation, raw pixels are copied from sprite.raster to spriteatlas.data, a dirty flag is set that triggers copy to GPU in map thread.  This works correctly even though SpriteAtlas and Sprite.raster have different widths.

**Comment by kkaefer** [comment]
We are not using the sprite image as in and upload it to the texture. Instead, we use a sprite atlas that only contains the sprite images that are used in the current map view. The coordinates we are using in the GPU buffer are the coordinates in the sprite atlas image, not those from the source image.

**Comment by mb12** [comment]
Thank you very much for the explanation.
