### ISSUE TITLE
Is there a way to setStrokWidth in annotations/Polygon?

### ISSUE THREAD

**Issue by tsenggordon** [mapbox/mapbox-gl-native#9622]
**Platform:** Android
**Mapbox SDK version:** 5.1.0

In Google Map, the stroke width can be set, I wonder how it can be done in Mapbox.
https://developers.google.com/android/reference/com/google/android/gms/maps/model/Polygon

Thanks.
Kuo-Wei

**Comment by jfirebaugh** [comment]
Hi @tsenggordon, thanks for using Mapbox. To control the stroke width, you'll need to create and add line layer to the map. [Here's an example.](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/styles/LineLayerActivity.java)

For other "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
