### ISSUE TITLE
Missing attribute: Visible and ZIndex in annotations/Polyline

### ISSUE THREAD

**Issue by tsenggordon** [mapbox/mapbox-gl-native#9623]
**Platform:** Android
**Mapbox SDK version:** 5.1.0

In Google Map, visible and ZIndex are included in polyline, I wonder if mapbox has the parity of those or how can achieve the same behavior. 
https://developers.google.com/android/reference/com/google/android/gms/maps/model/Polyline

**Comment by jfirebaugh** [comment]
Duplicate of #1728.
