### ISSUE TITLE
raster tiles blurry

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#963]
Possibly related to #924, but raster tiles are blurry on device. 

![img_3099](https://cloud.githubusercontent.com/assets/17722/6540671/0170664a-c460-11e4-87eb-889c49ca80cf.PNG)

The tile borders are 2x larger than they should be in debug mode. 

![img_3100](https://cloud.githubusercontent.com/assets/17722/6540672/0d930c52-c460-11e4-8a42-75a012a53ce6.PNG)

In addition, sometimes it looks like maybe two different zoom levels are being drawn together? 

![img_3101](https://cloud.githubusercontent.com/assets/17722/6540673/1a1c56e0-c460-11e4-8504-6d79973d0f42.PNG)

/cc @1ec5 @jfirebaugh

**Comment by 1ec5** [comment]
Interesting. Things look pretty sharp at z13+. Need to see which tiles are actually being fetched.

**Comment by 1ec5** [comment]
@yhahn points out that 2× satellite tiles are currently upsampled at low zoom levels. @incanus, please compare with [this online preview](https://www.mapbox.com/mapbox-gl-styles/) and close if you’re satisifed that it isn’t a software issue.

**Comment by incanus** [comment]
Weird. We didn't used to have this problem.

**Comment by incanus** [comment]
> The tile borders are 2x larger than they should be in debug mode.

Here's specifically what I'm seeing: 

https://dl.dropboxusercontent.com/u/575564/rasterblur.mov

You can see things looking ok at 15, 16, back out to 15, 14, 13, and then 12 looks like crap, as does anything lower-numbered out to 8, when I stop. 

This is a retina iPad, so the screen is 768x1024 virtual (1536x2048 actual). However, based on the tile borders, these are 512 raster tiles being shown in 512 of virtual space. In reality, we should be seeing 4x as many tiles on screen as we are. In the old, 256 raster days, we would see 16x as many tiles.

**Comment by jfirebaugh** [comment]
The current behavior is expected: for z in the interval [2, 3) we load z2 vector tiles and z3 raster tiles. At z2.0000 you see 512px @2x raster tiles in 256px of virtual space. At z2.9999, you see 512px raster tiles in ~512px of virtual space. Whether we want to change that is being discussed in https://github.com/mapbox/mapbox-gl-js/issues/1030.

**Comment by incanus** [comment]
Confirmed by: 

1. Setting starting zoom to an integer. 
1. Only using double-tap or two-finger single-tap to zoom, keeping integer zoom. 

That things are not blurry when at integer zooms. 

I put in my vote over in https://github.com/mapbox/mapbox-gl-js/issues/1030.

**Comment by jfirebaugh** [comment]
Per scrum discussion, we'll address this in a followup to the initial iOS Beta release.

**Comment by peterqliu** [comment]
Main discussion is still over at https://github.com/mapbox/mapbox-gl-js/issues/1030, but something more relevant for mobile: since this issue is really a tradeoff between image sharpness and lag in tile loading, can we detect the device's current connection quality/network speed and make the appropriate call? When slow, opt for blurry and stretched (Math.floor); when fast, try to get more sharpness.

**Comment by incanus** [comment]
A good way to evaluate how things are looking here as well is to use older, raster styles (not satellite) and evaluate the text legibility. We should be striving for this for backwards compatibility / use with other stacks and it can be easier to see blurriness / sharpness in these instances rather than straight-up satellite rasters.

**Comment by 1ec5** [comment]
The approach taken in mapbox/mapbox-gl-js#1221 doesn’t seem to have any effect in mapbox-gl-native.

**Comment by incanus** [comment]
Raster tiles aren't a focus of b2; pushing.
