### ISSUE TITLE
NavigationMapRoute LocationLayerPlugin from example. mapbox-android-navigation:0.4.0-SNAPSHOT Issue.

### ISSUE THREAD

**Issue by samvgorode** [mapbox/mapbox-gl-native#9631]
**Platform:**
**Mapbox SDK version:**
com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.0@aar

### Steps to trigger behavior

 1. Try to add local variables `NavigationMapRoute navigationMapRoute` and `LocationLayerPlugin locationLayerPlugin` with `compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.3.1'` ,
they are unavailable to import.

 2. Change gradle dependency to `compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.4.0-SNAPSHOT'` to resolve this problem.

 3. `NavigationMapRoute`  and `LocationLayerPlugin` are now available to import.

### Expected behavior
Everything in old imports without changes.

### Actual behavior
`ProgressChangeListener` and `OffRouteListener`, successfully implemented before, become not available to import and implement.

**Comment by cammace** [comment]
Hey @samvgorode, it's great to hear you switched over to 0.4.0 of the Navigation SDK. We moved some classes around into different packages which sounds like the issue you are running into. Removing the import and using <kbd>alt</kbd><kbd>enter</kbd> (on Mac) to re-import them. You can also use the[ project file structure](https://github.com/mapbox/mapbox-navigation-android/tree/master/navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5) to adjust the import path.

**Comment by samvgorode** [comment]
Today `NavigationMapRoute` and `LocationLayerPlugin` are now NOT available to import again. `compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.4.0-SNAPSHOT'`. Please, advice me, how can I make smooth moving of my marker while navigation without `NavigationMapRoute` and `LocationLayerPlugin` .

**Comment by samvgorode** [comment]
My customers are asking me to do a good navigation, but your classes in android navigation are not stable and they are experimental, as I've understood.
