### ISSUE TITLE
Can't restore map on Android, if it initialized without internet.

### ISSUE THREAD

**Issue by zfort-vitalii** [mapbox/mapbox-gl-native#9634]
I have pretty same issue like https://github.com/mapbox/mapbox-gl-native/issues/4500
Steps to reproduce (best way to check is clean app data and cache): 
1. Start MapboxAccountManager on the app context.
2. Before map loaded, turn on "Plane mode''

So i got the black screen which i can't fixed.

What i tried is to handle internet connection and on state "Connected" do this : 
1. mapView.setStyleUrl
2. mapView.invalidate
3. mapView.onResume
4. re sync map

Result the same, map still black.

**Platform:** Android emulator, Moto with Android 6, Samsung galaxy S7
**Mapbox SDK version:** i use AirMap sdk airmapsdk:1.0.9' and it use com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.0

### Expected behavior
Some how refresh map state to see the map.
### Actual behavior
Black screen in any case.

**Comment by tobrun** [comment]
Thank you for reaching out, it is normal you don't receive a callback for onMapReady as the style hasn't been loaded. First of all, you don't need to do anything when the device is reconnected:

![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/2151639/28708252-d7c7b9e2-737b-11e7-951d-4f1e2dace233.gif)

In above gif, I have clean install with airplane mode enabled. When enabling the network, the map will be loaded. I'm seeing that you are referring to `4.2.0`, if possible please upgrade to a more recent version.

Another advice is that you can listen to map not being loaded events through `MapView.setOnMapChangeListener` and listen for the event: `DID_FAIL_LOADING_MAP`. This allows your app to change behavior when there isn't a connection available. 

As shown in the gif, this is working as designed. Feel free to reach out if you have any follow up issues.

Closing as answered.

**Comment by zfort-vitalii** [comment]
@tobrun thanks for response!

**Comment by whyzjl** [comment]
why I cannot find the function MapView.setOnMapChangeListener ？？？

**Comment by tobrun** [comment]
@whyzjl sorry for the confusion, that needs to be `addOnMapChangeListener` instead

**Comment by whyzjl** [comment]
Hi，I use addOnMapChangeListener to  listen for the event: DID_FAIL_LOADING_MAP without Internet，however，I can not get the event: DID_FAIL_LOADING_MAP。my mapbox version is V5.5.1.
