### ISSUE TITLE
Revisit log level for HTTP permanent errors

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-native#9638]
The Mapbox Android SDK currently includes verbose logs for all canceled HTTP requests. While this makes sense for unknown errors, it can cause an unexpectedly large amount of logging for apps that are designed to work in a mostly offline environment and should be revisited to determine if the amount of logs should be reduced.

cc @zugaldia

**Comment by tobrun** [comment]
I'm proposing to add a debug flag indicating we want to see all the logs vs errors only.

**Comment by tobrun** [comment]
Additionally we could also allow setting a log level so only logs of that level and higher are printed.

**Comment by zugaldia** [comment]
> I'm proposing to add a debug flag indicating we want to see all the logs vs errors only.

I like the idea. In order to expedite a quick change though that could make it to the next patch released, how about we ticket that separately?

> Alternatively we could also allow setting a log level so only logs of that level and higher are printed.

Considering we're using Timber under the hood, isn't this already available to developers by changing the default `DebugTree` to a custom less verbose one?

**Comment by Guardiola31337** [comment]
> I like the idea. In order to expedite a quick change though that could make it to the next patch released, how about we ticket that separately?

Ticket 👉 https://github.com/mapbox/mapbox-gl-native/issues/9681

> Considering we're using Timber under the hood, isn't this already available to developers by changing the default DebugTree to a custom less verbose one?

Yeah, we could do that extending `Timber.Tree` 👀 https://github.com/JakeWharton/timber/blob/master/timber-sample/src/main/java/com/example/timber/ExampleApp.java
