### ISSUE TITLE
SSL handshake aborted: Failure in SSL library

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9640]
A user reported seeing:

> 07-18 13:54:54.006 3071-3071/com.mapbox.mapboxsdk.testapp E/mbgl: {pboxsdk.testapp}[Style]: Failed to load tile 0/0/0=>0 for source tileset-id: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7aecb620: Failure in SSL library, usually a protocol error
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:741 0x731e7d5c:0x00000000)

When connecting to an external vector source as shown in our examples [here](https://www.mapbox.com/mapbox-gl-js/example/third-party/). This issue only seems pre nougat devices. Been researching this a bit, and I think the [following](https://stackoverflow.com/questions/29916962/javax-net-ssl-sslhandshakeexception-javax-net-ssl-sslprotocolexception-ssl-han) could resole it:

> I found the solution for it by analyzing the data packets using wireshark. What I found is that while making a secure connection, android was falling back to SSLv3 from TLSv1 . It is a bug in android versions <= 4.4 , and it can be solved by removing the SSLv3 protocol from Enabled Protocols list.

I'm going to take proposed workaround in link above for a spin and see if it resolves the error in first section.

**Comment by tobrun** [comment]
Looked into the proposed workaround from OP, doesn't seem to fix the issue. Since we only have heard about one occurrence specific to these vector tiles. Don't think this actionable for us right now.

**Comment by davidpronk** [comment]
For reasons beyond my influence we use our own tile server which only supports TLS 1.2
Therefore Android clients running api 19 and below are unable to load vector tiles. Would it be possible for Mapbox to add the workaround as mentioned at https://blog.dev-area.net/2015/08/13/android-4-1-enable-tls-1-1-and-tls-1-2/

**Comment by tobrun** [comment]
@davidpronk thank you for the ping on this. Have you tried out the linked code and does it resolve your issue?

**Comment by davidpronk** [comment]
@tobrun I ran in to this while working on a NativeScript app using the nativescript-mapbox plugin. So I am unable to apply the workaround in our setup.
The reason we use the plugin is to avoid implementing Mapbox ourselves.

**Comment by tobrun** [comment]
I'm going to reopen this issue so we can look into the differences between the setup linked in https://github.com/mapbox/mapbox-gl-native/issues/9640#issue-246277543 versus https://github.com/mapbox/mapbox-gl-native/issues/9640#issuecomment-335469655.

**Comment by tobrun** [comment]
With https://github.com/mapbox/mapbox-gl-native/pull/10948 we are allowing to change OkHttpClient used, this allows to implement workarounds as mentioned above.
