### ISSUE TITLE
Error on add layers - Android SDK

### ISSUE THREAD

**Issue by rodrigoyleila** [mapbox/mapbox-gl-native#9645]
**SOURCE** CODE BEGIN

                GeoJsonSource gsonvalues = new GeoJsonSource(GeoJsonSource,
                        string_gson,
                        new GeoJsonOptions()
                                .withCluster(true)
                                .withClusterMaxZoom(O_Constantes.setMaxClusteringZoomLevel)
                                .withClusterRadius(O_Constantes.radiusMarkerClusterer)
                );

                mapboxMap.addSource(gsonvalues);

                for(int indice_markers=0; indice_markers<=14;indice_markers++)
                {
                    //Creating a marker layer for single data points
                    if(string_gson.contains("\"c_img\":\""+indice_markers+"\""))
                    {
                        Log.i(TAG, "tengo " + String.valueOf(indice_markers));

                        unclustered_points = "unclustered-points_" + indice_markers;
                        name_img_marker = "marker_residentes_" + indice_markers;
                        //Log.i(TAG, "icon: " + icon);

                        mapboxMap.addImage(name_img_marker, BitmapFactory.decodeResource(funciones._actividad.getResources(), pins.getResourceId(indice_markers,0)));
                        SymbolLayer unclustered = new SymbolLayer(unclustered_points, GeoJsonSource);
                        unclustered.setProperties(
                                iconImage(name_img_marker)
                        );
                        unclustered.setFilter(
                                eq("c_img", ""+indice_markers)
                        );

                        mapboxMap.addLayer(unclustered);

                    }
                }
                int[][] layers = new int[][]{
                        new int[]{100, ContextCompat.getColor(funciones._actividad, R.color.deslizar_1)},
                        new int[]{50, ContextCompat.getColor(funciones._actividad, R.color.deslizar_2)},
                        new int[]{0, ContextCompat.getColor(funciones._actividad, R.color.deslizar_3)}
                };

                for (int i = 0; i < layers.length; i++)
                {
                    //Add clusters' circles
                    CircleLayer circles = new CircleLayer(clusters + "-" + i, GeoJsonSource);
                    circles.setProperties(
                            circleColor(layers[i][1]),
                            circleRadius(15f)
                    );

                    // Add a filter to the cluster layer that hides the circles based on "point_count"
                    circles.setFilter(
                            i == 0
                                    ? gte("point_count", layers[i][0]) :
                                    all(gte("point_count", layers[i][0]), lt("point_count", layers[i - 1][0]))
                    );
                    mapboxMap.addLayer(circles);
                }

                //Add the count labels
                SymbolLayer count = new SymbolLayer(contador, GeoJsonSource);
                count.setProperties(
                        textField("{point_count}"),
                        textSize(12f),
                        textColor(Color.WHITE)
                );
                mapboxMap.addLayer(count);

**SOUCE CODE END**

**ERRORS BEGIN**

07-28 16:02:36.571 3846-5555/com.mapsjw.territorio W/zygote64: Attempt to remove non-JNI local reference, dumping thread
07-28 16:02:36.572 3846-5555/com.mapsjw.territorio W/zygote64: Attempt to remove non-JNI local reference, dumping thread
07-28 16:02:36.572 3846-5555/com.mapsjw.territorio I/mbgl: {AsyncTask #6}[Android]: Not activating as we are not ready
07-28 16:02:37.059 3846-5555/com.mapsjw.territorio W/zygote64: Attempt to remove non-JNI local reference, dumping thread
07-28 16:02:37.070 779-816/? I/ActivityManager: Displayed com.mapsjw.territorio/.A_Mapa: +825ms
07-28 16:02:37.136 3846-5555/com.mapsjw.territorio W/zygote64: Attempt to remove non-JNI local reference, dumping thread
07-28 16:02:37.153 3846-5555/com.mapsjw.territorio I/oMapa: tengo 0
07-28 16:02:37.155 3846-5555/com.mapsjw.territorio W/zygote64: Attempt to remove non-JNI local reference, dumping thread
07-28 16:02:37.156 3846-5555/com.mapsjw.territorio W/zygote64: Attempt to remove non-JNI local reference, dumping thread
07-28 16:02:37.156 3846-5555/com.mapsjw.territorio E/libEGL: eglMakeCurrent:866 error 3002 (EGL_BAD_ACCESS)
07-28 16:02:37.156 3846-5555/com.mapsjw.territorio E/mbgl: {AsyncTask #6}[OpenGL]: eglMakeCurrent() returned error 12290
07-28 16:02:37.161 3846-5555/com.mapsjw.territorio W/System.err: com.mapbox.mapboxsdk.style.layers.CannotAddLayerException: eglMakeCurrent() failed
07-28 16:02:37.161 3846-5555/com.mapsjw.territorio W/System.err:     at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddLayer(Native Method)
07-28 16:02:37.162 3846-5555/com.mapsjw.territorio W/System.err:     at com.mapbox.mapboxsdk.maps.NativeMapView.addLayer(NativeMapView.java:731)
07-28 16:02:37.162 3846-5555/com.mapsjw.territorio W/System.err:     at com.mapbox.mapboxsdk.maps.MapboxMap.addLayer(MapboxMap.java:298)
07-28 16:02:37.162 3846-5555/com.mapsjw.territorio W/System.err:     at com.mapsjw.territorio.objetos.O_Mapa.add_puntos_sin_mover(O_Mapa.java:938)
07-28 16:02:37.162 3846-5555/com.mapsjw.territorio W/System.err:     at com.mapsjw.territorio.objetos.O_Mapa.access$1000(O_Mapa.java:85)
07-28 16:02:37.162 3846-5555/com.mapsjw.territorio W/System.err:     at com.mapsjw.territorio.objetos.O_Mapa$generar_puntos.doInBackground(O_Mapa.java:611)
07-28 16:02:37.162 3846-5555/com.mapsjw.territorio W/System.err:     at com.mapsjw.territorio.objetos.O_Mapa$generar_puntos.doInBackground(O_Mapa.java:574)
07-28 16:02:37.162 3846-5555/com.mapsjw.territorio W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
07-28 16:02:37.163 3846-5555/com.mapsjw.territorio W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-28 16:02:37.163 3846-5555/com.mapsjw.territorio W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
07-28 16:02:37.163 3846-5555/com.mapsjw.territorio W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-28 16:02:37.163 3846-5555/com.mapsjw.territorio W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-28 16:02:37.163 3846-5555/com.mapsjw.territorio W/System.err:     at java.lang.Thread.run(Thread.java:764)
07-28 16:03:48.451 3846-3851/com.mapsjw.territorio I/zygote64: Do full code cache collection, code=488KB, data=359KB
07-28 16:03:48.452 3846-3851/com.mapsjw.territorio I/zygote64: After code cache collection, code=483KB, data=296KB
07-28 16:05:48.214 3846-3851/com.mapsjw.territorio I/zygote64: Do partial code cache collection, code=503KB, data=304KB
07-28 16:05:48.215 3846-3851/com.mapsjw.territorio I/zygote64: After code cache collection, code=503KB, data=304KB
07-28 16:05:48.215 3846-3851/com.mapsjw.territorio I/zygote64: Increasing code cache capacity to 2MB

**ERRORS** **END**

**Platform:Android 8.0 Preview 4**
**Mapbox SDK version:5.1.1**

**Comment by rodrigoyleila** [comment]
Mapbox SDK version:5.1.0 works very well

**Comment by jfirebaugh** [comment]
It looks like your code is modifying the map on a background thread. That's not supported; you must execute  `mapboxMap.addLayer` and so on from the main thread.

**Comment by rodrigoyleila** [comment]
Thanks.
