### ISSUE TITLE
featuresInSourceLayersWithIdentifiers returning empty every time.

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [mapbox/mapbox-gl-native#9646]
**Platform:** IOS
**Mapbox SDK version:** ios-v3.6.0

### Steps to trigger behavior

 1. Fetch the array of features from `MGLVectorSource` by using `sourceLayerIdentifiers` 
 2. It's returning empty array every time.

### Expected behavior

It should return all the features from sourceLayers

### Actual behavior

But it's returning empty array.

Below is my code,

```
func featuresInSourceLayers(WithIdentifiers sourceLayerIdentifiers: [String], andPredicate predicate: NSPredicate?) -> [MGLFeature]{

        if let source = self.mapView.style?.source(withIdentifier: "my-composite") as? MGLVectorSource {
            let features =  source.features(sourceLayerIdentifiers: Set(sourceLayerIdentifiers), predicate: predicate)
            return features
        }
        return [MGLFeature]()
    }
```

I have checked the older SDK `ios-v3.5.4` , it's working there. Thanks.

**Comment by jmkiley** [comment]
I was able to repro this in `iosapp` by adding this code to to [- (IBAction)handleLongPress:(UILongPressGestureRecognizer *)longPress](https://github.com/mapbox/mapbox-gl-native/blob/a33cad98557f2d15bfb578e4795b130d25a2def2/platform/ios/app/MBXViewController.m#L1588) 
```
    MGLVectorSource *source = [_mapView.style sourceWithIdentifier:@"composite"];
    NSArray *f = [source featuresInSourceLayersWithIdentifiers:[NSSet setWithArray:@[@"poi_label"]] predicate:nil];
```

I see the issue in iosapp with https://github.com/mapbox/mapbox-gl-native/commit/c2b00378b78b55d50968a9b11ed75bb4edf62ec9#diff-3f30d11bf1ea37d78c1c04b6c00a605dL62 but not with a235032. 

cc @jfirebaugh

**Comment by jmkiley** [comment]
Noting that this issue seems to be both on `master` and `release-ios-v3.6.0-android-v5.1.0`. 

cc @boundsj

**Comment by AFcgi** [comment]
I have the same problem. I test it with ios-v3.5.4, it's working there.

**Comment by epau** [comment]
I have repro'd this as well. I had to revert back to 3.5 on iOS. Would love to see this fixed soon.

**Comment by fabian-guerra** [comment]
This was fixed in https://github.com/mapbox/mapbox-gl-native/pull/9784. Will be released as part of iOS SDK v3.6.2

**Comment by fabian-guerra** [comment]
iOS SDK v3.6.2 has been released.

**Comment by ThiyagarajanShivSankaran** [comment]
@fabian-guerra Thank you.

**Comment by ThiyagarajanShivSankaran** [comment]
@fabian-guerra it's fetching only the visible features from source. But, it should fetch all the features right. This is not working consistently.

**Comment by AFcgi** [comment]
I have the same issue. I have a cluster on map and zoom in until the cluster has dissolved. In this case the sdk crashes at the first zoom operation.

**Comment by fabian-guerra** [comment]
@ThiyagarajanShivSankaran sorry to hear you are still having issues. Could you please provide a test app?

**Comment by AFcgi** [comment]
@fabian-guerra I have a map with cluster and poi layers. Over a button you can select pois that are within a cluster. To show the poi layer on the map, I center the map first inn the poi coordinates. Then I increase the zoom level recursively until the cluster has resolved.
With the iOS SDK v3.5.4 wasn't a problem and works fine. With the v3.6.2 crash the SDK after the first zoom in.

```
let source = self.mapView.style?.source(withIdentifier: "identifier") as? MGLShapeSource
let predicate = NSPredicate(format: "%K == %i", "id", poiID)
guard let poi = source?.features(matching: predicate).first else { return }
```

**Comment by fabian-guerra** [comment]
@AFcgi could you please make a separate ticket and attach the crash log?

**Comment by ThiyagarajanShivSankaran** [comment]
Hi @fabian-guerra I need to fetch all the features from the vector source, despite of zoom level or in visible rect. Is there any way to do that. Thanks.

**Comment by AFcgi** [comment]
@ThiyagarajanShivSankaran I think it's the same issue like https://github.com/mapbox/mapbox-gl-native/issues/9888

**Comment by ThiyagarajanShivSankaran** [comment]
Hi @fabian-guerra I need to fetch non-rendered features as well. Is it possible in mapbox IOS SDK.

**Comment by fabian-guerra** [comment]
Hi @ThiyagarajanShivSankaran there is https://www.mapbox.com/ios-sdk/api/3.6.2/Classes/MGLVectorSource.html#/c:objc(cs)MGLVectorSource(im)featuresInSourceLayersWithIdentifiers:predicate with the following restriction: the source was associated with a layer that was recently used and the features were in the bounds of a recently scrolled to region.

**Comment by ThiyagarajanShivSankaran** [comment]
@fabian-guerra Okay.So there is no way to get non-rendered features.
Anyways thank you for your reply.

**Comment by Ibeihl** [comment]
any update on this? would love to get not rendered features from MGLShapeSource
