### ISSUE TITLE
Recommendation about polygon de-clipping

### ISSUE THREAD

**Issue by ambientlight** [mapbox/mapbox-gl-native#9647]
Hi guys,

My task is to extract full polygon geometries from tiles, and since objects derived from `MGLMapView.visibleFeatures(in:styleLayerIdentifiers)` come clipped I need to de-clip them.

I think know pretty much how this can be achieved on my side. 
I can derive the tile boundaries via my custom implementation of QuadTree with spherical mercator projection, and then follow the adjacent tiles to current tile edges which touch the polygon and then combine the polygons from these tiles.

My question is - does it really makes sense to do it on my side? Maybe you guys can advice me where should I look into in your codebase - so I would say either add APIs into iOS / Android wrappers and directly implement it in core if needed?

**Comment by jfirebaugh** [comment]
Hi @ambientlight -- we don't have plans to implement feature reconstitution on the SDK side. It's a hard problem because it typically requires source-specific logic about how to tell when features from two different tiles came from the same source feature. That logic is best implemented on the client side.

**Comment by ambientlight** [comment]
Hm, thanks, got it, makes sense.

What about exposing the quadTree and tile geometry for a client? So that we can convert from coordinate to z/x/y and get bounds for z/x/y. And something like a callback on each tile load so that say additional non-tile data can be post-loaded per tile?
