### ISSUE TITLE
Can not retrieve saved map

### ISSUE THREAD

**Issue by basmasrour** [mapbox/mapbox-gl-native#9648]
I know it's not an issue ....but I'm really lost the way
OnMapReady not called at all when device offline
Could any one provide me a full example explains how to retrieve the saved region
and how to be sure that the region downloaded?

I used the same example in the demo (offlinesimpleactivity)
even I'm offline the message of "region downloaded successfully appears "

Just one complete example please 
thanks alot

**Comment by Guardiola31337** [comment]
Hey @basmasrour 👋
Thank you for reaching out and reporting your question.

Could you add some more information on what you're trying to achieve? Are you able to provide a full use case example? If there is any sample or pseudo code you can provide, that would be really helpful.

**Comment by tobrun** [comment]
The best way to implement offline is through a Service, I'm working on a reference implementation and an easy to use plugin in https://github.com/mapbox/mapbox-plugins-android/pull/72.
