### ISSUE TITLE
Android 5.1.1 Telemetry Crash

### ISSUE THREAD

**Issue by DejanRistic** [mapbox/mapbox-gl-native#9649]
**Platform: Android**
**Mapbox SDK version: 5.1.1**

We recently released an update of our Android app with Mapbox SDK 5.1.1. We've noticed a lot of crashes through Fabric/Crashlytics from telemetry. Is there a way to disable telemetry? If not, ill link the crash log below. 

The crash seems to happen when Mapbox tries to enable telemetry. 

```
Fatal Exception: java.lang.RuntimeException
Unable to create application com.roadtrippers.RoadtrippersApplication: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.roadtrippers/com.mapbox.services.android.telemetry.service.TelemetryService }: app is in background uid UidRecord{143a0b4 u0a262 RCVR idle procs:1 seq(0,0,0)}
...
com.mapbox.services.android.telemetry.MapboxTelemetry.setTelemetryEnabled(MapboxTelemetry.java:308)
```

Full crash details: http://crashes.to/s/c42a8c0da9b

**Comment by tobrun** [comment]
@DejanRistic thank you for the report, looking at the crash logs I'm seeing that this issue only affects Android O (which isn't officially released). I'm going to move this issue to repository where the telemetry code is developed.
