### ISSUE TITLE
iOS: Undefined symbols _kUTTypePNG

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#965]
I have built the library and created a new project. I added the required libraries, but am getting a build error:

Undefined symbols for architecture x86_64:
  "_kUTTypePNG", referenced from:

I fixed this on the device by including the Imageio.framework, but the simulator build still reports the error.

Any thoughts?

![screen shot 2015-03-09 at 5 02 56 pm](https://cloud.githubusercontent.com/assets/417933/6566334/282c25d8-c67e-11e4-9564-5e008a98e5b3.png)

**Comment by friedbunny** [comment]
It looks like this might be because `MobileCoreServices.framework` isn't linked?

**Comment by friedbunny** [comment]
The demo app's Build Settings → Linking → Other Linker Flags includes it:

```-lpthread -ldl -framework CoreGraphics -framework CoreLocation -framework ImageIO -framework GLKit -framework MobileCoreServices -framework OpenGLES -framework SystemConfiguration -framework UIKit -framework Foundation -lpthread -ldl -lpthread -ldl -lpthread -ldl -lsqlite3 -lz```

**Comment by picciano** [comment]
Adding MobileCoreServices fixed it.
Resolved. Thanks.
