### ISSUE TITLE
 OnlineFileSource.ConnectionError failed

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9650]
Noticed a failed test on ci on master: `linux-gcc5-release-qt5` ([link to build](https://circleci.com/gh/mapbox/mapbox-gl-native/15079?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link))

```
[ RUN      ] OnlineFileSource.ConnectionError
../../../test/storage/online_file_source.test.cpp:97: Failure
Expected: (wait + 0.2) > (duration), actual: 0.2 vs 0.254068
Backoff timer fired too late
../../../test/storage/online_file_source.test.cpp:97: Failure
Expected: (wait + 0.2) > (duration), actual: 1.2 vs 1.27669
Backoff timer fired too late
../../../test/storage/online_file_source.test.cpp:97: Failure
Expected: (wait + 0.2) > (duration), actual: 3.2 vs 3.29783
Backoff timer fired too late
[  FAILED  ] OnlineFileSource.ConnectionError (3319 ms)
```

cc @tmpsantos @brunoabinader

**Comment by brunoabinader** [comment]
Time-based utests are flaky by design - this could mean there were many parallel tasks running at the same time. Should we raise +1s @tmpsantos ?

**Comment by tmpsantos** [comment]
@tobrun do you still see this?

**Comment by tobrun** [comment]
I haven't
