### ISSUE TITLE
It is possible to delete all cached tiles for needed source? Android SDK

### ISSUE THREAD

**Issue by AlexeyIke** [mapbox/mapbox-gl-native#9659]
Hello. We use Mapbox for Android in our app to displaying map and road traffic by using two source (map tiles, road traffic tiles with cache time 60sec), and have some inappropriate work for us - when users turn on 'road traffic' layers engine display cached 'road traffic' tiles, and when update that 'road traffic' tiles,  on cellular network it can make some time (1 - 5 seconds) and all that time user see old traffic data.

So, question is - it is possible to clear all cached tiled for needed source?  Perfect logic for us - clear all 'traffic' tiles on user Turing traffic off.
It is possible? 

Out style -    https://vt-map.vl.ru/styles/mapvlru/style.json
Road traffic source - 
"traffic": {
      "url": "https://vt-map.vl.ru/styles/traffic/source.json",
      "type": "vector"
    },
Turning road traffic on/off by making visible/invisible all source layers ("state_0", "state_1", "state_5", "state_7", "state_15")

**Platform:Android**
**Mapbox SDK version:5.1.1**

**Comment by tobrun** [comment]
Atm this is not possble, feature request for clearing cache (though not on source level) can be found https://github.com/mapbox/mapbox-gl-native/issues/4376. Feel free to add to context to that ticket. Closing as duplicate.
