### ISSUE TITLE
Remove implicit epoch == Jan 1, 1970 assumption

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#9660]
We're using various time types, including `std::chrono::system_clock`, and `std::time_t`. While most (all?) of our target platforms use Jan 1, 1970 GMT as the epoch, it's not guaranteed. Using this implicit assumption may render our cache databases not interchangeable.

**Comment by jfirebaugh** [comment]
C++20 specifies that `system_clock` measures Unix Time. The format of `std::time_t` is still not fully specified however, so if we want to be pedantically correct we should use [`std::chrono::time_point::time_since_epoch`](http://en.cppreference.com/w/cpp/chrono/time_point/time_since_epoch).
