### ISSUE TITLE
Marker is dragging, and map is not moving.

### ISSUE THREAD

**Issue by samvgorode** [mapbox/mapbox-gl-native#9661]
**Platform:** 
Android
**Mapbox SDK version:** 
com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.1@aar

### Steps to trigger behavior

 1. Run app for the first time
 2.
```
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle 
    savedInstanceState) {
        View view = super.onCreateView(inflater, container, savedInstanceState);
        if (savedInstanceState == null) {
            mapFragment = SupportMapFragment.newInstance(new MapboxMapOptions()
                    .styleUrl(Style.DARK)
                    .compassEnabled(false)
                    .locationEnabled(false));
            FragmentTransaction transaction = activity.getSupportFragmentManager().beginTransaction();
            transaction.add(getContainerId(), mapFragment, "com.mapbox.map");
            transaction.commit();
        } else {
            mapFragment = (SupportMapFragment) 
       activity.getSupportFragmentManager().findFragmentByTag("com.mapbox.map");
        }
        return view;
    }
```
 3. mapfragment is inside my fragment

### Expected behavior
map is moving, marker in the centre
### Actual behavior
map is not moving, marker is moving with finger

**Comment by samvgorode** [comment]
![screenshot_2017-08-01-14-41-56-363_com android settings 1](https://user-images.githubusercontent.com/18192354/28823744-c249e992-76c7-11e7-97d4-415d2bca9f08.png)
My device.

**Comment by tobrun** [comment]
Thank you for the report, this seems similar to #9459. a couple of follow up questions: since you are adding a fragment inside another fragment, why not use a ChildFragmentManager? Are you having this issue on other devices? Are you experiencing the same issue with https://play.google.com/store/apps/details?id=com.mapbox.mapboxandroiddemo?

**Comment by samvgorode** [comment]
- Ok, I'll try to use ChildFragmentManager.
- I have this issue also on nexus 5x, samsung s5
- there is no location marker in that app

**Comment by tobrun** [comment]
Would you be able to show the full code of that fragment?

**Comment by samvgorode** [comment]
Using
```getChildFragmentManager()
                    .beginTransaction()
                    .add(getContainerId(), mapFragment, "com.mapbox.map")
                    .commit();```
Instead of
```FragmentTransaction transaction = activity.getSupportFragmentManager().beginTransaction();
            transaction.add(getContainerId(), mapFragment, "com.mapbox.map");
            transaction.commit();```
Fixed my problem. Thank you very much for the advice.

**Comment by tobrun** [comment]
Thank you for reporting that back!
