### ISSUE TITLE
Android - Typo in setOnCameraMoveStartedListener in MapboxMap.java

### ISSUE THREAD

**Issue by jcloquell** [mapbox/mapbox-gl-native#9662]
Platform: Android
Mapbox SDK version: 5.1.1

In the MapboxMap.java class there is a typo in the ``setOnCameraMoveStartedistener`` method signature (the "L" of "Listener" is missing). It should be renamed to ``setOnCameraMoveStartedListener``

**Comment by tobrun** [comment]
Great catch @jcloquell, this will be included in next upcoming patch release, aimed for this week.
