### ISSUE TITLE
Thread startup shouldn't block on Actor<Object> construction

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#9666]
The `Thread` constructor blocks until the spawned thread has constructed the object. For `DefaultFileSource` this includes creating the offline database, which could be a lengthy operation.

We should modify `Thread` so that it doesn't block. This will be tricky, requiring the ability to construct an `ActorRef<Object>` for an `Object` that might not have itself been constructed yet.

**Comment by kkaefer** [comment]
Instead of changing our Actor system, we could make the `OfflineDatabase` construction faster by not opening the database in the constructor, and instead open it in a self-sent message as the first message processed for this object.
