### ISSUE TITLE
Update readme with iOS client library requirements

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#967]
[Old mapbox-gl-cocoa readme:](https://github.com/mapbox/mapbox-gl-cocoa/blob/f36ee137496c8cf11ab604cacbb63ca645e6741c/dist/README.md)

- `CoreGraphics.framework`
- `CoreLocation.framework`
- `GLKit.framework`
- `OpenGLES.framework`
- `SystemConfiguration.framework`
- `UIKit.framework`
- `libc++.dylib`
- `libsqlite3.dylib`
- `libz.dylib`

Also necessary:

- `MobileCoreServices.framework`
- `ImageIO.framework`

Library consumers have been popping by with issues (#947, #965). In the interim before the beta drops and proper docs are written, perhaps it would be friendly to throw this list in the repo's readme.

**Comment by incanus** [comment]
Yes! Thanks for this. Saw one of those comments. I'll get these updated.

**Comment by incanus** [comment]
Related to getting (at least static) version going over at https://github.com/mapbox/mapbox-gl-native/issues/829.
