### ISSUE TITLE
setPadding not working correctly on MapboxMap

### ISSUE THREAD

**Issue by haydenkaizeta** [mapbox/mapbox-gl-native#9672]
**Platform:**
AndroidSDK
**Mapbox SDK version:**
5.1.1
**Devices:**
Nexus5, Nexus7, S7
**AndroidSDK:**
20-24

### Steps to trigger behavior

 1. Use setPadding(0, 0, 0, 0) (and other pixel values)
 2. Set the value again, or use LatLngBounding box camera animations

### Expected behavior
setPadding() will override current padding and set to given values (set rather than add)

### Actual behavior
setPadding() does multiple weird things:
1. If you set the padding twice most of the time it will add to itself. This is not expected Android behavior
2. If you use different kinds of padding on animations and objects sometimes the padding adds onto itself.
These issues effect the placement of attribution and compass in addition to mapobjects

I can add examples of this, but it is easy to try setPadding(0, value, 0, 0) to reproduce the issue

**Comment by tobrun** [comment]
This is fixed with https://github.com/mapbox/mapbox-gl-native/issues/9391 and scheduled for the 5.2.0 release.

**Comment by tobrun** [comment]
fwiw, you can workaround this issue as shown in https://github.com/mapbox/mapbox-gl-native/issues/9379#issuecomment-311605634

**Comment by BoD** [comment]
If I'm not mistaken, the fix is available in v5.1.3.
I can confirm that we no longer see the weird "added" padding. 

However, it seems that the top padding is ignored when changing the camera bounds. 
The bottom padding is correctly used. 

Is this a new/different issue?

**Comment by tobrun** [comment]
@BoD thank you for testing and reporting. We are following up on this in #9751. I added a note with your findings [here](https://github.com/mapbox/mapbox-gl-native/issues/9751#issuecomment-325310472).
