### ISSUE TITLE
[android] Debug flag indicating we want to see all the logs vs errors only

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#9681]
Follow up ticket of https://github.com/mapbox/mapbox-gl-native/issues/9638#issuecomment-318586278

> add a debug flag indicating we want to see all the logs vs errors only

**Comment by Guardiola31337** [comment]
https://github.com/mapbox/mapbox-gl-native/issues/9829#issuecomment-324627100 and https://github.com/mapbox/mapbox-gl-native/pull/9851 mean that https://github.com/mapbox/mapbox-gl-native/pull/9764 is not closed.

@tobrun do you know what was the issue in https://github.com/mapbox/mapbox-gl-native/commit/a059c74a54302f9604f3e3b28143be7645e6204f which caused CI tests timeouts?

**Comment by tobrun** [comment]
Not applicable anymore with https://github.com/mapbox/mapbox-gl-native/pull/12468, with this in place users have full control of the logging mechanism used in this library.
