### ISSUE TITLE
Error setting property: line-join value must be a valid enumeration value

### ISSUE THREAD

**Issue by slm** [mapbox/mapbox-gl-native#9684]
**Platform: Android 7.0**
**Mapbox SDK version:5.1.0**

### Steps to trigger behavior

 1. Crashing directly JNI
 2. Used LostLocationEngine

### Expected behavior
Non crash from JNI
### Actual behavior
Crashed from JNI

`08-02 12:27:39.578 30020-30020/? E/mbgl: {APP_PACKAGE_NAME}[JNI]: Error setting property: line-join value must be a valid enumeration value`

**Comment by tobrun** [comment]
Could you show the code where you are setting line-join property?

**Comment by slm** [comment]
```  navigation.addMilestone(new RouteMilestone.Builder()
                .setIdentifier(BEGIN_ROUTE_MILESTONE)
                .setInstruction(new BeginRouteInstruction())
                .setTrigger(
                        Trigger.all(
                                Trigger.lt(TriggerProperty.STEP_INDEX, 3),
                                Trigger.gt(TriggerProperty.STEP_DISTANCE_TOTAL_METERS, 200),
                                Trigger.gte(TriggerProperty.STEP_DISTANCE_TRAVELED_METERS, 75)
                        )
                ).build());```

```
  locationLayerPlugin = new LocationLayerPlugin(mapView, mapboxMap, true);
        locationLayerPlugin.setLocationLayerEnabled(LocationLayerMode.NAVIGATION);
        locationLayerPlugin.setLocationEngine(location_engine);
```
```
    @Override
    public void onProgressChange(Location location, RouteProgress routeProgress) {
        Log.i("NAVIGATION",routeProgress.getCurrentLeg().getSummary());
        locationLayerPlugin.forceLocationUpdate(location);
}
```
I am not using line-join directly. Maybe LocationLayerPlugin use that. It's package name com.mapbox.mapboxsdk.plugins.locationlayer

**Comment by tobrun** [comment]
@cammace can you follow on this issue and create a ticket in the related repo? 
This issue is unrelated to mapbox-gl-native.

**Comment by tobrun** [comment]
capturing from @cammace that the locationLayer plugin doesn't use line-join that is triggering the crash. Are you using any other plugins? Are you seeing this issue with the most recent version 5.1.2?

**Comment by slm** [comment]
I'm using also navigation plugin. I will try with recent version and let you know.

**Comment by tobrun** [comment]
Capturing from @cammace that this comes from the navigation plugin. 
Will close this issue and create an issue downstream.

**Comment by tobrun** [comment]
created a ticket downstream in https://github.com/mapbox/mapbox-navigation-android/issues/156. Closing.
