### ISSUE TITLE
iOS visibleAnnotations not returning MGLPolygon.

### ISSUE THREAD

**Issue by randomiser** [mapbox/mapbox-gl-native#9691]
ios-v3.6.1

I'm not sure if this is a bug or is part of the design.

The documentation for the visibleAnnotations methods states that the method returns:

> An array of objects that adopt the `MGLAnnotation` protocol or `nil` if no annotations associated with the map view are currently visible in the rectangle.

I've added MGLPolygon instances to the MapView and have scrolled the screen so they are clearly visible and centred within the map bounds. 

When I invoke this method none of the MGLPolygons are returned. Is this correct?

**Comment by jmkiley** [comment]
Repro'ed this using the [drawing a polygon](https://www.mapbox.com/ios-sdk/examples/polygon/) example.

**Comment by randomiser** [comment]
Definitely a bug then. 

Would be great to get this fixed as it's an obvious disparity with the documentation.
