### ISSUE TITLE
Return an error object removeSource: is called on an in use MGLSource

### ISSUE THREAD

**Issue by jmkiley** [mapbox/mapbox-gl-native#9692]
Currently the SDK prints a console message when a MGLSource that is still being used by a MGLStyleLayer is removed. It may be more helpful to throw an error that can then be handled by developers.

**Comment by jfirebaugh** [comment]
Previously: #9129.

**Comment by julianrex** [comment]
Closed in https://github.com/mapbox/mapbox-gl-native/pull/13399 - by adding a new method. As such this was not a `SEMVER-MAJOR` change.
