### ISSUE TITLE
Add a way to quickly preview a style URL via environment variables

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#9697]
When debugging with the Demo app, you can set an access token via environment variables. It'd be cool to be able to set a style URL as well that overrides the default style URLs.

/cc @mapbox/ios

**Comment by 1ec5** [comment]
Relatedly, #5918 tracks a UI option to set an arbitrary style URL. It would also be straightforward to support opening iosapp via a URL handler or dragging a style JSON file into the simulator.
