### ISSUE TITLE
Markers sometimes render incorrectly after using the map for a while.

### ISSUE THREAD

**Issue by DejanRistic** [mapbox/mapbox-gl-native#9701]
**Platform: Android 7.1.2 (problem seen on other versions)**
**Mapbox SDK version: 5.1.2 (issue also seen down to 5.1.0)**

We render markers on the fly as the user pans/zooms the map, the majority of the time this works great and markers show up fine. Eventually when we clear and re-render a set of markers they seem to break and stay broken unless we kill the map. Its tough to nail an exact repro here, but it seems to happen after clearing and re-rendering markers, maybe a bunch of times in a row. 

Working Example:
![device-2017-08-03-110708](https://user-images.githubusercontent.com/1928768/28929385-ca7328fa-783d-11e7-988a-797128da8dd6.png)

Broken Examples:
![device-2017-08-03-110311](https://user-images.githubusercontent.com/1928768/28929401-d60b8ffe-783d-11e7-9fe5-febfb2eec168.png)

![28902263-d4c9d96a-77cb-11e7-9402-4609ef379e0a](https://user-images.githubusercontent.com/1928768/28929468-fb259cc6-783d-11e7-9b7b-620270240707.png)

We generate markers using marker options:
```
MarkerOptions markerOptions = new MarkerOptions().position(position).icon(IconFactory.getInstance(context).fromBitmap(bitmap));
```

Let us know if you have any insight or if you've seen this type of behavior before.

**Comment by jfirebaugh** [comment]
This has been fixed for 5.2.0 by #9213.
