### ISSUE TITLE
Location Always In Usage for Mapbox

### ISSUE THREAD

**Issue by kirandasika98** [mapbox/mapbox-gl-native#9702]
I was wondering if Mapbox will functional normally if the always in location permission is denied. I've read couple of threads and people have mentioned that it is for Mapbox telemetry.

iOS
Mapbox SDK version: 3.5

**Comment by friedbunny** [comment]
There is no required level of location permission — the map will function fine with when-in-use, always, or, indeed, no permission. The map only asks the user for location permission if the developer enables some feature that requires it, such as [`MGLMapView.showsUserlocation`](https://www.mapbox.com/ios-sdk/api/3.6.1/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)showsUserLocation).
