### ISSUE TITLE
Support fractional minzoom values

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#9704]
Related: https://github.com/mapbox/mapbox-gl-js/issues/2929

**Comment by brunoabinader** [comment]
Added as ignored render test after the mapbox-gl-js version bump in https://github.com/mapbox/mapbox-gl-native/pull/9689.

**Comment by kkaefer** [comment]
ignore was added as part of https://github.com/mapbox/mapbox-gl-native/pull/9699
