### ISSUE TITLE
tileset: only first url is used

### ISSUE THREAD

**Issue by moodstubos** [mapbox/mapbox-gl-native#9706]
**Platform: Android**
**Mapbox SDK version: latest git 2017-08-04**

### Steps to trigger behavior

style:
```
    "sources": {
        "composite": {
            "type": "...",
            "tiles": [
              "http://www.host-a.com/{z}/{x}/{y}.foobar",
              "http://www.host-b.com/{z}/{x}/{y}.foobar"
            ]
        }
    },

```

### Expected behavior

if host-a cannot serve the tile, use host-b

### Actual behavior

only host-a has been tryed to get tile. 
host-b is never used even if host-a sends 404 

same behavior with programmatically used tileset (android/java):

`new TileSet("2.1.0", "http://www.host-a.com/...", "http://www.host-b.com/...", ... )
`

**Comment by jfirebaugh** [comment]
This is behaving as designed. The `tiles` array isn't intended as a fallback mechanism in case of failures; rather it's for [domain sharding](https://www.keycdn.com/support/domain-sharding/). Domain sharding is only relevant in web browsers though, where there's a browser-enforced limit on the number of simultaneous connections to a given host. On Android there's no such limit, and therefore the Android SDK uses only the first entry in `tiles`.
