### ISSUE TITLE
Info window position not correctly working

### ISSUE THREAD

**Issue by abdullo211** [mapbox/mapbox-gl-native#9710]
**Platform:**
**Mapbox SDK version:**
Mapbox sdk version 5.0.2 

 1. Onclick map marker marker info window displayed with incorrect position
![image 2017-08-05 153 55 15](https://user-images.githubusercontent.com/12582070/28995271-6b947222-79fe-11e7-93ea-17580b6a554d.jpg)

**Comment by tobrun** [comment]
Are these Marker or MarkerView. How are you setting up your  Marker click listener?

**Comment by abdullo211** [comment]
for (Plan plan : plans) {
            markets.put(plan.getName(), plan.getId());
            MarkerViewOptions markerViewOptions = new MarkerViewOptions()
                    .title(plan.getName())
                    .snippet(plan.getAddress())
                    .icon(drawableToIcon(getContext(), R.drawable.ic_location_primary))
                    .position(new LatLng(plan.getLocation().getLatitude(), plan.getLocation().getLongitude()));

            map.addMarker(markerViewOptions);
        }

**Comment by tobrun** [comment]
Not reproducible with latest release (5.1.2) using following code:

```
        // add a OnMarkerView click listener
        MarkerViewActivity.this.mapboxMap.getMarkerViewManager().setOnMarkerViewClickListener(
          new MapboxMap.OnMarkerViewClickListener() {
            @Override
            public boolean onMarkerClick(@NonNull Marker marker, @NonNull View view,
                                         @NonNull MapboxMap.MarkerViewAdapter adapter) {
              Toast.makeText(MarkerViewActivity.this, "Hello " + marker.getId(), Toast.LENGTH_SHORT).show();
              return false;
            }
          });

```

Please update to latest release, closing.

**Comment by abdullo211** [comment]
Thank you
