### ISSUE TITLE
Markers added via map.newImage are clipped at some zoom levels

### ISSUE THREAD

**Issue by kohesion** [mapbox/mapbox-gl-native#9719]
I'm using GL 0.39.1 but this is a problem in other version also.

It seems like it happens on one line but nowhere else. Maybe this is a tile line? Not sure of how it works underneath.

![image](https://user-images.githubusercontent.com/1246027/29032166-769c3158-7b5e-11e7-8e8a-1930397cb8b9.png)

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained JSFiddle that demonstrates the issue?

**Comment by kohesion** [comment]
Sure, here you go.

Seems to be related to enabling clustering.

https://jsfiddle.net/matthewbaker77/g4k4rzyo/

**Comment by jfirebaugh** [comment]
Migrated to an issue in the correct repository: https://github.com/mapbox/mapbox-gl-js/issues/5447.
