### ISSUE TITLE
Issue MGLAnnotationView subclass and AutoLayout

### ISSUE THREAD

**Issue by aodhol** [mapbox/mapbox-gl-native#9722]
**Platform:** iOS 10.3.x
**Mapbox SDK version:** 3.6.1

### Steps to trigger behavior

 1. Subclass MGLAnnotationView adding an UIImageView.
 2. Constrain the image view to the edges.
 3. Use an image for the normal state and an image for the selected state.
 4. Set the selected state of the annotation view. 

### Expected behavior

 The selected view should grow in size and remain in position.

### Actual behavior

The annotation view moves to the top left corner.

Note, I tried this without AutoLayout and if you set the frame yourself the pin will also move to top left unless the frame origin is preserved. So it looks like the AutoLayout issue might stem from this?

I modified your sample code: https://gist.github.com/aodhol/c4490cf2063628bf8fb96c637caa43e9 (you will just need to images - a small pin image and a large pin image).

![simulator screen shot 7 aug 2017 20 04 14](https://user-images.githubusercontent.com/274682/29041658-9f903b16-7bab-11e7-9301-35c9347b1ed0.png)

![simulator screen shot 7 aug 2017 19 49 43](https://user-images.githubusercontent.com/274682/29041665-a5931e3e-7bab-11e7-8080-d3ea60a9a3ea.png)

**Comment by OlegGordiichuk** [comment]
I have some issue connected with AutoLayout. Do you know solution ?

**Comment by 1ec5** [comment]
Just a quick guess that this code might be responsible, since it modifies the view’s frame manually rather than using Auto Layout:

https://github.com/mapbox/mapbox-gl-native/blob/268a4d7404d30dc4f866711e3fd1e778892bbe35/platform/ios/src/MGLMapView.mm#L5702-L5722
