### ISSUE TITLE
[android] app freeze when drawing lots of markerviews

### ISSUE THREAD

**Issue by joaopedro1520** [mapbox/mapbox-gl-native#9726]
Hello, since version 5.1.0-5.12 when drawing ~100-300 markerviewoptions the app shows few icons with big icons and then freezes while trying to add all others for a good 5 seconds.
The code i use:

`MarkerViewOptions options = new MarkerViewOptions().position(new LatLng(mapObject.getLatitude
                    (), mapObject.getLongitude())).icon(UIUtils.getIcon(getAppCtx(), mapObject.getMarkerIcon(false, getAppCtx())));
            mMapboxMap.addMarker(options);`

**Platform:** Android 
**Mapbox SDK version:** 5.1.0-5.1.2

**Comment by Guardiola31337** [comment]
@joaopedro1520 thank you for reaching out and reporting your problem.
Similar issue was reported in https://github.com/mapbox/mapbox-gl-native/issues/9026 👀 

> BTW, if you move `Icon` creation out of the `for` loop it works fine.
Actually, if you don't need to create a different `Icon` each time, you should implement it like this:

> ```java
> public void addMarkers() {
>     // Create Icon once so memory isn't waste it
>     IconFactory iconFactory = IconFactory.getInstance(MainActivity.this);
>     Drawable drawable = ContextCompat.getDrawable(MainActivity.this, R.drawable.poi);
>     Bitmap bitmap = ((BitmapDrawable) drawable).getBitmap();
>     Icon icon = iconFactory.fromBitmap(bitmap);
>     //
>     for (int i=0; i<MARKERS_CNT; i++) {
>         Random r = new Random();
>         double lat = r.nextDouble() * 50;
>         double lon = r.nextDouble() * 50;
>           
>         Marker marker = mapBoxMap.addMarker(new MarkerOptions()
>                 .position(new LatLng(lat, lon))
>                 .icon(icon));
>     }
> }
> ```

☝️ is using `Marker`s but the same applies to `MarkerView`s.

How are you creating the `MarkerView`s? If there is any sample or pseudo code you can provide, that would also be really helpful.

**Comment by joaopedro1520** [comment]
The function i posted above is inside a for cycle for marker creation. I have different icons that i need to create depending on a mapObject

**Comment by Guardiola31337** [comment]
@joaopedro1520 👀 https://github.com/mapbox/mapbox-gl-native/issues/9026#issuecomment-305167876 that might help

> I create icon before loop and it works fine. But if you need use different icons for markers I recommended divide objects into several parts and call several loop.

BTW, did you try using `Marker`s and `MarkerOption` instead? It performs better.

Another option would be using _Symbols_. It’s even more optimal than Markers. Symbols are part of the [Mapbox style specification](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-symbol) and allow to [`SymbolLayer`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/SymbolLayer.java)s to show icons/text labels on the map. 👀 the [`SymbolLayerActivity`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolLayerActivity.java) example for further information.

**Comment by joaopedro1520** [comment]
Yeah I tried using them but they don't fit my needs. The thing is that on the previous versions it worked fine

**Comment by Guardiola31337** [comment]
Hey @joaopedro1520 

We're moving from an Android SDK View to a core implementation. Progress on the implementation in #9782 

As a workaround, you could implement that behavior from your side 👀 the implementation details in #9782 or wait until that PR lands.

Eventually, that will be implemented as a plugin 👉 https://github.com/mapbox/mapbox-plugins-android/issues/7

**Comment by tobrun** [comment]
MarkerView is going to be deprecated with https://github.com/mapbox/mapbox-gl-native/pull/9782. We are no longer maintaining this API and will remove it in future versions of the SDK. As noted in the deprecation message. We are advising users to leverage SymbolLayer instead (you can use the sample code in #9782 to convert Android SDK views to an Image to be used as a Symbol). While we no longer maintain the API we are happy to accept any PRs on it.

**Comment by joaopedro1520** [comment]
@tobrun I followed the symbol layer approach and its indeed faster drawing the markers on map. The problem is that after you add ~1000 the map becomes really slow when performing gestures. I ended up using MarkerOptions and needed to adapt few things so my app can support it. The symbol layer approach is good for some markers but for many it makes the map slow

**Comment by tobrun** [comment]
@joaopedro1520 that shouldn't happen, can you add some code on how you are creating/adding your layer? A good reference implementation for a symbollayer with different images can be found [here](https://github.com/mapbox/mapbox-gl-native/blob/2a9bae5ec53e9760d88ae8340cce63ae972dda17/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java). Since you are talking about 1000 markers, have you tried using clustering?

**Comment by joaopedro1520** [comment]
@tobrun this was my approach, I might be doing something wrong but i followed the implementation you posted.

I added 1000 markers for testing performance against markerview.

`


                    for (MapObject tmpObject : data) {

                        Random rand = new Random();

                        FeatureCollection markers = FeatureCollection.fromFeatures(new Feature[] {Feature.fromGeometry(Point.fromCoordinates(new double[]{tmpObject.getLongitude(), tmpObject.getLatitude()}))});
                        int n = rand.nextInt(5000000) + 1;

                        Source source = new GeoJsonSource(GENERATED_SYMBOL_SOURCE_ID + n, markers);
                        mMapboxMap.addSource(source);

                        ImageView imageView = new ImageView(getAppCtx());
                        imageView.setImageResource(R.drawable.mapbox_marker_icon_default);


                        // create bitmap from view
                        String iconId = GENERATED_SYMBOL_IMAGE_ID_BASE + tmpObject.getId();
                        mMapboxMap.addImage(iconId,SymbolGenerator.generate(imageView) );

                        // create layer for bitmap and filter source on name
                        String layerId = GENERATED_SYMBOL_LAYER_ID_BASE + tmpObject.getId();
                        layerIds.add(layerId);
                        mMapboxMap.addLayer(new SymbolLayer(layerId, GENERATED_SYMBOL_SOURCE_ID+n)
                                .withProperties(
                                        iconImage(iconId),
                                        iconAllowOverlap(false)
                                )
                        );


                    }

`

**Comment by tobrun** [comment]
in this case you have a layer for each marker, I could advice you to use a one layer approach instead. It's possible to have a symbolLayer with different images. The example [here](https://github.com/mapbox/mapbox-gl-native/blob/2a9bae5ec53e9760d88ae8340cce63ae972dda17/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/SymbolGeneratorActivity.java) does this. With that in place you should be able to hit 1000 symbols on a map.

**Comment by joaopedro1520** [comment]
@tobrun Hi again,
I tried the approach above and I have around a ~1000 icons, but they only start appearing gradually when zoom its applied to their position. When zooming out it only shows 4/5 markers from all the 1000 Is this a feature of symbol layer or there might be something wrong?
Thanks

**Comment by tobrun** [comment]
SymbolLayer exposes allowIconOverlap as a property, setting it to true will always show all symbols.

**Comment by joaopedro1520** [comment]
@tobrun  So i managed to add different markers onto the same layer but something really strange is happening. I even tried to add just a unique marker but still didnt solve the problem. 
Here is the behaviour after i add lots of markers to the map
![screenshot_2017-10-04-14-26-56](https://user-images.githubusercontent.com/20184389/31182978-359f75f6-a91d-11e7-898a-f7a414364234.png)

Here is the code

`

             List<Feature> markerCoordinates = new ArrayList<>();
                    for (MapObject tmpObject : data) {

                        Feature feature = Feature.fromGeometry(
                                Point.fromCoordinates(com.mapbox.services.commons.models.Position.fromCoordinates(tmpObject.getLongitude(),tmpObject.getLatitude())));
                        feature.addStringProperty("nameProperty",tmpObject.getId());

                        markerCoordinates.add(feature);

                        markers.put(tmpObject.getId(),new LatLng(tmpObject.getLatitude(),tmpObject.getLongitude()));

                        ImageView imageView = new ImageView(getContext());
                        imageView.setImageResource(tmpObject.getMarkerIcon(false, getContext()));

                        Bitmap icon = UIUtils.getMapMarker(getContext(), mapMarkers, tmpObject.getMarkerIcon(false, getContext()));


                        // Add the marker image to map
                        mMapboxMap.addImage(tmpObject.getId(),icon );

                    }

                    FeatureCollection featureCollection = FeatureCollection.fromFeatures(markerCoordinates);

                    Source geoJsonSource = new GeoJsonSource("marker-source1", featureCollection);

                    mMapboxMap.addSource(geoJsonSource);
                    sources.add(geoJsonSource);

                    SymbolLayer markers = new SymbolLayer("marker-layer1", "marker-source1")
                            .withProperties(iconImage("{nameProperty}"),iconAllowOverlap(false));


                    mMapboxMap.addLayer(markers);
                    layers.add(markers);

`
