### ISSUE TITLE
Render tests for text-pitch-{alignment,scaling} are false positives in GL native

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-native#9732]
Our current render tests are indicating false positives for the following render tests:

| Render test | Diff (Image) |
|--|--|
| text-pitch-alignment/auto-text-rotation-alignment-map | ![diff](https://user-images.githubusercontent.com/76133/29089788-2daf654a-7c86-11e7-911b-17bfc3484494.png) |
| text-pitch-alignment/auto-text-rotation-alignment-viewport | ![diff](https://user-images.githubusercontent.com/76133/29089804-4078f736-7c86-11e7-8a6d-f743852082f7.png) |
| text-pitch-alignment/map-text-rotation-alignment-map | ![diff](https://user-images.githubusercontent.com/76133/29089818-4bdb1596-7c86-11e7-9afd-9c87cc930048.png) |
| text-pitch-alignment/map-text-rotation-alignment-viewport | ![diff](https://user-images.githubusercontent.com/76133/29089830-5594242e-7c86-11e7-9a7d-14d918c1c9e8.png) |
| text-pitch-alignment/viewport-text-rotation-alignment-map | ![diff](https://user-images.githubusercontent.com/76133/29089847-6510da32-7c86-11e7-8eb2-4bb41b0d0604.png) |
| text-pitch-alignment/viewport-text-rotation-alignment-viewport | ![diff](https://user-images.githubusercontent.com/76133/29089861-6e86e7fa-7c86-11e7-97d4-3e650fbf7fa1.png) |
| text-pitch-scaling/line-half | ![diff](https://user-images.githubusercontent.com/76133/29089886-807e336e-7c86-11e7-9488-7c68f93b9f61.png) |

We're [manually handicapping the diff threshold](https://github.com/mapbox/mapbox-gl-js/blob/master/test/integration/render-tests/text-pitch-alignment/auto-text-rotation-alignment-map/style.json#L5) to allow these tests to pass. However, these failures indicates that symbol placement has not yet properly finished. In https://github.com/mapbox/mapbox-gl-native/pull/9689 we capture a different result for `text-pitch-scaling/line-half` that goes slightly under the diff allowance and thus fails - but it's just a different manifestation of the same issue.

This issue will be used as a guide in our test suite ignore list for GL native to pursue a proper fix.

**Comment by jfirebaugh** [comment]
Added ignores in bbbd03ad0a98f9bfe35edc7dbffd5b6a093f229a.

**Comment by ChrisLoer** [comment]
PR #10346 will bring native and js closer into sync, but the four tests that use `rotation-alignment: map` still give slightly different results:

| Render test | Diff (Image) |
|--|--|
| text-pitch-alignment/auto-text-rotation-alignment-map |![diff](https://user-images.githubusercontent.com/375121/32694700-8b84adbe-c6fb-11e7-86d9-c20771d8cdad.png) |
| text-pitch-alignment/map-text-rotation-alignment-map | ![diff](https://user-images.githubusercontent.com/375121/32694703-9a45dac6-c6fb-11e7-90ac-ae78900d9c3c.png) |
| text-pitch-alignment/viewport-text-rotation-alignment-map | ![diff](https://user-images.githubusercontent.com/375121/32694716-dab84a44-c6fb-11e7-9785-0c00f8cf0716.png) |
| text-pitch-scaling/line-half | ![diff](https://user-images.githubusercontent.com/375121/32694723-ee640a38-c6fb-11e7-863c-0af7363fefea.png) |
