### ISSUE TITLE
Expose setVisibleCoordinateBounds

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#9733]
Looks like we've exposed `setVisibleCoordinateBounds` on [`NativeMapView`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java#L510-L515) but it hasn't made it to the public API. This is an useful method which would be a good addition to the next release of the SDK.

cc: @Guardiola31337 @tobrun

**Comment by tobrun** [comment]
Adding here that we already expose this functionality through:

```
CameraUpdateFactory#newLatLngBounds(@NonNull LatLngBounds bounds, int paddingLeft, int paddingTop, int paddingRight, int paddingBottom)
```

This method returns a CameraUpdate that you can use with the following methods:

```
MapboxMap#animateCamera
MapboxMap#easeCamara
MapboxMap#moveCamera
```

The only benefit of proposal in OP is control of direction of the resulting bounds.

**Comment by zugaldia** [comment]
Let's keep this one open - though the functionality is almost there as @tobrun describes on https://github.com/mapbox/mapbox-gl-native/issues/9733#issuecomment-321070841 it's important that we keep a high level of consistency between core's public API and Android's one. This is something we might be able to simplify in the future once we set up automatic binding generation.

**Comment by tobrun** [comment]
This API is still missing, reopening, though need to note that we will probably postpone adding this until the time we fully/automatically align the binding with core.
