### ISSUE TITLE
[android] How to avoid marker or  marker view  collision 

### ISSUE THREAD

**Issue by Larnoo** [mapbox/mapbox-gl-native#9735]
How to avoid marker or  marker view  collision?

**Comment by tobrun** [comment]
These concepts are implemented on SymbolLayer, see the style specification [here](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-symbol). For Marker (which uses SymbolLayer, we do not expose this as a configuration (yet)). For MarkerView you can use MarkerView.getView().bringToFront(), atm we do not expose z-ordering.
