### ISSUE TITLE
package_ios.sh is requiring obsolete version of iOS SDK

### ISSUE THREAD

**Issue by picciano** [mapbox/mapbox-gl-native#974]
The script at scripts/package_ios.sh is set for iOS SDK version 8.1 which is not available in the current version of Xcode. This should probably be updated to 8.2, or better yet, set to use the latest installed version.

**Comment by 1ec5** [comment]
Travis [only supports](http://docs.travis-ci.com/user/languages/objective-c/#Supported-OS-X-iOS-SDK-versions) up to iOS 8.1 for now, and local builds should match Travis. As a workaround for now, you can locally apply the one-line change in #975.

cc @incanus

**Comment by 1ec5** [comment]
#975 once again tracks using the latest installed SDK.
