### ISSUE TITLE
[android] Support late token initialization

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#9740]
Right now, we're initializing telemetry as a consequence of setting the access token `Mapbox#getInstance` 👀 https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java#L58-L59 which needs to be set before [`MapView#onCreate`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java#L217-L218) or [`MapboxConfigurationException`](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/exceptions/MapboxConfigurationException.java#L8-L9) will be thrown which means that happens before getting the style. So in order to address it, I suggest moving the initialization to a later time.

@tobrun do you 👀 any problem setting the token when [finished loading the style and initial load](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java#L986)?

cc/ @zugaldia

**Comment by tobrun** [comment]
> So in order to address it, I suggest moving the initialization to a later time.

It's not clear to me what you are trying to achieve and why?

> @tobrun do you 👀 any problem setting the token when finished loading the style and initial load?

Yes, you need you token to load the style.. some additional background, we used to allow setting the token through MapView and MapboxMap.

**Comment by tobrun** [comment]
Linking https://github.com/mapbox/mapbox-gl-native/issues/7584 as related ticket

**Comment by Guardiola31337** [comment]
https://github.com/mapbox/mapbox-java/pull/537 will fix OP.

**Comment by tobrun** [comment]
Since this issue is handled upstream, going ahead and close this.
