### ISSUE TITLE
[Android] IllegalArgumentException: R array length must be 3 or 4 with Samsung Device

### ISSUE THREAD

**Issue by kfadli** [mapbox/mapbox-gl-native#9745]
Hello, i'm encountering an issue with Samsung Galaxy S4 (GT-I9505) and Android 4.3.

`Fatal Exception: java.lang.IllegalArgumentException: R array length must be 3 or 4
       at android.hardware.SensorManager.getRotationMatrixFromVector(SensorManager.java:1336)
       at com.mapbox.mapboxsdk.maps.widgets.MyLocationView$CompassListener.onSensorChanged(MyLocationView.java:821)
       at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:467)`

It seems a known issue on Samsung devices when they owns more 4 vector sensors.

**Platform:4.3
**Mapbox SDK version:5.1.0

### Steps to trigger behavior

 1. `map.getTrackingSettings().setMyBearingTrackingMode(MyBearingTracking.COMPASS)
 `

### Expected behavior
No crash :)
### Actual behavior
throw IllegalArgumentException on Samsung device

**Comment by tobrun** [comment]
Thank you for the report @kfadli, first occurence we heard of it. 
Will look into fixing this for next patch release.

cc @cammace, related to LocationLayerPlugin in 
https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/locationlayer

**Comment by tobrun** [comment]
This bug has been reported on Chromium, going to use the same solution:
https://src.chromium.org/viewvc/chrome/trunk/src/content/public/android/java/src/org/chromium/content/browser/DeviceMotionAndOrientation.java?pathrev=246398

**Comment by kfadli** [comment]
Great, thank you for your responsiveness @tobrun

**Comment by tobrun** [comment]
@kfadli do you have this device available for testing?

**Comment by kfadli** [comment]
Unfortunately not, i tried to reproduce with Android Emulator without success.
