### ISSUE TITLE
Identical Lat/Long Data points do not overlap in UI

### ISSUE THREAD

**Issue by bfuerst** [mapbox/mapbox-gl-native#9757]
Hi,

We have two datapoints with identical Lat/Longs and expect them to overlap but in our Mapbox GL (https://api.tiles.mapbox.com/mapbox-gl-js/v0.39.1/mapbox-gl.js) web UI the points are slightly separated. Attached is an example of what it looks like in the UI when it is zoomed in. 

Ex - https://image.ibb.co/fQdKuv/2017_08_11_13_33_14.jpg
![2017_08_11_13_33_14](https://user-images.githubusercontent.com/1198851/29225107-f5357e36-7e9a-11e7-8de6-faa42e359f40.jpg)

### Steps to trigger behavior

 1. Load two points with identical lat/longs from two different datasets
 2. Convert both datasets to tilesets
 3. Layer the two tilesets in a style
4. Apply style to web map
5. Zoom into Lat/Long and the identical points do not overlap

### Expected behavior
Points with identical lat/longs would overlap
### Actual behavior
Points with identical lat/longs do not overlap

**Comment by jfirebaugh** [comment]
This repository is for the Mapbox SDK implementations for iOS and Android. Looks like you meant to file an issue in https://github.com/mapbox/mapbox-gl-js. If you file a bug in that repository, please include a minimal, self-contained example that demonstrates the issue.
