### ISSUE TITLE
[MGLMapView selectedAnnotations] becomes prematurely empty on centring

### ISSUE THREAD

**Issue by aodhol** [mapbox/mapbox-gl-native#9758]
**Platform: iOS 10.3.x**
**Mapbox SDK version: 3.6.1**

### Steps to trigger behavior

 1. Create a map with two or more annotations.
 2. Select an annotation with:  mapView.selectAnnotation(annotation1, animated: false)
 3. Centre on that annotation: mapView.setCenter(annotation1.coordinate, zoomLevel: mapView.zoomLevel, animated: true) (this is crucial)
 3. Select and centre another annotation with the same methods.

### Expected  #behavior

The MapView should maintain a list of selected annotations which can then be used with deselectAnnotation or invoke _deselect_ on the other annotation views upon selecting a particular annotation view. It is not unreasonable to expect to be able to centre the map on the newly selected annotation and for the previously selected annotation to become deselected. This, as far as I am aware is the behaviour in MapKit. It seems the annotations to be deselected being off screen may have a bearing on this.

<img width="378" alt="screen shot 2017-08-11 at 20 18 58" src="https://user-images.githubusercontent.com/274682/29228610-58769e62-7ed2-11e7-921b-15976807bd3c.png">

### Actual behavior

mapView.selectedAnnotations occasionally becomes empty, the result of which is multiple annotations in the selected state because there's nothing to deselect according to the MapView. Note that centring the map on the annotation to be selected before invoking mapView.selectAnnotation(..) results in the same effect as though it is ignored.  

<img width="377" alt="screen shot 2017-08-11 at 20 15 22" src="https://user-images.githubusercontent.com/274682/29228500-d7f61312-7ed1-11e7-8a48-7fade31f68d1.png">

**Comment by fabian-guerra** [comment]
Hi, @aodhol. Thank you for using Mapbox.

I tried the following test scenario on our latest [version](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.7.4).

1. Created two annotations.
2. Used a toggle button to select/center each using the same methods you provided.
3. In the toggle button I printed the content of `selectedAnnotations`.

Works as expected. I am able to select each. In the process of selection automatically deselects the previous annotation so you don't need to do anything. And prints the content of `selectedAnnotations`.

I am going to close it. Please feel free to add more information or a code snippet in case you still have this issue.

**Comment by aodhol** [comment]
Great Fabian, will test when I can update to this version! Thank you :)
