### ISSUE TITLE
MGLMapView init stuck on iOS11 beta 5 

### ISSUE THREAD

**Issue by VojtaStavik** [mapbox/mapbox-gl-native#9761]
I noticed an issue with the latest iOS11 beta. I was OK on beta 4. The initializer gets stuck on [MGLOfflineStorage init].

![screen shot 2017-08-13 at 13 57 15](https://user-images.githubusercontent.com/6388510/29249508-fee9e6e6-8030-11e7-904a-3b4eb1027292.png)

**Platform:** iOS11b5
**Mapbox SDK version:** 3.6.1

### Steps to trigger behavior

 1. Create empty single view project
 2. Add MGLMapView to the view controller
 3. Run the project

**Comment by friedbunny** [comment]
Do you have an exception breakpoint enabled? The initial database creation catches an exception (`SQLITE_CANTOPEN`) and continues. You can confirm this by 1. checking the console for messages about database creation, and 2. continuing from the breakpoint.
