### ISSUE TITLE
unknown schema version

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9776]
When switching from master to the release branch, I'm hitting

>com.mapbox.mapboxsdk.testapp E/libc++abi: terminating with uncaught exception of type std::runtime_error: unknown schema version

This issue didn't show ~ 2 weeks ago, I can try git bisecting if that would help.  
Couldn't find a related issue, feel free to close if a duplicate.

**Comment by friedbunny** [comment]
Schema v6 was added in #9670 on master by @kkaefer. That hasn’t been backported to the release branch, which means master databases are incompatible.

As a change that kinda-sorta breaks compatibility, I’m not sure this database schema bump is something we’d want to cherry-pick into patch releases (feasibility and desirability aside).

**Comment by jfirebaugh** [comment]
For robustness, I think we should start writing reverse as well as forward migrations. That way if someone needs to roll back an SDK version update that triggered a migration, they're don't run into this issue.

**Comment by kkaefer** [comment]
Thinking more about this, I don't think this is something we can do. An older SDK doesn't have any way of knowing how to *roll back* a future update. The only place where we could roll back is in the current branch *before* switching to the old branch, but I'm unsure that would be of any value.

**Comment by jfirebaugh** [comment]
🤦‍♂️ You're right, of course.

We could require that migrations always be backward compatible, and allow older SDKs to use newer schemas... but that might significantly constrain what changes we can make. If we want to sometimes make compatible changes, and sometimes breaking changes, we need a semver-like convention for schema versions.

**Comment by friedbunny** [comment]
Addressed this on the release branch with #9837 — will be in iOS v3.6.3.
