### ISSUE TITLE
how to load GEOJSON tile?

### ISSUE THREAD

**Issue by asaeid** [mapbox/mapbox-gl-native#9778]
**Platform:* Android-SDK*
**Mapbox SDK version:* 5.1.2*

### Steps to trigger behavior

 1.
 2.
 3.

### Actual behavior
Thanks.

**Comment by tobrun** [comment]
We support adding GeoJSON as a Source on which you can define Layers to visualize the data. 
An example of this can be found [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/style/RealTimeGeoJsonActivity.java). Don't hesitate contacting us through [here](https://www.mapbox.com/contact/support/) for additional support or post a question on StackOverflow. The issue queue on this repo is for requesting features and reporting bugs. 

Thank you for using our product!
