### ISSUE TITLE
Speed Up make android

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-gl-native#978]
Currently `make android` builds both the C++ and Android artifacts.  The Android artifact takes quite a long time to build and it'd improve development if it could be sped up.

The Gradle command used for building the Android artifact is `gradle build` which builds both *debug* and *release* flavors of the Android artifact.  Let's change this to `gradle assembleRelease` so that it only builds the *release* flavor for now.

We should also consider a `make aproj` task that just compiles the C++ into the Android project shell in `android/java` as that'd be much quicker too.

/cc @kkaefer @ljbade

**Comment by kkaefer** [comment]
We can just invoke assembleDebug or assembleRelease based on the $(BUILDTYPE) SET inn the Makefile

**Comment by bleege** [comment]
Changing to `gradle assembleRelease` got the Android compilation down to 51 seconds.

**Comment by bleege** [comment]
Created `make android-project` to mirror the functionality of `make iproj`.  This should be much quicker to build (only compiles Core GL C++) and leaves the local filesystem with a working Android project that can be imported in an IDE.

**Comment by bleege** [comment]
Refactor completed by @kkaefer in #982.
