### ISSUE TITLE
Android screenshot / screen capture not showing the map

### ISSUE THREAD

**Issue by d3mac123** [mapbox/mapbox-gl-native#9783]
I am using Nativescript with Mapbox and I need to capture the map screen for social sharing. I can get the bitmap part (even the Mapbox logo) but not the map content:
![screen shot 2017-08-16 at 2 37 30 pm](https://user-images.githubusercontent.com/229148/29379426-75ff3f86-8290-11e7-894b-82c4efeffb03.png)

and the capture:
![screen shot 2017-08-16 at 2 38 25 pm](https://user-images.githubusercontent.com/229148/29379511-be6d20a8-8290-11e7-8e62-6fe5079eda55.png)

This case here https://github.com/mapbox/mapbox-gl-native/issues/3677 mentions a "ScreenShotUtil" which is not available anymore.

Any idea on how I can capture it? Below the code I am using to create the bitmap:
```
var v = view;
var bmp = android.graphics.Bitmap.createBitmap(v.getMeasuredWidth(), v.getMeasuredHeight()+50, android.graphics.Bitmap.Config.ARGB_8888);
v.android.draw(new android.graphics.Canvas(bmp));

var source = new imageSource.ImageSource();
source.setNativeSource(bmp);

var folder = fs.knownFolders.documents().path;
var fileName = "Test.png"
var path = fs.path.join(folder, fileName);
var saved = source.saveToFile(path, "png");

```

**Comment by tobrun** [comment]
You can use the `MapboxMap#snapshot(@NonNull SnapshotReadyCallback callback)`api for that.

**Comment by d3mac123** [comment]
@tobrun any examples? Can you please point to the documentation?

**Comment by tobrun** [comment]
example is here:
https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/imagegenerator/SnapshotActivity.java#L52
