### ISSUE TITLE
Mapbox addAllHoles for adding polygons is not working

### ISSUE THREAD

**Issue by JigneshTank** [mapbox/mapbox-gl-native#9791]
Hi there,

We are using Mabox in our Android platform. So far its all working for showing co-ordinates, showing navigation route etc but facing issue in showing the polygons on Mapbox.

**Platform: Android
**Mapbox SDK version:5.1.0

### Steps to trigger behavior
 1. I am trying to add polygons using addAllHoles methods but its not drawing anything on map.  
 2. If I try to add single polygon using addAll method, its showing single polygon.
 3. Code used to show multiple polygon is
 mapboxMap.addPolygon(new PolygonOptions()
                .addAllHoles(polygons)
                .fillColor(Color.parseColor("#000000"))
                .alpha(0.5f));

4. Sample for single Polygon is below:

[{"latitude":23.03886222383359,"longitude":72.53002925475414},{"latitude":23.03886222383359,"longitude":72.53535459506622},{"latitude":23.03730432475328,"longitude":72.53535459506622},{"latitude":23.03730432475328,"longitude":72.53002925475414},{"latitude":23.03886222383359,"longitude":72.53002925475414}]

### Actual behavior: Nothing is drawn on map. It shows blank map.

Your help will be appreciated as we are on point of launching our product.

Thanking you in advance,
Jignesh Tank

**Comment by tobrun** [comment]
@JigneshTank you need to use `PolygonOptions#add` / `PolygonOptions#addAll` instead.

**Comment by JigneshTank** [comment]
Hi there,

Thank you for answering.

I wanted to add multiple holes and I have List<List<LatLng>>. I am not able to add this holes using add or addAll as these methods accept only List<Latlng> and not List<List<LatLng>>
Please clarify more.

Thanking you,
Jignesh Tank

**Comment by tobrun** [comment]
an example can be found [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java#L204)

**Comment by JigneshTank** [comment]
Hi there,

Thank you for answering.

I have used addAll method and it started to display the 1 polygon but I wanted to show the multiple polygons and circular shape on map. For circular shape, I have radius and 1 lat long (centre). How  to show:

1. Multiple polygons
2. Multiple circular shape  on map.

Looking for help.

Thanking you,
Jignesh Tank
