### ISSUE TITLE
replace fragment with MapView

### ISSUE THREAD

**Issue by tomekancu** [mapbox/mapbox-gl-native#9793]
**Platform:** Android SDK 17
**Mapbox SDK version:** com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.2@aar

https://github.com/tomekancu/MapboxProblem

### Steps to trigger behavior
1. Create two fragment instances, each containing a MapView.
2. Replace one fragment with other
```
FragmentTransaction transaction = fragmentManager.beginTransaction();
transaction.replace(R.id.fragment_container, mapViewFragmentTwo);
transaction.commit();
```
Problem occurs  < Android API 18 

### Expected behavior
Replaced first fragment with second

### Actual behavior
App crash, logcat shows only 
08-17 17:38:02.992 15020-15020/? A//system/bin/app_process: stack corruption detected: aborted

**Comment by tobrun** [comment]
Would you be able to provide the code of the fragments? 

One typical cause of a fragment crash is calling `MapView.onDestroy` in `Fragment#onDestroy` (this should be executed as part of `Fragment#onDestroyView`. 

We have an [example](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/BottomSheetActivity.java#L91) is the repo with the same setup and I'm not seeing the crash there.

**Comment by tomekancu** [comment]
I did it ;) 
https://github.com/tomekancu/MapboxProblem

**Comment by tobrun** [comment]
@tomekancu sorry, I completely overlooked that, and my hunch was correct, you are calling MapView#onDestroy as part of Fragment#OnDestroy, moving this to Fragment#onDestroyView should fix the crash. Thank you for reaching out, feel free to follow up. Closing as issue was identified.

**Comment by tomekancu** [comment]
It change nothing. App still crashes.

**Comment by tomekancu** [comment]
I can even use SupportMapFragment
```
private void initBottomNavigation() {
        mapViewFragmentOne = SupportMapFragment.newInstance(new MapboxMapOptions()
                .styleUrl(Style.DARK));
        mapViewFragmentTwo = SupportMapFragment.newInstance(new MapboxMapOptions()
                .styleUrl(Style.LIGHT));
        bottomNavigationView.setOnNavigationItemSelectedListener(this);
        showMapTabOne();
    }
```
And happens the same thing.

**Comment by tobrun** [comment]
Thank you for testing, this shows that the issue will be found in your code. 
Haven't looked too much in it, but I'm seeing that you don't have calls to onStart/onStop and that you are incorrectly providing the layout resource to your fragment (this should be placed in a bundle not set as a field). Feel free to post this question on StackOverflow. This issue queue is used for bug reporting and feature reqeusts.

**Comment by tomekancu** [comment]
Let's look at these
https://github.com/tomekancu/MapboxProblem/blob/master/src/main/java/com/lastengineer/mapboxhidetest/MainActivity.java
It's even simpler activity. I'm using SupportMapFragment from library, and happens the same.
