### ISSUE TITLE
My App always crashed when I pop other ControllerView back to MapBoxView

### ISSUE THREAD

**Issue by skingz** [mapbox/mapbox-gl-native#9799]
**Platform: iOS** 
**Mapbox SDK version: 3.6.0** 
1.￼My App always crashed when I pop other ControllerView back to MapBoxView,
and the error report from :-MGLMapView updateFromDisplayLink
did I something wrong?
![f63dca4f-d315-49b4-99ad-724324bdf494](https://user-images.githubusercontent.com/1037833/29450964-6065c646-8433-11e7-8c6f-3e33674d12f4.png)

and the crash info is:

```
0 libGPUSupportMercury.dylib	_gpus_ReturnGuiltyForHardwareRestart + 12
1 AGXGLDriver	  gldUpdateDispatch + 7156
2 libGPUSupportMercury.dylib	gpusSubmitDataBuffers + 176
3 AGXGLDriver	gldUpdateDispatch + 12544
4 GLEngine	_gliPresentViewES_Exec + 188
5 GLEngine	gliPresentViewES + 112
6 OpenGLES	-[EAGLContext presentRenderbuffer:] + 80
7 GLKit	-[GLKView _display:] + 308
8 Mapbox	  MGLUnitBezierForMediaTimingFunction(CAMediaTimingFunction*) + 16428
9 QuartzCore	CA::Display::DisplayLinkItem::dispatch(unsigned long long) + 44
10 QuartzCore	CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 436
11 IOKit	IODispatchCalloutFromCFMessage + 372
12 CoreFoundation	___CFMachPortPerform + 180
13 CoreFoundation	___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
14 CoreFoundation	___CFRunLoopDoSource1 + 436
15 CoreFoundation	___CFRunLoopRun + 1752
16 CoreFoundation	CFRunLoopRunSpecific + 424
17 GraphicsServices	GSEventRunModal + 100
18 UIKit	UIApplicationMain + 208
19 MapPlay_PJ	main + 124
20 libdyld.dylib	_start + 4
```

2. the mapBox always have a abnormal view when I pop other ControllerView back to MapBoxView, the screen shot like this:

![screen shot 2017-08-18 at 4 26 15](https://user-images.githubusercontent.com/1037833/29451234-7c7292aa-8434-11e7-92ba-f396927224b5.png)

the map seems like on a loading status forever.

**Comment by skingz** [comment]
3. How to change the scaleBar's origin?

**Comment by fabian-guerra** [comment]
Hi @skingz. Thank you for using Mapbox and I am sorry to hear you are having some issues. Is it possible you can share a test app we could use to look into this crash?

**Comment by friedbunny** [comment]
@skingz also note that you must show attribution on the map — you can read more about the requirements [in this help doc](https://www.mapbox.com/help/how-attribution-works/).
