### ISSUE TITLE
create sprite sheet bundling tool

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#981]
For the time being, we will need an easy-to-use tool for devs to pre-bundle marker images into a style's sprite sheet, until we allow runtime imagery and even animations for markers (see #877). 

We have `./bin/build-sprite.js` from https://github.com/mapbox/mapbox-gl-js#sprite-generation but we should think about distributing a tool in this repo and/or making an easy download of this standalone.

**Comment by jfirebaugh** [comment]
We should move `build-sprite.js` to mapbox-gl-style-spec, our [soon-to-be-monolithic-again](https://github.com/mapbox/mapbox-gl-style-spec/pull/259) repo for style spec and associated utilities.

**Comment by incanus** [comment]
Yeah, was almost gonna suggest that. Makes sense to have it there.

**Comment by ljbade** [comment]
We will also want some documentation/simple tutorial on how to get started work custom markers
