### ISSUE TITLE
Getting error while using Mapbox SDK with Fuse tools

### ISSUE THREAD

**Issue by Dhvl-Golakiya** [mapbox/mapbox-gl-native#9811]
Hi,

I am using Mapbox SDK in Fusetools. It is working properly in iOS but in Android, I am getting this error:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/services/android/telemetry/location/LocationEngine;
```
How can I fix this error?

**Comment by tobrun** [comment]
I'm not familiar with Fusetools but it seems it isn't pulling in external dependencies? The missing class error is pointing to [Telemetry](https://github.com/mapbox/mapbox-java/tree/master/mapbox/libandroid-telemetry) which is pulled in as a transitive dependency when resolving dependencies.
