### ISSUE TITLE
Custom My Location Tracking Behavior

### ISSUE THREAD

**Issue by dgadelha** [mapbox/mapbox-gl-native#9812]
Please allow us to set our custom ['my location' move animation time](https://github.com/mapbox/mapbox-gl-native/blob/71e7759a62d3d37817dca9f04aa4bc9df149ad75/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java#L1001) or to set our custom ['my location' tracking behavior](https://github.com/mapbox/mapbox-gl-native/blob/71e7759a62d3d37817dca9f04aa4bc9df149ad75/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java#L981) because sometimes the 'my location' pointer moves really slowly.

**Platform:** Android
**Mapbox SDK version:** 5.1.3

### Expected behavior

Allow the developer to set a custom 'My Location' Pointer Move Animation Time, or to set a custom 'My Location' Tracking Behavior.

### Actual behavior

The 'My Location' Tracking Behavior [is set manually](https://github.com/mapbox/mapbox-gl-native/blob/71e7759a62d3d37817dca9f04aa4bc9df149ad75/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java#L937) by Mapbox, same for [the 'My Location' Pointer Move Animation Time](https://github.com/mapbox/mapbox-gl-native/blob/71e7759a62d3d37817dca9f04aa4bc9df149ad75/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java#L1001).

**Comment by tobrun** [comment]
We are deprecating MyLocationView and related classes in 5.2.0, we are replacing this with MyLocationLayer plugin [here](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/locationlayer). Feel free to report any issues you have in that repo. Closing.

**Comment by dgadelha** [comment]
Thanks @tobrun, I'll upgrade to 5.2.0-SNAPSHOT and play with the plugin to see what I can do.

**Comment by tobrun** [comment]
@dgadelha, you can use the plugin in combination with the 5.1.3 release ;)
