### ISSUE TITLE
Exposing MGLGeometry_Private.h C++ globals

### ISSUE THREAD

**Issue by ambientlight** [mapbox/mapbox-gl-native#9819]
Hi guys,

It would be great to have tile geometry available to a client for feature reconstitution discussed in https://github.com/mapbox/mapbox-gl-native/issues/9647, so I have exposed tile geometry with:

```cpp
/* 
 Returns z/x/y tile id given coordinate belongs to.
 */
MGLTileID MGLTileIDContainingCoordinate2D(CLLocationCoordinate2D coordinate, double zoomLevel){
    
    mbgl::LatLng latLng = { coordinate.latitude, coordinate.longitude };
    const double scale = std::pow(2.0, zoomLevel);
    const mbgl::TileCoordinatePoint point = mbgl::Projection::project(latLng, scale) / double(mbgl::util::tileSize);
    return { uint8_t(zoomLevel), uint32_t(point.x), uint32_t(point.y) };
}

/*
 Returns the coordinate bounds corresponding to z/x/y tile id
 */
MGLCoordinateBounds MGLCoordinateBoundsForTileId(MGLTileID tileID){
    
    const mbgl::TileCoordinatePoint point = { double(tileID.x), double(tileID.y) };
    const mbgl::TileCoordinatePoint nextPoint = { double(tileID.x + 1), double(tileID.y + 1) };
    const double scale = std::pow(2.0, tileID.z);
    
    const mbgl::LatLng nw = mbgl::Projection::unproject(point * double(mbgl::util::tileSize), scale);
    const mbgl::LatLng se = mbgl::Projection::unproject(nextPoint * double(mbgl::util::tileSize), scale);
    
    return MGLCoordinateBoundsMake(CLLocationCoordinate2DMake(se.latitude(), nw.longitude()),
                                   CLLocationCoordinate2DMake(nw.latitude(), se.longitude()));
}
```

in `MGLGeometry_Private.h`, while `MGLTileID` is defined as:

```cpp
/**
 Identifies z/x/y tile.
 */
typedef struct __attribute__((objc_boxable)) MGLTileID {
    uint8_t z;
    uint32_t x;
    uint32_t y;
} MGLTileID;
```

It does work for me when I wrap these functions inside Objective-C++ methods, however I am hitting linker failures when I try exposing them directly as

```cpp
/** Returns z/x/y tile id given coordinate belongs to. */
MGLTileID MGLTileIDContainingCoordinate2D(CLLocationCoordinate2D coordinate, double zoomLevel);

/** Returns the coordinate bounds corresponding to z/x/y tile id. */
MGLCoordinateBounds MGLCoordinateBoundsForTileId(MGLTileID tileID);
```

in `MGLGeometry.h`. 
(ref: https://github.com/GeoThings/mapbox-gl-native/commit/2d6d23b70c9afdd1d06b1fe09695481d900c6ee4)

It feels like I am missing something obvious that I don't know here, any thoughts guys?

**Comment by 1ec5** [comment]
We have no plans to expose any C++ interfaces as part of the iOS or macOS SDK’s public API, because it [would break applications](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md#making-any-symbol-public) written in pure Objective-C or Swift. That said, if there are opportunities to implement these conversions independently in Objective-C, there might be a viable path to adding such an implementation to the public API.

**Comment by ambientlight** [comment]
Yes that is the approach(tile covertion done seperately at my swift/js client side) I actually followed in the end.

**Comment by ambientlight** [comment]
But if something like this:

```ts
// pixel size of tile
const tileSize = 512
const LATITUDE_MAX = 85.051128779806604
const LONGITUDE_MAX = 180
const DEGREES_MAX = 360
const DEGTORAD = Math.PI / 180.0
const RAD2DEG = 180.0 / Math.PI

// taken from mbgl::Projection
export class Projection {

    static worldSize(scale: number): number {
        return 512 * scale
    }

    static project(latLng: LngLat, scale: number): { x: number, y: number } {
        return {
            x: (LONGITUDE_MAX + latLng.lng) * Projection.worldSize(scale) / DEGREES_MAX,
            y: (LONGITUDE_MAX - RAD2DEG * Math.log(Math.tan(Math.PI / 4 + latLng.lat * Math.PI / DEGREES_MAX))) * Projection.worldSize(scale) / DEGREES_MAX 
        }
    }

    static unproject(p: { x: number, y: number }, scale: number): LngLat {
        const p2 = {
            x: p.x * DEGREES_MAX / Projection.worldSize(scale),
            y: p.y * DEGREES_MAX / Projection.worldSize(scale)
        }

        return new LngLat(
            p2.x - LONGITUDE_MAX,
            DEGREES_MAX / Math.PI * Math.atan(Math.exp((LONGITUDE_MAX - p2.y) * DEGTORAD)) - 90.0
        )
    }
}

export class TileID {
    constructor(
        readonly z: number, 
        readonly x: number, 
        readonly y: number
    ){}

    static fromLngLat(lngLat: LngLat, zoomLevel: number): TileID {
        const scale = Math.pow(2, Math.trunc(zoomLevel))
        const projected = Projection.project(lngLat, scale)
        const point = {
            x: projected.x / tileSize,
            y: projected.y / tileSize
        }

        return new TileID(
            Math.trunc(zoomLevel),
            Math.trunc(point.x),
            Math.trunc(point.y)
        )
    }

    get coordinateBounds(): LngLatBounds {
        const point = { x: this.x, y: this.y }
        const nextPoint = { x: this.x + 1, y: this.y + 1}
        const scale = Math.pow(2, this.z)

        const nw = Projection.unproject({ x: point.x * tileSize, y: point.y * tileSize}, scale)
        const se = Projection.unproject({ x: nextPoint.x * tileSize, y: nextPoint.y * tileSize}, scale)

        return new LngLatBounds(new LngLat(nw.lng, se.lat), new LngLat(se.lng, nw.lat))
    }
}
```

is available out of the box - that would be quite helpful certainly.

**Comment by ambientlight** [comment]
But if it will be available in SDK out of the box that would be certainly helpful.

**Comment by ambientlight** [comment]
@1ec5: does it make sense for me to go with a pull request to js/ios sdks?

**Comment by 1ec5** [comment]
Yes, we’d be open to a PR for the iOS and macOS SDKs at least. MGLComputedShapeSource (#6940) introduced x/y/z tile coordinates as a concept. For that feature, we ultimately went with a series of method parameters (e.g., `-invalidateTileAtX:y:zoomLevel:`) instead of a struct. But now that we have APIs that deal in x/y/z and other APIs that deal in coordinate bounds, it does make sense to expose conversion functions publicly.

> We have no plans to expose any C++ interfaces as part of the iOS or macOS SDK’s public API, because it [would break applications](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md#making-any-symbol-public) written in pure Objective-C or Swift.

On second thought, C++ is only a concern because these methods are currently inlined. If we move the implementations of these methods to a .mm file – probably a good idea anyways – then they’d be perfectly compatible with pure Objective-C.
