### ISSUE TITLE
Heading tracking mode idles at 50%+ CPU

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#9822]
**Platform:** iOS 10
**Mapbox SDK version:** iOS v3.6.0-3.6.2

### Steps to trigger behavior

 1. Enable heading tracking mode.
 2. Observe CPU idling at 50-65%, when idle should be 0-1%.

This bisects back to #7716 and 3b109c8540ebd4da943e81beff5d9ae1483500c3.

/cc @frederoni

**Comment by mdakram** [comment]
![screen shot 2017-08-22 at 1 40 42 pm](https://user-images.githubusercontent.com/1751271/29555239-a0f2b548-873f-11e7-9eeb-4eb7f76e2e71.png)
 
Pretty high CPU usage in case heading tracking on Android too.

**Comment by tobrun** [comment]
@mdakram is this with using TrackingSettings/MyLocationView setup on Android? Have you tried the [LocationLayer](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugins/locationlayer) plugin that will deprecate the former?

**Comment by friedbunny** [comment]
@mdakram the issue here appears to be specific to iOS layout code (that’s platform specific), so I would expect any Android performance issues to be unrelated.

**Comment by mdakram** [comment]
@friedbunny May be.

Yes @tobrun i tried LocationLayer too, but it seems CPU usage is due to tile rendering.

**Comment by friedbunny** [comment]
Fixed in #9845, will be in v3.6.3.

@mdakram please go ahead and open a new issue for Android, as this particular issue did turn out to be specific to iOS.
