### ISSUE TITLE
Map scrolling is heavy

### ISSUE THREAD

**Issue by yueno12** [mapbox/mapbox-gl-native#9824]
**Platform:**
iOS

**Mapbox SDK version:**
3.6.2

### Steps to trigger behavior

Scroll on MGLMapView

### Expected behavior
I have checked the same scenario using the older SDK v3.6.0, Scrolling is light.

Map scrolling by Mapbox iOS SDK v3.6.0
https://youtu.be/Yqf7VRKwKXI

### Actual behavior
Scrolling is heavy.

Map scrolling by Mapbox iOS SDK v3.6.2
https://youtu.be/sSxANmSDBr4

**Comment by fabian-guerra** [comment]
Hi @yueno12.

Thank you for using Mapbox. Could you please tell me the iOS version you are using, does this happens once you have downloaded the tilesets?

**Comment by yueno12** [comment]
@fabian-guerra Thanks. 
> Could you please tell me the iOS version you are using

 ios : 10.3.2 
iPhone 5S.

> does this happens once you have downloaded the tilesets?

It is not an offline map. I just displayed an online map.
This is the only source code.
```
Self.mapView.styleURL = [MGLStyle outdoorsStyleURL];
```

**Comment by jfirebaugh** [comment]
Fixed in 73e9ba14390fc5da5c1fb2fc0392accb606e04ff.
