### ISSUE TITLE
Crash on [MGLFillStyleLayer setFillColor:](MGLStyleValue *) -> Assertion failed: (r_ >= 0.0f)

### ISSUE THREAD

**Issue by dahbiahmed** [mapbox/mapbox-gl-native#9826]
**Platform: iOS 10**
**Mapbox SDK version: 3.6.0**

### Steps to trigger behavior

```
let layer = MGLFillStyleLayer(identifier: identifier, source: source)
layer.fillColor = MGLStyleValue(interpolationMode: .exponential, sourceStops: [
            0 : MGLStyleValue(rawValue : UIColor(displayP3Red: 240/255, green: 249/255, blue: 232/255, alpha: 1)),
            10 : MGLStyleValue(rawValue : UIColor(displayP3Red: 186/255, green: 228/255, blue: 188/255, alpha: 1)),
            20 : MGLStyleValue(rawValue : UIColor(displayP3Red: 123/255, green: 204/255, blue: 196/255, alpha: 1)),
            30 : MGLStyleValue(rawValue : UIColor(displayP3Red: 43/255, green: 140/255, blue: 190/255, alpha: 1))
            ], attributeName: "p", options: nil)
```

### Actual behavior
Crash at runtime at `[MGLFillStyleLayer setFillColor:](MGLStyleValue *)`
```
Assertion failed: (r_ >= 0.0f), function Color, file /Users/fabian/Workspace/iOS/mapbox-gl-native/include/mbgl/util/color.hpp, line 16.
```

**Comment by frederoni** [comment]
Even though it looks like your color components are within 0-1 range, when the color gets parsed  [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/src/UIColor+MGLAdditions.mm#L5), using the Display P3 color space, the result of the red color (43/255) will be -0.187814 which triggers an assertion.

Unfortunately, the Display P3 color space is not yet supported. A workaround in the meantime would be to use another color space.

**Comment by dahbiahmed** [comment]
Thanks @frederoni 

I tried some other color spaces that end up not crashing (literalRed or hex) , but not displaying the appropriate color on the map (either completely transparent or another color altogether...).

Is there a best practice we should be following?

**Comment by frederoni** [comment]
RGBA using `UIColor(red:green:blue:alpha:)` is the most tested. Let me know if you are not getting the appropriate color using that method.

**Comment by dahbiahmed** [comment]
Thanks @frederoni it works using `UIColor(red:green:blue:alpha:)`.

It would be great if the behaviour on other color spaces was a warning rather than a crash though? Or maybe mention the compatible color spaces in the documentation?
