### ISSUE TITLE
The Map in jammed when shows many markerView At the same time 

### ISSUE THREAD

**Issue by kkkkxu** [mapbox/mapbox-gl-native#9827]
**Platform:**Android 5.0
**Mapbox SDK version:** 5.1.3

### Steps to trigger behavior

 1.Create Map View
 2.Create 350 MarkerView
 3.Drag the map 

### Expected behavior
Drag the map 
### Actual behavior
Can't drag map， APP seems to happen ANR ，But waiting for ten seconds, such as 350 markerView show success, drag the map normal .

LOG：I/Choreographer: Skipped 301 frames!  The application may be doing too much work on its main thread.

**Comment by tobrun** [comment]
MarkerViews are going to be deprecated in #9365, please use performant alternatives as SymbolLayer and Marker instead.
