### ISSUE TITLE
iOS: Direction indicator is not correct when device is rotated

### ISSUE THREAD

**Issue by millenbop** [mapbox/mapbox-gl-native#9828]
The map rotates properly, as in North is correct independent of device angle. The blue beam, however, indicating the direction the device is facing, is not updated.

It is better described in this video:

https://www.youtube.com/watch?v=dg4lCa57ubA

**Comment by fabian-guerra** [comment]
Hi @millenbop. Thank you for using Mapbox. Could you please tell me the SDK/iOS version you are using?

**Comment by millenbop** [comment]
Yes, of course, sorry. It's been like this for the past year or so, never got around reporting it.

iOS: 8.x, 9.x, 10.x
Mapbox: 3.6.1

**Comment by friedbunny** [comment]
@millenbop to clarify: it appears that you’re physically rotating the device, but that the orientation is locked to landscape?

We [update the heading orientation](https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.6.2/platform/ios/src/MGLMapView.mm#L4687-L4718) when the status bar orientation changes. If the status bar orientation is locked, there’s probably no update.

**Comment by millenbop** [comment]
Yes correct, the app is locked to landscape (both left and right), and there is no status bar orientation change. I use `MGLUserTrackingModeFollowWithHeading` in case it wasn't obvious. 

As I'm still facing the same direction, IMHO the heading should update with the map.

**Comment by friedbunny** [comment]
@millenbop AFAIK, this is behaving as intended — in your video, both the map and heading indicator are rotating to follow the heading. Because the app is locked to landscape, the forward-direction of the device is the righthand side and that’s the direction the map and heading are pointed towards.

If you wanted the heading to reorient when the device is physically rotated to portrait, you would implement support for portrait in your application (and the map would auto-rotate, as you appear to want).

**Comment by millenbop** [comment]
IMHO I still think it's a bug if you just rotate it a little, like 15 degrees, it will show the wrong heading (it will be 15 degrees wrong).

But no worries, it's not that important to me, I just wanted to let you know.

**Comment by friedbunny** [comment]
@millenbop I should also say: thank you for the report, it’s much appreciated. 🙇

> if you just rotate it a little, like 15 degrees, it will show the wrong heading (it will be 15 degrees wrong).

There is a [5° filter on heading updates](https://github.com/mapbox/mapbox-gl-native/blob/ios-v3.6.2/platform/ios/src/MGLMapView.mm#L4182) (well, there will be again after #9845) and if you rotate your device slowly you can see it pause and then jump to the next increment. I’d like to change that to 1° and/or better smooth changes, but that may depend on future camera/concurrent animation improvements.
