### ISSUE TITLE
Why I am getting blank page for Mapboxgl api on IOS?

### ISSUE THREAD

**Issue by rajaa1985** [mapbox/mapbox-gl-native#9830]
Working on **mapboxgl** with **ionic3, angular4 and cordova**.

I have build .apk and .ipa files. I installed .apk file in my android device it works as expected (ie mapbox tiles, my icons (I have added some icons to custom some functionalities for eg. added an icon to switch the map style) and my markers are loaded successfully).

When I install the .ipa file in my Iphone my icons only loaded but mapbox tiles not getting loaded. Also the markers. I get blank white screen.

What is wrong with my implementation?

Note: **I have a doubt here. I think this may be the cause for my defect. Mapboxgl needs WebGL is enabled. Am I right? If so then how can enable WebGL for iOS app. Either I need to configure it in my ionic app itself or need to enable it in my device?**

Please provide me the appropriate solution for this.

**Comment by fabian-guerra** [comment]
Hi @rajaa1985. Thank you for using Mapbox. WebGL is supported on iOS by default you don't need to enable anything else. We don't support any of ionic3, angular4 and cordova. A third party developer made the bindings for cordova. I suggest you look into his website. http://plugins.telerik.com/cordova/plugin/mapbox.

I am closing this since is not related to our mapboxgl or iOS SDK frameworks.

**Comment by rajaa1985** [comment]
This is not related to Ionic3, angular4 and Cordova. I implemented MapboxGL in the above said architecture. One build the .apk it works as expected. But when I build .ipa and install I got a blank page instead of Map. So my question is did I miss anything related to iOS to make it work?

**Comment by fabian-guerra** [comment]
Hi @rajaa1985. If I understand when you say:
> I implemented MapboxGL in the above said architecture

You mean you are using this https://www.mapbox.com/mapbox-gl-js/api/ with Ionic3, angular4 and Cordova right? If so then you are implementing Mapbox with an architecture we don't support.
