### ISSUE TITLE
MarkerViewOptions.infoWindowAnchor seems not to work

### ISSUE THREAD

**Issue by ArLabDev** [mapbox/mapbox-gl-native#9831]
As I understand from documentation infoWindowAnchor should change the anchor point of the infoWindow of the Marker created using MapBox.addMarker( MarkerViewOptions ).

When I use it, the anchor point is always the same and the infoWindow overlays (and hides) the Marker icon

Tested with Android SDK (mapbox-android-sdk:5.1.3) on Android 6.

**Comment by tobrun** [comment]
MarkerViews have been deprecating, closing this as obsolete.
