### ISSUE TITLE
Not found a way to get clicks from Marker creatd with MarkerViewOptions

### ISSUE THREAD

**Issue by ArLabDev** [mapbox/mapbox-gl-native#9832]
When I add a Marker using a MarkerViewOptions object (calling MapBox.addMarker(MarkerViewOptions) )
the callback registered with:

        mMapBoxMap.setOnMarkerClickListener(new MapboxMap.OnMarkerClickListener()
        {
            @Override
            public boolean onMarkerClick(@NonNull com.mapbox.mapboxsdk.annotations.Marker marker)
            {
                // Not called
                return false;
            }
        });

is not called, the same is called if Marker is added with MapBox.addMarker(MarkerOptions) method.

Probably is only a lack of documentation (or my fault in looking into it), but I've found a callback interface:

public interface OnMarkerViewClickListener

that may be related to it, but no way to register a such callback.

**Comment by tobrun** [comment]
`mMapboxMap.getMarkerViewManager().setOnMarkerViewClickListener()`
