### ISSUE TITLE
 Android v4.2.2 release branch

### ISSUE THREAD

**Issue by jthetzel** [mapbox/mapbox-gl-native#9836]
I am looking for the Android v4.2.2 release branch of mapbox-gl-native. #7827 states that it should be available at https://github.com/mapbox/mapbox-gl-native/tree/release-android-v4.2.2 , but that branch does not exist. #8268 suggests Android v4.2.x branches were merged back to master. Searching for merge commits ( https://github.com/mapbox/mapbox-gl-native/search?p=1&q=merge&type=Commits&utf8=%E2%9C%93 ), I see no mentions of a v4.2.2 merge (or any commit containing "4.2.2"). The closest I can get is a v4.2.1 CHANGELOG commit: https://github.com/mapbox/mapbox-gl-native/commit/561694a878c0499c08bd036d0a902e296be8a1d7#diff-303d773d7593cfbdd7331ce896ef36af

I am doing some work in the react-native-mapbox-gl library, which builds off of mapbox-gl-native 4.2.2, and I'd like to read through 4.2.2 source to help debug.

Is there any way to view the v4.2.2 source that react-native-mapbox-gl is using ?
From the react-native-mapbox-gl build.gradle:
`
compile('com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.2@aar') {
        transitive = true
    }
`

**Comment by friedbunny** [comment]
See [the release](https://github.com/mapbox/mapbox-gl-native/releases/tag/android-v4.2.2) and [the tag](https://github.com/mapbox/mapbox-gl-native/tree/android-v4.2.2).
