### ISSUE TITLE
Use traffic style with own data

### ISSUE THREAD

**Issue by Buminta** [mapbox/mapbox-gl-native#9839]
Hi everybody!
I had a problem when i use traffic style layer.
In own maps, i use own styles with mapbox studio and custom data position with right database.
So own styles had something geometry different geometry of OSM data.
Exp: Some road, line, position have position (lat, lng) different position of OSM data.

And now. I wanna use traffic styles layer from mapbox release (Geometry data from OSM). However This styles doesn't mapping with own styles maps.

Photo of example:

![device-2017-08-23-111357](https://user-images.githubusercontent.com/5722956/29598641-48b4c03c-87f4-11e7-9149-5fff45d8c30f.png)

Everybody can help me for mapping traffic styles with right data of own team! I'm thanks so much!

**Comment by jfirebaugh** [comment]
Hi @Buminta, thanks for using Mapbox. If I understand your question correctly, you're asking if you can use Mapbox traffic styles, but with geometries coming from your own datasource. Unfortunately, this isn't something we support. If you need the traffic data to match the underlying roads, you will need to use Mapbox data sources.
