### ISSUE TITLE
Support adding SDF icons in addImage

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-native#9847]
https://github.com/mapbox/mapbox-gl-js/pull/5181 needs port.

**Comment by 1ec5** [comment]
mapbox/mapbox-gl-native#7300 makes use of an existing API to make mbgl interpret an image as an SDF image when adding it to the style. Is there anything left to do here in mbgl?

**Comment by samfader** [comment]
@1ec5 @lbud would this be an appropriate place to mention that there is no Android solution for this as of yet? As in, as far as I can tell, there's no way to add SDF icons via addImage in the Android SDK. Or should that be ticketed separately?

**Comment by tobrun** [comment]
##### Before enabling the sdf flag in Style.addImage:

![device-2018-06-20-133259](https://user-images.githubusercontent.com/2151639/41656167-5a1866b6-748f-11e8-9570-99ce19929146.png)

##### After enabling the sdf flag in Style.addImage + enabling icon-color tinting:

![device-2018-06-20-133844](https://user-images.githubusercontent.com/2151639/41656168-5c0e8f36-748f-11e8-8c54-408577378142.png)

**Comment by curvenut** [comment]
Hi,

    Did you use a SDF image ?
How did you add the SDF image ?
I am trying to do exactly what you are doing without sucess. In fact I dont kown how to create a SDF image.

Thanks for help 

> ##### Before enabling the sdf flag in Style.addImage:
> ![device-2018-06-20-133259](https://user-images.githubusercontent.com/2151639/41656167-5a1866b6-748f-11e8-9570-99ce19929146.png)
> 
> ##### After enabling the sdf flag in Style.addImage + enabling icon-color tinting:
> ![device-2018-06-20-133844](https://user-images.githubusercontent.com/2151639/41656168-5c0e8f36-748f-11e8-8c54-408577378142.png)

**Comment by tobrun** [comment]
@curvenut icons created through Android studio or copied from material spec are sdf compatible. In Android terms, vector drawables are sdf compatible.
