### ISSUE TITLE
Marker is below fillLayer

### ISSUE THREAD

**Issue by yangzhedeID** [mapbox/mapbox-gl-native#9850]
**Platform:Android**
**Mapbox SDK version:v5.1.2**

### Steps to trigger behavior

 1.Add GeoJsonSource
 2.get layer size,add FillLayer and Symbol Layer.
```
int size = mapboxMap.getLayers().size();

for (int i = 0, layersLength = layers.length; i < layersLength; i++) {
 Layer layer = layers[i];

 mapboxMap.addLayerAt(layer, size + i - 1);
}
```
 3. remove FillLayer and Symbol Layer
 4. remove GeoJsonSource
 5. remove markers
 6. Add GeoJsonSource
 7. get layer size,add FillLayer and Symbol Layer.
```
int size = mapboxMap.getLayers().size();

for (int i = 0, layersLength = layers.length; i < layersLength; i++) {
 Layer layer = layers[i];

 mapboxMap.addLayerAt(layer, size + i - 1);
}
```
### Expected behavior

marker is above fillLayer

![filllayerandmarker](https://user-images.githubusercontent.com/6702107/29645960-035782f8-88b3-11e7-8400-b8c3fd6f7158.png)

fillLayer has 0.5f opacity

### Actual behavior

marker is below fillLayer

**Comment by tobrun** [comment]
I don't fully understand what you are trying to achieve with code shown in OP or the expectations you have. If you want your layers to show below Markers please use `MapboxMap#addLayerBelow(fillLayer, ""com.mapbox.annotations.points")`. Let me know if you have any issues with proposed solution.

**Comment by yangzhedeID** [comment]
I want to dynamically increase map data。（FillLayer And marker）

**Comment by yangzhedeID** [comment]
However, the sort of marker goes wrong after the second operation

**Comment by tobrun** [comment]
Please post a full code example if you want additional information. Proposed suggestion to do it differently suggested. Closing for now. Feel free to post any follow up questions you have on StackOverflow or contact us through https://www.mapbox.com/contact/support/
