### ISSUE TITLE
5.2.0-SNAPSHOT CI build failing

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9852]
CI has trouble publishing SNAPSHOT builds when a merge to master occurs. We are hitting `401` http code even though the credentials are correct (works for release branch). Looking into the timeline that this started to show, it seems that the build started to fail once we started to create SNAPSHOT builds for patch releases (eg. 5.1.x versions). I think version number is not taken in account, it tracks when a new version is first build and treats that as latest version. 

Relevant links 
 - https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-android-sdk/5.1.2-SNAPSHOT/
 - https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-android-sdk/5.2.0-SNAPSHOT/

cc @zugaldia

**Comment by zugaldia** [comment]
I found two unpublished releases on Sonatype:

![image](https://user-images.githubusercontent.com/6964/30180410-ca6ed88e-93dd-11e7-8343-7716fad20156.png)

Wonder if that could've been related. Either way, I just dropped them as they were unnecessary. Meanwhile, let's assume we only publish SNAPSHOTS for one version at a time. Sounds good?

**Comment by tobrun** [comment]
@zugaldia having multiple unpublished releases is related to how the current release workflow works. When we prep a release, we alter the branch of the `release-all` target branch and push the changes (this results in publishing a release). Afterwards we run the release script (which results in another push and thus another release). Finally we trigger a build with the script (which results in another release). We need to revisit how we do release now we are running on Circle-CI. 

 > let's assume we only publish SNAPSHOTS for one version at a time. Sounds good?

👍

**Comment by tobrun** [comment]
@zugaldia it seems that #10069 hasn't resolved the issue, still seeing 401 unauthorized, see [build](https://circleci.com/gh/mapbox/mapbox-gl-native/25597). I'm suggesting to move forward with a 5.2.0-beta.1 asap so we have something to point user to.

cc @Guardiola31337
