### ISSUE TITLE
An MGLAnnotationImage backed annotation is not visible if it is animated off-screen and then on-screen

### ISSUE THREAD

**Issue by alisolutions** [mapbox/mapbox-gl-native#9854]
While animating the marker, when marker goes beyond the screen, it remains hide.
The following link is showing the issue.
https://www.dropbox.com/s/7auffog9x9yiuwv/IMG_4792.m4v?dl=0

**Comment by boundsj** [comment]
Thanks @alisolutions for providing the video. Can you please confirm you are using the default visual representation of the annotation (an `MGLAnnotationImage`) by providing one in `-mapView:imageForAnnotation:` or simply not implementing `-mapView:imageForAnnotation:` (or `-mapView:viewForAnnotation:`)? Also, can you please let us know the Mapbox iOS Maps SDK version you are using?

**Comment by alisolutions** [comment]
I am using Marker annotation, in Xamarin Android. 
Do you need the code which i am using to animate the Marker?

**Comment by boundsj** [comment]
> I am using Marker annotation, in Xamarin Android.

Thanks for the additional information. I could've sworn the video you linked to was of an iOS device!

In any case, this project does not officially support Xamarin. If you feel that you've discovered a bug in one of the supported, native SDKs and can provide relevant details then please feel free to re-open or file an issue separately.
