### ISSUE TITLE
[Android] Polyline is not shown when update points using ValueAnimator

### ISSUE THREAD

**Issue by viettanbkdn** [mapbox/mapbox-gl-native#9857]
**Platform: Android 7.1.1**
**Mapbox SDK version: 5.1.3**

### Steps to trigger behavior

 1. Create a polyline with 0 points:
`Polyline polyline = mapboxMap.addPolyline(new PolylineOptions().color(Color.RED).width(context.getResources().getDimensionPixelSize(R.dimen.line_width)))`
 2. Use `ValueAnimator` to update `Polyline` points from `0` to `size`:

```
        ValueAnimator valueAnimator = ValueAnimator.ofInt(0, size);
        valueAnimator.setDuration(3000);
        valueAnimator.setInterpolator(new LinearInterpolator());
        valueAnimator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override public void onAnimationUpdate(ValueAnimator valueAnimator) {
                int position = (int) valueAnimator.getAnimatedValue();
                Log.d(TAG, "onAnimationUpdate: " + position);
                if (position < size - 1) {
                    List<LatLng> points = polyline.getPoints();
                    points.addAll(line.subList(points.size(), position));
                    polyline.setPoints(points);
                }
            }
        });
        valueAnimator.start();
```

### Expected behavior
Polyline should show and animate its length from start point to end point

### Actual behavior
Polyline is not shown on map

**Comment by cjkiller** [comment]
Looks like you cannot add a polyline with zero points. So you'll just have to add it when there's two or more points to add. Source code:

    Polyline addPolyline(@NonNull PolylineOptions polylineOptions, @NonNull MapboxMap mapboxMap) {
    Polyline polyline = polylineOptions.getPolyline();
       if (!polyline.getPoints().isEmpty()) {
         long id = nativeMapView != null ? nativeMapView.addPolyline(polyline) : 0;
         polyline.setMapboxMap(mapboxMap);
         polyline.setId(id);
         shapeAnnotationIds.add(LAYER_ID_SHAPE_ANNOTATIONS + id);
         annotations.put(id, polyline);
       }
       return polyline;
    }
