### ISSUE TITLE
Disable use of secure environment variables in non-organization-member pushes

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-native#986]
Testing pull requests on Travis from non-organization members fails: https://travis-ci.org/mapbox/mapbox-gl-native/builds/54087275

This is because our build script depends on the existence of the secure variables, but they are disabled for pushes originating from other users. We should detect the presence of these variables and skip all parts of the build that requires these.

**Comment by ljbade** [comment]
Hmm I recall there is a Travis environment variable that indicated when there are no encrypted variables

**Comment by friedbunny** [comment]
Bottom of http://docs.travis-ci.com/user/environment-variables/

> To make the usage of secure environment variables easier, we expose info on their availability and info about the type of this build:

>`TRAVIS_SECURE_ENV_VARS` is set to "true" or "false" depending on the availability of environment variables
>`TRAVIS_PULL_REQUEST`: The pull request number if the current job is a pull request, "false" if it's not a pull request.

**Comment by jfirebaugh** [comment]
We're not building PRs currently because it overloads Travis too much, so this is moot.
