### ISSUE TITLE
maxZoom difference with gl-js

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9860]
When adding a vector source and zooming in, I'm noticing a difference between `gl-native` and `gl-js`. It seems that gl-native does a hard stop at the set maxZoom value while gl-js continous to display.

See this [gl-js fiddle](https://jsfiddle.net/5ct7pcpo/1/) for the gl-js behaviour.

Below a gif and code of the gl-native behaviour:

![ezgif com-video-to-gif 21](https://user-images.githubusercontent.com/2151639/29710386-5440d308-8990-11e7-821b-bbf9bb6c4a7b.gif)

```java
        map.addSource(new VectorSource(Mapillary.ID_MAPILLARY, new TileSet("2.1.0", Mapillary.URL_TILESET)));
        LineLayer lineLayer = new LineLayer(Mapillary.ID_MAPILLARY, Mapillary.ID_MAPILLARY);
        lineLayer.setMinZoom(0);
        lineLayer.setMaxZoom(14);
        lineLayer.setSourceLayer(Mapillary.SOURCE_LAYER);
        lineLayer.setProperties(
          lineCap(Property.LINE_CAP_ROUND),
          lineJoin(Property.LINE_JOIN_ROUND),
          lineOpacity(0.6f),
          lineWidth(2.0f),
          lineColor(Color.GREEN)
        );
        map.addLayerBelow(lineLayer, "aerialway");
```

This was tested with android 5.1.3 (release branch) and the visibility changes when we hit maxZoom = 14.

**Comment by tobrun** [comment]
Capturing from #9863, also occurs on iOS. Removing android label.

**Comment by asheemmamoowala** [comment]
@tobrun - in your example code - the layer max zoom is set to 14, which means geometry will be hidden starting at that zoom level.

When a vector tile source is constructed with a TileSet that does not explicitly specify a `maxZoom`, the default value used is zoom 20. In your example, the tile server is either not returning tiles or returning empty tiles beyond zoom 14.
