### ISSUE TITLE
External MBTiles preloaded with app

### ISSUE THREAD

**Issue by BharathMG** [mapbox/mapbox-gl-native#9861]
Hi,

Is it possible to preload the external generated MBTiles with the app and set it as a tile source in Mapbox SDK? Or Is there an alternative way? Thanks!

**Comment by kkaefer** [comment]
Mapbox GL doesn't support MBTiles files. You can use [Offline Packs instead](https://www.mapbox.com/help/mobile-offline/).

**Comment by BharathMG** [comment]
@kkaefer  Thanks for your reply. I've already been using Offline manager but could not find a way to preload offline tiles with the app. Can you recommend any way or point me to doc on that?
