### ISSUE TITLE
Android Mapbox : How to Load tiles from sd card of the mobile[offline]

### ISSUE THREAD

**Issue by MADHUSUDHANRAO527** [mapbox/mapbox-gl-native#9873]
I am new to mapbox android.I am able to place tiles from json. But How can i load tiles from internal storage/SD card of the mobile.

I am using below code for local storage - which is not working

RasterSource chicagoSource = new RasterSource("chicago-source", new TileSet("tileset", "asset://" + Environment.getExternalStorageDirectory().getAbsolutePath()
                        + "/OverlayTiles/{z}/{x}/{y}.png"));
                mapboxMap.addSource(chicagoSource);

                RasterLayer chicagoLayer = new RasterLayer("chicago", "chicago-source");
                mapboxMap.addLayer(chicagoLayer);
I am able to load from project assets folder - using below code, it might help someone

RasterSource chicagoSource = new RasterSource("chicago-source", new 
TileSet("tileset","asset://OverlayTiles/{z}/{x}/{y}.png"));
                        mapboxMap.addSource(chicagoSource); 
mapboxMap.addSource(chicagoSource);

                RasterLayer chicagoLayer = new RasterLayer("chicago", "chicago-source");
                mapboxMap.addLayer(chicagoLayer);

**Comment by tobrun** [comment]
@MADHUSUDHANRAO527 instead of `asset://` you should use `file://` as base. We currently don't have an example for this in place. Putting on my list to add. Going a head and close this issue as your question should be answered. Let us know if you run into any issues with this.

**Comment by MADHUSUDHANRAO527** [comment]
thanks @tobrun its working now
