### ISSUE TITLE
improve z-ordering of annotations

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#988]
Related to https://github.com/mapbox/mapbox-gl-js/issues/470, we want annotations to sort in the `z` direction from top to bottom of screen, like Apple's. 

![](https://cloud.githubusercontent.com/assets/32314/3320227/535003f4-f728-11e3-98c3-11b70bedfd4b.PNG)

*Not like this*

@jfirebaugh Can you take an initial look at how complicated this will be?

**Comment by jfirebaugh** [comment]
Not critical for Beta 1.

**Comment by incanus** [comment]
Here's the MapKit-like default algorithm used in our iOS SDK: 

https://github.com/mapbox/mapbox-ios-sdk/blob/dd26736adb6c2769accb99bd687509a0119780d6/MapView/Map/RMMapView.m#L3119-L3181

**Comment by incanus** [comment]
Hitting this for b2, but this is how things look in the shipping style: 

![ios simulator screen shot mar 21 2015 5 27 24 pm](https://cloud.githubusercontent.com/assets/17722/6767486/a17c5848-cfef-11e4-9c3d-a256cc5f932d.png)

**Comment by ansis** [comment]
This will be easy to implement once we can redo placement on rotation: https://github.com/mapbox/mapbox-gl-js/commit/5bf094f7c26ebe2730f258b2ac5cef1ca804767d

Spec issue here: https://github.com/mapbox/mapbox-gl-style-spec/issues/274

**Comment by ansis** [comment]
This is implemented in -js https://github.com/mapbox/mapbox-gl-js/pull/1184
We should port the same approach to -native. It should be ported to the `new-labelling` branch.

**Comment by incanus** [comment]
@ansis label porting work in https://github.com/mapbox/mapbox-gl-native/pull/1666 hits this.
