### ISSUE TITLE
Android Mapbox : How to Load tiles from sd card of the mobile[offline]

### ISSUE THREAD

**Issue by MADHUSUDHANRAO527** [mapbox/mapbox-gl-native#9880]
I am new to mapbox android.I am able to place tiles from json. But How can i load tiles from internal storage/SD card of the mobile.
I am using below code for local storage - which is not working

    RasterSource chicagoSource = new RasterSource("chicago-source", new TileSet("tileset", "asset://" + Environment.getExternalStorageDirectory().getAbsolutePath()
                        + "/OverlayTiles/{z}/{x}/{y}.png"));
                mapboxMap.addSource(chicagoSource);

                RasterLayer chicagoLayer = new RasterLayer("chicago", "chicago-source");
                mapboxMap.addLayer(chicagoLayer);

**Comment by tobrun** [comment]
Capturing from https://github.com/mapbox/mapbox-gl-native/issues/9873#issuecomment-325605350 that you were able to make it work with using `file://` instead of `asset://`. Closing.
