### ISSUE TITLE
[android] Explore CircleCI Git Tag Job Execution to better support automated releases

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-gl-native#9887]
First class tag support for Workflows in CircleCI was announced recently 🎉 
We could take advantage of [CircleCI Git Tag Job Execution](https://circleci.com/docs/2.0/workflows/#git-tag-job-execution) to better support our automated releases and make the process more pleasant/easier.

cc/ @tobrun

**Comment by tobrun** [comment]
Closing this in favor of https://github.com/mapbox/mapbox-gl-native/issues/9887, that issue also has iOS as label.

**Comment by Guardiola31337** [comment]
@tobrun 
> Closing this in favor of #9887, that issue also has iOS as label.

What issue? #9887 is this ticket.
