### ISSUE TITLE
clarify platform directory structure

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-native#989]
Due to the current folder structure, it can be quite confusing which files are part of the internal API (virtual classes and such) and which are platform-specific implementations.

- [include/mbgl/storage/default_file_source.hpp](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/storage/default_file_source.hpp)
- [src/mbgl/storage/default_file_source.cpp](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/storage/default_file_source.cpp)
- [include/mbgl/storage/file_cache.hpp](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/storage/file_cache.hpp)
- [include/mbgl/storage/default/sqlite_cache.hpp](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/storage/default/sqlite_cache.hpp)

This causes confusion like https://github.com/mapbox/node-mapbox-gl-native/issues/99, so I'm proposing that we move ALL implementation files into the platform directory to avoid this.

**Comment by jfirebaugh** [comment]
Agreed. I'm working on this in https://github.com/mapbox/mapbox-gl-native/pull/899 and will get back to it after the iOS Beta release.

**Comment by mikemorris** [comment]
Ack, didn't see that, closing this as a dupe.
