### ISSUE TITLE
Small Polygon layer are not always displayed - iOS and Android

### ISSUE THREAD

**Issue by paulVulog** [mapbox/mapbox-gl-native#9898]
Hi, 

When I want to display small GeoJson Polygons, from times to times, they are not displayed at all. iOS and Android are affected. 
You will find below some working / not working code and some workarounds (android version): 

```
// code to create Layer and associated source
mapboxMap.addSource(new GeoJsonSource("polygon_source"));
mapboxMap.addLayer(new FillLayer("polygon_layer","polygon_source"));

// code to update the source with a FeatureCollection.
FeatureCollection data = FeatureCollection.fromJson("My_GeoJson_Here");
mapboxMap.getSourceAs("polygon_source").setGeoJson(data);
```

Here is the result whe you replace "My_GeoJson_Here".
(all Json can be directly copy/past here for test [GeoJson](http://geojson.io/))

Let's start with some zone Sample around Paris : 
Eiffel Tower:
[2.2945064306259155,48.8574728849071],[2.2957026958465576,48.858274060261955],[2.2944849729537964,48.85905051753278],[2.2933155298233032,48.858252883985834],[2.2945064306259155,48.8574728849071]

Notre-Dame Cathedral:
[2.3489096760749817,48.853060896621066],[2.3506075143814087,48.85254731591993],[2.350875735282898,48.8529602987543],[2.3492342233657837,48.85348799408518],[2.3489096760749817,48.853060896621066]

Charles-De-Gaule Airport:
[2.522563934326172,48.9846107158526],[2.640151977539062,48.99204537731004],[2.5924301147460938,49.0306652257167],[2.4779319763183594,49.02424942553418],[2.522563934326172,48.9846107158526]

World :
[1.8E+2,9E+1],[1.8E+2,-9E+1],[-1.8E+2,-9E+1],[-1.8E+2,9E+1],[1.8E+2,9E+1]

If we addthe zone in a FeatureCollection and pass it instead of "My_GeoJson_Here", we get the following : 

Eiffel + Notre-Dame :
{"features":[{"geometry":{"coordinates":[[[2.2945064306259155,48.8574728849071],[2.2957026958465576,48.858274060261955],[2.2944849729537964,48.85905051753278],[2.2933155298233032,48.858252883985834],[2.2945064306259155,48.8574728849071]],[[2.3489096760749817,48.853060896621066],[2.3506075143814087,48.85254731591993],[2.350875735282898,48.8529602987543],[2.3492342233657837,48.85348799408518],[2.3489096760749817,48.853060896621066]]],"type":"Polygon"},"properties":{"name":"Home Zone"},"type":"Feature"}],"type":"FeatureCollection"}

Result OK : 
![Ok normal image](https://preview.ibb.co/cZWXMk/normal.png)

Eiffel + Notre-Dame + world:
{"features":[{"geometry":{"coordinates":[[[1.8E+2,9E+1],[1.8E+2,-9E+1],[-1.8E+2,-9E+1],[-1.8E+2,9E+1],[1.8E+2,9E+1]],[[2.2945064306259155,48.8574728849071],[2.2957026958465576,48.858274060261955],[2.2944849729537964,48.85905051753278],[2.2933155298233032,48.858252883985834],[2.2945064306259155,48.8574728849071]],[[2.3489096760749817,48.853060896621066],[2.3506075143814087,48.85254731591993],[2.350875735282898,48.8529602987543],[2.3492342233657837,48.85348799408518],[2.3489096760749817,48.853060896621066]]],"type":"Polygon"},"properties":{"name":"Home Zone"},"type":"Feature"}],"type":"FeatureCollection"}

Now we add a "world" zone. (hack to display polygon holes :) )
Result KO (no visible zone) : 
![Ok normal image](https://preview.ibb.co/n1oOSQ/world_KO.png)

Eiffel + Notre-Dame + world + CDG:
{"features":[{"geometry":{"coordinates":[[[1.8E+2,9E+1],[1.8E+2,-9E+1],[-1.8E+2,-9E+1],[-1.8E+2,9E+1],[1.8E+2,9E+1]],[[2.2945064306259155,48.8574728849071],[2.2957026958465576,48.858274060261955],[2.2944849729537964,48.85905051753278],[2.2933155298233032,48.858252883985834],[2.2945064306259155,48.8574728849071]],[[2.3489096760749817,48.853060896621066],[2.3506075143814087,48.85254731591993],[2.350875735282898,48.8529602987543],[2.3492342233657837,48.85348799408518],[2.3489096760749817,48.853060896621066]],[[2.522563934326172,48.9846107158526],[2.640151977539062,48.99204537731004],[2.5924301147460938,49.0306652257167],[2.4779319763183594,49.02424942553418],[2.522563934326172,48.9846107158526]]],"type":"Polygon"},"properties":{"name":"Home Zone"},"type":"Feature"}],"type":"FeatureCollection"}

result is OK if we add a Big zone (workaround 1):
![Ok normal image](https://preview.ibb.co/cEgXMk/world_ok.png)

As a second workaround, If I change the tolerance GeoJsonOption value, it works fine with the Eiffel + Notre-Dame + world data :

```
GeoJsonOptions opt = new GeoJsonOptions();
opt.withTolerance(0.001f);
mapboxMap.addSource(new GeoJsonSource("polygon_source"), opt);
```

What is the issue with small GeoJson Polygons? 
Thx.

**Comment by captainbarbosa** [comment]
I'd double check that your polygons are following [proper winding order](https://www.mapbox.com/vector-tiles/specification/#winding-order) - you may want to use a tool such as [geojson-rewind](https://github.com/mapbox/geojson-rewind) to verify this.

As a side-note, you may also be ok dropping the precision of each coordinate you're working with, [as noted here](https://tools.ietf.org/html/rfc7946#section-11.2).

**Comment by stonetip** [comment]
Looks like the winding order is the issue. Running one of your samples through geojson-rewind produced:

`{"features":[{"geometry":{"coordinates":[[[180,90],[-180,90],[-180,-90],[180,-90],[180,90]],[[2.294506,48.857472],[2.293315,48.858252],[2.294484,48.859050],[2.295702,48.858274],[2.294506,48.857472]],[[2.348909,48.853060],[2.349234,48.853487],[2.350875,48.852960],[2.350607,48.852547],[2.348909,48.853060]]],"type":"Polygon"},"properties":{"name":"Home Zone"},"type":"Feature"}],"type":"FeatureCollection"}`

which worked just fine, verified @ http://geojsonlint.com/

Also, note the reduction to 6 decimal places. This will greatly decrease file sizes (even when compressed as pbf, as with mbtiles) while still giving you 1-m accuracy.
