### ISSUE TITLE
get rid of white side bars on device rotation

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#990]
Piggybacking off of https://github.com/mapbox/mapbox-gl-native/pull/838's fix in https://github.com/mapbox/mapbox-gl-native/commit/8cc1c00a96d5afe531b33cf3ed62c4ec910ecd75, we should figure out if we need to fake a view snapshot or similar in order to prevent unsightly bars during orientation changes. 

Per @bleege this might not be essential. 

> BTW, I just looked at Google Maps on iOS and it has the same momentary white flicker on rotation too.

**Comment by incanus** [comment]
@bleege Want to take a crack at this?

**Comment by bleege** [comment]
Sure!

**Comment by bleege** [comment]
Should be good to go... waiting on Travis build to Green light it.

**Comment by incanus** [comment]
Oh wow, it was as simple as this?

**Comment by bleege** [comment]
Woo hoo Travis just green barred!  Time to merge!

**Comment by incanus** [comment]
Fixed in #994.
