### ISSUE TITLE
Performance issue in compiling mapbox-gl-native and launching MapboxGLAndroidSDKTestApp

### ISSUE THREAD

**Issue by mappy-mobile** [mapbox/mapbox-gl-native#9903]
Hello

Our project can't update to the MapBox V5.1 or higher because of the performance issue. The global performance has been downgraded since mapbox5.1 and particularly bad with Genymotion emulator.

In fact if we compile the `mapbox-gl-native` from github and launch the `MapboxGLAndroidSDKTestApp` from Android Studio, we have the performance problem.

However if we use your compiled version as below, we can launch the application, there isn't any performance issue.

compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.2@aar') {
transitive=true
}

Your `mapbox-android-demo` project from `github` doesn't have this performance issue.

We compile the mapbox-gl-native from github on iMac.
Could you please let me know there was any configuration special if we compile the `mapbox-gl-native` from iMac. Noted that we didn't have this performance problem until the version 5.1

**Comment by mappy-mobile** [comment]
We tried to always force the mapbox compilation in Release mode as below

dependencies {
    compile(project(**path':MapboxGLAndroidSDK', configuration:'release'**)) {
        transitive = true
    }
    ... 
}

Then the performance issue is resolved.
We now can update to the mapbox5.1.3, however we lost the mapbox debug capacities in developing. It's could be great if you could see the debug compilation issue.

**Comment by jfirebaugh** [comment]
Hi @mappy-mobile -- I'm afraid this is the inherent tradeoff with debug versus release builds: debug builds give you additional error checking and debuggability, but that necessarily comes at the cost of performance. That behavior isn't specific to Mapbox GL.

**Comment by mappy-mobile** [comment]
Hi @jfirebaugh thanks for your reply. I know that on debug mode is less performance than on release mode. But from the release MapBox V5.1, we can't work on the debug mode anymore. So I wonder that could be a disqualification from mapbox 5.0 up to mapbox 5.1 ?
