### ISSUE TITLE
Black screen on Desire 500 Plus Model MT6580M, Marshmallow, SDK 23

### ISSUE THREAD

**Issue by wohaooinit** [mapbox/mapbox-gl-native#9904]
@zugaldia,   @chrisvoll, @springmeyer   Hello,
I'm having a black screen issue on one phone and not on the other.
On My ASUS Phone everything works fine; the map shows up as expected.
However on my other Mediatek phone a Desire 500 Plus, the map only shows black.
Here is the Droid Info output for the Desire 500 Plus:
- Memory  2GB
- Processor: ARM v7 rev 3, 4 Cores
-OpenGL version: ES 2.0
-Renderer: Mali-400 MP
-Chipset: MT6560M
-Android SDK version: 23
-OS Version: Android 6.0

The fact is I include the map inside a View, itself inside a FrameLayout, embedded in a subclass of the Activity class (For some technical reason, I cannot use the AppCompatActivity).

It use to work until last Monday.

I read it could be an issue with SSL certificates. I couldn't verify it.
As the Mapbox Demo app (downloaded from Google Play) works just fine.
I can't seem to see any error on logcat, though.
Is there a way to make mapbox more verbose?

Here is the initialization code:
 `//getContext because we are inside a view
       Mapbox.getInstance(this.getContext(), this.getContext().
                getString(R.string.access_token));
        LayoutInflater inflater = LayoutInflater.from(super.getContext());
        XXXXXXDialogBinding binding = DataBindingUtil.inflate(inflater,
                R.layout.xxxx_xxxx_dialog, this, true);

        View rootView = binding.getRoot();

        //Initialize map as normal
        mapView = (MapView) rootView.findViewById(R.id.mapView);

        mapView.onCreate(savedStateOrCreated);

        mapView.getMapAsync(new OnMapReadyCallback() {

            @Override @Traceable
            public void onMapReady(MapboxMap map) {
                //Store for later
                mapboxMap = map;

            }
        });`
In the layout XML:
`<com.mapbox.mapboxsdk.maps.MapView
                android:id="@+id/mapView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_below="@+id/layout_top"
                mapbox:mapbox_styleUrl="@string/mapbox_style_mapbox_streets"
                mapbox:mapbox_cameraZoom="14"/>`

mapbox_style_mapbox_streets=mapbox://styles/mapbox/streets-v10

Any clue?

**Comment by jfirebaugh** [comment]
What SDK version? (In the future, please use the provided issue template when filing issues, to save us both time on questions like this.)

**Comment by wohaooinit** [comment]
Gradle configuration:
`// Mapbox dependencies
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.3@aar') {
        transitive = true
        exclude group: 'com.android.support', module: 'design'
        exclude group: 'com.android.support', module: 'appcompat-v7'
        exclude group: 'com.android.support', module: 'support-v4'
        exclude group: 'com.android.support', module: 'recyclerview-v7'
    }
    // Mapbox Android UI
    // Mapbox Navigation SDK for Android
    // Mapbox Android Services
    compile('com.mapbox.mapboxsdk:mapbox-android-services:1.1.0@aar') {
        transitive = true
    }
    compile('com.mapbox.mapboxsdk:mapbox-android-geocoder:1.0.0@aar') {
        transitive = true
    }
   compile 'com.mapbox.mapboxsdk:mapbox-android-ui:2.2.3'
   compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.1.0'`

**Comment by wohaooinit** [comment]
SOLVED!
The error was the overlapping of multiple views with mapbox MapView embedded inside the same FrameLayout!
For the record, we decided to stick with Mapbox for the following Key Selling Points:
1. Zero to no setup time (no need for keytool certificate etc)
2. Absolutely Zero loading time.
3. Mapbox' unbeatable MarkerView/MarkerViewAdapter allowing you to EASILY place Views/Animations inside Map markers!

For all these good things, thank you guys!
