### ISSUE TITLE
Android: annotation not visible in offline mode

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#9909]
I'm using the latest stable Android sdk. Everytime map will become idle, I show some annotations (markers) on the map. This works fine. But when I download an offline area and disable network connection, markers will not show all the time when map becomes idle. Sometimes marker appear, sometimes not. I use a custom style. Is this a known issue?

UPDATE: this problem occurs only when using MarkerView instead of Marker... When I use Marker, everything works fine.

**Comment by Guardiola31337** [comment]
@nijs9 thank you for reaching out and reporting your problem.

Could you add some more information on how you're implementing ☝️ (downloading, adding the markers, defining the custom style, etc.)? Are you able to provide a full use case example? If there is any sample or pseudo code you can provide, that would be really helpful.

**Comment by nijs9** [comment]
Thanks for your reply @Guardiola31337 .

Each time camera becomes idle, I rund this code:

`map.setOnCameraIdleListener(new MapboxMap.OnCameraIdleListener() {
                    @Override
                    public void onCameraIdle() {

                        new showVisibleNodesOnMap().execute();

                    }
                });`

In the async task (in the onPostExecuteMethod of showVisibleNodesOnMap) I add MarkerViews to the map:

`for (Node knooppunt : result) {


                    Gson gson = new Gson();

                    BitmapDrawable drawable = getDrawable();

                    Icon icon = iconFactory.fromBitmap(drawable.getBitmap());


                    nodesOnMap.add(map.addMarker(new MarkerViewOptions()
                            .position(new LatLng(knooppunt.getLocation().getLatitude(), knooppunt.getLocation().getLongitude()))
                            .title("knooppunt")
                            .anchor(0.5f,0.5f)
                            .snippet(gson.toJson(knooppunt))
                            .icon(icon)



                    counter ++;

                }`

Strange enough this works very nice when device is online. But when I go offline and scroll the map, markers are not visible on the map. Only when I start scrolling the map, I can see them a short time and then they disapear again.

**Comment by tobrun** [comment]
MarkerView is going to be deprecated with https://github.com/mapbox/mapbox-gl-native/pull/9782. We are no longer maintaining this API and will remove it in future versions of the SDK. As noted in the deprecation message. We are advising users to leverage SymbolLayer instead (you can use the sample code in #9782 to convert Android SDK views to an Image to be used as a Symbol). While we no longer maintain the API we are happy to accept any PRs on it.
