### ISSUE TITLE
allow for annotation selection z-order change

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#991]
Piggybacking off of https://github.com/mapbox/mapbox-gl-native/issues/988, when you mark an annotation as selected, it should come to the front of the z-order. This is how MapKit behaves. For state tracking, we can do that per-platform (such as determining whether single or multiple selection is allowed), but we need to be able to change individual ordering on demand for the visual component. 

Need to see how difficult this might be in the shaders in #988 first.

**Comment by jfirebaugh** [comment]
Not critical for Beta 1.

**Comment by incanus** [comment]
I think it is — try using Maps.app a bit with 8-10 annotations in overlapping proximity. As you tap the clump, each is selected in rotating order, coming to the front. So there are two things going on here: 

* Iteration among nearby point annotations to allow selection without zooming in (maybe not b1 material)
* Bringing the selected annotation to the front

Not having this alters the usability of annotations significantly.

**Comment by incanus** [comment]
Here's an example of what this looks like in our SDK: 

![](https://www.mapbox.com/guides/img/pages/ios/markers.png)

(from https://www.mapbox.com/guides/station-finder-part-2/)

This doesn't show the inability to select this annotation because it's obscured, but that would be the case for any near the center of the map.

**Comment by incanus** [comment]
> Not critical for Beta 1.

:+1: per offline discussion.

**Comment by mb12** [comment]
Is it possible to share what is the approximate date when all checkins for iOS beta1 will be in master repo?

**Comment by incanus** [comment]
We are shooting for very soon, likely early next week.

**Comment by incanus** [comment]
@kkaefer is starting to investigate more robust annotations in b3 and beyond.

**Comment by cupofjoakim** [comment]
@incanus Any updates on when this might be implemented?

**Comment by boundsj** [comment]
Hi @cupofjoakim please note that work on UIView based annotations is happening in https://github.com/mapbox/mapbox-gl-native/pull/4801 and is expected to land in the next release. z-order of UIViews can be done with Cocoa APIs. 

However, for use cases requiring many thousands of annotations displayed concurrently, we are still planning to keep the existing GL annotations API. Z ordering for GL annotations requires a runtime styling API and that is tracked in https://github.com/mapbox/mapbox-gl-native/issues/837

**Comment by 1ec5** [comment]
With #5264, we send an annotation view to the front when it is selected. #5264 doesn’t address non-view-backed annotations (GL point annotations); that functionality would depend on #837.

If you need to adjust the z-order of a specific annotation view beyond the functionality implemented in #5264, such as sending an annotation view to the back when the user deselects it, #5287 unblocks a simple approach to doing so using standard UIKit APIs; see https://github.com/mapbox/mapbox-gl-native/pull/5287#issue-159247473 for details.

**Comment by kythanh** [comment]
Hi @1ec5, I still having the problem with z-index of Annotation below.
 
<img width="246" alt="screen shot 2016-07-03 at 12 28 59 am" src="https://cloud.githubusercontent.com/assets/869405/16541728/8b03be16-40b5-11e6-9b02-a9333054d4bf.png"> 

Do you know what is final solution to fix it? Updated the latest Mapbox v3.2.3 from Fabric seem no helped.

Thanks.

**Comment by 1ec5** [comment]
@kythanh, the fix for this issue was added in #5264, which is in [v3.3.0-beta.2](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.3.0-beta.2). It’ll be available via Fabric once we release v3.3.0 in a week or so.

**Comment by sunzuhan** [comment]
Is annotation z-order api supported now? 
Or when will this been done?
