### ISSUE TITLE
Android: markers sometimes black and splitted

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-native#9910]
I'm using Android SDK 5.1.3 and I'm running into the same problem as https://github.com/mapbox/mapbox-gl-native/issues/8943 (markers are black and splitted sometimes). I know there is a workarround (creating icon outside the loop), but when you have to draw different markers this workarround is useless. Is there any other solution for this?

**Comment by Guardiola31337** [comment]
Hey @nijs9 👋

We're moving from an Android SDK View to a core implementation. Progress on the implementation in #9782 

As a workaround, you could implement that behavior from your side 👀 the implementation details in #9782 or wait until that PR lands.

Eventually, that will be implemented as a plugin 👉 https://github.com/mapbox/mapbox-plugins-android/issues/7

**Comment by nijs9** [comment]
Hi @Guardiola31337

Thanks for your reply. Any idea when this PR will land :-)? It's not clear to me how to impoement this :-).

**Comment by Guardiola31337** [comment]
> Any idea when this PR will land :-)?

@zugaldia you requested changes, do you know when #9782 will be ✅?

**Comment by zugaldia** [comment]
> @zugaldia you requested changes on #9782, do you know when it'll be ✅?

We don't have an ETA to share yet as we still need to decide on the vehicle to ship that feature. It can either be on the next major/minor release (unticketed yet) or shipped as a standalone plugin. Note in any case that this alternative approach (workaround if you wish) https://github.com/mapbox/mapbox-gl-native/pull/9782 is built on top of our existing runtime styling API. You could use the code on that PR to build your own solution meanwhile.

**Comment by jfirebaugh** [comment]
Should be fixed in v5.2.0.
