### ISSUE TITLE
Qt plugin can't import offline data

### ISSUE THREAD

**Issue by CMGeorge** [mapbox/mapbox-gl-native#9915]
**Platform: OSX**
**Mapbox SDK version: latest master branch, 5.1 beta...**

### Steps to trigger behavior
Use: Qt SDK 5.9.2, 5.9.3,5.10
Or recompile the plugin using the latest branch
Compile the offline file

### Expected behavior
Open and use the offline database
### Actual behavior
Cached data are displayed, the offline one not.
Investigate the issue, I found this difference into the database (Top Cached information, bottom information retrieved by offline tool)
![screen shot 2017-09-01 at 11 13 28](https://user-images.githubusercontent.com/4266604/30064457-85cca2f8-925a-11e7-9c50-a471fcb5d85f.png)
I tried a lot until I found that difference. Using sqlite3 command line everything looks correctly, some standard database utility, the same. 
I hade by mistake the readonly version of a SQLite browser got from apple store ( https://itunes.apple.com/us/app/sqlpro-for-sqlite-read-only/id635299994?mt=12 ) and found that information from SQLite is displayed different.
Looks like the Qt plugin is using the Qt SQLite library for inserting and reading data and the native MapBox is using is own method.

**Comment by jfirebaugh** [comment]
How are you creating the offline regions? What does "Compile the offline file" mean?

**Comment by CMGeorge** [comment]
Offline file... I want to say the tool to generate the offline database https://github.com/mapbox/mapbox-gl-native/blob/master/bin/offline.cpp
If you are looking to the image I posted, on top you can see how url_template is inserted by the Qt SQLite engine.
On the bottom is how the C++ SQLite engine from mapboxgl inserted data.
Looks to be something related to encoding at the Qt plugin level.

**Comment by brunoabinader** [comment]
Qt-based offline tool implementation proposed in #10427.

**Comment by brunoabinader** [comment]
Fixed in #10430.
