### ISSUE TITLE
Convenient snapshot wrappers

### ISSUE THREAD

**Issue by frederoni** [mapbox/mapbox-gl-native#9916]
Snapshots are currently returned as plain UIImage & Bitmap objects.
A convenient wrapper for these resources that converts between the image and the map view’s coordinate system would make it easier to overlay annotations and images on the snapshots.

On the iOS/macOS side, this would mean adding a `MGLMapSnapshot` and a `-[MGLMapSnapshot pointForCoordinate:]`.

@ivovandongen @fabian-guerra @tobrun

**Comment by zugaldia** [comment]
cc: @Guardiola31337 for visibility on the Android side.
