### ISSUE TITLE
GIF Animation and Scale PIN - iOS SDK

### ISSUE THREAD

**Issue by jevonch** [mapbox/mapbox-gl-native#9922]
Hello,

I want to use animate PIN and do the zoom animation like in MGLCircleStyleLayer and MGLSymbolStyleLayer. How do I implement it?

I have tried some alternatives but failed. Here the alternatives:
1. [self.mapView.style setImage:[UIImage sd_animatedGIFWithData:data] forName:@"name"];
When I use this, NO animation in the PIN, but the zoom effect become circle is working
2. use - (MGLAnnotationView *)mapView:(MGLMapView *)mapView viewForAnnotation:(id <MGLAnnotation>)annotation
I created annotations, and the PIN can be animated and using gif.I add UIImageView as subview in annotationView. but the zoom effect is NOT working. 

What should I do to achieve my goal?
PLease help me

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
