### ISSUE TITLE
Android: Mapbox SDK Download onto SD Card

### ISSUE THREAD

**Issue by tcolligan-ap** [mapbox/mapbox-gl-native#9929]
Currently using Mapbox with it's offline download feature successfully. Want to be able to add a feature to my app that allows users to choose whether the map pack is downloaded to their SD card or internal storage and the loaded appropriately.

Is this possible? Have not seen any examples (in the sample app) or specific documentation that would help me to figure this out. Any direction on resources of how to accomplish this would be very helpful.

**Comment by tobrun** [comment]
@tcolligan-ap adding the feature label as this is currently not supported. The database is currently placed in the app shell under the files folder and we do not allow an arbitrary path. You can though add configurations to your manifest as `android:installLocation="preferExternal"` to move the app shell to the SD card.

**Comment by tobrun** [comment]
just came accross the following configuratin, which I forgot we added:

```
         <meta-data 
         android:name="com.mapbox.SetStorageExternal" 
         android:value="true" /> 
```

With this enabled, your external storage will be used instead of the internal. 

Closing as this feature is already exposed.

**Comment by tcolligan-ap** [comment]
@tobrun How do I leverage this? I put that in my Application xml file? Is there a more dynamic way to control that feature?

**Comment by tobrun** [comment]
Yes, you can add that inside your AndroidManifest.xml file inside the application tag. 
We currently don't allow dynamically changing this as it would require us to have migration in place.
