### ISSUE TITLE
Custom userAnnotation Image

### ISSUE THREAD

**Issue by ciaosonokekko** [mapbox/mapbox-gl-native#9932]
**Platform:iOS Swift 3
**Mapbox SDK version:3.6 (Installed via CocoaPods)

hi, i need to customize the userAnnotation icon, i want to replace the default icon (circle) with custom image (car icon). I'm using swift3 with ios SDK, i've read that is possibile but i can't find the way to do that. Can someone help me?

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
