### ISSUE TITLE
Disallow expressions for text-font, or require fontstacks to be listed up front

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-native#9939]
One of the components of an offline region download is the complete set of glyph range PBFs for all the font stacks used by that region's style. We currently determine the set of font stacks via this method:

https://github.com/mapbox/mapbox-gl-native/blob/aa4dff1095e8f5e8ad584f5f7dcab3e61d8cf8ee/src/mbgl/style/parser.cpp#L271-L294

This will fail for `text-font` properties that use an expression. We need to either disallows the use of expressions for `text-font`, or introduce a new top-level style spec property that explicitly declares all the font stacks that the style uses (or at least the font stacks that should be available offline).

cc @anandthakker

**Comment by anandthakker** [comment]
@jfirebaugh as an in-between compromise, we could allow expressions of some tightly constrained form for `text-font`, such that we could implement the equivalent of the above code to collect the possible values from literals in the expression.

**Comment by nickidlugash** [comment]
> we could allow expressions of some tightly constrained form for text-font

Could expressions that only include literally values be allowed? I think the most common use cases for expressions for `text-font` would mainly just involve literally values (e.g. in `match` expressions and/or `zoom` curves).

**Comment by anandthakker** [comment]
Yeah, along the lines of @nickidlugash's point, one way to formulate this restriction that seems pretty reasonable both to implement and communicate:

_`text-font` expressions must have a finite number of output values.  I.e., varying expressions like `[zoom]`, `[get, property_name]`, `[id]` may not be used to construct the output value for a `text-font` expression._

So `[ "concat", "Wingdings", ["match", ["get", "font-weight"], "regular", "", "bold", " Bold"]]` would fail validation with the above error message, but `[ "match", ["get", "font-weight"], "regular", "Wingdings", "bold", "Wingdings Bold"]` would pass.

**Comment by jfirebaugh** [comment]
That also sounds more restrictive than what @nickidlugash wants. E.g., it disallows things like `["curve", ["step"], ["zoom"], "Stack A", 4, "Stack B"]`.

**Comment by jfirebaugh** [comment]
So long as `text-font` allows only feature-constant expressions, static analysis can determine the bounded set of possible output values. If we allow `text-font` to have feature-varying expressions, then some expressions will be ok (e.g. `["match", ["get", "foo"], "a", "Stack A", "Stack B"]`), while others will not (`["get", "stack"]`). Still, static analysis should be able to tell when the set of possible output values is unbounded, and we can disallow those cases.
