### ISSUE TITLE
Pinch zoom changes camera position

### ISSUE THREAD

**Issue by kjkrum** [mapbox/mapbox-gl-native#9946]
I have disabled all gestures except zoom because I don't want the user to directly control the camera position.  Pinch zooming off center allows the camera position to be changed.  I can see how this would be intuitive under normal circumstances, because pinch zoom normally means zoom _here_.  Perhaps its behavior can be modified when pan gestures are disabled.

Using Android SDK 5.1.3.

**Comment by tobrun** [comment]
@kjkrum you can work around this issue by specifying your own focal point (the center point where gestures work around). You can provide your own focal point with:

```
mapboxMap.getUiSettings().setFocalPoint(new PointF(mapview.getWidht()/2, mapview.getHeight()/2)
```

Let us know if you have any issues with this approach. We are bit reluctant adding more business logic to gesture handling for such specific use-cases. Going a head and close this as a workaround was provided.
