### ISSUE TITLE
Android SDK should use cache directory to store cached tiles

### ISSUE THREAD

**Issue by arashpayan** [mapbox/mapbox-gl-native#9949]
Platform: Android
Mapbox SDK version: 5.1.3

### Steps to trigger behavior

 1. Integrate Mapbox SDK into your app
 2. Use the MapView in your app

### Expected behavior
The Mapbox database cache should be stored in the app's `cache` directory (retrieved by calling [getCacheDir](https://developer.android.com/reference/android/content/Context.html#getCacheDir())), so it can be easily evicted by the OS when more disk space is needed. Additionally, this prevents it from being backed up with the user data.

### Actual behavior
The Mapbox database cache is being stored along with user data in the app's `files` directory. This causes unnecessary growth in the disk space used by the app.

**Comment by kkaefer** [comment]
The reason this isn't stored in the cache directory is that offline packs are stored in the same database, and we don't want offline packs to get randomly deleted by the OS.

**Comment by jfirebaugh** [comment]
See also #9929 for changing the directory location.

**Comment by arashpayan** [comment]
Thanks for the quick feedback.

Is there a way to programmatically delete the cache? My app doesn't work offline, so in lieu of using the cache directory, I can just delete the mapbox db from time to time.
