### ISSUE TITLE
can't stop stopUpdatingLocation

### ISSUE THREAD

**Issue by iwjs** [mapbox/mapbox-gl-native#9952]
dear mabox , I have a problem here is that, is my app used
     [MGLAccountManager setAccessToken: accessToken]; After that, my app is always in the positioning of active, can not, even if the standby does not do any operation, there will be battery power loss, but if I do not add this, my standby time, My battery loss is zero, do you have any way to make the app in the use of time to open, when not off, such as when I use the built-in positioning, startUpdatingLocation will open positioning, but when I stopUpdatingLocation You can close off my location server, this time I app the power consumption is reduced

**Comment by friedbunny** [comment]
Thanks for your report, but we do not offer support on this repo. If you have a bug to report, please follow the guidelines and provide the requested information.
