### ISSUE TITLE
LatLngBounds with one point

### ISSUE THREAD

**Issue by emerciercontexeo** [mapbox/mapbox-gl-native#9953]
**Platform: Android **
**Mapbox SDK version: 5.1.3**

Create a LatLngBounds with one point trigger an exception (Cannot create a LatLngBounds with one position)

Create a LatLngBounds with two point with same coordinates works.

It should be considered to let user creates a bounds including only one point or improve the exception behavior. #

**Comment by tobrun** [comment]
@emerciercontexeo could you elaborate on a use-case where you want bounds represented as a single point? You are correct that current behaviour allows duplicating points, we should ignore adding such points to the bounds.

**Comment by emerciercontexeo** [comment]
There is no really use-case. I tested this morning to see how the camera will be set with one point in bounds and I found this behavior.

It was priceless to share it with you :)
