### ISSUE TITLE
Annotation randomly added under raster layer

### ISSUE THREAD

**Issue by emerciercontexeo** [mapbox/mapbox-gl-native#9954]
**Platform:Android**
**Mapbox SDK version:5.1.3**

 1. Add raster layer to the map
 2. Add annotation (Polygon or Marker) on the map at coordinates covered by the raster layer

### Expected behavior
Annotation should be always display on top of the raster layer

### Actual behavior
Sometime, annotation are added under the raster layer and then are not visible.

I will try to make a screen shot of this issue as soon as the bug came back.

In my application, I add raster layer and draw polygon and marker annotation on it. In most of execution, everything gone right but sometime, marker and polygon are displayed under the raster layer.

Thanks to the randomness, it's pretty hard to reproduce.

**Comment by tobrun** [comment]
@emerciercontexeo which method are you using to add the layer to your map? 
You can do something as:

`mapboxMap#addLayerBelow(yourRasterLayer, "com.mapbox.annotations.points")`

which will add your layer below the Marker layer.

**Comment by emerciercontexeo** [comment]
Oh my bad!

I used addLayerBelow to organize my own layers but I supposed that annotation was drawn on top of all others layers.

I will try with your method.

Thanks.
