### ISSUE TITLE
Map is unusably slow in ios 11 beta Xcode 9 simulator

### ISSUE THREAD

**Issue by JesseCrocker** [mapbox/mapbox-gl-native#9959]
**Platform:** iOS
**Mapbox SDK version:** master@dfc5d51ae150b92ce2645d34383f04361d784bc3 Xcode Version 9.0 beta 6 (9M214v)

### Steps to trigger behavior

 1. Launch sample app
 2. pan map

### Expected behavior
Map pans smoothly

### Actual behavior
Map is extremely slugish

**Comment by boundsj** [comment]
Thanks for the report @JesseCrocker. 

Noting that I've been working with Xcode 9 b6 a lot and have not noticed extreme slowness of the operation of the Mapbox map view in the simulator. We will watch for this issue though.

**Comment by friedbunny** [comment]
This is evidently an endemic issue for the Xcode 9 simulator — Maps.app is, I daresay, even worse. 😬

**Comment by JesseCrocker** [comment]
Im seeing this issue in the sample app, and in my own applications.
Possibly relevant info: Im using a retina iMac, but the simulator is running on a second screen that is not retina.

**Comment by boundsj** [comment]
@JesseCrocker I do see this. I think I had tested in the simulator in an earlier beta and I've just been using a device recently and did not notice the regression.

As @friedbunny noted, this appears to be an issue with betas of Xcode 9 after beta 3. [This thread](https://forums.developer.apple.com/thread/83570) has more details including a workaround that I've not tried (and may not actually help much according to the comments).

A radar has been filed and it would be helpful to file additional radars with Apple and duplicate the ones noted here: https://github.com/lionheart/openradar-mirror/issues/18093.

Let's leave this issue open for tracking purposes and hope that this gets fixed before the GM release of Xcode!

cc @bsudekum

**Comment by mmase** [comment]
Also noticing this, as well as macOS demo app as well. It's just very sluggish zooming and panning. Far from smooth.

**Comment by perekstig** [comment]
I can confirm that SpriteKit also is very slow. Runs in 2.1 fps instead of about 40 fps. Totally useless. Then I downloaded a simulator running iOS 10.3.1. And to my big surprise it runs ok! So the problem is not Xcode 9, the problem is the iOS 11 simulators.

**Comment by boundsj** [comment]
Noting that the Xcode 9 GM did not fix this issue.

**Comment by kuchmiyalex** [comment]
That's not Mapbox - even MapKit is soo laggy..

**Comment by mmase** [comment]
Maybe, but separate issue. Even compiled and archived macOS have this performance problem whereas Maps.app does not.

**Comment by chefnobody** [comment]
FWIW the first public release of Xcode 9 did not resolve the issue. Here's the radar: https://openradar.appspot.com/radar?id=6138518606708736

**Comment by JasonGore** [comment]
Apple's own Maps app in iOS 11 simulator DOES exhibit this issue.

**Comment by lagst3r** [comment]
I am having the same issue with the official XCode 9 + iOS 11 Simulator.
- Gesture panning is very sluggish and not responsive.
- Map panning animation is very sluggish when executed programmatically.

**Comment by friedbunny** [comment]
This is [officially confirmed](https://twitter.com/xenadu02/status/911463433521860609) to be an issue with Xcode 9.0 and its iOS 11 simulator — it affects any OpenGL-using application.

Various hacky workarounds exist, such as [this one](https://twitter.com/xenadu02/status/911463504732839937) suggested by the same Xcode team member:

> This is entirely unsupported but you can copy libCoreVMClient.dylib from beta 3 into the GM and it will restore performance.

**Comment by hongchaozhang** [comment]
The workaround from [Apple forum](https://forums.developer.apple.com/thread/83570) works for me.

**Comment by blackjack75** [comment]
I must say this isn't map related. My SpriteKit app went from relatively slow compared to real device to < 1 FPS.

**Comment by asetiyadi** [comment]
What a life saver this workaround is!!!

Replace the following file with beta 3 or before version:
Xcode[-beta].app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/OpenGLES.framework/libCoreVMClient.dylib

**Comment by hungnq89vn** [comment]
Could anyone please upload the file libCoreVMClient.dylib from Beta 3 here so I can download and fix the issue with my Xcode 9? 

I couldn't seem to find anywhere to download Xcode 9 beta 3 to acquire the file.

**Comment by asetiyadi** [comment]
Not sure if this is beta 2 or 3, but works for me.  Here is the attached file.

[libCoreVMClient.dylib.zip](https://github.com/mapbox/mapbox-gl-native/files/1344769/libCoreVMClient.dylib.zip)

**Comment by hungnq89vn** [comment]
@asetiyadi Awesome. Thanks, mate! It worked for me.

**Comment by friedbunny** [comment]
It’s definitely frustrating that this bug continues to exist, but please do not redistribute Apple software here.

This issue has run its course and the cause has been identified as beyond the scope of this project. Let’s cross our fingers and hope for an official fix in Xcode 9.1.

**Comment by 1ec5** [comment]
From the Xcode 9.1 release notes:

> * Fixes an issue in Simulator that impacted the performance of OpenGL ES and maps
