### ISSUE TITLE
propose splitting map subfolder into map & data

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#996]
It's getting unwieldy with things since #928 and with work on #893. 

![screen shot 2015-03-12 at 4 27 03 pm](https://cloud.githubusercontent.com/assets/17722/6630363/593342a2-c8d5-11e4-970c-b72b124f2f44.png)

I propose moving the following into `<mbgl/data/...>`: 

* `*_tile.*` (4)
* `*_tile_data.*` (8)
* `*_tile_parser.*` (4)
* `tile.*` (2)

This would leave in `<mbgl/map/...>`: 

* `environment.*` (2)
* `map.*` (2)
* `source.*` (2)
* `sprite.*` (2)
* `transform*.*` (4)
* `view.*` (2)

I can handle this as part of #893 since I'm starting to add some `Annotation*` classes as well. 

/cc @kkaefer @jfirebaugh

**Comment by jfirebaugh** [comment]
Sound fine, but we don't need to do this right now.

**Comment by kkaefer** [comment]
Agree with @jfirebaugh
