### ISSUE TITLE
Android: Failed to load sprite error

### ISSUE THREAD

**Issue by haydenkaizeta** [mapbox/mapbox-gl-native#9963]
**Platform:**
Android (Any API)
**Mapbox SDK version:**
5.1.3
### Steps to trigger behavior

 1. Attempt to use custom MapStyle

### Expected behavior
Some reasonable way of finding where the error is and why it is happening

### Actual behavior
Error shown in console:
`E/mbgl: {llygoandroidapp}[Style]: Failed to load sprite: HTTP status code 404`

This error also seems to cause the map render listener to not return `MapView.DID_FINISH_RENDERING_MAP_FULLY_RENDERED`.

This error does not affect the iOS SDK as our custom MapStyle works fine with it. I would like to know steps to diagnose what the problem is, or if this is a fault with the Mapbox Android SDK.

**Comment by jfirebaugh** [comment]
This error indicates that attempting to load the [sprite URL](https://www.mapbox.com/mapbox-gl-js/style-spec/#root-sprite) in your style returned a 404. If your style does not use symbol icons, then you should remove the `sprite` property; otherwise you need to provide a valid URL.
