### ISSUE TITLE
TileSet downloading out of bounds tiles

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9964]
TileSet exposes an API to set a bounds:

eg.
```java
    static Source createSource(LatLngBounds bounds) {
      TileSet mapillaryTileset = new TileSet("2.1.0", Mapillary.URL_TILESET);
      mapillaryTileset.setMinZoom(0);
      mapillaryTileset.setMaxZoom(14);
      mapillaryTileset.setBounds(
        (float)bounds.getSouthWest().getLongitude(),
        (float)bounds.getSouthWest().getLatitude(),
        (float)bounds.getNorthEast().getLongitude(),
        (float)bounds.getNorthEast().getLatitude()
      );
      return new VectorSource(Mapillary.ID_SOURCE, mapillaryTileset);
    }
```

This configuration should prevent downloading tiles outside of the provided bounds. 
In the screenshot below it should only load tiles in the black square.

![device-2017-09-12-083238](https://user-images.githubusercontent.com/2151639/30311431-780ac45c-9795-11e7-8bad-d501015bb2dd.png)

I traced the java code and seeing the bounds correctly converted to the value object (wasn't able to debug the c++ code from the mapbox demo app).

**Comment by jfirebaugh** [comment]
Duplicate of #5394?

**Comment by tobrun** [comment]
yes, closing.
