### ISSUE TITLE
Data requests when app is backgrounded

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-native#9965]
Users have reported seeing data requests occurring when the app has been backgrounded (the Activity is in an paused state). One example given was the download of a sprite (eg. sprite@2x.png) which occured when the app has been backgrounded for a couple of hours. Ideally we stop requesting resources when `onPause` occurs and only resume downloads when we hit `onResume`.

**Comment by kkaefer** [comment]
It's likely that this happens because resources expire while the app is still running in the background. When a resource expires, we try to reload/refresh it.

**Comment by kkaefer** [comment]
@tobrun `DefaultFileSource` has the ability to `pause`: https://github.com/mapbox/mapbox-gl-native/blob/8e01f52dd212c57646a9b0fa1c65039a003b78cc/include/mbgl/storage/default_file_source.hpp#L126-L140

Are we calling this when the app goes to the background?

**Comment by tobrun** [comment]
Thank you for :eyes: @kkaefer, we aren't atm, will fix this up.

**Comment by tobrun** [comment]
This landed in 5.2.0
