### ISSUE TITLE
Android: although i use MarkerView.setVisible(false) ,the markView can also click on map

### ISSUE THREAD

**Issue by AlexLiuSheng** [mapbox/mapbox-gl-native#9971]
I want to hide a makerView on map.So I used `markerView.setVisible(false)` to hide. although the markView is hided , the markView can also be clicked on map.And the InfoWindow can pop up on map.Is it a bug?
following is the version of mapbox that I use :
`com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.1@aar`

**Comment by tobrun** [comment]
@AlexLiuSheng this can be considered a bug but we are no longer maintaining the MarkerView API and we are deprecating it in https://github.com/mapbox/mapbox-gl-native/pull/9782. Feel free to provide a PR handling this use-case.
