### ISSUE TITLE
Text from floating point data rounding error

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-native#998]
Hello,

we're seeing some issues with text rendering in the iOS client. See screenshot bellow of iOS:

![ios simulator screen shot 13 mar 2015 09 24 16](https://cloud.githubusercontent.com/assets/5638107/6635185/267f1582-c963-11e4-8138-7e615cbb66a6.png)

the same place in the js-client:

![screenshot 2015-03-13 09 29 22](https://cloud.githubusercontent.com/assets/5638107/6635215/8418ce86-c963-11e4-9009-26d933635750.png)

The depth soundings are fetched from the tile data with "text-field": "{}". The data is initially is from a single precision float column in a postgis db. The data is rounded to one decimal in the database using round(field::numeric, 1). The JS client handles this as expected, but the native iOS client does not.

Also, the text has some overflow issues, where it bleeds as illustrated on the picture. This only happens when these floating point issues are onscreen.

Let me know if you need more info.

**Comment by kristfal** [comment]
Bit more info on the font bleed issue:

Not only does the font "bleed" but characters may be randomly changed as well: 

![ios_simulator_screen_shot_13_mar_2015_10 59 04](https://cloud.githubusercontent.com/assets/5638107/6637711/200f490e-c97e-11e4-93bf-10577fb434a9.png)

The font rendering only overflows at high zoom levels, and the threshold corresponds to the zoom levels where the depth soundings (which has the rounding issues) are present. Zooming to lower levels alleviates the issue.

**Comment by kkaefer** [comment]
This looks like an issue of #957 for which we have a pull request open in #995

**Comment by kristfal** [comment]
@kkaefer: Great, I'll let you know and close it if that solves this issue. 

But do you still think it will fix the rounding value issue, or is it separate?

**Comment by friedbunny** [comment]
Unrelated, but those dashed lines look distorted and too thick on iOS. The red ones particularly. Is that stock OSM, @kristfal? If you can share the location, I'd like to poke around a bit with those lines (and maybe see about the odd rounding).

**Comment by kristfal** [comment]
@friedbunny It's not stock, all custom data. I can give you access and run you through our findings in detail if you'd like. Here is the overview:

Dashed lines took a hit on both iOS and js when style spec 7 rolled out. It was much more consistent before that. Right now, we're seeing quite different things in Chrome, Safari and on iOS. 

Iirc, the best way of spotting this is to do line-cap round, line-width 5+, and a dash of 2,2 maybe 3,6 or thereabouts.

In addition, there are pretty large rendering errors in Safari at high zoom with small dashed values.

Didn't know how finished the cross-platform implementation was, and we worked around the issue by finding values that was ok across all clients, so haven't posted an issue on it. Let me know how you want it reported and I'll put something up on Monday when I have my work equipment at hand.

**Comment by friedbunny** [comment]
@kristfal I can't speak for the Mapbox folks (who are quite busy!), but personally it'd be worthwhile to see what's happening with the dashes. This may be related to #779 or #780, both of which came around the time of the v7 styles.

**Comment by ljbade** [comment]
Hmm @ansis might be familiar with the line rendering changes in v7.

**Comment by incanus** [comment]
@kristfal How does your style fare in recent versions of `master`? Is this still an issue?

**Comment by kristfal** [comment]
@incanus: with regards to rounding of float numbers or dashed lines (or both)?

**Comment by incanus** [comment]
Both, though if it still exists, we should separate the dashed lines issue into a separate ticket to track.

**Comment by kristfal** [comment]
@incanus:

Floating point rounding is still present in Master from yesterday. I can't find any issues with dashed lines any more – native and gl looks pretty similar, if not identical.

-native floating point issue:

![ios simulator screen shot 30 apr 2015 11 59 40](https://cloud.githubusercontent.com/assets/5638107/7410601/a260955c-ef30-11e4-8440-4df72ad72682.png)

-js V0.7 on iPhone6:

![img_1107](https://cloud.githubusercontent.com/assets/5638107/7410695/95a84d0e-ef31-11e4-925e-3f219be3c19f.PNG)

-native Master of yesterday on iPhone6:

![img_1108](https://cloud.githubusercontent.com/assets/5638107/7410698/99b29120-ef31-11e4-8114-758384dc5663.PNG)

**Comment by friedbunny** [comment]
Looks like I took this ticket off course ages ago, but the core floating point rounding error for labels still exists.

I suspect the issue is coming from our use of `boost::lexical_cast()` in [`util::toString()`](https://github.com/mapbox/mapbox-gl-native/blob/a88e58ef3a90225fcfafca1efab996de6a827b72/include/mbgl/util/string.hpp#L17), initiated [here](https://github.com/mapbox/mapbox-gl-native/blob/a88e58ef3a90225fcfafca1efab996de6a827b72/src/mbgl/renderer/symbol_bucket.cpp#L114) in `SymbolBucket::parseFeatures()`.

@ansis perhaps you have time to look at this? Let me know in chat and I can provide a style+dataset that reproduces the issue.
