### ISSUE TITLE
The pinch to zoom function doesn't perform great

### ISSUE THREAD

**Issue by giperwlad** [mapbox/mapbox-gl-native#9985]
Hello,

Some of our users are unhappy that  the pinch to zoom function on their devices doesn't perform great. It pivots/rotates the map more than it zooms. On some devices, it is more difficult to zoom the map than on others devices. 
Our testers were able to reproduce this.
Maybe it's a device problem?

Platform:  Nexus 5, android 6.0.1, Nexus 5x, ONEPLUS A3000
Mapbox SDK version: 5.1.3

**Comment by tobrun** [comment]
This has been fixed with 5.1.4 with https://github.com/mapbox/mapbox-gl-native/pull/10026
