### ISSUE TITLE
Mapbox showing broken marker after some times

### ISSUE THREAD

**Issue by JigneshTank** [mapbox/mapbox-gl-native#9988]
**Platform:** Android 
**Mapbox SDK version:** 5.1.0

### Steps to trigger behavior

 1. Android app is showing the different markers on map
 2. When 1 marker's icon is shown big, app makes other marker's icon small
 3. If step#2 is repeated for many times, mapbox starts showing broken markers.
![mapbox-distorted-markers](https://user-images.githubusercontent.com/25880682/30375307-b3f3fd2e-98a5-11e7-99fd-7f9ac5e9535a.png)

### Expected behavior
Mapbox should show full markers without any distortion

### Actual behavior
Mapbox shows distorted markers

**Comment by tobrun** [comment]
@JigneshTank 
Thank you for reporting this issue:
 - could you add some code how you are reproducing this issue?
 - could you try testing this with a more recent version (eg. v5.1.3)?

**Comment by JigneshTank** [comment]
Hi,

Thank you for replying.

---> could you add some code how you are reproducing this issue?

I am iterating through all markers to make selected marker big and rest all small.

for (Marker marker : markerList) {

                        if(marker!=null){
                            if (bigMarkerPositon == markerList.indexOf(marker)) {
                                marker.setIcon(IconFactory.getInstance(getActivity()).
                                        fromResource(ResourceUtil.getBigMarker()));
                            }else{
                                marker.setIcon(IconFactory.getInstance(getActivity()).
                                        fromResource(ResourceUtil.getSmallMarker()));
                            }
                        }
                    
                    }
                        


--> could you try testing this with a more recent version (eg. v5.1.3)?

I tried just now with 5.13 but same issue.

Hope above information will help you. 

Thanks,
Jignesh

**Comment by tobrun** [comment]
@JigneshTank 

executing the following line multiple times will result in behavior shown in OP.
```java
IconFactory.getInstance(getActivity()).fromResource(ResourceUtil.getBigMarker()
```
to resolve this issue you need to cache the icon.

```java
private Icon bigIcon;
private Icon smallIcon;

....

if (bigIcon == null) {
   bigIcon = IconFactory.getInstance(getActivity()).                                       fromResource(ResourceUtil.getBigMarker();
}

if (smallIcon == null) {
   smallIcon = IconFactory.getInstance(getActivity()).                                        fromResource(ResourceUtil.getSmallMarker();
}

for (Marker marker : markerList) {
        if(marker!=null){
             if (bigMarkerPositon == markerList.indexOf(marker)) {
                    marker.setIcon(bigIcon));
            }else{
                   marker.setIcon(smallIcon));
            }
        }
 }
      
```

Above will not only resolve the issue, it will also be faster and less memory hungry. 
Closing as this is a known issue + workaround was given.

**Comment by JigneshTank** [comment]
Hi,

This works perfectly for me.  Thank you so much for your prompt help.

-Jignesh
